### ISSUE TITLE
Activity.SpanId is 0000000000000000 on .NET Framework

### ISSUE THREAD

**Issue by jamescrosswell** [dotnet/runtime#100329]
### Description

Activities returned by `ActivitySource.StartActivity` and `ActivitySource.CreateActivity` don't have fields like SpanId initialized. 

### Reproduction Steps

Build the following against a .NET Framework target (e.g. `net48`) and run it (I'm using mono, as I'm on a mac):

```csharp
using System.Diagnostics;
using System.Runtime.InteropServices;

var listener = new ActivityListener()
{
    // This is only for internal Sentry events
    ShouldListenTo = (source) => source.Name.StartsWith("ConsoleApp9"),
    Sample = (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllData,
    ActivityStarted = activity => Console.WriteLine($"Started activity {activity.SpanId}"),
    ActivityStopped = _ => { }
};
ActivitySource.AddActivityListener(listener);

var tracer = new ActivitySource("ConsoleApp9");

Console.WriteLine("Framework: {0}", RuntimeInformation.FrameworkDescription);
Console.WriteLine("Starting activity...");
var data = tracer.StartActivity("foo");
Console.WriteLine($"Stopping activity {data?.SpanId}");
data?.Stop();
```

### Expected behavior

I'd expect to see non-zero SpanIds written to the console, similar to what I see when running the code in .NET 8:

```csharp
Framework: .NET 8.0.2
Starting activity...
Started activity 07cf31b8b4e65543
Stopping activity 07cf31b8b4e65543
```

### Actual behavior

When targeting net48 and running using mono, none of the IDs are initialized:

```
Framework: Mono 6.12.0.199 (2020-02/f648ec1e0a6 Wed Jun 14 09:24:35 EDT 2023)
Starting activity...
Started activity 0000000000000000
Stopping activity 0000000000000000
```

### Configuration

.NET Framework 4.8 running on macOS (M2/Arm64) using mono with `System.Diagnostics.DiagnosticSource 8.0.0`.

**Comment by huoyaoyuan** [comment]
.NET Framework compatible mono is maintained at https://github.com/mono/mono . Generally it's unlikely to get new feature. We also suggest to use .NET 5+ natively on non-Windows platform

**Comment by teo-tsirpanis** [comment]
This behavior is by design. `Activity.SpanId` gets a non-zero value only if the activity ID format is `W3C`. [The default is `W3C` since .NET 5](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/default-activityidformat-changed), but even in new versions of the `System.Diagnostics.DiagnosticSource` package, [the new defaults only apply when your app is running on modern .NET](https://github.com/dotnet/runtime/pull/37686#:~:text=This%20breaking%20change%20will%20be%20applied%20to%20.NET%205.0%20only.), and it keeps using the older `Hierarchical` format on .NET Framework.

You can switch to the modern .NET defaults by writing `Activity.DefaultIdFormat = ActivityIdFormat.W3C;` at the start of your program.

**Comment by jamescrosswell** [comment]
> You can switch to the modern .NET defaults by writing `Activity.DefaultIdFormat = ActivityIdFormat.W3C;` at the start of your program.

Fantastic - thanks @teo-tsirpanis ! That did the trick 👍🏻
