### ISSUE TITLE
CI doesn't build `net9.0` targets in source generators.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#100346]
A while back we added `net9.0` targets to the source generator projects so that they support nullability annotations. These aren't being used by the product but help with local development. We discovered with https://github.com/dotnet/runtime/pull/100345 that these targets aren't being built by CI, so it's easy for them to be broken.

cc @ViktorHofer

**Comment by huoyaoyuan** [comment]
My local development environment lacks SG in VS currently, which is annoying when developing interop-heavy code. Sounds related to this?

**Comment by ericstj** [comment]
Shouldn't be.  These SG builds aren't meant to be run anywhere.  Just built to validate nullable annotations.

If SG's aren't working in your dev environment it's probably because you're using a VS that's older than the compiler toolset we're using and they are failing to load.  Make sure you're on a preview VS with the 9.0 preview SDK installed.
