### ISSUE TITLE
something.Where(predicate).FirstOrDefault() is faster than something.FirstOrDefault(predicate)

### ISSUE THREAD

**Issue by Treit** [dotnet/runtime#100378]
See the benchmark results here: 

https://github.com/Treit/MiscBenchmarks/tree/main/WhereFirstOrDefaultVsFirstOrDefault

![image](https://github.com/dotnet/runtime/assets/8271812/13b03d14-d9b1-4b0d-85e7-580891cdec3f)

In a recent code review someone pointed out that we should change calls to `something.Where(somePredicate).FirstOrDefault()` to just be `something.FirstOrDefault(somePredicate)`

Much to my surprise, benchmarks show this is significantly slower, at least in the worst case where the thing being searched for is at the end of the list.

**Comment by vcsjones** [comment]
Duplicate of #30119 and https://github.com/dotnet/runtime/issues/19382#issuecomment-734524103

**Comment by neon-sunset** [comment]
Since then LINQ has received extensive optimizations. This issue effectively suggests to address the discrepancy between [WhereListIterator specialization](https://github.com/dotnet/runtime/blob/ccc2d3b6253c47e1ec7b49223cea92f29bfde5fa/src/libraries/System.Linq/src/System/Linq/Where.SpeedOpt.cs#L284-L299) and a [lack of its counterpart on FirstOrDefault](https://github.com/dotnet/runtime/blob/ccc2d3b6253c47e1ec7b49223cea92f29bfde5fa/src/libraries/System.Linq/src/System/Linq/First.cs#L105-L129).

In particular, it is an issue as the analyzer will actively suggest to simplify expressions of `list.Where(condition).FirstOrDefault()` to just `list.FirstOrDefault(condition)`. Performance regression in this case will be unexpected and may lead to yet another case of "you have to know how to use the LINQ right", which may not be desirable.

Given that this likely will be guarded behind similar size opt flag like other iterators for size-sensitive targets, perhaps this can be reconsidered?

**Comment by eiriktsarpalis** [comment]
> . This issue effectively suggests to address the discrepancy between [WhereListIterator specialization](https://github.com/dotnet/runtime/blob/ccc2d3b6253c47e1ec7b49223cea92f29bfde5fa/src/libraries/System.Linq/src/System/Linq/Where.SpeedOpt.cs#L284-L299) and the [lack of its counterpart on FirstOrDefault](https://github.com/dotnet/runtime/blob/ccc2d3b6253c47e1ec7b49223cea92f29bfde5fa/src/libraries/System.Linq/src/System/Linq/First.cs#L105-L129).

In particular, the perf improvement discrepancy comes from the WhereIterator types specializing for list and array types, but I don't believe it would be as pronounced if the source enumerable was anything else. The performance of `First(OrDefault)` taking predicates can be improved for those cases if we add detection for span-based sources, as shown in [this draft PR](https://github.com/dotnet/runtime/pull/100405).

**Comment by stephentoub** [comment]
I expect this benchmark should see the difference evaporate in .NET 9.

**Comment by Treit** [comment]
Looks like the performance difference did effectively go away in .NET 9.

![Image](https://github.com/user-attachments/assets/3f9d3c4c-7144-46de-b55f-a054ae7d7bb5)

As a result, I am closing this issue.
