### ISSUE TITLE
QuicListener Not Including Intermediary Certificates Without Explicit ServerCertificateContext

### ISSUE THREAD

**Issue by pepone** [dotnet/runtime#100530]
When using a certificate that contains an intermediary present in the system store, a Quic server doesn't include the intermediary in the TLS handshake.

You have to manually set [ServerCertificateContext](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslserverauthenticationoptions.servercertificatecontext?view=net-8.0) in the SslServerAuthenticationOptions pass to the `QuicListener`.

With `SslStream` if the intermediary is present in the system store, it is also send without need to explicitly set `ServerCertificateContext`.

That is with Ubuntu 22.04, dotnet 8.0.3

Is this expected? It would be better if they work the same way as they are configured using the same `SslServerAuthenticationOptions`.

**Comment by rzikm** [comment]
I think it's because we don't explicitly pass the intermediates to MsQuic

https://github.com/dotnet/runtime/blob/e12e2fa6cbdd1f4b0c8ad1b1e2d960a480c21703/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/MsQuicConfiguration.cs#L97-L110

In SslStream, we build the SslStreamCertificateContext under the covers so we manage to find the intermediates, we should to that in Quic as well.

Note that using SslStreamCertificateContext is the recommended way to pass certificates in .NET 8+ because it avoids the need to build the X509 chain for each connection separately for the same certificate.
