### ISSUE TITLE
Add support of standard streams redirection in dbgshim

### ISSUE THREAD

**Issue by okodron** [dotnet/runtime#10077]
Currently it's impossible to redirect input/output streams of the process created with `CreateProcessForLaunch()`. Such feature can be useful for debugger implementation for Unix.
However PAL version of `CreateProcessW` supports stream redirection.
I propose to extend the API of the `dbgshim` library with something like this:
```c++
EXTERN_C HRESULT
CreateProcessForLaunchEx(
    __in LPWSTR lpCommandLine,
    __in BOOL bSuspendProcess,
    __in LPVOID lpEnvironment,
    __in LPCWSTR lpCurrentDirectory,
    __out PDWORD pProcessId,
    __out HANDLE *pResumeHandle,
    __out HANDLE *pStdInHandle,
    __out HANDLE *pStdOutHandle,
    __out HANDLE *pStdErrHandle);
```
Also a special portable API for `HANDLE` reading and writing will be added:
```c++
typedef VOID (*PREADHANDLE_CALLBACK)(PVOID pBuffer, DWORD dwBufferSizeInBytes, PVOID parameter);

EXTERN_C HRESULT
RegisterForStandardOutput(
    __in HANDLE hStdOutHandle,
    __in PREADHANDLE_CALLBACK pfnOutCallback,
    __in HANDLE hStdErrHandle,
    __in PREADHANDLE_CALLBACK pfnErrCallback,
    __in PVOID parameter,
    __out PVOID *ppListenerToken);

EXTERN_C HRESULT
WriteStandardHandle(
    __in HANDLE hStdInHandle,
    __in LPCVOID lpBuffer,
    __in DWORD dwNumberOfBytesToWrite,
    __out DWORD *pdwNumberOfBytesWritten
);

EXTERN_C HRESULT
CloseStandardHandle(
    __in HANDLE hStandardHandle);
```

In such case debugger can handle input/output of the newly created process in a portable way.

**Comment by KirillOsenkov** [comment]
Can anyone think of a workaround? Is there any way to read the output of the debuggee (suppose I'm Windows only)?

**Comment by noahfalk** [comment]
I would hope that you could use windows CreateProcess API with the CREATE_SUSPENDED flag, then use RegisterForRuntimeStartup(...) then ResumeThread(). @mikem8361 might know if there are issues with that approach?

**Comment by mikem8361** [comment]
On Windows that would work just fine. It is on Linux/MacOS that it gets more complicated.  You would have to emulate, the CreateProcess CREATE_SUSPENDED, call RegisterForRuntimeStartup, and then "resume" the target process.  Internally, that is what dbgshim's CreateProcessForLaunch/ResumeProcess does.

There are "CreateProcessW" and "ResumeThread" APIs exported by the DAC module (libmscordaccore.so/libmscordaccore.dylib) that could be used on Linux/MacOS, but these exports are considered internal, are not really documented and could change in future releases. The CREATE_SUSPENDED flag will work. CREATE_NEW_CONSOLE is ignored. Because of the fake handle issue I point out  above, only the CreateFile* APIs export by the DAC can be use to supply the redirection handles.

**Comment by KirillOsenkov** [comment]
Thanks! Is `CreateProcessForLaunch` open source? I'm guessing I could take that implementation and since I only need it on Windows I could tweak to create the process myself (suspended), then RegisterForRuntimeStartup, then resume.

**Comment by mikem8361** [comment]
Yes: https://github.com/dotnet/runtime/blob/48cd4789819d4903e11c786155211a97e1746a08/src/coreclr/src/dlls/dbgshim/dbgshim.cpp#L81
