### ISSUE TITLE
[API Proposal]: string.{Last}IndexOfAny(string[])

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#100724]
### Background and motivation

Sometimes you want the {Last] index of a set of strings.
When you get that index, sometimes you want the position of the first character in the match and sometimes you want the position of the last character in the match (start+length)

This should be easy.

### API Proposal

```csharp

public class String
{
public static Range? LastIndexOfAny(string[] anyOf);
public static Range? LastIndexOfAny(string[] anyOf, int startIndex);
public static Range? LastIndexOfAny(string[] anyOf, int startIndex, int count);
public static Range? LastIndexOfAny(string[] anyOf, int startIndex, StringComparison stringComparison);
public static Range? LastIndexOfAny(string[] anyOf, StringComparison stringComparison);
public static Range? LastIndexOfAny(string[] anyOf, int startIndex, int count, StringComparison stringComparison);

public static Range? IndexOfAny(string[] anyOf);
public static Range? IndexOfAny(string[] anyOf, int startIndex);
public static Range? IndexOfAny(string[] anyOf, int startIndex, int count);
public static Range? IndexOfAny(string[] anyOf, int startIndex, StringComparison stringComparison);
public static Range? IndexOfAny(string[] anyOf, StringComparison stringComparison);
public static Range? IndexOfAny(string[] anyOf, int startIndex, int count, StringComparison stringComparison);
}
```

### API Usage

```csharp
if(Input.LastIndexOf(["abc", "def"]) is { } Match){

}
```

### Alternative Designs

Instead of returning a ```Range?``` we could return a ```Range``` and no match would return ```default(Range)```.

There might be some way of doing this with ```SearchValues``` as well.

**Comment by stephentoub** [comment]
`SearchValues<string>` in .NET 9 supports efficiently searching for multiple substrings within a larger string. We currently have no plans to expose APIs like the ones mentioned here because a) it's expensive to do efficiently like this as a one-off (either paying on each call to do the analysis SearchValues does once, or incurring a much more expensive search that looks at all characters in all strings for all characters in the input), and b) it encodes policy as to which string is returned when there are multiple possible matches because the length needs to be factored in (leftmost-specified first? longest first? shortest first? etc).
