### ISSUE TITLE
On Windows x64 ABI, struct constructor call does not assign the value to a field directly, while a method call does

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#100733]
### Description

Currently, when creating a struct via `ctor`, the address of `this` passed to `ctor` is that of a temp local instead of a field that it is being assigned to. I'm not sure whether this is intended (zeroing considerations?) hence creating the issue.

### Configuration

.NET 8.0.3, Windows x64

### Regression?
No

### Analysis

Given the following snippet, only `FromMethod` assigns to a field directly.

```cs
class Test
{
    Holder _holder;

    struct Holder
    {
        object? _a;
        long _b;

        [MethodImpl(MethodImplOptions.NoInlining)]
        public Holder()
        {
            this = default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Holder(bool flag)
        {
            this = Inner();
            
            [MethodImpl(MethodImplOptions.NoInlining)]
            static Holder Inner()
            {
                return default;
            }
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public static Holder Create()
        {
            return new Holder
            {
                _a = null,
                _b = 0
            };
        }
    }

    public void FromCtor() => _holder = new Holder();
    public void FromInlinedCtor() => _holder = new Holder(false);
    public void FromMethod() => _holder = Holder.Create();
}
```

`FromCtor`:
```asm
G_M000_IG01:                ;; offset=0x0000
       push     rbx
       sub      rsp, 48
       vzeroupper 
       mov      rbx, rcx
 
G_M000_IG02:                ;; offset=0x000B
       vxorps   xmm0, xmm0, xmm0
       vmovdqu  xmmword ptr [rsp+0x20], xmm0
       lea      rcx, [rsp+0x20]
       call     [Test+Holder:.ctor():this]
       lea      rcx, bword ptr [rbx+0x08]
       mov      rdx, gword ptr [rsp+0x20]
       call     CORINFO_HELP_ASSIGN_REF
       mov      rax, qword ptr [rsp+0x28]
       mov      qword ptr [rbx+0x10], rax
 
G_M000_IG03:                ;; offset=0x0037
       add      rsp, 48
       pop      rbx
       ret
```

`FromMethod`:
```asm
G_M000_IG01:                ;; offset=0x0000
       sub      rsp, 40
 
G_M000_IG02:                ;; offset=0x0004
       cmp      byte  ptr [rcx], cl
       add      rcx, 8
       call     [Test+Holder:Create():Test+Holder]
       nop      
 
G_M000_IG03:                ;; offset=0x0011
       add      rsp, 40
       ret
```

**Comment by jkotas** [comment]
This behavior is by design.

The [IL generated by Roslyn for your example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAGAAkIEYA6AJQFcA7DbAWxioGEIWAHPGKAGUBAN2xgYAZwDcAWABQCwgCZSAFSkYFAbwWl9pABIRcAEwGkA+gAsT5qHMXyDpSRih0wGI3YF6Dus4uBhDAAFYwXgD8VgCGjsEGuBAMAOZWwI7+iQDaALIwGLamAJK8uAAUBUUQpeUA8jzMKZJUAHIQJQy42Ay9qQCUALrZwYQAzD5mAhUDoy6BiYlF2JKkALyk5gBmsXS4GAlLAL4K8wb5hcVlPJXV1w1N2C1UAIKpqbCSktgiMF09PppYbnfQTKb2CrACAmUjbXCxQag0iLJYuFZrTZdBgzAZHNH6ZEuS41Oq3KpXWo3XCNZoMVodAG9fogoIE8gUJAQizY3FEgL8xKEADsWxgu32h0FpFObOCsuRJIe5PuVMedIZnW6zOBIzlLnBlC5xmmUFIHFgsQwMFmyNR7JFpBxAHduVBpfb2QZLLENk79rg0NKXJZgH7iNLjvj5aMFXLDShSAAxKDcDgYaCzDYAPistlNfpdbtm0YTydTLCZONM6czAxzed8Zs2RZNkN2uEkMDxozLKe4qtMWfWuZsTb9bYEnEt1pLCmOQA=) creates a temp and then assigns it to the field. The C# language spec requires the value to be constructed in a temp for this case.

**Comment by huoyaoyuan** [comment]
If constructor throws, the destination should remain unmodified right?

**Comment by jkotas** [comment]
Right. Modifications of the destination should not be visible while the constructor is executing.

**Comment by neon-sunset** [comment]
Makes sense, thanks for the explanation!
