### ISSUE TITLE
ITrigonometricFunctions is missing Atan2

### ISSUE THREAD

**Issue by kaba2** [dotnet/runtime#100816]
### Description

ITrigonometricFunctions is missing [Atan2](https://learn.microsoft.com/en-us/dotnet/api/system.math.atan2?view=net-8.0). Atan2 is useful for obtaining the angle of a vector. It can be implemented in terms of Atan, but since the same implementation would be repeated for everyone, it would be nice to have it out of the box.

### Reproduction Steps

No reproduction needed.

### Expected behavior

There should be ITrigonometricFunctions<T>.Atan2.

### Actual behavior

There is no ITrigonometricFunctions<T>.Atan2.

**Comment by stephentoub** [comment]
It's on IFloatingPointIeee754:
https://github.com/dotnet/runtime/blob/e60d9a33355b536ba51478fc1940f1a4c8a799bc/src/libraries/System.Private.CoreLib/src/System/Numerics/IFloatingPointIeee754.cs#L38

**Comment by kaba2** [comment]
@stephentoub I think it's on the wrong abstraction level, since Atan2 can be implemented in terms of Atan which is found in ITrigonometricFunctions.

**Comment by tannergooding** [comment]
Atan2 is very explicitly not part of `ITrigonometricFunctions` because it entails a lot of special cases and consideration that make it non-trivial to implement in terms of `Atan`. Contrary to the common mathematical explanation, `atan2(y, x)` is not quite the same as `atan(y / x)`.

For IEEE 754 requirements in particular, there are many edge cases required around the handling of `+0`, `-0`, `+Infinity`, and `-Infinity` which necessitate various members and concepts existing that could not trivially exist lower than `IFloatingPointIeee754`.
