### ISSUE TITLE
Use another Core Assembly with `PersistedAssemblyBuilder`

### ISSUE THREAD

**Issue by bsdayo** [dotnet/runtime#101018]
As for the examples in [.NET Libraries in .NET 9 Preview 3](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview3/libraries.md#added-persistableassemblybuilder-type-in-systemreflectionemit), we can use `typeof(object).Assembly` as the Core Assembly to instantiate the `PersistedAssemblyBuilder`:

```csharp
PersistedAssemblyBuilder ab = new PersistedAssemblyBuilder(new AssemblyName("MyAssembly"), typeof(object).Assembly);
```

But how can we use another Core Assembly, for example another version of `System.Private.CoreLib`? The runtime rejects loading it, according to #89215 and my own tests.

The constructor defined a parameter specifically for it and allow us to provide our own Core Assembly, I'm curious if the scenario above can be achieved, or I left something.

EDIT: I'm writing a toy compiler which needs the ability to dynamically generate IL and save .dll to disk. I'm stucking at how to let users to specify their own `System.Private.CoreLib` reference, just like what `csc` do.

**Comment by teo-tsirpanis** [comment]
I think you can use an assembly from [`MetadataLoadContext`](https://learn.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext).

**Comment by jkotas** [comment]
> I think you can use an assembly from [MetadataLoadContext](https://learn.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext).

Pass the value returned by `MetadataLoadContext.CoreAssembly` to the `PersistedAssemblyBuilder` constructor.

Also, you should use types returned by the MetadataLoadContext instance throughout your compiler. For example, instead of `typeof(object)`, you should lookup `System.Object` type in `MetadataLoadContext.CoreAssembly` by name.

> I'm stucking at how to let users to specify their own System.Private.CoreLib

You should direct your uses to use reference assemblies for this purpose: https://www.nuget.org/packages/Microsoft.NETCore.App.Ref/. This package is also included as part of .NET SDK at paths like `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.4\ref\net8.0`.

The core assembly is going to be System.Runtime when using reference assemblies, reference assemblies do not have `System.Private.CoreLib`.

@buyaa-n Could you please make sure that we have documentation and a sample for this scenario at https://learn.microsoft.com/?

**Comment by bsdayo** [comment]
Thanks for pointing this out, I didn't even know there was a `MetadataLoadContext` type before. It fits my scenario perfectly and the problem has been solved. Thanks again.

**Comment by buyaa-n** [comment]
> @buyaa-n Could you please make sure that we have documentation and a sample for this scenario at https://learn.microsoft.com/

We have it explained in the conceptual doc https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-reflection-emit-assemblybuilder#persisted-dynamic-assemblies-in-net, need to add a sample
