### ISSUE TITLE
[API Proposal]: Add BinaryPrimitives Single and Double support to .NET standard 2.1

### ISSUE THREAD

**Issue by Vivraan** [dotnet/runtime#101085]
### Description

.NET Standard 2.1 is a wide surface; I use it extensively in Unity. Unity has plenty of use cases for efficiently writing floating-point data as bytes to data sinks. While it supports integer types through `BinaryPrimitives.Write(U)Int*Endian`, it doesn't work with single and double-precision floating types, which have been supported as long back as 2020 since C# 9.0.0 preview (https://github.com/dotnet/runtime/issues/2365)

### Reproduction Steps

N/A

### Expected behavior

It should be present.

### Actual behavior

Support for `WriteSingle*Endian` and `WriteDouble*Endian` is not present.

### Regression?

Not a regression.

### Known Workarounds

`MemoryMarshal` but only for Little Endian writes.

### Configuration

- .NET Standard 2.1
- Windows 11 Home x64
- Might be specific to Unity 2022.3.22f1

**Comment by tannergooding** [comment]
.NET Standard 2.1 has already shipped, the base surface area is frozen for types like `System.BitConverter` which are in-box.

.NET Standard 2.2 or 3.0 doesn't exist because that's just `.NET Core 3.0` or `.NET 5/6/7/8/etc`, which is to say each new version of .NET is the latest "standard" now that things are unified. See also: https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/, CC. @terrajobst 

Unity is working on adding support for modern .NET and will get access to newer APIs like you've called out above at that time.

https://blog.unity.com/engine-platform/unity-and-net-whats-next and https://blog.unity.com/engine-platform/unity-and-net-whats-next are blog posts discussing the progress Unity is making in this space

https://forum.unity.com/threads/unity-future-net-development-status.1092205/ has semi-regular updates with progress as well
