### ISSUE TITLE
Running dotnet core on Alpine for ARM32

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/runtime#10111]
Due to its small footprint (OS image size), Alpine is suited for embedded scenarios on ARM32.

Things leading to this: 
- Today dotnet core is Community Supported on ARM32. 
- dotnet core 2.1 will support arm32 officially ([Supported Operating Systems and Chip Architectures](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/)-section) 

- Today dotnet core 2.1 is running on Alpine for x86. 
- It is possible to run docker on an embedded system (for example [ResinOS](https://resinos.io/)) and in order to do this efficiently a small container image is needed, hence the need for Alpine support.
- It is expected to have symmetry in OS support between different CPU architectures where possible

(If/when this is implemented the docker images for running .net core application should be available. )

**Comment by JensNordenbro** [comment]
Is this status really correct? 
The related https://github.com/dotnet/runtime/issues/2021 seems to be done. 

![image](https://user-images.githubusercontent.com/9577365/159242621-d60a7054-bce7-4f50-862d-cd45c2e03853.png)

**Comment by ericstj** [comment]
I believe it is supported.  We call that out here:
https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md
Linked from here: https://github.com/dotnet/core/blob/main/os-lifecycle-policy.md

This issue should be closed.

The screenshotted document should probably be fixed.  Looks like you found that here https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/README.md?msclkid=510db129aa1811eca844fa3c0dbee4cf#build-an-image-for-arm32-and-arm64

Rather than transferring this issue could you instead file an issue in that repo, or propose a PR if it's straightforward?
