### ISSUE TITLE
Behaviour of GC HeapHardLimit

### ISSUE THREAD

**Issue by wc-s** [dotnet/runtime#101183]
Recently we've had an OutOfMemory issue which I believe is due to running into the HeapHardLimit.

The issue was eventually tracked down to a memory leak, but it got me looking at the HeapHardLimit mechanism, and I have a question on whether its behaviour is reasonable. Basically, we were running into the OOM even when our container memory usage was very low, nowhere near the container memory limit.

I've attached a screenshot of what we saw before we fixed the memory leak problem.
<img width="582" alt="Screenshot 2024-04-14 at 03 09 57 copy" src="https://github.com/dotnet/runtime/assets/15850705/4a43e28d-172a-470d-9467-42c7e0b45c6c">

You can see that the Working Set Size is much smaller than the GC Heap Size and GC Committed Bytes. I assume that the HeapHardLimit targets the GC Committed Bytes number, and so I think this discrepancy was why we ran into the OOM even when container memory usage is low.

That made me think - if the intention of the HeapHardLimit mechanism was to limit the physical memory usage, why target the heap size rather than the working set size?

**Comment by cshung** [comment]
The situation is strange, what .net version / OS is this?

**Comment by wc-s** [comment]
It's .net 8.0, the OS is an AWS AMI based on Ubuntu 20.04.6 LTS, x86_64.

Ah, so you're saying it's _not_ usual to have the GC heap size this much bigger than Working Set size? (Sorry I'm more of an infra guy helping to look into one of our app's memory issue, than an experienced dotnet person myself.)

If that's the case, we're happy to chalk this down to "when you have serious memory leaks, things get wacky and start to exceed the design parameters of the runtime". After the memory leak was fixed, our heap size did indeed become lower than working set size.

In case it's of interest, the main leaking objects were 2 Large Objects, which are `System.Byte[]` of `2,626,584` and `131,096` bytes.

**Comment by cshung** [comment]
The `gc-heap-size` counter tell you how much memory your application is using for objects, and the `working-set` counter tells you how much physical memory the OS is using to serve the process.

Since you used around 900M and the operating system is only giving 340M to this process, much of the other memory must be swapped out to disk. You might want to take a look at your swap usage. It might well be the case that because you are leaking memory, much of the memory is left untouched and therefore got swapped out by the OS heuristics (which I don't know much about that)

In any case, if the dotnet process is not throwing an `OutOfMemoryException`, it should be considered expected usage and you should not see wacky behavior.

**Comment by wc-s** [comment]
I see, thank you for the explanation. I'll close this issue.
