### ISSUE TITLE
Named pipes on MacOS can't connect in .NET 8

### ISSUE THREAD

**Issue by Jasper2213** [dotnet/runtime#101741]
### Description

I'm trying to use named pipes in .NET MAUI, but when testing on MacOS, the client can't connect to the server, it just hangs on `connect`.

When running the project with .NET 7, the client connects to the server on both Windows and MacOS.

### Steps to Reproduce

1. Clone the reproduction repo
2. Open the net-8 solution
3. Run the Server and Client at the same time

Expected outcome: Client connects to Server

Actual outcome: Client can't connect to Server, instead hangs at `_pipeClient.ConnectAsync()`

### Link to public reproduction project repository

https://github.com/Jasper2213/named-pipes

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by vitek-karas** [comment]
We should look into this and at least understand the problem as it's a regression (from 7 -> 8, but still).

**Comment by buyaa-n** [comment]
It doesn't seem we made changes in 8.0 that cause it suddenly to stop it working.  

I was not able run the repro you shared, seems my mac is too old for running MAUI with .NET 8, I did run some sample apps on .NET 8.0 similar to the example in the [doc](https://learn.microsoft.com/dotnet/api/system.io.pipes.namedpipeclientstream) successfully. So, if there is issue in runtime most likely it caused by MAC OS changes.

@Jasper2213 what version of MAC OS you are using? Could you try run the client/server sample apps in the [doc](https://learn.microsoft.com/dotnet/api/system.io.pipes.namedpipeclientstream) on your machine?

**Comment by Jasper2213** [comment]
Running the (slightly modified) sample from the docs works.
I've tried adjusting the .NET MAUI sample to match this example as good as possible, but without success so far. I'll try to get it working, and will give an update if I'm successful.

I'm running on a Mac Mini with an M2 Pro on Sonoma 14.4.1

**Comment by buyaa-n** [comment]
> Running the (slightly modified) sample from the docs works. I've tried adjusting the .NET MAUI sample to match this example as good as possible, but without success so far. I'll try to get it working, and will give an update if I'm successful

Thanks, I would try make sample app as close as MAUI app (for `NamedPipeClientStream` and `NamedPipeServerStream` usage prespective), it would narrow down the issue that it is not in runtime `NamedPipeClientStream`/`NamedPipeServerStream` libraries.
