### ISSUE TITLE
Random malloc failures on current Debian Bookworm slim image

### ISSUE THREAD

**Issue by KLazarov** [dotnet/runtime#101722]
### Describe the Bug

We are running the `mcr.microsoft.com/dotnet/aspnet:8.0.3-bookworm-slim` image for our Kubernetes Asp.Net services. A couple of days ago we started experiencing random pod restarts, and after investigating we came to the conclusion that something has changed in the image that breaks something with malloc. The code has not changed at all between builds, only the image has been rebuild. The previous working image on the bookworm 8.0.2, all 8.0.3 images fail after a while.

The errors that we get are:

```
Apr 8 22:43:16 pod1: tcache_thread_shutdown(): unaligned tcache chunk detected
Apr 9 09:32:53 pod2: malloc(): unaligned tcache chunk detected
Apr 9 10:15:15 pod3: malloc(): unaligned fastbin chunk detected
Apr 9 10:54:14 pod2: malloc_consolidate(): unaligned fastbin chunk detected
Apr 9 12:47:26 pod2: malloc(): unaligned tcache chunk detected
Apr 9 15:03:42 pod2: malloc_consolidate(): unaligned fastbin chunk detected
Apr 9 21:32:10 pod3: malloc(): unaligned tcache chunk detected
Apr 10 09:06:59 pod3: malloc(): unaligned tcache chunk detected
Apr 10 09:31:50 pod2: malloc(): unaligned tcache chunk detected
Apr 10 10:28:11 pod3: malloc(): unaligned tcache chunk detected
Apr 10 16:32:00 pod3: malloc(): unaligned tcache chunk detected
Apr 10 19:08:25 pod2: malloc(): unaligned tcache chunk detected
Apr 11 14:36:42 pod3: malloc_consolidate(): unaligned fastbin chunk detected
```

The only extra libs that we add to the image are `tzdata` and `libicu72`.

### Steps to Reproduce

1. Use an Asp.Net service using the `mcr.microsoft.com/dotnet/aspnet:8.0.3-bookworm-slim` image.
2. Deploy to Kubernetes.
3. Do a lot of requests (we have around 100k or so before it fails, but sometimes it fails sooner)
4. You get `malloc()` or `malloc_consolidate()` or `tcache_thread_shutdown` error and the pod restarts.

### Other Information

The issue is difficult to reproduce, we had to setup a bombardment service to get it.

We have tried with different RAM limits, but we never get to the max limit.

Workaround for now is to use the Alpine image instead. We have it in another service and it works fine on the same Kubernetes cluster.

### Output of `docker version`

We are running Kubernetes 1.28.8.

### Output of `docker info`

We are running Kubernetes 1.28.8.

**Comment by richlander** [comment]
@janvorli @bartonjs @vcsjones

**Comment by vcsjones** [comment]
If I had to guess, there might be an issue here:

https://github.com/Coflnet/SkyBackendForFrontend/blob/2bc2185916fba1e492d3eb2aad10f52b71e81831/Services/StateUpdateService.cs#L28-L34

This does a `var sha = SHA256.Create();` and captures it in a lambda used by Kafka. If that lambda is executing concurrently, then the hash object is being used from multiple threads. Instances of `SHA256` are not safe to use from multiple threads.

This line:

```C#
byte[] encoded = sha.ComputeHash(key.ToArray().TakeWhile(c => c != '-').Select(c => (byte)c).ToArray());
```

Should probably just be:


```C#
byte[] encoded = SHA256.HashData(key.ToArray().TakeWhile(c => c != '-').Select(c => (byte)c).ToArray());
```

Using the static is the "right" thing in this case. The static is safe to use from multiple threads, and will give better performance. There may be other instances of a hash algorithm being used from multiple threads. I did not examine every usage of the hash algorithm.

In .NET 9 this has been "fixed" to throw a managed exception if a hash object is incorrectly used concurrently instead of crashing the process.

**Comment by richlander** [comment]
Should this change be back-ported to .NET 8 or is that considered too breaking?

Getting tons of hard-to-diagnose reports isn't going to be great.

**Comment by vcsjones** [comment]
> Should this change be back-ported to .NET 8 or is that considered too breaking?

It's not a new behavior in .NET 8, I think it is easier to hit in .NET 8 though because .NET 8 docker images switched from OpenSSL 1.1 to OpenSSL 3.0 and OpenSSL 3.0 seems more prone to the issue occurring.

I also don't know for a _fact_ that is the issue at hand here - I just noted in the code base there is at least one place where it appears a hash algorithm instance is used concurrently and that is a known source of these hard to diagnose problems.

My 2c: back porting the fix as-is would be too breaking because we applied it to all platforms. Windows for example, we know is more tolerant to concurrent hash algorithm use in some (but not all!) circumstances, so the bad scenario just seems to "work". Whereas the backport would stop a "not correct but not broken" scenario from "working".

If we want to do something for 8.0 then the fix would need to be more targeted.

@bartonjs what are your thoughts?

**Comment by bartonjs** [comment]
I don't think that the servicing team will like "we want to make this change in case it happens to be useful".  I don't know that "this doesn't fix a problem per se, it just turns an app termination into an exception" would go over astonishingly well... so it would need to be coupled with someone who is hitting this problem in the wild saying it went away when they changed from instance hashes to static hashes (or shared instances to individual instances, or locking, or whatever).

**Comment by Ekwav** [comment]
@vcsjones is right switching to `SHA256.HashData` seemingly resolved my issue. No crashes since I changed.
I am not sure that this is already changed in .NET 9, I also tried the asp.net preview image last week and it had the same crashes.
An exception on .NET 8 would have saved me about a week of work.

**Comment by vcsjones** [comment]
> I am not sure that this is already changed in .NET 9, I also tried the asp.net preview image last week and it had the same crashes

This change was merged 3 weeks ago (at the time of writing). It is not in any release .NET 9 previews. It looks like it will be present in .NET 9 Preview 4.

**Comment by bartonjs** [comment]
> @vcsjones is right switching to SHA256.HashData seemingly resolved my issue. No crashes since I changed.

So now a backport seems more justified.  Probably just the OpenSSL-based impl... and I don't know if "just 8" or "may as well offer up 6".  But 7 has already had final servicing, so that's easier at least.

**Comment by vcsjones** [comment]
Okay. I will make a bespoke backport for 8 and 6 to something more reasonable.

**Comment by vcsjones** [comment]
We merged a change for .NET 8 that was approved for 8.0.6.

After some consideration I did not do a backport for 6.0. We have received no reports for this issue with .NET 6 since the 6.0 image base uses OpenSSL 1.1.

Since all expected actions have been taken, I am going to close this out. Please feel free to re-open this issue if there are any unaddressed concerns or issues.

Thanks all!

**Comment by richlander** [comment]
Thanks much @vcsjones  and @bartonjs!
