### ISSUE TITLE
[Performance] Regression on Fortunes - Windows

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#101936]
Isolated to these commits: https://github.com/dotnet/runtime/compare/774bc93087ad...d688ac290cd7
Only on Windows
320K RPS to 300K RPS.
There is also a visible first request regression on the same commits.

![image](https://github.com/dotnet/runtime/assets/1165805/750d61d5-617c-4eb8-a9cf-fccf8512c01d)
![image](https://github.com/dotnet/runtime/assets/1165805/4a88aec9-3d74-4691-8ad8-9bcf514e603d)
![image](https://github.com/dotnet/runtime/assets/1165805/398d392e-1c77-4261-be76-9891fc0573a9)

Command line

Between `9.0.0-preview.4.24223.5` and `9.0.0-preview.4.24223.6`
```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario fortunes --profile intel-win-app --profile intel-load-load --profile intel-db-db --application.framework net9.0 --application.options.collectCounters true --application.collectDependencies true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.4.24218.1 --application.runtimeVersion 9.0.0-preview.4.24223.6 --application.sdkVersion 9.0.100-preview.4.24223.13
```

**Comment by stephentoub** [comment]
Is anything in Fortunes using Channel.CreateUnbounded?

**Comment by roji** [comment]
Yep, an unbounded channel is the internal implementation of Npgsql's connection pool (Max Pool Size is enforced in other ways, so the channel itself is unbounded).

Is there any particular concern here? Was this a regression in the Channel implementation?

/cc @NinoFloris @vonzshik

**Comment by stephentoub** [comment]
> Is there any particular concern here? 

Not for you :smile:

> Is there any particular concern here? Was this a regression in the Channel implementation?

That's what I'm questioning. One of the changes in the diff range was a change that shouldn't have impacted throughput of the channel created by `Channel.CreateUnbounded` but seems like it may have.

**Comment by stephentoub** [comment]
@roji, which of these would end up being used on a hot path in Fortunes?

**Comment by vonzshik** [comment]
@stephentoub that's probably going to be the one in the [connector](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/Internal/NpgsqlConnector.cs#L391-L394).

The way it works is that each connector (that's a physical connection to pg) starts their own async loop to handle query responses. Then, whenever data source receives queries, it dispatches them to a connector with the least in-flight query count and after each dispatch it attempts to write that query to connector's socket. If that write does complete synchronously, it's just going to immediately dispatch another query to the exact same connector. That loop repeats until write doesn't complete synchronously.

As for the code, [here](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/Internal/NpgsqlConnector.cs#L1115-L1120) queries are received from [data source](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/MultiplexingDataSource.cs#L232-L233). Not sure whether it's relevant, but data source write loop is single threaded, so there shouldn't be any contentions.

**Comment by stephentoub** [comment]
> that's probably going to be the one in the [connector](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/Internal/NpgsqlConnector.cs#L391-L394).

Hmm. That one wouldn't have been affected at all by https://github.com/dotnet/runtime/commit/b4e0169bfe10cfe69f6e7a8952b8f80fdfe9e31e, as that doesn't touch the code used when SingleReader is true.

**Comment by vonzshik** [comment]
The only other one we have is the one we use for the [pooling](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/PoolingDataSource.cs#L91-L93) (just as @roji mentioned above).

It potentially could be quite hot since the way fortunes designed to:
1. Get connector from the pool
1.1. [Attempt](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/PoolingDataSource.cs#L211-L218) to get an idle connector
1.2. If previous step fails, [start waiting](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/PoolingDataSource.cs#L152) for the channel reader to return a connector
2. Execute a query (which takes extremely short time)
3. [Return](https://github.com/npgsql/npgsql/blob/12e5ec24db566a4a0fe93d283f1007a30b4e31aa/src/Npgsql/PoolingDataSource.cs#L339-L340) connector to the pool

Now, there is a catch. This particular path shouldn't ever be executed with fortunes. The reason for this is because we use multiplexing mode with TE benchmarks (as it's the most performing one), and it completely avoids connector renting, instead going through multiplexing data source (which I described above). @roji is there a chance this benchmark doesn't use multiplexing?

**Comment by stephentoub** [comment]
@sebastienros, does the regression persist? Based on all of this, I don't see how the Channel PR could have impacted this, but it's also seemingly the only commit in that diff range that could possibly be related.

**Comment by sebastienros** [comment]
@stephentoub it's still there. To confirm, if it doesn't take much to build an assembly with and without the commit then that would help me to confirm if we are looking at the correct change.
