### ISSUE TITLE
`StartupValidator` multiple registrations.

### ISSUE THREAD

**Issue by PetSerAl** [dotnet/runtime#102061]
`OptionsBuilderExtensions.ValidateOnStart` register `StartupValidator` service for option validation:
https://github.com/dotnet/runtime/blob/6cc6c66acc3f187f30e0fc7541e1097999863ff5/src/libraries/Microsoft.Extensions.Options/src/OptionsBuilderExtensions.cs#L28
It does that with `AddTransient`, but `ValidateOnStart` can be called multiple times (once for each option type plus option name combination), which leads to `StartupValidator` would be registered multiple times. Should it use `TryAddTransient` instead to keep only one registration of `StartupValidator`?

**Comment by tarekgh** [comment]
@PetSerAl thanks for your report. Could you please submit a small sample code to demonstrate the problem you are seeing?

**Comment by tarekgh** [comment]
@PetSerAl I think you are correct. `TryAddTransient` should be used instead of `AddTransient`.

@eerhardt @davidfowl @steveharter @ericstj do you see any risk fixing this? to summarize the issue, every time [OptionsBuilder<TOptions>.(ValidateOnStart)](https://github.com/dotnet/runtime/blob/6cc6c66acc3f187f30e0fc7541e1097999863ff5/src/libraries/Microsoft.Extensions.Options/src/OptionsBuilderExtensions.cs#L23) get called, it does 

```C#
optionsBuilder.Services.AddTransient<IStartupValidator, StartupValidator>();
```

which adds transit service to the DI always using the same interface type `IStartupValidator` and implmentation type `StartupValidator`. Using `TryAddTransient` should be used instead to avoid adding the same thing multiple times.

**Comment by ericstj** [comment]
That seems correct, looks like that's what the old extensions library did: https://github.com/dotnet/extensions/blob/c9b1f395705c56438fb4f9eba351d6e0db624f12/src/ToBeMoved/Hosting.StartupInitialization/Internal/StartupInitializationBuilder.cs#L45C18-L45C33

**Comment by tarekgh** [comment]
@PetSerAl are you interested to submit a PR for the fix?

**Comment by tarekgh** [comment]
@PetSerAl no worries, I'll do it.
