### ISSUE TITLE
DynamicallyAccessedMembers attribute ignored on generic attribute when publishing for AOT

### ISSUE THREAD

**Issue by phil-scott-78** [dotnet/runtime#102023]
### Description

When adding `DynamicallyAccessedMembers` to a type parameter on an attribute, the compiler doesn't respect the value set

### Reproduction Steps

```csharp
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

Derp.Merp<DirectoryInfo>("blargh");

[Demo<DirectoryInfo>]
static class Derp
{
    public static void Merp<T>(string s)
    {
        // forcing the issue here, the attribute should allow this 
        var constructor = typeof(T).GetConstructor(BindingFlags.Public | BindingFlags.Instance, null, [typeof(string)], null);
        Debug.Assert(constructor != null, nameof(constructor) + " != null");
        var i = (DirectoryInfo) constructor.Invoke([s]);
        Console.WriteLine(i.Exists);
    }    
}

internal class DemoAttribute<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T> 
    : Attribute;
```

### Expected behavior

Should print false

### Actual behavior

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Derp.Merp(Type) + 0x8a
   at ConsoleApp3!<BaseAddress>+0x13c5ac
```

### Regression?

No

### Known Workarounds

Using the type as a parameter in the constructor with the attribute defined on a type parameter works fine.

```csharp
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

Derp.Merp<DirectoryInfo>("blargh");

[Demo2(typeof(DirectoryInfo))]
static class Derp
{
    public static void Merp<T>(string s)
    {
        // forcing the issue here, the attribute should allow this 
        var constructor = typeof(T).GetConstructor(BindingFlags.Public | BindingFlags.Instance, null, [typeof(string)], null);
        Debug.Assert(constructor != null, nameof(constructor) + " != null");
        var i = (DirectoryInfo) constructor.Invoke([s]);
        Console.WriteLine(i.Exists);
    }    
}

internal class Demo2Attribute([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]Type type) : Attribute;
```

### Configuration

* .Net 8.0.4
* Windows 11
* x64

**Comment by vitek-karas** [comment]
Short answer - this works as designed. The attribute only makes guarantees about the thing it is on, not about the type in general.

In this case, the attribute guarantees the ability to access constructor when using the `T` of the `DemoAttribute` - so from within the `DemoAttribute` class. It does not guarantee that the constructor is there in general.

Note that the compiler tells you about this as well - the code in this case produces:
```
warning IL2090: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags, Binder, Type[], ParameterModifier[])'. The generic parameter 'T' of 'Derp.Merp<T>(String)' does not have matching annotations.
```

This is because the `T` in `Merp<T>` is not annotated, and so there's no guarantee that the constructor will be present.

*It's true that the final behavior in most cases tends to be like the one you want, but it's not what is guaranteed, and the compiler is free to optimize it away in this case*

Also as a side note - the program actually works for me when compiled with NativeAOT with 8.0.300-preview.

**Comment by phil-scott-78** [comment]
> Short answer - this works as designed. The attribute only makes guarantees about the thing it is on, not about the type in general.

That makes sense. To be honest, I'm trying hack a rather AOT unfriendly library relying heavily on reflection into at least giving users who want to give it a go some options. Source generators might be the cleaner solution for this scenario. 

Thanks for looking into it though.

**Comment by vitek-karas** [comment]
For workarounds - you might be able to use `DynamicDependencyAttribute`. But you won't get any validation (warnings).
