### ISSUE TITLE
Environment.GetFolderPath(Environment.SpecialFolder.Personal) returns different path for Xamarin.Forms and for MAUI on Android

### ISSUE THREAD

**Issue by yevgeny-sotnikov** [dotnet/runtime#102110]
### Description

During migration of an app from Xamarin.Forms was found weird behaviour:

`Environment.GetFolderPath(Environment.SpecialFolder.Personal)` returns another path on Android platform:

Xamarin.Forms:
/data/user/0/<packageName>/files

MAUI:
/data/user/0/<packageName>/files/Documents

It creates issue with an access to saved files during update process

### Steps to Reproduce

1. Create Core .net Standard project with class which returns `Environment.GetFolderPath(Environment.SpecialFolder.Personal)`;
2. Create Xamarin.Forms project and add reference to Core project.
3. Call core-class from Xamarin.Forms somehow, check string
4. Create MAUI project and add reference to Core project.
5. Call core-class from MAUI somehow, check string
6. Compare strings from both apps

### Link to public reproduction project repository

https://github.com/yevgeny-sotnikov/MAUI-issues/tree/environment-folder-android-issue

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

5.0.0.2012

### Affected platforms

Android

### Affected platform versions

Android 10 and upper

### Did you find any workaround?

Remove last Documents folder at path

**Comment by vitek-karas** [comment]
The macCatalyst version of this is https://github.com/dotnet/runtime/issues/100440.
@yevgeny-sotnikov could you please check it - there we plan to change the behavior at least in some cases.

**Comment by ivanpovazan** [comment]
> Will it keep same folder path on iOS and mac (same as at xamarin)? I don't want to change current folder of files for all platforms

It depends on which folder you would expect to retrieve. 
The following tables describe the difference between the behavior in previous releases (and the introduced breaking change in .NET8).


| .NET 7                                                           | Android                       | iOS                                                      | MacOS  |
|------------------------------------------------------------------|-------------------------------|----------------------------------------------------------|--------|
| Environment.GetFolderPath(Environment.SpecialFolder.Personal)    | /data/user/0/app_name/files | /var/mobile/Containers/Data/Application/app_guid/Documents | /Users/username/ |
| Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) | /data/user/0/app_name/files | /var/mobile/Containers/Data/Application/app_guid           | /Users/username/ |

| .NET 8                                                           |                                         |                                                          |                 |
|------------------------------------------------------------------|-----------------------------------------|----------------------------------------------------------|-----------------|
| Environment.GetFolderPath(Environment.SpecialFolder.Personal)    | /data/user/0/app_name/files/Documents | /var/mobile/Containers/Data/Application/app_guid/Documents | /Users/username/Documents |
| Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) | /data/user/0/app_name/files           | /var/mobile/Containers/Data/Application/app_guid           | /Users/username/          |

- If you expect to retrieve the `$HOME` directory, then as the documentation states you should be using `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)`
    - NOTE: Please note that $HOME on iOS devices is not writable
- If you expect to retrieve the `Documents` folder, then you should keep using `Environment.GetFolderPath(Environment.SpecialFolder.Personal)`

Please let us know if you have any other question.

**Comment by kiranbasvaraj** [comment]
Even i have the same issue with local dabase where the app failed  to get the data base path i tried above solution of using 
Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)  but Application is failing to deploy on top of xamarin forms application.

**Comment by ivanpovazan** [comment]
@kiranbasvaraj I am not sure I understand this part:
> Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) but Application is failing to deploy on top of xamarin forms application.

Are you also doing the migration from Xamarin.Forms to MAUI? 
Which platform are you targeting?

**Comment by ivanicin** [comment]
> Even i have the same issue with local dabase where the app failed to get the data base path i have tried the above solution of using Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) but Application is failing to deploy on top of xamarin forms application.

I can confirm that this doesn't work well instead of .Personal. While it makes the app not to crash it doesn't pull old data, as far as I can tell.

I am migrating from Xamarin.Android to .NET 8 Android (or whatever it is called).

**Comment by ivanpovazan** [comment]
> I can confirm that this doesn't work well instead of .Personal. While it makes the app not to crash it doesn't pull old data, as far as I can tell.

> I am migrating from Xamarin.Android to .NET 8 Android (or whatever it is called).

Just to clarify: 
- you have a `Xamarin.Android` project where you use `Environment.GetFolderPath(Environment.SpecialFolder.Personal)` 
- you upgraded the project to `.NET8 Android` and replaced all references of  `Environment.GetFolderPath(Environment.SpecialFolder.Personal)` to `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` but the old data is not pulled in?

**Comment by ivanicin** [comment]
> Just to clarify:
> 
>     * you have a `Xamarin.Android` project where you use `Environment.GetFolderPath(Environment.SpecialFolder.Personal)`
> 
>     * you upgraded the project to `.NET8 Android` and replaced all references of  `Environment.GetFolderPath(Environment.SpecialFolder.Personal)` to `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` but the old data is not pulled in?

I have deleted the original message as I want to do some more testing, but it does appear to be so - I had some items in the app and I don't see them anymore just an empty list. However as I have tried to "search" for the old database on various paths including Android native APIs it seems not to be present so it might have been somehow deleted during the process... I will test on another device soon to be sure.

**Comment by ivanpovazan** [comment]
Also, keep in mind that the paths can include the app name: `/data/user/0/app_name/files` so if you migrated the project, the app names should remain the same.

**Comment by ivanicin** [comment]
@ivanpovazan  Thanks for your suggestion.

I am shocked at this level of amateurism.

I am not sure if anyone at Microsoft heard for the thing called Nuget packages? You know it is a fairly popular thing, but I have to wander.

Every single package that I use may cause the app to crash or work improperly because you have changed this. And developers have no way to check it aside from real world testing.

I am still not sure if I should laugh for wasting 10 years on the platform that was overtaken by graduate students. Or people that have that level of knowledge in managing of projects.

I mean even if you take this seriously and make this optional in project settings... How can trust someone that obviously can't handle very basic things.

**Comment by ivanicin** [comment]
It is a huge irony that ChatGPT 4o significantly outperforms MAUI team in understanding this issue:

> I work for Microsoft on mobile frameworks. We transition Xamarin to MAUI. 
> 
> For higher level of consistency we want to change the path of Environment.GetFolderPath(Environment.SpecialFolder.Personal). What do you think about that idea?

Changing the path returned by Environment.GetFolderPath(Environment.SpecialFolder.Personal) can have significant implications and should be considered carefully. Here are the key points to consider:

Potential Benefits
Consistency Across Platforms: By standardizing the path, you can ensure a more consistent behavior across different platforms, which is particularly important in a multi-platform framework like MAUI.
Simplified Codebase: Developers would not need to write platform-specific code to handle different paths for personal folders, reducing complexity and potential bugs.
Enhanced Control: It gives you more control over where application data is stored, potentially improving security and data management.
Potential Drawbacks
Breaking Changes: Existing applications relying on the current path will break. This includes apps that store files, access settings, or any other data in the personal folder.
Backward Compatibility: You would need to ensure that there is a smooth transition path for existing applications, which may involve creating migration tools or providing extensive documentation.
User Expectations: Users expect certain behaviors from standard APIs, and changing these can lead to confusion and frustration.
Considerations
Deprecation Strategy: Instead of an immediate change, consider a deprecation strategy where the old path is supported for a while before completely switching over.
Configuration Options: Allow developers to override the default path if needed, providing flexibility while encouraging a standardized approach.
Communication: Clearly communicate the changes to developers, providing ample documentation and migration guides.
Testing: Extensive testing is required to ensure that the new path works correctly across all supported platforms and that the transition does not introduce regressions.

**Comment by terrajobst** [comment]
@ivanicin 

I appreciate that the behavior of core APIs can be frustrating when considering them across multiple platforms. What I don't appreciate is the hostile nature of your comments. You won't get better traction on this issue by using this tone of voice; if anything, it means others have less empathy for your situation and are less eager to help. This includes both us, as well as other community members who might willing to submit PRs.

Please follow the [Code of Conduct](https://dotnetfoundation.org/about/policies/code-of-conduct). If you choose to keep being abusive, we'll eventually be forced to block you.

**Comment by ivanicin** [comment]
@terrajobst 

If a customer provides you info like this, it is not called "abuse", it is called "a last chance". As marketing theory says your loyal customers will complain, those that are not loyal will simply leave without complaining and that is what most of the customers do.

This issue is so great in portraying of everything that is wrong in Microsoft. You prefer theoretical software solutions over those that work in the real world. Making Windows 10 Mobile a side product of Windows 10 was one such decision that in theory was great and in practice it completely ruined the product.

I am not trying to make you to fix this issue, actually if you ask me this issue is not fixable anymore. Now you have a chaos in the ecosystem where various packages depending on their age and developer expect different things and whichever variant you opt to can cause some packages not to work properly (and to compile well). Literally the only right thing to do is to deprecate everything and start clean.

The other thing that is wrong is that your engineers are paid very well (let's not quote their wages) and part of their job is to take part on the customer facing issues. For some reason they are less receptive to this than even indie open-source developers that work for free and start to complain on "abuse" for the minor things (it means that I had one more such issue and your developer has stalked me over the internet and talked on public forums that I abused him for really a very minor thing (!!!???)). It is your right to tolerate that, but that won't lead you anywhere. I haven't heard of a single corporation that works that way, if this was the right way to do the business everyone would implement it. Every successful corporation appreciate its customers and tolerate their negative feelings (to some extent) when they are objectively caused by the product of corporation. If we talk about empathy, that is what empathy is. 

To conclude, I am unlikely to post here anymore. I have moved my iOS app away from .NET and it seems that I need to do that for Android app too. There is nothing personal in that, I certainly won't spend few months of my life on a project just because someone put a wrong word on me, but because you don't meet some very basic standards to be considered as a reliable platform (at least for the mobile app development). Like it or not.

**Comment by terrajobst** [comment]
@ivanicin

> If a customer provides you info like this, it is not called "abuse", it is called "a last chance".

We don't mind customers telling us when the products don't work. We don't mind customers telling us when they are frustrated and wish the product would have certain features, work differently, or not have certain bugs. In fact, we love when customers do that.

But there is a big difference in constructive negative feedback and insulting/attacking the people working on it. I will generally tolerate a lot of colorful language so long it's directed at the product, not the people.

Your comments were directed at the people and that's where we draw the line.

> To conclude, I am unlikely to post here anymore.

You're more than welcome to stop participating if you don't like this community.

**Comment by ajs1037** [comment]
> * Environment.GetFolderPath(Environment.SpecialFolder.Per

This is what i am running into. Any suggestions?

**Comment by yevgeny-sotnikov** [comment]
> > Will it keep same folder path on iOS and mac (same as at xamarin)? I don't want to change current folder of files for all platforms
> 
> It depends on which folder you would expect to retrieve. The following tables describe the difference between the behavior in previous releases (and the introduced breaking change in .NET8).
> .NET 7 	Android 	iOS 	MacOS
> Environment.GetFolderPath(Environment.SpecialFolder.Personal) 	/data/user/0/app_name/files 	/var/mobile/Containers/Data/Application/app_guid/Documents 	/Users/username/
> Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) 	/data/user/0/app_name/files 	/var/mobile/Containers/Data/Application/app_guid 	/Users/username/
> .NET 8 			
> Environment.GetFolderPath(Environment.SpecialFolder.Personal) 	/data/user/0/app_name/files/Documents 	/var/mobile/Containers/Data/Application/app_guid/Documents 	/Users/username/Documents
> Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) 	/data/user/0/app_name/files 	/var/mobile/Containers/Data/Application/app_guid 	/Users/username/
> 
>     * If you expect to retrieve the `$HOME` directory, then as the documentation states you should be using `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)`
>       
>       * NOTE: Please note that $HOME on iOS devices is not writable
> 
>     * If you expect to retrieve the `Documents` folder, then you should keep using `Environment.GetFolderPath(Environment.SpecialFolder.Personal)`
> 
> 
> Please let us know if you have any other question.

@ajs1037 this is the solution
