### ISSUE TITLE
Legacy code crashes in net 8.0 runtime

### ISSUE THREAD

**Issue by luithefirst** [dotnet/runtime#102338]
### Description

Hello! 
We have some legacy code with an "unsafe" optimization, that causes an exception after a couple of iterations. 

The ReadArray<T> method "casts" T[] to a byte array, by overwriting its typeId and adjusting the size accordingly.

I assume that after a couple of iterations, the tiered compilation generates a code that checks the array length with the original value and not the hacked one.

### Reproduction Steps

```cs
using System;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

namespace Test
{
    public class Program
    {
        public class ArrayReader : BinaryReader
        {
            public ArrayReader(Stream stream) : base(stream) { }

            [StructLayout(LayoutKind.Explicit)]
            struct ByteArrayUnion
            {
                [FieldOffset(0)]
                public byte[] bytes;
                [FieldOffset(0)]
                public Array structs;
            }

            private static IntPtr s_byteId = GetTypeIdUncached<byte>();
            private static IntPtr GetTypeIdUncached<T>() where T : struct
            {
                var gcHandle = GCHandle.Alloc(new T[1], GCHandleType.Pinned);
                var typeField = gcHandle.AddrOfPinnedObject() - 2 * IntPtr.Size;
                var typeId = Marshal.ReadIntPtr(typeField);
                gcHandle.Free();
                return typeId;
            }

            public long ReadArray<T>(T[] array, long index, long count)
                where T : struct
            {
                if (count < 1) return 0;

                unsafe
                {
                    var sizeOfT = Unsafe.SizeOf<T>();
                    var hack = new ByteArrayUnion();
                    hack.structs = array;

                    var bytesToRead = (int)(sizeOfT * count);
                    IntPtr byteLen = (IntPtr)(array.Length * sizeOfT);
                    var offset = (int)(index * sizeOfT);

                    fixed (byte* pBytes = hack.bytes)
                    {
                        IntPtr* pId = (IntPtr*)(pBytes - 2 * IntPtr.Size),
                                pLen = (IntPtr*)(pBytes - IntPtr.Size);
                        IntPtr backupId = *pId, backupLen = *pLen;
                        *pId = s_byteId; *pLen = byteLen;

                        do
                        {
                            int finished = base.Read(hack.bytes, offset, bytesToRead); // Exception occurs here
                            if (finished == 0) break;
                            offset += finished; bytesToRead -= finished;
                        }
                        while (bytesToRead > 0);

                        *pId = backupId; *pLen = backupLen;
                    }
                    return ((long)(offset / sizeOfT) - index);
                }
            }
        }

        public static void ReadArrayTest()
        {
            var filename = Path.GetTempFileName();     
            
            using (var file = File.Create(filename))
            {
                using (var writer = new BinaryWriter(file))
                {
                    writer.Write(128);
                    for (int i = 0; i < 128; i++)
                        writer.Write(0.0f);
                }
            }

            for (int i = 0; i < 1000; i++)
            {
                Console.WriteLine("Read");
                using (var stream = File.Open(filename, FileMode.Open))
                {
                    var reader = new ArrayReader(stream);

                    var cnt = (int)reader.ReadInt32();
                    var fa = new float[cnt];
                    reader.ReadArray(fa, 0, cnt);
                }
                Thread.Sleep(100);
            }
        }

        public static void Main(string[] args)
        {
            ReadArrayTest();
        }
    }
}
```

### Expected behavior

Not crash

### Actual behavior

Crashes after a couple of iterations at line 58 with the following exception:
```System.ArgumentException: 'Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.'```

### Regression?

The exception does not occur when the project TargetFramework is changed to net 6.0.
However, it still occurs when compiled as netstandard 2.0 assembly and referenced in a net8.0 project.

### Known Workarounds

Rewrite with `Span<byte>`.

Unfortunately, we still also need to target net48 where `BinaryReader.Read` does not have an overload with `Span<byte>`. We decided to keep the code as is for net48 and use Span in net 6.0 onwards.

### Configuration

net 8.0, x64, Windows 10

### Other information

For us, this issue is not critical, but it might help you to improve the robustness of the compiler optimizations. Thanks!

**Comment by tannergooding** [comment]
> The ReadArray method "casts" T[] to a byte array, by overwriting its typeId and adjusting the size accordingly.

This is strictly undefined behavior and there is zero expectation that things work if you go and start changing things like this.

There is not really anything for dotnet/runtime to do, the fix is for you to change your code to not do unsafe/undefined things.

CC. @jkotas

**Comment by DaZombieKiller** [comment]
> Unfortunately, we still also need to target net48 where `BinaryReader.Read` does not have an overload with `Span<byte>`.

The first-party `CommunityToolkit.HighPerformance` package has [a polyfill for span-based `Stream.Read`](https://learn.microsoft.com/en-us/dotnet/api/communitytoolkit.highperformance.streamextensions.read?view=win-comm-toolkit-dotnet-7.0#communitytoolkit-highperformance-streamextensions-read(system-io-stream-system-span((system-byte)))). `BinaryReader.Read` is just a wrapper for `Stream.Read`, so you could forward to the extension method on .NET Framework. I would strongly suggest that over the UB-riddled implementation described in the OP. The `CommunityToolkit` implementation uses `ArrayPool` to allocate a temporary buffer, making it roughly equivalent to the base `Stream.Read(Span<byte>)` in the BCL.

**Comment by jkotas** [comment]
The UB behavior you are seeing is by design. The fix is for you to change your code to not do unsafe/undefined things as @tannergooding said.

**Comment by luithefirst** [comment]
I already expected that you would also see this implementation as undefined behavior, but I still wanted to bring this up since I would assume that a C++ compiler would not be fooled by such trickery. Luckily such hacks are no longer needed.

Thank you for the suggestion on how to remove this old code completely!

**Comment by tannergooding** [comment]
> since I would assume that a C++ compiler would not be fooled by such trickery

Such behavior is strictly undefined in C/C++ as well and while there are some simple cases that compilers can figure out, there are thousands of examples of the same compilers failing at doing aliasing analysis or intentionally recognizing the undefined behavior and doing something else instead for performance reasons.

This is such a prevalent problem in the C/C++ world that some examples of optimizations that compilers like `Clang` have done have caught the attention of the C/C++ language committees and they are intentionally making breaking changes to the spec to block such undefined behavior.

--------------------------------

One example is that the following program takes advantage of the fact that infinite loops are undefined in the latest language version:
```cpp
#include <iostream>

int main()
{
  while (1);
  return 0;
}

int unreachable()
{
  std::cout << "Hello!" << std::endl;
  return 1;
}
```

As such, clang will generate something such as the following, where calling `main` actually executes the code from `unreachable`:
```asm
main:                        # @main
unreachable:                 # @unreachable()
    push     rbx
    mov      edi, offset std::cout
    # ...
```

Notably the C++26 spec is trying to change such trivial infinite loops to be well-defined so Clang would not longer be allowed to do this optimization by default: https://isocpp.org/files/papers/P2809R3.html

-----------------------------

Another example is that signed integer overflow is undefined behavior in C++, and so you should consider the following program:
```cpp
#include <stdint.h>
#include <stdio.h>

void Test()
{
    int x = 2147483643; // int.MaxValue - 4
    
    if (x > 0)
    {
        int y = x + 5;
    
        if (y < 0)
        {
            printf("beef");
        }
        else
        {
            printf("chicken");
        }
    }
}

void Test2(int x)
{
    if (x > 0)
    {
        int y = x + 5;

        if (y < 0)
        {
            printf("beef");
        }
        else
        {
            printf("chicken");
        }
    }
}

void Test3() { Test2(2147483643); }
```

Where we get 3 different and entirely inconsistent behaviors:
* `Test` optimizes down to printing just `beef`
* `Test2` actually executes the code as given and will print `beef` or `chicken` based on the underlying platform behavior
* `Test3` will print `chicken` if `Test2` is inlined and will behave the same as `Test2` if it is not inlined.

------------------------

Aliasing tends to be a bit more complex to trigger bugs around and there's places that the compiler will correctly recognize reinterpret cast and basic unions. But its also possible to trip it up and cause issues. Most such aliasing issues come about from one view of the data optimizing under the assumption the corresponding data should be immutable/readonly/const where another view is unsafely overwriting that data. You can also run into issues by one accessor of the data not understanding that another accessor is an alias to that data and so on.

.NET will itself also handle some types of simple aliasing and trip up on others in the same fashion. However, actually rewriting the underlying object header metadata can lead to issues such as tearing of state across threads (and there is also at least the GC running in the background) or otherwise pessimizing optimizations the JIT may do such as guarded devirtualization where an early path may have checked the type or something like CSE could have kicked in and  cached the length so that it didn't have to recompute that data again later and so on.

You cannot and should not rely on undefined behavior. You can sometimes depend on implementation defined behavior when you know you won't be changing implementations and the can test/adjust if the implementation changes, but that's not what you're doing here. And most importantly, even in C/C++, doing these things fundamentally breaks portability and can lead to breaks when the code is compiled for new platforms, operating systems, architectures, etc.

**Comment by luithefirst** [comment]
Thank you for the detailed answer! So it sounds like C++ struggles even more with optimizations in way more cases. I also did not know that signed integer overflows are undefined behavior.

We already started eliminating all code that was using such hacks. For our net48 targets we actually no longer care about performance and first benchmarks of rewritten methods with span or similar in the net 6.0 targets (running on net 8.0) show that they outperform the old implementations :smiley:
