### ISSUE TITLE
Why the D value of RSA is different

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#102418]
```
var privatekeyBytes = Convert.FromBase64String("");

var rsa = RSA.Create(); rsa.ImportPkcs8PrivateKey(privatekeyBytes, out _);

var privateParameters = rsa.ExportParameters(true);
var d = Convert.ToBase64String(privateParameters.D!);
```

Why do RSA objects with the same key have different D values, I got the same D value on my local Windows computer as on another Linux computer, But I got a different D value on another Windows

**Comment by bartonjs** [comment]
What it really boils down to is "we send the values to the underlying cryptography libraries, and they send us back whatever we want".  D-Phi vs D-Lambda is the usual reason, but there may be others.

Since it's not .NET that's actually changing the values, I can't really offer any more of a "why" than I already have.

**Comment by bartonjs** [comment]
I don't know of anyone that can answer that question with public contact, no.

Looking through history I see that we added the "tolerate it changing" code in 2018 https://github.com/dotnet/runtime/commit/f0d034c40321b674e2e01707261e90ef6e6ae07d, and in 2019 I have an email thread asking "Hey, did you start being D-preserving all of a sudden?" to which they said basically "Yeah, because too many people complained.  You know, like you did?"

If you're seeing a change between Windows Server 2019 and Win 10-current, then it probably changed in 19H1 or 19H2.

**Comment by danmoseley** [comment]
@Varorbc Can you describe why it's painful in your scenarios?

**Comment by SteveSyfuhs** [comment]
Why is _this_ differing behavior a problem though? The fact that it's different does not explain why that makes it painful. Why do you need to solve it? Why does a changing `D` value cause you problems?

**Comment by bartonjs** [comment]
The D value being different doesn't matter to the RSA algorithm, they both should produce an equivalent result.

If something's using a hash of the key file, then the different bytes would be a problem, sure.  In that case, it seems like upgrading to a newer version of Windows will solve the problem (based on the 2019 email that I forgot about, suggesting Windows changed to D-Preserving then).  Or you can try using RSACryptoServiceProvider and see if you get more amenable results.

**Comment by bartonjs** [comment]
I don't know what specific version for either the client or server SKUs, no.  Based on the email I ran across, and the previous note, we noticed that Windows changed behavior in 2019.  So maybe that's 19H1, maybe 19H2, maybe 20H1; and I don't know the server SKU branding/alignment.

Since this has devolved into a question about Windows releases and a "why" that only Windows can really answer; I'm going to go ahead and hit close with this comment.

**Comment by SteveSyfuhs** [comment]
You haven't explained why this _is_ an issue though. You're saying it's different, but why does it being different cause you a real problem?

**Comment by SteveSyfuhs** [comment]
Okay but why is that a problem? You can get `D` without issue. Functionally it is a value that is allowed to change. Why does it changing introduce a problem? Sure, behavior is different, but any RSA library is going to be able to handle the math correctly regardless of how `D` was derived.
