### ISSUE TITLE
Activity id of nettrace events are always 0  

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#102411]
### Description

I noticed in all the nettrace collected from prod, all the ActivityId are RelatedActivityId are 0. One of the consequence is that the RequestStart/Stop events from ASP.NET Core can't be correlated. 

### Reproduction Steps

1.
```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.MapGet("/", () => { });
app.Run();
```
2. `dotnet trace collect --process-id $PID --providers Microsoft-AspNetCore-Server-Kestrel --clreventlevel verbose`
3. Open the nettrace and observe that all ActivityId are equal to Guid.Empty

### Expected behavior

I would expect to have non-0 ActivityId to correlate requests.

### Actual behavior

All ActivityIds are 0.

### Configuration

.NET: 8.0.105
OS: Windows
Arch: x64

**Comment by tommcdon** [comment]
@noahfalk

**Comment by noahfalk** [comment]
This probably could be documented a little more clearly, but ActivityIDs are off by default so the behavior you see appears to be by design. If you want to turn them on you need to add provider System.Threading.Tasks.TplEventSource with keyword 0x80 ([TasksFlowActivityIds](https://source.dot.net/System.Private.CoreLib/R/041b901aa973edef.html)). Check out the sample at https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventsource-activity-ids#tracking-work-using-an-activity-id.

**Comment by verdie-g** [comment]
I didn't know about that thanks! I was able to get the activity ids using
```
dotnet trace collect --process-id $PID --providers Microsoft-AspNetCore-Server-Kestrel:0x0:informational,System.Threading.Tasks.TplEventSource:0x80:informational
```
