### ISSUE TITLE
Incorrect configuration mapping

### ISSUE THREAD

**Issue by VeselovAndrey** [dotnet/runtime#102609]
### Description

The specified JSON configuration is incorrectly mapped to the settings class. 
Looks like it correctly read but then mapping to C# class goes wrong because of optional part:

The case: settings have a sequence of objects with optional property.

### Reproduction Steps

JSON:
```json
{
  "complexSequence": [
    { "id": 1, "title": "Title 1" },
    { "id": 2, "title": "Title 2" },
    { "id": 3, "title": "Title 3", "codes": [ 89, 56 ] }
  ]
}
```
Related C# models:
```csharp
public class TestSettings
{
	public required MappingWithOptionalArray[] ComplexSequence { get; init; }
}

public record MappingWithOptionalArray(int Id, string Title, int[]? Codes);
```

C# Test code:
```chsarp
	[Fact]
	public void Configuration_ParseAndMap_Success()
	{
		// Arrange
		IHostBuilder appBuilder = Host.CreateDefaultBuilder()
			.ConfigureAppConfiguration((hostingContext, config) => {

				config.AddJsonFile("config.json");
			})
			.ConfigureServices((hostContext, services) => { services.Configure<TestSettings>(hostContext.Configuration); });
		IHost host = appBuilder.Build();

		// Act
		TestSettings settings = host.Services.GetRequiredService<IOptions<TestSettings>>().Value;

		// Assert
		Assert.NotNull(settings);
	}
```

### Expected behavior

The `settings` variable must contains 3 elements with Id from 1 to 3.
First and second elements must have Code == null.
And 3rd element must have 2 items in the "Code" array.

### Actual behavior

The `settings` has single element with 
Id = 3
Title = Title 3
Codes = [ 89, 56, 89, 56 ]

Please note that Codes duplicated twice.
Records with Id = 1 and 2 are missing from `settings' array.

I checked what `JsonConfigurationFileParser` returns and it's looks valid.
```
Count = 8
{[complexSequence:0:id, 1]}
{[complexSequence:0:title, Title 1]}
{[complexSequence:1:id, 2]}
{[complexSequence:1:title, Title 2]}
{[complexSequence:2:id, 3]}
{[complexSequence:2:title, Title 3]}
{[complexSequence:2:codes:0, 89]}
{[complexSequence:2:codes:1, 56]}
```
Looks like problem is in the binding.

### Known Workarounds

I didn't find any workaround. 
Adding empty arrays to first 2 elements are not helping (result is the same).
Adding non-empty arrays to all elements give Code duplicating values for all 3 elements.

### Configuration

.NET SDK 8.0.300

**Comment by tarekgh** [comment]
For the first issue which is the binding not able to bind the first two entries of the array:

```json
    { "id": 1, "title": "Title 1" },
    { "id": 2, "title": "Title 2" },
```

This is because these are missing the `Codes` property and in same time you are defining the record as 

```C#
public record MappingWithOptionalArray(int Id, string Title, int[]? Codes);
```

For the binding to create a new record instance will need to have the values of all parameters `Id`, `Title`, and `Codes`. You cannot assume the absence of `Codes` value means to assign `null` to it when creating the record. The record needs to explicitly declare that by setting the default value for such parameter. So, if you want to make this work, make the `Codes` parameter has a default value like:

```C#
public record MappingWithOptionalArray(int Id, string Title, int[]? Codes = null);
```

For the second issue regarding the duplication of the array elements, it is known issue and tracked by https://github.com/dotnet/runtime/issues/83803. The easiest workaround is not using Records or use Record but not use primary constructor, instead list the parameters as a properties instead.

**Comment by VeselovAndrey** [comment]
@tarekgh Thank you for the response and explanation.
