### ISSUE TITLE
Regex parser regression

### ISSUE THREAD

**Issue by jacobzed** [dotnet/runtime#102643]
### Description

The following regex doesn't match in .net 8. The same regex matches in framework 4.72.

### Reproduction Steps

```
var re = new Regex(@"^(.+?) (says?),\s'(.+)'$", RegexOptions.RightToLeft);
var sample = "User says, 'adventure'";
var match = re.Match(sample);
Console.WriteLine(match.Success); // should return true like in 4.72

```

### Expected behavior

Regex match success

### Actual behavior

Regex match fails

### Regression?

Yes, this works in Framework 4.72

### Known Workarounds

Removing RegexOptions.RightToLeft, or putting "s?" outside capturing group:
`var re = new Regex(@"^(.+?) (say)s?,\s'(.+)'$", RegexOptions.RightToLeft);`

**Comment by steveharter** [comment]
Did verify the repro. .NET v6 returns `true` while v7 returns `false`, so the behavior changed in v7.

The `RegexOptions.RightToLeft` is causing this to fail.

**Comment by steveharter** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
Looks like this was introduced as part of an optimization that shouldn't be applying to RTL. We're looking to see whether we can combine loops with a multi that comes after it (a multi follows a loop in the example pattern because RTL ends up reversing concatenations), but because of the RTL we're looking at the wrong end of the multi, so it ends up erroneously combining the `s?` with the `s` that begins "say".
