### ISSUE TITLE
Rsa.Encrypt() is retuning "Error occurred during a cryptographic operation" after migration from .net6 to .net8

### ISSUE THREAD

**Issue by pamedasa** [dotnet/runtime#102620]
### Description

After the migration from .net6 to .net8, encountered the error - "System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.". The same code is working if we use .net6 but it is failing after moving to .net8.

**rsaKey.Encrypt(Encoding.Default.GetBytes("Hello World!"), RSAEncryptionPadding.OaepSHA256)**

Any help would be really helpful.

### Reproduction Steps

RSA creation for ssh-rsa file with below parameters:
  // Create RSA RSA.
  var rsa = RSA.Create(new RSAParameters()
  {
      Exponent = exponentBytes,
      Modulus = modulusBytes
  });

### Expected behavior

RSA key encryption and decryption should work as expected

### Actual behavior

Returning an error in "System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation."

### Regression?

it is working in .net6

### Known Workarounds

No

### Configuration

.net8, Windows2022 with x64 configuration.

### Other information

N/A

**Comment by bartonjs** [comment]
If you can share a public key for which this is true, that would be useful (and probably required for us to do anything).

In the meantime:

Does either Modulus or Exponent contain leading zero-value bytes?  What's the callstack of the exception (how deeply has it gone before it gets an error)?

**Comment by pamedasa** [comment]
@
[Test_SshKeyPairValidator_Success_PublicKey.txt](https://github.com/dotnet/runtime/files/15420988/Test_SshKeyPairValidator_Success_PublicKey.txt)
Please find the attached public key file and exception returned from library doesn't have any stack trace. Only below is popping out:
RSABCrypt.Encrypt(Byte[] data, RSAEncryptionPadding padding)

**Comment by pamedasa** [comment]
Can see Modulus has leading 0. Could you please confirm is this latest enforcement/check from .net8 because it is working in .net6?

**Comment by bartonjs** [comment]
That input is not easily paired with your repro, as the error might lie in how you're breaking the file down into the modulus and exponent.

Please provide a fully-contained working example.  Either by just sharing the modulus and exponent values you have (hex strings, base64 strings, whatever), or by including whatever code is necessary to break that file down so that it can be combined with the snippet above.

**Comment by bartonjs** [comment]
> Can see Modulus has leading 0. Could you please confirm is this latest enforcement/check from .net8 because it is working in .net6?

I don't believe we ever check for a leading zero in the modulus (or exponent).  We take whatever we were given and pass it down to the underlying library.

In .NET 8 on Windows we changed `RSA.Create()` from being powered by the Windows CNG library `ncrypt.dll` to the Windows CNG library `bcrypt.dll`.  The BCrypt implementation and NCrypt implementation may handle the leading zero problem differently.  That's generally considered as invalid input, and so you're subject to "implementation-dependent behavior".

Since this isn't the first "modulus started with a leading 0" problem I've heard this week, maybe we should add detection for it and throw an ArgumentException.

**Comment by pamedasa** [comment]
Exponent:
![image](https://github.com/dotnet/runtime/assets/30529404/5498d89a-927e-4ad1-bda7-62576e913819)

Modulus:
![image](https://github.com/dotnet/runtime/assets/30529404/80bc9c2c-46c0-48a9-af0e-6e44a39a74f2)

**Comment by pamedasa** [comment]
Also, please suggest on how to handle this issue with keys with parameters having leading 0's.

**Comment by bartonjs** [comment]
You need to remove them.

```C#
byte[] modulus = ...;

if (modulus[0] == 0)
{
   int start = 1;

   while (modulus[start] == 0)
   {
        start++;
   }

   modulus = modulus.AsSpan(start).ToArray();
}
```

is one such way.

**Comment by pamedasa** [comment]
Thank you for quick response and it will great help for folks in throwing proper error message otherwise hard to root cause it.
