### ISSUE TITLE
Exception in BlazorWasm applications due to NullabilityInfoContext usage

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#102848]
### Description

This was introduced in https://github.com/dotnet/runtime/pull/102499. This blocking runtime ingestion in ASP.NET for preview 5.

This exception is thrown when running a BlazorWasm application.

```
NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it.
```

The BlazorWebAssembly SDK disabled the feature https://github.com/dotnet/sdk/blob/a304e06708d72c1be0d78e214366a2c7c601b5d8/src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets#L49

[This method](https://github.com/dotnet/runtime/pull/102499/files#diff-2c25e4fef8b91fb8a23c1ec3e0f9d3a1473a895c7b4b978018a2762e60cc9133R490) should check `NullabilityInfoContext.IsSupported` is `true` before using calling `NullabilityInfoContext.Create`.

### Reproduction Steps

Run a BlazorWebAssembly application like this one:

https://github.com/dotnet/aspnetcore/blob/release/9.0-preview5/src/Components/WebAssembly/testassets/StandaloneApp/StandaloneApp.csproj

### Expected behavior

Application should not throw an exception when the `System.Reflection.NullabilityInfoContext.IsSupported` flag is `false`.

### Actual behavior

An exception is thrown.

### Regression?

Yes

### Known Workarounds

Enable the `System.Reflection.NullabilityInfoContext.IsSupported` switch.

**Comment by Jozkee** [comment]
[System.Reflection.NullabilityInfoContext.IsSupported](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md) is used by apps to trim nullability annotations, as @eiriktsarpalis mentioned offline, we could bail when the switch is set to false and process things like they were nullable-oblivious, but it feels odd that NullabilityInfoContext throws here rather than returning `new NullabilityInfo { ReadState = NullabilityState.Unknown, WriteState = NullabilityState.Unknown }`.

cc @buyaa-n @eerhardt
