### ISSUE TITLE
[API Proposal]: Implement `ISpanFormattable` on `string`

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#103176]
### Background and motivation

In our program, we have a settings system built on `ISpanFormattable` and `ISpanParseable<T>`. `string` currently implements `ISpanParseable<T>`, but not `ISpanFormattable`.

### API Proposal

```csharp
namespace System;

public class string : ISpanFormattable, IFormattable
{
    // implemented as explicit interface implementations as they're useless outside generics

    public string IFormattable.Format(string? format, IFormatProvider? formatProvider) =>
        this;
    public bool ISpanFormattable.TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        if (Length < destination.Length)
        {
            charsWritten = 0;
            return false;
        }
        this.CopyTo(destination);
        charsWritten = Length;
        return true;
    }
}
```

### API Usage

Anywhere `ISpanFormattable` is useable

**Comment by teo-tsirpanis** [comment]
Because `string.ToString()` returns `this` and therefore does not allocate, there is no need to implement `ISpanFormattable` on string.

Similarly, because the string representation of a string is always the same and not dependent to a culture or format, there is no need to implement `IFormattable` either.

**Comment by stephentoub** [comment]
Not only is there no need, it would also make certain operations _more_ expensive. Various formatting code that supports ISpanFormattable involves a loop where it tries to format with a certain buffer size and if formatting fails because the buffer is too small, grows the buffer by some amount (often doubling), and then tries again. For long strings, it might do that loop several times, and unnecessarily, because the fallback for the lack of ISpanFormattable is typically to call ToString, which for a string is free, and at that point those consumers end up knowing exactly how much space is needed. This is why when this has previously been proposed we've rejected doing so. Thanks for the suggestion, though.

**Comment by colejohnson66** [comment]
Understandable. It’s a shame that `ISpanFormattable` isn’t designed in such a way to indicate how many characters would actually be required, like `Encoding` does. Theoretically, `charsWritten` could’ve been `charsWrittenOrNeeded`, and the return value indicates which.

I still think `IFormattable` would be reasonable. There’s many cases where one wants to serialize something with the invariant culture, but `where T : IFormattable` excludes `string`.

**Comment by stephentoub** [comment]
> I still think IFormattable would be reasonable. There’s many cases where one wants to serialize something with the invariant culture, but where T : IFormattable excludes string.

What are the situations where you want to exclude types that don't implement IFormattable? The vast majority case I see is special-casing IFormattable but not constraining to it, falling back to regular ToString() if ToString(format, culture) isn't available.

**Comment by colejohnson66** [comment]
As I said, we have a settings system of `Setting<T> where T : IFormattable`.
