### ISSUE TITLE
CultureInfo "arb" is not a Textinfo.IsRightToLeft Language

### ISSUE THREAD

**Issue by Larhei** [dotnet/runtime#103131]
### Description

When doing CultureInfo.GetCultureInfo("arb") the cultureinfo i get has TextInfo.IsRightToLeft set to false.
When doing CultureInfo.GetCultureInfo("ar") the cultureinfo i get has TextInfo.IsRightToLeft set to true.
When doing CultureInfo.GetCultureInfo("ara") the cultureinfo i get has TextInfo.IsRightToLeft set to true.

I´m not the expert on Iso639 also not on arabic.
But shouldn´t
Generic Arabic and Standard Arabic be the same reading direction?
[Generic Arabic](https://iso639-3.sil.org/code/ara)
[Standard Arabic](https://iso639-3.sil.org/code/arb)

### Reproduction Steps

var x = CultureInfo.GetCultureInfo("arb");
Console.WriteLine(x.EnglishName);
Console.WriteLine(x.TextInfo.IsRightToLeft);

var y = CultureInfo.GetCultureInfo("ar");
Console.WriteLine(y.EnglishName);
Console.WriteLine(y.TextInfo.IsRightToLeft);

### Expected behavior

Same behaviour on arabic languages

### Actual behavior

Different behaviour on arabic languages

### Regression?

Tested on Fullframework.. "arb" and "ara" is unknown.
On .Net Core from 3.1 up to now the issue described can be reproduced.
So something changed between .Net 4.8 and .Net Core. But because it never worked. I would call it, something new.

**Comment by Clockwork-Muse** [comment]
The data used to determine right/left languages, among other things, [is (usually) provided by the host OS, and is not something maintained by the dotnet runtime](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu).  Presumably we're mimicking the host datasource, unless you've noticed a difference?

**Comment by tarekgh** [comment]
Please have a look at the [doc](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) for the globalization behavior change in .NET 5+. 

For your specific case, when running on .NET Framework or .NET Core up to not including .NET 5.0, we used to depend on NLS (when running on Windows). NLS recognizes only two letter language code (i.e.  [`ISO 639-1 Code`](https://www.loc.gov/standards/iso639-2/php/code_list.php)). This means the only valid code is `ar`. The `ara` and `arb` will be invalid. 

In .NET 5.0 and later, we started to use ICU library instead of NLS. ICU can recognize the two and three letters language code. (i.e. support [`ISO 639-1 and ISO 639-2 Codes`](https://www.loc.gov/standards/iso639-2/php/code_list.php)). This will make `ar` and `ara` supported. But `arb` will be invalid code to support. 

I hope this explain the behavior you are seeing.

**Comment by Larhei** [comment]
@tarekgh 
Thanks for the directions. May I ask why/how CultureInfo.EnglishName know that arb is Arabic. if the code is invalid?
In Fullframework returned Unknown? Just asking out of curiosity.

**Comment by tarekgh** [comment]
I tried that on .NET 8.0 and I am seeing 

```C#
            Console.WriteLine($"{CultureInfo.GetCultureInfo("arb").Name}, {CultureInfo.GetCultureInfo("arb").EnglishName}, {CultureInfo.GetCultureInfo("arb").TextInfo.IsRightToLeft}");
```

produces:

```
arb, arb, False
```

So, the English name is just `arb` and not `Arabic`. This is just ICU library uses the same culture name for the English name. For NLS, the culture is not recognized too and at that time it decides to use `Unknown` for the English name.

**Comment by Larhei** [comment]
@tarekgh 
Well  my fault not compiling it on my machine.
For windows this seems to be true.
But not here:
[dotnetfiddle.net](https://dotnetfiddle.net/Q2Gh7k)

**Comment by tarekgh** [comment]
You are right. It is the change in the ICU version. ICU version `68` used on Windows gives the name `arb`. ICU version `70+` gives the name `Arabic`. Anyway, I don't think you need to use `arb` code at all as it is invalid.

**Comment by Larhei** [comment]
@tarekgh 

I agree that it is technical incorrect. But this gives me a little bit more understanding why when compiling on windows CultureInfo is different compared to when compiling on mac. 

Example:
This code of a Maui App result in different results for iOS when compiled on Mac or Windows.
preference is a string like "de-DE"
`var culture = CultureInfo.GetCultures(CultureTypes.AllCultures).FirstOrDefault(c => c.Name == preference);

#if ANDROID
            var name = culture?.DisplayName;
#elif IOS
            var name = culture?.NativeName;
#6166`

name give different results on IOS when compiled from a windows or mac. And that´s because of ICU.
Well having Build agents on different machines and different OS versions also can lead to different results of CultureInfo related code. And in order to fix this we have RuntimeHostConfigurationOption to pin a specific version on all platforms.

Thank you very much for this lesson.

**Comment by Clockwork-Muse** [comment]
> This code of a Maui App result in different results for iOS when compiled on Mac or Windows.

Where this code was compiled shouldn't make a difference.  It will make a difference depending on where it was _run_.

That aside, that code should really look something like:
```csharp
var culture = CultureInfo.GetCultureInfo(preference, predefined: false);
// Or maybe this one
var culture = CultureInfo.GetCultureInfo(preference, cultureDefault);

// Just use the display name, platform shouldn't make a difference here:
var name = culture.DisplayName;
```
In particular on mobile, iterating through all the cultures will be a large performance penalty/hit.

> name give different results on IOS when compiled from a windows or mac. And that´s because of ICU.

Sure, but you normally shouldn't care.  Generally you should just use whatever value is output uncritically.  You _can_ pin the version, if your build infrastructure supports it, but even when that's the case you shouldn't make any assumptions about the contents of the data provided.
That is, don't pin it so that a particular value will be returned, only pin it so that all machines would have the same data, regardless of what it is.

**Comment by Larhei** [comment]
@Clockwork-Muse 
If culture.DisplayName should be the same on all platforms no matter where they are build. How comes when plugging a physical iPhone onto a Windows machine result in something different as when doing the same on an arm mac? I can retest this tomorrow... But last time worked on that Code they where different.

**Comment by Clockwork-Muse** [comment]
> If culture.DisplayName should be the same on all platforms no matter where they are build.

This isn't the best way to phrase it.

The `DisplayName` is also a resource coming from the localization files, so can be different on every actual deployed platform or instance of a platform (ie, two otherwise identical iPhones aren't guaranteed to output the same data even if running the same build of an application).

For two different builds of the same source deployed to the same platform instance the data should be the same.  If it's not, we may have a compile bug.
Otherwise.... you may be doing an app-local ICU deployment, and including the host resources (instead of some static resource version, which is what you would normally do in such a situation).
