### ISSUE TITLE
DataRows SetModified and SetAdded is not the same between the code and the document

### ISSUE THREAD

**Issue by ThoaiLeOrangelogic** [dotnet/runtime#103157]
https://github.com/dotnet/runtime/blame/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Data.Common/src/System/Data/DataRow.cs#L1378C13-L1391C10

The document said that (https://learn.microsoft.com/en-us/dotnet/api/system.data.datarow.setmodified?view=net-8.0)
![image](https://github.com/dotnet/runtime/assets/171533783/757f00da-a750-4d1c-a2a6-a13cc0d47251)

But in the code it only available for RowState.Unchanged

**Comment by roji** [comment]
The documentation remark itself seems to contradict itself: on the one hand, it says that an exception is thrown "if the current row is not in either an `Unchanged` or an `Added` state`. On the other hand, the exception message is supposed to says that `SetModified` can only be invoked on a `DataRow` instance where the `RowState` is `Unchanged`" (`Added` is missing).

As pointed out above, the actual code is to only allow calling SetModified when the state is Unchanged, and to throw otherwise; I'm guessing the behavior was changed at some point but the documentation was left in an out-of-sync/contradictory state.

Submitted https://github.com/dotnet/dotnet-api-docs/pull/10323 to amend the docs.
