### ISSUE TITLE
No nullable warning for IEnumerable<T> extension methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#10326]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/881135/no-nullable-warning-for-ienumerable-extension-meth.html)._

---
.NET Core 3.1, C# version 8, VS 2019 16.4.2
Even with nullable feature enabled the compiler gives no warning when using Linq extension methods on apparently null variables.

Example: (nullable is enabled for the whole project)

List<string>? list = null;
list. Count(); // No compiler warning! ArgumentNullException in runtime !

---
#### Visual Studio Feedback System on 1/10/2020, 00:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by stephentoub** [comment]
When you write:
```C#
List? list = null;
list.Count();
```
that's actually:
```C#
List? list = null;
Enumerable.Count(list);
```
In .NET Core 3.1, the System.Linq.dll library wasn't yet annotated for nullable reference types, which is why the compiler wasn't warning you on that `Enumerable.Count` call.  It has now been annotated for .NET 5, as part of https://github.com/dotnet/runtime/issues/2339.

Thanks.
