### ISSUE TITLE
Microsoft.Extensions.HostFactoryResolver project is not building

### ISSUE THREAD

**Issue by kasperk81** [dotnet/runtime#103553]
Microsoft.Extensions.HostFactoryResolver project is located in runtime but excluded from runtime build. it is built as part of efcore and aspnetcore. if there was a problem with the code being merged it goes undetected (https://github.com/dotnet/runtime/pull/102152) and blocks the code flow (https://github.com/dotnet/runtime/pull/103523, https://github.com/dotnet/runtime/pull/103546).

@ViktorHofer @ericstj

**Comment by ericstj** [comment]
It's a source package, the source is built by the tests: https://github.com/dotnet/runtime/blob/7e977dcbe5efaeec2c75ed0c3e200c85b2e55522/src/libraries/Microsoft.Extensions.HostFactoryResolver/tests/Microsoft.Extensions.HostFactoryResolver.Tests.csproj#L7

Perhaps the problem here is that the test is disabling some warnings that EFCore and ASPNETCore care about?  Maybe you could suggest what changes to make to the test that would match how EFCore and ASPNETCore consume it?  We're not so much a fan of this package living in runtime - it's only here because it's a place for EFCore and ASPNETCore to share code.  cc @halter73
