### ISSUE TITLE
[Analyzer Proposal]: Remove redundant cast on vectors

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#103557]
### Background and motivation

Strong typing for SIMD often leads to frequent casts from one type of Vector to another (typically, no-op in codegen). Sometimes user might accidentally introduce redundant casts that can be safely removed. I propose an analyzer that highlights such casts. Example:

```cs
return AdvSimd.MultiplyWideningLowerAndAdd(
    AdvSimd.ShiftLeftLogical(
        AdvSimd.AddPairwiseWidening(
            AdvSimd.Multiply(b.AsInt32(),
                AdvSimd.ReverseElement32(a).AsInt32()).AsUInt32()).AsInt64(), 32),
    AdvSimd.ExtractNarrowingLower(a),
    AdvSimd.ExtractNarrowingLower(b)).As<long, T>();
```
Here I had to insert quite a few casts to make it work as expected and it's not obvious whether some of them might be redundant or not. It's not a codegen issue, just an opportunity to make code smaller = easier to read.

### API Usage

```cs
Vector128<ulong> v = Vector128.Create(ulong.MaxValue);
DoWork(v.AsUInt64()); // Flagged with "redundant cast"
```

### Risks

N/A

**Comment by EgorBo** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
> (typically, no-op in codegen).

Notably this is always a no-op, it's fully elided in importation and never produces IR today (barring the case we throw because it is invalid, but that's also statically determined).

We can likely just close this and lump it together with the already approved: https://github.com/dotnet/runtime/issues/82488, which tracks a general analyzer for suggesting more optimal SIMD patterns.
