### ISSUE TITLE
System.IO.FileSystem.AccessControl depends on deprecated version of System.Security.AccessControl

### ISSUE THREAD

**Issue by avivanoff** [dotnet/runtime#104047]
### Description

The latest version 5.0.0 of System.IO.FileSystem.AccessControl depends on deprecated version 5.0.0 of System.Security.AccessControl.

### Reproduction Steps

1. Create a project that references System.IO.FileSystem.AccessControl 5.0.0.
2. Build the project.

### Expected behavior

The project pulls in deprecated version of 5.0.0 System.Security.AccessControl.

### Actual behavior

System.IO.FileSystem.AccessControl should depend on the newer version of System.Security.AccessControl.

**Comment by huoyaoyuan** [comment]
The packages are still providing content on netstandard2.0. Marking them as deprecated looks questionable.

If you are targeting .NET 6+, you should remove these packages. They are now in-box and will provide no content.

**Comment by avivanoff** [comment]
There is a newer version of System.Security.AccessControl, why not update System.IO.FileSystem.AccessControl to target it?

**Comment by huoyaoyuan** [comment]
Based on the announcement at https://github.com/dotnet/announcements/issues/190, both `System.Security.AccessControl` and `System.IO.FileSystem.AccessControl` shouldn't have 6.0 version. I don't know why a new version is published for the former.

Per https://github.com/dotnet/runtime/issues/91729#issuecomment-1710532511 and https://github.com/dotnet/runtime/issues/93577#issuecomment-1765923278 , System.IO.FileSystem.AccessControl/5.0.0 was manually un-deprecated afterwards. It's dependencies should also be un-deprecated. /cc @ViktorHofer

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
> I don't know why a new version is published for the former.

@ViktorHofer had to bring back `System.Security.AccessControl` because we made changes in 6.0 to it to break the dependency on `System.Security.Permissions`.  Those needed to ship to folks targeting .NETFramework and .NETStandard who cared about dropping that dependency so we needed to ship the package.

I think I prefer the AccessControl 5.0 package to stay deprecated since we'd want folks to update to latest and the 5.0 version is indeed out of support.  Our servicing bar does not include updating a package just to update its dependencies - we only do that in major releases.  As such I see this issue as "by design".  Nothing's blocked here and updating AccessControl is what I'd expect folks to do.

As has been mentioned - you don't need these packages at all on the latest versions of .NET.
