### ISSUE TITLE
[Analyzer] Use the async counterpart when available

### ISSUE THREAD

**Issue by Bartleby2718** [dotnet/runtime#104208]
Notes:
- I understand that this may be a false alarm, but I'm taking this opportunity to learn from experts!
- https://github.com/dotnet/roslyn-analyzers/blob/main/GuidelinesForNewRules.md redirected me from `dotnet/roslyn` to this repo.

---

In an `async` method, you can replace synchronous, `void`-returning methods with asynchronous, `Task`-returning counterparts to free up a thread.

Example (`task1` and `task2` are of type either `Task` or `Task<T>`)
```cs
async Task MyMethod()
{
    ...

    // before
    Task.WaitAll(task1, task2);

    // after
    await Task.WhenAll(task1, task2);

    ...
}
```

The caveat is that there may be false positives (if the user did want a synchronous, blocking code) and therefore this can change the semantics. However, [`IDE0300` also says "The code fix when this option is used might change the semantics of your code"](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300), so I think this should also be reasonable.

**Comment by Zintom** [comment]
Async methods come with significant overhead (see Stephen Toub's async/await talk on YouTube).

There are also LOTS of differences in control flow with async methods, not to mention exception propagation, deadlocks etc.

Automatically making all voids async would have a huge performance impact and break almost every piece of code out there. This can't just be abstracted away, if you're dealing with asynchrony, you need to code in a certain way.

**Comment by julealgon** [comment]
> In an `async` method, you can replace synchronous, `void`-returning methods with asynchronous, `Task`-returning counterparts to free up a thread.

This only applies if the underlying code supports async, otherwise all you are doing is adding extra overhead to the call.

There are also situations where the `async` version is not meant to be used directly:
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-8.0#microsoft-entityframeworkcore-dbcontext-addasync-1(-0-system-threading-cancellationtoken)
> Remarks
This method is async only to allow special value generators, such as the one used by 'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo', to access the database asynchronously. For all other cases the non async method should be used.

I think creating a general-purpose analyzer for this would be either very hard, or end up leading people to the pit of failure sometimes.

The analyzer would likely have to be specific to pairs of methods where it is known to be "always the better idea" to use the "Async" version. The problem is that, depending on your application, it might just always be better to use the sync version instead to avoid the task overhead, in scenarios where you don't have much concurrent access etc.

**Comment by stephentoub** [comment]
If I'm understanding the suggestion, is this basically https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1849 ?

**Comment by Bartleby2718** [comment]
- @stephentoub Didn't know this existed! This is exactly what I was looking for, and I have confirmed that this behaves as expected. Thanks!
- @julealgon I think you articulated why [CA1849](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1849) is not enabled by default in .NET 8. :)
- For future reference, the source code can be found in https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs.

**Comment by Bartleby2718** [comment]
(fixing the resolution)
