### ISSUE TITLE
Numerical issue when multiply 1.001 by 1000

### ISSUE THREAD

**Issue by logistikbroker** [dotnet/runtime#104225]
### Description

The results of multiplying 1.001 (double) or 1.001f (float) by 1000 (integer) does not produce the expected result. 
https://dotnetfiddle.net/0MSdIM

### Reproduction Steps

``` csharp
using System;
					
public class Program
{
    public static void Main()
    {
        Console.WriteLine($"1.001f * 1000 = {1.001f * 1000}");
        Console.WriteLine($"1.001 * 1000 = {1.001* 1000}");
    }
}
```

### Expected behavior

Expected Output:
1.001f * 1000 = 1001
1.001 * 1000 = 1001

### Actual behavior

Actual Output:
1.001f * 1000 = 1001.00006
1.001 * 1000 = 1000.9999999999999

### Regression?

Works in .NET 4.8 and below.

### Configuration

- **Which version of .NET is the code running on?**   
Tested .NET 4.7.2, .NET 4.8 / .NET 8

- **What OS and version, and what distro if applicable?**  
Tested on Windows 10 / Ubuntu 22.04.3 LTS (WSL 2)

- **What is the architecture (x64, x86, ARM, ARM64)?**  
x64

- **Do you know whether it is specific to that configuration?**  
I don't know.

**Comment by tannergooding** [comment]
This is expected and the correct result.

Notably, there is no change between the computed result on .NET Framework and Modern .NET (.NET Core 3.0 or later), only a change in the display string where modern .NET ensures the default string is roundtrippable as per https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

`float` and `double` are IEEE 754 binary-based floating-point types and as such can only exactly represent multiples of powers of two. This means that `1.001` is not actually `1.001` but is rather `1.00100004673004150390625` for float and `1.000999999999999889865875957184471189975738525390625` for `double`. These exact values can be seen by using `ToString("G99")` on .NET Core 3.0 or later and you can observe that the identical bitwise result was computed by using `BitConverter.DoubleToInt64Bits` which works on both .NET Framework and .NET Core.

Thus, when you see the literal `1.001f`, the C# compiler actually parses this as if to infinite precision and unbounded range and then rounds it to the nearest representable result (`1.00100004673004150390625`, or `1.000999999999999889865875957184471189975738525390625` for double). This is then multiplied against 1000 (which is exactly representable) giving you an intermediate result of `1001.00004673004150390625` (or `1000.999999999999889865875957184471189975738525390625` for double`), which itself is then rounded to the nearest representable value `1001.00006103515625` (or `1000.9999999999998863131622783839702606201171875` for double).

In both cases, the computed result and the result you're expecting are neighboring representable results (they differ by 1 ULP, or Units in Last Place), but the result chosen is closer to the infinitely precise result given the actual inputs used by the computation since the literals themselves have to be parsed (by the compiler) to float/double prior to the computation being performed.

**Comment by logistikbroker** [comment]
@tannergooding 

thank you for your explanation. I have one last question about this behavior. Assume the conversion of weights from kilograms (double) to grams (integer). 

```
  double x1 = 1.001; // G99 1.000999999999999889865875957184471189975738525390625
  double x2 = 2.001; // G99 2.000999999999999889865875957184471189975738525390625

  Console.WriteLine($"x1: {x1:G99}");
  Console.WriteLine($"x2: {x2:G99}");

  double result_x1 = x1 * 1000; // G99 1000.999999999999889865875957184471189975738525390625
  double result_x2 = x2 * 1000; // G99 2001

  Console.WriteLine($"result x1: {result_x1:G99}");
  Console.WriteLine($"result x2: {result_x2:G99}");

  bool b1 = result_x1 == 1001; // false
  bool b2 = result_x2 == 2001; // true

  Console.WriteLine($"b1: {b1}");
  Console.WriteLine($"b2: {b2}");
```

For this type of calculation the expected values would be 1001 and 2001 the internal representation of the double values may be different. The actual results are 1000 and 2001. In the case of 1000 the value of result_x1 is cast to an integer and the floats are dropped. 

According to your explanation, why is the value of result_x2 `2001` and not `2000.999999999999889865875957184471189975738525390625`? What is the best way to get 1.001 * 1000 == 1001 done correctly? 

Issue can be closed then. Thanks a lot.

**Comment by colejohnson66** [comment]
Whenever you need something *rounded* for output to the user, you should use `double.Round` (or `float.Round`).

**Comment by tannergooding** [comment]
If you want more "precise" results, you need to use `decimal` which is a base-10 format and can represent multiples of powers of 10. This is significantly slower (it is still fast, it just isn't natively hardware accelerated by any CPU) than using `float`/`double` but consumes inputs and produces outputs in a manner that better fits typical expectations. -- Noting that this is still not exact, given you're working with finite precision, for example: `((1.0m / 3.0m) * 3.0m) != 1.0m` for example, it equals `0.9999999999999999999999999999m`

colejohnson66 is correct that you may want to consider rounding to a set number of digits to help handle cases like these (for float, double, or decimal). It is not, however, a perfect fit and issues can still show up, especially after many operations allow the rounding error to accumulate. You rather need to consider that there is inherent imprecision and potential rounding error in any operation involving fractional data due to there only being a finite number of representable digits. The same issues also exist for `fixed-point` as `1 / 3` cannot be exactly represented; or for `rational` types since `irrational` values such as `pi` cannot be exactly represented, the same issues even exist for integers since `int.MaxValue + 1 == int.MinValue` due to overflow -- Computer math is not the same as real math and these differences are just something you have to learn and account for, in all programming languages.
