### ISSUE TITLE
Using trimming functionality to identify dead code

### ISSUE THREAD

**Issue by kimbell** [dotnet/runtime#104405]
We have some applications that date back to the dawn of .NET; asmx web services. Recently we have updated these to using WebApi and run on .NET6 (will be update to .NET8), but the codebase contains stuff that most likely is no longer in use. Over the years developers have been scared of removing it incase they break something. 

Is there a way we can compile this using the new native AOT system and get the trimming system to generate some output that can give us an idea where we might start to look for dead code? In this scenario all the code will be in the same sln file.

**Comment by vitek-karas** [comment]
The trimming/AOT is only reliable if you can make the code trim-compatible, in practical terms it means that you can build your app with trimming/AOT enabled and get no warnings. If you get warnings, it's possible that it removed more code than it should and you can't be certain about the results.

If you do manage to make your app trim-compatible then you can either:
* Just trim the app - `PublishTrimmed=true` and look at the resulting assemblies with some decompiler (ILDASM, ILSpy, ...) and see what was removed. Or just start by looking if it removed entire assemblies (the files won't be in the output at all).
* Compile the app for NativeAOT - `PublishAot=true` and use a tool like https://github.com/MichalStrehovsky/sizoscope to inspect the size of things.

I would probably start with just trimming and using ILSpy or something similar. I'm not aware of a tool which would compare untrimmed assemblies to trimmed ones and write out everything which was removed, but it should not be that hard to write one.

**Comment by julealgon** [comment]
@kimbell I'm in the same boat as you are. Just keep in mind that, even if this worked (using trimming mechanisms), it would still fall apart for anything `public` facing, such as API endpoints or any externally accessed service or library.

Libraries are easier to manage if you have a master solution with everything in it (so that you can trust compile-time references are all there is to it) but APIs are a completely separate beast: as far as I know, you'd have to individually check for calls to each endpoint to conclude if they are not being used anymore.

At this point, it helps if you are automatically generating all of your API clients with something like `kiota` which allows you to filter which entities should be included in the proxies. Then you could use that capability to "strangle" the API surface to only what is used by each component and then conclude that the rest of the unused spec can be removed.

If any of your API endpoints are used publicly (outside of your company) then that makes it exponentially harder of course.
