### ISSUE TITLE
[API Proposal]: X509Certificate2Collection.FindByThumbprint for more digest algorithms

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#104643]
### Background and motivation

Today we have `X509FindType.FindByThumbprint` which implicitly uses the SHA-1 algorithm. Regardless of the context and nature of security, SHA-1 is being phased out and the use of it ranges from discouraged to forbidden when writing net-new code.

To help with the transition away from SHA-1, we should offer finding certificates in a certificate collection and certificate store by their SHA-2-256 thumbprint (or any other hash).

### API Proposal

```C#
namespace System.Security.Cryptography.X509Certificates;

public partial class X509Certificate2Collection {
    public X509Certificate2Collection FindByThumbprint(HashAlgorithmName hashAlgorithm, string thumbprintHex);
    public X509Certificate2Collection FindByThumbprint(HashAlgorithmName hashAlgorithm, ReadOnlySpan<char> thumbprintHex);
    public X509Certificate2Collection FindByThumbprint(HashAlgorithmName hashAlgorithm, ReadOnlySpan<byte> thumbprint);
}
```

### API Usage

```csharp
// maybe this comes from config.
string sha256Thumbprint = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
using var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
X509Certificate2Collection found = store.Certificates.FindByThumbprint(HashAlgorithmName.SHA256, sha256Thumbprint);

// found will contain certificate with matching thumbprint
```

### Alternative Designs

If we do not want a new API on `X509Certificate2Collection`, then we can add a new enum member to `X509FindType` with the name `ThumbprintSha256`. The upshot to this is it extends the existing `Find` API. The downside to this is does not generalize it to support any `HashAlgorithmName`. Generalizing to support the same inputs as `X509Certificate.GetCertHashString` seems like a better idea.

**Comment by blowdart** [comment]
Does this not present the same sort of problem down the line, in that the method is tied to one algorithm that will eventually, hopefully long after I retire, end up being broken and banned?

Given that `X509Certificate.GetCertHashString` takes an algorithm name, and we rejected the idea of a [Thumbprint256](https://github.com/dotnet/runtime/issues/62425) or other convenience method that baked the algorithm in, would consistency not require a more general FindByThumbprint which takes an algorithm, even if the underlying win32 api only gives us sha1 and sha256 for now?

**Comment by vcsjones** [comment]
Actually we can implement it for all hash algorithms, not just SHA-1 and SHA-2-256, so we might as well do that.

https://github.com/dotnet/runtime/compare/main...vcsjones:runtime:sha256-find-cert-by-thumbprint-alt

The Win32 SHA256 is apparently new (Windows 10 22H2) so we would need to make it work for older Windowses anyway. Since we are doing that, we can make everything work.

**Comment by vcsjones** [comment]
Okay, I like @blowdart's idea more, so I updated the proposal.

**Comment by bartonjs** [comment]
If we want this functionality, the proposed shape seems fine. But I'm generally not a fan of X509Certificate2Collection.Find, and so I wonder if we want to invest more in it, or just tell people to use foreach/Linq/etc.

What don't I like?

1. No one understands `validOnly`.  _Clearly_ you only want valid things, right?  Except, it turns out, "valid" includes "this system trusts the certificate chain", which excludes self-signed and "some client cert I have to use when talking to this remote party that I otherwise don't care about".  Also, y'know, expiration and stuff.
2. Find doesn't return the same certificate instances, it returns clones.

```c#
X509Certificate2Collection coll = new() { cert };
X509Certificate2Collection coll2 = coll.Find(FindByThumbprint, cert.Thumbprint, false);
bool same = ReferenceEquals(cert, coll[0]); // true
bool stillSame = ReferenceEquals(cert, coll2[0]); // false
```

Find doesn't _look_ like it allocates finalizable objects, but it does.  And that leads to problems.

```c#
X509Certificate2Collection coll = OpenPFX(bytes, pwd);
coll = coll.Find(FindByThumbprint, thumbprintFromConfig, false);
return coll[0];
```

When does the private key file get erased?  Anyone?  Well... the object that owned cleaning it up got loaded into `coll`. It got cloned by Find.  And the key will be erased:

* .NET 9+: When the original cert gets finalized
* .NET 8-, .NET Framework: When the original cert gets finalized, or the new cert object gets finalized or disposed... whichever of these comes first

Hooray!

---

We have the option of saying "new method, new behavior", and that the new FindByThumbprint should NOT clone the certificates, but copy them into the return collection by reference.  But that would mean `.Find(FindByThumbprint, ...)` and `.FindByThumbprint(...)` were different in that respect, which is probably even more confusing.

End of the day? Probably should Obsolete Find and tell people to use foreach/Linq, especially now that the collection is `IEnumerable<X509Certificate2>`.

**Comment by vcsjones** [comment]
> No one understands validOnly.

I am fine nuking that. 

> Find doesn't return the same certificate instances, it returns clones.

In the general case of Find, that is interesting. In the case of FindByThumbprint, though, the typical case is to find exactly one cert. Cloning a single cert seems reasonable to keep the cloning consistency with Find. This API shouldn't result in a whole store being cloned.

> Probably should Obsolete Find 

Maybe. There are some things that Find does that are non-trivial for people to replicate, like all of the gymnastics for serial number. Hex, integer, big endian, little endian... etc. I would think a replacement is due then.

**Comment by vcsjones** [comment]
Updated proposal to remove `validOnly`.

**Comment by bartonjs** [comment]
I added overloads that accept the thumbprint as ROS-char (hex) and ROS-byte (actual bytes, since that's what the thumbprint really is).

Private key lifetimes got normalized with the new cert loader, so cloning now is just about GC+finalizer impact.  Since that doesn't have any impact on the API shape (unless someone wants to propose a defaulted boolean that controls the cloning behavior), marking it as ready for review.

**Comment by bartonjs** [comment]
> and ROS-byte ...

I don't think we really need support for UTF-8 matches, but if we do we'd have to change the method name between the hex ones and the bytes one.  E.g. FindByThumbprintHex.

**Comment by bartonjs** [comment]
* We renamed the `thumbprint` parameter that is ReadOnlySpan{byte} to `thumbprintBytes` to further clarify it's not a UTF-8 string.
* Making it an extension method for down-level compatibility came up.  We decided no (at least for now).

```C#
namespace System.Security.Cryptography.X509Certificates;

public partial class X509Certificate2Collection
{
    public X509Certificate2Collection FindByThumbprint(HashAlgorithmName hashAlgorithm, string thumbprintHex);
    public X509Certificate2Collection FindByThumbprint(HashAlgorithmName hashAlgorithm, ReadOnlySpan<char> thumbprintHex);
    public X509Certificate2Collection FindByThumbprint(HashAlgorithmName hashAlgorithm, ReadOnlySpan<byte> thumbprintBytes);
}
```
