### ISSUE TITLE
Faulting module name: coreclr.dll, version: 6.0.3224.31407

### ISSUE THREAD

**Issue by varnikhaasree** [dotnet/runtime#104675]
### Description

I receive an application error 
CoreCLR Version: 6.0.3224.31407
.NET Version: 6.0.32
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFBB50D4089 (00007FFBB4F00000) with exit code c0000005.

note: I've implemented gc.collect() in my code in finally block.

### Reproduction Steps

There is a large file of type XML to processed for some calculation. 
blocking collection is populated from service bus queue and then item from blocking collection queue are passed to do a calculation process. calculated output of xml type is written to the queue and even if any exception is thrown then the error is written to the queue in xml format. I face this crash issue only if there is an exception raised in that file.

### Expected behavior

I expect not the crash the application and it happens only in one azure environment and not with the other azure environment.

### Actual behavior

I expect not the crash the application and it happens only in one azure environment and not with the other azure environment.

**Comment by mangod9** [comment]
Hey @varnikhaasree, we would need more details/repro/dump to diagnose. You could also try if updating to .NET 8 makes things better. Thx

**Comment by Pethson** [comment]
I get the same error?

Application: HASS.Agent.exe
CoreCLR Version: 6.0.3224.31407
.NET Version: 6.0.32
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF960C74089 (00007FF960AA0000) with exit code c0000005.

Running Windows 11 23H2 Enterprise
It works on several computers but in one id don't runs and I get this error, and the app crashes
