### ISSUE TITLE
Unexpected float sum inaccuracy

### ISSUE THREAD

**Issue by eugbaranov** [dotnet/runtime#1048]
# Issue Title

Unexpected float sum inaccuracy.

# General

I'm running 3.1.100 on Windows 10 x64 [Version 10.0.19037.1].

The following sum (and equivalent in F# too):

    new[] { -7.80, -9.10, -7.80, -6.70, -7.80 }.Sum()

Unexpectedly for me ends un displayed as `-39.199999999999996`.

I know that floats have limited accuracy but I haven't expected this for such simple sum.

Also, running on .NET 4.8 produces `-39.20` as expected.

**Comment by scalablecory** [comment]
I believe we did change something regarding accuracy of floating point printing. CC @tannergooding

**Comment by Wraith2** [comment]
https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by eugbaranov** [comment]
Is this a flaw of IEEE 754-2008 or Dragon4?
I can see that e.g. Python have same behavior.

**Comment by jkotas** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
Its not a flaw, per say, in either.

> Is this a flaw of IEEE 754-2008 ...

This isn't some flaw that IEEE 754 arithmetic has, instead it is a fundamental flaw in attempting to represent normal math (where numbers can be unbounded) into some finite space (in this case, a 64-bit encoded value).

The same issue exists in `decimal`,  some `rational` type, and most other forms of representing numbers on computers, the only difference is to what degree and where you'll find inaccuracies. For example, `1 / 3` cannot be accurately represented by integers, decimal, or float/double but it can be by some `rational` type. On the other hand, `PI` cannot be accurately represented by any of them because it is an irrational number. You can also construct examples where `decimal` will incur rounding error, but the location of that error generally doesn't matter because it occurs around 29 significant digits.

> ... or Dragon4?

The formatting logic in .NET Core 3.0  and above will return a roundtrippable string by default. This means that the string returned is the shortest string that, when parsed, will return the original result (minus a couple error cases that were fixed in https://github.com/dotnet/runtime/pull/257 where we returned a roundtrippable string, but it was not necessarily the shortest).

In both cases, the sum returned by .NET Framework and .NET Core is the same. It's only how the result is formatted that differs. In the case of .NET Framework, `-39.2` was not the correct result to return because when parsed it returns `-39.200000000000003` (bit representation: `0xC04399999999999A`). The actual sum returned is `-39.199999999999996` (bit representation: `0xC043999999999999`), which is one representable value smaller.

> I know that floats have limited accuracy but I haven't expected this for such simple sum.

With any computer numeric representation, you can incur error with as few as 1 value. This is because, first and foremost, the computer has to take the value given (which is generally `text`, such as a literal in a programming language) and convert it to a representable value in the target format.

For example, when you declare `new[] { -7.80, -9.10, -7.80, -6.70, -7.80 }`, the C# compiler parses 5 literals. We have 3 unique values (`-7.80`, `-9.10`, and `-6.70`) which are parsed as follows (listed as `shortest roundtrippable value`, `string to 17 significant digits`, `bit representation`):
* `-7.8`, `-7.7999999999999998`, `0xC01F333333333333`
  * Exact Value: `-7.79999999999999982236431605997495353221893310546875`
* `-9.1`, `-9.0999999999999996`, `0xC022333333333333`
  * Exact Value: `-9.0999999999999996447286321199499070644378662109375`
* `-6.7`, `-6.7000000000000002`, `0xC01ACCCCCCCCCCCD`
  * Exact Value: `-6.70000000000000017763568394002504646778106689453125`

So, as you can see, even declaring the values introduces some minor error because the values given can't be exactly represented and have to be parsed to the "nearest representable result".

You then sum them together and rounding has to be performed after each operation. So, you first add `-7.80` and `-9.10`, and round the result; then you add `-7.80` to that and round; then `-6.70` and round; and finally `-7.80` again with a final round. Each operation has the chance to introduce more inaccuracy because the computed result may not be exactly representable.

**Comment by danmosemsft** [comment]
These improvements in accuracy sometimes mean that `ToString()` doesn't produce such a nice result for display, and you need to add rounding in the formatting.
