### ISSUE TITLE
List.Contains nullable warning

### ISSUE THREAD

**Issue by fjmorel** [dotnet/runtime#104916]
### Description

`IEnumerable` is fine with passing a null value to its `Contains` but `List` isn't when nullable is on.

### Reproduction Steps

```csharp
#nullable enable
List<string> list = [];
var a = list.Contains(null);
var b = list.AsEnumerable().Contains(null);
#nullable restore
```

### Expected behavior

`CS8625 Cannot convert null literal to non-nullable reference type.` should not trigger for either call to Contains.

### Actual behavior

CS8625 triggers on `List.Contains`.

### Regression?

I don't know.

### Known Workarounds

Nullable suppression or compiler warning suppression

### Configuration

.NET 8 (latest SDK and runtime)
Windows 11
x64

### Other information

Contains probably just needs an `[AllowNull]` on its parameter.

https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs,342

**Comment by stephentoub** [comment]
> IEnumerable is fine with passing a null value to its Contains but List isn't when nullable is on

That's because the API being bound to for the Contains on the enumerable is:
https://github.com/dotnet/runtime/blob/ac0eeb015a0266adb06696bb58c21e5bfe6d9b56/src/libraries/System.Linq/src/System/Linq/Contains.cs#L10
which is a generic method with its own generic method parameter. The compiler is then inferring that TSource is `string?`, not `string`, based on your passing in null. That's not the case with `List<T>`, where your code has declared `List<string>`, not `List<string?>`, and thus List's instance `Contains` method accepts a `string`, not `string?`, and you get a warning passing in a nullably-incompatible value.

It's behaving as designed.

**Comment by fjmorel** [comment]
Can we change it? It's pretty common for us to have collections of things, and check if user input is in that collection.

Often-times from an API request, where we could do model validation, but also sometimes from other JSON and CSV parsing.

**Comment by fjmorel** [comment]
nvm, I see your comments https://github.com/dotnet/runtime/issues/1775

Makes sense, thanks
