### ISSUE TITLE
[API Proposal]: CollectionsMarshall.AsMemory(List<T>? list)

### ISSUE THREAD

**Issue by sfiruch** [dotnet/runtime#105179]
### Background and motivation

When dealing with large amounts of data in a List<T> in high-performance code, it can be very useful to get direct access to the `_items` array backing a `List<T>`. This can be achieved using the existing `CollectionMarshall.AsSpan()` functionality, for example:
```cs
var listEndsWith123 = CollectionsMarshal.AsSpan(list).EndsWith([1,2,3]);
```

However, there are situation when you have to use `Memory<T>` instead of a `Span<T>`, for example when lambdas are required because of `Parallel` functions.

### API Proposal

```cs
namespace System.Runtime.InteropServices
{
    /// <summary>
    /// An unsafe class that provides a set of methods to access the underlying data representations of collections.
    /// </summary>
    public static class CollectionsMarshal
    {
+        /// <summary>
+        /// Get a <see cref="Memory{T}"/> view over a <see cref="List{T}"/>'s data.
+        /// Items should not be added or removed from the <see cref="List{T}"/> while the <see ref="Memory{T}"/> is in use.
+        /// </summary>
+        /// <param name="list">The list to get the data view over.</param>
+        /// <typeparam name="T">The type of the elements in the list.</typeparam>
+        public static Memory<T> AsMemory<T>(List<T> list);

        /// <summary>
        /// Get a <see cref="Span{T}"/> view over a <see cref="List{T}"/>'s data.
        /// Items should not be added or removed from the <see cref="List{T}"/> while the <see cref="Span{T}"/> is in use.
        /// </summary>
        /// <param name="list">The list to get the data view over.</param>
        /// <typeparam name="T">The type of the elements in the list.</typeparam>
        public static Span<T> AsSpan<T>(List<T>? list);
        ...
    }
}
```

### API Usage

```csharp
void ProcessListInParallel(List<int> list)
{
    var m = CollectionsMarshal.AsMemory(list);
    Parallel.Invoke(
        () => ProcessPart(m[..5]),
        () => ProcessPart(m[5..])
    );
}

void ProcessPart(Memory<int> blah) { /* ... */ }
```

In this example you couldn't use `Span<T>`, because those are not allowed in lambdas.

### Alternative Designs

- Allow `Span<T>` in many more places, e.g. lambdas, yield blocks, ...
- Expose items as `ArraySegment` instead

### Risks

Very low. Sure, giving direct access to the backing array is risky. However, the existing access via `CollectionsMarshall.AsSpan` already exposes the backing array already and comes with warnings in the documentation. In my opinion, exposing the backing array through `Memory<T>` in addition to `Span<T>` does not bring any additional risks.

**Comment by tannergooding** [comment]
This is not really a needed API and likely won't do what you might expect. It will in practice be more dangerous and worse for performance to have a `Memory<T>` which wraps the backing array for a `List<T>`.

For context, `Memory<T>` isn't necessarily a high-performance type in the first place, it primarily exists to give a common abstraction between unsafe (such as `T*`) and safe (such as `T[]`) allocations in a way that can be stored on the heap. Because it needs to be a heap safe common abstraction, it has overhead as it has to check what the backing data storage is and work alongside things like a `MemoryOwner` to ensure that native allocations don't leak. As such, you don't really work with `Memory<T>` itself but rather instead still work with `Span<T>` which you get via the `Span` property. Getting this span can be "expensive" (in comparison to many of the operations one might do with span) and so its recommended to get the span and cache it up front, so it isn't needed to be done repeatedly. `Memory<T>` correspondingly doesn't appear frequently in higher level APIs because it's largely only needed for contexts where you need the memory slice escaping the method to be stored on the heap -and- you need the common abstraction it provides between safe/unsafe memory. If you already have a heap safe way to track the backing allocation (such as `List<T>`) then it's going to be significantly better to pass that around and simply extract the span from that instead.

That is to say this code:
```csharp
void ProcessListInParallel(List<int> list)
{
    var m = CollectionsMarshal.AsMemory(list);
    Parallel.Invoke(
        () => ProcessPart(m[..5]),
        () => ProcessPart(m[5..])
    );
}
```

Should rather be:
```csharp
void ProcessListInParallel(List<int> list)
{
    Parallel.Invoke(
        () => ProcessPart(CollectionsMarshal.AsSpan(list)[..5]),
        () => ProcessPart(CollectionsMarshal.AsSpan(list)[5..])
    );
}
```

Which will be much more efficient and achieves the desired behavior.

--------------------

Noting also that the reason `AsSpan` is hidden away on `CollectionMarshal` is explicitly because its unsafe. If you mutate the `list` in a way that would cause the backing array to change, then the span no longer tracks the list and is no longer doing what is likely expected. The `span` having a limited lifetime to the current thread and method scope significantly helps mitigate risk here. `Memory<T>`, however, is not limited in that way and that makes it more dangerous and much easier for developers to get it wrong.

CC. @stephentoub

**Comment by huoyaoyuan** [comment]
See also #87210 #90141 #101914

**Comment by sfiruch** [comment]
> This is not really a needed API

I'd like to use callbacks, but failed to work around the fact that `Action<Span<T>>` is not permissible.


> and likely won't do what you might expect.

I doubt that :)


> It will in practice be more dangerous

More dangerous than `CollectionsMarshal.AsSpan`? How?


> `Memory<T>` [...] is largely only needed for contexts where you need the memory slice escaping the method to be stored on the heap -and- you need the common abstraction it provides between safe/unsafe memory.

That's precisely what I need in my code. I'd like to use `List<T>` and `T[]` in the same code paths.

In my case the desired behavior includes passing both `List<int>` and `int[]` to `ProcessListInParallel`. Perhaps this would be a more representative example:

```cs

ProcessInParallel(Enumerable.Range(1,100).ToArray());
ProcessInParallel(Enumerable.Range(1,100).ToList());

void ProcessInParallel(Memory<int> list)
{
    var m = CollectionsMarshal.AsMemory(list);
    Parallel.Invoke(
        () => ProcessPart(m[..5]),
        () => ProcessPart(m[5..])
    );
}
```


> Noting also that the reason `AsSpan` is hidden away on `CollectionMarshal` is explicitly because its unsafe. If you mutate the `list` in a way that would cause the backing array to change, then the span no longer tracks the list and is no longer doing what is likely expected. The `span` having a limited lifetime to the current thread and method scope significantly helps mitigate risk here. `Memory<T>`, however, is not limited in that way and that makes it more dangerous and much easier for developers to get it wrong.

Would placing it in `Unsafe` be better?



> See also #87210 #90141 #101914

@huoyaoyuan Thank you very much for referencing these. I now watched the very interesting [original API review](https://www.youtube.com/watch?v=8M5rFkINsus&t=2243s) about why `.AsMemory()` was decided against previously. While I understand the arguments raised against it, I pretty much disagree.

These posts also appear to show that other people are looking for this functionality.



In the meantime, I'll just use
```cs
static class Extension
{
    class ListAccessor
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_items")]
        public static extern ref T[] Items<T>(List<T> _list);
    }

    public static Memory<T> AsMemory<T>(this List<T> _list)
        => new Memory<T>(ListAccessor.Items(_list), 0, _list.Count);
}
```

**Comment by stephentoub** [comment]
>> This is not really a needed API

> I'd like to use callbacks, but failed to work around the fact that Action<Span<T>> is not permissible.

It is in .NET 9.

> More dangerous than CollectionsMarshal.AsSpan? How?

As Tanner explained:
"If you mutate the list in a way that would cause the backing array to change, then the span no longer tracks the list and is no longer doing what is likely expected. The span having a limited lifetime to the current thread and method scope significantly helps mitigate risk here. Memory<T>, however, is not limited in that way and that makes it more dangerous and much easier for developers to get it wrong."

> See also https://github.com/dotnet/runtime/discussions/87210 https://github.com/dotnet/runtime/issues/90141 https://github.com/dotnet/runtime/issues/101914

Closing as duplicate. Thanks.

**Comment by hamarb123** [comment]
> Would placing it in `Unsafe` be better?

Re this particular part: the `Marshal` classes are all unsafe/dangerous as well, there's very few 'completely safe in every context' APIs on these types - this is what the name marshal indicates. They are *generally* for specific purposes though, e.g., `CollectionsMarshal` is all the marshalling stuff for a particular set of APIs. The `Unsafe` class represents raw IL operations (mostly, with the only real exception being `BitCast`) that are (or were) not able to be expressed in C# - so this would not be a good place for it. It is good to be aware of this when using APIs in marshal classes, which is why I'm mentioning it :)
