### ISSUE TITLE
After creating a Worker service project, "System.text.json" 8.0.0 was referenced and identified as a vulnerable package

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/runtime#105120]
### Repro steps

1. `dotnet new worker`
2. Open project in Visual Studio
3. Right-client project > Manage NuGet Packages 

### Expected results

The project shouldn't have vulnerability warnings

### Actual results

Check 'Show only vulnerable' checkbox, then you can see that the warning is because the following packages have a dependency on System.text.json 8.0.0, which has been detected as the vulnerable package

### Original issue

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU 
4. Install Dev17.10.4 (Include Aspire 8.0.0) latest release build
    - Web workload

**REPRO STEPS**
1. File > New project > .NET Aspire App Host > .NET 8.0 > Create
2. Right-check project > Manage NuGet Packages

**ACTUAL**
Check 'Show only vulnerable' checkbox, then you can see that the warning is because the following packages have a dependency on System.text.json 8.0.0, which has been detected as the vulnerable package
Aspire.Hosting.AppHost "Version=" 8.0.0
![image](https://github.com/user-attachments/assets/8e99c487-e6f4-4c30-9d89-958ff5fb61b8)

**NOTE**: 
1. This issue can be repro in any aspire project or in a project with aspire
This issue also repro on Dev17.10 + Aspire 8.0.2/8.1 and Dev17.11 + Aspire 8.0.2/8.1

**EXPECTED**
The packages should be updated to depend on a newer version of System.text.json that is not vulnerable.

**Comment by steveharter** [comment]
The proposed fix from @eerhardt is:

> We are super stringent about TFM dependencies - in this case Microsoft.Extensions.Configuration.Json and Microsoft.Extensions.Logging.Console shouldn't have a nuget dependency on System.Text.Json for the net8.0 TFM. It should come from the TFM net8.0.

Thoughts @ericstj @eiriktsarpalis?

**Comment by ericstj** [comment]
I think that's reasonable to avoid dependencies when they're present in the framework.  I see that as a nice improvement to avoid package downloads.

**Comment by ericstj** [comment]
So there's a complication here.  If a package needs a reference for `NETStandard2.0` we may not be able to remove the package reference for older .NET versions.  Consider the following package shape:

A (netstandard2.0) -> B (package - 9.0.0.0)
A (net8.0) -> B (framework - 8.0.0.0 | package - 9.0.0.0)
A (net9.0) -> B (framework - 9.0.0.0)

We can't remove the package reference for net8.0 because that would cause a ref-def mismatch for folks compiling on netstandard2.0 then running on net8.0 - since net8.0 only contains the 8.0.0.0 version.  Even if we're OK using the API that's in 8.0 when compiling for it, we must deliver the 9.0 assembly since that's what we expose on netstandard2.0.

We can still remove the package reference for the current framework, but not past ones in this case.

**Comment by ericstj** [comment]
We only made this change for `net9.0` in RC1. If you are using targeting `net9.0` and an RC1 build you should see the fix.

**Comment by v-elenafeng** [comment]
> We only made this change for `net9.0` in RC1. If you are using targeting `net9.0` and an RC1 build you should see the fix.

Thanks! With 9.0 RC1, the dependency has been removed. For 8.0 templates in VS 17.11 and below, the package warning is only shown when checking for vulnerable packages from the nuget package manager. For 8.0 templates in VS 17.12 (where the default SDK is 9.0), we're tracking with issue https://github.com/dotnet/AspNetCore-ManualTests/issues/3047

**Comment by SymbioticKilla** [comment]
> We only made this change for `net9.0` in RC1. If you are using targeting `net9.0` and an RC1 build you should see the fix.
Hi @ericstj,

is it possible to port this fix and remove System.Text.Json 8.0 from .NET8.0 target framework?

**Comment by ericstj** [comment]
This change has been ported to 8.0 in https://github.com/dotnet/runtime/pull/107161 and should ship in the next servicing release of .NET 8.0.

**Comment by v-reinawang** [comment]
Verify that this issue has been fixed in SDK 8.0.403.

**Comment by chrarnoldus** [comment]
I have noticed that updating a reference to System.Data.OleDb from v8.0.0 to v8.0.1 in a WinForms project will now cause additional DLLs to be copied to the output folder, namely System.Configuration.ConfigurationManager.dll and a few others. (The new OleDb version is a result of the backport https://github.com/dotnet/runtime/pull/107161/files#diff-30298982b02597cb3012558d2f74db967ea32ef46132610ba0fd030fe62eb727 if I understand correctly.)

Failure to deploy these extra DLLs with your app may result in assembly load errors at runtime (possibly only when running on a pre-8.0.10 .NET 8 runtime).

Was this change intentional?
