### ISSUE TITLE
Compiler error CS1510 is triggered on compiler-generated variables

### ISSUE THREAD

**Issue by marchewek** [dotnet/runtime#105252]
### Description

When a variable is created implicitly by the compiler, it cannot be used as ref parameter in the extension methods; below is the minimal code that visualizes this issue. Since I'm not an expert on IL, I'm not sure whether it's a compiler bug (allowed in IL) or a gap in the language itself (not allowed in IL).

### Reproduction Steps

``` csharp
public class TestCode
{
	internal static void Main()
	{
		// with explicit variable it compiles
		var x = new SomeStruct();
		x.ExtensionsRefParam();
		x.ExtensionRefParamRefRet();

		// with implicit variable neither compiles (triggers CS1510)
		new SomeStruct().ExtensionsRefParam();
		new SomeStruct().ExtensionRefParamRefRet();

		// compiles, but copies the struct, so out of scope; kept for completeness 
		new SomeStruct().InstanceMethod();
		new SomeStruct().ExtensionNoRefParam();
	}
}

public struct SomeStruct
{
	public SomeStruct InstanceMethod()
	{
		return this;
	}
}

public static class SomeExtensions
{
	public static SomeStruct ExtensionNoRefParam(this SomeStruct @this)
	{
		return @this;
	}

	public static SomeStruct ExtensionsRefParam(ref this SomeStruct @this)
	{
		return @this;
	}

	public static ref SomeStruct ExtensionRefParamRefRet(ref this SomeStruct @this)
	{
		return ref @this;
	}
}
```

### Expected behavior

Compiles the same as with an explicit variable

### Actual behavior

Currently it doesn't compile (triggers CS1510)

### Regression?

checked on net481 - the issue is there as well

### Known Workarounds

use a class instead of struct... however I really wanted to use a stack-allocated type to not bother GC...

### Configuration

using VS2022 on Win10, targetframework=net80, LangVersion=latest, platform=anycpu, it seems configuration-independent

**Comment by stephentoub** [comment]
This is by design. As the error states, "A ref or out value must be an assignable variable". If you want to pass it by ref, you can change the parameter to be `in` instead of `ref`, or you can make the location assignable by separating it out into a local.

**Comment by marchewek** [comment]
From the programmer perspective both cases deal with a variable (explicit in the former example, implicitly created by the compiler in the latter), so why should it behave differently? So... why is it by design? Was it too complex to implement? Are there any misusages that discard implementing it consistently across both cases?

As for the "in" parameter - it doesn't go very well with FluentAPIs; you cannot ref return an in param (what does make logical sense), so in the following tests Test1 will be performing better than Test2 (at least if to believe benchmark.net and being allowed to generalize from two machines):

``` csharp
public static ref RefReadonlyStruct Test1(ref this RefReadonlyStruct @this)
{
	// ...
	return ref @this;
}

public static RefReadonlyStruct Test2(in this RefReadonlyStruct @this)
{
	// ...
	return @this;
}
```

**Comment by marchewek** [comment]
@stephentoub it feels discouraging to propose potential improvements for the language when a finding is closed before the actual discussion happens...

**Comment by stephentoub** [comment]
> As for the "in" parameter - it doesn't go very well with FluentAPIs; you cannot ref return an in param

You can, see the sharplab link I shared in my response. The return just needs to be `ref readonly` rather than `ref`.

> why should it behave differently?

Because that's how the C# language was designed and how the specification defines the semantics. It's not about complexity of implementation.

> it feels discouraging to propose potential improvements for the language

I'm sorry you feel discouraged, that was obviously not my intent. But from my perspective, this wasn't written as a discussion nor was it proposing improvements; it was written as a bug report, specifically saying you weren't sure how it was supposed to behave, and I answered the question both highlighting that it's by design and sharing a fixed code sample that does what I believe you wanted to do (using a ref readonly return).

If you want to propose changes to the C# language, this is not the repo for that. This repo is not about the C# language/specification, but rather about the runtime and core libraries. Please feel free to propose/discuss C# language additions at https://github.com/dotnet/csharplang/discussions.

Thanks.
