### ISSUE TITLE
Logging errors on Linux similar to Windows Event Log

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#10526]
Logging unhandled exceptions to Windows Event Log was enabled with https://github.com/dotnet/coreclr/pull/16875 but currently we don't do anything on Linux. To match the diagnostics experience on Linux for .NET Core developers, we should try to log exceptions to something like ```/var/log/netcore.log```

**Comment by danmoseley** [comment]
Java uses /var/log/java

https://docs.oracle.com/en/java/javase/14/troubleshoot/fatal-error-log.html

I'm surprised we haven't gotten many asks for this. @tommcdon @davidfowl perhaps because it more relevant for supporting consumer/desktop apps - in a cloud scenario one has an app model that logs unhandled exceptions and monitoring systems that gather crash dumps, etc, is that the right way to think about it?
