### ISSUE TITLE
c# string.TrimStart() unexpected behaviour

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#105367]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/c-stringTrimStart-unexpected-behavio/10702517)._

---
[severity:It bothers me. A fix would be nice]
Hi,
I have a weired situation for C# string.Trim() and TrimStart() methods.

In DddBase.Presentation dll I have an object as below:

```
public class AdminPermissions
{
    public class App
    {
        public const string Admin = "AdminPermissions.App.Admin";
    }
}
```
Type.FullName = `"Haskap.DddBase.Presentation.CustomAuthorization.AdminPermissions+App"`
Type.Namespace = `"Haskap.DddBase.Presentation.CustomAuthorization"`
After TrimStart method = `FullName.TrimStart(Namespace.ToCharArray())` => result is `"+App"`
Where is the `"AdminPermissions"` part?

I use DddBase.Persentation dll in another MVC project (as added reference.) For another object in MVC project with the same structure I get correct behaviour. I think this is a bug, could you explain this wrong behaviour?

I use; 
- Windows 11 with latest updates, 
- .Net 8.0 (both for dll and MVC projects), 
- Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.10.4

Thank you.

---
#### Feedback Bot on 7/14/2024, 10:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by EgorBo** [comment]
Looks like a completely expected behavior to me
```cs
var FullName = "Haskap.DddBase.Presentation.CustomAuthorization.AdminPermissions+App";
var Namespace = "Haskap.DddBase.Presentation.CustomAuthorization";
Console.WriteLine(FullName.TrimStart(Namespace.ToCharArray()));
```
We split `"Haskap.DddBase.Presentation.CustomAuthorization"` into a char array and then remove all leading chars in `FullName` based on that set, so it's expected that we only stop at `+` char since it's not presented in the "leading chars to remove" set.

**Comment by danmoseley** [comment]
I'm guessing you want to remove the string prefix if present. Use StartsWith(str) and if that's true then Substring to remove it.

**Comment by EgorBo** [comment]
Right. The problem that we don't have a `String.TrimStart(string substring)` api. It's getting even worse in .NET 9.0 since e.g. `str.TrimStart("substring");` is going to compile just fine, but will work as char array too.

**Comment by stephentoub** [comment]
> The problem that we don't have a String.TrimStart(string substring) api.

If we wanted such a thing, we'd add it with a different name, like RemovePrefix or something similar. A "TrimStart" version of it would remove as many copies as it found, just like the existing trimming APIs, and not just a single instance.
 
> It's getting even worse in .NET 9.0 since e.g. str.TrimStart("substring");

It's already been the case since .NET Core 2.1 that str.AsSpan().TrimStart("substring") treats the argument as individual characters, and the world hasn't ended. This just does the same thing now without the AsSpan.

**Comment by huoyaoyuan** [comment]
One more report for #103892.

I think we should have at least an analyzer to capture the pit of failure.

**Comment by stephentoub** [comment]
> One more report for [#103892](https://github.com/dotnet/runtime/issues/103892).

Not really... the OP here is using .NET 8 and passing in ToCharArray.
