### ISSUE TITLE
support for int256 integer data type; (note: extremely happy to see int128 in .net7.0 and moving forward!)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#105650]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/support-for-int256-integer-data-type;-n/10701607)._

---
[severity:It's more difficult to complete my work]
application of number theoretic transforms is greatly enhanced with support now for int128 data types, thank you .net community! When will the next step of support for int256 be enabled. Int256 will enable work with even larger NTT primes and the ability to increase the base10 mulitple of array elements in computing NTT. NTT operations using base10 can be improved by using base=10000 (10^4), but the next incremental improvement requires 10^8 base multiples which unfortunately cause int ovflw with Int128 operations.

---
#### Lisa Gao (CSI Interfusion Inc) [MSFT] on 7/11/2024, 06:38 PM: 

(private comment, text removed)
#### Feedback Bot on 7/11/2024, 11:14 PM: 

(private comment, text removed)

**Comment by tannergooding** [comment]
Thanks for your interest and taking the time to open this issue.

The core .NET Libraries has a near infinite number of types and APIs it could expose, so we have to find the right balance around what is common enough for widespread use, what must be implemented in the libraries for interop/compatibility reasons, and meeting overall developer needs. In the case of `Int128` and `UInt128`, they are what are known as "ABI primitives" (Application Binary Interface) and they have specialized size, packing/alignment, method passing/returning, and more that's required at the fundamental layers. Additionally they have widespread hardware support (at least on 64-bit computers) that allows acceleration above and beyond what a normal implementation may otherwise be able to achieve. As such, they are types that fit into the "must be implemented by the core libraries" category. `Int256` and `UInt256` on the other hand have none of these special requirements or considerations. They are, for all intents and purposes, something that any library can successfully implement and accelerate. This is particularly true with the `Generic Math` feature that was introduced in .NET 7, which allows developers to provide checked and unchecked operator implementations, provide conversions to/from other numeric types, and integrate with generic algorithms constrained to these types.

So given the above and the increasing nicheness of the such larger integer types, this is not something we'd be looking at exposing at this time. The same would be true for any `Int512`, `Int1024`, etc types. It is, however, something we'd be open to revisiting in the future if the ecosystem and need for such a type significantly changes.
