### ISSUE TITLE
Use CType on windows 11

### ISSUE THREAD

**Issue by DorianCanville** [dotnet/runtime#105614]
### Description

If I use CType(string,Double) (with .Net Framework 4.8.1) on Windows 10 it works but, if I use it on Windows 11 it does't in specific case.

if my string is "10500,25", it works, but if it's "10 500,25" , it gives a wrong format error on Windows  11, enven though it works on Windows 10.

I searched on the internet, but I didn't find anyone discussing this issue. 

 same case with CDbl or CInt
 
 
![image](https://github.com/user-attachments/assets/cbcca90c-6973-4872-9dac-627b99c98a08)

### Reproduction Steps

Dim toto As Double = CType("1 050 500,25", Double) (on windows 11 .Net Framework 4.8.1)

### Expected behavior

toto = 1050500.25

### Actual behavior

Error 'The input string '1 050 500,25' was not in a correct format.' (but works on windows 10 .Net Framework 4.8.1)

### Regression?

don't works with .Net Framework 4.7.2 or 4.8.0 on windows 11

**Comment by tarekgh** [comment]
To parse a string to Double number, this will depend on the number formatting data that is picked from the OS or the OS component. formatting data like decimal separator, group separator, negative sign, positive sign, and negative/positive formatting patterns. You can find these properties in the class https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=net-8.0. You can use `CultureInfo.CurrentCulture.NumberFormat` to look at such property's values and what it returns on Windows 10 and Windows 11. The values of these properties are picked from the underlying OS (Windows in this case). Windows can change such data between releases. You may look at the blog https://devblogs.microsoft.com/i18n/culture-data-shouldnt-be-considered-stable/ for more info. 

To guarantee parsing numbers, you should use Invariant culture when formatting and parsing the numbers because Invariant culture data never changes and guarantees successful parsing for the numbers formatted with the same invariant cultures.
