### ISSUE TITLE
DI allows for Scoped services to be resolved from Singletons when DOTNET_ENVIRONMENT != Development

### ISSUE THREAD

**Issue by PaulBujor** [dotnet/runtime#105791]
### Description

If a singleton services references a scoped service, that project will fail to start only when DOTNET_ENVIRONMENT is set to Development, however, if it has any other value, it will be able to resolve that project and run.

### Reproduction Steps

[Reproduction project](https://github.com/PaulBujor/.net-di-environment-issue)

There are 2 launch profiles, one for Development and one non-development.

### Expected behavior

DI errors should happen regardless of environment

### Actual behavior

DI errors occur only when DOTNET_ENVIRONMENT is set to Development

### Configuration

SDK: 8.0.302
Runtime: 8.0.7
OS: Windows 11, replicated in a linux container based on mcr.microsoft.com/dotnet/aspnet:8.0-alpine

**Comment by PaulBujor** [comment]
Ah, then my bad when searching stuff :(

Thanks a lot, hopefully this will come up when someone else will look up something like this and help them.

**Comment by julealgon** [comment]
@KalleOlaviNiemitalo do you now the underlying reason why this check is only performed in development mode? I would assume it is because it is an expensive check, but not sure if the docs mention that fact or not.

There could be a warning regarding performance if that is confirmed to be the case so folks who want to turn it always on would be aware of the tradeoff.
