### ISSUE TITLE
Inconsistent Behavior of System.Numerics.Complex and Other Numeric Types

### ISSUE THREAD

**Issue by LEI-Hongfaan** [dotnet/runtime#105843]
### Description

I have noticed several inconsistencies related to value changing optimization in .NET. Here is one such example.

### Reproduction Steps

```csharp
using System.Numerics;

Console.WriteLine(new Matrix4x4(float.PositiveInfinity, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4) * 2);
Console.WriteLine(new Matrix3x2(float.PositiveInfinity, 0, 0, 0, 0, 4) * 2);
Console.WriteLine(new Quaternion(float.PositiveInfinity, 1, 1, 4) * 5);
Console.WriteLine(new Complex(float.PositiveInfinity, 1) * 4);
```

### Expected behavior

```
{ {M11:∞ M12:NaN M13:NaN M14:NaN} {M21:0 M22:0 M23:0 M24:0} {M31:0 M32:0 M33:0 M34:0} {M41:0 M42:0 M43:0 M44:8} }
{ {M11:∞ M12:NaN} {M21:0 M22:0} {M31:0 M32:8} }
{X:∞ Y:NaN Z:NaN W:NaN}
<∞; NaN>
```
- or -
```
{ {M11:∞ M12:0 M13:0 M14:0} {M21:0 M22:0 M23:0 M24:0} {M31:0 M32:0 M33:0 M34:0} {M41:0 M42:0 M43:0 M44:8} }
{ {M11:∞ M12:0} {M21:0 M22:0} {M31:0 M32:8} }
{X:∞ Y:5 Z:5 W:20}
<∞; 4>
```

### Actual behavior

```
{ {M11:∞ M12:0 M13:0 M14:0} {M21:0 M22:0 M23:0 M24:0} {M31:0 M32:0 M33:0 M34:0} {M41:0 M42:0 M43:0 M44:8} }
{ {M11:∞ M12:0} {M21:0 M22:0} {M31:0 M32:8} }
{X:∞ Y:5 Z:5 W:20}
<∞; NaN>
```

**Comment by tannergooding** [comment]
These are not the same types, it is natural for them to deviate from eachother in some scenarios because multiplication is defined differently between them. Different types have different rules and expectations for what is mathematically correct.

### Matrix4x4 * float

`new Matrix4x4(float.PositiveInfinity, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4) * 2` is multiplication of a 4x4 matrix by a scalar:
```
[
    [∞, 0, 0, 0]
    [0, 0, 0, 0]
    [0, 0, 0, 0]
    [0, 0, 0, 4]
]
```

In this case it is defined by multiplying each entry in the matrix by the scalar (better known as `elementwise multiplication`). Thus:
```
[
    [∞ * 2, 0 * 2, 0 * 2, 0 * 2]
    [0 * 2, 0 * 2, 0 * 2, 0 * 2]
    [0 * 2, 0 * 2, 0 * 2, 0 * 2]
    [0 * 2, 0 * 2, 0 * 2, 4 * 2]
]
```

This produces the actual result:
```
[
    [∞, 0, 0, 0]
    [0, 0, 0, 0]
    [0, 0, 0, 0]
    [0, 0, 0, 8]
]
```

### Matrix3x2 * float

This is the same scenario as `Matrix4x4` and also produces the expected result

### Quaternion * float

This is similarly defined as elementwise multiplication, thus is also producing the correct result.

### Complex * float

Complex multiplication is defined as `(a + bi) * (c + di) = ((a * c) - (b * d)) + ((a * d) + (b * c))i`

A real number `c` is then the same as the complex number `c + 0i` (the imaginary part is zero).

Therefore, this breaks down to the algorithm `((a * c) - (b * 0)) + ((a * 0) + (b * c))i`. Since IEEE 754 floating-point has `infinity` and `NaN`, this means that `b * 0`  and `a * 0` are not erased (they may be non-zero) and thus the computation is preserved.

For the case of `new Complex(float.PositiveInfinity, 1) * 4`, this breaks down to `((∞ * 2) - (1 * 0)) + ((∞ * 0) + (1 * 2))i`, which is then `(∞ - 0) + (NaN + 2)i`, which is `∞ + NaNi`, that is the result actually returned.
