### ISSUE TITLE
[API Proposal]: Add TryGetReadOnlySpan<T>() to CollectionsMarshal for ReadOnlyCollection<T>

### ISSUE THREAD

**Issue by mphelt** [dotnet/runtime#106066]
### Background and motivation

I would like to propose to add a `TryGetReadOnlySpan<T>()` method to `CollectionsMarshal` that would take as argument an instance of `ReadOnlyCollection<T>` class and return a `ReadOnlySpan<T>` if underlying collection is `T[]` or `List<T>`, which in my opinion is very common.
Thanks to such method iterating over such collection could be more performant with less allocations in hot path scenarios.

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public class CollectionsMarshal
{
    public static bool TryGetReadOnlySpan<T>(ReadOnlyCollection<T> collection);
}
```

### API Usage

```csharp
ReadOnlyCollection<T> collection = list.AsReadOnly(); // or array.AsReadOnly();

if (CollectionsMarshal.TryGetReadOnlySpan(collection, out var span))
{
    // for loop over span
}
else
{
    foreach (var value in collection)
    {
        ...
    }
}
```

### Alternative Designs

1. Add this method to `CollectionExtensions` static class
2. Add this method directly to `ReadOnlyCollection<T>` as virtual

**Comment by colejohnson66** [comment]
Why limit to just ROCollection?

**Comment by mphelt** [comment]
I would like to limit to ROC to increase chances of getting this.

Other collections could have a separate issue(s) if they make sense.

What other collections make sense?
- array - one can easily create ROS from it
- list - CollectionsMarshall already exposes its internal array
- Collection<T> - is it used that often?
- ObservableCollection<T> - used mostly in MVVM apps, but not sure if more performant enumeration is needed

**Comment by eiriktsarpalis** [comment]
I find it unlikely that we would ever expose `Try-` methods for exposing the underlying span that may or may not back the elements of an abstract collection. It is not extensible to arbitrary user-defined collections and makes evolving the internal implementation details of a collection more difficult due to potential dependencies that such method would be creating.

The `CollectionMarshal.AsSpan` method added for `List<T>` is unsafe and was added specifically because the underlying buffer preserves the natural enumeration order of the collection, and that is unlikely to ever change. This is not the case for other collections backed by arrays such as `Stack<T>`, `Queue<T>` or `PriorityQueue<T,P>`.
