### ISSUE TITLE
Object cloning does not work in maui 

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#106077]
### Description

Deep or shallow object cloning does not work in maui 

### Steps to Reproduce
try to copy any control using the following code

```C#
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CrossPlatformLibrary.CSExtended.CSESystem
{
    public class CSEObject
    {
        public object ShallowCopy(object o)
        {
            return o?.GetType().GetMethod("MemberwiseClone", BindingFlags.Instance | BindingFlags.NonPublic)?.Invoke(o, null);
        }

        public object Copy(object o)
        {
            return DeepCopy(o);
        }
        public static object DeepCopy(object o)
        {
            JsonSerializerOptions jsonOptions;

            jsonOptions = new JsonSerializerOptions();

            jsonOptions.Converters.Add(new JsonStringEnumConverter());

            var json = JsonSerializer.Serialize(o, jsonOptions);
            return JsonSerializer.Deserialize(json, o.GetType(), jsonOptions);
        }
    }
}
```

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

No, this is something new, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

no

### Relevant log output

```shell
System.NotSuppotedException
```

**Comment by eiriktsarpalis** [comment]
I would say that this is expected behaviour for some object inputs at least -- unlike serializers like BinaryFormatter System.Text.Json doesn't support roundtripping arbitrary object graphs, as such it can't be used as a reliable mechanism to deep clone objects.

Would it be possible to share the specific object that is causing the error for you? We might be able to provide a better recommendation for it.

**Comment by Barshan-Mandal** [comment]
> I would say that this is expected behaviour for some object inputs at least -- unlike serializers like BinaryFormatter System.Text.Json doesn't support roundtripping arbitrary object graphs, as such it can't be used as a reliable mechanism to deep clone objects.
> 
> Would it be possible to share the specific object that is causing the error for you? We might be able to provide a better recommendation for it.

WebView control is causing the issue.If this method is not reliable then show me another reliable standard way

**Comment by eiriktsarpalis** [comment]
> WebView control is causing the issue.Shallow cloning and deep cloning both does not work.If this method is not reliable then show me another reliable standard way

Is WebView using System.Text.Json to perform deep cloning?

**Comment by Barshan-Mandal** [comment]
> > WebView control is causing the issue.Shallow cloning and deep cloning both does not work.If this method is not reliable then show me another reliable standard way
> 
> Is WebView using System.Text.Json to perform deep cloning?

I am passing webview control for deep cloning through DeepCopy(object o)

**Comment by eiriktsarpalis** [comment]
Ok. Like I said using STJ to deep clone arbitrary objects is not supported due to how the serializer has been designed. If you can share examples of the types of objects you are trying to serialize I might be able to provide a more specific recommendation, but generally speaking using an unsafe serializer like Json.NET or BF might be better suited for your use case.

**Comment by Barshan-Mandal** [comment]
Json.NET or BF also throws error.Give me a way to do this deep cloning and shallow cloning.Before that dont close the issue

**Comment by huoyaoyuan** [comment]
**Not every object can be "cloned" at all.** Especially WebView, which requires heavily on external resource including the actual browser process. The UI controls are usually not cloneable too, because their state would include graph relationship within the visual tree.
In this case, the UI object itself may provide a "duplicate" functionality to create a copy with similar properties, but with the external states detached.

**Comment by eiriktsarpalis** [comment]
I closed the issue because it isn't actionable from the perspective of System.Text.Json: the scenario is not supported by design. We might still be able to support you provided that you give us more details: the precise object you are trying to clone and the method that performs the deep cloning for BF or Json.NET. That being said, as @huoyaoyuan mentioned not every object is inherently cloneable even if you use BinaryFormatter.

**Comment by Barshan-Mandal** [comment]
then tell me a way by which i can copy every property of the webview for assigning

**Comment by huoyaoyuan** [comment]
You can use reflection or source generation to copy every public property to a clone. Again, this may not be valid at all. The properties may contain other elements in the visual tree, or other things that's not sharable.

Given the requested type is clear, the correct way is to manual write copy statement for every meaningful property.
