### ISSUE TITLE
assert(firstILBlock->hasProfileWeight());

### ISSUE THREAD

**Issue by mikelle-rogers** [dotnet/runtime#106033]
I hit this assert while running a sensitive workload. I have saved the repro instructions. Feel free to reach out for access.

**Comment by AndyAyersMS** [comment]
Not likely to affect the product in any noticeable way, so will mark as .NET 10 for now.

**Comment by AaronRobinsonMSFT** [comment]
More details on issue are at https://github.com/dotnet/runtime/issues/107055.

**Comment by AaronRobinsonMSFT** [comment]
> Not likely to affect the product in any noticeable way, so will mark as .NET 10 for now.

@AndyAyersMS This isn't affecting the product per se, but it does block managed debugging on a Checked runtime. I would consider reprioritizing this as it is blocking for the inner dev loop if only a managed debugger is attached.

**Comment by AndyAyersMS** [comment]
> > Not likely to affect the product in any noticeable way, so will mark as .NET 10 for now.
> 
> @AndyAyersMS This isn't affecting the product per se, but it does block managed debugging on a Checked runtime. I would consider reprioritizing this as it is blocking for the inner dev loop if only a managed debugger is attached.

Ah, I didn't realize. Do you need a fix in 9, or is main sufficient?

**Comment by AaronRobinsonMSFT** [comment]
main is sufficient for me and I'd imagine for most use cases at this point.

**Comment by AndyAyersMS** [comment]
I am seeing a different assert in `ProfilerInstrumentationTests.Instrumentation_PInvoke_GcStressl`. Perhaps it is a different symptom of the same underlying problem
```
 Assert failure(PID 22968 [0x000059b8], Thread: 25312 [0x62e0]): Assertion failed '!m_mismatch' in 'System.Diagnostics.Debug:Assert(ubyte,System.String,System.String)' during 'Profile incorporation' (IL size 80; hash 0x8afd7903; Tier1)
```
It looks like the IL for `Debug.Assert` was modified while the method was on the rejit queue, and the Tier1 jit request is unable to make sense of the Tier0 produced schema (which is keyed to initial the IL).

I'm a little surprised at the tiering behavior here, it looks like the tiering rejit uses whatever the latest IL is for the method, and not the IL that triggered the tiering request, so this sort of mismatch seems inevitable and the JIT will need to tolerate it (in release it does, by just ignoring the profile data).

I can relax the assert but it would be nice to have some clue that the IL has changed, since if it hasn't changed we would expect the schemas to match.

@AaronRobinsonMSFT I can't repro the failures you were seeing. If you still have a repro, can you capture a jit dump for me? 

Eg for the first failure you listed in #107055, do something like
```
set DOTNET_JitHashDump=06a6c31d
set DOTNET_JitStdOutFile=[some scratch directory]\jit.dump
```
then run the failing test and share out the dump file?

This assert also fired in #93768, #101900, and #101897; the latter two were dup'd to #101901.

**Comment by AndyAyersMS** [comment]
Ok, I got a repro of Aaron's issue (requires running under VS)
```

Assert failure(PID 10744 [0x000029f8], Thread: 25624 [0x6418]): Assertion failed 'firstILBlock->hasProfileWeight()' in 'System.String:Ctor(ulong):System.String' during 'Compute block weights' (IL size 55; hash 0x0f67cbd1; Instrumented Tier1)

    File: C:\repos\runtime0\src\coreclr\jit\fgprofile.cpp:4444
    Image: c:\repos\runtime0\artifacts\tests\coreclr\windows.x64.checked\tests\core_root\corerun.exe

===================================================================== *Blocks 0

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    [???..???)-> BB02(1)                 (always)                     i keep internal hascall
BB02 [0007]  1       BB01                  1    [???..???)-> BB04(0.5),BB03(0.5)     ( cond )                     internal
BB03 [0008]  1       BB02                  0.50 [???..???)-> BB04(1)                 (always)                     internal
BB04 [0006]  2       BB02,BB03             1    [???..???)-> BB05(1)                 (always)                     i keep internal hascall
BB05 [0001]  1       BB04                  1    [000..005)-> BB07(0.5),BB06(0.5)     ( cond )                     i
BB06 [0002]  1       BB05                  1    [005..00B)                           (return)                     i hascall
BB07 [0003]  1       BB05                  1    [00B..015)-> BB09(0.5),BB08(0.5)     ( cond )                     i hascall gcsafe
BB08 [0004]  1       BB07                  1    [015..01B)                           (return)                     i hascall
BB09 [0005]  1       BB07                  1    [01B..037)                           (return)                     i hascall gcsafe nullcheck
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
`fgPgoHaveProfileWeights` is true, but we're not optimizing, so we didn't actually incorporate the profile data. We need to null out this pointer if we're not optimizing, or stop running the block weight phase (to wit: the jit initially thinks it is optimizing, fetches the profile data pointer, then sees the minops flag, and decides not to optimize).
