### ISSUE TITLE
ARM-SVE: AddSequentialAcross() is defined incorrectly

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#106180]
Note how the C++ API uses floats, but C# uses vectors:
```
        /// <summary>
        /// float64_t svadda[_f64](svbool_t pg, float64_t initial, svfloat64_t op)
        ///   FADDA Dtied, Pg, Dtied, Zop.D
        /// </summary>
        public static unsafe Vector<double> AddSequentialAcross(Vector<double> initial, Vector<double> value) => AddSequentialAcross(initial, value);
```

[FADDA](https://docsmirror.github.io/A64/2023-09/fadda_v_p_z.html) instruction:
`FADDA <V><dn>, <Pg>, <V><dn>, <Zm>.<T>`

Output from coreclr:
`IN0021:             fadda   z17, p0, z17, z16.s`

**Comment by a74nh** [comment]
The signature is `Vector<double> AddSequentialAcross(Vector<double> initial, Vector<double> value)`

But underneath this is  `ScalarValueinSIMDVector AddSequentialAcross(SIMDVector initial, SVEVector value)`

What confuses me here is how we ensure that `initial` is SIMDVector and `value` is SVEVector? Ok, for 128bit (which is all we support) then it all works out ok. But this will break for >128bit.  @tannergooding  ?

In addition, we are conditionalselect optimising this incorrectly. I'm not exactly sure yet but it might just require stopping the use of movprfx before it, or it might require more changes.

**Comment by tannergooding** [comment]
The `C` definition is `float64_t svadda[_f64](svbool_t pg, float64_t initial, svfloat64_t op)`, the underlying instruction is `FADDA <V><dn>, <Pg>, <V><dn>, <Zm>.<T>`, and the instruction operation is defined as:
```
CheckNonStreamingSVEEnabled();
constant integer VL = CurrentVL;
constant integer PL = VL DIV 8;
constant integer elements = VL DIV esize;
bits(PL) mask = P[g, PL];
bits(esize) operand1 = V[dn, esize];
bits(VL) operand2 = if AnyActiveElement(mask, esize) then Z[m, VL] else Zeros(VL);
bits(esize) result = operand1;

for e = 0 to elements-1
    if ActivePredicateElement(mask, e, esize) then
        bits(esize) element = Elem[operand2, e, esize];
        result = FPAdd(result, element, FPCR);

V[dn, esize] = result;
```

So the definition here is correct and intentional, although it possibly should be `Vector128<double> AddSequentialAcross(Vector128<double> initial, Vector<double> value)` instead.

That is due to `floating-point` scalars living in element 0 of the SIMD registers it is intentional that the APIs which take `float`/`double` scalars instead consume or produce them as vectors. This is overall more convenient as you're typically passing in or consuming the output in a larger SIMD algorithm, but also more accurate because you can pass in upper state that is sometimes relevant. If a user needs a scalar seed value, they can simply convert it to a vector using `Vector.CreateScalar(2.0)`, `Vector.CreateScalarUnsafe(x)`, etc. (where the `Unsafe` variants can be "zero-cost"). For consuming values the inverse direction of doing `ToScalar()` is not zero cost, because writing a 128-bit register zeros the upper bits and that can be impactful since it is a mutation.

**Comment by a74nh** [comment]
> So the definition here is correct and intentional, although it possibly should be `Vector128<double> AddSequentialAcross(Vector128<double> initial, Vector<double> value)` instead.

If that's ok, I'll update the API to this. It should stop it breaking when we go >128bit.

> That is due to `floating-point` scalars living in element 0 of the SIMD registers

Understood, makes sense.

**Comment by tannergooding** [comment]
> It should stop it breaking when we go >128bit.

Noting that while I'm fine with making it more consistent with other `Across` APIs, I don't think it will break.
- we can do this now, but we need to take it back to API review before we ship it as stable if we do

Rather, it will just be more verbose than is actually required as `SVE` registers remain supersets of `V128` registers, in the same way `V128` is a superset of `V64` and in turn `float`/`double`. So there's still a convenience factor here of taking/returning `Vector<T>`, in many senses. The upper elements of the return are simply always zero.

**Comment by a74nh** [comment]
Ok, happy to keep the API signature the same then.

When needs checking then is:
* Fix the codegen printing.
* Are there other issues in the codegen we've got wrong for it?
* It should never be prefixed by `movprfx`. Possibly that's just a change of flag in `hwintrinsiclistarm64sve.h`
