### ISSUE TITLE
System.Text.Json  should allow any JSON type to be able to deserialzie to `string` type.

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#106245]
## user case 

json from a API

```jsonc
//json-a

{
    "Id":"Abc123"
}

//json-b
{
    "Id": 123
}
```

the mode class 

```C#
public class Foo
{
     public string Id { get;set;}
}

```

current System.Text.Json doesn't allow this deserialzation, and it throw on "jsonb" ,   
to deserialze this ,  the model should change the  type from `string` to  "JsonNode/JsonElement" .  **but** the "JsonNode/JsonElement" is for dynamic complex type,   and for this  json model , the best type for the property is `string`,  which means the number version json is wrong (may be because the api is using a dynamic type language like javascript)

## suggestion

```C#

JsonSeriazlieOptions.StringHanding = JsonStringHanding.AllowAnyType;

public enum JsonStringHanding
{
    Strict,
    AllowNumbersAndBollean,
    AllowAnyType
}

```

## refence

- #56760
- #37354

**Comment by elgonzo** [comment]
For special cases like these use a JsonConverter, something like:
```C#
class ReadAsStringConverter : JsonConverter<string>
{
    public override string? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => JsonElement.ParseValue(ref reader).ToString();

    public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        => _defaultConverter.Write(writer, value, options);

    private static readonly JsonConverter<string> _defaultConverter = (JsonConverter<string>) JsonSerializerOptions.Default.GetConverter(typeof(string));
}
```

**Comment by elgonzo** [comment]
> ```C#
> reader.TryGetDouble(out double number)
>    ? number.ToString()
>    : JsonElement.ParseValue(ref reader).ToString(),
> ```
That's giving inaccurate/incorrect results because of converting the json number into an inherent imprecise binary floating point type. As a result, large integers with very large absolute values (including such that would be otherwise readable as `long`/`ulong`) and some particular real numbers would not be correctly converted to strings.

At the cost of a possible intermediate byte array allocation, the conversion can be made in a way to preserve the the original json number accurately (i guess):

```C#
    ...
    JsonTokenType.Number =>
        Encoding.UTF8.GetString(reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan),
    ...
```
