### ISSUE TITLE
Implement IsNullOrWhitespace using SearchValues

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#106235]
Since we're only checking for a [known set of characters](https://learn.microsoft.com/en-us/dotnet/api/system.char.iswhitespace?view=net-8.0#remarks), I think it could take advantage of `SearchValues`.

**Comment by stephentoub** [comment]
It could, but typically with IsNullOrWhiteSpace the input isn't, and often the first character isn't. The overhead of vectorizing it then becomes measurable because the benefits of the increased throughput on the minority of uses don't offset the startup overhead. You're welcome to try, but we've tried in the past and it hasn't been profitable.

**Comment by jeffhandley** [comment]
Closing per @stephentoub's comment that we've explored this previously without realizing gains.
