### ISSUE TITLE
Convert.FromBase64(string s) not able to convert valid string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#106386]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ConvertFromBase64string-s-not-able-to/10718015)._

---
[severity:I'm unable to use this version]
![image.png](https://aka.ms/dc/image?name=B4a795509b60346d5983b2aef3d17428f638586665477579656_20240807-172907-image.png&tid=4a795509b60346d5983b2aef3d17428f638586665477579656)

This is in .NET 6. For some reason, this valid string throws a System.FormatException. Adding a character to the end of it results in no exception.

---
#### Feedback Bot on 8/8/2024, 10:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by stephentoub** [comment]
The image from the original report wasn't transferred:
![Image](https://github.com/user-attachments/assets/5b301f2f-8f58-487a-8578-0a88b7d01615)

> For some reason, this valid string throws a System.FormatException

Because it's invalid Base64. Base64-encoded text is a multiple of 4 in length, and is padded with '=' characters to make it so if it's not already. Your input is 27 characters long, which is not a multiple of 4.

> Adding a character to the end of it results in no exception.

Because that increases the length from 27 to 28 characters, which (assuming you added a valid Base64 character) makes it valid Base64.
