### ISSUE TITLE
Disallow nonexistent DateTime creation

### ISSUE THREAD

**Issue by solid1353** [dotnet/runtime#106821]
### Description

At the moment you can specify `kind = DateTime.Local` and a date/time that doesn't exist in local timezone for `DateTime` constructor due to transition to DST. No exception will be thrown during creation, however it will be once you try to convert the date.

### Reproduction Steps

```
var dt = new DateTime(2024, 3, 10, 2, 30, 0, DateTimeKind.Local);
TimeZoneInfo.ConvertTime(dt, TimeZoneInfo.Local, TimeZoneInfo.Utc);
```
Local timezone is `(UTC-05:00) Eastern Time (US & Canada)`

### Expected behavior

An exception should be thrown during `DateTime` creation.

### Actual behavior

```
Unhandled exception. System.ArgumentException: The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid. (Parameter 'dateTime')
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone)
```

### Configuration

.NET 8
Windows 11 Pro 22621.3737

**Comment by filipnavara** [comment]
`DateTimeKind.Local` doesn’t necessarily mean its **your** local time zone, it means it’s some local time zone. Since the time zone is not specified in the `DateTime` itself it’s inferred only when you do some transformation. That transformation may use explicit time zone parameter or assume your local time zone. Until that is done, though, the value is always valid is **some** local time zone (eg. some countries use UTC without daylight savings time).

**Comment by Clockwork-Muse** [comment]
> `DateTimeKind.Local` doesn’t necessarily mean its **your** local time zone, it means it’s some local time zone.

I struggle to imagine a case where "local" is ever reasonably used to mean "some unknown local timezone" and not "machine/user local timezone" in this sort of context.  At minimum, my assumption would be that the general consensus is that the common definition is "local to me", as reported here.

This is particularly pointed with [`DateTime.ToLocalTime()`](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tolocaltime?view=net-8.0), and pretty much all methods on `DateTime` that involve it.  Essentially all code involving `DateTimeKind` treats `Local` as "the machine/context local zone".  See for instance [the Remarks section of `TimeZoneInfo.ConvertTime`](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.converttime?view=net-8.0).  So no, it's not an arbitrary "local-zone" time.

<hr />

@solid1353 - 
Having it throw on creation wouldn't help, because there's ways to invalidate the value **after** creation:
 - timezone of the machine/process/context changes to one where the rules are different
 - timezone stays the same, but the rules are updated to include a DST change

Arguably what should really be provided instead (with an analyzer) is something with a resolver for invalid/duplicate times so that it _doesn't_ throw.

That said, if you're doing a lot of timezone-related work, you should either be using `DateTimeOffset` (or the potential future `DateTimeZoned`, if we ever get around to writing it), or switch to [NodaTime](https://nodatime.org/) for a better date-time experience.

<hr />

I hate `DateTimeKind`, because it causes all sorts of issues, and it should die in a fire.

**Comment by filipnavara** [comment]
> I struggle to imagine a case where "local" is ever reasonably used to mean "some unknown local timezone" and not "machine/user local timezone" in this sort of context.

We process iCalendar event data. The time coming in that context could be DATE, DATE-TIME and the DATE-TIME can be specified either as UTC or a local time with a time zone name. As much as you may or may not like it, we use `DateTime` to represent the UTC/local distinction at certain points. It's eventually paired with the time zone information but at various stages in the data parsing we don't have the time zone yet, we simply have a point in time specified in "local" or "utc" coordinates.

Another use case is parsing log files. Once again, the timestamps in the log file may be UTC or local time depending on the format and the time zone information may come out-of-band (eg. from user input) to interpret those values.

**Comment by tarekgh** [comment]
@filipnavara is correct in his response here. We cannot throw while creating DateTime with Local kind because of the reasons mentioned @filipnavara. Local time zone is used only when need to handle specific operations (like DateTime.Now for instance). In such scenarios use it is recommended to use TimeZoneInfo for validating any specific date liked to specific time zone. It is not wise to have such code occasionally throws in some machiines and work on another machines setup with different time zones.. I am closing the issue but feel free to send any more questions we can help with.
