### ISSUE TITLE
[API Proposal]: Support General Math value creation without sign propagation

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#106927]
### Background and motivation

I want to calculate the difference between two values as a non-negative `max - start` number.

`TFrom start`, and `TFrom max` define a range whose length is from `0` to `int.MaxValue - 1`.
`0 <= length < int.MaxValue`

When `TFrom` is wider than `int`, calculate the length simply as `length = int.CreateTruncating(end - start)`, because the difference `end - start` is always positive.

When `TFrom` is narrower than `int` and has a sign, the difference between them can be a negative number, which is difficult to convert to a positive value. For example when `TFrom` is `sbyte` and `start = -128; max = 127` then `length = 128 + 127 = 255 = -1 (signed byte)`.

It isn't not easy to convert TFrom(-1) to positive TTo(255)
`int.CreateTruncating(TFrom(-1))` creates int(-1)
`uint.CreateTruncating(TFrom(-1))` creates uint.MaxValue. **This made the sign propagation!**

So I made the next workaround code.

```cs
            internal static int StartMaxCount(T start, T max)
            {
                int count = int.CreateTruncating(max - start);
                if (count < 0)
                    count = int.CreateTruncating(max) - int.CreateTruncating(start);
                return count;
            }
```

### API Proposal

```csharp
namespace System.Numerics
{
    public interface INumberBase<TSelf> where TSelf : INumberBase<TSelf>?
    {
        static TSelf CreateTruncating<TOther>(TOther value, bool signPropagation) where TOther : INumberBase<TOther>;

        protected static bool TryConvertFromTruncating<TOther>(TOther value, bool signPropagation, [MaybeNullWhen(false)] out TSelf result) where TOther : INumberBase<TOther>;

        protected static bool TryConvertToTruncating<TOther>(TSelf value, bool signPropagation, [MaybeNullWhen(false)] out TOther result)  where TOther : INumberBase<TOther>;
    }
}
```

### API Usage

```csharp
// Range where TFrom is sbyte
TFrom start = -128;
TFrom max = 127;

// Calculate the correct length
int length = int.CreateTruncating(max - start, false);
```

See also
https://github.com/dotnet/runtime/blob/e689e2a3d8dfedfbefb17fb9ad559401c208265d/src/libraries/System.Linq/src/System/Linq/Range.cs#L30-L49

**Comment by colejohnson66** [comment]
If you need a delta between two numbers, use `INumberBase<TSelf>.Abs`

**Comment by tannergooding** [comment]
> When TFrom is larger int — all is okey.

This doesn't sound correct, as you could have a negative result produced for the scenario I gave, such as `start = 0, end = 2_147_483_648` (which gives `int.CreateTruncating(2_147_483_648)`, which is `-2_147_483_648`) or `start = 0, end = 4_294_967_295` (which gives `int.CreateTruncating(4_294_967_295), which is `-1`).

The only case it would be safe is if you knew that `end - start` must produce a value within the range `[0, int.MaxValue]` and therefore such cases are impossible to encounter (in which case you should likely have some validation or assertion that is true to avoid bugs).

> For example when TFrom is sbyte, start = -128; end = 127 then len = 127 + 128 = -1; So I need to convert sbyte(-1) to int(255).

When you have negatives covering the full range like this, there isn't really any fix you can do. You have lost information the moment you did `127 - (-128)` and it became `-1`, when it should've been `255`.

You can't use the `Read/Write` APIs like you suggested in the top post because there isn't any guarantee that `TFrom` wrote the value in a bit pattern that translates exactly to the equivalent unsigned bit pattern. For example, it would be legal to define some `MyCustomType` that was identical to `sbyte` in every way, but where it always serialized using 4-bytes in `WriteLittleEndian`, in which case it would write `0xFFFF_FFFF` for `-1`, not `0xFF`, and thus would become `-1` when read as an `int`, not `255`.

For types with a representable range smaller than `int`, you could upcast to `int` to ensure that it is always correct. But you would inversely need to upcast to say `long` if `TFrom` was `int` itself because `int.MaxValue - int.MinValue` is similarly unrepresentable by `int`. So the only real solution is to take another generic representing the result type and to recommend that the representable range be at least twice that of the input type.

**Comment by AlexRadch** [comment]
> The only case it would be safe is if you knew that `end - start` must produce a value within the range `[0, int.MaxValue]` and therefore such cases are impossible to encounter (in which case you should likely have some validation or assertion that is true to avoid bugs).

Yes `end - start` is in the range `[0, int.MaxValue]`. I mentioned this.

> For types with a representable range smaller than int, you could upcast to int to ensure that it is always correct. But you would inversely need to upcast to say long if TFrom was int itself because int.MaxValue - int.MinValue is similarly unrepresentable by int. So the only real solution is to take another generic representing the result type and to recommend that the representable range be at least twice that of the input type.

I don't know in advance when `TFrom` is greater or less than `TTo`. And the available methods do not allow you to know this at runtime.

> You can't use the Read/Write APIs like you suggested in the top post because there isn't any guarantee that TFrom wrote the value in a bit pattern that translates exactly to the equivalent unsigned bit pattern. For example, it would be legal to define some MyCustomType that was identical to sbyte in every way, but where it always serialized using 4-bytes in WriteLittleEndian, in which case it would write 0xFFFF_FFFF for -1, not 0xFF, and thus would become -1 when read as an int, not 255.

It works for `sbytes`, and `short`. But it can not work for custom types.

**Comment by AlexRadch** [comment]
>  You can't use the Read/Write APIs like you suggested in the top post because there isn't any guarantee that TFrom wrote the value in a bit pattern that translates exactly to the equivalent unsigned bit pattern. For example, it would be legal to define some MyCustomType that was identical to sbyte in every way, but where it always serialized using 4-bytes in WriteLittleEndian, in which case it would write 0xFFFF_FFFF for -1, not 0xFF, and thus would become -1 when read as an int, not 255.

I propose to expand the API for this case so that it always works.

**Comment by tannergooding** [comment]
> It works for sbytes, and short. But it can not work for custom types.

Which means its not an API we can provide in box.

> I propose to expand the API for this case so that it always works.

This would be a breaking change and is not something we're interested in doing.

> I don't know in advance when TFrom is greater or less than TTo. And the available methods do not allow you to know this at runtime.

If you can guarantee that `end - start` is in the range `0, int.MaxValue` always, then a simple way to handle it is something like:
```csharp
length = int.CreateTruncating(end - start);

if (length < 0)
{
    length = int.CreateTruncating(end) - int.CreateTruncating(start);
}
```

**Comment by AlexRadch** [comment]
> > I propose to expand the API for this case so that it always works.
> 
> This would be a breaking change and is not something we're interested in doing.

No breaking change in my suggestion.

**Comment by tannergooding** [comment]
The breaking change is that we cannot provide such a DIM without requiring some behavioral breaking change due to the fact that the output of `WriteLittleEndian` for a signed value is not guaranteed to represent the unsigned two's complement value of the same number of bits as the input type when interpreted as `unsigned` .

Such as for `MyCustomType` being 8-bits but opting to serialize using 32-bits.

There's no API we could provide here because there is no way to do the conversion and have it always behave as you're intending.

**Comment by AlexRadch** [comment]
@tannergooding I didn't look at how `CreateChecked`, `CreateChecked`, and `CreateTruncating` are implemented.
I somehow doubt that they are implemented through writing and reading into the buffer. Perhaps I'm wrong.

**Comment by tannergooding** [comment]
There are two `protected abstract` methods `TryConvertFrom*` and `TryConvertTo*` for each of the `Create*` methods. These are used in a specific pattern so that conversions can work regardless of how the layering exists (first preferring a conversion defined by `TSelf` and then the conversion defined by `TOther` if none exists).

This ensures that some concrete type is always defining the correct conversion behavior, because it at least understands its own definition and that is enough to ensure correct deterministic behavior in most scenarios.

The number types were designed to work by understanding the exact represented value of a `T`, regardless of what two's complement representation it serialized to. They were not designed to allow reinterpreting the raw bits to a different type as that's something that only becomes sensible if you know the concrete type.

**Comment by AlexRadch** [comment]
@tannergooding As far as I understood your explanation, the proposed API can be implemented. I'm not suggesting using serialization.

**Comment by tannergooding** [comment]
You're going to have to give the code you believe will work here. 

I do not see a way that a `CreateTruncatingWithoutSign` API could not be provided because, we cannot provide a valid DIM that ensures correct behavior for any potential type.

**Comment by AlexRadch** [comment]
> You're going to have to give the code you believe will work here.

@tannergooding 
I wrote an example of implementing the new API, for the `sbyte` and `int` types.
It is not optimized for production but shows the concept.
I also wrote a test that uses the new API.

```cs
            Assert.Equal(unchecked((int)0xFFFFFF80), NumberBaseHelper<int>.CreateTruncating<sbyte>(unchecked((sbyte)0x80), true));
            Assert.Equal(unchecked((int)0xFFFFFFFF), NumberBaseHelper<int>.CreateTruncating<sbyte>(unchecked((sbyte)0xFF), true));

            Assert.Equal(unchecked((int)0x80), NumberBaseHelper<int>.CreateTruncating<sbyte>(unchecked((sbyte)0x80), false));
            Assert.Equal(unchecked((int)0xFF), NumberBaseHelper<int>.CreateTruncating<sbyte>(unchecked((sbyte)0xFF), false));
```
https://github.com/dotnet/runtime/blob/47c68c6974c3639add6c67cd2b54ecf9305480a7/src/libraries/System.Runtime/tests/System.Runtime.Tests/System/Int32Tests.GenericMath.cs#L1980-L1999

**Comment by tannergooding** [comment]
@AlexRadch, I think you misunderstood.

I meant a generic DIM implementation, not a per type specialized implementation. This would require a DIM and therefore a valid default implementation would need to be provided, which I don't believe is possible here.

**Comment by AlexRadch** [comment]
> I meant a generic DIM implementation, not a per type specialized implementation. This would require a DIM and therefore a valid default implementation would need to be provided, which I don't believe is possible here.

I don't understand why we need to make a generic DIM implementation of the new `TryConvertToTruncating`, `TryConvertFromTruncating` methods that work for all types?

**Comment by tannergooding** [comment]
You cannot expose new methods on existing interfaces without giving them a default implementation, that is a breaking change otherwise.

The `TryConvertTo/From*` APIs are protected helpers used by the public `Create*` to help give a deterministic order to the create APIs to help ensure that we don't get into infinite cycles, ambiguities, or all the other problems that can come about for near arbitrary conversions between types.

It is likewise not sufficient to introduce APIs which fail for all types by default. This is a pit of failure for users.

The behavior you're wanting here rather seems something that is specific to two's complement representation and bit-blitting of data between types, not something that is truly general purpose and works for all numeric types. I do not think it is a good fit for the generic APIs.

**Comment by AlexRadch** [comment]
I wrote a default implementation, otherwise nothing would have compiled for me.

https://github.com/dotnet/runtime/blob/47c68c6974c3639add6c67cd2b54ecf9305480a7/src/libraries/System.Private.CoreLib/src/System/Numerics/INumberBase.cs#L411-L421

https://github.com/dotnet/runtime/blob/47c68c6974c3639add6c67cd2b54ecf9305480a7/src/libraries/System.Private.CoreLib/src/System/Numerics/INumberBase.cs#L460-L470

**Comment by tannergooding** [comment]
That implementation fails for common inputs and will result in the public `TOther CreateTruncating<TOther>(TSelf value, bool signPropagation)` API throwing `NotSupportedException`.

For example, `uint.CreateTruncating<int>(-1, false)` would first try `TryConvertFromTruncating` and would see that `signPropagation` is `false` and `value` is negative, so it would return false. It would then try `TryConvertToTruncating` and see the same. Thus, the default implementation fails for one of the "common" expected use-cases; rather than being a correct but likely slower implementation.

The expectation is that by default:
* `uint.CreateTruncating<int>(-1, false)` would result in `uint.MaxValue`
* `long.CreateTruncating(-1, false)` would result in `uint.MaxValue`
* `long.CreateTruncating(-1, true)` would result in `-1`

This is what I believe cannot be trivially achieved through a DIM and which is largely relying on very particular semantics of two's complement fixed-width primitive integer types, not something which is more general-purpose/generic in nature and which is a good fit for arbitrary number types.

**Comment by AlexRadch** [comment]
For base types, the new `TryConvert` methods will be implemented by the base types themselves. For the `sbyte` and `int` types I gave an example of such an implementation.

After all, even now there is no correct general slow implementation of the old `TryConvert` methods — base types implement them.

I don't understand why the old `TryConvert` methods **should not have** the correct common slow implementation for all types. Still, the new `TryConvert` methods  **should have** the correct common slow implementation for all types. 

Where does this demand come from?

**Comment by tannergooding** [comment]
> After all, even now there is no correct general slow implementation of the old TryConvert methods — base types implement them.

These were introduced day 1 and do not have DIMs, it is required for all types to implement them so there is no risk of existing types not supporting such an API.

Now that the types have shipped, new members must have DIMs to avoid being a binary breaking change. That DIM needs to be sensible and function as users would roughly expect across all types. A given type can then explicitly provide their own more efficient implementation, but that should namely be for performance or precision not for general correctness.

**Comment by AlexRadch** [comment]
Ok. I think I can use `INumberBase<TSelf>.Radix` property and make default slow implementation.
I will try.
