### ISSUE TITLE
Build AOT static library for Windows on Linux fails.

### ISSUE THREAD

**Issue by JCash** [dotnet/runtime#107336]
### Description

When using DotNet under Docker (Linux), it complains about:
```
/tmp/.nuget/microsoft.dotnet.ilcompiler/9.0.0-preview.7.24405.7/build/Microsoft.NETCore.Native.Publish.targets(64,5): error : Cross-OS native compilation is not supported. [/tmp/job17054391463646726815/upload/encoder_cs/ExtensionCSharp_2.csproj]
```

I was under the impression that DotNet didn't use external tools to produce object files/libraries, but it seems I was wrong.

I have Clang available, as well as a copy of the Windows SDK in the linux container.
We've used those to build Win32/64 apps for many years.
Is it possible for me to set some flags or environment variables for DotNet to cross compile for Windows under Linux?

Regards,
Mathias

### Reproduction Steps

* Use Linux machine (e.g. Ubuntu under Docker)
* Try to build a static library for Windows, using Dotnet NativeAOT

### Expected behavior

That it can produce a native library for windows.

### Actual behavior

Build error.

**Comment by huoyaoyuan** [comment]
> I was under the impression that DotNet didn't use external tools to produce object files/libraries, but it seems I was wrong.

It uses the system linker (link.exe for Windows) to produce the result dll/exe/lib file. See https://github.com/dotnet/runtime/issues/99152#issuecomment-1975837472 .

> Is it possible for me to set some flags or environment variables for DotNet to cross compile for Windows under Linux?

There's no direct support to use an alternative linker. You may try to replicate the logic in `Microsoft.NETCore.Native.Publish.targets`, and change the way invoking linker. This workaround is unsupported.

**Comment by MichalStrehovsky** [comment]
The environment needs to provide a Windows SDK, working link.exe on PATH and Visual C++ runtime libraries (static), since the GC etc were all compiled using Visual C++ and expect the Visual C++ runtime library (**not clang**).

On the technical side, you'd set `DisableUnsupportedError` property to true (to turn off the error), set `IlcUseEnvironmentalTools` property to true (to stop attempting to locate Visual Studio installation) and provide a working link.exe on the path with LIBPATH set to correct directories.

The properties are not documented so you're stepping out of what's supported. It may be possible to do this, it may not. The dependencies on Visual C++ CRT will likely be a problem since this only ships with Visual Studio.

**Comment by MichalStrehovsky** [comment]
> Note that I'm not looking to "link" anything really, but to generate a .lib file using the NativeAOT. I don't need nor want the .dll file.
Is there a way to avoid generating the .dll file?

NativeLib=static will avoid link.exe and generating the dll. You do need lib however.

**Comment by JCash** [comment]
Thanks. I already do use `<NativeLib>static</NativeLib>` (full [csproj](https://github.com/defold/extender/blob/dev/server/docker-base/template.csproj)) as I'm building static libraries for the different platforms. (I need to double check the error message, perhaps it's not trying to generate the .dll)

Still, for the library, I'm not sure what I need to do here.
I have Wine and lib.exe, but how to make sure that DotNet actually invokes that?
I think build configurability is important when it comes to cross compiling.

**Comment by MichalStrehovsky** [comment]
With `IlcUseEnvironmentalTools=true`, this should just invoke `lib`. You could add a shim `lib` that invokes lib.exe under Wine.
