### ISSUE TITLE
Use transitive reference packages instead of explicit reference packages.

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#107439]
I’ve noticed there’s a lot of info in the library package reference list. Let me use [one of the packages](https://www.nuget.org/packages/Microsoft.Extensions.Hosting/9.0.0-preview.7.24405.7#dependencies-body-tab) as an example. Could we simplify the reference list by using transitive references instead of explicit ones? Originally, we needed 22 explicit packages, but with transitive references, we only need 11, which is a 50% reduction.

### explicit references

![image](https://github.com/user-attachments/assets/e620b86e-2563-4197-9e13-c696de0ab699)

### transitive references

![image](https://github.com/user-attachments/assets/5ee06b63-b906-43ee-9bdd-9c2a9091edaa)

**Comment by ericstj** [comment]
This is by design.  We use all of these dependencies, and this representation is equivalent.  NuGet will actually perform better if listing the transitive closure since it sees the dependency before downloading the next package.  We won't be changing this.

**Comment by ericstj** [comment]
It doesn't hurt anything to have the references nor does it burden users.  I shared one benefit of listing the closure of references.  Another benefit (though not applicable _here_ since we own everything) is that it insulates you from breaking changes of a dependency - you can guarantee all the references of your library are present even if a future version of the dependency might remove one.

The changes you made are not "wrong" - it's just there's no absolute better or worse here and there are reasons for having it the way it is.

> Hope you guys can rethink this.

Happy to rethink if you can phrase this in terms of a bug or a real negative impact you see today.  Right not it looks to me like this is in a style / preference and I've described why we might have a different preference.
