### ISSUE TITLE
JsonSchemaExporter.GetJsonSchemaAsNode "format" output cannot be controlled by configuration

### ISSUE THREAD

**Issue by mas-sdb** [dotnet/runtime#107501]
### Description

- For numeric types, a regular expression is output using the "pattern" key, but this can be suppressed by setting JsonSerializerOptions.NumberHandling to JsonNumberHandling.Strict.
- For date and time types, the value format is output using the "format" key.However, the format output is hard-coded and cannot be suppressed by configuration.
I have confirmed similar implementations with DateOnly, DateTime, DateTimeOffset, TimeOnly, and Guid.

https://github.com/dotnet/runtime/blob/v9.0.0-preview.7.24405.7/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/DateOnlyConverter.cs#L82

Similar to controlling the output of the "pattern" key through JsonSerializerOptions.NumberHandling, I believe JsonSchemaExporterOptions (which I think is more appropriate than JsonSerializerOptions) should have a configuration that allows you to change the "format" key output as needed.

```csharp
var options = new JsonSchemaExporterOptions
{
	ValueFormatHandling = JsonValueFormatHandling.None, // or Always
};
```

### Reproduction Steps

Uses System.Text.Json 9.0.0-preview.7.24405.7.
Run the following code:

```csharp
var serializerOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web)
{
	NumberHandling = JsonNumberHandling.Strict,
	PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
	RespectNullableAnnotations = true,
	TypeInfoResolver = new DefaultJsonTypeInfoResolver(),
	WriteIndented = true
};

var exporterOptions = new JsonSchemaExporterOptions
{
	TreatNullObliviousAsNonNullable = true,
};

var schema = serializerOptions.GetJsonSchemaAsNode(typeof(TestModel), exporterOptions);
Console.WriteLine(schema.ToJsonString(serializerOptions));

public class TestModel
{
	public required DateOnly DateOnlyRequiredNotNull { get; set; }
	public required TimeOnly? TimeOnlyRequiredAllowNull { get; set; }
	public required DateTime DateTimeRequiredNotNull { get; set; }
	public required DateTimeOffset? DateTimeOffsetRequiredAllowNull { get; set; }
	public required Guid GuidRequiredNotNull { get; set; }
}
```

### Expected behavior

```json
{
  "type": "object",
  "properties": {
    "date_only_required_not_null": {
      "type": "string"
    },
    "time_only_required_allow_null": {
      "type": [
        "string",
        "null"
      ]
    },
    "date_time_required_not_null": {
      "type": "string"
    },
    "date_time_offset_required_allow_null": {
      "type": [
        "string",
        "null"
      ]
    },
    "guid_required_not_null": {
      "type": "string"
    }
  },
  "required": [
    "date_only_required_not_null",
    "time_only_required_allow_null",
    "date_time_required_not_null",
    "date_time_offset_required_allow_null",
    "guid_required_not_null"
  ]
}
```

### Actual behavior

"format" is generated for each property, but it cannot be suppressed in the configuration.

```json
{
  "type": "object",
  "properties": {
    "date_only_required_not_null": {
      "type": "string",
      "format": "date"
    },
    "time_only_required_allow_null": {
      "type": [
        "string",
        "null"
      ],
      "format": "time"
    },
    "date_time_required_not_null": {
      "type": "string",
      "format": "date-time"
    },
    "date_time_offset_required_allow_null": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "guid_required_not_null": {
      "type": "string",
      "format": "uuid"
    }
  },
  "required": [
    "date_only_required_not_null",
    "time_only_required_allow_null",
    "date_time_required_not_null",
    "date_time_offset_required_allow_null",
    "guid_required_not_null"
  ]
}
```

### Known Workarounds

Of course, I know I can change the generated JSON Schema by setting methods on JsonSchemaExporterOptions.TransformSchemaNode.
In fact, I generated the Expected schema with the code below.

```csharp
Console.WriteLine(OpenAIStructuredOutputs.CreateJsonSchema<TestModel>());

public static class OpenAIStructuredOutputs
{
	private static readonly JsonSerializerOptions s_serializerOptions = new(JsonSerializerDefaults.Web)
	{
#if DEBUG
		WriteIndented = true,
#endif
		NumberHandling = JsonNumberHandling.Strict,
		PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
		RespectNullableAnnotations = true,
		TypeInfoResolver = new DefaultJsonTypeInfoResolver()
	};

	private static readonly JsonSchemaExporterOptions s_exporterOptions = new()
	{
		TreatNullObliviousAsNonNullable = true,
		TransformSchemaNode = OnTransformSchemaNode
	};

	public static string CreateJsonSchema<T>()
	{
		var schema = s_serializerOptions.GetJsonSchemaAsNode(typeof(T), s_exporterOptions);
		return schema.ToJsonString(s_serializerOptions);
	}

	private static JsonNode OnTransformSchemaNode(JsonSchemaExporterContext context, JsonNode node)
	{
		if(context.TypeInfo.Kind != JsonTypeInfoKind.Object)
		{
			return node;
		}

		var current = node.AsObject();

		// It would be useful to have an option to always output "additionalProperties".
		if(!current.TryGetPropertyValue("additionalProperties", out _))
		{
			current.Add("additionalProperties", false);
		}

		// Search inside "properties" and delete the "format" key if it exists.
		if(current.TryGetPropertyValue("properties", out var properties))
		{
			if(properties is JsonObject propertiesObject)
			{
				for(int i = 0; i < propertiesObject.Count; i++)
				{
					if(propertiesObject[i] is not JsonObject property)
					{
						continue;
					}

					if(property.TryGetPropertyValue("format", out _))
					{
						property.Remove("format");
					}
				}
			}
		}

		return current;
	}
}

public class TestModel
{
	public required DateOnly DateOnlyRequiredNotNull { get; set; }
	public required TimeOnly? TimeOnlyRequiredAllowNull { get; set; }
	public required DateTime DateTimeRequiredNotNull { get; set; }
	public required DateTimeOffset? DateTimeOffsetRequiredAllowNull { get; set; }
	public required Guid GuidRequiredNotNull { get; set; }
}
```

I would like to generate a JSON schema to be passed to the Structured Outputs of OpenAI GPT-4o (2024-08-06) using GetJsonSchemaAsNode.

There are some restrictions on the JSON schema that GPT-4o accepts.
- "pattern" and "format" cannot be specified
- "required" is required for all fields
- "additionalProperties" must be set to false for all objects
etc.

I think the same problem will arise in the semantic kernel.
Therefore, property generation control should be as configurable as possible.

**Comment by gregsdennis** [comment]
(Just giving some JSON Schema context here.  I have no comment on the generator implementation.)

It's important to note (explicitly, because [people generally get this wrong](https://github.com/json-schema-org/json-schema-spec/issues/1520)) that `format` doesn't validate unless the tool has been explicitly configured to do so.  It's informational only.

The spec says that a `date-time` format should inform the user to expect an RFC3339 date/time.  But .Net uses the ISO8601 date/time format.  Within that context, and since there's no validation of the format, it _could_ be understood by a .Net consumer that the format should be ISO8601.

If the schema is going to be shared outside of a .Net ecosystem, then perhaps the RFC3339 requirement should be considered more carefully.

It's also allowable to create your own formats so long as consumers can be made to understand it.  So you could create an `iso8601` format (or whatever you want to name it).

---

> For numeric types, a regular expression is output using the "pattern" key

I assume this is only for cases where a number is string-encoded?  (I think encoding numbers as strings is a [bad practice](https://blog.json-everything.net/posts/numbers-are-numbers-not-strings/) and is perpetuated only because parsers generally don't support numbers well.)  `pattern` is only applied to string instances and won't affect numbers.  Furthermore, _no_ keyword can be applied to the JSON-encoding itself.  JSON Schema operates on the JSON _data model_ not on the JSON text itself.

**Comment by eiriktsarpalis** [comment]
Configuring the schema of individual types is something that isn't supported for the moment (primarily because we don't yet have a publicly accessible `JsonSchema` exchange type that something like a custom converter could try to configure). Right now, the only available mechanism for applying customizations is the post-hoc `TransformSchemaNode` delegate that you've already discovered.

The reason why you're seeing the `pattern` keyword in cases where `JsonNumberHandling.AllowReadingFromString` is because generator is producing schemas that are specifying the behavior of `JsonSerializer`. In other words, an instance should be valid under the schema _if and only if_ it is accepted as input by the `JsonSerializer.Deserialize` methods for the same type. It is understandable that your application might require a schema document that is a stricter subset of what the deserializer accepts, and it should be possible to make such refinements with the transformer delegate as an interim solution.

> There are some restrictions on the JSON schema that GPT-4o accepts.
> 
> * "pattern" and "format" cannot be specified
> * "required" is required for all fields
> * "additionalProperties" must be set to false for all objects
>
> etc.

To an extent it should be possible to influence your output by appropriately modelling your types directly:

* The `pattern` keyword can be avoided in all configurations by setting a `JsonNumberHandlingAttribute` on the type level.
* You can mark all your properties as `required` to influence the relevant keyword. Alternatively you could try using a deserialization constructor and then enable the `JsonSerializerOptions.RespectRequiredConstructorParameters` flag that has been added in .NET 9.
* `additionalProperties: false` is added to all types if you have the `JsonSerializerOptions.UnmappedMemberHandling` property set to `JsonUnmappedMemberHandling.Disallow`.

**Comment by eiriktsarpalis** [comment]
> Outside the ecosystem, the "format" keyword is an annotation by default and has no effect on actual validation.
> Therefore, the definition of "format" is an inside .NET implementation issue.

I don't follow this reasoning. Why does `format` not being validated by default imply that `format` is a .NET implementation detail? That's not true at all.

> The current behavior is fine as the default within the .NET ecosystem, but it should have an option in the configuration to not output "format" for outside the .NET ecosystem.

I still don't understand. The schema being generated is a valid JSON schema document that specifies the particular `JsonSerializerOptions` it has been passed. There is nothing .NET specific about the `format` keyword. The only issue I'm seeing is that Open AI impose restrictions in what schema documents their APIs accept. This is expected, and different vendors have different metaschematization requirements which is why we added `TransformSchemaNode`.

> Good news! But the additionalProperties isn't output, am I doing something wrong?

I think you might have hit an actual bug where the global setting is being ignored. Try adding it as an attribute annotation instead:

```C#
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
```

**Comment by eiriktsarpalis** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/105769
