### ISSUE TITLE
Single File Application Slow on osx-x64 runtime

### ISSUE THREAD

**Issue by thomhurst** [dotnet/runtime#107674]
I've done a benchmark of my library on linux-x64, win-x64 and osx-x64.

The benchmark can be seen here: https://github.com/thomhurst/TUnit/actions/runs/10793509810

As you can see, on Linux and Windows, the SingleFile benchmark is quicker than just invoking `dotnet run` (the line below it called just `TUnit`.)

However, on osx-x64, the SingleFile is substantially longer. Is this expected?

## osx-x64
TUnit_SingleFile | 1,106.13 ms | 21.857 ms | 50.657 ms | 1,099.29 ms
-- | -- | -- | -- | --
TUnit | 421.69 ms | 6.459 ms | 5.725 ms | 422.10 ms

## linux-x64
TUnit_SingleFile | 435.83 ms | 4.463 ms | 3.956 ms
-- | -- | -- | --
TUnit | 826.54 ms | 16.493 ms | 39.517 ms

## win-x64
TUnit_SingleFile | 407.13 ms | 4.578 ms | 3.823 ms
-- | -- | -- | --
TUnit | 759.65 ms | 14.855 ms | 20.333 ms
</html>

**Comment by vitek-karas** [comment]
Comparing executable to `dotnet run` is not a fair comparison. `dotnet run` invokes the build system which in the best case will have to check that everything is up-to date and then it runs the application. Running the single-file directly doesn't do any of that, it just runs the app. If you want to measure single-file impact, you should compare running the executable produced by `dotnet publish /p:PublishSingleFile=true` and `dotnet publish /p:PublishSingleFile=false`.

It's also a good idea to not measure the first execution of an executable on a system. Both Windows and Mac will run a new executable through security checks (AV scanning sometimes, and other types of checks) which will introduce lot of noise into the results.

Similarly, if your single-file uses auto-extraction (`IncludeNativeLibrariesForSelfExtract` or `IncludeAllContentForSelfExtract`) the specific behavior of the OS can influence the time (again due to AV or similar scanning).

**Comment by thomhurst** [comment]
> Comparing executable to dotnet run is not a fair comparison. dotnet run invokes the build system which in the best case will have to check that everything is up-to date and then it runs the application. Running the single-file directly doesn't do any of that, it just runs the app

By that logic the single file app should be quicker then? But on osx-x64 it's slower than dotnet run.

> It's also a good idea to not measure the first execution of an executable on a system. 
I'm using BenchmarkDotNet which does warm ups, so it shouldn't take those warm ups into account in the benchmarks.

> Both Windows and Mac will run a new executable through security checks (AV scanning sometimes, and other types of checks) which will introduce lot of noise into the results.
Is this just on the first execution though? Because again the warm ups would have sorted that. All subsequent executions take just as long.

**Comment by vitek-karas** [comment]
I don't have an explanation for the behavior you see. We would need to try to reproduce the behavior and profile it.
What does your test measure exactly? The duration of running a process which does some work?

**Comment by thomhurst** [comment]
> I don't have an explanation for the behavior you see. We would need to try to reproduce the behavior and profile it. What does your test measure exactly? The duration of running a process which does some work?

Yeah it measures invoking the executable, which runs a test using a library I've built (similar to NUnit/xUnit), and then shuts down

**Comment by thomhurst** [comment]
I'll see if I can reproduce in a minimal console app or something
