### ISSUE TITLE
[Breaking change]: New TimeSpan.From overloads which take integers

### ISSUE THREAD

**Issue by rstm-sf** [dotnet/runtime#107895]
### Description

https://github.com/dotnet/runtime/pull/98633

### Version

.NET 9 RC 1

### Previous behavior

Before .NET 9 there was a version with one float parameter

### New behavior

Now the following F# code throws an overload error: `TimeSpan.FromMinutes(20)`

> error FS0041: A unique overload for method 'FromMinutes' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: intCandidates: - TimeSpan.FromMinutes(minutes: int64) : TimeSpan - TimeSpan.FromMinutes(minutes: int64, ?seconds: int64, ?milliseconds: int64, ?microseconds: int64) : TimeSpan - TimeSpan.FromMinutes(value: float) : TimeSpan

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries might encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [X] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code might require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries might behave differently at run time.

### Reason for change

https://github.com/dotnet/runtime/issues/93890

### Recommended action

Specify the compiler what type of argument is being used so that the appropriate overload is selected

### Feature area

Core .NET libraries

**Comment by terrajobst** [comment]
@rstm-sf

> When a new API is designed, does it take into account that `.NET <> C#`?

We generally do consider other languages when designing APIs but we don't always remember all the specifics under which a change can become a source breaking change. As soon as overloads are concerned you can almost always find examples where existing code no longer compiles due to ambiguities, which isn't just the case for F#.

In order to prevent the problem you're describing here we'd have to have a rule that says "don't create overloads between numeric types when previously no such overload existed". I don't think we want to sign up for that because it basically forces us to either not add features or invent new method groups. Neither of which seems appealing to me.

For this particular API: I don't recall why we added the ones taking a single `long`. Initially I thought it was as a tie breaker to prevent `FromHours(12)` to be ambiguous between the existing one and the new one with defaults. We just did to follow our standard rules to have a simple one; which is already the case, it seems we did this follow our regular "have a simple overload without defaults", not realizing that we already had one.

@tannergooding @bartonjs: ignoring the RC1 but bar for a moment, would it be possible to just remove these methods?

```diff
 namespace System;
 
 public partial struct TimeSpan
 {
 	 // Exists prior to .NET 9
     public static TimeSpan FromDays(double days);
     public static TimeSpan FromHours(double hours);
     public static TimeSpan FromMinutes(double minutes);
     public static TimeSpan FromSeconds(double seconds);
     public static TimeSpan FromMicroseconds(double microseconds);

 	 // New in .NET 9
-    public static TimeSpan FromDays(int days);
     public static TimeSpan FromDays(int days, int hours = 0, long minutes = 0, long seconds = 0, long milliseconds = 0, long  microseconds = 0);
-    public static TimeSpan FromHours(int hours);
     public static TimeSpan FromHours(int hours, long minutes = 0, long seconds = 0, long milliseconds = 0, long microseconds = 0);
-    public static TimeSpan FromMinutes(long minutes);
     public static TimeSpan FromMinutes(long minutes, long seconds = 0, long milliseconds = 0, long microseconds = 0);
-    public static TimeSpan FromSeconds(long seconds);
     public static TimeSpan FromSeconds(long seconds, long milliseconds = 0, long microseconds = 0);
-    public static TimeSpan FromMicroseconds(long microseconds);
     public static TimeSpan FromMilliseconds(long milliseconds, long microseconds = 0);
 }
```

**Comment by terrajobst** [comment]
> FWIW, if I recall correctly, we just (like 5 minutes before your comment) switched from the RC bug bar to the RTM bug bar (any changes now would be changes between RC2 and RTM)... so "un-ignoring" that is slightly more costly than you were considering 😄

I was mostly concerned with "is this even feasible", mostly for my own education. If it's not, I'm not even attempting to see which approvals we'd need :-)

Sounds like "yes we could remove them but we probably don't want to due to perf and even if we did, it won't fix all possible source breaking concerns". Plus, the bar is pretty high now. Therefore I'm going to close as won't fix.

**Comment by bartonjs** [comment]
>  Therefore I'm going to close as won't fix.

Since this got opened in dotnet/docs, I think the filer just wants us to doc it as a source breaking change for F#, which seems valid...
