### ISSUE TITLE
Performance regression with JsonObject creation by +70%

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#107869]
### Description

I have a number of .NET applications I maintain, which I've also recently started maintaining some basic continuous benchmarks for. A number of these applications include an endpoints that's used as a health check for deployment/debugging and is implemented something like this:

```csharp
        app.MapGet("/version", static () =>
        {
            return new JsonObject()
            {
                ["applicationVersion"] = GitMetadata.Version,
                ["frameworkDescription"] = RuntimeInformation.FrameworkDescription,
                ["operatingSystem"] = new JsonObject()
                {
                    ["description"] = RuntimeInformation.OSDescription,
                    ["architecture"] = RuntimeInformation.OSArchitecture.ToString(),
                    ["version"] = Environment.OSVersion.VersionString,
                    ["is64Bit"] = Environment.Is64BitOperatingSystem,
                },
                ["process"] = new JsonObject()
                {
                    ["architecture"] = RuntimeInformation.ProcessArchitecture.ToString(),
                    ["is64BitProcess"] = Environment.Is64BitProcess,
                    ["isNativeAoT"] = !RuntimeFeature.IsDynamicCodeSupported,
                    ["isPrivilegedProcess"] = Environment.IsPrivilegedProcess,
                },
                ["dotnetVersions"] = new JsonObject()
                {
                    ["runtime"] = GetVersion<object>(),
                    ["aspNetCore"] = GetVersion<HttpContext>(),
                },
            };

            static string GetVersion<T>()
                => typeof(T).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion;
        });
```

As it's fairly trivial (e.g. has no external dependencies) I've been including it in the benchmarks as a sort of "canary" as a proxy for the overall performance of ASP.NET Core, JSON, the runtime etc.

I've over the last week updated a number of applications from .NET 8 to .NET 9 RC1 and was surprised to find that I'm consistently seeing a regression from this endpoint in terms of the memory allocated compared to .NET 8.

Below is an example chart from my tracking dashboard. The point at which the memory goes up and the duration goes down is the commit that applied the .NET 9 upgrade:

![image](https://github.com/user-attachments/assets/b936d4ce-aaac-48a1-bd73-d02ef9de16e9)

I've pulled this out into its own dedicated benchmark that just creates the `JsonObject`, and I see the same regression in terms of memory usage (and also duration). I've made an assumption here that the regression is in `JsonObject` as the properties being serialized are ones I would have thought wouldn't changed during the lifetime of a process and thus be cached.

Admittedly this isn't a critical path in terms of performance, but as it went backwards against what I would have thought the trend would be for the upgrade, and that it was noticeable, I figured I'd raise an issue so that if it's not an expected trade-off somewhere it can be fixed.

These are the results I get on my laptop for the simplified benchmark:

```

BenchmarkDotNet v0.14.0, Windows 11 (10.0.22621.4169/22H2/2022Update/SunValley2)
12th Gen Intel Core i7-1270P, 1 CPU, 16 logical and 12 physical cores
.NET SDK 9.0.100-rc.1.24452.12
  [Host]     : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX2
  Job-WBWTQA : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX2
  Job-MBMPCJ : .NET 9.0.0 (9.0.24.43107), X64 RyuJIT AVX2


```
| Method           | Runtime  | Mean     | Error    | StdDev   | Median   | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|----------------- |--------- |---------:|---------:|---------:|---------:|------:|--------:|-------:|----------:|------------:|
| CreateJsonObject | .NET 8.0 | 400.3 ns |  8.02 ns | 20.71 ns | 391.1 ns |  1.00 |    0.07 | 0.0067 |   1.24 KB |        1.00 |
| CreateJsonObject | .NET 9.0 | 769.2 ns | 14.13 ns | 19.35 ns | 771.6 ns |  1.93 |    0.11 | 0.0572 |   2.12 KB |        1.70 |

Compared to my higher-level benchmarks, it also appears to be slower than .NET 8 as well - I think it's masked there as there's much more going on and improvements elsewhere outweigh the increase in the runtime to create the object.

### Reproduction Steps

```console
dotnet run -c Release -f net8.0 -- --runtimes net8.0 net9.0
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>
</Project>
```

```csharp
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text.Json.Nodes;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Diagnosers;

BenchmarkRunner.Run<JsonNodeBenchmarks>(args: args);

[MemoryDiagnoser]
public class JsonNodeBenchmarks
{
    [Benchmark]
    public JsonObject CreateJsonObject()
    {
        return new JsonObject()
        {
            ["applicationVersion"] = "1.2.3",
            ["frameworkDescription"] = RuntimeInformation.FrameworkDescription,
            ["operatingSystem"] = new JsonObject()
            {
                ["description"] = RuntimeInformation.OSDescription,
                ["architecture"] = RuntimeInformation.OSArchitecture.ToString(),
                ["version"] = Environment.OSVersion.VersionString,
                ["is64Bit"] = Environment.Is64BitOperatingSystem,
            },
            ["process"] = new JsonObject()
            {
                ["architecture"] = RuntimeInformation.ProcessArchitecture.ToString(),
                ["is64BitProcess"] = Environment.Is64BitProcess,
                ["isNativeAoT"] = !RuntimeFeature.IsDynamicCodeSupported,
                ["isPrivilegedProcess"] = Environment.IsPrivilegedProcess,
            },
        };
    }
}
```

### Expected behavior

Performance using .NET 9 is on par, or better, with .NET 8.

### Actual behavior

Duration and memory allocations are greater running under .NET 9, by ~+80% for duration and ~+70% for allocations.

### Regression?

Yes.

### Known Workarounds

None.

### Configuration

.NET SDK 9.0.100-rc.1.24452.12.

**Comment by EgorBo** [comment]
@EgorBot -intel --runtimes net8.0 net9.0
```cs
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text.Json.Nodes;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Diagnosers;

BenchmarkRunner.Run<JsonNodeBenchmarks>(args: args);

[MemoryDiagnoser]
public class JsonNodeBenchmarks
{
    [Benchmark]
    public JsonObject CreateJsonObject()
    {
        return new JsonObject()
        {
            ["applicationVersion"] = "1.2.3",
            ["frameworkDescription"] = RuntimeInformation.FrameworkDescription,
            ["operatingSystem"] = new JsonObject()
            {
                ["description"] = RuntimeInformation.OSDescription,
                ["architecture"] = RuntimeInformation.OSArchitecture.ToString(),
                ["version"] = Environment.OSVersion.VersionString,
                ["is64Bit"] = Environment.Is64BitOperatingSystem,
            },
            ["process"] = new JsonObject()
            {
                ["architecture"] = RuntimeInformation.ProcessArchitecture.ToString(),
                ["is64BitProcess"] = Environment.Is64BitProcess,
                ["isNativeAoT"] = !RuntimeFeature.IsDynamicCodeSupported,
                ["isPrivilegedProcess"] = Environment.IsPrivilegedProcess,
            },
        };
    }
}
```

**Comment by EgorBo** [comment]
Ouch, indeed [a big difference](https://github.com/EgorBot/runtime-utils/issues/90#issuecomment-2353145811)

**Comment by eiriktsarpalis** [comment]
I'll investigate what might be causing this -- the key change that happened to `JsonObject` in .NET 9 was replacing its bespoke implementation with the new `System.Collections.Generic.OrderedDictionary` collection so it might be that it has different performance characteristics.

**Comment by eiriktsarpalis** [comment]
I suspect this might be caused by the fact that the original collection applies a performance optimization, using `List<T>` for objects containing 9 properties or fewer:

https://github.com/dotnet/runtime/blob/cb77171f85a1431e67525922a53621d7475c5ebd/src/libraries/System.Text.Json/src/System/Text/Json/JsonPropertyDictionary.cs#L16-L19

OTOH `OrderedDictionary` will always perform a hashtable insertion, including hashcode generation for all property names:

https://github.com/dotnet/runtime/blob/17c83a608925e39d7d454e27c2e0cbcaf7c4ae2d/src/libraries/System.Collections/src/System/Collections/Generic/OrderedDictionary.cs#L473-L483

**Comment by eiriktsarpalis** [comment]
@martincostello what happens if you update you benchmark an object with 10+ properties?

**Comment by eiriktsarpalis** [comment]
I've created [a new benchmark suite](https://github.com/dotnet/performance/pull/4463) for constructing JsonNode instances that attempts to isolate the individual node types. On my machine results look as follows:

| Method                  | Runtime  | Mean       | Error     | StdDev    | Median     | Min        | Max        | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------------------------ |--------- |-----------:|----------:|----------:|-----------:|-----------:|-----------:|------:|--------:|-------:|----------:|------------:|
| Create_JsonBool         | .NET 8.0 |   4.061 ns | 0.0762 ns | 0.0675 ns |   4.047 ns |   3.975 ns |   4.233 ns |  1.00 |    0.02 | 0.0115 |      48 B |        1.00 |
| Create_JsonBool         | .NET 9.0 |   4.435 ns | 0.3098 ns | 0.3444 ns |   4.322 ns |   4.117 ns |   5.342 ns |  1.09 |    0.08 | 0.0134 |      56 B |        1.17 |
|                         |          |            |           |           |            |            |            |       |         |        |           |             |
| Create_JsonNumber       | .NET 8.0 |   4.000 ns | 0.0496 ns | 0.0440 ns |   4.005 ns |   3.924 ns |   4.069 ns |  1.00 |    0.02 | 0.0115 |      48 B |        1.00 |
| Create_JsonNumber       | .NET 9.0 |   4.392 ns | 0.1816 ns | 0.2091 ns |   4.330 ns |   4.124 ns |   4.785 ns |  1.10 |    0.05 | 0.0134 |      56 B |        1.17 |
|                         |          |            |           |           |            |            |            |       |         |        |           |             |
| Create_JsonString       | .NET 8.0 |   4.250 ns | 0.1543 ns | 0.1585 ns |   4.194 ns |   4.030 ns |   4.578 ns |  1.00 |    0.05 | 0.0115 |      48 B |        1.00 |
| Create_JsonString       | .NET 9.0 |   4.650 ns | 0.4415 ns | 0.5085 ns |   4.542 ns |   4.137 ns |   6.040 ns |  1.10 |    0.12 | 0.0134 |      56 B |        1.17 |
|                         |          |            |           |           |            |            |            |       |         |        |           |             |
| Create_JsonArray        | .NET 8.0 |  21.888 ns | 0.2187 ns | 0.2046 ns |  21.900 ns |  21.544 ns |  22.355 ns |  1.00 |    0.01 | 0.0363 |     152 B |        1.00 |
| Create_JsonArray        | .NET 9.0 |  20.970 ns | 0.2579 ns | 0.2154 ns |  20.921 ns |  20.633 ns |  21.455 ns |  0.96 |    0.01 | 0.0363 |     152 B |        1.00 |
|                         |          |            |           |           |            |            |            |       |         |        |           |             |
| Create_JsonObject_Small | .NET 8.0 | 237.503 ns | 1.9982 ns | 1.6686 ns | 237.223 ns | 234.792 ns | 241.300 ns |  1.00 |    0.01 | 0.1624 |     680 B |        1.00 |
| Create_JsonObject_Small | .NET 9.0 | 252.162 ns | 1.6015 ns | 1.4197 ns | 252.466 ns | 249.266 ns | 254.602 ns |  1.06 |    0.01 | 0.2506 |    1048 B |        1.54 |
|                         |          |            |           |           |            |            |            |       |         |        |           |             |
| Create_JsonObject_Large | .NET 8.0 | 645.532 ns | 4.8418 ns | 4.2921 ns | 645.654 ns | 639.515 ns | 651.598 ns |  1.00 |    0.01 | 0.5620 |    2352 B |        1.00 |
| Create_JsonObject_Large | .NET 9.0 | 528.392 ns | 7.7646 ns | 6.8831 ns | 527.716 ns | 518.750 ns | 542.004 ns |  0.82 |    0.01 | 0.5088 |    2136 B |        0.91 |

The reported regression is the product of two separate factors:

1. While creating a new `JsonObject` containing 9 elements or fewer does introduce a slight performance regression, in isolation it isn't particularly substantial. For objects containing more than 9 elements .NET 9 actually records improvements, which is in line with the expected behavior of the new `OrderedDictionary` collection when compared with the original bespoke `JsonPropertyDictionary<T>` type. I don't believe we need to address this regression.
2. Primitive JSON values record a performance regression which is directly attributable to [this change](https://github.com/dotnet/runtime/pull/103733/files#diff-5b29ac85ac7f4d846ab1b6a87ab9cb361cc9965f5d784ffa143699baf12a5ceaR24). I'll post a PR that addresses the issue.

**Comment by martincostello** [comment]
@eiriktsarpalis Do you still need to me to re-run my benchmarks, or do you have a handle on this now that makes it unnecessary? My laptop's had issues since yesterday evening so I haven't been back to a state where I can re-run them yet (though should be resolved in a few hours).
