### ISSUE TITLE
Unable to load library published with PublishAot

### ISSUE THREAD

**Issue by MaxwellDAssistek** [dotnet/runtime#107971]
### Description

I am trying to dynamically load a module library that has been published with PublishAot set to true, but I get an exception.

### Reproduction Steps

1. Make a .NET 8 library project.
2. Set the PublishAot property to True,
3. Set TrimMode to partial.
4. Add the ILLink embedded resource
```
    <EmbeddedResource Include="ILLink.Descriptors.xml">
      <LogicalName>ILLink.Descriptors.xml</LogicalName>
    </EmbeddedResource>
```
5. Add a basic config to just disable trimming on the whole library.
```
<linker>
  <assembly fullname="MyLibrary" preserve="all" />
</linker>
```
6. Make a sample class with a function to expose.
7. Publish the project to a specific platform like `dotnet publish -f net8.0-windows -r win-x64 `
6. Now from another application, use `Assembly.Load` to attempt to load the resulting DLL.

### Expected behavior

DLL is loaded and untrimmed functions are available using reflection techniques.

### Actual behavior

```
System.BadImageFormatException: Bad IL format. The format of the file 'C:\path\to\MyLibrary.dll' is invalid.
```

### Regression?

No

### Configuration

.NET 8
Windows x64

**Comment by huoyaoyuan** [comment]
The output of NativeAOT is a native dll, not a managed assembly. You can load it with `NativeLibrary.Load` instead of `Assembly.Load`.

**Comment by MichalStrehovsky** [comment]
What @huoyaoyuan said - this is a native DLL now. What are you trying to achieve?

**Comment by MaxwellDAssistek** [comment]
@MichalStrehovsky
> What @huoyaoyuan said - this is a native DLL now. What are you trying to achieve?

I am trying to have these library modules be optimized ahead of time as much as possible, but still remain "managed", to allow them to be dynamically loaded in an interpretor-only host environment.

Is there a way for AOT to result in a managed DLL?

**Comment by MichalStrehovsky** [comment]
PublishAot optimizes results "as much as possible" and this includes optimizing the runtime itself. The runtime in a library compiled with PublishAot is no longer compatible with any other managed runtime. It can only be looked at as unmanaged code. You can p/invoke into it from a different managed application, but that's about it.

If you want AOT, you need to AOT the entire application. Otherwise you need to use the interpreter for the entire application. The only middle ground is the p/invoke solution but that one has other challenges (especially in defining the interface, since you cannot pass managed objects across the boundary, only unmanaged memory).

**Comment by MaxwellDAssistek** [comment]
In that case, we will probably have to stick with the interpreter. Is there any other optimizations that can be enabled at compile time to compensate for the lack of JIT? If using just the interpreter, would "Tier 0" optimizations even be applied?

**Comment by huoyaoyuan** [comment]
Which interpreter are you using? The coreclr interpreter is not maintained and only functional for basic scenarios. The mono interpreter may not be compatible with coreclr specific formats.

ReadyToRun is a theoretically possible solution. However I'm not sure whether the interpreter is compatible with it.

**Comment by MichalStrehovsky** [comment]
Which interpreter is this in reference to? The repro steps above say `dotnet publish -f net8.0-windows -r win-x64` but there's no interpreter on Windows.

**Comment by MaxwellDAssistek** [comment]
This would be intended for Mac targets. On Windows we have full JIT,so as you mentioned, this isn't relevant.

**Comment by MichalStrehovsky** [comment]
> This would be intended for Mac targets. On Windows we have full JIT,so as you mentioned, this isn't relevant.

I assume you mean iOS/Catalyst/etc. These default to AOT compilation (but not native AOT). Interpreter can optionally be enabled but it's not the default: https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0.

If you have more questions, I suggest opening a specific issue about the performance problem you're observing so that it can be routed to the correct people. Native AOT is not the correct area path and the set of folks who understand each of these technologies is different.
