### ISSUE TITLE
Results of sinh(−2 + 0i) and −sinh(2 + 0i) are not equal.

### ISSUE THREAD

**Issue by AntonovAnton** [dotnet/runtime#108196]
### Description

Hello!
The identity **sinh(−𝑧)=−sinh⁡(𝑧)** is a fundamental property of the hyperbolic sine function, it applies to both real and complex numbers. It reflects the oddness of the function.

I have noticed sinh(−2 + 0i)=−sinh(2 + 0i) is not true at the moment.
sinh(−2 + 0i) returns -3.6268604078470186
sinh(2 + 0i) returns 3.626860407847019
so -3.6268604078470186 are not equal -3.626860407847019

Could perhaps be solved by applying the trigonometry symmetry property of the hyperbolic sine function?

### Reproduction Steps

```
var value1 = Complex.Sinh(new Complex(2d, 0));
var value2 = -Complex.Sinh(-new Complex(2d, 0));
Console.WriteLine(Complex.Abs(value1 - value2) < double.Epsilon);
```

### Expected behavior

True

### Actual behavior

False

### Known Workarounds

1. Solving on user's side:
```
public static Complex Sinh(Complex z)
{
    //the Trigonometric Symmetry is applied: sinh(−z) = −sinh(z)
    if (Complex.IsNegative(z))
        return -Complex.Sinh(-z);

    return Complex.Sinh(z);
}
```
   
 

### Configuration

Windows 11 (10.0.22631.4169/23H2/2023Update/SunValley3)
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.400
.NET 8.0 : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

### Other information

I suggest bellow improvements for [System.Numerics.Complex](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Numerics/src/System/Numerics/Complex.cs): 
```
public static Complex Sinh(Complex value)
{
    if (double.IsNegative(value.m_real))
    {
        // Use sinh(z) = i sin(-iz) to compute via sin(z).
        Complex sin = Sin(new Complex(value.m_imaginary, -value.m_real));
        return new Complex(-sin.m_imaginary, sin.m_real);
    }
    else
    {
        // Use sinh(z) = -i sin(iz) to compute via sin(z).
        Complex sin = Sin(new Complex(-value.m_imaginary, value.m_real));
        return new Complex(sin.m_imaginary, -sin.m_real);
    }
}

``` 
Thanks!

**Comment by tannergooding** [comment]
This has already been fixed in .NET 9

The implementation of `Sinh` has always been: https://github.com/dotnet/runtime/blob/23b3d4199fd5fdf098ba41464e31d742e2977007/src/libraries/System.Runtime.Numerics/src/System/Numerics/Complex.cs#L387-L392

While the implementation of `Sin` was updated from:
https://github.com/dotnet/runtime/blob/aa280ad83632c2e79f8e6aa0d7a29e1911d39121/src/libraries/System.Runtime.Numerics/src/System/Numerics/Complex.cs#L415-L428

to instead be: https://github.com/dotnet/runtime/blob/23b3d4199fd5fdf098ba41464e31d742e2977007/src/libraries/System.Runtime.Numerics/src/System/Numerics/Complex.cs#L377-L385

This no longer relies on `Exp` and manual arithmetic, addition, and subtraction which allowed the parts to compound and impact the result in different ways based on the sign. Given that the old implementation been the behavior of `Complex` since its introduction and this is the only report, it likely doesn't meet the bar for backporting to .NET 8.

There are likely other cases where `Complex` has subtly "incorrect" implementations due to having been originally written with something that was "mathematically correct", but which did not take into account IEEE 754 semantics and imprecision.
