### ISSUE TITLE
ConfigurationBuilder: multiple JSON sources results in badly-handled top-level lists

### ISSUE THREAD

**Issue by tcbennun** [dotnet/runtime#108138]
### Description

I have two JSON configuration sources, one taking precedence over the other (e.g. the first giving defaults, the second giving overrides).

My config class has a top-level collection - any `IEnumerable<T>` will do.

When I write my JSON configs, I expect the array in the overriding file to be the basis of this collection. If the list is specified in the defaults file, I expect it to be ignored in the final collection.

Instead, let's say I have $N$ elements in the array in the defaults, and $M < N$ elements in the array in the overrides. I find that the final config class has a collection with $N$ elements, not $M$ as expected. The first $M$ elements come from the overrides, and the remainder from the defaults.

### Reproduction Steps

```.cs
using System.Text;

public static class App
{
    public class MyOptions
    {
        public IEnumerable<int>? IntList { get; set; }
    }

    public static void Main(string[] args)
    {
        var config = new ConfigurationBuilder()
            .AddJsonStream(new MemoryStream(Encoding.UTF8.GetBytes("{ \"IntList\": [1, 2, 3, 4] }")))
            .AddJsonStream(new MemoryStream(Encoding.UTF8.GetBytes("{ \"IntList\": [5, 6] }")))
            .Build();

        var intList = string.Join(", ", config.Get<MyOptions>()?.IntList ?? []);

        Console.WriteLine(intList);
    }
}
```

### Expected behavior

```
$ dotnet run
5, 6
```

### Actual behavior

```
$ dotnet run
5, 6, 3, 4
```

### Known Workarounds

I have no workarounds at the moment. I would really like one, because this is breaking an app I'm working on!

### Configuration

.NET 8.0.401 on macOS 15.0, arm64.

### Other information

After some reading about, it looks like elements of collections are treated as key-value pairs, with the key being the element index. This explains the behaviour. Is there any workaround I can use without rewriting the specs of my config files?

**Comment by tarekgh** [comment]
That's not how configuration binding works with collections. It was previously decided that when binding to a collection, new values will be appended rather than replacing the existing items. The breaking change documented [here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/7.0/config-bind-dictionary) for dictionaries also applies to collections.

To achieve your desired behavior, you'll need to handle the binding in two steps: first, bind to the default values, then clear the collection and bind again to the second set of configuration values. I am closing the issue but feel free to respond with any question if you still have any. Thanks!
