### ISSUE TITLE
Last() throws an exception when applied on a concatenation of a collection with two empty collections

### ISSUE THREAD

**Issue by AnnaVel** [dotnet/runtime#108477]
### Description

Hi, we've run into an issue with .NET 9, preview 2 onwards. If you have an enumerable with some elements and you concatenate it with other two enumerables which are empty the Last() method, applied to the result concatenation, throws an InvalidOperationException 'Sequence contains no elements'.

### Reproduction Steps

```csharp
IEnumerable<int> results = new List<int>() { 1, 2, 3 }.Concat(new List<int>()).Concat(new List<int>());

bool any = results.Any(); // true
int count = results.Count(); // 3
int last = results.Last(); // 'Sequence contains no elements.'
```

Same code in a project: https://github.com/AnnaVel/ConcatenatedLast

### Expected behavior

Last() should return 3.

### Actual behavior

Last() throws an exception.

### Regression?

Yes. This does not reproduce in .NET 9 preview 1, but reproduces in .NET 9 preview 2 and later.

### Known Workarounds

One could just use collection.ElementAt(collection.Count() - 1).

### Configuration

It is not likely this is a configuration-specific problem.

**Comment by andrewjsaid** [comment]
The reason for this bug is that in `Concat.SpeedOpt` we have loop through the tail using this

```
while ((node = node!.PreviousN) is not null)
```

https://github.com/dotnet/runtime/blob/0d863807580bae82225e5b7159c488a877530a74/src/libraries/System.Linq/src/System/Linq/Concat.SpeedOpt.cs#L338

Which is defined as
```
private ConcatNIterator<TSource>? PreviousN => _tail as ConcatNIterator<TSource>;
```
https://github.com/dotnet/runtime/blob/0d863807580bae82225e5b7159c488a877530a74/src/libraries/System.Linq/src/System/Linq/Concat.cs#L152

However the "base case" of the tail is a `Concat2Iterator`1` so `null` is returned and so the "base source" isn't inspected.
