### ISSUE TITLE
JIT: Assertion failed 'tree == stmt->GetRootNode()'

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#108406]
Failed in [Fuzzlyn](https://dev.azure.com/dnceng-public/public/_build?definitionId=149&_a=summary)/[20240929.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=821614)

```
- linux-arm64 checked
```

Repro:
```
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static int s_17;
    public static void Main()
    {
        var vr2 = (uint)ArmBase.ReverseElementBits(0);
        var vr3 = (ushort)s_17;
        bool vr4 = Crc32.ComputeCrc32(vr2, vr3) >= 1;
        bool vr5 = vr4;
        vr4 ^= true;
        if (vr4)
        {
            bool vr6 = default(bool);
            vr4 = vr6;
        }
        else
        {
            vr4 = !vr4;
        }

        System.Console.WriteLine(vr4);
        System.Console.WriteLine(vr5);
    }
}
```

Distinct assertion error:
```scala
JIT assert failed:
Assertion failed 'tree == stmt->GetRootNode()' in 'Program:M0()' during 'VN-based dead store removal' (IL size 776; hash 0xaf50ff37; FullOpts)

    File: /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp Line: 3597
```

**Comment by JulieLeeMSFT** [comment]
@amanasifkhalid, PTAL.
CC @dotnet/jit-contrib.

**Comment by amanasifkhalid** [comment]
In `Compiler::optRedundantRelop` during RBO, if we forward-substitute a statement without copying it, we remove the original statement after forward-subbing the relevant subtree. Here's the relevant snippet of code:
https://github.com/dotnet/runtime/blob/b3e8c3cff9601b07231c7dafb56ec37614160818/src/coreclr/jit/redundantbranchopts.cpp#L2162-L2176

For the above example, we forward-substitute from STMT00003 into STMT00004, so we start with this:
```
***** BB01 [0000]
STMT00003 ( 0x01C[E-] ... 0x020 )
N004 (  6,  4) [000018] DA---+-----                         *  STORE_LCL_VAR int    V01 loc1         d:3 $VN.Void
N003 (  6,  4) [000017] -----+-----                         \--*  EQ        int    <l:$183, c:$184>
N001 (  1,  1) [000015] -----+-----                            +--*  LCL_VAR   int    V02 loc2         u:2 (last use) <l:$181, c:$182>
N002 (  1,  2) [000016] -----+-----                            \--*  CNS_INT   int    0 $43

***** BB01 [0000]
STMT00004 ( 0x021[E-] ... 0x022 )
N004 (  5,  6) [000022] -----+-----                         *  JTRUE     void   $VN.Void
N003 (  3,  4) [000021] J----+-N---                         \--*  EQ        int    <l:$181, c:$182>
N001 (  1,  1) [000019] -----+-----                            +--*  LCL_VAR   int    V01 loc1         u:3 (last use) <l:$183, c:$184>
N002 (  1,  2) [000020] -----+-----                            \--*  CNS_INT   int    0 $43
```

We then remove STMT00003 after the substitution, and end up with this:
```
STMT00004 ( 0x021[E-] ... 0x022 )
N004 (  5,  6) [000022] -----+-----                         *  JTRUE     void   $VN.Void
N003 (  6,  4) [000017] J----+-N---                         \--*  NE        int    <l:$181, c:$182>
N001 (  1,  1) [000015] -----+-----                            +--*  LCL_VAR   int    V02 loc2         u:2 (last use) <l:$181, c:$182>
N002 (  1,  2) [000016] -----+-----                            \--*  CNS_INT   int    0 $43
```

Notice how tree [000018] is gone. The problem is we aren't keeping our SSA definition nodes up-to-date. For example, in `Compiler::optVNBasedDeadStoreRemoval`, we have this snippet:
https://github.com/dotnet/runtime/blob/b3e8c3cff9601b07231c7dafb56ec37614160818/src/coreclr/jit/optimizer.cpp#L6017-L6018

Here, we grab tree [000018], which has since been removed from the IR tree, and we proceed to make illegal transformations. I inserted some `DEBUG_DESTROY_NODE` logic in `Compiler::optRedundantRelop` when we remove a statement to see how often we try to read the nodes that weren't forward-subbed, and I hit asserts in `Compiler::optVNBasedDeadStoreRemoval` with pretty high frequency -- I'm guessing we haven't noticed any failures from this until now because dead store removal usually bails on making any transformations with removed nodes.

@AndyAyersMS do you have any suggestions for a surgical fix? I'm guessing we need to null out any removed SSA def node entries, though I'm wondering if we have any existing API surface for doing this cleanly -- I'm nervous that we might be quietly getting this wrong elsewhere when we remove statements.

**Comment by AndyAyersMS** [comment]
Nulling out the def node in `LclSsaVarDsc` (via `SetDefNode(nullptr)` seems like the right fix. Clients already need to cope with seeing nullptrs for def nodes, so making more of them null should be OK.

I don't know where else we do this, so am not too worried about possible further problems.
