### ISSUE TITLE
.NET 9 assert failure 

### ISSUE THREAD

**Issue by wellWINeo** [dotnet/runtime#108589]
### Description

.NET9 RC1 CLR fail assert with console 'Hello world' app on Windows 10 (more specified below)

### Reproduction Steps

1. Create new console app (e.g. [repro](https://github.com/wellWINeo/net9-helloworld)) that targets net9.0
2. Use dotnet sdk 9.0.100-rc.1.24452.12
3. `dotnet run`

### Expected behavior

Get `Hello, World!` console output

### Actual behavior

```
CLR: Assert failure(PID 110152 [0x0001ae48], Thread: 52028 [0xcb3c]): !AreShadowStacksEnabled() || UseSpecialUserModeApc()
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp:7938 Image:
C:\Users\sau5\source\demos\net9-helloworld\bin\Debug\net9.0\net9-helloworld.exe
```

### Regression?

Problem appears since 9.0.100-preview.6.24328.19 

### Configuration

* .NET: 9.0.100-rc.1.24452.12
* OS: Windows 10 Enterprise (Build 19045.2486)
* Architecture: x64

### Other information

macOS, Linux and Windows 11 not affected

**Comment by jkotas** [comment]
> OS: Windows 10 Enterprise (Build 19045.2486)

This version is way behind on patches (https://learn.microsoft.com/en-us/windows/release-health/release-information). Does the problem reproduce on fully patched Windows 10? In general, we support .NET on fully patches OSes only.

This crash is related to enablement of CET in .NET 9 (https://github.com/dotnet/docs/issues/42600). Some older Windows versions had issues in CET that have fixed by servicing updates. If you need your app to run on Windows OSes that are not fully patched, you can disable CET support for your app using one of the methods in https://github.com/dotnet/docs/issues/42600.

cc @janvorli

**Comment by wellWINeo** [comment]
Checked on freshly installed Windows 10 Pro (Build 19045.2965) and it works as expected.

Also can confirm that `<CETCompat>false</CETCompat>` fixes issue.

So i think issue could be closed, thanks for reply
