### ISSUE TITLE
Process.GetProcessById() doesn`t load StartInfo property

### ISSUE THREAD

**Issue by shellby1** [dotnet/runtime#108591]
Using pwsh 7 faced with issue that Process.GetProcessById() doesn`t load StartInfo property
but powershell 5 loads is and all it properties

Could you please implement this functionality as it implemented for powersehll 5

https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L1051

**Comment by vcsjones** [comment]
This has been discussed in https://github.com/dotnet/runtime/issues/29561 and https://github.com/dotnet/runtime/issues/14329.

In .NET Framework, `Process.StartInfo` does return something, but what it returns is actually just wrong if the current process did not start the process. For example, this will work in PowerShell 7:

```PowerShell
$notepad = Start-Process "notepad.exe" -PassThru
$notepad.StartInfo
```

.NET was changed to return an empty `ProcessStartInfo` object instead of returning wrong information.

**Comment by jeffhandley** [comment]
Thanks for digging that up, @vcsjones. Closing as by-design.
