### ISSUE TITLE
ToString() method implementation for HttpResponseMessage class returns content.Type, instead of the content itself

### ISSUE THREAD

**Issue by JaapSingh** [dotnet/runtime#108690]
### Description

ToString() method implementation for HttpResponseMessage class returns content.Type, instead of the content itself. Is there a reason why we care about the content type? It will inherit from HttpContent, what is relevant is the actual content/message itself:

https://github.com/dotnet/runtime/blob/43295bb5378453d2ec4d9272cb44c6f50b4faa1f/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs
            `sb.Append(_content == null ? "<null>" : _content.GetType().ToString());`

### Reproduction Steps

Logging an HttpReponse shows something like this:
`StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  ...
}`

### Expected behavior

Ideally, we would see something like this:
`StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: Error due to reason xyz, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  ...
}`

### Actual behavior

`StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  ...
}`

### Known Workarounds

directly logging the response.content as opposed to using .toString()

**Comment by julealgon** [comment]
If you look at how that content works, it becomes pretty clear why the `ToString()` method doesn't include it. The content is read using a `Stream`, separate from the rest of the response message.

If you were to actually attempt to read the contents, you'd end up in a situation where now you probably need to buffer the response so that further consumers don't read the whole stream multiple times (super inefficient). Additionally, there are multiple possible implementations of that content class, and each have to be read in a different way (xml, json, string, multi-part, etc):
- https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent?view=net-8.0

![image](https://github.com/user-attachments/assets/98482d54-b066-45a6-8fca-dc6a1918d66f)

Notce some are even raw byte array contents. How would you even present that in a `ToString()` result? Expecting a simple `ToString` method to be aware of all that, and overcome all the performance pitfalls, is unreasonable, I think.

If you want to log request/responses, use one of:
- API Http Logging (for logging aspnet request/responses): 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-8.0

- OpenTelemetry HttpClient instrumentation with an override to log the contents: 
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Http#httpclient-and-httpwebrequest-instrumentation-for-opentelemetry

**Comment by MihaZupan** [comment]
A couple of reasons come to mind:
- We would have to buffer the content, as response streams aren't seekable
- `ToString` is synchronous, forcing you to potentially do sync-over-async to buffer the content
- If the content is large, it could make the `ToString` output overwhelming, such that it's no longer appropriate for e.g. printing to the console
- If the content isn't text (compressed / arbitrary bytes), it may likewise not be useful when printed (base64?)
- Buffering the content isn't viable with duplex protocols (e.g. WebSockets, gRPC), so attempting to print the response would break their use

**Comment by JaapSingh** [comment]
Thank you for the prompt responses, will close this out!

**Comment by julealgon** [comment]
@JaapSingh when closing issues like this, prefer the `Close as unplanned` option to signal that it was rejected/not implemented.
