### ISSUE TITLE
OpenAPI hangs on XElement

### ISSUE THREAD

**Issue by tkvalvik** [dotnet/runtime#108755]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Request or response with XElement in them causes OpenAPI generation to hang and allocate memory at a high rate.

### Expected Behavior

Should do something more sensible.

### Steps To Reproduce

Build and run the following, then load the OpenAPI json-file.
```c#
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOpenApi();

var app = builder.Build();
app.MapOpenApi();

app.MapGet("/", () => new XElement("Test")).WithOpenApi();

app.Run();
```

### Exceptions (if any)

We have instances of XElement in some of our contracts with a custom converter. With Swagger it was easy to map XElement to the schema for object which is appropriate for our use case.

This problem now occurs before any OpenApiSchemaTransformers are applied, as such we cannot get it to work at all.

### .NET Version

9.0.100-rc.1.24452.12

**Comment by eiriktsarpalis** [comment]
Having debugged this for a bit, the issue seems to be caused by the fact that

1. `XElement` is a highly recursive type, i.e. it contains multiple properties of the same type or other types who are themselves recursive often containing references back to `XElement`. (`XNode`, `XNamespace`, `XAttribute`, etc.)
2. `JsonSchemaExporter` handles recursive types by emitting `$ref` keywords, but it does so conservatively; it only happens for nodes that are direct descendants of the original occurrence, but it never reuses schemas generated from sibling nodes of identical metadata.

The end result is a generated schema that blows up in size with a high degree of repeated schemas in the tree. I believe that this can be mitigated by being more aggressive in how we reuse schemas, however that does go against feedback that we should try to minimize `$ref` keywords as much as possible.
