### ISSUE TITLE
Nullable reference type question

### ISSUE THREAD

**Issue by jmroyb** [dotnet/runtime#1087]
Acording next link I can identify a nullable value type:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#how-to-identify-a-nullable-value-type

var result = IsNullable(typeof(int?));

bool IsNullable(Type type) => Nullable.GetUnderlyingType(type) != null;

With the introduction of #nullable enable/disable in C#8, when can we identify a nullable reference type?

var result = IsNullable(typeof(string?));

bool IsNullable(Type type) => Nullable.GetUnderlyingType(type) != null;

https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

Cheers

**Comment by Wraith2** [comment]
Try it in [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgZgAJT6Bhegb2vq8ZJPoF4AfIzIBOABQBJAM4A5HABsFAQ2AKY4jAE8ADjAgAzcUTIAGAPwBKawG5O3E0nrAIEBfRnylq9eIAqujD02nqWAsJeKmowAHQA4jAYAKp4ACYwUApaAJZ4AOYBepqBYQCE/PR4igp2VAC+QA===) and you'll find that no you can't because:

```error CS8639: The typeof operator cannot be used on a nullable reference type```

Nullable reference types are present in the assembly as attributes and are used by the compiler with flow analysis to identify violations of the stated use. Nullable value types are supported by the Nullable type and are a runtime feature.

**Comment by huoyaoyuan** [comment]
See the [compiled form](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+WRjgAwD8pAGgBQCUpALwA+UgDsArgBspAbkIBfIA==) of nullable reference type:
You need to check `System.Runtime.CompilerServices.NullableAttribute` when using reflection.
EFCore is a good sample of this.

**Comment by danmosemsft** [comment]
@jmroyb is your question answered?

**Comment by jmroyb** [comment]
Hi @danmosemsft . It is not answered. I thinks this is a new feature after C# 8.

The problem is typeof(string?): It is not allowed at writting time. Error CS8639 is raised. If typeof is valid  for any kind of  value type and referenced type in previous C# 8 versions except typeof(string?),  in C# 8 with  #nullable enable, typeof(string?) should be valid and this shoud work too:

bool isNullable=Nullable.GetUnderlyingType(typeof(string?)) != null;

Thanks

**Comment by mikedn** [comment]
>  typeof(string?) should be valid and this shoud work too

Why should it be valid? What result do expect to get?

Thing is, there's really no such thing as nullable or non-nullable reference types in the runtime. Depending on how you look at it, the String type is either
1. always non-nullable - if you have an instance of the String type then it is not null, otherwise it wouldn't be an instance of String
2. always nullable - there's no way for the runtime to prevent reference of String type to be null

`string?` isn't a real object type, it's rather the type of an object reference.
