### ISSUE TITLE
`IHostBuilder.UseConsoleLifetime` equivalent when using `IHostApplicationBuilder`

### ISSUE THREAD

**Issue by eduherminio** [dotnet/runtime#108865]
In the context of adding `IHostApplicationBuilder` support to our API surface, I'm trying to mimic existing `IHostBuilder.UseConsoleLifetime()` usage in the context of `IHostApplicationBuilder`.

Having a look at `IHostBuilder.UseConsoleLifetime()` implementation, it's doing something along these lines:
```csharp
        [UnsupportedOSPlatform("android")]
        [UnsupportedOSPlatform("browser")]
        [UnsupportedOSPlatform("ios")]
        [UnsupportedOSPlatform("tvos")]
        public static IHostBuilder UseConsoleLifetime(this IHostBuilder hostBuilder)
        {
            return hostBuilder.ConfigureServices(collection => collection.AddSingleton<IHostLifetime, ConsoleLifetime>());
        }
```

Does it make sense for us to do the same thing for `IHostApplicationBuilder`, or are there any gotchas hidden under `HostApplicationBuilder` implementation?
Something like:
```csharp
    private static IHostApplicationBuilder UseConsoleLifetime(this IHostApplicationBuilder builder)
    {
       // We were doing this for IHostBuilder, right before invoking .UseConsoleLifetime(), not sure if it still applies here
        builder.Services.RemoveIHostLifetime();

        _ = builder.Services.AddSingleton<IHostLifetime, ConsoleLifetime>();

        return builder;
    }
```

**Comment by eduherminio** [comment]
cc/ @eerhardt

**Comment by eerhardt** [comment]
HostApplicationBuilder uses the ConsoleLifetime by default:

https://github.com/dotnet/runtime/blob/a174fd12be93592cf694978cfc6bd89517e47c63/src/libraries/Microsoft.Extensions.Hosting/src/HostApplicationBuilder.cs#L176

https://github.com/dotnet/runtime/blob/a174fd12be93592cf694978cfc6bd89517e47c63/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L312

https://github.com/dotnet/runtime/blob/e1a14a8f284b94b31b84d62067773b2f9a5e2547/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.netcoreapp.cs#L12-L21

So you shouldn't need to mimic the existing `IHostBuilder.UseConsoleLifetime()` method. It happens by default out of the box.

**Comment by halter73** [comment]
Good point about the default.

Another thing to consider is that a lot of methods that extend `IHostBuilder` could have extended `IServiceCollection` or `IConfigurationBuilder` instead which would work with both `IHostBuilder` and `IHostApplicationBuilder`.

We've already dealt with similar issues with `UseSystemd() and `UseWindowsService()` which are very similar, and we addressed that by making equivalent `IServiceCollection` extension methods. [Add AddSystemd() and AddWindowsService() IServiceCollection extension methods](https://github.com/dotnet/runtime/pull/68580).

We initially hoped that any method targeting `IHostBuilder` could adapt to target `IServiceCollection` or `IConfigurationBuilder` instead. And if not, you could make it two extension methods. In time, we decided that there are use cases where we wanted a single extension method to confgure both of these and added `IHostApplicationBuilder`, but I think targeting that should be a last resort because you will have to duplicate the logic for `IHostBuilder`. See https://github.com/dotnet/runtime/discussions/81090#discussioncomment-8573371 for more context.

**Comment by eduherminio** [comment]
Thanks folks, closing the issue as my specific request is answered.

If you still envision it's worth having this method around, I'm happy to push a PR refactoring
https://github.com/dotnet/runtime/blob/e1a14a8f284b94b31b84d62067773b2f9a5e2547/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.netcoreapp.cs#L14-L21

into a separated `.UseConsoleLifetime()`/`.AddConsoleLifetime()` `IServiceCollection` extension as discussed.

Something else to consider if we were to move forward with that new extension would be the deprecation of the existing `IHostBuilder` extension in favor of this new one.
