### ISSUE TITLE
KeyedService.AnyKey -> not working correctly

### ISSUE THREAD

**Issue by waszakCeneo** [dotnet/runtime#109016]
### Description

Method GetKeyedServices should allow you to get all keyed services. 
Instead of adding correct override for that there was created this hack called "KeyedService.AnyKey"
The issues with this hack is that it doesn't work as intended. You would assume that its gonna return services for any key.
But no instead you have to name them the same.

Because this is confusing. I would propose adding just  "provider.GetKeyedServices<IMyType>();" and remove AnyKey because it doesn't work as intended.

### Reproduction Steps

```

services.AddKeyedSingleton<IMyType, MyType1>(typeof(MyType1).ToString());
services.AddKeyedSingleton<IMyType, MyType2>(typeof(MyType2).ToString());

access:
var list = provider.GetKeyedServices<IMyType>(KeyedService.AnyKey) //  empty list
```

### Expected behavior

Returns both services

### Actual behavior

Returns empty list

### Known Workarounds

```
services.AddKeyedSingleton<IMyType, MyType1>(KeyedService.AnyKey);
services.AddKeyedSingleton<IMyType, MyType2>(KeyedService.AnyKey);

access:
var list = provider.GetKeyedServices<IMyType>(KeyedService.AnyKey) // returns both
```

**Comment by stephentoub** [comment]
This prints 2 on .NET 9:
```C#
using Microsoft.Extensions.DependencyInjection;

ServiceCollection sc = new();
sc.AddKeyedSingleton<IMyType, MyType1>(typeof(MyType1).ToString());
sc.AddKeyedSingleton<IMyType, MyType2>(typeof(MyType2).ToString());
IServiceProvider provider = sc.BuildServiceProvider();

var list = provider.GetKeyedServices<IMyType>(KeyedService.AnyKey).ToList();
Console.WriteLine(list.Count);

interface IMyType { }
class MyType1 : IMyType { }
class MyType2 : IMyType { }
```

**Comment by waszakCeneo** [comment]
Doesn't work on .net8

**Comment by stephentoub** [comment]
> Doesn't work on .net8

Correct.
https://github.com/dotnet/runtime/issues/91466#issuecomment-1827916474
https://github.com/dotnet/runtime/pull/95582
https://github.com/dotnet/runtime/issues/100105

**Comment by stephentoub** [comment]
cc: @benjaminpetit, @steveharter 
https://github.com/dotnet/runtime/pull/95853

**Comment by steveharter** [comment]
I'm going to close this issue since [it was fixed in v9](https://github.com/dotnet/runtime/pull/95582) (specifically, `GetKeyedServices()` + `KeyedService.AnyKey`) [but was not backported to v8](https://github.com/dotnet/runtime/pull/95853#issuecomment-2012274349) since there were\are still related but unresolved design issues in v9 around `GetKeyedService()\GetKeyedServices()` consistency with `GetService()\GetServices()` relating to using either `null` and `AnyKey`.

We need to come up with a plan for the unresolved issues for v10, and get it in early in the release so we have time for feedback. I'll take the action item to come up with the proposal(s).

**Comment by davidfowl** [comment]
Seems worthy of a backport
