### ISSUE TITLE
Inconsistent AssemblyVersion of Microsoft.Extensions.Logging.Abstractions between .NET and .NET462

### ISSUE THREAD

**Issue by newbienewbie** [dotnet/runtime#109044]
The latest stable [Microsoft.Extensions.Logging.Abstractions.8.0.2.nupkg](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/8.0.2) has an AssemblyVerion of `8.0.0.0` for .NET8 while attributing anther AssemblyVersion (`8.0.0.2`) for .NET462.)

This may lead confusing runtime error in some scenario.

## Background

- I have a .NET8.0 library project `A` that uses some 3rd-party lagecy technology and must targets .NET472. This project has a referece on `Microsoft.Extensions.Logging.Abstractions.8.0.2.nupkg`.
- I have another .NET8.0 App `B` that refereces the above project `A` and also other .NET projects. The other projects also references the same `Microsoft.Extensions.Logging.Abstractions.8.0.2.nupkg`
- The App B compiles. However it throws at runtime due to the mismatch Assembly version :  

> unable to load one of requested types,
> unable to load file or assembly "Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.2"

## Troubleshooting

The version 8.0.0. is suspicious. After inspecting the dlls in the debug folder, I find this dll AssemblyVersion is inconsistent between .NET and .NET462.
 
- download the  [Microsoft.Extensions.Logging.Abstractions.8.0.2](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/8.0.2)
- unzip the nupkg and change directory to the `lib/` folder
- disassemly the dll under the `net8.0/` folder and we can get the AssemblyVersion is 8.0.0.0
- disassemly the dll under the `net6.0/` folder and we can get the AssemblyVersion is 8.0.0.0
- disassemly the dll under the `net462/` folder and we can get the AssemblyVersion is 8.0.0.2

![Image](https://github.com/user-attachments/assets/5481726e-38f8-4e48-a391-1a9e913a0812)

So I guess here's the reason why my app B crash at runtime:

- The project `A`, which targets net472, use the info that the Microsoft.Extensions.Logging.Abstractions.dll is coming from `lib/net462/`, and thus believe that the AssemblyVersion is **8.0.0.2**
- The project `B`, which targets net8.0,  finally copies the dll from `lib/net8/`, however, this dll's AssemblyVersion is **8.0.0.0** . And finally, it throws and complains that there's no assembly "Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.2".

Is it better to make the AssemblyVersion the same regardless of .NET or .NET Framework ?

**Comment by tarekgh** [comment]
@newbienewbie could you please provide a simple repro project we can look at?

**Comment by newbienewbie** [comment]
> [@newbienewbie](https://github.com/newbienewbie) could you please provide a simple repro project we can look at?

Hi @tarekgh , here's [a minimal demo](https://github.com/newbienewbie/minimal-demo-for-dotnet-runtime-109044/settings) .

**Comment by tarekgh** [comment]
@newbienewbie compilation of the shared projects produces the following warning:

`ProjectReference '...\minimal-demo-for-dotnet-runtime-109044-main\NetFxLib\NetFxLib.csproj' was resolved using '.NETFramework,Version=v4.7.2' instead of the project target framework '.NETCoreApp,Version=v8.0'. This project may not be fully compatible with your project.`. Are you ignoring this warning. 

CC @ericstj

**Comment by newbienewbie** [comment]
There is a warning indeed. However, if it is the key to the question, it doesn't explain why the other `works` branch works which produces the same warning too.

The key information I report here is the **AssemblyVersion** of dll from the **same 8.0.2 nupkg**, is different beween the lib/net8 and lib/net462 target.

**Comment by ericstj** [comment]
> versions for different target versions of the same assembly will break the build process somewhere and is absolutely a bug that should be fixed ASAP.

I'm sorry, but it is not a bug.  A warning is given whenever `.NETFramework` assets are consumed in a project that is not compatible with `.NETFramework`.  That warning is specifically meant to tell you about cases such as this.

The rule we must follow is that compatible frameworks must have >= assembly versions.  So `.NETFramework` must be >= `.NETStandard`, `.NET(CoreApp)` must be >= `.NETStandard`, versions of a framework must be >= older versions, newer packages must be >= older, etc.  There are no guarantees for frameworks which don't have a compatibility relationship, such as the use of `.NETFramework` in .NET through `AssetTargetFallback`.

We intentionally increment `.NETFramework` assemblies to guarantee that serviced packages will be used and win over an un-serviced version that was installed to the GAC.  This is a serviceability and security requirement from our users.

We [intentionally](https://github.com/dotnet/runtime/blob/4e4054bda992c284a4ef0e0d840cd906f9a8275d/src/libraries/Directory.Build.targets#L80) do not increment versions that are "inbox" in .NET since those are updated in-place through central servicing.  This also means we pin `.NETStandard` versions.  This is a compatibility requirement from our users.

We've reached this current behavior by balancing requirements.  It does create this rough edge when folks mix incompatible frameworks, but that's a tradeoff we have to make.  The recommended fix here is to multi-target the library which is targeting `.NETFramework`.  If you cannot do that, a workaround I've given for folks who are stuck in this situation is to force their `.NETFramework` library project to use the `.NETStandard` assembly with the lower version - you can do this by excluding the assets from the package and adding a reference constructing the path yourself. 

See https://github.com/dotnet/runtime/issues/92486#issuecomment-1733963757, https://github.com/dotnet/runtime/issues/20284#issuecomment-325390660 and many other issues.
