### ISSUE TITLE
X509CertificateLoader fails to read cat files

### ISSUE THREAD

**Issue by Nuklon** [dotnet/runtime#109046]
### Description

The now obsoleted ctor works fine when reading cat files, but the new X509CertificateLoader fails to load it and throws "Cannot find the requested object.".

### Reproduction Steps

```csharp
using X509Certificate2 certificate = X509CertificateLoader.LoadCertificateFromFile(path); // throws
```

Example cat file (taken from latest AMD driver, rename to .cat): [example.cat.txt](https://github.com/user-attachments/files/17444555/example.cat.txt)

### Expected behavior

Load OK.

### Actual behavior

Throws an exception.

### Regression?

Yes.

### Known Workarounds

Use obsoleted ctor.

### Configuration

.NET 9.0 RC2
Windows 11 24H2 x64

**Comment by jeffhandley** [comment]
@bartonjs, as far as I know we didn't consider CAT files to be in scope for the new X509CertificateLoader; is that right? From my understanding, they aren't actually X.509 certificate payloads.

@Nuklon, what data were you extracting from the CAT file via the X509Certificate2 API?

**Comment by Nuklon** [comment]
> [@Nuklon](https://github.com/Nuklon), what data were you extracting from the CAT file via the X509Certificate2 API?

The issuer and expiration date.

**Comment by bartonjs** [comment]
Yeah, .cat is not a certificate.  `X509Certificate2.GetCertContentType` would indicate that the content of this file is `Authenticode`, and Authenticode is not supported by the new loader (shown in https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/libraries.md#changes-to-x509-certificate-loading).

There have been a few other feedback items about this (e.g. https://github.com/dotnet/runtime/discussions/108740), so we may add improved Authenticode support in the future.  But, for now, your best course of action is to suppress the warning and continue to use the old constructor.

Bonus points if you precede it with `if (X509Certificate2.GetCertContentType(path) != X509ContentType.Authenticode) { throw something...; }`

My/our understanding is that the Authenticode support wasn't often used, but we've gotten more feedback during the RC period than I expected to get over the next several years... so that's clearly wrong.  However, a different discussion I was having recently showed that the support we DO have isn't sufficient for interacting with anything "recently" signed by Microsoft, as our support only finds the legacy/SHA-1 signer, and not the SHA-2-256 signer.  So I don't think we want to bring back a modernized version of what we had... if we do anything for Authenticode it needs to be more significant (current strawman, SignedCms.LoadFromAuthenticode, to get the whole authenticode block)

Based on the title of the issue, this is working exactly as designed... the new loader does not do content-sniffing, and each method only supports the name of the format embedded in the method ("Certificate" is the name of the data format in [IETF RFC 3280](https://datatracker.ietf.org/doc/html/rfc3280#section-4.1), and friends).
