### ISSUE TITLE
Directory.Exists() returning correctly for paths involving "i" characters on Turkish locale machine

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#109160]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DirectoryExists-returning-correctly-f/10644251)._

---
\[severity:Other\]  
Attached “ConsoleApp1.zip” used to reproduce issue with Directory.Exists() on Turkish locale windows 10 machine.

Here is the C# code that references Directory.Exists():

```  
string folder_uppcase = "C:\\TEMP\\NFPA";
if (Directory.Exists(folder_uppcase))
    Console.WriteLine($"Folder (in upper case) {folder_uppcase} exists");
else
    Console.WriteLine($"Folder (in upper casee) {folder_uppcase} does not exist");

string folder_lowcase = folder_uppcase. ToLower();

if (Directory.Exists(folder_lowcase))
    Console.WriteLine($"Folder (in lower case) {folder_lowcase} exists");
else
    Console.WriteLine($"Folder (in lower casee) {folder_lowcase} does not exist");

folder_uppcase = "C:\\TEMP\\IEC";
if (Directory.Exists(folder_uppcase))
    Console.WriteLine($"Folder (in upper case) {folder_uppcase} exists");
else
    Console.WriteLine($"Folder (in upper casee) {folder_uppcase} does not exist");

folder_lowcase = folder_uppcase. ToLower();

if (Directory.Exists(folder_lowcase))
    Console.WriteLine($"Folder (in lower case) {folder_lowcase} exists");
else
    Console.WriteLine($"Folder (in lower casee) {folder_lowcase} does not exist");
  
```

Here are the reproducible steps for incorrect Directory.Exists() return value on Turkish locale machine for paths involving upper and lower case “i” characters:

1.  On English locale windows 10 machine, download and build attached NET Core Console Standalone application (ConsoleApp1.zip) using Visual Studio 2022 Version 17.8.0
2.  Copy output “net8.0-windows” folder to Turkish locale windows10 machine
3.  In the Turkish locale windows 10 machine, create following folders:
    *   “c:\\temp\\nfpa”
    *   “c:\\temp\\ıec” (for English locale windows 10 machine, create “c:\\temp\\iec” instead)
4.  In the Turkish locale windows 10 machine, launch a command line window, browse to and execute ConsoleApp1.exe

Result: not all folders exist, refer to attached “MicrosoftTurkTRK.PNG”  
Expected result: all folders exist, refer to attached “MicrosoftTurkEnu.PNG”

English locale windows 10 machine: Version 22H2, OS Build 19045.4291  
Turkish locale windows 10 machine: Version 22H2, OS Build 19045.3693

[ConsoleApp1.zip](https://aka.ms/dc/file?name=B53b345e82ef34465ae62aa59408517f4638494595282085127_ConsoleApp1.zip&tid=53b345e82ef34465ae62aa59408517f4638494595282085127)  
[MicrosoftTurkEnu.PNG](https://aka.ms/dc/file?name=B642ce015facd467c9c8ccde2553c8ad1638494595545333215_MicrosoftTurkEnu.PNG&tid=642ce015facd467c9c8ccde2553c8ad1638494595545333215)  
[MicrosoftTurkTRK.PNG](https://aka.ms/dc/file?name=B581ac7b701954769a16718efd8d2e056638494595631243474_MicrosoftTurkTRK.PNG&tid=581ac7b701954769a16718efd8d2e056638494595631243474)

---
#### Li San Low on 4/23/2024, 11:43 AM: 

<p>This issue potentially has the same root cause as another issue: <a target='_blank' href="https://developercommunity.visualstudio.com/t/Target-location-does-not-exist-problem/10507392?q=turkish&amp;viewtype=all">https://developercommunity.visualstudio.com/t/Target-location-does-not-exist-problem/10507392?q=turkish&amp;viewtype=all</a></p>

#### Feedback Bot on 4/24/2024, 03:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Anonymized GDPR on 4/24/2024, 10:18 AM: 

<p>Thanks for your sharing the detail steps, I can reproduce this issue in VS2022 (17.9.6) through your shared steps and this issue has been escalated for further investigation, if there is any process, I will inform you immediately.</p>

**Comment by Clockwork-Muse** [comment]
Ah yes, the [Turkish "i" problem](https://stackoverflow.com/a/3550226/812837).  Essentially, this behavior is "as designed by unicode" (there's no bug in the runtime).

The correct fix _for the application_ depends on a few factors, but the biggest one is that you shouldn't be messing with file/directory casing.
Changing/using a directory with a different casing than it was created with is immediately non-portable, as non-Windows platforms have case-sensitive file systems (and even Windows, with some settings).  The application should be explicit about its casing and reject incorrect casing regardless.

Note that `File.Exists(...)`/`Directory.Exists(...)` can be a trap, since a result doesn't guarantee anything about the state of the filesystem - you need to actually attempt an action (eg, open a file).

If there's a need to reference/view a set of entries, regardless of case, then the better way to do that would be via [`EnumerateFiles(...)`](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=net-8.0#system-io-directory-enumeratefiles(system-string-system-string-system-io-enumerationoptions)) and setting `EnumerationOptions` appropriately.  However, note that you will need to be careful, as the results of the casing-ignorant comparison may not be what you expect - ie, on a Turkish-culture machine, the casing results are going to be Turkish-culture specific.

**Comment by cempehlivan** [comment]
Yes, these are taken into consideration when developing an application, but when the target location is clicked after publish, although the application name has uppercase letters, it tries to open the publish folder path by changing it to lowercase and gives an error.

![Image](https://github.com/user-attachments/assets/24ecadc2-265e-4964-a754-c0e400c2d017)

**Comment by Clockwork-Muse** [comment]
That's a completely separate issue from what was initially reported here, and still isn't a runtime issue.  Depending on what's happening, it might not even be coming from something written in C# anyways.

Check your `.csproj`/`.sln` for case mismatches (or casing functions), or whether it uses [`MSBuildProjectName` in place of `MSBuildProjectDirectory`](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2022), or [similar](https://learn.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170).
If everything looks fine, then it either belongs to the [sdk](https://github.com/dotnet/sdk), or to VisualStudio proper.
