### ISSUE TITLE
'ILLinkTreatWarningsAsErrors' doesn't seem to work when publishing as MSIX

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#109271]
### Description

Perhaps related to #109154. I noticed that when creating an MSIX package, which uses MSBuild `-t:build` and runs the publish targets internally, setting `ILLinkTreatWarningsAsErrors` doesn't seem to work. I get a bunch of ILC warnings, yet the build completes successfully just fine.

### Reproduction Steps

Same as #109270. Can't share repro steps here (since the code is not open source).
I can however share:
- binlog (MSFT only): [link](https://microsoft-my.sharepoint-df.com/:u:/p/sergiopedri/ESW_tpVfTPVEtkIJdBVS1AQBQ9ztXn2vzjpIlzbD65wZPw?e=pt20Y0)
- repo link and instructions to build locally (ping me on Teams)

### Expected behavior

Build should fail with all ILXXXX warnings as errors.

### Actual behavior

![Image](https://github.com/user-attachments/assets/7aa4a6b2-c6d0-4c15-9488-ff3a8943431a)

**Comment by MichalStrehovsky** [comment]
This is currently by design. Per [the docs](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0): "Some of the options mention ILLink, which is the name of the underlying tool that implements trimming." This is one place where the underlying tool that performs _IL level trimming_ seems to have leaked out. There is no _IL level trimming_ during an AOT compilation and ILLink never executes in that scenario. This warning is generated by ILC, which is not ILLink and doesn't respect ILLink specific settings.

The question is whether we need ILC to respect this. I don't know what prompted this ILLink specific property to be documented. It's not the kind of property we'd generally have in .NET (e.g. there's no CSCTreatWarningsAsErrors to only treat C# compiler warnings as errors). If we do teach ILC to respect this, should this also apply to AOT and single file warnings generated by ILC? If not, do we need new properties to have parity? How about the analyzers? Should single file analyzer also respect this? Etc.

In .NET we do have a mechanism that works universally and that's NoWarn, WarningsAsErrors, WarningsNotAsErrors, and TreatWarningsAsErrors, as spelled out in the trimming docs next to ILLinkTreatWarningsAsErrors. If it was up to me, I'd deprecate ILLinkTreatWarningsAsErrors and keep it for backcompat only (and drop it from docs).

@dotnet/illink for opinions.

**Comment by Sergio0694** [comment]
I suppose my concern is: especially in large codebases with lots of history, it's very hard or impractical to enforce all warnings as errors (I'd love to enable that, but it'll take us some time to get there). However, for trim/AOT warnings, I definitely would like to make them all errors. But maintaining a list of all the 50+ warnings manually seems like not a great solution. I'd like to have just a single setting I could turn on, that'd make all ILXXXX warnings be a build error, regardless of where they're coming from (analyzers, ILC, doesn't matter).

**Comment by MichalStrehovsky** [comment]
> I suppose my concern is: especially in large codebases with lots of history, it's very hard or impractical to enforce all warnings as errors (I'd love to enable that, but it'll take us some time to get there)

The way I've seen it done in large codebases is that one enables warnings as errors and adds NoWarn/WarningsNotAsErrors for everything that is already triggering. This draws a line that says: "any new kinds of warnings need to be looked at". Any new additions to the NoWarn will be reviewed from then on. This guarantees the codebase doesn't get any worse, unless code review says it's fine. Then one can chip off warning by warning at a leisure time, fixing them and dropping them from NoWarn.

Is that not feasible?

**Comment by Sergio0694** [comment]
Thank you both for the additional context! 🙂

> "The way I've seen it done in large codebases is that one enables warnings as errors and adds NoWarn/WarningsNotAsErrors for everything that is already triggering. This draws a line that says: "any new kinds of warnings need to be looked at". Any new additions to the NoWarn will be reviewed from then on. This guarantees the codebase doesn't get any worse, unless code review says it's fine. Then one can chip off warning by warning at a leisure time, fixing them and dropping them from NoWarn."

Yeah that seems reasonable, and like you said that'll also make all ILXXXX warnings be errors, which is what I'm looking for.
I can just do that and explicitly opt out the few warnings we currently have, and we can resolve them later.

Thank you again!
