### ISSUE TITLE
Throwing Exception with cyclical inner exception reference hangs forever

### ISSUE THREAD

**Issue by thomhurst** [dotnet/runtime#109262]
### Description

Weird scenario, initially raised against my testing framework (https://github.com/thomhurst/TUnit/issues/1018 & https://github.com/microsoft/testfx/issues/3971), but I've tried it in a bog standard console app and it hangs forever.

I don't know why this would ever happen in standard code, but I thought I'd bring it to your attention anyway.

I'm assuming when it's trying to generate the stacktraces of all the inner exceptions it's just looping forever.

### Reproduction Steps

Top level statement - Program.cs

```csharp
using System.Reflection;

throw new CyclicalException();

public class CyclicalException : Exception
{
    public CyclicalException()
    {
        typeof(Exception)
            .GetField("_innerException", BindingFlags.Instance | BindingFlags.NonPublic)!
            .SetValue(this, this);
    }
}
```

### Expected behavior

To finish throwing the exception 

### Actual behavior

Execution hangs indefinitely when `throw` is called

**Comment by jkotas** [comment]
You repro uses private reflection against .NET runtime internals. Using private reflection to modify .NET runtime internals is not supported. It can result into unexpected behaviors, including hangs.

Number of algorithms in `Exception` implementation are not robust against the reference cycles that you have created using private reflection. It is by design.
