### ISSUE TITLE
First class support for Vectored I/O

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#109358]
Hello everyone,

Vectored I/O could be used for even faster file operations (read & write).
There is evidence that performance is drastically increased (google it -> many results).

If I'm not mistaken, we can also map such vectored scenarios with the new Windows-IORING API - #58752.

**See:**
Windows: `ReadFileScatter`, `WriteFileGather`
Linux: `readv`, `preadv`, `preadv2`, `writev`, `pwritev`, `pwritev2`

For example, WriteFileGather is already used in `System.IO.RandomAccess`.

I would be in favor of integrating vectored I/O into our APIs.
For example, what would you think about adding a vectored Read & Write method to the FileStream class?

The Rust standard library also has such an API - as far as I know even in the generic trait above it (comparable to an interface in C#)
-> If nothing speaks against it, I would create a corresponding API-proposal

There are certainly other APIs where something like this could make sense, what do you think?

/area:System.IO
/cc @jeffhandley @adamsitnik

**Comment by huoyaoyuan** [comment]
Gather/scatter IO are already integrated with `RandomAccess`. Are you proposing to expose some wrapping or abstraction through `FileStream` or `Stream`?
See the discussions in #25344 and #24847 .

**Comment by adamsitnik** [comment]
Hi @deeprobin 

As @huoyaoyuan wrote , `RandomAccess` already provides such capabilities and uses the most performant sys-call when available (which is very, very tricky on Windows).

When it comes to adding it to the `FileStream` itself we were considering adding it to the `Stream`: https://github.com/dotnet/runtime/issues/25344

But never really had a good reason to move it to `Stream` itself. Since it would came at a cost of increased complexity (we would need to integrate it with `FileStream` buffering and handle all edge cases) and even more virtual methods, I am going to close this issue and suggest to wait for more feedback in #25344.
