### ISSUE TITLE
Failed to invoke two associated SO files using DllImport，System.DllNotFoundException: Unable to load shared library

### ISSUE THREAD

**Issue by Linyefeilyft** [dotnet/runtime#109762]
I have two so files in C++ and the code is as follows:

DllImportSoDemo：
```cpp
#include "../DllImportSoDemo2/ABC.h"
extern "C" {
    int add(int a, int b) {
        
        return ABC::add(a, b);
    }

    int add1(int a, int b) {

        return a+b;
    }
}
```

DllImportSoDemo2：
```cpp
#include "ABC.h"

int ABC::add(int x, int y)
{
    return x+y;
}
```

I raise the following issue when I call it
```csharp
 internal class DllImportSoDemo
  {
      [DllImport(@"libs/zkfpso/DllImportSoDemo.so")]
      private static extern int add(int x, int y);

      [DllImport(@"libs/zkfpso/DllImportSoDemo.so")]
      private static extern int add1(int x, int y);

      public static int addSO(int x, int y)
      {
          return add(x, y);
      }

      public static int add1SO(int x, int y)
      {
          return add1(x, y);
      }
  }
```

```csharp
AddTextMessage(string.Format("Add1 {0}+{1}={2}", 2, 3, DllImportSoDemo.add1SO(2, 3)));
AddTextMessage(string.Format("{0}+{1}={2}", 2, 3, DllImportSoDemo.addSO(2, 3)));
```

Error message:

```
System.DllNotFoundException: Unable to load shared library 'libs/zkfpso/DllImportSoDemo.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libs/zkfpso/DllImportSoDemo.so: cannot open shared object file: No such file or directory
   at AvaloniaApplication1.DllImportSoDemo.add(Int32 x, Int32 y)
   at AvaloniaApplication1.DllImportSoDemo.addSO(Int32 x, Int32 y) in 
```

I use the development environment Vs2022, NET6, Avalonia11.0.6.

**Comment by Linyefeilyft** [comment]
I had to use the command "LD_LIBRARY_PATH=./libs/zkfpso ./AvaloniaApplication1" to call it normally, but I wanted it to work just by double-clicking to run。

**Comment by Linyefeilyft** [comment]
> [@Linyefeilyft](https://github.com/Linyefeilyft) This needs to be handled by your application. Arbitrary relative path look-up is very complicated and making it perform the "right way" for everyone isn't practical. You can use tools like `strace` to see how the runtime attempts to probe for the path. In most cases, the runtime simply passes the path onto the underlying OS API, (for example, [`dlopen()`](https://man7.org/linux/man-pages/man3/dlopen.3.html))
> 
> There is documentation on this topic at https://learn.microsoft.com/dotnet/standard/native-interop/native-library-loading.
> 
> > I had to use the command "LD_LIBRARY_PATH=./libs/zkfpso ./AvaloniaApplication1" to call it normally, but I wanted it to work just by double-clicking to run。
> 
> Using [`NativeLibrary.SetDllImportResolver()`](https://learn.microsoft.com/dotnet/standard/native-interop/native-library-loading#custom-import-resolver) is likely to be the best way forward.

Why closed my issue，You haven't solved my problem, and you haven't tested your solution.

**Comment by Linyefeilyft** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
> Why closed my issue，You haven't solved my problem, and you haven't tested your solution.

Have you hit issues using [NativeLibrary.SetDllImportResolver()](https://learn.microsoft.com/dotnet/standard/native-interop/native-library-loading#custom-import-resolver) or following the reference documentation?

**Comment by Linyefeilyft** [comment]
It is found that you can set the RPATH of executable files. The default RPATH of executable files generated by avalonia is $ORIGIN/netcoredeps; you can put all SO files under the netcoredeps folder, but there is a problem that there cannot be subfolders. I don't know if there is a way to set this property when the project is published.

使用readelf -d AvaloniaApplication1查看可执行文件的(RPATH)        Library rpath:\[\$ORIGIN/netcoredeps]。

**Comment by AaronRobinsonMSFT** [comment]
> It is found that you can set the RPATH of executable files. The default RPATH of executable files generated by avalonia is $ORIGIN/netcoredeps; 

Yes, using RPATH is a way to address this, but that isn't a .NET API and as I said, the runtime simply passes the supplied relative path to the underlying OS API, `dlopen()`. My answer, https://github.com/dotnet/runtime/issues/109762#issuecomment-2472321009, is helping to explain how to do this from a .NET perspective, not from the underlying OS. Additionally, again as mentioned, using `strace` can help narrow down the ways in which the OS is probing for paths and options can be considered, but those are outside the control of .NET.

Regarding `$ORIGIN/netcoredeps;`, this is injected into the main host, immutable, and partially documented [here](https://github.com/dotnet/core/blob/main/Documentation/self-contained-linux-apps.md). This is not the recommended path for general issues with loading shared objects from relative paths, what was suggested in https://github.com/dotnet/runtime/issues/109762#issuecomment-2472321009 is.

Based on the supplied details I'm assuming this code is running on Windows under WSL, the original issue stated "Vs2022" and that only runs on Windows, but `.so` is a *nix extension. The .NET solution to this issue is to use [`NativeLibrary.SetDllImportResolver()`](https://learn.microsoft.com/dotnet/standard/native-interop/native-library-loading#custom-import-resolver) or alternatively, [`AssemblyLoadContext`](https://learn.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext) if that is involved.

**Comment by Linyefeilyft** [comment]
@AaronRobinsonMSFT  
Maybe I didn't make it clear, my application is running on linux, and I thought that calling the SO file would run on linux by default. In linux, NativeLibrary.SetDllImportResolver() and NativeLibrary.Load() don't work.
`
private static IntPtr DllImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
{
    if (libraryName == "netcoredeps/zkfpso/DllImportSoDemo.so")
    {
        string baseDir = System.Reflection.Assembly.GetExecutingAssembly().Location; //AppDomain.CurrentDomain.BaseDirectory;
        baseDir = baseDir.Substring(0, baseDir.LastIndexOf(@"/"));
        return NativeLibrary.Load(Path.Combine(baseDir, libraryName), assembly, searchPath);
    }
    return IntPtr.Zero;
}
`
The docs say "developers need to create a directory named netcoredeps next to the main application executable and copy all the necessary dependencies into it", but I can't stack all the files into one directory, I may need to create subdirectories, However, the SO file in the subdirectory cannot be called normally.

**Comment by Linyefeilyft** [comment]
Application runtime environment：OpenKylin 1.0; OpenKylin is an Ubuntu operating system.

**Comment by Linyefeilyft** [comment]
Usually the .so file we call is not a separate dynamic library file, it may be applied to other .so files.

**Comment by Linyefeilyft** [comment]
In QT, you can set RPATH by adding configuration to the .pro file, but in Visual studio you don't know how to deal with it.
