### ISSUE TITLE
Add JIT performance counters

### ISSUE THREAD

**Issue by benmwatson** [dotnet/runtime#1098]
Specifically, these:

-	`.NET CLR Jit\# of IL Bytes JITted`
-	`.NET CLR Jit\IL Bytes Jitted / sec`
-	`.NET CLR Jit\# of Methods Jitted`

To bring Core into parity with what is available in .NET Framework.

**Comment by BruceForstall** [comment]
@tommcdon Is this something that better falls into area-Diagnostics?

**Comment by tommcdon** [comment]
I believe @sywhang was looking into this

**Comment by sywhang** [comment]
@benmwatson Thanks for adding this Ben! Quick question - Are both # bytes jitted / sec *and* total # of bytes jitted important? Could you elaborate on why the total # of bytes jitted in the entire process lifetime useful if the rate of IL bytes jitted is available? The reason I ask is because we're trying to limit the number of runtime counters being added to avoid what we had back in the Framework days which confused a lot of people and had many counters that weren't very useful in quickly diagnosing performance issues.

**Comment by benmwatson** [comment]
@sywhang Both are useful in their way. The rate counter is nice because we can detect if jitting is happening concurrent to other performance counters. The total bytes jitted is useful because we JIT a truly enormous amount of code in our process and are sensitive to changes that cause a lot more code to be jitted.

If I had to pick one over the other, I'd go with total # of bytes jitted. That least can show jumps that correlate with other events.

**Comment by sywhang** [comment]
This has been implemented via #36489
