### ISSUE TITLE
dotnet: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by dotnet) (Installing on Raspberry pi 3)

### ISSUE THREAD

**Issue by ashah7** [dotnet/runtime#109993]
### Describe the bug
Getting the below error after installing .net 9.01 on raspberry pi 3

dotnet: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by dotnet)

### To Reproduce

```
wget -N -P /tmp https://download.visualstudio.microsoft.com/download/pr/526d93c5-bae2-4cfc-a9cf-b2d28d7b5c98/17c926df21958999f74992973837d261/dotnet-sdk-9.0.100-linux-arm.tar.gz
sudo mkdir -p /opt/dotnet
sudo tar -zxf /tmp/dotnet-sdk-9.0.100-linux-arm.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/bin #link may already exists

```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

running dotnet after the install gives error

`dotnet: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found`

```
pi@000000008359c11c:~ $ uname -a
Linux 000000008359c11c 6.1.21-v7+ dotnet/sdk#1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

pi@000000008359c11c:~ $ uname -r
6.1.21-v7+

pi@000000008359c11c:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by janvorli** [comment]
Debian Bullseye is no longer supported by .NET 9. See https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.md. The fact that it doesn't have this issue on arm64 is a coincidence, probably the GLIBC_2.34 versioned symbol is not needed on arm64.

**Comment by vcsjones** [comment]
> The fact that it doesn't have this issue on arm64 is a coincidence, probably the GLIBC_2.34 versioned symbol is not needed on arm64.

More specifically, this is because .NET 9 requires glibc 2.35+ on ARM32, whereas glibc 2.23+ is the minimum for ARM64.

The higher glibc requirement for ARM32 in .NET 9 is because of the ARM32 transition to 64-bit time. See this discussion for additional details. https://github.com/dotnet/core/discussions/9285

**Comment by vcsjones** [comment]
I am going to close this issue out because this is a documented behavior. See [Linux Compatibility](https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.md#linux-compatibility) in the .NET 9 release notes.

.NET 9 on ARM32 requires glibc 2.35+. Based on the issue, the OS is "Raspbian GNU/Linux 11 (bullseye)". Bullseye has 2.31.

This is not observed for ARM64 because the glibc version requirement is lower than what Bullseye provides.

Please feel free to re-open this issue if you think this issue was closed improperly.
