### ISSUE TITLE
Remove Misleading Claim About Java's Value Types in Object Stack Allocation Documentation

### ISSUE THREAD

**Issue by mburakeker** [dotnet/runtime#110295]
**Problem Description**
The documentation for Object Stack Allocation currently includes the following statement:

> `This optimization is more important for Java since it doesn't have value types.`

This is misleading because:

- Java does have an equivalent to value types, called Primitive Types, which are stored in stack memory.
- The comparison suggesting Object Stack Allocation is more important for Java is inaccurate.

**Proposed Solution**
Replace the misleading sentence with:

> `This is also important for Java.`

This update removes the false comparison and keeps the focus on the scope of Object Stack Allocation across both .NET and Java.

**Comment by teo-tsirpanis** [comment]
Primitive types in Java are only `boolean`, `char`, `byte`, `int`, `short`, `long`, `float`, and `double`. Unlike C# you cannot declare a _custom_ value type in Java. Because all user-defined types in Java are classes and therefore allocated on the heap, Object Stack Allocation is more important in Java because developers have no manual control of which values stay in the stack.

**Comment by mburakeker** [comment]
> Primitive types in Java are only `boolean`, `char`, `byte`, `int`, `short`, `long`, `float`, and `double`. Unlike C# you cannot declare a _custom_ value type in Java. Because all user-defined types in Java are classes and therefore allocated on the heap, Object Stack Allocation is more important in Java because developers have no manual control of which values stay in the stack.

Thank you for the explanation! Your comment provides a much clearer explanation. I'll close my PR since it’s obsolete. 
Feel free to update the documentation with better wording if you'd like.
