### ISSUE TITLE
Remove GT_ADDR nodes

### ISSUE THREAD

**Issue by mikedn** [dotnet/runtime#11057]
Similar to dotnet/runtime#10873 but about `GT_ADDR` nodes. Like `GT_ASG` nodes, `GT_ADDR` nodes have one fundamental issue: they change the semantics of their operand nodes.

A `GT_LCL_VAR` that is used by `GT_ADDR` is no longer a node that produces a value, it's a node that represents a location. It also affects `GT_FIELD` so you can have a chain like `GT_FIELD(GT_ADDR(GT_FIELD(GT_ADDR(GT_FIELD(…)))))` where the outer `GT_FIELD` is an indirection that produces a value while the inner ones just represent locations.

This approach results in various code complications, inefficiencies and bugs.

category:implementation
theme:ir
skill-level:expert
cost:extra-large

**Comment by SingleAccretion** [comment]
Seeing as I will be working on this issue (and the `ASG` elimination that is actually much more straightforward and at this point is just a mechanical refactoring), it would be useful to detail the work that needs to be done and ways in which I am planning to approach it. As detailed above, we have a few uses of `ADDR`, and some are easier to get replace with equivalents than others.

1) `FIELD` nodes: come in 3 flavors.
    - Statics: mostly harmless, and simple enough that they can be imported as `IND/OBJ(addr)`. "Complex" cases today already use this representation, only the simplest of statics (that have a constant) address are preserved until morph and then dissolved into `IND(const addr)` or `CLS_VAR`. It the latter case that is somewhat problematic (`CLS_VAR` is one of the distinct "location" nodes), fortunately, it is in the process of being deleted as part of #58312 (I actually have almost all the local changes necessary, so it is just a matter of time at this point). Code that cares about statics (mostly one looking for type infromation) can simply use `IsFieldAddr` to recognize them (that will also catch _all_ statics, not just "simple" ones).
    - TLS statics: so rare expanding them in the importer is likely to be just fine.
    - Instance, non-local struct/class members: very simple, can be reduced to `FIELD_ADDR`.
    - Instance, local: probably the most complex part of this work, otherwise known as `TYP_STRUCT` `LCL_FLD`. There are a few issues:
        - We cannot "just" add `ClassLayout*` to `LCL_FLD`. The current thinking is that we'll restrict the SSA number to 16 bits (an `unsigned short`) and exclude variables with too high refcounts from SSA. It is hard to imagine this hurting any realistic scenario (65K SSA defs for a single variable is quite a lot...), while it will allow us to cleanly fit a whole pointer worth of `ClassLayout*` into `LCL_FLD` cleanly.
        - `TYP_STRUCT` `LCL_FLD` needs to be supported everywhere other `TYP_STRUCT` nodes are supported. Fortunately, these local fields will always live in memory (for now at least) and so handling them should be straightforward enough and is expected to mostly be "mechanical work" (copy/extend the handling of `OBJ`, which is supported "everywhere"). Places where the handling will need to be added:
           - Block copies and initialization. In the frontend, block morphing will need some adjustments, however, the main problem is likely going to be liveness after lowering that will require deciding whether we'll want to carry `STORE_LCL_FLD<struct>` through to codegen or "give up" and turn it into `STORE_OBJ/BLK`. For the time being, I expect to take the latter approach (and thus "give up" on the "no `LCL_ADDR` for tracked variables" invariant after lowering).
           - SSA/VN and liveness in the frontend will likely require minimal changes.
           - `RETURN`s. Should be straightforward. This is mostly backend work.
           - Call arguments, the most complex piece of the puzzle. `fgMorphArgs` will need to touched, backend work will also be required to support the `PUTARG` nodes with `LCL_FLD` sources (Or would it be enough to dissolve them to `OBJ`s at first? Mismatching node types between lower and morph sounds risky, and supporting these in codegen also does not sound too bad, so I'll likely go for it as the first-cut approach).

2) `INDEX` and array access: surprisingly simple, comes in two distinct flavors: before morph (`GT_INDEX`) and after morph.
    - `INDEX`, as noted above, can simply be replaced by `OBJ/IND(INDEX_ADDR)`, I have most of the changes necessary done, with almost zero diffs (just a few cases to iron out). This is mostly mechanical work.
    - After morph, array address access tends to be represented as `ADDR(IND(actual address expression))`, where the `IND` has  an important out-of-band `ArrayInfo` annotation which is used by VN to deduce aliasing properties. The proposed replacement for `ADDR(IND(...))` is a new `ARR_ADDR` "annotation" node (like `BOX`/`RUNTIMELOOKUP`) that will carry what VN needs. We can also add a field sequence to this node, and be able to fold `ADD(ARR_ADDR(arrAddr), CONST [FldSeq])` into `ARR_ADDR(arrAddr + CONST) [FldSeq]` (that today cannot be folded in a sane manner due to the fact there is an intermediate `ADDR(IND))`), but that is an optional optimization. Notably, there is code today in the compiler which tries to support exactly this type of folding (the `ConstantIndex` pseudo-field annotation) that is dead because of this `ADDR(IND)` wrapping.
       - Ref: #64581.

3) `OBJ(ADDR(SIMD)))` otherwise known as `impNormStructVal` and #51569. This will require pulling signature type into `GenTreeCall::Use`, will replace `PUTARG_TYPE` nodes, and in general is the area I am yet to take a deep look at. This is probably the riskiest part of all of these changes as `fgMorphArgs` will have to be touched, and touching that function is one of the less fun things one can do. It will also require supporting `LCL_VAR`s in codegen where previously only `OBJ`s were supported (the `PUTARG_STK` issue). Mostly, however, this is "just work" without significant design component to it.

4) `ADDR(LCL)` as R-values are mostly already turned into `LCL_ADDR`s by local morph, there are only a few cases (I know of one in args morphing at least) where they're still used. Once all accesses to tracked locals are replaces with `LCL_FLD` equivalents, this will be a simple "search and replace".

**Comment by mikedn** [comment]
I hope you're not just copying all the work I did in my fork, it sounds way too similar to that...

**Comment by SingleAccretion** [comment]
I was very careful to only look at the issues and changes in this (and coreclr) repository. I think most (all?) of the above is just a restatement of what has been said already, in different threads.

**Comment by shushanhf** [comment]
Hi, @SingleAccretion  @BruceForstall @jkotas  @jakobbotsch 
I can supply several LoongArch64's cloud Linux accounts for you, If you need please email to qiaopengcheng@loongson.cn to get the account .

The CoreRoot for runtime will be updated every weekday [here](https://github.com/shushanhf/LoongArch64-Blog-for-.NET-Mono/tree/main/rumtime_main_CoreRoot)

**Comment by BruceForstall** [comment]
@SingleAccretion We've been doing JIT work planning for .NET 8. Since you continue to contribute so much (thank you!) it would be useful to know if you have a plan for a set of significant work for the next year. Perhaps the description above (https://github.com/dotnet/runtime/issues/11057#issuecomment-1027844414) covers it? (Is that description up-to-date?) Or, perhaps it would be useful to create a "meta-issue" (like https://github.com/dotnet/runtime/issues/74873) to cover it?

**Comment by SingleAccretion** [comment]
> Since you continue to contribute so much (thank you!) it would be useful to know if you have a plan for a set of significant work for the next year.

I will continue working on this, and #10873 after that. So, I suppose nothing new at this point \:).

> Perhaps the description above (https://github.com/dotnet/runtime/issues/11057#issuecomment-1027844414) covers it? (Is that description up-to-date?)

More or less. I have updated it to include the latest developments.

**Comment by BruceForstall** [comment]
@SingleAccretion Thanks for the update.

> So, I suppose nothing new at this point :).

I'm sure we can find something for you if you don't find something yourself first :)

**Comment by GSPP** [comment]
@SingleAccretion I also want to thank you. I follow this issue tracker and I frequently see your excellent work. 🚀
