### ISSUE TITLE
Is it possible to add System.Management for netstandard2.1 and remove System.CodeDom dependencies?

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#110507]
I am using dotnet from unitynuget and experiencing error when introducing any package that have dependency to `System.CodeDom` library
```
CS0433: The type 'CodeStatement' exists in
both 'System.CodeDom, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

Since `System.CodeDom` was being absorbed into core `System` library in netstandard2.1 it become conflict dependency with other package that also `using namespace System.CodeDom` (such as unity visualscripting)

Is it possible for this repo to build both version of library for netstandard2.0 with codedom dependency and netstandard2.1 without codedom dependency?

Also I think there are many more library that contain many similar dependency discrepancy. Is it possible to solve all of them in similar manner?

**Comment by huoyaoyuan** [comment]
> Since `System.CodeDom` was being absorbed into core `System` library in netstandard2.1

> Is it possible for this repo to build both version of library for netstandard2.0 with codedom dependency and netstandard2.1 without codedom dependency?

This is not correct. `System.CodeDom` is not a part of any version of netstandard. The change happens in **.NET Standard 2.1 compatible Unity**, which is a separated implementation.

Since there's no target framework moniker for Unity, it's not possible to build specifically for it.

---

The problem is hard to solve here. For .NET Framework, the NuGet package provides specific implementation to forward the content to the in-box implementation. Using this implementation would solve the problem of Unity, however the NuGet rule would prefer netstandard implementation. Modifying the NuGet rule will probably break more things.

**Comment by Thaina** [comment]
Thank you very much for your clarification
