### ISSUE TITLE
Wrong random read behaviour in StreamReader

### ISSUE THREAD

**Issue by AndreyShvidky** [dotnet/runtime#110509]
### Description

I have a text file and know exact offset and length of fragments I need to read.
I used BaseStream.Position or BaseStream.Seek to change reading offset
I used StreamReader.Read(Char[], Int32, Int32) to read fragments
Only the first reading returns correct result. Second and all subsequent reading return content located after the first fragment. Readings are cycled through buffer obtained during first read.
If I use direct call of
StreamReader.BaseStream.Read(Char[], Int32, Int32)
everything works fine, but it's inconvenient to work with different encodings. 

### Reproduction Steps

Minimal repro code provided in two files
- Text file in ANSI
- Program.cs
[Program.zip](https://github.com/user-attachments/files/18054239/Program.zip)

### Expected behavior

I expect that changing stream position directly or with Seek cause reader to read starting from position provided

### Actual behavior

Only the first reading returns correct result. Second and all subsequent reading return content located after the first fragment. Readings are cycled through buffer obtained during first read.
If I use direct call of
StreamReader.BaseStream.Read(Char[], Int32, Int32)
everything works fine

### Configuration

.NET 9.0
Windows 10
x64

**Comment by stephentoub** [comment]
This is by design. StreamReader buffers data from the Stream in order to reduce the number of times it needs to call into it. If you need to access the underlying stream separately from using StreamReader's public API, you need to tell the StreamReader to throw away its buffer, which is what the DiscardBufferedData method exists for:
https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.discardbuffereddata?view=net-8.0#remarks

**Comment by adamsitnik** [comment]
As @stephentoub wrote, this is by design.
