### ISSUE TITLE
[API Proposal]: Environment.GetRequiredEnvironmentVariable

### ISSUE THREAD

**Issue by mariusz96** [dotnet/runtime#110603]
### Background and motivation

Sometimes when using the environment variable there does not exist any fallback and the environment variable is required for the application to function.

Maybe it would be a good idea to have a helper method here, kind of similar to `ServiceProviderServiceExtensions.GetRequiredService`?

### API Proposal

```csharp
namespace System;

public static class Environment
{
    public static string GetRequiredEnvironmentVariable(string variable);
}
```

### API Usage

```csharp
// Throw if environment is not configured correctly.
string myPassword = Environment.GetRequiredEnvironmentVariable("MY_PASSWORD");
```

**Comment by julealgon** [comment]
I think a better design in this case is to rely on the much more high-level `IConfiguration` system, bind to an `xOptions` class, and use option validation to enforce a required setting.

`Environment.GetEnvironmentVariable` is too low-level and I think leveraging the existing abstractions for configuration is better than extending this API for that purpose, as it will potentially push people into using it directly instead of the (arguably preferred) `IConfiguration` abstraction.
