### ISSUE TITLE
CryptoStream Dispose issue in read mode

### ISSUE THREAD

**Issue by tony-hu-avepoint** [dotnet/runtime#110899]
### Description

Dispose a partially read CryptoStream will FlushFinalBlock since _finalBlockTransformed is false. 
And FlushFinalBlock will call Flush/FlushAsync at inner stream which does not make sense for a read only stream.
For read mode decryption, it should not call FlushFinalBlock at any condition.

### Reproduction Steps

Create a custom read only stream which does not implement flush method, use it as inner stream for CryptoStream  in read mode. Then don't complete read for all data, then try to call dispose for CryptoStream, it will call flush for internal custom read only stream, and throw not implement exception.

### Expected behavior

For read mode decryption, it should not call FlushFinalBlock at any condition.

### Actual behavior

It will call FlushFinalBlock for partially read stream.

**Comment by vcsjones** [comment]
As mentioned in your pull request, Dispose calling Flush even on a read Stream is intentional.


> then try to call dispose for CryptoStream, it will call flush for internal custom read only stream, and throw not implement exception.

Other issues like #105592 go in to this a bit - it is legal to call `Flush` on a read-only `Stream`. From the [documentation of `Flush`](https://learn.microsoft.com/dotnet/api/system.io.stream.flush?view=net-9.0):


> In a class derived from [Stream](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-9.0) that doesn't support writing, [Flush](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.flush?view=net-9.0) is typically implemented as an empty method to ensure full compatibility with other [Stream](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-9.0) types since it's valid to flush a read-only stream.

It seems like your custom stream should simply do nothing for `Flush` instead of throw.
