### ISSUE TITLE
[API Proposal]: Reflecting to find nullability of a generic return type is unreasonably complicated

### ISSUE THREAD

**Issue by SRNissen** [dotnet/runtime#110971]
### Background and motivation

For my specific problem, I am trying to recursively walk each member of an object to see if a non-nullable type has had null assigned.

E.g.
```csharp
    class Example
    {
        public string S {get;set;}
    }

    var e = new Example;

    e.S = null!;

    Assert.That(HasBrokenNullInvariant(e), Is.True);
```
Which has been a blast to write, until I encountered Index Properties - specifically *generic* index properties, which always claim to be allowed to return null.

Quite probably I'm just missing something, but I'm missing something because this API is currently less than intuitive.

First, I'd love to replace this:
```csharp
var properties = type.GetProperties( bindingFlags ) // existing call;
var indexProperty = properties.Single(p=>p.GetIndexParameters().Length != 0); //existing call
```
with:
```csharp
var properties = type.GetProperties( bindingFlags ) // existing call;
var indexProperty = properties.Single(p=>p.IsIndexProperty);
```

Once I have the index property, next step looks like:

```csharp
var nic = new NullabilityInfoContext(); // existing call
var nullabilityInfo = nic.Create(indexProperty);
return nullabilityInfo.ReadState == NullabilityState.Nullable;
```

Which only works for non-generic index properties. Try this on e.g. a `var l = new List<string>()` and it'll happily say that `l[2]` can return null.

### API Proposal

I'm hoping for two things here

- `NullabilityInfoContext.Create(PropertyInfo)` expanded to also assess nullability of generic index properties
- Additional methods on `NullabilityInfo` for methods (and property methods) that lets you query nullability in slightly more natural language.

### API Usage

```csharp
var nic = new NullabilityInfoContext();
var info = nic.Create(propertyInfo for index property, or methodInfo);
```
here `info` with additional members usable like:

```csharp
info.ReturnValue.IsNullable;
info.Parameters[0].IsNullable;
info.Parameters[1].IsNullable;
etc./
```

**Comment by SRNissen** [comment]
...that sure kicks the legs out from under my project, but thank you for letting me know.

**Comment by steveharter** [comment]
> This isn't specific to index properties. Rather, this is because typeof(List<string>) == typeof(List<string?>)

Closing. Nullability works with generic members (including indexer properties) provided the generic type is a value type (either wrapped or not with `Nullable<T>`) but per above, does not support generic reference types due to C# limitations. To help with this, and you own the code, you can constrain the generic parameter to a reference type and use `[MaybeNull]` - see this helpful link: https://endjin.com/blog/2020/07/dotnet-csharp-8-nullable-references-maybenull.

For this section:
> here info with additional members usable like:
>```cs
>info.ReturnValue.IsNullable;
>info.Parameters[0].IsNullable;
>info.Parameters[1].IsNullable;
>etc./
> ```

The "ReturnValue" info can be obtained by using the `Create(ParameterInfo)` method passing in `ReturnParameter`.

Is the proposal to add a `IsNullable` `bool` property? The ReadState\WriteState properties are based on an enum because the value may not be known to be true\false only, so I assume we would throw in the case it is not known? In either case, this is niche and can easily be wrapped through an extension method by the consumer.
