### ISSUE TITLE
Support single-file distribution

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#11201]
This issue tracks progress on the .NET Core 3.0 single-file distribution feature. 
Here's the [design doc](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md) and [staging plan](https://github.com/dotnet/designs/blob/master/accepted/single-file/staging.md) for the feature.

**Comment by JohnNilsson** [comment]
Eliminating reflection would be awesome. So much suffering could be avoided if reflection was banned. My most recent horror story was discovering I couldn’t event move code around because the framework used (service fabric SDK) found it prudent to tie the serialized bytes to the assembly name of the serializer implementation with no override possible.

Any progress towards discouraging reflection would be progress.

Btw was looking for way to merge assemblies to reduce bundle size and load times. I gather this issue isn’t really targeted that.

**Comment by swaroop-sridhar** [comment]
Single-file feature design is in this document: https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md
Tracking progress of single-file apps in this issue: https://github.com/dotnet/runtime/issues/36590.
Thanks to everyone for your feedback and suggestions in this issue.
