### ISSUE TITLE
Representation of function pointer types in the reflection stack

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#11354]
dotnet/csharplang#1951 discusses adding function pointer types to the C# language. The CLR has supported these for a while, but there are areas (such as the reflection stack), where function pointer types are weird/unhandled.

While this will just be a corner area of the C# language, we should probably at least track this:

- [x] Can we fix `ldtoken method explicit instance int32 *(int32)` not to return the token of `System.IntPtr`?
- [ ] Can we use `System.Reflection.Pointer` to reflection invoke methods that take/return function pointers?
- [x] Do we need new APIs to inspect/reflection emit function pointer types?

**Comment by GrabYourPitchforks** [comment]
Sample syntax below - here's a method that takes a function pointer of type `int -> void` as an argument.

```cs
public unsafe static void M(delegate*<int, void> ptr) {
}
```

**Comment by GrabYourPitchforks** [comment]
We should do this for 5.0 since function pointers support is being added imminently.

**Comment by mjsabby** [comment]
I hope the "we should do this for 5.0" still applies and we're tracking this as part of the overall function pointers work.

**Comment by GrabYourPitchforks** [comment]
At the moment it's not currently funded for 5.0 - it's more of a stretch goal. If it's blocking you let us know and we can mark it as such. Then we can pull resources from other things to address it.

**Comment by mjsabby** [comment]
Yeah this is pretty impactful since I'm wanting to freeze these objects and it is not possible to find which are fnptrs arrays. I'm ok if I can work around it somehow but I don't think I'm able to.

**Comment by mjsabby** [comment]
@GrabYourPitchforks I see you self-assigned this, does this mean it'll happen in 5.0?!

**Comment by GrabYourPitchforks** [comment]
Still not funded, but I'm growing increasingly worried that if we don't address it in 5.0 it'll be too difficult to address in 6.0 due to compat. So going to see if we can slam this in at the last minute. It'll definitely be a roller coaster. :)

**Comment by ThadHouse** [comment]
Now that 5.0 has released, and I'm switching my functions that used to take IntPtr to function pointers, I'm running into this issue.

I have the following interface (simplified of course)

```
public interface IThing {
    void Function(delegate* unmanaged[Cdecl]<int, void> cb); // This used to be an IntPtr cb
}
```

I'm generating at runtime using Reflection.Emit an implementation of this interface. However, with function pointers, this does not seem possible. When I iterate the parameters of that function, the parameter just shows up as an IntPtr, with now way to detect its a function pointer. If I generate the function using IntPtr, the signature doesn't match, and the importer fails with a TypeLoadException basically that the interface is not implemented.

**Comment by 333fred** [comment]
@MichalStrehovsky @davidwrighton I've been looking into the roslyn side of this, namely how to encode `typeof(delegate*<void>)` in an attribute argument (https://github.com/dotnet/roslyn/issues/48765). I'm concerned that we have an ambiguity problem with the encoding of types in such attributes that may take a runtime rev to address. 334 II.23.3 defines types as being serialized as follows:

> If the parameter kind is System.Type, (also, the middle line in above diagram) its value is stored as a SerString (as defined in the previous paragraph), representing its canonical name. The canonical name is its full type name, followed optionally by the assembly where it is defined, its version, culture and public -key-token. If the assembly name is omitted, the CLI looks first in the current assembly, and then in the system library (mscorlib); in these two special cases, it is permitted to omit the assembly-name, version, culture and public-key-token.

The issue is that, in this format, there are no keywords, and there is no escaping of type names that _are_ keywords, whereas the metadata format for function pointers uses a number of keywords. For example, take this program (assume that `Attr` is an attribute that has one `Type` argument):

```
class method {}
[Attr(typeof(method))]
class C {}
```

Here, the attribute argument is serialized as just `method`, with no escapes or other content. If we need to serialize function pointers in their metadata format, this suddenly becomes ambiguous: is it a reference to the type `method`, or is it a malformed function pointer definition? This becomes even more insidious if you consider the following program:

```cs
class cdecl {}
[Attr(typeof(delegate* unmanaged<cdecl>))]
class C {}
```

Without escapes, that would get serialized as `method unmanaged cdecl*()`, which is completely incomprehensible.

It feels to me like we might need to define a new serialization format for attribute typeofs in order to deal with these issues, potentially communicated on both the part of an individual assembly and on the part of the runtime. IE, the runtime adds a new flag for "supports escapes in typeof", and we add an attribute to a module when it's compiled in the new format, so that reflection and the compiler can both correctly understand the format of attribute type names.

**Comment by MSDN-WhiteKnight** [comment]
>so it would be worth checking whether C++/CLI already solved the problem for us.

It didn't solve. The code like this:

```
using namespace System;

typedef int(*PFUNC)(int);

public ref class MyAttrAttribute : public Attribute {
public:
	MyAttrAttribute(Type^ t) {

	}
};

[MyAttr(PFUNC::typeid)]
public ref class TestClass {

};
```
is compiled into the following IL:

```
  .custom instance void MyAttrAttribute::.ctor(class [mscorlib]System.Type) = ( 01 00 5B 53 79 73 74 65 6D 2E 49 6E 74 50 74 72   // ..[System.IntPtr
				2A 2C 20 6D 73 63 6F 72 6C 69 62 2C 20 56 65 72   // *, mscorlib, Ver
				73 69 6F 6E 3D 34 2E 30 2E 30 2E 30 2C 20 43 75   // sion=4.0.0.0, Cu
				6C 74 75 72 65 3D 6E 65 75 74 72 61 6C 2C 20 50   // lture=neutral, P
				75 62 6C 69 63 4B 65 79 54 6F 6B 65 6E 3D 62 37   // ublicKeyToken=b7
```

The C++/CLI compiler just substitutes function pointers with IntPtr types for attribute arguments

**Comment by MSDN-WhiteKnight** [comment]
How the reflection API to represent function pointers information should look like? I think there are two options:

1. Create new `Signature` type, that would contain information about calling convention, return type and parameter types
2. Use the existing `MethodInfo` type, and return the special dummy instances that would support CallingConvention, GetParameters and ReturnType, but have any other members no-op or throwing NotSupportedException.

The first looks more pleasant, but with second more existing code operating on MethodInfo could be reused.

**Comment by MichalStrehovsky** [comment]
One immediate problem with calling conventions is that we decided to encode them as modifiers going forward, but modifiers tend to disappear as reflection stack handles them.

In particular:

https://github.com/dotnet/runtime/blob/ead035b1774e91b871929b74a00726b6b9d23025/src/tests/reflection/ldtoken/modifiers.il#L12-L19

They disappear when we do LDTOKEN.

We'll need some special rules if we want to preserve that in `typeof` for function pointers. We are going to break compat in that direction anyway (since they're all loaded as IntPtr right now), but there might be other places that rely on modopts disappearing.

**Comment by jkotas** [comment]
CoreCLR and Mono reflection stacks represent function pointers differently today. For examle, `Console.WriteLine(typeof(delegate*<int>).FullName)` prints `System.IntPtr` on CoreCLR vs. `System.MonoFNPtrFakeClass` on Mono. That's also something that has to be unified to fix this issue.

**Comment by steveharter** [comment]
Moving to 8.0; we need to update the API and design based on feedback from https://github.com/dotnet/runtime/pull/71516.

**Comment by AndyAyersMS** [comment]
FWIW the jit currently mis-optimizes some cases involving function type comparison. 

The fix is in https://github.com/dotnet/runtime/pull/72136 where the jit will defer to the runtime to decide what sort of optimizations can apply. If/when the runtime type for function pointers changes those new bits of jit interface can potentially be revised to enable a little more optimization.

**Comment by jkotas** [comment]
> System.InvalidCastException: Unable to cast object of type 'ILCompiler.DependencyAnalysis.ConstructedEETypeNode' to type 'Internal.TypeSystem.TypeDesc'.

This error means that the result of `embed{Generic}Handle` is being used `CORINFO_CLASS_HANDLE`. You can get away with this with JIT since the two are identical pointers, but you cannot get away with this in AOT where the two are different pointers: One is a type handle and the other is a symbol in the AOT image.

**Comment by AndyAyersMS** [comment]
[Above is for the failure in #72136] -- looks like the jit IR holds onto the "compile time handle" but VN doesn't know how to get to this from the embedded handle. Think I can just build a map.

**Comment by IllidanS4** [comment]
What's the status of this? I hope `Type.GetFunctionPointerReturnType`, `Type.GetFunctionPointerParameterTypes` and `Type.MakeFunctionPointerType` will finally be possible, to that the full CLI type system can finally be expressible using reflection and emit (well, except for modopts and modreqs I guess).

**Comment by steveharter** [comment]
Closing; implemented in https://github.com/dotnet/runtime/pull/81006
