### ISSUE TITLE
Folding LoadAlignedVector* into the consumer instructions with VEX-encoding

### ISSUE THREAD

**Issue by fiigii** [dotnet/runtime#11592]
Currently, `LoadVector128/256` can be folded into its consumer instructions with VEX-encoding but  `LoadAlignedVector128/256` not. 
`LoadAlignedVector128/256` would throw hardware exceptions if the memory address is not aligned to the specific boundary, but other VEX-encoded instructions (e.g., `vaddps xmm0, xmm1, [unalignedAddr]`) can work with unaligned memory. So, actually, we can fold `LoadAlignedVector128/256` into its consumer instructions with VEX-encoding.
```asm
;;; unoptimized
vmovaps xmm0, [unalignedAddr]  ;;; hardware exception
vaddps xmm0, xmm1, xmm0

;;; optimized
vaddps xmm0, xmm1, [unalignedAddr]  ;;; ok
```

All the mainstream C/C++ compilers have this behavior. 

@CarolEidt @tannergooding @mikedn 

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Sounds like we decided not to implement this; closing.

**Comment by tannergooding** [comment]
We actually did end up deciding to implement this and it was resolved.

Effectively, we will fold `LoadAlignedVector*` when using the legacy encoding (as instructions take and enforce alignment). We will likewise fold such instructions under the VEX encoding when optimizations are enabled (even though instructions no longer enforce alignment).

This was done rather than exposing some alternative `Load` API that was explicitly unsafe and has a presumption that tiering and tests will help catch most incorrect usages.
