### ISSUE TITLE
What is the correct way to use ECDiffieHellman in netstandard2.0?

### ISSUE THREAD

**Issue by SteveSyfuhs** [dotnet/runtime#1172]
Alternate title: support netstandard2.1 in Framework. 😇

I need the current ECDH API available in 2.0 so it can be used by Framework. The application relying on this won't be migrated any time soon. According to https://github.com/dotnet/corefx/issues/8158 there was a brief consideration for adding support and then it was moved into 2.1, presumably for good reason.

Given that, is there a correct way to handle this within a 2.0 library?

**Comment by GrabYourPitchforks** [comment]
At the moment the easiest way would be to cross-compile between Full Framework and another framework (netcoreapp or netstandard). However, if you don't want to do this, you could use _public_ reflection to access the `ECDiffieHellman` class since the APIs are public and documented. If you go this route you'd want to be careful that you always specify the full signature of the method you're trying to invoke, otherwise your library could break if public overloads are added in a future release.

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
