### ISSUE TITLE
Allows setting of 4 spaces indentation or 2 spaces indentation in JsonSerializerOptions.

### ISSUE THREAD

**Issue by KumoKyaku** [dotnet/runtime#1174]
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L15

**Comment by ahsonkhan** [comment]
@KumoKyaku - is this customization required/blocking some scenario or is it just nice to have? Also, are there other "formatting" customization that you would need other than just the 2 spaces vs 4?

To me, since such customization affects the entire JSON stack (serialization and writer), I don't see it worth the potential perf cost, at least on its own. It would help to understand the reason behind such an ask.

**Comment by KumoKyaku** [comment]
Just 4 spaces are easier to read than 2 spaces。

**Comment by DaZombieKiller** [comment]
Wouldn't it be better to offer something more like this?
```cs
public partial class JsonSerializerOptions
{
    /// <summary>The number of spaces to write per indentation level when <see cref="WriteIndented" /> is enabled.</summary>
    public int IndentSpaces { get; set; }
}
```

**Comment by ahsonkhan** [comment]
> Wouldn't it be better to offer something more like this?

Agreed. Newtonsoft.Json exposes something like this as well.
https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonTextWriter_Indentation.htm

It also exposes capabilities to customize what char to use (i.e. could use tabs if needed):
https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonTextWriter_IndentChar.htm

That said, I don't yet see enough evidence that such customization is common enough or necessary for the built-in JSON API which focuses more on perf and most important features over providing all sorts of customizations. To me, this particular request falls in the camp of "keep using Newtonsoft.Json if such a feature/capability is important to your use case", because it isn't worth the trade-off considering the design goals.

**Comment by layomia** [comment]
Closing - we don't want to add complexity to the writer to support this feature.
