### ISSUE TITLE
Why does DisablePrivateReflection attribute not work on .net core 2.1, but works perfectly on .net core 2.0?

### ISSUE THREAD

**Issue by dalekseev-monokot** [dotnet/runtime#11811]
Hello!

Why does `DisablePrivateReflection` attribute not work on .net core 2.1, but works perfectly on .net core 2.0?

I have a class with private fields. The class is in assembly marked with a `DisablePrivateReflection` attribute.

The following test will be passed successfully on .net core 2.0

```csharp
var field = typeof(MonLicenseManager).GetField("_licenses", BindingFlags.NonPublic | 
BindingFlags.Static);

Assert.IsNotNull(field);

try
{
    var value = field.GetValue(null);
    Assert.Fail("FieldAccessException must be thrown");
}
catch (FieldAccessException)
{

}
```

but on .net core 2.1, `FieldAccessException` will never be thrown

Thanks

**Comment by GrabYourPitchforks** [comment]
Looks like we've now gone two major releases (2.1, 3.x) without this functionality. Is there any plan to resurrect it for 5.0?

**Comment by MichalStrehovsky** [comment]
This attribute is interesting for two reasons:

* Size optimizations: e.g. IL Linker can safely strip names and attributes on things without having to worry that it might change semantics compared to the state before linking (modulo things like stack traces). We could even give non-generic types/members `compilercontrolled` visibility (i.e. members are referred to by tokens, not by names where we don't even have to bother generating short unique names for them). Cc @marek-safar, @vitek-karas 
* Codegen optimization: none of the top-down codegen optimizations (the ones where in optimizing callee we assume we know values of parameters at all callsites) are safe to do in .NET because reflection allows calling anything with any values. When reflection is out of picture, these optimizations are safe. I know WASM has to do these illegal optimization to get size down (knowledge about parameters that are never passed as null). These optimizations would be safe when (at least the private) reflection can be disallowed and this is enforced by all runtimes. Cc @vargaz @AndyAyersMS @erozenfeld

**Comment by marek-safar** [comment]
I think it'd be useful to fix DisablePrivateReflectionAttribute to work the way that it provides better dev experience when something unexpectedly calls member via reflection.

**Comment by steveharter** [comment]
Moving to future due to priority + scheduling reasons.

**Comment by GrabYourPitchforks** [comment]
If punted, we will have gone __three__ major releases (2.1, 3.1, 5.0) without this functionality. I don't really see many people clamoring to bring this back. If we're unlikely ever to bring it back I'd rather close the issue (and obsolete the type) rather than continue punting.

**Comment by jkotas** [comment]
I believe that the linker annotations that we investing into are a better approach for taming reflection use. I agree that it is not worth spending time on `DisablePrivateReflection`.

**Comment by steveharter** [comment]
Agree. Closing.

**Comment by MichalStrehovsky** [comment]
> Agree. Closing.

Do we have an issue tracking updating documentation?

**Comment by GrabYourPitchforks** [comment]
Opened https://github.com/dotnet/dotnet-api-docs/issues/4646 to track.
