### ISSUE TITLE
Compile C++ with “/d2FH4” flag on Windows x64?

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#12230]
From https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/ meant to reduce exception handling code; not sure how the runtime works though?

**Comment by jkotas** [comment]
This is on by default in Visual Studio 2019 Update 3+ that we are building .NET 5 with.

You can tell that it is really working because of we are started getting crashes with the FrameHandler4 symbol on the stack https://github.com/dotnet/runtime/search?q=FrameHandler4&type=Issues . It used to be FrameHandle3 before...
