### ISSUE TITLE
Publish archived coreclr test assets onto the dotnet feed for Mono consumption

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#12471]
We should create an archive with the coreclr test assets and publish it onto the blob storage feed same as we did for the corefx tests.

From @RussKeldorph:

> Note that several CoreCLR tests have native components, and even the managed components of some build differently depending on the platform.  Not sure how interesting those tests are for this exercise, but FYI in case that’s a problem CoreFX didn’t have to solve.

cc @marek-safar @danmosemsft @jkotas

**Comment by trylek** [comment]
@ViktorHofer - do you think this is still relevant in the composite repo? I would assume that we no longer need any dotnet feed for Mono consumption as it can directly pull down arbitrary CoreCLR test build artifacts from the Azure DevOps storage. A related but technically independent consideration is that we should move the CoreCLR tests under a common location like tests/runtime so that they can be easily shared between CoreCLR and Mono.

**Comment by jkotas** [comment]
Right, this is no longer needed.

**Comment by trylek** [comment]
Thanks Jan for your immediate response, I'll close the corresponding infra backlog item in TFS.
