### ISSUE TITLE
ildasm has to run by full path

### ISSUE THREAD

**Issue by quantrpeter** [dotnet/runtime#12690]
Hi
   I successfully built coreclr and added bin/Product/OSX.x64.Debug to $PATH in mac. But when i execute ildasm, i got segmentation fault. If i execute by full path, it works. Why?

If i get into the powershell in mac by command "pwsh", then execute ildasm, it works again, so wried.

```
/Users/peter/workspace/hostclr>which ildasm
/Users/peter/workspace/coreclr/bin/Product/OSX.x64.Debug/ildasm
/Users/peter/workspace/hostclr>ildasm
Segmentation fault: 11
/Users/peter/workspace/hostclr>/Users/peter/workspace/coreclr/bin/Product/OSX.x64.Debug/ildasm
Usage: ildasm [options] <file_name> [options]

Options for output redirection:
  /OUT=<file name>    Direct output to file rather than to console.
[Undefined resource string ID:0xCC]  /HTML               Output in HTML format (valid with /OUT option only).
  /RTF                Output in rich text format (valid with /OUT option only).
Options for file/console output:
  /BYTES              Show actual bytes (in hex) as instruction comments.
  /RAWEH              Show exception handling clauses in raw form.
  /TOKENS             Show metadata tokens of classes and members.
  /SOURCE             Show original source lines as comments.
  /PRETTY             This option is obsolete and no longer supported.
  /LINENUM            Include references to original source lines.
  /VISIBILITY=<vis>[+<vis>...]    Only disassemble the items with specified
          visibility. (<vis> = PUB | PRI | FAM | ASM | FAA | FOA | PSC)
  /PUBONLY            Only disassemble the public items (same as /VIS=PUB).
  /QUOTEALLNAMES      Include all names into single quotes.
  /NOCA               Suppress output of custom attributes.
  /CAVERBAL           Output CA blobs in verbal form (default - in binary form).
[Undefined resource string ID:0xDC]The following options are valid for file/console output only:
Options for EXE and DLL files:
  /UTF8               Use UTF-8 encoding for output (default - ANSI).
  /UNICODE            Use UNICODE encoding for output.
  /NOIL               Suppress IL assembler code output.
  /FORWARD            Use forward class declaration.
  /TYPELIST           Output full list of types (to preserve type ordering in round-trip).
  /PROJECT            Display .NET projection view if input is a .winmd file.
  /HEADERS            Include file headers information in the output.
  /ITEM=<class>[::<method>[(<sig>)]  Disassemble the specified item only

  /STATS              Include statistics on the image.
  /CLASSLIST          Include list of classes defined in the module.
  /ALL                Combination of /HEADER,/BYTES,/STATS,/CLASSLIST,/TOKENS

  /METADATA[=<specifier>] Show MetaData, where <specifier> is:
          MDHEADER    Show MetaData header information and sizes.
          HEX         Show more things in hex as well as words.
          CSV         Show the record counts and heap sizes.
          UNREX       Show unresolved externals.
          SCHEMA      Show the MetaData header and schema information.
          RAW         Show the raw MetaData tables.
          HEAPS       Show the raw heaps.
          VALIDATE    Validate the consistency of the metadata.

Option key is '-' or '/', options are recognized by first 3 characters

Example:  ildasm /tok /byt myfile.exe /out=myfile.il
```

Thanks

**Comment by BruceForstall** [comment]
This happens for ilasm, ildasm, superpmi, mcs, and crossgen (although crossgen has a slightly different failure mode). It happens on Linux as well as Mac. Essentially, it happens for every tool that uses the PAL that starts with `PAL_Initialize(argc,argv)`, where the program itself it specified as just a name, e.g. `ilasm`, without a path. This seems to happen because `INIT_ConvertEXEPath` early outs if there is no path component.

Then, the PAL has lots of problems because it tries to print an error message but not enough of the PAL is initialized (apparently), so a flood of nested exceptions occurs.

@janvorli

**Comment by janvorli** [comment]
Let's fix it. I didn't know about this problem, I've probably always lauched these tools using full path.

**Comment by ivanpovazan** [comment]
The troubling line is at:
https://github.com/dotnet/runtime/blob/464508b9d15371b1a972de34b428b3e9ed6181b1/src/coreclr/src/pal/src/init/pal.cpp#L1293

_My two cents_: 
I am not sure why that check is necessary, but retrieving full path with _realpath_ seems to solve the issue.

**Comment by janvorli** [comment]
`realpath` alone is not reliable in case the executable was started using execve, because in that case, the caller can set the argv[0] to something that is not resolvable by the realpath. For example, it might contain just the app filename without the path and the full path to the app might not be in the PATH env var or pwd.
So the proper fix is to extract the absolute path of the current executable in the PAL_Initialize the same way we do that here:
https://github.com/dotnet/runtime/blob/9bb997bfa110b98d17a0ed7fe5a9f163072f36a3/src/coreclr/src/hosts/unixcoreruncommon/coreruncommon.cpp#L60
