### ISSUE TITLE
System.Double.Equals() returns true when `==` returns false

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#1285]
The `double` type has several forms for `NaN`. When I contrive two such values into `double` values as shown below, I see that `==` returns `false` between these two values even though `Equals` returns `true`.

```cs
double nan1, nan2;
*(ulong*)&nan1 = 0xFFF8000000000001;
*(ulong*)&nan2 = 0xFFF8000000000002;
this.Logger.WriteLine("double.IsNaN(nan1): {0}", double.IsNaN(nan1));
this.Logger.WriteLine("double.IsNaN(nan2): {0}", double.IsNaN(nan2));
this.Logger.WriteLine("nan1 == nan2: {0}", nan1 == nan2);
this.Logger.WriteLine("nan1.Equals(nan2): {0}", nan1.Equals(nan2));
this.Logger.WriteLine("nan1.GetHashCode(): {0}", nan1.GetHashCode());
this.Logger.WriteLine("nan2.GetHashCode(): {0}", nan2.GetHashCode());
```

**Output**:
```
double.IsNaN(nan1): True
double.IsNaN(nan2): True
nan1 == nan2: False
nan1.Equals(nan2): True
nan1.GetHashCode(): 2146435072
nan2.GetHashCode(): 2146435072
```

**Comment by GrabYourPitchforks** [comment]
@tannergooding do you have any thoughts on this?

[Per MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.double.equals), this disparity between `Equals` and `operator ==` appears to be intentional, but it does strike me as very strange. Perhaps the Framework required that all primitive types be `object.Equals` equal to themselves otherwise things would fall over dead?

> If two Double.NaN values are tested for equality by calling the Equals method, the method returns true. However, if two NaN values are tested for equality by using the equality operator, the operator returns false. When you want to determine whether the value of a Double is not a number (NaN), an alternative is to call the IsNaN method.

**Comment by AArnott** [comment]
Similar problem with `float` when initialized like this:

```cs
float nan1, nan2;
*(uint*)&nan1 = 0xFFC00001;
*(uint*)&nan2 = 0xFF800001;
```

**Comment by AArnott** [comment]
Feel free to close if this is by design.

**Comment by tannergooding** [comment]
This is by design and has been this way since v1 of the framework.

The equality operator (`==`) implements IEEE compliant equality. This means `x == x`, `+0 == -0` and `NaN != NaN`

The Equals method implements .NET value equality treating `x == x`, `+0 == -0`, and `NaN == NaN` (regardless of internal NaN representation).

Having `Equals` implement `NaN == NaN` is important as basic equality and hashing operations would otherwise fail (and we wouldn't be meeting their .NET implementation contracts).
