### ISSUE TITLE
Performance regression: DateTime.UtcNow and DateTimeOffset.UtcNow 2.5x slower

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#13091]
`DateTime.UtcNow` and `DateTimeOffset.UtcNow` are 2.5x slower compared to 2.2

```cs
[Benchmark]
public DateTimeOffset GetUtcNow() => DateTimeOffset.UtcNow;

[Benchmark]
public DateTime GetUtcNow() => DateTime.UtcNow;
```

Repro

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
# if you don't have cli installed and want python script to download the latest cli for you
py .\scripts\benchmarks_ci.py -f netcoreapp2.2 netcoreapp3.0 --filter *GetUtcNow*
# if you do
dotnet run -p .\src\benchmarks\micro\MicroBenchmarks.csproj -c Release -f netcoreapp2.2 --filter *GetUtcNow* --runtimes netcoreapp2.2 netcoreapp3.0 --join
```

```ini
BenchmarkDotNet=v0.11.3.1003-nightly, OS=Windows 10.0.18362
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview8-013262
   [Host]     : .NET Core 2.2.6 (CoreCLR 4.6.27817.03, CoreFX 4.6.27818.02), 64bit RyuJIT
   Job-BYJCMJ : .NET Core 2.2.6 (CoreCLR 4.6.27817.03, CoreFX 4.6.27818.02), 64bit RyuJIT
   Job-JSSCYO : .NET Core 3.0.0-preview8-27916-02 (CoreCLR 4.700.19.36302, CoreFX 4.700.19.36514), 64bit RyuJIT
```

|                Type |    Method |     Toolchain |     Mean |
|-------------------- |---------- |-------------- |---------:|
|       Perf_DateTime | GetUtcNow | netcoreapp2.2 | 25.12 ns |
|       Perf_DateTime | GetUtcNow | netcoreapp3.0 | 70.91 ns |
|                     |           |               |          |
| Perf_DateTimeOffset | GetUtcNow | netcoreapp2.2 | 38.19 ns |
| Perf_DateTimeOffset | GetUtcNow | netcoreapp3.0 | 91.96 ns |

/cc @danmosemsft

**Comment by GrabYourPitchforks** [comment]
@adamsitnik @DrewScoggins Heads up, as soon as your perf infrastructure takes https://github.com/dotnet/runtime/commit/eed3c7642ada205a4645dc3153fcb4c3c04c363c you'll see the `DateTime.UtcNow` benchmarks change. Here's what you should expect:

* On non-Windows platforms, no change
* On Win8 and earlier, no change
* On Win10, an improvement

If you see any change at all (good or bad) on non-Win10 platforms, let us know so that we can double-check that we didn't inadvertently change these code paths.

If you see a regression on Win10, let us know because it probably means we have a problem in our caching logic. (A cache miss in this logic is very expensive, but they should happen so infrequently that they shouldn't show up at all in benchmarks.)

**Comment by stephentoub** [comment]
>  A cache miss in this logic is very expensive

How expensive?

**Comment by GrabYourPitchforks** [comment]
> How expensive?

Best guess, probably 6x - 7x the cost of a cache hit?

**Comment by stephentoub** [comment]
Ok, so relatively very expensive rather than absolutely very expensive.  Cool.
