### ISSUE TITLE
Wrong order of the day names in Slovak language

### ISSUE THREAD

**Issue by janbodnar** [dotnet/runtime#1322]
# Wrong order of the day names in Slovak language

The `CultureInfo.DateTimeFormat.DayNames` gives a slightly incorrect list of the the day names in Slovak. In our culture, the days start with monday, not sunday.

The output is:

nedeľa
pondelok
utorok
streda
štvrtok
piatok
sobota

The correct output should be:

pondelok
utorok
streda
štvrtok
piatok
sobota
nedeľa

# General

OS: Windows 10
> dotnet --version
3.1.100

```
using System;
using System.Globalization;

namespace DayNames
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.OutputEncoding = System.Text.Encoding.UTF8;

            var skSk = new CultureInfo("sk-SK");

            foreach (var dayName in skSk.DateTimeFormat.DayNames)
            {
                Console.WriteLine(dayName);
            }
        }
    }
}
```

**Comment by scalablecory** [comment]
@tarekgh

**Comment by Clockwork-Muse** [comment]
This is an artifact of the fact that `DayOfWeek` is Sunday-first, whereas Slovakia (and pretty much every other country) uses the ISO-standard Monday-first.  Day-of-week names are correctly correlated to the real day-of-week:

```csharp
using System;
using System.Globalization;

namespace DayNames
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.OutputEncoding = System.Text.Encoding.UTF8;

            var skSk = new CultureInfo("sk-SK");

            for(var today = new DateTime(2020, 1, 6); today < new DateTime(2020, 1, 13); today = today.AddDays(1))
            {
                Console.WriteLine(today.ToString("yyyy-MM-dd - dddd", skSk.DateTimeFormat));
            }
        }
    }
}
```
... outputs the expected:
```
2020-01-06 - pondelok
2020-01-07 - utorok
2020-01-08 - streda
2020-01-09 - štvrtok
2020-01-10 - piatok
2020-01-11 - sobota
2020-01-12 - nedeľa
```

<hr />

What this means, though, is that **all** cultures have the same issue: Spain, for example, shows the same "problem":

```
domingo - Sunday
lunes
martes
miércoles
jueves
viernes
sábado
```

This is likely being reported because [the remarks for the property](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.daynames?view=netcore-3.1#remarks) state:

> The first element (the element at index zero) represents the first day of the week in the calendar defined by the Calendar property.

...whereas the item at index zero is presumably actually based on the constants in `DayOfWeek`.

**Comment by tarekgh** [comment]
@Clockwork-Muse is correct. DayNames always start with Sunday. This is the behavior of the .NET since day1. 

I have created https://github.com/dotnet/docs/issues/16558 to fix the doc issue.
