### ISSUE TITLE
Can't run tests from VS using Microsoft.DotNet.CoreSetup.sln

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#1323]
Fully building everything, even running installer tests from command line. Then opening the solution via: `installer.cmd -vs src\installer\Microsoft.DotNet.CoreSetup.sln`.

The test explorer can see all the tests, but trying to run them fails with: 
```
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0-alpha.1.19564.1' was not found.
```

The `DOTNET_ROOT` is set to testhost which only has version `5.0.0`.

This seems to be a test build problem in a way because when I try to run the `System.Net.Http.UnitTests` from VS it works. Looking at the two tests binaries, the CoreSetup ones (for example `HostActivation.Tests`) has its `.runtimeconfig.json` containing framework reference to `5.0.0-alpha.1.19564.1`. But the `System.Net.Http.UnitTests` has its framework reference set to `5.0.0`.

This worked couple of weeks ago, but I have no idea what changed since.

**Comment by safern** [comment]
We manually set `RuntimeFramework` to `ProductVersion` to make it easy whenever we rebrand to a new ProductVersion, so that the runtimeconfig.json file points to that version:

https://github.com/dotnet/runtime/blob/6a991f211f8a1c70f0fae4fcbd073ab9086bd0ee/eng/testing/runtimeConfiguration.targets#L42

Should the installer tests use these targets to also populate the `runtimeconfig.json` with the right framework version? 

It seems like installer `Directory.Build.targets` sets ProductVersion to include the suffix: https://github.com/dotnet/runtime/blob/bd6c81a944f609b88908864827b7797c6b127c5b/src/installer/Directory.Build.targets#L46

Maybe the tests should just point to the stable `ProductVersion` without the suffix? 

For context, we set `ProductVersion` for the repo here: 
https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/Versions.props#L4

**Comment by ViktorHofer** [comment]
cc @dagood

**Comment by dagood** [comment]
In installer, `ProductVersion` simply means the version of the product we're building, which includes the prerelease suffix. I'm not sure why it would be the stable version or how that would work. Does libraries set up a fake sharedfx with a stable version, something like that?

**Comment by dagood** [comment]
It looks like CoreFX got its notion of `ProductVersion` in https://github.com/dotnet/corefx/pull/35436. These appear to be unrelated properties with the same name.

**Comment by vitek-karas** [comment]
Turns out we actually don't want to/need to run the hosting tests on the live-build. The tests are different from other Libraries/Runtime tests. The test itself is just some C# which prepares the environment and then it invokes the live-built hosting components/runtime in a separate process. The non-hosting tests in this solution (bundler and extension packages) also don't have to run on live-built runtime since they are very similar.

We might want to run everything on live-built runtime, but it's not necessary for these tests and doesn't really bring much value (other than dogfooding like validation really).

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/runtime/pull/1525
