### ISSUE TITLE
Proposal: Run WASM on CLR

### ISSUE THREAD

**Issue by gulshan** [dotnet/runtime#13300]
There was some effort to run .net on WASM in browsers. Some effort was on the MONO and some was in CoreRT. But this proposal is not that. This is about running WASM on CLR or on .net. Then WASM modules can be treated as .net assemblies and .net assemblies can reference WASM modules. And this should not be like P/Invoke, where the calling interface has to be defined again in the .net side. Some supporting points-

- WASM is kind of the ultimate assembly language, every other languages is trying to compile it to WASM.
- WASM modules are like libraries and not executable programs, which makes it platform agnostic.
- WASM is designed to run on (JS) runtimes. So it can made to run a runtime like CLR.
- WASM is still low level.
- WASM v1 is minimal, but still manages to cover a lot.
- Also it may help development of Blazor.

So, I think CLR can look into running WASM itself.

**Comment by danmosemsft** [comment]
@jkotas is this contemplated?

**Comment by jkotas** [comment]
We have no plans in foreseeable future to have a wasm runtime built-in into .NET Runtime. 

NuGet packages like https://www.nuget.org/packages/WebAssembly that wrap native wasm runtimes and expose it as .NET APIs are the right way to do this.

**Comment by ReubenBond** [comment]
The [WebAssembly](https://www.nuget.org/packages/WebAssembly) package maps WASM instructions to IL, rather than wrapping an existing runtime. There are two packages that I know of which do wrap a native WASM runtime:

* https://www.nuget.org/packages/Wasmtime/ for https://wasmtime.dev/
* https://www.nuget.org/packages/WasmerSharp/ for https://wasmer.io/
