### ISSUE TITLE
superpmi: Add SuperPMI asm diff CI job

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#13319]
category:testing
theme:super-pmi
skill-level:intermediate
cost:large

**Comment by BruceForstall** [comment]
With our current system, where we have rolling JIT builds and automated SuperPMI collections on all platforms, it would be relatively easy to add an AzDO job that just runs "superpmi.py asmdiffs" on all platforms. However, actually seeing the resulting diffs is most of the value, and extracting the diffs from the run in a simple way might be difficult. You might also want to automatically post the jit-analyze results back to the triggering PR, but that has proven in the past to be difficult due to security concerns about permissions to post back to GitHub.

**Comment by BruceForstall** [comment]
Implemented with https://github.com/dotnet/runtime/pull/61335
