### ISSUE TITLE
Build a Windows 7 compatible Single-file AppHost

### ISSUE THREAD

**Issue by BrainSlugs83** [dotnet/runtime#13356]
# General

With .NET Core 3.0-preview8 -- I compiled a standalone exe for Windows 7 (x86) RID using the following command:
`dotnet publish -c Release -r win7-x86 -o .\bin\Redist\windows /p:PublishSingleFile=true /p:PublishTrimmed=true /p:DebugType=None`

This produces a single .exe file output that runs fine on Windows 10 (x64).

But when I copy this .exe file to a Windows 7 Home Basic (x86) machine, I get the following error message when trying to run it:
```
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```
According to this issue: https://github.com/dotnet/core-setup/issues/3220 it looks like this external dependency is possibly the "Windows Universal C Runtime", which can be found at this location: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

There does appear to be a download link for Windows 7 (x86), but when you try to install it on said operating system, you get the following message: `The update is not applicable to your computer.` -- This leads me to believe that it is impossible to run my app on Windows 7 (x86).

# Expected Behavior:
 - My app runs on Windows 7 (x86) without having to install anything that does not ship with
   the OS. (Many Corporate and Enterprise environments do not have the ability to install
   random service packs on their machines without significant IT involvement and overhead.)
    - Also, I'd like to avoid dependency issues, e.g. if a user has the wrong version installed, etc.

 - If I do have to install some random service pack, tell me about it and where to download it
   instead of a random missing dll notice, as that's a disaster waiting to happen.  (A non-technical
   user might just google the error message and follow some youtube video's instructions to
   download random .dll files from untrusted sites and dump them into the app's folder!)

# Other thoughts
 - This isn't that tall of an ask.  We wrote GUI software for Windows 7 with MinGW 20 years ago,
    and it never required any c runtime dlls; everything was statically linkable. (And never more
    than 2 MB) -- This is literally just a console app -- if there is some external dependency, just 
    link it into the executable already! 😑

**Comment by BinToss** [comment]
It seems the C runtime would need to be statically linked in the CLR App Host.

When building and publishing a SingleFile executable that targets win7-x86, win7-x64, win-x86, or win-x64, the IL Linker will need to crawl to find and extract code references from the C Runtime that are not available out-of-the-box on Windows 7 SP1. A not-so-insignificant amount of time would need to be spent to create the logic necessary for the crawl to know what is and isn't available on a factory-fresh Windows 7 SP1 install.

Solution A: Extract C Runtime assembly references and inject them into the CLR App Host during Compile/ILLink time

Solution B: Instead of injecting the C Runtime references into the App Host, inject them into a wrapper assembly. The wrapper assembly would contain and run the extracted (or generated) C Runtime references alongside the code normally used to run a SingleFile App Host. The resulting executable would be an objectively messy amalgamation that (hopefully) works.
```
non-SingleFile App Host ->
wrapper assembly with injected/generated C Runtime and SingleFile-equivalent functionality ->
developer's root assembly.
```

Solution C: Update Windows 7 SP1 images to have the the C Runtime preinstalled and distribute it via Windows Update to preexisting clients. Easier said than done, I know—Especially so since the OS is being sunsetted.

Non-Solution D: Drop support for Windows 7 SP1. It would be a shame, but it would also prevent a lot of headaches. Who knows? Maybe a community-supported win7 image could arise that alleviates issues stemming from the Operating System's age and under-the-hood mess right before the heat death of universe is observed.

**Comment by BinToss** [comment]
This may have been resolved by 
- https://github.com/dotnet/runtime/pull/63196

Two related pull requests are awaiting review in dotnet/sdk
- https://github.com/dotnet/sdk/pull/23336
- https://github.com/dotnet/sdk/pull/23177

**Comment by NN---** [comment]
Merged today 🥳
