### ISSUE TITLE
Consider generating R2R interop stubs

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#13389]
About 1/3 of WinForms startup time (when everything is R2R) is JITing and most of that is interop stubs. Given that ILC is able to generate interop IL for many cases, consider enabling stub generation where possible. This might require a stable API for R2R P/Invoke transitions.

**Comment by trylek** [comment]
@MichalStrehovsky - could you please comment on this very old work item? Based on tons of your work on implementing AOT interop stubs I'm inclined to believe we should be ready to close this item but I need your confirmation in this regard.

**Comment by MichalStrehovsky** [comment]
We pregenerate p/invoke stubs for everything that was considered reasonable to do marshalling for in crossgen2.

I'm not sure how much that helps WinForms, since WinForms uses the weirdest marshallers. But Jeremy Kuhne has been chipping away on dumb interop in WinForms and making it saner, and we also have the source generators coming. The future looks bright. We can open new bugs if there's something specific.
