### ISSUE TITLE
There's no way to call native library resolution on a specific AssemblyLoadContext

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#13472]
Currently it's possible to create a "chain" of `AssemblyLoadContext` instances such that there's a `ParentALC` and `ChildALC`. `ChildALC` has a reference to `ParentALC` and every time the `ChildALC.Load` is called, if it can't resolve the assembly it falls back to parent by calling `ParentALC.LoadFromAssemblyName` (which will in turn call `ParentALC.Load` and so on).

It is not possible to do the same for native library resolution. While the child can overload `ChildALC.LoadUnmanagedDll`, there's no API it can call on the `ParentALC` to fall back to its native library resolution. There might be some workarounds using contextual reflection and `NativeLibrary` but that would be rather tricky and absolutely non-discoverable.

Given the current API design, it would probably be cleaner to add a new API to `NativeLibrary`  - something like `IntPtr NativeLibrary.Load(string libraryName, AssemblyLoadContext context)`. Or alternatively expose something similar on the ALC itself.

**Comment by John0King** [comment]
anyone  hits  the Managed Assemblies's Alc across issue ;
in my library https://github.com/John0King/LazyMan.ModularLoader,  I want to side load the whole web site as subapp , then I facing this Assemblies's Alc **across** issue,
it too complex， that I can not reproduce this issue simple,  but when you use my lib to run, there are at least 98% web app will crash.

a little explain:  (this is after a long time debug)

1.  all `Microsoft.AspNetCore.App` assemblies is load in default ALC  by *default* , in this case my lib works
2.  if you reference/separate to multiple class library (such as DTO, model, service layer), then some of the `Microsoft.AspNetCore.App` assemblies will in web app's local folder, so  those `.dll` well load in `pluginAlc` , notice: not all  will copy to local folder.
3. anything you call in your primary dll (from pluginAlc) is ok, but  remember the powerfull of DI in asp.net core.  many configuration call is in  `Microsoft.AspNetCore.App` 's assemblise,  so the issue happend. 
4. (such as `Microsoft.Extensions.DependencyInject.Abstraction.dll`  in pluginAlc , let's called p_core.dll for shot , and  `core.dll`  for those in default alc)   because p_core.dll is in  pluginAlc,  and some  DI configure call in   default alc,  ,  now `core.dll` call will looking `p_core.dll` 's class in default alc,  that cause `MethodNotFoundException` 


------------

#### why not load everything in pluginAlc？
I can't , because the `AssemblyDependencyResolver` can not located  the `core.dll` 

#### why not load all `core.dll` in default Alc?
I can't by default , because it in the `.deps.json` , and will be discovered by `AssemblyDependencyResolver` 


## reprduce

run  https://github.com/John0King/LazyMan.ModularLoader/tree/master/test/SubAppTest  the HostApp,   and copy a bigger webapp (just not black app)  for example OrchardCore (need to change the `CreateWebHost` to `CreateWebHostBuilder`)

**Comment by vitek-karas** [comment]
@John0King Is your problem related to this issue? As far as I can tell you don't have any native components in your project. This issue is only about problems with handling native dependencies in hierarchical ALCs - neither of which you seem to be using. It would be better to create a new issue for this.

That aside I think that trying to load ASP.NET app into a secondary ALC is going to be problematic. I've seen issues around this already. Mostly they're because ASP.NET (and the libraries it uses) are not ALC aware and sometimes do things which will lead to problems. Good example is here: https://github.com/dotnet/runtime/blob/e25517ea27311297c1e3946acb3b4382d5fa7fef/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L82 - since `Microsoft.Extensions.Hosting` is going to be loaded to the default ALC (it's part of a framework) the `Assembly.Load` will work on the default ALC only - so if you try to load an application into a secondary ALC this will either directly fail, or it will not work as expected. I'm not sure how many other samples are there in ASP.NET of this.

There might be some tricks you can play with [`CurrentContextualReflectionContext`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.currentcontextualreflectioncontext?view=netcore-3.1) but it's not guaranteed to fix the problem. In short I think this is a problem in ASP.NET which was simply not designed to work in secondary ALCs - at least yet.

**Comment by John0King** [comment]
I'm sorry ask here, but I really do not know where should I create a new issue,  runtime/aspnetcore ,
the reason I post here is because I think it should be a alc fullback issue:

```
defualt alc:   A --(call) --> B  --(call)---> C
plugin alc :    D--(call)-> [  A  ](fallback from default alc)    --🚫--> C ′ 

```

in plugin alc, assembly D in plugin alc  can call assembly A   from defualt alc ,  but then it can not call the C ′  from plugin alc,  because the A is in default alc, and it can only find C instead of C′,
the theory to solve this, is make the  type/assembly  finding by  `CurrentContextualReflectionContext`

so when `D`  call  `A`  it is in plugin alc Context,  and when find C , it will look plugin alc first
