### ISSUE TITLE
QEMU support for ARM64

### ISSUE THREAD

**Issue by raffaeler** [dotnet/runtime#13648]
I need to debug from Windows some code running inside an ARM64 container (on HyperV / docker which uses QEMU to run ARM code).
The code contains a lot of generated unsafe code using 64 bit pointers that is running well on both Windows x64 and Linux x64.
A first test on the physical device (Ubuntu 64 on Rasberry PI 3) did not succeed without apparent errors, therefore I would like to iterate the development inside a container to ease the development and later the automatic tests phases.

Is that currently supported? What are the limitations?
/cc @richlander

**Comment by mangod9** [comment]
Moving this to future. @AntonLapounov can perhaps determine what is required here.

**Comment by richlander** [comment]
Last time we investigated this, I believe we determined that the issue was in a dependency (from the Linux package manager).  If that's the case, then we're not in a good position to enable the scenario. It is probably worth re-validating that, and then file an issue on the given library. We don't want to be in the position where we have to support a scenario that we cannot control.

@jkotas had well-defined views on this last time we talked about this. I believe I'm mostly parroting his viewpoint.

**Comment by AntonLapounov** [comment]
According to the comments above, `dotnet new` and `dotnet run` commands completed successfully modulo QEMU warnings, which may be ignorable.  I cannot comment on potential limitations as this is not one of the scenarios we test.

**Comment by richlander** [comment]
I don't believe I've had that much success with QEMU. It usually fails more quickly for me.

Stepping back, I think it would be cool to support QEMU but we've had very few requests. Perhaps this will increase as Arm64 becomes more popular. I'd like to wait for more call for this before investing. That said, it would be a fine .NET 7 investigation if folks have cycles for it.

**Comment by richlander** [comment]
This is relevant: https://gitlab.com/qemu-project/qemu/-/issues/249

**Comment by raffaeler** [comment]
Thank you @richlander, crossing fingers.
Should they fix this, how would you feel confident to support the scenario?

**Comment by richlander** [comment]
Great question @raffaeler. I don't have info to answer that, but quite possibly.

**Comment by stefandxm** [comment]
With NET7 i can now build if i use DOTNET_EnableWriteXorExecute=0 (export DOTNET_EnableWriteXorExecute=0)

**Comment by MichalPetryka** [comment]
> With NET7 i can now build if i use DOTNET_EnableWriteXorExecute=0 (export DOTNET_EnableWriteXorExecute=0)

As I've noted in https://github.com/dotnet/sdk/issues/27190, disabling `DOTNET_EnableWriteXorExecute` made the SDK go further for me but still crashed. But as also noted there, .Net 6 works fine with QEMU in my case.

**Comment by richlander** [comment]
I added a support statement about QEMU to clarify this: https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#qemu

We are not testing QEMU and the fact that the referenced qemu-project issue has not gotten traction is an indication that support might be difficult.

We're working on improving the Docker use case for QEMU so that it won't be needed. We should have that resolved relatively soon.

I'm closing this issue since the original question has been answered. If folks want to continue to explore making QEMU work, that's fine. You can continue to do it on this issue or open a new issue with a descriptive title.

**Comment by goncalo-oliveira** [comment]
So... what's the reality with .NET and QEMU? .NET 7 (and probably .NET 8) not supported?
Where does that leave anyone needing to build ARM images on AMD and vice versa?
Are the only workarounds 1. Use .NET 6 or 2. Use separate Dockerfile for each arch?

**Comment by richlander** [comment]
Great timing. We have a solution for this now.

https://github.com/dotnet/dotnet-docker/issues/4388#issuecomment-1459038566

I'll be writing up more about it, but you can try what we've done now.
