### ISSUE TITLE
Why `System.Net.Sockets` has dependency to `System.Security.Principal.Windows`?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/runtime#1383]
Why `System.Runtime.Caching` has dependency to `System.Security.Principal.Windows`?

Okay, the comment should be

Why `System.Net.Sockets` has dependency to `System.Security.Principal.Windows`?

to match new title.

**Comment by StephenBonikowsky** [comment]
If I understand this correctly, the necessary fix should be done in the tool that analyzes an app and is supposed to link away unneeded assemblies.

What area label should be applied to this issue?

**Comment by geoffkizer** [comment]
The reason that System.Net.Sockets has a dependency on System.Security.Principal.Windows is because the old APM-style async methods are implemented using ContextAwareResult, which supports flowing identity and thus requires System.Security.Principal.Windows.

The System.Net.Sockets code isn't actually using ContextAwareResult to flow identity, as far as I can see. So it's never used in practice.

Longer-term, we should reimplement the old APM style async stuff on top of the new Task based methods; this will eliminate the dependency on ContextAwareResult and should provide a bunch of other benefits too, like improving perf.

Short-term, we could look at refactoring the existing dependency. I'm not sure why the Sockets code uses ContextAwareResult here instead of LazyAsyncResult, but there's presumably a good reason for it.
