### ISSUE TITLE
PlatformNotSupportedException in XmlSerializer constructor when type to be serialized contains properties with XmlElementAttribute(Type=...)

### ISSUE THREAD

**Issue by wexman** [dotnet/runtime#1394]
I think I found a bug in the constructor of XmlSerializer. It happens when the class to be serialized contains a member with an XmlElement-Attribute which specifies a Type. The constructor will (irritatingly) throw a PlatformNotSupportedException with the text "Compiling JScript/CSharp scripts is not supported".

```
    [TestFixture]
    public class XmlSerializerTests
    {
        [Test]
        public void CanSerialize()
        {
            var testObject = new TestClass();
            var serializer = new XmlSerializer(typeof(TestClass));  // throws PlatformNotSupportedException
        }
    }

    public class TestClass
    {
        [XmlElement(Type = typeof(SomeSerializationHelper<AnotherTestClass>))]
        public AnotherTestClass SomeMember { get; set; }
    }

    public class AnotherTestClass
    {
    }

    public class SomeSerializationHelper<T>
    {
    }
```

**Comment by julealgon** [comment]
The proposed fix does not work for me. I stumbled on a new problem when trying to make the surrogate type approach work with manually generated serialization assemblies.

#630

Due to the bug above, I'm now getting 100+ compilation warnings and a failure at the very end of the process:
> Warning		SGEN: Failed to generate the serializer for MyProject.dll. Please follow the instructions at https://go.microsoft.com/fwlink/?linkid=858594 and try again.

The functionality from full Framework is something I relied upon as well for deserialization of complex objects using a surrogate type that can be converted to the original type.

> When you attempt to do something which the documentation says won't work, and it doesn't work, that's not a bug.

I disagree strongly with this comment @mconnew . Using surrogate types is something that was widely used in .Net Framework. Even if it wasn't properly documented, it did work fine, so it _became a feature_. By removing that behavior, you are introducing a very severe breaking change into existing code.

Now I'm stuck since the workaround is not working properly as well due to the issue above...

**Comment by mconnew** [comment]
@julealgon, for issue #630, have you tried the workaround in [this comment](https://github.com/dotnet/runtime/issues/1390#issuecomment-558848416)? As for you disagreeing, whether you agree or not doesn't change the reality that this particular issue can't be safely fixed in the RefEmit implementation as per my earlier comment describing the problems with doing so. There is a path to fixing this, but it's not a short one. We plan to implement async serialization which for the same rationale can't be implemented by iterating on the RefEmit implementation, but with async it's 1000 times worse as we would need to implement all the async state machine stuff that the compile does for you when compiling C# code. This means we need to bring the reflection based implementation up to par with the RefEmit implementation both in terms of features and performance and then do the work to make everything async. Only once this is done would we be able to make any changes, and we would likely need to write the code to look for an implicit conversion operator and call it explicitly, although I would hope we could get the compiler to do that with careful use of generics. But that's a long way out as we're a small team and I would recommend trying to solve your problem with how things are today.

**Comment by julealgon** [comment]
> @julealgon, for issue #630, have you tried the workaround in this comment?

Thanks for linking that, I hadn't seen it. It is quite an intrusive change for me so I have gone with a different strategy that doesn't rely on surrogates anymore for now.

> As for you disagreeing, whether you agree or not doesn't change the reality that this particular issue can't be safely fixed in the RefEmit implementation as per my earlier comment describing the problems with doing so. There is a path to fixing this, but it's not a short one.

I'm well aware that my opinion doesn't change _how hard it is to implement_, but is it being hard reason enough to close this issue though?

Also, can't you just consider a new mechanism for supporting surrogate serialization types that don't rely on the need for conversion operators to begin with? I think people use the surrogate approach the way they do because it is currently the only way to decouple and share the serialization logic, but if there was a native way of doing so it would be much better IMHO. For instance, an approach that allowed one to implement serializers for a given type externally (like `IEqualityComparer` implements equality externally) and then pass in those implementations to the serializer to use, that would be a considerable improvement on this "hacky" use of conversions into surrogate types.

The main issue right now as far as I can tell is the fact that you are forced to implement `IXmlSerializable` in the actual type being serialized/deserialized.
