### ISSUE TITLE
Make System.Collections.Immutable [Serializable]

### ISSUE THREAD

**Issue by psmolinsky** [dotnet/runtime#14395]
Please make collections from namespace System.Collections.Immutable serializable if it is possible - mark them with `[Serializable]` attribute and do other related changes. There can be many cases when this would be useful. Thanks.

**Comment by eiriktsarpalis** [comment]
Triage: would support such an addition, please provide an API proposal.

**Comment by fabricefou** [comment]
> Triage: would support such an addition, please provide an API proposal

I don't understand, just add `[Serializable]` attribute is not an option ?

**Comment by safern** [comment]
Adding @ViktorHofer as the serialization expert in case he has something to consider before adding this.

**Comment by ViktorHofer** [comment]
We aren't planning to expand the support matrix of serializable types for .NET 5 onwards. There are concerns as support binary serialization (which uses the Serializable attribute) limits the underneath implementation because of implementation details being encoded in the serialization payload.

cc @stephentoub

**Comment by stephentoub** [comment]
> I don't understand, just add [Serializable] attribute is not an option ?

No.  Just doing that exposes the implementation details of the collection, and makes it effectively impossible for us to make any meaningful changes to the implementation.  It's one of (but far from the only) reason we've significantly limited what types are serializable in .NET Core; most of the types that were serializable in .NET Framework are not in .NET Core, by design, with only a handful of hand-picked types opted-in as a compatibility tradeoff to help existing code migrate.

Binary serialization is not a technology we believe in, and in fact, there are active conversations like https://github.com/dotnet/runtime/issues/29976 about deinvesting in it further.

As noted by other respondents earlier in the thread, there are better technologies available for this that you can use around the collections you want to serialize rather than requiring changes to the collections themselves.  And if you must serialize them with BinaryFormatter, you can use serialization surrogates to do so.

Given all that, we don't plan to make these collection types serializable.

Thanks.

**Comment by fabricefou** [comment]
Thanks @stephentoub for this answer.
I understand well your motivation to not incite people to use BinaryFormater.

Juste to mitigate some of your arguments :
- `List<T>` is serializable why not `ImmutableArray<T>` ? internal structure are very similar.
- on legacy system, BinaryFormater are often wildly use, don't add serializable attribute on immutable collection slow down it's use.
- surrogate are pretty hard to use on imbricated data structure ex: ImmutableArray<ImmutableArray<T>>. BTW if you have smart implementation for immutableCollection don't hesitate to share.
- to not expose implementation details we can implement the ISerializable/IDeserializationCallback interfaces as used in `Dictionary<K,V>`

**Comment by sab39** [comment]
@stephentoub (sorry for the very belated response!)

>  And if you must serialize them with BinaryFormatter, you can use serialization surrogates to do so.

For those of us stuck in the legacy Framework world and stuck with binary serialization (ASP.NET WebForms forces both of those things on me), is there a way to put in some global code to automatically use serialization surrogates any time the formatter encounters one of the immutable collection classes? Or do I have to put in specific serialization handling every time I want to have a collection in a [Serializable] class?

**Comment by stephentoub** [comment]
@sab39, I'm not aware of any way to globally affect all BinaryFormatter instances.  I believe you'd need to specify the surrogate on each instance.
cc: @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
@stephentoub is right, it's a per-instance thing. Were you also looking for global fallback surrogate selector support in Full Framework apps as well, or just Core?

**Comment by sab39** [comment]
@GrabYourPitchforks My particular situation is a Framework application using ASP.NET Web Forms. The Web Forms framework does a lot of implicit binary serialization for things like the ViewState object and my particular application is heavily dependent on putting lots of custom objects into ViewState. (Needless to say, those are questionable-at-best design decisions from both my app and from WebForms, which is probably why WebForms isn't being ported to Core, but I'm stuck with them)

My interest in this topic is that I'd love to be able to use Immutable collections in those custom objects rather than relying on List<> and Dictionary<>, but it's impractical to add a whole lot of serialization boilerplate to every class that happens to have a field that's a collection type.

I think WebForms does have a way to customize the Formatter that's used for its serialization, so it wouldn't have to be global to the entire process or AppDomain or anything like that. Just need something so the class _being_ serialized doesn't need to do anything beyond the usual `[Serializable]` to get its ImmutableCollection typed fields serialized and deserialized correctly.
