### ISSUE TITLE
Add String.Format overloads to avoid unnecessary allocations

### ISSUE THREAD

**Issue by justinvp** [dotnet/runtime#14484]
It's pretty common to pass value types to `String.Format`, unfortunately this results in unnecessary boxing allocations.
## Rationale

Consider the following:

``` c#
long id = ...;
int index = ...;
int length = ...;

// Traditional call to String.Format
string foo = string.Format("{0}: Index = {1}, Length = {2}", id, index, length);

// Use of the string interpolation language feature
string bar = $"{id}: Index = {index}, Length = {length}";
```

Both the traditional call to `String.Format` and the use of the string interpolation language feature (which is just syntactic sugar for `String.Format`) requires 3 boxing allocations.
## Proposed API

``` c#
namespace System
{
    public sealed class String : ...
    {
        // Proposed methods
        public static string Format<T0>(string format, T0 arg0);
        public static string Format<T0, T1>(string format, T0 arg0, T1 arg1);
        public static string Format<T0, T1, T2>(string format, T0 arg0, T1 arg1, T2 arg2);
        public static string Format<T0>(IFormatProvider provider, string format, T0 arg0);
        public static string Format<T0, T1>(IFormatProvider provider, string format, T0 arg0, T1 arg1);
        public static string Format<T0, T1, T2>(IFormatProvider provider, string format, T0 arg0, T1 arg1, T2 arg2);

        // Existing methods
        public static string Format(string format, object arg0);
        public static string Format(string format, object arg0, object arg1);
        public static string Format(string format, object arg0, object arg1, object arg2);
        public static string Format(string format, params object[] args);
        public static string Format(IFormatProvider provider, string format, object arg0);
        public static string Format(IFormatProvider provider, string format, object arg0, object arg1);
        public static string Format(IFormatProvider provider, string format, object arg0, object arg1, object arg2);
        public static string Format(IFormatProvider provider, string format, params object[] args);

        ...
    }
}

namespace System.Text
{
    public sealed class StringBuilder
    {
        // Proposed methods
        public StringBuilder AppendFormat<T0>(string format, T0 arg0);
        public StringBuilder AppendFormat<T0, T1>(string format, T0 arg0, T1 arg1);
        public StringBuilder AppendFormat<T0, T1, T2>(string format, T0 arg0, T1 arg1, T2 arg2);
        public StringBuilder AppendFormat<T0>(IFormatProvider provider, string format, T0 arg0);
        public StringBuilder AppendFormat<T0, T1>(IFormatProvider provider, string format, T0 arg0, T1 arg1);
        public StringBuilder AppendFormat<T0, T1, T2>(IFormatProvider provider, string format, T0 arg0, T1 arg1, T2 arg2);

        // Existing methods
        public StringBuilder AppendFormat(string format, object arg0);
        public StringBuilder AppendFormat(string format, object arg0, object arg1);
        public StringBuilder AppendFormat(string format, object arg0, object arg1, object arg2);
        public StringBuilder AppendFormat(string format, params object[] args);
        public StringBuilder AppendFormat(IFormatProvider provider, string format, object arg0);
        public StringBuilder AppendFormat(IFormatProvider provider, string format, object arg0, object arg1);
        public StringBuilder AppendFormat(IFormatProvider provider, string format, object arg0, object arg1, object arg2);
        public StringBuilder AppendFormat(IFormatProvider provider, string format, params object[] args);

        ...
    }
}

namespace System.Runtime.CompilerServices
{
    public static class FormattableStringFactory
    {
        // Proposed methods
        public static FormattableString Create<T0>(string format, T0 argument0);
        public static FormattableString Create<T0, T1>(string format, T0 argument0, T1 argument1);
        public static FormattableString Create<T0, T1, T2>(string format, T0 argument0, T1 argument1, T2 argument2);

        // Existing method
        public static FormattableString Create(string format, params object[] arguments);
    }
}
```

I'd be happy to contribute an implementation and tests.

**Comment by joperezr** [comment]
Not sure why is this one flagged for 5.0, @jkotas @terrajobst I suppose that this one we probably want to push to future instead right?

**Comment by davidfowl** [comment]
Did we ever make progress on this? Did we remove the 9 internal allocations here? I was looking around at issues for improving `sting.Format` and this one keeps popping up in my searches. I'm also wondering why there isn't a method that "compiles" the template (sorta like a compiled regex):

```C#
FormattableString<string> formatter =  FormattableString.Create<string>("Hello {name}");

formatter.Format("Joe");
formatter.Format("John");
formatter.Format("Paul");
```

**Comment by terrajobst** [comment]
@stephentoub can correct me, but AFAIK we solved a related problem in the BCL a while ago to take advantage of specialized params overloads for a fixed number of arguments to avoid allocating the array. Not sure we made any progress for avoiding allocations due to boxing. If we do this, we likely want to support FormattableString. Depending on how Roslyn binds to the factory, this might or not might not need compiler changes.

> I'm also wondering why there isn't a method that "compiles" the template (sorta like a compiled regex)

I don't think the use case ever came up. For 99% of cases, callers have the format as a string and the arguments. Not saying it's wrong, but it's certainly not very convenient.

**Comment by stephentoub** [comment]
What I proposed (https://github.com/dotnet/runtime/issues/28945), and what @jaredpar's been running with as a potential C# 10 feature (https://github.com/dotnet/csharplang/issues/2302), is the idea of a target-typable custom builder, with the C# compiler generating Append calls for each string segment and each hole.  For example, if you had a method:
```C#
static void Foo(MyCustomBuilder builder);
```
and someone called that with:
```C#
ReadOnlySpan<char> name = ...;
int age = ...;
Foo($"Hi.  My name is {name}, and my age is {age}.");
```
the compiler would translate that into something along the lines of:
```C#
var b = MyCustomBuilder.Create();
b.Append("Hi. My name is ");
b.Append(name);
b.Append(", and my age is ");
b.Append(age);
b.Append(".");
```
MyCustomBuilder would at a minimum expose an Append overload for `object`, but it could also expose overloads for for `string`, for `int`, for `ReadOnlySpan<char>`, for `T`, and for whatever other types it wants to optimize for.

**Comment by geeknoid** [comment]
I have a proposed for a considerably faster solution to string formatting, which avoids boxing of arguments in the common case and only performs a single allocation for the final string. It's coming at around 2x faster than String.Format or string interpolation in the common case, plus since it doesn't create temporary garbage it's nicer on the GC in the long run.

See https://github.com/geeknoid/FastFormatting.

If folks are interested, I'd be happy to submit a PR and get this integrated in the system. The code that's there now is mostly feature complete, but it lacks full testing and docs. I'll address these shortcomings in the next few days.

PS: @stephentoub, you might recognize the concept from CompositeFormatString in that previous project we worked on years ago :-)

**Comment by stephentoub** [comment]
@geeknoid, what are the advantages of that over my cited proposal?  From a usability perspective, I'd prefer being able to write `Foo($"Hi.  My name is {name}, and my age is {age}.")` rather than `private static readonly StringFormatter s_nameFormat = new StringFormatter("Hi.  My name is {0}, and my age is {1}."); ...; Foo(s_nameFormat.Format(name, age);`, and I don't believe the proposed StringFormatter works well with spans, which can't be used in generic contexts.  The cited proposal also similarly avoids all boxing, only allocates for the final string (if a string is even needed... a consumer could just access a span from the builder), etc.

**Comment by davidfowl** [comment]
How do format specifiers work in your proposal @stephentoub ?

**Comment by stephentoub** [comment]
> How do format specifiers work in your proposal @stephentoub ?

We'd define a pattern for Append methods, where the first argument is the thing to be formatted,  if there's a second it's a format string, etc.

**Comment by geeknoid** [comment]
I've now added support for a Span-based TryFormat version which results in no allocations. This version is over 4x as fast as String.Format and induces no garbage. After 20 years, there's finally a formatting function in .NET that can compare in perf with C's sprintf :-)

Here are the benchmark results

```
|                      Method |     Mean |    Error |   StdDev |     Gen 0 |     Gen 1 |    Gen 2 |  Allocated |
|---------------------------- |---------:|---------:|---------:|----------:|----------:|---------:|-----------:|
|     TestClassicStringFormat | 46.02 ms | 0.865 ms | 1.515 ms | 2909.0909 | 1181.8182 | 363.6364 | 16800057 B |
|           TestInterpolation | 47.91 ms | 0.943 ms | 1.523 ms | 3000.0000 | 1250.0000 | 416.6667 | 16800523 B |
|         TestStringFormatter | 25.59 ms | 0.508 ms | 0.903 ms | 2187.5000 |  906.2500 | 281.2500 | 12000025 B |
| TestStringFormatterWithSpan | 10.86 ms | 0.182 ms | 0.224 ms |         - |         - |        - |        4 B |
```

**Comment by geeknoid** [comment]
@stephentoub The benefits to my proposal is that:

* I believe it is both smaller IL and faster than what you propose.
* The implementation exposes a span-based version which completely eliminates all allocations. 
* It's fully implemented and can be played around with.

I think the C# compiler can be thought about this type and magically generate the static StringFormatter instances for any use of string interpolation. Thus, existing code would just suddenly get faster by recompiling. Additionally, I think there could be a Roslyn code fixer which offers to convert any use of String.Format with a static format string into an interpolated string. Those cases would also then magically benefit from improved perf.

Also I think my implementation for a non-boxing version of the ParamsArray type could be used to eliminate boxing in existing APIs like String.Format, making those a touch faster too.

**Comment by En3Tho** [comment]
@geeknoid can you share benchmark code or link it please? While this is kinda off topic but I feel that there might be a way to make faster F# printf with things you're proposing.

**Comment by danmosemsft** [comment]
@En3Tho looks like it's at https://github.com/geeknoid/FastFormatting

**Comment by stephentoub** [comment]
> The benefits to my proposal is that

Thanks.

> I believe it is both smaller IL and faster than what you propose.

I expect it would be smaller IL.  I'm skeptical it'd be meaningfully faster for creating strings.  And it would almost certainly result in more asm, though, in particular as every unique combination of arguments involving a value type would result in generic specialization for the all of the generic pieces, and that's likely to be non-trivial; in contrast, with the builder approach, you only end up worst case with a generic-specialization per type formatted rather than per combination of types formatted.

> The implementation exposes a span-based version which completely eliminates all allocations.

I agree the TryFormat aspect of it is nice.  With the builder approach, you can get that as well, but it involves a copy.

In both approaches, it's also hard to claim all allocations are completely eliminated, as the moment you need to utilize IFormattable, you're likely incurring string allocations for each argument being formatted, only not when the instance is able to utilize a cached string.

I also don't see how the proposed approach supports arbitrary numbers of arguments without allocation.  At some point you need one more argument than can be supported by the explicit strongly-typed overloads provided, and you end up with the params object[] overload.  One of the nice things about the builder approach is it supports any number of arguments strongly-typed, as each argument is formatted independently with a single Append call.

> It doesn't require any significant new patterns across types

This also hints at one of its biggest flaws IMO, but maybe you have a good solution for this.  I think anything new we do in this space _must_ support formatting `ReadOnlySpan<char>` as arguments.  One of the nice things about the builder approach is this is easily supported just by having an `Append(ReadOnlySpan<char>)` overload on the builder.  I don't see how this is easily supported in your proposal, as spans can't currently be used as generic arguments.  How would you propose to support span?

> Also I think my implementation for a non-boxing version of the ParamsArray type could be used to eliminate boxing in existing APIs like String.Format, making those a touch faster too.

With the existing overloads?  I don't see how, since the boxing is inherent to the existing APIs.  It's also inherent to the existing implementation, which relies heavily on being able to pass the arguments around as object.  If you're suggesting new generic string.Format overloads like those proposed in the very first post, that would also require plumbing that through the whole formatting implementation; I'd be interested in understanding what that implementation would look like, and similar to my previous comments, what impact that would have on bloating asm size in a typical apps (especially for AOT compilations, Blazor, Xamarin apps, etc., where presumably existing usage would start binding to the new more-strongly-typed overloads).

**Comment by geeknoid** [comment]
Yes, you've found all the flaws of the current implementation  :-). Some more thoughts:

* It's only allocation-free up to 3 arguments. This could be extended to a larger number, but there's clearly an upper bound. With the way the API is designed, the first 3 arguments are captured in a strongly-typed fashion and the rest are in a `params object?[]`

* I made a specific point of keeping the code that has multiple generics as simple as possible. There is actually very little code in that regime, the generic code calls out ASAP to non-generic functions when possible. I learned my lesson about the impact of multi-generic types when we tried to implement a 4-parameter finger tree years ago. It was enormous! Anyway, I think the amount of code generated is within reason.

* Of course, if the implementation calls out to an IFormattable instance, an allocation will happen as a result. There's no getting around that given how IFormattable works. The code deals with all primitive types without boxing however. It would be good to make ISpanFormattable public so more types could implement it and improve formatting efficiency in general.

* It'd be interesting to compare the perf of the builder pattern with my design. The builder pattern would certainly win for large argument counts by completely eliminating the params array allocation and associated boxing. But I suspect in the common case of 1-3 arguments, my design would be faster due to a tight inner loop.

* My design works, today, in any version of .NET that supports Span<T> without requiring any changes in the system. I think that makes it pretty compelling to adopt immediately given the substantial perf improvement it delivers.

* Don't underestimate the value of the 2x perf boost you get with TryFormat. This is huge. We have a lot of services that do a lot of string formatting and enabling them to be 0 alloc in the common case would likely lead to measurable COGs savings.

I can't think of a way to support ReadOnlySpan<char> in my current design, just like it can't be supported by any of the existing formatting code in .NET. That doesn't make me too sad though. The solution there is to fix the GC to allow Span<T> in the heap :-)

**Comment by geeknoid** [comment]
@stephentoub So what I've done in my stuff is three things:

* Extend ValueStringBuilder to support Append methods for the various primitive types. These overloads support argument formatting.

* Create the machinery to preparse a composite format strings to a dense form that can be interpreted faster during formatting and provide a formatting loop that leverages this.

* Implement a hack to prevent the params array allocation and boxing for the first 3 formatting arguments.

Exposing the extended ValueStringBuilder as a public type would be sufficient to implement the builder pattern you describe. String interpolation would immediately benefit. This could support all the normal formatting features (width, justification, etc)

Exposing ValueStringBuilder would make it possible for developers to implement 0-alloc string **concatenation** by supplying a span to the constructor of ValueStringBuilder. It's a bit clumsy, but it'll be quite fast.

To let developers do 0 alloc string **formatting**, then you can add the StringFormatter type with its TryFormat method. Or, you could get fancy and enhance string interpolation with new syntax such as:
```
Span<char> target = new Span<char>(new char[256]);
target <= $"Hello {name}"
```

This would let the C# compiler pass the span to the ValueStringBuilder constructor and voila, slick no-alloc string formatting.

**Comment by En3Tho** [comment]
That syntax is too vague in this case. Should it return book and chars written, should it only return chars written and -1 in bad case, or should it completely hide details and just suddenly blow up with our of memory if anything goes wrong? I think that sticking to Method calls is better in this case

**Comment by geeknoid** [comment]
@stephentoub I've updated the design at https://github.com/geeknoid/FastFormatting. From the README:

* The `StringMaker` type is a supercharged version of the classic `StringBuilder` type. It
is designed for efficiently building up a string or span by appending together bits and
pieces. The implementation tries to avoid any memory allocations when it can, and if you
supply your own span to the constructor, it can operate entirely without allocating memory.
When used in this memory, totally performance is around 4x faster than using `StringBuilder`.

* The `StringFormatter` type is built on top of `StringMaker` and is designed to support the
normal .NET composite formatting model, such as you use with `String.Format`. The type splits
the normal formatting step in two in order to boost performance of the formatting process. 
The first step is parsing the composite format string into an efficient form. This step is done
by create a `StringFormatter` instance. Once you have this instance, you can use it to format 
a set of arguments by calling the `Format` method, which is about 2x as fast as `String.Format`.
You can also use the `TryFormat` method to format directly into your own span, which is 4x faster
than `String.Format`.

This new code maintains the same perf characteristics as I had previously. The code has nearly 100% code coverage and compatibility with classic String.Format semantics is explicitly tested for.

I think `StringMaker` can be used directly by the C# compiler to implement efficient interpolation with a single allocation for the final string. Some magic C# syntax can also enable 0 allocation by outputting to an existing span. The StringFormatter type on its side is useful as a faster replacement of String.Format for when interpolation is not an option (for localized text for example). 

How's that sound?

**Comment by geeknoid** [comment]
Latest perf tests. These are all trying to format the same set of inputs and produce the same final string:

```
|                      Method |     Mean |    Error |   StdDev |   Median |     Gen 0 |     Gen 1 |    Gen 2 |  Allocated |
|---------------------------- |---------:|---------:|---------:|---------:|----------:|----------:|---------:|-----------:|
|     TestClassicStringFormat | 45.306 ms | 0.8882 ms | 1.6016 ms | 45.605 ms | 2888.8889 | 1111.1111 | 333.3333 | 16800098 B |
|           TestInterpolation | 46.278 ms | 0.9231 ms | 1.8857 ms | 45.727 ms | 3000.0000 | 1250.0000 | 416.6667 | 16800517 B |
|         TestStringFormatter | 24.990 ms | 0.4604 ms | 0.6302 ms | 25.011 ms | 2187.5000 |  906.2500 | 281.2500 | 12000040 B |
| TestStringFormatterWithSpan | 11.166 ms | 0.2147 ms | 0.5225 ms | 10.991 ms |         - |         - |        - |        4 B |
|             TestStringMaker |  8.932 ms | 0.1380 ms | 0.1152 ms |  8.922 ms | 2859.3750 |         - |        - | 11999920 B |
|     TestStringMakerWithSpan |  6.416 ms | 0.1033 ms | 0.0967 ms |  6.418 ms |         - |         - |        - |        2 B |
```

**Comment by stephentoub** [comment]
> I think StringMaker can be used directly by the C# compiler to implement efficient interpolation with a single allocation for the final string

Isn't StringMaker essentially just ValueStringBuilder, and basically the same builder approach I was proposing?  The only thing that differs is I was suggesting a pattern in addition, but that's just to enable additional scenarios, namely an API that wants to take a particular builder so as to a) have raw access to its underlying buffer and b) have control over the Append methods exposed so as to have more control over the formatting.  But we'd have a built-in implementation of it that the compiler could use when targeting string, such that existing string interpolation just go more efficient in its implementation without semantic changes.  So, I'm not clear on fundamentally what's different here? (Note that if we do go with such an approach, such a type would likely live in the compiler services namespace, and would be discouraged for general direct use: in general we're wary of exposing structs that wrap pooled resources, even if ref structs, that would make it easy to accidentally copy them and dispose multiple times, double-freeing a buffer.)

> The StringMaker type is a supercharged version of the classic StringBuilder type.

As noted above, this seems like it's just ValueStringBuilder.  If from an implementation perspective there are things you've done in your implementation that you've found to be more efficient, please feel free to submit a PR to improve ValueStringBuilder's implementation / reduce its overheads.

> How's that sound?

I think you're now proposing two separate things:
1. Basically what I proposed (waving hands at minor API-level differences here and there)
2. In addition a separate StringFormatter class, with the primary goals of a) supporting the existing .NET formatting model pre-interpolated strings and b) exposing a TryFormat.

Am I understanding correctly?

**Comment by stephentoub** [comment]
ps I'm on a stay-cation now and will be slow to respond until the new year.  Thanks, and happy holidays.

**Comment by geeknoid** [comment]
@stephentoub Yes, that is correct. A layered model with a builder pattern and a composite format string formatter built on top.

Indeed, StringMaker exposes the builder pattern that you suggested. I realized that my original StringFormatter could easily be cleaved into two parts. One being a builder, and the other being the preprocessed string formatting functionality. And as you can see from the benchmarks, you were totally right that the builder pattern is faster at runtime. Makes sense, since StringFormatter is extra crap on top of the builder and is thus slower.

StringMaker is based on the same principle as ValueStringBuilder, but it is different in a few ways:

* It is a more specialized type designed strictly for high-speed append operations.
* It has a large selection of Append methods to address all primitive types without boxing.
* Some of the Append overloads support (string format, int width, IFormatProvider?) arguments, making them suitable to implement a full fidelity replacement for all the String.Format formatting features. This is needed for the C# compiler use case.
* It supports the TryFormat pattern such that dynamically reallocation of the buffer is blocked, ensuring no allocs occur.

I think as it is, the StringMaker type can handle random types efficiently:

* If a type implements ISpanFormattable, it should just work, without boxing by virtue of the Append<T> overload.
* If a type implements IFormattable, it would be boxed beforehand.
* Alternatively, the C# compiler could automatically detect extension methods against StringMaker which follow the TryFormat pattern and generate calls to those extension methods automatically.

In the common case, the C# compiler should be able to use the 0-alloc variant of StirngMaker and deliver a near optimal formatting experience. The only thing better would be if the compiler support syntax to do interpolation into an existing span.

**Comment by stephentoub** [comment]
Sorry for the delay, @geeknoid.

> It is a more specialized type designed strictly for high-speed append operations.
> It has a large selection of Append methods to address all primitive types without boxing.
> Some of the Append overloads support (string format, int width, IFormatProvider?) arguments, making them suitable to implement a full fidelity replacement for all the String.Format formatting features. This is needed for the C# compiler use case.

Yes, all of those are part of productizing a ValueStringBuilder-like type for the purposes of a C#-based string interpolation target.  We've been saying "ValueStringBuilder" just because it's the general approximation of what's needed.  There are other aspects of it that would differ as well; as noted, for example, we would likely want to hide it away in System.Runtime.CompilerServices and with some less appealing name to highlight that it's a relatively dangerous type to use directly (as is any struct that rents/returns arrays from a global pool that others use).

I spoke about all of this with @jaredpar last week, and it's definitely something he's interested in pushing ahead, but I don't know if it'll make C# 10 or not.  For me, this is really about the C# language feature being made more efficient rather than it being about a type a developer can use directly, though if someone wanted to directly use something from System.Runtime.CompilerServices, of course they could (we would need to decide whether to support the TryFormat approach even if it wasn't going to be used by the compiler). I think the 90% case here is just enabling:
```C#
string result = $"A={a} B={b}";
```
to efficiently generate that string.  This does bump up against something we'll need to solve, though, which is how does the compiler get the stack space to use to seed the ValueStringBuilder, or is it forced to always use a rented buffer.  In other words, it'd be nice if the compiler could generate for the above something like:
```C#
var vsb = new ValueStringBuilder(stackalloc char[SomethingReasonable]);
vsb.Append("A=");
vsb.Append(a);
vsb.Append(" B=");
vsb.Append(b);
string result = vsb.ToString();
```
but it's not clear at present exactly what it should do for `SomethingReasonable`.  We could pick an arbitrary small-ish number that should generally be ok, and it could use that same stackalloc for other interpolations in the same method, and hoist it out of loops to ensure we don't overflow, but all that needs to be worked out.  Or we could start by just always using rented space:
```C#
ValueStringBuilder vsb = default;
vsb.Append("A=");
vsb.Append(a);
vsb.Append(" B=");
vsb.Append(b);
string result = vsb.ToString();
```

**Comment by geeknoid** [comment]
@stephentoub thanks for the feedback.

Improving the interpolated string perf is key, but I think strictly focusing on that use case is missing other significant opportunities for perf gains.

The StringMaker type that's in my code takes as ctor input an initial capacity and internally decides to allocate its buffers on the heap or stack based on a fixed constant. The C# compiler can make an educated guess about the optimal buffer capacity in many cases which can prevent the need for StringMaker's buffer being reallocated during work.

As I mentioned above, there are two other key scenarios I'm enabling here:

- A direct replacement for StringBuilder.Format which is fully compatible and 2x the perf. If you use spans and other options, it can get considerably faster still. But as a drop-in replacement, you get direct benefits. String builder is still useful as it supports localized string substitution.

- A slightly more complicated model that delivers yet more performance. Users create a StringFormatter object by passing a format string, and then repetedly reuse this object to format text. This eliminates the redundant and expensive format string parsing that normally occurs every time a string is formatted. For hot paths, it takes only a few minutes to adopt to this pattern and you get instant speed up.

I'm content to deploy these technologies within our broad team and reap the benefits, but I would rather these improvements be rolled into .NET proper so that everyone can benefit. Just point me in the right direction...

**Comment by stephentoub** [comment]
>  I would rather these improvements be rolled into .NET proper so that everyone can benefit

You can ship a nuget package that anyone can use :)

**Comment by jaredpar** [comment]
> I spoke about all of this with @jaredpar last week, and it's definitely something he's interested in pushing ahead, but I don't know if it'll make C# 10 or not

For the interpolated string case I feel very good about the C# 10 chances assuming that runtime has the bandwidth to get the `ValueStringBuilder` type into .NET 6 as well. 

> but I think strictly focusing on that use case is missing other significant opportunities for perf gains.

This is the only part that makes me hesitate a bit. If we feel like interpolated strings can be solved independently of other string formatting issues then I'd actually hoped to move forward rather soon. If we think they're related though then we'll need to push forward with the other design points before the C# work. 

> Or we could start by just always using rented space:

This is the starting point I would prefer. There are several types which would benefit from the use case of "pass me a pre-allocated Span<T> I can use as an initial buffer". One other case was a `FrugalList<T>` style implementation of @geeknoid. That feels like something we should generalize and can push back into `ValueStringBuilder` at a later time. 

Alternatively if it helps the compiler could also pass some additional info to the constructor. For example it can give the length of the constant part of the string plus the number of arguments if that would be beneficial to `ValueStringBuilder` (swear that was already brought up in this thread, but having trouble finding it).

**Comment by stephentoub** [comment]
FWIW, I do like the additional support of being able to a) TryFormat the result of string interpolation rather than always going into a string, and b) being able to seed the builder with the destination output buffer so that there's no additional copying needed.  For (a), I could imagine us implementing that for string interpolation where the compiler transforms something like:
```C#
bool success = $"A={a} B={b}".TryFormat(span, out int charsWritten);
```
into code like:
```C#
var vsb = new ValueStringBuilder();
vsb.Append("A=");
vsb.Append(a);
vsb.Append(" B=");
vsb.Append(b);
bool success = vsb.TryFormat(span, out int charsWritten);
```
And for (b), I could imagine us implementing that for string interpolation where the compiler transformed that same example into something along the lines of:
```C#
charsWritten = 0;
var vsb = new ValueStringBuilder(span, ref charsWritten);
bool success =
    vsb.TryFormat("A=") &&
    vsb.TryFormat(a) &&
    vsb.TryFormat(" B=") &&
    vsb.TryFormat(b) &&
    vsb.TryComplete();
```

**Comment by geeknoid** [comment]
@jaredpar As written, you can use my StringMaker type (a.k.a. ValueStringBuilder per your name) independent of the other layers. The StringFormatter type I've got defined is an independent thing that uses StringMaker in its implementation. So it's easy to peal off StringMaker and use that directly.

**Comment by stephentoub** [comment]
Just to circle back, @333fred has a spec that we're moving forward with that enables something very similar to what I outlined in https://github.com/dotnet/runtime/issues/14484#issuecomment-780271020 and https://github.com/dotnet/runtime/issues/14484#issuecomment-734950020.  He can share the details when he's ready, but I think folks will be happy.

**Comment by 333fred** [comment]
I was just submitting a PR with the spec: https://github.com/dotnet/csharplang/issues/2302.

**Comment by teo-tsirpanis** [comment]
The [interpolated string handlers](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler) feature in .NET 6 is much more flexible, usable and performant than these proposed APIs. I'm going to close this issue, please correct me if I'm wrong.
