### ISSUE TITLE
More offsets in MetadataReader

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#14540]
I believe MetadataReader should have more APIs which tell me about offsets.

I. e.: Let's say I'm writing strong name signer, there are few steps required (assuming that assembly is already delayed signed):
- calculate hash,
- sign hash,
- inject signature

to calculate hash you need to skip some parts of the PE file like:
- strong name signature blob (including the 8 bytes in the header)
- certificates blob (including 8 bytes header)
- checksum

so I need to have offsets and sizes for each of those.
For blobs there are already APIs:
i.e.:

```
peReader.PEHeaders.CorHeader.StrongNameSignatureDirectory.Size
peReader.PEHeaders.CorHeader.StrongNameSignatureDirectory.RelativeVirtualAddress
peReader.PEHeaders.PEHeader.CertificateTableDirectory.Size
peReader.PEHeaders.PEHeader.CertificateTableDirectory.RelativeVirtualAddress
```

what is missing is:
- checksum offset (and optionally a size)
- blob headers

for blob headers we can do simple change in System.Reflection.PortableExecutable.DirectoryEntry
which is:

``` diff
    public struct DirectoryEntry
    {
//...
+       public readonly int HeaderOffset;
//...
        internal DirectoryEntry(ref PEBinaryReader reader)
        {
+           HeaderOffset = reader.CurrentOffset;
            RelativeVirtualAddress = reader.ReadInt32();
            Size = reader.ReadInt32();
        }
//...
    }
```

For stuff like CheckSum offset we need something like this:

``` diff
    public sealed class PEHeader
    {
//...
+       public int BaseOffset; // this might be always 0 so const would be fine too
//...
+       public const int CheckSumOffset;
+       public const int CheckSumSize;
+       //etc. for other fields
}
```

cc: @nguerrera @tmat

What are your thoughts? With good modifications we could probably reuse some of those types when writing MetadataWriter (assuming we are planning to do that)

**Comment by scott-xu** [comment]
Looking forward about signing API (sign/verify) for PE/COFF formats. The SignTool.exe is windows only and has no switch to turn off revocation check.

**Comment by ericstj** [comment]
This library does not implement signing, the discussion was about exposing enough API so that one could implement strong name signing on top of this API.   This issue remains only about exposing offsets.  Note that strong-name signing is different from Authenticode signing, which is what signtool does.  We aren't discussing authenticode at all in this issue.

I took a look at what was exposed and it looks like it covers @krwq's suggestion.

> checksum offset (and optionally a size)

https://github.com/dotnet/runtime/blob/110282c71b3f7e1f91ea339953f4a0eba362a62c/src/libraries/System.Reflection.Metadata/tests/PortableExecutable/PEBuilderTests.cs#L723-L725

> blob headers

```c#
peHeaders.PEHeaderStartOffset
```
