### ISSUE TITLE
Make all structs that claim to be thread-safe dereference `this` at most once per entrypoint

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#14746]
`ImmutableArray<T>` goes to great lengths to be thread-safe by [never dereferencing `this` more than once per public entrypoint](https://github.com/dotnet/corefx/blob/1dc118cc46f88e4889a23190b450d89e565967fd/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601.cs#L18-L33) (to fix bug dotnet/runtime#13908). Other structs in the Framework do _not_ take this care (such as `DateTime`, `Nullable<T>`, or `System.Int32`), despite [claiming to be thread-safe in MSDN documentation](https://msdn.microsoft.com/en-us/library/System.DateTime%28v=vs.110%29.aspx).

Should we take the same care for the other structs? 

The community [has been fascinated](http://stackoverflow.com/questions/30957211/what-advantage-is-there-to-storing-this-in-a-local-variable-in-a-struct-method/30957262) by the pattern in `ImmutableArray<T>` and brought up that it might make sense to spread it around more.

**Comment by airbreather** [comment]
> despite [claiming to be thread-safe in MSDN documentation](https://msdn.microsoft.com/en-us/library/System.DateTime%28v=vs.110%29.aspx).

Today, the "Thread Safety" documentation section of the documentation for some of the indicated structs (`DateTime` and `Int32`, not `ImmutableArray<T>`, and `Nullable<T>` doesn't a "Thread Safety" section) contains this language:

> As with any other type, reading and writing to a shared variable that contains an instance of this type must be protected by a lock to guarantee thread safety.

Is that good enough?

**Comment by AArnott** [comment]
Yes, I suppose that would be sufficient for those types that include that documentation.

**Comment by sharwell** [comment]
Ideally we should audit all the public value types that have a size no greater than a pointer. We could go further and audit the types with a size equal to `long`, but those would only guarantee atomic reads on x64 machines.

**Comment by corranrogue9** [comment]
Is this work item still up for grabs? I would be willing to start making some progress on this work if it is still something that we want addressed.

**Comment by AArnott** [comment]
I think so, @corranrogue9. But we should probably wait for a regular repo contributor to chime in as well.

**Comment by EmJayGee** [comment]
Hey, I was intrigued by this issue so I was poking into it and had a question or two.

Looking at struct DateTime, there's a helper private method:

        private void ValidateLeapSecond()
        {
            if (!IsValidTimeWithLeapSeconds(Year, Month, Day, Hour, Minute, Kind))
            {
                ThrowHelper.ThrowArgumentOutOfRange_BadHourMinuteSecond();
            }
        }

question 1: do the six field references constitute six references or would you trust the compiler to address this "properly"? e.g. do you need to make a copy of the struct first? e.g. sorry my c# is rusty but I assume something like

        private void ValidateLeapSecond()
        {
            const DateTime thisCopy = this;
            if (!IsValidTimeWithLeapSeconds(thisCopy.Year, thisCopy.Month, thisCopy.Day, thisCopy.Hour, thisCopy.Minute, thisCopy.Kind))
            {
                ThrowHelper.ThrowArgumentOutOfRange_BadHourMinuteSecond();
            }
        }

question 2: the first question kind of indicates that there's a problem with helper methods like this in the first place since presumably even if ValidateLeapSecond() is going to do the right thing itself, it's an attractive nuisance and should instead be passed a copy of "this" since presumably the caller will validate and then dereference this.

question 3: is there some marking, whether comments or compiler enforced to label methods or types which have been "sealed" like this so that they don't regress? I know that there are careful gatekeepers but implicit dereferencing can be insidious.

Would you be amenable to addressing this issue one type at a time? I've been AFK for quite a while and would like to dig back in to some issues like these.

**Comment by AArnott** [comment]
Structs are *not* copied when calling instance methods by default. I think they are copied when the struct is stored in a readonly field, unless the method itself has a readonly modifier on it (a relatively new thing). 

As you deduced in Q2, this leads us to want to make this a static method. It could take `in DateTime` as a first parameter so that the caller can pass its own _copy_ of `this` into the helper method. Thus only one copy is made and shared for the entire public entrypoint.
Q3: I don't think there is anything the compiler might offer to help with this. A new attribute with a new analyzer might do the trick at least to notify when it isn't done properly. Maybe an automated codefix could also be offered. If the analyzer triggered on any struct with a `readonly` modifier, that might do a decent job at selecting which structs should get the treatment.

Why would a readonly struct need to worry about mutations? Because it doesn't own its own memory, and its memory might be reassigned to a different value of the same struct.

**Comment by EmJayGee** [comment]
duh! of course, while you can't partially mutate a DateTime, you can wholesale overwrite it. Apologies for wasting the vertical space in this thread.

I'll put together what I think a fix for this for DateTime would look like and figure out what the right workflow is for this new world order of git and open source. I guess submitting a PR?

addendum:

I don't know that you can force, at the source level, a fix for this, without some kind of synchronization primitives or at least acquire/release semantics like C++ has, and you don't want acquire/release semantics like C++ has. I mean we can fix these examples easily but just because you make a copy of the value, if the compiler "sees" that the value should not have changed, there is no reason it (and now we have both the C# compiler and the code generator to ponder) can't make its own decision between using a register, allocating space on the frame or just re-fetching the value from the source value type. Legit tradeoffs between all three as you inline these kinds of methods into their callers.

In 99% of the cases for a pointer-sized value type in a small method like this it won't be an issue and the source code changes will coax the compiler to generate code that will usually do the right thing but as far as I know, there's still nothing forcing it. Oh well maybe defects for a future generation to worry about.

**Comment by AArnott** [comment]
This issue came from considering a struct that was particularly important to be thread-safe and would frequently be changed *in place* (`ImmutableArray<T>`). For that particular type, it was worthwhile to audit the type and fix it so all entrypoints observed its one, pointer-sized field no more than once. Because it's pointer sized, torn state was impossible, but it could still malfunction if the value were observed more than once, since the value could change in between, which isn't something the author of that method would likely have considered. Copying the value to a local is cheap for a pointer-sized struct, and frees the developer of such a concern.

When we're talking about other structs, it's less compelling. Structs that have multiple fields or exceed pointer-size cannot be read atomically anyway, so even one read at the entrypoint could still observe torn state. The larger the struct, the greater the perf hit from copying the value into a local as well. 

So, IMO if this issue leads to any code changes, those changes should probably be reserved to just structs that contain one pointer-sized (or shorter) field and are likely to exist in concurrent scenarios that rewrite the memory that stores that value. If such a struct can be identified, a PR with a fix for just that one struct is one I'd support. 

But I'm not actually on the .NET team, so I can't speak for whether they agree or would accept the PR.

**Comment by stephentoub** [comment]
> So, IMO if this issue leads to any code changes, those changes should probably be reserved to just structs that contain one pointer-sized (or shorter) field and are likely to exist in concurrent scenarios that rewrite the memory that stores that value. If such a struct can be identified, a PR with a fix for just that one struct is one I'd support.

Yes, in general we don't need or want to change all structs for this.  I expect there are very few (potentially zero) additional ones where we want to do something special here.  In general when we've authored public structs where we're concerned about this issue, it's already factored into the implementation, so this would mainly be about any places that slipped through.  If someone is interested in auditing and producing a list of structs they think would benefit from this, I'd be happy to review the list.  Otherwise, I'd be inclined to just close this issue and deal with any discovered problems on a case-by-case basis.

**Comment by EmJayGee** [comment]
Stephen, that do you think of @airbreather's example above?

It's not a particularly common case or anything but it is weird behavior. The problem is arguably that ToLocalTime() didn't capture the value before operating on it. (We can argue the correct mode of capture later but right now let's discuss whether to fix it and general scope.)

So should we fix this method?

If so, should we proactively fix this across DateTime? I think we can probably fix it with minimal to no performance hit depending on exactly what capture semantics are required.

Making the code changes across DateTime that discourage the coding pattern which leads to double-reads is a little larger but probably worthwhile if we think this was worth fixing.

Making the code changes to uniformly always capture "this" and then delegate to helper private statics to make the pattern 100% clear would cement the intent but would also be the largest source churn. I like obvious source but this code has been low churn for a long time so it's not obvious that it's valuable unless it was a step in establishing a larger pattern.

I'm game for digging in to this if there is an appetite. In any case, it seems like this is an old issue that should get figured out and I can help fix it or close it as by design since the docs pretty clearly say you need to have synchronization around it anyhow. (I couldn't find the referenced claims of thread safety from the original posting for this issue.)

**Comment by stephentoub** [comment]
> It's not a particularly common case or anything but it is weird behavior. The problem is arguably that ToLocalTime() didn't capture the value before operating on it. (We can argue the correct mode of capture later but right now let's discuss whether to fix it and general scope.)

Even if you were to make the proposed change, on a 32-bit system it still wouldn't solve "the problem" because the read could still be torn.

> If so, should we proactively fix this across DateTime?

I don't believe it's worth changing DateTime for this.
