### ISSUE TITLE
System.Xml.XPath to support XPath 2, XPath 3 and their XSLT variants

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#14819]
#### Motivation

`System.Xml.XPath` currently conforms with XPath 1.0 [<sup>[W3C-xpath-1]</sup>](http://www.w3.org/TR/xpath/) and XSLT 1.0 [<sup>[W3C-xslt-1]</sup>](http://www.w3.org/TR/xslt/) standards, but not XPath 2.0 [<sup>[W3C-xpath-2]</sup>](http://www.w3.org/TR/xpath20/), XPath 3.0 [<sup>[W3C-xpath-3]</sup>](http://www.w3.org/TR/xpath-30/), XPath 3.1 [<sup>[W3C-xpath-3.1]</sup>](http://www.w3.org/TR/xpath-31/), XSLT 2.0 [<sup>[W3C-xslt-2]</sup>](http://www.w3.org/TR/xslt20/) and XSLT 3.0 [<sup>[W3C-xslt-3]</sup>](http://www.w3.org/TR/xslt-30/). 

The missing standard implementations in BCL are required by many consumer scenarios, for which .NET applications rely on [third party libraries](http://stackoverflow.com/a/1533114/863980). One of the chief scenario is Content Query Web Part (CQWP) in SharePoint, where the users' XSLT code can be drastically minimized if v2 is supported by `System.Xml.XPath`. As for most parts, there are backward compatibility fallbacks available, that is; the code written in XSLT 2 precisely, can be expressed verbosely in XSLT 1 and since so forth.
### Pitfalls

Unfortunately, (besides the existing third-party libraries' APIs) I do not have an off-hand -- concrete -- method list to propose, as it requires further brain-storming on whether to auto-select processor based on the input or to explicitly separate the namespaces (`System.Xml.XPath2` and `System.Xml.XPath3`). 

The point to ponder being; since the sub-languages XPath 2 and XPath 3 intrinsically facilitates backward compatibility modes, see [XPath 2: J.1.3 Backwards Compatibility Behavior](http://www.w3.org/TR/xslt20/#backwards-compatibility-behavior) and [XPath 3: 3.10 Backwards Compatible Processing](http://www.w3.org/TR/xslt-30/#backwards), should the API be any different than the existing one and let consumers select the standard mode?

**Comment by vasont** [comment]
Seriously this got booted to next year/release? SMH

**Comment by danmosemsft** [comment]
I reached out to XmlPrime (https://www.xmlprime.com/xmlprime/) and they confirmed that they have completed .NET Core support now. This is a commercial offering, so this isn't a solution for everyone. If you try this - it would be great to post your results back here to help others in the community.

**Comment by TsengSR** [comment]
> I reached out to XmlPrime (https://www.xmlprime.com/xmlprime/) and they confirmed that they have completed .NET Core support now. This is a commercial offering, so this isn't a solution for everyone. If you try this - it would be great to post your results back here to help others in the community.

Slightly off-topic, but now I'm curious (since we're in urge need of such a thing).

The website doesn't seem updated yet with any new information (or downloads) about that one, but I'd be also interested in information on it, if it has async API what the performance is and if it utilize the new .NET Core APIs such as `Span<T>`/`Memory<T>` and/or pipelines? Especially compared to Saxon.NET (via IKVM on the full .NET Framework) and the .NET XSLT Processor ?

And whens that one supposed to get released to the public?

P.S. How about a proposal to acquire this guys? :P

**Comment by JDziurlaj** [comment]
It seems Microsoft does not invest in APIs where third parties are already providing products in (see SFTP). However I think this is different. XML is a core component used throughout the Microsoft ecosystem, and should be treated as such.

**Comment by LokiMidgard** [comment]
I think XPath 3 also support JSON which would be a good addition to the new JSON API's.

---------

I would also like to see Visual Studio tools supporting higher versions of XSLT.
In the past I had used a 3rd party library for .NetFramework. But for Visual studio constantly complained about the XSLT files in my project since it only understood XSLT 1.1 *(I think)*.

**Comment by stephen-lim** [comment]
XmlPrime is not usable for many projects. Their licensing is very restrictive and expensive that is unreasonable for many open source projects and small businesses. 

Please consider adding support for XSL 3 in .NET core. This is a much requested feature. It's long overdue.

**Comment by vasont** [comment]
My concern with XmlPrime is their website has not been updated since what appears to be 2018 🤷‍♂ and direct email to their sales email address has gone unanswered so far. If their responsiveness to a potential sale and their attention to detail in regard to their website content is any indication of their product quality, we should all have some reservations about paying for that product.

**Comment by michaelhkay** [comment]
Actually, XmlPrime's pricing reflects the cost of producing an advanced piece of technology. Be careful what you ask for: Microsoft's reluctance to implement these standards is strongly affected by (some) users' reluctance to pay for them.

**Comment by vasont** [comment]
What about a cost proposal to work out the code and a "gofundme" campaign to pay for it? I think there's enough demand for it, we all could throw in $20 and this would get done within the year.

**Comment by JDziurlaj** [comment]
All the XML specifications (save for a few by OASIS) were developed by the W3C and were meant to be part of modern web infrastructure such as web browsers. The shift from XHTML probably hampered that effort, but nonetheless people expected this to be core infrastructure (i.e. part of platforms).

**Comment by stephen-lim** [comment]
> What about a cost proposal to work out the code and a "gofundme" campaign to pay for it? I think there's enough demand for it, we all could throw in $100 and this would get done within the year.

I'm happy to fund the $100 but how do you know it's enough to get developed? I think XSL is not a simple implementation. It takes a lot of hard work to build.

**Comment by hmobius** [comment]
It seems pretty clear given how long this issue has been around that it really isn't a priority for Microsoft, and that this needs to be an open source effort. It's also clear that implementing XSLT is not a trivial thing. There is a list of projects [here](https://github.com/maxtoroq/dotnet-xml#xpath-xquery-and-xslt) but the only one we might be interested in is a form of [XPath2.net](https://github.com/StefH/XPath2.Net). Saxon is open source but only in Java so maybe there is scope for a port to .NET rather than the transpiled .NET version currently available. The plus side at least is that the test suite is available as XSLT, XPath (and XQuery) are clearly defined standards.

**Comment by vasont** [comment]
> > What about a cost proposal to work out the code and a "gofundme" campaign to pay for it? I think there's enough demand for it, we all could throw in $100 and this would get done within the year.
> 
> I'm happy to fund the $100 but how do you know it's enough to get developed? I think XSL is not a simple implementation. It takes a lot of hard work to build.

It most certainly would be an effort to get public support for this. I would think you would start with the individuals who up-voted this issue on Microsoft's user voice site. From there, spreading the initiative among .NET user groups, etc. I would think 1,000 devs/companies offering $100 each would do the trick to get the effort underway and to a working beta release. 🤷‍♂

**Comment by terrajobst** [comment]
@michaelhkay 

> Be careful what you ask for: Microsoft's reluctance to implement these standards is strongly affected by (some) users' reluctance to pay for them.

I don't think that's true. Our primary motivation for doing a platform feature is:

1. Is this a core concern for many users?
2. Would adding it to the platform benefit the feature?
3. Is this a feature that we likely need as a building block for other platform features?

I'm not aware of cases where pricing of external components have influenced our decision; however, the availability of widely used external libraries (commercial or not) does influence our decision how beneficial/harmful our involvement would be.

In the case of XSLT 3, I think our interest (or lack of thereof) is informed by the direction of the web industry as a whole. Right now, I can't see a world where supporting it would likely become a priority for us.

**Comment by vasont** [comment]
Thanks Immo. So that sums it up gang that's it's likely not going to happen. OSS initiative will be the only solution here. Getting technical expertise and developers to dedicate the effort to implement something similar to Saxon or XmlPrime is a relatively large undertaking.

**Comment by terrajobst** [comment]
Pretty much, which is why I'm closing this.

**Comment by jeffska** [comment]
@terrajobst 
> In the case of XSLT 3, I think our interest (or lack of thereof) is informed by the direction of the web/client industry as a whole. Right now, I can't see a world where supporting it would likely become a priority for us.

I think that's been my frustrations for a long time. In my view XSLT is much less useful for the "traditional" web/client activities than it is for a more generalized standard data transformation framework. I've used XSLT in several project for that type of role, to good effect. However, the restriction of only having  XSLT 1.0 as part of the standard environment limits capabilities and further adoption for those other applications. It's a catch-22.

I've been waiting for XSLT > 1.0 for over 10 years now. Sounds like it's still not going to happen in standard libraries.

**Comment by stephen-lim** [comment]
> @michaelhkay
> 
> > Be careful what you ask for: Microsoft's reluctance to implement these standards is strongly affected by (some) users' reluctance to pay for them.
> 
> I don't think that's true. Our primary motivations for doing platform features are:
> 
> 1. Is this a core concern for many users?
> 2. Would adding it to the platform benefit the feature?
> 3. Is this a feature that we likely need as a building block for other platform features?
> 
> I'm not aware of cases where pricing of external components have influenced our decision; however, the availability of widely used external libraries (commercial or not) does influence our assessment of how beneficial/harmful our involvement would be.
> 
> In the case of XSLT 3, I think our interest (or lack of thereof) is informed by the direction of the web/client industry as a whole. Right now, I can't see a world where supporting it would likely become a priority for us.


If this is the determining factor, then we can argue the case:

1. Is this a core concern for many users? 
Yes, XSLT 2+ was one of the top 3 most requested feature back when it was voted through the VisualStudio UserVoice. See [archive link has 2817 votes "Implement XSLT 3.0 for .NET"](https://web.archive.org/web/20190321120101/https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/category/31481--net)

2. Would adding it to the platform benefit the feature? 
Absolutely, there are no available 3rd party open source, free or otherwise affordable solution for open source projects and small businesses. XSLT 2 or 3 brings a wealth of improvement that fixes the shortcomings of XSLT 1.0 increasing productivity.

3. Is this a feature that we likely need as a building block for other platform features? 
Yes, XSLT is a standard.  It is widely used in:

- [Sharepoint](http://mundrisoft.com/tech-bytes/how-to-customize-list-view-web-part-using-custom-xslt-in-sharepoint-2013/)
- SQL Server has native support for XML column and XPath query. One can even write managed code to return transformed XML using XSL.
- Many popular CMS like Umbraco, DNN still use XSLT to transform XML data for display
- Many large enterprise still use XML (probably more than JSON) and need ability to manipulate the XML easily.

**Comment by danmosemsft** [comment]
@stephen-lim  your examples show that XML and XSLT are widely used but not v3 specifically.

**Comment by stephen-lim** [comment]
> @stephen-lim your examples show that XML and XSLT are widely used but not v3 specifically.

SQL server partially supports Xpath v2. There isn't wide support for v3 because Windows/ASP.NET software like Sharepoint, DNN, Umbraco ultimately rely on the .NET libraries, which only supports XSLT v1. On the other hand, you can find many more examples of v2 and v3 support in Java apps.

The short story is thousands of developers have been asking Microsoft to support v2 for the last 10 years. At one point, Microsoft said they would strongly consider implementing XSLT 2, but that stopped as soon as they started working on LINQ and XQuery. Fast forward today, the v3 spec is out and the hope is that Microsoft should add support for v3, if not v2.

**Comment by TsengSR** [comment]
> @stephen-lim your examples show that XML and XSLT are widely used but not v3 specifically.

Well, to be honest, XSLT 2.0 and XPath 2.0 would be a **huge** improvement already. XSLT 1.0 is very very limiting  (major blockers being lack of user defined functions - You just have templates, but these can't be used as part of XPath Expressions), same applies for XPath 2.0 (Lot of functions missing, no white-spaces for Namespaces (i.e. no `/*:elementName``)l

Sure, XPath 3.0 and XSTL 3 would be awesome (i.e. exception throwing and try/catch from XSLT). But XSTL 1.0 is just seriously lacking to much features to really consider it. 

I'm rather tempted to extract the whole XSLT processor as an Java-based Microservice, rather than falling back to XSLT 1.0/XPath 1.0 (Saxon.NET via IKVM.NET on .NET Framework is not an option)

**Comment by michaelhkay** [comment]
As far as Saxonica is concerned, we are eagerly awaiting technical details of what Microsoft is proposing to offer under the "Java interoperability" feature promised in the .NET 5 announcement; that will determine our forwards path for Saxon on .NET. If anyone knows of any details that have been published since the May 2019 announcement, please share!

**Comment by vasont** [comment]
Regarding Saxon and .NET Core, IKVM is obviously shelved. Why not take the runtimes, decomiple using something like DotPeek to C#, and refactor to .NET Core, then implement Saxon to use those libs?

**Comment by michaelhkay** [comment]
We're looking at a number of options (which is why we really want to know what .NET 5 will offer), but obviously we're very keen to avoid forking the source code.

**Comment by TsengSR** [comment]
> Regarding Saxon and .NET Core, IKVM is obviously shelved. Why not take the runtimes, decomiple using something like DotPeek to C#, and refactor to .NET Core

Not sure what you mean. IKVM.NET is open source... there is just no one to take it over. IKVM.NET author already [offered](http://weblog.ikvm.net/2017/04/21/TheEndOfIKVMNET.aspx) others to take over the project under the condition it's renamed to something else. 

But not sure how much sense that makes anyways, since (as far as I know) it required a lot of changes for each new JRE version, which now ship bi-annually rather than once every 3-5 years

**Comment by hmobius** [comment]
@michaelhkay Completely understand about forking the source code but I for one would be very interested in working on a port around XSLT\XPath in .NET using the new features we have in C#. I'm curious if rather than forking the source code, we could fork \ port the code for the test suite and work from there.

**Comment by michaelhkay** [comment]
There are good test suites for XSLT 3.0, XPath 3.1, and XQuery 3.1 on GitHub, and we're happy to share our test drivers. The bulk of the test material is in XML files and is 100% portable; creating a test driver to run the tests on a particular platform is a fairly trivial exercise. The only other requirement is API testing, which is specific to each platform/API/language-binding. But the source code for the product itself is 600K lines of Java so that's a major undertaking.

**Comment by JDziurlaj** [comment]
I would assume the problem with SAXON isn't so much the source code being in Java, as it having dependencies on third party Java libraries, which may be hard to decouple.

**Comment by michaelhkay** [comment]
No, that's not the case. Saxon's dependencies on third party (non-JDK) libraries are very easily isolated and decoupled. Where such dependencies exist (e.g on the ICU-J library) you can either port the third party code as if it were part of Saxon, or you can make do without it.

**Comment by kant2002** [comment]
> There are good test suites for XSLT 3.0, XPath 3.1, and XQuery 3.1 on GitHub, and we're happy to share our test drivers. The bulk of the test material is in XML files and is 100% portable; creating a test driver to run the tests on a particular platform is a fairly trivial exercise. The only other requirement is API testing, which is specific to each platform/API/language-binding. But the source code for the product itself is 600K lines of Java so that's a major undertaking.

Where the test cases? Can you give a link?

**Comment by michaelhkay** [comment]
https://github.com/w3c/xslt30-test (XSLT 3.0)
https://github.com/w3c/qt3tests (XQuery 3.1, XPath 3.1)
https://github.com/w3c/xsdtests (XSD 1.1)

In each case the test suites also include tests for earlier versions, labelled as such in the test metadata.

**Comment by am11** [comment]
+1, spec suites are the way to go for realistic and reliable conformance testing. I have some experience with writing spec suite adapter for Sass' and YAML's .NET implementations. If the porting effort transpires out in open, I am willing to contribute. :)

**Comment by MicahEdwards** [comment]
> I reached out to XmlPrime (https://www.xmlprime.com/xmlprime/) and they confirmed that they have completed .NET Core support now. This is a commercial offering, so this isn't a solution for everyone. If you try this - it would be great to post your results back here to help others in the community.

A .Net Core trial version of XmlPrime 4.1.3 is now available as a signed NuGet package. 

Just send me a message or drop us an email ( info@xmlprime.com ) saying what area you would like to test it in and we will send you a download link.

Micah Edwards.
XmlPrime.

**Comment by DanAtkinson** [comment]
@MicahEdwards What are the costs? You don't display them online. Some pages say that I can purchase licenses online but then when I go to those pages, I'm told that I can't purchase it online.

So I guess the simple question is where can I see a breakdown of your prices? I shouldn't need to contact you to get these - they should just be available on your website.

**Comment by alirobe** [comment]
Super glad to see this was unlocked, unfortunate that 'still no action' is the current plan.

**Comment by wstaelens** [comment]
@TsengSR  e-invoicing in Europe is based on Peppol BIS Billing 3.0 (at this moment).
The official downloads provide Schematron files and stylesheet (xslt) for visualizing and validating. The schematron itself is based on xslt2. https://docs.peppol.eu/poacc/billing/3.0/2025-Q4/ 

I understand that you are not familiar with it because you confuse that PDF embeds xml. It is an xml with even an optional pdf.
Meaning whole Europe (and later on PINT) will have to deal with it.

But I agree, @michaelhkay could play an important role into this.

**Comment by danvy** [comment]
It's funny to see how many dev teams are embracing non Microsoft stack to solve this issue in Europe with the emergence of electronic invoicing.
Who would have guess that this good old XML would resurface in 2026 ?

**Comment by michaelhkay** [comment]
Indeed, XML has always remained popular with people who have to deal with complex documents, but the adoption of electronic invoicing is prompting a lot of people outside that community to rediscover it.

**Comment by TsengSR** [comment]
@dannyvv 
> It's funny to see how many dev teams are embracing non Microsoft stack to solve this issue in Europe with the emergence of electronic invoicing. Who would have guess that this good old XML would resurface in 2026 ?

Problem lies more in companies using ancient XML based formats in 2026, when you have gRPC, json and GraphQL, not the lack of XSLT processors for some ultra-niche use case.

**Comment by michaelhkay** [comment]
>using ancient XML based formats

You're missing the point. XML has always been about stability and longevity, not about following the latest fashion. For financial documents you need to set a standard and stick with it for 50 years or more, you can't go making incremental improvements all the time. And electronic invoicing is hardly "ultra-niche".

**Comment by TsengSR** [comment]
> You're missing the point. XML has always been about stability and longevity, not about following the latest fashion. For financial documents you need to set a standard and stick with it for 50 years or more, you can't go making incremental improvements all the time. And electronic invoicing is hardly "ultra-niche".

Then people would still be using EDIfact. Obviously people are fed up with EDIfact and it being error prone due more and more people implementing it awfuly. You'd be surprised how many companies generate EDIfact files without any library just by concatting it or some spaghetti string splitting and you almost daily have issues with peoples documents not being processed due to some formatting or syntax errors, missing required fields and stuff. 

If people really would have wanted something stable with wide addopttion, then json would been the tool/format of choice. Its supported in litterally on any platform and guaranteed to last the next few decades. 

Unlike XSLT where you only have 1 ancient Java Library (Xalan), one not-so ancient Java library (Saxon) and one I forgot for C (iirc mostly ancient too, read: xstl 1.0 or so) and smoe half. Picking XML fora ny type of exchange format is the worst possible choice considering its platform adoptability. Its literally a lock-in in Java or C world. 
There's literally no usable XSLT processor other then the one you maintain. It's literally counter-intuitive to adopt/design an exchange format that only runs on a single platform, developed by a single company.

**Comment by michaelhkay** [comment]
@TSengSR No doubt you could have designed it better if the job had been left to you. But it wasn't, it was done by international committees over many years (indeed decades). For those interested, there's a good summary of the state of play with e-invoicing standards at https://e-invoice.be/blog/xml-invoicing . If you're operating in this space, you don't get to choose what format to use, you have to live with what the experts have chosen. Standards are rarely perfect.

**Comment by alirobe** [comment]
Oh man. I remember when I was a student, and I thought those sort of opinions mattered too. We should have some grace for people who have opinions unencumbered by reality. Just let it be. We all have more productive things we can do than engage with that. 

I like the idea of splitting this ticket into components. However given how well specified the problem domain is, I am curious if you could just feed this whole ticket into an LLM and have a first shot at a version. It would likely need some back/forth with the community to tease out design decisions; but honestly given the lack of interest from Microsoft, it might be better than nothing.

**Comment by tonyqus** [comment]
Sorry, I don't live in Europe. Can someone explain me what's the gap of EDIFact implemention in .NET? Which library do you usually use? 

I'm willing to dive into this and see whether I can fill the gap with a new open source library.

**Comment by AndersMad** [comment]
"To see life as it is, and not how it should be...." There is a reason HTML is not JSON, and Microsoft did not convert .csproj files to JSON either (they tried I believe). As a full-stack developer, I both love (and hate) XML and JSON - each has its pros and cons. Namespaces and comments in JSON? But the JSON vs. XML debate is pretty irrelevant to this thread, imho (spite I am at it here).

And yes, why not give it a try with AI? By now I think it's pretty clear MS doesn't care much. I am going to try later to make it fully async XPath, a JSON navigator and extended language etc.

**Comment by alirobe** [comment]
> "To see life as it is, and not how it should be...." 

Indeed. The universe is not obliged to make sense to us. 

I'll be curious to hear how you go with it.

**Comment by am11** [comment]
> I like the idea of splitting this issue into smaller components.

In my defense, this issue predates the documentation of the API review process (https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md). I agree that, in its current form, it isn't specific enough to gain traction with maintainers or to be truly actionable. A concrete proposal would be needed. That said, there is also a valid counter‑argument: since most platforms don't provide these features out of the box, developers often rely on external libraries. In that sense, .NET isn't unique, though we still expect it to be the best/richest (in external library-free form). 😎

**Comment by TsengSR** [comment]
> That said, there is also a valid counter‑argument: since most platforms don't provide these features out of the box, developers often rely on external libraries. In that sense, .NET isn't unique, though we still expect it to be the best/richest (in external library-free form). 😎

I don't think people mind if its part of the runtime or external library, they more of "expect" it to be maintained by a big company (preferably the one who maintains the runtime) and with first-class support, i.e. utilizing all of the new performance benefits that .NET brought in since .NET Core 3.0 onwards) with the funds to do so rather than to depend on 1-man projects that would be abandoned at any point. 

`System.Text.Json` is a good example of this adoption and its received rather well, as its both from microsoft and a first-class citizen in .NET ecosystem. 
Most company I've worked with would plain out reject any library thats maintained as a hobby by a single person. And for most use-cases also reject a paid solution that costs middle 5 to 6-figure costs annually, as most customers these type of work/implementation is aimed towards are SMBs who simply won't pay 100k annually (or even single-time payment) to implement e-invoicing, order, delivery or whatever type of documents they need. 

The xslt technology has been very niche for the past 15-20 years, and being very niche usually means used/operated by enterprises, who are rather reserverd on takings risks on libraries or software with uncertain future. Most use-cases I've seen were migrating old systems based on it (BPM Workflow-Engines and SOAP Services namely, which is where a lot of the invoicing/order type of formates are processed in) or for formating documents (XML-FOP) for printing (including PDFs).

**Comment by michaelhkay** [comment]
@TsengSR If you have good well researched data on adoption, it would be great to see it, because I don't, and it would add a lot of value to this thread. If you just want to share opinions based on your personal experience, then forget it: you don't see the big picture any more than anyone else does.

**Comment by wstaelens** [comment]
@michaelhkay go ahead and shake hands with Microsoft ;-)

**Comment by mikkeljohnsen** [comment]
Please implement this. We need this to validate OIOUBL Invoice etc. here i EU
