### ISSUE TITLE
TimeZoneInfo should have consistent Ids across Windows and Linux

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#14929]
[AB#1179633](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1179633)

Currently Windows has TimeZoneInfo.Id values like "Pacific Standard Time" and "Eastern Standard Time".  But on Linux they are "America/Los_Angeles" and "America/New_York".

We should make these Ids consistent across platforms so the same code can run on both Windows and Linux.  Currently if you call TimeZoneInfo.FindSystemTimeZoneById you need to pass in different strings between Windows and Linux.

**Comment by mynkow** [comment]
Greetings from mid 2020.

Hala

**Comment by molekm** [comment]
Still waiting on something so crucial to be solved especially with Docker Linux/Windows.

**Comment by tarekgh** [comment]
@molekm can't you use the library https://github.com/mj1856/TimeZoneConverter?

**Comment by timmydo** [comment]
It would be nice if something like `DOTNET_SYSTEM_GLOBALIZATION_APPLOCALICU` (from https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu) existed for the tz data. TimeZoneConverter would only be a solution for people that can rewrite their code to point to the that library.

**Comment by udlose** [comment]
> @molekm can't you use the library https://github.com/mj1856/TimeZoneConverter?

@tarekgh With all due respect, we shouldn't have to use an external library to do something so fundamental as working with TimeZones.  I had hoped that the abstraction of "concern of which OS my app is running on" should be handled by .NET Core as that was one of the main goals of the .NET Core platform. Very disappointed that this issue has been opened for a little over 5 years now with little more than "...use an external library to do this" as a solution.

Can you please provide an update on where this is in progress?  .NET 5.0 is slated for release in November 2020 which is less than 3 months away now.

**Comment by tarekgh** [comment]
@udlose I agree with you in principle. The issue here we were trying to avoid in the .NET is to carry Time zone data which will need to get updated when something change. This create a nightmare in servicing old versions of the .NET especially time zone is a core functionality. That is why we were planning to get into the point to depend on something that we can use and not require servicing the .NET. 

In 5.0 we started to use ICU library for globalization support but this is huge work as globalization is kind affecting most of the basic functionality in the .NET. We are trying to stabilize the product with using ICU. When I suggested using TimeZoneConverter it was a temporary till the framework introduce the functionality.

We have the plan in 6.0 to look using ICU which we already integrated in 5.0 to do the TZ Ids conversions and possibly introduce more better interfaces for time zone in general. I hope this clarify why we delayed this work but I am emphasizing this is in our near future plan to get it done. Thanks for your understanding.

**Comment by ericsampson** [comment]
@tarekgh thanks for the update. It's not a small task to do 'well'. I'm happy to see the ICU changes coming in 5.0

**Comment by udlose** [comment]
@tarekgh Thank you for the update and I do appreciate the challenge you face.  I am happy to see there is a plan for it in the near future and I'm looking forward to leveraging it.  In the meantime, I will use the [TimeZoneConverter ](https://github.com/mj1856/TimeZoneConverter)you suggest.

**Comment by tarekgh** [comment]
This is addressed by https://github.com/dotnet/runtime/pull/49412
