### ISSUE TITLE
HTTP2: Two remote server tests occasionally timing out in CI

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#1580]
These are tests I'm modifying to run with HTTP2 in https://github.com/dotnet/corefx/pull/39343 but disabling for now.

Sometimes in CI, these tests timeout. Likely they are just running really slowly in CI and increasing the timeout would make them more reliable. We should investigate and confirm and change the timeout as appropriate.

PostAsync_RedirectWith307_LargePayload
PostRewindableContentUsingAuth_NoPreAuthenticate_Success

**Comment by maryamariyan** [comment]
Perf PRs


| PR | Fixes | Perf | Author |
|----|-------|--------|--------|
| Remove allocations from OptionsCache<T> and OptionsManager #45229 and #45231 | Contributes to #44598 | #Options | stephentoub |
| Revise UnnamedOptionsManager to avoid allocation in ctor #49883| - | #Options | stephentoub |
| Remove array enumerator allocations #49970 | - | #Options | davidfowl |
| Fixed regression caused by performance change #51032 | Fixes #51023 | #Options | davidfowl |
| Remove some allocations related to logging configuration (#50055) | - | #Logging | davidfowl |
| few minor MemoryCache perf improvements #44797 | - | #Caching | adamsitnik |
| Remove more LINQ usage from various dotnet/runtime libraries #44964 | - | #Caching/Logging | stephentoub  |
| More MemoryCache perf improvements #45280 | - | #Caching | adamsitnik |
| Remove some allocations related to storing CacheEntry scopes #45563 | - | #Caching | adamsitnik |
| Reduce CacheEntry size #45962 | - | #Caching | adamsitnik |
| Remove unnecessary closure / delegate allocation from CallSiteFactory.GetCallSite #44755 | Related to #44598 | #DI | stephentoub |
| Pool the underlying list and dictionary in scopes. #50463 | Fixes #47607 | #DI | davidfowl |
| Avoid dictionary lookup for singleton services #52035 | - | #DI | davidfowl |
| Remove closure allocations from ServiceCollectionDescriptorExtensions #44696| - | #DI | benadams |
| Remove lots of boxing from EnvironmentVariablesConfigurationProvider.Load #47453 | - | #Configuration | stephentoub |
| Change Configuration.Json to use a regular Dictionary. #50611 | - | #SizeReduction #Configuration | eerhardt |

**Comment by ManickaP** [comment]
Triage: either fix the tests or get rid of them or just disable them in CI, but run them locally if it's impossible to run in CI.
