### ISSUE TITLE
Add ChaCha20-Poly1305 to CoreFX

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/runtime#16010]
Add ChaCha20-Poly1305 to CoreFX's cipher suite.  It is a very fast AEAD (significantly faster than AES-GCM except when the latter has hardware support) that is immune to side channel attacks and is relatively easy to implement.

It is included in OpenSSL 1.1 or later, or in libSodium.

**Comment by ohsorry** [comment]
AEAD_CHACHA20_POLY1305 uses chacha encryption, it's fast.
[ChaCha20 and Poly1305 for IETF Protocols](https://tools.ietf.org/html/rfc8439)

**Comment by oliverjanik** [comment]
Seconding this request. Net core needs to support modern cryptographic suit. It's lagging terribly compared to e.g. Go ecosystem.

It's been 4 years?

Can this make it into .net 5?

**Comment by bartonjs** [comment]
> Can this make it into .net 5?

It definitely can't make it into 5, since 5 is pretty much wrapped up (only critical bug fixes at this point).

> It's been 4 years?

We have a policy of not implementing cryptographic primitives, but deferring to OS libraries.  As of when I last looked, Windows does not support ChaCha/Poly.  This means that whatever our ChaCha/Poly implementation looked like it wouldn't work on Windows.  That means we'd only go from "not available" to "not available half the time", which doesn't currently feel like a significant win.

**Comment by oliverjanik** [comment]
Maybe time to reexamine the policy?

 When it comes to modern security features, other platforms are leaving .net core in the dust. AES-GCM only became available in .net core 3.

Heaps of libraries and SDKs bundle BouncyCastle due to lack of modern cryptograhy in dotnet.

Officially sanctioned and supported modern crypto would be a big win for the platform.

**Comment by DemiMarie** [comment]
@bartonjs IIRC there are formally verified, reasonably-performing implementations of both ChaCha20 and Poly1305, meaning that we can bundle them without worrying about future bug fixes (since none will be needed).

**Comment by ohsorry** [comment]
I don't know why the native Windows crypto library is so conservative.
chacha is fast, a managed implementation is also acceptable.

**Comment by FiniteReality** [comment]
Supporting XSalsa20-Poly1305 would mean I don't have to distribute builds of libsodium for users of my library, and would make installation *so* much easier.

**Comment by DemiMarie** [comment]
I strongly suggest that we bundle a formally-verified implementation on platforms where no implementation is provided by the OS.  A formally verified implementation (by definition) has a machine-checked proof of correctness, so we do not need to worry about having to patch bugs in our crypto, which I suspect is the primary reason for not bundling crypto primitives.

**Comment by GrabYourPitchforks** [comment]
It's not just "correctness". It's also about things like being resilient to side-channels.

To be resilient against side channels, the implementation must control many details of execution. As a non-exhaustive list, the implementation must tightly control: register allocation, exact locations of all data in memory and on the stack, how context switches take place, how jump targets are aligned, when page faults occur, and so on.

This is why you often see battle-tested implementations written in assembly rather than higher-level languages. The more abstracted the language is from the raw codegen, the less ability the author has to make their implementations resilient to these types of flaws. It's hard to get even something seemingly trivial like [a fixed-time equality check](https://github.com/dotnet/runtime/blob/035ebeab160b9a281e5fbb3fa0c237f244c81b7a/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CryptographicOperations.cs#L31) solid in C#. We still need to check every release that a JIT optimization didn't break our assumptions there - and that's just a single twenty-line method! The fact is that .NET's managed runtime doesn't provide enough low-level control for somebody to confidently write a secure cryptographic primitive. And that's fine! Not all code belongs in the managed layer; that's what unmanaged code and p/invokes are for. The solid implementations of these algorithms are written in \[generally\] assembly, and we p/invoke into them.

**Comment by DemiMarie** [comment]
We could still bundle the assembler implementation, or P/Invoke into a bundled BoringSSL.

**Comment by ohsorry** [comment]
I agree that tampering obfuscated assembly is more difficult than IL , but it has nothing to do with side-channel attacks like variable-time equality.

**Comment by oliverjanik** [comment]
As a user of dotnet, I care about batteries included official API, whether managed or just a wrapper around BoringSSL does not matter one bit to me.

If Microsoft does not provide reliable modern crypto, what chance does a majority of dotnet developers stand when evaluating random Nuget packages on their own?

All of this reflects back on the platform. Help dotnet developers do the *right* thing.

**Comment by GrabYourPitchforks** [comment]
API proposal approved via https://github.com/dotnet/runtime/issues/45130.
