### ISSUE TITLE
MulticastDelegate, BeginInvoke throws NotSupportedException

### ISSUE THREAD

**Issue by christiannagel** [dotnet/runtime#16312]
Invoking the BeginInvoke method of a MulticastDelegate derived delegate compiles fine with .NET Core, but throws a NotSupportedException.
Should this really be the case?
Sample code is here, .NET 4.6 runs ok, but .NET Core fails with the mentioned exception:
https://github.com/ProfessionalCSharp/ProfessionalCSharp6/tree/master/Synchronization/SynchronizationSamples/AsyncDelegate

Thanks,
Christian

**Comment by danmoseley** [comment]
> Generally the compiler enables / disables features by looking at the types for hints. Is there anything we can key on here to know to exclude these members?

this is now an old issue, but an internal customer pointed me at it today and I see there have grown to be a lot of thumbs up above, over time. @jkotas did you see @jaredpar question above -- do you think it might be feasible?

**Comment by jkotas** [comment]
This should be an analyzer. It is proposed by https://github.com/dotnet/roslyn-analyzers/issues/2807.  https://github.com/dotnet/roslyn-analyzers/pull/2972 was an attempt to implement this analyzer, but it was closed due to unaddressed feedback.

Changing Roslyn to stop emitting `BeginInvoke`/`EndInvoke` would be a breaking change. This was discussed in https://github.com/dotnet/roslyn/issues/50826. I think we can consider it after the analyzer is in place for several years and we have reasonable confidence that it won't affect too much code.

Resolving as duplicate of https://github.com/dotnet/roslyn-analyzers/pull/2972

**Comment by danmoseley** [comment]
Got it, thanks for the links. Perhaps someone here might be interested in working on that analyzer.

**Comment by danmoseley** [comment]
cc @wikimonkey in case he's interested in the above.

also linking https://github.com/dotnet/docs/pull/34937
