### ISSUE TITLE
Support of additional port namens (ttyGS0)

### ISSUE THREAD

**Issue by Johonis** [dotnet/runtime#1677]
Unfortunately only standard serial names are supported. I am currently using a generic USB serial gadget that creates a serial port. This is displayed under /dev/tty as "ttyGS0" and creates a directory in /sys/class/tty but without the required folder **/sys/class/tty/tty*/device**/ and **/sys/class/tty/tty*/device/id** or the director **"of_node"**

Unfortunately I can't modify the gadget so that the criteria required in the code (**src/libraries/System.IO.Ports/src/System/IO/Ports/SerialPort.Linux.cs**) is fulfilled.

It would be very helpful to adjust the criteria in the code to allow more names as just ttyS*
` bool isTtyS = entry.Name.StartsWith("ttyS");`

For alternative suggestions I would also be pleased.
Thanks and best regards

**Comment by wfurt** [comment]
You still should be able to open that port and use it AFAIK. Just the list of ports will miss it if you have specialty hardware. I'm concern is we can ever return completely wrong device if the filter is to broad.  

cc: @krwq

**Comment by krwq** [comment]
Yes, I'm generally fine with adding ttyGS to be listed in GetPortNames since those seem to be GigaSet phones or similar devices. I'm not in favor off adding everything though since that seems to show more than what you normally need. As @wfurt mentioned opening should still work even if device is not listed.

This is documented in https://www.kernel.org/doc/html/latest/isdn/gigaset.html
Note that ttyG seem to be too broad.

Are you interested in sending a PR @Johonis?

**Comment by Johonis** [comment]
It's not only adding GS0 to the query.
The gadget, you can find https://www.kernel.org/doc/Documentation/usb/gadget_serial.txt 
generates a generic serial device. Unfortunately I am currently not able to provide a pr, but I am working hard to present a solution.

**Comment by krwq** [comment]
@Johonis perhaps for ttyGS0 we can remove the extra checks which don't apply there, the extra checks are mainly done to filter out bogus serial ports from ttyX list

**Comment by Johonis** [comment]
This is a good idea, since you cannot know what features other devices that are not yet supported have.
That could definitely work.
