### ISSUE TITLE
[Linux][RHEL] Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#168]
https://helix.dot.net/api/2019-06-17/jobs/01c8c73c-d102-4ec4-8680-1e9dd63d454b/workitems/JIT.Stress/console

https://dev.azure.com/dnceng/public/_build/results?buildId=433392&view=logs

```
JIT/Stress/ABI/tailcalls_do/tailcalls_do.sh [FAIL]
      
      Assert failure(PID 24244 [0x00005eb4], Thread: 24253 [0x5ebd]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.\n" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
          File: /__w/2/s/src/coreclr/src/vm/hosting.cpp Line: 268
          Image: /home/helixbot/work/01c8c73c-d102-4ec4-8680-1e9dd63d454b/Payload/corerun
      
      /home/helixbot/work/01c8c73c-d102-4ec4-8680-1e9dd63d454b/Work/8543e0ef-3fed-493d-b02b-356fdd033e54/Exec/JIT/Stress/ABI/tailcalls_do/tailcalls_do.sh: line 294: 24244 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /home/helixbot/work/01c8c73c-d102-4ec4-8680-1e9dd63d454b/Work/8543e0ef-3fed-493d-b02b-356fdd033e54/Exec/JIT/Stress/Reports/JIT.Stress/ABI/tailcalls_do/tailcalls_do.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/01c8c73c-d102-4ec4-8680-1e9dd63d454b/Payload/corerun tailcalls_do.dll '--tailcalls' '--num-calls' '1000' '--no-ctrlc-summary'
      Stressing tailcalls
      OSVersion: Unix 2.6.32.754
      OSArchitecture: X64
      ProcessArchitecture: X64
      Selecting SysV ABI
      50 callers done (49 successful tailcalls tested)
      100 callers done (98 successful tailcalls tested)
      150 callers done (146 successful tailcalls tested)
      200 callers done (194 successful tailcalls tested)
      250 callers done (244 successful tailcalls tested)
      300 callers done (294 successful tailcalls tested)
      350 callers done (339 successful tailcalls tested)
      400 callers done (388 successful tailcalls tested)
      450 callers done (434 successful tailcalls tested)
      500 callers done (483 successful tailcalls tested)
      550 callers done (532 successful tailcalls tested)
      600 callers done (581 successful tailcalls tested)
      650 callers done (631 successful tailcalls tested)
      700 callers done (681 successful tailcalls tested)
      750 callers done (730 successful tailcalls tested)
      800 callers done (779 successful tailcalls tested)
      850 callers done (828 successful tailcalls tested)
      900 callers done (878 successful tailcalls tested)
      950 callers done (927 successful tailcalls tested)
      1000 callers done (975 successful tailcalls tested)
      975 tailcalls tested
      24 rejected tailcalls. Breakdown:
      [100.00%]: Not enough incoming arg space
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
```

**Comment by tommcdon** [comment]
@josalem can you take a look?

**Comment by noahfalk** [comment]
> The easiest way actually seems to be to put the gCurrentEventPipeThreadHolder as a member to the Thread class.

Unfortunately this thread-static data was specifically moved off of the Thread class because it needs to be used for GC events and the GC threads don't have a Thread object assigned to them. @josalem is researching if we have other options.

**Comment by janvorli** [comment]
@noahfalk got it. Then it seems we can just change the gCurrentEventPipeThreadHolder to be just a pointer instead of the wrapper and destroy the underlying object in Thread destructor. For GC threads, we don't need to destroy it as they never die.

**Comment by josalem** [comment]
I was able to repro this in a RHEL6 vm, but I haven't started work on a change to bypass the bad behavior.  I am curious what the priority/scope of a "fix" for this would look like in light of #423.  Is this high enough priority to "fix" for 3.0/3.1?  Is this worth "fixing" in 5.0 if we are dropping support for this OS version in 5.0?

**Comment by janvorli** [comment]
I would like to fix that even in 5.0 just to get rid of the last place where a destructor is called at process exit.

**Comment by josalem** [comment]
Okay, let me add this to the backlog.

**Comment by josalem** [comment]
> The EventPipeThread has an array of EventPipeSessionStates on it. Each of those have an EventPipeThreadHolder field on them which creates a copy of the Wrapper and acts as a hard reference to the underlying memory. This means that the original Wrapper does get deleted on physical thread exit, but its destructor just decrements the internal ref count of the EventPipeThread object. That memory won't be deleted until its ref count hits zero (it calls delete this on itself), which won't happen until the EventPipeBufferManager calls DeallocatedBuffers when all EventPipe sessions have closed.

Quoting my comments on the PR I opened and then closed.

The issue here seems to be one with the c++ runtime version in RHEL6 and not an issue with the code itself.  I'm going to do a little more investigation into what is specifically causing the error, but I'm inclined to believe this is an issue with the c++ runtime incorrectly deleting the `thread_local` `Wrapper<...>` member on `EventPipeThread`.  `EventPipeThread` has acquire and release semantics where an internal ref count is incremented and decremented.  When that count hits 0, it calls `delete this` on itself.  The main thread will keep a hard reference to the `EventPipeThread` via the `thread_local` wrapper, which is how we get into the at_exit delete case.

I see this as a couple different issues of varying severity discovered here:
1. RHEL6 (glibc 2.12) has a bug that somehow results in calling the wrong `delete` operator being called at_exit on the `Wrapper<...>`

I don't see this as very high priority as we have already said we're dropping support for this version

2. There is a _partial_ leak where `EventPipeThread` objects remain alive after their physical thread dies until _all_ EventPipe sessions are closed

The scope of this leak isn't huge (~256 B per object * number of threads created while sessions are active), but the integral for a very long-lived application that gets traced for the life of the process can get large.

3. The main thread's `Wrapper<...>` --> `EventPipeThread` will stay alive until the death of the physical thread since the `Wrapper<...>` is a hard reference.

This is the true at_exit issue that Jan pointed out above.  I think a fix here, might be to modify the wrapper to be a weak reference semantic, so that the `EventPipeThread` can get deleted when everything else is finished with it.

**Comment by tommcdon** [comment]
@josalem close?

**Comment by josalem** [comment]
I'm inclined to punt this to 6.0.  I'm not sure it's worth the risk to mess with this infrastructure this close to 5.0.

**Comment by noahfalk** [comment]
If we think issues are puntable then maybe it should be closed as "Won't Fix"? Did any customer care that we left this unfixed for a year? Would we still support RHEL6 in .NET 6?

**Comment by jashook** [comment]
I suggest closing this bug. This is not a supported platform for this release. When the bug was opened things were not as concrete.

@janvorli do you object?
