### ISSUE TITLE
BinaryFormatter: OutOfMemoryException while deserializing large objects with circular reference

### ISSUE THREAD

**Issue by buddhashrestha** [dotnet/runtime#1686]
While deserializing an object(>40Mb in my case), the amount of memory used by BinaryFormatter is very high and hence causing OutOfMemory Exception.  I am using the WPF framework with .NET Framework 4.7.2 and the object I am trying to deserialize has circular references.

I also opened an issue here which has the implementation: https://github.com/dotnet/corefx/issues/42813

Here is a snapshot of the memory usage. The application crashes if you perform deserialization of two objects in the same session.

![image](https://user-images.githubusercontent.com/10449218/72288399-d2ed8180-35fd-11ea-9988-4edd66f1fb2e.png)

**Comment by danmosemsft** [comment]
@buddhashrestha thanks for this issue. I transferred your other one here https://github.com/dotnet/runtime/issues/1689 .. given that, I think you can close this as a duplicate? 

BTW, I notice you are using .NET Framework. These repos are for .NET Core. Since BinaryFormatter has not changed much between the two (we discourage its use) any issue likely exists in .NET Core too, but just letting you know.

Is it feasible for you to use a different serialization mechanism and avoid this problem entirely?
