### ISSUE TITLE
Use generic collections in System.ComponentModel.TypeConverter implementation instead of non-generic

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/runtime#17217]

**Comment by marcusturewicz** [comment]
Is this for the entire System.ComponentModel.TypeConverter assembly or just the TypeConverter class from that assembly?

**Comment by eerhardt** [comment]
Note: not all usages of non-generic collections were replaced, by design. See https://github.com/dotnet/runtime/pull/63315#discussion_r777746398 for the reasoning. We replaced the ones that were obvious. But any more conversions here would need to be backed by data showing why the change must happen.
