### ISSUE TITLE
Consider adding algorithm-agnostic X509Certificate2.GetPublicKey() and X509Certificate2.GetPrivateKey()

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/runtime#17269]
A while ago, it was decided to remove these properties from the public contract to encourage people to use the strongly typed extensions: https://github.com/dotnet/corefx/issues/2449#issuecomment-129042445.

Though the motivation seems legitimate, this approach leads to very weird code in practice, specially in framework classes that don't need to deal with the concrete algorithm instance, as it ties them to algorithm-specific extensions:
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs#L78
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs#L102

Is there a chance to bring these properties back?

/cc @bartonjs @brentschmaltz

**Comment by bartonjs** [comment]
While I appreciate the complexities that not having something like `GetAnyPublicKey()` leaves on libraries that want to unify between a provided key and a certificate... the current design of ECDSA vs ECDH precludes creating one (we have to instantiate the key as one of the two classes, but don't know which kind you're expecting).

Even if we did add it, we're back at the classic problem that `PrivateKey` had: It would return AsymmetricAlgorithm, and people love casting too far (RSACryptoServiceProvider vs RSA... granted... our API from .NET Framework 2.0 made it impossible to do otherwise).

Lacking any clear path forward, and the issue having not had activity for about 6 years, I think it's time to just close it.
