### ISSUE TITLE
System.IO.Stream.Close() behavior issues

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#17418]
So normally you would think `Dispose()` does the same job including writing out the file to disk.

It turns out there is one extra case. Space for the file is not guaranteed to have been allocated until calling `close()` or `CloseHandle()` and may not in fact exist. This means that writing a file swallows knowledge of certain errors that should be thrown.

`Close()` must throw to catch write errors
`Dispose()` must _not_ throw to avoid problems with `using() {}` blocks. In effect `Dispose()` is `{ try { Cose(); } catch (IOException){}}` (omitting certain details of the dispose pattern for clarity)

The code to replace a file safely was:

```c#
   using (f = new System.IO.FileStream("name~", ...) {
       /\* write contents */
       f.Close();
   }
   System.IO.Move("name~", "name");
```

But now that doesn't work because `Close()` can't be there to error out. Adding it to just `FileStream()` doesn't help all that much. I have many occasions to do `new MyStream1(new MyStream2(new GzipOutputStream(new FileStream(...))));`

**Comment by joshudson** [comment]
Since nobody seems to be able to decide if  CA1065 should stand or fall, I came up with an option 3.

    enum FileOptions {
       //...
       DontThrowInDispose = 65536,
    }

This allows calling code to be upgraded in stages, or perhaps not at all.

I've been waiting for somebody to actually be able to decide which path to take before I write one giant patch for handling of `close(2)` failing.

**Comment by carlossanlop** [comment]
The main problem mentioned in this issue was fixed by https://github.com/dotnet/runtime/pull/38742

There are many other problems mentioned in this issue but to avoid confusion, I'll close this. If there's interest in discussing the other problems mentioned here, please open individual issues for each.
