### ISSUE TITLE
Proposal: Enums should implement generic IEquatable/IComparable interfaces

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#17456]
Every enum should implement its own version of `IEquatable<T>` and `IComparable<T>`, to avoid boxing when being compared/tested for equality (as they are really just ints underneath). The API would be similar to how each delegate class has its own version of `Invoke`/each `T[]` implements `IList<T>`, although there is no strongly-typed base class that actually declares this.

(Note: I'm aware that `EqualityComparer<T>.Default` already specializes for enums, however I still think this would be an API addition worth pursuing. Additionally, `Comparer<T>.Default` [does not](https://dotnetfiddle.net/vlr0UV) specialize for enums and falls back to boxing.)

Enums already implement the non-generic `IComparable` interface (there is no non-generic `IEquatable`), so I think this would be a welcome change right?

**Comment by CZEMacLeod** [comment]
I like this idea - has there been any traction on it? I have generic methods which use `<T> where T : IEquatable<T>` and would very much like to be able to pass enum values to this. At the moment I have to have a different method just for Enums - `<TEnum> where TEnum : enum` (and also vb.net doesn't allow enum as a generic restriction which causes other issues)

**Comment by Shpendicus** [comment]
> I like this idea - has there been any traction on it? I have generic methods which use `<T> where T : IEquatable<T>` and would very much like to be able to pass enum values to this. At the moment I have to have a different method just for Enums - `<TEnum> where TEnum : enum` (and also vb.net doesn't allow enum as a generic restriction which causes other issues)

yea this is super bad .. sadly still in .net 7

**Comment by dakersnar** [comment]
This issue does not contain enough info to be actionable and it is not something we will be driving a design process around at this time. If you are interested in driving it forward yourself, please feel free to open a new issue that follows the API suggestion template. Our API review process and a link to the template/good example is here:  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps.

**Comment by tannergooding** [comment]
@CZEMacLeod, @IngmarBitter just to address your confusion....

In order to simplify our own work and ease the API review process, we require API proposals to generally follow a given template (and provide such a template when you select "new issues": https://github.com/dotnet/runtime/issues/new/choose).

Due to the sheer volume and breadth of issues the repo sees opened, this really means the proposer needs to spend the small amount of time/effort to fill out an issue that follows the API proposal template as the area owners do not have the time/resources to turn every "rough idea" and turn it into something that is "actionable" from the perspective of API review.

-------------------------------------------

In this particular case there is also additional work needed on top of that to flesh out the design due to various complications that exist.

For example, we cannot go and change `System.Enum` itself to be generic or implement the generic `IEquatable<T>`/`IComparable<T>` methods. At best these would need to be implemented on the actual `enum` types defined/emitted in IL.

What this really means is that either the higher level languages (such as C#/F#) need to update the IL they generate to actually emit these interfaces and a correct implementation -or- the runtime needs to special case and shim things, as it does for `Array`.

If we did the former, then all existing enum values wouldn't implement the interfaces until they were recompiled. This represents and inconsistency in the world and may make the end to end experience feel incomplete. The runtime spec would also need to be relaxed to allow instance methods to be defined on `enums`.

If we did the latter, then the higher level languages would need to be updated to understand that `enums` may now implicitly implement such interfaces even if the metadata doesn't expose that information. The runtime spec would also need to be updated to explain in what scenario(s) these interfaces will be provided by the runtime.

There are then several other factors and considerations that come into the design and implementation as this will always be a cross-cutting feature requiring work in multiple layers of the stack and make it extremely non-trivial as compared to the seemingly "simple" ask initially presented.
