### ISSUE TITLE
COMException raised.When wsl Ubuntu run linux PInvoke.

### ISSUE THREAD

**Issue by zealeyes** [dotnet/runtime#1765]
# Issue Title

COMException raised.When wsl Ubuntu run on linux64
[CtpQuote.zip](https://github.com/dotnet/core/files/4062687/CtpQuote.zip)
[CtpTrader.zip](https://github.com/dotnet/core/files/4062691/CtpTrader.zip)

 with PInvoke.

# General

When I was use http://www.sfit.com.cn/5_2_DocumentDown_2.htm  sdk to build option app.
I called ReqQryInstrument and Wait RspQryInstrument, a exception throw not under \:
System.Runtime.InteropServices.COMException (0x8007007A): The data area passed to a system call is too small.
 (0x8007007A)
   at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkListElement& pCleanupWorkList)

I check all struct size .they all Ok.I can't find exception how.

![微信图片编辑_20200115095630](https://user-images.githubusercontent.com/14071268/72398555-474f2e80-377e-11ea-8896-0a7addd414cb.jpg)

**Comment by jkotas** [comment]
@jkoritzinsky Same problem as #1355 ?

**Comment by jkoritzinsky** [comment]
This one looks more similar to https://github.com/dotnet/coreclr/issues/6569 where the fixed string size doesn't have enough space for all of the multi-byte characters.

**Comment by jkoritzinsky** [comment]
@zealeyes can you post the struct definition that you're working with?

**Comment by jkoritzinsky** [comment]
@zealeyes I'm going to close this for now since we don't have enough information.

Most likely the case is that the characters you're using are not single byte-length characters. As a result, you effectively have less space because your characters take up multiple bytes. If you can, expand your fixed string length to fit more characters and then you should be able to support your scenario.
