### ISSUE TITLE
Make KeyDerivationAlgorithm a primitive

### ISSUE THREAD

**Issue by prajaybasu** [dotnet/runtime#17655]
@bartonjs 
I think this would allow for more flexibility than simply parameterizing Rfc2898DeriveBytes, UWP already has concepts of KeyDerivationAlgorithm, HashAlgorithm, MacAlgorithm, AsymmetricAlgorithm and SymmetricAlgorithm defined.

**Comment by prajaybasu** [comment]
Any updates on this?
I noticed that PBKDF2 was also implemented in [ASP.NET Core](https://github.com/dotnet/aspnetcore/tree/master/src/DataProtection/Cryptography.KeyDerivation/src/PBKDF2).   
These should be a part of an extensions API or corefx, is there any reason to use the above API over the .NET Core API?

**Comment by GrabYourPitchforks** [comment]
The performance profile of the ASP.NET implementation is better than the performance profile of the BCL's built-in implementation (`Rfc2898DeriveBytes`). This is mainly because the BCL's implementation has back-compat constraints that inhibit our ability to make significant optimizations. For example, ASP.NET's API is one-shot, but BCL's API is stateful and can be called multiple times to keep producing output. (This calling pattern is non-standards-compliant.)

I've mentioned this in other crypto-related threads, but if we add improved APIs for this I'd prefer for us to have a clean break with the existing base classes and to stand up a brand new stack unencumbered by history.

**Comment by vcsjones** [comment]
Just to circle back around to this, .NET 6 [now has a PBKDF2 one-shot](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes.pbkdf2?view=net-6.0). ASP.NET DataProtection will now prefer to use what is in .NET 6 when available. https://github.com/dotnet/aspnetcore/issues/30941.

**Comment by bartonjs** [comment]
Since we already have the abstract `DeriveBytes` class that `PasswordDeriveBytes` (extended PBKDF1) and `Rfc2898DeriveBytes` (PBKDF2) extend, we have the scenario of "give me a pre-tuned KDF that I can get a key from", even though I don't think we've seen any real usage of that... which is why HKDF just got added as static methods, because it better matched what people seem to want.

Since it's almost 5 years later and it's still not clear what change is actually being requested, and we don't have current plans to add more KDFs, I'm going to close the issue.
