### ISSUE TITLE
Cross-Compilation not working

### ISSUE THREAD

**Issue by krishvoor** [dotnet/runtime#1862]
Post consolidation of .Net Repos, instructions listed here for cross-complining ARM arch on x86_64
https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/cross-building.md#cross-compilation-for-arm-arm64-or-x86-on-linux  
is not working. This needs an update

1) Is Cross-Compile still supported ?
2) Did anyone attempt cross-compile on dotnet/runtime ?

**Comment by wfurt** [comment]
what error do you get? Daily build do use cross-compilation for ARM platforms so it is unlikely to be broken. However instructions may be incomplete or inaccurate after repo merge.

**Comment by BruceForstall** [comment]
It's best to build using Docker with the instruction here: https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/linux-instructions.md

The documentation here, overall, could be improved.

**Comment by harsha544** [comment]
@BruceForstall we made considerable efforts to port coreclr to IBM's ppc64le arch, we started closely monitoring ARM Cross-compilation on x86_64, however with Microsoft's decision to consolidate  repo(s) and merge into dotnet/runtime, the instructions listed were still old/not-precise until few days back.

Instructions here https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/linux-instructions.md#Environment aren't still reflecting parameters from https://github.com/dotnet/runtime/blob/master/src/coreclr/build.sh 

Do you know if someone's making efforts to README.md files (I know for sure dotnet/runtime has many README.md files scattered around and which also adds up to confusion) else we can extend our support alongwith @sriramasharma insight(s)

@wfurt I do not have the ERROR handy, however are you referring to the crossgen pipeline jobs for ARM from here https://github.com/dotnet/runtime/tree/master/eng/pipelines which I see are failing on Azure pipeline otherwise advice where to take a peek at ?

**Comment by BruceForstall** [comment]
At this point, most of the main documentation files on "how to build" have been updated (as far as I know). I'm sure there is room for them to improve. The documentation probably will never be comprehensive in describing the "build.sh" command-line arguments.

As a concrete example, when I cross-build for Linux ARM32 in a Linux/x64 Docker container that contains the correct (current) rootfs, I do this (in bash):

```
SRC=/home/bruce/gh/runtime
ARCHITECTURE=arm
CONFIG_LOWER=checked
DOCKER_IMAGE=mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-14.04-23cacb0-20200121150126
DOCKER="docker run --env HOME=${HOME} --user $(id -u) -i --rm -v ${HOME}:${HOME} -w ${SRC} -e ROOTFS_DIR=/crossrootfs/${ARCHITECTURE} -e CAC_ROOTFS_DIR=/crossrootfs/x86 ${DOCKER_IMAGE}"
${DOCKER} ${SRC}/build.sh -c Release -arch ${ARCHITECTURE} /p:CrossBuild=True
${DOCKER} ${SRC}/src/coreclr/build.sh ${ARCHITECTURE} ${CONFIG_LOWER} cross -clang9 -skipnuget
${DOCKER} ${SRC}/src/coreclr/build-test.sh ${ARCHITECTURE} ${CONFIG_LOWER} priority1 cross -clang9 /p:LibrariesConfiguration=Release
```

**Comment by harsha544** [comment]
@BruceForstall - Thanks, I will give cross-compile ARM on x86_64 inside docker env a try.

I along with @SriramaSharma would like to propose adding a new architecture ( IBM's ppc64le ) for _dotnet/runtime_ repo and we are making progress towards the same. I will propose via a new github issue unless there is a standard template that needs to be submitted. 
FWIW, is there a weekly community call where roadmap is discussed and contributors can join ?

**Comment by wfurt** [comment]
cc @janvorli for the  ppc64le

**Comment by BruceForstall** [comment]
There is no community call meeting that I am aware of.

Note that PPC support has been requested and discussed in several issues (in the unmerged repos): https://github.com/dotnet/coreclr/issues/17294, https://github.com/dotnet/coreclr/issues/26252.

cc @richlander Platform porting work

**Comment by jashook** [comment]
Closing as we are regularly building arm and arm64 in CI.

**Comment by jashook** [comment]
Please open another issue and tag me if there is an updated issue.
