### ISSUE TITLE
Map Unix TimeZoneId to Windows TimeZoneId

### ISSUE THREAD

**Issue by jchannon** [dotnet/runtime#18644]
If I execute `TimeZoneInfo.GetSystemTimeZones()` on Linux & Windows I get different lists, this is because each OS uses a different timezone db.

However, is there a way in .netcore to get a consistent list no matter the OS and/or is there a way that `TimeZoneInfo.FindSystemTimeZoneById` on Windows will work with a Unix timezone id and vice versa a Windows id parsed on a Unix OS?

**Comment by qJake** [comment]
Would be great to have this. I am running into a scenario where I'm building a Docker container containing an ASP.NET Core 3.1 website, and I offer up a dropdown of timezones. In certain container environments, `TimeZoneInfo.GetSystemTimeZones()` does not return any results.

And, as mentioned before, if the `TZ` environment variable is set, it contains a Unix-style timezone (e.g. `America/Chicago`), not the .NET parseable equivalent (`Central Standard Time`).

![image](https://user-images.githubusercontent.com/652006/78519129-f69d0f80-7787-11ea-9ff4-c915072ec15f.png)

It would be great if we could address this and/or find a better cross-platform solution for .NET 5!

(P.S. Timezones are *really hard.* ☹️)

**Comment by Clockwork-Muse** [comment]
@qJake - 

[Unix-style timezone strings are indeed parseable - on Unix derivatives](https://dotnetfiddle.net/YH0pRV).

> In certain container environments, `TimeZoneInfo.GetSystemTimeZones()` does not return any results.

This is the actual problem - your string should be parseable, but because it can't find _any_ timezones, it looks like your _specific_ ones don't work.  For that matter, if `GetSystemTimeZones()` returns no results, I'd expect **Windows** timezones to fail as well.

Note that varying the list of timezones offered to your users based on the OS would likely be a mis-feature - and given the prevalence elsewhere, in a web context I'd default to the Unix/Olson tzdb identifiers (even if my OS was Windows).

**Comment by tarekgh** [comment]
The PR https://github.com/dotnet/runtime/pull/49412 now allowing to create a TZI objects using IANA or Windows Ids no matter you are running on Windows or Linux.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/pull/51093

**Comment by tarekgh** [comment]
We have merged the time zone names conversion https://github.com/dotnet/runtime/pull/51093. I am closing this issue but feel free to send any quesstion as needed.
