### ISSUE TITLE
Add IReadOnlyList<T> constructor to ReadOnlyCollection<T>

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/runtime#19089]
In some places in `System.Linq.Expressions` we implement `IList<T>` with all mutating methods throwing exceptions, just to be able to pass it to the constructor of `ReadOnlyCollection<T>`. An additional constructor overload with `IReadOnlyList<T>` would be useful to reduce code bloat.

###  API Proposal

```diff
 namespace System.Collections.ObjectModel
 {
     public partial class ReadOnlyCollection<T>
     {
+        public ReadOnlyCollection(IReadOnlyList<T> list);
     }
 }
````

The constructor would wrap the provided collection, just like the other constructor would. Please note that no copies are to be made, any modifications in the underlying `IReadOnlyList<T>` need to be observed.

**Comment by xtqqczze** [comment]
It does seem an oversight that a `ReadOnlyCollection<T>` cannot be instantiated from a `IReadOnlyList<T>`.

**Comment by terrajobst** [comment]
I've updated the API proposal.

**Comment by terrajobst** [comment]
@dotnet/area-system-collections any objections marking this as api-eady-for-review?

**Comment by eiriktsarpalis** [comment]
Sounds reasonable to me.

**Comment by terrajobst** [comment]
* This API has the issue that it would be ambiguous for common types, such as `List<T>`
* This would also force the implementation to grow by a field or having to type cast in every operation between `IList<T>` and `IReadOnlyList<T>`
* Instead of this, we probably should expose an API that allows adapting an `IList<T>` to an `IReadOnlyList<T>` by casting or wrapping (and vice versa)
     - @terrajobst will make separate API proposal for this.
