### ISSUE TITLE
Span and Memory Read/Write Stream extensions on .netstandard2.0

### ISSUE THREAD

**Issue by jesterret** [dotnet/runtime#1915]
Hi,
I've found myself copying Stream.Read(Async) overloads around lately and I've tried to look around for some reasoning why it's not available, but couldn't find anything even mentioning this topic, so would it be possible to get [this piece of code](https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamExtensions.netstandard.cs) from System.IO.Pipelines built into the System.Memory package, or some new optional netstandard2.0 compatibility package?
Thanks

**Comment by carlossanlop** [comment]
We cannot service `System.Memory` with new APIs since it is already inbox without that API.

Due to the way .NET Standard/API versioning works, we cannot add APIs to NuGet packages when we already shipped a platform with the previous API set, which is why they were added as extension methods in System.IO.Pipelines.

@jesterret Feel free to copy the code, it has a MIT license (with attribution, of course).

cc @ericstj @terrajobst @JeremyKuhne
