### ISSUE TITLE
Linq: Where(pred).First should not be faster than First(pred)

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#19382]
Related StackOverflow question: http://stackoverflow.com/q/8663897/4077294

Because `Where` is specialized internally for different types, e.g. arrays and lists, we can iterate through them directly in `MoveNext` and avoid some virtual dispatch. `First(pred)`, on the other hand, does not do any such specialization. This means that `array.Where.First` will be faster than `array.First` if the first element that matches the predicate is far up in the sequence.

We may want to share code between `Where.First` & `First`, i.e. by doing a bunch of typecasts in `First` and calling some function that statically receives the source as an array/list, & then also have the specialized iterators call through to those functions. Same applies for certain other functions that accept predicates, such as `Count`.

**Comment by eiriktsarpalis** [comment]
@jvandertil I know it's been a while, but would you still be willing to take this on? Thanks.

**Comment by jvandertil** [comment]
@eiriktsarpalis Yeah, sure. Which methods should be covered? There is an old PR on corefx: https://github.com/dotnet/corefx/pull/39200

Want me to port that one over?

**Comment by eiriktsarpalis** [comment]
Thanks @jvandertil, I wasn't aware of this PR. I see that it was closed due to concerns that we couldn't find real-world examples to justify the optimizations. I would argue we should still go ahead with the changes for a couple of reasons:

* The non-predicate overloads already apply the same optimizations.
* Using `array.First/Any/Single(predicate)` is fairly common in business logic. That business logic could be part of a hot path, especially when building batched queue processing microservices (think Kafka consumers or event sourcing systems).

cc @stephentoub

**Comment by stephentoub** [comment]
> The non-predicate overloads already apply the same optimizations

The non-predicate overloads are simpler: if they can determine a count for the source, they immediately know whether there's an element or not to use.  When there's a predicate, it requires iteration.

> That business logic could be part of a hot path

My thoughts as shared in that PR haven't changed.  We're already pushing the boundaries with LINQ, which was never intended to be a high-performance set of APIs, yet we've added special-casing upon special-casing, many of which add non-trivial expenses in various ways (to the point where we actually had to start building LINQ in a separate flavor without much of these special-cases because they were increasing AOT binary size way too much).  If you can find real-world places where such a change actually makes a measurable improvement for an app (not just in a microbenchmark), that would change my mind.  For example, some of the analyzers in dotnet/roslyn-analyzers make heavy use of LINQ.  Does this measurably improve the execution time of any of those analyzers when run on, say, dotnet/runtime?

**Comment by eiriktsarpalis** [comment]
Fair enough. In that case, I'm just going to close this.
