### ISSUE TITLE
Remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by olegoid** [dotnet/runtime#1938]
`ManagedWebSocket` claims that the remote party closed the connection without completing the handshake even though it didn't.

Here's the stack trace:
https://gist.github.com/olegoid/f426ea5f74eb9f5e145fd807e9bb5339

and web socket message exchange made with Charles proxy:
<img width="1136" alt="Screen Shot 2020-01-20 at 12 53 06 PM" src="https://user-images.githubusercontent.com/1524073/72748028-3b031100-3b84-11ea-8165-c4e2d3e8fdfb.png">

Investigation:

The decision to close the connection is being made here:
https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L669
because `TryParseMessageHeaderFromReceiveBuffer` returns `false`.

`TryParseMessageHeaderFromReceiveBuffer` in its turn returns `false` because `reserveSet` is set to `false` here:
https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L978

and then `shouldFail` is equated to `reserveSet` here:
https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1004

Concerns:

1) `reserveSet` evaluation doesn't seem to cover the entire set of reserved opcodes. It looks like we compare only against `0x70` while the protocol documentation says:
```
Opcodes 0x3-0x7 are reserved for further non-control frames yet to be defined.
```
Source: https://tools.ietf.org/html/rfc6455

2) Certain logic in `TryParseMessageHeaderFromReceiveBuffer` can be slightly improved to not close WebSocket connection when it's not expected. Specifically, instead of assigning `shouldFail` to `reserveSet` we can simply assign it to `false` and then if the opcode we're dealing with is unknown we will handle it here:
https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1049

**Comment by stephentoub** [comment]
I think there's a misunderstanding here.  I'm not seeing anything wrong with the implementation here, other than that maybe we could improve the error message, and add some tests to fill a test gap (your PR shouldn't have passed).

> reserveSet evaluation doesn't seem to cover the entire set of reserved opcodes

`reserveSet` isn't about opcodes.  Here is the frame format from the cited spec:
```
      0                   1                   2                   3
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
     +-+-+-+-+-------+-+-------------+-------------------------------+
     |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
     |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
     |N|V|V|V|       |S|             |   (if payload len==126/127)   |
     | |1|2|3|       |K|             |                               |
     +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
     |     Extended payload length continued, if payload len == 127  |
     + - - - - - - - - - - - - - - - +-------------------------------+
     |                               |Masking-key, if MASK set to 1  |
     +-------------------------------+-------------------------------+
     | Masking-key (continued)       |          Payload Data         |
     +-------------------------------- - - - - - - - - - - - - - - - +
     :                     Payload Data continued ...                :
     + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
     |                     Payload Data continued ...                |
     +---------------------------------------------------------------+
```

Note that the `opcode` is separate from the reserved bits.  They're both in the same byte, but the reserved bits are in bits 1-3, and the opcode is bits 4-7.  That's why in the cited line of code, we read the same byte twice but mask it differently:
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L978-L979
Notice that we're `&`ing with 0x70 for the reserve bits (that's `0b_0111_0000`) and 0xF for the opcode (that's `0b_0000_1111`).

> Opcodes 0x3-0x7 are reserved for further non-control frames yet to be defined.

Right.  That's why the `enum MessageOpcode` doesn't contain values 0x3-0x7:
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1472-L1480
and why the switch you highlight will flag an unknown opcode, including 0x3-0x7:
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1047-L1050

> Specifically, instead of assigning shouldFail to reserveSet we can simply assign it to false and then if the opcode we're dealing with is unknown we will handle it here:

No.  As noted above, the `header.Opcode` used in that switch statement:
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1018
doesn't include the reserved bits:
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L979
And thus it will flag an erroneous frame that contains those bits set.  That's what the `reserveSet` check is for:
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L978
https://github.com/dotnet/runtime/blob/539d9e6532dd39331a716ed2c1fa47e5d130954d/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1004

**Comment by olegoid** [comment]
@stephentoub I appreciate the explanation. Indeed, I misunderstood the part with different masks (0x70 & 0xF) and how they're applied to the same byte.

Here's also the spec info that explains why endpoint should fail the existing connection:
```
MUST be 0 unless an extension is negotiated that defines meanings
for non-zero values.  If a nonzero value is received and none of
the negotiated extensions defines the meaning of such a nonzero
value, the receiving endpoint MUST _Fail the WebSocket
Connection_.
```
