### ISSUE TITLE
Async parallel foreach

### ISSUE THREAD

**Issue by tomesendam** [dotnet/runtime#1946]
There are situations where a asynchronous parallel foreach is needed instead of the already existing ```Parallel.ForEach()``` and while it's not rocket science to implement yourself I think it would be a nice feature to be implemented in corefx. This should be seen as the asynchronous alternative to the existing ```Parallel.ForEach()```. And should take ```IEnumerable<T>```  as well as ```IAsyncEnumerable<T>```.

There are examples on this issue already here is one: https://devblogs.microsoft.com/pfxteam/implementing-a-simple-foreachasync-part-2/

```c#
        /// <summary>
        ///     Executes a foreach asynchronously.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="source">The source.</param>
        /// <param name="dop">The degrees of parallelism.</param>
        /// <param name="body">The body.</param>
        /// <returns></returns>
        public static Task ForEachAsync<T>(this IEnumerable<T> source, int dop, Func<T, Task> body)
        {
            return Task.WhenAll(
                from partition in System.Collections.Concurrent.Partitioner.Create(source).GetPartitions(dop)
                select Task.Run(async delegate
                {
                    using (partition)
                    {
                        while (partition.MoveNext())
                            await body(partition.Current);
                    }
                }));
        }
```
### Proposed API

```c#
namespace System.Threading.Tasks
{
    public static class Parallel
    {
        public static Task ForEachAsync<T>(IAsyncEnumerable<T> source, Func<T, ValuteTask> body);
        public static Task ForEachAsync<T>(IAsyncEnumerable<T> source, ParallelOptions parallelOptions, Func<T, CancellationToken, ValueTask> body);

        public static Task ForEachAsync<T>(IEnumerable<T> source, Func<T, ValuteTask> body);
        public static Task ForEachAsync<T>(IEnumerable<T> source, ParallelOptions parallelOptions, Func<T, CancellationToken, ValuteTask> body);
    }
}
```

### Closed questions
While I consider these questions to be closed feel free to continue discussion on them. 

- Should DOP be automatic or manual at all times? 
    DOP Will have a default, just like parallel linq. However documentation should make it clear that this default can be wrong in various cases. Such as detailed by @GSPP in various comments. 
- Should it accept IEnumerable<T>?
    Yes it should 
- Should the partitioner concept be supported at all?
    No we should ensure the specified DOP is adhered to exactly. Creating batches can lead to a smaller than expected effective DOP. 
- Should we process the source items sequentially or make no attempt? 
    By default we should try to process source items sequentially to improve data locality. Reason being: HDD read performance will increase drastically. Furthermore cache usage will be improved. It should however be made very clear to people in docs, that the order cannot be guaranteed
- Should there be an alternative to Parallel.For? 
    There should be one but I'll leave that outside of this issue.
- Should the funcs return ValueTask instead of Task? 
    Yes ValueTask is more accomodating than Task (cheaper to convert Task to ValueTask than the other way arround). Furthermore it should result in a peformance increase.
- Should TaskCreationOptions.DenyChildAttach be specified? 
    Yes this should be specified see [This comment](https://github.com/dotnet/runtime/issues/1946#issuecomment-576902625) for more info
- Should there be an overload without CancellationToken in the Func? 
    No there shouldn't be. It would have little to no benefit, but would cause a lot of implications (ambiguity, analysis becomes harder)

**Comment by MihaZupan** [comment]
@tomesendam transfered

**Comment by Clockwork-Muse** [comment]
>By default we should try to process source items sequentially to improve data locality. Reason being: HDD read performance will increase drastically. 

This assumes **all** of the following, at a minimum:
 1. The API is being primarily used to read from a local hard drive.
 2. The hard drive is a traditional disk drive, not an SSD.
 3. The hard drive has been defragmented; files are contiguous, and in directory traversal order.

... please correct me if I'm wrong, but I personally would expect this to be more likely to be used to make _web requests_...

> Furthermore cache usage will be improved.

If you're speaking about CPU cache usage, can we really rely on that?  It assumes that the allocated objects (especially the tasks) will be contiguous in memory.  That doesn't strike me as something we can actually control.
(Please correct me if I'm wrong about the assumptions here)

**Comment by tomesendam** [comment]
@Clockwork-Muse You are not wrong. But do you suggest the default behavior should be different? We could also make no attempt at it, but would that actually result in any performance increase?

**Comment by tarekgh** [comment]
@tomesendam please move the proposal you mentioned https://github.com/dotnet/runtime/issues/1946#issuecomment-576464191 to the top of the issue. I think the proposal is reasonable now. 

@stephentoub please let's know if you have any comment before we mark this issue ready for review.

**Comment by Clockwork-Muse** [comment]
@tomesendam I think I would personally explicitly state in documentation that the order of processing is not guaranteed.  The easiest way to iterate over the source items is going to be in source collection order, as in your example.  The problem is that once each or any task is created, all bets are off, and people may naively expect that:

```csharp
// Side note: we probably want an override without ParallelOptions
var result = someEnumerable.ForEachAsync(url => MakeDeleteRequestAsync(url));
```
... would be guaranteed to post the delete requests in sequence, which is absolutely untrue (even assuming that `MakeDeleteRequest` was somehow called in sequence, the server probably isn't going to **receive** them in sequence).

In the example you're showing, the partitioner is going to mess up your desire to read files sequentially.  Which probably means you would want something documented about `dop` not being terribly helpful if you have only a single physical disk, and are reading from it - but this depends heavily on things outside programmer control, and possibly knowledge.  It also means ignoring the possibility of things like the drive reordering operations, or having the ability to queue operations (if you were trying to delete files instead).

**Comment by tarekgh** [comment]
I agree with @Clockwork-Muse regarding be explicitly mentioning the order is not guaranteed in the docs.

**Comment by tomesendam** [comment]
@Clockwork-Muse @tarekgh  Yes I agree it should be made clear to people. I'll update the proposal to include it. 

Why do you think we want an override without ParallelOptions? As discussed earlier DOP should always be specified. Or are we too biased in our assumptions.

**Comment by Clockwork-Muse** [comment]
"simplified use case", mostly, along the lines of what PLINQ does.

**Comment by stephentoub** [comment]
In general the API seems fine.  Some questions/comments:
- I don't understand why the methods return a `Task<ParallelLoopResult>` rather than just `Task`.  The members on `ParallelLoopResult` are fairly tied to a `ParallelLoopState` that gets passed around, and these methods as currently defined don't have one.  For better or worse, the corresponding `ForEach` methods returned `ParallelLoopResult` for consistency with the overloads that did pass a `ParallelLoopState` to the delegates, but there aren't any such overloads here.
- Should there be?  Is there a similar need for it?  I've not seen a ton of usage of those overloads of ForEach, so maybe it's not something we should propagate forward?
- I suggest we reduce the number of overloads and just have a CancellationToken always passed into the delegate.  You then end up with one for IEnumerable and one for IAsyncEnumerable.
- I think the funcs should return ValueTask rather than Task.  The primary concern with ValueTask is that it'll be consumed incorrectly, but here the consumer is the method we're implementing, and we'll just make sure to do it right ;)  And returning ValueTask is more accomodating: Task can be converted to a ValueTask very cheaply, but it requires an allocation to convert a ValueTask (if it's not already wrapping a Task) into a Task.
- Re: "DOP should not be automatic in te case of async parallel foreach"... how do you plan to do that?  It defaults to -1 in ParallelOptions.  Are you suggesting -1 would mean ProcessorCount or similar when used with ForEachAsync even though it means "no upper bound" with ForEach?
- Re: "Should we process the source items sequentially or make no attempt?" I don't understand this.  Can you elaborate?
- Re: "Should TaskCreationOptions.DenyChildAttach be specified?"  parent/child relationships with tasks is something I wish we could go back and uninvent.  Very few people use it, and we pay for it regardless (in complexity if nothing else).  I also don't think it's particularly relevant here: async methods in general do not play with the parent/child relationship concept.  If we schedule tasks as part of the implementation, we should do so with DenyChildAttach, just as Run does.

**Comment by tomesendam** [comment]
@stephentoub 

- To answer your first question: You are right I suppose there is no reason to have it be `Task<ParallelLoopResult>`.  Cancelling from outside the loop should be good enough with just the cancellation token. I too have never used `ParallelLoopState`myself and cannot come up with a sensible usecase. 

- `ValuteTask<T>`: I never thought about this. But it could be better. but if I'm right this will increase the size of the callers allocation but spares us creating new allocations for each Task<T> (manually) synchronously returned? So if the user would pass a method containing some caching logic this could improve performance. But would it not decrease performance slightly in all other cases?

- DOP: A user should be forced to manually specify a DOP since there is no way of knowing what the right DOP is. But if we do try to set some DOP for the user it should be made very clear to the user that it might be a bad DOP. Trough warnings perhaps? Forcing users to set it manually would require either adapting `ParallelOptions` or creating a new way of setting it. `AsyncParallelOptions`?

- See [This comment](https://github.com/dotnet/runtime/issues/1946#issuecomment-484439367) on "Should we process the source items sequentially or make no attempt?" 

- TaskCreationOptions.DenyChildAttach Will be used then I'll update the issue

**Comment by tarekgh** [comment]
@tomesendam go ahead and update the final proposal so we can proceed with this issue.

**Comment by tomesendam** [comment]
@tarekgh it's updated to the current state

**Comment by tarekgh** [comment]
@tomesendam thanks for the update. 

I think @stephentoub suggested the following 

```
I suggest we reduce the number of overloads and just have a CancellationToken always passed into the delegate. You then end up with one for IEnumerable and one for IAsyncEnumerable.
```

But I am still seeing you are proposing the other overloads. if you agree with @stephentoub suggestion, please update the proposal one last time.

**Comment by tomesendam** [comment]
@tarekgh @stephentoub I do not agree on the CancellationToken. There might not always be a need for one thus simplifying use (a minor amount) is a good thing in my opinion. I'll remove it if this adds some major drawback I'm not seeing.

**Comment by tarekgh** [comment]
>  I do not agree on the CancellationToken. There might not always be a need for one thus simplifying use (a minor amount) is a good thing in my opinion. I'll remove it if this adds some major drawback I'm not seeing.

 @tomesendam you may list this as an open issue in the proposal that can be discussed during the design review. I marked the issue ready for review.

**Comment by tomesendam** [comment]
@tarekgh will do! Thanks

**Comment by stephentoub** [comment]
> There might not always be a need for one thus simplifying use (a minor amount) is a good thing in my opinion

First, we're talking about the difference between:
```C#
await Parallel.ForeachAsync(source, options, async (item, _) =>
{
    ...
});
```
vs
```C#
await Parallel.ForeachAsync(source, options, async (item) =>
{
    ...
});
```
That's a _very_ minor amount and is not worth exposing two additional overloads.

Second, without the cancellation token being exposed there, it'll be really easy for code to accidentally omit it.  Static analysis tools can look at the signature and say "I see a CancellationToken is being passed into your delegate, but your call to XyzAsync which has an overload that takes a CancellationToken isn't using it; strongly consider passing it through".  But with both of these overloads, it'd take much more complicated and fragile analysis to help the developer fall into the pit of success here.

Third, having multiple overloads actually causes ambiguity problems in some cases.  Let's say you just want to run the body 1000 times, but you don't actually need any input data, so you pass in something like `Enumerable.Range(0, 1000)` and then for your lambda you write `async delegate` to avoid specifying any arguments.  If there are multiple delegate types valid, this will produce a compilation error "The call is ambiguous between the following methods or properties".

Finally, new methods need to prove their worth.  We do not add new methods/overloads just because we can; we need to justify their value, and everything starts with negative value.

**Comment by tomesendam** [comment]
@stephentoub I'll remove the overloads. You're right, I overlooked these issues.

**Comment by stephentoub** [comment]
> DOP: A user should be forced to manually specify a DOP since there is no way of knowing what the right DOP is.

We don't do that for the sync overloads, we shouldn't for the async overloads.  Even for things that are I/O bound, we can still choose some reasonable default, either Environment.ProcessorCount or unbounded, and document that's the default; then if that maps to what the dev wants, great, they don't need to allocate and pass in a ParallelOptions just to use our defaults.  If that's inappropriate for the developer's needs, then they can choose to pass in a ParallelOptions and override our default choices.  This is one place where I do believe having additional overloads is warranted.  And then since you won't be providing a CancellationToken, the delegates there won't take one; any cancellation via a token would be achieved via closure, which is fine.  We keep the simple cases simple and the more complicated cases more complicated.

> But would it not decrease performance slightly in all other cases?

Potentially very slightly.  I suspect it'll be a drop in the bucket.  And the upside is potentially significant, especially depending on what we do with https://github.com/dotnet/coreclr/issues/27403.

> Should we process the source items sequentially or make no attempt?
By default we should try to process source items sequentially to improve data locality. Reason being: HDD read performance will increase drastically. Furthermore cache usage will be improved. It should however be made very clear to people in docs, that the order cannot be guaranteed

I'm still not understanding.  Both `IEnumerable<T>` and `IAsyncEnumerable<T>` are forward-only iterators, so via those interfaces the only way they can be consumed is sequentially (unless you're suggesting we try to type check for other interfaces?)  In other words, without doing anything special, we'll be processing sequentially.  What kind of consumption are you concerned we might encounter if we "make no attempt"?  Or are you thinking about trying to ensure that all of the actual code execution runs serialized even when we allow I/O to be overlapped?  That can be achieved by passing in a TaskScheduler like `new ConcurrentExclusiveSchedulerPair().ExclusiveScheduler`; we should not bake in such behavior to the ForEachAsync, as there'd be no good way for the consumer to override it, whereas they can with the inverse.

**Comment by tomesendam** [comment]
@stephentoub Having an overload without `ParallelOptions` and thus no CancellationToken sounds okay to me. But Can we give the devs a warning that the default DOP might be bad trough the compiler? Or by the optional rosyln analyzers? @GSPP 

> Potentially very slightly. I suspect it'll be a drop in the bucket. And the upside is potentially significant, especially depending on what we do with dotnet/coreclr#27403.

I have included ValueTask in the suggestion. 

> we should not bake in such behavior to the ForEachAsync, as there'd be no good way for the consumer to override it, whereas they can with the inverse.

So we should leave this to the devs calling the code?

**Comment by stephentoub** [comment]
> But Can we give the devs a warning that the default DOP might be bad trough the compiler?

The default is going to be unbounded if the developer just passes in `new ParallelOptions()`, so I'm not clear on what kind of warning you're hoping for when one isn't provided.

**Comment by tomesendam** [comment]
@stephentoub If we set it automatically based on cpu or something else. Then I would like there to be some kind of warning if that's possible to do. With this I mean either a compiler warning or from analyzers. I get that there currently isn't one but could or should there be one?

**Comment by stephentoub** [comment]
I'm still not understanding. Even for the overload that takes a ParallelOptions, the default is still unbounded, because `new ParallelOptions()` defaults to unbounded. Are you suggesting we always warn for every call to any of these overloads?

**Comment by tomesendam** [comment]
@stephentoub no I'm suggesting it for the overload without parallel options. And or a warning if the dop isn't manually changed in ParallelOptions (which probably isn't possible). That would by my ideal.

Or do you think any kind of warning is unnecessary? And that the documentation should suffice.

**Comment by stephentoub** [comment]
> I'm suggesting it for the overload without parallel options

Why do you see that overload as being different from the one that takes ParallelOptions?

When a developer sees they need to pass in a ParallelOptions, they'll likely do:
```C#
await Parallel.ForEachAsync(source, new ParallelOptions(), i => { ... });
```
at which point they're getting the unlimited behavior.

You're concerned about the behavior when a ParallelOptions isn't provided but not when they get this default unlimited behavior?

> Or do you think any kind of warning is unnecessary?

With the APIs shaped as they are, I don't think it makes sense to try to provide a warning.  Added an API that always triggers a warning suggests either the warning is bad or the API is bad.

**Comment by tomesendam** [comment]
@stephentoub 

> And or a warning if the dop isn't manually changed in ParallelOptions (which probably isn't possible)

What I mean is: if the dop in ParallelOptions = default then give a warning. And don't get me wrong I don't always want the warning to show. Only when there's no manually set DOP.

**Comment by stephentoub** [comment]
> Only when there's no manually set DOP.

How are you going to write an analyzer to detect that?

Is there going to be a warning for this?
```C#
public static async Task FooAsync(ParallelOptions options) =>
    Parallel.ForEachAsync(..., options, ...);
```
?

**Comment by tomesendam** [comment]
@stephentoub that's the question. I'm asking if that's possible at all.

**Comment by stephentoub** [comment]
> I'm asking if that's possible at all.

Warnings for that would easily be wrong. You don't know whether a custom dop was stored into the options or not.

**Comment by tomesendam** [comment]
@stephentoub well if it's not possible then it's not possible. Then we should just make this clear enough in the documentation.

**Comment by GSPP** [comment]
> Re: "DOP should not be automatic in te case of async parallel foreach"... how do you plan to do that? It defaults to -1 in ParallelOptions. Are you suggesting -1 would mean ProcessorCount or similar when used with ForEachAsync even though it means "no upper bound" with ForEach?

> Even for things that are I/O bound, we can still choose some reasonable default, either Environment.ProcessorCount or unbounded, and document that's the default;

Any IO workload has an optimal DOP. Deviating from that DOP can quickly become quite bad. `Environment.ProcessorCount` is mostly unrelated to the optimal DOP. The deviation will commonly be *very* bad.

For example, a 2 core microservice that tries to make 10000 HTTP requests to an external service will underutilize that service greatly. A process running on a 64 core box might DOS the receiving web service into downtime. And migrating the same application with the same configuration to a smaller larger server will now change performance and safety drastically. This could happen in the presence of cloud autoscaling.

Using `Environment.ProcessorCount` is quite unsafe.

Unbounded for IO is even more dangerous and most certainly inappropriate.

For the same reasons, doing IO on `Parallel` and PLINQ is very dangerous. Now with this new API, we know for sure that it is used for IO.

In my opinion, we should force the user to make a decision. For example, reject a `-1` in the `ParallelOptions` or not use `ParallelOptions` at all.

Do we even need `ParallelOptions`? We need a required DOP argument and an optional `CancellationToken` argument. Maybe just add those two arguments to the method.

**Comment by GSPP** [comment]
> I'm still not understanding. Both IEnumerable<T> and IAsyncEnumerable<T> are forward-only iterators, so via those interfaces the only way they can be consumed is sequentially (unless you're suggesting we try to type check for other interfaces?) In other words, without doing anything special, we'll be processing sequentially.

I believe PLINQ and/or `Parallel` attempt to cast the input argument to `IList<T>` or array. If that is used for range partitioning this would introduce drastic deviations from the "natural" order of items. I think that's quite undesirable. We also don't want batching and, since this is about IO, small CPU overheads are not much of a concern. So this kind of `IList<T>` optimization should not be performed. Using the `IEnumerable<T>` in the obvious way will do exactly the right thing.

**Comment by stephentoub** [comment]
> Now with this new API, we know for sure that it is used for IO.

It's the likely use case, but we don't know "for sure".  Any of us can come up with a call where no I/O is involved.

> Any IO workload has an optimal DOP.

In general, what's optimal is going to depend on many factors, some (most?) of which aren't known in most cases statically.  You argue that Environment.ProcessorCount and unbounded are going to be wrong.  I argue that it's going to be close to impossible for a developer to determine and pass in the "optimal" dop, except in very constrained cases where they're intimately aware of everything in the application, the hardware, the network, etc.  If we force a dop to be provided, I can almost guarantee you we're going to see the vast majority of call sites passing in either Environment.ProcessorCount (or a constant factor of it) or some arbitrary number based on little more than sticking one's index finger in the air to see which way the wind is blowing. 

> Using the IEnumerable<T> in the obvious way will do exactly the right thing.

Right.

**Comment by GSPP** [comment]
Examples for a hardcoded DOP from my practical experience:

1. When querying Amazon products from its API nightly for 1000 different search terms, I can decide a DOP value at development time and use that. If I go too high I will get banned from the API. The scenario is predictable.
2. When querying from my relational database, I understand what hardware it is running on. I will pick a fairly low DOP to not crowd out other users of the system.
3. When writing a web crawler, I will empirically determine at development time what DOP is best with respect to network usage. I can definitely set a good DOP for this by trying out different values.

None of these scenarios work with CPU count.

>  If we force a dop to be provided, I can almost guarantee you we're going to see the vast majority of call sites passing in either Environment.ProcessorCount

I do not believe so. I'd expect callers to *become aware* of the choice they *need* to make and just try a few different values.

**Comment by stephentoub** [comment]
You have given this a lot of thought.  I firmly believe that is not the typical case.  I expect the typical case is "I need to pass in some value here, what's a good default DOP, hmm, ProcessorCount seems like a reasonable stand-in, and I see lots of other code on the net using ProcessorCount as a default for dop, I'll use that.".  Further, in most scenarios, ProcessorCount is going to be (much) lower than the optimal value for I/O-based concurrency, not higher.

**Comment by GSPP** [comment]
I have done *a lot* of ETL-style data pipelines over time... That's where my interest in this comes from :smile:. It turns out that many production applications contain the basic pattern "take some data, transform it item by item, store it somewhere else".

**Comment by tomesendam** [comment]
@GSPP I think we should just provide a default but have documentation to warn devs about the pitfalls. Probably a good idea to put in XML comment/docs as well. When someone starts to dabble with parallel stuff they most likely will be bench-marking performance anyway and trying out various configs. 

Even if we force someone to manually supply a DOP they'll be guessing the first time anyway. Probably selecting like @stephentoub said some random number most likely to be cpu count.

**Comment by tarekgh** [comment]
@terrajobst why this is marked back api-needs-work? I think we can go ahead with the proposed APIs and later we can add the overloads which have the default DOP if needed. But I don't think we need to block on that.

**Comment by stephentoub** [comment]
Because the proposed design is still being debated.

**Comment by tomesendam** [comment]
@stephentoub I think we should proceed with the defaults and warn users in the docs/summary. When someone start's dabbling with this kind of stuff they most likely will be testing various configs anyway. And if they don't they wouldn't do it when they're forced to supply DOP anyway.

**Comment by jamsoftperu** [comment]
I use this....
/// <summary>
        /// 
        /// </summary>
        /// <param name="source"></param>
        /// <param name="degreeOfParallelism"></param>
        /// <param name="body"></param>
        /// <param name="token"></param>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public static async System.Threading.Tasks.Task ForEachAsync<T>(this IEnumerable<T> source, int degreeOfParallelism,
            Func<T, System.Threading.Tasks.Task> body, CancellationToken token = default)
        {
            var tasks = new List<System.Threading.Tasks.Task>();
            using var throttler = new SemaphoreSlim(degreeOfParallelism);
            foreach (var element in source)
            {
                await throttler.WaitAsync(token);
                tasks.Add(System.Threading.Tasks.Task.Run(async () =>
                {
                    try
                    {
                        await body(element);
                    }
                    finally
                    {
                        throttler.Release();
                    }
                }, token));
            }
            await System.Threading.Tasks.Task.WhenAll(tasks);
        }

**Comment by GSPP** [comment]
Can we revisit this for .NET 6?

I believe there is tremendous demand for such an API (as evidenced by the 63 positive votes at this time).

Even if no proposal in this thread seems quite right to the team, the demand for this capability seems to justify *some* progress in this direction.

The core of this proposal is to

1. Process a set of items
2. in parallel
3. using an async API.

The API could take various shapes but we are longing for *something*.

**Comment by YohanSciubukgian** [comment]
As many APIs are rate-limited (eg. 100 calls / min), Could we consider having a variant based on time which takes in parameter ?
 - int numberOfCalls
 - TimeSpan time

**Comment by tomesendam** [comment]
@YohanSciubukgian I don't think this API is the correct place for such a feature. That's better suited for the devs using this API to do on their own.

**Comment by Symbai** [comment]
> Can we revisit this for .NET 6?
> 

Could we get an update on this please?

**Comment by terrajobst** [comment]
@tarekgh @stephentoub how can we move this forward? Can someone summarize the contentious points and proposed options?

**Comment by tarekgh** [comment]
I think the only open issue here is DOP should be forced or can be defaulted. I think we should allow the default and we can clarify that in the docs with some different use case examples. but I'll let @tomesendam and @stephentoub continue their discussion to reach some conclusion here. I moved this to 6.0 release.

**Comment by tomesendam** [comment]
> I think the only open issue here is DOP should be forced or can be defaulted. I think we should allow the default and we can clarify that in the docs with some different use case examples. 
> 
> 

This sounds good to me. If @stephentoub has other ideas I'll gladly hear them out!

**Comment by stephentoub** [comment]
> I think we should allow the default and we can clarify that in the docs with some different use case examples. 

Yup.

So... what is the proposed set of APIs now?

**Comment by tarekgh** [comment]
> So... what is the proposed set of APIs now?

If I understand correctly, the proposed APIs on the top still hold. the detailed behavior may need to change in the description. @tomesendam please correct me if I spelled anything wrong here.

**Comment by tomesendam** [comment]
> > So... what is the proposed set of APIs now?
> 
> If I understand correctly, the proposed APIs on the top still hold. the detailed behavior may need to change in the description. @tomesendam please correct me if I spelled anything wrong here. 

Correct, I'll change the description to fit the default DOP.

**Comment by tarekgh** [comment]
one last question I have, as we are going to have a default anyway, does it make sense to make ParallelOptions parameter be nullable to avoid allocations if the caller is happy with whatever default we'll have?

**Comment by tomesendam** [comment]
> one last question I have, as we are going to have a default anyway, does it make sense to make ParallelOptions parameter be nullable to avoid allocations if the caller is happy with whatever default we'll have?

Yes, I don't see a problem with that. I'll update it for now. Can always revert if others in this issue, have problems with that.

**Comment by stephentoub** [comment]
> as we are going to have a default anyway, does it make sense to make ParallelOptions parameter be nullable to avoid allocations if the caller is happy with whatever default we'll have?

Personally, rather than making it nullable, I'd prefer an additional overload that just didn't take one.  Since the options is also how a CancellationToken is specified, that delegate also wouldn't take a CancellationToken, e.g.
```C#
public static Task ForEachAsync<T>(IEnumerable<T> source, Func<T, ValuteTask> asyncBody)
```
Then a user isn't forced into unnecessary ceremony to provide things for the default common case.

There are other aspects of Parallel.ForEach that aren't represented in this proposal, e.g. support for ParallelLoopState, support for  Partitioner, task state, etc.  Is the plan to just leave those out for now and add overloads for them only if needed later?

**Comment by tarekgh** [comment]
> Personally, rather than making it nullable, I'd prefer an additional overload that just didn't take one.

I think this is a good idea. @tomesendam could you please update the proposal by adding the overloads?

> here are other aspects of Parallel.ForEach that aren't represented in this proposal,

I think we can wait to see if there is a demand on that and then add the overloads.

**Comment by tomesendam** [comment]
@stephentoub I agree with @tarekgh, I would wat and see if there's demand for those overloads. And I've changed the description to reflect your comment.

**Comment by tarekgh** [comment]
And now the issue is marked ready for design review :-)

**Comment by GSPP** [comment]
> support for ParallelLoopState, support for Partitioner, task state

I'll post my opinions on these: This API is meant to be used with async IO. Any async IO carries a lot more overhead than typical parallel algorithms or allocations bring. I do not think that CPU efficiency should be a significant concern here.

1. ParallelLoopState: I see a little of a use case for these features except for breaking the loop entirely. This is supported through the normal cancellation mechanisms.
2. Partitioner: I have described above that single-item partitioning seems to be the only reasonable choice. This is needed to achieve reliable and predictable scheduling of IO.
3. Task state: I'm not sure what is meant by this. If it is the common pattern of threading through an `object state` then I think this is not needed because of the efficiency argument.

**Comment by terrajobst** [comment]
* The bodies should take a cancellation token so that the method can construct a cancellation token to stop work when one work item failed.
* Let's make it easier to pass in a cancellation token without parallel options. Since we don't want it last for consistency, let's overload with and without cancellation token.

```C#
namespace System.Threading.Tasks
{
    public static class Parallel
    {
        public static Task ForEachAsync<T>(IAsyncEnumerable<T> source, Func<T, CancellationToken, ValueTask> body);
        public static Task ForEachAsync<T>(IAsyncEnumerable<T> source, CancellationToken cancellationToken, Func<T, CancellationToken, ValueTask> body);
        public static Task ForEachAsync<T>(IAsyncEnumerable<T> source, ParallelOptions parallelOptions, Func<T, CancellationToken, ValueTask> body);

        public static Task ForEachAsync<T>(IEnumerable<T> source, Func<T, CancellationToken, ValueTask> body);
        public static Task ForEachAsync<T>(IEnumerable<T> source, CancellationToken cancellationToken, Func<T, CancellationToken, ValueTask> body);
        public static Task ForEachAsync<T>(IEnumerable<T> source, ParallelOptions parallelOptions, Func<T, CancellationToken, ValueTask> body);
    }
}
```

**Comment by tomesendam** [comment]
@stephentoub great work! Excited to see what will be done with this.

**Comment by GSPP** [comment]
A small step for a developer, a big step for mankind. Awesome!
