### ISSUE TITLE
Consider adding more LINQ operators from Ix.NET

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/runtime#19522]
https://github.com/dotnet/corefx/issues/13842 introduces `TakeLast` and `SkipLast` which existed in [Ix.NET](https://github.com/Reactive-Extensions/Rx.NET/tree/master/Ix.NET/Source/System.Interactive) (`System.Interactive`, which is part of the Reactive Extensions project) for a long time. This may be a good time to review other operators we got in Ix.NET and see whether they're worth adding to .NET proper.

I'm pasting a short selection (using the Ix names) below:

### Min and Max with IComparer<T>

No overloads of these operators exist with an `IComparer<TSource>`. The existing overload uses `Comparer<TSource>.Default` to get the comparer. It seems an omission that we don't provide an option to pass in a custom comparer.

```csharp
public static TSource Min<TSource>(this IEnumerable<TSource> source, IComparer<TSource> comparer);
public static TSource Max<TSource>(this IEnumerable<TSource> source, IComparer<TSource> comparer);
```

### MinBy and MaxBy to select element(s) with lowest/highest key value

Similar to `MinimalBy` and `MaximalBy` in Mathematica. The current overloads with a `Func<TSource, TResult>` are merely shortcuts for `xs.Select(f).Max()` rather than providing a means to get the list of values that have the lowest projected value (e.g. the list of people with the lowest value for `Age`).

```csharp
public static IList<TSource> MinBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector);
public static IList<TSource> MinBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IComparer<TKey> comparer);
public static IList<TSource> MaxBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector);
public static IList<TSource> MaxBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IComparer<TKey> comparer);
```

### Concat (or Flatten or Unwrap)

Just like `Task<Task<T>>` can be unwrapped into `Task<T>` or `AggregateException` can be flattened. Obviously, this is just a macro for `xss.SelectMany(xs => xs)`, but possibly more descriptive and having better performance.

```csharp
public static IEnumerable<TSource> Concat<TSource>(this IEnumerable<IEnumerable<TSource>> sources);
public static IEnumerable<TSource> Concat<TSource>(params IEnumerable<TSource>[] sources);
```

### StartWith (Prepend with multiple values)

I noticed we've added `Prepend`. Ix provides `StartWith` which is basically the same but takes a `params` array with elements to prepend. (Note it comes from the dual of `StartWith` on `IObservable<T>` where we can start an event sequence with one or more initial values provided from an array.) It could be done quite easily today using `new[] { ... }.Concat(xs)` but may be deemed a natural extension to `Prepend`.

```csharp
public static IEnumerable<TSource> StartWith<TSource>(this IEnumerable<TSource> source, params TSource[] values);
```

### Scan (aggregate yielding intermediate results)

Totally analogous signatures to `Aggregate` but yields every intermediate computed result. As usual, it comes from the duality with Rx where we deal with streams of events (that may never terminate). This said, it has value on a lazy enumerable sequence, e.g. when processing large logs and providing all intermediate aggregation values as the analysis is going on. `Aggregate` is pretty much `Scan` followed by `Last`, only optimized.

```csharp
public static IEnumerable<TAccumulate> Scan<TSource, TAccumulate>(this IEnumerable<TSource> source, TAccumulate seed, Func<TAccumulate, TSource, TAccumulate> accumulator);
public static IEnumerable<TSource> Scan<TSource>(this IEnumerable<TSource> source, Func<TSource, TSource, TSource> accumulator);
```

There are a bunch more that are likely a bit more esoteric and of lesser value, but nonetheless worth having a look at. One family of them deals with sharing side-effects of enumeration in a less aggressive way than the traditional `ToArray` to `ToList` approach; see things like `Share`, `Memoize`, and `Publish`.

It's been a while since I've worked on / looked at this code, so some design decisions may have eroded from my memory, but I'll do my best recollecting these if questions come up.

**Comment by eiriktsarpalis** [comment]
As already mentioned adding more methods to System.Linq comes at a cost, so we would need to see strong evidence for the utility of any new method on a case by case basis. As it stands this issue is more of a wish list of assorted LINQ methods, making it more difficult to evaluate during API review. I would recommend closing it and creating separate issues for each proposal, so that we can have a more focused debate.

A few thoughts on the individual proposals:

* I think `MaxBy` and `MinBy` are genuinely useful additions, that cannot be easily expressed with the existing API, though I would probably lose the overloads that accept `IComparer`. They pile one abstraction over another and I really don't believe they provide more value over just using a `keySelector`. These additions are already covered by #27687.
* `Concat` seems like a useful addition. Would you be able to create a dedicated issue for it?
* I would not support adding `StartWith` since it's really just a slightly different `Prepend`.
* `Scan` seems pretty niche. While I can see why it might make sense in Rx-like flows, I don't think it would see much use in the context of LINQ. IMHO `Aggregate` is pretty niche as well and should best be avoided.
