### ISSUE TITLE
Clarification on backwards compatibility of .NET Core

### ISSUE THREAD

**Issue by bencyoung** [dotnet/runtime#1959]
I raised https://github.com/dotnet/aspnetcore/issues/18386 because a change from .NET Core 2.1 to .NET Core 3.1 broke an application that used nothing but .NET Core code (this is because you can't chose your ASP.NET Core version, it's fixed by the runtime)

From there it says ASP.NET Core is part of .NET Core, so should it give the same backwards compatible guarantees? E.g. all recent care about Regex protected members restricting the allowed optimisations?

If it is now part of .NET Core that's introducing a lot of surface area to keep compatible, or there's been a change in the level of compatibility required? Will there be those guarantees in future versions?

**Comment by stephentoub** [comment]
cc: @richlander

**Comment by jkotas** [comment]
We do not guarantee 100% compatibility between major version. This is true for ASP.NET Core and the runtime itself. We intentionally make breaking changes where we believe that they are necessary to move the platform forward and the cost of the .NET ecosystem adjusting to them is low enough.

The compatibility bar for ASP.NET is lower than the compatibility bar for the runtime itself, so the chances that you may need to do small adjustments to your ASP.NET between major versions are higher.

 cc @Pilchie

**Comment by bencyoung** [comment]
Thanks for the response @jkotas. I completely understand the reasons behind allowing backwards compatibility breaks but I'll try and explain why this feels a little different to me. 

1. (and key one) The breaking change overrode explicitly referenced NuGet packages. I explicitly referenced ASP.NET Core 2.1 packages and nothing else. There's no warning or build error, just an error when I try to run it.
2. It seems unnecessary for this to happen. I was happy referencing ASP.NET Core 2.1 packages. The reasons to package it into the runtime this deeply seem problematic to me. I see no reason why ASP.NET Core 2.1 shouldn't work on later .NET Core versions (just like any other NuGet package)
3. It seems a massive (and potentially dynamic) API load to shift into .NET Core. .NET Framework was eventually weighed down by the scope of its APIs and I worry that subsuming ASP.NET Core into .NET Core at this relatively early stage is doing the same.

On a selfish note this makes life quite difficult for me :). I maintain a large BCL for a company. This BCL has been around for about 10 years and contains much of the things that ASP.NET Core has introduced, so we've needed to write huge amounts of adaptors (DI-to-DI, Logging-to-Logging, Config-to-Config etc). Every time breaking changes are introduced I need to add more and more adaptors as my internal consumers target everything from .NET Framework 4 (for Silverlight support) to .NET Core 3.1. So far I've never bumped my major version number but we already have AspNetCore and AspNetCore3 support libraries....

**Comment by jkotas** [comment]
I agree with you that the ASP.NET 2.1 -> 3.0 migration experience is not great. I have seen and helped with number of issues that people have hit during the migration (e.g. https://github.com/dotnet/coreclr/issues/26878#issuecomment-535116994). 

> I see no reason why ASP.NET Core 2.1 shouldn't work on later .NET Core versions

We are supporting the matching version of ASP.NET Core and the runtime only. It is simple to explain and simple to test.

You are right that various combinations of older and newer versions can work in theory. It adds complexity. We choose to not spend our energy on dealing with this complexity.

> It seems a massive (and potentially dynamic) API load to shift into .NET Core.

.NET Core is composed from number of independent parts. We are very careful about not creating huge monolith like .NET Framework with all-or-nothing proposition. 

The change in ASP.NET distribution model did not make all ASP.NET APIs part of .NET Runtime. ASP.NET and .NET Runtime are still independent entities. 
Console apps still reference .NET Runtime APIs only by default. And you can [download](https://dotnet.microsoft.com/download/dotnet-core/3.1) just the .NET Runtime only without ASP.NET.

**Comment by bencyoung** [comment]
Thanks for the response. I'll leave it for now, but isn't the whole point of having things like netstandard is you don't have to test every combination? If ASP.NET Core was a third party library what would your advice to its developers be?

The message to external developers is very different to that which MS are following themselves, and I don't see anything in ASP.NET Core that's so special it needs runtime support (nice as it is). 

That's enough moaning though. I like .NET Core very much in general, which is why I get concerned for it's future direction. We're a 30% .NET and 70% Java company and I'd much rather it was the other way around...

**Comment by jkotas** [comment]
netstandard guarantees that the API is there, so that you do not have to cross-compile. It does not guarantee that the API works in the exact same way on all runtimes that support given version of netstandard. The combinations of runtimes and platforms to test your library on depends on the library level of exposure to these issues and the quality level you would like to maintain.

**Comment by bencyoung** [comment]
Agreed to an extent, although also not entirely true? There's no way on NuGet.org to specify what combination of runtimes you've tested your netstandard2 library on so it's not ideal for library developers, unless netstandard2 does mean a bit more than just the API existing... Otherwise what does it mean for a library produce to target netstandard2 and release it to the world? It might not work on .NET 5?

**Comment by davidfowl** [comment]
> (and key one) The breaking change overrode explicitly referenced NuGet packages. I explicitly referenced ASP.NET Core 2.1 packages and nothing else. There's no warning or build error, just an error when I try to run it.

There were a few key breaking changes made to ASP.NET Core in 3.0:
- Remove packages for a large part of ASP.NET Core (this wasn't binary breaking in itself because the dlls still have the same names and most APIs were intact)
- Remove Newtonsoft.Json as the default JSON serializer in favor of System.Text.Json. This removed the last 3rd party dependency from the ASP.NET Core shared framework.
- Changed pubternal things to be internal. To better maintain the framework going forward we removed a large set of APIs that were "public but could break every release".

There also other smaller breaking changes to low level interfaces that likely don't affect many if any applications.

> It seems unnecessary for this to happen. I was happy referencing ASP.NET Core 2.1 packages. The reasons to package it into the runtime this deeply seem problematic to me. 

That decision was made very early in the 3.x cycle. I appreciate that people don't have time to try things during development but there were long long discussions on github about the direction and why we were going this there and also ~8 previews before we shipped.

> I see no reason why ASP.NET Core 2.1 shouldn't work on later .NET Core versions (just like any other NuGet package)

Like I said, you can make it work its just untested and unsupported as there are lots of components that were updated around those packages that might make assumptions. In all honestly, we just haven't tried it because its not a thing we'd encourage or test.

> If ASP.NET Core was a third party library what would your advice to its developers be?

If we wanted to make things nice for everyone we would rename all of the assemblies when we made a breaking change. That's the nice way to do it with a package as well. Everything is side by side and you can't use both of them in the same project because it'll lead to conflicts.

What we do today is reuse the dlls names and make breaking changes so you end up getting method missing (or whatever kinda break ends up happening).

PS: I don't forsee us making as big of breaking changes as we did previously. 1.1 -> 2.1 was horribad because we broke the authentication model. 2.1 -> 3.1 can be tough because of some of those changes I mentioned above. 

Moving forward we're being much more diligent about planning for breaking changes via obsoletion (which we started in 2.2) then removing things in a later release. Rather than breaking hard without that step.

**Comment by GeorgeS2019** [comment]
I could not find discussions leading to this NET5 milestone. I included here because it is relevant to companies which are 70% Java and 30% NET
[Java interoperability will be available on all platforms.](https://devblogs.microsoft.com/dotnet/introducing-net-5/)

**Comment by jkotas** [comment]
> There's no way on NuGet.org to specify what combination of runtimes you've tested your netstandard2 library on so it's not ideal for library developers

Yes, we are aware of this problem and looking into solutions for it. We have hit it in our own libraries too. For example, https://github.com/dotnet/corefx/issues/42179 is about using netstandard2 System.Text.Json library on a runtime that it was not tested on.

> It might not work on .NET 5?

Yes, there is small chance that it might break on .NET 5. We are talking about rare cases, 99+% of the libraries are fine. For example, we have seen breakages like this when libraries take a bad dependency on the internal runtime implementation details via private reflection.

**Comment by jkotas** [comment]
>  Java interoperability

@GeorgeS2019 This issue is not about Java interoperability. If you would like to discuss Java interoperability, please open a separate issue on it.

**Comment by GeorgeS2019** [comment]
@jkotas From @bencyoung
> I like .NET Core very much in general, which is why I get concerned for it's future direction. We're a 30% .NET and 70% Java company and I'd much rather it was the other way around...

.NET5 aims to converge .NETCore, .NET Framework, Xamarin (Mono)
I believe there are many .NETCore supporters as discussed here who wish the other way around BUT hopping to know what option is offered by .NET5 is such scenario

As far as I understand, there is no mixing of .NETcore (Cloud/Web) and Mobile solution (Xamarin(Mono) in terms of java support for interoperability).

However, if such java interoperability is also available to NETCore (Cloud/Web), then NET5 will be truly game changing

I have search everywhere ,no such topic has been discussed since May 2019 when .NET was announced.

There is need to do so Officially without waiting for users to suggest that.  :-)

**Comment by jkotas** [comment]
@GeorgeS2019 I will to be happy to give you an update on where we are with Java interoperability if you open a new new issue on it. It is a different topic that what this issue about.
