### ISSUE TITLE
Unexpected output from Enum.TryParse

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#1964]
Given the following code:

```csharp
using System;
					
public class Program
{
	public static void Main()
	{
		var result = Enum.TryParse("5", out Month month);
		Console.WriteLine(result);
		Console.WriteLine(month);
	}
}

public enum Month
{
   Jan = 1,
   Feb = 2,
   Mar = 3
}
```

Expected output is "False", Actual output is "True".

**Comment by stephentoub** [comment]
This is by design. From the docs:
https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=netframework-4.8
"If value is the string representation of an integer that does not represent an underlying value of the TEnum enumeration, the method returns an enumeration member whose underlying value is value converted to an integral type."

**Comment by Youssef1313** [comment]
Thanks. Closing...
