### ISSUE TITLE
RPM references krb5-libs which does not exist in openSUSE

### ISSUE THREAD

**Issue by Mailaender** [dotnet/runtime#2000]
This is a bit weird: https://pkgs.org/download/krb5-libs exists everywhere in the rpm world but @openSUSE which causes problems as discussed in dotnet/core-setup#5628 and https://github.com/dotnet/runtime/issues/929. The solution is probably to

```spec
Requires: krb5
```

instead.

See also this fake package https://build.opensuse.org/package/show/home:michals:compat/krb5-libs

**Comment by leecow** [comment]
Noticed the incorrect deps files in the OpenSUSE feed yesterday. Will be getting those cleaned out.

**Comment by dagood** [comment]
The repodata.xml does currently have both:

https://packages.microsoft.com/opensuse/15/prod/repodata/44841d38d34e81e7b1cc010faa3fd88dfd762e12c26e97931639a5e17886f7f0-primary.xml.gz

```
<location href="dotnet-runtime-deps-3.1.1-opensuse.42-x64.rpm"/>
...
<location href="dotnet-runtime-deps-3.1.1-oraclelinux.7-x64.rpm"/>
```

I'm not familiar enough with how repositories work in depth to know why your client would pick up the `oraclelinux.7` one and mine picks up `opensuse.42`. In any case, fixing the conflict and making sure the release tooling is fixed so this doesn't happen again seems like the right move here.

**Comment by Mailaender** [comment]
On services like https://build.opensuse.org/ you always have separate repositories for distributions.

You can still have one spec file with syntax like this:
```spec
%if 0%{?suse_version}
Requires:       krb5
%else
Requires:       krb5-libs
%endif
```

What you are doing seems pretty non-standard.

**Comment by dagood** [comment]
> What you are doing seems pretty non-standard.

Very. We don't have spec files, and we don't build the Microsoft distribution on a single machine. It's also very expensive for our release process and the team that maintains the Msft Linux repositories to provide packages for a new distro. We make do by reusing the same packages across as many distros and versions as possible. Debian packages have "or" dependencies that we leverage for this. RPM packages have "or" dependencies too, but only as a brand new feature that doesn't have widespread support.

In this particular instance the problem was just a problem with the package push, I don't think we have identified a dependency *yet* that has actually changed between openSUSE versions. `libicu` probably soon.

**Comment by NikolaMilosavljevic** [comment]
Please ensure it works.

**Comment by NikolaMilosavljevic** [comment]
@v-chayan - can you check that latest .NET 3.1 runtime servicing build can be installed correctly on OpenSUSE 15?

**Comment by Mailaender** [comment]
I had a package update recently and it didn't ask to resolve broken dependencies, so I presume you fixed it successfully. Thanks!
