### ISSUE TITLE
Proposal: System.Text.Json extension methods

### ISSUE THREAD

**Issue by ConnerPhillis** [dotnet/runtime#2019]
Hi All,

Whenever I'm using a Json library I usually find myself writing the following two extension methods

```C#

public static T ParseJson<T>(this string jsonString)
	=> JsonSerializer.Deserialize<T>(jsonString);

public static string ToJsonString(this object target)
	=> JsonSerializer.Serialize(target);

```
(I'm not married to the naming, and I'm welcome to receive feedback on that code)

To me, this feels more natural and easier to read, when you compare how this looks in the code it produces shorter lines and more fluent-looking code.

```C#
var numbers = "{\"numbers\": [1, 2, 3, 4]}";
var numberList = default(NumberList);

numberList = JsonSerializer.Deserialize<NumberList>(numbers);
numberList = numbers.ParseJson<NumberList>();

numbers = JsonSerializer.Serialize(numberList);
numbers = numberList.ToJsonString();
```

Apologies if this has been proposed before, exists somewhere that I haven't thought to look, or is outside of the scope of the project; I just feel it would be useful to read code this way over the direct function invocation.

If this is something that people would want to be in the framework I'd love to implement it.

Thanks in advance!

**Comment by Gnbrkm41** [comment]
I personally am okay with people having those convenience methods in their codebase, perhaps for readability reasons, but I'm not sure how I feel adding it in the BCL as an extension method on string, given how general purpose the type is - i.e. string is not only for JSON. If we were to add this we might end up with a hundred other similar additions for other types, while not adding much significant value (it ends up being an another way of writing something that's already possible.) while requiring a lot of work to do so.

APIs can only be added, not removed; therefore it's crucial for these to be very carefully reviewed before it gets added to ensure they add significant values and would not end up being burdens.

**Comment by ahsonkhan** [comment]
Agreed with what @Gnbrkm41 stated.

Whether the API should be static methods or extension methods was discussed when the JsonSerializer class was being designed and we explicitly chose to keep them as static methods instead of extension methods on types like string/object that are used in a lot of different contexts.

See the following (which has the link to the API review video as well):
https://github.com/dotnet/apireviews/blob/4f2f720ff8e23bc6bacb2144a249fa2e8556066d/2019/System.Text.Json-Serialization/README.md
> Make them regular static methods (rather than extension methods).

https://github.com/dotnet/corefx/issues/34372
