### ISSUE TITLE
Add Enumerable.AggregateRight

### ISSUE THREAD

**Issue by leandromoh** [dotnet/runtime#20330]
# Background

LINQ offers a [Aggregate](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Aggregate.cs) (`foldl`) method, but it does not provide its rigth-associative version  (`foldr`).

![foldr](https://cloud.githubusercontent.com/assets/11452028/23327019/ed4cefbe-fae3-11e6-92ea-63efb9ac0f75.png)

# Proposal

I would like to submit a PR for this, but i dont know exactly which files I must change. There is something beyond to create AggregateRight and tests?

**Comment by eiriktsarpalis** [comment]
A few remarks:

* Since IEnumerable is a lazy type, a `foldr` implementation must necessarily be _O(n)_ space. This is evident if you take a look at the corresponding [F# implementation](https://github.com/dotnet/fsharp/blob/d7d91d9452800e9a9a69ed66513bf06732991144/src/fsharp/FSharp.Core/seq.fs#L837).
* Assuming you had a right-associative operation, you could work around the issue by chaining `Reverse()` with the existing `Aggregate()` method.
* Using fold(r) in imperative languages is considered an anti-pattern. The recommended way for aggregating enumerables is `foreach` blocks.

Given the above, I don't think we would accept such an addition. I'm going to close this issue. 

Thank you for your contribution!

**Comment by leandromoh** [comment]
> * Using fold(r) in imperative languages is considered an anti-pattern

 Can you provide any link? I never heard such of thing. I cant figure out that, why foldr would be bad, if map, filter and foldl is standard (LINQ inclusive).

Just for register, the [morelinq](https://www.nuget.org/packages/morelinq/) open source project adds this one and a lot more of missing functional methods in native LINQ

**Comment by eiriktsarpalis** [comment]
> > Using fold(r) in imperative languages is considered an anti-pattern
>
> Can you provide any link? I never heard such of thing.

@dsyme often talks about [fold being considered harmful](https://www.youtube.com/watch?v=1AZA1zoP-II&t=2243). 

In my view, using `foreach` with mutable state generally offers a faster and more maintainable way for reducing enumerables. Also, the inability to express abstractions such as the `Foldable` type class largely removes any benefits of thinking in terms of `fold`.

> I cant figure out that, why foldr would be bad, if map, filter and foldl is standard (LINQ inclusive).

Please refer to my previous post. It being _O(n)_ space is one reason why we wouldn't consider it.

> Just for register, the morelinq open source project adds this one and a lot more of missing functional methods in native LINQ

That's great, and we fully encourage third-party libraries providing alternatives that are better than LINQ. With the base class libraries we need to be conservative in what we ship because it impacts the footprint of the framework for everyone.

**Comment by leandromoh** [comment]
thanks for reply, i gonna watch the video!
