### ISSUE TITLE
CryptoStream is no longer usable for Hashing with CryptoStreamMode.Read

### ISSUE THREAD

**Issue by jcdickinson** [dotnet/runtime#2042]
The behavior of `CryptoStream.FlushFinalBlock` was changed in [CoreFX 36048](https://github.com/dotnet/corefx/pull/36048). In the PR, `TransformFinalBlock` is no longer called during `FlushFinalBlock` when `CryptoStreamMode.Read` is used. This effectively breaks the following means of verifying a hash using `CryptoStream`:

            using (var hashStream = new CryptoStream(source, hmac, CryptoStreamMode.Read, true))
            using (var dec = aes.CreateDecryptor())
            using (var aesStream = new CryptoStream(hashStream, dec, CryptoStreamMode.Read))
            {
                ...

                aesStream.FlushFinalBlock(); // hmac.TransformFinalBlock is not called with the final block, rendering the hash invalid.
            }
            var hash = hmac.Hash;

# Workaround

Implement a custom stream and avoid CryptoStream.

# Comments

This is an undocumented breaking change from netfx. The CryptoStream ctor should ideally throw a `NotSupportedException` if a hashing algorithm is passed in as the transformation (and mode = Write), if the current behavior is considered correct.

**Comment by stephentoub** [comment]
This was known to be a divergence from .NET Framework:
https://github.com/dotnet/corefx/issues/7779#issuecomment-459924179

@bartonjs, how would you like to handle this?

**Comment by bartonjs** [comment]
> how would you like to handle this?

By going back in time and standing firm that we weren't going to let `HashAlgorithm : ICryptoTransform` again.  But I currently lack that ability, and probably the resolve :smile:.

Since we already shipped the change, and it made sense at the time, it probably just needs a breaking change doc.  We didn't have the label when we made the change, and it got missed in the "oh, right, what were all the breaks we took" scrub.  I've now flagged the PR for posterity's sake.

Making the ctor throw for HashAlgorithm inputs in Read mode is not entirely unreasonable, but there's an easy workaround of just calling TransformFinalBlock on the HashAlgorithm instance before calling the Hash property, which is an easier workaround than "we threw an exception, you have to invert your data flow".  We could add this to either @terrajobst's API analyzer (which might only have PNSE data), or the going-forward platform provided analyzer set (or both), to report when it sees a HashAlgorithm used in conjunction with Read mode.

**Comment by jcdickinson** [comment]
> @bartonjs an easy workaround of just calling TransformFinalBlock on the HashAlgorithm instance before calling the Hash property, which is an easier workaround

I did try this, but there's still unfortunately buffered data in the CryptoStream that hasn't yet been seen by the HashAlgorithm, so the hash ends up being different.

**Comment by bartonjs** [comment]
I'm actually kind of confused.  CryptoStream.Read(Async) _will_ call TransformFinalBlock, when the inner stream's Read(Async) returns 0 (otherwise it wouldn't depad encrypted data).

I think the problem is just that you're calling FlushFinalBlock explicitly on the inner stream, so it doesn't make a final demand, which would propagate the signal.  Are you trying to partial-read `source` within the using statements?  If so, the more stable answer might be to make a wrapper stream object around `source` which just forwards the calls to Read until you signal to your stream that it's terminated.

**Comment by jcdickinson** [comment]
Yep, I am reading a partial stream. Thanks, I'll make a length-limited stream as a workaround.

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/docs/pull/20366
