### ISSUE TITLE
Early return possible in ImmutableInterlocked.AddOrUpdate

### ISSUE THREAD

**Issue by sharwell** [dotnet/runtime#20619]
If the `valueFactory` returns the same value as was present in the dictionary previously, the [`AddOrUpdate`](https://github.com/dotnet/corefx/blob/343561048c85321713c30b6e69ddd20cfac94dea/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L262) method can return that immediately. This optimization would be equivalent to the one currently performed by the [`Update`](https://github.com/dotnet/corefx/blob/343561048c85321713c30b6e69ddd20cfac94dea/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L42-L46) methods in the same class.

:memo: There are two `AddOrUpdate` methods which this change applies to.

**Comment by eiriktsarpalis** [comment]
I think it's a reasonable optimization, it should be added to these methods as well.

**Comment by lateapexearlyspeed** [comment]
Hi @sharwell @eiriktsarpalis I would like to pick this but want to confirm one difference compared with that [update](https://github.com/dotnet/corefx/blob/343561048c85321713c30b6e69ddd20cfac94dea/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L42-L46): The type of [TValue ](https://github.com/dotnet/corefx/blob/343561048c85321713c30b6e69ddd20cfac94dea/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L262)may be ether value type or ref type.
So maybe we need to check it ( by Type.IsValueType) and then use .Equals() for value type or use ReferenceEquals() for ref type ?  Is that still ok for current optimization purpose ?

(Maybe we cannot use .Equals for ref type because that will not write new instance with same "value" into Dictionary which will change method behavior)

**Comment by sharwell** [comment]
I believe you can use [`ImmutableDictionary<TKey, TValue>.ValueComparer`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2.valuecomparer) for the comparison.

**Comment by lateapexearlyspeed** [comment]
Hi @sharwell Thanks, but doesn't ImmutableDictionary<TKey, TValue>.ValueComparer also use "custom" comparision for both value type and ref type and current method can only just "get" to use it?
I think we should use custom cmp (type overrided Equals) for value type and default cmp (object.ReferenceEquals) for ref type here so that we will not change existing method behavior, as mentioned above.
Unless we agree to change behavior to keep old ref type instance (with same value) in dic rather than new instance when user are adding <existing key, same ref type value but diff instance>, if that, have no concern.

**Comment by sharwell** [comment]
I think it's safe to assume we can use reference equality for reference types. I'm not sure what the right answer is for value types. If we had a fast "same binary representation" method we could use that (essentially the same thing reference equality is doing).

**Comment by lateapexearlyspeed** [comment]
Yes, we need to consider both value type and ref type which was as my initial thought above. 
For value type, not sure but maybe it is not always good to cmp by binary and using a good user-design Equals should be fast, safe and proper meaning way here.
Anyway that is why I am not sure if type.IsValueType should be used here to distinguish TValue and maybe impact perf.

**Comment by sharwell** [comment]
> using a good user-design Equals should be fast, safe and proper meaning way here

If we can't use `ValueComparer`, then we also can't rely on the `TValue.Equals` method (for the same reason: it may or may not be an oracle for identical values).

> Anyway that is why I am not sure if type.IsValueType should be used here to distinguish TValue and maybe impact perf.

The JIT should eliminate this check so it would not have a runtime impact.

**Comment by lateapexearlyspeed** [comment]
Just found that ImmutableDictionary.SetItem() will keep old value instance if key existed and new value instance has same value but is different instance (as [this),](https://github.com/dotnet/runtime/issues/43809#issue-729085894 said), so I think can use custom cmp for TValue here without changing behavior mentioned. Will try to raise PR later.

**Comment by eiriktsarpalis** [comment]
FWIW I found at least two instances in the [ImmutableInterlocked class](https://github.com/dotnet/runtime/blob/867ba801d1a609f4cbb6e5847a3ec030adb2d8f4/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L454) where `Comparer<TValue>.Default` is hardcoded when determining value equality. This is almost certainly accidental. We should either follow that convention or update the existing places so that the encapsulated value comparer is being used. @sharwell thoughts?

**Comment by quixoticaxis** [comment]
Could someone explain the rational behind this optimization? Are `ImmutableDictionary` and `ImmutableSortedDictionary` tailored for any particular user scenario?
Are there any benchmarks that prove benefits of additional comparison? Because, from my understanding, comparison itself is not zero cost.
As I mentioned in the linked issue, I'm more concerened with the general usability of immutable collections, and the current behavior that prevents updating with equal values is currently undocumented (I've started working on doc update PR,) and can create issues for users who expect reference equality for their classes that happen to implement `IEquatable<T>`.

**Comment by eiriktsarpalis** [comment]
> Could someone explain the rational behind this optimization?

Since we're talking about immutable collections, any update operation comes at the cost of additional allocations, so it stand to reason to avoid those if we can. As mentioned in the OP there is precedent of this optimization being applied elsewhere in the same project.

**Comment by quixoticaxis** [comment]
@eiriktsarpalis maybe I was not clear enough. My question is not why this should be done consistently now, my question is why this kind of optimization was introduced in the first place? Because it looks that removing the allocation of a single AVL tree node in the corner-case when elements are updated with equal values is being paid by not-so-clear contract and, I suppose, at least three random memory accesses on every update.

**Comment by eiriktsarpalis** [comment]
That's a fair point. Happy to reconsider our approach here if you could provide relevant benchmarks.

**Comment by quixoticaxis** [comment]
Would it be ok if I extract `ImmutableDictionary` out into a separate project an run benchmarks before and after removing the the value comparer? For now I'm under the impression that it would be easier for me than building through runtime build procedure (I don't have no required dependencies installed and would like to keep it that way).

**Comment by eiriktsarpalis** [comment]
> P.s. If anyone knows how (if it's possible) to build System.Collections.Immutable without building the runtime, any advise would be appreciated.

That might take more work than just building the runtime. Our build prerequisites are [pretty straightforward](https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md). You can use the infrastructure in https://github.com/dotnet/performance to host benchmarks against custom builds of the runtime.
