### ISSUE TITLE
Add missing [Browsable(false)] attributes

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#20666]
The attribute is new in 2.0. We should port also its usages into .NET Core 2.0.
Example: dotnet/runtime#20654

cc @danmosemsft @weshaggard

**Comment by joperezr** [comment]
This issue seems to be old and we haven't had any complaints so far from GUI applications wanting us to add these to any additional types, and I'm checking our targetting pack and this attribute seems to be already set and applied to more than 350 types on the framework, so I'll consider this one done for now. Feel free to reopen if that is not the case.
