### ISSUE TITLE
Need APIs for unicode case mapping and case folding

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#20674]
@gafter commented on [Mon May 11 2015](https://github.com/dotnet/coreclr/issues/976)

The Unicode function for determining the category of Unicode characters (`System.Globalization.CharUnicodeInfo.GetUnicodeCategory(char)`) appears to reflect a fairly recent version of the Unicode standard. However, the functions for performing Unicode case mapping (culture-insensitive uppercase and lowercase) appear to reflect Unicode version 1.0. This mismatch was a severe impediment for implementing spec-compliant case folding in the VB compiler.

There is also no support whatsoever for performing case folding according to the Unicode specification (simplified or otherwise). APIs in the platform to do this would help with any language that, like VB, wants to depend on the Unicode specification for the meaning of case-insensitive identifiers.

---

@jkotas commented on [Mon May 11 2015](https://github.com/dotnet/coreclr/issues/976#issuecomment-101117346)

cc @ellismg 

---

@ellismg commented on [Mon May 11 2015](https://github.com/dotnet/coreclr/issues/976#issuecomment-101125393)

This is something I'd like to do.  I think the open issue is how we support this on Windows (since I think that we can get Case Folding functionality from ICU).

In general, we've tried to move away from the framework itself shipping globalization data and used the OS provided APIs instead.  Since Windows doesn't currently expose a way to do case folding, we'd have to figure out what to do.

---

@karelz commented on [Fri Mar 17 2017](https://github.com/dotnet/coreclr/issues/976#issuecomment-287305272)

@tarekgh do we need a new API for this? If yes, we should move it to CoreFX. If not, let's remove "api addition" label.

**Comment by GrabYourPitchforks** [comment]
@tarekgh As a straw man, here's what it might look like to spread these APIs out on the classes where they naturally belong:

```cs
namespace System
{
    public struct char
    {
        public static char ToCaseFold(char c);
    }

    public static class MemoryExtensions
    {
        public static int ToCaseFold(this ReadOnlySpan<char> source, Span<char> destination);
    }

    public class string
    {
        public string ToCaseFold();
    }
}

namespace System.Globalization
{
    public static class CharUnicodeInfo
    {
        public static int ToCaseFold(int codePoint);
    }

    public class TextInfo
    {
        public static char ToCaseFold(char c);
        public static string ToCaseFold(string value);
    }
}

namespace System.Text
{
    public struct Rune
    {
        public static Rune ToCaseFold(Rune value);
    }
}
```

If we were to follow these patterns, then we'd probably end up with this behavior:

 * If you call the `CharUnicodeInfo` APIs, we use our carried data (currently Unicode 12.1, but likely Unicode 13.0 by the time the implementation ships).
 * If you call _any other_ API, the following logic occurs:
   * If `GlobalizationMode.Invariant` is set, we fold only ASCII and leave everything else as-is, regardless of OS. Otherwise:
   * If we're on a version of Win10 where OS natively carries the ICU data, or if we're on a non-Windows OS, we p/invoke into ICU to perform case folding on our behalf.
   * If we're on a version of Windows where the OS doesn't natively carry the ICU data, we fall back to the `CharUnicodeInfo` tables.

This follows the general concept of `CharUnicodeInfo` being a fully self-contained data set, while `string`, `char`, and `Rune` all fall back to `TextInfo`, which interfaces with our unmanaged dependencies.

Personally I think it's a little confusing to have multiple APIs that all share the same name but do slightly different things, but it _does_ follow established convention.

Thoughts?

**Comment by tarekgh** [comment]
Thanks, @GrabYourPitchforks for your proposal. I talked with you offline, I just want to mention what is the idea I like to have. Moving the [CaseFolding Library](https://github.com/dotnet/corefxlab/tree/master/src/System.Text.CaseFolding) from corefxlab to runtime libraries repo but not including it as part of the shipping SDK and instead, we ship it as a separate independent NuGet package so anyone wants to get the case-folding feature will just need to depend on this package. The reason is we are going to carry the case folding Unicode tables which will increase the footprint size of the product if we ship it inside the SDK. So only apps/libraries need to use this feature will need to carry it.

Here are some comments if we go with this plan: 
- Properly we'll need to rename the package to something more generic so we can accommodate more features as needed. I would prefer something Microsoft.Extensions.Globalization.
- Your proposed APIs look good we'll have to convert the proposal to be extension methods instead.
- We shouldn't have any method on TextInfo for case-folding.
- We need to visit the current APIs in the package to look if we need to keep it or polish it.

Thanks for your thoughts on this issue.
