### ISSUE TITLE
AzDO jitstress jobs are running on too many platforms

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#2100]
The purpose of the JIT stress jobs is to run various JIT stress modes through various test beds (coreclr, libraries, etc.) to exercise more code paths in the JIT. It's useful to do this on different OS platforms (Linux, Windows). But running on multiple Linux platforms (including Mac) that are essentially identical to the JIT doesn't give us usefully increased coverage for the cost. I propose pruning some of the OS platforms to reduce cost, reduce potential flakiness, and simplify these pipelines.

Consider the following pipelines:
- "runtime-coreclr jitstress". We run both "Linux arm64" and "Linux_musl arm64". We can probably drop the "Linux_musl" case. We run both "Linux x64" and "Linux_musl x64". We can probably drop the "Linux_musl" case. We build and run "OSX x64". It's not clear this is valuable.
- "runtime-coreclr jitstress2-jitstressregs". same as above.
- "runtime-coreclr jitstressregs". same as above.

@dotnet/jit-contrib @dotnet/runtime-infrastructure Comments?

**Comment by janvorli** [comment]
I agree that from the JIT stress point of view, one Unix platform for x64 should be sufficient and using more of them don't add value.

**Comment by tannergooding** [comment]
Just as a note: For the hardware intrinsics stress jobs, several of the physical mac machines which are used for CI are a bit older and have AVX but not AVX2 support.

These have been useful in catching issues where the JIT had mistakenly emitted an unsupported instruction. It would be good to keep this in mind when doing the job cleanup to ensure things are distributed nicely.

**Comment by BruceForstall** [comment]
> Just as a note: For the hardware intrinsics stress jobs, several of the physical mac machines which are used for CI are a bit older and have AVX but not AVX2 support.

It seems like unless we have a defined queue of AVX-not-AVX2 machines in Helix, this characteristic wouldn't be consistent and could change without our knowing.

The various SIMD stress modes are meant to approximate this by preventing certain instructions from being used, right? So running on actual specific hardware is really just verification of that?

**Comment by tannergooding** [comment]
> The various SIMD stress modes are meant to approximate this by preventing certain instructions from being used, right? So running on actual specific hardware is really just verification of that?

Correct.

The problem with running on modern hardware is that, if an instruction or path isn't limited correctly, it will still get emited and will "just work" since the underlying hardware still supports it (even though the JIT is supposed to be configured to not emit it).

We had originally run into a few issues since `System.Numerics` was course grained and required AVX2 for the 256-bit code paths (and therefore keyed the VEX encoding support off AVX2), but `System.Runtime.Intrinsics.X86` was much more fine grained and supported just AVX as standalone.

The Linux jobs would consistently pass as they were running on Azure VMs which I believe were always at least Broadwell (and so always supported AVX2 as a baseline). But we had some "flaky" Mac jobs due to a few code paths not having been updated correctly.

> This characteristic wouldn't be consistent and could change without our knowing.

Yes, this is another concern. Maybe its something that would benefit from some more thought on how to handle as the "light up" codegen support in the JIT expands (I don't think this needs to be expansive either, just a outer loop job that runs every couple of weeks and before releases would likely be good enough for these types of issues).

**Comment by CarolEidt** [comment]
Thanks @tannergooding for pointing out this issue. I agree that an outerloop job would be useful and sufficiently effective to ensure that we don't regress, assuming that we can provision the right combination of hardware. That said, it's always been a bit scary just how complex the support-test matrix is.
