### ISSUE TITLE
Provide API XmlDsigC14NTransform.GetCanonicalBytes without need for hashalgorithm

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/runtime#21388]
The current API public override byte[] GetDigestedOutput(HashAlgorithm hash) requires the user to have a HashAlgorithm. This makes extensibility a bit harder since the HashAlgorithm would have to be derived for special handling.

In IdentityModel we choose to simply write the canonicalized bytes into a stream allowing processing later.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/WsFed/src/Microsoft.IdentityModel.Xml/ExclusiveCanonicalizationTransform.cs#L119

**Comment by bartonjs** [comment]
It's not a very discoverable thing, but this actually already exists.  The output of XmlDsigC14NTransform.GetOutput() or XmlDsigC14NTransform.GetOutput(typeof(Stream)) is a MemoryStream containing the canonical XML.

Since we're not investing in SignedXml other than security issues, and no one has rattled any cages over this issue, it seems like we can close this.
