### ISSUE TITLE
Better library build defaults

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#2147]
The build.sh should build only the minimal required set of configurations for .NET 5 app to work. If someone needs additional configurations for testing they should use configuration options.

Today default libraries build also builds netstandard2.0-{configuration} and netstandard2.1-{configuration} which I think should be under opt-in mode.

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ViktorHofer** [comment]
cc @Anipik

**Comment by ericstj** [comment]
This is controlled by AdditionalBuildTargetFrameworks.  We only build additional configurations for reference assemblies because we allow assemblies which are part of the product to target NETStandard if that's what makes the most sense for the library (for example, if it ships the same configuration in a nuget package).

> Today default libraries build also builds netstandard2.0-{configuration} and netstandard2.1-{configuration} which I think should be under opt-in mode.

We do not build any additional configurations of source projects, only the one *best* configuration for netcoreapp.  Can you point out a specific case where you think we're building too much?
