### ISSUE TITLE
Desktop: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute fails occasionally on NETFX

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/runtime#22007]
Failed test: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute (from System.Diagnostics.Process.Tests) 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/67/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
System.NullReferenceException : Object reference not set to an instance of an object.
~~~
STACK TRACE:
~~~
at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 1013
~~~

**Comment by adamsitnik** [comment]
It looks like `System.Diagnostics.Process.Tests` project is not targeting .NET Framework anymore:

https://github.com/dotnet/runtime/blob/78efb9250245617ff8532371ae4b8375a741f5ea/src/libraries/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj#L6

I know that we have a lot of MSBuild magic that could somewhere overwrite it, but even then it would fail to build this project because it's using .NET Core-specific APIs like `ProcessStartInfo.ArgumentList`:

https://github.com/dotnet/runtime/blob/78efb9250245617ff8532371ae4b8375a741f5ea/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs#L1118

https://webcache.googleusercontent.com/search?q=cache:7OxdtdwL7HgJ:https://apisof.net/catalog/System.Diagnostics.ProcessStartInfo.ArgumentList+&cd=1&hl=en&ct=clnk&gl=pl&client=firefox-b-d

Having said that, I am going to close this issue.
