### ISSUE TITLE
Why is KeyedCollection abstract?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/runtime#22139]
Why is [KeyedCollection](https://github.com/dotnet/corefx/blob/master/src/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs) abstract, how about having it non-abstract with its constructor accepting a `GetKeyFromItem` delegate? So to allow creating `KeyedCollection`s of any type on the flow without having to create classes for each.

**Comment by layomia** [comment]
The issue here is that we'd have to convert the `GetKeyFromItem` method from `abstract` to `virtual`. The compiler will not require derived classes to override this method, and there won't be anything to enforce that a delegate is provided by a constructor. This leads to derived instances easily being in an invalid configuration which is not an acceptable design. A workaround here if the proposal is desired is to write a class deriving from `KeyedCollection<,>` that accepts a delegate.

Given the design challenges, I'll close this issue.
