### ISSUE TITLE
Scan for libraries with no ref in the ref package and no incoming dependencies in the runtime package

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#22276]
@ericstj pointed out it would be useful to improve our build to detect such things, by comparing the runtime and designtime dependency graphs. They can exist as a legacy of an earlier runtime dependency

Example: System.Security.AccessControl is in this category for UAP. corefx\bin\packages\Debug\reports\runtime.win10-x64.Microsoft.Private.CoreFx.UAP-runtime.dgml shows no incoming nodes for it (including none from netstandard.dll), and it has no ref in the design time package. (I'll take it out)

**Comment by ViktorHofer** [comment]
I don't understand this issue. @ericstj or @danmosemsft can you please provide more details?

**Comment by ericstj** [comment]
This was trying to track the case that we include assemblies in our shared framework, don't expose them, and don't actually use them.

Psuedo code:
```
var referencedAssemblies = runtimePackAssemblies.SelectMany(a => a.GetReferencedAssemblies());
var unneededAssemblies = runtimePackAssemblies.Except(refPackAssemblies).Except(referencedAssemblies)
```

Though now we actually permit some of these, so that we have consistent runtime exposure.  For instance we include System.Security.Cryptography.OpenSSL on windows, and Microsoft.Win32.Registry on linux.  As such I'm not sure if this is so interesting anymore.

**Comment by ViktorHofer** [comment]
> and Microsoft.Win32.Registry on linux

Could we remove that assembly from the shared framework / runtime pack on linux actually or does it need to be there?

**Comment by ericstj** [comment]
We need our shared frameworks to have the exact same footprint across all run times. The way the SDK bundles shared framework applications depends on it.

**Comment by ViktorHofer** [comment]
Got it, thanks. Based on the discussion above I'm inclined to close this issue. Feel free to reopen if you disagree.
