### ISSUE TITLE
Standardize on DiagnosticSource/OpenTelemetry for database tracing

### ISSUE THREAD

**Issue by divega** [dotnet/runtime#22336]
Currently we have around [27 `EventSource` trace points](https://github.com/dotnet/corefx/search?p=1&q=DataCommonEventSource++&type=&utf8=%E2%9C%93) in `System.Data.Common`. 

On the other hand, SqlClient has been instrumented with `DiagnosticSource`. 

I talked to @vancem today and we came to the conclusion that there may be enough value in standardizing on `DiagnosticSource` before we release 2.0. This would make the story more consistent for consumers of ADO.NET events (we are planning to add more `DiagnosticSource` instrumentation and make it easier for ADO.NET providers to add it) and once we ship the `EventSource` instrumentation it is unlikely that we will be able to remove it. 

cc @saurabh500

**Comment by roji** [comment]
Small note after looking at this again: a quick grep in dotnet/runtime's System.Data.* reveals that all current EventSources seem to be emitted from DataSet/DataTable/DataRow and related types; in other words, they are not emitted from any actual provider-related code.

**Comment by roji** [comment]
Take the Activity API into account as well when looking into this (e.g. https://github.com/open-telemetry/opentelemetry-dotnet/issues/675).

**Comment by mairaw** [comment]
@roji should we mark this as Cut or remove this from the .NET 6 project? Trying to clean things up a bit.

**Comment by roji** [comment]
@mairaw thanks, yeah. I'm both removing this from the project and closing the issue as I no longer think it's very relevant. Since this issue was opened, OpenTelemetry has emerged as the tracing standard, and has an [experimental spec for database client semantic conventions](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/database/). ADO.NET providers should simply implement that.
