### ISSUE TITLE
Rename ThirdPartyNotices.txt to THIRD-PARTY-NOTICES.txt

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#2243]
When you install the .NET Core runtime there is a `ThirdPartyNotices.txt` that gets installed.  If you install other .NET Core components such as the ASP.NET Core runtime or the .NET Core WindowsDesktop SDK, they install TPNs named `THIRD-PARTY-NOTICES.txt`.  .NET Core should be consistent.  I propose the upper case variant as it aligns nicely with the convention used by the `LICENSE.txt` file.

**Comment by NikolaMilosavljevic** [comment]
ThirdPartyNotices.txt file is installed as a shared component, to the same location, by both .NET 5.0 and .NET Core 3.1. Renaming this file in 5.0 would still preserve the 3.1 file on disk. If a similar fix was applied in 3.1,  it would not guarantee that the old file is removed, due to ref-counting and order of installs and version of shared .NET runtime on user's machines.

**Comment by MichaelSimons** [comment]
This is rather unfortunate.  These types of fit and finish problems add up over time and can degrade the UX especially for noobs.  That being said is there a larger issue (the shared components ref-counting issue) here that needs attention?  Are there other cases where this has caused issues such as this?
