### ISSUE TITLE
What tier does ProfileOptimization use?

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#2273]
From https://github.com/dotnet/aspnetcore/issues/18605#issuecomment-579027883

Does it  eagerly jit at Tier0 or Tier1?

How does it interact with R2R?

/cc @AndyAyersMS @kouvel

**Comment by kouvel** [comment]
It looks like the profile only records methods that are actually jitted, so R2R'ed methods would not be impacted. Then multi-core JIT tries to eagerly JIT the recorded methods, in the same way as normally, so it would use the default initial tier (tier 0 unless it contains a loop or is attributed with `AggressiveOptimization`, etc.).

**Comment by kouvel** [comment]
After a tier 0 JIT, the methods would transition similarly to tier 1, including with the tiering delay. Multi-core JIT just generates code and records the entry point somewhere, when the method is called for the first time the entry point is fetched and set to be used. It's as though the method is being jitted, just the code may already be available due to eager jitting.
