### ISSUE TITLE
Add ImmutableArray Span-based APIs

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#22928]
EDIT see https://github.com/dotnet/runtime/issues/22928#issuecomment-855154372 for the full API proposal.

@stephentoub You did not open a tracking issue for this in https://github.com/dotnet/corefx/issues/21281, although from the notes at https://github.com/dotnet/apireviews/pull/40 it seems like this was approved (:tada:). So I took the liberty of moving the proposal here:

```cs
namespace System.Collections.Immutable
{
    public struct ImmutableArray<T>
    {
        public static implicit operator ReadOnlySpan<T>(ImmutableArray<T> array);
    }
}
```

Since the API seems to have been approved, this is intended to be a tracking issue for work towards implementing it.

**Comment by 333fred** [comment]
Just ran into another case where `Builder.AddRange(ROS<T>)` would be very nice. There has not been any movement on this for a couple years: @layomia what do we need to kick off design review? More concrete API proposals?

**Comment by 333fred** [comment]
@eiriktsarpalis, Layomi said you would be the better person to answer: what are the next steps here? Do we need a more concrete API proposal?

**Comment by eiriktsarpalis** [comment]
Hi @333fred, next steps would be coming up with a finalized design for API review. Would you be interested in driving this?

**Comment by Joe4evr** [comment]
At a glance of the thread and existing APIs, it looks like this is the proposed design:
```diff
public static partial class ImmutableArray
{
+   public static ImmutableArray<T> Create<T>(ReadOnlySpan<T> items);
}

public partial struct ImmutableArray<T>
{
    public sealed partial class Builder
    {
+       public void AddRange(ReadOnlySpan<T> items);

        // Unsure if this one is needed, but I'll list it just in case for proper parity
+       public void AddRange<TDerived>(ReadOnlySpan<TDerived> items) where TDerived : T;
    }
}
```

**Comment by 333fred** [comment]
@Joe4evr that's a start, but leaves out slicing (and possibly some other apis as well). It's on my plate to go through and do this, which I should get done in the next few days.

**Comment by 333fred** [comment]
@eiriktsarpalis quick question: for sliceability, is the runtime's preference to an an indexer that takes a `Range`, or to add a `Slice(int, int)` method and get sliceability via the implicit language support?

**Comment by NickStrupat** [comment]
Any thoughts on my `ImmutableSpan<T>` idea? Immutable collections could all return `ImmutableSpan<T>` instead of `ReadOnlySpan<T>`, signalling to the calling code that the span of `T`s will never change.

**Comment by alrz** [comment]
Are we going to return a span or another IA? I wonder why we didn't do that for arrays (GetSubArray), should this be consistent?

**Comment by 333fred** [comment]
> Any thoughts on my `ImmutableSpan<T>` idea? Immutable collections could all return `ImmutableSpan<T>` instead of `ReadOnlySpan<T>`, signalling to the calling code that the span of `T`s will never change.
> 
> My apologies if I'm distracting from the main topic.

ImmutableArray doesn't make a guarantee of deep immutability today either. I don't see how ImmutableSpan would be any different than ReadOnlySpan, other than the name.

**Comment by mikernet** [comment]
Should indexers that take ranges return the same type, i.e. `ImmutableArray`, to follow existing designs for arrays and strings and such? While I think that was a mistake (I would have much preferred if the default was performant and the more expensive operation required `.ToString()` or `.ToArray()` to be added), it's kind of a baked-in design decision at this point. If you want to slice IA then following existing designs you would do `immutableArray.AsSpan()[1...6]`.

**Comment by mikernet** [comment]
Also love the idea of immutable spans. Would be great to have an immutable analogue to ROSpan that indicates the underlying list of items shouldn't change.

**Comment by terrajobst** [comment]
I'm not convinced that `ImmutableSpan<T>` would add a lot of value: spans are ref-structs, which means you can't stash them away easily. Hence their life time is fundamentally more constrained than regular collections. `ImmutableMemory<T>` is a different story, but considering the vast majority of the usages are for buffers which aren't immutable but only segregated into readers and writers, I don't think that such an abstraction would buy us much their either.

However, I enriching `ImmutableArray<T>` with span-based APIs (as proposed in this issue) still makes sense.

**Comment by mikernet** [comment]
Right after I posted my comment I had the same thought about it being stack-only and thus perhaps overkill to have an immutable version but figured I would review my codebase more to see if I could see any actually potential benefits. It probably doesn't overcome the -100 test the more I think about it.

**Comment by stephentoub** [comment]
I agree with @terrajobst. Let's focus on adding the ReadOnlySpan-based members,  and in particular Slice(int, int).

**Comment by airbreather** [comment]
I agree that **this issue** should probably focus on improving the relationship between `ImmutableArray<T>` and `ReadOnlySpan<T>`, as it has already evolved quite a lot over the years (to the point where I don't think that the single API in the issue description is even necessarily a good idea anymore, now that we have [`AsSpan()`](https://apisof.net/catalog/7df550fd-90b2-a1b3-4b77-5f5f82f9fc30)).

Regarding `ImmutableSpan<T>`, I don't think that the notion is **completely** without merit, even given that it would be stack-only.  If I write a method that accepts a parameter of `ImmutableArray<T>` today, then I'm declaring that I need a contiguous block of `T` instances that **nobody** will ever modify, not even if they're running in a different thread.  I recognize that the runtime environment and type system cannot fully guarantee this, but I'm content with trusting callers to keep their hands off of the underlying array once it makes it to such a method.

This concept of "contiguous block of `T` instances that **nobody** will ever modify, not even if they're running in a different thread" only seems to be exposed via `ImmutableArray<T>`, which currently requires a new perfectly-sized `T[]` instance to sit behind it, even if the caller is perfectly suited to slice chunks out of a larger `ImmutableArray<T>` that came from somewhere else.

Again, though, there should probably be a separate issue for this kind of thing.  I just wanted to jot down that potential usage scenario before I go crawling back into my cave again.

**Comment by terrajobst** [comment]
The question isn't whether something has *some merit*, the question is whether there is *sufficient merit* to offset the cognitive load of yet another core data type. My assertion is that there isn't. The cases where this would be useful are too niche IMHO.

**Comment by mikernet** [comment]
I've come to the same conclusion after further analysis. It seemed like a good idea at first but the uses would be so niche that in those limited cases ensuring that you don't modify the underlying data is not challenging to do with current constructs and thus does not merit another set of parallel BCL types. If you ***really*** want this you can always add it yourself and then add an extension method to `ImmutableArray` that returns your `ImmutableSpan`.

**Comment by mikernet** [comment]
@airbreather 
> If I write a method that accepts a parameter of ImmutableArray<T> today, then I'm declaring that I need a contiguous block of T instances that nobody will ever modify, not even if they're running in a different thread

I think that most (/all?) methods that accept `Span` or `ReadOnlySpan` already expect that the data won't be mutated on a background thread before the method returns, so this may be a bit of a moot point. Requiring the user to pass in an `ImmutableSpan` in all these cases, which effectively can only be safely created from an `ImmutableArray` (or a `string` I suppose), would be problematic IMO.

**Comment by NickStrupat** [comment]
Sounds good, folks. So if/when this span API change gets implemented, I'll add extension methods to my implementation of `System.ImmutableMemory` for the appropriate structures in `System.Collections.Immutable`.

https://github.com/NickStrupat/System.ImmutableMemory if anyone's curious.

Unrelated: Hi @mikernet! I grew up in London, Ontario! Great to know there's cool people doing cool .NET things in London :)

**Comment by 333fred** [comment]
## Background and Motivation

C# 7 and 8 added a number of features, including Range/Index and ReadOnlySpan support. While ImmutableArray has `AsSpan`, it and the other types are missing some other types that would work well here, such as `AddRange` and `Slice`.

## Proposed API

```diff
namespace System.Collections.Immutable
{
    public static partial class ImmutableArray
    {
+       public static ImmutableArray<T> Create<T>(ReadOnlySpan<T> items);
+       public static ImmutableArray<T> ToImmutableArray<T>(this ReadOnlySpan<T> items);
    }

    public partial struct ImmutableArray<T>
    {
+       public ImmutableArray<T> AddRange(ReadOnlySpan<T> items);
+       public void CopyTo(Span<T> destination);
+       public void CopyTo(int sourceIndex, Span<T> destination, int length);
+       public ImmutableArray<T> RemoveRange(ReadOnlySpan<T> items, IEqualityComparer<T>? equalityComparer);
+       public ImmutableArray<T> Slice(int start, int length);
        public sealed partial class Builder
        {
+           public void AddRange(ReadOnlySpan<T> items);
+           public void AddRange<TDerived>(ReadOnlySpan<TDerived> items) where TDerived : T;
+           public void CopyTo<T>(ReadOnlySpan<T> destination, int index);
        }
    }

    public partial class ImmutableList<T>
    {
+       public ImmutableList<T> Slice(int start, int length);
    }

    public partial class ImmutableSortedDictionary<TKey, TValue>
    {
+       public ImmutableDictionary<TKey, TValue> Slice(int start, int length);
    }

    public partial class ImmutableSortedSet<T>
    {
+       public ImmutableSortedSet<T> Slice(int start, int length);
    }
}
```

## Alternative Designs

I left off the other `System.Collections.Immutable` types from the `Span`-based overloads, because most of those types are already not trying to optimize for 0-allocation scenarios. They don't have `AddRange` methods that take their same types, for example, nor do they have one that takes an `ImmutableArray`. I can certainly add these `Span`-based overloads if they're actually desired.

## Risks

More APIs to learn is always more cognitive load. Beyond that, I don't see any risks here.

@eiriktsarpalis, could you take a look at this proposal?

**Comment by Joe4evr** [comment]
🤔 Shouldn't `CopyTo` on the builder take in a writable Span?

**Comment by 333fred** [comment]
Yes it should, thanks. Copy/paste :)

**Comment by eiriktsarpalis** [comment]
A few remarks:

* I would agree that the `CopyTo` overload that takes a `startIndex` parameter is likely not needed. It can be achieved by chaining `AsSpan().Slice().Copy()`.
* Shouldn't we also have an `AddRange<TDerived>` method in `ImmutableArray<T>` and not just its builder type?
* What is the use case for adding `Slice` methods to `ImmutableSortedDictionary` and `ImmutableSortedSet`? Set is probably passable since it already implements `IList<T>` but the methods still feel strange to me.
* How useful is it to expose a `ROS.ToImmutableArray()` extension method in addition to `ImmutableArray.Create`?

**Comment by 333fred** [comment]
> A few remarks:
> 
>     * I would agree that the `CopyTo` overload that takes a `startIndex` parameter is likely not needed. It can be achieved by chaining `AsSpan().Slice().Copy()`.

Thanks, I'll remove.

>     * Shouldn't we also have an `AddRange<TDerived>` method in `ImmutableArray<T>` and not just its builder type?

It doesn't have any of these such methods today. We could certainly add them, but we would probably want to add the other overloads as well (for `ImmutableArray<TDerived>` and `IEnumerable<TDerived>`).

>     * What is the use case for adding `Slice` methods to `ImmutableSortedDictionary` and `ImmutableSortedSet`? Set is probably passable since it already implements `IList<T>` but the methods still feel strange to me.

They're collections that have an order, and you can get at individual subsections. If there's not really appetite for this I can remove it, but it does feel like something natural to me.

>     * How useful is it to expose a `ROS.ToImmutableArray()` extension method in addition to `ImmutableArray.Create`?

I pretty much went through all the APIs that took an `ImmutableArray<T>` and an `IEnumerable<T>` and added a `ROS<T>` or `Span<T>` overload, as appropriate. If we don't think that's important, we can adjust, but as we have extensions for those two I added it here as well.

**Comment by eiriktsarpalis** [comment]
> They're collections that have an order, and you can get at individual subsections. If there's not really appetite for this I can remove it, but it does feel like something natural to me.

I don't disagree that the operations are well-defined, I'm just skeptical about about their usefulness, particularly for the case of `ImmutableSortedDictionary`. Dictionaries are indexed by their key type and not integers, so assuming I had a need for "slicing" a sorted dictionary, wouldn't it make more sense for the method to accept key ranges?

Other than that, the API proposal LGTM.

**Comment by eiriktsarpalis** [comment]
> They're collections that have an order, and you can get at individual subsections. If there's not really appetite for this I can remove it, but it does feel like something natural to me.

I don't disagree that the operations are well-defined, I'm just skeptical about about their usefulness, particularly for the case of `ImmutableSortedDictionary`. Dictionaries are indexed by their key type and not integers, so assuming I had a need for "slicing" a sorted dictionary, wouldn't it make more sense for the method to accept key ranges?

Other than that, the API proposal LGTM.

**Comment by 333fred** [comment]
> wouldn't it make more sense for the method to accept key ranges?

@eiriktsarpalis the goal of the proposal is to get implicit slicing support, ie to be able to say `list[..^1]` or `sortedDictionary[2..]`. To do that, we need a `Slice` method that takes a start index and a length. We admittedly don't have similar support for this in `SortedDictionary<TKey, TValue>`, so I'd be fine with remove it from the proposal.

**Comment by eiriktsarpalis** [comment]
Let's keep it for now, and we can discuss during API review.

**Comment by terrajobst** [comment]
* Let's add `ImmutableArray<T>.AsSpan(int, int)` to match arrays
* We're not sure we can add `Create<T>(ReadOnlySpan<T> items)` and `ToImmutableArray<T>(this ReadOnlySpan<T> items)`
    - They might cause ambiguities with existing ones over `IEnumerable<T>`. We can, of, course address those by adding overloads for common concrete types that have implicit conversion to `ReadOnlySpan<T>` (e.g. `string` and array).
    - @333fred will investigate
* Let's not add methods to any other types because we haven't done this for the mutable collections either (mostly lack of feedback but also due to performance considerations)

```C#
namespace System.Collections.Immutable
{
    public static partial class ImmutableArray
    {
        // Open question:
        // public static ImmutableArray<T> Create<T>(ReadOnlySpan<T> items);
        // public static ImmutableArray<T> ToImmutableArray<T>(this ReadOnlySpan<T> items);
    }

    public partial struct ImmutableArray<T>
    {
        public ReadOnlySpan<T> AsSpan(int start, int length);
        public ImmutableArray<T> AddRange(ReadOnlySpan<T> items);
        public void CopyTo(Span<T> destination);
        public ImmutableArray<T> RemoveRange(ReadOnlySpan<T> items, IEqualityComparer<T>? equalityComparer);
        public ImmutableArray<T> Slice(int start, int length);
        public sealed partial class Builder
        {
            public void AddRange(ReadOnlySpan<T> items);
            public void AddRange<TDerived>(ReadOnlySpan<TDerived> items) where TDerived : T;
            public void CopyTo(Span<T> destination);
        }
    }
}
```

**Comment by agocke** [comment]
> We can, of, course address those by adding overloads for common concrete types that have implicit conversion to ReadOnlySpan<T> (e.g. string 

I don't see how you could do this for `string` since we don't have generic specialization. You shouldn't be able to do `ImmutableArray<int>.Create(string)`

**Comment by terrajobst** [comment]
What I meant is adding tie breakers for overload resolution, like this:

```C#
public static partial class ImmutableArray
{
    public static ImmutableArray<char> Create(string text);
    public static ImmutableArray<T> Create(T[] items);
    public static ImmutableArray<T> Create(ReadOnlySpan<T> items);
}
```

**Comment by Joe4evr** [comment]
> ```cs
> public static partial class ImmutableArray
> {
>     public static ImmutableArray<char> Create(string text);
> }
> ```

This would break people writing `ImmutableArray.Create("Hello")` expecting to get an `ImmutableArray<string>` of length 1 with `"Hello"` as its element. In that case I think changing the method name is a better option:
```cs
public static partial class ImmutableArray
{
    public static ImmutableArray<T> FromSpan<T>(ReadOnlySpan<T> items);
}
```

**Comment by terrajobst** [comment]
That's a fair point. Considering that span is somewhat advanced anyways, that workaround seems acceptable to me.

**Comment by 333fred** [comment]
Alright, I’ve investigated the ambiguities we face for the `ImmutableArray` API changes. The general problem occurs when we have an instance method on `ImmutableArray<T>` that accepts both an `IEnumerable<T>` and a `ReadOnlySpan<T>`, `char` is used for `T`, and a `string` is passed to the method, _or_ for any `T` when `T[]` is passed to a method that does not already have a `T[]` overload. The latter ambiguity is easily solvable, as we could just add a `T[]` overload for these methods that don’t already have one, providing a most-specific method. The `char` ambiguity, though, is more complex, as we don’t have generic specialization. I see a few options to resolving it:

* Rename the APIs in question. Instead of a new `AddRange` overload, we could do an `AddSpan` method (and similar for the other new APIs). Because there is no existing overload, there is no ambiguity problem, but people will have to know about the new version.
* Define `AddRange(ReadOnlySpan<T>)` as an extension method, rather than an instance method. This means that for the problematic cases, the existing method will always be chosen because it will successfully bind before extensions are even considered. However, it will mean that the default behavior of the method will be non-optimal for these cases (as the IEnumerable version will be chosen), and I can see users immediately writing an analyzer to ensure that they’re always calling the ROS extension method, either by casting or by calling the extension in normal form.

Separately, I was wrong about user-defined conversions in extensions: I thought we considered them, but I was wrong about that. So, there is no concern with ToImmutableArray.

There is also no concern with the `Create` method, because of two reasons:

* We already have an array overload of Create, `Create(params T[])`.
* We already have a single-element overload of Create, `Create(T)`.

Arrays will prefer the former always, and strings will prefer the latter unless we were to introduce a `Create(string)` (and we have no reason to do so). So only the instance methods on `ImmutableArray<T>` and `ImmutableArray<T>.Builder` present an issue for overload resolution.

Internal discussion has preferred option 1 so far, renaming the APIs in question. Our candidates at the moment are (and extrapolate out to the other methods in question):

* `AddRangeFromSpan` - This will keep the same prefix, so people who start typing `AddRange` will see the new overload. It is a bit more wordy, but that could be good for discoverability.
* `AddSpan` - Shorter and more direct, but potentially less discoverable.

**Comment by terrajobst** [comment]
Marked as blocking to make sure we review it next Tuesday, because we just spent a bunch of time paging in context.

**Comment by Joe4evr** [comment]
> * `AddRangeFromSpan` - This will keep the same prefix, so people who start typing `AddRange` will see the new overload. It is a bit more wordy, but that could be good for discoverability.
> * `AddSpan` - Shorter and more direct, but potentially less discoverable.

I would 100% prefer `AddSpan` because it simply looks slightly less clunky than the first option (especially for the long-term).

### **Tangent**
If discoverability in IntelliSense is a concern, I wonder if there's room for a tooling feature here. Consider this to be nothing more than 🍝, but if the IntelliSense/Quick Info window could display related methods, driven by a little bit of extra metadata, that could potentially help with finding new method(s).
Badly-made mock-ups:
![](https://i.imgur.com/Ih7ZpDS.png)
![](https://i.imgur.com/WJA22pc.png)
Possible representation in source/refs:
```cs
public partial struct ImmutableArray<T>
{
    public sealed partial class Builder
    {
        [RelatedMembers(nameof(AddSpan))]
        public void AddRange(IEnumerable<T> items);

        public void AddSpan(ReadOnlySpan<T> items);
    }
}
```

**Comment by terrajobst** [comment]
* We discussed several options, such as adding as a suffix like `AddRangeFromSpan` as well as extension methods that could help to have tie breakers, but it seems the break would be rare in practice:
    - It's only ambiguous for types that have an implicit conversion to `IEnumerable<T>` and `ReadOnlySpan<T>`. We only ship two types, arrays and strings. For arrays, we can add a tie breaker `AddRange(T[])` to avoid ambiguity issues. The string one in practice feels super rare that asking the consumer to add a cast or adding `.AsSpan()` seems acceptable and preferable over adding a new method group.
* We should align the API surface of the builder with immutable, as per #822.

```C#
namespace System.Collections.Immutable
{
    public static partial class ImmutableArray
    {
        public static ImmutableArray<T> Create<T>(ReadOnlySpan<T> items);
        public static ImmutableArray<T> Create<T>(Span<T> items);
        public static ImmutableArray<T> ToImmutableArray<T>(this ReadOnlySpan<T> items);
        public static ImmutableArray<T> ToImmutableArray<T>(this Span<T> items);
    }

    public partial struct ImmutableArray<T>
    {
        // Existing:
        // public ImmutableArray<T> AddRange(IEnumerable<T> items);
        // public ImmutableArray<T> AddRange(ImmutableArray<T> items);      
        public ImmutableArray<T> AddRange(ReadOnlySpan<T> items);
        public ImmutableArray<T> AddRange(params T[] items);

        public ReadOnlySpan<T> AsSpan(int start, int length);
        public ReadOnlySpan<T> AsSpan(Range range);
        public void CopyTo(Span<T> destination);

        // Existing:
        // public ImmutableArray<T> InsertRange(int index, IEnumerable<T> items);
        // public ImmutableArray<T> InsertRange(int index, ImmutableArray<T> items);
        public ImmutableArray<T> InsertRange(int index, T[] items);
        public ImmutableArray<T> InsertRange(int index, ReadOnlySpan<T> items);
        
        // Existing:
        // public ImmutableArray<T> RemoveRange(int index, int length);
        // public ImmutableArray<T> RemoveRange(IEnumerable<T> items);
        // public ImmutableArray<T> RemoveRange(ImmutableArray<T> items);
        // public ImmutableArray<T> RemoveRange(IEnumerable<T> items, IEqualityComparer<T>? equalityComparer);
        // public ImmutableArray<T> RemoveRange(ImmutableArray<T> items, IEqualityComparer<T>? equalityComparer);
        public ImmutableArray<T> RemoveRange(ReadOnlySpan<T> items, IEqualityComparer<T>? equalityComparer = null);
        public ImmutableArray<T> RemoveRange(T[] items, IEqualityComparer<T>? equalityComparer = null);

        public ImmutableArray<T> Slice(int start, int length);
        public sealed partial class Builder
        {
            // Existing:
            // public void AddRange(T[] items);
            // public void AddRange(T[] items, int length);
            // public void AddRange(IEnumerable<T> items);
            // public void AddRange(ImmutableArray<T> items);
            // public void AddRange(ImmutableArray<T> items, int length);
            public void AddRange(ReadOnlySpan<T> items);

            // Existing:
            // public void AddRange<TDerived>(Builder! items) where TDerived: T;
            // public void AddRange<TDerived>(ImmutableArray<TDerived> items) where TDerived: T;
            // public void AddRange<TDerived>(TDerived[] items) where TDerived: T;
            public void AddRange<TDerived>(ReadOnlySpan<TDerived> items) where TDerived : T;

            // TODO: As per https://github.com/dotnet/runtime/issues/822, we should add the corresponding
            //       methods on the builder as well.

            public void CopyTo<T>(Span<T> destination);
        }
    }
}
```

**Comment by 333fred** [comment]
@terrajobst did you mean to have a `Create(Span<T>)` overload? I don't believe we wanted that.

**Comment by eiriktsarpalis** [comment]
Moving to 7.0.0, since it didn't make it to preview 7.

**Comment by lateapexearlyspeed** [comment]
Hi, I would like to learn and try this issue by [PR](https://github.com/dotnet/runtime/pull/61196). Will notify when it is ready for review, thanks.

**Comment by eiriktsarpalis** [comment]
Cool @lateapexearlyspeed, assigning the issue to you

**Comment by lateapexearlyspeed** [comment]
Hi, there are some questions during working on it, could anyone please help answer these, thanks :)

- > public ReadOnlySpan<T> AsSpan(Range range);

`Range` is from .netstandard2.1, but project [System.Collections.Immutable](https://github.com/dotnet/runtime/blob/5fa6dd364982be4ffd83358adbf130d88049c72a/src/libraries/System.Collections.Immutable/src/System.Collections.Immutable.csproj#L3) and its ref project include target '.netstandard2.0', so how to add this new method into ?

- Existing `RemoveRange(items)` methods have following behaviors (I changed method logic so that existing test can report following output to describe previous behavior), so just confirm is previous logic as expected ? - only remove first occurrence element from array.

> System.Collections.Immutable.Tests.ImmutableArrayTest.RemoveRangeEnumerable(source: [1, 2, 2, 3], items: [2], comparer: null) [FAIL]
>         Assert.Equal() Failure
>         Expected: ImmutableArray<Int32> [1, 2, 3]
>         Actual:   ImmutableArray<Int32> [1, 3]

- Just wonder which methods should be the substitute for existing methods with `IEnumerable<T>` based argument so that users can efficiently pass their `IEnumerable<T>` for `AddRange` and `RemoveRange` ?

- I have synchronized apis for implementation and reference project of System.Collections.Immutable. But how to enable remote build pipeline for this breaking change PR by 

> ApiCompat failed comparing net5.0 to net7.0. If this breaking change is intentional, the ApiCompat baseline can be updated by running 'dotnet build /__w/1/s/src/libraries/shims/ApiCompat.proj /p:UpdatePreviousNetCoreAppBaseline=true'

**Comment by eiriktsarpalis** [comment]
> Range is from .netstandard2.1, but project System.Collections.Immutable and its ref project include target '.netstandard2.0', so how to add this new method into ?

I believe the standard way of consuming Span types in netstandard2.0 projects is by consuming the `System.Memory` nuget package. Alternatively the APIs could be elided from the netstandard2.0 TFM, @terrajobst I presume the former is the preferred approach here?

**Comment by terrajobst** [comment]
Yeah, there is only one method that accepts a Range. Eliding that from .NET Standard 2.0 seems fine.

**Comment by lateapexearlyspeed** [comment]
Thanks @eiriktsarpalis and @terrajobst , skipped compilation for `public ReadOnlySpan AsSpan(Range range)`; from .netstandard2.0.

Can anyone help answer other questions ?

> * Existing `RemoveRange(items)` methods have following behaviors (I changed method logic so that existing test can report following output to describe previous behavior), so just confirm is previous logic as expected ? - only remove first occurrence element from array.
> 
> > System.Collections.Immutable.Tests.ImmutableArrayTest.RemoveRangeEnumerable(source: [1, 2, 2, 3], items: [2], comparer: null) [FAIL]
> > Assert.Equal() Failure
> > Expected: ImmutableArray [1, 2, 3]
> > Actual:   ImmutableArray [1, 3]
> 
> * Just wonder which methods should be the substitute for existing methods with `IEnumerable<T>` based argument so that users can efficiently pass their `IEnumerable<T>` for `AddRange` and `RemoveRange` ?
> * I have synchronized apis for implementation and reference project of System.Collections.Immutable. But how to enable remote build pipeline for this breaking change PR by
> 
> > ApiCompat failed comparing net5.0 to net7.0. If this breaking change is intentional, the ApiCompat baseline can be updated by running 'dotnet build /__w/1/s/src/libraries/shims/ApiCompat.proj /p:UpdatePreviousNetCoreAppBaseline=true'

**Comment by airbreather** [comment]
> Thanks @eiriktsarpalis and @terrajobst , skipped compilation for `public ReadOnlySpan AsSpan(Range range)`; from .netstandard2.0.
> 
> Can anyone help answer other questions ?

I was going to let the experienced members of the team weigh in instead of commenting myself, since I'm just some random guy, but since it's been a few days... I expect the dotnet team to reject breaking changes like the ones you're asking about, especially when they're such hard breaks as removing `AddRange(IEnumerable<T>)` and `RemoveRange(IEnumerable<T>)` would be.

From my perspective, it looks like you might have misinterpreted https://github.com/dotnet/runtime/issues/22928#issuecomment-870794413?  The methods that are commented-out in that reference description probably weren't meant to be treated as "remove these methods", but rather "these methods already exist, so you don't need to add them for this".
- The discussion about breaking changes actually centers around a much softer breaking change, where I believe that adding the new overloads could make it so that `immArray = immArray.AddRange(myCustomThing);` compiles just fine today, but would be ambiguous after the change, for some unlikely values of `myCustomThing`.
- That breaking change, where something that's currently unambiguous becomes ambiguous, is the only breaking change that I can see being accepted, and I agree with that decision FWIW.

I could be mistaken, which is again why I was holding off on commenting, but I do have an interest in these new APIs, and I would very much appreciate the `IEnumerable<T>` versions sticking around...

**Comment by eiriktsarpalis** [comment]
@airbreather's interpretation is accurate, apologies for not clarifying this earlier.

**Comment by terrajobst** [comment]
> The methods that are commented-out in that reference description probably weren't meant to be treated as "remove these methods", but rather "these methods already exist, so you don't need to add them for this".

That is corrected. I often add those for context, in order to judge how the new APIs compose with (the relevant subset) of the existing APIs.

> That breaking change, where something that's currently unambiguous becomes ambiguous, is the only breaking change that I can see being accepted, and I agree with that decision FWIW.

Agreed. We try to avoid source breaking changes like this, but we accept them when there is no other way to make progress. That is, we prefer creating designs that don't cause them, but we're also trying to avoid design-paralysis or frankendesigns purely because some source code would need a cast.

**Comment by lateapexearlyspeed** [comment]
Thanks @airbreather's interpretation.

**Comment by lateapexearlyspeed** [comment]
Hi, this [PR ](https://github.com/dotnet/runtime/pull/61196)is ready for review, thanks !
