### ISSUE TITLE
CoreCLR -- Audit C++ use of macro names and identifiers with leading underscore

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#2303]
@lpereira Noted that the use of identifiers with leading underscores is prohibited by the C++ standard in certain cases.

I will fix a number of them related to TARGET_* and HOST_*, but more remain.

 The general rule is that any identifier with a leading underscore or a double underscore is reserved for use by the implementation of the compiler et al. in global scope.  This includes macros.

See for instance https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier.

There are macros which we are using which control the implementation and are therefore proper.

**Comment by sdmaclea** [comment]
There are quite a lot.

```bash
$ cd src/coreclr
$ git grep "^[ \t]*#[ \t]*define *_[A-Z_]" | grep -v "System.Private.CoreLib" | wc -l
4611
```

Most are in src/coreclr/src/pal. Maybe they are OK...

**Comment by cspatig** [comment]
I'd like to try my hand at contributing and I'm thinking this may be a good first issue for me to look into. Any suggestions would be much appreciated. I imagine I'll run the grep in the comment above and start working through what that finds. If I understand the issue correctly the leading and trailing underscores just need to be removed (tedious, but not difficult). Is my understanding correct?

**Comment by jashook** [comment]
Adding a few people who may be able to help. Thank you for your interest @cspatig! /cc @janvorli @sdmaclea

**Comment by cspatig** [comment]
Just following up on this. If someone could give me a quick overview of how to run the tests associated with the project I'd really appreciate it. I've been working through some of the header files in my spare time and everything seems to be building without issue, but I'd like the added security of knowing the tests are still working as expected.

**Comment by janvorli** [comment]
@cspatig here is what you can use to build and run coreclr tests that should exercise most of the coreclr native runtime:
On Windows:
From the root of the repo, run
```
build.cmd Clr+Libs -c Release -rc Checked
cd src\coreclr
build-test.cmd checked -priority=1
tests\runtest.cmd checked
```

On Linux or OSX:
From the root of the repo, run
```
./build.sh Clr+Libs -c Release -rc Checked
cd src/coreclr
build-test.sh Checked -priority1
tests/runtest.sh Checked
```

**Comment by sdmaclea** [comment]
Also note, if you upload a draft PR, CI will run most of them.  It has the advantage of running the test on all supported architectures.

**Comment by danmosemsft** [comment]
I think at present CI has stopped running on draft PR's (separate issue) - if that's the case you may have to use a regular PR

**Comment by cspatig** [comment]
Checking in again. I am seeing three tests fail every time I run the test commands referenced above. I pulled down a fresh copy of master and ran the tests and am still seeing them fail so I don't believe it is due to the header files I've changed so far. Any thoughts would be appreciated. I'm running MacOS 10.15.6 and have run the brew dependency install. I've attached a screenshot of the test output. 
![Screenshot at Aug 23 12-11-38](https://user-images.githubusercontent.com/5324978/90985539-ea003480-e539-11ea-8eac-0d248ef57723.png)

**Comment by janvorli** [comment]
@cspatig can you please share details on the actual failures? You should see them in the console output printed during the test execution. It would be great if you could share it as a gist instead of a screenshot (copy the text from the console and paste it to a gist that you create). If you never created a gist before, it is very easy. On the top right of this web page, there is a large `+` button (next to your profile icon). If you click it, a dropdown menu will show a list of options including "create a gist"

**Comment by cspatig** [comment]
Here is the Output of the failing tests: https://gist.github.com/cspatig/27b9d2663902f773b2b554327d3a23a9
Specific output for tracing.eventpipe.XUnitWrapper: https://gist.github.com/cspatig/a7e922d16c4b8190b28bb59012384aae
Specific output for profiler.unittest.XUnitWrapper: https://gist.github.com/cspatig/6c4ca52bd5f52fd233b0345dbf36653e
Specific output for Loader.binding.XUnitWrapper: https://gist.github.com/cspatig/ceeef91221d3eeee87e8a34366236f6e

Let me know if theres any other information that would be helpful or that I might have missed.

**Comment by janvorli** [comment]
@cspatig thank you! I'll take a look today or on Monday and get back to you.

**Comment by janvorli** [comment]
@cspatig I've found that I get exactly the same errors when running the coreclr tests on my local Mac, so they are clearly unrelated to your changes.

**Comment by cspatig** [comment]
Thanks for checking on this for me! I'll proceed with the assumption that if I don't break any more tests everything is fine.
