### ISSUE TITLE
Proposal: ValueTask.WhenAll

### ISSUE THREAD

**Issue by casperOne** [dotnet/runtime#23625]
Currently, when I have a number of `Task` instances where I want to perform aggregate operations across all of them (waiting for all of them to complete, for any of them to complete, etc.), I like to use the static `WhenAll`, `WhenAny`, etc. methods.

I also like to use `ValueTask<T>` as well for areas where I don't need the heap allocation that a `Task<T>` brings.

That said, I can't currently use `WhenAll`, `WhenAny`, etc. because they take sequences of `Task<T>`.  While there *are* workarounds, all of them fall short in some way:

* I could call `AsTask`, but then that allocates a `Task<T>` and call the existing methods on `Tasks` but the allocations is the situation I was trying to avoid in the first place.
* I could write my own, but [the coreclr implementation is quite robust](https://github.com/dotnet/coreclr/blob/eb2e9f90ba3679fa8386c4130f81c8061e8d4ca4/src/mscorlib/src/System/Threading/Tasks/Task.cs#L5501), and I'd certainly miss situations that are coded for in there.

This specific example is for `ValueTask<T>` but it really applies to any awaitable type.

I also think we'd need a new signature for `WhenAny`; the current implementation returns a `Task`, and the pattern to figure out *which* task finished is to do an equality comparison on the reference returned.  I don't really agree that [checking the result as `ValueTask<T>` does](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Extensions/src/System/Threading/Tasks/ValueTask.cs#L90) is the right way (imagine waiting on signals for `true`/`false` results from multiple votes, checking equality on the result won't work here).

**Comment by NinoFloris** [comment]
Related https://github.com/Cysharp/ValueTaskSupplement/blob/master/src/ValueTaskSupplement/ValueTaskEx.WhenAny.tt

**Comment by wstaelens** [comment]
any updates on this? I need to load different items calls return ValueTask. Would be more efficient if I can use something similar to Task.WhenAll for ValueTask!

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#await-tasks-efficiently

**Comment by stephentoub** [comment]
>  Would be more efficient if I can use something similar to Task.WhenAll for ValueTask
> https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#await-tasks-efficiently
https://github.com/dotnet/runtime/issues/39230

Note you can already do:
```C#
await Task.WhenAll(valueTask1.AsTask(), valueTask2.AsTask(), valueTask3.AsTask(), ...);
```

**Comment by wstaelens** [comment]
@stephentoub but that creates additional allocations.

**Comment by AraHaan** [comment]
I ran into this problem as well recently when wanting to execute stored procedures in the ``select`` part in query style linq code (of which all return ``ValueTask``.

**Comment by deeprobin** [comment]
```cs
public partial class ValueTask {
    // Span to reduce heap allocations
    public static ValueTask WhenAll(ReadOnlySpan<ValueTask> tasks);

    // params to be consistent with Task.WhenAll
    public static ValueTask WhenAll(params ValueTask[] tasks);
   
    public static ValueTask WhenAll(IEnumerable<ValueTask> tasks);
}
```

**Comment by stephentoub** [comment]
I'm of mixed minds about this one.

On the one hand, I get it, there's a desire to write the simple `await ValueTask.WhenAll(SomeVT1(), SomeVT2());`, and in some situations it'll allocate a bit less than `await Task.WhenAll(SomeVT1().AsTask(), SomeVT2().AsTask());`.

On the other hand
- It's trivial to achieve the desired functionality today, just by using `.AsTask()` to get a Task from the ValueTask.  This is functional, and while it does result in an allocation if the ValueTask isn't backed by a Task (if it's backed by a Task, it's free), WhenAll itself isn't going to be allocation-free, especially an overload that works with `ValueTask<TResult>` and needs to return all of the results.
- There's also no general way today to convert a `ValueTask<TResult>` to a `ValueTask`, which means unlike where `Task.WhenAll` can work with any number of non-generic tasks and generic tasks with different generics, to use a `ValueTask.WhenAll` all of the inputs would either need to be non-generic `ValueTask`s or they'd need to all be `ValueTask<T>` all with the same `T`.  That could be avoided by having overloads for specific arities, e.g. `public static ValueTask<(T1, T2, T3)> WhenAll<T1, T2, T3>(ValueTask<T1> task1, ...)`, etc., but there's still no escape hatch for once you go beyond whatever max arity is provided, other than the already existing solution of just using Task.WhenAll.
- We also don't have the ability with `ValueTask.WhenAll` to handle failures well.  With `Task.WhenAll`, you can get an exception indicating that something failed, and then go back through all of the constituent tasks and examine each to see which succeeded and which failed, and if they failed, with what error.  With `public static ValueTask WhenAll(...)`, that's not possible, since the moment you call WhenAll, you can never touch any of those input `ValueTask`s again.
- And finally, from a design perspective, we generally message ValueTask as being appropriate when you expect the consumer to directly await.  ValueTask isn't as flexible as Task and you can easily get into misuse situations if you store them, pass them around, etc., yet a ValueTask.WhenAll is only useful if you don't immediately await the thing (since by definition you need two things for the call to be useful).

While this may be an unpopular opinion, at this point I don't think we should add this.  There are existing libraries / source generators folks have built and shared that provide such implementations (some mentioned earlier in the thread), and anyone who needs this functionality can reference those existing libraries and/or copy and paste whatever implementations they need.

**Comment by HardBlock729** [comment]
@stephentoub Should we be relying on third party implementations for something that feels like a missing feature? One of the biggest issues with ValueTask is the inability to await more than one at once. This could cause a lot of performance issues and feels like something that should be added to the framework natively rather than needing a whole new lib.

**Comment by stephentoub** [comment]
> Should we be relying on third party implementations...

Yes

> ... for something that feels like a missing feature?

There are lots of things that might "feel like a missing feature" to some.  That doesn't mean all of them must be included in the core libraries.  And I enumerated a bunch of reasons why it's not there by design.

**Comment by markusschaber** [comment]
I just came across some use case. I have a whole collection of objects which implement `IAsyncDisposable`. Their disposal might take a bit (as they're stopping and waiting for background tasks), so I want to dispose them in parallel.

My current solution is to use something like `mycollection.Select(s => s.DisposeAsync().AsTask())` and use Task.WhenAll().

I cannot use Tasks directly, as `IAsyncDisposable` forces the use of `ValueTask`.

**Comment by AraHaan** [comment]
I agree, I think IAsyncDisposable should have went with allowing a Task OR ValueTask version be implemented on the Async dispose method.

**Comment by stephentoub** [comment]
> by it using a common interface for a return type that both Task and ValueTask inherit from

That would defeat the purpose of ValueTask. Returning am interface would force it to be boxed. You can also already return a Task just be doing `new ValueTask(task) `.

> My current solution is to use something like mycollection.Select(s => s.DisposeAsync().AsTask()) and use Task.WhenAll().

Yes, adding `.AsTask()` is how you use everything to do with Task.
