### ISSUE TITLE
cannot import X509Certificate from file in .net core 2.0

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/runtime#23763]
@xingzhougmu commented on [Sat Sep 02 2017](https://github.com/dotnet/core/issues/932)

# Issue Title

cannot import X509Certificate from file in .net core 2.0

# General

The following code works perfectly in .net core 1.0, however, does not in .net core 2.0.
`X509Certificate clientCert = new X509Certificate(Directory.GetCurrentDirectory() + "/Certs/Production/CN_Certificate.crt");`

Under .net core 2.0, the exception is as below:

> {Interop+AppleCrypto+AppleCommonCryptoCryptographicException: Unknown format in import.
>    at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
>    at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName)
>    at Test.Program.Main(String[] args) in /Users/xzhou/Projects/Test/Program.cs:line 40}

> For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by david-castaneda** [comment]
I was able to resolve this issue by creating a pkcs12 file from my cert & key. You can use the following command.

`openssl pkcs12 -export -out Cert.p12 -in your-cert.pem -inkey your-key.pem`

And then 

```dotnet
var certificate = new X509Certificate2(your-p12-bytes, your-pass);
```

**Comment by dazinator** [comment]
I am encountering the same type of error as in #47005 (which is closed and locked) but this issue was linked so just commenting here.

> System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
 ---> System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Application' class value '13', but it should have been 'Universal' class value '16'.
   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
   at System.Formats.Asn1.AsnDecoder.ReadSequence(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnValueReader.ReadSequence(Nullable`1 expectedTag)
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PfxAsn& decoded)
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PfxAsn& decoded)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags 

In my case, `KeyVault` helped me get into this situation. 
We use a local development PFX when debugging locally and didn't see any issues with our code. When we then deployed to a test environment, we provision the PFX's from keyvault.
When you download a `pfx` from keyvault using the `az keyvault secret download` cli command, it likes to download PFX file secrets as plain text by default. So you think you have a valid PFX file, but if you try to read from it you'll hit this issue.
This issue was raised as a docs problem here: https://github.com/Azure/azure-cli/issues/11084
The solution here is make sure your PFX is downloaded in raw binary form from keyvault, so no conversion is necessary.

**Comment by monty241** [comment]
Same error as on #47005, but with different approach:

```
cert = new X509Certificate2(filePath, default(string), X509KeyStorageFlags.DefaultKeySet);
```

with `filePath` pointing to a DLL. Works on .NET Framework 4.8 and .NET Core on Windows. Fails on Linux 6.0.3 with:

> System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
>  System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Application' class value '13', but it should have been 'Universal' class value '16'.\n   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)\n   at System.Formats.Asn1.AsnDecoder.ReadSequence(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed, Nullable`1 expectedTag)
>   at System.Formats.Asn1.AsnValueReader.ReadSequence(Nullable`1 expectedTag)
>   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PfxAsn& decoded)\n   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PfxAsn& decoded)

Use case is to in-code (obfuscated) validate a DLL being signed with the intended certificates instead of relying on standard, but possibly tampered, OS-features on an untrusted node.

**Comment by wfurt** [comment]
should this be closed @bartonjs as we now have PEM loading functions?

**Comment by bartonjs** [comment]
I think it was also sort of being a placeholder of "oh, on Windows bare base64 works", but since there haven't been a lot of complaints on that point I think it's fine to close it out.
