### ISSUE TITLE
System.Diagnostics.TraceSource doesn't read configuration from App.config in .NET Core?

### ISSUE THREAD

**Issue by jemiller0** [dotnet/runtime#23937]
The following code outputs "Hello, world!" as a trace message to the console when in a .NET Framework console application. When the same code is used in a .NET Core console application, it outputs nothing. 

Program.cs
```csharp
using System.Diagnostics;

namespace ConsoleApp5
{
    class Program
    {
        private readonly static TraceSource traceSource = new TraceSource("ConsoleApp5", SourceLevels.All);

        static void Main(string[] args)
        {
            traceSource.TraceEvent(TraceEventType.Information, 0, "Hello, world!");
        }
    }
}
```

App.config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.diagnostics>
    <trace autoflush="true">
      <listeners>
        <add name="consoleTraceListener" />
        <add name="textWriterTraceListener" />
      </listeners>
    </trace>
    <sharedListeners>
      <add name="consoleTraceListener" type="System.Diagnostics.ConsoleTraceListener" traceOutputOptions="DateTime,ThreadId" />
      <add name="textWriterTraceListener" type="System.Diagnostics.TextWriterTraceListener" traceOutputOptions="DateTime,ThreadId" initializeData="Trace.log" />
    </sharedListeners>
    <sources>
      <source name="ConsoleApp5" switchValue="Verbose">
        <listeners>
          <add name="consoleTraceListener" />
          <add name="textWriterTraceListener" />
        </listeners>
      </source>
    </sources>
  </system.diagnostics>
</configuration>

```

Also, I found that if I try to read a connection string using System.Configuration.ConfigurationManager and I have the system.diagnostics section in the App.config, I receive the following error. I'm assuming that .NET Core doesn't have a machine.config where the system.diagnostics section would normally be defined?

```
Unhandled Exception: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Library2\LibraryConsoleApplication\bin\Debug\netcoreapp2.0\LibraryConsoleApplication.dll.config line 6)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_ConnectionStrings()
   at LibraryLibrary.LibraryContext..ctor(String name) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Library2\LibraryLibrary\LibraryContext.cs:line 43
   at LibraryLibrary.LibraryContext..ctor() in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Library2\LibraryLibrary\LibraryContext.cs:line 39
   at LibraryConsoleApplication.Program.Main(String[] args) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Library2\LibraryConsoleApplication\Program.cs:line 13
```

Is there I way I could specify the section similar to the following to get it to work? That is how it is defined in machine.config for .NET Framework.

```xml
  <configSections>
    <section name="system.diagnostics" type="System.Diagnostics.SystemDiagnosticsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
  </configSections>
```

Is there some other way in .NET Core to specify that configuration settings for system.diagnostics?

**Comment by jbe2277** [comment]
I agree with @jemiller0 's proposal to allow configuring it programmatically. This would allow us to use TraceSource when the TraceSource instance is not available to the application.

Maybe you find my Wiki page interesting: [Logging with .NET Standard 2.0](https://github.com/jbe2277/waf/wiki/Logging-with-.NET-Standard-2.0). It describes how to use TraceSource and to expose the TraceSource instance. This way it can be used by .NET Core and it might be combined with 3rd party logger like NLog.

**Comment by obiwanjacobi** [comment]
I feel TraceSource should be removed until it works. It is very misleading to put in code that compiles but does not work as expected. It wastes the time of the developer. 
Not sure if there are more cases like these - better to include only stuff that actually works.
You could put it in a prerelease/experimental package, but it must be very clear what the deal is.

**Comment by jemiller0** [comment]
@obiwanjacobi I agree and disagree. The current implementation is brain dead and I think it should be fixed. However, I'm currently using the current brain dead solution with hacks. So, I would prefer that it stay in there and not be removed. It is better to just fix it.

**Comment by MSACATS** [comment]
I just wanted to chime in as well and say what a loss this is.  We used System.Diagnostics.Trace a lot, and it is pretty much the remaining issue in our Framework to Core migration.  

With System.Diagnostics.Trace	

- internal components can expose trace output

- activity is correlated.  for example, we can start an "operation", and that operation will flow through to other components that are tracing
- components can expose multiple discrete trace sources 
- components can access discrete trace options.  for example, we can have a trace switch for whether or not to trace raw HTTP request and response data to our vendors
- - this is separate from "verbose", "info", "warning", etc. 
- - as a concrete example, each vendor integration has its own trace source.  but they share a low-level HTTP component.  That HTTP component has a switch for whether or not to trace the raw request/response data (which it will emit as 'verbose').  The raw data tracing comes out of each vendor's own trace source (each with its own current output level), hence we can specifically trace one vendor's raw HTTP request/response data (tagged with the correlation id of the overall operation!)
- different trace outputs can be routed to different locations (e.g. event log, file, database)
- all of this can be configured via the config file

ILogger can also be set up with the config file, but doesn't provide anything close to this.  For example having a component expose multiple sources, or having specific tracing options (like the HTTP request/response data option).  And the scoping seems to be per-log source, rather than carrying through across multiple components.  The biggest issue is it can only be used via dependency injection, which is not always practical - e.g. an extension method.  Logging always seemed to be one of those grey areas for dependency injection, but in any case Logging is not quite the same as Tracing.
 
DiagnosticSource is a bit closer (any component can emit a diagnostic source), but it's pretty onerous to use and to attach listeners.  Everything would have to be done in code, and basically we'll have to take all the informal Tracing, and put object wrappers on everything, it seems, in order for anything to make sense: It's more of an event logging framework as far as I can tell.  Hence its similarity to EventSource.

I tried wiring things up in code, but that still leaves TraceSwitches - I can configure the trace listeners and whatnot in Startup but there's no way I can see to set a trace switch, they used to read from the configuration to set their runtime value

**Comment by JeremyWard33** [comment]
I just spent a couple hours trying to figure this out.  Why is this not well advertised?  Developers are going to beat their heads on this like I did and that's really bad business for y'all.

**Comment by deeprobin** [comment]
Shouldn't we introduce a label for this called "bot-contribution" so that this can be separated a bit?
@dotnet/area-meta

**Comment by TishSerg** [comment]
Spent hours trying to figure out what I'm doing wrong with `App.config` in .NET 6...
Oh, that's it. Ok, .NET Framework, your shot.

**Comment by jemiller0** [comment]
The .NET Core geniuses decided config files are bad and got rid of them

**Comment by wilson0x4d** [comment]
... this is what happens when every few years a group of new developers appear which don't have adequate exposure to technology, declare it bad, then start removing/replacing things that worked perfectly fine.

after 30+ years of programming i've learned that nothing survives, not even good things. sad, but true. everything everyone has worked on in .NET Core these past few years will also, eventually, be undone by some future generation of programmers that don't have adequate exposure to technology, will declare it bad, then start removing/replacing things that work perfectly fine.

nothing fundamentally changed, but it was still changed.  between the lack of backward compatibility (FROM MICROSOFT NO LESS!) and perpetual bugs being introduced to their development tools i've decided to retire early. make hay in the sun, watch the cattle graze, etc. i'll come back if we're lucky enough to experience another Carrington event and actually need to rebuild the world... but as it is, there are better things to invest precious lifespan into than other people's messes.

</bittervet-rant>

Loosely related, https://github.com/wilson0x4d/diagnostics

... but it is not maintained, and not the most elegant code I've ever written, but if someone is determined to use app.config files and the classic logging framework then you may find some joy there.

such a shame. from DI to logging and everything in between +poof+ gone. what began as a xplat initiative turned into a rewrite from the ground up.

**Comment by jemiller0** [comment]
@wilson0x4d What you said is exactly how I feel about it. Looking forward to retirement. I have often theorized that all the original developers at Microsoft who created .NET quit for higher paying jobs elsewhere. Then Microsoft was left with people who didn't know the existing code base who decided to re-write everything. That might be fine if the result was something that worked better, but, that's not the case. Web development in particular has taken a turn for the worse. It was better 20 years ago.

**Comment by noahfalk** [comment]
I think this got directed to the wrong devs, we want https://github.com/orgs/dotnet/teams/area-system-diagnostics-tracesource for this. Thanks @tarekgh for helping clarify ownership here and I noticed @jkotas fixed the label, appreciate it!

**Comment by RussKie** [comment]
Just to note that the inability to configure `TraceSwitch`s from app.config affects dotnet/winforms, and likely quite a few Windows Forms apps...

**Comment by MSACATS** [comment]
> Just to note that the inability to configure `TraceSwitch`s from app.config affects dotnet/winforms, and likely quite a few Windows Forms apps...

To clarify, is there _any_ way to configure a TraceSwitch now?

**Comment by MSACATS** [comment]
> Just to note that the inability to configure `TraceSwitch`s from app.config affects dotnet/winforms, and likely quite a few Windows Forms apps...

Indeed - https://github.com/dotnet/runtime/discussions/68753

**Comment by Brain2000** [comment]
Wait, so you're telling me that we have win32 forms in .net core 6, but no tracing?
Let me repeat that again, are you telling me there isn't any way to do tracing in .net core???
Someone needs to lay off the crack.

**Comment by jemiller0** [comment]
Not everyone wants to jump through hoops and use dependency injection. The new setup is ridiculous. Maybe it is fine for an ASP.NET web app, which from what I know is where it originated, but, it is ridiculous in other contexts. Besides that, not everyone wants infinite configurability. They want something simple that is included with the core platform that works out of the box and doesn't require a ton of other open source/third party dependencies. I think Microsoft did a really poor job on this. If you want to have the other one in addition to this, then fine, but, this should have been kept if for no other reason for backwards compatibility. I have to wonder about the entire approach that Microsoft took in creating the multi-platform version. Breaking changes all over the place. Dropping Web Forms was ridiculous as well.

**Comment by MarcoDorantes** [comment]
Last time I check, the entire .NET Framework 4.8 is fully supported and still works as usual (including all System.Diagnostics exact behavior as always). The design decision to target a given runtime is, for the most part, on the hands of the designers of a given application-level solution.

**Comment by jemiller0** [comment]
Yes, and 4.8 is basically frozen except for bug fixes. It doesn't take a rocket scientist to see what the problem is. Rewrite all your applications because Microsoft opted for piss poor support of major components such as Web Forms.

**Comment by MarcoDorantes** [comment]
The software designers at Microsoft have taken their design decisions. I assume they are taking good care of their business. Time will tell if that become the case.

On the other hand, I am in charge of my design decisions for my own business. All business solutions of mine are up and running and supporting the businesses of my customers. Their businesses are shield from work-in-progress by any of my providers (including Microsoft). The evolution of those business solutions, of course, includes research on the evidence for completeness of any runtime or API by any provider, way before touching any feature branch (including possible deprecations of any runtime or API to better alternatives).

**Comment by MSACATS** [comment]
Marco, is this a fair summary of your suggestions?

1. stick on .NET Framework 4.8 forever
2. rewrite all tracing simply because there's no way to configure TraceSource, TraceSwitch

and that as long as Microsoft makes money, there is no reason to work out this oversight?

Being honest with yourself, do these seems like particularly constructive suggestions?

**Comment by jkotas** [comment]
> oversight?

`TraceSource` is a very slow tracing mechanism. It was an intentional decision to remove it as the tracing mechanism for the core .NET runtime libraries, not an oversight.

.NET runtime libraries such as networking or sockets have been unified on `System.Diagnostics.EventSource` as the one and only built-in high-performance tracing mechanism.

> rewrite all tracing simply because there's no way to configure TraceSource, TraceSwitch

TraceSource can be configured programmatically as shown above.

**Comment by MSACATS** [comment]
> It was an intentional decision to remove it as the tracing mechanism for the core .NET runtime libraries, not an oversight.

We're not talking about configuring the core libraries, we're talking about our own code.  You're truly arguing that the inability to configure TraceSource via the configuration files is simply for our own good because the performance is bad?  

> TraceSource can be configured programmatically as shown above.

Cool, what about TraceSwitch?  TraceSource and TraceSwitch are closely related.

**Comment by jkotas** [comment]
> You're truly arguing that the inability to configure TraceSource via the configuration files is simply for our own good 

I am not arguing about this part.

**Comment by RussKie** [comment]
> .NET runtime libraries such as networking or sockets have been unified on `System.Diagnostics.EventSource` as the one and only built-in high-performance tracing mechanism.

Optimising for some libraries we've broken other stacks, e.g. Windows Forms. It's no longer possible enable the tracing without recompiling an app.

**Comment by stephentoub** [comment]
>> NET runtime libraries such as networking or sockets have been unified on System.Diagnostics.EventSource

> Optimising for some libraries we've broken other stacks, e.g. Windows Forms

How does networking using EventSource break Windows Forms?

**Comment by RussKie** [comment]
@stephentoub I'm talking about inability to configure tracing via app.config in .NET.

**Comment by MSACATS** [comment]
Okay taking a step back - I don't think these comments trying to persuade us that "we're holding it wrong" (i.e. that this isn't an issue) are productive.

So can we brainstorm solutions?

I think we can presume it's not likely that we're going to bring back the app.config model.  So what is realistic?

Can we have an app pass in xml-like contents to configure the System.Diagnostics stack?  So that even if we're not bringing back app.config per se, an app could still pass through a chunk of configuration XML to configure TraceSource/TraceSwitch?

**Comment by jkotas** [comment]
The logic to read the TraceSource initialization xml should live in https://github.com/dotnet/runtime/tree/main/src/libraries/System.Configuration.ConfigurationManager/src . Would it make sense to do it implicitly when the ConfigurationManager is initialized (no new method required)?

TraceSource would have to expose a few new public methods to make it possible for System.Configuration.ConfigurationManager to initialize it. For example, a new method to return all TraceSwitches instance. These new public methods would have to go through an API review.

**Comment by MarcoDorantes** [comment]
> 1. stick on .NET Framework 4.8 forever

Mark S - ACA, no, those points are not a fair summary of that comment of mine: I mentioned the fact that net48 is still fully supported but that would be a temporary condition. My point is that an app could still be using net48 tracing in the meantime you research for the evolution of tracing, e.g., build or buy, for your own app. So, “1. stick on .NET Framework 4.8 forever” is not what I am saying.

**Comment by ericstj** [comment]
@jkotas what you suggest could work, however I don't think anything in the app would force ConfigurationManager to be initialized, so user code could start tracing before any one touches configuration.  TraceSouce itself might need some light-up code that probes for Configuration via reflection to force that to load.

**Comment by jkotas** [comment]
The app can explicitly initialize ConfigurationManager in its Main method. Adding a single to Main method should not be prohibitive, and gives the app a full control. I would avoid any magic light-up - it can help as much as it can hurt.

**Comment by ericstj** [comment]
I see what you mean, perhaps an explicit method in Configuration would take some magic out of it - avoid folks relying on someone else initializing config and not realizing it.

**Comment by RussKie** [comment]
> The app can explicitly initialize ConfigurationManager in its Main method. Adding a single to Main method should not be prohibitive, and gives the app a full control. I would avoid any magic light-up - it can help as much as it can hurt.

This feels like a sensible workaround, however it appears there's something else is broken if you go down this route:
```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at WinFormsApp1.Program.Main() in D:\Development\!Tests\WinFormsApp1\Program.cs:line 16

  This exception was originally thrown at this call stack:
    System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool)
    System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
    System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
    System.Configuration.ClientConfigurationSystem.EnsureInit(string)

Inner Exception 1:
ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (D:\Development\!Tests\WinFormsApp1\bin\Debug\net6.0-windows\WinFormsApp1.dll.config line 3)
```

Here's a repro that is working for .NET Framework and is failing for .NET: [WinFormsApp1.zip](https://github.com/dotnet/runtime/files/9129545/WinFormsApp1.zip)

**Comment by RussKie** [comment]
The latter looks like the root cause of several other issues we thought were caused by the CPS, e.g.: https://github.com/dotnet/project-system/issues/6784 and https://github.com/dotnet/project-system/issues/7448.

**Comment by deeprobin** [comment]
> > The app can explicitly initialize ConfigurationManager in its Main method. Adding a single to Main method should not be prohibitive, and gives the app a full control. I would avoid any magic light-up - it can help as much as it can hurt.
> 
> This feels like a sensible workaround, however it appears there's something else is broken if you go down this route:
> 
> ```
> System.Configuration.ConfigurationErrorsException
>   HResult=0x80131902
>   Message=Configuration system failed to initialize
>   Source=System.Configuration.ConfigurationManager
>   StackTrace:
>    at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
>    at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
>    at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
>    at System.Configuration.ConfigurationManager.GetSection(String sectionName)
>    at System.Configuration.ConfigurationManager.get_AppSettings()
>    at WinFormsApp1.Program.Main() in D:\Development\!Tests\WinFormsApp1\Program.cs:line 16
> 
>   This exception was originally thrown at this call stack:
>     System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool)
>     System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
>     System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
>     System.Configuration.ClientConfigurationSystem.EnsureInit(string)
> 
> Inner Exception 1:
> ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (D:\Development\!Tests\WinFormsApp1\bin\Debug\net6.0-windows\WinFormsApp1.dll.config line 3)
> ```
> 
> Here's a repro that is working for .NET Framework and is failing for .NET: [WinFormsApp1.zip](https://github.com/dotnet/runtime/files/9129545/WinFormsApp1.zip)

I'll investigate in this.

**Comment by ericstj** [comment]
@deeprobin please hold off for now.  We need API to fix this.

@RussKie that's because ConfigurationManager doesn't have the type registration for the section.  I've added that in a prototype here; https://github.com/ericstj/runtime/tree/addDiagConfig.  We'll need some more work to refine API on this and test it if we want to make the change.  Removing up-for-grabs for now.

**Comment by ericstj** [comment]
> The latter looks like the root cause of several other issues we thought were caused by the CPS

Whenever you see `ConfigurationErrorsException: Unrecognized configuration section` it means the `app.config` used a named section that wasn't registered.  In .NETFramework that would happen in `machine.config`.  In .NETCore we don't have a machine.config, instead we have an implicit one https://github.com/dotnet/runtime/blob/cd75ae127698b66821b5a2d364aa5ff7aa1a4a2a/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L75-L94
Since we don't have all the same sections supported in .NETCore many of those sections are not registered at all and produce this exception.  The right fix in most cases is to remove the unused portion of the `app.config`.  Perhaps we should improve that exception message so that it lets the developer know what to do.

**Comment by RussKie** [comment]
> In .NETFramework that would happen in `machine.config`. In .NETCore we don't have a machine.config, instead we have an implicit one

Ah, now it starts clicking together. It's been many years since I had to deal with this. Thank you for clarifying this.

**Comment by danmoseley** [comment]
Thanks @steveharter for fixing this as a DCR. Hopefully this allows the folks above to migrate from .NET Framework to .NET 7. Commenters above, please let us know if this doesn't unblock you.

**Comment by RussKie** [comment]
@danmoseley please excuse my ignorance, what's DCR?

**Comment by jkotas** [comment]
Design Change Request. It is Microsoft acronym used to describe features that got added after feature complete date. DCRs need some level of approval, the feature teams cannot just go ahead and implement them.

**Comment by RussKie** [comment]
Thank you @jkotas
