### ISSUE TITLE
Support System.DirectoryServices.Protocols on Linux/Mac

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#23944]
Port `System.DirectoryServices.Protocols` to Linux & Mac -- we need to decide on x-plat LDAP library to use first

Note: Offshoot from larger topic dotnet/runtime#14734

**Comment by flamencist** [comment]
I wrote cross platform library [ldap4net](https://github.com/flamencist/ldap4net). Unlike Novell the library use same way as DirectoryServices and supports integrated passwordless authentication.
Also expected support of ldap v3 controls.

**Comment by pasikarkkainen** [comment]
@flamencist cool! Are you planning to try to get ldap4net merged to dotnet core?

**Comment by flamencist** [comment]
> @flamencist cool! Are you planning to try to get ldap4net merged to dotnet core?

Probably but now  I am focusing on implementation compatibility with ldap v3 features.

**Comment by JasonPierce** [comment]
With .NET Framework and .NET Core merging in .NET 5 (now in [Preview 1](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-1/)), it sounds like we'll get proper cross-platform support (i.e., at the level currently available in .NET Framework)

**Comment by yaakov-h** [comment]
uhhhh, "merging"? That's not what's happening.

**Comment by JasonPierce** [comment]
@yaakov-h at the risk of hijacking this thread, would you care to expound upon your comment?

**Comment by OskarKlintrot** [comment]
.NET 5 is basically just .NET Core 4.0 but since .NET Framework is already at version 4 and .NET Core is replacing (not merging with) .NET Framework with it's next release .NET Core will be called .NET 5 instead (just imagine the confusion with .NET Framework 4.x and .NET 4.x). I simplified it a bit but that's the broad strokes from my understanding.

**Comment by danmosemsft** [comment]
What @OskarKlintrk says above is correct (well at least the first para..can't say about lucky numbers..)

**Comment by joperezr** [comment]
Just as FYI for all people interested in this, I've put up a PR https://github.com/dotnet/runtime/pull/35380 that is adding Linux support for S.DS.P. It is currently under review and only adding support for Linux, but once that is in I will take a look at what it would take to also add support for Mac.

**Comment by joperezr** [comment]
Most of the support for Linux has been merged now. I'm reopening the issue to track two more things I want to finish before we call this issue done:
- [ ] Add OSX support
- [ ] Add Default credentials support (meaning you can create an LdapConnection object without requiring credentials when you have ran a successful kinit command on the server/machine)

I'm planning on addressing both of them in subsequent PRs

**Comment by iSazonov** [comment]
Will it be in 5.0 Preview4?

**Comment by MarkusAmshove** [comment]
Does this issue also include the namespace `System.DirectoryServices.AccountManagement`? I'm having trouble finding informations about it :-)

**Comment by flamencist** [comment]
> Does this issue also include the namespace `System.DirectoryServices.AccountManagement`? I'm having trouble finding informations about it :-)

No. Its another big task.

**Comment by joperezr** [comment]
> Will it be in 5.0 Preview4?

No, preview 4 has already been forked so this would go into preview 5. Alternatively you can add our nightly feed to your project and could take a dependency on the nightly builds which will soon have this change (nightly builds have been broken for a little while but I believe our team is close on fixing that.)

> Does this issue also include the namespace System.DirectoryServices.AccountManagement? I'm having trouble finding informations about it :-)

As @flamencist points out, this only includes System.DirectoryServices.Protocols library. We decided to support this one on Linux/Mac as opposed to the other DirectoryServices ones as the API for this one was strictly down to the protocol. The other DirectoryServices namespaces have some of Windows-specific types and COM types leaked into the surface area, so it would be hard to support that API on Linux/MAC.

**Comment by iSazonov** [comment]
> The other DirectoryServices namespaces have some of Windows-specific types and COM types leaked into the surface area, so it would be hard to support that API on Linux/MAC.

It seems AccountManagement is implemented based on "providers" and I hope it is possible to add Linux PAM too.

**Comment by FWest98** [comment]
> > Does this issue also include the namespace System.DirectoryServices.AccountManagement? I'm having trouble finding informations about it :-)
> 
> As @flamencist points out, this only includes System.DirectoryServices.Protocols library. We decided to support this one on Linux/Mac as opposed to the other DirectoryServices ones as the API for this one was strictly down to the protocol. The other DirectoryServices namespaces have some of Windows-specific types and COM types leaked into the surface area, so it would be hard to support that API on Linux/MAC.

So do I understand correctly that namespaces like S.DS.AM will not be supported for .NET 5 on Linux? Do you think it could be a potential future addition, or do you rule it out completely at this point?

**Comment by joperezr** [comment]
It is not in the plans to support S.DS.AM for .NET 5 in Linux as our solution for communicating and controlling LDAP servers in Linux is via System.DirectoryServices.Protocols for now. Is there a specific scenario you have in mind that you can do with AccountManagement but not with Protocols?

**Comment by iSazonov** [comment]
>  Is there a specific scenario you have in mind that you can do with AccountManagement but not with Protocols?

Currently Windows PowerShell has LocalAccounts module based on non-public Windows API. I port the module on AccountManagement API with expectation the API will be ported on Unix with (perhaps) PAM support. If we get this, PowerShell 7 users get possibilities to manage local and domain/ldap accounts from any platform.

**Comment by FWest98** [comment]
I'm working on an application that does a lot of user and group management through S.DS.AM, which I am planning on running in Kubernetes. Currently, it works with Windows hosts and pods within Kubernetes, but that is tricky to manage and some of our toolkit does not work with Windows in K8s (for example, secret injection from HashiCorp Vault). Add to that the extra licensing costs and computing resources...

Reworking the application to S.DS.P is probably possible, but very inconvenient and would require significant work, as well as being more cumbersome to work with native LDAP objects instead of full-featured Principal objects from AM.

**Comment by joperezr** [comment]
I see. It does sound that S.DS.P supports pretty much all you want to do but I understand the pain that porting from one library to another would mean to apps that already work on Windows. The reasons why we decided to focus first on S.DS.P were because a) S.DS.P supports pretty much all operations you would want to do against an LDAP server, b) supports any type of LDAP server (as opposed to AccountManagement which is focused on ActiveDirectory mostly) and c) S.DS.P API is really mostly platform-agnostic as it is just the implementation of the LDAP protocol, whereas other namespaces like Account management and S.DS expose some WinRT object APIs and other things that are very Windows-specific.

My suggestion for your scenario would be to log a new issue for adding Linux support for S.DS.AccountManagement along with your scenarios, so that we have the one place tracking the need and upvotes for that feature to be added, so we can make a decision of how to go forward, similar to what happened in this issue.

**Comment by MarkusAmshove** [comment]
We use AccountManagement to read all users from specific groups in Active Directory, so no „management“ per se  :) is there a replacement for those use cases on either Core or .NET5? Just from searching it, it also seems like an unresolved issue for ASP Core identities, aside from Azure AD somehow :)

**Comment by joperezr** [comment]
> is there a replacement for those use cases on either Core or .NET5?

Yup with System.DirectoryServices.Protocols you can do that as well. The way to do it would be to create a LdapConnection object, and use it to send a SearchRequest where you can filter out for objects of type user which have the group id on their memberOf property. Granted doing this is a bit more complicated than using AccountManagement, given that with S.DS.P you are working with the Protocol itself, but it is possible and will be there for .NET5

**Comment by FWest98** [comment]
> My suggestion for your scenario would be to log a new issue for adding Linux support for S.DS.AccountManagement along with your scenarios, so that we have the one place tracking the need and upvotes for that feature to be added, so we can make a decision of how to go forward, similar to what happened in this issue.

I added a tracking issue for this: https://github.com/dotnet/runtime/issues/37100

**Comment by rafis** [comment]
Do I undestand properly that implementing `System.DirectoryServices.AccountManagement` is more difficult that `System.DirectoryServices.Protocols` and you will firstly implement `System.DirectoryServices.Protocols` and after maybe 2-3 years `System.DirectoryServices.AccountManagement`?

**Comment by rafis** [comment]
And if you don't want to wait 2-3 years you can refactor project to use some cross-platform library like https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard?

**Comment by joperezr** [comment]
> Do I undestand properly that implementing cross-platform System.DirectoryServices.AccountManagement is more difficult than System.DirectoryServices.Protocols and you will firstly implement System.DirectoryServices.Protocols and after maybe 2-3 years System.DirectoryServices.AccountManagement?

Not really. The reason why we decided to go with Protocols for cross-plat support was because a) the API was meant to support any LDAP server as opposed to AccountManagement which was more ActiveDirectory only, and b) the API in Protocols would give you most of the functionality without really exposing much of things that are Windows-only. If people want AccountManagement to get ported to Unix as well, then I would suggest to comment on the issue #37100 that was created in order to start the discussion.
