### ISSUE TITLE
System.Threading.Channels.Channel<T>: After Complete with exception, the ReadAsync and ReadAllAsync method throws different exception

### ISSUE THREAD

**Issue by chenyj796** [dotnet/runtime#2403]
I have some codes as below:
```csharp
	class Program
	{
		class TestException : Exception
		{
			public TestException()
				: base("This is for test channel complete method with exception")
			{
			}
		}

		static async Task Main(string[] args)
		{
			var channel = Channel.CreateUnbounded<string>();
			channel.Writer.Complete(new TestException());

			try
			{
				await channel.Reader.ReadAsync();
			}
			catch (Exception ex)
			{
				Console.WriteLine($"ReadAsync throws {ex.GetType().Name}: {ex.Message}");
			}

			try
			{
				await foreach (var item in channel.Reader.ReadAllAsync())
				{
				}
			}
			catch (Exception ex)
			{
				Console.WriteLine($"ReadAllAsync throws {ex.GetType().Name}: {ex.Message}");
			}

			Console.ReadLine();
		}


	}

```

After run it, I get the following output:
```
ReadAsync throws ChannelClosedException: The channel has been closed.
ReadAllAsync throws TestException: This is for test channel complete method with exception
```

I hope the ReadAsync also throws TestException just as ReadAllAsync does.

**Comment by stephentoub** [comment]
Looking at it again, we're very consistent as to whether we wrap: we always do in Read/WriteAsync, and we never do in WaitToRead/WriteAsync.  I think we probably did that because the Wait APIs have a built-in way of communicating that the channel has been closed (they return false), whereas it's invalid for a Read/WriteAsync to be pending when the channel is closed, and so that's communicated with the wrapping ChannelClosedException.  ReadAllAsync falls into the same category as WaitToRead/WriteAsync, in that it inherently communicates the channel being closed by ending the enumeration.  As such, I think the current behavior is reasonable.  On top of that, it'd be a breaking change at this point to change.  So, I'm going to close this.  Thanks for the issue.
