### ISSUE TITLE
Provide localization for default error messages in System.ComponentModel.Annotations

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/runtime#24084]
Currently, using attributes like `[Required]` or `[Range(1, 20)]` in ASP.NET Core only gives you english error messages, no matter what culture you set. That is because .NET Core currently only has [one ](https://github.com/dotnet/corefx/tree/master/src/System.ComponentModel.Annotations/src/Resources)(english) resource file. In this [issue ](https://github.com/aspnet/Localization/issues/286), @ryanbrandenburg suggested to create a issue here instead of aspnet/Localization to see if this could get resolved, so this is what I'm doing.

I wish I could just write, for example, `[Required]` and get localized error messages, without the need to write `[Required(ErrorMessage = "bla bla bla")]` all the time, or creating a lot of resource files, or creating a single big resource file for _every_ annotation... All of these options introduce a lot of hassle for anyone developing applications in any language other than english. It's especially frustrating when all the Annotations you use are the default ones.

**Comment by ajcvickers** [comment]
We have no plans to add additional functionality to data annotations.

**Comment by ygoe** [comment]
@ajcvickers So basically, the built-in validation attributes are useless. Don't use them! Ever! Instead, create your own attributes that provide a decent feature set, like localisation of the messages. Either do it in your own project or build, share and use a NuGet package that replaces the entirely broken validation attributes. They're just wasted space in a project deployment. I've tried several things but wasn't able to get localised messages working. I can set a message programmatically – either once and the same for all subsequent requests, or as static property with no access to the current request's language. This is a very frustrating situation. The documentation should really contain a huge warning that says that the BCL validation attributes are a dumb stub and should never used for real applications because they cannot support multilingual UIs.

**Comment by ygoe** [comment]
Even worse, I believe the entire API of System.ComponentModel.DataAnnotations is non-localisable by design. While I can create my own `ValidationAttribute` that can do its own validation and provide its own error message, there's nothing that can tell it what language the message is needed in. The only relevant overridable method `FormatErrorMessage(string name)` is only given the field name (useless) but no environment object, HttpContext or service provider of any kind. I don't see where the current request language should be regarded. Static data obviously isn't appropriate in a multi-threaded web server. The attribute's constructor is executed only twice (once for EF and once for ModelBinding) and never again, so it can't theoretically be used for per-request dependency injection either. There are no other base properties that might be useful.

This lets me question the complete data validation story of ASP.NET (Core) and WPF. It doesn't seem to exist. But it doesn't seem to be needed either. IIRC, EF6 did validate data before sending it off to the database but EF Core doesn't seem to do that anymore. So actually I don't need the concept of validation attributes at all anymore. Instead, I just validate all form data explicitly in each controller method, and if invalid, generate the necessary error validation message for the user. Just like any other model error message.

Oh, I haven't even started to explore the localisation of automatically generated model binding conversion error messages, like when the user enters text into a field where the model type is a number. That's even harder because I can't normally just do that myself in the controller action – the model binder has already done that before. I'll have to find out where and how, and overwrite those default messages, too.

ASP.NET (Core) and WPF just work best when the user only enters all required and valid data. It fails quickly otherwise.

(I know I could and should add client-side validation in ASP.NET, but that's not there yet and that certainly doesn't free the server-side validation from working properly.)
