### ISSUE TITLE
Add "Create" method to EqualityComparer<> class

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#24460]
EDITED by @stephentoub on 4/26/2022 to update proposal:
```diff
namespace System.Collections.Generic
{
    public abstract class EqualityComparer<T> : IEqualityComparer<T>, IEqualityComparer
    {
+        public static EqualityComparer<T> Create(Func<T?, T?, bool> equals, Func<T, int> getHashCode);
    }
}
```

To discuss:
- Making `getHashCode` optional such that the returned instance's GetHashCode would throw `NotSupportedException` if it's used.

---

_From @ViIvanov on December 14, 2017 20:15_

Now we have a `Create` method in [Comparer<> class](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Comparer.cs#L21):
```cs
public static Comparer<T> Create(Comparison<T> comparison)
```

I think, it will be usable to have an analog in EqualityComparer<>:
```cs
public static EqualityComparer<T> Create(Func<T, T, bool> equals, Func<T, int> getHashCode)
```

_Copied from original issue: dotnet/coreclr#15526_

**Comment by weitzhandler** [comment]
I bump into this over and over. I find this very compelling.

**Comment by terrajobst** [comment]
Can someone update the sample to make a compelling case for the currently proposed API? The sample code was for a different proposal.

**Comment by peterduniho** [comment]
> Can someone update the sample to make a compelling case for the currently proposed API? The sample code was for a different proposal.
> If Distinct is the only use case, then maybe we should fix Distinct itself.

I'm not sure what sample you mean, so I'm probably missing part of the point of the request. My apologies about that.. But this isn't just an issue with `Distinct()`. Another common scenario would be various dictionary types (e.g. `Dictionary<TKey, TValue>` and `ConcurrentDictionary<TKey, TValue>`). Pretty much any place you'd want an instance of `IEqualityComparer<T>`, it would be much nicer to be able to quickly define one using lambdas, rather than having to implement a whole new class every time.

The fact that utility libriaries used internally in numerous projects have defined this functionality over and over strongly suggests it'd be a useful addition to the API (for what it's worth, this has come up in pretty much every non-trivial project I've been involved with over the last ten years or so).

Yes, it's true that this could be addressed in other ways. For example, just forget about it and let everyone keep doing what they've been doing (i.e. create the helper methods themselves). Or each of the places in .NET where `IEqualityComparer<T>` can be used can add an overload where instead of passing `IEqualityComparer<T>`, one can pass the necessary lambdas to define the comparer. But putting this in a single centralized place where it can be used for any place one needs `IEqualityComparer<T>` seems to me to be a lot more useful approach.

**Comment by weitzhandler** [comment]
What would be a good way to use `Enumerable.Intersect` with a lambda for equality-comparison?

**Comment by ericstj** [comment]
Given where we are at in 5.0.0 I don't this this will make it.   I do support the scenario, I've come across this before and have felt it jarring that I need to stop coding and create a new type, just when I want to tweak the comparison behavior of a collection.

**Comment by daviburg** [comment]
Needed that today to avoid repeatedly writing classes for Distinct in LINQ

```

    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Inline capable generic equality comparer
    /// </summary>
    /// <typeparam name="T">The type to compare for equality</typeparam>
    public class InlineableEqualityComparer<T> : EqualityComparer<T>
    {
        /// <summary>
        /// Type specific equality function
        /// </summary>
        private readonly Func<T, T, bool> equalityFunction;

        /// <summary>
        /// Type specific hash function
        /// </summary>
        private readonly Func<T, int> hashFunction;

        /// <summary>
        /// Prevents the creation of default instance, as it would be invalid
        /// </summary>
        private InlineableEqualityComparer()
        {
        }

        /// <summary>
        /// Creates a new instance of an equality comparer using the provided functions
        /// </summary>
        /// <param name="equalityFunction">The equality function</param>
        /// <param name="hashFunction">The hash function</param>
        public InlineableEqualityComparer(Func<T, T, bool> equalityFunction, Func<T, int> hashFunction)
        {
            this.equalityFunction = equalityFunction ?? throw new ArgumentNullException(nameof(equalityFunction));
            this.hashFunction = hashFunction ?? throw new ArgumentNullException(nameof(hashFunction));
        }

        /// <inheritdoc/>
        public override bool Equals(T x, T y) => this.equalityFunction(x, y);

        /// <inheritdoc/>
        public override int GetHashCode(T obj) => this.hashFunction(obj);


        /// <summary>
        /// Creates an equality comparer using the provided functions
        /// </summary>
        /// <param name="equalityFunction">The equality function</param>
        /// <param name="hashFunction">The hash function</param>
        /// <returns>The new comparer</returns>
        [SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Same pattern as .NET's Comparer<T>.Create(Comparison<T>) Method")]
        public static IEqualityComparer<T> Create(Func<T, T, bool> equalityFunction, Func<T, int> hashFunction) =>
            new InlineableEqualityComparer<T>(equalityFunction, hashFunction);
    }
```

Usage (with dummy lambdas for the sake of argument):
`.Distinct(InlineableEqualityComparer<MetadataRetrievalNode>.Create((x, y) => true, x => 0))`

**Comment by eiriktsarpalis** [comment]
Came across the need for such a method today while working with Roslyn incremental values. I suspect there might be value in making the `getHashCode` delegate optional, which would help accelerate scenaria like the following
```C#
nodes1.SequenceEqual(nodes2, EqualityComparer<SyntaxNode>.Create((n1, n2) => n1.IsEquivalentTo(n2)));
```
Calling `GetHashCode` on a comparer that doesn't specify a `getHashCode` delegate would throw `NotSupportedException`. It is fairly common to construct comparers that only require the `Equals` method.

**Comment by ViIvanov** [comment]
Not sure, that `NotSupportedException` is a part of equality comparer (`IEqualityComparer<>` or `EqualityComparer<>`) contract 🤔
Someone can expect `NotimplementedException` or even some `ArgumentException` in that case.

Maybe, for your cases it is better to use explicit delegate?
```cs
nodes1.SequenceEqual(nodes2, EqualityComparer<SyntaxNode>.Create((n1, n2) => n1.IsEquivalentTo(n2), _ => throw new NotSupportedException()));
```

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Collections.Generic
{
    public partial class EqualityComparer<T> : IEqualityComparer<T>, IEqualityComparer
    {
        public static EqualityComparer<T> Create(Func<T?, T?, bool> equals, Func<T, int> getHashCode);
    }
}
```

**Comment by stephentoub** [comment]
@bartonjs, in implementing this and using it in various places, I think we should make `getHashCode` optional. It's common to only need Equals and not need GetHashCode (e.g. passing a comparer to SequenceEquals), and I expect a significant number of the consumers for this API will be tests, in which case it's actually beneficial for GetHashCode to throw if it's not supplied in order to validate GetHashCode isn't being used in situations you don't expect it to be used.  Since in the discussion yesterday the room was largely ambivalent about whether to require getHashCode or not and we effectively flipped a coin, I'm going to proceed under the assumption we're ok with it.
```C#
public static EqualityComparer<T> Create(Func<T?, T?, bool> equals, Func<T, int>? getHashCode = null);
```
The only real downside is if GetHashCode was actually needed for a use and someone neglected to supply it because it's optional, but in such cases, they'll likely get an exception almost immediately.

**Comment by bartonjs** [comment]
I'm not sure that I agree that "null-accepting" should immediately jump to "null-defaulting", but I guess I agree with the logic that the exception is fast-coming.

But, yeah, if anyone had said "oh, it's super common in writing tests to not specify an implementation for GetHashCode" then we'd've slapped on the question mark.
