### ISSUE TITLE
FileSystemWatcher does not raise events when target directory is symlink (on linux)

### ISSUE THREAD

**Issue by JustArchi** [dotnet/runtime#25078]
Steps to reproduce:

```shell
mkdir /tmp/realdir
ln -s /tmp/realdir /tmp/symdir
```

Launch a program similar to below:

```csharp
var fsw = new FileSystemWatcher("/tmp/symdir") { NotifyFilter = NotifyFilters.FileName | NotifyFilters.LastWrite };
fsw.Created += (o, i) => Console.WriteLine(i.Name);
fsw.EnableRaisingEvents = true;
```

Create empty file (or any other one):

```shell
touch /tmp/symdir/test.txt # Could be also /tmp/realdir/test.txt, since it's one and the same
```

No event being raised. Event is raised properly if we listen in `/tmp/realdir` instead.

Since expected behaviour of linux programs is to handle symlinks transparently, I expected that `FileSystemWatcher` would properly raise events that happened in real directory. That didn't happen though (no events being raised, I also tested with other event types). I couldn't find similar issue so I consider it a bug, but if this is expected then it should probably be noted somewhere.

Thank you in advance for looking into this.

```
.NET Command Line Tools (2.1.300-preview2-008210)

Product Information:
 Version:            2.1.300-preview2-008210
 Commit SHA-1 hash:  f6065dcc62

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /opt/dotnet/sdk/2.1.300-preview2-008210/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c

```

**Comment by carlossanlop** [comment]
I started poking into this, and I'm wondering if we could add a new notify event to enable listening to the contents of symlinked directories:

```cs
public enum NotifyFilters
{
    FollowSymlinks = 0x02000000
}
```

And to avoid disrupting the world, the code @wfurt pasted above could add the `IN_DONT_FOLLOW` flag by default, and would remove it if the user passed `FollowSymlinks`. Something like:

```cs

// User did not pass the flag, so we keep adding the IN_DONT_FOLLOW flag as before
if ((filters & NotifyFilters.FollowSymlinks) == 0)
{
    _watchFilters |= Interop.Sys.NotifyEvents.IN_DONT_FOLLOW;
}

int wd = Interop.Sys.INotifyAddWatch(_inotifyHandle, fullPath, (uint)(this._watchFilters | Interop.Sys.NotifyEvents.IN_EXCL_UNLINK));
```

Thoughts, @wfurt, @JeremyKuhne ?

**Comment by wfurt** [comment]
I think there are two separate issues @carlossanlop. First one is if the directory we are asked to watch is symlink and then what do we do if there are symlinks within watched directory. 

For first one I think we can:
1.a close this with "work as expected" and perhaps improve documentation
1.b Do fstat/readlink as @JustArchi suggested. That would add one time cost when creating watcher. If we do this we should do macOS as well. 

For second I think it is more tricky. With following links  the search may be huge if you ever have something like ../.. in the tree as well as there may be loop. You can try 
```c#
 Directory.GetFiles("/sys/devices", "foo", SearchOption.AllDirectories));
````
There is really no way how the caller may know or have influence over. 

If we want to proceed, I would open new issue for API proposal. (2a)
We should also validate that that can work on macOS (2b) and Windows (2c - not sore if that is even possible) If this gets through, we would have option to express the desire to treat symlinks  transparently and that can be 1.c option to do it only when explicitly asked. 

The current behavior seems to mimic old Windows behavior. However I do agree that on Unix symbolic links are generally handled transparently. My personal recommendation would be to try 1b (and perhaps mark it as breaking change) but I would be worried about recursively following symbolic links because of possible DoS and other pitfalls.

**Comment by ericstj** [comment]
Do you know if clearing IN_DONT_FOLLOW would still follow file symbolic links when watching a directory?  The docs indicate that IN_DONT_FOLLOW controls following `pathname` which could be a directory.  It wasn't clear to me if it would just follow the symlink on the directory or it would also follow symlinks on files within the directory.  If it didn't do the latter we'd probably need to enumerate the files in the directory to find those that were symlinks and add them as well.

I don't think Windows has this type of functionality, so we might need to enumerate all paths to find the symlinks and add them.  We'd have to watch multiple handles for each directory symlink.  For file symlinks we'd have to watch the containing directory and make sure to only raise events for the single file.

**Comment by wfurt** [comment]
following nested links can be dangerous as that can create loops. (something windows do not need to deal with) 
My suggestion would be to do it only for the name passed in via 

https://github.com/dotnet/runtime/blob/a9c5eadd951dcba73167f72cc624eb790573663a/src/libraries/Common/src/Interop/Unix/System.Native/Interop.ReadLink.cs#L32

Something similar to  #48151

**Comment by ericstj** [comment]
I believe loops can be detected and short-circuited: would have to be if we followed them.  Loops can exist on windows too.  I agree it makes this more complicated.

If all we do is follow the passed in link, why do that here?  Why not instead just allow the user to do that with https://github.com/dotnet/runtime/issues/24271.

**Comment by wfurt** [comment]
We could but #24271 sits there for very long time. And pushes the complexity to the caller. We _could_ make small improvement to FileSystemWatcher instead without new API dependency.

**Comment by ericstj** [comment]
At least in the case I'm looking it I don't believe the root watch is a symlink directory.  The symlinks are files in the directory.  So following symlinks on the root directory won't help.  See https://github.com/dotnet/runtime/issues/36091#issuecomment-704828472.  I'm not sure how many cases will really be helped by only following the root.

IMHO a set of brand new API is easier since it is additive and well defined.  I don't see any major blockers to #24271 (WinRT was mentioned but that's no longer a constraint), just some work to prototype more and drive it through API review.

**Comment by wfurt** [comment]
#36091 seems different. This issue was written for the linked root as far as I can tell.
