### ISSUE TITLE
[System.Runtime.InteropServices] Introduce broader platform definitions. 

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/runtime#25172]
Unity, Xamarin and Mono users suffers from a historic problem with platform detection. This patch introduces definitions for all the existing platforms that .NET supports beyond .NET Core via Unity and
Xamarin.

To cope with the historical setting that OSX has been used in existing code to probe for an Apple OS (iOS, tvOS, watchOS), we introduce new values for all four apple platforms (macOS, iOS, tvOS, watchOS) and also return true when probed for the legacy OSX setting.

The same principle is applied to Linux, we will continue to return true, but the more specific versions of Tizen and Android are supported.

The list has been expanded to all the platforms currently supported by Mono and Unity.

# Proposed Changes

The System.Runtime.InteropServices.OSPlatform is updated to surface the following public definitions:

```csharp
        public static OSPlatform Android { get; } = new OSPlatform("ANDROID");

        public static OSPlatform iOS { get; } = new OSPlatform("IOS");

	// Returns true for Linux, Tizen and Android systems
        public static OSPlatform Linux { get; } = new OSPlatform("LINUX");

        public static OSPlatform macOS { get; } = new OSPlatform("MACOS");

        public static OSPlatform N3DS { get; } = new OSPlatform("3DS");
	
	// This one has historically been used as "Apple platforms", so it returns true
	// on iOS, tvOS, macOS, watchOS.
        public static OSPlatform OSX { get; } = new OSPlatform("OSX");

        public static OSPlatform PlayStation4 { get; } = new OSPlatform("PS4");

        public static OSPlatform PlayStationPortable2 { get; } = new OSPlatform("PSP2");

        public static OSPlatform PlayStationVita { get; } = new OSPlatform("PSVITA");

        public static OSPlatform Switch { get; } = new OSPlatform("SWITCH");
	
        public static OSPlatform Tizen { get; } = new OSPlatform("TIZEN");

        public static OSPlatform tvOS { get; } = new OSPlatform("TVOS");

        public static OSPlatform watchOS { get; } = new OSPlatform("WATCHOS");

        public static OSPlatform WebAssembly { get; } = new OSPlatform("WEBASSEMBLY");

        public static OSPlatform WiiU { get; } = new OSPlatform("WIIU");

        public static OSPlatform Windows { get; } = new OSPlatform("WINDOWS");

        public static OSPlatform XboxOne { get; } = new OSPlatform("XBOXONE");
```

Additionally, `RuntimeInformation`'s `IsOSPlatform` method is modified to cope with the aliasing described before, and Android and Tizen systems are Linux systems, and macOS, tvOS, iOS and watchOS are reported as OSX systems.

Twist: we could make OSX deprecated as well, and introduce an additional AppleOS definition or a Darwin definition to cover Apple-based OSes.

# PR

A pull request with the first batch is available here:

https://github.com/dotnet/corefx/pull/27378

**Comment by am11** [comment]
IMO, RID could be used as [documented](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/pkg/Microsoft.NETCore.Platforms/readme.md#naming-convention) for additional platforms supported by Mono as @eerhardt has pointed out. (the wording of doc could probably be updated to reflect `os or kernel name` instead of `os name`).

There are two unfortunate cases with RID, which probably cannot be rectified now (post-release) but could be avoided for future platforms:

1. disparity in RID design doc and RID in practice in case of `linux-musl-{arch}` series. According to
the doc, architecture-aware RID should have been `linux-x64-musl` (additional qualifier comes at the end) and architecture-agnostic one is correct, `linux-musl`. This is analogous to the existing `win-aot` and `win-x64-aot` and other such `aot` examples. Now we have to special case musllibc architecture-agnostic case, while tokenizing (as of now) [387 keys](https://raw.githubusercontent.com/dotnet/runtime/bd98efe6adf4638d699f92d4b24bc6cdd5e0ca47/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json).
2. `macos` instead of `osx`, so when `watchos`, `ios` and `tvos` are included, they don't look odd.

**Comment by eerhardt** [comment]
> Now we have to special case musllibc architecture-agnostic case, while tokenizing (as of now) 387 keys.

In the current RID design, the strings are not meant to be tokenized. In the RID documentation you linked above it defines a RID as: "A RID is an **opaque** string that identifies a platform."

However, there is a [proposal](https://github.com/NuGet/Home/issues/5862) to change the opaqueness.

**Comment by am11** [comment]
Sure, thanks for pointing it out. I think even for human readability, musl case looks a bit odd. Do you think `linux-musl-64` goes against the documented naming `[os name].[version]-[architecture]-[additional qualifiers]` and other RIDs `win-x64-aot` etc. and should have been `linux-x64-musl` instead? I understand it is probably now too late to change it, but if we had spotted it out earlier, would we have corrected it or has it been just a free-form string?

**Comment by danmosemsft** [comment]
@eerhard not disagreeing they're publicly opaque but note that we "parse" them some ourselves 
https://github.com/dotnet/runtime/blob/890c3b6ac0e7bb2fc9b4aa73201d417dd628b109/src/installer/Directory.Build.props#L228
