### ISSUE TITLE
Move/create authorization classes in .Net Core

### ISSUE THREAD

**Issue by pi3k14** [dotnet/runtime#25773]
The Microsoft.AspNetCore.Authorization namespace contains classes that are useful in .Net Core and is not dependent on ASP.Net Core, please make them available in a .Net Core namespace. Ref. [Make Authorization available outside of ASP.NET Core](https://github.com/aspnet/Security/issues/1480)

**Comment by GrabYourPitchforks** [comment]
As was mentioned at https://github.com/aspnet/Security/issues/1480#issuecomment-335869384, if these packages are truly independent from the ASP.NET Core runtime then there's nothing stopping a non-ASP.NET application from pulling in the packages and using them as-is.

The confusion seems to stem from two issues. First, there's the impression that non-ASP.NET applications are forbidden from using packages that contain _AspNet_ in the name. This isn't true: you should be able to reference them as you would any other package. Since they're independent from the ASP.NET Core runtime they won't pull in any of the runtime aspects.

The second issue is that the package may _in the future_ take a dependency on an ASP.NET Core feature. Such a change wouldn't affect any already-released version of the package. Additionally, if a future version of the package _does_ take such a dependency, then it's evidence that the authorization feature really does belong in ASP.NET Core rather than the base class libraries.

If I have misunderstood the scenario please let me know. Otherwise it seems like there's no action required on the part of the base class library.

**Comment by pi3k14** [comment]
> The confusion seems to stem from two issues. First, there's the impression that non-ASP.NET applications are forbidden from using packages that contain _AspNet_ in the name. This isn't true: you should be able to reference them as you would any other package. Since they're independent from the ASP.NET Core runtime they won't pull in any of the runtime aspects.
...
> If I have misunderstood the scenario please let me know. Otherwise it seems like there's no action required on the part of the base class library.

No one think it is forbidden, but no one with their sanity in place would dream of including a namespace clearly marked for ASP.NET in their non-ASP.NET project. Because there is no guarantee that this will work in the future.
Thinking that you can stay on an old version of a package "forever" doesn't make sense, even an assembly upgrade could break this. Like what was done to support the new Chrome feature recently.

**Comment by GrabYourPitchforks** [comment]
> No one think it is forbidden, but no one with their sanity in place would dream of including a namespace clearly marked for ASP.NET in their non-ASP.NET project.

The namespace is just a name. The package dependencies don't care about the name. The package either works or it doesn't, and from what I'm reading it sounds like the answer is that it works. Why would "no one with their sanity" care about the name?

> Because there is no guarantee that this will work in the future. Thinking that you can stay on an old version of a package "forever" doesn't make sense, even an assembly upgrade could break this.

Why would the namespace matter in this regard? There's nothing inherent in the namespace that would make the package any more or less likely to be compatible from major version to major version.

**Comment by pi3k14** [comment]
> The namespace is just a name.

Really, why do you think it got the name AspNetCore in the first place?

>  Why would "no one with their sanity" care about the name?

YMMV

> There's nothing inherent in the namespace that would make the package any more or less likely to be compatible from major version to major version.

So, you think Microsoft has a review procedure that forbids developers using ASP.NET Core specific classes/methods in an AspNetCore namespace since the first version didn't do that?

BTW - the complete Microsoft.AspNetCore.Authorization namespace isn't usable outside of ASP.NET Core (which is described in the issue).

**Comment by GrabYourPitchforks** [comment]
Can you specify exactly which APIs / classes you want made available to .NET Core apps, plus any issues you currently encounter when trying to use those APIs from non-aspnet project types? Thanks!
