### ISSUE TITLE
Add a version table for all assemblies included inside a NuGet package on its description in order to make it more understandable which assemblies with which versions are provided inside.

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/runtime#26002]
Why are the NuGet versions and the assembly versions not in sync?

### Example

Assembly | NuGet Version | Assembly Version
------ | --------- | --------
[System.Net.Http](https://www.nuget.org/packages/System.Net.Http/) | 4.3.3 | 4.1.1.2

Is this across the board or just some assemblies?

---

I have to go through mental gymanistics when I get exceptions like this:

>System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 

- What NuGet package do I have installed?
- Ok, that corresponds to which assembly version?  Crack open IL Spy...
...

---

What am I not understanding why it is this way?

**Comment by jzabroski** [comment]
I believe there is a great expanse of issues to unpack here, and I've done some of that unpacking in other issues, mostly related to System.ComponentModel.DataAnnotations.  Happy to help flesh out all the holes so that the real development budget required for filling these holes is clear.

**Comment by jzabroski** [comment]
Here is an example of one pain point, although minor, and still better than what the user story was in Visual Studio 2017:

1. I originally built my app to target .netstandard2.0, but due to a missing assembly, changed to a different target framework in an effort to workaround the problem.  I then got this long message:
![image](https://user-images.githubusercontent.com/447485/75068312-f3daa980-54bc-11ea-9561-c7025362e041.png)

2. This screenshot also demonstrates my next pet peeve: System.ComponentModel.Annotations.dll doesn't mention its assembly version, even if you click on that node in Solution Explorer and look at the Properties dialog.

**Comment by ViktorHofer** [comment]
We have no plan to provide a mapping table for previous versions but we consolidated the version logic. Since 5.0, the PackageVersion and AssemblyVersions have been in sync.

**Comment by jzabroski** [comment]
Also, nuget.org added a link to fuget and from fuget, you can manually see a particular packages details quicker than downloading the raw package.  A bit hacky and slow (since you can't query nuget.org to say, "I got this assembly binding issue with an assembly version x.y.z.omega but can't figure out which nuget package that is", but just mentioning this in case anyone else is baffled by this.

@ViktorHofer are there tests in place that validate packageversion == assemblyversion?  Just trying to make sure we're all on the same page here as to why this feature was requested in the first place.  As devs, if we get an exception about a particular assembly missing, it is really painful to figure out which version it is expecting and why.  For me, the natural workflow would be to look it up on nuget.org.

**Comment by ViktorHofer** [comment]
> @ViktorHofer are there tests in place that validate packageversion == assemblyversion? Just trying to make sure we're all on the same page here as to why this feature was requested in the first place. As devs, if we get an exception about a particular assembly missing, it is really painful to figure out which version it is expecting and why. For me, the natural workflow would be to look it up on nuget.org.

The versions might not always map exactly during a servicing release when a package is updated but the `Major` and `Minor` digits, i.e. 6.0.5 -> 6.0.0.1, should always be in sync. We don't have tests in place for that as we are not planning to change this again anytime soon.

**Comment by jzabroski** [comment]
OK, but so you understand, .NET assembly binding goes to the third level, which is why this pain point exists.  I only understand it very well because in December 2018 on Christmas break I spent 5 days getting to the bottom of my .NET Core binding redirect confusions, and replied to a bunch of mysterious issues users were complaining about explaining that the root cause was precisely this issue.
