### ISSUE TITLE
Clean up ref files to more closely match GenerateReferenceSource

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#26187]
Running /t:GenerateReferenceSource leads to a ton of differences between the generated files and what we currently have for the refs.  Some of the differences are by design, e.g. ifdefs, but many are not:
- Out-of-order members
- Missing _dummy or _dummyPrimitive fields (which seems like it could be a bug)
- Missing protected ctors on abstract classes
- Whitespace differences, e.g. blank lines, spaces between generic type parameters, etc.
- Missing namespace qualifiers
- Numeric vs named Flags enum attribute arguments
- etc.

It would be good to clean all of this up, in order to a) do an audit to make sure nothing important is wrong, and b) make it easier in the future to use GenerateReferenceSource for minor additions without then needing to deal with a ton of noise.

**Comment by ericstj** [comment]
@Anipik/@safern didn't we do something like this already?  I thought we got the diff pretty clean after supporting follow-type-forwards.

**Comment by Anipik** [comment]
> I thought we got the diff pretty clean after supporting follow-type-forwards.

We fixed the scenarios(there was a couple of them) where it was not working, but we never did a whole sweep up.

**Comment by safern** [comment]
I think we should do another pass. I remember for stuff that was manual added into the ref src files we added a feature to specify a file with ignored APIs so that should help us get it better for complicated assemblies like System.Runtime.

**Comment by AraHaan** [comment]
Sorry if this is offtopic but how did you guys somehow pack the ref projects with the outputs from the runtime ones in the same packages?

**Comment by ericstj** [comment]
We use a custom packaging system that generates then packs a nuspec.

You can still do it with CSProj. See https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificcontentinpackage

**Comment by ViktorHofer** [comment]
Triage: We want to keep this in 5.0 as we want to fix the parameter name mismatches.

**Comment by ViktorHofer** [comment]
> CC. @ericstj - Is there an easy way to run the tooling for "everything" to try and find out what is actually out of sync?

@tannergooding by building with the [`/p:GenerateReferenceAssemblySource=true` property](https://github.com/dotnet/arcade/blob/e4e5e16cf38c950ed835f8b223ebfdeca3e112aa/src/Microsoft.DotNet.GenAPI/build/Microsoft.DotNet.GenAPI.targets#L9), you can re-generate all reference source files. BUT, doing that would cause duplicate file writes and most likely file locks as TFMs like `net8.0-windows` and `net8.0` would write to the same location.

If you just care about net8.0, you could add the following to the root Directory.Build.targets file:
```xml
<PropertyGroup>
    <!-- Hook onto the TargetsTriggeredByCompilation target which only runs when the compiler is invoked. -->
    <TargetsTriggeredByCompilation Condition="'$(TargetFramework)' == 'net8.0'">
      $(TargetsTriggeredByCompilation);
      GenerateReferenceAssemblySource
    </TargetsTriggeredByCompilation>
</PropertyGroup>
```

That enables GenAPI to run for the net8.0 TFM in all our source projects. You then just need to build allconfigurations: `build.cmd libs -allconfigurations`.

-----

All that said, to provide a comprehensive response I need to add the following (listed by priority):
1. The existing GenAPI is CCI based and has a number of defects that we aren't planning to resolve. Reason for that is, that we have been working on a new Roslyn based GenAPI implementation for the last months. It just last week got enabled in [SBRP](https://github.com/dotnet/source-build-reference-packages) and works nicely so far. There are a number of missing features that doesn't make it yet usable in dotnet/runtime: https://github.com/dotnet/sdk/issues/31088.
2. We have a big number of reference source projects that don't ship anymore, i.e. `System.Data.Odbc`. Since .NET 6, reference assemblies haven't been part of our packages anymore.
The reference source projects which don't ship in a targeting pack (either Microsoft.NETCore.App.Ref, Microsoft.AspNetCore.App.Ref or Microsoft.WindowsDesktop.App.Ref) don't add much value anymore, given that we now have PackageValidation (from the new ApiCompat) enabled. We were actually considering removing these projects and I had a [WIP] PR up for that last year: https://github.com/dotnet/runtime/pull/65775.
3. One aspirational but still standing goal is to use Roslyn's RefOut feature to generate our shipping reference assemblies instead of compiling them ourselves: https://github.com/dotnet/runtime/issues/58163. Note that AspNetCore and WindowsDesktop already leverage Roslyn's feature to generate their reference assemblies which then end up in their targeting packs.

cc @ericstj @andriipatsula @carlossanlop
