### ISSUE TITLE
Extend IDbCommand to include all method implementations

### ISSUE THREAD

**Issue by helloserve** [dotnet/runtime#26505]
It's great that System.Data.Common includes interfaces for the most implementations - it's easy to mock with and thus unit test our reader and parameter building routines. However, moving to async causes a problem since those implementations on DbCommand are not exposed via the interface.

DbCommand.ExecuteReaderAsync() does not have a matching IDbCommand.ExecuteReaderAsync() definition. Similarly for all the other execute methods.

Is there some design consideration that is preventing these definitions from being added? Or simply an oversight from the carry-over from the old framework code?

**Comment by ajcvickers** [comment]
System.Data and many applications built on System.Data assume that the interfaces can be cast to the base types. This greatly reduces the usefulness of the interfaces since in many cases different implementations than expected with result in exceptions. This means that, even with default interface implementations now available, we still don't plan to evolve these interfaces.
