### ISSUE TITLE
String.GetHashCode() consistently slower on dotnetcore than .Net Framework

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#26779]
Using this PowerShell script on Win10 17713

```powershell
$totalms = 0
1..10 | % { $totalms += (measure-command { foreach($i in 1..10000000) {$Null = "PowerShell6HasSlowerHashCode".GetHashCode()} }).totalmilliseconds }
$totalms/10
```
 Computes the hash for the string 10M times and averages the time over 10 runs.

On .Net 4.7.2 it takes 12455ms
Same machine with PSCore6.1 w/ dotnetcore 2.1.301 17579ms

This is causing a perf regression in PowerShell due to use of GetHashCode() calls.

**Comment by GrabYourPitchforks** [comment]
`new Dictionary<string, ...>()` now has the optimization which optimistically uses the "fast" hash code calculation routine, falling back to the randomized hash code calculation routine only when collisions are encountered. We also improved the performance of Marvin32 in the .NET Core 3.0 timeframe (see https://github.com/dotnet/coreclr/pull/22816).

Additionally, per https://github.com/PowerShell/PowerShell/issues/7112, it looks like the original scenario which precipitated the opening of this issue has since been resolved in PowerShell Core.

Since it looks like there's nothing left to do on the runtime side of things I'm closing the issue for now. Please reopen this issue if needed. Thanks!
