### ISSUE TITLE
Move appropriate parts of Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment into the shared framework

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#26780]
### Rationale

It is often the case, when working with .NET Core that you want to do something based on the current platform/architecture. In many cases, this can include needing to interop with tools published using a particular "runtime identifier".

Today, the RuntimeIdentifier is only exposed through the `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()` API and is not exposed as part of CoreFX. This requires referencing an additional package, and prevents it from being used in certain scenarios (such as evaluation time in MSBuild).

As such, I propose that we expose a mechanism to get the `RID` for the current execution environment at runtime.

### Proposed API
```C#
#nullable enabled
namespace System.Runtime.InteropServices
{
    public static class RuntimeInformation
    {
        // The current OS RID, e.g.: win7-x64, osx.10.11-x64, ubuntu.18.04-arm64, rhel.7-x64
        public static string RuntimeIdentifier { get; }
    }
}
```

The above API will return the value of a new AppContext variable `RUNTIME_IDENTIFIER`. This variable will be passed by the `dotnet.exe` host, and can be passed by any other native host when the runtime is loaded.

DISCUSSION: Should we still maintain a managed fallback code path for when this AppContext variable isn't present? For example if the app was loaded from a different native host that didn't set this variable.

### Additional Notes

This would allow switching on the active `RID` from an MSBuild project/props/targets file, which would allow greater versatility in consuming native tools from a package during build time (or from a user program at runtime).

It may be worth reviewing the other APIs exposed via `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment` and determining which others, if any, should also be exposed: https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs

### Updates

- eerhardt: Add proposal for `OperatingSystem` and `OperatingSystemVersion` so `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment` can be completely removed/deprecated/etc.

- vihofer: Choosing _OS_ over _OperatingSystem_ as we already use _OS_ in `IsOSPlatform`. `OperatingSystemPlatform` is already accessible through `IsOSPlatform(Platform)`. RuntimeArchitecture is already exposed as `ProcessArchitecture`. The `RuntimeVersions` proposal is already covered by [dotnet/coreclr#22664](https://github.com/dotnet/coreclr/pull/22664) and doesn't require an api review. 

- eerhardt: Remove proposal for `OSName` and `OSVersion`, we will drop support for these APIs. Callers can instead call `Ntdll.RtlGetVersionEx` on Windows, or read `/etc/os-release` on Unix.
Change `RuntimeIdentifier` from a property to a method call, since the proposed behavior will invoke a method: `AppContext.GetData()`, which isn't appropriate for a property.

**Comment by eerhardt** [comment]
After discussing with @jkotas and @ericstj, I have modified this API proposal to just include an API for getting the current RID of the machine. I have updated the original issue comment as appropriate.

The proposed `RuntimeInformation.GetRuntimeIdentifier()` method will return a new AppContext variable `CURRENT_RUNTIME_IDENTIFIER`. This variable will be passed by the dotnet.exe host, and can be passed by any other native host when the runtime is loaded.

DISCUSSION: Should we still maintain a managed fallback code path for when this AppContext variable isn't present? For example if the app was loaded from a different native host that didn't set `CURRENT_RUNTIME_IDENTIFIER`.

We decided to drop `OSName` and `OSVersion`. The current API for this information is `RuntimeInformation.OSDescription`. It would be confusing to have all 3 of these APIs, and each returning different information. The only known use-case for `OSName` and `OSVersion` APIs are for diagnostic or telemetry types of situations, which is solved by `RuntimeInformation.OSDescription`.

Note, that the following callsites in `dotnet/sdk` will need to be updated since those APIs will be going away - /cc @nguerrera @dsplaisted. 

https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Layout/toolset-tasks/CurrentPlatform.cs#L159
https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/dotnet/Telemetry/TelemetryCommonProperties.cs#L66
https://github.com/dotnet/sdk/blob/dc3dc1499ed2ce922c6c5fa2ad4a6c8166436049/src/Cli/dotnet/Program.cs#L313

Marking this as `api-ready-for-review` to get the `GetRuntimeIdentifier()` method moved from `PlatformAbstractions.RuntimeEnvironment` to `RuntimeInformation`.

**Comment by jkotas** [comment]
> `CURRENT_RUNTIME_IDENTIFIER`

Nit: Why not just `RUNTIME_IDENTIFIER`? I do not think that the "CURRENT" in the name is necessary.

>  Should we still maintain a managed fallback code path for when this AppContext variable isn't present?

I do not think so. The API should be allowed to return null when the RID is not known.

**Comment by dsplaisted** [comment]
@eerhardt Can you leave the old APIs in for a while (I'd suggest at least a different preview release than we make the SDK change in)?  Otherwise we may have trouble doing the change "atomically" due to how dependencies flow, etc.

**Comment by eerhardt** [comment]
@jkotas - 

> Why not just RUNTIME_IDENTIFIER?

Good point. I've updated the proposal.

@dsplaisted -

> Can you leave the old APIs in for a while

For sure. We have separate issues for adding the new API to `RuntimeInformation` (this issue). And the issue to remove the old PlatformAbstractions library (#3470). The latter can't happen until the new API is in place, and it won't happen at the same time. Separate preview releases would probably make sense, but I'd like to do it as early as possible to get feedback on the takeback here. We _could_ start weaning the SDK off PlatformAbstractions now. There are a few places that use OperatingSystemPlatform and RuntimeArchitecture that could switch to RuntimeInformation now.

Ex:
https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/Microsoft.DotNet.Cli.Utils/ProcessReaper.cs#L40
https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/Microsoft.DotNet.Cli.Utils/RuntimeEnvironmentRidExtensions.cs#L28-L29

**Comment by terrajobst** [comment]
* Looks good
    - We like that we don't duplicate code between the native and the managed implementation
    - However, we should make sure that other hosts can access the logic in the hosting APIs, so it seems they should expose an easy API to compute the current RID and set the `AppContext` value (or make sure they are automatically set)
* We should make it a property
* It shouldn't return a nullable string, rather it should do a sensible fallback (either in the host or the managed side)

```C#
#nullable enabled
namespace System.Runtime.InteropServices
{
    public static class RuntimeInformation
    {
        // The current OS RID, e.g.: win7-x64, osx.10.11-x64, ubuntu.18.04-arm64, rhel.7-x64
        public static string RuntimeIdentifier { get; }
    }
}
```

**Comment by jkotas** [comment]
> It shouldn't return a nullable string, rather it should do a sensible fallback

There is no sensible fallback in number of advanced cases. That's why it was proposed as potentially returning null.

**Comment by jkotas** [comment]
I guess we can make it return `any` RID as the fallback.

**Comment by eerhardt** [comment]
The proposed options for what happens if `AppContext.TryGetSwitch("RUNTIME_IDENTIFIER")` returns `false` were:

* Throw an exception
* Return `any`
* Do a super simple managed fallback:
    * win-{arch}
    * osx-{arch}
    * linux-{arch}
    * ...
    * potentially `any` at the end if all the known `IsOSPlatform` checks return `false`.

> I guess we can make it return any RID as the fallback, but is it really better than null?

The case where it is better than null is that `any` is a valid RID, and if you were passing that into some other API (or were inspecting the RID graph), it would be a treated as a valid RID.

**Comment by jkotas** [comment]
The fallback really means "don't know". If you pass `any` to other APIs that expect actual meaningful RID, they are likely going to crash anyway.

**Comment by eerhardt** [comment]
The issue in the API design meeting regarding this API being defined as:

```C#
public static string? RuntimeIdentifier { get; }
```

Is that it is an exceptional case when the AppContext variable isn't set. When an app is launched by our app host, the `RUNTIME_IDENTIFIER` AppContext variable will be set. If an app is using the new [preferred native Hosting APIs](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#hosting-apis), it will be set. The only time `RUNTIME_IDENTIFIER` won't be set is if someone is using the `CoreClrHost.h` or `mscoree.h` native hosting, which shouldn't be a lot of places. Forcing callers of this method to have to handle `null` when it is an exceptional situation, and there is a possible non-null fallback, wasn't desired.

> If you pass any to other APIs that expect actual meaningful RID, they are likely going to crash anyway.

I would think that depends on the API. Since `any` is a valid RID, I don't see why it would crash. If it can't find `any` in its graph, it would treat it the same as any invalid RID it couldn't find.

However, the other API is probably defined as 
```
#nullable enbale
void MyRidApi(string rid)
```

And we couldn't say `MyRidApi(RuntimeInformation.RuntimeIdentifier)`, without the compiler complaining for everyone.

____


The [current RuntimeEnvironment API](https://github.com/dotnet/runtime/blob/master/src/installer/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L106) returns `unknown-{arch}` when it can't figure it out. Perhaps keeping that same behavior is the best approach for this new API.

**Comment by jkotas** [comment]
> The only time RUNTIME_IDENTIFIER won't be set is if someone is using the CoreClrHost.h or mscoree.h native hosting

That's not the only case. The broader .NET ecosystem includes e.g. Unity that has its own runtime and number of Unity target platforms do not even have well-defined RIDs by design.

I am fine with this being implemented as `GetData("RUNTIME_IDENTIFIER") ?? "any"``.

**Comment by terrajobst** [comment]
I think the primary conclusion is that we'd consider such hosts as having a bug. Frankly, I'd even go so far and say we should crash on startup when a RID isn't specified. Or said differently, for this API to be reliable, the host must set it meaningfully. That's why we should force the change there, rather than asking everyone to guard for `null`.

**Comment by am11** [comment]
> We like that we don't duplicate code between the native and the managed implementation

If by native we also consider the control flow stemming from https://github.com/dotnet/runtime/blob/3d8073daba7a84fe2692816763ada490b6353359/src/installer/corehost/cli/hostmisc/pal.h#L67 as a problem, then +1. For operating systems, that are not officially supported, such as BSD lane or even other SystemV likes such as Illumous, these kind of hardcoded constraint unnecessary puts another barrier on already complicated system for porting work, which is suffering for a long time due to:

* over-engineered RID barriers everywhere: starting from post- `CoreCLR native compilation` to the package delivery via NuGet to build publish dotnet apps.
* heavy (mandatory?) dependency on CI: so if AzDevOps (since it has replaced its more capable counterpart Jenkins in 2019) does not support the operating system (i.e. anything beyond Windows, macOS, Linux), we have no dice to get `dotnet(1)` running and will have our fingers crossed forever since dotnet/source-build also relies on AzDevOps and is locked down to those three systems.

By the time we get any version working on other OS, it is already too late in lifetime of that version, due to breaking changes in infra for the next version.

IMO, keep RID story super simple; restrictions wise and otherwise so it can scale better in what it was originally designed to do. This is mitigate some pain points in porting work for vast range of targets.

**Comment by jkotas** [comment]
@terrajobst As @am11 said, the RIDs are ever-engineered, do not scale and major barrier for entry for non-Microsoft driven ports. It is why I believe that it is important that this API is allowed to return "don't know answer". If we dislike `null`, it is ok for this `don't know` answer to be "any", "unknown" or even  empty string.

**Comment by terrajobst** [comment]
> @terrajobst As @am11 said, the RIDs are ever-engineered, do not scale and major barrier for entry for non-Microsoft driven ports. It is why I believe that it is important that this API is allowed to return "don't know answer". If we dislike `null`, it is ok for this `don't know` answer to be "any", "unknown" or even empty string.

The host doesn't need to validate the string against the graph; it just needs to return a string that is unique and can be used to identity the runtime. However, for libraries with native dependencies it's important the "sensible" answers are returned. As you said, returning "any" is unlikely to be a good answer.

**Comment by jkotas** [comment]
> However, for libraries with native dependencies it's important that "sensible" answers are returned

I would like to see programs and libraries that try to do their own native library resolution based on RIDs to assume that the native library is supplied by other means for unknown RID. Nobody really needs to their own native library resolution in .NET Core, this is very niche case - often just a left over from .NET Framework. I know that there are a few libraries that do that for "reasons", and I would not feel bad that the potential null is in their face.

I would like to avoid the situation we have with `Assembly.Location` today where every other call to this API does not handle the case of empty path correctly that results in a lot of breaks with single-file publishing.

**Comment by tmds** [comment]
@eerhardt the value returned for `RuntimeIdentifier` depends on the distributions known to .NET Core?
For example, if I have installed Microsoft `linux-x64` .NET Core build on Ubuntu 18.04, this returns `ubuntu.18.04-x64`?
If I install that same version on Ubuntu 20.04, this will return `linux-x64` (because this rid is not known)?

From a use-case perspective, it may be interesting to be able to query whether the platform is compatible with an rid.

**Comment by jkotas** [comment]
This API is not doing any filtering against any known lists. It is going to return `ubuntu.20.04` in your example.

**Comment by tmds** [comment]
@jkotas Ah, that's good! The processing is limited to some normalization of `/etc/os-release/` (like stripping the minor for rhel7).

**Comment by tmds** [comment]
fwiw, since this returns an rid for the OS, `OSIdentifier` would be a more indicative name.

**Comment by eerhardt** [comment]
> From a use-case perspective, it may be interesting to be able to query whether the platform is compatible with an rid.

Today, you can use the framework's `.deps.json` file, or the app's `.deps.json` file if it is a self-contained app (the RID graph was added for self-contained apps with https://github.com/dotnet/sdk/issues/3361), to get the RID graph. `.deps.json` files can be loaded with the [`DependencyModel`](https://www.nuget.org/packages/Microsoft.Extensions.DependencyModel) library. See the [`RuntimeGraph`](https://github.com/dotnet/runtime/blob/925837e9be56a4b04ad023882634be44ed10c0f8/src/installer/managed/Microsoft.Extensions.DependencyModel/DependencyContext.cs#L64) property on DependencyContext. You can use that to see what RID is compatible with what for the current platform.

If you need a full RID graph (ex. `win` information on `unix`), we don't have an API to get this information. You would have to ship and update the `runtime.json` file yourself.

> The processing is limited to some normalization of /etc/os-release/ (like stripping the minor for rhel7).

Yes, it still does that normalization for rhel and alpine.

> since this returns an rid for the OS, OSIdentifier would be a more indicative name.

I believe that would be confusing since everywhere else in the system (CLI options, SDK properties, Documentation, etc) calls this RID or RuntimeIdentifier.
