### ISSUE TITLE
API Proposal: Add PipeWriter accessor for the number of currently-buffered bytes  

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#26818]
# The Problem

Applications use two major APIs when writing to a PipeWriter:

* `Advance()` "commits" bytes written to a previously-obtained Span or Memory, and
* `FlushAsync()` makes all committed bytes visible to the reader.

If an application needs to write a particularly large value (say a very large string), care must be taken not to buffer too much; doing so needless inflates memory use. In simple scenarios, an application can track how much it has already committed, and intermittently call `FlushAsync()` to provide a chance to the reader to read data, thereby clearing out some buffers internally held by the pipe.

However, in some applications knowing how much has already been committed to the pipe isn't trivial: writing a single chunk may involve several components, which must currently coordinate between each other to make themselves aware of how much they've committed.

For a concrete example, when Npgsql (PostgreSQL database driver for .NET) sends a query to the database for execution, it sends multiple wire protocol messages (ideally packed in a single packet and flushed once, if they fit). One of these messages contains the list of parameters to the command, and one of these parameters can be an array of strings. The "type handler" responsible for writing the binary representation of a PostgreSQL array delegates to the string type handler for each of its values. Flushing may happen at any point while writing the array; it could be an array of one single huge string (so the flush would need to happen inside the string handler), or an array of many small strings (so the flush would need to happen inside the array handler). All these components would need to cooperate, passing a "currently buffered bytes" value back and forth.

# Proposed API

The idea would be to move the responsibility for tracking the number of committed/buffered bytes into PipeWriter, and expose it via a property:

```c#
class PipeWriter {
    public int BytesWritten { get; }
}
```

The number of bytes is already present in the pipe (`_currentBytesWritten`), so it's mostly a matter of exposing it to users. It's expected that any other implementation of PipeWriter will similarly track buffered bytes.

Naming alternatives could be `BytesBuffered` or `BytesPending` or `BytesCommitted` (since `BytesWritten` may be taken to mean total bytes written in the history of the pipe).

Originally raised in dotnet/runtime#26747.

/cc @davidfowl @mgravell @stephentoub

**Comment by cocowalla** [comment]
Another concrete example of where this would be nice: length-prefixed protocols.

Let's say I serialize directly to a `PipeWriter` (since it implements `IBufferWriter<T>` - if I don't have full control over the serialization code, I have no way of knowing how many bytes were written.

I'm working around this by serializing to a temporary buffer first, writing the length to the `PipeWriter`, *then* writing out the temp buffer to the `PipeWriter` - it's just more complex and messy than it needs to be.

If `PipeWriter`/`IBufferWriter` exposed how many bytes had been written, I could grab `GetSpan(4)` and `Advance()`, serialize to the `PipeWriter`, then write the length to the `Span` before finally calling `FlushAsync()` - more simpler!

**Comment by davidfowl** [comment]
That’s not allowed. Once you call Advance the buffer you previously retrieved is invalidated

**Comment by cocowalla** [comment]
@davidfowl hmm, it's working for me, but perhaps only because of an implementation detail in `StreamPipeWriter` then? So it's clear in my mind, are you saying that any buffer obtained through GetSpan/GetMemory should not be written or read after Advance is called?

If so, then I guess writing to a temporary buffer first, so the length can be obtained, is the way to do this.

**Comment by mgravell** [comment]
To be explicit: once you've advanced the buffer:, what happens is *undefined*. There's no reason a reader can't take that data, even without you calling flush. This means that if you keep a hold of that buffer to cheat:

1. your change may or may not make it to the other end
2. you may or may not be over-writing what is now someone else's buffer

Neither option is good, so don't do that.

The third option, rather than writing to a temporary buffer, is to compute the length *without* writing first, but I appreciate that this is not always possible.

At various points a few options have been discussed here - including the ability to stitch a pre-formed buffer into a pipe without an extra copy back, but today: those things don't exist.

**Comment by cocowalla** [comment]
@mgravell thanks for confirmation!

I had thought no data could be read until it was explicitly flushed by the writer, but the contract is clear now (expect that the writer implementation could *theoretically* flush data at any time), and I understand that it only works in my case because of an implementation detail.

I confess it's a bit annoying not to expect full control over flushing, but I can see it makes sense and I'll get over it :stuck_out_tongue_winking_eye:

It's not possible in my cases (different processes using both MessagePack and JSON serialisation) to calculate the length beforehand, so I'll stick with a temporary buffer.

Thanks to @davidfowl and @mgravell both for quickly pointing this out and potentially saving me from a world of debugging pain in the future, you guys are great! :sweat_smile:

**Comment by mgravell** [comment]
That by itself doesn't make it technically impossible - just perhaps not implemented currently. I recently added precisely this feature into protobuf-net v3, for example. And even without any changes, it is often possible to use a "nul writer" - for example (in the case of JSON) a custom TextWriter subclass that only measures and counts things, but doesn't actually write encode anything yet.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/48913
