### ISSUE TITLE
Getting rid of ImmutableArray<T>.IsDefault ?

### ISSUE THREAD

**Issue by lowercase93** [dotnet/runtime#26829]
Hi guys, 

First of all, I am really enjoying your immutable collections library, well done. It is very useful.
I am not sure if there was something like this issue. I could not find one. So, if it duplicates, then feel free to close this one, but could you please give a link to the original one? Thanks.

So here is the deal.
We all used to work with value types as with such that always valid not matter how they initialized. 
I'm sure pretty much of people used to call `new TimeSpan()` and be sure, that the value is equivalent to zero, or say use `default (Vector3d)`  as a default value for `origin` parameter in `Polygon.Transform()` method. Its invariants will not be violated, and the X, Y and Z are going to be 0, which absolutely correct and the instance remains consistent.

And I was really disappointed that I have to check `ImmutableArray<T>.IsDefault` every time my method/property accepts an instance from outside. Otherwise my code blows up with `NullReferenceException`. Because the private array field of ImmutableArray<T> is not initialized. I expected `ImmutableArray<T>` to be valid in the state of default constructor. But it is not. And I have to put such checks all over my code because I can't be sure what a caller will be sticking into my method/property.
It is really annoying. In most cases I don't need to know that array is initialized by default or not. Sometimes I need to check `Length`. But not always. How much checking for `IsDefault` differs from check `Length == 0`? If you say there is `IsDefaultOrEmpty`, then i would as ask you, why should I? For me it is very common just to do some mapping/filtering on a collection, no matter how many items it contains. I really don't care if instance is initialized with default constructor on a factory method. I just wan to be sure, that if I have a structure passed to my method I'm free to access its properties/methods.
If you say, that this is similar for checking a collection for null, then I'll ask you again, why should I? It is a value type and if I want it to be able non-initialized I would make it Nullabel<ImmutableArray<T>>;
Is it performance after all? Does this check `if(this.array == null)` makes even more impact on performance than `if(instance.IsDefault)`?

Maybe I'm wrong, please tell me where. Because I really don't see any reason for IsDefault to exist.

**Comment by jakerdy** [comment]
You guys deffenetly should remove throws from ImmutableArray, because it implements commonly used interfaces, which shouldn't kill your programm just because.

Consider this example:
```cs
private void UpdateLabels(IEnumerable e)
{
    //...
    if(e is ICollection c)
    {
        m_label.Text = $"Count: {c.Count}"; //It will throw sometime InvalidOperationException, but should it realy?.
    }
    //...
}
```

God damn please DO NOT IMPLEMENT LOGICS VIA EXCEPTIONS in future, it breaks .net convenience fundamentally.

**Comment by Clockwork-Muse** [comment]
@jakerdy - If you're getting an `InvalidOperationException`, it means that the `ImmutableArray` getting passed around hasn't been initialized, which is unsafe for general use.  

That is, _your_ program (or possibly a library it uses) has a bug, and you should figure out what part of your program is creating/returning the uninitialized array (you probably want to be returning `ImmutableArray.Empty` instead).

**Comment by jakerdy** [comment]
@Clockwork-Muse, thanks you for your attention to this problem.
I don't think thats it's a bug. 
Check this out:
![image](https://user-images.githubusercontent.com/66637406/131240654-8b76f230-7f08-4684-812f-e7322c260e66.png)
This thing called Inspector, it is part of our custom IDE project. It could inspect any CLR object, and show it's contents in nice and convenient way.
To make data "actual", we need pull data from object, lets say, 5-10 times per second. And if some property constnatly throws exceptions it costs us about 10-30ms, just for one throw-catch.
IDE UI rendered at 60fps, which means 1 frame == 16.(6) ms. If we always will get exceptions on every corner, performance wouldn't be good. Of course we handle it most of the time, but some times, pretty bad things happens, like `ICollections` which throws when `get Count` was called. At this point you start thinking, should all calls to BCL should be wrapped into try{}catch{}? Well, yes, but why? Is not null object of ICollection should ever throw when we asking it about it's count?
Ok, if you want to throw, if object is invalid, give us some mecanisms to check if it actually valid, without try-catch or casting it to some specific generic type instance. Because catching is just slow most of the times (_all we love snappy ui, arn't we?_), and casting to specific type isn't actually possible.
I say all of this because i tired of all of this exceptions so much, mosltly because most design choices which guys from MS made in their libs all just throws. No matter what, rule of thumb, just thorw, it is not your job to handle even some obvious situations like this.
And the most bad thing that you just couldn't prevent it if somehow, ImmutableArray<>.IsDefault == true. There is not `IImmutableArray` iface with IsDefault property, nor `static ImmutableArray.IsDefault(...)` nor `IGonnaThrowIfDefault` , you just must try-catch if ImmutableArray got boxed and went to you throug interface.

To handle this specific situation we need to write code like this to avoid throws and avoid unnecessary lattency in ui:
```cs
public override void SyncValue()
{
  var cur_value = m_io.GetValue(PropertyPath);
  var enumerable = (IEnumerable)cur_value.Result;
  //...
  var t = enumerable?.GetType(); 
  if (t?.Name == "ImmutableArray`1")
  {
    if ((bool)t.GetProperty("IsDefault").GetValue(enumerable))
    {
      enumerable = null;
    }
  }
  //...
  UpdateLabel(enumerable);
  UpdateListContents(enumerable);
}
```
To get this:
![image](https://user-images.githubusercontent.com/66637406/131241058-7a8aa8fc-fc60-4ddf-94dc-eacf2cec6b25.png)

Well, maybe there is some cases when "default" behaviour just worse then throwing some exceptions, but deffenetly not in ImmutableArrays, imho.

Anyway, there always some checks in every single method and property inside ImmutableArray. But why souhld it throws instead of just pretending like it is empty, scince it value type, i just dot got it, as an user of this library or as engeneer of other libraries.

**Comment by jakerdy** [comment]
Excuse me for the rude tone in the past message. It's just that we often struggle with exceptions from the BCL rather than with our own bugs. And this is i think probably pretty good example why exceptions should be thrown in "exceptional" situations rather then in "evryday logics".

**Comment by En3Tho** [comment]
@jakerdy I both agree and disagree with you here.

I totally more than 100% agree that Unchecked exceptions are evil and I personally so goddamn tired of seeing try-catch everywhere with blind exceptions type checks. There is a good blog about Midori from Joe Duffy and he specifically blogged about exceptions. I agree with him: if a function can throw then just return a goddamn result type or even better - make compiler aware of potential errors and let it optimize return type accordingly.

In case of Immutable Array being empty there - honestly it's your bug. The point of Immutable Array is to mimic usual array while being struct wrapper. This actually means you have a null somewhere in your program. 

As for workaround I  don't think having special checks like this for every Immutable collection is a good choice. What about Immutable HashSet for example? But of you have to do it no matter what then I believe simply special casing ImmutableArray and friends is better than to use reflection. What I mean is to check if type is ImmutableArray after you've checked it is an ICollection. And I think having little generic there in UpdateLabels could help with that.

**Comment by Clockwork-Muse** [comment]
> And the most bad thing that you just couldn't prevent it if somehow

Your problem isn't limited to `ImmutableArray`.  Multiple types, in and out of the BCL, have a concept of "invalid" (and not all of them express it the same way).  If you're building an inspector like this, you're either going to have to accept the penalty from catching the resulting exceptions, or you're going to have to handle the special cases (and your code needs to be able to discover them, since there's multiple ways this occurs).  You already must be doing some of this - some collection types are unsafe or otherwise invalid to enumerate more than once.

Or you could just crash, I suppose, but your customers probably won't enjoy that.

**Comment by jakerdy** [comment]
@En3Tho. I agree that cheking stuff via reflection is a bad thing in general.

Your example about ImmutableHashSet isn't sutis this issue because it is a class, but ImmutableArray is a struct, which implemets 
common interfaces. And as far as i know it is the only ImmutableXXX who is struct and not a class. 

With classes evrything completly fine, because they could become null's (_and if something is null, it doesn't by default means that it is a bug, it just one of the possible states of an object_). But ImmutableArray is a special thing. But there is no way to tell if it is ok, or not ok.

It would be great, if object which could become invalid and throws, could be idetified somehow. Let's say, if we got interface like:
```cs
public interface IInvalid
{
  bool IsValid {get;}
}
```
We could check if object is valid/initialized/ready-to-work. And without any doubt we could at least touch it's "readonly-ish" api's, like Count/Capacity etc...

Right now, there is no way to handle ImmutableArray (_and probably many other types_) without try-catch. 
Or i miss something?

@Clockwork-Muse Yep, there is lots of try-catch stuff, but i trying to minimize throws whenever it is possible. Some aditional checks (_made in a good way, not via reflection_), way faster then catching.

**Comment by jakerdy** [comment]
But still. Is there any good way to check if ImmutableArray<T>.IsDefault == true, if it is under ICollection interface without reflection?
And if there no way to check it, is there any possibility in future that we could see some good api for that?

**Comment by En3Tho** [comment]
Why can't you use ICollection<T> interface? Is there something blocking you from doing it?

**Comment by jakerdy** [comment]
@En3Tho, what exactly do you mean by using ICollection of T?

You couldn't cast things to not completely constructed types.
I am specifically talking about this situation:
```cs
//You don't know exact type of T in ImmutableArray<T>, you just got IEnumerable
private void SyncToValue(IEnumerable collection)
{
    //You couldn't do this in C#
    if (collection is ICollection<T>) { /**/ }
    //You couldn't do this, because ImmutableArray hasnt its related public Interface for some reason
    if (collection is IImmutableArray { IsDefault:true })
    {
        collection = null;
    }
    
    //There only reflection based methods to check this
    if (collection.GetType().GetGenericTypeDefinition() == typeof(ImmutableArray<>))
    {
        //Some logics here
    }
    
    // or calls via DLR, but it is slow, and both are bad
    dynamic arr = collection;
    if (arr.IsDefault) collection = null;
    //There currently no way to tell if ImmutableArray IsDefault in non generic context
}
```

If ImmutableArray is a "special thing" and implemented as ValueType, why does it tries to be like class (when it hidden behind interface), instead of be just like a value type? I don't see any reasons why it should throws in all interface implementations, instead of just returning some obvious values, which coulnd't break things. 
When i working with ImmutableArray using it type directly, i know what i am doing, and i will check if it is valid. But when i working with interfaces, i waiting that implementations are good enough to handle some "internal issues", and gave me some reasonable values. But at current implemenration of ImmutableArray, there is no consistency, event if i call Equals(null), it always be false
At the end of the day, what could you do wrong with collection of 0 elements?

I still think that IsDefault is an issue, and definitely should be fixed.

Consider this solution. There is `internal interface IImmutableArray`, what if it will be rewritten like this:
```cs
public interface IImmutableArray
{
  internal Array? Array { get; } 
  public bool IsDefault { get; }
}
```
It wouldn't break any existing apis, but will add pretty convenient functionality for checking if it valid without reflection.

**Comment by airbreather** [comment]
@jakerdy, your request is very unusual.  It sounds to me like you are asking for the ability **not** to have to rely on using reflection to solve a particular problem, in a program that fundamentally **requires** you to use reflection for its core functionality?

I don't know exactly what's going on in your application that would lead you to ask for that, but this might help... it should only tend to have significant `ImmutableArray<T>`-related overhead the first time that you encounter an instance for a given value of `T`:
```csharp
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;

IEnumerable?[] enumerables =
{
    null,
    Enumerable.Empty<object>(),
    default(ImmutableArray<string>),
    ImmutableArray<string>.Empty,
    ImmutableArray.Create("foo", "bar", "baz"),
    new[] { 123, 456 },
    ImmutableArray.Create(1.1, 2.2, 3.3),
};
foreach (var coll in enumerables)
{
    Console.Write($"coll type is '{coll?.GetType()}' and is treated as ");
    if (ImmutableArrayHandler.Normalize(coll) is not IEnumerable normalized)
    {
        Console.WriteLine("a null collection");
        continue;
    }

    Console.WriteLine("a collection that contains the following element(s):");
    foreach (object o in normalized)
    {
        Console.WriteLine($"    {o}");
    }
}

internal static class ImmutableArrayHandler
{
    private static readonly Dictionary<Type, Func<IEnumerable, IEnumerable?>> ExpressionCache = new();

    public static IEnumerable? Normalize(IEnumerable? coll)
    {
        if (coll is null)
        {
            return null;
        }

        var typ = coll.GetType();
        if (!ExpressionCache.TryGetValue(typ, out var callback))
        {
            callback = ExpressionCache[typ] = CreateExpressionForCache(typ);
        }

        return callback(coll);
    }

    private static Func<IEnumerable, IEnumerable?> CreateExpressionForCache(Type typ)
    {
        if (!(typ.IsConstructedGenericType && typ.GetGenericTypeDefinition() == typeof(ImmutableArray<>)))
        {
            return x => x;
        }

        var elementTyp = typ.GetGenericArguments()[0];
        var expParam = Expression.Parameter(typeof(IEnumerable));
        var exp = Expression.Lambda<Func<IEnumerable, IEnumerable?>>(
            Expression.Call(
                typeof(ImmutableArrayHandler).GetMethod(nameof(AsArray), BindingFlags.Static | BindingFlags.NonPublic)!.MakeGenericMethod(elementTyp),
                Expression.Convert(expParam, typ)),
            expParam);
        return exp.Compile();
    }

    private static ICollection? AsArray<T>(ImmutableArray<T> imm)
    {
        return Unsafe.As<ImmutableArray<T>, T[]?>(ref imm);
    }
}
```
That program writes (for me):
```
coll type is '' and is treated as a null collection
coll type is 'System.Linq.EmptyPartition`1[System.Object]' and is treated as a collection that contains the following element(s):
coll type is 'System.Collections.Immutable.ImmutableArray`1[System.String]' and is treated as a null collection
coll type is 'System.Collections.Immutable.ImmutableArray`1[System.String]' and is treated as a collection that contains the following element(s):
coll type is 'System.Collections.Immutable.ImmutableArray`1[System.String]' and is treated as a collection that contains the following element(s):
    foo
    bar
    baz
coll type is 'System.Int32[]' and is treated as a collection that contains the following element(s):
    123
    456
coll type is 'System.Collections.Immutable.ImmutableArray`1[System.Double]' and is treated as a collection that contains the following element(s):
    1.1
    2.2
    3.3
```

**Comment by En3Tho** [comment]
@jakerdy My question basically was: why not use generic IEnumerable/ICollection instead of non generic ones? Is non generic one a some kind of requirement?

**Comment by jakerdy** [comment]
Do you guys really do not understand whats wrong with logic based on exceptions in ImmutableArray?

Yes, inspector in my program uses reflection extensively, yes of course i catch exceptions if something goes wrong at the places where it make sense. But no, i won't use them to solve problems which could be (and i beleve) should be solved in a different way, by designing libraries in a more intelligent way.

Problem not in my code, or in some algorithms which makes it possible to default ImmutableArray occurs some times.
The problem is in api of ImmutableArray, which breaks things because of exceptions, and in that inconvenience which this single type introduces by throwing InvalidOperationExceptions, when it actually pretty valid and able to just return 0 instead of throwing.

This issue wouldn't even exists if there is no problems with IsDefault, and all problems which it makes. But there is problems because it throws whenever ImmutableArray hidden behind interface. And even "better", we has no good ways to check if it valid when it is under some interface.

All those workarounds, which you suggesting just doesn't really works, because there is way more simple and more obvious solutions which doesn't breaks currently existing api's, and doesn't affects performance. But you still talking to me that i doing things in a wrong weird way, and things which i am talking about is unusual.

Isn't `System.Collections` a general purpose library which should serves most of use cases, and not some specific ones? I think it is. Also i think that ImmutableArray implementation currently broken, because interfaces which looks safe, implemented in a pretty unsafe way:
- `Count {get}` thorws exception
- Equals doesn't works when i pass null to 'Uninitialized' immutabble array casted to IEnumerable or any other iface ImArr implements.
- IImmutableArray iface implemented as internal, has no property IsDefault, but all other immutable collection interfaces implemented as public ifaces, and provides some useful information

In Russia we say "Hammer in nails with microscope". This situation illustrates this phrase pretty good. Yes i could use Reflection to find out if ImmutableArray<T>.IsDefault == true. Also i could try-catch when calling ICollection.Count. But it isn't great experience. 

I would prefer more consistent and convenient API in this case, for example public non generic interface for ImmutableArray with property IsDefault, is it so hard to implement? Or is it breaks something? Or is it mess up some existing APIs?
Of course it would be better if explicit implementations of collection related interfaces wouldn't throws at all when we accessing readonly api, but i already understand that it will never happens.

Comming back to my case. Objects inspected in inspector could get into it from any place, not even from my code, but from any lib from nuget, or other place, because inspector is part of god damn interactive IDE which we written for sandboxing with CLR based libs and stuff. There is some property editors which could display internal state of objects to you. Editor for IEnumerables could inspect some, well... IEnumerables. And we recently encounter one nasty IEnumerable which called ImmutableArray<T>. Its instances went from some external lib written by someone else. And we wonder whats wrong with this lil boy, why is it throws so often. And how could we handle it having instance of it under IEnumerable inteface,,, Continuation of this history you may read in this issue.

I hope you could look onto this problem under some different angle, and somehow get a glimpse of the problem that there really are. 

Anyway, thanks everybody for your participation, this is my last message, wouldn't interrupt you anymore.

**Comment by jakerdy** [comment]
> @jakerdy My question basically was: why not use generic IEnumerable/ICollection instead of non generic ones? Is non generic one a some kind of requirement?

Yes it is. Please read my previous message again.

**Comment by Clockwork-Muse** [comment]
@En3Tho - The underlying problem is that you need to cast to `ImmutableArray<whatever>` in order to be able to call `IsDefault()` (or check it via reflection, as in the sample).  Accessing it as one of the standard collection/enumerable interfaces is what's actually calling the problem.

@jakerdy - Regardless of whether `ImmutableArray` ends up being changed, the underlying issue your code has is that even objects returned from constructors aren't guaranteed to be in a "domain valid" state (and definitely aren't guaranteed to stay that way).  In the general case there are other enumerables that may throw (potentially rarer) exceptions - anything connecting to a database, for example.  `ImmutableArray` is just one (easy to find) instance of the issue, not the sole problem.

That said, I'm of the same mind as @airbreather - caching types and expressions on debug start could have (possibly significant) benefits.

**Comment by eiriktsarpalis** [comment]
The current `ImmutableArray<T>.IsDefault` design is intentional. It's a trade-off for performance and is also meant to represent `null` arrays. As such, incorporating a check for your `ImmutableArray<T>` arguments should be considered equivalent to checking that your `T[]` argument is null. Admittedly the compiler does check for the latter case if you're using nullability annotations, so perhaps there might be an opportunity for creating an `ImmutableArray<T>` analyzer here.

That being said, `IsDefault` is not something we will be removing.
