### ISSUE TITLE
Nanosecond time

### ISSUE THREAD

**Issue by shravan2x** [dotnet/runtime#27191]
I found myself writing a software PWM recently, for which high precision time is required. But there doesn't seem to be any reliable method to get system time in nanoseconds in .NET Core. The only available solution use system ticks, but more than one highly ranked google result on this doesn't work correctly.

Could an API be added to get nanotime (preferably not using a struct like DateTime to improve performance)?

**Comment by mikhail-barg** [comment]
I'd like to add another reason for such an API to exist: it's working with multimedia and/or VoIP stuff. For example when playing voice over network, you need to provide audio packets in really proper intervals, or you get tearing.

So for windows the proper way to do this is to use [Multimedia Timers](https://docs.microsoft.com/en-us/windows/win32/multimedia/multimedia-timers). 

But what to do for Linux? We will have to find while porting our app to dotnetcore and Linux, but It surely would be great to have an unified API.

**Comment by tannergooding** [comment]
@mikhail-barg, could you please elaborate?

Most modern applications (especially games, etc) utilize the underlying `monotonic` hardware timers for the system. This is `QueryPerformanceFrequency` and `QueryPerformanceCounter` on Windows, `clock_gettime` on Linux, and `mach_absolute_time` on macOS (and typically have resolution up to 1ns). The Multimedia Timers, to my knowledge, are considered legacy and only have up to 1ms resolution.

.NET exposes these values directly via the static `Stopwatch.Frequency` and `Stopwatch.GetTimestamp` methods (and as of the current .NET Core iterations, only supports `Stopwatch.IsHighResolution` being `true`.

`Stopwatch.Frequency` reports the number of "monotonic ticks" per second and `Stopwatch.GetTimestamp` reports the number of "monotonic ticks" that have elapsed since some point (generally computer boot). Using these two methods you can determine the number of seconds elapsed via:
```cs
long startTicks = Stopwatch.GetTimestamp();
// ...
long endTicks = Stopwatch.GetTimestamp();

long deltaTicks = end - start;
double elapsedSeconds = deltaTicks / (double)Stopwatch.Frequency;
```

The `Stopwatch` instance methods take care of normalizing the system ticks into `DateTime`/`TimeSpan` ticks, which are 1 tick per 100ns (which basically just requires another step or two on top of the above: https://source.dot.net/#System.Private.CoreLib/Stopwatch.cs,d42cb3f35f8b35dc).

**Comment by mikhail-barg** [comment]
@tannergooding 

> The Multimedia Timers, to my knowledge, are considered legacy and only have up to 1ms resolution.

As far as I understand, it's not that Multimedia Timers are deprecated. More like they have significant cost in terms of CPU usage and they were frequently abused for other needs besides media processing because of their high precision. See for example [this](https://stackoverflow.com/a/29183085). But up until now we found no way to get around using those for media processing.

> .NET exposes these values directly via the static Stopwatch.Frequency and Stopwatch.GetTimestamp methods

That's really nice that `Stopwatch` could be used to **measure** time intervals, but the real need I'm talking about is to have a callback called at very precise intervals. And it's not clear how to create a timer based on `Stopwatch` that would have such a guarantee. See for example [this attempt](https://stackoverflow.com/a/41697139). 

> the current .NET Core iterations, only supports Stopwatch.IsHighResolution being true

That's nice to know, thanks.

**Comment by tmds** [comment]
@mikhail-barg 

I wonder how you deal with GC pauses?

The hardware audio device has a buffer of a couple of ms which you need to keep filled. You don't need nanosecond precision to do this.
You do need a good timer (like `StopWatch`) to calculate clockdrift between sender and receiver.

**Comment by benaadams** [comment]
> I wonder how you deal with GC pauses?

Don't allocate when you are doing latency sensitive operations 😉  If you don't allocate you won't pause.

**Comment by tmds** [comment]
And when your app performs latency sensitive operations all the time, that is: never allocate.

**Comment by tannergooding** [comment]
> the real need I'm talking about is to have a callback called at very precise intervals

@mikhail-barg, The point I was trying to make is that the Multimedia timers aren't very precise. That is, they only have accuracy up to 1 millisecond and while which might be suitable for some purposes, it won't be for all (in fact, called out above, people are asking for nanosecond resolutions, which is only possible via the mechanisms we already expose).

QueryPerformanceFrequency/Counter on the other hand are considered "high resolution" and have tick count that is less than 1 microsecond. https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps goes into some of the differences between the various timing APIs.

> That's really nice that Stopwatch could be used to measure time intervals

The underlying methods used by Stopwatch are frequently used for dispatching events at specific intervals. You just have to track the delta between each "frame" and fire when that delta accumulates to be the desired interval.
Your typical UI based application (or long running service) has some kind of loop keeping the executable alive. This loop is typically checking and dispatching events so that the main application stays alive. It is also an ideal place to track the accumulated delta and to fire off events needed at specific intervals (this is in fact how many of the other timers work under the covers).

**Comment by mikhail-barg** [comment]
@tmds 
> The hardware audio device has a buffer of a couple of ms which you need to keep filled. You don't need nanosecond precision to do this.

While this is true for hardware audio, it's not true for other scenarios, like VoIP where you need to send media via network.

@tannergooding 
> The underlying methods used by Stopwatch are frequently used for dispatching events at specific intervals. You just have to track the delta between each "frame" and fire when that delta accumulates to be the desired interval.
> Your typical UI based application (or long running service) has some kind of loop keeping the executable alive. This loop is typically checking and dispatching events so that the main application stays alive. It is also an ideal place to track the accumulated delta and to fire off events needed at specific intervals

The thing here is that while it's possible to write a tight loop in a thread, it still would be affected by the thread scheduler running undercover. So you would be unable to assure precise timing for events.

Let's imagine you have a tight loop like this (some ugly pseudo-code):
```
long currentTimestamp = SuperHiresTimeSource.GetNs();
long nextTimeStamp = currentTimestamp + 20000; //20ms in future
while (currentTimestamp < nextTimeStamp)
{
   currentTimestamp = SuperHiresTimeSource.GetNs();
}
```

So, imagine that `currentTimestamp` at start is 0,  `nextTimeStamp` is 20000.
And then at some moment of running a loop you get `currentTimestamp == 19999`.

So, what would be a next value set to `currentTimestamp` in next loop iteration?
Like what if thread re-scheduling would happen in between?  Windows thread scheduler has a 16ms time slice size, so you have a real possibility of getting something like 35999, and this is really not precise at all.

Multimedia timers on the other hand do assure this precise timings.

> The point I was trying to make is that the Multimedia timers aren't very precise. That is, they only have accuracy up to 1 millisecond and while which might be suitable for some purposes, it won't be for all (in fact, called out above, people are asking for nanosecond resolutions, which is only possible via the mechanisms we already expose).

While this is certainly true, I still fail to understand how to use the Stopwatch mechanisms to issue events at precise intervals, given that the looping code would be affected by thread scheduler.

**Comment by tmds** [comment]
> While this is true for hardware audio, it's not true for other scenarios, like VoIP where you need to send media via network.

My experience tells me different. I've built low latency RTP-based voice-and video over IP systems for 5+ years.

**Comment by tannergooding** [comment]
> Like what if thread re-scheduling would happen in between? Windows thread scheduler has a 16ms time slice size, so you have a real possibility of getting something like 35999, and this is really not precise at all.

I don't believe this is a concern in real world/modern applications. Games can run just fine at 144+ frames per second all while dealing with disk IO, networking, graphics rendering, audio buffering, etc (and still fully saturating a system).
Modern step timers may also take things like scheduling concerns into consideration and may trigger an event early if the elapsed time is "close enough". That is, in your case above  if you have `currentTimestamp == 19999` and it should trigger at `20000`, a smart step timer may trigger it anyways, because you will clearly pass over the target timestamp by the next time it triggers and the less than a millisecond difference won't matter in practice. A common example of this is when dealing with vsync and rendering, where the target framerate might be 60 fps but the actual framerate is 59.94 NTSC.

> Multimedia timers on the other hand do assure this precise timings.

AFAIK, the multimedia timers do not pre-empt the Windows scheduling service, instead it just creates and schedules a higher priority thread.

**Comment by mikhail-barg** [comment]
Well I'm having a hard time arguing, because I have only 2+ years of working with VoIP ;) And actually have no deep insight into windows scheduling. 

Still what I do have, is a setup where we were trying to substitute multimedia timers with something based on Stopwatch and WaitOne calls — mostly because we are planning to move to Linux and are looking for a cross-platform solution.
For now we failed to get a stable performance. Instead we get audio tearing — but not always — when there's no other media-related application is working in background. Which is rather weird by itself.

Anyway, I'd be grateful if you point me at some reliable code that could be used instead of multimedia timers. I'd be really glad to move there, for reasons explained above.

**Comment by deeprobin** [comment]
There is now the Nanoseconds API in DateTime, DateOnly, TimeOnly.
See #67666

**Comment by teo-tsirpanis** [comment]
`StopWatch.GetTimeStamp()` uses the best timestamp source the OS can provide ([QPC on Windows](https://github.com/dotnet/runtime/blob/9a72a29c60f2254a72cd36ee2ef0007dba1fc2d7/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Stopwatch.Windows.cs#L19-L28) and [`clock_gettime_nsec_np` or `clock_gettime` on Unix](https://github.com/dotnet/runtime/blob/8b1aecb7d89fdd7ff0319aa57001315da3d1a6a4/src/native/libs/System.Native/pal_time.c#L83-L96)), and its usage has been made easier thanks to #65858. Also we use [`GetSystemTimePreciseAsFileTime`](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) on `DateTime.UtcNow` [if we can](https://github.com/dotnet/runtime/blob/9a72a29c60f2254a72cd36ee2ef0007dba1fc2d7/src/libraries/System.Private.CoreLib/src/System/DateTime.Windows.cs#L134-L169).

I'm going to close this issue, feel free to voice any additional concerns if you have.
