### ISSUE TITLE
IsEnumDefined throws an exception with empty ParamName

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#27491]
Hello,
could you please clarify why do we expect an exception with an empty `ParamName` according this TypeInfo test https://github.com/dotnet/corefx/blob/master/src/System.Reflection/tests/TypeInfoTests.cs#L462 ?

**Comment by GrabYourPitchforks** [comment]
Marking as up for grabs. If somebody wants to take it feel free. Otherwise after a few months of inactivity we'll close due to no interest from the community.

**Comment by Youssef1313** [comment]
@GrabYourPitchforks , I'd like to fix that. But need some guide.

I looked at https://github.com/dotnet/runtime/blob/0a2f0e6da98a784601b37d19417b930a33b2c478/src/libraries/System.Private.CoreLib/src/System/Type.Enum.cs#L20

and there is:

```csharp
            if (!IsEnum)
                throw new ArgumentException(SR.Arg_MustBeEnum, "enumType");
```

So, that thrown exception has ParamName = "enumType", and not empty. So, I seem to be looking in the wrong place. Any guide?

**Comment by svick** [comment]
@Youssef1313 Based on [the test in question](https://github.com/dotnet/runtime/blob/d48be104/src/libraries/System.Reflection/tests/TypeInfoTests.cs#L477), this is about the case when an integer is passed to `IsEnumDefined()` and the type is not an `enum`. As far as I can tell, in that case, the exception ends up being thrown from this line of C++ code:

https://github.com/dotnet/runtime/blob/5178041776634bfbc4f868425710e60d95f7066f/src/coreclr/src/vm/reflectioninvocation.cpp#L2400

I'm not sure what is the right way to fix this. One option would be to add a check to `IsEnumDefined`, which makes sure the current type is an `enum` and throws an exception with the correct `paramName` otherwise.

Though changing the C++ code to at least provide a better exception message than "Value does not fall within the expected range." could be worthwhile too.

**Comment by Youssef1313** [comment]
@svick Thanks for pointing to the native implementation. I opened a PR that I hope is a correct fix.
