### ISSUE TITLE
Server side ALPN support for SslStream on Mac

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#27727]
This is follow-up on dotnet/runtime#26534

SSL API on OSX/MacOS does not provide sufficient functionality to implement server side ALPN.
That is primarily missing code to parse client hello in SSLProcessClientHelloExtensions() and callback (or some other mechanism) for server to choose from provided list.

**Comment by dvtkrlbs** [comment]
Are there any progress on this?

**Comment by wfurt** [comment]
not at the moment. This _may_ get to 6.0 but it requires to re-write PAL to use new API so it is significant chunk of work.

**Comment by JamesNK** [comment]
Are there are plans to investigate this in .NET 6? No TLS on macOS is a point of friction, particularly for gRPC apps.

**Comment by wfurt** [comment]
'/[}

**Comment by wfurt** [comment]
It is low on team priority @JamesNK so I would not put much hope in 6.0. The effort is significant and resources sparse. If you think this is important convince stakeholders.

**Comment by filipnavara** [comment]
I did some investigation into this when doing the iOS TLS bring-up work.

The current TLS implementation uses Security.framework which is deprecated. Underneath the Security.framework with public API there's a coreTLS library with private API. Both of them are open source and the Security APIs are deprecated. In theory there's some ALPN support in there, even for the server side, but in practice it's broken on the coreTLS layer. The code parsing Client Hello messages is [missing ALPN code path](https://github.com/apple-opensource/coreTLS/blob/74450f679817f96a9b659cc5de53313d959333cc/lib/sslHandshakeHello.c#L1459-L1462) which in turns prevents getting the peer's ALPN data. Thanks to @wfurt's earlier efforts .NET has managed TLS frame parser that could be used to retrieve the ALPN data and then select the correct protocols to send back in the Server Hello. I successfully got that part running locally. Unfortunately coreTLS is unable to send the ALPN data back either. When coreTLS encodes the Server Hello packet it [checks the `alpn_announced`](https://github.com/apple-opensource/coreTLS/blob/74450f679817f96a9b659cc5de53313d959333cc/lib/sslHandshakeHello.c#L1459-L1462) flag which is never set since it didn't try to parse the ALPN from the client packet. Hence it's irreparably broken on the Apple API side.

The newer Network.framework APIs are considerably more high level. One basically tells the framework how to stack the protocols and then make the connection. It is thus impossible to use TLS without a transport protocol such as TCP, UDP or domain sockets. There are some APIs to set the transport protocol but I was unable to make it work with any custom protocol. In fact, there's no way to create a custom protocol except for a "framer" one which is designed to frame application-level protocols and not transport level ones. Other frameworks (Python, Ruby, QT) which implement similar abstraction as `SslStream` came to the conclusion that it's basically impossible to mimic it using the new Network.framework APIs ([1](https://bugreports.qt.io/browse/QTBUG-82604) [2](https://bugreports.qt.io/browse/QTBUG-83219) [3](https://bugreports.qt.io/browse/QTBUG-85231) [4](https://github.com/python-trio/trio/issues/1165)).

It's possible to use the "framer" custom protocol to high jack the TLS traffic before it reaches the transport protocol. Thus, in theory it's possible to create a dummy transport (eg. local domain socket) and get the Network framework to do TLS handshake on top of it and intercept all the traffic. Trivial example is [here](https://gist.github.com/filipnavara/bf1e7ad3516082eafa71a9a5b01a29a7). This is reasonably doable for the client-side flows. I was not able to achieve the same thing for the server-side handshake.

Funnily enough, Apple are competing with themselves by maintaining the [SwiftNIO](https://github.com/apple/swift-nio) framework that has its [own TLS stack](https://github.com/apple/swift-nio-ssl) based on BoringSSL. 🤦🏻‍♂️

cc @mandel-macaque

**Comment by wfurt** [comment]
thanks for digging and good summary @filipnavara. The findings on Security.framework match my with my memory.

**Comment by davidvmckay** [comment]
> There are some APIs to set the transport protocol but I was unable to make it work with any custom protocol.

Apple Developer Relations left a hint about how to configure ALPN using the Network.framework APIs: https://developer.apple.com/forums/thread/116193  The OP there succeed in implementing an h2 server using that technique.

Was HTTP2 one of the "custom protocols" unusable based on your investigation, @filipnavara ?


I'm trying to use Kestrel and HTTP2 to make limited application, internal-use ES6 bundler -- but because my main dev machine is a mac, the incomplete HTTP2 support is hampering my progress.  Anything that can dislodge this ALPN-on-macOS issue will be appreciated down the road.

**Comment by filipnavara** [comment]
The problem with Network.framework is that it expects to handle the transport (TCP, UCP, etc.) by itself. That's incompatible with the `SslStream` programming model where the underlying transport stream is provided by the app. It's possible to circumvent for client side but I was not able to do the same for server side.

It would definitely be possible to build the whole server-side including HTTP/2 on top of the Network.framework but that's totally different proposition than just implementing `SslStream` API on top of the framework.

**Comment by chrisdrobison** [comment]
Any progress on this? This issue makes development of GRPC on Mac (specifically GRPC web) almost unusable.

**Comment by wfurt** [comment]
Not really. It is on 7.x list but as @filipnavara and other look into the integration will be probably difficult (or impossible) because of structural differences. 
Would H/3 be possibility for you @chrisdrobison? While you would need to jump through some hoops, it should be possible and I'm reasonably confident we can fix possible lingering issues. 
Since we did integration with OpenSSL for QUIC, we _could_ possibly have alternative mode where the TLS is powered by OpenSSL instead of native Apple's stack. While there are some security implications we could possibly get on par with Linux. That may be OK for development.

**Comment by chrisdrobison** [comment]
H/3 isn’t an option for me right now. I’ll experiment with the VS code remote container stuff and see if that will suffice for now.

**Comment by chrisdrobison** [comment]
Yeah, it looks like the dev container capabilities of VS Code will work well and do what I need for local development. Seems to work pretty well.

**Comment by razfriman** [comment]
Is there any roadmap update to when this might happen? 

Local dev of gRPC and MacOS is pretty sub-par with the only workaround currently to manually disable security features and to toggle this code snippet with directives.

Would love to see 1st class support for this experience while programming on Mac OS

**Comment by davidfowl** [comment]
Agree, we need to revisit the plan here, even if it's just for dev purposes

**Comment by wfurt** [comment]
The consensus so far is that it is not possible with available macOS API. That leaves IMHO alternative with OpenSSL backend or HTTP/3. (that gives gRPC without dependency on SslStream)

**Comment by TyBarthel** [comment]
Are there any disadvantages to advising macOS users to use NGINX to handle SSL  and `grpc_set_header` to send along cert and other details if needed in application code?

**Comment by chrisdrobison** [comment]
I have no idea what the workload would be like, but would this be something worth making a Microsoft specific fork of OpenSSL for so support could be added? Google forked OpenSSL for Chrome to make the kinds of changes they needed so this kind of thing would not be unique.

**Comment by davidfowl** [comment]
> The consensus so far is that it is not possible with available macOS API. That leaves IMHO alternative with OpenSSL backend or HTTP/3. (that gives gRPC without dependency on SslStream)

HTTP/2 not HTTP/3. I'm thinking OpenSSL on MacOS supported for development scenarios only for gRPC as a way to scope the work/support.

**Comment by Leonardo-Ferreira** [comment]
do we have any updates here? .net 7 is right around the corner and as a Mac user, I would surely love to remove the `#if DEBUGMAC` from my code AND let's remember that advanced troubleshooting  is really really hard

**Comment by davidfowl** [comment]
.NET 7 has changed nothing, we're making plans for .NET 8 to solve this.

**Comment by wfurt** [comment]
I put out fix for 8.0. It would be great if people can give it try and provide feedback once the daily build is available. My testing is somewhat limited to runtime and machines I have access to. 
cc: @Tratcher @JamesNK

**Comment by Tratcher** [comment]
I've filed https://github.com/dotnet/aspnetcore/issues/45569 to track this on our side.

**Comment by davidfowl** [comment]
Very cool @wfurt !
