### ISSUE TITLE
EventLog without desktop framework installed results in "message is not found" logs in EventViewer

### ISSUE THREAD

**Issue by pakrym** [dotnet/runtime#27742]
Original issue: https://github.com/aspnet/Logging/issues/858

As far as I understood from reading EventLog implementation it relies on `EventLogMessages.dll` file that shipped with the desktop framework and doesn't ship as part of .net core resulting in `the message resource is present but the message is not found in the string/message table` message being prepended to all event logs in event viewer.

Additionally `EventLog.CreateEventSource(string, string)` would create event source pointing to `EventLogMessages.dll` inside shared directory (`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0\EventLogMessages.dll`) that doesn't exist.

**Comment by Anipik** [comment]
MessageResourceFile should be provided by the user while creating an EventSource. 
As a fallback mechanism, .Net Framework started providing a  messageResourceFile(EventlogMessages.dll). 
This resource file contains all the possible event ids. (1 - 16000 of them). The resource dll is used to return the message string without any locale modification.

The good thing is that all the necessary info associated with event is already shown by the event viewer.
We can fix the reading of the event log from the .Net core apis and also not create a registry key to a file that doesnt exist.

If you guys can give us some scenario where there is some loss of info while reading event using eventviewer or where having that extra string at the end is hindering some diagnostics, then we can take up the issue to fix that as well.

One possible solution for event viewer problem will be to just use one event id for writing the default case.

**Comment by iress-ac** [comment]
@Anipik Could you give an example of how a developer can provide a MessageResourceFile in .Net Core? When adding event logging to the pipeline via `Microsoft.Extensions.Logging.AddEventLog`, you provide an `EventLogSettings` which only contains LogName / MachineName / SourceName.

The issue is quite a bit more intrusive than you might think, as the extra string is not at the end of the message but at the beginning. Most logging tools will give you a snippet of the logs when looking at an overview of logs in aggregate, if we don't specifically write something in to strip this message off, we will see "The description for Event ID  x from source y..." as the summary which actually does hinder diagnostics in practice.

More generally I'd like a way to write an application which can be configured correctly without putting unnecessary strings in the outputted logs. Working around the problem forever isn't appropriate, and adding correct registry entries outside of .Net Core doesn't seem appropriate either.

**Comment by ryannewington** [comment]
@Anipik 

With your statement that
`MessageResourceFile should be provided by the user while creating an EventSource.`

You actually need the c++ compiler to do this. You need to create a message file, compile the message file into a C header file and resource, and finally compile that it into a DLL. 
https://docs.microsoft.com/en-us/windows/win32/eventlog/message-files

It's a very heavy burden that doesn't make sense in a dotnet app.

We don't generally care or want the old windows style of formatting messages and arguments (which this message file format was built around), since we do that ourselves in dotnet. We just need a message file like the one that was provided in .net fx that mapped each possible event ID to a single string.

It's not OK to ship a production application, and have these 'broken' error messages appear in the event logs.

It's a relatively simple inclusion, that means we have correctly represented log messages that are easy to read and diagnose issues with. Expecting dotnet developers to dive into C++ just to get a correctly outputted event log message seems a bit excessive.

So options are either
1) Dotnet core includes the existing message resource files from the framework (they are native windows dlls, not dependent on dotnet fx), and all event logging scenarios work out of the box as expected.

2) Developers create, compile (being aware of platform architecture because anycpu is not a thing in c++), and distribute their own message resource file, just to ensure that their event log messages display correctly in dotnet core

**Comment by KalleOlaviNiemitalo** [comment]
> Most logging tools will give you a snippet of the logs when looking at an overview of logs in aggregate, if we don't specifically write something in to strip this message off, we will see "The description for Event ID x from source y..." as the summary which actually does hinder diagnostics in practice.

Are the logging tools scraping the text from the Event Viewer window? The event log APIs do not return that message.

> You actually need the c++ compiler to do this. You need to create a message file, compile the message file into a C header file and resource, and finally compile that it into a DLL.

[Microsoft.Diagnostics.Tracing.EventRegister](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventRegister/1.1.28) embeds mc.exe and rc.exe, but it is intended for manifest-based events; IIRC, those encode version numbers and other things in [event identifiers](<https://docs.microsoft.com/windows/win32/eventlog/event-identifiers> "Event Identifiers (Event Logging) - Win32 apps | Microsoft Docs"), which then might not match what aspnet/Logging and other libraries write to System.Diagnostics.EventLog.

> We don't generally care or want the old windows style of formatting messages and arguments (which this message file format was built around), since we do that ourselves in dotnet.

The old Windows style has the advantage that the language of the events can be chosen by the user viewing them, rather than the software reporting them. But perhaps that is less important nowadays.

**Comment by ericstj** [comment]
> Are the logging tools scraping the text from the Event Viewer window? The event log APIs do not return that message.

The same exact message is generated by the EventLog apis: https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Diagnostics.EventLog/src/Resources/Strings.resx#L186
https://github.com/dotnet/runtime/blob/3130ac980c97c0664eddb04411f8f765a9f908d8/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogEntry.cs#L156-L167

IIRC a lot of MMC was written in .NET so it's likely that event viewer is using the .NETFramework version of this code (which is largely copied here) to render event messages.

I've checked in a fix for this issue here: https://github.com/dotnet/runtime/pull/45884

Folks who are needing this or would like to try it out can pick up the 6.0 builds of EventLog and try it out.
