### ISSUE TITLE
Deprecate IAsyncResult

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#27936]
Consider marking the `IAsyncResult` interface and the `AsyncResult` class as obsolete and deprecate them in favor of the modern task-based asynchronous pattern.

Then in the future remove all APIs dependent on that interface. This would clean up the API substantially.

**Comment by miloush** [comment]
I understand that some APIs need to be obsoleted because they are fundamentally broken, unsecure or not working. I can also accept that an API can lead to so bad and widespread practices, that the benefits of reducing its usage outweigh compatibility.

I don't see how `IAsyncResult` meets this bar though. Both are valid and working patterns. Obsoletion should not be taken lightly and using it to prefer one pattern over another seems inappropriate. Pattern preference is driven by many factors - subjective opinion, conventions, compatibility requirements - and changes over time.

**Comment by jeffhandley** [comment]
Based on the types of APIs [we've been marking](https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md) as `[Obsolete]` since introducing "better obsoletion," I agree with @miloush that `IAsyncResult` does not meet the bar for obsoletion. It would be very disruptive without enough benefit to justify the disruption.
