### ISSUE TITLE
Expose the match length when using String.IndexOf in culture specific mode

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#27935]
`str.IndexOf(stringToFind)` returns the index of the start of the match but there is no way to tell the length of the match. The match length can be different from the search input (`stringToFind.Length`) in a culture specific mode such as `CurrentCulture`.

For example:
```c#
            Console.WriteLine("Straße".IndexOf("Straße", StringComparison.CurrentCulture)); //0
            Console.WriteLine("Straße".IndexOf("Strasse", StringComparison.CurrentCulture)); //0
            Console.WriteLine("Strasse".IndexOf("Straße", StringComparison.CurrentCulture)); //0
            Console.WriteLine("Strasse".IndexOf("Strasse", StringComparison.CurrentCulture)); //0

            Console.WriteLine("Straße".Length); //6
            Console.WriteLine("Straße".Normalize(NormalizationForm.FormC).Length); //6
            Console.WriteLine("Straße".Normalize(NormalizationForm.FormD).Length); //6
            Console.WriteLine("Strasse".Length); //7
```
`Straße` and `Strasse` are equivalent according to German string processing rules. The example code shows that the two forms match each other. This means that a longer string can be matched in a short string and the other way around.

The Framework should expose the length of the match. For example, in `"Straße".IndexOf("Strasse", StringComparison.CurrentCulture)` it should return `6` although `stringToFind.Length == 7`. In `"Strasse".IndexOf("Straße", StringComparison.CurrentCulture)` it should return `7` although `stringToFind.Length == 6`.

The motivating use case is HTML word highlighting. If I want to highlight all occurrences of `Straße` with `<b></b>` then I need to determine the length of the match.

Doing this currently requires Windows specific PInvoke or a search loop repeatedly calling `IndexOf`: https://stackoverflow.com/questions/20480016/length-of-substring-matched-by-culture-sensitive-string-indexof-method

I also found that `Regex` can accurately report the match length. But `Regex` is slow and awkward to use for non-constant search strings. I'm also not sure if `Regex` supports the exact same string processing semantics that the normal string functions have.

API proposal:

```c#
class String {
 public int IndexOf(string value, int startIndex, int count, StringComparison comparisonType, out int matchLength);
 public int LastIndexOf(string value, int startIndex, int count, StringComparison comparisonType, out int matchLength);
 public bool StartsWith(string value, StringComparison comparisonType, out int matchLength);
 public bool EndsWith(string value, StringComparison comparisonType, out int matchLength);
}

static class MemoryExtensions {
 public static int IndexOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType, out int matchLength);
 public static int LastIndexOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType, out int matchLength);
 public static bool StartsWith(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType, out int matchLength);
 public static bool EndsWith(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType, out int matchLength);
}
```

We could also add this to `StartsWith` and `EndsWith`. They are currently implemented in terms of `IndexOf`.

**Comment by GrabYourPitchforks** [comment]
Since we've now said that returning a `Range` is a valid API pattern (thanks https://github.com/dotnet/runtime/issues/29588#issuecomment-582069797! 🎉), let's start with adding these APIs to the existing type `CompareInfo` and see how things progress from there.

### Proposal (for `CompareInfo`)

```cs
namespace System.Globalization
{
    public sealed class CompareInfo
    {
        /* new proposed APIs */
        public bool IsPrefix(ReadOnlySpan<char> source, ReadOnlySpan<char> prefix, CompareOptions options, out Range match);
        public bool IsSuffix(ReadOnlySpan<char> source, ReadOnlySpan<char> suffix, CompareOptions options, out Range match);
        public bool TryFind(ReadOnlySpan<char> source, ReadOnlySpan<char> value, CompareOptions options, out Range match);
        public bool TryFindLast(ReadOnlySpan<char> source, ReadOnlySpan<char> value, CompareOptions options, out Range match);
    }
}
```

### Behaviors

`TryFind` and `TryFindLast` are similar to `IndexOf` and `IndexOfLast`. If the target _value_ occurs within the search space _source_, the `TryFind[Last]` method will return `true`, and _match_ will be set to the first (last) location where the target string was found. If the target _value_ does not occur within the search space _source_, the `TryFind[Last]` method will return `false`, and _match_ will be set to `default`.

`IsPrefix` and `IsSuffix` are similar. They'll return `true` if and only if the target value is found at the beginning (end) of the search space _source_, and they'll set _match_ to the location where the target string was found.

I wrote a whole tome on just what it means to "find" a target _value_ within a search space _source_. If you're having trouble falling asleep one night go ahead and [give it a read](https://github.com/dotnet/runtime/blob/52aea3b2f739682b75f27d5c264f5d2bc89adfe7/src/libraries/System.Private.CoreLib/src/System/String.Searching.cs#L222-L299). The tl;dr is that even if `IsPrefix` returns `true`, the returned _match_ isn't guaranteed to start at index 0 in the _source_ string. Thus the reason for using `Range` for these APIs instead of having a bunch of different out parameters to return all the necessary values.

Related: https://github.com/dotnet/runtime/issues/25428, which exposes other span-based APIs on `CompareInfo` and which was already approved.

**Comment by tarekgh** [comment]
@GrabYourPitchforks I am wondering for IsPrefix and IsSuffix, does it need to return Range? usually, the index would be 0 anyway from start or from the end. returning the matched length may make more sense and simpler in this case.

**Comment by GrabYourPitchforks** [comment]
@tarekgh IsPrefix isn't guaranteed to return a 0 index, which surprised me when I tested it. Counterexample: source = `"<ZWJ>hello"`, target = `"he"`, IsPrefix = true with match = (1, 3).

**Comment by tarekgh** [comment]
@GrabYourPitchforks I think you are referring to IndexOf which in some cases not returning 0.  if IsPrefix returns true then 0 index is the still correct answer (and should be always the case). The behavior you are describing is just Windows behavior which I don't think is accurate (even if it is technically correct). moving forward I think 0 index is always the right answer for the prefix. In your example, if you return index 0 with length 4 would be accurate answer and better than (1, 3).

**Comment by GrabYourPitchforks** [comment]
Normalizing the result to 0 could introduce a discrepancy where IsPrefix and IndexOf return different ranges given the same input. Wouldn't that possibly lead to coding errors?

**Comment by tarekgh** [comment]
> Normalizing the result to 0 could introduce a discrepancy where IsPrefix and IndexOf return different ranges given the same input. Wouldn't that possibly lead to coding errors?

I don't think so, because both answers are correct. I don't think anyone will call IndexOf and IsPrefix try to match both results (we do that only in our tests but we can change that). Today, if someone doing that, they are already broken. So, we are not really breaking anyone. I think ICU doesn't have this behavior (we can confirm though). Supporting such case just to work with Windows is not worth it and I believe returning always index 0 with IsPrefix is more consistent and accurate and even match users assumption. regardless if we return Range or matched length from the API, I prefer we always force index 0.

**Comment by terrajobst** [comment]
* We shoulnd't invent new names for `IndexOf` and `LastIndexOf`
* While our guidance says we should be adding `string`-based version of the new range returning APIs, we don't believe they are common enough to be warranted. We can add them later if necessary.
* Given the programming model for `IndexOf`, we decided against using the `Try`-pattern.

```C#
namespace System.Globalization
{
    public sealed class CompareInfo
    {
        public bool IsPrefix(ReadOnlySpan<char> source, ReadOnlySpan<char> prefix, CompareOptions options, out Range match);
        public bool IsSuffix(ReadOnlySpan<char> source, ReadOnlySpan<char> suffix, CompareOptions options, out Range match);
        public int IndexOf(ReadOnlySpan<char> source, ReadOnlySpan<char> value, CompareOptions options, out int matchLength);
        public int LastIndexOf(ReadOnlySpan<char> source, ReadOnlySpan<char> value, CompareOptions options, out int matchLength);
    }
}
```

**Comment by tarekgh** [comment]
do we need IsPRefix and IsSuffix return Range? why not just match length? I think we discussed that above.

**Comment by terrajobst** [comment]
@bartonjs felt strongly about this

**Comment by tarekgh** [comment]
Will talk to @bartonjs

**Comment by bartonjs** [comment]
After talking with @tarekgh and @GrabYourPitchforks; and getting a strong lesson in culture-sensitive matching and differences between ICU and NLS; I've changed my mind.

```C#
public bool IsPrefix(ReadOnlySpan<char> source, ReadOnlySpan<char> prefix, CompareOptions options, out int matchLength);
public bool IsSuffix(ReadOnlySpan<char> source, ReadOnlySpan<char> suffix, CompareOptions options, out int matchLength);
```

Is better, because we a) can't agree on what the right answer is for the Range to produce; and b) can't make it be the same on all systems, anyways :smile: (except for "starts at 0", which is effectively what matchLength reports).

**Comment by terrajobst** [comment]
Makes sense :shipit:

**Comment by danmosemsft** [comment]
How is this blocking release of 5.0 product? Moving to Future.

**Comment by GrabYourPitchforks** [comment]
I'm actually about to push up a PR for this.

**Comment by danmosemsft** [comment]
> I'm actually about to push up a PR for this.

Sounds good

**Comment by GrabYourPitchforks** [comment]
Not sure why it got marked as blocking, though. That was weird.

**Comment by tarekgh** [comment]
could be when marked for design review?

**Comment by terrajobst** [comment]
> Not sure why it got marked as blocking, though. That was weird.

Might have been some residue from the API review process.
