### ISSUE TITLE
Azure Functions - System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by rohan3usturge** [dotnet/runtime#27966]
Hi Team,

When using System.Data.SqlClient (  4.6.0-preview-versions ) with azure functions, following exceptions is being thrown.

4.6.0-preview3-27014-02

`System.Private.CoreLib: One or more errors occurred. (System.Data.SqlClient is not supported on this platform.). System.Data.SqlClient: System.Data.SqlClient is not supported on this platform`

Downgrading the version to 4.5.1 works fine.

Tried with `2.2.100-preview2-009404` SDK too, still getting the same exception.

I am using the preview version because we need to use the AAD accesstoken property on `SqlConnection ` Object.

**Comment by cheenamalhotra** [comment]
Closing this issue as we don't reproduce any problems with SqlClient, but the problems emerge due to Azure Functions SDK existing issues.

For anyone facing this issue, please create a new issue with reproducible app provided in **[dotnet/sqlclient](https://github.com/dotnet/sqlclient)** repository if any problems are found with SqlClient libraries.
