### ISSUE TITLE
Assembly(Definition|Reference).GetAssemblyName() do not match handling of neutral culture of AssemblyName.GetAssemblyName()

### ISSUE THREAD

**Issue by nguerrera** [dotnet/runtime#28153]
``` C#
using System;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

class Program
{
    static void Main()
    {
        var coreAssemblyPath = typeof(object).Assembly.Location;

        Console.WriteLine(AssemblyName.GetAssemblyName(coreAssemblyPath));

        using (var peReader = new PEReader(File.OpenRead(coreAssemblyPath)))
        {
            var mdReader = peReader.GetMetadataReader();
            Console.WriteLine(mdReader.GetAssemblyDefinition().GetAssemblyName());
        }
    }
}
```

```
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
System.Private.CoreLib, Version=4.0.0.0, PublicKeyToken=7cec85d7bea7798e
```

Notice culture=neutral vs culture omitted.

**Comment by ThyPillow** [comment]
@satano If you are not working on this anymore, I would like to give it a shot.

**Comment by satano** [comment]
@ThyPillow I am not working at it. I did not understand where is the problem, as I stated in my last comment (and nobody answered).

**Comment by ThyPillow** [comment]
The value at the culture offset in the assembly table is 0 because it is emitted as such.
The compiler is normalizing the culture name in [AssemblyIdentity](https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Compilers/Core/Portable/MetadataReference/AssemblyIdentity.cs#L198), treating `neutral` as invariant culture name and setting `string.empty` to its value.  

As it's saved as null instead of empty, my proposal is to treat the value as empty when reading and building the AssemblyName, similar to what [assemblyspec.cpp ](https://github.com/dotnet/runtime/blob/7c6ec46a637017971d3eaa210fd2b6e4d4a6b737/src/coreclr/src/vm/assemblyspec.cpp#L536) appears to be doing.
At display time [AssemblyNameFormatter](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyNameFormatter.cs#L57) is doing what the compiler is doing in reverse order, treating an empty culture name as `neutral`.
