### ISSUE TITLE
System.Range package similar to System.ValueTuple

### ISSUE THREAD

**Issue by lostmsu** [dotnet/runtime#28285]
My understanding is `System.Range` and `System.Index` are going to be .NET Core 3.0 specific features.
That prevents me from creating a library, that targets .NET Standard 2.0 (for I need to support .NET 4.7), and implements range indexers for the types defined in it.

I think it is a huge problem, especially considering the next .NET Standard is not going to be implemented by .NET 4.8.

Are there any plans to deal with it?

Is the problem in the desire to implement range-based indexing for the core types like `System.Array`? If so, are there ways to work around that? Can .NET Core 3.0 instead define `System._Range`, and have hypothetical System.Range package implementing an implicit conversion `System._Range` -> `System.Range`? Any other alternatives?

**Comment by RayKoopa** [comment]
Also looking forward to a "backport" NuGet package for ranges in .NET Standard 2.0, just like `System.Memory` or `Microsoft.Bcl.HashCode`.

And here I wondered why I never get code style hints by VS for starting to use ranges... was because I also target classic .NET Framework... 👀

**Comment by joperezr** [comment]
ping @terrajobst can you please take a look?

**Comment by terrajobst** [comment]
I've recently discussed this. The problem is this:

1. `ValueTuple` was a bit of disaster. That's because we shipped an out of box (OOB) and in-box version on .NET Framework. This has caused significant pain with binding redirectcs and friends.
2. `Range` itself doesn't suffer from this because there is no version of .NET Framework that included it. We don't have any issues with pure OOBs (span, JSON) However, `Range` depends on tuples 😞 

One could maybe argue that (1) is a thing of the past as .NET Framework 4.7 includes it in-box (and we generally [recommend to be on 4.7.2](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) to consume .NET Standard 2.0 binaries).  We should test this, but I think an OOB for range seems doable.

@ericstj any other concerns?

**Comment by ericstj** [comment]
I think we've created a pattern with the Microsoft.Bcl additions that solves the technical problems.   I briefly looked at @bgrainger's solution and it follows this pattern.  There is still the annoyance that the entire stack needs to target the framework with the component inbox to eliminate the need for the package, for example https://github.com/dotnet/runtime/issues/35984.

**Comment by DjArt** [comment]
That's still actual problem. Any chance to make this happens?

**Comment by chucker** [comment]
@DjArt I've just backported a library from .NET 6.0 to .NET Standard 2.0, and one of the things I had to re-add was System.Range. Long story short:

		<PackageReference Include="IndexRange" Version="1.0.0" />

This seemed to do the trick for my relatively simple use case (get a string's characters except for the very first and very last, with `[1..^1]`). Some more complex needs may not work; see the issues at https://github.com/bgrainger/IndexRange

**Comment by saucecontrol** [comment]
I wouldn't hesitate to use @bgrainger's package in an app, but as a library author, I'm more concerned about the likelihood of downstream conflicts if I were to take a dependency on it.  Not being an 'official' package, it doesn't show up in places like https://apisof.net/, making it more likely a similar third-party shim or a copy/paste of the BCL source might end up in a consuming project alongside my transitive dependency.

It would be really nice to see an 'official' package for this, if only to avoid such conflicts.

**Comment by IanKemp** [comment]
@terrajobst @ericstj bump.

**Comment by Crono1981** [comment]
This would be a huge help. I have legacy apps I still need to patch from time to time, and the ability to use one code base for both legacy and modern .NET apps is a lifesaver.

**Comment by gregsdennis** [comment]
So I'm guessing this probably isn't coming?  It's been a year since any activity here.

**Comment by lostmsu** [comment]
@gregsdennis the abovementioned package `IndexRange` does the job.

**Comment by gregsdennis** [comment]
@lostmsu I'm in the same boat as @saucecontrol.  I'm building a library, and I have to consider downstream impacts.

**Comment by chucker** [comment]
@gregsdennis @saucecontrol can’t you use `PrivateAssets="All"` to avoid downstream impact?

**Comment by saucecontrol** [comment]
You can't if you expose public APIs with Index or Range arguments, which I do, but FWIW I have been using the IndexRange package for over a year with no reported issues.

**Comment by saucecontrol** [comment]
Since it's not yet mentioned here, if you need Index/Range only for internal use (not exposing in public API surface), [PolySharp](https://github.com/Sergio0694/PolySharp) includes those types, along with polyfills for the attribute types required to support modern C# features downlevel.

PolySharp can also make its generated Index/Range public, but then each project's definition of them is distinct.  For public APIs, I'd still recommend the IndexRange package, as those types can be shared between projects.

**Comment by ericstj** [comment]
As of .NET 9.0 release last month this package is now available publicly as [Microsoft.BCL.Memory](https://www.nuget.org/packages/Microsoft.Bcl.Memory#readme-body-tab) for those who were previously waiting on this please give it a try.
