### ISSUE TITLE
Propose new method Enumerable.SelectAll

### ISSUE THREAD

**Issue by pedrolamas** [dotnet/runtime#28486]
For `IEnumerable<IEnumerable<T>>` instances, we currently have the `Enumerable.SelectMany` extension method that does a 1 dimension flatten of all items to a single `IEnumerable<T>`.

I would like to propose a new `Enumerable.SelectAll()` extension method that would allow to recursively flatten all items in all sub-enumerables.

Here's a sample of how this extension would work:

```csharp
public static IEnumerable<T> SelectAll<T>(this IEnumerable<T> source) where T : IEnumerable<T>
{
    foreach (var value in source)
    {
        yield return value;

        if (value == null) continue;

        foreach (var child in value.SelectAll())
        {
            yield return child;
        }
    }
}

public static IEnumerable<T> SelectAll<T>(this IEnumerable<T> source, Func<T, IEnumerable<T>> selector)
{
    foreach (var value in source)
    {
        yield return value;

        if (value == null) continue;

        foreach (var child in selector(value).SelectAll(selector))
        {
            yield return child;
        }
    }
}
```

On the first primitive, it would automatically iterate though `IEnumerable<T>` implementation (do notice that `T : IEnumerable<T>`)

The second primitive would allow to pass a selector, so this would be useful when `T` is not an `IEnumerable<T>`, thus we would indicate how to iterate the "nodes" of the hierarchy.

Root value cannot be `null` (null check is not being done as it happens with most Linq methods), but child `null` values would be returned in correct order and can later be filtered with a `Where` method call.

**Comment by eiriktsarpalis** [comment]
This is essentially a tree flattening operation. If I'm honest, I don't think that this behaviour is common enough to justify addition (particularly in the context of the System.Linq namespace). There are many considerations to be taken into account (e.g. whether to do depth-first or breadth-first traversal, protecting from stack overflows, etc) so my recommendation here would be for authors of the tree type to author their own flattening implementations (since as you demonstrate this is fairly trivial to write using generators).

I'm going to close this issue. Feel free to reopen if you would like to continue this conversation.
