### ISSUE TITLE
System.Data.Odbc.OdbcParameterCollection.Add Slow

### ISSUE THREAD

**Issue by pgodwin** [dotnet/runtime#28693]
I have a project which adds thousands of parameters to an OdbcCommand for bulk inserts.

Testing shows that `OdbcParameterCollection.Add()` and `OdbcParameterCollection.AddRange()` are both very slow methods. 

Jumping into the profiler it seems these methods spend most of their time in Validate():
![image](https://user-images.githubusercontent.com/1046558/52837850-3942f900-313c-11e9-86cf-c3dd3131f4a5.png)

Is there anything that can be done to improve the performance here?

**Comment by madelson** [comment]
I believe the runtime of adding N parameters without names is actually cubic: N additions x N indices attempted (we always try 1..N+1) x O(N) scan for each try.

This gets noticeable pretty quickly; on my machine for example adding 100 parameters without names takes ~8ms whereas adding the same number with names takes only ~0.01ms, an 800-fold increase.

**Is retaining the exact same auto-generated parameter names essential for backwards compatibility here?**

If not, using `Guid` as mentioned above is straightforward and very fast. 

A potential compromise would be to simply start the search for a unique name with index Count+1 instead of 1. That way, we retain the original names in the case where all parameters are unnamed, but shave off a factor of N from the runtime. We could also start with this approach and cut over to the `Guid` approach when the set of parameters grew sufficiently large.

Neither of these incurs any overhead in time or space for users who are not leveraging auto-generated parameters, which seems appealing.

**Comment by Wraith2** [comment]
> Is retaining the exact same auto-generated parameter names essential for backwards compatibility here?

It shouldn't be but unfortunately it is likely to be because of how long it has worked this way. Somewhere in the last 20 years someone has taken a dependency on behaviour that wasn't part of the contract. The question is whether this is worth breaking them?

I like the idea of starting the search at the end though. Test the last one and see if it's the expected n-1 and if it is just add the next one, otherwise fallback to current behaviour. That feels compatible and improves things.
