### ISSUE TITLE
System.IO.Packaging has no way to support private keys that are external

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/runtime#28811]
Splitting off from https://github.com/dotnet/corefx/issues/29959

I've hit issues with `public PackageDigitalSignature Sign(IEnumerable<Uri> parts, X509Certificate certificate);` 

Basically there's no way to account for an external private key. There should be some overload that takes an RSA object (or something else), along with a public cert, and does the signing.

**Comment by wzoet** [comment]
We have a use case for this. Instead of the X509Certificate2 to sign the document, an AsymmetricAlgorithm type should be passed in to the method along with a X509Certificate2. The AssymetricAlgorithm can contain either an X509Certificate2 private key object, or RSA or ECDSA object. 

We have both overloads for the RSA and ECDSA object in our software to forward the signing to external appliances holding the private key. Now we cannot use this to sign office documents, which would be really beneficial for our product.
