### ISSUE TITLE
Force GET Redirect on PUT and POST on HTTP Status Code 300-303

### ISSUE THREAD

**Issue by mnaumanali94** [dotnet/runtime#28998]
Currently, GET request is just forced for POST requests with a 300-303 response. This behavior should also be in place for PUT and DELETE considering they are not safe functions either. RestSharp does it like that.

If not, I couldn't even figure out a way to keep the current behavior and just handling it differently for these methods. From the looks of it, I'll have to implement the complete redirection logic to achieve the desired behavior.

**Comment by TimothyByrd** [comment]
Just so I can understand, if I do a PUT and get back a 303 does net core do another PUT to the URI of the Location header, or to the original URI?
Is there anything to indicate that the Location header indicates a place to PUT, since for POST it's a place to GET?
I just converted a utility from Net Framework to Net 5.0, and a PUT with a 303 response is now doing 50 retries of the PUT.

**Comment by geoffkizer** [comment]
Here's my take on the RFC language, taken from https://tools.ietf.org/html/rfc7231#section-6.4

`300 Multiple Choices` is a weird one and not really used in practice. The RFC is unclear here. I would suggest we not make any change here.

`301 Moved Permanently` and `302 Found` both explicitly state:

> For historical reasons, a user agent MAY change the request method from POST to GET for the subsequent request.

So I think our current behavior here (only change POST) is correct.

`303 See Other` explicitly states:

> This status code is applicable to any HTTP method.

So, I think we should change the behavior for 303 to change the method to GET for all methods (not just PUT). I believe this matches both .NET Framework behavior and common practice.

@scalablecory @stephentoub Any concerns here?

**Comment by TimothyByrd** [comment]
Is there a place I can check the Net Framework code to make sure the behaviour is matching?

**Comment by stephentoub** [comment]
> @stephentoub Any concerns here?

If it brings us better in line with the spec and netfx, sounds good.

**Comment by karelz** [comment]
@TimothyByrd best option is to write a test for each case and try it out. Code is here: https://referencesource.microsoft.com/

> If there are places where the RFC is unclear, I suggest compatibility with the existing Net Framework.
Otherwise, I can't trust porting code that has worked for years.

That is our high-level desire as well -- see https://github.com/dotnet/runtime/issues/28998#issuecomment-539705307.
However note, that we do not have plans to be bug-by-bug compatible with .NET Framework (as it is technically impossible and extremely limits innovation and improvements). If we decide that a behavior on .NET Framework was buggy / undesirable / not conformant with RFC, it might be acceptable to make a breaking change in .NET Core in certain circumstances.
Of course, we do not want to break majority of customers intentionally, so for "bugs" which many customers depend on, we will likely keep them also in .NET Core to make everyone's life easier.

**Comment by TimothyByrd** [comment]
Fair enough.
In cases where the RFC is not clear, the code needs to do _something_, so figuring out the most sensible something is important.

So I should update the PR such that:
- The behaviour will only change for 303/SeeOther, not for any of the other 30x responses.
- A redirect on a 303 will change to a GET for POST (existing behaviour), PUT, DELETE and PATCH
    - GET is already GET and HEAD should stay HEAD
- What about HttpMethod.Options and the internal HttpMethod.Connect ?

**Comment by geoffkizer** [comment]
> A redirect on a 303 will change to a GET for POST (existing behaviour), PUT, DELETE, PATCH and OPTIONS

Why not all methods?

I think special casing HEAD is probably reasonable; HEAD is sort of a special case of GET, and if you did a HEAD in the first place it's pretty weird for that to result in a response body.

But for other methods, including OPTIONS and any unrecognized method, the RFC seems pretty clear that 303 applies to this. The server chose to send a 303. That means it wants the client to follow the redirect.

**Comment by TimothyByrd** [comment]
> Why not all methods?

Well, we know the RFC is unclear, and that since HEAD stays HEAD, "all" doesn't really mean "all".

(This paragraph is how I was imagining things.) POST/PUT/PATCH all create/update a resource, so having a redirect to a GET makes sense for the case where assembling the resource is expensive. OPTIONS sounds like it retrieves metadata about a resource, which makes it seem more like HEAD in a way.

To figure things out, I took a [brute force approach](https://github.com/TimothyByrd/TestRedirects) and checked what Firefox, Edge/Chrome and Net Framework do. (I left out TRACE, because AspNetCore doesn't seem to allow for it.)

It looks like the only major discrepancy is that Net Framework changes "all" methods (except HEAD) to GET when redirecting on a 300. I don't suggest doing that, but I do think it should be documented as change between Net Framework and Net.

And I've updated the pull request to change all methods (except HEAD) to GET.

**Comment by wfurt** [comment]
It seems like compatibility with Framework could be useful if RFC is ambiguous. Would it make sense to add AppContext switch @geoffkizer for legacy behavior?

**Comment by geoffkizer** [comment]
> Would it make sense to add AppContext switch @geoffkizer for legacy behavior?

You mean, to match current behavior? I think our current behavior here is pretty broken, so I don't think there's a need for a compat switch.

**Comment by geoffkizer** [comment]
So to conclude the discussion, here's where we have landed:

(1) 303 should change all methods to GET, except HEAD. This matches .NET Framework and common browser behavior.
(2) 300 behavior is inconsistent across browsers/.NET Framework; we will not make any changes here.

If anything looks wrong, please yell now.

**Comment by geoffkizer** [comment]
BTW @TimothyByrd thanks for doing the research re browser behavior here, that's very helpful.
