### ISSUE TITLE
ClientWebSocket should allow configuration of HttpMessageHandler pipeline for CONNECT

### ISSUE THREAD

**Issue by szilvaa** [dotnet/runtime#29247]
HttpClient provides a flexible [HttpMessageHandler pipeline](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2). Unfortunately, ClientWebSocket does allow the configuration of such pipeline. It directly instantiates [SocketsHttpHandler](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L97). It'd be nice to be able to use the same facilities for all HTTP requests.

**Comment by karelz** [comment]
Triage: There is option to use `WebSocket` on top of stream, which one can create from manually using `HttpClient` (a bit involved, but not rocket science).
Given that `ClientWebSocket` is not tied to `SocketsHttpHandler`/`HttpClient` in API surface and it is only implementation detail, we believe this is the best option here. Otherwise we would have to create very general extensibility model, which is over kill at this moment.
Closing.

**Comment by szilvaa** [comment]
Thanks @karelz! Can you give me some pointers how to go about doing the `WebSocket` on stream thing that you are referring to. I can work through the details but I need an initial clue!
