### ISSUE TITLE
Add an `ISet<T>.AsReadOnly()` extension method

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#29387]
The [`List<>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1) class have a [`AsReadOnly`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.asreadonly) method to turn the collection into a [`ReadOnlyCollection`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.readonlycollection-1), but [`HashSet<>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1) does not have any such method.

## Rationale and usage
Allows Entity Framework Core to expose a [collection navigation property](https://docs.microsoft.com/en-us/ef/core/modeling/relationships) as a [`IReadOnlyCollection`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlycollection-1) when backing it with a private [backing field](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field) declared as a `HashSet`.
```cs
[Table("Blogs")]
public class Blog
{
    private HashSet<Post> _posts;
 
    public int BlogId { get; set; }
 
    public IReadOnlyCollection<Post> Posts => _posts?.AsReadOnly();
 
    public void AddPost(Post post)
    {
        // Do some business logic here...
        _posts.Add(post);
    }
}
```

## Proposed API
```diff
namespace System.Collections.Generic;

public class CollectionExtensions
{
      public ReadOnlyCollection<T> AsReadOnly(this IList<T> list);
      public ReadOnlyDictionary<T> AsReadOnly(this IDictionary<T> dictionary);
+     public ReadOnlySet<T> AsReadOnly(this ISet<T> set);
}

**Comment by NN---** [comment]
> And what would be the return type of `HashSet<T>.AsReadOnly()`? As discussed it can't be `ReadOnlyCollection<T>`.


What about ReadOnlySet which can wrap any ISet ?
Like https://stackoverflow.com/a/36815316/558098

**Comment by eiriktsarpalis** [comment]
Assuming we decided to add something like this, I think it should return an [`IReadOnlySet<T>`](https://github.com/dotnet/runtime/pull/32488) instance. This begs the question whether we should be implementing a `ReadOnlySet<T>` class that wraps an `ISet<T>` instance.

**Comment by binki** [comment]
Wouldn’t it be better for this not to be part of the class but just an extension? Especially since [`HashSet<T>` now implements `IReadOnlySet<T>`](https://github.com/dotnet/runtime/blob/738dcf7994167ab5e4c792f2163b72f79dc9c3a2/src/libraries/System.Collections/ref/System.Collections.cs#L191), this could just be like this:

```csharp
public static class HashSetExtensions {
    public static IReadOnlySet<T> AsReadOnlySet(
        this IReadOnlySet<T> readOnlySet) {
        return readOnlySet;
    }
}
```

Since a direct cast exists, the rationale for including the above API would be the same as for having [`Enumerable.AsEnumerable<TSource>()`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.asenumerable?view=net-5.0)—to support the use of implicit typing and/or method overload resolution, especially if `T` in `IReadOnlySet<T>` is big, impractical, or impossible to provide explicitly.

For wrapping `ISet<T>`, I’d expect a thin wrapper and the return type to be `IReadOnlySet<T>` instead of doing something like returning an instance of `ReadOnlyCollection<T>`. Then the reader can see updates made to the `ISet<T>` by others (remember, read-only and immutable are very different concepts even though immutable implies unwritable). The biggest issue with this approach would be the specificity/overloads for the appropriate extension methods. Since `HashSet<T>` is both `ISet<T>` and `IReadOnlySet<T>`, the following would create an ambiguity error if merged with the above code:

```csharp
public static class HashSetExtensions {
    public static IReadOnlySet<T> AsReadOnlySet(
        this ISet<T> set) {
        return new ReadOnlySetAdapter<T>(set);
    }

    class ReadOnlySetAdapter<T> : IReadOnlySet<T> {
        …
    }
}
```

**Comment by stephentoub** [comment]
`ReadOnlySet<T>` now exists in .NET 9. We _could_ choose to have an `ReadOnlySet<T> AsReadOnly()` if desirable.

**Comment by eiriktsarpalis** [comment]
I've updated the API proposal to add an extension method in `CollectionExtensions`.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Collections.Generic;

public partial class CollectionExtensions
{
    // Existing:
    // public ReadOnlyCollection<T> AsReadOnly(this IList<T> list);
    // public ReadOnlyDictionary<T> AsReadOnly(this IDictionary<T> dictionary);
    public ReadOnlySet<T> AsReadOnly(this ISet<T> set);
}
```

**Comment by silkfire** [comment]
Was there any reason this extension didn't make it into .NET 9?
