### ISSUE TITLE
Investigate allowing Utf8String package to work on netstandard 2.0

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#29442]
Currently the package requires netcoreapp3.0 nightly. We'd reach a wider audience if our customers could experiment and give feedback with a netstandard 2.0 compatible package.

**Comment by Entomy** [comment]
I second this. My entire text processing/manipulation/parsing API's support as far back as netstandard2.0 since there's nothing language support wise that I need from newer runtimes. So being able to add `Utf8String` directly to the supported API's for all targets, not just the most recent supported targets, would be nice.

If it helps at all, I've actually backported `Rune` to netstandard2.0 [here](https://github.com/Entomy/Stringier/commit/1e5b3e7e4308ff0b98f416a707c302fff127079e), and tested against (translated) official tests. You can lift that code for an official backport, since I can just remove the backport and add the official backport as a dependency.
