### ISSUE TITLE
RemoveWhere with post processing action

### ISSUE THREAD

**Issue by helviett** [dotnet/runtime#29634]
I suggest to add method for HashSet<T>. 
`HashSet<T>.RemoveWhere(Predicate<T>, Action<T> postProcessingAction).`
It's a common situation when you need to remove something from collection and do a post processing things (e.g. remove references)

**Comment by infogulch** [comment]
I also found that it was cumbersome to post-process removed elements efficiently.

So I wrote `RemoveWhereEnumerator` which is just like `RemoveWhere` except it is a generator function that yields each removed element.  This is based on the [referencesource](https://github.com/microsoft/referencesource/blob/master/System.Core/System/Collections/Generic/HashSet.cs#L872) code because I couldn't find HashSet implementation here.

``` c#
        /// <summary>
        /// Remove elements that match specified predicate and emit the removed elements as an 
        /// enumerable. The enumerable must be completely consumed to ensure all matching elements
        /// are removed.
        /// </summary>
        /// <param name="match"></param>
        /// <returns></returns>
        public IEnumerable<T> RemoveWhereEnumerator(Predicate<T> match) {
            if (match == null) {
                throw new ArgumentNullException("match");
            }
            Contract.EndContractBlock();

            for (int i = 0; i < m_lastIndex; i++) {
                if (m_slots[i].hashCode >= 0) {
                    // cache value in case delegate removes it
                    T value = m_slots[i].value;
                    if (match(value)) {
                        // check again that remove actually removes it
                        if (Remove(value)) {
                            yield return value;
                        }
                    }
                }
            }
        }
```

This enables consumers to process elements in a stream without accumulating them like the following examples suggest:

```c#
// removes elements from setB and adds them to setA
var removed = setA.UnionWith(setB.RemoveWhereEnumerator(e => e.ShouldBeRemoved));
```

```c#
// removes elements with Value greater than 10 from setA and calls processes() on each
foreach (var removed in setA.RemoveWhereEnumerator(e => e.Value > 10))
    process(removed);
```

I think that a generator function is a great fit here because it efficiently iterates the HashSet, doesn't perform any allocations (modulo perhaps allocating for the generator state machine itself), doesn't do any internal accumulation, and is naturally consumed by all collections which use IEnumerable interfaces everywhere.

Here is an alternative extension method that I'm using in my project today (since I can't implement RemoveWhereEnumerable without access to the internal data structure), but it loses many of the benefits listed above:

```c#
        public static IEnumerable<T> RemoveAndCollectWhere<T>(this System.Collections.Generic.HashSet<T> self, Predicate<T> predicate)
        {
            var result = new List<T>();
            self.RemoveWhere(t =>
            {
                var p = predicate(t);
                if (p) result.Add(t);
                return p;
            });
            return result;
        }
```

I'm open to name suggestions.  Thoughts?

**Comment by eiriktsarpalis** [comment]
A few thoughts on the proposal:

* My first interpretation when reading `HashSet<T>.RemoveWhere(Predicate<T>, Action<T> postProcessingAction)` was that `postProcessingAction` was meant for the elements that were *not* removed. While clearly wrong in hindsight, it demonstrates an inherent ambiguity w.r.t. the semantics of such a method.

* A potential `IEnumerable<T> RemoveWhereEnumerator(Predicate<T> match)` method is problematic, since IEnumerable is lazily evaluated. Depending on how it is consumed, the "RemoveWhere" operation could be run once, more than once, or none at all. Clearly `RemoveAndCollectWhere` is the right approach here, even though it needs to copy the removed elements into an intermediate list.

In light of the above I think it would make more sense for users to author their own extension methods expressed on top of the existing `RemoveWhere` method. For example:

```csharp
public static void RemoveWhere<T>(this HashSet<T> hashSet, Predicate<T> predicate, Action<T> postProcessingAction)
{
    hashSet.RemoveWhere(t =>
    {
        if (predicate(t))
        {
            postProcessingAction(t);
            return true;
        }

        return false;
    });
}
```

**Comment by eiriktsarpalis** [comment]
I am going to close this issue, since I don't think we could accept such a proposal. Feel free to reopen if you would like the conversation to continue.

**Comment by infogulch** [comment]
Your objections are noted in the doc comment for `RemoveWhereEnumerator`:

```c#
/// RemoveWhereEnumerator removes elements that match specified predicate, and yields the removed
/// elements in the returned enumerable. The enumerable must be completely consumed to ensure 
/// all matching elements are removed.
```

If a user wants to do something with the elements that were *not* removed, they can trivially solve the problem by combining existing language features (one example: `setA.RemoveWhere(e => e.X); foreach (var e in setA) process(e);`), whereas processing the removed elements efficiently is not as straightforward accomplish.  I don't think it's fair to call this feature request 'semantically ambiguous' on these grounds (though there's room for these methods to have better names).

I prefer lazy evaluation because it gives the user more choice (you can just `.ToList()` whenever you like), enables composition without unbounded nested lambdas, and encourages building processing pipelines over batching.  I sympathize that this may not be a good choice for a standard library, but I still lament that such functionality is not available.

**Comment by eiriktsarpalis** [comment]
> If a user wants to do something with the elements that were not removed, they can trivially solve the problem by combining existing language features (one example: setA.RemoveWhere(e => e.X); foreach (var e in setA) process(e);), whereas processing the removed elements efficiently is not as straightforward accomplish. I don't think it's fair to call this feature request 'semantically ambiguous' on these grounds (though there's room for these methods to have better names).

I'm not arguing that it is impossible to use it appropriately if you're careful, my point is that things can very easily go wrong if you're not. `RemoveWhere` performs an operation on the collection, however `RemoveWhereHashSet` does not do anything; the resulting enumerator(s) may or may not trigger the desired side-effects, but that really depends on how it is being consumed. It could even just remove half the elements because the consuming code chained it with `.Take(3)`.

**Comment by infogulch** [comment]
The part of my comment that you quoted is about how it's awkward to post-process removed elements, and doesn't say anything about the issues around IEnumerable.  Maybe you meant to respond to the doc comment or my second paragraph?:

> I prefer lazy evaluation because it gives the user more choice (you can just .ToList() to opt out), enables composition without unbounded nested lambdas, and encourages building processing pipelines over batching. I sympathize that this may not be a good choice for a standard library, but I still lament that such functionality can't be offered outside the library itself.

I agree that `RemoveWhereEnumerator` (I guess this is what you meant by "`RemoveWhereHashSet`"?) could have surprising behavior if you've never used IEnumerables before, but if a user is opting in to using an API that is pretty explicitly a generator and states "The enumerable must be completely consumed to ensure all matching elements are removed." then I don't know if we should coddle them further.

The problematic chaining that you point out could be fixed by the user with `.ToList().Take(3)`; I like this solution because it is clear that the user wants to consume the whole enumerable, and that they have explicitly chosen to do that by collecting all the removed elements.  The key is that the user can *choose* how to implement it.

Note, if `RemoveWhereEnumerator` existed, that would lend to a trivial implementation for `RemoveAndCollectWhere` and still enable non-allocating use cases:

```
IList<T> RemoveAndCollectWhere<T>(Predicate<T> match) => RemoveWhereEnumerator(match).ToList();
```

**Comment by infogulch** [comment]
Honestly, I could imagine *wanting* the behavior you mentioned where it only removes the first N arbitrary matching elements from the HashSet.  This would be easily accomplished with:

```c#
var removed = hashSet.RemoveWhereEnumerator(e => e.Value > 10).Take(5); // Remove up to 5 elements where Value > 10
// do something with up to 5 elements at a time
```

But the same thing would require 10-20 lines without `RemoveWhereEnumerator`
