### ISSUE TITLE
C# console app failed with 'Error Connecting to Exchange Server!!Could not load file or assembly 'System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by githubgato** [dotnet/runtime#29786]
Executing a .NET Framework 4.6.1 console app that references a .NET Standard 2.0 assembly fails with
Error Connecting to Exchange Server!!Could not load file or assembly 'System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Any idea? Thank you so so much

`using System;
using Microsoft.Exchange.WebServices.Data;

namespace GetMailFromExchange
{
    class Program
    {
        ExchangeService serviceInstance;
        public string ExceptionMessage { get; }
        static void Main(string[] args)
        {
            Console.WriteLine("start!");
            ConnectToExchangeServer();
            
        }

        static void ConnectToExchangeServer()
        {

            Console.WriteLine("connect to exchangeServer!");

            try
            {
                //ExchangeService exchange = new ExchangeService(ExchangeVersion.);
                //exchange.Credentials = new WebCredentials("123@abc.com", "abc" );
                //exchange.AutodiscoverUrl("123@abc.com");

                ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2013_SP1);
                
                //service.UseDefaultCredentials = true;
              
                 
                service.Credentials = new WebCredentials("123@abc.com", "abc"   );
                service.TraceEnabled = true;
                service.TraceFlags = TraceFlags.All;
                service.AutodiscoverUrl("123@abc.com");
                EmailMessage email = new EmailMessage(service);
                email.ToRecipients.Add("123@abc.com");
                email.Subject = "HelloWorld";
                email.Body = new MessageBody("This is the first email I've sent by using the EWS Managed API");
                email.Send();

                Console.WriteLine("Connected to Exchange Server : " + service.Url.Host);

            }
            catch (Exception ex)
            {
                Console.WriteLine("Error Connecting to Exchange Server!!" + ex.Message);

            }

        }

        

    }
}
`

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Exchange.WebServices" Version="2.2.0" />
    <PackageReference Include="NETStandard.Library" Version="2.0.0" />
  </ItemGroup>

</Project>
`

**Comment by danmosemsft** [comment]
@joperezr

**Comment by joperezr** [comment]
Hello @githubgato. We need a bit more time to investigate this further but my initial hunch is that you are either missing a direct reference to the System.DirectoryServices package or you might be using packages.config to restore your project which is not bringing in some transitive dependencies. In order to confirm this, would you mind sharing either a minimal repro project or if not just a binlog file of your build? You can get a binlog file by running the following from a developer command prompt: `msbuild yourProject.csproj /t:rebuild /bl:msbuild.binlog` and attach here your resulting msbuild.binlog file.

**Comment by githubgato** [comment]
@joperezr  I did use  NuGet Package Manager  and Install-Package Microsoft.Exchange.WebServices
and using Microsoft.Exchange.WebServices.Data; also in package
 <PackageReference Include="Microsoft.Exchange.WebServices" Version="2.2.0" />
    <PackageReference Include="NETStandard.Library" Version="2.0.0" />
I do see an alert in my package said
Package 'Microsoft.Exchange.WebServices 2.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.


let me try share the repo
https://github.com/githubgato/ExchangeTest

Thank you all.

**Comment by joperezr** [comment]
I see, usually when you hit those types of errors, we suggest you to add a PackageReference to "Microsoft.Windows.Compatibility" package which has basically the purpose of fixing these type of issues. I just tried out your project and the problem doesn't repro after I add that extra reference. I'll go ahead and close the issue assuming you will also have it working after adding that package reference, but please do feel free to re-open if you are still hitting problems with this.

**Comment by githubgato** [comment]
Maybe I should not use core

**Comment by githubgato** [comment]
And Thank you @joperezr , it did fix the issue

**Comment by joperezr** [comment]
> Maybe I should not use core

I would really argue that using .NET Core in most cases is the right thing to do, this problem you are hitting is only because some of the packages you are using were designed with only .NEt Framework in mind, and not really Core, but that is exactly why we've built the compatibility package in order to be able to fix this for more than 90% of the case. So that means that if you hit any problems in the future either using .NET Core or not, we would be very interested in ensuring there is some path for you to be successful using .NET so do be sure to log an issue if you hit any problems.
