### ISSUE TITLE
[API Proposal]: JsonSerializer.TryReadValue(ref Utf8JsonReader)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#29902]
Today if the JSON passed into the JsonSerializer needs to be the fully formed, this means its basically impossible to let the caller handle buffering (which is unfortunate). This seems solvable if we add a TryReadValue which would return false if the Serializer failed to Read the full object from the Utf8JsonReader. 

```C#
public static class JsonSerializer
{
    public static bool TryReadValue(ref Utf8JsonReader reader, Type returnType, out object value, JsonSerializerOptions options = null);
    public static bool TryReadValue<TValue>(ref Utf8JsonReader reader, out TValue value, JsonSerializerOptions options = null);
}
```

This currently wouldn't preserve the serializer state, but it would let the caller buffer an entire JSON payload from a Stream of bytes without a surrounding envelope.

**Comment by frankhaugen** [comment]
Would name this TryDeserialize<T>()

And include a TrySerialize(), because suddenly you have something too complex or self recursive references that will cause a crash unless wrapped in try/catch. when creating a library you have no control over what is being serialized, it results in so many bug reports

**Comment by davidfowl** [comment]
😢

**Comment by eiriktsarpalis** [comment]
@davidfowl I realize that this is a fairly old issue, but don't the async deserialization methods address that particular use case today?

FWIW this API shape is precisely how async serialization is [implemented internally](https://github.com/dotnet/runtime/blob/becd0136afd072a7e94bfb730784ad390034f4c4/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L148), but you still need to somehow marshall the deserialization stack (this is done using the `ReadState` struct internally). We plan on possibly exposing this API in 7.0.0, but only on the converter level (cf. https://github.com/dotnet/runtime/issues/36785)

**Comment by davidfowl** [comment]
I'd still love a PipeReader overload on DeserializeAsync. This was a workaround for that missing

**Comment by eiriktsarpalis** [comment]
I see. We probably wouldn't be able to take a Pipes dependency on STJ, so presumably you'd need the ability to roll your own method.

We should consider offering this as part of #60904. Closing in favor of that issue.

**Comment by steveharter** [comment]
Note that PipeReader\Writer async were in the initial commit for the serializer back in 3.0. However, due to concerns it was pulled:

[read](https://github.com/dotnet/corefx/pull/35609/commits/ebfb03c342a5f923dd58751d1016791ddcffd742#diff-b2f02759e59139a12db78731cdd548f0f52a17bee79ae87f6f73f0ce44887838)
[write](https://github.com/dotnet/corefx/pull/35609/commits/ebfb03c342a5f923dd58751d1016791ddcffd742#diff-60d370871667dd10e2c9664caebda0397ecbf3a74adaff3e72c4319c9210c7bd)
[tests](https://github.com/dotnet/corefx/pull/35609/commits/ebfb03c342a5f923dd58751d1016791ddcffd742#diff-81c4e76f2172c2ef44486eb4648c630d6c78a427a2612e2b2e972d947d71276e)

Original issue: https://github.com/dotnet/runtime/issues/28325
Older prototype: https://github.com/dotnet/corefxlab/pull/2647#pullrequestreview-202341575

**Comment by davidfowl** [comment]
Bring it back 🥲

**Comment by steveharter** [comment]
> Bring it back 🥲

Yeah we'd have to re-evaluate the dependency from STJ to System.IO.Pipelines. Some options:
- Take the dependency
  - We'd have to account for lack of it being in NetStandard so in-box only? If part of the package, users will have additional assembly(s) that they may not use.
  - Trimming should work fine for Blazor client and stand-alone apps.
- Add an extension assembly like STJ.PipeLines.
  - Since C# doesn't support static extension methods to add the new methods to JsonSerializer class, there would likely need to be a new class (e.g. `JsonSerializerPipelines`), a new extension model, or we add Serializer\Deserialize extension methods to PipeReader\Writer.
  - We'd also need a public way to call into the currently internal serializer methods that deal with internal classes like `ReadState` etc (we already have some other reasons to do this).
