### ISSUE TITLE
Support polymorphic serialization through new option

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#29937]
EDIT see https://github.com/dotnet/runtime/issues/29937#issuecomment-861491156 for the finalized API proposal.

<details>
<summary>
 Original proposal by @steveharter (click to view)
</summary>

# Current behavior
Consider a simple model:
```cs
abstract class Person {...}
class Customer : Person {...}
```

The current behavior, by design, is to use the static type and not serialize polymorphically.
```cs
// This will serialize all properties on `Person` but not `Customer`:
Person person = new Customer();
string str = JsonSerializer.ToString<Person>(person);

// This does the same thing through generic type inference:
string str = JsonSerializer.ToString(person);
```

However, if the type is declared to be `System.Object` then all properties will be serialized:
```cs
object person = new Customer();
// This will serialize all properties on `Customer`
string str = JsonSerializer.ToString(person);
```

In addition, the `Type` parameter can be specified:
```cs
Person person = new Customer();
// This will serialize all properties on `Customer`
string str = JsonSerializer.ToString(person, person.GetType());
```

All of these semantics are current as will remain as-is.

# Proposed API
Add an opt-in setting that will serialize all types polymorphically, instead of just `System.Object`:
```cs
namespace System.Text.Json
{
    public class JsonSerializerOptions // existing class
    {
. . .
        bool SerializePolymorphically { get; set; }    
. . .
    }
}
```

Example of new behavior:
```cs

var options = new JsonSerializerOptions();
options.SerializePolymorphically = true;

// This will serialize all properties on `Customer`:
Person person = new Customer();
string str = JsonSerializer.ToString(person, options);
```

This new behavior applies both to the root object being serialized (as shown above) plus any properties on POCOs including collections, such as `List<Person>`.

Note: this issue does not enable any additional support for polymorphic **deserialize**. Currently, a property or collection of type `System.Object` will result in a `JsonElement` being created. Any additional polymorphic deserialize support must be done with a custom converter.
</details>

**Comment by ahsonkhan** [comment]
From @mauricio-bv in https://github.com/dotnet/runtime/issues/31742

> I am trying to use the System.Text.Json serialization libray, but I can't get it is serialize it as I used to with Newtonson. Properties in derived classes or Interfaces are not serializing. This issue has also been asked and explained in the link below.
> 
> [Link](https://stackoverflow.com/questions/59258655/system-text-json-jsonserializer-doesnt-serialize-properties-from-derived-classe/59536948#59536948)
> 
> Is there any serialization option I should set for proper serialization?

cc @Arash-Sabet, @bailei1987, @bstordrup

**Comment by rosieks** [comment]
It would be nice if this could be compatible with OpenAPI polymorphism.

**Comment by ttrinidad** [comment]
The solution for deep serialization of derived types, (and many other amenities) is to keep using Newtonsoft, which work as desired by most reasonable people

Or do as the docs recommend and change your classes property types to "object":
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialize-properties-of-derived-classes

We get it, it's free, but it's just not good as advertised.

**Comment by jan-johansson-mr** [comment]
Hi,

It's not that hard to add polymorphic support to `System.Text.Json` via some `Converter`. However, once done we know we break JSON specification, since JSON specification doesn't support metadata anyway (we can however add some ad hoc convention for metadata). So the good news is, yes, it's very possible to add polymorphic support, and it is not that hard either.

The bad news is that by design ASP.NET Core endpoint will not support polymorphism anyway. I'm including some examples for illustration. Assume two types, the base type and the type inheriting from the base type, called `Payload`.

If we feed the instance of the polymorphed object to the serializer as

`JsonSerializer.Serialize(payload, _jsonSerializerOptions)`

Then we get the following output with the instantiating type embedded in the JSON document:
```
{"$i":"JsonSerializationTest.Payload","title":"Title","description":"Description","id":"72f191f9-35b8-459e-897b-98745d4f4005"}
```

If we feed the same object with slightly tweaked code

`JsonSerializer.Serialize(payload, payload.GetType(), _jsonSerializerOptions)`

Then we get the output
```
{"title":"Title","description":"Description","id":"72f191f9-35b8-459e-897b-98745d4f4005"}
```
The effect is that yes, we kind of get the same "polymorphed" object on top level, but we've lost the polymorph metadata in the process (the `$i` tag in the JSON document).

Notice the `payload.GetType()` as parameter to `System.Text.Json.JsonSerializer`? That is the reason for the difference in the output.

Look at the code in ASP.NET project, from [line 77](https://github.com/dotnet/aspnetcore/blob/02bf53de96b066fbda1bbb4127523b62c8b5a09c/src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonOutputFormatter.cs#L77) (where we get the type) and then further down where the serialization actually occurs. If you read the comment, you also see that this is by design, and of course only applies to the top level of the object.

Now, if I add my [polymorphic] `Converter` to `System.Text.Json` in the ASP.NET Core, e.g.
```
services
    .AddControllers()
    .AddJsonOptions(configure => ...)
```
I'll get exactly the same behavior as described above. But if I feed my object in some deeper level, e.g. I return `new { payload = payload }`, then my `Converter` kicks in and I get the expected output (however, now it's on second level and not first and that's inconvenient).

I understand the reason for this design in the ASP.NET Core, but again, even if they would build in support for polymorphic serialization with `System.Text.Json`, the same problem that I described will hit you anyway because of this design.

**Comment by lwansbrough** [comment]
@jan-johansson-mr IMO any performance gains made from stripping expected behaviour from .NET’s defacto JSON library is a disingenuous comparison. It’s very easy to make anything fast if we rip out all the functionality. Fact is, System.Text.Json breaks behaviour and expectations around serialization in the .NET world. .NET is popular because for the most part it just works. From that perspective, this library has dysfunctional behaviour. And it definitely should not be advertised as a cost-free drop in replacement for JSON.NET.

**Comment by sake402** [comment]
@jan-johansson-mr I second lwansbrough with his comment. 
Worse now is if given
```
public class Base{
public string PropertyBase{ get; set; }="Base";
}
public class Foo:Base{
public string PropertyFoo{ get; set; } = "Foo";
}

public class Bar:Base{
public string PropertyBar{ get; set; } = "Bar";
}
```
If we then do
```
var bases = new[]{ new Foo(), new Bar() }
JsonSerializer.Serialize<object>(bases);
```
We still get
```
[{"PropertyBase":"Base"}, {"PropertyBase":"Base"}]
```
which entirely strip off upper class hierachy property yet. Despite using object as the serialization type

**Comment by TheBuzzSaw** [comment]
@sake402 While not a solution, does it start working if you cast the array itself to `object[]`?

**Comment by qsdfplkj** [comment]
There is another issue that adds metadata to prevent infinite loops. JsonSerializerOptions.ReferenceHandler. If we allow metadata we migh also allow type information to be included and use this during deserialization.

Besides the SerializePolymorphically option you could also tweak the model with attributes to only make certain properties polymorphic [SerializePolymorphically] or use a convention that properties declared as interfaces (or abstract classes) are always polymorphic even when the SerializePolymorphically option is disabled. You could also skip the metadata $type when the declared type equals the runtime type when SerializePolymorphically option is enabled so that there is no difference in the result json output 

Personally I think if you serialize $type metadata only when the declared type differs from the runtime type you don't even need a SerializePolymorphically option where this wouldn't break existing scenario's because I _assume_ that the declared type should equal the runtime type.

Security:
If deserialized with a generic type argument it will fail due to casting but if deserialized with the generic type argument being object you should throw an not supported exception because you might have a security vulnerability.

**Comment by qsdfplkj** [comment]
I use the following polymorphic json converter which serializes interfaces and abstract classes (or properties) with type metadata and uses that for deserialization. (See also my previous comment for my thoughts on polymorphic serialization.)

This converter serializes an object or property that is declared as abstract or interface as follows:
{  $type: typeof(T).AssemblyQualifiedName, $value: { propertyName: propertyValue } }

It would be nice though if it worked like this:
{ $type: typeof(T).AssemblyQualifiedName, propertyName: propertyValue }

The difference is that the first $type is property about $value the second $type is a property of $value it itself. The later I think is cleaner and is the way newtonsoft seems to do it. For it to work like that I would need to loop over the properties when (de)serializing myself.

    public class PolymorphicJsonConverter : JsonConverter<object>
    {
        public override bool CanConvert(Type typeToConvert)
        {
            return typeToConvert.IsInterface || typeToConvert.IsAbstract;
        }

        public override object Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            reader.Read();
            reader.Read();
            string assemblyQualifiedName = reader.GetString();
            reader.Read();
            object result = JsonSerializer.Deserialize(ref reader, Type.GetType(assemblyQualifiedName), options);
            reader.Read();
            return result;
        }

        public override void Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("$type");
            writer.WriteStringValue(value.GetType().AssemblyQualifiedName);
            writer.WritePropertyName("$value");
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
            writer.WriteEndObject();
        }
    }

**Comment by josh-endries** [comment]
FFS, just own up to a bad decision and make it the default behavior, like every other worthwhile serialization tool out there. The thing needs to do before it fasts. As far as stupid default behaviors go, this has got to be one of the dumbest I've come across. A serialization library that (by default) doesn't serialize what you give it. Awesome! No wonder it's so fast!

IFoo { string Foo }
IBar { string Bar }

Serialize(listOfBar) → [{Bar:""}]

I now expect this, NOT based on documentation and NOT based on common sense, but based on a thread I found that linked to this one...however:

Serialize<object>(listOfBar)

also gives the same exact, incorrect, result. This library isn't serializing List<IBar>, because IBar includes both properties. That's how C#/OOP works, I'm sorry but it's not okay to just ignore this and pretend/assume that I don't want all of my IBar object serialized. The inherited properties are also important and are also part of that object and objects of that type.

I can't do Serialize<object[]>(listOfBar) as it can't convert my actual List<IBar> to List<object> or object[]. So now everyone needs to .ToArray() and use Serialize<object[]> to get behavior that seems completely reasonable to expect and is how every other serializer I've ever used in my life works.

The option should switch it to whatever nonsense you seem to think is super important yet neither I nor anyone I know has ever cared about. I'm sure some people do, but I would bet money that it's a small minority. This behavior and the proposed solution to it is simply backwards.

I had high hopes for switching to Core and using this library everywhere without additional dependencies, but not if there are bizarre design decisions like this in it. People like to say this is a drop-in for Newtonsoft but it absolutely isn't with this giant bug.

Not only should this be documented, it should be put right into the method docs along with the object workaround, because nobody I know is going to expect this to work as it does... Or make a SerializeShallow() or something. Rather than cause people to waste a bunch of time looking into why their stuff doesn't work, I'm just going to abandon this pile and go back to json.net. Sigh.

This is really super super disappointing. :(

**Comment by qsdfplkj** [comment]
If you like OOP you should be serializing IList and not a List. I don’t have a problem to serialize object[] but we need metadata to deserialize the Json but there is no metadata yet so deserialize should be called with the samen generic type argument as serialize (which only works for the root object and not for properties) When you use object or the non generic method you cannot deserialize without metadata. Neither can json.net by default but they have metadata support so enable it and it works. Besides this I noticed that both serializers don’t support explicit interfaces.  I don’t think this metadata will degrade performance but I don’t like metadata when it isn’t needed (which json.net generates). I personally don’t understand why we use JavaScript a dynamic typed language to serialize strong type languages and then complain about stuff not working or not according to “the standard”. It was never ment to be send anywhere but to JavaScript. Why not use xmlserializers?

**Comment by lukacs-andras** [comment]
> @jan-johansson-mr I second @lwansbrough with his comment.
> Worse now is if given
> 
> ```
> public class Base{
> public string PropertyBase{ get; set; }="Base";
> }
> public class Foo:Base{
> public string PropertyFoo{ get; set; } = "Foo";
> }
> 
> public class Bar:Base{
> public string PropertyBar{ get; set; } = "Bar";
> }
> ```
> 
> If we then do
> 
> ```
> var bases = new[]{ new Foo(), new Bar() }
> JsonSerializer.Serialize<object>(bases);
> ```
> 
> We still get
> 
> ```
> [{"PropertyBase":"Base"}, {"PropertyBase":"Base"}]
> ```
> 
> which entirely strip off upper class hierachy property yet. Despite using object as the serialization type

In that case, the correct generic type parameter is object[] instead of object.

**Comment by steveharter** [comment]
> FFS, just own up to a bad decision and make it the default behavior, like every other worthwhile serialization tool out there. The thing needs to do before it fasts. As far as stupid default behaviors go, this has got to be one of the dumbest I've come across. A serialization library that (by default) doesn't serialize what you give it. Awesome! No wonder it's so fast!

The first release in 3.0 was considered a minimum viable product and getting polymorphism in correctly wasn't feasible. Polymorphic serialization is easy -- we already do it when type == typeof(object) -- but adding the metadata for deserialization needs to be done right where it uses "known types" and not the raw CLR string (for security). This feature didn't fit into the 5.0 release either.

Polymorphic serialization of a root type has basically zero perf overhead -- calling object.GetType(). Polymorphic deserialization will have a perf hit if the metadata is there, but that entails a simple lookup from the string-based metadata ("$type:MyKnownType") to a CLR Type.

System.Text.Json was never intended to replace Newtonsoft.JSON for all scenarios. From the [documention](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#table-of-differences-between-newtonsoftjson-and-systemtextjson):

_System.Text.Json focuses primarily on performance, security, and standards compliance. It has some key differences in default behavior and doesn't aim to have feature parity with Newtonsoft.Json. For some scenarios, System.Text.Json has no built-in functionality, but there are recommended workarounds. For other scenarios, workarounds are impractical. If your application depends on a missing feature, consider filing an issue to find out if support for your scenario can be added._

**Comment by Symbai** [comment]
> System.Text.Json was never intended to replace Newtonsoft.JSON for all scenarios

If you dont support polymorphic (de)serialization then the number of scenarios are extremely small makes me wonder why doing all the afford of creating it then? Its like you build a calculator and tell us "Hey this is a super fast calculator you should use for your mathematical operations" and on usage it turns out the calculator supports subtract, add, divide but not multiply. And on request you tell us "Well, it does not support multiply thats true. But our calculator was not supposed to calculate in every scenario 🤷‍♂️"

Using interfaces, abstract classes, and inherits is a huge part of .NET and its currently not supported, not even in .NET5. Its like a calculator which cannot multiply. And this is exactly how it feels like. I really hope this feature gets higher priority and perhaps a backport to .NET5.

**Comment by brunoalreis** [comment]
Is the future .net api's expected to not work by default and, the only solutions, are workarounds?

I start using .net core 1.1, then migrate to 2.1 and now I am migrating to 3.1. Of all migrations, this one is being a nightmare.
First I start with https://github.com/dotnet/runtime/issues/29932 problem. Ok, exists a workaround. Now this?

If System.Text.Json is still in development, I understand. But please don't make it the default serializer for api's. This is like creating a super engine that only work if it is a sunny day. In an OOP this must be possible.

Just sharing one of my **real world** scenarios:
My dashboard, has a list of widgets. I have many types of widgets, with different properties, but all widgets extends the Widget abstract class.

For the sake of simplicity:
`
public abstract class Widget{
  public decimal Height {...}
  public decimal Width {...}
}

public class Dashboard {
  List<Widget> Widgets {...}
}

public class Widget1: Widget {
  public string Widget1Data {...}
}

public class Widget2: Widget {
  public string[] Widget2Data {...}
  public OtherClass Widget2DataOther {...}
}
`

How can my api return the complete information of one dashboard, including widgets? Can't. Everything is broken. Have to use other workaround or .AddNewtonsoftJson(). Choosing last one for now.

Hope you change your mind. An if your going to make something important like this to be used by default, make it "for all scenarios". If not the default behavior, at least, make it optional. This is a must have, not a should have.

**Comment by ColinM9991** [comment]
Just chiming in to add my voice to the weight on one side.

I am sorry for saying so but this was a very poor design choice and it would be good if Microsoft could refrain from assuming what is wanted or needed of APIs and technologies that people use on a daily basis. JSON is at the very heart of hundreds of thousands, if not millions, of public APIs. 

There is a bit of a contradictory statement that System.Text.Json is not a replacement of Newtonsoft.Json yet all Microsoft documentation that I come across, around System.Text.Json, seems to enjoy pointing out the flaws and issues with Newtonsoft, which pushes people down a path of using System.Text.Json.

I read elsewhere (I believe the Microsoft docs) that polymorphic serialization is not supported because it 'leaks' information that shouldn't be leaked. Isn't that the purpose of `JsonIgnoreAttribute`? I shouldn't have to create a `JsonConverter<T>` or writer to clearly portray my intentions when OOP exists for that purpose.

**Comment by oliverjanik** [comment]
I'm writing a new service in .NET 5 and this issue is still present. 

I have a tree of objects with nested properties declared as interfaces. The serialiser just skips all of them, issues empty object.

What a nightmare, this is one of those instances where you can tell the disconnect between designers at Microsoft and real use-case scenarios.

I understand completely that polymorphic **deserialisation** is a tough problem. But polymorphic serialisation is a straight-forward decision.

**Comment by zachsaw** [comment]
It doesn't cost as much performance as you think it does, even with a binary serialiser that doesn't have the overhead of writing out UTF8 text like my [Binaron.Serializer](https://github.com/zachsaw/Binaron.Serializer) which supports polymorphism.

**Comment by jason-daly** [comment]
There should be a big disclaimer at the start of the System.Text.Json documentation, of "**Use at your own risk! The JsonSerializer doesn't do what you want, need, or expect. Does not support OO programming!**".

It is very lame of m'soft to not have resolved this weakness by now.

After several days of writing code to make use of System.Text.Json I discovered this fundamental flaw, and now have to rip out that code and go back to JSON.Net. Thanks for wasting my valuable and precious time.

I agree, don't make this the default json serializer in ASP.NET if it is not a fully functional json serializer.

Please don't reply with your lame excuses - not interested., This customer is right. Fix it.

**Comment by PureKrome** [comment]
@jason-daly At least you had the smarts to create a burner-github-account before you ranted at everyone on the internet.

Now, if you've can't be polite when you disagree, then please refrain from attacking people who are trying to be positive and do good for the community. There are Community Standards, here - like respecting each other.

**Comment by jason-daly** [comment]
> @jason-daly At least you had the smarts to create a burner-github-account before you ranted at everyone on the internet.
> 
> Now, if you've can't be polite when you disagree, then please refrain from attacking people who are trying to be positive and do good for the community. There are Community Standards, here - like respecting each other.

Don't be such a baby. Fix the problem!

**Comment by IanKemp** [comment]
The fact that somebody thought it was acceptable to ship STJ with this behaviour as a default **mind-blowing**. What's even more mind-blowing is that not only was a feature flag not provided to control this behaviour. What's yet more mind-blowing is that said feature flag hasn't been introduced yet.

It seems like every time I use STJ for even the most basic things, I run into yet another wall that Microsoft has artificially imposed for apparently no other reason than to make developers' lives unnecessarily more painful. What happened to the BCL being designed by competent architects, as opposed to clowns? But hey at least there's a doc: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism

jason-daly is right, there really is no excuse for this stupidity, and the time for being nice about it is long gone. Especially on such a basic issue that's coming up on two years old yet remains unaddressed.

**Comment by bklooste** [comment]
I used to think that OO should exist outside the memroy space and go onto a phycial medium. 

I have had issues with this with remoting , binary serializer , XML  and newtsoft etc .. I got smart and decided do not put this on the wire and avoid magic converters which does bad stuff for you  ( often poorly due expensive reflection based  instantiation) , I saved tons of money due to less bugs, easier to understand by other devs wwhat actually goes on and faster systems.  

Write a object to on DTO (wire object)  converter , seperate your responsabilities ( es SOLID) and save yourself a LOT of time and bugs .

I aplaud IMHO the smarter architects which tried to steer people away from this which can take people decades to discover.  Like immutable strings 20 years ago it can be controversional but i encourage people to keep going.

**Comment by qsdfplkj** [comment]
@bklooste so keep dto”s plain and simple. But now you have to solve the polymorphic mapping in the dto mappers.

**Comment by saithis** [comment]
> @bklooste so keep dto”s plain and simple. But now you have to solve the polymorphic mapping in the dto mappers.

yes, but this way you know exactly whats going on and don't rely on some mysterious magic that is hard to understand.

for us system.text.json works way better than newtonsoft json. the performance is so much better and we don't miss the magic.

**Comment by Symbai** [comment]
> for us system.text.json works way better than newtonsoft json. the performance is so much better and we don't miss the magic.

Then go ahead and move on. Stop commenting an OPT-IN feature request by **only** saying that you don't need it. Not only that you ping everyone who subscribes to it, which is **really** annoying, it's also completely redundant and helps no one. If you have the desire to tell the world about things you dislike, please use Twitter. If you have some constructive / technical feedback to share, you're welcome. FYI: This is not just you but also other people here, I just picked you because you are the last. Thanks in advance for yours and everyone else understanding and have a nice weekend.

**Comment by ColinM9991** [comment]
Any updates on whether this is being picked up in this lifetime? There are many issues like this that just seem to sit in limbo as updates to .NET Core and the surrounding ecosystem are pushed out.

**Comment by IanKemp** [comment]
> Any updates on whether this is being picked up in this lifetime? There are many issues like this that just seem to sit in limbo as updates to .NET Core and the surrounding ecosystem are pushed out.

The answer is invariably "no", since Microsoft's figured out that hype-driven development is the next big thing. As in they announce and ship a cool new feature that works for 80% of scenarios, then pretend it's complete and thus never finish the outstanding 20%. I was hoping that with James Newton-King joining Microsoft, STJ would gain parity with Newtonsoft.Json, but it seems that James has been tasked to work on other new features that will inevitably also be delivered incomplete.

**Comment by bklooste** [comment]
> @bklooste so keep dto”s plain and simple. But now you have to solve the polymorphic mapping in the dto mappers.

I think tagged unions on dtos have been around for decades  (used in Kernighan and Richie C )  and the performance difference between CreateType(type)  and new T() is massive.

switch ( dto.type)  new mytype  and setting some variables is a GOOD thing and the new c# features make this pretty,  its simple code someone whose picked the language up for a few weeks can do it that cant go wrong vs signficant complexity burried in a lib which goes wrong in complicate ways.. 

KISS, remove the magic.

**Comment by saithis** [comment]
> > for us system.text.json works way better than newtonsoft json. the performance is so much better and we don't miss the magic.
> 
> Then go ahead and move on. Stop commenting an OPT-IN feature request by **only** saying that you don't need it. Not only that you ping everyone who subscribes to it, which is **really** annoying, it's also completely redundant and helps no one. If you have the desire to tell the world about things you dislike, please use Twitter. If you have some constructive / technical feedback to share, you're welcome. FYI: This is not just you but also other people here, I just picked you because you are the last. Thanks in advance for yours and everyone else understanding and have a nice weekend.

What I wanted to say with my comment is, that I don't want this feature if it means worse performance. At the moment STJ and Newtonsoft.Json complement eachother nicely. STJ has top performance and Newtonsoft.Json has all the bells and whistles. Pick whats more important to you. 

If STJ gets feature parity, then the performance will most likely suffer immensely and we have essentially another Newtonsoft.Json. 

So if you need all the features, why not just use Newtonsoft.Json and be happy with it. If the performance isn't a problem for you, then it's a great choice.

I would like Microsoft to only implement new features for STJ, that don't sacrifice performance. We had some cases where Newtonsoft.Json took multiple seconds to serialize something and with STJ it is now almost instant. I don't want this problem back. Thanks.

**Comment by eiriktsarpalis** [comment]
## Proposed Design

Consider the following type hierarchy:
```csharp
public class Foo
{
    public int A { get; set; }
}

public class Bar : Foo
{
    public int B { get; set; }
}

public class Baz : Bar
{
    public int C { get; set; }
}
```
Currently, when serializing a `Bar` instance as type `Foo` the serializer will apply the JSON schema derived from the type `Foo`:
```csharp
Foo foo = new Foo { A = 1 };
Bar bar = new Bar { A = 1, B = 2 };
Baz baz = new Baz { A = 1, B = 2, C = 3 };

JsonSerializer.Serialize<Foo>(foo); // { "A" : 1 }
JsonSerializer.Serialize<Foo>(bar); // { "A" : 1 }
JsonSerializer.Serialize<Foo>(baz); // { "A" : 1 }
```
Under the new proposal we can change this behaviour by annotating the base class (or interface) with the `JsonPolymorphicType` attribute:
```csharp
[JsonPolymorphicType]
public class Foo
{
  ...
}
```
which will result in the above values now being serialized as follows:
```csharp
JsonSerializer.Serialize<Foo>(foo); // { "A" : 1 }
JsonSerializer.Serialize<Foo>(bar); // { "A" : 1, "B" : 2 }
JsonSerializer.Serialize<Foo>(baz); // { "A" : 1, "B" : 2, "C" : 3 }
```
Polymorphism applies to nested values as well, for example:
```csharp
public class MyPoco
{
    public Foo Value { get; set; }
}

JsonSerializer.Serialize(new MyPoco { Value = foo }); // { "Value" : { "A" : 1 } }
JsonSerializer.Serialize(new MyPoco { Value = bar }); // { "Value" : { "A" : 1, "B" : 2 } }
JsonSerializer.Serialize(new MyPoco { Value = baz }); // { "Value" : { "A" : 1, "B" : 2, "C" : 3 } }
```
Note that the `JsonPolymorphicType` attribute is not inherited by derived types. In the above example `Bar` inherits from `Foo` yet is not polymorphic in its own right:
```csharp
JsonSerializer.Serialize<Bar>(baz); // { "A" : 1, "B" : 2 }
```
If annotating the base class with an attribute is not possible, polymorphism can alternatively be opted in for a type using the new `JsonSerializerOptions.SupportedPolymorphicTypes` predicate:
```csharp
public class JsonSerializerOptions
{
  public Func<Type, bool> SupportedPolymorphicTypes { get; set; }
}
```
Applied to the example above:
```csharp
var options = new JsonSerializerOptions { SupportedPolymorphicTypes = type => type == typeof(Foo) };
JsonSerializer.Serialize<Foo>(foo1, options); // { "A" : 1, "B" : 2 }
JsonSerializer.Serialize<Foo>(foo2, options); // { "A" : 1, "B" : 2, "C" : 3 }
```
It is always possible to use this setting to enable polymorphism _for every_ serialized type:
```csharp
var options = new JsonSerializerOptions { SupportedPolymorphicTypes = _ => true };

// `options` treats both `Foo` and `Bar` members as polymorphic
Baz baz = new Baz { A = 1, B = 2, C = 3 };
JsonSerializer.Serialize<Foo>(baz, options); // { "A" : 1, "B" : 2, "C" : 3 }
JsonSerializer.Serialize<Bar>(baz, options); // { "A" : 1, "B" : 2, "C" : 3 }
```
As mentioned previously, this feature provides no provision for deserialization. If deserialization is a requirement, users would need to opt for the [polymorphic serialization with type discriminators feature](https://github.com/dotnet/runtime/issues/30083).

## Proposed APIs

```diff
namespace System.Text.Json
{
+    [AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
+    public sealed partial class JsonPolymorphicTypeAttribute : JsonAttribute
+    {
+        public JsonPolymorphicTypeAttribute() { }
+    }

+    public class JsonSerializerOptions
+    {
+        public Func<Type, bool> SupportedPolymorphicTypes { get; set; }
+    }
}
```

[Polymorphism Draft Design Document](https://github.com/dotnet/designs/pull/226)
[Prototype Implementation](https://github.com/dotnet/runtime/pull/53882)

**Comment by thomaslevesque** [comment]
@eiriktsarpalis thanks for the update. I generally like the proposed design. Just one thing: the name `SupportedPolymorphicTypes` is a bit misleading; it sounds like it's a list of types, when it's actually a predicate (I don't have a better idea right now, but I think it's worth trying to find a better name)

**Comment by eiriktsarpalis** [comment]
Thanks @thomaslevesque. I think you're onto something since I've already received the same feedback from someone else. For lack of a better alternative (`SupportedPolymorphicTypesPredicate`?) I'll let this be decided during API review.

**Comment by qsdfplkj** [comment]
How about deserialzing and and tree of foo’s where nodes can be any subtype.

**Comment by eiriktsarpalis** [comment]
@qsdfplkj the particular feature has no provision for deserialization. This is a simple feature intended at extending the simple brand of polymorphism that is currently possible with `object` values. It should only be used in scenaria where you are only interested in dumping all properties of a type hierarchy on the wire or where the deserializing process is dynamically typed.

Since it is not possible to roundtrip polymorphic values in nominal type systems without emitting some form of metadata on the wire, we are working on a separate feature that allows polymorphic deserialization using type discriminators (cf. #30083)

**Comment by qsdfplkj** [comment]
@eiriktsarpalis So far it seems you can do all of it with JsonSerializer.Serialize*<object>*(...) works. And for List<Foo> you either need to change it to List<object> or create a jsonconverter<List<T>> that calls JsonSerializer.Serialize(writer, value.Cast<object>().ToList());

**Comment by eiriktsarpalis** [comment]
This feature is orthogonal to #30083, which implements a different brand of polymorphism using type discriminators. Calling both features "polymorphism" is likely to confuse users who might expect the two API sets to be the same or compatible. They might reasonably expect that APIs serialized using this feature to be deserializable using APIs from #30083. We need to be careful about the names we pick so that they clearly illustrate that they are independent. Suggested names might include "Simple Polymorphism" or "Write-Only Polymorphism".

**Comment by qsdfplkj** [comment]
I think its not needed because I can write such code already but SerializeRuntimeTypes vs SerializeDeclaredTypes is what this is about.

**Comment by bartonjs** [comment]
API Review Feedback:

* We're concerned that the model as proposed is still too open for accidental data exposure, and so we recommend a "closed hierarchy" approach, similar to DataContractSerializer's known-types attribute.
  *  The "late-bound" doodle for this was `public Dictionary<Type, IEnumerable<Type>> PolymorphicSerialization { get; }`
* Given that the same closed hierarchy would apply to deserialization, we feel that the two should be reviewed together, and that a simplified serialization-only can be designed later... but not first.

**Comment by eiriktsarpalis** [comment]
Here is a sketch of a model that might accommodate both designs:
```csharp
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
public class JsonPolymorphicAttribute : JsonAttribute
{
    public JsonPolymorphicAttribute();
    public JsonPolymorphicAttribute(string typeDiscriminator);

    public string? TypeDiscriminator { get; }
}

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple = true, Inherited = false)]
public class JsonKnownTypeAttribute : JsonAttribute
{
    public JsonKnownType(Type derivedType, string typeIdentifier);
    public JsonKnownType(Type derivedType);

    public Type DerivedType { get; }
    public string? TypeIdentifier { get; }
}
```
Here's how a hierarchy that doesn't emit any metadata can be defined:
```csharp
[JsonPolymorphic]
[JsonKnownType(typeof(Bat))]
public class Goo { }
public class Bat : Goo 
{ 
    public int A { get; set; }
}

JsonSerializer.Serialize<Goo>(new Bat { A = 42 }); // { "A" : 42 }
```
And here's one that does:
```csharp
[JsonPolymorphic("_case")]
[JsonKnownType(typeof(Bat), "bat")]
public class Goo { }
public class Bat : Goo
{ 
    public int A { get; set; } = 42;
}

JsonSerializer.Serialize<Goo>(new Bat { A = 42 }); // { "_case" : "bat", "A" : 42 }
```

**Comment by eiriktsarpalis** [comment]
Given the API review feedback I'm going to close this issue in favor of  #30083, which will be revised to address both requirements.
