### ISSUE TITLE
Concurrency issue in TypeDescriptor.GetConverter(type)

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/runtime#30024]
`TypeDescriptor.GetConverter(type)` returns different results when calling on multiple threads with the same type and this `type` has a custom `TypeDescriptionProvider`.

This issue is reproducible with target frameworks `netcoreapp2.2` and `net472` on window 10 x64.

## Repro
I'm calling the method on 10 threads and print the fetched type converter at the end.

### Expected output
All 10 calls return `MyTypeConverter`

### Actual output
The method return both `TypeConverter` and `MyTypeConverter` in random order like the following:

```
TypeConverter
TypeConverter
TypeConverter
MyTypeConverter
TypeConverter
TypeConverter
TypeConverter
TypeConverter
TypeConverter
TypeConverter
```

The good thing is that the method is returning `MyTypeConverter` after the concurrent calls are finished. The bad thing is that there are libs (like newtonsoft.json) that are caching the type descriptors. If the cache of 3rd party lib is initialized with wrong descriptor then the application is broken until restart.

### Program.cs
```
public class Program
{
   public static async Task Main()
   {
      var tasks = new Task<TypeConverter>[10];

      for (var i = 0; i < tasks.Length; i++)
      {
         tasks[i] = new Task<TypeConverter>(() => TypeDescriptor.GetConverter(typeof(MyClass)));
      }

      foreach (var t in tasks)
      {
         t.Start();
      }

      foreach (var conv in await Task.WhenAll(tasks))
      {
         Console.WriteLine(conv.GetType().Name);
      }
   }
}

[TypeDescriptionProvider(typeof(MyClassTypeDescriptionProvider))]
public class MyClass
{
}

public class MyClassTypeDescriptionProvider : TypeDescriptionProvider
{
   public override ICustomTypeDescriptor GetTypeDescriptor(Type objectType, object instance)
   {
      return new MyClassTypeDescriptor();
   }
}

public class MyClassTypeDescriptor : CustomTypeDescriptor
{
   public override TypeConverter GetConverter()
   {
      return new MyTypeConverter();
   }
}

public class MyTypeConverter : TypeConverter
{
}
```

### .csproj-file
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>EXE</OutputType>
    </PropertyGroup>
</Project>
```

**Comment by eerhardt** [comment]
Moving to Future as this issue has been around for a long time and is not critical to fix in 7.0.

**Comment by ericstj** [comment]
Adding some links based on @stephentoub's analysis above.

The issue stems from this https://github.com/dotnet/runtime/blob/cfa42d32b45780c85a407b5dfde4bb7d30433da8/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L270-L281

Which allows a second caller to escape this function before the first thread's initialization completes.

My first thought was to hold onto the `s_internalSyncObject` longer - until the end of this method.  That would require us to also acquire that lock before the first check though - which could introduce a performance penalty in the initialized case.
https://github.com/dotnet/runtime/blob/cfa42d32b45780c85a407b5dfde4bb7d30433da8/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L265-L268

I don't think we'd want to introduce such a penalty - this code-path seems to have been intentional about avoiding a lock in the read case.

Perhaps a way to solve this, retaining the protection for recursion and avoiding a performance penalty (or another list) is to use a sentinel value during initialization - in addition to holding the initialization lock for the duration of the initialization phase.

So we can have `public static object s_initializingProvider = new object();`

We'll set this as the value for type instead of null during initialization.   When we check for the value outside the lock we'll only return if we get a value that is not the sentinel value.  If we find the sentinel value (or no value at all) we'll enter the lock and do the initialization.  Under the lock if we find any value (including the sentinel) we'd just return since it means we're either in the recursive case or some other thread completed initialization.

@stephentoub does this sound like it would work?  If so I can propose a PR.

**Comment by ericstj** [comment]
I just noticed that https://github.com/dotnet/runtime/pull/92521 was also trying to fix this by adding an extra hashtable.  That works, but I wonder if we can solve it with just a sentinel.  @karakasa can you have a read of my suggestion above and see if it makes sense?

**Comment by stephentoub** [comment]
> @stephentoub does this sound like it would work? If so I can propose a PR.

It's been a while since I looked at this, but at first glance your suggestion sounds viable.

**Comment by steveharter** [comment]
The sentinel pattern was applied new PR created: https://github.com/dotnet/runtime/pull/96846

**Comment by steveharter** [comment]
Long-standing threading issues in TypeDescriptor have been addressed, so any existing work-arounds can be removed. Workarounds included pre-populating internal caches such as by calling `TypeDescriptor.GetProvider(type)` for every type that has a `TypeProviderAttribute`, and by wrapping the access to the affected APIs with a `lock` statement.

Also see [TypeDescriptor.GetProperties(object instance) is not thread-safe](https://github.com/dotnet/runtime/issues/92394).

The threading issues also exist in .NET Framework. **If you are affected by this issue in .NET Framework, please add feedback to this blog or the issues above so we can determine the priority of porting the fix to .NET Framework.**
