### ISSUE TITLE
Enable Windows arm32 test builds and publishing

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#30021]
I want to enable coreclr repo CI to test corefx on Windows/arm32. This requires that the corefx official build generate and publish a build of the test assets, and corefx-test-assets.xml file manifest. This should be as easy as setting "_publishTests: true" for the Windows/arm32 case in eng\pipelines\windows.yml. However, it looks like Windows/arm32 isn't tested in the official build (why? It is a supported platform) so I presume the tests aren't built, either.

What needs to happen to make this work?

**Comment by safern** [comment]
@ViktorHofer @BruceForstall -- we started running libraries tests on coreclr in ARM32 a couple of weeks ago on rolling CI builds: https://github.com/dotnet/runtime/pull/35690

Should we close this issue now?

**Comment by BruceForstall** [comment]
Makes sense to me.

**Comment by ViktorHofer** [comment]
Before closing let's please validate that we actually test on arm32. It sounds like we are running tests against an arm32 version of the runtime but on arm64 hardware which makes me believe that we don't exercise anything arm32 specific. As an example, the tests were failing on arm32 hardware and we had to disable tests via ActiveIssue/SkipOnPlatform but never (fully) did that for all failing tests.

So what I would want to make sure of, before closing this issue is, that issues like https://github.com/dotnet/runtime/issues/30566 are actually fixed now and aren't just hidden because we don't run on arm32 hardware.

**Comment by safern** [comment]
We run on arm64 using WOW to run on arm32... I did have to disable some tests on arm32 when putting that PR... (FWIW coreclr runtime tests for arm32 use the same arm64 helix queue) cc: @jashook

**Comment by safern** [comment]
> So what I would want to make sure of, before closing this issue is, that issues are actually fixed now and aren't just hidden because we don't run on arm32 hardware.

I did a test run to the arm32 helix queue of libraries tests and indeed there are like 16 test assemblies with failures. We should disable those, open issues and switch to the right queue for libraries tests.

I believe runtime tests can't use that queue because of the payload size as it is very slow to download the workitems.

@MattGal and I looked at my private run and the workitems spent a few seconds downloading the payload, so it doesn't seem to be the case for libraries.

**Comment by BruceForstall** [comment]
@safern Where did you do the arm32 helix queue test? My change https://github.com/dotnet/runtime/pull/36486 has been running Windows arm32 testing, and there are still some un-triaged failures, but it's been using the /eng/pipelines/coreclr/templates/helix-queues-setup.yml file to set up the queues, so maybe that sets up a different helix queue than the libraries version?

**Comment by safern** [comment]
> /eng/pipelines/coreclr/templates/helix-queues-setup.yml file to set up the queues, so maybe that sets up a different helix queue than the libraries version?

Right now they setup the same queues. I did it locally in my computer by building for arm32 and sending a private test run to helix. Replicating what we do in CI. I used, `Windows.10.Arm32.Open` helix queue.

**Comment by safern** [comment]
Based on the conversation we had with @richlander this week, this shouldn't be required anymore. Closing.
