### ISSUE TITLE
GetCustomAttributes behavior is different when used as extension method

### ISSUE THREAD

**Issue by Evangelink** [dotnet/runtime#30219]
Hi folks,

When doing a PR for https://github.com/fluentassertions/fluentassertions/pull/1095 I have noticed a really strange behavior with `GetCustomAttributes` when using the `inherits` option.

Indeed this call `CustomAttributeExtensions.GetCustomAttributes(property, true).OfType<TAttribute>().Any()` returns `true` whereas `property.GetCustomAttributes(true).OfType<TAttribute>().Any()` returns `false`.

I have made a couple of tests and it seems that the bug happens only for `PropertyInfo` passed to the `MemberInfo` overload.

Given the following classes:

```csharp
[AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
internal class DummyPropertyAttribute : Attribute
{
}

internal class TestClassForPropertySelectorWithInheritableAttribute
{
    [DummyProperty]
    public virtual string PublicVirtualStringPropertyWithAttribute { get; set; }
}

internal class TestClassForPropertySelectorWithInheritableAttributeDerived : TestClassForPropertySelectorWithInheritableAttribute
{
}
```

This code doesn't work properly:

```csharp
Type type = typeof(TestClassForPropertySelectorWithInheritableAttributeDerived);

// Returns 1
var classicMethodCallCount = type.GetProperties()
    .Count(property =>
        CustomAttributeExtensions.GetCustomAttributes(property, true).OfType<DummyPropertyAttribute>().Any());

// Should return 1 but returns 0
var extensionMethodCallCount = type.GetProperties()
    .Count(property =>
        property.GetCustomAttributes(true).OfType<DummyPropertyAttribute>().Any());
```

Please let me know if this is not the good place to report this problem.

BTW I found this issue which seems more or less related dotnet/runtime#17180

**Comment by GrabYourPitchforks** [comment]
A little history behind this. Some frameworks didn't expose the instance method `MemberInfo.GetCustomAttributes(bool)`, so the extension method was added to account for this missing API. Since the extension method couldn't call `MemberInfo.GetCustomAttributes(bool)` - it was missing, after all - it had to do the next best thing and call `Attribute.GetCustomAttributes(MemberInfo, bool)`. As mentioned in https://github.com/dotnet/runtime/issues/30219#issuecomment-510395415, there is a subtle behavioral difference between these two methods. It's unfortunate that the behavioral difference is there since it could cause behavioral differences depending on what target framework you compiled against, but the behavior is established by now and I don't see us changing it at this time as it could break people.
