### ISSUE TITLE
Add an API to perform streaming transcoding

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#30260]
_(Edit by @GrabYourPitchforks: proposed API is in a comment at https://github.com/dotnet/corefx/issues/39483#issuecomment-557737022.)_

System.Text.Json specifically supports UTF8 inputs and outputs. MVC needs to support arbitrary user configured encoding schemes. To support this in a performant way, MVC has transcoding `Stream` implementations that minimally buffer inputs and outputs to the serializer.

Most of the work in these implementations is to perform state management when calling `Utf8.FromUtf16` \ `Encoders` * `Decoders`.  It would be great if these APIs were instead available as part of CoreFx.

**Comment by terrajobst** [comment]
* We'll likely need this ourselves for the `HttpClient` extension methods for JSON, so putting it in the BCL seems more reasonable than an ASP.NET/networking specific helper
* Instead of exposing a concrete type, we'd prefer a factory because we'll likely want to have dedicated implementations for specific encodings in order to speed things up.
* Putting the factory on `Encoding` seems most sensible because that's the array based helpers are too

```C#
namespace System.Text
{
    public partial class Encoding
    {
        public static Stream CreateTranscodingStream(Stream innerStream, Encoding innerStreamEncoding, Encoding outerStreamEncoding, bool leaveOpen = false);
    }
}
```

**Comment by scalablecory** [comment]
@GrabYourPitchforks I'd love a version of this API that checks for byte order marks; I know there are a few places in code we check for these. Something like:

```c#
public static Stream CreateTranscodingStreamFromBOM(Stream innerStream, Encoding fallbackInnerStreamEncoding, Encoding outerStreamEncoding, bool leaveOpen = false);
```

**Comment by GrabYourPitchforks** [comment]
@scalablecory If you don't mind go ahead and open a new issue tracking the BOM request. Since this issue is now closed I don't want your feedback to get lost!
