### ISSUE TITLE
Add a copy constructor to JsonSerializerOptions

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#30445]
(Edit by @Jozkee: proposed API is in a comment at https://github.com/dotnet/runtime/issues/30445#issuecomment-601979376)

MVC has a scenario where it needs to start with an existing options instance, modify a single property on a copy of it (the encoder) and perform serialization. In the absence of a copy constructor, we're at risk of missing out on newly added properties to the type.

## Proposed API
```cs
namespace System.Text.Json
{
    public sealed partial class JsonSerializerOptions
    {
        public JsonSerializerOptions(JsonSerializerOptions source)
        {
            /* Copy all options from source to a new JsonSerializerOptions instance. */
        }
    }
}
```

**Comment by Jozkee** [comment]
This should be very simple to implement and it could be very helpful since will allow our ASP.NET users to try-out preview features that need to be enabled from the options like `ReferenceHandling`.

## Proposed API
```cs
namespace System.Text.Json
{
    public sealed partial class JsonSerializerOptions
    {
        public JsonSerializerOptions(JsonSerializerOptions source)
        {
            /* Copy all options from source to a new JsonSerializerOptions instance. */
        }
    }
}
```

cc @steveharter @layomia @terrajobst

**Comment by steveharter** [comment]
> /* Copy all options from source to a new JsonSerializerOptions instance. */

The state on the option instances can diverge after a clone so we need to ensure they don't contaminate eachother by sharing caches (the `JsonClassInfo` cache) or a direct reference to the converter list. Sharing caches can result in threading\concurrent issues and sharing the converter list reference can result in incorrect semantics.

For the clone, we should only add the converters that were manually added via `options.Converters.Add()` which is only allowed before the first (de)serialization. This means we need to track them in some way -- I recommend storing the index of the converter list when we (de)serialize for the first time, and during a clone only add the converters up to that index (and ensure we set the index for the newly created options so a second clone will do the correct thing as well).

The reason is that some converters (e.g. `NullableConverterFactory<T>`) during (de)serialization will get the underlying converter for `T` and pass it to a child converter (`NullConverter<T>`) which will cache the reference to the underlying converter. That underlying converter is obtained by the options instance through `GetConverter()` which could change across different option instances (if cloning occurs before the first serialization occurs where the converter list is still mutable). So we don't want to cache every converter in the list, just the ones manually added via `Add`.

**Comment by terrajobst** [comment]
* Looks good
* This will only copy settings, no cache information
* Converters that were added automatically (e.g. factories) should not be copied.

```C#
namespace System.Text.Json
{
    public sealed partial class JsonSerializerOptions
    {
        public JsonSerializerOptions(JsonSerializerOptions source)
        {
            /* Copy all options from source to a new JsonSerializerOptions instance. */
        }
    }
}
```

**Comment by ahsonkhan** [comment]
Also capturing another note: The copied option that is returned should be "unlocked" and the user should be able to modify it until the first serialization occurs (regardless of whether the original option was locked or unlocked).
