### ISSUE TITLE
Consider supporting byte arrays in JsonValueConverterByteArray

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#30456]
Consider:

```
var json = "[1, 2, 3, 128]";
```

Deserializing this as a byte[] currently fails since the `byte[]` converter expects a base-64 encoded string:

```
JsonSerializer.Deserialize<byte[]>(json);

Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Byte[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetBytesFromBase64(Byte[]& value)
   at System.Text.Json.Utf8JsonReader.GetBytesFromBase64()
   at System.Text.Json.Serialization.Converters.JsonConverterByteArray.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
```

While reading, the converter could be modified to support an actual array type:

```C#
if (reader.TokenType == JsonTokenType.StartArray)
{
    // Read as byte[]
}
else
{
    return reader.GetBytesFromBase64();
}
```

Serialization can remain the same as users are free to change the behavior if they want a different format.

**Comment by layomia** [comment]
A custom converter can be written for this. We can reopen if there's more customer demand.

**Comment by infacto** [comment]
JSON (JavaScript Object Notation) only has one number type. The equivalent in C# is `byte` or `sbyte` or `short` or `ushort` or `int` or `uint` or `long` or `double`, etc. It's a question of bit length. A `byte[]` is not always binary data. For the communication to JavaScript we expect `byte[]` as `number[]`. Now we have to write a lot of code and confuse our developers and reviewers because of this base64 issue. It's a nice idea to convert binary data to base64. It's good for a `Blob`, `Buffer` or other binary data. Also maybe for `byte[]`. But not as default value. This should be an option (globally or locally) to `System.Text.Json.JsonSerializer`. In my case I just have to transmit 8 bytes. I don't want casts, CustomSerializer or other special implementations for a `number[]` type.

```cs
class JsonData {
  public uint id { get; set; }
  public byte[] data { get; set; }
}
```

json: `{ id: 42, data: [ 1, 2, 3, 4, 5, 6, 7, 8] }`

Again, the `base64` conversion is a nice idea. But it should be a simple option without any hassle. 

@layomia

**Comment by nvmkpk** [comment]
This issue is preventing me from sending byte array across javascript interop in my blazor application. Javascript's `atob` does not deserialize it correctly.

**Comment by AceHack** [comment]
How do you write a custom converter for byte arrays?  That's not clear to me.

**Comment by khellang** [comment]
@AceHack You write it like the built-in one;

https://github.com/dotnet/runtime/blob/4a4e347b964a2c8d2216ec382e4fb481965bb2fc/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/ByteArrayConverter.cs#L7-L18

**Comment by izzycoding** [comment]
I am currently seeing issues with byte[] conversion.
In the built-in ByteArrayConverter what is the expected json output?
When I serialise a byte[] i am seeing the value as an array of ints.
I have also created my own converter and assigned it to my property using the JsonConverterAttribute and it appears it never gets called.
How can I find out why this is not converting as expected?

**Comment by ahsonkhan** [comment]
> I have just re-run my code and it would appear my custom converter is being called for deserialisation, but not for serialisation.
Unsure why this is happening as the JSON handling is part of web api controller implementation and there is certainly not any difference in the JsonSerilazationOptions being used.
Why with the same options are there different converters being used for reading and writing?
Especially as I am specifically targeting my custom converter using the attribute.

Please file a new issue and provide a simplified repro of the incorrect behavior you are seeing, along with the model you are trying to serialize.

You will have better luck getting attention to it that way.
https://github.com/dotnet/runtime/issues/new/choose
