### ISSUE TITLE
Unseal JsonStringEnumConverter

### ISSUE THREAD

**Issue by josundt** [dotnet/runtime#30486]
## Background and Motivation

`JsonStringEnumConverter` can be configured using a couple of parameters. But since the type is marked sealed, it can be awkward to configure when applied via the `JsonConverter` attribute, leading to awkward workarounds [like this one](https://github.com/dotnet/runtime/issues/54187#issuecomment-861400912).

## API Proposal

```diff
namespace System.Text.Json.Serialization
{
-    public sealed class JsonStringEnumConverter : JsonConverterFactory
+    public class JsonStringEnumConverter : JsonConverterFactory
    {
        public JsonStringEnumConverter() { }
        public JsonStringEnumConverter(JsonNamingPolicy? namingPolicy = null, bool allowIntegerValues = true) { }
-        public override bool CanConvert(Type typeToConvert) { throw null; }
+        public sealed override bool CanConvert(Type typeToConvert) { throw null; }
-        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options) { throw null; }
+        public sealed override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options) { throw null; }
    }
}
```

## Risks

Unsealing public types is generally not considered a breaking change. It might break reflection in the hypothetical scenario where a user depends on the result of `typeof(JsonStringEnumConverter).IsSealed`.

<details>
<summary>
 Original proposal by @josundt  (click to view)
</summary>
In our APIs, we serialize most enums as strings (no case conversion) since string enums make APIs more self-explanatory, but for **flag enums** we serialize with the numeric value since strings would prevent bitwise flag enum operations. 

With NewtonSoft.Json, we accomplished the described serialization behavior by creating our own converter that inherited from NewtonSoft's `StringEnumConverter`.

This would have been possible and even easier with System.Text.Json, if only the `JsonStringEnumConverter` class was not **sealed**.

If it was not sealed, I could have done this simply by overriding the `CanConvert` method like below:

```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MyNamespace
{
    public class JsonStringEnumNumericFlagConverter : JsonStringEnumConverter
    {
        public JsonStringEnumNumericFlagConverter()
            : base() {}

        public JsonStringEnumNumericFlagConverter(JsonNamingPolicy namingPolicy = null, bool allowIntegerValues = true)
            : base(namingPolicy, allowIntegerValues) {}

        public override bool CanConvert(Type typeToConvert)
        {
            return typeToConvert.IsEnum
                && typeToConvert.GetCustomAttributes(typeof(FlagsAttribute), false).Length == 0;
        }
    }
}
```

Can you please make this extensibility point available ("un-sealing" the class)?
</details>

**Comment by layomia** [comment]
Closing - there's a workaround.

**Comment by eiriktsarpalis** [comment]
Reopening following conversation from #54187.

**Comment by eiriktsarpalis** [comment]
>> @steveharter, @JeremyKuhne why was this type sealed?
>
> This was done for performance

How so? The public type itself is a converter factory so any perf impact would probably only impact the initial converter generation.

**Comment by JeremyKuhne** [comment]
> How so? The public type itself is a converter factory so any perf impact would probably only impact the initial converter generation.

It was a general API best practice. Virtuals make it harder to change internal implementation details- when something can't be derived we can make assumptions and/or take shortcuts we can't otherwise do when we're sealed. `FileStream` comes to mind as a concrete example of where we suffered for it not being sealed (being forced to call methods such as `ReadByte() `that weren't strictly necessary as derived classes _might_ depend on it).

Your factory point is valid, of course, and the team can certainly decide to unseal this if it is felt to give significant value.

**Comment by eiriktsarpalis** [comment]
Good point about changing virtuals; I have updated the OP so that virtual members are explicitly sealed.

**Comment by layomia** [comment]
Since the motivating scenario behind unsealing this type is to effectively pass state through it's constructor when using `JsonConverterAttribute`, I just want to point out that [`JsonConstructorAttribute`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonconverterattribute?view=net-5.0) is unsealed and exposes a virtual [CreateConverter](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonconverterattribute.createconverter?view=net-5.0) method which allows users to create converter instances using parameterized ctors. Here's an example in our [tests](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/CustomConverterTests/CustomConverterTests.Attribute.cs#L10-L31). It is an imperative approach, whereas attribute usages are usually declarative, but I thought it was worth mentioning.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Text.Json.Serialization
{
    // Unsealed
    public class JsonStringEnumConverter : JsonConverterFactory
    {
        // Existing:
        // public JsonStringEnumConverter();
        // public JsonStringEnumConverter(JsonNamingPolicy? namingPolicy = null, bool allowIntegerValues = true);

        // Existing methods, now sealed
        public sealed override bool CanConvert(Type typeToConvert);
        public sealed override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options);
    }
}
```
