### ISSUE TITLE
Add API for detecting broken pipe when write to stdout(or stderr)

### ISSUE THREAD

**Issue by itn3000** [dotnet/runtime#30540]
currently, corefx's `System.Console.Out` implementation is ignoring broken pipe, just pretend to success.(due to dotnet/runtime#15587)
* [Windows impl](https://github.com/dotnet/corefx/blob/82e64c6cec3f0bb6a5a98b6c1bddc568f0ab61c8/src/System.Console/src/System/ConsolePal.Windows.cs#L1211-L1217)
* [Unix impl](https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Console/src/System/ConsolePal.Unix.cs#L1252-L1257)

This behavior is sometimes inconvenient when work together with some command like `head` command.
if dotnet command output is very long, there is no easy way to stop program if command which follows after pipe stop (except using native API, but it is sometimes very difficult).

So, I want the API to detect whether stdout(and maybe stderr) is broken.

**Comment by adamsitnik** [comment]
Triage: I don't believe that we can provide reliable API for this feature request. To check whether pipe is broken, we would need to perform a write. Writing 0 bytes has a special meaning (https://github.com/dotnet/runtime/issues/81053), so writing 0 bytes is not an option. Changing the behavior to always throw in such cases is also not an option, as it would break plenty of apps (especially those which are printing to console while the process is shutting down).

Since there was only one up-vote, the best I can do right now is to provide a workaround:

```cs
static void Workaround(string text, out bool brokenPipe)
{
    Console.Write(text);
    brokenPipe = Marshal.GetLastWin32Error() == (OperatingSystem.IsWindows() ? 0x6D : 0x10043);
}
```
