### ISSUE TITLE
EnvironmentVariable operations with EnvironmentVariableTarget.User fails on Windows Nano Server

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#30566]
This seems to be a product bug because of an underlying windows api change.

cc @Anipik @stephentoub @danmosemsft

**Comment by danmosemsft** [comment]
Not blocking release of 5.0 product

**Comment by MichalStrehovsky** [comment]
I'm trying to bring up checked legs for the NativeAOT runtime and running into the same assert this is tracking (#79847). I don't believe it's NativeAOT specific because it only happens on Nano server. My theory is that we just don't have any test legs that would detect this with CoreCLR anymore.

I'm going to disable the entire System.Runtime.Extensions suite on the checked legs because I've already spent too much time on this 3.5 year old known bug. It would be nice if this got attention from the maintainers in 8.0.

**Comment by jkotas** [comment]
> My theory is that we just don't have any test legs that would detect this with CoreCLR anymore.

We do not have a leg that runs libraries tests on Windows Nano Server as admin with checked CoreLib. NativeAOT happens to have some coverage for this specific config by accident.
