### ISSUE TITLE
API suggestion: Provide an overload of float/double.ToString that allow precision greater than 99

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#30657]
At the moment, there is no way to specify precisions greater than 99 when using standard format specifiers. This is because the specifiers only allow no numbers, or numbers that are less than two digits (inclusive). Numbers bigger than that will result in rather unexpected ways, as it is recognised as custom format specifiers.

For example: `10f.ToString("G100")` returns "G110", format: "G999" returns "G999", `double.MaxValue.ToString("G308")` returns "G3179769313486232000000000"............"000000" etc. This can be confusing as many are not aware of such facts, and leaves no way of obtaining precise strings except implementing the ToString ourselves manually.

Unfortunately, allowing interpretation of such strings would be a breaking change, since it changes the behaviour of ToString. 

One way to solve this could be to add an overload that accepts a `char` and `int`, the `char` for format and `int` for the desired precision.

```cs
public struct Single
{
    public string ToString(char format, int precision);
}
```

\* Wonder if similar overload of `TryFormat` would be nice to have as well?

**Comment by terrajobst** [comment]
* There are issues with supporting more thant 99 digits of precision, some are in parsing behavior as pointed out by the OP, some of them are in public data structures which are size limited, and some are likely in the implementation.
* Normally, it would seem better to extend the existing format specifier because it works better with resource strings and localization
* However, given that production code is very unlikely to ever use more than 99 digits, it seems acceptable to have separate overloads to override the precision for debugging purposes. 

```C#
namespace System
{
    public struct Single
    {
        public string ToString(char format, int precision);
    }
    public struct Double
    {
        public string ToString(char format, int precision);
    }
}
```

**Comment by terrajobst** [comment]
* It was suggested to add support for custom cultures. New shape:

```C#
namespace System
{
    public struct Single
    {
        public string ToString(char format, int precision);
        public string ToString(char format, int precision, IFormatProvider? provider);
    }
    public struct Double
    {
        public string ToString(char format, int precision);
        public string ToString(char format, int precision, IFormatProvider? provider);
    }
}
```

**Comment by Gnbrkm41** [comment]
Was alteration of the existing format specifier also considered as well? just curious, because it would be a neater solution if it's possible - I'm just not sure if it holds more value than the cost of it being technically a breaking changen although I don't think people would actually do something like `dbl.ToString("D123")` to print the thing, when one could already do that without all the ToString things. The value is fairly weak at the same time as well because scenarios requiring more than 99 digits is uncommon.

**Comment by tannergooding** [comment]
There was a lot of oddities in how custom format strings worked and it has a much greater risk of breaking some existing code, even if accidentally.

**Comment by Gnbrkm41** [comment]
I can put up a PR for this.

Question: Do we want to enforce a limit on what kind of values are supported for the precision? I think the longest output is something like 308 digits, and I'm not sure what we should do for anything above 308. Just pad it with 0s?

**Comment by Gnbrkm41** [comment]
Also.... how about new overloads of TryFormat? it's definitely nice to have and provides some flexibility in high performance scenarios.

Feels weird that we're not doing it even though we are adding those TryFormat APIs everywhere to give people a choice.

**Comment by Gnbrkm41** [comment]
...And, what for invalid / unsupported format specifiers? the default behaviour with the string based overloads would have been to just treat it as a custom format specifier, but I don't think it applies here...

**Comment by tannergooding** [comment]
> I think the longest output is something like 308 digits, and I'm not sure what we should do for anything above 308. Just pad it with 0s

It should work like it does today, which is that it may just cap at whatever the actual digit count is (but the exact behavior depends on the format string). The actual max is 112 digits for float and 767 digits for double.

> Also.... how about new overloads of TryFormat? it's definitely nice to have and provides some flexibility in high performance scenarios.

I think we can bring that forward in a separate proposal. The scenario of producing a fully qualified string is already fairly rare and is largely useful for diagnostic purposes so I'm not quite convinced having a `Span<char>` API is necessary from day 1.
However, the actual implementation is trivial since it just forwards to the generic implementation that can handle any digit count, so I would be fine with taking it forward in a separate proposal.

> ...And, what for invalid / unsupported format specifiers? the default behaviour with the string based overloads would have been to just treat it as a custom format specifier, but I don't think it applies here...

It will throw, as is already the case today: https://source.dot.net/#System.Private.CoreLib/Number.Formatting.cs,508

**Comment by tannergooding** [comment]
As per https://github.com/dotnet/runtime/issues/46440#issuecomment-758863444

Due to the additional locations that may require more than 99 digits, the API review team wants to look at making the breaking changes to the parser instead.
