### ISSUE TITLE
[Api Suggestion] Add System.Text.Xml

### ISSUE THREAD

**Issue by JustNrik** [dotnet/runtime#30718]
Just as we got System.Text.Json, we should have a high-performance low-allocation XmlSerializer, which could support as well XPath, Linq2Xml and such. It could even allow non-closing tags for HTML parsing

**Comment by deeprobin** [comment]
I don't know if you are the right one to tag here: @danmoseley. But I think such an API is very useful. 
Even if most WebAPIs and high-performance applications use gRPC and JSON, XML is still often used today (APIs of some governments, SOAP APIs, ...).

I think a new Xml API in a similar architecture as System.Text.Json makes a lot of sense (and must be more performant than System.Xml). 

Do you think this could be taken on the plan for .NET 8?

**Comment by danmoseley** [comment]
> Do you think this could be taken on the plan for .NET 8?

As mentioned above, this area has different owners than the folks you @-mentioned here.

As a general observation @deeprobin, not specific to XML serialization, when an issue proposes a new major investment of some sort, it is not meaningful to ask "do you think this could be taken on the plan". Such an issue just forms the start of a possible discussion. Bear in mind that high performance serializers are very expensive: System.Text.Json has absorbed many developer years: it required deferring other possible work of the same size. We are missing data such as -- is there substantial evidence of a widespread need? are there reasonable alternative ways of achieving the goal? why does this need to be in core platform? what work would not happen if we did such work?

**Comment by deeprobin** [comment]
@danmoseley 
You're right, it would be a very big project.

Nevertheless, I think that we can achieve significant added value through it.

Alternatively, we could plan a general serializer for SGML-derived (System.Text.Sgml) on which we could then build System.Text.Xml.

I would go for an XML API for now:
XML will always/for a long time be part of applications that require at least a relatively good performance.
I think an example is XAML, which is used in MAUI, WPF and WinUI.
A more general example (which is not specific to the .NET world) are SVGs.
In many apps SVG graphics are used to render size independent graphics. Not only the rendering process is an expensive step but also the parsing of the XML based SVG file.

In today's Internet, XML is also used for SOAP requests/responses (although these are usually replaced by REST APIs or even gRPC in the long run).

Also SDMX 2.1 uses XML and for this often a good performance is important. Since many governments/banks provide such interfaces and often the actuality of the data (e.g. currency rates) is crucial.

As far as I know even Microsoft Office (@OfficeDev) uses a lot of System.Xml via .NET FX and there might be an interest (if planned to move to .NET Core in the long run) for this API.

There are many more use cases but I think these are the most important ones for now.

Many have the impression that XML is dead. It isn't. And it won't be, as there are still current use cases for it. Even if the trend is towards JSON, JSON is not a panacea either.

---

Also to be mentioned is that an XML parser will never achieve comparable performance to JSON, since JSON has a leaner syntax. But in my opinion a much higher performance can be achieved even with a new API shape.

---

I look forward to hearing more opinions.

---

Other interesting articles about this:

* [Medium: Who Marks Data Better - XML or JSON](https://medium.com/geekculture/who-marks-data-better-xml-or-json-86d07d60dced)
* [Wikipedia: Simple Object Access Protocol](https://en.wikipedia.org/wiki/SOAP)

**Comment by StephenMolloy** [comment]
From the 'area-Serialization' owner standpoint... something like this would be quite a large project and we just don't have anywhere near the resources to tackle it. Xml is quite a bit more expressive than Json which complicates things. I'm going to move the area tag to Runtime (the folks who did System.Text.Json I believe) in case they want to chime in. But this isn't something that my team has the ability to handle currently.

I would note however that we do still have XmlSerializer and DataContractSerializer. Both have languished a bit, and as @danmoseley said - XML is not really an area of tech with rapid changes at the moment, but they are not dead. We are currently making a big push to bring DCS up to par with 4.8. And there are pretty substantial plans to improve the efficiency of XmlSerializer in the future as well - probably not .Net 7, since that's coming up faster than our small team can manage. But the point is that we are still investing in the Xml serializers that already exist.

**Comment by stephentoub** [comment]
As noted, we have no plans to create a brand new set of APIs here. Obviously anyone else interested in investing in their own new library and sharing it on nuget is able to do so. Thanks.
