### ISSUE TITLE
API Proposal: SequenceReader<T>.TryRead overloads to read a specified number of elements

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#30778]
The use case is to return a contiguous `ReadOnlySpan<byte>` or a `ReadOnlySequence<byte>` the current position.

```C#
public partial ref struct SequenceReader<T>
{
    bool TryRead(int count, out ReadOnlySpan<T> value);
    bool TryRead(int count, out ReadOnlySequence<T> value);
}
```

One use case for this type of method is length prefixed network protocols e.g.

```C#
void Parse(ref ReadOnlySequence<byte> buffer)
{
    var reader = new SequenceReader<byte>(buffer);
    // Read the length prefix, then read the payload
    if (!reader.TryReadBigEndian(out int length) || !reader.TryRead(length, out ReadOnlySequence<byte> payload))
    {
        return;
    }
    
    ProcessPayload(payload);
}
```

**Comment by terrajobst** [comment]
* The first API will have to allocate when `count` causes spanning blocks in the sequence. The bigger the `count`, the more likely it is to cross such a boundary. This could be changed to allow the caller to pass in a pre-allocated span or we could change the semantics to only succeed if the data is available contiguously.
* We should change the name to `TryReadExact` to make it clear that returning less or more is both not possible.

```C#
public partial ref struct SequenceReader<T>
{
    bool TryReadExact(int count, out ReadOnlySequence<T> value);
}
```

**Comment by reflectronic** [comment]
We talked about this API (and some others) more in https://github.com/dotnet/runtime/issues/30807#issuecomment-553204267. Specifically, we discussed putting the `out` parameter first (as it is on every other SequenceReader API), and also renaming `value` to `sequence`. For the sake of having a congruent API surface, that should probably be done for this API.

On the topic of the Span overload, I think that keeping the overload is also important for having a congruent API surface. There are existing APIs like [`TryReadTo`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1.tryreadto?view=netcore-3.1#System_Buffers_SequenceReader_1_TryReadTo_System_ReadOnlySpan__0____0_System_Boolean_) and [`TryReadToAny`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1.tryreadtoany?view=netcore-3.1#System_Buffers_SequenceReader_1_TryReadToAny_System_ReadOnlySpan__0___System_ReadOnlySpan__0__System_Boolean_) that take both Span and Sequence overloads; it would be strange/annoying to have a new API, which is similar in purpose to the existing ones, but with no Span overload "because reasons." 

Of course, having some type of alternative which doesn't necessarily allocate is useful, especially since the buffer size can be much more predictable. But I think that the matching APIs should be added for this method, and likewise anything new we come up with should be added to `TryReadTo`/`TryReadToAny`/`TryPeek`/etc.

**Comment by tannergooding** [comment]
Moved this to future and marked as up-for-grabs. @davidfowl if this is needed for 6.0.0, please let us know.

**Comment by davidfowl** [comment]
This is fine for .NET 7

**Comment by lateapexearlyspeed** [comment]
Hi, I would try and learn this. I have raised draft [PR ](https://github.com/dotnet/runtime/pull/57921)and will change its status when it is ready for review, thanks !

**Comment by lateapexearlyspeed** [comment]
[PR ](https://github.com/dotnet/runtime/pull/57921)is ready for review now, please review, thanks.
