### ISSUE TITLE
Remove [DisallowNull] from EqualityComparer.GetHashCode

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#30998]
Visual Studio 16.3.1 generates code like this for GetHashCode specifically because this way the null check is handled. EqualityComparer.GetHashCode is well-known to return 0 if you pass null:

```cs
struct Foo
{
    public string? Bar { get; }

    public override int GetHashCode()
    {
        // CS8604 Possible null reference argument for parameter 'obj' in
        // 'int EqualityComparer<string?>.GetHashCode(string? obj)'.      ↓
        return 1739646154 + EqualityComparer<string?>.Default.GetHashCode(Bar);
    }
}
```

Rather than generating a `!` to go along with it, could `[DisallowNull]` be removed from `EqualityComparer<>.GetHashCode` as a kind of contravariance, even though `IEqualityComparer<>.GetHashCode` has it? It would reflect the true behavior of the `EqualityComparer<>` class.

**Comment by EamonNerbonne** [comment]
I just ran into this issue, and as a consumer of this code, the nullability annotations of IEqualityComparer really surprised me; it's not intuitive at all for Equals and GetHashCode to permit differing input.

In fact, I struggle to think of any comparer that can reasonably throw from GetHashCode but not Equals.  IEqualityComparer docs state - and for fundamentally necessary reasons - that *"Implementations are required to ensure that if the Equals(T, T) method returns true for two objects x and y, then the value returned by the GetHashCode(T) method for x must equal the value returned for y.  The Equals(T, T) method is reflexive, symmetric, and transitive."* 

Since it's reflexive, Equals(null, null) should return true (or fail to return, but the docs don't permit exceptions here).  But if `Equals(null, null)` returns true, then consumers may assume `GetHashCode(null)` returns a value equal to the value `GetHashCode(null)`.  That may seem inane, but of course you'd never literally right code like that, you'd see code calling gethashcode on variables that happen to be null at runtime.  Needing to check for null specifically is simply a nasty gotcha for no particularly good reason.

Additionally - yes, it appears impolite to allow nulls given the existence of implementations written before the change, that may assume it's OK to throw when passed null. However, there is likely also existing code that assume's it's OK to pass null, simply because bar some exceptions common equality comparers do allow null.  But even if it's impolite - code isn't going to stop working just because of an annotation or docs change; changing the nullability spec here shouldn't actually break code (outside of niche cases with warnaserror and the like - and even there, the fix is purely one of annotation).

As a consumer of libs, I'd much rather you break compatibility on trivial things like this, that keep around cruft for no functional reason; it's just much easier to reason about a good API than to know all the gotchas.  And some backwards compatibility hacks may unfortunately be necessary - this particular case is purely compile time; no code will suddenly behave different.  Such breaking changes have occurred regularly in .net, and I hope you consider - given the really limited scope of breakage - that OK here too.

Finally - exceptions specifications aren't typechecked in C# (nowhere in .net?).  It's entirely normal to find interface implementations that throw all kinds of things the interface does not describe in the docs.  Having a legacy implementation choose to throw ArgumentNullException while the interface does not spec that does not seem to be out of the ordinary (and avoiding that exception if you do have the option of updating the code should be likely trivial).

So **TL;DR:** 1 anecdote for this interface specification being confusing, and some arguments why I don't believe changing it will hurt many codebases, nor any very much.

**Comment by sharwell** [comment]
This contract is continuing to place a large burden on consumers of this API. The attribute on this parameter is causing the C# compiler's flow analysis to incorrectly consider argument validity for equality comparers of nullable types.

**Comment by stephentoub** [comment]
It is the contract. Implementations/overrides throw for null. We can't just wish that away.

**Comment by sharwell** [comment]
The contract was written before Nullable Reference Types was a language feature, and forcing the attribute is overriding what would have otherwise been a correct interpretation of this API by the compiler. I have an API that needs to accept `IEqualityComparer<object?>` (as opposed to `IEqualityComparer<object>`), but it's producing two problems:

1. I have to put a suppression on each use of `GetHashCode`, because the attribute causes `object?` (the correct type) to get treated as `object` (not the correct type)
2. The compiler allows an implementation of the argument to this API to omit required handling for `(object?)null`. This is not valid for this API, and when it gets called by the library it will throw.

**Comment by EamonNerbonne** [comment]
> It is the contract; the attribute is just reflecting what is already the case. Implementations/overrides throw for null. We can't just wish that away.

The contract *allows* for that.  But any implementation that does so violates the reflexivity, so it's arguable the contract doesn't really allow for it at all.  Furthermore, the contract is purely textual; this isn't some fixed interpretation, there are multiple perspectives.  There is no one clear technically correct contract.

But more critically, the currently nullability annotations pretty much *require* the consumer to assume non-reflexivity.  Even if there is some wish to *allow* non-reflexive null-unsafe legacy implementations due to history, there should not be a wish to enshrine that in the future, yet that's exactly what the current annotation does.  The current annotation does *not* allow null-safe implementations to be reflexive and compiler checked, which should be a major no-no.  If the argument is that old implementation might throw and thus `DisallowNull` is needed; well, that holds for pretty much *every* BCL interface method, regardless of contract, yet annotations were not applies based on possible implementations, but on reasonably intended usage.

That should be the goal here too, and thus the requirement for reflexivity should weigh more heavily than possible legacy non-nullability annotated null-unsafe implementations.  Compared to the major codebase upheaval nullability checks caused; changing this is peanuts; it's hard to argue introducing nullability was OK in the first place yet we can't fix this.

**Comment by stephentoub** [comment]
> The contract allows for that.

Yes, and many implementations throw exceptions when passed null, both in the framework itself and external to the framework.  Regardless of nullability contracts, any API that accepts an `IEqualityComparer<T>` needs to be prepared for that and assume that GetHashCode doesn't allow for null.  That has always been the case, and it's why APIs like `HashSet<T>` check for null before invoking GetHashCode:
https://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSet.cs,1522
The introduction of nullable contracts for such an existing API needs to reflect that reality.  If this was a closed system, with all implementations in the framework itself, then we could potentially update all implementations and make the contract more flexible.  But that is not reality.  If we were to change the contract now, code written against `IEqualityComparer<T>` would assume that it could call GetHashCode without checking for null, and would encounter problems for many existing implementations of this long-standing API.  I do not see a viable path to changing it, no matter how much we may wish it had been defined differently 15 years ago.

**Comment by stephentoub** [comment]
> that holds for pretty much every BCL interface method

Yes, it does, and we've held true to that in almost every case.  The only times we haven't are when the chance that it would cause a problem in reality are super small.  That is not the case here.

**Comment by CyrusNajmabadi** [comment]
This goes to philosophy.  Should NRT match teh docs, or match teh impl.  With TS we went with the latter.  We would prefer false negatives versus false positives for things like this.  It does mean you might not get an NRT warning when an NRT can happen.  But that's *known* and acceptable as part of the NRT design.  

Literally how we designed it when analyzing the language is to look for patterns and apply some heuristics about how we *hope* it will behave.  There is no actual safety here, and we can mark patterns as safe even if they will actually end up throwing at runtime.  The idea is to benefit the majority of users for the majority of coding patterns.

I think that should apply here.   NRT should not be used for the conservative view, it should be used for the optimistic view on this.  NRTs will still leak through, but that's ok since stopping all null-refs is not the goal of the feature.  The goal is to bring my attention to the *likely areas of concern*, so i get the best bang for buck in terms of addressing potential problems.

**Comment by stephentoub** [comment]
> Should NRT match teh docs, or match teh impl.

It matches both.  The docs say it can throw, implementations throw:
https://github.com/dotnet/runtime/blob/34728a5866be7aa5c27e7fffc4ab52a1e4e07cb7/src/libraries/System.Private.CoreLib/src/System/StringComparer.cs#L107-L112
and implementations avoid calling GetHashCode because it may throw:
https://github.com/dotnet/runtime/blob/34728a5866be7aa5c27e7fffc4ab52a1e4e07cb7/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs#L215

**Comment by EamonNerbonne** [comment]
Note that implementations are free to constrain `where T : notnull`; so the argument that *some* implementations don't accept null in GetHashCode isn't very convincing.  Some don't; others do - but this annotation *requires* callers to assume non-null-safeness, even if the callee is documented to be null-accepting.  You could even go so far as to add `[AllowNull]` on the `Equals` arguments, if it turns out to be relevant.

And while it's fine for implementations to throw; is there a reason for e.g. StringComparer to throw?  Superficially removing the throw sounds like a simple, practical improvement.

**Comment by stephentoub** [comment]
If a concrete implementation wants to be more permissive and accept null, that's fine, it can, and its public signature can reflect that. But the interface is the exchange type, and consumers of that interface need to know how to safely use it: with implementations not accepting null, and with the docs stating passing null may throw, consumers shouldn't pass in null to an arbitrary instance received. That needs to be clear in the annotations on the interface.

As for StringComparer, it could theoretically be changed. It wouldn't solve this, though. It's just one case of many where the implementation is following the contract that had existed for a very long time. We do not have the luxury of pretending otherwise.

**Comment by jnm2** [comment]
In principle, I'd rather have false positives to suppress than both false positives and false negatives to worry about when using NRTs. It's unfortunate that EqualityComparer<T>.GetHashCode is both a virtual method and also in the extremely common use case of delegating to EqualityComparer<T>.Default.GetHashCode as a means of avoiding a null check, but this is also fading into the past as we move things to .NET Core. Even more so when C# 9's records are generally available. And it's not like GetHashCode implementations are a particularly transfixing read either way.

**Comment by EamonNerbonne** [comment]
Why not let the implemenation pick the nullability, e.g. something like this?

```C#
    public interface IEq<in T>
    {
        bool Equals([AllowNull] T a, [AllowNull] T b);
        int Hash(T obj);
    }

    public class Eq<T> : IEq<T>
        where T: notnull
    {
        public bool Equals([AllowNull] T a, [AllowNull] T b) => EqualityComparer<T>.Default.Equals(a,b);
        public int Hash(T obj) => EqualityComparer<T>.Default.GetHashCode(obj);
    }
```

Because there's no *good* way for a concrete implementation to declare that it accepts null now - failure to follow the interface nullability attrs is a warning, and if you ever pass the "extended and null-safe" comparer to something using the interface you cannot capture the permitted nullability in the type parameter.

**Comment by jnm2** [comment]
The IDE should not be warning for making implementations more accepting than the interface constraints. That would be an issue to file at dotnet/roslyn if one doesn't already exist there.

**Comment by EamonNerbonne** [comment]
Sorry, the warning is noise; that occurs for AllowNull, not disallow.  Not that it helps, such an implementation can't be consumed by anything not specifically written to that type.

Why not the `AllowNull` and `where T : notnull` approach above?  In essence, why not make the distinction between `IEquality<string>` and `IEquality<string?>` useful?  Legacy implemenations like StringComparer remain possible, but at least reflexive null-safe implementations are too.

**Comment by jnm2** [comment]
I'm sorry, I don't understand what "the warning is noise" means. The warning for removal of AllowNull is important because callers on `IEqualityComparer<NonNullbleType>` are expecting to be allowed to pass `null` to `Equals` in spite of non-nullable T. Maybe that's what you're saying.

> Why not the `AllowNull` and `where T : notnull` approach above? 

Because with this approach, I can't access `EqualityComparer<T>.Default` without virally placing `where T : notnull` throughout my own generic type parameters.

**Comment by jnm2** [comment]
@stephentoub I read through the thread and wasn't able to answer this question. If `[DisallowNull]` was removed from `IEqualityComparer<T>.GetHashCode`, implementations of `IEqualityComparer<AnyClass>` would not be affected. Only implementations of `IEqualityComparer<AnyClass?>` would be affected.

Could the problem be solved by saying, make implementations that throw implement `IEqualityComparer<AnyClass>` rather than `IEqualityComparer<AnyClass?>`?

It seems possible that all documentation existing prior to NRTs could be consistently interpreted as applying only to ``IEqualityComparer<AnyClass>` and not to `IEqualityComparer<AnyClass?>`.

**Comment by EamonNerbonne** [comment]
`EqualityComparer<T>.Default` *does* allow nulls passed to GetHashCode, so that wouldn't need `where T : notnull` - but a hypothetical implementation that required the old behavior that doesn't accept null for GetHashCode has the *option* of disallowing null. So I guess that would be an issue for `EqualityComparer<T>` subtypes?  But that's still a little narrower in scope; isn't there some way to leverage that to keep the interface clean and push the problem down?

**Comment by jnm2** [comment]
@EamonNerbonne `EqualityComparer<T>` must include the same generic constraints on T as `IEqualityComparer<T>` in order to implement it.

**Comment by jnm2** [comment]
@stephentoub I'm considering moving my [question](https://github.com/dotnet/runtime/issues/30998#issuecomment-637812155) to a new thread since it would apply to IEqualityComparer\<T> rather than EqualityComparer\<T>. I'll plan to do that soon if you don't immediately see the flaw that would make it a moot point.

**Comment by EamonNerbonne** [comment]
> @EamonNerbonne `EqualityComparer<T>` must include the same generic constraints on T as `IEqualityComparer<T>` in order to implement it.

The class can't omit constraints, but can implement additional constraints, such as `T:notnull`.  The `IEq` + `Eq` example above does that and compiles.

**Comment by jnm2** [comment]
@EamonNerbonne I lost the thread in the conversation and misunderstood the `where T : notnull` to be on the interface, sorry! Putting the constraint either place is still a problem for me because I use both in generic methods where I don't want that constraint.

**Comment by EamonNerbonne** [comment]
Yeah, that's not an ideal solution for the general case and given the usage of `EqualityComparer<T>.Default that kind of needs to be available for the general case.

**Comment by jnm2** [comment]
I moved my [comment above](https://github.com/dotnet/runtime/issues/30998#issuecomment-637812155) to https://github.com/dotnet/runtime/issues/37569 since it is a separate proposal.
