### ISSUE TITLE
Enumerating StringCollection via ForEach allocates redundantly.

### ISSUE THREAD

**Issue by Mrnikbobjeff** [dotnet/runtime#31070]
StringCollection uses ArrayList as a backing collection. The current stringlist enumerator is a reference type. By adopting a private version for the current state of StringCollection as is present in List<> we can cut enumeration times in half and avoid allocating by ignoring the ArrayList enumerator and use a variant of the List<> enumerator. Also, the ArrayList indexer can easily avoid one range check by using the optimization present in the List<> indexer:
`if((uint)index >= (uint)_size) throw...`
Finally, to the best of my knowledge methods which throw directly are not inlined. The ArrayList Indexer throws, unlike the List<> Indexer which uses a throw helper. We should also introduce a throwhelper for ArrayList

**Comment by eiriktsarpalis** [comment]
> Also, the ArrayList indexer can easily avoid one range check by using the optimization present in the List<> indexer:

Note that this would be a breaking change since it would now throw `IndexOutOfRangeException` instead of the current `ArgumentOutOfRangeException`. I'm not convinced it would bring any significant performance gains either.

I'm going to close the issue since we can't avoid enumerator allocations without taking a breaking change.
