### ISSUE TITLE
Api proposal: Change JsonSerializerOptions default settings

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/runtime#31094]
New API:

```cs
public static class JsonSerializerOptions
{
    // Can only be set until the first (de)serialization occurs (like other properties here)
    public static Func<JsonSerializerOptions> Default { get; set; }
}
```
Newtonsoft \  JSON.NET does it this way:
```cs
public static class JsonConvert
{
    public static Func<JsonSerializerSettings> DefaultSettings { get; set;}
}
```

The upside is that you can have different settings for different situations, including different options per assembly, even though that would require the developer be aware of the potential pitfalls of that. The fact that it has also worked for many years in JSON.NET I think is a plus as well.

Performance could suffer a little bit, would have to test. Either way, one could always get over that by explicitly passing their options.

----

Original text:

Provide a way to change the default settings for the static `JsonSerializer` class. In Json.NET, you could do:

```cs
JsonConvert.DefaultSettings = () => new JsonSerializerSettings();
```

Currently you have to keep passing the options around and remembering to pass it to each call to `[De]Serialize`

**Comment by ericsampson** [comment]
@ahsonkhan are you looking for a design proposal here? Just curious because I see that it's been tagged with the 5.0 milestone, but haven't heard much action since your last post in December. Thanks!!

**Comment by ahsonkhan** [comment]
> are you looking for a design proposal here?

Yes, we at least need a straw man API proposal that facilitates a discussion around the topics I mentioned: https://github.com/dotnet/runtime/issues/31094#issuecomment-567232806

We can then mark this issue as `api-ready-for-review` and have it reviewed as part of the weekly API review. 

From what I recall, there were reservations in the past to expose this global setting as it doesn't compose/scale well as you start to get more complex scenarios where you have multiple dependencies, each with their own "globally" defined options. 

Think of an application which overrides the default setting and a library it depends on, which has its own default `JsonSerializerOption` override, and how can the developer of the app and the developer of the library reason about it in their code (different components, different authors, different timelines).

**Comment by andre-ss6** [comment]
> > are you looking for a design proposal here?
> 
> Yes, we at least need a straw man API proposal that facilitates a discussion around the topics I mentioned: [#31094 (comment)](https://github.com/dotnet/runtime/issues/31094#issuecomment-567232806)
> 
> We can then mark this issue as `api-ready-for-review` and have it reviewed as part of the weekly API review.

I would rather have a discussion around the points [I mentioned](https://github.com/dotnet/runtime/issues/31094#issuecomment-567148654) earlier before drawing an API proposal, but OK, I'll do it.

**Comment by andre-ss6** [comment]
@ahsonkhan 

Done. I don't know how api review works, but I hope the issue is not closed if this specific API is rejected. I didn't open the issue because I had a specific _API_ in mind, but because I want to have this _feature_. It's also hard not knowing the team's thoughts on the different possible approaches...

**Comment by ericsampson** [comment]
@ahsonkhan wrote
> 
> From what I recall, there were reservations in the past to expose this global setting as it doesn't compose/scale well as you start to get more complex scenarios where you have multiple dependencies, each with their own "globally" defined options.
> 
> Think of an application which overrides the default setting and a library it depends on, which has its own default `JsonSerializerOption` override, and how can the developer of the app and the developer of the library reason about it in their code (different components, different authors, different timelines).

@andre-ss6 thanks for updating your original post with a proposal.
However, I believe that copying Json.NET's design 1-1 is not desirable. My experience is that it's important to have a way for library authors to create a JsonSerializer with their own default settings, not coupled to whatever settings the consumer of the library has set. This has been a pain point with Json.NET's design, and not one I'd like to see repeated.

**Comment by andre-ss6** [comment]
> @andre-ss6 thanks for updating your original post with a proposal.
> However, I believe that copying Json.NET's design 1-1 is not desirable. My experience is that it's important to have a way for library authors to create a JsonSerializer with their own default settings, not coupled to whatever settings the consumer of the library has set. This has been a pain point with Json.NET's design, and not one I'd like to see repeated.

@ericsampson  Well I'd love to hear a different suggestion/thoughts on the different approaches. I've been waiting for that [since last year](https://github.com/dotnet/runtime/issues/31094#issuecomment-567148654).

**Comment by SidShetye** [comment]
> Think of an application which overrides the default setting and a library it depends on, which has its own default `JsonSerializerOption` override, and how can the developer of the app and the developer of the library reason about it in their code (different components, different authors, different timelines).

Application authors shouldn't suffer due to poor design choices by a library author. Plus that argument essentially boils down to "management of shared resources" - and has been solved before. The obvious advantage to this is greater application design consistency from a single place (e.g. app init) rather than auditing the whole codebase around every http call. Finally, it makes sense to optimize for the common case i.e. JSON serialization options is likely to stay similar rather than change in every instance

So back to the point, either of the two API proposals now in the original post should work.

**Comment by ericsampson** [comment]
IMO the defaulted options should not cross assembly boundaries; or at least without requiring explicit opt-in to this behavior.

**Comment by steveharter** [comment]
Updated the main API proposal to:
```cs
public static class JsonSerializerOptions
{
    // Can only be set until the first (de)serialization occurs (like other properties here)
    public static Func<JsonSerializerOptions> Default { get; set; }
}
```

I am assuming it returns `null` by default meaning a private default options is still used like today.

A simple implementation would be:
```cs
    static class MyCustomOptions
    {
        private static JsonSerializerOptions _options;

        // Since we're storing the options in a static variable, just use a static ctor.
        static MyCustomOptions()
        {
            _options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            };
        }

        public static JsonSerializerOptions MyDefault()
        {
            return _options;
        }
    }
```

The implementation can be more complicated of course -- you could read the settings from disk, for example, or to change the storage from a static variable to one based on a context variable (like per user or thread).

To register:
```cs
JsonSerializerOptions.Default = MyCustomOptions.MyDefault;
```

**Comment by svenso** [comment]
I am currently struggling with the default settings on System.Net.Http.Json (there are some different defaults once more).
Because here is going on something, I just wanted to hint, that the new default settings would probably also need to be applied here:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs

**Comment by IanKemp** [comment]
I believe that the root of the problem is that `JsonSerializer`'s design is questionable: it is defined as a static class, but has an implicit dependency on a separate stateful class (`JsonSerializerOptions`) in order to function by default. I understand why this was done - to mimic `Newtonsoft.Json` as closely as possible, to simplify porting code that uses that API - but the end result is that this state leaks (hence causing the problems noted in this issue). Having the property holding this state private somewhat prevents that leak, but changing it to public would effectively open the floodgates.

Therefore, I'd like to suggest a counter-proposal: instead of making `JsonSerializer` more static, create a non-static wrapper API for it that has an instance of `JsonSerializerOptions` injected into its constructor, as per the standard DI pattern. Something like:

```csharp
public interface IJsonSerializer
{
    Task<T> DeserializeAsync<T>(string json);

    // other methods elided for brevity
}

public class DefaultJsonSerializer : IJsonSerializer
{
    private JsonSerializerOptions _defaultOptions;

    public DefaultJsonSerializer(IOptions<JsonSerializerOptions> defaultOptions)
    {
        _defaultOptions = defaultOptions.Value;
    }

    public Task<T> DeserializeAsync<T>(string json, JsonSerializerOptions options = null)
        => await JsonSerializer.DeserializeAsync<T>(json, options ?? _defaultOptions);
}
```

The default options are configured at startup using the standard DI mechanisms, and your code that does serialization gets an instance of `IJsonSerializer` with those options. You can still override them if absolutely necessary, but if you don't, you don't need to worry about what they're set to.

This will overcome the issue that @ahsonkhan noted in https://github.com/dotnet/runtime/issues/31094#issuecomment-563075492 - for example in an ASP.NET Core context, the options that it sets for its defaults, plus any user overrides set via `AddJsonOptions()`, will now be implicitly used by `IJsonSerializer`, and everything Just Works.

There is, of course, nothing preventing anyone from applying the pattern I've suggested right now.

**Comment by TanvirArjel** [comment]
I have been tired of writing `PropertyNameCaseInsensitive = true` as follows:

```
var options = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true,
};
var weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(jsonString, options);
```

This should have been a default setting. I am not convinced why .NET team made this `PropertyNameCaseInsensitive = false,` ass default. This is one of the misdesign in .NET 5.0 which is giving and will give a lot of pain in the upcoming days unless they alter this.

**Comment by ericsampson** [comment]
@TanvirArjel it is my understanding that the default was chosen because of improved performance, you take a perf hit for using caseinsensitive. I doubt that the default is going to change now, that would change behavior.

**Comment by ahsonkhan** [comment]
Also, asp.net core web apps and HttpClientJsonExtensions methods use [JsonSerializerDefaults.Web](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializerdefaults?view=net-5.0) options setting by default, which is geared specifically for such web scenarios and has case insensitive set to true.
https://github.com/dotnet/runtime/blob/35fbaefa57f94268090dd28d432b6109e64a8c48/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L105-L110

https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/jsonserializer-allows-reading-numbers-as-strings

**Comment by TanvirArjel** [comment]
@ahsonkhan Thank you. I know this but the question is when your default in the base class library is being altered in almost every case then surely your default is wrong and it needs to be amended as a breaking change in the next major version.

**Comment by michal-ciechan** [comment]
> ```cs
> ((JsonSerializerOptions)typeof(JsonSerializerOptions)
>                 .GetField("s_defaultOptions", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic).GetValue(null))
>             .PropertyNameCaseInsensitive = true;
> ```
> 
> 😈😈😈

Thanks for this, this is what we ended up doing!

We use Automapper to map all the properties from the AspNetCore version into the global default one!

This definitely needs to be exposed as a public API!


```csharp
        /// <summary>
        /// This sets provided JsonSerializerOptions to be used by System.Text.Json by default.
        /// As the `s_defaultOptions` field is init (and private static), it's not possible to set it directly via reflection.
        /// The only way was to map all properties inside of JsonSerializerOptions, so we used AutoMapper to do that.
        /// </summary>
        private static void SetDefaultJsonSerializerOptions(JsonSerializerOptions options)
        {
            var globalOptions = (JsonSerializerOptions?)typeof(JsonSerializerOptions)
                .GetField(
                    "s_defaultOptions",
                    BindingFlags.Static | BindingFlags.NonPublic
                )?.GetValue(null);
                
            if (globalOptions == null)
                throw new Exception("Could not find property for global JsonSerializerOptions");

            var config = new MapperConfiguration( x => 
                { 
                    x.CreateMap<JsonSerializerOptions, JsonSerializerOptions>(); 
                }
            );

            var jsonSerializerOptionsMapper = config.CreateMapper();

            jsonSerializerOptionsMapper.Map(options, globalOptions);
        }
```

**Comment by HeinA** [comment]
I just spent all day trying to figure out why I keep getting a "The value must be a DateTimeOffset or Date." error in my OData controller when trying to PUT an object

Turns out PutAsJsonAsync<> changes my properties from pascal case to  camel case.  OData/MVC is happy to deserialize all properties, except DateTime properties, which must match the case of the property exactly.

What makes DateTime properties so special that they get treated differently???

**Comment by Clockwork-Muse** [comment]
> I just spent all day trying to figure out why I keep getting a "The value must be a DateTimeOffset or Date." error in my OData controller when trying to PUT an object
> 
> Turns out PutAsJsonAsync<> changes my properties from pascal case to camel case. OData/MVC is happy to deserialize all properties, except DateTime properties, which must match the case of the property exactly.
> 
> What makes DateTime properties so special that they get treated differently???

@HeinA - That sounds like a related but separate bug.  Please report it separately.

**Comment by kvbutler** [comment]
Thanks for the reflection hack @michal-ciechan!

Need a better solution than this for Azure Isolated Function App, the docs are misleading and suggest you can set default options (https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide)

**Comment by PieterjanDeClippel** [comment]
I created a new Blazor Server application using .NET 6, and when I'm sending an HTTP request to retrieve data in my Client application, I get the following response:

```
[
  {
    "date": "2021-11-14T11:04:55.7007215+01:00",
    "temperatureC": 27,
    "summary": "Chilly",
    "temperatureF": 80
  },
  {
    "date": "2021-11-15T11:04:55.7009955+01:00",
    "temperatureC": 11,
    "summary": "Cool",
    "temperatureF": 51
  },
  {
    "date": "2021-11-16T11:04:55.7009985+01:00",
    "temperatureC": 19,
    "summary": "Scorching",
    "temperatureF": 66
  },
  {
    "date": "2021-11-17T11:04:55.7009988+01:00",
    "temperatureC": 29,
    "summary": "Bracing",
    "temperatureF": 84
  },
  {
    "date": "2021-11-18T11:04:55.700999+01:00",
    "temperatureC": 27,
    "summary": "Freezing",
    "temperatureF": 80
  }
]
```

However, when deserializing this response using the following code

    var result = await System.Text.Json.JsonSerializer.DeserializeAsync<WeatherForecast[]>(content);

The fields are empty since `System.Text.Json.JsonSerializer` expects the properties to start with a capital:

```
[
  {
    "Date": "2021-11-18T11:04:55.700999+01:00",
    "TemperatureC": 27,
    "Summary": "Freezing",
    "TemperatureF": 80
  }
]
```

**Comment by Clockwork-Muse** [comment]
@PieterjanDeClippel - [You need to use case-insensitive deserialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-casing).

**Comment by Xyncgas** [comment]
I would like this too, sometimes I am changing my old code instead of new code, to have a new behavior, then instead of going around making sure I did the right thing that I've passed in the correct Serializer option every where, I want to have a way to set it project wide, for all the System.text.json Serializations to use my enforced serializer option, instead of doing this myself which is possible, plus I think it is too late at this point when I am working on a project already written, I would like it to be possible.

**Comment by SuperMeip** [comment]
I need this at the moment lol. It would be nice to be able to add default settings.

**Comment by iocio005** [comment]
I cannot understand why this has not done yet. Adding the possibility of set a default global behaviour of a static class in the serializer have a lot of sense when you are using .net mvc.

**Comment by 0xced** [comment]
I'm really surprised that so many people are asking for a public static property in a JSON library. This is shared mutable state and the industry has pretty much settled that shared mutable state is evil and the source of so many bugs.

Last year, I submitted a pull request to a project that was [altering Newtonsoft.Json JsonConvert.DefaultSettings](https://github.com/perfahlen/AzureMapsRestServices/pull/29). The pull request was not merged because the maintainer switched to `System.Text.Json` where this problem simply does not exist!

**Comment by iocio005** [comment]
That could explain why this proposal has not done yet. Thanks for your comment Cédric.

**Comment by ericsampson** [comment]
@0xced FWIW, if you notice the original proposal, the options become immutable once the first serialization has occurred.

**Comment by ericsampson** [comment]
@krwq and @steveharter, being able to put an annotation on a class could be useful to some people, but it would be really nice to be able to set the assembly level.
This would avoid the unfortunate issue in Newtonsoft where a poorly-behaved library (perhaps internally developed at a company by someone that doesn't know better) changes the default options out from under your application 😓. While still achieving the goals that people have requested in the thread. It's effectively a solved problem for MVC apps and that works well, but that leaves a lot of other app/service types out.

**Comment by krwq** [comment]
Next steps here are to design specific APIs (and if proof of concept is needed create a prototype). Any volunteers? We're currently still in a bug fixing/planning stage so we're not sure if we'll have time to pick this up in 7.0 without some help.

ref:
https://github.com/dotnet/runtime/issues/31094#issuecomment-951164825
https://github.com/dotnet/runtime/issues/31094#issuecomment-951071151

**Comment by Xyncgas** [comment]
> I'm really surprised that so many people are asking for a public static property in a JSON library. This is shared mutable state and the industry has pretty much settled that shared mutable state is evil and the source of so many bugs.
> 
> Last year, I submitted a pull request to a project that was [altering Newtonsoft.Json JsonConvert.DefaultSettings](https://github.com/perfahlen/AzureMapsRestServices/pull/29). The pull request was not merged because the maintainer switched to `System.Text.Json` where this problem simply does not exist!

No one has agree anything, nothing has to be one way, don't commit to the path that has been there unless is necessary, by that it usually means solid logical constrains, if there isn't one then possibility shouldn't be limited.

Are you so smart to guaranteed it's a bad thing 5 years later, don't limit yourself until others proves you wrong since it's none lethal just like we as a society is making progress having multiple gender identities not instead because of we are biological different.

**Comment by rf-0** [comment]
> ```cs
> ((JsonSerializerOptions)typeof(JsonSerializerOptions)
>                 .GetField("s_defaultOptions", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic).GetValue(null))
>             .PropertyNameCaseInsensitive = true;
> ```
> 
> 😈😈😈

😁I would be careful with this implementation though. In the case that a serialization already occurred, you're likely to get an exception.

**Comment by nguyenlamlll** [comment]
@0xced Hey Mr-Know-It-All. Your use case is different. And read the author's original intention again, please. Implementation is open for discussion. We don't want a `public static property in a JSON library`. We want to be able to set the a default setting once in our projects. My use case is different than yours. I'm not building a package to be consumed by others. I'm just building websites that make lots of requests to my APIs. Passing the default setting every single time? Not the brighest idea.

**Comment by udlose** [comment]
@nguyenlamlll
If you are using a `Microsoft.NET.Sdk.Web` project, you can use `AddJsonOptions` in Startup/Program to customize your JsonSerializerOptions that .NET will use instead of having to create a static property - https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvcjsonmvcbuilderextensions.addjsonoptions

**Comment by jeroenheijmans** [comment]
Want to add that this is especially a concern for me when writing `WebApplicationFactory` based integration tests (or related unit tests). I was looking for a way to make xUnit globally set the same "Web" defaults for deserializing data. A shame that it's not possible, and a real toss-up for me between the Reflection hack above or "having to remember" using my own convenience deserialization methods in all tests.

Being able to set a more sane default for `PropertyNameCaseInsensitive` globally should outweigh the desire to keep all static things not mutable.

But perhaps there's greater concerns that block making this issue from being resolved?

**Comment by InsomniumBR** [comment]
I am using a SignalROutput in an Azure Function, and that gets me to the same problem here, I cannot change the default behavior since the property is not exposed and the Output trigger is the one using the Serializing method, so I cannot send my settings either.

![image](https://user-images.githubusercontent.com/2073799/167474924-2d4bff74-fc80-4911-b918-1eb899611a36.png)

**Comment by InsomniumBR** [comment]
@krwq in fact none worked. I thought my problem was in the System.Text.Json serialization. And that line of code **worked** in azure function constructor or inside the function method to make the JsonSerializer.Serialize works as I expected (using the converter). But didn't solve my problem anyway. I need to dig more here to understand with this SignalROutput is not using these settings, or if I am missing something:

![image](https://user-images.githubusercontent.com/2073799/167481743-170879f2-acd7-48d9-b0a9-57f942c2b5e2.png)

**Comment by schoder-moreno** [comment]
@steveharter @krwq I'm willing to help move this issue forward with an API design and a prototype as I have a need for this functionality in my own projects.

How were you envisioning the solution with assembly level attributes working? 
One similar idea I had was to change `JsonSerializerOptions.Default` from
```C#
public static JsonSerializerOptions Default { get; } = CreateDefaultImmutableInstance();
```
to 
```C#
        public static JsonSerializerOptions Default
        {
            set
            {
                string callingAssembly = Assembly.GetCallingAssembly().GetName().FullName;
                if (_defaultOptions.ContainsKey(callingAssembly))
                {
                    ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable(context: null);
                }

                value.InitializeCachingContext();
                _defaultOptions.Add(callingAssembly, value);
            }
        }

        internal static JsonSerializerOptions GetDefaultOptions(string callingAssembly)
        {
            return _defaultOptions.TryGetValue(callingAssembly, out JsonSerializerOptions? value) ? value : _defaultOption;
        }

        private static Dictionary<string, JsonSerializerOptions> _defaultOptions = new Dictionary<string, JsonSerializerOptions>();
        private static JsonSerializerOptions _defaultOption = CreateDefaultImmutableInstance();
```
Then the options could vary depending on which assembly is calling into `System.Json.Text`:
```C#
        public static TValue? Deserialize<TValue>([StringSyntax(StringSyntaxAttribute.Json)] string json, JsonSerializerOptions? options = null)
        {
            if (json is null)
            {
                ThrowHelper.ThrowArgumentNullException(nameof(json));
            }
            // Insert this in every public api method that takes a `JsonSerializerOptions?` input parameter
            options ??= JsonSerializerOptions.GetDefaultOptions(Assembly.GetCallingAssembly().GetName().FullName);

            JsonTypeInfo jsonTypeInfo = GetTypeInfo(options, typeof(TValue));
            return ReadFromSpan<TValue>(json.AsSpan(), jsonTypeInfo);
        }
```
Some quick benchmarking seemed to indicate that the performance hit from the third and any subsequent call to `Assembly.GetCallingAssembly()` was on par with adding another if statement. Not sure what your stance is on using reflection calls such as this throughout the apis to the extent that I am suggesting?

**Comment by schoder-moreno** [comment]
@eiriktsarpalis I totally get that and agree to some extent. I guess I am a little confused on what the sentiment is. Are we at a point where you are willing to accept a solution with a public static default options (mutable or immutable), or should the solution exhibit other characteristics/behavior, and if so which?

**Comment by eiriktsarpalis** [comment]
.NET 7 will expose an immutable default instance (via #61093). For reasons already stated in this thread, I don't believe we would ever consider making it settable. 

One possible alternative might be to supporting "JsonSerializer" instances: an object encapsulating `JsonSerializerOptions` and exposing instance method equivalents to the existing static API. That might be one way of avoiding the common pitfalls of forgetting to pass the right `JsonSerializerOptions` instance or creating a new options instance on each serialization op.

**Comment by schoder-moreno** [comment]
Then I will reiterate @IanKemp's suggestion (https://github.com/dotnet/runtime/issues/31094#issuecomment-674990782):

```cs
public interface IJsonSerializer
{
    Task<T> DeserializeAsync<T>(Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken);

    // other methods elided for brevity
}

public class DefaultJsonSerializer : IJsonSerializer
{
    private JsonSerializerOptions _defaultOptions;

    public DefaultJsonSerializer(IOptions<JsonSerializerOptions> defaultOptions)
    {
        _defaultOptions = defaultOptions.Value;
    }

    public async Task<T> DeserializeAsync<T>(Stream utf8Json, JsonSerializerOptions options = default, CancellationToken cancellationToken = default)
        => await JsonSerializer.DeserializeAsync<T>(utf8Json, options ?? _defaultOptions, cancellationToken);
}
```

Is this closer to something you will consider @eiriktsarpalis?

**Comment by eiriktsarpalis** [comment]
Something like that, although probably without the interface and IOptions dependency. I also think that the instance methods should not accept an options parameter to emphasize encapsulation.

At risk of stating the obvious, such a class can easily be defined by users and would introduce duplication of serialization APIs. It's a fairly drastic intervention providing comparatively low benefit and as such we should not do it unless we are absolutely convinced it's the way forward.

**Comment by michal-ciechan** [comment]
I think as a stop gap, registering in DI a `IJsonSerializer` in the with the `JsonOptions.JsonSerializerOptions` set to whatever has been configured in AspNetCore would be a good starting point so that we can use it inside the app, or retrieve it from services in testing. Would also add an easier access / discoverability for it in `WebApplicationFactory` as more often then not you will be serializing/deserializing Json and most likely want to use the same options.

Most of my use cases have been either integration testing an AspNetCore app, or within the app itself where I want to do some logging of some sort, or persisting Json into external storage systems.

**Comment by eiriktsarpalis** [comment]
Here's another reason why we might want to consider introducing a `JsonSerializer` instance API: all current serialization methods accepting `JsonSerializerOptions` have been marked `RequiresUnreferencedCode` due to them using reflection-based serialization by default. This is behavior that predates the introduction of source generators in .NET 6 and contract customization in .NET 7.

The virality of `RequiresUnreferencedCode` can be a nuisance when using otherwise perfectly linker-safe code in trimmed applications. Using instance serialization methods means that we can push RUC annotations to specific constructors/factories and have linker warnings only surface in the app's composition root.

@krwq @eerhardt @jeffhandley thoughts?

**Comment by eerhardt** [comment]
>  we might want to consider introducing a JsonSerializer instance API

I chatted a bit with @vitek-karas about this yesterday. Being able to put all the "JSON source gen information" (i.e. JsonTypeInfos / JsonSerializerContext, or an instance of JsonSerializer) into DI makes a lot of sense to me. This could be a nice way for ASP.NET to use the JSON source generated code when they serialize objects.

One scenario that might need thinking about is if you want to serialize the same Type in multiple ways - lets say PascalCase in one case, and camelCase in another (or any other option that the source gen respects - like WriteIndented).

Either way - I think having a "DependencyInjection-friendly" way of serializing objects makes sense and would be valuable. This could be to make `JsonSerializer` be instantiable and have normal instance methods, or some other design like where the DependencyInjection info (JsonTypeInfos / JsonSerializerContext) gets passed to the static `JsonSerializer` methods. I do like the idea of instance methods on JsonSerializer, and then having certain ways of creating the instance of the JsonSerializer be `RequiresUnreferenced/DynamicCode`. That seems clean.

One more issue is that you'd still want the default experience to work in ASP.NET, when JSON source generation isn't used at all. That means a "fallback" or "default" experience (i.e. Reflection) needs to still work for "normal" apps. However, this "fallback" or "default" code will raise trimming warnings. To get rid of those, we could introduce a [feature switch](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md) that removes the Reflection experience and ONLY works with trim-safe serialization code. Then your app wouldn't use Reflection to do serialization at all.

cc @davidfowl - FYI since we've discussed this "how can ASP.NET use JSON source generation code" topic a lot.

**Comment by vitek-karas** [comment]
I think another important capability which ASP.NET would probably make use of is the ability to "merge" several such instances. For example let's say my app uses a library FabulousObjects which contains source generated serialization code for its objects because it calls into ASP.NET on my app's behalf. But my app also contains other source generated code for app's objects, which again are serialized by ASP.NET. For this to work both the app and the FabulousObjects would need to register the source generated code with the DI - but the fact that there are 2 sources should be transparent to ASP.NET itself, thus the need to "merge" the two instances into one which can serialize objects from both the app the library.

Such design would probably work better if we DI the contexts which can be merged, but maybe there's a way to do this with serializer instances themselves.

**Comment by agocke** [comment]
Having an "instance" serializer makes a lot of sense to me. The interesting pivot point to me is the concept of having a "serializer" vs a "serialization context".

What I mean by that is that we could consider three separate levels of serialization state. 

At the highest level we have a static `Serialize` method that takes a type and some options, and preferably consumes no global state at all. This is what we already have. Each invocation is entirely self-contained. There is no state preserved between invocations.

The next level is a kind of serialization context, which bakes in some set of options. This version would allow you to preserve options between invocations, but wouldn't preserve any information about the serialization process itself.

The last level is the actual serialization process. This is an inherently stateful operation where the output and input are held in intermediate state as we walk the type graph (or text in the case of deserialization). This level would fix the input and the output and would be essentially one-shot, not reusable across multiple serializations.

Right now in [serde-dn](https://github.com/agocke/serde-dn) I have support for the first and last abstraction levels, but not the middle one, i.e. this is the implementation of JsonSerializer.Serialize, which is missing a set of options:

```C#
        public static string Serialize<T>(T s) where T : ISerialize
        {
            using var bufferWriter = new PooledByteBufferWriter(16 * 1024);
            using var writer = new Utf8JsonWriter(bufferWriter);
            var serializer = new JsonSerializer(writer);
            s.Serialize(serializer);
            writer.Flush();
            return Encoding.UTF8.GetString(bufferWriter.WrittenMemory.Span);
        }
```

One way to fix this would be to introduce a `JsonSerializerContext` type which takes and stores options.

The tricky bit in my mind here is the source generation stuff. To me that doesn't necessarily fit in any of the abstraction levels, as IMHO the source generation context should be carried with the _type_, not the options.

**Comment by wrkntwrkn** [comment]
> Want to add that this is especially a concern for me when writing `WebApplicationFactory` based integration tests (or related unit tests). I was looking for a way to make xUnit globally set the same "Web" defaults for deserializing data. A shame that it's not possible, and a real toss-up for me between the Reflection hack above or "having to remember" using my own convenience deserialization methods in all tests.
> 
> Being able to set a more sane default for `PropertyNameCaseInsensitive` globally should outweigh the desire to keep all static things not mutable.
> 
> But perhaps there's greater concerns that block making this issue from being resolved?
> 
> EDIT: Right now I contemplate doing something like this to support my xUnit API Integration tests:
> 
> ```cs
> private static readonly JsonSerializerOptions jsonSerializerOptions
>     = new JsonSerializerOptions(JsonSerializerDefaults.Web);
> 
> static HttpClientExtensions()
> {
>     jsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
> }
> ```
> 
> to use it along these lines:
> 
> ```cs
> public static async Task<T> GetAsync<T>(this HttpClient client, string url)
> {
>     return await client
>         .GetAsync(url)
>         .ReadAsDeserializedData<T>();
> }
> 
> private static async Task<T> ReadAsDeserializedData<T>(this Task<HttpResponseMessage> responseTask)
> {
>     var response = await responseTask;
>     response.EnsureSuccessStatusCode();
>     var json = await response.Content.ReadAsStringAsync();
>     var data = JsonSerializer.Deserialize<T>(json, jsonSerializerOptions);
>     if (data == null) throw new Exception("Unexpectedly encountered null response body.");
>     return data;
> }
> ```
> 
> 😢

Cleanest solution for now. 

Still not great to have to pass it in every serialization. Id rather have the risk of not configuring it when needed than to add the options everytime....

**Comment by eiriktsarpalis** [comment]
Per previous discussions in this thread, we don't plan on making `JsonSerializerOptions.Default` mutable in future releases. Exposing global mutable state can have unintended consequences: within the context of one application, multiple components can depend on the default options object, including internal implementations of third-party components. As such, assumptions about the application author owning all serialization calls within the process are transient at best.

At the same time, the conversation has spun into a discussion about potentially exposing the serialization APIs as instance methods: I've opened a separate issue (https://github.com/dotnet/runtime/issues/74492) to track this, feel free to contribute to the discussion there.

**Comment by TanvirArjel** [comment]
@eiriktsarpalis Nobody would have wanted to change the default unless you guys chose some completely irrational value as default. With the current default, it is almost impossible to use the JsonSerializer without changing the current default values. Without any second thought following two should have been defaulted in the library:

```C#
PropertyNameCaseInsensitive = true,
PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
```
If your default is needed to change every time, then your default is entirely wrong and useless.

You ask the whole world (except dotNET Team), and almost everybody will say that JSON deserialization must be case insensitive and serialization should be in camelCase by default.

What's wrong with changing the above two defaults in the library as these would not break any existing thing?
