### ISSUE TITLE
HTTPS Proxy support feature requests

### ISSUE THREAD

**Issue by matteo-prosperi** [dotnet/runtime#31113]
Hello,
As the support of HTTPS proxies is becoming more common, we need to execute HTTP and HTTPS requests through an HTTPS proxy.

To be clear, this is not about executing an HTTPS request through an HTTP proxy (which works well), it is about connecting to the proxy itself using HTTPS.

As an additional requirement, we are also supposed to authenticate the client using client certificates.

When I try to use a proxy created from an https URI
```c#
            HttpClientHandler handler = new HttpClientHandler();
            handler.Proxy = new WebProxy("https://127.0.0.1");
            HttpClient client = new HttpClient(handler);
```
I receive an `Only the 'http' scheme is allowed for proxies.` `NotSupportedException`.

I found some indication at https://github.com/dotnet/corefx/issues/20435 that this is not supported at all, so I am reopening this as a feature request.

Thanks

**Comment by normj** [comment]
Any progress on this feature? We are getting more feature requests at AWS for customers wanting to connect via a HTTPS proxy. The latest one is making calls through the [ngx_http_proxy_connect_module](https://github.com/chobits/ngx_http_proxy_connect_module) Ngnix addin using client cert authentication.

**Comment by mottersheadt** [comment]
Any update on this feature? This will be very useful when it becomes available.

**Comment by mikekilburn** [comment]
Any plans to support this feature?

**Comment by richlander** [comment]
@karelz

**Comment by karelz** [comment]
Last time we looked into this, there were almost no scenarios for HTTPS proxies.
@normj can you please help me understand exactly the product (nginx?) that does support it? Is it mainstream these days?
I wonder why we hear about it from AWS and not from other sources.

@mottersheadt @mikekilburn which proxies do you use which support it? Are they GA, in Beta, or are you interested just from future-proofing perspective?

**Comment by opinionmachine** [comment]
> Last time we looked into this, there were almost no scenarios for HTTPS proxies.

What is the reason to make it forbidden? That is extra effort once made just to make it impossible to connect to a proxy over HTTPS. There is no valid reason for that. 

LexisNexis ID&V API cannot be the only one that requires using a remote proxy. This arbitrary unnecessary disabling of HTTPS reminds me of the gaslighting we got over the "crazy idea" to make Visual Studio 64-bit that "nobody wanted". 

If AWS requiring it means we'll get in in .NET I'm happy.

**Comment by mottersheadt** [comment]
@karelz - I'm looking to support [VGS's Forward Proxy](https://www.verygoodsecurity.com/docs/guides/outbound-connection), which is an HTTPS proxy requiring an additional cert to be added to the request. This product is GA and is often used to descope sensitive data from enterprise networks.

Here is an example of how the proxy can be used in a cURL request:
```
curl https://echo.apps.verygood.systems/post --cacert path/to/sandbox.pem \
  -x https://USERNAME:PASSWORD@tntqoslmkzi.SANDBOX.verygoodproxy.com:8443 \
  -H "Content-type: application/json" \
  -d '{"account_number": "ALIAS"}'
```

**Comment by normj** [comment]
@karelz My understanding from AWS user's point of view is this is most commonly wanted when making request from on-premise network to their AWS infrastructure through a VPN. They want complete end to end encryption with either TLS or MTLS through a proxy to AWS. Protecting themselves from bad actors within their own network. 

When an enterprise has this situation they want all the languages that their application developers use to be able to support this configuration. AWS we have 12+ different languages and most all had this feature but .NET was one of the few outliers that didn't have this support.

**Comment by karelz** [comment]
@opinionmachine 

> What is the reason to make it forbidden? That is extra effort once made just to make it impossible to connect to a proxy over HTTPS. There is no valid reason for that.

It is not forbidden. It is not implemented. If you look at the code, you will see, it is not matter of single if-check. There is impact on connection pool, etc. There would need to be tests, E2E validation, etc. Almost every change is usually more involved than one would hope.

> gaslighting we got over the "crazy idea" to make Visual Studio 64-bit that "nobody wanted"

I wasn't on VS team, but I know that 64-bit VS was a HUUUUUUGE investment. Easily hundreds or thousands of engineer-years. Let's not oversimplify things just because they seem to be simple from the outside. Let's judge the change based on its real cost.

> LexisNexis ID&V API

Can you post a link? Is https proxy part of the API? (that seems weird)

> ... cannot be the only one that requires using a remote proxy

Well, if you read the thread here, you can notice that you are the first person ever to mention a real product that needs it.

**Comment by karelz** [comment]
@mottersheadt great, thanks! That is helpful for our prioritization!

**Comment by karelz** [comment]
@normj thanks for info, few more questions:

> making request from on-premise network to their AWS infrastructure through a VPN. They want complete end to end encryption with either TLS or MTLS through a proxy to AWS.

If they are under VPN, why is a proxy to AWS needed? I might be misunderstanding some common enterprise architecture here ... please bear with me.
Or is it defense in depth / paranoia to make everything HTTPS just to be sure? (I assume DNS will be next)
Naively, just secure connections should be good enough for communication ... that's why we didn't consider it important before.

> When an enterprise has this situation they want all the languages that their application developers use to be able to support this configuration. AWS we have 12+ different languages and most all had this feature but .NET was one of the few outliers that didn't have this support.

Yeah, that totally makes sense from this point of view. Do you happen to have the list of languages that support it already handy? That would save us some research ...
Competitive disadvantage is a good argument ...

**Comment by opinionmachine** [comment]
> It is not forbidden. It is not implemented. If you look at the code, you will see, it is not matter of single if-check. There is impact on connection pool, etc. There would need to be tests, E2E validation, etc. Almost every change is usually more involved than one would hope.
> 
All I know is, it works in .NET Core 2.2 and was broken from 3.1 onwards.  And making network connections over https works, so it can't be miles away. 

> I wasn't on VS team, but I know that 64-bit VS was a HUUUUUUGE investment. Easily hundreds or thousands of engineer-years (don't quote me, it is a wild guess). Let's not oversimplify things just because they seem to be simple from the outside. Let's judge the change based on its real cost.

The real reason of course was as you hint that the code was in such a state with hard assumptions of bitness that it would be a massive undertaking to change and on balance it wasn't worth it for a decade or so but instead of just saying that, we were gaslighted with "nobody wants that, 64-bit makes no difference in performance". 

> Can you post a link? Is https proxy part of the API? (that seems weird)
I wish I could, but I left that employer a while ago so I don't have access to the docs anymore. 
 
> Well, if you read the thread here, you can notice that you are one of the first persons ever to mention a real product that needs it. 🤷
Yeah, I guess. I mean if Lexis Nexis just fixed their authentication method it wouldn't matter but the limitation is so arbitrary it doesn't make sense. I mean proxies are everywhere.  Should nobody ever be able to use .NET to build a competitor to Istio because you can't connect to a reverse proxy over HTTPS?

**Comment by normj** [comment]
@karelz 

> If they are under VPN, why is a proxy to AWS needed? I might be misunderstanding some common enterprise architecture here ... please bear with me.

I make a poor sys admin so bare with me. I believe the concern is the traffic for the on-premise side. The proxy is on-premise which connects on-premise users to the VPN to AWS. So in our SDK's case developers using AWS SDK request will go `workstation/on-premise-server -> proxy -> vpn -> AWS service` but with out HTTPS support that first hop is going over the on-premise network unencrypted.

> Do you happen to have the list of languages that support it already handy?

I'll see if I can get you a complete list but this is my quick list.
* Java (https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
* Python (https://github.com/urllib3/urllib3/pull/1679, https://github.com/urllib3/urllib3/pull/1806, https://github.com/urllib3/urllib3/pull/1923)
* PHP (through third party package Guzzle https://docs.guzzlephp.org/en/stable/)
* Node.js (https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html)
* Go (https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/custom-http/#configuring-a-proxy)

**Comment by LiorBanai** [comment]
Hi,
it this planned for 8.X or for Future?

**Comment by karelz** [comment]
This will be part of Preview 7 (we missed the snap for Preview 6 by a few hours) -- https://github.com/dotnet/core/issues/8438

**Comment by wfurt** [comment]
BTW it would be great if community can pick up daily build and give it try: https://github.com/dotnet/installer
My testing was very limited.

**Comment by LiorBanai** [comment]
Great. Thanks

**Comment by opinionmachine** [comment]
Thanks, folks, this is wonderful news. May you be blessed in every possible way! ❤️
