### ISSUE TITLE
Announcement: .NET Core 3.0 concludes the .NET Framework API porting project

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#31162]
We started in .NET Core 1.0 with a very minimal API set that only included \~18K of the .NET Framework APIs. With [.NET Standard 2.0](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-0/), we tried to make it much more viable to share code between .NET Framework, .NET Core, and Xamarin which resulted in approximately 38K .NET Frameworks APIs being available in .NET Core 2.0. We also built the [Windows Compatibility Pack](https://devblogs.microsoft.com/dotnet/announcing-the-windows-compatibility-pack-for-net-core/) which made another 21K .NET Framework APIs available to .NET Core, resulting in almost 60K additional APIs. And in .NET Core 3.0 we added WPF and WinForms, which increased the number of .NET Framework APIs ported to .NET Core to over 120k, which is more than half of all .NET Framework APIs.

It’s also worth pointing out that we added about 62K APIs to .NET Core that don’t exist in .NET Framework. If we compare their total number of APIs, .NET Core has about 80% of the API surface of .NET Framework.

<p align="center">
<img src="https://user-images.githubusercontent.com/5169960/66777114-f8db7c80-ee7c-11e9-9161-acfe1c491586.png" width="600" align="center">
</p>

We announced that the [future of .NET](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/) will be based on .NET Core. And at Build 2019, [Scott Hunter stated](https://www.youtube.com/watch?v=ZlO1utbB2GQ&t=54m20s) that AppDomains, remoting, Web Forms, WCF server, and Windows Workflow won’t be ported to .NET Core.

With .NET Core 3.0, we’re at the point where we’ve ported all technologies that are required for modern workloads, be that desktop apps, mobile apps, console apps, web sites, or cloud services. That’s not to say that we don’t have any gaps or opportunities for new technologies, but we generally believe we won’t be finding them in the .NET Framework code base anymore. Moving forward, we’re focusing our resources on incorporating new technologies.

Simultaneously, we’re looking into releasing more of the [.NET Framework code base under the MIT license](https://github.com/microsoft/referencesource) on GitHub to allow the community to create OSS projects for technologies we’re not intending to bring to .NET Core. For example, there already are community projects for [CoreWF](https://github.com/UiPath/corewf) and [CoreWCF](https://github.com/CoreWCF/CoreWCF).

We’d like to thank everyone who filed issues with requests for APIs being ported. Those issues allowed us to prioritize and close the gaps that prevented people from porting to .NET Core.

But since we generally no longer plan to bring existing technologies from .NET Framework to .NET Core we’ll be closing all issues that are [labeled with port-to-core](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aport-to-core).

**Comment by duaneking** [comment]
@terrajobst We really need System.Speech support; It feels like the blind or visually disabled community is really being ignored here, either intentionally or by mistake, and a remote service in azure for speech is the absolute WORST answer you could give me for this as it MUST be all running locally to even be useful or functional for many disabled people.  Honestly, System.Speech should have had the same priority in .net as System.Console because for many, its the exact same thing when you cant see.

I'm really confused here because I'm not seeing the sort of inclusiveness or leadership on this issue  that I would normally expect from MSFT.

**Comment by dotMorten** [comment]
@duaneking can't you use the sdk contracts to use the WinRT apis for that?
https://blogs.windows.com/windowsdeveloper/2019/04/30/calling-windows-10-apis-from-a-desktop-application-just-got-easier/

**Comment by duaneking** [comment]
@dotMorten Sadly, No, I don't like that idea at all as it violates the fundamental ideal of inclusion that MSFT has publicly stated is its goal here. It does not fit the same use cases, does not provide the same functionality, would require API/Code changes, and would effectively force sighted/non-sighted segregation by namespace and functionality.  I don't feel that's a fair solution as it would only make things worse for the disabled.

System.Console is simple to you or anybody looking at this because you can see it.  But imagine if you had no monitor hooked up to your computer, or if you somehow simply could not turn it on and didn't have the ability to do so every day.  How would you interact with the computer if you could not see it? So yes, a computers ability to speak "hello world" should just be as simple as printing it to the screen. We need the same simplicity. Using the same API as System.Speech so that code can all be reused without needing to be rewritten from scratch to support WinRT and its dependency chain would be a great start.

Right now I can only get this simplicity on Linux using non-msft software.

**Comment by terrajobst** [comment]
> Right now I can only get this simplicity on Linux using non-msft software.

Does this mean you require a version of `System.Speech` that can work on Linux? We didn't bring `System.Speech` to .NET Core because the team that owns it considers it replaced. But even if we would provide it: it's a very slim wrapper over Windows COM APIs which means it wouldn't work on Linux.

**Comment by duaneking** [comment]
All you need is a plugin interface.

**Comment by dotMorten** [comment]
Lots of APIs were removed because they wrapped old deprecated Windows com APIs no longer supported (GeoCoordinate APIs is another example). They've been replaced by newer, better and supported WinRT APIs that you can use instead. Why don't you want to use something that's more up to date and supported for the users you refer to? (And if you need, create that compat interface you're talking about).

**Comment by terrajobst** [comment]
@duaneking would you mind opening a new issue specifically asking for speech synthesis? I'd like to keep this discussion generic here.

**Comment by duaneking** [comment]
@terrajobst Sure, I can file a bug, Should I make it here or in a different project? I noticed this is a repeated issue and others have tried to support this, as the bug exists multiple times.

**Comment by duaneking** [comment]
@dotMorten I get the idea that APIs that are newer are sometimes considered to be better, but really they often are not.  My experience with the WinRT apis is that they are often a grab bag of good and evil, often had weird API interfaces that forced incorrect assumptions, didn't play well outside of these assumptions, and in the cases I was forced to use them FORCED me to violate SOLID because the API itself was leaky.

I just don't want to subject a blind person to that hell when all they want to do is make a hello world "console" app because they cant see the screen anyway.  It just feels like this would be harmful.

**Comment by jkotas** [comment]
Let's continue the discussion about System.Speech in https://github.com/dotnet/runtime/issues/34963
