### ISSUE TITLE
Add back netfx test run in System.IO.FileSystem

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#31256]
Per https://github.com/dotnet/corefx/pull/41452#issuecomment-544650139

If instead we decide to close this issue, please delete the netfx-specific tests added in the above PR.

**Comment by JeremyKuhne** [comment]
Triage: We definitely want to do this to make sure we're catching unintentional regressions and document where we intentionally change behavior from .NET Framework.

**Comment by carlossanlop** [comment]
Per [this comment](https://github.com/dotnet/runtime/pull/33063#issuecomment-617416082), we won't be re-enabling the tests for .NET Framework.
I'll submit a PR to remove the Framework specific tests from FileSystem.

**Comment by ericstj** [comment]
> We definitely want to do this to make sure we're catching unintentional regressions and document where we intentionally change behavior from .NET Framework.

Just to address this: our existing tests should cover this.  When we make a change to a test case we should note that it corresponds to a behavior change that's may be a breaking change.  We don't need to run the tests against .NETFramework in order to catch that.

If we do decide to write new tests that cover API that exists on .NETFramework it would make sense for the initial author of those tests to run them against .NETFramework to understand their differences.
