### ISSUE TITLE
HttpClient attempts to call .crt file even after setting ServerCertificateCustomValidationCallback to return true on HttpClientHandler 

### ISSUE THREAD

**Issue by MishalValiyakath** [dotnet/runtime#31264]
.Net Standard library 2.0 
.Net Core 2.2 Web App 

We are using HttpClient to make an https request, initially, we used to get SSL certificate validation errors, after setting ServerCertificateCustomValidationCallback delegate to return true the error is no more and the call is successfully completed. However, we are observing an attempt to reach the .crt file from a server location during teh actual call and it takes 100 seconds before timing out with a faulted state and proceeding to the successful API calls. It makes our total call time to 100seconds + the API response time. Are there any resolution for the same?

**Comment by bartonjs** [comment]
The timeout (consistency) is being investigated by #38782 

As already pointed out, even though the delegate returns true, the system has to build the chain first in order to evaluate the values to pass as the SslPolicyErrors (and X509Chain, of course) value(s), and that's where the pause is occurring.

I think we already have enough changes already in flight (or soon to be done) to address the main thrust of the problem here, so I'm closing this issue because there's no clear next step to it.
