### ISSUE TITLE
System.Text.Json Utf8JsonReader reading an empty buffer causes exception

### ISSUE THREAD

**Issue by dazinator** [dotnet/runtime#31296]
If you use the `Utf8JsonReader` to read an empty buffer  / byte array / stream you get an exception.
This can be seen when using AspNet Core's Configuration system and adding an empty json file:

```
System.FormatException : Could not parse the JSON file.
    ---- System.Text.Json.JsonReaderException : The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
  Stack Trace: 
```

I'm not sure an empty file should cause the reader to fall over - it seems to already have the concept of a `Nothing` token, so it could just tokenise an empty buffer as a `Nothing` token.

**Comment by BrunoBlanes** [comment]
I'm getting this same error message when trying to read an empty reply from a web api using the ReadAsStringAsync() method. Before I used to filter a server reply as below:

```
using HttpResponseMessage httpResponseMessage = await httpClient.GetAsync(requestUri, CancellationToken).ConfigureAwait(false);

if (httpResponseMessage.IsSuccessStatusCode)
{
	return JsonSerializer.Deserialize<List<T>>(await httpResponseMessage.Content.ReadAsStringAsync().ConfigureAwait(false), jsonSerializerOptions) ?? throw new ArgumentNullException();
}
```

Since the server returns 204 for No Content, it passes the above test, and therefore now I have to add an additional check.
Shouldn't it just return `null` for empty replies?
