### ISSUE TITLE
Bitmap.Save 'A generic error occurred in GDI+

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/runtime#31367]
when calling bitmap.Save with a file path where the folder doesn't exist the save method throws a 
System.Runtime.InteropServices.ExternalException: 'A generic error occurred in GDI+.'

IMHO the the folder should be created (to match folder file operations) or throw an expection of DirectoryNotFoundException

**Comment by Macromullet** [comment]
The root of this issue is that Image.Save calls GdipSaveImageToFile, which is implemented natively. The only way to solve this issue is to introduce a new exception by doing the directory path check earlier. This check could potentially be moved, and only performed before the call to GdipSaveImageToFile, but it would then lead to a potential difference when the code paths diverge in Save(Stream stream, ImageCodecInfo encoder, EncoderParameters? encoderParams) when _rawData vs non-null.
