### ISSUE TITLE
Console.OpenStandard* few times slower on Linux

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#31396]
Console.OpenStandard* methods are few times slower on Linux. 

| Slower                                              | diff/base | Base Median (ns) | Diff Median (ns) | Modality|
| --------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| System.ConsoleTests.Perf_Console.OpenStandardInput  |     10.50 |           175.08 |          1838.35 |         |
| System.ConsoleTests.Perf_Console.OpenStandardError  |      4.25 |           434.18 |          1846.05 |         |
| System.ConsoleTests.Perf_Console.OpenStandardOutput |      4.21 |           437.84 |          1843.03 |         |

How to run the [benchmarks](https://github.com/dotnet/performance/blob/3e855485cc40576e364eae4ddd3a60cd60438b72/src/benchmarks/micro/corefx/System.Console/Perf.Console.cs#L22-L47):

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f netcoreapp5.0 --filter 'System.ConsoleTests.Perf_Console.OpenStandard*'
```

Recommended profilers are [PerfCollect](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#PerfCollect) and [VTune](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#VTune).

**Comment by tmds** [comment]
> Which sets _handleType which looks like is not used anymore (it might be a low hanging fruit)

@adamsitnik this issue can be closed. `_handleType` was removed in https://github.com/dotnet/corefx/pull/42400.

**Comment by adamsitnik** [comment]
@tmds When I created this issue I was hoping that somebody is going to perform a full investigation and bring the performance on par with Windows. We have solved only the low hanging fruit (20%) and the difference is still very big. That's why I would perfer to keep it open.

**Comment by tmds** [comment]
Digging a bit deeper.

The highest cost comes from the syscalls involved:

Windows makes 1 for open, and `Dispose` doesn't make any:

https://github.com/dotnet/runtime/blob/886e4422a0731d5941525db18f69316500670452/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L1104-L1113

Unix makes 1 for open, and `Dispose` makes 2:

https://github.com/dotnet/runtime/blob/886e4422a0731d5941525db18f69316500670452/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L110-L126

The `flock` could be eliminated. It would require specializing the `Handle` type. I don't think it is worth it because I expect this won't be called on perf critical paths. For best performance, the method should be called once, and the returned `Stream` should be kept around.

**Comment by tmds** [comment]
@adamsitnik is the above analysis good enough to close this issue?
