### ISSUE TITLE
[System.Threading.Tasks.Dataflow] Data loss during parallelization of BufferBlock.

### ISSUE THREAD

**Issue by VirRus77** [dotnet/runtime#31513]
Good day.
Use:
System.Threading.Tasks.Dataflow v4.10.0

I needed to parallelize data processing on several implementations of handlers. When testing the implementation of parallelization, a data loss situation arose.
Example:
Program.cs
```C#
static void Main(string[] args)
{
    int count = 0;
    while (count++ < 10)
    {
        Console.WriteLine($"Index: {count}");
        Test001.WorkAsync().Wait();
    }
}
```
Test001.cs
```C#
public static class Test001
{
    private const int CountElements = 100000;
    private const int MessagePerInstance = 2;
    private static ICollection<int> Elements = Enumerable.Range(0, CountElements).ToArray();

    public static async Task WorkAsync()
    {
        ICollection<Func<int, int>> instances = new Func<int, int>[]
        {
            v => v,
            v => v,
            v => v,
            v => v,
        };

        var buffer = new BufferBlock<int>(new DataflowBlockOptions { BoundedCapacity = 10 });

        var transformBlocks = instances.Select(
                func => new TransformBlock<int, int>(
                    v => func(v),
                    new ExecutionDataflowBlockOptions
                    {
                        BoundedCapacity = MessagePerInstance,
                        MaxDegreeOfParallelism = MessagePerInstance,
                    }
                )
            )
            .ToArray();

        var bufferOutput = new BufferBlock<int>(new DataflowBlockOptions { BoundedCapacity = 10 });

        var actionList = new BlockingCollection<int>();
        var countAction = 0;

        var action = new ActionBlock<int>(
            v =>
            {
                actionList.Add(v);
                Interlocked.Increment(ref countAction);
            }
        );

        var inputLinks = transformBlocks
            .Select(transformBlock => buffer.LinkTo(transformBlock, new DataflowLinkOptions { PropagateCompletion = true }))
            .ToArray();
        var outputLinks = transformBlocks
            .Select(transformBlock => transformBlock.LinkTo(bufferOutput, new DataflowLinkOptions { PropagateCompletion = false }))
            .ToArray();

        var outputActionLink = bufferOutput.LinkTo(action, new DataflowLinkOptions { PropagateCompletion = true });

        var fillTask = Task.Run(
            async () =>
            {
                foreach (var value in Elements)
                {
                    await buffer.SendAsync(value);
                }
                buffer.Complete();
            });

        await fillTask;
        
        Task.WaitAll(transformBlocks.Select(v => v.Completion).ToArray());
        bufferOutput.Complete();

        await action.Completion;

        if (actionList.Count != CountElements)
        {
            var actionValue = actionList
                .ToArray();
            var notExist = Elements.Where(v => !actionValue.Contains(v)).ToArray();
            Console.WriteLine($"Not exist action [{countAction}]: {string.Join(", ", notExist)}");
        }
    }
}
```
Console output.
A different launch gives a different amount of missing elements:
```
Index: 1
Index: 2
Not exist action [99999]: 23091
Index: 3
Index: 4
Index: 5
Index: 6
Index: 7
Index: 8
Not exist action [99999]: 67884
Index: 9
Index: 10
```

P.S. Translated using Google Translate.

**Comment by Hermholtz** [comment]
Still occurs in 7.0.0. Additional remediation is to use `MaxDegreeOfParallelism = 1` in the TransformBlock.

The fact that it can happen silently in production makes me reluctant to consider Dataflow as a technology to go, despite the fact I really like its principles and API.

Please can we expect a fix?

**Comment by theodorzoulias** [comment]
I wrote a simpler repro, with fewer components and simplified configuration:

- One unbounded `BufferBlock<int>` as input.
- One unbounded `ActionBlock<int>` as output.
- Two intermediate `TransformBlock<int, int>`s, each one with parallelism 2 and capacity 10, and each linked independently to both the input and the output blocks.

In order to understand better what's going on, the items transformed by each `TransformBlock` are stored in separate `ConcurrentQueue`s. The issue can be reproduced with a very small number of items, even with 20 or less, so dumping all the work done by each `TransformBlock` is not a problem.

[Online demo](https://dotnetfiddle.net/2Vt2Fk).

Sample output:

```none
SourceCount: 40
Transform blocks count: 2
BoundedCapacity: 10
MaxDegreeOfParallelism: 2

An error occured after 94 runs!
- Missing (9): [18, 19, 23, 24, 25, 26, 27, 28, 29]
- Transformed by #1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 18, 19, 23, 24, 25, 26, 27, 28, 29]
- Transformed by #2: [11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

BufferBlock Count: 0
TransformBlocks InputCount/OutputCount: 0/0, 0/0
```

Observations:
- The number of missing items is usually equal to `BoundedCapacity - 1`, and sometimes less.
- The missing items are always the last items transformed by one of the `TransformBlock`s.
- The missing items are contiguous most of the time, but not always.
- The `TransformBlock` that fails to propagate its last items is usually the block that was linked first with the *input* block, but not always. The linking order with the *output* block seems to be irrelevant.

Although the severity of the bug is significant, it is easy to be workarounded if you are aware of it. In this one-to-many-to-one scenario, preserving the order of each individual `TransformBlock` offers no advantage, because the items are going to be shuffled anyway when they reach the output block. So the `TransformBlock`s can be configured with `EnsureOrdered = false`, which prevents the bug from appearing. In case restoring the order of the shuffled output is desirable, the StackOveflow question below offers some ideas:

[How to restore the order of a shuffled Dataflow pipeline?](https://stackoverflow.com/questions/65358480/how-to-restore-the-order-of-a-shuffled-dataflow-pipeline)
