### ISSUE TITLE
Suggestion/Question: Is it possible to add time estimation in the porting guide?

### ISSUE THREAD

**Issue by theaoqi** [dotnet/runtime#31616]
[Guide for porting .NET to a new processor architecture](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/guide-for-porting.md) is very useful and helps us a lot. We are doing our work according to this document.

Is it possible to estimate the man-hours required for each stage? In the interpreter section of [Stage 1 Initial Bring Up](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/guide-for-porting.md#stage-1-initial-bring-up), it is mentioned that “it is expected that the interpreter will take 1-2 months to enable for an engineer familiar with the CoreCLR codebase”. This information is very useful. However, the similar information is not given in the later sections in Stage 1 and in Stage 2-5. Is it possible to give the time and engineer estimation of other parts?

Thanks!

**Comment by theaoqi** [comment]
Related to #716

**Comment by jkotas** [comment]
cc @davidwrighton

**Comment by davidwrighton** [comment]
Unfortunately, man hour estimates for this work is very difficult as it has been a very long time since it was last done, and the runtime has become substantially more portable in the intervening years, so old timeframes are likely not valid.

I cannot provide an estimate for the timescale to port the JIT at all. Please ask @BruceForstall if he is able to provide estimates. My estimate for the VM side of the work is approximately 2 clr experienced engineers for 1-2 years. In general, the VM tasks are not particularly difficult, but there are quite a few of them, and some failures can be time consuming to diagnose especially for developers inexperienced in the codebase. This also assumes the presence of 2-3 engineers responsible for managing build and test automation, and providing them with a continuing series of problems to fix.

**Comment by BruceForstall** [comment]
I agree with @davidwrighton that it is very difficult to provide good porting time estimates. For the JIT, it greatly depends on how similar (or different) the target architecture is from one of the existing supported architectures. For example, ARM32 and ARM64 had many similarities and could share some code, or at least some ideas. It also depends greatly on having plenty of available, high-quality (that is, reliable) target hardware for use in testing, including in the automated testing infrastructure. Porting where the target machines are simulators or slow, flaky hardware, is more costly. Much of our time has historically been spent in this kind of infrastructure work. A rough estimate of 4 experienced engineer man-years might be in the right range to port the JIT from zero to shipping, given those previous caveats.

**Comment by theaoqi** [comment]
Thank you very much, @davidwrighton and @BruceForstall . Your replies already help a lot!
