### ISSUE TITLE
Binary Deserialisation in .Netcore 3.0 :: Getting System.InvalidCastException

### ISSUE THREAD

**Issue by AgnesAarthy** [dotnet/runtime#31611]
Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Specified cast is not valid.
   at System.Data.DataTable..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)

**Comment by GrabYourPitchforks** [comment]
Hi @AgnesAarthy. Thanks for the report. I looked into this but cannot repro the problem on my local machine. If you could provide the full stack trace or provide sample code that demonstrates the issue we can look into it further..

**Comment by AgnesAarthy** [comment]
Hi Broderick,

The Issue comes when I am trying to serialise the data using binary formatter in .NetCore 3.0 Linux platform and Deserialise the data in .NetFramework 4.6.2 (any versions) windows platform.

As mentioned I have subsystem interactions, where the above scenario comes into picture.

**Comment by GrabYourPitchforks** [comment]
Root cause is that the type `System.Data.SerializationFormat` got moved from assembly `System.Data` in Mono and Full Framework to `System.Data.Common` in .NET Core, but no `[TypeForwardedFrom]` attribute is present on the type.

In .NET Core, when serializing, the assembly-qualified name `"System.Data.SerializationFormat, System.Data.Common, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"` is written to the serialized data stream. However, in Mono / Full Framework, since that assembly does not exist the deserialization logic silently replaces the value with an instance of type `TypeLoadExceptionHolder`.

https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/mscorlib/system/runtime/serialization/formatters/binary/binaryobjectreader.cs#L496-L501

Normally such an error occurs at the top level of the deserialized object graph, and the deserializer will turn it into the expected `SerializationException` with an error message that states the type or assembly could not be loaded.

https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/mscorlib/system/runtime/serialization/objectmanager.cs#L953-L954

However, in this case the error doesn't occur at the top level of the object graph. It instead allows the `DataTable` ctor to proceed with partially hydrated data. In particular, the line below throws the `InvalidCastException` because it's trying to cast an object of type `TypeLoadExceptionHolder` (since it's still present in the object graph) to `SerializationFormat`.

https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/System.Data/System/Data/DataTable.cs#L218

**Comment by danmosemsft** [comment]
@ViktorHofer added `[TypeForwardedFrom]` on (presumably) every `[Serializable]` type, this one was simply missed because it was transitive and implicitly serializable, I assume.

**Comment by danmosemsft** [comment]
@AgnesAarthy any interest in offering a PR? It looks like what's required is

1. Edit [BinaryFormatterTestData.cs](https://raw.githubusercontent.com/dotnet/runtime/master/src/libraries/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs) to add a test. Probably reasonable to just take one of the 3 existing DataSet serialization tests eg, change 
```c#
yield return new object[] { new DataSet() { Locale = CultureInfo.InvariantCulture },`)
```
to
```c#
yield return new object[] { new DataSet() { Locale = CultureInfo.InvariantCulture, RemotingFormat = SerializationFormat.Binary },`)
```
2. Execute this by running the `System.Runtime.Serialization.Formatters` tests and verify it fails withe 
3. It will fail because when serialized it will no longer match the expected data. Update this "blob" starting with `AAEAAAD/////AQAAAAAAAAAMAgAAAE5TeXN0ZW0...`) to match what the test expects - it will dump this for you.
4. Run the test again, it will now fail with the invalid cast exception.
5. To [System.Data.SerializationFormat](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Data.Common/src/System/Data/DataSerializationFormat.cs#L7) add the attribute `[System.Runtime.CompilerServices.TypeForwardedFrom("System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")]`
6. Build and run the test it should now pass.



https://source.dot.net/#System.Data.Common/System/Data/DataTable.cs,1117

**Comment by danmosemsft** [comment]
We do not plan to add support for SerializationFormat.Binary. We do expect SerializationFormat.Xml, which is the default, and that should never appear in the payload so it's not an issue that it isn't forwarded.
