### ISSUE TITLE
Interop+Crypto+OpenSSLCryptographicException while connecting to DB2

### ISSUE THREAD

**Issue by castasint** [dotnet/runtime#31703]
I am trying to connect a DOTCORE application with the IBM DB2 database. My development environment is a windows one. I am able to connect to the database on the development environment. 

Then to deploy, I created an SCD package and copied the folder into an RHEL Linux box.  When I am running the application, I am getting the below error.

Some Info - 

Visual Studio - 16.4.4
Target RunTime - .NET CORE 3.1

Any leads on how this can be addressed? 

Exception: 
![image](https://user-images.githubusercontent.com/16588875/73706485-973a6900-471e-11ea-86b3-8c0e4aba9d09.png)

csproj file-

![image](https://user-images.githubusercontent.com/16588875/73706519-a7524880-471e-11ea-9ac4-7f524178c2a5.png)

**Comment by vcsjones** [comment]
It looks like the DB2 library is attempting to use the DES cipher. My understanding of RHEL is that DES was [removed in version 7][1] which seems to be supported by the message “disabled for fips”. This is likely because DES (the single 56-bit version) is not regarded as secure or modern, and not FIPS 140-2.

Perhaps there is a way to configure the library and server to support a more modern encryption algorithm like AES?

[1]: https://access.redhat.com/articles/3642912

**Comment by vcsjones** [comment]
It seems that DB2 has a connection string property called "ClientEncAlg" that allows specifying AES. So in your connection string, perhaps you can try setting ClientEncAlg=AES in your connection string or DB2ConnectionStringBuilder?

To give a bit of background, .NET Core does not implement any cryptography by itself - it provides managed APIs that wrap a cryptographic library provided by the operating system. Different operating systems offer different cryptographic functionality. In the case of Linux, .NET Core gets cryptographic support from OpenSSL. RHEL appears to be building or configuring OpenSSL without DES support since it has long been deprecated.

The reason it works for you on Windows is because Windows has not removed DES support from CNG.

**Comment by castasint** [comment]
I have tried adding the ClientEncAlg setting in the connection string as well as DB2ConnectionStringbuilder. Yet, it did not work. See below. The same exception is coming up.

![image](https://user-images.githubusercontent.com/16588875/73769317-77e42000-47a0-11ea-8fe0-41603a30629c.png)

**Comment by castasint** [comment]
![image](https://user-images.githubusercontent.com/16588875/73769432-a6fa9180-47a0-11ea-9d5c-98e51149586e.png)

**Comment by vcsjones** [comment]
I think there are two options here.

1. Figure out how to get the DB2 library working without DES.
2. Disable FIPS requirement for RHEL.

The first option is very much the better one.

My understanding is that FIPS enforcement for REHL is an opt-in policy. It seems like the RHEL instance you are deploying to has FIPS enabled intentionally, thus DES is disabled. Can you confirm if the RHEL instance is indeed configured to require FIPS algorithms?

/cc @bartonjs

**Comment by danmosemsft** [comment]
@castasint as an aside, could you please paste in callstacks and errors as text, rather than screenshots? That way they can be searched. Just copy/paste, and put a line above with triple-back-ticks to format it.

**Comment by castasint** [comment]
Here is the call stack

```
System.TypeInitializationException: The type initializer for 'IBM.Data.DB2.Core.DB2Trace' threw an exception.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0607B0A3:digital envelope routines:EVP_CipherInit_ex:disabled for fips
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.OpenSslCipher.OpenKey(IntPtr algorithm, Byte[] key, Int32 effectiveKeyLength)
   at Internal.Cryptography.DesImplementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Byte[] iv, Int32 blockSize, Boolean encrypting)
   at Internal.Cryptography.DesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
   at Internal.Cryptography.DesImplementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
   at System.Security.Cryptography.DESCryptoServiceProvider.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
   at IBM.Data.DB2.Core.DB2ConnPool.GetDB2ConnPool()
   at IBM.Data.DB2.Core.DB2ConnPool..ctor()
   at IBM.Data.DB2.Core.DB2Trace..cctor()
   --- End of inner exception stack trace ---
   at IBM.Data.DB2.Core.DB2ConnPool.Open(DB2Connection connection, String& szConnectionString, DB2ConnSettings& ppSettings, Object& ppConn)
   at IBM.Data.DB2.Core.DB2Connection.Open()
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\<<Username>>\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 42 ```
