### ISSUE TITLE
Removing the use of RefPath and binplacing for old frameworks

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#31844]
_//edited by @ViktorHofer, copied from https://github.com/dotnet/runtime/issues/31844#issuecomment-588418508_

Make our non-NetCoreAppCurrent projects behave more like normal SDK projects with respect to references.
Eliminate the use of artifacts\bin\ref as the reference path for all frameworks exception NetCoreAppCurrent.  Eliminate the need of depprojs.

Next steps:
- [x] Enable restore for ref and src projects: https://github.com/dotnet/runtime/pull/33242
- [x] Allow non-NetCoreAppCurrent projects to use implicit shared framework (which requires restore).
- [x] Add PackageReferences to any project that relies on a package that was previously restored by depprojs.  EG: System.Memory for NETStandard2.0.  Make sure to use version.props to represent the dependency version: https://github.com/dotnet/runtime/pull/33422
- [x] Handle references to other live-built libraries.  EG: System.Collections.Immutable depends on System.Reflection.Metadata.  This could either be done with a projectreference to the reference assembly, or a projectreference to the src assembly.
- [x] Once done for all projects, delete depprojs that were responsible for building out ref packs.  Ideally we can delete all depprojs and just meld whatever remaining restores were happening into toolset restore.

cc @ericstj @ViktorHofer

**Comment by ViktorHofer** [comment]
It has been some time since I last used implicit framework references. Do I remember correctly that when enabling the build would use the default references that come with the framework and by either referencing via ProjectReferences or named references conflict resolution would overrule the default references with the live built references? Does all that apply to .NET Framework as well? cc @ericstj

**Comment by ericstj** [comment]
This is more/less true.   We may need to fix / modify conflict resolution to work with ProjectReferences: https://github.com/dotnet/sdk/issues/2674.  .NETFramework has a behavior defined by SDK + [Arcade](https://github.com/dotnet/arcade/blob/c7dca08a5b2dc589392b2a7680c5d64f057ddc0a/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L134-L136), we'd use that.

We better not need conflict resolution with .NETFramework, that would imply we're OOBing .NETFramework assemblies... which isn't very popular...  Even so, yes it works for .NETFramework.

I think in most of our cases we wouldn't need ProjectReferences because we'd instead want to compile against the minimum thing provided by the framework and then our packaging infra would deal with getting the right version for PackageReferences.  Testing infra (today) would still run on latest.  We'd only need the P2P's when we wanted to use new surface area.

**Comment by ViktorHofer** [comment]
> We better not need conflict resolution with .NETFramework, that would imply we're OOBing .NETFramework assemblies... which isn't very popular... Even so, yes it works for .NETFramework.

Funny thing, we already do but not because of any reason, just for consistency with netcoreapp.

I more or less understand what you are proposing here but I thing we should write this down in more detail.

**Comment by ViktorHofer** [comment]
@ericstj just discussed with @Anipik that will tackle this. Can you please help us identify goals and required steps here? Thanks

**Comment by ericstj** [comment]
Goal:
Make our non-NetCoreAppCurrent projects behave more like normal SDK projects with respect to references.
Eliminate the use of artifacts\bin\ref as the reference path for all frameworks exception NetCoreAppCurrent.  Eliminate the need of depprojs.

Next steps:
1. Enable restore for ref and src projects.
2. Allow non-NetCoreAppCurrent projects to use implicit shared framework (which requires restore).
3. Add PackageReferences to any project that relies on a package that was previously restored by depprojs.  EG: System.Memory for NETStandard2.0.  Make sure to use version.props to represent the dependency version.
4. Handle references to other live-built libraries.  EG: System.Collections.Immutable depends on System.Reflection.Metadata.  This could either be done with a projectreference to the reference assembly, or a projectreference to the src assembly.
 5. Once done for all projects, delete depprojs that were responsible for building out ref packs.  Ideally we can delete all depprojs and just meld whatever remaining restores were happening into toolset restore.

**Comment by ViktorHofer** [comment]
Assigning myself as well as the project restore work is already ongoing. @Anipik my work also covers some of the other todos so I recommend to not start with this work yet until I can clearly draw a line.

**Comment by ViktorHofer** [comment]
@ericstj copying your instructions to the top post.

**Comment by Anipik** [comment]
@ViktorHofer can i start working on this now ?

**Comment by ViktorHofer** [comment]
Thanks Anirudh but I already started with the next steps in a private branch.
