### ISSUE TITLE
EditorConfig for csharp_indent_case_contents_when_block is non-ideal

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#319]
The .editorconfig style is currently set to the following:
https://github.com/dotnet/runtime/blob/381372f6f12884caee5bb90f52649040827e19cc/.editorconfig#L32-L33

This results in the following rule:
```csharp
switch (value)
{
    case 0:
        break;

    case 1:
        {
            break;
        }
}
```

We should instead change it to:
```
csharp_indent_case_contents = true
csharp_indent_case_contents_when_block = false
```

Which results in the following formatting:
```csharp
switch (value)
{
    case 0:
        break;

    case 1:
    {
        break;
    }
}
```

The `csharp_indent_case_contents_when_block` rule was only added a couple releases ago and defaults to `true` in VS due to backcompat reasons: https://github.com/dotnet/roslyn/pull/20292

**Comment by tannergooding** [comment]
CC. @stephentoub

**Comment by stephentoub** [comment]
I'm not necessarily sure it's better.  It makes some things look a bit better, and others worse.  For example, instead of:
```C#
case A:
    {
        ...
    }
    break;
case B:
    {
        ...
    }
```
VS auto-formatting changes the above to:
```C#
case A:
{
    ...
}
break;
case B:
{
    ...
}
```
which in my opinion is harder to read.  You can manually move the break inside the braces, e.g.
```C#
case A:
{
    ...
    break;
}
case B:
{
    ...
}
```
but you still have the closing brace aligned with the subsequent case, which for me is harder to read as the case no longer stands out.  So you can then introduce a blank line before the case, but now it's inconsistent with other cases that don't use braces, and in particular ones that all map to the same block.  A game of whack-a-mole.

While the current formatting may not be ideal, changing it just introduces a different set of problems, IMO.

**Comment by joperezr** [comment]
I agree with @stephentoub in terms of readability. I'm closing this one for now but @tannergooding feel free to reopen if you think otherwise and we can revisit and ask more people about their preference.
