### ISSUE TITLE
Feature Request: Batch GC allocation for an object aggregation

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/runtime#31906]
Classes are very frequently have an aggregation part, for example:
```CSharp
    public class MyAsyncClass
    {
        private readonly ManualResetEvent _someEvent = new ManualResetEvent(false);
        private readonly List<object> _someCollection = new List<object>();
    }
```
The lifetime of the objects in such aggregations are *most probably* 100% the same.

And GC optimization is possible. Rather than have 3 dedicated separately managed chunks,
the GC can allocate one chunk of memory:
```
---- Memory representation of the chunk ------------------------
MyAsyncClass header // With flag 'chunk master' set            |
MyAsyncClass fields                                            |
----                                                           |
chunkStartOffset: NativeInt // For ManualResetEvent            |
ManualResetEvent header // With flag 'chunk master' unset      |
ManualResetEvent fields                                        |
----                                                           |
chunkStartOffset: NativeInt // For List<object>                |
List<object> header // With flag 'chunk master' unset          |
List<object> fields                                            |
----------------------------------------------------------------
```

In theory it's possible to add this feature only on the JIT level.

The existing binaries could start benefit from this feature immediately (up to 10% of speedup possible)
The new code written with assumption that aggregates allocation is cheap can be optimized even better.

P.S
```struct``` is not an answer to everything, frequently you need to pass aggregation parts by reference.

**Comment by scalablecory** [comment]
> The existing binaries could start benefit from this feature immediately (up to 10% of speedup possible)

Where do you get this 10% from? Have you prototyped this?

**Comment by dmitriyse** [comment]
@scalablecory unfortunately it's a hard feature for prototyping. The estimate is just empirical.

Let's try to estimate "more precisely":
1) 1/2 of the objects have an aggregation part.
2) Aggregation asymptotically have 3 objects.
3) GC throughput overhead by adding this feature is 10%.
Concluding we have ~(50%-10%)=40%  more throughput of GC. 

If we dump the memory of some workload and perform the statistical analysis we will receive the strict numbers (above).

It's very hard to predict the impact of GC throughput on an application performance.

**Comment by dmitriyse** [comment]
The one story is the impact of this feature on existing binaries.
The totally different story is the impact to the new code targeting this feature.

If I know that aggregation allocation is cheap regardless of amount of objects in the allocation, I would create bigger aggregations for performance critical objects with less lazy allocations.

**Comment by benaadams** [comment]
> The lifetime of the objects in such aggregations are 100% the same.

Do you mean because they are `readonly` fields? So would be an optimization to aggregate the readonly chunks?

> In theory it's possible to add this feature only on the JIT level.

I assume it could only be done if the constructors inlined; or there was annotation on the constructors highlighting size and readonly field aggregate. Likely to have similar issues to Jit stack allocation of objects? https://github.com/dotnet/runtime/issues/1661#issuecomment-573868943

**Comment by dmitriyse** [comment]
>>The lifetime of the objects in such aggregations are 100% the same.

>Do you mean because they are readonly fields? So would be an optimization to aggregate the readonly chunks?

When JIT compiles type and its constructors it can infer that some of ```readonly``` fields could be allocated in a batch.
(Relatively deterministic way)
```CSHarp
    public class SomeAggregate
    {
        private readonly List<string> _myList; // Marked by JIT as allocated within parent chunk

        private readonly object _state; // Marked by JIT as regular reference

        public SomeAggregate(bool myFlag)
        {
            // Allocated inside the parent chunk.
            _myList = new List<string>();

            // JIT Declines allocation in the parent chunk due to the type-variance.
            _state = myFlag ? (object)"Test" : new[] { 'T', 'e', 's', 't' };
        }
    }
```

Not all readonly fields could be included into the object allocation chunk.

**Comment by AartBluestoke** [comment]
i can see 2 issues, as this optimisation boils down to escape analysis:
1. private readonly's might escape, so the context of all uses of the readonly would have to be known:

public class SomeAggregate{
    private readonly List<string> _myList;
    public IReadonlyList<string> PeekAtList(){return _myList.asReadOnly();} // definitely escapes
    public string SerializeMyList(){string.Join(",",_myList);} // definitely escapes from the POV of the jit, that's just an arbitrary function call accepting the list.
}

2. reflection makes all this hard to handle, as _myList can be set via reflection to point outside the object. we would need a way to *Gaurantee* that reflection setting object aggregates was safe.

**Comment by dmitriyse** [comment]
@AartBluestoke escape analysis can be avoided. If some nested objects will escape the owner, then the owner will live in memory little bit longer (some rounds of GC). We can rely just on case-probability that readonly fields initialized in the constructor most probably are not escaping.

**Comment by mikedn** [comment]
> Rather than have 3 dedicated separately managed chunks, the GC can allocate one chunk of memory:

What is a "separately managed chunk"? How does "separately managed" or not affect throughput?

> up to 10% of speedup possible

Even a magician would have a hard time pulling such a number from the hat.

> If we dump the memory of some workload and perform the statistical analysis we will receive the strict numbers (above).

It looks like the magician did actually pull a fox from the hat and now he's trying to convince the public that the fox is in fact a rabbit.

**Comment by Suchiman** [comment]
Which part of the GC is this supposed to optimize? The allocator or the collector? The existing pointer bump fast path allocator is already extremely fast and the collector would still need to traverse through the subobjects, e.g. to mark the objects referenced from the `List<object>`. Objects allocated chronologically closely together are typically also co-located on the heap. Requiring a `IntPtr chunkStartOffset` on the other hand decreases heap density, wasting more memory and thus increasing the chance that the fast path allocator has to fallback to the slow path to search the free list, trigger a GC or allocate more memory.

**Comment by dmitriyse** [comment]
> Which part of the GC is this supposed to optimize? The allocator or the collector? 

All of these:
1) Allocation 
2) Mark phase (not sure, still all roots should be visited, interior pointers processed)
3) Collect phase

The amount of elements in all algorithms should be reduced.
Algorithms contains iterations, if you are iterating over all managed objects it's one number,
if you are iterating over chunks (maser managed object) you have less iterations.


> The existing pointer bump fast path allocator is already extremely fast

```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-8550U CPU 1.80GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.100
  [Host] : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

|                  Method |        Mean |     Error |    StdDev | Ratio | RatioSD |
|------------------------ |------------:|----------:|----------:|------:|--------:|
|               EmptyLoop |    311.2 us |   6.22 us |   8.30 us |  0.18 |    0.01 |
|        StaticMethodCall |  2,662.8 us |  45.24 us |  42.32 us |  1.53 |    0.02 |
|   MemberMethodCallNoArg |  1,735.8 us |  17.82 us |  16.66 us |  1.00 |    0.00 | <--- Baseline
|    MemberMethodCall1Arg |  1,796.3 us |  19.88 us |  18.60 us |  1.03 |    0.02 |
|    MemberMethodCall2Arg |  1,873.7 us |  23.09 us |  21.60 us |  1.08 |    0.01 |
| MemberMethodCall2ArgRet |  1,724.8 us |  13.70 us |  12.82 us |  0.99 |    0.01 |
|       VirtualMethodCall |  2,114.4 us |  36.72 us |  34.35 us |  1.22 |    0.02 |
|          ObjectCreation |  5,295.4 us |  71.87 us |  63.71 us |  3.05 |    0.05 | <------- Cheap but not free
|              ActionCall |  1,787.0 us |  26.41 us |  23.41 us |  1.03 |    0.02 |
|            LockOperator | 20,281.6 us | 404.48 us | 539.96 us | 11.80 |    0.31 |
| IntInterlockedIncrement |  5,523.9 us | 102.12 us |  90.53 us |  3.18 |    0.06 |
|      IntCompareExchange |  5,631.8 us | 127.85 us | 246.33 us |  3.37 |    0.18 |
|     LongCompareExchange |  5,634.5 us | 105.11 us |  98.32 us |  3.25 |    0.06 |
|   ObjectCompareExchange |  7,794.0 us | 123.72 us | 115.72 us |  4.49 |    0.06 |
|            IntIncrement |    540.3 us |   8.94 us |   8.36 us |  0.31 |    0.01 |
```

Fast pass of GC allocation is extremely fast, I agree. 
3 calls to a function === one GC allocation.

Even saving 5+ such cheap GC allocation call per aggregation root  can give 1.5x+ speed up on some workload. For example denationalization of JSON POCOs.
====
I am not saying that this feature 100% should be implemented and it for sure give performance super boost.
But the direction of the optimization looks promising from the first look.

**Comment by scalablecory** [comment]
I'd love to see a prototype made that can be benchmarked under a wide array of scenarios. I think this is too complex a change to be able to realistically estimate what effects it will have on perf.

**Comment by Suchiman** [comment]
In general this feature sounds to me like an automatic form of an arena allocator for which there was a prototype made but without significant gains IIRC.

**Comment by mikedn** [comment]
> Mark phase (not sure, still all roots should be visited, interior pointers processed)

Presumably by "interior pointers" you refer to `_someEvent` & `_someCollection` in your example, not to what GC typically refers to as interior pointers - pointers inside the managed object. Real interior pointers are a pain in the back for a GC so it's probably not something you would want to use often.

> The amount of elements in all algorithms should be reduced.

Well, yes. Except that in the case of the mark phase the "element" is a reference to an object and not an object. Most of the cost of marking a GC heap containing 2 objects - an 1 million `object`s array and a single `object` instance referenced from every array element is traversing the array.

Ultimately it may be possible to get an improvement in this phase but that probably requires the GC to keep track of such fields in a special manner, in order to avoid unnecessary marking. Not exactly trivial.

> Collect phase

It's not clear why you expect any improvement in this phase, 3 objects of 32 byte each take 96 bytes even if they're allocated together or not. So the cost of moving is the same, unless the GC can perhaps take advantage of it somehow (e.g. use SSE/AVX instructions to do it). Or perhaps it can do this already when it finds multiple contiguous live object. That's something that should be checked before speculating that aggregate allocations may be an improvement in this GC phase.

The only place where you may get an improvement is allocation itself. At least in theory, one call to runtime's allocation function is better than 3, right? Maybe, but even that is not trivial to implement as the runtime doesn't allocate blobs of bytes or whatever size, it allocates objects - blobs of bytes having a method table at offset 0 that the GC uses to figure out the size of the blob. You want to allocate 3 objects at once? Well, you'll have to figure out how to communicate 3 method table pointers to the allocation function. Or 4 or 2 or whatever. Perhaps not that complicated but you may find that some of the speedup a single allocation call may provide actually gets lost in extra bookkeeping.

BTW:

> In theory it's possible to add this feature only on the JIT level.

No, it is not possible.

**Comment by Maoni0** [comment]
I agree with @mikedn. 

this sounds like something that would require a lot of changes but the benefit is very questionable. I'm unsure about your estimate of "1/2 of objects have an aggregation part" if you assume only the readonly fields can be aggregated. you are assuming readonly fields appear very often. that hasn't been my experience but I welcome data that shows otherwise. 

> Algorithms contains iterations, if you are iterating over all managed objects it's one number,
if you are iterating over chunks (master managed object) you have less iterations.

this also sounds weird to me. you don't just "iterate over all the objects there are", you iterate over something that serves some purpose together. in your example, one might want to iterate through all MyAsyncClass instances and that number does not change with what you are proposing. 

I don't see how this reduces GC cost, a reference is a reference and the number of references does not change with your proposal. 

based on the above I'm closing this issue. please feel free to reopen it if you think there's evidence that I missed something.
