### ISSUE TITLE
Settings for a single-file WinForms app goes into new folders for every publish

### ISSUE THREAD

**Issue by livarcocc** [dotnet/runtime#31959]
_From @felizk on Saturday, September 28, 2019 9:41:57 PM_

## Steps to reproduce
 * Publish a self contained WinForms app. 
 * Run it.
 * Change and save some Settings (using the WinForms style .settings)
 * Notice settings are saved in LocalAppData ultimately in a folder with this kind of postfix: "_Url_2z3wslwxp2unr2f2llkyxtrbrq3rb5cd"
 * Repeat, notice the postfix has changed and settings are not reused

## Expected  behavior
To be able to persist settings between versions of the application.

## Actual behavior
Every time you publish, settings are effectively wiped.

_Copied from original issue: dotnet/cli#12749_

**Comment by swaroop-sridhar** [comment]
paul1956, Yes, in .net 5 single-file apps, it is recommended that assets be stored as resources and loaded through resource handling API. However, this configuration will not work for app-configuration that should service across updates. The settings should be stored elsewhere, separate from the app, which will be replaced in each build.

**Comment by swaroop-sridhar** [comment]
@JeremyKuhne @paul1956 

There are two levels of problem/solutions to this problem:
(1) The specific case of config file, computed as:
`Appdomain.CurrentDomain.BaseDirectory()\Assembly.GetEntryAssembly().ManifestModule.Name` + `.config` 

In .net 5 single-file apps, the `AppContext.BaseDirectory` will be set to the location of the single-file app  -- since there may not be a location associated with the `app.dll` at all. This will make the current code work OK.  That is, the `app.dll.config` file will live beside the single-file `app.exe`, even though there's no corresponding `app.dll`.

(2) Assemblies loaded from within single-file apps will be treated as if loaded from a memory-stream. So `Assembly.Location` will return `null`. Apps that depend on assembly-location semantics will need to be aware of this distinction. However, we can consider providing APIs to abstract this distinction for specific use-cases. If you have any concerns beyond the `AppContext.BaseDirectory` please let us know at your earliest convenience. Thanks.

CC: @jkotas

**Comment by swaroop-sridhar** [comment]
This is a variant of https://github.com/dotnet/runtime/issues/3704

**Comment by paul1956** [comment]
@swaroop-sridhar OK, for now storing new things in Resources doesn't work in Visual Studio for Core apps (I assume that will be fixed). Settings are the things that need to be preserved across apps and are handled by the run-time so it should just work. Finding files in other places, sounds like should be discouraged, though some examples might be needed dealing with application files in Single-File Apps. If I remember correctly in WPF "assets" are stored in a relative directory not in a resource so that might still be an issue.

FYI Some of the solutions you find on StackOverflow below but it sounds like both are wrong going forward
```VB
    Private Function GetAssetPath() As String
        Using processModule As ProcessModule = Process.GetCurrentProcess().MainModule
            Return Path.GetDirectoryName(processModule?.FileName)
        End Using
    End Function
```
and
```VB
        'To get the location the assembly normally resides on disk or the install directory
        Dim CodeBasePath As String = Reflection.Assembly.GetExecutingAssembly().CodeBase
        'once you have the path you get the directory with:
        Dim AssetsPath As String = Path.GetDirectoryName(CodeBasePath)
```

**Comment by karelz** [comment]
@swaroop-sridhar only 1 area label per issue please - see [why](https://github.com/dotnet/runtime/blob/master/docs/project/issue-guide.md#motivation-for-triage-rules).

**Comment by agocke** [comment]
This should be fixed now that apps are not extracted.
