### ISSUE TITLE
RyuJIT: Optimze Type.GetType("type id str") to type handle

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#31974]
I wonder if it makes sense in RyuJIT to optimize things like
```csharp
Type type = Type.GetType("Foo.MyType"); // and, perhaps,  typeof(T).Assembly.GetType
```
to a runtime equivalent of :
```csharp
Type type = typeof(Foo.MyType); // to CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
```
Once https://github.com/dotnet/runtime/pull/1378 is merged there will be `getStringLiteral` API for ldstr tokens.

Example: [Environment.Unix.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Environment.Unix.cs#L81) (on tier1 compilation most assemblies/types most likely will be already known/loaded, e.g. via the same code but on tier0 🙂)

Or this is how we detect mono runtime:
```csharp
bool isMono = typeof(object).Assembly.GetType("Mono.RuntimeStructs") != null;
```

/cc @jkotas @MichalStrehovsky

**Comment by jkotas** [comment]
I do not think this optimization is useful.

> Example: Environment.Unix.cs 

This is one-time initialization already. This method won't ever reach tier 1.

> `typeof(object).Assembly.GetType("Mono.RuntimeStructs")`

This is using private reflection against internal runtime implementation details. It is something to discourage, not encourage by optimizing it.

This should be fixed by having proper public APIs to detect the runtime you are running on.

**Comment by EgorBo** [comment]
Ok, closing it then
