### ISSUE TITLE
[QUIC] Use client TLS options in QUIC

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32069]
We need to get client certificates working in QuicConnection SSL options.

https://github.com/dotnet/runtime/blob/5c6f5b14f0688b20ef339773854ff92e01807cde/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs#L88-L93

**Comment by ManickaP** [comment]
Was this solved by https://github.com/dotnet/runtime/pull/50613? Could we close this? Or what is missing?
cc: @wfurt @scalablecory

**Comment by wfurt** [comment]
#50613 is not sufficient as it is focusing on typical use e.g. sever certificates.
We don't have handling for client certificates and that will also need msquic changes AFAIK (at least for OpenSSL). I'm yet to figure out if `LocalCertificateSelectionCallback` would work e.g. providing certificate via callback in middle of handshake instead of specifying it upfront. 

CipherSuitesPolicy support was added to msquic recently but it is not plumbed from runtime AFAIK. 

cc: @nibanks

**Comment by wfurt** [comment]
`SslClientAuthenticationOptions.LocalCertificateSelectionCallback` depends on https://github.com/microsoft/msquic/issues/1249

**Comment by ManickaP** [comment]
Triage: we have a basic support for client certificate and the callback is not yet supported by msquic, we cannot fully fix it for 6.0.
