### ISSUE TITLE
`hostfxr_run_app` shuts down coreclr too early

### ISSUE THREAD

**Issue by sanosdole** [dotnet/runtime#32112]
I'm implementing a native node plugin that hosts dotnet core applications (<https://github.com/sanosdole/nodeclrhost>).

I recently switched from using the `coreclrhost.h` based hosting API to the `hostfxr` API.
After switching debugging the dotnet application did no longer work.

Some resarch revealed that debugging only works until `coreclr_shutdown` is called.
`hostpolicy.cpp` line 255 and following calls this directly after calling `coreclr_execute_assembly`.

At the moment I work around this Problem by replacing the call to `hostfxr_run_app` with manually loading the `coreclr.dll` and calling `coreclr_initialize`, `coreclr_execute_assembly` & `coreclr_shutdown` directly using the properties retrieved from the `hostfxr`.

I believe that a scenario that calls the entry point of an assembly to set up an application and keeps it running for some time after that is not unusual. E.g. any Server hosting ASP applications could behave like this.

So either I'm misunderstanding the `hostfxr` API or it lacks support for this kind of scenario.

**Comment by jeffschwMSFT** [comment]
Here is a sample that shows how to call multiple assemblies from a native host: https://github.com/dotnet/samples/tree/master/core/hosting/HostWithHostFxr.   In .NET Core 3 we introduced nethost to help with this scenario.  The goal is that you should not need to load hostfxr or coreclr directly when hosting .NET Core.

cc @elinor-fung

**Comment by sanosdole** [comment]
I know this example, as my implementation is based upon it.

The example uses `hostfxr_initialize_for_runtime_config_fn` & `hostfxr_get_runtime_delegate`.
I`m using `hostfxr_initialize_for_dotnet_command_line` and want to use `hostfxr_run_app` after that.

This works basically, but debugging the hosted application breaks. If i take the runtime properties from the context initialized by `hostfxr_initialize_for_dotnet_command_line` and load the coreclr directly instead of using `hostfxr_run_app` it works. The only difference i can see from reading the hostfxr & hostpolicy source code is the timing when `coreclr_shutdown` is called.
I can even reproduce the debugging failure by calling shutdown directly after `coreclr_execute_assembly`.

Maybe `hostfxr_initialize_for_dotnet_command_line` is the wrong start for my use case?
My host implementation does not know the name of the entry point of the assembly it should host,
so I can not see how I should implement my use case using `hostfxr_initialize_for_runtime_config_fn` & `hostfxr_get_runtime_delegate`. 

- Is there a way to specify that i want a delegate for the assemblies entry point without knowing its name?
- When is the shutdown called in the `hostfxr_initialize_for_runtime_config_fn` & `hostfxr_get_runtime_delegate` method?

**Comment by vitek-karas** [comment]
The `coreclr_execute_assembly` should only return once the app's `Main` returns. That should obviously only happen when everything in the app is done. So the fact that hostpolicy calls `coreclr_shutdown` right after that should not matter much.
Do you see the `coreclr_execute_assembly` return too early?

**Comment by elinor-fung** [comment]
`hostfxr_run_app` will wait for the application to finish running before shutting down, so as long as the application is still running, `coreclr_shutdown` will not be called.

Some questions, since I'm not sure I understand the scenario:
- What application are you trying to debug after the executed .NET Core application exits?
- Are you attempting to execute multiple .NET Core applications in the same process (e.g. execute another application after the first one exits)?

**Comment by sanosdole** [comment]
I think that's the misunderstanding here. The entry point of the dotnet assembly just registers some callbacks (e.g. HTTP request handler or events in Electron) and returns. This is required so the node thread is unblocked again. So my application is still running after the main entry point is completed.

I want to debug the application after the entry point returned.

I could also do with an asynchronous main that completes when we want to shutdown, but blocking the invoking thread is not working.
I also require that the main thread is invoked on the node thread, so JS interop works during the set up. Also a native thread local is used to associate the node environment with the managed application.

I hope this makes my scenario and its requirements more clear. Most of it comes from the single threaded nature of node which prevents blocking the entry point until the application is finished.

As I have a work around, this could be seen more like a feature request to support this scenario.

**Comment by vitek-karas** [comment]
What you describe is typically not considered an "application" in the .NET Core terminology. A .NET Core app is code which starts, runs and exits on its own. Once it exits the whole thing (most commonly process) is done (including the runtime).

Your scenario is much more like a component, where you load the component into already running process to do some things.

The `hostfxr_run_app` is specifically designed for the "app" scenario only. To load a component the `hostfxr_get_runtime_delegate` is the right API. As for your comment of not knowing what the entry point is going to be: you can work around that by calling your own managed function via the hosting APIs and then from the managed code load the desired component, find the entry point in it (whatever that means) and run it.

**Comment by sanosdole** [comment]
My host implementation knows nothing about the dotnet assembly it loads.

So I see two options where the hostfxr API can be improved to support my scenario:
- `hostfxr_run_app` supports asynchronous entry points (usually `Program.Main`)
- `hostfxr_get_runtime_delegate` can be used to retrieve the entry point without passing a type/method name

I can replace my workaround (loading coreclr manually) by requiring a type/method name in addition to the assembly in my node API so i can call `hostfxr_get_runtime_delegate`.
This will only work if `coreclr_shutdown` is only called when closing the `hostfxr` context. Is this correct?

Maybe there is an easy way to find out the entry point (Startup object, usually Program.Main) of an assembly?

**Comment by vitek-karas** [comment]
In the case of `hostfxr_get_runtime_delegate` the `coreclr_shutdown` is actually never called as currently CoreCLR doesn't support clean unload from a process (so there's no point in shutting it down in the component case). We call it in the `hostfxr_run_app` scenario to be compatible with what happens if you just run the app directly (without native hosting).

What I find weird in your scenario is that the "apps" you're talking about will not run on their own - if you simply start them directly (via their own .exe or via `dotnet.exe`) they would immediately exit as well. The `hostfxr_run_app` will behave the same way - as expected.

So in your case these are really "components" which typically have some agreed upon interface - since this varies wildly between different component systems, the hosting layer does not (and should not) try to prefer any one case over the other. You can choose to use the "Method marked as entry point" as the interface, but in that case you have to implement the code to find and invoke it. In managed code this is easy, load the component's assembly and call [`Assembly.EntryPoint`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.entrypoint?view=netcore-3.1) property to get it.

So the proposed solution is to have a small managed `MyComponentHost.dll` with a static well defined method which you call through the hosting APIs by name. In it you load the component and find its entry point and call it.

**Comment by sanosdole** [comment]
Thanks. That answers my questions.

I'm still undecided whether changing my interface or using a managed component to keep my interface, but this is my problem ;)

I'll close the issue.
