### ISSUE TITLE
System.Threading.Tasks.Tests.CESchedulerPairTests failing with TypeLoadException on CoreCLR

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#32126]
The System.ThreadTasks.Tests.CESchedulerPairTests tests are failing with a TypeLoadException as follows:

```
System.TypeLoadException : Could not load type 'System.Threading.Tasks.SingleProducerSingleConsumerQueue`1+Segment[System.__Canon]' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
```

Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=516148&view=ms.vss-test-web.build-test-results-tab&runId=16342246&resultId=159245&paneView=debug

cc: @dotnet/runtime-infrastructure

**Comment by safern** [comment]
See discussion here: https://github.com/dotnet/runtime/pull/32083#issuecomment-584707840 

Trying to figure out which change caused this.

**Comment by safern** [comment]
@janvorli @jkotas it seems like this is the change that caused this test regression: https://github.com/dotnet/runtime/pull/31956

The reason why it didn't fail on the PR is because it is a flaky failure. Locally I was able to repro and it failed 1 out of 3 runs pretty much all the time. The most runs I saw without a failure was 8.  However when I reverted that commit locally, it has done 40 runs with no failures since I reverted it. 

@jkotas do you want me to revert and send a PR in the meantime to get a clean CI?
