### ISSUE TITLE
Hanging test in System.Reflection.Emit.Tests

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32177]
https://dnceng.visualstudio.com/public/_build/results?buildId=517242&view=ms.vss-test-web.build-test-results-tab&runId=16366188&paneView=attachments&resultId=172855

Unsure which test causes the hang.

```
netcoreapp5.0-OSX-Release-x64-Mono_release-OSX.1014.Amd64.Open

===========================================================================================================
/private/tmp/helix/working/B2510962/w/BAE50A30/e /private/tmp/helix/working/B2510962/w/BAE50A30/e
  Discovering: System.Reflection.Emit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Reflection.Emit.Tests (found 399 of 500 test cases)
  Starting:    System.Reflection.Emit.Tests (parallel test collections = on, max threads = 12)
```

cc @akoeplinger Mono related?

**Comment by akoeplinger** [comment]
Hard to say whether it's Mono related without more context.

**Comment by safern** [comment]
> Hard to say whether it's Mono related without more context.

By downloading the test payload, does it repro locally?

**Comment by akoeplinger** [comment]
Yeah I was able to repro locally with the downloaded payload. It looks like it hangs randomly on different tests though so disabling will be a bit tricky.

Repro:
1. Download and unzip https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-34c645ef-68ba-4987-adc2-c4a3edc9f79f3decab90ac24f5da3/System.Reflection.Emit.Tests.zip
2. Download and unzip https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-34c645ef-68ba-4987-adc2-c4a3edc9f79f3decab90ac24f5da3/test-runtime-netcoreapp5.0-OSX-Release-x64.zip
3. `cd System.Reflection.Emit.Tests && chmod +x RunTests.sh`
4. `while [ $? -eq 0 ]; do ./RunTests.sh --runtime-path ../test-runtime-netcoreapp5.0-OSX-Release-x64.zip/ --rsp-file mono.issues.rsp ; done`

Here's a lldb backtrace: https://gist.github.com/akoeplinger/263781cf9b924ef6dcb9b6f9778e9780

@lambdageek does anthing in that trace look suspicious?

**Comment by safern** [comment]
Can we disable the whole assembly on Mono for the time being? While investigation goes on?

**Comment by akoeplinger** [comment]
Sure, I can send a PR tomorrow or feel free to do it :)

**Comment by safern** [comment]
I put up: https://github.com/dotnet/runtime/pull/32201

**Comment by lambdageek** [comment]
@CoffeeFlux Look at @akoeplinger's gist https://gist.github.com/akoeplinger/263781cf9b924ef6dcb9b6f9778e9780

I think there's a deadlock between thread 12 and thread 16  and the gc initiator (thread 9) because `mono_domain_assemblies_lock` uses an OS mutex, not a coop mutex.  It's near here:

https://github.com/dotnet/runtime/blob/0e0e852e83d5f30dfeeef7ac4999873ee10f9a4b/src/mono/mono/metadata/sre.c#L1378-L1392

Thread 16 is on line 1382 it is holding the domain lock (an os mutex) and it cooperatively suspended trying to take the ALC lock (a coop mutex).
Thread 12 is on line 1378 it wants to take the domain lock (an os mutex) and we're in GC Unsafe mode here so we're trying to cooperatively suspend it.  But it's stuck because 16 is already suspended and won't let go of the mutex.

The domain lock should be a coop mutex.

Also, semi-related  in dynamic-image.c https://github.com/dotnet/runtime/blob/0e0e852e83d5f30dfeeef7ac4999873ee10f9a4b/src/mono/mono/metadata/dynamic-image.c#L34-L46

The dynamic images lock should also be a coop mutex.

**Comment by CoffeeFlux** [comment]
We maaaaay have to delay its initialization if so... I need to look through the startup code and see how to handle that. At least if it's initialized too early it should very obviously fail, so it could be worse. Surprised I didn't notice this earlier.

**Comment by karelz** [comment]
@lambdageek please only 1 area label per issue - see [why](https://github.com/dotnet/runtime/blob/master/docs/project/issue-guide.md#motivation-for-triage-rules). Thanks!
