### ISSUE TITLE
Question: Should System.Buffers.BuffersExtensions.Write<T> pass sizeHint?

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#32244]
Currently `System.Buffers.BuffersExtensions.Write<T>` is doing this:

```csharp
public static void Write<T>(this IBufferWriter<T> writer, ReadOnlySpan<T> value)
{
       Span<T> destination = writer.GetSpan();
```

Should it be doing this?

```csharp
public static void Write<T>(this IBufferWriter<T> writer, ReadOnlySpan<T> value)
{
       Span<T> destination = writer.GetSpan(value.Length);
```

I was performance testing some code and noticed it was doing a lot of extra allocations because hintSize was 0. But it could be just a bad implementation of IBufferWriter.

**Comment by ahsonkhan** [comment]
> But it could be just a bad implementation of IBufferWriter.

Can you share your implementation of `IBufferWriter` and sample code where you see lots of allocations?

Not passing a sizeHint (i.e. passing `sizeHint = 0`, which is the default) lets the implementation provide whatever available buffer it has as quickly as possible (or do what it thinks is optimal for the scenario). If you pass in `value.Length`, it is possible that the `IBufferWriter` would end up allocating really large buffer segments (say over 85k) which would end up on the Large Object Heap (L.O.H.). Passing 0 let's the `IBufferWriter` to potentially pass in pooled 4k chunks instead which might be a better allocation strategy.

So, as a general purpose extension method, `Write` shouldn't pass in `sizeHint` to the `IBufferWriter`. You could write your own that has different semantics fairly easily that might work better for you.

**Comment by CodeBlanch** [comment]
@ahsonkhan Thanks for that great explanation. It still feels kind of weird that there is a `sizeHint` parameter, and `Write` knows the size it needs, but it doesn't pass that hint along. Maybe the param shouldn't exist at all? ::shrug::

I'm using basically the [System.Text.Json.PooledByteBufferWriter](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/PooledByteBufferWriter.cs).

Using that implementation, if you do something like this...
```csharp
            PooledByteBufferWriter writer = new PooledByteBufferWriter(256);

            byte[] SomeBuffer = new byte[200];

            writer.Write(SomeBuffer); // 56 bytes left in the buffer after this call.

            SomeBuffer = new byte[10];

            writer.Write(SomeBuffer); // New buffer[512] allocated.
```
The second `Write` call will cause a new buffer to be allocated (of 512 bytes) even though the internal buffer actually has enough space available to satisfy the request.

If you do this...
```csharp
            PooledByteBufferWriter writer = new PooledByteBufferWriter(256);

            byte[] SomeBuffer = new byte[200];

            Span<byte> Span = writer.GetSpan(SomeBuffer.Length);
            SomeBuffer.CopyTo(Span);
            writer.Advance(SomeBuffer.Length);

            SomeBuffer = new byte[10];

            Span = writer.GetSpan(SomeBuffer.Length);
            SomeBuffer.CopyTo(Span);
            writer.Advance(SomeBuffer.Length);
```
...it works fine.

Now I'm only providing this because you asked, given your explanation I'm pretty sure you're going to say that type is purpose-built and not meant for general use... which is fine :)

PS: I did go and check System.Text.Json and it seems to be passing the hint to `PooledByteBufferWriter`.

**Comment by ahsonkhan** [comment]
That's a fair point. Thanks for showcasing the unexpected behavior you are seeing with a clear example.
The difference here is that you are looking at the behavior of a specific implementation of an interface (in this case `PooledByteBufferWriter`), and suggesting the interface (and its extension method) cater to the specific impl. The whole point of having an interface is for that to do the "general-purpose" thing and specify the contract, while letting the concrete implementations have customized and the context specific behavior.

In your example, the reason why `PooledByteBufferWriter` allocates a new buffer, is because it has a minimum buffer size of 256, which means that when `GetSpan()` is called without a size hint, it thinks you need 256 bytes. Like you observed, if you need less, you'd want to specify what you need. The buffer doesn't always grow though* (implementation detail). Alternatively, change the implementation of `PooledByteBufferWriter` to have a `MinimumBufferSize` of 1 byte, if that works better for you. Then `IBufferWriter.Write` won't grow the buffer when it calls `GetSpan(0)` unless absolutely necessary.

https://github.com/dotnet/runtime/blob/70c1e9dbebe2d737e93b7900c34c6f1dff6a2d77/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/PooledByteBufferWriter.cs#L130-L133

*
```csharp
            PooledByteBufferWriter writer = new PooledByteBufferWriter(512);

            byte[] SomeBuffer = new byte[200];

            writer.Write(SomeBuffer); // 312 bytes left in the buffer after this call.

            SomeBuffer = new byte[10];

            writer.Write(SomeBuffer); // won't allocate since 312 > 256 (the min set in the impl)
```

> Now I'm only providing this because you asked, given your explanation I'm pretty sure you're going to say that type is purpose-built and not meant for general use... which is fine :)

Thanks. Appreciate it :)
