### ISSUE TITLE
CoreCLR tests issues.targets not excluding tests for mono

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#32332]
### Repro Steps

Check out this branch with a modified issues.targets (or just edit issues.targets) to skip the RVAInit tests:

https://github.com/naricc/runtime/blob/naricc/core-riuntime-tests/src/coreclr/tests/issues.targets

Build mono,. and the coreclr tests:

```./build.sh /p:RuntimeFlavor=mono -c Release && cd src/coreclr && ./build.sh -Release && ./build-test.sh -Release```

Then run the tests:

```
cd src/mono/netcore
make run-tests-coreclr-all
```

Expected Result:

Test results for the RVAInit test should **not** appear in <gitroot>/artifacts/log/TestRun.xml

Observed Result:

Test results for RVAInit appear in <gitroot>/artifacts/log/TestRun.xml

@trylek

**Comment by trylek** [comment]
@naricc - I have managed to repro your instructions and according to my initial findings the proximate cause of the issue you're observing is trivial: apparently for IL tests like those under JIT/Directed/RVAInit the build to MSIL creates an extra folder level in the artifacts subtree named after the test project. As the wildcard specifications in issues.targets are used to search the MSIL-built test execution scripts under artifacts, not their source code under src/coreclr/tests, you need to use the double asterisk ('**') in your new issues.targets clause so that MSBuild picks up the entire recursive subtree, not just the current folder. I have verified locally using my Ubuntu VM that, when I specify the double asterisk at the end of the RVAInit clause, I can no longer find it in TestRun.xml. Please let me know if that helped or if I'm missing something.

**Comment by naricc** [comment]
@trylek  That seems to have done it! Thanks.
