### ISSUE TITLE
Use RID-layout for OS configurations in libraries

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32451]
We should switch to the well defined RID system away from our current defined OS configurations. This allows us to share the OS configuration matrix with installer and have just one central point where this is defined.

See https://github.com/dotnet/runtime/blob/97044930e2248d0d529d974e867e551fcffc7abf/src/installer/Directory.Build.props#L227-L308 for how this is currently implemented in installers.

cc @Anipik @ericstj

**Comment by ericstj** [comment]
Yep, @Anipik and I talked about this and agreed this would be good, to avoid the custom runtime.json.  We didn't do it in initial pass because it would churn all the projects.  Now is a good time to do it.

**Comment by Anipik** [comment]
Things that need to get done here. Taken from @jkotas  comment  https://github.com/dotnet/runtime/pull/33315#issuecomment-601508163

- Changes that affect developer workflow should be synchronized using https://github.com/dotnet/runtime/issues/33821
- For anything that gets renamed to use RIDs, make it follow RIDs 100%: i.e.: Debug\win-x64 instead of win.x64.Debug, linux-arm instead linux_arm, etc.
- Renaming of the build output directories to use RIDs sounds reasonable. I agree with Eric that the .NET SDK uses RID based directory names, and so it sounds reasonable for consistency.
- Can this be broken into multiple changes? E.g. Would it make sense to rename the output directories as the step 1, without changing the other stuff? Or can the renames in the CI config be separate change?
- The non-RID names are used in number of places, and we won't be able to change all of them and achive 100% consistency. I do not think it makes sense to try to change as much as possible to use RID OS names. I think we should rather strike the right ballance, e.g. switch to use RIDs where there is a clear prior art (e.g. where the .NET SDK is using them) and leave the rest alone. For example, I do not think it makes sense to be changing the CMakeFiles to use RID OS names.

**Comment by ViktorHofer** [comment]
@Anipik sounds like we can make incremental progress. Do you want to work on this and if yes, can you break down the necessary changes into individual tasks with a rough estimation? Would like to better understand the size of this task.

**Comment by Anipik** [comment]
The  Benefits vs cost scenario is not that great for this issue, so we put it on hold. But u can summarize the steps in detail
