### ISSUE TITLE
Add periodic CI job to test off-by-default code

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#32576]
There are several codes in the JIT that are currently off by default, but we would like to ensure they don't regress (too badly) before they are able to be enabled by default. Consider adding a regularly run (weekly?) AzDO pipeline that runs these.

E.g., EH WriteThru (#543 ), OSR (on stack replacement), guarded de-virtualization, the interpreter.

category:eng-sys
theme:testing
skill-level:beginner
cost:small

**Comment by BruceForstall** [comment]
cc @AndyAyersMS

**Comment by Gnbrkm41** [comment]
Having configurations for different ISAs available (e.g. AVX2 / SSE41 / SSE2 / None) would be also great for testing `System.Numerics` namespace and various components that use HWIntrinsics in their implementations. They can be configured with `COMPlus_Enable{ISA}` environment variable:
https://github.com/dotnet/runtime/blob/2f38f64ceb2ece3e57742e798409642565ddfcb0/src/coreclr/src/jit/jitconfigvalues.h#L223-L275

Often those APIs take different paths depending on the ISA levels available that are otherwise unreachable and will get eliminated by the JIT. Ensuring those fallback paths don't fail with AVE / incorrect behaviours would be nice. I believe currently we don't do that.

**Comment by BruceForstall** [comment]
@Gnbrkm41 The "runtime-coreclr jitstress-isa-x86" pipeline (https://dev.azure.com/dnceng/public/_build?definitionId=664) should cover this.

**Comment by BruceForstall** [comment]
Fixed by https://github.com/dotnet/runtime/pull/33709

(Note, we could still add more to the pipeline as appropriate, e.g., interpreter, if it is brought back to life).
