### ISSUE TITLE
X509Store.Add() on Linux is racing with X509Chain.Build

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#32608]
On Linux, adding a certificate to store , then build chain on this certificate. 
The results of chain building is :
 `UntrustedRoot:  self signed certificate`
So the adding to store doesn't work immediately.

On Windows, everything is fine.

Repro steps:
1.Download the attached repro console  to a Linux machine.
2. Install SDK 5.0 on a Linux machine.
3.Go to` ./BuildChain-linuxAddToStore/BuildChain`, run `dotnet build`
4.Run  `dotnet ./bin/Debug/netcoreapp5.0/BuildChain.dll`

The console app runs 2 tests:
1. add a certificate to X509Store and run X509Chain.Build immediately. (10 times)
2. add a certificate to X509Store and wait for a while, then run X509Chain.Build. (10 times)

The results shows that 1st test has a low passing rate, while the 2nd has a higher passing rate.

You may also run it on Windows, all the 2 tests have 100% passing rate on Windows.

[BuildChain-linuxAddToStore.zip](https://github.com/dotnet/runtime/files/4232340/BuildChain-linuxAddToStore.zip)

**Comment by bartonjs** [comment]
Yep.  Windows has a live-synchronized model, and on Linux we have a filesystem/rescan delay problem.

For performance reasons, we only check to see if the store has been modified once a second.

**Comment by heng-liu** [comment]
Thanks @bartonjs  !
So the chain build will only succeed when the once a second checking is one and discover the store has been modified, right?
May I know if there is any way for us to check the real-time status, to see if the certificate is added to store or not?
I tried to go through X509Store.Certificates to check, but it's always there even if it's not yet finished adding.
I also tried to create a new X509Store and check the Certificates in the new X509Store , but it's not there even if it's already added.
For now, we just  wait for a while after adding to store for all test cases, it's time consuming. If we can get the real-time status, we can avoid waiting for some cases. Do you have any suggestions for our workaround? Thanks!

**Comment by bartonjs** [comment]
The chain trust processor is what has the static cached view, new X509Store instances always see live.  There's no way to see its internals.

Rather than doing modification of the store, consider the contextual trust feature (X509ChainPolicy.CustomTrustStore / X509ChainPolicy.TrustMode; new in 5.0).

If you need to modify the store and have it show up "immediately" you can run your test from a new process.  Or wait more than a second between adding/removing a cert and expecting the result.

The 1 second interval is how often it'll check for a new last modified time on the store.  LMT values are only to the second, so if you end up causing the chain processor view of the store to load and modify the store again during the same second, you'll have to wait for the longer interval (30 seconds) before you actually see the benefit (that's the "just in case LMT is disabled for this filesystem, or we had a level-of-refinement problem, or clock adjustments" failsafe).

My recommendation is to just set things up at the beginning of your test suite, then do all of your tests with no during-test modification, then (presumably) restore the system state.  If you need to do "trust this now, then stop trusting it, then trust it again" you need to do multiple processes, lots of sleeping, or use the .NET 5 custom trust store feature.

**Comment by heng-liu** [comment]
Thanks! That's very helpful. @bartonjs
