### ISSUE TITLE
Delete `GTF_INX_REFARR_LAYOUT`

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#32647]
This flag should be no longer needed. Deleting it is causing unexpected assembly diffs that need to be investigated. More context: https://github.com/dotnet/runtime/pull/32521#issuecomment-589567814

**Comment by jkotas** [comment]
cc @ivdiazsa

**Comment by AndyAyersMS** [comment]
Looks like one source of collision is `GTF_ARRLEN_NONFAULTING`.

**Comment by AndyAyersMS** [comment]
When morphing `GT_INDEX` nodes, we were inadvertenly setting `GTF_IND_NONFAULTING`
for the `GT_IND` subtree for ref type arrays, because `GTF_IND_NONFAULTING` has
the same value as `GTF_INX_REFARR_LAYOUT`.

This turns out to be safe since in general there is an upstream bounds check to
cover the null check from the indexing operation, so the fact that we were claiming
the `GT_IND` can't fault is ok.

A no diff change would remove the flag and then modify `fgMorphArrayIndex`
to set `GTF_IND_NONFAULTING` for ref type arrays with bounds checks:
```
    // If there's a bounds check, the the indir won't fault.
    if (bndsChk && (tree->gtType == TYP_REF))
    {
        tree->gtFlags |= GTF_IND_NONFAULTING;
    }

    tree->gtFlags |= GTF_EXCEPT;
```
Removing `GTF_INX_REFARR_LAYOUT` and adding change above gives a no-diff change.

But there's no good reason to limit the above to ref type arrays
and no good reason to OR in `GTF_EXCEPT` when there are bounds checks.

Once we do the more general fix we see diffs, so might as well further
clean up by removing the odd related constraint in the importer under
`REDO_RETURN_NODE`.
