### ISSUE TITLE
PublishSingleFile affects exceptions stacktrace

### ISSUE THREAD

**Issue by nvborisenko** [dotnet/runtime#32658]
- `dotnet new console`
- Modify Main() method which throws any exception (`throw new Exception("Hmm")`)
- Build and run application `dotnet run`

Expected output:
```
Unhandled exception. System.Exception: Hmm
   at Q.Program.Main(String[] args) in C:\Temp\Q\Program.cs:line 9
```

Now let's publish it as single file.
- `dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true`
- Go to published folder and run application

Actual output:
```
Unhandled exception. System.Exception: Hmm
   at Q.Program.Main(String[] args)
```

We see that ` in C:\Temp\Q\Program.cs:line 9` is missing.

Also tried `/p:IncludeSymbolsInSingleFile=true`, didn't help.

## dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64

**Comment by jkotas** [comment]
cc @swaroop-sridhar

**Comment by nvborisenko** [comment]
More additional info: actually `/p:IncludeSymbolsInSingleFile=true` compiler option works, and stacktrace is correct. But I should delete `Q.pdb` file, which is located in publish output folder from previous publishing. It seems presence of pdb file near with executable single file affects stacktrace.

Since I understood what is wrong (this case can be resolved just as warning during publishing), I continued further steps, and applied `/p:PublishTrimmed=true` option. With this option stacktrace is always incorrect.

**Comment by vitek-karas** [comment]
The `Q.pdb` being left behind in publish folder is a known issue. SDK will not delete the publish folder during `dotnet publish`, so it will effectively "add/overwrite" the newly built files into it. You can try to delete the folder before running `dotnet publish`, the file should not be there anymore. (If I remember correctly this behavior should be changed in 5 - basically fixed).

The issue with /p:PublishTrimmed=true is effectively the same as https://github.com/dotnet/sdk/issues/4017.  It contains a workaround for it, basically include:
``` XML
  <ItemGroup>
    <TrimmerRootAssembly Include="System.Diagnostics.StackTrace" />
  </ItemGroup>
```
and
``` XML
<PropertyGroup>
  <_ExtraTrimmerArgs>--keep-facades true</_ExtraTrimmerArgs>
</PropertyGroup>
```
In your project file. It will add quite a few more files to the output, but in general they should be relatively small.

The fix for that issue has been merged here: https://github.com/dotnet/runtime/pull/32023.

**Comment by swaroop-sridhar** [comment]
Closing this issue as a dup of:
Cleaning publish directory: https://github.com/dotnet/sdk/issues/377
Preserving StackFrameHelper:  dotnet/sdk#4017
