### ISSUE TITLE
API Proposal: static RandomNumberGenerator.GetDouble() method

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#32855]
With the addition of the new static methods on the `RandomNumberGenerator` class in .NET Core 3.0 (see #26716), it's been possible to get a random 32-bit integer value without having to worry about creating an instance of `RandomNumberGenerator` (or `Random`) to do so. This has the benefit of saving some allocations/complexity, as well as being secure by default compared to `Random`.

To allow for consistent simple usage of `RandomNumberGenerator` for common use cases without having to create an instance and also benefit from the security of RNG over `Random`, it would be useful if there was also an equivalent static method for getting a random `double` value equivalent to the functionality of [`Random.NextDouble()`](https://github.com/dotnet/runtime/blob/955578f1fdd49be1f4a895d7ad4bb8d4eee38707/src/libraries/System.Private.CoreLib/src/System/Random.cs#L223-L231).

This is very much just a nice-to-have suggestion to improve the developer experience for simple use cases.

## Proposed API

```csharp
namespace System.Security.Cryptography
{
    public abstract class RandomNumberGenerator
    {
        public static double GetDouble();
    }
}
```

## Proposed Usage

```csharp
double numberBetween0And100 = RandomNumberGenerator.GetDouble() * 100.0;
```

## Current Usage

```csharp
// Non-secure
var random = new Random();
double numberBetween0And100 = random.NextDouble() * 100.0;

// Secure (adapted from Stack Overflow https://stackoverflow.com/a/2854635/1064169)
var bytes = new byte[8];
RandomNumberGenerator.Fill(bytes);

ulong ul = BitConverter.ToUInt64(bytes, 0) / (1 << 11);
double d = ul / (double)(1UL << 53);
double numberBetween0And100 = d * 100.0;
```

**Comment by GrabYourPitchforks** [comment]
This is actually a more difficult problem than it seems. One thing to keep in mind is that floating point numbers are not evenly distributed across their entire domain. So there's a difference between "give me a random float between 0 and 1" and "choose a real number with even distribution between 0 and 1". Since this is presumably a cryptographic API, we'd need to understand the scenarios deeply so that we can provide the right behavior.

See also: https://crypto.stackexchange.com/q/31657

**Comment by martincostello** [comment]
If this comes into the realm of _”hard problems”_ and the APIs current non-existence is because of that then I guess it wouldn’t be worth the engineering effort.

The reason I thought I’d suggest the API is I stumbled across a usage of Random on some code I’ve not looked at for a while and wondered if I could update it over to use RNG and delete a suppression for “weak random number” while I was at it.

The code in question is used for jitter on a retry so doesn’t _need_ cryptography, but I wondered if I could leverage something to tidy it up a bit with the more recent APIs,  which I’ve been rolling over to for integers to make a bit more simple.

As there’s no way to do floating point simply in the same, I thought I’d suggest the API. Of it ends up as something unimplemented it won’t be the end of the world, but don’t-ask-don’t-get 🙂

**Comment by GrabYourPitchforks** [comment]
There's nothing wrong with hard problems. :) I had to spend a few minutes convincing myself that creating a denormal number and then multiplying would give an unbiased distribution. If we do this, then the produced double will have 52 bits of entropy and will be uniformly chosen from the range `[ 0, 1 )` with a step size of `2 ^ (-52)`.

I am curious as to what happens *after* we return a double back to the application, though. Say that the framework goes to great lengths to ensure even distribution. If the calling application then performs almost any arithmetic operation on that number, there's a decent chance that a bias will be introduced into the result since the range of results will no longer be evenly stepped.

That's why the discussion on scenarios is important. What does the app intend on using such an API for? Do we need to massage the return value further than simply choosing a value from a uniformly distributed sample?

These concerns aren't generally applicable to choosing an integer from a uniformly distributed sample, so adding the int-returning method was much more straightforward.

**Comment by bartonjs** [comment]
The need for cryptographically sound random numbers for integers has a scenario: picking an array/list/etc index at random, fairly.

I'm having trouble understanding what a CSPRNG-filled double would be used for.

**Comment by GrabYourPitchforks** [comment]
Without a good scenario we can't really make progress on this, so I'm closing it for now. But please reopen if you find a scenario and can provide more details. Thanks!
