### ISSUE TITLE
Delegate contains code which ILLink can't analyze

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#32864]
`Delegate.GetMethodImpl` calls [`this.GetType().GetMethod("Invoke")`](https://github.com/dotnet/runtime/blob/ba76c377203bc852c6e2c28f4f4a24c7ae71ea1e/src/coreclr/src/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs#L207-L209). This should get the `Invoke` method on the derived delegate type. Linker may decide to remove methods which are not directly referenced by the application code, but delegates are special. Linker will preserve all methods on any class derived from `MulticastDelegate`.

Is there any other type which derives from `Delegate` and implements `Invoke` for which we would need to keep the behavior? Or do we need to change linker to preserve all methods on all types derived even indirectly from `Delegate` itself?

**Comment by stephentoub** [comment]
> Is there any other type which derives from Delegate and implements Invoke for which we would need to keep the behavior? Or do we need to change linker to preserve all methods on all types derived even indirectly from Delegate itself?

I'm not aware of anything other than Multicast delegate that derives from delegate.

That said, it seems like changing the linker to special-case Delegate rather than MulticastDelegate should cheap, both in terms of dev work and in terms of app impact. If there aren't any other derived types, it'll have no negative impact. And if it turns out there is one, it'll prevent breaks. No?

**Comment by eerhardt** [comment]
@vitek-karas @MichalStrehovsky - has this work been completed? I'm going to close this issue, since there is no work in `dotnet/runtime` for this. If there is remaining work needed in the linker, please open an issue in `mono/linker`.
