### ISSUE TITLE
NullReference when JsonExtensionData dictionary have a custom JsonConverter

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#32903]
Repro:
```cs
private class ClassWithExtensionData
{
    [JsonExtensionData]
    public Dictionary<string, object> Overflow { get; set; }
}

public class DictionaryOverflowConverter : JsonConverter<Dictionary<string, object>>
{
    public override Dictionary<string, object> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }

    public override void Write(Utf8JsonWriter writer, Dictionary<string, object> value, JsonSerializerOptions options)
    {
        // Do something.
    }
}

[Fact]
public static void QuickTest()
{
    var root = new ClassWithExtensionData();
    root.Overflow = new Dictionary<string, object>();
    root.Overflow.Add("test", "TestValue");

    var opts = new JsonSerializerOptions();
    opts.Converters.Add(new DictionaryOverflowConverter());

    string json = JsonSerializer.Serialize(root, opts);
}
```

This only happens in master.

@steveharter @layomia

**Comment by layomia** [comment]
Note: custom converters can only be used on serialization. Deserialization is handled by the serializer.

**Comment by ahsonkhan** [comment]
> can only be used on serialization. Deserialization is handled by the serializer.

That's a bit strange. Is there a reason for that and should we (can we?) fix it?

**Comment by Jozkee** [comment]
@ahsonkhan Overflow properties does not come on a particular order when reading the JSON and the `Read` method must return a `Dictionary<string, JsonElement>` or `Dictionary<string, object>` while overflow properties are parsed to `JsonElement` entries in such dictionary. That is why we don't use it on deserialization.

**Comment by layomia** [comment]
> > can only be used on serialization. Deserialization is handled by the serializer.
> 
> That's a bit strange. Is there a reason for that and should we (can we?) fix it?

@ahsonkhan it's because we may not have all the extra JSON in one go - we'd have to parse and wrap all the extension properties in one JSON object, or pass the entire payload to the converter to be filtered.

FWIW Newtonsoft does not honor custom converters for both reading and writing extension data: https://dotnetfiddle.net/qwMrPS. Writing seems doable, so I think the action for this issue is to fix the NRE and make sure custom converters are honored on serialization.

 @steveharter, it seems that the assumption in https://github.com/dotnet/runtime/blob/0bf721ab4dcd3426790c3251788f77262e8abb1c/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L283 is that only internal converters are used for serialization. Any thoughts?

**Comment by Reza1024** [comment]
I think for writing it makes sense to support custom serialization.
