### ISSUE TITLE
Why System.Drawing.Common nuget is asking to install Microsoft.NetCore.Platforms on Asp.NetCore 3.1 Web App as required dependency?

### ISSUE THREAD

**Issue by LazZiya** [dotnet/runtime#32907]
Hi,

I have Asp.Net Core web app that is targeting **.Net Core v3.1.0**. When I try to install `System.Drawing.Common.4.7.0` nuget via "Nuget Package Manager" it asks to install `Microsoft.NETCore.Platforms.3.1.0` as dependency:
````
Installing:

Microsoft.NETCore.Platforms.3.1.0
Microsoft.Win32.SystemEvents.4.7.0
System.Drawing.Common.4.7.0
````

I tried to install lower versions but lower versions also has the same issue, v4.6.0 is asking to install `Microsoft.NETCore.Platforms.3.0.0` and v4.5.1 is asking to install `Microsoft.NetCore.Platforms.2.0.0`, ...etc. 

The issue appears only when the project is targeting .Net Core 3.x because when I install `System.Drawing.Common` on a web project that is targeting .Net Core v2.2 it doesn't ask to install `Microsoft.NETCore.Platforms` as dependency:

````
Installing:

Microsoft.Win32.SystemEvents.4.5.0
System.Drawing.Common.4.5.1
```` 

 So why `System.Drawing.Common` is asking to install `Microsoft.NETCore.Platforms` as dependency when my project is already targeting .Net Core v3.x?

I'm using VS2019 v16.4.5

**Comment by danmosemsft** [comment]
@joperezr

**Comment by joperezr** [comment]
Microsoft.NETCore.Platforms is a package that doesn't really contain any assets that get passed in to the compiler, but it is a package that includes a runtime mapping table that lets us know what are the latest RID mappings for all OSes. This file, looks something like this:
```json
{
  "runtimes": {
    "alpine": {
      "#import": [
        "linux-musl"
      ]
    },
    "alpine-x64": {
      "#import": [
        "alpine",
        "linux-musl-x64"
      ]
    },
    "alpine.3.10": {
      "#import": [
        "alpine.3.9"
      ]
    },
    "alpine.3.10-x64": {
      "#import": [
        "alpine.3.10",
        "alpine.3.9-x64"
      ]
    },
    "alpine.3.11": {
      "#import": [
        "alpine.3.10"
      ]
    },
 ...
```

We include this package reference for any package that has Runtime-specific assets, as we want to make sure that if you are targeting a RID like `alpine.3.11` NuGet knows which asset to grab from the package. System.Drawing.Common has runtime-specific assets that apply for .NETCoreApp 2.0 and 3.0 here:

```
        "runtimes/unix/lib/netcoreapp2.0/System.Drawing.Common.dll",
        "runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll",
        "runtimes/win/lib/netcoreapp2.0/System.Drawing.Common.dll",
        "runtimes/win/lib/netcoreapp3.0/System.Drawing.Common.dll",
```

This means that whenever you target either netcoreapp 2.0 or above, you will get a reference to Microsoft.NETCore.Platforms package as well in order for NuGet to be able to find the right runtime assets to deploy with your app. The reason why you were not seeing it in the console when you targeted .NET Core 2.2, might be that the package was already installed so it didn't require to install it again, but I bet that if you go and inspect your assets file (located at `obj\project.assets.json`) you'll see that Microsoft.NETCore.Platforms was also included on NuGet restore, and was taken into consideration in order to finalize which assets your app will get.

**Comment by joperezr** [comment]
I'll go ahead and close this given that I believe the question posted was answered, but @LazZiya please do feel free to reopen if you think otherwise or if you have any follow-up questions.
