### ISSUE TITLE
COMPlus_PartialNGen is not being set since repo consolidation

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#32935]
we are setting this flag _partialCrossgenFlag for some assemblies here https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/framework.dependency.targets#L427-L431

Before this change these lines of code was never been executed https://github.com/dotnet/arcade/pull/4911 becuase $(OSGroup) can never be linux in installer. we either set it to unix or osx https://github.com/dotnet/runtime/blob/master/src/installer/Directory.Build.props#L63

The failure due to this flag being set can be found in  https://github.com/dotnet/runtime/pull/32858

the failure message is 
```
Error compiling /root/runtime/artifacts/bin/pkg/netcoreapp5.0/runtime/Linux-Debug-x64/System.ComponentModel.TypeConverter.dll: Cannot compile using the PartialNgen flag because no IBC data was found. (0x8013200C)
```

I checked the flag value and its being set to 1

This was introduced in https://github.com/dotnet/core-setup/pull/5252
@MichalStrehovsky  can you take a look and help me fix this ?

cc @ericstj @dagood @ViktorHofer @safern

**Comment by MichalStrehovsky** [comment]
This is either because CoreFX stopped embedding IBC data again like in https://github.com/dotnet/corefx/pull/38343#discussion_r294102593 (when Release builds of CoreFX were actually Debug builds), or because the optimization infra is not generating the IBC data for CoreFX to embed.

Cc @brianrob who own the area.

**Comment by Anipik** [comment]
@brianrob any pointers here to fix this ?

**Comment by Anipik** [comment]
cc @ericstj

**Comment by brianrob** [comment]
It looks like we are publishing IBC data for System.ComponentModel.TypeConverter.dll so this implies that the IBC data isn't being embedded into the IL image before the call to crossgen occurs.  Note that this only happens for official builds so if you try this on your dev box you'll never see the IBC data.

I would recommend looking for the call to ibcmerge.exe in build logs and make sure that this is succeeding for System.ComponentModel.TypeConverter.dll.

**Comment by ericstj** [comment]
I believe @Anipik is seeing the failure on debug build in CI which would explain why the IBC data is missing.  

I checked the binaries from a [recent official build](https://dev.azure.com/dnceng/internal/_build/results?buildId=540482) and confirm that IBC data is present:
![image](https://user-images.githubusercontent.com/8918108/75583740-13288800-5a23-11ea-9158-5d6974abd11b.png)

It did get an OSGroup value of Linux when it was in core-setup, and the binaries it got from the corefx transport package would have always had IBC data (since they were release binaries)
https://github.com/dotnet/core-setup/commit/0d80fe3cfdceeb0873222176573a7add30f5db85

Regardless the fix would be to condition that code.  I think we need to match these conditions:
https://github.com/dotnet/runtime/blob/2458930a6b03edc18618d0a614493cd589d44d23/eng/Tools.props#L46
@brianrob as far as I can tell it might just be a release/debug difference.  I can't find anywhere else we condition this to be disabled on official vs not.  To be sure, try a release build on Linux and make sure it is successful

Separately: @dagood do we really want library specific configurations to exist in Arcade?  Seems to me this should live in the shared framework project.  This is leaking repo-specific state into shared tooling: https://github.com/dotnet/arcade/blob/4d9720ccb07cc01068c2f7c19cb2ded64c44b1a1/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/framework.dependency.targets#L427-L431

**Comment by brianrob** [comment]
Historically, the conditioning has been on whether or not ibcmerge.exe is present, which only happens on release official builds since it is not publicly available.

**Comment by Anipik** [comment]
@ericstj I tried with the release flag still the same error
```
/root/.nuget/packages/microsoft.dotnet.build.tasks.sharedframework.sdk/5.0.0-beta.20127.9/targets/framework.dependency.targets(441,5): error MSB3073: The command "/runtime/artifacts/bin/coreclr/Linux.x64.Release/sharedFramework/crossgen @/runtime/artifacts/obj/netcoreapp/Release/netcoreapp5.0/linux-x64/crossgen/System.ComponentModel.TypeConverter.rsp" exited with code 12. [/runtime/src/installer/pkg/projects/netcoreapp/src/netcoreapp.depproj]
```

**Comment by ericstj** [comment]
I see, we are probably missing another condition then as @brianrob suggests.

**Comment by ericstj** [comment]
Found it: https://github.com/dotnet/arcade/blob/f6121fcaf62777bc2288f7f0917b48a130a0174e/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets#L59

**Comment by ericstj** [comment]
@brianrob I don't like copying a bunch of this conditional logic or running the targets.   Is there a way for these installer targets to "observe" that IBCMerge was run and only then specify the param?  Or for crossgen to ignore the option if the binary doesn't have IBC merge data?

**Comment by brianrob** [comment]
We specifically added this error message because release builds were making it out into the wild without IBC data, and thus partial NGEN resulted in no pre-compilation.  I wouldn't want to go back to a world where that's a possibility.  Without having dug too much into the targets here, I'm not sure there's a great answer here.  The invariant we want to hold true is that we always call crossgen -partialNGEN for assemblies that we should partial NGEN and if that fails due to missing IBC data, then that's a bug we need to fix.

**Comment by ericstj** [comment]
So you want to test that all binaries have IBC data by failing if 3 of them are missing IBC data?  I understand you'd want test coverage, but relying on this as a side-effect of cross-gen commandline seems a little busted.

Regardless, if you want this stuff in the installer targets to match what is done in the optimatizationdata targets you ought to agree upon a contract to communicate that rather than rely on folks getting both conditions to match.  @dagood / @MichalStrehovsky can you help make these consistent?

**Comment by Anipik** [comment]
I took a look at the official build and it doesn't seem like we are hitting this code on the official build as well. Not sure which target is responsible for embedding the ibc data to dlls

**Comment by ericstj** [comment]
This target does: https://github.com/dotnet/arcade/blob/f6121fcaf62777bc2288f7f0917b48a130a0174e/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets#L174-L177

**Comment by brianrob** [comment]
@ericstj the reason that we do this in crossgen is because that's the natural place to detect whether or not specifying -partialNGEN is going to have the desired behavior.  From a crossgen usage perspective, you would never want to specify -partialNGEN if there isn't IBC data embedded in the input IL image, as that would mean "please don't precompile this DLL", even though that's exactly what you're attempting to do.  The key here is that we want a uniform way to make sure that no one ever specifies -partialNGEN on an IL image that has no IBC data.

**Comment by ericstj** [comment]
Changed the title of the issue.  This needs to track re-enabling the COMPlus_PartialNGen option.  That appears to have been broken since repo consolidation.  It needs to be brought back with "awareness" of whether the rest of the build actually embedded IBC data.  It didn't need this before because it was consuming transport packages in core-setup (which were always "official" "release" packages with IBC data).

**Comment by ViktorHofer** [comment]
@MichalStrehovsky @brianrob I assume this is required for 5.0? Is someone actively working on this?

**Comment by MichalStrehovsky** [comment]
Cc @mangod9 for IBC.

**Comment by ViktorHofer** [comment]
cc @mangod9

**Comment by mangod9** [comment]
What is the current impact of this issue? Is it that some assemblies are not getting precompiled? + @davidwrighton in case you have any context?

**Comment by brianrob** [comment]
This does not impact whether or not an assembly is precompiled, but does impact which assemblies are precompiled with partial NGEN.  Partial NGEN uses IBC data to decide which methods to precompile, in order to reduce assembly size.  This is especially important for assemblies that are loaded into the Visual Studio devenv process, which is 32-bit and needs to save VM address space.

In general, partial NGEN is less important for the dotnet SDK, but does have an impact on overall size on disk.

**Comment by mangod9** [comment]
Ok, thanks for the context. Guess we can check the size of disk when compared to 3.1 and determine whether it meets the bar for 5.0. 

cc @trylek

**Comment by brianrob** [comment]
Yes, that seems like a reasonable way to go.  I know there was some work done in the 3.1 timeframe around Docker images specifically on Linux, so do make sure that you look at Linux size as well as Windows.

**Comment by davidwrighton** [comment]
In particular, I believe the size work here was targeted at improving Linux container size, so that's the detail that needs to be looked at. @MichaelSimons do we have container size measurements?

**Comment by MichaelSimons** [comment]
@davidwrighton - Here is a generated graph which illustrates the image hierarchy and size comparisons between the 3.1 and 5.0 alpine images.  All sizes are the compressed images (size of the pulled image - wire cost).  If you want to see this for the other distros or for Windows, I can easily generate it.

Runtime and ASP.NET changes are minimal.  SDK growth is noticeable.

![image](https://user-images.githubusercontent.com/8290530/91453647-a3664f00-e845-11ea-80ac-b28e1f5826bd.png)

FWIW, I did take a brief look at this a month ago and noted the following.  I see the SDK has grown a fair bit more since this.

Alpine 3.12 SDK Image Details
--
Details | 3.1 | 5.0 | Delta | %
|--- |--- |--- |--- |---
Compressed Image Size | 146.7 | 168 | 21.3 | 14.5%
Extracted Image Size | 422 | 475 | 53 | 12.6%
Compressed Owned Layer Size | 104.4 | 124.9 | 20.5 | 19.6%
  |   |   |  |  
/usr/share/dotnet/sdk | 181.3 | 209 | 27.7 | 15.3%
/usr/share/dotnet/shared | 90.9 | 95.5 | 4.6 | 5.1%
/usr/share/dotnet/packs | 54.2 | 57.2 | 3 | 5.5%
  |   |   | 35.3 |  
/usr/share/dotnet/sdk/xxx/Roslyn | 37.8 | 43.8 | 6 | 15.9%
/usr/share/dotnet/sdk/xxx/Sdks | 44.8 | 64.5 | 19.7 | 44.0%
  |   |   | 25.7 |  
/usr/share/dotnet/sdk/xxx/Sdks/Microsoft.NET.Sdk.Razor | 14.9 | 27.3 | 12.4 | 83.2%
/usr/share/dotnet/sdk/xxx/Sdks/Microsoft.NET.Sdk | 5.9 | 11.2 | 5.3 | 89.8%
  |   |   | 17.7 |  
/usr/share/dotnet/sdk/xxx/Sdks/Microsoft.NET.Sdk.Razor/Microsoft.CodeAnalysis.CSharp.dll | 5 | 15 | 10 | 200.0%

**Comment by davidwrighton** [comment]
Partial ngen isn't really applied to anything in the sdk, so the sdk size growth is something else. To be honest it looks like in the case of the sdk.razor size increase its due to actually crossgenning the sdk in some form, but again, that's not affected by the policy change around partial ngen which probably only affects the runtime and possibly the aspnet containers.

Looking at the results from doing partial ngen in the past, we should gain about 5-8MB of extracted size which is probably something like 1-2MB of compressed size. This would result in our 5.0 docker images being *smaller* than the 3.1 ones.

**Comment by MichaelSimons** [comment]
@davidwrighton, consider checking with the performance team on this as well.  I was told they were investigating or have some checks in place that monitor the _product_ size.  IDK any details.

**Comment by davidwrighton** [comment]
@billwert @MichaelSimons has a point, does the perf team have a statement here?

**Comment by ViktorHofer** [comment]
Note to myself, talk with @brianrob about priority. We need to understand if this is needed for 5.0 which closes very soon.

**Comment by mangod9** [comment]
Based on the discussion above, my recommendation is to move to 6.0

**Comment by richlander** [comment]
This is "nice to have". We have lots to do in this space for 6.0. I agree with @mangod9 that we should move this to 6.0 at this point.

**Comment by hoyosjs** [comment]
@ViktorHofer @brianrob looks like this one flew under the radar once more. Is this something that should still be considered for 6.0?

**Comment by richlander** [comment]
Thanks for raising this!

We've been talking about this as part of the crossgen crew. I've been doing some perf testing for crossgen with this as one of the variables to consider. I'll have more to share soon.

**Comment by ViktorHofer** [comment]
Let's keep this onto 6.0 until we hear back from Richard.

**Comment by richlander** [comment]
I did some more analysis of the data I was collecting. This will be important for .NET 7 but I think we can consider the ship sailed on this for .NET 6.

**Comment by hoyosjs** [comment]
@mangod9 @brianrob @dotnet/crossgen-contrib is partial ngen still a concern? Deciding if this is an 8.0 issue, or if it should be closed.

**Comment by mangod9** [comment]
partialNGen is not a thing currently. I think this issue was capturing the fact that pgo was not being used in the runtime repro, which has now been fixed. Not sure if this needs to be tracked anymore?

**Comment by hoyosjs** [comment]
PGO doesn't consume IBC data in managed images (unless you mean dotnet-pgo. But that's newer than this issue).

**Comment by brianrob** [comment]
At a minimum, this issue can be moved to .NET 8.  It is also possible that it can be closed - we should understand the scenario requirements around whether we want to support anything like partial NGEN on R2R.  Historically, it was used to address VM constraints and to a lesser degree, size constraints.  It's not clear that we have a strong scenario where this is required.

**Comment by mangod9** [comment]
we will be looking into supporting partial R2R scenario for the composite scenario, but will track it as a separate user story.

**Comment by agocke** [comment]
Closing as no longer relevant.
