### ISSUE TITLE
Xml Serialization problem

### ISSUE THREAD

**Issue by izzetuslu** [dotnet/runtime#32977]
Xml Serialization problem

Service response and reference file attached.

< fareComponentGroupList > field in < originDestinationOptionList > has 2 items but serilaized to availabilityFareComponentGroupType[] originDestinationOptionList array one item only.

[serviceresponse.zip](https://github.com/dotnet/core/files/4255698/serviceresponse.zip)

**Comment by scalablecory** [comment]
Not sure if runtime or WCF. CC @mconnew @StephenBonikowsky 

@izzetuslu can you please reduce your repro to a small piece of runnable C#?

**Comment by izzetuslu** [comment]
string contents = File.ReadAllText(@"D:\serviceresponse\serviceresponse.xml");
var xmlSerializer = new XmlSerializer(typeof(GetAvailabilityResponse));
GetAvailabilityResponse resp;
using (var stringreader = new StringReader(contents))
{
resp = (GetAvailabilityResponse)xmlSerializer.Deserialize(stringreader);
}

**Comment by StephenMolloy** [comment]
Sorry for the late response on this. I took a look at your repro and I don't see any issue with the XmlSerializer itself. It is doing what it is supposed to do. But reading your description and looking at your data and code, I can see where it looks like some 'originDestinationOptionList' are getting lost in deserialization. But the reason for this is because your code does not match the data being deserialized. Let me demonstrate.

You have data that looks like this:
```xml
<availabilityByDateList>
	<dateList>2020-02-15T00:00:00+03:00</dateList>
	<originDestinationOptionList>
		<fareComponentGroupList> ... </fareComponentGroupList>
        </originDestinationOptionList>
	<originDestinationOptionList>
		<fareComponentGroupList> ... </fareComponentGroupList>
        </originDestinationOptionList>
</availabilityByDateList>
```

And the corresponding classes look like this:
```CS
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [XmlTypeAttribute(Namespace = "http://impl.soap.ws.crane.hititcs.com/")]
    public partial class availabilityByDateType
    {
        [XmlElementAttribute("dateList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public System.Nullable<System.DateTime>[] dateList { get; set; }

        [XmlArrayAttribute(Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        [XmlArrayItemAttribute("fareComponentGroupList", typeof(availabilityFareComponentGroupType), Form = XmlSchemaForm.Unqualified)]
        public availabilityFareComponentGroupType[] originDestinationOptionList { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://impl.soap.ws.crane.hititcs.com/")]
    public partial class availabilityFareComponentGroupType
    {
        [XmlElementAttribute("boundList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public boundType[] boundList { get; set; }

        [XmlElementAttribute("fareComponentList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public availabilityFareComponentType[] fareComponentList { get; set; }
    }
```

The `availabilityByDateType` class contains two array properties. The first, `dateList`, is tagged with an XmlElementAttribute, which tells the serializer that 1) this array will be in-place without a wrapping element, and 2) items this array will use the name 'dateList'. Your data only has one 'dateList' element, but if there were more, they would be deserialized into the array without issue.

The second property, `originDestinationOptionList`, is tagged differently. It has an XmlArrayAttribute and an XmlArrayItemAttribute. The first attribute doesn't really do much relevant to this discussion. The serializer already knows the property is an array, and it is expecting a wrapping element around the array that matches the property name 'originDestinationOptionList.' The second attribute tells the serializer that items in the array will be in xml elements named 'fareComponentGroupList.' So, restating what the serializer is expecting based on the definition of this second array property - the serializer is looking for a single array, wrapped in an 'originDestinationOptionList' element, with child items represented by 'fareComponentGroupList' elements.

But if you look at the xml data, instead of a single 'originDestinationOptionList' element wrapping your array, you have each item in the array wrapped in such an element. The serializer sees the first one, deserializes it, and then ignores the rest since it thinks it already finished deserializing the array because it is expecting only one wrapping element.

*************

To fix your deserialization issue, you can change the data, or you can change your code. If you elect to fix your data, the solution is to simply include all the array items in a single 'originDestinationOptionList' element, like this:
```xml
<availabilityByDateList>
	<dateList>2020-02-15T00:00:00+03:00</dateList>
	<originDestinationOptionList>
		<fareComponentGroupList> ... </fareComponentGroupList>
		<fareComponentGroupList> ... </fareComponentGroupList>
        </originDestinationOptionList>
</availabilityByDateList>
```

If you instead want to make the change in your code, you would first need to tag the 'originDestinationOptionList' property similarly to the 'dateList' property so the serializer will expect to find the array items in-place instead of in a wrapper. Then you will also need to include a container class for the array items so you can apply proper naming to the elements contained within each 'originDestinationOptionList' element. Like this:
```CS
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [XmlTypeAttribute(Namespace = "http://impl.soap.ws.crane.hititcs.com/")]
    public partial class availabilityByDateType
    {
        [XmlElementAttribute("dateList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public System.Nullable<System.DateTime>[] dateList { get; set; }

        [XmlElementAttribute("originDestinationOptionList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public availabilityFareComponentGroupContainer[] originDestinationOptionList { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://impl.soap.ws.crane.hititcs.com/")]
    public partial class availabilityFareComponentGroupContainer
    {
        [XmlElementAttribute("fareComponentGroupList", Form = XmlSchemaForm.Unqualified)]
        public availabilityFareComponentGroupType Item { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://impl.soap.ws.crane.hititcs.com/")]
    public partial class availabilityFareComponentGroupType
    {
        [XmlElementAttribute("boundList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public boundType[] boundList { get; set; }

        [XmlElementAttribute("fareComponentList", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public availabilityFareComponentType[] fareComponentList { get; set; }
    }
```

***************************

As you can see, the classes don't match the data. Whether this is the fault of the data source or the class generator, I couldn't say. You would have to provide more information on how your data and classes are being produced. But the XmlSerializer is doing what it is supposed to do in this instance.
