### ISSUE TITLE
Verify limitation in Compiler::impCanPInvokeInlineCallSite still applies

### ISSUE THREAD

**Issue by fadimounir** [dotnet/runtime#330]
https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/importer.cpp#L6358

Revisit the ifdef'd block on 64-bit, and understand if we still need it. And if so, verify there's test coverage for it.

Context: https://github.com/dotnet/runtime/pull/327

category:implementation
theme:pinvoke
skill-level:beginner
cost:small

**Comment by AndyAyersMS** [comment]
Adding a permalink...

https://github.com/dotnet/runtime/blob/4becc7585148277c041bed2e1099744f7172df21/src/coreclr/src/jit/importer.cpp#L6456-L6490

Seems like we could still hit the problem described in the comment on platforms where we have exception interop. Would be good to verify with an actual test.

Assuming the concern is valid, seems like we could zero out the inline frame return address on entry to any handler or filter in the method to make sure the frame object is properly reset if an exception happens, instead of banishing inline pinvoke. Probably worth some prospecting to see the impact of this on our current codegen.

**Comment by AndyAyersMS** [comment]
I'm going to push this out of 5.0 as it's a nice to have.

**Comment by jakobbotsch** [comment]
@jkoritzinsky Should this be closed in favor of #70109?

**Comment by jkoritzinsky** [comment]
Yes, I think so
