### ISSUE TITLE
Reversed order between StringComparer.InvariantCulture and IgnoreCase version

### ISSUE THREAD

**Issue by faddiv** [dotnet/runtime#33009]
I discovered that some Compare operations outputs different results even when there is no lower-case upper-case relations between them. For example:

`var ch1 = "\uFE63";`
`var ch2 = "\uFF0D";`
`StringComparer.InvariantCulture.Compare(ch1, ch2); // => 1`
`StringComparer.InvariantCultureIgnoreCase.Compare(ch1, ch2); //=> -1`
`ch1.ToUpperInvariant(); //=> remains the same`
`ch2.ToUpperInvariant(); //=> remains the same`

Why is this works this way?

**Comment by danmosemsft** [comment]
@GrabYourPitchforks will know

**Comment by GrabYourPitchforks** [comment]
`ToUpperInvariant` doesn't necessarily do what most people think it does. If a character is not itself uppercase, it performs a simple uppercase mapping transform on the character. Since `U+FE63 SMALL HYPHEN-MINUS` does not have an uppercase form (see https://unicode.org/cldr/utility/character.jsp?a=fe63&B1=Show, heading *Simple_Uppercase_Mapping*), its `ToUpperInvariant` form returns itself. Same deal with `U+FF0D`.

On the other hand, any of the culture-aware `StringComparison` instances (including `InvariantCulture[IgnoreCase]`) will normalize data before performing the comparison. The particular type of normalization that takes place is somewhat too complex to explain here, but it depends largely on your operating system, the comparison being used, and the exact contents of the text.

In the case of `U+FE63`, it will get normalized to a standard hyphen when `InvariantCultureIgnoreCase` is requested.

```cs
Console.WriteLine(string.Compare("\uFE63", "-", StringComparison.InvariantCulture)); // writes > 0
Console.WriteLine(string.Compare("\uFE63", "-", StringComparison.InvariantCultureIgnoreCase)); // writes 0
```

And, under the rules of the invariant sorting logic, a _standard_ hyphen sorts before a _fullwidth_ hyphen (`U+FF0D`).

Again, this depends on your particular OS. I'm on Windows 10 20H1, so my statements are accurate for that operating system. If you're on a different version of Windows, or if you're on a non-Windows platform, your results may differ. Some OSes might even say that `"-"`, `"\uFE63"`, and `"\uFF0D"` are all equivalent under an `InvariantCultureIgnoreCase` comparer. .NET Core simply delegates to the underlying OS.
