### ISSUE TITLE
CloudLinux 6.10 will not run net core web app -- Segmentation fault (core dump)

### ISSUE THREAD

**Issue by wcswanson** [dotnet/runtime#33055]
# Issue Title
CloudLinux 6.10 will not run net core web app -- Segmentation fault (core dump)
Be as descriptive as you can with your title.

# General
I did a self contained install on CloudLinux 6.10 and received the following error Segmentation fault (core dump). The code was compiled with this:
`dotnet publish -c Release -r centos-x64`
It will run on Centos 7 & 8 but not ClouldLinux. Tech support believes it is a memory issue, so I tried to compile the code for just centos but could not get that to work. According to the wiki CloudLinux is built on rhel,

`./hwweb` gets the Segmentation fault on CloudLinux but works on Fedora 30, Centos 7 & 8.
Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by janvorli** [comment]
The problem is that CloudLinux 6.10 is built on RHEL / CentOS 6. That system is too old. We have a special version for RHEL 6 that would work there (unless the CloudLinux deviated from the related RHEL one too much). You need to use rhel.6-x64 RID for your publish command

For the upcoming .NET 5.0, we've dropped support for RHEL 6, so only versions <= 3.1 would work there.
