### ISSUE TITLE
Managed and Native RID discovery can resolve different RIDs

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#33069]
We currently have two methods of resolving the current build's RID. For native components, we use the `init_distro_rid.sh` script in `eng/native`. This script supports discovering RIDs for not-officially-supported distros as well as discovering rids for cross-compilation.

The managed RID discovery mechanism only supports discovering the host RID and then overriding it with a specific RID manually. @am11 reported that was causing him issues when building for android, where the native components built correctly for `android.28-arm64` but the managed components were looking for `linux-arm64`.

**Comment by am11** [comment]
Following components built successfully (with #31701 changes):

* CoreCLR - native and managed
* Libraries - native and managed
* Installer - native

managed components of installer failed at the package step, due to the wrong RID (`linux-arm64`) resolution.

**Comment by ViktorHofer** [comment]
@am11 do you know if there's still work left to do here? Asking as you spent quite a lot of time into consolidating RID logic on at least the managed side.

**Comment by am11** [comment]
Yes, this can be closed. :)

The native RID continues to be calculated in `eng/native/init-distro-rid.sh`, and managed RID is derived from the input from script in some cases (`__DistroRid`). We have combined all managed RIDs calculation in `CalculateRID` property group in `Directory.Build.props` at root of the repo.

For Android, currently it is working but the situation is not ideal as coreclr and mono are using different setups for Android. That requires us to add mysterious conditions and tweaks here and there to make things just work. I opened https://github.com/dotnet/runtime/issues/56622 for discussion. The rootfs setup done by this script: `eng/common/cross/build-android-rootfs.sh` builds both coreclr and mono. If mono.android requires lower API level, we can change https://github.com/dotnet/runtime/blob/58efa4b79751a2dad08d9bf7ca67930f8160afe3/eng/common/cross/build-android-rootfs.sh#L23 and I'll find a workaround where we need glob(3) support in coreclr. But using this setup is a good thing because it will put Android in line with other cross-build setups.
