### ISSUE TITLE
Remove use of reflection in System.Net.NameResolutionPal

### ISSUE THREAD

**Issue by RUSshy** [dotnet/runtime#33127]
Hello

What is the exact reason you are using reflection here? https://github.com/dotnet/runtime/blob/9c82a36c23235c4d50954cb33a4d5d89b787a1aa/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Win32.cs#L13-L14

Can this be avoided? could Assembly.GetExecutingAssembly be used instead?

I personally see no reason to pull in reflection use inside this API, it is has lot of overhead when you don't want to deal with reflection at all in your application

**Comment by jkotas** [comment]
`typeof` and `Type.Assembly` are light weight constructs. They are not the expensive reflection APIs that need to be avoided for performance reasons.

I believe that you have opened this because of the experimental limited reflection mode in CoreRT.  This should be addressed in the limited reflection mode in CoreRT. I do not expect we are going to be doing unnatural changes in dotnet/runtime to make it work.
