### ISSUE TITLE
Remove calls to empty RuntimeHelpers.PrepareConstrainedRegions()

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#33179]
There are ~140 calls to RuntimeHelpers.PrepareConstrainedRegions(). In .NET Core this has no implementation. The calls can be removed.

https://source.dot.net/#System.Private.CoreLib/RuntimeHelpers.cs,5bb48d7700e1ad2e,references

(Except in libraries that we still ship for .NET Framework, except I don't believe any of these are calls from those.)

**Comment by danmosemsft** [comment]
@stephentoub just curious are you aware of an analyzer that flags calls to empty methods (I realize it could be noisy)

**Comment by stephentoub** [comment]
> just curious are you aware of an analyzer that flags calls to empty methods (I realize it could be noisy)

I'm not aware of one, though it's possible there is somewhere.  Unless such an analyzer is cracking open the IL of a referenced assembly, it's not clear how much value it would provide, since it would be for only the same assembly.  And even if it was reading the IL of the called method, it would have difficulty with reference assemblies, which may have a lot of empty methods that aren't actually empty at run time.  On that note, even in an assembly such an analyzer could be quite noisy, e.g. we have partial classes that in one build calls a method that does something meaningful and in another build calls an empty version of that same method.

**Comment by danmosemsft** [comment]
True..

**Comment by Marusyk** [comment]
Please assing it to me

**Comment by danmosemsft** [comment]
@Marusyk it's all yours!
