### ISSUE TITLE
Disable producing NETStandard targeting pack in 5.0 branch

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/runtime#33208]
Net Standard 2.1 packages (with preview branding) are still being produced in 5.0 branches.

This issue was fixed in 3.1 - issue https://github.com/dotnet/runtime/issues/3800

Are we missing the fix in runtime repo?

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/2294

**Comment by dagood** [comment]
https://github.com/dotnet/runtime/issues/3800 covers disabling targeting packs from building during servicing builds only. We don't disable targeting pack builds in general in `master`/`preview` branches because we expect constant API breaks. NETStandard is a special case because it doesn't quite fit in with the repo.
