### ISSUE TITLE
macOS ends up as marked as a cross build

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#33211]
Using `uname -p` on mac returns `i386`, which means here we classify the host as x86:

https://github.com/dotnet/runtime/blob/389835b1597180c0753c4daeb88afe008252dfe4/eng/native/init-os-and-arch.sh#L42

And this cascades into flagging this as a cross build here:
https://github.com/dotnet/runtime/blob/389835b1597180c0753c4daeb88afe008252dfe4/src/coreclr/build-runtime.sh#L183

A better solution might be to use `uname -m`, although there's a comment stating `# Some Linux platforms report unknown for platform, but the arch for machine.` That seems like the desired outcome nonetheless. 

Related: #33164

**Comment by BruceForstall** [comment]
It looks like on macOS, `uname -p` returns `i386`. This previously would end up getting set as the default `arch=x64`, but now `init-os-and-arch.sh` checks for `i[3-6]86` instead of just `i686`, so sets `arch=x86`.

I don't see why the OSX R2R test just started failing on 3/3:

https://dev.azure.com/dnceng/public/_build/results?buildId=545828&view=results

**Comment by BruceForstall** [comment]
Oh, I see -- @jkoritzinsky introduced `init-os-and-arch.sh` with https://github.com/dotnet/runtime/pull/31701 and that changed the semantics.
