### ISSUE TITLE
Restoring harvested packages should be sequenced into the pkgproj's restore phase

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#33226]
Currently we upfront restore all the harvested packages _always_. Adding the individual packages to the respective pkgproj's restore phase, allows us to only restore the packages that are needed and when they are needed. Additionally to that, we can remove the harvestPackages.depproj file.

cc @joperezr @ericstj

**Comment by ericstj** [comment]
You don’t need to do this to remove harvestPackages.depproj.  It can be moved to a single target that defines packagedownload.  Also we only harvest what we need today and I believe that only runs for allconfigurations.  Moving to pkgproj won’t change what is downloaded.  Making restore work from pkgroj might have complications and is not necessarily a desirable thing: what does it even mean in general for a pkgproj to reference packages?

**Comment by ViktorHofer** [comment]
> You don’t need to do this to remove harvestPackages.depproj. It can be moved to a single target that defines packagedownload.

This is more complicated as it seems as harvestPackages.depproj requires a package's task to calculate the PackageDownload items. We would need to add a seconds repo restore phase to make that possible (what we have today).

> what does it even mean in general for a pkgproj to reference packages?

I was more thinking about adding PackageDownload items into the respective pkgprojs instead of PackageReferences. Or to phrase it differently, let the respective pkgproj restore the necessary to be harvested packages themselves instead of central point of restore.

**Comment by ericstj** [comment]
> seconds repo restore phase

I think any solution will require some sort of 2-phase restore since we use a task to calculate PackageDownload.  One way to accomplish 2-phase is to put package tasks into an SDK.  Another way is to eliminate the task but that would result in some sort of static representation (other than package index) of past versions.

> I was more thinking about adding PackageDownload items into the respective pkgprojs instead of PackageReferences

I understand what you are suggesting.  I’m saying your suggested solution supports more than just this.  Doing so may introduce more challenges or unused / undefined features.

Before assuming either path I’d first recommend understanding how difficult it is to make pkgproj support restore directly.  We should have a ‘recipe’ for this as it should be done by ilproj and depproj. /cc @Anipik

**Comment by joperezr** [comment]
Just to add some info to this, harvestPackages runs on every build, not just on all configurations:

https://github.com/dotnet/runtime/blob/fef9ca70f6e7268dfc9e0f600433f5293932f166/src/libraries/restore/dirs.proj#L12

I'm not really sure what is it that we want to optimize here. If we want to remove the second phase restore, I'm not sure on how to do that without having to check in a static list of packages to restore or to write the task that calculates this on runtime repo. If we want to remove the central restore place, I believe this may cause unintended workflow breaks for people that have run restore once and then lose network connection and try to build allConfigurations. If the problem is that restoring this takes time and resources, I'm fine with having this project only build on the AllConfigurations leg, in fact, I think that is probably the right thing to do anyways as we only really ever use those restored packages for harvesting assets or package validation which only happens on an AllConfigurations build.

**Comment by ViktorHofer** [comment]
> I'm not really sure what is it that we want to optimize here. If we want to remove the second phase restore, I'm not sure on how to do that without having to check in a static list of packages to restore or to write the task that calculates this on runtime repo.

Actually we have three upfront restore phases today (for libraries):
1. [Our tools-local](https://github.com/dotnet/runtime/blob/c15835bb194990723e2a5e1a5b1584f1e81f77ba/eng/Build.props#L80)
2. [Arcade's Tools.proj which imports our Tools.props](https://github.com/dotnet/arcade/blob/bc4fa8e7149769db4efd466f160417a32b11f0bf/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj#L182-L185)
3. [Our build.proj Restore target](https://github.com/dotnet/runtime/blob/c15835bb194990723e2a5e1a5b1584f1e81f77ba/src/libraries/build.proj#L18-L29)

My goal is to remove the upfront libraries specific restore phase by sequencing the depproj logic into either the other restore phases or into respective projects, ie pkgproj.

Just talking about harvestPackages.depproj alone, we could add a PackageDownload for the packaging nuget package to our tools-local project (restore phase 1) and convert the harvestPackages.depproj into a simple target which is hooked into restore phase 2 (Tools.props). We already do that for i.e. docs. Long term I would like to explore if we can make pkgprojs restorable so that we can remove the logic from the repo restore and sequence it into our (pkg)projects.

**Comment by ericstj** [comment]
> long term 

Long term I wonder what the better story for pkgproj will be.  We might be able to take the good parts out of it and just make it a mode for packing a csproj.

**Comment by ViktorHofer** [comment]
That would be a preferred option indeed. Maybe we can port some of the required features back into the product (nuget) and implement the rest on top of it

**Comment by ericstj** [comment]
I think we can technically make it work today.  We just shut off the consumption of the assets file, then generate a partial nuspec based on our assembly analysis.  We feed in the partial nuspec to Pack and let it add what it wants (maybe just the files, which IIRC have sufficient extensibility).   Now that's a bit of a hammer, but I think it would work.  We then bring over some of our helpers for harvesting and validation and sequence into pack.  I've discussed here: https://github.com/dotnet/arcade/issues/1033.

**Comment by joperezr** [comment]
Yeah, the Pack target on sdk projects is actually very extensible, I've played with it for the iot repo since that is how we create our packages, you can pretty much modify it to a very big extent to do what we want here.

**Comment by ViktorHofer** [comment]
Closing as we don't plan to continue harvesting assets.
