### ISSUE TITLE
Fallback to base host RID for Microsoft.DotNet.PlatformAbstractions

### ISSUE THREAD

**Issue by akihikodaki** [dotnet/runtime#3329]
dotnet/core-setup#1689 implemented fallback to base host RID for `corehost`, but it doesn't for `Microsoft.DotNet.PlatformAbstractions`.

It must noted that `Microsoft.DotNet.PlatformAbstractions` is on level lower than `corehost` when implementing such a mechanism, you; corehost knows RID graph, but `Microsoft.DotNet.PlatformAbstractions` doesn't. There should be two options due to that:

* Add a code to interpret RID graph and transform the API higher level
* Add yet another low level method, `GetRIDOSFallback` or something similar, which corresponds to `pal::get_current_os_fallback_rid`

I'd like to know how this problem will actually be solved (one of these two or possible something different.) Thanks.

## Steps to reproduce

1. Use `Microsoft.DotNet.PlatformAbstractions` on an exotic platform (on Arch Linux in my case)

## Expected  behavior

It reports known RID such as `linux-x64`.

## Actual behavior

It reports unknown RID such as `arch-x64`.

## Environment data

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by eerhardt** [comment]
We've added the `RuntimeInformation.RuntimeIdentifier` API in .NET 5 (#26780 and #34206). This API will use the fallback RID since it uses the same information as the `corehost`.

We are removing the PlatformAbstractions library with #3470, and recommending to use the new `RuntimeInformation.RuntimeIdentifier` API to get the RID of the current machine.

Closing this issue.
