### ISSUE TITLE
ToImmutableDictionary() doesn't use Dictionary Comparer

### ISSUE THREAD

**Issue by NickLydon** [dotnet/runtime#33379]
I would expect this test to pass:

```
[Fact]
public void dictionary_test()
{
    var mutable = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["a"] = "a"
    };

    Assert.Contains("A", (IDictionary<string, string>) mutable);

    var readOnly = new ReadOnlyDictionary<string, string>(mutable);
    
    Assert.Contains("A", (IDictionary<string, string>) readOnly);

    var immutable = mutable.ToImmutableDictionary();
    
    Assert.Contains("A", (IDictionary<string, string>) immutable); // fails here
}
```

Is it possible to add an overload that accepts a `Dictionary` so that the key comparer is used?

**Comment by eiriktsarpalis** [comment]
Note that the [`ToImmutableDictionary()`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary.toimmutabledictionary?view=net-5.0#System_Collections_Immutable_ImmutableDictionary_ToImmutableDictionary__2_System_Collections_Generic_IEnumerable_System_Collections_Generic_KeyValuePair___0___1___) extension method you are invoking acts on `IEnumerable<KeyValuePair<string,string>` rather than the dictionary type, which should explain why the custom comparer is not taken into account.

You can work around the issue by using the [overload that accepts a comparer argument](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary.toimmutabledictionary?view=net-5.0#System_Collections_Immutable_ImmutableDictionary_ToImmutableDictionary__2_System_Collections_Generic_IEnumerable_System_Collections_Generic_KeyValuePair___0___1___System_Collections_Generic_IEqualityComparer___0__):

```csharp
var immutable = mutable.ToImmutableDictionary(mutable.Comparer);
```
