### ISSUE TITLE
API proposal: Make ImmutableArray readonly struct

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#334]
### Background
It's intuitive to use `ImmutableArray<T>` as readonly fields, and wrap it into other readonly structs. Currently it's not marked readonly, and may cause hidden copies. Although being small itself, immutable arrays are aggresively optimised for performance. Hidden copy of only 1 pointer size can be reduced.

### Proposed API
```diff
namespace System.Collections.Immutable
{
-    public struct ImmutableArray<T>
+    public readonly struct ImmutableArray<T>
}
```

### Works to do
The only write usage of its field is `ImmutableInterlocked`. Given that the layout is the prerequisite of interlocked to work, they should be fine to use `Unsafe.As<ImmutableArray<T>, T[]>`.

Seems that the `Unsafe` class came later than readonly structs. I guess it's the reason not using it.

**Comment by saltukkos** [comment]
First, I was going to say, that JIT will optimize defensive copies anyway like in this case
[sharplab](https://sharplab.io/#v2:C4LghgzgtgPgAgBgARwIwDoDCB7ANrgUwGNgBLbAOwnQEkooBXYMAI0IG4BYAKB7gGYUAJiSYkAbx5JpKQXUbM2BAIIAnVWACeAHlIVgAPiQBZVAApVBAGZJ5TVoTUadew0lJQAlBKky/cAHZ3KHRlABMws1RPLm4/AF9faSTZW3p7JSctXX0jYyEzPTSFBxV1bNcjD29JOL8ZQODQiKiYlMTebnigA=)

But after I change the example to use `Clear` instead of `Add` it just blew up my mind.
[sharplab](https://sharplab.io/#v2:C4LghgzgtgPgAgBgARwIwDoDCB7ANrgUwGNgBLbAOwnQEkooBXYMAI0IG4BYAKB7gGYUAJiSYkAbx5JpKQXUbM2BAIIAnVWACeAHlIVgAPiQBZVAApVBAGZJ5TVoTUadew0lJQAlBKky/cAHZ3KCxCMFUzTy5uPwBfX2kE2Vt6eyUnLV19I2MhMz0UhQcVdUzXIw9vSRi/GUDg0IJwyOi4nh5YoA)

So, we definitely need the `readonly` modifier.

**Comment by huoyaoyuan** [comment]
Going to tag the area owners @eiriktsarpalis @layomia because this seems to be forgotten.
Is this a concrete API proposal?

**Comment by eiriktsarpalis** [comment]
@huoyaoyuan We're currently working our way through a long backlog of untriaged collections issues, so we haven't had the chance to go through this one yet. At first glance this looks reasonable, however we would need to investigate a bit more thoroughly. Thanks.
