### ISSUE TITLE
GetFullPath behavior in .Net Core 3.1.2 differs from .Net 4.6.2

### ISSUE THREAD

**Issue by paiden** [dotnet/runtime#33477]
The following code fragment

```csharp
var x = Path.GetFullPath(@"C:\test:");
```

throws this (expected as the path is invalid) exception when run with .Net 4.6.2

`System.NotSupportedException: 'The given path's format is not supported.'`

But when I run the same code with .Net Core 3.2.1, the method simply returns the input without throwing an exception. AFAIKT the doc does not state that there should be such a behavior change [MSDN GetFullPath .Net Core 3.1](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netcore-3.1)

This looks like a bug in .Net Core 3.X to me.

More discussion regarding this can be found in this [Stack overflow thread](https://stackoverflow.com/questions/60634204/getfullpath-behavior-in-net-core-3-1-2-differs-from-net-4-6-1)

**Comment by vcsjones** [comment]
I suspect this is an intended change, and related to https://github.com/dotnet/dotnet-api-docs/issues/2411.

From a correctness point of view, Windows is fine handling files that end with a colon:

```
echo bye > test.txt:
```

The colon is used to identify alternate data streams in file systems that support it. If I understand NTFS correctly, the "empty" ADS is the file itself with type of $DATA, so in this case it's just "test".

**Comment by paiden** [comment]
It's not only the colon, other cases like 

```csharp 
var x = Path.GetFullPath(@"C:\test>");
var y = Path.GetFullPath(@"C:\test>\");
```
and probably similar ones, do not throw an exception. And '>' AFAIK is not allowed in file names?

Also Path.GetInvalidFileNameChars() contains the ':' character.

So IMO there are definitely some inconsistencies here, that do not make any sense (to me).

**Comment by JeremyKuhne** [comment]
This is an intentional breaking change from .NET Framework. I discuss the reasoning in detail in [this blog post](https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek).

The short of it is that we were blocking legitimate paths. Trying to predict what paths will be thrown back when used is essentially impossible without actually using them. More details on that is in the blog link above.

We didn't change `Path.GetInvalidFileNameChars()` because there isn't a good answer to what to change it to, and it doesn't hurt in common scenarios like filtering what file names you allow users to enter. I've got a few proposals on new APIs that would be more practical, particularly when writing cross platform code.  Notably #25011 and #25010.

**Comment by JeremyKuhne** [comment]
@carlossanlop, it looks the docs aren't updated on exceptions with [`Path.GetFullPath`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netcore-3.1#System_IO_Path_GetFullPath_System_String_). Can you fix this?

**Comment by carlossanlop** [comment]
Sure, I'll update the documentation.
Closing this to track this issue with the older one: https://github.com/dotnet/dotnet-api-docs/issues/2411
