### ISSUE TITLE
Deployment and Servicing guidance for customers

### ISSUE THREAD

**Issue by dleeapho** [dotnet/runtime#3351]
- Particularly for Windows desktop UI scenarios
- How can enterprise customers deploy their apps to Windows clients?
- How can enterprise customers service .NET Core to Windows clients?
- How can customers author MSIX deployments via VS?

**Comment by wjk** [comment]
Just my 2¢ on this issue, since you mentioned MSIX above: Currently, to create a fully self-contained MSIX (for Windows Store deployment, usually) I have to do [something like this](https://github.com/wjk/MSIExtractApp/blob/1481b23b1dbd0076fa5f85fd0f3586b73ece427d/src/MSIExtract.AppxPackage/Directory.Build.targets#L11-L33) to copy the .NET Core runtime into my package's VFS folder. This is much like self-contained deployment, except that there is one copy of the .NET Core runtime across two different top-level targets (the main app and a shell extension, both implemented in Core). However, I still have to package the runtime separately for each app. When several apps that use this technique are installed, the disk space wasted by the duplicate copies of the runtime begins to add up.

One easy solution to this problem is for me to create an MSIX package with `<Framework>true</Framework>` in the AppxManifest.xml file. This would allow all of my applications to depend on this one copy of the runtime. However, I would then need to distribute a copy of the runtime MSIX with each of my apps to ensure it is present on each system, or the app package would fail to install. (Since I am currently planning on using a setup EXE that contains my MSIX so I can publish my self-signed certificate along with the app, this is very easy to do.)

However, this would break Windows Store deployment, as only Microsoft can publish framework packages to the Store. If we could have official .NET Core runtime packages available as dependencies in the Store, that would be amazing. If those dependencies could be downloaded and installed automatically when I try to install an MSIX package from outside the store, that would be even better. (Following this morning's announcement, I am planning on porting as many of my apps as possible to MSIX deployment, to provide the best possible experience on Windows 10X.) Thanks!

**Comment by maxkatz6** [comment]
I believe that issue is related
https://github.com/dotnet/installer/issues/7725

**Comment by dleeapho** [comment]
@maxkatz6 , I believe what @wjk reported is related to #7725. This issue is really just tracking the documentation work.

**Comment by MichaelSimons** [comment]
[Triage] @jamshedd & @adegeo, please link to the doc issues which addressed this as well as any issue tracking the remaining work.

**Comment by adegeo** [comment]
@MichaelSimons I don't think we have any content related to this except for generic mentions of "use the visual studio publish"
