### ISSUE TITLE
dotnet publish --no-build with PublishSingleFile doesn't produce a working executable

### ISSUE THREAD

**Issue by jcberleur** [dotnet/runtime#33655]
## Steps to reproduce

```
mkdir Main 
cd Main
dotnet new console
dotnet build -c Release -r linux-x64
dotnet publish -c Release -f netcoreapp3.1 -r linux-x64 --no-build --no-self-contained /p:PublishSingleFile=true
./bin/Release/netcoreapp3.1/linux-x64/publish/Main
```

## Expected behavior
running the executable works normally

## Actual behavior
running the executable doesn't work with the error:
```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/usr/share/dotnet'.
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by elinor-fung** [comment]
I think this is a result of specifying `--no-self-contained` in the `dotnet publish` step, but not the equivalent in the `dotnet build` step.

I believe the application is built as self-contained by default when specifying a rid. Then, the publish step is just taking that output - which has a configuration file indicating that it is a self-contained application - but not including all the framework bits since `--no-self-contained` was specified.

If you want to publish a framework-dependent (non-self-contained) single-file, could you try building with `dotnet build -c Release -r linux-x64 /p:SelfContained=false` instead?

cc @swaroop-sridhar

**Comment by jcberleur** [comment]
I see

so it is more that the `dotnet build` self contained option is undocumented

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/sdk/issues/10608
