### ISSUE TITLE
Test failure: Interop\\NativeCallable\\NativeCallableTest\\NativeCallableTest.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#33663]
failed in job: [runtime-coreclr jitstress 20200315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=560455&view=ms.vss-test-web.build-test-results-tab&runId=17650420&resultId=100828&paneView=debug)

error message:
```
Assert failure(PID 1532 [0x000005fc], Thread: 5560 [0x15b8]): !PreemptiveGCDisabled()
CORECLR! Thread::DetachThread + 0x112 (0x00007ffce57d0d6e)
CORECLR!EEDllMain'::5'::__Body::Run + 0x143 (0x00007ffce5696997)
CORECLR! EEDllMain + 0x2A (0x00007ffce5692d52)
CORECLR! DllMain + 0x37 (0x00007ffce562bfaf)
CORECLR! CoreDllMain + 0x9F (0x00007ffce562bf4f)
NTDLL! RtlDeactivateActivationContextUnsafeFast + 0x1BF (0x00007ffd149c38ff)
NTDLL! LdrShutdownThread + 0x151 (0x00007ffd149c0f91)
NTDLL! RtlExitUserThread + 0x3E (0x00007ffd149ab07e)
KERNELBASE! FreeLibraryAndExitThread + 0x43 (0x00007ffd10efb8f3)
KERNEL32! FreeLibraryAndExitThread + 0xA (0x00007ffd1271fb1a)
File: F:\workspace\_work\1\s\src\coreclr\src\vm\threads.cpp Line: 928
Image: C:\h\w\96D90843\p\CoreRun.exe
Return code: 1
Raw output file: C:\h\w\96D90843\w\C2590A16\e\Interop\NativeCallable\Reports\Interop.NativeCallable\NativeCallableTest\NativeCallableTest.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\96D90843\p\corerun.exe" NativeCallableTest.dll
Running TestNativeCallableValid...
Running TestNativeCallableValid_OnNewNativeThread...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\96D90843\p
> C:\h\w\96D90843\w\C2590A16\e\Interop\NativeCallable\NativeCallableTest\NativeCallableTest.cmd
Expected: True
Actual: False


Stack trace:
at Interop_NativeCallable._NativeCallableTest_NativeCallableTest_._NativeCallableTest_NativeCallableTest_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Interop.NativeCallable\Interop.NativeCallable.XUnitWrapper.cs:line 140
```

**Comment by AaronRobinsonMSFT** [comment]
@jkotas or @davidwrighton Any idea why during [`Thread::DetachThread()`](
https://github.com/dotnet/runtime/blob/0d19a5e18a988ad52ca0c2907edeb40ba4e00d9b/src/coreclr/src/vm/threads.cpp#L882-L886) - where `fDLLThreadDetach = TRUE`, the following assert would be a hard requirement? I assume this should be generally true since we would want a proper separation to have occurred, but in this case that doesn't seem to be have happened. I am seeing this assert fire when `COMPlus_TailcallStress=1`.

https://github.com/dotnet/runtime/blob/0d19a5e18a988ad52ca0c2907edeb40ba4e00d9b/src/coreclr/src/vm/threads.cpp#L935

This detach is occurring after the [new Reverse P/Invoke enter helper](https://github.com/dotnet/runtime/blob/0d19a5e18a988ad52ca0c2907edeb40ba4e00d9b/src/coreclr/src/vm/jithelpers.cpp#L5390-L5410) is called put prior to [exit helper](https://github.com/dotnet/runtime/blob/0d19a5e18a988ad52ca0c2907edeb40ba4e00d9b/src/coreclr/src/vm/jithelpers.cpp#L5412-L5421).

@dotnet/jit-contrib Can someone educate me on what setting the following `COMPlus_TailcallStress=1` does?

**Comment by sandreenko** [comment]
@AaronRobinsonMSFT it treats calls as if they have explicit IL tail-call prefix when it can. So it creates tail calls even if they are not profitable.

**Comment by AaronRobinsonMSFT** [comment]
The issue here isn't that the thread is exiting prior to calling the exit helper, the exit helper just isn't being called here since the call to the function is being done via a `jmp` and from within that function call a `ret` is being used which means the enclosing reverse P/Invoke frame isn't being cleaned up/reset by a call to [`JIT_ReversePInvokeExit`](https://github.com/dotnet/runtime/blob/0d19a5e18a988ad52ca0c2907edeb40ba4e00d9b/src/coreclr/src/vm/jithelpers.cpp#L5412-L5421).

**Comment by AaronRobinsonMSFT** [comment]
@sandreenko Ah. That makes sense. Thank you.

With the above knowledge, it looks like we should disable tail calls in general for functions marked with the `NativeCallableAttribute`. On the other hand perhaps the reverse P/invoke frame needs to be modified. I will need to defer to someone else to make that decision.

**Comment by jkotas** [comment]
> we should disable tail calls in general for functions marked with the NativeCallableAttribute

+1
