### ISSUE TITLE
Need to include libraries in iOS packaging

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#33752]
To complete the packaging story for iOS, we need to include the libraries (the entire netcoreapp).  

@NikolaMilosavljevic @dagood, I was told the installer may already do this and that you may be able to help?

**Comment by dagood** [comment]
Is there a design for how we want the iOS dev experience to work overall? I assumed iOS was just another RID when I responded to your IM earlier, but with a quick search I see it's connected to Mono, e.g. https://github.com/dotnet/runtime/issues/33690, https://github.com/dotnet/runtime/issues/1018.

I heard of a plan maybe a year ago to ship .NET 5 Mono as a runtime pack only (set of runtime packs?) with some additional data in the package id to differentiate the mono VM vs. coreclr, but nothing since then. At this point I think we could point you to the files responsible for packaging netcoreapp but I think we're missing context to actually do this right.

I *think* I'm echoing @jaredpar's comment at https://github.com/dotnet/runtime/issues/1018#issuecomment-583034733, which suggests the runtime pack thing I'm mentioning about is no longer the plan.

**Comment by dsplaisted** [comment]
iOS and android will be represented in the `TargetFramework` property, ie `net5.0-ios14` or `net5.0-android21`.  The OS portion will be broken down into the `TargetPlatformIdentifier` and `TargetPlatformVersion` properties.  Here's the design for that: https://github.com/dotnet/designs/pull/92

The selection of the runtime pack is done by the .NET SDK.  For iOS and Android that will probably in concert with the iOS and Android optional components (ie they would supply KnownFrameworkReference items).

So I think the iOS and Android runtime packs will work pretty much the same as the existing runtime packs.  The logic to select which one to use may change a bit, but would still generally be based on the target framework and the RID.

Does that make sense?

**Comment by akoeplinger** [comment]
Sounds good, who can work on adding the package for iOS?

**Comment by dagood** [comment]
Very helpful, thanks @dsplaisted.

RIDs for this are e.g. `ios.8-x64`. We'll need logic in `src/installer/pkg/projects/netcoreapp/src/netcoreapp.depproj` (and files that feed paths into it like `eng/liveBuilds.targets`) to gather up the right Mono assets when building for that RID, and a new set of official build jobs to build the new platforms in `installer`:

https://github.com/dotnet/runtime/blob/8a83488465f101e3ec2620cb1eb2a8c3d7cc1a1c/eng/pipelines/runtime-official.yml#L119-L121

/cc @dleeapho

**Comment by Redth** [comment]
Not sure this is in scope of this issue but it may help to keep in mind that generally when we talk about building android and iOS apps we need to build _multiple_ RID’a at once.

**Comment by dagood** [comment]
@Redth it sounds like you're asking for https://github.com/dotnet/sdk/issues/6490 or https://github.com/dotnet/sdk/issues/9363, or something like that. (But yeah, it's not part of this issue.)

**Comment by NikolaMilosavljevic** [comment]
Have a plan for this work on Mono side. All questions have been answered.
