### ISSUE TITLE
Use span-based string.Concat

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33777]
The rule should flag instances of a pattern like `str1 + str2.Substring(...) + str3` or `string.Concat(str1, str2.Substring(...), str3)` and instead switch to using the span-based `string.Concat(str1, str2.AsSpan(...), str3)`.

**Category**: Performance
**Suggested severity**: Info

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Medium

**Comment by Mrnikbobjeff** [comment]
The invocation of concat with substring can be caught by [the string.Substring(x) analyzer](https://github.com/dotnet/runtime/issues/33784)

**Comment by buyaa-n** [comment]
Should this analyzer flag a case without Substring() and suggest Concat? like  `str1 + str2 + str3 => string.Concat(str1, str2, str3)`

**Comment by bartonjs** [comment]
* Find calls to `str1 + str2.Substring(...) + ...` (but not `string.Concat(str1, str2.Substring(...), ...)`, since that's in a different analyzer)
* If there's an applicable overload of string.Concat that accepts ReadOnlySpan&lt;char> with the correct number of arguments, suggest changing the Substring call to AsSpan and calling string.Concat
* Don't arbitrarily suggest changing str1 + str2 to string.Concat(str1, str2).

Category: Performance
Suggested severity: Info

**Comment by carlossanlop** [comment]
@Mrnikbobjeff was this one of the analyzer proposals that you had already started working on? It's been approved, so let us know if you'd like to work on it.

**Comment by NewellClark** [comment]
I would like to be assigned to this.

**Comment by NewellClark** [comment]
Quick question about trivia: if we have `foo /*A*/ + /*B*/ bar.Substring(1)`, do we want to turn it into `string.Concat(foo, /*A*/  /*B*/ bar.AsSpan(1))`, or `string.Concat(foo /*A*/ , /*B*/ bar.AsSpan(1))`? If we want the first option, do we want to collapse the double spaces between `/*A*/` and `/*B*/`? If we want the second option, do we want to collapse the extra spaces to the left of the comma?

**Comment by NewellClark** [comment]
[Analyzer/fixer](https://github.com/dotnet/roslyn-analyzers/pull/4764) and [docs](https://github.com/dotnet/docs/pull/24270) have been completed. This issue can be closed.

**Comment by jeffhandley** [comment]
Thanks, @NewellClark!!
