### ISSUE TITLE
Forward CancellationToken to methods that can take it

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33774]
The rule should try to identify places where a `CancellationToken` should have been passed but wasn't, e.g. in an async method that takes a `CancellationToken`, a method is called that has an overload that takes a `CancellationToken` but a shorter overload that doesn't take a `CancellationToken` was used instead.

**Category**: Reliability

**Comment by stephentoub** [comment]
cc: @marklio

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Medium

**Comment by stephentoub** [comment]
> Analyzer: Small

The challenge here is around ensuring we invest enough thought in the design to minimize false positives.  It might be more than "small".

> Fixer: Medium

Conversely, I would guesstimate that once we've identified the problem (e.g. method XYZ(arg1, arg2, arg3) is being called, you have a cancellation token, and there's an XYZ(arg1, arg2, arg3, cancellation token) overload you could be using instead), fixing it will be fairly straightforward.

**Comment by bartonjs** [comment]
Analyzer heuristic:

* Only applies to methods using the async state machine generator (`async`/`await`) that take a `CancellationToken` value.
* For all invocation operations, if the invocation is already passing a CancellationToken, move to the next invocation.
* Otherwise, if the method is being invoked with an *implicit* default CancellationToken, or there is an overload to the method that takes a CancellationToken, report a warning against the method invocation (e.g. squiggle under the word "PostAsync" in a call like "client.PostAsync(data)`).

Fixer:
* No fixer if the current async method takes more than one CancellationToken.
* When the target method already takes a CancellationToken, but is invoked with a default parameter, specify the parameter (using the named parameter syntax if required).
* When an overload has the CancellationToken in a "one more parameter" or "one named parameter" compatible call, pass the declaring method's CancellationToken.
* If there is no "call compatible" overload, no fixer.

**Comment by marklio** [comment]
@bartonjs I would also be wary of fixers in the following "harder to detect" scenarios:
* The method makes use of a CancellationTokenSource
* The method registers callbacks on a token - We had some tricky finds in the prototype we built where passing a default token was the right thing to do because the cancellation strategy relied on the callback to keep state uncorrupted. Careful review was required to recognize this. Stephen saw it and I didn't.

**Comment by AArnott** [comment]
This is redundant with https://github.com/microsoft/vs-threading/issues/591, which is likely to get funded soon.
The vs-threading analyzers target less frameworks than .NET 5. Can we consolidate rules for this one on vs-threading so that folks can get the benefit without targeting .NET 5?

Or if your plan is to target all TFMs with these analyzers, I can close ours as redundant with yours.

**Comment by AArnott** [comment]
The .NET 5 SDK requirement is unfortunate, and means that the very *earliest* people can use these analyzers in a stable form in November, right?

> And shipping the VS analyzers in-box doesn't make a lot of sense.

I'd like to discuss this further. We actually already have a backlog item on the fxcop analyzer package to add a dependency on the vs-threading analyzers package. There's nothing VS-specific about them, nor ever will be. We have a separate analyzer package for VS-specific concerns. 
We have a lot of value in the existing vs-threading analyzers that go well beyond this issue or any other issue I see on your backlog. 
I'd like to avoid multiple analyzers that verify the same thing, both to avoid customer frustration with suppressing multiple analyzers or seeing duplicate warnings, as well as to avoid wasted effort across teams in developing similar rules.

Also, *moving* analyzers from vs-threading to roslyn-analyzers has a couple of major downsides:
1. the rule ID would presumably change, along with our AdditionalFiles naming scheme, which would be disruptive to our existing users.
1. it wouldn't be available downlevel where it exists today.

After discussions with the Roslyn team (@jinujoseph in particular) we came to the conclusion that the best thing would be to add a package reference to the vs-threading analyzers package from `Microsoft.CodeAnalysis.FxCopAnalyzers`.

With that in mind then, does that change how you feel about any of this?

**Comment by stephentoub** [comment]
> so we wrote our own analyzer to fill in the gap.

FWIW, I'd prefer the default reaction to be "let's fix the existing analyzer" rather than "let's build a duplicative analyzer".

> if we followed your proposed rule nothing would be flagged, leaving bugs in a large method where the token wasn't always passed in.

Yup.  I still believe explicitly passing in `default` is the better route.  Setting `cancellationToken = default;` has the issues I outlined, and is generally an unnatural gesture.  If code wants to do that and continue to pass in cancellationToken, that's fine, but I strongly believe the analyzer should not warn if the caller is passing in a token, regardless of that token's value.

> > I don't remember where the cited constraint came from.

> The issue description itself

No, I mean, I don't remember why the issue says that.

**Comment by AArnott** [comment]
> FWIW, I'd prefer the default reaction to be "let's fix the existing analyzer" rather than "let's build a duplicative analyzer".

I like that. But when we did this, it wasn't an analyzer. It was a built-in compiler warning. And the compiler team made an intentional choice to *not* warn in that case because they wanted upgrading compiler versions to not produce a bunch of new warnings in existing code.

> but I strongly believe the analyzer should not warn if the caller is passing in a token, regardless of that token's value.

That's fine. I'm flexible on that point. I just wanted to share what research and thought had already gone into the area.

**Comment by stephentoub** [comment]
> I like that.

Great.

>  But when we did this, it wasn't an analyzer. It was a built-in compiler warning. And the compiler team made an intentional choice to not warn in that case because they wanted upgrading compiler versions to not produce a bunch of new warnings in existing code.

Sorry, I was typing too quickly earlier... I meant to say "awaited without a ConfigureAwait".  That's the functionality I was referring to.  That's always been an analyzer (or previously IL-based FxCop rule) rather than a compiler warning.

**Comment by bartonjs** [comment]
I wrote it down because it got said on the call :smile:.  I think it was just trying to limit work; but if it's already been shown to not be too much work, then the more the merrier.

**Comment by AArnott** [comment]
> I meant to say "awaited without a ConfigureAwait".

Ah, yes. And if/when we consolidate, I imagine our version of that analyzer will just disappear, assuming a comparison shows ours doesn't add anything unique any more.

**Comment by stephentoub** [comment]
> I think it was just trying to limit work

Work (CPU) done by the analyzer you mean? (As opposed to work done by a developer implementing the analyzer)

**Comment by stephentoub** [comment]
> assuming a comparison shows ours doesn't add anything unique any more.

If it does, we should consolidate, rather than have two :smile:

**Comment by bartonjs** [comment]
Yeah, the CPU-work of finding "compatible" alternatives that take a CancellationToken.  (Implicitly using a default value seems pretty mild) ... at least, if it's a rule that we expect to be on by default during CLI compilations.

Though it's probably enough noise that we wouldn't even turn it on by default with the "waves".

**Comment by carlossanlop** [comment]
The issue has been assigned to me, but I'd like to know if we have green light to start working on this.

From the above discussion it's not entirely clear to me what course should we take:

- Should I move an existing `microsoft/vs-threading` analyzer to `dotnet/roslyn-analyzers` and improve it?
- Should I write one from scratch in `dotnet/roslyn-analyzers`
- Or something else?

Also, regarding these comments:

> I meant to say "awaited without a ConfigureAwait". That's the functionality I was referring to. That's always been an analyzer (or previously IL-based FxCop rule) rather than a compiler warning.

> I think it was just trying to limit work; but if it's already been shown to not be too much work, then the more the merrier.

It may be helpful/relevant to mention that I recently merged a new Roslyn analyzer that looks for any `Stream.ReadAsync` or `Stream.WriteAsync` invocations and suggests the better, newer overload with slightly different arguments. The analyzer will only generate a diagnostic when the invocation is awaited, and it also works if the user calls `ConfigureAwait`. I'm currently working on the fixer, which will be capable of detecting the CancellationToken argument if the user passed one. Here's the [issue](https://github.com/dotnet/runtime/issues/33790), the [analyzer PR](https://github.com/dotnet/roslyn-analyzers/pull/3497) and the [fixer PR](https://github.com/dotnet/roslyn-analyzers/pull/3592), for anyone curious.

**Comment by stephentoub** [comment]
> Should I write one from scratch in dotnet/roslyn-analyzers

Yes.  (There isn't one implemented in vs-threading, just the idea for one.)

> Or something else?

Please sync with @marklio.  He has a prototype implementation of one.  It may not be exactly the direction we want to go, but it might help seed some ideas.

> It may be helpful

Thanks.  I suggest we start with something along the lines of the following:
- For methods that take one CancellationToken argument, optional or not.
- Find all method calls in its body.
- Ignore any that take a CancellationToken parameter to which something is already being passed explicitly, e.g. don't warn if the supplied token, `default`, `default(CancellationToken)`, `CancellationToken.None`, or anything else is being explicitly passed....
- Warn on any that take an optional CancellationToken parameter where that parameter has been omitted, e.g. calling stream.WriteAsync(readOnlyMemory), as that has an optional CancellationToken parameter that was omitted.
- Warn on any that have an overload that takes the exact same parameters as are currently being passed plus a CancellationToken parameter, e.g. if stream.WriteAsync(array, 0, array.Length) is called, it should warn because there's a stream.WriteAsync(byte[], int, int, CancellationToken) overload.

We may need to tweak this a bit as we go, but my expectation is this will lead to a reasonable balance between false positives and false negatives.

**Comment by carlossanlop** [comment]
> _Please sync with @marklio. He has a prototype implementation of one. It may not be exactly the direction we want to go, but it might help seed some ideas._

I synced with Mark and he shared the prototype with me. I'm taking a look to determine how much of the code can be reused for this analyzer.

**Comment by stephentoub** [comment]
Thanks.

**Comment by carlossanlop** [comment]
The code has been merged. Reopening because the [documentation PR](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6752) is still being reviewed.

**Comment by carlossanlop** [comment]
This roslyn analyzer has been merged as well as its documentation, so we can consider it fixed.
Only pending task is to merge the PR that applies this analyzer's findings in the runtime repo, which is being tracked here: https://github.com/dotnet/runtime/pull/37607
