### ISSUE TITLE
Override Stream.ReadByte/WriteByte

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33788]
The rule should flag types derived from `Stream` that don't override `ReadByte` or `WriteByte`.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Medium

**Comment by stephentoub** [comment]
> Fixer: Medium

I don't think there's anything meaningful a fixer could do here

**Comment by carlossanlop** [comment]
This analyzer is related to https://github.com/dotnet/runtime/issues/33789 . Let's consider adding this case to that one, instead of creating a new analyzer.

And just like in https://github.com/dotnet/runtime/issues/33789, we should scope this to only types that are directly derived from `Stream` (and not a derived type).

- Suggested severity: Info
- Suggested milestone: Future
- Suggested category: Performance
- No fixer: VS already offers the option "Generate overrides", and the user can then select to override `ReadByte` and `WriteByte`:
![image](https://user-images.githubusercontent.com/1175054/108909264-31df4180-75d9-11eb-9c52-c37b82ad7abd.png)

![image](https://user-images.githubusercontent.com/1175054/108909309-3efc3080-75d9-11eb-954a-67617d848246.png)

**Comment by bartonjs** [comment]
Knowing to override ReadByte and WriteByte is something that would show up in a performance analysis, and a performance-improvements focus would likely have already highlighted it.

Without usage on a specific Stream-derived type saying that ReadByte/WriteByte were even called, this is too low value considering the already high cost of implementing a Stream "properly", and so doesn't seem justified.

The group got sidetracked by theorizing about a `DelgatingStream : Stream` type and a new intermediate `Stream` type that rewrites everything in terms of fewer protected abstract methods focused on Span/Memory... but that's not really what this issue was about.
