### ISSUE TITLE
Prefer Nullable<T>.GetValueOrDefault() over manual checking

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33792]
After checking a `Nullable<T>.HasValue`, it's common to see calls to `Nullable<T>.Value`; instead of calling `Value`, it's less work to call `GetValueOrDefault()`, as `Value` repeats the `HasValue` check.  It's possible a future JIT could optimize away the duplicate check, but if nothing else using `GetValueOrDefault()` makes the job of the JIT easier.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Medium

**Comment by GSPP** [comment]
This is a high-noise analyzer. `GetValueOrDefault` is preferable from a performance standpoint, but this does not matter for 99% of the code.

From a style perspective, `Value` is preferable because semantically is more correct than `GetValueOrDefault`. You never want a default. If anything, you want the explicit assertion in `Value`.

If many high-noise analyzers like this one are default-on then people will learn that the analyzer suite is not meaningful to their work.

**Comment by stephentoub** [comment]
> If many high-noise analyzers like this one are default-on then people will learn that the analyzer suite is not meaningful to their work.

It wouldn't be on by default.

**Comment by xtqqczze** [comment]
The CodeGen issue is #13699.

**Comment by iSazonov** [comment]
What about correlation with [IDE0030: UseCoalesceExpressionForNullable](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0030)?
The rule suggest `x ?? y` instead of `x != null ? x : y` when x and y are nullable _value_ types or nullable _reference_ types.
For the new analyzer I'd prefer `x.GetValueOrDefault(y)` for value types - this clearly indicates that the type is value, which adds readability to the code. In the case IDE0030 should be changed to work only for reference types.

**Comment by carlossanlop** [comment]
Suggested severity: Hidden
Milestone: Future

```cs
int? x = null;


// Before: The else has the exact same code as in the if body, but instead of x.Value it uses y, and is used only once
int p;
if (x.HasValue)
{
    p = x.Value;
}
else
{
    p = 5;
}
// After
p = x.GetValueOrDefault(5);




// Before: The else has the exact same code as in the if body, but instead of x.Value it uses y, and is used only once
int y = 3;
if (x.HasValue)
{
    Console.WriteLine(x.Value);
}
else
{
    Console.WriteLine(y);
}
// After
Console.WriteLine(x.GetValueOrDefault(y));




int e;
// Before: A case where "IDE0030: Coalesce expression" will be offered
e = x.HasValue ? x.Value : y;
// After: We continue offering the IDE0030 fixer
e = x ?? y;
// But we also offer our new fixer
e = x.GetValueOrDefault(y);




// Before: Difficult case (optional), where Nullable<T> is used in multiple places in the if and else, but the body is the same
int w = 5;
if (x.HasValue)
{
    Console.WriteLine(x.Value);
    Foo(x.Value);
    Bar();
}
else
{
    Console.WriteLine(w);
    Foo(w);
    Bar();
}
// After
int z = x.GetValueOrDefault(w);
Console.WriteLine(z);
Foo(z);
Bar();




// Not flagged: There is no else
if (x.HasValue)
{
    Console.WriteLine(x.Value);
}




// Not flagged: Code inside if/else is different
if (x.HasValue)
{
    Console.WriteLine(x.Value);
}
else
{
    x = 5;
    Foo(x.Value);
}
```

**Comment by bartonjs** [comment]
The feeling in the room during API review is we should just fix the JIT here.  The resulting code this suggests looks rather unnatural.

**Comment by xtqqczze** [comment]
This issue has been fixed in the JIT in .NET 6, see https://github.com/dotnet/runtime/issues/13699#issuecomment-902961514.
