### ISSUE TITLE
Do not call Task.WhenAll with a single argument

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33806]
There's no reason to call `WhenAll` with a single `Task`; just use the `Task`.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Medium

**Comment by carlossanlop** [comment]
If the API review folks agree, we can group this proposal with https://github.com/dotnet/runtime/issues/33807.

If they prefer a separate rule ID, then please approve separately.

Here is a usage example:
```cs
using System.Threading.Tasks;

namespace MyNamespace
{
    class Sample
    {
        public static void Main()
        {
            Task task = ...;

            // Instead of this
            Task.WhenAll(task);
            // Suggest this
            task.Wait();

            // Instead of this
            Task.WhenAll(GetTask());
            // Suggest this
            GetTask().Wait();

            // Analyzer should trigger, but should not offer a fix because whenResult is used somewhere else
            Task whenResult = Task.WhenAll(task);
            DoSomethingWithTask(whenResult);
        }

        static Task GetTask()
        {
            return ...;
        }

        static void DoSomethingWithTask(Task task)
        {
            ...;
        }
    }
}
```

- This analyzer should not affect any of the other `WhenAll` overloads, because they take a `Task[]`. Only this overload, which takes a `params Task[] task` would be affected.
- This analyzer should also have a fixer, except for the 3rd case indicated in the usage example.
- Suggested severity: Info.
- Suggested milestone if approved: 6.0 (seems simple to address).

**Comment by terrajobst** [comment]
* Makes sense, but we shouldn't use `Wait()`:

```C#
async Task M()
{
    // Before
    await Task.WhenAll(task);

    // After
    await task;
}
```

**Comment by carlossanlop** [comment]
Thanks for the correction, and thanks for approving.

**Comment by carlossanlop** [comment]
This is also yours, @ryzngard, per your request in https://github.com/dotnet/runtime/issues/33807. Thanks for your help! Let us know if you have any questions.

**Comment by jeffhandley** [comment]
@ryzngard Here's a [getting started guide](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/NetCore_GettingStarted.md) as well.  Included in there is our typical "Definition of Done" for creating .NET Libraries analyzers.

**Comment by ryzngard** [comment]
@jeffhandley @terrajobst checked into https://github.com/dotnet/roslyn-analyzers/tree/release/6.0.1xx-preview4

**Comment by stephentoub** [comment]
This was implemented as CA1842/1843. Thanks!
