### ISSUE TITLE
Do not call Task.WaitAll with a single argument

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33807]
`Task.Wait` can be used instead.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Small

**Comment by Mrnikbobjeff** [comment]
I have a working analyzer for this as well, if this is ready to implement. #33806 is very similar, my analyzer would offer a great basis for that issue.

**Comment by carlossanlop** [comment]
Here is a usage example:
```cs
using System.Threading.Tasks;

namespace MyNamespace
{
    class Sample
    {
        public static void Main()
        {
            Task task = ...;

            // Instead of this
            Task.WaitAll(task);

            // Suggest this
            task.Wait();

            
            // Instead of this
            Task.WaitAll(GetTask());

            // Suggest this
            GetTask().Wait();
        }

        static Task GetTask()
        {
            return ...;
        }
    }
}
```

- This analyzer should not affect any of the other `WaitAll` overloads, because they take a `Task[]`. Only this overload, which takes a `params Task[] task` would be affected.
- This analyzer should also have a fixer.
- Suggested severity: Info.
- Suggested milestone if approved: 6.0 (seems simple to address).

### Questions
- Should we group this proposal with https://github.com/dotnet/runtime/issues/33806 (same but for `WhenAll`) into a single Roslyn Analyzer ID?

**Comment by terrajobst** [comment]
* Makes sense

```C#
void M(Task task)
{
    // Before
    Task.WaitAll(task);

    // After
    task.Wait();
}
```

**Comment by ryzngard** [comment]
I'll take this and #33806

**Comment by carlossanlop** [comment]
It's yours, @ryzngard. Thanks for your help! Let us know if you have any questions.

**Comment by stephentoub** [comment]
This was implemented as CA1842/1843. Thanks!
