### ISSUE TITLE
Building a .NET Standard project that references a .NET Framework assembly using System.Net.Http results in a warning

### ISSUE THREAD

**Issue by Epic-Santiago** [dotnet/runtime#33888]
[standard2framework.zip](https://github.com/dotnet/runtime/files/4361713/standard2framework.zip)
I realize it's unusual to reference a .NET Framework assembly from a .NET Standard project but it is possible and I believe supported.

This works fine except when the .NET Framework project references System.Net.Http and uses it (if it doesn't use it, the reference seems to be discarded and the warning disappears).

The warning is:

> warning MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

I have a attached a trivial repro.

I tried the solutions from [StackOverflow](https://stackoverflow.com/questions/48866419/found-conflicts-between-system-net-http/52102147) such as adding a dummy reference to System.Buffers but I couldn't resolve the warning.

**Comment by danmosemsft** [comment]
cc @joperezr

**Comment by joperezr** [comment]
Hey @Epic-Santiago I actually believe that I have already taken a look at this specific one since an internal coworker refer me to this exact example. Internally I did tell him that first off the example you had was using the wrong way to reference one project from another, since instead of using `<Reference ..` it should really be using `<ProjectReference`. If you were to do that, you'll see that we would actually be throwing a different warning as well, telling you that what you are trying to do is unsupported and that you may encounter errors at runtime. The fact that you get the other warning about System.Net.Http, is just a side effect of falling into this unsupported scenario, and unfortunately there is not much you can do to get rid of it. My suggestion would be that whenever you are trying to port a large codebase from .NET Framework into .NET Standard, you should start from the bottom up, meaning start with the libraries that don't have other dependencies (within your code). That way you wouldn't fall into unsupported territory and your projects will work just fine.

All that aside, even if you hit this warning, if you actually continue working without fixing this issue, it is likely that the app will run fine in the end as we have some tooling in place in most of our frameworks that might fix this problem at runtime.

**Comment by joperezr** [comment]
I'll leave this open for now to give you some time to ask any follow-up questions in case you need more details here, but if you think my answer above is enough we can go ahead and close this issue.

**Comment by Epic-Santiago** [comment]
Thanks for the response @joperezr.
I think both references are valid, either a `Reference` to an assembly or a `ProjectReference` to another project in the solution. I used a `Reference` in my repro because it reflects our real world use case where we have thousands of projects (this is a large enterprise application) and having a giant solution so we can use `ProjectReference` is not feasible.

In any case, I'm familiar with the warning you mention when doing the `ProjectReference`:

> warning NU1702: ProjectReference '...\ClassLibraryFramework.csproj' was resolved using '.NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This project may not be fully compatible with your project.

That warning makes sense but I think that the MSB3277 warning is due to something else as I can reference plenty of other packages and the only one giving me that warning is System.Net.Http.

I would be fine temporarily suppressing NU1702 as that is a warning that is directly related to what I'm doing (referencing net48 from netstandard2.0). But suppressing MSB3277 is problematic as that is is a warning that is not directly related to the use case and I could be hiding warnings that I don't wish to ignore.

What further leads me to believe that this is a specific problem with System.Net.Http is that this assembly/package has a history of issues with version resolution [for example](https://github.com/dotnet/runtime/issues/24382).

As for your comment to start bottom up, you are of course correct and this is what we are attempting to do. Unfortunately the project at the root of our entire product is the one that will be most difficult to port and right now it is holding up converting thousands of other projects. I am hoping to temporarily leave it as net48 while we convert everything else to netstandard2.0 so that we can continue working on it in parallel while not holding up the rest of the conversion. But if that means building every other project with warnings or with a warning suppression, that is not ideal.

**Comment by joperezr** [comment]
> I think both references are valid, either a Reference to an assembly or a ProjectReference to another project in the solution.

I'm not saying that using `<Reference` is not valid, but whenever you are using it, you should be really really careful, since you are basically bypassing all of the project reference logic that is built-in to MSBuild to ensure the right configuration is always picked. Using `<Reference`  when both projects target the exact same framework might be fine (and I say might because by doing so, you need to also understand that you are also bypassing the logic NuGet does in order to make sure it also copies your reference's transitive dependencies over, which not always happen magically), but whenever you have projects that target different frameworks (like your case) you will probably just be shooting yourself on the foot as you are bypassing both MSBuild project reference logic and NuGet's transitive dependency logic.

> That warning makes sense but I think that the MSB3277 warning is due to something else as I can reference plenty of other packages and the only one giving me that warning is System.Net.Http.

The reason why you hit this in your project is in fact because of this unsupported issue. More specifically, System.Net.Http is an assembly that exists inbox (meaning it ships inside the framework) for both .NET Framework and .NET Standard (ships as a shim). Those two inbox System.Net.Http have conflicting versions, which is why you are seeing the warning you are seeing. The reason why you are able to just reference other packages and that doesn't give you problems, it is most likely because those other packages must not be shipping inbox on both places, or at least are not shipping inbox using the same assembly identity (same assembly name). 

> What further leads me to believe that this is a specific problem with System.Net.Http is that this assembly/package has a history of issues with version resolution for example.

The reason why System.Net.Http usually has more problems than others, is in fact because of what I explained above, System.Net.Http is one of the few assemblies where we didn't change the assembly identity between .NET Framework and .NET Standard and .NET Core. For most other assemblies, we changed the assembly identity when we first shipped .NET Core and .NET Standard (for example, System.Collections in .NET Framework vs System.Collections.Immutable in .NET Core and .NET Standard) so we don't run into issues of runtimes getting the wrong assumption of one of the assemblies.

>As for your comment to start bottom up, you are of course correct and this is what we are attempting to do. Unfortunately the project at the root of our entire product is the one that will be most difficult to port and right now it is holding up converting thousands of other projects

That is reasonable, and do know that things will most likely work just fine at runtime even if you get these warnings at build time, it is not guaranteed but it is very possible. One thing that could make that even more failure-proof, would be to change that bottom project to target .NET 4.6.1 as that one has fewer APIs that exist in .NET Framework but  not in .NET Standard when compared to .NET 4.8.

**Comment by joperezr** [comment]
> having a giant solution so we can use ProjectReference is not feasible.

Also one more note I forgot to mention, in order to use `ProjectReference` you don't necessarily need the projects to be part of the same solution, you can just manually add the ProjectReference to the .csproj and things should just work. This is the way we do it in our runtime repo, if you see, most of our projects under src/libraries/*/ref/*.csproj will have ProjectRefrences to other projects in the repo, but if you open the solution in VS you won't see them, and only see your project instead.

**Comment by Epic-Santiago** [comment]
Thanks for all the good info @joperezr. I understood from the start that referencing a .NET Framework assembly from a .NET Standard project was not a go forward strategy. However, I was hoping that the fact that it worked (as long as I was still running on .NET Framework) would break a log jam in a very large conversion project and buy some time until that could be fully resolved. While it will still work, I don't want to show warnings across hundreds of projects as that will reduce confidence in the conversion effort. I will look for an alternative. Thanks.
