### ISSUE TITLE
BinaryFormatter encodes wrong type information, ignoring SerializationBinder.BindToName, on array of array

### ISSUE THREAD

**Issue by shonk-msft** [dotnet/runtime#34048]
**Expected**: When `BinaryFormatter` is given a `SerializationBinder`, the binder should be used for constructed types like `A[]` and `A[][]`.

**Observed**: See the attached code and output files. The binder maps type `A` to `B`, by using "special" assembly and type names.
- Serializing/deserializing an `A` works fine.
- Serializing/deserializing an `A[]` seems to work, but the original assembly name surprisingly appears in the stream.
- Serializing/deserializing an `A[][]` throws on deserialization. The original assembly name as well as the type `A[]` appear in the stream.

See attached code and output files.

[Program.cs.txt](https://github.com/dotnet/runtime/files/4378270/Program.cs.txt)

[output.txt](https://github.com/dotnet/runtime/files/4378273/output.txt)

**Comment by shonk-msft** [comment]
Note that when the loading process doesn't have access to the original type (`A` in this case) a different exception is thrown at deserialization time. In my particular case, the original type is a class generated by a `TypeBuilder` and the rogue assembly name can't be found by the deserializer, so a `SerializationException` is thrown.

**Comment by GrabYourPitchforks** [comment]
`BinaryFormatter` gives single-dimensional arrays special treatment, which is why you see `A[]` behave somewhat as expected. But other array types - such as jagged arrays (`A[][]`) or multi-dimensional arrays (`A[,]`) - aren't given special treatment and are considered their own independent types. That's probably why you're seeing inconsistent behavior in the `SerializationBinder`. Even though the `BindToName` function isn't called with the inputs you expect, the `BindToType` function should still be able to participate in the system. So by overriding `BindToType` (and perhaps ignoring the assembly name entirely?), you should still be able to return the correct `System.Type` that your system expects.
