### ISSUE TITLE
Introduce way to disable localization support

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#34057]
The localization support for dotnet/runtime comes with a noticeable cost for workloads which are size sensitive and would be fine with English only.

The primary costs come from 
- linker not being able to remove resource entries which are not needed
- ResourceManager implementation which is redundant for a single locale

There should be a way to switch to English mode only perhaps using some extra linker logic which converts .resources back to strings.

/cc @danmosemsft @vitek-karas @eerhardt

**Comment by danmosemsft** [comment]
ProjectN went further, I think, and replaced exception strings with ID'S (?). Not sure how desirable that is given often some are visible to users.

**Comment by vitek-karas** [comment]
We actually went somewhat back on that decision and the shared library (I think in .NET Native 2.0) included full exception messages as the UX was pretty bad with just the IDs. I think a better way would be to try to teach linker to trim resource strings if they're not used anywhere (if we can reliably detect that - which might be pretty hard).

**Comment by MichalStrehovsky** [comment]
Project N only went back because when we introduced replacing exception messages with resource strings, we didn't have an option to turn this off and _some_ developers wanted to turn it off.

It's a pretty significant saving and frankly if the app makes the exceptions user-facing, turning "Arg_DecBitCtor" into "Decimal constructor requires an array or span of four valid decimal bytes." doesn't help anyone but the developer. We shipped a CSV with the mapping. I think it would be a valuable option to expose. The CoreRT compiler can do it and saves 433 kB on Hello World when this is enabled (or at least it did when this option was introduced).

For the "let's replace resources with inline strings instead" approach, we might want to wait until there's internal support for UTF-8 string literals - resource strings are stored as UTF-8, but string literals are UTF-16, so we would be getting rid of resource manager, but doubling the string data itself - we can do better than that.

**Comment by marek-safar** [comment]
@danmosemsft I don't think there is an appetite for removing the string altogether, this might be interesting super optimization but I don't think it'd be used in wild.

Using string literals as the keys for location is probably the most elegant solution but I fear the model of using IDs for localization for decades is something I'll have a hard time to convince others to switch from.

**Comment by eerhardt** [comment]
Would this support only be for CoreLib/BCL or would it also apply to 3rd party libraries?

**Comment by marek-safar** [comment]
Ideally for everything but BCL + our core SDKs need to be in the first wave

**Comment by danmosemsft** [comment]
>  teach linker to trim resource strings if they're not used anywhere 

That has the considerable appeal of not affecting the user experience. So I do hope we can at least do that part. But as an aside, for my education, is corelib itself typically trimmable much? Or too central/heavily used/interconnected and most is retained?

**Comment by danmosemsft** [comment]
>  if the app makes the exceptions user-facing, turning "Arg_DecBitCtor" into "Decimal constructor requires an array or span of four valid decimal bytes." doesn't help anyone but the developer. 

Right, but there may be plenty of apps that anticipate the ones their users will see are reasonable like `Could not find file '{0}'.` .

**Comment by marek-safar** [comment]
>their users will see are reasonable like

For most apps the user-facing aspect of exception messages does not matter but the developers care a lot about actionable messages in their logs.

**Comment by MichalStrehovsky** [comment]
> Right, but there may be plenty of apps that anticipate the ones their users will see are reasonable like `Could not find file '{0}'. `.

This is similar to the globalization invariant mode - turning it on and then exposing the user to it will cause confusion, but we provide the option because it's worthwhile for certain scenarios.

> For most apps the user-facing aspect of exception messages does not matter but the developers care a lot about actionable messages in their logs.

Our resource key names are pretty descriptive. E.g. `The file 'foobar.baz' already exists.` and `IO_FileExists_Name, foobar.baz` would both have enough things to go off.

**Comment by danmosemsft** [comment]
@MattWhilden since you've done a lot of work supporting customers on Project N -- have you seen developers have trouble reverse engineering its "compressed exception strings" ?

**Comment by eerhardt** [comment]
> ResourceManager implementation which is redundant for a single locale

Note, if we don't disable localization support for all assemblies involved (even 3rd parties), as soon as the app references one library which uses resources for their exception messages (which is basically most production libraries), then ResourceManager will have to be included. Or if the app itself uses ResourceManager to localize its UI and messages, ResourceManager will have to be included.

How are Xamarin apps localized in .NET 5? Do we expect them to use ResourceManager at all?

**Comment by marek-safar** [comment]
The world is not black and white if someone decides to localize using ResourceManager then they take the dependency and that's fine. If someone is working on app or web assembly page which is English only the framework should not force the dependency and additional data to be pulled in.

There are also 3rd party solution for localization so don't assume localization == ResourceManager.

**Comment by eerhardt** [comment]
In a conversation with @ericstj and @tarekgh, we came up with the following:

1. There are 2 kinds of "trimming" in this area, which we should keep in mind:

    1. Trim by usage - cutting out individual resources that are not used
    2. Trim by locale - cutting out languages that aren't used

2. A holistic solution should consider `dotnet/runtime` libraries, as well as 3rd party libraries (ex. a referenced NuGet package), and the app itself. Just spending efforts on the `dotnet/runtime` libraries won't make as big of an impact as doing it for the runtime and large 3rd party libraries (ex. Azure SDK libraries).

3. This should be a "post-compile" step (i.e. done by the linker). A solution that involves the library to be compiled specifically for "disabled localization support" would cause the runtime's build to be "forked". It would also affect all 3rd party libraries and force them to put a separately built asset into their NuGet package.

### High-level options

1. Use the `resource key` instead of full strings
    - This is the model UWP took for the runtime libraries.
    - It results in the smallest assemblies possible since there is no need for the `ResourceManager` code, and the resource strings themselves are not in the app.
    - In order to make it possible for 3rd party libraries, it could involve a lot of work in the linker, or possibly a code gen change in the `.resx` code generator.
    - There were complaints from UWP users that they didn't get decent messages in diagnostic tracing.

2. Take the full strings out of `.resources` and inline them into the IL code directly.
    - This is the model mono has taken.
    - Removes the dependency on `ResourceManager`
    - In order to make it possible for 3rd party libraries, it could involve a lot of work in the linker, or possibly a code gen change in the `.resx` code generator.
    - The strings are larger in IL because they are UTF-16 encoded, instead of UTF-8 encoded in the `.resources` file. (Although we could consider generating the strings as `byte[]` in code, and calling `UTF8.GetString`.)
    - We would need to ensure the strings only appear once in the IL and are interned at runtime, so there aren't separate copies.

3. Trim the resources in the resource stream
    - We could teach the linker to trim out any resource that doesn't appear to be used.
    - This could easily be adaptable to 3rd party libraries as well.
    - This doesn't remove the `ResourceManager` code. But we could consider a mode where `ResourceManager` only retrieves string resources, and isn't able to load up "extension" resource types, like it does for WinForms applications. This would make the `ResourceManager` code smaller.

### Recommended next steps

We need to get a canonical Xamarin or Blazor application working on top of the `dotnet/runtime` libraries and do some measurements of the above approaches. Approach (1) is already in place for the libraries, ([SR.UsingResourceKeys()](https://github.com/dotnet/runtime/blob/c27376e46ccec555b00eb45cefaa1b3712b44a99/src/libraries/Common/src/System/SR.cs#L13-L20) exists from our usage in UWP. We could tell the linker to turn that to `true`). Approach (3) seems the most reasonable if we are also trimming 3rd party libraries, and not just the `dotnet/runtime` libraries. If we are only trimming the `dotnet/runtime` libraries, Approach (3) might not make much of a difference.

**Comment by MattWhilden** [comment]
@danmosemsft Most of the pain along this path (string stripping) revolved around method name stripping causing exception stack frames be indecipherable. I don't recall a huge outcry from non-loc'd exception messages but it's possible it was drowned out by only-offest-stacks taking up most of the attention.

(reply delayed due to paternity leave)

**Comment by vargaz** [comment]
Some data from mono's corlib:
- The resources file is 150k.
- The resource manager code appears to be around 50k IL.
- The SR version used by corlib which is at src/libraries/System.Private.CoreLib/src/System/SR.cs,
  doesn't use UsingResourceKeys for GetResourceString (), only for the Format () methods.

**Comment by MichalStrehovsky** [comment]
> The SR version used by corlib which is at src/libraries/System.Private.CoreLib/src/System/SR.cs,
doesn't use UsingResourceKeys for GetResourceString (), only for the Format () methods.

Seems like we were missing a .NET Native change (`UsingResourceKeys` was only really used in .NET Native). Pull request #35830 brings it over.

**Comment by vargaz** [comment]
The IL trimmer seems to optimize away calls to UsingResourceKeys so it's not possible to set its value later during product linking.

**Comment by eerhardt** [comment]
> The IL trimmer seems to optimize away calls to UsingResourceKeys so it's not possible to set its value later during product linking.

See discussion on: https://github.com/mono/linker/issues/1112. Either the linker will have to change to respect this pattern, or we will need to adjust this code for the linker.

**Comment by MichalStrehovsky** [comment]
> See discussion on: mono/linker#1112. Either the linker will have to change to respect this pattern, or we will need to adjust this code for the linker.

I think the linker really just needs to respect the `NoInlining` bit. I have not seen a compiler/tool before that would interpret `NoInlining` like linker is doing here (while maybe it's being "technically correct" because it didn't inline the method, but it still made decisions at the callsite that inlined the result of the method into the callee).

**Comment by joperezr** [comment]
Closing this as it has been fixed now via #38397. Do note that I still plan on working on https://github.com/dotnet/runtime/issues/38036 which will contribute to improve the experience when UsingSystemResourceKeys feature flag is set.
