### ISSUE TITLE
CoreCLR tests on Mono runtime : System.MissingMethodException: Method not found: void System.Int32[*]..ctor(int,int) Due to: Failed to load due to unknown reasons

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#34068]
When running the following CoreCLR tests on the Mono runtime from the dotnet\runtime repo, we get the error "System.MissingMethodException: Method not found: void System.* ..ctor(int,int) Due to: Failed to load due to unknown reasons failures"

Example error :  Unhandled Exception:
          System.MissingMethodException: Method not found: void System.Int32[*]..ctor(int,int) Due to: Failed to load due to unknown reasons
          [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method not found: void System.Int32[*]..ctor(int,int) Due to: Failed to load due to unknown reasons

1.	JIT/Methodical/Arrays/misc/_il_dbgaddress/_il_dbgaddress.sh
2.	JIT/Methodical/Arrays/range/_il_relint32_range2/_il_relint32_range2.sh
3.	JIT/Methodical/Arrays/range/_il_dbgfloat64_range2/_il_dbgfloat64_range2.sh
4.	JIT/Methodical/Arrays/range/_il_dbgfloat64_range1/_il_dbgfloat64_range1.sh
5.	JIT/Methodical/Arrays/misc/_il_reladdress/_il_reladdress.sh
6.	JIT/Methodical/Arrays/range/_il_dbgint32_range1/_il_dbgint32_range1.sh
7.	JIT/Methodical/Arrays/range/_il_dbgint32_0_5b/_il_dbgint32_0_5b.sh
8.	JIT/Methodical/Arrays/range/_il_relint32_0_5a/_il_relint32_0_5a.sh
9.	JIT/Methodical/Arrays/range/_il_dbgint32_1/_il_dbgint32_1.sh
10.	JIT/Methodical/Arrays/range/_il_dbgint32_m1/_il_dbgint32_m1.sh
11.	JIT/Methodical/tailcall/_il_dbgdeep_array_nz/_il_dbgdeep_array_nz.sh
12.	JIT/Methodical/Arrays/range/_il_relint32_neg_range/_il_relint32_neg_range.sh
13.	JIT/Methodical/Arrays/range/_il_dbgint32_neg_range/_il_dbgint32_neg_range.sh
14.	JIT/Methodical/Arrays/range/_il_relint32_m1/_il_relint32_m1.sh
15.	JIT/Methodical/Arrays/misc/_il_relgcarr/_il_relgcarr.sh
16.	JIT/Methodical/Arrays/range/_il_relint32_0_5b/_il_relint32_0_5b.sh
17.	JIT/Methodical/tailcall/_il_reldeep_array_nz/_il_reldeep_array_nz.sh
18.	JIT/Methodical/Arrays/range/_il_relfloat64_range1/_il_relfloat64_range1.sh
19.	JIT/Methodical/Arrays/misc/_il_relinitializearray/_il_relinitializearray.sh
20.	JIT/Methodical/Arrays/range/_il_relfloat64_range2/_il_relfloat64_range2.sh
21.	JIT/Methodical/Arrays/range/_il_dbgint32_range2/_il_dbgint32_range2.sh
22.	JIT/Methodical/Arrays/range/_il_relint32_1/_il_relint32_1.sh
23.	JIT/Methodical/Invoke/25params/25paramMixed_il_r/25paramMixed_il_r.sh
24.	JIT/Methodical/Arrays/range/_il_dbgint32_0_5a/_il_dbgint32_0_5a.sh
25.	JIT/Methodical/Arrays/range/_il_relint32_range1/_il_relint32_range1.sh

Repro steps : After building the coreclr tests (cd src/coreclr && ./build-test.sh -c FlavorYouWantToRun(Debug or Ship)
Example command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command - **make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/Arrays/misc/_il_dbgaddress/_il_dbgaddress.sh"**

**Comment by SamMonoRT** [comment]
@vargaz @thaystg @lambdageek fyi

**Comment by SamMonoRT** [comment]
@lateralusX fyi too

**Comment by SamMonoRT** [comment]
@lateralusX - sending this your way. Try to get to it soon as this is affecting a lot of tests. @marek-safar fyi

**Comment by lateralusX** [comment]
Took a brief look, this is new territory for me, but it looks like the constructor used in this specific IL is not setup when setting methods for array in mono_class_setup_methods. I will take a look at adding a ctor method with the a signature (int32, int32) and then look through the rest of code will handle case an instance array in the expected way. This is not a netcore only issue, I can repro on regular Mono BCL as well (but we don't have IL triggering this scenario), so fix should probably target both configurations.

**Comment by lateralusX** [comment]
Will work on a fix tomorrow.

**Comment by SamMonoRT** [comment]
Thank you, I grouped the following failures under this issue, hopefully same underlying issue. 
Method not found: void System.Int32[*]..ctor(int,int) 
Method not found: void System.Double[*]..ctor(int,int)
Method not found: void GCTest.Test[*]..ctor(int,int)
Method not found: void System.Int16[*]..ctor(int,int)

**Comment by lateralusX** [comment]
Looking at ECMA spec it says:

The class that the VES creates for arrays contains several methods whose implementation is supplied
by the VES:

- A constructor that takes a sequence of int32 arguments, one for each dimension of the array, that specify the number of elements in each dimension beginning with the first dimension. A lower bound of zero is assumed.
- A constructor that takes twice as many int32 arguments as there are dimensions of the array. These arguments occur in pairs—one pair per dimension—with the first argument of each pair specifying the lower bound for that dimension, and the second argument specifying the total number of elements in that dimension. Note that vectors are not created with this constructor, since a zero lower bound is assumed for vectors.

Looking at our current implementation we only create twice number of arguments for rank > 1 and hijacks the rank == 1 constructor with two int's for jagged arrays and looking at the code, I believe that constructor won't really be used, since when creating array instance there is an optimised path that will assume number of constructor arguments is same as number of ranks, so current implementation doesn't handle the case where you have a lower bound that is not 0, since it will incorrectly route the constructor with twice the number of arguments through code interpreting it as number of ranks.

I will look at fix that needs to:

* Always add constructors for rank and rank *2 number of int32 args, removing special case for jagged arrays.
* Fix optimisation to correctly handle case where number of ctor aguments is not twice the amount compared to rank, since that indicates lbound, size.
* Jagged arrays? Question is if they have been instanced through this code path, because it would have been instanced as a array with rank 2 using 0 as lbound. We could preserve this behaviour, or add assert if this case ever gets into MONO_CEE_NEWOBJ trying to create a jagged array, since result would not been what's expected.  Compiling a jagged array using csc will also use newarray IL instruction and our runtime invoke also handle jagged arrays differently, but relying on using a constructor taking two int32, but route that through internal methods called to create a jagged array.

**Comment by lateralusX** [comment]
https://github.com/mono/mono/pull/19494.

**Comment by lateralusX** [comment]
https://github.com/dotnet/runtime/pull/35008 passed with tests failing in this issue enabled on Mono runtime.
