### ISSUE TITLE
Task.WaitAll missing IEnumerable<Task> overload

### ISSUE THREAD

**Issue by shravan2x** [dotnet/runtime#34106]
In general, `Task.WhenAll` is used to wait for a collection for tasks to complete execution. However, `Task.WaitAll` still has valid niche use-cases. For example, in a synchronous method that blocks shutdown until it completes - `appLifetime.ApplicationStopping.Register(() => _shutdownTokenSource.Cancel())`.

`Task.WaitAll` seems to be missing an overload that takes an `IEnumerable<Task>`. This overload exists for `Task.WhenAll`. Can we add this?

**Comment by NinoFloris** [comment]
Could easily call `.Wait()` on the returned task from WhenAll no?

**Comment by shravan2x** [comment]
@NinoFloris In general, working with tasks tend to have some tricky cases which cause deadlocks when using `Wait`/`WaitAll`. I wasn't sure if `WhenAll(...).Wait()` and `WaitAll(...)` were _always_ equivalent. My workarounds were `Task.WhenAll(allTasks).Wait()` like you suggested and `Task.WaitAll(allTasks.ToArray())` - I went with the latter since it seemed a safer bet.

But I agree that this is a _nice-to-have_ rather than a _priority_.

**Comment by bartonjs** [comment]
We expanded the original proposal by
* Adding a defaulted CancellationToken
* Also including WhenAny


```C#
namespace System.Threading.Tasks
{
    public partial class Task
    {
        public static void WaitAll(IEnumerable<Task> tasks, CancellationToken cancellationToken = default);
        public static int WaitAny(IEnumerable<Task> tasks, CancellationToken cancellationToken = default);
    }
}
```

**Comment by campersau** [comment]
Does it make sense that `WaitAny` returns an `int`?
How would you get the actual task if also the caller only has an `IEnumerable` without iterating it again?
Should it return the `Task` directly like `WhenAny`?

**Comment by amiru3f** [comment]
Hello gents,
I'm keen to know if I can pick this up for implementation? 
@stephentoub @shravan2x

**Comment by stephentoub** [comment]
@amiru3f, sure, thanks, go for it.

**Comment by stephentoub** [comment]
> Also including WhenAny

In looking at this now to implement it, I don't think this is good to add. The return int value indicates which task completed, but with an enumerable, it's possible the tasks are lazily produced (e.g. `WaitAny(Enumerable.Range(...).Select(_ => Task.Run(...)))`), in which case the number doesn't actually give you access to the completed task, and you can't just enumerate the source sequence to get it, as that would produce an entirely new task.  This is one of the reasons WhenAny returns the Task rather than a number.

I'm just sticking with the originally requested WaitAll.
