### ISSUE TITLE
CollectionExtensions: Duplicate type in System.Collections and M.E.DependencyModel

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#34420]
The type `System.Collections.Generic.CollectionExtensions` is defined in multiple seed assemblies.
The multiple assemblies are Microsoft.Extensions.DependencyModel.dll, System.Collections.dll.

This is a pre-existing issue that was discovered moving Microsoft.Extensions.DependencyModel into `src\libraries`, see #34296. We've suppressed the duplicate error for now.

To fix this, I recommend we rename the `CollectionExtensions` in `Microsoft.Extensions.DependencyModel`, which would be a breaking change.

**Comment by ViktorHofer** [comment]
@eerhardt should we do anything about this? We still exclude the DependencyModel assembly when generating shims. cc @ericstj

**Comment by eerhardt** [comment]
Honestly I'm not sure what we can do about this other than make a breaking change in `Microsoft.Extensions.DependencyModel`.

If we were going to make this breaking change, we could also delete this mistake as well:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/Microsoft.Extensions.DependencyModel/src/HashCodeCombiner.cs#L11-L13

So if we think this library would be acceptable to make a breaking change in, we should do it. If not, then we should probably close out this issue.

**Comment by ericstj** [comment]
I don't think a breaking change to make our tools happy is the right tradeoff.  

Obsoletion isn't a great option either, since I don't think the compiler considers that when examining betterness for extension methods.  So if we put an obsolete attribute on the type and created a new type, nothing would tell the compiler the new type was better.  We'd have to break the old type.

Given we haven't gotten any customer feedback on this, I'd reccomend we just live with it.

**Comment by eerhardt** [comment]
> I'd reccomend we just live with it.

I'm fine with that as well. Closing.
