### ISSUE TITLE
System.Speech.Synthesis.SpeechSynthesizer depends on RegistryKey.hkey

### ISSUE THREAD

**Issue by lukeb1961** [dotnet/runtime#34441]
Powershell - speech is broken.
https://github.com/PowerShell/PowerShell/issues/12236

System.Speech uses reflection to access the non-public field RegistryKey.hkey which was renamed in core to _hkey. Maybe worth opening an issue on dotnet/runtime to inform them that there's a Microsoft assembly depending on that field name.

**Comment by jkotas** [comment]
`System.Speech.Synthesis` is part of .NET Framework. It is not supported on .NET Core.

**Comment by duaneking** [comment]
It should be, if MSFT is true to its stated values of inclusiveness.

This System.Speech namespace is VITAL to the visually disabled community, as vital as System.Console is for everybody else. Not having this has been a HUGE DEAL.

By not supporting System.Speech, You are effectively denying anybody with a visual disability the ability to use anything .net core unless they make other arrangements, that are often just not avaialble.

I sincerely PLEAD with MSFT and the teams involved to support this, as there are many people who REALLY NEED THIS, especially since MS abandoned the Agent SDK and has yet to give the community an alternative that works.

**Comment by jkotas** [comment]
Let's continue the discussion about System.Speech support in #34963

**Comment by danmoseley** [comment]
Note this is now ported and released
https://github.com/dotnet/runtime/issues/46730

**Comment by danmoseley** [comment]
https://www.nuget.org/packages/System.Speech
