### ISSUE TITLE
.NET Core 3.1 Self-contained fails with `System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0`

### ISSUE THREAD

**Issue by nietras** [dotnet/runtime#34494]
I have a simple .NET Core 3.1 Windows Desktop Windows Forms application that references a couple of C++/CLI assemblies. Running this from "normal" publish e.g.:
```
Release\netcoreapp3.1\win-x64
```
works fine, but when publishing as self-contained it fails during startup e.g. running `exe` from:
```
Release\netcoreapp3.1\win-x64\publish
```
fails with the exception as seen in EventViewer is:
```
CoreCLR Version: 4.700.20.6602
.NET Core Version: 3.1.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at FOO.MainForm.InitializeComponent()
   at FOO.MainForm..ctor()
   at FOO.Program.Main()
```
Since this works fine when it is not self-contained I am not sure what is going on here?

UPDATE: Seems like the error was my mistake because I did not publish a **self-contained** single-file but only a single-file.

**Comment by nietras** [comment]
@Dotnet-GitSync-Bot area-Single-File @swaroop-sridhar

**Comment by danmosemsft** [comment]
@nietras was this actually single file ? you only mention self contained.

**Comment by nietras** [comment]
@danmosemsft sorry I guess self contained *and* single file. If I understand the difference :) Copying all files (a lot) to a machine without dotnet core installed works. Copying single file does not.

**Comment by vitek-karas** [comment]
@nietras - how are you building the single-file?

Just to make sure the terminology is consistent:
* Self-contained - app which doesn't require pre-installed .NET Core on the machine
* Single-file - app which is all packaged into one file, the executable
* Self-contained & Single-file - app which is a single executable and doesn't require .NET Core. The executable is typically pretty large (50MB or even more).

The content of `Release\netcoreapp3.1\win-x64` is not a result of publish. Any publish (single-file or not) will be (by default, unless you specify differently) in a `publish` folder.

**Comment by nietras** [comment]
@vitek-karas thanks yes, I'm finally getting the terminology :+1: Should have included my build commands. So first **self-contained** publish only:
```
dotnet publish -r win-x64 -c release --self-contained 
```
This outputs a directory as shown below, and **works**.
![image](https://user-images.githubusercontent.com/10798831/78378355-20f89c80-75d1-11ea-993f-0a07f64fd556.png)

Next up **self-contained and **single-file**:
```
 dotnet publish -r win-x64 -c release /p:PublishSingleFile=true  --self-contained
```
Which gives a single large file as expected. And .... wait a minute ... **works!**. Sorry I must have made a mistake, it works now it seems. Perhaps, I copied a single file that was not `--self-contained` but just single file. That would explain it I guess. My bad! :)

![image](https://user-images.githubusercontent.com/10798831/78378570-72089080-75d1-11ea-86bf-d87299d92f51.png)

I do have some questions though, if you don't mind. 

As far as I understand, **single-file** is based on extracting files to some place, upon first start? Where is that? This also means if the project is quite big it takes a long time before anything happens since files need to be extracted first... is this something one can customize?

We have quite a lot of native dependencies `dll` that we copy to a sub-directory e.g. `x64` will this work with that? We then use `SetDllDirectory` to ensure this directory is part of the path.

**Comment by nietras** [comment]
@vitek-karas follow up question since I found where this is unpacked at:
```
C:\Users\<USERNAME>\AppData\Local\Temp\.net\<APPNAME>\hgpwgycu.qcv
```
and you can have quite a lot of folders there. How is this cleaned up? Our projects has resources worth several GBs hence the questions :)

**Comment by swaroop-sridhar** [comment]
> As far as I understand, single-file is based on extracting files to some place, upon first start? 

Yes, this is the mechanism of single-file apps in .net core 3.

> Where is that? 

`%TEMP%\.net\<APPNAME>\<ID>`

> This also means if the project is quite big it takes a long time before anything happens since files need to be extracted first... 

You can try ILLinking the app to reduce the managed code size. Publish your app with /p:PublishTrimmed=true. However, if the size of the app is due to non-IL payload, then this approach will not be very useful. 

The extracted files will be reused on subsequent runs, so the app will not have a startup overhead every time.

The need for extracting files will be reduced (possibly eliminated based on the app contents and settings) in .net 5. Further details are [in this document](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md).

We have quite a lot of native dependencies dll that we copy to a sub-directory e.g. x64 will this work with that? We then use SetDllDirectory to ensure this directory is part of the path.

> is this something one can customize?

You can choose what files are bundled into the app, and what files are left beside the app. 
Please see the `ExcludeFromSingleFile` setting [in this page](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md#build-system-interface).

and you can have quite a lot of folders there. How is this cleaned up? Our projects has resources worth several GBs hence the questions :)

Clean up is through manual deletion or cleanup of the temp directory by the OS, as noted [here](
https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/extract.md#cleanup).
