### ISSUE TITLE
Question: Escaping of pinned reference

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#34501]
It's unclear for me the actual behavior of GC when I'm trying to return a managed pointer to the portion of pinned object. For instance:
```csharp
static unsafe ref readonly char GetRawData(this string str)
{
  fixed (char* ptr = str)
    return ref ptr[0];
}
```
Roslyn compiler creates two temporary variables:
1. Of type `char*`
1. Of type `string` which is pinned

After that, it just obtains pointer to the first character with help of `OffsetToStringData` and returns it. This is the most unclear place for me. Is GC and JIT knows that `char*` is actually a managed pointer according with method's return type and "unpin" the string properly. Or I can, in theory, obtain dangling pointer because JIT "unpins" string and after that converts `char*` to the managed pointer. Between these two points GC may decide to move the string.

**Comment by jeffschwMSFT** [comment]
@cshung

**Comment by jkotas** [comment]
> Is GC and JIT knows that char* is actually a managed pointer

GC and JIT does not know that. `char*` is similar to `int` or `long` as far as GC/JIT are concerned.

The JIT needs to see an assignment from into `ref` variable to start the GC tracking. The GC interactions with conversions from pointer back to byref do not seem to handled by Roslyn precisely and sometimes optimized out. For example:

```
static char dummy;

static unsafe ref readonly char GetRawData(string str)
{
  ref char ret = ref dummy;
  fixed (char* ptr = str)
  {
     ret = ref ptr[0];
  }
  return ref ret;
}
```

will generate this IL:

```
  .locals init (char* V_0,
           string pinned V_1)
  IL_0000:  ldsfld     char My::dummy
  IL_0005:  pop
  IL_0006:  ldarg.0
  IL_0007:  stloc.1
  IL_0008:  ldloc.1
  IL_0009:  conv.u
  IL_000a:  stloc.0
  IL_000b:  ldloc.0
  IL_000c:  brfalse.s  IL_0016
  IL_000e:  ldloc.0
  IL_000f:  call       int32 [mscorlib]System.Runtime.CompilerServices.RuntimeHelpers::get_OffsetToStringData()
  IL_0014:  add
  IL_0015:  stloc.0
  IL_0016:  ldloc.0
  IL_0017:  ldnull <- the pinning ends here, but the GC tracking for the return value have not started yet!
  IL_0018:  stloc.1
  IL_0019:  ret
```

@VSadov Is it a bug or by design that Roslyn is optimizing out the `ref` assignment in this example? 

BTW: [string.GetPinnableReference](https://docs.microsoft.com/en-us/dotnet/api/system.string.getpinnablereference?view=netcore-3.1) is trying to exactly what you are trying to do above. 

In any case, it is best to avoid these rountrips between GC tracked and GC untracked pointers. They tend to cause very subtle bugs.

**Comment by sakno** [comment]
Unfortunately, `GetPinnableReference` is not available in .NET Standard 2.1. However, many thanks for explanation. For me, it was unclear how JIT defines the end of the pinning.

**Comment by VSadov** [comment]
Technically  `ret = ref ptr[0];` creates an alias to a location specified by an expression. No other sideeffects are assumed.
Once an alias is obtained via unsafe code, it is hard for the language to guarantee much. It is up to the user to make sure the location is valid as long as there is an alias.

The following is a simpler example that is just as bad.
```cs
    static unsafe ref readonly char GetRawData(char ch)
    {
      char* pch = &ch;
      ref char ret = ref *pch;
      return ref ret;
    }
```

I do not think the loss of tracking in the original example is intentional though. It could work more intuitively.

It could be a bit tricky to fix since every individual part works as intended and byref expressions do not keep track if they are possibly aliasing a dereferenced pointer.

Tracking such information would need to consider reassignments, nesting, conditionals, etc.

```cs
        static char dummy = 'W';
        static bool b = true;

        static unsafe ref char GetRawData(string str)
        {
            ref char ret = ref dummy;
            fixed (char* ptr = str)
            {
                // nesting and conditionally managed/unmanaged
                ref var tmp = ref b ? ref ptr[0] : ref dummy;

                // reassignments
                ref var tmp1 = ref tmp;
                ref var tmp2 = ref tmp1;

                ret = ref tmp2;
            }
            return ref ret;
        }
```

Perhaps force spilling of byref locals whose def-use crosses out of a fixed block, would be the most noninvasive "fix".
