### ISSUE TITLE
Prefer string.Equals over string.Compare(string, string) == 0 or != 0

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#34514]
As a carryover from native code habits, I see folks use `string.Compare(a, b) == 0` or `!= 0` a *lot* where `string.Equals(a, b)` is more semantically meaningful.

But *more importantly*, Compare is for *sorting* strings whereas Equals is for determining equality. In particular cultures two strings may have *sort* equivalence without being *equal*. So in some cases it may even make a security difference (when StringComparison isn't specified). 

**Category**: Performance

**Comment by AArnott** [comment]
@terrajobst to consider for inclusion in the Roslyn Analyzers project.

**Comment by danmosemsft** [comment]
cc @GrabYourPitchforks who I think has commented on this before.

**Comment by GrabYourPitchforks** [comment]
`string.Equals(...)` and `string.Compare(...) == 0` are semantically equivalent _as long as the same `StringComparison` is used_.

The thing that messes people up is that if you don't specify an explicit comparison, `string.Equals` defaults to `Ordinal`, while `string.Compare` defaults to `CurrentCulture`.

IMO this particular issue should be performance rather than correctness. Let existing issue https://github.com/dotnet/roslyn-analyzers/issues/2581#issuecomment-584438937 be the "correctness / security" issue.

**Comment by GrabYourPitchforks** [comment]
Shouldn't we keep this issue open? There is some benefit to having devs prefer `string.Equals(...)` over the equivalent `string.Compare(...) == 0` (or `!= 0`).

**Comment by AArnott** [comment]
Oh, I misunderstood. I thought you were suggesting we close it in favor of the other issue. But now I see that you simply suggested I revise the category.

**Comment by EgorBo** [comment]
There are a few hits in dotnet/runtime itself:

![image](https://user-images.githubusercontent.com/523221/220393984-b5d6c4d0-556c-4005-bb69-ceacf0354c65.png)

cc @stephentoub

**Comment by stephentoub** [comment]
We have https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2251.  This issue should have been closed with that.

Regarding "There are a few hits in dotnet/runtime itself", those are all for `string.CompareOrdinal` rather than `string.Compare`.  We should open an issue in dotnet/roslyn-analyzers to update CA2251 to also look for that method, at least the two-argument one... string.Equals doesn't provide an equivalent overload for the five-argument one.
