### ISSUE TITLE
IEnumerator Linq Select

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#34575]
```C#
public static IEnumerable<TResult> Select<T,TResult>(this T source,Func<T,TResult> func) where T : IEnumerator
{
    while(source.MoveNext())
       yield return func(source);
}

////

// (object,object)[]
var keyValues = obj is IDictionary dict ? obj.GetEnumerator().Select((iter) => (iter.Key,iter.Value)).ToArray() : null;
```

As you can see, sometimes we still utilize a non generic version of collection, and it also better use `IEnumerator` in some cases, such as `IDictionary` that could give `Key` `Value` and `Entry` from its enumerator

So I would like to propose the above function to `System.Linq.Enumerable` class. So we could utilize the non generic collection with generic `Linq` easily

**Comment by Gnbrkm41** [comment]
Why not `.Cast<T>` then `.Select`? It seems weird to only special-case Select for this.

**Comment by Thaina** [comment]
@Gnbrkm41 It not always guarantee that the thing that was implemented `IDictionary` will implement `IEnumerator` to return `DictionaryEntry`

Such as `Dictionary<K,V>` which implement `IDictionary` but its `IEnumerator.GetEnumerator()` it internally return `KeyValuePair<K,V>`

**Comment by eiriktsarpalis** [comment]
The general assumption around `IEnumerable` types is that they can enumerated many times. Wrapping an IEnumerator with an IEnumerable specifically violates that invariant. While it is sometimes necessary to play tricks like that in certain internal implementations, I don't think we should include this in System.Linq, since it might be misused.

I am going to close this issue for now. /cc @adamsitnik
