### ISSUE TITLE
Consider removing `_version++` from overwrites in `Dictionary<TKey, TValue>`

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#34606]
We previously removed the `_version++` when Remove'ing from a dictionary.  We should consider doing so as well when just overwriting a value for an existing key in the dictionary.  This would enable update loops that tweak a value in the dictionary without needing to resort to convoluted and more expensive measures.

**Comment by Wraith2** [comment]
What is the benefit of doing this? It quietly removes a concurrency correctness safeguard for casual users and replaces it with them needing to make complex decisions about concurrency and immutability that most people aren't equipped to deal with.

**Comment by stephentoub** [comment]
> It quietly removes a concurrency correctness safeguard

It's not about concurrency; Dictionary is not thread-safe for concurrent reads and writes, and the existing version checks don't help with that.  The checks are there purely for enumeration and to prevent cases where the mutation being performed as part of an enumeration (sequentially) will cause the enumeration to silently repeat data, see corrupted data, etc., and the version check in an overwrite doesn't help with any of that.  It's the same reason the version checks were removed from Remove; they didn't provide any meaningful benefit, and only served to make things developers wanted to do more expensive.

> What is the benefit of doing this?

As called out in the original post, fine patterns that are currently throwing today will start working correctly, e.g.
```C#
foreach (KeyValuePair<string, int> pair in dict)
    dict[pair.Key] = pair.Value + 1;
```

**Comment by Wraith2** [comment]
By concurrency I meant interleaving of enumeration and modification operations. Those could be on other threads but aren't required to which is why I didn't mention thread safety. 

The previous removal enabled a common pattern of cache clearing enumeration and in general was unlikely to lead to problems because the removal left interleaved operations in the state where if one operation had a reference the other wouldn't be able to find it again so there's no confusion between two different values possible. That isn't the case here. It's possible for the body of an enumerating loop to overwrite the value while something else holds the original. 

Now you'll probably say that that's for the programmer to consider and guard against and you'll be right, but doing so requires that all callers be aware of this change in behaviour. Consider the existing behaviour and people who will have written code to catch the exception while enumerating, they will now have code that still compiles and works but would continue where they expect it to fail which could lead to bugs. They shouldn't use the exception or the dictionary in that way but there's a high likelihood that the pattern is present in all sorts of software because it's the easiest "fix". 

I don't object in principle to unversioning specific operations or possibly even dictionary as a whole but the possibly impact of the change is large because it's on Dictionary which has wide use over a long time. I think it will cause support problems. At the very least it could do with a big splashy warning somewhere (docs, release notes?) that dictionary behaviour has changed so support and debugging people can find and point to the reason things are broken in their ported or naïvely apps.

**Comment by stephentoub** [comment]
> It's possible for the body of an enumerating loop to overwrite the value while something else holds the original.

This is not different from the removal case. It's trivial to come up with examples where code could be making assumptions about both.

> who will have written code to catch the exception while enumerating

We do not consider turning exceptional situations into non-exceptional situations to be breaking. We frequently do that, making things work that previously threw. Could it change someone's behavior? Sure. We accept that in the name of forward progress.

> warning somewhere (docs, release notes?)

That's fine. No one has said otherwise.
