### ISSUE TITLE
Remove or neuter Microsoft.DotNet.PlatformAbstractions

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#3470]
As agreed more broadly (with @dleeapho et al) we are committed to remove (in some sense) Microsoft.DotNet.PlatformAbstractions from core-setup in 3.0. 

After https://github.com/dotnet/corefx/issues/31002 is completed, all its functionality will have equivalents in CoreFX proper - albeit in different shapes.

(Note that Microsoft.DotNet.DependencyModel is not included here - it must run on older runtimes, so it remains in core-setup.)

Options for M.DN.PA:

1. Remove it, and document alternative functionality. Because the existing package remains on NuGet, we avoid breaking existing code. (However it is possible it becomes out of date, eg., if we change how we determine the RID)
1. Retain it as is, but replace its implementation by calls into the CoreFX functionality, if semantically possible. 
1. As above, but also move into CoreFX.

@eerhardt @dseefeld is the above correct? thoughts?

**Comment by ViktorHofer** [comment]
I assume in cases where we build on .NET Framework, we still need to reference the PlatformAbstractions package to retrieve the RID? As an example, we need to retrieve the RID during the runtime build which can either run on Desktop or portable MSBuild.

**Comment by eerhardt** [comment]
For projects outside of the .NET product, they can continue using the older versions of PlatformAbstractions, if necessary.

However, projects inside of the .NET product should move off of PlatformAbstractions completely. Because once we stop building a new version of PlatformAbstractions, it won't be available in source-build.

For the runtime repo, when building on .NET Framework, I would either:

1. Check `#if NETFRAMEWORK` and `return $"win-{RuntimeInformation.OSArchitecture.ToString().ToLowerInvariant()}"`.
1. At the beginning of the build, Exec out to a `dotnet.exe` process which writes the RID to a .props file

> or portable MSBuild.

I don't know what this means. MSBuild is either running on .NET Framework or on .NET Core. If your task assembly is targeting `netstandard`, you can change it to target `netcoreapp5.0` instead. That `netstandard` build is only going to work on .NET Core anyway, because you won't have the correct facades to run on .NET Framework with a netstandard library. (That's why all task assemblies that need to run on both, build for both.)

**Comment by ViktorHofer** [comment]
> I don't know what this means.

"Portable msbuild" is just another name for msbuild targeting .NET Core.

**Comment by ViktorHofer** [comment]
Any suggestions for replacing `RuntimeEnvironment.OperatingSystemVersion`: https://github.com/dotnet/runtime/blob/7cbf0a7011813cb84c6c858ef19acb770daa777e/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Unix.cs#L38?

**Comment by eerhardt** [comment]
> Any suggestions for replacing `RuntimeEnvironment.OperatingSystemVersion`:

There are a couple ways of handling this. For the specific case you linked above, my opinion is that we should fix https://github.com/dotnet/runtime/issues/34977. Then this code can just use `Environment.OSVersion.Version`. IMO that is what customers actually want when they call this API.

The other place that `RuntimeEnvironment` is used in that file is just for Linux:

https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Unix.cs#L207-L211

Since this method is only ever called on Linux, we could do 1 of the following approaches:

1. Read `/etc/os-release` in this code and parse out the OSName and OSVersion.
2. Parse the `RuntimeInformation.RuntimeIdentifier` into OSName and OSVersion.
