### ISSUE TITLE
LLVM product build failing on retry

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#34770]
Rerun caused failure in mono LLVM leg due to duplicate artifact publish:
```
##[error]Artifact BuildLogs_Mono_LLVM_Linux_x64_debug already exists for build 594294.
```
I believe that's a bug in the yml. @directhex 

Similar bug here: https://github.com/dotnet/runtime/pull/33446#issuecomment-598833492

PR: https://github.com/dotnet/runtime/pull/34738
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=594294

**Comment by safern** [comment]
The build didn't fail per se. That step just warns as it is just publishing the logs. I think the right fix here is that for all UploadPipelineArtifacts task, we append the attempt number to the artifact name. We can get that using `System.JobAttempt` predefined variable in azure devops.

**Comment by directhex** [comment]
I don't see how this is similar to #33446 - the artifact name is duplicated because it _is_ duplicated. We upload logs on success _or_ failure, so we _did_ upload the logs in the failing first attempt - https://dev.azure.com/dnceng/public/_build/results?buildId=594294&view=logs&j=a9d8e986-d894-500e-79d4-4a88b1039057&s=d654deb9-056d-50a2-1717-90c08683d50a&t=6cfa02a4-b4fa-5b23-5734-5ed4f287fa17&l=1

There's nothing LLVM specific here, it just so happens that an infra failure job killed the LLVM run on the prior attempt. The same log upload logic is used in CoreCLR too.

**Comment by ericstj** [comment]
Yep, I think you're right.  Given this is just a non-failing warning on retry I'm going to close this.  Sorry for the noise.
