### ISSUE TITLE
Change Activity.DefaultIdFormat to W3C

### ISSUE THREAD

**Issue by shirhatti** [dotnet/runtime#34787]
In 5.0, we should change the Default value for `Activity.DefaultIdFormat` to `ActivityIdFormat.W3C`.

cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
Thank you for filing it!

**Comment by shirhatti** [comment]
@tarekgh Can we get this work scheduled?

cc @davidfowl @noahfalk

**Comment by tarekgh** [comment]
@shirhatti @noahfalk this looks a breaking change. did we decide we are going to do it? is it an acceptable change. 

@tommcdon @noahfalk any idea who should do this work?

**Comment by davidfowl** [comment]
It’s not breaking if you have a mix of 3.1 and 5.0 apps. It’s only breaking if you mix 2.x and >= 5.x apps specifically if you have a 5.0 app with w3c making a request to a 2.x app. This is broken today if you explicitly set it but it work fine if you do the same with a 3.x app (since Activity detects the format)

**Comment by noahfalk** [comment]
@shirhatti - If I remember right the last time we talked about this you were looking into what kind of notification we should do to customers. Did we ever reach a conclusion?

> did we decide we are going to do it? is it an acceptable change.

I am in favor of doing it. If there is a broader process the BCL team likes to do or more consensus to gather could you let me know?

> @tommcdon @noahfalk any idea who should do this work?

I was hoping it could be you but let me know if that is a problem. Code-wise I expect this is a tiny change:
1. [Assign W3C to the s_defaultIdFormat field]( https://github.com/dotnet/runtime/blob/73cde557e8e041c93d10dffc37f7fb0ea37b4b1a/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L739)
2. Add a compat switch so that customers can opt-out of the change if it breaks their app (hopefully this is very rare)

**Comment by tarekgh** [comment]
@noahfalk I'll try to get into this then at some time in the next couple of weeks if it is not earlier.  We need to talk about the config switch as from what I am hearing from @davidfowl will not be a serious breaking except with some configuration (mixing 2.x with 5.x). Usually, we don't use config switches in core except for serious breaking cases. We can delay the switch till we fix someone broken and we can try service the library with the switch support.

**Comment by noahfalk** [comment]
> We need to talk about the config switch

I'm happy to chat, but up-front I'd be nervous about making a change like this without an opt-out. 

> We can delay the switch till we fix someone broken and we can try service the library with the switch support.

This sounds hugely expensive vs. adding it now. I'm not sure why we'd want to be this reserved about it? I think the odds of at least one customer wanting this switch is pretty good.

**Comment by davidfowl** [comment]
> I'm happy to chat, but up-front I'd be nervous about making a change like this without an opt-out.

The workaround is trivial thought it requires a code change. Does that count 😄 ?

**Comment by noahfalk** [comment]
> The workaround is trivial thought it requires a code change. Does that count 😄 ?

Nope : ) We want people to be able to upgrade between versions without recompiling.

**Comment by tarekgh** [comment]
> his sounds hugely expensive vs. adding it now. I'm not sure why we'd want to be this reserved about it? I think the odds of at least one customer wanting this switch is pretty good.

I am hesitating to add this switch from now because it looks to me it will serve a short term and not expect to be used. This is exactly the servicing bar. adding the switch means we have to support it forever I guess.

**Comment by noahfalk** [comment]
> adding the switch means we have to support it forever I guess.

I think it would reasonable to support it forever : ) The only burden I am aware that imposes on us is that we'd have an extra ~5 lines of code that shouldn't be deleted

````
if(compat_switch)
{
    s_defaultIdFormat = ActivityIdFormat.Hierarchial;
}
else
{
     s_defaultIdFormat = ActivityFormat.W3C;
}
````

**Comment by tarekgh** [comment]
@noahfalk I am ok to add the switch then as you feel strongly about it. we can write the code in just one line :-)

```C#
    s_defaultIdFormat = compat_switch ? ActivityIdFormat.Hierarchial : ActivityFormat.W3C;
```

even we can cache the value in some static and avoid the switch check. of course, we'll pay for the static variable access cost :-)

**Comment by noahfalk** [comment]
Cool : )

> even we can cache the value in some static and avoid the switch check

s_defaultIdFormat static field already serves as that cache. Barring rare race conditions that assignment will only get evaluated once per app.

**Comment by tarekgh** [comment]
https://github.com/dotnet/docs/issues/18953
