### ISSUE TITLE
Compiler optimizing needed variable away

### ISSUE THREAD

**Issue by liadpaz** [dotnet/runtime#34799]
I'm developing an UWP app and I'm using a REST client that I have developed by myself. I have checked the REST client independently, and it works just as expected. But when using it on the UWP app I get a null reference exception for a variable that I assigned a value from the REST client.
When I'm debugging and pinning a breakpoint on the the assignment line it works, also if I'm writing "Debug.WriteLine($var)" after assigning the value to the variable it works just fine. Also I tried to put the no optimization attribute on the method.

I don't know if it's the right format or place to post this, if it's not please let me know

EDIT: On release configuration the "Debug.WriteLine($var)" have no effect but "Console.WriteLine($var)" does make it work as intended

**Comment by hoyosjs** [comment]
@tommcdon

**Comment by jkotas** [comment]
> On release configuration the "Debug.WriteLine($var)" have no effect but "Console.WriteLine($var)" does make it work as intended

This is expected behavior. `Debug.WriteLine` is annotated with `Conditional("DEBUG")` attribute. It means that the compilers will emit a call to this method in debug builds only by default. See https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug?view=netcore-3.1#remarks for more details.

**Comment by KalleOlaviNiemitalo** [comment]
Sure, the compiler discards the `Debug.WriteLine` call in release builds. However, that still does not quite explain why a null reference exception is thrown.

Without seeing the original poster's source code, I guess the exception could be caused by the garbage collector either clearing a weak reference or calling a finalizer that then resets some field to `null`. If so, `GC.KeepAlive` could be one way to fix it.
