### ISSUE TITLE
Shouldn't Microsoft.Extensions.Hosting.BackgroundService implement IDisposable according to the Dispose pattern?

### ISSUE THREAD

**Issue by Mr-Bart-Simpson** [dotnet/runtime#34809]
In Microsoft.Extensions.Hosting.BackgroundService, the IDisposable interface is implemented via 
`public virtual void Dispose()
{
...
}` only - Shouldn't the implementation follow the recommended pattern with somenthing like that?

`public void Dispose()
{
...
}`

`protected virtual void Dispose(bool disposing)
{
...
}`

**Comment by eerhardt** [comment]
We can't change `BackgroundService` to implement the Dispose pattern outlined below, since it has already shipped in the form it has.

https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

If we changed the class to follow this pattern it would break anyone who has already overriden the `virtual void Dispose()`.

However, this may not be an issue since the official Dispose pattern's major advantage is for classes that contain a Finalizer. Our recommendation is to not have Finalizers on your BackgroundService, but instead implement it using a SafeHandle. See this section: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#safe-handles

> Writing code for an object's finalizer is a complex task that can cause problems if not done correctly. Therefore, we recommend that you construct System.Runtime.InteropServices.SafeHandle objects instead of implementing a finalizer.

So if you needed to clean up unmanaged resources in a BackgroundService, you can wrap the unmanaged resource in a SafeHandle, and hold onto the SafeHandle in the `BackgroundService`. Then just override `void Dispose()` and call `.Dispose()` on the SafeHandle. The SafeHandle will ensure the unmanaged resource is cleaned up in the case where the service isn't Disposed correctly.

If we were to do it over, I think we should have implemented the Dispose pattern as doc'd. But since it has already shipped, I don't think we can make this change.
