### ISSUE TITLE
User-friendly single-file cross-platform binaries

### ISSUE THREAD

**Issue by Serentty** [dotnet/runtime#34852]
Looking at the documentation for .NET Core, it seems that even when generating cross-platform CIL DLLs, it's necessary to distribute a native app loader stub for each platform. What I would appreciate is a way to compile an application as a single file that you can double click and run on any operating system or CPU architecture (assuming that the runtime is already installed), similar to the experience with JAR files on the JVM. The ability to distribute applications this way is important to me because it has saved me many times in situations where the developer either forgot or chose not to distribute an application for my platform.

**Comment by swaroop-sridhar** [comment]
@Serentty Thanks for filing the issue.

Basically, we want platform-independent framework-dependent single-file apps. 
For this feature, we need the ability to build single-file app DLLs -- which will enable us to run the app using the framework's dotnet host.

Effectively, this issue is a dup of https://github.com/dotnet/runtime/issues/13677

**Comment by Serentty** [comment]
Thank you! I searched for an issue like this already, but it was hard to put into words for a search, so I didn't find anything.
