### ISSUE TITLE
Microsoft.Extensions.DependencyModel dependencies for .NET Framework 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#35006]
#34296 bumped the versions of its dependencies as side-effect. It breaks ingestions of Microsoft.Extensions.DependencyModel into SDK: https://github.com/dotnet/sdk/pull/11246#issuecomment-613804552

**Comment by eerhardt** [comment]
Doing an initial investigation, it appears the reason `System.Runtime.CompilerServices.Unsafe, 5.0.0.0` is being brought in on .NET Framework is because `Microsoft.Extensions.DependencyModel` is now referencing `System.Text.Json` on `net461` (which references `System.Runtime.CompilerServices.Unsafe, 5.0.0.0`). Previously, `DependencyModel` was using `Newtonsoft.Json`, which doesn't bring in a newer `System.Runtime.CompilerServices.Unsafe`.

I believe what `Microsoft.Extensions.DependencyModel` is doing now is the correct thing to do going foward. So to resolve this issue, I think we either need to bump `Microsoft.NET.HostModel` to a newer `System.Runtime.CompilerServices.Unsafe` version, or we need to add a binding redirect.

**Comment by eerhardt** [comment]
@swaroop-sridhar - is there a reason that `Microsoft.NET.HostModel` is using an older version of `System.Text.Json`?

https://github.com/dotnet/runtime/blob/1cfccd2a7937117341b256847e613dd710a70adb/src/installer/managed/Microsoft.NET.HostModel/Microsoft.NET.HostModel.csproj#L19

Why isn't this compiling against the `System.Text.Json` that is in `src\libraries`?

**Comment by elinor-fung** [comment]
cc @jkoritzinsky - version of `System.Text.Json` was explicitly set in #2115

**Comment by jkoritzinsky** [comment]
The version was explicitly set because the version of System.Runtime.CompilerServices.Unsafe in the 5.0 package was broken at the time and that was blocking dotnet/runtime uptake to dotnet/sdk.

**Comment by eerhardt** [comment]
> the version of System.Runtime.CompilerServices.Unsafe in the 5.0 package was broken at the time

But that was fixed with https://github.com/dotnet/runtime/issues/1918, right? Do we know of a reason why `Microsoft.NET.HostModel` shouldn't reference the `5.0.0` version of `System.Text.Json` now?

**Comment by jkoritzinsky** [comment]
I didn't want to risk breaking anything by moving things, so I never went to go back to fix it.

**Comment by eerhardt** [comment]
This was verified with https://github.com/dotnet/sdk/pull/11329. New versions of `Microsoft.Extensions.DependencyModel` are now consumed in `dotnet/sdk`.

**Comment by ericstj** [comment]
@eerhardt did you intend to keep this consuming System.Text.Json via package?  It looks like that's still the case, and additionally it is using an API which is now marked obsolete: IgnoreNullValues
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/installer/managed/Microsoft.NET.HostModel/ComHost/ClsidMap.cs#L68

https://github.com/dotnet/runtime/commit/c2291eb865fa542c888cefdb16e669dceffeda5f /cc @layomia

**Comment by eerhardt** [comment]
> @eerhardt did you intend to keep this consuming System.Text.Json via package?

My intention with this change was to unblock the ingestion of the new DependencyModel library.

The uber issue tracking HostModel's dependency on System.Text.Json is #1823.
