### ISSUE TITLE
Add a flag to System.Data.CommandBehavior to dispose the command with the DbDataReader

### ISSUE THREAD

**Issue by mburbea** [dotnet/runtime#35069]
I propose adding a new flag to the `System.Data.CommandBehavior` enum, to dispose the parent command with the reader. `DisposeCommand` 
First, there's **very** little use of the command once the reader is executed but in some cases like `SqlDataReader`, disposing the reader is insufficient and will lead to some confusing exceptions like the one below.
e.g.
```cs
using var conn = new SqlConnection(connectionString);
await conn.OpenAsync();
using var readerCmd = new SqlCommand(query, conn);
using(var reader = await readerCmd.ExecuteReaderAsync(CommandBehavior.SingleResult | CommandBehaviorSequentialAccess))
{
      while(await reader.Read())
      {
      // do stuff with reader.
      }
}
using var nonQuery = new SqlCommand(someQuery, conn);
await nonQuery.ExecuteNonQueryAsync(); // throws an odd exception saying that there is an active reader on this command which is not true.
```
But more importantly, in libraries like Dapper, to reduce the verbosity of the this pattern of requiring a command, and a reader, it returns a wrapped instance to workaround this problem. This flag will simplify the standard practice, as you can now hand the native reader back and it will handle this behavior.

Internally at my work, my project that has to deal with many databases on different backends (similar to dapper), but also logs information about the query being executed and I had to create a wrapped reader to simplify the use case.

**Comment by Wraith2** [comment]
If you use the explicit using block for the first command it should dispose before the second command is created and your error will go away. The command owns the connection while it is active and so even though you dispose the reader because you don't dispose the command the connection isn't available to be owned by the second command. If you're tempted to use MARS I suggest against it, just handle the scopes cleanly.

**Comment by mburbea** [comment]
Oh I'm aware, but I have library code that handles query setup and I want to hand the consumer back the reader (because they're going to use it for bulk copy or whatever).

Here is a very simplified version of something I currently do:

```cs

public abstract class LoggedDbConnection
{
      protected readonly ILogger _logger;
      private DbConnection _connection;
      public abstract ConnectionName {get;}
      protected abstract DbConnection EnsureInitialized(ref connection);
      protected DbConnection Connection => EnsureInitialized(ref _connection);
       protected abstract DbCommand SetupCommand(commandText, timeout, parameters);

      public Task<DbDataReader> ExecuteReaderAsync(string text, CommandBehavior behavior = default,
      int? timeout = null, CancellationToken cancellationToken = default,
      params (string name, object value)[] parameters)
     {
         var watch = StopWatch.StartNew();
         var cmd = SetupCommand(commandText, timeout, parameters);
         var reader = await ExecuteReaderAsync(behavior, cancellationToken).ConfigureAwait(false);
         Log.Logger(LogMessage, conn.ConnectionName, watch.Elapsed, commandText, parameters);
         return WrappedDataReader(reader, cmd);
     }
```

And then I have an inheritor that is for postgres, sqlserver, and sqllite etc that does the appropriate thing for the various db for setting the connection and the command up correctly. I do this to abstract away the different dbs that other systems are using that I have no control over, and simplify the code I end up calling. The final bit is that `WrappedDataReader`, that only exists so that as a consumer of the `LoggedDbConnection` can just work with the resulting datareader and not the command that spawned it. For things like `ExecuteScalarAsync`, and `ExecuteNonQueryAsync` the caller doesn't have to care about the command at all, and I handle that in the library method.

**Comment by bgrainger** [comment]
I don't think this is necessary. Correct ADO.NET implementations should allow the `DbDataReader` to "outlive" the `DbCommand`:

```csharp
var connection = new SomeDbConnection();
connection.Open();

DbDataReader reader;
using (var cmd = connection.CreateCommand())
{
    reader = cmd.ExecuteReader();
}

// use 'reader' after 'cmd' is disposed
return reader;
```

You can see that most libraries support this here: https://mysql-net.github.io/AdoNetResults/#Dispose_command_before_reader

If ADO.NET providers would need to be updated to support this new flag, then it would be just as easy to update them to allow this pattern.

Thus there's no need to add a flag to dispose the `DbCommand` when the `DbDataReader` is disposed, because it can be disposed by the method that created it.

**Comment by Wraith2** [comment]
That's a really interesting feature matrix @bgrainger. Looking at it i'm wondering if there are a few things on there we can change in SqlClient to make it more usable, like in-range conversions from decimal to double. /cc @David-Engel

**Comment by bgrainger** [comment]
Thanks! It was born out of this discussion: https://github.com/dotnet/runtime/issues/17004#issuecomment-346109151

**Comment by roji** [comment]
Missed this discussion... FWIW Npgsql also works just like @bgrainger describes - it's fine to create a new command while a previous command is still un-disposed. What's disallowed is executing it while a previous reader is still un-disposed. I agree that this should be handled as a SqlClient enhancement rather than a general new ADO flag.

I'm going to close this for now as not needed, but if there are arguments to the contrary we can continue the discussion and re-open if needed.
