### ISSUE TITLE
Should JsonSerializerOptions have bounds in its cache size?

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#35084]
What prevents the caches inside of this instance from growing unbounded?  Do we need to place a limit on the size of the cache, making it an LRU cache or something like that?

_Originally posted by @stephentoub in https://github.com/dotnet/runtime/pull/35040#discussion_r409594626_

cc @steveharter @layomia

**Comment by JamesNK** [comment]
> What prevents the caches inside of this instance from growing unbounded?

Typically there are a finite number of types in an app that are serialized so it isn't an issue. But dynamic type generation plus serialization could create caching issues.

In Newtonsoft.Json the DefaultContractResolver holds the cache. Because it is an instance type it is possible to create a new contract resolver for serialization of dynamic types and then throw it away.

**Comment by NinoFloris** [comment]
>and then throw it away.
This is also important in the context of assembly unloading

**Comment by steveharter** [comment]
As @JamesNK points out the existing caches are all rooted to a given Type that was previously (de)serialized.

Currently it is not possible to "unload" a given Type from the serialized, but that could certainly be done. For example, a `JsonSerializerOptions.Uncache(Type)` could be added. This would simply remove the `JsonClassInfo` entry for the Type from the dictionary held by the options class.

To unload all Types for a given assembly a `JsonSerializerOptions.Uncache(Assembly)` could be added which would enumerate the underlying dictionary to unload the appropriate types.

**Comment by NinoFloris** [comment]
I understand the implications, I was pointing out assembly unloading as another angle to keep in mind.
