### ISSUE TITLE
How to: COM with C++ Client and .Net Core 3.1 Server ?

### ISSUE THREAD

**Issue by abhiphirke** [dotnet/runtime#35129]
I am currrently stuck up while using `.Net Core 3.1` component from a `Vanilla C++ Client`.
The issue I am facing is **_how to make the Events Sink work_**. 

My questions are:

1. If `ComSourceInterfaces` is obsolete, **what is the best and new way to do this?**

2. Everything in the code below works pretty well with C++ client, except Event Sink: With the above code, my C++ client can successfully get `IConnectionPointContainer`, `FindConnectionPoint` and then `Advise` on it. This results into my event invocation list having 1 item registered. However, `OnReceiveNotification(objectType, objectNo)` from C# Server does not invoke the method on the client. In fact, the further method in C# after this call is not executed at all which is shown by the logs. There is no exception, no error whatsoever. **What possibly is going wrong? How to make this work?**

Please help me get out of this situation. Many thanks in advance.

My .Net Core 3.1 COM component does a simple thing as send and receive notifications. It looks like this:

**Server Interface:**
```
[ComVisible(true)]
[Guid("a403aad0-1d41-4573-90d3-eb45fdea6b56")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IServer
{
    string Connect(string userName, string password);
    string Disconnect();
    public string Send(int objectType, int objectNo);
}
```
**Server Object:**
```
[ComVisible(true)]
[Guid("8c95f6e6-82c6-465a-b9ce-238e63af7327")]
[ProgId("App.Client.1")]
[ClassInterface(ClassInterfaceType.None)]
[ComSourceInterfaces(typeof(IEventReceiver))]
[Obsolete]
public class Server : IServer
{
    public delegate void ReceiveNotificationEvent_Delegate(int objectType, int objectNo);
    private event ReceiveNotificationEvent_Delegate OnReceiveNotification;

    public string Connect(string userName, string password) { }

    public string Disconnect() { }

    public string Send(int objectType, int objectNo) { }
}
```
**Event Receiver Interface:**
```
[ComVisible(true)]
[Guid("8c95f6e6-82c6-465a-b9ce-238e63af7327")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IEventReceiver
{
    void OnReceiveNotification(int objectType, int objectNo);
}
```

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@abhiphirke Thanks for asking about this. Your question made me realized we were missing test coverage for this scenario. See https://github.com/dotnet/runtime/pull/35151 for the test as well as an example of how to consume COM events from a managed COM server.

>what is the best and new way to do this?

That is the appropriate attribute. It was marked `Obsolete` when it was slated to be removed but now it is most likely going to stay.

>What possibly is going wrong? How to make this work?

COM is simple in some ways, but not for events. COM Events are incredibly complicated and interacting with .NET adds additional complexity. Try referring to the test in the above PR. If you still have questions let us know.

**Comment by AaronRobinsonMSFT** [comment]
>What possibly is going wrong? How to make this work?

As an attempt at psychic debugging, it could be the case that your native sink didn't implement `IDispatch`. This is required to work with .NET events. See the test for an example of how to implement the minimum of `IDispatch`.

**Comment by abhiphirke** [comment]
> > What possibly is going wrong? How to make this work?
> 
> As an attempt at psychic debugging, it could be the case that your native sink didn't implement `IDispatch`. This is required to work with .NET events. See the test for an example of how to implement the minimum of `IDispatch`.

Thanks a ton for quick responses. I too was thinking about IDispatch on the sink but nowhere in the documentation mentions this as requirement, so I was not sure. Will try that.

**Comment by AaronRobinsonMSFT** [comment]
>Thanks a ton for quick responses. I too was thinking about IDispatch on the sink but nowhere in the documentation mentions this as requirement, so I was not sure. Will try that.

@abhiphirke Which documentation did you refer to when attempting to consume COM events?

**Comment by abhiphirke** [comment]
This page: [Exposing .NET Core components to COM](https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com)  and [ComSourceInterfacesAttribute Class](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comsourceinterfacesattribute?view=netcore-3.1).

Also, the sample that is provided here (https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo)  provides client in .Net Core only. IMHO, if a C++ and VB client is provided, it'd be much useful, cause most likely these are the environments where this feature is most likely to be used.

**Comment by abhiphirke** [comment]
> > What possibly is going wrong? How to make this work?
> 
> As an attempt at psychic debugging, it could be the case that your native sink didn't implement `IDispatch`. This is required to work with .NET events. See the test for an example of how to implement the minimum of `IDispatch`.

BTW, the `IDispatch` on my sink, hits breakpoint neither on `QueryInterface` nor on `IDispatch.Invoke`. :(

**Comment by AaronRobinsonMSFT** [comment]
@abhiphirke Okay. Can you share your native sink? At least the declaration. 

Here is the one from the test PR above:

```C++
    class EventSink : public UnknownImpl, public TestingEvents
    {
        std::map<DISPID, std::wstring> _firedEvents;


    public:
        void ResetFiredState(_In_ DISPID id)
        {
            _firedEvents.erase(id);
        }


        bool DidFire(_In_ DISPID id, _Out_ std::wstring& message)
        {
            auto iter = _firedEvents.find(id);
            if (iter == std::end(_firedEvents))
                return false;


            message = iter->second;
            return true;
        }


    public: // IDispatch
        virtual HRESULT STDMETHODCALLTYPE GetTypeInfoCount(
            /* [out] */ __RPC__out UINT* pctinfo)
        {
            return E_NOTIMPL;
        }


        virtual HRESULT STDMETHODCALLTYPE GetTypeInfo(
            /* [in] */ UINT iTInfo,
            /* [in] */ LCID lcid,
            /* [out] */ __RPC__deref_out_opt ITypeInfo** ppTInfo)
        {
            return E_NOTIMPL;
        }


        virtual HRESULT STDMETHODCALLTYPE GetIDsOfNames(
            /* [in] */ __RPC__in REFIID riid,
            /* [size_is][in] */ __RPC__in_ecount_full(cNames) LPOLESTR* rgszNames,
            /* [range][in] */ __RPC__in_range(0, 16384) UINT cNames,
            /* [in] */ LCID lcid,
            /* [size_is][out] */ __RPC__out_ecount_full(cNames) DISPID* rgDispId)
        {
            return E_NOTIMPL;
        }


        virtual /* [local] */ HRESULT STDMETHODCALLTYPE Invoke(
            /* [annotation][in] */
            _In_  DISPID dispIdMember,
            /* [annotation][in] */
            _In_  REFIID riid,
            /* [annotation][in] */
            _In_  LCID lcid,
            /* [annotation][in] */
            _In_  WORD wFlags,
            /* [annotation][out][in] */
            _In_  DISPPARAMS* pDispParams,
            /* [annotation][out] */
            _Out_opt_  VARIANT* pVarResult,
            /* [annotation][out] */
            _Out_opt_  EXCEPINFO* pExcepInfo,
            /* [annotation][out] */
            _Out_opt_  UINT* puArgErr)
        {
            //
            // Note that arguments are received in reverse order for IDispatch::Invoke()
            //


            switch (dispIdMember)
            {
            case DISPATCHTESTINGEVENTS_DISPID_ONEVENT:
            {
                return OnFireEventHandler(dispIdMember, pDispParams);
            }
            }


            return E_NOTIMPL;
        }


    private:
        HRESULT OnFireEventHandler(_In_ DISPID dispId, _In_ DISPPARAMS* dispParams)
        {
            if (dispParams == nullptr)
                return E_POINTER;


            if (dispParams->cArgs != 1)
                return E_INVALIDARG;


            VARIANTARG* msgMaybe = dispParams->rgvarg;
            if (msgMaybe->vt != VT_BSTR)
                return E_INVALIDARG;


            _firedEvents.insert({ dispId, msgMaybe->bstrVal });
            return S_OK;
        }


    public: // IUnknown
        STDMETHOD(QueryInterface)(
            /* [in] */ REFIID riid,
            /* [iid_is][out] */ _COM_Outptr_ void __RPC_FAR* __RPC_FAR* ppvObject)
        {
            return DoQueryInterface(riid, ppvObject,
                static_cast<TestingEvents*>(this),
                static_cast<IDispatch*>(this));
        }


        DEFINE_REF_COUNTING();
    };
```

**Comment by abhiphirke** [comment]
[NotificationTest.zip](https://github.com/dotnet/runtime/files/4507423/NotificationTest.zip)

Here is my code. Simple SignalR Hub called `Hub`, a SignalR client called `Spoke` and C++ client called `Client`. 

When the `Spoke` receives notification from `Hub`, it tries to fire `OnNotification` event, but the subscriber on `Receiver` is never called. It creates a simple log in 'spokelog.txt` in project directory to indicate that.

Also, the `IDispatch` on `Receiver` is never queried and  `IDispatch.Invoke` is never called during entire execution.

That is the only challenge between me and finish line. So, please help. Many thanks!

**Comment by AaronRobinsonMSFT** [comment]
@abhiphirke Looking at the following

```CSharp
_hubConnection.On<int, int>("ReceiveMessage", (int objectType, int objectNo) =>
{
    File.AppendAllText(@".\spokelog.txt", "ONRECEIVE : Start...\r\n");
    onReceiveMessage(objectType, objectNo);
    File.AppendAllText(@".\spokelog.txt", "ONRECEIVE : Finish.\r\n");
});
```

and the `_hubConnection` log file, I would surmise the `onReceiveMessage(objectType, objectNo);` call is throwing an exception and somewhere up the ASP.Net stack all exceptions are being caught. This makes sense because my guess is the passed in delegate `(int objectType, int objectNo) => OnNotification(objectType, objectNo)` doesn't check if the event `OnNotification` is `null`. It would be helpful to verify that is the case.

Other than that I would suggest to try verify what your receiver is being QI'd for during the `Advise()` call. It should be QI'd for `4E2186FC-A8DC-455F-836F-1C07EEACF248`. Also the managed definition of the `IReceiver` interface states `IUnknown`, but the IDL states `IDispatch`. Change `[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]` to `[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]` on `IReceiver`. Additionally and this is just speculation because I have never tried it, your defined event on `ComServer` is marked `private`, I would try changing that to `public`. COM doesn't understand access modifiers, but in .NET we expect matching contracts and use reflection in a simple way for COM Events so it wouldn't surprise me if we only consider public members.

I tend not to run user supplied code, so haven't ran any of the above code just looked at the log and various code sections. Remember that COM is all about consistency. The IDL and managed definitions of the interfaces need to match or else anything or nothing can happen.

**Comment by abhiphirke** [comment]
Thanks again for your inputs. 

The event notification is not null since `Advise` is working. The invocation list shows exactly 1 item in it.

I am getting query on QI for the id `4E2186FC-A8DC-455F-836F-1C07EEACF248`. With everything you mentioned corrected and everything else working like it should, the final call to `Receiver.OnNotification` is just not happening. 

That too without any error or exception. Perhaps, there is some, but is not raised. Is there any way to raise exceptions for any possible erros?

**Comment by AaronRobinsonMSFT** [comment]
@abhiphirke I looked through this again and given your statement above and the logs, I believe the issue is related to COM. COM has its own threading model called [apartments](https://docs.microsoft.com/windows/win32/com/processes--threads--and-apartments#the-apartment-and-the-com-threading-architecture). This means that whenever attempting to perform multi-threaded operations with COM objects that must be taken into account.

Please refer to the documentation for [`CoInitialize()`](https://docs.microsoft.com/windows/win32/api/objbase/nf-objbase-coinitialize) and [`CoInitializeEx()`](https://docs.microsoft.com/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex). The issue is the usage of `CoInitialize()` which will initialize the current thread to an STA and all managed object will therefore be associated with that apartment. During the dispatch a deadlock occurs since the STA thread that created the object is the one that is expecting to handle the dispatch. In order to initialize to the MTA use the following instead.

```C
CoInitializeEx(NULL, COINIT_MULTITHREADED);
```

Please read the accompanying documentation for this.

I would also suggest providing the corresponding [`DispIdAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dispidattribute) for the method on the managed definition of `IReceiver`.

The correct managed definition should be:

```CSharp
[ComVisible(true)]
[Guid("4E2186FC-A8DC-455F-836F-1C07EEACF248")]
[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
public interface IReceiver
{
    [DispId(123)]
    void OnNotification(int objectType, int objectNo);
}
```

/cc @elinor-fung

**Comment by abhiphirke** [comment]
`Hurrah...` It worked now!!!! 
Really appreciate you review my code and give me pointers that made it work.  
Thank you so much!

**Comment by abhiphirke** [comment]
> That is the appropriate attribute. It was marked `Obsolete` when it was slated to be removed but now it is most likely going to stay.

One more quick question, when is it likely that I'd get to remove that [Obsolete] attribute? 
It'd help me for our internal communication.

**Comment by AaronRobinsonMSFT** [comment]
I'm not sure why it was added to the `Server` class. Instead it should be suppressed via `#pragma warning disable 618`. However, we should remove the tag anyways. Let me create a PR.
