### ISSUE TITLE
Dictionary<string, object> not serialized properly with dictionary key naming policy set to camel case

### ISSUE THREAD

**Issue by gislikonrad** [dotnet/runtime#35242]
I'm writing a logger extension that writes json log lines that are to be consumed by a log aggregator.

When a key/value pair in the log entry dictionary has a value that is not a value type, the key doesn't follow the camel case policy.

Reproduction example:
``` csharp
var dictionary = new Dictionary<string, object>()
{
    { "Timestamp", DateTimeOffset.UtcNow },
    { "EventId", new EventId(1, "Serialization") },
    { "Category", typeof(Program).FullName },
    { "Level", LogLevel.Information },
    { "Message", "The property names should all be camel cased." },
    { "Exception", null },
    { "Scope", Enumerable.Empty<string>() }
};
var policy = JsonNamingPolicy.CamelCase;
var options = new JsonSerializerOptions
{
    PropertyNamingPolicy = policy,
    DictionaryKeyPolicy = policy,
    // Added for readability
    WriteIndented = true
};
options.Converters.Add(new JsonStringEnumConverter(policy, false));
var serialized = JsonSerializer.Serialize(dictionary, options);
Console.WriteLine(serialized);            
```

Expected result
``` json
{
  "timestamp": "2020-04-21T14:33:41.8750293+00:00",
  "eventId": {
    "id": 1,
    "name": "Serialization"
  },
  "category": "JsonSerializerBug.Program",
  "level": "information",
  "message": "The property names should all be camel cased.",
  "exception": null,
  "scope": []
}
```

Actual result
``` json
{
  "timestamp": "2020-04-21T14:33:41.8750293+00:00",
  "EventId": {
    "id": 1,
    "name": "Serialization"
  },
  "category": "JsonSerializerBug.Program",
  "level": "information",
  "message": "The property names should all be camel cased.",  
  "Exception": null,
  "Scope": []
}
```

**Comment by layomia** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/33508. The bug here is that the dictionary key policy is not applied when the value is not a primitive, i.e it should be written as a JSON object or JSON array.

Just to confirm, what version of System.Text.Json are you using? This issue is fixed in 5.0/master.

**Comment by gislikonrad** [comment]
This is happening when running as a Microsoft.NETCore.App v 3.1.2 and not referencing a specific package from nuget.

**Comment by layomia** [comment]
Thanks. As mentioned, this issue is fixed for .NET 5 (master). However, porting the fix to 3.x will not meet the servicing bar.

Some workarounds here are to use a custom converter, upgrade the app to a [preview of .NET 5](https://dotnet.microsoft.com/download/dotnet/5.0), or use a [preview of the System.Text.Json v5.0.0 package](https://www.nuget.org/packages/System.Text.Json/5.0.0-preview.2.20160.6) on nuget.
