### ISSUE TITLE
System.Diagnostics.DiagnosticSource v4.7.0 fails to load in PowerShell v6.2.4

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/runtime#35263]
We came across this issue when publishing a *netstandard2.0* library and importing module on PowerShell that contains dependency on **System.Diagnostics.DiagnosticSource v4.7.0**.
Running function from module fails as under:

```log
System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at myModule.TestSampleCmdletCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

The System.Diagnostics.DiagnosticSource.dll is available in publish directory from where we're trying to import from.

Observations:
- The issue does not reproduce with System.Diagnostics.DiagnosticSource v4.6.0 (last working version)
- The issue also does not reproduce when working with PowerShell v7.0.0.

Since PS 6.2.4 also supports .NET Standard 2.0, this is expected to work as well. What we're unclear is whether this issue belongs to DiagnosticSource or PowerShell.

[Link to repro App](https://github.com/cheenamalhotra/DiagnosticSourceIssue)

**Comment by tarekgh** [comment]
@cheenamalhotra could you please try to set the environment variable `Set COREHOST_TRACE=1` before importing the module and look if you'll get any logs produced in your PS session? also will be helpful if you can run 
```
dotnet-trace collect --providers Microsoft-Windows-DotNETRuntime:4:4 --process-id <PID>
```
before loading the module. <PID> I think can be the PowerShell process Id. 

@joperezr do you have any idea what could be the problem here?

**Comment by fMichaleczek** [comment]
if you go to your $pshome, you will see the dll is already inside PowerShell. 
You can load the dll with Add-Type  -AssemblyName System.Diagnostics.DiagnosticSource

I think your problem is linked to this issue :
[Unable to load multiple versions of .Net assembly module dependencies](https://github.com/PowerShell/PowerShell/issues/2083) 

This issue will be resolved by the [RFC0043](https://github.com/PowerShell/PowerShell-RFC/blob/master/X-Withdrawn/RFC0043-Loading-Module-Into-Isolated-AssemblyLoadContext.md) but there is no ETA and it will be available on a new release (7.1+)

Use a reference dll into your c# projet and use the property 'RequiredAssemblies' of the psd1's module to specify the assembly name (it accepts assembly name if it's already present) 
https://docs.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest?view=powershell-7

**Comment by joperezr** [comment]
While I wasn't able to repro your issue (probably because I don't have the same version of powershell) this is most likely an issue because you are publishing a netstandard application which is not really supported. NetStandard is an API spec, not really a runtime, therefore you can't really expect to publish them as the dependencies your module will need might be different depending on the runtime you end up running in. For this reason, my suggestion would be to instead of publishing as a netstandard2.0 module, publish it as a net461 module (or netcoreapp2.0 if you intend to run on powershell core) that way all the right dependencies for the runtime you will be running in will be placed on the publish folder, and you should get the right behavior.

**Comment by tarekgh** [comment]
Closing the issue per the listed comments. @cheenamalhotra please let's know when you correcting the publishing and still have a problem.

**Comment by fMichaleczek** [comment]
@joperezr you should use [powershell.standard](https://github.com/PowerShell/PowerShellStandard/) package 
There is a blog from the PS team with more detailed
[ Depending on the right PowerShell NuGet package in your .NET project]( https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/) 
It's not an easy area... i advice you to read the opened issue in powershell.standard.

**Comment by tarekgh** [comment]
@fMichaleczek thanks for your comments, it is very useful. This seems not runtime issue and more about PowerShell. We can help more if thought otherwise. My comment https://github.com/dotnet/runtime/issues/35263#issuecomment-617466783 also suggesting how can get more logs when loading the assemblies which may help too.
