### ISSUE TITLE
API Proposal: UnreachableException

### ISSUE THREAD

**Issue by carlreinke** [dotnet/runtime#35324]
## Motivation
This exception is expected to never be thrown.  Code coverage tools might choose to ignore non-coverage of the statement or branch that throws this exception.  In fact, coverage of such a statement or branch is undesirable, as it would indicate that the code is making an invalid assumption.

## Proposal
```csharp
#nullable enable
using System.Runtime.Serialization;

namespace System
{
    public sealed class UnreachableException : SystemException
    {
        public UnreachableException()
            : base("The program executed an instruction that was thought to be unreachable.")
        {
        }

        public UnreachableException(string? message)
            : base(message)
        {
        }

        public UnreachableException(string? message, Exception? innerException)
            : base(message, innerException)
        {
        }

        private UnreachableException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }
    }
}
```

## See Also
 * [ExceptionUtilities.Unreachable in runtime](https://github.com/dotnet/runtime/blob/0fbd88e4bd00b5f5218a20468e617b3d79d10a1d/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/ExceptionUtilities.cs#L19)
 * [ExceptionUtilities.Unreachable in Roslyn](https://github.com/dotnet/roslyn/blob/894fce6b124299b2db6a7a8b30e1973adeb84a5f/src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs#L30)

**Comment by carlreinke** [comment]
Any concerns or can this be ready-for-review?

**Comment by GrabYourPitchforks** [comment]
How would this interact with the proposed "never" return type (https://github.com/dotnet/csharplang/issues/538)? Is this API a point-in-time patch until that feature comes online?

Presumably code coverage analyzers could already look for methods marked with [`[DoesNotReturn]`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnattribute) and exclude any code after such call sites from being included in the final metrics.

It would be helpful to clarify this exception's place in the ecosystem in a world where both of these capabilities exist.

**Comment by carlreinke** [comment]
`[DoesNotReturn]` and "never" do not apply in a lot of cases where `UnreachableException` would be used.

Consider a random example taken from Roslyn:
https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Compilers/CSharp/Portable/Binder/BlockBinder.cs#L64-L72

In this case, the method does sometimes return, so neither `[DoesNotReturn]` nor "never" are applicable to that method, yet there is a code path that is expected to be unreachable.

Applying `[DoesNotReturn]` or "never" to an "Unreachable" helper method and calling that instead doesn't solve the problem because that helper method still has to throw some exception to indicate that the presumably unreachable code path was executed (or it could `FailFast`, but that's not what you want in a lot of cases).

**Comment by GSPP** [comment]
This seems very useful to me. Sometimes, a place is to be considered unreachable. Having this exception type confers the following benefits:

1. It documents intent.
2. It makes C# flow analysis understand that this point in the code does not continue execution.
3. If this is ever reached at runtime due to a bug, the algorithm aborts. Presumably, control transfers to some generic top-level exception handler that logs the exception and alerts developers.
4. Resharper could be taught to understand what this type means.
5. Having this in the BCL creates an ecosystem-wide standard.

I have defined this type myself and I'm using it.

**Comment by carlreinke** [comment]
@GrabYourPitchforks Any other concerns or can this be put into the review queue?

**Comment by GrabYourPitchforks** [comment]
Marking this as ready for review.

Open question for reviewers: given that the target scenario is for debugging, code coverage, and other dev tools; would _System.Diagnostics_ be a more appropriate namespace than _System_?

**Comment by marek-safar** [comment]
I like this and it'd be also useful for tools like IL linker which have to now uses `NotSupportedException` with a string explanation that the body is unreachable.

**Comment by bartonjs** [comment]
System.Diagnostics feels more appropriate to me.  In all the cases I'd see myself using it I currently have a Debug.Fail, then the exception so the compiler doesn't tell me my execution flow makes no sense.

If we end up doing a public ThrowHelper-type API for ArgumentNullException (#48573) then we'd probably want one here, too.

**Comment by FilipToth** [comment]
The only case where I'd use this is when I have an unexpected case in a switch statement of something, what I usually do is just throw a regular `System.Exception` with exception text being something like: "Unexpected <name>.". This API seems very niche to me. Could you provide some direct cases where using `UnreachableException` over just regular `Exception` would be useful. Also, I would certainly not go over all my previous code and change the exceptions.

But, for new code, I'd certainly consider using this exception type, as @marek-safar already mentioned, This would be good for some applications which now had to use `NotSupportedException`, I guess. Although, I do not think this should be a priority.

**Comment by GrabYourPitchforks** [comment]
> Could you provide some direct cases where using UnreachableException over just regular Exception would be useful.

@FilipToth Per earlier discussion, the best use cases seem to be debuggers, flow analyzers, and other design-time and diagnostics tools. I don't think anybody would go back and change their existing code to use this API unless they want the benefits these tools offer.

**Comment by bartonjs** [comment]
* This exception made us muse for a long time on wishing that we had better language support for showing that control won't come back. (General ThrowHelper problem)
* We didn't add a static Throw method yet, because of the ThrowHelper control flow problem
* We might want to get the runtime to consider it uncatchable, like StackOverflowException (or what @bartonjs remembers ThreadAbortException doing: you can catch it to log it, but it's being propagated unconditionally at the end of the catch block).
* Since the type is just a .NET N type (not netstandard2.0) the serialization ctor and attr aren't needed
* We discussed UnreachableException vs UnreachableCodeException.  We were split 50/50, so let the tie break go to the proposer
* We're approving it as deriving from SystemException on the assumption we'll give it special treatment.  If it's "just another exception" at the end of the day we should derive directly from Exception.

```C#
#nullable enable
using System.Runtime.Serialization;

namespace System
{
    public sealed class UnreachableException : SystemException
    {
        public UnreachableException()
            : base("The program executed an instruction that was thought to be unreachable.")
        {
        }

        public UnreachableException(string? message)
            : base(message)
        {
        }

        public UnreachableException(string? message, Exception? innerException)
            : base(message, innerException)
        {
        }
    }
}
```

**Comment by stephentoub** [comment]
> This exception made us muse for a long time on wishing that we had better language support for showing that control won't come back.

For reference:
https://github.com/dotnet/csharplang/issues/538

**Comment by GrabYourPitchforks** [comment]
@bartonjs Shouldn't this be under _System.Diagnostics_ as previously discussed?

**Comment by jkotas** [comment]
>  We might want to get the runtime to consider it uncatchable, like StackOverflowException

Stack overflow is hard fail fast. We do not allow any handling of it in managed code. (.NET Framework allowed handling stackoverflow exceptions using SQL hosting interfaces. We do not have those in .NET Core.)

> ThreadAbortException: you can catch it to log it, but it's being propagated unconditionally at the end of the catch block

Thread abort was not a simple uncatchable exception. The thread abort switched the thread into a special aborting mode, it was about much more than just rethrowing exception at the end of catch block.

We do not have concept of uncatchable exceptions in the runtime and I do not think we should be introducing it for this one.

The only difference between uncatchable exceptions and `Environment.FailFast` is that uncatchable exception would allow custom logging. The process is going to be unconditionally terminated in both cases anyway. If we want to make this situation uncatchable, but still allow custom logging for it, I think we may want to rather look at adding logging hook to `Environment.FailFast`.

**Comment by svick** [comment]
Personally I think this should not have any kind of uncatchable behavior. Consider a plugin system, like Roslyn analyzers: an `UnreachableException` thrown from a plugin means that the plugin has a bug, but that doesn't necessarily mean the whole process (Visual Studio, or its child process) should crash. It should be up to the plugin runner to decide what happens.

Also, there's already a somewhat similar type, `SwitchExpressionException`, that's thrown by a `switch` expression with unexpected input. Would it make sense to make `SwitchExpressionException` inherit from `UnreachableException`? Though this is probably not particularly valuable, since both of these exceptions shouldn't be caught by name.

**Comment by GSPP** [comment]
> https://imgur.com/gallery/C9qm57g

What would happen if a single request in a web app encounters such an exception? Would thread or process be torn down? That's unacceptable. The application must keep running and keep serving traffic.

Bugs happen all the time. Even state corrupting ones. We can't tear down the process when that happens.

Web apps also rarely experience true state corruption because, usually, requests are isolated and the request state is cleanly thrown away at the end of request processing.

**Comment by GSPP** [comment]
For the same reason, it is not possible to use `Debug.Assert` in production applications. It either ignores the assert in release builds or pops up a dialog or crashes the process. In a concurrent, multi-user, highly-available application, these things are non-starters.

[This is why I suggested an AssertFailedException.](https://github.com/dotnet/runtime/issues/16570) The design concept is very much like this `UnreachableException`.

It's simply an exception that anyone can use to their liking. There is no runtime integration. Nothing in the framework reacts specially to that.

But we *can* standardize the community on using these two exception types to expect common semantics. I consider that to be valuable.

**Comment by terrajobst** [comment]
> @bartonjs Shouldn't this be under _System.Diagnostics_ as previously discussed?

One suggestion was `System.Diagnostics.CodeAnalysis`, but maybe that's a bad fit becaust it contains the attributes for helping code analysis, this feels more like a plumbing type. Personally, I think I'm leaning towards `System`.

**Comment by deeprobin** [comment]
Why does this need a constructor for Inner Exceptions? Is there any use case to nest Exceptions in UnreachableExceptions?

**Comment by terrajobst** [comment]
> Why does this need a constructor for Inner Exceptions? Is there any use case to nest Exceptions in UnreachableExceptions?

All exceptions have these constructors; it's the standard pattern.

**Comment by AraHaan** [comment]
Could this type be used for those like me who want to use it at runtime as well (to notify any application that something unexpected happened inside of one of it's dependencies)? Currently I have mine stuck between these:

- ns2.0 only dependency:
  - Throw Exception (or NotSupportedException if it's available)
- net5.0 only dependency:
  - Throw NotSupportedException
- net7.0 only dependency:
  - Throw UnreachableException (I think this is targeting .NET 7)

**Comment by GrabYourPitchforks** [comment]
@AraHaan There's nothing terribly unique about this exception type from a runtime perspective. You should be able to use reflection to instantiate it just as you would any other type, cast to the base `Exception` type, then _throw_ to your heart's content. :)

**Comment by deeprobin** [comment]
Happy to assign me :smile:

**Comment by bartonjs** [comment]
The PR observed that there were still some floating points.  Marking as review-ready and blocking so we discuss them today to unblock the PR.

**Comment by deeprobin** [comment]
> The PR observed that there were still some floating points. Marking as review-ready and blocking so we discuss them today to unblock the PR.

Great 👍🏼!

Is this a small change (i.e. just implement the API + tests) or are there no other changes that need to be made?

**Comment by bartonjs** [comment]
We seem to have hit the most agreeable (perhaps "least disagreeable") position with System.Diagnostics, on the basis that it's rather like an assert (`System.Diagnostics.Debug.Assert`); and based on @jkotas feedback, the exception isn't really special... so `: Exception` instead of `: SystemException`.

```C#
namespace System.Diagnostics
{
    public sealed class UnreachableException : Exception
    {
        public UnreachableException()
            : base("The program executed an instruction that was thought to be unreachable.")
        {
        }

        public UnreachableException(string? message)
            : base(message)
        {
        }

        public UnreachableException(string? message, Exception? innerException)
            : base(message, innerException)
        {
        }
    }
}
```

**Comment by deeprobin** [comment]
Since this is only a small change, I'm happy to work on that issue.

**Comment by stephentoub** [comment]
> Since this is only a small change, I'm happy to work on that issue.

There's already an in-flight PR for it.

**Comment by jstaro** [comment]
I know this is a bit late, but I was surprised the discussion didn't float the idea that this exception (at least in my mind) is quite similar to `NotImplementedException` which lives in the `System` namespace.
