### ISSUE TITLE
Replace Dictionary<,>.Keys.Contains with ContainsKey

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/runtime#35343]
This is a proposal for a new analyzer/codefix for:

```c#
// given
Dictionary<int, string> dic = ...;

dic.Keys.Contains(1);
dic.Values.Contains("");

// Could instead be
dic.ContainsKey(1);
dic.ContainsValue("");
```

I found this code in some design-time build targets today.

**EDIT** I'd previously incorrectly stated that the former form was O(N), but `System.Linq.Enumerable.Contains` does type test for `ICollection<>` and delegate to `ICollection<>.Contains`, which is also O(1). There is some overhead associated with that however, which could be avoided.

**Comment by Evangelink** [comment]
Sorry for the rush on implementing something! To be honest, I am a little lost with which issue is going where. As an external user, it feels more natural to have _all_ of the analyzers in one place instead of having some in vs-threading some here, some in roslyn and others in roslyn-analyzers. Just my 2 cents.

**Comment by bartonjs** [comment]
It's a reasonable suggestion in the Performance category.

Because Dictionary's KeyCollection and ValueCollection types are lazy, there's not a whole lot of perf difference from the concrete type.  The constructors just save a reference to the dictionary and the Contains methods forward to ContainsKey/ContainsValue (as appropriate).

```C#
dict.Keys.Contains(foo);
```

is roughtly equivalent to

```C#
new object();
dict.ContainsKey(foo);
```

though the latter example does need to work in two more dereference/invocations to add the extra couple of CPU cycles to the mix.

Is there a good way to avoid hard-coding specific dictionary types here?

* Invocation of a single-parameter method named "Contains" that returns a Boolean.
* The parent expression is a property invocation of `IDictionary<TKey,TValue>.Keys` (or `Values`) or `IReadOnlyDictionary<TKey,TValue>.Keys` (or `Values`) where TKey or TValue (as appropriate) is the (exact) same type (after generic substitution) as the parameter for the Contains method
* Fixer replaces `a.Keys.Contains(b)` with `a.ContainsKey(b)`, and `c.Values.Contains(d)` with `c.ContainsValue(d)`

It becomes a lot more valuable when it's through the interfaces, since the Contains method would likely be the item-walking version from `System.Linq.Enumerable`.


The trickiest case is probably this helper method:

```C#
private static bool IsRelevant<T>(T candidate, IReadOnlyDictionary<string, T> context)
{
    return context.Values.Contains(candidate);
}
```

since it involves an analysis with a partially bound generic (it's probably not really any trickier than a concrete example, but generic type parameter symbols may have some interesting quirks to them in the symbol tree).

This would probably be an IDE suggestion that we may kick up to a bigger warning via TFM opt-in.

**Comment by Mrnikbobjeff** [comment]
I would like to have this assigned to me. I just completed my work on this analyzer including the code fix provider. One flaw still unadressed is the fact that only Dictionary<T,K> has a ContainsValue method, the interfaces do not. This is the last thing I still need to implement.

**Comment by carlossanlop** [comment]
@NewellClark thanks for starting working on this. I'm trying to assign to you but I can't for some reason, but consider it yours.

@Mrnikbobjeff apologies for not assigning this to you when you requested it, but your offer is appreciated. We have many more analyzers marked as up-for-grabs and would love to get your help on those others too.

**Comment by jeffhandley** [comment]
@NewellClark We figured out why we cannot assign this to you.  You must comment on the issue before you show up in the assignees list.

**Comment by NewellClark** [comment]
@jeffhandley Gotcha.

**Comment by stephentoub** [comment]
Can this be closed (https://github.com/dotnet/roslyn-analyzers/pull/4687)?

**Comment by buyaa-n** [comment]
Yes, closing
