### ISSUE TITLE
Xamarin frameworks assume support for types not in .NETCoreApp today

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#35401]
Not all required assemblies are included in self-contained runtime packs. For example mscorlib.dll has assembly reference to `System.Security.Permissions` but that assembly is not included.

**Comment by jkotas** [comment]
`mscorlib.dll` is a compat shim. It is by design that it has references to assemblies outside of netcoreapp.

**Comment by ericstj** [comment]
Correct, this is by design.

**Comment by ericstj** [comment]
I chatted with @marek-safar about this and the issue isn't so much the dangling references, but instead that TFMs like `Xamarin.IOS` which are compatible with `net5-ios` support types which are not present today in the `net5` shared framework.  

This isn't all that dissimilar from the scenario where `net4x` is compatible with `netcoreapp` and has many types which are not present inbox.  In that case we tell folks that they can reference the compatibility pack or individual packages that contain those types in order to bring them in if they need them.

The fact that we have an `mscorlib` inbox to facilitate this isn't really an issue.

So this issue should track what is done for the xamarin frameworks about the missing types.  Some of the options I can imagine:
1. Do nothing and tell folks to do the same thing on these frameworks as we tell folks when using .NETFramework assemblies with .NETCoreApp
2. Add those types to the runtime package only for the frameworks compatible with past Xamarin frameworks.  To do this libraries can build with `IsNetCoreAppRef`=false and `IsNetCoreApp` conditional on platform as we did previously for things like Registry https://github.com/dotnet/corefx/pull/19780.  This is safe to do now since the host can decide between App and shared framework and no longer assumes that the app always wins.  We'd have to make sure to omit any of these from the PlatformManifest.txt file since not all platforms will carry them. 
3.  Add those types to both the ref and runtime pack that is specific for these new frameworks, eg in the `net5-ios` - specific layer rather than `net5` layer.

@terrajobst is this something you've already spec'ed as part of the TFM convergence?

**Comment by marek-safar** [comment]
I think because net5-{mobile} TFMs are compatible with existing SXamarin TFMs as defined at https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#design the option 1 is not feasible.

**Comment by ericstj** [comment]
@marek-safar why is option 1 not feasible?  I'm not yet seeing how this is different than `.NETFramework` where the same compatibility relationship exists.

**Comment by marek-safar** [comment]
>  I'm not yet seeing how this is different than .NETFramework where the same compatibility relationship exists.

I didn't realize the `netcoreapp` TFM derives from `net` TFM. What is the user experience today for example when someone migrates its project to .NET Core and runs AOT compilation which fails due to missing OOB package reference?

**Comment by jkotas** [comment]
The CoreCLR AOT compilation is resilient to this situation. It will succeed and you will get the same failure at runtime as you get with the JIT.

**Comment by terrajobst** [comment]
> > I'm not yet seeing how this is different than .NETFramework where the same compatibility relationship exists.
> 
> I didn't realize the `netcoreapp` TFM derives from `net` TFM.

It doesn't derive from it; `net4x` is is a fallback TFM when NuGet can't find assets for .NET Core/.NET Standard. NuGet will then the re-select assets, pretending that that the project you're trying to install into being .NET Framework. When this succeeds the user will get warning [NU1701](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701):

> Package 'packageId' was restored using 'TargetFrameworkA' instead the project target framework 'TargetFrameworkB'. This package may not be fully compatible with your project.

We refer to this experience as the [.NET Framework compatibility mode](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-framework-compatibility-mode).

For Xamarin, we have two options:

1. We treat it the same as `netcoreapp3.1` and earlier, i.e. `xamarin.xxx` is considered the earlier version of `net5.0-xxx`. No warning is giving and the API surface of `net5.0-xxx` is assumed to be a superset.
2. We treat it the same as `net4x` and earlier, i.e. it's considered a compat fallback. Users will get a warning as some stuff is expected to break.

When I wrote the spec my working assumption was that we're pursuing (1), because the namespace renamed won't affect the OS bindings (only app model things such as Xamarin.Forms). Assuming we still like (1), then I'd:

1. Consider adding the missing dependencies to `net5.0`.
2. Consider adding the missing dependencies to `net5.0-xxx`
3. Consider building a NuGet package akin to the Microsoft.Windows.Compatibility where a meta package just bundles up all the missing APIs in a single NuGet package.
4. Consider combining option (2) with tooling that automatically adds the reference whenever a package is installed that was built for the `xamarin.xxx` TFM.

The nice characteristic of (1)/(2) is that it makes things just work, with no moving pieces in tooling. (3)+(4) are nice because they avoid the legacy being added to the platform. We could isolate the legacy additions to Xamarin platform but I think it's weird to have components that are shared between two platforms but that component isn't part of `net5.0`, but strictly speaking that's not an issue. Parties targeting `net5.0` can still get those components by referencing the corresponding NuGet packages.

@ericstj @marek-safar: do we have a list of the missing APIs? Are there any APIs that don't exist on .NET Core at all today (i.e. we don't have a compat NuGet package for)? Based on the way the issue was phrased it sounds like the only thing that was noticed was dangling type forwards, but for all of those we have a .NET Standard NuGet package, so we should be covered.

**Comment by ericstj** [comment]
> @ericstj @marek-safar: do we have a list of the missing APIs?

I don't have this, but imagine it's a diff of any overlapping assembly names between the latest Xamarin targeting pack and the net5.0 ref-pack.  @tarekgh may have this.

One thing to remember is that all of the API that is in this set was already explicitly excluded from .NETStandard which included considering Mono and Xamarin.  We shouldn't be resetting those decisions without some new data.  It's possible we should be projecting those decisions on the TFM design and model things instead as fallback instead of actually compatible.

**Comment by marek-safar** [comment]
> Consider adding the missing dependencies to net5.0.

This looks to me like the most natural option, especially as the missing assembly is like 90k.

> Consider adding the missing dependencies to net5.0-xxx

This feels a bit odd as we are pushing the implementation detail of mscorlib.dll to SDKs and we assume there will be net5.0 TFM which might not be the case for e.g. WASM

> Consider building a NuGet package akin to Microsoft.Windows.Compatibility where a meta package just bundles up all the missing APIs in a single NuGet package.

How would that work? There is no missing API we need but the internal implementation of netcoreapp runtime pack depends on OOB package.

Another option is to change the implementation of mscorlib.dll to not depend on OOB package (e.g. throwing PNSE for code paths which bring the dependency).

> Based on the way the issue was phrased it sounds like the only thing that was noticed was dangling type forwards

Correct but that still means the user experience today is pretty bad for projects migrating to net5 as the default behaviour is to fail during build/publish due to missing assembly reference.

**Comment by akoeplinger** [comment]
I took a look at which dangling assembly references exist for the shim assemblies, ordered by how often an assembly is referenced:

```
System.Security.Permissions.dll
    System.Configuration.dll
    System.Data.dll
    System.Drawing.dll
    System.Net.dll
    System.Security.dll
    System.ServiceProcess.dll
    System.Transactions.dll
    System.dll
    WindowsBase.dll
    mscorlib.dll

System.Windows.Extensions.dll
    System.Drawing.dll
    System.Security.dll
    System.dll

System.Configuration.ConfigurationManager.dll
    System.Configuration.dll
    System.Drawing.dll
    System.dll

System.Diagnostics.EventLog.dll
    System.Core.dll
    System.dll

System.Diagnostics.PerformanceCounter.dll
    System.Core.dll
    System.dll

System.Threading.AccessControl.dll
    System.dll
    mscorlib.dll

System.Data.Odbc.dll
    System.Data.dll

System.Data.OleDb.dll
    System.Data.dll

System.Data.SqlClient.dll
    System.Data.dll

System.Drawing.Common.dll
    System.Drawing.dll

System.Security.Cryptography.Pkcs.dll
    System.Security.dll

System.Security.Cryptography.ProtectedData.dll
    System.Security.dll

System.Security.Cryptography.Xml.dll
    System.Security.dll

System.ServiceModel.Syndication.dll
    System.ServiceModel.Web.dll

System.ServiceProcess.ServiceController.dll
    System.ServiceProcess.dll

System.CodeDom.dll
    System.dll

System.IO.Ports.dll
    System.dll

System.IO.Packaging.dll
    WindowsBase.dll

Microsoft.Win32.SystemEvents.dll
    System.dll

as.dll
    System.Runtime.CompilerServices.Unsafe.dll

System.Runtime_1.dll
    System.Runtime.CompilerServices.Unsafe.dll

windowsruntime.dll
    System.Runtime.WindowsRuntime.dll

Windows.dll
    System.Runtime.WindowsRuntime.dll
```

**Comment by jkotas** [comment]
> Correct but that still means the user experience today is pretty bad for projects migrating to net5

The same problem exists for .NET Framework -> .NET Core migrations. We have done multiple iterations on this experience, incorporating customer feedback. I believe that the customers are reasonably happy with the current experience. I have not seen it mentioned as a problem in the feedback we are getting.

> We shouldn't be resetting those decisions without some new data. 

+1. It would be useful to get some data about how often we expect this to problem for Xamarin apps, and which APIs are expected to cause the most problems.

> > Consider building a NuGet package akin to Microsoft.Windows.Compatibility where a meta package just bundles up all the missing APIs in a single NuGet package.

> How would that work? There is no missing API we need but the internal implementation of netcoreapp runtime pack depends on OOB package.

The same way as it works for .NET Core today. The legacy forwarders do not have any code. I would not really consider them internal implementation.

> It might be a good option if the missing assemblies are small.

The sum of them is not small at all.

**Comment by marek-safar** [comment]
> It would be useful to get some data about how often we expect this to problem for Xamarin apps

This is not about APIs but about additional tooling run for Xamarin workloads. I believe the same problem could happen with .NET Core they are just on rare path for now. We could fix the tooling to ignore the missing assembly references but that's I think not ideal as it's more hiding the problem than fixing it.

> The same way as it works for .NET Core today. The legacy forwarders do not have any code.

I meant how we'll get the additional assemblies to the build? @terrajobst proposed to create Compatibility package but that package would not have any public API only set of implementation assemblies. I'm not sure how that would flow through the build to get them to the output dir all the time.

> The sum of them is not small at all.

Not at the moment but looking at the list we should probably be able to cut it noticeably. I don't think System.Data.Odbc or System.IO.Ports or even System.Diagnostics.PerformanceCounter will ever work on mobile.

Similarly, we never shipped System.Runtime.WindowsRuntime or System.Configuration with Xamarin so these legacy dependencies are redundant from a compatibility standpoint.

Essentially we use .NET Framework legacy shims for Xamarin legacy mode and they have different API surface so we could cut some of them.

**Comment by danmosemsft** [comment]
@marek-safar is there 5.0 work here? Seems we we can move to 6.0.

**Comment by krwq** [comment]
@marek-safar is this issue still valid? It's been open for a while already. I assume it's not needed for 6.0?

**Comment by filipnavara** [comment]
I've one thing for analysis on my backlog that is likely related to this. In our app we consume a 3rd-party .NET Framework class library (IndependentSoft.PST.dll). The library has reference to `mscorlib` and fails to load when compiled into `net6.0-macos` app. I was planning to make a self-contained sample to describe the problem.

**Comment by filipnavara** [comment]
Here's a self-contained sample showing that this is still relevant with .NET 6 Preview 6: [Archive.zip](https://github.com/dotnet/runtime/files/6840528/Archive.zip)

Build with `dotnet build` (workloads need to be installed, `maui-check` works well for that). Run with `./bin/Debug/net6.0-macos/osx-x64/netfx-ref.app/Contents/MacOS/netfx-ref`. Output:
```
2021-07-19 13:51:38.577 netfx-ref[68355:1715609] Could not find `System.Security.Permissions` referenced by assembly `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`.
2021-07-19 13:51:38.578 netfx-ref[68355:1715609] Could not find `System.Security.Permissions` referenced by assembly `netfx-lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
2021-07-19 13:51:38.578 netfx-ref[68355:1715609] Could not find `System.Security.Permissions` referenced by assembly `netfx-ref, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
2021-07-19 13:51:38.584 netfx-ref[68355:1715609] 
Unhandled Exception:
System.IO.FileNotFoundException: 
IO_FileName_Name, System.Security.Permissions
2021-07-19 13:51:38.588 netfx-ref[68355:1715609] Unhandled managed exception:  (System.IO.FileNotFoundException)
```

**Comment by marek-safar** [comment]
@filipnavara the same error would happen with console app and such reference, right?

**Comment by jkotas** [comment]
If you are referencing .dlls directly, you are on your own. You have to know what you are doing and that it is going to be compatible.

If you reference NuGet packages that are potentially incompatible, you will get warnings like:
```
warn : NU1701: Package 'Microsoft.AnalysisServices.AdomdClient.retail.amd64 19.22.5' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net6.0'. This package may not be fully compatible with your project.
```

**Comment by filipnavara** [comment]
I am aware of the NuGet warning although it doesn't really show the solution. I'll retry with console app and CoreCLR. Just pointing out the default experience is crappy. In fact, why ship mscorlib.dll at all when it literally never works in this configuration?! I am not necessarily asking to get it fixed for .NET 6 since it's late and workaround exists, just pointing out the current situation is not great developer experience.

**Comment by ericstj** [comment]
> In fact, why ship mscorlib.dll at all when it literally never works in this configuration?!

mscorlib does work in this configuration.  Both the compiler and runtime are tolerant to dangling typeforwards.  Nothing in the tooling should be producing any diagnostics about this (if it is, that needs to be fixed).  By shipping one copy we avoid having to have multiple different copies floating around and trying to figure out which is the *right* one for various combinations of references.

**Comment by filipnavara** [comment]
> runtime are tolerant to dangling typeforward

Apparently MonoVM is not. The library in the example is empty library made with `dotnet new classlib` and modified to target `net40`. It does not reference any of the missing types or assemblies.

**Comment by marek-safar** [comment]
Looping in @lambdageek and @vargaz for thoughts about delay loading type-forwarders.

**Comment by filipnavara** [comment]
Recompiling the `net6.0-macos` test app with CoreCLR (`dotnet build /p:UseMonoRuntime=false`) still produces the runtime error:
```
2021-07-20 04:50:36.855 netfx-ref[70121:1794360] Could not find `System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` referenced by assembly `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`.
2021-07-20 04:50:36.857 netfx-ref[70121:1794360] Could not find `System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` referenced by assembly `netfx-lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
2021-07-20 04:50:36.857 netfx-ref[70121:1794360] Could not find `System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` referenced by assembly `netfx-ref, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
```

Removing all the Xamarin code and targeting console `net6.0` does work. Code:
```
var c = new netfx_lib.Class1();
System.Console.WriteLine("No crash");
```
Output:
```
filipnavara@Filips-MacBook-Air netfx-ref % dotnet run
No crash
```

**Comment by vargaz** [comment]
x.ios seems to load it explicitly from ObjCRuntime.Runtime:CollectReferencedAssemblies ().

**Comment by rolfbjarne** [comment]
> Removing all the Xamarin code and targeting console `net6.0` does work.

What if you enable the linker (`/p:PublishTrimmed`) and/or make it self-contained?

**Comment by filipnavara** [comment]
@rolfbjarne I gave it couple of tries but I was unable to get anything working. The assembly enumeration path is triggered both from `NSApplication.Init` and `xamarin_register_entry_assembly` run from `xamarin_main`.

The call to `xamarin_register_entry_assembly` is guarded by `xamarin_supports_dynamic_registration` which I tried to set using `<MonoBundlingExtraArgs>--optimize=+remove-dynamic-registrar</MonoBundlingExtraArgs>` but unsuccessfully due to the following error:
```
ILLINK : warning MM2003: Option '--optimize=remove-dynamic-registrar' will be ignored since it's only applicable to iOS, watchOS, tvOS. [/Users/filipnavara/Downloads/gc/Archive (1)/netfx-ref.csproj]
```

`NSApplication.IgnoreMissingAssembliesDuringRegistration` doesn't work either since `xamarin_register_entry_assembly` is call before any user code and hence there's no way to set it early enough.

The trimming with `/p:PublishTrimmed` didn't make any difference either.

**Comment by rolfbjarne** [comment]
> @rolfbjarne I gave it couple of tries but I was unable to get anything working.

I meant enabling the linker / self-contained for a plain `net6.0` app, not a Xamarin app.

**Comment by filipnavara** [comment]
Ah, that... self-contained publish of the `net6.0` app still produces working result. `System.Security.Permissions.dll` doesn't exist in the output.

**Comment by rolfbjarne** [comment]
> Ah, that... self-contained publish of the `net6.0` app still produces working result. `System.Security.Permissions.dll` doesn't exist in the output.

Does the linker succeed if you enable trimming?

**Comment by filipnavara** [comment]
> Does the linker succeed if you enable trimming?

Yes

```
filipnavara@Filips-MacBook-Air netfx-ref % rm -fr bin obj                                                                                                                          
filipnavara@Filips-MacBook-Air netfx-ref % dotnet build /t:Publish /p:PublishTrimmed=true
Microsoft (R) Build Engine version 17.0.0-preview-21329-01+1b7661f36 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/filipnavara/Projects/netfx-ref/netfx-ref.csproj (in 209 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  netfx-ref -> /Users/filipnavara/Projects/netfx-ref/bin/Debug/net6.0/osx-x64/netfx-ref.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  netfx-ref -> /Users/filipnavara/Projects/netfx-ref/bin/Debug/net6.0/osx-x64/publish/

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.61
filipnavara@Filips-MacBook-Air netfx-ref % /Users/filipnavara/Projects/netfx-ref/bin/Debug/net6.0/osx-x64/publish/netfx-ref 
No crash
filipnavara@Filips-MacBook-Air netfx-ref % ls /Users/filipnavara/Projects/netfx-ref/bin/Debug/net6.0/osx-x64/publish/
Microsoft.Win32.Primitives.dll				System.Reflection.Metadata.dll				libSystem.Security.Cryptography.Native.OpenSsl.dylib	mscorlib.dll
System.Collections.Immutable.dll			System.Runtime.dll					libclrjit.dylib						netfx-lib.dll
System.Collections.dll					createdump						libcoreclr.dylib					netfx-ref
System.Console.dll					libSystem.Globalization.Native.dylib			libdbgshim.dylib					netfx-ref.deps.json
System.Diagnostics.StackTrace.dll			libSystem.IO.Compression.Native.dylib			libhostfxr.dylib					netfx-ref.dll
System.IO.Compression.dll				libSystem.Native.dylib					libhostpolicy.dylib					netfx-ref.pdb
System.IO.MemoryMappedFiles.dll				libSystem.Net.Security.Native.dylib			libmscordaccore.dylib					netfx-ref.runtimeconfig.json
System.Private.CoreLib.dll				libSystem.Security.Cryptography.Native.Apple.dylib	libmscordbi.dylib
```

**Comment by joperezr** [comment]
@marek-safar is there something from this issue that we have to fix for 6.0.0? If yes, are you tracking that work? Or if nothing to fix for 6.0.0, is it ok to change the milestone of this issue?

**Comment by filipnavara** [comment]
The Xamarin issue with bailing on missing assemblies was resolved [today]. Now it behaves same as .NET on desktop.

**Comment by lambdageek** [comment]
(closing the loop on Mono runtime behavior)

> > runtime are tolerant to dangling typeforward
> 
> Apparently MonoVM is not. The library in the example is empty library made with `dotnet new classlib` and modified to target `net40`. It does not reference any of the missing types or assemblies.



> Looping in @lambdageek and @vargaz for thoughts about delay loading type-forwarders.

We shouldn't be resolving type-forwarders unnecessarily.

Here is a console app (that uses netfx-lib.dll from Filip's repro [above](https://github.com/dotnet/runtime/issues/35401#issuecomment-882487608).

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">osx-x64</RuntimeIdentifier>
    <UseMonoRuntime>true</UseMonoRuntime>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="netfx-lib.dll" />
  </ItemGroup>

</Project>
```

```

bool isMono = typeof(object).Assembly.GetType("Mono.RuntimeStructs") != null;
Console.WriteLine($"Hello World {(isMono ? "from Mono!" : "from CoreCLR!")}");
var c = new netfx_lib.Class1();
```

This prints:

```
Hello World from Mono!
```
and runs without errors.  `MONO_LOG_LEVEL=debug MONO_LOG_MASK=asm dotnet run` shows that we load `mscorlib.dll` from the `bin/` folder, but don't attempt to load any non-existent assemblies.

**Comment by joperezr** [comment]
@marek-safar ping 😄

**Comment by lambdageek** [comment]
@joperezr Marek is OOF for a couple weeks.

I don't believe there's any 6.0 work here.  moving the milestone.

**Comment by marek-safar** [comment]
Closing as it seems there is general consensus that the .NET Core behaviour for the legacy assemblies is reasonable and .NET6 mobile workloads have added the references automatically to simplify the migration.
