### ISSUE TITLE
'build.cmd -subset clr -arch x86' fails

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#35487]
Currently, running `build.cmd -subset clr -arch 86` locally fails with the following:
```
D:\tagoo\Repos\runtime\.dotnet\sdk\5.0.100-preview.4.20202.8\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3030: Could not copy the file "D:\tagoo\Repos\runtime_base\artifacts\obj\coreclr\dotnet-pgo\x86\Debug\dotnet-pgo.exe" because it was not found. [D:\tagoo\Repos\runtime_base\src\coreclr\src\tools\dotnet-pgo\dotnet-pgo.csproj]
D:\tagoo\Repos\runtime\.dotnet\sdk\5.0.100-preview.4.20202.8\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3030: Could not copy the file "D:\tagoo\Repos\runtime_base\artifacts\obj\coreclr\R2RTest\x86\Debug\R2RTest.exe" because it was not found. [D:\tagoo\Repos\runtime_base\src\coreclr\src\tools\r2rtest\R2RTest.csproj]
D:\tagoo\Repos\runtime\.dotnet\sdk\5.0.100-preview.4.20202.8\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3030: Could not copy the file "D:\tagoo\Repos\runtime_base\artifacts\obj\coreclr\R2RDump\x86\Debug\R2RDump.exe" because it was not found. [D:\tagoo\Repos\runtime_base\src\coreclr\src\tools\r2rdump\R2RDump.csproj]
```

x64 does not have this problem. The projects are all building successfully but no `*.exe` is being created or placed next to the respective `*.dll`

**Comment by tannergooding** [comment]
A similar issue exists for `crossgen2`:
```
D:\tagoo\Repos\runtime\.dotnet\sdk\5.0.100-preview.4.20202.8\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3030: Could not copy the file "D:\tagoo\Repos\runtime\artifacts\obj\coreclr\crossgen2\x86\Debug\win-x86\crossgen2.exe" because it was not found. [D:\tagoo\Repos\runtime\src\coreclr\src\tools\crossgen2\crossgen2\crossgen2.csproj]
```

**Comment by filipnavara** [comment]
Is the `-arch 86` instead of `-arch x86` a typo?

**Comment by tannergooding** [comment]
Yes

**Comment by hypeartist** [comment]
@tannergooding I have tried today to make separate builds:

```
call build.cmd -subset Clr -os Windows_NT -arch x86 -configuration Debug -runtimeConfiguration Debug
call build.cmd -subset Clr -os Windows_NT -arch x86 -configuration Release -runtimeConfiguration Release
```

and they finished successfully (both .exe and .dll stuff in place)

PS: Can't check the all-in-one building since storage free space limits, sorry

**Comment by tannergooding** [comment]
Still hitting this. cc @ViktorHofer

**Comment by john-h-k** [comment]
Also hitting this with the exact same build command

**Comment by ViktorHofer** [comment]
cc @jashook @trylek

**Comment by trylek** [comment]
@tannergooding, @john-h-k - hmm, just tried this on a freshly synced enlistment (after deleting the artifacts folder) and the command

<pre>
build.cmd -subset clr -arch x86
</pre>

passed fine for me. I have uploaded the log file under

https://gist.github.com/trylek/608c31a54d653eddbed3e743f6a96a5b

I'm not sure what can be going on but the inability to reproduce this locally makes me wonder whether the issue may be related to some stale artifacts in your repo clone, frankly speaking we're totally lame when it comes to rebuilding over pre-generated artifacts after syncing.

I apologize for the inconvenience, this is what I'm usually doing when hitting similar issues in my git clones of the runtime repo (ordered from the least annoying to the most annoying, retrying the command after each step):

1) Deleting the artifacts folder
2) git clean -xdf
3) git clone the repo to a new folder.

If the problem still persists after all these steps, could you please also share the build log from the command so that we can try to compare them and hopefully get further insight into what may be causing the weird behavioral variation?

Thanks for your patience

Tomas

**Comment by john-h-k** [comment]
@trylek i'll give that a shot thanks - possibly worth noting this was my first time building for x86, so the only artifacts were `Windows_NT.x64.<Debug&Release>`

**Comment by trylek** [comment]
@john-h-k - I see, that makes step 1 probably superfluous - on the other hand, packages are also located under artifacts and one especially annoying group of problems happens when some nuget dependencies change and packages become stale. Of course, packages should be versioned and all that, I know, but you know... I did hit this in the past.

**Comment by tannergooding** [comment]
I can repro even from a new enlistment.
I'll collect a log and share in a bit.

**Comment by trylek** [comment]
@tannergooding - great, thank you! I'll also try this out off a fresh enlistment just to be sure.

**Comment by trylek** [comment]
Hmm, still no repro, passed just fine on a brand new enlistment. I'm getting really curious what weird variation between our environments may be causing this.

**Comment by tannergooding** [comment]
It looks to repro definitively if you `.\build.cmd -subset clr -arch x64` and then `.\build.cmd -subset clr -arch x86` immediately after.

It appears to do with the version of the .NET SDK that is downloaded. Likewise, if you have two enlistments and you do `.\build.cmd -subset clr -arch x64` and then do a `.\build.cmd -subset clr -arch x86` in the second enlistment after the first completes, you can sometimes hit the same issue.
The second enlistment will pull down the .NET SDK but it will end up locking and using the `dotnet.exe` from the first enlistment (I'd guess due to one of the build servers still being up and about).

**Comment by trylek** [comment]
Hmm, just tried that, still green :-(. Kudos for narrowing down the issue, would you mind trying to grab a log of the failed type of build? I'm somewhat surprised that a particular version of dotnet.exe should affect this; after all, it should only be used for Roslyn compilation and for execution of the few managed assemblies in CoreCLR, none of which are actually getting executed in clr build today as we're still crossgenning the System.Private.Corelib assembly with the "old" native Crossgen and we're certainly not running R2RDump or R2RTest in CoreCLR build; not so sure about the PGO tooling for instance.

**Comment by tannergooding** [comment]
I'm no longer able to repro after moving forward to the latest master, so it may have been a point-in-time issue.
Will reopen and share logs if I hit it again in the future.

**Comment by trylek** [comment]
Thanks for sharing; I've been also thinking about suggesting to wait for Viktor to land the bulk infra rollout change as that also tweaks various package versions and whatnot. One way or another it's great to hear you're unblocked for now, certainly feel free to reopen if it happens again and hopefully we'll catch it then!
