### ISSUE TITLE
Build test machine images step fails in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#35507]
https://dev.azure.com/dnceng/public/_build/results?buildId=618837&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=76467409-274e-589c-5c88-4286504c504b&l=1311

Build pipeline: `runtime-libraries enterprise-linux`

```
Err:131 https://apt.kitware.com/ubuntu bionic/main amd64 cmake-data all 3.17.1-0kitware1
  Could not connect to apt.kitware.com:443 (66.194.253.19), connection timed out
Err:132 https://apt.kitware.com/ubuntu bionic/main amd64 cmake amd64 3.17.1-0kitware1
  Unable to connect to apt.kitware.com:https:
Fetched 188 MB in 30s (6193 kB/s)
E: Failed to fetch https://apt.kitware.com/ubuntu/pool/main/c/cmake/cmake-data_3.17.1-0kitware1_all.deb  Could not connect to apt.kitware.com:443 (66.194.253.19), connection timed out
E: Failed to fetch https://apt.kitware.com/ubuntu/pool/main/c/cmake/cmake_3.17.1-0kitware1_amd64.deb  Unable to connect to apt.kitware.com:https:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Service 'linuxclient' failed to build: The command '/bin/sh -c echo "APT::Acquire::Retries \"10\";" > /etc/apt/apt.conf.d/80-retries &&     apt-get update &&     apt-get install -y --no-install-recommends apt-transport-https ca-certificates gnupg software-properties-common wget &&     wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - &&     apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' &&     wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | apt-key add - &&     apt-add-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' &&     apt-get update &&     apt-get install -y --no-install-recommends cmake llvm-9 clang-9 lldb-6.0 liblldb-6.0-dev libunwind8 libunwind-dev gettext libicu-dev liblttng-ust-dev libssl-dev libnuma-dev libkrb5-dev locales &&     locale-gen en_US.UTF-8 &&     update-locale LANG=en_US.UTF-8' returned a non-zero code: 100
```

@davidsh Can we make apt-get install retry-able?

**Comment by karelz** [comment]
@davidsh can you please take a look?

**Comment by davidsh** [comment]
>@davidsh Can we make apt-get install retry-able?

I did make apt-get install retry-able. Up to 10 retries. :)

https://github.com/dotnet/runtime/blob/a9626b9d3e1f52234c6864cc5d9f11252fa5d3e4/src/libraries/Common/tests/System/Net/EnterpriseTests/setup/linuxclient/Dockerfile#L13

I suspect that there is a problem with the upstream Ubuntu package servers. I've seen this before but usually having a retry count of 10 always worked.

I'll look into this and see if making it more than 10 helps.

Longer-time, I was thinking of cache the images used for these dockerfiles. Instead of always building this custom Ubuntu image with multiple apt-get installs, it would be better to just do that once and have this custom docker base image pre-built. That would also speed up this enterprise test pipeline (although it currently only take 25 minutes for the whole thing).

**Comment by davidsh** [comment]
Right now, the pipeline is working fine. So I suspect this was a transient issue with the external Ubuntu package feed servers:
![image](https://user-images.githubusercontent.com/7684835/81247012-cab2bb00-8fcd-11ea-951e-02e0d7392859.png)

**Comment by jkotas** [comment]
kitware feed is no longer used by this dockerfile.
