### ISSUE TITLE
Static nethost should ship symbols

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#35521]
The static version of [`nethost`](https://github.com/dotnet/runtime/blob/master/src/installer/corehost/cli/nethost/CMakeLists.txt) (i.e. `libnethost.lib`) should also ship corresponding symbols (i.e. PDB). This is needed so that when the library is linked into the final binary that binary's PDBs can be complete.

At present, when linking against `libnethost.lib` the [4099](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-warning-lnk4099) linker warning needs to be suppressed at a minimum and in the worse case can't be debugged very well.

/cc @vitek-karas @swaroop-sridhar

**Comment by MSLukeWest** [comment]
I am hitting this issue with a new tool we're creating that uses libnethost.lib.  So I'm unable to build without warnings until this issue is resolved.  Right now I get 7 warnings like this:

libnethost.lib(nethost.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(nethost.obj)' or at '<Path to Project>\Release\libnethost.pdb'; linking object as if no debug info
