### ISSUE TITLE
Utf8Parser.Decimal.TryParse, outside minimum range, incorrect success state

### ISSUE THREAD

**Issue by MiYanni** [dotnet/runtime#35586]
For `Utf8Parser.Decimal.TryParse`, if I feed a value of `2.5976931e-101` which is outside the minimum range for Decimal, the method returns `0` and `true`. It looks to me that the outer-most code path defaults to `default` (0) and `true`. I cannot debug this code, but I believe this happens because the value has an `e` in it. It looks like the method was trying to be clever in letting the logic fall through it, but missed this situation. Defaulting to a success state like this isn't a great idea for this very situation. 😜

Code seen here:
![image](https://user-images.githubusercontent.com/17788297/80539467-656f2200-895c-11ea-9969-804a8e958c49.png)

**Comment by danmosemsft** [comment]
@tannergooding

**Comment by tannergooding** [comment]
I can repro. I'd be happy to take a community contribution fixing this. Please just ensure the relevant tests are added (preferably also covering the `decimal.Parse` path).

**Comment by tannergooding** [comment]
CC. @pgovind

**Comment by felipepessoto** [comment]
> I can repro. I'd be happy to take a community contribution fixing this. Please just ensure the relevant tests are added (preferably also covering the `decimal.Parse` path).

I'll take a look if I'm able to fix it. But where is the decimal.Parse path?

**Comment by tannergooding** [comment]
> But where is the decimal.Parse path?
* https://github.com/dotnet/runtime/blob/39171154e34fd9cef8111976cb3b7c775a4a8224/src/libraries/System.Private.CoreLib/src/System/Decimal.cs
* https://github.com/dotnet/runtime/blob/39171154e34fd9cef8111976cb3b7c775a4a8224/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs

**Comment by felipepessoto** [comment]
I'm receiving this error when I try to debug the unit tests, do you know what can be causing the problem? The tests run successfully, the problem only happens while debugging:

![image](https://user-images.githubusercontent.com/1336227/83309738-753e8800-a1e0-11ea-9970-669d49abea55.png)

**Comment by felipepessoto** [comment]
decimal.Parse works as expected.

If I understand correctly, both APIs first call a method to convert the input to Number and then the Number to decimal.
The first step is obviously different for each API, in the second step, both call Number.TryNumberToDecimal.

The difference is that TryParseNumber in decimal.Parse implementation retuns false, and the number buffer is not correct (scale = 1), so it doesn't even call TryNumberToDecimal:

![image](https://user-images.githubusercontent.com/1336227/85958174-d1283800-b969-11ea-8856-10c4bfa6e615.png)



While in Utf8Parser TryParseNumber seems more flexible, it returns true and the Number is correct:

![image](https://user-images.githubusercontent.com/1336227/85958206-206e6880-b96a-11ea-8169-cd89a98cf7a9.png)

We have 2 ways to fix it, we can change Utf8Parser TryParseNumber to behave like in Number class, or change Number.TryNumberToDecimal to validate this situation. Number.TryNumberToDecimal  is broken anyway, since it returns true and value = 0.

**Comment by felipepessoto** [comment]
Considering this statement:

"A Decimal object has 29 digits of precision. If s represents a number that has more than 29 digits, but has a fractional part and is within the range of MaxValue and MinValue, the number is rounded, not truncated, to 29 digits using rounding to nearest."

Can't we say 2.5976931e-101 is been successfully rounded to 0?

**Comment by MiYanni** [comment]
IMO, you shouldn't 'round' a parser. The point of the parser is to say, "Was I able to parse this string into a Decimal value?" If the value is outside the range of Decimal, it logically should not be able to parse it as it is no longer a 'lossless' conversion/parsing. From a user's perspective, I get a string from *somewhere* and to me, `0` is different from `2.5976931e-101`. The slippery slope of 'rounding' is that logically **anything** that could be outside the range of Decimal would then be `0`. So, typing random numbers like `6.3243768921e-342` would also be `0`. It is basically like saying it is half-parsable because you recognize it is a decimal value but it cannot be converted to a Decimal. I don't believe this is the right approach.

**Comment by felipepessoto** [comment]
**First a disclaimer about my last comment, Idk if my understanding is correct.**

About the rounding, it doesn't mean that any string will round to zero nor that it is happening because your value is out of range. The problem with the examples you gave is that both are so small that it round to zero. Any numeric type will round at some point, you can't have infinite precision.

Some examples:

"2.5976931e-28" = "0.0000000000000000000000000003" or "3.000000E-028" (calling ToString("E"))
"10000000000000000000000000002.5976931e-28" = 1.0000000000000000000000000003
"2.5976931e-29" = 0
"100000000000000000000000000002.5976931e-29" = 1 (here we can see it doesn't round to 0, it just round to nearest value)

**Comment by MiYanni** [comment]
Ah, I see. If that is the intended parsing mechanics of Decimal, then the Utf8Parser should match that. The `NumberStyles.Float` is a great find. Any way that fix could be done?

**Comment by felipepessoto** [comment]
Utf8Parser already matches decimal behavior, using your example, both returns true and the result is 0

**Comment by tannergooding** [comment]
> The point of the parser is to say, "Was I able to parse this string into a Decimal value?"

IEEE 754, which defines the behavior for `float` and `double` and the longstanding behavior of `Decimal` (which is the Windows `DECIMAL` type) is that inputs are taken as given, the operation is performed as if to infinite precision and unbounded range, and is then rounded to the nearest representable result.
This means that nothing is really unpresentable, it might just not be exactly representable with varying degrees of error. There are parts of the IEEE 754 spec that allow reporting of inexact values, but due to how floating-point works, that is actually a lot more common than you might expect and quickly gets very noisy. The same is true of decimal, as even something as simple as `1 / 3` is not exactly representable.

`decimal.TryParse` and `Utf8Parser.TryParse(..., out decimal)`, outside of creating the `Number.NumberBuffer`, use the same algorithm for parsing out the decimal, so the results should be the same unless the initial filling of the `NumberBuffer` differs somewhere.

**Comment by MiYanni** [comment]
It sounds like everything is working as expected then. Overall, it was just a misunderstanding/ignorance on my part for how boundaries for Decimal values are handled. Thank you for clearing that up. 😊
