### ISSUE TITLE
Problem with UI Culture

### ISSUE THREAD

**Issue by Robert-LTH** [dotnet/runtime#35638]
I think i need an explanation about why NlsGetUserDefaultUICulture uses InitializeUserDefaultCulture instead of InitializeUserDefaultUICulture. I think this is why i get the wrong result when using CurrentUICulture when my process is running as system.

https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureInfo.Nls.cs#L82

**Comment by tarekgh** [comment]
InitializeUserDefaultUICulture is calling NlsGetUserDefaultUICulture. We cannot make NlsGetUserDefaultUICulture to call InitializeUserDefaultUICulture or it will be infinite loop.

https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureInfo.cs#L826

could you tell me more about your environment to investigate? we may have some bug somewhere. Are you turning Nls config switch on? otherwise, you'll be using ICU by default now which maybe the bug in this path. 

CC @safern

**Comment by tarekgh** [comment]
I think the bug is here 
https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureInfo.Icu.cs#L45

**Comment by tarekgh** [comment]
thanks @Robert-LTH for reporting this issue. we'll try to fix this soon.

**Comment by Robert-LTH** [comment]
Thank you for looking into this! I can add some info to this, it might help you understand my issue.

if i run `dism /online /get-intl` it outputs

> Default system UI language : en-US

Default User Locale is sv-SE.

If i check the properties of `CultureInfo.CurrentUICulture` it has LCID = 1053 (sv-SE). I expect this to be 1033 (en-US).

**Comment by tarekgh** [comment]
@Robert-LTH thanks for the info. I assume you are using v5.0 bits here as the whole discussion around that. Just to ensure we all in the same page. 

As a workaround, if this is blocking you, you may use the config switch https://github.com/dotnet/runtime/blob/dd22ce809f235b40f20737b56458bacdb8ec2b46/src/libraries/System.Globalization/tests/NlsTests/runtimeconfig.template.json#L3.

**Comment by safern** [comment]
Thanks @Robert-LTH for reporting the issue. I've put up a PR to fix this: #35680
