### ISSUE TITLE
Retrieving supported target framework versions programatically

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/runtime#35671]
_From @holc-tkomp on Monday, April 27, 2020 6:00:40 PM_

Is there a way to retrieve the #supported-target-framework-versions list programatically in .NET (C#)?
I'd prefer to avoid hard-coding this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-framework-versions)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

_Copied from original issue: dotnet/docs#18105_

**Comment by IEvangelist** [comment]
_From @IEvangelist on Tuesday, April 28, 2020 6:27:19 PM_

Hi @holc-tkomp,
Thank you for asking this question, and reaching out through an issue. This is a good question, and I agree - that I would rather not hard-code this lookup data either. Unfortunately, I do not believe that this is available programmatically. I'll ask around a bit, and report back - but could you please clarify how you might imagine this being available? Are you thinking exposed through some types with static data or something?

**Comment by IEvangelist** [comment]
_From @holc-tkomp on Tuesday, April 28, 2020 6:52:14 PM_

I would like to see some helper class, maybe within one of the `Microsoft.NETCore.*` namespaces, with static methods such as
```c#
public static string[] GetSupportedTargetFrameworks();
public static string[] GetDeprecatedTargetFrameworks();
```

Similar thing could be considered for the [Runtime identifiers](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) ([runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json)).

**Comment by IEvangelist** [comment]
_From @IEvangelist on Tuesday, April 28, 2020 6:59:26 PM_

Adding @terrajobst - what do you think about the idea ☝️ ?

**Comment by vitek-karas** [comment]
I think if we do expose this it would belong to something like Microsoft.Extensions.DependencyModel or similar library which is shipped outside of the core framework.

@holc-tkomp Can you please describe in a bit more detail what is the scenario you want to use these APIs in? Also do you need this to work on .NET Core/.NET 5 only or also on .NET Framework?

**Comment by paul1956** [comment]
I have an application that translates code and need a way for the developer to pass both the target framework for the translation so it knows what flags to set and what libraries referenced to include. It would be nice for Framework.

**Comment by vitek-karas** [comment]
Actually ASP.NET has very similar code in it - it can recompile some parts "at runtime". But the way that works is that it always bases all decisions on the versions which the application asked for. It never uses the versions available on the machine where the code runs.

That's similar to just plain compiler. It should not matter what the compiler runs on (.NET Framework, .NET Core, ...) - the output of the compiler should not change. In other words, compiling a project on one machine should produce the same result as compiling it on another machine (which can have different versions installed on it).

I don't know about your specific use case, but in general it feels better to not rely on the exact available frameworks on the machine. (Another aspect are previews - what we try to avoid at all costs is changing behavior if you install a new preview version, which is a very similar problem, the preview version would have to show up in the list you ask for).

To support ASP.NET you can build the project with "compilation info included", this gets stored in the `.deps.json` file - it stores compiler defines and all dependencies used during compilation (basically all reference assemblies), including versions and so on. To read this you use the Microsoft.Extensions.DependencyModel library - that can parse the `.deps.json` and exposes things like "Get me all reference assemblies for this library". Getting framework versions out of it will be a bit more tricky, but I think it should be possible.

**Comment by paul1956** [comment]
I posted code that can do it for framework and core that can be used as a sample but it uses the DotNet console command to get the Core information which should not ne necessary. https://github.com/paul1956/CSharpToVB/blob/master/CSharpToVB/Utilities/TargetFrameworkSupport.vb

**Comment by holc-tkomp** [comment]
> @holc-tkomp Can you please describe in a bit more detail what is the scenario you want to use these APIs in? Also do you need this to work on .NET Core/.NET 5 only or also on .NET Framework?

Sorry for such a late response.

_I ultimately solved the problem differently in my scenario - extracted the target frameworks and runtime identifiers straight from the directories structure._
_App that was going to need it was on  .NET Framework 4.7.2._

In my scenario I needed to retrieve all existing dependencies of an assembly for every runtime.
I retrieved as much data as I could from `.deps.json` and `.runtimeconfig.json` files, but this wasn't enough.

Consider dependencies of .NET Core 3.1 Console Application, referencing `System.Data.SqlClient`, copied to output directory, published as:
 - targetting: `netcoreapp2.1`,
 - framework dependent,
 - portable.

This will result in `System.Data.SqlClient.dll` assemblies located under following paths (relative to main assembly):
```c#
var paths = new [] {
    @"System.Data.SqlClient.dll",
    @"runtimes\unix\lib\netcoreapp2.1\System.Data.SqlClient.dll",
    @"runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll",
}
```

Now I needed to retrieve all those paths, by having main assembly path as an input.
I know that the folder structure (for .NET assemblies) is:
```
runtimes/{rid}/lib/{targetFramework}/{assemblyFileName}
```
Only hint from `.deps.json`, regarding the `System.Data.SqlClient.dll`, was this:
```json
{
  "targets": {
    ".NETCoreApp,Version=v3.1/win10-x64": {
      "System.Data.SqlClient/4.8.1": {
        "runtime": {
          "runtimes/win/lib/netcoreapp2.1/System.Data.SqlClient.dll": {
            "assemblyVersion": "4.6.1.1",
            "fileVersion": "4.700.20.6702"
          }
        }
      }
    }
  }
}
```
This allows to retrieve 1 out of 3 assemblies, so that's not enough.

So I thought, that only searching directories constructed from **supported target frameworks** and **known runtime identifiers** would be a better way, since the runtime won't look in different directories either, right?

Ultimately I just generated the list of RIDs and target frameworks used by this particular assembly, by browsing the directories structure.
While this solution does not check if assembly, from lets say `runtimes/abc/lib/notcoreapp9.99/`, is gonna be used by runtime in any way, it solves issue with handling any upcoming target frameworks (or rids).
