### ISSUE TITLE
Installer test BundleProbe.Bundle_Probe_Passed_For_Single_File_App failures on Linux_musl x64 

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#35755]
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#626420](https://dev.azure.com/dnceng/public/_build/results?buildId=626420)|Rolling|1|
|[#626513](https://dev.azure.com/dnceng/public/_build/results?buildId=626513)|Rolling|1|
|[#626634](https://dev.azure.com/dnceng/public/_build/results?buildId=626634)|Rolling|1|
|[#626761](https://dev.azure.com/dnceng/public/_build/results?buildId=626761)|Rolling|1|
|[#626950](https://dev.azure.com/dnceng/public/_build/results?buildId=626950)|Rolling|1|
|[#627020](https://dev.azure.com/dnceng/public/_build/results?buildId=627020)|Rolling|1|
|[#627303](https://dev.azure.com/dnceng/public/_build/results?buildId=627303)|Rolling|1|
|[#627435](https://dev.azure.com/dnceng/public/_build/results?buildId=627435)|Rolling|1|
|[#627770](https://dev.azure.com/dnceng/public/_build/results?buildId=627770)|Rolling|1|
|[#627900](https://dev.azure.com/dnceng/public/_build/results?buildId=627900)|Rolling|1|
|[#627940](https://dev.azure.com/dnceng/public/_build/results?buildId=627940)|Rolling|1|
|[#627985](https://dev.azure.com/dnceng/public/_build/results?buildId=627985)|Rolling|1|
|[#627992](https://dev.azure.com/dnceng/public/_build/results?buildId=627992)|Rolling|1|
|[#628150](https://dev.azure.com/dnceng/public/_build/results?buildId=628150)|Rolling|1|
|[#628240](https://dev.azure.com/dnceng/public/_build/results?buildId=628240)|Rolling|1|
### Configurations
- Installer-coreclr-Linux_musl_x64-Release

```
Expected command to pass but it did not."\nFile Name: /root/runtime/artifacts/tests/Release/ahb/1/BundleProbeTester/bundle/BundleProbeTester\nArguments: SingleFile\nExit Code: 253\nStdOut:\nUnexpected file hostpolicy.dll found in bundle.\n\nStdErr:\n\n"

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in /_/src/installer/test/TestUtils/Assertions/CommandResultAssertions.cs:line 31
   at AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Passed_For_Single_File_App() in /_/src/installer/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleProbe.cs:line 46
```

https://dev.azure.com/dnceng/public/_build/results?buildId=628240&view=ms.vss-test-web.build-test-results-tab&runId=19618302&resultId=100000&paneView=debug

Docker image: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-WithNode-0fc54a3-20190918214015

@swaroop-sridhar this is blocking clean rolling builds, can you please take a look?  

cc: @dotnet/runtime-infrastructure

**Comment by swaroop-sridhar** [comment]
OK I'll take a look into it.
I'll disable the test in the meantime so that rolling builds are green.

**Comment by safern** [comment]
Thanks, @swaroop-sridhar

**Comment by safern** [comment]
Tests where disabled so removing the `blocking-ci` label.

**Comment by swaroop-sridhar** [comment]
we're hitting a set of test failures only on Linux-Musl  _release_ jobs. 
This issue was the first test to fail so we've temporarily disabled it.

I've reproed the problem locally using the docker image. It looks like a misinterpreted return value (maybe due to compiler optimization) at an interop boundary for stdcall. So, @AaronRobinsonMSFT  I wanted to ask your opinion about how to debug it. 

In this test, the program [PInvokes](https://github.com/dotnet/runtime/blob/master/src/installer/test/Assets/TestProjects/BundleProbeTester/Program.cs#L18) to an [Stdcall function](https://github.com/dotnet/runtime/blob/master/src/installer/test/Assets/TestProjects/BundleProbeTester/Program.cs#L12-L13). This calls [`bundle_probe`](https://github.com/dotnet/runtime/blob/7d4f73ca0a1268d3b07a71410c828f7cd1d9471c/src/installer/corehost/cli/hostpolicy/hostpolicy_context.cpp#L38-L57) function in the host.

For the [invocations that test for non-existant files](https://github.com/dotnet/runtime/blob/master/src/installer/test/Assets/TestProjects/BundleProbeTester/Program.cs#L79-L81), the call eventually returns `false` from native code, but the managed code thinks that it got a `true`, and fails at [this step](https://github.com/dotnet/runtime/blob/master/src/installer/test/Assets/TestProjects/BundleProbeTester/Program.cs#L32).

So, was wondering if this rings a bell. 

There are several more here: https://github.com/dotnet/runtime/issues/35967
Not sure if they are the same problem ... 

CC: @VSadov  @vitek-karas

**Comment by AaronRobinsonMSFT** [comment]
So the `StdCall` should not impact this at all - that should only impact x86. However that is an interesting place to start. What would be helpful is to see the generated IL stub for the call.

Set a breakpoint at line 1103.

https://github.com/dotnet/runtime/blob/08b244ed43b1684d8ee1fce9b6ed0e913f4cdba4/src/coreclr/src/vm/dllimport.cpp#L1103-L1115

The predicate will evaluate false, so you need to set the IP manually to be on 1105.

Set a breakpoint at line 1255.

https://github.com/dotnet/runtime/blob/08b244ed43b1684d8ee1fce9b6ed0e913f4cdba4/src/coreclr/src/vm/dllimport.cpp#L1252-L1267

From here you can look at `strILStubCode` and that will contain the generated IL stub.

**Comment by AaronRobinsonMSFT** [comment]
It would also be helpful to see the native function being called - at least the signature.

**Comment by swaroop-sridhar** [comment]
The native function being called is [`bundle_probe`](https://github.com/dotnet/runtime/blob/7d4f73ca0a1268d3b07a71410c828f7cd1d9471c/src/installer/corehost/cli/hostpolicy/hostpolicy_context.cpp#L38-L57) with signature
`bool (anonymous namespace)::bundle_probe(char16_t const*, long*, long*)`

Since this is a release build only failure, I'm having a hard time setting a breakpoint at the said location, I'll try a source change to make it work -- and let you know. Thanks.
