### ISSUE TITLE
API proposal ReadAsync(Predicate<T>) on System.Threading.Channels

### ISSUE THREAD

**Issue by prcdpr** [dotnet/runtime#35780]
In my use case I add elements to channel along with associated index.  On reader side I'd like to retrieve them in particular order. Currently it's possible with workaround that adds item back on the end of queue when it's not coming in expected order

```
await foreach (var item in _channel.Reader.ReadAllAsync())
{
    if (item.Index == _currentIndex)
    {
        await WriteAction(item.Item);
        _currentIndex++;
    }
    else
    {
        await _channel.Writer.WriteAsync(item);
    }
}
```

Of course it generates a lot of uneccessary spinning.

With proposed API it could look like this
```
while (true)
{
    if (!await WaitToReadAsync(item => item.Index == _currentIndex))
        break;

    if (TryRead(out T item))
        ProcessItem(item);

    _currentIndex++;
}
```

Or maybe it's already possible in another way that I'm not aware of?

**Comment by tarekgh** [comment]
CC @stephentoub 

does it make more sense if used ConcurrentQueue<T> for this scenario?

**Comment by stephentoub** [comment]
Such an API isn't really feasible at this point; it would need to be virtual rather than abstract, and there isn't a good way to build this on top of the existing APIs that are there, so there would separately need to be some kind of mechanism to communicate whether the method was supported.  It would also add non-trivial requirements for implementations to support, as there's unlikely to be a good way to implement this in some cases without taking a lock, e.g. the unbounded channel today is able to enjoy lock-free reads in many cases, and that would no longer be true.  It would also add delegate invocation overheads to every read, would complicate the notification mechanism by which a writer signals to a waiting reader that there's data available, etc.

I think a better approach would be either:
a) to ensure items go into the channel in the right order.  If there are multiple producers, they would need to coordinate. You can see the System.Threading.Tasks.Dataflow library does something similar with its reordering buffer: https://github.com/dotnet/runtime/blob/b6341c6e1ada32117639cc409d445fd6b9b9e9f0/src/libraries/System.Threading.Tasks.Dataflow/src/Internal/ReorderingBuffer.cs
b) do https://github.com/dotnet/runtime/issues/32700, at which point you could plug in your own IProducerConsumerCollection which could yield items in whatever order you like, e.g. it could be a priority queue prioritized based on index

**Comment by prcdpr** [comment]
Thanks for answering. I can see the difficulties that it would cause so I'll close this issue for now.

Meanwhile, building reordering buffer on top of existing Channels API seems like a good direction. I'll take a look at Dataflow's code as reference.

**Comment by stephentoub** [comment]
Sounds good. Thanks.
