### ISSUE TITLE
System.IO.DirectoryNotFoundException: 'Could not find a part of the path

### ISSUE THREAD

**Issue by BrunnaMaiaradaSilva** [dotnet/runtime#35825]
When I run .NET Core Web API Application on VS 2019,
In Output's Debug panel, keep showing me Exception throw:

System.IO.DirectoryNotFoundException: 'Could not find a part of the path in System.Private.CoreLib.dll

However, application runs well without stoping or malfunctioning.
I know Exception always means somthing needs to be cared.

So, how can I search what File is Not Found when run CoreCLR?

**Comment by scalablecory** [comment]
@jeffschwMSFT

**Comment by jkotas** [comment]
Go to Debug / Windows / Exception Setting in Visual Studio, and check "Common Language Runtime Exceptions". It will make the debugger stop when the exception is thrown and show you the callstack.

It is not unusual for exceptions to be thrown and handled gracefully. You are likely seeing one of these cases since the application works fine otherwise.

> I know Exception always means something needs to be cared.

Unhandled exceptions need to be cared for. Handled exceptions are ok.

**Comment by BrunnaMaiaradaSilva** [comment]
The exception persisted, so I press alt + Enter and selected Properties. In this properties window you have the option to copy to the output directory and it is this option that I changed, the program ran without problems.
