### ISSUE TITLE
Add a function to convert a globbing pattern to a regex pattern in the Regex class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#359]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/486651/add-a-function-to-convert-a-globbing-pattern-to-a.html)._

---
<p>Add a function, e.g. named &quot;GlobToRegex&quot; that takes one string parameter and returns a string. This would be a static method of the System.Text.RegularExpressions.Regex class.</p><p>This function would take a 'globbing' pattern and return the equivalent regular expression pattern.</p><p>A globbing pattern is a widely established syntax used for matching files and folders, where '*' represents any sequence of characters, and '?' represents any one character. Sometimes there are further facilities available, such as '[' and ']' surrounding a set of characters, which matches any one of the set of characters. </p><p>A simple stab at describing the implementation would be: use Regex.Escape to make all the characters in the globbing pattern be literal in a regex (generally by prefixing each character with '\'); replace all '\*' with '.*' and replace all '\?' with '.?'; prefix with '^' and suffix with '$'. However, a better implementation would replace all '\*' with '[^xy]*' where xy represents path delimiter characters (and possibly some other characters) and would also deal with the further facilities I mentioned above. </p><p>I'm pretty sure this function would be very useful (or at least a convenience) to many people. </p>

---
#### Jane Wu [MSFT] on 3/13/2019, 00:49 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by danmosemsft** [comment]
One concern here is what is expected by globbing. Various implementations have more or less vocabulary. We would have to pick one.

Also, not all globbing features can be implemented by simple modifications to a regex, and may be domain specific. For example `**` -- should that be equivalent to `*` or should `**` and not `*` match directory separators?

If this goes on Regex, it has to be something that matches expectations for almost everyone. 

What are you trying to achieve here? Would it be better to just use a globbing library? It may actually be faster. Eg., https://github.com/dazinator/DotNet.Glob

**Comment by theREALdebater** [comment]
As to what is expected, I suggest there is an extra 'options' parameter of a flag-like enum type. There could be an option for the `**` feature (which I like) and an option for `[`...`]` and a convenience value `All` which could be the default.
As for why have this on Regex rather than as a separate globbing library, it's about interfaces. Supposing I'm adding an entrypoint to an API, and I want it (or need it) to have a parameter that allows a text pattern to be specified. For example, it might be something like `ExtractFiles` to fetch multiple files out of an archive. It might make a lot of sense for the parameter to be a Regex, since Regex has become so popular nowadays. However, on top of that, I want to add an entrypoint to a higher-level API, e.g. `ExtractAttachments`, that specifically allows a glob as one of its parameters. This method would call `ExtractFiles` to get the files , but it needs to convert the glob to a Regex.

**Comment by pgovind** [comment]
So I understand the motivation to have this, but IMO the Regex engine itself should not implement this. There are enough subtleties in the behavior of various glob patterns on different platforms that I think getting it working to meet every expectation is not feasible. Dan makes a great point. I'm going to close this issue.

However, I do think this is a great idea for an extension package. The package can also expose convenience APIs, for ex: a fluent API to build up the glob pattern. Also, if one wanted to use Regex for this, I don't see why he/she can't write the Regex in the first place instead of using a glob pattern?
