### ISSUE TITLE
Overload missing from RSACryptoServiceProvider.Encrypt Method

### ISSUE THREAD

**Issue by StewartRyanSony** [dotnet/runtime#35920]
Hello, 

I'm using .net core 3.1 as part of of PowerShell 7. I have a script which uses the encrypt method of a certificate to encrypt a string. 
```powershell
$Cert = Get-Item Cert:\LocalMachine\My\$ThumbPrint
$EncryptedBytes = $Cert.PublicKey.Key.Encrypt($StringBytes, $true)
```
This code runs just fine in PowerShell 5.1, which I believe uses .net framework 4.5.2. But throws an error in PowerShell 7 about not being able to cast `$true` to type `Cryptography.RSAEncryptionPadding`.

In PowerShell 5 there are two overloads for the encrypt method
```powershell
OverloadDefinitions
-------------------
byte[] Encrypt(byte[] rgb, bool fOAEP)
byte[] Encrypt(byte[] data, System.Security.Cryptography.RSAEncryptionPadding padding)
```
However in PowerShell 7 there is only one overload for the encrypt method
```powershell
OverloadDefinitions
-------------------
byte[] Encrypt(byte[] data, System.Security.Cryptography.RSAEncryptionPadding padding)
```

The Error makes sense given that the `Encrypt(Byte[], Boolean)` overload is not present in PowerShell 7 and .net core 3.1.

According to the .net documentation both overloads should be available in .net core 3.1
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacryptoserviceprovider.encrypt?view=netcore-3.1

Is there a reason the `Encrypt(Byte[], Boolean)` overload is missing, and will it be included in a future version?

Thanks,
Ryan

**Comment by bartonjs** [comment]
I'm guessing that the problem is that in PowerShell 7 you're not getting an RSACryptoServiceProvider object, but some other object (e.g. RSACng, or an opaque RSA object); and so the dynamic binding for Encrypt says there's only one method, with incompatible parameters.

What is `$Cert.PublicKey.Key.GetType().FullName`?

**Comment by StewartRyanSony** [comment]
Ugh, I just closed an issue with the PowerShell team and they sent me to this team.
I think you're right the Types are different in the different versions of PowerShell.
PowerShell 5.1
```powershell
Scripts> $Cert.PublicKey.Key.GetType().FullName
System.Security.Cryptography.RSACryptoServiceProvider
```
PowerShell 7
```powershell
Scripts> $cert.PublicKey.Key.GetType().FullName
System.Security.Cryptography.RSACng
```
So is this a PowerShell issue after all or is this still a difference between .net framework and .net core?

**Comment by bartonjs** [comment]
The property returning a different type is a difference between Framework and Core.  The boolean-based overload is specific to RSACryptoServiceProvider; the RSAEncryptionPadding version comes from the RSA (base) class, so it's available to all RSA types.

**Comment by StewartRyanSony** [comment]
Is there anything that can be done about this?

**Comment by vcsjones** [comment]
> Is there anything that can be done about this?

Use the overload that accepts `RSAEncryptionPadding` since that is on `RSACryptoServiceProvider` and `RSACng`. Use `OaepSHA1` where you were previously using `true`, and `Pkcs1` when you were specifying `false`.

**Comment by bartonjs** [comment]
If you really need to use the RSACryptoServiceProvider API for public keys you can wrap it:

```
$Key = new RSACryptoServiceProvider();
$Key.ImportParameters($Cert.PublicKey.Key.ExportParameters($false));
$EncryptedBytes = $Key.Encrypt($StringBytes, $true);
$Key.Dispose();
```

That won't reliably work for private keys, since not all private keys allow their parameters to be exported.  Certainly the recommendation would be to change the code to use the newer encrypt method

```
$EncryptedBytes = $Cert.PublicKey.Key.Encrypt($StringBytes, RSAEncryptionPadding.OaepSHA1);
```

Apologies if my PS is non-functional/non-canonical.  It's not a language I'm proficient in.

**Comment by StewartRyanSony** [comment]
Than you for the feedback. I had already started using the RSAEncryptionPadding overload on a new script I am writing so that I could get it working and move forward. 
```powershell
$EncryptedBytes = $Cert.PublicKey.Key.Encrypt($StringBytes, [System.Security.Cryptography.RSAEncryptionPadding]::OaepSHA256)
```
However it seems like I will need to continue running older scripts on PowerShell 5.1 until and if I ever get a chance to update them. 

I don't mean to bug everyone too much but I don't understand, and I'd like to, why in powershell 5.1/ .net framework 4.5.2 `$Cert.PublicKey.Key` is type RSACryptoServiceProvider and in PowerShell 7/ .net core 3.1 it is type RSACng.

Is this something that is just required to be compatible with other operating systems, is it a feature that hasn't been ported over yet, or is it something specific to powershell?

Thanks,
Ryan

**Comment by bartonjs** [comment]
In .NET Core (since 1.0) the Key property uses the best provider implementation for the system, which is RSACng on Windows.  That's really from before we made the RSACryptoServiceProvider type try to work in most situations on non-Windows systems, by just wrapping the system-provided version.

Now it's just one of those things that's different between .NET Framework and .NET Core.  As for PowerShell, it's presumably that for 7 they moved from Framework to Core.  Changing it to RSACryptoServiceProvider might break existing Core apps that assume it's always RSACng, so we're essentially stuck with what we have.

**Comment by vcsjones** [comment]
Also note that `PublicKey.Key` is going to return different things from platform to platform. By definition, it returns an `AsymmetricAlgorithm`. If the certificate's public key is an RSA key, it will be of some type [`RSA`][1], which is the base class for `RSACng` and `RSACryptoServiceProvider`.

PowerShell Core on other platforms, like MacOS, will not return `RSACng` or `RSACryptoServiceProvider`, it will return an internal type called `RSASecurityTransforms`. If you ever plan on your PowerShell script being x-plat, it probably makes sense to not assume any specific concrete implementation, but only `RSA`.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa?view=netcore-3.1

**Comment by bartonjs** [comment]
Closing the issue since this was a question about a behavior change in PowerShell, which corresponded to a behavior change between .NET Framework and .NET Core, and that question has been answered.
