### ISSUE TITLE
Microsoft Visual Studio Installer Projects other device issue

### ISSUE THREAD

**Issue by Tikadze** [dotnet/runtime#35951]
Hi,

I have a .Net Core 3.1 project, I want to make a Setup file from.
I used Microsoft Visual Studio Installer Projects:
Project Output: "Publish Items" - 1 Icon - 2 Shortcuts
I rebuilt my Setup project and it generated .exe and .msi files in Setup Project ~\Debug folder.

I Launched .msi and installed everything normally. Tested the app, and it works on my device.
Then, I moved the .msi file to another device. Installed .Net Core 3.1. Launched the .msi, installed everything normally. However, my app didn't run.

I'd like to add, that I used the .msi file from Setup project ~\Debug folder.

Thanks in advance

**Comment by Tikadze** [comment]
@safern @ViktorHofer

**Comment by safern** [comment]
cc: @jeffschwMSFT not sure who to redirect this one to.

**Comment by jeffschwMSFT** [comment]
Please set COREHOST_TRACE=1 and collect the logs for the launching application.

cc @vitek-karas

**Comment by vitek-karas** [comment]
> However, my app didn't run.

Can you please provide more details? It's nearly impossible to tell what could be wrong with just that statement:
* Is this a console or GUI app (WinForms, WPF, ...)?
* What happens when you run it - do you get an error reported back either via command line or a dialog?
* If it's a UI app, can you look with EventViewer if there's an event about the application failing to start? If so, what does the error say?
* Is the app x86 or x64 (or you didn't set a specific arch)?

**Comment by Tikadze** [comment]
@vitek-karas Hi,
1. The project is WPF. 
2. When I run the app, nothing happens. I looked into the Task Manager, it appears in the Background processes, then, it disappears. And doesn't appear in the Apps.
3.  There is no error.
4. The app is x64.

Thanks in advance.

**Comment by vitek-karas** [comment]
Can you please open a command line:
```console
set COREHOST_TRACE=1
set COREHOST_TRACEFILE=host_trace.txt
myapp.exe
```

as the last step run your application from the command line.
This should produce the `host_trace.txt` file in the current directory. The file contains lot of details about the startup of the app, and it should include the error why the app failed to start.
It may contain information about the machine, the user name and local paths, so if you feel comfortable with that please share it with us, otherwise you should be able to find the error near the end of that file.

**Comment by vitek-karas** [comment]
Closing as there's not enough information to make progress. Please feel free to reopen or create a new issue if more assistance is needed.
