### ISSUE TITLE
Named Mutex on Different Docker Containers

### ISSUE THREAD

**Issue by AhmedMabrouck** [dotnet/runtime#35968]
Hello,

I would like to develop inter-process locking on different docker containers using ASP.NET Core, I have tried --ipc for sharing IPC memory but it did not help.

Anyone can help if it is feasible to do it or not and how.

Thanks in advance.

**Comment by mangod9** [comment]
@AhmedMabrouck could you please elaborate on the scenario? You need to synchronize across two asp.net core apps running within separate containers?

**Comment by AhmedMabrouck** [comment]
> @AhmedMabrouck could you please elaborate on the scenario? You need to synchronize across two asp.net core apps running within separate containers?

Yes, I would like to do so.

**Comment by mangod9** [comment]
I am not aware of any specific mechanisms for this currently. You could try using shared volumes (mounted in each container for some data sharing to use for locking). Might also be worthwhile to check in [aspnetcore](https://github.com/dotnet/aspnetcore/issues) if there are any other ideas.

**Comment by AhmedMabrouck** [comment]
> I am not aware of any specific mechanisms for this currently. You could try using shared volumes (mounted in each container for some data sharing to use for locking). Might also be worthwhile to check in [aspnetcore](https://github.com/dotnet/aspnetcore/issues) if there are any other ideas.

There are an option within Docker called IPC which shares some memory between containers which should enable named Mutex to work across container but unfortunately it is not working also.

Thanks a lot for your concern.

**Comment by danmosemsft** [comment]
Is it possible to solve your problem in a different way? You don't say what you're trying to achieve but if there's a contended resource, could access to it be mediated by a single app/container?

**Comment by rsaltrelli** [comment]
I'm exploring this same situation.  I'm writing a caching layer for an ASP.NET Core application.  The cache that is backed by Redis and has a method `public T GetOrCreate<T>(string key, Func<string, T> factory)` that is susceptible to cache stampedes.  If multiple web requests handled by my application simultaneously call this method, they will all detect a cache miss and attempt to run the factory function in parallel, leading to redundant work and wasted resources.

I have a new implementation that creates a mutex for the cache key being accessed and ensures that only one thread may run the factory function for that key at a time.  All others are blocked until it completes and when they are released they read the newly cached value instead of running the factory function themselves.

This works great until I realized that my application will be running in Kubernetes so there will be many pods of this app running in parallel behind a load balancer.  Since each container has its own mutex, it doesn't know if another container is already in the process of running a factory function for this cache key.  I'm at least better off than I was since I've limited the cache stampede to one factory function call per key _per container_, but the ideal solution would be to have a mutex that the containers could share so that among all of the pods there is only ever one factory function running at a time per key.
