### ISSUE TITLE
When awaiting an async method from ExecuteAsync which throws an unhandled exception, the service hangs

### ISSUE THREAD

**Issue by hognevevle** [dotnet/runtime#36017]
### Describe the bug
In a .Net Core Worker Service, whenever an exception is thrown inside an async method, and you happened to not surround the method invocation in a try/catch, the application will simply hang when it hits the exception -- giving no sign that an exception has occured at all.

The same code applied within a simple Console Application does indeed work as expected, and you get the normal "unhandled exception" behaviour.

### To Reproduce
Run sample worker service available at https://github.com/hognevevle/WorkerServicePlayground

This project was created using the Worker Service project template, and my only changes are done inside `Worker.cs`.

### Expected behavior
The exception should be propagated up to the caller, and not simply disappear.

### Screenshots
https://drive.google.com/file/d/1VCfrJY_a45gJ17uQXwGAq_krc8n-iteB/view?usp=drivesdk

### Additional context
```dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download```

**Comment by eerhardt** [comment]
I investigated this issue and here is what I found:

There is a problem that there is no good location to do the logging. When the `ExecutingTask` is not finished in `StartAsync`, the `BackgroundService` class holds privately on to the returned `ExecutingTask`.

https://github.com/dotnet/runtime/blob/a52f237fe7a9f61d480e95912dcf6c16525bbee7/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs#L13-L15

And in `StartAsync`, it returns `Task.CompletedTask` saying that the service is done starting:

https://github.com/dotnet/runtime/blob/a52f237fe7a9f61d480e95912dcf6c16525bbee7/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs#L30-L46

We could add a `.ContinueWith` on the `_executingTask` and check if an exception was thrown. However, there is nothing we can do in `BackgroundService` because it doesn't contain a Logger of any kind. so that's a dead end.

The more correct place for the logging to occur would be in the Host that starts the task. The Host already contains a logger, so it can simply log any exception to it:

https://github.com/dotnet/runtime/blob/a52f237fe7a9f61d480e95912dcf6c16525bbee7/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L51-L55

However, the Host doesn't have access to the `_executingTask`, since `BackgroundService` doesn't expose it, and the Task returned from `hostedService.StartAsync` is the CompletedTask returned from `BackgroundService.StartAsync` above. So the Host has no way of knowing anything about the ExecutingTask.

We could do some hack to make this work in `5.0`, but the real fix would be to expose the `ExecutingTask` on `BackgroundService`. This has come up before: #35991. So we will need to wait for that - which will need to go through API approval, which won't happen until 6.0.
