### ISSUE TITLE
Test coverage for AdvSimd.Extract() with const index operand

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#36074]
As shown in https://github.com/dotnet/runtime/issues/36070, we don't generate optimize code when we pass variable as index value instead of const. Our test coverage only covers passing variables. We should add coverage to test passing constant to `AdvSimd.Extract()` and other APIs that depend on value being constant while doing the importation.

**Comment by kunalspathak** [comment]
cc: @BruceForstall , @echesakovMSFT , @tannergooding

**Comment by BruceForstall** [comment]
cc @CarolEidt

**Comment by echesakovMSFT** [comment]
This is not true - we do test both code paths - case "a const immediate operand"
 is tested in the all scenarios here
https://github.com/dotnet/runtime/blob/0f6b933693e6d1f221e044d26ddbef8860c367e0/src/coreclr/tests/src/JIT/HardwareIntrinsics/Arm/Shared/GenerateTests.csx#L434-L450

except one or two - that are "call via reflection" - where we generate a switch table. The same code path will be triggered for "a non-const immediate operand" i.e. when you pass a local variable instead of constant value.

**Comment by kunalspathak** [comment]
Are you saying [Extract.Vector64.Byte.1.cs](https://github.com/dotnet/runtime/blob/32dd7d4dcb8ee91a920715ddb20672f7610b6b0d/src/coreclr/tests/src/JIT/HardwareIntrinsics/Arm/AdvSimd/Extract.Vector64.Byte.1.cs) . Here all the calls to `.Extract()` takes variable.  Can you point to the place that you are referring to?

**Comment by echesakovMSFT** [comment]
ElementIndex is not a local variable - it is a static readonly field.
```c#
private static readonly byte ElementIndex = 1;
```
it is treated in importer the same way as a literal "1" - i.e. when imported it will become GenTreeIntCon()

https://github.com/dotnet/runtime/blob/196080817a61a82fa98a66c0e63fa4df79c11b7e/src/coreclr/src/jit/importer.cpp#L6839-L6896

**Comment by kunalspathak** [comment]
Ah ok. Thanks for confirming.

**Comment by kunalspathak** [comment]
May be then I can just close this one. I will reopen it if I find any other API not having this coverage. Thanks @echesakovMSFT !
