### ISSUE TITLE
New item doesn't add to the Cache when old item expired, when SizeLimit used

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/runtime#36122]
Hi,

Consider following code:

```cs
using System;
using Microsoft.Extensions.Caching.Memory;

class Program
{
    static IMemoryCache _cache; 
    static MemoryCacheEntryOptions _memoryCacheEntryOptions;
    
    static void Main(string[] args)
    {
        _cache = new MemoryCache(new MemoryCacheOptions {SizeLimit = 20});            
        _memoryCacheEntryOptions = new MemoryCacheEntryOptions { Size = 10, SlidingExpiration = TimeSpan.FromSeconds(2) };        
    
        _cache.Set("Item1", "Value 1", _memoryCacheEntryOptions);
        _cache.Set("Item2", "Value 2", _memoryCacheEntryOptions);            
        
        Console.WriteLine(get("Item1"));            
        Console.WriteLine(get("Item2"));            
        Console.WriteLine("---");

        System.Threading.Thread.Sleep(2500);                
    
        _cache.Set("Item3", "Value 3", _memoryCacheEntryOptions);
        
        Console.WriteLine(get("Item1"));            
        Console.WriteLine(get("Item2"));            
        Console.WriteLine("---");
        Console.WriteLine(get("Item3"));
    }
    
    static string get(string key)
    {
        if (_cache.TryGetValue(key, out string value)) return value;

        return "Not Found!";
    }
}
```

Output:
```
dotnet run
Value 1
Value 2
---
Not Found!
Not Found!
---
Not Found!
```

### Expected behavior
`Item3` should be added to cache

**Comment by eerhardt** [comment]
Moving to 7 as we have shipped multiple versions with the current behavior.

**Comment by Nick-Stanton** [comment]
Just was able to repro this in .NET 7. Confirmed that unexpected behavior doesn't happen when SizeLimit isn't used, or if any get() or set() is called just before the Item3 Set(). Seems like eviction kicks off when the Item3 Set() is called but does so after the item is set. Is this by design?

CC @Tratcher

**Comment by Tratcher** [comment]
There are conflicting requirements here:
- We didn't want to run active timers for every entry expiration
- Avoid doing too much work on any thread directly interacting with the cache (e.g. don't do a full scrub when someone tries to get or add).
This results in transient states like the one described above where the cache knows it's full and doesn't add, but also triggers a background thread to process evictions.

The implementation has changed quite a bit over the years, it may be possible to handle this case more gracefully. Regardless, there will always be race conditions when dealing with capacity limits.

**Comment by ericstj** [comment]
I suppose the reason it doesn't scan synchronously for evictions when an item fails to add is because the cost of doing so would be very high in the case of a full cache, since it's doing a walk of every item in the cache in an arbitrary order:
https://github.com/dotnet/runtime/blob/9b9b0c95c678065044d01049c56915e6b750b10a/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L643

I wonder if there is a way to make that much cheaper?  For instance, if the cache could know the next significant time when it would need to change, that could be used in the failing case to decide if an eviction scan would be fruitful or not.  At the limit I could imagine the cache keeping entries as a linked list based off of order of expiration - which would make it much cheaper to do an eviction scan - to the point we could always do it synchronously.  I wonder if we could apply learnings from GC here.

**Comment by Tratcher** [comment]
You don't want to do evictions inline because it would be a significant source of contention on a full cache, and that contention would be blocking application threads (e.g. requests).

I'd recommend against trying to over optimize for the case of a full cache, it will always be racy. Adjusting utilization of the cache and its size limits is a more tractable solution for app developers. E.g. if their cache is full, they're over utilizing it.

**Comment by Nick-Stanton** [comment]
Based on the conversation in this thread, it seems best to not attempt to over-optimize for this case. I have opened a PR to document a warning in the API doc for `SizeLimit`.
