### ISSUE TITLE
ILogger mutates the array of objects to format

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/runtime#36165]
Hello there, I'm using ASP.NET Core 3.1. Basically the problem is the one described in the title. Here's how to reproduce.

Create a new ASP.NET Core application with `dotnet new web`
Change the `Configure` method of the `Startup` class like this.
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILogger<Startup> logger)
{
    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGet("/", async context =>
        {
            //Here's the relevant part of the repro
            var values = new object[] { null };
            logger.LogInformation("These are the values", values);

            //Is the first value still null?
            bool stillNull = values[0] == null;

            //It's not! This displays: "Still null: False, Value is: (null)"
            await context.Response.WriteAsync($"Still null: {stillNull}. Value is: {values[0]}");
        });
    });
}
```
As you can see, the original `null` value gets replaced with the string `(null)`. It's a very subtle behavior by the `ILogger` service and I think this is not right. The original array should be left untouched. 

Of course, the workaround is to make it log a copy of the array.
```csharp
logger.LogInformation("These are the values", values.ToArray());
```
That yields: "Still null: True. Value is:"

I'm not sure if this is the intended behavior. The `LogInformation` method description doesn't say anything about mutating the provided array.

Thanks,
Moreno

**Comment by davidfowl** [comment]
Minimal repro, I haven't dug in as yet.

```C#
using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace ConsoleApp15
{
    class Program
    {
        static void Main(string[] args)
        {
            using var loggerFactory = LoggerFactory.Create(logging =>
            {
                logging.Services.AddSingleton<ILoggerProvider, MyLoggerProvider>();
            });

            var logger = loggerFactory.CreateLogger<Program>();

            //Here's the relevant part of the repro
            var values = new object[] { null };
            logger.LogInformation("These are the values", values);

            //Is the first value still null?
            bool stillNull = values[0] == null;

            Console.WriteLine(stillNull);

            Console.Read();
        }
    }

    public class MyLoggerProvider : ILoggerProvider
    {
        public ILogger CreateLogger(string categoryName)
        {
            return new MyLogger();
        }

        public void Dispose()
        {

        }

        private class MyLogger : ILogger
        {
            public IDisposable BeginScope<TState>(TState state)
            {
                return null;
            }

            public bool IsEnabled(LogLevel logLevel)
            {
                return true;
            }

            public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
            {
                formatter(state, exception);
            }
        }
    }
}

```

**Comment by davidfowl** [comment]
Here's the code https://github.com/dotnet/runtime/blob/d2f7c8f52b7b21112a7765d311dc82a413e7116c/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LogValuesFormatter.cs#L181

**Comment by davidfowl** [comment]
OK I took a quick look and this is a bug that's been there forever. My guess is it doesn't show up because what you're showing isn't typical usage. 

The bug is here https://github.com/dotnet/runtime/blob/e3ffd343ad5bd3a999cb9515f59e6e7a777b2c34/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LogValuesFormatter.cs#L117-L127. When the logger provider tries to turn the object into a string, it get mutated here.

It should just copy the array before modifying it. We should be aware of the performance implications here though since this is a pretty hot and main code path.

**Comment by BrightSoul** [comment]
> My guess is it doesn't show up because what you're showing isn't typical usage.

Yeah, it came up affer logging a `formattableString.GetArguments()` which contained a `null`. The arguments were changed and a subsequent query to the database produced an unexpected result. See for instance the [FromSqlInterpolated](https://github.com/dotnet/efcore/blob/daf9cf36ffec8769ab4fa0a123a407fb2fd401bf/src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs#L134) extension method of a `DbSet<T>` which works with `FormattableString` objects.

**Comment by Frassle** [comment]
We hit this using FormattedLogValues class directly, we just copy the array before passing it in. Took a while to track down it was formatting code that was causing changes in our arrays.

**Comment by davidfowl** [comment]
> We hit this using FormattedLogValues class directly, we just copy the array before passing it in. Took a while to track down it was formatting code that was causing changes in our arrays.

Are you on < 3.1 bits? FormattedLogValues is internal now.

**Comment by Frassle** [comment]
> Are you on < 3.1 bits? FormattedLogValues is internal now.

I'll check when I'm in work Friday

**Comment by Frassle** [comment]
We're using Microsoft.Extensions.Logging.Abstractions 2.2.0.

**Comment by vaz-rodrigo** [comment]
Isn't this the same thing as [issue 36025](https://github.com/dotnet/runtime/issues/36025)?

Anyway, can I work on this?

**Comment by WernerMairl** [comment]
Hi
i have prepared a few tests and fix here: 

https://github.com/WernerMairl/runtime/tree/Issue-36165-Formatter-Mutations-50

(ready for feedback/discussions specially about performance impact.....)

Assuming that this should go into master/6.0 
But i was not able to compile with 6.0 (may be there is a bigger change in progress from 5.0 to 6.0)
So i did the dev work based on the 5.0 release branch, assuming that if we agree on the implementation i can create a PR for master/6.0 later on....

regards
Werner

**Comment by PathogenDavid** [comment]
@WernerMairl Did you investigate implementing an `IFormatProvider` instead? I think that'd avoid the redundant array allocation and still allow customizing the formatting behavior `IEnumerable`.

**Comment by WernerMairl** [comment]
@PathogenDavid  can you explain how a IFormatProvider should avoid that? 
I cannot follow....

Yes the array needs array allocation but not sure how much effort we should spend for optimizations without better measurements (benchmarks).....

**Comment by WernerMairl** [comment]
@vaz-rodrigo : i have seen your code after creating my one - exactly the same ;-)

I have 1 or 2 tests different and may be a simpler testing aproach... 
so we can merge/decide after the "allocation" discussion....

**Comment by PathogenDavid** [comment]
@WernerMairl From what I can see, the crux of the issue is that `LogValuesFormatter.Format(object[])` is pre-formatting `IEnumerable` in order to bypass their default format logic to provide something more useful in logs.

`IFormatProvider` is capable of providing an alternative formatter for `string.Format` to use directly instead of trying to do the alternate formatting ahead of time. ([Simplified example here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQuADAAS6EB0A4gDYD2wETAlgF4QyctMAbjJk2AKzgBjGAG0AulQAOEBBDBx4CKFQC8VTHADuVCdLmKA3gfRMmSKoQrUAviNJkA9J6oAVABacOlyGVEacdsoInJgwVADk8VTA0hDoUHBUnDDxOpRUMP6ZACZwAGZpTHEp/hAAbgIIpmVUUoJ1iPyYAOZUEDaRMCx9NE50ZLQAnAAUAMow0T10AGIsCJAw0wBEAUFZOpi2TCAJlhQuSbs6e5gsqKeEF1sOKmoaWlAAlJ/u3n6BwRimXCkSUizi8QAPIc7AA+JIpKRpDJZOLpOA6QqZKBKaScDhUVjdThSZJwVhGcbkQgzeaLborNYbaYAORJiBZRygq3WfC0dAAkphYBBMFI4A4dgD9gNjqdzpdpTc7id4pZHvFnspVOpNIgvj9RKQYlpMASCFQ2eKEJy7NymXzEFQTgKeRsAAoIFgNUrIKgCgDC6SGYDdjoQZEsZCoMainDqfEyVo5XLDMC000+0djUdIsaoLmzMaLNAAzKZgJIZFQGJo09NfABPXFUMoOmBN3FZvP52O6WEFAHuXuxku4cu0aj1yet9sOMzV1TdByu9ue72cX2z3kwdc+xDd/O5kcxzgtaZLmUwpiHk/WXAAdioW2hR1hWyEBZL+fJKLPVAvBBej2VcdxgCBgCYTI2zAiCoNvEd7yfGCNnAyC4DoXwWDpGJummFC+AcIMqnQBA4CFNs6CDBAyNiYiYFIuAfi/HsR1/OBvxzGgnyXTDsIWXDM0/QtWJY/MxwnQgADYqDIiBikEJhG0tdkbVTdstH9YVwLFTJ9EMIwhLIESgA))

I don't really have a horse in this race, but my gut reaction is that doubling allocations in order to handle an uncommon case isn't ideal.

**Comment by KalleOlaviNiemitalo** [comment]
Implementing via `ICustomFormatter` might increase the number of `string` allocations by disabling the `ISpanFormattable` optimization.

**Comment by KalleOlaviNiemitalo** [comment]
If you worry about the array allocation, then perhaps `LogValuesFormatter.Format(object[])` can do it lazily when it finds an array element that cannot be used as is, i.e. the value is either `null` or an `IEnumerable` other than `string`. However, it would be best to have some benchmarks before adding such complexity. I don't know what fraction of log calls in real programs have null references among the values. For `IEnumerable` values, I suspect the `string.Join(", ", enumerable.Cast<object>().Select(o => o ?? NullValue))` expression in `LogValuesFormatter.FormatArgument(object)` causes so many allocations that the array does not matter. And if the log level is disabled, then the log entry won't be formatted anyway.

**Comment by pergardebrink** [comment]
> If you worry about the array allocation, then perhaps `LogValuesFormatter.Format(object[])` can do it lazily when it finds an array element that cannot be used as is, i.e. the value is either `null` or an `IEnumerable` other than `string`. However, it would be best to have some benchmarks before adding such complexity. I don't know what fraction of log calls in real programs have null references among the values.

If you take my numbers with a grain of salt (haven't been running BenchmarkDotNet a lot), I did some quick benchmarks with some of the things discussed here, like the lazy init or custom formatter. I couldn't yet get the dotnet/runtime repo to build locally for me, so I have created roughly equivalent code in a small repro project to test different scenarios. I am running each method with two different arrays, 10 items each. One that needs mutating (containing IEnumerables and nulls) and one that would end up with the same value and not mutate the array.

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.103
  [Host]     : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  DefaultJob : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
```

|                              Method |       Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------------ |-----------:|---------:|---------:|-------:|------:|------:|----------:|
|           FormatArgument_SameValues |   526.8 ns | 10.13 ns | 11.26 ns | 0.0229 |     - |     - |     192 B |
|           AlwaysNewArray_SameValues |   502.9 ns |  4.99 ns |  4.66 ns | 0.0353 |     - |     - |     296 B |
|         NewArrayOnDemand_SameValues |   515.4 ns |  3.53 ns |  3.31 ns | 0.0229 |     - |     - |     192 B |
| ICustomFormatterOnDemand_SameValues |   486.0 ns |  6.81 ns |  6.03 ns | 0.0229 |     - |     - |     192 B |
|         ICustomFormatter_SameValues |   479.5 ns |  3.10 ns |  2.75 ns | 0.0572 |     - |     - |     480 B |
|              AlwaysNewArray_Mutated | 2,675.8 ns | 32.16 ns | 30.09 ns | 0.4005 |     - |     - |    3352 B |
|            NewArrayOnDemand_Mutated | 2,746.2 ns | 31.17 ns | 29.15 ns | 0.4005 |     - |     - |    3352 B |
|    ICustomFormatterOnDemand_Mutated | 2,704.0 ns | 53.90 ns | 68.16 ns | 0.3967 |     - |     - |    3344 B |
|            ICustomFormatter_Mutated | 2,640.8 ns | 47.70 ns | 39.83 ns | 0.3967 |     - |     - |    3344 B |

**FormatArgument** is similar to the existing code today, that modifies the array in place (I could not get a reliable benchmark for mutated values since the array would be mutated when BenchmarkDotNet warms up and couldn't get IterationSetup working fully)
**AlwaysNewArray** always creates a new array and then runs FormatArgument on all of them
**NewArrayOnDemand** allocates and copies the array only if the value would be mutated
**ICustomFormatter** is using a custom formatter provided to string.Format so the array doesn't have to be mutated
**ICustomFormatterOnDemand** is using a custom formatter only if a value in the array would mutate, otherwise it will use normal string.Format

From my quick tests, it seems to indicate that creating a new array lazily on demand might be a good tradeoff that wouldn't add too much complexity?

I'll see if I can get the dotnet/runtime repo to build locally for me so I can get some more data to compare them with the real code instead and also run all unit tests so I don't break any functionality as well.. ;).

> For `IEnumerable` values, I suspect the `string.Join(", ", enumerable.Cast<object>().Select(o => o ?? NullValue))` expression in `LogValuesFormatter.FormatArgument(object)` causes so many allocations that the array does not matter. And if the log level is disabled, then the log entry won't be formatted anyway.

I saw that this was optimized and changed recently in https://github.com/dotnet/runtime/pull/47873
