### ISSUE TITLE
Why GC doesn't collect the object?

### ISSUE THREAD

**Issue by heku** [dotnet/runtime#36213]
I'm facing a confused GC collection behavior, the following code is to test whether GC collect LOH object "as expected".
I build the code under x86 + Debug, as I want to use the 2G memory limitation for test, I try allocating a 850M byte array in a while loop, the '850' comes from my test, which I suppose I can allocate one such array, but I cannot allocate another one, so that I can realize a out of memory error if GC doesn't free the previous one. You can tweak this value on your machine.

My test machine installed x64 OS and has more than 2G available memory.

.netcore 3.1 console app (x86 + Debug)
```csharp
    // Out of memory, why?
    while (true)
    {
        _ = new byte[850 * 1024 * 1024];
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }

    // Out of memory, why?
    while (true)
    {
        var a = new byte[850 * 1024 * 1024];
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }

    // Out of memory, why?
    while (true)
    {
        var a = new byte[850 * 1024 * 1024];
        a = null;
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }
```

Same tests on .NET Framework (4.6.1 and 4.8)
```csharp
    // No out of memory, as expected!
    while (true)
    {
        _ = new byte[850 * 1024 * 1024];
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }

    // Out of memory, why?
    while (true)
    {
        var a = new byte[850 * 1024 * 1024];
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }

    // No out of memory, as expected!
    while (true)
    {
        var a = new byte[850 * 1024 * 1024];
        a = null;
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }
```
And on .NET Framework, if I put the code in `try` block, then all of them out of memory.
```csharp
try{
    // case1
    // Out of memory, why?
    while (true)
    {
        _ = new byte[850 * 1024 * 1024];
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    } 
    // case2
    // Out of memory, why?
    while (true)
    {
        var a = new byte[850 * 1024 * 1024];
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }
    // case3
    // Out of memory, why?
    while (true)
    {
        var a = new byte[850 * 1024 * 1024];
        a = null;
        Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
    }
} catch { ... }
```
But if I move code into methods, the results different again.
```csharp
try { 
Case1();   // No out of memory now.
or
Case2();  // Still out of memory.
or
Case3();  // No out of memory now.
} catch { ... }
```

I didn't find any doc on these behavior, so I posted the questions here.

Thank you.

**Comment by benaadams** [comment]
Try under Release; the Jit may extend the lifetime of objects in Debug to assist with debugging (so you can look at the state of an object after the last line that references it has passed; i.e. to answer the question "how did I get here?")

**Comment by heku** [comment]
Thank you, will do.
I just built the app under Debug and run it normally via .exe, not run it in VS debug session.

**Comment by jkotas** [comment]
This JIT optimizations can extend variable lifetimes till end of method. The JIT optimizations depend on many subtle details, and vary from version to version. It explains the behavior differences that you are seeing.

Check these discussions for details:

https://github.com/dotnet/runtime/issues/9328
https://github.com/dotnet/runtime/issues/6157#issuecomment-226574611

**Comment by heku** [comment]
Tested some of them in Release, still not works as expected. I suppose all of these can work without out of memory, or at least except case2, all others should work.

**Comment by Clockwork-Muse** [comment]
... In release mode, is it possible the JIT/Roslyn might remove those allocations anyways?

**Comment by jkotas** [comment]
You are right that the GC does not seem to try as hard as it should. 

Specific repro:

```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Work()
    {
        GC.KeepAlive(new byte[850 * 1024 * 1024]);
    }

    static void Main(string[] args)
    {
        Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture);
        while (true)
        {
            Work();
            Console.WriteLine(GC.GetTotalMemory(true) / 1024f / 1024);
        }
    }
}
```

```
netcoreapp3.1
dotnet publish -r win-x86
```

Result:
```
X86
0.048168182
0.050281525
0.050281525
Out of memory.
```

**Comment by Maoni0** [comment]
@jkotas I cannot repro this, on x86 or x64 on 5.0. maybe try with while(Sleep(1)) instead of while(true)?

**Comment by Maoni0** [comment]
okie..so I tried this in release with both 3.1 and 5.0. on 5.0 it never fails. in 3.1 it was failing right away (doesn't even give me any iterations at all, right away it says
```
X86
Out of memory.
```
I was wondering if this has something to do with not giving a chance for the virtual memory manager to actually free up the memory so I added a Thread.Sleep(1) in the loop and that ran fine, I never get OOM; then I reverted it back and made sure I'm running the new .exe, and that also never fails :thinking: 

can you try to see if this is the behavior for you too, @jkotas?

**Comment by jkotas** [comment]
I do see that the behavior is not deterministic - it sometimes fails right away, sometimes after a few iterations, and sometimes runs for while.

**Comment by Maoni0** [comment]
so my theory is this is simply because when GC is trying to acquire a new segment to accommodate this 850mb object and it fails to do so. if I change it to 500mb it never fails. I thought this might have something to do with ASLR but it still fails with 850mb after I set the DYNAMICBASE to NO, although I'm not sure it's set correctly (I used editbin) because link can't even dump most of the header info for the bin that dotnet.exe created.

this never fail with the x64 version which means GC does not keep the object alive - GetTotalMemory(true) always returns a small value, as it should.

**Comment by Maoni0** [comment]
so my theory is this is simply because when GC is trying to acquire a new segment to accommodate this 850mb object, even when there are other such objects in memory, it still fails to do so. if I change it to 500mb it never fails so it can't be because GC keeps the objects alive. I thought this might have something to do with ASLR but it still fails with 850mb after I set the DYNAMICBASE to NO, although I'm not sure it's set correctly (I used editbin) because link can't even dump most of the header info for the bin that dotnet.exe created.

this never fail with the x64 version which means GC does not keep the object alive - GetTotalMemory(true) always returns a small value, as it should.

**Comment by heku** [comment]
I beliveve your point that it cant because GC keep it alive. 
Maybe a more correct desc about the question is "why GC not free the memory in time as expected?"

**Comment by Maoni0** [comment]
no, my point is GC couldn't even get 850mb the 1st time around, that's why it sometimes gets OOM right away, not even completing the very 1st iteration. there was nothing to free at that point. and if it's because GC didn't free it, it shouldn't succeed when I changed it to 500mb. 

and the behavior in 64 bit also proves this - in 64 bit there's no problem getting 850mb and we can run forever as expected. GC does not have a different to determine if something is freeable in 64-bit vs 32-bit.

**Comment by heku** [comment]
Yes, sometimes the result is a little random, not every time OOM occurs at very 1st iteration, changed it to 500MB or others might work, but my code was designed to test this problem out, so even x64 or 500MB worked as expected, I'm afraid current CLRs (both .NET Framework and .NET Core) have this GC bug, or at least, this behavior should be estimatable.

**Comment by Clockwork-Muse** [comment]
>no, my point is GC couldn't even get 850mb the 1st time around, that's why it sometimes gets OOM right away, not even completing the very 1st iteration. there was nothing to free at that point. and if it's because GC didn't free it, it shouldn't succeed when I changed it to 500mb.
>
>and the behavior in 64 bit also proves this - in 64 bit there's no problem getting 850mb and we can run forever as expected. GC does not have a different way to determine if something is freeable in 64-bit vs 32-bit.

It may or may not have different codepaths, but what it has is a differently sized _address space_.  850MB is about 1/5 of the _entire_ (theoretical - there's a lot of things that push limits lower) address space for a 32-bit process.

In a 64-bit process, your memory limits are way higher (about ~40 bits worth of address space, IIRC).  

In Java I seem to recall that (at least some) runtimes could be configured for the max memory they would allocate, not sure about .NET Core.

**Comment by Maoni0** [comment]
that's exactly why I'm saying this is not because GC is not letting the objects go; it just means GC can't successfully get a contiguous virtual address range that's 850mb big. it's not just about the ratio of the total address space - it has to be contiguous. in 64-bit since the VA range is so much bigger, it's always successful at getting such an address range. and GC is always letting the object go (otherwise you'd run out of physical memory pretty quickly).

**Comment by mjsabby** [comment]
Just a thought, I wonder if playing with hard limit can yield some determinism if that helps in any way.

**Comment by Maoni0** [comment]
hardlimit is only supported on 64-bit, a big reason for that is because it's very difficult to reserve a lot of memory due to limited VA space. you already only get 2g-4g and since right now we over reserve because we don't know if your objects will be on SOH or LOH (that part will get better going forward but for this issue if we can't reserve 850mb of VA space we can't, doing it a bit earlier in the process could help but it's very unpredictable). 

I'll close this isssue but feel free to reopen if you'd like to discuss more.

**Comment by heku** [comment]
@Maoni0 do you mean there won't any fix on this? If so, can somebody explain why in some of my tests, put the code inside a `try` always got OOM, and move code inside `try` into a sepeared method always work?

**Comment by Maoni0** [comment]
there's no bug in GC AFAICS. GC is clearly letting the memory go. you are requesting a large amount of VA range and sometimes you don't get it. GC is merely calling the VirtualAlloc API to request this much memory from the OS and when the OS can't give the amount of memory you requested it will throw OOM. moving things around may cause the virtual addresses to be laid out differently. you could try things like disabling ASLR and making it large address aware but it's a gamble.

**Comment by Clockwork-Muse** [comment]
@Maoni0 - That's not what @heku is experiencing, though; they're able to get initial allocations (meaning they can get that much memory).  And @jkotas 's work showed that GC is perhaps not being agressive enough.

**Comment by Maoni0** [comment]
> And @jkotas 's work showed that GC is perhaps not being agressive enough.

not really, both @jkotas and I observed that this is random - @jkotas showed a result where it was able to get the memory *and* release the memory (this is the part where GC released memory) because the 3 numbers are all very small. if GC didn't release the memory you should see the numbers going up. I also observed this. and I showed a result where it's just not able to get 850mb to begin with. when it could get the memory, GC always releases it in the full blocking GC that GetTotalMemory(true) requests. it has NOTHING to do with the GC tuning. this is just you request GC to make the heap the smallest it can and it does that.
