### ISSUE TITLE
FileConfigurationProvider becomes empty for short amount of time while reloading

### ISSUE THREAD

**Issue by VasiliyNovikov** [dotnet/runtime#36244]
When using any configuration provider based on `FileConfigurationProvider` with `reloadOnChange == true` then during reloading it gets empty set of keys for short amount of time - it affects the code which watches and relay on those keys' values

This line causes the issue:
https://github.com/aspnet/Extensions/blob/beb26b875e042f5347f98e464faaaebc1c288c35/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L79

```
$ dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84
```

**Comment by ericstj** [comment]
Interestingly this used to not create an empty dictionary.  That was added by @HaoK https://github.com/aspnet/Configuration/commit/36ec5b0f8d07f04e81650041ffb2b740bd1fd29c.  At that time most providers seemed to completely set Data rather than append to it.  We should probably try to understand the purpose of that change before removing new Dictionary.

**Comment by HaoK** [comment]
Its been ages since I made those changes, but from what I recall, the reason we need to clear the dictionary was due to reloading the configuration requiring dropping all the old keys and values. 

```
               // Always create new Data on reload to drop old keys
                if (reload)
                {
                    Data = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }
``` 

Otherwise reloading configuration would just result in adding new keys over time

**Comment by HaoK** [comment]
My guess, is that the reason we do this in the base class, is if Load fails on a reload, we want an empty dictionary.  We could try to avoid creating the empty dictionary and only doing that if Load fails.  So the old values would be visible during reload, and if reload fails, you end up with an empty dictionary, otherwise whatever dictionary load set
