### ISSUE TITLE
Resolve typeof(T).GUID to a runtime constant where possible

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#36272]
This would be particularly useful for COM interop where getting the GUID of the type is often necessary, for e.g `IUnknown::QueryInterface` or `ID3D12Device::CreateFence`. Currently it goes to an FCALL, `ReflectionInvocation::GetGUID`, which results in codegen like this

```
C.guid[[System.Int32, System.Private.CoreLib]]()
    L0000: push rsi
    L0001: sub rsp, 0x30
    L0005: vzeroupper
    L0008: mov rsi, rdx
    L000b: mov rcx, 0x7ffa1aacb1e8
    L0015: call 0x7ffa7a5cb730
    L001a: mov rcx, rax
    L001d: lea rdx, [rsp+0x20]
    L0022: vxorps xmm0, xmm0, xmm0
    L0026: vmovdqu [rdx], xmm0
    L002a: lea rdx, [rsp+0x20]
    L002f: call System.RuntimeType.GetGUID(System.Guid ByRef)
    L0034: vmovdqu xmm0, [rsp+0x20]
    L003a: vmovdqu [rsi], xmm0
    L003e: mov rax, rsi
    L0041: add rsp, 0x30
    L0045: pop rsi
    L0046: ret
```

category:cq
theme:optimization
skill-level:intermediate
cost:medium

**Comment by john-h-k** [comment]
I think I have a rough prototype going, except i'm not sure how it works for `FEATURE_COMINTEROP` or `FEATURE_COMINTEROP_UNMANAGED_ACTIVATION`, which seem to have different code in `GetGUID`

**Comment by john-h-k** [comment]
Also `Type.GUID` is abstract. Is this an issue for applying the `[Intrinsic]` attribute

**Comment by AndyAyersMS** [comment]
> This would be particularly useful ...

Can you provide more details? "Useful" as in improved perf?

**Comment by john-h-k** [comment]
> "Useful" as in improved perf?
Yes. The only current alternative is to manually write out the GUIDs and access them by name, which isn't fun, high effort, and is bugprone. And using `typeof(T).GUID` right now is too slow for hot code

**Comment by AndyAyersMS** [comment]
It would be helpful if you could come up with a benchmark and add it here, so we have a sample use case and can quantify the impact of the current approach. And I'm curious to see what your "rough prototype" looks like.

Going to mark this as future, just for our own accounting.

**Comment by tannergooding** [comment]
Just noting that most native APIs I've encountered that take a `Guid` (largely the DirectX APIs) take it as a `const GUID &` (and more rarely a `const GUID *`), so you would still have a copy to the stack and then taking the address of the local in that scenario. I wonder if there is something we could do to improve that scenario as well?

**Comment by jkotas** [comment]
Store the Guid in a readonly static? 

Making sure that the guid operations are as efficient as they can be is really a problem for interop code generators to solve.

**Comment by tannergooding** [comment]
Is using `Unsafe.AsPointer()` on a `readonly static T` where `T` is a blittable value type safe or does it need to be pinned?

**Comment by jkotas** [comment]
Needs to be pinned.

**Comment by tannergooding** [comment]
So improving the perf of `typeof(T).GUID` would basically just better support the generic scenario (such as `bool QueryInterface<TUnknown>(TUnknown** ppUnknown) where T : unmanaged`).

**Comment by john-h-k** [comment]
@tannergooding yes, and also from a convenience/bug point of view it is a little cleaner and lower chance of messing up the GUID.

@AndyAyersMS here is the benchmark
```cs
public unsafe class GUIDBenchmark
    {
        private class FakeComObject
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            public virtual void Baz(Guid* iid) { }
        }

        private FakeComObject Bar = new FakeComObject();

        [Benchmark]
        public void WithStaticReadonlyGuid()
        {
            var iid = D3D12.IID_ID3D12CommandAllocator;
            Bar.Baz(&iid);
        }

        [Benchmark]
        public void WithStaticReadonlyPinnedGuid()
        {
            fixed (Guid* iid = &D3D12.IID_ID3D12CommandAllocator)
            {
                Bar.Baz(iid);
            }
        }

        [Benchmark]
        public void WithTypeof_Guid()
        {
            var iid = typeof(ID3D12CommandAllocator).GUID;
            Bar.Baz(&iid);
        }
    }```

and results

|                       Method |       Mean |     Error |    StdDev |
|----------------------------- |-----------:|----------:|----------:|
|       WithStaticReadonlyGuid |   1.268 ns | 0.0099 ns | 0.0093 ns |
| WithStaticReadonlyPinnedGuid |   1.281 ns | 0.0020 ns | 0.0019 ns |
|              WithTypeof_Guid | 194.504 ns | 1.8829 ns | 1.7612 ns |

**Comment by svick** [comment]
@john-h-k Why isn't caching the result of `typeof(T).GUID` in a `static readonly` field and then accessing that good enough? Effectively, it would be like your first two benchmarks, except that you declare the field yourself.

**Comment by john-h-k** [comment]
I mean, that is what it is right now with `D3D12.IID_foo`. But it's inconvenient, easy to mess up, and doesn't play well with generic methods.

**Comment by AaronRobinsonMSFT** [comment]
@john-h-k Are you basically asking for the JIT to make access to `typeof(T).GUID` be as optimized as static access? The call to the `GUID` property does basically one of 4 things - the code is [here](https://github.com/dotnet/runtime/blob/4224c4c16274b99791fbcc4e8fc987e64c4aaead/src/coreclr/src/vm/methodtable.cpp#L7462).

1) Return the `GUID` if it was stored on the type - there are several cases when this isn't done.
1) Query the type for the `GuidAttribute`.
1) Compute the `GUID` based on a seed of the concatenated string of the assembly, type name, and various other things. This is the typical case as well as for COM.
1) Compute the `GUID` based on the WinRT algorithm: https://docs.microsoft.com/uwp/winrt-cref/winrt-type-system#guid-generation-for-parameterized-types

I think there are opportunities here to make the current code path more efficient. I don't know how easy it would be to convey this information to the JIT in a way that would allow it to make the GUID a constant value. I think we could probably get the delta between the two approaches smaller, but not equivalent.

**Comment by john-h-k** [comment]
Yes, that was my ideal scenario. Shame it doesn't seem possible :(. Could
the second (and possibly first) ones be resolved to a single static? I
would guess they are the easiest to do so, and they would be enough in a
lot of COM scenarios (as bindings can generate the GuidAttribute)

**Comment by AaronRobinsonMSFT** [comment]
>Could the second (and possibly first) ones be resolved to a single static?

If by "single static" you mean in native code, they are. However, I assume the desire would be have this in managed code so an assembly or class constant and metadata isn't something the JIT is permitted to alter - at least I don't think it is? @AndyAyersMS.

What could happen here is that during compilation the Roslyn compiler could detect that the `GuidAttribute` exists on the type and create a static in the assembly with the value. It could then convey that information in perhaps a new attribute (e.g. `GuidConstantTokenAttribute`) that would indicate the token the JIT could then use. The reason for this dance is the fact that `GUID` is a vestige of the close relationship with COM and not really of much interest outside of that scenario. It was lazily done because it isn't typically needed in .NET scenarios so we are at the "pay-for-play" argument. The `GuidAttribute` is a mitigation since COM required a predefined `GUID` and the generation algorithm couldn't be made backwards compat because the way users generate `GUID`s for COM isn't prescribed.

There are solutions here, but would probably require compiler work to get at performance parity. As mentioned there does seem to be an opportunity to make the path faster, but my guess is using code generation solutions for COM would provide more value than trying to optimize the current path.

**Comment by john-h-k** [comment]
> However, I assume the desire would be have this in managed code so an assembly or class constant and metadata isn't something the JIT is permitted to alter

Surely it is fine if it only reads the GUID?

**Comment by jkotas** [comment]
> using code generation solutions for COM would provide more value than trying to optimize the current path.

+1

**Comment by AaronRobinsonMSFT** [comment]
>Surely it is fine if it only reads the GUID?

I don't understand this statement, The `GUID` is a property that immediately calls into another function. There is no static/constant defined in managed code. The value contained in the `GuidAttribute` is a `string` _not_ a [`Guid`](https://docs.microsoft.com/dotnet/api/system.guid), which means that needs to be retrieved and interpreted as a `Guid`. This is usually stored for quicker access as mentioned in (1) above, but there are cases where it is not stored so must be computed again in those scenarios. Further optimizing this quick access path and perhaps reducing the number of scenarios where it must be computed could make this faster, but converting it into a constant is difficult because we would need to tell the JIT when the computed value can be stored and additionally that it can be placed somewhere as a constant.

To reiterate I am not saying it isn't possible just that the effort to make this faster would need to involve a decent amount of knowledge being shared with the JIT _or_ some additional Roslyn (compiler) optimizations. Both those paths seem like a lot more work than simply doing the work through a source generator for COM which would yield some additional benefits.

**Comment by BruceForstall** [comment]
It looks like the consensus here is to make improvements outside of the JIT, so I'm closing this.
