### ISSUE TITLE
.Net should support Logarithmic function with base 2 like log2 in c/c++

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#363]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/689106/建议net支持以2为基的对数函数-net-should-support-logarithmic-fu.html)._

---
<p>Math.Ceiling(Math.Log(i, 2)) in C# gets the right results in general for positive integer i.</p><p>But it goes wrong when i is 536870912(the 29 th power of 2).</p>

---
#### bysdxt on 8/9/2019, 09:07 AM: 

<p>(uint)2147483648 has the same probrem</p>

#### Visual Studio Feedback System on 11/26/2019, 05:52 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it

**Comment by danmosemsft** [comment]
@tannergooding 

(Seems like Math ideally would get the numerics tag, although it's in runtime.extensions)

**Comment by tannergooding** [comment]
`Math.Log(value, base)` is error prone because it only computes the result as `Log(value) / Log(newBase)` and so it can incur multiple levels of rounding error.  Like many of the math functions, it is non-trivial to implement and would require significant work to ensure it always returns the correct result (and unlike many of the other math functions does not have an existing C Runtime implementation we can call into).

We added `System.Math.Log2(double)`, `System.MathF.Log2(float)`, `System.Numerics.BitOperations.Log2(uint)` and `System.Numerics.BitOperations.Log2(ulong)` in .NET Core 3.0 which should compute the correct result and cover the scenario initially requested.
