### ISSUE TITLE
Marshalling VT_SAFEARRAY VARIANT to managed object does not lock when accessing array data

### ISSUE THREAD

**Issue by hughbe** [dotnet/runtime#36450]
In `OleVariant::MarshalSafeArrayForArrayRef`, we marshal `SAFEARRAY`  to an object array

https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/src/coreclr/src/vm/olevariant.cpp#L4611

Notice that we access `SAFEARRAY->pvData`

I don't see any calls to `SafeArrayLock` or `SafeArrayAccessData`.

This means that we someone can end up deleting the data while we are reading from it

Spotted writing a managed implementation in https://github.com/dotnet/winforms/pull/3197

I am not sure whether this is actually a problem in practice, as I'm not very accustomed with native code, but worth investigating, as the docs say we should

Also see https://microsoft.public.vc.atl.narkive.com/vS1ILjY1/safearraylock-why-is-it-required

/cc @weltkante @AaronRobinsonMSFT

**Comment by weltkante** [comment]
I don't think SafeArrayLock is about thread safety, its probably just a usage counter. The docs themselves say SafeArrayLock is _not_ threadsafe.

> If these functions are called concurrently from different threads on the same SAFEARRAY data type instance, an inconsistent lock count may be created. [...] You can prevent this by providing your own synchronization code.

The "lock" terminology is about "locking the memory in place" - i.e. to prevent moving it around when resizing the array. Corresponding move operations will fail.

This is required if you store the pointer in some variable to operate on the array, and then want to call some helper function. If you want to guarantee that the helper function can't delete/move/resize the array you can lock it.

**Comment by weltkante** [comment]
> This means that we someone can end up deleting the data while we are reading from it

I don't think that can happen, the data structure is not threadsafe (see collapsed comment about threadsafety)

**Comment by hughbe** [comment]
According to https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-safearraylock

> An array cannot be deleted while it is locked.

**Comment by weltkante** [comment]
Yes, if you say you are intending to keep a pointer into the array (by locking it) then deleting the array would be fatal (dangling pointer, access violations or other security issues if accessed). I don't think thats relevant though, the snippet you showed doesn't store a pointer and memcpyNoGCRefs is not going to delete the safearray either.

**Comment by AaronRobinsonMSFT** [comment]
>I don't think SafeArrayLock is about thread safety, its probably just a usage counter. The docs themselves say SafeArrayLock is not threadsafe. If its not threadsafe its purpose can't be thread safety.

@weltkante That is correct. The `SAFEARRAY` concept is from the Automation world and really targeted at VB and C/C++ interaction. Since VB legacy (unsure what to call it, VB6?) was STA only there was no concept of race conditions from the script side, but there was an issue with references. It is really a corollary to the COM `AddRef()`/`Release()` semantics.

There are 4 uses of this API in the code base. Let's go through each of them.

This one is done via a marshalling call and we created the `SAFEARRAY` during initialization so we own the lifetime and no one knows about the `SAFEARRAY` yet.

https://github.com/dotnet/runtime/blob/ddd458e8beb5ca7711b6082aeb8ed88f6580512e/src/coreclr/src/vm/ilmarshalers.cpp#L4917-L4922

We create the `SAFEARRAY` prior to calling the function in both of these locations. So no issue here either.

https://github.com/dotnet/runtime/blob/fcd862e06413a000f9cafa9d2f359226c60b9b42/src/coreclr/src/vm/dispparammarshaler.cpp#L312-L317

https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/src/coreclr/src/vm/olevariant.cpp#L4176-L4177

The next invocation is a part of a very convoluted scenario. This path represents support for late bound `Invoke` and is utilized in .NET Reflection or `IDispatch` scenarios. I would be surprised if there is an issue here, but that is a bit difficult to prove without debugging through all the code paths. I also accept there could be a bug here, but unless we observe a real user impacted issue I'm not inclined to change any of this. If you can create a scenario where this fails, feel free to file an issue with a repro and we can address that.

https://github.com/dotnet/runtime/blob/5178041776634bfbc4f868425710e60d95f7066f/src/coreclr/src/vm/dispatchinfo.cpp#L2345-L2346

**Comment by AaronRobinsonMSFT** [comment]
The usage lock appears unnecessary in this code path. Please file an issue with a repro if a case can be found.
