### ISSUE TITLE
GetOrCreate is not atomic which is a serious issue for a cache ( eg poor perf and memory issues)

### ISSUE THREAD

**Issue by bklooste** [dotnet/runtime#36499]
This blog provides the detail 

https://tpodolak.com/blog/2017/12/13/asp-net-core-memorycache-getorcreate-calls-factory-method-multiple-times/

We see poor performance in 1 in 10 queries due to multiple invokes when not needed even under non high load conditions and have had to resort to a similar solution to that blog post which is not great . 

This was closed with no good reason https://github.com/aspnet/Caching/issues/359

**Comment by alastairtree** [comment]
Another work around that implements the use of Lazy, and the locking required to stop a different version ending up in the cache is to use [LazyCache](https://github.com/alastairtree/LazyCache), a library that is available on nuget I wrote to solve these issues. 

It wraps MemoryCache with the additional stuff required to make the lambda atomic as requested in this issue. It is also likely to perform better than the nice code provided by @BladeWise because of some smarts in the way the locks are collated by cache key and do not use SemaphoreSlim. Hopefully it helps some people who might stumble on this issue when their cache is not working as expected.

**Comment by jodydonetti** [comment]
On top of the great LazyCache, may I suggest taking a look at [FusionCache ⚡🦥](https://github.com/jodydonetti/ZiggyCreatures.FusionCache) as another option for a concurrent-factory-calls optimized cache?

It is also optionally multi-level (memory + distributed) and it has some other advanced features you may be interested in, like a fail-safe mechanism (see [here](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/FailSafe.md)) , soft/hard timeouts with background factory completion (see [here](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/Timeouts.md)) and more.

I just released it and, if you find it helpful, that would be great to know.

/shameless-plug

Also, any comment on it would be greatly appreciated!

**Comment by rmandvikar** [comment]
2c: I'd like to see this bug fixed, as not many devs realize this. It seems the stance is to not fix it and in which case, I'd like to throw in another impl here. /shameless-plug

The impl (implementation) (called `CacheWithTaskAndLockPool` in repo) caches the _task itself_ instead of the value, but creates the task inside a lock which is fetched from a lock pool (it can be concurrent map even). Concurrent requests get the same task. The task is then awaited _outside_ of the lock to get the value. A task, if it "errors" out (canceled or faulted), is evicted using an `IChangeToken`. It perfs the same when compared with an impl that uses LazyCache (authored by @alastairtree). [See here](https://github.com/rmandvikar/threading#cache-impls) and look for `CacheWithTaskAndLockPool`, and `CacheWithLazyCache` along with tests.

**Comment by maryamariyan** [comment]
Closing as dupe of https://github.com/dotnet/runtime/issues/36500#issuecomment-1090517755

**Comment by rmandvikar** [comment]
2c: I feel a snippet in the msdn article providing an example of using lazy<t> would be helpful. There is a comment in here with many upvotes.
