### ISSUE TITLE
Add support for interpolation within appsettings

### ISSUE THREAD

**Issue by Eilon** [dotnet/runtime#36506]
_From @jkotas on June 27, 2018 2:26_

_From @BlacKCaT27 on June 26, 2018 14:13_

Currently, any app configuration entries in your appsettings.json file must be a direct value type, ex:

    "TargetDirectories": {
        "RootDir": "/path/to/rootdir/",
        "SubDir1": "subdir1",
        "SubDir2": "subdir2"
    }

If I, as a developer, want to concatenate or otherwise combine configuration parameters, I have to wire all of it up manually within my code:

    public class TargetDirectories
    {
        public string RootDir { get; set; }
        public string SubDir1 { get; set; }
        public string SubDir2 { get; set; }
        public string FullDirectoryPath => $"{RootDir}/{SubDir1}/{SubDir2}";
    }

This is more error prone and verbose than it could be, especially since a proper implementation would likely want to check to ensure configuration values were parsed properly and exist on the model object prior to accessing them.

My hope is that support could be added to interpolate values within the config file such that combinations like the above example could be defined solely within the configuration file itself:

    "TargetDirectories": {
        "RootDir": "/path/to/rootdir/",
        "SubDir1": "subdir1",
        "SubDir2": "subdir2",
        "FullDirectoryPath": "${RootDir}/${SubDir1}/${SubDir2}"
    }

(note: I'm using the same syntax used by [the python configparser library](https://docs.python.org/3.4/library/configparser.html#interpolation-of-values) just for the sake of example. Whatever syntax is most appropriate for .net core could be chosen.)

This would follow the same expected behavior as the rest of the existing configuration tools, such that we could still map our configuration entries to a configuration model class:

    public class TargetDirectories
    {
        public string RootDir { get; set; }
        public string SubDir1 { get; set; }
        public string SubDir2 { get; set; }
        public string FullDirectoryPath { get; set };
    }
```

// Startup.cs

public void ConfigureServices(IServiceCollection services)
{
...

    services.Configure<TargetDirectories>(Configuration.GetSection("TargetDirectories"));

...
}
```

Thoughts?

_Copied from original issue: dotnet/corefx#30666_

_Copied from original issue: aspnet/Home#3271_

**Comment by BlacKCaT27** [comment]
Hey there, thanks for taking the time to respond. I appreciate the well thought out answer.

I have to admit, when I initially proposed this idea years ago I didn't have nearly as firm a grasp on the config system as I do now. Having a much deeper knowledge of it due to my recent work, I definitely understand the hesitation.

I completely agree that the layered implementation would be the expectation, and what such a feature should support.

I do have some high level ideas of how I could see an implementation working. I'll leave them here to maybe at some point give whoever might regroom the ticket some things to think about. (This is just me thinking off the top of my head, so please excuse if I miss some obvious reason why this wouldn't work; it's late here. :) )

After all configuration providers have reported their key:value pairs to the config system, an analysis is run on each value to look for any reserved symbols (`$` , `{`, `}`, just as an example). If the matching syntax is found, extract the value between the symbols, and use it do a key lookup on the full dictionary of config data. If the key is found, copy the value into the location where the key name was found and remove the reserved symbols.  If no value is found, leave the reserved symbols and key string in place to make it easy to debug which lookup failed. You could even make a config setting to change that behavior to something else, like leaving a blank value, potentially.

By waiting until all configuration providers have been loaded, you skip needing to care about the layering all together. By doing so, you end up following the same behavior as any other configuration override where the last provider to give a value 'wins'. Only in this case, the provider giving the value is the aggregate of all providers, and the 'winner' is just one of the existing configuration values.

**Comment by BlacKCaT27** [comment]
Actually, I may just write a library to do this...

**Comment by maryamariyan** [comment]
> Actually, I may just write a library to do this...

@BlacKCaT27 were you able to add your library? Just in case someone finds this issue later and was interested in the library.

Closing issue based on the conversation. We could reopen if there's more discussion building up.

**Comment by BlacKCaT27** [comment]
I did try to and almost succeeded, but unfortunately there's no way to
write key-value pairs back into the system after the configuration
providers have been resolved.
