### ISSUE TITLE
Empty lists are bound as nulls

### ISSUE THREAD

**Issue by DumpsterDoofus** [dotnet/runtime#36504]
### Minimal working example

Consider the following `Main` method:

```
static void Main(string[] args)
{
    var c = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json")
        .Build()
        .GetSection("Things")
        .Get<string[]>();
}
```

#### Case 1

With the following config, `c` has 2 items:

```
{
    "Things": [
        "Value1",
        "Value2"
    ]
}
```

#### Case 2

With the following config, `c` has 1 item:

```
{
    "Things": [
        "Value1"
    ]
}
```

#### Case 3

With the following config, `c` is `null`:

```
{
    "Things": [
    ]
}
```

#### Case 4

With the following config, `c` is null:

```
{
}
```

### Notes

In Case 3, I would expect a list with 0 items. I find it surprising that an empty list is considered null. This causes trouble for settings validation, because there are legitimate use cases where an empty list is valid. Because empty lists are treated the same as nulls, it's not possible to distinguish between the configuration system correctly specifying an empty list (Case 3), and a total binding failure (Case 4) or other problem ingesting `IConfiguration`. 

Although the minimal example above uses strings, the behavior is the same for more complex objects.

**Comment by vaz-rodrigo** [comment]
Can I work on this issue?

**Comment by vaz-rodrigo** [comment]
I've been trying to work on this issue but I think it might be bigger than was initially expected. One of the reasons the arrays are null is because the JsonConfigurationFileParser adds the elements of the array and not the array itself to the underlying ConfigurationProvider.

This implies that the solution involves not just changing the Extension.Configuration.Binder, but also checking if the concrete implementations of ConfigurationProvider are outputing empty arrays (or anything that resembles that...)

I checked with XML and empty tags (not self-closing ones) are actually added to the ConfigurationProvider Data Dictionary with an empty value, so maybe this can be the default for empty arrays in JSON or other ConfigurationProviders too?

**Comment by maryamariyan** [comment]
> Can I continue to work on this issue if it is still valid?

Were you able to make progress here. Are you interested in submitting a PR for it?

**Comment by maryamariyan** [comment]
Related to https://github.com/dotnet/runtime/issues/36510
