### ISSUE TITLE
GetOrCreateExclusive() and GetOrCreateExclusiveAsync(): Exclusive versions of GetOrCreate() and GetOrCreateAsync()

### ISSUE THREAD

**Issue by rmja** [dotnet/runtime#36500]
It would be nice with equivalents of `GetOrCreate()` and `GetOrCreateAsync()` where it is ensured that the factory is only invoked once for each cache miss.

This basically resolves https://github.com/aspnet/Caching/issues/218, but with alternate extension methods.

An implementation proposal:

```cs
public static TItem GetOrCreateExclusive<TItem>(this IMemoryCache cache, object key, Func<ICacheEntry, TItem> factory)
{
    object result;

    if (!cache.TryGetValue(key, out result))
    {
        SemaphoreSlim exclusiveLock;

        lock (cache)
        {
            exclusiveLock = cache.GetOrCreate("__exclusive__", entry => {
                entry.Priority = CacheItemPriority.NeverRemove;
                return new SemaphoreSlim(1);
            });
        }

        exclusiveLock.Wait();

        try
        {
            if (cache.TryGetValue(key, out result))
            {
                return (TItem)result;
            }

            var entry = cache.CreateEntry(key);
            result = factory(entry);
            entry.SetValue(result);
            entry.Dispose();
        }
        finally
        {
            exclusiveLock.Release();
        }
    }

    return (TItem)result;
}

public static async Task<TItem> GetOrCreateExclusiveAsync<TItem>(this IMemoryCache cache, object key, Func<ICacheEntry, Task<TItem>> factory)
{
    object result;

    if (!cache.TryGetValue(key, out result))
    {
        SemaphoreSlim exclusiveLock;

        lock (cache)
        {
            exclusiveLock = cache.GetOrCreate("__exclusive__", entry => {
                entry.Priority = CacheItemPriority.NeverRemove;
                return new SemaphoreSlim(1);
            });
        }

        exclusiveLock.Wait();

        try
        {
            if (cache.TryGetValue(key, out result))
            {
                return (TItem)result;
            }

            var entry = cache.CreateEntry(key);
            result = await factory(entry); //.ConfigureAwait(false);
            entry.SetValue(result);
            entry.Dispose();
        }
        finally
        {
            exclusiveLock.Release();
        }
    }

    return (TItem)result;
}
```

**Comment by theodorzoulias** [comment]
Related StackOverflow question: [Stop Reentrancy on MemoryCache Calls](https://stackoverflow.com/questions/65640644/stop-reentrancy-on-memorycache-calls/)

**Comment by deeprobin** [comment]
For completeness. If I understand correctly, the following is proposed here:
```cs
namespace Microsoft.Extensions.Caching.Memory {
    public static partial class CacheExtensions {
        public static TItem GetOrCreateExclusive<TItem>(this IMemoryCache<TItem>, object key, Func<ICacheEntry, TItem> factory);
        public static Task<TItem> GetOrCreateExclusiveAsync<TItem>(this IMemoryCache<TItem>, object key, Func<ICacheEntry, Task<TItem>> factory)
    }
}
```

An implementation example has already been given by @rmja in top post.

I myself have not worked much with `Microsoft.Extensions.Caching.Memory`. Therefore I cannot say much about it.
@maryamariyan Is this a relevant API? If yes, you could take a look at it (this issue is already a bit older than 5 years).

**Comment by maryamariyan** [comment]
> I myself have not worked much with Microsoft.Extensions.Caching.Memory. Therefore I cannot say much about it.
@maryamariyan Is this a relevant API? If yes, you could take a look at it (this issue is already a bit older than 5 years).

[`GetOrCreate`](https://source.dot.net/#Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs,d5560184862c46ed) is not thread safe and for that to become possible there would need to be lock statements added into MemoryCache and due to perf regression concerns I don't think we will go with that change fix this thread safety issue.

I don't think we would want these extension methods added built-in to the library. Doesn't seem like a bigger value add than just letting whomever needs this functionality to just add it directly into their code. Would make sense to keep the onus on the app side to make sure they keep their transactions thread safe by also assuring they don't make calls to `GetOrCreate`, otherwise as explained in this issue it could lead to factory method in `GetOrCreate` getting called multiple times, etc. for a given cache miss in a multithreaded scenario.

Closing as won't fix.
