### ISSUE TITLE
Assertion failed 'varDsc->lvExactSize == 12'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#36586]
Failure in libraries System.Numerics.Vectors.Tests: release libraries, checked coreclr with:
```
set COMPlus_JitStress=1
```
(note that TieredCompilation is the default 1)

Windows x64

E.g.,
```
build -s libs+libs.tests -runtimeConfiguration checked -c Release -arch x64 /p:ArchiveTests=true
```

(the `/p:ArchiveTests=true` is required to build the RunTests.cmd wrapper scripts)

```
C:\gh\runtime\artifacts\bin\System.Numerics.Vectors.Tests\net5.0-Release>call .\RunTests.cmd -r C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64
```

```
Assert failure(PID 42844 [0x0000a75c], Thread: 13268 [0x33d4]): Assertion failed 'varDsc->lvExactSize == 12' in 'System.Numerics.Tests.Matrix4x4Tests:Matrix4x4CreateFromAxisAngleTest():this' during 'Lowering nodeinfo' (IL size 357)

    File: C:\gh\runtime\src\coreclr\src\jit\compiler.h Line: 3498
    Image: C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\dotnet.exe
```

@tannergooding @CarolEidt @echesakovMSFT

**Comment by tannergooding** [comment]
This is failing because `optCSE` is introducing a `LCL_VAR` but due to there being no known class handle, `lvExactSize` is never set and is therefore 0: <https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/optcse.cpp#L2640-L2651>

**Comment by tannergooding** [comment]
@CarolEidt it looks like the relevant code was introduced back in https://github.com/dotnet/coreclr/pull/22255, but the recent changes for implementing `GT_SIMD` as `GT_HWINTRINSIC` have exposed it: <https://github.com/dotnet/runtime/pull/35421>.

It wasn't appearing for `GT_SIMD` because this particular case inserted the left/right shift in codegen (which was the one place I called out we were producing additional node in importation: <https://github.com/dotnet/runtime/pull/35421#issuecomment-621509676>).
