### ISSUE TITLE
Throw PlatformNotSupportedException when encountering VT_RECORD in Marshal.GetObjectForNativeVariant

### ISSUE THREAD

**Issue by hughbe** [dotnet/runtime#36603]
E.g. in https://github.com/dotnet/runtime/issues/27015 we discovered that trying to marshal VT_RECORD always throws `ArgumentException` where .NET Framework would succeed.

Since VT_RECORD is not supported in .NET Core, I suggest we can clean out a bunch of code that is essentially dead because we always end up throwing. Then we throw `PlatformNotSupportedException` if there is a failure.

Relevant to https://github.com/dotnet/winforms/pull/3197

/cc @AaronRobinsonMSFT @weltkante

**Comment by AaronRobinsonMSFT** [comment]
@hughbe There are cases when this would be okay. For example if someone supplied a `VARIANT` and provided an `IRecordInfo`, we will use it. Can you offer up a concrete example? The PR https://github.com/dotnet/winforms/pull/3197 has a lot in it.

**Comment by hughbe** [comment]
> There are cases when this would be okay. For example if someone supplied a VARIANT and provided an IRecordInfo, we will use it. 

Sorry, do you mean that it is ok to throw? or that we should actually implement support.

> Can you offer up a concrete example? The PR dotnet/winforms#3197 has a lot in it.

Sure. So basically I used `typeof(int)` rather than a custom struct for simplicity to prevent having to register a coclass value type on the local device during tests. But the same logic applies for structs.

An example failure is at https://github.com/dotnet/winforms/blob/07c63247b5221a8955946d9abb686b6a6f48208e/src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/VARIANTTests.cs#L5385-L5415

In .NET Framework we return `1` which makes sense. In .NET Core we throw `ArgumentException`

**Comment by AaronRobinsonMSFT** [comment]
> > There are cases when this would be okay. For example if someone supplied a VARIANT and provided an IRecordInfo, we will use it.
> 
> Sorry, do you mean that it is ok to throw? or that we should actually implement support.

I meant the exception type was valid in some cases (i.e. the `IRecordInfo` field is `null`).

>In .NET Framework we return 1 which makes sense. In .NET Core we throw ArgumentException

Yep. That is true and correct in this case. The GUID of the type passed in isn't known and we won't generate it either - this was the TLB generation support we removed from .NET Core. Potential work here is we could add support for querying the registry and that would support some of this system - that was mentioned in  https://github.com/dotnet/runtime/issues/27015#issuecomment-611079237.

I don't think changing the exception type is appropriate here since this is letting the user know that the type is invalid because the GUID doesn't have a mapping to an `IRecordInfo` instance - why that is and can support be added is another question.

**Comment by hughbe** [comment]
> I don't think changing the exception type is appropriate here since this is letting the user know that the type is invalid because the GUID doesn't have a mapping to an IRecordInfo instance - why that is and can support be added is another question.

Right, but are there any GUIDs that do work?
