### ISSUE TITLE
System.Text.Json:Serialize method with CamelCase conversion, does not work on complex property in dictionary.

### ISSUE THREAD

**Issue by PopeyeZhong** [dotnet/runtime#36679]
### Description

The `JsonSerializer.Serialize` method with `CamelCase` conversion, sometimes not working properly.
Below is my code:

```csharp
public class UserEntity
{
	public int UserId { get; set; }
	public string Name { get; set; }
}

public static void Main(string[] args)
{
	var data = new Dictionary<string, object>()
	{
		{ "CredentialId", "123" },
		{ "RenewalToken", "666" },
		{ "Expiration", "4:0:0" },
		{ "User", new UserEntity { UserId = 100, Name = "Popeye" } },
	};

	var text = JsonSerializer.Serialize(data, new JsonSerializerOptions()
	{
		WriteIndented = true,
		Encoder= JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
		DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
		PropertyNamingPolicy = JsonNamingPolicy.CamelCase
	});

	Console.WriteLine(text);
}
```
Its output is:

```json
{
  "credentialId": "123",
  "renewalToken": "666",
  "expiration": "4:0:0",
  "User": {
    "userId": 100,
    "name": "Popeye"
  }
}
```

The **"User"** property name above has not been converted. Is this a **BUG** or another reason?!

### Configuration

.NET Core 3.1.3
Visual Studio 2019 Enterprise  v16.5.5
Window 10 x64 _(version 1909/18363.836)_
CPU: Intel i7-8700K @3.7GHz
RAM: 16GB

**Comment by layomia** [comment]
Hi. This is a dup of #30889. The bug here is that the dictionary key policy is not applied when the value is not a primitive (i.e when it's JSON representation is an object or array.)

This issue is fixed for .NET 5 (master). However, porting the fix to 3.x will not meet the servicing bar.

Some workarounds here are to use a custom converter, upgrade the app to a [preview of .NET 5](https://dotnet.microsoft.com/download/dotnet/5.0), or use a [preview of the System.Text.Json v5.0.0 package](https://www.nuget.org/packages/System.Text.Json/5.0.0-preview.2.20160.6) on nuget.
