### ISSUE TITLE
LdapConnection.BeginSendRequest uses defunct Delegate.BeginInvoke

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#36690]
https://github.com/dotnet/runtime/blob/55d3260ad5dc48988228ac0cb1278541e87e513d/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L382

Delegate.BeginInvoke throws PlatformNotSupportedException on .NET Core.  So it appears LdapConnection.BeginSendRequest is broken (and we don't have tests for it).

cc: @joperezr

**Comment by joperezr** [comment]
This code will only happen when people use `LdapConnection.BeginSendRequest()` method and this is most likely code that was ported from .NET Framework. My guess here is that the reason why this hasn't come up yet in the past is because most people won't use this method, and instead call the sync version of the method `LdapConnection.SendRequest()`. That is what all of our tests do and it is also what all code samples I found online use when sending requests to the LDAP server.

All that said, we definitely want to increase code coverage on the library and if possible fix `BeginSendRequest` member which as @stephentoub pointed out, it throws PNSE now.

@stephentoub I'm not very familiar with Delegate class, is there a recommended alternative to Delegate.BeginInvoke that we suggest for our customers?

**Comment by jmaine** [comment]
I believe the correct fix would be to add a `LdapConnection.SendRequestAsync()` method.

**Comment by stephentoub** [comment]
> I'm not very familiar with Delegate class, is there a recommended alternative to Delegate.BeginInvoke that we suggest for our customers?

Task, e.g. Task.Run
