### ISSUE TITLE
Disabling EventPipe session doesn't unset runtime providers

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#36728]
Initially reported through https://twitter.com/KooKiz/status/1262370490880057344. 

When you start a dotnet-trace session (or any EventPipe session with rundown enabled), the runtime will start firing verbose events across the runtime. 

I've finished root-causing this issue and will follow-up with a PR to fix this issue soon.

**Comment by noahfalk** [comment]
> When you start a dotnet-trace session (or any EventPipe session with rundown enabled), the runtime will start firing verbose events across the runtime

To ensure I understand it I want to clarify a few things:
1. Based on the fix my assumption is that 'firing' in this context means the runtime executed some code that created the event arguments and called into EventPipe::WriteEvent(). It does not appear that any of these events are being emitted into in-memory buffers or into an on-disk file because EventPipe::WriteEventInternal() would still correctly filter out the events.
2. I don't see anything in the code that limits this bug to only occurring when rundown is enabled. If it does require rundown it would be helpful to explain how rundown alters the results.

> I've finished root-causing this issue

It can be useful to explain what you found when root causing : ) I think I was able to connect the dots but for anyone not already fairly familiar it would probably be tricky.

**Comment by noahfalk** [comment]
I believe bug #36913 would have very similar symptoms to this issue and potentially exacerbated the problem observed here.
