### ISSUE TITLE
[System.Text.Json] Utf8JsonReader should support multiple content

### ISSUE THREAD

**Issue by Int32Overflow** [dotnet/runtime#36750]
The following JSON file (with multi content) is not supported:

`{ "name": "Admin" }{ "name": "Publisher" }`

The following exception occurs:
`System.Text.Json.JsonReaderException: "'{' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | `

In the library Newtsoft Json.NET there was the following property "SupportMultipleContent". What is the solution here?

https://www.newtonsoft.com/json/help/html/ReadMultipleContentWithJsonReader.htm

**Comment by Clockwork-Muse** [comment]
Strictly speaking, a JSON file should either have a top-level object, or a top-level array.  Multiple objects is ill-formed.

There is the [JSON Lines](http://jsonlines.org/) format (this is the first I've heard of it), where _each line_ is valid JSON - if this is your situation, you would parse the file line-at-a-time, not tell the parser to operate over the entire file (this is because the entire file might be too large to fit into memory, or might be streaming - that is, not complete yet).

**Comment by layomia** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/33030.
