### ISSUE TITLE
Assembly Loading via ProjectReference and Assembly.LoadFile upon same file leads to two instances

### ISSUE THREAD

**Issue by mbrenn** [dotnet/runtime#36787]
### Description

Let's consider three assemblies: 

1. abc.exe has a ProjectReference to bla.dll and foo.dll
2. bla.dll contains a class X and a method that checks if an instance is of type 'X' (the checker)
3. foo.dll contains a loader via Load.Assembly to load bla.dll. It collects all 'checker'. It also checks whether the currently loaded Assemblies via 'Assembly.CurrentDomain' contains bla.dd

Now: 

1. abc.exe calls the loader in foo.dll which now has a supporting method to call the checker. bla.dll is not loaded yet since no type is queried ==> The pluginloader loads explicitly the bla.dll as bla.dll:1
2. abc.exe creates an instance of X called a (here, the referenced assembly will be used), so X is of type bla.dll:2
3. abc.exe calls foo.dll to call the checker which verifies that the instance a is of type X. 

The result will be _FALSE_ because foo.dll will check that bla.dll.X:2 is of type bla.dll.X:1 which is not the case. 

In .Net Framework the result is true. 

Also described here:
https://stackoverflow.com/questions/61922511/gettype-equalstypeoftype-return-false-in-net-core-but-not-in-net-framework/61923888#61923888

### Configuration

.Net Core 3.0 was NOK
.Net Core 3.1 was NOK
.Net Framework 4.6.1 is OK

### Regression?

.Net Framework was OK

### Other information

The workaround is to first use the type in abc.exe to trigger loading via ProjectReference, so loading via PluginLoader is avoided.

**Comment by vitek-karas** [comment]
The assembly loading is rather different between .NET Framework and .NET Core. For one .NET Core has no appdomains (there's only ever the one default appdomain, there's no way to create another one). Instead .NET Core has [`AssemblyLoadContext`](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext).

`Assembly.LoadFile` behaves differently between .NET Framework and .NET Core. In both cases it allows loading of an assembly from a file and potentially loading multiple versions of the same assembly. In .NET Core this is done by creating a new AssemblyLoadContext (ALC) for each assembly loaded via `Assembly.LoadFile`. (Since only one copy of a given simple assembly name is allowed per ALC).

It's hard for me to guess how you load the bla.dll exactly and from where - one load is from the main application which is implicit via assembly reference - that one will be loaded into the default ALC. The second load happens through your plugin system which seems to use `Assembly.LoadFile`, but only sometimes. If it does use `Assembly.LoadFile` on bla.dll it would end up with a second copy (even if the file path is exactly the same). This leads to the type difference you see.

I assume you don't want any isolation between the plugins (isolation in this case means ability for each plugin to have different versions of dependencies, so for example one plugin can use Dependency.dll version 1, and another plugin can use Dependency.dll version 2 - in .NET Core this requires usage of separate ALCs). So if no isolation is required a better way to load the assembly into the default load context is `AssemblyLoadContext.Default.LoadFromAssemblyPath` - especially if you manually load all dependencies (as seems to be the case in your plugin loader). Alternatively you could use `Assembly.LoadFrom` which adds some amount of auto-resolution (it looks for dependent assemblies in the same folder). Both of these will load the assemblies to the default ALC and thus there's no way to load more than one copy.

If you need fully isolated plugin system, then custom ALCs is the way to go. There's a guide and a sample here: https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support.

**Comment by mbrenn** [comment]
Thanks a lot for lengthy answer and good explanation, it perfectly fits to my scenario and gave me sufficient background. And I don't need isolation (up to now) , so I will try the AssemblyLoadContext.Default.LoadFromAssemblyPath and dig deeper into the documentation.

So, no Bug... Intended by Design 👌
