### ISSUE TITLE
Make string.FastAllocateString public

### ISSUE THREAD

**Issue by vanbukin** [dotnet/runtime#36989]
## Background and Motivation
Provide ability for developers to write libraries that able to format something to string using pre-allocated pinned char* pointer withoput any overhead for delegate call.
It's also possible now to "export" that function using .ilproj [like this](https://github.com/dodopizza/primitives/blob/c9769a2eac492034c0ff0f1de567717d7593316c/src/Dodo.Primitives.IL/netcoreapp31.System.Private.CoreLib.il#L21), but it works only with undocumented [IgnoresAccessChecksToAttribute](https://github.com/dodopizza/primitives/blob/c9769a2eac492034c0ff0f1de567717d7593316c/src/Dodo.Primitives.IL/netcoreapp31.System.Runtime.CompilerServices.il#L1-L59)
## Proposed API
```diff
namespace System
{
-    internal static extern string FastAllocateString(int length);
+    public static extern string FastAllocateString(int length);
}
```

## Usage Examples
Preallocate known-size string, get pinned char* pointer and overwrite string contents [like here](https://github.com/dodopizza/primitives/blob/c9769a2eac492034c0ff0f1de567717d7593316c/src/Dodo.Primitives/Uuid.cs#L501-L507) or [here](https://github.com/dodopizza/primitives/blob/c9769a2eac492034c0ff0f1de567717d7593316c/src/Dodo.Primitives/Hex.cs#L107)
``` C#
public string ToString(string? format, IFormatProvider? formatProvider)
{
   // ...
   public string ToString(string? format, IFormatProvider? formatProvider)
   {
       // ...
        var uuidString = string.FastAllocateString(32);
        fixed (char* uuidChars = &uuidString.GetPinnableReference())
        {
            FormatN(uuidChars);
        }
        return uuidString;
       // ...
   }
   // ...
}
```

## Alternative Designs
Provide separate external library (do not ship it with System.Private.CoreLib), that expose that method with `public` modifier or add string.Create overload without delegate that can only allocate and return string.

## Risks
That API should be supported in a future versions of .NET

**Comment by stephentoub** [comment]
Making this pubic would encourage mutating an immutable type. It's internal for a good reason. I would not want to make this public. string.Create was exposed an alternative.

**Comment by vanbukin** [comment]
@stephentoub Maybe provide that ability via string.Create without delegate?

**Comment by svick** [comment]
@vanbukin How would that work?

**Comment by tannergooding** [comment]
There could be an unsafe version which takes a function pointer, which would allow the delegate like scenario without forcing a delegate allocation

**Comment by GrabYourPitchforks** [comment]
@vanbukin
Per Steve's comment, we're not going to expose an API which encourages mutating `string` instances. In fact, in .NET Core 3.0 we [started obsoleting APIs](https://github.com/dotnet/runtime/issues/27515) which encouraged this practice.

Adding overloads to the `string.Create` factory method may work. What do you have in mind?

**Comment by vanbukin** [comment]
@svick It could be like this: 
Icall string.Create(32), pin it using fixed statement, get char* pointer and then change string content using that pointer inside fixed statement. Like System.Guid.ToString. 

Here and now it’s only possible inside System.Private.CoreLib, because FastAllocateString is internal. Prefer way to do that now is to call string.Create, provide delegate, fake “state” and get span pointer inside delegate. But I don’t want to get overhead on delegate creation and call, that’s why I ask to make FastAllocateString public.

**Comment by vanbukin** [comment]
@tannergooding sounds like a good idea

**Comment by stephentoub** [comment]
> There could be an unsafe version which takes a function pointer, which would allow the delegate like scenario without forcing a delegate allocation

I seem to remember @jkotas having an opinion about that, but I don't remember what it was.

> But I don’t want to get overhead on delegate creation and call

Can you share more details about in what situation this matters? A delegate can be cached (and often is by the C# compiler), so the concern is about the cost of delegate invocation? A string is being allocated and populated; the delegate invocation shows up as being negatively impactful?

**Comment by svick** [comment]
@tannergooding 

> There could be an unsafe version which takes a function pointer, which would allow the delegate like scenario without forcing a delegate allocation

Since `string.Create` has a `state` parameter, it should be just one delegate allocation per callsite for the whole application runtime. Is that worth optimizing?

@vanbukin

> I call string.Create(32), pin it using fixed statement, get char* pointer and then change string content using that pointer inside fixed statement.

 Oh, I assumed you meant something else, not just renaming `string.FastAllocateString` to `string.Create`.

> Prefer way to do that now is to call string.Create, provide delegate, fake “state” and get span pointer inside delegate. But I don’t want to get overhead on delegate creation and call, that’s why I ask to make FastAllocateString public.

The delegate allocation overhead is tiny, since it's just one allocation for the application runtime, if you use `string.Create` correctly. And [the overhead of delegate call in the case of `Guid` formatting seems to be ~10 %.](https://gist.github.com/svick/d2bd0cffb6f14fb1a2f1e1978d8ff883#file-results-md)

**Comment by vanbukin** [comment]
>Since string.Create has a state parameter, it should be just one delegate allocation per callsite for the whole application runtime. Is that worth optimizing?
I think yes.
>Oh, I assumed you meant something else, not just renaming string.FastAllocateString to string.Create.
Not renaming. Make FastAllocateString public or provide additional  string.Create overload that does not take any state or delegrate. Only string size. To avoid any allocations.
>The delegate allocation overhead is tiny
Yes, but this might be helpful in performance-sensitive places. Like custom structures string formatting or database providers strings materialization.

**Comment by vanbukin** [comment]
@svick [Here is my results](https://gist.github.com/vanbukin/e32490596d7cd853e5e7522eabb6bba5). Looks like 30%.

**Comment by vanbukin** [comment]
@svick I've updated results. Add benchmarks for .NET 5.0 preview 4. Same difference.

**Comment by GrabYourPitchforks** [comment]
Per earlier comments, string instances are contractually immutable. The team is largely against adding APIs which encourage developers to mutate these instances. Such code is not guaranteed to work correctly across all versions of the runtime. I don't think benchmarks are going to do much to sway the majority position here.

There might be opportunity here to improve the performance of the existing `string.Create` method. Or, per Tanner's earlier suggestion, offer unsafe overloads which use function pointers + calli rather than delegate dispatch. Or any overloads which might be useful for your scenario.

But to repeat, any API which promotes the idea of returning a _string_ instance to the caller and saying "sure, go ahead and pin it and mutate its contents" is anathema to our team.

**Comment by vanbukin** [comment]
@GrabYourPitchforks Ok. Tanner's suggestion looks good. Let's continue our discussion in a way to add string.Create overload that takes a pointer instead of opening FastAllocateString. Can we continue our discussion here or I need to create a new issue?

**Comment by GrabYourPitchforks** [comment]
Feel free to explore that idea here.

**Comment by jkotas** [comment]
> > There could be an unsafe version which takes a function pointer, which would allow the delegate like scenario without forcing a delegate allocation

> I seem to remember @jkotas having an opinion about that, but I don't remember what it was.

The difference between delegate call and function pointer calli call is a few instruction. It is unlikely to make significant difference to add an overload that takes function pointer.

I believe that most of the overhead of passing in delegate comes from extra call(s): setting up the frame, passing the arguments around, saving callee saved registers, ... . This overhead needs to be eliminated to get on par with calling FastAllocateString directly. Teaching the JIT to inline the delegates would be the most natural way to do it. I know @AndyAyersMS looked into it, but it is not easy.

**Comment by SingleAccretion** [comment]
> add string.Create overload that takes a pointer instead of opening FastAllocateString

I investigated the possibility of adding a new API that would utilize the old "generic struct" trick. The conclusion is that there is room for improvement, but not a whole lot.

### Setup
The goal was to see if the following API could achieve performance of the fully "unsafe" method that uses `FastAllocateString` directly:
````C#
static string GenericStringCreate<T>(int length, T initializer) where T : IStringInitialzer

interface IStringInitializer
{
    void Initialize(Span<char> span);
}
````
The testing consisted of measuring the time it would take to pass parameters to a dummy function with this signature:
````C#
[MethodImpl(MethodImplOptions.NoInlining)]
static unsafe void Payload(char* dest, Uuid* uuidPtr) { }

unsafe struct Uuid { fixed byte Bytes[16]; }
````
Tested "means of delivery" (optimized for optimal performance):
````C#
public const int Length = 1; //To exacerbate the differences

[MethodImpl(MethodImplOptions.AggressiveInlining)]
static unsafe string StringifyWithUnsafe(Uuid uuid)
{
    var result = CoreLib.FastAllocateString(Length);
    fixed (char* ptr = &result.GetPinnableReference())
    {
        Payload(ptr, &uuid);
    }

    return result;
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
static unsafe string StringifyWithGenericStringCreate(Uuid uuid)
{
    return StringHelpers.GenericStringCreate(Length, new UuuidStringInitialzer(&uuid));
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
static unsafe string StringifyWithStringCreate(Uuid uuid)
{
    var uuidString = string.Create(Length, uuid, (s, u) =>
    {
        fixed (char* ptr = &MemoryMarshal.GetReference(s))
        {
            Payload(ptr, &u);
        }
    });

    return uuidString;
}

readonly unsafe struct UuuidStringInitialzer : IStringInitialzer
{
    private readonly Uuid* _uuidPtr;

    public UuuidStringInitialzer(Uuid* uuidPtr) => _uuidPtr = uuidPtr;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Initialize(Span<char> span)
    {
        fixed (char* ptr = &MemoryMarshal.GetReference(span))
        {
            Payload(ptr, _uuidPtr);
        }
    }
}
````
Where `StringHelpers.GenericStringCreate` is the implementation mirroring current `string.Create`'s one, but with an initializer structure instead of a delegate.
````C#
static unsafe string GenericStringCreate<T>(int length, T initializer) where T : IStringInitialzer
{
    if (length <= 0)
    {
        if (length == 0)
        {
            return string.Empty;
        }

        throw new ArgumentOutOfRangeException(nameof(length));
    }
    
    string result = CoreLib.FastAllocateString(length);
    initializer.Initialize(MemoryMarshal.CreateSpan(ref CoreLib.GetRawStringData(result), length));

    return result;
}
````
### The benchmarks
````C#
public class Tests
{
    public static readonly Uuid DefaultUuid = default;

    [Benchmark(Baseline = true)]
    [MethodImpl(MethodImplOptions.NoInlining)]
    public unsafe string UnsafeOverhead()
    {
        return UuidManipulation.StringifyWithUnsafe(DefaultUuid);
    }

    [Benchmark]
    [MethodImpl(MethodImplOptions.NoInlining)]
    public unsafe string StringGenericCreateOverhead()
    {
        return UuidManipulation.StringifyWithGenericStringCreate(DefaultUuid);
    }

    [Benchmark]
    [MethodImpl(MethodImplOptions.NoInlining)]
    public unsafe string StringCreateOverhead()
    {
        return UuidManipulation.StringifyWithStringCreate(DefaultUuid);
    }
}
````

### Typical results
|                      Method |      Mean |     Error |    StdDev | Ratio | RatioSD |
|---------------------------- |----------:|----------:|----------:|------:|--------:|
|              UnsafeOverhead |  7.635 ns | 0.1612 ns | 0.1429 ns |  1.00 |    0.00 |
| StringGenericCreateOverhead | 10.183 ns | 0.2914 ns | 0.4086 ns |  1.30 |    0.04 |
|        StringCreateOverhead | 15.050 ns | 0.3796 ns | 0.3728 ns |  1.98 |    0.05 |

I rerun them multiple times with random statics added to see if layout could influence the timings, but the results do seem to be consistent (or at least not deviating by more than 1 ns with each run). On average, the unsafe version was ahead by ~2 ns, and vanilla `string.Create` was behind by ~4.5 ns. While this is a somewhat significant improvement, I personally do not think it warrants adding a new API, especially since it still cannot achieve the performance of "the best" code. It is very much possible I missed something but after ~8 hours of trying different things this is the outcome.

**Comment by TYoung86** [comment]
Try `new string('\0', n)` instead of `CoreLib.FastAllocateString(Length)`?

**Comment by SingleAccretion** [comment]
> Try new `string('\0', n)` instead of `CoreLib.FastAllocateString(Length)`?

Using the constructor seems to be slower:
````C#
[Benchmark(Baseline = true)]
public string CreateWithFastAllocate() => CoreLib.FastAllocateString(32);

[Benchmark]
public string CreateWithNullCharacters() => new string('\0', 32);
````
|                   Method |      Mean |     Error |    StdDev | Ratio | RatioSD |
|------------------------- |----------:|----------:|----------:|------:|--------:|
|   CreateWithFastAllocate |  6.838 ns | 0.2152 ns | 0.2013 ns |  1.00 |    0.00 |
| CreateWithNullCharacters | 11.600 ns | 0.3240 ns | 0.3857 ns |  1.70 |    0.06 |

> Also, will the gc move allocated strings if they're not pinned?

I believe no, since `ref`s are "managed" pointers, so the GC is aware of their existence. However, in your example, you are modifying the reference variable, thus changing its identity, and I do not know if that makes it not "tracked" anymore. It would be reasonable to expect that that answer is "yes, it is not safe to do this", but I am not knowledgeable enough to definitively say so.

The reason that I went with the pointer-based `Payload` and not `ref`s is that there is no way to do `ref` fields, thus I will always have to copy the `Uuid` parameter at least once. That said, this decision might be worth revisiting.

**Comment by GrabYourPitchforks** [comment]
I'm closing this issue because the API questions have been answered and because the discussion has veered into encouraging dangerous coding practices. But once more, just to make this painfully clear:

__It is never safe or supported to mutate the contents of a returned `string` instance.__

Doesn't matter whether the API is `new string('\0', ...)` or `string.FastAllocateString`. As soon as the caller gets an object of type `string`, the contents of that object __must__ remain immutable. I see no world in which the .NET team will ever change its stance on this matter.

If you mutate a string instance within your own library or application, you are entering unsupported territory. A future framework update could break you. Or - more likely - you'll encounter memory corruption that will be very painful for you _or your customers_ to diagnose.
