### ISSUE TITLE
Microsoft.VisualBasic tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37066]
### Microsoft.VisualBasic.Core.Tests:
[List of test failures](https://github.com/dotnet/runtime/files/4691086/fails.txt)
[XML of test failures](https://github.com/dotnet/runtime/files/4691087/test_failures.txt)

**Comment by ehasis** [comment]
I have a doubt in how to deal with this. Most of the tests are failing because of empty test data for `[Theory]` tests. Except in couple cases, all others seems "impossible" to test the conditions. For example, take this test:
```c#
[Theory]
[MemberData(nameof(Val_Char_ArgumentException_TestData))]
public void Val_ArgumentException_Char(char value)
{
	Assert.Throws<ArgumentException>(() => Conversion.Val(value));
}

public static IEnumerable<object[]> Val_Char_ArgumentException_TestData()
{
    yield break; // Add more...
}
```
And now Val function:
```vb.net
Public Function Val(ByVal Expression As Char) As Integer
    'Val only handles Ascii decimal chars '0' to '9'
    Dim CharValue As Integer
    CharValue = AscW(Expression) 'CType(Expression, IConvertible).ToInt32(Nothing)
    If CharValue >= AscW("1"c) AndAlso CharValue <= AscW("9"c) Then
        Return CharValue - AscW("0")
    End If
    Return 0
End Function
```
There is no way to test ArgumentException (at least I could not find a way), so, should I delete this kind test or just disable for Android (Mono)?

**Comment by cston** [comment]
@ehasis, thanks for investigating.

I agree, it looks like several of the empty test data and associated tests can be removed because the conditions being tested cannot be hit: `Val_Char_ArgumentException_TestData`, `Val_Char_OverflowException_TestData`.

Are there values for the other empty test data that would satisfy the conditions being tested? For instance:
```
        public static IEnumerable<object[]> Val_Object_OverflowException_TestData()
        {
            yield return "123456e789";
        }
```

**Comment by ehasis** [comment]
> Are there values for the other empty test data that would satisfy the conditions being tested?
Yes, there are and I'm working on it.

**Comment by ehasis** [comment]
Ok, I've managed to almost resolve this issue, except the test bellow. Is failing on `Assert.False(string.IsNullOrEmpty(actual))`. Any suggestion?
```c#
[Fact]
public void Command()
{
    var expected = Environment.CommandLine;
    var actual = Interaction.Command();
    Assert.False(string.IsNullOrEmpty(actual));
    Assert.EndsWith(actual, expected);
}
```

**Comment by cston** [comment]
> Is failing on `Assert.False(string.IsNullOrEmpty(actual))`.

Perhaps `Environment.CommandLine` is returning `null` or `""`. We could log a specific bug and follow up on this test failure separately if that is blocking.
