### ISSUE TITLE
Microsoft.Extensions.DI.Specification.Tests need to be shipped

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#37108]
DI.External tests use DI.Specification.Tests https://github.com/dotnet/runtime/pull/37103

Outside of the runtime repo, DI.Specification.Tests could be useful and they used to be shipped from extensions repo prior to https://github.com/dotnet/extensions/pull/3160

This issue keeps track of this work item.

**Comment by maryamariyan** [comment]
@JunTaoLuo Do we also need to be shipping Logging.Tests? or DI.Specification.Tests is the only one needed to ship?

**Comment by maryamariyan** [comment]
cc: @safern

**Comment by JunTaoLuo** [comment]
Di.Specification.Tests need to be shipped. Logging.Tests do not.

**Comment by maryamariyan** [comment]
nuget package link
https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Specification.Tests
as expressed in this issue we need to be shipping Microsoft.Extensions.DependencyInjection.Specification.Tests

csproj in dotnet/extensions
https://github.com/dotnet/extensions/blob/v3.1.8/src/DependencyInjection/DI.Specification.Tests/src/Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj

I think dotnet/runtime doesn't have any test project currently that ships as a package as well. So not sure if there is a straightforward way to package this. 

@safern how do you think we can accomplish this task for Microsoft.Extensions.DependencyInjection.Specification.Tests?

**Comment by safern** [comment]
Hmm I think we would need to add a pkgproj for that and then mark it as `IsShipping=false`

cc: @ericstj

**Comment by ericstj** [comment]
Yeah, that's the best way to do it.

**Comment by safern** [comment]
`Shipping` would mean that it would be stable and that it would go into nuget, do we want that, or is it enough with a non-stable package, that ships to our public dnceng feeds?

**Comment by ericstj** [comment]
It looks to me like these tests previously shipped public stable and are consumed by other public repositories. 

This raises another concern that our tests depend on assemblies that don’t ship.

**Comment by ericstj** [comment]
Here's a commit that does this: https://github.com/ericstj/runtime/commit/21cdff85d8e9ef599525df5207d00ead7248b739

It depends on @Anipik's change https://github.com/dotnet/runtime/pull/48385

Some things to decide:
- I just suppressed the package dependency on [Microsoft.DotNet.XUnitExtensions](https://github.com/ericstj/runtime/commit/21cdff85d8e9ef599525df5207d00ead7248b739#diff-eca9f7212ff23b6ded37c0d8f25fc9c07227848945559b82ace20cd8152f1e78R19).  It might be better to `#ifdef` the usage or add `ConditionalAttribute` to all the test API in Arcade to strip it so that we don't ship the dangling dependency.
- Rather than source-share, we could consume this in our own tests.

**Comment by ericstj** [comment]
self-assigning since I'm driving a PR for this.
