### ISSUE TITLE
Test failure: System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(cancellationCause: 0)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#37140]
failed in job: [runtime 20200528.55 ](https://dev.azure.com/dnceng/public/_build/results?buildId=663094&view=ms.vss-test-web.build-test-results-tab&runId=20558868&resultId=131681&paneView=debug)

Error message
~~~
Assert.True() Failure
Expected: True
Actual: False


Stack trace
   at System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(Int32 cancellationCause) in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 494
--- End of stack trace from previous location ---
~~~

**Comment by BruceForstall** [comment]
`net5.0-Windows_NT-Release-x64-Mono_release-Windows.10.Amd64.ServerRS5.Open`

**Comment by BruceForstall** [comment]
@danmosemsft I don't see an "area-System.Media" label; what would be appropriate here?

**Comment by danmosemsft** [comment]
uh, good question -- @ericstj which label for System.Windows.Extensions ?

**Comment by ericstj** [comment]
Let's use Microsoft.Win32  I don't think it's big enough to warrant a separate label.

**Comment by v-haren** [comment]
failed again in job: [runtime 20200903.94 ](https://dev.azure.com/dnceng/public/_build/results?buildId=801115&view=ms.vss-test-web.build-test-results-tab&runId=25362096&resultId=139267&paneView=debug)

failed test: System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(cancellationCause: 0)

net5.0-Windows_NT-Release-x64-Mono_release-Windows.10.Amd64.Server19H1.Open


Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(Int32 cancellationCause) in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 493
--- End of stack trace from previous location ---
~~~

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20210909.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1351569&view=ms.vss-test-web.build-test-results-tab&runId=39547926&resultId=171063&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(cancellationCause: 1)

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(Int32 cancellationCause) in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 0
--- End of stack trace from previous location ---
```

**Comment by danmoseley** [comment]
The bug is a race in SoundPlayer.cs

LoadStream here ends up awaiting the test stream
https://github.com/dotnet/runtime/blob/1dc8dfa0058396495203e18ddc7f8a632d72c165/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L284-L290
assigning the task to `_copyTask`
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L323

Immediately after that, it waits on `_semaphore`, which in this test times out immediately (1ms). On the timeout, it calls `CancelLoad()` which signals the CancelationTokenSource.
https://github.com/dotnet/runtime/blob/1dc8dfa0058396495203e18ddc7f8a632d72c165/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L235-L237
it then calls CleanupStreamData() which sets `_lastLoadException` to null:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L172-L177

meanwhile the copy task is awaiting the test stream
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L496
which is canceled and the exception is caught here and turned into an AsyncCompletedEventArgs which is then posted back to the original thread:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L514-L528

The bug is that it's copying the field `_lastLoadException` into the ACEA but that gets cleared in a race with CleanupStreamData().

It should probably use the local.
