### ISSUE TITLE
AssemblyDependencyResolver  filename should not be  case sensitive

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#37162]
### Description

```C#
// filename: 'Module1.dll'

var filename = AppContext.BaseDirectory + "module1.dll"
var resolver = new AssemblyDependencyResolver(filename) // throw  An item with the same key has already been added : module1
```

### Configuration

```
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.300
 Commit:    b2475c1295

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Regression?

unknow

**Comment by vitek-karas** [comment]
Can you please include the callstack of the exception you get?
The dictionary in `AssemblyDependencyResolver` is case insensitive already: https://github.com/dotnet/coreclr/blob/b1745659051f73cf089fbfb2ebbe4648c2fb6c12/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.cs#L99

So if it's that one, there has to be something else at play.

Also can you try this:
on command line run:
```console
set COREHOST_TRACE=1
set COREHOST_TRACEFILE=host_trace.txt
<run the app and repro the failure>
```
This should produce `host_trace.txt` in the current directory. The interesting part will be after text `corehost_resolve_component_dependencies results`. There should be a list of assemblies there. I guess if that contains the same assembly twice it might fail like this. If that's the case I would be interested in how you made that happen.

**Comment by John0King** [comment]
I believe it worked like this:
1. actual file name :  Module1.dll  
2. passing to `AssemblyDependencyResolver` is "module1.dll" 
3. add module1  as the key  
4. foreach the  Module1.deps.json   and find the "Module1"  as another key  (  the code using `.Add()` instead of `dic[key]` )

**Comment by John0King** [comment]
[host_trace.txt](https://github.com/dotnet/runtime/files/4704939/host_trace.txt)

this is the host_trace

**Comment by John0King** [comment]
@vitek-karas   this is my repo https://github.com/John0King/LazyMan.ModularLoader/

and you can try set the 
https://github.com/John0King/LazyMan.ModularLoader/blob/77f5d6a7e2a2b8bdc1c6e10be85f878ca1c6f7ca/test/LoaderRunner/Program.cs#L25-L33   from 'Module1.dll' to  `module1.dll`  to see the error

**Comment by vitek-karas** [comment]
Thanks for the repro. I was able to repro it locally as well.
The problem is in `hostpollicy.dll` where we use `name_to_resolved_asset_map_t` as the "dictionary" to store "simple name" -> "path" of assets resolved from `.deps.json`. This dictionary is case sensitive, so in the above case we end up with two entries in the dictionary:
* The first one is the path specified to `AssemblyDependencyResolver` (and the file name as the simple name), since we always add the app/component main assembly first.
* The second one is the name and path of that assembly found in the `.deps.json`, which has different casing in this example.

Later on this breaks `AssemblyDependencyResolver` since it doesn't expect to get two entries for the same assembly from `hostpolicy`.

I verified that this problem exists even when running an app. If I build an app with name `Module.dll` and then rename the file on disk to `module.dll` and run it via `dotnet module.dll` the TPA will contain two entries for `Module.dll` and `module.dll`. Runtime won't complain and will simply take one of them.

There are two possible ways to fix this:
* Make `AssemblyDependencyResolver` resilient to this - we could also compare the paths reported and if they're the same, simply ignore the duplicate entries. And only fail if the paths are different (since `hostpolicy` normalizes paths, the comparison should be sufficient to perform as simple string case sensitive/insensitive comparison).
* Fix `hostpolicy` to treat asset names as case insensitive. This is a bit tricky as managed assemblies should be case insensitive always (runtime treats assemblies this way and thus `hostpolicy` should probably do the same) but native assets should be case sensitive on non-Windows systems (and case insensitive on Windows). This could be a edge-case breaking change (if some app has two assets with same names but different casing with different file paths, currently `hostpolicy` won't fail and report them both - runtime would pick the first one I think, after the change `hostpolicy` may fail on finding two different paths for the same asset, so app which used to work, doesn't work anymore).

@elinor-fung, @AaronRobinsonMSFT, @swaroop-sridhar  - any opinion on the fix?

**Comment by John0King** [comment]
@vitek-karas  not sure it will help ,    when use dictionary  I always use `dic[key] = value`  and avoid use of `dic.add(key,value)` , because this will avoid most of the `An item with the same key has already been added` exception for both cases sensitive/insensitive dictionaries, it means `AddOrReplace(key,value)`.

for this issue , what about use `FileInfo.Name`, as my test we need to use  
```C#
var f = new FileInfo(path);
var folder = new DirectoryInfo(f.DirectoryName);
var name = folder.GetFiles(f.Name).First().Name
```

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas I would prefer option (1) and make `AssemblyDependencyResolver` handle the case where we actually use the data. Handling case insensitivity in a native context is non-trivial and I am unsure we will get it right the first 2 or 3 times - such a pain. Can we come up with a compelling scenario where the `hostpolicy` logic is deficient if we don't fix this on the native side?

**Comment by vitek-karas** [comment]
> Can we come up with a compelling scenario where the hostpolicy logic is deficient if we don't fix this on the native side?

I was trying to, but can't really. I would like for ADR to fail if it finds the duplicate assets to have different paths - mainly because if left as is it is likely to break apps (and makes for a fun debugging session to figure out why). And it won't be breaking as we already fail in the case.

Running app will ignore such case and use the first value, but it's been like that for a long time - and we haven't heard about it being a problem yet. Another reason why it's not a problem if we don't fix it on the native side.

I'm fine deciding we only fix this on the managed side: Allow duplicate entries as long as the path is the same. "The same" meaning:
* On Windows - `OrdinalIgnoreCase` comparison
* Elsewhere - `Ordinal` comparison

This relies on `hostpolicy` normalizing paths, which it already does and if there's a corner case where the normalization still ends up with two different paths for the same file, it would keep failing like it does today.
