### ISSUE TITLE
Function pointers and GC

### ISSUE THREAD

**Issue by omariom** [dotnet/runtime#37262]
C# is getting [functions pointers](https://github.com/dotnet/csharplang/issues/191).
I checked what [code is generated](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRjgOwMYwJYD2mqADgXpjBAsgDQwhTIC2APgAIBMAjALABQ7AAwACdtwB0AJSz5mECQGECzEngA21AMrUAbnmwoA3AOFjJMynnkSAkpWoESOhPsPIT/AVmRRIYzhFFEQEAbwERSLEAFhEAWQAKAEoQ/iiRcLT0qPsYAAUYBBEAa2pMCHUAZk4ACShMABNNEQBeEQA5WDxdCAAZPGAEKAQATwlegigGhIAiUoRyqs4ZpM9snMoCoowcVo6unv7B4bGAcQgYAFEADzIEGAT5xeq6xs1aERnzmEVEJE2EAR3MgCAh2nBmMBqCs1utUnCglB1JoEAkEg0KhAAOawCAAKgAPHAKDAAHxJHbYVYRKIAXxpkQZIgA2nELgALAgNWyqdQJNkwTnc3kAeRI+CIyAk7QI9nUFAoWKSAF0mSQEN1cTFEcjqOjMTiqITiZRSSJKVskkzMgiwKCRAkSSI8HshEZnSICSJuAB9IT+gPu50AamDVqy6xtCKiFsKyVh63pEZESfSao1ui17FiiiRmjy9l0BFKyWtTPSdqKjsoHrabo9Xt9AcDkTwofDCKj0ZE31+CH++UBwNB4MheupyfSqbpTKZzIAIsieXcHnMyhVqjMPjoYL0mFd+/a2mAkcgIEkPuIJDpsIg8DAxlo4CR1ShkABVTDMepQLEQBrKBiN53g+qrJuqmpUOYABsIgQNcVALCIJowD2Fx9gOeRDm+I4QlCqITrSQA)  for them.

For PInvoke calls JIT adds  a check for parking the threads executing managed code.
For callis it doesn't do anything special.

What are possible implications? Can calling an external method via calli  in a loop, for example, delay GC?

**Comment by tannergooding** [comment]
The codegen difference is because you declared a function pointer to a managed method. The function pointer needs to include the calling convention in order to be `unmanaged`: https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRjgOwMYwJYD2mqADgXpjBAsgDQwhTIC2APgAIBMAjALABQ7AAwACdtwB0AJSz5mECQGECzEngA21AMrUAbnmwoA3AOFjJMynnkSAkpWoESOhPsPIT/AVmRRIYzhFFEQEAbwERSLEAFhEAWQAKAEoQ/iiRcLT0qPsYAAUYBBEAa2pMCHUAZk4ACShMABNNEQBeEQA5WDxdCAAZPGAEKAQATwlegigGhIAiUoRyqs4ZpM9snMoCoowcVo6unv7B4bGAcQgYAFEADzIEGAT5xeq6xs1aERnzmEVEJE2EAR3MgCAh2nBmMBqCs1utUnCglB1JoEAkEg0KhAAOawCAAKhE2Ax2HUAB44BQYAA+JI7bCrCJRAC+jMirJEAG04hcABYEBq2VTqBLcmB8gVCgDyJHwRGQEnaBHs6goFCxSQAuuySAhuriRBTKIjkdR0ZicVQCUSICTyZSqSI6VskuzMgj2AB2R1YbBbZKwyIsrJs4Oc0XiwUkYXh/mR9TS2WYeWK5WqzDqrWhnV6qgGynGlGcM2aC34u2UB1Owou0NuuGe704P0M0NB9La3W6fWGmAFiB5ey6AilZKu9npBvfX4If75QHA0HgyGmlvpNtRdkcgAiyMjoIeczKFWqMw+OhgvSYVxnoL2YCRyAgSQ+4gkOmwiDwMDGWjgJB1KDIAAqpgzD1FAWIQA0ygYu+n7fpm6TZl2ubiAAbCIEDXFQCx5kaU5/BAAJAoBi4QlCqItkyQA=

Also noting, that the `unmanaged` convention listed in https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md is not currently supported.
Additionally, the eventual syntax for specifying the calling convention might change slightly: <https://github.com/dotnet/csharplang/pull/3441>

CC. @jkotas, @AaronRobinsonMSFT

**Comment by omariom** [comment]
Aaah.. thaat's why 😮
