### ISSUE TITLE
DebuggerTypeProxy types are empty after linking

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#37307]
After linking an application, any type that is used by a `DebuggerTypeProxyAttribute` still exists, but is empty. This is because there are no callers of any of the members on these types - they exist so the debugger can call them to show in the Watch window. So the linker is removing all of the members from the type. But the type remains because it is being referenced by the `DebuggerTypeProxyAttribute`. This will limit the ability to debug a linked application, because any type that uses a DebuggerTypeProxy will be empty in the Watch window.

We should fix this by annotating the DebuggerTypeProxyAttribute class to tell the linker to preserve its members that are required by the debugger. My initial thinking is that includes `PublicConstructors` and `PublicProperties`, as I don't think the debugger will call any methods on the proxy type.

cc @vitek-karas @joperezr @layomia

**Comment by stephentoub** [comment]
> My initial thinking is that includes PublicConstructors and PublicProperties, as I don't think the debugger will call any methods on the proxy type.

That sounds reasonable; while technically the debugger can show things beyond public properties, every type proxy I've looked at has only public constructors and properties (beyond the private fields that serve those properties).  That said, the same argument could be used to say "just keep everything", because there's unlikely to be anything more in the debugger type proxy than public ctors and properties, and if there is, it's likely there for a good debugging reason.

**Comment by MichalStrehovsky** [comment]
> After linking an application, any type that is used by a DebuggerTypeProxyAttribute still exists, but is empty

That's odd because linker has [bunch of code](https://github.com/mono/linker/blob/95d8c21c8d9bfc8cad107ff36fa44851f61bb28c/src/linker/Linker.Steps/MarkStep.cs#L1569-L1593) that is attempting to do stuff with that attribute.

I'll be happy to replace this with the public dataflow annotations and delete the linker special casing with prejudice.

Unless we get a statement from VS debugging folks on what they can actually use, I would go with `.All`.

**Comment by eerhardt** [comment]
> That's odd because linker has bunch of code that is attempting to do stuff with that attribute.

It looks like in order to get that code activated, you need to pass `-v` to the linker command line, which I wasn't.

We should probably come up with a coherent strategy for trimming "debug only" code out.

See
* https://github.com/mono/linker/issues/1231#issuecomment-637642323
* https://github.com/mono/linker/issues/1093
* https://github.com/dotnet/runtime/pull/37288
