### ISSUE TITLE
Could not load assembly on published project after net core upgrade

### ISSUE THREAD

**Issue by xolott** [dotnet/runtime#37356]
### Description

We are shipping microservices using the worker template (which use `Microsoft.Extensions.Hosting`) using these docker images:
* `mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build`
* `mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS runtime`

When those images were upgraded to version `3.1.4` multiple microservices CI/CD pipelines started to fail with this output:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

In the meantime, we change our `Dockerfiles` to use a specific image version:

* `mcr.microsoft.com/dotnet/core/sdk:3.1.201-alpine AS build`
* `mcr.microsoft.com/dotnet/core/aspnet:3.1.3-alpine AS runtime`

And everything works as intended

### Configuration
This is my `dotnet --info` output

```shell
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0090613580

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Regression?

It was working in the previous version. (3.1.3)

**Comment by safern** [comment]
Thanks, @xolott. It seems like `Microsoft.Extensions.Hosting.Abstractions` is part of the ASP.NET shared framework and that it got serviced on `3.1.4` and the implementation assembly version got bumped and somehow is causing a mismatch on the version with what your app was built against when you move to the newer docker image.

I believe the short workaround would be to rebuild your solution against ASP.NET 3.1.4. 

@ericstj do you have any idea how to prevent this from happening on future servicing releases? I wonder why do ref and implementation have to match if implementation is newer?

**Comment by ericstj** [comment]
.NET core should not error when version of def is higher than ref.  This error indicates that the def was lower than the ref.   This would happen when running on a 3.1.0 shared framework, or if the host decided to load the wrong assembly due to bad information in the app or shared framework's deps file.  @vitek-karas could provide some debugging steps to enable logging from the host to see what file it chose here.

In NetCore.App we never service the ref-pack with new assembly versions.  This is because the ref-pack must match the lowest (GA) runtime of the target framework.  If this assembly were in NetCore.App and a newer package version was referenced I would expect the newer assembly to be treated as app-local.  When run on 3.1.0 NetCore.App the app-local copy would be loaded.  When run on 3.1.2 or later I would expect the host to see that the shared framework version was >= and it would prefer that.

I know there were some reference assembly versioning issues with AspNetCore that may be at play here.  cc @Pilchie @dougbu

**Comment by vitek-karas** [comment]
You can turn on host tracing to determine what versions it looked at and which it chose:
```console
export COREHOST_TRACE=1
export COREHOST_TRACEFILE=host_trace.txt
<repro the failure>
```

This should produce `host_trace.txt` in the current directory which will have very detailed information about the assembly resolution process. If you decide to share this file, please be aware that it can contain names of local files, environment variable values and so on from the machine you're running the application on.

**Comment by Pilchie** [comment]
Tagging the rest of @dotnet/aspnet-build here.  Does this look like one of our previous issues?

**Comment by wtgodbe** [comment]
This is a known issue with the 3.1.300 SDK - it contains a version of the AspNetCore targeting pack that contains a bug causing these assembly load issues. Upgrading to 3.1.301 or 3.1.302 should resolve the issue.

If upgrading your SDK is impossible, you could also add the following workaround to your project file:

```
  <ItemGroup>
    <FrameworkReference
      Update="Microsoft.AspNetCore.App"
      TargetingPackVersion="3.1.3"
      />
  </ItemGroup>
```

This will tell the SDK to use the patched (`3.1.3`) targeting pack, rather than the bundled targeting pack (`3.1.2`), which has the bug.

**Comment by dougbu** [comment]
Yes, this looks like our previous issues. I _think_ 3.1.4 may have been the last time we had to fix our (ASP.NET Core-specific) targeting pack but it could also have been 3.1.5. @wtgodbe do you have a quicker way to confirm the versions❔

In any case, targeting pack information isn't listed above directly but 3.1.302 is newer than 3.1.300 and should include our most recent targeting pack IIRC.

**Comment by dougbu** [comment]
Oops, didn't see @wtgodbe's response😺

**Comment by eerhardt** [comment]
Closing as this was fixed. See @wtgodbe's response above for how to get the fix.
