### ISSUE TITLE
Large object heap does not respect System.GC.HeapHardLimit

### ISSUE THREAD

**Issue by lippinio** [dotnet/runtime#37410]
### Description
System.GC.HeapHardLimit is not respected when objects on Large object heap are allocated. 
Application Freezes due GC if HeapHardLimit is reached instead of throwing an OutOfMemoryException.

#### Expected behaivour
Throw out of Memory Exception
#### Observed behavior
Application try to GC and freezes

### Steps to reproduce

 

1. Set HeapHardLimit in runtimeconfig.template.json
`{
  "configProperties": {
    "System.GC.HeapHardLimit": 2147483648
  }
}`

2. Allocate large objects
`           
var list = new List<byte[]>();
                while (true)
                {
                    list.Add(new byte[10485760]);
                }`

### Behaviour on small Objects
With small Objects everything is fine. Like if you try `new byte[1024]`

**Comment by Maoni0** [comment]
thanks for reporting this! this is because `should_retry_other_heap` is reporting we should retry yet `virtual_commit` says we cannot commit more. so we go into an infinite loop. this was exacerbated when we added the POH because now we reserve a lot more (I don't think POH should reserve this much but that's a separated issue and I haven't really looked at POH tuning yet). 

I'll have a fix soon.

**Comment by lippinio** [comment]
Any Updates here?

**Comment by Maoni0** [comment]
not yet; I'm still in the process of finishing up some other work. I aim to get this in for the next preview build.

**Comment by Maoni0** [comment]
just making sure - you are seeing this with Server GC, correct? there shouldn't be a problem if you use Workstation GC.

**Comment by lippinio** [comment]
Yes in server gc.

**Comment by Maoni0** [comment]
fixed by [#38071](https://github.com/dotnet/runtime/pull/38071)
