### ISSUE TITLE
ARM64: Investigate why more stack space is allocated than needed and why they are not aligned

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#37429]
This was brought to the attention by @TamarChristinaArm in https://github.com/dotnet/runtime/pull/37139#issuecomment-635892020. For a method that takes 2 `Vector64<>` parameters, there are couple of problems:
1. We allocate stack space of 48 bytes although we just want to store 16 bytes. 
2. The 16 bytes that is stored are not aligned properly. If they are aligned properly, we can convert it tp `stp` instead. 

Here is the sample code:
```
G_M35607_IG01:
        A9BD7BFD          stp     fp, lr, [sp,#-48]!
        910003FD          mov     fp, sp
        FD0017A0          str     d0, [fp,#40]
        FD000FA1          str     d1, [fp,#24]
						;; bbWeight=1    PerfScore 3.50
G_M35607_IG02:
        FD4017B0          ldr     d16, [fp,#40]
        FD400FB1          ldr     d17, [fp,#24]
        0EB01E10          mov     v16.8b, v16.8b
```

Here is the assembly code for reference: [Create_after.txt](https://github.com/dotnet/runtime/files/4698903/Create_after.txt)

**Comment by kunalspathak** [comment]
@BruceForstall , @CarolEidt

**Comment by CarolEidt** [comment]
As I mentioned [here](https://github.com/dotnet/runtime/pull/37139#issuecomment-638502745) this appears to be because `Compiler::getSIMDTypeAlignment` which is called by `Compiler::lvaAllocLocalAndSetVirtualOffset` always returns 16 for `TARGET_ARM64` which it should not be doing for 8-byte vectors. That accounts for 32 of the 48 bytes. The remaining bytes are because we store fp and we're aligning to 16 bytes.

**Comment by kunalspathak** [comment]
> always returns 16 for TARGET_ARM64 which it should not be doing for 8-byte vectors. 

Thanks @CarolEidt , I will try out this suggestion and verify that the change doesn't regress anywhere else.
