### ISSUE TITLE
Mono not producing native binaries with version header in Windows

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#37503]
While working on collapsing the mono official builds into single legs, I noticed that we don't produce a runtime pack for Windows:
https://github.com/dotnet/runtime/blob/704be185161f0d30cd9ab52acb2f5aad12ec5857/eng/pipelines/runtime-official.yml#L227-L249

I added that to my test change and the windows build failed with:
```
F:\workspace\_work\1\s\.packages\microsoft.dotnet.build.tasks.sharedframework.sdk\5.0.0-beta.20280.1\targets\framework.dependency.targets(201,5): Missing FileVersion in 1 shared framework files:
F:\workspace\_work\1\s\artifacts\bin\mono\Windows_NT.x64.Release\coreclr.dll [F:\workspace\_work\1\s\src\installer\pkg\projects\netcoreapp\src\netcoreapp.depproj]
```

As a workaround I will be setting PermitDllAndExeFilesLackingFileVersion=true for mono on windows in `installer/netcoreapp.depproj` to start producing the runtime pack for Windows. However, we should fix this. 

cc: @steveisok @akoeplinger @marek-safar

**Comment by safern** [comment]
@akoeplinger as discussed offline, assigning to you.

**Comment by safern** [comment]
When fixing this we should remove the temporary workaround in: https://github.com/dotnet/runtime/pull/37511/files#diff-9fac0b3c275ca346bd7e392f9ae3807cR7

**Comment by hoyosjs** [comment]
Another issue here that might not be obvious is that the symbol indexer will see CoreCLR and try to index the special modules with it: the DAC (mscordaccore/libmscordaccore) and the DBI (mscordbi/libmscordbi). I don't expect this to be an issue because it indexes modules with a index composed of the version + an identifier composed of timestamp and size on windows and the build ID on linux, but I don't know if the same indexing logic applies to Mono. See other impact in https://github.com/dotnet/runtime/issues/34202. @mikem8361, what happens if the indexer doesn't find the dac and dbi in the same package as coreclr.

**Comment by mikem8361** [comment]
If there is no DAC or DBI module for the coreclr module (currently only “coreclr.dll”, “libcoreclr.so” or “libcoreclr.dylib”), the uploader ignores it and displays an warning if the tracing level is high enough.
