### ISSUE TITLE
Review Substring usages

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#37557]
A Span could be used and be more efficient than Substring in some cases.

For example, there are many Substring calls [here](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/Common/tests/System/Net/Http/LoopbackServer.AuthenticationHelpers.cs) (This is just an example, I'd expect more usages across the repo)

If these could make use of the Span<T>, it'd be much much more better.

**Comment by stephentoub** [comment]
> For example, there are many Substring calls here

That's in a test.

**Comment by Youssef1313** [comment]
Oh, sorry didn't notice that. Let me try to search if there occurrences that aren't in tests.

**Comment by Youssef1313** [comment]
Examples on non-test code:

- https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.Xml/src/System/Xml/XPath/Internal/StringFunctions.cs

- https://github.com/dotnet/runtime/blob/4b03513e20e0caf9ee34817eb74356903f1bb33e/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs

- https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/PhoneAttribute.cs

**Comment by stephentoub** [comment]
Thanks. If there are specific cases you've seen that could be improved, please feel free to submit PRs for them. In general, though, a broad issue about reviewing all Substring usage isn't particularly actionable: when is the issue complete? I'd rather such a concern be addressed more holistically, with an analyzer that would help find all relevant uses, both in this codebase and others, that would help fix them, and that would highlight new violations as they're being written, rather than having to continually audit manually. And that's many to be covered by https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+substring+label%3Acode-analyzer.

**Comment by Youssef1313** [comment]
Thanks. I'll close in favor of the currently opened issues that you referred to.
Certainly, I'd submit PRs if I could improve something.
