### ISSUE TITLE
build.sh --pack option doesn't generate nuget packages

### ISSUE THREAD

**Issue by kumbham** [dotnet/runtime#37551]
Steps to reproduce:
```./build.sh --projects src/libraries/System.Collections.Immutable/src/System.Collections.Immutable.csproj --pack```

Output:
```
  Determining projects to restore...
  Tool 'coverlet.console' (version '1.7.2') was restored. Available commands: coverlet
  Tool 'dotnet-reportgenerator-globaltool' (version '4.5.8') was restored. Available commands: reportgenerator
  Tool 'microsoft.dotnet.xharness.cli' (version '1.0.0-prerelease.20303.2') was restored. Available commands: xharness

  Restore was successful.
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  System.Collections.Immutable -> runtime/artifacts/bin/System.Collections.Immutable/Debug/System.Collections.Immutable.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

Wanted to check if this is the correct way to generate nupkg packages? If not, could you please guide me on how to generate nuget packages for the library?

**Comment by kumbham** [comment]
@ViktorHofer @safern any thoughts?

**Comment by safern** [comment]
@kumbham in order to build packages we have special projects, which are `pkgproj` as we use other targets and do special stuff in order to build them, so we don't use pack. I think we could endup using pack, but I suspect that being a somewhat considerable change... we could of course always override the pack target and just make it depend on `build` which is the target we execute for those projects.

You can read this thread in order to see how to build an individual nuget package quickly: 
https://github.com/dotnet/runtime/issues/32249#issuecomment-622124361

However, you can always do, `build.cmd -allConfigurations` and that will build all nuget packages (but it is longer than the regular build). The post I shared above is a shortcut to make it faster.

**Comment by ViktorHofer** [comment]
> I think we could endup using pack, but I suspect that being a somewhat considerable change... we could of course always override the pack target and just make it depend on build which is the target we execute for those projects.

Actually that's something that @ericstj and I discussed in one of our last meetings and we believe that we can enable this low-cost by overriding the Pack target and point it to the pkgproj (what you said above). https://github.com/dotnet/runtime/pull/35606 will lay the foundation for this as you will be possible to build for all configurations without any vertical upfront restore or build besides the one for net5.0 (NetCoreAppCurrent).

You would do an initial build of the libraries and then just invoke `dotnet pack` on either the sln, the ref's or src's csproj or on the pkgproj. Going even further we discussed a) getting rid of pkgprojs long term (XL task!) and b) collapsing ref and src projects together which we would do for a different reason but would also help here as it makes the entry point for `dotnet pack` more obvious.
