### ISSUE TITLE
`AssemblyLoadContext` confusion when running ASP in a native host

### ISSUE THREAD

**Issue by sanosdole** [dotnet/runtime#37584]
I'm still not sure if this is an Issue, but according to dotnet/runtime#35465 there is some confusion around using a `libhost` hosted runtime and ALCs (`AssemblyLoadContext`).

The Problem occurs when running an ASP application in a `libhost`  hosted runtime. Code can be seen in the [nodeclrhost project](https://github.com/sanosdole/nodeclrhost).

We use a default dotnet core 3.1 web app (`TestApp`). This app then references an assembly (`NodeHostEnvironment`) which provides an API to the hosting environment. The native hosting code (`coreclr-hosting`) loads the runtime using the following commands:

1. `get_hostfxr_path` with `assembly_path` set to `TestApp`
2. `hostfxr_initialize_for_runtime_config` using the `TestApp.runtimeconfig.json`
3. Uses `hostfxr_set_runtime_property_value` to set `APP_CONTEXT_BASE_DIRECTORY`, `APP_PATHS`, `APP_NI_PATHS` & `APP_CONTEXT_DEPS_FILES`
4. `hostfxr_get_runtime_delegate` with `hdt_load_assembly_and_get_function_pointer`

After this setup the `TestApp` is started using those steps:

1. Uses the callback `load_assembly_and_get_function_pointer` with `assembly_path` set to `TestApp` to load a static method (`NativeEntryPoint.RunHostedApplication`) from a type in `NodeHostEnvironment`
2. The static method uses `Assembly.Load("TestApp")` to load the `TestApp` assembly and executes its `EntryPoint`. This will use an __isolated ALC__.

Now the `TestApp` sets up an ASP application which in turn uses `Assembly.Load` to load `TestApp` again. But this time it (including its dependencies) is loaded into the __default ALC__.

This duplication/isolation is clearly not intented, and causes problems. We currently employ a workaround by loading the `NodeHostEnvironment` again into the default ALC and invoking the `NativeEntryPoint.RunHostedApplication` through reflection.

Although we do not use the isolation right now, I believe that it is correct and desired for further features (e.g. reloading the app during development, supporting npm packages build with dotnet, etc.).

I think it would be nice if the isolated ALC would be used when the ASP code loads assemblies. Also it would be nice if some of those runtime-properties would be configurable per "ALC", but I have not thought a lot about it. At least the `APP_PATHS` property is strongly connected to the assembly loading and required for the ASP code to find the assemblies in the first place.

Maybe this is just a Problem with the way ASP loads assemblies and we need the workaround for running ASP applications? I doubt the ASP team would re-implement all their assembly loading to make it work with an isolated ALC.

Also the proposals in dotnet/runtime#35465 & dotnet/runtime#36990 include an option to turn off the isolated context for `load_assembly_and_get_function_pointer`. This would basically be the workaround we implemented right now.

**Comment by vitek-karas** [comment]
As you mention the ability to invoke code in default ALC from native host is being work on now by @rseanhall  - the design is described here: https://github.com/dotnet/runtime/blob/master/docs/design/features/native-hosting.md#calling-managed-function-net-5-and-above.
Note that for that to work all of the code will need to be loaded into the default ALC, so the native hosting will need to use `hostfxr_intiailize_for_dotnet_command_line`.

With that approach I think even ASP.NET should work just fine - in default ALC.

As for isolating ASP.NET application into a secondary ALC - there's an issue on it here: https://github.com/dotnet/aspnetcore/issues/21159. It's something we've heard about, but nobody really looked into it in detail. It's not something the runtime itself can easily solve because we still want to load the ASP.NET framework into the Default ALC (no need to reload that every time, plus it's currently the only way to actually load frameworks), and then load the app alone into secondary ALC. So if the framework is doing work on behalf the app it needs to be aware of which ALC to use (especially if there are to be multiple apps loaded at the same time). As mentioned it might be possible to workaround at least some of the problems with `CurrentContextualReflectionContext`. 

As for unloading that's actually even harder, see the ASP.NET issue for a bit more details on that.

**Comment by vitek-karas** [comment]
As for the title of this issue - I don't think the `Assembly.Load` API is doing anything wrong here.

**Comment by sanosdole** [comment]
Thanks, that helps.

So once .NET 5 is available we use `hostfxr_intiailize_for_dotnet_command_line` (which will also set the runtime properties properly) and the new `hdt_get_function_pointer` instead of our current workaround to force the default ALC.

If we want isolation (e.g. multiple dotnet components) we do it setting up the `AssemblyLoadContext` and ensure that the `NodeHostEnvironment` is shared to the context.

If the ASP team one day supports running apps in an isolated ALC, we can implement features like reloading the app that require isolation.

I`ll still have to figure out how to support the multiple component scenario with the app scenario in one process, as the app has to initialize the runtime first before loading components. But this feature is currently not required, and will not be implemented if it is too complicated.

The most requested feature is reloading for a "dotnet watch" like behavior though. Are there alternatives from the runtime besides waiting for dotnet/aspnetcore#21159 to be implemented (if it ever will)?

I think this issue can be closed as there are already dotnet/aspnetcore#21159 &  #36990 ?

**Comment by vitek-karas** [comment]
Glad to hear this might work for you in the end (at least for the core scenario).

I forgot to address the `APP_PATH` question above: `APP_PATH` and similar properties are basically a left-over from the old days. I would not recommend using those. The correct way to customize assembly resolution is to do it in code. For secondary ALCs you get to implement `AssemblyLoadContext.Load` which gives you full control over everything. For the default ALC you can implement an event handler to `AssemblyLoadContext.Resolving` event, this lets you handle resolution of assemblies which would otherwise fail to resolve. In either case implement something like `APP_PATH` is really easy, basically take the name of the assembly being resolved, append `.dll`, and try to look it up in the desired folders. Once found, call `AssemblyLoadContext.LoadFromAssemblyPath` and return it. It does require a little bit of code to do something like `APP_PATH`, but it gives you full flexibility in handling anything else/special you might want at the same time.

Re "dotnet watch": We have no plans to support any other assembly isolation feature outside of `AssemblyLoadContext` and thus until the ASP.NET can handle running apps in separate ALCs (and realistically also unload them) I don't think a true in-proc solution for "dotnet watch" is available. The current solution is out-of-proc, which works, but it's relatively slow to reload.
