### ISSUE TITLE
Marshal.GetActiveObject() for .Net Core 3.1

### ISSUE THREAD

**Issue by EuroEager2008** [dotnet/runtime#37617]
Marshal.GetActiveObject() is missing even though COM is supported.
I don't know if other useful (COM related) API's are missing as well.

There should be a way of getting an existing instance of e.g. Excel using .Net Core 3.1.
Are there possibly alternatives?

**Comment by AaronRobinsonMSFT** [comment]
>Marshal.GetActiveObject() is missing even though COM is supported.

@EuroEager2008 That API was originally removed from .NET Core since COM support was not included. In .NET Core 3.0 we brought back a subset of COM support in order to enable targeted scenarios and aid in porting code from .NET Framework to .NET Core. Exactly what APIs we decided to bring back wasn't really well defined but more a matter of what was the minimum needed to support COM. I believe this is the first ask/request for this particular API.

The `Marshal.GetActiveObject()` API is a simple wrapper over the [Running Object Table](https://docs.microsoft.com/windows/win32/com/registering-objects-in-the-rot) (ROT) and relies on specific Win32 APIs that can easily be called via a P/Invoke. An example of how to manually communicate with the ROT can be found at https://github.com/AaronRobinsonMSFT/COMInterop/blob/master/OutOfProcDemo. It is unlikely that we will bring this API back, but please [submit a new or update this issue to an api-proposal](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) if you feel this is a must have for your scenario.

**Comment by AaronRobinsonMSFT** [comment]
@EuroEager2008 I just realized there is also the Win32 API that can be call via P/Invoke as well: [`GetActiveObject()`](https://docs.microsoft.com/windows/win32/api/oleauto/nf-oleauto-getactiveobject).

**Comment by AaronRobinsonMSFT** [comment]
Given that there is a direct P/Invoke solution to a well-defined Win32 API, I am going to close this. I have verified that the latest .NET Framework implementation was simply doing that as well.

**Comment by EuroEager2008** [comment]
Thanks, works fine :)
