### ISSUE TITLE
Compile Windows specific com files while building against Unix

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#37782]
we are compiling com files while targeting unix as well
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime.InteropServices/src/System.Runtime.InteropServices.csproj#L15

 I checked the history and its always been like this.
 Its started failing when i removed the crosstargeting here. This should not have been the case 

@safern @ViktorHofer @ericstj am i missing something here ?

```
  System.DirectoryServices.AccountManagement -> /Users/runner/runners/2.170.1/work/1/s/artifacts/bin/System.DirectoryServices.AccountManagement/netstandard2.0-Debug/System.DirectoryServices.AccountManagement.dll
  System.DirectoryServices -> /Users/runner/runners/2.170.1/work/1/s/artifacts/bin/System.DirectoryServices/netstandard2.0-Debug/System.DirectoryServices.dll
/Users/runner/runners/2.170.1/work/1/s/src/libraries/Common/src/Interop/Windows/Ole32/Interop.CoGetStandardMarshal.cs(12,9): error BCL0015: ole32.dll!CoGetStandardMarshal is not supported on one\more targeted platforms. [/Users/runner/runners/2.170.1/work/1/s/src/libraries/System.Runtime.InteropServices/src/System.Runtime.InteropServices.csproj]
##[error]src/libraries/Common/src/Interop/Windows/Ole32/Interop.CoGetStandardMarshal.cs(12,9): error BCL0015: (NETCORE_ENGINEERING_TELEMETRY=Build) ole32.dll!CoGetStandardMarshal is not supported on one\more targeted platforms.
  System.DirectoryServices.Protocols -> /Users/runner/runners/2.170.1/work/1/s/artifacts/bin/System.DirectoryServices.Protocols/net5.0-OSX-Debug/System.DirectoryServices.Protocols.dll
  System.Dy
```

**Comment by safern** [comment]
The error you're hitting is because of the PInvoke analyzer... that API is in the allowed APIs list for windows:https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.CodeAnalysis/build/Microsoft.DotNet.CodeAnalysis.targets#L9However, we depend on TargetsUnix property to disable that analyzer:https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.CodeAnalysis/build/Microsoft.DotNet.CodeAnalysis.targets#L31

That's why when we stop cross-targeting this project, the PInvoke analyzer is now running for Unix build as well. 

We could disable the PInvoke analyzer for this project but I don't know if we want to do this... this code seems very Windows specific... do we actually expect it to work on Unix? cc: @AaronRobinsonMSFT

**Comment by safern** [comment]
cc: @ericstj

**Comment by AaronRobinsonMSFT** [comment]
>do we actually expect it to work on Unix?

@safern Thanks for tagging me. I have no idea what this API is or how it works in practice. The `Interop.CoGetStandardMarshal` API is Windows only and there is no reasonable way to implement that on a non-Windows platform. I would say that is a good code smell for something not intended to run on a non-Windows platform.

**Comment by ericstj** [comment]
Here is the change that introduced this: https://github.com/dotnet/runtime/commit/7f3c4378aa25b3f8bd26d0a1e2bd9c01d449fddd

This is not ifdef'ed for Windows.  It probably should be.  

We should implement StandardOleMarshalObject in a way that it doesn't try to call into ole32.dll on linux.  That either means throwing or just returning some default value.

One thing that could be done here is push this down into corelib: if we did that we wouldn't need to cross-compile InteropServices.

**Comment by Anipik** [comment]
This was ported as a part of supporting wpf/winforms related stuff, i can take the lead the on fixing this.
