### ISSUE TITLE
Q: How to use UnmanagedCallersOnlyAttribute?

### ISSUE THREAD

**Issue by hypeartist** [dotnet/runtime#37930]
Is there any info on how to use that new attribute? 
All I have found is: [https://github.com/dotnet/runtime/blob/f185bd5571f2500b4843d145418c4418747246b6/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/UnmanagedCallersOnlyAttribute.cs#L8](https://github.com/dotnet/runtime/blob/f185bd5571f2500b4843d145418c4418747246b6/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/UnmanagedCallersOnlyAttribute.cs#L8)
I have tried to apply it to some static POD method of a class library but what next? It doesn't show up in exports (used some third-party tools to check) and also I can't obtain its address having dll's handle via `GetProcAddress`.

Thanks in advance for any clarification.
PS: using .NET 5 Preview 7

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@hypeartist The `UnmanagedCallersOnlyAttribute` is used to produce the most lite weight version of a function pointer to a managed function that can be call outside the runtime. The ability to create a function pointers in C# was recently exposed in C# 9 - see [proposal](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md) and tracking issue https://github.com/dotnet/roslyn/issues/39865. Consuming function pointers isn't the only way this feature can be used, but is definitely the most obvious utilization of this attribute.

Another way to use this attribute is via the low level hosting APIs - [`load_assembly_and_get_function_pointer`](https://docs.microsoft.com/dotnet/core/tutorials/netcore-hosting) (PR https://github.com/dotnet/runtime/pull/35763). Leveraging this low level API is how the [DNNE](https://github.com/AaronRobinsonMSFT/DNNE) package creates a native export.

This attribute is really a low level building block for tooling or providing symmetry for C# function pointers.

**Comment by tomrus88** [comment]
So this attribute itself doesn't create native export and you need to go extra mile if you need one?

Is it safe to use C# function pointers feature to get a pointer to C# method and manually pass that pointer to native code (using pinvoke or something)?

What's the difference compared to Marshal.GetFunctionPointerForDelegate?

**Comment by AaronRobinsonMSFT** [comment]
>So this attribute itself doesn't create native export and you need to go extra mile if you need one?

Correct. It is an attribute that indicates to the JIT that this function will only be called from a non-managed context and therefore you should add that transition logic.

>Is it safe to use C# function pointers feature to get a pointer to C# method and manually pass that pointer to native code (using pinvoke or something)?

Yes. That is exactly the intent - the function itself and subsequently the pointer can only be dispatched to in an unmanaged way. Note that the `calli` instruction does permit an unmanaged dispatch.

>What's the difference compared to Marshal.GetFunctionPointerForDelegate?

Mostly performance and an allocation. Using `Marshal.GetFunctionPointerForDelegate` requires a delegate allocation but using the C# function pointers update to `address-of` (i.e. `&`) the address can be taken of a manged function with the above attribute and then immediately passed to native instead of allocating a delegate.
