### ISSUE TITLE
Add feature-switch for invariant TimeZone support

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#37973]
For size sensitive apps it'd be very helpful to have an option (feature switch) to exclude full time-zones support. This is something that is supported by Blazor 3.2 as an opt-in feature which we should not regress on.

@eerhardt

**Comment by Clockwork-Muse** [comment]
... This is implying that we'd be distributing our own copy of timezone data?  Or is this something else?  Traditionally, we've pulled from the OS for desktop/server deployments, which would mean the size of the timezone data with an app is `0`.  

Note that the full tzdb is < 400kb, and is trivially amenable to CDN delivery/caching.  Perhaps Blazor should also add the ability to specify a web resource for this, so it can be delivered out-of-band from the app itself?

**Comment by joperezr** [comment]
@eerhardt at least the setting seems to already be present in the SDK so isn't this one done already? https://github.com/dotnet/sdk/blob/408fe82020f979ec65862add4d5b1dd85fef5d80/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L396-L399

What am I missing?

@Clockwork-Muse The point here is to have a switch so that consumers can choose to always treat the Timezone as Invariant with the intent of reducing the application final size once it gets linked since all of the code in the framework that takes Timezones and compares them will be optimized out.

**Comment by eerhardt** [comment]
> @eerhardt at least the setting seems to already be present in the SDK so isn't this one done already? 
> What am I missing?

The `InvariantGlobalization` setting only affects the globalization data that we read from ICU. In relation to TimeZones, the only thing `InvariantGlobalization` affects is how we look up time zone names - we will use a non-localized name from the tzdata file. We will need a new setting here since we've shipped `InvariantGlobalization` already with the current TimeZone behavior.

> This is something that is supported by Blazor 3.2 as an opt-in feature which we should not regress on.

In Blazor WASM 3.2, we shipped an MSBuild property named `BlazorEnableTimeZoneSupport`, which removes the `dotnet.timezones.dat` file from the app. That functionality is in `5.0-preview8` currently.

This work item is to introduce a new feature switch in the BCL which will disable Time Zone support altogether (even without the app being linked, as feature switches can be configured by AppContext). The feature switch will also be used to trim the TimeZoneInfo code in Blazor WASM, when enabled.

Since this is net-new functionality that changes behavior, and .NET 5 is closing down, I don't believe this is strictly necessary to ship .NET 5. The behavior from 3.2 is not regressed with the current bits.

In 6.0, we can introduce a new feature switch in this area.

cc @pranavkm

**Comment by SamMonoRT** [comment]
@eerhardt @pranavkm - Still seems to be in Uncommitted state - do we think this is possible to fit in for .NET6 ?

**Comment by eerhardt** [comment]
I don't believe this will fit into 6.0. Moving to `Future`.

**Comment by pavelsavara** [comment]
After https://github.com/dotnet/runtime/pull/82250 the `BlazorEnableTimeZoneSupport ` feature is broken and this issue is good way how to make it work again.

**Comment by danmoseley** [comment]
Is this potentially helpful for current AOT work @eerhardt .. or is it a subset of invariant globalization flag?

**Comment by eerhardt** [comment]
> is it a subset of invariant globalization flag?

See https://github.com/dotnet/runtime/issues/37973#issuecomment-666734725

> Is this potentially helpful for current AOT work

It is minorly helpful. TimeZoneInfo has some code in it that can be trimmed, but it won't move the needle on a web app. TimeZoneInfo is already trimmed in a "Hello, World" app.

Using version `8.0.100-preview.5.23265.3` of the .NET SDK on win-x64 the rough cost of TimeZoneInfo is:

**Console.WriteLine("Hello, World!")**: `1.19 MB (1,257,984 bytes)`
**Console.WriteLine(DateTime.Now)**: `1.34 MB (1,405,952 bytes)`

So TimeZoneInfo adds about 145 KB. For linux-x64 it is slightly larger at 180 KB.

The real savings here is when we can exclude the tzdata information. The only place I know of where this is helpful is browser-wasm apps. Everywhere else we get the tzdata information already on the OS.

**Comment by pavelsavara** [comment]
On wasm tzdata is now bundled into .wasm file, about 220KB. Previously it was separate file which `BlazorEnableTimeZoneSupport` flag removed from download. In order to fix it, we need similar feature-switch in the runtime for wasm, which will skip bundling the TZ into the .wasm file (while recompiled with wasm-tools workload) and redirect `BlazorEnableTimeZoneSupport` into the new runtime flag.

**Comment by Clockwork-Muse** [comment]
... given JS (and thus presumably wasm) has the [`Temporal` proposal](https://tc39.es/proposal-temporal/docs/index.html), which includes timezone info, would one route to take be to shim calls to the native library?

Obviously not out yet, also obviously you need an implementing browser.  But it could mean you don't need to ship the timezones to clients (unless you really want to, to potentially ensure certain data, but that should normally be an edge case).

**Comment by danmoseley** [comment]
> So TimeZoneInfo adds about 145 KB. For linux-x64 it is slightly larger at 180 KB.

That's still ~2% of stage 1, right? Or it's already out of stage 1?

**Comment by eerhardt** [comment]
TimeZoneInfo is in stage 1. That's why I said it is "minorly helpful", but it won't move the needle. Stage 1 is rather small compared to a real world web app. I don't believe we would turn this switch on by default.
