### ISSUE TITLE
Process totally frozen.

### ISSUE THREAD

**Issue by rubarax** [dotnet/runtime#37983]
Hi there,

We saw an issue with a process (a server) that got totally stuck: no connections accepted, no background jobs run, no new log entries.

It looks totally frozen, although the process is kept alive. The memory usage remained constant and there was no CPU usage (which makes sense since it looked frozen).

The binaries were compiled with NET Core 3.1.100 and the process was run in Ubuntu 18.04.4 LTS, x64

I attach a dump of the process after being 20 minutes in that way. It was done with the _createdump_ app.

https://public-dumps.s3.eu-central-1.amazonaws.com/dump.20200616_1238

Any help will be appreciated. Thanks!

**Comment by danmosemsft** [comment]
Thanks, if there is any chance this dump may contain non public info (eg., secrets, environment variables, sensitive paths or user names, etc) you will want to secure it.

**Comment by danmosemsft** [comment]
Also, is it possible for you to post some relevant stacks? All the symbols (at least managed ones) should be publicly resolvable. This dump will take a few hours to download as we're all at home these days 😄

**Comment by adamsitnik** [comment]
@tommcdon I've changed the area from `System.Diagnostics.Process` to `System.Diagnostics` since it's more related to diagnostics rather than the `System.Diagnostics.Process` class. Who would be the best person to take a look at this memory dump?

**Comment by tommcdon** [comment]
@hoyosjs can you take a look?

**Comment by hoyosjs** [comment]
The dump is in a state I can't see too much in it:
- All threads are in preemptive mode and this is a server GC in progress. The runtime has 307 active threads and 3 dead ones, all of them trying to synchronize on some type of primitive or blocked in IO.
- There's a lot of locking happening in `plasticd` but very few actually get to the wait, most are waiting for the GC to happen. It's almost as if every plasticd call is within a `lock` statement, `Monitor.Wait`, or `Monitor.WaitTimeout` or a `ManualResetEvent`
- There's a few threads blocked waiting for IO (UDP, TCP, and HTTP) from components within libraries like `Google.Apis.Core.dll`
- A lot of them are waiting on `RareDisablePreemptiveGC` (270+), and some on other synchronization  so they need the gc to finish before they can continue.
- Of the 8 gc threads, 7 are waiting on the "assembly list lock" critical section. The other thread is waiting on `join` for the other. No one holds the critical section, but it feels like the other GC thread just got done with it. Once those finish, then a bunch of threads would be unblocked and there could be some .

I can't see much beyond that given the state of the heap, so I say it's lock contention or starvation for sure. However, it does feel weird to see these many different locks being waited on.  If you are still having this issue, I'd say our next steps would be collecting traces (preferably using perfcollect so that we can get native state) and a couple dumps at different points in time, to see if any progress is happening.

**Comment by tommcdon** [comment]
Closing as this is currently non-actionable
