### ISSUE TITLE
System.Threading.Channels for netstandard2.1

### ISSUE THREAD

**Issue by almazik** [dotnet/runtime#38046]
## Background and Motivation

At the moment the API of System.Threading.Channels package lacks ChannelReader<T>.ReadAllAsync method in netstandard2.0 and netstandard1.3 unlike netcoreapp target. 
The reason is obvious - IAsyncEnumerable is not defined in the netstandard 1.3/2.0. But it is defined in netstandard2.1, thus it is logical to add netstandard2.1 target to the library with ChannelReader<T>.ReadAllAsync method present.

## Proposed API

Add a new netstandard2.1 target to System.Threading.Channels library and include ChannelReader<T>.ReadAllAsync implementation in it.

**Comment by tarekgh** [comment]
@terrajobst could you please advise about that? 

CC @stephentoub

**Comment by terrajobst** [comment]
Seems like a reasonable request to me

**Comment by almazik** [comment]
For the context - the exclusion of ChannelReader.ReadAllAsync method from netstandard targets is implemented by not including System.Threading.Channels.netcoreapp.cs file for these targets, see https://github.com/dotnet/runtime/blob/master/src/libraries/System.Threading.Channels/ref/System.Threading.Channels.csproj

The fix is simple and should touch only System.Threading.Channels.csproj file. I can submit a PR if this issue is accepted.

**Comment by tarekgh** [comment]
@almazik go ahead and submit a PR. @stephentoub do you have any concern here? like package size for instance?

**Comment by stephentoub** [comment]
No concerns from me with a netstandard2.1 implementation,.

**Comment by joperezr** [comment]
Isn't IAsyncEnumerable available in netstandard2.0 via the Microsoft.Bcl packages? If so, do we actually need to cross target?

**Comment by almazik** [comment]
Is removing the target for netcore3.0 considered a breaking change given that we are adding a netstandard 2.1 target?

**Comment by tarekgh** [comment]
@joperezr follow-up question: do you think it will be any problem if we added ns2.1 target to this package and some apps referencing `Microsoft.Bcl` packages at the same time? will we run into conflicts at that time? I am trying to know if the concern is only cross targeting or there will be other problems. 

I am thinking in the future, if we add new APIs that can be part of ns2.1, that will be good I think. 

@almazik is there any blocking issue to use `Microsoft.Bcl` for now when targeting ns2.1? I just want to understand more about your scenario.

**Comment by almazik** [comment]
If someone targets netstandard 2.1 AND uses Microsoft.Bcl.AsyncInterfaces package then they are already doing something wrong, as the Microsoft.Bcl.AsyncInterfaces package is a backfill for interfaces already declared in netstandard 2.1

By adding a netstandard 2.1 target to System.Threading.Channels, we do not change the status quo - customer already has 2 declarations of IAsyncEnumerable<T>. The only public change is the addition of the ReadAllAsync method to the ChannelReader<T>.

My issue was that I could not find `ReadAllAsync` method which I expected to see. I was using netcore 3.0 version of the documentation as there are no articles for netstandard targets of the package.

**Comment by tarekgh** [comment]
@joperezr I am not seeing any other way for using `ReadAllAsync` when targeting ns2.1 other than adding this targeting to the package. What exactly your concern here? is it only cross targeting?

**Comment by joperezr** [comment]
The only concern I had is that usually when you have shipped a package that exposes portable and TFM-specific API (meaning that in your package you have a netstandard2.0 and also netcoreappx.x reference assemblies) then you have to be careful when adding more things to portable TFMs. I haven't looked into the specifics of this one so it may not be a valid concern, but imagine this scenario: surface area of NS2.0 is (A), surface area of NCA3.0 is (A+B) meaning it has all surface area NS2.0 has plus some extra methods. If you now ship a NS2.1 assembly, you could potentially instead expose (A+C) and in some rare scenarios people might consume you and require (B) which they won't have any more. This is much more of a problem with assemblies that also ship in the shared framework specially in roll forward scenarios and S.T.Channels does ship in the shared framework, so that is my concern.

As to why I suggested keeping just evolving NS2.0 (which might not be possible) was because starting this thread the only concern looked to by that IAsyncEnumerable wasn't available in NS2.0, which actually is not the case if you use the Microsoft.Bcl package.

**Comment by almazik** [comment]
@joperezr By adding a NS2.1 target we will actually expose the same set of APIs as with NCA3.0, so that would be A+B.

And, on the contrary, if we just add Microsoft.Bcl.AsyncInterfaces to NS2.0, then the NS2.1 project consuming the System.Threading.Channels package will have a collision of NS2.1 IAsyncEnumerable with Microsoft.Bcl's IAsyncEnumerable exposed by System.Threading.Channels package. That would match "A+C" definition in your example

**Comment by joperezr** [comment]
I see, in that case, I would probably suggest to go ahead and add a NS2.1 target and remove NCA3.0 one (since NS2.1 should now work in NCA3.0). If this were an assembly only shipping OOB, then I would have no concern in doing this, but the fact that it also ships in the shared framework might mean we need to do some additional testing here to make sure things won't break.

**Comment by tarekgh** [comment]
@almazik do you want to go ahead and submit a PR for that? adding ns2.1 and remove netcoreapp3.0 targeting (with keeping CurrentNetCoreApp).

**Comment by almazik** [comment]
As I mentioned before:
> There are differences in implementation of AsyncOperation though. NetCore implementation [uses](https://github.com/dotnet/runtime/blob/8bd04e0170040096c201d0013c63833fe4b2e8d5/src/libraries/System.Threading.Channels/src/System/Threading/Channels/AsyncOperation.netcoreapp.cs#L15) IThreadPoolWorkItem while NetStandard implementation [uses](https://github.com/dotnet/runtime/blob/8bd04e0170040096c201d0013c63833fe4b2e8d5/src/libraries/System.Threading.Channels/src/System/Threading/Channels/AsyncOperation.netstandard.cs#L16) TaskFactory

This is done to reduce allocations as described [here](https://github.com/dotnet/runtime/commit/1cc5f8c24feeead293cc951b8afb4d32fe12ac89). So I would prefer not to remove the netcoreapp3.0 targeting as it will be an regression for netcore.

**Comment by tarekgh** [comment]
@almazik sorry I missed this part before. 

@terrajobst @stephentoub is it feasible to add `IThreadPoolWorkItem` to ns2.1 too? I know maybe we don't want to go that far just for that, but I was just wondering if this is feasible at all.

**Comment by stephentoub** [comment]
> is it feasible to add IThreadPoolWorkItem to ns2.1 too?

@terrajobst can correct me if I'm speaking out of line, but I don't believe we have any precedent for adding to the already released .NET Standards and wouldn't do so for this.

**Comment by almazik** [comment]
The corresponding pull request (#38053) has been merged, closing this issue
