### ISSUE TITLE
CryptoStream.FlushFinalBlockAsync method missing

### ISSUE THREAD

**Issue by rupertsciamenna89** [dotnet/runtime#38076]
## Background and Motivation
I'm creating a web API for file encryption with an AES Key. I creates an helper functions that generate an instance of EncryptedFileResult (an extension of ActionResult class that I created) where I encrypt the file.

I override the two methods ExecuteResult and ExecuteResultAsync.

The body of ExecuteResultAsync is the next:
```C#
var fs = GetCryptoStream(ms, Cypher);
await fs.CopyToAsync(ms);
fs.FlushFinalBlock();
await fs.FlushAsync();
```
When the program runs, at the line `fs.FlushFinalBlock();`, it generates an exception: 

```
'System.InvalidOperationException' in Microsoft.AspNetCore.Server.IIS.dll
Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
```

For the moment I set the AllowSynchronousIO to true, but it will be good to have an async overload for the FlushFinalBlock, to have the benefits of async methods. 
I would like to implements it.

## Proposed API

```C#
partial class CryptoStream
{
    public ValueTask FlushFinalBlockAsync(CancellationToken cancellationToken = default) => throw null;
}
```

## Usage Examples

Previous code could be this:

```C#
var fs = GetCryptoStream(ms, Cypher);
await fs.CopyToAsync(ms);
await fs.FlushFinalBlockAsync();
await fs.FlushAsync();
```

**Comment by vcsjones** [comment]
cc @bartonjs

**Comment by vcsjones** [comment]
It looks like the `FlushFinalBlock` implementation is already async:

https://github.com/dotnet/runtime/blob/643f5e1be543ef6582cf9b90c91e804f07e2bea4/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CryptoStream.cs#L106

Though a public version is not directly exposed. However, `DisposeAsync` will perform the asynchronous flush final block.

Assuming you are done with the `CryptoStream` as well, you could use `DisposeAsync` to cause the final block to be flushed.  

https://github.com/dotnet/runtime/blob/643f5e1be543ef6582cf9b90c91e804f07e2bea4/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CryptoStream.cs#L695

This might be a good work around for now instead of setting `AllowSynchronousIO`.

**Comment by bartonjs** [comment]
@stephentoub It doesn't look like it occurred to me to ask the question back then (https://github.com/dotnet/corefx/pull/33422), but: Did you consider adding `public (Value)Task FlushFinalBlockAsync(CancellationToken cancellationToken=default)` when you added `DisposeAsync()`?

I'm guessing it was just a narrow scope of "override DisposeAsync in all the right places"

**Comment by stephentoub** [comment]
> Did you consider adding public (Value)Task FlushFinalBlockAsync(CancellationToken cancellationToken=default) when you added DisposeAsync()?

I don't think I considered it.

> I'm guessing it was just a narrow scope of "override DisposeAsync in all the right places"

Yup.

**Comment by bartonjs** [comment]
Seems like we can do

```C#
partial class CryptoStream
{
    public ValueTask FlushFinalBlockAsync(CancellationToken cancellationToken = default) =>
        FlushFinalBlockAsync(useAsync: true, cancellationToken);
}
```

And plumb the token into all of the relevant places in the existing private FlushFinalBlockAsync(bool)

**Comment by terrajobst** [comment]
Looks good as proposed.

```C#
namespace System.Security.Cryptography
{
    partial class CryptoStream
    {
        public ValueTask FlushFinalBlockAsync(CancellationToken cancellationToken = default);
    }
}
```
