### ISSUE TITLE
JIT known generic casts not elided

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#38106]
### Description
When writing generic types, using a pattern as seen in `Vector<T>` (`if (typeof(T) == typeof(int)) ... if (typeof(T) == typeof(float)) ...`) once this construct grows to 9 blocks JIT will end up not correctly eliding some casts:
See [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgJgIwCwAUFgAwAEWeAdAEoCuAdjAJZhzUDCA9mAA4sANogDKiAG4sAxnCgBuYmXIiAFhAR8AMhGB0mrdgqKKAzJTwA2SjnKdiAb2LlnlM1SvAAnvHIBBKABC3nAAFABmgtwQMOTwsACUTi6ORC5plADs5CFe8PFxMEZpAL5JzmWu5h7BfoHBeOGR0bGyMImpyRVpWFn+eAA8uXAAfCEF8UUupR3lM5Xu5EO1QfA4jVEx4xUp6S49tTiDwaPjk87TaRUA2gBSLDAA4nCMiNJjnnxw3GE5wfHxAF1rgBZOAwFTcAAmAEl+IIQqDwVDYXxBAB5PisbiMKDUXwAc3xCFkUBY4jg0MYghYjBp+MBFSwbks5AAKrUBqzRhENuRxBBBPQ4PFyAB3FSIOBs8ggciwBD0KQwbZdFwsMLZGAfL4/VkigC8+ti2u+vzy7V2zh2lu6WRCepC3GAACs4Er4mbhfzBXAzukLpb1ZqTbqDUatZ9TVAhv9VVa4+l9vaPU7Xe6QtG/t6hX6Sgmg+9I6HyIbjUWQvQoBCEG0LZbrTbnEmHam3W0K1XuDX4tnfQmA7sCxGdcmS+GQxnq7WEw3G82Uy62x7O93e7mpvmNYWR3qx2WR/QadO5mlZzb547F+nD8wewKc/2E/s+ocuSFexMKgPyAnbvcni8CBvMOpoxgycxXIiEIwnCCJgtBKLopiLDYriBJEiSZIUlSNJ0uB3TMlY7Ivv0b48s0H5ihKxLSrK8qKsqcxnmqW4gcWpZsSER6xienS8bsF6tu6a6Pvx5BDhOu4cRO9CRIw9J1rszECXaLZXu2snYvSIlid+aQSeWUnjuWckKTOCa2tkalpu2pl3j667nJuwaGWG+6muRx42spiaqQuNkep59kPrpznbqaRnuT8kLcPQwDCDx3kWXsfmXgFIQxXFCU6TaemWvskJwGEECyTAyZ+tM1x3I8zyvFI4U/GBQIQVByKwa1MGohiWI4nihLElApLkpS1K0vJ+F7IR0r+K+3JNDElHipKtFyjACpKiqYnsgNpWOT+YkGTubmcWB5liWkO2CDERrJmlS6esFfahWJcCCFAUqHRFx0Tpm5pnY2LiXddVn+fdv1eveT25Qmr3veJrGSd95aVlOiX1slzhAyWIN3deK5tDllp5c4sMfQjrl7px+No0pGPkFjN3WWDqOE7sxPkKT8MuUdlMydxinpD5F2yKV2O3UJGncaz/ow29ZPc19vPlvz/0A/TItXWLTPCZDe3s5zn3scZB52QLp50wzOMSx6mnjdLeYvXLXMNaO0kmVpNOCxbGvA+L6kenZ9sbo7cOG67xsefNnvm+dgM+1roPpkFQdOSH8su5FnGZfFwpm3xavq1AouM4n7bZ9luuiTapOqwDluFcVpXlaJT5ZEDFXEMUQA==)
Removing any two blocks from `As2<T>` will improve code gen significantly (matching a non-generic version & the other version)
splitting up the function will also resolve the issue.

**Comment by AndyAyersMS** [comment]
The sharplab link is showing codegen for . Net Framework x86 jit. For core this [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9BrIAW2KGIAy2YO258BG6poDMTckiakGQmgG8aDL0zvNHwAE8MGAYAQVwAISCYAAoAM0kIbAwGYNwMAEpPbw9qb3ymAHYGGMDgjLSMK3yAX2yvep97f2iwyOjyeMTk1NVMxtyC72Ji8PIAHjKYAD4Yyozq7zq870biXwcGKbao4NIupJT5gcb8kbbSSejZ+cWvZfzGgG0AKV4MAHEYLhllOYCxDAIHFStEMhkALrPACyMAwOggABMAJLiSQxWHwpGosSSADyYj4EC4uBYoQA5uTYLhcLwFDBkVxJLwuCzyZC1htHAAVNoTbmzBKHBgKbCSDgwDIMADuOhkIV5IAY6SgHDAGBOKyGvDiJQwAKBIO5UoAvCbUgbgaDylktQVBkMCucYsaYhBgAArGDqjLWyWi8UwO4FB6OnV6y1G03m/WAq24Kbg045ZNDZ2u91en0xBNggMS4O1VMMcP/ONRhhmi3lmIcXAIqCZW2OhgOltedO+zPezK1+vQTL5oPF0Pa3Vlw0u6PVyf9xtJu35Nvtztuz0931zwdigsj4ul2OT42VmOR2sspvF5ct1fd7McC8ZIeFpbF85jS4CmJDhaNUcMYtXneL4figP5DytRMOTtJ5MQRFE0QxOF4JxfFCV4YlSQpKlVFpelGWZVkuHZKE7XWZoGF5D9xi/IUeh/GU5VgSiGCVFU1Q1O1r28A8z2PKsIJBR9m0dbi02KKc1yzbdAxfe593HQSpxPGcrQ4RJiIXFsxKdCSM3Xe8NPZZ890XHjFL46clKMrTROLM49K7AzexskyzPk9ySwsmt+NPGs6MvTydIckp9Ok30AqfHdh08/98l4nyrLPREIA4YBpFsoZguGRypI3GIUrSjK3JbOLHXOREYDibB1IwKdg2WZ43k+b5fjACdILBaD8lg5DsUQuD+txAkiRJMlKWpPCGSZFk2W64YuRY8JP0FboUgY2V5RYtiMFVdVNRbXlqVquSAM8hKjySmsoKvezvGOyQUnNSS717RMSsdMqvBgSRcBCC6rV81SQVzG1bs8/IHqe0KnPCnN3ui06voYH6/q8iNEpUpS6wbQLtLurwocrGG8vvLcotk0yW1R/7vMurGz3JkSsoJhgieesL8vJj6hmRmn0Y6isBLPB8eEy+1WfZknXt9UWZN3WLi35gGhb8ydhPB9t7tUWriZe5yKYV0qld+2mMfp4Wa3U4l2WZiWIe13BdY52H8utzSeZDE20ZV5TLcnGy7aXSWdcevXOezVzEapx1lbpwGrsnSKg5TB3CdD6H9bhyLPaLTy4/NhOGZrQr0slFOvGy9OnbDl3Sd7UviujxX89NzWtbZjPicq6ravq0y32KKGGpoGogA=) is more relevant.

Either way we're tail calling into `C.As2` instead of inlining it, which seems odd. I'll dig in and see what's up.
```asm
C.AsByte2(Single)
    L0000: vzeroupper
    L0003: mov rax, C.As2[[System.Byte, System.Private.CoreLib]](Single)
    L000d: jmp rax
```

**Comment by SingleAccretion** [comment]
@AndyAyersMS This is a pattern that I've noticed while using Sharplab, primarily because it comes up when doing [this](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9BrIAW2KGIAy2YO258BG6poDMTckiakGQmgG8aDL09KfvH6m8g+wBOAApyAEorIIBfGligA). I've always assumed it was some bug "in the toolchain".

**Comment by AndyAyersMS** [comment]
The inliner has a budget that it uses to prevent runaway inlining, and it is tripping (prematurely) in this case, as (generally speaking) `AggressiveInlining` methods should be exempt from budgeting.
```
Inlines into 06000003 C:AsByte2(float):ubyte
  [0 IL=0001 TR=000001 06000006] [FAILED: inline exceeds budget] C:As2(float):ubyte
```
That explains why the behavior changes as more checks are added -- at some point the extra IL pushes `As2` over budget.

Let me look into fixing this.
