### ISSUE TITLE
.NET Core Libraries on Linux and MAC

### ISSUE THREAD

**Issue by jnkarate** [dotnet/runtime#38100]
Is there a way to call .NET Core libraries from native C++ on MAC and Linux?  I know there is the C++/CLI on windows that allows you to do this, is there a way to do this on MAC and Linux?

**Comment by jeffschwMSFT** [comment]
@jnkarate the way that we recommend to do this is to call a static method which then does the more complex object construction.  In this case the static method could create an object (via the constructor of your choice) and return back function pointers, etc.  
Do you have an example that we can take a look at so that we can provide some additional thoughts?

cc @AaronRobinsonMSFT @vitek-karas

**Comment by jnkarate** [comment]
Thank you for the help I really appreciate it.
