### ISSUE TITLE
Documentation of PipeReader.AdvanceTo overloads is incomplete

### ISSUE THREAD

**Issue by lg2de** [dotnet/runtime#38277]
### Description
The documentation of the two overloads of [PipeReader.AdvanceTo](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.advanceto) is incomplete:
The difference in behavior of the overloads is not described in detail.

There are two overloads
1. AdvanceTo(SequencePosition)
2. AdvanceTo(SequencePosition, SequencePosition)

The difference in API is the second parameter named *examined*.
The current implementation of the overload (1) uses the parameter to call the overload (2) for both parameters. So, there is no difference between *consumed* and *examined* in this case. There no hint on the documentation for this behavior.

Even the difference is related to *examined* both overloads have the same sentence when mentioning *examined*.

The meaning/behavior of the states *processed*, *read* and *examined* (mentioned in summery of overload (2)) should be described in detail. (Having 3 states for 2 overloads is confusing too.)

### Suggestion
I'm not a native speaker. Anyway, here is my suggestion for "better" description. This is based on my current understanding of the behavior. Hope this is correct...

* Remarks for both overloads
  * The processing of the buffer distinguishes between consumed and examined. Consumed data can be released. The amount of examined data communicates to the pipeline when it should signal more data is available.
  * The memory for the consumed data will be released and no longer available. So, the buffer previously returned from ReadAsync(CancellationToken) must not be accessed after this call.
* Additional remarks for the overload (1)
  * The specified position marks the end of the buffer section which is consumed and examined. Remaining buffer is kept and immediately provided as unexamined at the next call to ReadAsync.
* Additional remarks for the overload (2)
  * The specified positions mark the first buffer section to be consumed and the second buffer section to be examined. The examined position must be greater or equal to the consumed position. The buffer not yet consumed is kept.
  * Specifying a buffer section to be not yet examined causes the next call to ReadAsync to return immediately the whole remaining buffer. If all data has been examined, the end position of current buffer should be specified.
* Summary of the overload (2)
  * Moves forward the pipeline's read cursor to after the consumed data, marking the data as processed and examined.

### Additional question
What is the use case to have a position *examined* which is different from *consumed* AND different from end of buffer?

### Other information
Before understanding the behavior described above I was using only overload (1). This caused the reader cycle to enter endless loop because the next call to ReadAsync returned immediately with completed ValueTask. Should this behavior be added to the behavior description too?

I already used the page feedback on https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.advanceto
Because I only received a *Thank you.* without option for you to ask me for clarification, I create this issue.

**Comment by halter73** [comment]
> I'm not a native speaker.

You definitely could have fooled me. Your writing is great.

> What is the use case to have a position examined which is different from consumed AND different from end of buffer?

This feature is useful for incremental parsers. For example, a JSON parser might get the following data from its first read:

```
{
  "a": "bcd",
  "e": "f
```

If it does, it could set the consumed position before the quotation mark in `"f` and set the examined position to the end of the read result. That way the parser won't be called again with a partial token.

If the consumed-only overload of AdvanceTo was called with a position before the quotation mark in `"f`, the next call to ReadAsync would immediately return the partial token `"f` in the likely case no new data has arrived.

```
"f
```

By using the two-parameter overload of AdvanceTo, the parser can ensure it won't get another ReadResult until one or more new bytes have arrived.

You could argue that examined should always implicitly be at the end of the ReadResult's buffer, but we decided against that in the initial API design because there can be cases where say the JSON number parsing component wants to advance the reader to the end of a number literal but leave the following property name unexamined to be picked up by the string literal parsing component.

> Before understanding the behavior described above I was using only overload (1). This caused the reader cycle to enter endless loop because the next call to ReadAsync returned immediately with completed ValueTask. Should this behavior be added to the behavior description too?

This is a common pitfall that's called out in https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines#gotchas, but it might be worth calling out in the API docs if there's a clear and concise enough way to do it.

@lg2de Do the edits made in https://github.com/dotnet/dotnet-api-docs/pull/4311 address your concerns about the PipeReader.AdvanceTo() docs? It was merged the same day you originally filed this issue. If not, you're more than welcome to submit a PR yourself to clarify things further.

**Comment by halter73** [comment]
@danmosemsft I think this issue was addressed by https://github.com/dotnet/dotnet-api-docs/pull/4311, so I'm closing this.
