### ISSUE TITLE
Currency symbol may be wrong after apply string format method

### ISSUE THREAD

**Issue by alepikhov** [dotnet/runtime#38308]
### Description
Code:
```
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("de");
string text = string.Format("{0:c}", 100);
```
Expected value for text variable: "100,00 €"
 but in .net 5 runtime we see "100,00 ¤".

.NETCore 5 -  text[7] | 164 '¤'
.NET 4.8	- text[7]  | 8364 '€'
.NETCore 3.1 -	text[7]  |  8364 '€'

### Configuration
5.0.100-preview.5.20279.10
OS Version:                10.0.18362 N/A Build 18362

### Regression?
For netcoreapp3.1 / .NET 4.8:
Code:
```
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("de");
string text = string.Format("{0:c}", 100);
```
Text  - "100,00 €"

**Comment by GrabYourPitchforks** [comment]
Repros on my box as well running Win10 19041. Also confirmed that setting the environment variable `DOTNET_SYSTEM_GLOBALIZATION_USENLS=1` fixes the regression. So it's definitely related to the NLS / ICU conversion.

**Comment by tarekgh** [comment]
This is by design. CLDR data having the international currency symbol associated to "de" culture. that makes sense because this is a parent culture to other cultures that have currency different than the euro. Windows data looks not updated to that for compatibility reason. 

```
de, German, ¤
de-AT, German (Austria), €
de-BE, German (Belgium), €
de-CH, German (Switzerland), CHF
de-DE, German (Germany), €
de-IT, German (Italy), €
de-LI, German (Liechtenstein), CHF
de-LU, German (Luxembourg), €
```

if you want to get back to Windows behavior you have the option to use the config switch to do that.

**Comment by tarekgh** [comment]
CC @@jefgen 
https://github.com/dotnet/runtime/issues/37743
