### ISSUE TITLE
How to run dotnet/runtime library test which actually use updated library

### ISSUE THREAD

**Issue by handlespeed** [dotnet/runtime#38383]
Hi, I am trying to change some dotnet/runtime code and found problem about build and test.

1. I change code in src\libraries\Microsoft.Extensions.Configuration.Binder\src\ConfigurationBinder.cs
2. run 'build.cmd -projects src/libraries/*/Microsoft.Extensions.Configuration.Binder.sln' to build both lib and test. Seems output of lib is in 'artifacts\bin\Microsoft.Extensions.Configuration.Binder\netstandard2.0-Debug', output of test code is in 'C:\runtime\artifacts\bin\Microsoft.Extensions.Configuration.Binder.Tests\net5.0-Debug'. (Correct me if wrong)
3. run 'build.cmd -projects 'src\libraries\Microsoft.Extensions.Configuration.Binder\tests\Microsoft.Extensions.Configuration.Binder.Tests.csproj' -test to run test. 
But seems in step3, test is not using lib which I updated. To verify that, I add 'throw exception' into all public methods of ConfigurationBinder class, test cases can still pass.

So could you please tell which folder the test finds to reference lib 'Microsoft.Extensions.Configuration.Binder.dll' during test running. From test.runtime.dep.json, I can see another dep lib 'TestUtilities.dll' but cannot see lib 'Microsoft.Extensions.Configuration.Binder'.
Which cmd can run test which is based on updated library 'Microsoft.Extensions.Configuration.Binder'?

Thanks !

**Comment by safern** [comment]
Hello @handlespeed -- the directories that you point out in step 2 are correct, however, given the way that we run our tests since we want to "override" the dotnet SDK inbox shared framework that we use to run to use the live assets we just built, we construct a "fake" shared framework in order to run the tests.

This shared framework will be found in `artifacts\bin\testhost\<buildconfig>\shared\Microsoft.NETCore.App\net5.0`. 

Could you validate that the "updated" assembly is there?

What I would recommend is trying the following, changing the implementation to throw, then run:

1. Build not incrementally the src project 
```
dotnet build --no-incremental src\libraries\Microsoft.Extensions.Configuration.Binder\src\
```

2. Run the tests:
```
dotnet build /t:test src\libraries\Microsoft.Extensions.Configuration.Binder\tests\
```

The commands you pasted above should work as expected, but I want you to give this way a try to see if we have something wrong going on when using the `build.cmd -projects` switch.

**Comment by ericstj** [comment]
Also, if it wasn't clear, you need to do at least one build up front to create the test shared framework.  Further info is here: https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries

**Comment by handlespeed** [comment]
@safern @ericstj Thanks for quick help.
I tried way as you suggested and found same result: test cannot use updated lib 'automatically', even use dotnet build command:
1. remove previous Microsoft.Extensions.Configuration.Binder.dll from artifacts\bin\testhost\net5.0-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\5.0.0.
2. run dotnet build --no-incremental src\libraries\Microsoft.Extensions.Configuration.Binder\src\, it successfully.
3. run dotnet build /t:test src\libraries\Microsoft.Extensions.Configuration.Binder\tests\, failed with: 

> An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
      package: 'Microsoft.NETCore.App', version: '5.0.0'
      path: 'runtimes/rid/lib/netcoreapp0.0/Microsoft.Extensions.Configuration.Binder.dll'

Then I tried to copy Microsoft.Extensions.Configuration.Binder.dll from artifacts\bin\Microsoft.Extensions.Configuration.Binder\netstandard2.0-Debug to artifacts\bin\testhost\net5.0-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\5.0.0 and run dotnet build /test, the test works as expected. Seems I have to copy output firstly?
BTW, I have not installed net 5 in my machine (installed netcore 3), I guess I was using 'inbox' sdk to build runtime code. To work with visual studio, I use build.md -vs to launch vs (based on wiki). Even that, the test project cannot be built from vs. That is why I use cmd to run test. Is that situation expected when not installed net 5 in machine ?
Thanks :)

**Comment by ViktorHofer** [comment]
Hey @handlespeed, can you try to just do a `dotnet test` on the Microsoft.Extensions.Configuration.Binder.Tests.csproj project on latest master? The source library is built together with the test project. Also what @ericstj said above, a root build is required first: `build.cmd clr+libs -rc Release`.

**Comment by handlespeed** [comment]
@ViktorHofer @ericstj @safern Sorry for delayed response and I will try latest master later. 
Can I have a subsequent question: 
say if I want to learn to contribute some code in dotnet/runtime (I try my best :)), so I update and rebuild one lib file from dotnet/runtime source code, can I replace existing dll which my personal project already referencing with the new built one? For example, "System.Private.CoreLib" dll. If yes, how to do that?
Sorry I cannot find related guidance from wiki. What I want is to change (or add) some corefx method and try to verify behavior or benchmark performance for updated corefx lib in my daily project. Is that right way to verify my corefx change from user perspective? Or, just use dotnet/runtime test project ? 
Thanks.

**Comment by ViktorHofer** [comment]
> Or, just use dotnet/runtime test project ?

That's probably the easiest. You could pick the updated System.Private.CoreLib but I'm not sure if you will run into troubles because the AssemblyVersion is different. My concern might not be valid as the loader might just be fine with the higher version.

If you want to do that, you would publish your application as self-contained and then overwrite the bits in the publish directory. Just be cautious when doing that as you will need to make sure that changes are compatible between the framework being used and the updated assemblies.

**Comment by handlespeed** [comment]
@ViktorHofer Thanks a lot, I will try that.

**Comment by handlespeed** [comment]
@ViktorHofer Your guidance works, I can use modified corelib dll in my personal project now!
Will try more later, thanks! 👍

**Comment by ViktorHofer** [comment]
Awesome, let's close this issue meanwhile. Feel free to reopen or reach out in a discussion if you have more questions.
