### ISSUE TITLE
Factory delegate causes copying of ExpirationTokens during GetOrCreate on Microsoft.Extensions.Caching.Memory.MemoryCache

### ISSUE THREAD

**Issue by Mariachi1231** [dotnet/runtime#38393]
Hi, I faced an unexpected particularity of usages of `GetOrCreate` which causes copying of `ExpirationTokens` (and absolute expiration) to a new item from any other entries that were retrieved in the factory delegate from the cache. 

This simple test represents my issue:

            List<string> log = new List<string>();

            MemoryCache msCache = new MemoryCache(new MemoryCacheOptions());

            string key1 = "key1";
            string key2 = "key2";

            CancellationTokenSource cts1 = new CancellationTokenSource();
            CancellationTokenSource cts2 = new CancellationTokenSource();

            msCache.Set(key1, new object(),
                new MemoryCacheEntryOptions()
                    .AddExpirationToken(new CancellationChangeToken(cts1.Token))
                    .RegisterPostEvictionCallback(
                        (object callbackKey, object callbackValue, EvictionReason reason, object state) =>
                        {
                            log.Add($"Meow from {callbackKey}");
                        }));

            msCache.GetOrCreate(key2,
                entry =>
                {
                    // For some reasons in factory delegate we are using some service which is doing TryGetValue on cache.
                    msCache.TryGetValue(key1, out _);

                    entry.SetOptions(new MemoryCacheEntryOptions()
                        .AddExpirationToken(new CancellationChangeToken(cts2.Token))
                        .RegisterPostEvictionCallback(
                        (object callbackKey, object callbackValue, EvictionReason reason, object state) =>
                        {
                            log.Add($"Meow from {callbackKey}");
                        }));

                    return new object();
                });

            cts1.Cancel();

            await Task.Delay(100);             

            log.ForEach(x => System.Diagnostics.Trace.WriteLine(x));

The output of the test is:
```
Meow from key1
Meow from key2
```

I see that this was caused by the call of `PropagateOptions` on the current scoped `CacheEntry`, if any call to `TryGetValue` occurred in the context of the `CacheEntry` scope, but as for me, it seems to be quite issues pron. Just curious, what is the reason for such behaviour and why idempotence of 'Get' convention is ignored? And how do you think, what is the best way to leverage this, I mean avoiding the duplicating/copying of expiration tokens in the delegate before disposing of the current `CacheEntry`?

**Comment by ericstj** [comment]
Source in question is here: 
https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L254-L256

I agree it's a little unusual that the act of calling `TryGetValue` modifies the cache entry being created.

Looks like this behavior has been around for a very long time.  Initially introduced here; https://github.com/aspnet/Caching/commit/4662317f5e78a64b04a702169d78b3a8f8094e4b.

@Tratcher do you think this behvior is intentional?  Could you shed some light on the original reasoning if you recall?

**Comment by Tratcher** [comment]
Yes, that's an intentional feature. The point is that if you're aggregating items from the cache to build other entries, you may want to expire the composite item when any of the original components expire.

I don't see any docs for this feature, nor a way to opt out of it. There is a whole batch of tests around it:
https://github.com/dotnet/runtime/blob/4233110dfc3336be7e79129d6d7f0a144065d51a/src/libraries/Microsoft.Extensions.Caching.Memory/tests/CacheEntryScopeExpirationTests.cs#L14

**Comment by maryamariyan** [comment]
Closing as it seems the behaviour is intentional. Feel free to reopen if you have additional questions.
