### ISSUE TITLE
What is the correct way to use Dictionary with FormUrlEncodedContent in .NET 5 without compiler warnings?

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#38494]
As part of updating some OAuth provider libraries to target .NET 5 using preview 6 (see https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/438), I've come across an issue with new nullable annotations I'm not sure of how to resolve correctly.

The `FormUrlEncodedContent` type has been updated to add nullable annotations (see #33268) and now the constructor takes an `IEnumerable<KeyValuePair<string?, string?>>`.

A common existing pattern to populate the values for an instance of `FormUrlEncodedContent` was to use a `Dictionary<string, string>`, but that now generates an `CS8620` warning.

However simply changing the dictionary to use `string?` then generates `CS8714` because the key cannot be null.

It's possible to fix the warning by casting the dictionary to `IEnumerable<KeyValuePair<string?, string?>>`, but then Visual Studio suggests the cast is redundant and can be removed.

The redundant cast and warnings can be eliminated by using a list or array of `KeyValuePair<string?, string?>`, but that's much more verbose.

Below is a simple program that demonstrates different approaches I took to try and fix the warning.

```csharp
using System.Collections.Generic;
using System.Net.Http;

#nullable enable

namespace FormUrlEncodedContentNullable
{
    class Program
    {
        static void Main()
        {
            var dictionary = new Dictionary<string, string>
            {
                ["foo"] = "bar"
            };

            _ = new FormUrlEncodedContent(dictionary); // CS8620
            _ = new FormUrlEncodedContent((IEnumerable<KeyValuePair<string?, string?>>)dictionary); // OK, but says cast is redundant

            var nullableValueDictionary = new Dictionary<string, string?>
            {
                ["foo"] = "bar"
            };

            _ = new FormUrlEncodedContent(nullableValueDictionary); // CS8620

            var nullableDictionary = new Dictionary<string?, string?> // CS8714
            {
                ["foo"] = "bar"
            };

            _ = new FormUrlEncodedContent(nullableDictionary);

            var listOfKvps = new List<KeyValuePair<string?, string?>>
            {
                new KeyValuePair<string?, string?>("foo", "bar")
            };

            _ = new FormUrlEncodedContent(listOfKvps); // OK, but verbose

            var arrayOfKvps = new[]
            {
                new KeyValuePair<string?, string?>("foo", "bar")
            };

            _ = new FormUrlEncodedContent(arrayOfKvps); // OK, but verbose
        }
    }
}
```

For now I've settled with the cast, but none of the above approaches seem correct to me.

What is the "correct" fix for this code pattern for .NET 5 when nullable is in use? It doesn't seem to be resolvable without suppressing warnings or making the code a lot more verbose that it was before.

**Comment by aik-jahoda** [comment]
I see no reason why support null for keys. Values are discussable too. Instead on null key the key should be an empty string.

With the assumption made above it should be:
```c#
var nullableDictionary = new Dictionary<string, string?>
{
     ["foo"] = "bar"
};

_ = new FormUrlEncodedContent(nullableDictionary);
```

Proposal for change in libraries: #40267

**Comment by karelz** [comment]
Fixed in #40267

**Comment by ManickaP** [comment]
Changing nullability of the existing `IEnumerable<KeyValuePair<string?, string?>>` API is not a correct solution. We internally handle nulls (in keys as well as in values) and encode them as `String.Empty`, see method [`Encode`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/FormUrlEncodedContent.cs#L37-L39). This has been allowed in previous versions on .NET Core, by changing it we might actually break someone.

Proper solution to this problem could be to introduce a new ctor overload accepting `Dictionary<string, string>`. But that requires API review and probably more discussion.

Moving to 6.0.

**Comment by martincostello** [comment]
So for .NET **5**, what is the official recommendation to fix compiler warnings/errors caused by these new nullability annotations for existing uses of `Dictionary` as the value to the constructor?

**Comment by ManickaP** [comment]
Use the cast for now. Once, the API is in, you would just remove it.
BTW, I just tried that and I'm not getting any warnings about redundant cast.

**Comment by dotMorten** [comment]
I'm finding I have to significantly rewrite my code because of this issue. I can't just add a `?` to my key for dictionary as that isn't allowed, so now have to use IEnumerable or List of `KeyValuePair<string?,string?>`.
I don't even get how a nullable key for `FormUrlEncodedContent` makes sense ?

**Comment by ManickaP** [comment]
@dotMorten you don't have to rewrite your code everywhere. You only need to use explicitly cast  when initializing the content, for instance:
```C#
new FormUrlEncodedContent((IEnumerable<KeyValuePair<string?, string?>>)dictionary);
```

My proposition is to add a new constructor accepting `Dictionary/IDictionary` instead of changing the current API.

**Comment by Kaelum** [comment]
@ManickaP changing a `null` key to `String.Empty` is breaking.  I don't see how you can't see that.  This was done for something else a long while back, where no one expected it.  History is repeating itself again.

**Comment by karelz** [comment]
@Kaelum as mentioned in the duplicate issue comment: https://github.com/dotnet/runtime/issues/54367#issuecomment-865268384 ... Let's stick to technical discussion, avoiding broad statements. Let's respect all opinions and each other. Let's accept the fact that mistakes and bugs in SW development do happen unintentionally and let's focus on how to address them.

**Comment by Kaelum** [comment]
>  Let's accept the fact that mistakes and bugs

@karelz finally the proper term has been used, bug.  Since this is a bug, and it affects all previously existing code, there should be a bug fix.  We should not be waiting an entire year for a bug fix.  The exact fix does not matter to us.  It only needs to take into account the fact that a `Dictionary<TKey, Tvalue>` object has never allowed the value of `TKey` to be null.

**Comment by stephentoub** [comment]
@karelz didn't say this is a bug.  The public API is in fact accurately reflecting what's allowed by the implementation, which is the primary purpose of nullable annotations in a case like this.  The problem here is that the lack of nullable variance in this particular situation means the compiler ends up warning even when everything is copasetic.  Regarding "changing a null key to String.Empty is breaking", I'm not sure what you mean about it being "breaking": the implementation has been like that for a very long time, no one is proposing changing it, and there's no need to change it for this issue... changing it would only make it more likely we break someone.

I don't remember a discussion about why https://github.com/dotnet/runtime/pull/40267 was reverted, but I do see this in the revert description in https://github.com/dotnet/runtime/pull/40711:
> By removing nullability from the key, we are removing ability to pass null values and have them encoded as empty strings (which has been allowed up until this change). This might actually break someone.

Removing `?` from the key doesn't affect run-time semantics: we can continue to be more lenient in the implementation (allowing/transforming nulls) than the nullable annotation dictates.  The presence or absence of a `?` here simply impacts what nullable warnings are given by the compiler if nullability checking is enabled.  Thus, we need to choose between whether we warn when someone goes off the beaten path and passes in a key typed as nullable or whether we warn for when someone passes in something with a non-nullable key.  I expect the latter is much more common, so if we're forced to choose one to prioritize, we should likely prioritize the latter and revert the revert.

**Comment by stephentoub** [comment]
It's also worth pointing out that a workaround here for any warning you get from passing a `Dictionary<string, string>` to `FormUrlEncodedContents`'s constructor is literally one character long:
```C#
new FormUrlEncodedContent(dictionary!)
```
vs
```C#
new FormUrlEncodedContent(dictionary)
```
