### ISSUE TITLE
Mono interpreter performance problems with BitOperations.LeadingZeroCount

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#38552]
Benchmark:
```
			for (int i = 0; i < 10000000; ++i) {
				BitOperations.LeadingZeroCount (1);
				BitOperations.LeadingZeroCount (1);
			}
```
Problems:
- LeadingZeroCount is marked as AggressiveInlining, but:
Inline start method BitOperations.LeadingZeroCount
Inline aborted method BitOperations.LeadingZeroCount
- The call       bool System.Runtime.Intrinsics.X86.Lzcnt::get_IsSupported() etc. calls
   are replaced with ldc.i4.0, but there is no constant propagation performed on them, so
  the interpreter still has to ran:
  ldc.i4.0
  brfalse ..
  a few times.
- ReadOnlySpan`1..ctor () is not inlined into  BitOperations.get_Log2DeBruijn ().

**Comment by BrzVlad** [comment]
This would require a lzcnt intrinsic in the interpreter to be fast. I'm not currently sure how relevant this would be. I think this is used only with `BigInteger`.

**Comment by tannergooding** [comment]
> I think this is used only with BigInteger.

We use LeadingZeroCount in a number of places, including Kestrel, Net.Http, Decimal, BigInteger, floating-point parsing/formatting, and Half.

Most of BitOperations exists because they represents "core functionality" that various algorithms across the BCL and greater .NET ecosystem used extensively enough to warrant centralizing them.

**Comment by tannergooding** [comment]
> The call bool System.Runtime.Intrinsics.X86.Lzcnt::get_IsSupported() etc. calls
are replaced with ldc.i4.0, but there is no constant propagation performed on them, so
the interpreter still has to ran:
ldc.i4.0
brfalse ..
a few times.

Is this a hard limitation in the interpreter? There are many code paths throughout the BCL, often in the most "perf-critical" areas, that expect the various `IsSupported` (or similar checks like `IsLittleEndian`, `Is64BitProcess`, `IntPtr.Size == 8`, etc) calls will be treated as constants and cause the dead code paths to be eliminated. They haven't been profiled or implemented to account for `IsSupported` always being checked and how that might impact the various code-paths.

**Comment by BrzVlad** [comment]
@tannergooding All of the problems specified in the original report have since been implemented. The remaining problem with this benchmark is that mono interpreter uses the fallback since it has no implementation for any platform intrinsics. I'm not yet sure what is the proper fix for this. Implementing intrinsics for every platform probably doesn't make sense since we can't use inline assembly code in the interpreter (for wasm).

I think we should implement some set of intrinsics (which one ??, just implement all x64 intrinsics ??) in a platform agnostic way. For example we could just use any supported compiler intrinsics (on gcc/clang `__builtin_clz` for lzcnt), or if there aren't any we can just implement the intrinsic with naive C code (which would be much faster anyway than doing the same thing in interpreted managed code and the C compiler backend will most likely optimize it anyway if supported on the target, like autovectorization). Also if I start to implement a simd intrinsic set, then I'm forced to add all of them ? Thousands of opcodes, most of which are not really that important. Maybe you could provide some guidance on how we can get something here.

**Comment by tannergooding** [comment]
> I think we should implement some set of intrinsics (which one ??, just implement all x64 intrinsics ??) in a platform agnostic way. For example we could just use any supported compiler intrinsics (on gcc/clang __builtin_clz for lzcnt), or if there aren't any we can just implement the intrinsic with naive C code (which would be much faster anyway than doing the same thing in interpreted managed code and the C compiler backend will most likely optimize it anyway if supported on the target, like autovectorization). Also if I start to implement a simd intrinsic set, then I'm forced to add all of them ? Thousands of opcodes, most of which are not really that important. Maybe you could provide some guidance on how we can get something here.

There are likely a subset of cross platform "intrinsics" that should be implemented everywhere. In particular, `wasm` has explicit opcodes for:
* `clz`- Leading Zero Count: `0x67` for i32 and `0x79` for i64
* `ctz` - Trailing Zero Count: `0x68` for i32 and `0x7A` for i64
* `popcnt` - Population Count: `0x69` for i32 and `0x7B` for i64
* `rotl` - Rotate Left: `0x77` for i32 and `0x89` for i64
* `rotr` - Rotate Right: `0x78` for i32 and `0x8A` for i64

There are also some math intrinsics I'd expect are already implemented:
* `abs`
* `ceil`
* `floor`
* `trunc`
* `nearest`
* `sqrt`
* `copysign`
* `max` and `min` -- although these may or may not be compatible, depending on which IEEE min/max they are

Where we support these, I'd expect it to be for the publicly exposed xplat functionality, such as in `System.Numerics.BitOperations` or `System.Math`/`System.MathF` and not for anything under `System.Runtime.Intrinsics` which is very strictly platform/architecture dependent and where `WASM` is its own platform/architecture. That being said, WASM is looking at adding their own SIMD intrinsics: <https://github.com/WebAssembly/simd/blob/main/proposals/simd/SIMD.md>. When that is eventually finalized (its getting closer and is currently in preview, but is largely supported by the various WASM interpreters today), I'd expect we look at exposing `System.Runtime.Intrinsics.Wasm` and for the various code paths to be updated to use this acceleration where possible. Assuming the interpreter supports the dead code elimination, this will eventually provide a nice performance boost for our users in the same "core paths" that they already see the benefits.
