### ISSUE TITLE
`Task.WhenAny` given an empty set.

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#38592]
Currently the following code

```c#
System.Threading.Tasks.Task.WhenAny(new System.Collections.Generic.HashSet<System.Threading.Tasks.Task>())
```

 produces:

> The tasks argument contains no tasks. (Parameter 'tasks')
--

I would suggest this return an immediately completed Task instead.

The cost of the exception is high and I don't see the value in throwing then a static completed `Task` could be used.

**Comment by stephentoub** [comment]
Why are you calling it with an empty set?

WhenAny returns a `Task<Task>`, or a `Task<Task<T>>`.  For this to not throw, it would need to return a `Task<Task>` with a task it manufactures out of thin air, e.g. Task.CompletedTask as you suggest.  And such a task wasn't in the input set.  That's why it throws: there's nothing this can return that logically makes sense given the inputs.

**Comment by juliusfriedman** [comment]
Well then one must check if they have something like a bag or list of tasks that is empty before calling that method then I suppose.

I didn't intentionally do so, it manifested out of the fact I had tested setting a number to 0 meaning unlimited and I ended up created 0 tasks and then calling that method (with what would usually be an populated set of at least 1 `Task`)

The scenario is probably valid in other cases though and I feel like perhaps a `TryWait` might be a better solution than throwing.

**Comment by stephentoub** [comment]
> Well then one must check if they have something like a bag or list of tasks that is empty before calling that method then I suppose.

If it's possible it's empty, yes, it's up to the caller.

**Comment by juliusfriedman** [comment]
Since this is closed I suppose a proposal for `TryWhenAny` would also not fly. Thank you for your time.
