### ISSUE TITLE
Why is Hashmap in Java much faster than Dictionary in .NET?

### ISSUE THREAD

**Issue by Dogwei** [dotnet/runtime#38660]
### Description

10 times faster on 1000 elements.

 5 times faster on 1000000 elements.

### Configuration

.NET Core 3.1 on release

Java 12 on nodebug

### Java

```Java

	public static void main(String[] args) {

		Random random = random = new Random();

		while (true) {

			int count = 1000000;
			
            int times = 10;

			int existsStart = random.nextInt(count);
			int notExistsStart = existsStart + count;

			String[] exists = getStrings(existsStart, existsStart + count);
			String[] notExists = getStrings(notExistsStart, notExistsStart + count);
			HashMap<String, String> map = new HashMap();

			long begin = System.currentTimeMillis();

			for (int i = 0; i < exists.length; i++) {
				String item = exists[i];
				map.put(item, item);
			}

			System.out.println("add:" + (System.currentTimeMillis() - begin));

			begin = System.currentTimeMillis();

			
            for (int t = 0; t < times; t++){
				for (int i = 0; i < exists.length; i++) {
					String item = exists[i];
					map.containsKey(item);
				}
			}

			System.out.println("exists:" + (System.currentTimeMillis() - begin));

			begin = System.currentTimeMillis();

            for (int t = 0; t < times; t++){
				for (int i = 0; i < notExists.length; i++) {
					String item = notExists[i];
					map.containsKey(item);
				}
			}

			System.out.println("not exists:" + (System.currentTimeMillis() - begin));

			begin = System.currentTimeMillis();

			for (int i = 0; i < exists.length; i++) {
				String item = exists[i];
				map.remove(item);
			}

			System.out.println("remove:" + (System.currentTimeMillis() - begin));

			System.out.println("=====================end======================");
		}
	}

	public static String[] getStrings(int start, int end) {
		int length = end - start;

		String[] ret = new String[length];

		for (int i = 0; i < length; i++) {
			ret[i] = "0x" + Integer.toString(start + i, 16);
		}

		return ret;
	}
```
### C#
```C#
        var random = new Random();



        while (true)
        {
            int count = 1000000;

            int times = 10;

            var existsStart = random.Next(count);
            var notExistsStart = existsStart + count;

            var exists = Enumerable.Range(existsStart, existsStart + count).Select(i => $"0x{Convert.ToString(i, 16)}").ToArray();
            var notExists = Enumerable.Range(notExistsStart, notExistsStart + count).Select(i => $"0x{Convert.ToString(i, 16)}").ToArray();

            var dic = new Dictionary<string, object>();

            var stopwatch = Stopwatch.StartNew();

            for (int i = 0; i < exists.Length; i++)
            {
                var item = exists[i];
                dic.Add(item, item);
            }

            Console.WriteLine("add:" + stopwatch.ElapsedMilliseconds);

            stopwatch = Stopwatch.StartNew();

            for (int t = 0; t < times; t++)
            {
                for (int i = 0; i < exists.Length; i++)
                {
                    var item = exists[i];
                    dic.ContainsKey(item);
                }
            }

            Console.WriteLine("exists:" + stopwatch.ElapsedMilliseconds);

            stopwatch = Stopwatch.StartNew();

            for (int t = 0; t < times; t++)
            {
                for (int i = 0; i < notExists.Length; i++)
                {
                    var item = notExists[i];
                    dic.ContainsKey(item);
                }
            }

            Console.WriteLine("not exists:" + stopwatch.ElapsedMilliseconds);

            stopwatch = Stopwatch.StartNew();

            for (int i = 0; i < exists.Length; i++)
            {
                var item = exists[i];
                dic.Remove(item);
            }

            Console.WriteLine("remove:" + stopwatch.ElapsedMilliseconds);

            Console.WriteLine("=====================end======================");
        }
```

### Analysis

Is it possible that Java use more extreme tiered compilation optimization?

**Comment by SingleAccretion** [comment]
Some thoughts:
1. Would it be better to move the array init logic outside the loop? As is, the bechmark is very noisy because of constant allocations. Java can also do objects-on-stack, but I doubt this is happening there.
2. `stopwatch.Stop` should probably be called before `Console.WriteLine`.

**Comment by eiriktsarpalis** [comment]
Related: https://github.com/dotnet/runtime/pull/36252. Would be interesting to try the same benchmark with non-string keys.

**Comment by SingleAccretion** [comment]
The benchmark (.NET version) is very sensitive to some random stuff (alignment, our old friend?). On different runs I've got these average results for the metrics (they are fairly consistent within each run). Note that I moved the the array initialization outside the loop.
| Run | "Exists" | "Not exists" |
|------|---------|--------------|
| 1      | 1000    | 1800            |
| 2      | 500      | 1350            |
| 3      | 750      | 1600            |

**Comment by benaadams** [comment]
You will also want to have the timing loops in a called method; and then call it at least 30 times for tier1 compilation to kick it (the Jit won't currently replace the asm in a running method)

**Comment by BreyerW** [comment]
@Dogwei  just for the record try SlimDictionary? It contains extra optimizations with breaking changes. It lies in Microsoft.Experimental.Collections package

**Comment by MarkPflug** [comment]
My understanding is that Java caches hashcodes for strings. I'm not sure if this is done on creation, or lazily, but either way that could easily account for the differences in these numbers. Reinitializing the exists/nonExists arrays with new strings between the timed sections hurts performance for the Java version. This could indicate that caching is done lazily, since it would have be re-hashed during lookup, or it could be that reference equality can no longer be used as an equality optimization.

When testing using int/Integer keys instead, the performance of the .NET implementation is comparable/marginally better. Though, .NET does appear to be generally slower (~2x) when looking up non-existent keys. 

Seeing a lot of noise in the Java numbers, and not being even remotely competent with Java I don't know how to account for/fix that.

**Comment by SingleAccretion** [comment]
So, I profiled the thing again (with a big `existsStart = count` and `count = 1000000`) (with standard VS CPU profiler), but this time focusing on the `FindEntry` only (95% of inclusive time) and without any allocations in the loop to remove that variable. Here's the result, extracted with the excellent PerfView tool:
````C#
  9,3K|  int hashCode = comparer.GetHashCode(key) & 0x7FFFFFFF;
         // Value in _buckets is 1-based
 17,0K|  i = buckets[hashCode % buckets.Length] - 1;
         do
         {
             // Should be a while loop https://github.com/dotnet/coreclr/issues/15476
             // Test in if to drop range check for following array access
  8,9K|      if ((uint)i >= (uint)entries.Length || (entries[i].hashCode == hashCode && comparer.Equals(entries[i].key, key)))
             {
                 break;
             }
         
 34,2K|      i = entries[i].next;
535,0 |      if (collisionCount >= entries.Length)
             {
                 // The chain of entries forms a loop; which means a concurrent update has happened.
                 // Break out of the loop and throw, rather than looping forever.
                 ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
             }
215,0 |      collisionCount++;
         } while (true);
````
Please note that this is not the current code (which uses a faster modulo and is in general more optimized), the purpose of this is to show that the fact that Java does hash code caching is a factor but does cannot explain 5x differences and that we should really be testing against .NET 5.

**Comment by danmosemsft** [comment]
We are not planning to go back and modify the implementation of Dictionary in 3.1, unless there is some egregious high impact problem. Any work here would be in 5.0 or later. As @SingleAccretion points out, the implementation was changed significantly in 5.0 as well.

@Dogwei (or @SingleAccretion ) to make progress here, I think we need measurements comparing 5.0 to Java, and with some tweaks as suggested by @SingleAccretion to the measurements.

I am going to set this as Milestone=Future since it is not clear that there is anything here that would require a fix before shipping 5.0.

**Comment by MarkPflug** [comment]
I commented previously that I wondered if part of this performance difference was due to Java caching the hashcode for strings. I deleted that comment, because it had other results that I realized were bogus and misleading. I'm honestly not even sure if Java does cache hashcodes, but I felt like I "knew" that once.

Some observations about the tests cases as provided:
1) As already noted the use of random was causing inconsistent results.
2) The access of pattern of adding strings, and then checking them *in the same order they were added* is probably unrealistic. This would be a more cache-friendly access pattern than a more realistic scenario of accessing them in a random order. Obviously, both java and C# tests would benefit from this. I tested randomizing the order in Java and saw some significant slow down. I didn't try in C#, though I'd expect it to also be slower..
3) The contains/existing checks are done using the same (by reference) string as the insert. Is that realistic? Maybe, maybe not.

First, concerning the hashcode caching, I modified the C# test to use a "HashedString" struct:
```    
readonly struct HashedString : IEquatable<HashedString>
{
    public HashedString(string str)
    {
        this.str = str;
        this.hash = str.GetHashCode();
    }

    readonly int hash;
    readonly string str;

    public override string ToString()
    {
        return str;
    }

    public override int GetHashCode()
    {
        return hash;
    }

    public override bool Equals(object obj)
    {
        return obj is HashedString s && this.Equals(s);
    }

    public bool Equals(HashedString other)
    {
        return string.Equals(this.str, other.str);
    }
}
```
On netcore 3.1 (3.1.6 as reported by `Environment.Version`)
Using this `HashedString` struct as the dictionary key, the test case ran in about 2/3 the time as using `string` when the string length was 16 characters. For shorter string lengths, using `string` keys was faster than using HashedString, presumably this is because the dictionary entries end up requiring 2x the memory which ends up being more expensive than the hash calculation when strings are short short strings, not sure.

Now, on net5.0 (preview7) things get... interesting.
The `HashedString` test case behaves almost exactly the same as it did on 3.1.
However, when running using `string` keys things become concerning. **The first iteration takes almost 10x the time that subsequent iterations do**. Would this much extra time be caused by tiered JIT? After the first, slow iteration the performance is *marginally* better than on 3.1. It would take a long time to pay back the 10x costs of the first iteration (honestly, feels like a bug).

Things turn out to be interesting in Java land too:
Indeed, running the test scenario with keys: "0x1000000".."0x1999999" (str length 9) is impressively fast. ~1/3 the time for .NET using the same string keys.
However, if the string is longer ("0x10000001000000".."0x19999991999999") (Str length 16), then the Java test takes ~10x longer,  suddenly it doesn't look that impressive.

What's weird, is the nature of the string greatly affects the performance (all 16 length):
"0x1234567891000000".."0x1234567891999999" (common prefix) is fast. (~1x)
"0x1000000123456789".."0x1999999123456789" (common suffix) is slower. (~3x)
"0x10000001000000".."0x19999991999999" (no commonality) is slowest. (~10x)

I can only speculate at an explanation. Perhaps Java doesn't cache hashcodes after all. Perhaps it only hashes the first part of the string, then when collisions occur in the hashtable, it uses a search tree within the bucket (this can be seen in the HashSet source code) instead of a linear linked list. Again, the these test cases might show interesting performance behavior, but are unrealistic so probably not of much value. The Java implementation is surely optimized for realistic scenarios, and seems to use bucket tree search to protect against malicious input causing pathological performance scenarios that would result from a linear bucket (without hash randomization).

The final scenario I looked at was comparing Java UUID to .NET Guid keys. This is a scenario that I (unfortunately) care about. Here, .NET beats Java pretty handily, by about 25%.

Anyway, I'm not sure that any of this is of much use as far as analysis goes, but I thought some of these observations might be of some interest.

Gist:
https://gist.github.com/MarkPflug/246e71ef19a6a1de64a565fe61215a5e

**Comment by danmosemsft** [comment]
You can eliminate the issue of hashcodes by using `int` as the keys -- the hash of an `int` is itself.  Also, there are [several ways ](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/compilation) you can switch off tiered JITting  (we generally measure with Benchmark.NET which takes care of this and many other things)

> The final scenario I looked at was comparing Java UUID to .NET Guid keys. This is a scenario that I (unfortunately) care about. Here, .NET beats Java pretty handily, by about 25%.

Concrete scenarios are great. Measuring collections like Dictionary abstractly is hard, because there are so many different axes to vary, from object size, collisions, reads vs writes, size vs capacity, etc. It is unlikely that Java has some magic sauce that we could simply apply without regressing something others care about. We have made improvements to Dictionary every release, though, and I'm sure there's more to be made. Is there a specific scenario you have where you're finding .NET perf lacking? That might help focus a discussion.

**Comment by MarkPflug** [comment]
> You can eliminate the issue of hashcodes by using int as the keys -- the hash of an int is itself.

I had done just that in a my previous, deleted comment. The problem was that I did it in the super-naive way: sequential ints, which provide a perfect hash function (no collisions) that accesses the buckets in sequential order. The perfect performance scenario, and horribly unrealistic (which is why I deleted it).

> Is there a specific scenario you have where you're finding .NET perf lacking?

Me? No. 

I was only intrigued by this issue because I found it hard to believe that Java was so much faster than .NET in this scenario. I still find it hard to believe. I think Java has chosen to optimize string hashing/hashset to get better performance in a very specific scenario, at the cost of other scenarios where .NET wins.

The only thing that concerns me is the the 10x cost of the first test iteration when running on .net 5 (tiered JIT?). That is *really concerning*, and should probably be reported as a separate issue.

**Comment by danmosemsft** [comment]
Can you make a minimal repro of the 10x case?

**Comment by MarkPflug** [comment]
Sure. This is fairly minimal:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

class Test
{
    const int count = 1000000;
    const int times = 10;

    public static void Main()
    {
        for (int i = 0; i < 10; i++)
        {
            var sw = Stopwatch.StartNew();
            var dic = new Dictionary<string, bool>(count * 3 / 2);
            TestDict(dic, i => "0x" + (count + i));
            Console.WriteLine(sw.Elapsed.ToString());
        }
    }

    static void TestDict<T>(IDictionary<T, bool> dic, Func<int, T> src)
    {
        var exists = Enumerable.Range(0, count).Select(i => src(i)).ToArray();
        var notExists = Enumerable.Range(count, count).Select(i => src(i)).ToArray();

        for (int i = 0; i < exists.Length; i++)
        {
            var item = exists[i];
            dic.Add(item, true);
        }

        for (int t = 0; t < times; t++)
        {
            for (int i = 0; i < exists.Length; i++)
            {
                var item = exists[i];
                dic.ContainsKey(item);
            }
        }
    }
}
```

Run this on net5 and the first run will be super-duper slow (~5.6sec), the second iteration will be normal ~.9sec). This is with TieredCompilation = false in the csproj. Is there a way to verify that this property is having the desired effect? I don't see any assembly metadata indicating to disable it, which is how I would expect this to be signaled.

Run on netcore3.1 and all runs are roughly the same (1.1sec - .93sec).

Happy to provide any other info that's necessary.

**Comment by jkotas** [comment]
Thanks for reporting the performance regression in the first run. It is a real perf bug. I have opened https://github.com/dotnet/runtime/issues/40298 to track it.

**Comment by MarkPflug** [comment]
> What's weird, is the nature of the string greatly affects the performance (all 16 length):
"0xZZZZZZZ1000000".."0xZZZZZZZ1999999" (common prefix) is fast. (~1x)
"0x1000000ZZZZZZZ".."0x1999999ZZZZZZZ" (common suffix) is slower. (~3x)
"0x10000001000000".."0x19999991999999" (no commonality) is slowest. (~10x)

Turns out, this isn't that weird. The way the java string hash algorithm works causes "sequential strings" with long common prefixes to produce sequential hash codes, and so produces a very cache-friendly access pattern. The .NET implementation does not have this characteristic, and produces hash codes that produce a random pattern, which explains the significant difference of performance between the two when using sequentially allocated strings.

If I switch to using UUID/Guid.toString(), the performance is more comparable, with .NET being about 2x that of Java. But... that can be explained by Java's hash code caching, which I confirmed does exist. Wrapping the Guid.ToString in a `HashedString` struct and the .NET dictionary performs almost exactly the same as Java's HashSet.

So, all of this is to say, I don't think there is a performance issue here. With the exception of the first-run issue that jkotas created.

**Comment by benaadams** [comment]
>  The .NET implementation does not have this characteristic, and produces hash codes that produce a random pattern

The .NET string hashing in dictionaries is strengthened against [hash collision attacks](https://en.wikipedia.org/wiki/Collision_attack); which is why it doesn't produce a sequential pattern of hashcodes

**Comment by benaadams** [comment]
>  The .NET implementation does not have this characteristic, and produces hash codes that produce a random pattern

The .NET string hashing in dictionaries is strengthened against [denial of service hash collision attacks](https://arstechnica.com/information-technology/2011/12/huge-portions-of-web-vulnerable-to-hashing-denial-of-service-attack/); which is why it doesn't produce a sequential pattern of hashcodes

**Comment by Dogwei** [comment]
[IKVM](https://www.nuget.org/packages/IKVM/) is a library that transplants the JAVA core library to .NET in OpCodes form. Through it, I tested the performance gap between Dictionary and HashMap on the .NET platform. The result is that HashMap is five times faster than Dictionary, almost the same as the performance on the Java VM (Consider the performance loss caused by transplantation). This may be able to show that the performance gap is mainly reflected in the algorithm difference between Dictionary and HashMap.


It’s been too long and I can’t provide the code.

**Comment by eiriktsarpalis** [comment]
>  The result is that HashMap is five times faster than Dictionary

How long ago was that? As far as I know IKVM is no longer being maintained. I tried [replicating the results](https://gist.github.com/eiriktsarpalis/ec3b06bb5267c67e0ef0b61dd159f03c) and in my benchmarks dictionary is 2-3x faster.

|     Method |    Size |             Mean |           Error |         StdDev |           Median |
|----------- |-------- |-----------------:|----------------:|---------------:|-----------------:|
| Dictionary |      10 |         932.2 ns |        41.94 ns |       116.9 ns |         900.0 ns |
|    HashMap |      10 |       2,654.0 ns |       280.75 ns |       768.5 ns |       2,400.0 ns |
| Dictionary |    1000 |      27,310.3 ns |       898.53 ns |     2,459.7 ns |      26,100.0 ns |
|    HashMap |    1000 |      43,250.0 ns |       861.90 ns |     1,341.9 ns |      43,050.0 ns |
| Dictionary | 1000000 |  44,508,088.5 ns |   722,507.27 ns |   603,326.3 ns |  44,422,250.0 ns |
|    HashMap | 1000000 | 102,567,602.1 ns | 1,934,881.60 ns | 3,773,838.0 ns | 101,342,000.0 ns |

**Comment by eiriktsarpalis** [comment]
I feel that we can probably clause this issue. Feel free to reopen if there are any actionable points I might have missed.
