### ISSUE TITLE
Microsoft.Extensions.DependencyInjection & .NET FWK

### ISSUE THREAD

**Issue by jnanneng** [dotnet/runtime#38666]
### Description

The Microsoft.Extensions.DependencyInjection nuget package contains a target lib for the .NET framework 4.6.1.  This package however has a required dependency on Microsoft.Extensions.DependencyInjection.Abstractions which only provides a target for .NET Standard (2.0).

This is problematic as noted here:  https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET, and even here:  https://github.com/dotnet/extensions/issues/434

I'd like to understand why the later bug was not addressed:

1) it's not always possible to readily move a codebase to a later framework
2) referencing .net standard 2.0 from 4.6.2, 4.6.1, etc... appears to be super problematic
3) Why do we produce a nuget package that targets .net framework 4.6.1, but it's direct dependency (appears to be from the same team / [product line / etc... ]) does not also mirror such targets?

**Comment by ericstj** [comment]
> Why do we produce a nuget package that targets .net framework 4.6.1, but it's direct dependency (appears to be from the same team / [product line / etc... ]) does not also mirror such targets?

Mirroring targetframeworks in general is an anti-pattern.  Packages are a layer of abstraction that shouldn't leak into consumption / dependencies.  In this case I believe DI cross-targeted because it wanted to have a feature on .NETFramework that it couldn't support everywhere.  Here that's Ref.Emit-Save.  See https://github.com/dotnet/runtime/blob/1621d7c7d508e779f159009851ea2916cb95d7dc/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs#L107-L122

> referencing .net standard 2.0 from 4.6.2, 4.6.1, etc... appears to be super problematic

Agreed.  This is why @joperezr added desktop TFMs to most of the packages produced from dotnet/corefx and now dotnet/runtime.  We just haven't given this treatment to extensions yet, but should.

@joperezr would you want to consider this while you're porting all the servicing changes to 5.0?

**Comment by joperezr** [comment]
> @joperezr would you want to consider this while you're porting all the servicing changes to 5.0?

I don't really have a choice since the tests that I'll add as part of this port will fail for this library if I don't 😜 but I'm happy to take care of it too 😄

**Comment by joperezr** [comment]
Closing as this one is done now.
