### ISSUE TITLE
Extra copy of struct before return

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#38743]
### Description

Looking [Guid.NewGuid()](https://github.com/dotnet/runtime/blob/8b50c519a8deaffed3f221874ecc39bc930a5573/src/libraries/System.Private.CoreLib/src/System/Guid.Unix.cs) implementation I prepared a simple test on [CSharpLab site](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQ64GYAEAHMAJ2AEswAbHCYQgVwGNgcBxWkgE1TRx5wG90vHIKG9sOOEgBsOWgDsIYAGYBTCQBYWK4ACUwc9gHsoAIQCewFRAAUAIwsqAVDlu0lqwgBocJOU3IqcgDmwAAWAJQiovxR0bxKhoQ4dg4+OAC8OAAMANxpADw4AcFhALRIeSQA1FWR3HFCAvUN0Y52bh44VT7hGT45sQ0AvoO8IxgTDXiEJABuYJY+fjgA+mB5PAD0mzgAIoY4coZMhIFgUGp2vkRmVCozFCQAXgskhnJ1UzPzixChiUwVrY8ts9gcjiczhdkrZroRbhB7mRyM9Xu9PnFpnMFmo/gDVvQQTt9odjjhTnJzpdYZT4XcHiiXqR0aMeFifmp7IsVuwNqCSRDyVDqXCEUjHky3h9WfhvjiXKkVio+cTwWSKVSYaL6cjUczpc1ROz5Vy1CslCqwaTIZToVdaWKGXqpRjosbFqbVkFLQL1cKtQ6dRK0QavtiPYrQj61TbNfabkHGSHXUa5RHuSRo9ahbaRYHEU7JSzDUJ3ZzFQArLOCjV2mkJgu6ouhzFp8vcgDW1b9uYDDfFSf1dRlOFBABVQiQIDgAO4kciUeineVgQ4qGfk/RGKA4IJsdguSAqA/vHBhNShYDAPAQEDbGcPgB0JG0SkfiSCm0ISnoX5/6iQBAEEfYAAA9gBlcRJBkeRFFUFh9yQHAADl11YDhrBTRoR14dDOF3AYSziZhtD0AxjHMSwbBSSxHHCAAyIJvAgZ4VEMJRrDwpBwnCQjhCI6J6HeahZDxYgcAANXuFj3gAWUgDs+iyUCADEsnUviWh4ISFCYWgxKYMjtzwqTCBkuQlNA9R1NyQQcO04SmE9ABhchDHoDsAGUVAARwACRIABBAwdCse5ZmPeSIEUzJlOc2yBNEHSRJctyPO8/ygpCsLCAi9gJIoWg1Fi0CAA4Ev4rSth2WTDHYEglFuWFgGnXx6voV5gjPUI1GAMw8DUdjurUZgAFUAEldjsxKhHkegeo8497JiGa4lBUgLhWSc1gMFYIrMqVlqEIJHxWeg+msAzwmsawTrOnB6JwAA/UzzKijtehgHAjOMEzpJdTSqt4UF6DSjsVkRHytpIHb2BWU4Czyo7eDug9MholRrtu06D0ep7XPcrzfIC4L2FCxHIoUz6cAJ9LiaysmcrygryCK3jlvGSqqrgAB2AiZU5nhxiAA=)
It seems the method does extra struct copy before return (`g` variable is defined on stack and could be returned as is).

I do not know whether this is an omission in the existing optimization, or a new optimization сould be added.

category:cq
theme:structs
skill-level:intermediate
cost:medium
impact:small

**Comment by GrabYourPitchforks** [comment]
I can't speak for the JIT team, but it's possible that writing directly into the return value's storage address could be an incorrect optimization. Consider:

```cs
public class MyClass
{
    public Guid MyGuid;
}

MyClass o = new MyClass();
o.MyGuid = SomeMethod();

Guid SomeMethod()
{
    // do something
    if (rnd()) { return g; }
    else { throw new Exception(); }
}
```

If any portion of _SomeMethod_ has a side effect that may result in the method throwing an exception or otherwise not returning, then the write to _MyClass.SomeGuid_ should never have taken place at all, as the write is performed by SomeMethod's caller, not by SomeMethod itself.

**Comment by JulieLeeMSFT** [comment]
CC @CarolEidt @sandreenko PTAL

**Comment by CarolEidt** [comment]
There are at least a few factors at play here:
- First, taking the address of the local variable `g` and passing it to another method will cause every write to `g`'s fields to go to the stack because it's address-exposed. Declaring a separate variable to hold the random bytes, and then assigning it field-by-field to `g` might improve things a bit.
- The JIT doesn't currently have support for shuffling and assembling fields of structs in a single register, so even if the first issue is addressed, there will be one, rather than two, stores to the return local.
- The JIT doesn't do any forwarding optimizations, so in any case I believe that it will always store to the return local in the epilog.

Perhaps @AndyAyersMS has additional thoughts.

**Comment by iSazonov** [comment]
> in any case I believe that it will always store to the return local in the epilog.

It could be allocated on stack before the method call like an optimization for stackalloc.
Given that the size of structures (and tuples?) can be relatively large there can be a good performance gain.

**Comment by AndyAyersMS** [comment]
The .NET analogs of C++'s RVO and NRVO are indeed useful -- but not something the jit is able to do at present. Reverse struct copy-prop (#8887) will eventually allow the jit to construct some structs directly into the hidden return buffer.

However, as @GrabYourPitchforks notes, on the `NewGuid` example, this optimization would likely be blocked by the call to `GetRandomBytes`, since the jit would have to assume that method could throw an exception before writing all of its result.

**Comment by jakobbotsch** [comment]
As discussed above, the cases we can do this would be very limited. The return buffer can also alias other arguments in the managed calling convention which makes this even harder. I don't think there is much we would be able to do because of that. Will close this.

**Comment by jakobbotsch** [comment]
There are cases we would still be able to do this, even in the face of there being potential aliasing/overlap between the return buffer and arguments. Reverse copy prop would probably need to handle this in some form anyway, so let's reopen this.

**Comment by iSazonov** [comment]
I can explain my perplexity about this issue.
Structures are good for high performance code and suddenly copying happens. Immediately the question arises whether it is so necessary.
Perhaps this is not the right analogy but it reminds us of async methods that execute synchronously if possible, and moreover try to return value results to avoid allocation.
So my expectation for structures is similar that the compiler tries to make the code as efficient as possible.
Another analogy is related to static anonymous functions. The compiler does this optimization if possible, but we can specify `static` explicitly to avoid regression. Perhaps something similar could be possible for structures since there are quite a few shadow copy traps there.

**Comment by jakobbotsch** [comment]
@iSazonov It's not just about what is possible but also about what is going to be realistic in the framework of the JIT. The fact that the return buffer is allowed to alias global memory puts the JIT on territory that it generally handles very conservatively today. More powerful alias analysis is quite costly and I don't know how much we could get away with there.

In your original example it is very unlikely we would be able to do anything without making the JIT's alias analysis more powerful. There are two main reasons: 1) Unlike C++, `return g` does not mean we can make `g` the return buffer function-wide for the reasons described above, e.g. `GetRandomBytes` call could partially write it before throwing an exception. 2) Exposing the address of `g` to `GetRandomBytes` makes the JIT believe `g` can alias any other global memory. Removing the copy in this case requires us to optimize something like `g = <arbitrary expression involving global memory>; *retbuf = g` into `*retbuf = <arbitrary expression involving global memory>`. That's hard in the framework of the JIT when we know `retbuf` is allowed to alias.

If the expression does not involve global memory then it becomes easier; so those are the cases where I think we would more easily be able to do something, and why I reopened it. E.g. it may be common that you just have `g = <constant assigned to each field>; *retbuf = g` which could be optimized.

**Comment by benaadams** [comment]
Some methods don't have any throws and are self contained; could the Jit write directly to the output buffer in these cases?

**Comment by benaadams** [comment]
Related issue https://github.com/dotnet/runtime/issues/12219
