### ISSUE TITLE
Enum should use the supplied IFormatProvider

### ISSUE THREAD

**Issue by HobbsCode** [dotnet/runtime#38779]
Much of Enum's implementation of IConvertible disregards the supplied IFormatProvider, and instead uses CurrentCulture. Is this intentional? Example:

```
ulong IConvertible.ToUInt64(IFormatProvider? provider)
{
     return Convert.ToUInt64(GetValue(), CultureInfo.CurrentCulture);
}
```

**Comment by GrabYourPitchforks** [comment]
`Enum` is backed by numeric types (byte, int, long, etc.). Conversion from one numeric type to another is always culture-agnostic because there's no localization that ever has to be performed.

Honestly the implementation should probably be passing _null_ rather than `CultureInfo.CurrentCulture` as an optimization.

**Comment by HobbsCode** [comment]
If using CurrentCulture doesn't result in any correctness problem, then I'm going to close the issue. Thanks for the quick response.
