### ISSUE TITLE
[Proposal] Stream.IsAsynchronous property

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#38797]
## Background and Motivation
When I have high-level API to work with streams such as string decoding or deserializing complex structures it's good to know whether the stream natively supports asynchronous methods or not. This knowledge gives the possibility to write more efficient code without async-to-sync transitions caused by `WriteAsync` or `ReadAsync` default implementations.

## Proposed API

```csharp
public abstract class Stream
{
  public virtual bool IsAsynchronous { get; }
}
```

The default value is **false**.

## Usage Examples

```csharp
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

ValueTask<TResult> Deserialize<TResult>(Stream input, JsonSerializerOptions options, CancellationToken token = default)
{
  if (input.IsAsynchronous)
    return JsonSerializer.DeserializeAsync<TResult>(input, options, token);
  else
    return new ValueTask<TResult>(JsonSerializer.Deserialize<TResult>(input, options));
}
```

## Alternative Designs
N/A

## Risks

* Library X defines its own stream class that overrides the async methods but does not override IsAsynchronous (because it targets an older version on .NET that does not define Stream.IsAsynchronous).
* Library Y, which previously used the async methods only, is modified to read the IsAsynchronous property and call the sync methods if its value is false.
* Library Y is given an instance of the stream class defined in library X. Because IsAsynchronous defaults to false, library Y then calls the sync methods rather than the async methods, and blocks the calling thread for longer than its previous versions did.

## Impact
This property should be overridden by all existing streams in .NET standard libraries.

**Comment by KalleOlaviNiemitalo** [comment]
There is a risk that:

- Library X defines its own stream class that overrides the async methods but does not override IsAsynchronous (because it targets an older version on .NET that does not define Stream.IsAsynchronous).
- Library Y, which previously used the async methods only, is modified to read the IsAsynchronous property and call the sync methods if its value is false.
- Library Y is given an instance of the stream class defined in library X. Because IsAsynchronous defaults to false, library Y then calls the sync methods rather than the async methods, and blocks the calling thread for longer than its previous versions did.

In this situation, the app developer might have to downgrade library Y back to a version that does not read the IsAsynchronous property. That becomes harder if library Y is part of .NET itself. Would you make any type in .NET read the property?

**Comment by danmosemsft** [comment]
@stephentoub

**Comment by sakno** [comment]
@KalleOlaviNiemitalo , if code ignores `IsAsynchronous` property then its performance remains the same. This fact allows to migrate step-by-step, at least for code in .NET Core. As additional option, `IsAsynchronous` property might return `bool?` type where **null** means no special knowledge about async internals of the stream.

**Comment by KalleOlaviNiemitalo** [comment]
> This fact allows to migrate step-by-step, at least for code in .NET Core.

The developers of library Y might not even know that library X exists. The app developer who wants to use both libraries then suffers.

Perhaps the default `Stream.IsAsynchronous` implementation could check whether the async methods are overridden. Would this require reflection that would hinder the IL linker? Apparently, one cannot get a [function pointer](https://github.com/dotnet/csharplang/blob/43966001afe2cdf94e5638063536a090769d2c0b/proposals/function-pointers.md) to an instance method and compare it.

**Comment by SingleAccretion** [comment]
1. What would the guidance be for implementations that only supports some async methods? Is that assumed to be very rare?
2. As this is a performance-oriented API, what is the order of the estimated benefit here?
3. If accepted, it is a good candidate for the "soft abstract" attribute.

**Comment by stephentoub** [comment]
I appreciate the goal behind the suggestion, but I don't think this is something that should be added.  The base implementation would have to return false, and there are tons of custom streams in the world that won't have overridden this even though it would make sense for them to, leading to a caller paying attention to it experiencing worse behaviors.  There are many async operations on a Stream, and a single property that dictating one aspect of the behavior for all of them isn't appropriate: there are definitely streams that override some but not all of the async methods.  Some implementations may or may not be asynchronous depending on conditions, for example CryptoStream does use async I/O, but it also does a lot of computation, and so it forces its operations to queue in order to move the work off the calling thread in case the caller is expecting parallelism.  And there are many APIs beyond Stream where an async method may or may not queue a work item as part of its operation, and even where the base method queues.

A more general approach to this that I'd be in favor of would be an API that let you determine whether a method had an override.  The logic in the original example here would be based on whether the target API was overridden or not.

**Comment by scalablecory** [comment]
I agree with @stephentoub.

This is a problem in any async abstraction -- e.g. some 3rd party DbConnection implementations do not implement async still; I don't know that only enabling this visibility in `Stream` will adequately solve it. Also, I think very little code will be willing to dual-path at the `Stream` level for sync/async, so I'm not sure how much use this would see.

**Comment by stephentoub** [comment]
Closing per https://github.com/dotnet/runtime/issues/38797#issuecomment-654235546 and https://github.com/dotnet/runtime/issues/38797#issuecomment-654504410. Thanks for the suggestion.
