### ISSUE TITLE
Microsoft.Bcl.AsyncInterfaces portability with .NET Standard 2.0

### ISSUE THREAD

**Issue by troysteinbauer** [dotnet/runtime#38882]
### Description

Using the [.NET Portability Analyzer](https://github.com/microsoft/dotnet-apiport) on the `.NET Standard 2.0` build of `Microsoft.Bcl.AsyncInterfaces` library gives a result of `96.45%`. See the attached file below which contains the `HTML` and `XML` output of the `ApiPort` tool.

 - [ApiPortAnalysis.zip](https://github.com/dotnet/runtime/files/4886338/ApiPortAnalysis.zip)

This appears to be the reason preventing the library from being used inside a `Unity3D` project. `Unity3D` does support `.NET Standard 2.0` libraries (info [here](https://docs.unity3d.com/Manual/dotnetProfileSupport.html)). Here is a minimal example of the `Unity3D` project failing to compile with `Microsoft.Bcl.AsyncInterfaces`.

 - [Example.zip](https://github.com/dotnet/runtime/files/4886366/Example.zip)

Is it possible to update `Microsoft.Bcl.AsyncInterfaces` to become `100% .NET Standard 2.0` compatible to unblock it's usage on `Unity3D` projects?

### Configuration

N/A

### Regression?

N/A

### Other information

N/A

**Comment by twsouthwick** [comment]
This occurs because the recommendation is to use ApiPort to analyze users' own code, not necessarily dependencies. In this example, you're actually analyzing against a .NET 4.7.2 version of the interfaces, while there is a .NET Standard build of it. The implementation details of an assembly can be different for different target versions (normally for perf reasons),

When analyzing an application, you want to follow a specific set of [ordered steps](https://docs.microsoft.com/en-us/dotnet/core/porting/). Note that API analysis is after you update dependencies.

**Comment by joperezr** [comment]
Given the comment above and the fact that AsyncInterfaces actually does support netstandard 2.0 today I'll go ahead and close this for now. Feel free to reopen otherwise.
