### ISSUE TITLE
Remove Serialization tests for SQLClient types now that they no longer live in the dotnet/runtime repo

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#38949]
referencing @stephentoub's comment here https://github.com/dotnet/runtime/pull/38948#discussion_r451742184

Now that SqlClient is no longer part of dotnet/runtime repo we should remove the serialization tests for those types. The comment on the PR above pretty much sumps up which section needs to be removed from the serialization test data.

**Comment by Wraith2** [comment]
Some things can be removed like `OperationAbortedException` for example was moved out of `System.Data` into SqlClient and so the testing belongs in the M.D.SqlClient repo. Other things like `SqlTruncateException` are in `System.Data.Common` which remains in this repo and likely can't be moved for similar reasons to the SqlInt32 types, because DataAdapters use them. So anything that's in SqlClient assembly can go but anything in Common must still be tested in runtime.

**Comment by focusonmx** [comment]
Let me do this.
