### ISSUE TITLE
[Perf -22%] System.Collections.Tests.Perf_Dictionary.ContainsValue

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39028]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Collections.Tests.Perf_Dictionary

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
ContainsValue | 5.27 ms | 6.44 ms | 1.22 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.Tests.Perf_Dictionary_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.Tests.Perf_Dictionary.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.Tests.Perf_Dictionary*';
```
<details>

#### System.Collections.Tests.Perf_Dictionary.ContainsValue(Items: 3000)

```log
[4962331.796 ; 5192188.408) | @@@@@
[5192188.408 ; 5388224.960) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[5388224.960 ; 5584261.513) | 
[5584261.513 ; 5826478.241) | 
[5826478.241 ; 6050548.738) | @@@@@@@@@@@@@@@@@@@
[6050548.738 ; 6291365.890) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[6291365.890 ; 6487402.443) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[6487402.443 ; 6696002.912) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

category:cq
theme:codegen
skill-level:intermediate
cost:medium

**Comment by stephentoub** [comment]
cc: @benaadams

**Comment by stephentoub** [comment]
I also see a fairly consistent (but slightly smaller) regression locally:

```
dotnet run -c Release -f netcoreapp3.1 --runtimes netcoreapp3.1 netcoreapp5.0 --join --filter *System.Collections.Tests.Perf_Dictionary.ContainsValue*
```

|        Method |        Job |       Runtime |     Toolchain | Items |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio |
|-------------- |----------- |-------------- |-------------- |------ |---------:|----------:|----------:|---------:|---------:|---------:|------:|
| ContainsValue | Job-BRMEWE | .NET Core 3.1 | netcoreapp3.1 |  3000 | 3.710 ms | 0.0423 ms | 0.0395 ms | 3.709 ms | 3.645 ms | 3.777 ms |  1.00 |
| ContainsValue | Job-VAPWCQ | .NET Core 5.0 | netcoreapp5.0 |  3000 | 4.349 ms | 0.0386 ms | 0.0322 ms | 4.353 ms | 4.287 ms | 4.400 ms |  1.17 |

**Comment by danmosemsft** [comment]
As dictionary perf tests go, this is a simple case as there's no hashing involved.

Note the perf test is choosing `Dictionary<int, int>` so it goes down the value type path.
Previously that was
```c#
                if (default(TValue)! != null) // TODO-NULLABLE: default(T) == null warning (https://github.com/dotnet/roslyn/issues/34757)
                {
                    // ValueType: Devirtualize with EqualityComparer<TValue>.Default intrinsic
                    for (int i = 0; i < _count; i++)
                    {
                        if (entries![i].next >= -1 && EqualityComparer<TValue>.Default.Equals(entries[i].value, value)) return true;
                    }
                }
```
now
```c#
            else if (typeof(TValue).IsValueType)
            {
                // ValueType: Devirtualize with EqualityComparer<TValue>.Default intrinsic
                for (int i = 0; i < _count; i++)
                {
                    if (entries![i].next >= -1 && EqualityComparer<TValue>.Default.Equals(entries[i].value, value))
                    {
                        return true;
                    }
                }
            }
```
Basically the same. This may be one of those subtle code quality things.

**Comment by danmosemsft** [comment]
I see the exact same regression as @stephentoub.

`C:\git\performance\src\benchmarks\micro>dotnet run -c Release -f netcoreapp3.1 --runtimes netcoreapp3.1 netcoreapp5.0 --join --filter *System.Collections.Tests.Perf_Dictionary.ContainsValue*`
```

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.421 (2004/?/20H1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-rc.1.20401.3
  [Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
  Job-RCZOTE : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
  Job-LFLPXX : .NET Core 5.0.0 (CoreCLR 5.0.20.40101, CoreFX 5.0.20.40101), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable  IterationTime=250.0000 ms
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1

|        Method |        Job |       Runtime |     Toolchain | Items |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------- |----------- |-------------- |-------------- |------ |---------:|----------:|----------:|---------:|---------:|---------:|------:|------:|------:|------:|----------:|
| ContainsValue | Job-RCZOTE | .NET Core 3.1 | netcoreapp3.1 |  3000 | 4.097 ms | 0.0325 ms | 0.0304 ms | 4.099 ms | 4.051 ms | 4.160 ms |  1.00 |     - |     - |     - |         - |
| ContainsValue | Job-LFLPXX | .NET Core 5.0 | netcoreapp5.0 |  3000 | 4.800 ms | 0.0511 ms | 0.0453 ms | 4.815 ms | 4.691 ms | 4.854 ms |  1.17 |     - |     - |     - |         - |

```

**Comment by danmosemsft** [comment]
Is devirtualization not happening?

**Comment by danmosemsft** [comment]
@AndyAyersMS might you have cycles to compare the codegen for Dictionary<int, int>ContainsValue ? We did not change the code, apparently.

**Comment by AndyAyersMS** [comment]
Yes, I'll take a look.

**Comment by AndyAyersMS** [comment]
The inner-loop codegen for `ContainsValue` is slightly different:
<table>
<tr>
<td>
<pre>
;;; 3.1
M01_L00:
       cmp       r9d,eax
       jae       short M01_L04
       movsxd    r10,r9d
       shl       r10,4
       ;; 
       cmp       dword ptr [r8+r10+10],0FFFFFFFF
       jl        short M01_L01
       mov       r10d,[r8+r10+1C]
       cmp       r10d,edx
       sete      r10b
       movzx     r10d,r10b
       test      r10d,r10d
       jne       short M01_L03
M01_L01:
       inc       r9d
       cmp       r9d,ecx
       jl        short M01_L00
</pre>
</td>
<td>
<pre>
;;; 5.0
M01_L00:
       cmp       r9d,eax
       jae       short M01_L04
       movsxd    r10,r9d
       shl       r10,4
       lea       r10,[r8+r10+10]
       cmp       dword ptr [r10+4],0FFFFFFFF
       jl        short M01_L01
       mov       r10d,[r10+0C]
       cmp       r10d,edx
       sete      r10b
       movzx     r10d,r10b
       test      r10d,r10d
       jne       short M01_L03
M01_L01:
       inc       r9d
       cmp       r9d,ecx
       jl        short M01_L00
</pre>
</td>
</tr>
</table>

Since this particular test is not intentionally causing collisions it's likely that this loop does not iterate (will confirm), so we're probably looking at straight-line performance; also the test is only looking up keys known to be present, so the first two jumps in the sequence (bounds check and empty bucket check) should both fall through. So at first guess we're seeing the additional latency caused by the extra `lea` in the 5.0 sequence.

**Comment by AndyAyersMS** [comment]
We changed the layout of the `Entry` data structure in dotnet/coreclr#27195.

The upshot is that in 5.0 the offset add for the `next` field is outside the bounds check comma rather than within:
```
3.1 tree

[000036] ---XG+------  \--*  JTRUE     void  
[000035] J--XG+-N----     \--*  LT        int   
[000110] ---XG+------        +--*  COMMA     int   
[000103] ---X-+------        |  +--*  ARR_BOUNDS_CHECK_Rng void  
[000030] -----+------        |  |  +--*  LCL_VAR   int    V05 loc3         
[000102] ---X-+------        |  |  \--*  ARR_LENGTH int   
[000029] -----+------        |  |     \--*  LCL_VAR   ref    V02 loc0         
[000112] *---G+------        |  \--*  IND       int   
[000111] ----G-------        |     \--*  ADDR      byref  Zero Fseq[next]
[000031] a---G+-N----        |        \--*  IND       struct
[000109] -----+------        |           \--*  ADD       byref 
[000100] -----+------        |              +--*  LCL_VAR   ref    V02 loc0         
[000108] -----+------        |              \--*  ADD       long  
[000106] -----+------        |                 +--*  LSH       long  
[000104] -----+------        |                 |  +--*  CAST      long <- int
[000101] i----+------        |                 |  |  \--*  LCL_VAR   int    V05 loc3         
[000105] -----+-N----        |                 |  \--*  CNS_INT   long   4
[000107] -----+------        |                 \--*  CNS_INT   long   16 Fseq[#FirstElem]
[000034] -----+------        \--*  CNS_INT   int    -1

5.0 tree

[000029] ---XG+------   *  JTRUE     void  
[000028] J--XG+-N----   \--*  LT        int   
[000026] *--XG+------      +--*  IND       int   
[000086] ---XG+------      |  \--*  ADD       byref 
[000097] ---XG+------      |     +--*  COMMA     byref 
[000090] ---X-+------      |     |  +--*  ARR_BOUNDS_CHECK_Rng void  
[000023] -----+------      |     |  |  +--*  LCL_VAR   int    V04 loc2         
[000089] ---X-+------      |     |  |  \--*  ARR_LENGTH int   
[000022] -----+------      |     |  |     \--*  LCL_VAR   ref    V02 loc0         
[000098] ----G-------      |     |  \--*  ADDR      byref 
[000024] a---G+-N----      |     |     \--*  IND       struct
[000096] -----+------      |     |        \--*  ADD       byref 
[000087] -----+------      |     |           +--*  LCL_VAR   ref    V02 loc0         
[000095] -----+------      |     |           \--*  ADD       long  
[000093] -----+------      |     |              +--*  LSH       long  
[000091] -----+------      |     |              |  +--*  CAST      long <- int
[000088] i----+------      |     |              |  |  \--*  LCL_VAR   int    V04 loc2         
[000092] -----+-N----      |     |              |  \--*  CNS_INT   long   4
[000094] -----+------      |     |              \--*  CNS_INT   long   16 Fseq[#FirstElem]
[000085] -----+------      |     \--*  CNS_INT   long   4 field offset Fseq[next]
[000027] -----+------      \--*  CNS_INT   int    -1
```
This alters the jit's CSE behavior as now the comma subtree in 5.0 is identical to the one for the element access, and so they get CSEd. That CSE is the `lea` we see above.

This difference arises in morph. Both compiles start out with
```
*  JTRUE     void  
\--*  LT        int   
   +--*  FIELD     int    next
   |  \--*  ADDR      byref 
   |     \--*  INDEX     struct
   |        +--*  LCL_VAR   ref    V02 loc0         
   |        \--*  LCL_VAR   int    V04 loc2         
   \--*  CNS_INT   int    -1
```

In 3.1 the `next` field is at offset 0 and so the field offset add is "pushed down" by `fgAddFieldSeqForZeroOffset` onto the addr. 

In 5.0 the `next` field is at offset 4 and so morph takes a different path and produces the tree you see above.

Sadly the jit codegen here is still quite sloppy (in both cases) as there are a number of issues:
* not making effective use of address modes (`shl` should fold in to address mode, etc)
* materialize a bool result and then test it rather than just use flags from the `cmp`
* no IV widening or strength reduction

Would be instructive perhaps to code up the equivalent in C++ and see what perf we're leaving on the table.

**Comment by danmosemsft** [comment]
I want to appreciate your analyses, @AndyAyersMS, I always learn something 😺 

As you know, Dictionary,GetValue is an antipattern API - if it is on a hot path, the caller is probably using the wrong data structure. So there is no suggestion on my part that this is important for 5.0. It's key lookups that are vital.

**Comment by AndyAyersMS** [comment]
@danmosemsft yes, this is not a perf critical API.

Per dotnet/coreclr#27195, the rational for the rearrangement of `Entry` fields was:

> Rearrange Entry struct to put hashCode first rather than next as it is accessed first which should work with prefetching better.

We might try undoing this and see if we can recover the perf here without regressing the more important `TryInsert` and `FindValue` methods, but would suggest we hold off on this until after 5.0.

**Comment by AndyAyersMS** [comment]
Also even if we flip `Entry` back to how it was before, I'd like to tag this as codegen somehow, as we should be able to cope with either layout equally well.

**Comment by danmosemsft** [comment]
@eiriktsarpalis @layomia are area owners. Chaps, shall we move this out to Future since it's not such a perf-critical API, and there is no simple fix?

@AndyAyersMS I'm thinking it makes sense to re-label this codegen since it sounds like improvements there might be of broader value/more durable than twiddling with the layout of the struct in Dictionary which itself may regress something else.

**Comment by AndyAyersMS** [comment]
FWIW this has since been fixed:

BenchmarkDotNet v0.13.7-nightly.20230717.35, Windows 11 (10.0.22621.2283/22H2/2022Update/SunValley2)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8.1 (4.8.9181.0), X64 RyuJIT VectorSize=256
  Job-ABUNJC : .NET 5.0.0 (5.0.20.51904), X64 RyuJIT AVX2
  Job-BNIUVI : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT AVX2
  Job-FGPKFA : .NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2
  Job-ECXIHB : .NET 8.0.0 (8.0.23.28008), X64 RyuJIT AVX2
  Job-DMXYGM : .NET Core 3.1.32 (CoreCLR 4.700.22.55902, CoreFX 4.700.22.56512), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:EnableUnsafeBinaryFormatterSerialization=true  IterationTime=250.0000 ms
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1

|        Method |       Runtime | Items |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio | RatioSD | Allocated | Alloc Ratio |
|-------------- |-------------- |------ |---------:|----------:|----------:|---------:|---------:|---------:|------:|--------:|----------:|------------:|
| ContainsValue |      .NET 5.0 |  3000 | 7.297 ms | 0.5940 ms | 0.6840 ms | 7.244 ms | 6.261 ms | 8.555 ms |  1.51 |    0.13 |       2 B |        1.00 |
| ContainsValue |      .NET 6.0 |  3000 | 5.751 ms | 0.2182 ms | 0.2512 ms | 5.764 ms | 5.347 ms | 6.153 ms |  1.22 |    0.05 |      11 B |        5.50 |
| ContainsValue |      .NET 7.0 |  3000 | 3.484 ms | 0.1171 ms | 0.1253 ms | 3.461 ms | 3.292 ms | 3.738 ms |  0.74 |    0.03 |       7 B |        3.50 |
| ContainsValue |      .NET 8.0 |  3000 | 3.534 ms | 0.1147 ms | 0.1275 ms | 3.502 ms | 3.368 ms | 3.811 ms |  0.74 |    0.02 |       6 B |        3.00 |
| ContainsValue | .NET Core 3.1 |  3000 | 4.724 ms | 0.0743 ms | 0.0695 ms | 4.711 ms | 4.638 ms | 4.886 ms |  1.00 |    0.00 |       2 B |        1.00 |
