### ISSUE TITLE
Clarify constraints on using NGEN with ReJIT

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/runtime#39160]
There is some contradictory information in this repo regarding whether ReJIT can be used with NGEN assemblies.

The original [ReJIT Limitations blog post by David Broman](https://github.com/dotnet/runtime/blob/d8302cef7946be82775ba5b94a88ad8eee800714/docs/design/coreclr/profiling/davbr-blog-archive/ReJIT%20-%20Limitations.md) states:

> In order to set that ReJIT flag I just mentioned, you must also set a new flag which completely disables the use of NGENd images. (`COR_PRF_DISABLE_ALL_NGEN_IMAGES`)

However, the following comment can be inferred to mean that David's blog post is now outdated, and that it is now supported except for a known issue with inlining:
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/coreclr/src/vm/rejit.cpp#L124-L125

But then, the following comment, and the existence of [inlinetracking.cpp](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/coreclr/src/vm/inlinetracking.cpp) seem to indicate that perhaps that known issue has already been solved: 
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/coreclr/src/vm/rejit.cpp#L803-L804

It would be very useful you could please share some clarity on this issue.

/cc @davmason

**Comment by davmason** [comment]
Hi @OmerRaviv

ReJIT has worked with NGEN images since roughly .Net Framework 4.5. The original blog post by David Broman was written for the 4.0 release when it was not supported. It is also supported for R2R images on all versions of .Net Core.

The inlining issue you mentioned is that NGEN is free to inline methods, so you potentially have methods inlined and won't get a JITInlining callback for them. We added ICorProfilerInfo6::EnumNgenModuleMethodsInliningThisMethod to solve this problem, if there is a method you want to ReJIT in a NGEN image you can call this method to get an enumerator that will give you all the methods your method has been inlined in.

Let me know if there's anything else I can help provide information on.

**Comment by OmerRaviv** [comment]
Thanks so much, @davmason ! That is extremely helpful.

**Comment by davmason** [comment]
It seems like this issue is resolved so I am closing it. If you have further questions feel free to reopen or file a new issue.
