### ISSUE TITLE
System.Runtime.CompilerServices.ExtensionAttribute not being applied to the extensions

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#39253]
Microsoft.CCI.Extensions rely on this attribute to check whether a method is an extension or not https://github.com/dotnet/arcade/blob/master/src/Microsoft.Cci.Extensions/Extensions/CSharp/CSharpCciExtensions.cs#L667

I encountered this while generating a reference source of system.refelection.typeextensions where all the "this" keyword was getting skipped. 

I checked the dll and this attribute is not present and also verified by attaching a debugger.

if this behavior is by design ?

cc @ericstj @safern @ViktorHofer

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Reflection.TypeExtensions/src/System/Reflection/TypeExtensions.cs#L4 has comment about this. I do not think that this comment has merit. It should be fine to delete this comment and mark all methods in the implementation with `this`.

**Comment by ericstj** [comment]
Agree with @jkotas here, assuming compiler does the right thing.  We can mitigate the "looks like infinite recursion" by adding a comment that says these all call the instance methods, then ensure we have tests that directly invoke the static methods to ensure they don't recurse.

IIRC that comment came about because someone forgot an assembly ref in the src at one point and actually did create infinite recursive impl and the tests didn't catch it because they were using instance and not static syntax.
