### ISSUE TITLE
Remove BinaryFormatter usage from System.Resources.Extensions

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#39292]
Ref:

https://github.com/dotnet/runtime/blob/af828ae24cd094b7f0abfe5f208e329049934b37/src/libraries/System.Resources.Extensions/src/System/Resources/Extensions/DeserializingResourceReader.cs#L37-L48

This issue tracks the removal and replacement of this code per [the `BinaryFormatter` obsoletion plan](https://github.com/dotnet/designs/pull/141).

**Comment by tarekgh** [comment]
CC @ericstj

**Comment by danmosemsft** [comment]
Per the plan, this could maybe have the 6.0 milestone?

**Comment by ericstj** [comment]
Actually it's not clear to me from this doc why this code is removed or replaced.   Why wouldn't we just let this be controlled by "disable `BinaryFormatter`" feature switch?

**Comment by GrabYourPitchforks** [comment]
`BinaryFormatter` is eventually going to be disabled by default across all project types, and for all new project types (wasm, etc.) it's permanently disabled _with no way to re-enable it_. Per the doc our eventual goal is that no aspect of the .NET runtime or first-party libraries should require developers to re-enable `BinaryFormatter` within their applications. Requiring users to re-enable it runs counter to our goal of improving the ecosystem. It's also going to be infeasible for certain code bases to re-enable support for `BinaryFormatter` since it will be perma-disabled for compliance reasons, regardless of project type.

**Comment by ericstj** [comment]
I see.  The real work here would be to get @dotnet/dotnet-winforms and @dotnet/project-system to migrate off of using `BinaryFormatter` for types and move to one of the other supported formats (`TypeConverter` or `Stream`).  We may also need to  add some API (Stream ctors) or TypeConverters to support this scenario for types we own that don't currently work well in this scenario.  We probably also need an migration tool that would convert binary-formatted payloads folks have checked into their source resx files and converts to a one of the new formats.

@GrabYourPitchforks maybe we should start by getting these teams to move to a new method and update the components which are producing BinaryFormatted payloads?

Here's a rough sketch of the order I'd see this happening:
1. Update ResXResourceWriter (and any other code in WinForms designer / project-system) to ensure that it gives precedence to safe formats, and fails rather than using BinaryFormatter.
2. Produce a migration tool that converts existing BinaryFormatted payloads -> safe formats, ideally just roundtripping through code updated in 1.
3. Introduce some type of warning/failure in MSBuild when it encounters these payloads and instructs folks to run tool from 2.
4. For any types which require work (TypeConverters or API) we add it based on feedback / discovery of errors after doing 3.  We could probably proactively do some of this based on our existing data.  Note that anything we do here wouldn't work on older frameworks if we just added the converters to the types.  TypeConverters could be OOB-able if we register them on the consumption side (via TypeDesicriptor).  We'd need to decide if it was important for this change to work on older frameworks, and if so we could do this registration in the DeserializingResourceReader.
5. Remove the use of BinaryFormatter in DeserializingResourceReader.

**Comment by merriemcgaw** [comment]
@dreddy-work . FYI. We need to start planning for this.

**Comment by ericstj** [comment]
cc @rainersigwald as well

**Comment by rainersigwald** [comment]
I believe there's also implication on the VS designers for .resx files.

**Comment by tmeschter** [comment]
Yep. I've pinged @jjmew so we can get updates to the Resource Editor into the planning for (hopefully) .NET 6 but I can't offer any guarantees.

We're going to have interesting problems with projects that multi-target versions of .NET that have `BinaryFormatter` and those that don't.

**Comment by jjmew** [comment]
@rainersigwald and @tmeschter  I think we need PM involved to help us with what experience we want for multi-targeting. Cc: @mckennabarlow @cartermp

**Comment by merriemcgaw** [comment]
@OliaG might be interested in this discussion too.

**Comment by bartonjs** [comment]
Addressed by #102379.
