### ISSUE TITLE
RegularExpressionAttribute does not work correctly

### ISSUE THREAD

**Issue by kronic** [dotnet/runtime#39502]
```csharp
var isValid = new RegularExpressionAttribute("[0-9]{2}|[0-9]{5}|[0-9]{8}").IsValid("12"); //true 
isValid = new RegularExpressionAttribute("[0-9]{2}|[0-9]{5}|[0-9]{8}").IsValid("12345");//false 
isValid = new RegularExpressionAttribute("[0-9]{2}|[0-9]{5}|[0-9]{8}").IsValid("12345678");//false

**Comment by MarkPflug** [comment]
I think the problem is with your regex pattern. All of these inputs are matching the first alteration `[0-9]{2}`. The problem is that RegularExpressionAttribute checks if the pattern matches, then subsequently checks that the match covers the entire input string start == 0, matchlength== inputlength. The first alteration doesn't cover the entire input in the second and third cases. Probably debatable whether RegularExpressionAttribute should be doing that second check or not, but it does.

You can fix this by explicitly adjusting your regex pattern:

`var pattern = "^([0-9]{2}|[0-9]{5}|[0-9]{8})$";`

In my experience, 9 times out of 10, a validation regex should always start with `^` and end with `$`. Also, in my experience, I see this done about 1/10 times.

**Comment by danmosemsft** [comment]
@MarkPflug is correct that the regex will match the first alternation.

Another option is to reverse the alternation eg `[0-9]{8}|[0-9]{5}|[0-9]{2}`. Note that this will still match 4 digits, but as two matches. I don't know whether that's what you want.

This is not specific to .NET. Most .NET regexes are also valid in other dialects, and you can use an online tester to experiment. Here's a good one:

https://regex101.com/r/PhVIeG/1
