### ISSUE TITLE
Add additional APIs to support common certificate scenarios

### ISSUE THREAD

**Issue by csteegz** [dotnet/runtime#39590]
## Background and Motivation
HTTPClientHandler offers a callback, CertificateCustomValidationCallback which enables custom validation of server certificates in the client. It also offers a pre-written delegate, DangerousAcceptAnyServerCertificateValidator which implements allows any server certificate. There are other common server certificate validation scenarios, specifically trusting certificates with a specific certificate as the root CA which would benefit from having a correctly implemented solution as opposed to being ad-hoc re-implimented based on the top stack overflow result.

## Proposed API

Add to `HttpClientHandler` 
```
public static Func<HttpRequestMessage, X509Certificate2?, X509Chain?, SslPolicyErrors, bool> AcceptAsRootCAPolicy(X509Certificate2 caCertificate)
``` 

(Apologies if this isn't the right issue format)

**Comment by wfurt** [comment]
That seems rather complicated and if I understand correctly, you really just want this inside of CertificateCustomValidationCallback, right?
```c#
  chain.ChainPolicy.CustomTrustStore.Add(caCert);
  chain.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;

  return chain.Build(certificate);
```
and of course you can add you custom CA to users/system CA store.

**Comment by csteegz** [comment]
I didn't know about those APIs being added in Dotnet 5.0! That's good enough for me, I was asking more along the lines of 3.1 where you have to do stuff like this (https://stackoverflow.com/questions/33627593/c-sharp-net-how-to-allow-a-custom-root-ca-for-https-in-my-application-on).

It'd be nice to have a docs page with that specific code (or on the CertificateCustomValidationCallback or X509Chain or X509ChainPolicy pages)

**Comment by wfurt** [comment]
It is unlikely for  3.1 or Framework to get any API changes. For old releases, I think something along the stackoverflow is reasonable. You generally test if root of the chain is what you expect and if UntrustedRoot is only one reported issue.
Since this is probably not very common scenario, doing little bit of code does not seems that bad. (and it is easier with 5+)

It seems like neither https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.customtruststore?view=net-5.0 nor https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chaintrustmode?view=net-5.0 have good documentation ;(

If you want to, https://github.com/dotnet/dotnet-api-docs takes contributions.

**Comment by csteegz** [comment]
I'll disagree about "Not very common scenario" and the <=3.1 amount of code not being bad (it's not the amount of code, it's the documentation and general skittishness about writing security code), but the 5+ apis are excellent. I'll look into opening an issue or PR in the API-docs repo.
