### ISSUE TITLE
coreclr.dll regressed by ~300kB due to vxsort

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#39600]
coreclr.dll sizes

64c9e7c6d12db0e03d5a2589239b53b0a4046761 4,728,832
69b0d160953f5c920e52f021366743623693c158 5,027,840

**Comment by jkotas** [comment]
Is it really expected for vxsort to be 300kB of code? That's almost as much as the rest of the GC.

**Comment by jkotas** [comment]
cc @PeterSolMS

**Comment by PeterSolMS** [comment]
Well, we have 4 flavors of the sorting code (two instruction sets - AVX2, AVX512F, and two types - int32_t and int64_t). We can limit the amount of inlining in the bitonic sorters that are called for small arrays - doing this immediately reduced the size of coreclr.dll by 180 kB. There are more tricks we can do, or dial back on the number of sorting code flavors.

**Comment by mangod9** [comment]
is avx512 significantly better to keep both implementations?

**Comment by PeterSolMS** [comment]
AVX512 is roughly about 2.2x faster than AVX2 for 64-bit elements, and about 1.4x faster for 32-bit elements, according to Dan Shechter's numbers. That is unless we're limited by memory bandwidth, in which case the difference is less. However, it's quite common to have one GC server thread take significantly longer than the others due to a larger mark list, in which case the other GC threads will have to wait. In that case, the difference in performance will definitely show up in pause time.

**Comment by MichalStrehovsky** [comment]
Does AVX-512 still have the throttling issues CloudFlare talked out [here](https://blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/) (would they affect us?).

At the end of the blog they basically recommend disabling AVX-512 unless one has some very specific tasks that rely on it.

**Comment by PeterSolMS** [comment]
We are aware of the issue and only use AVX-512 for big mark lists where (according to our back-of-the-envelope calculations) it seems worthwhile, even taking into account the ~700 us long downclocking that occurs with current Intel hardware.

After the sorting, we do the plan_phase, whose performance is more driven by main memory access speed than processor clock.

So, in theory we should be ok, but we are still lacking validation from the real world.

**Comment by damageboy** [comment]
Jumping on this thread just now.

@MichalStrehovsky 
> Does AVX-512 still have the throttling issues CloudFlare talked out here (would they affect us?).

The throttling issues are definitely real, but given we start with a scalar version that runs for ~7ms and speeds it up by a good factor of 10x, the extra 650-680usec of throttling incurred AFTER the sorting completes (the downclock is anywhere between 20-30% depending on the amount of cores doing AVX512) does not seem like a bad trade-off to me.

For a complete a thorough discussion of throttling in this respect:
https://github.com/dotnet/runtime/pull/37159#discussion_r445049384

It should be noted that the AVX2 code also throttles but to a lesser degree.

I'm working on a different approach to my bitonic sort which is the greatest contributor to the code size here.

If everything works out well, the time per element will be higher (during bitonic sorting) but this would also allow for higher sizes (up to 048 elements with int32) which would in turn pay up for the per-element slowdown in the global scheme of things.

Regardless of the bitonic sort code/size improvements, there is indeed a separate discussion to be had about AVX512.

It's also worthwhile to mention that we can always decide to not include AVX512 in the code if its specific benefit seems marginal, but I think it is best to reconvene here after I hopefully finish my bitonic_sort diet.

My expectation is that going from 16 vectors to 4 vectors at a time (for sorting) will cut down about 60% of the size increase reported (so working assumption should be 300K -> 100K-ish for AVX2+AVX512).

Also bear in mind that only one of those versions would be used in runtime at any given moment (e.g. disk-space vs. memory/cache space).

Any thoughts as to these plans? I'm assuming I'm 1-2 weekends away from at least being able to commit to this happening after I see the whole thing giving first signs of life.

**Comment by PeterSolMS** [comment]
I'm testing an update with limited inlining for the bitonic sorters (saving about 180 kB code size), and using your dynamic packing/unpacking code. Assuming things go well, that'll be the next step. After this, we can certainly do more.

**Comment by damageboy** [comment]
Just to update quickly: I've managed to create an on-par version of the bitonic sorter, which was by far the biggest offender in terms of code-size bloat.
The new version is considerably smaller, per type (56KB -> 2.8KB or 95% reduction). I now expect the total size of the vxsort related bloat to fall well below 100KB. All this without sacrificing any considerable speed.

I'm still working on cleaning up the code so that all AVX2+AVX512 sorters benefit from this code-size reduction. It will probably take a few more days before I complete the "upgrade" on my-end before we can backport it to the coreclr version.

**Comment by mangod9** [comment]
@PeterSolMS can this issue be closed now that your sort changes have merged?

**Comment by PeterSolMS** [comment]
Yes, let's close it. As @damageboy mentioned, we can do better in .NET 6 though...

**Comment by mangod9** [comment]
Fixed by: https://github.com/dotnet/runtime/pull/40613
