### ISSUE TITLE
GetFromJsonAsync(HttpClient, String, Type, CancellationToken) Losing Track of its Type

### ISSUE THREAD

**Issue by ericpincus** [dotnet/runtime#39627]
Using GetFromJsonAsync(HttpClient, String, Type, CancellationToken) via Blazor hosted WebAssembly (Version 16.7.0 Preview 4.0 and WebAssembly v5.0.0-preview.6.20312.15.

I don't want to use the `GetFromJsonAsync<TValue>(HttpClient, String, CancellationToken)` because I specifically don't want to make any explicit casts. The following only works successfully with the explicit cast, it won't return the result from the Json call without it.

This should work, since it knows it's a `List<Means>` type via the DataType parameter but does not:
`Items = ((List<TableEntity>)await Server.GetFromJsonAsync(GetAPIs, DataType));`

This does, but the need for explicit casting takes away the power of the non TValue version of the function:

`Items = ((List<Means>)await Server.GetFromJsonAsync(GetAPIs, DataType)).Cast<TableEntity>().ToList();`

Note: GetAPIs a string with the correct path to the API on the controller. DataType is set as `typeof(List<Means>)` and Items is `List<TableEntity>`.

Perhaps I'm missing something, but I expect the source code may have a bug.

Thank you in advance - EP

**Comment by scalablecory** [comment]
The behavior you're seeing is that you can't cast a List of one type as a List of another type. This is happening outside of `GetFromJsonAsync`.

As an example of what you're seeing, this will fail for the same reason:
```c#
List<Means> listA = new List<Means>();
List<TableEntity> listB = listA;
```

Calling `.Cast<TableEntity>.ToList()` is one correct solution, if you do need a `List`. Another, if you don't need to modify the list, is to use the covariant `IEnumerable` instead of `List`:

```c#
Items = ((IEnumerable<TableEntity>)await Server.GetFromJsonAsync(GetAPIs, DataType));
```

**Comment by ericpincus** [comment]
Thank you @scalablecory - IEnumerable is an acceptable workaround for my purposes.
