### ISSUE TITLE
System.Runtime.Serialization.Formatters.Tests.FormatterServicesTests.GetUninitializedObject_COMObject_ThrowsNotSupportedException fails with Mono

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#39704]
Configuration: net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open

The test wasn't running before because it was excluded via `TargetsWindows` even though the test project is runtime agnostic. https://github.com/dotnet/runtime/blob/632cdcab09fda363e460296a77be0be32096f512/src/libraries/System.Runtime.Serialization.Formatters/tests/System.Runtime.Serialization.Formatters.Tests.csproj#L15

This was fixed with https://github.com/dotnet/runtime/pull/35606 and started failing for Mono.

```
System.Runtime.Serialization.Formatters.Tests.FormatterServicesTests.GetUninitializedObject_COMObject_ThrowsNotSupportedException [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          C:\git\runtime4\src\libraries\System.Runtime.Serialization.Formatters\tests\FormatterServicesTests.Windows.cs(17,0): at System.Runtime.Serialization.Formatters.Tests.FormatterServicesTests.GetUninitializedObject_COMObject_ThrowsNotSupportedException()
          C:\git\runtime4\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(384,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

cc @akoeplinger @lateralusX

**Comment by akoeplinger** [comment]
@lateralusX does this seem like something that should work on netcore-mono on Windows?

**Comment by lateralusX** [comment]
So we have disabled COM support on netcore (all platforms), this is from winconfig.h

#ifndef DISABLE_COM
#define DISABLE_COM 1
#endif

and the will result in:

#ifdef DISABLE_COM
#define mono_class_is_com_object(klass) (FALSE)
#else
#define mono_class_is_com_object(klass) (m_class_is_com_object (klass))
#endif

so IsCOMObject will always return FALSE on netcore mono runtime.

Since this is a Windows only test, it won't show up on other platforms, but the same implementation should apply.

We could include some more logic where we could make IsCOMObject working for just COMObject type and make sure the rest of this test pass as well (maybe Windows only). I did similar things to make sure "minimal" COM works on Windows (basically IUnknown) even when DISABLE_COM has been defined, we could include some more needed things for this scenario to pass even when DISABLE_COM has been defined. So questions is if its worth doing that change for combability reasons of Type.IsCOMObject on Windows only?

**Comment by marek-safar** [comment]
The test will need adjustment for IsComSupported or something like that

**Comment by akoeplinger** [comment]
@marek-safar do you think we should support COM on Mono on Windows?

**Comment by marek-safar** [comment]
@akoeplinger I'm now aware of any ask to support COM with MonoVM

**Comment by HongGit** [comment]
@Benjie-Liu can you please work on this test issue?

**Comment by HongGit** [comment]
@ViktorHofer  is this still an issue for you?

**Comment by ViktorHofer** [comment]
Has something changed since I filed the issue? I don't see any failures in the CI logs for the last 7 days but that doesn't mean that this isn't happening anymore.

**Comment by HongGit** [comment]
Nothing has happened.  However, we couldn't repro this issue.  If this is not an issue anymore, we would like to close it out.

**Comment by akoeplinger** [comment]
@HongGit you'll need to remove the `ActiveIssue` from the test which currently disables it: https://github.com/dotnet/runtime/blob/463eeaed94837fdce3a6d4735803f0c7a4de7fe8/src/libraries/System.Runtime.Serialization.Formatters/tests/FormatterServicesTests.Windows.cs#L14


After that I can still repro the issue with these steps which make sure you use the Mono runtime instead of CoreCLR:

```
build.cmd mono+libs
dotnet build /t:Test /p:RuntimeFlavor=mono src\libraries\System.Runtime.Serialization.Formatters\tests
```

**Comment by HongGit** [comment]
> After that I can still repro the issue with these steps which make sure you use the Mono runtime instead of CoreCLR

@Benjie-Liu ?

**Comment by StephenMolloy** [comment]
I looked at this one to help churn through burndown, and it seems pretty straighforward. No COM on Mono ==> Don't run the COM test on Mono. So I updated the test, created a PR, and then... 

I thought to myself - I don't think we actually own Formatters. So... @GrabYourPitchforks? Here's a bug an a PR for quick review.
