### ISSUE TITLE
TextEncoder.FindFirstCharacterToEncodeUtf8 not being used anywhere.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#39829]
Discovered [this issue](https://github.com/dotnet/runtime/pull/38707#issuecomment-658418135) while working on ARM64 intrinsics optimizations for System.Text.Encodings.Web. While the method is public, it is also marked `EditorBrowsable.Never`. There are however unit tests consuming it.

A lot of the intrinsics optimizations for this project live in `FindFirstCharacterToEncodeUtf8` implementations, and as a result we're not seeing performance improvements when [benchmarking `TextEncoder.EncodeUtf8`](https://github.com/dotnet/runtime/pull/38707#issuecomment-658187505).

**Comment by tarekgh** [comment]
@GrabYourPitchforks just checking if you are triaging this area?

**Comment by GrabYourPitchforks** [comment]
This method was at one point used by _System.Text.Json_ ([see source](https://github.com/dotnet/corefx/blob/23db30b63d4945653f358ae4ac387c3f259fc9d0/src/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.Escaping.cs#L58-L66)). They've stopped using the API since then, but since it's a public API we need to keep it around in perpetuity.

What is this bug tracking? That we should stop making perf changes to this API? I'd be fine with that if that's the direction we want to go.

**Comment by eiriktsarpalis** [comment]
> What is this bug tracking?

Unlike `TextEncoder.Encode(string)` which depends on `FindFirstCharacterToEncode(char*)`, `TextEncoder.EncodeUtf8` does not make use of `FindFirstCharacterToEncodeUtf8`. The issue then is that `TextEncoder.EncodeUtf8` does not take advantage of any of the hardware intrinsics optimizations. If that's intentional or not necessary to improve on, I can close the issue.
