### ISSUE TITLE
FileSystemWatcher is missing Description Attribute 

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/runtime#39875]
* .NET Core Version: 
.Net SDK 5.0.100-rc.1.20367.2

* Have you experienced this same bug with .NET Framework?: 
No

**More Info**

1. All events of BackgroundWorker and FileSystemWatcher has no functional description.
2. BackgroundWorker's "Misc" item name is different from framework.
![image](https://user-images.githubusercontent.com/45864649/87918993-bef17380-caa9-11ea-9cc9-7203579a3156.png)

**Minimal repro:**

1. Create a winforms .NET core app.
2. Drag and drop a BackgroundWorker/FileSystemWatcher to form designer.
3. Select a property under the Misc item, and check the description of the function.
[WindowsFormsApp5.zip](https://github.com/dotnet/winforms/files/4946582/WindowsFormsApp5.zip)

**Expected behavior:**
The property under 'Misc' should has functional description.
![image](https://user-images.githubusercontent.com/45864649/87918831-85b90380-caa9-11ea-8027-4b02bcc23605.png)

**Actual behavior:**
The property under 'Misc' has no functional description.
![image](https://user-images.githubusercontent.com/45864649/87918823-83ef4000-caa9-11ea-842b-4ba8e639f067.png)

**Comment by merriemcgaw** [comment]
https://referencesource.microsoft.com/#System/services/io/system/io/FileSystemWatcher.cs,30 for reference to the Framework approach.

**Comment by danmosemsft** [comment]
@merriemcgaw does it have to be `IODescriptionAttribute` or can it just be `DescriptionAttribute`? For some reason we never ported the former. I'm guessing the designer doesn't care?

Here's where it should be
![image](https://user-images.githubusercontent.com/6385855/88351488-5acdea00-cd0b-11ea-9b59-bc73732a272d.png)

**Comment by danmosemsft** [comment]
As for BackgroundWorker, in .NET Framework it's System.SRDescriptionAttribute which is internal. So the fix is to apply the public System.ComponentModel.DescriptionAttribute onto those. (I think that reinforces that we don't need IODescriptionAttribute)

![image](https://user-images.githubusercontent.com/6385855/88351699-1000a200-cd0c-11ea-8a3b-33a9554220ae.png)

How important are these attributes, BTW? Some of the descriptions were a bit vacuous, eg., for PerformanceCounter.CategoryName it would show "Category name of the performance counter object."

**Comment by ericstj** [comment]
cc @safern who is looking at similar attributes in https://github.com/dotnet/runtime/issues/31428

I believe this is a duplicate / overlapping with https://github.com/dotnet/runtime/issues/39375
