### ISSUE TITLE
Make Data Type Static methods Extension Methods

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#39892]
Please make many of the static methods on:
string
char
byte
int
long
etc

be Extension methods so that instead of typing things like:

````
char.IsDigit(x)
````

I can simply type:
````
x.IsDigit()
````

**Comment by joperezr** [comment]
I don't think that this is something that we will want to take given that it would involve a lot of additional APIs for something that you can achieve very easily today and that people are already used to doing. If you could provide a rationale explaining why using the static versions might cause issues it might help build up a case for these.

**Comment by TonyValenti** [comment]
@joperezr The reason I was requesting the above is because of teh following:
1.  It makes the static methods more discoverable.
2.  It looks cleaner in fluent scenarios.

**Comment by joperezr** [comment]
I would really argue against your first point, first of all because if we set them as extension methods  it means that you might require to include a special namespace/nuget package in order to see them, and also assuming we add them so they are almost always visible then it would really pollute the API surface of types like string which will now have things like `isDigit` on it which will probably hide other members that people are trying to discover. I also don't think that discoverability is something we should be concerned with, as it is a pattern we have on the rest of the framework where we use static methods whenever trying to convert or interpret one type from another (for example the int.Parse methods). 

Anyway, those are my 2 cents, but I can also tag @bartonjs so that we can also find out his perspective in terms of our framework design guidelines for things like these.

**Comment by bartonjs** [comment]
We generally don't like having two different ways of doing the exact same thing with roughly the same level of complexity.  (Usually there's some nuance when there are two very very similar ways, or one is an ease of use for the other).

As far as extension methods go, these wouldn't meet the criteria (summarized from Framework Design Guidelines, 3rd edition, section 5.6)
* The target type isn't an interface
* There's no dependency problem
* The target type isn't generic (with the extension method restricted on T or non-generic)
* The target type isn't generic and very, very low level and we're trying to keep the vtable small (e.g. Span)

The fact that they're static methods that accept the type they're declared on means that way back in the early framework days someone decided they shouldn't be instance methods.  The reason may no longer hold, but then we're back to "don't have two ways to do the same thing without a good reason", so we wouldn't do this unless we were addressing a major overhaul of framework APIs to be more fluent-friendly.

I'm going to go ahead and close the issue, but if there's a compelling thing I'm missing we can always reopen it.
