### ISSUE TITLE
coreclr documentation questions - Virtual Stub Dispatch

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#39963]
I have been trying to follow the documentation for how Virtual Stub Dispatch works in the CLR. I understand that the documentation explains some features that aren't currently turned on in the CLR, but I am still interested in knowing how they work:

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/virtual-stub-dispatch.md

About halfway through, there is an example that shows what the resulting implementation table and slot map would be for the given C# class structure:

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/virtual-stub-dispatch.md#example

In the explanation below the example, it states the following:

"Thus, if I had an object of type B and I wished to invoke I.Foo, I would look for a mapping of I.Foo starting at B's slot map. Not finding it there, I would look in A's slot map and find it there. It states that virtual slot 0 of I (corresponding to I.Foo) is implemented by virtual slot **_0_**. Then I return to B's slot map and search for an implementation for slot **_0_**, and find that it is implemented by slot 1 in its own implementation table."

The highlighted items are what I have a question about: I don't see why it's not [virtual] slot 4. If someone could please explain the reasoning behind this to me, I would greatly appreciate it.

Additionally, shortly after the example there is a section regarding optimizations:

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/virtual-stub-dispatch.md#optimizations

I'm still trying to follow how mappings can be implied by the ordering in the implementation table. It would really help if that could be further explained.

Thank you very much

**Comment by jkotas** [comment]
cc @davidwrighton

**Comment by davidwrighton** [comment]
Your reasoning is correct. It should be virtual slot 4. As for the optimization question, as the logic for implementation entries handled by VSD is long gone, this is from fuzzy memories of the past, but I believe the way it once worked is...

1. Each MethodTable is annotated with the number of virtual slots that it describes
2. The implementation table is ordered in the same order as the metadata.
3. For each virtual method that is defined on a type which doesn't override a method on a parent type, then it is simple to know the mapping from vtable slot index to implementation slot as one can do math based on the number of slots present in the parent type.
4. Thus the technique would be to look at the DispatchMap to find out what the implementation slot is, but if no method is found in the DispatchMap, the method can be found by looking in the implementation table of the current type if the slot could not have been present on the parent type.

The effect was that a set of newslot virtual methods did not need to be present in the implementation map as long as they were contiguous, and at the start of the set of methods for a type.

**Comment by WizardBrony** [comment]
@davidwrighton 

Thank you so much for the explanation. I think I'm starting to understand, but I have a couple more questions. You said that the implementation table is ordered in the same order as the metadata. Does the metadata include all 3 different implementation table member types (newslot virtual, introduced non-virtual, and overriding virtual) or just one value representing the number of virtual slots for that type?

Also, I don't see yet how newslot virtuals can be eliminated from the DispatchMap. Going back to the VSD document's example, say I had an object of type B and I wished to invoke A.Bar, I would look for a mapping of A.Bar starting at B's slot map. Not finding it there, I would look in A's slot map. If A's newslot virtual methods weren't in its DispatchMap, how would it find A.Bar?

**Comment by davidwrighton** [comment]
Yes, the metadata includes all methods. See ECMA 335 Partition II for a description of the format.

For the lookup case, there are 3 types involved.

Type Object which has 4 Virtual slots (0-3)
Type A which has 6 Virtual slots (0-5)
Type B which has 7 Virtual slots (0-6)

When looking virtual function 5 by dispatch map in type B, the following steps will occur.

1. Look at the dispatch map for B. Do not find a mapping from slot 5 to anything. 
2. Look at the count of virtual slots in A. Determine that A could provide an implementation because slot 5 is a valid slot for type A
3. Look at the dispatch map for A. Since the mapping from slot 5 to slow 1 is an implied map entry. It isn't actually there
4. Look at the count of virtual slots in Object. Since Object does not have virtual slot 5, then this is an implied map entry.
5. Subtract 4 (the count of slots in type Object) from 5 (the slot index that is being looked up. This yields the number 1, which is the index into the implementation table of type A that should be used.
6. Using index 1 into the implementation table, find the A.Bar method.

**Comment by WizardBrony** [comment]
@davidwrighton Got it. It all makes sense now. Thank you again!
