### ISSUE TITLE
Optimize Math.Pow(x,y) for basic ranges

### ISSUE THREAD

**Issue by tafo** [dotnet/runtime#40081]
Hi,

I implemented a power function for basic ranges to have fun.

(0..9)^(0...9) &
(0..99)^(0...9) &
(0..999)^(0...9) &
(0..9999)^(0...9)

```csharp
public static double Power(double x, double y)
{
    var result = 1.0;
    var p = (int)y;
    while (p != 0)
    {
        if ((p & 1) == 1)
        {
            result *= x;
        }

        p /= 2;
        x *= x;
    }

    return y < 0 ? 1 / result : result;
}
```

Then compared its performance to the performance of Math.Pow(x,y) to check ...

But!

| Method | BaseRange | PowerRange |           Mean |        Error |       StdDev |
|------- |---------- |----------- |---------------:|-------------:|-------------:|
| **DotNet** |         **9** |          **9** |     **2,444.6 ns** |     **12.82 ns** |     **11.37 ns** |
|   Tafo |         9 |          9 |       639.8 ns |      3.23 ns |      3.02 ns |
| **DotNet** |        **99** |          **9** |    **31,418.2 ns** |    **177.88 ns** |    **166.39 ns** |
|   Tafo |        99 |          9 |     6,798.8 ns |     62.53 ns |     55.43 ns |
| **DotNet** |       **999** |          **9** |   **322,419.4 ns** |  **3,114.50 ns** |  **2,913.31 ns** |
|   Tafo |       999 |          9 |    68,344.1 ns |    310.25 ns |    290.21 ns |
| **DotNet** |      **9999** |          **9** | **3,187,568.0 ns** | **32,424.25 ns** | **30,329.66 ns** |
|   Tafo |      9999 |          9 |   681,957.3 ns |  3,970.06 ns |  3,713.59 ns |
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18362.959 (1903/May2019Update/19H1)
Intel Core i7-4720HQ CPU 2.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.302
[Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
Job-VUEIRA : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
Runtime=.NET Core 3.1  RunStrategy=Throughput  
```
The benchmark repository =>

https://github.com/tafo/math

Why it is faster than the .NET Math API?

**Comment by tannergooding** [comment]
> Why it is faster than the .NET Math API?

Simply put it is because your function doesn't compute `pow`, it estimates `pow`.

I gave a more in depth answer, with examples, of how floating-point works behind the scenes here https://github.com/dotnet/runtime/issues/39838#issuecomment-663558739. However for convenience a summary is that due to the internal representation and having finite precision, math on a computer may not work exactly the same as normal math (even with integers, where you have to be concerned with overflow). This means that `a + (b + c)` and `(a + b) + c` may compute different results even though in the strict mathematical sense they are identical operations.

The actual implementation of `pow` looks more like this (both are MIT License):
* https://github.com/amd/win-libm/blob/master/pow.asm
-or-
* https://github.com/ARM-software/optimized-routines/blob/master/math/pow.c

As you can see, it has to do a lot of additional checks, adjustments, and manipulation of the underlying representation to ensure it meets the IEEE 754 requirements, which is that the values must be taken as given, the operation is then computed as if to "infinite precision and unbounded range". The result is then rounded to the nearest representable value according to the current rounding mode.
* IEEE 754 is the standard that defines the behavior and representation of `float` and `double`

Some implementations take some shortcuts or allow some well-defined error for larger inputs and while these aren't truly IEEE compliant, they are close enough for almost all use-cases. For example the arm-optimized routines specifies:
```cpp
/*
Worst-case error: 0.54 ULP (~= ulperr_exp + 1024*Ln2*relerr_log*2^53)
relerr_log: 1.3 * 2^-68 (Relative error of log, 1.5 * 2^-68 without fma)
ulperr_exp: 0.509 ULP (ULP error of exp, 0.511 ULP without fma)
*/
```

I would recommend comparing the results of your implementation vs the official implementation and also comparing that to the result given by something like `Wolfram Alpha` to see where the differences come into play and what kind of errors are introduced by a simpler but fast implementation.

**Comment by tafo** [comment]
Thanks for the answer. I think, my question was not clear. Your answer is far away from what I focused on. Actually, it was about integers. Because the base and the exponent of the most power operations are between 0 and 100. 

I checked the .NET API again and realized that the power function of System.Numerics.BigInteger class is also implemented with the basic "square-and-multiply" logic. 

This is the benchmark result.

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
| DotNet | 4.416 ms | 0.0208 ms | 0.0194 ms |
| a Code | 4.775 ms | 0.0446 ms | 0.0418 ms |

So, no problem. 
Thanks.

**Comment by tannergooding** [comment]
If it is purely integer powers you are wanting to do, then doing a simple for loop is likely sufficient and for some values may be more accurate (if the result is greater than 2^53 for double or 2^24 for float). You don't really have to do any special tricks as the representation is 1-to-1 and you don't have any fractional portions to consider (or even really negative powers for that matter). However, you are likely to quickly run out of space and start overflowing, which is likely the biggest concern.

**Comment by tafo** [comment]
There are some decimal powers such as 0.777 ^ 777. 
But most of the numbers and exponents are integer.
I am just trying to optimize, even if the current performance is ok. 
But now I decided to check the repository of ARM. 
Thank you very much (:
