### ISSUE TITLE
CA1063: Remove IDisposable from the list of interfaces

### ISSUE THREAD

**Issue by lisberPontes** [dotnet/runtime#40196]
### Description

CA1063: Microsoft.Design : Remove IDisposable from the list of interfaces implemented by 'XXXXX and override the base class Dispose implementation instead.

Ok, so after reading the documentation Microsoft about this rule:

"Every unsealed type that declares and implements the IDisposable interface must provide its own protected virtual void Dispose(bool) method. Dispose() should call Dispose(true), and the finalizer should call Dispose(false). If you create an unsealed type that declares and implements the IDisposable interface, you must define Dispose(bool) and call it. For more information, see Clean up unmanaged resources (.NET guide) and Dispose pattern."

Is a basic set of rules that can and to some extent are easy to adopt among developers.

### Configuration

1) Define a base class MyBase that implements an interface such as IMyInterface;
2) IMyInterface implements IDisposable
3) Define a derived class MyDerive which inherits from MyBase class

4) Define a virtual implementation of Dispose() method in MyBase class
5) Do not override Dispose method on MyDerive class

### Regression?
No, it has been like this since day 1

### Other information

It shouldn't raise any CA1063 error for a scenario like the one described before, right ?

**Comment by KalleOlaviNiemitalo** [comment]
> CA1063: Microsoft.Design : Remove IDisposable from the list of interfaces implemented by 'XXXXX and override the base class Dispose implementation instead.

This warning seems to come from [legacy analysis](<https://docs.microsoft.com/visualstudio/code-quality/static-code-analysis-for-managed-code-overview?view=vs-2017> "Code analysis for managed code - Visual Studio | Microsoft Docs") rather than [Roslyn FxCop analyzers](<https://docs.microsoft.com/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2017> "Code analysis using Roslyn analyzers - Visual Studio | Microsoft Docs"), which use a [different wording](<https://github.com/dotnet/roslyn-analyzers/blob/39d189ab8b48b3811978edbafdc0aef190025f53/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx#L640-L642> "roslyn-analyzers/MicrosoftCodeQualityAnalyzersResources.resx at v3.0.0 · dotnet/roslyn-analyzers").

**Comment by lisberPontes** [comment]
Hi @KalleOlaviNiemitalo , thanks for your input. And [legacy analysis](https://docs.microsoft.com/visualstudio/code-quality/static-code-analysis-for-managed-code-overview?view=vs-2017) are no longer maintained, is that i?

**Comment by danmosemsft** [comment]
@lisberPontes thanks for the issue. Please can you reopen it in https://github.com/dotnet/roslyn-analyzers.
