### ISSUE TITLE
ConsoleLoggerProvider should work without an IOptionsMonitor

### ISSUE THREAD

**Issue by lukoerfer** [dotnet/runtime#40261]
## Background and Motivation

Instead of using the builder pattern with `LoggerFactory.Create(Action<ILoggingBuilder>)` it is possible to construct an `ILoggerFactory` via dependency injection, e.g. using Autofac:

``` csharp
builder.RegisterType<DebugLoggerProvider>().As<ILoggerProvider>().SingleInstance();
builder.RegisterType<LoggerFactory>().As<ILoggerFactory>().InstancePerLifetimeScope();
builder.RegisterGeneric(typeof(Logger<>)).As(typeof(ILogger<>)).InstancePerLifetimeScope();
```

`LoggerFactory` takes an `IEnumerable<ILoggerProvider>` and Autofac will automatically pass any registered `ILoggerProvider`. This works fine with (for example) `DebugLoggerProvider`, but gets complicated when using `ConsoleLoggerProvider`, because the latter only provides a constructor that requires an `IOptionsMonitor<ConsoleLoggerOptions>`. One solution for this is to actually register the dependencies from `Microsoft.Extensions.Options`:

``` csharp
builder.RegisterType<ConsoleLoggerProvider>().As<ILoggerProvider>().SingleInstance();
builder.RegisterGeneric(typeof(OptionsMonitor<>)).As(typeof(IOptionsMonitor<>));
builder.RegisterGeneric(typeof(OptionsFactory<>)).As(typeof(IOptionsFactory<>));
builder.RegisterGeneric(typeof(OptionsCache<>)).As(typeof(IOptionsMonitorCache<>));
```

Another solution may be to provide a fake implementation of `IOptionsMonitor<>`:

``` csharp
builder.RegisterType<ConsoleLoggerProvider>().As<ILoggerProvider>().SingleInstance();
builder.RegisterGeneric(typeof(FakeOptionsMonitor<>)).As(typeof(IOptionsMonitor<>));
```

However, those are workarounds and it should be possible to create a `ConsoleLoggerProvider` just based on some static `ConsoleLoggerOptions` or even based on the default options (just like calling `AddConsole()` on an `ILoggingBuilder`).

## Proposed API

```diff
namespace Microsoft.Extensions.Logging.Console
{
    [Microsoft.Extensions.Logging.ProviderAlias("Console")]
    public class ConsoleLoggerProvider : IDisposable, Microsoft.Extensions.Logging.ILoggerProvider, Microsoft.Extensions.Logging.ISupportExternalScope

+        public ConsoleLoggerProvider() { }
+        public ConsoleLoggerProvider(Microsoft.Extensions.Logging.Console.ConsoleLoggerOptions options) { }

    }
}
```

## Usage Examples

This change will allow developers to register / use a `ConsoleLoggerProvider` based on static options and without using `Microsoft.Extensions.Options`:

``` csharp
builder.RegisterType<ConsoleLoggerProvider>().As<ILoggerProvider>().SingleInstance();
builder.RegisterInstance(new ConsoleLoggerOptions() {
    IncludeScopes = true
});
```

## Alternative Designs

Out of the provided implementations of `ILoggerProvider`, the `BlobLoggerProvider` and the `FileLoggerProvider` (from `AzureAppServices`) both share the API of the `ConsoleLoggerProvider` and only have a single constructor that takes an `IOptionsMonitor`. The constructor `DebugLoggerProvider` does not take any arguments at all. The `EventLogLoggerProvider` provides three constructors, one without arguments, one that takes `EventLogSettings` and one that takes `IOptions<EventLogSettings>`. Thus the API is pretty inconsistent regarding the different approaches for the constructors and should be adjusted anyhow.

## Risks

The proposed API does not include breaking changes.

**Comment by KalleOlaviNiemitalo** [comment]
`Microsoft.Extensions.Logging.LoggerFactory` uses [`internal class StaticFilterOptionsMonitor`](https://github.com/dotnet/runtime/blob/53976d38b1bd6917b8fa4d1dd4f009728ece3adb/src/libraries/Microsoft.Extensions.Logging/src/StaticFilterOptionsMonitor.cs) to implement constructors that likewise don't require an `IOptionsMonitor<LoggerFilterOptions>` argument. If such a class is useful for logger providers too, then perhaps it could be promoted to a generic type in Microsoft.Extensions.Options instead of being internally reimplemented in each logger provider. The new constructors of logger providers would then create instances of that type.

```patch
 namespace Microsoft.Extensions.Options
 {
     public static class Options
     {
         public static readonly string DefaultName;
         public static IOptions<TOptions> Create<TOptions>(TOptions options)
             where TOptions : class;
 
+        // Place this method in the same class as DefaultName.
+        public static IOptionsMonitor<TOptions> CreateMonitor<TOptions>(TOptions options)
+            where TOptions : class;
     }
 
     public class OptionsWrapper<TOptions> : IOptions<TOptions>
         where TOptions : class
     {
         public OptionsWrapper(TOptions options);
         public TOptions Value { get; }
     }
 
+    public class OptionsMonitorWrapper<TOptions> : IOptions<TOptions>
+        where TOptions : class
+    {
+        public OptionsMonitorWrapper(TOptions options);
+        public TOptions CurrentValue { get; }
+        public TOptions Get(string name);
+        public IDisposable OnChange(Action<TOptions, string> listener);
+    }
 }
```

However, this might be a bad idea. It is not clear to me whether `OptionsMonitorWrapper<TOptions>.Get(string)` should throw if called with a string other than `Options.DefaultName`. In `StaticFilterOptionsMonitor`, it does not matter because the type is internal and `LoggerFactory` never calls that method.

Alternatively, make the type generic but keep it internal and share the source file to each logger provider project.

**Comment by davidfowl** [comment]
This is a general issue when we design things to be used inside and outside of a dependency injection system. While I agree it should be nicer to create these things by manually, that's not the scenario shown above (you've made it work by injecting the wrapper).

> The proposed API does not include breaking changes.

When adding constructors, it's important to consider the DI scenario and how constructor selection works.

> The EventLogLoggerProvider provides three constructors, one without arguments, one that takes EventLogSettings and one that takes IOptions<EventLogSettings>. Thus the API is pretty inconsistent regarding the different approaches for the constructors and should be adjusted anyhow.

Right, this should be consistent. When we inject options we should be using IOptionsMonitor\<*Options\> so that change notification works.

If we can come up with a design that doesn't add constructor hell to these types as they evolve, I'll be happy 😄

**Comment by maryamariyan** [comment]
Closing issue since we don't plan to support ConsoleLoggerProvider without IOptionsMonitor

**Comment by maryamariyan** [comment]
> Close this as "not planned" rather than "completed" then?

yes
