### ISSUE TITLE
[Proposal] string.NormalizeLineEndings

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#40315]
__Edit by @GrabYourPitchforks on Wed 31 Mar:__ Fuller API proposal at the comment https://github.com/dotnet/runtime/issues/40315#issuecomment-811358895.

-----

## Background and Motivation

This is a very common issue developers run into especially on cross platform. When we handle a string which we don't created ourselves it might have a different line ending as expected. On Windows it can be a `\n` instead of `\r\n` and on Linux vice versa. On Linux its a bit easier as the workaround can be a simple `string.Replace("\r\n", "\n")` while on Windows we have to use Regex (because `"\r\n".Replace("\n", "\r\n")` obviously does something else than we are looking for) and if we don't want to go down the line by reading char by char ourselves. In order to eliminate the issue on all platforms there should be a single API.

Name and place of the API are free to change.

## Proposed API
```  C#
namespace System
{
    public sealed class String
    {

        //
        // Normalizes all line endings to the line ending on which platforms it runs
        //     
        public string NormalizeLineEndings(this string s) {
		#if !PLATFORM_UNIX 
			//Replace all line endings with \r\n
		#else
			//Replace all line endings with \n
		#endif
		}
	}
}
```

## Usage Examples

``` C#
public class MyPublicAPI
{
	public string DoStuff(string content)
	{
		foreach(string line in content.NormalizeLineEndings().Split(Environment.NewLine))
		{
		}
	}
}
```
``` C#
public class MyPublicAPI
{
	public string ShowMessage(string message)
	{
		Console.WriteLine(message.NormalizeLineEndings())
	}
}
```

## Alternative Designs

None

## Risks

None

**Comment by GrabYourPitchforks** [comment]
Seems reasonable. Wonder if we should do this on `StringBuilder` as well.

Behavior would be to find isolated `\r`, isolated `\n`, and grouped `\r\n` and replace them all with `Environment.NewLine`.

**Comment by Gnbrkm41** [comment]
Would it also be a possible scenario for someone to normalise the line ending to something that isn't `Environment.NewLine`? e.g. mixed `\r\n` and `\n` to all `\n` on Windows, non-Console environments.

**Comment by GrabYourPitchforks** [comment]
@Gnbrkm41 You mean something like below?

```cs
public sealed class string
{
    // if lineEnding == null, use Environment.NewLine; otherwise use provided lineEnding as a replacement
    public static string NormalizeLineEndings(string input, string? lineEnding = null);
}
```

**Comment by Gnbrkm41** [comment]
Ooh.... That's.... Interesting. Never thought about allowing something that isn't CR, LF or CRLF. Doesn't sound too bad, but I suppose the folks in API review will figure out.

**Comment by GrabYourPitchforks** [comment]
## API proposal

```cs
public class String
{
    public string NormalizeLineEndings(string? lineEnding = null);
}

public static class MemoryExtensions
{
    // mimics the existing methods 'EnumerateRunes'
    public System.Text.SpanLineEnumerator EnumerateLines(this ReadOnlySpan<char> span);
    public System.Text.SpanLineEnumerator EnumerateLines(this Span<char> span);
}

namespace System.Text
{
    // mimics the existing type 'SpanRuneEnumerator'
    public ref struct SpanLineEnumerator
    {
        public ReadOnlySpan<char> Current;
        public SpanLineEnumerator GetEnumerator();
        public bool MoveNext();
    }
}
```

## Behaviors \& usage

_NormalizeLineEndings_ searches for occurrences of `<CR>`, `<LF>`, and `<CR><LF>`, replacing such occurrences with the value of the _lineEnding_ parameter. If _lineEnding_ is _nullptr_, defaults to _Environment.NewLine_ (the newline sequence for the current platform).

__Examples:__

```cs
string s = GetString(); // may contain a mix of CR, LF, and CRLF

// Normalize line endings to Environment.Newline (all calls below are identical)
string normalized = s.NormalizeLineEndings();
string normalized = s.NormalizeLineEndings(null);
string normalized = s.NormalizeLineEndings(Environment.NewLine);

// Normalize line endings to <CR><LF>, regardless of the current platform
string normalized = s.NormalizeLineEndings("\r\n");

// Normalize line endings to <LS> (not common)
string normalized = s.NormalizeLineEndings("\u2028");

// Remove all line endings by normalizing them to [empty]
string normalized = s.NormalizeLineEndings("");
```

During span-based enumeration, the _Current_ property will refer back to a substring within the original provided string. The enumerator does not give newlines at the beginning or the end of the input string any special consideration, which may result in empty spans being seen during enumeration.

__Examples:__

```cs
ReadOnlySpan<char> span = "Hello\nworld!\r\n";

foreach (var line in span.EnumerateLines())
{
    // On the first loop, line := span[0..5] ("Hello")
    // On the second loop, line := span[6..12] ("world!")
    // On the third loop, line := span[14..14] ("")
    // Loop then terminates
}
```

## Discussion

This API is useful for https://github.com/dotnet/runtime/issues/50044 and other scenarios where text intended for user display may be transmitted across the wire, where the host system must account for any newline differences between itself and the remote system.

[The Unicode Standard, §5.8](https://www.unicode.org/versions/Unicode13.0.0/ch05.pdf), provides the canonical list of official Unicode-recognized newline sequences: `<CR>`, `<LF>`, `<CR><LF>`, `<NEL>`, `<VT>`, `<FF>`, `<LS>`, and `<PS>`. However, in practice, [very few systems](https://en.wikipedia.org/wiki/Newline#Unicode) use anything other than `<LF>` or `<CR><LF>` for this purpose. Most internet protocols recognize only these two sequences plus `<CR>` for compatibility.

Given that our use case involves programmatically generated strings and really involves smoothing over `Environment.NewLine` differences between platforms, I don't believe our API needs to account for these uncommon occurrences. We can get away with detecting only `<CR>`, `<LF>`, and `<CR><LF>`. We do not need to provide customization where the caller can specify the exact list of sequences they want to search for. Such callers are probably performing more advanced text processing and likely have other considerations that we haven't accounted for in our basic `string` APIs. If we ever were to provide a Unicode-compliant version of this API (perhaps in the _System.Text.Unicode_ namespace), I expect that API would detect the full breadth of Unicode-recognized newline sequences instead of just the three we special-case here.

**Comment by GrabYourPitchforks** [comment]
I incorporated some feedback from subject matter experts and marked this API ready for review.

**Comment by bartonjs** [comment]
* Instead of default parameter, make a parameterless overload and make the parameter non-nullable
* The word "Normalize" is overloaded in this space, suggest ReplaceLineEndings instead of NormalizeLineEndings
* Suggest `replacementText` instead of `lineEnding` in the ReplaceLineEndings method.
* If a char overload seems reasonable, go ahead and add it, too.

```C#
namespace System
{
    partial class String
    {
        public string ReplaceLineEndings() => ReplaceLineEndings(Environment.NewLine);
        public string ReplaceLineEndings(string replacementText);
    }
    partial class MemoryExtensions
    {
        public System.Text.SpanLineEnumerator EnumerateLines(this ReadOnlySpan<char> span);
        public System.Text.SpanLineEnumerator EnumerateLines(this Span<char> span);
    }
}
namespace System.Text
{
    public ref struct SpanLineEnumerator
    {
        public ReadOnlySpan<char> Current;
        public SpanLineEnumerator GetEnumerator();
        public bool MoveNext();
    }
}
```
