### ISSUE TITLE
System.Environment.GetFolderPath (Environment.SpecialFolder.ApplicationData) Is the wrong path on MacOS

### ISSUE THREAD

**Issue by Clancey** [dotnet/runtime#40353]
### Description

When you call the following code, it is correct on Windows and Linux, but MacOS you get the linux path
`var path = System.Environment.GetFolderPath (Environment.SpecialFolder.ApplicationData) `
paths actual value = `~/.config `
It should be` ~/Library/Application Support`
### Configuration

MacOS

**Comment by lewing** [comment]
The code is here https://github.com/dotnet/runtime/blob/b5705587347d29d79cec830dc22b389e1ad9a9e0/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L100 and there are OSX specific overrides for other folders.

**Comment by danmosemsft** [comment]
Thanks @Clancey . Does ~./config have any plausible meaning on Mac, ie what is the chance a change would break apps?

I assume Local Application Data needs a change also?

**Comment by Clancey** [comment]
A change shouldn't break existing apps. It would just treat it as a fresh install since the user folder location would change.

**Comment by Clancey** [comment]
There are 2 folders on MacOS, `/Library/Application Support/` and `~/Library/Application Support`. Global vs User. Not sure which should map where.

**Comment by migueldeicaza** [comment]
`.config` is an [XDG-istm](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which is a Linux-only thing.   MacOS predates XDG.

**Comment by SingleAccretion** [comment]
@Clancey If you want to do this in a backward-compatible manner (aka the only feasible way), you would need to propose some new API and optionally obsolete/hide the old one. For example, there could be a new overload of `Environment.GetFolderPath()` with a new enum argument (`CrossPlatSpecialFolder`) and a new behavior that would be "correct". This would be necessary because adding new members to `SpecialFolder` is also a breaking change (arguably even more breaking than the change of the macOS folder). This of course runs into problems of API duplication vs API obsoletion and all the headaches that causes, so I could see this actually being less desirable than the current behavior.
