### ISSUE TITLE
HttpClientHandler redirect bug

### ISSUE THREAD

**Issue by cubesnyc** [dotnet/runtime#40367]
According to msdn documentation:

[HttpClient uses HttpWebRequest under the hood](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8)

[HttpWebRequest is supposed to attach the referer header if allowautoredirects is set to true](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.referer?view=netframework-4.8)

However, it seems that the referer header is never attached on a redirect when examining the requests with fiddler. 

Quick reproducible test code: 
```
            var _httpClient = new System.Net.Http.HttpClient();
            var _cookieContainer = new CookieContainer();
            var _httpClientHandler = new HttpClientHandler();
            _httpClientHandler.AllowAutoRedirect = true;
            _httpClientHandler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
            _httpClientHandler.CookieContainer = _cookieContainer;
            _httpClientHandler.UseCookies = true;
            _httpClient = new System.Net.Http.HttpClient( _httpClientHandler );
            _httpClient.DefaultRequestHeaders.ExpectContinue = false;
            
            await _httpClient.GetAsync( "https://httpstat.us/302" );
```

**Comment by ManickaP** [comment]
Your link points to 4.8 Framework documentation. Is the bug happening on .NET Framework? If so, please file it in developer community: https://developercommunity.visualstudio.com/spaces/61/index.html. This repository is only for .NET Core.

Note that `HttpClient` on .NET Core (since 2.1) uses `SocketsHttpHandler`: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1#httpclient-and-net-core.

Feel free to reopen if you encounter problems on .NET Core.
