### ISSUE TITLE
Survey: Native AOT

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#40430]
Performance has been a key .NET feature. The existing options for optimizing published applications work well for most scenarios that .NET targets today.

Some of you asked us to consider adding native AOT compilation option with distinctly different characteristics. The distinctly different characteristics of native AOT come with tradeoffs such as lower compatibility that are explained in detail in [.NET Runtime Form Factors](https://github.com/dotnet/designs/blob/master/accepted/2020/form-factors.md#native-aot-form-factors). We’ve created a survey to help us better understand the native AOT use cases.

We would appreciate your feedback so we can work on creating the right plans for future. If you don’t supply contact details, then responses will be anonymous.

Survey: https://www.surveymonkey.com/r/7THQK5K

Thank you for your time!

**Comment by Gnbrkm41** [comment]
Looks like a typo - `* 9. Which of these tasks are apart of your production debugging workflow? (Please select all that apply)` Maybe it should be "a part of"?

**Comment by Sergio0694** [comment]
I'm **so** happy to see this issue! 😄🚀

Question: for UWP devs that have worked with the .NET Native toolchain, should we answer the survey just saying we haven't used CoreRT before, or since .NET Native has many similarities (and some shared code too?) with CoreRT, should we just mention this in the notes and then reply the other CoreRT questions just with respect to our experience with .NET Native? 🤔

**Comment by jeffschwMSFT** [comment]
@Sergio0694 thanks for the UWP question.  I agree, I think it makes sense to mention that in the notes and reply to the use corert if you had used the open source version.

**Comment by rgwood** [comment]
Thanks for posting this survey! 

I was also confused about how to answer certain questions as a UWP dev who has only used .NET Native. I have a number of opinions about UWP’s .NET Native toolchain but I didn’t really see a place to write them down. Totally fine if that’s outside the scope of this survey but it might be worth clarifying.

I also suspect “because .NET Native is the default for UWP release builds and required in the Store” is probably the most common reason why people use AOT but it’s not one of the pre-populated answers for question 5.

**Comment by jmacato** [comment]
Thanks for including Avalonia in the GUI options :) We've experimented with CoreRT+Avalonia before and the results were gorgeous :D though we havent maintained compat since it's been 2 yrs then...

**Comment by texasbruce** [comment]
AOT mostly matters in GUI apps. That's where it needs focus. I don't see webapp, services, etc. needing that

**Comment by Vincenz099** [comment]
An often forgotten part of .net is game development, a lot of platforms do not allow a JIT to run, think of Consoles or IOS devices.
It is very important for the future of game development to get .net native AOT as a first-class citizen of the .net ecosystem.
Some game engines rolled their own AOT (for example Unity does with il2cpp) but it is an absolute trainwreck. so an official solution would be more than welcome. It could be a industry changing event.

**Comment by prajaybasu** [comment]
I'd like full/partial AOT for game dev (unity), serverless deployments and client apps (web/desktop/mobile/console) to be supported/standardized by the .NET platform as a "first class" compilation option instead of being fragmented into a sea of different names and runtimes (IL2CPP, Uno/Mono WASM, .NET Native, CoreRT, ReadyToRun, etc.).

**Comment by phil-harmoniq** [comment]
I disagree with the statement saying webapps wouldn't benefit from this. AOT would help greatly with serverless workloads (aka Azure Functions). Not to mention the benefits from startup time for CLI tools.

**Comment by pjmlp** [comment]
I have answered the survey, but to be honest I don't get this continuous asking of surveys since .NET Core 1.0 started, without a clear direction where things are going.

.NET Native is what .NET should have been all along, back when Ext-VOS project started, and there is the experience from Singularity and Midori that you guys can certainly relate to, or even get some internal servers with them going on.

Even Java has decided to catch up with its missing AOT capabilities the team isn't asking what workloads we want to have it working.

We hardly use NGEN, because since .NET release its code quality generation was never improved and the deployment workflow is a pain versus other AOT compiled languages.

So if going forward, AOT is dropped again from .NET consider that all the competition in managed languages is now focusing in AOT toolchains, and they also don't ask which workflows we would like to use the compiler.

I want to see .NET continuing to flourish and being the first option regardless of the scenario, and if anything to take over workflows where Microsoft still forces us to use C++ alongside .NET, which other AOT compiled languages don't have issues with.

**Comment by texasbruce** [comment]
> I have answered the survey, but to be honest I don't get this continuous asking of surveys since .NET Core 1.0 started, without a clear direction where things are going.

I think it's a great thing that MS is trying to listen to the community, rather than just dictating what we want.

**Comment by nxrighthere** [comment]
@jkotas I noticed that two different links for this survey are spreading, is that okay?
https://www.surveymonkey.com/r/7THQK5K
https://www.surveymonkey.com/r/SQV8JQK

**Comment by pjmlp** [comment]
@ texasbruce  ask the people that answered similar surveys regarding WCF and EF tooling support how much it has helped.

**Comment by Symbai** [comment]
For me the only acceptable AOT solution is when it generates a true native application with no JIT at all in release mode (no side-by-side solution alias ready-to-run) and when it works on all .NET projects developers are working on. This specifically includes Winforms and WPF. In best case it should then also work standalone without any runtime dependencies without bloating itself up from 3mb to 80mb.

_I've also written applications in Delphi and it bugs me to see I just compile and then ship my single Delphi executable elsewhere and it just runs. And its just faster. Same applies to a C++ application when compiled in a specific way. And you can still debug both applications and both applications still provide a useful stacktrace/dump when you decide to include the PDB. But for security reasons you can also decide to NOT include it which then also just works fine. It bugs me to ask myself why cannot we have that with C#? When I heard of AOT plans I expected THIS._

**Comment by VladimirAkopyan** [comment]
I always see issues with reflection mentioned a lot, and I believe that it actually does not matter that much if ASP.net core produces a big executable. 

Most of the places where AOT is a hard requirement are things like CLI tools, games and UI applications, they can be picky about which libraries to include and can sidestep some of reflection issues. The priority should be to enable "clean slate" applications.

**Comment by stefan-schweiger** [comment]
> I always see issues with reflection mentioned a lot, and I believe that it actually does not matter that much if ASP.net core produces a big executable.

With the release of Blazor WebAssembly I think executable size and also execution speed are going to matter very much and it could greatly benefit from AOT. But for whatever reason it wasn't even mentioned specifically in the survey.

**Comment by maximilien-noal** [comment]
Yes, pretty please ! I was considering using Rust or CoreRT in order to keep the memory safety and gain native speeds & have my code be native callable. But it would be fantastic to have AOT in .NET, as it is incredibly rich and powerful and Rust, while fantastic, is not easy to transition to.

**Comment by jkotas** [comment]
> @jkotas I noticed that two different links for this survey are spreading, is that okay?

Yes, we use different SurveyMonkey links for different posts. All links point to the same survey. It allows us to see how the distribution of responses varies depending on where people found the survey.

**Comment by amerkoleci** [comment]
For gamedev we need this, i suspended working on my game engine https://github.com/amerkoleci/alimer_sharp in favour of native engine using c++, i maintain bindings for DirectX ans vulkan as well, performance is needed here

**Comment by john-h-k** [comment]
> For gamedev we need this, i suspended working on my game engine https://github.com/amerkoleci/alimer_sharp in favour of native engine using c++, i maintain bindings for DirectX ans vulkan as well, performance is needed here

Identical scenario here 😄, except I didn't suspend it . I like AOT both for the better startup times but also (and in my case, more importantly), the opportunity to have more optimised code - I am fine with a 50% increase in build times for a 10% speedup, which obviously isn't really the attitude of a JIT

**Comment by PathogenDavid** [comment]
> I am fine with a 50% increase in build times for a 10% speedup, which obviously isn't really the attitude of a JIT

This is actually one of the big secondary reasons I want AOT in .NET instead of switching to a different ecosystem. I am totally spoiled by the speedy compile times of large .NET projects compared to large C++ or Rust projects.

I want JIT for the fast iteration during development, but AOT once I'm shipping something to my customers.

**Comment by josephmoresena** [comment]
I had use CoreRT create cross platform (and cross platform) Native libraries.

**Comment by swordday** [comment]
AOT w/ static linking is urgent needed for game engines in iOS and console platform which disable jit, and also want multiple aot compile modes: 
1. full aot
2. hybrid aot which support jit + aot or interpreter + aot run mode
hybrid aot is really important for game industry, it can be game changer

**Comment by srxqds** [comment]
> AOT w/ static linking is urgent needed for game engines in iOS and console platform which disable jit, and also want multiple aot compile modes:
> 
> 1. full aot
> 2. hybrid aot which support jit + aot or interpreter + aot run mode
>    hybrid aot is really important for game industry, it can be game changer

like mono on iOS platform, aot+interpreter run mode.

**Comment by alper-atay** [comment]
Full Aot, single exe, independent runtime and clipping unnecessary codes it definitely makes me kreygasm XD

**Comment by wizardars** [comment]
I've been waiting for this question for 10 years. Damn it, I have 5 cool projects that are gathering dust on the hard drive, because if I release them, any child can reverse them and sell them as their own. Yesterday a jerk tried to hire me to fix bugs in a stolen program on .Net. It's just wonderful.

**Comment by sebas77** [comment]
I have developed Robocraft, Cardlife and Gamecraft with Unity on a PC platform and never needed to use IL2CPP unless required by the platform (Xbox one in this case), not even for the game servers. I personally would see a mix of JIT compilation and a solution like Burst (which does a better job than I can ever do using explicit intrinsics) as more than enough when performance is necessary. However, I understand that AOT is necessary for the platforms that require fully native code and for those platforms where hardware resources are precious. I understand how the .net platform developers can have mixed feelings about AOT, but I don't think it's an option if we want it to see adopted more broadly in game development.

**Comment by jpapp05** [comment]
We develop high-performance, high-scalability financial/scientific simulators.   Our simulations can run anywhere from a few minutes to many days depending on the complexity of the model the user creates.   

Because of the nature of our simulation software, startup times are almost never a concern, as well as software/binary sizes.  For that matter, neither is the time it takes to install the product.   For example, it would be completely acceptable to us, if compilation were part of installation, even if such a process took a long time.

I would say that about 25% of the code during a run is dynamically created, so a hybrid approach would be preferred; some combination of AOT and JIT compilation.  If the dynamic bits had to be interpreted, I think much of the benefits of AOT would be diminished, at least in our use case.

The GC is our number one issue keeping us from achieving higher scalability (e.g. once we get around 44 cores).  Having the compiler be able to do more in-depth inter-assembly optimizations, aggressive in-lining, and escape analysis may allow for more short-lived object to be allocated on the stack instead of the heap.

There are many places in our code-base where JIT code quality becomes a bottleneck particularly with register allocations and dealing with many structures.  This forces us to write code to manipulate the JIT compiler to do the right thing (a tug-of-war that is fragile, obfuscating, and hard to maintain) or drop to native code (and we lose much of benefit from lack of inlining and overhead from GC/PInvoke transitions).   

Sometimes small improvements to code quality can make crazy wins over the course of a model that runs for hours across numerous cores.  To us, the JIT has become a bit fragile (even less deterministic) with performance, as our code base changes with development.  Our hope would be that an AOT compiler could take much more time in compiling and generating much higher quality code, reducing some of these unnecessary performance fluctuations, and allow us to keep more of our code base in C#.
 
In general, I would love to see move invested both in JIT and AOT technologies.

**Comment by davidfowl** [comment]
cc @AndyAyersMS

**Comment by RalfKornmannEnvision** [comment]
> AOT w/ static linking is urgent needed for game engines in iOS and console platform which disable jit,

I totally agree here. As we are in need of a solution for this problem (C# code running on game consoles for a non Unity project) we are using a Mono-AOT based tool chain. But it has some serious limitations and doesn't perform that well. 

Therefore we are looking into getting CoreRT running on 3 poplar game consoles (XBox One; PlayStation 4 and Nintendo Switch). An initial prof of concept show that it actually works (still with some limitations) but already with an significant run time performances improvement compared to the Mono based solution.

But with the NDA situation around game consoles official support for this use cause is properly even more far fetched than getting official native AOT in the first place.

**Comment by AndyAyersMS** [comment]
> To us, the JIT has become a bit fragile (even less deterministic) with performance, as our code base changes with development.

@jpapp05 I would love to hear more about your app, and the above issue specifically, as it's one of my key concerns. Feel free to contact me offline (via email in profile) if that helps.

**Comment by jpapp05** [comment]
Hi @AndyAyersMS, that would be great.   I'll contact you offline as I can talk a bit more freely but I'm happy to post back any summary from our discussions for the benefit of others.

**Comment by movedoa** [comment]
Don't know if this is even a problem but just to mention it here.
An important feature for us would be the ability to dynamically load und unload native assemblies at runtime.

**Comment by john-h-k** [comment]
@movedoa see the `NativeLibrary` APIs <https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.1>

**Comment by jcbeppler** [comment]
My biggest problem is that usually .NET can be easily decompiled, except with UWP Native, at least as far as I tested (I hope to be right). Not in a "normal" company mindset, someone will put a lot of IP in a project which can be easily decompiled.
Linux is cool ok, but all desktop applications are for Windows in the enterprise world. 

Maybe to make the life easier, put a checkbox which says:
**NATIVE COMPILATION (WORKS FOR WINDOWS 10 DESKTOP ONLY!)**
Man, do that and I don't care about AOT anymore. If it works for ASP.NET Core, cool! If not, I really don't care. 

By the way, thanks for creating the issue asking and making the survey, you did a great job because you are asking the opinion from people who uses the technology in their jobs. I think (in fact I'm sure) you still miss tons of desktop developers opinions who usually don't get involved into this things on Github. Not everyone remembers (or knows) that .NET code can be easily decompiled and I'm sure their bosses would go nuts if they knew :grin:.

**Comment by MostHated** [comment]
> Not everyone remembers (or knows) that .NET code can be easily decompiled

Shhh... The fact that Rider does this for you automatically is amazing when I am trying to figure out how something works behind the scenes in Unity or 3rd party packages.

**Comment by pjmlp** [comment]
@jcbeppler  You are wrong, that is a common misunderstanding of bytecode vs native, it is just a matter of having the right tools.

https://www.hex-rays.com/products/decompiler/compare/compare_vs_disassembly/

Hex-Rays is just a possible solution, there are others to choose from.

**Comment by jcbeppler** [comment]
@pjmlp I know the difference between decompile vs disassembly. I cannot do anything against disassemblying my software but native compilation can make the software much more secure because the person cannot do a very simple decompilation. A disassembled software will definitely look weird and the disassembled code may not even run correctly.

**Comment by Symbai** [comment]
> 
> 
> @jcbeppler You are wrong, that is a common misunderstanding of bytecode vs native, it is just a matter of having the right tools.

Currently a .NET program decompiled reveal the whole source code. This even includes all method names and variable names. This is cool for debugging and allows us to have a "readable" stacktrace when an exception occurs. However its a huge security flaw and a reason why there is a huge market for .NET obfuscators.

A native application can be disassembled. But it does not goes down to reveal its full C++/Delphi etc. source code (there are some tools which tries to rebuild this source code but the results are horrible). What you get is assembler code and control flow charts at most. If you are lucky and it ships with symbol file you also get the function names but in release mode this symbol file is usually not included, again for security purpose.

We can lose ourselves into details talking about how native code is a real protection. In my opinion its not a protection in terms of cracking (although thanks to full full method / variable names and full C# source generation a license check can be removed without requiring any special knowledge) or debugging, but a protection against stealers. Tools like dnSpy can even export the .NET application into a full VS project by a SINGLE CLICK. There is no such tool that works the same way for native code. So for commercial applications it would be a huge win to generate native code, besides of the fact that they no longer have to pay thousands of dollars a year for something that just renames all of the methods and variables in the final application.

I'm curious about the result of this survey. Are there any plans to make them public on how people voted?

**Comment by pjmlp** [comment]
@Symbai It is not a protection against anything, as any Android developer that has tried to use the NDK as means to protect their IP will tell you. The applications that you briefly mention, can do the same with single click, and even though they usually assume C or C++ code as original source code, they are good enough to steal your algorithms.

I want AOT, for scenarios where .NET will lose long term against Rust, Go, Swift, C++, Java (GraalVM), desktop, console, and mobile/IoT applications where startup time is really important, there are high constraints on memory usage and speed loss due to JIT on Assembly load is not tolerable, just like on some ASP.NET scenarios AOT code might be relevant when one is scaling their 100 K8S pods instances.

On the other side, I also find relevant to keep the JIT capabilities, and improve them as well, on scenarios where JIT is the way to go.

There are plenty of languages that offer both compilation models, letting their users to pick and chose depending on the situation, so basically lets keep JIT around, and improve the AOT story into .NET Native direction, while forgetting about the timid attempt named NGEN.

**Comment by jcbeppler** [comment]
> @Symbai It is not a protection against anything, as any Android developer that has tried to use the NDK as means to protect their IP will tell you. The applications that you briefly mention, can do the same with single click, and even though they usually assume C or C++ code as original source code, they are good enough to steal your algorithms.

Stealing an algorithm I can live with, but not what .NET allow today (e.g. WPF), where a person have your complete application beautifully and easily ready to run as a VS project. I think UWP with Native compilation does a good job, if someone wants to disassemble it, ok, good luck! I will always use Native compilation, no matter what. Android world I can't talk about, tried AOT with Xamarin Forms one time and it really didn't work as I expected.

**Comment by peter-dolkens** [comment]
> I think UWP with Native compilation does a good job, if someone wants to disassemble it, ok, good luck! I will always use Native compilation, no matter what. Android world I can't talk about, tried AOT with Xamarin Forms one time and it really didn't work as I expected.

Spoiler - the people that are trying to get at your source are probably trying to improve/extend/integrate with you, not rip you off. If they're trying to rip you off, then your metrics are really silly.

If I write a book, then get someone to translate it into Japanese before I publish it - I might think I'm really clever, because I don't understand Japanese, and neither do any of my friends. The reality is though, there's entire countries out there who can read that book - and I'm doing nothing more than fooling myself if I pretend otherwise.

I say this as a developer who had no experience with disassembled native binaries, and decided to reverse engineer the encryption and data formats on Star Citizen.

It took me, someone with *zero* prior experience, two weeks to go from nothing, to having a program that can not only decrypt their encrypted data files, but also convert their proprietary data formats into XML/JSON.

After those 2 weeks - I might not have your complete application ready to run as a VS project - but I also realize that I don't need to. It's far simpler to just inject my own code into the existing application, and not have to deal with all their code.

**Comment by ihlong** [comment]
Cloud Native and WPF Must be AOT.
Windows client no runtime !   no JIT

**Comment by jeffschwMSFT** [comment]
The results of the survey have been posted - https://github.com/dotnet/runtime/issues/41522.  We are now in the process of following up with people that provided their contact information and have some additional follow-up questions.

**Comment by lateralusX** [comment]
> > AOT w/ static linking is urgent needed for game engines in iOS and console platform which disable jit,
> 
> I totally agree here. As we are in need of a solution for this problem (C# code running on game consoles for a non Unity project) we are using a Mono-AOT based tool chain. But it has some serious limitations and doesn't perform that well. 
> 
> Therefore we are looking into getting CoreRT running on 3 poplar game consoles (XBox One; PlayStation 4 and Nintendo Switch). An initial prof of concept show that it actually works (still with some limitations) but already with an significant run time performances improvement compared to the Mono based solution.
> 
> But with the NDA situation around game consoles official support for this use cause is properly even more far fetched than getting official native AOT in the first place.

@RalfKornmannEnvision Are you using the Xamarin Xbox One/PS4 Mono ports and LLVM codegen?

**Comment by RalfKornmannEnvision** [comment]
> @RalfKornmannEnvision Are you using the Xamarin Xbox One/PS4 Mono ports with LLVM codegen?

@lateralusX As the integration was done by someone else I don't know any detail. But as far as I know they used the mono ports that are provided for the XBox One/PS4 and made a simple port for the Switch. themself.

**Comment by lateralusX** [comment]
@RalfKornmannEnvision Would be great to get in contact and discuss the experience related to this. The LLVM codegen has (depending on project) very positive performance effects on the generated code so if that was not used (needs to be enabled) there is normally a lot to gain by just enabling that. Are you on the DotNetEvolution discord server, if so maybe we could have an offline discussion there related to this?

**Comment by RalfKornmannEnvision** [comment]
@lateralusX I am pretty sure the team members who worked on this have enabled the LLVM codegen and tried other things. Their last statement before moving on to another project was that this is the best they could do.

As part of my investigation I build a benchmark with the core component using Xamarin Android and run it on a Tegra X1 based device to see if we lost performances because of an issue with the our custom Switch port of Mono. Unfortunately the performance of the Xamarin project was not that different of what we have seen on the Switch. 

I am sorry I am not on this discord server and to be honest their is not that much I know about the current MONO integration anyway. From my point of view it's a dead end anyway for this project. The current CoreRT prototype (while having even less official support) is already far superior when it comes to performances and usability.

**Comment by lateralusX** [comment]
@RalfKornmannEnvision OK, thanks for your information and feedback, all very valuable.
