### ISSUE TITLE
System.Text.Json.JsonElement get parent element or document

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/runtime#40452]
## Background and Motivation

The models don't have any way of navigating _up_ the hierarchy, e.g. from a leaf node back to the root.  This was discovered while attempting to implement [Relative JSON Pointers](http://json-schema.org/draft/2019-09/relative-json-pointer.html).  These are mentioned as a option for the `format` keyword in the latest JSON Schema draft ([2019-09](http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.7)).

## Proposed API

I'm not really fussed about the API so long as the data is accessible.  The rest of the API appears to be method-based, which makes sense when you don't know whether the data you're looking for exists (e.g. properties).  However, I think a `.ParentElement` or simply `.Parent` would be good here since it could be inferred that navigation to a given element from the root within a document already exists.

## Usage Examples

This is based on the example in the Relative JSON Pointer specification.

```c#
var json = JsonDocument.Parse("{\"foo\":[\"bar\",\"baz\"],\"highly\":{\"nested\":{\"objects\":true}}}");
var startElement = json.RootElement.GetProperty("foo")[1];
```

`startElement` now contains the element `"baz"`.  With Relative JSON Pointer, I should be able to navigate from here, up two levels and down the `/highly/nested/object` path to find myself at the `true` value.  Or, I could navigate up one level to find myself at the array, and then select the first item to get `"bar"`.

I've got navigating _down_ the tree with the current API.  It's the initial part of navigating _up_ the tree that can't currently be done.

What I'd like is something akin to this:

```c#
var parent = startElement.Parent; // "foo": ["bar", "baz"]
```

## Risks

I don't see any risks.  I had considered that an element instance could appear within two documents, but these are value type objects, and that could only happen with reference types.

**Comment by gregsdennis** [comment]
Implementation of JSON Pointer and JSON Schema using the `System.Text.Json` namespace: https://github.com/gregsdennis/json-everything

**Comment by bartonjs** [comment]
My recollection is that the lack of a parent property it was intentional.  Both because it would make the element struct bigger (it'd need to store the parent index, since you can't easily walk the table backwards to find it), and because we viewed the type as a cursor, and when passed into a function that function shouldn't have any reason to want to pop to a higher element... so it provided clean scope.

Aside from the annoying complexity of having to special case a document root to have no parent, it's not difficult to do... just a question of what the current design principles are.
