### ISSUE TITLE
Update Equals to compare IsRemote boolean for ActivityContext

### ISSUE THREAD

**Issue by eddynaka** [dotnet/runtime#40462]
## Background and Motivation

After adding the IsRemote boolean to ActivityContext, the Equals method isn't comparing that flag. With that, if we create two ActivityContext with same parameters, but IsRemote different, then, we would have equal activities.

## Proposed API

Current implementation:
https://github.com/dotnet/runtime/blob/ff47b4bb937553eaf92d891e47085aeba663a8d6/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/ActivityContext.cs#L96

My suggestion:
```csharp
public bool Equals(ActivityContext value) =>  
SpanId.Equals(value.SpanId)
&& TraceId.Equals(value.TraceId)
&& TraceFlags == value.TraceFlags
&& TraceState == value.TraceState
&& IsRemote == value.IsRemote; 
```

**Comment by tarekgh** [comment]
IsRemote is not part of the W3C context. So, I don't think it should be part of the comparison of the context. What is your scenario that need to distinguish the contexts according to the remote property?

CC @noahfalk @cijothomas @lmolkova

**Comment by noahfalk** [comment]
IsRemote is part of OTel SpanContext (which ActivityContext is attempting to represent for .NET). I would have  strongly expected IsRemote to be part of the Equals comparison.

**Comment by tarekgh** [comment]
@noahfalk I understand IsRemote is part of OTel sepcs. My question is, which scenario either OTel or any other parties want to distinguish the context because of the remote property? I believe in the mainstream cases, API users will care about the context itself (e.g. TraceId or Span Id). 

Also, when having a remote property in the context and then create an Activity with this context, the activity parent context will not have remote property on it. That is means if you created Activity with a remote context and then requested the parent context, is not longer are equal even it is created for this remote context. This will create confusion.

**Comment by noahfalk** [comment]
> Also, when having a remote property in the context and then create an Activity with this context, the activity parent context will not have remote property on it. That is means if you created Activity with a remote context and then requested the parent context, is not longer are equal even it is created for this remote context. This will create confusion.

Is this the code version of what you are describing? I want to make certain I understand:
````
ActivityContext parentContext = new ActivityContext(id, spanId, flags, isRemote: true);
using(var activity = source.StartActivity(parentContext))
{
    Debug.Assert(activity.Context == parentContext); // this fails
}
````


> My question is, which scenario either OTel or any other parties want to distinguish the context because of the remote property?

I think I would frame this the other way? In .NET if we have a struct that has fields X, Y, Z then my default assumption as a .NET developer is that the equality operator will compare all the fields. I think not having that default behavior is where we should place the burden of proof if we want to do that (ie what is the scenario where the user benefits because we did not include the IsRemote property in the comparison?)

**Comment by tarekgh** [comment]
> Is this the code version of what you are describing? I want to make certain I understand:

nevermind, I thought when creating Activity using ActivityContext, I can get Activity.Parent.Context. but it looks this is not the case.

> I think I would frame this the other way? In .NET if we have a struct that has fields X, Y, Z then my default assumption as a .NET developer is that the equality operator will compare all the fields. I think not having that default behavior is where we should place the burden of proof if we want to do that (ie what is the scenario where the user benefits because we did not include the IsRemote property in the comparison?)

I am not sure if there is .NET design guidelines saying should compare all struct fields in the equality. I am not sure either this is the default assumptions. This is usually left to the implementer deciding the semantics of the operation. anyway, I am not feeling strongly about it. I was just trying to think the real scenarios that someone want to compare the contexts and having the contexts not equals because of remote property which is not really part of the real W3C context.

I'll approve the PR.
