### ISSUE TITLE
System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyWithRevocation failing in outerloop

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#40708]
For instance this run: https://dev.azure.com/dnceng/public/_build/results?buildId=766799&view=results
Multiple occurrences of this test failing.
Happening since `2020-08-11T21:51:22.31Z`, seems to be Linux-only problem.
Kusto query:
```
TestResults
| where Method == "VerifyWithRevocation" and Result == "Fail"
| join kind=inner WorkItems on WorkItemId
| where FriendlyName == "System.Security.Cryptography.X509Certificates.Tests"
| join kind=inner Jobs on JobId
| order by Queued desc 
| project Type, StackTrace, Message, Branch, QueueAlias, Queued, DockerTag, Properties, Duration
```

Only one commit in this space and time frame: https://github.com/dotnet/runtime/commit/efafca9bd8ba5a746634820596f8144d0d98fde1#diff-e90af7202ab9605abea24897462bd930

cc: @adamsitnik

**Comment by vcsjones** [comment]
I'm kind of in that space now, I'll take a look.

**Comment by vcsjones** [comment]
I can reproduce it. The problem is that the CA for the certificate we are testing is giving back a CRL with no `NextUpdate`. This code here doesn't seem to tolerate a CRL with no NextUpdate.

https://github.com/dotnet/runtime/blob/13d97e1ebb2d99e9aad631dcd1afb35f2d6c99ac/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CrlCache.cs#L99-L100

Here is the CRL in question:

```
-----BEGIN X509 CRL-----
MIICMDCCARgCAQEwDQYJKoZIhvcNAQEFBQAweTELMAkGA1UEBhMCVVMxEzARBgNV
BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
c29mdCBDb3Jwb3JhdGlvbjEjMCEGA1UEAxMaTWljcm9zb2Z0IENvZGUgU2lnbmlu
ZyBQQ0EXDTIwMDgxMTE3NDkyNVowNDAyAhMzAAABbRIRksVDXEYSAAEAAAFtFw0x
NzExMTUwMTMwMDdaMAwwCgYDVR0VBAMKAQWgRDBCMB8GA1UdIwQYMBaAFMsR6MrS
tBZYAck3LjMWFrlMmgofMBIGCSsGAQQBgjcVAQQFAgMBAAEwCwYDVR0UBAQCAgCj
MA0GCSqGSIb3DQEBBQUAA4IBAQBN1QvVDg9R/87+cjGUSR/R7HZRCypozwF3/iBD
H0meIwzp2Bl8U91VcjY5HYu2Uq6Bf9z3dxcI/X/oNXovYOFP7DWQfIrpoF4lsQGq
ExyioFuHLn+y2wjd/Jv9FX8Dhv0yfwyr1cu9wKZiBVAu5skevoAmpSMcxN8ge56Q
9qH/BxP2GO7/1K5O8cu+zKXL/lVXXPtbMtOVl3EvN/AzF1USFdesEWjxMzBEPTnn
COYEi3x+J5RhL2WOiwVXI5rp3gJ+Wxx+B7cgfQWyD8/zBg8ywqQ2sF/G/hHlyIFU
AwSMHWL8ELJistpKOg0VxI2ZJY+YErVYyF9HgZIe3wTnfztE
-----END X509 CRL-----
```

CRL can be inspected via `openssl crl -in /path/to/crl/blah.pem -text`

```
Certificate Revocation List (CRL):
        Version 2 (0x1)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = Microsoft Code Signing PCA
        Last Update: Aug 11 17:49:25 2020 GMT
        Next Update: NONE
```

RFC-5280 says this field MUST be specified. However, the ASN.1 syntax says it's OPTIONAL. 

My guess is this started happening because the [issuing intermediate](https://crt.sh/?id=12728731) is expiring very soon (this month). I've seen CAs return a `NextUpdate` of none when the authority is no longer valid and won't provide updates anymore.

**Comment by vcsjones** [comment]
I think the appropriate fix here would be to modify the code so that if a CRL has an empty `NextUpdate`, return false from `AddCachedCrl` since we probably don't want to download a fresh CRL that is likely to be what we already have in the cache. Thoughts @bartonjs ?

**Comment by bartonjs** [comment]
> if a CRL has an empty NextUpdate, return false from AddCachedCrl since we probably don't want to download

Returning false (cached file is corrupt, or expired) would make us download a new one, so I assume you meant "return true".

I'm having trouble identifying what Crypt32 does here.  I... think... they mark it as never-expiring in the cache.  The only thing I can think of better than that is to do something like 72 hours after the LastModifiedTime of the file when there's no nextUpdate.

**Comment by bartonjs** [comment]
Oh, and we should probably add a dynamic revocation test... and delete this one, since it's about to perma-fail.
