### ISSUE TITLE
Tracking: Reflection issues which would be breaking changes if fixed

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#40737]
Spoke with @steveharter yesterday and realized that there's a category of reflection issues which are truly legitimate bugs but which could be considered breaking changes if they were addressed. This meta-issue is an effort to aggregate these individual issues as we encounter them.

We need to determine the correct course of action for this category of issue. Should we fix them? What's the appropriate balance between allowing 20-year-old code to work without changes vs. forcing all consumers of reflection to read the docs errata?

- [x] https://github.com/dotnet/runtime/issues/12355 - Type.IsPublic returns wrong answer for pointer and byref types
- [x] https://github.com/dotnet/runtime/issues/28056 - Inconsistent GetRuntimeProperties() Behavior

**Comment by GrabYourPitchforks** [comment]
I've tentatively marked this 6.0 so that we can make a decision soon as to how we want to address this category of issue.

**Comment by krwq** [comment]
@GrabYourPitchforks @steveharter have there been any conclusions there? In the meantime I'm moving this to 7.0. For some of these issues like the second one i.e. we could consider adding new overload perhaps (with extra bool telling to show all properties including the hidden ones)

**Comment by steveharter** [comment]
IMO if a given API is broken (e.g. `Type.IsPublic` is wrong for by-ref types) we should fix it even though technically it would be breaking change. One consideration on this is whether there is an existing workaround for the incorrect behavior (i.e. check if by-ref type and check for Public some other way) and whether the workaround continue to work as-is even though the underlying issue was fixed -- if so, then IMO it is much more palatable to do these breaking changes.
