### ISSUE TITLE
HttpHandlerDiagnosticListener does not send second chain of events if the request was autoredirected on netfx in W3C mode

### ISSUE THREAD

**Issue by eduard-bystrov** [dotnet/runtime#40777]
Here from https://github.com/dotnet/runtime/issues/38152

Request with status code 401(Unauthorized) can be autoredirected, which leads to the execution of the second request on the same object HttpWebRequest (may be HttpRequestMessage too).

If this happens we have the following chain of events:

1) System.Net.Http.Desktop.HttpRequestOut.Start
2) System.Net.Http.Desktop.HttpRequestOut.Ex.Stop (got 401)
3) System.Net.Http.Desktop.HttpRequestOut.Stop (success)

it's a bit strange... hardly anyone expects to get Stop and Stop.Ex for one request.

**Comment by karelz** [comment]
@eduard-bystrov were you able to reproduce it also on .NET Core?
Or is the report only about .NET Framework?

**Comment by eduard-bystrov** [comment]
> @eduard-bystrov were you able to reproduce it also on .NET Core?
> Or is the report only about .NET Framework?

only about .NET Framework
I have no information about .NET Core

**Comment by karelz** [comment]
We won't be able to fix .NET Framework, unless it has high business impact.

Triage: It will likely repro in .NET Core as well, we should think about it in our DiagnosticHandler changes in 6.0. We may decide it is by design potentially.

**Comment by MihaZupan** [comment]
Note: the issue here is that `DiagnosticHandler` was wrapping the underlying handler and as such could never intercept redirects.

#55392 fixes that by moving `DiagnosticHandler` to the start of the chain so that any redirect flows through it again and can be instrumented.
With this, automatic redirects will light up in 6.0 like any other regular request.
