### ISSUE TITLE
Need to include Windows Server Core in our test suite

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#40804]
The image to use is available here https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/316

There is no need to build here but we need to include this in our rolling build validation matrix as it's part of our supported platforms.

**Comment by jaredpar** [comment]
I believe we want to have a test path for both Nano and Server Core.

**Comment by ericstj** [comment]
@jaredpar mentioned to me offline that folks would still like us to have coverage of this for 5.0.  I think the next steps here are to enable in master then see what changes would need to be made in 5.0 (likely a subset since product changes need to be evaluated against the 5.0 bar for risk).  We should at least do what we can to get the data in time for 5.0.

**Comment by safern** [comment]
Yeah, agreed. Working on it after taking care of: https://github.com/dotnet/runtime/issues/41496

**Comment by ViktorHofer** [comment]
We need to at least do an one-off validation before we release.
