### ISSUE TITLE
Add NT_SIGINFO NOTE for each thread to createdump dumps

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#40958]
On Linux, add the NT_SIGINFO note for each thread. This NOTE contains the siginfo_t struct which can be obtained with ptrace's PTRACE_GETSIGINFO or PTRACE_PEEKSIGINFO (doesn't remove signals).  

See https://man7.org/linux/man-pages/man2/ptrace.2.html on ptrace.

**Comment by mikem8361** [comment]
This helps native debuggers like lldb/gdb and windbg to get more info on native exceptions/signals.

**Comment by hoyosjs** [comment]
Is this `SA_SIGINFO`?

**Comment by mikem8361** [comment]
SA_SIGINFO is the sigaction() flag used when setting an signal handler. The siginfo_t struct is passed to the handler if SA_SIGINFO is passed to sigaction.

NT_SIGINFO is a NOTE in the ELF coredump containing the signal info.  This note contains a siginfo_t struct for the thread.

**Comment by leculver** [comment]
This issue is impacting all Watson bucketing for Linux.  The issue was reported by AzureML.  Currently WinDbg (and therefore !analyze) assumes that the startup thread is the crashing thread (as seen by `.lastevent`).  This means that any dump run through !analyze will only work properly if the startup thread happens to be the one crashing.

It took a while to notice this, because other coredump writers (like the Linux Kernel) would add this information correctly, and some environments were configured in a way that uploaded both Linux Kernel generated dumps along with a createdump generated dump.  Sometimes though, the Linux Kernel generated dumps wouldn't have the correct `coredump_filter` set, meaning they would report the right faulting thread but managed analysis would fail.

The end result here is a bizarre mix of issues that was tough to untangle until AzureML reached out with a repro we could track all the way through the system.

**Comment by tommcdon** [comment]
Moving to 6.0 to track servicing backport
