### ISSUE TITLE
GetAppDomainStaticAddress only works for collectible modules

### ISSUE THREAD

**Issue by ASuurkuusk** [dotnet/runtime#40954]
### Description

I have previously reported an issue with an AV in GetAppDomainStaticAddress (issue #33367), which was fixed in #34677. However, as far as I can see, this fix introduces a regression. It is no longer possible to retrieve AppDomain static addresses for non-collectible modules. The fix verifies that the LoadAllocator has an initialized "ExposedObject", but this object only seems to be initialized for collectible modules. Maybe "ExposedObject" should only be verified for collectible modules?

In ProfToEEInterfaceImpl::GetAppDomainStaticAddress:

```
    if (typeHandle.GetModule()->GetLoaderAllocator() == NULL ||
        typeHandle.GetModule()->GetLoaderAllocator()->GetExposedObject() == NULL)
    {
        return CORPROF_E_DATAINCOMPLETE;
    }
```

### Configuration

* .NET 5 Preview 7, Windows x86/x64

### Regression?

Works correctly under .NET Core 3.1.6, but this version may be susceptible to the AV mentioned in #33367. I have not been able to reproduce the original AV on .NET Core 3.1.6.

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
Thanks for reporting this. Looking at the code you are correct that GetExposedObject should only be verified for collectible modules. Actually, the whole check can just be for collectible modules since once a non-collectible module is loaded the LoaderAllocator will never be null.

The fix is simple and will be out soon.
