### ISSUE TITLE
Unable to run executable program from PHP shell_exec()

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/runtime#40971]
I've built my program into a release executable file and now I'm trying to execute it through PHP `shell_exec()` function as below:
`$result = shell_exec("./myprogram 2>&1");`

But it always throwing `Failed to create CoreCLR, HRESULT: 0x8007000E` error.

Even I have allocated 16G RAM for this server. It can run **successfully** if been executed directly from internal bash instead of from PHP `shell_exec()`. What's wrong here?

**Comment by vitek-karas** [comment]
It's hard to tell without more information, things which might help to investigate this:
* Try to get it to fail under a debugger (either `shell_exec` the debugger directly or somehow attach to it), Typically CoreCLR will throw exceptions internally for failures, so it should be possible to just stop on exception and grab the callstack.
* What is the full stdout/stderr of the process? Maybe there's some additional info printed out.
* Grab a host trace - set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=hosttrace.txt` before running the process, it should create the `hosttrace.txt` in the current directory with very detailed information about how it tried to start the runtime. Please note that the file may contain information about the local machine and user (file paths, env. variable values and so on) - so only share it if you're comfortable doing so.

Since it works outside of PHP, grab the host trace for the working case as well and compare the two - something is likely different.

**Comment by vitek-karas** [comment]
Also version/environment information would help:
* What is the .NET Core SDK you used to build the app
* What is the target framework for the app - `netcoreapp3.1` or something else?
* How did you build it? `dotnet build`, or `dotnet publish` - any special settings (single-file, crossgen, trimming, ...)
* What is the platform (which Linux I guess)

**Comment by jkotas** [comment]
Potentially related: #13027

**Comment by agocke** [comment]
Closing due to lack of info
