### ISSUE TITLE
System.ComponentModel.Composition support for .NET Core 3.1

### ISSUE THREAD

**Issue by Pikhulya** [dotnet/runtime#41018]
I have .net core 3.1 application (targeting win-x64, also tried win10-x64 with the same results) referencing netstadard 2.0 [Microsoft.SqlServer.DACFx 150.4826.1](https://www.nuget.org/packages/Microsoft.SqlServer.DACFx/) which fails with **PlatformNotSupportedException: System.ComponentModel.Composition APIs are not supported on this platform.**:

![image](https://user-images.githubusercontent.com/11545082/90607673-656a8a80-e1b6-11ea-8ee6-5cd045ade190.png)

Are there plans to support ComponentModel.Composition in .NET Core 3.1 ? Are the ways to get it work without waiting for a new release?

**Comment by ericstj** [comment]
System.ComponentModel.Composition is supported on .NETCore 3.1.  Are you sure you are targeting `netcoreapp3.1` and not something else (or perhaps you manually selected the wrong DLL rather than referencing the package)?

It looks to me like your application copied
`system.componentmodel.composition\4.5.0\lib\netstandard2.0\System.ComponentModel.Composition.dll`
instead of 
`system.componentmodel.composition\4.5.0\lib\netcoreapp2.0\System.ComponentModel.Composition.dll`

`netcoreapp2.0` should be preferred over `netstandard2.0` for a `netcoreapp3.1` application.

**Comment by ericstj** [comment]
Here's a sample that demonstrates this works.
[mefSample.zip](https://github.com/dotnet/runtime/files/5220437/mefSample.zip)

Please reactivate and provide a repro if you need further help.
