### ISSUE TITLE
I made a fast String.Concat<IEnumerable<string>) where IEnumerable<string> is actually a List<string>

### ISSUE THREAD

**Issue by thargol1** [dotnet/runtime#41096]
### I made a faster String.Concat<IEnumerable<string>) where IEnumerable<string> is actually a List<string>

I don't know how Git works, I'm a TFS man, so here is the code, maybe someone else can process it?

### Benchmark
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.450 (2004/?/20H1)
Intel Core i7-3820 CPU 3.60GHz (Ivy Bridge), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.6.20318.15
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.30506, CoreFX 5.0.20.30506), X64 RyuJIT
  DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.30506, CoreFX 5.0.20.30506), X64 RyuJIT

|                        Method |     Mean |    Error |   StdDev | Ratio |
|------------------------------ |---------:|---------:|---------:|------:|
| StringConcatRegularListString | 48.64 us | 0.913 us | 0.976 us |  1.00 |
|        StringConcatListString | 21.04 us | 0.351 us | 0.417 us |  0.43 |

### Code

The test code generates a 1000 random string of length 0 to 100 and with 2% null-values.
It used a fixed random seed, so the test is the same every time.

I used `string.Create` to fill a `Span<char>`. Maybe the code can get even faster using `FastAllocateString` and `FillStringChecked` but those methods are private.

If I change `List<string>` to `IList<string>` the code gets a slower: 0.52 instead of 0.43.

Using `foreach(..` instead of `for(var...` makes the code slower.

Using `string.Concat(list.ToArray())` is also a little bit slower, but a simple optimisation I use now in my production code.

```csharp
#nullable enable

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PerfTests
{
    public class Program
    {
        public class Concats
        {
            private static List<string?> dataSetList = new List<string?>();

            static Concats()
            {
                const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
                var r = new Random(1234);

                for (var i = 0; i < 1000; i++)
                {
                    if (r.Next(50) == 0)
                    {
                        dataSetList.Add(null);
                    }
                    else
                    {
                        var length = r.Next(100);
                        dataSetList.Add(new string(Enumerable.Range(0, length).Select(i => chars[r.Next(chars.Length)]).ToArray()));
                    }
                }
            }

            [Benchmark(Baseline = true)]
            public string StringConcatRegularListString() => string.Concat(dataSetList);

            private string StringConcatListString(List<string?> values)
            {
                var n = values.Count;
                var length = 0;
                for (var i = 0; i < n; i++)
                {
                    var s = values[i];
                    if (s is not null) length += s.Length;
                }
                return string.Create(length, values, (chars, state) =>
                {
                    var position = 0;
                    var n = state.Count;
                    for (var i = 0; i < n; i++)
                    {
                        var s = state[i];
                        if (s is not null)
                        {
                            s.AsSpan().CopyTo(chars[position..]);
                            position += s.Length;
                        }
                    }
                });
            }

            public string StringConcatReplacement(IEnumerable<string?> values)
            {
                if (values is List<string?> list) return StringConcatListString(list);
                return string.Concat(values);
            }

            [Benchmark]
            public string StringConcatListString() => StringConcatReplacement(dataSetList);
        }

        public static void Main(string[] args)
        {
            var check = new Concats();
            var s1 = check.StringConcatRegularListString();
            var s2 = check.StringConcatListString();
            if (s1 != s2) throw new Exception("s1 does not match s2.");

            var summary = BenchmarkRunner.Run<Concats>();
        }
    }
}

**Comment by GrabYourPitchforks** [comment]
I don't think we would specialize this for `List<string>`, but you have a good observation that there's a tradeoff to be made. Let's assume for now continuing to specialize `IEnumerable<string>`. For short lists, the current use of `ValueStringBuilder` has _O(2 \* n)_ amortized runtime during the memcpy operations, plus a small overhead to create the enumeration object from the underlying enumerable. For long lists or long strings the memcpy operation will dominate the runtime.

If we switched this to use `string.Create`, we'd need to run over the enumeration twice: once to build up the length, and once to do the copy. The overhead of creating the enumeration object doubles, but the memcpy amortized runtime is now _O(n)_ instead of _O(2 \* n)_.

It would be interesting to see the typical number of elements provided in a call to `string.Concat` or the typical length of the returned string. This would speak to which algorithm is more suited for real-world workloads.

**Comment by thargol1** [comment]
Iterating an `IEnumerable<string>` twice is bad, you never know what the source is and it could cause side effect. I am not suggesting to iterate the `IEnumerable<string>` twice, but more code like:
```csharp
if (values is List<string> stringList) { return ConcatStringList(stringList)};
... continue with orginal code...
```
This would introduce a small penalty for all other calls.

Adding a new overload `string.Concat(List<string> values)` would also be possible but than it would not be 100% backward compatible, after a recompile of existing code the new overload would be called. I don't know if that is bad, but it is a change.

As for real-world workloads, the `List<string>` in my code usually contains about 10 to 30 elements of limited length. A github [search](https://github.com/search?l=C%23&q=%22List%3Cstring%3E%22&type=Code) for `List<string>` yields 415K results, so it is used a lot. The same [search](https://github.com/search?l=C%23&q=%22IEnumerable%3Cstring%3E%22&type=Code) for `IEnumerable<string>` yields 265K results. How many of them are concatenated in the end... I don't know how to search for that.

Now I use `string.Concat(values.ToArray())` which is twice as fast as `string.Concat(values)` where values is a `List<string>`. But a little bit slower than my code, because of the overhead of creating the array.

Some background: we're migrating code to Azure where CPU and memory usage are billed, so every performance gain is welcome. (And I really do appreciate all the performance improvements made in .Net 5 so far). All small improvements combined add up to lower billing in the end.

And (micro) optimizations are fun to do :-)

**Comment by GrabYourPitchforks** [comment]
`List<string>` and `IEnumerable<string>` are clearly heavily used. The real question is how many people call `string.Concat(IEnumerable<string>)`, _passing in a `List<string>` instance_. Or, if we wanted to generalize the problem as you had suggested, we could special-case `IList<string>` rather than `List<string>`.

If we had more evidence that this is commonly used and is a hot code path, that would warrant the extra work here. But without such evidence I don't see us introducing complexity into this code. Even within the runtime and libraries, [I see very few references](https://source.dot.net/#System.Private.CoreLib/String.Manipulation.cs,206408f6325aea24,references) to this API.

**Comment by thargol1** [comment]
You're right. I can't find many examples myself. And in the 5 examples you linked, 3 are tests and 1 is a sample.
I'll close this issue.
