### ISSUE TITLE
Rooted objects from IAsyncEnumerable (only in debugger)

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#41187]
Disclaimer: This only roots objects when in the debugger because of the `s_currentActiveTasks` dictionary that keeps around incomplete tasks. Which may be changed one day to WeakReferences https://github.com/dotnet/runtime/issues/26565.

This issue is similar to https://github.com/dotnet/roslyn/issues/39321 except that it doesn't "leak" every enumerator, instead it "leaks" occasionally.

The following code will leave 3 objects rooted per "failed async enumerable". 
![image](https://user-images.githubusercontent.com/7574801/90940017-3cb6e080-e3c2-11ea-82b1-d76934bbc3eb.png)

```c#
for (var iteration = 0; iteration < 10000; iteration++)
{
    static async IAsyncEnumerable<byte[]> func()
    {
        await Task.Yield(); // await Task.CompletedTask; will not repro
        for (var i = 0; i < 10; ++i)
        {
            yield return new byte[] { 1 };
        }
    }

    await foreach (var item in func())
    {
    }
}
```

Took a look at this with @jcouv and we didn't see anything obviously wrong from the compiler side of things. The fix for the linked issue is present in the repro.

cc @bartonjs and @jkotas for routing as Toub is not available.

**Comment by jcouv** [comment]
@stephentoub I will prepare a PR to swap those two calls. But it doesn't look like that's fixing the leak.
There is some variability in repro, but I could still see a leak of similar size with this change.

I've prepared nuget packages of the compiler with change made: https://www.dropbox.com/s/wojznub86kvndhm/compiler-async-leak.zip?dl=0 (to use it, decompress to a local folder, add nuget source referencing this folder, then add compilers toolset package version `3.8.0-dev`).

Here's the program I test: https://gist.github.com/jcouv/7142c07e2c4cc2792cdcd7a98c898250 (note there is a warm up loop and calls to `GC.Collect()` before places that I break and collect data for).

Here's what the IL looks like with change made:
<img width="1033" alt="leak-il-change" src="https://user-images.githubusercontent.com/12466233/90987066-e621e180-e53c-11ea-9a33-b02687e442a6.PNG">

**Comment by stephentoub** [comment]
Thanks. So what you're saying is I can't fix this all just by staring on my phone :-)

**Comment by davidfowl** [comment]
> Thanks. So what you're saying is I can't fix this all just by staring on my phone :-)

I believe in you. Stare at it longer.

**Comment by stephentoub** [comment]
Finally made time with a debugger.  Fundamentally the problem is too many methods named "MoveNext" :wink:

If anyone wants to play along at home, here's a deterministic repro that doesn't require the debugger be attached (by using private reflection no one should depend on):
```C#
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;

public class C
{
    static async IAsyncEnumerable<int> Func(TaskCompletionSource tcs)
    {
        await tcs.Task;
        yield return 1;
    }

    static void Main()
    {
        typeof(Task).GetField("s_asyncDebuggingEnabled", BindingFlags.NonPublic | BindingFlags.Static).SetValue(null, true);

        for (int i = 0; i < 1000; i++)
        {
            TaskCompletionSource tcs = new();
            IAsyncEnumerator<int> e = Func(tcs).GetAsyncEnumerator();
            Task t = e.MoveNextAsync().AsTask();
            tcs.SetResult();
            t.Wait();
            e.MoveNextAsync().AsTask().Wait();
        }

        Console.WriteLine(((dynamic)typeof(Task).GetField("s_currentActiveTasks", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null)).Count);
    }
}
```

The state machine task is removed from the static tracking collection here:
https://github.com/dotnet/runtime/blob/722b8a660e7e0c59419196be102784244883ff08/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs#L335-L341
This `AsyncStateMachineBox.MoveNext` method is the invoked in response to an await completing.  So, for example, in the above repro, it’ll be invoked when the tcs.Task completes, causing this MoveNext to be called, which in turn will call `StateMachine.MoveNext` to invoke the compiler-generated `MoveNext` method for the iterator. The iterator will proceed to set the current value as `1` and complete the `ValueTask<bool>` returned from the `IAsyncEnumerable<int>.MoveNextAsync` call.  All’s good so far.

But, then the next call to `e.MoveNextAsync()` calls to `AsyncIteratorMethodBuilder.MoveNext(ref stateMachine)` which effectively just invoked `StateMachine.MoveNext` directly; there’s no more work to be done, so it just completes the call synchronously, and we never end up calling into the `AsyncStateMachineBox.MoveNext` again, which means we never execute that code path which checks to see whether the task has completed and removes it from tracking.

I need to think about the cleanest way to address this.
