### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by piotrsz1234** [dotnet/runtime#412]
I would like to ask, how to add dependenci to another project, which isn't in solution?
For example: If I would like use System.Runtime.Serialization in System.Text, how should I add such dependenci or it shouldn't be done like that.

Regards

**Comment by jkotas** [comment]
This is done via `<Reference Include="assembly name" />` element in the .csproj file.

> System.Runtime.Serialization in System.Text

System.Runtime.Serialization and System.Text are namespace names. The `Reference` element takes assembly names. Each namespace can be implemented by many different assemblies. You need to find out which assembly implements the relevant part of the namespace that you would like to add a dependency to.

Note that we are deliberate about introducing dependencies between components. For example, we would not want to add more dependencies on System.Runtime.Serialization.Formatters because of it is deprecated legacy non-secure technology.
