### ISSUE TITLE
System.ComponentModel.Annotations.dll has different version for ref assemblies (netstandard2.0)

### ISSUE THREAD

**Issue by AndreyTretyak** [dotnet/runtime#41221]
`System.ComponentModel.Annotations.dll` **ref assembly** that targets **netstandard2.0** has a different version then actual assembly (4.2.0 vs 4.2.1).

This causes a runtime error since assembly failing to load if you don't have assembly redirect.

In my case failure accrued for package version 4.7.0, but in the latest package (5.0.0-preview.7.20364.11) problem still exists.

Looks like the same issue with versions also exist for following targets: netcore5.0, netstandard1.4.

Ref assembly - version 4.2.0
![image](https://user-images.githubusercontent.com/2550113/90967348-f05cc500-e4d5-11ea-8c7f-3320f36494cb.png)
Actual assembly version 4.2.1
![image](https://user-images.githubusercontent.com/2550113/90967372-403b8c00-e4d6-11ea-917a-f44521c5272a.png)

**Comment by ajcvickers** [comment]
@danmosemsft Who should look at build/packaging issues?

**Comment by danmosemsft** [comment]
@Anipik can you help advise or route this?

**Comment by Anipik** [comment]
Taking a look

**Comment by Anipik** [comment]
We updated the 4.2.0.0. -> 4.2.1.0 when we branched off from release/2.0 to release/2.1. We did the similar thing for packages in 3.1.

I think we missed to change the ref assembly here https://github.com/dotnet/corefx/blob/release/2.1/src/System.ComponentModel.Annotations/ref/System.ComponentModel.Annotations.csproj#L8

For mostly projects the change in dir.props is enough for the change.

@joperezr @ericstj are there any fallbacks of fixing in this in 2.1? We will need it to fix in 2.1 because we are just harvesting them in 3.1 and 5.0

**Comment by ericstj** [comment]
We didn’t miss this, read the comment above the linked line.  We have to do this when a package represents an assembly as inbox and doesn’t provide an implementation from the package.  It’s ok for the ref to be lower than the implementation.

BindingRedirects are only needed on .NETFramework. All other frameworks have a binder which permits a newer implementation automatically.  Are you seeing a mismatch when targeting .NETFramework?  Or only when targeting netstandard and running on NETFramework?

**Comment by AndreyTretyak** [comment]
In my case package `System.ComponentModel.Annotations` is a dependency of another NuGet package that targets `netstandard2.0` and it's used in full framework packages.
This scenario looks like a valid usage to me, but it causes a failure.

Also, this error might be quite confusing since you can see that dll in the package have version 4.2.1.0 but your project build with a dependency to 4.2.0.0 and that fails in runtime in another repo that use NuGet package with a transient dependency to `System.ComponentModel.Annotations`.

Are there any benefits in having ref dlls with different versions?

Is it possible that you might publish a package with consistent versioning?

**Comment by joperezr** [comment]
TBH this shouldn't be a problem in your case, since if you target .NET Framework then the reference asset resolved by the package should be the one in the net461 folder which has 4.2.1.0 as assembly version. I do get that you are getting it as a transitive dependency of something that does target netstandard2.0, meaning that this other dependency is probably seeing the 4.2.0.0 version. All that said, this means that when we are building RAR should see a mismatch with the versions of System.ComponentModel.Annotations that it is getting: It should see that you are directly referencing 4.2.1.0 (coming from the net461 folder from the package) and it should see that some dependency you have depends on 4.2.0.0 meaning that it should be suggesting a binding redirect in order to fix this. Do you have Auto binding redirects enabled in your project?

FWIW I just tried out what I think is exactly your scenario and I do see that RAR is correctly generating the binding redirect as I expected which is causing the app to run just fine at runtime:
![image](https://user-images.githubusercontent.com/13854455/91208546-34f78480-e6bf-11ea-8c04-5d4691918dc4.png)

@AndreyTretyak if you don't see a binding redirect being generated on your app.config file, please send us a msbuild.binlog of your project so that we can diagnose why is this happening. To generate a binlog, simply run `msbuild yourProject.csproj /t:rebuild /bl:msbuild.binlog` from a developer command prompt.

**Comment by AndreyTretyak** [comment]
Binding redirects would probably work, but it's problematic for me to use them. Problems occur in the repository using archaic build system (predecessor of BuildXL) that has problems with generating redirects (sure it could be done manually) and contains over 700 projects and for each of the redirects you need to manually specify that file with redirects would be deployed alongside with services :(

It definitely could be done, but it's painful, and if it possible I would like to understand why you've decided to have different versions?

**Comment by joperezr** [comment]
@ericstj can go into more details much better than I can, but the reason for pinning the ref version to 4.2.0.0 for netstandard2.0 is very technical, which is that frameworks compatible with netstandard2.0 (netcoreapp2.0, netcoreapp2.1 and others) shipped with this assembly inbox with version 4.2.0.0 and we need the inbox version to win over the one in the package. If we were to instead also version the ref to 4.2.1.0 for netstandard2.0, then when consuming this package (either directly or transitively) on a framework that did have it inbox will start preferring the package version over the one that ships inbox given that the assembly version will be higher, which could lead up to many issues from increasing package app footprint, decrease performance or even have unification issues.

Binding redirects are really a core requisite for being able to consume .NET Standard packages, given that the runtime loader for .NET Framework wasn't originally designed with the thought of technologies like NuGet and .NET Standard in mind, so even if we were able to fix this issue with System.ComponentModel.Annotations so that it wouldn't require a redirect then very likely other assemblies would start needing redirects as well. For this reason, even though I'm not familiar with the build system you might be using I would suggest trying to either figure out a way of easily adding binding redirects which is more manageable or to move to a build system like MSBuild where we do all of this for you.

**Comment by AndreyTretyak** [comment]
Thank you for the explanation, that makes sense. And what would be the downside of pinning netstandard2.0 version of the library to 4.2.0.0? (aside of not updating version) 

I'll try to go with setting up proper redirects. We are trying to depricate that repo but its a slow process.

I'll close the issue since this behaviour is by design. Thanks again

**Comment by joperezr** [comment]
> And what would be the downside of pinning netstandard2.0 version of the library to 4.2.0.0?

You still want the implementation assembly to version because you want that one to be preferred over the non-serviced one, so when fixing bugs you still version the implementation assembly, just not the reference assembky for the reasons called out above.
