### ISSUE TITLE
Microsoft.Net.HostModel consumes a preview version of System.Text.Json Package

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#41302]
Microsoft.Net.HostModel consumes a preview version of System.Text.Json Package 
https://github.com/dotnet/runtime/blob/master/src/installer/managed/Microsoft.NET.HostModel/Microsoft.NET.HostModel.csproj#L19

https://github.com/dotnet/runtime/blob/master/eng/Versions.props#L98

This would be a problem when we start producing stable bits, as stable shipping packages cannot depend on preview packages.

https://github.com/dotnet/runtime/pull/35024 upgraded the package version. 

cc @ViktorHofer @safern @ericstj @eerhardt @danmosemsft

**Comment by eerhardt** [comment]
I believe this is a duplicate of #1823.

cc @agocke @jkoritzinsky @swaroop-sridhar @vitek-karas 

> This would be a problem when we start producing stable bits, as stable shipping packages cannot depend on preview packages.

Note that we do not officially ship `Microsoft.NET.HostModel` on nuget.org. We did in the past, but that was a mistake. (#32825) This package is only intended to be a "transport" package to be consumed by `dotnet/sdk`.

**Comment by Anipik** [comment]
Talked with @eerhardt and we can close this one

**Comment by ViktorHofer** [comment]
What's the outcome of your discussion? :)

**Comment by eerhardt** [comment]
> What's the outcome of your discussion?

Since `Microsoft.NET.HostModel` doesn't ship on nuget.org, we don't need to build a stable package of it. The only reason it exists is to be a transport into `dotnet/sdk` to be consumed by the SDK. Since we don't need a stable build of it, it won't need a stable dependency on System.Text.Json.

We still should fix #1823 for this library. It is becoming a pain.
