### ISSUE TITLE
System.Text.Json - JsonSerializer issue when deserializing property of type System.Version

### ISSUE THREAD

**Issue by proggmatic** [dotnet/runtime#41368]
### Description
Property of type System.Version serialized successfully, but on deserialization it returns empty object (in sample below Ver1 = 0.0.0.0)

public class TestClass
{
    public Version Ver1 { get; set; }
}

var ver = new TestClass
{
    Ver1 = new Version(1, 3, 4, 6)
}

string serialized = JsonSerializer.Serialize(ver);    // returns {"Ver1":"Major":1,"Minor":3,"Build":4,"Revision":6,"MajorRevision":0,"MinorRevision":6}}

TestClass deser = JsonSerializer.Deserialize<TestClass>(serialized);    // Ver1 is 0.0

### Configuration
Windows 10 2004 X64
.NET Core 3.1.7

**Comment by layomia** [comment]
We can add a new internal converter for this. Given prior art from Newtonsoft.Json and just `.ToString()`, we'd want to serialize `Version` instances as "1.2.3.4" instead of `{ "Major": 1, "Minor": 2, ... }`.

The workaround for 3.1 & 5 is to [write a custom converter](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to) for the `Version` type.
