### ISSUE TITLE
Android Runtime Test Design Proposal

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41414]
This is a proposal for how to get the Dotnet runtime tests running for Android. Not everyhting is pinned down yet, and some things need to be investigated.

### Existing Test Infrastructure

Once built, the runtime test have three parts: 

1. An xunit wrapper
2. A shell script
3. The actual test assembly.

The XUnit wrapper runs serves as an interface between the shell script and Xunit. It calls the shell script. The shell script sets up various environment variables, and calls the test assembly. The test assembly itself is just a program that exists with 100 if the test passes.

### What needs to change for android

The android platform has limitations that mean we can't just change the OS to "android" and expect the runtime tests to work. Among the most salient: We cannot fork a process on android, so there is no way for the xunit wrapper to start a shell script, or for the shell script to run the test assembly.

 Instead, we will need to create an *Android Test Runner*. The Android Test Runner is an android application, that when started with a test name, runs that test and returns the result.  The shell script will run on the host OS, and instead of directly running the test assembly, will invoke the Android Test Runner with the name of a test as a parameter.

### Build Changes

The android test runner must be built as part of the building the tests. It needs to contain all the test assemblies inside it.

Android simulator should probably be started as a helix precommand.
     
### Helix payload changes

When running in CI, the Xunit wrappers (and thus the scripts), are all run on Helix. Thus the built Android Test Runner must be included in te Helix payload.

### Unknowns

 Is there a practical limit on how big an android app can be? Would including ~3k test assemblies exceed this limit?

 Would an alternative design where we build one android app per test be too slow?

@fanyang-mono  @imhameed @SamMonoRT

**Comment by naricc** [comment]
@trylek @ViktorHofer @safern @jkoritzinsky   Any suggestions on your end regarding this design?

**Comment by trylek** [comment]
In the WebAssembly testing plan you also initially planned to build a huge wasm app containing all the tests and then you changed it to per-test wasm apps; do you expect that Android will have larger overhead that would make this impractical? One other partitioning we already support is test grouping into Helix work items / payloads - if it turns out that we need to combine multiple tests in one "Android app" to achieve reasonable performance, would it be possible to leverage this partitioning for creating the larger Android apps? One slight wrinkle of the "combined app" is that this basically means getting rid of the environment initialization in the cmd / sh execution scripts some of the tests rely on.

**Comment by naricc** [comment]
> In the WebAssembly testing plan you also initially planned to build a huge wasm app containing all the tests and then you changed it to per-test wasm apps; do you expect that Android will have larger overhead that would make this impractical? 

I'm still tracking down the numbers, but the overhead per building a minimal android app is much higher than building a wasm app. It takes 10 seconds to build as is roughly 10 MB in size, and on top of that needs to be send over to the simulator (sending 1000 apps is slower than one big app). So I am pretty sure its infeasible.

I believe leveraging the existing partitioning to create several large android apps is possible though.

Do you know approximately how many tests rely on environment initialization? It might be possible to just not use those.

**Comment by trylek** [comment]
Hmm, taking 10 seconds to produce a 10 MB app sounds a bit slow on today HW but I guess it's what it is. Thankfully it seems to me that custom test setup is not that common. The most prevalent (572) is <code>CLRTestExecutionArguments</code> for both <code>BuildAndRun</code> and <code>RunOnly</code> tests. A handful of tests uses <code>CLRTestBatch/BashEnvironmentVariable</code> and I guess that basically all Interop tests are out of question, at least in this phase. (Just like readytorun and other tests that are simply not applicable to this build mode.)

The command-line arguments (both for BuildAndRun and RunOnly tests) bring me to another problem: today, the individual BuildAndRun tests are technically standalone managed apps. At the first glance it seems to me that, if you want to combine 500 RunOnly tests calling the same BuildAndRun test with 500 different command-line argument variations, you'd need something like an IL rewriter / generator as you need to generate a "new Main" that will call the "old Main" 500 times with different parameters. For combining multiple BuildAndRun tests you need to generate a "new Main" that will call into a sequence of the "old Main methods" (again with the appropriate command-line arguments). Is the Android app builder capable of doing this by itself or is that something that needs to be built as part of this effort?

**Comment by jonpryor** [comment]
Question: is there a way to get a "`dotnet` host" built *for Android*?  Not a `.so`; an executable binary.

I know of at least one person who has expressed interest in such a thing. :-)

*If* you can do that, then you don't need to create an Android `.apk` *at all*.

(Channel additional inspiration from: https://gist.github.com/jonpryor/55670ee1b15c421f3fa2f0c9e29a01e9 )

With lots of hand-waving, what you do is:

 1. Build/otherwise obtain the `dotnet` command built to run *on* Android.
 2. Build your other test assemblies
 3. Zip (1) and (2)  into e.g. `dotnet-tests.zip`
 4. *Deploy* `dotnet-tests.zip` to your Android target:

        adb shell mkdir -p /data/local/tmp/dotnet-tests
        adb push dotnet-tests.zip /data/local/tmp/dotnet-tests
        adb shell "(cd /data/local/tmp/dotnet-tests; unzip dotnet-tests.zip)"

    Behold! The contents of `dotnet-tests` are now on the Android device.  No need for building an Android `.apk` or anything!

 5. *Run* your tests.  Assuming `dotnet-tests.zip` contains a `dotnet` binary, you could do:

        adb shell /data/local/tmp/dotnet-tests/dotnet run /data/local/tmp/dotnet-tests/my-test.dll

The only problem with the above setup is that you "pollute" `/data/local/tmp`; some care should be taken.  If this is a "throw away" emulator instance for CI use, who cares?  If it's a personal device, you probably want to ensure that "something" *removes* `/data/local/tmp/dotnet-tests` when test execution is complete.

**Comment by EgorBo** [comment]
that is a great idea! (if there are no pitfalls converting the dotnet host to android) but if we're fine with APK we can easily re-use the existing infrastructure. APK size for a typical runtime test shouldn't exceed 1-2 mb.

**Comment by akoeplinger** [comment]
> APK size for a typical runtime test shouldn't exceed 1-2 mb.

Only if we run the linker :)

**Comment by jonpryor** [comment]
One additional "pro" of the [approach discussed above](https://github.com/dotnet/runtime/issues/41414#issuecomment-681201210) is that if any of the tests involve process exit/unhandled exceptions/etc., they will work "reasonably", without pulling in Android+Java process exit complexities.

One "con" of that approach is that it can't easily involve Java code.  "Normal" Android process startup has a Java VM running "before" the app starts executing.  In the approach described above, there would be *no* JVM already executing.  Consequently, if any CoreCLR code requires the presence of a JVM, that code won't work immediately.

This doesn't mean it's impossible; it just means it doesn't work *now*.  The NDK does *declare* [`JNI_CreatejavaVM()`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#JNI_CreateJavaVM), but the Android NDK doesn't contain any `.so` files which *export* that symbol. Consequently, various (presumably) unsupported "hacks" would be needed in order to create a JVM from a `dotnet` console context, e.g. this 2017 article ["Creating a Java VM from Android Native Code"](https://calebfenton.github.io/2017/04/05/creating_java_vm_from_android_native_code/).  However, such an approach increasingly diverges from what "normal customer apps" would be doing, and thus while potentially *possible*, may not be *ideal*.

**Comment by jonpryor** [comment]
Possibly useful Discord conversation links:

  * https://discordapp.com/channels/732297728826277939/732297837953679412/748284420712038501
  * https://discordapp.com/channels/732297728826277939/732297837953679412/748285976316477540
  * https://discordapp.com/channels/732297728826277939/732297837953679412/748515030898704444

**Comment by EgorBo** [comment]
> Consequently, if any CoreCLR code requires the presence of a JVM

Currently, it relies on the following JVM APIs:
```
Context.getFilesDir().getAbsolutePath();
Context.getCacheDir().getAbsolutePath();
```
to set up "HOME" and "TMPDIR" env. variables.

**Comment by marek-safar** [comment]
> Question: is there a way to get a "dotnet host" built for Android? Not a .so; an executable binary.

This sounds like `corerun` or the equivalent we have for Mono. I think it's worth exploring as we could ship shared libraries and a selected number of tests in one batch

**Comment by fanyang-mono** [comment]
The idea of creating a  "dotnet host" built for Android is great idea. The investigation and implementation for that is complicated enough to be a whole another project. For now, I plan to focus on getting CoreCLR runtime tests running with Android on CI, by leveraging the approach that Nathan used to make runtime tests running with WASM on CI.

**Comment by CoffeeFlux** [comment]
Are you sure that making a custom Android test runner is actually easier than porting the default host? I'm inclined towards jonp's suggestion here, having seen the effort involved in making the iOS runner.

**Comment by fanyang-mono** [comment]
> Are you sure that making a custom Android test runner is actually easier than porting the default host? I'm inclined towards jonp's suggestion here, having seen the effort involved in making the iOS runner.

I am following the example of runtime tests running with WASM plus the Android sample to create the Android test runner. On the other hand, I don't know where I should start to create a "dotnet host" built for Android. Currently, to me, creating an Android test runner is more manageable. I don't know if it is easier or not. If you have any idea on how to create a "dotnet host" built for Android, please share it here.

**Comment by fanyang-mono** [comment]
I implemented the one app per test project approach. This is the test result, from my local run.

Time Elapsed 03:57:33.26
Test run finished.

Total tests run    : 2354
Total passing tests: 2354
Total failed tests : 0
Total skipped tests: 0

**Comment by fanyang-mono** [comment]
The one app per test project approach didn't work on CI. That approach would have worked the best, if it was possible to build Android apps on helix machines to build apps in parallel. However, the helix machines are not designed to build Android apps, but to run tests in Android apps only. Therefore, they don't have Android toolchain installed to build Android apps.

As a result, I had to move Android apps creating process to the test build phase, which should be done on build machines. Build machines are designed to build Android apps. And they should have Android toolchain installed. Now building Android apps are happening in sequential order. Building one app per test won't make sense any more, since it would take a long time. Eventually, I decided to bundle tests together the way as they were bundled when creating XUnitWrapper.
