### ISSUE TITLE
XmlReader.IsStartElement namespace argument should allow null

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#41461]
## Background and Motivation

XmlReader has 3 overloads of `IsStartElement`:

https://github.com/dotnet/runtime/blob/46dd8ed88bd5f1968ff09aa36d64667c1547aa19/src/libraries/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs#L805-L807

Calling the last overload with `ns == null` doesn't act like calling the middle overload. In other places in XmlReader, the "namespace" parameter is optional and marked with `string?`, but this one is being annotated as non-nullable because if you passed in `null`, it would always return `false`.

In the [.NET Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/member-overloading) we have:

✔️ DO allow null to be passed for optional arguments.

We should consider changing this overload to be `string? ns`, and making this API act accordingly.

## Proposed API

```diff
namespace System.Xml
{
    public abstract class XmlReader
    {
        public virtual bool IsStartElement() { } 
        public virtual bool IsStartElement(string name) { } 
-       public virtual bool IsStartElement(string localname, string ns) { } 
+       public virtual bool IsStartElement(string localname, string? ns) { } 
```

## Usage Examples

``` C#
XmlReader r = ...;

string? ns = GetOptionalNamespace();
r.IsStartElement("Customer", ns);
```

As the API exists today, callers will instead be forced to check for `null` and call the other overload themselves:

``` C#
XmlReader r = ...;

string? ns = GetOptionalNamespace();
if (ns == null)
{
    r.IsStartElement("Customer");
}
else
{
    r.IsStartElement("Customer", ns);
}
```

**Comment by krwq** [comment]
@eerhardt one thing to note is that in case of overload without namespace the namespace is ignored. In case of this overload null may mean:
- no namespace (empty namespace) / default namespace
- ignore namespace

we should figure out how to interpret that and do some research on what customers would expect

**Comment by KalleOlaviNiemitalo** [comment]
I don't think it should treat `string localname` ([local name](https://www.w3.org/TR/2009/REC-xml-names-20091208/#dt-localname)) as `string name` ([qualified name](https://www.w3.org/TR/2009/REC-xml-names-20091208/#dt-qualname)) just because `string ns` is `null`.

If I'm writing an XML deserializer that should compare [expanded names](https://www.w3.org/TR/2009/REC-xml-names-20091208/#dt-expname) regardless of which namespace prefix is used, then I should avoid `IsStartElement(string name)` and instead use `IsStartElement(string localname, string ns)`. But if `ns == null` causes the latter to behave like the former, then it will be harder for me to be sure I did it right. I don't think there is a scenario in which the caller of `IsStartElement` would want a runtime decision on whether to use _Namespaces in XML_ semantics or not.

So, for `IsStartElement(localname, ns: null)`, my order of preference would be:

1. Return `false` regardless of `localName` -- current implementation, no compatibility risk, easy to document
2. Throw `ArgumentNullException` -- consistent with `XNamespace.GetName`, but would be a breaking change
3. Same as `IsStartElement(localName, ns: string.Empty)` -- seems inconsistent with existing APIs
4. Same as `IsStartElement(name: localName)` -- does not seem useful; consistent with undocumented behavior of `XmlWriter.WriteStartElement(string localName, string ns)`

If the treatment of `string ns` in `XmlReader.IsStartElement` is changed, then `XmlReader.ReadStartElement` should be changed similarly.

**Comment by krwq** [comment]
@eerhardt I generally agree with @KalleOlaviNiemitalo + what I wrote above, I'm leaning toward closing this as "won't fix" given the confusion this would cause. Please re-open if you feel strongly about fixing this.
