### ISSUE TITLE
GA versioning for System.Numerics.Tensors

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#41560]
Do we want to ship a stable version for System.Numerics.Tensors or dont ship any preview after rc2.

cc @ericstj @ViktorHofer @eerhardt @safern

**Comment by eerhardt** [comment]
I don't believe we want to ship a stable version of this package at this time.

cc @jeffhandley @pgovind @eiriktsarpalis - the owners listed on https://github.com/dotnet/runtime/blob/master/docs/area-owners.md.

**Comment by ericstj** [comment]
We should just remove this from dotnet/runtime and put back to corefxlab.  It was only moved to dotnet/runtime because it needed to ship *a* stable version and at the time corefxlab couldn't do that.  Now that corefxlab has arcade infra I think this package should be moved back.

For 5.0 let's make sure not to ship any stable versions.  For 6.0 + let's move it back to corefxlab.

**Comment by safern** [comment]
@jkotas was suggesting we move these to runtimelab. What would be the benefit of one over the other?

**Comment by jkotas** [comment]
The right place for experiments going forward is runtimelab. 

Once we get runtimelab fully up and running, we should plan on archiving corefxlab. It is mentioned in https://github.com/dotnet/runtime/issues/35609 .

**Comment by Anipik** [comment]
The 5.0.0 related work has been done
