### ISSUE TITLE
Better way to build non-stable non-shipping packages with non-private & non-experimenatal strings in their name

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#41561]
There are couple of properties that need to be set in order to not build the non-stable non-shipping packages.
We set them no the basis of package names containing private or experimental string in their names.

System.Numeric.Tensors and Microsoft.Extensions.HostFactoryResolver.Sources doesnt fall in that category. we should either change the name or find a better way to set these properties.

cc @ericstj @ViktorHofer @safern

**Comment by safern** [comment]
This is how we do it for System.Numerics.Tensors:
https://github.com/dotnet/runtime/blob/c4841c5b62cb23b8d27fc7b675bb0d5515fbf827/src/libraries/System.Numerics.Tensors/Directory.Build.props#L5-L7

I think this is fine as we have it because even though this is a shipping package, we don't want to make it stable so we need to set these properties, one for the package version and `IsShippingAssembly=false` for the version info in the assembly metadata to match the package version. `System.Numerics.Tensors is a shipping package, jut without a stable version. I think having granular properties is good cause it gives you flexibility on what to do.

**Comment by jkotas** [comment]
It would be best for all unstable experimental packages to live in dotnet/runtimelab, and move them to dotnet/runtime only once we are ready to ship them as stable.

**Comment by ViktorHofer** [comment]
> System.Numeric.Tensors and Microsoft.Extensions.HostFactoryResolver.Sources doesnt fall in that category. we should either change the name or find a better way to set these properties.

Closing as System.Numerics.Tensors ships publicly now and Microsoft.Extensions.HostFactoryResolver.Sources is just a transport package. We could change its name but given that AspNetCore and EF would need to react to it, I don't think it's worth it.
