### ISSUE TITLE
LightInjectDependencyInjectionSpecificationTests are failing with out of memory exceptions

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#41778]
Build https://dev.azure.com/dnceng/public/_build/results?buildId=793381&view=logs&j=ed31f2e8-9a21-528b-426c-e91b77680964&t=f58a0a3e-bd0a-579e-dcbb-ae97d27253d6

Console log https://helix.dot.net/api/2019-06-17/jobs/77f0a034-53e6-4107-a9ef-be398d1926d8/workitems/Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests/console

**Comment by eerhardt** [comment]
Looking at history test results for this test:

https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA21RTU/DMAy991dYO4HUv7DD0JjUSWPAJnHOErNlTZ3KcYBK/Hicdh8XcojtPNvv2VnHQ6p+oed4RiuwjofG1fBiOqxhFzNbtfuh1/sp+6DQTgwLOqhh5cmn0+i+ZcxYitR/5dgji8fS9xw9QevJzT0RMjxUoGePSd4x5SBpjO/8G5RTVJYJra96PiK3jWA36bpGK/ZILgwX4ucvJGmKnAUfc6dBmrQX7MdiLz4SjBPYds/GFmCDKZlj8ZaZTcko5CYVuxAl6UUxzfal25W5cRfd3ydkvKiF+RxmK+PDDAy5W2cbSYynBLNtlu3nBrvIw03PlPvvRPfCJfb6jGSHhsqaSl31WOk0435AFx3Z6XoPw/1XHCYLlENIEEySP6b3QDjpAQAA

it shows that this is the only time the test has failed for `OutOfMemoryException`. I think it was a machine configuration issue. The test has been passing since.

So I'm going to close this issue for now, since there is no way to investigate this. We can re-open it if we see if failing again.
