### ISSUE TITLE
HTTP Pre-authentication does not appear to work for Basic auth

### ISSUE THREAD

**Issue by smashery** [dotnet/runtime#42045]
### Description

The [HttpWebRequest.PreAuthenticate](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.preauthenticate?view=netcore-3.1) method claims to "send an HTTP Authorization header with requests after authentication has taken place", if set to `true`. This is not the behaviour that I observe, when accessing a web server that requires Basic auth.

Code to reproduce:

```
        static void SendRequest(string url, string username, string password)
        {
            HttpWebRequest req = WebRequest.Create(url) as HttpWebRequest;
            req.PreAuthenticate = true;
            req.KeepAlive = true;
            req.Credentials = new NetworkCredential(username, password);
            WebResponse resp = req.GetResponse();
            resp.Close();
        }
```
I then call this function two times, with the same parameters each (pointing to a web server that requests Basic Auth). 

* Running this code in .NET Core, and watching in Wireshark, I observe a 401, then a 200, then a 401, then a 200. Every new HttpWebRequest object seems to disregard the PreAuthenticate value
* Running this exact same code in .NET framework, I observe a 401, then a 200, then a 200: this seems to respect the PreAuthenticate value.

In case it makes a difference, here are the connection details I've been testing against: https://overthewire.org/wargames/natas/natas0.html

### Configuration

Tested on:
* .NET Core 3.1 (works fine on .NET Framework 4.7.2)
* Win10 2004
* x64

### Regression?

I tested on a few other versions (2.1 and 1.1); they seemed to display the same behaviour.

**Comment by wfurt** [comment]
The properly maps directly to [HttpClientHandler.PreAuthenticate](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.preauthenticate?view=netcore-3.1). The difference is that Framework has global ServicePointManager and global connection pool. With .NET Core, WebRequest sites on top of HttpClient and that will get re-created in your case and it will loose authentication state. 

I would recommend to use HttpClient directly if you can and reuse same instance for multiple requests. 
WebRequest was marked as obsolete in #41400. We can probably update documentation to make this clear. 
https://github.com/dotnet/corefx/pull/41462 added some caching for underlying HttpClient but that will not work for your case because it will fail in AreParametersAcceptableForCaching()

**Comment by smashery** [comment]
Thanks for the response.
