### ISSUE TITLE
Cancellation of Socket.ConnectAsync intermitently hangs

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#42198]
**When `Socket.ConnectAsync` is cancelled it might lead to a deadlock.**

The cancellation code for [`MultipleConnectAsync`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs#L320-L320) tries to acquire a lock which is held by the `connectAsync` continuation (triggered by [`DoDnsCallback`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs#L94)). The continuation then tries to [dispose](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs#L112) of the cancellation registration which will wait for all the callbacks if they've already been triggered.

This is easily reproducible with our HTTP stress suite (for HTTP 1.1 runs longer than 30 mins).

The biggest impact of this issue is that it prevents us from getting reasonable results from HTTP 1.1 stress pipeline on master. The pipeline gets cancelled on timeout and no results are available ([AzDO empty logs](https://dev.azure.com/dnceng/public/_build/results?buildId=807101&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=6c56d998-158d-5232-283c-5140104799fc)).

**Comment by geoffkizer** [comment]
In AttemptConnection, when ConnectAsync completes synchronously, we are calling InternalConnectCallback directly. This is bad since the caller of AttemptConnection should be holding the lock here.

We should instead return to the caller and do the call to InternalConnectCallback outside the lock.

Additionally, we should add asserts wherever we take the lock, but especially in the callbacks like InternalConnectCallback, that the lock is not already held by this thread -- basically, `Debug.Assert(!Monitor.IsEntered(_lockObject))`.

And if a method is assuming the caller is holding the lock, like AttemptConnection is, we should add an assert that the lock is actually held. This is valuable not just to detect bugs, but also to document the expectation of the function.

**Comment by riberk** [comment]
Is there a workaround? I have the same problem and i don`t know how to solve it from outside of the Socket class

**Comment by ManickaP** [comment]
The only workaround is to avoid cancellation during socket connect. I don't know your exact problem so I cannot help much further at this point.
