### ISSUE TITLE
JsonElement with Undefined kind

### ISSUE THREAD

**Issue by DsAekb** [dotnet/runtime#42249]
[Here](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.writeto?view=netcore-3.1) it is said that JsonElement.WriteTo throws the InvalidOperationException when the ValueKind is Undefined.

My question is why it does that? How is Undefined value not valid for the serialization/deserialization?

This behaviour doesn't allow to use Undefined together with System.Text.Json even though it is declared [there](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonvaluekind?view=netcore-3.1#System_Text_Json_JsonValueKind_Undefined) as a valid value.

**Comment by bartonjs** [comment]
A JsonElement with the Undefined ValueKind represents effectively uninitialized data (the only way to get one should be `default(JsonElement)`), and is logically equivalent to the value in ECMAScript when reading an unset property (`var data = obj["some property no one set"];`).  There's no representation of that concept in JSON, because if anything gets written down the value is no longer Undefined, it's whatever defined value it had. Writing it as the empty string would possibly work, but would result in an invalid JSON document.

Utf8JsonReader has a similar Undefined concept because it's also a struct, and needs to describe the state that it's in if it gets created with `default(Utf8JsonReader)`.  Neither of these values should be encountered in normal processing.

Is there somewhere that you're encountering Unknown elements on a regular basis?

**Comment by DsAekb** [comment]
Hey @bartonjs, thanks for your reply. Indeed `undefined` is not a valid value for JSON unlike in JavaScript, my bad.
