### ISSUE TITLE
Question: SpinWait normalization does not take into account the dynamic CPU frequency. Is this a problem?

### ISSUE THREAD

**Issue by ikopylov** [dotnet/runtime#42268]
After migrating to .NET Core 3.1, I noticed that `Thread.SpinWait` latency increased due to the introduced SpinWait normalization (tested on pre-Skylake CPU). In my project, I tried to reproduce the same normalization behavior for the desktop framework, but got stuck with unstable results due to dynamic CPU frequency. The CPU decreases its frequency on idle, which results in an increase in SpinWait latency, which results in a lower measured normalization coefficient. After looking at the  .NET Core source code (https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/yieldprocessornormalized.cpp#L15), I noticed that it can suffers from the same issue. It can measure the coefficient at low CPU frequency and then use it for high load scenarios.

So the question is: should the SpinWait normalization handle dynamic CPU frequency?

Tag @kouvel as the one who implemented SpinWait normalization feature

**Comment by kouvel** [comment]
I'm not seeing much difference in measured values based on CPU frequency. I tried on a Skylake and a pre-Skylake processor with various power settings, starting the measurement from low frequency and high frequency when the machine is idle, and I'm seeing roughly the same values. When the measurement starts the processor/core frequency is being increased briefly, so not sure yet if the frequency itself could affect the measurement.

What you might be seeing is that the normalization done in .NET Framework is different from that done in .NET Core.

In .NET Framework, even after normalization a `Thread.SpinWait(1)` would yield for a shorter duration on a pre-Skylake processor than on a Skylake processor. The normalization there mainly affects `Thread.SpinWait(n)` where `n` is a larger value, then the actual number of yields done would be scaled down on a Skylake processor to simulate the yield time on a pre-Skylake processor. This was mainly for compatibility with existing spin-waits that were tuned for pre-Skylake processors (which may have to be retuned for Skylake processors).

In .NET Core, the normalization is the other way around, where on pre-Skylake processors a spin-wait tries to simulate a Skylake processor, so a `Thread.SpinWait(1)` would yield for longer on a pre-Skylake processor. This was done because the yield duration was very short on pre-Skylake processors such that a single yield was unlikely to see a meaningful state change, and it allows longer and shorter spin-wait loops to behave similarly on both types of processors such that spin-waits can be tuned once and work similarly on both types of processors.

Shorter spin-waits may work fine on both types of processors but larger/longer ones may need to be retuned. If possible I suggest using the `SpinWait` struct when retuning, as that has some improvements in .NET Core.

**Comment by ikopylov** [comment]
I have tested my own SpinWait normalization code on Bradwell i5-5287U, and saw results in range [2, 10]. 2 - when CPU frequency is at 0.78 GHz after idle, and 10 in TurboBoost mode when CPU frequency is at 3.3 GHz. In my tests the frequency increases from low value to it's normal value after roughly 50ms of CPU burning, while SpinWait normalization code works only for about 20ms. Probably, because .NET Core measures normalization factor during application start-up, these whole start-up procedure can increase frequency to the normal value before normalization code runs and that's why the difference is not critical.

> Shorter spin-waits may work fine on both types of processors but larger/longer ones may need to be retuned.

I agree with that, that's why I think that it is better just to leave things as is.

> If possible I suggest using the SpinWait struct when retuning, as that has some improvements in .NET Core.

**Comment by kouvel** [comment]
I see, yea that makes sense, I figure the delay is based on cycles and can scale with frequency and also between processors. Some processors also have a large difference between base and max frequency, so even normalizing based on the max delay (when processor is say using only one or two cores) may not work well at base frequency (when processor is using all cores), but that would probably be a decent approach. Unfortunately I don't think there is an easy way to get the max delay and 50 ms is a fairly long time to spend during startup. The normalization tries to normalize to a certain amount of time currently as an easy way to work similarly between processor types.

There isn't a good way currently to have spin-waits work similarly between .NET Core and .NET Framework. If the spin-waits are short enough it may not matter. If longer spin-waits are necessary and are causing problems, it may be possible to tune the spin-wait for .NET Framework and expose a scaling factor in .NET Core where the `n` in `Thread.SpinWait(n)` can be divided by that to get similar spin-wait behavior between the two. It's unlikely that we would be changing the spin-wait behavior in the .NET Framework libraries.

**Comment by ikopylov** [comment]
As i see, with the measurement approach, it is almost impossible to obtain the stable and accurate normalization factor everywhere. There will always be some configurations in which the results will be awkward. Probably it can be extended with table based approach, where normalization factors will be pre-calculated for wide range of well-known CPUs and measurement will be taken for unknown CPUs only.

A possible alternative approach is to use `rdtsc` CPU instruction inside spin-wait loop, but, unfortunately, this instruction is CPU dependent.


> If longer spin-waits are necessary and are causing problems, it may be possible to tune the spin-wait for .NET Framework (for pre-Skylake processors) and expose a scaling factor in .NET Core where the n in Thread.SpinWait(n) can be divided by that to get similar spin-wait behavior between the two. 

Thanks! In my project I ended up with the similar solution: I chose .NET Core as baseline and adjusted spin-wait intervals to its level. For .NET Framework I implemented SpinWait normalization in a similar way to .NET Core (measure the normalization factor and multiply `iteration` parameter by this factor). As a result, in the worst case on .NET Framework on pre-Skylake I got smaller delay than expected, but this is not a problem. It is much worse to get longer delay than expected.

**Comment by kouvel** [comment]
> Probably it can be extended with table based approach, where normalization factors will be pre-calculated for wide range of well-known CPUs and measurement will be taken for unknown CPUs only.

It's a maintenance nightmare, each generation of processors has many different kinds of processors, it would not be feasible. The CPU could provide the info instead. An interesting question is what info could be provided (or gathered) that would help. How long a spin-wait needs to be can depend on many things (memory/cache speed, how long it takes for caches to become consistent, what happens after the spin-wait (context-switch, lock contention, etc.), etc.), and with processor heuristics changing timings I'm not sure there is a single answer to it. In some ways it makes sense for the delay to be cycle-dependent, but in other ways it doesn't seem useful.

**Comment by kouvel** [comment]
Also curious about your spin-wait scenario, could you describe?

**Comment by ikopylov** [comment]
> Also curious about your spin-wait scenario, could you describe?

I have a custom Semaphore implementation in my library, written back in 2014 (https://github.com/qoollo/dotNet-turbo/blob/master/src/Qoollo.Turbo/Threading/SemaphoreLight.cs). At the time, it outperformed `SemaphoreSlim`, especially in some critical corner cases. It uses spin-wait before expensive `Monitor.Wait` (just like `SemaphoreSlim`), and it is critical to have a predictable spin delay to avoid excessive CPU usage. 

In addition, I use `Thread.SpinWait` in many multi-threaded tests to simulate CPU activity, and after adding support for .NET Core 3.1, that tests started to fail due to a timeout. But this case is easy to fix without SpinWait normalization by simply updating the iteration number.

**Comment by kouvel** [comment]
Thanks for the info. A possibility may be to redo the measurement for a bit longer at some point after startup. Closing for now, will keep an eye out for similar issues.
