### ISSUE TITLE
Support natural size data types in the CLR

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/runtime#4233]
There are cases (in particular on OSX) where native APIs are defined in terms of the natural size of the platform.   This means that APIs use 32-bit integers on 32-bit platforms and 64-bit integers in 64-bit platforms.

Mono uses a poor man's approach to solve this problem, and we introduce the structures System.nint, System.nuint and System.nfloat that stand for native integer, native unsigned integer, and native float.   These data types will be 32 bits or 64 bits depending on the platform.

The usual set of operators on ints, uints and floats are defined on those structures.

The Mono runtime then has special support to turn sequences that would invoke those operators into the native representation for it.

This means that code that would pass two nint structures, and call the addition operator on it are turned into a regular integer addition operation with no performance loss.   

This is the poor man's way of introducing a new data type that is not part of the CIL spec.

This is what we published on the subject:

http://developer.xamarin.com/guides/cross-platform/macios/nativetypes/

**Comment by benaadams** [comment]
> This proposal needs to explain why we need more than just nicer `IntPtr` support at the C# level. 

There are other .NET languages.

**Comment by tannergooding** [comment]
@benaadams, could you elaborate?

Other languages (such as F#) already support `IntPtr`/`UIntPtr` with operators since it is the framework type defined to match the runtime `native int` type (which itself has the direct IL support). C# is just exposing the new `nint`/`nuint` types to be partially erased wrappers over `IntPtr`/`UIntPtr` so that the operators can be exposed in a non breaking way (that is, you will write `nint` but it will emit as `[AttributeIdentifyingAsNativeInt] IntPtr` in metadata: https://github.com/dotnet/csharplang/pull/2833).

`nfloat` is a new concept (to the runtime, framework, and language) but is realistically macOS/iOS specific. Apple has also been dropping 32-bit support entirely and there is really only legacy and a small selection of other devices (such as the watch, iirc) where this would be relevant. This leads me to believe that `nfloat` would be best supported by a user (or possibly framework) defined type that is `float` or `double` depending on the target platform bitness.

**Comment by benaadams** [comment]
So VB will be able to do use apis that expose `nint` (as they will be `IntPtr`); however the api changes for it don't expose comparison operators for `IntPtr` https://github.com/dotnet/runtime/issues/21943; so you couldn't use it as a loop iterator value without doing `i.CompareTo((IntPtr)upperbound) = 0`

**Comment by tannergooding** [comment]
> however the api changes for it don't expose comparison operators

Right, `IntPtr` is functionally the same as `Int32` and so it shouldn't directly expose user defined operators (and it minimally doing so in .NET 4 is one reason why we needed to go down the partial erasure route). Languages will need to treat it as a primitive type and emit the right IL instructions if they want operator support to be available.

@KathleenDollard or @jaredpar might be able to comment on if there are any plans for VB in particular.

**Comment by jaredpar** [comment]
> might be able to comment on if there are any plans for VB in particular.

There are not for `nint`

**Comment by jkotas** [comment]
The bulk of this is covered by nint/nuint added for C# 9.

If we still need nint/nuint/nfloat for Xamarin.iOS compatibility, it would be best to create a new issue for it.
