### ISSUE TITLE
PostJsonAsync<string> can't deserialize response

### ISSUE THREAD

**Issue by Odis25** [dotnet/runtime#42492]
i trying to get string response from my API and there is some error occured:

Here is my API method:

```
public class AuthenticationController : ApiController
{
    public async Task<ActionResult<string>> PostAsync(CreateTokenCommand credentials)
    {
        string test= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9";

        return Ok(test);
    }
}
```

Here is my calling method:

```
public async Task Login(UserCredentials model)
    {
        try
        {
            var result = await _httpClient.PostJsonAsync<string>("https://localhost:44373/api/authentication", model);       
        }
        catch (Exception ex)
        {
            throw ex;
        }
    }
```

And it gives an exception: 

> 'e' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

It is the bug or i miss something?
And what is correct way to solve this problem?

**Comment by Clockwork-Muse** [comment]
> `_httpClient.PostJsonAsync(...)`

I'm having a terrible time finding the actual documentation for this method, but as near as I can tell it's in an ASP.NET package.

That said, it looks like it's attempting to parse the string as a JSON object.  Which implies that the method assumes that since you _sent_ a JSON object, you want to _receive_ a JSON response as well (because that's how most JSON APIs work).

So either you need to change your API to return a JSON object, or manually serialize the object to a JSON string and send/receive the raw string.

**Comment by layomia** [comment]
> I'm having a terrible time finding the actual documentation for this method, but as near as I can tell it's in an ASP.NET package.

cc @Jozkee, do you know where the docs live?

**Comment by Jozkee** [comment]
`Microsoft.AspNetCore.Blazor.HttpClient` was an experimental package, I don't think there are any docs related to it.
cc @pranavkm
