### ISSUE TITLE
Add UTF8 (and maybe UTF16) to System.Runtime.InteropServices.CharSet + Marshal class

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/runtime#4257]
Currently marshaling in .NET has three modes: Ansi, Unicode (platform dependent) and "Auto" which picks a good default between those two. The meaning of Unicode is closely associated with Window's UTF16.

There is today no convenient and reliable way to do UTF8 encoding, and at best we have an ambiguous definition of what Unicode is.

There are enough bits on the metadata tables to add these two values.

People can resort to custom marshalers (slow, cumbersome, everyone has to do it), or manual marshaling, or hope that the platform does the right thing.    

Anecdotally: this also happens to be oldest Mono bug that is still open.

The world has spoken, and UTF8 is the standard, we should have first-class support for it both for P/Invoke signatures as well as the various helper methods in Marshal.

**Comment by Serentty** [comment]
@migueldeicaza Has anything happened related to this in the past few years? Especially now that .NET is focusing on better Unicode support with stuff like ``System.Text.Rune``, it seems like this would be a logical step.

**Comment by danmosemsft** [comment]
cc @eerhardt @GrabYourPitchforks

**Comment by migueldeicaza** [comment]
Nothing has happened.   It is funny because this issue was the oldest bug we kept open for Mono - filed by Red Hat sometime around 2002-2003.

We tried ECMA at the time, we tried every contact we had, and even now it seems to be a part of the code that nobody wants to touch and is scared of changing.   After Xamarin was acquired I had various discussions in person about it.   

At this point developers have resorted to a spectrum of workarounds, hacks and band aids, depending on just how badly you need this and how much performance you require.   

In the end, given that there are suboptimal workaround prevents this from being considered.

The world continues, but it remains unnecessarily complex for newcomers.

**Comment by jkotas** [comment]
We tried to add `CharSet.UTF8`, but it turned out to be pretty difficult and far-reaching. The issue https://github.com/dotnet/runtime/issues/17000 on this is still open. You can see some of the difficulties in closed PR https://github.com/dotnet/coreclr/pull/18186. At this point, the most likely way we are going to fully address this is via interop source generators that we are starting to prototype. cc @elinor-fung @AaronRobinsonMSFT 

In the mean time, the following related thigs happened that made the UTF8 interop story better:

- Performance of UTF8 encoding / decoding was improved about an order of magnitude since .NET Core project started.
- `Span<T>` makes interop is easier to write, more performant and more secure.
- `Marshal.LPUTF8Str` was added
- `Marshal.PtrToStringUTF8`, `Marshal.StringToHGlobalUTF8` and `Marshal.StringToCoTaskMemUTF8` APIs were added.
- We have started using these new functions in the core framework, e.g. here: https://github.com/dotnet/runtime/blob/07a5ee89b835a915ff3ac082ba3677fe39384a18/src/libraries/Common/src/Interop/OSX/Interop.CoreFoundation.CFString.cs#L46 .

**Comment by migueldeicaza** [comment]
Those APIs and similar ones are the sort of bandaids I was referring to.   They exist in assorted ways across cross platform rejects because of the missing attribute. 

I looked at the issue and could not figure out what part of it was the blocking one?

**Comment by jkotas** [comment]
There was nothing blocking. 

It is just a lot of work to get the design proposed here pushed through the system. In addition to implementing it in both CoreCLR and Mono runtimes for all situations where interop does string marshaling, there is also changing Roslyn, changing ilasm/ildasm and number of other tools and libraries that operate on IL, etc.

The interop source generators will make it much easier. Proposed design 
https://github.com/dotnet/runtime/blob/master/docs/design/features/source-generator-pinvokes.md

**Comment by Serentty** [comment]
So you're saying that if you use ``DllImportAttribute`` with source generators, it will be possible to specify UTF-8 in a portable way, and that people should use that going forward instead of the old ``DllImport``?

**Comment by AaronRobinsonMSFT** [comment]
>So you're saying that if you use DllImportAttribute with source generators, it will be possible to specify UTF-8 in a portable way, and that people should use that going forward instead of the old DllImport?

@Serentty It is a little more nuanced than that. With the source generators for P/Invokes proposal, we will be able to support UTF-8 in a portable and real way that doesn't cost any where near as much as the referenced PR (https://github.com/dotnet/coreclr/pull/18186). The goal of source generators for P/Invokes is to enable support of many language and cross-platform features that can be much cheaper than the high cost of updating the built-in environment (e.g. [`Span<T>`](https://github.com/dotnet/runtime/issues/9113)). I say more nuanced because the exact shape and primary focus of v1 of the feature isn't defined yet. This conversation though does seem to warrant making it higher priority, but it is still a bit away from being released.

For now, as @migueldeicaza stated, it is "unnecessarily complex" but  reducing that complexity is going to be possible with the source generator approach.

**Comment by Serentty** [comment]
I see, thanks.

**Comment by AaronRobinsonMSFT** [comment]
Now that the [LibraryImport generator](https://github.com/dotnet/runtime/issues/60595) (i.e., source generated `DllImport`s) has been exposed as a publicly consumable tool, this issue should be explored relative to that effort. This specific issue is being close due to first class support in the LibraryImport generator for UTF-8. See https://github.com/dotnet/runtime/pull/67635.
