### ISSUE TITLE
Tracking issue: enable more MSVC warnings

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#42767]
*Initial cost estimate*: 1 week
*Initial contacts*: @trylek, @GrabYourPitchforks, @janvorli 

We enable the following warning codes (as error) on some internal runs as part of compliance checks. The warnings are reviewed by hand. The manual reviews always show that we're ok, but it would be nice if we could turn these on as part of the public build. There's a little bit of work involved here to make things compile cleanly. But it would save us the trouble of running through manual review every release.

```cmake
add_compile_options(/we4018)
add_compile_options(/we4055)
add_compile_options(/we4146)
add_compile_options(/we4242)
add_compile_options(/we4244)
add_compile_options(/we4267)
add_compile_options(/we4302)
add_compile_options(/we4308)
add_compile_options(/we4509)
add_compile_options(/we4510)
add_compile_options(/we4532)
add_compile_options(/we4533)
add_compile_options(/we4610)
add_compile_options(/we4611)
add_compile_options(/we4700)
add_compile_options(/we4701)
add_compile_options(/we4703)
add_compile_options(/we4789)
add_compile_options(/we4995)
add_compile_options(/we4996)
```

**Comment by jkotas** [comment]
We set warning level 3 at https://github.com/dotnet/runtime/blob/master/eng/native/configurecompiler.cmake#L438 . Majority of the warnings in this list are warning levels 1-3, so they should be enabled by default. 

The clrcompression build is one exception that is not using the central setting and disables all warnings:  https://github.com/dotnet/runtime/blob/master/src/libraries/Native/Windows/CMakeLists.txt#L4 . Maybe you are seeing this flagged because of that?
