### ISSUE TITLE
Question about optimization of System.Globalization.IdnMapping

### ISSUE THREAD

**Issue by RamType0** [dotnet/runtime#42793]
https://github.com/dotnet/runtime/blob/a8b793c9e3d0096a8486a178e9409d95543a8caa/src/libraries/System.Private.CoreLib/src/System/Globalization/IdnMapping.Icu.cs#L10-L52

Why we allocate new array instead of using `ArrayPool<char>.Shared` at here?

And also...

https://github.com/dotnet/runtime/blob/a8b793c9e3d0096a8486a178e9409d95543a8caa/src/libraries/System.Private.CoreLib/src/System/Globalization/IdnMapping.cs#L154-L166

It seems that this method's implementation doesn't need pinned pointer of input,so we could use ref instead of pointer.
and we could also avoid output pinning by using `new string(ReadOnlySpan<char>)` overload.

Is there any advantages of current implementation?

**Comment by stephentoub** [comment]
> Why we allocate new array instead of using ArrayPool<char>.Shared at here?

It technically could use the array pool. I expect it just hasn't been done because we expect the vast majority of inputs here to never hit this path, and thus it's not worth the extra complexity to pool for only an occasional allocation.  Are you seeing this code path got frequently? Can you share the scenario?

> It seems that this method's implementation doesn't need pinned pointer of input,so we could use ref instead of pointer.

The cited method is just a helper called from both the ICU and NLS implementations, which currently work in terms of pointers, hence this does, too.

**Comment by RamType0** [comment]
> > Why we allocate new array instead of using ArrayPool.Shared at here?
> 
> It technically could use the array pool. I expect it just hasn't been done because we expect the vast majority of inputs here to never hit this path, and thus it's not worth the extra complexity to pool for only an occasional allocation. Are you seeing this code path hit frequently? Can you share the scenario?

I see.
I was just researching common threshold of whether using stackalloc or ArrayPool,so we have no scenario.
Thanks!

> > It seems that this method's implementation doesn't need pinned pointer of input,so we could use ref instead of pointer.
> 
> The cited method is just a helper called from both the ICU and NLS implementations, which currently work in terms of pointers, hence this does, too.

It seems that many slow pass of code in IdnMapping must use `fixed` bacause of this signature. 

I think replacing it by ref will simplify code,and also better for performance,isn't it?

**Comment by stephentoub** [comment]
> It seems that many slow pass of code in IdnMapping must use fixed bacause of this signature.

It's the other way around: this signature is the way it is because the call sites have a pointer and a length.  This code is simply a helper that was refactored out of both callers to avoid the code duplication.  If the callers had an array, this would use an array; if they had a span, this would use a span; and if they had a ref/length, this would use a ref/length.

> also better for performance,isn't it?

Unlikely.  The callers both P/Invoke, which means a pointer needs to be passed out to native code, which means the heap-based object needs to be pinned, whether it's done manually via `fixed` or automatically via a marshaling stub generated by the runtime for a P/Invoke that has a ref in the signature (and the latter incurs additional cost).

But you're of course welcome to give it a try and measure it.  If you come up with a solution that is both simpler and performs just as well, we'd welcome a PR.

**Comment by danmosemsft** [comment]
This seems answered.
