### ISSUE TITLE
Backgroundservice throws System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart. 

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/runtime#42825]
I wrote backgroundservice in asp.net core which starts a new thread inside StartAsync

**Comment by eerhardt** [comment]
This isn't an Extensions.Hosting issue - this is the way Threading + async works.

In `RunHB` above:

```
private async void RunHB()
        {
            while (true)
            {
                try
                {
                    //some logic
                }
                finally
                {
                    await Task.Delay(10000);
                }
            }
        }
```

When you start a Thread against a method that is `async void` and you `await` inside of that method, the original Thread you started runs until the first asynchronous `await` and then it returns the Task to the caller and the Thread completes. So the next time in your `ExecuteAsync` loop you call `HBThread.IsAlive` it will return `false` because that Thread has completed (even though it has queued more work with the `while(true)` and `Task.Delay`. When this work continues - it continues on a different Thread.

So in the `ExecuteAsync` loop, you try calling `Thread.Start()` again on an already completed Thread - and it is throwing an exception.

What you really want to do here instead is to use `Task.Run` inside your `ExecuteAsync` loop to kick off a "background-to-the-background" task. You can then check the Task that is returned from `Task.Run` for completion/results.
