### ISSUE TITLE
SignData() using a generated private ECDsa/ RSA key

### ISSUE THREAD

**Issue by ggjjj** [dotnet/runtime#42869]
I would like to use the `SignData()` API of [ECDsa](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.signdata?view=netcore-3.1) and [RSA](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.signdata?view=netcore-3.1) but would like to read the EC parameters and RSA parameters from a generated private key of my choice so that I can sign the data with the private key.

For ECDsa, I see `Create` [API](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.create?view=netcore-3.1)  which takes the `ECParameters `object as input. But there is only one API `ExportParameters` [API](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.exportparameters?view=netcore-3.1) and it does not take a private key as input to get the `ECParameters`. is there a way to achieve it ? I would like to do the same for RSA as well. 

Thanks!

**Comment by vcsjones** [comment]
There are several ways to get keys in to `ECDsa` and `RSA` depending on what format your keys are in, and whether they are public or private keys.

For `ECDsa` (and `ECDiffieHellman` as well) the `ECParameters` type can hold either a private key and/or a public key. In ECDsa, the `Q` field represents the public part of the key, and the `D` field is the private key. When you use `ExportParameters`, the return type will always be `ECParameters` for both public and private exports. If you don’t include the private key, the `D` field will be null, otherwise it will be included.

If you have `ECParameters`, you can use [`ImportParameters`][1], like so:

```c# 
using ECDsa ecdsa = ECDsa.Create(yourEcParameters);
```

If your ECParameters contains the private key, then the private key will get loaded. If it doesn’t, then it will load with just the public key.

For RSA, it’s largely the same idea. There is `ExportParameters` that has an option for just the public key, or the full private key. RSA parameters are different, if its just the public key, only `Modulus` and `Exponent` will have a value.

Again, with RSAParameters there is also [`Create`][2]:

```C#
using RSA rsa = RSA.Create(yourRsaParameters);
```


[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.importparameters?view=netcore-3.1
[2]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.create?view=netcore-3.1#System_Security_Cryptography_RSA_Create_System_Security_Cryptography_RSAParameters_

**Comment by ggjjj** [comment]
Thanks for the explanation. Will close it!
