### ISSUE TITLE
Question: Examining the evaluation stack using a profiler

### ISSUE THREAD

**Issue by ddiefenthaler** [dotnet/runtime#43034]
Hello, I'm trying to access specific values from the intermediate language evaluation stack during the execution. My motivation behind this is the extension of [siemens/drace](https://github.com/siemens/drace) to use a profiler for managed code. In order to perform the race detection from within the runtime I do not only need access to the load/store instruction themselves but also the addresses they operate on. Especially the stores are troublesome for me, as the address hides behind the value to be stored on the evaluation stack.

My current approach is to instrument the intermediate language using the method from the [ReJITEnterLeaveHooks](https://github.com/microsoft/clr-samples/tree/b8e9f7df084084dc627711342a0d601725237867/ProfilingAPI/ReJITEnterLeaveHooks) sample profiler. This solution uses P/Invokes to call a native function and passes information from the stack to the profiler this way. The downside of this is, that it is only possible to access the topmost element easily, as this call consumes the values from the stack and they have to be duplicated beforehand.

What I would like to do is to duplicate multiple values of the evaluation stack at once. The problem is that I don't know how to achieve this with the lower elements.
- One approach I can see is to store the topmost values in a local variables and restore it later on. My concern with that is the types of the values on the stack. As I'm planning to use this with arbitrary code I have no control over the types and I don't think that it is feasible to create a local variable for every possible type.
- Another idea would be to analyze the code and instrument it earlier on, so that the evaluation stack is in the state we want later on. The downside of that would be that that would be very complicated and error-prone.
- My question now is whether I am missing something and if there is a simpler approach to solve this problem. (I.e. if there were non-consuming calls or other profiling methods that would help in this case.)

**Comment by josalem** [comment]
CC @noahfalk @davmason @dotnet/dotnet-diag

**Comment by davmason** [comment]
Hi @ddiefenthaler,

Generally speaking there are two ways to inspect managed code using the profiler APIs.
- ELT hooks will give you the ability to inspect arguments at the function boundaries, so arguments and return values, but not in the middle of a method. It is a lot easier to use than IL rewriting but is limited in what exactly you can inspect. See https://github.com/dotnet/runtime/blob/master/src/tests/profiler/native/eltprofiler/slowpatheltprofiler.cpp for how they work.
- IL rewriting (as you are doing now). It is a lot harder to do, but you can achieve anything as long as you are willing to put the effort in.

I don't fully understand your use case so it's hard to offer advice on which solution is the best. If getting the function arguments and return values is sufficient for you then I would suggest going with ELT hooks. Otherwise if you need to inspect locals in the middle of a method's execution you would have to use IL rewriting. Duplicating the values doesn't seem like it would be a crazy amount of effort, though.

Another option outside of the profiling APIs to consider is writing a static analyzer using the roslyn apis - see https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix. If you don't need information at runtime, it will be a lot less work to write a static analyzer than to do IL rewriting.

**Comment by tommcdon** [comment]
Closing this issue since it sounds like it has been answered. Please let us know if that isn't true and we will re-activate.

**Comment by ddiefenthaler** [comment]
Hi, sorry for the delayed response.
Yes my question is answered and I think this issue can remain closed.

I think in the meantime I have a pretty good idea how I want so solve my problem,
and if you are interested in it I can share my solution in a future PR to [rejitprofiler](https://github.com/dotnet/runtime/tree/master/src/tests/profiler/native/rejitprofiler) once it is done.

Nevertheless @davmason, thank you very much for your response.

Unfortunately for my use case it is not enough to access the values at function borders.
For the race detection I want to track all memory accesses, even if they occur in the middle of a long function.
I am aware of the ELT hooks and I'm already using them where applicable.

While static analysis is also a good consideration, the runtime nature is an integral part of the objective.

I was afraid that there was no simpler solution but I still wanted to check, so that I do not overlook anything.
I think that the duplication of the values should be actually straight forward,
with the hard part being the cleanup afterwards so that the IL remains valid through all branches.
