### ISSUE TITLE
Where is the source code of the system.runtime.4.1.0.nupkg ? 

### ISSUE THREAD

**Issue by sunny868** [dotnet/runtime#43248]
Where is the source code of the system.runtime.4.1.0.nupkg ?  
I try to build it using dotnet/corefx for run:
`./build.sh--configuration Release --pack /p:DisableCrossgen=true /p:PortableBuild=true /p:SkipTests=true `
But this package is not generated in the artifects/ directory.

**Comment by safern** [comment]
That would be in the 1.0 source code. https://github.com/dotnet/corefx/blob/release/1.0.0/src/System.Runtime

> But this package is not generated in the artifects/ directory.

That is because System.Runtime no longer ships as a package, it is instead part of the shared framework. Which is what is shipped as part of the product and what you get as part of an application when you create a new .NET Core app. This change was made starting `.NET Core 2.0`.

**Comment by sunny868** [comment]
> ystem.Runtime no longer ships as a package...This change was made starting `.NET Core 2.0`.

but I found the lastest version v4.3.1 updated 2019/2/12 at https://www.nuget.org/packages/System.Runtime/

**Comment by safern** [comment]
No that version is built from corefx 1.1.0 branch, which is .NET Core 1.1: https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Runtime/dir.props#L5

**Comment by ViktorHofer** [comment]
Closing as answers provided.
