### ISSUE TITLE
System.Text.JSON.Serialization.JsonConverter issues with VB

### ISSUE THREAD

**Issue by paul1956** [dotnet/runtime#43253]
### Description
Trying to replace Newtonsoft.Json with Text.JSON and getting error BC30668 'Utf8JsonReader' is obsolete: 'Types with embedded references are not supported in this version of your compiler.'.	

```
Imports System.Text.Json
Imports OxfordDictionariesAPI.Models

Namespace OxfordDictionariesAPI.Converters
    Public Class JSONEntriesConverter
        Inherits Serialization.JsonConverter(Of SearchResult)

        Public Overrides Sub Write(writer As Utf8JsonWriter, value As SearchResult, options As JsonSerializerOptions)
            Throw New NotImplementedException()
        End Sub

        Public Overrides Function Read(ByRef reader As Utf8JsonReader, typeToConvert As Type, options As JsonSerializerOptions) As SearchResult
            Throw New NotImplementedException()
        End Function
    End Class
End Namespace
```

```
Public Class SearchResult
    Public Property Metadata As Metadata
    Public Property Results As Result()
End Class
Public Class Metadata
    Public Property Provider As String
End Class
Public Class Result
    Public Property Id As String
    Public Property Language As String
    Public Property LexicalEntries As LexicalEntry()
    Public Property Type As String
    Public Property Word As String
End Class
```
### Configuration
Windows 10 x64
Microsoft.WindowsDesktop.App 5.0.0-rc.2.20466.10

### Regression?
Works with VB in Newtonsoft.Json

**Comment by layomia** [comment]
The issue here is that stack-only types like `Utf8JsonReader` and `ReadOnlySpan<T>` cannot be referenced in VB source. There is a tracking issue for this on the VB side (https://github.com/dotnet/vblang/issues/297), so I'll close this as a dup.

From some limited local testing, using `JsonSerializer`, `JsonDocument`, `JsonElement`, and `Utf8JsonWriter` directly appears to work as expected.

A workaround here is to implement custom converters in a C# library assembly, and reference the assembly from your VB project.

FYI @KathleenDollard @terrajobst since this was discussed offline.

Also cc @jaredpar on if the Roslyn team is considering this support anytime soon.
