### ISSUE TITLE
Proposal: Add fast path for an empty array to Array.ConvertAll

### ISSUE THREAD

**Issue by lechu445** [dotnet/runtime#43281]
In case of an empty array, `Array.ConvertAll` method allocates a new empty array as a return value.

I propose to return `Array.Empty<TOutput>()` in case on an empty input array.

This is similar approach as in many `ToArray` method implementations (e.g. in `System.Collections.Generic.List<T>` or `System.Span<T>`).

**Comment by jkotas** [comment]
`Array.ConvertAll` is a low-performance method for convenience. We prefer the code of methods like that to be as simple as possible. The code for extra special cases is not free.

Have you run into a situation where this special case would make meaningful performance difference?

**Comment by lechu445** [comment]
My use-case is preparing database queries using NpgSql driver:
```c#
    public async Task UpdatePersonNames(Person[] persons)
    {
      using (var cmd = new NpgsqlCommand(updatePersonsSql, conn))
      {
        cmd.CommandType = CommandType.StoredProcedure;
        cmd.Parameters.Add(new NpgsqlParameter("Ids", persons.Select(p => p.Id).ToArray());
        cmd.Parameters.Add(new NpgsqlParameter("Names", persons.Select(p => p.Name).ToArray());
        await cmd.ExecuteNonQueryAsync();
      }
    }
```

The method can be optimized to reduce Linq usage:
```c#
    public async Task UpdatePersonNames(Person[] persons)
    {
      using (var cmd = new NpgsqlCommand(updatePersonsSql, conn))
      {
        cmd.CommandType = CommandType.StoredProcedure;
        cmd.Parameters.Add(new NpgsqlParameter("Ids", Array.ConvertAll(persons, p => p.Id));
        cmd.Parameters.Add(new NpgsqlParameter("Names", Array.ConvertAll(persons, p => p.Name));
        await cmd.ExecuteNonQueryAsync();
      }
    }
```
NpgsqlParameter, in case of collection as value, must be an array or `IList<T>` (https://github.com/npgsql/npgsql/issues/1178#issuecomment-228129585), so I think it is a common to call `.ToArray()` or `.ToList()` on result of linq `Select(...)` method.

Roslynator is going to add support for refactor such case for lists, so more people will get to know ConvertAll and will try the array equivalent.
https://github.com/JosefPihrt/Roslynator/issues/559

**Comment by Clockwork-Muse** [comment]
... for your specific use case, linq will return `Array.Empty<TOutput>()`.  It's also going to only allocate once, if the source array has a non-zero size.

It's true that linq has a slightly higher cost due to the virtual indirections, but that's almost certainly going to be dwarfed by your database call costs.

Although I think I'm somewhat more concerned about the use of arrays here, as opposed to a standard `List<T>`...

**Comment by lechu445** [comment]
But anyways, people may refactor `array.Select(predicate).ToArray()` to `array.ConvertAll(predicate)` as this is an array specific method, so they would expect that has better performance than Linq combination. As you said, in general it's true, but not for a case of an empty array.

The documentation does not say which method is a low-performance method for convenience...

**Comment by mburbea** [comment]
Is there any way the runtime could just do the same optimization it does for `""` and something like `new string('a',0)` where it will always just return the same object for empty arrays?

This optimization against wasted allocation is littered throughout the framework and user code, and results in ugly conditional code.

**Comment by jkotas** [comment]
It would be a breaking change (new array is required to return a new instance per spec). And it would likely introduce performance regression on average. The problem is that caching the empty array instance is not free and majority of places are unlikely to benefit from it. 

For short-lived arrays - like in the example from https://github.com/dotnet/runtime/issues/43281#issuecomment-706756502 - it is perfectly fine and likely more performant to just allocate an empty array.

**Comment by mburbea** [comment]
Can it just point to the already existing storage in `Array.Empty<T>()`? 
Even convenience methods that are not meant to be high performance, have this optimization special cased. E.g. Linq:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/Where.cs#L29-L34
 
I believe `new string(...)` returning string.empty is also a spec violation. Outside of odd cases, how would this change be observable, why would it lead to regression?

**Comment by Clockwork-Muse** [comment]
@mburbea - The `Empty<TSource>` in the code you linked isn't `Array.Empty()`, but `Enumerable.Empty()`.  `Array.Empty()` would be a destination type, and at that point in the code it's unknown if the collection is even going to captured (as opposed to just iterated), much less as an array (as opposed to a list or a dictionary...).  The reasoning for this specific one is to avoid the allocation of the iterator, and potentially enable further optimizations elsewhere

> Outside of odd cases, how would this change be observable, why would it lead to regression?

One possibility is data locality, because now it (almost certainly) has to jump to some other memory page (and probably invalidate at least some of the CPU cache) to access the array, instead of maybe having the array in the same memory page (for small arrays).  Additionally, there's going to be contention on the bookkeeping for the cached empty array, whereas a local empty will have none.  Reducing allocations is nice, but it's not completely free.

**Comment by lechu445** [comment]
@jkotas @Clockwork-Muse thank you for the explanation. You are right, it would be a breaking behavioral change. 

The spec for `Array.ConvertAll()` clearly says that it returns a new array. But it looks like there are some collections that spec for method `.ToArray()` also says that it returns a new array, but it's not true for the case of an empty array.
Examples:
- `Copies the elements of the List<T> to a new array.` https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.toarray?view=netcore-3.1
- `Copies the Queue elements to a new array.` https://docs.microsoft.com/en-us/dotnet/api/system.collections.queue.toarray?view=netcore-3.1
- `The Split methods allocate memory for the returned array object and a String object for each array element. ` https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netcore-3.1#performance-considerations

**Comment by eiriktsarpalis** [comment]
> But it looks like there are some collections that spec for method .ToArray() also says that it returns a new array, but it's not true for the case of an empty array.

That probably suggests we should improve the docs, and not change the logic?

**Comment by lechu445** [comment]
I will close the proposal as we agreed that it won't be done due to breaking change and change in performance characteristics.

@eiriktsarpalis Yes, in my opinion the documentation could be improved regarding the discussion.

Please feel free to re-open this issue if you have any other thoughts.
