### ISSUE TITLE
DirectoryInfo and FileInfo should not be sealed

### ISSUE THREAD

**Issue by IdkGoodName** [dotnet/runtime#43283]
DirectoryInfo and FileInfo shouldn't be sealed. It's super annoying to use "unions" if you want to hold either ZipEntry or FileInfo. You could just instead inherit from them both and create common interface for them.

I know this could be solved if Microsoft made interface for both ZipEntry and FileInfo, but I am using completely different zip library, not .NET's System.IO.Compression.

**Comment by huoyaoyuan** [comment]
> It's super annoying to use "unions"

This pattern is never considered in mind.

Once you are receiving these objects from other classes, rather than constructing yourself, inheriting will be meaningless. This applies to `ZipArchiveEntry`. For `SharpCompress` you do have the ability to override `CreateEntryInternal`, but there's also a lot of work.



> I know this could be solved if Microsoft made interface for both ZipEntry and FileInfo

I can't imagine how many members they can share. The BCL doesn't make interface without very important members to share(e. g. `IHasXXX`).


Generally speaking, to create abstractions among types that you don't own, is explorer by the language feature "roles" (dotnet/csharplang#164).

**Comment by carlossanlop** [comment]
Thank you for opening an issue, @IdkGoodName . We do not think this is a change we would want to make in our libraries. It would be a breaking change, the two types belong to different assemblies, and as @huoyaoyuan pointed out, there isn't any relationship between a `ZipEntry` and a `FileInfo`.

**Comment by IdkGoodName** [comment]
> I know this could be solved if Microsoft made interface for both ZipEntry and FileInfo, **__but I am using completely different zip library, not .NET's System.IO.Compression.__**

As I said, I am using completely different library, which means I am not really talking about ZipEntry.

Still, there are some common things. For instance, `FullName`, `LastWriteTime`, `Length`, `Name`.(You could also add `Extension` and `LastWriteTimeUtc` to ZipArchiveEntry and add them to interface).

**__My original point was that DirectoryInfo and FileInfo shouldn't be sealed, as you will need to do "unions" for them.__**
