### ISSUE TITLE
Possible PAL structural issues

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#43312]
This bug was reported (I think) for the Linux kernel. Does the .NET PAL make this sort of problem more likely?

https://sourceware.org/bugzilla/show_bug.cgi?id=25847

**Comment by benaadams** [comment]
Is glibc rather than kernel? Means `pthread_cond_signal` doesn't wake up waiters

**Comment by mangod9** [comment]
Doesnt seem like there is any work required as part of this is there?

**Comment by davidwrighton** [comment]
@richlander, this isn't really an issue with the structure of the PAL, its more that in the runtime the lock we use is close in design to pthread condition variables instead of the more normal mutexes, and we have fairly fine grained locking. Unfortunately, it turns out that implementing pthreads is apparently very difficult, and it is there are some bugs in places. I don't believe there is anything we can usefully do in this space, other than continue to report bugs in pthreads to the various libc providers.
