### ISSUE TITLE
Microsoft.Extensions.Primitives.CompositeChangeToken may induce deadlocks

### ISSUE THREAD

**Issue by dlyz** [dotnet/runtime#43438]
A deadlock occurs when multiple source change tokens (at least based on CancellationTokenSource) are triggered nearly at the same time. This happens because all CompositeChangeToken.OnChange calls will try to dispose registrations, and each CancellationToken registration will wait cancellation callback to complete, but this callback calls CompositeChangeToken.OnChange.

Repro example (call it few times to reproduce):

```cs
static void TestCct(int iter)
{
	var cts1 = new CancellationTokenSource();
	var cts2 = new CancellationTokenSource();

	var ct1 = new CancellationChangeToken(cts1.Token);
	var ct2 = new CancellationChangeToken(cts2.Token);

	var cct = new CompositeChangeToken(new[] { ct1, ct2 });

	using var cctreg = cct.RegisterChangeCallback(state => Console.WriteLine("cancelled"), null);

	var t1 = Task.Factory.StartNew(() => CancelCt(cts1), TaskCreationOptions.LongRunning);
	var t2 = Task.Factory.StartNew(() => CancelCt(cts2), TaskCreationOptions.LongRunning);

	t1.Wait();
	t2.Wait();
	Console.WriteLine("Completed " + iter);

	void CancelCt(CancellationTokenSource cts)
	{
		Thread.Sleep(10);
		cts.Cancel();
	}
}
```

CancellationTokenSource.CreateLinkedTokenSource does not have this problem becase of few reasons.
This example runs without any deadlock:

```cs
static void TestLcts(int iter)
{
	var cts1 = new CancellationTokenSource();
	var cts2 = new CancellationTokenSource();

	var lcts = CancellationTokenSource.CreateLinkedTokenSource(new[] { cts1.Token, cts2.Token });

	using var cctreg = lcts.Token.Register(state => Console.WriteLine("cancelled"), null);

	var t1 = Task.Factory.StartNew(() => CancelCt(cts1), TaskCreationOptions.LongRunning);
	var t2 = Task.Factory.StartNew(() => CancelCt(cts2), TaskCreationOptions.LongRunning);

	t1.Wait();
	t2.Wait();
	Console.WriteLine("Completed " + iter);

	void CancelCt(CancellationTokenSource cts)
	{
		Thread.Sleep(10);
		cts.Cancel();
	}
}
```

There are few solutions to this.

The first solution is simple and totally non-breaking. We can rewrite part of CompositeChangeToken.OnChange as follows:

```cs
List<IDisposable> disposables;
lock (compositeChangeTokenState._callbackLock)
{
    disposables = compositeChangeTokenState._disposables;
    compositeChangeTokenState._disposables = null;
    // ...
}

if (disposables != null)
{
    // dispose registrations here
}
```

The second solution is to rewrite CompositeChangeToken to make it closer to CancellationTokenSource.CreateLinkedTokenSource. Now when source tokens invoke callbacks, CompositeChangeToken makes sure that each source invocation will last untill all CompositeChangeToken registered callbacks is completed. But CancellationTokenSource invokes callback only under first Cancel call (next calls will be completed immediately). I've made a [draft](https://gist.github.com/dlyz/f5bef9bd8da5c5d8a4c9851f41f08586) of this solution (also considers #40677).

**Comment by eerhardt** [comment]
The deadlock is actually coming from `CancellationTokenSource`. I can repro the same issue with the following code that doesn't use anything in `Microsoft.Extensions`:

```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var cts1 = new CancellationTokenSource();
            var cts2 = new CancellationTokenSource();

            var cct = new MyComposite(new[] { cts1.Token, cts2.Token });

            Console.WriteLine("Starting ");
            var t1 = Task.Factory.StartNew(() => CancelCt(cts1), TaskCreationOptions.LongRunning);
            var t2 = Task.Factory.StartNew(() => CancelCt(cts2), TaskCreationOptions.LongRunning);

            t1.Wait();
            t2.Wait();
            Console.WriteLine("Completed ");

            void CancelCt(CancellationTokenSource cts)
            {
                Thread.Sleep(10);
                cts.Cancel();
            }
        }
    }

    class MyComposite
    {
        private static readonly Action<object> _onChangeDelegate = OnChange;
        private List<IDisposable> _disposables;

        public MyComposite(IReadOnlyList<CancellationToken> changeTokens)
        {
            _disposables = new List<IDisposable>();
            for (var i = 0; i < changeTokens.Count; i++)
            {
                var disposable = changeTokens[i].UnsafeRegister(_onChangeDelegate, this);
                _disposables.Add(disposable);
            }
        }

        private static void OnChange(object state)
        {
            var compositeChangeTokenState = (MyComposite)state;

            var disposables = compositeChangeTokenState._disposables;
            Debug.Assert(disposables != null);
            for (var i = 0; i < disposables.Count; i++)
            {
                disposables[i].Dispose();
            }
        }
    }
}
```

Here's a snapshot of the Parallel Stacks window when this happens:

![image](https://user-images.githubusercontent.com/8291187/96156307-84e01400-0ed6-11eb-8daf-8bc48136d8e8.png)

The deadlock appears to come from this code:

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenRegistration.cs#L82-L100

> (assuming we are not currently called by the callback itself)

In this case, we actually ARE called by the callback itself.

Since the `private static void OnChange(object state)` method is being called from the `CancellationTokenSource.Cancel` callback, `source.IsCancellationCompleted` is still `false` - because it is still running callbacks. `source.WaitForCallbackToComplete(_id)` is called, and since we are still in `CancellationTokenSource.ExecuteCallbackHandlers`, the `ExecutingCallback` id is still set to `_id`, and `CancellationTokenSource` starts spinning infinitely here:

https://github.com/dotnet/runtime/blob/12025658acf6c9747fcbb63569be4107b3e0f0f3/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L794-L801

I assume the issue is `changeTokens[i].UnsafeRegister` - which doesn't capture the ExecutionContext. @stephentoub - is this messing up the "thread" check above (`source.ThreadIDExecutingCallbacks != Environment.CurrentManagedThreadId`)?  `UnsafeRegister` comes from:

https://github.com/dotnet/runtime/blob/b6af738eabf08b7e450e8a73290c2baca8635334/src/libraries/Microsoft.Extensions.Primitives/src/CancellationChangeToken.cs#L32-L37

which I believe was added by @davidfowl. Do you remember why this uses `UnsafeRegister`?

**Comment by stephentoub** [comment]
> is this messing up the "thread" check above (source.ThreadIDExecutingCallbacks != Environment.CurrentManagedThreadId)?

Nope, ExecutionContext doesn't affect on what thread the callback is invoked or the value that would be returned from these properties.

CancellationTokenRegistration.Dispose makes the guarantee that upon its return the callback has either completed running or will never run.  To make that guarantee, if the callback is already executing, it has to block until it finishes.  If you don't care about that guarantee, you can use Unregister instead of Dispose.

The repro is setting up a situation where two different cancellation callbacks are blocked disposing the other, waiting by design for the other to complete, and thus deadlocking.

**Comment by eerhardt** [comment]
> setting up a situation where two different cancellation callbacks are blocked disposing the other

Ah, that's the piece I was missing. The callback for the first register is Disposing the 2nd register. While at the same time, the callback of the 2nd register is Disposing (again) the 1st register.

> If you don't care about that guarantee, you can use Unregister instead of Dispose

I _think_ this sounds like the right answer in this case. Since we know we are calling `Dispose` during the callback, we don't need this guarantee.

**Comment by rdragon** [comment]
Threads were piling up on our servers because of this issue. Let's fix the bug. 

As Stephen Toub explains above, if you have two cancellation callbacks that are calling `CancellationTokenRegistration.Dispose` on each other, then "by design" this results in a deadlock. Example:

```csharp
var cts1 = new CancellationTokenSource();
var cts2 = new CancellationTokenSource();
IDisposable? reg1 = null;
var reg2 = cts2.Token.Register(() => reg1?.Dispose());
reg1 = cts1.Token.Register(reg2.Dispose);
Task.Run(cts1.Cancel);
cts2.Cancel(); // Deadlock
```

So we should try not to write code like this. However, in `CompositeChangeToken` this is exactly what has been done. Now it becomes easy to get a deadlock:

```csharp
var cts1 = new CancellationTokenSource();
var cts2 = new CancellationTokenSource();
var t1 = new CancellationChangeToken(cts1.Token);
var t2 = new CancellationChangeToken(cts2.Token);
var composite = new CompositeChangeToken(new[] { t1, t2 });
composite.RegisterChangeCallback(_ => { }, null);
Task.Run(cts1.Cancel);
cts2.Cancel(); // Deadlock
```

The first solution proposed by @dlyz seems to me like a good idea. It makes sure only a single thread runs all `CancellationTokenRegistration.Dispose`, preventing the deadlock.

It shouldn't matter that now the disposables are only disposed once, nor that `CompositeChangeToken.OnChange` now may return before it has unregistered itself everywhere.

I've written a unit test for this bug and implemented the solution, see [this commit](https://github.com/rdragon/runtime/commit/79632865821897f2cd93f349e052565d9fe93910). Note that my implementation differs a bit from the one of dlyz, but actually does the same thing.

Please let me know if I should create a PR for this change. If this is not the way to go then I'd also like to hear it.
