### ISSUE TITLE
Suggestion for not locking running single-file executables

### ISSUE THREAD

**Issue by UweKeim** [dotnet/runtime#43487]
In your [single-file executable](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md) proposal, I didn't find any information regarding updating and locked files.

Sorry, if I did miss it.

My suggestion is that the executable itself is not being locked when it is running, allowing the application to update itself silently and be available upon the next application restart.

The [Squirrel.Windows tool](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/5-updating.md#myapp-example) seems to do it the same way as e. g. Google Chrome does it: Having the updates install itself into child directories and always running the latest directory's executable.

Please make something similar for single-file executables, too.

**Comment by vitek-karas** [comment]
I'm sorry to reply to late to this - not sure to which version of single-file this relates to. In any case, the single-file is not meant to replace installer/updater technologies. For example one requirement on single-file is that it doesn't spawn child processes - running "mytool.exe" should run everything in that one process (so that command line integration works as expected, killing the process actually kills it, getting PID does what it's expected to do and so on).

In both .NET Core 3.1 and .NET 5 the single-file executable itself is locked because it's the main file running the application. If you want to build an auto-updater on top of it, it should be possible to use similar technique you describe, but that's out of scope for the single-file feature.
