### ISSUE TITLE
host shared framework resolution

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#43490]
The host has an opinion on where it expects to find the shared framework.

The hosts that are provided via nuget.org contain the location where Microsoft installs .NET Core.
Unfortunately, this is not the same as the location where Fedora source-build packages install .NET Core.

This causes FDD apphosts to fail on Fedora because they are unable to locate the shared framework.
It can be worked around by setting DOTNET_ROOT.

It would be good if we can make this work without having to set DOTNET_ROOT.

In https://github.com/dotnet/cli/issues/9114 we proposed probing `dotnet` on PATH as an additional resolution step to find the shared framework.

With .NET Core 3.0, the publish operation will generate a native apphost by default. That executable is affected by this issue.

@natemcmaster @KathleenDollard @richlander @livarcocc @steveharter @dleeapho @omajid @RheaAyase

**Comment by vitek-karas** [comment]
As @omajid noted above, there's a way to register a different global install location on the machine. On Windows this uses Registry, on Linux/OSX this is stored in `/etc/dotnet/install_location` (the file was renamed since the original proposal). The design is desrcibed here: https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md#global-install-to-custom-location

To make it clearer this is not exactly the same as setting `DOTNET_ROOT`. The location specified in the file becomes the global install location and as such it works for `dotnet app.dll`, SDK lookups as well as any `app` executable. `DOTNET_ROOT` only affects `app` executables, but not the `dotnet` or SDK lookups.

To configure the machine such that the global location is different from default and everything behaves as if it was the default the new location should be in the `/etc/dotnet/install_location` and `PATH` should point to the new location as well (but the .NET Core host never looks at the `PATH`, it's solely that writing `dotnet` runs the right thing).
