### ISSUE TITLE
Consider making minihost long path aware

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#43555]
## The problem
Today, the native host that's generated on project build (`bin/Release/net5.0/Program.exe`) is not long path aware, while the `dotnet` host is. This lead me personally to spend hours debugging Roslyn and MSBuild source code until I finally discovered the underlying issue. While, clearly, this problem is not affecting lot of people (I was not able to find opened issues about it), I believe there is value in aligning the behavior of the two hosts, even if just for consistency.

## Reproduction
```CMD
> dotnet --version
6.0.100-alpha.1.20506.3
> dotnet new console -n "LongPaths"
```
```C#
using System;
using System.Runtime.InteropServices;

namespace LongPaths
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"Long paths are enabled: {RtlAreLongPathsEnabled()}");
        }
		
	[DllImport("ntdll")]
	static extern byte RtlAreLongPathsEnabled();
    }
}
```
```CMD
> dotnet run
Long paths are enabled: 0
> bin\Debug\net5.0\LongPaths.exe
Long paths are enabled: 0
> dotnet bin\Debug\net5.0\LongPaths.dll
Long paths are enabled: 1
```

Note: this issue probably belongs to dotnet/sdk, but I was not sure and so opened it here.

**Comment by vitek-karas** [comment]
This is known problem tracked here: https://github.com/dotnet/sdk/issues/12904
`dotnet.exe` contains a [Windows manifest](https://github.com/dotnet/runtime/blob/master/src/installer/corehost/cli/dotnet/dotnet.manifest) which explicitly enables long path support. `apphost` doesn't have any manifest on its own, it gets one from the managed assembly (compiled in by C# compiler). The default manifest with C# compiler generates doesn't enable long path support.

A simple workaround is to add a manifest to your app - C# compiler will then use that one instead of the implicit one and it will make it to the `.exe`.

**Comment by SingleAccretion** [comment]
Thank you for the explanation! That'll close the issue then, I guess. I did end up using `dotnet myapp.dll` as a workaround, so it works for me just fine now, but I wanted to open the issue anyway even if just to add to the bucket of feedback that could be used to prioritize this work.
