### ISSUE TITLE
Double-free in OverlappedTests?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#43588]
A handful of tests in:
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Threading.Overlapped/tests/OverlappedTests.cs#L11
appear to be double-freeing the `NativeOverlapped*`.  The callback used frees it:
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Threading.Overlapped/tests/OverlappedTests.cs#L223-L232
as does the main test method, e.g.
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Threading.Overlapped/tests/OverlappedTests.cs#L189-L192
Is that intentional?

cc: @kouvel

**Comment by davidwrighton** [comment]
@stephentoub @kouvel  This looks to be intentional. The test actually creates two separate Native overlapped structures. Note that the call to MyCallback actually creates a different overlapped structure and queues another event. So, I can't explain why its done this way in the test, but it doesn't appear to be a bug.
