### ISSUE TITLE
System.Text.Json deserialization of arrays with various types

### ISSUE THREAD

**Issue by mattchidley** [dotnet/runtime#43670]
We're trying to migrate from Newtonsoft to System.Text.Json

We have a test case which checks the roundtrip of serializing an object and then deserializing that result, and comparing the deserialized result back to the original object.

The object in question is:

`new object[] { 1.1, 23.0, "sdfsd" }`

In both Newtonsoft and System.Text.Json, this is serialized into:

`"[1.1,23,"sdfsd"]"`

When deserializing the above string, Newtonsoft will return an object[] which matches the original.

System.Text.Json deserializes the above string into an object[] with JsonElements which have a ValueKind and 
value. It's important to note that this only occurs when deserializing an object[] with a variety of types.

Is this by design? I haven't been able to find any documentation regarding the expectations here.

**Comment by layomia** [comment]
Here's some documentation we have provided on this behavior: https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#deserialization-of-object-properties

Benefits
- Provides universal and consistent behavior for deserializing `System.Object` members and collection elements.
-  No "guessing" or ambiguous algorithm for what the expected primitive to return is, such as sometimes treating a JSON string as a `DateTime` (detected by parsing), or creating a `System.Double` for a JSON number if a decimal point is present (which can cause accuracy issues if `System.Decimal` is expected). Similarly, creating a `System.Int64` for a JSON number if there is no decimal point can cause range issues if a System.UInt64 or BigInteger is expected. 

Downsides
- Potential usability inconvenience when compared with the Newtonsoft.Json experience
- Perf cost due to creating `JsonElement` (whereas creating a primitive is cheaper). This perf cost was significant in 3.x-5.0 but has been recently improved in 6.0 (https://github.com/dotnet/runtime/pull/42538)

Overall, we believe that the default behavior provides the best trade-offs and prioritizes correctness over convenience and performance.

Alternatives
- For Newtonsoft-like semantics, please see this [sample](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to#deserialize-inferred-types-to-object-properties). There's also a feature request to provide a built-in, opt-in only feature that implements this behavior - https://github.com/dotnet/runtime/issues/29960.
- Utilize samples for `dynamic` deserialization which allows primitives to be returned based on typed variable assignment or explicit casts - https://github.com/dotnet/runtime/pull/42097.
