### ISSUE TITLE
There is a bug in latest Guid

### ISSUE THREAD

**Issue by ultimaweapon** [dotnet/runtime#43714]
Take a look at this line: https://github.com/dotnet/runtime/blob/0e959bef48363f762ec7189db9b317d0a6d029b5/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L755

It should writing to offset 6, not 8. I'm not sure if this effect on .NET 5 only or also 3.1 too.

**Comment by symphony2014** [comment]
@ultimaweapon @jkotas  Same issue with this line:
https://github.com/dotnet/runtime/blob/0e959bef48363f762ec7189db9b317d0a6d029b5/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L60

**Comment by stephentoub** [comment]
> I'm not sure if this effect on .NET 5 only or also 3.1 too.

It doesn't; it's only in .NET 5, and it only affects big endian machines, which is why our tests aren't failing: we're not currently routinely testing on big endian architectures.  And since coreclr doesn't currently run on big endian, it doesn't impact the official .NET 5 release.  It could affect architectures on which mono runs, however. cc: @marek-safar

**Comment by marek-safar** [comment]
big-endian support is still on a community only basis. Having said that this is 5.0 regression only with an isolated fix, we should fix it in upcoming 5.x servicing

**Comment by jkotas** [comment]
This does not make bar for servicing. There is no functional big-endian target in 5.0 to start with.
