### ISSUE TITLE
NullReference when `default` is set as optional argument default for value-typed ctor parameter

### ISSUE THREAD

**Issue by cupsos** [dotnet/runtime#43757]
#### Source code

```csharp
public record PositionalRecord(Guid st = default);

class Program
{
    static void Main(string[] args)
    {
        var data = new PositionalRecord();
        Console.WriteLine(data.ToString());
        Console.WriteLine(JsonSerializer.Serialize(data));
    }
}
```

#### Expected output

```output
PositionalRecord { st = 00000000-0000-0000-0000-000000000000 }
{"st":"00000000-0000-0000-0000-000000000000"}
```

#### Real output (NullReferenceException)

```output
PositionalRecord { st = 00000000-0000-0000-0000-000000000000 }
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.JsonParameterInfo`1.Initialize(Type runtimePropertyType, ParameterInfo parameterInfo, JsonPropertyInfo matchingProperty, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.InitializeConstructorParameters(ConstructorInfo constructorInfo)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
   at System.Text.Json.WriteStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at RecordJson.Program.Main(String[] args) in /mnt/c/Users/cupsos/Desktop/git/RecordJson/RecordJson/Program.cs:line 15
```

Also same error occured when using non primitive structs like

- DateTime
- DateTimeOffset
- Index
- BigInteger
- user defined structs
- ..etc

#### dotnet --info

```output
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100-rc.2.20479.15/

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]
  5.0.100-rc.2.20479.15 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

#### csproj

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>9.0</LangVersion>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

### Other information

I don't know how, but [RoslynPad](https://github.com/aelij/RoslynPad) can use record type with .NET Core 3.1.  
And in this enviroment, no error happen with System.Text.Json 4.7.2 to 5.0.0-preview.2.20160.6,
but after that, same error (NullReferenceException) happen.

![image](https://user-images.githubusercontent.com/24942851/96977902-aeddaa00-1558-11eb-8bd5-c52c4013577e.png)  
![image](https://user-images.githubusercontent.com/24942851/96977991-d3398680-1558-11eb-9b97-acb329bc48de.png)

**Comment by layomia** [comment]
The issue here is this [line](https://github.com/dotnet/runtime/blob/eec1e2518ebafadaa08dce19098150bd1e8f2130/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonParameterInfoOfT.cs#L31)  where the serializer expects `ParameterInfo.DefaultValue` to be non-`null` for non-nullable value-typed parameters. Instead, in this example this value is `null`.

cc @steveharter - wrt to Reflection/`ParameterInfo.DefaultValue` semantics, is this expected? I'd expect `DefaultValue` to be a boxed instance of `default(Guid)`:

```cs
using System;
using System.Reflection;

namespace StructDefaultParameterInfo
{
    class Program
    {
        static void Main(string[] args)
        {
            Type type = typeof(PositionalRecord);
            ParameterInfo stParam = type.GetConstructors()[0].GetParameters()[0];
            
            object defaultValue = stParam.DefaultValue;
            Console.WriteLine(defaultValue == null);
            // Expected: false (shouldn't `defaultValue` should be a boxed default(Guid)?)
            // Actual: true
        }

        public record PositionalRecord(Guid st = default);
    }
}
```

--- 

If the reflection behavior in this scenario is correct/expected, then we'd have to make a straightforward/easy fix on the `JsonSerializer` side.

**Comment by steveharter** [comment]
For now we should detect a `null` default value for value types and then substribute `default<T>`.

The underlying issue has some history:
- The C# compiler does not generate the `.param []` IL metadata for value types -- it says `.param [1] = nullref` for the `PositionalRecord` case. However, I believe VB would have the zeros for that metadata.
- System.Reflection doesn't attempt to fix up `nullref` metadata to `default<T>` except for some edge cases.
- The compiler will detect `nullref` value type parameters and substitute a call to initialize the value type, which is the reason why things work at runtime today outside of reflection.

If fixed in reflection, it has the potential to break others. Here's some related issues:
- https://github.com/dotnet/runtime/issues/24574
- https://github.com/dotnet/roslyn/issues/24004
- https://github.com/dotnet/runtime/issues/12924

**Comment by layomia** [comment]
Thanks @steveharter - I'll make the fix in JSON.

**Comment by layomia** [comment]
Workarounds in .NET 5:

- If feasible, don't set the default value for non-nullable value-typed parameters to `default` , OR, don't make the parameter optional.
- Use a custom converter to control (de)serialization of the type with the parameterized constructor - https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to.

**Comment by layomia** [comment]
Re-opening for .NET 5.0 servicing consideration.

**Comment by layomia** [comment]
Fixed in https://github.com/dotnet/runtime/pull/45457.
