### ISSUE TITLE
Move name resolution cancellation test into Docker

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#43816]
https://github.com/dotnet/runtime/pull/33420 introduces tests:

- DnsGetHostAddresses_PostCancelledToken_Throws
- DnsGetHostEntry_PostCancelledToken_Throws

These tests fail under a stressed CI environment as they depend on a cancellation token triggering before a DNS response comes back. To fix this, these tests might be moved into a Docker container with a non-working DNS server that will never respond.

**Comment by gfoidl** [comment]
Instead of 

> be moved into a Docker container with a non-working DNS server that will never respond

(which is quite some work), can we "flood" the dns-queue with lookup tasks and see if at least any of them will be canceled?
Something like https://github.com/gfoidl/dotnet-runtime/commit/2281e5ebe4af5b3b50d85dceb3c0c963b9edf19a

Although "a non-working DNS server that will never respond" will be safer here in regard of the race, but there will be more moving parts that need to play together nicely.

**Comment by antonfirsov** [comment]
Sounds like something to address when together (or as a precondition of) fixing #63552. I think instead of expensive infrastructure refactoring we may just try serializing them as we did with many socket tests
