### ISSUE TITLE
IPv4InterfaceStatistics OutputQueueLength in Linux seems to be a maximum size rather than current output length

### ISSUE THREAD

**Issue by rickge** [dotnet/runtime#43978]
I'm using dotnet core in Linux (version 3.1.9) with the following code:
```cs
using System.Net.NetworkInformation;
...
NetworkInterface[] netInterfaces = NetworkInterface.GetAllNetworkInterfaces();
foreach (NetworkInterface netIntf in netInterfaces)
{
    IPv4InterfaceStatistics stats = netIntf.GetIPv4Statistics();
   Console.WriteLine("Output Queue Length = " + stats.OutputQueueLength.ToString());
}
```
The value for output queue length is always 1000 when this code runs on Ubuntu 19.04, but is typically 0 when run in Windows. I'm guessing the output queue length in Linux isn't the current queue fill size as the property description indicates when running in Linux?

**Comment by Bond-009** [comment]
I think it's always 0 in Windows because it's not implemented.
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/SystemIPInterfaceStatistics.cs#L15
https://docs.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_if_row2
> OutQLen
Type: ULONG64
The transmit queue length. This field is not currently used.

This also returns the max queue size on FreeBSD and macOS (afaik).
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/BsdIpInterfaceStatistics.cs#L28
https://github.com/dotnet/runtime/blob/master/src/libraries/Native/Unix/System.Native/pal_networkstatistics.c#L560
`int	ifm_snd_maxlen;	/* maximum length of send queue */`
ref: https://opensource.apple.com/source/xnu/xnu-3789.41.3/bsd/net/if.h.auto.html

This makes me believe the property is documented incorrectly.

**Comment by alnikola** [comment]
Done.
