### ISSUE TITLE
[Wasm] linking a netstandard2.0 assembly forces a reference to System.Net.Quic

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#44033]
### Description

When building an application that references a netstandard 2.0 assembly, the following linker error happens:

```
Assembly 'Uno.Wasm.SampleNet5, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' processing 'BenchmarkDotNet, Version=0.11.5.0, Culture=neutral, PublicKeyToken=null' reference 
---> Assembly 'BenchmarkDotNet, Version=0.11.5.0, Culture=neutral, PublicKeyToken=null' processing 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' reference 
---> Assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' processing 'System.ComponentModel.TypeConverter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' reference 
---> Assembly 'System.ComponentModel.TypeConverter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' processing 'System.Xml.XDocument, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' reference 
---> Assembly 'System.Xml.XDocument, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' processing 'System.Private.Xml.Linq, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' reference
---> Assembly 'System.Private.Xml.Linq, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' processing 'System.Private.Xml, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' reference 
---> Assembly 'System.Private.Xml, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' processing 'System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' reference 
---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1009: Assembly 'System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' reference 'System.Net.Quic, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x' could not be resolved 
---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Net.Quic, Version=5.0.0.0, Culture=neutral, PublicKeyToken=x'
```

The file is created during the build process, but is not copied to the artifacts folder.

### Configuration

d84d05f898c6e46d46af6752fc1604fe639065c9

### Regression?

No

**Comment by scalablecory** [comment]
What version of .NET are you using?

CC @geoffkizer @safern

**Comment by jeromelaban** [comment]
@scalablecory A build from https://github.com/dotnet/runtime/commit/d84d05f898c6e46d46af6752fc1604fe639065c9, specifically, using the WebAssembly outputs.

**Comment by safern** [comment]
It seems like System.Net.Quic is not building for Browser at all, however System.Net.Http references it: https://github.com/dotnet/runtime/blob/d84d05f898c6e46d46af6752fc1604fe639065c9/src/libraries/System.Net.Http/src/System.Net.Http.csproj#L629

https://github.com/dotnet/runtime/blob/d84d05f898c6e46d46af6752fc1604fe639065c9/src/libraries/System.Net.Quic/src/System.Net.Quic.csproj#L4

@geoffkizer @scalablecory was that intentional?

@ViktorHofer do you know why did System.Net.Http build if it has a reference to something that should not be part of the ref for the wasm vertical?

**Comment by ViktorHofer** [comment]
> @ViktorHofer do you know why did System.Net.Http build if it has a reference to something that should not be part of the ref for the wasm vertical?

1. System.Net.Quic is marked as inbox: https://github.com/dotnet/runtime/blob/d84d05f898c6e46d46af6752fc1604fe639065c9/src/libraries/NetCoreAppLibrary.props#L67
2. System.Net.Http doesn't build against the implementation assembly but against the reference assembly which has a matching configuration: https://github.com/dotnet/runtime/blob/d84d05f898c6e46d46af6752fc1604fe639065c9/src/libraries/System.Net.Quic/ref/System.Net.Quic.csproj#L3

**Comment by ViktorHofer** [comment]
Looks like we are missing a safe-guard that guarantees that src.proj is able to build all assemblies that are part of the shared framework with a matching configuration.

**Comment by safern** [comment]
> Looks like we are missing a safe-guard that throws if an inbox ref/src isn't resolvable for the passed in configuration.

I see... so it seems like this should throw in Browser because it is inbox and we have a ref for that. We should definitely add that safe guard.

**Comment by ViktorHofer** [comment]
@geoffkizer @scalablecory as Santi asked, I assume not adding a matching configuration for Browser in the src assembly wasn't intentional?

> We should definitely add that safe guard.

Agree.

**Comment by ViktorHofer** [comment]
@Anipik is it intentional that the TargetFramework.Sdk silently continues if no suitable tfm was found for a project in the outer build?

As an example, I replaced the `$(NetCoreAppCurrent)` condition with `$(NetCoreAppCurrent)-Unix;$(NetCoreAppCurrent)-Browser` and then built the source projects: `build.cmd libs.src`.

![image](https://user-images.githubusercontent.com/7412651/97641155-85ce8500-1a42-11eb-8428-7e25b589794c.png)

It removes the inner build target frameworks and doesn't throw if there are none left:

Should this throw in the line below? https://github.com/dotnet/arcade/blob/19e7e769f7ca2ece42221f7ff951e7ec705498ec/src/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/src/build/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.targets#L21

cc @ericstj

**Comment by scalablecory** [comment]
System.Net.Http does not use System.Net.Quic when it's in the browser. It should probably just not reference it in that case.

**Comment by safern** [comment]
Sounds good. However, we should provide a PNSE assembly for `Browser` as we're providing a reference assembly for it, or not build `System.Net.Quic` for `Browser` at all.

**Comment by jeromelaban** [comment]
I've opened a larger issue about missing assemblies in the WebAssembly target, `System.Net.Quic` being one among many others (https://github.com/dotnet/runtime/issues/44044)

**Comment by ericstj** [comment]
> System.Net.Http does not use System.Net.Quic when it's in the browser. It should probably just not reference it in that case.

It must reference it because you've exposed it in the surface area: https://github.com/dotnet/runtime/commit/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7#diff-343ff8b4c3dfb2ecdeac03bdc818cca45bd8cf184d6e8eb9df9ba2763b8e6cdeR383

If you'd like to remove that dependency you could refactor that into an extension method and implement it in the Quic assembly.

> or not build System.Net.Quic for Browser at all.

We need to build a PNSE.  We cannot have different surface area exposed for the shared framework on different runtimes.  The TFM represents a set of surface area and that surface area contains `System.Net.Quic`.

**Comment by scalablecory** [comment]
Ah right. That API is temporary to be removed prior to .NET 6, so I wasn't thinking in those terms, but I guess we need to at least ensure things still work while it is in place. @geoffkizer something we need to keep in mind I guess.

**Comment by jkoritzinsky** [comment]
This is now blocking #38457 since that PR runs our closure validation on all platforms including WASM.

**Comment by ViktorHofer** [comment]
I opened https://github.com/dotnet/runtime/issues/44192 to follow-up on the missing shared framework assembly.

**Comment by akoeplinger** [comment]
#44192 was merged so this should be fixed, @jeromelaban can you please confirm?

**Comment by jeromelaban** [comment]
I can confirm that the System.Net.Quic file is now generated properly and that the linker step does not fail anymore.

Thanks!
