### ISSUE TITLE
Added cookie accessor/iterator to CookieContainer

### ISSUE THREAD

**Issue by shravan2x** [dotnet/runtime#44094]
## Background and Motivation

There's currently no way to access all cookies in a CookieContainer instance without known their domain names. CookieContainer also does not expose a list of domains it holds cookies for. I propose adding a `GetAllCookies()` method for this. It seems I'm not the only one with a use-case for it https://stackoverflow.com/questions/15983166/how-can-i-get-all-cookies-of-a-cookiecontainer

## Latest API proposal

Based on discussion below - https://github.com/dotnet/runtime/issues/44094#issuecomment-827123620

```c#
public class CookieContainer
{
  // Existing API:
  public CookieCollection GetCookies(Uri uri);

  // Proposed API:
  public CookieCollection GetAllCookies();
}
```

## Original API proposal

```c#
 public IEnumerable<Cookie> GetAllCookies();
```
or
```c#
class CookieContainer : IEnumerable<Cookie>
```

**Comment by KalleOlaviNiemitalo** [comment]
CookieContainer tries to be thread-safe, although I don't see that in the documentation. If other threads add or remove cookies while you enumerate them, does that invalidate the enumerator?

**Comment by shravan2x** [comment]
> CookieContainer tries to be thread-safe, although I don't see that in the documentation. If other threads add or remove cookies while you enumerate them, does that invalidate the enumerator?

It could invalidate it and throw an exception on the next iteration, or it could iterate an older "snapshot" similar to how `ConcurrentDictionary` works. Either would make sense to me though the latter would be preferred.

The only bad version would be one that doesn't make any guarantees and just silently corrupts itself to miss entries or return duplicate ones.

**Comment by geoffkizer** [comment]
Seems like just implementing `IEnumerable<Cookie>` is the cleanest approach here, unless there's some problem with that.

**Comment by geoffkizer** [comment]
Actually, we already did this. See https://github.com/dotnet/corefx/pull/30080. I knew it sounded familiar.

**Comment by shravan2x** [comment]
@geoffkizer That's weird, I just made a new project using .NET 5.0 and I still can't get it to work:

![image](https://user-images.githubusercontent.com/4096676/97921533-ef36e800-1d0f-11eb-80d2-03e54e135661.png)

**Comment by geoffkizer** [comment]
Sorry, the linked issue is about CookieCollection, not CookieContainer.

**Comment by shravan2x** [comment]
Ah that makes sense. Agree that implementing `IEnumerable<Cookie>` is the cleanest approach.

**Comment by KalleOlaviNiemitalo** [comment]
Could even implement `IReadOnlyCollection<Cookie>`. It would add only a `Count` property to `IEnumerable<Cookie>`, and `CookieContainer.Count` exists already.

Implementing `IReadOnlyCollection<Cookie>` could cause `ImmutableArray.CreateRange<T>(IEnumerable<T>)` to throw if it first reads `Count` and allocates an array and then another thread adds more cookies. However, I suppose `ConcurrentDictionary<TKey,TValue>` already has that problem, so developers can be expected to cope.

Perhaps, instead of having `CookieContainer.GetEnumerator` make a snapshot, there should be a thread-safe `Clone` method or a copy constructor. That way, an application that cannot ensure single-threaded access to `CookieContainer` would be able to clone the container and then enumerate the clone at its leisure.

**Comment by geoffkizer** [comment]
Yeah, the more I think about this, the more I'm kinda concerned about enumerating a CookieContainer directly.

Another suggestion would be to add a method (ToCookieCollection?) that creates a snapshot as a CookieCollection, which you can then iterate as you want without worrying about someone else mutating it.

**Comment by shravan2x** [comment]
Couldn't we do that (i.e. create a snapshot) internally and iterate over that one in `GetEnumerator`? It would be the same as you mentioned but avoids the `GetAllCookies()` extra method.

**Comment by geoffkizer** [comment]
Why is that better?

**Comment by shravan2x** [comment]
I suppose it's a matter of opinion, and I hold mine lightly - Since it's a container object (like lists or sets), it should be iterable using a for-each loop or LINQ query.

What are your thoughts on doing both i.e. `GetAllCookies()` and a new shortcut `GetEnumerator() { return Snapshot().GetAllCookies() }`?

**Comment by geoffkizer** [comment]
I think that since we have `GetCookies(uri)` already, adding something like `GetAllCookies()` seems pretty natural.

Then the question is, should we also add an enumerator that calls GetAllCookies under the covers? It doesn't add any new capability, and it might not be obvious to users that it implicitly does a snapshot. So I think I'd lean toward not doing this.

> Since it's a container object (like lists or sets), it should be iterable using a for-each loop or LINQ query.

I'm somewhat sympathetic to this, but I think this is a bit of an unusual case. CookieCollection is the collection class for Cookies and supports the methods you'd expect -- IEnumerable, ICollection, etc. CookieContainer is optimized for multithreaded access when you are adding/updating/etc cookies. As long as it's easy to go from one to another, I think that's sufficient.

**Comment by shravan2x** [comment]
Sounds reasonable to me, let's go with `GetAllCookies()` 👍

**Comment by KalleOlaviNiemitalo** [comment]
Huh, CookieCollection has a [System.Net.Cookie this\[int index\]](https://docs.microsoft.com/dotnet/api/system.net.cookiecollection.item?view=net-5.0#System_Net_CookieCollection_Item_System_String_) indexer, but CookieCollection.Add allows multiple cookies with the same Name to be added to the collection, provided that the Domain or Path differs. I suppose CookieContainer.GetAllCookies() can return a CookieCollection, then.

**Comment by geoffkizer** [comment]
cc @antonfirsov -- you know this code better than I do, any thoughts?

**Comment by antonfirsov** [comment]
> [...] I suppose CookieContainer.GetAllCookies() can return a CookieCollection, then.

@KalleOlaviNiemitalo considering the first part of the sentence, I guess you rather wanted to say *" I suppose CookieContainer.GetAllCookies() can return a CookieCollection, then."* :)

> So I think I'd lean toward not doing this.

@geoffkizer I agree. Adding a single enumerator method seems to be the safest thing to do here. I don't think we should return `CookieCollection`. I'm not very familiar enough with call sites, so I may be wrong, but it looks like we rarely use it (0 usages in `System.Net.Http`, 1 in `System.Net.WebSockets`, the rest is in `System.Net.Requests` stuff). Considering the concern pointed out by @KalleOlaviNiemitalo looks like it's technically not possible.

The only remaining open question before an actual API proposal is whether we should return an `IReadonlyList<Cookie>` or simply just `IEnumerable<Cookie>`?

**Comment by shravan2x** [comment]
> The only remaining open question before an actual API proposal is whether we should return an IReadonlyList<Cookie> or simply just IEnumerable<Cookie>?

Of course `IReadonlyList<Cookie>` has slightly more methods, but `IEnumerable<Cookie>` is probably easier to implement and solves all for-each and LINQ usages. People could also just call `.ToList()` trivially. So I think `IEnumerable<Cookie>` is a good option.

**Comment by KalleOlaviNiemitalo** [comment]
@antonfirsov, isn't that exactly what I wrote already?

To elaborate: The CookieCollection.Item\[string name\] indexer gives the impression that CookieCollection ([source](<https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Net.Primitives/src/System/Net/CookieCollection.cs> "runtime/CookieCollection.cs at v5.0.0-rtm.20519.4 · dotnet/runtime")) has at most one cookie for each name. CookieCollection.Add(Cookie) however has no such restriction: it calls CookieCollection.IndexOf(Cookie), which uses CookieComparer ([source](<https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/Common/src/System/Net/CookieComparer.cs> "runtime/CookieComparer.cs at v5.0.0-rtm.20519.4 · dotnet/runtime")), which compares Name, Domain, and Path. Thus, it would be technically possible to have CookieContainer.GetAllCookies() return a CookieCollection, even if that might look a bit odd.

**Comment by aepot** [comment]
I have to bump this issue while a lot of developers still using either Reflection or `BinaryFormatter` to get all Cookies e.g. to save ones to a file.

As for me it's doesn't matter how accessing to all Cookies will be implemented. I prefer any way to get all Cookies because it's better than no way.

Just need something better than this extension:
```c#
public static CookieCollection GetAllCookies(this CookieContainer container)
{
    CookieCollection allCookies = new CookieCollection();
    Hashtable domainTable = (Hashtable)container.GetType()
        .GetRuntimeFields()
        .First(x => x.Name == "m_domainTable")
        .GetValue(container);
    FieldInfo pathListField = null;
    foreach (object domain in domainTable.Values)
    {
        SortedList pathList = (SortedList)(pathListField ??= domain.GetType()
            .GetRuntimeFields()
            .First(x => x.Name == "m_list"))
            .GetValue(domain);
        foreach (CookieCollection cookies in pathList.GetValueList())
            allCookies.Add(cookies);
    }
    return allCookies;
}
```
The job is loading+saving all the Cookies for `HttpClientHandler` at the application startup and shutdown. `BinaryFormatter` helped me before but you know [the story](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md).

Also the most popular answers to this problem on StackOverflow have ~77k views in total: [1](https://stackoverflow.com/a/15991071/12888024), [2](https://stackoverflow.com/a/14074200/12888024).

**Comment by aepot** [comment]
@shravan2x Upon thread-safe `CookieContainer` nature I suggest a method that returns fullfilled collection (snapshot) as `CookieCollection` instead of yielding through `IEnumerable`.

**Suggestion1.** Add method `GetAllCookies()`
```c#
public CookieCollection GetAllCookies();
```

**Suggestion2.** Add overload for [`GetCookies()`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Primitives/src/System/Net/CookieContainer.cs#L781) that accepts 0 arguments.

```c#
public CookieCollection GetCookies();
```

I think `GetAllCookies()` looks more explicit as method returning all the cookies. But `GetCookies()` overload for me looks reasonable too as it was a first thing I tried to get all cookies.

**Comment by antonfirsov** [comment]
@geoffkizer to me the only open question was if `GetAllCookies()` should return `CookieContainer` or just `IEnumerable<Cookie>`. I was against `CookieCollection` but since it looks like an ugly legacy type, but it's more consistent with the existing `CookieContainer` API surface so I recommend to go with the following explicit overload:

```C#
public CookieCollection GetAllCookies();
```

@geoffkizer if you agree, I recommend to push this into the API review queue, so we have a chance to get this into 6.0. It's a trivially small feature, and it's no fun that reflection+BinaryFormatter (🤯 ) workarounds keep spreading over stackoverflow as described in https://github.com/dotnet/runtime/issues/44094#issuecomment-820262017. The number of upvotes on SO indicate that this is a visible API gap.

**Comment by shravan2x** [comment]
@antonfirsov I agree that getting some API out for this functionality is more important than small differences in proposed APIs. At its core `CookieContainer` seems very similar to `ConcurrentDictionary` so an iterator could be reconsidered too. I don't have a strong opinion.

**Comment by aepot** [comment]
@shravan2x I guess you may edit the first post according to template linked in the [API Review Process](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md).

**Comment by geoffkizer** [comment]
Ok, I updated the initial post to reflect the consensus proposal and marked this as ready for review.

Any feedback is welcome.

**Comment by karelz** [comment]
@geoffkizer FYI: I updated top post to keep visible Original and Latest API proposals -- easier for following discussions ...

**Comment by geoffkizer** [comment]
I marked this as 6.0 so it will get reviewed in the near future. That doesn't mean this is committed for 6.0.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Net
{
    partial class CookieContainer
    {
        public CookieCollection GetAllCookies();
    }
}
