### ISSUE TITLE
Proposal - Provide an overload for MemoryMarshal.AsBytes to create the byte representation of a struct

### ISSUE THREAD

**Issue by Dewera** [dotnet/runtime#44113]
## Background and Motivation

There are many instances in which in retrieving the byte representing of an unmanaged `struct` is needed. As an example, writing a `struct` into a `MemoryStream` and PInvoke calls that take byte representations of `structs` (i.e. WriteProcessMemory) come to mind.

[This](https://stackoverflow.com/questions/3278827/how-to-convert-a-structure-to-a-byte-array-in-c) stack overflow post highlights the issue

## Proposed API

```c#
public static Span<byte> AsBytes<T> (ref T structure) where T : struct;
```

## Usage Examples

There are many use cases, but the simplest I think of is the original example of a `MemoyStream`

Consider the following

```c#

struct CustomStruct
{
    int M1;
    Guid M2;
}

MemoryStream stream;

...

CustomStruct cs = new CustomStruct();

// Do operations with the struct

...

// Write the custom struct into the stream

Span<byte> structBytes = MemoryMarshal.AsBytes(ref cs);

stream.Write(structBytes);
```
-->

## Alternative Designs

There are ways to do this using the existing API's such as

```c#

CustomStruct cs = new CustomStruct();

Span<CustomStruct> csSpan = new CustomStruct[] {cs};

Span<byte> structBytes =MemoryMarshal.Cast<CustomStruct, byte>(csSpan );

// Or

CustomStruct cs = new CustomStruct();

Span<byte> structBytes = new byte[Unsafe.Size<T>()];

MemoryMarshal.Write(structBytes, ref cs);
```

However, having an API that explicitly states `AsBytes` is likely to make more sense to readers as well as remove the need for boilerplate code / the introduction of helper methods in code bases that need this functionality.

## Risks

None as far as I am aware

**Comment by BreyerW** [comment]
You can also create span of 1 length with memory marshal then use asbytes from same type. Looks a bit ugly but works rn

**Comment by GrabYourPitchforks** [comment]
p/invoking APIs that take a struct is already straightforward: use pointers. Define the p/invoke parameter as `MyStruct*` or `void*`, then get the address and pass it along. Or define the parameter as `ref MyStruct` and let the p/invoke marshaler handle it.

If you need to get the raw bytes in order to perform manipulation of the structure, then as @BreyerW said, this can be done via `MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref myStruct, 1))`. Consult the table at https://github.com/dotnet/runtime/issues/41418 for any type safety considerations you'd need to take into account + any usage notes.
