### ISSUE TITLE
Incomplete arm intrinsics substitions

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44146]
A list of ARM intrinsics https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.NoArmIntrinsics.xml is incomplete. It's missing APIs like Rmd and Dp.

When fixing this it would be also helpful to split 32 and 64 bit ARM substitutions.

@eerhardt

**Comment by eerhardt** [comment]
I was actually considering getting rid of these substitution files. Do they actually provide value since for each architecture the `XXX.IsSupported` is already hard-coded to `false` when it isn't supported:

https://github.com/dotnet/runtime/blob/1ade5327c94d1b67622705b9f9b76fac4b49e677/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/Dp.PlatformNotSupported.cs#L17

Shouldn't the linker pick that up by itself without the substitution file?

**Comment by marek-safar** [comment]
> Shouldn't the linker pick that up by itself without the substitution file?

The implementation has `Intrinsic` which means the linker ignores the implementation because it's "unknown". If it would accept `false` then we would have no intrinsic code everywhere.

**Comment by eerhardt** [comment]
> If it would accept false then we would have no intrinsic code everywhere.

The pattern for when the intrinsic could be supported is to recurse on the same method/property:

https://github.com/dotnet/runtime/blob/1ade5327c94d1b67622705b9f9b76fac4b49e677/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/Dp.cs#L17

and

https://github.com/dotnet/runtime/blob/1ade5327c94d1b67622705b9f9b76fac4b49e677/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/Dp.cs#L32

> The implementation has Intrinsic

I wonder if that is intentional, or a mistake? @tannergooding @CarolEidt - is there a reason we put `[Intrinsic]` on the `IsSupported => false;` properties in the `XXX.PlatformNotSupported.cs` files?

**Comment by marek-safar** [comment]
> is there a reason we put [Intrinsic] on the IsSupported => false; properties in the XXX.PlatformNotSupported.cs files?

That could work if we remove it from all PlatformNotSupported.cs files

**Comment by jkotas** [comment]
It is intentional: https://github.com/dotnet/coreclr/pull/23751. It is to allow the JIT to recognize and strip the unreachable code early.

**Comment by tannergooding** [comment]
The `PlatformNotSupported.cs` files explicitly treat only `IsSupported` as intrinsic as it helps with dead code elimination even in scenarios where inlining can't happen (such as too many locals or too much code).

**Comment by eerhardt** [comment]
OK, then I'll go ahead and add the extra substitutions for ARM. Thanks for the information @jkotas and @tannergooding.
