### ISSUE TITLE
How to use Socket to write high-performance sending data in concurrent scenarios?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#44182]
If I want to write a high-performance Socket communication program, should I use mmap and socket.sendfile?  
How to use Socket to write high-performance sending data in concurrent scenarios?

**Comment by wfurt** [comment]
There may not be simple answer to the simple question. I strongly recommend to build prototypes using different strategies and measuring perf - if you really care. Also API performing well on one platform may show different characteristic on different OS (or version) even if we try to minimize such behavior. 
Since you mentioned sendfile, that is certainly not a bad choice since on most OSes this is performed by kernel itself e.g. without all the overhead of user space application.

**Comment by NMSAzulX** [comment]
@wfurt Thank you for your answer. I'm trying the "sendfile" solution, and I'm also following .NET 5 System.Net.Connections API. I don't know how to make the right choice between them. I am learning this example: https://github.com/davidfowl/CommunityStandUpNet5/blob/master/APIPlayground/Program.cs, and this is not a very simple example. I am confused, this should not be easy to use in a short period of time. :)

**Comment by antonfirsov** [comment]
@NMSAzulX System.Net.Connections has been removed from the final version of .NET 5, for explanation see https://github.com/dotnet/runtime/pull/41648#issuecomment-687465097.

What's most performant also depends on the application. I'm not sure if `SendFile` is the best approach when it comes to sending small chunks of data, but might worth a try. You may also get some inspiration from Kestrel's socket transport layer, but it's definitely a very complex code:
https://github.com/dotnet/aspnetcore/tree/ad94d41a7f786bd11e1a3e1f599feeaac147610a/src/Servers/Kestrel/Transport.Sockets/src/Internal

**Comment by NMSAzulX** [comment]
@antonfirsov Oh! Thank you very much. Through your and wfurt's description, I think these feature will have an answer in .NET 6.0.   I had to use another approach, such as Kestrel or httpClient. :)
