### ISSUE TITLE
Why is AppDomain still in net core ？ 

### ISSUE THREAD

**Issue by bluetianx** [dotnet/runtime#44249]
AppDomain was deprecated, why is AppDomain still in net core ,etc System Domain shared Domain and Default AppDomain?
Is there any  Design Docs  about Domain ?

**Comment by jkotas** [comment]
`System.AppDomain` type is in .NET Core public surface for compatibility. It turns out that most methods `System.AppDomain` do not have much to do with app domains and work fine even with appdomain support removed.

We have eradicated appdomain handling in many places in the internal implementation. There are still many places left (in particular in comments) that reference appdomains. We are cleaning them up as we run into them.
