### ISSUE TITLE
Test failure: System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(useExistingWatchers: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44277]
failed in job: [runtime-libraries-coreclr outerloop 20201104.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=875322&view=ms.vss-test-web.build-test-results-tab&runId=28002120&resultId=102641&paneView=debug)

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 190
~~~

**Comment by carlossanlop** [comment]
According to Kusto, we started hitting this on 10/03 but haven't hit it anymore since 11/04. We can reopen if we see it again. We can see it's now passing consistently.


JobId | Source | Started | Method | Result | WorkItemFriendlyName | Class
-- | -- | -- | -- | -- | -- | --
11593228 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:19 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593228 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:19 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593230 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:19 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593230 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:19 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593232 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:20 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593232 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:20 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593234 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:20 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11593234 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/03 12:20 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657206 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 10:46 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657206 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 10:46 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657207 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 10:46 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657207 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 10:46 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657949 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:23 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657949 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:23 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657950 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:23 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657950 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:23 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657964 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:24 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657964 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:24 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657965 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:24 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
11657965 | ci/public/dotnet/runtime/refs/heads/master | 2020/10/08 11:24 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
12003517 | ci/public/dotnet/runtime/refs/heads/release/5.0 | 2020/11/03 12:01 PM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
12020241 | ci/public/dotnet/runtime/refs/heads/master | 2020/11/04 11:44 AM | FileSystemWatcher_File_Create_ForceLoopRestart | Fail | System.IO.FileSystem.Watcher.Tests | System.IO.Tests.FileSystemWatcher_Multiple_Test
