### ISSUE TITLE
OleDbConnectionInternal.BuildInfoLiterals should return non-null

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#44288]
This method itself is internal but it affects annotations of couple of public methods.

OleDbConnectionInternal.BuildInfoLiterals code suggests that:

```csharp
                if (null == dbInfo)
                {
                    return null;
                }
```

is likely a dead code since dbInfo is annotated as non-nullable which suggests this method will never return null.

Found when applying nullable annotations

**Comment by ajcvickers** [comment]
@roji Can you take a look at this along with the other nullability tweaks?

**Comment by roji** [comment]
Yep, already on my list.

**Comment by roji** [comment]
The pattern of doing:

```c#
UnsafeNativeMethods.IDBInfo dbInfo = wrapper.Value;
if (null == dbInfo)
{
    return false;
}
```

... seems common in the codebase, e.g. AddInfoKeywordsToTable does this as well. `dbInfo` is assigned from `IDbInfoWrapper._value`, which comes from native COM components; I suspect null would only be observed in some sort of error condition, but I simply don't know enough about OleDB/COM to be sure... So it seems a bit risky to assume that dbInfo is never null.

Note also that OleDbConnection.GetOleDbSchemaTable - the public method wrapping BuildInfoLiterals - also needs to return null because of GetSchemaRowset, which is also annotated to return null. There as well, the `rowset` variable is assigned by native code and compared to null; this could again be dead code, but we'd have to dive into the native code to be sure.

So given that this is effectively legacy code, and to be on the safe side, it seems better to leave this annotated as nullable... @krwq thoughts?

**Comment by ajcvickers** [comment]
Closing this as by-design. Can re-open if @krwq has any input.
