### ISSUE TITLE
X509Store.Certificates.Find() results in surprisingly large finalized object counts

### ISSUE THREAD

**Issue by brporter** [dotnet/runtime#44382]
### Description

While debugging a memory allocation issue, I noted a large number of finalized objects were being reported in my perfview trace, specifically over 100,000 instances of finalization for Internal.Cryptography.Pal.Native.SafeCertContextHandle.

After some experimentation, I've found that the following program reproduces this behavior:

```c#
for (int i = 0; i < 100; i++)
{
    using (var store = new X509Store(StoreName.My, StoreLocation.LocalMachine, OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly))
    {
        var certs = store.Certificates;

        var retVal = certs.Find(X509FindType.FindBySubjectName, "doestnotexist.com", true);
    }
}
```

### Configuration
I've reproduced this behavior on both .NET 5.0 RC2 and .NET Core 3.1. Windows 10 20H2, x86 and x64. 

### Regression?
The behavior seem to be present in .NET Core 3.1, so if this is a regression it doesn't appear to be a particularly new one.

### Other information
I'm happy to learn that I'm doing something terribly stupid with the above API. :)

**Comment by stephentoub** [comment]
Disposing of the X509Store doesn't dispose of all of the certificate objects in the Certificates collection.  Try adding:
```C#
foreach (var cert in certs) cert.Dispose();
```
to your test.

**Comment by stephentoub** [comment]
Disposing of the X509Store doesn't dispose of all of the certificate objects returned in the Certificates collection, as they can be used after the store is disposed. Try adding:
```C#
foreach (var cert in certs) cert.Dispose();
```
to your test.

However, there does appear to be a bug beyond that.  @bartonjs, the StorePal.CopyTo's method use of SafeHandles is really strange: it's bending over backwards to try to keep pointers in safe handles only to then extra the underlying handle from each in a "dangerous" way.  As a result, it's not actually disposing of a bunch of SafeHandles it seems it should.  The handles are all transferred to something that will be disposed of, so it's doesn't appear to actually be a leak, but lots of invalid SafeHandle objects are getting left for finalization unnecessarily.  It seems like this line:
https://github.com/dotnet/runtime/blob/628c14ba85294e29be9e93da184c993f646bb6ee/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/Native/Interop.crypt32.cs#L157
should actually be:
```C#
CERT_CONTEXT* pPrevCertContext = null;
if (pCertContext != null)
{
    pPrevCertContext = pCertContext.Disconnect();
    pCertContext.Dispose();
}
```
and then also here:
https://github.com/dotnet/runtime/blob/628c14ba85294e29be9e93da184c993f646bb6ee/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/StorePal.cs#L45
there should be an additional call like:
```C#
pCertContext?.Dispose();
```
but, again, I question how SafeHandles are being used here at all: it seems like this would all be much simpler if `CertEnumCertificatesInStore` just worked in terms of pointers rather than SafeHandles.

**Comment by brporter** [comment]
@stephentoub Enumerating the returned certificates collection and disposing of the certificates individually does reduce, but doesn't eliminate, the spike in finalized objects.

**Comment by stephentoub** [comment]
> individually does reduce, but doesn't eliminate, the spike in finalized objects.

Right, see the remainder of my comment (which I added subsequently).
