### ISSUE TITLE
Allow custom IServiceCollection in build method

### ISSUE THREAD

**Issue by ti24horas** [dotnet/runtime#44435]
Is that possible to pass a custom IServiceCollection instead of using the internal IServiceCollection created in Build method?

My case is that the WebHostBuilder is just part of a bigger application (which contains part of code running as a service, for example)

Because the services are registered by an external IServiceCollection, it would be impossible to utilize the existing IServiceProvider without duplicating registrations (or delegating them to existing IServiceProvider).

**Comment by davidfowl** [comment]
This should be closed, I'm not exactly sure what a custom Build method would do here. We have an `IServiceProviderFactory<TContainer>` for extensibility in the host which satisfies this need.

**Comment by lanwin** [comment]
> This should be closed, I'm not exactly sure what a custom Build method would do here. We have an `IServiceProviderFactory<TContainer>` for extensibility in the host which satisfies this need.

I didnt have tried the HostBuilder yet, but the problem here was not the extensibility from my point of view. 

The WebHostBuilder always builds its own ServiceCollection and allows other only to hook in. But what about scenarios where you already have another application root and only want to add a webhost to it?

**Comment by davidfowl** [comment]
HostBuilder has a similar problem but that's by design as a host is responsible for creating and managing the DI container and hosted services within that container. It sounds like you're looking for something else.

What experience are you looking for?

**Comment by lanwin** [comment]
We have an company intern boostrap system for services/docker and co, witch builds upon everything we need for all off our services. This works also with ServiceCollection but it creates one already at start time. We want to use HTTP/ASP.NET as opt in feature to it. So manly wee need the *setup part* from WebHostBuilder to work against and existing ServiceCollection.

I mad it work by using forwarding IServiceProvider. But its complicated and feels messy while all it would nee is that WebHostBuilder would add a Ctor witch accepts an ServiceCollection.

**Comment by davidfowl** [comment]
Maybe you should target the the `IHostBuilder` directly instead of the `IServiceCollection`? Can you show what you're doing right now (a code sample would be best)?

FWIW, I think it would be possible to take an initial `IServiceCollection`, but taking a baked `IServiceProvider` wouldn't be possible.

**Comment by lanwin** [comment]
I will try to revisit that and build an example. But it could take a little while right now.

**Comment by davidfowl** [comment]
This issue is 4 years old, I got time 😆

**Comment by maryamariyan** [comment]
>  should be closed, I'm not exactly sure what a custom Build method would do here. We have an IServiceProviderFactory<TContainer> for extensibility in the host which satisfies this need.
