### ISSUE TITLE
New ctor for `FormUrlEncodedContent` accepting `Dictionary`

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#44458]
## Background and Motivation

https://github.com/dotnet/runtime/issues/38494

Once we annotated [`FormUrlEncodedContent`](https://github.com/dotnet/runtime/pull/33268/files#diff-1482fe0fd575b1c0514c1a752a77369f7f478d20c1ff7106a0413fd0e3557310R16) we have prevented people from using the ctor with `Dictionary`. `Dictionary`'s `TKey` cannot be null, colliding with key nullability in `IEnumerable<KeyValuePair<string?, string?>>`.

Changing the existing API might be problematic since the type have always accepted `null` keys and replaces them with an empty string: https://github.com/dotnet/runtime/blob/5f96636b63bea718bcfa1355e17cb36693ff8bca/src/libraries/System.Net.Http/src/System/Net/Http/FormUrlEncodedContent.cs#L37

Proposal is to add a new constructor accepting `IDictionary<string, string?>` and thus enabling uses like:
```C#
var nullableValueDictionary = new Dictionary<string, string?>
{
    ["foo"] = "bar"
};

_ = new FormUrlEncodedContent(nullableValueDictionary);
```

## Proposed API

```diff
namespace  System.Net.Http
{
    public partial class FormUrlEncodedContent : ByteArrayContent
    {
+       public FormUrlEncodedContent(IDictionary<string, string?> dictionary);

        // Existing ctor
        public FormUrlEncodedContent(IEnumerable<KeyValuePair<string?, string?>> nameValueCollection);
        ...
    }
}   
```

## Alternative Designs

Making the value non-null as well will ease the usage even more. Enabling usage with `Dictionary<string, string>`:
``` C#
var dictionary = new Dictionary<string, string>
{
    ["foo"] = "bar"
};
_ = new FormUrlEncodedContent(dictionary);
```
Api proposal:
```diff
namespace  System.Net.Http
{
    public partial class FormUrlEncodedContent : ByteArrayContent
    {
        // non-nullable value as well, we cannot overload on nullability so we cannot add this later, we must chose one
+       public FormUrlEncodedContent(IDictionary<string, string> dictionary);

        // Existing ctor
        public FormUrlEncodedContent(IEnumerable<KeyValuePair<string?, string?>> nameValueCollection)
        ...
    }
}   
```

## Usage Examples

``` C#
var nullableValueDictionary = new Dictionary<string, string?>
{
    ["foo"] = "bar"
};
_ = new FormUrlEncodedContent(nullableValueDictionary);
```

**Comment by karelz** [comment]
@ManickaP can you please look at it when you get a chance, so that we can make decision? Thanks!

**Comment by LeaFrock** [comment]
IMO, I prefer `public FormUrlEncodedContent(IDictionary<string, string?> dictionary)`. It makes no breaking changes, and callers can write codes like below,
``` C#
var nullableValueDictionary = new Dictionary<string, string?>
{
    ["foo"] = default //use easier syntax sugar instead of string.Empty(or "" which is possible to make a typo like " ") and don't worry about exceptions
};
_ = new FormUrlEncodedContent(nullableValueDictionary);
```
@karelz @ManickaP I can make a PR to finish it if you have more imporant things to deal with.

BTW, I think [Encode](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/FormUrlEncodedContent.cs#45) here can be optimized. 
``` C#
  // Escape spaces as '+'.
  return Uri.EscapeDataString(data).Replace("%20", "+");
```
Since this method will be used **every time on the keys and values**, may [String.Replace](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs#1043) be removed if we have another method for escaping data string? It's just due to the difference of treating WHITESPACE by *W3C* and by *RFC 2396*. Need I to create a stand-alone issue about it?

**Comment by karelz** [comment]
Triage: Some more tests are needed to determine if we need new API - @ManickaP is on point.
