### ISSUE TITLE
Browser WebSocket Improvements

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#44614]
The current Browser ClientWebSocket implementation is using managed side buffering of partial writes, we should review wether we can push the writes to the browser and chain all the data there for the send call.

**Comment by lewing** [comment]
cc @kjpou1 @kg

**Comment by kg** [comment]
We should just push it directly to the browser, I don't see any reason to do unnecessary work on the managed side unless it's addressing a bottleneck we found in a profiler.

**Comment by lewing** [comment]
No, the issue is just the api mismatch and we can track the write buffers on the browser side rather than in managed for the fragmented send.

**Comment by lewing** [comment]
Yeah,  looking closer at the [spec](https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket) it appears we should:
- [ ] remove the buffering
- [ ] handle `endOfMessage == false` the way we currently handle `endOfMessage == true`
- [ ] Add code to make `endOfMessage == true` to only complete once the `ws.bufferedAmount == 0`
- [ ] Review the expectations for the other states

**Comment by lewing** [comment]
cc @kjpou1

**Comment by kjpou1** [comment]
Looking at it

**Comment by kjpou1** [comment]
So far looking at sample streams of chained blob and an array of write buffers. 

Have not found a way to control the websocket text or string send type when using the above.  It is always sent as binary.

WebSocketMessageType 

Type | Value | Desc
-- | -- | --
Binary | 1 | The message is in binary format.
Close | 2 | A receive has completed because a close message was received.
Text | 0 | The message is clear text.


What controls this with fetch is the type of buffer that is passed.

Type | Data structure sent with fetch
-- | -- 
Binary | Uint8Array
Text | string

This also controls how we receive data from a websocket using the same criteria.  If the fetch body is text then we signify text and a blob or array buffer sent back is read and transferred back to the client as binary.

**Comment by lewing** [comment]
I added that distinction to https://github.com/dotnet/runtime/issues/44666 lets start by getting some tests in place so that we can validate any changes.

**Comment by lewing** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
[WebSocketStream](https://github.com/ricea/websocketstream-explainer/blob/master/README.md) would be nice if it was ready, [but it is not](https://chromestatus.com/feature/5189728691290112).
