### ISSUE TITLE
[Mono Android] Runtime tests failed due to Android app crashing

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#44648]
### Description

There were a bunch of tests failed due to Android app crashing. The root cause might be different. Need further investigation.

Some of them are GC tests. Some of them are under `JIT/Methodical`, `JIT/Performance`. Refer to https://github.com/dotnet/runtime/blob/master/src/tests/issues.targets for a detailed list of tests which are marked with this issue.
### Configuration

Runtime tests building and running instructions could be found [here](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/mono/testing.md)

### Regression?

No. Android is a new target for runtime tests.

**Comment by imhameed** [comment]
As part of getting the iOS simulator running the runtime tests, I think I stumbled on something related. With my PR in its current state, throwinfinallyintryfilter2.dll fails because it cannot load common.dll. So I started looking around for common.dlls.

Here's all the `common.dll`s available inside JIT/jit64:
```
imhameed@ms-ih-mbp ~/ms/dnr-9.x-ios/runtime/artifacts/tests/coreclr/iOSSimulator.x64.Release/JIT/jit64$ find . -iname common\.dll -exec shasum -a 256 {} \;
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/common/common/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/call/call05_large/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/call/call05_small/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/call/call05_dynamic/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/ehverify/eh05_dynamic/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/ehverify/eh06_dynamic/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/ehverify/eh07_dynamic/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/ehverify/eh07_large/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/ehverify/eh08_dynamic/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/ehverify/eh07_small/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/eh/eh03_large/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/eh/eh03_dynamic/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/eh/eh04_small/common.dll
1e59f9481a841e9e2acdff6cac4bad0f079b6d8fa2c194be81e33334884b74cb  ./localloc/eh/eh03_small/common.dll
20d90a783ea937a100086c71d317ff3f2b35b1d1dd3ee1c48dfc037ddad1c392  ./hfa/main/dll/common/common.dll
20d90a783ea937a100086c71d317ff3f2b35b1d1dd3ee1c48dfc037ddad1c392  ./hfa/main/testC/hfa_nd1C_r/common.dll
bb44ad02dacb84b60eb77e56eff3e6a86578731e7edd5ddbdfd6de6371e45787  ./eh/basics/throwinfinallyintryfilter2/common.dll
bb44ad02dacb84b60eb77e56eff3e6a86578731e7edd5ddbdfd6de6371e45787  ./eh/Common/common/common.dll
```

Presumably an arbitrary one (I have no idea what, if any order MSBuild imposes on globs) survives the grand overwriting tournament caused by https://github.com/dotnet/runtime/blob/d156b9e58d7b09f742d4553bb5a94657cf7e28ae/src/tests/run.proj#L455

So assuming that MSBuild ends up issuing copies in a random order, it is highly likely that throwinfinallyintryfilter2.dll and hfa_nd1C_r.dll will fail, and these two are exactly the tests from JIT.jit64 that are disabled for Android in issues.targets.

**Comment by fanyang-mono** [comment]
More detailed issues have been created. Closing this.
