### ISSUE TITLE
SignedXml can't find Id's with a namespace prefix

### ISSUE THREAD

**Issue by mconnew** [dotnet/runtime#44674]
### Description
When calling SignedXml.CheckSignature, it validates the signature of each of the references. A Reference has an Id and SignedXml needs to retrieve the XmlElement from it's XmlDocument which has the matching Id. It does this by calling the method SignedXml.GetIdElement. This method initially attempts to use XmlDocument.GetElementById which fails as that method is close to useless as it requires a DTD with each element name which could have an Id listed with IDREF, which goes against the whole concept of xmldsig where you can specify arbitrary elements as part of the signature. So then when that inevitably always fails, it falls back to using XPath to look for an element with a matching Id. Unfortunately the XPath query is incorrect. It is `"//*[@" + idAttributeName + "=\"" + idValue + "\"]"` where it substitutes in the values `Id`, `id` and `ID` for `idAttributeName` in turn checking for each of the case variations. A typical SOAP security header will have a timestamp which looks something like this:

```xml
	<u:Timestamp u:Id="_0" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
		<u:Created>2020-11-10T21:20:32.863Z</u:Created>
		<u:Expires>2020-11-10T21:25:32.863Z</u:Expires>
	</u:Timestamp>
```

The XPath query used is incorrect as the Id here has a namespace prefix and the XPath query is unable to find it. The correct query to use would be `"//*[@*[local-name()='" + idAttributeName + "']='" + idValue + "']"` where it only checks the local-name part of the attribute name, i.e. it ignores the namespace prefix. A correct implementation would look more like this (some code removed for brevity):
```c#
        public virtual XmlElement GetIdElement(XmlDocument document, string idValue)
        {
            try { XmlConvert.VerifyNCName(idValue); }
            catch (XmlException) { return null; }

            return GetSingleReferenceTarget(document, "Id", idValue) ??
                   GetSingleReferenceTarget(document, "id", idValue) ??
                   GetSingleReferenceTarget(document, "ID", idValue);
        }

        private static XmlElement GetSingleReferenceTarget(XmlDocument document, string idAttributeName, string idValue)
        {
            string xPath = "//*[@*[local-name()=\"" + idAttributeName + "\"]=\"" + idValue + "\"]";
            XmlNodeList nodeList = document.SelectNodes(xPath);

            if (nodeList == null || nodeList.Count == 0) { return null; }
            if (nodeList.Count == 1) { return nodeList[0] as XmlElement; }

            throw new CryptographicException(SR.Cryptography_Xml_InvalidReference);
        }
```
### Configuration
All versions of .NET where SignedXml exists.

### Regression?
Never worked correctly on any version of .NET.

### Other information
Making this change shouldn't be considered a breaking change as the fixed XPath query returns a strict superset of what the previous query returned. There are no cases where this would fail to return an XmlElement when the previous query would. It changes an incorrect signature validation failure into a potential correct signature validation for those scenarios where a namespace prefix is used with the Id. The referenced item hash and subsequent signature calculation would still need to match so it's not possible for this to cause a false positive when validating the signature.

Edit: Updated to include some necessary input validation and fixed concatenated string input to use double quotes to further prevent possibility of XPath query injection.

**Comment by krwq** [comment]
as a side note you can likely just use `"//*[@*[translate(local-name(), 'ID', 'id')='id']='" + idValue + "']"`

XML spec only mentions special meaning of `xml:id` attribute but xml dsig spec says `identity of the object is part of the application context` (in context of Uri). I think this can be interpreted that GetIdElement should be extensible which it is as the methods are virtual:
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.encryptedxml.getidelement?view=dotnet-plat-ext-5.0
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.signedxml.getidelement?view=dotnet-plat-ext-5.0

IMO you should redefine what ID means in you application (override GetIdElement) as xml dsig spec is not clear on the meaning of ID attribute (at least I couldn't find it) which can be interpreted ambiguously

**Comment by bartonjs** [comment]
> Making this change shouldn't be considered a breaking change as the fixed XPath query returns a strict superset of what the previous query returned.

Aside from our general hesitation to enhance the crypto XML libraries, I think the fact that the package unifies with the types in .NET Framework means that there's a reverse-compatibility problem: When run under .NET (nee Core) this behavior would be present, then when running on .NET Framework it would disappear.  Trying to emulate a user who doesn't understand how our facade system works: that feels like surprising behavior from a .NET Standard package.

We could solve that problem by putting it in the package as a net new type (`SignedXmlWithMoreSearchitude : SignedXml`), but I'm skeptical that there's a good name for it.  This probably is just done best as a sample... which probably wants the code that was "removed for brevity" reinstated, since there's a preponderance of blind copy/paste in the world.

**Comment by mconnew** [comment]
@krwq, I tried your replacement query and did a crude benchmark and it's actually slower. It has to do translate on every attribute it finds. It does the translate before it does the string match so it needs to traverse the entire id string one character at a time checking for each of "I" and "D" before it does the string compare. A string compare though can be lazy and if the first character doesn't match, it bails out. As the most common case is "Id", running three XPath queries is going to be faster in the common case. And the larger the document the worse the difference in performance will get. 
@bartonjs, I'll fix the code above to have less brevity for the copy/paste crowd.

**Comment by mconnew** [comment]
@bartonjs, is the desired outcome for someone with a valid signed XML document which is currently incorrectly failing validation that is should continue failing validation and this it's the wrong thing to do to now validate correctly? If we were incorrectly rejecting server certificates on an SSL connection which should pass validation, would we take the same approach of not accepting a fix because someone who is incorrectly broken should continue to be incorrectly broken?  

@krwq, I'm having difficulty following your reasoning of the quoted part from the xmldsig spec. That text comes [from the part](https://www.w3.org/TR/xmldsig-core/#sec-URI) talking about the ability to omit a reference URI, in which case the identity of the referenced item is part of the application context. This makes sense, if you don't specify the URI on a reference, the application using xmldsig needs to know what the reference is referring to. One examples in the spec is if it's referring to a Manifest. The type on the reference would say it's a manifest so the application knows how to find the manifest without having a reference URI provided. In the case that the URI isn't provided, no amount of overriding the GetIdElement method would help you resolve it as you don't have an Id to lookup. I don't think this part of the spec is applicable to this situation. Checking the code for SignedXml, in the case of no URL it expects the first transform to know how to get it which seems like a pragmatic way to handle the issue although to stick to the spec rigidly I think it would have been beneficial to make CalculateHashValue public and virtual instead. So that's the extensibility point for the section of the spec you reference, to provide a Transform to handle the no-URI case. Interestingly the Id attribute in the spec has the specific casing of "Id" listed so technically an attribute cased as ID or id should be ignored.

Whatever the outcome, I will need to carry the fix in my own implementation as even if a change does happen, I wouldn't expect it to be made down level.

**Comment by bartonjs** [comment]
> is the desired outcome for someone with a valid signed XML document which is currently incorrectly failing validation that is should continue failing validation and this it's the wrong thing to do to now validate correctly?

Sort of, yeah.  Basically, it's the principle of least surprise.  For .NET (nee Core) it's "this behavior changes when you upgrade from System.Security.Cryptography.Xml version 5.0.0 to version 6.0.0", for .NET Framework it's "this never works".  I understand why, you understand why, but to many (I'll assert "most") people they feel like "I upgraded the package, the behavior should be consistent".

> If we were incorrectly rejecting server certificates on an SSL connection which should pass validation, would we take the same approach of not accepting a fix because someone who is incorrectly broken should continue to be incorrectly broken?

The difference there is that I believe at better than 50% that we'd service .NET Framework for that.  I don't believe that we would service SignedXml for this, particularly because we view xmldsig and xmlenc as obsolete tech that only exist in .NET (nee Core) to remove speedbumps in migrating from .NET Framework to .NET (nee Core), and the workaround is pretty simple.

**Comment by bartonjs** [comment]
Basically just reiterating things from back in November, but:

* We're not currently investing in the crypto XML APIs (other than security issues).
* This would intentionally create a somewhat hard to debug divergence between .NET (nee Core) and .NET Framework
  * Looking back through the library history, I don't think we've taken any other change that did so.  The changes are all bulk repo changes, or fixing accidental divergences.

If the type were only available via NuGet, then I'd be supportive of the change.  But since the NuGet package just projects into System.Security.dll as a type forward on .NET Framework I think that the divergent behavior is too hard to reason about.

Thanks for providing an easy to use inheritance workaround, though, @mconnew.
