### ISSUE TITLE
C# Double Multiplication in .Net Core / .Net 5.0 has different result than .Net Framework and Roslyn

### ISSUE THREAD

**Issue by alas** [dotnet/runtime#44714]
### Having different results tham expected in multiplication in .Net Core / .Net 5.0

this code will print "1e-20" in.Net Framework 4.7.2 and in Roslyn 3.8 but it prints "1.0000000000000001e-20" with .Net Core 3.1 and in .Net 5.0:

```
using System;
					
public class Program
{
	public static void Main()
	{
        Console.WriteLine("{0:g}", 1e-19 * 0.1);
	}
}
```

This snippet can be tested in https://dotnetfiddle.net/

**Comment by danmosemsft** [comment]
@alas As you probably know, floating point math doesn't always produce "exact" results like integer math: 1e-19 * 0.1 produces a double value with the same bit pattern as "1.0000000000000001e-20", which is not the same as the bit pattern for 1e-20:

```c#
		Console.WriteLine("{0:X16}", BitConverter.DoubleToInt64Bits(1e-19 * 0.1));
		Console.WriteLine("{0:X16}", BitConverter.DoubleToInt64Bits(1.0000000000000001e-20));
		Console.WriteLine("{0:X16}", BitConverter.DoubleToInt64Bits(1e-20));
```
produces
```
3BC79CA10C924224
3BC79CA10C924224
3BC79CA10C924223
```

Your code takes this double and tries to format it with `g`, which is equivalent to `g17` for doubles. The `g` specifier is expected to produce the most compact representation of a round trippable result, if it can do so within the specified precision. Round trippable means parsing the number as a string will give the same double value. 1e-20 is not a round trippable result as you see above it produces a different double value. 1.0000000000000001e-20 is the shortest round trippable result, and it fits within the required 17 significant figures. Previous to .NET Core 3.1, it would incorrectly produce a non round trippable result.

The fix for your code depends on what you want: if you want a round trippable result (for example you are persisting to a file to be parsed by other code), it is working correctly. If you want a visually pleasing result, you can round it by specifying a smaller precision, for example 
```c#
Console.WriteLine("{0:g5}", 1e-19 * 0.1);
```
produces
```
1e-20
```

For more information please see
https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/
especially
```
For the "G" format specifier that takes a precision (e.g. G3), the precision specifier is now always respected. For double with precisions less than 15 (inclusive) and for float with precisions less than 6 (inclusive) this means you get the same string as before. For precisions greater than that, you will get up to that many significant digits, provided those digits are available (i.e. (1.0).ToString("G17") will still return 1 since the exact string only has one significant digit; but Math.PI.ToString("G20") will now return 3.141592653589793116, since the exact string contains at least 20 significant digits).
```

@tannergooding please correct me if I got anything wrong here. Note that [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-general-g-format-specifier) it says that `g` for a double defaults to 15 SF, but in this case I see it is producing 17 SF - is this doc wrong?

**Comment by tannergooding** [comment]
@danmosemsft, that's a good explanation. Thanks!

Also yes, that's one of the docs that I'm in the process of updating to call out the .NET Core 3.0+ vs prior behavior.
