### ISSUE TITLE
WinHttpHandler HTTP/2 trailing headers

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#44778]
WinHTTP has added support for HTTP/2 trailing headers in modern versions of Windows.

WinHttpHandler should set trailers into the `HttpResponseMessage.TrailingHeaders` collection in .NET Core 3+.

An idea that the gRPC team is thinking about is using WinHttpHandler to support `Grpc.Net.Client` on .NET Framework. For that to work the trailing headers would need to be available in .NET Framework, which doesn't have the `HttpResponseMessage.TrailingHeaders` API.

A possible solution that doesn't involve adding new API to .NET Framework could be to set the trailing headers collection as a value in `HttpRequestMessage.Properties` using a known key, e.g. `__Http2ResponseTrailingHeaders`.

**Comment by JamesNK** [comment]
Example of what hacking in trailing headers could look like:

```cs
        public static HttpResponseHeaders GetTrailingHeaders(this HttpResponseMessage responseMessage)
        {
#if !NET472
            return responseMessage.TrailingHeaders;
#else
            if (!responseMessage.RequestMessage.Properties.TryGetValue("__Http2ResponseTrailingHeaders", out var headers))
            {
                throw new InvalidOperationException();
            }
            return (HttpResponseHeaders)headers;
#endif
        }
```

**Comment by karelz** [comment]
Triage: Making it compatible with .NET Core 3.0+ makes sense.
If it is worth exposing on .NET Framework is subject to discussion (which we will have tomorrow) and should be split off into separate issue.

**Comment by antonfirsov** [comment]
Following up on https://github.com/dotnet/runtime/pull/46602#issuecomment-756111075 I also think that we should continue API discussions here, under the issue, before going further with implementation details.

At the moment I'm a bit pessimistic, since I don't see a good way to expose this without going against established BCL practices. A list of challanges I see:
- `HttpRequestMessage.Properties` is obsolete since .NET 5. Although there is no obsoletion warning when building against .NET Framework, exposing a new feature trough this bag doesn't look good
- There aren't many precedents for exchanging information with the help of arbitrary property-bag keys. The only thing I was able to find is #39182 / #34168
- In general, extensibility is not a strong point of `HttpRequestMessage`, especially when targeting multiple frameworks
- API (header container) differs depending on the target, behaviors differs depending on the OS


The best thing I can think of to overcome these challanges is to introduce an extension method within the WinHttpHandler lib, so we can at least hide some of this mess:

```C#
public static class WinHttpExtensions
{
    // Returns true and a header collection if WINHTTP_QUERY_FLAG_TRAILERS is supported, false otherwise.
    // Hides the access of the property bag as an implementation detail.
    // We may decide to also set HttpResponseMessage.TrailingHeaders for consistency, but the recommended way to access them is to use the extension method.
    public static bool TryGetWinHttpTrailingHeaders(this HttpResponseMessage responseMessage, out HttpResponseHeaders headers);
}
```

**Comment by JamesNK** [comment]
I believe a `GetWinHttpTrailingHeaders` method in WinHttpHandler package will need to return `HttpHeaders` (base type of `HttpResponseHeaders`).

The constructor for `HttpResponseHeaders` isn't public so creating an adhoc one on .NET Framework isn't possible.
