### ISSUE TITLE
Enable Trim to framework-dependent

### ISSUE THREAD

**Issue by transis2** [dotnet/runtime#44869]
Hi,

I was wondering if there's any plan to enable Trim to framework-dependent (with produce single file option) publish ?

The final size is much bigger with .net5 than with .net framework 4.7.2

.Net Framework 4.7.2 -> 7.5MB
.Net 5 -> 20MB

![image](https://user-images.githubusercontent.com/4941173/99536042-8f377700-2988-11eb-8fc0-fac52b3eb14a.png)

**Comment by vitek-karas** [comment]
You can look at the `.\bin\Debug\net5.0\` folder to see the "unpacked" size of the .NET 5 app and what goes into it. The "packing" should have next to no effect on size over that folder. That should provide a good idea where the size increase is coming from.

Currently we don't have plans to add a way to trim framework-dependent apps. There are two main reasons:
* The size saving is typically not that interesting
* It's much more risky. For self-contained apps we only trim the framework, not the app or NuGets - because it's much less risky to do so. Trimming the app or NuGets is currently risky and may very well break the application.

**Comment by transis2** [comment]
Thanks for the answer @vitek-karas 

I know it's very risky, but I think MS should allow to developers choose, just like using linker with Xamarin.
The actual aproach is too heavy.

Thanks for your time.

**Comment by vitek-karas** [comment]
I created an issue in mono/linker which is the repo where trimmer work is done. https://github.com/mono/linker/issues/2139

Currently we don't have any plans to support this, but I want to keep it in the list.
