### ISSUE TITLE
Survey: Repo contribution experience, Fall 2020

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#44903]
We normally focus on how to improve the product, but we’re also turning our focus to improving the open source project. Periodically we are running a survey to collect feedback on your experience working with our repos. We did one back in May, and as its been about 6 months, its about time for another. We’ve created a survey to better understand your individual experience of participating and contributing in this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. 

Survey

Thank you for your time!

**Comment by Wraith2** [comment]
No https://github.com/dotnet/SqlClient ?

**Comment by srxqds** [comment]
I am checking every issue and every pull request everytime everyday.
I hope you can take more attention and focus to work on MonoVM.
The AssemblyLoadContext and profiler is not full supported on MonoVM. 
and make more performation optimization.

I am waiting for it since last year.
Thank you for your great work.

**Comment by PathogenDavid** [comment]
If we regularly interact with multiple repos listed on the survey, should we complete the survey more than once?

> If you don’t supply contact details, then responses will be anonymous.

Should have I been prompted for them? Not really a big deal, but I was a bit surprised when the survey just ended without it asking.

**Comment by Symbai** [comment]
Any chance we will get the results of this survey? And when does the survey ends?

**Comment by PathogenDavid** [comment]
@Symbai [They have in the past](https://devblogs.microsoft.com/dotnet/repo-experience-survey-results/), so I'd assume they will.

**Comment by tebeco** [comment]
hello @samsp-msft 

I think that one of the biggest show stopper we encountered at work was the proxy on the build tool chain. (especially NTLM-v2 proxy ... because life it more fun with 407)
We ended up having to bring our own (personal) laptop at work to work on Pull Request ... to add proxy support to SignalR and Azure SignalR Service SDK (the irony :D)

The way `dotnet/arcade` works make it quite complex to change the restore behavior.
At that time, the list of nuget feed were not centralized in a single place.

The only way we have to hit `myget.org` or `nuget.org` was though a `JFrog Artifactoy` so I have to find out the `AdditionalRestoreSource` or other, create equivalent feed / change URI in repo
and repeat it over and over

I understand that I could possibly attempt to use `HTTP(s)_PROXY` and so on but at that time it was not properly respected in dotnet/runtime (multiple fixes had to land in 2.1/2.2 and 3.0)
I honestly think that `restore.cmd|ps1|sh` should support a `-Proxy http://localhost:1234` that should be passed down

This issue don't not just concern `dotnet restore` (for httpclient in `dotnet/runtime` ), it's also a pain point in `pwsh` during `Invoke-WebRequest` and so on.
I understand that this scenario might not be frequent "over the world", but at least 3 attempt of PR were discarded by teamted because they could not restore the repo

Note that this scenario is not just for contribution, but also when you want to debug the sample provided:
We wrote an `IHubProtocol` with `protobuf` as a serialization format, and having the opportunity to debug the existing `MessagePackHubProtocol` was very important in that scenario

**Comment by danmosemsft** [comment]
> No https://github.com/dotnet/SqlClient ?

Good point @Wraith2  - we'll hopefully include them next time.

**Comment by danmosemsft** [comment]
> Should have I been prompted for them? Not really a big deal, but I was a bit surprised when the survey just ended without it asking.

Thanks, edited text above since we didn't include that this time.

**Comment by sakno** [comment]
From time to time I'm working on _dotnet/runtime_ repo and development on Linux is a bit complicated. I had spend a lot of time to fight with debug from vscode but without luck. The same story with code navigation. Additionally, there are some issues with the tools such as `dotnet` shipped with repo and relative paths. I believe that experienced *nix user and developer can solve these problems locally in an hour, but this looks like unfriendly if you trying to contribute first time.

**Comment by danmosemsft** [comment]
@sakno thank you for that info. Can you open an issue for that? As well as putting in the survey

**Comment by sakno** [comment]
@danmosemsft , I have already passed survey. Cloned repo is now configured to work properly on my linux workstation, so I will try clone it from scratch and pass through this path again to collect all the issues.

**Comment by lateapexearlyspeed** [comment]
Hi, very happy to be able to contribute to .net! As a external contribution beginner, I just wonder normally how long reviewer can response the comment fix. I know everyone is busy, but still feel a little puzzled for my first pr status as it has been 15 days by now after I respond reviewer that I have fixed comments.

**Comment by danmosemsft** [comment]
@lateapexearlyspeed thanks for the reminder. It is always OK to ping folks with @<their name> if something seems overlooked. @maryamariyan  hopefully can take a look and get that one done.

**Comment by samsp-msft** [comment]
The survey is now closed. Thank you to everyone who provided feedback. I have removed the link from the first post.
