### ISSUE TITLE
Targets* properties in libraries are ambiguous

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44946]
We define `Targets*` properties in all other parts of the repository based on the `TargetOS` property which is either passed in or set to the current OS. In libraries we set the `Targets*` based on the `TargetFrameworkSuffix` which indicates which OS a library targets. There might be value in removing the ambiguity especially now as the `Targets*` properties in libraries can't be used in the libraries project files anymore.

Opened because of https://github.com/dotnet/runtime/pull/43804/files#diff-aec399247327507f8a921926dfa34e159e9786455234791d9895fe64185d91f2R158.

cc @Anipik @am11 @ericstj @jkoritzinsky

**Comment by am11** [comment]
I think if CoreLib projects under coreclr and mono are also switched to SDK hook (`TargetFrameworkSuffix` based introspection), there is a very little use of `Targets{PlatformName}` properties left (that are converged in `eng/Configurations.props`). We can replace the remaining usages to `TargetOS == 'abc'` conditions, and delete that property group. This way, we will have only one meaning of `Targets{PlatformName}` properties in the entire repo.

**Comment by ViktorHofer** [comment]
Sounds good. I was considering filing an issue to discuss moving the CoreLib projects into the libraries tree anyway so that they would benefit from our binplacing and multi-targeting by RID infra.

cc @jkotas

**Comment by ViktorHofer** [comment]
But as said, the problem with the `Targets*` properties in libraries is that they only work after the project file is evaluated, usually in targets files.

**Comment by jkotas** [comment]
> especially now as the Targets* properties in libraries can't be used in the libraries project files anymore.

I do not understand this statement. `Targets*` properties are used in many libraries projects today and work just fine. One many examples: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj#L93

**Comment by ViktorHofer** [comment]
This works today because we set the `TargetFramework` in a props files: https://github.com/dotnet/arcade/blob/0778b689bb85bf74dbb0d9d00b48d7b3401fd073/src/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/src/build/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.props#L20.

We eventually want to remove that hack as the `TargetFramework` property isn't supposed to be read before it's evaluated in the project file. I was under the assumption that we already cleaned up.

**Comment by jkotas** [comment]
This would be like 10th time we are changing how you say `if (Windows)` in the project files. I do like the `Targets*` properties since they provide abstraction and do not require changing all project files every time we decide there is a new better way to say `if (Windows)`. Why can't we keep them around?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/msbuild/issues/5171 touches on this, especially the remarks section "Background on MSBuild evaluation".

**Comment by ViktorHofer** [comment]
If I could travel back in time and just change one aspect of msbuild, it would be its evaluation order which makes the whole build system far more complex than necessary...

@jkotas what are you thoughts on moving the CoreLib project files into libraries at some point? That would improve the current workflow that requires to invoke libs.pretests to update the CoreLib in the testhost. Instead we would you use the existing binplacing mechanism that we use for all our other libraries which essentially is a push instead of a pull mechanism.

More specifically, what were the reasons during the consolidations that we kept them in the runtime folders? And why do we have two project files instead of a single one with conditional imports?

**Comment by am11** [comment]
> > especially now as the Targets* properties in libraries can't be used in the libraries project files anymore.
> 
> I do not understand this statement. `Targets*` properties are used in many libraries projects today and work just fine. One of many examples: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj#L93

There are two ways `Targets{PlatformName}` properties are currently calculated:
1. Based on RID, which in turn is seeded by the `build.{cmd,sh}` scripts.
    * used by coreclr, mono, installer and tests
2. Based on frameworksuffix: https://github.com/dotnet/runtime/blob/b5dffeb/eng/targetframeworksuffix.props
    * used only by libraries, influenced by SDK and design time VS build.

therefore this gets tricky to figure out which one is which due to the same names and their values are initially different when a new platforms is introduced (we have to wait for the new SDK update, with support for the new platform).

The proposed idea is to forgo this ambiguity by switching the two CoreLib csprojs to same plan as rest of the libraries (<span>#</span>2) and for the remaining (very few) usages elsewhere (in installer, mono.proj etc.), we can use `TargetOS == '{name}'` conditions, as we are interchangeably using in those few files anyway.

**Comment by jkotas** [comment]
> what are you thoughts on moving the CoreLib project files into libraries at some point?

The CoreLib is special in many ways. It is coupled to runtime build flavor (e.g. debug corelib does not work with release native runtime and vice versa), it gets crossgened in the default workflow to make up stack libraries more pleasant to work with, ... .

As we rewrite more core runtime logic in C#, this coupling is only going to grow. For the long run, you can rephrase this questions why we have coreclr/mono split - why not just move the whole coreclr/mono under libraries?

> requires to invoke libs.pretests to update the CoreLib in the testhost

The same suboptimal workflow exists for updating anything in coreclr/mono, it is not limitted to CoreLib. I think the fix for this is to binplace from coreclr/mono builds into the test host. Ideally, I think all our build targets would automatically binplace into a layout that you can just run test against and `libs.pretests` would not be needed at all.

**Comment by ViktorHofer** [comment]
@am11 would you be willing to pick this up? The work required would be
1. Change OS conditions in both CoreLibs to use `TargetOS` instead of `Targets*` properties.
2. Remove `Targets*` from any other component outside of src/libraries and replace with `TargetOS`.
3. Move `Targets*` properties to src/libraries/Directory.Build.props

Do the steps make sense?

**Comment by ViktorHofer** [comment]
Closing as src/libraries projects don't use `Targets*` properties anymore to refer to the TargetFramework's TargetOS. Instead we now use TargetPlatform(Identifier/Version) which is the shipping concept to target a platform.
