### ISSUE TITLE
StringBuilder.Append methods do unnecessary allocation

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44992]
When StringBuilder.Append methods of primitive types https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1149-L1172 require internal buffer resizing they allocate unnecessary temporary string for the value being appended.

It'd be better to rewrite the generic [AppendSpanFormattable](https://github.com/dotnet/runtime/blob/e2312e1edb97d51ea0feded221f67506a1ce67a6/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1174-L1182) method not to be generic and call number formatting methods directly. If the buffer is not big enough the method would resize the buffer and make the call again. Something like

```c#
public StringBuilder Append(uint value)
{
	while ((int missingSpace = Number.TryUInt32ToDecStr(value, 0, RemainingCurrentChunk, out int charsWritten)) != 0)
	{
		Capacity += missingSpace;
    }

    m_ChunkLength += charsWritten;
    return this;
}
```

**Comment by EgorBo** [comment]
The problem here is that even if we know we won't fit our e.g. `long` we still have to fill the current chunk to the full and then allocate a new one and write the rest there. Fortunately, all primitive unlikely to be longer than let's say 8 chars so we can do `TryFormat` against a buffer allocated via `stackalloc` I guess.

**Comment by jkotas** [comment]
See discussion in #45000
