### ISSUE TITLE
ActivitySource.StartActivity returns null

### ISSUE THREAD

**Issue by ma-gu** [dotnet/runtime#45070]
I haven't find the way to make `activitySource.StartActivity` return non-null activity, which is different comparing to `DiagnosticSource.StartActivity` behavior. Is it expected? Am I'missing something obvious?

I can see [docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.startactivity?view=net-5.0#System_Diagnostics_ActivitySource_StartActivity_System_String_System_Diagnostics_ActivityKind_) says: "The created activity object, if it had active listeners, or null if it has no event listeners." The following test still fails, what's the correct way of initializing `ActivityListeners`?

```
        [TestMethod]
        public void Start_Not_Null_When_ActivityListener_Added_And_ShouldListenTo_Explicitly_Defined_Activity()
        {
            var activitySource = new ActivitySource("ActivitySourceName");
            var activityListener = new ActivityListener
            {
                ShouldListenTo = s => true
            };
            ActivitySource.AddActivityListener(activityListener);
            
            using var activity = activitySource.StartActivity($"MethodType:/Path");
            
            Assert.IsNotNull(activity);
        }
[Issue.Repro.zip](https://github.com/dotnet/runtime/files/5579761/Issue.Repro.zip)

**Comment by tarekgh** [comment]
> I haven't find the way to make activitySource.StartActivity return non-null activity, which is different comparing to DiagnosticSource.StartActivity behavior. Is it expected? 

Yes it is expected. `ActivitySource.StartActivity` is designed to avoid creating any Activity object when there is no listener because it means no-one is interested on such object.

> what's the correct way of initializing ActivityListeners?

```C#
var activityListener = new ActivityListener
{
    ShouldListenTo = s => true
    SampleUsingParentId = (ref ActivityCreationOptions<string> activityOptions) => ActivitySamplingResult.AllData;
    Sample = (ref ActivityCreationOptions<ActivityContext> activityOptions) => ActivitySamplingResult.AllData;            
};
```

This should force creating the Activity object. The listener callback `Sample` and `SampleUsingParentId` are important to have the listener decide if interested to create the Activity object or not. 

Basically `ShouldListenTo` callback is used to deice which ActivitySource to listen to, and Sampling callbacks to decide if interested to create the Activity or to sample it out and not creating it.

I am closing the issue but feel free to send any more questions.
