### ISSUE TITLE
Process.get_StandardInput throws InvalidOperationException after Process object has been disposed

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#45149]
Wonder if it's worth throwing an `ObjectDisposedException` instead to make this situation more discoverable.

_Originally posted by @pakrym in https://github.com/dotnet/runtime/issues/34097#issuecomment-726350901_

## Minimal Reproduction

```csharp
static void Main()
{
    var psi = new ProcessStartInfo
    {
        FileName = "git",
        Arguments = "--help",
        RedirectStandardInput = true,
    };

    var proc = Process.Start(psi);
    proc.WaitForExit();
    proc.Dispose();

    _ = proc.StandardInput; // throws System.InvalidOperationException: 'StandardIn has not been redirected.'

}
```

**Comment by eiriktsarpalis** [comment]
cc @stephentoub

**Comment by danmosemsft** [comment]
That seems reasonable to me and I believe we have made similar changes elsewhere.

**Comment by adamsitnik** [comment]
@danmosemsft please excuse me if this is a stupid question, but do we have to go through any approval process to change the exception that is thrown? It would be both a breaking change and a bug fix

**Comment by danmosemsft** [comment]
@adamsitnik I think there are two decisions to make - is the change acceptable, and does it need to be documented.
For the former, I think there is precedent that this is generally OK, since use after dispose should never occur intentionally. However this is a commonly used type. @stephentoub @marklio any thoughts?
For the latter, it would probably be worth a breaking change note (the template in the docs repo)

**Comment by danmosemsft** [comment]
Incidentally when we make a call on something like this (case that could be potentially generalized) it would be great to get it into breaking-change-rules.md as "case law" so we only have a discussion once. We already have in there eg that it's acceptable to throw a more specific type than NullReferenceException.

**Comment by Marusyk** [comment]
Should it be something like in other places: `CheckDisposed();`?

Please assign it to me, I'll try to prepare a PR for this

**Comment by danmosemsft** [comment]
I think it would be good to get comment from one of the folks above, and they are out for holidays. But I have assigned it meantime.

**Comment by eiriktsarpalis** [comment]
> Should it be something like in other places: CheckDisposed();?

I think it's best to follow existing convention used in the particular class, namely inline an `if (!_disposed)` check.

**Comment by Marusyk** [comment]
Ok, so, can I start implementing this?

**Comment by marklio** [comment]
Since ObjectDisposedException derives from InvalidOperationException, this doesn't even qualify as a breaking change. It is certainly possible to imagine scenarios where this can break user code, but those are not typically invoked for .NET Core changes. This seems completely in line with changes we'd take for a .NET Core major release.

**Comment by adamsitnik** [comment]
> Ok, so, can I start implementing this?

@Marusyk yes, please
