### ISSUE TITLE
Stream.CopyTo(Stream, int) does not respect bufferSize parameter

### ISSUE THREAD

**Issue by Kyle8329** [dotnet/runtime#45154]
### Description
Stream CopyToAsync(Stream destination, int bufferSize, CancellationToken cancellationToken) and CopyTo(Stream destination, int bufferSize) do not respect bufferSize parameter (e.g.  a value of 67 is passed but a buffer size of 128 is used).  See repro here: [Program.cs.gz](https://github.com/dotnet/runtime/files/5590680/Program.cs.gz)

### Regression?
Works as expected in net472.  Reproduced in net5.0 and netcoreapp3.1 (didn't test lower netcore versions).

### Other information
The issue seems to be in [Stream.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs) line ~63 and ~98.
`byte[] buffer = ArrayPool<byte>.Shared.Rent(bufferSize);`
It looks like the current ArrayPool implementation rounds the requested buffer to the next highest power of two.  So a requested buffer size of 67 will use a 128 byte buffer, 212 => 256, etc.

**Comment by stephentoub** [comment]
This is by design.  The buffer size is a hint, and in general it won't use a smaller buffer size, but it may end up using a larger one.  It may also not use a buffer at all, e.g. if you copy from a MemoryStream to the destination, MemoryStream's CopyTo{Async} override will just write its internal buffer directly.
