### ISSUE TITLE
AsnDecoder permits reading values that are not valid for the encoding rules

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#45169]
This might be "working as intended" but I thought I would ask, is it intended that this succeeds?

```c#
using System;
using System.Formats.Asn1;

var data = new byte[]
{
    0x02, //Integer tag
    0x03, //Has a content length of "3",
    0x00, 0x00, 0x86, //With a value of 134, with a leading zero.
};


bool good = AsnDecoder.TryReadEncodedValue(data, AsnEncodingRules.DER, out _, out _, out _, out _);
Console.WriteLine(good);
```

I would expect this to be `false` since the integer value is not canonically encoded, it has a leading zero, but it is `true`. Similarly other non-canonical and other oddities are accepted, such as an ASN NULL with a non-zero length.

The consequence of this is that `AsnWriter.WriteEncodedValue` will accept things that are not valid for the encoding rules (or are not valid under any encoding rules). This is not what I expected, since the documentation states an `ArgumentException` is thrown if

> `value` could not be read under the current encoding rules.

I sense that maybe the intention here is that `TryReadEncodedValue` and thus `WriteEncodedValue` does not validate the contents, just that the tag and length are valid (not indefinite for DER, etc), and no data is beyond the length.

**Comment by bartonjs** [comment]
Yeah, I think I originally had it applying value-validation for universal types, but with the vast amount of data that gets pumped through as implicit tag it's hard to do in a manner that feels consistent. `8203000086` is invalid if it's an INTEGER, but OK if it's an OCTET STRING or BIT STRING, and we can't tell the difference.

IIRC (without looking at code):
* It verifies that the tag is legally encoded
* It verifies that the length is valid for the encoding rules (no extraneous bytes for CER/DER, no indefinite for DER, only indefinite for CER+constructed)
* If the value was constructed it recurs
* After recursion it checks that a constructed value used 100% of its contents

That's why https://github.com/dotnet/runtime/blob/aebd598664e7d931eee19eb1779c0ace5d1c3600/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Helpers.cs#L151 has more logic than just calling ReadEncodedValue

**Comment by vcsjones** [comment]
Thanks!
