### ISSUE TITLE
Text.Json Slowdown when using custom JsonConverter

### ISSUE THREAD

**Issue by CryoMyst** [dotnet/runtime#45187]
### Description
When using a custom JsonConverter<T> on a class with many writes slowdown will occur and memory will spike when writing to a filestream.

### Configuration

* Windows 10
* .Net 5
* Visual Studio 2019 + LINQPad

### LINQPad Example
```
async Task Main()
{
	await JsonSerializer.SerializeAsync(File.OpenWrite(Path.GetTempFileName()), new CustomClass(), new JsonSerializerOptions() { WriteIndented = true });
}

[JsonConverter(typeof(CustomClassConverter))]
class CustomClass
{ 
	
}

class CustomClassConverter : JsonConverter<CustomClass>
{
	public override bool CanConvert(Type typeToConvert)
	{
		return typeToConvert == typeof(CustomClass);
	}

	public override CustomClass? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		throw new NotImplementedException();
	}

	public override void Write(Utf8JsonWriter writer, CustomClass value, JsonSerializerOptions options)
	{
		var lastTime = DateTime.Now;
		var timeout = lastTime + TimeSpan.FromSeconds(10);
		
		for (int e = 0; e < 1000000; e++)
		{
			if (e % 10000 == 0 || DateTime.Now >= timeout)
			{
				Debug.WriteLine($"e:{e} Time spend:{DateTime.Now - lastTime}");
				lastTime = DateTime.Now;
				timeout = lastTime + TimeSpan.FromSeconds(10);
			}
			
			for (int i = 0; i < 200; i++)
			{
				writer.WriteNull("TestName");
			}
		}
	}
}
```
This slows down on my machine around e=280k

### Regression?
This produces an OverflowException when run on on Core 3.1

**Comment by eiriktsarpalis** [comment]
This is a by-design limitation of custom converters. Because the publicly exposed converter methods do not support async serialization, serialization data is written to an [intermediate `PooledByteBufferWriter`](https://github.com/dotnet/runtime/blob/881f3c6c2b9800dfce3c0d2dd1a98771364754e2/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs#L345-L346) which cannot be [flushed to the underlying stream](https://github.com/dotnet/runtime/blob/881f3c6c2b9800dfce3c0d2dd1a98771364754e2/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs#L371) while a custom converter is running. If a custom converter is serializing a large amount of data, then it is expected that this will manifest as increased buffer allocations.

We have been discussing potential improvements in future releases that might allow users author custom converters that support async serialization out of the box cc @steveharter.

**Comment by eiriktsarpalis** [comment]
Closing in favor of #36785.
