### ISSUE TITLE
[Proposal] String.this[index, count]

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/runtime#45253]
I suggest that allows using 2-param indexer for strings:
```
var S = "Test";
var x = S[1, 2];
```

It will be nicer and shorter than:
`x = S.Substring(1, 2);`

The suggested API is simply:
`public string this[int index, int count] => this.SubString(index, count);`

**Comment by pinkfloydx33** [comment]
You can already do something like this, but with the range operator. Granted it doesn't work with a count, but rather directly with indices. But since you can use calculations within the range this seems redundant. 

```csharp
var x = "Hello World!";
var y = x[0..5];
var z = x[6..^1]; 
var start = 1;
var count = 4;
Console.WriteLine(y); // Hello
Console.WriteLine(z); // World
Console.WriteLine(x[start..(start+count)]); // ello
```
See [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQBADGQQMwAEA3mXS3Qfo869wG4QJ0AHnQC8dAEQAJOABsZAezoB1eQhkATAITiA3F24s+AgJ6ihAbQoA6KwFYAuntIHWRugC8zg8wDYbAPUJHfQM3WH4YM0InF0N+OgBjeSxIsQAWGNjcQgBOAApjAEpMl2z892KQ7jK873CEGBs8+pgAaiSUwvtK5xYAXzI+oA) 

Perhaps you'd want a "simpler" syntax for an offset from start (rather than an end index), though I can't think of one offhand that wouldn't be ambiguous. Either way that'd be more of a language construct than a runtime one I think.

**Comment by VBAndCs** [comment]
Range is not supported in other languages. .NET API is.

**Comment by stephentoub** [comment]
> Range is not supported in other languages. .NET API is.

And an API for this already exists: Substring.

**Comment by VBAndCs** [comment]
`S[0]` also exists although `S.SubString(0, 1)` already exists.
So, why not `S[0, 2]` for `S.SubString(0, 2)`?

**Comment by stephentoub** [comment]
> S[0] also exists although S.SubString(0, 1) already exists.

Those are completely different operations.

**Comment by stephentoub** [comment]
Thank you for the suggestion. This is not an API we'd add. In C#, you can already achieve this with ranges. For other languages, if this level of brevity was important, they could choose to add a similar ranges feature, and in the meantime the functionality is fully there just by typing "Substring". (And your motivating example was in C#, where this is already as brief.)
