### ISSUE TITLE
Publish with single file is generating dll

### ISSUE THREAD

**Issue by transis2** [dotnet/runtime#45265]
### Description
I'm trying to publish an project with Produce single file option checked but Visual Studio is generating an called sni.dll also.

![image](https://user-images.githubusercontent.com/4941173/100383658-e4b0fb00-2ffc-11eb-9456-20e291111e82.png)

If I remove dll, the binary file doesn't execute. So, it's dependent of him.

![image](https://user-images.githubusercontent.com/4941173/100383869-76b90380-2ffd-11eb-9e11-8ab5993aa7a2.png)

I'm using Visual Studio 16.8.2

**Comment by vitek-karas** [comment]
This is expected behavior. The .NET 5 single-file can't bundle native libraries by default. The goal of .NET 5 single-file was to avoid writing to disk when running the app by default. There's no good way to load native libraries from an executable on Windows, so it leaves native libraries next to it. All of the managed code will be bundled into the .exe and will execute directly from the .exe.

You can choose to allow writing to disk (on application start it would write some files onto disk) by setting the property `IncludeNativeLibrariesForSelfExtract` to `true`. This will bundle the native library as well and when you run the app it will first write it to disk (into temp) and then run the app.

https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#user-experience

**Comment by transis2** [comment]
Nice! It works.
Thank you very much!
