### ISSUE TITLE
Support Apple Silicon Diagnostics

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#45383]
Our goal is to deliver parity with osx-x64 for apple silicon diagnosics.

- [x] Implement ICorDebug APIs 
- [x] Test ICorProfiler APIs
- [x] SOS support

**Comment by tommcdon** [comment]
Debugger API's completed on https://github.com/dotnet/runtime/pull/47834, https://github.com/dotnet/runtime/issues/42105

SOS supports Apple Silicon.

**Comment by sdmaclea** [comment]
I am not aware of any missing profiler code in the runtime.  The runtime profiler tests mostly just pass.  Our internal profiler tests have not been run successfully yet, but that may or may not be a runtime issue.

/cc @davmason

**Comment by davmason** [comment]
The only feature that requires platform specific changes should be ELT hooks, everything else should be portable. We do run in to the issue where new platforms often require new APIs to handle different behavior - i.e. on Linux/Mac due to the way we cache environment variables in the PAL we had to add profiler APIs to set and get environment variables. I don't anticipate any of those for Apple Silicon, but it's a risk we run by not validating the scenario. I think it's the right risk to take, but worth calling out.

**Comment by k15tfu** [comment]
BTW, I'm not aware of any issues with Profiling API on Apple Silicon (incl. ELT hooks).

**Comment by sdmaclea** [comment]
@k15tfu Thanks.

I think the only known issue is that our internal profiler tests are not running yet.  So there is a potential of an issue.

**Comment by tommcdon** [comment]
We have minimal testing in the runtime repo.
