### ISSUE TITLE
.Net5.0 win-x86 Console app does not run in Windows 2012 R2 server

### ISSUE THREAD

**Issue by thudugala** [dotnet/runtime#45395]
### Description

.net5.0 SingleFile console app is crashing on Windows 2012 R2. Can you help ?

```
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0</TargetFramework>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
		<Platforms>x86</Platforms>		
		<PublishSingleFile>True</PublishSingleFile>
		<PublishReadyToRun>True</PublishReadyToRun>
		<PublishTrimmed>False</PublishTrimmed>		
		<IncludeNativeLibrariesForSelfExtract>True</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>
```

App is located here
https://github.com/thudugala/RocketM/tree/master/ME

### Configuration

* Which version of .NET is the code running on? .Net5.0
* What OS and version, and what distro if applicable? Windows
* What is the architecture (x64, x86, ARM, ARM64)? x86
* Windows version: Windows 2012 R2 

### Regression?

This app works when in netcoreapp3.1

### Other information

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	MohioExpress.Run.exe
  Application Version:	3.20332.0.0
  Application Timestamp:	5f8de458
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.19724
  Fault Module Timestamp:	5ec50c3e
  Exception Code:	e0434352
  Exception Offset:	000156e8
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	5129
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	9d53
  Additional Information 4:	9d539ab2d38cfad867f683ba4be72a2d

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

![image](https://user-images.githubusercontent.com/4112014/100403351-9450a080-30c3-11eb-830a-7c72639c8d5e.png)

**Comment by danmosemsft** [comment]
@thudugala would it be possible to start it using a native debugger (like Visual Studio) to get a callstack of the failure?

**Comment by vitek-karas** [comment]
I think this is due to the lack of `api-ms-win-...` files. We do include them in the shared framework, but we drop them for single-file.
A possible workaround would be to copy all of the `api-ms-win-...` files from the shared framework (typically in `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0`) next to the single-file app. It will probably make it work (I don't have 2012 R2 around to test this).

**Comment by thudugala** [comment]
Sorry @danmosemsft, I do not have permission to install developer tool on customer server.

**Comment by danmosemsft** [comment]
@thudugala you should be able to use [windbg.exe](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) from a share or USB drive.

**Comment by elinor-fung** [comment]
Is this only failing on Windows 2012 R2, or is it failing on a newer OS (e.g. Windows 10) as well?

Also note that with single-file in .NET 5.0, there are a number of [APIs that are not compatible with single-file deployment](https://docs.microsoft.com/dotnet/core/deploying/single-file#api-incompatibility). Since you mentioned that the app was working with 3.1 (where single-file still extracted all files and thus did not have those API incompatibilities), it would be worth checking if you are using any of those APIs.

**Comment by thudugala** [comment]
@elinor-fung Only failing on Windows 2012 R2.

@danmosemsft Only fails when PublishSingleFile is True

**Comment by vitek-karas** [comment]
I tried both .NET Core 3.1 and .NET 5 single file apps (console hello world) on both Win7 and Windows Server 2012 R2 and they work. So if the app is failing it's probably for some other reason than the missing `api-ms-win...` libraries.

You can check event log - it's likely to contain some additional details about the failure (but not guaranteed, depends on how it failed).

Is this using .NET 5.0.0 SDK or some preview? We had a bug in previews around 32bit single-file apps using R2R - which would run out of virtual memory space and crash. It should be fixed in the final release of .NET 5.

**Comment by vitek-karas** [comment]
Closing as we can't seem to repro this and there's not enough information in the issue.
