### ISSUE TITLE
HttpClient does not recycle sockets when server uses Connection: close. Sockets can be exhausted with high request rate.

### ISSUE THREAD

**Issue by gmorris007** [dotnet/runtime#45544]
I have been converting a service that talks to IoT devices from HttpWebRequest/HttpWebResponse objects to HttpClient. My interest stems from the fact that occasionally I will get “An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full”. We (the company & I) require timely polling of data so that is bad news, obviously. I did not have this problem with the previous iteration which used HttpWebRequest/HttpWebResponse objects. From what I've read, HttpClient is supposed to be the better option, so our firm has invested time in researching it and switching over.
I am using HttpClient directly, not the factory. The Windows Service application I am working on polls embedded systems, and makes several requests per IP, sequentially (awaited), to get different bits of data. The URI is always the same, with different POST data to tell the device what to return. I can see using netstat that several connections are open to the same IP & port, most sitting at TIME_WAIT status (see below). There are multiple instances of this Windows Service running, each using different groups of IP addresses, so are essentially running like multiple threads. This can add up to a lot of requests in a short time. Note that only one request to a given IP is in operation at a time.
I have tried using these suggestions:
httpClient.DefaultRequestHeaders.ConnectionClose = true;
(and leaving it unassigned)
httpClientHandler.MaxConnectionsPerServer = 1;
(and leaving it unassigned)
Disposing of HttpResponseMessage objects
(they were already wrapped in Using blocks).
These have had no effect. My supposition is that the sockets won't get reused until the TIME_WAIT expires, but I am confused. If ConnectionClose is not used, why is it not reusing the HttpClientHandler and the last socket it had open?
When Connection: Keep-Alive is in the request header (ConnectionClose is false or null), I am seeing the application side close the connection after each request (FIN-ACK, etc.). Shouldn't the application side be waiting for further requests? I think I see the problem: the remote device has "Connection: close" in its header. For the record, the device manufacturer says that keep-alive should NOT be used, and it appears that they enforce this on their end if the client side doesn't. My guess is that this forces the socket into the TIME_WAIT state. It seems that, after the connection is torn down, TIME_WAIT should be aborted, so the socket can be reused.
Note that I am not an HTTP expert, so I could be making bad assumptions here. Thanks for your forbearance in advance.

Here is a tail section of "netstat -p tcp -n" output. I have removed lines that are not related to our app.
TCP 192.168.163.8:58179 10.239.128.67:80 TIME_WAIT
TCP 192.168.163.8:58207 10.239.128.67:80 TIME_WAIT
TCP 192.168.163.8:58259 10.239.128.67:80 TIME_WAIT
TCP 192.168.163.8:58314 10.239.128.85:80 TIME_WAIT
TCP 192.168.163.8:58328 10.239.128.85:80 TIME_WAIT
TCP 192.168.163.8:58368 10.239.128.86:80 TIME_WAIT
TCP 192.168.163.8:58387 10.239.128.86:80 TIME_WAIT
TCP 192.168.163.8:58448 10.234.72.67:80 TIME_WAIT
TCP 192.168.163.8:58498 10.234.72.85:80 TIME_WAIT
TCP 192.168.163.8:58564 10.234.72.86:80 TIME_WAIT
TCP 192.168.163.8:58612 10.234.72.87:80 TIME_WAIT
TCP 192.168.163.8:58631 10.234.72.87:80 TIME_WAIT
TCP 192.168.163.8:58651 10.235.44.67:80 TIME_WAIT
TCP 192.168.163.8:58661 10.235.44.67:80 TIME_WAIT
TCP 192.168.163.8:58682 10.235.44.67:80 FIN_WAIT_1
TCP 192.168.163.8:58700 10.212.196.67:80 LAST_ACK
TCP 192.168.163.8:58706 10.212.196.67:80 SYN_SENT
TCP 192.168.163.8:58708 10.235.44.85:80 SYN_SENT

**Comment by benaadams** [comment]
> I am using HttpClient directly, not the factory

Are you creating multiple `HttpClient`s and if so are you calling `.Dispose()` on them; or are you using a single `readonly static HttpClient` (so not Disposing it)?

**Comment by gmorris007** [comment]
> > I am using HttpClient directly, not the factory
> 
> Are you creating multiple `HttpClient`s and if so are you calling `.Dispose()` on them; or are you using a single `readonly static HttpClient` (so not Disposing it)?

I am creating multiple `HttpClient` objects, one per IP address, which stay alive for the life of the application. They get reused at the start of a new polling cycle. The application is meant to run indefinitely.

**Comment by scalablecory** [comment]
> Shouldn't the application side be waiting for further requests? I think I see the problem: the remote device has "Connection: close" in its header.

Yes, closing the socket when we receive "Connection: close" is correct behavior.

> It seems that, after the connection is torn down, TIME_WAIT should be aborted, so the socket can be reused.

TIME_WAIT is a fundamental part of how TCP works -- it can't be aborted safely.

What you can do -- and I want to emphasize that this is not a good idea unless you have very controlled behavior -- is to override `SocketsHttpHandler.ConnectCallback` with something that manages a set of ports and sockets with `SO_REUSEADDR` set.

This is not something we would ever do by default.

**Comment by benaadams** [comment]
`TIME_WAIT` is more a function of TCP than Http; it's the final state the socket ends up in before closure:

![image](https://user-images.githubusercontent.com/1142958/101043754-8d6bd700-3576-11eb-9da0-e96a2244d73c.png)

`TIME_WAIT` will end up on one side of the socket (client or server); since the server can only use 1 port `80` whereas the client uses a large range of 16k+ ports (e.g. 49152 - 65535), it is better if the `TIME_WAIT` ends up on the client; as it can pick the next port to use that doesn't conflict; as the address of the socket is a 4 part tuple `(IP:PORT, IP:PORT)` 

Can check the allowed range on Windows with:
```
> netsh int ipv4 show dynamicport tcp


Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 49152
Number of Ports : 16384
```

If you do have client port exhaustion from closing sockets then there are a few things you can do:

1. Increase number of available ephemeral ports https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-port-exhaust

e.g. increasing to 55k
```
> netsh int ipv4 set dynamicport tcp start=10000 numberofports=55535
Ok.

> netsh int ipv4 show dynamicport tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 10000
Number of Ports : 55535
```

2. Increase the number of TCP Control Blocks (e.g. concurrent connections (Active + TIME_WAIT))

[`HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters`]
`MaxFreeTcbs` = 10000 (Default = RAM dependent, but usual Pro = 1000, Srv=2000)

Note: Each will use 1Kb (0.5kb Non paged)

Bump up the hashset to match

[`HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Tcpip\Parameters`]
`MaxHashTableSize` = 5000 (Default = 512, Range = 64-65536)

3. Decrease the `TIME_WAIT` wait time (4 minutes/60 sec on exhaustion); 

`[HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Tcpip\Parameters]`
TcpTimedWaitDelay = 30 (Default = 240 secs, Range = 30-300)

4. Set `SO_REUSEADDR` on the socket (though you'd have to manage the sockets directly and return NetworkStreams via  `SocketsHttpHandler.ConnectCallback`

`SO_REUSEADDR` [has security issues](https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse); so you may also want to apply `SO_EXCLUSIVEADDRUSE`

If you are opening all the connections simultaneously every minute; then you may also hit SYN-Attack-Protection in Windows; so you could either stager the opens over a slightly larger time period (within the minute); or turn it off

[`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters`]
`EnableConnectionRateLimiting` = 0

**Comment by scalablecory** [comment]
Closing this issue as there's nothing we can do about it and you've been given a few options.

**Comment by gmorris007** [comment]
@benaadams Thanks for your detailed response. I was actually reviewing {http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html) when your message came in. I will review the information I have now and try to come up with a solution. The article mentioned above also talks about "...setting the SO_LINGER socket option to 0..." to prevent TIME_WAIT. I'm not sure how to do that or if it's a good idea. The server instances are all firewalled and we access them thru a VPN so should be safe from DOS and other attacks.

**Comment by benaadams** [comment]
If the number of connections isn't unexpectedly high (other than them being in `TIME_WAIT`); I'd start with increasing the limits (e.g. `MaxFreeTcbs` and port range ) before reducing the safety/protections
