### ISSUE TITLE
System.Text.Json defines netcoreapp3.0 with no dependencies

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#45560]
Users are hitting an issue with needing to add an explicit reference to System.Text.Encodings.Web when they have System.Text.Json 5.0.0 in a netcoreapp3.1 project. I'm not sure why there is even a netcoreapp3.0 target for this package, but that's not my concern.

Looks like the regression was added between preview8 and rc1 of the 5.0.0 package.

![image](https://user-images.githubusercontent.com/7574801/101072020-36540b00-3552-11eb-8ca5-8a8893363d99.png)

**Comment by BrennanConroy** [comment]
@ericstj Could someone look into this as a possible 5.0.2 fix?

**Comment by ericstj** [comment]
This is because the build of System.Text.Json for `netcoreapp3.0` doesn't have a reference to the "live" built System.Text.Encoding.Web, instead it references the version from the shared framework.  This creates a compatibility problem because the `netstandard2.0` version references a higher version of the dependency than is inbox on `netcoreapp3.0`

I believe this was caused by https://github.com/dotnet/runtime/commit/809a06f45161ae686a06b9e9ccc2f45097b91657.  Previously the ref path build process would ensure that all libraries built would build against the live version of live built dependencies. 

This is similar to https://github.com/dotnet/runtime/issues/40208.

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Ufff. @ericstj suggestions how to protect this in CI?

**Comment by ericstj** [comment]
We don't have a great place today to test consistency of dependencies between two different compatible TFMs.  @Anipik perhaps we can capture this in our list of things to validate packages for?

**Comment by ViktorHofer** [comment]
Can you please elaborate on "consistency of dependencies between two different compatible TFMs."?

**Comment by ericstj** [comment]
Nothing compares the dependencies referenced by a package when that package is resolved for 2 different compatible TFMs.  That's the sort of testing that would need to happen here to catch this bug.

The problem is that this package, when resolved for `netstandard2.0` exposes a System.Text.Encodings.Web version 5.0.0.0 assembly, but when resolved for `netcoreapp3.0` it only exposes a 4.0.4.0 assembly.  To catch this type of problem we'd need to evaluate restoring the packages and examining all sets of assemblies in the closure for compatibility between two different TFMs.  One shortcut for this might be two compare the packages referenced, however we often intentionally trim package references when the assembly referenced is also inbox.

**Comment by ericstj** [comment]
@ViktorHofer do you have ideas for how to scan for other instances of this issue?

One thought I had was we could insist on a ProjectReference on non NetCoreAppCurrent frameworks if a project exists (suppressable).  What do you think?

**Comment by ViktorHofer** [comment]
Yeah already at it. I had to finish the infrastructure rollout notification first which was higher prio. I'm currently looking at any projects that contain configurations older than `$(NetCoreAppCurrent)` which contain a pkgproj in its leaf. Filtering this further to just look for projects with P2P makes sense. Thanks for the suggestion.

**Comment by ViktorHofer** [comment]
Reopening to track backporting into release/5.0.

**Comment by BrennanConroy** [comment]
I know there has been work in this area, is there still some work left?

**Comment by ViktorHofer** [comment]
No, just forgot to close. Thanks.
