### ISSUE TITLE
Vector min/max do not handle NaNs consistently

### ISSUE THREAD

**Issue by RossNordby** [dotnet/runtime#4558]
Logically irrelevant code changes can influence the result of Min and Max when NaN values are involved.

For example:

``` C#
        public static Vector4 Repro()
        {
            Vector4 notNan = new Vector4(0);
            Vector4 nan = new Vector4(float.NaN);
            return Vector4.Max(notNan, nan);
        }
```

returns the expected (NaN, NaN, NaN, NaN) while this:

``` C#
        public static Vector4 Repro()
        {
            Vector4 nan = new Vector4(float.NaN);
            Vector4 notNan = new Vector4(0);
            return Vector4.Max(notNan, nan);
        }
```

returns (0,0,0,0).

Disassembly for the first case:

```
            Vector4 notNan = new Vector4(0);
00007FFD57424A80  xorps       xmm0,xmm0  
            Vector4 nan = new Vector4(float.NaN);
00007FFD57424A83  movss       xmm1,dword ptr [7FFD57424A98h]  
00007FFD57424A8B  shufps      xmm1,xmm1,0  
            return Vector4.Max(notNan, nan);
00007FFD57424A8F  maxps       xmm0,xmm1  
00007FFD57424A92  movups      xmmword ptr [rcx],xmm0
```

versus the second:

```
            Vector4 nan = new Vector4(float.NaN);
00007FFD57414A80  movss       xmm0,dword ptr [7FFD57414A98h]  
00007FFD57414A88  shufps      xmm0,xmm0,0  
00007FFD57414A8C  xorps       xmm1,xmm1  
            return Vector4.Max(notNan, nan);
00007FFD57414A8F  maxps       xmm0,xmm1  
00007FFD57414A92  movups      xmmword ptr [rcx],xmm0
```

It appears that maxps input parameter order is generated without regard for the NaN corner case, so the register fill order defines the result.

I haven't tested with AVX. The no-optimizations fallback produces the expected result either way, returning the second parameter value when NaNs are involved.

category:correctness
theme:vector-codegen
skill-level:intermediate
cost:small

**Comment by am11** [comment]
Since .NET Core 3.1, it is returning `<NaN, NaN, NaN>` from both `Repro()` method. The [x64 disassembly](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkBXfGKASzFwBuGvSasAShwB2GXtxYBhCPgAOvADY8AyjwBu/GEJGNmLSTLkwWASRk8IKnVH1hDw6jQDEUjuvXZgTQYYKQDNGhEAZiZSBgUGAG8aBhTUtKZo5iQGADUYMAxoFAZxGBUoCAAKAEpk9JSk6nr6vIKihikIDDZsKQYAXg6YAHdc/MKoFEq6avdm9NaJ4tC+wakRsbbJyoAzdQhsDHZsNlm6+ZTiAHZNpZYAWWwESs7u3rQO3rOm5oBfc/SxEy5Gyi3apXKEFINQBaUaF1SYMmn1WQ1GSKmewORx6pzmCNu7VePVR63R4yK02+BKYNwxDyeLy6JI+K2pfwi1F+QA) shows the parameter order of `vmaxps` has been corrected by the JIT.

**Comment by am11** [comment]
Since .NET Core 3.1, it is returning `<NaN, NaN, NaN>` from both `Repro()` methods. The [x64 disassembly](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkBXfGKASzFwBuGvSasAShwB2GXtxYBhCPgAOvADY8AyjwBu/GEJGNmLSTLkwWASRk8IKnVH1hDw6jQDEUjuvXZgTQYYKQDNGhEAZiZSBgUGAG8aBhTUtKZo5iQGADUYMAxoFAZxGBUoCAAKAEpk9JSk6nr6vIKihikIDDZsKQYAXg6YAHdc/MKoFEq6avdm9NaJ4tC+wakRsbbJyoAzdQhsDHZsNlm6+ZTiAHZNpZYAWWwESs7u3rQO3rOm5oBfc/SxEy5Gyi3apXKEFINQBaUaF1SYMmn1WQ1GSKmewORx6pzmCNu7VePVR63R4yK02+BKYNwxDyeLy6JI+K2pfwi1F+QA) shows the parameter order of `vmaxps` has been corrected by the JIT.

**Comment by RossNordby** [comment]
Pretty sure this has been fixed for a while, so I suppose I'll just, press this button.
