### ISSUE TITLE
Parent of CultureInfo.GetCulture("nb") has changed

### ISSUE THREAD

**Issue by jbearfoot** [dotnet/runtime#45588]
Previously CultureInfo.GetCulture("nb") had a parent "no", now the parent is Invariant culture. I do not know what is 
linguistically correct but it is a different behavior at least.  

The difference is at least between .NET framework and net5.0 but I think the same difference is between netcoreapp3.1 and net5.0

I run the test on Windows 10

**Comment by tarekgh** [comment]
@jbearfoot In .NET 5.0 we have switched to use ICU library instead of NLS Win32 APIs. It is expected to see some differences but mostly will get the behavior seen on Linux before. You may consult the doc https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu for more info. 

ICU picks its data from CLDR which is the Unicode standard. So, usually ICU be more correct linguistically. I am closing the issue but feel free to send any question or ask and we'll be happy to help with.
