### ISSUE TITLE
[PortableThreadPool] ASP.NET TE benchmarks on Windows are slower

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#45716]
Just to add some data, most aspnet benchmarks are also down on windows with this change. Some also on linux but not as much.

![image](https://user-images.githubusercontent.com/1165805/101402722-fad67b00-3888-11eb-99cb-643bee573240.png)

_Originally posted by @sebastienros in https://github.com/dotnet/runtime/issues/44211#issuecomment-740166204_

**Comment by kouvel** [comment]
From a brief look a difference looks like the same operations that were there before the change got more expensive after (some work got faster, perf bottleneck shifted, and some operations that weren't changed got more expensive), there may be other reasons as well. The Windows IO system hasn't been optimized much, there are thoughts around that as well, may need some investigation.

**Comment by fanyang-mono** [comment]
Portable thread pool may also have affected the TE benchmarks on ARM with Linux for both CoreCLR and Mono, especially for PlaintextPlatform and JsonPlatform scenarios. According to the following screenshots, the charts started to fluctuate since it started to measure .NET6

<img width="1489" alt="Screen Shot 2020-12-14 at 1 57 33 PM" src="https://user-images.githubusercontent.com/52458914/102123006-53bb8b80-3e14-11eb-907c-2c882d76655f.png">

<img width="1489" alt="Screen Shot 2020-12-14 at 1 59 18 PM" src="https://user-images.githubusercontent.com/52458914/102123161-91b8af80-3e14-11eb-94c8-43d0322b3940.png">

**Comment by kouvel** [comment]
Thanks, I'll take a look to see if it's the same issues

**Comment by kouvel** [comment]
Looks like the arm issue is the same
