### ISSUE TITLE
ComObject from Window (.Net 5)

### ISSUE THREAD

**Issue by Gavin-Williams** [dotnet/runtime#45735]
I want to create a swapchain for the window without any xaml.

SharpDX has the following technique to construct a swapchain ...

```CSharp
using (var windowAsCom = new ComObject(coreWindow))
{
    tempSwapChain = new SwapChain1(CoreGraphics.dxgiFactory, CoreGraphics.Device3d, windowAsCom, ref SwapChainDesc);
}
```

Can .Net 5 / WinUI provide a ComObject for this call?

https://github.com/microsoft/microsoft-ui-xaml/issues/3773

**Comment by AaronRobinsonMSFT** [comment]
@Gavin-Williams Can you elaborate a bit more on what is being expressed above. I am unfamiliar with the "swapchain" concept in COM or WinRT. For WinRT, the .NET projections are all pre-generated and provided by the [C#/WinRT](https://github.com/microsoft/CsWinRT) tool chain.

**Comment by Gavin-Williams** [comment]
I have no idea what COM is myself other than - I believe it to be a convention to enable multilingual objects or maybe other kinds of objects to communicate with one another.

The SharpDX ComObject class is as follows...

`namespace SharpDX
{
    [Guid("00000000-0000-0000-C000-000000000046")]
    public class ComObject : CppObject, IUnknown, ICallbackable, IDisposable
    {
        public static Action<string> LogMemoryLeakWarning;

        public ComObject(object iunknowObject);
        public ComObject(IntPtr nativePtr);
        protected ComObject();

        public static T As<T>(object comObject) where T : ComObject;
        public static T As<T>(IntPtr iunknownPtr) where T : ComObject;
        public static bool EqualsComObject<T>(T left, T right) where T : ComObject;
        public static T QueryInterface<T>(object comObject) where T : ComObject;
        public static T QueryInterfaceOrNull<T>(IntPtr comPointer) where T : ComObject;
        public virtual T QueryInterface<T>() where T : ComObject;
        public virtual void QueryInterface(Guid guid, out IntPtr outPtr);
        public virtual IntPtr QueryInterfaceOrNull(Guid guid);
        public virtual T QueryInterfaceOrNull<T>() where T : ComObject;
        protected override void Dispose(bool disposing);
        protected override void NativePointerUpdated(IntPtr oldNativePointer);
        protected override void NativePointerUpdating();
        protected void QueryInterfaceFrom<T>(T fromObject) where T : ComObject;

        public static explicit operator ComObject(IntPtr nativePtr);
    }
}`

The swapchain is a DirectX 11 swapchain. Somehow the window object's drawing surface is being obtained by SharpDX - perhaps the underlying WindowHandle? Is that a pointer to a raw drawing surface? I don't know.

**Comment by AaronRobinsonMSFT** [comment]
@Gavin-Williams Thanks for pointing out that the [`ComObject`](https://github.com/sharpdx/SharpDX/blob/1f89381bc08f2d8cf8d294c6c5fce8dc85a849a1/Source/SharpDX/ComObject.cs#L37-L44) in question is the SharpDX implementation and not our own. [COM](https://docs.microsoft.com/windows/win32/com/the-component-object-model) is basically an ABI contract for a myriad of things and is about 30 years old - this doesn't due it justice but at this point that is the TL;DR. It is very useful but due to age is rather clunky in places.

I don't fully get what this swap chain mechanism is nor do I claim to know anything about DirectX or UI development in general. I will only speak to what I see from a cursory look at the SharpDX code. SharpDX appears to rely upon the built-in COM support in .NET Core 3+ and .NET 5. WinRT support in .NET 5 is provided by the C#/WinRT tool chain and consumes the [`ComWrappers` API](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers). This API is supported in some of the built-in COM APIs but doesn't behave exactly the same way. The break down on all these differences is nuanced and esoteric so I won't clutter this issue, but there are differences. It is entirely possible the C#/WinRT generated APIs can be supported in SharpDX but that would require an investigation by the C#/WinRT team or someone from the community to root out the discrepancies and determine if they are runtime issues or C#/WinRT generated code issues.

There are two bright spots I can offer at this point. (1) One of the contributors to SharpDX is a colleague (@jkoritzinsky) and he wrote part of C#/WinRT so may be able to provide more insight. (2) the second `ComObject` constructor takes an `IntPtr` which I think is retrievable from the generated C#/WinRT classes and should be what is expected - @jkoritzinsky would also be able to help with that.

**Comment by andrew-boyarshin** [comment]
`ComObject` is actually part of _SharpGen_ (maintained by @jkoritzinsky), it's just that _SharpDX_ and [Vortice](https://github.com/amerkoleci/Vortice.Windows) ship their own version of it with minor changes. SharpGen doesn't rely on built-in COM support (instead, it generates its own wrapper around Vtbl), but it does interface with it (e.g. you can construct ComObject from `IUnknown` wrapped by .NET as `object`).

This question is highly off-topic, since it is about constructing DirectX swapchains from UAP/UWP `CoreWindow`. It does relate much more to the UWP core, rather than .NET, so I'm surprised that Microsoft developer redirected it to the .NET repo (although, not this one specifically, to be fair).

Short version to actually answer your question:
You need to [create DXGI factory](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-createdxgifactory1), downcast to IDXGIFactory2, then create swapchain specifically for your `CoreWindow` using  [IDXGIFactory2::CreateSwapChainForCoreWindow](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgifactory2-createswapchainforcorewindow). I don't know how exactly do you obtain `CoreWindow` instance since that's specific to your app. If you have a native `IUnknown` pointer or the wrapper created by `Marshal.GetObjectForIUnknown`, you can construct `ComObject` (for SharpDX) or `IUnknown` (for Vortice) right from it (there are constructors both for `IntPtr` and `object`).

**Comment by AaronRobinsonMSFT** [comment]
@andrew-boyarshin Thank you for the comprehensive answer. It aligns well with the current runtime design for WinRT and my limited understanding of the external libraries involved here.

>2.5. Do you run as an actual UWP compiled with .NET Native in Release mode? If so, the story is different (not related to .NET 5 and CsWinRT), and likely more complicated (I don't know how it works there, @AaronRobinsonMSFT should know better). But the point remains, you need to acquire native IUnknown pointer as IntPtr or .NET RCW wrapper for it as object.

The default constructor taking an `object` should work just fine for the existing UWP scenario (i.e. .NET Native).

Given the description and workarounds above I am going to close this issue. @Gavin-Williams Sorry to do this to you, but I think the best location for this issue is on SharpDX to support the new C#/WinRT generated types or in the C#/WinRT repo to ensure the scenario works for SharpDX. I appreciate the non-trivial nature of this, many apologies, but it sounds like moving to Vortice is the best way forward. Validating and filing issues to ensure that C#/WinRT can be used with that library seems most appropriate.

**Comment by Gavin-Williams** [comment]
SharpDX is archived. There are no more issues being filed or resolved.
