### ISSUE TITLE
UTF8Encoding still emitting BOM

### ISSUE THREAD

**Issue by 89z** [dotnet/runtime#45731]
If I run a command like this:

~~~
Write-Output March > a.txt
~~~

I get this result:

~~~
        U+FEFF    
M       U+004D          
a       U+0061          
r       U+0072    
c       U+0063          
h       U+0068 
        U+000D       
\n      U+000A       
~~~

I do not want the BOM. I tried different actions, like this:

~~~
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
$PSDefaultParameterValues['*:Encoding'] = 'utf8'
[Console]::InputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
~~~

but none of them seem to address the issue. Note I am using PowerShell 5.1.

**Comment by GrabYourPitchforks** [comment]
Powershell's _Write-Output_ command is used to send text to the next pipeline stage. When you use the `>` operator, that's (in PS 5.1) sending it to the file system as UTF-16 LE with BOM, not UTF-8 with BOM. (I confirmed this on my own box, as the resulting output file was 16 bytes in length, whereas UTF-8 with BOM would result in a 10-byte output.)

This is a Powershell behavior and the .NET team has no control over this. Check the instructions at https://github.com/powershell/powershell#windows-powershell-vs-powershell-core for how to file issues for the version(s) of Powershell you're using. You could also check solutions like https://stackoverflow.com/a/48851642, but I can't vouch for them since I'm not familiar enough with PS.
