### ISSUE TITLE
Libraries AllConfigurations failing

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#45782]
Libraries AllConfigurations is failing with the following errors:

> src\libraries\pkg\test\testPackages.proj(214,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Validation Failed: System.Security.Cryptography.Pkcs is harvesting assets from package version 5.0.0 which is not the latest for that package release. Latest package version from that release is 5.0.1. In order to fix this, run `dotnet msbuild System.Security.Cryptography.Pkcs.pkgproj /t:UpdateHarvestVersionOnPackageIndex /p:UpdateStablePackageInfo=true`

> src\libraries\pkg\test\testPackages.proj(214,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Validation Failed: System.IO.Pipelines is harvesting assets from package version 5.0.0 which is not the latest for that package release. Latest package version from that release is 5.0.1. In order to fix this, run `dotnet msbuild System.IO.Pipelines.pkgproj /t:UpdateHarvestVersionOnPackageIndex /p:UpdateStablePackageInfo=true`

https://github.com/dotnet/runtime/pull/45779/checks?check_run_id=1519390883

**Comment by safern** [comment]
@xtqqczze thanks for reaching out. This was fixed by: https://github.com/dotnet/runtime/pull/45775, it is possible that your build ran before this fix was merged. If you run your pipeline again (by opening/closing, or pushing a new commit) you shouldn't see this failure anymore.

Please let me know if you don't have any luck and I can definitely help.

**Comment by xtqqczze** [comment]
@safern Build for #45779 was on 10381a2. So you are right, the build ran before the fix was merged.
