### ISSUE TITLE
net core   can not use com SHDocVw

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45820]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/net-core---can-not-use-com-SHDocVw/1276475)._

---
[severity:I'm unable to use this version]
When I use net core technology to use SHDocVw COM component, I always return empty document, as shown in the figure, but the same code is normal in net framework.
---------------------------------------------------------------------------------------
! [1606967934(1).png] (https://aka.ms/dc/image?name=B4d33cad6390f4096bb78778a2cce5b2b637425647638167819_1606967934(1).png&tid=4d33cad6390f4096bb78778a2cce5b2b637425647638167819)

---
#### Feedback Bot on 12/2/2020, 11:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by raoyutian** [comment]
I use the code **document = ieTab.Document as HTMLDocument;** ,
 NET Framework ,net core are all OK

**Comment by AaronRobinsonMSFT** [comment]
@raoyutian This issue is likely "by-design" due to some decisions made early in the the port of COM support to .NET Core. The gist here is the inability to use "class" types during most casts. In order to confirm this can you try casting to one of the underlying COM interface types rather than the class type (e.g. [`IHTMLDocument2`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752574(v=vs.85))). Other options exist as documented [here](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752052(v=vs.85)#remarks).
