### ISSUE TITLE
[Question] How to use the ActivitySource Entrypoints of an Application

### ISSUE THREAD

**Issue by mjeanrichard** [dotnet/runtime#45843]
I am trying to instrument a messaging library with the new ActivitySource. According to the [docs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md)
I should use the ActivitySource for this.

Lets assume I have the following scenario:
```
|------Activity 1: Consume Message ----------|   <-- no listener
      |------Activity 2: Process Message ---|  <-- has listener
                 |---- Activity 3: Do something else ----- |   <-- has listener
```

The start of Activity 1 is a message that comes from somewhere outside of my application, but it has an ActivityId attached somehow. If I use `ActivitySource.StartActivity("Consume", ActivityKind.Consumer, parentIdFromMessage)` to create this Activity, it will return `null` since there is no listener. 
This also means that any subsequent Activities that might have a listener will also not have the root activity Id, because it was not applied when the first activity was started.

What do I need to do to ensure that the parent Id is always set correctly? Is the ActivitySource the wrong choice for this first Activity? Am I missing something?

**Comment by tommcdon** [comment]
@noahfalk @sywhang @tarekgh

**Comment by tarekgh** [comment]
@mjeanrichard you have the choice when creating any new Activity using `ActivitySource.StartActivity` to pass the parentContext which will set the parent Id. So you have control over what parent you want to have to the created Activity. If you want to ensure the Parent Activity is always created even if there is no listener, then use `new Activity(...)` and start it instead of using `ActivitySource.SatrtActivity`. 

I am closing this issue but feel free to send any more questions and we'll be happy to help with. Thanks for your report.
