### ISSUE TITLE
3.1 exes should be emitted as -pie enabled

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/runtime#45862]
BinSkim reports that dotnet exes cross-compiled for *nix platforms are not -pie enabled. This has reportedly been resolved in .NET 5.0, can we consider back-porting as appropriate? @jegour

**Comment by eddynaka** [comment]
cc: @jegour

**Comment by carstencodes** [comment]
Hello,

I would much appreciate this. We're currently inspecting the FDD executables for a linux software created by `dotnet publish`.

When creating the debian package for our software and check the result via lintian, we get warnings like the following:

dspace-sampleproject: hardening-no-fortify-functions opt/dspace/common/sampleproject/bin/sampleproject
dspace-sampleproject: hardening-no-bindnow opt/dspace/common/sampleproject/bin/sampleproject
**dspace-sampleproject: hardening-no-pie opt/dspace/common/sampleproject/bin/sampleproject**

We're currently not using .NET 5.0 since it lacks a long term support making it hard to adapt.

It would be good, if the executables would be positioned independent. Any chance of back-porting this fix to .NET core 3.1 SDK?

cc: @sschukat

**Comment by mangod9** [comment]
@ivdiazsa is currently working on porting this change. Thx

**Comment by mangod9** [comment]
Yeah this has merged as with https://github.com/dotnet/coreclr/pull/28143. So it should be included in the latest 3.1 update. Will close it now.
