### ISSUE TITLE
For anyone else who comes across this problem and doesn't have the luxury of using an alternative library libgdiplus can be installed through EPEL on Amazon Linux with:

### ISSUE THREAD

**Issue by roopeshkurian** [dotnet/runtime#45881]
As you mentioned 
I have created two files 

file1.config

container_commands:
    epel_extras:
        command: "sudo amazon-linux-extras install epel"

file2.config 

container_commands:
    epel_extras:
        command: "sudo yum install libgdiplus"
Still I am unable to  use SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0

Can you please help me ?

For anyone else who comes across this problem and doesn't have the luxury of using an alternative library libgdiplus can be installed through EPEL on Amazon Linux with:

sudo amazon-linux-extras install epel
sudo yum install libgdiplus

I've confirmed this works with Elastic Beanstalk

_Originally posted by @peter-manton in https://github.com/dotnet/runtime/issues/33748#issuecomment-665707170_

**Comment by safern** [comment]
Thanks for the issue. This is by design as System.Drawing.Common depends on libgdiplus on Unix and we don't carry a copy of it, it has to be manually installed by the user. We know this is not an ideal scenario and we are discussing what to do with that, however, SYstem.Drawing.Common was ported to Unix for compat reasons and libgdiplus is community driven, so we don't recommend new development for cross plat using it. We instead recommend other alternatives in the docs: https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-5.0#remarks
