### ISSUE TITLE
Regex.Escape doesn't escape ] ) }

### ISSUE THREAD

**Issue by LazaroOnline** [dotnet/runtime#45896]
`Regex.Escape` currently only escapes this set of characters:  
> \, *, +, ?, |, {, [, (,), ^, $, ., #, and white space.

as per [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.escape),
it states that it escapes the "minimal" set of characters, but the definition of "minimal" is subjective, and I would have expected it to also include at least these 3 characters:  `] ) }`.

The issue comes when trying to do something like this:
```cs
var someInputText = "test with special char ]";
var specialChars = "[](){}";
var containsSpecialCharacters = Regex.IsMatch(someInputText , "([" + Regex.Escape(specialChars ) + "]+)");
```
The above example will fail, it is not obvious to find that the "]" is not being escaped.
I understand that usually the "]" doesn't have a special meaning unless I put a "[" before it, and the one at fault may be me.
However, I think it would be greatly beneficial to also escape `] ) }` and prevent common errors considering how easy the implementation would be, and that it would make it easier for web developers to transition from JS code to C# code since that is how most regex escape implementations work in JavaScript like the MDN example [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Escaping)
or [lodash](https://lodash.com/docs/4.17.15#escapeRegExp), escapes `], ), }`.

If changing this behavior in `Regex.Escape` wouldn't be possible to keep compatibility, then maybe we could have a "less minimal" version like `Regex.EscapeAll()` to achieve this.

**Comment by danmosemsft** [comment]
Interesting. The MDN section you linked to notes that Javascript standards committee rejected the proposal to add an escape() method because they noted it would not avoid exactly the kind of problem that you're hitting here:
https://github.com/benjamingr/RegExp.escape/issues/37
Even if they escaped close bracket, prefixing with slashes could defeat it.

Which begs the question, what is the value of our Escape method? The docs have an example where I think it is safe -- where the regex part is only preceded by escaped characters.
https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.escape?view=net-5.0

That doc also notes

> While the Escape method escapes the straight opening bracket ([) and opening brace ({) characters, it does not escape their corresponding closing characters (] and }). In most cases, escaping these is not necessary. If a closing bracket or brace is not preceded by its corresponding opening character, the regular expression engine interprets it literally. If an opening bracket or brace is interpreted as a metacharacter, the regular expression engine interprets the first corresponding closing character as a metacharacter. If this is not the desired behavior, the closing bracket or brace should be escaped by explicitly prepending the backslash (\) character.

My tentative conclusion is that whether or not we escaped close bracket, there would always be characters that it would be invalid to prefix the result with. In your case it's open bracket; if we escaped close bracket, then it could be backslash, and potentially others.

Maybe escaping these three would at least improve the situation -- we'd have to carefully consider whether it would break anyone, too.

Meantime to achieve what you want, I suggest to [use IndexOfAny](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexofany?view=net-5.0)

**Comment by danmosemsft** [comment]
More interesting discussion here

**Comment by danmosemsft** [comment]
More interesting discussion
https://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript/3561711

**Comment by ygra** [comment]
Has also been noted before: #29068

**Comment by danmosemsft** [comment]
@LazaroOnline I'm going to close per the above. The benefit is marginal - it's not zero, but small enough to probably not be worth the possibility of breaking someone.
