### ISSUE TITLE
Question: Can I share a base HttpClientHandler between two HttpClient DI consumers?

### ISSUE THREAD

**Issue by ssa3512** [dotnet/runtime#45933]
I am trying to configure a delegating handler to pull a token at a set interval and would like to share the same base HttpClientHandler between the HttpClient passed to the delegating handler and the primary HttpClient such that my send pipeline looks like this

Delegating Handler called -> gets token if not set or expired, sets request header -> Base handler called

The output of the below program handles the scenario I need and logs the following output:
```
Delegating handler called: https://microsoft.com/hello

Base handler called: https://microsoft.com/token
Headers:
x-auth-key: someauthkey

Base handler called: https://microsoft.com/hello
Headers:
x-auth-key: someauthkey
Authorization: bearer tokenValue
```

I have tried numerous ways to set this up using the Microsoft.Extensions.Http DI packages but can't seem to figure out how to get the two HttpClient instances to share a handler when one of them is also consuming the other as a delegating handler. Is this something that is possible? The key is that I would like to set the MaxConnectionsPerServer for the handler and have this shared between the delegating handler HttpClient and primary HttpClient since they are calling the same server.

```cs
async Task Main()
{
	await NoDi();
}

async Task NoDi()
{
	var handler = new TestHttpClientHandler()
	{
	};
	var baseClient = new HttpClient(handler)
	{
		BaseAddress = new Uri("https://microsoft.com")
	};
	baseClient.DefaultRequestHeaders.Add("x-auth-key", "someauthkey");
	var delegatingHandler = new TestDelegatingHandler(baseClient)//, handler)
	{
		InnerHandler = handler
	};
	var wrapperClient = new HttpClient(delegatingHandler)
	{
		BaseAddress = new Uri("https://microsoft.com")
	};
	wrapperClient.DefaultRequestHeaders.Add("x-auth-key", "someauthkey");

	await wrapperClient.GetAsync("hello");
}

public class ClientConsumer
{
	private readonly HttpClient httpClient;
	public ClientConsumer(HttpClient httpClient)
	{
		this.httpClient = httpClient;		
	}
	
	public Task CallHttp()
	{
		return httpClient.GetAsync("hello");
	}
}

public class TestDelegatingHandler : DelegatingHandler
{
	private readonly HttpClient httpClient;

	public TestDelegatingHandler(HttpClient httpClient)
	{
		this.httpClient = httpClient;
	}

	protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		Console.WriteLine($"Delegating handler called: {request.RequestUri}");
		Console.WriteLine();

		var response = await httpClient.GetAsync("token");
		var token = await response.Content.ReadAsStringAsync();
		
		request.Headers.Authorization = new AuthenticationHeaderValue("bearer", token);

		return await base.SendAsync(request, cancellationToken);
	}
}

public class TestHttpClientHandler : HttpMessageHandler
{
	protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		Console.WriteLine($"Base handler called: {request.RequestUri}");
		Console.WriteLine("Headers:");
		Console.WriteLine(request.Headers.ToString());
		
		if (request.RequestUri.PathAndQuery == "/token")
		{
			return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent("tokenValue") });
		}

		return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK));
	}
}
```

**Comment by CarnaViire** [comment]
Short answer is: no, you cannot (reliably) share the same handler between different client names with HttpClientFactory.

The reason for that is because HttpClientFactory is in charge of handler lifetimes - it creates, caches and disposes them. It will treat handlers for different client names as independent. If you somehow trick the factory to reuse the same handler, you may end up with the handler being disposed at an unexpected time.

If it is important to enforce single MaxConnectionsPerServer value, I would suggest to stop using HttpClientFactory and use two static/singleton instances of HttpClient instead. In that case please use SocketsHttpHandler and don't forget to set [PooledConnectionLifetime](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime?view=net-5.0) to an interval of expected DNS changes (if you were fine with HttpClientFactory, it uses 2 minutes by default).

**Comment by CarnaViire** [comment]
Closing as answered, please feel free to speak up if you feel the answer is not sufficient.
