### ISSUE TITLE
BeginSendRequest from  System.DirectoryServices.Protocols not working for receiving LDAP notifications

### ISSUE THREAD

**Issue by msoliver** [dotnet/runtime#46005]
Having trouble using System.DirectoryServices.Protocols to receive LDAP notifications. See this code for best sample C# program online:

http://dunnry.com/blog/ImplementingChangeNotificationsInNET.aspx

This works fine in .NET Framework 4.72, but I am unable to get it working in any version of .NET Core, including .NET5, despite the fixes mentioned here:

https://github.com/dotnet/runtime/issues/36690

https://github.com/dotnet/runtime/issues/28470

@joperezr - any thoughts? I believe you were the last to look at this issue earlier this year.

**Comment by joperezr** [comment]
Thanks for logging the issue! Most of the work I did was more around the interaction with the native layer on Linux in order to be able to run on non-Windows, so I haven't played around much with LDAP notifications so getting to the bottom of your issue would warrant an investigation. When you say that you are trying to run it in .NET 5, do you mean in Windows as well? or is this on Linux?

**Comment by msoliver** [comment]
@joperezr  - Hi. This was all on Windows (Win 10 client connecting to Win Server 2019 AD server). The same sample code that I linked to above works fine in .NET Framework 4.72 but I was unable to receive LDAP notifications via BeginSendRequest mechanism on any .NET Core version, nor .NET 5. No errors or exceptions while running the code, just never received notifications. 

FWIW - I was able to use the LDAP4Net package - https://github.com/flamencist/ldap4net in a .Net Core app without any issue. This library seems like a more direct wrapper of the underlying Win32 LDAP API. Let me know if I can help any further.

**Comment by danmosemsft** [comment]
This feature was broken in the original port to .NET Core.

We fixed that in May 2020 in https://github.com/dotnet/runtime/pull/37774 which added a little more test coverage but there was already a test DirectoryServicesProtocolsTests.TestAsyncSearch and it is not clear to me why it wasn't already broken; perhaps that older test isn't validating correctly.

Unfortunately a month later, the feature was broken again by this change
https://github.com/dotnet/runtime/pull/38161/files#diff-593d95f5a17a19601d6f123b5d38cab08318c80af2241e7d9d974f80815ec3edL68
This broke it because newing up the PartialResultsRetriever, although it wasn't subsequently used, is necessary to start the thread that services the async results. 

Unfortunately this means it shipped broken again. We need to rethink how often we run these tests, and find a way to make it easier to run them as well.
