### ISSUE TITLE
DateTimeFormat for the en-GB CultureInfo is incorrect on .NET 5

### ISSUE THREAD

**Issue by SimonPilkington** [dotnet/runtime#46033]
### Description

Per the title, the patterns seem incorrect. ShortDatePattern is notably wrong and causes my code to parse dates incorrectly.

```
new System.Globalization.CultureInfo("en-GB").DateTimeFormat
{System.Globalization.DateTimeFormatInfo}
    AMDesignator: "AM"
    AbbreviatedDayNames: {string[7]}
    AbbreviatedMonthGenitiveNames: {string[13]}
    AbbreviatedMonthNames: {string[13]}
    Calendar: {System.Globalization.GregorianCalendar}
    CalendarWeekRule: FirstDay
    DateSeparator: "/"
    DayNames: {string[7]}
    FirstDayOfWeek: Sunday
    FullDateTimePattern: "dddd, dd MMMM yyyy HH:mm:ss"
    IsReadOnly: false
    LongDatePattern: "dddd, dd MMMM yyyy"
    LongTimePattern: "HH:mm:ss"
    MonthDayPattern: "MMMM dd"
    MonthGenitiveNames: {string[13]}
    MonthNames: {string[13]}
    NativeCalendarName: "Gregorian Calendar"
    PMDesignator: "PM"
    RFC1123Pattern: "ddd, dd MMM yyyy HH':'mm':'ss 'GMT'"
    ShortDatePattern: "MM/dd/yyyy"
    ShortTimePattern: "HH:mm"
    ShortestDayNames: {string[7]}
    SortableDateTimePattern: "yyyy'-'MM'-'dd'T'HH':'mm':'ss"
    TimeSeparator: ":"
    UniversalSortableDateTimePattern: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'"
    YearMonthPattern: "yyyy MMMM"
```

### Configuration

x64 Windows and Linux. Most likely platform-agnostic.

### Regression?

Yes, .NET Framework is correct:

```
> System.Globalization.CultureInfo.GetCultureInfo("en-GB").DateTimeFormat.ShortDatePattern
"dd/MM/yyyy"
```

**Comment by safern** [comment]
Thanks @SimonPilkington for opening the issue. The reason why this is different in between `.NET Framework` and `.NET Core` and `.NET 5.0` is because in `.NET Framework` we used `NLS` as the globalization engine and we changed the implementation for `.NET Core` and `.NET 5.0` to use `ICU` as the globalization engine. However, from looking at the ICU data for `en-GB` it seems like we should be returning `dd/MM/yyyy`: https://github.com/unicode-org/icu/blob/master/icu4c/source/data/locales/en_GB.txt

However, I'm going to see if `ICU` is returning this value or if it is a bug on our side. In the meantime as a workaround you should be able to set the pattern you want by doing: `System.Globalization.CultureInfo.GetCultureInfo("en-GB").DateTimeFormat.ShortDatePattern = dd/MM/yyyy` (This should work on both Linux and Windows).

If you would like to have the same behavior as `.NET Framework` on Windows (note this won't provide consistency in between Windows and Linux) you can use a runtime configuration switch to tell `.NET 5.0` to use `NLS` as the backing engine. You can read more about this here: https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu. However, this is not recommended long term as even Windows is moving to use ICU. I'll update the issue once I got info on why we're returning this value.

**Comment by danmosemsft** [comment]
I see the format is correct on Linux (used 5.0.1)

Can personally confirm that `MM/dd/yyy` would be completely wrong in en-GB 😄

**Comment by am11** [comment]
```c#
using System;
using System.Globalization;
class Program
{
    static void Main() =>
        Console.WriteLine(new System.Globalization.CultureInfo("en-GB").DateTimeFormat.ShortDatePattern);
}
```
on Windows 10 (10.0.19042.630) with .NET SDK 5.0.100 gives me `dd/MM/yyyy` (both with ICU and NLS).

**Comment by tarekgh** [comment]
@danmosemsft is right, we are returning the right pattern on Windows and Linux. my guess here is on @SimonPilkington machine, the short date pattern is overridden `HKEY_CURRENT_USER\Control Panel\International` for the value of `sShortDate`. 

@SimonPilkington you may try 

```C#
    var cul = CultureInfo.GetCultureInfo("en-GB");
    Console.WriteLine($"{cul.DateTimeFormat.ShortDatePattern}");
```

This should print the value without using the user override. I am closing this issue but feel free to send any question. Thanks!

**Comment by SimonPilkington** [comment]
I am getting the incorrect value on both Windows and Linux so a registry override is unlikely. Still, if everyone else is seeing the correct value it seems like something must be wrong here. I will investigate this further.

**Comment by safern** [comment]
> I am getting the incorrect value on both Windows and Linux so a registry override is unlikely. Still, if everyone else is seeing the correct value it seems like something must be wrong here. I will investigate this further.

I got confused by that as well because  I saw that you specified both Windows and Linux on the configuration. I just tried it on both Linux and Windows and I got, `dd/MM/yyyy`. Also, I wrote a small console app to call `ICU` directly and I get `dd/MM/yyyy` as well. 

@SimonPilkington maybe the ICU version that you're using on `Linux` is old? You can run: `icuinfo` on your console to get that info. Did you try @tarekgh's suggestion that will not use an user override on `Windows`?

**Comment by tarekgh** [comment]
@SimonPilkington could you print the value of `CultureInfo.GetCultureInfo("en-GB").NumberFormat.CurrencySymbol`? I have some doubt you are running on the Invariant globalization mode.

**Comment by SimonPilkington** [comment]
@safern @tarekgh's suggestion is exactly the code I use in my application where I have the problem, but for completeness' sake:
```
System.Globalization.CultureInfo.GetCultureInfo("en-GB").DateTimeFormat.ShortDatePattern
"MM/dd/yyyy"
```
`icuinfo` returns version 13.0. The system I'm using is running Debian Unstable so all software should be relatively recent.

@tarekgh The output here is also unexpected:
```
System.Globalization.CultureInfo.GetCultureInfo("en-GB").NumberFormat.CurrencySymbol
"¤"
```

(All output is from the Immediate Window in Visual Studio with my application running unless stated otherwise.)

**Comment by tarekgh** [comment]
@SimonPilkington you are running with `Invariant globalization mode` https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization. try to turn it off on your project.

**Comment by SimonPilkington** [comment]
Yes, you are correct. I even remember enabling this now that you linked the docs. Thanks for clearing that up, and sorry about the bogus report.

**Comment by SimonPilkington** [comment]
If practical maybe it would be good to have `GetCultureInfo` throw in this scenario.

**Comment by tarekgh** [comment]
> If practical maybe it would be good to have GetCultureInfo throw in this scenario.

We have to be careful doing that. When Invariant globalization mode is turned on intentionally, throwing can cause some problems. like, if the app is using a library which not having control over and this library is creating a culture like that.

**Comment by danmosemsft** [comment]
We should perhaps move https://github.com/dotnet/runtime/blob/master/docs/design/features/globalization-invariant-mode.md out of the repo onto the docs site.
