### ISSUE TITLE
.NET 5.0 RC2 - self-contained build on Linux - version missing in generated file

### ISSUE THREAD

**Issue by rasmk** [dotnet/runtime#46087]
Already reported on RC2 (https://github.com/microsoft/dotnet/issues/1258), but it was closed without any action.

When I build a self-contained app on Linux (in a Docker container), targeted to win-64, the generated exe file misses version, copyright, and other information. When built on Windows, the information is built into the exe file as expected.

![image](https://user-images.githubusercontent.com/12119107/101621526-28046400-3a16-11eb-9ec6-77e404f3be29.png)

**Comment by wli3** [comment]
To runtime team, I think we've talked about having a crossplatform API to write PE bites. What's the progress?

**Comment by vitek-karas** [comment]
This is currently by design - there's a master issue for this somewhere (can't find it right now). Basically the root cause is that SDK uses Windows API to update native resources for windows executables. These APIs are obviously not available on Linux and instead of failing it will just "skip" that step. This applies to all native resources, so version information, manifests, icons, ...

**Comment by rseanhall** [comment]
https://github.com/dotnet/runtime/issues/3828?

**Comment by agocke** [comment]
That looks right to me
