### ISSUE TITLE
System.Text.Json Throms Bad Exceptions...

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#46197]
![image](https://user-images.githubusercontent.com/364896/102533912-4f0e0600-40a6-11eb-922a-b4ab4b2a79ac.png)

See in the Screenshot.

What is the Exception?

**Comment by jogibear9988** [comment]
Was on HaltOnAllExceptions... My bad...

**Comment by GrabYourPitchforks** [comment]
@ericstj I know the issue is closed, but is there any reason the exception text would contain the literal string `"Exception_WasThrown"` rather than the resource string identified by the key _Exception\_WasThrown_?

https://github.com/dotnet/runtime/blob/ffa24bd954dd102da68d42f4d6fbece03e82d1f4/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L2182-L2184

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Private.CoreLib/src/System/Exception.cs#L55

**Comment by ericstj** [comment]
Could be blazor/linker.  I know it does funny things to the resources, though I would have expected the inner exception type to be concatenated see: https://github.com/dotnet/runtime/blob/79c4e417f0a1cdfec007535540e6d563979105f1/src/libraries/Common/src/System/SR.cs#L54-L62

This looks like there was a setting made to use resource keys instead of values, but it's not setting the switch:https://github.com/dotnet/runtime/blob/79c4e417f0a1cdfec007535540e6d563979105f1/src/libraries/Common/src/System/SR.cs#L13

cc @joperezr @eerhardt

**Comment by eerhardt** [comment]
@jogibear9988 - was this running in Blazor WASM? Do you have repro steps to get into this situation?
