### ISSUE TITLE
System.Threading.Channel - Reader - TryPeek / PeekAsync

### ISSUE THREAD

**Issue by boukenka** [dotnet/runtime#46261]
## Background and Motivation

I'm trying to implement the following flow.

Requests are sent to a web server. Only one request can be processed at a time. That is to say that as soon as a request has been able to enter the channel (within a specific period of time), all other requests are returned in failure. Until the processing related to the request (and executed by the background worker) is completed, no further requests can be processed. However, by defining a bounded channel with a capacity of 1, I always get at least two requests to be processed. The one that is taken into account by the '_channel reader_' and the one that was able to register in the '_channel writer_' (see the attached demo zip file)

[ChannelDemo.zip](https://github.com/dotnet/runtime/files/5721510/ChannelDemo.zip)

The solution would be for me to be able to read the request data in the '_channel reader_' without removing it from the queue. Once the request data has been processed by the background service, then the data is removed from the queue.

PS : Multiple producers, one consumer.

## Proposed API

```
ValueTask<T> Channel.Reader.PeekAsync(CancellationToken cancellationToken = default)
bool Channel.Reader.TryPeek(out T result) in conjunction with Channel.Reader.WaitToPeekAsync() ?
IAsyncEnumerable<T> Channel.Reader.PeakAllAsync(CancellationToken cancellationToken = default)
```

## Usage Examples

```
await _consumer.PeekAsync() => item is not removed from the channel reader
..processing of the item by the background service
..end of the processing of the item by the background service
await consumer.ReadAsync() => item is removed from the channel reader
```

## Risks

None ?

**Comment by boukenka** [comment]
There was a discussion here:  https://github.com/dotnet/runtime/issues/31182
@stephentoub Any hope in .NET 6 to get a Peek feature ? It is a show stopper for us.

**Comment by tarekgh** [comment]
I moved it to 6.0 and I'll let @stephentoub comment about it.

**Comment by boukenka** [comment]
@tarekgh Thank you 😄

**Comment by stephentoub** [comment]
CanPeek / TryPeek was approved here:
https://github.com/dotnet/runtime/issues/31362

With that, someone could implement their own async peeking, e.g.
```C#
if (reader.CanPeek)
{
    await reader.WaitToReadAsync(cancellationToken);
    reader.TryPeek(out var item);
    ...
}
```
I don't think we should expose a PeekAsync method, though.  It would need to be robust against multiple consumers (so there would be a loop around the WaitToReadAsync and TryPeek, looping if TryPeek returns false), but with multiple consumers, peeking generally makes little sense, since the moment you've peeked, everything could change out from under you.

I also don't think we should expose a PeakAllAsync.  It would have the same problems mentioned above, and be very expensive at runtime, as it would need to either a) make a copy of all of the data available in the channel or b) synchronize access to the channel while all of the data is being enumerated, and would almost certainly not be pay-for-play.

So, I think this issue should be closed.

**Comment by boukenka** [comment]
Thank you @stephentoub for your comments. 😄 

I will then wait for version 6 of .NET (or a possible preview) to use ```.CanPeek``` and ```.TryPeek```.
