### ISSUE TITLE
System.Drawing.Image.FromStream is not populating PropertyItems

### ISSUE THREAD

**Issue by Socolin** [dotnet/runtime#46411]
Image.FromStream is not populating PropertyItems, while Image.FromFile do that

## Repro

```
        private static void Main()
        {
            var webClient = new WebClient();
            var imageUrl = "https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/Canon_40D.jpg";
            webClient.DownloadFile(imageUrl, "1.jpg");
            var imageFromFile = Image.FromFile("1.jpg");

            Console.WriteLine("From File");
            Console.WriteLine("  w/h: " + imageFromFile.Width + " " + imageFromFile.Height);
            Console.WriteLine("  Properties: " + imageFromFile.PropertyItems.Length);
            Console.WriteLine("  PropertiesIds: " + imageFromFile.PropertyIdList.Length);


            var imageFromStream = Image.FromStream(webClient.OpenRead(imageUrl));
            Console.WriteLine("From File");
            Console.WriteLine("  w/h: " + imageFromStream.Width + " " + imageFromStream.Height);
            Console.WriteLine("  Properties: " + imageFromStream.PropertyItems.Length);
            Console.WriteLine("  PropertiesIds: " + imageFromStream.PropertyIdList.Length);
        }
```

### Output
```
From File
  w/h: 100 68
  Properties: 46
  PropertiesIds: 46
From File
  w/h: 100 68
  Properties: 0
  PropertiesIds: 0
```

### csproj

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Drawing.Common" Version="5.0.0" />
	</ItemGroup>

</Project>
```

### dotnet info

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by safern** [comment]
Thanks, @Socolin. Just as in the other issues you opened this unfortunately seems like a `libgdiplus`, `bug/limitation`. It seems like when we are loading from stream, we depend on the loader that reads the information from the stream. It is created here:  https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/image.c#L2266. 

Then when the image info is read from the stream, `libgdiplus` tries to get the exif information to populate the properties using that loader: https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/jpegcodec.c#L702-L705

However, it seems like the loader has a property that controls if the data is returned or not when calling `dstream_get_exif_buffer`. https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/dstream.c#L192

It seems like that property, defined here: https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/dstream.c#L36 is never set to true, so the condition that controls if the exif buffer is returned or not is always false, so that's why the properties are not preserved when loading from a stream on `Unix`. Would you mind opening an issue on `libgdiplus` instead and linking to this one? 

cc: @akoeplinger
