### ISSUE TITLE
[Report Progress Of a Function] 

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#46441]
I want to create a wrapper that will bind a function to a progress. For example, I would call it like

ProgressBar.ReportProgressFor(MyDefinedFunction())
I want to make a function that will take an user defined function as its parameter and execute it and return the percentage of the user defined function executed in a method property

The code example should be like

var x = ProgressBar.ReportProgressFor(MyDefinedFunction());
and to get the executed percentage we will use x.RemainingPercentage and x.ExecutedPercentage
Please implement it

**Comment by ygra** [comment]
There are a lot of things weird with this proposal in my eyes:

1. Since this is apparently a member method of ProgressBar, this should probably belong to either Windows Forms or WPF.
2. Even then, the way you're calling it could probably only work if your method returns an instance of `IProgress<int>` or `IProgress<IConvertible>`, since you don't pass a method reference, but instead just call the method.
3. There is nothing preventing you right now from doing that yourself, specific for the project you need it in. From what I've gathered from the outside, there's somewhat of a high bar for features to appear in .NET since a proposal has to address thoughts of compatibility and future-proofing, as well as finding out who this would be interesting and useful for.

The very concept of a method that returns arbitrary progress _and_ having that progress be bound to a progress bar is probably very specific to each individual use case. I've used `IProgress<string>` in the past, or even something like `IProgress<(int, string)>` to have something that both moves a ProgressBar forward and also shows status updates in a label. Then there's the question of whether that instance is returned from the method or passed in (the latter might be more common, since it allows you to wire up the progress reporter from the outside before passing it to the method. It would also allow that method to still have a return value (or be asynchronous).

**Comment by jeffschwMSFT** [comment]
@Barshan-Mandal if you have a specific question please provide a repro.  An issue in this repro is not the best place to ask for an implementation.  I am going to close the issue for now, but happy to reopen to answer a specific question.  Please see @ygra's reply for specifics on where to start.
