### ISSUE TITLE
Thread-safe Dispose implementation for Socket and NetworkStream

### ISSUE THREAD

**Issue by jbe2277** [dotnet/runtime#46509]
I did a [research](https://github.com/jbe2277/waf/wiki/Implement-IDisposable) on how to implement the `IDisposable` interface in a thread-safe way. For this I had a look at some .NET BCL classes and saw that different implementations are used.

The following implementations might not be 100% thread-safe:

# Socket class
Actual:
```C#
private int _disposed; // 0 == false, anything else == true
```
Expected the volatile keyword here:
```C#
private volatile int _disposed; // 0 == false, anything else == true
```
See: https://source.dot.net/#System.Net.Sockets/System/Net/Sockets/Socket.cs,74

# NetworkStream class
Actual:
```C#
bool disposed = _disposed;
_disposed = true;
if (!disposed && disposing)
```
Expected usage of Interlocked.CompareExchange:
```C#
if (Interlocked.CompareExchange(ref _disposed, 1, 0) == 0 && disposing) 
{
```
See: https://source.dot.net/#System.Net.Sockets/System/Net/Sockets/NetworkStream.cs,345

**Comment by gfoidl** [comment]
> Expected the volatile keyword here:
> 
> ```cs
> private volatile int _disposed; // 0 == false, anything else == true
> ```

Did you notice https://github.com/dotnet/runtime/blob/5078dd61a81c88dbdd131a77b8148b4dee3803fa/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3552-L3556 ? So no need for volatile (as the compare exchange generates a full memory-barrier).

(I'm not sure what guarantees for thread-safety the NetworkStream-class provides, so can't comment on this).

**Comment by jbe2277** [comment]
@gfoidl That's one of the aspects which I try to find out: 
- When modifying a field only with Interlocked compare exchange is the usage of volatile still required?

---

The `TcpClient` class uses volatile here: 
```C#
private volatile int _disposed;
...
if (Interlocked.CompareExchange(ref _disposed, 1, 0) == 0)
{
```
https://source.dot.net/#System.Net.Sockets/System/Net/Sockets/TCPClient.cs,20 

---

If volatile is not needed then removing the keyword might improve the performance. In this concrete case the performance gain might be insignificant.

What is recommended? Keep `volatile` or remove it?

**Comment by gfoidl** [comment]
> When modifying a field only with Interlocked compare exchange is the usage of volatile still required?

It's not that easy to just say "no".

`volatile` does the following:
* it prevents the compiler(s) from taking optimizations on that field-access (i.e. cache it in a register)
* for reads it generates an _acquire fence_, so it prevents that any read is reordered with any read or write that follows in program order
* for writes it generates an _release fence_, so it prevents that any read or write that preceedes in program order will be reordered with any write that follows

Note: this is about visibility, and has per se nothing to do with atomicity.
Note2: `volatile` can be substituted by explicit `Volatile.Read`s and `Volatile.Write`s -- the have the same effect (I prefer the latter, as it makes the code more explicit).

`Interlocked.CompareExchange` besides being an atomic operation generates a [full memory barrier](https://preshing.com/20120710/memory-barriers-are-like-source-control-operations/), i.e. has stronger guarantees on memory-ordering than volatile has.

The full memory barrier has a bit more cost than the half-fences from volatile (as it's kind of "a combination of release and acquire fence"), so if atomicity is already given (i.e. the size of the (properly aligned) memory access <= word-size of the cpu, e.g. `int` on x86, `long` on x64) then one can use volatile reads and writes.

Technically -- in easy words -- the cpu performs these kind of guarantees by [flushing it's buffers](https://stackoverflow.com/a/51295584/347870).

So coming back the cited question:
These fences need to be "paired" in order to do a synchronisation. I like the following visualization for this:
![](https://preshing.com/images/two-cones-fences.png)
(from [Acquire and Release Fences](https://preshing.com/20130922/acquire-and-release-fences/))

---

For the TcpClient -- or in general: for each type where the dispose-pattern must be thread-safe -- I'd write the code as
```c#
private int _disposed; // 0 == false, anything else == true
...
private bool Disposed => Volatile.Read(ref _disposed) != 0;
...
if (Interlocked.CompareExchange(ref _disposed, 1, 0) == 0)
{
```
Here a volatile read (acquire fence) is needed in order to synchronize with a potential write from the interlocked operation (full fence). Otherwise (in theory) the read in `_disposed != 0` could be cached and a change won't be recognized.
I wouldn't use `volatile int _disposed` here, as the only write is done with `Interlocked.CompareExchange` and in order to make the intention -- the volatile read -- explicit.

From your top-post and Socket https://github.com/dotnet/runtime/blob/5078dd61a81c88dbdd131a77b8148b4dee3803fa/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3453 IMHO the same should be done.

On cpus with a _strong memory model_ (kind like "implicit acquire/release") like x86 this won't be a problem, but it may be a problem on cpus with _weak memory model_ (memory operations can be reordered as long the behavior of a isolated-single-thread execution won't be changed).

For memory models also see
* [C# - The C# Memory Model in Theory and Practice](https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/december/csharp-the-csharp-memory-model-in-theory-and-practice)
* [C# - The C# Memory Model in Theory and Practice, Part 2](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2)
* [Weak vs. Strong Memory Models](https://preshing.com/20120930/weak-vs-strong-memory-models/)

**Comment by weltkante** [comment]
> On cpus with a strong memory model (kind like "implicit acquire/release") like x86 this won't be a problem

What about caches? Won't even on a strong memory model the possibility exist that the variable in on the CPU cache and return the wrong value if you don't use `Volatile.Read` or a volatile variable modifier?

**Comment by stephentoub** [comment]
For Socket, as @gfoidl noted the one place that it's mutated already uses Interlocked.CompareExchange.  The field is being passed by ref there, at which point the volatility of the field is ignored, so there's no performance impact to that CompareExchange usage to the field being volatile.  The only other place that _disposed field is used is it being returned from the internal Disposed property.  The majority of the Disposed accesses are just of the form `if (Disposed) throw ...`, so there's little benefit to volatile being used.  However, in a couple of places, after Disposed is accessed some other field is read, and making _disposed volatile means those subsequent reads can't be reordered to actually come before the read of disposed; since Dispose does change the value of various fields after setting _disposed, it's possible there could be a functional impact to removing the volatile.  The "right" answer is probably to remove the volatile from the field and then audit all uses of Disposed and only use `Volatile.Read(ref _disposed)` in the places where it truly matters, but the cost/benefit of doing so isn't worth it.  On x86/x64, the volatile actually disappears when compiled to assembly, so it's only on an architecture with a weaker memory model like ARM where an actual memory barrier would be inserted, and even then, looking at all the places Disposed is used, I'm not seeing any usage on a hot path where the impact would be at all measurable.

For NetworkStream, the volatile on _disposed looks to be pretty useless.  The only benefit it would really have is ensuring that some of the later writes in the method (such as to _readable and _writeable) don't end up being visible before the write to _disposed, but _disposed isn't viewable anywhere outside of the Dispose method, so I don't think there's any observable impact to such a reordering.  If we really cared to be guarantee and be explicit that NetworkStream.Dispose could be called concurrently from multiple threads, we could remove the volatile from _disposed, change it to be an int, and use Interlocked.CompareExchange to read/set the flag in Dispose to ensure that only one thread ever calls Close on the Socket. But, in practice the implementation looks like it will already be safe for such usage, as the Dispose method really just ends up calling to a few Socket methods that will work correctly if used concurrently.  And on top of that, I don't personally see a lot of benefit in doing so.  At the same time, one additional interlocked operation in NetworkStream.Dispose is not going to be measurable, so if someone really wanted to be able to make the guarantee that NetworkStream.Dispose was thread-safe with concurrent calls to itself, we could.
