### ISSUE TITLE
[System.Net.Http.Json] JsonSerializerOptions

### ISSUE THREAD

**Issue by drma-dev** [dotnet/runtime#46514]
I have the following code that is sending a json with attributes in the CamelCase format, but I am not able to read in my API.

```c#
public async static Task<T> Post<T>(this HttpClient http, string requestUri, T obj) where T : class
{
    var response = await http.PostAsJsonAsync(http.BaseApi() + requestUri, obj);

    return await response.ReturnResponse<T>();
}
```

But when I start the options, without changing any default values, my API can read the json correctly.

```c#
public async static Task<T> Post<T>(this HttpClient http, string requestUri, T obj) where T : class
{
    var response = await http.PostAsJsonAsync(http.BaseApi() + requestUri, obj, new JsonSerializerOptions());

    return await response.ReturnResponse<T>();
}
```

Shouldn't the code already apply the default values?

**Comment by campersau** [comment]
The default for these JSON methods is to use `camelCase` and not `PascalCase` / `CamelCase`.
Here are the corresponding code references:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs#L22

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerDefaults.cs#L18-L24

According to the design doc this was intentional: https://github.com/dotnet/designs/blob/main/accepted/2020/json-http-extensions/json-http-extensions.md#default-serialization-options

**Comment by karelz** [comment]
cc @Jozkee

**Comment by karelz** [comment]
@eiriktsarpalis @layomia @steveharter can you please help triage this issue? Thanks!

**Comment by eiriktsarpalis** [comment]
Agree with @campersau that seems to be by-design. The workaround as provided in the OP is the recommended solution (but perhaps consider not allocating one options instance per request). I'm going to close this issue.
