### ISSUE TITLE
runtime pipeline(s) jobs can be based on top of different commits

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#46596]
These JIT tests are failing on a few legs of #46559.

See the logs here:

https://dev.azure.com/dnceng/public/_build/results?buildId=937878&view=logs&j=40d27226-09bf-5dd6-600e-719dc91d57e5&t=81c7ae10-7832-5173-b7fe-92ee582028ba&l=33

https://helix.dot.net/api/2019-06-17/jobs/a1bb7d7e-fd66-461e-a17d-2b5a93083dfc/workitems/JIT.Regression/console

```
+ dotnet /home/helixbot/work/A7A908B8/p/xunit/xunit.console.dll JIT/Regression/JIT.Regression.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.Regression
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 5.0.0)
  Discovering: JIT.Regression.XUnitWrapper
  Discovered:  JIT.Regression.XUnitWrapper
  Starting:    JIT.Regression.XUnitWrapper
    JIT/Regression/JitBlue/Runtime_45090/Runtime_45090/Runtime_45090.sh [FAIL]
      Managed assembly not found: No such file or directory
      
      Return code:      1
      Raw output file:      /home/helixbot/work/A7A908B8/w/AE9109D9/e/JIT/Regression/Reports/JIT.Regression/JitBlue/Runtime_45090/Runtime_45090/Runtime_45090.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/A7A908B8/p/corerun Runtime_45090.dll ''
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/home/helixbot/work/A7A908B8/p
      > /home/helixbot/work/A7A908B8/w/AE9109D9/e/JIT/Regression/JitBlue/Runtime_45090/Runtime_45090/Runtime_45090.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Regression._JitBlue_Runtime_45090_Runtime_45090_Runtime_45090_._JitBlue_Runtime_45090_Runtime_45090_Runtime_45090_sh()
      Output:
        Managed assembly not found: No such file or directory
        
        Return code:      1
        Raw output file:      /home/helixbot/work/A7A908B8/w/AE9109D9/e/JIT/Regression/Reports/JIT.Regression/JitBlue/Runtime_45090/Runtime_45090/Runtime_45090.output.txt
        Raw output:
        BEGIN EXECUTION
        /home/helixbot/work/A7A908B8/p/corerun Runtime_45090.dll ''
        Expected: 100
        Actual: 255
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/home/helixbot/work/A7A908B8/p
        > /home/helixbot/work/A7A908B8/w/AE9109D9/e/JIT/Regression/JitBlue/Runtime_45090/Runtime_45090/Runtime_45090.sh
  Finished:    JIT.Regression.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Regression.XUnitWrapper  Total: 291, Errors: 0, Failed: 1, Skipped: 0, Time: 64.351s
```

**Comment by jkotas** [comment]
cc @echesakovMSFT

**Comment by echesakovMSFT** [comment]
The failure is due to the following facts:
1) *"Runtime Tests Run"* jobs that create test runner scripts and XUnit test wrappers is based on top of my commit 8b8a3fca1ace915d13c221d0fb3a794da2eef823 that introduces the test
2) *"CoreCLR Common Pri0 Test Build"* job that build test assemblies is based on top of earlier commit ac8e1225eb71eb5975f1e65368497c36ec81f1a2 that doesn't have knoweldge about the test
3) During test run artifacts are downloaded from the latter job and the test runner scripts fail due to the missing corresponding test assembly

I was surprised to find that we don't use checkout bundles anymore that were introduced to specifically avoid such issues.

**Comment by jkoritzinsky** [comment]
cc: @safern @ViktorHofer

**Comment by echesakovMSFT** [comment]
Change the issue area and title

**Comment by safern** [comment]
I'm assigning myself as I removed the checkout bundle and already was investigating this. I will put up a PR to bring the checkout bundle back for PRs and open an issue on dnceng to follow up with AzDo. FYI: @MattGal

**Comment by safern** [comment]
> I was surprised to find that we don't use checkout bundles anymore that were introduced to specifically avoid such issues.

Yeah, we reached out to AzDo, and they were supposed to have fixed it, on my PR to remove the checkout bundle, we did a few tests and it seemed like it worked fine but it seems like we hit a cache in the GH refs and that's why the test (introducing a commit to documentation in between two legs started) passed.

**Comment by safern** [comment]
FYI: Based on this conversation: https://github.com/dotnet/runtime/pull/47003#issuecomment-760420624 we're going to remove the checkout bundle from PRs again as the issue should be fixed. If for any reason you see it is not, please let me know and I will look at it.
