### ISSUE TITLE
Issue in System.Globalization

### ISSUE THREAD

**Issue by arunendapally** [dotnet/runtime#46591]
I have observed that I get different results in .NET 5 whereas .NET Framework 4.61 and .NET Core 3.1 are working as expected, If you run the below code in all the three frameworks you would see the output which I added below.

```
 using System;

using System.Globalization;

 

public class Program

{

public static void Main()

{

var cal = new CultureInfo("en-US");

var val = -1234.56M;

Console.WriteLine(val.ToString("C2", cal));        

}

}
```

Output:
.NET Framework: ($1,234.56)
.NET Core: ($1,234.56)
.NET 5:  -$1,234.56

**Comment by tarekgh** [comment]
@arunendapally which culture you are using on your environment? I mean print out `CultureInfo.CurrentCulture` value.

In .NET 5.0 we switched to use ICU library which is implementing the Unicode standard and using it is standard data `CLDR`. When you send the culture name used in your environment I can try to confirm that in CLDR. mean while I encourage you to look at the doc https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu for more information which also specify how to switch back to the old behavior if needed (which we don't recommend to ensure consistency across OS's).

**Comment by arunendapally** [comment]
I am using 5.0, I have more info on why this is happening, run the below code in https://dotnetfiddle.net/ in all the three compilers/frameworks and you will see the below output

```
using System;
using System.Globalization;
                   
public class Program
{
    public static void Main()
    {
        var cal = new CultureInfo("en-US");
        Console.WriteLine(cal.NumberFormat.CurrencyNegativePattern);
    }
}
```

Output:

.NET Framework 4.7: 0

Roslyn 3.8: 0

.NET 5: 1

**Comment by arunendapally** [comment]
tried with `var cal = CultureInfo.GetCultureInfo("en-US");` still no difference. Yes, I am on windows 10

**Comment by tarekgh** [comment]
@arunendapally I have investigated this more to understand what is going on. 

The behavior here is the difference when using `ICU` which we do in 5.0 (we use it on Linux/MacOS for all net core versions too) and when using `NLS` which we use it on Windows only with net core versions up to and including 3.1. Also, NLS is used with the Full Framework. 

The ICU behavior looks more correct though according to Unicode CLDR data. you may look at how it is defined there https://github.com/unicode-org/icu/blob/dea5448cb199a627c3a758394bf97ba09067ca50/icu4c/source/data/locales/en.txt#L23.

When using https://dotnetfiddle.net/, with .NET 5.0, I am seeing it is using `Linux 5.4.0-1034-azure #35~18.04.1-Ubuntu SMP Thu Dec 10 09:13:52 UTC 2020` (you can get this value by printing `RuntimeInformation.OSDescription`). That means you are running on Linux machine which is using ICU.

When using `Roslyn 3.8` option, you will be actually running on the Full Framework:

```
.NET Framework 4.7.3690.0
Microsoft Windows 10.0.17763 
```

One last note here, if you run on Windows machine with exact same code you have which is using `var cal = new CultureInfo("en-US")`, you will still get the old result `($1,234.56)`. The reason is you opted in to use the user overrides from the machine. But if use `var cal = CultureInfo.GetCultureInfo("en-US")` you will get the new result `-$1,234.56` which is the format defined by Unicode and that is because will use ICU format and not the user override. 

By that, I think everything is explained now. You can look at the doc https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu to learn more about the change using ICU. The doc has the info how you can switch back to NLS behavior if you need to do so. 

I am closing the issue, but feel free to send any more follow up question we can help you with.

**Comment by arunendapally** [comment]
I have recorded what I was trying to explain, please check and let me know what the problem is.

https://user-images.githubusercontent.com/7790461/103737399-2da29900-5018-11eb-9d3d-ec925a22a07e.mp4

**Comment by tarekgh** [comment]
@arunendapally your recording is matching what I have explained before. Here is more clarification: 

- When using netcoreapp3.1, the framework will be using `NLS` for globalization. `NLS` data is using the `($1,234.56)` for the negative currency formatting. 
- When using net5.0, the framework at that time will be using `ICU` for globalization which will have `-$1,234.56` for the negative currency formatting. by the way, I assume your current culture `CultureInfo.CurrentCulture` is not `en-US` on your environment.
- When doing `cal.NumberFormat.CurrencyNegativePattern = 0`, this basically override the default negative currency settings on the created instance of the CutureInfo by the format `($1,234.56)`.

Let me know if this still unclear.
