### ISSUE TITLE
Question about memory barriers in .NET

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#46661]
In .NET, there are some APIs that explicitly mention the use of memory barriers in their implementation (`Volatile`, `Interlocked`, `Thread.MemoryBarrier`, etc.). But then there are other APIs (such as `ThreadPool.QueueUserWorkItem`, `Task.Run`, and `Threading.Timer`) where it's generally assumed that there is an implicit memory barrier, but the API doesn't explicitly state this. For example:

```c#
private int _i;

public void Method()
{
    _i = 1;
    var timer = new Timer(_ => Console.WriteLine(_i), null, 0, -1); //Guaranteed to print 1?
}
```

More generally, is there somehow a way to tell which APIs guarantee a memory barrier and which don't? I have a hard time blindly _trusting_ without strong API guarantees to fall back on, especially knowing that implementations are allowed change over time.

**Comment by stephentoub** [comment]
In order to successfully achieve the defined purpose of the API, any method (Timer's ctor, ThreadPool.QueueUserWorkItem, Task.Run, etc.) which queues work necessarily incurs the appropriate barriers to ensure that the queued work can read any state set by the thread doing the queueing prior to the queueing.  How it achieves that is an implementation detail, but that it achieves it is just necessary for the method to be functionally correct.

> //Guaranteed to print 1?

Yes (unless some other code changes _i to something else before the callback actually runs).

**Comment by WizardBrony** [comment]
@stephentoub Okay, I can accept that. Does this rationale also apply to all concurrent APIs? For example:

```c#
private class C
{
    public int I;
}

private readonly ConcurrentDictionary<int, C> _dictionary = new ConcurrentDictionary<int, C>();

public void Thread1()
{
    var c = new C();
    c.I = 1;

    // No memory barrier

    _dictionary.TryAdd(0, c);
}

public void Thread2()
{
    if (_dictionary.TryGetValue(0, out var c))
        Console.WriteLine(c.I); // Guaranteed to print 1?
}
```

**Comment by stephentoub** [comment]
Yes

**Comment by WizardBrony** [comment]
@stephentoub Thank you very much for your time.

**Comment by WizardBrony** [comment]
@stephentoub I'm really sorry to bring this up again, but if you could calm my paranoia about one other API I'd really appreciate it. Is `CancellationTokenSource.Cancel` guaranteed to incur a barrier such that all state changes are visible prior to the request for cancellation?

**Comment by stephentoub** [comment]
Yes.
