### ISSUE TITLE
Double.ToString regression from .NET Framework

### ISSUE THREAD

**Issue by Rand-Random** [dotnet/runtime#46670]
### Description

.NET 5.0 produces different result on double.ToString() than .NET Framework.
![image](https://user-images.githubusercontent.com/9868626/103895223-58602080-50f0-11eb-919e-317883df60cd.png)
Source: https://stackoverflow.com/questions/65478282

### Configuration

.NET 5.0 vs .NET 4.8

### Regression?

Yes, code implies that is was desired to have the same result as .NET 4.8.

As stated at the comment here:

https://github.com/dotnet/runtime/blob/81b9558199454adc6cc2a0e34cc64ebeb8f754c6/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L253-L261

https://github.com/dotnet/runtime/blob/81b9558199454adc6cc2a0e34cc64ebeb8f754c6/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L535-L540

### Other information

Error was reported here:
https://stackoverflow.com/questions/65478282

I am posting my comment from StackOverflow here, to show where the error maybe

Seems like a bug to me this line https://github.com/dotnet/runtime/blob/c142f162854185ba45f0fab678f8b28d1add3968/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L532 doesn't return '\0' so it doesn't enter this if https://github.com/dotnet/runtime/blob/c142f162854185ba45f0fab678f8b28d1add3968/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L535

**Comment by huoyaoyuan** [comment]
This should by probably caused by the FP precision update in 3.0.

**Comment by Joe4evr** [comment]
For reference: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by tannergooding** [comment]
This is by design. The comment is in relation to "custom numeric format strings": https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings

While the sample is just using `ToString()` which represents a "standard numeric format string": https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings

The blog post shared by Joe4evr above gives more details on the breaking change and why it exists.

**Comment by Rand-Random** [comment]
@tannergooding 
Just want to point out that the MSDN documentation doesn't reflect this behaviour and still says 15 digits is the default, also as I shared, the code doesn't reflect this "design" as-well since the comments that I have shared still talk as if it is desired to have backwards compatibility.

**Comment by tannergooding** [comment]
> Just want to point out that the MSDN documentation doesn't reflect this behaviour and still says 15 digits is the default

There are a range of conceptual docs that were missed when the breaking change first went in. I've been updating them as they are found for the most part.

> the code doesn't reflect this "design" as-well since the comments that I have shared still talk as if it is desired to have backwards compatibility.

The comments in question explicitly call out the back-compat is for custom format strings/specifiers.

**Comment by Rand-Random** [comment]
@tannergooding 
Can you share an example in what case this if statement is true

https://github.com/dotnet/runtime/blob/81b9558199454adc6cc2a0e34cc64ebeb8f754c6/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L535-L540

Tried a couple "custom format strings/specifiers" but with no luck.

**Comment by tannergooding** [comment]
The difference is that [standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) are things like `C`, `D, `E`, `G`, `N`, `P`, `R`, or `X` followed by up to 2 digits; so `"F4"` or `"G99"`, for example.

While [custom numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) are allowed to be more complex and use `0`, `#`, `.`, `,`, `%`, and others to specify exactly how you want the string to display. For example, `0.0e+00` specifies that you want an integral digit, or `0` if none exists, followed by a decimal point, followed by a single fractional digit, if one exists, followed by the exponential notation indicating the value's scale.

The former (standard numeric format strings) will respect precisions above 15 (up to 99) and will follow the correct IEEE 754 semantics.
The latter (custom numeric format strings) should be largely backwards compatible and only respects up to 15 digits of precision. In order to support more, there would need to be more extensive changes to the formatting logic and pre-parse the format specifier.
