### ISSUE TITLE
Difference in behaviour between `ICorProfilerInfo::SetILFunctionBody` and `ICorProfilerFunctionControl::SetILFunctionBody`

### ISSUE THREAD

**Issue by robertpi** [dotnet/runtime#46671]
### Description

A difference in behaviour between `ICorProfilerInfo::SetILFunctionBody` and `ICorProfilerFunctionControl::SetILFunctionBody` exists. Changes written by `ICorProfilerInfo::SetILFunctionBody` are visible to `ICorProfilerInfo::GetILFunctionBody` where as changes written by `ICorProfilerFunctionControl::SetILFunctionBody` are not visible to `ICorProfilerInfo::GetILFunctionBody` (`ICorProfilerFunctionControl` has no equivalent of `GetILFunctionBody`).

To demonstrate this I have create a repo available in this repository: https://github.com/robertpi/ProfilerApiBug

### Configuration

* .NET 5.0
* Windows 10 Pro
* x64

I do not think this bug is specific to this configuration.
 
### Regression?

I do not think this is a regression, I think the same issue exists in older version.

### Other information

This bug may seem fairly harmless, but to us it's quite annoying. We hope to have an architecture when several different types of profiling may or may not be run on a method. We'd therefore like to apply the profiling injection in different places in our code, but if we go via rejit using  `ICorProfilerFunctionControl::SetILFunctionBody` it means only the last set of changes is applied.

**Comment by davmason** [comment]
Hi @robertpi,

Thanks for reaching out to us. What you are seeing I would not classify as a bug, but rather that you are trying to use two independent approaches for IL modification at the same time. SetILFunctionBody was introduced long before ReJIT and allows the profiler to modify IL only before the method is jitted (any changes will be ignored after jitting takes place) and ReJIT was introduced later to allow the profiler to modify IL at any point in the process lifetime. They are not necessarily intended to be used interchangeably, we guarantee that the runtime will behave in a sane manner but don't guarantee that you can do things like call GetILFunctionBody to get ReJITted IL.

This issue can serve as a feature request for an equivalent API to GetILFunctionBody for ReJIT. Just to set expectations we are already most of the way through planning for .Net 6.0, and 7.0 would be the earliest this feature would appear (it could likely take even longer), and it would not appear in any previous versions of .Net due to our servicing policy.

My advice would be to only use RequestReJIT and stop calling SetILFunctionBody - it is perfectly fine to call RequestReJIT before the function has been jitted and it will behave the same as calling SetILFunctionBody (other than being able to call GetILFunctionBody). Then you can cache the most recent IL inside your profiler and use that as the basis for the next edit.

If you cannot stop using SetILFunctionBody, it should not be too much effort to use the same caching approach but modified to synchronize between RequestReJIT and SetILFunctionBody so you can always request the active IL of a function.

**Comment by robertpi** [comment]
Hi @davmason ,

Thanks for the detailed explanation. 

A GetILFunctionBody for ReJIT would be useful, but ultimately it would be more useful to find a way to relax the restriction that means only one profiler can be attached to an application at once - it's the reason I came across this behaviour. I know this is a much bigger ask, let me explain why I think this would be useful.

Recent years have seen APM agents using dynamic instrumentation rise in popularity in the .NET world and on other platforms. To make the developer's life easier, many APMs use dynamic instrumentation, they automatically hook instrumentation points into the code, so the developer is not required to make changes to the code to support instrumentation. I believe agents, not just APM agents, and dynamic instrumentation will become more popular in the future.

On the .NET platform two APM vendors have chosen to use the .NET Profiling API to implement dynamic instrumentation. It can be seen that [DataDog dotnet APM agent](https://github.com/DataDog/dd-trace-dotnet) and [New Relic dotnet APM agent](https://github.com/newrelic/newrelic-dotnet-agent/) both use the profiling API.

This means that DataDog and New Relic cannot easily be used together, because an application can only have one profiler attached. While this isn't normally an issue, as a client is likely to only want to use one type of APM vendor, other uses of agents and dynamic instrumentation are likely to become available over time meaning that this will be an issue in the future.

For example, we at [Sqreen](https://www.sqreen.com/) are working on a security agent that will use dynamic instrumentation. We would like our agent to be able to work either DataDog or New Relic as we feel this will be a common customer requirement. I have PoC way to do this, but this particular behaviour from the profiling API is one thing that makes it more difficult than I would like.

To be able to have reasonable timelines for releasing our agents, we're going to have to make do with a work around, however it would be nice to see us moving towards a world where the work around isn't required. I also believe a more flexible appoarch to dynamic instrumentation would be benifical for the .NET platform in general. This issue has been experienced on other platforms. Issues created by several agents trying to dynamically instrument python code led to the creation of [wrapt](https://pypi.org/project/wrapt/), which coordinates changes made by several agents.

As quick aside: 

 - I wouldn't respectfully disagree about mixing ReJIT and different versions of SetILFunctionBody, my tests show that ICorProfilerInfo::SetILFunctionBody can be used from inside a ReJIT requests does change the method definition. Perhaps, RequestRevert doesn't work if ICorProfilerInfo::SetILFunctionBody is used? I have not tested this yet.
 - I find it hard to understand why ICorProfilerFunctionControl is only passed to GetReJITParameters and not ReJITCompilationStarted, it would be great to have some docs around that

**Comment by davmason** [comment]
For using multiple IL rewriting profilers, Microsoft provides CLRIE - https://github.com/microsoft/CLRInstrumentationEngine. It registers itself as the profiler and then handles synchronization across profilers.

>  my tests show that ICorProfilerInfo::SetILFunctionBody can be used from inside a ReJIT requests does change the method definition.

The story here is a bit complicated. When the ReJIT APIs were introduced, the intention was that ICorProfilerFunctionControl would be the only way to set the IL for a ReJIT request, but a bug in the implementation made it so you could call SetILFunctionBody and it would also work. In .Net Core when we did the tiered compilation work it made SetILFunctionBody no longer work to set the IL inside GetReJITParameters, unintentionally breaking all the profilers who had a dependency on SetILFunctionBody working with ReJIT. So we made a fix specifically to allow it again, even though it was never the original intention. So it ended up in this odd place where it was never intended to work that way, but does work because we don't want to break profilers.

> I find it hard to understand why ICorProfilerFunctionControl is only passed to GetReJITParameters and not ReJITCompilationStarted, it would be great to have some docs around that

The way that ReJIT works conceptually is:

1. The profiler informs the runtime that it would like a method ReJITted with RequestReJIT
2. At some later point the runtime asks the profiler for the new IL, code maps, and codegen flags with GetReJITParameters. ICorProfilerFunctionControl is the interface that the runtime provides so the profiler can specify the new IL, code maps, and flags.
3. At some even later point when code tries to call in to the ReJITted method the runtime will actually do the ReJIT and replace the method body, and inform the profiler that the ReJIT has occurred with ReJITCompilationStarted

ICorProfilerFunctionControl is not passed to ReJITCompilationStarted because when the ReJIT begins to compile the IL, code maps, and codegen flags are already set so there is no need to request further data from the profiler. If the profiler wants to request another ReJIT, it is free to call RequestReJIT again with new IL.

**Comment by robertpi** [comment]
Thanks @davmason ! I did not know about CLRIE and this seems to be exactly what I need. I'm therefore closing this.
