### ISSUE TITLE
[System.Net.Http.Json] HttpClient not always calling HttpContent.LoadIntoBufferAsync

### ISSUE THREAD

**Issue by danielgerlag** [dotnet/runtime#46683]
### Description

When doing a Post with `HttpClient` and using `JsonContent`, I noticed that sometimes an empty body is posted.  When I drilled into it, I found that if I explicitly call `LoadIntoBufferAsync()` on the HttpContent then the issue goes away and everything works fine.

```c#
var content = JsonContent.Create(data);
await content.LoadIntoBufferAsync();  //without this, it doesn't always work
await _httpClient.PostAsync(item.CallBack, content);
```

### Configuration

.net core 3.1
System.Net.Http.Json, Version=5.0.0.0

Hosted on Azure App Service, with AppInsights enabled

**Comment by karelz** [comment]
@eiriktsarpalis @layomia @steveharter can you please help triage this issue? Thanks!

**Comment by eiriktsarpalis** [comment]
That's surprising, since on quick inspection it seems like `HttpClient` will also call `LoadIntoBufferAsync` eventually. Could you provide a minimal reproduction that demonstrates the issue?

> .net core 3.1
> System.Net.Http.Json, Version=5.0.0.0

I can't help noticing that you're running a v5 library on .NET Core 3.1. I believe `JsonContent` was added in 5 so I wouldn't be too surprised if it depended on implementation details of the v5 HttpClient.

**Comment by danielgerlag** [comment]
It's not deterministic, bigger payloads are more likely to be sent as empty, so I suspect the `LoadIntoBufferAsync` is not being awaited somewhere, causing a race condition.

**Comment by eiriktsarpalis** [comment]
Are you able to verify that the same behaviour reproduces on .NET 5?

**Comment by karelz** [comment]
No response for a week, closing. Feel free to reopen once there is more info.
