### ISSUE TITLE
TcpClient(hostName, port) constructor not handling IPv4-Mapped Addresses correctly

### ISSUE THREAD

**Issue by agowa338** [dotnet/runtime#46724]
The System.Net.Sockets.TcpClient constructor fails to handle IPv4-Mapped Addresses correctly.
However the Connect function does.

I've tried this with Powershell 7.0.1 and .Net Core 3.1.4

Not working example:
```
PS C:\> $tcpConnection = [System.Net.Sockets.TcpClient]::new("::ffff:c163:9050", 443)
MethodInvocationException: Exception calling ".ctor" with "2" argument(s): "The requested address is not valid in its context. [::ffff:193.99.144.80]:443"
```
Working example:
```
PS C:\> $tcpConnection = [System.Net.Sockets.TcpClient]::new()
PS C:\> $tcpConnection.Connect("::ffff:c163:9050", 443)
PS C:\> $tcpConnection.Connected
True
```
Version information:
```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> [Environment]::Version

Major  Minor  Build  Revision
-----  -----  -----  --------
3      1      4      -1
```

Related RFC: https://tools.ietf.org/html/rfc4038#section-4.2

References: https://github.com/microsoft/dotnet/issues/1214

**Comment by karelz** [comment]
Reproduced on both .NET Core 3.1 and .NET 5:
```c#
        TcpClient c1 = new TcpClient();
        c1.Connect("::ffff:c163:9050", 443);
        Console.WriteLine(c1.Connected); // True
        TcpClient c2 = new TcpClient("::ffff:c163:9050", 443);
        // System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10049): The requested address is not valid in its context. [::ffff:193.99.144.80]:443
```

**Comment by antonfirsov** [comment]
Since dotnet/corefx#30036 the parameterless constructor is triggering `InitializeClientSocket()` that will pre-create a dual-stack socket for the connection:

https://github.com/dotnet/runtime/blob/c2e098b14a9a352fc9a2afad59060d6097f89418/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L26

https://github.com/dotnet/runtime/blob/c2e098b14a9a352fc9a2afad59060d6097f89418/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L432-L440

The `TcpClient(string, int)` constructor does not call that method, and will eventually attempt the connection using a non-DualMode socket:

https://github.com/dotnet/runtime/blob/c2e098b14a9a352fc9a2afad59060d6097f89418/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L171-L174

I think this is a legacy logic inherited from [the times before dual-stack sockets existed](https://devblogs.microsoft.com/aspnet/dual-mode-sockets-never-create-an-ipv4-socket-again/) in .NET. Replacing it with a call to `InitializeClientSocket()` seems to be a trivial fix.

@agowa338 are you interested in a PR?

**Comment by jaymin93** [comment]
@antonfirsov just to understand your last comment better , InitializeClientSocket() method call addition will fix out the issue correct ?

**Comment by antonfirsov** [comment]
Setting `_family = AddressFamily.Unknown`, and calling `InitializeClientSocket()` in the constructor should fix the bug.
After that, the following branch might become dead, if yes it should be removed:
https://github.com/dotnet/runtime/blob/c2e098b14a9a352fc9a2afad59060d6097f89418/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L166

We also need a new test case to prove the fix and establish functional coverage.

--------
However:
Taking a second look, I would do a more radical simplification, and drop all the logic from `TcpClient.Connect(string, int)`, so it  delegates into `Socket.Connect(string, int)` instead. @wfurt is there any reason you didn't do it in dotnet/corefx#30036? Do you see any chance we'll break something with such a change?

**Comment by wfurt** [comment]
I think we can look at it. I'm not sure what the behavior would be is OS does not support DualMode sockets. It seems like the current logic would still work but I'm not sure what the behavior would be  with Socket.Connect(). It seems like we would always connect to only one address family. 
On broader thought, I'm wondering if Pv4-Mapped should be really treated as IPv4 e.g. use IPv4 socket instead of DualMode.

**Comment by agowa338** [comment]
@wfurt: I'd expect behavior according to the RFC https://tools.ietf.org/html/rfc4038#section-4.2 

I'm interested in this feature as I do not want to handle dual stack and just use the mapped addresses instead of the IPv4 ones, so that my applications can be fully IPv6 only while still being able to reach github and twitter...

**Comment by antonfirsov** [comment]
@agowa338 some context on @wfurt's concerns:
While .NET socket behavior tends to (silently) shift towards Dual Stack everywhere, recently we discovered that it may lead to unexpected issues when used together with certain VPN-like solutions (see #44686).

Regardless, we need to have a preference for the sockets we use in AddressFamily-agnostic API-s, and stick to it for consistency. Currently our [most visible Socket constructor](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.-ctor?view=net-5.0#System_Net_Sockets_Socket__ctor_System_Net_Sockets_SocketType_System_Net_Sockets_ProtocolType_) is creating Dual Stack sockets in most environments, so we should prefer it everywhere IMO. If we are concerned of potential dual-stack issues, we should shift our preference globally, not just in one particular method.

**Comment by agowa338** [comment]
@antonfirsov Well, these workaround than provide issues to others. I'd suggest to follow the RFC.
We frequently encounter issues where applications try to be smart instead of just leaving that task to the admin. The administrator can than decide to disable IPv4 completely, to add a firewall rule, or to do whatever else. But what is needed for that to work is software that follows the RFC.

**Comment by karelz** [comment]
@agowa338 I am not sure which part of RFC you have in mind. Can you please be specific? Thanks!

**Comment by wfurt** [comment]
The RFC really talks what should happen on the wire. There is no doubt that it should go out as IPv4. The trickery in in TcpClient it self. I was wondering if we should do something similar to https://github.com/dotnet/corefx/pull/37194/files e.g. treat v4 mapped address as IPv4 instead of using dual-mode socket. 

Since that (and any other clean-up) is unrelated to the reported issue I put up PR to fix this issue.

**Comment by agowa338** [comment]
@wfurt: I thought the RFC is clear on that, look at the "stack" in section 4.2, the application (and the libraries should be IPv6).
E.g. The application doesn't know that IPv4 exists nor that it is a special address. The "magic" hapens when the TCP layer (aka. the library that crafts the tcp package) adds the IP layer. It will pick the IPv4 layer when sending the package. But from the application side it will be IPv6 (with the mapped address). Allowing application developers to disregard the existence of IPv4.
