### ISSUE TITLE
System.InvalidOperationException : The word passed to the normalize interface cannot be normalized.

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#46801]
Job : [runtime-libraries-coreclr outerloop 20210110.2](https://dev.azure.com/dnceng/public/_build/results?buildId=944231&view=ms.vss-test-web.build-test-results-tab&runId=29799020&resultId=102190&paneView=debug)

Failed test : `SampleSynthesisTests.SpeechRecognizerTests.SpeechRecognizer`

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

**Error message:**
```
System.InvalidOperationException : The word passed to the normalize interface cannot be normalized.
```

**Stack trace:**
```
   at System.Speech.Recognition.RecognizerBase.Initialize(SapiRecognizer recognizer, Boolean inproc) in /_/src/libraries/System.Speech/src/Recognition/RecognizerBase.cs:line 455
   at System.Speech.Recognition.SpeechRecognizer.get_RecoBase() in /_/src/libraries/System.Speech/src/Recognition/SpeechRecognizer.cs:line 451
   at SampleSynthesisTests.SpeechRecognizerTests.SpeechRecognizer() in /_/src/libraries/System.Speech/tests/SpeechRecognizerTests.cs:line 39
```

**Comment by BruceForstall** [comment]
@danmosemsft can you triage?

**Comment by danmosemsft** [comment]
I think our enum of errors is disjoint. If I count the offset in our error codes, it's 120, then go to sperror.h, it seems like

/*** SPERR_AUDIO_NOT_FOUND                                 0x80045078    -2147200904
*   No audio device is installed.    
*/
#define SPERR_AUDIO_NOT_FOUND                              MAKE_SAPI_ERROR(0x078)

I need to double check.

**Comment by danmosemsft** [comment]
Yes, the error codes were off because in sperror.h they seem to jump from hex to dec in two places..!

The tests are actually failing with

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
SPERR_RECOGNIZER_NOT_FOUND (reported incorrectly as SPERR_CANNOT_NORMALIZE) coming from speechRecognizer.LoadGrammar() calling RecognizerBase.Initialize(..)

net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
SPERR_SHARED_ENGINE_DISABLED (reported incorrectly as SPERR_WORD_NEEDS_NORMALIZATION)

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
System.PlatformNotSupportedException : Speech Recognition is not available on this system. SAPI and Speech Recognition engines cannot be found. (from SapiRecognizer..ctor(..))

**Comment by danmosemsft** [comment]
With error codes fixed, I happened to hit another variation, by running the test over remote desktop:
```
        System.InvalidOperationException : No audio device is installed.
        Stack Trace:
          C:\git\runtime\src\libraries\System.Speech\src\Recognition\RecognizerBase.cs(455,0): at System.Speech.Recognition.RecognizerBase.Initialize(SapiRecognizer recognizer, Boolean inproc)
          C:\git\runtime\src\libraries\System.Speech\src\Recognition\SpeechRecognizer.cs(451,0): at System.Speech.Recognition.SpeechRecognizer.get_RecoBase()
          C:\git\runtime\src\libraries\System.Speech\src\Recognition\SpeechRecognizer.cs(116,0): at System.Speech.Recognition.SpeechRecognizer.LoadGrammar(Grammar grammar)
          C:\git\runtime\src\libraries\System.Speech\tests\SpeechRecognizerTests.cs(39,0): at SampleSynthesisTests.SpeechRecognizerTests.SpeechRecognizer()
```
