### ISSUE TITLE
DateTime.Parse broken on 20H2

### ISSUE THREAD

**Issue by DanAvni** [dotnet/runtime#46847]
Running this single line (Full .NET framework 4.8)
`
DateTime.ParseExact("9 a. m.","h tt",System.Globalization.CultureInfo.GetCultureInfo(9226))
`
Throws "String was not recognized as a valid DateTime" exception when running on Windows 20H2 and 2004. It does work on Windows 1909 and Server 2019

Stack trace (executed from LinqPad)
`
at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)   at UserQuery   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   at System.Threading.ThreadHelper.ThreadStart()
`

**Comment by safern** [comment]
I guess given that this happens in 20H2 and 2004, but does not in 1909, seems like a change in NLS is causing this? 

I'll defer to @tarekgh in this case.

**Comment by tarekgh** [comment]
@DanAvni unfortunately this break because of a Windows change. Windows used to have the AM designator for the culture `es-CO` be `a. m.` while the middle space is the regular space character (ordinal 0x20). Look Windows changed that and replaced this middle space with the no-break space (ordinal 0xA0). 

If you try 

```C#
    DateTime.ParseExact("9 a.\u00A0m.","h tt",System.Globalization.CultureInfo.GetCultureInfo(9226));
```

that will work. 

As the .NET is not the real problem causing that, I am closing this issue but I am going to contact Windows team for that. Also, I would suggest you log a new issue for Windows team using Windows 10 Feedback Hub to track it and get the news about it.

Feel free to send any question if you have any and thanks for reporting the issue.

**Comment by DanAvni** [comment]
@tarekgh, Thanks for the explanation. Just for my understanding, I have noticed the original line of code does work in .NET 5 even on my 20H2 machine (but not in core 3.0 on the same machine). Doesn't NET5 use the same NLS?

**Comment by safern** [comment]
@DanAvni .NET 5.0 uses ICU by default when running on Win 19H1 or later. You can however force .NET 5.0 to use NLS with a runtime switch but is not recommended unless you need it because of compat issues.

Please see this article for more detail: https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu

**Comment by tarekgh** [comment]
@DanAvni what @safern mentioned is correct regarding .NET 5.0 is using ICU by default. I want to clarify one issue why this worked when using ICU. ICU still using the `0xA0` as a space separator in `a. m.`. The parser then using ICU to compare the strings (the one coming from culture data and the one we are parsing) and ICU make the regular space character `0x20` equals to the no-break space `0xA0`. That is why the parsing succeeded with ICU.
