### ISSUE TITLE
How can one use C# function pointer to call Win32API on .NET2.0-.NET4.8?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/runtime#46858]
```C#
            nint address = GetProcAddress(GetModuleHandle("user32"), "MessageBoxA"); //MessageBoxW

            //Messy code
            var MessageBox = (delegate*<int, string, string, int, int>)address;
            MessageBox(0, "Hello", "World", 0);

            //No problem, but I can only use 'unmanaged' on .NET5 and doesn't support .NET2.0-4.8
            //var MessageBox = (delegate* unmanaged<int, string, string, int, int>)address;
            //MessageBox(0, "Hello", "World", 0);
```
![image](https://user-images.githubusercontent.com/2529999/104340466-ada69280-5533-11eb-8e7d-3a15b963ea59.png)

How can I use Function pointer to call Win32API on .NET2.0-.NET4.8?

**Comment by Symbai** [comment]
Guess using .NET strings to call unmanaged API don't work for the same reason why it doesn't work on dllimports. Have you tried replacing them with IntPtr and marshall the strings to unmanaged code?

**Comment by tannergooding** [comment]
`delegate*<void>` (or alternatively `delegate* managed<void>` represents a managed function pointer that calls into managed.

`delegate* unmanaged<void>` represents an unmanaged function pointer which calls into unmanaged code using the "system default" (basically equivalent to `Winapi` in `DllImport`) calling convention which may not always line up with the "managed" calling convention. Additionally, it causes things like GC transitions to occur so that the call is safe. However, it is only available on .NET 5+.

`delegate* unmanaged[Stdcall]<void>` represents an unmanaged function pointer which calls into unmanaged code using the `Stdcall` calling convention. It likewise causes things like GC transitions to occur and is available prior to .NET 5 (that is, .NET Standard, Full Framework, and .NET Core).

You can also use other explicit calling conventions, such as `[Cdecl]`, `[Fastcall]`, or `[Thiscall]` keeping in mind that not all of them are necessarily supported by all runtimes (in particular `[FastCall]` is unsupported on .NET Standard, Full Framework, .NET Core, and .NET 5+).

**Comment by tannergooding** [comment]
In the case of your sample code above, you'd want to use `delegate* unmanaged[Stdcall]<IntPtr, byte*, byte* uint, int>` as the signature of the native API: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxa
* Most, but not all, Win32 APIs and callbacks are `Stdcall`.
* `HWND` is an opaque handle and can be represented by a `void*` or `IntPtr`.
* `LPCSTR` is a `const char*` in C/C++, which is a string consisting of 8-bit characters on Windows, this is typically considered just ASCII text (in practice, this is really code page based, so it can be more complex). Most APIs ending with `A` are in this category. Since .NET strings are sequences of 16-bit characters, you can't just use `string` here, you must first convert it to ASCII.
* `UINT` is just an unsigned 32-bit integer, it directly equates to `uint` in C#. You can also use `int`, since it is also 32-bits, but that isn't always desirable

I believe (CC. @AaronRobinsonMSFT, @jkoritzinsky to confirm) that there is a limited amount of marshalling supported for function pointers and so using `string` with `MessageBoxW` may be fine. I believe the behavior is the same as for `P/Invoke` in the docs: https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-data-with-platform-invoke

You can always provide a friendly signature which takes things like `byte[]`, `string`, `out/ref/in parameters`, or other .NET types and then use the correct unsafe code (generally just pinning, sometimes conversion from UTF16<->ASCII or UTF8) to invoke a blittable function pointer. This will be more easily customizable and will show all of the otherwise "implicit" overhead that exists for these .NET types.

**Comment by CreateAndInject** [comment]
By the way, what's the meaning of `calli` ? Whose abbr is `i`? How to pronounce `calli` ?

**Comment by tannergooding** [comment]
`calli` stands for `indirect method call`. You can read more in ECMA-335 (https://www.ecma-international.org/publications/standards/Ecma-335.htm). The actual instruction is documented on III.3.20, but there are more related details throughout the spec

**Comment by CreateAndInject** [comment]
Why is `delegate* unmanaged` unavailable on .NET2.0-4.8?

**Comment by tannergooding** [comment]
Because it required runtime modifications to support. Function pointers, going back to .NET Framework 1.0, only supported a set of explicit calling conventions:
* DEFAULT (the managed convention)
* VARARG
* C (equivalent to cdecl)
* STDCALL
* THISCALL
* FASTCALL

Unlike `DllImport`, there was no bit available that allowed the user to specify `platform default` (`DllImport` provides this via `WinApi`). When C# 9 was working on introducing these features, we recognized this drawback and opted to add a new calling convention bit, which required corresponding runtime changes. Given that .NET Framework is effectively in maintenance mode (https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/) it is not possible to backport this change and so the functionality is unavailable.

**Comment by AaronRobinsonMSFT** [comment]
>How can I use Function pointer to call Win32API on .NET2.0-.NET4.8?

@CreateAndInject I would defer to P/Invokes for calling Win32 APIs on most platforms - even .NET 5+. There are caveats here but in general the use case is unclear. Passing callbacks into a Win32 API is very useful, but the approach above is close to equivalent to a P/Invoke, but as @tannergooding stated the marshalling is limited. I would need to confirm all the cases but the marshalling is inconsistent at best and one would best defer to [blittable types](https://docs.microsoft.com/dotnet/framework/interop/blittable-and-non-blittable-types) in practice for `unmanaged` function pointers.

Is there a specific reason function pointers are desirable for your scenario? If so, understanding that would be interesting for us.

**Comment by CreateAndInject** [comment]
Not every function is exported, `MessageBoxA` is just an example, I want to call any unmanaged function. If `delegate* unmanaged` is unavailable on .NET Framework, I have to use old code : `Marshal.GetDelegateForFunctionPointer`.

**Comment by tannergooding** [comment]
> Not every function is exported

`GetProcAddress` only resolves exported symbols (https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress). If `GetProcAddress` can resolve it, then `DllImport` should be able to resolve it as well.
You should only need function pointers for cases like `Vulkan` or `OpenGL` where they have optional extensions that you have to resolve via a separate exported function, such as `VkGetInstanceProcAddr` or `wglGetProcAddress`.

**Comment by AaronRobinsonMSFT** [comment]
>If delegate* unmanaged is unavailable on .NET Framework, I have to use old code : Marshal.GetDelegateForFunctionPointer.

It is possible in some cases. The issue here is the marshalling semantics are rather different. For functions will blittable types the support should just work since that is what happens for P/Invokes under the hood. However using any non-blittable types is going to result in a random sprinkling of support and as such should be avoided. If the desire is to have ignore all marshalling and avoid the complexity of having to deal with it, I would defer to using `Marshal.GetDelegateForFunctionPointer`.

**Comment by MichalStrehovsky** [comment]
Note that function pointer types in C# are part of C# 9.0 and C# 9.0 is only supported when targeting .NET 5 (see this document for details: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version).

It can be made to work outside .NET 5, but it's an unsupported configuration - so if it doesn't work in a specific environment, you might not be able to get fixes for those issues. There are known issues on UWP, for example. (I assume by ".NET2.0" you mean NetStandard 2.0 - which UWP implements.)

**Comment by AaronRobinsonMSFT** [comment]
@CreateAndInject I think the best answer here is from @MichalStrehovsky. Although some scenarios may work the path is very narrow so the best advice is to stick with .NET 5+.
