### ISSUE TITLE
DateTime.Parse FormatException for non-english text date

### ISSUE THREAD

**Issue by bzz445** [dotnet/runtime#46931]
### Description

After migrate from .NET Core 3.1 to .NET 5.0 get exception: `System.FormatException: The string '12 Янв 2021' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.` for non-english text date

### Example

```
using System;
using System.Globalization;

public class Program
{
	public static void Main()
	{
		Console.WriteLine(DateTime.Parse("12 Jan 2021", new CultureInfo("ru-RU")));
		Console.WriteLine(DateTime.ParseExact("12 Янв 2021", "dd MMM yyyy", new CultureInfo("ru-RU")));
		Console.WriteLine(DateTime.Parse("12 Янв 2021", new CultureInfo("ru-RU")));
	}
}
```

This is confirm on dotnetfiddle if select compiler .NET 5, but no has error if select other compiler: [https://dotnetfiddle.net/dfsT3i](https://dotnetfiddle.net/dfsT3i)

**Comment by danmosemsft** [comment]
@bzz445 what OS are you using? 

Assuming Windows, does forcing 5.0 to NLS mode ([instructions here](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu)) give you the 3.1 behavior again?

**Comment by tarekgh** [comment]
@bzz445 

When running on dotnetfiddle and choosing .NET 5, it will make it run on Linux based system. doing
```C#
    Console.WriteLine("{0}", RuntimeInformation.OSDescription);
```

It prints:

```
Linux 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021
```

On Linux based systems, ICU globalization library is used. ICU is using CLDR Globalization data which is decided by the Unicode standard and considered the most correct data. When looking at such data, you'll find the abbreviated January month name in Russians is `янв.`. Note that it has `.` at the end. You may look at the CLDR data here https://github.com/unicode-org/icu/blob/3b1ec5032c640c360bb8f796db51fa23b85547e2/icu4c/source/data/locales/ru.txt#L1245.

Having the dot in the month name is what made the parsing fail. You should get the same behavior when using 3.1 or 2.0 on Linux machines too. 

On Windows, when using .NET 5.0 by default we are using ICU too. Which means you'll get the same behavior as if you are running on Linux. i.e. the month name will be `янв.`. You have the choice to select the old behavior by opting in using `NLS` mode as @danmosemsft pointed in his reply. Note, the `NLS` behavior which has the month name without the dot is coming from Windows as the .NET don't carry the Globalization data either way. Windows also in the process converging the NLS data to CLDR data. So maybe in the future you start seeing `NLS` using the month name with the dot. 

Last, in general it is proven the globalization data is dynamic and can change. So, if your app/library is doing date formatting and parsing, we would recommend either format the dates with Invariant culture or with ISO format (using "o" specifier) to guarantee the parse succession. 

I am closing the issue here but feel free to send any more question you may have and we'll be happy to help with.
