### ISSUE TITLE
HTTP Compression - Improve/fix support for user-specified Accept-Encoding encodings

### ISSUE THREAD

**Issue by EatonZ** [dotnet/runtime#46948]
### Background

To specify [Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) encodings for HTTP requests, you set `AutomaticDecompression` in a `HttpMessageHandler`-based class (such as `SocketsHttpHandler`). If you wish to change the order the encodings, or add [quality weightings](https://developer.mozilla.org/en-US/docs/Glossary/Quality_values), the workaround seems to be to add the encodings manually before the request is sent:

```c#
if (handler.AutomaticDecompression.HasFlag(DecompressionMethods.Brotli)) request.Headers.AcceptEncoding.Add(new StringWithQualityHeaderValue("br", 1.0));
if (handler.AutomaticDecompression.HasFlag(DecompressionMethods.GZip)) request.Headers.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip", 0.9));
if (handler.AutomaticDecompression.HasFlag(DecompressionMethods.Deflate)) request.Headers.AcceptEncoding.Add(new StringWithQualityHeaderValue("deflate", 0.8));
```

### The Problem

After reviewing the .NET source, I found that `DecompressionHandler` _does_ take into account the existence of user-added encodings before it adds any (code starts [here](https://github.com/dotnet/runtime/blob/0c7dde5de145940dc19bda59a32554ffcafc8c73/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L42)).

Due to the way these checks are set up, with quality weightings added to the encodings, the resulting `Contains` return `false` and duplicate encodings are unnecessarily added.

This is what the header ends up looking like:
`Accept-Encoding: br; q=1.0, gzip; q=0.9, deflate; q=0.8, gzip, deflate, br`

### Proposed Fix/Improvement

Replace `Contains` with a better check. For each encoding already in `AcceptEncoding`, you should check it with `StartsWith`.

**Comment by geoffkizer** [comment]
Yeah, you're right, the current check is not handling quality weighting at all.

I think the best fix would be to explicitly look for StringWithQualityHeaderValue.Value == (encoding name); this should find any encoding header value regardless of quality weighting, and avoid any pitfalls with string comparison that StartsWith might introduce.

This should be straightforward to fix.

**Comment by karelz** [comment]
@EatonZ are you interested in putting up a PR with a fix?

**Comment by EatonZ** [comment]
@karelz [Here you go!](https://github.com/dotnet/runtime/pull/47000)😁

**Comment by EatonZ** [comment]
@karelz Continuing discussion from the PR:

I want to be able to specify compression preferences in various services I communicate with. Without the fix, since the header values get duplicated, it may result in undefined behavior with some servers, or worse - errors.

There isn't a workaround to set quality weightings without also sending duplicate values. Without setting quality weightings, it won't be clear to the server what the client's preferences are since the weighthings will be all be equal (1.0) in that case.

Since there is no workaround, and shouldn't break any existing code, it seems like a good candidate for a servicing release. Let me know your thoughts.

**Comment by karelz** [comment]
@EatonZ thanks for bringing the backport discussion here.

Can you please give me more details about your case? What is your application / service? How large is it? (RPS, number of users, or something like that)
How bad does it hurt your app/service if you cannot specify compression preferences? What is the impact? ... Larger payload sizes? By how much? How does it translate into business cost for your app/service? ... Would "not using" the feature be an acceptable workaround for the time being?

> Without the fix, since the header values get duplicated, it may result in undefined behavior with some servers, or worse - errors.

Does it happen in practice? Do you know about specific servers or server instances that fail? Or is it in phase of "it could potentially happen"?

Would it be an option for you to use .NET 6.0 Preview bits for your app / service?

Just in case for context: In general, we backport only serious problems -- bugs that significantly impact either larger set of customers, or specific segments of customers. Serious problems are for example security issues, reliability issues and occasionally also functional bugs and regressions which make customers' apps entirely/significantly unusable, or make life of large number of developers significantly worse.
Overall, the backport needs to "earn it" with benefit/value. There is always cost and risk associated with making any change (e.g. thorough testing, assessing risk of regressing other scenarios, etc.), and we do not want to make servicing just a copy of vNext/master branch. Servicing releases should be highly stable, minimizing any risk of introducing more problems/regressions.
The key question we will have to answer for shiproom (which makes decision to take or reject each backport) is: If the bug is there for so long (I assume at least since .NET Core 2.1), why is it suddenly important now, given this is the first report ever?

**Comment by EatonZ** [comment]
@karelz

> Can you please give me more details about your case? What is your application / service? How large is it? (RPS, number of users, or something like that)
> How bad does it hurt your app/service if you cannot specify compression preferences? What is the impact? ... Larger payload sizes? By how much? How does it translate into business cost for your app/service? ... Would "not using" the feature be an acceptable workaround for the time being?

My application is a WinForms app, currently in beta with over 1k users. I am working on the "new" server API, and I discovered this bug when working on client-side HTTP code. Unfortunately this API is still basically bare-bones, so I don't know much compression is going to help in the end. I just wanted to ensure the API gets correct headers so I don't have to deal with a potentially confusing problem server-side with these duplicated header values.

> Would it be an option for you to use .NET 6.0 Preview bits for your app / service?

No. I just asked customers/testers to install .NET 5, and don't want to bother anyone with yet another requirement.

> If the bug is there for so long (I assume at least since .NET Core 2.1), why is it suddenly important now, given this is the first report ever?

It could be affecting others (they may not be getting their intended compression types). They probably wouldn't notice unless they intercept the traffic. Backporting the fix _could_ improve compression scenarios for others with high-volume services, who set up headers in the way I do.

As for it being a security issue or serious problem, it's not, but given how simple the fix was, I don't see much harm in backporting it. If the bar is higher than that, I would understand.

**Comment by karelz** [comment]
Thanks for the details!

> given how simple the fix was, I don't see much harm in backporting it. If the bar is higher than that, I would understand.

Any change, no matter how simple or benign it seems, carries a risk (I touched on some of such cases in my talk "[War stories from .NET team](https://www.youtube.com/watch?v=ntGBRi_I3MM)" if you are interested in examples).
Shiproom (rightfully) does not allow fixes into servicing which are not serious enough to offset the general risk. The bar is indeed higher.
If we see evidence that it is hurting customers in productions with real business impact (not just potentially problematic), that could change the fix chances to get backported.
