### ISSUE TITLE
Getting additional fractional digits in sum operation of two double numbers

### ISSUE THREAD

**Issue by david9** [dotnet/runtime#46955]
# Getting additional fractional digits in sum operation of two double numbers

Earlier, we were running with .net core 2.2 and we upgraded to .net core 3.1 for next release of our product.

```
static void Main(string[] args) { 
    double a = 1.035, b = 2.897;
    double sum = a + b;
    Console.WriteLine($"Actual : {a} + {b} = {sum}"); //3.9319999999999995
    Console.WriteLine($"Expectation : {a} + {b} = 3.932");
    Console.ReadLine();
 }
```
![image](https://user-images.githubusercontent.com/2461554/102434606-1be25d00-403b-11eb-8c5b-3959ecbdf3df.png)

After upgrading to .net core 3.1, we are observing that addition of two double numbers is giving additional fractional digits.
We have executed this sample code with 
- .NET Core 2.2
- .NET Core 3.1
- .NET Core 5

This issue is not observed with .NET Core 2.2, but with both .NET Core 3.1 and .NET Core 5.

NOTE: This additional fractional digits is not everytime observed, I have tried with below inputs.
```
a = 1.036, b = 2.896; //not observed
a = 1.035, b = 2.897; //observed
a = 1.034, b = 2.898; //observed
a = 1.033, b = 2.899; //not observed
```

[Sum_With_DoubleDataType_Gives_Additional_FractionalDigits.zip](https://github.com/dotnet/core/files/5706547/Sum_With_DoubleDataType_Gives_Additional_FractionalDigits.zip)

**Comment by scalablecory** [comment]
@tannergooding

**Comment by tannergooding** [comment]
This is by design and more details can be read here: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

The summary is that the values computed haven't changed, just the default display string for these values. 
Prior to .NET Core 3, the default strings returned by `float.ToString()` and `double.ToString()` were not roundtrippable and so `x == x.Parse(x.ToString())` might have returned `false` or even have thrown in some cases.

If you would like to have shorter strings, I would recommend using either a [standard numeric format string](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) or [custom numeric format string](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) that limits the precision to a suitable range.
