### ISSUE TITLE
what are the difference among coop, hybrid and preemptive of thread suspend in monovm? 

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#47076]
why introduce these three mode and what difference?

**Comment by lambdageek** [comment]
There's a description of some of this over at https://www.mono-project.com/docs/advanced/runtime/docs/coop-suspend/

The basic problem is that when the runtime needs to stop threads (for example at some steps during GC) there are two general approaches:
* Preemptive - the runtime sends a signal to the thread and the signal handler for the thread puts it to sleep until it gets a resume signal. (or on Windows or Apple OSes, it uses a kernel calls to stop the thread).
   The problem with this is that we have absolutely no control about what the thread is doing when it gets the signal - it could be in the middle of a syscall to do I/O, it could be running native user code, it could be in the Mono runtime loading a class, etc.  This is a problem because it limits what the runtime can do while threads are suspended - they could be holding system locks or mono locks, they could be in a state where we can't accurately trace their stack, etc.
   Also on some platforms (watchOS, WebAssembly) we don't have enough OS facilities to examine the context when a thread is suspended - we can't see the contents of their registers, or their stack, and thus preemptive suspend on those systems wouldn't be useful for GC and other runtime operations that need to examine the state of suspended threads.
* Cooperative - the runtime sets a flag that all the user threads periodically check. When the flag is set, the thread puts itself to sleep until it gets a resume notification.   With this, as long as the thread is running managed code, it will eventually reach a safepoint and suspend itself.  The advantage is that it will always be in a "nice" place.
   There is more to keep track of in cooperative mode when a thread calls native code - while it's in native it won't have safepoints and it might block for arbitrary amounts of time.  So the runtime marks all the places where a thread goes from managed code ("GC Unsafe" - because it can manipulate managed memory) to native code ("GC Safe" - because it's not supposed to access managed memory).  When the thread is in GC Safe mode instead of trying to suspend it, we just let it run until it tries to come back to GC Unsafe mode.
   The problem with cooperative suspend is that it relies on nice (cooperating) behavior from embedders and from native code - if the native code calls back into Mono suddenly it might be running managed code again when the GC thinks that it is not.  And that can cause problems.   So to use preemptive mode, the native code has to be explicitly annotated with GC transitions - telling the runtime when the thread is switching between GC Safe and GC Unsafe modes.

Hybrid suspend is a combination of the two.  While the thread is in managed code or in the Mono runtime itself, it is in GC Unsafe mode.  In GC Unsafe mode we will try to suspend it cooperatively by expecting the thread to reach a safepoint and suspend itself.   But when the thread calls out to native code we switch it to GC Safe mode and start preemptively suspending it.  That way no matter what kind of native code it is running, we will stop it and it won't be able to invalidate our assumptions by touching managed memory or calling runtime functions.

Hybrid suspend requires even more bookkeeping (every embedding API function needs to switch from GC Safe mode to GC Unsafe on entry and back on exit), but all the bookkeeping is done by the runtime, not by the user code.

So hybrid suspend is a good approach because the embedder code doesn't need to be aware of it - it behaves just like preemptive.  But at the same time it is less likely to suspend the thread in a state that is inconvenient for the runtime, unlike preemptive suspend.

**Comment by SamMonoRT** [comment]
@lambdageek - if the documentation is updated, can we close this out ?

**Comment by lambdageek** [comment]
@SamMonoRT thanks.  I opened a PR for the docs https://github.com/mono/website/pull/561
