### ISSUE TITLE
Test failed: System.Net.NameResolution.Tests.LoggingTest.GetHostEntryAsync_InvalidHost_LogsError

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47104]
Job: [runtime-coreclr libraries-jitstress 20210116.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954677&view=ms.vss-test-web.build-test-results-tab&runId=30122164&resultId=151744&paneView=debug)

Failed tests:
```
net6.0-Linux-Release-arm-CoreCLR_checked-zapdisable-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
net6.0-Linux-Release-arm64-CoreCLR_checked-zapdisable-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
        - System.Net.NameResolution.Tests.LoggingTest.GetHostEntryAsync_InvalidHost_LogsError
```

Error message:
```
events.Count should be > 0
Expected: True
Actual:   False

stack trace:
at System.Net.NameResolution.Tests.LoggingTest.GetHostEntryAsync_InvalidHost_LogsError() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/LoggingTest.cs:line 91
--- End of stack trace from previous location ---
```

**Comment by danmosemsft** [comment]
@wfurt

**Comment by wfurt** [comment]
cc: @MihaZupan  @gfoidl

**Comment by gfoidl** [comment]
This is the timing issue outlined in https://github.com/dotnet/runtime/pull/47034#discussion_r558374191, unfortunately it's bites us (me) here.

But that will be fixed with https://github.com/dotnet/runtime/pull/47034, as the [latest commit there](https://github.com/dotnet/runtime/pull/47034/commits/b723ccd03e2c27b45d24e757ddcf9433a62966a8) has a robust handling for the events.

**Comment by karelz** [comment]
@gfoidl great! Can you please update the PR description that it fixes this issue?
