### ISSUE TITLE
System.Text.Json custom converter doesn't work with Nullable value 

### ISSUE THREAD

**Issue by Gladskih** [dotnet/runtime#47126]
The same Issue https://github.com/dotnet/runtime/issues/44006 closed with comment about HandleNull.
But that still does not work (.Net 5). The next complete example does not throw when it's expected.
```
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

static void Main(string[] args) =>
	Console.WriteLine(JsonSerializer.Deserialize<Dto>("{}")?.Property);

internal class ThrowOnNull<T> : JsonConverter<T>
{
	public override bool HandleNull => true;
	public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
		throw new Exception();
	public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) =>
		JsonSerializer.Serialize(writer, value);
}

internal record Dto
{
	[JsonConverter(typeof(ThrowOnNull<string>))]
	public string Property { get; init; }
}


```

**Comment by huoyaoyuan** [comment]
This will only throw when you are deserializing `{ "Property": null }`. No such property isn't null. The converter will be never invoked, because no potential value can be read.
You are requiring verification for missing property. Since JSON is unordered, the implementation isn't trivial. Their must be a collection to track which properties are present, and is somehow harmful to performance.
