### ISSUE TITLE
iOS: Attempting to JIT compile method '(wrapper native-to-managed) void System.Net.NetworkInformation.BsdNetworkInterface/<>c__DisplayClass5_0:<GetBsdNetworkInterfaces>b__0 (intptr,Interop/Sys/IpAddressInfo*)' while running in aot-only mode.

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#47120]
### Description

The following code throws an exception at runtime when running on an iOS device:

```csharp
NetworkInterface.GetAllNetworkInterfaces ();
```

Exception:

```csharp
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper native-to-managed) void System.Net.NetworkInformation.BsdNetworkInterface/<>c__DisplayClass5_0:<GetBsdNetworkInterfaces>b__0 (intptr,Interop/Sys/IpAddressInfo*)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
    at System.Net.NetworkInformation.BsdNetworkInterface.GetBsdNetworkInterfaces()
    at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces()
    at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
    at MySingleView.AppDelegate.FinishedLaunching(UIApplication app, NSDictionary options) in /Users/rolf/work/maccore/onedotnet/xamarin-macios/tests/dotnet/MySingleView/AppDelegate.cs:line 43
```

Repro:

```shell
git clone https://github.com/rolfbjarne/xamarin-macios
cd xamarin-macios
git checkout dotnet-attempting-to-jit-compile-method-GetBsdNetworkInterfaces
./configure --enable-dotnet
make reset
make all -j8
make install -j8
make singleview -C tests/dotnet
```

[Complete output](https://gist.github.com/rolfbjarne/fea88cdafc1fee4f0c26ea7f93dc1af7)

### Configuration

.NET 6.0.100-alpha.1.21060.3

Binlog: 
[MySingleView.binlog.zip](https://github.com/dotnet/runtime/files/5830375/MySingleView.binlog.zip)

### Regression?

No (new feature)

**Comment by lambdageek** [comment]
This is similar to https://github.com/dotnet/runtime/issues/55736 - It's not an AOT compiler problem, it's a problem in the libraries not using `[UnmanagedCallersOnly]` or `[MonoPInvokeCallback]` to tell the AOT compiler that a managed function will be passed to native code and invoked from there.

This particular issue looks like it was fixed by https://github.com/dotnet/runtime/pull/52192 which switched from passing lambdas to the native method, to using unmanaged function pointers.
