### ISSUE TITLE
Test Regressions/coreclr/GitHub_45929/test45929/test45929.sh failed with assertion failure: IsExecutingOnAltStack() || (curSP <= m_pFrame && m_pFrame < m_CacheStackBase) || m_pFrame == (Frame*) -1 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47142]
Job: [runtime-coreclr gcstress-extra 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954814&view=ms.vss-test-web.build-test-results-tab&runId=30125170&paneView=attachments&resultId=109254)

Failed tests:
```
CoreCLR Linux arm64 Checked gcstress0xc_jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
        - Regressions/coreclr/GitHub_45929/test45929/test45929.sh
```

Error message:
```
Assert failure(PID 770 [0x00000302], Thread: 1112 [0x0458]): IsExecutingOnAltStack() || (curSP <= m_pFrame && m_pFrame < m_CacheStackBase) || m_pFrame == (Frame*) -1
    File: /__w/1/s/src/coreclr/vm/threads.h Line: 1844
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7b7b61f4)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7b7c112c)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7b7c112c)
/root/helix/work/workitem/Regressions/coreclr/GitHub_45929/test45929/test45929.sh: line 388:   770 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/Regressions/coreclr/Reports/Regressions.coreclr/GitHub_45929/test45929/test45929.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun test45929.dll ''
The test started.
Progress:
1/17/2021 11:35:27 PM : 001.0%
1/17/2021 11:35:48 PM : 002.0%
1/17/2021 11:36:06 PM : 003.0%
1/17/2021 11:36:23 PM : 004.0%
1/17/2021 11:36:41 PM : 005.0%
1/17/2021 11:36:59 PM : 006.0%
1/17/2021 11:37:17 PM : 007.0%
1/17/2021 11:37:34 PM : 008.0%
1/17/2021 11:37:52 PM : 009.0%
1/17/2021 11:38:11 PM : 010.0%
1/17/2021 11:38:29 PM : 011.0%
1/17/2021 11:38:48 PM : 012.0%
1/17/2021 11:39:07 PM : 013.0%
1/17/2021 11:39:25 PM : 014.0%
1/17/2021 11:39:43 PM : 015.0%
1/17/2021 11:40:02 PM : 016.0%
1/17/2021 11:40:20 PM : 017.0%
Gathering state for process 770 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.770.dmp
Written 153300992 bytes (37427 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Regressions/coreclr/GitHub_45929/test45929/test45929.sh

stack trace:
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_sh()
```

**Comment by danmosemsft** [comment]
@VincentBu should issues like this have 'jitstress' label as it's part of a jitstress run?

**Comment by VincentBu** [comment]
> @VincentBu should issues like this have 'jitstress' label as it's part of a jitstress run?

@danmosemsft, this test is in ```"CoreCLR Linux arm64 Checked gcstress0xc_jitstress1"```, which also containes the word `gcstress`. Do we need to add `gcstress` label?

**Comment by danmosemsft** [comment]
Good question. @BruceForstall ?

**Comment by BruceForstall** [comment]
> @danmosemsft, this test is in "CoreCLR Linux arm64 Checked gcstress0xc_jitstress1", which also containes the word gcstress. Do we need to add gcstress label?

Yes. Any job name that includes the work "gcstress" (like "gcstress0xc" here) should get the "gcstress" label.

(I've done it for this one).

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/42791

@janvorli You were going to look at the other one.

**Comment by VincentBu** [comment]
Failed again in run: [runtime-coreclr gcstress-extra 20210124.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963916&view=ms.vss-test-web.build-test-results-tab&runId=30356020&paneView=debug&resultId=109347)

Failed tests:
```
CoreCLR Linux arm64 Checked gcstress0xc_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
        - Regressions/coreclr/GitHub_45929/test45929/test45929.sh
```

Error message:
```
Assert failure(PID 4645 [0x00001225], Thread: 5041 [0x13b1]): IsExecutingOnAltStack() || (curSP <= m_pFrame && m_pFrame < m_CacheStackBase) || m_pFrame == (Frame*) -1
    File: /__w/1/s/src/coreclr/vm/threads.h Line: 1844
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f974815f4)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f974815f4)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f979e88b0)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f979f37e8)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f979f37e8)
/root/helix/work/workitem/Regressions/coreclr/GitHub_45929/test45929/test45929.sh: line 388:  4645 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/Regressions/coreclr/Reports/Regressions.coreclr/GitHub_45929/test45929/test45929.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun test45929.dll ''
The test started.
Progress:
1/25/2021 12:12:37 AM : 001.0%
1/25/2021 12:12:57 AM : 002.0%
1/25/2021 12:13:16 AM : 003.0%
1/25/2021 12:13:34 AM : 004.0%
1/25/2021 12:13:54 AM : 005.0%
1/25/2021 12:14:12 AM : 006.0%
1/25/2021 12:14:31 AM : 007.0%
1/25/2021 12:14:50 AM : 008.0%
1/25/2021 12:15:09 AM : 009.0%
1/25/2021 12:15:28 AM : 010.0%
Gathering state for process 4645 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.4645.dmp
Written 144617472 bytes (35307 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Regressions/coreclr/GitHub_45929/test45929/test45929.sh

stack trace:
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_sh()
```

**Comment by janvorli** [comment]
I understand why the assert happens, but the original triggering condition is not possible to figure from the dump. It could be some quirk in the GC stress instructions injection.
It starts with a SIGSEGV in managed code that is not detected as coming from managed code and so exception handling code returns and let a previous registered SIGSEGV handler handle it by calling the invoke_previous_action. Note that we are still running on an alternate stack used for SIGSEGV handling. That handler is the default one and so we restore its handler and then call PROCNotifyProcessShutdown(). That in turn calls a callback registered by the runtime using the `PAL_SetShutdownCallback`. That callback is set to `EESocketCleanupHelper` which ends up calling DiagnosticServerAdapter::Shutdown(); and that one calls DiagnosticServer::Shutdown(). That method uses `EX_TRY` / `EX_CATCH` macros. These end up calling Thread::GetFrame which also checks that the frame address is sane. We are running on an alternate stack, but the flag to detect that is not set on the Thread as it is set only for handling stack overflows. So the `IsExecutingOnAltStack()` returns false and we try to check that the current SP is within the known stack boundaries of the current thread. But since we are running on an alternate stack, that is not true and the assert fires.

The fix would be to propagate a flag indicating that we are running on an alternate stack from the PAL to the runtime in the callback. That will be a bit ugly as it would need to be propagated through several layers. Maybe we could just set the flag on the thread in the EESocketCleanupHelper always. It should have no bad effects as it is running before the runtime shutdowns and effectively just switches off some stack range sanity checks for that code path.
