### ISSUE TITLE
[Question] Why test libraries that target single TFM use TargetFrameworkS (plural)?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#47155]
Very often when I try to run all tests without specifying TFM, I get the following error:

```log
C:\Projects\runtime\src\libraries\System.Diagnostics.TraceSource\tests> dotnet run -c Release
Unable to run your project
Your project targets multiple frameworks. Specify which framework to run using '--framework'.
```

Can `$(NetCoreAppCurrent)` be more than one moniker?

Is there anything that stops us from applying the following change to all test projects?

```diff
- <TargetFrameworks>$(NetCoreAppCurrent)</TargetFrameworks>
+ <TargetFramework>$(NetCoreAppCurrent)</TargetFramework> 
```

cc @ViktorHofer @Anipik

**Comment by ViktorHofer** [comment]
cc @ericstj. I don't remember the exact reason for that limitation anymore

**Comment by ericstj** [comment]
@Anipik hit this limitation when implementing the config system.  At least partially it was due to derived properties which were used in project body.
Regardless it wasn’t an intentional limitation.  I think we should be able to do anything the normal SDK permits.

**Comment by Anipik** [comment]
As @ericstj we rely on tfm being set globally(not in csproj) to set some of custom properties like TargetsWindows. We removed a lot of derived props like outpathPath from props to targets file.

IIRC the only obstacle currently against are the Targets* props being set before the csproj is loaded

**Comment by adamsitnik** [comment]
Thank you all! 

Since it looks that it can't be changed, I am going to close the issue.

**Comment by ViktorHofer** [comment]
It definitely can be changed. Let's keep this issue open to track it.

**Comment by ericstj** [comment]
I remembered another thing here that's challenging: nuget's conditions in props and targets.  At the time those generated props/targets are imported we need to make sure the right value for `$(TargetFramework)` is set.  IIRC this wasn't always the case for a project that just sets `TargetFramework`.  Stuff has changed since then so it might be working now.

**Comment by ViktorHofer** [comment]
With https://github.com/dotnet/arcade/pull/8377 it will be possible to change projects which don't multi-target and aren't RID specific (i.e. `$(NetCoreAppCurrent)` but not `$(NetCoreAppCurrent)-Linux`) to use `TargetFramework` instead of `TargetFrameworks`. That will make the build noticeably faster as well.

I tested my change with the ref projects so I would switch them over first and afterwards address the remaining projects in the libs tree.

**Comment by ViktorHofer** [comment]
This was fixed with https://github.com/dotnet/runtime/pull/64500 and https://github.com/dotnet/runtime/pull/64000.
