### ISSUE TITLE
Debugger siezes up when many websocket connections are opened

### ISSUE THREAD

**Issue by sossee2** [dotnet/runtime#47204]
![image](https://user-images.githubusercontent.com/12380738/105118417-7ed78000-5b22-11eb-887a-f1395023285a.png)
Not sure if exaxtly the same issue but the same symptoms with the exception that this happens reliably as soon as I fire up the hundred or so client websocket connections in my app. App slows to a crawl, Diag tools screen almost stops and many threads are in "System.Private.CoreLib.dll!System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()" as per the screenshot. It started happening following my port from .NET Framework to .NET5.0 (latest GA build)

_Originally posted by @sossee2 in https://github.com/dotnet/runtime/issues/42375#issuecomment-763283117_

* The app appears to run fine without the debugger attached. 
* With debugger attached the app appears to get slower and slower (exponentially) with more and more websockets added.

**Comment by hoyosjs** [comment]
This looks like a case of https://github.com/dotnet/runtime/issues/38736

**Comment by sossee2** [comment]
> This looks like a case of #38736

Thanks for the link. Are there any suggested workarounds to this?

**Comment by hoyosjs** [comment]
None that I can think of now really. The debugger uses the cross-thread dependency notifications very often (evaluation of properties for example in the watch window) and we always fire them. We are talking about adding something, but if won't land until at least .NET 6. Looping @dotnet/dotnet-diag in case they have any ideas.

**Comment by sossee2** [comment]
I tried adding [DebuggerStepThrough] attribute to the websocket wrapper however that didn't seem to have an impact. Given I don't need to debug the class that is doing most of the task based work which I believe to be the source of this issue, is there a workaround based on that?

**Comment by hoyosjs** [comment]
No. This is all in the general debugger infrastructure. If we didn't have said notifications, we could end up in deadlock situations when evaluating functions under the debugger. The problem is there's no mechanism to turn it off so that it only happens during evaluations - it's always on. This is actually a notorious perf hit when running under the debugger and there's large amounts of tasks completing for example.

**Comment by noahfalk** [comment]
You said this problem occurs when debugging in .NET 5 but it doesn't occur when debugging in .NET Framework right? Is the .NET Framework app also using similar web socket code with similar load or did something change there as well? I ask because this performance characteristic in the debugger has existed for a long time, including on .NET Framework. The fact that it wasn't causing you grief before suggests something else changed. We don't yet know what it is, but my first guess is that the app might be executing code containing NotifyOfCrossThreadDependencySlow() far more frequently in .NET 5 than it did on Framework because something is generating Tasks much more frequently. For example if the original app was generating 100 Tasks/sec and the ported code is generating 10,000 Tasks/sec then a previously trivial debugger perf overhead might now be a large one. Comparing a CPU trace of the .NET Framework app to the .NET 5 app while running under the debugger might be able to identify where the discrepancy is.

> Are there any suggested workarounds to this?

By no means do I think this is an easy or pleasant workaround, but just to put all options on the table theoretically you could build a private copy of System.Private.CoreLib.dll with [this line](https://github.com/dotnet/runtime/blob/e4c6c4c4422b15c526642ee139e89bda4f83b242/src/coreclr/System.Private.CoreLib/src/System/Diagnostics/Debugger.cs#L50) commented out to use for development purposes. Depending on your app this might make VS more prone to having function evaluations that it can't abort. If that did occur you could additionally disable implicit function evaluation in the VS debugger settings window to mitigate it.

**Comment by sossee2** [comment]
Hi Noah,

That's correct, I am now using an open source wrapper around the System.Net.WebSockets.WebSocket class whereas I was previously using websocketsharp in the .NET framework which didn't use async/await. What you've described resonates with what I am seeing. 
I am assuming that this code is creating a task on every read of the websocket:
`while (true)
                    {
                        result = await client.ReceiveAsync(buffer, token);`
![image](https://user-images.githubusercontent.com/12380738/105250317-a8011a80-5bcd-11eb-8a1d-afff4baef9f2.png)

In my case, there are many websocket reads. I'm not sure if it is related but there are also much more GC Events in the Diagnostic tools (session) while debugging (I assume also related to tasks?)

My application is aiming to be as real time as possible (low latency) when it comes to reading these streams of data. I'm not sure if there is a way to read the websocket stream without all the task creation? I'm going to try using the overload for receive that returns a ValueTask in case that may help.

It sounds like I will need to find a way to reduce task usage in my local debug env.

**Comment by noahfalk** [comment]
> there are also much more GC Events in the Diagnostic tools (session) while debugging (I assume also related to tasks?)

It could be Task objects though I don't have much evidence to go on. If you are curious the Visual Studio profiling tools has an [allocation profiler](https://docs.microsoft.com/en-us/visualstudio/profiling/dotnet-alloc-tool?view=vs-2019) that can give you lots more detail.

> I'm going to try using the overload for receive that returns a ValueTask in case that may help.

This sounds like a good thing to try and certainly the intended purpose of ValueTask was to get the benefits of Task asynchrony while avoiding a lot of the objection allocation overhead. I don't know offhand if it will reduce the frequency of calls to NotifyOfCrossThreadDependency().

I was also chatting with @hoyosjs today and he is investigating if there are options to improve the debugger's performance here. I don't want to make any promises, but we sympathize that having the debugger run that slowly sounds very aggravating and we'd like to improve it if we can. In the meantime I am glad that you have a few leads.

**Comment by sossee2** [comment]
Thanks Noah, I'll check out the allocation profiler (didn't know it existed) as it will definitely help me identify the GC issues. For the time being I'm going to have to reduce load in my debug env which as you've guessed is not ideal as I can't leverage it's awesome powers. Very keen to here if there are any other options that may come up in future.

**Comment by Mithras** [comment]
Here is a working workaround that might be ok for some scenarios (e.g. dev conteiners): https://github.com/dotnet/runtime/issues/52149#issuecomment-831657590

**Comment by tommcdon** [comment]
Seems to be a duplicate to #38736
