### ISSUE TITLE
Add machine epsilon constant

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/runtime#4722]
(Moved from https://github.com/dotnet/roslyn/issues/7088)

Currently there is a `Double.Epsilon` constant, but it is not reliable (because it is **not** the machine epsilon) and could be equal to zero in some extreme cases (on ARM as [stated by MSDN](https://msdn.microsoft.com/en-us/library/system.double.epsilon%28v=vs.110%29.aspx?cs-save-lang=1&cs-lang=csharp)).

According to the [Wikipedia article](https://en.wikipedia.org/wiki/Machine_epsilon), machine epsilon is a number around `2 ^ (-53)` or `1.11e-16` (and `Double.Epsilon` is `4.94065645841247E-324` currently).

Machine epsilon could be usable when doing floating point comparison, and the presence of `Double.Epsilon` currently only confuses people (see some StackOverflow questions: [1](http://stackoverflow.com/questions/20222314/is-math-absx-double-epsilon-equivalent-to-math-absx-0d), [2](http://stackoverflow.com/questions/9392869/where-do-i-find-the-machine-epsilon-in-c)). It is **not** usable when comparing double number values.

I propose the new constant value `Double.MachineEpsilon` that should be determined according to the current IEEE754 rules. It could be usable for doing math and comparisons, and it will correspond to the C language `DBL_EPSILON` constant.

Additional reading: http://www.johndcook.com/blog/2010/06/08/c-math-gotchas/

**Comment by joperezr** [comment]
In order to move this forward we need an actual API Proposal so that it can be reviewed.

**Comment by tannergooding** [comment]
@joperezr, I've moved this off of `System.Runtime` as it is a `System.Numerics` issue that got mistriaged. Most of the APIs/issues impacting `float`/`double` fall under numerics, but get triaged to `System.Runtime` because that is the reference assembly they live in.

**Comment by tannergooding** [comment]
@ForNeVeR, the `machine epsilon` value you are quoting is not formally defined by the IEEE 754 specification and it is equally "unusable", in principle, as the existing `double.Epsilon`.

The `epsilon` value used by .NET is the smallest value such that `x + 0 != 0`
The `epsilon` value most commonly referenced is the C/C++ `FLT_EPSILON` and `DBL_EPSILON`, which is the smallest value such that `x + 1 != 1`
The `epsilon` value you referenced above (`~1.11e-16`) is the counterpart to C/C++ epsilon, which is the smallest value such that `1 - x != 1`

Every one of these values has some inherent issue that "prevents" its more general use.

The root issue is that IEEE 754 floating-point values are not evenly distributed, in fact the epsilon between values doubles every power of 2 (for float/double, which are binary floating-point).
What this ultimately means is that while `float` is 32-bits and can represent ~4 billion unique values, ~50% of those values fall between -1 and +1. A more accurate breakdown is:
* Negative Infinity
* ~1 billion values between MinValue and -1
* ~1 billion values between -1 and the smallest negative normal
* ~8.3 million denormal values between the smallest negative normal and zero
* Negative Zero
* Positive Zero
* ~8.3 million denormal values between the zero and the smallest positive normal
* ~1 billion values between the smallest positive normal and +1
* ~1 billion values between +1 and MaxValue
* Positive Infinity
* ~16.7 million NaN values

The epsilon exposed by .NET is the smallest possible epsilon and the one for which all other epsilon are multiples.
The C/C++ epsilon is actually `double.Epsilon * 2^1022` and is the epsilon for all values between 1 and 2, the epsilon for values between 2 and 4 will be `double.Epsilon * 2^1023` (`FLT_EPSILON * 2`), the epsilon for values between 4 and 8 will be `double.Epsilon * 2^1024` (`FLT_EPSILON * 4`), etc
Likewise, going downwards, the epsilon for values between 0.5 and 1 is `double.Epsilon * 2^1021` (`FLT_EPSILON / 2`), for values between 0.25 and 5 is `double.Epsilon * 2^1020` (`FLT_EPSILON / 4`), etc.

This exposes the "fundamental" issue in that there is no single epsilon value that can be defined, because the maximum error between two values can differ greatly and some values (specifically powers of two) can have two epsilons.
.NET Core exposes `Math.BitIncrement` and `Math.BitDecrement` functions which can be used to help determine the epsilon between two values. For example, to get `FLT_EPSILON`, you can do `MathF.BitIncrement(1.0f) - 1.0f`.
The general algorithm `BitIncrement(x) - x` can be used to get the upper epsilon and `x - BitDecrement(x)` can be used to get the lower epsilon for almost any value (NaN and Infinity are special exceptions).

**Comment by ForNeVeR** [comment]
@tannergooding, thanks for your thorough answer!

I agree that using `Math.BitIncrement`/`Math.BitDecrement` (these two weren't around when I was filing the issue) should be enough for most numeric-related purposes, and they also have no problem of vague "epsilon" definition. The users will _have_ to think of their purpose and which "epsilon" value (if any) they need to use in their case.

I believe this could be closed as obsolete.
