### ISSUE TITLE
As a developer, I get compile time diagnostics for unsupported APIs

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#47228]
In .NET 5, we introduced a built-in platform analyzer that will check whether you call platform-specific APIs. However, this doesn't cover APIs that always throw `PlatformNotSupportedException`. We should mark those APIs in some fashion as well, for example, by applying `ObsoleteAttribute`.

We should make sure whatever mechanism we choose for detecting those APIs, that the docs [also reflect this](https://github.com/dotnet/dotnet-api-docs/issues/1683).

An example of an unmarked APIs is [CSharpCodeGenerator.CreateFromBatch()](https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.PlatformNotSupported.cs#L13).

**Comment by danmosemsft** [comment]
@jeffhandley is this one something you're going to drive? If so we can set you or someone as assignee I think.

**Comment by jeffhandley** [comment]
As was mentioned in #42967, we have over 4000 instances of throwing `PlatformNotSupportedException`. We would need to review that list and for each occurrence determine:

1. Should there be a `[SupportedOSPlatform]` or `[UnsupportedOSPlatform]` attribute applied?
    * This would apply if the member is statically (un)supported on specific platforms
    * But this cannot be used if support is conditional, unless #44922 is addressed
2. Should there be an `[Obsolete]` attribute?
    * This would apply if the member is no longer supported in .NET, regardless of platform

I suspect we'd want to divide this list up by area so that owners across the areas could review and address the instances in their areas. That could be done either before or after the implementation of an analyzer.

We were pondering in #42967 whether or not an analyzer for doing this would be valuable beyond the runtime team, or if this is one we should build directly into the runtime repo. I'm unsure on that myself.

**Comment by terrajobst** [comment]
Talked to @jeffhandley today. #42967 is really about us finding the issues; while that's useful that's not actually what this issue is about. This issue is about the user's experience when they call such an API. They should get a warning.

**Comment by jeffhandley** [comment]
#44916 is also filed, and this one would involve reviewing the 4000 occurrences of PNSE that exist.

**Comment by buyaa-n** [comment]
> 2. Should there be an `[Obsolete]` attribute?
>     * This would apply if the member is no longer supported in .NET, regardless of platform

If we apply for those `[Obsolete]` attribute what we would do in case the API get supported on any of the OS? For example i see an [issue](https://github.com/dotnet/runtime/issues/18768) for  adding support for the [CSharpCodeGenerator.CreateFromBatch()](https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.PlatformNotSupported.cs#L13). Can we remove the attribute?

**Comment by buyaa-n** [comment]
Could not we use the `[SupportedOSPlatform] or [UnsupportedOSPlatform]`  attributes with framework names (with optional version)? (especially in case we want the PCA analyzer warn for their usages)

For example, by my understanding the above [CSharpCodeGenerator.FromFileBatch()](https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.PlatformNotSupported.cs#L13) API is unsupported on .NetCore (or it is only supported on .Net framework)
```cs
[UnsupportedOSPlatform("netcoreapp")]
// or [SupportedOSPlatform("net46")]
private CompilerResults FromFileBatch(CompilerParameters options, string[] fileNames)
{
    throw new PlatformNotSupportedException();
}
```

**Comment by buyaa-n** [comment]
[Brief Meeting Note]: 
We have 3 options for handling APIs not supported in .NetCore but having open issue for future support:
1. If we decide not to support the API we can close the related issue and add [Obsolete] to the API
2. Add support for `AllPlatforms` scenario to PCA analyzer and annotate the API with `[UnsupportedOSPlatform("AllPlatforms")]`
3. Leave the API un annotated until we decide if we really gonna add support for this

For the 2 API we discussed in the meeting, `Regex.RegexAssemblyCompiler()` and `CodeDom.CSharpCodeGenerator` we are leaving them unannotated until we decide to not support for sure. (Did not choose `option 2` because there are too few cases found, only 2 for now)

**Comment by krwq** [comment]
@buyaa-n what's the current status of this?

**Comment by buyaa-n** [comment]
> @buyaa-n what's the current status of this?

Previously detected PNSEs on cross-platform builds and filed issues with findings, yesterday started the work detecting PNSEs on targeted builds and will file/update issues with findings. Overall this issue will cover the detecting PNSEs and that work will be done within 6.0. But some of the related issues might not make 6.0, depends on the area owners

**Comment by buyaa-n** [comment]
My PNSE analysis is done and most findings are reported with separate issues referenced above. There is few APIs having an issue for future support which we decided not to annotate, for now, I did not file issue for them since the discussion we had in https://github.com/dotnet/runtime/issues/50535. Here is the list of those APIs:

Assembly | API | Progress | Issue for   support
-- | -- | -- | --
System.CodeDom | 'CSharpCodeGenerator.FromFileBatch(CompilerParameters, string[])'   unconditionally throws PNSE, VB version too | No progress | https://github.com/dotnet/runtime/issues/18768
System.Text.RegularExpressions | 'RegexAssemblyCompiler.Save()' throws PNSE   and has no annotation | No   progress | https://github.com/dotnet/runtime/issues/19838
System.Configuration.ConfigurationManager | 'RsaProtectedConfigurationProvider' all   APIs unconditionally throws PNSE | in   PR | https://github.com/dotnet/runtime/issues/19838

Some of them were missing info in the doc that they are not supported in .Net Core, [a PR for updating them is up](https://github.com/dotnet/dotnet-api-docs/pull/7024)

With that, I think we can close this issue now what do you think @terrajobst @jeffhandley?

**Comment by jeffhandley** [comment]
Thanks, @buyaa-n!
