### ISSUE TITLE
TypeDescriptor cannot be invoked in Console Application on .NET 5

### ISSUE THREAD

**Issue by yangzhongke** [dotnet/runtime#47248]
### Description
When running the following code  in Console Application on .NET 5:
```csharp
Type type = Type.GetTypeFromProgID("PowerPoint.Application", true);
object comObject = Activator.CreateInstance(type);
TypeDescriptor.GetProperties(comObject);
```
TypeDescriptor.GetProperties throws the following exception:
```
FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

```
In contrast, the code can run well in Windows Form Application on .NET 5.

My PowerPoint version is Office 365 Apps for enterprise(13530.20376).

@jeffschwMSFT

**Comment by yangzhongke** [comment]
@jeffschwMSFT

**Comment by AaronRobinsonMSFT** [comment]
@yangzhongke Thanks for reporting this. The issue here is around COM objects and how the `TypeDescriptor` looks these up. Unfortunately there is an indirect dependency on WinForms and without that available this class will fail. The following illustrates how this dependency is made:

https://github.com/dotnet/runtime/blob/7225baf3b4e233bf4e8cf53a5c01485beaca5773/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L2858-L2876

I am going to defer to the WinForms team on their thoughts but my initial ones are this is "by-design". If this is a blocking issue I am more than willing to work with you to develop a workaround if needed.

/cc @JeremyKuhne @RussKie @jkoritzinsky @elinor-fung

**Comment by AaronRobinsonMSFT** [comment]
Actually reading this more I believe there will be another deeper failure here and this is simply the failure of the "helpful" diagnostic system.

**Comment by yangzhongke** [comment]
Thanks for your reply. I see. 
Is it possible to add System.Windows.Forms to the reference of a Console Application?
I tried to add NuGet Package System.Windows.Forms: Install-Package System.Windows.Forms, but ended up failing.

**Comment by JeremyKuhne** [comment]
@yangzhongke  You can make a "WinForms" console app if you manually change the project file. Note, however, that this isn't a scenario we test.

With .NET 5.0 your project file needs to have at least this:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
```

The `Main` method should be marked with `[STAThread]`:

``` C#
[STAThread]
static void Main(string[] args)
{
    Console.WriteLine("Hello World!");
    Console.ReadLine();
    MessageBox.Show("Howdy!");
}
```

Older versions of .NET Core look a little different:

``` xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
```

**Comment by AaronRobinsonMSFT** [comment]
I believe that @JeremyKuhne's suggestion is appropriate here.

**Comment by RussKie** [comment]
Associated docs: https://docs.microsoft.com/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type
