### ISSUE TITLE
PowerPoint instance didn't quit when code runs in debug mode.

### ISSUE THREAD

**Issue by yangzhongke** [dotnet/runtime#47249]
The follow code launches PowerPoint application, and open a pptx file, and then iterates all slide.

```csharp
Type type = Type.GetTypeFromProgID("PowerPoint.Application", true);
dynamic ppApp = Activator.CreateInstance(type);
dynamic presentations = ppApp.Presentations;
dynamic ppFile = presentations.Open(filePath, false, false, false);
var slides = ppFile.Slides;
foreach (var slide in slides)
{
	slide.Copy();
}
ppFile.Close();
ppApp.Quit();
Marshal.FinalReleaseComObject(slides);
Marshal.FinalReleaseComObject(ppFile);
Marshal.FinalReleaseComObject(presentations);
Marshal.FinalReleaseComObject(ppApp);
GC.Collect();
```
.NET Version: .NET 5, Console Application.

When the code runs in Release mode and then quit, the PowerPoint process will quit automatically.
In contrast, When the code runs in Debug mode and then quit, the PowerPoint process will not quit.

My PowerPoint  version is Office 365 Apps for enterprise(13530.20376).

@jeffschwMSFT

**Comment by yangzhongke** [comment]
@jeffschwMSFT

**Comment by yangzhongke** [comment]
I understand that using for loop instead of foreach can solve this problem, as follows:
```csharp
for (int i= 0;i < slides.Count;i++)
{
	var slide = t.T(slides[i+1]);
	slide.Export(@$"{workDir}\{i}.png", "PNG");
}
```
Even so, I wonder why foreach version has problem under Debug mode.
Thanks!

**Comment by huoyaoyuan** [comment]
Some information I know:
In Debug mode, the lifetime of a variable is the whole method. In Release mode, its lifetime ends at the last use. This may be part of the reason.

**Comment by AaronRobinsonMSFT** [comment]
@huoyaoyuan There are a few behavioral issues here that are kind of confusing compared to .NET Framework. The distinction between Debug/Release mentioned is important and plays a role. The most relevant is that .NET Core no longer attempts to finalize all RCWs when shutting down. This means that if the application is terminating and the RCW is in the finalizer it will simply be leaked. This behavior is typically acceptable for in-proc COM servers because all resources are bound to the process. If however the final clean up of the RCW is needed for some side effect then measures must be put in place to perform that cleanup. Being in Debug builds will exaggerate this issue.
