### ISSUE TITLE
Redundant load-acquire elimination discrepancy between CoreCLR and Clang

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#47261]
C code:

```c
void foo(int *p)
{
    (void)__atomic_load_n(p, __ATOMIC_ACQUIRE);
    (void)__atomic_load_n(p, __ATOMIC_ACQUIRE);
    (void)__atomic_load_n(p, __ATOMIC_ACQUIRE);
}
```

C# code:

```csharp
public static void Foo(ref int p)
{
    _ = Volatile.Read(ref p);
    _ = Volatile.Read(ref p);
    _ = Volatile.Read(ref p);
}
```

`clang-11 -O3 atomic.c` results in this code for `foo`:

```asm
mov eax, dword ptr [rdi]
mov eax, dword ptr [rdi]
mov eax, dword ptr [rdi]
ret
```

(Note: I'm specifically using Clang because it optimizes atomics much more aggressively than GCC. In any case, GCC emits the same code.)

The C# code for `Foo` results in this:

```asm
cmp [rcx], ecx
ret
```

Given that both snippets are using acquire semantics, who's right? Is CoreCLR wrong to eliminate the redundant loads, or is Clang being overly conservative?

**Comment by GrabYourPitchforks** [comment]
Also /cc @stephentoub, who understands the `Volatile` type better than anybody else. I suspect this has to do with that _volatile_ in CLR land is for acquire / release semantics, while _volatile_ in C++ is more for controlling low-level hardware memory access.

**Comment by alexrp** [comment]
Note that the C code makes no use of `volatile`.

**Comment by stephentoub** [comment]
This looks like https://github.com/dotnet/runtime/issues/6280.

**Comment by JulieLeeMSFT** [comment]
CC @AndyAyersMS 
Is this related to https://github.com/dotnet/runtime/issues/10268

**Comment by AndyAyersMS** [comment]
Yes, they are related.

Per ECMA-355, I.12.6.7 Volatile reads and writes:

> The `volatile.` prefix on certain instructions shall guarantee cross-thread memory ordering rules.
They do not provide atomicity, other than that guaranteed by the specification of §I.12.6.6. 

and subsequently

> An optimizing compiler that converts CIL to native code shall not remove any volatile operation,
nor shall it coalesce multiple volatile operations into a single operation. 

and the jit is not honoring this last "shall not," either here or in #6280 or in #10268.

In this case the latter two of the three reads are removed because we can clear their side effect flags during assertion prop, so only the first read remains:

```
Non-null prop for index #01 in BB01:
N002 (  3,  2) [000018] V--XGO-N----              *  IND       int    $1c1
Propagating 0000000000000001 assertions for BB01, stmt STMT00003, tree [000008], tree -> 0
Propagating 0000000000000001 assertions for BB01, stmt STMT00003, tree [000009], tree -> 0
Re-morphing this stmt:
STMT00003 (IL   ???...  ???)
N004 (  3,  2) [000009] ---XGO------              *  COMMA     void   $241
N002 (  3,  2) [000018] V---GO-N----              +--*  IND       int    $1c1
N001 (  1,  1) [000005] ------------              |  \--*  LCL_VAR   byref  V00 arg0         u:1 $80
N003 (  0,  0) [000008] ------------              \--*  NOP       void   $201


optAssertionPropMain removed tree:
N003 (  0,  0) [000008] ------------              *  NOP       void   $201
```

The fix should be fairly simple, morph must check for volatile, but currently this involves a tree walk. Perhaps we should model volatile as a general side effect so it tends to get checked along with all the other side effects, and propagates up to the roots of trees.

**Comment by AndyAyersMS** [comment]
I don't see us fixing this for 6.0. Willing to reconsider if we have evidence this is causing a problem somewhere.

**Comment by VSadov** [comment]
I think this is ByDesign. Clang may be used with device memory with unknown sideeffects of volatile reads, so it can't drop then.

In .NET reads just read memory. Since noone looks at the results, the reads can be dropped.

**Comment by VSadov** [comment]
There are multiple existing versions of the runtime, in and out of support, that exhibit this assumption/behavior, trying to fix it will only introduce inconsistencies. 

Since targeting device memory is not a supported scenario, there is a very little value in changing this (as opposed to documenting).
