### ISSUE TITLE
[Release\3.1] Adding a ci leg similar to the sourceBuild

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#47480]
In the past few releases, sourcebuild have to make some patches due to some bugs\inconsistencies merged in the corefx branch.

eg system.numerics.tensors stable verison list was updated to have 0.3.0 which was not shipped. This was not caught during the corefx ci because we dont build packages in the servicing branch.

solutions here :- add a sourcebuild leg or add a leg which builds all the packages (that should reduce this frequency).

cc @ViktorHofer @safern @ericstj @aik-jahoda

**Comment by ViktorHofer** [comment]
Agreed, but should we focus on protecting this scenario in master instead of in a release branch. release/2.1 and release/5.0 both will be out of support very soon and release/3.1 a year later. How often has this happened in release/3.1? Is this something that we can live with until release/3.1 is out of support?

**Comment by ViktorHofer** [comment]
cc @Anipik regarding my question about priority for 3.x.

**Comment by ViktorHofer** [comment]
Closing as we will likely not work on this before 3.1 is out of support.
