### ISSUE TITLE
crossgen2 crashes when using --codegenopt:EnableExtraSuperPmiQueries

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#47554]
Repro:

I'm trying to SuperPMI collect a crossgen2 compilation of all libraries in Core_Root (win x64 Checked):
```
py c:\gh\runtime2\src\coreclr\scripts\superpmi.py collect --crossgen2 -output_mch_path c:\win-x64-cg2.mch -assemblies c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
```

A small repro:
```
c:\gh\runtime2\.dotnet\dotnet.exe c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\crossgen2\crossgen2.dll  --codegenopt:EnableExtraSuperPmiQueries=1 @c:\bugs\spmicollect4\x.rsp
```
x.rsp:
```
c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\R2RDump\ILCompiler.Reflection.ReadyToRun.dll
-o:c:\bugs\spmicollect4\cg2-temp\crossgen2_c__gh_runtime2_artifacts_tests_coreclr_windows_x64_Checked_Tests_Core_Root_R2RDump_ILCompiler_Reflection_ReadyToRun_dll.out.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\System.*.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\Microsoft.*.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\mscorlib.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\netstandard.dll
```

failure:
```
Unhandled exception. System.NotImplementedException: [System.Reflection.Metadata]System.Reflection.Internal.MemoryBlock
   at ILCompiler.DependencyAnalysis.ReadyToRun.ModuleTokenResolver.GetModuleTokenForType(EcmaType type, Boolean throwIfNotFound)
   at ILCompiler.DependencyAnalysis.ReadyToRun.SignatureContext.GetModuleTokenForType(EcmaType type, Boolean throwIfNotFound)
   at ILCompiler.DependencyAnalysis.ReadyToRun.SignatureContext.GetTargetModule(TypeDesc type)
   at ILCompiler.DependencyAnalysis.ReadyToRun.TypeFixupSignature.GetData(NodeFactory factory, Boolean relocsOnly)
   at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable()
   at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObject(String objectFilePath, EcmaModule componentModule, IEnumerable`1 nodes, NodeFactory factory, Boolean generateMapFile, Boolean generateMapCsvFile, Boolean generatePdbFile, String pdbPath, Boolean generatePerfMapFile, String perfMapPath, Int32 customPESectionAlignment)
   at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```

This JIT option is used to ensure that SuperPMI replays are more useful, especially for JitDump and other textual output and debugging, by asking more JIT/EE interface method questions than are strictly required to compile a function.

**Comment by BruceForstall** [comment]
@dotnet/crossgen-contrib It seems like the "extra" JIT-EE api calls during SuperPMI collections that the JIT makes about structs and  struct fields causes problems for crossgen2.

**Comment by trylek** [comment]
So I've taken a closer look at what happens there. The problem happens in the compilation of <code>PEExportTable..ctor</code> due to the <code>BlobReader</code> local variables. BlobReader is a struct that has a field of type <code>MemoryBlock</code> and the SuperPMI-specific code path in <code>Compiler::makeExtraStructQueries</code> ends up asking for its getClassSize which triggers the type layout check emission, we're however unable to encode its signature because the MemoryBlock is not directly referenced anywhere in the ILCompiler.Reflection.ReadyToRun assembly so that we have no token to represent it. I haven't yet double-checked why Crossgen1 doesn't hit this, I suspect the reason is hits the same problem but silently skips emitting the check. Currently Crossgen2 delays emitting signatures until all methods have been compiled (for more or less historical reasons) which makes it harder to use the same opportunistic logic. We hit a similar problem before that I fixed with Jan's and Andy's help in

https://github.com/dotnet/runtime/pull/35728

At the first glance it seems to me that we should do something similar around the makeExtraStructQueries code path but I'm no JIT expert and frankly speaking I don't know too much about SuperPMI either. If my suggestion makes sense to you, I think I should be able to produce the PR along the lines of the previous one.

/cc @jkotas @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Seems plausible the same fix would work for the "extra queries".
