### ISSUE TITLE
Error when initializing a coreclr host

### ISSUE THREAD

**Issue by WilhelmW** [dotnet/runtime#47679]
I always get the error "Fatal error. Internal CLR error. (0x80131506)" no matter what I do after initializing.

https://github.com/WilhelmW/CSharpCoreCLRHost

**Comment by vitek-karas** [comment]
For example:
https://github.com/WilhelmW/CSharpCoreCLRHost/blob/ee1f3ec9a22e4f3e6481e437910f16b212d5a077/CoreCLRHost/CoreCLR.cs#L17

The native interface defines the `propertyKeys` as `char**`, but default .NET marshalling on Windows will marshal `string` as `WCHAR`. So you're passing the strings as UTF16, while the native API assumes UTF8.

Can I ask what is the purpose of this library? I guess on .NET Framework it makes some sense (to be able to load .NET Core components into otherwise .NET Framework process), but the library is `netstandard2.0` - and on .NET Core this will potentially load a second instance of .NET Core into the process - which is currently not a supported configuration.

**Comment by WilhelmW** [comment]
I am trying to sandbox c# code by running it in an modified coreclr host.

**Comment by WilhelmW** [comment]
I tried changing all string arguments with IntPtr using Marshal.StringToHGlobalAnsi. But I still get the same error.
I also logged the exception which gets returned by the initialize method: "Unhandled exception. System.Runtime.InteropServices.COMException (0x80131022): Invalid operation. (0x80131022)".
But I can't find any useful information about that exception.

**Comment by SingleAccretion** [comment]
That's the host not being happy with something.
```
for hex 0x80131022 / decimal -2146234334
HOST_E_INVALIDOPERATION                                        corerror.h
# The operation is invalid
```
For future reference, https://docs.microsoft.com/en-us/windows/win32/debug/system-error-code-lookup-tool is a very handy tool for recovering meaning of error codes.

**Comment by vitek-karas** [comment]
The test does basically this:
* It runs as .NET Core 3.1 app - so it loads `coreclr.dll` (and the rest of .NET Core) and then runs the test code
* Then it calls `LoadLibrary("coreclr")` - on Windows this returns the already loaded `coreclr.dll` module which runs the test itself
* Then it calls `coreclr_initialize` from that module
* This fails with `HOST_E_INVALIDOPERATION` because CoreCLR can only be initialized once. Basically it fails here: https://github.com/dotnet/runtime/blob/025c4d0bdab3ad55d429cdd5b3ec78c852f8a074/src/coreclr/vm/corhost.cpp#L88

Scenario question:
By "modified" you mean you want to run a different version of .NET Core in-proc with the one running your main process?

As mentioned above, we currently don't support running two instances of .NET Core in the same process. You can force this to happen, but I would not recommend it. Just a small subset of things which will be difficult or won't work at all:
* Debugging - debuggers have no mechanism to pick one runtime over the other - the results are probably a mess or failure
* Communication with the other runtime - you won't be able to use any managed objects to communicate - it would have to be purely a native ABI (just like talking to a C++ component for example)
* Tracing and similar features - probably broken if not outright failing

If you need to load a component and are worried about problems with dependency resolution (different versions of the same dependency and so on) - then use `AssemblyLoadContext`: https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

If you want to run untrusted code, then there's no good way to do this in-proc. The only recommended way is to run the component in a separate process. This also applies to cases where you need stricter control over resource usage of the component (for example you don't want the component to starve the host process of memory).
