### ISSUE TITLE
Add IsMacCatalyst() and IsMacCatalystVersionAtLeast() to System.Runtime

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#47768]
## Background and Motivation

As per the header, all changes to src/libraries/System.Runtime/ref/System.Runtime.cs are subject to API review. This is a minimal change to class OperatingSystem to add checks for [Mac Catalyst](https://developer.apple.com/mac-catalyst/), directly copying the existing behaviour of `IsTvOS()` and `IsTvOSVersionAtLeast`

Roughly speaking, Mac Catalyst exposes the iOS API subset for use on macOS, allowing for source (but not binary) compatibility with iOS/iPad apps. A number of the default apps in recent macOS are actually Catalyst apps.

Ref: https://github.com/dotnet/runtime/issues/47517

## Proposed API

```diff
diff --git a/src/libraries/System.Runtime/ref/System.Runtime.cs b/src/libraries/System.Runtime/ref/System.Runtime.cs
index 67894c17773..8ed0532b930 100644
--- a/src/libraries/System.Runtime/ref/System.Runtime.cs
+++ b/src/libraries/System.Runtime/ref/System.Runtime.cs
@@ -3099,6 +3099,8 @@ public sealed partial class OperatingSystem : System.ICloneable, System.Runtime.
         public static bool IsIOSVersionAtLeast(int major, int minor = 0, int build = 0) { throw null; }
         public static bool IsMacOS() { throw null; }
         public static bool IsMacOSVersionAtLeast(int major, int minor = 0, int build = 0) { throw null; }
+        public static bool IsMacCatalyst() { throw null; }
+        public static bool IsMacCatalystVersionAtLeast(int major, int minor = 0, int build = 0) { throw null; }
         public static bool IsTvOS() { throw null; }
         public static bool IsTvOSVersionAtLeast(int major, int minor = 0, int build = 0) { throw null; }
         public static bool IsWatchOS() { throw null; }
```

## Usage Examples

Right now, my main usage is in correctly gating which tests are run specifically against the correct platform, i.e.
```diff
+        [Fact, PlatformSpecific(TestPlatforms.MacCatalyst)]
+        public static void TestIsOSPlatform_MacCatalyst() => TestIsOSPlatform("MacCatalyst", OperatingSystem.IsMacCatalyst);
```

## Alternative Designs

You could argue that adding one bool-return function per OS isn't very scalable, but that ship already sailed a long time ago I think.

**Comment by rolfbjarne** [comment]
Versioning on Mac Catalyst is somewhat complex, because there are two versions in effect: the macOS version the app is running (or targeting), and the equivalent iOS version of the Mac Catalyst API.

Unfortunately Apple decided to use the macOS version in some places, and the iOS version in other places.

For the Xamarin parts of Mac Catalyst (API bindings), we decided to use the iOS version for API version checks (https://github.com/xamarin/xamarin-macios/issues/10453), because this is the version that Apple uses in Objective-C/Swift, and the version they use in their documentation.

Unfortunately it's not the version their version API (`[NSProcessInfo operatingSystemVersionString]`, [UIDevice systemVersion]`) returns.

The end result is that we had to special-case the API we expose for version checks to handle Mac Catalyst versions (https://github.com/rolfbjarne/xamarin-macios/commit/9314bb5679bb246d7926ba32bb33fd2277da00c0).

I believe `IsMacCatalystVersionAtLeast` should handle versions the same way.

**Comment by directhex** [comment]
@rolfbjarne That's valuable info RE the implementation details. Does it change anything about the API added to the System.Runtime reference assembly (i.e. `IsMacCatalystVersionAtLeast()`), in your opinion?

**Comment by directhex** [comment]
src/libraries/Common/src/Interop/OSX/Interop.libobjc.cs is where the actual implementation is happening, I'd welcome suggestions there

**Comment by rolfbjarne** [comment]
> Does it change anything about the API added to the System.Runtime reference assembly (i.e. `IsMacCatalystVersionAtLeast()`), in your opinion?

No, it doesn't change the public API in any way, it's an implementation detail. Should I open a new issue about it?

**Comment by directhex** [comment]
> > Does it change anything about the API added to the System.Runtime reference assembly (i.e. `IsMacCatalystVersionAtLeast()`), in your opinion?
> 
> No, it doesn't change the public API in any way, it's an implementation detail. Should I open a new issue about it?

Maybe just move the discussion to the PR for now? Unless it gets merged with "wrong" version detection, then a new issue is absolutely correct

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Diagnostics
{
    public partial class OperatingSystem
    {
        public static bool IsMacCatalyst();
        public static bool IsMacCatalystVersionAtLeast(int major, int minor = 0, int build = 0);
    }
}
```
