### ISSUE TITLE
Question: Deserializing a claim using BinaryReader fails in netfx if the claim has a property set

### ISSUE THREAD

**Issue by akhilesh84** [dotnet/runtime#47793]
This is w.r.t. to the below issues that I could find:

[28515](https://github.com/dotnet/runtime/issues/28515)
[23004](https://github.com/dotnet/runtime/issues/23004)

I see the problem fixed in netcoreapp 2.1. Is there any workaround suggested for netfx?

**Comment by GrabYourPitchforks** [comment]
I'll ping the Full Framework owners and get their thoughts on this.

**Comment by akhilesh84** [comment]
Thanks. For the time being, we managed by adding an extension method on Claim which essentially includes the small fix that was made in netcore side. I'll close this one.

**Comment by GrabYourPitchforks** [comment]
@akhilesh84 We discussed this with the Full Framework owners this morning. We decided __not__ to backport this fix to Full Framework due to the small number of requests for it. There is a workaround, as you discovered: create your own method which implements the correct logic around `BinaryReader`, copied from the fixed netcore sources. This mechanism will work across all runtimes: netcore and unpatched netfx, and if netfx ever gets patched in the future your logic will continue to work correctly.
