### ISSUE TITLE
Reference type in public field causes TypeLoadException for Com Interop

### ISSUE THREAD

**Issue by BickelLukas** [dotnet/runtime#47849]
### Description

I am using a VB6 Library through COM Interop. 
Everything works fine until the class contains a reference type as a public field. 
This causes the program to throw a `System.TypeLoadException: 'The Signature is incorrect'` as soon it is launched.

VB6 Code:
```
Public Settings As clsSettings
```

as soon as the class containing that line gets used within the project it crashes.

### Configuration
.NET Version: 5.0.102
OS: Windows 10 19042.746
Architecture: x64 (but app is built for x86 for Com interop)

### Regression?
The same library can be used from .NET Framework without a Problem.

**Comment by AaronRobinsonMSFT** [comment]
@BickelLukas Can you provide some more details on how to reproduce this? Support for `IDispatch` and VB6 in .NET 5+ is much more limited than in .NET Framework. Understanding exactly what is failing will help us to determine if this is an area that is intentionally no longer supported or a bug we will fix in .NET 5+.

For example, see https://github.com/dotnet/runtime/issues/13192

**Comment by BickelLukas** [comment]
@AaronRobinsonMSFT I did have a Breakthrough on this yesterday and was able to use the Library after all.

It might just have been a User error that could've been solved by better documentation or error messages. 

I will provide more Information and a sample project first thing monday.

**Comment by BickelLukas** [comment]
Here's a summary of the changes I made in order to get this to work.
- Enable `EmbedInteropTypes`
- Instantiate the interface instead of the class: `clsMain` instead of `clsMainClass` (Otherwise i get an error that the class cannot be embedded)

The weird thing is that without a reference type as a public field, I don't have to embed the interop types and can instantiate the class directly.


minimal Repro:
[ComInteropRepro.zip](https://github.com/dotnet/runtime/files/5942143/ComInteropRepro.zip)

The Repro contains 2 C# and one VB6 Project. 
I included the compiled VB6 binary dll inside the VB6 Folder. It needs to be registered via `regsvr32`.

The Solution contains 2 C# Winforms Projects targeting .NET 5.
One of them works while the other does not.

The only difference between the 2 Projects is that one has `EmbedInteropTypes` set to true while the other one has it set to false.
The code to instantiate the com class is in the codebehind of the Form1. I also provided some comments there.

**Comment by elinor-fung** [comment]
Alright - finally got to digging through this. @BickelLukas - thank you for the clear repro including the compiled VB6 binary - it was really helpful.

The actual error is on inspecting the `_VTablGap*` on `ComInteropRepro._clsMain` - `0x8013123b : Method is not marked static but is not HASTHIS or EXPLICITTHIS.`

And indeed, the method is:
```
.method public specialname rtspecialname 
        void  _VtblGap8() runtime managed
{
} // end of method _clsMain::_VtblGap8
```

Whereas when it is embedded:
```
.method public specialname rtspecialname 
        instance void  _VtblGap1_1() runtime managed
{
} // end of method _clsMain::_VtblGap1_1
```

When running `tlbimp.exe` (from .NET Framework) on `ComInteropRepro.dll` directly, the method is also correctly marked as an instance method.

It is using the [`TypeLibConverter`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.typelibconverter) class that is problematic. The implementation of `TypeLibConverter.ConvertTypeLibToAssembly` ends up producing `_VTablGap*` methods that are not marked as static or instance, resulting in the failure in the .NET runtime.

By default, `COMReference` uses the `TypeLibConverter` in-proc instead of launching `tlbimp.exe` to generate the interop assembly. This can be configured through the `ComReferenceExecuteAsTool`, so a potential workaround (aside from embedding the types) is to set:
```xml
<PropertyGroup>
  <ComReferenceExecuteAsTool>true</ComReferenceExecuteAsTool>
</PropertyGroup>
```
Which will launch `tlbimp.exe` instead, such that the generated library won't fail validation.

In .NET Framework, the validation that is failing here was not done for `_VTblGap*` methods, since they aren't 'real' methods, but just indications for the correct vtable layout. But with https://github.com/dotnet/runtime/commit/beb215b1d134b6f1b9affe2481b48073481139d1, the signature validation was moved up such that we end up doing it for `_VTablGap*`.

We should be able to go back to skipping that validation for `_VTablGap*` methods.
