### ISSUE TITLE
Socket.Begin*** methods wrapping Task variants do not throw SocketExceptions synchronously

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#47905]
The patterns we started to use while implementing #43845 are silently introducing a breaking change.

Previously, when a native socket method (eg. `WSASend`) returned an error within a `Begin***` call, we were throwing `SocketException` synchronously:

https://github.com/dotnet/runtime/blob/f0c95523d7f3d5006a8a87ff48870983e9007669/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L2492-L2496

We are no longer doing this in the methods we refactored to wrap Tasks. We are just forwarding the failed task to an `IAsyncResult`:
https://github.com/dotnet/runtime/blob/f3b433039b23b57fea17de117485f2b071030f69/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L2245
The Task/ValueTask variants are (by design?) not throwing on sync path. This means that the APM exceptions will be only observed when invoking the corresponding `End***` calls, even if the error has been reported synchronously.

We should either switch back to old exception behavior in the APM methods, or announce this as a breaking change.

Note that this is a poorly covered functionality. The refactor work did not lead to any test failure until #47781, and even there, we only encountered it one outerloop test.

/cc @geoffkizer

**Comment by geoffkizer** [comment]
We should maintain the existing behavior here if it's not too much trouble, i.e. throw from Begin* for sync failure. Again, I think this is counter to the usual IAsyncResult pattern, which is why the helpers don't do this. But it's better to maintain existing behavior.

FWIW, it would also be interesting to look at .NET Framework behavior here. Early in .NET Core (2.0?) we made a change so that operations that complete synchronously at the OS level would actually complete synchronously at the .NET level, i.e. IAsyncResult/Task. I can't recall how exception behavior was handled before this change, though -- it may be that exceptions were still synchronous and were thrown from Begin even before this change. Either way, it would be good to know for sure. If .NET Framework doesn't throw from Begin in these cases, then that's a good reason to do the same for .NET Core, even if that's different than past behavior of .NET Core.

**Comment by antonfirsov** [comment]
Looks like we are throwing synchronously in .NET Framework:
https://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,3430
https://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,4066

I also think, we should revert to the old behavior, so *triaging* this issue to 6.0. I believe we should fix this before pushing in any further overloads.

**Comment by stephentoub** [comment]
> we should revert to the old behavior

FWIW, I wouldn't invest a ton of time and energy into doing so, nor would I jeopardize the behavior the Task-based methods to do so.

**Comment by antonfirsov** [comment]
I don't think it's a ton of time and energy to reintroduce this for the APM methods. I didn't mean to change the Task-based overloads. Putting back the `untriaged` label since there is no consensus.

**Comment by karelz** [comment]
Triage: Looks like regression we introduced during 6.0. Low cost, we should do it and prevent 6.0 from shipping it.
If cost goes higher, we can revisit.

**Comment by antonfirsov** [comment]
As per discussion under https://github.com/dotnet/runtime/pull/51212#discussion_r615453251,  I'm closing this in favor of https://github.com/dotnet/dotnet-api-docs/issues/6658.
