### ISSUE TITLE
TraceSource nullable ref annotations should allow more nulls

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#47936]
Several methods on `TraceSource` allegedly do not accept nulls for message parameters, but as no exception is thrown with null input I think a nullable annotation is appropriate.

This code throws no exceptions:

```cs
TraceSource ts = new TraceSource("test");
ts.TraceEvent(TraceEventType.Error, 0, null, null);
ts.TraceInformation(null);
ts.TraceInformation(null, null);
```

Yet you can see each method produces warnings about null inputs:

![image](https://user-images.githubusercontent.com/3548/107098526-a427e780-67cc-11eb-8cf9-6e51338a79fb.png)

**Comment by stephentoub** [comment]
Yeah, this is one of those situations where the nullable annotations are relatively meaningless because there are interactions between them.  So whereas this doesn't throw an exception:
```C#
using System.Diagnostics;

TraceSource ts = new TraceSource("test");
ts.Switch.Level = SourceLevels.All;
ts.TraceEvent(TraceEventType.Error, 0, null, null);
```
this does throw an exception:
```C#
using System.Diagnostics;

TraceSource ts = new TraceSource("test");
ts.Switch.Level = SourceLevels.All;
ts.TraceEvent(TraceEventType.Error, 0, null, new object[0]);
```
because the implementations check whether the args is not null, and if it isn't, then it requires that the format also be non-null.

I agree we should loosen the annotations on the parameters, as right now they're preventing valid uses, it just means the annotations here are useless.
