### ISSUE TITLE
Fix setup-stress-dependencies

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#48015]
The setup-stress-dependencies.* scripts were removed in #44490, but there are references which were missed.

Most notably
https://github.com/dotnet/runtime/blob/1bff0cce7ba7de077c09e331d24e3b27c3779888/eng/pipelines/libraries/run-test-job.yml#L94-L107

See also 
```
$ git grep setup-stress-dependencies
eng/pipelines/libraries/run-test-job.yml:            - script: $(Build.SourcesDirectory)\src\coreclr\tests\setup-stress-dependencies.cmd
eng/pipelines/libraries/run-test-job.yml:            - script: $(Build.SourcesDirectory)/src/coreclr/tests/setup-stress-dependencies.sh
src/coreclr/scripts/superpmi.py:#    NuGet packages (like the setup-stress-dependencies scripts do).
src/coreclr/scripts/superpmi.py:        the setup-stress-dependencies.cmd/sh script has been run, which is typically only
src/coreclr/scripts/superpmi.py:        package and extract it using the same mechanism as setup-stress-dependencies
src/tests/Common/scripts/bringup_runtest.sh:${scriptPath}/setup-stress-dependencies.sh --arch=$ARCH --outputDir=$coreOverlayDir
```

/cc @echesakovMSFT

**Comment by echesakovMSFT** [comment]
@sdmaclea Thanks for reporting this - I will put up a PR to remove all these references.

**Comment by BruceForstall** [comment]
@echesakovMSFT I hit this problem because I thought I would try again to get the `runtime-coreclr libraries-gcstress0x3-gcstress0xc` pipeline running, but the code has decayed because it (namely, eng\pipelines\libraries\run-test-job.yml) still calls setup-stress-dependencies.cmd/sh.

So how can this be fixed?

It looks like the src/tests/Common/Directory.Build.targets parts of https://github.com/dotnet/runtime/pull/44490 need to be added to some part of the build system that constructs the libraries testhost -- maybe as part of the "libs.pretest" subset that the run-test-job.yml file also calls?

@safern Do you know where this logic should go?

@echesakovMSFT Do we now always populate coredistools into Core_Root? (on platforms that support GCStress and require cordistools for GCStress)?

**Comment by echesakovMSFT** [comment]
> Do we now always populate coredistools into Core_Root? (on platforms that support GCStress and require cordistools for GCStress)?

Yes, we do this on win-x86, win-x64 and linux-x64.

**Comment by echesakovMSFT** [comment]
Closed by https://github.com/dotnet/runtime/pull/65924
