### ISSUE TITLE
Question: Rewriting IL function body for calleeId inside ICorProfilerCallback::JITInlining

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#48081]
Hi!

We know that the runtime generates `ICorProfilerCallback::JITInlining()` callbacks (not `ICorProfilerCallback::JITCompilationStarted()`) for methods being inlined.

Is it possible to instrument IL code in `ICorProfilerCallback::JITInlining()` callback for `calleeId` function (the one being inlined), or it can only be done in `ICorProfilerCallback::JITCompilationStarted()` callbacks, and to get them we have to disable inlining for specific calleeId by `*pfShouldInline = FALSE` (https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-jitinlining-method)?

Linked issue: https://github.com/dotnet/runtime/issues/37504

cc @davmason

**Comment by davmason** [comment]
Hi @k15tfu,

There are two relevant items here. The first is that due to the way the JIT requests IL for inlined methods it ignores any profiler code versioning. So regardless of whether you instrument via ICorProfilerInfo::SetILFunctionBody or RequestReJIT, it will be ignored at any point it is inlined. In order to have the runtime use the updated IL you must set pfShouldInline false in JITInlining, and you must set pfShouldInline to false for all calls to JITInlining for the same method or you could have a situation where some methods are calling in to the instrumented code and some are not.

The second is about when you can instrument the method. Assuming you set pfShouldInline to false for all JITInlining callbacks, you will always received a JITCompilationStarted callback for the method that was originally going to be inlined. You do not have to instrument code in the inliner's JITCompilationStarted, it is sufficient to instrument the code at any point in time as long as it occurs before the inlinee is compiled.

I.e. if A() is attempting to inline B() and you set pfShouldInline to false for the call to JITInlining for B, you can update B's IL at any point before it is compiled. The JITCompilationStarted callback for B would be easiest.

Let me know if you have any more questions.

**Comment by k15tfu** [comment]
@davmason Thank you, everything is clear.
