### ISSUE TITLE
Enable SO_REUSE_UNICASTPORT when connecting sockets without an explicit bind

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#48219]
### The problem

When `SocketsHttpHandler` or other middleware building on top of System.Net.Sockets establishes high  (>= 16k) number of TCP connections, new connection attempts will fail with socket error 10055 (`WSAENOBUFS`) because of port exhaustion.

On Windows 10+, this can be avoided by enabling `SO_REUSE_UNICASTPORT` (`SocketOptionName.ReuseUnicastPort`). When enabled, `socket.Bind()` will not allocate a local port, instead, actual port allocation will be deferred until the `ConnectEx` call, allowing local port reuse and a much higher scale of outbound connections.

Currently the only way to enable `SO_REUSE_UNICASTPORT` for HttpClient is to override `ConnectCallback` as following:
https://gist.github.com/antonfirsov/e86ddc9ac287b7dd63cd85f78ca125f6 

We had 1 customer hitting this in production, causing port exhaustion.

### Proposal

If no explicit bind has been done before connecting a socket, we are doing a wildcard bind:
https://github.com/dotnet/runtime/blob/a473a9c4b2d5545d8d7ce2269727a633eb90a2c4/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs#L232-L261

We should enable `SocketOptionName.ReuseUnicastPort` before binding (by default). This is a non-breaking change, since it is scoped to the internal auto-binding logic.

**Comment by davidni** [comment]
To preserve context for anyone looking at this in the future, the limit mentioned in the PR description (16k connections) is really the number of ephemeral ports configured on the machine. Per [msdn](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-port-exhaust), recent Windows machines are configured with 16,384 ephemeral ports by default, hence the 16k mentioned.

Error message we observed when attempting to create a new connection after the limit was exceeded: `socket error 10055 (WSAENOBUFS): An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full`.

Thanks @antonfirsov for the quick fix.

**Comment by aaronla-ms** [comment]
@antonfirsov I might be missing something, but this looks a lot like [ServicePointManager.ReusePort](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.reuseport?view=net-5.0). Is there a reason `ServicePointManager.ReusePort=true` isn't already sufficient when using HttpClient?

**Comment by wfurt** [comment]
`HttpClient` does not use `ServicePointManager` @aaronla-ms. The whole strategy changes and .NET Core does not depend or use single global setting and `ServicePointManager` is obsolete.

**Comment by aaronla-ms** [comment]
@wfurt Thanks for clarifying, that certainly clears up the issue.

I filled a doc bug for the potentially misleading netcore/net5.0+ documentation.
