### ISSUE TITLE
Remove and fix suppressions of ca1825

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#48212]
There are a few suppressions for CA1825 commented with the reason being that `Array<T>.Empty` isn't available in all configurations.

This can be fixed by using a conditional compilation to use `Array<T>.Empty` when it's available, and `new T[0]` where it's not.

**Comment by huoyaoyuan** [comment]
Most `new T[0]` in corelib should be intentionally not using `Array.Empty`, with a comment explaining.

**Comment by Youssef1313** [comment]
Cases that shouldn't use `Array.Empty<T>` seem to be already documented:

https://github.com/dotnet/runtime/blob/451d67f85b2f2ad75669cb4da20e7881fe83e8e0/src/libraries/System.Linq.Expressions/src/System/Dynamic/DynamicObject.cs#L435

https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/tools/Common/TypeSystem/Common/MethodDesc.cs#L375

The number of violations is very low, so it should be easy to manually review and make sure there are no unintended changes.

**Comment by stephentoub** [comment]
I see two places:
https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Threading.Tasks.Dataflow/src/Internal/ImmutableArray.cs#L28-L30
https://github.com/dotnet/runtime/blob/b2adfd7ae40e1ca0f4bd311ca052846d46a8c9bb/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L36-L41
(there's a third that mentions this, but also has other reasons explained)

Is that what this issue is about?

FWIW, I don't think it's worth the complexity to try to address it.

**Comment by Youssef1313** [comment]
> Is that what this issue is about?

@stephentoub Yes. Also the following if the usage of `Array.Empty<T>` is okay:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/EmptyArray.cs#L8-L10

https://github.com/dotnet/runtime/blob/69f260eff523bc16c8a95c232e4816b3a1764e88/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs#L91-L95

---

> I don't think it's worth the complexity to try to address it.

Given that the number of violations is low, I don't think it would be that complex.

**Comment by stephentoub** [comment]
> Also the following if the usage of Array.Empty<T> is okay

The ExecutionContext one is not because of lack of the API; it's by design not using Array.Empty.

> Given that the number of violations is low, I don't think it would be that complex.

It mucks up the code with ifdefs, and Array.Empty only doesn't exist in some of the oldest targets in the repo; over time those will stop being supported, and this wouldn't be necessary anyway, so it's unnecessary churn.

The benefit of Array.Empty is also in aggregate; a couple of extra zero-length arrays allocated isn't measurable, and use of Array.Empty in such cases can actually be a net negative: in addition to the overhead of the array itself, you have the overhead of all of the support necessary in the runtime for that particular generic instantiation, and that's not free.  So, for example, it's pretty unlikely any other code will ever use `Array.Empty<ActivityLink>()`, yet we'll be paying for that generic instantiation.

**Comment by Youssef1313** [comment]
> Array.Empty in such cases can actually be a net negative

@stephentoub Hmm, good to know that. Could the docs for CA1825 be updated with that info in [When to suppress violations](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825#when-to-suppress-warnings) section? I thought it's always more performant to use Array.Empty vs. new T[0].

Meanwhile, I'm going to close.

**Comment by stephentoub** [comment]
> Could the docs for CA1825 be updated with that info in When to suppress violations section?

I don't think it's worthwhile to complicate the docs for that.  Better to keep them clean and straightforward and not impart undue choice.  The differences we're talking about here are miniscule in the grand scheme of things, but for the core .NET libraries, we care about miniscule.
