### ISSUE TITLE
Microsoft.Extensions.DependencyInjection package is missing a net5.0 configuration and doesn't exclude $(NetCoreAppCurrent)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48307]
Also, did we intentionally ship a net5.0 asset for that package?

cc @maryamariyan @ericstj

**Comment by ViktorHofer** [comment]
Also why does the package's nuspec list dependency groups for `netcoreapp2.1` and `netcoreapp3.0`? Is this a packaging infra bug? cc @Anipik @ericstj 

```
      <group targetFramework=".NETCoreApp2.1">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="6.0.0-preview.1.21102.12" />
        <dependency id="Microsoft.Extensions.DependencyInjection.Abstractions" version="6.0.0-preview.1.21102.12" />
      </group>
      <group targetFramework=".NETCoreApp3.0">
        <dependency id="Microsoft.Extensions.DependencyInjection.Abstractions" version="6.0.0-preview.1.21102.12" />
      </group>
```

**Comment by ericstj** [comment]
Those are projections of the netstandard dependencies, trimming inbox packages.

.NETStandard 2.0
Microsoft.Bcl.AsyncInterfaces (>= 5.0.0)
Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0.0)
System.Threading.Tasks.Extensions (>= 4.5.4)

.NETStandard 2.1
Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0.0)

So .NETCoreApp2.1 supports .netstandard2.0 and it has Threading.Task.Extensions inbox, so it gets a new group and that package is removed.

.NETCoreApp3.0 needs to be copied from .NETStandard2.1 so that the newly created .NETCoreapp2.1 group doesn't take precedence.

This is done by this task: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs

**Comment by ViktorHofer** [comment]
I didn't know about this packaging feature. Are we concerned that we won't have a similar mechanism with NuGet's pack task? I guess not as there's still conflict resolution which will remove the unnecessary reference during the build.

**Comment by ericstj** [comment]
This optimization was much more important when we regularly referenced so many inbox packages (netcoreapp1.x,  netstandard1.x).  As part of the work when moving to NuGet pack folks should be closely looking at the diff of nuspecs and understanding the reason and implications of the differences. I suspect very few will notice this difference and those that do will be OK with conflict resolution doing its thing. cc @Anipik
