### ISSUE TITLE
The Generic Enum.Parse<T> method should have a Generic Type Constraint on Enum

### ISSUE THREAD

**Issue by annaisabelhuber** [dotnet/runtime#48310]
## Background and Motivation

Right now, the generic `Parse<T>` and `TryParse<T>` methods have only a type constraint on struct, but not on enum.

This means the following code compiles:

```
var x = Enum.Parse<int>("This compiles");
```

At runtime it throws an exception that the type provided must be an `Enum`. This can already be detected at compile time if the Parse<T> method uses a `where T: struct, Enum`.

## Proposed API

Add `Enum` as a type constraint to the public Parse and TryParse method of the Enum class.

**Comment by SingleAccretion** [comment]
This would be a breaking change - extremely unlikely to happen.

The design for constraints on generic `Enum` methods is the way it is because it makes using them possible in generic contexts where the `T` is not constrained to `Enum, struct`.

**Comment by MichalStrehovsky** [comment]
Just last week I was looking at some code that needs to do some ugly reflection just because of the `struct` constraint:

https://github.com/dotnet/aspnetcore/blob/0fc8560af08ad580cea0e96a37db62b8c46d06a5/src/Components/Components/src/BindConverter.cs#L1496-L1498

If it was up to me, instead of doing a breaking change and constraining it even more, I would drop the `struct` constraint since it doesn't prevent that much anyway.

**Comment by thomasclaudiushuber** [comment]
I think it makes sense to adjust it. Right now it looks inconsistent to me with other generic methods in the Enum class, like for example the GetNames<T> method, as that one has the type constraints struct, Enum.

![image](https://user-images.githubusercontent.com/7116546/108038030-aa268f80-703a-11eb-820c-627f738ccf0c.png)

**Comment by tannergooding** [comment]
Closing this. As indicated we cannot fix this without it being a breaking change and that is a very high bar that is unlikely to be hit for something as core and widely used as `System.Enum`.
