### ISSUE TITLE
Test failed : threading.SetThreadDescription.test1

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#48496]
Run: [runtime-coreclr outerloop 20210218.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1001621&view=ms.vss-test-web.build-test-results-tab&runId=31316134&resultId=109694&paneView=debug)

Failed test:
```
CoreCLR Linux x64 Checked no_tiered_compilation @ (Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59

 -threading.SetThreadDescription.test1
```

**Error message:**
```
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
```

**Comment by danmoseley** [comment]
Possibly related to https://github.com/dotnet/runtime/pull/47465

**Comment by jkotas** [comment]
@esoros @am11 Could you please look into fixing this test on Alpine?

**Comment by esoros** [comment]
Yeah I can take a look at this - I don’t think that alpine supports pthread_setname_np but I need to verify that

**Comment by esoros** [comment]
@am11 @jkotas Not to spin around in circles but are you fine with removing the tests? I don't see a compiler pragma for musl and don't have a goof way off the top of my head to conditionally run these tests.

**Comment by jkotas** [comment]
I would be fine with it.

**Comment by am11** [comment]
This was the first conditionally compiled PAL test.

> I don't see a compiler pragma for musl

The test is already excluded from compilation on Alpine (which is why PAL tests are building on Alpine without error). During the test run, however, this line is causing issue if the test name (from .txt file) was not found in test binaries: https://github.com/dotnet/runtime/blob/584d9bfa692f0cab3dd9382b8cd0a4f9d0c302d3/src/coreclr/pal/tests/palsuite/paltests.cpp#L74 fix is to replace this line with a simple skip message: `printf("Skipping test '%s' because its binary was not found on this platform.\n", argv[1]); return 0;` for any conditionally-compiled test.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr outerloop 20210228.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1015947&view=ms.vss-test-web.build-test-results-tab&runId=31632410&resultId=109694&paneView=debug)

Failed test:
```
R2R Linux x64 Checked @ (Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59
 
-threading.SetThreadDescription.test1
```

**Error message:**
```
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
```

**Comment by BruceForstall** [comment]
@am11 @esoros @jkotas This test has been failing every coreclr outerloop job since it was introduced 11 days ago (https://dev.azure.com/dnceng/public/_build?definitionId=655&_a=summary).

Can we either get it (1) disabled (for just Alpine, or for all platforms), (2) fixed, or (3) deleted ASAP?
