### ISSUE TITLE
FeatureRequest: Being able to set TimeZoneInfo.Local per thread

### ISSUE THREAD

**Issue by angelaki** [dotnet/runtime#48518]
Right now the property `TimeZoneInfo.Local` is readonly (haven't investigated further, propably it doesn't have a backing field), but being able to set a Threads timezone would be very great!

Right now we are able to set a threads culture what is widely used in AspNetCore environments, allowing the program to return "stringed" values based on the clients locale. I guess it would be great to allow `DateTime.ToLocalTime()` to get the threads (e.g. the users) timezone. Right now I am working with a service for that, but it feels a bit inconsequent to use the threads culture but need a dedicated service for "the threads time".

What do you think? Are there good reasons this isn't realized yet?

**Comment by mattjohnsonpint** [comment]
From a functional perspective, one can achieve the same thing by using a `ThreadLocal<T>` or preferably an `AsyncLocal<T>`, with a `TimeZoneInfo` object of their choosing.  They can then use `TimeZoneInfo.ConvertTime` and similar functions with that time zone rather than `DateTime.ToLocalTime`.

However, it would support other scenarios.  For example, one might be using a library that calls `DateTime.ToLocalTime` internally.  As only a consumer of the library, one can't change the time zone being used.

It would also be useful in testing scenarios.  Some of this is being discussed in #36617

**Comment by tarekgh** [comment]
@angelaki I am closing this issue. Please try to add your input and follow up on https://github.com/dotnet/runtime/issues/36617. In general, in .NET changing the time/time zone on specific part of the app can cause some issues (interop between various parts of the app, interop with other related functionality of the system...etc.

@mattjohnsonpint suggestion is reasonable if you want to achieve the scenario you want to support.
