### ISSUE TITLE
Unexpected behavior of DiagnosticListener and ActivityListener

### ISSUE THREAD

**Issue by AndreyTretyak** [dotnet/runtime#48533]
I would like to clarify that the following behaviors are expected:
1. `ActivityListener.ActivityStarted/ActivityStopped` would be called when you start and stop activity using `DiagnosticListener.StartActivity/StopActivity`. You are getting this behavior when  `ActivityListener.ShouldListenTo` return `true` for `ActivitySoure` with an empty name, the one created here (see repro below): https://github.com/dotnet/runtime/blob/b2adfd7ae40e1ca0f4bd311ca052846d46a8c9bb/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L42

2. `DiagnosticListener.IsEnabled()` always returns `true`, or at least I was not able to find cases when it returns `false`.
Calling method in an empty project still returns `true` (It looks like some subscriptions always exist or added when a listener created). 

Code that demonstrates both issues (console app targets net5.0) 
```CSharp
using System;
using System.Diagnostics;

var listener = new DiagnosticListener("TestListener"); 
Console.WriteLine(listener.IsEnabled()); // Output: True
Console.WriteLine(listener.IsEnabled("SomeString")); // Output: False

var activityListener = new ActivityListener();
activityListener.ShouldListenTo += activitySource => true;
activityListener.ActivityStarted += activity => Console.WriteLine("Start -> " + activity.OperationName);
activityListener.ActivityStopped += activity => Console.WriteLine("Stop -> " + activity.OperationName);
ActivitySource.AddActivityListener(activityListener);

var activity = new Activity("TestActivity");
listener.StartActivity(activity, null); // Output: Start -> TestActivity
listener.StopActivity(activity, null);  // Output: Stop -> TestActivity
```

**Comment by pakrym** [comment]
cc @tarekgh @noahfalk 

It feels strange that Activity started via diagnostic source leaks into ActivitySource world. As well as the DiagnosticListener being on from the get-go.

**Comment by tarekgh** [comment]
@AndreyTretyak 

- All activities are attached a ActivitySource object. The activities created using `new Activity(...)` is attached to ActivitySource with a name as empty string. This is intentional behavior to allow a way in ActivitySource to listen to activities created the old way. It is up to the listener to decide to listen to such activities or no. I am seeing the code `activityListener.ShouldListenTo += activitySource => true;` you are listening to all sources which of course include the source with empty name. It is up to listener to decide to include listening to such source to just filter it out. Also, in the event handling (for start and stop), it is easy to get `Activity.Source` and check the name to know if this is Activity created using `new Activity(...)`. 

@pakrym 
> It feels strange that Activity started via diagnostic source leaks into ActivitySource world. 

It is not leaking by default. it is the listener decision to listen to such activities. 

- regarding `DiagnosticListener.IsEnabled()` returning true all the time is not true. I even couldn't repro it. It looks when you tried that maybe there is some other component inside your process was enabling the listener. Please try that with a small app not doing any activity related operations and let's know.

**Comment by pakrym** [comment]
Thank you @tarekgh, makes sense.

**Comment by AndreyTretyak** [comment]
@tarekgh Thank you for the explanation. 
About `DiagnosticListener.IsEnabled()` it looks like it returns `true` when you are running it with the debugger attached,  running from the command line returns `false`.
