### ISSUE TITLE
[VS experience] Clean build in M.E.Logging fails perhaps due to timing issue but succeeds on second try

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#48711]
In Visual Studio, when solution file is up to date with all references, doing a clean build (build solution after clean or just rebuild), it gives random errors which is perhaps a timing issue. Because doing build for the second time completes successfully.

Tried this on Microsoft.Extensions.Logging solution, although I don't think it is specific to the logging solution.

Here's a part of the build log: (which will go away on the second successful build)
```
10>CSC : error CS0006: Metadata file 'C:\CodeHub\runtime\artifacts\bin\System.Text.Encodings.Web\netstandard2.0-Debug\System.Text.Encodings.Web.dll' could not be found
10>Done building project "System.Text.Json.csproj" -- FAILED.
10>CSC : error CS0006: Metadata file 'C:\CodeHub\runtime\artifacts\bin\System.Text.Encodings.Web\netcoreapp3.0-Debug\System.Text.Encodings.Web.dll' could not be found
10>Done building project "System.Text.Json.csproj" -- FAILED.
9>C:\Users\maariyan\.nuget\packages\microsoft.dotnet.apicompat\6.0.0-beta.21105.12\build\Microsoft.DotNet.ApiCompat.targets(51,5): error : ResolvedMatchingContract 'C:\CodeHub\runtime\artifacts\bin\System.Diagnostics.DiagnosticSource\ref\netstandard1.1-Debug\System.Diagnostics.DiagnosticSource.dll' did not exist.
9>Done building project "System.Diagnostics.DiagnosticSource.csproj" -- FAILED.
9>C:\Users\maariyan\.nuget\packages\microsoft.dotnet.apicompat\6.0.0-beta.21105.12\build\Microsoft.DotNet.ApiCompat.targets(51,5): error : ResolvedMatchingContract 'C:\CodeHub\runtime\artifacts\bin\System.Diagnostics.DiagnosticSource\ref\netstandard1.3-Debug\System.Diagnostics.DiagnosticSource.dll' did not exist.
9>Done building project "System.Diagnostics.DiagnosticSource.csproj" -- FAILED.
52>C:\Users\maariyan\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21105.12\build\Microsoft.DotNet.GenPartialFacadeSource.targets(30,5): error : Could not find a part of the path 'C:\CodeHub\runtime\artifacts\bin\System.Threading.AccessControl\ref\net461-Debug\System.Threading.AccessControl.dll'.
...
```

cc: @ViktorHofer @Anipik @safern

**Comment by ViktorHofer** [comment]
I finally now what's going on here. Visual Studio only builds projects that are referenced by the first active configuration in the TargetFrameworks list (i.e. `$(NetCoreAppCurrent)-windows`). It unfortunately skips project dependencies of other tfms which causes the dependency to not be built in time when the project depends on it. The build then succeeds then at a later point because the referenced project is then already built by VS.

This is a project-system / CPS bug and tracked via https://github.com/dotnet/project-system/issues/8117 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1524343.

**Comment by ViktorHofer** [comment]
The underlying issue in Visual Studio has been fixed recently. Please use VS 17.3 (internal preview at the moment) or above.
