### ISSUE TITLE
Support EC P192 on macOS

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#48723]
MacOS supports EC 192-bit keys (the NIST P-192, X9.62 prime192v1 variant) but currently we limit it to 256, 384, and 521.

I don't know right now how far back this support goes on macOS but it is present in macOS 10.15 and macOS 11.

I believe CNG and OpenSSL support this size EC key, so it might be worth bringing to macOS if it is feasible.

**Comment by vcsjones** [comment]
Seems like it has been there for as long as 256 as been there. https://developer.apple.com/documentation/security/seckeysizes/1398550-secp192r1

**Comment by vcsjones** [comment]
@bartonjs I guess before I poke too much at this, I should ask, is there interest in making P-192 work, and if so, to what extent? For example, the `ECDsa` (and ECDH) have `LegalKeySizes`. Would this get adjusted to 192, or would we treat P-192 more like another named curve like brain pool?

**Comment by bartonjs** [comment]
> is there interest in making P-192 work?

I don't think I've ever heard of anyone ask for secp192r1.

> Would this get adjusted to 192, or would we treat P-192 more like another named curve like brain pool?

If we wanted to support it at all, I think it'd just be as another manual fallback in the named curve lookup.  The `KeySizes` property is weird on the ECC types, I believe it's always fixed as { 256, 384, 521 }, no matter what the underlying provider has... because those are the only three magic numbers we allow in the setter (which then turn into secp{value}r1).

So... if you really wanted to do the work to hook it up as a named curve lookup, I guess I won't stop you.  Though I'd definitely rather see the one-shot crypto API additions get completed than this :smile:.

FWIW, I think I knew that secp192r1 was supported on macOS back when doing the initial Security.framework work, but since we didn't have it on Win7/Win8.1 and no one had asked for it specifically I didn't think it was worth the time to hook up and test.

**Comment by vcsjones** [comment]
> I don't think I've ever heard of anyone ask for secp192r1.

Yeah, I unearthed this since someone did ask if .NET supported 256k1 (Koblitz) on macOS (it does not) so I started poking to see what macOS does support. This is the only one I found that is not supported that we potentially could.

I'm fine closing this then.

> Though I'd definitely rather see the one-shot crypto API additions get completed than this 

Yeah, yeah. I need to get a draft up asap since I could use some input. It's "done" in so much that it works but some loose ends to tie up.
