### ISSUE TITLE
Dependency manifest (deps.json) has no entry for Private=false reference and additionalProbingPath doesn't work

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/runtime#48792]
Hello, 

I try to move app from net472 to net5 using Visual Studio 16.8.3 and netcore sdk 5.0.101. App use external libraries/apps (that are build under net472) and reference a couple of them. To avoid a several copy of references (`Private=false`) and to separate them from main app in folder them are placed in sub folder and app has a corresponding `probing` in the `app.config` to correctly load them in runtime. 

However, the similar results cannot be obtain in .net5:

Firstly, `Private=false` avoid generating an entry in `*.deps.json` for this references, that cause an error `System.IO.FileNotFoundException: 'Could not load file or assembly... The system cannot find the file specified.`

Secondly, (without `Private=false` and manually removing this assemblies from the root output folder) netcore runtime doesn't try to find assemblies in `additionalProbingPath` that was listed in  `runtimeconfig.template.json`, that cause an error `An assembly specified in the application dependencies manifest (ConsoleApp.deps.json) was not found`.

The simple project that shows behavior: [ConsoleApp.zip](https://github.com/dotnet/sdk/files/5981464/ConsoleApp.zip)

So is it a way to put external libraries in a sub directory without copying them to root folder and resolve them correctly in runtime? Besides, I hope it can be done without append to app dynamically resolving by handling `AssemblyLoadContext.Resolving`. 

If I miss something, please let me know about it.

**Comment by vitek-karas** [comment]
Currently there's no good way to modify the layout of the output of the build - as in put some files into subdirectories and so on. The main problem is that the SDK probably can't build an app like that (honestly we would need people from the SDK - in the dotnet/sdk repo).

The reason why the runtime will not load the file if it's not listed in `.deps.json`: It's by design. .NET Core runtime intentionally doesn't do any probing for assemblies (it's faster, simplifies the code and there are some reliability considerations for certain apps as well). The current design is basically: The app is produced by SDK, which knows exactly which assemblies the app relies on, and writes this information into `.deps.json` - the runtime blindly follows this.

`Private=false` is basically telling the SDK - build this project as well, but it's not part of the application. This is typically used for example for plugins and such. Meaning the application will explicitly load them from file (`AssemblyLoadContext.LoadFromAssemblyPath`).

This behavior is very different from .NET Framework. .NET Framework runtime does quite a bit of probing when resolving assemblies and will "try it's best to find it". .NET Core is the exact opposite, the runtime makes no effort to find the assembly outside of the pre-determined list. There are lot of extension points (like `AssemblyLoadContext.Resolving`) which can customize the runtime behavior, but they're almost all code-based (you have to write code to do that).

Out of curiosity: Why do you want some libraries to be in a sub-directory? I'm not questioning the motive, I'm just curious - it would help us deciding on potentially improving this in the future.

**Comment by GeorgeAlexandria** [comment]
@vitek-karas,
> honestly we would need people from the SDK - in the dotnet/sdk repo

Well, they are move this issue from dotnet sdk repo, where it was created firstly. So should we call them again?

I understood the main goals about loading references just that were listed in `.deps.json`. But wat about `additionalProbingPath` in `runtimeconfig.template.json` (without Private=false so the reference would be in `.deps`, and removing duplicate references from the root folder)? Seems that this case should work,  but it doesn't.

> Why do you want some libraries to be in a sub-directory?

As this libraries/apps is externally
* They have a some files structure (is not just a single or a few libraries) and them use this information (relative paths) to load some their assemblies and other files. So we cannot change this files structure to put the used libraries from us to our root folder in a flat list. If suppose that we can find a minimal set of libraries that we references and that don't use any other external libraries we probably must duplicate them to our root, because the other external apps, that we run at runtime, can use them, and we should not broke this usages. Such duplicating will increase the total output app size and we want to avoid it.
* We and external libraries/apps use a some count of similar system assemblies, assemblies from nuget, but with a different version. So if we try to merge the external libraries/apps root and our root we will have a version conflict between these "common" references and may have a couple runtime errors.

**Comment by vitek-karas** [comment]
`additionalProbingPath` - those are for the things in `.deps.json`. If the file is in `.deps.json` and it's not next to the app, the `additionalProbingPath` will be used to search for that file. This is actually done before the runtime starts - once it starts the set of assemblies it knows about (without customizations) is "Fixed".

Generally `additionalProbingPath` is something which was useful/necessary in .NET 2.* timeframe, in 3.0 there were changes made to the SDK which make it more of a fringe case. It's typically used with `--additional-deps` but that's a different story. Either of these is something I personally would love to eventually remove from the product (they are very tricky to use correctly).

The way you describe this is that you have .NET Core app which has a dependency on some .NET Framework components which are not really "part of the build". In this case things will likely be rough. For one thing, running .NET Framework assemblies in .NET Core might work, but it's not supported. The other problem is that SDK expects to know about everything in the app, which doesn't seem to be the case here.

Re sharing assemblies between apps: (Please correct me if I didn't understand the intent) If this is the goal, then we don't really have a good solution right now. There are some ways, but they're not very nice and generally are targetted at cases where you "own the machine" and not when you just try to build couple of apps which ship as a unit. The best solution is probably implementing the search logic in code in `AssemblyLoadContext.Resolving` or similar callback.

Re dependency version conflicts between libraries: Another example of a requirement which .NET Core currently doesn't solve. In fact if SDK understood all of your libraries it would probably enforce a single copy of each dependency anyway. The only runtime solution we have is loading the dependencies into isolated load contexts, since .NET Core runtime doesn't allow loading multiple versions of the same assembly into the same load context. (Note these are not AppDomains)

**Comment by GeorgeAlexandria** [comment]
> additionalProbingPath - those are for the things in .deps.json. If the file is in .deps.json and it's not next to the app, the additionalProbingPath will be used to search for that file

And this, as I wrote in issue as second point, doesn't work – reference is listed in `.deps.json`, assemblies doesn't exist in the root folder, but exists in a folder by `additionalProbingPath`, `runtimeconfig.json` includes `additionalProbingPath` from `runtimeconfig.template.json` but an error was raised at runtime.

> you have .NET Core app which has a dependency on some .NET Framework components which are not really "part of the build"

To be clear, this components are referenced directly from our app, and them are used from external apps that we also run at runtime.

**Comment by KylePreuss** [comment]
@vitek-karas I'm working on migrating a large repo with several applications supporting dynamically loaded plugins from a mixed net472 and netstandard2.0 (and some netcoreapp3.1) environment to net5.0 and net5.0-windows. There are multiple plugin assemblies contained in the main repo itself and these are all built to the *same* bin folder. This goes against typical .NET Core plugin recommendations (i.e. the sample plugin project which lends itself to OP's separate directory case) but my experience here may be relevant to the discussion on dependency version conflicts.

We have traditionally used some csproj rules including that all ProjectReferences have a `<Private>false</Private>` on them. This produced the first issues for me as our "built-in" (in-repo) plugins could no longer be dynamically loaded (after migrating from net472) via e.g. `Type.GetType()` with qualified type name and assembly name string. It turned out we had to delete the `.deps.json` for host app or explicitly reference the plugin, despite our plugins being in the same bin folder. Secondly, even after that hack -- if you will -- our plugins (again, in-repo ones) had issues at runtime when referencing things that should have been inherited from parent project. We ended up having to remove the `<Private>false</Private>` piece on all ProjectReferences in the plugin projects.

I went down the path of trying separate assembly load contexts but type unification is basically impossible because our plugins don't implement just a couple of interfaces defined in a "contract" assembly. They also leverage our dependency injection setup to extend all sorts of stuff. I basically had to add a bunch of direct references in the plugin projects' to things that might be used at runtime by a host project or project reference of the host project which was a game of whack-a-mole with critical runtime exceptions in this repo.

In the end, it was easiest to just add a hook into AssemblyLoadContext.Resolving on the default context to check if the assembly being requested is actually right next to the host app assembly on disk and if so, load it. Single assembly load context. Single version of dependencies. 

@GeorgeAlexandria this isn't at all the same as your setup so I apologize for the thread-jack if it is deemed as such but I hit some of the same issues as you and can testify that the hook mentioned here and in your OP definitely works in my case. However, it seems like you would want the separate load contexts since you stated these projects use different versions of other dependencies. You may be in for a tough battle with this type unification stuff if the separate assemblies interact/call-into each other or your regular projects.

**Comment by GeorgeAlexandria** [comment]
@KylePreuss,

> I hit some of the same issues as you and can testify that the hook mentioned here and in your OP definitely works in my case

If so can you try to check working the test project in the issue removing `Private=false` from project file and removing `ClassLibrary.dll` from root output folder before run `ConsoleApp.exe`?

> However, it seems like you would want the separate load contexts since you stated these projects use different versions of other dependencies.

Presumably, it may arise in the future, but currently it will enough for me to reference external components, put them to subdirectory and do not put a copy of them to the root folder (if such case will work of course)

**Comment by KylePreuss** [comment]
@GeorgeAlexandria I just setup a sample project with a console program (net5.0) and a class library (net5.0). I built the console project to a bin/Debug folder and the class library to bin/Debug/External. The library does not reference the console project, but the console project does reference the library via a ProjectReference. By including the `<Private>false</Private`, the library does not get copied to /bin/Debug (so no duplicate assemblies) and thus fails to load at runtime due to the entries written in .deps.json. See screenshot: 
![ex1](https://user-images.githubusercontent.com/7189991/111625912-c6e1ee80-87c3-11eb-943c-f7268525e842.png)
 Even if I grab the files from /bin/Debug/External and drop them in /bin/Debug and run the console app again, it still fails to load them (due to entries in `.deps.json` from the `<Private>false</Private>`). Moving on to your question...

Now when I change the console app project to remove the `<Private>false</Private>` element on the project reference to library and clean/rebuild, the library output is copied to bin/Debug (thus duplicated on disk since it also resides in bin/Debug/External) and the program runs fine. But if I delete the library artifacts from bin/Debug as you suggest it fails to run. It is expecting them to be in bin/Debug.

I went ahead and tried hooking into AssemblyLoadContext.Resolving for both of the previous cases (using `<Private>false</Private>` *and* not using that + deleting from regular bin/Debug after libraries are copied there). I used something simple:
```
    private const string _relativePathToLibraries = "External";
    private static void Main( string[] args )
    {
      Console.WriteLine( "Hello World!" );

      AssemblyLoadContext.Default.Resolving += ( context, name ) =>
      {
        var binPath = Assembly.GetCallingAssembly().Location;
        var assemblyPath = Path.Combine( binPath, _relativePathToLibraries, $"{name}.dll" );
        if ( !File.Exists( assemblyPath ) )
          return null;
        return context.LoadFromAssemblyPath( assemblyPath );
      };

      var c1 = new Class1();

      var c2 = new Class2();

      Debug.Assert( c1 != null && c2 != null );
    }
```

However, it looks like the runtime doesn't get that far. The program is not loaded and my handler is not registered. It appears if you reference via the csproj, you cannot specify your own assembly resolution at runtime. It has to be static. Thus I suppose the `additionalProbingPath` is indeed the path you would need to take but -- as you stated -- that doesn't appear to work either.

Again my use case mostly revolves around dynamically loaded assemblies and thus I can specify resolution behavior via the `AssemblyLoadContext.Default` hook but in your case I don't think you can.

**Comment by vitek-karas** [comment]
@GeorgeAlexandria I'm sorry I missed the part about `additionalProbingPaths` not working in the case where the file is listed in `.deps.json` but missing on disk.

### Additional probing paths
`additionalProbingPaths` don't really work the way you would expect - they're basically designed for NuGet packages (long history, I don't like it, but for now we're stuck with it). For example, let's say I have a classlib called `Lib`, version `1.0` and I include it in `deps.json` but delete it from the output. And then I have `additionalProbingPath` set to a directory `C:\probe`.

In this case the host will look for file `C:\probe\Lib\1.0\Lib.dll` - because that's how NuGet packages are placed on disk.

So while technically possible to use, I would not recommend using `additionalProbingPaths` because it's just very cumbersome. There's also no good way to tell it "subdirectory of the app". It will let you specify a relative path, but it's resolved based on the current directory, not the app directory. So it can point to random places depending on how the app is started.

### Assembly resolution in code
@KylePreuss the reason why it doesn't work is that you're using the library from `Main`. The way this works is that `Main` is loaded and JITed - and in order to JIT it, all of the referenced types/assemblies must be resolved BEFORE it gets executed. So the custom resolution logic is not in place when that happens.

The way to "Fix" that is to setup the assembly resolution and put everything else into a different method (preferably marked as no-inlining), that way the assembly resolution setup is executed before the code which needs it is JITed.

For example this works:
```C#
    class Program
    {
        static void Main(string[] args)
        {
            AssemblyLoadContext.Default.Resolving += (context, name) =>
            {
                return context.LoadFromAssemblyPath(Path.Combine(AppContext.BaseDirectory, "sub", name.Name + ".dll"));
            };

            Console.WriteLine("Hello World!");
            DoAdditionalThings();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void DoAdditionalThings ()
        {
           Library.Do();
        }
    }
```

For the case where you want some dependencies in a subfolder I would go with the code solution. If you own the calling app and the subfolder is fixed (doesn't change per deployment) the code solution is really no different from config solution - it's basically just written in different language. It's also way more flexible and easier to debug :-).

**Comment by KylePreuss** [comment]
@vitek-karas Thanks for the explanation and example use of `MethodImplOptions.NoInlining`.

To bring this full circle w.r.t. plugin architectures if anyone lands on this issue the same way I did: @GeorgeAlexandria you could similarly do this *without* a reference to the external library inside your console project if you were able to do assembly resolution at runtime and instantiate via reflection (e.g. the external assembly is a plugin and you know from a config file etc. the type name and assembly name). e.g. You could remove the reference to ClassLibrary1 in the following example and then use something like this to load the contract/plugin types:
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            AssemblyLoadContext.Default.Resolving += (context, name) =>
            {
                return context.LoadFromAssemblyPath(Path.Combine(AppContext.BaseDirectory, "sub", name.Name + ".dll"));
            };

            Console.WriteLine("Hello World!");
            DoAdditionalThings();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void DoAdditionalThings ()
        {
          // TODO: Get actual string from somewhere else
           var t1 = Type.GetType( "ClassLibrary1.Class1, ClassLibrary1" );
           var c1 = Activator.CreateInstance( t1 );
           c1.DoStuff();
        }
    }
```

**Comment by GeorgeAlexandria** [comment]
@vitek-karas,
> additionalProbingPaths don't really work the way you would expect - they're basically designed for NuGet packages

It's not obvious by `additionalProbingPaths` name or by something else that `additionalProbingPaths` correctly works only for NuGet packages and doesn't work for other things...

> long history, I don't like it, but for now we're stuck with it

Seems that `additionalProbingPath` is a kind of workaround and is not designed so good.

@vitek-karas,
> you could similarly do this without a reference to the external library inside your console project if you were able to do assembly resolution at runtime and instantiate via reflection

More easy way it's use `Private=false` reference and dynamically resolve assembly at runtime, without any instantiation via reflection.

I had hoped that it can be done without dynamically resolving at runtime, sad that it cannot be done – close issue.

**Comment by vitek-karas** [comment]
@GeorgeAlexandria I'm just curious why you would prefer some kind of "configuration" solution over the "code solution". It will help us make better decisions about potential future improvements.

**Comment by AraHaan** [comment]
I also have a similar issue, however my plugins in my application are in a subfolder of the root application, and each dependency of said plugin are in the root folder of the application (in my case in with the exe file itself), however trying to load each plugin into their own ``AssemblyLoadContext`` would result in it not being "found" (well duh because it's not in the folder of the plugins but of the folder right above it.

![image](https://user-images.githubusercontent.com/15173749/111687563-c9166e00-8800-11eb-886d-b2a872004134.png)

And yes the plugins are ironically under ``plugins``.

**Comment by vitek-karas** [comment]
Side note: GAC doesn't exist in .NET Core - so I would advise against solutions using it. And as you mention it has versioning problems on its own as well.

If you create the `AssemblyLoadContext` for the plugin, you can customize the `Load` method and teach it to look in the parent folder if you need. I obviously don't know the layout and purpose of these assemblies, but with custom load context you have full control over the assembly resolution in it.

**Comment by AraHaan** [comment]
Thanks, I done this too (I decided to extend it for native code as well too)

```cs
    /// <inheritdoc/>
    public class PluginLoadContext : AssemblyLoadContext
    {
        private readonly AssemblyDependencyResolver resolver;

        /// <summary>
        /// Initializes a new instance of the <see cref="PluginLoadContext"/> class.
        /// </summary>
        /// <param name="name">The name of the load context.</param>
        /// <param name="pluginPath">The path the the plugins.</param>
        public PluginLoadContext(string name, string pluginPath)
            : base(name, true)
            => this.resolver = new AssemblyDependencyResolver(pluginPath);

        /// <inheritdoc/>
        protected override Assembly Load(AssemblyName assemblyName)
        {
            var assemblyPath = this.resolver.ResolveAssemblyToPath(assemblyName);
            return assemblyPath != null
                ? this.LoadFromAssemblyPath(assemblyPath)
                : !File.Exists($"{Assembly.GetExecutingAssembly().Location}{assemblyName.Name}.dll")
                ? null
                : this.LoadFromAssemblyPath($"{Assembly.GetExecutingAssembly().Location}{assemblyName.Name}.dll");
        }

        /// <inheritdoc/>
        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            var libraryPath = this.resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            return libraryPath != null
                ? this.LoadUnmanagedDllFromPath(libraryPath)
                : !File.Exists($"{Assembly.GetExecutingAssembly().Location}{unmanagedDllName}.dll")
                ? IntPtr.Zero
                : this.LoadUnmanagedDllFromPath($"{Assembly.GetExecutingAssembly().Location}{unmanagedDllName}.dll");
        }
    }
```

**Comment by vitek-karas** [comment]
This looks really weird: `{Assembly.GetExecutingAssembly().Location}{assemblyName.Name}.dll`
It will probably return something like `App.dllPlugin.dll`.
But otherwise this should work. 

Side note: I personally would stay away from `GetExecutingAssembly` as that may change if you move the code around. Maybe something like `AppContext.BaseDirectory` would be better.
(There's also the fact the `Assembly.Location` doesn't work in single-file apps, so if you ever wanted to use this in single-file app it would likely break).

**Comment by AraHaan** [comment]
Oh ye you are right I probably should wrap ``Assembly.GetExecutingAssembly().Location`` inside a call to ``Path.GetDirectoryName``.

``AppContext.BaseDirectory `` is the path where the apphost exe file is (in this case it's ``Els_kom.exe``)?
