### ISSUE TITLE
Json Deserialize fails silently when consuming JsonContent.Create output

### ISSUE THREAD

**Issue by DuncanStone** [dotnet/runtime#48816]
### Describe the bug
One type fails to deserialize after being transmitted to an aspnetcore rest api. Every property of the deserialised object is simply set to the default for that type. 

The biggest problem here is that it fails SILENTLY. It took me ages to find out what was wrong and now my database is spammed full of these invalid objects.

To illustrate (and workaround) the issue I created the following helper function:

```
public static async Task<T> VerifyJson<T>(HttpRequest request, T recieved, ILogger logger)
{
	ReadResult result = await request.BodyReader.ReadAsync();
	string json = Encoding.UTF8.GetString(result.Buffer);

	T deserialised = System.Text.Json.JsonSerializer.Deserialize<T>(json);

	JObject requestJson = JObject.Parse(json);
	JObject recievedJson = JObject.Parse(JsonConvert.SerializeObject(recieved));

	bool same = JToken.DeepEquals(requestJson, recievedJson);
	if (!same)
	{
		logger.LogError($"Asp json deserializer screwed up again: deserialised \n{requestJson} \nas \n {recievedJson}");
		return JsonConvert.DeserializeObject<T>(json);
	}
	return recieved;
}
```

which I call in each controller at the start of any post methods.
An example output is: 

oneAPI.Controllers.SessionController: Error: Asp json deserializer screwed up again: deserialised 
{
  "sessionId": "6568c54d-dd3f-48d6-bd99-73f0aca21b19",
  "title": "TestSession",
  "index": 0,
  "publishedStreamUrl": null,
  "created": "2021-02-25T21:22:33.2582807Z",
  "uploaded": "0001-01-01T00:00:00",
  "lastModified": "2021-02-25T21:22:33.2583459Z",
  "version": null,
  "projectId": "10df252d-e977-4a43-80c1-b5ea24875492"
} 
as 
 {
  "SessionId": "00000000-0000-0000-0000-000000000000",
  "Title": null,
  "Index": 0,
  "PublishedStreamUrl": null,
  "Created": "0001-01-01T00:00:00",
  "Uploaded": "0001-01-01T00:00:00",
  "LastModified": "0001-01-01T00:00:00",
  "Version": null,
  "ProjectId": "00000000-0000-0000-0000-000000000000"
}

### To Reproduce
https://github.com/DuncanStone/JsonBugReport

I am able to reproduce this in my actual app without JsonContent.Create instead using 
string json = JsonConvert.SerializeObject(session);
StringContent data = new StringContent(json, Encoding.UTF8, "application/json");

but this did not repro in the test project.

### Exceptions (if any)
NO, that is the problem

### Further technical details
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by eiriktsarpalis** [comment]
The issue is due to the fact that `JsonContent` and `JsonSerializer` apply different sets of [serialization defaults](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializerdefaults?view=net-5.0): `JsonContent`  uses `JsonSerializerDefaults.Web` and `JsonSerializer` uses `JsonSerializerDefaults.General`. More specifically your properties end up being ignored because `JsonSerializer` by default does not convert property names to camelCase.

You need to configure your deserializer to use the web defaults, in your case:
```csharp
var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
var deserialised = JsonSerializer.Deserialize<Session>(json, options);
```
and deserialization should work as expected.

**Comment by eiriktsarpalis** [comment]
Taken from #56036

> I reported this already #48816 but the report was obviously too detailed and the responding developer got confused and simply added a workaround to make the reproduction I had posted stop being a valid reproduction of the issue.
> 
> The issue is that when the automatic system for interpreting post data gets camel case variable names it ignores the post data, generates empty, fake data to replace it, and then continues as though nothing happened without any warnings or errors.
> 
> In this situation asp should return an http error (specifically 400 Bad Request) because it can't read the data object required by the function. Ideally it could even say that the input casing is wrong if that is the only reason the parser fails.
> 
> In the case of the reproduction it should just throw an exception.

**Comment by eiriktsarpalis** [comment]
> The issue is that when the automatic system for interpreting post data gets camel case variable names it ignores the post data, generates empty, fake data to replace it, and then continues as though nothing happened without any warnings or errors.

This is by design. The serializer is not "generating empty, fake data", it is simply not populating members not matching any properties in the underlying JSON. The data you are seeing in the deserialization are in fact the `default` values for `Guid`, `int` and `DateTime`: NB these are not values inserted arbitrarily by the serializer, they are an artifact of how the properties of your `Session` class are being populated by the default constructor. This can be seen via the following example:
```csharp
public class MyClass
{
    public MyClass()
    {
        A = Guid.Parse("11111111-1111-1111-1111-111111111111");
        B = "string";
        C = 42;
    }

    public Guid A { get; set; }
    public string B { get; set; }
    public int C { get; set; }
}

JsonSerializer.Deserialize<MyClass>("{}"); // properties have non-default values.
```

> In this situation asp should return an http error (specifically 400 Bad Request) because it can't read the data object required by the function. Ideally it could even say that the input casing is wrong if that is the only reason the parser fails.

This concerns the aspnet layer and not the serializer. Have you considered using the [model validation feature](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0) offered in asp.net core? This would be the recommended way for detecting missing properties.

Moreover, my feedback from https://github.com/dotnet/runtime/issues/48816#issuecomment-811883804 still holds. Your application should ensure that matching `JsonSerializerDefaults` are applied across the board in order to avoid issues like the one you are reporting.
