### ISSUE TITLE
Add support for Decimal Floating Point arithmetic

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [dotnet/runtime#48834]
### Description
* There are too many problems with the IEEE 754 standard, especially when it comes to dealing with anything related to finances.
* The end goal should be to eventually phase out Binary Floating Point (but not immediately). The sooner a widely used programming language or framework adopts a Decimal-based alternative, the better.
* I am nor great at explanations, so I will instead link to a recorded presentation and a github repository, both by Douglas Crockford.

### Configuration
* This is an issue endemic to all modern computing languages and CPU architectures.

### Other information
* Hardware acceleration for Decimal Floating Point arithmetic will become widely available once there is sufficient demand.
* Douglas Crockford's DEC64 format can currently be efficiently implemented in software.

### Presentation and repository by Douglas Crockford:
* You Can Count On Numbers — SSVC 2019: https://youtu.be/ZgETMYsmmtU
* DEC64 format/library: https://github.com/douglascrockford/DEC64

**Comment by tannergooding** [comment]
Thanks for taking the time to open this issue!
> There are too many problems with the IEEE 754 standard, especially when it comes to dealing with anything related to finances.

I do agree that the binary floating-point formats defined by IEEE 754 have some issues that prevent their use in certain scenarios, such as finances.

However, we expose the `System.Decimal` type as something that does fulfill this need and IEEE 754 defines its own decimal floating-point formats that could be expose in the future to further address customer needs.

> The end goal should be to eventually phase out Binary Floating Point (but not immediately). The sooner a widely used programming language or framework adopts a Decimal-based alternative, the better.

The IEEE 754 binary floating-point types are the industry standard for CPUs, GPUs, platform ABIs, and programming languages.

Because of these standards, our binary floating-point functionality is expected to stay in place unless significant evidence emerges that the industry as a whole is standardizing on something different. Only with such a signal would the libraries, runtime, and languages changes be justified.

Even languages like C/C++ have not made significant effort to support `decimal floating-point types` beyond optional appendices for the IEEE 754 decimal types.

--------------

If there is more interest in the area, I would request users express that desire and would suggest prototyping the support in a 3rd party library to see how much use it can garner first.

**Comment by Clockwork-Muse** [comment]
> Hardware acceleration for Decimal Floating Point arithmetic will become widely available once there is sufficient demand.

It's not common on consumer hardware, [but does exist on some platforms](https://stackoverflow.com/q/1447215/812837).

Part of the problem is that there's literally no demand from the average (or even most super) user.  Non-programmers don't care because they don't need to know that to use a program.  Most programmers don't care because the numbers they work with don't need to be accurate like that; for most of those who do, the existing software types are good enough.
