### ISSUE TITLE
Question: How to elevate at runtime

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/runtime#48856]
Hi,

I would like to know how to elevate my process at runtime. I don't want to use an application manifest or restart the application.

The reason I want to elevate at runtime is because in my application, I copy files to a user selected path. When this path is protected by admin rights, I want to prompt the user the same way that the application manifest does at runtime. But, I still want to allow non-admin users to use my application but I will restrict the user to non-protected path.

I saw this [answer](https://stackoverflow.com/a/8832162) on StackOverflow which is exactly what I needed but the attribute PrincipalPermission is obsolete in .Net Core.

Thank you.

**Comment by NN---** [comment]
Windows doesn’t allow process to change its integrity level during runtime.
A common solution is spawning an additional elevated process and ask it to perform the task requiring elevation.

**Comment by danmoseley** [comment]
@GrabYourPitchforks did `[PrincipalPermission(SecurityAction.Demand, Role = @"BUILTIN\Administrators")]` do anything other than verify the current process was running in the context of a user that was a member of that group? Ie it didn't change capabilities.

**Comment by KalleOlaviNiemitalo** [comment]
I remember using PrincipalPermissionAttribute in a WCF service over named pipes, for verifying that the client was elevated — and then having to replace it with something else because BUILTIN\Administrators did not match on a localized version of Windows.

**Comment by SimonCropp** [comment]
@joperezr is really planned for the future? wouldnt this require changes in windows to allow elevating a current process?

**Comment by joperezr** [comment]
You are right that this would require changes in Windows, but do note that doesn't really prevent for features to eventually get added. Not particularly talking about this specific one, but we sometimes mark issues as future to see how much traction they get to see what features our contributors care about the most.

All that said, this one actually has a fundamental security concern (it is ok to allow processes to execute as lower privileged but not the other way around) which does make it so that it is very unlikely for something like this ever to be added, so I'll go ahead and close it for now instead.

**Comment by ThomasGoulet73** [comment]
To be honest, I totally forgot about this issue and solved my issue using Pipes. I just invoke the same process with elevation, which prompts the user, and run the code that needs to be elevated. It's not perfect but it does the job.

**Comment by GrabYourPitchforks** [comment]
> I just invoke the same process with elevation, which prompts the user, and run the code that needs to be elevated. It's not perfect but it does the job.

That's how this is normally done.
