### ISSUE TITLE
Loop opts should not be recomputing pred lists from scratch

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#49030]
Several loop opts end up calling `fgUpdateChangedFlowGraph` when done, and this calls `fgComputePreds`, leaking previous pred lists and losing the profile weights carefully calculated earlier.

This seems wrong-headed; I think those optimizations should maintain pred lists and not rebuild them.

Removing the call to `fgComputePreds` shows a number of places in loop opts where pred lists are not properly updated, and more downstream failures from places unknown where `BBF_JMP_TARGET` is not properly set, so cleaning this up may be nontrivial.

category:cq
theme:loop-opt
skill-level:expert
cost:medium
impact:medium

**Comment by AndyAyersMS** [comment]
See notes in #48850 for some context.

**Comment by AndyAyersMS** [comment]
cc @BruceForstall

**Comment by BruceForstall** [comment]
We used to always need to rebuild pred lists after renumbering blocks due to pred list ordering being dependent on block number, so presumably phases knew they could be sloppy and things would get cleaned up later. But with the new `ensurePredListOrder()/reorderPredList()`, that's no longer required, as renumbering also keeps preds lists properly ordered.

Maybe we need a pred list checker that runs `fgComputePreds` but doesn't update the IR, and compares the results against the existing flowgraph (does such a thing exist already?), then `fgUpdateChangedFlowGraph` can call the checker to verify that no preds need to be updated, and if that check fails, we know which phase caused the problem.

**Comment by AndyAyersMS** [comment]
I get post-phase check failures about missing preds if I remove the call to `fgComputePreds` so I think the current checking may be sufficient?

The missing jump target flags might be harder to track down; it's not clear if we have agreement about when the jump target bit needs to be set, and we don't seem to check this post phase. It is checked in codegen.

**Comment by BruceForstall** [comment]
I'm thinking we should get rid of `BBF_JMP_TARGET` entirely, and replace it's use by `BBF_HAS_LABEL` for marking blocks that need labels. Then, add a pass over the blocks just before codegen that sets `BBF_HAS_LABEL` on all necessary blocks, like `genPrepForEHCodegen` does for EH constructs. Then, we wouldn't need to set and maintain the `BBF_JMP_TARGET` throughout compilation. We may lose a couple uninteresting asserts, but would greatly simplify block maintenance.

**Comment by AndyAyersMS** [comment]
Sounds good to me.

**Comment by BruceForstall** [comment]
`BBF_JMP_TARGET` was removed with https://github.com/dotnet/runtime/pull/51208

**Comment by JulieLeeMSFT** [comment]
@BruceForstall Please link this issue with your Loop Optimization user story https://github.com/dotnet/runtime/issues/43549.

**Comment by BruceForstall** [comment]
Remaining phases calling `fgUpdateChangedFlowGraph` that recompute preds lists:
- optFindNaturalLoops
- optUnrollLoops
- fgInsertGCPolls
