### ISSUE TITLE
Stale dotnet process after exception

### ISSUE THREAD

**Issue by ldy985** [dotnet/runtime#49166]
### Description
I have a problem on Windows where a simple application that just throws an exception, will never terminate. It remains in the background showing as "Suspended" in Process Explorer from Sysinternals. This often causes msbuild to fail due to locked files.

I have been unable to narrow down why the processes never exit.

See example program below:
```csharp
        static void Main(string[] args)
        {
            throw new Exception();
        }
```

### Configuration
I am running Windows 10 x64 (19042.844), but have a few friends experiencing the same issue.
The issue is present in dotnet 5.0.102, 5.0.200 and 6.x preview.

### Regression?
This issue arose somewhere between dotnet 2.1 and now

### Other information
I have a dump of one of the suspended processes here: https://gofile.io/d/JIEo5i 
Below is a picture of stale processes, after they have thrown an exception:
![image](https://user-images.githubusercontent.com/5678199/110026295-c3188b80-7d30-11eb-886a-108ee7a54152.png)

**Comment by jkotas** [comment]
@dotnet/dotnet-diag Can Windows crash reporting be keeping crashes processes alive like this?

**Comment by ldy985** [comment]
I have just tried to disable the Windows error reporting service. The same program as before no longer cause the hanging processes. 

Is this an issue with dotnet or Windows Error reporting?

**Comment by noahfalk** [comment]
> Is this an issue with dotnet, Windows Error reporting or something else?

I don't think we have enough information to say yet as there is some dotnet specific logic running within WER. If you repro the problem again you could look for a WerFault.exe process which is the process that should be collecting the crash report. Capturing a several dumps of WerFault spaced a few seconds apart could give us more information why it wasn't completing its work.

**Comment by ldy985** [comment]
I was unable to find WerFault.exe but instead found wermgr.exe. I have dumped it a few times here: https://gofile.io/d/yUrap9
hope it provides anything.

**Comment by tommcdon** [comment]
@ldy985 Thank you for the links!  

Unfortunately the first dump did not seem to valid (perhaps because the app is shutting down?), and I was unable to open it in both VS and windbg as it seems to be missing thread information.  Can you try attaching a debugger to the one of the suspended processes with a debugger and save a Full Heap Dump?  For example, from Visual Studio, you can choose Debug-\>"Save Dump As".  If you cannot attach, you can try non-invasive attach with [windbg ](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/noninvasive-debugging--user-mode-) and use ".dump /ma \<path to dump\>" to save a dump.  

To help rule out other possibilities, can you try checking for automated dump/debugger related reg keys - https://docs.microsoft.com/en-us/windows/win32/debug/configuring-automatic-debugging? Also since you are using sysinternals procexplorer, can you look to see if there is a virus scanner or some other processes holding handles on to the process?

**Comment by ldy985** [comment]
@tommcdon Thanks for having a look at my issue!

Process Explorer shows no active Threads or handles when looking at the suspended dotnet application. When trying to attach directly i get the following message: 
![image](https://user-images.githubusercontent.com/5678199/110448457-83033100-80c1-11eb-999c-e0fcaa47c39b.png)

I tried to install windbg preview from the MS store, when attaching directly i get this error NTSTATUS 0xC0000001 and when attaching non-invasively: Win32 error 0n5

Just to clarify the execution flow is as follows:

Test Application starts -> Test Applications throws Exception -> Test Application exits with code -532462766 -> Test Application appears suspended in process explorer and wermgr.exe starts running. -> wermgr.exe exits -> Test Application is still suspended.

I have attached a dump of the debug settings in my registry below:
[Registry.zip](https://github.com/dotnet/runtime/files/6107434/Registry.zip)

I will try to create a fresh windows 10 VM to ensure its not a software conflict.

**Comment by jeremycollake** [comment]
I am the author of Process Lasso.

I can confirm that some interaction between WER and Process Lasso results in these zombie WER processes.

When Process Lasso exits, these stale processes complete their termination.

Process Lasso does keep a handle open to all running processes. This is done to detect termination, and to limit OpenProcess calls since some security software may evaluate and log these, resulting in excessive load.

Although it seems bizarre that WER would be waiting on all handles to its snapshot processes to close, that is my first guess as to the cause.

I'll be digging deeper into this, so will update with a more precise diagnosis.

**Comment by jeremycollake** [comment]
As of Process Lasso v10.0.1.5 beta, handles to these WER snapshot processes are no longer kept open.

This appears to have resolved this issue.

In any event, this issue was not related to the .NET runtime, so can be closed here.

**Comment by sdmaclea** [comment]
Thanks @jeremycollake

**Comment by ldy985** [comment]
Thanks everyone for helping.
