### ISSUE TITLE
Support TLS 1.3 Early Data (0-RTT) with SslStream

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#49274]
## Background and Motivation

TLS 1.3 brings with it "Early Data", also called 0-RTT. Because QUIC (and HTTP/3) requires TLS 1.3, this also affects that.

Early Data elides the latency hit caused by the TLS handshake by allowing data to optimistically be sent immediately following the TLS ClientHello, without waiting for completion of the handshake from the peer. This enables TLS 1.3 to be just as quick (latency-wise) as plain TCP.

## API Proposal

None yet; this needs a lot of prototyping.

## Risks

Early Data is a very serious security risk as it allows trivial replay attacks for anything sent as early data (once the handshake is complete, this vulnerability goes away). Early Data also defeats Perfect Forward Secrecy, also only for pre-handshake data.

In the context of HTTP, this means an adversary can cause any early requests to be repeated. To defeat this, the server application must ensure non-idempotent requests in early data will get a response of [425 Too Early](https://tools.ietf.org/html/rfc8470#section-5.2). @Tratcher this would probably need some sort of `HttpContext.Request.IsEarlyData` flag.

As such, this must be off by default, use a scary API name, and we should not implement this without an end-to-end plan on how to make customers successful.

CC @wfurt @blowdart

**Comment by Tratcher** [comment]
> In the context of HTTP, this means an adversary can cause any early requests to be repeated. To defeat this, the server application must ensure non-idempotent requests in early data will get a response of [425 Too Early](https://tools.ietf.org/html/rfc8470#section-5.2). @Tratcher this would probably need some sort of `HttpContext.Request.IsEarlyData` flag.

The client has a similar concern. HttpClient decides when to make connections so a user won't know if their request might be sent as early data. That means HttpClient must take some efforts not to send early data for non-idempotent requests.

> Early Data also defeats Perfect Forward Secrecy, also only for pre-handshake data.

That implies the client must never send credentials on an early-data request.

**Comment by geoffkizer** [comment]
Before we spend any significant time on this, we should probably discuss with security experts to make sure they wouldn't have any issues with this.

I'm also not clear re support in underlying libraries -- OpenSsl, schannel. Do you know?

I do think msquic supports this.

**Comment by blowdart** [comment]
Of course I have issues :)

* Are customers asking for this specifically? If not, don't do it. It's too dangerous.

* If customers are asking for it has any research been done into why they're asking? If not, do the research and don't do it unless there's a very good reason, with a very large customer base.

At a minimum, to start making it safe, we'll need to

1) Have the server decide if it wants to enable it, and what type of connections it wants to enable it for. For example, if Kestrel sees a GET request, with no query parameters it may be safe to accept 0-RTT on that one request (we of course have to assume that developers do realise that GET requests are idempotent. From experience a lot of them don't, or assume that it means "read-only", which it doesn't.) 
2) Have a mechanism to make sure that there's a time limit on replays (and that needs to synchronize across multiple servers. Good luck with that, because now you need a shared state mechanism), 
3) Have a max size on the request (finally an easy one).

We do not tend to implement parts of specs that are dangerous and take major effort from both ourselves and our customers to secure. 0RTT seems like one of those parts.

cc @GrabYourPitchforks

**Comment by wfurt** [comment]
let's close it unless we have compelling reason to proceed.
