### ISSUE TITLE
Add a notification mechanism for EnC and HotReload

### ISSUE THREAD

**Issue by StephaneDelcroix** [dotnet/runtime#49361]
## Background and Motivation

One of the key work stream for the success of HotReload is a feedback mechanism so frameworks and 3rd party libraries knows that a type was hot reloaded and can decide to replace a live instance, invalidate a cache, refresh a binding, etc...

The proposed API isn't prescriptive, and other feedback mechanisms can be discussed, but it's quite important that the API is part of the BCL and the feature is supported by the runtime, so all frameworks will benefits from it, and it'll work in all HotReload scenarios (debugger and botnet watch).

This proposal was first mentioned in #45689, 2nd bullet of the 'Related API changes' section

## Proposed API

```C#
namespace System.Reflection.Metadata
{
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class  ApplyUpdateNotificationAttribute : Attribute
    {
        /// <summary>
        /// HotReload notification API
        ///
        /// Declares which static method to execute when a HotReload delta is applied. The hot reload agent is responsible
        /// for scanning assemblies at load, and register the notifiers.
        ///
        /// notifier signature should look like: internal static void BeforeUpdate(Type type) and/or AfterUpdate(Type type).
        /// </summary>
        /// <param name="type">The Type on which the notifier is defined</param>
        /// <exception cref="ArgumentNullException">type or notifier are null</exception>
        /// <exception cref="...">type or notifier does not exist, or notifier isn't static, or doesn't have the right signature</exception>
        public ApplyUpdateNotificationAttribute (Type type)   
    }
}
```

## Usage Examples

This is how a UI Framework could reload a view when an HotReload change is applied

```C#
[assembly:ApplyUpdateNotification(typeof(HotReloadExtensions)]

namespace MyUIFramework
{
    public class View {
        public View Parent {get; set;} // setting the Parent sets the Child on the Parent view

        public View ()
        {
            HotReloadExtensions.RegisterInstance(this);
        }
    }

    internal static class HotReloadExtensions
    {
        // Keep weakRef of created views in a cache
        public static void RegisterInstance(View view) {...}

        // retrieve values from the cache
        static IEnumerable<View> GetViewsOfType(Type type) {...}

        // the notifier, declared by the attribute
        public static void AfterUpdate(Type type)
        {
            foreach (var oldinstance in GetViewsOfType(type)
            {
            }
        }
    }
}
```

## Alternative Designs

1. event: creating an event has the problem of registration, mainly for 3rd party libraries
2. implement this capability at the framework level. repetitive work, and the runtime would still have to implement it's own mechanism to invalide its caches (I'm thinking ReflectionCache, ....) 
3. whatever applies the change could also trigger the notification, but that would require injecting some shared code in all platforms supporting EnC/HR

## Risks

Unknown at this time

**Comment by stephentoub** [comment]
> The runtime is responsible for scanning assemblies at load, and register the notifiers

If it's the runtime (i.e. corelib) that's responsible for notifying, then I think it should just be an event code can subscribe to rather than a dynamic reflection-based mechanism, likely right next to ApplyUpdate, e.g. UpdateApplied.

If we want to use a reflection-based scheme looking for attributes, it doesn't need to be the runtime that does this: it can just be the hot reload component injected into the process.

> EnCNotificationAttribute

EnC is an implementation detail on coreclr, e.g. mono uses MBR.  We should tie the naming here to the same naming used for the other public surface area, e.g. ApplyUpdate.

> `Guid notifierId, IEnumerable<Guid> runBefore`

Why is this necessary at this level?  If there are multiple components that have a relationship, why can't just one of them register and then be responsible for invoking whatever else needs to be invoked in whatever order is important?

**Comment by stephentoub** [comment]
> and the runtime would still have to implement it's own mechanism to invalide its caches

This part still needs to be debated.  @jkotas has expressed strong concerns against doing this.

**Comment by jkotas** [comment]
> attributes

Enumerating all types in all assemblies to find items marked with a specific attribute is well know performance anti pattern. What about having assembly-level attribute that specifies the EnC manager(s) in the given assembly? The EnC manager can then just look for the assembly-level attributes to find all eligible participants that is quite cheap.

> A component can register with the event from a ModuleInitializer if desired.

I like the declarative scheme better than registering upfront. The declarative scheme is more pay-for-play (e.g. wrt linkability) without additional work.

Also, the declarative scheme allows assemblies compiled against netstadard to participate, without re-targeting for .NET 6+. I am not sure whether this is important.

> If there are multiple components that have a relationship, why can't just one of them register and then be responsible for invoking whatever else needs to be invoked

How does the lower-level component know whether there is going to be some higher-level component to flush it, or whether it is on its own and it should be responsible to itself? I think there will need to be some sort of ordering applied by the EnC manager.

> runtime invalide its caches

I would be fine with CoreLib reflection participating in the updating scheme as long as it is pay-for-play, like the assembly-level attribute that specifies the EnC manager(s) in the given assembly that I have suggested.

Also, do we need an API that returns true when code updates are allowed? This API would return true when the environment variable that enables code updatability is set. I expect that some components will want to switch to a different mode of operation to support updateability.

**Comment by jkotas** [comment]
>  IEnumerable<Guid> runBefore

I do not think you can have `IEnumerable`<Guid>` in a attribute. 

I think the attribute should just have the local update manager type name. The types of notifications and other details can be inferred from the methods implemented on the update manager.

> public static void OnChange(Type oldType, Type newType)

Why does this have `oldType` and `newType`? I thought that we are focused on updating types in-place.

**Comment by stephentoub** [comment]
> I would be fine with CoreLib reflection participating in the updating scheme as long as it is pay-for-play, like the assembly-level attribute that specifies the EnC manager(s) in the given assembly that I have suggested.

To make sure I understand, who is doing the clearing/reset here?  And your previously expressed concerns about reflection becoming a mutable model are no longer a concern because the assembly is opting in to hot reload via the attribute?

> The declarative scheme is more pay-for-play (e.g. wrt linkability) without additional work.

You mean because the linker could be told whether or not to remove the attribute based on build flavor vs needing to be taught if/when it was ok to remove the module initializer?  Fair enough.

> How does the lower-level component know whether there is going to be some higher-level component to flush it, or whether it is on its own and it should be responsible for itself?

It's a question of scenarios.  If it's really the case that you might be using a lower-level component that needs notification and be doing so separately from a higher-level component (that may or may not be used) that also needs notifications and they need to be executed in a particular order, then yeah, that would need to be applied by the invoker.  Is that the scenario?  To make it concrete, how does that come into play here, e.g. with Xamarin?

**Comment by jkotas** [comment]
> To make sure I understand, who is doing the clearing/reset here?

The global update manager (not in CoreLib, comes with SDK) would call local update handler in CoreLib. The local update handler in CoreLib would simply clear the weak handle that points to the reflection cache.

> And your previously expressed concerns about reflection becoming a mutable model are no longer a concern because the assembly is opting in to hot reload via the attribute?

I have internalized the fact that all this is best effort, the feature will not work as expected in number of cases and that it is by design.

>  Is that the scenario? To make it concrete, how does that come into play here, e.g. with Xamarin?

Reflection and Json serializer are example of lower-level / higher-level components with relationship.

> EnC manager

I meant the code injected into process. We need better names for this - what about:
- Update Manager: Global component injected into the process
- Update Handler: Local assembly-specific code that applies the updates

**Comment by stephentoub** [comment]
> The global update manager (not in CoreLib, comes with SDK) would call local update handler in CoreLib

Meaning corelib itself would have an attribute on it like:
```C#
[assembly: UpdateAppliedHandler("System.Reflection.Type", "ClearReflectionCaches", "D02B1C93-A6E5-4F07-A45D-2CD02675CF77")] //with whatever attribute name and arguments we decided on
```
yes?

> I have internalized the fact that all this is best effort

Ok :smile:

And, yes, there are plenty of things that won't work, automatically.  For example, I don't think JsonSerializer will be in a good position to automatically dump all reflection-emitted code it spit out previously, given that it doesn't reference all JsonSerializerOptions instances ever used, and such options objects hold on to reflection-related state.  Libraries and app code that may have used JsonSerializer and are holding on to the options bag that references the serialized code will need to (and know to) drop it and create a new one.

> Reflection and Json serializer are example of lower-level / higher-level components with relationship.

I presume you mean because, for example, JsonSerializerOptions will need to ditch its s_defaultOptions instance in order to drop any reflection caches it contains?  Are all executing threads going to be paused during the invocation of these handlers?  If not, I wonder how much ordering really matters, as problems can arise regardless of which cache is cleared first.  It's obviously better for the underlying reflection cache to be cleared so that all subsequent accesses to it get up-to-date information, but if JsonSerializer could be executing concurrently with an update being applied, it's going to be operating on stale state until its cache is cleared and executing threads with a reference to the cached data decide to go back to the cache to update.

Regardless, your point is that such orderings may be needed.  That suggests we're going to need to document the IDs of anything that anyone might want to rely on for ordering, so that they can include those dependencies.

This example is also one where just ordering the invocations from lower in the assembly reference graph to higher in the graph would suffice.  Are there examples where it'd be important for the higher-level component to update first (and where the lower-level component is used with and without the higher-level one such that it needs its own update handler)?

> We need better names for this

@tommcdon has been using:
- Hot Reload Agent: the code injected into the process (what you refer to as "update manager")
- Hot Reload Manager: the external launcher component (e.g. dotnet watch) that injects the agent

and we could add to that:
- Hot Reload Update Handler: code invoked by the manager in response to an update being applied

**Comment by jkotas** [comment]
> Meaning corelib itself would have an attribute on it like:
> `[assembly: UpdateAppliedHandler("System.Reflection.Type", "ClearReflectionCaches", "D02B1C93-A6E5-4F07-A45D-2CD02675CF77")]`

Yep.

> with whatever attribute name and arguments we decided on

I think the attribute should have just the type name. No method name or Guid. All those details can be attached to the update handler type.

> You could imagine a complicated versioning scheme where every cache is tagged with a version, JsonSerializer updates its notion of valid version on every update, and it only respects caches created with that same version number, or something like that.

Yep, there is a lot of complicated schemes we can invent here to push this further. Another option can be to have `BeforeUpdate` and `AfterUpdate` methods on the update handler, and require the update handler takes a lock in `BeforeUpdate` and release the lock in `AfterUpdate`.

> ordering the invocations from lower in the assembly reference graph to higher in the graph would suffice. 

Yes, this works for assemblies with static dependencies. It does not work for cases where the graph is composed dynamically, via DI or similar architectures. Again, whether this is a question for how far we want to go.

**Comment by mikem8361** [comment]
Couldn't AppDomain.AssemblyLoad be used for the dynamic cases by the Hot Reload Agent?

>  All those details can be attached to the update handler type.

If the attribute only has the type name, how does the agent know what to call on that type?  Is the agent going to make assumptions on the name and parameters of the method or methods? Would defining an interface that the type implements make sense?

**Comment by jkotas** [comment]
> how does the agent know what to call on that type? Is the agent going to make assumptions on the name and parameters of the method or methods?

Yes, the idea is to define a convention that the update handler methods need to follow, and that the agent will use to find methods to call.

> Would defining an interface that the type implements make sense?

I expect that we will see a need to evolve the convention a lot over time as the feature evolves and handling of more complex cases is added. Fixed interface would get in the way.

Also, the convention based scheme makes it straightforward for the application-framework specific types to be part of the convention and be special cased by the agent as necessary.

**Comment by mikem8361** [comment]
I would like to propose:

1) Rename to ApplyUpdateNotificationAttribute.
2) Have one constructor with with "string type" as the only parameter. The type is a the simple type name not a strong-name type reference.
3) Define the Update Handler convention as two functions "BeforeUpdate()" and "AfterUpdate()" with no parameters.

Any feedback?

**Comment by stephentoub** [comment]
> Any feedback?

1. Is the intent that BeforeUpdate/AfterUpdate are statics or that the specified type will be instantiated and then those would be instance members?
2. Will any additional information be passed, e.g. the Types being updated?

**Comment by jkotas** [comment]
> Have one constructor with with "string type" as the only parameter.

The parameter should be `Type handler`. `Type`s are fine as attribute parameters.

**Comment by mikem8361** [comment]
> 1. Is the intent that BeforeUpdate/AfterUpdate are statics or that the specified type will be instantiated and then those would be instance members?

I think they should be static.
> 2. Will any additional information be passed, e.g. the Types being updated?

The Hot Reload Manager would have to crack the metadata delta format to pass any information about the change.  To keep this simple for now, no information is passed.

**Comment by stephentoub** [comment]
> To keep this simple for now

FWIW, it keeps this simpler, but it likely makes some handlers more complicated.  For example, the handler for clearing reflection type caches needs to null out a field in the relevant type.  If it's given the Type, it can set the field.  If it's not and needs to assume that any type could have been updated, it'll need to enumerate every Type in the system that's been reified and clear it on that.

**Comment by mikem8361** [comment]
Yes, I realized this as I was editing the "Usage Example" in the header that without the info on the type being updated it will make flushing the reflection caches and probably the JsonSerializer-like cases way more difficult.  If we pass the type in the *Update handlers, are we ok with putting this burden of writing a parser in C# for the deltas on the Hot Reload Agent or Manager?  I may be making a big deal of the work involved since the format isn't well documented.  

What does everyone else think about adding the type being updated to the handler?

**Comment by jkotas** [comment]
I believe that @tmat said at one point that Roslyn has the information about edited types available and it should not be hard to pass it through the pipeline. @tmat Do I remember it correctly?

Also, there is a distinction between directly edited types and types affected by the edit. For example, when you edit a base type, reflection caches or cached serializers for inherited types may need to get invalidated too. How are we going to handle that?

**Comment by stephentoub** [comment]
> For example, when you edit a base type, reflection caches or cached serializers for inherited types may need to get invalidated too.

That's a good point.  For reflection caches, if the type provided is unsealed, we'd probably need to walk whatever cache we have of all created Types to look for ones deriving from the one specified.  For cached serializers, at least for JsonSerializer, I expect the most expedient thing to do (with or without derived types) is to invalidate all serializers, whether or not they were affected... but maybe we can be more surgical.

**Comment by lambdageek** [comment]
> are we ok with putting this burden of writing a parser in C# for the deltas on the Hot Reload Agent or Manager?

Technically this exists [MetadataReaderExtensions.GetEditAndContinueLogEntries](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.ecma335.metadatareaderextensions.geteditandcontinuelogentries?view=net-5.0#System_Reflection_Metadata_Ecma335_MetadataReaderExtensions_GetEditAndContinueLogEntries_System_Reflection_Metadata_MetadataReader_)  but the devil is in the details: to resolve the tokens to type names (or some other identity) you will need not only the delta blob but also a view of the updated metadata heaps.  A good comparison is what [`metadata-tools` has to do to get a value from a heap](https://github.com/dotnet/metadata-tools/blob/16dec995680c0951a8480ef958ddfdbeee89725e/src/Microsoft.Metadata.Visualizer/MetadataVisualizer.cs#L572-L614) in the presence of multiple generations.

It's probably better to get the data over the wire from the Hot Reload Manager and Roslyn.

**Comment by mikem8361** [comment]
Even though we haven't worked out all the details of the Hot Reload Handler convention, I think the attribute itself is ready for review.  The convention can be refined over time, but getting the attribute reviewed and into the framework soon is important schedule wise.

**Comment by tmat** [comment]
> Why does this have oldType and newType? I thought that we are focused on updating types in-place.

Initially we would only have a single type that's updated in-place. Later on when we add support for editing "reloadable" types we would need old and new type as an edit in a reloadable type will result in addition of a new type. I'd start with in-place only. We can add another form of `AfterUpdate` later.

**Comment by tmat** [comment]
> I believe that @tmat said at one point that Roslyn has the information about edited types available and it should not be hard to pass it through the pipeline. @tmat Do I remember it correctly?

That's correct. Roslyn could produce a list of tokens of updated types and pass it to the Manager, which can pass it to the Agent.
That said, if we decide to invoke the notification by the runtime it would be redundant to the data stored in EnC delta metadata tables that the runtime is already parsing anyways. If the notification is invoked by the Agent then it'd make sense to avoid metadata parsing in the agent.

I think it'd be preferable for the event to be invoked by the runtime because we'd want it to be invoked in both debugger EnC and Hot Reload (no debugger attached) scenarios. The Agent does not exist in the former.

**Comment by tmat** [comment]
@StephaneDelcroix The type `HotReloadExtensions` in your example above is missing some info: `Type type` parameter to `AfterUpdate`.

**Comment by tmat** [comment]
@stephentoub 
> Why is this necessary at this level? If there are multiple components that have a relationship, why can't just one of them register and then be responsible for invoking whatever else needs to be invoked in whatever order is important?

I don't think we would want to make these update handler types public so that they can be invoked by other components. E.g. making Reflection cache invalidation API public.
Given this assumption we need a declarative mechanism for ordering the handlers. Having each updatable component define a GUID that identifies it for this purpose and then using the id to declare dependency would do.

**Comment by tmat** [comment]
Actually, perhaps we do not need any ordering... We can define that the update handler shall not call APIs from any other component it depends on (if it does the behavior is undefined). We would just guarantee that each update invokes all handlers of all loaded assemblies marked with the attribute.

**Comment by jkotas** [comment]
> I think it'd be preferable for the event to be invoked by the runtime

There is a ton of policy involved in invoking the notifications: the thread they are invoked on, the order that they are invoked in, or the parameters that the notification events take. Since all this is incremental best effort I expect that the policy is going to evolve a lot over time, it is very likely going to include app-model specific quirks to make the experience actually work. These are reasons why I do not think it is a good idea for the events to be invoked by the core runtime.

> we'd want it to be invoked in both debugger EnC and Hot Reload (no debugger attached) scenarios. 

Nothing prevents the debugger EnC from loading the agent (or running the equivalent of the agent code in some other way - e.g. via FuncEval) as well.

**Comment by jkotas** [comment]
> Having each updatable component define a GUID

Can we just use names instead of cryptic GUIDs?

> perhaps we do not need any ordering... 

We do need ordering. A lot of these notifications are about flushing caches. The caches have to be flushed from the bottom to the top.

**Comment by jkotas** [comment]
> We can define that the update handler shall not call APIs from any other component it depends on (if it does the behavior is undefined).

Ah ok. I see. This design may make it harder to implement some of the notification handlers and it would be less reliable, but it is probably ok - at least to start with.

**Comment by jkotas** [comment]
> We can define that the update handler shall not call APIs from any other component it depends on (if it does the behavior is undefined).

Ah ok. I see. This design may make it harder to implement some of the notification handlers and it would be less reliable, but it is probably ok - at least to start with.

**Comment by stephentoub** [comment]
> I don't think we would want to make these update handler types public so that they can be invoked by other components. E.g. making Reflection cache invalidation API public.

I don't like the idea of anything being public either, which is why I was pushing back on ordering in general.  But if you need to support ordering, then something needs to be "public", whether it's documenting names/IDs/whatever or actually having a public API (which I definitely don't want to do).  And since we're talking about everything being invoked via reflection, a higher level component doesn't need a public API to invoke a lower-level one.

**Comment by mikem8361** [comment]
I made those changes to the attribute and the example.  Yes, the example does need changes as long as everybody is in agreement that the Type be passed to the handlers.

**Comment by tmat** [comment]
> Can we just use names instead of cryptic GUIDs?

We can as long as we use some naming pattern that makes them reasonably unique (e.g. assembly name + component name).

>  But if you need to support ordering, then something needs to be "public", whether it's documenting names/IDs/whatever or actually having a public API

Let's start without ordering. We can add it later.

**Comment by tmat** [comment]
@jkotas 

> Nothing prevents the debugger EnC from loading the agent (or running the equivalent of the agent code in some other way - e.g. via FuncEval) as well.

True. The debugger currently does not load any extra assemblies to the debuggee to support EnC. I wonder what the side effects might be if we do so for every F5 of every app. We are enhancing EnC to allow applying changes while the app is running under debugger (not just when the debuggee is stopped at breakpoint). If the debugger needs the agent dll to be loaded it should probably load it asynchronously as soon as the runtime is loaded to the debuggee so that the agent is ready when change is made and applied. 

Having an extra assembly will also be observable to the debuggee. Could that potentially break anything?

Invoking the update handlers via FuncEval might be a better option.

**Comment by jkotas** [comment]
> the debugger needs the agent dll to be loaded it should probably load it asynchronously as soon as the runtime is loaded to the debuggee

Why would it be a problem to load the agent only once it is needed (ie when there is a change to apply)?

> Having an extra assembly will also be observable to the debuggee. Could that potentially break anything?

We do not usually worry about loading of extra assemblies causing problems. Other diagnostic tools do it too. If it proves to be real problem, we can add an API to load assembly as hidden to fix this problem for all diagnostic scenarios. Assemblies loaded as hidden would not be returned from APIs like `AppDomain.GetAssemblies()`.

Flushing of the caches is going to be observable as well. My guess is that flushing of the caches has much higher breaking potential than loading of an extra assembly.

> Invoking the update handlers via FuncEval might be a better option.

Yes, it would work. The downside is that it would lead to some code duplication.

**Comment by tmat** [comment]
> Why would it be a problem to load the agent only once it is needed (ie when there is a change to apply)?

For perf reasons - applying change is blocking operation, so ideally we wouldn't need to do any IO. We could wait until we observe a text change in the editor (before the user applies it) and trigger the load asynchronously then.

> If it proves to be a real problem, we can add an API to load assembly as hidden to fix this problem for all diagnostic scenarios. Assemblies loaded as hidden would not be returned from APIs like AppDomain.GetAssemblies().

Good to have that option.

**Comment by tmat** [comment]
> We can define that the update handler shall not call APIs from any other component it depends on (if it does the behavior is undefined).

Thinking about this more - we have to have an exception to this rule. We need Reflection caches are flushed before we call other update handlers since the handlers are going to use `System.Type` and it seems reasonable they would see the updated members of the type.

**Comment by tmat** [comment]
Also wondering if it'd be better to pass in more details about the edits (not just Type object). E.g. the most common scenario is that a method body is updated. This has no effect on  any type members. Should we invoke update handlers for the containing type even for these kind of changes? I guess some component might have a cache that memoizes results of some calculation and that could be affected by a method body edit. 

Perhaps it would be better if we had multiple optional handlers - similarly to the model we use in Roslyn analyzers. Some components would declare that they are interested in type member changes (`AfterTypeUpdate(Type)` handler), others could declare they are interested in method body updates (`AfterMethodBodyUpdate(MethodBase)` handler).

**Comment by jkotas** [comment]
> We need Reflection caches are flushed before we call other update handlers

Sure, we can have one-off exception for reflection (more policy built into the agent). But I do not think reflection is an exception. I believe that the same problem exists in other places. For example, between dependency injection infrastructure and the injected components. The notification handlers can work around it by not doing any actual work and just taking a note that the actual work has to be done later.  Some of the notification handlers may be harder to implement this way, but not impossible.

**Comment by tmat** [comment]
I'd generally expect the handlers to do as little work as possible so that we don't block applying changes too long. Ideally just nulling out some field and let the data be repopulated on next access. Having Reflection caches flushed before other handlers get executed makes it possible for the handler to determine what specific clean up to do based on inspecting the Type it's given.

**Comment by mikem8361** [comment]
It sounds like the ordering and the details of the hot reload handler convention are close.  Do we want a separate Reflection cache update handler? Since it and other caches can be just marked as "cleared" and not repopulated in the handler, the order isn't important other than being before the UI refresh handlers.  Is BeforeUpdate (caches)/AfterUpdate (UI) handlers enough?

Can we agree that the attribute itself is ready for review?  I would like to drive that to closure if possible.

**Comment by jkotas** [comment]
The attribute looks good to me. I am not sure whether `System.Reflection.Metadata` namespace make sense - something to discuss during API review.

**Comment by jkotas** [comment]
>  The runtime is responsible for scanning assemblies at load, and register the notifiers

This should be updated to say that the hot reload agent is reponsible for this.

**Comment by stephentoub** [comment]
> Can we agree that the attribute itself is ready for review?

As specified, it'll prohibit multiple such attributes on an assembly.  Is that the desired semantic?  That might make it harder for source generators, as a source generator that wanted to receive a notification would then need to coordinate with any other usage of the attribute in the assembly.  So, maybe it should be AllowMultiple=true, and the hot reload agent is responsible for calling all defined handlers rather than just one.

> I am not sure whether System.Reflection.Metadata namespace make sense - something to discuss during API review.

I think it makes sense for ApplyUpdateNotificationAttribute to be in the same namespace as ApplyUpdate, which leads to System.Reflection.Metadata.  But, I'm fine with whatever we decide in API review, as well.

> Do we want a separate Reflection cache update handler?

We should use the same mechanism as everyone else, which would suggest Corelib will need its own handler for the agent to invoke, and that handler will clear the relevant state.  Presumably that'll be some static that QCalls into the runtime to clear whatever caches it needs to clear, if it can't just do it by looking at the one type it's handed (e.g. if it's given a non-sealed type and needs to find derived types that might need to be cleared as well).

**Comment by mikem8361** [comment]
>> Do we want a separate Reflection cache update handler?

What I meant was should there be a different method on the handler class (i.e. ReflectionUpdate(Type type)) just for reflection cache clearing in corelib or will BeforeUpdate(Type type) be sufficient.

**Comment by stephentoub** [comment]
> or will BeforeUpdate(Type type) be sufficient

BeforeUpdate should be sufficient.  If we find it's not, we'll need to revisit the general approach and discuss exactly what support for different levels/ordering are required for the target scenarios.  We should not add anything reflection-specific to the pattern.

**Comment by tmat** [comment]
BeforeUpdate? I though we are invoking AfterUpdate so that one can inspect the new version of the type.
Reflection's handler only needs to be special cased so that it's invoked first (so that AfterUpdate(Type) _can_ inspect the new version of the type. But it can follow the same API pattern.

**Comment by stephentoub** [comment]
The pattern would have both before and after.  The reflection clearing support in corelib would only need to implement the before.

**Comment by tmat** [comment]
I see. OK.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Reflection.Metadata
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple=True)]
    public sealed class MetadataUpdateHandlerAttribute : Attribute
    {
        public MetadataUpdateHandlerAttribute(Type type)   
    }
}
```

**Comment by danmoseley** [comment]
@mikem8361 @stephentoub who is doing the work here to (1) add this attribute type (2) make it work?

**Comment by danmoseley** [comment]
cc @ericstj

**Comment by stephentoub** [comment]
Adding the attribute is trivial.  I can do that.  "Making it work", meaning invoking it,  is part of the hot reload agent and is not part of dotnet/runtime. Then there are the various places we ourselves want to subscribe to a notification.  I believe Mike is signed up to clear the runtime's reflection cache,  but he can correct me if that's evolved.  And @eerhardt has been auditing where else we may want to take action.

**Comment by mikem8361** [comment]
I'm planning to add the attribute and to clear the runtime's reflection caches. I'm currently working on something else at this point, but I'll get to this hot reload work in a few weeks.

**Comment by stephentoub** [comment]
Thanks, Mike.  I'll just add the attribute now, as it's quick to do, to unblock anyone else upstream.  I'll open an issue and leave a TODO in the code for you to fill in the cache clearing stuff later.
