### ISSUE TITLE
StringComparer implementations are not serializable

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/runtime#49449]
Correctly serializing dictionaries and other collections which contain non-default `IEqualityComparer<T>` implementations requires serializing the comparer in some form. Unfortunately, there are some roadblocks serializing some of the very common in-built implementations for `string` keys.

Out-of-the-box `StringComparer` implementations currently include `OrdinalComparer` (plus its two subtypes) and `CultureAwareComparer`.

`OrdinalComparer` does not currently implement `ISerializable`. Its subtypes do ([OrdinalCaseSensitiveComparer](https://github.com/dotnet/runtime/blob/b38ea6a4f067b571a007b2ac69f3e4431cb100e7/src/libraries/System.Private.CoreLib/src/System/StringComparer.cs#L286) and [OrdinalIgnoreCaseComparer](https://github.com/dotnet/runtime/blob/b38ea6a4f067b571a007b2ac69f3e4431cb100e7/src/libraries/System.Private.CoreLib/src/System/StringComparer.cs#L315)), however they do not implement a corresponding `(SerializationInfo, StreamingContext)` ctor and neither does the base `OrdinalComparer` type. I may be misunderstanding how the pattern is supposed to be implemented, but this doesn't seem right to me - corrections are welcome. I could alternatively create a serialization surrogate if `OrdinalComparer` and its implementations + properties were exposed.

`CultureAwareComparer` implements `ISerializable` in a manner which can be serialized using the `ISerializable` route (it requires IL or reflection to implement).

**Comment by danmoseley** [comment]
ISerializable is in the process of being obsoleted, as part of the BinaryFormatter machinery: https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md

What serialization mechanism do you use -- something hand rolled, or a shipping serializer?

**Comment by ReubenBond** [comment]
Hand-rolled. I am building a new serializer which is version tolerant, fast, and supports .NET's type system well. Currently hosted here: https://github.com/ReubenBond/Hagar

If that mechanism is being deprecated, do we have ideas on a replacement for safe, high-fidelity serialization?

**Comment by danmoseley** [comment]
There's a discussion with some guidance here https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide
I expect we'll want to continue to extend that guidance over the next year or two as we continue obsoletion. It would be great to include any feedback you may have.

cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
`[Serializable]` is a marker attribute which says "I am serializable." For `BinaryFormatter` and similar serializers, they understand this attribute to mean "To serialize, enumerate my instance fields and write their contents to a stream. To deserialize, instantiate the type (but don't call any ctors) and repopulate the instance fields."

`ISerializable` and `.ctor(SerializationInfo, StreamingContext)` are __optional__ ways to control how serialization takes place. The interface says "Instead of enumerating my instance fields, call `ISerializable.GetObjectData`, which will write all of the relevant data to the stream for you." And the ctor says "To deserialize, call this special ctor, which will rehydrate the object state by reading relevant data from the stream." (In reality, `SerializationInfo` is a glorified property bag rather than a stream, but the same concept holds.)

Note the "optional" in the description above. It's only used for types that need to customize how data is written to / read from the stream. "Simple" types like `OrdinalComparer` don't implement the interface because they contain a small handful of primitive fields, and there's nothing really special about serializing or deserializing such objects.

`OrdinalIgnoreCaseComparer` is a little clever. It implements `ISerializable` but not the deserialization ctor. The reason for this is that [its implementation of `ISerializable.GetObjectData`](https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/StringComparer.cs#L356) basically says "pretend I'm really an instance of `OrdinalComparer` with the field value _\_ignoreCase = true_." This causes the type information written to the serialized stream to read "System.OrdinalComparer, mscorlib" instead of "System.OrdinalIgnoreCaseComparer, System.Private.CoreLib". Then, when deserializing such a stream, the serializer only looks at the shape of `OrdinalComparer` - _not_ `OrdinalComparerIgnoreCase` - to figure out what to do. So there's no need for `OrdinalComparerIgnoreCase` to contain the deserialization ctor, since nobody will ever query for it in the first place.

Typical disclaimer: Serializers that rely on putting type information in the payload, or in rehydrating private instance state independent of normal class ctors, or that allow weirdly complex object graphs to be created may present security vulnerabilities. `BinaryFormatter` hits the golden trifecta, which is why we're trying to squash it. But each is dangerous on its own to some extent. So use caution if you write a serializer that heads down this route.

**Comment by GrabYourPitchforks** [comment]
Can I go ahead and close this issue? I don't think there's any work for the libraries team to do here. These types all appear to implement the legacy serialization pattern correctly.
