### ISSUE TITLE
TryAddWithoutValidation works differently for HttpClient.DefaultRequestHeaders and HttpRequestMessage.Headers

### ISSUE THREAD

**Issue by AbeniMatteo** [dotnet/runtime#49463]
### Description

Header in `HttpClient.DefaultRequestHeaders` is formatted and sent as `en-US, en; q=0.5` (note the spaces).
```cs
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/"));
client.DefaultRequestHeaders.TryAddWithoutValidation("Accept-Language", "en-US,en;q=0.5");
client.Send(request);
```

Header in `HttpRequestMessage.Headers` is untouched and sent as `en-US,en;q=0.5`.
```cs
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/"));
request.Headers.TryAddWithoutValidation("Accept-Language", "en-US,en;q=0.5");
client.Send(request);
```

### Configuration
.NET 5

**Comment by stephentoub** [comment]
The code here:
https://github.com/dotnet/runtime/blob/89fbdcafcc09af0e1c2d86783eb8e8b93a743968/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L557
is parsing the data from the default headers being added.  Looking back through history, it appears this was done when the handler would enumerate the headers in a way that would parse/validate them, in which case it was desirable to forcible do that parsing/validation just once for the default header collection rather than on every send.  But as of https://github.com/dotnet/corefx/pull/41640 in .NET 5, we're no longer doing that parsing/validation forcibly as part of actually sending the request, which means that up-front parsing/validation of the default header collection is now not only unnecessary work but also leads to the behavioral discrepancy highlighted in this issue.  Seems like we should just stop doing that.

**Comment by geoffkizer** [comment]
> Seems like we should just stop doing that.

By "that", you mean:

> up-front parsing/validation of the default header collection

? Seems reasonable to me.

**Comment by stephentoub** [comment]
Yup :)

**Comment by ManickaP** [comment]
Triage: we should investigate here and if we parse the headers we should not.

**Comment by AbeniMatteo** [comment]
This is getting interesting. 😄 
`DebuggerDisplayAttribute` works the opposite way. Now `HttpRequestMessage.Headers` is the one being formatted.

![image](https://user-images.githubusercontent.com/634710/111203755-aba99000-85c5-11eb-98c7-e96618242e83.png)
![image](https://user-images.githubusercontent.com/634710/111203662-946aa280-85c5-11eb-9fc1-b86d034269e0.png)

**Comment by stephentoub** [comment]
> DebuggerDisplayAttribute works the opposite way

There's no DebuggerDisplayAttribute here: it's calling ToString().

I also don't see the behavior you're seeing... what .NET version is that?

**Comment by AbeniMatteo** [comment]
The problem appears after hovering `.Headers` then `request` and again `.Headers`.
Apparently calling `request.ToString()` changes the value, you can also trigger it programmatically:
```cs
var a = request.Headers.ToString(); // Accept-Language: en-US,en;q=0.5
request.ToString();
var b = request.Headers.ToString(); // Accept-Language: en-US, en; q=0.5
```

I'm using .NET 5.0.201 with VS 2019 Version 16.9.1.

**Comment by stephentoub** [comment]
> Apparently calling request.ToString() changes the value

Yes.  I thought you were just looking at headers, but HttpRequestMessage.ToString() enumerates HttpHeaders (rather than using its ToString()), and such enumerating will parse.
