### ISSUE TITLE
string.Format() returns different results cross platforms.

### ISSUE THREAD

**Issue by vuqtran88** [dotnet/runtime#49562]
### Description
Consider the following code.
```
    class Program
    {
		static void Main(string[] args)
		{
			var ci = new CultureInfo("ar"); // Arabic Culture.
			Thread.CurrentThread.CurrentCulture = ci;
			Thread.CurrentThread.CurrentUICulture = ci;
			float a = 1.2343f;
			//Turn a float number into a string with the format X.XXXXX
			string floatNumberString = string.Format("{0:0.######}", a);
			Console.WriteLine("float number string presentation: " + floatNumberString);
			Console.WriteLine("is ASCII string ? " + IsAsciiString(floatNumberString));
		}
		public static bool IsAsciiString(string input)
		{
			for (int i = 0; i < input.Length; ++i)
			{
				char c = input[i];
				if (((int)c) > 127)
				{
					Console.WriteLine("Character '" + c + "'(hex value " + ((int)c).ToString("X") +  ") + at index " + i + " is not ASCII");
					return false;
				}
			}
			return true;
		}
	}
```
If running in the code in windows and linux, we get 2 different outputs:

Windows Output:
```
float number string presentation: 1.2343
is ASCII string ? ? True
```
Linux Output:
```
float number string presentation: 1٫2343
Character '٫'(hex value 66B) + at index 1 is not ASCII
is ASCII string ? ? False
```
The call string.Format("{0:0.######}", a)  under “Arabic” culture, yields two different string interpretations of the same float number under 2 different platforms (Window vs Unix). In windows, under “Arabic” culture, the decimal point is converted into an ascii character (.colon). In contrast, in Linux, the decimal point is converted into an unicode character (٫ Arabic decimal separator).

### Configuration

* Which version of .NET is the code running on? .Net Core 3.1
* What OS and version, and what distro if applicable? Windows and Linux.

**Comment by tarekgh** [comment]
.NET is using the underlying OS to get the Globalization data which is used in the number formatting. On Windows it uses `NLS` Windows APIs and on Linux it uses `ICU` library. So, this is expected behavior to see differences between platforms. 

In .NET 5.0, we are using `ICU` library on Windows too and should get consistent behavior across the platforms. I would recommend you migrate to use .NET 5.o if you want the consistency. `ICU` is using the CLDR data which is picked up from Unicode Standard. The behavior you get when using `ICU` would be the desired behavior according to Unicode standard. 

Let me know if you have any more questions. Thanks for reporting the issue.
