### ISSUE TITLE
Move to include Mono in the name of all Mono runtime packs

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#49718]
Back in .NET 5, we had some scenarios where we would be targeting the same platforms as coreclr.  In order to get around ugly name conflicts in the runtime packs, we added Mono as part of the name.  `microsoft.netcore.app.runtime.mono.osx-64`, for example.  We did not apply this rule to any of the platforms where there was just the mono runtime and nothing else (iOS, Android, and wasm).  

Fast forward to .NET 6 and we have more combinations where it makes sense to default **all** mono runtime packs to include mono in the name.  This may be a break for groups who rely on the package name, so I'm raising awareness before moving forward.

The workloads impacted are:

- iOS / tvOS / MacCatalyst
- Android
- WebAssembly

Example: `microsoft.netcore.app.runtime.mono.ios.arm-64`

@rolfbjarne @jonathanpeppers @lewing @radical @naricc

**Comment by naricc** [comment]
@DrewScoggins It seems like this would probably effect the performance pipelines; I assume they are using the name to find the runtime pack.

I think the runtime tests will probably need a minor change for the new name too. @fanyang-mono @imhameed This will probably effect runtime tests on iOS/Android, as well as wasm.

I am happy though, because it would probably keep things from accidentally using a coreclr runtime pack, which has occasionally been a source of woe.

**Comment by DrewScoggins** [comment]
This should not change anything for mono, as we don't use the runtime packs.

For WASM we rely on this file, `artifacts/packages/Release/Shipping/Microsoft.NETCore.App.Runtime.browser-wasm.6.0.0-ci.nupkg`, and it doesn't look like that will be changing.

Finally, for AOT this will be a breaking change as we rely on `artifacts/bin/microsoft.netcore.app.runtime.linux-x64/Release`, and I assume that will change to `artifacts/bin/microsoft.netcore.app.runtime.mono.linux-x64/Release`
