### ISSUE TITLE
Delete redundant vectorization code paths

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#49846]
We have a non-trivial number of implementations that duplicate loops across multiple hardware instruction sets plus a generalized Vector path, e.g.
https://github.com/dotnet/runtime/blob/9f93bcb46478b1282daba268aa4d0a8550e06a31/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs#L266-L434
has a structure that's approximately:
```C#
if (Avx2.IsSupported)
{
    ... // use Avx2
}
else if (Sse2.IsSupported)
{
    ... // use Sse2
}
else if (AdvSimd.Arm64.IsSupported)
{
    ... // use AdvSimd
}
else if (Vector.IsHardwareAccelerated)
{
    ... // use Vector / Vector<T>
}
```

We have others like:
https://github.com/dotnet/runtime/blob/9f93bcb46478b1282daba268aa4d0a8550e06a31/src/libraries/System.Collections/src/System/Collections/BitArray.cs#L152-L224
that similarly have paths for Avx2, Sse2, and AdvSimd but without a Vector path.

This is a lot of complicated code being duplicated, and it should no longer be necessary.  In most cases, the path using `Vector<T>` should produce code identical to what we'd otherwise write manually using hardware intrinsics, automatically picking 32-bytes or 16-bytes based on what the hardware supports.  So, for any of these cases that do Avx2/Sse2/AdvSimd/Vector, we should theoretically be able to simply delete the Avx2/Sse2/AdvSimd code paths, leaving only the Vector code path, because if the Avx2 path would be supported, then Vector would similarly use 32-byte widths, and if Avx2 wouldn't be supported but Sse2/AdvSimd would, Vector would similarly use 16-byte widths.  And for the cases that today use Avx2/Sse2/AdvSimd without a Vector path, we should be able to add a path for Vector and then delete the others, for the same reason.

For paths that don't have an Avx2 option, and instead just have paths for Sse2/AdvSimd/Vector, it's less clear whether we could delete the Sse2/AdvSimd implementations, as it's possible there could be performance differences (for better or worse) if the Vector path ended up using 32-byte widths.

cc: @tannergooding, @benaadams

**Comment by benaadams** [comment]
They aren't completely the same with for example the `Avx2` paths being more optimized than the `Vector` path (e.g. for determining the "found" index from the Vector) and also uses 16-byte and 32 byte vectors; so acceleration starts at 16 bytes or 8 chars; whereas the `Vector` path would always start at 32 bytes or 16 chars

**Comment by stephentoub** [comment]
What is the additional optimization in the BitArray example?

**Comment by benaadams** [comment]
> What is the additional optimization in the BitArray example?

Looks like it needs work 😅

As an aside I was considering whether a Generator for all the SpanHelper methods would be interesting since they are all variations on a theme (as is the one in `System.Text.Json` https://github.com/dotnet/runtime/pull/41097#discussion_r589723963) and additional variants like `IndexNotEquals` were rejected https://github.com/dotnet/runtime/issues/28795#issuecomment-717466792; but that could be covered with a Generator.

Don't know if that would be better or worse?

Would be less code to look after, but also easier to generate more variants so more asm...

**Comment by tannergooding** [comment]
I think a generator for vectorized code seems like an overall interesting idea but also a complex one. The main issue I see is that we have 3-4 code paths that are all nearly identical. They often only differ in one or two places when they do differ at all.

The options for normalizing these are:
* Wait for https://github.com/dotnet/runtime/issues/49397 and normalize on `Vector128<T>` everywhere
* Continue using `Vector<T>` and utilize the `.AsVector256()` and `.AsVector128()` intrinsics to handle platform specific ops over different `Vector<T>` sizes

--------------------------

`Vector<T>` is nice in that it is generic and allows you to write a single path supporting multiple platforms.
It is not so nice in that it is variable sized and so it can be difficult to accurately know the benefit.
* If the inputs are small, you are adding overhead for the vector handling and may frequently not use it.
* If input is large, using Vector<T> may be beneficial but this can be dependent on alignment of the data, operations being done, etc
* Because it is variable sized, certain operations can't be easily represented (shuffling/permute is one example)
* Larger vector sizes may impact things like battery life negatively
* If we onboard additional vector sizes in the future (such as Vector512, or any of the SVE sizes) these issues may become more problematic

`Vector128<T>` is nice in that it is currently the cross-platform shared vector size.
* It is fixed size and so conceptually allows more xplat ops
* It is trivial to fallback to the relevant hardware intrinsics where shared xplat functionality isn't possible
* It generally doesn't incur overhead or downclocking and so is "battery friendly"
* If data is misaligned, cache line splits only occur every 4 reads, rather than every 2, which CPUs tend to handle better
It is not nice in that it may leave perf on the table when inputs are particularly large, but I feel this is algorithm specific and not the "default/expected"

**Comment by benaadams** [comment]
> The options for normalizing these are

For span helpers while the "not here" are mostly the same (essentially `.Equals`) identifying a found item is very different; the intrinsic paths use the single instruction `MoveMask` whereas the `Vector<T>` path uses a loop over each vector element; which is also why the Jit special cases loop unrolling for `i < Vector<ulong>.Count`
https://github.com/dotnet/runtime/blob/9f93bcb46478b1282daba268aa4d0a8550e06a31/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs#L1681-L1698

However accessing each element of the vector individually to check them isn't great... Perhaps we need to extend the apis on the platform independent vectors?

**Comment by tannergooding** [comment]
> Perhaps we need to extend the apis on the platform independent vectors?

The primary blocker here is that `Vector<T>` is variable sized. We cannot easily expose concepts like `MoveMask` because that may break future extensions. (e.g. `SVE` which can go up to 2048-bits)
Even thinking of AVX-512 support, it can become very limiting in what concepts you can expose for `Vector<T>` because you start requiring `long` or more to represent per element masks.

**Comment by benaadams** [comment]
> It generally doesn't incur overhead or downclocking 

Looks like Rocket Lake and AVX-512 aren't downclocking anymore? https://twitter.com/trav_downs/status/1376416816482807811

**Comment by tannergooding** [comment]
This is something that will likely not make 6.0.0 but will be more easily resolvable once https://github.com/dotnet/runtime/issues/49397 is in.

**Comment by stephentoub** [comment]
Closing as we're exploring other directions.
