### ISSUE TITLE
API Proposal: Implement IEnumerable<> on various X509 collection types

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#49878]
## Background and Motivation

X509Certificate2Collection and related types implement the non-generic enumerable but not generic enumerable.  This makes them harder to use with LINQ, and it's very common to see `.OfType<X509Whatever>()` used with these types, even though all of the elements of the collection are guaranteed to implement that type.  This makes consumption both more cumbersome, more confusing, and more expensive.  We can't change the signatures of the public GetEnumerator methods on these types, but we can at least implement the interfaces so that the OfType isn't necessary.

## Proposed API

```diff
public class X509Certificate2Collection : X509CertificateCollection,
+     IEnumerable<X509Certificate2>
{
    ...
}

public sealed class X509Certificate2Enumerator : IEnumerator,
+     IEnumerator<X509Certificate2>
{
    ...
}
    

public sealed class X509ChainElementCollection : ICollection,
+    IEnumerable<X509ChainElement>
{
    ...
}

public sealed class X509ChainElementEnumerator : IEnumerator,
+    IEnumerator<X509ChainElement>
{
    ...
}

public sealed class X509ExtensionCollection : ICollection,
+    IEnumerable<X509Extension>
{
    ...
}

public sealed class X509ExtensionEnumerator : IEnumerator,
+    IEnumerator<X509Extension>
{
    ...
}
```
All new interface method implementations would be explicit.

(We could also consider implementing `ICollection<T>` where the existing type implements `ICollection`.)

Example commit:
https://github.com/stephentoub/runtime/commit/d310e84f5b1918f5886edf640fdfee13cb01393d

**Comment by vcsjones** [comment]
> `IEnumerable<X509Certificate2>`

Much to my dismay, `X509Certificate2Collection` can contain an `X509Certificate`, it isn't limited to `X509Certificate2`.

```csharp
var coll = new X509Certificate2Collection();
var cert = new X509Certificate();
coll.Add(cert);
```

> all of the elements of the collection are guaranteed to implement that type

That does not seem to be the case for `X509Certificate2Collection`.

**Comment by stephentoub** [comment]
If that's true, that's a bug, since the implementation assumes that's not true:
https://github.com/dotnet/runtime/blob/ded66fc97eaeb9cefd4646cce431131cf8e8877c/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2Collection.cs#L38

**Comment by bartonjs** [comment]
I believe they can be added and removed, because of the members on X509CertificateCollection (the base class of X509Certificate2Collection), but it puts the collection in a bad state for indexing and enumerating.

I agree with the current proposal not making `X509CertificateCollection : IEnumerable<X509Certificate>` (since that would make the 2-coll be both-kinds enumerable), and I think we can safely ignore this corner case (being in no worse a state than we currently are).

In reality, no one instantiates X509Certificate(1), and no one derives from it (other than X509Certificate2), so it's not a major practical concern.

**Comment by stephentoub** [comment]
We could also override OnValidate to throw an exception if a non-X509Certificate2 is added, but it sounds like even that's not warranted.

**Comment by bartonjs** [comment]
Throwing that at SharpLab and looking at the IL, it looks like the argument to `collection.Cast<X509Certificate>` is ending up at CollectionBase.GetEnumerator, which returns an enumerator over the underlying ArrayList.

So in order to maintain compatibility in this case (if we care) we would need to explicitly re-implement IEnumerable.GetEnumerator to replicate the one coming from CollectionBase, instead of deferring to the stronger-typed X509Certificate2Collection.GetEnumerator.

**Comment by bartonjs** [comment]
Looks good as proposed.

```diff
namespace System.Security.Cryptography.X509Certificates
{
    public class X509Certificate2Collection : X509CertificateCollection,
+         IEnumerable<X509Certificate2>
    {
        ...
    }
    
    public sealed class X509Certificate2Enumerator : IEnumerator,
+         IEnumerator<X509Certificate2>
    {
        ...
    }
        
    
    public sealed class X509ChainElementCollection : ICollection,
+        IEnumerable<X509ChainElement>
    {
        ...
    }
    
    public sealed class X509ChainElementEnumerator : IEnumerator,
+        IEnumerator<X509ChainElement>
    {
        ...
    }
    
    public sealed class X509ExtensionCollection : ICollection,
+        IEnumerable<X509Extension>
    {
        ...
    }
    
    public sealed class X509ExtensionEnumerator : IEnumerator,
+        IEnumerator<X509Extension>
    {
        ...
    }
}
```
