### ISSUE TITLE
System.Runtime.CompilerServices.RuntimeFeature.VirtualStaticsInInterfaces

### ISSUE THREAD

**Issue by jcouv** [dotnet/runtime#49905]
The runtime should expose the following feature flag for runtimes that support static abstract members in interfaces.

```csharp
namespace System.Runtime.CompilerServices
{
    public static class RuntimeFeature
    {
        public const string VirtualStaticsInInterfaces = nameof(VirtualStaticsInInterfaces);
    }
}
```

The implementation of `static bool IsSupported(string feature)` should be updated accordingly.

FYI @davidwrighton @AlekseyTs 

Relates to language feature: https://github.com/dotnet/csharplang/issues/4436

Per discussion with the overall feature crew, we'd like this change in .NET 6 preview 5, to line up with runtime and C# compiler work.

**Comment by stephentoub** [comment]
I assume this gets attributed as [Preview] as well?

**Comment by davidwrighton** [comment]
@jcouv  I agree with @stephentoub that this constant should be marked with the preview attribute. Do we think that the IsSupported function result should also be conditional on the runtime preview flag being set as well?

**Comment by jcouv** [comment]
I think marking it as `[Preview]` (or whatever attribute we end up using to gate preview features) is okay, but would have minimal benefit as the compiler is the main consumer of `RuntimeFeature`.

It is also okay to have the `IsSupported` logic conditional on the runtime preview flag, but the difference is only observable if you use "preview" language version without setting the runtime preview flag. In such a scenario the user is aware of being outside of the supported boundaries.

Neither seems needed for preview 5. I'm not sure what's the best way to track such a change (once the design of preview flag is done). I'll add a note in roslyn work items for now.

**Comment by marek-safar** [comment]
> but would have minimal benefit as the compiler is the main consumer of RuntimeFeature.

Why are we adding this API? The compiler will use the string literal because it does not target net6, right?

**Comment by huoyaoyuan** [comment]
> Why are we adding this API? The compiler will use the string literal because it does not target net6, right?

Like `DefaultImplementationsOfInterfaces`, the compiler detects the existence of the property to decide feature availability.

**Comment by bartonjs** [comment]
Looks good as-is (with the RequiresPreviewFeatures attribute)

```C#
namespace System.Runtime.CompilerServices
{
    public static class RuntimeFeature
    {
        [RequiresPreviewFeatures]
        public const string VirtualStaticsInInterfaces = nameof(VirtualStaticsInInterfaces);
    }
}
```

**Comment by tannergooding** [comment]
Notably, as raised by @333fred, this may need to be changed to `AbstractStaticsInInterfaces` if we believe default implementation support will not ship in the runtime for v1.

The library team has stated that default implementation support will be eventually required (at least by v2) so we can add members to existing interfaces such as `INumber` (otherwise we are forced to create `INumber2` and friends, which is not desired).

CC. @davidwrighton and @AlekseyTs to determine when that support will go in and whether that has any impact for what we use in .NET 6 vs when the feature ships as stable (v1) vs when we need to version the interfaces (v2)

**Comment by davidwrighton** [comment]
I think its highly likely that default implementation support will ship in the runtime, even if it doesn't make the language.

**Comment by AlekseyTs** [comment]
@davidwrighton 

> I think its highly likely that default implementation support will ship in the runtime

I am not sure how runtime would be able to do that since specification doesn't define a way to describe that in metadata. I believe according to specification, virtual statics in interfaces can be only abstract, which doesn't allow them to have an implementation.

**Comment by davidwrighton** [comment]
My expectation is that we'll take an update to our spec in time for Preview 6. There have been enough consistent from @tannergooding for this during the feature, that I'd like to take a stab at the design so that the runtime work in .NET 7 to move this from a preview feature is performance focused and not behavior focused.
