### ISSUE TITLE
After adding friendly name to x509certificate2 on exporting public bytes , we are loosing friendly name

### ISSUE THREAD

**Issue by prohith14** [dotnet/runtime#49993]
### Description

* While creating certificate , i set friendly name. But upon exporting public bytes that value is lost

### Configuration

* Which version of .NET is the code running on - netcoreapp31
var crtFileName = @"D:\test-dps-sw\9988770_public.pem";
X509Certificate2 x509 = new X509Certificate2(crtFileName);
var publicKeyBytes = x509 .Export(X509ContentType.Cert);

Upon creating certificate from public key bytes i find friendly name feild empty.

I there any way to carry that value, or else any other key where i can set and carry value

**Comment by vcsjones** [comment]
The friendly name is a Windows-specific concept that is stored as metadata along side the certificate when it is in the certificate store. It does not actually change a property on the certificate itself, which is why it  is "lost" when it is exported.

Since changing a certificate after it's creation would invalidate the signature, this couldn't be "added" either.

I think the best you can do is to export the certificate, and read the FriendlyName from the certificate as well and save it in a separate file. When importing it, read the certificate, then read the file with the friendly name and set it again.

**Comment by prohith14** [comment]
We are using certificate to authenticate with azure dps and provision it to azure iot hub. The common name of certificate will be device id in iot hub. So i cant use that field to store this additional property.
Can you please guide if i can use any other field to save a string value so that i can read it from certificate public pem

**Comment by bartonjs** [comment]
> Can you please guide if i can use any other field to save a string value so that i can read it from certificate public pem

There isn't anything you can set that would appear in such a file.  A certificate is just the data that the issuer signed plus the signature, there's no room for post-issuance data.
