### ISSUE TITLE
[System.Net.Http.Json] `HttpRequestException` thrown by `HttpClient.GetFromJsonAsync` doesn't contain response content

### ISSUE THREAD

**Issue by snebjorn** [dotnet/runtime#50164]
`HttpClient.GetFromJsonAsync` will throw an `HttpRequestException` on non-success responses. This is fine.
But the exception doesn't include enough info to figure out what went wrong.

So when using `HttpClient.GetFromJsonAsync` we have to leave some commented out debug code to figure out why a request failed. This isn't ideal.

```cs
// uncomment to read the error response
// var error = await httpClient.GetAsync("...");
// var msg = await error.Content.ReadAsStringAsync();

var response = await httpClient.GetFromJsonAsync<Foo>("...");
```

This basically means that we can't use `GetFromJsonAsync` if we care about why a request failed.

A solution would be to include `HttpResponseMessage.Content` in `HttpRequestException`. Then we could act on it.
Something like this:
```cs
try
{
    var response = await httpClient.GetFromJsonAsync<Foo>("...");
}
catch (HttpRequestException ex)
{
    var errorMsg = await ex.Content.ReadAsStringAsync();
    _logger.Error(errorMsg);
    throw;
}
```

**Comment by davidfowl** [comment]
This assumes that everyone wants the  content fully buffered, and that definitely isn't the case. This would have to be opt-in, if we allow for it.

**Comment by snebjorn** [comment]
I can see that one might not care about the content when using `httpClient.GetAsync("...");`.

But I'd argue when using `GetFromJsonAsync` we care about the content as we're trying to deserialize it. If that fails we were already expecting to "pay" for fully buffered content so including it in an exception shouldn't be too harmful. I also expect the error content to be smaller then the success content.

An opt-in could absolutely work, but I fear it's only something you'll figure out you need to opt-in to when you see it fail and try to figure out why.

**Comment by mburbea** [comment]
I think at minimum it could be useful to get back some data on the exception. (maybe just 128 characters or something). As a statuscode may not tell you all the reasons why a call failed.

**Comment by davidfowl** [comment]
IMO this sorta thing helps debugging. You make a request and it fails and you need to make another request to get the string back to figure out why. Is this something you would use outside of debugging? If so how?

**Comment by mburbea** [comment]
I deal with a vendor api at work that uses 403 status code for an assortment of errors with a small message explaining why(invalid credentials, unauthorized, rate limited, etc).

In my current code, I try to get the response, and if I get a 403, I decipher the message and display something more useful to the end user. (e.g. Unauthorized: please contact Administrator if you think this is a mistake. Rate limited: Please try again later.).

While I'd like to use the simpler API, since I can't get the content, I cannot here.

**Comment by snebjorn** [comment]
> In my current code, I try to get the response, and if I get a 403, I decipher the message and display something more useful to the end user.

> While I'd like to use the simpler API, since I can't get the content, I cannot here.

That's pretty much my usage as well. I just log the error content so I can figure out the what and why later

**Comment by wfurt** [comment]
Note that the context may contain sensitive data and that it makes difficult IMHO to put it to exception all the time.

**Comment by snebjorn** [comment]
> Note that the context may contain sensitive data and that it makes difficult IMHO to put it to exception all the time.

Valid point. But what kind of sensitive data would an error message from a web API contain?

**Comment by davidfowl** [comment]
It may not be an error message, it's a non JSON response body

**Comment by karelz** [comment]
@eiriktsarpalis @layomia @steveharter can you please help triage it? Thanks!

**Comment by dferretti** [comment]
Some previous discussion on a similar topic: https://github.com/dotnet/runtime/issues/23648#issuecomment-550251657

Original request was for adding StatusCode to the exception. Then it was considered to include the full HttpResponseMessage on the exception, but that was decided against because that would involve keeping a disposable on the exception. So StatusCode was eventually added as of .net5.0. 

GetFromJsonAsync uses EnsureSuccessStatusCode, so you will have access to `ex.StatusCode` to make decisions on. But I feel like if you know you may potentially want to parse different error codes and their response bodies you can just `SendAsync` and use the `response.Content.ReadFromJsonAsync` extensions after checking the `response.StatusCode`.

**Comment by snebjorn** [comment]
All web api's will eventually fail, so in praksis the simplified API should just be avoided?

**Comment by dferretti** [comment]
True, but I can see some scenarios where just knowing if I received a 404 vs 401 is enough to go on. Other errors might just bubble up without special handling. 
But in those scenarios where I do know that I might want to look deeper into the error responses, I can use SendAsync and be more intentional with my error handling, instead of relying on exceptions for control flow.

**Comment by karelz** [comment]
@eiriktsarpalis @layomia @steveharter ping?

**Comment by eiriktsarpalis** [comment]
At quick glance, the only source for `HttpResponseException` in the `GetFromJsonAsync` method is the [`HttpResponseMessage.EnsureSuccessStatusCode`](https://github.com/dotnet/runtime/blob/ddaa1c3c503f989db48102f50a693765e4e6ae2a/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L166-L178) check. The [JsonContent implementation itself](https://github.com/dotnet/runtime/blob/ddaa1c3c503f989db48102f50a693765e4e6ae2a/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpContentJsonExtensions.cs#L26-L70) will surface regular `JsonException`'s without any http related information.

Embedding response content in exception messages is something that should be avoided at all times. In most production environments exceptions get logged and leaking PII in log data can result in serious privacy incidents.

> But what kind of sensitive data would an error message from a web API contain?

Speaking from personal experience: a bad deployment of a reverse proxy in a third-party payments API resulted in successful responses having a 5xx status code.

I'm not sure if that has been considered before, but one potential compromise might be to add the `HttpResponseMessage` as a property in `HttpRequestException`:
```csharp
public class HttpRequestException
{
    public HttpResponseMessage? ResponseMessage { get; }
}
```
This would also eliminate concerns about unbuffered content as well.

**Comment by snebjorn** [comment]
So this would work?

```cs
try
{
    var response = await httpClient.GetFromJsonAsync<Foo>("...");
}
catch (HttpRequestException ex)
{
    var errorMsg = await ex.ResponseMessage.Content.ReadAsStringAsync();
    _logger.Error(errorMsg);
    throw;
}
```
Cause that'd be super fine 👍

**Comment by dferretti** [comment]
@eiriktsarpalis the github issue I linked above does actually talk about that specific idea, but decided against it because disposables and exceptions don't mix very well. 

@snebjorn 
In your example how is that any better than:
```c#
using var response = await httpClient.SendAsync("...");
if (response.StatusCode == HttpStatusCode.OK)
    return await response.Content.ReadFromJsonAsync<Foo>();

var errorMsg = await response.Content.ReadAsStringAsync();
_logger.Error(errorMsg); // still should be careful and not actually log this sort of thing...
throw new Exception(...); // or HttpRequestException or app-specific exception
```

Also the catch block you wrote above would need to check `ex.ResponseMessage` is not null, because HttpRequestException is used for other types of errors like network connectivity, DNS, etc, Even if you catch that exception it isn't guaranteed that there will be a response to parse at all.

Or if you really want to use the GetFromJsonAsync you can still do that and log the response code:
```c#
try
{
    var response = await httpClient.GetFromJsonAsync<Foo>("...");
}
catch (HttpRequestException ex)
{
    _logger.Error("Failed to get Foo: {statusCode}", ex.StatusCode); // available currently, and doesn't leak potentially sensitive response content
    throw;
}
```

**Comment by snebjorn** [comment]
> In your example how is that any better

Hmm, it isn't.
I think this can be written up as tunnel vison on using the simplified API when in practice it should be avoided in most real world cases.

Even if the response was added to the exception then having to deal with `try-catch` scopes is - well annoying :)

On another note. Can you point me to an article, or the like, that explains the dangers for logging? Cause I had considered sending logs to providers like CloudWatch safe.

**Comment by eiriktsarpalis** [comment]
> On another note. Can you point me to an article, or the like, that explains the dangers of logging? Cause I had considered sending logs to providers like CloudWatch safe.

I can't recommend any, but there's an abundance of material if you search for "pii logs".
