### ISSUE TITLE
Align BufferedStream DefaultBufferSize with Stream.CopyTo default buffer size

### ISSUE THREAD

**Issue by IgorMilavec** [dotnet/runtime#50197]
Stream.CopyTo{Async} is using some heuristics to determine the best buffer size (81920+ bytes). On the other hand BufferedStream still has a DefaultBufferSize of 4096.
Is this just an omission or am I missing the rationale?

**Comment by jkotas** [comment]
These two buffers serve different purposes, and so they have different sizes. There is no one universal buffer size that would be the right choice everywhere.

**Comment by jkotas** [comment]
Another example: Buffer size for BinaryReader is just 128: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs#L25

**Comment by IgorMilavec** [comment]
I fail to see, how they serve different purposes... IMO they both try to lessen the number of calls to the underlying stream. Can you please explain how they serve different purposes?
I understand there is no universal buffer size. But someone went to a great length to optimize one specific case, resulting in a factor of 20 (soon to be 40) difference in buffer sizes, which seems odd. This is why I am trying to understand the rationale.
BinaryReader is also an example of buffer sizes that I think would benefit from some discussion: BinaryReader is notoriously slow when reading from disk and greatly benefits from reading from a BufferedStream. Is there a specific use case that supports such a small buffer size?

**Comment by jkotas** [comment]
Fewer number of calls to the underlying stream at the cost having a large buffer does not necessarily improve performance. As the buffer size grows, caches become less effective, larger buffer sizes provide diminishing improvements and just cause the application to require more memory. 

The optimum buffer size depends on many factors: the fixed cost of the call to the underlying stream, how much processing is done with the data, how many of buffered operations are in flight simultaneously, etc. We guess what the typical use cases may be and choose the default buffer sizes based on benchmarking each case. The default won't work well for everybody and that's the libraries provide overloads to provide a custom buffer size in many APIs. Have you run into a case yourself where the default buffer size does not work well and need to override it?

In order to change the defaults, we would have to see overall improvement in benchmarks that represent typical use cases.

**Comment by adamsitnik** [comment]
I think that @jkotas has answered the question.
