### ISSUE TITLE
System.Text.Json - regression/breaking change on handling JsonSerializerOptions.MaxDepth

### ISSUE THREAD

**Issue by flensrocker** [dotnet/runtime#50321]
### Description

My usecase:  
Limit the serialization to flat objects without nested objects or arrays.

In .Net Standard 2.0 and .Net Core 3.1 (System.Text.Json 4.7.2) I use `MaxDepth = 2` in the `JsonSerializerOptions`, so that `JsonSerializer.Serialize` throws an exception.

With .Net 5.0 an object with an array is serialized without throwing an exception.

Is this change in behaviour intended?

### Configuration

* Which version of .NET is the code running on?  
  .Net Core 3.1 and .Net 5.0
* What OS and version, and what distro if applicable?  
  Windows 10
* What is the architecture (x64, x86, ARM, ARM64)?  
  x64
* Do you know whether it is specific to that configuration?  
  No.

### Regression?

My code throws on .Net Core 3.1, but not anymore on .Net 5.0.  
Throwing is expected.

### Other information

sample project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
  </PropertyGroup>

</Project>
```

Program.cs
```csharp
using System;
using System.Text.Json;

namespace JsonMaxDepthIssue
{
    class WithArray
    {
        public string[] Array { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var jsonOptions = new JsonSerializerOptions
            {
                IgnoreNullValues = true,
                WriteIndented = false,
                MaxDepth = 2,
            };

            var obj = new WithArray
            {
                Array = new [] { "", "" },
            };
            // throws on .Net Core 3.1 as expected
            // does not throw on .Net 5.0
            var json = JsonSerializer.Serialize(obj, jsonOptions);
            Console.WriteLine(json);
        }
    }
}
```

**Comment by eiriktsarpalis** [comment]
I can reproduce locally. Changing `MaxDepth` to 1 does force the same exception in .NET 5. This indicates to me that it could either be an off-by-one error or an intentional change in the definition of depth: @layomia or @Jozkee might have more context.

I don't consider this to be a breaking change TBH: `MaxDepth` is a setting designed to protect your application from stack overflows, so it should be treated as a rough upper bound rather than a precise setting.

**Comment by flensrocker** [comment]
Yes, I understand that I'm operating on the limits of `MaxDepth` and "missuse" it for my usecase.

`MaxDepth = 1` doesn't help me, because I can't serialize nearly anything with that.  
What I like to achieve is, that the users of my module just call it with really flat objects. And I understand that the definition of "flat" maybe special in my case, since I just want primitive properties without nesting and arrays.

What has changed is the meaning of "depth" of an array between the versions.

Here's the example, why `MaxDepth = 1` does not work:
```csharp
using System;
using System.Text.Json;

namespace JsonMaxDepthIssue
{
  class ValidObject
  {
    public string Property { get; set; }
  }

  class WithArray
  {
    public string Property { get; set; }
    public string[] Array { get; set; }
  }

  class Program
  {
    static void Main(string[] args)
    {
      var jsonOptions1 = new JsonSerializerOptions
      {
        IgnoreNullValues = true,
        WriteIndented = false,
        MaxDepth = 1,
      };

      var jsonOptions2 = new JsonSerializerOptions
      {
        IgnoreNullValues = true,
        WriteIndented = false,
        MaxDepth = 2,
      };

      var validObj = new ValidObject
      {
        Property = "valid",
      };
      // MaxDepth 2: does not throw on .Net Core 3.1 and .Net 5.0 as expected
      Console.WriteLine("MaxDepth 2");
      var json = JsonSerializer.Serialize(validObj, jsonOptions2);
      Console.WriteLine(json);

      Console.WriteLine();

      try
      {
        // MaxDepth 1: does throw on .Net Core 3.1 and .Net 5.0
        Console.WriteLine("MaxDepth 1");
        json = JsonSerializer.Serialize(validObj, jsonOptions1);
        Console.WriteLine(json);
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.Message);
      }

      Console.WriteLine();

      var invalidObj = new WithArray
      {
        Property = "invalid because of array",
        Array = new[] { "invalid", "array" },
      };
      try
      {
        // throws on .Net Core 3.1 as expected
        // does not throw on .Net 5.0
        Console.WriteLine("MaxDepth 2 with array");
        json = JsonSerializer.Serialize(invalidObj, jsonOptions2);
        Console.WriteLine(json);
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.Message);
      }

      Console.WriteLine();

      try
      {
        Console.WriteLine("MaxDepth 1 with array");
        json = JsonSerializer.Serialize(invalidObj, jsonOptions1);
        Console.WriteLine(json);
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.Message);
      }
    }
  }
}
```

**Comment by eiriktsarpalis** [comment]
The underlying cause for this issue is that the array converter optimizes for element types using [internal value converters](https://github.com/dotnet/runtime/blob/95147163dac477da5177f5c5402ae9b93feb5c89/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/ArrayConverter.cs#L46), skipping the relevant converter infrastructure that among other things [checks for writer depth](https://github.com/dotnet/runtime/blob/95147163dac477da5177f5c5402ae9b93feb5c89/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L318). Minimal reproduction:
```csharp
        [Fact]
        static void Repro()
        {
            var jsonOptions = new JsonSerializerOptions
            {
                MaxDepth = 1
            };

            string[] value = new[] { "" };

            Assert.Throws<JsonException>(() => JsonSerializer.Serialize(value, jsonOptions));
        }
```
Since internal value converters do not serialize nested members, this discrepancy only affects object graphs of `MaxDepth + 1` depths. I think this is a reasonable trade-off vis a vis having a fast path for array serialization. As mentioned earlier, `MaxDepth` is meant to be used as a rough upper bound to protect from stack overflows, I would therefore think that the current behavior is well within the intended parameters of the feature. Therefore, I'm going to close this as wontfix/by design behavior.

**Comment by flensrocker** [comment]
Thank you for the explanation!
