### ISSUE TITLE
Lack of DynamicallyAccessedMemberTypes for any default constructor forces keeping unused types

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#50353]
One example is https://github.com/dotnet/runtime/blob/72f57669b2ca032c4eb86251e2cadec611426ded/src/mono/System.Private.CoreLib/src/System/RuntimeType.Mono.cs#L1838 which has an annotation for any constructor even if only the default constructor is considered. This keeps unnecessary dependencies like `System.Runtime.Serialization.StreamingContext` via `EnumComparer<T>` private ctors. I far as I know there is no workaround for this.

/cc @eerhardt @vitek-karas

**Comment by eerhardt** [comment]
Looking through all the callsites of `CreateInstanceForAnotherGenericParameter`, it looks like either all the types passed into it already have a public parameterless constructor, or they are internal classes, so we can make the constructor public on them.

The only one that doesn't look this way is 

https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.cs#L180-L183

But that class isn't public in a contract - just in the implementation, and the comment indicates it needs to be public due to binary serialization. Since this isn't in a public contract, we could make its parameterless constructor public.

Then we can change `CreateInstanceForAnotherGenericParameter` implementation to only look for public parameterless constructors.

**Comment by marek-safar** [comment]
> Then we can change CreateInstanceForAnotherGenericParameter implementation to only look for public parameterless constructors.

I guess that could work.

**Comment by eerhardt** [comment]
I can put up a PR after https://github.com/dotnet/runtime/pull/50232 is merged.
