### ISSUE TITLE
Deadlock when calling System.Environment.Exit(int exitCode) during Startup.Configure(..)

### ISSUE THREAD

**Issue by armingerten** [dotnet/runtime#50397]
In some situations my web application requires to immediately quit during start-up. When doing so via `System.Environment.Exit(int exitCode)`, the dotnet process does not exit.

Minimal set-up to reproduce:

```csharp
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

```csharp
public override void Configure(IApplicationBuilder app)
{
	System.Environment.Exit(1);
}
```

It seems that in this scenario `Set()` will no longer be called on the instance of ManualResetEventSlim passed to `AttachCtrlcSigtermShutdown(..)` resulting in the `Shutdown()` method to block indefinitely.

https://github.com/aspnet/Hosting/blob/97c9510a95e676324ed8fa03d8b6dcf3b1c19ccf/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L134-L162

One possible solution could be applying the `WebHostOptions.ShutdownTimeout` when waiting for the manual reset event.

_System Info:_
- dotnet core: 2.1
- Microsoft.AspNetCore.Hosting: 2.1.1

**Comment by davidfowl** [comment]
Here's the repro with the generic host:

```
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = Host.CreateDefaultBuilder()
        .ConfigureServices(services =>
        {
            services.AddHostedService<Worker>();
        })
        .Build();

host.Run();

class Worker : IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken)
    {
        Environment.Exit(1);
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

Results in hanging at this:

![image](https://user-images.githubusercontent.com/95136/112920973-d5cb7980-90be-11eb-9548-f4f90e45841d.png)

**Comment by davidfowl** [comment]
@janvorli All of hosting weird designs are around trying to let the program continue execution before sigterm tears the application down (blocking on a wait handle in the event and waiting for the application code to signal it when it's done). Is there anyway we can stop doing this? Any cleaner way the runtime can support this natively without us doing these tricks?

**Comment by janvorli** [comment]
@davidfowl I am not sure if I fully understand what tricks you are talking about, so let me answer a bit broadly. We've been trying to get rid of all attempts to synchronize with process exiting / cleaning stuff up in the runtime during the past years, as they've often lead to intermittent, sometimes very rare and hard to debug deadlocks during process exit. Or process shutdown delays. On Unix, after the main thread exits, the secondary threads can still be running code (including managed code) for some time until the OS shuts down the process. 

As for SIGTERM handling in the runtime, we cannot execute the termination code in the SIGTERM handler directly, as only so called async safe functions can be called from it. The reason is that the signal can be delivered to any thread of the process any time. So for example, if the thread that the signal handler is called on was inside of malloc code and the handler then attempted to allocate memory too, it could lead to deadlock or memory corruption depending on where in the malloc code the thread was running when it was interrupted for the signal. That's why we run it on a special thread and the signal handler just notifies that thread.

**Comment by davidfowl** [comment]
Right. What we're trying to do is let the main thread unwind. Many systems use SIGTERM as a way to start a graceful shutdown. To make this work we need to start the shutdown process and wait for some timeframe until it's done. To coordinate that, we set up a bunch of events to allow the main thread to exit before continuing the process exit handler.

Ideally we could have the runtime coordinate this so that we can remove our code (similar to how Console.CancelKeyPress allows cancelling shutdown). Here's a narrowed down piece of code:

```C#
using System;
using System.Threading;

namespace ConsoleApp35
{
    class Program
    {
        static void Main(string[] args)
        {
            var waitForProcessShutdownStart = new ManualResetEventSlim();
            var waitForMainExit = new ManualResetEventSlim();

            AppDomain.CurrentDomain.ProcessExit += (sender, e) =>
            {
                // Tell everyone that shutdown has started
                waitForProcessShutdownStart.Set();

                Console.WriteLine("Waiting for main");
                // Don't unwind until main exists
                waitForMainExit.Wait();
            };

            Console.CancelKeyPress += (sender, e) =>
            {
                e.Cancel = true;

                // Tell everyone that shutdown has started
                waitForProcessShutdownStart.Set();
            };

            Console.WriteLine("Waiting for shutdown");
            // Wait for shutdown to start
            waitForProcessShutdownStart.Wait();

            // This will cause the hang because it invokes the process exit handler directly
            // Environment.Exit(1);

            // Now we're done with main, tell the shutdown handler
            waitForMainExit.Set();
        }
    }
}
```

**Comment by davidfowl** [comment]
To makes matters more complex, `Environment.Exit`, synchronously triggering the OnProcessExit callback. In the above scenario this causes a deadlock. The most pragmatic thing we could do here is to timeout the wait so it isn't a permanent deadlock...

cc @maryamariyan

**Comment by davidfowl** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/50527
