### ISSUE TITLE
System.Diagnostics.CorrelationManager is not thread-safe

### ISSUE THREAD

**Issue by mahalex** [dotnet/runtime#50480]
### Description

The following code crashes due to issue in `System.Diagnostics.CorrelationManager`, which appears to be not thread-safe (even though it uses an `AsyncLocalStackWrapper`).
```csharp
using System.Diagnostics;
using System.Threading;

namespace CorrelationManagerExample
{
    class Program
    {
        static void Main(string[] args)
        {
            var t1 = new Thread(Method);
            var t2 = new Thread(Method);
            t1.Start();
            t2.Start();
        }

        private static void Method()
        {
            Trace.CorrelationManager.StartLogicalOperation();
            Trace.CorrelationManager.StopLogicalOperation();
        }
    }
}
```

### Configuration

I verified by compiling and running this code using .NET SDK 5.0.201 on Windows 10 (x64).

### Regression?

A similar issue was reported in 2005 against the .NET Framework implementation, [and was apparently fixed then](https://social.msdn.microsoft.com/forums/vstudio/en-US/00ab1ca0-876a-4f82-ae95-3d6d6668cf8e/correlationmanager-andor-logicaloperationstack-not-thread-safe).
So recent versions of .NET Framework do not have this issue (I verified this by re-targeting the project to net461).

### Other information

Stack trace:
```
Unhandled exception. System.InvalidOperationException: Stack empty.
   at System.Collections.Stack.Pop()
   at System.Diagnostics.CorrelationManager.AsyncLocalStackWrapper.Pop()
   at System.Diagnostics.CorrelationManager.StopLogicalOperation()
   at CorrelationManagerExample.Program.Method() in C:\git\CorrelationManagerExample\CorrelationManagerExample\Program.cs:line 19
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by ChristophLindemann** [comment]
The code seems to be a _verbatime copy_ (apart from reordering members) of an _idea_ from @stephentoub that he posted as a comment to [the original code review](https://github.com/dotnet/corefx/pull/12527#discussion_r83333871), even though he noted: "Take this with a grain of salt... I've not tested it so there may be an issue here and there."

This copy/paste is also the reason for #38176

**Comment by dradovic** [comment]
I guess that this in turn affects using the `HttpClient` in parallel requests. What I do is:

    using (var client = _httpClientFactory.CreateClient("MyService"))
    {
        var response = await client.PostAsync(...);
        await EnsureSuccessStatusCode(response);
        ...
    }

and under heavy load I sometimes see:

>  Error Message:
   System.InvalidOperationException : Stack empty.
  Stack Trace:
     at System.Collections.Stack.Pop()
   at System.Diagnostics.CorrelationManager.AsyncLocalStackWrapper.Pop()
   at System.Diagnostics.CorrelationManager.StopLogicalOperation()
   at Microsoft.Extensions.Logging.TraceSource.TraceSourceScope.Dispose()
   at Microsoft.Extensions.Logging.Logger.Scope.Dispose()
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
    ...

How could I mitigate this until the issue is fixed? I don't have a possibility to tell the `HttpClient` to not do any logging, do I?

**Comment by KalleOlaviNiemitalo** [comment]
You could try removing every Microsoft.Extensions.Http.IHttpMessageHandlerBuilderFilter from the IServiceCollection. That way, LoggingHttpMessageHandlerBuilderFilter.Configure would not get the chance to create a  LoggingScopeHttpMessageHandler.

**Comment by dradovic** [comment]
@stephentoub Great! Any chance this goes into 6.0 as it is LTS? This bug makes using `HttpClient` a dangerous thing in production.

**Comment by stephentoub** [comment]
> Great! Any chance this goes into 6.0 as it is LTS?

The issue has existed since the beginning of .NET Core, there's a simple workaround (just touch Trace.CorrelationManager once somewhere in your startup path to ensure it's initialized), and there have been few complaints about it over years of existing... that tends to not make it a great candidate for servicing.

For starter, though, it'd be helpful if you could confirm that workaround actually addresses the issue you see; if it doesn't, then there's an additional issue lurking somewhere and the fix I submitted while necessary is insufficient.  If it does address your issue, then I can at least raise it for consideration, but no promises on it actually being taken.

> This bug makes using HttpClient a dangerous thing in production.

It's not really HttpClient.  It's HttpClientFactory and whatever is injecting a logger based on TraceSource.

**Comment by dradovic** [comment]
@stephentoub Thanks for the detailed background explanations. I can indeed confirm that we are using the `HttpClientFactory` (the recommended way of getting hold of a `HttpClient`).

And I'm super happy to test the fix for you. Would it mean that I need to checkout/compile the sources themselves? Or is your fix available through a preview NuGet?

**Comment by stephentoub** [comment]
Literally just add:
```C#
_ = Trace.CorrelationManager;
```
at the beginning of your app (when everything is still sequential) :)

**Comment by dradovic** [comment]
Just to confirm that since I've introduce your work-around, I don't see the issue appearing anymore.

Once again, thank you.
