### ISSUE TITLE
Reference conflicts using System.ComponentModel.Annotations from aspnet core 3.1

### ISSUE THREAD

**Issue by juanan** [dotnet/runtime#50485]
Hi,

I have a netstandard2.0 library that contains a reference to the package System.ComponentModel.Annotations 5.0.0.
When the netstandard2.0 library is published as a nuget package, the System.ComponentModel.Annotations library version is 4.2.0.0.

![image](https://user-images.githubusercontent.com/17723190/113163259-46e66a80-9240-11eb-817b-3d8e6bf8740e.png)

Now from an aspnet core 3.1 project I add a reference to my netstandard2.0 nuget package and after building the .net core project the library System.ComponentModel.Annotations 5.0.0 is in the bin folder so at the end when I run my app I get

Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies

How do I fix this?
My running project is .net core so I can not fix it using assembly redirects.

**Comment by juanan** [comment]
Any idea pls?

**Comment by ericstj** [comment]
> Now from an aspnet core 3.1 project I add a reference to my netstandard2.0 nuget package and after building the .net core project the library System.ComponentModel.Annotations 5.0.0 is in the bin folder so at the end when I run my app I get
Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies
How do I fix this?
My running project is .net core so I can not fix it using assembly redirects.

Can you check your application's deps file to ensure it contains `System.ComponentModel.Annotations`?  The deps file is effectively what tells the .NETCore loader about bindingRedirects-like information.  This could happen if your app was using something like a binary reference to your library rather than a project or package reference.  This could also happen if your application was loading assemblies in a way that ignored the deps file cc @agocke @vitek-karas

**Comment by roji** [comment]
Closing as no answer was provided.
