### ISSUE TITLE
Scenerio: Slow startup for ASP.NET Core Fortunes Platform test

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#50501]
The ASP.NET Core Fortunes Platform test has an incongruously large start-up time; might be something to look at:

Its different from the others as it also pulls in npgsql dll and HtmlEncoder; however it still seems disproportionately long?

![image](https://user-images.githubusercontent.com/1142958/113189958-b4e85d00-9253-11eb-942e-3a8fb4eb9848.png)

/cc @sebastienros @roji

**Comment by sebastienros** [comment]
Since the Caching scenario has been added the data is loaded on startup, for all database scenarios. The difference between 5.0 and 6.0 is still 20%, I would have hope the other way around. However they are not be using the same version of npgsql, so this might also be a reason. Traces with crank are done after the startup though.

**Comment by benaadams** [comment]
Ah so the startup measurement includes loading from the db?

**Comment by sebastienros** [comment]
https://github.com/aspnet/Benchmarks/blob/main/src/BenchmarksApps/Kestrel/PlatformBenchmarks/Program.cs#L41

**Comment by sebastienros** [comment]
I sense a PR to only do it on the cache scenario ... or on the first request of the cache scenario

**Comment by benaadams** [comment]
Will close then until loading from the DB is not part of startup
