### ISSUE TITLE
PDB support for ilasm

### ISSUE THREAD

**Issue by kyulee1** [dotnet/runtime#5051]
Currently ilasm /DEBUG\* is ignored on CoreCLR.

**Comment by ivanpovazan** [comment]
Ilasm can now generate PDB in portable PDB format #37702 
This feature is available through command line arguments: -debug -pdbfmt=portable

**Comment by akoeplinger** [comment]
@ivanbasov awesome work! would it make sense to use `-debug:portable` instead of a separate argument to be consistent with csc/roslyn?

**Comment by ivanpovazan** [comment]
@akoeplinger thank you.

I agree it would be nice to have consistency across the tools, but I have introduced a separate argument in order to avoid ambiguity with existing ilasm `-debug` options:
`-debug:opt` 
`-debug:impl`

So the question is not about whether these options should be merged but whether it will be clear enough for ilasm users.
@noahfalk what do you think?

**Comment by AaronRobinsonMSFT** [comment]
>So the question is not about whether -pdbfmt and -debug options can be merged but whether it will be clear enough for ilasm users.

@ivanpovazan I would agree that taking inspiration from the `csc` options is appropriate here.

```
-debug[+|-]                   Emit debugging information
-debug:{full|pdbonly|portable|embedded}
                              Specify debugging type ('full' is default,
                              'portable' is a cross-platform format,
                              'embedded' is a cross-platform format embedded into
                              the target .dll or .exe)
```

Since the `debug` flag appears to have a predefined set of options for `ilasm` and I personally wouldn't want to deal with the matrix of multiple argument, I propose slightly modifying your suggestion to align with existing `ilasm` syntax and acknowledge `csc` convention.

`-debugfmt={full|portable}`

At this point we can support `full` and `portable`. In the future we can add `embedded` as the need arises.

**Comment by noahfalk** [comment]
I'm fine with the approach @AaronRobinsonMSFT suggested above. The thing I care about most is that we don't break any CLI syntax for scripts/build projects already succesfully using ilasm. Having new syntax that is understandable/consistent with csc is certainly nice as well. I don't fret about it too much because I assume there are a relatively small set of people in the world who will need to format ad-hoc ilasm commands.

**Comment by jkotas** [comment]
The follow up work is tracked by #39436
