### ISSUE TITLE
Annotate unsupported APIs in System.Security.*

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#50528]
As part of https://github.com/dotnet/runtime/issues/47228 i am running an analyzer to detect APIs throwing PNSE but not annotated with Obsolete/SupportedOSPlatform/UnsupportedOSPlatform attributes, we need to annotate them so that developers get warnings when they use them unexpectedly

For now, I have results only for cross-platform builds, analysis of targeted builds are coming soon where more APIs could be detected

API | Comment | Suggestion | Location
-- | -- | -- | --
'SecurityContext.Capture()' | throws unconditionally | All APIs throws [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(11,51)
'SecurityContext.CreateCopy()' | throws unconditionally | [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(12,47)
'SecurityContext.Dispose()' | throws unconditionally | [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(13,33)
'SecurityContext.IsFlowSuppressed()' | throws unconditionally | [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(14,49)
'SecurityContext.IsWindowsIdentityFlowSuppressed()' | throws unconditionally | [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(15,64)
'SecurityContext.RestoreFlow()' | throws unconditionally | [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(16,44)
'SecurityContext.Run(SecurityContext,   ContextCallback, object)' | throws unconditionally | [Obsolete] the type| libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(17,107)
'SecurityContext.SuppressFlow()' | throws unconditionally | [Obsolete] the type | libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(18,57)
'SecurityContext.SuppressFlowWindowsIdentity()' | throws unconditionally| [Obsolete] entire type| libraries\System.Security.Permissions\src\System\Security\SecurityContext.cs(19,72)

EDIT: Adding APIs found for `netstandard` targeted builds
API | Comment | Suggestion | Location
-- | -- | -- | --
'ECDiffieHellmanCng.FromXmlString(string,   ECKeyXmlFormat)'  | Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDiffieHellmanCng.Xml.cs(10,13)
'ECDiffieHellmanCng.ToXmlString(ECKeyXmlFormat)' |  Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDiffieHellmanCng.Xml.cs(15,13)
'ECDiffieHellmanCngPublicKey.ToXmlString()'  | Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDiffieHellmanCngPublicKey.cs(37,13)
'ECDiffieHellmanCngPublicKey.FromXmlString(string)' | Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDiffieHellmanCngPublicKey.cs(42,13)
'ECDsaCng.FromXmlString(string,   ECKeyXmlFormat)' | Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDsaCng.cs(131,16)
'ECDsaCng.ToXmlString(ECKeyXmlFormat)' | Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDsaCng.cs(143,16)
'ECDiffieHellmanOpenSslPublicKey.ToXmlString()' | Internal   API, unconditionally throwing | obsolet if referenced in public API | libraries\Common\src\System\Security\Cryptography\ECDiffieHellmanOpenSslPublicKey.cs(42,17)
'ECDiffieHellmanOpenSslPublicKey.ToByteArray()' |  Internal   API, unconditionally throwing |obsolete if referenced in public API| libraries\Common\src\System\Security\Cryptography\ECDiffieHellmanOpenSslPublicKey.cs(47,17)
'CmsSigner.CmsSigner(CspParameters)' | It has comment possibly adding windows support | but no issue attached, obsolete | libraries\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\CmsSigner.cs(63,55)
'SignerInfo.ComputeCounterSignature()'  | Uncondidionally throws | obsolete | libraries\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\SignerInfo.cs(296,13)
'PermissionSet.PermitOnly()' | Uncondidionally throws | it has ifdef-ed obsolete | libraries\System.Private.CoreLib\src\System\Security\PermissionSet.cs(43,36)
'CodeAccessPermission.PermitOnly()' | Uncondidionally throws | it has ifdef-ed obsolete | libraries\System.Security.Permissions\src\System\Security\CodeAccessPermission.cs(22,36)

Note: We are suggesting to add [Obsolete] for the APIs only supported in .Net framework but not supported in .NetCore, with the corresponding Message, DiagnosticId, and UrlFormat https://github.com/dotnet/runtime/blob/cecc76a29a8b6c1fca181a38f076b4d949081746/src/libraries/System.Net.Requests/src/System/Net/AuthenticationManager.cs#L17  You can claim the next available DiagnosticId from [Obsoletions.cs ](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Obsoletions.cs).

If it is only supported on a specific platform(s) consider adding [SupportedOSPlatform("platformName")] or if it is unsupported on a specific platform(s) [UnsupportedOSPlatform("platformName")] attribute instead

cc @jeffhandley @terrajobst @GrabYourPitchforks

**Comment by buyaa-n** [comment]
Notes need to consider:
- If the API has an issue associated with future support we are not suggesting to add [Obsolete], we need to make sure that we are not gonna support the API ever and related issue should be closed, then we can add [Obsolete]
- If the API is internal/private the annotation is not necessary, but they could point you to the public API needs annotation

**Comment by vcsjones** [comment]
Some of these APIs that "unconditionally throw" are virtual and are expected to be overridden in derived classes, so while the base class throws, they aren't necessarily obsolete because derived classes override them and some functionality depend on these classes. I think this would be the case for all of the methods on the `HMAC` class. So I do not think those should be obsolete or otherwise annotated.

**Comment by buyaa-n** [comment]
> I think this would be the case for all of the methods on the HMAC class. So I do not think those should be obsolete or otherwise annotated.

That is right, removed HMAC related APIs, but others looks valid

**Comment by buyaa-n** [comment]
Adding few more:
API | Comment | Suggestion | Location
-- | -- | -- | --
'ECDsa.ECDsaImplementation.ECDsaSecurity Transforms.ExportExplicitParameters(bool)'  |  unconditionally throwing, reachable on iOS, tvOS, OSX unreachable:   browser | UnsupportedOSPlatform("iOS"), UnsupportedOSPlatform("tvOS"), UnsupportedOSPlatform("tOSX") |  \libraries\Common\src\System\Security\ Cryptography\ECDsaSecurityTransforms.cs(209,21)
'DSA.CreateCore()' | unconditionally throwing, reachable on iOS, tvOS unreachable: browser | UnsupportedOSPlatform("iOS"), UnsupportedOSPlatform("tvOS") | \libraries\System.Security.Cryptography.Algorithms \src\System\Security\Cryptography \DSA.Create.NotSupported.cs(12,13)
'Rfc2898DeriveBytes.CryptDeriveKey(string, string, int, byte[])'  | unconditionally throwing reachable on Android, Unix, iOS, tvOs, OSX, Windows unreachable: browser | Only implemented for PasswordDeriveBytes and has SupportedOSPlatform("windows") attribute, should we obsolete or also add SupportedOSPlatform("windows") |  libraries\System.Security.Cryptography.Algorithms\src \System.Security.Cryptography.Algorithms.csproj]

CC @bartonjs

**Comment by vcsjones** [comment]
> `DSA.CreateCore()`

The public entry, `Create` is already marked with `UnsupportedOSPlatform`:

https://github.com/dotnet/runtime/blob/a2f2a629328a136c2cd18f2cd729e3854de2aeb4/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/DSA.cs#L38

So I think that one is already taken care of.

**Comment by buyaa-n** [comment]
Removed, thanks

**Comment by vcsjones** [comment]
@buyaa-n is this something you are working on or is this something I can contribute to? Some of these look reasonable.

**Comment by vcsjones** [comment]
> 'ECDsa.ECDsaImplementation.ECDsaSecurity Transforms.ExportExplicitParameters(bool)'

I'm not sure adding an `UnsupportedOSPlatform` here would be ergonomic. The issue is that the public API `ExportExplicitParameters` is accessible via the virtual `ECDsa.ExportExplicitParameters`. We would have to decorate the virtual with the UOSP attribute, which would not interact well with derived classes (our own or developers' own). To illustrate:

```csharp
using System.Runtime.Versioning;

Foo f = new Bar();
f.Do(); // This is actually a `Bar` but since it's called through the base type, a compiler warning appears.

public class Foo
{
    [UnsupportedOSPlatform("iOS")]
    public virtual object Do() => throw new PlatformNotSupportedException();
}

public class Bar : Foo
{
    public override object Do() => new();
}
```

Similar concerns lie with `ToXmlString`, `FromXmlString`, and `ToByteArray`. It seems a little odd to obsolete an `override` when a user derived type could override one of these from the base class and implement it.

Some of these do make sense to me to obsolete:

1. `Rfc2898DeriveBytes.CryptDeriveKey` - it's unimplemented and can't be implemented xplat since it's a Windows thing. I'm unaware of demand to bring it back.
2. `CmsSigner.CmsSigner(CspParameters)` seems weird. It manufactures a certificate on the fly based on those CspParameters. It makes sense to obsolete since it can only be implemented on Windows. If we really, really wanted "make me a cert on the fly" behavior, it probably makes sense to implement a new API that accepted an `AsymmetricAlgorithm` or something.
3. `SignerInfo.ComputeCounterSignature()` There's an overload that accepts the `CmsSigner`, so I think it makes sense to obsolete.

I don't see any immediately actionable things. Presumably the obsoletions need to go through API review, and I don't know if we're taking any more obsoletions for 6.0 (granted all of them `throw`, so it's not exactly a breaking change).

**Comment by jeffhandley** [comment]
We could take these 3 obsoletions without going through API Review--just code review from @bartonjs and @GrabYourPitchforks. I'm comfortable taking them before the August 17th cutoff for .NET 6, especially since it's not a breaking change.

**Comment by buyaa-n** [comment]
Adding last findings, these are all internal APIs / overrides in the different platform source PALs, might be false positive but might worth checking 

API | Comment | Reachable platforms | Location
-- | -- | -- | --
'EccSecurityTransforms.ExtractPublicKeyFromPrivateKey(ref   ECParameters)' | unconditionally throws PNSE | reachable on iOS, tvOS | Common\src\System\Security\Cryptography\EccSecurityTransforms.iOS.cs(19,16)
'EccSecurityTransforms.ExtractPublicKeyFromPrivateKey(ref   ECParameters)' unconditionally throws PNSE | reachable on iOS, tvOS | Common\src\System\Security\Cryptography\EccSecurityTransforms.iOS.cs(19,16)
'RC2Implementation.CreateTransformCore(CipherMode,   PaddingMode, byte[], int, byte[]?, int, int, int, bool)' | unconditionally   throws PNSE | reachable on Android | System.Security.Cryptography.Algorithms\src\Internal\Cryptography\RC2Implementation.Android.cs(23,13)
'AppleCertificatePal.FriendlyName.set' | unconditionally throws PNSE | reachable on iOS, OSX, tvOS | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.OSX\AppleCertificatePal.cs(198,17)
'AppleCertificatePal.Archived.set' |  unconditionally throws PNSE | reachable on iOS, OSX, tvOS | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.OSX\AppleCertificatePal.cs(313,17)
'OpenSslX509CertificateReader.Archived.set' |  unconditionally throws PNSE | reachable on Unix | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Unix\OpenSslX509CertificateReader.cs(405,17)
'OpenSslX509CertificateReader.FriendlyName.set' |  unconditionally throws PNSE | reachable on Unix | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Unix\OpenSslX509CertificateReader.cs(415,17)
'AndroidCertificatePal.Archived.set' |  unconditionally throws PNSE | reachable on Android | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Android\AndroidCertificatePal.cs(262,17)
'AndroidCertificatePal.FriendlyName.set' |  unconditionally throws PNSE | reachable on Android | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Android\AndroidCertificatePal.cs(272,17)
'AppleCertificatePal.CopyWithPrivateKey(DSA)' |  unconditionally throws PNSE | reachable on iOS, tvOS | System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.iOS\AppleCertificatePal.Keys.cs(21,13)

**Comment by vcsjones** [comment]
* `FriendlyName` and `Archived` were marked with `SupportedOSPlatform` in https://github.com/dotnet/runtime/pull/53877 to be Windows only.
* `CopyWithPrivateKey(DSA)` was marked with `UnsupportedOSPlatform` here

    https://github.com/dotnet/runtime/blob/604abc216ada9b8ebf39c38d725a08c04f87c563/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/DSACertificateExtensions.cs#L14-L17

* `ExtractPublicKeyFromPrivateKey` I don’t think there is a good way to annotate this as it is not really a public API. It means that iOS / tvOS cannot import EC parameters that are lacking Q but have D.


It does look like we can annotate `RC2` to indicate that it is not supported on Android.

**Comment by vcsjones** [comment]
> Adding last findings

Just to summarize findings that I think are actionable:

- [ ] `Rfc2898DeriveBytes.CryptDeriveKey` obsolete: https://github.com/dotnet/runtime/pull/57002
- [ ] `System.Security.SecurityContext` obsolete https://github.com/dotnet/runtime/pull/57035
- [ ] `CmsSigner.CmsSigner(CspParameters)` obsolete
- [ ] `SignerInfo.ComputeCounterSignature()` obsolete
- [ ] `RC2.Create()` add `[UnsupportedOSPlatform(“android”)]`

It would still be useful to have someone else validate this.

**Comment by bartonjs** [comment]
* Rfc2898DeriveBytes.CryptDeriveKey obsolete
  *  Agreed
* System.Security.SecurityContext obsolete
  * Agreed (merged!)
* CmsSigner.CmsSigner(CspParameters) obsolete
  * Agreed (double checked that we didn't make it work on Windows)
* SignerInfo.ComputeCounterSignature() obsolete
  * Agreed (double checked that we didn't make it work on Windows)
* RC2.Create() see below

For RC2-browser we seem to have marked the whole type, which was probably a bit of an overreach, because someone /could/ provide a working implementation of RC2.  RC2.Create() on android I'm pretty sure succeeds, but returns an object that fails if you try to actually use it.  Part of me thinks it'd be better to just put the PNSE there, but maybe there's a legit use case I can think of for the dummy RC2 instance.

So... yeah, marking RC2.Create as Unsupported-android is probably right.  With a comment that says a more formal version of "yeah, it returns, but the object is going to throw if you call CreateEncryptor or CreateDecryptor... so it's the same as not working"

As for other things in @buyaa-n 's tables:

* ECDiffieHellmanCng.ToXmlString/FromXmlString
  * Obsolete.
  * We never added them in Core, no one ever complained (to my recollection).  The base class version literally never worked (even in NetFX when it was added), and the derived type is Windows-only.
* ECDiffieHellmanCngPublicKey.ToXmlString/FromXmlString
  * Obsolete (same as above, probably same diagnostic ID)
* ECDsaCng.ToXmlString/FromXmlString
  * Obsolete (same as above, probably same diagnostic ID)
* ECDiffieHellmanPublicKey.ToXmlString
  * Obsolete
  * We've never had a derived type in Core that didn't throw.  Let's just obsolete the base type's version.  Maybe the same diagnostic ID as above.
  * Wasn't directly on the table, but addresses the ECDiffieHellmanOpenSslPublicKey case :smile:

I think that only leaves ECDiffieHellmanPublicKey.ToByteArray and ECDiffieHellmanPublicKey..ctor(byte[]).  I'd support Obsoleting these.  I... thought... we had added SPKI export on this type, but I don't see it.  So maybe we need to hold this one back one release.  Using inbox types the ToByteArray only works on Windows, but since it's a virtual I don't like putting a SupportedOSAttribute on it.

**Comment by vcsjones** [comment]
> I... thought... we had added SPKI export on this type, but I don't see it.

We did, unless I am misunderstanding what API you're thinking of. 

https://github.com/dotnet/runtime/blob/c5faf00fd5df6ffb619aa8d2592618fc982f36ff/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECDiffieHellmanPublicKey.ExportParameters.cs#L50

**Comment by vcsjones** [comment]
I'll tackle the rest of these over the next day or two.

**Comment by bartonjs** [comment]
No, that's it.  Just that I wasn't smart enough to remember to look in a partial file.

**Comment by vcsjones** [comment]
> ECDiffieHellmanPublicKey.ToXmlString

Just so I am super clear, we are okay obsoleting a virtual on an abstract class that developers can inherit from for a RC?

**Comment by bartonjs** [comment]
> Just so I am super clear, we are okay obsoleting a virtual on an abstract class that developers can inherit from for a RC? Or would it be better to push those for .NET vNext?

I am.  @ericstj or @danmoseley would you care to object?

If there are more than three NuGet packages that have extended ECDiffieHellmanPublicKey I'll... I don't know... be flabbergasted.  ("MC an API Review while only speaking French" (a language I don't know) sounds like a fun consequence, but would be incredibly unproductive).  Even then, I doubt they'd've implemented To/FromByteArray in a way that interoperated with the inbox CNG one.  Since https://github.com/novotnyllc/RSAKeyVaultProvider/tree/master/RSAKeyVaultProvider didn't do ECDH I'll even lower that expectation to two derived types.

**Comment by vcsjones** [comment]
> If there are more than three NuGet packages that have extended ECDiffieHellmanPublicKey I'll... I don't know... be flabbergasted. "MC an API Review while only speaking French" (a language I don't know) 

I need to figure out how to publish a few NuGet packages, then.

Fair enough, just thought I'd ask. Will do those next then.

**Comment by bartonjs** [comment]
> I need to figure out how to publish a few NuGet packages, then.

Had there been an actual "eat my hat" type consequence I definitely would have thrown in a disclaimer like "(offer valid only for non-prerelease packages already present on nuget.org at the original time of this post)".  I may not be smart enough to remember to look in partial files, but I'm not _that_ naive :smile:.

**Comment by danmoseley** [comment]
@marklio is this an assumption we can easily verify from Nuget packages?

**Comment by marklio** [comment]
I can look at this. I'll follow up with @bartonjs offline.

**Comment by marklio** [comment]
OK, the landscape here is complicated, but in general it looks like @bartonjs's wager holds up, particularly through the lens of "ecosystem code exposed to such a change". I definitely found types that inherit from System.Security.Cryptography.ECDiffieHellmanPublicKey, but almost universally these are types in our own shipped assemblies (System.Core, System.Security.Cng/Algorithms/OpenSsl). These assemblies are in our own packages, as well as redistributed in other packages at a pretty high rate. None of those really represent problematic scenarios WRT deprecation. The few that were genuinely non-product types are in assemblies that are not published on NuGet.org, and instead come from other locations like internal test trees/tools.

**Comment by bartonjs** [comment]
~~"Bonjour les amis. Nous sommes mardi et environ 10h à Redmond, il est donc temps de passer en revue l'API. Vous avez peut-être remarqué que je parle en français aujourd'hui. Non, je **ne** parle pas français, mais je peux lire des choses sur Google Translate dans ce que je pense ressemble à du français, et c'est loin d'être la bonne réponse mais le mieux que je puisse faire. Pourquoi? J'ai fait un mauvais pari sur Internet."~~

Yeah, I knew it.  Obscure type, no clear implementation.  No derivers.  Obvs.

Thanks, @marklio :smile:.

**Comment by vcsjones** [comment]
@bartonjs I was not able to get to the rest of these before the 6.0 branch was taken. Should this be moved to 7.0.0 or should I prioritize this so that it can get ported to the 6.0 branch (not sure that's even wise / a possibility).

**Comment by bartonjs** [comment]
Ah, yes.  I'm guessing the answer will be move to 7 at this point.  But if @danmoseley is happy to take another couple of obsoletions then I'd personally be happier to see them knocked out sooner.

**Comment by jeffhandley** [comment]
Based on "Obscure type, no clear implementation. No derivers." I would be comfortable porting these into release/6.0-rc1 if @danmoseley is. We would need tactics approval.

Or we could take them in RC2 with just Dan's approval.

7.0 also wouldn't upset me.

**Comment by jeffhandley** [comment]
Moved to 7.0.0.

**Comment by vcsjones** [comment]
@bartonjs 

> I think that only leaves ECDiffieHellmanPublicKey.ToByteArray and ECDiffieHellmanPublicKey..ctor(byte[]). I'd support Obsoleting these. I... thought... we had added SPKI export on this type, but I don't see it

I didn't quite take this as an affirmative "let's obsolete these". Do we want to obsolete `ECDiffieHellmanPublicKey.ToByteArray` and `ECDiffieHellmanPublicKey..ctor(byte[])`?

**Comment by vcsjones** [comment]
>  The constructor is... harder? 

Yeah. But then it feels weird to have a constructor that takes the key blob and no not-obsolete way to do anything with it.

Since it's a protected constructor on a class that [no one is deriving from](https://github.com/dotnet/runtime/issues/50528#issuecomment-898003900) I would wager we could take a swing at obsoleting it with less than perfect wording.

**Comment by bartonjs** [comment]
"ECDiffieHellmanPublicKey.ToByteArray() and the associated constructor do not..." might work?

**Comment by bartonjs** [comment]
I'm not really a fan of obsoleting _types_, as that makes every member declaration that uses it have to suppress the obsoletion.  I think we just ignore it.

**Comment by vcsjones** [comment]
>  as that makes every member declaration that uses it have to suppress the obsoletion. 

I would imagine it would get obsolete under SYSLIB0042, if it were pursued.

I don't know if there is telemetry on this, but I would be surprised if developers were using `ECKeyXmlFormat` as a parameter type, especially since it never contained anything more than one enum value.

For dotnet/runtime members, it would only be half a dozen or so suppression I suspect, which seems manageable.

From my own searching on GitHub, I didn't see a single use of `ECKeyXmlFormat` that was not a fork of the runtime, or calling To/FromXmlString (which is going to hit the diagnostic anyway).
