### ISSUE TITLE
GetMonthName for HijriCalendar

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#50548]
Hi,

Please add GetMonthName to the HijriCalendar and all Calendars so it will be quick to get the month name.

It should also be possible to get it as per the Culture setting in case the developer wants to show the English or Arabic names for example.

Thanks,
Jassim

**Comment by tarekgh** [comment]
@jrahma it is by design to not have the month names exposed on the calendars, but it is exposed from DateTimeFormatInfo. The reason is the month names can differ according to different DateTimeFormatInfo. And if you want to have the API to work with different cultures, then that is where you can just use the DateTimeFormatInfo from that culture. Anything related to different localized names should be stored on the culture/DTFI and not the calendar.
