### ISSUE TITLE
.NET 5: RID changes made in servicing are missing from shared framework deps file, breaking RID-asset selection for framework dependent applications on new RIDs

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#50739]
### Description

As part of the work to add [support for Alpine 3.13](https://github.com/dotnet/core/issues/5687), a RID for it has not been included in the Microsoft.NETCore.App.deps.json file.

This command returns no results:

```console
$ cat /usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.5/Microsoft.NETCore.App.deps.json | grep alpine.3.13
```

This causes the RID of the runtime environment to only show `linux-musl-x64` rather than the more specific `alpine.3.13-x64` RID.

```console
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.13
 OS Platform: Linux
 RID:         linux-musl-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Configuration

This behavior only occurs in .NET 5.0.

**Comment by mthalman** [comment]
cc @rbhanda - We need to catch this sooner as part of signing off on new platforms.

**Comment by LiangZugeng** [comment]
@joperezr Is there any plan (before 6.0) to add the alpine.3.13 RID into Microsoft.NETCore.App.deps.json? I tested the 5.0.7 SDK docker image and the RID is still incorrect.

```
/ # dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.13
 OS Platform: Linux
 RID:         linux-musl-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Could it be fixed in the next minor version of 5.0.7? It has a bigger impact than it seems to be. Due to this issue, unit tests using SQLite will fail in .NET 5.0 Alpine 3.13 docker container, some people (including me) have to fall back to .NET 5.0 Alpine 3.12 docker image to correctly run unit tests. For more information please see https://github.com/dotnet/efcore/issues/24189

**Comment by ericstj** [comment]
From https://github.com/dotnet/efcore/issues/24189#issuecomment-878848659

> It looks like the `Microsoft.NETCore.Platforms` version was pinned to 5.0.0 by https://github.com/dotnet/runtime/pull/43182 and it hasn't been updated since then to match the live version, so it faithfully continues to use 5.0.0. It seems odd to me that it used `5.0.0` rather than `$(ProductVersion)`, ~and that it was merged with a `* NO MERGE *` label active~(explained in PR description).

> The `Microsoft.NETCore.Platforms` `5.0.0` package name/version shows up in the deps.json file, so I don't think it'll be hard to spot for specific tar.gzs. And yeah, `fedora.35-x64` is also missing in a tar.gz I pulled for 5.0.7.

> /cc @dleeapho @NikolaMilosavljevic

**Comment by ericstj** [comment]
>  It seems odd to me that it used `5.0.0` rather than `$(ProductVersion)

Agree that's odd, however using `$(ProductVersion)` might meant that the installer subset needs to restore and consume a package built by the libraries subset.  Perhaps rather than `$(ProductVersion)` it should be https://github.com/dotnet/runtime/blob/84228b7a531ce33d28a96c347f9cd9a8c37ed076/eng/packaging.props#L26
In 3.x this made sense in core-setup since the package was coming from a different repo, now that they are in the same repo it doesn't make sense.

In 6.0 this is happening via direct consumption of the runtime.json file.  https://github.com/dotnet/arcade/blob/1b053babb8a542e3ab20f93b3d0aedc732b7e0c7/src/Microsoft.DotNet.SharedFramework.Sdk/src/GenerateSharedFrameworkDepsFile.cs#L42

Perhaps that's the best fix for 5.0 as well.

**Comment by dagood** [comment]
Ah... `Microsoft.NETCore.Platforms` is not always built/shipped with the current version. Yeah, probably needs to be matched up with that property. (Is the package always at least *built*, or is it sometimes disabled completely? How? Is this infra also fragile?)

**Comment by dagood** [comment]
> Is the package always at least _built_

> In 6.0 this is happening via direct consumption of the runtime.json file.

On second thought, since the runtime.json file is just a literal file in the repo, I suppose nothing has to be built. It might be worth considering if it would be bad if someone made a change to the runtime.json and forgot to make it build, so the tar.gz would contain newer RIDs than the latest publicly available Microsoft.NETCore.Platforms package.

**Comment by ericstj** [comment]
> if it would be bad if someone made a change to the runtime.json and forgot to make Microsoft.NETCore.Platforms build

We have the same problem with every nuget package in the repo.  That's a tradeoff we accept for selective servicing.

I believe that the latest SDKs carry a copy of the runtime.json so we can just ensure that it flows there through a transport package instead of `Microsoft.NETCore.Platforms` at which point `Microsoft.NETCore.Platforms` is largely redundant.

**Comment by ViktorHofer** [comment]
@ericstj can this issue be closed given that https://github.com/dotnet/arcade/pull/7643 was merged?

**Comment by Anipik** [comment]
I verified the fix in the final bits, we might want to wait until we release before closing.

**Comment by ViktorHofer** [comment]
If the necessary fix is already merged and the final bits prove its correctness, this should be fine to close. Thanks Anirudh for validating.
