### ISSUE TITLE
Questions about AddMemoryFont

### ISSUE THREAD

**Issue by icejd** [dotnet/runtime#50742]
I put font package in a resource file, so as to avoid installing fonts, the code below, run Windows is normal and perfect, and no Windows install corresponding font, but under Linux, he doesn't seem to be effective, there is only one display font anyway, and not from any one of the resources, seems to be the default font, I only have the font file into the "/ usr/share/fonts/micro/" below, have the effect, but I don't want to do, why under Linux, the resources of the font will not take effect?

`
System.Drawing.Text.PrivateFontCollection pfc = new System.Drawing.Text.PrivateFontCollection();
pfc.AddMemoryFont(ResourcesHelper.GetResFontPtr(Properties.Resources.elephant), Properties.Resources.elephant.Length);
pfc.AddMemoryFont(ResourcesHelper.GetResFontPtr(Properties.Resources.georgia), Properties.Resources.georgia.Length);
pfc.AddMemoryFont(ResourcesHelper.GetResFontPtr(Properties.Resources.Vineta), Properties.Resources.Vineta.Length);
Font myFont = new Font(pfc.Families[new Random().Next(0,pfc.Families.Length)], fsize/1.5f, FontStyle.Regular);
`

.NET 5.0
Linux Centos 3.10.0-1160.el7.x86_64

**Comment by safern** [comment]
Hello, @icejd. In linux we use an underlying native library for all drawing operations that is a port of `GDI+` to run on `Unix`. 

From looking at the code, `AddMemoryFont` is using: `fcconfigappfontaddfile` in order to add the font to the OS font database, however it is not capturing what that call to the OS is returning. So it could be that the call to register the font is failing and `libgdiplus` is just silently ignoring that failure. https://github.com/mono/libgdiplus/blob/e15e1e00bcff4a2cb9c5135cbd43a7ffa0f13756/src/font.c#L1439

Also, it looks like `libgdiplus` always uses the same file name under the `/tmp` path... so that could be one of the underlying issues as well. 
https://github.com/mono/libgdiplus/blob/e15e1e00bcff4a2cb9c5135cbd43a7ffa0f13756/src/font.c#L1426

Might be worth trying this piece of native code on your environment to see what the OS call is returning?

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
