### ISSUE TITLE
Directory.Move throws invalid exception message

### ISSUE THREAD

**Issue by nmoreaud** [dotnet/runtime#50833]
### When _destination_ directory is invalid, Directory.Move() throws an exception claiming that parts of _source_ directory does not exist.

Snippet:
```
using System.IO;

try
{
    // cleanup
    Directory.Delete("dst", true);
} catch {}
Directory.CreateDirectory("src");
Directory.Move("src", "dst/dst"); // dst/dst is nested and doesn't exist ; move failure
```

Current error message:
> Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/dev/projects/test/src'.
>    at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
>    at System.IO.Directory.Move(String sourceDirName, String destDirName)
>    at <Program>$.<Main>$(String[] args) in /home/dev/projects/test/Program.cs:line 8

I think the exception message should be something like: `System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/dev/projects/test/dst/dst'.`

I guess the error comes from here: https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/io/directory.cs#L1266

### Configuration

.Net 5.0.102 - Ubuntu 20.4 - x64

**Comment by manandre** [comment]
Hello,
The [current code targeting Unix](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L373) assumes that the `ENOENT` error is due to the `source` parameter.
BTW, a similar approach is taken in the [current code targeting Windows](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs#L126), but the thrown exception does not mention any path:
> Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Runtime50833.Program.Main(String[] args) in C:\Users\manu\source\repos\Runtime50833\Runtime50833\Program.cs:line 18

Even the [.Net documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.move?view=net-5.0#exceptions) only refers to the `sourceDirName` parameter as root cause for the `DirectoryNotFoundException`.
> [DirectoryNotFoundException](https://docs.microsoft.com/en-us/dotnet/api/system.io.directorynotfoundexception?view=net-5.0)
> The path specified by `sourceDirName` is invalid (for example, it is on an unmapped drive).

I see 2 possible solutions:
- Remove the path from the error message of the exception, as done on Windows side.
- Add extra checks (on Windows and Unix sides) to ensure the parent (destination) directory exists.

**Comment by ayousuf23** [comment]
If we remove the path from the error message, the `isDirectory` parameter in the exception would still be true, which may not be the case if the path is invalid. Is adding extra checks the better option?

**Comment by YVEF** [comment]
@ayousuf23 hi, sorry, what do you mean: isDirectory parameter in the exception? in which exception? Have you had inconveniences with it on Windows side?

**Comment by steveberdy** [comment]
@YVEF I think what @ayousuf23 means is [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L408). Also, I would like to give this a go. I'll work on a PR.
