### ISSUE TITLE
.Net 5.0 Crashes Running Deveel.Math's BigDecimal Division

### ISSUE THREAD

**Issue by sharpninja** [dotnet/runtime#50895]
### Description

I am working on calculating Fib(1_000_000) using Binet’s formula.  Decimal isn't large enough, so I'm using Deveel.Math nuget package which is based on Apache Harmony Math.  When running for any n > 100, it crashes the CLR with no output.  I've verified this locally on .Net 5.0, .Net Core 3.1 and .Net Core 3.0.  Additionally, I've verified it on dotnet fiddle, which simply dies executing the algorithm.

[Link to dotnet fiddle](https://dotnetfiddle.net/gTAVqM)

### Configuration

Tested on:
* .Net 5.0
* Dotnet Core 3.1
* Dotnet Core 3.0
* Windows 10 20H2
* https://dotnetfiddle.net/gTAVqM

### Regression?

Unknown

### Other information

CLR dies without output.

**Comment by GrabYourPitchforks** [comment]
The runtime isn't crashing. The underlying library is throwing an exception, the catch handler is executing, but it's not producing any output because there's no untyped data in the exception instance. This is seen by modifying your code as follows.

```cs
catch (Exception ex)
{
/*
	foreach (DictionaryEntry pair in ex.Data)
	{
		Console.WriteLine($"{pair.Key}, {pair.Value}");
	}
*/
    Console.WriteLine(ex); // <-- ADD THIS LINE
}
```

And it will show you the output you expect.

```txt
System.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
   at Deveel.Math.BigDecimalMath.Divide(BigDecimal dividend, BigDecimal divisor)
   at Deveel.Math.BigDecimal.op_Division(BigDecimal a, BigDecimal b)
```

For more information on exception handling in .NET, see https://docs.microsoft.com/dotnet/csharp/programming-guide/exceptions/.

**Comment by sharpninja** [comment]
I cannot believe I missed that.
