### ISSUE TITLE
InsertItem function's real name is Insert for ObservableCollection<T>

### ISSUE THREAD

**Issue by Omcsesz** [dotnet/runtime#51079]
### Description

Hello, Team!

The real name of the InsertItem function should be Insert in the documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1.insertitem?view=netframework-4.8

It should be fixed.

### Configuration

* Which version of .NET is the code running on? **.NET Framework 4.8**
* What OS and version, and what distro if applicable? **Windows 7 Professional (ver. 6.1 build 7601)**
* What is the architecture (x64, x86, ARM, ARM64)? **AMD64**
* Do you know whether it is specific to that configuration? **No**

**Comment by huoyaoyuan** [comment]
`InsertItem` is an override function. It's invoked by `Collection<T>.Insert`, which is the `Insert` function. They are different functions.

**Comment by Omcsesz** [comment]
> 
> 
> `InsertItem` is an override function. It's invoked by `Collection<T>.Insert`, which is the `Insert` function. They are different functions.

So, it should not be visible in the AutoComplete suggestions list?

**Comment by huoyaoyuan** [comment]
> So, it should not be visible in the AutoComplete suggestions list?

It should be only accessible when you are inheriting `Collection<T>` or `ObservableCollection<T>`. That's the accessibility of `protected`.

**Comment by Omcsesz** [comment]
> 
> 
> > So, it should not be visible in the AutoComplete suggestions list?
> 
> It should be only accessible when you are inheriting `Collection<T>` or `ObservableCollection<T>`. That's the accessibility of `protected`.

I tried that too, but even then, it does not appear.

**Comment by huoyaoyuan** [comment]
![image](https://user-images.githubusercontent.com/5644458/114340399-111f7b00-9b8a-11eb-81b7-2c42c5da665c.png)

**Comment by eiriktsarpalis** [comment]
As @huoyaoyuan points out, [`Insert`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.insert?view=net-5.0) and [`InsertItem`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.insertitem?view=net-5.0) are two separate methods of [`Collection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1?view=net-5.0). The latter method is marked protected and therefore can only be called by inheriting classes.

I hope this answers your question. I'm going to close the issue, feel free to reopen otherwise.
