### ISSUE TITLE
JsonPropertyName ignored on interface implementations

### ISSUE THREAD

**Issue by andyolivares** [dotnet/runtime#51129]
### Description

I'm defining some interfaces but I'm marking properties with JsonPropertyName on implementations. Here an example:

```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

public interface ITest
{
	string MyProperty { get; }
}

public class Test : ITest
{
	[JsonPropertyName("myProperty")]
	public string MyProperty { get; }
	
	public Test(string myProperty)
	{
		MyProperty = myProperty;
	}
}

public class Program
{
	public static void Main()
	{
		ITest test = new Test("foobar");
		
		var json1 = JsonSerializer.Serialize(test, new JsonSerializerOptions() { WriteIndented = true });
		
		// I would expect to see: { "myProperty": "Hello world" }
		Console.WriteLine(json1);
	}
}
```

I don't see the point marking my interfaces with something that should be an implementation detail. I would expect the JsonPropertyName to be evaluated when serializing. Is this behavior by design?

### Configuration

.NET 5.0
Windows 10 Enterprise Version 1809 x64

**Comment by eiriktsarpalis** [comment]
> Is this behavior by design?

It is. The type is being serialized as an `ITest` instance so any attribute metadata specified in the derived type will not be taken into account by the serializer. There are a few workarounds to consider here:

1. Define the attribute at the interface level. That should be the preferred approach if your code is expected to serialize multiple implementations of `ITest`.
2. Serialize the type as `Test`:  `var test = new Test("foobar"); JsonSerializer.Serialize<Test>(test);`
3. Finally, since it seems like your example is using the attribute to convert the property name to camelCase, I would recommend configuring your serializer with [JsonNamingPolicy.CamelCase](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonnamingpolicy.camelcase?view=net-5.0) instead.

**Comment by andyolivares** [comment]
Thank you for the quick reply. Anyway I think an option (JsonSerializerOptions) to consider attributes on derived types would be helpful in many situations.

Even though I can define the attributes on the interface, it doesn't look right to me doing that as the serialization names are more like an implementation detail than something that should belong to the interface (at least in this case).

**Comment by eiriktsarpalis** [comment]
We are planning on adding something like that in a future release: https://github.com/dotnet/runtime/issues/29937

**Comment by andyolivares** [comment]
Would be great, thank you!

**Comment by eiriktsarpalis** [comment]
Closing this issue since I assume your question has been answered. Thank you for contributing!
