### ISSUE TITLE
The method System.Security.Cryptography.HashAlgorithm.Initialize() doesn't reset algorithm to its initial state under NET5 correctly

### ISSUE THREAD

**Issue by ymalich** [dotnet/runtime#51172]
### Description
I discovered the bug in the method HashAlgorithm.Initialize() under NET 5.
It doesn't reset algorithm to its initial state in NET5, as it do under net4.8.
I tested with providers SHA1CryptoServiceProvider, SHA1Managed, SHA256Managed, SHA256CryptoServiceProvider.

Steps to reproduce (I've also attached the small test solution with net5 and net48 targets).
Test (1)
- Create the new SHA1CryptoServiceProvider
- Call TransformBlock with any data
- Call Initialize() 
- Call ComputeHash() with other data

Compare ComputeHash() result with: 
Test (2)
- Create the new SHA1CryptoServiceProvider
- Call ComputeHash() with other data

or compare ComputeHash() result with:
Test (3)
- Create the new SHA1CryptoServiceProvider
- Call TransformBlock with any data
- Call TransformFinalBlock with any data
- Call Initialize() 
- Call ComputeHash() with other data

Result (1) != (2), but (2) == (3) under NET5.
Under net48 (1) == (2)  == (3) under NET4.8.

### Configuration
NET 5.0.4, Windows 10 64 bit

### Regression?
Yes.
Initialize() works fine under .Net Frameworks 4.8.
See attached project.

### Other information
Project file is attached:
[ConsoleAppBrokenHashDemo.zip](https://github.com/dotnet/runtime/files/6304057/ConsoleAppBrokenHashDemo.zip)

**Comment by vcsjones** [comment]
@bartonjs It looks like `Initialize` is a no-op on .NET (Core). We could do any of the following:

1. Implement on the `HashProvider`. For some platforms that support a reset like `EVP_DigestInit_ex` we could use that, or, more simply, just dispose the underlying handles and re-initialize the whole thing.
2. `[Obsolete]` this method and document it as so, and expect that callers should either re-create the hash instance themselves, or finalize the instance and discard the result to get a reset.

**Comment by ymalich** [comment]
>     2. `[Obsolete]` this method and document it as so, and expect that callers should either re-create the hash instance themselves, or finalize the instance and discard the result to get a reset.
IMHO declaring a method as [Obsolete] between the major and minor versions because it is buggy is not a good idea at all. :)
It's already documented in MSDN as it's supported in .NET 5.0
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.initialize
therefore it must be supported to correspond the documentation.

**Comment by ymalich** [comment]
The background, for your understanding, : 
I have a software, which processes hundreds-thousands of data packets per second.
I could create the hundreds-thousands of HashProviders per second, but it also increase the memory traffic.
I have a shared pool of HashProviders to reduce the memory traffic and reduce the pressure on GC and I need to re-set a shared HashProvider to its initial state when I get it from my shared pool using Initialize().

**Comment by vcsjones** [comment]
> I have a software, which processes hundreds/thousands of data packets per second.

I'm not sure where `Initialize` fits in to this. Calling `ComputeHash` does have the affect of resetting / `Initialize`. `Initialize` I suppose would be useful if you did `TransformBlock` and wanted to discard the in-flight hash, but you could just do `ComputeHash` to get the same result.

This should work:

```csharp
HashAlgorithm hash; // Get from pool
hash.TransformBlock(....);
_ = hash.ComputeHash(); // Discard hash and re-initialize.
```

Although I am not clear what the use case is for these steps:

> * Call TransformBlock with any data
> * Call Initialize()
> * Call ComputeHash() with other data

What is the purpose of the first `TransformBlock` if you are just going to discard it in step 2?

**Comment by ymalich** [comment]
> I'm not sure where `Initialize` fits in to this. Calling `ComputeHash` does have the affect of resetting / `Initialize`. `Initialize` I suppose would be useful if you did `TransformBlock` and wanted to discard the in-flight hash, but you could just do `ComputeHash` to get the same result.
> 

The HashProviders from shared pool are being used in different parts of the software.
For small data packets and small files the `ComputeHash` is used.
But there are also large data streams. They being read and hashed per blocks using TransformBlock() +TransformFinalBlock().  

> This should work:
> _ = hash.ComputeHash(); // Discard hash and re-initialize.
Is there an additional performance penalty here to call the ComputeHash() isstead of Initialize()?


> 
> Although I am not clear what the use case is for these steps:
> 
> > * Call TransformBlock with any data
> > * Call Initialize()
> > * Call ComputeHash() with other data
> 
> What is the purpose of the first `TransformBlock` if you are just going to discard it in step 2?

As I mentioned above, these 3 calls are located in different methods of the software. I've just put them together only in the test app to help you to reproduce the bug easily. 
There are cases when the reading+hashing of large data streams is being stopped/cancelled for some reason and the `TransformFinalBlock` is never called at the end of the stream, but the given hash provider is automatically returned into my shared pool to be used later again.

**Comment by vcsjones** [comment]
`TransformFinalBlock` also does a reset.

```csharp
using System;
using System.Security.Cryptography;

using var hashAlg = SHA1.Create();

byte[] input1 = new byte[] { 1, 2, 3 }, input2 = new byte[] { 4, 5, 6 };
byte[] dest1 = new byte[3];

hashAlg.TransformBlock(input1, 0, input1.Length, dest1, 0);
byte[] digest = hashAlg.TransformFinalBlock(input2, 0, input2.Length);

Console.WriteLine(Convert.ToBase64String(digest));


hashAlg.TransformBlock(input1, 0, input1.Length, dest1, 0);
digest = hashAlg.TransformFinalBlock(input2, 0, input2.Length);

Console.WriteLine(Convert.ToBase64String(digest));
```

This will output the same hash even though we are re-using an instance, so we can observe that the first call to `TransformFinalBlock` re-initialized. The only time you would want to call `Initialize` explicitly is when you are updating a hash with `TransformBlock` and you never get the final digest, but want to re-use the instance anyway.

-------

Some other thoughts that are not explicitly related to this, but might be helpful to you:

1. > For small data packets and small files the ComputeHash is used.

    Since it looks like you are targeting .NET 5, a better option might be for you to use the one-shot static methods. Like [`SHA256.HashData`][1]. Since these methods are static, there are no object instances that you need to pool. They will oftentimes be faster as well.

2. You might consider using [`IncrementalHash`][2] for "updating" hashes for your scenario of `TransformBlock` and `TransformFinalBlock`. The `TransformBlock` APIs exist so that `HashAlgorithm` instances could be used with `CryptoStream`. If you are just hashing inputs then `IncrementalHash` might make more sense. The `TransformBlock` APIs unnecessarily copy the input buffer to the output buffer. If you _are_ hashing a stream, then consider using `HashAlgorithm.ComputeHash` which takes a `Stream` as input. 

[1]:  https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.hashdata?view=net-5.0
[2]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.hashdata?view=net-5.0

**Comment by bartonjs** [comment]
> It's already documented in MSDN as it's supported in .NET 5.0 ... therefore it must be supported to correspond the documentation.

Technically, the documentation is only saying that the method is available.  It also says it's available in .NET Core 1.0... which is probably when it got added as a no-op (because in .NET Core 1.0 we had removed the TransformBlock and TransformFinalBlock methods), and it has been a non-functioning method on .NET Core and .NET 5 since the beginning.

Apparently you're the first person to want it, in about 5 years :smile: (or at least the first to speak up).

> Is there an additional performance penalty here to call the ComputeHash() instead of Initialize()?

Technically, yes, since it has to allocate the array to return, but Gen0 garbage collection is pretty good.

If you care about perf at that level, you should switch to `IncrementalHash` and then call `GetHashAndReset(Span<byte>)`.  E.g. for "Just reset, I don't care about the result" (which we've not, to my recollection, ever had a previous request for):

```C#
Span<byte> discard = stackalloc byte[512 >> 3];
hasher.GetHashAndReset(discard);
```

> Other things

While I was writing this, @vcsjones had a good reply.  It seems pretty spot on, so I won't say much else.

> It looks like Initialize is a no-op on .NET (Core). We could do any of the following

It's probably fine to fix it to be a reset... but we'd need to doc it as a breaking change for .NET 6 (just so that anyone who is calling it, accidentally depending on it being a no-op, and gets surprised when their answers change can't say we didn't warn them).

**Comment by vcsjones** [comment]
> It's probably fine to fix it to be a reset

Okay, I can take of that.

**Comment by ymalich** [comment]
> 
> Apparently you're the first person to want it, in about 5 years 😄 (or at least the first to speak up).
>
Cool. The single human being on the Earth using Initialize (in .NET Core)  😄
I've finally started porting my existing software from .Net Framework to .NET Core 2-3 just about months ago and I've found the second bug in Core BCL.  😄 Who knows how many bug I'll find again. ;)
 

> If you care about perf at that level, you should switch to `IncrementalHash` and then call `GetHashAndReset(Span<byte>)`. E.g. for "Just reset, I don't care about the result" (which we've not, to my recollection, ever had a previous request for):
> 
> ```cs
> Span<byte> discard = stackalloc byte[512 >> 3];
> hasher.GetHashAndReset(discard);
> ```

Thanks, for the hint! I'll take it into account and test this new class IncrementalHash.

**Comment by ymalich** [comment]
> Some other thoughts that are not explicitly related to this, but might be helpful to you:
> 
>     1. > For small data packets and small files the ComputeHash is used.
>        
>        
>        Since it looks like you are targeting .NET 5, a better option might be for you to use the one-shot static methods. Like [`SHA256.HashData`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.hashdata?view=net-5.0). Since these methods are static, there are no object instances that you need to pool. They will oftentimes be faster as well.
> 
>     2. You might consider using [`IncrementalHash`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.hashdata?view=net-5.0) for "updating" hashes for your scenario of `TransformBlock` and `TransformFinalBlock`. The `TransformBlock` APIs exist so that `HashAlgorithm` instances could be used with `CryptoStream`. If you are just hashing inputs then `IncrementalHash` might make more sense. The `TransformBlock` APIs unnecessarily copy the input buffer to the output buffer.

Great! Thanks for hints 

> If you _are_ hashing a stream, then consider using `HashAlgorithm.ComputeHash` which takes a `Stream` as input.
It doesn't fit well my case. I also need to process the stream-chunks data parallel using buffers. The hashing is only one part of the job in this case. Therefore I calculate hashes using already read buffered data.

**Comment by vcsjones** [comment]
@bartonjs 

An interesting side affect of implementing this is we might end up slightly hurting performance in the more typical use cases of `HashAlgorithm`.

The `ComputeHash` method in `HashAlgorithm` calls `Initialize` (by way of `CaptureHashCodeAndReinitialize`) after calling `HashCore`.

Today, that initialize does nothing for our in the box implementations. That makes sense since the underlying `HashProvider` is "self-resetting" so the `Initialize` doesn't need to do anything.

If we implement `Initialize`, we will end up double-resetting. e.g. once by `HashProvider`'s underlying hash mechanism (which might be done in the native shims) and again by way of `ComputeHash`. I don't think we can remove the call to `Initialize` from `ComputeHash` since that would be a very visible breaking change for implementors of `HashAlgorithm`.

I'll try and gather benchmarks to see how noticable the performance change is, but, thought I would see if you have thoughts or if this changes your opinion on implementing this.

**Comment by bartonjs** [comment]
Low-coffee thinking:

* If it's barely noticeable in a benchmark, just do it.
* If it's noticeable, maybe it can be guarded by a state check (I feel like there's a state thing for dealing with TransformBlock).
* If that's still noticeable, or just "too complex", [Obsolete].

**Comment by vcsjones** [comment]
Looks fairly noticeable to me. I'll see what the effort would be to reduce/eliminate the impact of it.

|                    Method |        Job | Toolchain | DataSize |     Mean |   Error |  StdDev | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |----------- |---------- |--------- |---------:|--------:|--------:|------:|-------:|------:|------:|----------:|
|         Sha256ComputeHash | Job-EESGLV |    branch |        0 | 280.9 ns | 2.48 ns | 2.32 ns |  1.14 | 0.0067 |     - |     - |     112 B |
|         Sha256ComputeHash | Job-HXPUQU |      main |        0 | 246.8 ns | 1.45 ns | 1.36 ns |  1.00 | 0.0067 |     - |     - |     112 B |
|                           |            |           |          |          |         |         |       |        |       |       |           |
| Sha256TransformFinalBlock | Job-EESGLV |    branch |        0 | 355.9 ns | 2.66 ns | 2.22 ns |  1.10 | 0.0100 |     - |     - |     168 B |
| Sha256TransformFinalBlock | Job-HXPUQU |      main |        0 | 322.8 ns | 2.36 ns | 1.97 ns |  1.00 | 0.0100 |     - |     - |     168 B |
|                           |            |           |          |          |         |         |       |        |       |       |           |
|         Sha256ComputeHash | Job-EESGLV |    branch |       64 | 290.9 ns | 0.15 ns | 0.14 ns |  1.04 | 0.0067 |     - |     - |     112 B |
|         Sha256ComputeHash | Job-HXPUQU |      main |       64 | 278.9 ns | 2.80 ns | 2.49 ns |  1.00 | 0.0067 |     - |     - |     112 B |
|                           |            |           |          |          |         |         |       |        |       |       |           |
| Sha256TransformFinalBlock | Job-EESGLV |    branch |       64 | 452.0 ns | 0.90 ns | 0.84 ns |  1.22 | 0.0153 |     - |     - |     256 B |
| Sha256TransformFinalBlock | Job-HXPUQU |      main |       64 | 371.4 ns | 1.35 ns | 1.26 ns |  1.00 | 0.0153 |     - |     - |     256 B |
