### ISSUE TITLE
Are C++ cli mixed assemblies supported on Windows 7?

### ISSUE THREAD

**Issue by andrei-datcu** [dotnet/runtime#51196]
I'm building a mixed x86 C++/CLI that uses a lot of native code referencing std::thread / std::async. I'm targeting NetCore 3.1 and everything works nicely on Windows 10. However, on Windows 7 I get `BadImageFormatException`. I know about some of the quirks of my use case on Windows 7, when stuff gets ugly once thread local variables are involved (see [here](https://social.msdn.microsoft.com/Forums/en-US/f303aea4-9414-42ed-be2e-f0764f2a80ef/ccli-assembly-with-tls-callbacks-results-in-os-loader-failure?forum=vcgeneral) for example). When loading my test app on Windows 7,  the code gets to call **mscore.dll!__CorValidateImage** and returns `STATUS_INVALID_IMAGE_FORMAT`. I have 0 experience with NetCore, but as I'm getting it, `mscore.dll` should not be loaded at all. In my tests, I've noticed it is not loaded in Windows 10, but it is loaded on Windows 7.  Furthermore, `dumbin /imports` doesn't show any reference to `mscoree.dll`. There's zero documentation for this, but I've noticed some people are able to run the mixed assemblies tests on Windows 7: https://github.com/dotnet/runtime/issues/12108#issuecomment-500993792

My questions therefore are:
* Is this supposed to work?
* Is `mscoree.dll` supposed to be loaded on Windows 7? I'm deploying `Ijwhost.dll` correctly on the Win7 machine.
* If the answer to the above question is no, is there any workaround? Maybe build an empty shim for `mscoree.dll` and ship that with the test app?

**Comment by jeffschwMSFT** [comment]
@jkoritzinsky

**Comment by jkoritzinsky** [comment]
Last I remember testing with Windows 7, the Windows OS DLL Loader gets in the way and tries loading the assembly with mscoree. As you see, I have yet to re-enable the C++/CLI tests here as I've hit issues on Windows 7 with OS loader hooking itself in instead of respecting that the C++/CLI assembly references `ijwhost.dll`.

As the OS hooks in and grabs the machine-global copy of `mscoree.dll`, you can't override this locally (that's why the tests were first disabled). I believe the success I saw with the tests was an accident of the design of C++/CLI loading in .NET Core, where the runtime can call back into `mscoree.dll` instead of `ijwhost.dll` since they have the same interface and the lookup isn't hardcoded to a specific name. As a result, the trivial cases we're testing in our tests can work. However, this doesn't change the fact that `mscoree.dll` gets involved, so you end up limited to what `mscoree.dll` can load.

**Comment by andrei-datcu** [comment]
Thanks for answering, @jkoritzinsky. Just to make it crystal clear for me: There's no way to get `mscoree.dll` out of the way on Windows 7, is it? Thanks!

**Comment by jkoritzinsky** [comment]
To my knowledge, there is no way to get `mscoree.dll` out of the way completely.

**Comment by andrei-datcu** [comment]
@jkoritzinsky Is there any other workaround I could try? Could I link the C++ /CLI assembly with the main netcore assembly and ship it as one?

**Comment by AaronRobinsonMSFT** [comment]
@andrei-datcu I think an option here is to start from a managed entry point. For example, if the starting process is managed. Is that possible?

**Comment by andrei-datcu** [comment]
@AaronRobinsonMSFT The end goal is to have a WPF app that is using the C++/CLI assembly. Would that count as a managed entry point?

**Comment by andrei-datcu** [comment]
@AaronRobinsonMSFT Cool. Any hints/examples on how I could make it work? Thanks!

**Comment by AaronRobinsonMSFT** [comment]
@andrei-datcu Apologies for the very slow response. The hint/example here is create a basic WPF application and reference a C++/CLI assembly. The issue is the CLR needs to start first in a stable way and then load a C++/CLI assembly. Note this is only an issue on Win7 I believe.
