### ISSUE TITLE
PrincipalContext, ValidateCredentials

### ISSUE THREAD

**Issue by trivalik** [dotnet/runtime#51222]
### Description

We were authenticate to our domain via simple:
`new PrincipalContext(ContextType.Domain).ValidateCredentials(name, password);`

But since probably a domain configuration/security harden, this is not working anymore, instead a `DirectoryOperationException` occure with errorcode 0x80131500.
english error text is: The server cannot handle directory requests.
german error text is: Der Server kann Verzeichnisanforderungen nicht verarbeiten.

After looking into code I found that in class `CredentialValidator` in method `Validate` for `SimpleBind` only the `LdapException` has been catched. Changing the internal member via debugger from `Simple` to `Negotiate`, let the `ValidateDomainCredentials` run through without issue.

### Solution

Catch additional to `LdapException` also `DirectoryOperationException` in `CredentialValidator` in method `Validate`.

### Question
In case this is here is fixed, where can I find a nuget package which works with .NET Framework 4.8, since the regular package have not build for it inside.

**Comment by joperezr** [comment]
@trivalik thanks for logging the issue, once the fix is in you would be able to consume the new package in .NET Framework4.8 since we have a .NET Standard2.0 configuration that we build, which goes in the package and will get resolved by your .NET Framework4.8 app. Since you have found the issue and fix, would you be interested in contributing a PR for it?

**Comment by trivalik** [comment]
add pull https://github.com/dotnet/runtime/pull/52748
