### ISSUE TITLE
Segmentation Fault when using dotnet 5.0 from snap

### ISSUE THREAD

**Issue by briguyjm** [dotnet/runtime#51322]
I just installed dotnet sdk 5.0 using snap on Ubuntu 20.10. When creating a simple Hello World and running `dotnet test`, nothing happens. Running `dotnet build` builds my Hello World just fine, but `dotnet run` does nothing. Running the binary directly in the `bin/` directory results in a Segmentation Fault.

```
brian@brian-pc:~/hello$ dotnet build
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  hello -> /home/brian/hello/bin/Debug/net5.0/hello.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.74
brian@brian-pc:~/hello$ dotnet run
brian@brian-pc:~/hello$ cd bin/Debug/net5.0/
brian@brian-pc:~/hello/bin/Debug/net5.0$ ./hello 
Segmentation fault (core dumped)
```

This is my Program.cs

```
using System;

namespace hello
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

System info:

```
lsb_release -cr
Release:	20.10
Codename:	groovy

dotnet --version
5.0.101

uname -r
5.8.0-7630-generic

```

**Comment by mangod9** [comment]
Hi @kouvel, believe you had done some investigation for snap -- does this issue still exist in 6?

**Comment by kouvel** [comment]
This seems to be the same issue as described in detail in https://github.com/dotnet/runtime/issues/3775#issuecomment-534263315. Snap's dotnet seems to be targeting and should be running under the `core18` base snap but it's ending up loading libs from system paths instead of from the base snap paths due to the `RPATH` issue.

Modifying the `RPATH` or just putting the app one folder deeper seems to resolve the issue when running the app directly from the build folder. Same issue with `dotnet run` as well it seems. `dotnet bin/Debug/net5.0/hello.dll` seems to work without any issues.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
