### ISSUE TITLE
[wasm] Runtime assertion should block all further use of the runtime

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51329]
Runtime assertions, or memory access violation kind of errors should stop any further calls into the runtime.

from a discussion on discord:
```
Katelyn Gadd: i think it's fine for the app's js to keep running
Katelyn Gadd: if it can handle it. maybe the wasm was just serving an ancillary purpose
Katelyn Gadd: similar to how it can be reasonable to keep on chugging in winforms if an event handler throws an uncaught exception of some sort, if you decide to live that life - it's a managed language
Katelyn Gadd: but if it's an unhandled access violation you probably should in fact not keep chugging, and should back into the station
```

/cc @kg @vargaz @lewing

**Comment by kg** [comment]
I think the solution is a global js variable that all the bindings APIs check before calling into the runtime. We may want to also do a similar check at native entry points instead, but JS is in a good position to check it and perhaps throw a JS error in response. If we only do the check on the wasm side things could get weird due to many entry points not having a clear way to signal failure.

To make this happen we need to modify the assert handler to set the flag (probably by calling out to a JS function responsible for flag-setting), and then make the relevant changes to the JS. We should think about whether we want to explicitly check this flag in any particular places.

We definitely want to make ongoing managed timers shut off, not respond to things like socket send/receive handlers or file load events, and block calls to methods through bind_static_method etc. We could go further and do checks in various APIs like string conversion and unboxing, but I think the important parts are the ones that can kick off long trees of calls, infinite loops, undefined behavior, etc.

This is also a good opportunity to (if we wish to) detect attempts to call into the runtime *before* everything is loaded, since blazor was doing that for a while. We can detect both failure cases (calling before startup, calling after shutdown) the same way.

**Comment by lambdageek** [comment]
> I think the solution is a global js variable that all the bindings APIs check before calling into the runtime. 

Can we just destroy  the wasm instance? (or better: move it and its heap out of the way to some `$MONO.crashed_instance` field - so it's still possible to examine it)

**Comment by lewing** [comment]
I think we can just call abort() and emscripten will do the rest.

**Comment by vargaz** [comment]
I think this was fixed by 
https://github.com/dotnet/runtime/pull/53734
