### ISSUE TITLE
[Wasm][Interp] inline interpreter option sees to create memory corruptions

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#51406]
### Description

When running an app with `-fsanitize=address` on all the runtime, the following stack comes up as an error:

![image](https://user-images.githubusercontent.com/5839577/115070617-2d415600-9ec3-11eb-8514-a70ce2cb7d5d.png)

Later on, the runtime fails as follows:

![image](https://user-images.githubusercontent.com/5839577/115070695-48ac6100-9ec3-11eb-895b-1adae1c5f7b0.png)

When disabling the inlining optimizations of the runtime (`mono_ee_interp_init ("-inline");`), the errors disappear.

I cannot extract a small repro, the out of bounds error does not happen. This issue may be related to https://github.com/dotnet/runtime/issues/51207.

**Edit:** To repro clone this branch https://github.com/jeromelaban/Uno.Prism/tree/dev/jela/interpreter-crash, and the instructions are here: https://gist.github.com/jeromelaban/4b354545eaf3418207c6bd7f0b40e4cf

### Configuration

c377f415235

### Regression?

Likely

**Comment by kg** [comment]
Some stuff we know so far:
* For the frees that fail inside inline_method, if we make the relevant allocs bigger ( ```+ 1024``` instead of ```+ 1```) the crash goes away but the app silently fails later.
* If we replace the relevant mallocs along with some of the mallocs from generate_code with mallocs that put canaries around the allocation (https://github.com/kg/runtime/tree/interp_canary), the crash goes away but the app silently fails later. This means that the canaries at the start and end of the buffer aren't being modified (this is weird). You would expect them to be modified if adding the padding is fixing it (as it does above) but instead it seems they aren't. The canary fill pattern isn't 0, either.

I think it might be useful to instrument *all* the allocations in transform.c with canaries, but doing so is much more difficult. The failed free indicates to me that something *next to* the allocation is getting trashed (and overrunning into the malloc/free bookkeeping data), but it's hard to tell what.
