### ISSUE TITLE
High Outbound TCP conneciton usage, while calling a Restful WCF with HttpClient under heavy load

### ISSUE THREAD

**Issue by fkucuk** [dotnet/runtime#51456]
### Describe the bug

I have a Legacy Restful WCF service. And I also have BFF (BackendForFronthand) service coded in NetFramework 4.6.1 which consumes the Legacy Restful WCF via RestSharp library.

So, we re-coded our BFF with .netCore 3.1 and used HttpClient to replace these requests. And we turned the whole process into async. The functional tests seemed okay, but when we make a load test our new .netCore BFF is experiencing a bottleneck.

So I simplified the applications and make load test with artillery. and the results are fascinating, even for me.

I am asking if this is a bug, or am I doing something wrong?

### To Reproduce

Artillery Setup:

All tests have been made with the following phases:

```yaml
phases:
    - duration: 120
      arrivalRate: 10
      rampTo: 50
      name: "Warm up the application"
    - duration: 600
      arrivalRate: 50
      name: "Sustained max load"
```

Test 1: Direct call to Restful WCF service (Direct_Call_LegacyRestWCF)

I tested the LegacyRestWCFService. All requests have been succeeded. 

```json
"scenariosCreated": 33603,
    "scenariosCompleted": 33603,
    "requestsCompleted": 33603,
    "latency": {
      "min": 6.9,
      "max": 1052.5,
      "median": 10,
      "p95": 21.4,
      "p99": 97.2
```

Test 2: Call the Legacy Rest WCF service over NetFramework service with RestSharp's client. (NetFramework_RestSharp)

All requests have been succeed. There are increases in response times, but it is acceptable.

```json
    "scenariosCreated": 33631,
    "scenariosCompleted": 33631,
    "requestsCompleted": 33631,
    "latency": {
      "min": 19.1,
      "max": 2421.3,
      "median": 26.4,
      "p95": 172.4,
      "p99": 1583.2
```

Test 3: Call the Legacy Rest WCF service over .netCore with HttpClientFactory - ASYNC. (Using_HttpClientFactory)

Well we expected better results. 'cause as far as we know .netCore is faster than .netFramework. But, wait:

Artillery made 33679 requests, only 10987 of them are successful. I have 12189,  503 response and 10503 ESOCKETTIMEDOUT error. 

```json
    "scenariosCreated": 33679,
    "scenariosCompleted": 23176,
    "requestsCompleted": 23176,
    "latency": {
      "min": 7.2,
      "max": 60007.8,
      "median": 45.4,
      "p95": 35779.3,
      "p99": 55747.4
```

Well this was surprising. 

Test 4: Calling the Legacy Rest WCF over .netCore with RestSharp client - SYNC.   (Using_RestSharp_Sync)

All scenarios were successful. 

```json
    "scenariosCreated": 33647,
    "scenariosCompleted": 33647,
    "requestsCompleted": 33647,
    "latency": {
      "min": 17.7,
      "max": 12510.6,
      "median": 23.7,
      "p95": 83.5,
      "p99": 114.1
```

Test 5: Calling the Legacy Rest WCF over .netCore with WebClient - SYNC. (Using_WebClient)

All scenarios successful.

```json
    "scenariosCreated": 33621,
    "scenariosCompleted": 33621,
    "requestsCompleted": 33621,
    "latency": {
      "min": 17.9,
      "max": 1476.8,
      "median": 23.5,
      "p95": 111.8,
      "p99": 201.9
```

I really want to go with HttpClient. But I can not explain why it is failing under stress. 

You can find all the details in this repo: https://github.com/fkucuk/aspnetcoreHttpClientTests

**Comment by mayorovp** [comment]
Missing usings:

https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/786107ee431961cd23e5791ed7903503eb27611c/NetCoreBFF/Controllers/MobileController.cs#L27

https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/786107ee431961cd23e5791ed7903503eb27611c/NetCoreBFF/Services/OldService.cs#L27

**Comment by fkucuk** [comment]
> Missing usings:
> 
> https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/786107ee431961cd23e5791ed7903503eb27611c/NetCoreBFF/Controllers/MobileController.cs#L27
> 
> https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/786107ee431961cd23e5791ed7903503eb27611c/NetCoreBFF/Services/OldService.cs#L27

@mayorovp according to this documentation (https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net) using statement is not preferred.

**Comment by antonfirsov** [comment]
> using statement is not preferred.

This doesn't apply to `HttpResponseMessage`, you need to make sure all instances are disposed after processing the response.

@CarnaViire can you spot any issues around `IHttpClientFacrtory` injection?
- https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/4107625df6dcc1d86a3ee4c0d131e8521f78a198/NetCoreBFF/Startup.cs#L24
- https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/786107ee431961cd23e5791ed7903503eb27611c/NetCoreBFF/Services/OldService.cs#L27
- https://github.com/fkucuk/aspnetcoreHttpClientTests/blob/4107625df6dcc1d86a3ee4c0d131e8521f78a198/NetCoreBFF/Controllers/MobileController.cs#L27

The detailed repro is really appreciated, thanks for that!

**Comment by CarnaViire** [comment]
`HttpClientFactory` *is* used a bit wrongly (I will be explaining that below), but that only creates a redundant `HttpClient` instance which shouldn't cause the problems described, as there's no requests to a redundant `HttpClient`, so no additional sockets should be captured there. I would suspect the cause might not disposing `HttpResponseMessage` that holds the socket, as @antonfirsov has commented.

Aside from that -- is there anything that prevents you from using a *static/singleton* `HttpClient`? @fkucuk If you could add another test to your repro, that uses a singleton `HttpClient`, and see whether the problem is the same, that would be super helpful! (pls don't forget to set `PooledConnectionLifetime`, or you may lose DNS changes)

```c#
new HttpClient(
    new SocketsHttpHandler { PooledConnectionLifetime = TimeSpan.FromMinutes(2) }
)
```

---

As for right way to use `HttpClientFactory`, it would be either to register `IOldService` separately as a transient or scoped, and to remove `HttpClient` parameter from the constructor

```c#
services.AddHttpClient();
services.AddScoped<IOldService, OldService>();

...

public class OldService : IOldService
{
    public OldService(IConfiguration conf, IHttpClientFactory clientFactory)
    {
        ...
    }
    public async Task<HttpResponseMessage> CallOldServiceAsync(object requestObj, string endpoint)
    {
        var client = _clientFactory.CreateClient();
        ...
    }
```
or to actually use `HttpClient` instance provided to OldService constructor instead of calling the factory again -- but keep in mind that `IOldService` should not be injected into singletons, or you may lose DNS changes.
```c#
services.AddHttpClient<IOldService, OldService>();

...

public class OldService : IOldService
{
    public OldService(HttpClient client, IConfiguration conf)
    {
        ...
    }
    public async Task<HttpResponseMessage> CallOldServiceAsync(object requestObj, string endpoint)
    {
        // use client from the constructor
        ...
    }
```

**Comment by fkucuk** [comment]
@CarnaViire we have also tried SingleHttpClientInstance by following this code sample (https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/#how-to-fix-the-problem) and also tried by registering as Singleton by IOC. The result was the same.

I've also tried disposing the HttpResponseMessage object (https://www.stevejgordon.co.uk/demystifying-httpclient-internals-httpresponsemessage) but has no positive effect. 

I'll update the github repo with these improvements. 

I am not sure but maybe it's the Restful WCF causing the problem. I'll test it by calling another native Web API.

**Comment by ahmetmithat** [comment]
Hello,

I had a chance to look at the memory dump of the ASP.NET Core application, which are captured when the same issue is reproduced and I believe there is nothing wrong on HttpClient side and you should look at the WCF backend.

In the memory dump of ASP.NET Core app, there is no thread starvation at all and all requests are passed to the backend application and the tasks are waiting to be activated again when the backend WCF app responds. The HTTP 503 - Service Unavailable should be coming from the WCF service and the socket errors should be related with the same WCF backend problem.

Then why don't we see the same issue with the other tests? It is most probably because the requests are always sent as SYNC on the working scenarios, in that case, threads on the ASP.NET Core process will be blocked until the backend app responds so at some point all threads would be blocked under stress test and the new requests will be waiting for available thread. Since the backend WCF service eventually responds, the waiting requests on the ASP.NET Core side will be handled one by one, so the result is success.

However when it is ASYNC, threads on ASP.NET Core process will not be blocked while the backend responds, instead will go back to the thread pool to handle other tasks. So, since the threads won't be blocked, it will keep sending the requests to backend over and over again, and eventually the backend WCF application will be too busy with a lot of requests and start to send HTTP 503 as response, or, even the socket connections will be broken.

As a summary, I don't think this is something related with HttpClient. The bottleneck is not ASP.NET Core app (or HttpClient implementation), instead the bottleneck is the backend WCF application. If the other tests would be run with ASYNC approach I would expect a lot of failures with those tests as well. So, when ASYNC is used, way more requests are sent to the backend compared with the SYNC one.

You can check and compare the number of concurrent requests handled by the WCF application in different tests, I bet you would see a lot of requests and even queued ones in the backend when ASYNC is used.

Hope this helps.

**Comment by ManickaP** [comment]
Triage: this looks like an issue on the server side. If you have data supporting that the problem is on HttpClient side, feel free to reopen.

**Comment by ahmetmithat** [comment]
I had a chance to work with Fatih on this one and this turned out to the following:

**Cause**

Our theory was this before: since the new application makes ASYNC calls, it causes way more requests to be sent to the backend than the SYNC one which eventually causes performance problems in the backend.

This theory was correct since the threads were not blocked with SYNC calls but the actual issue was different. When we looked at the backend WCF application running on IIS, we have seen that there were a lot of requests waiting for acquiring sessions. This was not true when sending requests with other approaches, e.g.: with RestSharp.

So, as we thought, the bottleneck was the backend for sure but the difference between two client approach was causing this problem. Fatih's further troubleshooting actions showed that the HttpClient was adding an ASP.NET session ID in the request headers while the other approaches were not adding that one.

Since the requests coming with HttpClient had an ASP.NET session ID, and most importantly since all the requests had the _same session ID_, WCF application was handling only one request at a time (by-design behavior of .NET Framework, which is different in .NET Core), causing a lot of requests to wait for acquiring the session to have a chance to be processed.

HttpClient was adding the session ID by default because of the following HttpClient property:

> HttpClientHandler.UseCookies Property (System.Net.Http) | Microsoft Docs
> 	
> Definition
> Gets or sets a value that indicates whether the handler uses the CookieContainer property to store server cookies and uses these cookies when sending requests.
> 	
> true if the if the handler supports uses the CookieContainer property to store server cookies and uses these cookies when sending requests; otherwise false. The default value is true.
> 

**Solution**

Since the WCF application does not need sessions, the solution would be to disable the sessions on server application side. However Fatih had to set the HttpClient's UseCookies property to false on client side which resulted superb response times.
