### ISSUE TITLE
singlefile apps do not emit file and line info when printing stacktraces

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#51461]
https://github.com/dotnet/diagnostics/issues/2192#issuecomment-822030226

e.g. this code:
```c#
using System;
class Program
{
    static void Main() => throw new Exception("foo");
}
```
would yield:
```sh
Unhandled exception. System.Exception: foo
   at Program.Main()
```
instead of what we get with non-singlefile execution:
```sh
Unhandled exception. System.Exception: foo
at Program.Main() in /home/am11/projects/app1/Program.cs:line 4
```

cc @mikem8361

**Comment by jkotas** [comment]
The guidance is to use embedded PDBs for this scenario. See https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#include-pdb-files-inside-the-bundle .

**Comment by am11** [comment]
I have tested with embedded PDB, it still does not print file/line info in stacktraces.

The guidance does not say that the default, DebugType=portable, for singlefile is unsupported, but rather 'PDB can be embedded'. If the default setting has no use for singlefile, should the SDK be updated to report error?

**Comment by mikem8361** [comment]
To support embedded PDBs for single-file the StackTraceSymbols.cs code [here](https://github.com/dotnet/runtime/blob/01d4dca28248fd21fe512badd4d069d89d0ea563/src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs#L191) needs the assembly path which doesn't exist for single-file apps (see [here](https://github.com/dotnet/runtime/blob/01d4dca28248fd21fe512badd4d069d89d0ea563/src/coreclr/vm/debugdebugger.cpp#L741) where GetPath() returns an empty assembly path).

**Comment by jkotas** [comment]
Looks like a dup of #11261

**Comment by am11** [comment]
1. Embedded - probably duplicate of #11261
2. Physical PDB (default single file build using .NET5 SDK) - is this unsupported?

**Comment by jkotas** [comment]
> Physical PDB (default single file build using .NET5 SDK) - is this unsupported?

It is unsupported today. Embedded PDBs are the recommended way to make this work for single file.

**Comment by am11** [comment]
Alright, makes sense.
I haven't tested, but seems like `BundleFileLocation` or the static `Bundle::AppBundle->BasePath()` might help to cater both embedded/physical cases.

**Comment by AdamCaviness** [comment]
I'm watching this with interest. We need stacktraces with line numbers but to achieve that at present we have to deploy 468 files due to this issue. We are using Embedded PDBs. Is there a workaround in .net5.0 where I can use the old 3.1 self-extracting single-file approach to avoid this issue? Thanks.

**Comment by am11** [comment]
The output in the top-post is from .NET 5, where we don't get the `file:line` in expection traces (case with all three embedded, full and portable `DebugType`s).

In .NET 6 latest greatest preview (6.0.100-preview.5.21226.1), stack traces are even more broken.
```sh
Unhandled exception. System.Exception: foo
   at Program.Main() in app1.dll:token 0x6000001+0xa
Aborted
```
with all three `DebugType`s. Maybe we should first revert this fix, before attempting to fix the .NET 5 behavior. 🙂

**Comment by KevinCathcart** [comment]
@am11 I'm not sure what you think is wrong there. .NET 6 recently (#44013) added a new feature to print out token + il based offsets in stack traces if PDB information is not available. The idea is that later such stack traces can be combined with the PDB file to get the line numbers again. 

Since at the moment, the PDB's are not being loaded properly for stack traces in single file executables, what you are seeing would be the intended behavior. Of course, it would be ideal to fix this so that the PDB can be loaded at least for the embedded case.

---

I'm confused what the hold up is on fixing the embeded pdb case. According to [@mikem8361](https://github.com/dotnet/runtime/issues/34187#issuecomment-649144431) fixing this should be really easy. Like it seems to be [less than 30 changed lines of code](https://github.com/dotnet/runtime/issues/18423). 

The above linked code change is completely untested (not even compiled) but if it is not correct it should be *really* close. It is assuming that for non-file-layout in-memory assemblies that PEReader knows how to handle correctly for all platforms. If not, the code in StackTraceSymbols.GetPEReader can be trivially changed to only try to load from memory for the on-disk layout case, which it definitely knows how to handle correctly. That leaves us no worse off than today, and would enable use of embedded symbols for the file-layout in memory case, which is what we care about here.

The other reason I have not submitted a pull request of the above is because I don't feel like setting up the needed unit test. This requires creating a new project file configured with `<DebugType>embedded</DebugType>`, that contains a class with a static method that gets a stack frame and verifies that its own method contains line numbers, returning false or throwing if line number were not present. The main System.Diagnostics.StackTrace test project would have a project reference to said assembly such that it would get copied to the build output directory. The actual unit test in the main test project would load the helper assembly via a byte array along the lines of `Assembly.Load(File.Read("HelperAssembly.dll"))` (probably need to do something slightly fancier to get the correct path), and then call the previously mentioned static method via reflection. The test fails if the method returns false or throws, otherwise it succeeds.

I'm simply not set up with a working runtime development environment at the moment, to actually do this properly, but I'm guessing this would be a really quick and easy thing for somebody correctly set up, if they started with my above untested code.
