### ISSUE TITLE
System.Text.Json: Preserve JsonException.Path

### ISSUE THREAD

**Issue by weifenluo** [dotnet/runtime#51537]
`JsonException` is mutable, notably in [AddJsonExceptionInformation(in ReadStack state, in Utf8JsonReader reader, JsonException ex)](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs#L347) and [AddJsonExceptionInformation(in WriteStack state, JsonException ex)](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs#L383). When converters of complex type throws `JsonException` with `Path` property set, the information will be overwritten. It's better to preserve this information by concating existing `Path` data:

```C#
string path = state.JsonPath();
if (!string.IsNullOrEmpty(ex.Path))
{
    path = path + ex.Path;
}
ex.Path = path;
```

**Comment by eiriktsarpalis** [comment]
This seems to be caused by the following two catch blocks: https://github.com/dotnet/runtime/blob/ddaa1c3c503f989db48102f50a693765e4e6ae2a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.WriteCore.cs#L50 and https://github.com/dotnet/runtime/blob/ddaa1c3c503f989db48102f50a693765e4e6ae2a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs#L94

This is catching any `JsonException` exceptions and overwriting the `Path` property. Perhaps we should be using the [`ReThrowWithPath`](https://github.com/dotnet/runtime/blob/ddaa1c3c503f989db48102f50a693765e4e6ae2a/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs#L331) method instead? cc @steveharter @layomia
