### ISSUE TITLE
[Blazor WASM] - Investigate 6% size regression in System.Collections.dll.br

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#51572]
Size increase in System.Collections.dll.br as observed in https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0

![image](https://user-images.githubusercontent.com/46026722/115444696-ea44f280-a1e2-11eb-97b5-5455b7a02396.png)

cc @CoffeeFlux - is this worth investigating ?

**Comment by GrabYourPitchforks** [comment]
Likely related to https://github.com/dotnet/runtime/issues/51571. Seeing lots of infrastructure to support `SortedDictionary` and `SortedSet` coming back into the assembly. Will track down the callers.

![image](https://user-images.githubusercontent.com/1746272/115482487-a9a9a100-a203-11eb-86ce-85cb47bee1aa.png)

**Comment by GrabYourPitchforks** [comment]
I believe the code path below is responsible for this regression.

https://github.com/dotnet/runtime/blob/ccc25a90082fa6592eeca8e146ff37e1b7d6b79d/src/libraries/System.Text.Json/src/System/Text/Json/Node/JsonObject.IDictionary.cs#L108-L124

In particular, on line 120, there's a call to `Dictionary.Remove(string)`. However, the `Dictionary` property getter is typed as `IDictionary<,>`, backed by an `IDictionary<,>` field. This means that the linker needs to keep every possible implementation of `IDictionary<,>.Remove` around, and in the case of `SortedDictionary<,>` that means also keeping much of the `SortedSet<>` infrastructure around as well.

If the `Dictionary` property getter is changed to be a strongly-typed `Dictionary<,>` rather than an interface `IDictionary<,>` I believe this might resolve the issue, since the target method will now be statically known rather than a virtual dispatch.

**Comment by layomia** [comment]
cc @steveharter. This overlaps with the effort to use a strongly-typed sorted dictionary to store `JsonObject` values (to preserve insertion order when enumerating over the object).

---

That aside, this is related to https://github.com/dotnet/runtime/issues/51311 and my comment here https://github.com/dotnet/runtime/issues/51571#issuecomment-824145051.
