### ISSUE TITLE
Exception in Dispose() prevents host from shutting down

### ISSUE THREAD

**Issue by meum** [dotnet/runtime#51622]
I'm not sure if this is a bug or not, but I could not find it documented anywhere.
When a service which implements IDisposable throws an exception in Dispose(), the host never shuts down.

To reproduce, run this code and hit Ctrl + C
```
    public class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                IHost host = Host.CreateDefaultBuilder(args)
                    .ConfigureServices(services => services.AddSingleton<Class>())
                    .Build();

                host.Services.GetRequiredService<Class>();
                host.Run();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }

    public class Class : IDisposable
    {
        public void Dispose()
        {
            throw new Exception();
        }
    }
```

After a few seconds. this is printed:
```
info: Microsoft.Hosting.Lifetime[0]
      Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.
```

**Comment by eerhardt** [comment]
Looks like the issue here is that the `ConsoleLifetime` service isn't getting disposed, and thus hanging the process:

https://github.com/dotnet/runtime/blob/65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed/src/libraries/Microsoft.Extensions.Hosting/src/Internal/ConsoleLifetime.cs#L79-L90

https://github.com/dotnet/runtime/blob/65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed/src/libraries/Microsoft.Extensions.Hosting/src/Internal/ConsoleLifetime.cs#L104-L106

The reason `ConsoleLifetime` isn't getting disposed is because the exception in the `Class` service is being thrown first, so none of the other services get disposed.

The following DI code captures the first exception from a service and returns it without disposes the rest of the services:

https://github.com/dotnet/runtime/blob/65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs#L106-L132

**Comment by davidfowl** [comment]
Isn't throwing from dispose a no-no?
