### ISSUE TITLE
Use Marshal.GetLastPInvokeError instead of Marshal.GetLastWin32Error in NETCoreApp

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#51648]
.NET 6 introduces `Marshal.GetLastPInvokeError` that has the same functionality as `Marshal.GetLastWin32Error`, but is named to be representative of what it does: https://github.com/dotnet/runtime/issues/46843

Usage in NETCoreApp should be updated to use `GetLastPInvokeError` instead of `GetLastWin32Error`. Note that not all usage in libraries can be updated, since some libraries compile for down-level targets.

**Comment by KZedan** [comment]
Hey, interested in contributing. How do I get this assigned to me? :D

**Comment by KZedan** [comment]
@elinor-fung I have linked the PR to this issue however there seem to be some failing builds in the CI but I have noticed the same issue happening in different PRs where the same build is failing. I am assuming this is a known issue with the builds?

As you mentioned there were invocations of the method that I had to revert back to `Marshal.GetLastWin32Error` as they were causing build errors.

Let me know if this covers it.

Thanks!

**Comment by jkotas** [comment]
#52003 converted some of the occurences. I believe that there are more than can be converted.

**Comment by KZedan** [comment]
@jkotas I've managed to get the remaining done that were referenced in system.private.corelib. There were some conflicts due to different framework versions of the package being used simultaneously. I followed the readme and added the ref for System.Runtime.Interop directly into the relative slns.

One thing that I am confused about currently is after making this change, the Interop.Crypt32.CryptProtectData call is now complaining about a compilation error as the string szDataDescr param is not nullable when it's being passed as null in ProtectedData.cs. This is in the System.Security.Cryptography.ProtectedData library. It seems that before it was being passed as such but this compilation error must have been suppressed somehow. 

Any ideas what might be causing this?

I've attached the PR as a reference with the parameter being tweaked to become nullable but I am under the impression that it is not supposed to so.

![image](https://user-images.githubusercontent.com/48921114/117057834-d1295f00-ad15-11eb-9c1b-41dfb38f0238.png)
![image](https://user-images.githubusercontent.com/48921114/117057889-e4d4c580-ad15-11eb-89ca-a37e0f791ebd.png)

**Comment by jkotas** [comment]
> Any ideas what might be causing this?

I think it may be because of you have added $(NetCoreAppCurrent) target.

I am not sure that it is worth it to be adding ifdefs to files that are used in multiple places. I think it would be better to use the existing API without an ifdef.

Have you looked at the places outside corelib?

**Comment by KZedan** [comment]
> Have you looked at the places outside corelib?

Nope, I was under the impression that corelib had everything contained in its sln library-wise (that's the readme said), sounds like that's not the case though, where else should I be looking?

**Comment by KZedan** [comment]
Ah nevermind, I just found a bunch in externals.csproj

**Comment by jkotas** [comment]
Any `Marshal.GetLastWin32Error` under src/libraries in this repo is a candidate, as long as it does not require ifdefs to update.

**Comment by elinor-fung** [comment]
Thank you, @KZedan!

**Comment by KZedan** [comment]
No problem!
