### ISSUE TITLE
ComWrappers API missing de-registration method

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#51730]
Currently if somebody call `ComWrappers.RegisterForMarshalling` in the process, there no way to undo that operation. That would be useful for tests. I personally encounter that when implementing tests for https://github.com/dotnet/runtimelab/pull/992, but that may be valid scenario for the WinForms ComWrappers, or WPF if they appears. Create one test exe for each test scenario seems a bit wasteful.

**Comment by jkotas** [comment]
Note that `ComWrappers.RegisterForTrackerSupport` has same limitations.

>  that may be valid scenario for the WinForms ComWrappers, or WPF if they appears

I do not think it would be a good idea to repeteadly register / unregister the global ComWrappers in any real world application. It would be a factory for race conditions.

> That would be useful for tests.

NativeAOT smoke tests are not designed to provide comprehensive test coverage. You may want to look at running the full ComWrappers tests under runtimelab\src\tests\Interop\COM\ComWrappers for the comprehensive test coverage.

**Comment by AaronRobinsonMSFT** [comment]
>Currently if somebody call ComWrappers.RegisterForMarshalling in the process, there no way to undo that operation.

@kant2002 That is true. These global state impacting functions are for specific scenarios where a singular tool is responsible for orchestration - e.g. [C#/WinRT](https://github.com/microsoft/CsWinRT). The purpose of the `ComWrappers` API is to enable source generators and in practice avoid any of the built-in marshalling APIs. In fact the global concepts were introduced for practical reasons to support the pre-existing WinRT [Reference Tracker runtime contracts](https://docs.microsoft.com/windows/win32/api/windows.ui.xaml.hosting.referencetracker/).

**Comment by kant2002** [comment]
@AaronRobinsonMSFT so current vision, is that each library use something in the spirit of [DllImportGenerator](https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator) for each individual library who need COM. That library can then create proper ComWrappers implementation, and let's say, if I declare something like 
``
[DllImport]
static void DoComMagic(IComInterface pInterface);
``` 

then it will be unrolled by source generators in following way.
```
class LibraryComWrappers : ComWrappers
{
    internal static LibraryComWrappers Instance {get;}
}

static void DoComMagicImp(IntPtr pInterface);

partial static void DoComMagic(IComInterface pInterface)
{
    IntPtr comInterface = LibraryComWrappers.Instance.GetOrCreateComInterfaceForObject(pInterface, CreateComInterfaceFlags.None);
    DoComMagicImp(comInterface);
}
```

Also in a sense current state of ComWrappers is transitional state, until WinForms and WPF and UWP would be able to implement required source code generators, so each library/framework would use their own ComWrappers implementation.
And if I understand things properly source generators is to have more or less same way to define interop, without too much boilerplate.

Am I properly aligned with your vision?

**Comment by AaronRobinsonMSFT** [comment]
> Am I properly aligned with your vision?

Yes.

>Also in a sense current state of ComWrappers is transitional state

Not entirely sure what is meant by this. The `ComWrappers` API represents a basic building block for all future COM interop. As far as using it directly, I could see this as a "transitional" state until the Interop team or community creates a default source generator. However, whatever the default source generator looks like there will always be an opportunity for others to innovate by writing their own or forking the default.

Some notes about WinForms and WPF. Both use COM, but in slightly different ways. WinForms basically requires COM to be a fully realized windowing stack. Without COM support the automation side of UI isn't possible nor is the ActiveX integration available. WPF on the other hand uses COM as an implementation details in most cases rather than exposes it as a core feature. This means that WinForms will likely require a solution that libraries that want to integrate with it must adopt where as WPF can offer a solution as a side car. This isn't saying that both won't eventually adopt the same solution just that they are different and use COM in different ways. Using both UI stacks at the same time is also important so that does need to be considered however `ComWrappers` is consumed by either UI stack.

The UWP stack is currently supported by .NET Framework and .NET Native only. These models rely on a very different interop system through WinRT interopThe first step toward support in a .NET 5+ environment was to develop the `ComWrappers` API to help bring up the [C#/WinRT](https://github.com/microsoft/CsWinRT) tool chain. I highly recommend looking at the C#/WinRT project as it demonstrates our longer term vision for how COM interop is likely to look in .NET.

**Comment by kant2002** [comment]
> Not entirely sure what is meant by this. The `ComWrappers` API represents a basic building block for all future COM interop. As far as using it directly, I could see this as a "transitional" state until the Interop team or community creates a default source generator. 

Yes. I was thinking that most likely community adopt whatever tech comes from Microsoft, for better, or for worse. I understand that WinForms and WPF is separate, but from consumer perspective, once something which works for both (and this definitety happens) will be implemented, I (and many others) would lean towards that solution. I know that I speculate here and how it happens in real-life nobody knows.

> I highly recommend looking at the C#/WinRT project as it demonstrates our longer term vision for how COM interop is likely to look in .NET.

I take that advice to heart, I just currently do not have project, where I can vivisect sufficiently complex UWP application, but I promise I will look for it.
