### ISSUE TITLE
File.Exist multi user flaw

### ISSUE THREAD

**Issue by AvrumFeldman** [dotnet/runtime#51910]
# Summary
When probing if a file exist on multi user session machine, there seems to be a flaw where if a privileged user tests for a file, then for the next 10 seconds if a non privileged user probes they get the results based on the privileged users access. This should not be happening.

# Steps to reproduce
1. Create a file share on a computer with permissions to specific users. (I used a domain joined computer)
2. From a second computer log in two users at once (either use a terminal server or use runas).
3. Test a file that is hosted on the share using
[system.io.file]::exists(*unc path*) .net class (I used PowerShell to test)
    * First test from the non privileged user - you should get a false
    * then from the privileged user - you should get a true
    * then right away from the non-privileged user again - This time you will get a true.
  
    Meaning the denied user was somehow able to read the file.

**Comment by AvrumFeldman** [comment]
__Update:__ Seems we can even get some filesystem info from the file using the above method, for example the `getlastwritetimeutc()` method returns the correct info. I tried reading the content using the same method but at the moment I was not able to, but I wouldn't be surprised if someone is able to take this further and be able to read the content as well.

**Comment by KalleOlaviNiemitalo** [comment]
File.Exists on Windows goes to [FileSystem.FileExists](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/Common/src/System/IO/FileSystem.Attributes.Windows.cs#L36) and from there to [GetFileAttributesEx](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/Common/src/System/IO/FileSystem.Attributes.Windows.cs#L63). .NET does not cache these results. Therefore, I think you'd get similar behavior by calling GetFileAttributesEx ([Win32 documentation](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesexw)) directly from a C program. Which would then mean that the bug is in the Windows operating system (perhaps in the SMB redirector) rather than in .NET.

**Comment by KalleOlaviNiemitalo** [comment]
I'm curious whether the behavior depends on the cache settings described in [Performance tuning for file servers](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/) and [Set-SmbClientConfiguration](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbclientconfiguration?view=windowsserver2019-ps). If you configure **FileInfoCacheLifetime**  as 0 seconds on the client machine, does that prevent the information leak (while costing more network I/O)?

**Comment by AvrumFeldman** [comment]
Thanks @KalleOlaviNiemitalo the __FileInfoCacheLifetime__ indeed controls the behavior. I wonder though if it is a bug or by design. My intuition tells me it is a bug, as cache should not be shared between users.

**Comment by AvrumFeldman** [comment]
What is interesting though is when testing using cmd and `if exists <path> (echo true) else (echo false)` I did not get that behavior.

**Comment by KalleOlaviNiemitalo** [comment]
`IF EXIST` in cmd.exe of Windows 10 20H2 appears to use [FindFirstFileEx](https://docs.microsoft.com/windows/win32/api/fileapi/nf-fileapi-findfirstfileexw) rather than [GetFileAttributesEx](https://docs.microsoft.com/windows/win32/api/fileapi/nf-fileapi-getfileattributesexw).

The RDBSS [Name Cache Management](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/name-cache-management) topic mentions SMB. Perhaps those routines are what the redirector uses to manage the cache.

I doubt Microsoft is going to try to completely block this information leak. Sharing the file cache between users seems likely to save a lot of time and memory, and perhaps lets memory-mapped files behave more coherently. It might be difficult for the SMB redirector to limit what information it reveals from the cache to each user, if the file server does not tell it the access control list of the file share. Even with ACL checks, a timing attack might be able to reveal whether a file exists.

File content seems easier to protect from unauthorized users, and I'll be surprised if you are able to bypass that.

**Comment by GrabYourPitchforks** [comment]
Hi @AvrumFeldman. This isn't a .NET issue and .NET has no control over this behavior, but I'm forwarding the thread to some folks in the Windows org to see if they have thoughts.

**Comment by AvrumFeldman** [comment]
@GrabYourPitchforks fair enough. Thanks for your involvement.

**Comment by GrabYourPitchforks** [comment]
@AvrumFeldman We handed this off to MSRC and the Windows team. They've categorized it as _Moderate_ class (see https://aka.ms/windowsbugbar, bottom of pg. 9) and are investigating an appropriate path forward. They're tracking the issue in their internal issue tracker. Unfortunately I won't have much visibility into or influence over this process, and I won't be able to relay information back here, so I'm going to close this GitHub issue.

Thank you again for the report!
