### ISSUE TITLE
System.Net.Http innerloop tests have gotten much slower

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#51942]
These used to take ~15s on my machine; now it's >100s.

**Comment by geoffkizer** [comment]
Looks like the main culprit is new SOCKS proxy tests:

System.Net.Http.Functional.Tests.Socks.SocksProxyTest_Http1_Async.TestLoopbackAsync
System.Net.Http.Functional.Tests.Socks.SocksProxyTest_Http1_Async.TestExceptionalAsync

**Comment by geoffkizer** [comment]
@huoyaoyuan @MihaZupan Any idea why these tests are so slow?

**Comment by MihaZupan** [comment]
These run in quite a matrix, so I think 84 combinations of `LoopbackAsync` and 45 combinations of `ExceptionalAsync`.
But they should still be very fast to execute.

Compared to all the other loopback tests, these do
`Client <=> Loopback Proxy Server <=> Loopback Server` instead of
`Client <=> Loopback Server`.

I don't see anything suspicious standing out though.

**Comment by MihaZupan** [comment]
Is it specifically the Http11+Async ones that are being slow or just all socks tests in general?

**Comment by geoffkizer** [comment]
Looks like all of them to me -- HTTP11/Async, HTTP11/Sync, and HTTP2.

**Comment by huoyaoyuan** [comment]
Can sync over async in test server ever be a problem?
Without profiling or measuring, I can't guess what's actually costful.

Or, can it be the overhead of sockets? The socks proxy handler reads and writes the socket stream a lot without buffering.

**Comment by geoffkizer** [comment]
> Can sync over async in test server ever be a problem?

It could be. It could cause thread starvation. Are there places we are doing this?

**Comment by MihaZupan** [comment]
I found the root cause - we're using `localhost` as the proxy Uri instead of `127.0.0.1` 🤦‍♂️
