### ISSUE TITLE
SafeBCryptHashHandle instances in finalize queue after dispose of HMAC instances

### ISSUE THREAD

**Issue by avendel** [dotnet/runtime#52041]
### Description

When disposing instances of e.g. ``System.Security.Cryptography.HMACSHA256``, the ``SafeBCryptHashHandle`` instance can still be found in the finalizable objects queue.

Here is a minimal repro.

```
for (int i = 0; i < 100; i++) {
    using (var hmacsha = new HMACSHA256()) {
        hmacsha.ComputeHash(new byte[100]);
    }
}

// Wait and enable capturing a process dump
Console.ReadKey();
```

Capture a dump of the process and analyze it, e.g. with ``dotnet-dump analyze`` and the ``finalizequeue`` command. You will see that there are 100 instances of the ``SafeBCryptHashHandle`` class.

```
Statistics for all finalizable objects (including all objects ready for finalization):
              MT    Count    TotalSize Class Name
00007ffc150664a0        1           32 Microsoft.Win32.SafeHandles.SafeBCryptAlgorithmHandle
00007ffc1503a8e8        2           48 System.WeakReference`1[[System.Diagnostics.Tracing.EventSource, System.Private.CoreLib]]
00007ffc1503d548        1          184 System.Diagnostics.Tracing.NativeRuntimeEventSource
00007ffc15035790        1          368 System.Diagnostics.Tracing.RuntimeEventSource
00007ffc15036fb0        4          448 System.Diagnostics.Tracing.EventSource+OverrideEventProvider
00007ffc15069410      100         3200 Microsoft.Win32.SafeHandles.SafeBCryptHashHandle
Total 109 objects
```

### Configuration

Can reproduce this on 3.1 and 6.0.100-preview.2.21155.3 on Windows 10.

### Other information

Here is the allocation stack trace:

```
Internal.Cryptography.HashProviderCng.ctor(String, Byte[])
Internal.Cryptography.HMACCommon.ChangeKey(Byte[])
System.Security.Cryptography.HMACSHA256.ctor(Byte[])
```

Looking at the code, all instances seem to be disposed from HMACSHA256 down to the SafeBCryptHashHandle. There is however a scenario in HashProviderCng that handles pre-Win8 (according to code comments) that might cause this. Or maybe I'm missing something in the way SafeHandle instances are supposed to work.

**Comment by vcsjones** [comment]
Thanks for the excellent research and information on this. To me, the issue appears to be when the HMACCommon needs to fixup the key when the input key is larger than the MAC's block size. In that case, we end up hashing the key so that the key as exposed to the user is actually the key that ends up getting used.

That hash provider was not getting disposed of, so it ended up leaving the hash handle in the finalization queue. I opened a PR to address this.

**Comment by avendel** [comment]
That makes sense looking at the code, if one passes a key longer than the block size of 64. I can still reproduce the issue when passing a shorter key than the block size, though. And the default constructor of HMACSHA256 creates a random key of the block size length.

**Comment by vcsjones** [comment]
@avendel Fair point. The other issue should be fixed regardless, but I changed that PR to not close this issue while I look in to that further.

**Comment by vcsjones** [comment]
Doesn't seem specific to Windows. On Linux:

![image](https://user-images.githubusercontent.com/361677/116795620-560d4200-aaa4-11eb-8a2c-6a465b407c6a.png)

**Comment by vcsjones** [comment]
@bartonjs @GrabYourPitchforks  maybe I am misunderstanding how the finalization queue works. If I run this program:

```csharp
using System;

for (var i = 0; i < 100; i++) {
    using (var _ = new Potato())
    {
        
    }
}

Console.WriteLine(Environment.ProcessId);
Console.ReadKey(true);

class Potato : IDisposable
{
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
        Console.WriteLine("supressed");
    }

    protected void Dispose(bool disposing)
    {
        if (disposing)
        {
        }
    }

    ~Potato()
    {
        Dispose(false);
    }
}
```

I have 100 potatoes in the finalization queue, even though I've suppressed finalization (and my console out appears). Do things remain in this queue even if suppressed?

![image](https://user-images.githubusercontent.com/361677/116796243-f7969280-aaa8-11eb-8790-8c82d5eb3361.png)

Similarly, if I go back to the HMAC example, and dump one of the objects in the queue:

![image](https://user-images.githubusercontent.com/361677/116796333-a2a74c00-aaa9-11eb-9a41-820be9cab1cc.png)

I can see that the handle is zero (which is because `ReleaseHandle` sets it to zero)

https://github.com/dotnet/runtime/blob/d2fba8fdc44f5ed7a4676c219c626e36a3fa2998/src/libraries/Common/src/Microsoft/Win32/SafeHandles/SafeHmacCtxHandle.Unix.cs#L19

And the `state` is 3 (0b11), which means it looks like it has been disposed:

https://github.com/dotnet/runtime/blob/d2fba8fdc44f5ed7a4676c219c626e36a3fa2998/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L34-L42

**Comment by avendel** [comment]
When reading about ``GC.SuppressFinalize`` online, you will find articles mentioning that calling the method will prevent the object from being put in the finalizer queue. Some memory profilers also warns about objects in the finalizer queue and suggest implementing the Disposable pattern. However, the official documentation of ``SuppressFinalize`` says that calling it will just set a bit on the object header preventing its finalizer from being called.

So I think the misunderstanding here is a mixup between the __finalizer_ queue and the _freachable_ queue. Objects should not end up in the freachable queue, though.

It looks like we're learning things in the open here and that my reported issue might not be a problematic issue. =)

The best article I could find on the subect was an old one covering GC in .Net Framework: https://docs.microsoft.com/en-us/archive/msdn-magazine/2000/november/garbage-collection-automatic-memory-management-in-the-microsoft-net-framework. Here are some excerpts:

> When an application creates a new object, the new operator allocates the memory from the heap. If the object's type contains a Finalize method, then a pointer to the object is placed on the finalization queue.

> The garbage collector scans the finalization queue looking for pointers to these objects. When a pointer is found, the pointer is removed from the finalization queue and appended to the freachable queue 

> When you call SuppressFinalize, it turns on a bit flag associated with the object. When this flag is on, the runtime knows not to move this object's pointer to the freachable queue, preventing the object's Finalize method from being called.

So unless the object ends up in the freachable queue, things are probably working as designed.

**Comment by bartonjs** [comment]
My understanding is that we've gotten this to a happy state.  If not, just reactivate and let me know what I missed :smile:.
