### ISSUE TITLE
Missing StartupFlags in Runtime/Start event

### ISSUE THREAD

**Issue by kkokosa** [dotnet/runtime#52042]
`/Runtime/Start` event contains `StartupFlags` field, informing on various attributes provided to host. They were very useful, for example in PerfView analysis - showed in GCStats CLR Startup Flags view. It was a super convenient way to check GC mode, with the help of CONCURRENT_GC/SERVER_GC values. Especially when analysis of sessions recorded on external, not fully controlled environments (like customer support etc.). These flags are reported in .NET Framework apps, but [are not used in .NET Core/.NET 5](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/vm/eventtrace.cpp#L5048-L5104).

I wonder how we can return to informing about GC modes in the recorded session? Do we need a new dedicated "GC settings" event for that (taking the opportunity to add something more than GC mode)? I've created an issue on [PerfView side too](https://github.com/microsoft/perfview/issues/1420), but apparently, we need runtime support for that. Or maybe I'm missing something and we can get this info from a trace?

**Comment by brianrob** [comment]
@noahfalk, @tommcdon

**Comment by tommcdon** [comment]
@sywhang @josalem

**Comment by josalem** [comment]
You're correct, it looks like the `startupMode` and `startupFlags` parameters are both unset when the event is fired. This event _should_ be showing up in .net traces, but that field will be zero. I'll take a look at where we can get that information from and if we can inject it into the event since the field is already there.

CC @cshung who might know off the top of his head where the GC flags are stored or if they're being sent in a new/different event.

**Comment by Maoni0** [comment]
it's unfortunate this code was simply deleted, ironically it's the same way to get the startup flags for GC in coreclr as on .NET framework -

`startupFlags = CorHost2::GetStartupFlags();`

this is how the startup flags are obtained in `InitializeStartupFlags` [in ceemain.cpp](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/ceemain.cpp#L418).
