### ISSUE TITLE
[Question] Packing multiple assemblies into a single assembly

### ISSUE THREAD

**Issue by wstaelens** [dotnet/runtime#52049]
In .NET Framework 4.8 we use Fody Costura to pack multiple (20+) assemblies into a single assembly.

In .NET Core / .NET 5 I've read that you can create a single exe (self contained). ( related: [#19227](https://github.com/dotnet/runtime/issues/19227) )

How can this be done with assemblies where the resulting file is an assembly (.dll) and not an executable (.exe) ?

* Can we modify the project and add several EmbeddedResource statements?
* Should we use ILMerge ? ILRepack ? (Fody ...?)

**Comment by KevinCathcart** [comment]
On .NET Core, the team would recommend against trying to do such assembly merging. You seem to know the various approaches that could be used to do this, so let's talk about why they would not recommend this.

The tooling and ecosystem of .NET Core are designed to encourage users not to think about individual DLL assemblies, but to think in terms of NuGet packages. Normally users of your library have typically don't need to know or care if your library has 1 assembly, or many, or depends on other NuGet packages. They gain no real convenience by having you combine your DLLs.

If the end app developer is worried about the total number of DLLs in their output directory, then they can use the the single file deployment option.

Certain methods for assembly combining won't function well with the IL linker (which contrary to its name, does not link assemblies into one executable, but instead trims out unused code). Other techniques may cause issues with the deps.json approach used by the default assembly load context. This is in addition to the normal issues of these techniques where they can cause headaches if one of the combined libraries is also independently used elsewhere in the end application. Depending on approach this can result in compile time errors, since the compiler sees two different types with the same name and namespace, or runtime errors, where expected versions of certain assemblies don't get loaded.
 
If you still want to combine your assemblies despite all this, I believe that any of the mentioned approaches could still work. I'm not sure it makes sense to try and specify one as preferred, since they have different upsides and downsides.

**Comment by jkotas** [comment]
@KevinCathcart Thank you for answering this question! The answer is spot-on.

>  IL linker (which contrary to its name, does not link assemblies into one executable

We are switching to call it IL trimming going forward to avoid this confusion.
