### ISSUE TITLE
System.Text.Json.JsonElement.ToString return type is nullable but documentation suggests otherwise

### ISSUE THREAD

**Issue by BertanAygun** [dotnet/runtime#52069]
### Description

As we updated our code to use new version of System.Text.Json, we noticed that System.Text.Json.JsonElement.ToString now returns "string?" (which also follows object.ToString). However documentation doesn't list any cases where null can be returned. Is there a case where null may be returned? Based on documentation we have been assuming that a null return wasn't possible and haven't encountered any such case so far.

If null return is not possible can the override be changed to return "string" (which I believe is possible) so that we don't have to suffix the call with "!" each time.

Area should be area-System.Text.Json but I can't add the label it looks like.

**Comment by stephentoub** [comment]
@bartonjs, it looks like JsonElement.ToString() returns a nullable string because of this:
https://github.com/dotnet/runtime/blob/4bdaa8e2fb06b1065d0e418d21abd80dfff00a8f/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonElement.cs#L1407-L1408
and GetString() returns a nullable string.  But we're only calling `GetString()` if the token type is String, and `GetString()` will only return null if the token type is Null... so... should JsonElement.ToString() actually be changed to return a non-nullable string and this call to `GetString()` be `GetString()!`?

**Comment by bartonjs** [comment]
> so... should JsonElement.ToString() actually be changed to return a non-nullable string and this call to GetString() be GetString()!?

Yep.
