### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe.dll doesn't contain source code attributes

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#52174]
Most runtime assemblies contain meaningful source code metadata attributes like these:

```
[assembly: AssemblyFileVersion("6.0.21.21502")]
[assembly: AssemblyInformationalVersion("6.0.0-preview.4.21215.2+3ffaab9b6f90c8f5169cf529035d209b060b1d83")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
```

However `System.Runtime.CompilerServices.Unsafe.dll` only has these:

```
[assembly: AssemblyFileVersion("6.0.21.21502")]
[assembly: AssemblyInformationalVersion("6.0.0-preview.4.21215.2")]
```

It's not critical but in my case it results my analysis tools finding a distinct dependency.

**Comment by teo-tsirpanis** [comment]
Since at least #64861 this assembly just contains type forwards and its attributes are similar to what other assemblies get. The OOB package with the same name has also been discontinued (stuck at 7.0.0-preview.2). Closing.

![image](https://user-images.githubusercontent.com/12659251/178125296-fa1aa2b4-9c06-4c78-9f42-0a1247bef82d.png)
