### ISSUE TITLE
Using ManagementObjectSearcher in WPF with Core 3.0/3.1 stops Stylus & Touch inputs

### ISSUE THREAD

**Issue by spacestr** [dotnet/runtime#522]
I have a Windows WPF app that uses Mouse and Touch.
It uses System.Management to get things like OS and CPU information.

Here is a simplified example (start with a new WPF .NET Core 3 project).

```
using System.Diagnostics;
using System.Management;
using System.Windows;

namespace test
{
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            GetOs();
            base.OnStartup(e);
        }
        private static void GetOs()
        {
            using (var searcher = new ManagementObjectSearcher("SELECT Caption FROM Win32_OperatingSystem"))
            {
                foreach (var query in searcher.Get())
                {
                    var operatingSystem = query["Caption"].ToString();
                    Debug.WriteLine(operatingSystem);
                    break;
                }
            }
        }
    }
}
```

When I subscribe MainWindow to any of the mouse and touch events (ex: PreviewMouseDown, PreviewTouchDown - I have a touch screen) I expect them to get triggered.

With .NET Framework 4.6.2 and 4.7.2, this works as expected.
With .NET Core 3.0 and 3.1 (need to import System.Management 4.6 or 4.7 package), this code causes touch events to never trigger, yet mouse events work. (But if I comment out the entire foreach loop or the call to GetOs, touch events work again).

(Tested on Windows 10 Enterprise 64-bit and Windows 8 Embedded 32-bit)

**Comment by YerongAI** [comment]
No any progress now? I have the same problem.

**Comment by spacestr** [comment]
Microsoft never responded, but I found this workaround:
In you application startup code, add this line:

_ = Tablet.TabletDevices;

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT off the top of your head, any idea why performing an operation with WMI (which is COM based) might then prevent event handlers for UI events from being called? Some kind of message filter?

**Comment by spacestr** [comment]
I think it's described in the comments of this issue:
https://github.com/dotnet/wpf/issues/2393

**Comment by danmosemsft** [comment]
@spacestr thanks. I don't think that explains to me why using WMI - which is presumably causing that thread to initialize COM - is triggering the problem. But it does seem clear that the fix is in WPF, so I'll close this.

**Comment by AaronRobinsonMSFT** [comment]
@danmosemsft If I had to guess I would say this is occurring because of implicit MTA semantics and the other aspects of the system not anticipating that, calling into COM, expecting a failure, and then setting up an STA. Since COM was already initialized instead of failing the implicit MTA activates the MTA on the thread and that plays heck with other aspects of the WPF application - in this case touch.

The above is merely a guess at what could be going on. I am going to defer to the WPF team to drive an needs for a resolution on the runtime side of things.

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT can you remind me, what was the change in behavior here from .NET Framework -- we always initialize threads to MTA implicitly now?

Just curious. I agree next action is not on us.

**Comment by AaronRobinsonMSFT** [comment]
> can you remind me, what was the change in behavior here from .NET Framework -- we always initialize threads to MTA implicitly now?

@danmosemsft I am not sure of the exact change that is involved here, but we do do things differently. I am assuming COM was initialized somewhere prior and that is possibly causing issues. We tend to preemptively initialize COM for a myriad of reasons - most of them because we are about to use a COM API.

The "implicit MTA" is a concept in COM that is unrelated to anything the CLR does. The implicit MTA is a "helpful" undocumented semantic that assumes if any thread in the process has initialized COM for MTA but the current thread hasn't then it will be implicitly initialized as an MTA thread. Yay for convenience... I guess? The downside is the implicit MTA doesn't actually add ref the MTA apartment it just added the thread to. Which means that if the thread that did initialize for the MTA calls `CoUninitialize()` the MTA apartment is shut down and the thread that was implicitly initialized will cause substantial damage if it uses COM.

That isn't happening in the case above. I am hypothesizing that the thread is in an apartment accidentally because we removed COM initialization for STA in a code path and now it is in an implicit MTA instead of indicating it isn't as would happen if only an STA apartment had been created.

**Comment by danmosemsft** [comment]
Interesting, thank you.
