### ISSUE TITLE
Add concurrent/ multi threaded version of PriorityQueue<T>

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#52205]
## Background and Motivation

`System.Collections.Generic.PriorityQueue` is a great addition but its lack of multi threading support. Please add a multi thread safe variant of it. A great example would be a download queue, where downloads are processed in background while downloads are adding in main thread.

Performance penalties are not an issue, similar to Concurrent collections.

## Alternative Designs

None

## Risks

None

**Comment by danmoseley** [comment]
The existing concurrent collections exist because they can use a different implementation to be more scalable than simply putting appropriate (reader writer) locks on the entry points. Are there priority queue implementations that would do substantially better than just synchronizing access?

**Comment by eiriktsarpalis** [comment]
It would be interesting to see examples of lock-free priority queue designs as well as benchmarks demonstrating performance under high contention.

**Comment by Symbai** [comment]
@danmoseley As far as I've seen the Concurrent versions are *basically* the same just with locks/semaphores on add/remove. It has the benefit that we don't have to do this on our end and locks are difficulty to handle if the collection is not private and gets accessed from more than single class. It also bloats up our code.

And if a BlockingCollection uses semaphores on the entry points to give developers a thread safe collection. Why not doing the same with PriorityQueue? We have a Concurrent version of almost all other collections so far, except of the recent added PriorityQueue. Its just filling the gap.

**Comment by svick** [comment]
@Symbai That is not the case at all. The concurrent collections use lock-free algorithms when possible. And even when not possible, they often only lock a part of the collection, so that multiple concurrent updates can still happen. In other words, they were primarily designed for performance, not convenience.

And if you're looking for a version of `BlockingCollection` that supports priority, you could fairly easily implement `IProducerConsumerCollection` using `PriorityQueue` and locks and use that when constructing your `BlockingCollection`.

**Comment by Symbai** [comment]
That does not change the fact that we have concurrent collections for almost all non concurrent collection types. Except of priority queue. I don't care if its a "when possible lock-free" priority queue or if it uses locks as I'm not the one who writes it anyway. I've just requested a concurrent version of it.

**Comment by danmoseley** [comment]
@Symbai as you know, to add types into the core libraries they have to pay their way (due to eg semantic load, they must be supported for decades, and are held to higher breaking change bar). We generally don't believe that a simple wrapper that adds locks meets that bar.

If there was a PriorityQueue implementation that was significantly more scalable than that, and a proven need for it, that would be interesting.

**Comment by stephentoub** [comment]
> That does not change the fact that we have concurrent collections for almost all non concurrent collection types. 

This is simply not correct.  There's only ConcurrentDictionary, ConcurrentStack, ConcurrentQueue, and ConcurrentBag.  There's no corresponding "Concurrent" collection for `List<T>`, `HashSet<T>`, `LinkedList<T>`, `SortedDictionary<TKey, TValue>`, `SortedList<TKey, TValue>`, `SortedSet<T>`, `ArrayList`, `Hashtable`, `SortedList`, `HybridDictionary`, `NameValueCollection`, `OrderedDictionary`, `StringCollection`, `StringDictionary`, and so on.

> I don't care if its a "when possible lock-free" priority queue or if it uses locks as I'm not the one who writes it anyway. I've just requested a concurrent version of it.

Our policy is to only add a `Concurrent` collection when a) there is significant demonstrated need, and b) the implementation can be made faster and more scalable than just taking a lock around every operation.  `ConcurrentPriorityQueue` doesn't meet either bar.  You can read about challenges with building a scalable, thread-safe priority queue at https://www.1024cores.net/home/lock-free-algorithms/queues/priority-queues, for example.

**Comment by danmoseley** [comment]
The Intel implementation mentioned in that blog is the basis for the Microsoft CRT one which you can read here (or similar path) 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30032\include\concurrent_priority_queue.h

and you can see how little it provides. There's a queue of pending operations, that another thread helps service, but given both push() and pop() block on it, I don't see what value that thread provides. Also, I guess one would generally not expect push() to block.

**Comment by Symbai** [comment]
> > That does not change the fact that we have concurrent collections for almost all non concurrent collection types.
> 
> This is simply not correct. There's only `ConcurrentDictionary`, `ConcurrentStack`, `ConcurrentQueue`, and `ConcurrentBag`. There's no corresponding "Concurrent" collection for `List<T>`, `HashSet<T>`, `LinkedList<T>`, `SortedDictionary<TKey, TValue>`, `SortedList<TKey, TValue>`, `SortedSet<T>`, `ArrayList`, `Hashtable`, `SortedList`, `HybridDictionary`, `NameValueCollection`, `OrderedDictionary`, `StringCollection`, and so on.
> 

Really? Is that your argument? StringCollection is inofficially obsolete. Sorted is a different topic and for List we have the Bag which is more or less the same. HybridDictonary? Who the fuck uses that... NameValueCollection? Never heard of it. 99% of Developers are using Dictonary and List. A few uses Stack and Qeues and YOU (and everyone else here) knows that for sure, so I dont understand why you come the other way around with these rare collection types when I always said "ALMOST collection types". We have ConcurrentDictionary, ConcurrentStack, ConcurrentQueue and ConcurrentBag. This is why I always spoke about "almost" collection types. Its literally all types that 99% of developer uses.

Anyway, I've requested it. Drop it and then add it 2 months later by claiming it was your idea, I dont care. But I'm 100% sure after .NET6 releases there will be someone else requesting it if not me. It is a collection type where using multiple threads makes more sense then on any other collection type.

**Comment by stephentoub** [comment]
> Sorted is a different topic

It's not. "Priority" is a form of ordering, just as the "Sorted" collections provide a form of ordering.

> List we have the ConcurrentBag or BlockingCollection which is more or less the same

They are not.  List maintains order and enables random access; bag explicitly does not.  And BlockingCollection is just a wrapper around some other producer-consumer collection, by default ConcurrentQueue, adding in blocking semantics; it's not comparable to List.

> with these rare collection types

I'm not sure from where you're getting your usage data. HashSet is one of the most popular collection types.  LinkedList is used very frequently.  The Sorted types are very popular.  And the non-generic ones you ask who uses that or say you've never heard of it, they're also used; for example, the NameValueCollection you dismiss because you say you've never heard of it is shown to be instantated several thousands times in just the projects indexed by grep.app.

> Really? Is that your argument?
> Who the @^#$@# uses that

Swearing and criticizing valid arguments being made will not further your cause.

> Anyway, I've requested it

You have, and we've provided the reasons we have no intentions of shipping such a type, until a) there's much higher demand and b) we're able to provide a generalized implementation that's measurably better than just locking.  Even if (a) changes (you are not the first to express interest), I don't expect (b) will.

**Comment by danmoseley** [comment]
There is also no reason why you cannot make your own and put it on Nuget. It will be far easier for you to make changes to it there as well.
