### ISSUE TITLE
Code generated by Json source generator results in warnings in projects with nullable enabled

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#52227]
I think it's an issue with the nullability annotations on the getters and setters for [JsonMetadataServices.CreatePropertyInfo](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonMetadataServices.cs#L26-L27)

These should be:

```diff
- Func<object, T>? getter,
+ Func<object, T?>? getter,
```

etc

**Comment by Trolldemorted** [comment]
Aren't the warnings correct in this case, because System.Text.Json ignores the non-nullability?

**Comment by layomia** [comment]
> Aren't the warnings correct in this case, because System.Text.Json ignores the non-nullability?

There's robust logic in STJ to handle `null` on serialization and deserialization, including to support features like ignoring `null` on serialization. Because of this we don't leak `NullReferenceException` and related bugs. However, it would be most correct to accept `T?` on deserialization and return `T` on serialization, since property values could indeed be `null`. Unfortunately, I couldn't find a way to express this in a prototype to have the correct semantics, due [error CS0453](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0453?f1url=%3FappId%3Droslyn%26k%3Dk(CS0453)) given [this code](https://github.com/layomia/dotnet_runtime/commit/6bbf1b640889bec36a531912aa90bdd226380c51#diff-c0e6bc47405dcd7e6920cb0f76f369ef6a99a7ffca192e9cc581dbcfb6e01c8eR269-R270).

In the fix for the issue https://github.com/dotnet/runtime/pull/57178, I left the parameter type as `Func<object, T>? getter` and just [banged](https://github.com/dotnet/runtime/pull/57178/files#diff-b7da6b90947be2bdebc35f367d9dc2c5bb66dd3be881af8a2d6cbb9c18108a7fR659) the return value of the getter call in the generated code.
