### ISSUE TITLE
BUG: API:DateTime: AddYears & AddMonths calculation with leap year 

### ISSUE THREAD

**Issue by dadimsh** [dotnet/runtime#52271]
### Description
Bug when use DateTime.AddYears(Int32).AddMonths(Int32) to project a DateTime from a leap day (February 29th of leap year) to non leap year, result is less of one date.

Example:
Increment given date by **1 year** and **6 months**:
**Input: "2020-03-29" Expected: "2021-09-29" Actual: "2021-09-29" Result: Pass**
**Input: "2020-02-29" Expected: "2021-08-29" Actual: "2021-08-28" Result: Fail**

### xUnit Test

1, 2 test cases passed, But 3rd case failed

        [Theory]
        [InlineData("2019-02-28", 1, 6, "2020-08-28")]
        [InlineData("2020-03-29", 1, 6, "2021-09-29")]
        [InlineData("2020-02-29", 1, 6, "2021-08-29")]
        public void TestAddMonths(string startDate, int years, int months, string expectedDate)
        {
            Assert.Equal(DateTime.Parse(expectedDate), DateTime.Parse(startDate).AddYears(years).AddMonths(months));
        }

### Regression?
Did not tested with previous builds

### Other information
Current Fix:
Manually solved by adding one extra day if Start Date is a leap day.

**Comment by dadimsh** [comment]
area-System.Runtime

**Comment by KalleOlaviNiemitalo** [comment]
In `DateTime.Parse("2020-02-29").AddYears(1).AddMonths(6)`, AddYears first returns 2021-02-28 (because there is no 2021-02-29 in the calendar) and then AddMonths adds 6 months to that, giving 2021-08-28.

Hypothetically, AddYears could be changed to return a special DateTime that looks like 2021-02-28 but knows that it should have been 2021-02-29; then AddMonths would recognise that and return 2021-08-29. This extra information would be a little similar to how DateTime.Kind has three possible values in the public API but uses four states internally. However, such a change seems likely to cause compatibility problems.

Can you use AddMonths(years * 12 + months) instead of calling AddYears and AddMonths separately?

**Comment by dadimsh** [comment]
Yes, I would use your suggested method. Thanks
