### ISSUE TITLE
[iOS] X509KeyStorageFlags in X509Certificate constructor are ignored

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#52434]
The implementation of PKCS#12 certificate loading ignores the flags passed to the constructor. It always imports the key as ephemeral even if asked to persist it which is easy to fix.

The exportable flag is also ignored. It has to be investigated how it should map on iOS. It may control storing keys in the secure enclave. The keychain is per-application storage which greatly reduces the security risk of non-exportable keys actually being exportable.

**Comment by mdh1418** [comment]
I might be missing something, but is this resolved by https://github.com/dotnet/runtime/pull/55425?
It seems like the `X509KeyStorageFlags keyStorageFlags` are being used now?
https://github.com/dotnet/runtime/blob/6874ef21eae2aabe2f3dd0e7852390e20e0ce1f7/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.iOS/StorePal.cs#L40
https://github.com/dotnet/runtime/blob/6874ef21eae2aabe2f3dd0e7852390e20e0ce1f7/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.iOS/StorePal.cs#L56

I'm not very familiar, what is the exportable flag?

**Comment by bartonjs** [comment]
* The Exportable flag means that the private keys, once imported, can be exported again (e.g. `cert.GetRSAPrivateKey().ExportRSAPrivateKey()`).
* The PersistKeySet flag means that the intention is to add the certificate to a certificate store, so the private key should be written to a place that it can be used again later.
  * For macOS if PersistKeySet is used we import the cert+key into the default keychain, otherwise we use a temporary keychain.
* The EphemeralKeySet flag means the private key shouldn't ever be written to disk.
  * This isn't supported on macOS because there's no way (at least, there used to not be) to get a SecIdentityRef without putting the key and cert into a keychain, which means the key was written to disk.

On iOS we need to do the appropriate equivalent things.  EphemeralKeySet works on iOS, but PersistKeySet and Exportable might need specific support.

macOS version:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/AppleCertificatePal.ImportExport.cs#L45-L53
