### ISSUE TITLE
Tasks issues on Mac Catalyst

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#52460]
### Description

```
* thread #11, name = 'com.apple.NSEventThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2ee00)
    frame #0: 0x00007fff20243ed1 libsystem_malloc.dylib`tiny_malloc_from_free_list + 162
libsystem_malloc.dylib`tiny_malloc_from_free_list:
->  0x7fff20243ed1 <+162>: movq   %rax, (%r9)
    0x7fff20243ed4 <+165>: jmp    0x7fff20243f9d            ; <+366>
    0x7fff20243ed9 <+170>: movq   0x828(%r15), %rax
    0x7fff20243ee0 <+177>: shrq   %cl, %rax
Target 0: (System.Threading.Tasks.Tests) stopped.
```

Approx the same failure with System.Threading.Tasks.Dataflow.Tests

### Configuration

`./build.sh -ci -arch x64 -os MacCatalyst -s libs.tests -c Release /p:ArchiveTests=true /p:MonoForceInterpreter=true  /p:CrossBuild=false`

### Regression?

No

### Other information

Related PR: https://github.com/dotnet/runtime/pull/51139

**Comment by lambdageek** [comment]
Fails in various ways, but the upshot seems to be that a LowLevelLifoSemaphore (probably `s_semaphore` in PortableThreadPool.WorkerThread is not initialized when methods are called on it.

Sometimes we get a null `sem_ptr` in
```
gint32
ves_icall_System_Threading_LowLevelLifoSemaphore_TimedWaitInternal (gpointer sem_ptr, gint32 timeout_ms)
```

Sometimes instead the TimedWait throws a NRE, or sometimes there's an access violation.

It seems like `PortableThreadPool.WorkerThread.WorkerThreadStart` sees a null `s_semaphore` sometimes.  Not clear how that can happen - or why it only happens on catalyst.

**Comment by lambdageek** [comment]
This is failing because there are two tests disabled with `[ActiveIssue("...", typeof(PlatformDetection), nameof(PlatformDetection.IsMonoInterpreter))]`

https://github.com/dotnet/runtime/blob/2e08554621bcd8415bccd581e7be06b48c7813d8/src/libraries/System.Threading.Tasks.Dataflow/tests/Dataflow/DataflowBlockExtensionTests.cs#L1125

and

https://github.com/dotnet/runtime/blob/2e08554621bcd8415bccd581e7be06b48c7813d8/src/libraries/System.Threading.Tasks.Dataflow/tests/Dataflow/DataflowBlockExtensionTests.cs#L1927

The problem is that `GetIsRunningOnMonoInterpreter` is wrong on mobile (including catalyst) - we don't set the `MONO_ENV_OPTIONS` variable to turn on the interpreter, we use the embedding API.

https://github.com/dotnet/runtime/blob/2e08554621bcd8415bccd581e7be06b48c7813d8/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L467-L477

So the fix is to do correct interpreter detection.
