### ISSUE TITLE
Cannot Assembly.LoadFrom() in net5.0-windows from the .exe 

### ISSUE THREAD

**Issue by jbennink** [dotnet/runtime#52477]
As part of program startup we check several .dll and .exe files in the main executable folder and load the assembly and initialize some interface types. This worked fine in net48 but .exe files do not work in net5.0-windows and give a `System.BadImageFormatException` specifiying the `Bad IL format. The format of the file 'filename.exe' is invalid.'`

.DLL files seem to work fine. I can't find anything about this but it feels like a change not mentioned in the docs

Code inserted here and downloadlink to small sample code:
```
        // I kept some of the 'boilerplate' in this method but excluded everything after the failing line (21)
        public static void RegisterAssembly(string assemblyFilename)
        {
            string fullAssemblyFilename = "";
            if (!Path.IsPathRooted(assemblyFilename))
            {
                string directory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                fullAssemblyFilename = Path.Combine(directory, assemblyFilename);
            }
            Assembly assembly = Assembly.UnsafeLoadFrom(fullAssemblyFilename);
        }

        [STAThread]
        static void Main()
        {
            // P.S. this also fails for different .exe than the current .exe running!
            RegisterAssembly("WindowsFormsApp2.exe");

            ...
        }
```

Sample code: [here](https://calway-my.sharepoint.com/:u:/g/personal/j_bennink_calway_nl/Ec12rWbF3uZCk0A-edMS2LYBiT68hSwyolXTRtnU_fpARg?e=Xe4Wif)

**Comment by jeffschwMSFT** [comment]
I think what you are looking for is https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getcallingassembly?view=net-5.0.  This will return the assembly of the code that you are executing.  That way you do not need to Load it as it is already loaded.

**Comment by vitek-karas** [comment]
In your sample above you pass the `App.exe` as the assembly name to load. In .NET Core, the `.exe` is a native binary which is just a small shim to start the runtime. It's not a managed assembly (there should be `app.dll` next to it, which is the managed assembly). That's very likely the reason it fails, there's no manage assembly content to load from that file.

Note: In .NET Framework the main assembly for an app was compiled into an `.exe`, and the Windows OS had a piece of special code in it which recognized .NET `.exe` and started the .NET Framework. Otherwise it was basically a normal assembly (and that's why it was possible to load it as one). In .NET Core there's no OS component, so we need a native executable to start the .NET runtime - which is what the `.exe` does. Typically it has `app.dll` next to it, which is the main assembly for the app.

**Comment by jespergustinmsft** [comment]
@vitek-karas and @jeffschwMSFT - at least my comment was regarding single-file publish apps (where there is no App.dll next to the App.exe) that can be used to LoadFrom(). Do you want me to open a separate issue for this scenario?

**Comment by vitek-karas** [comment]
@jespergustinmsft There's currently no way to load assembly from a single-file "from the outside". I'm curious, what is the scenario where this is needed? I know about tools like ILSpy - but for those it's typically enough to document the file format - so for example specifically ILSpy can open single-file bundles already.

**Comment by jespergustinmsft** [comment]
Our specific scenario is that in our product we deliver an Uninstall.exe (which is a single-file published .NET 5 app, that share almost all its code with the installer exe), which holds a hardcoded, implicitly signed list of files that were (or can be) installed by the installer. So, when the user picks up an installer for a different version of the application, we go ahead and read the signed list of files from the Uninstall.exe using LoadFrom() to get that list of files.

We used to be able to work around this in .NET 3 by getting the location of the DLL somewhere in %temp%, and then call LoadFrom() on that DLL. But since .NET 5 doesn't extract the application to %temp% any longer, we seem to have no way at all to do this? Or do you see any similar workarounds or other approaches that would allow us to keep the same strategy with an implicitly signed list of installable files inside Uninstall.exe?

**Comment by vitek-karas** [comment]
Assuming this is Windows only - you could store the list as a native resource (publishing as single-file should put the native resource there if the app was built with it). You can then use Win32 APIs to read that resource. It is implicitly signed as it's part of the executable. This approach should work regardless of which publish option you use (and should work on .NET 3 as well) - the tooling should include native resources in all cases (since some of them are vital to actually make an app work - for example the windows manifest file). It's also probably much faster then `LoadFrom` approach.

**Comment by jespergustinmsft** [comment]
I failed to say that the list is a dynamic list, compiled by running a "give-me-all-the-files-you-might-install" method on each component in the installer. So this is not a static list that can be put as a resource like you suggest (I think?).

**Comment by vitek-karas** [comment]
In that case I think the easiest way would be to add a new command line option to the executable in question which will make it simply print out the list. Again basically implicitly signed (nothing can modify the output of an executable if that is signed and validated).

**Comment by jespergustinmsft** [comment]
Right! Thanks! One wonders why we didn't take that obvious approach from the beginning... Anyway, that could work in our case, since it's not really sensitive information. We have currently solved it by bundling the Uninstall.dll as well, using that as our LoadFrom() target. But that approach seems simpler (and also involves less maintenance on the build side of things).

Another potential scenario I have come up with in a spare time project is an application that provides interfaces for writing extensions for the application, but instead of having a separate SDK, you can simply load all interfaces directly from the program executable itself, which would make the complete program with extension interfaces would all be packaged in one, easily movable/sharable executable. I'm sure there are many more scenarios for this.

**Comment by packdat** [comment]
> 
> 
> @jespergustinmsft There's currently no way to load assembly from a single-file "from the outside". I'm curious, what is the scenario where this is needed? I know about tools like ILSpy - but for those it's typically enough to document the file format - so for example specifically ILSpy can open single-file bundles already.

I have a tool whose sole purpose is to load assemblies for reflection, collect all the internal references and generate a database  for another tool that visualizes the type-relationships. (https://github.com/packdat/SourcetrailDotnetIndexer)
Reading the discussion it seems I'm out of options when it comes to single-file assemblies.
Can i safely assume this is not going to change in the foreseeable future ?
Or are there any plans to provide an api for extracting the contents of a single-file assembly ?
Then at least i should mention this in my readme, stating it will not work with single-file assemblies.

**Comment by vitek-karas** [comment]
@VSadov Are we still considering adding an "Extractor"?

**Comment by svick** [comment]
@packdat One approach that I think should work would be to use [the ILSpy engine](https://www.nuget.org/packages/ICSharpCode.Decompiler/) as a library, and then copy [the code to use it from ILSpy itself](https://github.com/icsharpcode/ILSpy/blob/3c6961a/ILSpy/LoadedPackage.cs#L111).

**Comment by packdat** [comment]
@svick That looks promising, thank you !

**Comment by VSadov** [comment]
@vitek-karas yes, I still plan to add some kind of extractor/unbundler. I do not know yet in what form.

**Comment by vitek-karas** [comment]
For .NET 6 we will not introduce an "extractor", but the approach suggested by @svick (using code from ILSpy) should work.
