### ISSUE TITLE
Copy/paste error in GenTree::GetRegSpillFlagByIdx for xarch hwintrinsics

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#52473]
In `GenTree::GetRegSpillFlagByIdx` the following code exists:

https://github.com/dotnet/runtime/blob/d3a72e51641c0bc935bbb3e313df33fe1d9a839a/src/coreclr/jit/gentree.h#L7646-L7654

This makes no sense, as the function is supposed to return a GTF_SPILL / GTF_SPILLED mask, but in this case it is returning a type, instead.

This code is an exact copy of code in `GenTree::GetRegTypeByIndex`, immediately above.

So what should it return in this case?

@tannergooding @echesakovMSFT @dotnet/jit-contrib

**Comment by tannergooding** [comment]
Looks like this was introduced in https://github.com/dotnet/runtime/pull/36155. CC @sandreenko 

I'd speculate it needs to just be `AsHWIntrinsic()->GetRegSpillFlagByIdx(regIndex);`, like the other paths are doing given that `GetRegSpillFlagByIdx` was a new instance method added to `GenTree` at the same.

**Comment by sandreenko** [comment]
I agree with @tannergooding analysis, looks like this error does not produce any failures because we don't set the spill flag currently, so the return value is always treated as "no spill flags" for any var_type.
Why don't we set the spill flag currently? It is because we don't expect it here:
https://github.com/dotnet/runtime/blob/28cff50994cf8246d2b0fd07fa5a617fc474786c/src/coreclr/jit/regset.cpp#L275


so looks like there are several pieces that are missed, what are the current multireg HWIntrinsics that return multireg results? I assume they have to return structs based on:
https://github.com/dotnet/runtime/blob/28cff50994cf8246d2b0fd07fa5a617fc474786c/src/coreclr/jit/gentree.h#L7408-L7412

**Comment by tannergooding** [comment]
> what are the current multireg HWIntrinsics that return multireg results?

I don't think we have any officially doing it today. https://github.com/dotnet/runtime/pull/52424 will be adding the `LoadPair` intrinsics which will do multi-reg returns.

Carol had started a prototype for this on `Bmi2.MultiplyNoFlags` on the x86 side, but I don't think it was ever completed: <https://github.com/CarolEidt/runtime/tree/Mulx2>

**Comment by echesakovMSFT** [comment]
I will take this

**Comment by BruceForstall** [comment]
This code has been fixed.
