### ISSUE TITLE
DynamicLinkLibraryPathResolver() cctor crashes when single file publishing is used

### ISSUE THREAD

**Issue by vadi2** [dotnet/runtime#52496]
### Description
I'm using a third-party library, QmlNet, which crashes when .NET 5 single file publishing is used. The culprit is the initialization of the `NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver()`.

### Configuration

.NET 5 both on Ubuntu 20.04 and Windows 10.

### Regression?
Not sure.

### Other information

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Qml.Net.Internal.Interop' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver' threw an exception.
 ---> System.ArgumentException: Path cannot be the empty string or all whitespace. (Parameter 'path')
   at System.IO.Directory.GetParent(String path)
   at NetNativeLibLoader.PathResolver.LocalPathResolver..ctor()
   at NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver..cctor()
   --- End of inner exception stack trace ---
   at NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver..ctor(Boolean searchLocalFirst)
   at Qml.Net.Internal.Interop..cctor()
   --- End of inner exception stack trace ---
   at Qml.Net.Internal.Interop.get_QQuickStyle()
   at Qml.Net.QQuickStyle.SetStyle(String style)
   at Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by vitek-karas** [comment]
This is an issue in the NativeLibraryLibLoader:
https://github.com/pauldotknopf/net-native-lib-loader/blob/344a1df38aa6ec0d827c972375c6e2d7eac3d3b9/src/NetNativeLibLoader/PathResolver/LocalPathResolver.cs#L39

The call to `GetExecutingAssembly().Location` is not compatible with single-file. Assemblies in single-file are not files on disk since .NET 5 - they're loaded directly from the executable, so there's no path to return. The API returns empty string, which will cause the code using it to fail.

In .NET 6 we have an analyzer which can be enabled by setting `EnableSingleFileAnalyzer=true` in your project. It will issue a warning when it sees code which is not compatible with single-file. Note that this only works when you're compiling the affected code from source code, so it doesn't work for NuGet packages (as those are binaries only).
