### ISSUE TITLE
Current state of Blazor WebAssembly and the Firefox Debugger

### ISSUE THREAD

**Issue by curtisy1** [dotnet/runtime#52698]
Transferring this question here based on [my question in the mono project](https://github.com/mono/mono/issues/8378) 

To save you the long read, here's the gist of it:
As far as I can tell debugging Blazor Wasm is currently only possible in Chromium based browsers because it relies on the Chrome DevTools Protocol. Having Firefox support as well would be great since there's many people using it as a daily development driver.

Taking that into consideration I have a few questions on the current state and future plans of the Wasm debugger and its support for different browsers:

1. Is using the Firefox debugger currently supported and I'm just missing some configuration steps to make it work?
2. Are there any future plans to add such support if it doesn't exist already?
3. Firefox Nightly apparently [supports a limited subset of CDP](https://firefox-source-docs.mozilla.org/remote/index.html). If support is not planned, maybe the existing configuration could at least be tweaked to support one flavor of Firefox?
4. If support is not planned because of the big workload another debugger implementation would cause, are community contributions still welcome to add support for it or can I and potentially others save myself the work on this? There used to be a PR about this topic already, [for reference](https://github.com/mono/mono/pull/15951)

**Comment by lewing** [comment]
Hi @curtisy1 thanks for moving the discussion here.  

1. Firefox debugging isn't currently supported, @thaystg did a prototype in mono/mono that we eventually closed because we had to prioritize the supported scenarios.  The CDP based proxy works with Visual Studio, Visual Studio Code, and the built in inspector in Chrome and Edge across multiple platforms so there is a lot to test.
2. Nothing concrete at the moment.
3. I'm not very familiar with RDP or the subset of CDP that firefox supports but I think @thaystg is familiar with some of the details.  There are also some changes underway in how the runtime interacts with the remote proxy that would make it much simpler to use with other protocols.
4. Community contributions are absolutely welcome. The main concern I'd with landing the changes here would be around testing and maintainability but those are likely solvable.

**Comment by sshquack** [comment]
Thanks @lewing I just wanted to pitch-in my feedback on this:

1. Firefox been my primary browser for a long time. My current stack uses react ([firefox ext](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)), and redux ([firefox ext](https://addons.mozilla.org/en-US/firefox/addon/reduxdevtools/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)) - both of which have great debugging capabilities with the [firefox js debugger](https://developer.mozilla.org/en-US/docs/Tools/Debugger).
2. Currently debugging in Chrome or Edge with anything more than one session (example: three concurrent users adding an item to shopping cart) gets messy fast. This requires creating completely different profiles or having incognito or multiple browsers. This is by [design of chromium to share the cookies](https://superuser.com/questions/920199/chrome-open-separate-browser-windows-each-in-incognito-mode-that-do-not-shar). Firefox makes this a breeze with [multi-account containers](https://support.mozilla.org/en-US/kb/containers) since my apps have complex concurrent interactions.

As someone learning blazor, it would significantly improve my developer experience to have good blazor WASM debugging capabilities for firefox without having to juggle multiple browsers. Please consider adding support for Firefox in the future.

**Comment by lewing** [comment]
Some progress https://github.com/dotnet/runtime/pull/61776

**Comment by Turnerj** [comment]
Hey @lewing - the linked PR is now closed and locked (automatically) due to inactivity. Is it as simple as there isn't enough time/resources/priority to continue that right now or was something specific with the changes/direction/design of the work?
