### ISSUE TITLE
WindowsCryptographicException trying to read certificate from file

### ISSUE THREAD

**Issue by ligadata-dima** [dotnet/runtime#52754]
### Description

I'm getting exception while trying to read certificate from file (or from memory). 
I'm running example from [documentation](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-from-file)
```
var bytes = File.ReadAllBytes("~/<relative-path-to-cert-file>");
var cert = new X509Certificate2(bytes);
```
and getting 
```
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException
  HResult=0x80092009
  Message = Object Not Found
  source = System.Security.Cryptography.X509Certificates
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
...
```

### Configuration

This is DotNet Core app 5.0, windows 10, Visual studio. 

I also must to run it on Linux therefore I really need to know to load certificates from file .

### What did I try  to do

- I tried to run Visual Studio As Administrator. No luck.
- tried to Setting up X509Store as explained [here ](https://github.com/dotnet/runtime/issues/23437#issuecomment-409505650). Same error.
- tried to copy files to C:\appservice\certificates\public as [explained here](https://stackoverflow.com/questions/43955181/internal-cryptography-cryptothrowhelper-windowscryptographicexception)  - same error 
- tried to pass property `X509KeyStorageFlags.MachineKeySet` to X509Certificate2 constructor
```
            var bytes = File.ReadAllBytes(filename);
            string s = null;
            var cert = new X509Certificate2(bytes, s, X509KeyStorageFlags.MachineKeySet );
```
same error
- Several links seems to suggest to add  X509KeyStorageFlags.MachineKeySet , for example, [here](https://www.davidyardy.com/blog/windowscryptographicexception-the-system-cannot-find-the-file-specified) I tried:
```
 var cert = new X509Certificate2(filename, password, X509KeyStorageFlags.MachineKeySet);
```
and - same error, again

- I even tried to pass `EphemeralKeySet`  -- no luck
```
            var bytes = File.ReadAllBytes(filename);
            string s = null;
            var cert = new X509Certificate2(bytes, s, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.EphemeralKeySet);
```
same error
- issue with this error [closed without resolution ](https://github.com/dotnet/runtime/issues/23437) - why is it closed, what is resolution? 

Please help.

**Comment by vcsjones** [comment]
> C:\appservice\certificates\

Are you experiencing this issue while trying to run your application in Azure App Service, or locally on Windows 10?

If you are running in to this locally, without Azure being involved, sharing a **test** PFX that reproduces the behavior would help to reproduce the issue. If you chose to share a PFX that reproduces the issue that would be very helpful, but only if you can make a new PFX that you do not mind sharing the private key and password with us.

> issue with this error closed without resolution - why is it closed, what is resolution?

That issue looks a little weird I suspect because it was migrated from the corefx repository. However the conclusion for that issue was to use `EphemeralKeySet`. 

The issues may not be related. A `WindowsCryptographicException` will be thrown for nearly any problem that occurs while reading a PFX and can be thrown for different reasons.

**Comment by bartonjs** [comment]
Since there hasn't been any followup, there's not much action we can take.  Closing the issue.
