### ISSUE TITLE
Wrong line info when debugging CoreLib in windbg 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#52774]
- Build this program:
```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

public class MyAttribute
{
}

class Program
{
    static void Main(string[] args)
    {
        var ab = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("MyAssembly"), AssemblyBuilderAccess.Run);
        var mb = ab.DefineDynamicModule("MyModule");
        var tb = mb.DefineType("MyType");
        tb.SetCustomAttribute(typeof(MyAttribute).GetConstructor(new Type[0]), new byte[0]);
        var t = tb.CreateType();
        for (;;) t.GetCustomAttributes();
    }
}
```
Run the program on checked CoreCLR build under windbg, e.g. `windbg.exe corerun test.exe`
- Break in, try to step through some of the more complex methods that are called in CoreLib

Actual behavior: The line information is wrong for more complex methods. The debugger tends to show the lines at the end of the method instead of the correct line.
Expected behavior: The line information is mostly correct

For example, here is a screen shot showing debugger stopped at GetMetadataImport near the beginning of `AddCustomAttributes` method, but source view showing the exception handler at the end of the method.

![image](https://user-images.githubusercontent.com/6668460/118302686-5ee51700-b499-11eb-9b34-cbd6a5102920.png)

**Comment by tommcdon** [comment]
@hoyosjs   possibly a bug in windbg, or in optimized method sequence points?

**Comment by noahfalk** [comment]
This appears to be a bug in the DAC when working with code that has multiple jitted versions, such as what is generated by Tiered Compilation. The problematic code is [here](https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/daccess/daccess.cpp#L6129-L6130):

```C++
    TADDR  nativeCodeStartAddr = PCODEToPINSTR(methodDesc->GetNativeCode());
    request.InitFromStartingAddr(methodDesc, nativeCodeStartAddr);
```

The DAC code incorrectly assumes that it should always fetch the native->IL offset map for the default version of the code (that is the address returned by methodDesc->GetNativeCode()). It also incorrectly assumes that the default code version address is the appropriate reference to later use when calculating the code offset. For one particular example from RuntimeType.IsSubclassOf we can see the different code addresses:

```
0:000> !ip2md 00007ff9`a2a16553
MethodDesc:   00007ff9a29ee130
Method Name:          System.RuntimeType.IsSubclassOf(System.Type)
Class:                00007ff9a2a7c4b0
MethodTable:          00007ff9a29ef7b8
mdToken:              00000000060006A4
Module:               00007ff9a28d4000
IsJitted:             yes
Current CodeAddr:     00007ff9a2a16520
Version History:
  ILCodeVersion:      0000000000000000
  ReJIT ID:           0
  IL Addr:            00007ff9e155ef90
     CodeAddr:           00007ff9a2a16520  (OptimizedTier1)
     NativeCodeVersion:  0000025C1E47FCB0
     CodeAddr:           00007ff9e117f360  (ReadyToRun)
     NativeCodeVersion:  0000000000000000
```

Instead of computing the correct method offset `0x00007ff9a2a16553 - 0x00007ff9a2a16520 = 0x33`, the DAC computes `0x00007ff9a2a16553 - 0x00007ff9e117f360 = 0x000000c0ec37cae8`. This huge offset causes the logic that selects the native->IL offset map entry to determine the code is in the epilog and return a sentinel IL offset value of 0xFFFF_FFFD which then leads windbg to map the wrong source line.

We likely haven't seen wider problems but the buggy codepath is in our legacy DAC APIs. Windbg still uses these APIs but Visual Studio moved to ICorDebug long ago which goes down a different code path.

**Comment by mikem8361** [comment]
@noahfalk what method desc function returns the current code addr instead the default?
