### ISSUE TITLE
ComWrappers requiring Apartments Support

### ISSUE THREAD

**Issue by b-iotti** [dotnet/runtime#52834]
Hello, we're trying to separate the ComWrapper and ComInterop features so that we can work on the former independently as part of our Linux porting effort. We're running into issues such as FEATURE_COMWRAPPERS requiring FEATURE_COMINTEROP_APARTMENTS_SUPPORT. Currently, we're working off of the PR that was provided by @AaronRobinsonMSFT and his team (https://github.com/dotnet/runtime/pull/52146) since it extracts the COMWRAPPERS feature flag. Can we have ComWrappers enabled without other interop features, or are some required? If so, which ones should always be present?

**Comment by jkotas** [comment]
>  Can we have ComWrappers enabled without other interop features

Yes. In particular, `FEATURE_COMINTEROP_APARTMENTS_SUPPORT` should not be required for `FEATURE_COMWRAPPERS `. If it is not the case, it is a bug that should be fixed.

**Comment by AaronRobinsonMSFT** [comment]
@b-iotti The `FEATURE_COMWRAPPERS` should be considered entirely independent from any other `FEATURE_*` as far as I recall. If it isn't, as @jkotas mentions, this should be initially considered a bug. It is possible there are some interactions I am missing but the design is expected to be independent of any other feature.

If you find it necessary to detangle  features due to inadvertent build expectations I would strongly suggest putting out smaller PRs that are independent of the larger cross-platform `ComWrappers` support.

**Comment by b-iotti** [comment]
After some more investigation, it seems that ComWrappers does indeed leverage some interop features, since through `GetIUnknownImplInternal `you recall `ecallist.h`, and this references `introplibinterface.cpp`. Finally, `interoplibinterface.cpp` includes `olecontexthelpers.h`, which then quips that you need Apartments enabled.

**Comment by jkotas** [comment]
Place `#include "olecontexthelpers.h"` under ifdef to fix this.

```
#ifdef FEATURE_COMINTEROP_APARTMENT_SUPPORT
#include "olecontexthelpers.h"
#endif
```

**Comment by b-iotti** [comment]
Now we're having issues with the CoreShim.h including combaseapi.h. This file is in src/hosts/coreshim/CoreShim.h. Since the combaseapi.h is part of the Windows 10 SDK, how should we proceed?

**Comment by b-iotti** [comment]
If we remove combaseapi.h and include instead:
```
#define PAL_STDCPP_COMPAT
#include "pal_mstypes.h"
#include "pal.h"
#include "palrt.h"
#include "unknwn.h"
#include "coreclrhost.h"
```
we get: 
```
/src/coreclr/hosts/coreshim/ComActivation.cpp:62:44: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char16_t [29]'
RETURN_IF_FAILED(Utility::TryGetEnvVar(COMACT_ASSEMBLYNAME_ENVVAR, assemblyName));
```

**Comment by AaronRobinsonMSFT** [comment]
@b-iotti The `CoreShim.h` file is for the `FEATURE_COMINTEROP` testing environment and not for `FEATURE_COMWRAPPERS`. There is going to be a bit more confusion in the testing tree than the product because these `FEATURE_*` defines haven't historically been used. The only tests needed for this work are under `src/tests/Interop/COM/ComWrappers`. The rest of the  `src/tests/Interop/COM` directory can be ignored.

**Comment by b-iotti** [comment]
I'm missing something here. This file is in `src/coreclr/hosts/coreshim`, not in the tests directories. Are we doing something wrong in our build command? We're using `./build.sh -subset clr -c Debug` and have only enabled `FEATURE_COMWRAPPERS`.

**Comment by AaronRobinsonMSFT** [comment]
@b-iotti Ah. This is my bad. The `CoreShim` project is similar to `CoreRun` in that it helps testing and light weight investigation. The `CoreShim` was written to test scenarios where the entry point was not an EXE per se but rather some implicit load. In this case the only current use of `CoreShim` is for enabling author a .NET COM Server. This means that most of it's implementation can be behind the `FEATURE_COMINTEROP`.

**Comment by AaronRobinsonMSFT** [comment]
This has been answered.
