### ISSUE TITLE
Add basic collection interfaces to the PriorityQueue<,>

### ISSUE THREAD

**Issue by vhil** [dotnet/runtime#52944]
## Background and Motivation

The ```System.Collections.Generic.PriorityQueue``` is something that I have been waiting for a long time.
However would it be logical to add an imlementation for IEnumerable<TElement> and IReadOnlyCollection<TElement>?

## Proposed API

```diff
-    public class PriorityQueue<TElement, TPriority>
+   public class PriorityQueue<TElement, TPriority> : IEnumerable<TElement>, IReadOnlyCollection<TElement>
```

## Risks

Just need to make sure the enumeration performs in O(1) time complexity and does not lead to re-heapifying.

**Comment by eiriktsarpalis** [comment]
The PriorityQueue type is intentionally not implementing IEnumerable<T>, since many users might have the expectation that enumeration happens by ascending priority. However, this is not possible without incurring _O(n * log(n))_ time and _O(n)_ space complexity. 

You can use the [`PriorityQueue.UnorderedItems`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs#L193) property which as the name suggests returns the items without any ordering guarantees.
