### ISSUE TITLE
System.Diagnostics.Eventlog package has a dependency on System.Security.Principal.windows for netfx

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#52982]
We dont need the  System.Security.Principal.windows  dependency for System.Diagnostics.Eventlog for netfx.  We specifically exclude the dependency https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj#L124

But its present in the package.

cc @ViktorHofer @ericstj

**Comment by ericstj** [comment]
Question for you: if someone compiled a .NETStandard library and only referenced `System.Diagnostics.Eventlog` package would their NETStandard library be able to use types present in `System.Security.Principal.Windows` and thus have a binary with an assembly ref to this assembly?  If so, then it must be provided by the `System.Diagnostics.Eventlog` package since exposing this assembly is part of the public contract of the package.

**Comment by ericstj** [comment]
Here's a sample that demonstrates what would happen if you didn't have that dependency on System.Security.Principal.Windows:
https://github.com/ericstj/sample-code/commit/49ed934e8b3bfb47a5a342f8fd8a2c727689933d

If you run this, you'll see the following exception
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at lib.EventLogHelper.<GetEventUsers>d__0.MoveNext()
   at app.Program.Main(String[] args) in C:\scratch\eventLogSample\app\Program.cs:line 10
```
This is because `System.Security.Principal.Windows` is required since it's exposed to the `netstandard2.0` assembly.

**Comment by ericstj** [comment]
So in other words, we do require this depdency and pkgproj ensures it is present.  We need to make sure that remains true after switching to CSProj.  This is one of those things that we can catch with package-validation if it considers dependencies.

**Comment by Anipik** [comment]
understood, our current pack task infra is missing this. i will make sure to fix this.

**Comment by ericstj** [comment]
@Anipik did you want to keep this issue tracking anything or was the original question answered?

**Comment by Anipik** [comment]
yes i think the question is answered, i will close this one.

**Comment by ericstj** [comment]
And just to add a bit more info here.  PKGProj determines dependencies by analyzing assemblies.  It looks at ref and src assemblies and creates package dependencies for both.  It removes package dependencies for any assemblies which are inbox and don't need a dependency.  It also makes sure to copy any package-references to compatible frameworks, even if those packages aren't used on that framework, since a project might depend on that package delivering the dependency.

**Comment by chucklu** [comment]
@Anipik  Please try my forked sample repository, https://github.com/ChuckFork/sample-code/tree/eventLogNetFxSample. You are right, the irrelevant dependency should not be referenced.

@ericstj  Your sample repository just give a wrong case, I suggest you to read [Using .NET Standard with Full Framework .NET](https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET) to know how to publish a package correctly.
When we are developing a project base .net framework 4.8, then we are supposed to use a lib which also target the .net framework 4.8,  and that's why we do not need the dependency of System.Security.Principal.Windows as we already have it in .net 4.8.
For NuGet, you will find most packages are now multi framework targeted to solve the problem mentioned in that article.

**Comment by chucklu** [comment]
> 
> 
> understood, our current pack task infra is missing this. i will make sure to fix this.

@Anipik It seems you also need to read [Using .NET Standard with Full Framework .NET](https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET) to know how to publish a package correctly. When you pack a package and release it to NuGet, make sure you make it support multi target frameworks as mentioned in article.

**Comment by ericstj** [comment]
> @ericstj Your sample repository just give a wrong case

What's wrong about it?  We can't tell every customer not to use .NETStandard.

The package must be self consistent.  If it exposes an assembly with type definitions on one framework it must expose that an assembly with compatible name on all compatible frameworks.  We cannot require every package up the stack to cross-target for all the frameworks of its dependencies, if we did it defeats the purpose of TargetFramework compatibility.

A more obvious case of this might be the following.  Suppose I have a package that targets `net4.5` and `net4.6`.  Say on `net4.5` I decide to use `Newtosoft.Json` and on `net4.6` I decide not to.  Does that mean I can omit my dependency on `Newtonsoft.Json` in the `net4.6` dependency group?  No, that would cause FileNotFoundExceptions if someone built a package compiling against `net4.5`, running on `net4.6` and expecting my package to bring the dependency.

A package's dependencies are part of its public API contract.

All that said, in this specific case, If you target .NETFramework you can omit your dependency on `System.Diagnostics.Eventlog`. This package's purpose is to enable folks to compile against these types on `.NETStandard` (or `.NETCore`) and use them on `.NETFramework` and `.NETCore`.  For folks who are only concerned with `.NETFramework` they don't need to reference this package at all, they can just include an assembly reference to `System`.

**Comment by chucklu** [comment]
@ericstj  There is no problem with the .net  standard 2.0 of System.Diagnostics.EventLog, we are talking about the .net framework of System.Diagnostics.EventLog.
That's why I said you are demonstrating a wrong case.

Anyway, the original question is "We dont need the System.Security.Principal.windows dependency for System.Diagnostics.Eventlog for netfx. " So we should focus on the dependency of .net framework instead of .net standard.

https://www.nuget.org/packages/System.Diagnostics.EventLog/5.0.1
**We should discuss the dependency of the second section,** but you are talking about the third section.  The third section is fine, and the second section(dependency of .net framework) is absolutely wrong.
![image](https://user-images.githubusercontent.com/3004057/119754744-74176800-bed3-11eb-9eda-48d532aebf7e.png)

**Comment by ericstj** [comment]
You can’t talk about .NETFramework in isolation. Since it is compatible with .NETStandard this package must also ensure its .NETFramework behavior is compatible wit .NETStandard.

I can understand why you think the dependency might not be necessary since the .NETFramework assembly itself does not have an assembly reference to System.Security.Principal.Windows.  The dependency is needed to support the case when libraries build against .NETStandard but run in a .NETFramework application. In this case dependencies will be resolved using the .NETFramework dependency group, but will need to satisfy all references exposed when the package was consumed in the .NETStandard project.

**Comment by chucklu** [comment]
@ericstj  Actually we have two folders under C:\Users\username\.nuget\packages\system.diagnostics.eventlog\5.0.1\lib
net461 and netstandard2.0, and there is a System.Diagnostics.EventLog.dll file under them.

 The dependency of net461 is 

> // mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> // System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> // System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

The dependency of netstandard2.0 is

> // netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> // System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

We are talking about the net461 library instead of netstandard2.0 library.
You said the netstandard2.0 library depends on System.Security.Principal.Windows, it's fine, no problem.
But the net461 library would not depend on System.Security.Principal.Windows, do you agree?

**Comment by chucklu** [comment]
The dependency is needed to support the case when libraries build against .NETStandard but run in a .NETFramework application. 

> In this case dependencies will be resolved using the .NETFramework dependency group

I can not agree with this, why the dependencies will be resolved using  the .NETFramework dependency group? As you are using the .net standard library, **the dependencies should be resolved by .net standard dependency group.**
In this case you mentioned, I expect to resolve the dependency with the third one, not the second one. The third one have a dependency of System.Security.Principal.Windows.
![image](https://user-images.githubusercontent.com/3004057/119754744-74176800-bed3-11eb-9eda-48d532aebf7e.png)

And this case is fine, resolved the dependency with the .net standard library, but it's not best practice.
You will get the additional System.Security.Principal.Windows under your .net framework app, which is useless(because we already have it in .net framework).
And to solve this problem, we need to have multi target packages. That's the reason why the article exists 
[Using .NET Standard with Full Framework .NET](https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET)

**Comment by ericstj** [comment]
> I can not agree with this, why the dependencies will be resolved using the .NETFramework dependency group? As you are using the .net standard library, the dependencies should be resolved by .net standard dependency group.

Not if the application is .NETFramework (app.csproj in my sample).  Packages are resolved in the context of the project they are restored for, not the library they are referenced by.  This is how multi-targeted packages are able to provide the best asset for the application in which they run.  In fact this package and others like it rely on this behavior because the replace a .NETStandard assembly that contains type defs with a .NETFramework implementation that has type forwards.

> And this case is fine, resolved the dependency with the .net standard library, but it's not best practice.

Consuming .NETStandard libraries on .NETFramework is very much supported and can't fail with exceptions at runtime.   In fact, the only reason to even use this package on .NETFramework is to consume .NETStandard libraries which used types exposed by this package.

> You will get the additional System.Security.Principal.Windows under your .net framework app, which is useless

It's no more useless than the System.Dianostics.EventLog.dll.  Both serve the exact same purpose: to let people build .NETStandard libraries that use these types, but then forward to their location in .NETFramework.  I agree that both assemblies are equally useless on .NETFramework: you shouldn't use this package at all if you are building a .NETFramework application, just reference System.dll etc.

> (because we already have it in .net framework).

Neither assembly exists in .NETFramework.  These are new assemblies which we added in .NETCore.  The types exist in .NETFramework but we need the packages to provide assemblies which type-forward to their location in .NETFramework.  This lets us expose common API that is available in both .NETCore and .NETFramework but not part of netstandard.dll itself.

**Comment by chucklu** [comment]
> Packages are resolved in the context of the project they are restored for, not the library they are referenced by.

app references lib, a .net framework proejct references .net standard project
and lib references System.Diagnostics.EventLog, a .net standard project references a .net standard library

Since the app does not reference System.Diagnostics.EventLog directly, I suppose the .net standard library will still resolved by the lib project, which is a .net standard project. Doesn't it mean resolve the dependencies by  the .net standard dependency group?

**Comment by ericstj** [comment]
> Since the app does not reference System.Diagnostics.EventLog directly, I suppose the .net standard library will still resolved by the lib project
> Doesn't it mean resolve the dependencies by the .net standard dependency group?

The .NETStandard library (and dependencies) will be resolved by the lib, the .NETFramework library (and dependencies) will be resolved app, even though it doesn't directly reference System.Diagnostics.EventLog.  Dependencies are transitive and resolved in the context of every project for that projects TFM.  NuGet flows dependencies across ProjectReferences (unless they are marked with `PrivateAssets`).

**Comment by chucklu** [comment]
Hi @ericstj ,  Is there any official documentation from Microsoft about the knowledge  you mentioned?

**Comment by chucklu** [comment]
@ericstj  I am trying another test, but get confused.
Please check this https://github.com/ChuckFork/sample-code/commit/c7b19295c6839c14936eb663a38b1c3308b6c6a4
I add a new .net framework project, and reference the lib project(.net standard). After I build the solution, I got something weird.
The app4\bin\Debug folder contains System.Security.Principal.Windows.dll, but lost System.Diagnostics.EventLog. 
How could this be possible? Is it a bug of visual studio? or I make something wrong?

**Comment by ericstj** [comment]
>  Is there any official documentation from Microsoft about the knowledge you mentioned?

Here are a few resources.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

> The app4\bin\Debug folder contains System.Security.Principal.Windows.dll, but lost System.Diagnostics.EventLog

I actually can't reproduce System.Security.Principal.Windows.dll being in the output from your sample if I build from clean.  I see no package libraries at all.  If I had to guess it may be left from a previous build, if you delete it and build again it may go away.  If you repro consistently share a [build log](https://www.msbuildlog.com/#usingbl).

System.Diagnostics.EventLog being missing in this case is due to you using `packages.config` restore mode in your csproj.  This is the default for legacy CSProjs and the behavior of NuGet since you didn't include any `PackageReference`s in your project .  In this mode nuget doesn't flow transitive package references.  You can enable PackageReference and the transitive flow of dependencies with https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#using-packagereference-for-a-project-with-no-packagereferences.
If you don't enable PackageReference then you need to manually install packages in every project in your project graph.  This was a shortcoming of `packages.config` and one of the motivators behind why NuGet v3 added the PackageReference mechanism for dependencies.  When using `Packages.config` the dependencies of a project are "guessed" by ResolveAssemblyReferences looking next to a project's assembly.  Sometimes it can get it right, but more often it can't.  It has no way of handling conflicts (two different versions) or re-evaluating the best TargetFramework for the referencing project.  Installing the packages up the ProjectReference stack avoids this guessing, but the reccomended approach is to switch to PackageReference.

**Comment by chucklu** [comment]
Hi @ericstj ,
       Could you take a look at these two similar  issues? 
      https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1573 and https://github.com/dotnet/SqlClient/issues/1137.
      Currently based on my experience, we should list all top level dependences on NuNet package page, such as https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0. However this package only list Azure.Identity as required dependency. I suppose  the  Azure.Core also be listed as a required dependency, as the Microsoft.Data.SqlClient reference it directly.

> .NETFramework 4.6.1
> 
>     Azure.Identity (>= 1.3.0) 


  
 I just wonder what's the correct way to list the dependencies. To make it simple, imagine that we have a libA which references packageB and packageC. And packageB require PackageC. 
       I think the libA should list both packageB and packageC as dependencies, but from the above mentioned Microsoft.Data.SqlClient package, it only list packageB. Which one is the correct one?

**Comment by ericstj** [comment]
> Currently based on my experience, we should list all top level dependences on NuNet package page

Both are *correct*, but listing all packages that are directly referenced by an assembly is slightly better in the sense that it insulates a package from breaking changes in a dependent package.  I would *recommend* that packages try to list every package that they directly depend on so that they can ensure that the package will be present, even if a new version of a dependency decides to drop the package.  We were discussing codifying this type of rule in https://github.com/dotnet/sdk/tree/main/src/Compatibility/Microsoft.DotNet.PackageValidation.  cc @Anipik @safern

**Comment by chucklu** [comment]
@ericstj  Thanks, it's clear now.
