### ISSUE TITLE
Consider removing `CROSSGEN_COMPILE` define and the CrossGen binary

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#53007]
Now that CrossGen2 has replaced CrossGen, we should consider removing code guarded by the following defines:

- [x] #57657
- [x] #57658
- [x] #57659
- [x] #57660
- [x] #57661
- [x] #57706 

/cc @jkotas @mangod9 @davidwrighton

**Comment by mangod9** [comment]
@dotnet/crossgen-contrib . Thanks for creating the issue, its been on our radar to first remove crossgen from building to determine what things break :)

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Yep. That was my secondary realization. My first was the amount of code we could remove but I'd also assumed we would build faster - thanks for confirming that assumption!

**Comment by agocke** [comment]
Hell yeah

**Comment by k15tfu** [comment]
@AaronRobinsonMSFT Hi! Looks like this method `AssemblyLoadContext.LoadFromNativeImagePath(string nativeImagePath, string? assemblyPath)` (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromnativeimagepath) now completely ignores `nativeImagePath` parameter and moreover now always requires a not null `assemblyPath` parameter (otherwise the runtime will crash with SIGSEGV). Is this expected behavior and the documentation should be updated, or is the method not working correctly?

Linked issue: https://github.com/dotnet/runtime/issues/57660.

**Comment by elinor-fung** [comment]
There is https://github.com/dotnet/runtime/issues/59825 about `LoadFromNativeImagePath` behaviour.
