### ISSUE TITLE
Volatile fields and implicit memory barriers within default constructors

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#53174]
In C#, volatile writes have release semantics, meaning a write to a `volatile` field introduces an implicit memory barrier (half-fence).

C# also guarantees that all fields are initialized to a default value.

Therefore, does the default initialization of a `volatile` field (such as in the default constructor of a type) also introduce an implicit memory barrier?

**Comment by Joe4evr** [comment]
I believe a constructor in the CLR always runs with a *full* fence, regardless of the existence of `volitile` fields.

**Comment by VSadov** [comment]
The reason why C# guarantees that all fields are initialized to default value is because by default GC heap locations are  zero-initialized before use. The memory contains zeroes before it becomes a particular object.

So, no. Only an actual assignment guarantees that there is a fence.

> a constructor in the CLR always runs with a full fence

That is more subtle:
- constructors in CLR do not impose any ordering semantics by themselves.
- assigning a reference to a heap location is a release (in CLR, not sure about Mono)

In order to share an instance with another thread, the reference must be assigned to some heap location and as a result constructed instance will have to go through a release fence. That is sufficient to guarantee that fields assigned in the constructor, before the instance is shared, are safe to read in a different thread. 
There is no full fence in the constructor though.

**Comment by mangod9** [comment]
@WizardBrony hoping your question has been resolved by the response above?
