### ISSUE TITLE
AssemblyLoadContext incorrectly validates name of dynamic assembly when returned from Load

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#53181]
`AssemblyLoadContext` validates that the assembly returned from `Load` has the same name as the name which was asked for. This validation incorrectly handles dynamic assemblies and will always fail for them.

This is the cause because `ValidateAssemblyNameWithSimpleName` simply casts the returned assembly to `RuntimeAssembly`:
https://github.com/dotnet/runtime/blob/01c9cf6102b525f0b787cfa3fcce72cbee2d6716/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L660

But this doesn't work for assemblies created by `AssemblyBuilder`.

The code should call `GetRuntimeAssembly` instead, which handles this case correctly.

Full repro for both affected public APIs (`Load` and `Resolving`) is here:
https://gist.github.com/vitek-karas/3c8f938dc15730ad00a375d8d745f36a

This is basically a derivative issue from the bug fix in https://github.com/dotnet/runtime/pull/49387.

**Comment by Ap0k** [comment]
@vitek-karas 
This error can be easily treated. But in the process of fixing it, I found the following case.
https://github.com/dotnet/runtime/blob/cc8d9b33005ef617379ff9841284398414505104/src/coreclr/vm/appdomain.cpp#L5416
If I understood everything correctly, then the dynamic assembly is not domain-specific and the code execution goes along the specified branch with the subsequent generation of an exception.

If fixing the definition of ALC for a dynamic assembly is not urgent, then I can investigate the above problem in more detail within the framework of this task. Otherwise, I propose to create a separate ticket for the error in the definition of ALC, merge it, merge the fixes of the tests (#48579) and then tackle the problem of this ticket tightly.

**Comment by vitek-karas** [comment]
Honestly I was expecting this - that dynamic assemblies will be prevented from actually succeeding in `Load`. I still think it's worth fixing the name validation logic, mainly because it's inconsistent and fails with really bad error.

The potential support for dynamic assemblies in load resolution is probably a much larger work item (I'm not even sure what are all the potential problems with it for example), so I would definitely track that separately. There's also the question if it's actually worth going after at all.

**Comment by Ap0k** [comment]
Okay, I fill in both fixes, but without the `ValidateAssemblyNameWithSimpleName` tests
