### ISSUE TITLE
Register IHttpClientFactory inside UnityContainer

### ISSUE THREAD

**Issue by Robert969696** [dotnet/runtime#53273]
I am trying to register IHttpClientFactory. Firslty I've implemented it into my service:

```
public class WebApiService : IWebApiService
{
   private readonly IHttpClientFactory _httpClientFactory;
   public WebApiService(IHttpClientFactory httpClientFactory) => _httpClientFactory = httpClientFactory;
}
```
Nevertheless i am not sure how should i correctly register it in DI UnityContainer. Can anyone help me out?

```
namespace MobileAppXamarinForms
{
    public partial class App : Application
    {
        var container = new UnityContainer()
                .AddExtension(new Diagnostic())
                .RegisterInstance(mapper)
                .RegisterType<IDb, Db>(new ContainerControlledLifetimeManager())
                .RegisterType<IPageService, PageService>(new ContainerControlledLifetimeManager())
    }
    ...

}
```
So far i've tried to add ServiceCollection and register it and i hoped i will help to resolve IHttpClientFactory but it doesn't work and i get error as folows:

```
namespace MobileAppXamarinForms
{
   public partial class App : Application
   {

        IServiceCollection serviceCollection = new ServiceCollection();
        serviceCollection.AddHttpClient();
        serviceCollection.BuildServiceProvider();


        var container = new UnityContainer()
                    .AddExtension(new Diagnostic())
                    .RegisterInstance(mapper)
                    .RegisterInstance(serviceCollection)    // <======
                    .RegisterType<IDb, Db>(new ContainerControlledLifetimeManager())
                    .RegisterType<IPageService, PageService>(new ContainerControlledLifetimeManager())
    }
    ...
    
}
```
When debugging error shows:

`Unity.ResolutionFailedException: 'The current type, System.Net.Http.IHttpClientFactory, is an interface and cannot be constructed. Are you missing a type mapping?`

**Comment by KevinCathcart** [comment]
Registering the service collection is not going to be useful. The service collection is just a a list of registrations that need to be translated to the containers native format. To do that you can use the Unity.Microsoft.DependencyInjection NuGet package (written and maintained by the Unity team), which provides the needed code. While most examples show it as part of either using in asp.net core, or as part of using the Microsoft.Extensions.Hosting model, it can be used directly with the container.

To use, add a using directive with the Unity.Microsoft.DependencyInjection namespace. Then on your UnityContainer there should be a BuildServiceProvider extension method that takes an IServiceCollection, where you can pass your serviceCollection to register any entries inside it. This does not return support fluent chaining, so you want to have your UnityContainer in a variable when you call this. Alternatively you could cast the return value to `Unity.Microsoft.DependencyInjection.ServiceProvider` and then cast again to UnityContainer, in order to get back to the container, but that would be silly.

@ENikS This is another example where having the chainable AddServices method be public (unitycontainer/microsoft-dependency-injection#54) would probably be simpler for the user, since they are really only interested in being able to use a provided ServiceCollection extension method instead of needing to basically copy that code and manually convert to native registrations, and then need to monitor for any changes that might make in the future (this would be especially bad since some types registered are internal to Microsoft.Extensions.Http making registering them from user code tricky and fragile, but duplicating those types would be obnoxious, and an even larger maintenance burden on the user).

**Comment by Robert969696** [comment]
@KevinCathcart Could you be so kind and show me how to do it in presented code of mine. I would appreciate.

**Comment by KevinCathcart** [comment]
@Robert969696 :
1. Add the NuGet package. Many ways to do this. such as Visual Studio's Manage NuGet Packages, or from the command line you could do: `dotnet add package  Unity.Microsoft.DependencyInjection`.
2. Add `using Unity.Microsoft.DependencyInjection` to the top of the `App` file.
3. Update code to be:
```c#
IServiceCollection serviceCollection = new ServiceCollection();
serviceCollection.AddHttpClient();

var container = new UnityContainer()
            .AddExtension(new Diagnostic())
            .RegisterInstance(mapper);
            
container.BuildServiceProvider(serviceCollection); 

 container.RegisterType<IDb, Db>(new ContainerControlledLifetimeManager())
            .RegisterType<IPageService, PageService>(new ContainerControlledLifetimeManager());
...
```

You can do the `RegisterType` calls before the the service collection, as part of the previous chain of methods, but I kept the registration order the same as you were trying to do in your original code for the sake of clarity.

I ran a simplified test version of this and this seemed to work fine for me.

**Comment by CarnaViire** [comment]
Closing as answered above

**Comment by ENikS** [comment]
This should be fixed in v6 of Unity
unitycontainer/microsoft-dependency-injection#54
