### ISSUE TITLE
LINQ performance of .Where(pred).Any() against .Any(pred)

### ISSUE THREAD

**Issue by mhartkorn** [dotnet/runtime#53274]
Visual Studio 16.10 introduces a new quick fix for replacing `.Where(pred).Any()` with `.Any(pred)` (and similar like `First`, `Last`, `Single`, etc.). This was known to have severe negative performance impacts in .NET (#19382, https://github.com/dotnet/runtime/issues/19382#issuecomment-467612364) and was declared to be out of scope to fix because LINQ "was never intended to be a high-performance set of APIs". https://github.com/dotnet/runtime/issues/19382#issuecomment-734524103

[The documentation for this quick fix claims:](https://docs.microsoft.com/en-us/visualstudio/ide/reference/simplify-linq-expression?view=vs-2019&preserve-view=true) (emphasis mine)

> Why: Removing the unnecessary call to the Enumerable for the .Where() method *improves performance* and readability.

Has the previous view on this changed and was it fixed in LINQ?

**Comment by eiriktsarpalis** [comment]
cc @stephentoub. We could update to documentation to only claim that the fixer improves readability.

**Comment by jpapp05** [comment]
This is unfortunate.  I just updated our repository, marveling how cool these analyzers are in all the performance fixes it found based on the name and description of the analyzer rules.   

Please consider fixing this performance disparity in LINQ as it is not intuitive; I had no idea it was making things slower until I stumbled on this post. 

I understand there is always a balance between size and performance, but size is never an issue for us, given that our product runs on larger multi-core servers in the financial sector.  Perhaps, there is some way to have a sperate LINQ package geared for pure performance that is interchangeable with the default one, which exposes the same public API surface. 

In any case, it would be nice to clearly indicate any rules that may hurt performance or move all positive performance fixes to a new analyzer prefix.   Maybe introduce a new rule the can reverse this in the name of execution speed?

**Comment by stephentoub** [comment]
The only case in which I'd expect `source.Where(pred).Any()` to be faster than `source.Any(pred)` is when source is a `T[]` or `List<T>`, and even there, the difference is purely due to the extra code in `Where` that indexes into these rather than using `MoveNext`/`Current`... it doesn't change the algorithmic complexity or anything like that. `source.Where(pred).Any()` may also incur an additional allocation.  Are the cases you're concerned about calling `Any(pred)` on a `T[]` or `List<T>`?

> This was known to have severe negative performance impacts in .NET

On microbenchmarks on the specific case of operating on an array or list.  I've repeatedly asked for even a single example where it measurably negatively impacted real-world code.  Do you have an example?

> Removing the unnecessary call to the Enumerable for the .Where() method improves performance and readability.

I don't know who wrote that, but yes, we should tweak the doc to remove the "improves performance and".  The change may or may not help with perf; it arguably helps with readability.

> I understand there is always a balance between size and performance

The issue isn't just size.  It's some but not a ton of code:
https://github.com/stephentoub/runtime/commit/43249c59410a15fb8e90b96ec3ec18a578510191
There is an aspect of maintainability.  There's also an aspect of such a change will actually add cost to `Any(pred)` for things that aren't `T[]` or `List<T>`, because we're now paying for two type checks that wouldn't otherwise be there.  If we expect arrays and lists to be the common case, then great, but if they're not going to be, it's a deoptimization overall.

**Comment by mhartkorn** [comment]
To clarify, I'm not asking to reevaluate the decision made in #19382. I completely understand that it's very low priority and would've commented on #19382 with a short question about it if the issue wasn't closed.

I was originally about to only open an issue for the documentation but then remembered all the efforts in regards to improving performance in .NET and thought that it maybe got fixed. The documentation should be improved, maybe it could still say it improves performance in most cases with a hint that working with `List<T>` and `T[]` might become slower with this refactoring.

> Do you have an example?

No, but I also don't think that it needs to get fixed urgently. The workaround is fine with me considering the complexity of a fix.

**Comment by eiriktsarpalis** [comment]
I believe the document has now been updated to reflect performance concerns, cf. https://docs.microsoft.com/en-us/visualstudio/ide/reference/simplify-linq-expression?view=vs-2019&preserve-view=true#remarks
