### ISSUE TITLE
[System.Diagnostics.DiagnosticSource]. Starting version 6.0.0-preview.3.21201.4, there is a behavior change when calling activitySource.StartActivity() with Invalid W3C Id for parent.   

### ISSUE THREAD

**Issue by vishweshbankwar** [dotnet/runtime#53375]
### Description

**Previous Behavior**: 

Activity is not created when starting activity by calling activitySource.StartActivity("TestActivity", ActivityKind.Client, "InvalidW3CIdParent"). This behavior is same whether Activity.ForceDefaultIdFormat is set to True or False.

**New Behavior**: 

Activity is created when starting activity by calling activitySource.StartActivity("TestActivity", ActivityKind.Client, "InvalidW3CIdParent") and setting Activity.ForceDefaultIdFormat to True.

Activity is not created when starting activity by calling activitySource.StartActivity("TestActivity", ActivityKind.Client, "InvalidW3CIdParent") and setting Activity.ForceDefaultIdFormat to False.

The following repo has sample app showing the difference in behavior. 

https://github.com/vishweshbankwar/DiagnosticSource6Preview_Activity

The `main` branch of this repo shows example code using .NET5.0 console app for the behavior noted above with version 6.0.0-preview.3.21201.4. `DiagnosticSource5_Activity` branch uses 6.0.0-preview.2.21154.6 which confirms the previous behavior (also matches with behavior from version 5.0.1).

**Comment by tarekgh** [comment]
@vishweshbankwar this is intentional fix we have done in .NET 6.0. 

If not providing `ActivityListener.SampleUsingParentId` and providing `ActivityListener.Sample` with setting `Activity.ForceDefaultIdFormat = true` that suggest creating the Activities with `W3C` Ids and the `ActivityListener.Sample` will be the callback to decide creating the Activity object. 

You have full control on the behavior. Either you can make `ActivityListener.Sample` decide not creating such object if needed or you can just provide `ActivityListener.SampleUsingParentId` callback and decide what to do there.

What we are trying to fix here is to give more control to the `ActivityListener` when not providing `ActivityListener.SampleUsingParentId` and the default Ids forced to W3C format.

CC @noahfalk

**Comment by tarekgh** [comment]
by the way the table listed here is very useful to know the expected behavior:

https://github.com/dotnet/runtime/blob/fe67c3f20e3c2f4a26e460abaa0c15b8ce3de9da/src/libraries/System.Diagnostics.DiagnosticSource/tests/ActivitySourceTests.cs#L1083

**Comment by tarekgh** [comment]
@vishweshbankwar I am closing the issue but feel free to respond back with any question or ask and we'll be happy to help with. Thanks for your report.

**Comment by vishweshbankwar** [comment]
Thanks @tarekgh
