### ISSUE TITLE
Feature Request: Emit values from array instead of array itself when constructing JsonArray with only one enumerable

### ISSUE THREAD

**Issue by JohnyL** [dotnet/runtime#53477]
According to new [writable JSON API](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/#system-text-json-writable-dom-feature), it's possible to construct JSON with [object initializers](https://github.com/dotnet/designs/blob/main/accepted/2020/serializer/WriteableDomAndDynamic.md#support-for-c-object-initializers). Among other things, you can create an array like this:
```csharp
var json = new JsonObject
{
  ["nums"] = new JsonArray { 1, 2, 3 }
};
```
The output is:
```
{
  "nums": [
    1,
    2,
    3
  ]
}
```
However, if I want to emit data dynamically from array (or, in general, from some IEnumerable), I get the _array of array_:
```csharp
var nums = from x in Enumerable.Range(1, 3) select x;
var json = new JsonObject
{
  ["nums"] = new JsonArray { nums }
};
```
Output:
```
{
  "nums": [
    [
      1,
      2,
      3
    ]
  ]
}
```
So, here's the request: if there's _only one enumerable_ passed to object initializer, then emit its values only (as in the first output) instead of emitting array.

**Comment by svick** [comment]
I think this is a bad idea. There is nothing wrong with having an array of arrays, even one that contains a single array, and this suggestion would make creating those harder and inconsistent.

Also, because of the way object initializer works, it would require that `Add` also behaved inconsistently:

```c#
var array = new JsonArray();
array.Add(nums); // [ 1, 2, 3 ]
array.Add(nums); // [ [ 1, 2, 3 ], [ 1, 2, 3 ] ]
array.Add(nums); // [ [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ] ]
```

If you want to create a something that deserializes into a JSON array from a collection, you can use `JsonValue`: `JsonValue.Create(nums)`.

**Comment by JohnyL** [comment]
@svick `JsonValue.Create` did the trick. Thanks!
