### ISSUE TITLE
COR_E_EXECUTIONENGINE when debugging any managed code

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#53508]
## Repro Steps

Regression on a daily runtime build 

1. Checkout https://github.com/dotnet/winforms/commit/7c212247eb7757187612b5340b5d075fe43654e9 (the previous working commit)

2. `.\start-vs.cmd`

3. Set “WinformsControlsTest” as the start project

4. F5 and observe the project running

5. Close VS

6. Checkout https://github.com/dotnet/winforms/commit/542c6129652d47aa4f1b726208c8fe068f264973 (the problematic commit)

7. `.\start-vs.cmd`

8. Set “WinformsControlsTest” as the start project

9. F5 and observe the immediate crash:

```
The program '[20668] WinformsControlsTest.exe: Program Trace' has exited with code 0 (0x0).
The program '[20668] WinformsControlsTest.exe' has exited with code -2146233082 (0x80131506).
```

## Notes

The app can be executed from cli just fine though, so it is VS / .NET Runtime/SDK issue.

To verify:

1. Checkout https://github.com/dotnet/winforms/commit/542c6129652d47aa4f1b726208c8fe068f264973 (the problematic commit)

2. `.\start-code.cmd`

3. From console in VS Code run the following:
```
.\build.cmd
pushd .\artifacts\bin\WinformsControlsTest\Debug\net6.0
WinformsControlsTest.exe
```

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/120409560-893d3c80-c394-11eb-8a80-2a78bbe6afe2.png)

Disabling the suggested property has no effect

**Comment by hoyosjs** [comment]
This was caused by a codeinfo obtained in EEDbgInterfaceImpl::GetFuncletStartOffsets  upon JIT completion notification having an invalid jit manager after #53173 when there's jitting happening in the startup path.

**Comment by hoyosjs** [comment]
cc; @stephentoub

**Comment by tommcdon** [comment]
Adding @janvorli.  This is a debugging regression caused by https://github.com/dotnet/runtime/pull/53173/.  I'll managed debugging is broken on the current .NET 6 daily build.  Marking P0.

**Comment by hoyosjs** [comment]
The nibble lookup looks a little fishy. When we are instantiating the EECodeInfo from the address in the EE debug interface, we try to get the header in `EEJitManager::FindMethodCode`, but the lookup in the nibble map is returning something that doesn't make any sense. The inputs are correct, the heap list matched the one the jit manager used, and the module base is also correct. There are some bits of the implementation that look weird to me, but I'm not familiar with it as much and this has been used for a while, so the problem is likely in the flushing side. I think the issue happens because `CEEJitInfo::WriteCode` doesn't get called until after `CallCompileMethodWithSEHWrapper` - the method that notifies the debugger - returns to `UnsafeJitFunction`. If I manually evaluate `jitMgr->NibbleMapSet(comp->m_pCodeHeap, comp->m_CodeHeader->GetCodeStartAddress(), TRUE)` before the call, all lookups work correctly.

**Comment by RussKie** [comment]
I've just tested with v20210603.1, and everything appears back to normal.
Thank you

**Comment by Ashley-Li** [comment]
Verified the issue with latest .NET SDK 6.0.100-preview.6.21306.1, the issue has been fixed, after created a Winforms/WPF .Net 6.0 app and then press F5 to run it, run app successfully. Please see below gif:
![issue_53508_verify](https://user-images.githubusercontent.com/56664234/120954285-68545d00-c781-11eb-9613-a56172a193ee.gif)
