### ISSUE TITLE
[X509Certificate2 Class] X509Certificate2 can't export full bytes

### ISSUE THREAD

**Issue by BethanyZhou** [dotnet/runtime#53517]
### Description
X509Certificate2 can't export full bytes

```
PS C:\Users\bez> $secretByte = [Convert]::FromBase64String($secret)
PS C:\Users\bez> $x509Cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($secretByte, "", "Exportable,PersistKeySet")
PS C:\Users\bez> $type = [System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx
PS C:\Users\bez> $pfxFileByte = $x509Cert.Export($type, "")
PS C:\Users\bez> $secretByte.Equals($pfxFileByte)
False
```
### Configuration
* Which version of .NET is the code running on?
dotnet --version
5.0.203
* What OS and version, and what distro if applicable?
Win10
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
* If you're using Blazor, which web browser(s) do you see this issue in?
PowerShell 6

**Comment by vcsjones** [comment]
> X509Certificate2 can't export full bytes

Can you explain a little more about what problem you are having or what issue you are trying to solve? Based on your PowerShell sample, I can see a few issues.

The main issue I see is that you are expecting PFX/PKCS12 to round-trip byte-for-byte, which isn't going to work. An exported PFX/PKCS12 object is not deterministic, which is easier to illustrate as:

```c#
X509Certificate2 cert = new X509Certificate2("test.pfx", "test", X509KeyStorageFlags.EphemeralKeySet | X509KeyStorageFlags.Exportable);
byte[] bytes1 = cert.Export(X509ContentType.Pfx, "");
byte[] bytes2 = cert.Export(X509ContentType.Pfx, "");
Console.WriteLine(bytes1.AsSpan().SequenceEqual(bytes2)); // Prints false
```

This is because PBES1 uses PBKDF1 which has a random 8 byte salt. So the contents of the export are going to change each time.

Additionally, `Equals` performs reference equality. So something like this returns `false`:

```powershell
$a = [Convert]::FromBase64String("AQ==")
$b = [Convert]::FromBase64String("AQ==")
$a.Equals($b) # false
```

Even though they have the same binary content, they are not the same array references. You need to compare the actual contents of the array. An example of how to do so:

```powershell
[System.Linq.Enumerable]::SequenceEqual($a, $b) #true
```

**Comment by BethanyZhou** [comment]
Hi @vcsjones, thank you for your explanation. It makes me more clear about PFX. 

If I write $secretByte and $pfxFileByte to a PFX file respectively, I can install two similar certificate by them. But they will be a little difference, such as $pfxFileByte‘s certificate missed certificate chain to install. My question is why the size of $pfxFileByte is different with $secretByte and why their corresponding certificates are different.

**Comment by bartonjs** [comment]
> such as $pfxFileByte‘s certificate will miss certificate chain to install.

$pfxFileByte is the export of a single certificate to a PFX.  If you want to export multiple certificates you have to do it from an X509Certificate2Collection.  But you'd also need to change how you read the PFX to read the collection (instead of just a single cert, which picks one from the collection heuristically).

My Powershell-ese is poor, so I'll answer in C#:

```C#
X509Certificate2Collection coll = new X509Certificate2Collection();
coll.Import(secretByte, "", X509KeyStorageFlags.Exportable);
pfxFileByte = coll.Export(X509ContentType.Pfx, "");
```

(You should only specify PersistKeySet when you're importing a certificate to load it into an X509Store)

**Comment by BethanyZhou** [comment]
Thank you @bartonjs @vcsjones for the excellent answers!!! Will close this issue, thank you!
