### ISSUE TITLE
JIT doesn't recognize memory read in Vector256.Create

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#53541]
### Description
```cs
static Vector256<T> Test(ReadOnlySpan<T> data)
{
    return Vector256.Create(data[0]);
}
```
(the type does not matter here, but has to be specified explicitly)
generates (ignoring range checks etc.) some version of (example float)
```asm
vmovss   xmm0, dword ptr [rax]
vbroadcastss ymm0, ymm0
vmovupd  ymmword ptr[rcx], ymm0
```
something similar to `vpbroadcastw ymm0, ymmword ptr[rbp-3CH]` would be expected.

### Configuration
.NET 6 main branch from a few days ago (I can rebuild from latest commit if needed)
Windows10, Zen2 (Ryzen 9 3900x), Avx2 support.

### Other information
@tannergooding / @SingleAccretion identified that this related to JIT thinking this needs to be a 16-byte memory read (at least that's what I understood 😅).
(For future reference: https://discord.com/channels/143867839282020352/312132327348240384/849332771360473098 and following)

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib

**Comment by sandreenko** [comment]
If I understand correctly you are talking about not-efficient codegen, not a correctness issue, am I right?
From the dump I see that we transform `Create` as `BroadcastScalarToVector256(CreateScalarUnsafe)` and the inner one is not marked as contained so we end up with two instructions. The transformation happens here:
https://github.com/dotnet/runtime/blob/5399ee59e55a75a850011908a0f96d7abb8a91c7/src/coreclr/jit/lowerxarch.cpp#L965-L975

we could try to add logic to contain `CreateScalarUnsafe` or keep it as 1 node after lowering, but in 7.0.

**Comment by DeepakRajendrakumaran** [comment]
@tannergooding 
I went through the options - 1. Adding logic to contain ``` CreateScalarUnsafe ``` or 2. Keep it as  1 node after lowering

A couple of questions
1. From some initial experiments adding logic to contain  ``` CreateScalarUnsafe ``` creates more complications while trying to handle it. I think creating a  single node for an 'Indir -> create vector' pattern makes more sense. Does this sound like an acceptable solution here? To further expand on this - currently, we lower ```Vector256.Create ``` and ``Vector128.Create ``` to
``` CreateScalarUnsafe ``` + ``` BroadcastScalarToVector256/BroadcastScalarToVector128 ``` for a lot of cases including when the operand to ``Vector256.Create ``` is an ``` IND```. My proposal is to use the fact that ```BroadcastScalarToVector256/BroadcastScalarToVector128 ``` seem to be able to directly handle memory address as an operand and create a single ```BroadcastScalarToVector256/BroadcastScalarToVector128 ``` node which then gets lowered to 
``` VBROADCASTSS ymm, m32 ``` (ref https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.avx.broadcastscalartovector256?view=net-5.0). Does this make sense?

2. for this particular code snippet, is there any any specific reason for suggesting ```vpbroadcastw ymm0, ymmword ptr``` as the preferred instruction ?

The current asm is

On windows

``` asm
vmovss   xmm0, dword ptr [rax]
vbroadcastss ymm0, ymm0
vmovupd  ymmword ptr[rcx], ymm0 ```

I would expect the optimized asm to be something like this

On windows
``` asm
vbroadcastss ymm0, ymmword ptr[rax]
vmovupd  ymmword ptr[rcx], ymm0 ```

**Comment by DeepakRajendrakumaran** [comment]
@BruceForstall Tagging the right area owner for the above question from here - https://github.com/dotnet/runtime/blob/main/docs/area-owners.md

**Comment by tannergooding** [comment]
@DeepakRajendrakumaran, most of the logic comes down too `IsContainableHWIntrinsicOp` here: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5466

We should be generally handling `CreateScalarUnsafe` as containable IMO and avoiding the need to emit the `vmovss` if the consuming instruction supports reading only the element size from memory (`supportsSIMDScalarLoads`).

As per that, the non-containment here is because the check here is too narrow:
<https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5732-L5739>

Given that `VBROADCAST*`/`VPBROADCAST*` takes either an `XMM` register or a memory operand the size of the underlying element type, this should probably be closer to `NI_Vector128_CreateScalarUnsafe`. It shouldn't quite match as we still want to support broadcast in the case we have a full vector but its in memory.

That is, https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5732-L5739 should probably be setting `supportsSIMDScalarLoads = true;` here and possibly handling `supportsGeneralLoads` a bit different as well.

We should then probably also handle `CreateScalarUnsafe` as equivalent to `LoadScalarVector128`: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5839-L5843, particularly given they ar ethe same instruction for `float`/`double`.

**Comment by DeepakRajendrakumaran** [comment]
> @DeepakRajendrakumaran, most of the logic comes down too `IsContainableHWIntrinsicOp` here: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5466
> 
> We should be generally handling `CreateScalarUnsafe` as containable IMO and avoiding the need to emit the `vmovss` if the consuming instruction supports reading only the element size from memory (`supportsSIMDScalarLoads`).
> 
> As per that, the non-containment here is because the check here is too narrow: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5732-L5739
> 
> Given that `VBROADCAST*`/`VPBROADCAST*` takes either an `XMM` register or a memory operand the size of the underlying element type, this should probably be closer to `NI_Vector128_CreateScalarUnsafe`. It shouldn't quite match as we still want to support broadcast in the case we have a full vector but its in memory.
> 
> That is, https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5732-L5739 should probably be setting `supportsSIMDScalarLoads = true;` here and possibly handling `supportsGeneralLoads` a bit different as well.
> 
> We should then probably also handle `CreateScalarUnsafe` as equivalent to `LoadScalarVector128`: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L5839-L5843, particularly given they ar ethe same instruction for `float`/`double`.

Thanks for the detailed reply. It looks like you prefer handling ``` CreateScalarUnsafe ``` over identifying a pattern for which we simple create a ``` BroadcastScalarToVector* ``` . I will make the changes you suggest above and see how it goes.

For reference, this is how it would look if we were to do it the other way : https://github.com/DeepakRajendrakumaran/runtime/commit/17cde8d5c91ec99a056f53aa9e3c8b5ddabf9eb1 (It's a draft so probably can be cleaned up better but logic should be same)

**Comment by tannergooding** [comment]
> It looks like you prefer handling CreateScalarUnsafe over identifying a pattern for which we simple create a BroadcastScalarToVector*

Right and the reasoning is that `BroadcastScalarToVector*` is just one API out of a plethora of scalar hardware intrinsics. Things like `Sse.AddScalar(x, Vector128.CreateScalarUnsafe(5.0f
))` should likewise be "just as efficient" and that requires:
1. Correctly tracking the API as `supportsSIMDScalarLoads=true` (this is already true for most `*Scalar` APIs, just not `Broadcast`)
2. Correctly handling `Vector*.CreateScalarUnsafe` as foldable and roughly equivalent to `LoadScalarVector*`

**Comment by DeepakRajendrakumaran** [comment]
> > It looks like you prefer handling CreateScalarUnsafe over identifying a pattern for which we simple create a BroadcastScalarToVector*
> 
> Right and the reasoning is that `BroadcastScalarToVector*` is just one API out of a plethora of scalar hardware intrinsics. Things like `Sse.AddScalar(x, Vector128.CreateScalarUnsafe(5.0f ))` should likewise be "just as efficient" and that requires:
> 
> 1. Correctly tracking the API as `supportsSIMDScalarLoads=true` (this is already true for most `*Scalar` APIs, just not `Broadcast`)
> 2. Correctly handling `Vector*.CreateScalarUnsafe` as foldable and roughly equivalent to `LoadScalarVector*`

It's taking a  little longer than I expected because marking 'CreateScalarUnsafe' as contained breaks register allocation  because it doesn't update the def chain+ some other reasons. Even with that handled, I'm having to update the logic for 'genHWIntrinsic' as well(not necessarily in the exact func but how contained HWIntrinsics are handled when it's not memoryLoad/Store) the current assumption is any contained HWIntrinsics is a memLoad/Store while in this case it's a slightly more complicated Chain : BroadcastScalarToVector->CreateScalarUnsafe->IND->IND . Will update here when I have the issues sorted out.

**Comment by tannergooding** [comment]
After looking at it a bit more, I think there are two issues I can see.

-----------------

For the first issue, code such as `CreateScalarUnsafe(constant)` gives a tree that looks roughly like:
```
               [000006] -A--G+------              *  ASG       simd16 (copy)
               [000004] D---G+-N----              +--*  LCL_VAR   simd16<System.Runtime.Intrinsics.Vector128`1[Single]>(AX) V01 tmp1
               [000002] -----+------              \--*  HWINTRINSIC simd16 float BroadcastScalarToVector128
               [000001] -----+------                 \--*  HWINTRINSIC simd16 float CreateScalarUnsafe
               [000000] -----+------                    \--*  CNS_DBL   float  1.0000000000000000
```

We actually don't do really do containment of the `GT_DBL_CNS` and it's basically handled by `genSetRegToConst` instead (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/codegenxarch.cpp#L490-L507)
* This means that no other code can see the `CORINFO_FIELD_HANDLE hnd` introduced and so nothing can optimize around that

We notably have some handling for containing `CNS_DBL` for true scalar ops in `ContainCheckFloatBinary` (meaning `float + float`, rather than scalar HWIntrinsic ops like `Sse.AddScalar`), just not anywhere in the HWIntrinsic paths.

---------------------

The second case is just `CreateScalarUnsafe(value)` in general. `CreateScalarUnsafe` basically exists as a "shim" for the type system so the user can represent "I have a scalar value, I need a vector value".

If it's a `floating-point type` and `already in register` or a `float`, `double`, `int32`, `uint32`, `int64`, or `uint64` in memory the underlying value can be consumed directly. This is where `CreateScalarUnsafe` is conceptually itself "containable".

--------------------

When I initially responded; I was referring largely to the second case as I expect we want this to be generally handleable. That is, things like `Sse.Add(x, Vector128.CreateScalarUnsafe(y))` shouldn't have unnecessary `movss`, `movsd` or `movd` when `y` is  in memory or already in a SIMD register.

I do think both cases are interesting to consider and both likely have to be handled to get the "expected" codegen here. Although noting that `Vector128.Create(value)` also does a broadcast and is architecture agnostic and looks to "do the right thing", at least codegen wise (I've not checked if there are better ways we can handle the trees).

**Comment by DeepakRajendrakumaran** [comment]
@tannergooding Looks like you have commit for the same pending merge

This is the patch I have - I have already tested it for the cases involving createScalarUnsafe :  [myFix](https://github.com/DeepakRajendrakumaran/runtime/commit/60598a96b43a8fe722f3cd1732a6cd685729501b)

**Comment by tannergooding** [comment]
@DeepakRajendrakumaran, sorry, I didn't realize you had still been working on this.

The changes look to both cover this case, but with https://github.com/dotnet/runtime/pull/62407 covering the broader scenario of "all" intrinsics that support scalar loads and being a somewhat simpler change by removing the `CreateScalarUnsafe` by folding it away rather than containing it.

**Comment by DeepakRajendrakumaran** [comment]
@tannergooding No worries. I should have updated the comments. Been using this as a way to understand the backend better.
