### ISSUE TITLE
Add Volatile.Read for readonly variable

### ISSUE THREAD

**Issue by bysdxt** [dotnet/runtime#53611]
## Background and Motivation
C# has readonly struct, and sometime data in readonly struct need to be read by Volatile.Read method

## Proposed API

```diff
namespace System.Threading
{
	public static class Volatile
+		public static bool Read(in bool location);
+		public static byte Read(in byte location);
+		public static double Read(in double location);
		//...and so on
     }
```

## Usage Examples

``` C#
using System;
using System.Threading;
namespace ConsoleApp1 {
    class Program {
        static void Main(string[] args) {
            A a = new(3);
            Console.WriteLine(Volatile.Read(ref a.x));// this can run now
        }
    }
    readonly struct A {
        public readonly int x;
        public A(int x) => this.x = x + 1;
    }
}

```

## Risks && Alternative
There is a function overloading conflict between 'bool Read(ref bool location)' and 'bool Read(in bool location)'.
Maybe use new method name like 'bool ReadReadonly(in bool location)'

**Comment by alexrp** [comment]
> There is a function overloading conflict between 'bool Read(ref bool location)' and 'bool Read(in bool location)'.

This isn't just a risk. It's a compiler error, effectively making the proposed API impossible.

**Comment by alexrp** [comment]
I'm actually very curious what the motivating use cases for the proposed API are. If it's `readonly`, why do you care about atomicity or ordering? My immediate thoughts are this smells a bit like misuse of `Volatile`.

**Comment by Clockwork-Muse** [comment]
... classes, at least, emit a full fence during initialization, meaning you've already got the necessary barrier (barring doing something like calling out to another thread during construction).  I'm not sure if that's the case for non-default constructors for structs, though.

Your example is flawed because you're not using multiple threads; even if you were, some of the other mechanics of structs means similar structs would be copied in many situations that might otherwise require using `Volatile` or `lock`.  A more realistic example might be using a readonly array or other container, since the elements therein can be updated afterwards (although there's ways to block that).

**Comment by huoyaoyuan** [comment]
The situation is that the **struct member** is readonly, but the struct itself is store in a non-readonly field.
In this case the struct field itself is non atomic, and you should worry more about volatile.

If you do have usage, using `Unsafe.AsRef` will be sufficient.

**Comment by bysdxt** [comment]
> I'm actually very curious what the motivating use cases for the proposed API are. If the data is `readonly`, why do you care about atomicity or ordering? My immediate thought is that this smells a bit like misuse of `Volatile`.

'readonly' is just in current scope,not global.

for example, use int variable to tell the job thread need to exit:
```C#
using System;
using System.Threading;

namespace ConsoleApp1 {
    class Program {
        static void Main() {
            Signal e = new() { Exit = 0 };
            Thread jobTh = new(() => ProcessJobs(ref e.Exit));
            jobTh.Start();
            for (; ;Thread.Sleep(1) ) {
                if (!Console.KeyAvailable) continue;
                if(Console.ReadKey(true).Key == ConsoleKey.Escape) {
                    Volatile.Write(ref e.Exit, 1);
                    break;
                }
            }
            jobTh.Join();
        }
        static void ProcessJobs(ref int Exit) {
            for (; Volatile.Read(ref Exit) == 0; Thread.Sleep(1)) {
                //... do some jobs
                Console.WriteLine(DateTime.Now);
            }
        }
    }
    class Signal {
        public int Exit;
    }
}

```
I want to make sure that code in `ProcessJobs` method can not change the value of `Exit`.So I want to declare something like `void ProcessJobs(in int Exit)`

**Comment by Clockwork-Muse** [comment]
The "proper" type to use for that is usually [`CancellationToken`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-5.0).  Barring that, you hide the actual `Exit` field and provide a set of methods that manipulate/read the field with the appropriate atomic/volatile access... and then you pass `Signal`.

That aside, none of this is really necessary for this example;
 - You could make the field itself `volatile`, which should have the same effect.
 - You could use a tightly constrained lock, since you don't have any contention.
 - Just read/write the value.  You don't have an serious threading concerns here; while `ProcessJobs` may not exit as quickly, it should still eventually exit.

**Comment by stephentoub** [comment]
I agree with https://github.com/dotnet/runtime/issues/53611#issuecomment-853179585: needing to read `readonly` fields via Volatile is very niche, and in such situations, `Unsafe.AsRef` can be used, e.g. from your usage example, instead of:
> Console.WriteLine(Volatile.Read(in a.x));
you'd have:
> Console.WriteLine(Volatile.Read(ref Unsafe.AsRef(in a.x)));
and that already works today.

Given that it's a rare use case, there's a simple workaround, and we can't just add an overload of Volatile.Read (we can't overload on ref vs in), I'm going to close this.  Thanks for the suggestion.
