### ISSUE TITLE
[QUIC] SendMoreThanStreamLimitRequestsConcurrently_LastWaits on Mocks hangs in CI

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#53688]
`SocketsHttpHandlerTest_Http3_Mock.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(10)` will regularly hang in CI.
Discovered in #52704.

I'm unable to reproduce locally, even with the test running in a loop for more than an hour.

Test is disable via a condition in code:
```C#
// This combination leads to a hang manifesting in CI only. Disabling it until there's more time to investigate.
if (this.UseQuicImplementationProvider == QuicImplementationProviders.Mock)
{
    return;
}
```

Update: Seems like the first run of this tends to timeout (now it's the 100), disabling all mock runs for now.

**Comment by radical** [comment]
Is this failure caused by the problem being tracked here? (`linux x64`)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55848-merge-2184098765af4a5dab/System.Net.Http.Functional.Tests/console.e53e1391.log?sv=2019-07-07&se=2021-08-05T19%3A14%3A07Z&sr=c&sp=rl&sig=t5fCnf%2FCwLQ%2Fd8V%2FcmmAF21nLAvDL2zaE9Omh%2BOzLCM%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1242777&view=logs&jobId=71afe768-e493-597c-228c-037834193aeb&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6)

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(streamLimit: 10) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(273,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(Int32 streamLimit)
        --- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Unfortunately no, what you're reporting needs to be investigated on its own.
I did a quick Kusto query and:
```
"Method": SendMoreThanStreamLimitRequestsConcurrently_LastWaits,
"Result": Fail,
"Arguments": streamLimit: 10,
"count_": 159,
"min_Queued": 2021-07-16T14:42:38.333Z,
```

So it got broken on 16.7. and fails consistently only for stream limit 10.

**Comment by ManickaP** [comment]
https://github.com/dotnet/runtime/pull/70421
