### ISSUE TITLE
Crash CLR when using ComWrappers and multiple interfaces

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#53712]
This issue is somewhat strange, so I'm not yet sure that this is not my personal fault.

## What happens
Crash in app.
```
> kp c
 # Child-SP          RetAddr               Call Site
00 00000019`107fe330 00007ffb`3b049b76     KERNELBASE!RaiseException+0x69
01 00000019`107fe410 00007ffb`3b178521     coreclr!RaiseTheExceptionInternalOnly(class Object * throwable = 0x000001ec`67ee09a0, int rethrow = 0n276818176)+0x29a [D:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp @ 2806] 
02 00000019`107fe520 00007ffb`3b1e9e73     coreclr!UnwindAndContinueRethrowHelperAfterCatch(class Exception * pException = 0x000001ec`67ee09a0)+0x35 [D:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp @ 8137] 
03 00000019`107fe560 00007ffa`db5212bc     coreclr!JIT_RngChkFail(void)+0x63 [D:\workspace\_work\1\s\src\coreclr\src\vm\jithelpers.cpp @ 4239] 
04 00000019`107fe690 00007ffb`3b0a9373     0x00007ffa`db5212bc
05 00000019`107fe7c0 00007ffb`3af8d0fa     coreclr!CallDescrWorkerInternal(void)+0x83 [D:\workspace\_work\1\s\src\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 100] 
06 00000019`107fe800 00007ffb`3b0107df     coreclr!MethodDescCallSite::CallTargetWorker(unsigned int64 * pArguments = 0x00000019`107feac8, unsigned int64 * pReturnValue = 0x00000000`00000000, int cbReturnValue = 0n0)+0x3d2 [D:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.cpp @ 552] 
07 (Inline Function) --------`--------     coreclr!MethodDescCallSite::Call(void)+0xb [D:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.h @ 458] 
08 00000019`107fe990 00007ffb`3b0105aa     coreclr!RunMainInternal(struct Param * pParam = 0x00000019`107feae8)+0x11f [D:\workspace\_work\1\s\src\coreclr\src\vm\assembly.cpp @ 1465] 
09 00000019`107feac0 00007ffb`3b010309     coreclr!RunMain(class MethodDesc * pFD = 0x00007ffa`db5c4930, int * piRetVal = 0x00000019`107febb0, class PtrArray ** stringArgs = 0x00000019`107fef28)+0xd2 [D:\workspace\_work\1\s\src\coreclr\src\vm\assembly.cpp @ 1536] 
0a 00000019`107feb70 00007ffb`3b0100c8     coreclr!Assembly::ExecuteMainMethod(class PtrArray ** stringArgs = 0x00000019`107fef28)+0x1cd [D:\workspace\_work\1\s\src\coreclr\src\vm\assembly.cpp @ 1648] 
0b 00000019`107fef00 00007ffb`3afd2962     coreclr!CorHost2::ExecuteAssembly(unsigned long dwAppDomainId = <Value unavailable error>, wchar_t * pwzAssemblyPath = 0x00000000`00000001 "--- memory read error at address 0x00000000`00000001 ---", int argc = 0n0, wchar_t ** argv = 0x00000000`00000000, unsigned long * pReturnValue = 0x00000019`107ff150)+0x1c8 [D:\workspace\_work\1\s\src\coreclr\src\vm\corhost.cpp @ 384] 
```

This crash happens immidiately after exit from implementation of Proxy for COM method here https://github.com/kant2002/WinFormsComInterop/blob/c649814ba4dec2dc16b83c7564d44605e49cf6ea/WinFormsComInterop/IStreamVtbl.cs#L49-L50

And this is happens even if I reduce function implementation to just `return 0;`?

## Background
I have a project which provide ComWrappers suitable for WinForms. I use these wrappers to enable WinForms and NativeAOT. Recently I add support for COM interface IStream, to be able load images. Images in WinForms loaded in two ways, System.Drawing.Bitmap from System.Drawing.Common. This is how regular developers likely load images in their apps. Second way is using internal classes with interop. This is used for loading Cursors, etc. Internally both Bitmap and WinForms use `internal interface Interop.Ole32.IStream` which probably shared on source code level, or something like that.

## What I do.
Since mostly all COM interfaces used in WinForms are internal, I create fake project with same identity as `System.Windows.Forms.Primitives` and apply `[assembly: global::System.Runtime.CompilerServices.IgnoresAccessChecksTo("System.Windows.Forms.Primitives")]` to assembly with my ComWrappers.
When I add second project with fake identity for `System.Drawing.Common` and similarly decorate my assembly with `IgnoresAccessChecksTo`.
See https://github.com/kant2002/WinFormsComInterop/blob/c649814ba4dec2dc16b83c7564d44605e49cf6ea/WinFormsComInterop/IgnoresAccessChecksToAttribute.cs#L1 

Then in my ComWrappers implementation I use external aliases
```
extern alias primitives;
extern alias drawing;
```
to be explicit from which assembly I want `IStream` interface declaration.
Then in my implementation I check that I need to provide VTBL for object which supports `IStream` from System.Drawing.Common and hand created Com VTBL https://github.com/kant2002/WinFormsComInterop/blob/c649814ba4dec2dc16b83c7564d44605e49cf6ea/WinFormsComInterop/WinFormsComWrappers.cs#L92-L96
which when called just bypass to original implementation.
https://github.com/kant2002/WinFormsComInterop/blob/c649814ba4dec2dc16b83c7564d44605e49cf6ea/WinFormsComInterop/IStreamVtbl.cs#L49-L50

## Additional information
What I try
- I try create repro with minimal implementation of ComWrappers specifically for , but that works.
- If I run my implementation under NativeAOT, it works perfectly. (which obviously does not prove that my impl is correct).

I have fancy object which support both interfaces.

**Comment by AaronRobinsonMSFT** [comment]
@kant2002 I took a quick look at the `ComWrappers` implementation and this memory allocation for the vtable appears to be too small - https://github.com/kant2002/WinFormsComInterop/blob/c649814ba4dec2dc16b83c7564d44605e49cf6ea/WinFormsComInterop/WinFormsComWrappers.cs#L68-L83. I think it should be 14 instead of 12.

A general thought on this area. The entire `ComWrappers` API is a very advanced scenario and mentally debugging it is incredibly difficult. Add to this the infinite number of ways that wrapper types can created and it becomes very difficult to field this sorts of questions. There are a few approaches for helping to narrow down the issues.

1) Extensive unit testing at a granular level. A small sample of the runtime tests can be found [here](https://github.com/dotnet/runtime/blob/main/src/tests/Interop/COM/ComWrappers/API/Program.cs).
1) Stepping through the creation and management portion in WinDBG using the [SOS plug-in](https://docs.microsoft.com/dotnet/core/diagnostics/dotnet-sos). The SOS plug-in has a set of macros that help to understand the data structures in being used to enable the interop.
1) Consider starting from a basic design and then using code generation coupled with testing to remove trivial errors. The [C#/WinRT](https://github.com/microsoft/CsWinRT) tooling is an example of the approach we would recommend for library authors using `ComWrappers`. The vast majority of the code leveraging `ComWrappers` will be repetitious and is prone to minor mistakes that yield complex failure states.

**Comment by kant2002** [comment]
> I think it should be 14 instead of 12.

Yes. That was it. My apologies.

I agree with Source generators, since I understand that I cannot reliable work on that amount of interfaces and do not do mistakes. This interfaces was actually last way how I manually create, because I want initially better understand ropes, before going to code generation.
