### ISSUE TITLE
StringSegment IndexOf behavior

### ISSUE THREAD

**Issue by hrrrrustic** [dotnet/runtime#53727]
### Description
Working on reopening PR for #45021 (first one was closed due to inactivity)
Found a few more strange behaviors

**First**:
There is no check for the right bound in `IndexOf` like in the `IndexOfAny`
`IndexOfAny`:
https://github.com/dotnet/runtime/blob/911640b3a891f92ff66e9c82ce65f71d203f11a2/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L519-L529

`IndexOf`:
https://github.com/dotnet/runtime/blob/911640b3a891f92ff66e9c82ce65f71d203f11a2/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L457-L467

Anyway, exception will be thrown in Span\<T\>.Slice method  (exception message will be a little different), but I don't think this is by design 😄

**Second:**
Check for the right bound above (`IndexOfAny`) is quite weird, it allows to get index from original string
Example:
```C# 
public static void Main(string[] args)
        {
            StringSegment segment = new StringSegment("12345", 0, 1);
            var index = segment.IndexOfAny(new[] { '5' }, 2, 3);
            Console.WriteLine(index); // Prints 4 
        }
```
<del>I believe that correct value here should be -1, am I missing something?</del>
UPD: OutOfRangeException should be thrown
So it seems like `Buffer.Length` have to be replaced with `Length` property

### Regression?
Fixes will be breaking changes, but for the original issue (#45021) it was ok https://github.com/dotnet/runtime/pull/46432#issuecomment-803032974

**Comment by hrrrrustic** [comment]
@gfoidl @tarekgh @davidfowl (You reviewed/commented previous PR)

**Comment by gfoidl** [comment]
> exception will be thrown in Span<T>.Slice method (exception message will be a little different), but I don't think this is by design

You are right. In https://github.com/dotnet/runtime/pull/53463#discussion_r642749460 it was similar, and the argument validation was kept (to throw the correct exception with the right paramName).

**Comment by tarekgh** [comment]
CC @GrabYourPitchforks

**Comment by tarekgh** [comment]
@hrrrrustic 

> Btw, is it possible to unlock old PR or I have to create new one?

Could you please open a new PR if it is handy? Thanks!

**Comment by villarst** [comment]
Very weird. I tried testing with `var index1 = segment.IndexOfAny(new[] { '5' }, 0, 5);` and `var index2 = segment.IndexOfAny(new[] { '5' });` which resulted in 4 and -1 respectively. The only way you will get 4 as an output while having '5' as your char argument is if you have the index of  '5' be included in the two int arguments for `IndexOfAny (char[] anyOf, int startIndex, int count);`. Essentially you have to let it be hit or passed for a 4 to be outputted. 

My guess for why `var index1 = segment.IndexOfAny(new[] { '5' }, 0, 5);` is outputting a 4 is because when the IndexOfAny method is being called it is referring to the original string that is being passed in when we call `StringSegment segment = new StringSegment("12345", 0, 1);` 

I also tested `var index3 = segment.IndexOfAny(new[] { '4' }, 1, 3);` to see if maybe it was because the '5' was at the end of the string but I was still able to get a number other than -1 which was 3.
