### ISSUE TITLE
System.Memory referencing old version of System.Runtime.CompilerService.Unsafe 

### ISSUE THREAD

**Issue by dominoFire** [dotnet/runtime#53758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemMemory-referencing-old-version-of/1440601)._

---
[severity:It's more difficult to complete my work]
Hi!
I've got a problem with Nuget package System.Memory (v4.5.4) which is referencing an old version of System.Runtime.CompilerService.Unsafe (v4.5.3)
This is creating problems when I am using the newest versions of Roslyns CodeAnalysis Nuget packages (v3.9.0).

The package Microsoft.CodeAnalysis.Common (v3.9.0) is referencing System.Runtime.CompilerService.Unsafe (v5.0.0).
It also references System.Memory (v4.5.4) which in turn is not referencing the same version of System.Runtime.CompilerService.Unsafe (v4.5.3).
Even if I add assembly binding instructions in Web.Config this is still not working since it's searching for the old DLL for System.Runtime.CompilerService.Unsafe anyway.

The only solution I have come up with is to install the old DLL for System.Runtime.CompilerService.Unsafe in the GAC, but this is not really optimal.
Can you please update System.Memory to reference the same version of System.Runtime.CompilerService.Unsafe as Roslyn.CodeAnalysis.Common please?

---
#### Feedback Bot on 6/3/2021, 06:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by GrabYourPitchforks** [comment]
I'm assuming you're using a Full Framework ASP.NET app. I tried this using a 4.7.2 ASP.NET app and am unable to repro this on my machine. Installing the package and updating binding redirects (which should be performed automatically by the nuget client) should cause deployment to succeed. Can you validate that your web project's .csproj, your packages.config file, and your web.config file are all in sync?

Ensure that your .csproj has an entry similar to this in it:

```xml
<Reference Include="System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
  <HintPath>..\YourWebProject\packages\System.Runtime.CompilerServices.Unsafe.5.0.0\lib\net45\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
</Reference>
```

That your packages.config file has this entry:

```xml
<!-- targetFramework below might be different depending on your assembly -->
<package id="System.Runtime.CompilerServices.Unsafe" version="5.0.0" targetFramework="net472" />
```

And that your web.config has the correct binding redirect:

```xml
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

If you've verified all three of these and you can still repro the problem on your machine, please create a standalone ASP.NET app which demonstrates the problem, zip it up, and attach it to this issue. You can drag-and-drop a file into this text box to attach it to the issue. Reminder: any files attached here are public, so make sure there's no private or personal information in anything you attach.

**Comment by andersjarl** [comment]
Hi @GrabYourPitchforks!
And thanks for your thorough comments of what to check. Good stuff!

Everything turned out to match exactly what you wrote above with one minor exception.
I created a testproject and tested this all out and it worked, so I really scratched my head here.
I installed it on two different machines with same result.

So I got back to my faulty environment to see what was really going on here. And atlast I found the problem.
In that test-environment, where this was actually distributed, the assembly bindings had been commented out with  which I hadn't noticed. So the assembly bindings was there, and they were right, but not activated...

So when I removed the DLL from the GAC again (the old one that it said it was looking for), updated web.config, restarted IIS and did a new testrun it all worked...

I am really sorry for the trouble, jumping to early conclusions and pointing finger in the wrong direction.
I am very grateful for your help though! Sometimes you need a push in the right direction.

Regards
Anders

**Comment by GrabYourPitchforks** [comment]
Wow, glad you were able to drill down and debug that! Thanks for the follow up. :)
