### ISSUE TITLE
Cannot AOT compile with trimming disabled

### ISSUE THREAD

**Issue by lbargaoanu** [dotnet/runtime#53804]
With [this project](https://github.com/lbargaoanu/RoslynInBlazor/blob/master/RoslynInBlazor/RoslynInBlazor.csproj) I get
    
Could not load file or assembly 'Microsoft.AspNetCore.Components, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies..

I've disabled trimming because the trimmed version fails and I wanted to move forward.

**Comment by radical** [comment]
The error:

` Failed to load method 0x6000004 from '/private/tmp/RoslynInBlazor/RoslynIn       Blazor/obj/Debug/net6.0/RoslynInBlazor.dll' due to Could not load file or assembly 'Microsoft.AspNetCore.Components, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.`

This is happening because:
1. blazor invokes the wasm targets, before `publish` has copied the files to the output directory, but *after* trimming
	- So, the wasm targets get a list of the files in their original locations

2. When trimming is on, the files are in a single `linked/` dir
3. So, when `mono-aot-cross` is run for a given assembly, it is uses `MONO_PATH` that points to dir containing that assembly
	- in case of trimming, that's `linked/`, which has all the dependent assemblies too
	- so, `mono-aot-cross` can resolve the dependencies

	- But, with trimming off, the dependencies can be in different paths, and so `mono-aot-cross` can fail to resolve them

Example paths:
```
/private/tmp/RoslynInBlazor/RoslynInBlazor/obj/Debug/net6.0/RoslynInBlazor.dll

/Users/radical/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/6.0.0-preview.4.21253.7/runtimes/browser-wasm/lib/net6.0/Microsoft.CSharp.dll
/Users/radical/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/6.0.0-preview.4.21253.7/runtimes/browser-wasm/lib/net6.0/Microsoft.VisualBasic.Core.dll
/Users/radical/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/6.0.0-preview.4.21253.7/runtimes/browser-wasm/lib/net6.0/Microsoft.VisualBasic.dll

..

/Users/radical/.nuget/packages/microsoft.aspnetcore.components.forms/6.0.0-preview.4.21253.5/lib/net6.0/Microsoft.AspNetCore.Components.Forms.dll
/Users/radical/.nuget/packages/microsoft.aspnetcore.components.web/6.0.0-preview.4.21253.5/lib/net6.0/Microsoft.AspNetCore.Components.Web.dll
/Users/radical/.nuget/packages/microsoft.aspnetcore.components.webassembly/6.0.0-preview.4.21253.5/lib/net6.0/Microsoft.AspNetCore.Components.WebAssembly.dll
```

One solution here would be to add all the unique source paths as `MONO_PATH`, for `mono-aot-cross`.

**Comment by lewing** [comment]
So the problem here is resolving the assembly references inside mono-aot-cross across multiple directories?

**Comment by radical** [comment]
> So the problem here is resolving the assembly references inside mono-aot-cross across multiple directories?

Yeah.

**Comment by lewing** [comment]
@radical is this case covered by your current work?

**Comment by radical** [comment]
> @radical is this case covered by your current work?

Yeah, this can be done after the publish->build move.

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/58913 .
