### ISSUE TITLE
NET 5 GC and Reflection performance regression

### ISSUE THREAD

**Issue by helviett** [dotnet/runtime#53800]
### Description

We've got our own game engine written entirely in C#. We've moved from NET Framework to NET 5 and found that our animation engine and deserialization have become much slower. I've profiled our scene editor in some scenarios like heavy scene loading, tab switching, animation timeline rewind and found that in new runtime reflection is much slower and we have to wait for GC for a longer time. 

### Configuration

Windows 10 Pro x64, version 2004, OS build 19041.985.
.NET 5.0.201

### Regression?
Result of tab switching:

Was:
![image](https://user-images.githubusercontent.com/17850773/120966540-b8471a00-c7a9-11eb-9701-2be680c8ab7e.png)
Now:
![image](https://user-images.githubusercontent.com/17850773/120966610-cc8b1700-c7a9-11eb-89bc-da087676bb55.png)

The most time is spent in `System.Reflection.RtFieldInfo.GetValue`.

**Comment by joperezr** [comment]
Hey @helviett thanks for logging the issue. What tool did you use to profile your application? Would it be possible for you to profile using tools like the VS Profiler and share the results? That might be helpful into understanding which code are you calling that is now taking longer so we have something to investigate. Unfortunately, with the info you shared above we have really little to go and investigate, so we would appreciate more info, or even better, if you could come up with a small repro project that showed what you are seeing.

**Comment by helviett** [comment]
@joperezr I used dotTrace to profile. I've managed to create a repro for the [animation rewind](https://drive.google.com/file/d/1LZR0Ax846-K-qJ8k6Q5AG7b7EC2CfjrE/view?usp=sharing) problem.  Couldn't do the same for other issues yet. 

Basically, you should launch scene editor, open animation_rewind_repro.tan scene, set focus on timeline and rewind animation using mouse or arrows. My test wast just rewinding animation till 1000 frame with right arrow pressed. It takes 30s more in net5. 

You can launch a scene editor using Tangerine.bat file.

**Comment by krwq** [comment]
[Triage] @helviett can you see if you can create a smaller repro?

**Comment by jkotas** [comment]
@helviett  The screenshot that you have shared suggests that there is a lot more time spent accross number of areas: file I/O, collections, ... . It means that the regression is not specific to reflection. There is likely some behavior change in the top level logic of your app that causes a lot more work to be done now. I would suggest to look for the code where this behavior change happened.

**Comment by helviett** [comment]
@jkotas The tests were taken on exactly the same code base and assets. The only difference is everything related to net5 migration.

**Comment by jkotas** [comment]
I am not disageering that you are observing a performance regression. I am just pointing out that the root cause of the regression is likely in some higher level logic, and not in the GC or reflection itself as the title of the issue suggests.

Can you look at the full stacktraces of the `System.Reflection.RtFieldInfo.GetValue` calls where the time is spent? Are similar stacktraces present in the .NET Framework profile?

I am not able to build the repro project that you have shared. I am getting build errors like net5\EmptyProject\EmptyProject.Game\Dialogs\Options.cs(3,27,3,33): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'EmptyProject.Scenes' . It looks like a large complex project. I do not think we will be able to profile it for you. We can only provide guidance for what to look for in your profile.
