### ISSUE TITLE
Implement new FileStreamStrategy for Unix

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#53809]
https://github.com/dotnet/runtime/pull/53669#discussion_r645138381

cc @stephentoub

**Comment by teo-tsirpanis** [comment]
I can do it, I will start working on it in after July 2.

**Comment by stephentoub** [comment]
> I can do it, I will start working on it in after July 2.

@teo-tsirpanis, I hadn't seen this comment, and I was inspired to do it based on your RandomAccess PR.  Have you already started?  I'm fairly close to done, but if you're already working on it, I can drop mine and let you run with it.

**Comment by teo-tsirpanis** [comment]
No @stephentoub I haven't started it yet, that was going to be after the `RandomAccess` PR. Better not drop it though, I don't know how easy or hard it will be for me to do.

**Comment by teo-tsirpanis** [comment]
I am currently working on it, its progress can be found on https://github.com/teo-tsirpanis/dotnet-runtime/tree/unix-file-stream-strategy, I will submit a PR once ready.

**Comment by stephentoub** [comment]
Based on your previous response, I have a  PR ready to go; I just need to measure it with your other PR.

**Comment by teo-tsirpanis** [comment]
OK, better you do it, both PRs are following the same idea either way but yours is already complete and you can locally test and benchmark it (spoiler alert, I did not test the other PR on my machine, I don't even have Linux 😳). And you did some things ~~differently~~ better, like the `OperatingSystem` check for file locking on Macs instead of the pre-existing separate files I moved to `FileStreamHelpers`.

I reviewed your code and did not find anything I would change.
