### ISSUE TITLE
NET5.0 vs NETCore3.1 - Strings comparison between space and non-breaking-space characters

### ISSUE THREAD

**Issue by albertospelta** [dotnet/runtime#53856]
### Description

I am encountering different behavior comparing SPACE (ALT+032) and NBSP (ALT+255) characters using NET 5.0 or NETCore 3.1. 
It seems that the case insensitive comparison in NET 5.0 treats a space and a non-breaking-space as equal. 

### Configuration

* Which version of .NET is the code running on? `Microsoft.NETCore.App 5.0.6` and `Microsoft.NETCore.App 3.1.15`
* What is the architecture (x64, x86, ARM, ARM64)? `x64`
* Do you know whether it is specific to that configuration? `No`

### Steps to Reproduce
Here's a small example code to reproduce the issue

```csharp
var space = "Equality Test";
var nbsp = "Equality\x00A0Test";

Console.WriteLine($"Test 1: { space == nbsp }");
Console.WriteLine($"Test 2: { space.Equals(nbsp, StringComparison.CurrentCultureIgnoreCase) }");
```

### Actual Output

Target Framework NET 5.0

```
Test 1: False
Test 2: True
```

Target Framework NETCore 3.1

```
Test 1: False
Test 2: False
```

### Expected Output

This is the expected output for Target Framework NET 5.0 

```
Test 1: False
Test 2: False
```

**Comment by teo-tsirpanis** [comment]
Hello, did you ran the code on Windows 10 version 1903 or later? .NET 5 started using the ICU library for the globalization operations on these versions of Windows, to ensure consistent behavior between .NET's supported platforms (where ICU was already being used).

For more information about this change, as well as instructions to revert to the previous behavior take a look at https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu and https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus.

**Comment by tarekgh** [comment]
@albertospelta when we are using ICU library (as on non-Windows platforms or when using .NET 5.0 on Windows), we try to map the comparison options to Unicode collation strengths. I agree the current behavior is not perfect, but it is good enough for mainstream cases. 

How is this issue affecting your scenario? I am asking because changing the current behavior will be considered a major breaking change and we need to understand if your scenario is critical to consider fixing it. Thanks for your report.

**Comment by marcosqlbi** [comment]
@tarekgh we found the issue testing the [Microsoft.AnalysisServices.NetCore](https://www.nuget.org/packages/Microsoft.AnalysisServices.NetCore.retail.amd64) library with .NET 3.1 and .NET 5. Loading a valid model.bim file (which is a JSON serialized object model) with .NET Core 3.1 works. However, in .NET 5.0 the presence of two different measures with a name differing only by two separators (as shown by @albertospelta crashes the library.

![crash](https://user-images.githubusercontent.com/13840816/121243930-94193500-c89e-11eb-9ad2-77f88f3b218f.png)

 A workaround could be a fix in the Microsoft.AnalysisServices library so that the code works correctly with any .NET version. We can use a workaround in our application with a global setting, but the default behavior of the library is not consistent.
I suppose the same issue could be a breaking change for other libraries, even though currently we only have this use case.

**Comment by tarekgh** [comment]
@marcosqlbi thanks for the info. We understand there will be differences when running with .NET 5.0 on Windows as we switched to use ICU library there. If your library used on Linux or other non-Windows platforms, it should experience the exact same behavior you are seeing with .NET 5.0 even if using .NET Core 3.1. We have switched to use ICU on Windows for that exact purpose is to have consistent behavior across different platforms. 

We have a [config switch](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu) which can be used by the application when using .NET 5.0 to go back to the old behavior if needed. 

Side note, linguistically the space and non-breaking space should be equal because both are spaces. So, it looks to me distinguishing the two strings with space difference is not correct here. does your scenario really want to use linguistic behavior and not the ordinal behavior?

**Comment by albertospelta** [comment]
@tarekgh in our scenario the use of linguistic behavior is an internal implementation of the [Microsoft.AnalysisServices.NetCore](https://www.nuget.org/packages/Microsoft.AnalysisServices.NetCore.retail.amd64) Microsoft NuGet package which uses a dictionary with a `CurrentCultureIgnoreCase` string comparison.

**Comment by marcosqlbi** [comment]
@tarekgh As @albertospelta said. we are using another Microsoft library. While we can find a workaround for our application, the problem exists for any other developer using the same library. All the products producing the model.bim format today have the setting that makes a difference between those "different" spaces. I completely agree that this is a bad idea, but now we have to deal with the millions of Power BI models out there that already have this behavior.

As of today, using the Microsoft.AnalysisServices.NetCore library with .NET 5 cannot read a valid file generated by Visual Studio or Power BI. I think that fixing that library (forcing the comparison with the right setting) rather than changing .NET 5 could be the right solution. Unfortunately, that library is not open source, so we cannot edit it!

**Comment by marcosqlbi** [comment]
The Microsoft.AnalysisServices.NetCore library is just the .NET Core version of the Microsoft.AnalysisServices library for .NET Framework. Most of the existing products use the latter (Power BI, Analysis Services, just to name two MS products) and the generated files should be readable by the .NET Core version.
Today we found just one case, but we didn’t release our product yet. The actual number could be bigger once we release and other products start using .NET Core instead of .NET Framework. A small percentage of a very large number of models.

**Comment by tarekgh** [comment]
Isn't https://github.com/microsoft/Analysis-Services is the repo for such library? if so, could you please file issue there?

**Comment by marcosqlbi** [comment]
No, those are samples, the libraries have never been released as open-source.
NuGet packages are available here:

https://www.nuget.org/packages/Microsoft.AnalysisServices.NetCore.retail.amd64
https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64

**Comment by tarekgh** [comment]
I reached the owners, and they are currently looking.

**Comment by tarekgh** [comment]
Tagging the owners of Analysis-Services so they can respond and update about the progress here. 

@orenfisher @christianwade

**Comment by tarekgh** [comment]
This became stale and there is no action from .NET runtime. Please let's know if you still have a problem.

**Comment by marcosqlbi** [comment]
I confirm that the issue has been resolved in more recent versions of the [Microsoft.AnalysisServices.NetCore](https://www.nuget.org/packages/Microsoft.AnalysisServices.NetCore.retail.amd64) library.
