### ISSUE TITLE
BaseAddress null when AddHttpClient<T> registration is declared before than service registration

### ISSUE THREAD

**Issue by salem84** [dotnet/runtime#53944]
### Description
When wrote this code:

```
services.AddHttpClient<SampleService>(options =>
{
       options.BaseAddress = new Uri("https://petstore.swagger.io/v2/");
});
services.AddTransient<SampleService>();
```

HttpClient declared in SampleService is not null, but property BaseAddress is null.
Instead it works correctly when is declared as:
```
services.AddTransient<SampleService>();
services.AddHttpClient<SampleService>(options =>
{
       options.BaseAddress = new Uri("https://petstore.swagger.io/v2/");
});
```

Example XUnit Test project is available in https://github.com/salem84/HttpClientTest

### Configuration
Which version of .NET is the code running on? **SDK 5.0.301**
What OS and version? **Win 10**
Development environment? **Visual Studio 2019 (16.10.1)**

**Comment by ManickaP** [comment]
cc @CarnaViire

**Comment by FiniteReality** [comment]
`AddHttpClient<TClient>(Action<HttpClient>)` internally calls `AddTransient<TClient>()`, so in your first code snippet you're effectively overwriting the `SampleService` service:
https://github.com/dotnet/runtime/blob/00ee1c18715723e62484c9bc8a14f517455fc3b3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L403
https://github.com/dotnet/runtime/blob/00ee1c18715723e62484c9bc8a14f517455fc3b3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L338

This causes a blank HttpClient to be injected, which is why BaseAddress is null. The validation done by ReserveClient only looks for named client registrations, so it will only pick up two calls to `AddHttpClient<TClient>()`.

**Comment by CarnaViire** [comment]
That's right, a second call to `AddTransient` would overwrite the first one - that is how M.E.DI is designed. Since `AddHttpClient` already finished execution and the second `AddTransient` is just a call to DI itself, we cannot validate that from HttpClientFactory perspective. We do a validation on a second call to `AddHttpClient` though, as @FiniteReality kindly mentioned.

Closing as answered.
