### ISSUE TITLE
Need ChannelReader.TryReadAll

### ISSUE THREAD

**Issue by ahdung** [dotnet/runtime#54038]
assembly: System.Threading.Channels.dll
Type: System.Threading.Channels.ChannelReader<TRead>

Need method:
```c#
public bool TryReadAll<T>(out IEnumerable<T> items);
```

The goal is try to get all current exists items in channel, return empty if no element. no MoveNextAsync, no wait.

**Comment by stephentoub** [comment]
Can you elaborate on your scenarios / why this is needed?

You can implement this without new API on ChannelReader, e.g.
```C#
static IEnumerable<T> ReadAll<T>(this ChannelReader<T> reader)
{
    var results = new List<T>();
    while (reader.TryRead(out T item)) results.Add(item);
    return result;
}
```

I don't think this is a common enough need to add that or a TryReadAll variation.

If, instead, you were hoping for the operation to be atomic, there's no way to implement such an operation today for the unbounded channels, since it's not taking a lock around every operation, and there's no "extract all the contents of a ConcurrentQueue and clear it atomically" operation on ConcurrentQueue, which is what it uses internally.

**Comment by ahdung** [comment]
When need batch process, It's common, I believe that.

**Comment by stephentoub** [comment]
As there haven't been further requests for this, it's possible to implement a non-atomic equivalent in a couple of lines of consuming code, and there's no way today for the implementation to provide an atomic equivalent, I'm going to close this.  Thanks for the interest.
