### ISSUE TITLE
Loop alignment issue in Array2 benchmark

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#54072]
A recent change #51901 leading to a regression in the Benchstone.BenchI.Array2 benchmark on Ubuntu (but not Windows): #52316.

The core of the benchmark is the `Bench` function inner loop:
```
for (; loop != 0; loop--) {
    for (int i = 0; i < 10; i++) {
        for (int j = 0; j < 10; j++) {
            for (int k = 0; k < 10; k++) {
                d[i][j][k] = s[i][j][k];
            }
        }
    }
}
```

The code of this loop is almost equivalent, modulo register allocation, before and after #51901. The difference is loop alignment: before #51901, the loop fits in 2 32-byte chunks; after, it is in 3 32-byte chunks. On Ubuntu, this leads to about a 50% performance regression. Simply setting `COMPlus_JitAlignLoopAdaptive=0` changes the alignment such that the inner loop fits in 2 32-byte chunks, recovering the performance.

This is a high weight basic block; perhaps the alignment heuristics should "try harder" and be willing to insert more alignment padding in case it might be profitable?

**Comment by kunalspathak** [comment]
I have shared my investigation in https://github.com/dotnet/runtime/issues/52316#issuecomment-859192325. In before case, we align the loop (with `6 bytes`), but after your change we don't align it because of other heuristics (loop size vs. no. of padding needed). 

> This is a high weight basic block; perhaps the alignment heuristics should "try harder" 

We already have `COMPlus_JitAlignLoopMinBlockWeight` that tells if the alignment should be done, and in this case, we do try to align, but we want to restrict ourselves in adding too much padding because of code size reason, hence we have conservative heuristics. I don't think we can do much for this case; to put in other way - Before your change, the benchmark was benefitting from loop alignment, but after your change, it is not.

**Comment by kunalspathak** [comment]
No action needed here.
