### ISSUE TITLE
Breeze.Sharp.BaseEntity inherited model throws the error when using "System.Text.Json"

### ISSUE THREAD

**Issue by kmuthukumar23** [dotnet/runtime#54134]
Hi Team,

Thanks in advance.

I have tried to serialize the model using ‘System.Text.Json’ in Blazor server .NET 5.0 application. And I have inherited the ‘Breeze.Sharp.BaseEntity’ into my model class.  But, when I the application, it throws the following error.

![image](https://user-images.githubusercontent.com/31958591/121689480-455bdd00-cae2-11eb-9d18-f893894d7323.png)

Here is my Code,

    private string SerializeString{ get; set; }

    List<TodoItem> todos = new List<TodoItem>();

    public class TodoItem : Breeze.Sharp.BaseEntity {
        public int Id {
            get { return GetValue<int>(); }
            set { SetValue(value); }
        }

        public string Description {
            get { return GetValue<string>(); }
            set { SetValue(value); }
        }
    }

    protected override void OnInitialized()
    {
        todos = Enumerable.Range(1, 1).Select(x => new TodoItem()
        {
            Id = 1,
            Description = "Description",

        }).ToList();

        JsonSerializerOptions options = new JsonSerializerOptions()
        {
            ReferenceHandler = ReferenceHandler.Preserve
        };

        SerializeString = System.Text.Json.JsonSerializer.Serialize(todos, options);
    }

Also, I have attached the replication sample.

[BlazorApp1.zip](https://github.com/Breeze/breeze.sharp/files/6638550/BlazorApp1.zip)

Can anyone please help me to resolve this?

Thanks...

**Comment by olivier-spinelli** [comment]
You simply cannot do this: your base type exposes a "ClrType" that is a Type object and de/serializing a Type object is forbidden (for security reason).
You may handle the serialization of your object more explicitely.

**Comment by eiriktsarpalis** [comment]
As @olivier-spinelli points out, this is by-design behaviour due to security issues associated with `System.Type` serialization. My recommendation would be to use a dedicated DTO class for serialization that does not inherit from `Breeze.Sharp.BaseEntity` (which seems to be the type containing the `ClrType` property). Alternatively you could try to author a [custom converter for your class](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0).
