### ISSUE TITLE
RequiresAssemblyFilesAttribute is not always checked and applied correctly

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#54154]
There are cases like https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L255 where APIs which is not supported in single-file setup are not issuing any warnings when used. What is also strange is that the APIs which are annotated but have override don't need the annotation either, for example, https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L77

**Comment by MichalStrehovsky** [comment]
Isn't this tracked in https://github.com/mono/linker/issues/1985? I think there's a pull request with the fix in flight.

**Comment by marek-safar** [comment]
Do you think? In this case the method is already annotated but no warning is issued (it could be build issue)

**Comment by MichalStrehovsky** [comment]
> What is also strange is that the APIs which are annotated but have override don't need the annotation either,

This part sounds like the issue, but @tlakollo would know for sure. I would expect RAF to work the same as RUC in illink - all overrides have to have a matching annotation status with the slot defining method/implemented interface (so the warning here would be that CodeBase needs to have a RAF attribute and once one does that, the other warnings (at use site) will show up..

**Comment by tlakollo** [comment]
What Michal described is correct, the Requires attribute matching doesn't go through interfaces nor overrides in the analyzer at this moment, and that's true for both RUC and RAF. https://github.com/mono/linker/pull/2046 is the PR that tracks the implementation of this functionality. With this PR we will start producing IL2046 and IL3003 to report attributes not matching with the analyzer. At this moment the PR is halted to solve the diagnostic location for a source implementation with RUC/RAF and missing attributes in a MetadataReference. Once merged we will start to have warnings on the runtime for all of these cases.

**Comment by marek-safar** [comment]
> With this PR we will start producing IL2046 and IL3003 to report attributes not matching with the analyzer.

Just checking we are talking about the same thing. There are 2 places where the warning is missing now. Is your PR going to fix both of them ?

**Comment by tlakollo** [comment]
The PR will make https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L77 to warn with the new IL3003 because the override doesn't have the attribute, and once the attribute is there the analyzer will warn with IL3002 in https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L255 because the method is called. The second warning is not part of the fix in the PR, is the already existing analyzer behavior.
But in short yes, I expect after the PR is merged there will be a way to follow these broken paths and fix them
