### ISSUE TITLE
Features required to entirely remove the pkgprojs.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#54287]
This summarizes and tracks the features required to remove the pkgprojs and using dotnet pack.

- [ ] Trim Inbox dependencies
- [ ] adding dependencies for compatible frameworks  https://github.com/dotnet/runtime/issues/52982#issuecomment-845342994
- [ ] Add dependency groups for tfms not in package eg Xamarin.tvOS,  (TBD) 
- [x] Add extra targets for any analyzers related stuff or , where we add extra files.

cc @ViktorHofer @safern @ericstj

**Comment by ViktorHofer** [comment]
>  Trim Inbox dependencies

Does this require a NuGet feature? Isn't setting `PrivateAssets="all"` enough to exclude the dependency? See https://github.com/NuGet/Home/issues/6354#issuecomment-383754821.

>  Add dependency groups for tfms not in package eg Xamarin.tvOS, (TBD)

Why would we want this? It's actually currently quite confusing that dependency groups are added by the pkgproj infrastructure for .NETStandard compatible frameworks to trim out dependencies that are i.e. inbox. If there isn't a strong reason to do so, I would prefer to not have additional dependency groups specified.

**Comment by Anipik** [comment]
> Does this require a NuGet feature? Isn't setting PrivateAssets="all" enough to exclude the dependency? See NuGet/Home#6354 (comment).

Yes i didnt know that it will work for project references but it works well for package and project references.

**Comment by Anipik** [comment]
> adding dependencies for compatible frameworks

For this one i will suggest to just project references to those dependencies and add a validation to check we dont miss any.
@ericstj does it sound good ?

**Comment by ericstj** [comment]
> For this one i will suggest to just project references to those dependencies and add a validation to check we dont miss any.
@ericstj Eric St. John FTE does it sound good ?

Initially we need to catch this in the diff.  We can place a comment around any dependencies added for this purpose so that we don't accidently remove them.  The same project file should have the dependency on a compatible framework, so that shouldn't really be a problem in most cases (as it's really just omitting a condition).

Eventually we'd like to have a check in PackageValidation that examines dependencies across compatible frameworks and tells folks when they've dropped dependencies.

**Comment by ViktorHofer** [comment]
Closing as pkgprojs are removed.
