### ISSUE TITLE
Incorrect regex match results with negation under case-insensitivity

### ISSUE THREAD

**Issue by veanes** [dotnet/runtime#54408]
### Description

Two buggy code snippets:

1) The following two-line code snippet in C# produces the result **(False,True)**.
The correct output is **(True,True)**.

 CultureInfo.CurrentCulture = new CultureInfo("tr"); 
 Console.WriteLine("{0},{1}", Regex.IsMatch("i", "(?i:[^I-J])"), Regex.IsMatch("i", "(?i:[^IJ])"));

2) The following single-line code snippet also produces the wrong result **(True,False)** while the correct result is **(True,True)**.
Here the culture is not changed but is the current culture, so the bug is not just culture-related or negated-interval-related.

 Console.WriteLine("{0},{1}", Regex.IsMatch("i", "(?i:[\0-HJ-\uFFFF])"), Regex.IsMatch("i", "(?i:[^I])"));

Clearly [\0-HK-\uFFFF] and [^IJ] are equivalent character classes.

### Configuration

Both (1) and (2) can be reproduced under .NET framework 5.0.

### Regression?

(1) occurs in 4.8 so at least it is not a regression from 4.8.
(2) also reproduces under .NET framework 3.0 and 4.8 as well.
(CultureInfo.CurrentCulture setter used in (1) is not yet available in 3.0).
I believe that that the bugs originate from the same root cause, that seems 
to be a character-class-complementation semantics issue (under case-insensitivity).

**Comment by tannergooding** [comment]
This is not a bug.

`(?i:[^I])` and `(?i:[\0-HJ-\uFFFF])` are not equivalent ranges due to the case insensitivity. The equivalent range is instead `(?i:[\0-HJ-hj-\uFFFF])`

This is because the capital ASCII range is `0x0041-0x005A` while the lower case range is `0x0061-0x007A`. This means that `J-\uFFFF` includes `i`, which causes both `I` and `i` to be included due to being a case insensitive comparison.
