### ISSUE TITLE
Is there a way to disable network for a .net desktop applications?

### ISSUE THREAD

**Issue by harvinders** [dotnet/runtime#54413]
We develop desktop apps based on WPF and now on WinUI and MAUI, and test these apps on Azure DevOps on remote agents using WinAppDriver. We are facing the challenge of testing applications under network failure scenarios. Unfortunately, we can't disable network adapters etc on the agents (hosted or on-premise).

I am wondering if there is a way to just disable network for the application under test? It would be even great if we can simulate different network conditions like limiting the data rate etc. Seems like such support exists in android world.

The alternatives available are all extremely poor and requires setting up brittle infrastructure, like disabling network adapters, communicating through proxy, and all of which requires admin rights, something which network admins are not keen to hand over to developers for security reasons.

**Comment by Clockwork-Muse** [comment]
This likely won't be a property of the runtime, but something you have the OS do.  That's how Android is pulling it off as well - it's the OS enforcing a permissions model, especially for network access.  

Normally I'd say "get the OS firewall in on it", but if you're on Windows 10 there might be something easier to do.  Otherwise, if you do need to do firewall rules, you can probably have the machine admin set it up once.

**Comment by karelz** [comment]
Triage: Are you interested in disabling network entirely for the application for the entire time, or just for a short period of time?
Or do you expect only some requests to go through?

Overall it seems like this will be better handled at the OS layer, not at framework layer ...

**Comment by harvinders** [comment]
@karelz I am trying to just disconnect from network at particular point of time for short time only. 

I am not sure how best to control that through OS layer without requiring admin rights. Or what options are there, I had played with disabling the network adapters, but it cuts off the whole PC from the network and is not suitable. (e.g. if the test script is running remotely, as is an option using WinAppDriver). It also requires admin rights. Not to mention that something can go wrong before there is chance to enable it, bringing down the whole test suite. It is also not suitable if there are tests running in parallel.

Controlling through firewall, I have not tried, as I am not sure how to do it, may still require me to have admin rights, and this option still would require me to run tests one after another.

**Comment by wfurt** [comment]
back to your question @harvinders: there is really nothing similar to what you looking for .NET. Conceptually it is not .NET's  job to control the networking. It primarily exposes core functionality via friendly API. 

To elaborate little bit more on some of the topics: If given action needs admin privilege, app written in .NET will need it as well. That comes from core OS functions and typically it cannot be bypassed regardless of the language. If you don't want to or cannot interact with the OS or networking gear you will probably need to build fault injection to your app or test framework. e.g. have mode when you connect test server and that will fail with same pattern. Many of functions can be containerized if you don't want to deal with full scale operation.  

I'm closing this since the question was answered.
