### ISSUE TITLE
[MacCatalyst] Failing to build MacCatalyst 'preadv' 'pwritev' only available on macCatalyst 14.0 or newer

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#54424]
`./build.sh -s mono+libs+libs.pretest -os MacCatalyst -arch x64 -c Debug`
```
/Users/mdhwang/runtime/src/libraries/Native/Unix/System.Native/pal_io.c(1491,21): error GD510DF4C: 'preadv' is only available on macCatalyst 14.0 or newer [-Werror,-Wunguarded-availability-new] [/Users/mdhwang/runtime/src/libraries/Native/build-native.proj]
/Users/mdhwang/runtime/src/libraries/Native/Unix/System.Native/pal_io.c(1491,21): error GD510DF4C: 'preadv' is only available on macCatalyst 14.0 or newer [-Werror,-Wunguarded-availability-new] [/Users/mdhwang/runtime/src/libraries/Native/build-native.proj]
/Users/mdhwang/runtime/src/libraries/Native/Unix/System.Native/pal_io.c(1531,21): error GDC37A26C: 'pwritev' is only available on macCatalyst 14.0 or newer [-Werror,-Wunguarded-availability-new] [/Users/mdhwang/runtime/src/libraries/Native/build-native.proj]
EXEC : error : 'pwritev' is only available on macCatalyst 14.0 or newer [-Werror,-Wunguarded-availability-new] [/Users/mdhwang/runtime/src/libraries/Native/build-native.proj]
/Users/mdhwang/runtime/src/libraries/Native/build-native.proj(38,5): error MSB3073: The command ""/Users/mdhwang/runtime/src/libraries/Native/build-native.sh" x64 Debug outconfig net6.0-MacCatalyst-Debug-x64 -os MacCatalyst " exited with code 2.
```

**Comment by filipnavara** [comment]
cc @adamsitnik This needs the same guard as macOS.

**Comment by adamsitnik** [comment]
How is it possible that we have a CMAKE check for that:

https://github.com/dotnet/runtime/blob/f721cf4144005334827c02931317366f7f6ee114/src/libraries/Native/Unix/configure.cmake#L222-L225

and the call to `preadv` is guarded with `#if HAVE_PREADV`:

https://github.com/dotnet/runtime/blob/f891033db5b8ebf651176a3dcc3bec74a217f85e/src/libraries/Native/Unix/System.Native/pal_io.c#L1490-L1492

and we are still getting this error?

cc @janvorli

**Comment by filipnavara** [comment]
On macOS/iOS/tvOS/MacCatalyst you build on a quite recent SDK. This SDK does have `preadv` but it's decorated with an attribute that says on what OS version it started to be available:
```
ssize_t preadv(int, const struct iovec *, int, off_t) __DARWIN_NOCANCEL(preadv) __API_AVAILABLE(macos(11.0), ios(14.0), watchos(7.0), tvos(14.0))
```

If you compile with default flags it will not give you an error since it assumes you target the same OS version as the SDK. However, if you compile for downlevel OS (eg. `-target x86_64-apple-ios13.5-macabi`) you will get an error for APIs that don't have a runtime check (`if (__builtin_available(macOS 11, ...)`).

I have a suspicion that the target version flags are not passed for the configure checks. It's not exactly clear whether that's something you want to do but in this case it is.

**Comment by janvorli** [comment]
@adamsitnik I cannot build due to this problem even on my local Apple M1 device targetting macos arm64 without Catalyst option since your change that added those (I've mentioned that on your PR, but I guess you have missed it). We build with -mmacosx-version-min=11.0, but the API declaration is guarded in my SDK in the headers by the following check:
```
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE)
```
Looking at the compiler options for the pal_io.c, we set the _XOPEN_SOURCE, so that blocks the preadv / pwritev

Adding the following to the `src/libraries/Native/Unix/System.Native/CMakeLists.txt` fixes the problem:
```
add_definitions(-D_DARWIN_C_SOURCE)
```

**Comment by janvorli** [comment]
Ah, this seems to be a different issue. This is x64, we don't use -mmacosx-version-min=11.0 for x64, for that one we use -mmacosx-version-min=10.13. So either we need to move the minimum supported version to 11.0 for x64 too or, as @filipnavara mentioned, ensure that this option is used for the configure phase too (I think that he's right that it is likely the issue)

**Comment by filipnavara** [comment]
There are also some specific hard-coded `HAVE_*` checks for the mobile platforms so this could easily be added there until a better solution is implemented:

https://github.com/dotnet/runtime/blob/64f5f0b31d9af2df199229e6e4ef3f4a876a05a5/src/libraries/Native/Unix/configure.cmake#L512-L535

**Comment by janvorli** [comment]
I have found the culprit. The option `-mmacosx-version-min=10.13` is added using `add_compile_options` in `eng/native/configurecompiler.cmake`. That is included before the `runtime/src/libraries/Native/Unix/configure.cmake`. However, the `check_symbol_exists` (and other similar tests) only get compiler flags from CMAKE_C_FLAGS and CMAKE_CXX_FLAGS. cmake doesn't propagate the options added via `add_compile_options` to these variables, so the checking functions don't see the minimum version set.

There are two possible fixes here. One is to modify `eng/native/configurecompiler.cmake` to put the `MACOS_VERSION_MIN_FLAGS` into `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`. 
```diff
diff --git a/eng/native/configurecompiler.cmake b/eng/native/configurecompiler.cmake
index 99a8013d7cf..d47da771dd3 100644
--- a/eng/native/configurecompiler.cmake
+++ b/eng/native/configurecompiler.cmake
@@ -415,7 +415,8 @@ if (CLR_CMAKE_HOST_UNIX)
       else()
         clr_unknown_arch()
       endif()
-      add_compile_options(${MACOS_VERSION_MIN_FLAGS})
+      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${MACOS_VERSION_MIN_FLAGS}")
+      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${MACOS_VERSION_MIN_FLAGS}")
       add_linker_flag(${MACOS_VERSION_MIN_FLAGS})
     endif(CLR_CMAKE_TARGET_MACCATALYST)
   endif(CLR_CMAKE_HOST_OSX OR CLR_CMAKE_HOST_MACCATALYST)
```

The other is this:
```diff
diff --git a/src/libraries/Native/Unix/configure.cmake b/src/libraries/Native/Unix/configure.cmake
index 9d40db9dbf2..a630777a0b8 100644
--- a/src/libraries/Native/Unix/configure.cmake
+++ b/src/libraries/Native/Unix/configure.cmake
@@ -21,6 +21,9 @@ elseif (CLR_CMAKE_TARGET_LINUX)
set(PAL_UNIX_NAME \"LINUX\")
elseif (CLR_CMAKE_TARGET_OSX)
set(PAL_UNIX_NAME \"OSX\")
+ if (CLR_CMAKE_HOST_ARCH_ARM64)
+     set(CMAKE_REQUIRED_FLAGS -mmacosx-version-min=11)
+ else()
+     set(CMAKE_REQUIRED_FLAGS -mmacosx-version-min=10.13)
+ endif ()
```

The former is preferable as it doesn't duplicate the option choice.

**Comment by adamsitnik** [comment]
@janvorli awesome, big thanks for doing that! Would you like me to send a PR or do you want to do it  yourself?

**Comment by janvorli** [comment]
Let me send it out, I have made the change locally.

**Comment by janvorli** [comment]
My fix actually fixes just the issues I had. The catalyst problem remains. I am trying to figure out how to fix that one.

**Comment by filipnavara** [comment]
@janvorli The Catalyst build is a mess because CMake doesn't support it natively, at least not properly. Thus the `-target x86_64-apple-ios13.5-macabi` is likely injected at slightly different place than the equivalent macOS code.

https://github.com/dotnet/runtime/blob/f70723d3e5be910983b630dad32b2a08ec77f80e/eng/native/configurecompiler.cmake#L398-L404
https://github.com/dotnet/runtime/blob/64f5f0b31d9af2df199229e6e4ef3f4a876a05a5/src/libraries/Native/Unix/CMakeLists.txt#L82-L94

**Comment by janvorli** [comment]
@filipnavara thank you, this was helpful! I have believed that we've already fix our build so that the configurecompiler.cmake applies to everything in coreclr, libraries and installer, but it is clearly not the case.
