### ISSUE TITLE
Make Arrays implement IDictionary<int, T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#54491]
The title says it all.

An array is basically a dictionary where the key is the index.

￼

**Comment by davidfowl** [comment]
Any associated use cases?

**Comment by huoyaoyuan** [comment]
`IDictionary` is a contract more than indexer:

`Values`: array naturally supports
`Keys`: requires extra cost
`Add`: doesn't support
`ContainsKey`: can support
`Remove`: doesn't supports
`TryGetValue`: can support

And also, the behavior of set indexer is different with `IDictionary` contract: it throws for not-contained key.

Let array implements `IList<T>` is already a mistake since we didn't have readonly version then. Array lacks a lot of feature of `IDictionary`.

**Comment by tannergooding** [comment]
This would need a lot more discussion and as indicated above isn't trivial to do. This would also open the doors for any `IList` to also be an `IDictionary` which is likely undesirable and potentially confusing to many users.
