### ISSUE TITLE
new keyword variable is ignored when downcasting

### ISSUE THREAD

**Issue by GieltjE** [dotnet/runtime#54500]
### Description
When using the simplest possible class as a parameter in a function call any overriden variables using the new keyword in any derived classes are ignored.

Consider the following simple application:

```
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main()
        {
            ClassB classB = new();
            SetValue(classB, "CORRECT");
            Console.WriteLine(classB.TestVariable);
            Console.ReadLine();
        }
        private static void SetValue(ClassA classAOrB, String value)
        {
            classAOrB.TestVariable = value;
        }
    }

    public class ClassA
    {
        public String TestVariable = "oldValue";
    }
    public class ClassB : ClassA
    {
        public new String TestVariable = "WRONG";
    }
}
```

One would expect it to print "CORRECT", but it doesn't.

### Configuration
Tested with: .NET 4.8 and .NET5 on Windows 10 X64 21H1 with VS2019 16.10.2

**Comment by stephentoub** [comment]
> One would expect it to print "CORRECT", but it doesn't.

Printing "CORRECT" would be wrong.  ClassA.TestVariable and ClassB.TestVariable are two completely different fields.  The code creates a new ClassB (its ClassB.TestVariable will be "WRONG", ClassA.TestVariable will be "oldValue").  It then sets its ClassA.TestVariable to "CORRECT".  It then prints its ClassB.TestVariable, so it prints "WRONG".

If your goal is to override the base TestVariable with a derived TestVariable, it needs to be a virtual property rather than a field, and the derived type shouldn't use "new".  Using "new" is explicitly saying "this is completely unrelated to the same named one on the base type".

**Comment by huoyaoyuan** [comment]
> overriden variables using the new keyword

`new` keyword doesn't *override* member. It *hides* member. The two members have the same name **but with completely no relationship**.

**Comment by huoyaoyuan** [comment]
The code satisfies your expectation is:

```csharp
    public class ClassA
    {
        public virtual String TestVariable { get; set; } = "oldValue";
    }
    public class ClassB : ClassA
    {
        public override String TestVariable { get; set; } = "WRONG";
    }
```
