### ISSUE TITLE
[wasm] Check if `python` is installed when installing the workload

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#54638]
Right now the build expects python to be in the path on linux but ends up checking this by running `emcc --version` and not surfacing the error text.

**Comment by lewing** [comment]
Likely the cause of https://github.com/dotnet/runtime/issues/54342

**Comment by radical** [comment]
1. https://github.com/dotnet/runtime/pull/61276 surfaces the output of `emcc --version` correctly, so the error would show up for the user
2. But we should also check for python when installing the workload

**Comment by radical** [comment]
> But we should also check for python when installing the workload

This needs to be done on the sdk side, so closing this in favor of - https://github.com/dotnet/sdk/issues/26050 .

**Comment by radical** [comment]
Doing it in WorkloadManifest.targets would mean that we do it for every build. Though maybe we can add some sentinel file in `obj`, so we don't have to do that more than once for incremental builds.

**Comment by lewing** [comment]
I was thinking something simple like <OnError ExecuteTargets="SanityCheckEmsdk"/>

**Comment by radical** [comment]
> I was thinking something simple like `<OnError ExecuteTargets="SanityCheckEmsdk"/>`

That we essentially do:
 https://github.com/dotnet/runtime/blob/e43e31527db9f1a2dde3095a1651279b272c8c09/src/mono/wasm/build/WasmApp.Native.targets#L474-L486

First we run `emcc --version`, and if that fails then we run it again but surface the output to the user as errors.

This will show `emcc --version` failing due to missing python:
```
emcc --version
unable to find python in $PATH
```

So, if we are not adding a check at workload install time, then I think there is nothing else to be done here. But please re-open if you don't agree.
