### ISSUE TITLE
Unhelpful GDI+ Generic error in System.Drawing.Common

### ISSUE THREAD

**Issue by djthegr8** [dotnet/runtime#54946]
### Description

> Linked to #49275 

When trying to use GDI+ methods in Linux (specifically `FillPie`) I'm getting `Generic GDI+ Error`
This works fine in Windows and fails in Linux. 

### Configuration

* Which version of .NET is the code running on? 5.0.4
* What OS and version, and what distro if applicable? Ubuntu 16
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? yes

### Other information

Error:
```
System.AggregateException: One or more errors occurred. (A generic error occurred in GDI+.)
 ---> System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillPie(Brush brush, Single x, Single y, Single width, Single height, Single startAngle, Single sweepAngle)
   at System.Drawing.Graphics.FillPie(Brush brush, Rectangle rect, Single startAngle, Single sweepAngle)
   at ...
```

**Comment by safern** [comment]
Hello, @djthegr8. Thank you for submitting the issue. This is most likely a `libgdiplus` issue about not supporting this specific scenario.

However, we just announced that we will not longer support `System.Drawing.Common` on non-Windows OSs because of `libgdiplus` lacking a lot of stability and features. You can read more about this here: https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

Please let me know if you have any questions and if you need any help maybe doing this in other libraries as recommended in that document.

**Comment by djthegr8** [comment]
Thanks @safern for making me aware of this. I'm basically just using two functions `.FillPie`, `.DrawPie`, `FillRectangle` and `.DrawString` from this, so it could be great if you could redirect me to documentation regarding their alternatives in other libraries mentioned in above deprecation link.

**Comment by safern** [comment]
I definitely will. I'm working on putting together some basic examples on these alternative libraries.
