### ISSUE TITLE
[Mono] Make sure the iOS and MacCatalyst AOT workload packs are not imported on Windows

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#54944]
As detailed in https://github.com/dotnet/maui/pull/1443#discussion_r661091236, we need windows hosted AOT compiler packs for iOS & MacCatalyst.

**Comment by jonathanpeppers** [comment]
@steveisok I don't know if you need to actually run the AOT compiler on Windows, we just need to make sure these aren't imported because they are not installed on Windows:

https://github.com/dotnet/runtime/blob/685eda620e0f058b157b6d0a66da6f21c2d165fa/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets#L23-L25

(there might be more packs than this, too)

The errors you get when building iOS or MacCatalyst on Windows are:

```
C:\src\maui\bin\dotnet\sdk-manifests\6.0.100\microsoft.net.workload.mono.toolchain\WorkloadManifest.targets(23,9): error : C:\src\maui\bin\dotnet\sdk\6.0.100-preview.6.21328.1\Sdks\Microsoft.NETCore.App.Runtime.AOT.Cross.ios-arm\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
C:\src\maui\bin\dotnet\sdk-manifests\6.0.100\microsoft.net.workload.mono.toolchain\WorkloadManifest.targets(24,9): error : C:\src\maui\bin\dotnet\sdk\6.0.100-preview.6.21328.1\Sdks\Microsoft.NETCore.App.Runtime.AOT.Cross.ios-arm64\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
C:\src\maui\bin\dotnet\sdk-manifests\6.0.100\microsoft.net.workload.mono.toolchain\WorkloadManifest.targets(29,9): error : C:\src\maui\bin\dotnet\sdk\6.0.100-preview.6.21328.1\Sdks\Microsoft.NETCore.App.Runtime.AOT.Cross.maccatalyst\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
```

iOS has an "offline" build on Windows that just compiles your C# code against reference assemblies. You have to use a Mac build host to do a full build with AOT.

**Comment by jonathanpeppers** [comment]
I do think this is might be a blocker for Preview 6. Is there time to solve this?

**Comment by steveisok** [comment]
> I do think this is might be a blocker for Preview 6. Is there time to solve this?

From what I know, I believe it's too late for P6
