### ISSUE TITLE
[Preview 4] dotnet sdk check fails when runtimes installed via script

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet/runtime#54965]
Running `dotnet sdk check` throws this exception using dotnet preview4.

```console
➜ dotnet sdk check
System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libhostfxr, 1): image not found
   at Microsoft.DotNet.NativeWrapper.Interop.hostfxr_get_dotnet_environment_info(String dotnet_root, IntPtr reserved, hostfxr_get_dotnet_environment_info_result_fn result, IntPtr result_context)
   at Microsoft.DotNet.NativeWrapper.NETBundlesNativeWrapper.GetDotnetEnvironmentInfo(String dotnetExeDirectory) in Microsoft.DotNet.NativeWrapper.dll:token 0x600000f+0x20
   at Microsoft.DotNet.Tools.Sdk.Check.SdkCheckCommand.Execute() in dotnet.dll:token 0x60004e0+0x13
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args) in dotnet.dll:token 0x60008af+0x5e
   at Microsoft.DotNet.Tools.Sdk.SdkCommand.Run(String[] args) in dotnet.dll:token 0x60004ce+0x6
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient) in dotnet.dll:token 0x6000918+0x2e8
   at Microsoft.DotNet.Cli.Program.Main(String[] args) in dotnet.dll:token 0x6000916+0x6f
```

Here are the results of my call to `dotnet --list-sdks`

```console
➜ dotnet --list-sdks
2.1.202 [/Users/khalidabuhakmeh/.dotnet/sdk]
2.1.816 [/Users/khalidabuhakmeh/.dotnet/sdk]
3.0.103 [/Users/khalidabuhakmeh/.dotnet/sdk]
3.1.409 [/Users/khalidabuhakmeh/.dotnet/sdk]
5.0.203 [/Users/khalidabuhakmeh/.dotnet/sdk]
6.0.100-preview.3.21202.5 [/Users/khalidabuhakmeh/.dotnet/sdk]
6.0.100-preview.4.21255.9 [/Users/khalidabuhakmeh/.dotnet/sdk]
```

**Comment by agocke** [comment]
+ @elinor-fung @AaronRobinsonMSFT 

Looks like the PInvokes we use to find hostfxr on Mac have started failing. We suspect it might be Apple's SIP that's clearing environment variables. Any chance you've hit this before and know what the replacement should be?

**Comment by agocke** [comment]
Code is here: https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Resolvers/Microsoft.DotNet.NativeWrapper/Interop.cs#L92

Looks like the assumption in the SDK is that hostfxr is automatically located, but I'm not sure how that's supposed to work.

**Comment by AaronRobinsonMSFT** [comment]
@agocke This would be very sad if environment variables are being removed from the process space. I would imagine we are going to get far worse issues if this is a broader policy. I've not observed this in practice but if this does indeed become an issue we should think about some runtime policy to address it.

**Comment by elinor-fung** [comment]
I did not know about the loader variables being cleared. That said, I'm definitely not familiar with macOS, but I didn't think we would expect environment variables like `DYLD_LIBRARY_PATH` to point at hosting binaries?

> Looks like the assumption in the SDK is that hostfxr is automatically located

Could it be expecting that `hostfxr` will be found because it is already loaded in the process? @sfoslund - would you know if that is the assumption in that NativeWrapper code?

**Comment by mateoatr** [comment]
> Could it be expecting that hostfxr will be found because it is already loaded in the process?

It seems like this was the case. If I print all modules loaded by the process on Windows I can see hostfxr in there, while in macOS there's nothing else than the executing process (dotnet).

**Comment by elinor-fung** [comment]
> in macOS there's nothing else than the executing process (dotnet)

Is that only when SIP is enabled? `hostfxr` has to have been loaded before running the SDK code - I'd guess things are somehow locked down such that we can't correctly determine what is loaded?

**Comment by mateoatr** [comment]
Doesn't work with SIP disabled either -- from [Apple docs](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html):

> The first parameter to dlopen(3) OS X Developer Tools Manual Page is the name of the dynamic library to open. This may be a filename or a partially or fully qualified pathname. For example, libCelsus.dylib , lib/libCelsus.dylib , or /usr/local/libCelsus.dylib.
> 
> The dynamic loader searches for libraries in the directories specified by a set of environment variables and the process’s current working directory. These variables, when defined, must contain a colon-separated list of pathnames (absolute or relative) in which the dynamic loader searches for libraries. Table 1 lists the variables.


Only the native wraper is trying to load the hostfxr on this way (in the SDK). Here's [possible solution](https://gist.github.com/mateoatr/99ac599ae332b7b0c5c0dccfb589e315) (manually finding the hostfxr on the SDK). This also raises the question of whether `[DllImport("hostfxr")]` should work or what assumptions can be made on how DllImport looks for dlls where a path is not specified.

**Comment by agocke** [comment]
To add onto @mateoatr's comment, macos does not check loaded module names before trying to resolve a `dlopen` target. It doesn't matter that the so was already loaded -- it must be able to find it on disk first before checking load status.

**Comment by elinor-fung** [comment]
> Doesn't work with SIP disabled either
> It doesn't matter that the so was already loaded -- it must be able to find it on disk first before checking load status.

Wait, as in the scenario here is that this is just completely broken on any macOS? Or is it just M1?

I'm pretty sure some of the tests also rely on this (and they should be running on macOS, but only x64):
https://github.com/dotnet/runtime/blob/be80f675c7aa1fc895c053f80229d2591c69e5eb/src/installer/tests/Assets/TestProjects/HostApiInvokerApp/HostFXR.cs#L66-L67

> how DllImport looks for dlls where a path is not specified

The loading will go through:
- Any registered `DllImportResolver` delegate for the assembly containing the p/invoke
- For non-default ALC (don't think that is the case here), `AssemblyLoadContext.LoadUnmanagedDll`
- Cached unmanaged images (from previous p/invokes) based on the path/name
- `NATIVE_DLL_SEARCH_DIRECTORIES` (which I would not expect to point at the `hostfxr` directory)
- If `DllImportSearchPath.AssemblyDirectory` is specified, the containing assembly's directory
- `dlopen` with the library name
- `AssemblyLoadContext.ResolvingUnmanagedDll` event (don't think that is used here)

**Comment by agocke** [comment]
Checked on both my M1 and 2015 x64 Mac, both fail. If I open up a COREHOST trace I can see that hostfxr was found and loaded, but the interop wrapper then throws a `DllNotFoundException` saying "Unable to load shared library 'hostfxr' or one of its dependencies."

I suppose it could be something new in an OS update. The CI machines are running Cataline (10.15.7) and I'm running Big Sur (11.4).

@AaronRobinsonMSFT Do you have a pre-Big Sur Mac available? Any chance you could test the `dotnet sdk check` command and see if it works for you?

**Comment by AaronRobinsonMSFT** [comment]
>@AaronRobinsonMSFT Do you have a pre-Big Sur Mac available? Any chance you could test the dotnet sdk check command and see if it works for you?

Nope, I was forced to updated by... I had an incredibly snarky retort for this, I wish I could use it :-(

**Comment by agocke** [comment]
I can try running the hosting tests locally on my Mac and see if they work on 11.4.

**Comment by agocke** [comment]
They work -- although I'm assuming those tests run with `./build.sh host.tests -test`

**Comment by elinor-fung** [comment]
Ohh, I missed that those tests were explicitly copying over hostfxr on non-Windows:
https://github.com/dotnet/runtime/blob/be80f675c7aa1fc895c053f80229d2591c69e5eb/src/installer/tests/HostActivation.Tests/NativeHostApis.cs#L554-L562

Sorry for the noise/distraction.

**Comment by agocke** [comment]
Great, that makes sense. In that case, we can assume that this has never worked on Mac (no idea about Linux).

Is there a recommendation on what should be done instead? More generally, it seems like we have to define what we think `[DllImport("hostfxr")]` should do.

**Comment by elinor-fung** [comment]
`[DllImport("hostfxr")]` is doing what we expect it (or any DllImport with just the library name) should, in my opinion - basically going through any extension points and runtime-configured search paths and then it is just 'let the OS do its default load' (so whatever `dlopen`/`LoadLibrary` does on that OS).

Making the SDK implement a `DllImportResolver` (as @mateoatr had) makes sense to me. This is the same as would be needed for any other native library that is not part of the app's deps.json and not next to the app. Unfortunately, that would mean the SDK would have knowledge of the install layout baked into it - I think `Process.Modules` only has the main module on macOS, so the implementation couldn't use that to find the hostfxr that is already loaded.

The other possibility I see is having the host add the hostfxr path to `NATIVE_DLL_SEARCH_DIRECTORIES`. I don't think 
 it would make sense to always add it, since it would affect other p/invokes (add an extra lookup), so I think it would need to be conditional. That would avoid the SDK (or any other app that wants to invoke into hostfxr) needing to figure out install layout, but I don't see it as a common use case, so I wouldn't want some new behaviour/configuration for the host to keep maintaining and supporting just for this one internal case.

**Comment by vitek-karas** [comment]
After discussing this with a couple of people I like the idea of muxer helping SDK here. Let me first describe the possible solutions:
* The most correct one is to find the already loaded `hostfxr` in the process. Unfortunately runtime doesn't have this capability and `dlopen` doesn't do it either. But we do have a solution for this in `nethost` (well, hopefully - we should try if that solution actually works on M1)
  * Unfortunately calling `nethost` from SDK is tricky (ideally we would use it as a NuGet dependency, but that bring along quite a few other files which we would rather not ship in the SDK)
* Find the `hostfxr` on disk - this is not so bad - there are many things relying on the relative location of `dotnet` and `hostfxr` so adding another would not be the end of it.
* Modify the muxer (`dotnet`) to pass the path to the `hostfxr` to the SDK somehow.

I like the last solution the best (although technically the cleanest one is using `nethost`) since it's relatively cheap and relatively clean. (Kudos for this goes to @agocke). I also agree with @elinor-fung that the muxer should not do this unconditionally. But the muxer knows that it's running SDK - it has special code path to actually execute any SDK command, so it can easily do this only when running SDK. With that there are 2 options:
* Muxer would set some new runtime property, for example `HOSTFXR_FULL_PATH`. SDK would read this via `AppContext` and use it whichever way it wants to (in this case probably using it in the `DllImportResolver`).
* Muxer would add the path to hostfxr to the `NATIVE_DLL_SEARCH_DIRECTORIES`

I find the first one (special new property) cleaner, but it's more work. If others think that just setting the `NATIVE_DLL_SEARCH_DIRECTORIES` is not too bad, I'd be OK with it as well.

**Comment by elinor-fung** [comment]
I would much prefer the new property runtime property that the SDK can read and use however it needs.

**Comment by vitek-karas** [comment]
Just to summarize - the plan is to:
* Modify the muxer (`dotnet.exe`) to set a new runtime property called `HOSTFXR_PATH` (simplified the name) when launching SDK/CLI (`dotnet.dll`).
* SDK is expected to read this value via `AppContext.GetData("HOSTFXR_PATH")`
* SDK is expected to use this value to fix the `DllImport` problems - I'll let interop people advice what is the best way to do this (pre-load via `NativeLibrary` or use `DllImportResolver`, or something else)

**Comment by elinor-fung** [comment]
> SDK is expected to use this value to fix the DllImport problems

I'd recommend using `DllImportResolver`.

**Comment by tsal** [comment]
This is now happening on Preview 7, Big Sur (11.3) on Intel hardware. Based on the close date I'm guessing this hasn't released as of yet?

**Comment by agocke** [comment]
Yup this fix will be in rc1
