### ISSUE TITLE
a new poison test is failing in ci

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#55062]
Examples https://dev.azure.com/dnceng/public/_build/results?buildId=1216832&view=ms.vss-test-web.build-test-results-tab
added in https://github.com/dotnet/runtime/pull/54685

**Comment by jakobbotsch** [comment]
This seems to be failing because crossgen2 does not pass the `CORJIT_FLAG_DEBUG_CODE` to the JIT when optimizing, even when the module has the debug flag set. The crossgen jobs all pass -O to crossgen, so poisoning does not get turned on for the test.

Along with poisoning the flag also makes the JIT extend lifetimes on refs, ensure all IL basic blocks emit some code that can be breakpointed and ensure exception throws get unique code sites. The question is if crossgen2 should respect the debug flag in the module even when -O is passed. Thoughts @dotnet/crossgen-contrib?

**Comment by mangod9** [comment]
Yeah looks like it cg2 doesnt check the debuggable attribute if `-O` is explicitly specified. Its always been this way though, are you noticing that this started failing recently? 

https://github.com/dotnet/runtime/blob/17481fef502ee6aed6f9e8fc76e45bb5863c68b5/src/coreclr/tools/aot/crossgen2/Program.cs#L648

**Comment by jakobbotsch** [comment]
No, the test is new. So the alternative is to disable this test in crossgen2 jobs.

**Comment by mangod9** [comment]
we should fix it in cg2, but if its blocking yeah please disable for r2r jobs till its fixed.
