### ISSUE TITLE
.NET Core System.Math type has no overloaded support for TanH(decimal)

### ISSUE THREAD

**Issue by carlyman77** [dotnet/runtime#55115]
At time of writing, there are no overloaded methods in the `System.Math` type for many `decimal` operations, including `TanH(decimal)`. I noticed this became quite the issue when attempting to write my own hyperbolic tangent activation function for an artificial neural network I wrote for my recent paper. I believe this extra functionality will be extremely useful for those of us who require extra precision.

Proposed area would be area-System.Numerics.

Thank you for reading and I look forward to the discussion.

**Comment by tannergooding** [comment]
This is "by design". `System.Decimal` is a type designed for and around `currency` and does not expose many of the concepts required to correctly support transcendental functions.

We may in the future look at providing the IEEE 754 `decimal` types and would provide such APIs for said types if that happens.
