### ISSUE TITLE
SerStack.IsEmpty() clarification needed

### ISSUE THREAD

**Issue by jasonpugsley** [dotnet/runtime#55112]
https://github.com/dotnet/runtime/blob/0605bb3aba533702f234c907906ef076a97131fe/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryUtilClasses.cs#L190-L191
I was looking at this code and found it a little confusing.

The comment doesn't seem to describe the intent. My guess is the code was changed but the comment not updated.

From my reading of this class, only `_top == -1` would indicate an empty stack. When `_top == 0` it has 1 element. This code hasn't changed for 5 years so maybe it's working as intended, so I think it at least needs a comment that explains this behaviour to people like me ;)

Tagging @stephentoub from git blame

**Comment by stephentoub** [comment]
Thanks for pointing it out.

It's been like this basically forever; you tagged me from git blame, but that was just me importing the sources from .NET Framework... you can see it's the same logic there:
https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/runtime/serialization/formatters/binary/binaryutilclasses.cs#L345-L350

BinaryFormatter is obsolete:
https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0011
and we're avoiding making further changes to it.

It does look like the code should be:
```C#
internal bool IsEmpty() => _top < 0;
```
instead of:
```C#
internal bool IsEmpty() => _top <= 0;
```
but I don't think we'll change it at this time.

cc: @GrabYourPitchforks

**Comment by jasonpugsley** [comment]
OK, thanks for the explanation Stephen. If you have determined it is not a bug then we can close this issue.
