### ISSUE TITLE
LINQ: Combination of AsParallel, SelectMany and OrderBy of a custom IComparable throws when the enumerable contains duplicates

### ISSUE THREAD

**Issue by nth-commit** [dotnet/runtime#55159]
This took me ages to isolate. I have a machine that would do complex calculations in parallel, and very rarely, those calculations would land on a duplicate value, causing a crash.

This is my minimal reproduction:

```
private record Confidence(int Value) : IComparable<Confidence>
{
    public int CompareTo(Confidence? other) =>
        other == null ? 1 :
        Value > other.Value ? 1
        : -1;
}

new[] { 0 }
    .AsParallel()
    .SelectMany(x => new[]
    {
        new Confidence(x),
        new Confidence(x)
    })
    .OrderBy(x => x)
    .ToList();
```

Each LINQ operator there is important to repro, but just to "enumerate" (badumtish) the pre-conditions for this crash:
- Needs to be parallel
- Needs duplicates to be produced inside the select many
- Needs to order by the comparable, doing an ordering with  `x => x.Value` (the `int`) seems to work - is it a different codepath for ordering by a comparable vs. a known native type?

### Configuration

Windows 10
Version: 10.0.19042 Build 19042
Architecture: x64

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  
</Project>
```

### Regression?

Haven't tested other versions.

### Other information

Stacktrace:

```
Index was outside the bounds of the array.
   at System.Linq.Parallel.SortHelper`2.QuickSort(Int32 left, Int32 right, TKey[] keys, Int32[] indices, CancellationToken cancelToken)
   at System.Linq.Parallel.SortHelper`2.QuickSortIndicesInPlace(GrowingArray`1 keys, List`1 values, OrdinalIndexState ordinalIndexState)
   at System.Linq.Parallel.SortHelper`2.Sort()
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by pinkfloydx33** [comment]
If you fix your `CompareTo` method so that it handles the "equals" case, then the error goes away.

```csharp 
public int CompareTo(Confidence? other) =>
        other == null ? 1 :
        Value.CompareTo(other.Value);
```
[SharpLab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUAYiggBtiBDAI2IFMACaqSmvDARhc1tVYDoAZAJZQAjrQDcHLqwAsE3HjxRqAdwDaAXVoBvWpwC+eWkdo8AggGcACmTBlS1YgAoAlIeM8Ayg+oBjYAFkyKABPRwAPWgBeAD5aJTV1NyMtJOMjeNoAYQB7KAAzATgGH2pw5xhUtIyc/MLi0rDXXDS9JrSeAHkwIrAAIVCImNpG1J4AFWzBc2AXOQV5BcMwX2zurNyCoqgSxyFgWgA1OwhqZ1oQWgBJHIBbAAcbJmoAHhrN+ui8FObjVABmWh7db3GzUCaON51bbUAD8tGywAAFtQwGcYpVjAjkWAopE4iRiLQ4axzhijEdiCceLcHstwViUTwKSdnHI0mlDHpaPMgA===)  

Or
```csharp 
public int CompareTo(Confidence? other) =>
        other == null ? 1 :
        Value > other.Value ? 1 : 
        Value < other.Value ? -1 : 
        0;
```
[SharpLab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUAYiggBtiBDAI2IFMACaqSmvDARhc1tVYDoAZAJZQAjrQDcHLqwAsE3HjxRqAdwDaAXVoBvWpwC+eWkdo8AggGcACmTBlS1YgAoAlIeM8Ayg+oBjYAFkyKABPRwAPWgBeAD5aJTV1NyMtJOMjeNoAYQB7KAAzATgGH2pw5xhUtIyc/MLi0rDXXDS9JrSeAHkwIrAAIVCImNpG1J4AFWzBc2AXOQV5BcMwX2zurNyCoqgSxyFgWgA1OwhqZ1oQWgBJHIBbAAcbJmoAHhrN+ui8FObjVABmWh7db3GzUCaON51bbUAD8tGywAAFtQwGcYpVjAjkWAopE4iRiLQ4axzhijEdiCdaLEsSieBSqcTzrQyYdjnRnvCkXSGXQ4QBaEkXVmYORpNKGPQshZAA===) 

The error message itself is a little weird, but I'm pretty sure that some form of error or unexpected behavior is, well, *expected*. That said,  I'm having trouble determining which rule (if any) you've violated in the "note to implementers section" of the `IComparable` documentation. 

What's interesting is that if you return 0 instead of -1 that the error also goes away. See [SharpLab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUAYiggBtiBDAI2IFMACaqSmvDARhc1tVYDoAZAJZQAjrQDcHLqwAsE3HjxRqAdwDaAXVoBvWpwC+eWkdo8AggGcACmTBlS1YgAoAlIeM8Ayg+oBjYAFkyKABPRwAPWgBeAD5aJTV1NyMtJOMjeNoAYQB7KAAzATgGH2pw5xhUtIyc/MLi0rDXXDS9JrSeAHkwIrAAIVCImNpG1J4AFWzBc2AXOQV5BcMwX2zurNyCoqgSxyFgWgA1OwhqZ1oQWgBJHIBbAAcbJmoAHhrN+ui8FObjVABmWh7db3GzUCaON51bbUAD8tGywAAFtQwGcYpVjAjkWAopE4iRiLQ4axzhijEdiCdaLEsSieBSqcTzrQybQAPRshl0Z7wpF0rlE2gAWhJF1ZmDkaTShj0LIWQA===)

**Comment by Clockwork-Muse** [comment]
... my guess is that the sort algorithm finally throws up its hands in confusion, or due to an invariant being invalidated, almost certainly because this is a misbehaving comparison.

> That said, I'm having trouble determining which rule (if any) you've violated in the "note to implementers section" of the `IComparable` documentation.

[I don't know what you're talking about, it violates all of these](https://docs.microsoft.com/en-us/dotnet/api/system.icomparable.compareto?view=net-5.0#notes-to-implementers)

>Notes to Implementers
>For objects A, B and C, the following must be true:
>
>`A.CompareTo(A)` must return zero.
>
>If `A.CompareTo(B)` returns zero, then `B.CompareTo(A)` must return zero.
>
>If `A.CompareTo(B)` returns zero and `B.CompareTo(C)` returns zero, then `A.CompareTo(C)` must return zero.

(Although these specific rules are in the method documentation, not the overall interface documentation)

> What's interesting is that if you return 0 instead of -1 that the error also goes away.

This is almost certainly not guaranteed, as this would still violate the full set of comparison rules and be a misbehaving comparison.  Note that neither this "fix" nor the original result in a consistent sort order (stable isn't guaranteed regardless).

**Comment by pinkfloydx33** [comment]
Oh, I was definitely not suggesting it as a fix. Just commenting that something weird was happening.

And you're right. I was so focused on the "sign-based" rules that I paid no attention to the zero-based ones. That's what I get for posting something at 3am :-)
