### ISSUE TITLE
.NET Core 3.1 Process.Start cannot open url in OSX 10.14

### ISSUE THREAD

**Issue by derekantrican** [dotnet/runtime#55215]
My application has a number of users hitting the following error on OSX 10.14:

```
System.DllNotFoundException: Unable to load shared library 'libproc' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibproc, 1): image not found
Stack Trace:

at Interop.libproc.proc_pidpath(Int32 pid, Byte* buffer, UInt32 bufferSize)
at Interop.libproc.proc_pidpath(Int32 pid)
at System.Diagnostics.Process.ResolvePath(String filename)
at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start(String fileName, String arguments)
at Bulk_Edit_Calendar_Events_WPF.Common.OpenURLForAnyPlatform(String url) in /Users/derekantrican/Public/Drop Box/Bulk Edit Calendar Events/Code/Bulk Edit Calendar Events_WPF/Common.cs:line 39
```

The `OpenURLForAnyPlatform` method looks like this:

```csharp
public static void OpenURLForAnyPlatform(string url) //Credit: https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/
{
    try
    {
        Process.Start(url);
    }
    catch
    {
        // hack because of this: https://github.com/dotnet/corefx/issues/10361
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            url = url.Replace("&", "^&");
            Process.Start(new ProcessStartInfo("cmd", $"/c start {url}") { CreateNoWindow = true });
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            Process.Start("xdg-open", url);
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Process.Start("open", url);
        }
        else
        {
            throw;
        }
    }
}
```

This exception is *not* thrown on .NET 5 and seems to work just as expected (same code - only updated the framework). The issue seems to be only with .NET Core 3.1 & OSX 10.14 (maybe others, and maybe not all users on 10.14 - I do not have that data. I know that some users on 10.13 were able to open this successfully)

Some relevant envvars that I was able to collect from one user hitting this issue:

```
  "$LD_LIBRARY_PATH": null,
  "$DYLD_LIBRARY_PATH": null,
  "$DYLD_FALLBACK_LIBRARY_PATH": null,
  "$DYLD_FRAMEWORK_PATH": null,
  "$DYLD_FALLBACK_FRAMEWORK_PATH": null
```

I believe I have included all information that I have that is relevant to the template, but let me know if you would like more information.

This is a pretty big deal for my application because it requires users to go through an oauth flow in their browser and the url cannot be opened in the browser

**Comment by danmoseley** [comment]
I thought the fix in 5.0 may have been https://github.com/dotnet/runtime/pull/36029/files#diff-922ca9dbb79d523e05111f86ff64a296dcc226d61a57e07c02a505c1e2f05b14R13 based on this comment https://github.com/dotnet/runtime/issues/24095#issuecomment-609631612 -- but in that case DYLD_FALLBACK_FRAMEWORK_PATH was bad and you have pasted an empty one.

I don't have a mac handy -- on a working one, what are the values of these variables? https://stackoverflow.com/a/34905091 suggests they have default values. What happens if they define DYLD_FALLBACK_FRAMEWORK_PATH  as per those defaults, so it includes /usr/lib?

Also, can you please use DYLD_PRINT_LIBRARIES to get more info about where it's looking, as suggested in the error message?

(Is it feasible for these customers to update to 5.0 or later?)

**Comment by danmoseley** [comment]
Setting milestone future as this is apparently not a 6.0 issue.

**Comment by derekantrican** [comment]
Sorry for the delay

My solution was to just release a new version of my program built on .NET 5. I figured I'd log here in case there was some reason to push out some fix to .NET Core 3.1.

I can ask the user for the values of those variables. Did you have a suggestion for what to do in regards to "please use DYLD_PRINT_LIBRARIES to get more info about where it's looking"?

**Comment by danmoseley** [comment]
The goal is to find out where it's looking for libproc, because either it's not looking in /usr/lib or somehow it's not there.

Now I think about it, `DYLD_PRINT_LIBRARIES=1` will write to stderr where successful loads come from. In this case it's not loading successfully. (I don't have a mac handy right now to try)

https://stackoverflow.com/questions/51178311/dotnet-restore-unable-to-load-shared-library-libproc-or-one-of-its-dependencie
suggests using fs-usage for that:
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/FileSystem/Articles/FileSystemCalls.html

If your customers are willing to use .NET 5.0, I don't think this is worth investigating further, though.

**Comment by derekantrican** [comment]
Thanks for the stackoverflow link - I couldn't find one before.

Yeah, I personally don't have any problem with marking this as "won't fix - just use .NET 5" (though someone else may have a more specific reason why they can't upgrade). Just figured I'd report it so you guys were aware

**Comment by danmoseley** [comment]
We appreciate the report! I'll close. BTW, perhaps you'd be interested in picking up an issue to contribute a PR for something?

**Comment by derekantrican** [comment]
> perhaps you'd be interested in picking up an issue to contribute a PR for something?

I would if I had any free time! Unfortunately more busy these days than I'd like :)

**Comment by danmoseley** [comment]
@derekantrican I understand completely! I often ask, so folks know that they're welcome here 😄
