### ISSUE TITLE
Blazor WebAssembly debugger jumps into JS code mono CLR while debugging C# only code 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#55214]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssembly-debugger-jumps-into-J/1460253)._

---
Debugging Blazor apps, when it stops in a breakpoint, pressing F10 or even F5 sometimes, it jumps from C# into the JS code of the mono/CLR, which makes no sense.
I would expect to only stop in my C# code and not in minimise JS from the framework, which is useless.

! [image.png] (https://aka.ms/dc/image?name=Bdae72a2c859b416abae54aeb5aa71c7f637601756372352277_20210625-095358-image.png&tid=dae72a2c859b416abae54aeb5aa71c7f637601756372352277)

! [image.png] (https://aka.ms/dc/image?name=B08eea34afe7f462691618cc5df896729637601755533096995_20210625-095234-image.png&tid=08eea34afe7f462691618cc5df896729637601755533096995)

---
#### Feedback Bot on 6/24/2021, 11:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by lewing** [comment]
Without digging into the details I suspect this is the expected behavior of the current code, we should consider if it makes sense to be more aggressive about filtering out the implementation details here.

**Comment by rmencia-isv** [comment]
I created this item because me and my team we have experienced this a number of times. 
The first thing that comes to our heads is, something went wrong, the debugger/VS has failed again, restart the application or even VS. Even when we realised that it was happening consistently but nothing was broken, we just wasted some time trying to figure out what was happening. More junior guys kept asking the more senior devs to get help because they thought their VS install was wrong and even wasted a full day reinstalling VS. 

I don't think that any developers using Blazor need to see the minimised code of the CLR in JS. Maybe it's something that you would need for the Blazor framework development, but you could accomplish that by adding a setting/flag in VS to enable it. 

Just my point of view.

**Comment by lewing** [comment]
@rmencia-isv the tricky part here is passing the flags down to the wasm debugger, we are working on it.

**Comment by thaystg** [comment]
@rmencia-isv are you still getting this behavior?

**Comment by rmencia-isv** [comment]
Sorry, I'm not doing any debugging on blazor at the moment, I'm working on the API. I was getting very frustrated with blazor dev work, so I decided to complete the API and wait for a few more versions to fix the large number of issues I was finding every day.

Get Outlook for Android<https://aka.ms/AAb9ysg>

Roberto Mencia Franco
Principal Solutions Architect

40 Rosslyn Street
West Melbourne VIC 3003
T: 03 9825 7200 | D: 03 9825 7221<tel:03%209825%207221>
***@***.******@***.***>

[cid:isv_logo_emailsignature_c7e588ed-f2af-475e-9fd5-ac616247555f.png]

[cid:isv_blueblogicon_32x32px_ce38392c-df77-4e11-ba92-5f2222689245.png]<https://is.vic.edu.au/media-centre/blog/> [cid:isv_bluelinkedinicon_32x32px_0838ad28-6fa9-46e7-a61b-c84b567e3f35.png] <https://www.linkedin.com/company/independent-schools-victoria/mycompany/>  [cid:isv_bluefbicon_32x32px_faca1ac8-e138-40a7-8af4-04d9d1edad5c.png] <https://www.facebook.com/IndSchoolsVictoria>  [cid:isv_bluetwittericon_32x32px_48f38438-42a0-427e-b326-b9f367a20f00.png] <https://twitter.com/IndSchoolsVic>  [cid:isv_blueyticon_32x32px_3ba24e02-7c77-4f92-9663-dee38134d93e.png] <https://www.youtube.com/channel/UCDGrFIPCQF4WLtItF4DlHMg>

***@***.***

<https://is.vic.edu.au/programs/principals-leadership-academy/><https://is.vic.edu.au/programs/teacher-fellowship-program/><https://bit.ly/3Hi2x2g><https://bit.ly/3Hi2x2g><https://bit.ly/isv-ohs><https://bit.ly/3Hi2x2g><https://bit.ly/isv-ohs><https://bit.ly/3xFPG5M><https://bit.ly/3lPGS8O><https://bit.ly/3GiX61v><https://bit.ly/3rEY9om><https://bit.ly/3rEY9om><https://is.vic.edu.au/programs/principals-leadership-academy/><https://is.vic.edu.au/programs/principals-leadership-academy/><https://bit.ly/3hkNVUc><https://bit.ly/3tC96XF><https://bit.ly/3HWqZFG><https://bit.ly/36m4gWG><https://bit.ly/3K5So9X><https://bit.ly/3LOi9Mr><https://is.vic.edu.au/learning-and-development/reignite-series/><https://is.vic.edu.au/learning-and-development/reignite-series/#unpacking-resilience><https://bit.ly/3KENjoF><https://bit.ly/3Pv1qQV><https://bit.ly/394JNHj><https://bit.ly/39o14LL>[cid:lead_survey2022_emailsignaturebanner_abd2a967-2ee5-414b-8500-f90774970571.png]<https://bit.ly/3Pv1qQV>
<https://bit.ly/3kmmwn6>
We work flexibly at Independent Schools Victoria. I'm sending this message now because this time suits me, and I encourage you to read, respond or action this email at a time that best works for you. Read our email disclaimer<https://is.vic.edu.au/terms-of-use/>.


________________________________
