### ISSUE TITLE
RuntimeConfigParserTask fails in .NET framework MSBuild

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#55277]
### Description

This would fail inside VS Windows, but you can repro by doing:

* `dotnet new android`
* `"C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\MSBuild.exe" -restore`
or
* `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe" -restore`

Fails with:
```
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\30.0.100-preview.6.62\targets\Microsoft.Android.Sdk.RuntimeConfig.targets(36,5): error MSB4018: The "RuntimeConfigParserTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at RuntimeConfigParserTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

This works fine if you use `dotnet build` instead of using .NET framework.

### Configuration

```
> dotnet --version
6.0.100-preview.6.21355.2
```

### Regression?

I'm not sure if .NET framework MSBuild worked before or not.

### Other information

Here is are `.binlog` files using `MSBuild.exe` from VS 2022 and VS 2019:

[logs.zip](https://github.com/dotnet/runtime/files/6778758/logs.zip)

/cc @steveisok

**Comment by safern** [comment]
@steveisok this looks more like mono infra, rather than libraries infra?

**Comment by steveisok** [comment]
@akoeplinger Can you please look into this?

**Comment by lambdageek** [comment]
On .NET Framework, S.R.M should come from nuget. https://www.nuget.org/packages/System.Reflection.Metadata/5.0.0
We probably needs some PrivateAssets thing in the .csproj for framework.

That said, another way to fix this is to stop using BlobBuilder for writing length-prefixed UTF8 strings.
https://github.com/dotnet/runtime/blob/e544ccffbd6f7018372923871dd39129810e4b11/src/tasks/RuntimeConfigParser/RuntimeConfigParser.cs#L98-L103

The tricky bit is that the length uses the ECMA value-based compression (values < 255 take 1 byte, otherwise 2 bytes or 4 bytes) which we'd need to re-implement ourselves.  But it should be simple.
