### ISSUE TITLE
Inefficient codegen for enum -> object -> int casts

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#55355]
### Description

The JIT usually optimizes box + unbox cases, this isn't the case for enum -> object -> int though. Filled per request from @EgorBo 

### Configuration

Sharplab Core CLR v5.0.721.25508

### Regression?

No idea.

### Data

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQBMlKgHZlAb2Xln5ANoApVhgDiMJiOkACgwATz4YCAAzQIBRJgZ8KgBKJIBdZwB6DPImCAwnF1cAWRgMdQgAEwBJfkFAkrLKmr5BAHk+NggmXBoAQQBzfthcXFYJGCqmQVYmGf60gudiAGZrJHJgCAhBcgAJPAAxQWx+gB4AFQA+QPPyCWxBBhg0clvI4/nF8kclFz/KGzkQKBGYYJKBCDAABWMDAYPujxg5AAZEDQeDITC4Ul3ickuQALwEoEMdEQ6GwsG4/qmP4AX2UDLMKlWfgS5DiCSo33IvReACFyHSgA)

**Comment by EgorBo** [comment]
Repro: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQBMlKgHZlAb2Xln5ANoApVhgDiMJiOkACgwATz4YCAAzQIBRJgZ8KgBKJIBdJxdXAFkYDHUIABMASX5BQJy8wpK+QQB5PjYIJlwaAEEAc3bYXFxWCRgipkFWJhH2tIznYAgIQXIACTwAMUFsdoAeABUAPkDN8gQqNHJ9hAsk8gBebfJAkYwkwIhgACsYMAfD50vL2/vH55vD5JM6mAC+ynMAGZyH4EuQ4gkqOR7ORWscAELkMFAA==

Potential fix: https://github.com/EgorBo/runtime-1/commit/b38c94e3af8f917d44b33eaffe192b89b1214f8a (but it's not correct since some places expect compareTypesForEquality to compare types directly so we probably need to get underlying type of Enums in JIT)

**Comment by EgorBo** [comment]
I've made a proper fix but the jit-diff couldn't find any diffs so I delayed it to 7.0.0

**Comment by deeprobin** [comment]
Potential workaround:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQBMlKgHZlAb2Xln5ANoApVhgDiMJiOkACgwATz4YCAAzQIBRJgZ8KgBKJIBdJxdXAFkYDHUIABMASX5BQJy8wpK+QQB5PjYIJlwaAEEAc3bYXFxWCRgipkFWJhH2tIznZlxsSJhyYAgIQXIACTwAMUFsdoAeABUAPkD98gQqNHJThAsk8kclFyfyCS0zqgAFDChyAF5yACqzVmnFauA+EBGGBEgVgkXeSVMzxcrx+Ny+P3+QJmcza4MhLBhcLOtyRyPIUPegwwf0BwNxYLoMEiuyhx3OGMRk2elJu1Np2JBeKZLLZgXR3y5j3JxBsVJYf3+fJYZOcAF9lBqzCoAMzkPwJchxBJUe7kVqXABC5DVQA=
