### ISSUE TITLE
object.ToString() claims it can return a nullable string?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/runtime#55509]
After reading through https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-5.0, it is stated that:

> - Your ToString() override should not return Empty or a null string.

Why then is the signature marked that it returns a possible null string?

Is this in the event the inheritor has decided to ignore the conventions and go crazy by returning `null` and various other things?

**Comment by stephentoub** [comment]
> Why then is the signature marked that it returns a possible null string?

Because, even with that, over 20 years of .NET history many implementations return null and empty string.  The nullability annotations are meant to reflect reality, and the unfortunate reality is that ToString() can and does end up returning null.  We don't have a way to say "the base implementation won't return null but overrides might return null", so we're left with it being nullable on the base.

See https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md#virtualabstract-methods-and-interfaces for more details.
