### ISSUE TITLE
`CharUnicodeInfo.GetBidiCategory(String, Int32)` returns enumeration value that is not listed

### ISSUE THREAD

**Issue by Lotes** [dotnet/runtime#55511]
### Description

I need the (Unicode) bidirectional category for a character of a string (left-to-right or right-to-left, basically).
In [a tutorial](http://archives.miloush.net/michkap/archive/2007/01/06/1421178.html), this is accomplished by accessing the internal function `System.Globalization.CharUnicodeInfo.GetBidiCategory(String, Int32)` using reflection.

If you execute the following code, the return value of several calls will output a `64` instead of a valid enum value that is listed in the internal enumeration.
```csharp
using System;
using System.Globalization;
using System.Reflection;

namespace ConsoleApp4
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var st = "Hello!\r\nשלום!";
            var typeCharUnicodeInfo = Type.GetType("System.Globalization.CharUnicodeInfo");
            var bf = BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance | BindingFlags.InvokeMethod;
            var getBidiCategory = typeCharUnicodeInfo.GetMethod("GetBidiCategory", bf, null, new []{typeof(string), typeof(int)}, null);

            for (var ich = 0; ich < st.Length; ich++)
            {
                var parameters = new object[2] {st, ich};

                var o = getBidiCategory.Invoke(typeCharUnicodeInfo, bf, null, parameters, CultureInfo.InvariantCulture);

                Console.WriteLine("U+" + ((ushort) st[ich]).ToString("x4") + "    " + o.GetType() + "    " + o);
            }
        }
    }
}
```
But what I actually inspect is a value like "RightToLeft".

My target platform is `net5.0`.

It is not urgent, just an entry in your tracking system.
I can also compute the information on my own with this [file here](https://www.unicode.org/Public/UNIDATA/extracted/DerivedBidiClass.txt).

**Comment by GrabYourPitchforks** [comment]
This code sample uses private reflection into an internal runtime routine and is not supported. In .NET 5.0+, the definition of the internal enum changed so that "left to right" and "right to left" are the only valid options. [See here](https://github.com/dotnet/runtime/blob/4c92aef2b08f9c4374c520e7e664a44f1ad8ce56/src/libraries/System.Private.CoreLib/src/System/Globalization/StrongBidiCategory.cs) for more information.

@tarekgh The definitions in _StrongBidiCategory.cs_ (linked above) are incorrect. The enum values should probably be `0x20` and `0x40` (_not_ `0x10` and `0x20`), since the bidi information is contained [in bits 5 and 6](https://github.com/dotnet/runtime/blob/4c92aef2b08f9c4374c520e7e664a44f1ad8ce56/src/coreclr/System.Private.CoreLib/Tools/GenUnicodeProp/CategoryCasingInfo.cs#L76-L88). That we don't have unit test failures for this makes me think we don't have sufficient test coverage. The primarily consumer of this internal API is the `System.Uri` class.

**Comment by tarekgh** [comment]
@GrabYourPitchforks I have submitted the PR https://github.com/dotnet/runtime/pull/55790 to fix the issue. The good news is the BiDi category is used only inside IdnMapping code which is used only in Globalization Invariant Mode. IdnMapping is not perfect anyway in this way because we don't support string normalization because it needs to carry big size of data. So, this BiDi category is needed only for Globalization Invariant Mode.

@Lotes thanks for reporting the issue. Although I submitted the fix, it is not good idea to take dependency on internal APIs. For now, your work around carrying your own data is reasonable. We may in the future we expose that publicly.
