### ISSUE TITLE
Provide better json support for servers don't support chunked request body (re-open)

### ISSUE THREAD

**Issue by doggy8088** [dotnet/runtime#55583]
Refer to https://github.com/dotnet/runtime/issues/49357

As the issue #49357 been closed due to [this comment](https://github.com/dotnet/runtime/issues/49357#issuecomment-825656890):

> Given there is no detail about wide-spread server usage with chunked encoding disabled / not working, we should close this until more evidence appears.

I have to say the **Azure Logic App** HTTP trigger doesn't support "chunked encoding".  In [Handle large messages with chunking in Azure Logic Apps](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-handle-large-messages#set-up-chunking-over-http?WT.mc_id=DT-MVP-4015686) doc, it says:

> Logic App triggers don't support chunking because of the increased overhead of exchanging multiple messages.

I was trying to POST a message to Azure Logic App with a HTTP trigger.  It because HttpClient's `PostAsJsonAsync` ONLY support chunked encoding by default. I know what @davidfowl said **not recommend buffering for large JSON payloads**, but most of the payload to the Azure Logic App are really small. I think it should have an straightforward option to use `PostAsJsonAsync` without chunked encoding.

**Comment by davidfowl** [comment]
The workaround looks pretty good:

```C#
var content = JsonContent.Create<T>(json);
await content.LoadIntoBufferAsync();
var response = await httpClient.PostAsync(url, content);
```

**Comment by doggy8088** [comment]
I agreed. I think this should be documented somewhere.

**Comment by karelz** [comment]
Triage: This is general problem that the server is violating HTTP spec and does not support chunking.
Above is a workaround how to trick HttpClient into NOT sending chunking.

We believe that this issue is currently good enough documentation. We won't update official docs, unless we have few more reports. If you run into this, please upvote to post, or create new issue and link this one (if this one is locked by then).

@doggy8088 can you please file an issue against `Azure Logic App` service? They should be aware and primarily make their server compliant.

**Comment by doggy8088** [comment]
@karelz  I can only find out there is an UserVoice item here: https://feedback.azure.com/forums/287593-logic-apps/suggestions/33616297-implement-chunked-transfer-encoding-inside-logic-a
