### ISSUE TITLE
Pending cleanup in tests/run.cmd

### ISSUE THREAD

**Issue by cw2** [dotnet/runtime#55628]
### Description

It seems that `__RootBinDir` in src/tests/run.cmd is configured to artifacts directory outside the repository:
https://github.com/dotnet/runtime/blob/5b0c6dd5756eea63a57b1f69b182f7386da0f631/src/tests/run.cmd#L18

Unless, of course, it is a desired behavior, I would assume the path to the artifacts directory to be the same as configured in similar scripts, such as build.cmd:
https://github.com/dotnet/runtime/blob/5b0c6dd5756eea63a57b1f69b182f7386da0f631/src/tests/build.cmd#L31

### Configuration

Windows 10 x64

**Comment by cw2** [comment]
I just forgot to mention that if it really was a bug I would be glad to contribute the fix.

**Comment by cw2** [comment]
Closing (no feedback in almost a week).

**Comment by hoyosjs** [comment]
Did you see any case where this was at actual fault? Reviewing that script, I am not sure we touch anything past `SetupMSBuildAndCallRuntestProj`. @trylek maybe this is dead code in the scripts? @dotnet/jit-contrib are you aware of any workflows that touch beyond the invocation to MSBuild and the vars XunitTestBinBase and XunitTestReportDirBase?

**Comment by cw2** [comment]
> Did you see any case where this was at actual fault?

Well, in my scenario it was not an actual fault (although I think not having write permission to the outside artifacts folder would cause at least some errors) - I was running tests in runtimelab/feature/NativeAOT branch and it creates `artifacts\tests\coreclr\windows.x64.Debug\Reports` one level above the repository root. Setting `__RootBinDir` value to `%__RepoRootDir%\artifacts` seems to use the correct location (for the ... Reports folder).

Because all derived repos merge from the main, I thought the potential fix in main will automagically propagate (instead of fixing in derived repo and then request cherry-pick to main). Unfortunately, I have not yet had a chance to check, whether the Reports folder gets misplaced also in the main (this) repo.

**Comment by BruceForstall** [comment]
I agree with @hoyosjs that this issue is probably due to moving the tests up a level.

There appears to be a LOT of dead code in run.cmd now. E.g., the `:SetupMSBuildAndCallRuntestProj` label appears to be dead, and everything it calls. There's a comment `REM We are not running in the official build scenario, call run.py`; apparently at some point there was an "official build path" scenario that used it, but that must be gone now.

It's certainly unclear who uses `__RootBinDir`, as it's impossible to see who uses the derived `__BinDir`/`__TestWorkingDir`/`XunitTestBinBase`/`XunitTestReportDirBase`.

**Comment by trylek** [comment]
Interesting, it seems to me that the two environment variables derived from the <code>__RootBinDir</code> are not that heavily used in the script - <code>__BinDir</code> is supposed to populate <code>CORE_ROOT</code> with product binaries but the test build script does that in the <code>generatelayout</code> phase and <code>__TestWorkingDir</code> is only used to clean up pre-existing R2R ni binaries; its incorrect functionality may constitute a factor in the perceived unwanted test build incrementalism where in subsequent runs Crossgen / Crossgen2 is not invoked. It would be certainly beneficial if @cw2 was willing to clean this up.

**Comment by cw2** [comment]
I am willing to clean that up, but I don't know exactly what can be removed... for example, `XunitTestReportDirBase` is used at https://github.com/dotnet/runtime/blob/913facdca8b04cc674163e31a7650ef6868a7d5b/src/tests/run.proj#L215 `XunitTestBinBase` is referenced from multiple locations including https://github.com/dotnet/runtime/blob/913facdca8b04cc674163e31a7650ef6868a7d5b/src/coreclr/tools/r2rtest/TestExclusion.cs#L164 or https://github.com/dotnet/runtime/blob/913facdca8b04cc674163e31a7650ef6868a7d5b/src/tests/build.cmd#L152

**Comment by BruceForstall** [comment]
Maybe you could just change `__RootBinDir` for now, and we could leave a bigger cleanup for later (or never)?

Even if we didn't remove setting the Xunit variables, there's a comment in run.cmd asking who uses them, and if setting them is required, and updating those comments would be useful to the next viewer.

It's impressive you found the run.proj case; GitHub's search didn't find it, presumably because the `%22` throw off tokenized searches.

**Comment by trylek** [comment]
I think the easiest way of fixing this is by redefining <code>__RootBinDir</code> based on <code>__RepoRootDir</code> instead of open-coding the folder tree ascent that was only relevant during the actual process of repo integration by the end of 2019.

**Comment by hoyosjs** [comment]
Changed the title as @cw2 submitted a PR to mitigate the paths-off-root issue
