### ISSUE TITLE
 int __stdcall  fncp1(int a,int b)  can be  invoke suceess  when  CallingConvention = CallingConvention.StdCall

### ISSUE THREAD

**Issue by gitlsl** [dotnet/runtime#55631]
### Description
````
c++  code
extern "C"  CP1_API int __cdecl  fncp2(int a, int b)
{
	return a * b;
}

c# code
[DllImport(@"cp1.dll", CallingConvention = CallingConvention.StdCall)]
 extern static int fncp2(int a, int b );
````

In my opinion, there should be an exception when invoke fncp2(4,5), but it work fine  as expected  return 20? It shouldn't be！
I change `CallingConvention = CallingConvention.Cdecl` ,     return 20 also

 

### Configuration

net core 5.0.7  win10 x64  vs2019

**Comment by huoyaoyuan** [comment]
For x86, calling convention matters. However for x64, they are unified and doesn't differ. You can test your code in x86 to see if I'm correct.

**Comment by gitlsl** [comment]
@huoyaoyuan  my program is  32bit ,  我dll跟c#程序都 32位的，不应该啊？

**Comment by huoyaoyuan** [comment]
https://godbolt.org/z/1bsb4K5G4

I have no idea. The code does differ for call convention.

**Comment by jkoritzinsky** [comment]
@gitsl Due to a variety of reasons, we cannot detect the mismatched calling convention easily. Specifically, since `__stdcall` entrypoints have [name mangling](https://en.wikipedia.org/wiki/Name_mangling#C), .NET provides a feature that allows you to specify the non-mangled name for stdcall `DllImport` entry points. First the runtime tries to resolve the name as given (since a number of linker scripts manually define the exported name as the simple name), and then it mangles it. Since `__cdecl` uses the unmangled name as the export, the runtime looks up the entry-point with the wrong calling convention and uses it.

Since `__cdecl` and `__stdcall` use the same mechanism for passing parameters, the result seems to be write, but the stack is will be imbalanced.

**Comment by huoyaoyuan** [comment]
> but the stack is will be imbalanced.

I think the question should be that why imbalanced call stack not causing crash? It is because the caller code is too simple that doesn't touch stack any more?

**Comment by jkoritzinsky** [comment]
It depends on how the JIT sets up the calling frame. If it uses a stack-pointer-based frame, the the imbalance would cause issues. However, the JIT uses a frame-pointer-based layout in many cases, which ends up not being affected by a stack imbalance. Additionally, if the caller doesn't use the stack, the stack imbalance could be missed.

**Comment by elinor-fung** [comment]
@gitlsl Does @jkoritzinsky's explanation answer your question?

**Comment by gitlsl** [comment]
@elinor-fung  yes, I understand
