### ISSUE TITLE
[QUIC] MsQuic packaging

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55639]
#### Windows:
  - [x] lack of automation to flow msquic to runtime (darc/maestro) (dotnet/runtime - 6.0)
  - [ ] employ win preview images in runtime CI pipeline --> depends on https://github.com/dotnet/core-eng/issues/13582 (external)

#### Linux:
  - [x] automation to sign and publish to packages.microsoft.com (dotnet/msquic - 6.0)
  - [x] use msquic preloaded docker images in runtime CI pipeline
  - [x] use as many as possible docker images to run CI (7.0)

#### Miscellaneous:
  - **versioning needs to be more granular than 1.5.0 we have now, to actually push package updates 6.0 :exclamation:** (dotnet/msquic - 6.0) - @wfurt
    - [ ] 6.0 servicing - document "How to check if msquic version was bumped and if not, how to bump it" - @wfurt
    - [ ] 7.0 - automation with bumps in numbers from dotnet/msquic
  - [x] missing package description
  - [x] **separate crypto functions from baked in SSL and add dependency to the package - security 6.0 :exclamation:** - @ManickaP --> https://github.com/dotnet/msquic/pull/31
  - [x] **branching and versioning post 6.0 branch = main becoming 7.0 6.0 :exclamation:** - infra help needed, post 6.0 branching (dotnet/msquic - 6.0)
  - [ ] for single file host we'll need to link msquic statically into runtime, see discussion in https://github.com/dotnet/runtime/pull/55607 (7.0)
  - [ ] build packages with Debug MsQuic and use them in Debug builds and stress (7.0)

:warning: **If the work on the item is non-trivial, please create a separate issue and link it here, don't spam this issue with details.**

cc: @wfurt @karelz

**Comment by wfurt** [comment]
For separate crypto we should use `UseSystemOpenSSLCrypto` for the build script or` QUIC_USE_SYSTEM_LIBCRYPTO` wit cmake

**Comment by ManickaP** [comment]
Triage: Identified 3 tasks that should be done within 6.0 time frame, marked bold, rest can be punted.

**Comment by wfurt** [comment]
I think versioning is good enough for 6.0. We used 1.6.0 and 1.7.0 recently. We can use the last digit for any minor or security fixes. 
The tricky part is 7.0 when we may want to consume main branch of Microsoft/msquic more frequently. Since that is running branch there are no versioning updates. That is ok for Windows since we publish NuGet with specific number but there is no good way how communicate that for Linux packages unless we add something to MsQuic's version.
While this was not original plan, current Fedora docker image is consuming msquic by building this repo instead of fetching pre-built package. That bypassed our dependency on automatic publishing but at the end it will not test what customers are using and it may leave us blind too class of problems. But it still may be acceptable if we use it only for main branch of runtime.

**Comment by karelz** [comment]
Triage: Let's hear a simple story what needs to happen where and when from @wfurt next week in HTTP/3 sync.

**Comment by wfurt** [comment]
closing as we have flow Windows packages (x64, x86 and arm64) and final Linux packages are signed and published by MsQuic pipeline.
We maintain dotnet/msquic fork to be able consume development msquic updates
