### ISSUE TITLE
GZipStream regression - Worse compression in .NET 5 vs. .NET Framework

### ISSUE THREAD

**Issue by Lizzy-Gallagher** [dotnet/runtime#55754]
## Expected behaviour
To produce identical compressed result for the same original byte array on .NET Framework and .NET 5 (or more compressed in .NET 5).

## Actual behaviour
Results of GZipStream on .NET Framework and .NET 5 are different.

## Repro
```
var text = "non-ASCII Latin characters";

using (var memoryStream = new MemoryStream())
{
	using (var writer = new StreamWriter(new GZipStream(memoryStream, CompressionMode.Compress), new UnicodeEncoding(bigEndian: false, byteOrderMark: false)))
	{
		writer.Write(text);
	}

        // 64 bytes in .NET Framework
        // 70 bytes in .NET 5
	var length = memoryStream.ToArray().Length;
}
```

I have seen this with a variety of other short text snippets (this came up in a unit test, so I only have very small snippets) include samples with ASCII-only text, emoji-only text, and non-ASCII latin characters.

## Related issues
I found https://github.com/dotnet/runtime/issues/28235, but it appeared to have been "fixed" in .NET Core 3, and I can repro this in .NET 5.

**Comment by danmoseley** [comment]
What about if you specify CompressionLevel. SmallestSize?

**Comment by adamsitnik** [comment]
> What about if you specify CompressionLevel. SmallestSize?

I can repro it for `CompressionLevel.Optimal`.  I've repeated the string content 10_000 times and I can see that the compressed content size is almost two times bigger for all .NET Core versions:

<details>

```cs
using System;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace compression_size
{
    class Program
    {
        static void Main()
        {
            var text = new StringBuilder().Insert(0, "non-ASCII Latin characters", 10_000).ToString();

            using (var memoryStream = new MemoryStream())
            {
                using (var writer = new StreamWriter(new GZipStream(memoryStream, CompressionLevel.Optimal), new UnicodeEncoding(bigEndian: false, byteOrderMark: false)))
                {
                    writer.Write(text);
                }

                Console.WriteLine(memoryStream.ToArray().Length);
            }
        }
    }
}
```

</details>

```log
PS C:\Projects\repros\compression_size> dotnet run -f net48
1593
PS C:\Projects\repros\compression_size> dotnet run -f netcoreapp2.1
3974
PS C:\Projects\repros\compression_size> dotnet run -f netcoreapp3.1
3353
PS C:\Projects\repros\compression_size> dotnet run -f net5.0
3353
PS C:\Projects\repros\compression_size> dotnet run -f net6.0
3353
```

@ericstj do you know why is that? I am not very familiar with `System.IO.Compression` yet

**Comment by ericstj** [comment]
We use a different GZip than .NETFramework, with optimizations that help in a lot of common scenarios.  This was based on research scenarios from intel and contributed early in .NETCore 1.x.  There are some scenarios (like all zeros) that do worse under `Optimal` levels.  In the past we have worked with @jtkukunas to update https://github.com/jtkukunas/zlib if we feel the differences represent a bug.  Be careful measuring fake content as you could be biasing the algorithm for non-representative data. Compression algorithms are better measured using real data or industry standard compression test corpus data.

Make sure you test As @danmoseley suggests https://github.com/dotnet/runtime/issues/55754#issuecomment-881838503 since this more closely represents “best size”.  Optimal represents a tradeoff of size/perf.

**Comment by adamsitnik** [comment]
@ericstj big thanks for your reply!

@Lizzy-Gallagher Since we have done that on purpose and for good reasons, I am going to close the issue. Thanks!

**Comment by ericstj** [comment]
For very small text segments like this where perf isn’t as important but you want smaller sizes, try `CompressionLevel.SmallestSize`
