### ISSUE TITLE
Saving PixelFormat.Format16bppGrayScale is not supported

### ISSUE THREAD

**Issue by twsl** [dotnet/runtime#55854]
### Description

```
byte[] data = new byte[] {..........};
var b = new Bitmap(Width, Height, PixelFormat.Format16bppGrayScale);
var boundsRect = new Rectangle(0, 0, Width, Height);
BitmapData bmpData = b.LockBits(boundsRect, ImageLockMode.WriteOnly, b.PixelFormat);
int bytes = bmpData.Stride * b.Height;
Marshal.Copy(data, 0, bmpData.Scan0, bytes);
b.UnlockBits(bmpData);
b.Save("test.png", ImageFormat.Png);
```
I expect saving a PNG file with 16bit grayscale precission, yet it's causing an exception.

### Configuration

* Which version of .NET is the code running on? .NET 5.0
* What OS and version, and what distro if applicable? Windows 10, 20H2
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? -
* If you're using Blazor, which web browser(s) do you see this issue in? -

### Other information

System.Runtime.InteropServices.ExternalException: `A generic error occurred in GDI+.`
StackTrace:
```
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(String filename, ImageFormat format)
```

Culprit seems to be GDI+, yet I do expect the code to work nonetheless. Current Workaround is using Magick.NET's MagickImage instead of Bitmap.

This is important because many sensors save depth maps as 16bit grayscale images.

**Comment by danmoseley** [comment]
@twsl do you want to debug a little?

**Comment by twsl** [comment]
[Here](https://github.com/dotnet/runtime/blob/dfd618dc648ba9b11dd0f8034f78113d69f223cd/src/libraries/System.Drawing.Common/src/System/Drawing/Image.Windows.cs#L172) the pinvoke function [GdipSaveImageToFile](https://github.com/dotnet/runtime/blob/dfd618dc648ba9b11dd0f8034f78113d69f223cd/src/libraries/System.Drawing.Common/src/System/Drawing/GdiplusNative.Windows.cs#L222) is called and returns 1 (GenericError) instead of 0 (Ok) as status code. I am not able to debug native libraries.

**Comment by danmoseley** [comment]
Probably the next step is to eliminate System.Drawing by calling the pinvokes directly, or even just using C. If it's GDI+ there is little that can be done.

**Comment by twsl** [comment]
IMHO, the next step should be to eliminate GDI+ directly, if it doesnt support writing the full PNG spec.
Writing the file in C# only shouldn't be too hard.
Meanwhile, `Format16bppGrayScale` should be marked as depricated/obsolete to warn users and then removed as long as it doesnt support it.

**Comment by danmoseley** [comment]
System.Drawing will always be tightly coupled to GDI+: it was created as a managed API for GDI+, essentially. For new usage, we recommend modern libraries like ImageSharp and SkiaSharp.

I'm not sure I'm ready to mark this format as deprecated without knowing why it's failing. Eg., maybe it works on other Windows versions.

**Comment by hopperpl** [comment]
The Windows GDI+ PNG Encoder does not support 16-bit grayscale images. It never has, and never will. 

There are reports of that back in 2007, even 2005.. e.g. https://social.msdn.microsoft.com/Forums/en-US/10252c05-c4b6-49dc-b2a3-4c1396e2c3ab/writing-a-16bit-grayscale-image

The format exists for the TIFF encoder. Not all formats work with all encoders.

**Comment by danmoseley** [comment]
Thanks @hopperpl . In that case I think we can close this issue. Unless it is worth a custom error message for this case.

**Comment by hopperpl** [comment]
GDI+ since Windows 7 (I think) uses WIC (Windows Imaging Component) as backend for image decoding/encoding - but in a limited way. Additional installed WIC codecs are not exposed via GDI+, also the WIC codecs are very basic in functionality. 

For basic image processing it is fine. That is RGB 24-bit, or RGB-32 bit. All other formats almost always return invalid argument/call. I would use an external library that is specialized in image processing. And even for PNG/JPEG encoding, the GDI+/WIC encoders are sub-optimal. Also, on other platforms WIC is not available.

Personally, I don't think it is worth it to implement additional formats for the PNG encoder. Even thought the PNG is very simple, it is just zlib-over-raw-pixels (after pixel values are converted from absolute values to relative-change values). But with so many image formats, especially with so many raw formats of digital cameras, this can turn into a lot of maintenance work. And then there is no color correction and so on. Image processing is a huge topic and needs a specialized library.

**Comment by danmoseley** [comment]
I found this is documented. By following the doc for the flat API to Image.Save to the Graphics constructor
https://docs.microsoft.com/en-us/previous-versions//ms536159(v=vs.85)
I find

> This constructor also fails if the image uses one of the following pixel formats:
PixelFormatUndefined
PixelFormatDontCare
PixelFormat1bppIndexed
PixelFormat4bppIndexed
PixelFormat8bppIndexed
PixelFormat16bppGrayScale
PixelFormat16bppARGB1555

I'm going to close this. Thanks for the report though.
