### ISSUE TITLE
QUIC API: Consider passing QuicConnectionOptions to Quic.Connection.ConnectAsync

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#56009]
We have a somewhat awkward API pattern today, where you pass the QuicConnectionOptions object to to QuicConnection constructor, but we don't actually use it until you do ConnectAsync. One minor inconvenience of this is that we have to store the QuicConnectionOptions object for this brief period of time when we don't use it any other time.

We should consider passing these options into ConnectAsync instead, to simplify the model and implementation here.

**Comment by ManickaP** [comment]
Moreover, as @scalablecory mentioned in our discussion, we shouldn't create `QuicConnection` via constructor since that would prevent us from making the class abstract in the future - if we decide to provide the abstraction. Instead, we could have a static method `QuicConnection QuicConnection.ConnectAsync(QuicConnectionOptions options)` to construct and connect the connection in one go.

**Comment by ManickaP** [comment]
Closing as covered by https://github.com/dotnet/runtime/issues/68902 and https://github.com/dotnet/runtime/issues/70424
