### ISSUE TITLE
Remove limitation of one EventSource with same name/GUID per process 

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/runtime#56052]
There is currently a limitation in the EventSource implementation that prevents an EventSource with the same GUID from being instantiated in the same AppDomain.

When loading different versions of an assembly that contains an EventSource in different AssemblyLoadContext(s), an exception is raised when the second EventSource is instantiated.

This issue tracks the work required in the runtime/EventSource code to remove this limitation in .NET 6.

**Comment by stephentoub** [comment]
cc: @noahfalk, @brianrob

**Comment by noahfalk** [comment]
Based on offline discussion we are going to treat this issue as a servicing request back to 3.1, and optionally a servicing request for 6 depending if we are unable to get to it before things lock down.

**Comment by noahfalk** [comment]
@josalem - Given that I am likely to be OOF during the timeframe where we are trying to do this, I'm assigning it to you for now. Of course feel free to work with Tom and further load balance, but I am guessing you are the most likely person who winds up implementing it : )

**Comment by josalem** [comment]
As part of starting to look at this, I wanted to document a few thoughts that came to mind about this feature request:

* EventSources create native representations of themselves that get registered with EventPipe and ETW. If we break the restriction of their being only one provider for a given GUID will we be causing issues in these other systems? Does this increase the potential for a change like this to be breaking?
* Allowing 2 or more instances of an EventSource with a given GUID means that we could have multiple and potentially different states, e.g., manifest, metadata, calculated eventIDs, etc. What are the ramifications something like this would have on external tooling, e.g., PerfView or VS? If there are mismatched manifests between two instances of the same EventSource, will tooling receive both and which will take precedence?

I'm not opposed to making the change, but I felt it worth noting this may be a farther-reaching change than simply removing the if statement that leads to the exception. Event consumers like EventPipe and ETW make assumptions that we may be breaking here. I'll find out as part of working on this.

@brianrob are you aware of a historical reason that we restricted the number of EventSources?

**Comment by brianrob** [comment]
@josalem your questions here are great and definitely worth considering.  The primary reason for single instancing EventSources was that Vance was of the belief that you shouldn't need to create any more than one, and that creation of multiple was generally wrong from a performance perspective.  From that perspective, we have evolved the runtime such that now it is more likely to end up with the need for multiple instances.  Prior to AssemblyLoadContext, it was much harder to get into this situation.

The questions that you list above are valid, and you're right that it's definitely possible to create multiple EventSources with different events.  From ETW's perspective, this is all valid, and you're on your own.  We should decide where we want EventSource to come down on this.  As you point out, one situation that this does open up is the possibility that two poorly named EventSources from different assemblies are loaded into a process and they conflict with each other because we don't notice that there are two of them.  There are likely safety checks that we can put in to try and prevent this which could be worthwhile.

All in all, I agree that this is worth thinking through, and maybe there is a level of safety that we want to maintain here.

**Comment by noahfalk** [comment]
> maybe there is a level of safety that we want to maintain here

Fully agree that there are likely to be some ramifications to be explored. In terms of servicing my suggestion would be:
1. We should do some scenario validation / thinking about the code ourselves for any of the cases where we forsee potential trouble.
2. We should add an explicit opt-in config switch so that if our exploration in (1) missed some of the issues we have greatly limited which customers are impacted and those customers who did turn it on could always turn it back off in the worst case.

@josalem - priority-wise I'd focus on the other 6.0 bugs first. If this falls after the deadline we can take it through servicing instead.
