### ISSUE TITLE
Test_BadEventSource_MismatchedIds failing on CI

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#56279]
Can't create tracking issue, see: https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Aruntime+name%3ATest_BadEventSource_MismatchedIds

cc: @dotnet/dotnet-diag

**Comment by josalem** [comment]
Is there any way to see timestamps in the runfo data? When did this start failing?

**Comment by josalem** [comment]
https://github.com/dotnet/runtime/blob/0c200955af77bf17cd05488db96d3cdb3716a16c/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsUserErrors.cs#L136

@noahfalk did anything change in the activity ID generation logic recently? I'll go take a look at the error path for this.

The test is expecting an error to be generated because the `EventSource` has a mismatched ID in the `WriteEvent` call, e.g., 

```csharp
public void Event1() => WriteEvent(1, "foo");
public void Event2() => WriteEvent(1, "foo");
```

The test seems to be passing until it checks some of the details on the event that came in. The error message is correct, but it is expecting empty GUIDs rather than the activity IDs it is getting.

**Comment by hoyosjs** [comment]
This is odd. Looks like before 7/15 they were failing in another way. After that it's the guid mismatch. That seems to match https://github.com/dotnet/runtime/pull/55625

[Query](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA01OTUvDQBC9+yuG0EMFLYLnCgoKESKoBY9l3HkmW5Md2ZlYBH+8G2Opx/f9NjB/go29G518075DBjXwToXWa6o2Rd/esNx+Ivmzjjlg20Qb2EMHqcUq4iQ0V/wm7jj2M9nAjFtQ0OQck1F1bYbsVRmSaB5TcLrX1wcecEYvmt9rxzCjv2xx7jQmWh5Uo8PJxxEjhK6IW11eXshpUT6y7hD8nPf8NTXXcuyti0PTcW/R481X/1en+4sc285XE/wBDul/pRsBAAA=)
```sql
TestResults 
| where Method == "Test_BadEventSource_MismatchedIds" and Result == "Fail" and Message contains "Assert"
| distinct JobName, WorkItemName, Message
| join (WorkItems | where Queued > ago(30d) | project-away JobId, WorkItemId) on JobName, $left.WorkItemName == $right.Name
```

**Comment by noahfalk** [comment]
The only change I know of that directly modified ActivityIDs was #55625 that Juan mentioned. It is also possible that something changed in the test harness to create additional activities, or something changed in the logging to enable the TPL provider (which causes activity ID tracking to be enabled). 

The test doesn't appear to take any steps to prevent ambient activity IDs from being present so I'd consider this a test bug, fixable by either eliminating the check or setting the expected value to EventSource.CurrentThreadActivityID.
