### ISSUE TITLE
[mono] iOS - Size reduction: many more corelib symbols are materialized/AOT compiled in netcore compared to legacy Mono

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#56385]
### Original description

Seen while investigating [size differences between legacy Mono and netcore Mono](https://github.com/xamarin/xamarin-macios/issues/10249#issuecomment-868195729) when used for iOS.

More details are forthcoming--and P7 apparently generates larger binaries than P6. A tsv containing size information for the P6 singleview app is available here: https://github.com/xamarin/xamarin-macios/issues/10249#issuecomment-876454078

I'll provide P7 and legacy (for comparison) breakdowns soon.

### Curent state

We continued to investigate the size reduction issue in .NET 7 and identified the following work items to reflect the problem:
-  https://github.com/dotnet/runtime/issues/71430
-  https://github.com/dotnet/runtime/issues/71431
-  https://github.com/dotnet/runtime/issues/71482

**Comment by SamMonoRT** [comment]
We'll keep working on this, but nothing concrete is expected to be checked in the 6.0.0 timeframe. Moving to 7.0.0

**Comment by imhameed** [comment]
This is mostly a note to myself to do more followup work. I don't know why the .NET core corelib is resulting in twice as much stuff being compiled.

**Comment by imhameed** [comment]
@eerhardt Do you have any suggestions or ideas on what might be causing the increase in CoreLib size, or any pointers for directions to go when investigating? As far as I know we're doing some .NET-level dead code elimination via the managed linker, but I have no firsthand experience with this tool.

**Comment by eerhardt** [comment]
One easy way to investigate is to use something like ILSpy to look into both assemblies to see what's in both. However, diffing is hard here because it doesn't diff assemblies. So you'd be able to spot high-level things using this method.

Another approach I've used in the past is to use the API reviewer tool - \\fxcore\tools\ApiReviewer.lnk. This allows you to diff the APIs of assemblies, including `internal` classes and methods. This can pretty quickly spot where the differences between two assemblies are based on internal types.

Other tools that can be used to investigate where IL size is being used:

https://github.com/dotnet/linker/tree/main/src/analyzer
https://github.com/dotnet/linker/tree/main/src/tlens

**Comment by ivanpovazan** [comment]
After some further analysis the following stats have been gathered by comparing:

- dotnet - version`6.0.301-rtm.22263.15` and 
- legacy mono - version `6.12.0` (later referenced as `oldnet`)

builds of `MySingleView` app on iOS.

### Analysis
[bloaty](https://github.com/google/bloaty) was used to generate symbols from both binaries respectively:

- for `dotnet`
``` bash
bloaty -d segments,sections,symbols --debug-file=dotnet/bin/iPhone/Release/net6.0-ios/ios-arm64/MySingleView.app.dSYM/Contents/Resources/DWARF/MySingleView dotnet/bin/iPhone/Release/net6.0-ios/ios-arm64/MySingleView.app/MySingleView -n 0 --tsv > ../logs/dotnet_symbols.list
```

- for `oldnet`

``` bash
bloaty -d segments,sections,symbols --debug-file=oldnet/bin/iPhone/Release/MySingleView.app.dSYM/Contents/Resources/DWARF/MySingleView oldnet/bin/iPhone/Release/MySingleView.app/MySingleView -n 0 --tsv > ../logs/oldnet_symbols.list
```

Bloaty outputs were then further broken down by a [script](https://gist.github.com/ivanpovazan/8f19dd741a467091c71a88a10b7971fd) for easier analysis of the `__text` section:

- [dotnet_all_symbols_report](https://gist.github.com/ivanpovazan/85d0a3fd615fa463417297b09dc700a9)
- [dotnet_generics_sorted_by_name_report](https://gist.github.com/ivanpovazan/781c7fe70a3f5fb7a5a17b2eeaf82e11)
- [dotnet_generics_sorted_by_size_report](https://gist.github.com/ivanpovazan/36467b83e2bf7e4ea4730e68fb030f6c)
- [oldnet_all_symbols_report](https://gist.github.com/ivanpovazan/c448cf9d3163bfc7ea7dc39b3daf585b)
- [oldnet_generics_sorted_by_name_report](https://gist.github.com/ivanpovazan/0dc1851ecb7ed8ed0ae13646a9dba647)
- [oldnet_generics_soerted_by_size_report](https://gist.github.com/ivanpovazan/28472aad0f7467c769c1d405c31d3af0)

### Observation

What can be observed from the generated reports is that there are many more symbols in the `__text` section in the `dotnet` variant:

-   Total symbols: `28602 -> 16131 (+77%)`
-   Total size: `5430112 -> 2952832 (+84%)`

 However, after inspecting just generic methods it can be seen that there a following difference:
 
-   Total symbols: `2324 -> 1364 (+70%)`
-   Total size:  `750544 -> 362040 (+107%)`

Since generics take around %13 of the total app size, I was wondering whether some optimisations mentioned [here](https://www.mono-project.com/docs/advanced/runtime/docs/gsharedvt/#possible-future-work) (especially the point regarding usage of gsharedvt versions of a method) could help reduce the app size. 

@vargaz what do you think?

**Comment by ivanpovazan** [comment]
Mostly note to myself.

Further analysis has been performed on the output generated by `bloaty` as described in my previous comment by running [script](https://gist.github.com/ivanpovazan/8f19dd741a467091c71a88a10b7971fd)

The script reads the bloaty `dotnet` and `oldnet` reports and processes their symbols by:
- categorising them into:
    - `CORLIB` - Symbols from: `System.Private.CoreLib` (and `mscorlib` - mapped)
    - `MONLIB` - Symbols from: `mono` (which start with mono prefix or come from /mono/ path)
    - `SYSIOS` - Symbols from: `Microsoft.iOS` (or `Xamarin.iOS` - mapped) 
    - `OTHERS` - Symbols not from any of the above
- sorting them by name in each of the categories
- diffing symbols between `dotnet` and `oldnet` for all categories except `OTHERS` (too much noise)
- generating diff reports

Diff reports include symbols that are new in `dotnet` and are sorted by size (decreasing) and can be found here:
- [diff_CORLIB](https://gist.github.com/ivanpovazan/60d69c423e31476d4c5bc86804919f33) (additionally includes breakdown by `System.Private.CoreLib` namespace at the end of the report)
- [diff_MONLIB](https://gist.github.com/ivanpovazan/78956439116e7313c44765a891775c09)
- [diff_SYSIOS](https://gist.github.com/ivanpovazan/8d4ff19223db920b3321f0fcb6bda914) 

Most interesting one is `CORLIB` category (and its namespace breakdown section) which shows candidates for further investigation .

**Comment by marek-safar** [comment]
@ivanpovazan which runtime version is this using? There are many methods which I cannot find in main.

**Comment by ivanpovazan** [comment]
@marek-safar 6.0.301-rtm.22263.15 version was used for these measurements (xamarin repo configuration)

**Comment by ivanpovazan** [comment]
Here is the first comparison report comparing legacy with .NET 7 Mono for `MySingleView` app.
Compared versions:
- Legacy Mono - `v6.12.0` 
- .NET Mono - `v7.0.100-preview.5.22274.9`

New diff reports (generated as described in previous comments) and can be found here:
- [diff_CORLIB](https://gist.github.com/ivanpovazan/3e7a6d384576fa3bfce2d6fc4b2c62aa)
- [diff_MONLIB](https://gist.github.com/ivanpovazan/d26d1c8f27eca372217d941863d9518f)
- [diff_SYSIOS](https://gist.github.com/ivanpovazan/ef4af7d80601e2f7388f47290d461d4f)

**Comment by vargaz** [comment]
The Scalar class is used to implement the fallback code for the vector classes, and Scalar<GSHAREDVT> are the gsharedvt versions of these methods. The code in Scalar<T> is designed to be specialized, so the gsharedvt versions are very large/slow.

**Comment by marek-safar** [comment]
> The code in Scalar is designed to be specialized, so the gsharedvt versions are very large/slow.

The code handles only primitive types, everything else throws NotSupportedException. I'm not sure how to best handle this but gsharedvt version should not exist at all or always throw.

**Comment by ivanpovazan** [comment]
@marek-safar, agreed.
After discussions with @lambdageek and @vargaz there two paths to tackle this problem. 
I have opened the issues:
#71430 
#71431 
which would try to minimize and prevent generation of unnecessary `GSHAREDVTs`.

**Comment by ivanpovazan** [comment]
Closing this issue as it is outdated and all 3 dependent tasks have been move to the newer - .NET8 tracking issue: https://github.com/dotnet/runtime/issues/80938
