### ISSUE TITLE
Missing prerequisite for dotnet on Alpine

### ISSUE THREAD

**Issue by alyssajotice** [dotnet/runtime#56422]
### Description

I am on the Live Share team and I am trying to troubleshoot running Live Share on [Alpine v3.13 WSL in VS Code](https://github.com/MicrosoftDocs/live-share/issues/4328). I've downloaded all of the dependencies noted here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies.

I think that there may be a missing dependency for dotnet in Alpine that is not listed in the docs. The Live Share extension does not successfully activate, which indicates a missing dependency. When I navigate to the `vsls-agent` executable, it says "file not found" when I try to run it, even though it is in the directory. Running the `strings` command yields the following result. 

```
Using environment variable %s=[%s] as runtime location.
Using global installation location [%s] as runtime location.
A fatal error occurred, the default install location cannot be obtained.
 or register the runtime location in [
A fatal error occurred. The required library %s could not be found.
If this is a self-contained application, that library should exist in [%s].
If this is a framework-dependent application, install the runtime in the global location [%s] or use the %s environment variable to specify the runtime location%s.
The .NET Core runtime can be found at:
  - %s
A fatal error occurred. The folder [%s] does not exist
```

After this, I tried to download dotnet. I followed the instructions here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install and used the script. When navigating to where dotnet is installed, it still says that dotnet is not found. Running strings on the executable resulted in a message about a missing prerequisite. 

```hostfxr_main_bundle_startupinfo
hostfxr_set_error_writer
hostfxr_main
The library %s was found, but loading it from %s failed
libhostfxr.so
  - Installing .NET prerequisites might help resolve this problem.
     %s
https://go.microsoft.com/fwlink/?linkid=2063370
COREHOST_TRACE
Tracing enabled @ %s
COREHOST_TRACEFILE
COREHOST_TRACE_VERBOSITY
Unable to open COREHOST_TRACEFILE=%s for writing
libcoreclr.so
Checking if CoreCLR path exists=[%s]
DOTNET_RUNTIME_ID
DOTNET_SHARED_STORE
store
```

**Comment by am11** [comment]
[`strings(1)`](https://www.man7.org/linux/man-pages/man1/strings.1.html) just prints whatever is in a given file. It does not actually invoke the executable, but shows the contents of file as text.

Note that Visual Studio Code is not available for Alpine Linux (desktop) natively*, because the underlying framework electron is not available on Alpine Linux. It is possible that Visual Studio Live Share (VS Code extension) is also not compatible with Alpine Linux which is why the binary loader is rejecting it.

<sub>\* I use VSCode via flatpak sandbox on Alpine Linux Desktop on a laptop ([baremetal](https://github.com/am11/LRAP/blob/c82fc2f7755c34aaccfcf0b07b849b735386eb42/install.sh#L166-L169)) just because it's not natively available for alpine or musl-libc in general</sub>

**Comment by vitek-karas** [comment]
I can't comment on the VS Live Share, but dotnet should work on Alpine Linux.
Can you please try to download the right binaries from here: https://dotnet.microsoft.com/download/dotnet/5.0 and try to run `dotnet` that way?
(It's possible that the `dotnet-install.sh` doesn't correctly handle Alpine).

**Comment by alyssajotice** [comment]
I solved this problem by running the following command on the executable: `ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2` 

https://github.com/MicrosoftDocs/live-share/issues/4328#issuecomment-899595665

I'll close the issue.
