### ISSUE TITLE
[API Proposal]: JsonNode.FromObject(object obj, JsonSerializerOptions? options = null)

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#56514]
### Background and motivation

Api compare to [JToken.FromObject(object o)](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JToken.cs#L1912)

Current:
``` C#
var node = JsonNode.Parse(JsonSerializer.Serialize(obj));
```

### API Proposal

```C#
namespace System.Text.Json.Nodes
{
     public class JsonNode
     {
           public static JsonNode? FromObject(object obj, JsonSerializerOptions? options = null);
     }
}
```     

### API Usage

```C#
// Fancy the value
var obj = new SomeClass();

var node = JsonNode.FromObject(obj);
```

**Comment by eiriktsarpalis** [comment]
Have you tried using the [`JsonNode.Create`](https://github.com/dotnet/runtime/blob/742ea07eff4ae09efd748ba94f96e536e0a274d0/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonValue.cs#L31) method? cc @steveharter

**Comment by steveharter** [comment]
Note there are new [JsonSerializer methods](https://github.com/dotnet/runtime/issues/31274) that allow conversions between objects and `JsonNode` for both serialize and deserialize. These were also added to `JsonElement` and `JsonDocument`.

So instead of
```cs
JsonNode node = JsonNode.Parse(JsonSerializer.Serialize(obj));
```

you can now do:
```cs
JsonNode node = JsonSerializer.SerializeToNode(obj);
```

Also, if you just want to serialize an existing CLR object (whether a primitive, object or collection) within a `JsonNode` graph, you can use `JsonValue.Create` for performance which avoids an extra serialize-object-to-json and deserialize-json-to-node:
```cs
JsonNode node = JsonValue.Create(obj);
// the node instance holds onto `obj` which will be serialized when the node is serialized.
string json = node.ToJsonString();
```
