### ISSUE TITLE
Any chance to support Microsoft.Extensions.Logging on .NET Framework 4.5.2?

### ISSUE THREAD

**Issue by Snipx** [dotnet/runtime#56539]
Hi, thanks for all your hard work!
I've been wondering about the possibility to support Microsoft.Extensions.Logging on .NET Framework 4.5.2 - would it be possible and is it planned? I [see](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework) that version 4.5.2 is still supported till April 26, 2022. We are building a .NET library and we aim to support .NET Framework versions that Microsoft still officially supports and we want to migrate to Microsoft.Extensions.Logging but the fact that it's only available from .NET Framework 4.6.1 is a big hurdle now. 

Any thoughts on this? Thanks a lot!

**Comment by teo-tsirpanis** [comment]
Hello, judging from dotnet/announcements#190, supporting .NET Framework 4.5.2 is pretty unlikely.

A supported framework does not necessarily mean that people should write new code targeting it, otherwise we would still write code that targets .NET Framework 3.5 which is supported until 2028. And April 2022 is not a long time; it's less than a year.

**Comment by eerhardt** [comment]
We don't plan on adding support for frameworks older than  .NET Framework 4.6.1. See https://github.com/dotnet/announcements/issues/190.

Note it wouldn't just be Logging that would need a `net452` target. We would need to change all of its dependencies as well to support that TFM. For example:

* Microsoft.Bcl.AsyncInterfaces
* Microsoft.Extensions.DependencyInjection
* Microsoft.Extensions.Options
