### ISSUE TITLE
Hash code and equality broken when marshalling COM EXEs objects between apartments

### ISSUE THREAD

**Issue by forderud** [dotnet/runtime#56701]
### Description
The `GetHashCode`, `Equals` and `==` methods appear to break when marshalling COM EXE objects between threads running in separate apartments. This prevents me from being able to detect references to the same COM object across apartments.

### Minimal reproducer
Reproducer to demonstrate how the hash code changes and equality operators break after marshalling a COM object across apartments:
```
  [STAThread]
  static void Main(string[] args)
  {
      string progid = "PowerPoint.Application"; // sample EXE-based COM server (problem not tied to PowerPoint)
      object object_mta = null;

      Thread thread = new Thread(() => {
          // create COM object in separate MTA apartment
          Type type = Type.GetTypeFromProgID(progid);
          object_mta = System.Activator.CreateInstance(type);
      });
      thread.SetApartmentState(ApartmentState.MTA);
      thread.Start();
      thread.Join();

      // marshal object over to main thread STA apartment
      IntPtr object_ptr = Marshal.GetIUnknownForObject(object_mta);
      object object_sta = Marshal.GetObjectForIUnknown(object_ptr);

      int hash_mta = object_mta.GetHashCode();
      int hash_sta = object_sta.GetHashCode();
      Console.WriteLine(String.Format("Object hash codes: MTA={0}, STA={1}", hash_mta, hash_sta));

      bool same1 = (object_mta == object_sta);
      bool same2 = object_mta.Equals(object_sta);
      Console.WriteLine(String.Format("Objects equal: =={0}, Equals={1}", same1, same2));

      Marshal.Release(object_ptr);
  }
```

The problem is reproduced with .Net 5 x64 on Windows 10. The same problem also observed on .Net framework 4.5, so it's probably not a regression.

### Request
I'm observing this problem when accessing a custom COM EXE server implemented in C++ from C#. The COM objects to compare are not created explicitly in my application, but instead injected through callbacks. I'm therefore not able to work around the problem by moving all COM object creation to the main thread.

It would help a lot if the .Net runtime could either:
* Improve the Runtime Callable Wrapper (RCW) to enable comparison across apartments, or
* Provide a mechanism for customizing the hash & equality implementation from within the custom COM EXE server, like e.g. making it possible to implement the `IHashCodeProvider` interface from C++, and let the RCW use it if implemented.

**Comment by jkoritzinsky** [comment]
I believe that the two COM objects compare unequal because the proxy on the MTA has a different IUnknown pointer than the original object on the STA. Since .NET uses the IUnknown pointer as the identity element, the two instances compare as non-equal. I'm not familiar enough personally with COM cross-apartment marshalling, so I'm not sure what the best solution here would be.

@AaronRobinsonMSFT do you have any suggestions/workarounds?

**Comment by AaronRobinsonMSFT** [comment]
>This prevents me from being able to detect references to the same COM object across apartments.

@forderud That is by-design. Proxies in COM are intentionally designed to look and work like the object instance itself. Attempting to peer through the proxy is violating the intention of how COM is designed to work &ndash; the client really shouldn't know/care in practice.

This is not the intent of the `GetHashCode`, `Equals`, or `==` operator as they appear on an RCW. Those methods/operators are designed to show managed `object` instance equality and have nothing to do with the underlying COM server. Again, this is intentional because attempting to peer through a proxy is a bad idea and violates how COM is designed. This is the .NET perspective which means we aren't inclined to do anything at the .NET API level because it doesn't follow the rules.

The above aside, there might be a Win32 solution that could find this information out and that could be called via a P/Invoke. I am dubious a supported solution exists though because as @jkoritzinsky stated the RCWs in this case are different because of the identity rules that exist regarding `IUnknown` instances. The real instance is queried for an `IUnknown` and that is required to return the same one for an instance in all cases. The newly created proxy will have a separate `IUnknown` because it is a different COM object. We don't have any insight into how to connect these two because we shouldn't be aware of the connection &ndash; they are different objects as far as we and all COM clients are concerned.

I did reach out to the COM team if they had another suggestion and the following option was suggested.

An option here is to have the COM server implement an interface akin to the following:

```C++
struct IIdentity
{
    virtual HRESULT STDMETHODCALL GetIdentity(_Out_ ULONG_PTR* identity) = 0;
};
```

The returned value could be the `this` pointer or some other identifier that peers through the COM layers. This could then be compared between any object and proxy.

**Comment by forderud** [comment]
Thanks for the feedback @jkoritzinsky & @AaronRobinsonMSFT . I guess I then misunderstood the intended semantics when comparing  managed `object` instances.

As a work-around I've already created a `EqualComObjects` function to use instead of `Equals` or `==` for comparing the underlying COM objects:
```
  /** Check if the underlying COM objects are the same, regardless of apartment differences. */
  static bool EqualComObjects (object obj_a, object obj_b)
  {
      // Marshal objects to the _same_ apartment (the current thread apartment) before comparing.
      // The target apartment doesn't necessarily need to be the "native" apartment for the object,
      // but could point to a COM proxy. This doesn't matter, since identical objects will then point to the same proxy.
      // Please note that marshalling is redundant if both objects already reside in the same apartment.
      IntPtr obj_a_prt = Marshal.GetIUnknownForObject(obj_a);
      IntPtr obj_b_prt = Marshal.GetIUnknownForObject(obj_b);
      
      bool equal = Marshal.GetObjectForIUnknown(obj_a_prt) == Marshal.GetObjectForIUnknown(obj_b_prt);

      Marshal.Release(obj_b_prt);
      Marshal.Release(obj_a_prt);

      return equal;
  }
```

This seem to work nicely for me. However, it would be simpler & less confusing if .Net could provide some sort of in-built support for this type of comparison. I would of course prefer if the in-built `Equals` could be extended to do just this. However, could it be an alternative to instead add such a function to `System.Runtime.InteropServices.Marshal` for ease of access?

**Comment by AaronRobinsonMSFT** [comment]
@forderud This is a reasonable solution but only because of how .NET handles RCW caching. There is nothing stopping a custom proxy/stub implementation from creating a new proxy each time.

>I guess I then misunderstood the intended semantics when comparing managed object instances.

My statement was only for the `__ComObject` type. The assumed semantics are possible because we could override the `__ComObject.Equals()` method. However, that would make the implementation rather heavy weight and that is something I would be hesitant to do or even consider as the "correct" implementation. As I've said previously, COM doesn't support the concept of equality between a COM object and a COM proxy and as such we aren't inclined to provide a mechanism to enable that.

>However, could it be an alternative to instead add such a function to System.Runtime.InteropServices.Marshal for ease of access?

I don't see anything wrong with a proposal for this but I am going to venture a guess this would be rejected for all the previous reasons given. The scenario is odd from a COM perspective and given the 20+ years of .NET without this functionality getting it in a new API seems a bit niche and not something we would like to own. It might be helpful in a community owned COM utilities NuGet package &ndash; personally, I'd be very interested in helping maintain that sort of project.

**Comment by forderud** [comment]
Thank you again for the explanations @AaronRobinsonMSFT . I'll then probably continue using my custom `EqualComObjects` function moving forward.

Adding this function to an open-source library sounds like a good idea. However, I'm primarily a C++ developer myself and am only working in C# to ensure that my company's COM servers remain compatible with managed code. I'm therefore probably not the right person to initiate such a project if nothing similar already exists.

One final thought: Could it be a possibility to somewhere document that `__ComObject` doesn't marshal the pointers to the same apartment before performing comparison. Therefore, references to the same COM object can report as not equal if residing in different apartments?

**Comment by Joe4evr** [comment]
> Could it be a possibility to somewhere document that `__ComObject` doesn't marshal the pointers to the same apartment before performing comparison. Therefore, references to the same COM object can report as not equal if residing in different apartments?

Sounds like a request for dotnet/docs. 🙂

**Comment by AaronRobinsonMSFT** [comment]
> One final thought: Could it be a possibility to somewhere document that __ComObject doesn't marshal the pointers to the same apartment before performing comparison.

@forderud I can document this behavior. The issue is `__ComObject` isn't documented as it is an internal type and implementation detail. We'd have to place it under RCW/CCW documentation and that is likely to get lost. I will add a note under https://docs.microsoft.com/dotnet/standard/native-interop/runtime-callable-wrapper &ndash; does that okay?
