### ISSUE TITLE
When lat / lon becomes (0,0) in GeoCoordinateWatcher

### ISSUE THREAD

**Issue by yufumiyanagino** [dotnet/runtime#56751]
[sample.zip](https://github.com/dotnet/sdk/files/6889401/sample.zip)
I am in trouble because there are many cases where the latitude and longitude cannot be obtained with GeoCoordinate Watcher.

Specifically, the following acquisition results are often obtained.

(conditions)
・ Model: Surface GO 2 (LTE model)
・ GPS = ON / LTE = No Sim / Wifi = OFF
・ GeoPositionAccuracy = default

(State in PositionChanged event) * 1
・ (GeoCoordinateWatcher) .Status! = GeoPositionStatus.Ready
・ (GeoCoordinateWatcher) .Position.Location.IsUnknown = false
・ (GeoCoordinateWatcher) .Position.Longitude (Latitude) = 0

In the case of " 1", what kind of hardware state can be considered?
Example)
・ GPS module: Obtained but GPS signal is incorrect
・ GPS module: Not acquired
・ GPS module: Acquiring
If the signal has not been acquired, I think it will be "Is Unknown = true".

Also, if the signal is received purely by the GPS module (LTE = No Sim / Wifi = OFF), how long does it generally take to make a decision? (GeoPositionAccuracy = default)

Thank you

**Comment by jeffschwMSFT** [comment]
@danmoseley thoughts on an appropriate repo/area label?

**Comment by danmoseley** [comment]
@krwq  do you know?

**Comment by krwq** [comment]
AFAIK those APIs didn't get ported from full framework and I do not know about anyone who might might own these now - I think they might be deprecated but do not know for sure.

I've created https://github.com/dotnet/iot/issues/1623 to consider adding these APIs into .NET IoT since they fit there better than runtime anyway. I'm not sure if we will add this APIs at all and even if we are if they would remain the same though as in full framework but I'd suggest moving this conversation into .NET IoT repo.

As for solution to this issue: most of the sensors doing any geolocation use NMEA 0183 protocol and simply send NMEA messages over serial port (it's a textual protocol). I'd suggest trying to communicate with them directly (after plugging frequently new serial port will show up which you can connect to) and once you establish connection start reading line by line - you should start getting some text messages which you can convert into lat/lon (i.e. you can use https://github.com/dotMorten/NmeaParser for that). I'm not sure if what I wrote applies to your device as well but that was true for any geolocation device I've tried so far.

I suggest to close this issue since full framework issue is unlikely to be fixed and we don't have this component here. For questions about accessing any sensors/devices it's better to ask them in the https://github.com/dotnet/iot repo or discord as it's more likely someone will be able to help you.

**Comment by krwq** [comment]
Closing issue per above answer since it's not actionable in here. Consider creating issue in dotnet/iot repo about how to read lat/lon from your sensor but note the answer you will get will most likely not involve GeoCoordinateWatcher APIs and be similar to the solution I suggested above.

**Comment by danmoseley** [comment]
Original requests were here: https://github.com/dotnet/runtime/issues/26666

**Comment by yufumiyanagino** [comment]
@krwq @danmoseley @jeffschwMSFT
 
Thank you for your support.
I understand that it is difficult to solve here.
Try to negotiate with the customer.
