### ISSUE TITLE
Detect the .NET core version at runtime

### ISSUE THREAD

**Issue by j82w** [dotnet/runtime#568]
# Issue Title

Detect the .NET core version from a library. 

# General

I have a library that targets .NET standard 2.0. I need to log the .NET core version of the application using the library for telemetry and troubleshooting purposes. The `RuntimeInformation.FrameworkDescription` only returns the CLI version, but it works correctly for applications targeting .NET Framework.

Example:
`RuntimeInformation.FrameworkDescription`  return  ".NET Core 4.6.28008.01"

Is there any way to reliably get the .NET core version of the application?

**Comment by tannergooding** [comment]
Most of the APIs were updated in .NET Core 3.0 to report the product version rather than the file version: https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#apis-that-report-version-now-report-product-and-not-file-version

I do not recall if there is a "correct" way to detect the product version prior to 3.0

**Comment by j82w** [comment]
Is there any way to map the file version to a product version?

**Comment by akoeplinger** [comment]
`RuntimeInformation.FrameworkDescription` returns the product version since .NET Core 3.0.
Given the versions prior to that won't receive updates anymore you could check the file versions of each release and build a mapping table yourself.
