### ISSUE TITLE
Getting managed assembly entrypoint on diagnostic pipe GetProcessInfo2 command during suspension

### ISSUE THREAD

**Issue by jander-msft** [dotnet/runtime#56808]
### Description

When issuing a a GetProcessInfo2 command on the diagnostic pipe to a runtime instance that is suspended, it will fail to get the managed entrypoint assembly information and return an empty string. 

The expected behavior is that for any .NET process that does have a managed entrypoint, that this command will return the managed entrypoint assembly even while the process was suspended at startup.

Without this, it makes any diagnostic tool have an extremely difficult time determining if it should start observing a process based on its entrypoint name, especially in a multi-container environment where the process name is likely `dotnet` for all .NET processes and the process ID is 1 for many of them; the main differentiator will be the entrypoint name. Diagnostic tools would have start observing the process (start event pipe sessions, or maybe even attach a profiler, during suspension), have to "wait a little while" until the command does return a valid value for the entrypoint, and possibly cancel all of the diagnostic operations on the process if it was not one that the tool really wanted to observe.

Expectation is that the GetProcessInfo2 should be able to get the managed entrypoint assembly information during suspension. From a naive perspective, this shouldn't require running managed code but _just_ to read the assembly information from the metadata table.

### Regression?

No

### Other information

This is in reference to the following code: https://github.com/dotnet/runtime/blob/a33ea98572b93ad1b357961e2b2904605cdec9f6/src/coreclr/vm/eventing/eventpipe/ep-rt-coreclr.h#L1185

Behavior was introduced in the following PR: https://github.com/dotnet/runtime/pull/55379

cc @josalem

**Comment by tommcdon** [comment]
Adding @vitek-karas for ideas for a possible .NET 6 fix.  It sounds like the runtime is not fully initialized and so our current implementation retrieving the startup assembly through the appdomain is occurring too early in runtime startup.  I am curious if we could access the required information through a different mechanism - I suspect that the runtime host has this information.

**Comment by josalem** [comment]
We discussed this offline a little bit. There are a few things we're going to have blocking us:
* At the point where we suspend, the host hasn't loaded the entrypoint assembly so we can't use the assembly metadata to get the information.
* The host may be a single-file host or loading an assembly dynamically from a memory address. In these cases, there may not be a name we can use until the assembly is loaded.
* There's no guarantee that the assembly filename is the same as the assembly's _name_.
* We can't move the suspension point to later in the process since we need to suspend before the GC and other components are initialized.

All that being said, I think we can try to do something better than `""` for the assembly name. We could make a bet that _most_ of the time we are dealing with a `dotnet MyApp.dll` style invocation where the assembly name matches the filename and attempt to pull the info from the command line the host collects.

**Comment by josalem** [comment]
I'm going to hold off on putting this into the 6.0 milestone for now and put it in 7. If we have time left after some bug fixes, this is worth getting in before we ship. @tommcdon or @jander-msft feel free to put it there for now if you feel it necessary and we can reassess as we get closer to RC2.

**Comment by jander-msft** [comment]
> * At the point where we suspend, the host hasn't loaded the entrypoint assembly so we can't use the assembly metadata to get the information.

Could the assembly loading logic for the entrypoint be refactored a bit to preload just the entrypoint assembly so that the metadata is available earlier?

Alternatively, could the GetProcessInfo2 command use a pay-for-play model where if the entrypoint assembly is not loaded yet, it loads the assembly itself and reads out the metadata from the file?

**Comment by josalem** [comment]
> Alternatively, could the GetProcessInfo2 command use a pay-for-play model where if the entrypoint assembly is not loaded yet, it loads the assembly itself and reads out the metadata from the file?

I'd be wary of the `GetProcessInfo2` command having a side-effect like that. I'd rather that be a separate command if we did that via the IPC channel at all.

> Could the assembly loading logic for the entrypoint be refactored a bit to preload just the entrypoint assembly so that the metadata is available earlier?

I'm not sure about the broader implications of this. @vitek-karas is it feasible to load the main assembly _before_ the host calls `EnsureEEStarted`? Will this break loader tracing because it would be loading things before EventPipe is started?

**Comment by vitek-karas** [comment]
> is it feasible to load the main assembly before the host calls EnsureEEStarted? Will this break loader tracing because it would be loading things before EventPipe is started?

Not really. There are scenarios where there's no "main" assembly (native hosting, COM, IJW, ...) - in these cases the runtime has to start with actually just the framework (no app/user code loaded yet) and only then the managed code in CoreLib will load the app/user code using managed assembly loading APIs. It's likely that going forward we will want to use the ability to start the runtime and run managed code in CoreLib (or closeby) well before any user code gets loaded.

Also - the current native APIs which `coreclr.dll` exposes don't allow this:
* `coreclr_initialize` - this will call `EnsureEEStarted` but there's no parameter to tell it which will be the "main" assembly. In fact the caller might not know yet.
* `coreclr_create_delegate` - this is the no "main" assembly API - this does in a way specify some managed assembly, but in lot of cases it is CoreLib - so not really helpful (and as mentioned above, no user code is available yet)
* `coreclr_execute_assembly` - this specifies which is the "main" assembly, so only inside this method we can tell.

**Comment by josalem** [comment]
@jander-msft based on Vitek's response, it sounds like there isn't a reliable way to retrieve the assembly name while we are suspended. Is it possible for you to attempt to scrape the assembly name (or a best guess) from the command line when the assembly name field comes in blank?

**Comment by jander-msft** [comment]
Given that the order of `dotnet` executable parameters is arbitrary and can have (slightly) different syntax on different OSes, I would say that would be, at best, error prone. It would effective have to duplicate the existing algorithm that the runtime uses. Given that, the runtime should provide that information since it already does the work to get the entry point assembly.

**Comment by josalem** [comment]
I don't think the _runtime_ parses this information. The _host_ _may_ have the assembly file path, but that is dependent on the instantiation path having already done the work. Based on Vitek's comment, I don't think that is something we can assume or expect.

@vitek-karas please correct me if I'm wrong, but it sounds like getting either the assembly name _or_ scraping the assembly path from the commandline is controlled by the host and isn't guaranteed to have happened by the time `EnsureEEStarted` has been called. More directly, in the case where the runtime can't use the assembly APIs to get the assembly name, the runtime also cannot get a pre-scraped assembly filename. This is sounding like we would need to change hosting layer APIs to get this information at the suspension point.

**Comment by vitek-karas** [comment]
@josalem - you're right. What we could do is:
* Make the code/API/design in the event source accept that the main assembly name is "optional" - it may or may not be available (native hosting scenarios simply don't have such a thing - even logically).
* Add a new optional runtime property which the host may set, something like "MAIN_ASSEMBLY_NAME" (or maybe something specific to the diagnostics, not sure yet). Since runtime gets all these properties during `coreclr_initialize` it would be available during `EnsureEEStarted`.
* Modify our host to set this if possible - so that for normal "running an app" scenario, this would get set as expected.
* Allow native hosting scenarios to set this if desired (this is already possible, native hosting can set any runtime property it wants).

The only downside of this approach is performance. Passing yet another property from host to runtime is not free. And eventually we would really like to reduce this interface to minimum. Ideally we would do this through something like https://github.com/dotnet/runtime/issues/3673. But for now it's probably OK to just add it as is.

Q: Is this value "needed" every time, or only if something tries to use diagnostic tooling on the process?

**Comment by josalem** [comment]
Thanks for the explanation @vitek-karas! 

This information is _only_ needed during EnsureEEStarted if someone sends a ProcessInfo2 command while the runtime is suspended before execution. Otherwise, this information is pulled from the Assembly APIs if it is set. It's already considered optional. In the event we can't retrieve it from the Assembly APIs we just return the empty string in the command payload.

**Comment by vitek-karas** [comment]
In that case I'll leave it up to you to decide how important is to have this during startup. It could be added for most scenarios via the host->runtime property mechanism.

**Comment by josalem** [comment]
@vitek-karas could you direct me to where the runtime properties logic is in the host? It sounds like a pretty straightforward change to get this info during suspension. If possible, I'd like to light this up for the dotnet-monitor folks in 6.

**Comment by vitek-karas** [comment]
It's around here: https://github.com/dotnet/runtime/blob/f81e82df0c779c4eaa267b557e179fb2a480f670/src/native/corehost/hostpolicy/hostpolicy_context.cpp#L222-L229

The local variable `application` (currently unused for some reason) already contains the full path to the main application dll (the main assembly). I think it can be null/empty though.
