### ISSUE TITLE
RuntimeInformation.ProcessArchitecture is not a JIT constant

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#57152]
### Description

RuntimeInformation.ProcessArchitecture currently isn't a JIT time constant so it doesn't participate in dead branch elimination and it also isn't inlined. Since the API has a simillar usage as OperatingSystem APIs which are JIT constants, the expected behaviour would be for it to be as optimized as them. The simple solution would be to store the value in a `static readonly` field and return that instead, which would be optimized in T1.

Thinking about it though, I think that since the process architecture will be always the same as the one dotnet running it was built for, wouldn't such implementation as the one below be valid?
```C#
        public static Architecture ProcessArchitecture
        {
            get
            {
#if TARGET_ARM64
                return Architecture.Arm64;
#elif TARGET_ARM
                return Architecture.Arm;
#elif TARGET_AMD64
                return Architecture.X64;
#elif TARGET_X86
                return Architecture.X86;
#elif TARGET_WASM
                return Architecture.Wasm;
#elif TARGET_S390X
                return Architecture.S390x;
#else
#error Unknown Architecture
#endif
            }
        }
```

### Configuration

SharpLab Core CLR 5.0.721.25508 on amd64

### Regression?

Probably not

### Data

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFmKCAA4BlPgDdWYGLgDcAWABQC4gGZKVJOWa5sAMxiUATOQAqUjAoDeC8jcqrqG1i3IBBABQBKa7avzb/ygB2ckYWdhgeHWh8bDYIJhoABX5JXFwXKDAAC1YMGDAMBlhyAF4S10ycvIKizgANVHIAfnIqchByUjk/WwBfBV6gA)

**Comment by am11** [comment]
This is a good point, we can also cleanup `SystemNative_GetProcessArchitecture` related code in the process since it is doing exactly the same thing with extra overhead.

**Comment by am11** [comment]
I gave it a shot (#57172), but it turned out we can't use architecture-based preprocessors or partials for this assembly (or any assembly currently produced from under src/libraries).

Other option could be to have a named intrinsic for it in JIT: https://github.com/dotnet/runtime/blob/c59d2005fc61b58365cd877c910642c477bb0a48/src/coreclr/jit/importer.cpp#L4753 followed by the node replacement implementation with the value from coreclr's PAL. Though I am not sure if ProcessArchitecture is interesting enough to meet the bar for intrinsic.

**Comment by MichalPetryka** [comment]
Fetching the data in a static constructor and storing it in a static readonly field should also work, but only in T1.

**Comment by am11** [comment]
> Fetching the data in a static constructor and storing it in a static readonly field

This is exactly how it is setup this way: https://github.com/dotnet/runtime/blob/85441ce69b81dfd5bf57b9d00ba525440b7bb25d/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Unix.cs#L16

notice it is using ` { get; } = methodcall`and not ` => methodcall`. The former does the static initialization (method call in this case) once per process and set the value, which subsequent calls will use.

**Comment by am11** [comment]
Ah, and sharplab is using Windows VM (in Azure), so it uses https://github.com/dotnet/runtime/blob/85441ce69b81dfd5bf57b9d00ba525440b7bb25d/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs#L45 that can use the backing field (or private method like unix setup).

**Comment by MichalPetryka** [comment]
> Ah, and sharplab is using Windows VM (in Azure), so it uses
> 
> https://github.com/dotnet/runtime/blob/85441ce69b81dfd5bf57b9d00ba525440b7bb25d/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs#L45
> 
> but in this file too, we have backing fields caching values for static properties.

The JIT only optimizes it for `static readonly`, not just static.

**Comment by am11** [comment]
It is a readonly property.

**Comment by MichalPetryka** [comment]
https://github.com/dotnet/runtime/blob/85441ce69b81dfd5bf57b9d00ba525440b7bb25d/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs#L12

It's `volatile`, not `readonly`.

**Comment by am11** [comment]
By `it` I meant ProcessArchitecture, not its backing field, but like I said, this is Windows only, not the one you were initially looking at in top proposal (s390x etc.)..

**Comment by MichalPetryka** [comment]
In the top proposal I assumed that an universal implementation with defines would be possible, I actually looked at the Windows implementation. And it being an issue only on Windows doesn't change the fact that it is still an issue.

**Comment by jkotas** [comment]
>  it turned out we can't use architecture-based preprocessors or partials for this assembly

You can fix that by moving the type to CoreLib. CoreLib is built as architecture-specific.

> Other option could be to have a named intrinsic for it in JIT:

That would require moving the type to CoreLib as well. We do not like having JIT intrinsics outside CoreLib.

**Comment by am11** [comment]
ProcessArchitecture: currently .NET supports Linux x86_64 (-m64) officially. There are community-supported i386 (-m32) builds WIP, where .NET returns `Architecture.X86` from RI.ProcessArchitecture. The -m32 binaries can also run on x64 Linux systems, where 32-bit ld and supporting libraries are installed. However, there is a third variant x32 ABI (-mx32), i.e. x64 calling convention with 32-bit address space (which doesn't require installing extra stuff for 32-bit support), which is currently not a supported target in .NET. Assuming, this target is added in future, it will still require a separate runtime pack for multiple reasons, and during that work we would need an additional preprocessor for C# corresponding to `__ILP32__` (https://wiki.debian.org/X32Port#Detecting_X32, e.g. TARGET_MX32 in MSBuild config), and a new enum value Architecture.X32 which ProcessArchitecture will return in this case. Therefore, I think using the constant value set at build-time will work in all cases for ProcessArchitecture.

OSArchitecture: would be tricky to resolve with constant on Linux and Windows. Currently on Windows we do the right thing by calling interop; but on Linux, we return Architecture.X64 on Windows from the 32-bit .NET process running on linux-x64. but when the linux-x86 .NET process is running on linux-x64 system, we get Architecture.X86 from OSArchitecture instead of X64. The fix for this issue will likely be addressed in System.Native: https://github.com/dotnet/runtime/blob/e62b82ab1583386a3c90460bc24b0623dbeb6856/src/libraries/Native/Unix/System.Native/pal_runtimeinformation.c#L62-L71 so I think we would need to keep OSArchitecture coming through the interop layer at least for x86 (and probably also for arm32). JIT named intrinsic can help in this case.

**Comment by jkotas** [comment]
> OSArchitecture coming through the interop layer at least for x86 (and probably also for arm32). JIT named intrinsic can help in this case.

OSArchitecture is very rarely used and never on performance critical paths. I do not think it would be worth it to add JIT intrinsic for it.
