### ISSUE TITLE
Unable to hijack thread in empty while (true) loop

### ISSUE THREAD

**Issue by wesrupert** [dotnet/runtime#5724]
One of our tests was checking funceval timeout on a function with the body `while (true) { ; }`. This timed out properly on windows but wouldn't terminate on OSX or Ubuntu.

**Comment by KirillOsenkov** [comment]
Subscribing because VSMac has an issue where if the debuggee is busy with 100% CPU and we are running and we press Break in the debugger, the process doesn't break immediately like on Windows, but keeps running and the only way forward is to Force Quit the debuggee. Gregg indicated that this issue might be related.

**Comment by danmoseley** [comment]
Cc @VSadov

**Comment by VSadov** [comment]
Debugger and suspension have additional interaction. 
Let's first confirm if this is still a case with no debugger involved. A lot of things changed since 2016.

**Comment by hoyosjs** [comment]
This might be https://github.com/dotnet/runtime/issues/33561

**Comment by KirillOsenkov** [comment]
Additional symptom I'm seeing (not sure if related), if a .NET 6 process is busy spinning with 100% CPU I can't attach to it using the debugger on Mac, it times out.
