### ISSUE TITLE
AssemblyDependencyResolver not using nuget package storage

### ISSUE THREAD

**Issue by angelaki** [dotnet/runtime#57345]
I'm using the `AssemblyDependencyResolver` for some kind of framework. With .Net 5.0 the `AssemblyDependencyResolver` based on my plugin's path `(new AssemblyDependencyResolver(plugInPath))` hold the nuget package storages `(e.g. C:\Users\[user]\.nuget\packages\microsoft.entityframeworkcore\6.0.0-preview.7.21378.4)` in it's internal `_assemblyPaths`. Now all assemblies point to the assemblies path itself (`plugInPath`) where they actually aren't located. Is this a misbehavior?

**Comment by vitek-karas** [comment]
I assume this problem started to occur after you retargeted the host application to .NET 6, right?
This is because by default when the app is built, the SDK doesn't produce `.runtimconfig.dev.json` anymore (as for normal apps it's not used for anything really and without it the app startup is faster). When the app is built, all of its dependencies are copied to the output, so it doesn't need to go to NuGet cache.

Loading classlibs via ADR will experience a failure though because by default, classlibs don't copy their dependencies to the output.

The way to fix that is (As you mention) to set `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`. If you were to move your application to another machine to run it, you would have to set that property anyway, since a published app doesn't have `.runtimeconfig.dev.json` and on top of that, you can't rely on the necessary packages to be available in local NuGet cache (there might not be any cache on the target machine).

But this is effectively a change from 5 to 6 in behavior on developer machine. I don't know if we can detect this scenario and "warn" and/or "fix" it without going back to always having `.runtimeconfig.dev.json". I think that ideally all plugins should specify `<EnableDynamicLoading>true</EnableDynamicLoading>` which is designed to make the output such that it can be "moved" to a different location and still have everything it needs (both for native hosting as well as managed dynamic loading).

**Comment by angelaki** [comment]
Thank you for this pretty much detailed explanation! So it actually works as intended - just wanted to mention in, if it was a bug.

**Comment by vitek-karas** [comment]
Reopening as a "docs"/"samples" issue. We need to fix the guide and fix the sample so that it works on .NET 6 (and probably retarget the sample from .NET 5 -> .NET 6).

**Comment by vitek-karas** [comment]
Samples are updated in https://github.com/dotnet/samples/pull/4773. Docs are updated in https://github.com/dotnet/docs/pull/25785.

Retargeting to .NET 6 will need to wait for actually shipping .NET 6 (no need to rely on previews in this sample).
