### ISSUE TITLE
[mono] FullAOT runtime test failures: Attempting to JIT compile method

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#57350]
Several runtime tests (which can be found by searching issues.targets for this issue number) fail to pass with this message:

```
Attempting to JIT compile method '[function name here]' while running in aot-only mode
```

Tests are run using `MONO_ENV_OPTIONS=--full-aot`.

FullAOT compilation uses these flags on x64:
```
MONO_ENV_OPTIONS="--aot=full,llvm,llvm-path=$MONO_PFX,mattr=sse4.2,mattr=popcnt,mattr=lzcnt,mattr=bmi,mattr=bmi2,mattr=pclmul,mattr=aes"
```
and these on arm64:
```
MONO_ENV_OPTIONS="--aot=full,llvm,llvm-path=$MONO_PFX,mattr=crc,mattr=crypto"
```

**Comment by lambdageek** [comment]
Looking at, for example, https://github.com/dotnet/runtime/pull/80642 which introduced a new testcase that appears to hit this issue, it seems like what is happening is that we need to throw a TypeLoadException during layout of some class, but since we're in the AOT compiler, we're not allowed to run managed code (such as the TLE constructor).

**Comment by lambdageek** [comment]
Probably the best we can do here is just improve the diagnostic: instead of attempting to throw a TLE and erroring out (because execution is not allowed) we would detect that we're in the AOT compiler and just print a diagnostic message (ideally mentioning the real issue) and exit.

It might see like a better idea is to succeed in compilation and generate code that when called with throw the TLE, but that actually seems pretty hard.  For example if the bad class is used as a method parameter we might not be able to generate anything that is callable - so compilation will appear to succeed but it will crash badly (possibly even more confusingly) if the method is called.

I think we should just improve the AOT compiler error message to report the actual cause.

/cc @SamMonoRT - we should talk about this on our next 1-1

**Comment by lambdageek** [comment]
Note, that the "attempting to JIT compile" issue might actually be masking real issues.

For example the test case added by #80642 is supposed to _pass_ not to throw a TLE.

**Comment by lambdageek** [comment]
We should have a better error message in full AOT mode.  Also a better way to skip tests with full AOT than just adding to the issues.targets file
