### ISSUE TITLE
.NET Runtime 5.0.9 / .NET SDK 5.0.400 not available for Ubuntu 18.04

### ISSUE THREAD

**Issue by appimpact** [dotnet/runtime#57391]
Neither .NET Runtime 5.0.9 nor .NET SDK 5.0.400 is available for Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/34662138/129437592-045e37b1-deac-4bd7-a079-037f5161dc3c.png)

![image](https://user-images.githubusercontent.com/34662138/129437651-e50a1750-487d-43f6-8e1b-518623361f8c.png)

**Comment by ianclegg** [comment]
It appears this issue is not limited to dotnet 5.0.9, but also affects the latest release's of dotnet 2.1 on Ubuntu 18.04 LTS. Interestingly, the latest release of dotnet 3.1 does appear to available for Ubuntu 18.04.

For example:

**dotnet 5.0 Ubuntu 18.04**
latest `dotnet sdk 5.0.400` is available for Ubuntu 16.04, but is missing for Ubuntu 18.04
`E: Version '5.0.412-1' for 'dotnet-sdk-5.0' was not found`

latest `dotnet runtime 5.0.9` is available for Ubuntu 16.04, but is missing for Ubuntu 18.04
`E: Version '5.0.9-1' for 'dotnet-runtime-5.0' was not found`

latest `aspnetcore 5.0.9` is available for Ubuntu 16.04, but is missing for Ubuntu 18.04
`E: Version '5.0.9-1' for 'aspnetcore-runtime-5.0' was not found`


**dotnet 2.1 Ubuntu 18.04**
latest `dotnet sdk 2.1.817` is available for Ubuntu 16.04, but is missing for Ubuntu 18.04
`E: Version '2.1.817-1' for 'dotnet-sdk-2.1' was not found`

latest `dotnet  runtime 2.1.29` is available for Ubuntu 16.04, but is missing for Ubuntu 18.04
`E: Version '2.1.29-1' for 'dotnet-runtime-2.1' was not found`

latest `aspnetcore 2.1.29` is available for Ubuntu 16.04, but is missing for Ubuntu 18.04
`E: Version '2.1.29-1' for 'aspnetcore-runtime-2.1' was not found`

**Comment by joperezr** [comment]
Thanks for reporting. In order to unblock you, have you tried using either the [dotnet-install.sh script](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) or to manually downloading it? [x64](https://download.visualstudio.microsoft.com/download/pr/13b9d84c-a35b-4ffe-8f62-447a01403d64/1f9ae31daa0f7d98513e7551246899f2/dotnet-sdk-5.0.400-linux-x64.tar.gz
) version is here, and other platforms can be downloaded from [here](https://dotnet.microsoft.com/download/dotnet/5.0)

**Comment by ianclegg** [comment]
👍

**Comment by danmoseley** [comment]
out of support
