### ISSUE TITLE
Why are symbols (pdbs) created for reference assemblies?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57474]
In a discussion with @hoyosjs we noticed that when building a reference assembly, the corresponding pdb is generated as well even though those pdbs aren't distributed into the shared framework package. As pdbs aren't necessary for reference assemblies which don't contain actual sources, why are these even generated?

Design discussion, cc @ericstj, @safern, @Anipik

**Comment by ViktorHofer** [comment]
@ericstj should we disable the PDB generation for our reference assembly projects?

**Comment by ViktorHofer** [comment]
Gentle ping regarding my above question @ericstj

**Comment by ericstj** [comment]
I recall issues in the past around release tools / build tools / insertion checks requiring symbols for every dll.  I remember having to get exceptions for things like facades and reference assemblies in the past.  I recall us treating it as virtuous that we build these as normal assemblies in .NETCore with symbols / signing / etc.

It doesn't feel wrong to include symbols, but I can also see them as being pretty useless since one cannot load or debug the reference assemblies.  If we could have confidence that we wouldn't break anything by removing them, we could do it.  I wonder if @joeloff or @wtgodbe have any experience around building these without symbols and inserting them to VS and if they face any hurdles around not having symbols (I don't think ASP.NET reference assemblies would have symbols).

**Comment by wtgodbe** [comment]
Our ref pack does not carry any .pdb's, so it seems like it should at least be possible. I don't know about the VS end.

**Comment by joeloff** [comment]
For VS we can simply add an exclusion. The ideal solution would be for VS to look at the DLL and be able to determine that it's a reference assembly and has no code and therefore should automatically exclude it from a symbol check. Will the PE header contain enough information to make this determination, e.g. a DLL with no `.text` section.

**Comment by ViktorHofer** [comment]
We stopped producing symbols during for reference assemblies sometime during the .NET 8 release cycle: https://github.com/dotnet/runtime/blob/7ed33d80c92fa0b7ae740df60a460e984f2f442b/Directory.Build.props#L427C4-L431. Closing.
