### ISSUE TITLE
[net6.0-android] HttpClient.ServerCertificateCustomValidationCallback throws 'Arg_PlatformNotSupported'

### ISSUE THREAD

**Issue by PureWeen** [dotnet/runtime#57537]
### Description

Try to set `HttpClient.ServerCertificateCustomValidationCallback` when running as net6.0-android

### Configuration

net6.0-android
dotnet version: 6.0.100-preview.7.21379.14

### Regression?

This worked inside Xamarin.Android

### Other information

[MauiPool.zip](https://github.com/dotnet/runtime/files/6996186/MauiPool.zip)

**Comment by filipnavara** [comment]
See https://github.com/dotnet/runtime/pull/57555 and the linked issue.

There was an intentional change to use native HTTP handlers for `new HttpClientHandler()` scenario (as opposed to only using it for `new HttpClient()` in earlier Xamarin platforms). This causes some properties to throw PNSE even if the underlying handler ended up being `SocketsHttpHandler` (eg. when native handler is switched off in .csproj). The above PR fixes that but there's possibly still some work remaining on the XA/XI side to implement the missing properties on the native handlers.

cc @steveisok if some further clarification is required.

**Comment by karelz** [comment]
Reopening to track port to 6.0

**Comment by karelz** [comment]
Fixed in 6.0 RC2 in PR #58508.
Fixed in 7.0 in PR #58456.
