### ISSUE TITLE
When will Microsoft.Office.Interop.Excel have a netcore version 

### ISSUE THREAD

**Issue by steel-li** [dotnet/runtime#57547]
![image](https://user-images.githubusercontent.com/48340400/129655984-0133f1ad-0130-4627-972e-b0e0e2d621ce.png)
When will Microsoft.Office.Interop.Excel have a netcore version

**Comment by AaronRobinsonMSFT** [comment]
Hi @steel-li. I recommend reaching out via the "Contact owners" link on the [NuGet package page](https://www.nuget.org/packages/Microsoft.Office.Interop.Word/). The .NET team does not own this package and has no insight into its long term purposes.

**Comment by rgwood** [comment]
Agreed with Aaron. But I can tell you the answer is “probably never”, the Office team has no love for COM interop and they have confirmed that .NET Core/5+ support will never be coming to VSTO addins (one of the primary users of this PIA).

If you need a .NET Core COM interop assembly for Excel, you will probably have to roll your own somehow.

**Comment by AaronRobinsonMSFT** [comment]
>If you need a .NET Core COM interop assembly for Excel, you will probably have to roll your own somehow.

One quick clarification since I want to make sure we are clear on what .NET Core supports and doesn't. @rgwood is correct in that VSTO will not being moving to .NET Core and will remain a .NET Framework only platform &ndash; see https://github.com/dotnet/core/issues/5156. However, one can automate an Office scenario from .NET Core &ndash; see [Excel demo](https://github.com/dotnet/samples/tree/main/core/extensions/ExcelDemo) or [Visio demo](https://github.com/dotnet/samples/tree/main/core/extensions/VisioDemo).

**Comment by rgwood** [comment]
Thanks for sharing those demo links! For some reason I was under the impression that the Office PIAs were incompatible with .NET Core, I'm very glad to be wrong about that.

**Comment by steel-li** [comment]
Ok，Thanks
