### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by YousefSaber** [dotnet/runtime#57611]
Ubuntu 21.04 

installed using snap 
```
dotnet-sdk               5.0.400                     137    latest/stable    dotnetcore✓  classic
```
snap version 
```
5.0.400
```
when creating a console template application I get this error 
```
(base) joseph@joseph-X541UJ:~/Documents/HelloWorldCS$ sudo dotnet new console
Segmentation fault
```

**Comment by jeffschwMSFT** [comment]
@YousefSaber can you capture a dump for this issue?  Thanks

**Comment by mangod9** [comment]
@kouvel who has investigated a similar issue in the past.

**Comment by YousefSaber** [comment]
> @YousefSaber can you capture a dump for this issue? Thanks

I don't understand? @jeffschwMSFT

**Comment by kouvel** [comment]
This is probably the same as another, see my comment there: https://github.com/dotnet/runtime/issues/51322#issuecomment-890306629

Until those issues are fixed, I would suggest uninstalling the snap dotnet and install it instead through the packages instead: https://docs.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

Closing since the other issue was closed due to prioritization, feel free to reopen if you have further questions.
