### ISSUE TITLE
HttpClient rejects valid certificates for dot-appended FQDNs

### ISSUE THREAD

**Issue by markdchurchill** [dotnet/runtime#57792]
### Description

HttpClient does not accept valid server certificates when a fully qualified domain name is used.

program.cs: `await new System.Net.Http.HttpClient().GetAsync("https://microsoft.com./");`

This should succeed. While not commonly used, the trailing `.` indicates that the host name is fully qualified and search suffixes should not be appended to support name resolution.

`microsoft.com` in the server certificate should match `microsoft.com.` as server identity in certs are implicitly full qualified.

### Regression?

Originally noticed this in some 4.7.2 code, tested on newer dotnet 6. Suspect this is likely an underlying http.sys issue.

### Workarounds

Obviously workarounds exist, this just can be a pain having to strip fqdns when building uris in iac.

**Comment by karelz** [comment]
Triage: We should try to reproduce and then find out if wildcard certificates should match this per RFC.

**Comment by wfurt** [comment]
any thoughts on this @bartonjs @vcsjones @blowdart ? 
I tested curl on Linux and Safari & Edge and they all work.

Curl puts 'www.microsoft.com' to SNI e.g. they may strip it before TLS. Safari & Edge leave original 'www.microsoft.com.' e.g. I would expect validation handles that.

**Comment by blowdart** [comment]
Which rfc covers this trailing dot?

**Comment by wfurt** [comment]
This is part of DNS: http://www.dns-sd.org/trailingdotsindomainnames.html pointing to https://www.ietf.org/rfc/rfc1034.txt

**Comment by bartonjs** [comment]
That does sound familiar from the days when I had to maintain some manual `bind` configuration :smile:.

It sounds reasonable to me, but if SChannel isn't doing it automagically it might be worth asking them why and if we're really expected to handle it ourselves.  (And then do whatever we need to do to unify the behavior across OSes).

**Comment by wfurt** [comment]
It is not only Schannel. It fails on .NET on Linux as well. (works OK on macOS)

**Comment by wfurt** [comment]
I also test with `curl` and it works without any error. The interesting difference is that `curl` sets 
```
Host: microsoft.com
```
but HttpClient use 
```
Host: microsoft.com.
```

so it looks like the normalization happens at HTTP layer before TLS even kicks in. 

I'm wondering if the proper fix is at HttpClient or even URI.
cc: @geoffkizer @scalablecory @MihaZupan

**Comment by markdchurchill** [comment]
> so it looks like the normalization happens at HTTP layer before TLS even kicks in.

This makes sense to me - the dot demonstrating intent in name resolution to prevent ambiguities in network connection - but not an HTTP specific concern.

FQDN usage should be allowed in a Uri, as that is a legitimate intent.

**Comment by karelz** [comment]
Triage: As @wfurt mentions above in https://github.com/dotnet/runtime/issues/57792#issuecomment-958401934 we should just strip the ending dot in HttpClient layer.

**Comment by ChrisFWood** [comment]
This appears to be two issues, first certificate validation and second the Host auto generation header.
Looking at the Host header
https://datatracker.ietf.org/doc/html/rfc7230#section-5.4

> If the target URI includes an authority component, then a
   client MUST send a field-value for Host that is identical to that
   authority component, excluding any userinfo subcomponent and its "@"
   delimiter

So by this the Host should include the `.`, and `curl` is technically wrong when it generates the header for you, but then some web server don't cope if the `.` is there.  So what is the correct thing to do here?

If you follow `curl` with the Host header generation you still need to fix the certificate validation as it uses the Host header if present and Host header can be manually assigned maybe because you need it to include the `.` or if it is not present it drops back to the URI IdnHost like the two places that current generate a Host header. I'm not yet sure why the Host header would not be present, at a guess it is HTTP version or execution sequence.

**Comment by greenEkatherine** [comment]
I tried to compare browsers with `curl`. For "www.microsoft.com." I see in request headers host "www.microsoft.com." However if I put the same query that was initially suggested "https://microsoft.com./" in Edge and Firefox - it failed with `ERR_CERT_COMMON_NAME_INVALID` or `SSL_ERROR_BAD_CERT_DOMAIN` respectively. `HttpClient` requires absolute Uri - does it mean that the second example is more relevant?

**Comment by wfurt** [comment]
I guess that really opens the question if `microsoft.com` and `microsoft.com.` are truly the same host. If they are, I would argue that the comment raised by @ChrisFWood  is really not applicable because they are the same. 
If we see them different, perhaps the behavior is correct e.g. the certificate owners _could_ issue certificate for "microsoft.com."  but they did not.

**Comment by ChrisFWood** [comment]
> I guess that really opens the question if `microsoft.com` and `microsoft.com.` are truly the same host.

They are by the way DNS defines FQDNs but I think you may have miss understood my point. The host header and the validation of the certificate are two separate issues. The host header RFC explicitly states it must be the authority as entered. The RFC6066 for TLS explicitly state that the hostname must exclude the training dot. So I would suspect a certificate would never be issued with a hostname with a trailing dot.

The host header is written out in  `WriteHostHeaderAsync` in `System\Net\Http\SocketsHttpHandler\HttpConnection.cs` this is working correctly by the RFC. But there is no need to change this to get the validation of the certificate to work.
The hostname used for that validation is calculated in `GetConnectionKey` in `System\Net\Http\SocketsHttpHandler\HttpConnectionPoolManager.cs` so to follow the TLS RFC the hostname used for comparison just needs the dot removing.
i.e. adding the line `sslHostName = sslHostName.TrimEnd('.');` after sslHostName has been defined from an explicit host header or from the IdnHost valid of the request URI.

**Comment by wfurt** [comment]
RFC6066 is TLS extension and does not talk about validation. However, I'm ok talking the argument that the SNI host is without trailing dot and treating rest of the usages identically.  With that the fix may be in 
https://github.com/dotnet/runtime/blob/39b4f2661f7ea5abbffcb1cb15e78363af9a81c7/src/libraries/System.Net.Security/src/System/Net/Security/SslAuthenticationOptions.cs#L26
so it works for non-HTTP protocols as well.

**Comment by greenEkatherine** [comment]
I applied the fix in ssl and my test with `HttpClient` failed with `BadRequest` "Invalid Hostname". I used default hostname in my test - https://corefx-net-http11.azurewebsites.net./ However, when I tried to run it with https://www.microsoft.com./ - it works fine. I'm wondering what could be the differences for these servers.

**Comment by wfurt** [comment]
You can reproduce it with `curl` as well
```
curl -kv -H "Host: corefx-net-http11.azurewebsites.net."  https://corefx-net-http11.azurewebsites.net./
< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=us-ascii
< Date: Tue, 07 Dec 2021 17:11:06 GMT
< Connection: close
< Content-Length: 334
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Hostname</h2>
<hr><p>HTTP Error 400. The request hostname is invalid.</p>
</BODY></HTML>
```
I think this is because the request is routed by Azure and it may see the extra dot as separate site ... and that is not configured. 
My recommendation would be to proceed with SslStream fix to close the validation issue. 
HTTP can be updated independently if needed. We can either do what Curl does (maybe not quite valid bu working) or let user to Set Host header if their site does not like the extra dot.

**Comment by ChrisFWood** [comment]
I would also say definitely fix the validation issue.
The host header not being accepted when it follows the RFC is a bug in the server (or just configuration) not the client's default generation of the header. There is a workaround that a consumer of client can use if for some reason they would need to use the trailing dot and the server has the bug that means it doesn't cope with the dot being there. While you could argue going the other way around and follow curl's example, it just feels wrong to me to add extra code to be run every request to explicitly ignore the RFC.
