### ISSUE TITLE
Regex SourceGenerator Feature Request: Named Capture Variables

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#57952]
I've heard that a Regex Source Generator is being considered.
It would be great if the source generator would turn named captures into properties on the Match.

For example, it would be really nice if I could do something like this:
```
var RX = new Regex(@"(?<Number>[\d]{9})  (?<Date>[\d]{2}/[\d]{2}/[\d]{4})  (?<Code>.*)");

if(RX.TryMatch(Input, out var Match)){
  Console.WriteLine($@"[{Match.NamedCaptures.Number}] {Match.NamedCaptures.Code} @ {Match.NamedCaptures.Date}");
}
```

What I am specifically hoping to avoid is writing a regex and then having to use a string to index into the named capture.

**Comment by stephentoub** [comment]
The goal for the regex source generator is it currently stands is to do at compile time when RegexOption.Compiled / Regex.CompileToAssembly do at run-time today, generating the optimized IL for parsing a particular regular expression.  This does not influence the Match type nor what members are exposed there. It's possible it could emit extension methods for Match, but they would end up showing up for every Match instance, regardless of whether they came from this particular Regex.  To do what you're asking, the source generator would effectively need to emit an entirely customized set of types for the whole regex-related object model, such that you use that instead of the built-in Regex types.  I don't expect we'll be pursuing that, at least not in .NET 7.

For reference, taking your example:
```C#
var RX = new Regex(@"(?<Number>[\d]{9})  (?<Date>[\d]{2}/[\d]{2}/[\d]{4})  (?<Code>.*)");
```
the current frontrunner design is you write code like:
```C#
[Regex(@"(?<Number>[\d]{9})  (?<Date>[\d]{2}/[\d]{2}/[\d]{4})  (?<Code>.*)")]
private static partial Regex CreateDateParser();
```
and the source generator implements that method, which you'd then use:
```C#
var RX = CreateDateParser();
```
All other consumption of your `RX` would be identical to what it is today.

**Comment by jeffhandley** [comment]
I'm going to close this as not feasible based on the goals/design of the source generator per @stephentoub's comment. @TonyValenti, please let us know if you think a different approach/feature should be considered here to accomplish what you're seeking.

Thanks.
