### ISSUE TITLE
Use Span<Char>.Fill in String(Char, Int32) constructor

### ISSUE THREAD

**Issue by jfd16** [dotnet/runtime#57993]
This would most likely be a significant performance improvement, especially with the vectorized span fill introduced in https://github.com/dotnet/runtime/pull/51365.

**Comment by GrabYourPitchforks** [comment]
@jfd16 Thanks for the suggestion! I've marked it up for grabs so that anybody can tackle it if they're interested. Or feel free to submit a PR if you're feeling up to it.

For whoever submits a PR: please also submit benchmarks demonstrating that this is a perf win for common use cases. Maybe try lengths of __1__, __2__, __5__, and __10__ as typical use cases (to mimic code which emits padding); or __4__, __8__, __12__, and __16__ (to mimic code which emits spaces as a tab char replacement).

**Comment by ahydrax** [comment]
@GrabYourPitchforks I can look into it. Could you assign this to me?

**Comment by adamsitnik** [comment]
Fixed by #57993

**Comment by GrabYourPitchforks** [comment]
@adamsitnik Did you mean to include a different link in your message above?

**Comment by adamsitnik** [comment]
> Did you mean to include a different link in your message above?

@GrabYourPitchforks Yes, I meant https://github.com/dotnet/runtime/pull/60269. Apologies for the confusion
