### ISSUE TITLE
[Regression] Json - Serialization and deserialization of 'System.Type' instances are not supported 

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#58006]
### Description

Using `System.Text.Json.JsonSerializer` and trying to serialize a class with a `System.Windows.Media.ImageSource` property results in `System.NotSupportedException: 'Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues`

### Configuration

.NET 6 (Preview 7)
x64 Windows WPF

### Regression?

Yes, this still works absolutely fine in .NET5

**Comment by eiriktsarpalis** [comment]
> Yes, this still works absolutely fine in .NET5

I can reproduce in both .NET 5 and .NET 6, here's a minimal repro in a WPF app:
```csharp
PixelFormat pf = PixelFormats.Bgr32;
int width = 200;
int height = 200;
int rawStride = (width * pf.BitsPerPixel + 7) / 8;
byte[] rawImage = new byte[rawStride * height];

// Initialize the image with data.
Random value = new Random();
value.NextBytes(rawImage);

// Create a BitmapSource.
ImageSource bitmap = BitmapSource.Create(width, height,
    96, 96, pf, null,
    rawImage, rawStride);

JsonSerializer.Serialize(bitmap);
```
Could you provide a reproduction that works in .NET 5 but fails in .NET 6?

This is by-design behavior, STJ will explicitly throw an exception if an attempt is made to serialize a `System.Type` in the object graph due to security issues associated with deserialization. The offending property in the case of WPF types is [this one](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyObjectType.cs#L128). Such types are not designed to be used in JSON serialization, if they really need to be serialized in your application I would recommend either using DTOs or authoring a custom JsonConverter for the required types.

**Comment by Symbai** [comment]
I will use JsonConverter
