### ISSUE TITLE
JsonStringEnumConverter ignores 'allowIntegerValues' when deserializing quoted numeric values

### ISSUE THREAD

**Issue by DenisAloner** [dotnet/runtime#58247]
**.NET 5**
JsonStringEnumConverter ignores JsonNumberHandling.Strict on deserialization.
Example: https://dotnetfiddle.net/IsP6Dn

**Comment by wsugarman** [comment]
Back to the original question, I think allowing integers encoded as strings violates the spirit of this parameter. For example, developers may use `JsonStringEnumConverter` in their ASP.NET Core projects such their users can specify enumeration names in the request body. This is great because the names are much more description than using numbers. However, I think developers may also assume that they've also decoupled their enum integral values from their web APIs, but this isn't the case. A user could still pass the integral values as strings and successfully bind to the model.

I understand that accepting both the string and integral representations has precedence with use cases like [`Enum.TryParse`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=net-5.0#System_Enum_TryParse__1_System_String___0__), but personally I would like the option to impose more strictness on my JSON parsing. It would be a welcomed addition if this was provided out-of-the-box.

**Comment by eiriktsarpalis** [comment]
Moving to Future, as we won't have time to work on this in the .NET 7 timeframe.

**Comment by layomia** [comment]
Up for grabs. I believe the fix here would be to enforce that only named constants are permitted when reading enum values as strings and `allowIntegerValues` is false.

The relevant code would need to be added to this [method](https://github.com/dotnet/runtime/blob/1abc433c5f18a8e5f889739b983c55903ffc6722/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L112-L125).

**Comment by davisnw** [comment]
As of 2022-12-19, the documentation at https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter.-ctor?view=net-7.0#system-text-json-serialization-jsonstringenumconverter-ctor(system-text-json-jsonnamingpolicy-system-boolean) states:

>**`allowIntegerValues`** [Boolean](https://learn.microsoft.com/en-us/dotnet/api/system.boolean?view=net-7.0) 
>
>`true` to allow undefined enum values; otherwise, `false`. When `true`, if an enum value isn't defined, it will output as a number rather than a string.

This clearly implies that you should never receive undefined enum values when parsing with `allowIntegerValues: false`.

I could see this discrepancy leading to security vulnerabilities in some api usage contexts.

(Note: for some reason the links to file feedback on the documentation via github is not available for that page)

**Comment by ckarcz** [comment]
workaround for now https://stackoverflow.com/a/74890774/929401

**Comment by eiriktsarpalis** [comment]
The fix is technically a breaking change since disabling integers no longer accepts strings containing integers. The workaround is trivial (just enable integers) but we should still document it.
