### ISSUE TITLE
System.Text.Json source gen containing non-localized error messages

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#58292]
For example https://github.com/dotnet/runtime/blob/3e6d492bdf6fbf2d8af3871379f31dcc6e27716b/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L793
We should find all such messages and localize them.

**Comment by steveharter** [comment]
We need to determine if these error messages are displayed at design-time. If they occur at design-time they should be localized.

However, in the referenced example above, the exception with the non-localized message occurs at run-time within the generated code which I believe should not be localized because we don't localize other exception messages in STJ that occur at run-time. In theory, at run-time the generated code and STJ are interchangeable (logic could exist on either side, and may change in the future) and should be indistinguishable from the user and thus should throw non-localized exception messages.
