### ISSUE TITLE
ASP.NET 4.8 EventCounter does not contain methods

### ISSUE THREAD

**Issue by esyker** [dotnet/runtime#58408]
I am using the code from the documentation present at this link.:

[https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counter-perf](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counter-perf).

The code is this:
```
using System.Diagnostics.Tracing;

[EventSource(Name = "Sample.EventCounter.Minimal")]
public sealed class MinimalEventCounterSource : EventSource
{
    public static readonly MinimalEventCounterSource Log = new MinimalEventCounterSource();

    private EventCounter _requestCounter;

    private MinimalEventCounterSource() =>
        _requestCounter = new EventCounter("request-time", this)
        {//does not work
            DisplayName = "Request Processing Time",
            DisplayUnits = "ms"
        };

    public void Request(string url, long elapsedMilliseconds)
    {
        WriteEvent(1, url, elapsedMilliseconds);
        _requestCounter?.WriteMetric(elapsedMilliseconds);
    }

    protected override void Dispose(bool disposing)
    {
        _requestCounter?.Dispose();//does not work
        _requestCounter = null;

        base.Dispose(disposing);
    }
}
```

However, when I use the code on VS2019 the IDE imeddiatly tells me that EventCounter class does not contain .Dispose() method and also the DisplayName and DisplayUnits properties.
These are the lines that give problems:
```
private MinimalEventCounterSource() =>
        _requestCounter = new EventCounter("request-time", this)
        {//does not work
            DisplayName = "Request Processing Time",
            DisplayUnits = "ms"
        };

protected override void Dispose(bool disposing)
    {
        _requestCounter?.Dispose();//does not work

```

When I inspected the class, this is in fact true. The definition of the class just contains this:
```
namespace System.Diagnostics.Tracing
{
    //
    // Summary:
    //     Provides the ability to collect statistics for very frequent events through the
    //     System.Diagnostics.Tracing.EventSource class.
    public class EventCounter
    {
        public EventCounter(string name, EventSource eventSource);

        public void WriteMetric(float value);
    }
}
```
 Why is the official example from Microsoft not working? Is this related to my run-time version which is different from the example which is .NET core (mine is ASP.NET framework 4.8 WebForms).

**Comment by tommcdon** [comment]
@josalem  @mikelle-rogers

**Comment by hoyosjs** [comment]
`EventCounter` extends `DiagnosticsCounter` which exposes both of those properties and also implements `IDisposable`, and does so for core and standalone. You can see that in [`DiagnosticsCounter.DisplayUnits`](https://source.dot.net/#System.Private.CoreLib/DiagnosticCounter.cs,2a05b0bc6c90df89). So the code linked in the article you linked works. 

However, if you looks at the .NET framework docs for [EventCounter](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventcounter?view=netframework-4.8) doesn't derive from anything and doesn't implement IDisposable. The tutorial you linked is for .NET Core, says `.NET Core 3.0 SDK and later versions`, and links a sample that's a .NET Core 3.1 sample app.  So as you say, the problem is the sample really only applies to .NET Core and .NET 5+.

**Comment by josalem** [comment]
I don't think there is anything actionable in this issue. If that's not the case we can reopen.
