### ISSUE TITLE
[libraries][Android] System.Security.Cryptography.X509Certificates No IndexOutOfRangeException thrown

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#58416]
```
System.Security.Cryptography.X509Certificates.Tests.CollectionTests.X509ChainElementCollection_CopyTo_NonZeroLowerBound_ThrowsIndexOutOfRangeException
    Assert.Throws() Failure\nExpected: typeof(System.IndexOutOfRangeException)\nActual:   (No exception was thrown)
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1329092&view=logs&j=b6e5d97f-d4f8-506b-9e47-e3e32385754a&t=94ce2805-f3e2-5f9a-1d92-0da5613f733d

**Comment by akoeplinger** [comment]
This started failing on an unrelated commit.

**Comment by akoeplinger** [comment]
Looks to be because the `MicrosoftDotComSslCertBytes` has a `NotAfter=2021-08-29 00:17:02` and that causes the chain to be empty.

For some reason this only fails on Android, I assume because it uses the Java native crypto APIs and they handle loading these expired certificates differently than openssl.

@bartonjs can we regenerate that cert bytes?

**Comment by akoeplinger** [comment]
Ah looks like this is indeed expected on Android according to this comment:
https://github.com/dotnet/runtime/blob/3716919e21842e583881d53290ca93bd703951ec/src/libraries/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs#L496-L501

Given this test isn't about the cert validity I think we can just set the VerificationTime like we do elsewhere, will open a PR.
