### ISSUE TITLE
System.Drawing Image.Save(Stream stream, ImageFormat format) produces different results in linux and windows

### ISSUE THREAD

**Issue by oliinyka** [dotnet/runtime#58496]
### Description

The Image.Save(Stream stream, ImageFormat format) saves an image to an input stream. However, the data inside the steam is different in windows and linux. 
Sample code:

using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace DrawingTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var bitmap = new Bitmap(10, 10, PixelFormat.Format32bppArgb);
            bitmap.SetResolution(96.0F, 96.0F);
            var bitmapStream = new MemoryStream();
            // Save the image.
            bitmap.Save(bitmapStream, ImageFormat.Png);
            bitmapStream.Flush();
            var data = bitmapStream.ToArray();
            int i = 0;
            foreach (var item in data)
            {
                Console.WriteLine($"item {i} : {item}");
                i++;
            }
            Console.ReadLine();
        }
    }
}

Number of bytes in array in windows is 121 and in linux its 143. 
You can check it using this Dockerfile:
FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
RUN apt-get update && apt-get install -y libgdiplus
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
COPY . .
WORKDIR /src
COPY ["DrawingTest/DrawingTest.csproj", "DrawingTest/"]

RUN dotnet restore "DrawingTest/DrawingTest.csproj"
COPY . .
WORKDIR "/src/DrawingTest"
RUN dotnet build "DrawingTest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DrawingTest.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DrawingTest.dll"]

I would expect same behavior in both OS - MemoryStream byte array should contain same values. 

### Configuration

Using Windows 10 pro 19043.1165 and mcr.microsoft.com/dotnet/runtime:5.0 image for linux run.
using .net5

**Comment by filipnavara** [comment]
The Linux and Windows versions are backed by a different library. There's no guarantee that the output of this operation will be byte identical, just that it will be semantically identical. It can easily produce different compression or different header blocks.

Furthermore, starting with .NET 6 the System.Drawing package is marked as obsolete on non-Windows platforms due to longterm lack of maintenance of mono/libgdiplus and its associated distribution packages. It is recommended to switch to different library such as ImageSharp or SkiaSharp.

**Comment by tarekgh** [comment]
@oliinyka please review the doc https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md for more info regarding moving forward. As @filipnavara mentioned, please consider using ImageSharp or SkiaSharp on non-Windows platforms. Thanks.

**Comment by danmoseley** [comment]
@oliinyka is this difference causing functional issues, eg., an image is corrupted, and if so on which OS? If Windows, does it repro on .NET Framework too?

As mentioned above, we are removing Linux implementation of this library, so we would likely not fix anything Linux specific and we can close this. For Windows, we will continue support but have a relatively high threshold for making fixes as this library has been stable for a long time.

**Comment by oliinyka** [comment]
@danmoseley we are doing a migration from .net framework 4.7.2 windows services to .net5 linux containers.  After migration to .net5 our code works same way in windows but when we run it in linux container Save method produces different result. It can be a problem, as this byte array is used for further image processing. We just started the migration, currently it just breaks the tests, so not sure if it breaks real images.

**Comment by tarekgh** [comment]
@oliinyka could you start using libraries like ImageSharp or SkiaSharp on Linux to avoid the break again when you migrate to .NET 6.0 later? Let's know if there is anything will be blocking doing that. Thanks!

**Comment by koszeggy** [comment]
@oliinyka: It is known that the encoders and decoders under Linux behave a bit differently. In fact, sometimes the Linux ones are better, eg. on Linux, when loading an 8 bpp PNG with partial transparency, the pixel format and the palette is [correctly preserved](https://github.com/koszeggy/KGySoft.Drawing.Tools#compatibility), whereas on Windows, the same PNG is loaded with a 32bpp ARGB pixel format, with no palette.

To compare the outputs produced on different platforms you need to compare the _pixels_ instead of the raw content. But please be aware that even such a test may fail with some ecoders, eg. some might not preserve transparency on Linux or they might handle premultiplied pixel formats differently, etc. Once I [collected](https://docs.kgysoft.net/drawing/?topic=html/M_KGySoft_Drawing_ImageExtensions_ConvertPixelFormat_1.htm) all the known differences (see the table under **Restrictions of Possible Pixel Formats on Different Platforms**) and also created a bunch of `SaveAs*` methods (an [example](https://docs.kgysoft.net/drawing/?topic=html/M_KGySoft_Drawing_ImageExtensions_SaveAsPng.htm) for PNG), in order to correct or minimize the issues on all platforms. (Available as a [NuGet package](https://www.nuget.org/packages/KGySoft.Drawing/) if you whish use it)

But as @filipnavara suggests you can try to migrate to 3rd party libraries that don't use `System.Drawing`. If you still insist using `System.Drawing` even on Linux, please be warned that starting with .NET 6 they throw a `PlatformNotSupportedException` by default as @tarekgh [mentioned](https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md). To avoid that without messing with the `runtimeconfig.json` file you have to place the following piece of code before accessing any `System.Drawing` types that use GDI+:

```cs
if (!(Environment.OSVersion.Platform is PlatformID.Win32NT or PlatformID.Win32Windows))
    AppContext.SetSwitch("System.Drawing.EnableUnixSupport", true);
```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
