### ISSUE TITLE
Inbox assets which ship as part of packages aren't crossgend

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#58500]
Today, these libraries ship as part of the shared framework and inside packages:
- System.Collections.Immutable
- System.Diagnostics.DiagnosticSource
- System.Formats.Asn1
- System.Net.Http.Json
- System.Reflection.Metadata
- System.Runtime.CompilerServices.Unsafe
- System.Text.Encoding.CodePages
- System.Text.Encodings.Web
- System.Text.Json
- System.Threading.Channels
- System.Threading.Tasks.Dataflow

Whenever these packages are consumed and the libraries in it have a higher assembly- and fileversion than what's in the shared framework, "conflict resolution" (SDK) prefers them (regardless of the TFM). In reality that means that whenever someone on an older shared framework (including the same release) references the newest version of these packages, the Ready-to-Run optimization inside the shared framework is lost. Example:

A.csproj targets net5.0 and builds with the latest shared framework (5.0.9 as of time of writing). The project either directly or transitively references the 6.0.0 "System.Text.Json" package. As the assets in that package have a higher assembly version, the System.Text.Json.dll from the package wins over its pendant in the shared framework. As the asset from the package isn't crossgend, the Read-to-Run optimization is lost.

Opening this issue to discuss if we can mitigate the mentioned performance regression somehow. Presumably when creating a self-contained application and setting the R2R flag, the asset from the package should still get crossgend so this is primarily a concern when not publishing self-contained and without crossgen.

cc @vitek-karas @eerhardt @stephentoub

**Comment by jkotas** [comment]
> Opening this issue to discuss if we can mitigate the mentioned performance regression somehow.

The app author can crossgen the application if they want to. It will make their application platform specific and the binaries bigger.

I think our guidance should be to stick with the inbox versions of these assemblies, and pick up version updates by updating the whole runtime. The piecemeal updates of the inbox versions of these assemblies should be a last resort solution for complex versioning problems.

**Comment by ViktorHofer** [comment]
> I think our guidance should be to stick with the inbox versions of these assemblies, and pick up version updates by updating the whole runtime. The piecemeal updates of the inbox versions of these assemblies should be a last resort solution for complex versioning problems.

Discussed this with @eerhard just yesterday:

In some cases this isn't possible as these packages might get into the graph transitively.
Imagine someone writes a .NETStandard library which ships on NuGet. The library references 5.0.1 of System.Text.Json without any particular reason but because the NuGet Package Explorer in Visual Studio makes it so easy to always update to the latest version of packages.
When you then package reference that package, you get the 5.0.1 version of System.Text.Json as it's a transitive dependency.

I can mostly speak from my experience in University, when we created .NET applications inside VS. Everyone kept their package dependencies up-to-date

**Comment by jkotas** [comment]
Experienced NuGet package authors are careful about versions of their dependencies and often try to keep them as low as possible to maximize adoption and avoid problems like you have described. I agree that less experienced NuGet package may not be thinking through the consequences of picking latest versions.

> NuGet Package Explorer in Visual Studio makes it so easy to always update to the latest version of packages.

Maybe it should it also update the runtime version to latest?

**Comment by ViktorHofer** [comment]
The other example where this falls apart is when someone on .NET 5 consumes 6.0.0 packages (which is a valid scenario) i.e. to leverage new features in System.Text.Json that are available on all targets (including .NET Standard).

> Maybe it should it also update the runtime version to latest?

Can you please elaborate?

**Comment by jkotas** [comment]
> Can you please elaborate?

.NET 5 + System.Text.Json 6.0 is a valid scenario, we should make sure that it works as expected, but it is always going to be sub-optimal. We should drive people away from falling into this sub-optimal configuration by accident. I am suggestion that when the NuGet package explorer updates all package versions to latest, it should also update or suggest updating the netcoreapp version to latest to avoid this sub-optimal configuration.

**Comment by ericstj** [comment]
This has been the case for all past releases since .NETCore 1.0 (and technically even before that when we were OOBing on .NETFramework and NGEN).  It's a very intentional tradeoff: we allow ourselves to remain agile in API by shipping new versions in packages that can add new API even on old frameworks, at the cost of those new packages not being optimized.  I don't think we'd want to start carrying crossgen'ed images for every framework and every runtime in the nuget packages, or constrain ourselves to only adding API in the latest framework in these packages.  The toolchain already has support for folks that wish to cross-gen app code to enable that for their app.

I don't think the *only* case here is inexperienced NuGet authors accidentally crossing servicing bands.  These libraries are specifically developed to target `netstandard2.0` and we have customers (in Microsoft and outside) who intentionally depend on the the latest versions even for old frameworks.

Additionally, servicing will cause this behavior even within a band when we service that package.  Folks (correctly) to reference the serviced package.  Since the SDK cannot assume the serviced package will be present on all machines (even though we also service the shared framework) the assembly will go app local.  There won't be a performance penalty on a serviced runtime as it does runtime conflict resolution, but apps do pay a size penalty.

I'm not sure the right solution is discouraging folks to update packages.  IMO we should just make it easier to recognize when they might benefit from cross-gen.

**Comment by ViktorHofer** [comment]
Closing per the discussion above. This is by design.
