### ISSUE TITLE
Certificate SHA1withRSA encryption method dotnet Framework and dotnet core calculation results are inconsistent

### ISSUE THREAD

**Issue by 1290690484** [dotnet/runtime#58705]
### Description

Can anyone help me? The above code runs in the above environment list The result is not the same?
I can't upgrade dotnet core because of this.

 ```C#
 public static string SignatureMessage(string certFileName, string password, byte[] dataTobeSign)
    {
        byte[] pfxCert = File.ReadAllBytes(certFileName);
        SecureString pwd = new SecureString();
        char[] pwdCharArray = password.ToCharArray();
        for (int i = 0; i < pwdCharArray.Length; i++)
        {
            pwd.AppendChar(pwdCharArray[i]);
        }

        X509Certificate2 cert = new X509Certificate2(pfxCert, pwd);

        CmsSigner signer = new CmsSigner(cert);
        signer.DigestAlgorithm = new Oid("1.3.14.3.2.26", "sha1");
        signer.IncludeOption = X509IncludeOption.EndCertOnly;

        ContentInfo signedData = new ContentInfo(dataTobeSign);
        SignedCms cms = new SignedCms(signedData, true);
        cms.ComputeSignature(signer);
        byte[] signature = cms.Encode();
        return Convert.ToBase64String(signature);
    }
 ```

[Completed issue reproduction dome github link](https://github.com/1290690484/DotNetCoreSignError)

### Configuration
dotnet core 3.1

dotnet Framework v4.6.1

**Comment by filipnavara** [comment]
Are you saying that the byte output is different or that the signature is not mutually accepted? The byte output could be different due to small differences in the encoding wrt. the specification. You can check the semantic output by pasting the encoded base64 string into https://lapo.it/asn1js/. 

There was more than one instance where the output differs because the specification changed and there's more than one way to encode something (with one of the encodings being preferred). Additionally, there were specific incompatibilities between the Unix/Windows versions of the code (eg. https://github.com/dotnet/runtime/commit/9cc7ba4c0d364024f71a3aea46c2dd9e5246163a#diff-3bbda86be023c218ee859a0b171c1845d7609139a9f4a1d950dfce12b016c992) but the resulting documents should still be interchangable.

**Comment by 1290690484** [comment]
@filipnavara 
That means the subtle encoding differences can be decoded successfully by the parsing side of java, right? I just tried it. It's not the same, but the interactive side can still check the signature successfully

**Comment by filipnavara** [comment]
> That means the subtle encoding differences can be decoded successfully by the parsing side of java, right?

Correct, it should be interoperable.

**Comment by bartonjs** [comment]
> It's not the same, but the interactive side can still check the signature successfully

Since it sounds like the bigger issue (interoperability) isn't a problem, and the byte-for-byte stability isn't a guarantee, that there's nothing left here, so I'm going to close the issue.

If I missed something, the reopen button is easy to push :smile:.
