### ISSUE TITLE
StreamReader.ReadLineAsync cannot quit even if Close() is called.

### ISSUE THREAD

**Issue by wzzdzr** [dotnet/runtime#58713]
### Description

StreamReader.ReadLineAsync cannot quit even if Close() is called.

### Configuration

Which version of .NET is the code running on?  netcoreapp 3.1
What OS and version, and what distro if applicable? Windows 10

### Reproduce

```
      Pipe pipe = new Pipe();

      StreamReader reader = new StreamReader(pipe.Reader.AsStream(false));

      Task cancelTask = Task.Run(async () =>
      {
          await Task.Delay(5000);
          Console.WriteLine("Try to close streamReader.");
          reader.Close();
          Console.WriteLine("StreamReader closed");
      });

      string line;
      while (true)
      {
          Console.WriteLine("begin to read");
          line = await reader.ReadLineAsync();
          Console.WriteLine("end read.");
          Console.WriteLine(line);
      }
```

And output is as below
> begin to read
Try to close streamReader.
StreamReader closed

I think StreamReader.ReadLineAsync should be able to quit when streamReader is closed.

**Comment by wzzdzr** [comment]
I test for another scenario. And It seems that it is due to different provided Stream.

```
StringContent content = new StringContent("test\ntest\n");
StreamReader reader = new StreamReader(await content.ReadAsStreamAsync());
```

And ReadLineAsync can throw exception as I hope.

**Comment by Jozkee** [comment]
StreamReader.ReadLineAsync passes CancellationToken.None to the underlying stream.Read call, that's why it hangs until the stream actually returns something, which in your case will never happen. 
https://github.com/dotnet/runtime/blob/1dc8dfa0058396495203e18ddc7f8a632d72c165/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs#L870

I think changing from Cancellationtoken.None to something else would be a breaking change, so I don't think we can change that.

Could you be able to use StreamReader.ReadAsync and pass a CancellationToken bound to a CancellationTokenSource? The problem is that you will need to handle the logic of splitting the buffer into lines, at least until this gets closed https://github.com/dotnet/runtime/issues/20824.

```cs
using System.IO.Pipelines;

Pipe pipe = new Pipe();

StreamReader reader = new StreamReader(pipe.Reader.AsStream(false));
var cts = new CancellationTokenSource();

Task cancelTask = Task.Run(async () =>
{
    await Task.Delay(5000);
    Console.WriteLine("Try to close streamReader.");
    reader.Close();
    cts.Cancel();
    Console.WriteLine("StreamReader closed");
});

string line;
while (true)
{
    Console.WriteLine("begin to read");
    var buffer = new char[1024];
    await reader.ReadAsync(buffer, cts.Token);
    line = new string(buffer);
    Console.WriteLine("end read.");
    Console.WriteLine(line);
}
```

cc @stephentoub in case he has a better alternative to this.
