### ISSUE TITLE
regex: different behavior between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/runtime#58757]
_While copy/pasting a regex (don't judge me 😁) from a .NET Framework to a .NET 5.0 project alongside with the associated tests, I was surprised to see the exact same tests failing only with .NET Core._

I created a sample project ([TestRegex.zip](https://github.com/dotnet/runtime/files/7122419/TestRegex.zip)) with the following class:

```csharp
using NUnit.Framework;
using System.Text.RegularExpressions;

public class TestRegex
{
    internal static readonly Regex HttpUrlRegex = new Regex(@"\b(?>(?>[\w-]+:\/\/?|www[.])[^\s()<>]+(?:\([\w\d]+\)|(?>[^[:punct:]\s]|\/)))", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);

    [TestCase(@"www.example.com dummy text", @"www.example.com")]
    [TestCase(@"www.example.com/myrequest dummy text", @"www.example.com/myrequest")]
    [TestCase(@"www.example.com/myrequest/test dummy text", @"www.example.com/myrequest/test")]
    [TestCase(@"www.example.com/myrequest?get=yes dummy text", @"www.example.com/myrequest?get=yes")]
    [TestCase(@"dummy text http://example.com.", @"http://example.com.")]
    [TestCase(@"dummy text https://example.com.", @"https://example.com.")]
    public void Test_auto_detect_urls(string text, string url)
    {
        var matches = HttpUrlRegex.Matches(text);
        Assert.AreEqual(1, matches.Count, "Detections count incorrect");
        Assert.AreEqual(url, matches[0].Value, "URL is invalid");
    }
}

```

And here is the test results execution:

![image](https://user-images.githubusercontent.com/15875066/132365591-2fd752e5-49c4-4eac-a8bf-128c643c6e0d.png)

(Side note 1: it seems the execution is slower but it would require a proper benchmark)

The regex in question can be checked here: https://regex101.com/r/emMYNP/1 

(Side note 2: the behavior is a bit different than with .NET Framework)

**Comment by jairbubbles** [comment]
(.NET6 version is 6.0.100-preview.7.21379.14)

**Comment by stephentoub** [comment]
.NET doesn't (and never has) supported POSIX bracket expressions, so the `[:punct:]` in your expression isn't doing what you expect it to be doing (https://github.com/dotnet/runtime/issues/22401), on either .NET Framework or .NET Core.  You can use `\p{P}` instead.  I expect the difference in behavior you're seeing is due to bug fixes related to parsing that are influencing how that is being handled.

**Comment by danmoseley** [comment]
It would be interesting if you could simplify your regex and text down as far as possible. I would expect you can make it quite short and still see the divergent behavior. Then we could confirm it's a bug fix.

**Comment by jairbubbles** [comment]
Thx @stephentoub, it works great with `\p{P}`:
![image](https://user-images.githubusercontent.com/15875066/132440546-23d13ef9-3fff-4bec-a6bb-b3242f015fd4.png)

As it's not supported I would expect it to thrown when building the RegEx but I guess it's not that simple.

> It would be interesting if you could simplify your regex and text down as far as possible.

I'll give it a shot.

**Comment by jairbubbles** [comment]
It all goes down to `[:punct:]` which is handled differently between both frameworks but never properly.

In .NET Framework, `[:punct:]` seems to be ignored in the list of possible values but other values in the list won't be ignored.
In .NET Core, the list nevers matches anything as soon as there `[:punct:]` in it.

To sum up, these tests will only pass with .NET Framework:
```csharp
Assert.IsTrue(Regex.IsMatch("test", @"[\w[:punct:]]+"));
Assert.IsTrue(Regex.IsMatch("toto", @"[^[:punct:]]+"));
```

**Comment by danmoseley** [comment]
Our parser requires that a close square bracket in a character class be escaped. So the regex is parsed as a character class containing these literal chars `\w[:punct` followed by `]+`. This doesn't match "test". If I change the pattern to escape it, it works: `[\w[:punct:\]]+`

This means if we were to support classes like `[something]` then it would break some existing behavior because today we assume an unescaped close bracket in a character class is literal, even if there's a matching open bracket.

Looks like we tweaked the parser to fix this but I'd have to check on the change.

I'm going to close this since it's understood and you have a fix but thanks for the report.
