### ISSUE TITLE
DOTNET_ROLL_FORWARD=Major ignores in new builds of .net 6 since preview 7 

### ISSUE THREAD

**Issue by grinay** [dotnet/runtime#58754]
Hi. I'm using the global environment variable DOTNET_ROLL_FORWARD=Major and I'm able to run .net 3,5 projects on my Mac machines with m1 CPU. But since preview 7 this variable seems to be ignored and I'm unable to run .net 3,5 projects with new versions.
The version which I using currently dotnet-sdk-6.0.100-preview.6.21355.2-osx-arm64.pkg , but after update to
dotnet-sdk-6.0.100-rc.2.21454.3-osx-arm64 or dotnet-sdk-6.0.100-preview.7.21379.14-osx-arm64.pkg project builds correct but it can't be run anymore and fails with error

Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib, 1): no suitable image found. Did find:
/usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib: mach-o, but wrong architecture
/usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib failed

Installing .NET prerequisites might help resolve this problem.

**Comment by ViktorHofer** [comment]
cc @vitek-karas

**Comment by vitek-karas** [comment]
I assume you're running your app via `dotnet run` - as I can't think of another case where the behavior changed.

The change we made was that we enable apphost on all apps in the .NET 6 SDK. Since 3.1 only supports x64, I assume the apphost it built as x64 and then when the app is trying to run, it does so as x64. Since you only have arm64 runtime, it fails.

We were able to do this since we now default-sign the apphost always (so that M1 macOS doesn't complain about lack of signature).

This should be sort of fixed at RTM when we have installers for both .NET 6 and .NET 3.1 updated for arm64 macOS so that they can correctly coexist. See this description of how to set it up now (manual process, until the installers are put in place): https://github.com/dotnet/sdk/issues/20584). It would still require you to install .NET Core 3.1 runtime, or .NET 6 x64 (3.1 apps are not really supported on arm64).

Alternatively you can do either:
* Set `UseAppHost=false` in your project - this will effectively revert the change we've made and should get you back into the state you were in before
* Run your app via `dotnet <path>/app.dll` which will ignore the apphost (the `app` executable). With this approach you should also not need to set the environment variable and instead you can specify the roll forward on the command line `dotnet --roll-forward major <path>/app.dll`

/cc @mateoatr

**Comment by skyflyer** [comment]
Not related to roll-forward, but I had the same error after installing latest preview on Mac M1 (with existing 5.0.9). A coworker with the same 6 preview does not have this issue.

Note: the issue is present when running a program with target framework `net5.0` and none of the workarounds work. I had to uninstall preview 6 **and** net 5 SDK and runtime to get it working again. Perhaps also related to #11164.

**Comment by vitek-karas** [comment]
@skyflyer what you describe is very likely due to having both .NET 5 and .NET 6 but different architectures. I assume you installed .NET 5 x64 and then .NET 6 arm64 (or reverse order) - currently the installers are not clever enough to recognize this layout the bits on disk correctly (the desired layout is described in the sample from Rich here https://github.com/dotnet/sdk/issues/20584).

Unfortunately the end result is that basically no app will work. And the only way to fix this is to remove everything and install only one of the two (or do the manual install described in the issue above).

**Comment by grinay** [comment]
@vitek-karas Thanks. Using UseAppHost in the project file really helps. The project now runs as before.
