### ISSUE TITLE
[API Proposal]: Add `System.Reflection.Metadata.Ecma335.ControlFlowBuilder.Reset`.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#58765]
### Background and motivation

One of the very few reference types in S.R.M, the `ControlFlowBuilder` class is an obstacle to low-allocation code, since it requires allocating one object of this type for each emitted method.

I propose to add a public method that resets `ControlFlowBuilder` objects, allowing consumers to reduce allocations by reusing them.

Such method already exists but it's internal and unused. It is named `Clear` but I think `Reset` is better since it's a more abstract word that more directly conveys what it does (and there are many other `Reset` methods with a similar purpose throughout the framework).

### API Proposal

```C#
namespace System.Reflection.Metadata.Ecma355
{
     public sealed class ControlFlowBuilder
     {
          public void Reset();
     }
}
```

### API Usage

```C#
BlobBuilder bb = /* ... */;
ControlFlowBuilder cfb = new ControlFlowBuilder();

EmitMethod1(bb, cfb);
cfb.Reset();
EmitMethod2(bb, cfb);
```

### Risks

No known risks.

**Comment by teo-tsirpanis** [comment]
Is there anything that prevents the proposal from going forward? It looks like a pretty small change.

**Comment by buyaa-n** [comment]
The proposal looks useful, but i would keep the API name `Cleear()` because
1. The `BlobBuilder` builder has `Clear()` method for similar purpose https://github.com/dotnet/runtime/blob/836f2c546a8c4ceb76dcb70abcf74fa6a98fe825/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/BlobBuilder.cs#L76
2. The existing internal `ControlFlowBuilder.Clear()` is just clearing the internal collections: https://github.com/dotnet/runtime/blob/836f2c546a8c4ceb76dcb70abcf74fa6a98fe825/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/Encoding/ControlFlowBuilder.cs#L88-L93

**Comment by terrajobst** [comment]
* Makes sense, but we'd prefer the term `Clear`

```C#
namespace System.Reflection.Metadata.Ecma355
{
     public partial sealed class ControlFlowBuilder
     {
          public void Clear();
     }
}
```

**Comment by tmat** [comment]
lgtm
