### ISSUE TITLE
[API Proposal]: Rename misleading members of TimeSpan

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [dotnet/runtime#58848]
### Background and motivation

Members like `Hours` in `TimeSpan` can be misleading. I have been bitten by this earlier. Please see [this SO answer](https://stackoverflow.com/a/241189/742775) and its upvotes and comments.

My suggestion is: 

- New members can be added with names that prevent such mistake. I do not have a concrete naming suggestion, but `HoursOnly`, `HoursOfDay`, `HourPart`, etc can be good, I'm sure you can come up with great names.
- Deprecate and eventually remove old members

### API Proposal

```C#
public readonly struct TimeSpan : ...
{
        --- public int Hours { get; }
        +++public int HoursOnly { get; }
}
```     

### API Usage

```
var a = TimeSpan.FromHours(20);
var b = TimeSpan.FromHours(16);
var c = a + b;
c.Hours; //Expect 36, get 12
c.TotalHours // 36
```
### Risks

Normal risks associated with renaming a public API: breaking changes, etc.

Same is true for Minutes, Seconds, etc.

**Comment by Symbai** [comment]
I don't find this misleading at all. When there is something named as "Total" and something else not, it's perfectly clear to me that one returns all and the other don't. Introducing a breaking change for something like this is ridiculous given the fact that many other really useful API suggestions have been declined because of breaking existing code (for example to return all modules in Process.Modules when called from a 32bit process instead of just only 32bit modules).

**Comment by AlirezaHaghshenas** [comment]
@Symbai I agree that a breaking change should not be taken lightly, and I'm totally fine if this is rejected for that.

But having the assumption that people will search all members before hitting enter on `Hour` is unrealistic. So is assuming that people know all members of a type, or read the whole document before using a type.

**Comment by Symbai** [comment]
> @Symbai I agree that a breaking change should not be taken lightly, and I'm totally fine if this is rejected for that.
> 
> But having the assumption that people will search all members before hitting enter on `Hour` is unrealistic. So is assuming that people know all members of a type, or read the whole document before using a type.

Why would you say that? First of all with intellisense if you type `hour` it shows BOTH properties, I find it rather unrealistic to say that they will close their eyes after typing and blindly hit return. 
![image](https://user-images.githubusercontent.com/14368203/132781612-003d5019-015e-4520-af1a-1a09b8f585eb.png)

And second if you are using a class you don't know at all, of course you read the docs (at least the first page) but on docs it also shows all properties. I agree that the name schema is not the best but renaming something and making it a breaking change only because people refuse to use their eyes isn't a very strong argument in my opinion.

**Comment by AlirezaHaghshenas** [comment]
I agree with your point about intellisense.

**Comment by danmoseley** [comment]
I think this is resolved. Users should see both in intellisense. Thanks for the suggestion.
