### ISSUE TITLE
JIT still seems to be hoisting some modified indirs

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#58877]
```csharp
// Generated by Fuzzlyn v1.4 on 2021-09-09 16:16:00
// Run on .NET 7.0.0-dev on X64 Windows
// Seed: 9372673482466191512
// Reduced from 87.8 KiB to 1.2 KiB in 00:02:21
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    public static void Main()
    {
        ushort[] vr3 = new ushort[]{0};
        for (int vr4 = 0; vr4 < 2; vr4++)
        {
            vr3[0] = 1;
            var vr5 = new byte[][][][]{new byte[][][]{new byte[][]{new byte[]{1}, new byte[]{1, 1}}}, new byte[][][]{new byte[][]{new byte[]{1, 1}, new byte[]{1, 1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}, new byte[]{1}}, new byte[][]{new byte[]{1}}}, new byte[][][]{new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}, new byte[]{1}}, new byte[][]{new byte[]{1}, new byte[]{1}, new byte[]{1}}, new byte[][]{new byte[]{1}}}, new byte[][][]{new byte[][]{new byte[]{1, 1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1, 1}}, new byte[][]{new byte[]{0}}, new byte[][]{new byte[]{1}, new byte[]{1, 1}}}, new byte[][][]{new byte[][]{new byte[]{0}, new byte[]{0}, new byte[]{1}}, new byte[][]{new byte[]{1}, new byte[]{1, 1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}}, new byte[][]{new byte[]{1}}}, new byte[][][]{new byte[][]{new byte[]{1, 1}}}};
            var vr6 = vr3[0];
            System.Console.WriteLine(vr6);
        }
    }
}
```

cc @AndyAyersMS

**Comment by jakobbotsch** [comment]
I'm a bit confused about this, it seems to be a recent regression or I have messed up something in my environment. Can someone verify that this is failing for them as well?

**Comment by AndyAyersMS** [comment]
I'll take a look.

**Comment by AndyAyersMS** [comment]
Yes, can confirm. With latest main, I get `1` for minopts and `0` for optimized.

**Comment by AndyAyersMS** [comment]
However, hoisting's not the culprit here, we only host out some class handles. 

Another oddity: enabling jit dumps for main changes the output:
```
complus_noguionassert=0
complus_tieredcompilation=0
corerun.exe ex.exe
0
0

complus_jitdump=Main
complus_jitstdoutfile=D:\bugs\r58877\main.d1
complus_noguionassert=0
complus_tieredcompilation=0
corerun.exe ex.exe
1
1
```

**Comment by AndyAyersMS** [comment]
Bug repros if we just enable disassembly, and there the load of `vr6` does seem to be hoisted.

**Comment by AndyAyersMS** [comment]
Looks like one issue is that if we run out of budget in VN chasing back through memory updates, we fail to record the loop dependence. Here `[00835]` is the indir tree that ultimately gets hoisted.

```
    VNForMapSelect($807, $101):ref returns $7c7 {MemOpaque:Indeterminate}
    VNForMapSelect($7c7, $200):ref returns $79a {$7c7[$200]}
    VNForMapSelect($79a, $142):short returns $3c1 {$79a[$142]}
  hAtArrType $7c7 is MapSelect(curGcHeap($807), short[]).
  hAtArrTypeAtArr $79a is MapSelect(hAtArrType($7c7), arr=$200).
  wholeElem $3c1 is MapSelect(hAtArrTypeAtArr($79a), ind=$142).
    VNForCastOper(ushort) is $47
    VNForCast($3c1, $47) returns $281 {Cast($3c1, $47)}
  selectedElem is $281 after applying selectors.
N006 [000835]   IND       => <l:$281 {Cast($3c1, $47)}, c:$841 {MemOpaque:L00}>
```
I am not sure yet why (seemingly) hoisting behavior depends on whether dumps are enabled during hoisting.  I selectively turned on dumping during VN and the IR looks identical (and the test still fails).

**Comment by AndyAyersMS** [comment]
I recall getting stuck here when working on tracking loop memory dependence because when we hit the budget limit we don't create an opaque VN that can be attributed to a block, for reasons.

https://github.com/dotnet/runtime/blob/4d4aa2c97e8cce78af64101b569959168a4164ea/src/coreclr/jit/valuenum.cpp#L2284-L2294

This is unfortunate because we then can't easily determine the loop memory dependence of this opaque VN, and seemingly we then think this VN is not loop dependent.

One possible fix is to rely on `LoopOfVN` returning `MAX_LOOP_NUM` for such VNs and then use this to record a special entry in the loop dependence map that indicates the VN is effectively defined in all loops. We could possibly use `fgFirstBB` as the special entry here since it can't be inside any loop, or some other random sentinel address. Then if we see this special entry we simply report the VN as loop dependent, whatever the loop.

Also seems like we ought to have a VN stress mode where we set the budget very low, to make sure we get better coverage of cases where we run out of budget.

**Comment by AndyAyersMS** [comment]
> I am not sure yet why (seemingly) hoisting behavior depends on whether dumps are enabled

Starting to suspect there's some uninitialized state somewhere. I modified the jit to only set verbose for selective phases and there doesn't seem to be any correlation between which phases are run with verbose and whether or not the test passes.

**Comment by AndyAyersMS** [comment]
Ok, found the issue for the odd behavior re dumping. When we hit the budget limit and return the special non-block opaque VN, we end up invoking `optLoopContains` with `MAX_LOOP_NUM` and this causes us to index off the end of the loop table.

One possible fix is to consider a `MAX_LOOP_NUM` loop as containing or being contained in any other loop, since it represents some potentially unknown loop dependence.

**Comment by AndyAyersMS** [comment]
Doing so also fixes the bug, since these special opaque VNs are now always loop variant. Though we prefer to assert that we never call `optLoopContains` with this odd value, and instead intercept things in `optVNIsLoopInvariant`.
