### ISSUE TITLE
System.IO.Pipelines.Pipe.ReadAsync fails to cancel on CancellationToken

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#58909]
### Description

I have a hang dump of a process that is stuck in a `PipeReader.ReadAsync` call that was canceled via `CancellationToken` but which never canceled the returned `ValueTask<ReadResult>`. This resulted in the hang.

I do not have a reliable repro of it but I have a rash of pipelines and repos that all suffer from frequent hangs in test runs and ultimately they all lead into this same function so I believe they are all caused by this one problem.

[Dump file](https://1drv.ms/u/s!Aj3kll8mDD0Ggajbd3pZLSLYx8gj68o?e=mglxD2). [Failed pipeline](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=5160&view=results).

Looking at the dump file in WinDbg I took these notes, which form a kind of continuation chain mixed with some state in each of the objects. Below you can see that the CancellationToken that was passed to `PipeReader.ReadAsync` is in fact cancelled, but that the `Pipe._readerAwaitable` field has no `CancellationTokenRegistration` for it. You can also see that `ReadAsync` has not completed, so we're blocked waiting for `ReadAsync` to honor the `CancellationToken` yet it never will because it wasn't even registered to notice.

```
0000020b0e0e2048 Pipe
  0000020b0e0e20e8 _readerAwaitable
    10 _awaitableState
    0000020b0e0e2110 _cancellationTokenRegistration
      0 _id
      0 _node
0000020b0e0e2278 DefaultPipeReader.ReadAsync
  0000020b0e0e2048 _pipe
0000020b0dff7d38 System.IO.Pipelines.PipeReaderStream+<ReadAsyncInternal
  0000020b0dfdeeb8 cancellationToken.m_source (_state: 3, cancelled)
  0000020b0e0e2278 _pipeReader
0000020b0dff7df8 MessagePackStreamReader.TryReadMoreDataAsync
  0000020b0dfdeeb8 cancellationToken.m_source (_state: 3, cancelled)
  0000020b0dfde1a8 underlying System.IO.Pipelines.PipeReaderStream 
0000020b0dfde5b8 V2Formatter
```

### Configuration

Windows 10
The hangs show up on .NET Framework and .NET Core 3.1 at least.
x64 process
System.IO.Pipelines v5.00.120.57516 (nuget package version v5.0.1)

### Regression?

Unknown. 

### Other information

This bug was originally filed against Nerdbank.Streams as https://github.com/AArnott/Nerdbank.Streams/issues/387 before I tracked it into System.IO.Pipelines.

**Comment by davidfowl** [comment]
Anything that updates the PipeAwaitable should be in a lock. The only thing that could change state here is the cancellationToken itself (since the caller owns that). The registration is released here https://github.com/dotnet/runtime/blob/033b2ac49a3f473a790da21dd67cbea02ad93c8b/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L854.

It seems you're also using the sync context. I dunno if that's related but does it repro if you disable it?

**Comment by zlatanov** [comment]
This looked interesting, so I did a little digging and here is what I found:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L46-L60

If the cancellation token gets cancelled just before executing line `58` here:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L58

then the callback will be invoked synchronously. The callback is actually: 
https://github.com/dotnet/runtime/blob/033b2ac49a3f473a790da21dd67cbea02ad93c8b/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L1043-L1051

which calls `PipeAwaitable`
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L139-L150

However if we read carefully in `CancellationTokenFired` we find that `Cancel(out completionData)` is only called if `CancellationToken.IsCancellationRequested`. If we go to the definition of `CancellationToken` in `PipeAwaitable` it is defined as:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L21-L23

It uses the `_cancellationTokenRegistration` field to extract the cancellation token. However if we go back to the beginning, we will see that the `_cancellationTokenRegistration` is not yet set:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L58

The summary is that `UnsafeRegister` method invokes the callback synchronously, but the callback uses the result from `UnsafeRegister`. Writing a test for this particular case would be extremely difficult in my opinion.

//cc @davidfowl

**Comment by davidfowl** [comment]
@zlatanov amazing analysis!

**Comment by zlatanov** [comment]
@davidfowl In order to keep the use of the registration an easy solution would be to modify the callback:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L1114-L1122

to have something like this at the beginning:
```c#
if ( Monitor.IsEntered(SyncObj))
{
    // We have synchronous callback from UnsafeRegister, but because we use the result from it
    // we can't process it synchronously.
   ThreadPool.UnsafeQueueUserWorkItem(s_signalReaderAwaitable, this);
   return;
}
//... the rest of the method as is
```

**Comment by davidfowl** [comment]
I'm wondering if there's any downside is removing the IsCancellationRequested check in `CancellationTokenFired`

**Comment by zlatanov** [comment]
Somebody left a pretty telling comment there: `We might be getting stale callbacks that we already unsubscribed from`. I don't know how true it is though.

**Comment by davidfowl** [comment]
Yea, I was looking at that PR as well. @pakrym added that comment. 

Actually, maybe we can add a check [here](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L60) to see if the token did fire and mark the awaitable as cancelled synchronously.

**Comment by zlatanov** [comment]
I think it's dangerous to add it there, because it only hides the issue. In the future if `CancellationTokenFired` method were to be refactored or something else added that counted on `IsCancellationRequested` being up to date, it would blow up silently later on.

The issue here is that the callback is fired synchronously and in that code's execution path, some method is using the `CancellationToken` which is not yet set. At any point in the future if any code is added, this might cause more hard to spot problems.

The best solution would be to be able to set a dummy `CancellationTokenRegistration` that has the up to date cancellation token, even if not really subscribed, before calling UnsafeRegister, but I guess that isn't possible at the moment.

**Comment by davidfowl** [comment]
I'm not concerned about code refactoring. We'll add some heavy comments to explain why it's important. I'd like to keep the fix as localized to PipeAwaitable as possible so the option seems like we should add some extra state management in there

**Comment by zlatanov** [comment]
> But I like checking if the token fired after this call since it would be doing the moral equivalent if it ran inline.

True, but what I don't like about this, is the fact that the callback has already run and could potentially have already changed the state of the awaitable.

**Comment by davidfowl** [comment]
I'm now not sure how this happens on .NET Framework since the cancellation token is assigned before registering for the callback...

**Comment by zlatanov** [comment]
> I'm now not sure how this happens on .NET Framework since the cancellation token is assigned before registering for the callback...

How sure are we that the pipeline uses the correct dll? I can't open the build pipeline at the moment to try and download the artifacts for .NET Framework and use reflection to make sure the we're not chasing ghosts.

**Comment by davidfowl** [comment]
> How sure are we that the pipeline uses the correct dll? I can't open the build pipeline at the moment to try and download the artifacts for .NET Framework and use reflection to make sure the we're not chasing ghosts.

@AArnott ?

**Comment by AArnott** [comment]
I can confirm from the dump that the System.IO.Pipelines.dll loaded in the process is  5.0.1+b02e13abab3d6f499751af2ad1ae6333fb4e633d.

> I'm now not sure how this happens on .NET Framework since the cancellation token is assigned before registering for the callback

The dump file isn't of the .NET Framework. It's a .NET Core process (coreclr.dll 4,700,21,35901 @Commit: 2aee3eb10b6303dff09cbe5ac99b6fae4644f346).

If the bug you found that can be blamed for the cause of the hang in *this* dump can't explain a failure on .NET Framework then I will find a .NET Framework dump as well that we can investigate.

**Comment by AArnott** [comment]
This still repros after the fix is applied (albeit less frequently).
As evidenced by the `testResults-Windows` artifact downloaded from [this pipeline](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5214140&view=artifacts&pathAsName=false&type=publishedArtifacts).

Here are my notes from windbg and VS investigation of the hang dump:

```
0000021b3bcc1a20 ContextRuleMonitorServiceTests+<RegisterContextRuleAsyncSerializesRuleMetadata>d__3
    0 <>1__state
    0000021b3bc0f358 <>4__this (ContextRuleMonitorServiceTests)
        0000021b3bc0f3d0 <TimeoutTokenSource>k__BackingField
              3 _state (CANCELED)
    0000021b3bc0f4b0 <Service>k__BackingField
        0000021b3bae3040 <LastRuleMetadata>k__BackingField
    0000021b3bcb6538 <ClientProxy>k__BackingField
        0000021b3bc80d48 rpc
            0000021b3bc80810 <MessageHandler>k__BackingField
                  0000021b3bc80120 <Formatter>k__BackingField
                       0000021b3bc6cf10 multiplexingStream
                           0000021b3bc0fe50 formatter (V1Formatter)
                               0000021b3bc0f918 stream
                                    0000021b3bc0f8b8 readableStream


0000021b3bae2ac8 00007ffec92a3148      168          0 Nerdbank.Streams.MultiplexingStream+<ReadToFillAsync>d__55
0000021b3bae2b70 00007ffec92a38f8      240          0 Nerdbank.Streams.MultiplexingStream+V1Formatter+<ReadFrameAsync>d__12
    0000021b3b3ceb80 <>4__this (V1Formatter)
    0000021b3bae2c10 cancellationToken
        0000021b3bc687d0 _source
            1 _state (CANCELED)


0000021b3bcad1e8 00007ffec92a3148      168          0 Nerdbank.Streams.MultiplexingStream+<ReadToFillAsync>d__55
0000021b3bcad290 00007ffec92a38f8      240          0 Nerdbank.Streams.MultiplexingStream+V1Formatter+<ReadFrameAsync>d__12
    0000021b3bc6cf10 <>4__this (V1Formatter)
    0000021b3bcad330 cancellationToken
        0000021b3bc6d188 _source
            1 _state (CANCELED)
```

The source code for that V1Formatter.ReadFrameAsync at the 0th await is ultimately a call to PipeReaderStream.ReadAsyncInternal as can be seen in the VS visualization of the async state machines:
![image](https://user-images.githubusercontent.com/3548/133682315-bf24e434-bc87-4e90-804e-2a8a4d9ee4bb.png)

And as you can see from the windbg notes, both of those ReadFrameAsync calls have already been canceled.

**Comment by zlatanov** [comment]
@AArnott I can't download the artifact from either source. It seems both are internal to Microsoft organization only. Can you share it some other way so I can access it?

**Comment by AArnott** [comment]
I'm afraid not in this case. The original dump with which I created this issue came from an open source repo, but this new one comes from a private one. If I can repro on the OSS one, I'll share that publicly.

**Comment by zlatanov** [comment]
I double checked the fix by @davidfowl and it seems solid. However then I decided to look into `CancellationTokenSource` and its Register method. The fix by David assumes that if the token is cancelled while we are calling the `Register` method, that a default `CancellationTokenRegistration` will be returned:
https://github.com/dotnet/runtime/blob/467f5c646be6895ee980321690296e61800c387b/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L59-L69

However after reading the source code in CancellationTokenSource, this seems to not always be the case:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L585-L594

**Comment by stephentoub** [comment]
Doesn't it just assume that if default is returned the callback has been? That holds.

**Comment by zlatanov** [comment]
> Doesn't it just assume that if default is returned the callback has been invoked? That holds.

You're right. Can we consider another case then. When signaling the `CancellationTokenSource` this method is called
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L602-L605

which sets the state to `notifying` and then
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L630-L638

which resets the `_reservations` field to null. Lets assume that one thread is doing this, while another thread is halted at `Register` method and more specifically, just before line:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L512

Then the registering thread will try to create new registrations object. Everything is fine until these lines in the `Register` method:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L591-L594

and more specifically `IsCancellationRequested` property. It is defined as:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L69

Is it possible that the `_state` field, even if it's declared as volatile, to have a value (as observed from the other thread, and possible other CPU node) that is not completely in sync with the `Interlocked.CompareExchange(ref _state, NotifyingState, NotCanceledState)` operation?

I specifically ask because of this note in the documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile):
```txt
On a multiprocessor system, a volatile read operation does not guarantee 
to obtain the latest value written to that memory location by any processor. 
```

**Comment by stephentoub** [comment]
> Is it possible that the _state field, even if it's declared as volatile, to have a value (as observed from the other thread, and possible other CPU node) that is not completely in sync with the Interlocked.CompareExchange(ref _state, NotifyingState, NotCanceledState) operation?

In your sequence of events, we're only at this point because the thread read a null _registrations. That read is a full fence and can't be reordered with the subsequent read you cite of _state. _state was written by the other thread with a full fence _prior_ to nulling out _registrations, also with a full fence.  The reordering describe isn't possible then.

**Comment by AArnott** [comment]
Ok, I found a cancellation bug in Nerdbank.Streams this time around (AArnott/Nerdbank.Streams#414). So till evidence suggests otherwise, I will consider _this_ bug fixed with the original PR.
@davidfowl, I will do some more testing of the Pipelines fix combined with the Nerdbank.Streams fix. If I don't see any hangs in test runs, I'll request that we resume the backport of the fix made for this bug.
