### ISSUE TITLE
Assertion failed '!replacedInLowering' 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#58972]
Repro:

Compile with `/o+`, run with `DOTNET_TieredCompilation=0` on Windows checked x64:

```csharp
using System;

GetItem<MyStruct>(new MyStruct[1], 0);

static T GetItem<T>(T[] a, int i)
{
    try
    {
        return a[i];
    }
    catch (IndexOutOfRangeException)
    {
        ThrowHelper();
        return default;
    }
}

static void ThrowHelper() => throw new Exception();

struct MyStruct
{
    byte b;
}
```

**Comment by jkotas** [comment]
This is a regression introduced in last 6 days. Found by https://github.com/dotnet/runtimelab/pull/1549

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib @kunalspathak PTAL.

**Comment by jakobbotsch** [comment]
I added the assert in #58589. I'm not sure if the assert should just be removed or if there is a real problem. I don't see why we would replace an unenregistered struct with its field.

That PR was backported already so we should also look at backporting the fix.

**Comment by jakobbotsch** [comment]
I can take a look.

**Comment by jakobbotsch** [comment]
Ah, the enregister check is ends up happening on the field, not the parent. It is perfectly possible for the promoted struct's field to be do-not-enregister. In this case the code in CIL looks like
```csharp
static MyStruct GetItem(MyStruct[] a, int i)
{
    T v06;
    try
    {
        v06 = a[i];
    }
    catch (IndexOutOfRangeException)
    {
        ThrowHelper();
        v06 = default;
    }
    return v06;
}
```

We promote `v06` but its promoted field is marked as do-not-enregister because it is live in/out of the handler.
I suspect the assertion is benign because #58589 also fixed the do-not-enregister case to correctly retype the `LCL_FLD` when normalization is required.
