### ISSUE TITLE
[Proposal] Create benchmarks for performance quality assurance

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#58995]
I think it would make sense to benchmark methods (except Intrinsics) using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) and to create a benchmark project for each of the test projects.

**Comment by filipnavara** [comment]
There's already a set of benchmarks at https://github.com/dotnet/performance. They use BDN and they are run regularly to track performance regressions.

**Comment by deeprobin** [comment]
> There's already a set of benchmarks at https://github.com/dotnet/performance. They use BDN and they are run regularly to track performance regressions.

@filipnavara

Ah, wouldn't it make sense to move them to the same repository as tests though?

**Comment by filipnavara** [comment]
It was intentionally moved out, or rather it replaced all the legacy non-BDN benchmarks in this repository which got deleted.

I suppose they are logistic reasons for that. For example, the benchmarks are not tied to specific runtime version and in fact they compare different runtime versions for regressions.

**Comment by danmoseley** [comment]
Yes, it is a separate repo primarily because it has no need to be tied to a particular version. Since there's conditions around use of new API's, the repo can easily compare different .NET versions fairly, even though the tests evolve and new tests are added.

We use the repo extensively throughout the cycle. All the improvements listed here should be protected by tests in that repo:

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/

You are welcome to contribute if you see significant gaps in coverage.
