### ISSUE TITLE
[API Proposal]: Parallel.ForAsync

### ISSUE THREAD

**Issue by 0x90d** [dotnet/runtime#59019]
### Background and motivation

#1946 recently `Parallel.ForEachAsync` has been approved and added to .NET6. However there still no async of `Parallel.For`. Developers still have to use the same workarounds as for `Parallel.ForEach` on .NET5 and below to make it run asychronously. An async version of `Parallel.For` has been mentioned two times in the linked issue, but was left out of discussion so I couldn't find a reason why it hasn't been made async yet. I simply assume that it wasn't taken into consideration because it was not explicit proposed.

As for the motivation I think the same arguments for `Parallel.ForEachAsync` also applies to `Parallel.ForAsync`

### API Proposal

```C#
namespace System.Threading.Tasks
{
    public static class Parallel
    {
        public static Task ForAsync(int fromInclusive, int toExclusive, Func<int, CancellationToken, ValueTask> body);
        public static Task ForAsync(int fromInclusive, int toExclusive, CancellationToken cancellationToken, Func<int, CancellationToken, ValueTask> body);
        public static Task ForAsync(int fromInclusive, int toExclusive, ParallelOptions parallelOptions, Func<int, CancellationToken, ValueTask> body);
        public static Task ForAsync(long fromInclusive, long toExclusive, Func<long, CancellationToken, ValueTask> body);
        public static Task ForAsync(long fromInclusive, long toExclusive, CancellationToken cancellationToken, Func<long, CancellationToken, ValueTask> body);
        public static Task ForAsync(long fromInclusive, long toExclusive, ParallelOptions parallelOptions, Func<long, CancellationToken, ValueTask> body);
    }
}
```     

### API Usage

```C#
List<DuplicateItem> duplicates = new();
//duplicates.Add(...);
//...

await Parallel.ForAsync(0, duplicates.Count, new ParallelOptions { CancellationToken = cancellationTokenSource.Token}, async (i, token) => {
	await duplicates.GenerateThumbnail();
	
	for (int j = i + 1; j < duplicates.Count; j++) {
		//...
	}
});
```

**Comment by WeihanLi** [comment]
Any plan for this?

**Comment by stephentoub** [comment]
> Any plan for this?

Not currently.  In the meantime, you can of course just use ForEachAsync with a range:
```C#
Parallel.ForEachAsync(Enumerable.Range(0, count), async (i, cancellationToken) =>
{
    ...
});
```

**Comment by stephentoub** [comment]
> As for the motivation I think the same arguments for Parallel.ForEachAsync also applies to Parallel.ForAsync

Sort of.  With Parallel.ForEachAsync, the primary motivation was being able to consume `IAsyncEnumerable<T>`, and once we're doing that, overloads that also support async bodies also make sense (and then once you have async bodies, you also want to consider `IEnumerable<T>`... it's a slippery slope).  With Parallel.For, `IAsyncEnumerable<T>` isn't a factor; the source is always synchronous since it's just a constant range.  There's still the possibility of an async body, but that's the minor aspect of the APIs.  There are also multiple ways to achieve the same basic functionality, e.g. the aforementioned layering on ForEachAsync, using Partitioner.Create to split up the range into individual iterators and spawning a task to process each partition, etc.

If we decide it's worthwhile to add Parallel.ForAsync, the proposed API set looks good to me.  I've marked it as ready for review to have a broader discussion about whether we want ForAsync at all.

**Comment by stephentoub** [comment]
Temporarily moving back to api-ready-for-review to discuss collapsing the int/long overloads to be just based on `T : IBinaryInteger<T>`

**Comment by bartonjs** [comment]
We brought this back to discuss collapsing the int/long variants into a single generic representation, with a result of we do feel like one generic version is the better approach.

The discussion says that IBinaryInteger is the correct restriction, so we're going with that.

```C#
namespace System.Threading.Tasks
{
    public static partial class Parallel
    {
        public static Task ForAsync<T>(T fromInclusive, T toExclusive, Func<T, CancellationToken, ValueTask> body) where T : notnull, IBinaryInteger<T>;
        public static Task ForAsync<T>(T fromInclusive, T toExclusive, CancellationToken cancellationToken, Func<T, CancellationToken, ValueTask> body) where T : notnull, IBinaryInteger<T>;
        public static Task ForAsync<T>(T fromInclusive, T toExclusive, ParallelOptions parallelOptions, Func<T, CancellationToken, ValueTask> body) where T : notnull, IBinaryInteger<T>;
    }
}
```
