### ISSUE TITLE
[BUG] TimeBeginPeriod / TimeEndPeriod strange behavior while loading dynamically from an assembly

### ISSUE THREAD

**Issue by SuRGeoNix** [dotnet/runtime#59058]
Tested on Windows Version 10.0.19043.1165 with .NET 5 (not sure if that is .NET 5's issue)

It seems that there is a bug with Time Periods stack while using Activator.CreateInstance to load dynamically an assembly.

If you try to close VS, Browser etc. to ensure the global time period is not small (eg. 1ms) you will see different results while running the console app executable.

The important issue is that the Class Library 12 (which sets the time period to eg. 5ms) affects the Class Library's 11 time period 1ms.

I've created a [solution sample](https://drive.google.com/file/d/1UDNt-KbwW24aPymF4TIQZia_Apb2V5Ea/view?usp=sharing) with two class libraries and one console app. Related discussion on [StackOverflow](https://stackoverflow.com/questions/69127786/timebeginperiod-timeendperiod-sequence)

**Comment by vitek-karas** [comment]
I'm pretty sure this has nothing to with dynamically loading an assembly or `CreateInstance`. If I rewrite your sample to not use dynamic loading and just use `new Class12` it has the same behavior as with dynamic loading. (Also I would not expect any change in behavior between the two).

I think what you're seeing is a Windows behavior - I know next to nothing about media timers, so I can't comment if the behavior is expected or not. And unfortunately the docs don't seem to describe this (they simply say either `timeBeginPeriod` should be matched with a `timeEndPeriod`, but they don't describe what happens if you have overlapping settings).

**Comment by SuRGeoNix** [comment]
Hi @vitek-karas,  did you run the sample within the VS? Use Command Prompt instead to see the difference with CreateInstance as the VS will change your app's timers when you debug to 1ms. Make sure that you use Windows 10 2004 (aka, the April 2020 version of Windows) or greater where the TimeBegin/EndPeriod behavior has been changed to per app so "it will not" be affected by others.

Output (with class12 embedded) | The right one

```
TimeBeginPeriod(5)
00:00:00.0019360
00:00:00.0048730
00:00:00.0045212
00:00:00.0077463
00:00:00.0044132
TimeBeginPeriod(1)
00:00:00.0016170
00:00:00.0019618
00:00:00.0019592
00:00:00.0019633
00:00:00.0019682
TimeEndPeriod(5)
00:00:00.0018461
00:00:00.0019554
00:00:00.0019531
00:00:00.0019523
00:00:00.0019642
TimeEndPeriod(1)
```

Output with class12 dynamic assembly

```
TimeBeginPeriod(5)
00:00:00.0048622
00:00:00.0048731
00:00:00.0049184
00:00:00.0049300
00:00:00.0044874
TimeBeginPeriod(1)
00:00:00.0044160
00:00:00.0049280
00:00:00.0042060
00:00:00.0049282
00:00:00.0049521
TimeEndPeriod(5)
00:00:00.0230172
00:00:00.0150670
00:00:00.0151850
00:00:00.0151827
00:00:00.0150665
TimeEndPeriod(1)
```

**Comment by vitek-karas** [comment]
I'm running this on Windows 10 21H1. I tried all of "Running from VS", `dotnet run` and `consoleapp1.exe`. All shows the same results:

Static:
```
TimeBeginPeriod(5)
00:00:00.0018856
00:00:00.0012261
00:00:00.0018677
00:00:00.0017868
00:00:00.0018897
TimeBeginPeriod(1)
00:00:00.0014118
00:00:00.0015868
00:00:00.0017795
00:00:00.0013012
00:00:00.0013379
TimeEndPeriod(5)
00:00:00.0149158
00:00:00.0152190
00:00:00.0159112
00:00:00.0155281
00:00:00.0155012
TimeEndPeriod(1)
```

Dynamic:
```
TimeBeginPeriod(5)
00:00:00.0018311
00:00:00.0016173
00:00:00.0017333
00:00:00.0019481
00:00:00.0017546
TimeBeginPeriod(1)
00:00:00.0010419
00:00:00.0017823
00:00:00.0018420
00:00:00.0018717
00:00:00.0018779
TimeEndPeriod(5)
00:00:00.0044870
00:00:00.0158513
00:00:00.0157627
00:00:00.0159228
00:00:00.0148873
TimeEndPeriod(1)
```

The first time printed out after the `TimeEndPeriod(5)` is shorter, but that also sometimes happen in the static case. It's basically random in both static and dynamic.

I honestly don't see any observable difference between the two. (I did modify the sample a little, but only so that I can easily switch between static and dynamic using MSBuild property, otherwise it works exactly the same as your sample).

**Comment by SuRGeoNix** [comment]
It seems that for some reason when you start the console app you already have TimeBeginPeriod(1). I would close all the windows (browsers, vs, etc.) just to make sure nobody sets it.

But even in your results you see that after the TimeEndPeriod(5) the wait ms go to 15ms which is wrong as you still have the TimeBeginPeriod(1).

**Comment by vitek-karas** [comment]
> But even in your results you see that after the TimeEndPeriod(5) the wait ms goes to 15ms which is wrong as you still have the TimeBeginPeriod(1).

I honestly don't know the expected behavior for this case. As far as I can read the docs, it's not written what the expected behavior is there. It doesn't state anywhere (that I could find) that the calls can be nested and it would internally keep a stack of the expected values. It's very possible that the behavior is simply to keep one per-process value and each call to `TimeBeingPeriod`/`TimeEndPeriod` just updates that value - no stack. But to reiterate - I simply don't know what the behavior should be (I understand it's not what you want).


I closed everything on the machine:

Static:
```
TimeBeginPeriod(5)
00:00:00.0040256
00:00:00.0040820
00:00:00.0052384
00:00:00.0052615
00:00:00.0043729
TimeBeginPeriod(1)
00:00:00.0012686
00:00:00.0021385
00:00:00.0017437
00:00:00.0013638
00:00:00.0015307
TimeEndPeriod(5)
00:00:00.0013491
00:00:00.0014681
00:00:00.0017381
00:00:00.0018556
00:00:00.0013905
TimeEndPeriod(1)
```

Dynamic:
```
TimeBeginPeriod(5)
00:00:00.0013522
00:00:00.0050781
00:00:00.0050332
00:00:00.0048717
00:00:00.0051943
TimeBeginPeriod(1)
00:00:00.0016145
00:00:00.0017133
00:00:00.0017067
00:00:00.0016759
00:00:00.0013893
TimeEndPeriod(5)
00:00:00.0012433
00:00:00.0019741
00:00:00.0016728
00:00:00.0014175
00:00:00.0018752
TimeEndPeriod(1)
```

The behavior is different but it's still consistent between static and dynamic.

**Comment by SuRGeoNix** [comment]
Just re-tested. You are right it gives different result for both static/dynamic. So, the issue is not about dynamic loading but general. So probably, it is related with Windows and not dotnet. It should be an issue generally. Imagine that within your Time Begin/End you can call any underlying library. If that library changes the time period as well, when it returns to your code it changes yours as well.

I've some new windows updates will try them and if the issue persists I will try to open in to the Windows side.
