### ISSUE TITLE
Blazor Wasm can't read Azure Storage Tables directly, it needs azure functions or controllers.

### ISSUE THREAD

**Issue by pabloarthurrodger** [dotnet/runtime#59098]
Everything that can be done in an Azure Function or in a Controller can be done in Blazor Wasm.  You do not need Azure functions to be Serverless.

If Blazor Wasm could read Azure Table Storage it will only need the Blazor SPA and the Storage Tables.  All cpu consumption will be on the Client.  Zero Controllers, Zero Azure Functions.  And I do not know if this is only on Azure Storage Tables or in SQL, MySQL, CosmosDB, and all Databases

I try to read it, but I get System.Security.Cryptography APIs not supported on Blazor WebAssembly, And I read that is going to take too many changes I get that, but this could have the potential to be TRULY SERVERLESS.
 
I just want to know if this issue is going to be address in the future or Blazor could never read data directly?

Thanks in Advance,

Pablo Arthur Rodger

**Comment by mkArtakMSFT** [comment]
@lewing I couldn't find the issue you use to track the cryptoAPIs support. I think that will unblock this customer too.

**Comment by bartonjs** [comment]
The saga of why this isn't supported is described well in https://github.com/dotnet/runtime/issues/87214.

https://github.com/dotnet/runtime/issues/80904 says that there might be a path forward; but I haven't looked into it enough to know if we're talking .NET 9 or beyond at this point.

Since this issue, in particular, is just a restatement of ".NET-wasm doesn't support cryptography", I'm going to close it as basically older-dupe of #87214.
