### ISSUE TITLE
Figure out an alternative to startup hooks for dev-time scenarios such as hot reload

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#59107]
### Description

In .NET 6, hot reload relies on startup hooks to inject binaries in to the app that can do things like receive hot reload deltas when not attached to the debugger, and invoke metadata update handlers when it is. However, the runtime disables startup hooks for an `PublishTrimmed=true`. To workaround this, VS / dotnet-watch will disable hot reload for apps with startup hooks disabled.

In addition to this, there's also the issue that startup hooks are a public facing feature and there's a chance that the hooks injected by tooling could interfere with the ones added by the user.

For .NET 7, we'd like to explore an alternative channel to support these dev time scenarios.

**Comment by jkotas** [comment]
How do you expect hot reload and apply delta to work in `PublishTrimmer=true` apps?

To apply deltas to trimmed apps, you would have to ensure that the deltas do not reference any APIs that got trimmed, and that the deltas do not violate any other invariants inferred by the linker from the app code. That is close to impossible to do in reasonable way.

>  startup hooks are a public facing feature and there's a chance that the hooks injected by tooling could interfere with the ones added by the user.

The same would be true for other channels.

**Comment by pranavkm** [comment]
@jkotas this is on an app that hasn't been trimmed (i.e. when you `dotnet run` the app). We definitely don't want to support hot reloading on app that has been trimmed.

**Comment by jkotas** [comment]
Ah ok. I guess that the simplest fix would be to trust startup hooks that they are not doing anything that affects behavior after trimming, and leave them enabled in untrimmed app even when the project file has `PublishTrimmer=true`.

**Comment by jkotas** [comment]
@pranavkm Are you doing anything unnatural to workaround the current behavior? Trying to see whether we should consider this for .NET 6.

**Comment by vitek-karas** [comment]
I'll try to summarize what was discussed (@pranavkm please correct me):
* We don't want to limit hot-reload to only work on app builds which are "made for hot-reload". This effectively means the SDK doesn't know if the app will need hot-reload capability when it's building it. So it would have to always assume "yes" - which would mean to enable startup hooks on non-trimmed builds of app even if `PublishTrimmed=true`.
* If we enable startup hooks on untrimmed builds of apps which have `PublishTrimmed=true` we violate the predictability - the app will behave differently in that build (startup hooks work) and in the trimmed build (startup hooks don't work).
* Suggestion was for hot-reload when it's starting the app to overwrite `.runtimeconfig.json` to enable startup hooks, but that was deemed problematic (incremental builds might be confused, file locking might be an issue, there's a potential for race conditions, ...)
  * There's an alternative where the runtime exposes the startup hook feature switch also as an env. variable (configuration knob) - which would avoid all of the above mentioned issues. But this would require new functionality in runtime/framework.
* On a general level (ignoring trimming), if hot-reload uses startup hooks, it is competing for that feature with potential application usage, which might cause issues. A potential solution to this problem is to introduce a new channel through which hot-reload would deploy its code into the app.
* My understanding is that the decision is to try to tackle this in 6 and simply disable hot-reload on apps which have `PublishTrimmed=true` (or actually any way through which startup hooks are disabled) - and solve this in 7.

**Comment by jkotas** [comment]
> PublishTrimmed=true we violate the predictability - the app will behave differently in that build (startup hooks work) and in the trimmed build (startup hooks don't work).

To keep things simple, I would be ok with giving up predictability for features controlled by the environment (as opposed to the program source code).

Profilers are environment controlled feature too. Profilers can do IL rewriting that can get confused by trimming. We are not disabling profilers for predictability either.

**Comment by agocke** [comment]
I don't think we're planning on changing anything here on the AppModel side for trimming. @pranavkm Is there a plan to do anything to address this elsewhere?

**Comment by agocke** [comment]
Closing this on the AppModel side, as there's no specific path forward. Feel free to re-open if there's a specific proposal for us to implement.
