### ISSUE TITLE
EncryptedXml.Encrypt(XmlElement, X509Certificate) does not support rsa oaep, only insecure rsa1.5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59127]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EncryptedXmlEncryptXmlElement-X509Cer/1437226)._

---
[severity:I'm unable to use this version]
EncryptedXml.Encrypt(XmlElement, X509Certificate) does not support rsa oaep, only rsa 1.5 which is deemed insecure.

from: https://www.w3.org/TR/xmlsec-algorithms/#rsa15

RSA-v1.5
URI:
http://www.w3.org/2001/04/xmlenc#rsa-1_5
Specified in:
section 5.4.1 of [XMLENC-CORE]
This algorithm is optional to implement in [XMLENC-CORE]. **Implementation of RSA v1.5 is not recommended due to security risks associated with the algorithm.**

6.2 RSA OAEP
RSA-OAEP (including MGF1 with SHA1 mask generation function)
URI:
http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
Specified in:
section 5.4.2 of [XMLENC-CORE]. This version has a fixed mask generation function of MGF1 with SHA1.
**This algorithm is mandatory to implement in [XMLENC-CORE].**

---
#### Feedback Bot on 5/31/2021, 07:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/5/2021, 08:15 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by bartonjs** [comment]
RSA-OAEP-SHA1 has been supported since the introduction of EncryptedXml in .NET Framework 2.0.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.Xml/tests/Samples/EncryptingDecryptingAsymmetric.cs#L34-L39

shows tests utilizing it.

**Comment by bartonjs** [comment]
Upon reflection, I see that the issue was about the certificate-based ease-of-use method, not the total class functionality.

This can be worked around in caller code, perhaps with an extension method for symmetry.  Just copy https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs#L526-L561 and change the OAEP `false`s to `true`s.

We basically haven't changed EncryptedXml since 2005 (.NET Framework 2.0).  I'd be somewhat amenable to accepting a PR to add an overload that parameterized OAEP for (XmlElement, X509Certificate2, bool), but it would probably only be available to callers on .NET (nee Core), not .NET Framework.

It doesn't look to me like we've actually added any new API for EncryptedXml or SignedXml since the creation of .NET Core.

In general, we strongly recommend EnvelopedCms over EncryptedXml.
