### ISSUE TITLE
.NET 5.0 - ShortDatePattern for the culture nl-NL has changed

### ISSUE THREAD

**Issue by draphyz** [dotnet/runtime#59251]
### Description

* The ShortDatePattern for the culture nl-NL has changed
* Minimal steps to reproduce the problem : 
        static void Main(string[] args)
        {
            var culture = CultureInfo.CreateSpecificCulture("nl-NL");
            var shortDatePattern = culture.DateTimeFormat.ShortDatePattern;
            // Displays d-M-yyyy with net48, netcoreapp2.1, netcoreapp3.1
            // Displays dd-MM-yyyy with net5.0
            Console.WriteLine(shortDatePattern);
        }

### Configuration

* Version of .NET : 5.0.10
* OS : Microsoft Windows 10 Enterprise, 10.0.19043 Build 19043
* Architecture : x64

### Regression

* There is a difference for the ShortDatePattern between the frameworks net48, netcoreapp2.1, netcoreapp3.1 and the framework net5.0

**Comment by Clockwork-Muse** [comment]
Almost certainly due to [the switch to ICU for globalization entry](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api).  Does setting the flag they mention show the previous behavior?

Note that going forward it's recommended that use use the ICU globalization for ease of porting to other platforms.

**Comment by draphyz** [comment]
Yes, it works. Thank you for the information. I wasn't aware of this change.
