### ISSUE TITLE
System.Text.Json source generator produces nullability warnings for NRT properties

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/runtime#59464]
### Description

The System.Text.Json source generator produces nullability warnings (CS8260, and CS8604) during a build.

```csharp
using System.Text.Json.Serialization;

Console.WriteLine("JSON Source Generator repro");

public class Class
{
    public Uri? NullableUri { get; set; }
    public byte[]? ByteArray { get; set; }
}

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(Class))]
internal partial class Context : JsonSerializerContext
{

}
```

The above code produces 2 warnings:

```
warning CS8620: Argument of type 'JsonTypeInfo<Uri>' cannot be used for parameter 'jsonTypeInfo' of type 'JsonTypeInfo<Uri?>' in 'void JsonSerializer.Serialize<Uri?>(Utf8JsonWriter writer, Uri? value, JsonTypeInfo<Uri?> jsonTypeInfo)' due to differences in the nullability of reference types.
warning CS8604: Possible null reference argument for parameter 'value' in 'void Context.ByteArraySerialize(Utf8JsonWriter writer, byte[] value)'.
```

Runnable repro [here](https://github.com/JakeYallop/STJ-source-generation-warnings-repro).

### Impact

This breaks CI builds set up to fail if there are any warnings present in the project.

Are there any workarounds that can be done in the meantime, other than disabling the warnings in CI builds?

### Configuration
.NET Version: NET 6 RC1

**Comment by layomia** [comment]
Source generators shouldn't emit code that causes errors in user projects. Looking into whether the relevant nullability info is available through the Roslyn compilation APIs. cc @chsienki @jaredpar for any tips.

**Comment by ericstj** [comment]
I see https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Nullability%20Public%20API%20Design%20Notes.md that describes this API in roslyn.
@buyaa-n also recently added this to reflection in https://github.com/dotnet/runtime/pull/54985.

Presumably the serializer isn't really doing anything different for nullable annotated types today since it wasn't observing that. 
 Should we disable nullability in the generated code (`#nullable disable`) for now and see about fixing that in 7.0?
