### ISSUE TITLE
Question: What is the minimum version of libicu required?

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#59536]
I can't find this documented anywhere. I'm trying to determine what is the minimum version of libicu required for .NET? I see the Docker [runtime-deps](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/3.1/bullseye-slim/amd64/Dockerfile#L11) is installing version 67. I have anecdotally seen 60 but is it documented anywhere what is the required version?

**Comment by tarekgh** [comment]
@normj .NET can run with version [50 and up](https://github.com/dotnet/runtime/blob/7e67f8763d998ce0a626e91c647122cdc19d7c5c/src/libraries/Native/Unix/System.Globalization.Native/pal_icushim.c#L172). The catch here is there are some functionalities will be enabled with the higher ICU versions only. Example of that, TZ ID conversions wouldn't work if you have ICU version less than `52`. In general, we always recommend running with the latest ICU if possible. 

I am closing this issue but feel free to reply back with any question and we'll be happy to help answering it.

**Comment by normj** [comment]
@tarekgh Thanks for getting back to me. With version 50 I'm getting the following error at least on ARM. Version 50 is the default version on Amazon Linux 2 ARM. When I upgrade to 60 the error goes away.

```
Cannot get symbol ucol_setMaxVariable_50 from libicui18n
Error: /lib64/libicui18n.so.50: undefined symbol: ucol_setMaxVariable_50
Aborted
```

**Comment by tarekgh** [comment]
@normj sorry I forgot to mention about ARM64 case. For that architecture need to have at least ICU v52. The reason is this architecture built linking to some ICU APIs that not existing before v52. The [issue](https://github.com/dotnet/runtime/issues/57983#issuecomment-923509355) is tracking the same issue.

In your case, will be able to get at least ICU v52 installed on your environment? I am happy to help as needed here if you can explain more about what you are trying to do in general.

**Comment by normj** [comment]
@tarekgh Thanks that is what I needed. We have version 60 in the Amazon Linux 2 yum repo we can update to. I just wanted some assurance that version was good enough.

**Comment by normj** [comment]
I would recommend getting the native dependency minimums documented somewhere though.
