### ISSUE TITLE
C# string formatting with negative numbers are not working as expected in net5.0 

### ISSUE THREAD

**Issue by bharatbodage** [dotnet/runtime#59570]
C# string formatting with negative numbers are not working as expected in net5.0 
- I have created .net 4.8 framework console app and net 5.0 console app. 
- Then I tried to set value.ToString(format) in both versions and they are giving different results 
- Example: var d = -0.0305441935; Console.WriteLine(d.ToString("f1")); 
- In .Net Framework 4.8 console app it gives me result => 0.0 
- whereas as in net 5.0 console app it gives me result => -0.0 
- Behavior in both should be same. 
- Look like its broken in net 5.0 version.

**Comment by stephentoub** [comment]
cc: @tannergooding

**Comment by tannergooding** [comment]
This is as expected and fits the IEEE 754 requirements around parsing and formatting floating-point values: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

In particular, `+0.0` and `-0.0` are distinct values in the floating-point world and can impact the result of various operations. Since .NET Core 3, we have produced roundtrip able values by default which includes preserving the sign of negative zero.

If you would like to remove the sign, you will need to use a [Custom numeric format string](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) and in particular, you'll need to use the a 3 section format. I believe (but have not confirmed) that `d.ToString("0.0;-0.0;0.0")` should be roughly equivalent to the `"f1"` behavior of .NET Framework

**Comment by bharatbodage** [comment]
@tannergooding  Thanks for explanations. This was very helpful.
