### ISSUE TITLE
Using delegate*<void*, uint> instead of a managed delegate in Win32 CreateThread crashes the runtime.

### ISSUE THREAD

**Issue by ChrisKoebke** [dotnet/runtime#59605]
### Description
When using delegate*<void*, uint> instead of defining a managed delegate type, the Win32 CreateThread() method crashes the process without an exception.

### Configuration
- .NET 6 (RC1)
- Windows 10
- x64
- VS2022 Preview
- Regular Build, no AOT

### Demo project for repro
[ConsoleApp4.zip](https://github.com/dotnet/runtime/files/7230319/ConsoleApp4.zip)

**Comment by jkotas** [comment]
Function pointers used for interop must have `unmanaged` calling convention. The crash is caused by managed vs. unmanaged calling convention mismatch.

Try changing `delegate* <void*, uint> lpStartAddress` to `delegate* unmanaged<void*, uint> lpStartAddress` and annotating the `Proc` method with `[UnmanagedCallersOnly]`.

**Comment by PathogenDavid** [comment]
The crash is happening because you're letting a managed function pointer be called by unmanaged code. You need to specify the calling convention on `CreateThread`:

```csharp
[DllImport("kernel32.dll")]
public static unsafe extern void* CreateThread(SECURITY_ATTRIBUTES* lpThreadAttributes, ulong dwStackSize, delegate* unmanaged[Stdcall]<void*, uint> lpStartAddress, void* lpParameter, uint dwCreationFlags, uint* lpThreadId);
```

As well as on `Proc`:

```csharp
[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
static uint Proc(void* argument)
```

(`WINAPI` maps to `stdcall`. If I remember right you can also just specify the general `unmanaged` function pointer, which defaults to `stdcall` on Windows.)

--------

As an aside, you need to specify it on your `THREAD_START_PROC` delegate too, I suspect that you're either being saved by the marshaler or that only works by accident:

```csharp
[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public unsafe delegate uint THREAD_START_PROC(void* parameter);
```

---------

As even more of an aside, `dwStackSize` should technically be `nuint`, not `ulong`.

**Comment by ChrisKoebke** [comment]
Thanks so much for your help!! This solved it 🙏

**Comment by hypeartist** [comment]
Seems like there is something to do with memory protection. First call ```Win32.CreateThread(null, 0, &Proc, null, 0, null)``` works just fine, but the next fails. Subsequential calling of ```Win32.CreateThread``` with a pointer to a different method works ok:
```
    static uint Proc(void* argument)
    {
        for (int i = 0; i < 10000; i++)
        {
            var x = "Hello " + i;
        }
        return 0;
    }

    static uint Proc2(void* argument)
    {
	    for (int i = 0; i < 10000; i++)
	    {
		    var x = "Hello " + i;
	    }
	    return 0;
    }

    public static void Main()
    {
        for (int i = 0; i < 2; i++)
        {-
            if (i == 0)
            {
	            var t = Win32.CreateThread(null, 0, &Proc, null, 0, null);
	            Win32.WaitForSingleObject(t, 0xffffffff);
            }
            else
            {
	            var t = Win32.CreateThread(null, 0, &Proc2, null, 0, null);
	            Win32.WaitForSingleObject(t, 0xffffffff);
            }
        }

        Console.WriteLine("Done"); // <- this is never reached, process crashes
        Console.ReadKey();
    } 
```

**Comment by jkotas** [comment]
> First call works just fine, but the next fails. 

First call just got lucky,

Crashes caused by mismatched signatures or calling convention are non-deterministic.
