### ISSUE TITLE
NLS vs ICU difference in invariant case changing of title case characters.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#59661]
### Description

When .NET uses the ICU globalization libraries, changing the case of a title case character in the invariant culture works the most intuitive way:

``` csharp
Char.ToUpperInvariant('ǲ') == 'Ǳ';
Char.ToLowerInvariant('ǲ') == 'ǳ';
```

When using the NLS libraries by setting `DOTNET_SYSTEM_GLOBALIZATION_USENLS` to `true` however, the methods don't change the character at all:

``` csharp
Char.ToUpperInvariant('ǲ') == 'ǲ';
Char.ToLowerInvariant('ǲ') == 'ǲ';
```

### Configuration

.NET 6, RC 1, Windows 10 21H1

### Regression?

No

### Other information

Even if it's by design, it should be documented somewhere as another NLS vs ICU difference.

**Comment by tarekgh** [comment]
@teo-tsirpanis thanks for your report. As you indicated this is by design as switching using ICU is expected to notice differences comparing to NLS. This is the whole point switching to ICU to always get consistent behavior across platforms and conforming with whatever Unicode standard spec.

> Even if it's by design, it should be documented somewhere as another NLS vs ICU difference.

I don't think we can list every single difference between NLS and ICU. We already documented the [generic breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api) giving some idea what to expect in general. Also, we have the issue https://github.com/dotnet/runtime/issues/43956 which is listing some of these issues. I'll add a link to this issue there.
