### ISSUE TITLE
CS0433 The type 'ImageConverter' exists in both....

### ISSUE THREAD

**Issue by vkuehn** [dotnet/runtime#59807]
### Description

CS0433 is now well know and a workaround would be an alias the the desired type. For me in a visual Studio 2019 Project for dotnetcore 5.0 in the using section of a class file this

using SDmageConverter = System.Drawing.ImageConverter;

or even for

System.Drawing.ImageConverter imgConverter = new System.Drawing.ImageConverter();

did already cause a
CS0433	The type 'ImageConverter' exists in both 'System.Drawing.Common, Version=5.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Windows.Extensions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

I have imported 
Syste.Drawing.Common and System.ServericeModel.Duplex and some others used for a soap connection

Looks like System.ServericeModel... relies on a dll system.windows....

I would expect the use of an alias is a workaround but visual studio 2019 complains about it.

### Configuration

 dotnetcore 5.0 on a windows 10 machine

  <ItemGroup>
    <PackageReference Include="itext7" Version="7.1.16" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.1" />
  </ItemGroup>

### Regression?

There is already a conflict with itext but there an alias did help as workaround. Wonder why not in that case ?

**Comment by vkuehn** [comment]
Configuration did disapear
     |PackageReference Include="itext7" Version="7.1.16" /|
    |PackageReference Include="System.Data.SqlClient" Version="4.8.3" /|
    |PackageReference Include="System.Drawing.Common" Version="5.0.2" /|
    |PackageReference Include="System.ServiceModel.Duplex" Version="4.8.1" /|
    |PackageReference Include="System.ServiceModel.Http" Version="4.8.1" /|
    |PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.1" /|
    |PackageReference Include="System.ServiceModel.Security" Version="4.8.1" /|

**Comment by safern** [comment]
Hello @vkuehn, thank you for your report.

The reason why you are seeing that is because the type `ImageConverter` used to be defined on `System.Windows.Extensions` on versions prior to the `5.0.0` version of the package. However on the `5.0.0` version of the package we moved the type to `System.Drawing.Common` and added a `TypeForward` on `System.Windows.Extensions`. See here: https://github.com/dotnet/runtime/blob/a2f721ef1d030b15ddcc6483b8b68d2344e0f56e/src/libraries/System.Windows.Extensions/ref/System.Windows.Extensions.Forwards.cs#L9

You are referencing `System.Drawing.Common` version `5.0.2` which now contains `ImageConverter` and `System.ServiceModel.Primitives` depends on `System.Windows.Extensions` version `4.7.1`, which still contains `ImageConverter` so that's why the type shows as duplicated.

The way to fix this is to use a newer version of `System.Windows.Extensions` or an older version of `System.Drawing.Common` so that the type only exists on one or the other. As a workaround I would recommend that you add a package reference to `System.Windows.Extensions` version `5.0.0`, that should fix your problem. i.e:

```xml
<PackageReference Include="System.Windows.Extensions" Version="5.0.0" />
```

Please let me know if that helps and if we can close the issue.

**Comment by vkuehn** [comment]
That did indeed fix the issue. 

Actually I have installed the newest Versions just this week through NuGet  !

If you won't mind updating System.ServiceModel.xxx Packages for a dependency to the latest System.Windows.Extensions version or even better avoid such situation by cleaning duplicate packages in the latest versions

**Comment by safern** [comment]
I'm glad you got unblocked. For the System.ServiceModel.* packages, including @mconnew and @HongGit as an FYI.

**Comment by mconnew** [comment]
We'll update to the 5.0 version of the packages for .NET 6 RTM release.
