### ISSUE TITLE
FileInfo.DirectoryName return invalid information on MacOS

### ISSUE THREAD

**Issue by MarkLynch-puzzel** [dotnet/runtime#59948]
### Description

The problem is on the FileInfo object returns an invalid path string when the DirectoryName property is called.

```
string filepath = "file:///Users/ml/Projects/example/bin/Debug/netcoreapp3.1/Some.dll";
Fileinfo fi = new FileInfo(filepath);
Console.Write(fi.DirectoryName);

```
this will output **/Users/ml/Projects/example/file:/Users/ml/Projects/example/bin/Debug/netcoreapp3.1**

If you then try to use the directory string to say iterate the other files in the directory
foreach(var file in Directory.GetFiles(fi.DirectoryName)){}
this causes an exception to be thrown.

Code works on Windows, but not on MacOS, I have not tried on any Linux environments yet. 

### Configuration

.NET : version .net core 3.1
OS : macOS Big Sur v11.6
Architecture: x64 (intel core i7)

### Regression?

Code works on Windows, but not on MacOS, I have not tried on any Linux environments yet. 

### Other information

My current workaround is to have a helper function split the path on the 'file:' and return the latter section.

**Comment by carlossanlop** [comment]
Thanks for reporting, @MarkLynch-puzzel.

The `file://` prefix indicates you are passing a URI, not a path. The System.IO path-related APIs do not guarantee they will be able to handle URIs as you expect.

The reason why `FileInfo.DirectoryName` gives you that value, is because when you passed the URI to the `FileInfo` [constructor](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L22), it [internally](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L27) tries to determine [the full path of the passed path](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L35). Since URIs do not start with a `/`, [`Path.GetFullPath`](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L17) thinks it's dealing with a relative path, so it[ prepends the current directory to the URI](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L58-L61), and uses that as the full path.

The behavior on Windows happens to be benign for your test case when passing a URI to the `FileInfo` constructor because [`Path.GetFullPath` calls](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L141) an [internal Windows P/Invoke](https://github.com/dotnet/runtime/blob/608128995e6bf9acefadc34cd4ba01fcac510d92/src/libraries/System.Private.CoreLib/src/System/IO/PathHelper.Windows.cs#L77) that is capable of removing the URI prefix and normalizing the path with Windows separators (`\`).

Unix (Linux or MacOS) do not have a P/Invoke (that I know of) that can convert a URI into a path for you.

Your workaround is the correct thing to do, although I would make sure to remove the full URI prefix `file://`, and leave one `/` to indicate it's a rooted path.

Let us know if you have any more questions.
