### ISSUE TITLE
Assert - Type Too Big to log for ETW

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/runtime#6027]
Please have a look at http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_pri1r2r_tst/lastCompletedBuild/testReport/Loader.classloader.generics.GenericMethods/VSW491668/VSW491668/

It is firing for Ubuntu Checked R2R test run - and passes for release likely because Asserts dont compile for that build. 

@davmason PTAL.

CC @sergiy-k @lt72

**Comment by mangod9** [comment]
Closing since this hasnt been touched for a few years.

**Comment by MichalStrehovsky** [comment]
@mangod9 we still have the disabled test here:

https://github.com/dotnet/runtime/blob/233c65db10389b431728ca79be7fdcd7619fee89/src/tests/Common/dirs.proj#L16

It's in dirs.proj because it was added there instead of issues.targets 6 years ago for whatever reason, so it doesn't go through the "we have tests blocked on closed issues in issues.targets" process.

We need to either delete the test or keep the issue open.
