### ISSUE TITLE
Regression in Blazor WebAssembly startup time

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/runtime#60349]
We'll use this issue to track the investigation around the first UI render regression (~100ms)

![image](https://user-images.githubusercontent.com/34246760/135540558-53fdfaf2-f086-484d-8391-e7e09f317d9d.png)

**Comment by radekdoulik** [comment]
I have checked `-O3 (-Oz compile)` meanwhile with 2.0.21 and added it to the table.

**Comment by lewing** [comment]
@radekdoulik  can you open a PR -O2 for the change in `main` and queue up a backport to `release/6.0` that we should probably target for servicing at this point.

**Comment by pranavkm** [comment]
AspNetCore changes during this internal: https://github.com/dotnet/aspnetcore/compare/223d6e527cc98ce13fe45e4e14911013dd5ad807...69eb4b38bca90bb830f290a6eaa5a61650dc87ac

Runtime changes: https://github.com/dotnet/runtime/compare/cf2938f44fc1494ae984c52a1568a03d51e513ca...83a4d3cc02fb04fce17b24fc09b3cdf77a12ba51

That said, it looks like this made a recovery since which is why I wasn't super concerned about it:

![image](https://user-images.githubusercontent.com/174281/137988393-e5c6dea9-6ab8-4728-a85f-0a67737baf29.png)
