### ISSUE TITLE
System.Diagnostics.Eventing.Reader.EventLogRecord throws an InvalidOperationException on Windows 11

### ISSUE THREAD

**Issue by RyusukeFujita** [dotnet/runtime#60740]
### Description

On Windows 11, `System.Diagnostics.Eventing.Reader.EventLogRecord` (version [5.0.1](https://www.nuget.org/packages/System.Diagnostics.EventLog/5.0.1)) throws an InvalidOperationException when accessing its Properties:

  > System.InvalidOperationException: We do not have 18 variants given for the UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties)

This happens for any event log file and I can reproduce with a very minimal sample program (see [Reproduction Steps]).
The issue does not occur when using the same log file on Win10.  

The exception occurs on the following call stack:  

    at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtRenderBufferWithContextSystem(EventLogHandle contextHandle, EventLogHandle eventHandle, EvtRenderFlags flag, SystemProperties systemProperties, Int32 SYSTEM_PROPERTY_COUNT)
    at System.Diagnostics.Eventing.Reader.EventLogRecord.PrepareSystemData()
    at System.Diagnostics.Eventing.Reader.EventLogRecord.get_Id()
    at WinEvent.Program.Main(String[] args) 

The problem is that `SYSTEM_PROPERTY_COUNT` is hard coded to 18, but `propCount` is 16 on Win11. 
See below:

  https://github.com/dotnet/runtime/blob/895c99cc502913fd7393b95af7cae5b9e6fbdea3/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/NativeWrapper.cs

  ```C# 
        public static void EvtRenderBufferWithContextSystem(EventLogHandle contextHandle, EventLogHandle eventHandle, UnsafeNativeMethods.EvtRenderFlags flag, SystemProperties systemProperties, int SYSTEM_PROPERTY_COUNT)
        {
            IntPtr buffer = IntPtr.Zero;
            IntPtr pointer = IntPtr.Zero;
            int bufferNeeded;
            int propCount;

            try
            {
                bool status = UnsafeNativeMethods.EvtRender(contextHandle, eventHandle, flag, 0, IntPtr.Zero, out bufferNeeded, out propCount);
                if (!status)
                {
                    int error = Marshal.GetLastWin32Error();
                    if (error != UnsafeNativeMethods.ERROR_INSUFFICIENT_BUFFER)
                        EventLogException.Throw(error);
                }

                buffer = Marshal.AllocHGlobal((int)bufferNeeded);
                status = UnsafeNativeMethods.EvtRender(contextHandle, eventHandle, flag, bufferNeeded, buffer, out bufferNeeded, out propCount);
                int win32Error = Marshal.GetLastWin32Error();
                if (!status)
                    EventLogException.Throw(win32Error);

                if (propCount != SYSTEM_PROPERTY_COUNT)  // <<-- Here propCount is 16 in Win11
                    throw new InvalidOperationException("We do not have " + SYSTEM_PROPERTY_COUNT + " variants given for the UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties)");
  ```

  https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogRecord.cs

  ```C#
  namespace System.Diagnostics.Eventing.Reader
  {
      public class EventLogRecord : EventRecord
      {
          private const int SYSTEM_PROPERTY_COUNT = 18;  <<-- 

  ```

I'm not sure if this is considered as a Win11's bug.
According to [EvtRender](https://docs.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtrender), I don't see any guarantee about PropertyCount.

Note that PowerShell `Get-WinEvent` is also affected by this because it uses `System.Diagnostics.Eventing.Reader.EventLogRecord`: 

    Get-WinEvent : We do not have 18 variants given for the  UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties)
    At line:1 char:1
    + Get-WinEvent -Path "C:\Users\...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Get-WinEvent], InvalidOperationException
        + FullyQualifiedErrorId : We do not have 18 variants given for the  UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties),Microsoft.PowerShell.Commands.GetWinEventCommand
__

### Reproduction Steps

I can reproduce with the following simple program:

  ```cs
  using System;
  using System.Diagnostics.Eventing.Reader;

  class Program
  {
      static void Main(string[] args)
      {
          var file = args[0];
          var query = new EventLogQuery(file, PathType.FilePath, "*");

          using (var reader = new EventLogReader(query))
          {
              EventRecord record;
              while ((record = reader.ReadEvent()) != null)
              {
                  Console.WriteLine($"event {record.Id}");
              }
          }
      }
  }
  ```

Or, as I mentioned, you can see the repro with PowerShell's `Get-WinEvent` too.

### Expected behavior

EventLogRecord shouldn't fail with InvalidOperationException even if it's run on Win11.

### Actual behavior

On Windows 11, `System.Diagnostics.Eventing.Reader.EventLogRecord` (version 5.0.1) throws an InvalidOperationException when accessing its Properties.

### Configuration

I've tested with .NET Core (5.0), .NET Framework.

**Comment by mika76** [comment]
Running into this too with an app compiled in .net framework 4.5...

**Comment by ericstj** [comment]
@mika76 can you try the Windows 11 update to see if it fixes your problem?  You can check the version of Windows you're using with `winver`

**Comment by mika76** [comment]
Thanks @ericstj, but still getting it...

![Screenshot 2021-11-05 at 11 43 22](https://user-images.githubusercontent.com/229311/140498636-5fb09596-b7b6-4d61-9aa5-815e474a543a.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: We do not have 18 variants given for the  UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties)
   at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtRenderBufferWithContextSystem(EventLogHandle contextHandle, EventLogHandle eventHandle, EvtRenderFlags flag, SystemProperties systemProperties, Int32 SYSTEM_PROPERTY_COUNT)
   at System.Diagnostics.Eventing.Reader.EventLogRecord.PrepareSystemData()
   at System.Diagnostics.Eventing.Reader.EventLogRecord.get_Level()
   at EventLogViewer.Form1.dataGridView1_CellFormatting(Object sender, DataGridViewCellFormattingEventArgs e) in C:\_GIT\eventlogviewer\EventLogViewer\Form1.cs:line 292
   at System.Windows.Forms.DataGridView.OnCellFormatting(DataGridViewCellFormattingEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellFormatting(Int32 columnIndex, Int32 rowIndex, Object val, Type formattedValueType, DataGridViewCellStyle cellStyle)
   at System.Windows.Forms.DataGridViewCell.GetFormattedValue(Object value, Int32 rowIndex, DataGridViewCellStyle& cellStyle, TypeConverter valueTypeConverter, TypeConverter formattedValueTypeConverter, DataGridViewDataErrorContexts context)
   at System.Windows.Forms.DataGridViewCell.GetEditedFormattedValue(Object value, Int32 rowIndex, DataGridViewCellStyle& dataGridViewCellStyle, DataGridViewDataErrorContexts context)
   at System.Windows.Forms.DataGridView.OnCellValidating(DataGridViewCell& dataGridViewCell, Int32 columnIndex, Int32 rowIndex, DataGridViewDataErrorContexts context)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
   at System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
   at System.Windows.Forms.DataGridView.OnClearingRows()
   at System.Windows.Forms.DataGridViewRowCollection.ClearInternal(Boolean recreateNewRow)
   at System.Windows.Forms.DataGridView.RefreshColumnsAndRows()
   at System.Windows.Forms.DataGridView.DataGridViewDataConnection.ProcessListChanged(ListChangedEventArgs e)
   at System.Windows.Forms.DataGridView.DataGridViewDataConnection.currencyManager_ListChanged(Object sender, ListChangedEventArgs e)
   at System.Windows.Forms.CurrencyManager.OnListChanged(ListChangedEventArgs e)
   at System.Windows.Forms.CurrencyManager.List_ListChanged(Object sender, ListChangedEventArgs e)
   at System.Windows.Forms.BindingSource.OnListChanged(ListChangedEventArgs e)
   at System.Windows.Forms.BindingSource.ResetBindings(Boolean metadataChanged)
   at System.Windows.Forms.BindingSource.SetList(IList list, Boolean metaDataChanged, Boolean applySortAndFilter)
   at System.Windows.Forms.BindingSource.ResetList()
   at System.Windows.Forms.BindingSource.set_DataSource(Object value)
   at EventLogViewer.Form1.<DataGridView2_SelectionChanged>d__8.MoveNext() in C:\_GIT\eventlogviewer\EventLogViewer\Form1.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
EventLogViewer
    Assembly Version: 2.0.0.22457
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/_GIT/eventlogviewer/EventLogViewer/bin/Release/EventLogViewer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Robo210** [comment]
The Windows fix is available in the latest Windows Insider builds, and will be available through Windows Update soon.

**Comment by Trentent** [comment]
This issue exists in Server 2022 as well. Is the fix being ported to there as well?

**Comment by WilliamRyan2** [comment]
I am also seeing this on Windows Server 2022.  I added this to the .NET channel in the Developer Community - here's the link:
https://developercommunity.visualstudio.com/t/Win-Svr-2022-exception-SystemDiagnostic/1600819?entry=myfeedback&space=61&q=System.Diagnostics.Eventing.Reader.EventLogRecord

**Comment by danmoseley** [comment]
@Robo210 could you share whether 2022 will get the patch?

**Comment by Robo210** [comment]
I’ll look into it. I do not see this repro’ing on my WS2022 machine, and IIRC, the code change that was buggy and fixed for Win11 was not in WS2022, so the server update released this month did not contain that fix.

**Comment by WilliamRyan2** [comment]
@danmoseley and @Robo210 - thank you for chiming in - I have repro'd this consistently on several VMs that are running Win Server 2022, if you need to see them or discuss

**Comment by WilliamRyan2** [comment]
is there any update on whether a fix for this issue in Windows Server 2022 is planned?  Thank you.

**Comment by Robo210** [comment]
I have not been able to reproduce this issue on multiple Windows Server 2022 VMs that I've set up. Plus I still don't see the buggy code that was fixed for Windows 11 in the Windows Server 2022 code base at all.

**Comment by Robo210** [comment]
While I still can't repro the issue, I did just discover the bug hiding out in the Windows Server 2022 code (the perils of refactoring some massive files into smaller pieces between WS2022 and Win11...). I'll see that it gets fixed there too, and perhaps try to understand why I can't reproduce the issue at all on WS2022 even with the buggy code in hand.

**Comment by WilliamRyan2** [comment]
@Robo210 Thank you for the update.  Much appreciated!  Will this thread also be updated when the fix is available?  Thanks.

**Comment by stevenh-authlogics** [comment]
Hi. We are seeing the "We do not have 18 variants given for the" issue on Windows 2022 21H2 (OS Build 20348.707). Our app uses .NET Framework 4.8 to interact with the Windows Event Log and works fine on Windows 2019 and older. We get the following exception: 

> Exception processing event record data point. We do not have 18 variants given for the  UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties)

Is there an expected fix for 2022 any time soon as we currently can't support Windows Server 2002 with our product?

**Comment by danmoseley** [comment]
@Robo210  can you give our customers an update here?

**Comment by jameswestgate** [comment]
Behaviour we have seen on Server 2022 is that you can have an event log record that has either 16 or 18 properties. 
I have created a class for [Harmony](https://github.com/pardeike/Harmony) that allows us to patch the internal method that passes this constant value to the code that populates the event record structure. This provides us a very temporary fix, but does raise concerns what happens when the internal code is fixed.

Code can be viewed here -> https://gist.github.com/jameswestgate/b4eb35df19d74747bbac8eaa50ebed2e

**Comment by Robo210** [comment]
I can't personally provide any official support nor details about internal decisions. I can say, however, that if you have an avenue to make formal support requests to Microsoft, please do so and let them know that you are still waiting for this fix.

**Comment by NickMitrokhin** [comment]
Hi,

@Robo210, I have the same issue on Server 2022. 

The attached archive contains a simple .net core app (**myapp**) and the **test_log.evtx** file. To reproduce the issue, please build the app and execute it in the following manner:

```
./myapp.exe <path to the test_log.evtx file>
```
[attachment.zip](https://github.com/dotnet/runtime/files/9140738/attachment.zip)

You should see the error on Server 2022.

**Comment by stevenh-authlogics** [comment]
We logged a support ticket with MSFT for this. It wasn't officially admitted that it was a "known bug" and the PG was being cagy. The ticket cost was refunded so that says a lot. The official "workaround" is to use Windows Server 2019 until an update for 2022 is available that fixes the problem. No ETA was given but they were hopeful of "soon" as it has been fixed in Windows 11 already.

**Comment by NickMitrokhin** [comment]
Ok, thanks.

**Comment by Robo210** [comment]
@stevenh-authlogics if you'd like to email me your support ticket number, I can try to follow up on it from my side and make sure the people in charge of releasing the fix are aware of it. kysabo @ microsoft

**Comment by ericstj** [comment]
Likely the developer of this initially was trying to be defensive of things changing in the operating system and needing to reflect those in this library's handling of the properties and exposing them.

It looks like the two properties that were dropped in win11 were
`EvtSystemVersion`
`EvtSystemRelatedActivityID`

These are plumbed through as 
https://github.com/dotnet/runtime/blob/e55c908229e36f99a52745d4ee85316a0e8bb6a2/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogRecord.cs#L78
https://github.com/dotnet/runtime/blob/e55c908229e36f99a52745d4ee85316a0e8bb6a2/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogRecord.cs#L222
Both of these are already nullable -- as well as most of the other properties.

I believe we can just remove the exception, and stay defensive by adding an assert for an unknown property.

**Comment by Robo210** [comment]
No properties have been removed. If they are not set for an event, the Win32 API says they should be returned as an empty variant, whereas due to the issue in Windows they were being omitted entirely if the unset properties were at the end of the returned array.

That said, it would be very nice if the check in question was removed. There is a 19th property that I have been unable to expose via the Win32 API due to this hard-coded check for exactly 18 properties. The correct behavior would be to always bounds check the array accesses based on the returned number of properties, and if calling code is only aware of *X* number of properties, gracefully ignore any additional returned properties beyond *X*.

**Comment by ericstj** [comment]
> The correct behavior would be to always bounds check the array accesses based on the returned number of properties, and if calling code is only aware of X number of properties, gracefully ignore any additional returned properties beyond X.

Yes, this is what it will do now.  I put an assert in for the unknown property so that we can see it during our internal test runs on debug bits and make the update.

**Comment by Robo210** [comment]
Awesome. Now we just need .net framework to fall out of fashion (or someone to backport this fix) and then I can start exposing new things.

**Comment by danmoseley** [comment]
this could potentially be backported to versions of .NET Core still in support (basically just 6.0 as 3.1 is in security fix mode only) but it'd be a heavy lift to get it into .NET Framework. If it's tying your hands in a significant way we could start a thread about it and explore that.

**Comment by stevenh-authlogics** [comment]
Simply put. If this .NET 4.8 call doesn't work on Windows Server 2022 the way it works on every other version of Windows Server then we are unable to support our product on Windows Server 2022 and have to recommend that customers don't upgrade beyond Windows Server 2019. Microsoft customer quite honestly don't care if it is a Windows or .NET bug, it's just a Microsoft issue. It used to work fine for years and then somebody broke it. Pls get it sorted.
