### ISSUE TITLE
Multi-targeting logic in Source Generators in NuGet packages doesn't work transitively

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#60870]
When the `System.Text.Json` or `Microsoft.Extensions.Logging` nuget packages are brought in transitively, our multi-targeting logic isn't working. This is because we put the logic in the `build` folder of the nuget package, instead of the `buildTransitive` folder.

See https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior for the difference.

### Repro

Using a VS 2019 command prompt, build a project that looks like:

global.json:
```json
{
  "sdk": {
    "version": "5.0.402"
  }
}
```

.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="6.0.0-rc.2.21480.5" />
  </ItemGroup>
</Project>
```

Program.cs:
```C#
using System;
using System.Text.Json.Serialization;

Console.WriteLine("Hello, World!");

[JsonSerializable(typeof(Customer))]
internal partial class MyJsonContext : JsonSerializerContext
{
}

class Customer
{
    public string? Name { get; set; }
    public string? Address { get; set; }
    public int EmployeeID { get; set; }
    public DateTime LastModified { get; set; }
}
```

### Results

```
  C:\Users\eerhardt\source\repos\ConsoleApp36\ConsoleApp36\System.Text.Json.SourceGeneration\System.Text.Json.SourceGen
eration.JsonSourceGenerator\MyJsonContext.g.cs(4,6): error CS0579: Duplicate 'global::System.CodeDom.Compiler.Generated
CodeAttribute' attribute [C:\Users\eerhardt\source\repos\ConsoleApp36\ConsoleApp36\ConsoleApp36.csproj]
  C:\Users\eerhardt\source\repos\ConsoleApp36\ConsoleApp36\System.Text.Json.SourceGeneration\System.Text.Json.SourceGen
eration.JsonSourceGenerator\MyJsonContext.String.g.cs(5,102): error CS0102: The type 'MyJsonContext' already contains a
 definition for '_String' [C:\Users\eerhardt\source\repos\ConsoleApp36\ConsoleApp36\ConsoleApp36.csproj]
```

Thanks to @ViktorHofer for pointing this out.

**Comment by pphadke** [comment]
Here's another theme to an issue we faced with the multitargeting.

1. Our solution does not have an explicit reference to: System.Text.Json version 6.0.*, it was brought over by another dependent nuget.
2. Our build system uses .NetCore 5.0.*, so the build fails with errors documented here: https://github.com/dotnet/runtime/issues/61602
3. We tried to use the workaround documented in #2 above, but the workaround did not work due to us running into the problem discussed in this github issue. 
4. The build errors showed all the projects affected by the multi targeting issue from #2 above.
5. We have used the workaround documented here by adding an explicit System.Text.Json PackageReference to all projects from #4 above, like this: 
<ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

Following that the solution builds.

**Comment by eerhardt** [comment]
Re-opening to backport this (and transitively https://github.com/dotnet/runtime/issues/63413) to `6.0.x`.

**Comment by ericstj** [comment]
> I was saying that some folks might not even view it as a workaround. I think it's the way that analyzers were intended to work from the start. 

Correction to my understanding here.  I was imagining that this bug was preventing the generator from being *added*, when in fact it's preventing the generator from *deduplicated*.  That makes it more severe since folks not even using the generator will see the impact of this bug in the form of slow-downs to their development experience, as mentioned in https://github.com/dotnet/roslyn/issues/63522.

**Comment by eerhardt** [comment]
It makes 3 things harder:

1. Prevents the generator from being used (the original error message above).
2. Prevents the generator from being deduplicated
3. Prevents the generator from being disabled (when users don't want to use it at all).

In all 3 of those cases, the workaround is to directly reference the System.Text.Json NuGet package.

Should we move ahead with servicing 6.0.x to fix this?

**Comment by ericstj** [comment]
> Should we move ahead with servicing 6.0.x to fix this?

Yes, it sounds like it to me.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/runtime/pull/75813
