### ISSUE TITLE
Support PROCESSOR_COUNT envvar on mono

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#60915]
https://github.com/dotnet/runtime/pull/52492 adds support to specify the number of processors available to the process using an envvar in .NET Core.

This is a feature request to make it possible also for mono.

**Comment by jeffhandley** [comment]
@tmds I removed the `area-GC-mono` and `area-VM-meta-mono` labels; we try to keep only 1 `area-` label on issues and PRs to help the issue labeler pick the best one and to keep accountability clear. `area-System.Runtime` seems most appropriate to me here since the prior art was also under that area.

**Comment by lewing** [comment]
cc @marek-safar

**Comment by tmds** [comment]
Implemented by @nealef in https://github.com/mono/mono/pull/21280.
