### ISSUE TITLE
My.Computer.FileSystem.CopyFile Bug (It Changes LastWriteTime)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#60923]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MyComputerFileSystemCopyFile-Bug-It-/1551421)._

---
[severity:It's more difficult to complete my work]
Hi!
I am making a VB.NET program to sync my SD card and my PC.
Unfortunately, when using My.Computer.FileSystem.CopyFile, the last modified date of the new file created is changed: 2 seconds are added to the new file last modified date.
It is weird as it does not happen with every file, but for about 80% of them (in my case).
This bug makes imposible to sync folders with this method. It has been happening for me in Windows 8, Windows 10, Visual Studio 2015, 2017 and 2019 (I just didn´t notice what was changed between files until now because I though CopyFile function was working perfectly, but it is not.)
I attach an image where you can see these 2 second modification.
Could you please help me?
Thank you very much!

---
#### Feedback Bot on 10/12/2021, 11:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Adam Sitnik [MSFT] on 10/27/2021, 09:49 AM: 

<p>Hello <a target='_blank' href="https://developercommunity.visualstudio.com/user/80138a99-668a-4e08-a19e-9f0aefe76eba/profile">Vanerio Lama</a>! Which .NET version are you using?</p>

---
### Original Solutions
(no solutions)

**Comment by adamsitnik** [comment]
> Otherwise, we likely defer to OS utilities to perform the copy here...

@Clockwork-Muse is right, all the VB `FileSystem` type is to defer to System.IO (which just performs a sys-call) or perform a Windows sys-call directly:

https://github.com/dotnet/runtime/blob/0666ebc475871c27f5b9d4ee8e91922f20be46e9/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/FileIO/FileSystem.vb#L1136-L1145

https://github.com/dotnet/runtime/blob/0666ebc475871c27f5b9d4ee8e91922f20be46e9/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L50-L61

https://github.com/dotnet/runtime/blob/0666ebc475871c27f5b9d4ee8e91922f20be46e9/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs#L58-L60

https://github.com/dotnet/runtime/blob/0666ebc475871c27f5b9d4ee8e91922f20be46e9/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CopyFile.cs#L11-L15

https://github.com/dotnet/runtime/blob/0666ebc475871c27f5b9d4ee8e91922f20be46e9/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CopyFileEx.cs#L15-L34

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/Helpers/NativeMethods.vb#L241-L256

So the observed behavior is caused be either `CopyFileExW` or `MoveFileEx` sys-call behavior or by the hardware as also mentioned by @Clockwork-Muse 

Since it's not something that we control, I am going to close the issue.
