### ISSUE TITLE
JsonException is too general

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#610]
While working on migrating PowerShell ConvertTo-Json cmdlet from Newtonsoft to new Core Json API I discovered that JsonException is too general to be finely processed.

For example,  Json API detects a cycle, throw with JsonException and it is impossible to determine what exactly this event happened. (Only message contains the information but it is localized).
We can see more examples in the file https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs

**Proposal:** Json API should throw with more specific exceptions derived from `JsonException` class like Newtonsoft Json.NET does.

**Comment by GSPP** [comment]
Alternatively, introduce an error code enum.

**Comment by danmosemsft** [comment]
What decision do you need the calling code make based on this info? Is there a specific case you want to distinguish?

One issue with error codes historically is that it can make it harder to refactor without a potentially breaking change, since error cases may have more than one  possible error code. (Eg in case of a parser)

**Comment by iSazonov** [comment]
> What decision do you need the calling code make based on this info? Is there a specific case you want to distinguish?

It looks like the same case as IOException. 
- After I implemented ConvertTo-Json using new Json API, I had to create tests but I could not create a test to detect cycles. (We need additional tests because we implement PSObject custom converter and some other converters.)
- PowerShell catches often Core exceptions, put its in inner ones and rethrow to create more user-friendly messages/suggestions for a particular scenario. Having only generic exception it is very difficult to get there.

**Comment by ahsonkhan** [comment]
What other exception cases, outside of cycles, do you need to distinguish?

**Comment by iSazonov** [comment]
After your comment in my PR I think Core could throw in JsonSerializerOptions with specific exception if JsonSerializerOptions.MaxDepth > 1000.

**Comment by danmosemsft** [comment]
Issue to add error code to IO exception : https://github.com/dotnet/runtime/issues/926. In this case however, the error code is usually well defined (eg., directory missing) and expected to be stable.

**Comment by amosonn** [comment]
The exception case that I'm looking for is `NotEnoughData` (as it is named in `System.Text.Json/src/Resources/Strings.resx`): I want to distinguish between when deserialization fails because some data was missing (meaning I need to perform IO to receive more data), and when it fails because of an actual error in the JSON (meaning I should report error and abort).

**Comment by ahsonkhan** [comment]
Triage: We should explore all the various error cases and what distinctions we need to make to design the appropriate type hierarchy. The concern with just solving the 1-2 concerns that were brought up here is that we could have an incomplete derivation hierarchy for the exceptions. Moving to future until more scenarios have been captured or we have a better sense of the set of exception types required. If "NotEnoughData" and "MaxDepth" is good enough, then consider moving this back to 5.0.

Let's also take into account the exception hierarchy from `Newtonsoft.Json`.

**Comment by amosonn** [comment]
The current error messages should also give some direction as to what error types exist. They are not hierarchic, but they do define (at least some of) the existing cases.

**Comment by ahsonkhan** [comment]
What do you mean? The exception message does mention `but instead reached end of data`

```C#
JsonSerializer.Deserialize<List<int>>("[1, 2, 3,");
```
```text
System.Text.Json.JsonException: Expected start of a property name or value, but instead reached end of data. Path: $[3] | LineNumber: 0 | BytePositionInLine: 10.
 ---> System.Text.Json.JsonReaderException: Expected start of a property name or value, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 10.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

**Comment by amosonn** [comment]
Huh. I get "There is not enough data to read through the entire JSON array or object.", which the one named `NotEnoughData`. What I meant with my last message, is that the exception messages themselves are already quite detailed, meaning some thought has been dedicated to what exactly has "gone wrong" in each case, and therefore could be used to create a list of all the possible errors. However, this example shows that they might be *too detailed*, and need to be grouped up into types.

**Comment by eiriktsarpalis** [comment]
> For example, Json API detects a cycle, throw with JsonException and it is impossible to determine what exactly this event happened. (Only message contains the information but it is localized).

Presumably the motivation is to be able to catch specific failure modes without the need to parse exception messages. What use case might necessitate this kind of exception handling? In other words, would it be possible to share an example where, say, error handling for cycles is different vs. error handling for malformed JSON?

I personally think that STJ should encourage a "let it crash" approach to exception handling rather than exposing elaborate hierarchies below `JsonException` so that every failure mode is adequately surfaced. We should certainly make sure that exception messages are as helpful and detailed as possible though.

**Comment by eiriktsarpalis** [comment]
> Let's also think about PowerShell interactive session and utilizing of custom converters. Users could construct complex PSObject directly or by means of a cmdlet. In such cases PowerShell usually wraps .Net exceptions in custom specific exceptions so that users get more useful message for the specific script scenario.

A custom converter can throw any exception type, and this will be appropriately surfaced by the serializer for handling by the caller.

**Comment by amosonn** [comment]
Our usecase wishes to differentiate the error of unexpected end-of-data
from other errors. This is because we are stream-parsing huge JSONs, which
we can't store in-memory, so we need to lazily read more data to parse -
whenever we get a parse error stemming from end-of-data, but obviously not
for other errors (where we bubble them up).
