### ISSUE TITLE
WASM C APIs need a rooting audit

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#61008]
We pass lots of bare managed pointers to the C APIs from JavaScript, and we don't always root those pointers. Up until this point we've been operating on the assumption that the pointer is properly rooted once it enters the runtime, but I realized that the GC can't actually reach function locals/parameters, so that may not actually be true.

I expect handle-based functions are fine since they do explicit lifetime management, but almost all the stuff we call from JS doesn't use handles. We manually root things appropriately in some cases, but I think we're probably doing the wrong things in others (for example, call_method takes a raw managed pointer for 'this'.)

**Comment by kg** [comment]
@lewing pointed out that AOT was recently changed to use volatile to try and address this problem there, so maybe a similar approach in all the right spots in C would do this? I'm not certain that's enough though.

https://github.com/dotnet/runtime/pull/59352

**Comment by lambdageek** [comment]
> @lewing pointed out that AOT was recently changed to try and address this problem there efficiently, so maybe a similar approach in all the right spots in C would do this? I'm not certain that's enough though.

That's more or less what coop handles do.  So my advice would be to use handles.

See, for example https://github.com/dotnet/runtime/blob/7144c2f806788667a6810e87bbdb8748d0593968/src/mono/mono/metadata/object.c#L170-L175

Essentially you'd do:
```
int
some_wasm_function (MonoObject *x_raw, MonoObject *y_raw)
{
  int result;
  HANDLE_FUCTION_ENTER();
  MONO_HANDLE_DCL  (MonoObject, x);
  MONO_HANDLE_DCL (MonoObject, y);
  result = some_wasm_function_impl (x_raw, y_raw);
  HANDLE_FUNCTION_RETURN_VAL (result);
}
```

(note that nowadays you don't really need to pass the `MonoObjectHandle x` and `y` values down to the impl.  As long as the handles are created, the callees can use raw pointers)

**Comment by kg** [comment]
OK, so if we make sure every function exposed to JS uses handles internally, we can safely pass object pointers in. That sounds reasonable.

**Comment by kg** [comment]
@lambdageek so after messing around with this, one obstacle seems to be that handles aren't exposed to wasm code (driver.c), much like some other internals. Is there a straightforward way for me to address this - just add handle.h to a list somewhere? It seems like handle.h touches other stuff that is also internal and I don't have a good understanding of our internal/external header situation when it comes to handles, I would have expected them to be available.

**Comment by ilonatommy** [comment]
@lambdageek, @lewing, does any of you have a clue how to help with exposing handlers?

**Comment by lambdageek** [comment]
@ilonatommy We're now using a slightly different plan - with @kg.

There are three things that we're doing for the mono native-to-JS APIs:
1. We're using `MONO_ENTER_GC_UNSAFE` in the wasm C APIs (by including [gc-common.h](https://github.com/dotnet/runtime/blob/main/src/mono/wasm/runtime/gc-common.h))
2. When the C code calls out to JS, we should wrap those calls in `MONO_ENTER_GC_SAFE`
3. To pass pointers to mono objects between JS and C, we're using the `PPVOLATILE(T)` macro: for example `PPVOLATILE(MonoObject)` or just `MonoObject * volatile *` for arguments.  On the JS side, we use `WasmRoot<T>` for the arguments.  To do return values, we pass in an "out" argument that the C side fills in.

The goal of this issue is to look at all the functions in `exports.ts` (ie: all the functions that cross the JS to C boundary - both JS calls from C and also C calls from JS) and to verify that all of them either follow the above pattern or we have a note for why they're the exception.

**Comment by kg** [comment]
I believe we have comprehensively audited and revised things on our end at this point, the only remaining task is to ensure that downstream users like Blazor, Uno, etc have migrated.
