### ISSUE TITLE
Mention --roll-forward switch in error message when no matching frameworks are found

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#61019]
From https://twitter.com/KirillOsenkov/status/1454140410930950144 and the thread in https://twitter.com/akoeplinger/status/1454168539301036034

Today if you run an app but don't have the right shared framework installed we default to the "minor" roll forward policy and print this error message:
![image](https://user-images.githubusercontent.com/1376924/139491349-6a768f13-5edb-45a5-bf2e-414608db6287.png)

We could improve the user experience if we mentioned the `--roll-forward=major` switch for the `dotnet` host so the user can opt-in to running on the later framework, rather than needing to install the old framework.

**Comment by safern** [comment]
I think we could also include an aka link and point to the docs about roll forward.

**Comment by jkotas** [comment]
We treat roll forward as the fallback option that should be only used by experts who know what they are doing. The strongly preferred solution for missing major runtime version is to install it.

**Comment by jkotas** [comment]
And the full error message has a link for how you can install the missing major runtime version already:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-rc.2.21474.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-rc.2.21480.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
  ```

**Comment by safern** [comment]
> And the full error message has a link for how you can install the missing major runtime version already:
> We treat roll forward as the fallback option that should be only used by experts who know what they are doing.

Maybe we could include that in the error message? Making emphasis that the recommended solution is to install the specified framework, but that for more advanced scenarios roll forward could be used?

**Comment by jkotas** [comment]
> Maybe we could include that in the error message?

I do not think it is a good idea. It would be misleading for 99% of people who will see this error message.

If you agree with the premise that roll forward is for expert only, it is fine to depend on them to discover it in the existing documentation for roll forward.

**Comment by jkotas** [comment]
Note that there are number of other potential solutions when you see this error. For example, the actual problem may be that one has `<TargetFramework>net5.0</TargetFramework>` in the code copied from stackoverflow that needs to be changed to `<TargetFramework>net6.0</TargetFramework>`.

**Comment by filipnavara** [comment]
I didn't know about the roll forward option either until I read it on Twitter. Maybe I am not an expert. When I encountered the same error I went ahead, changed TFM, and updated dependencies to pick up Apple Silicon compatible NuGets. On one hand roll-forward would have saved me this chore for 50% of the cases if I knew about it. On the other hand it would still fail due to dependencies on Apple Silicon in many cases (but it also fails by just changing TFM).

**Comment by jkotas** [comment]
> On the other hand it would still fail due to dependencies on Apple Silicon in many cases (but it also fails by just changing TFM).

Right, it is almost guaranteed that any larger app will be broken in at least one place in roll-forward mode, unless it is explicitly maintained with attention to roll-forward by the app developer.

**Comment by filipnavara** [comment]
> Right, it is almost guaranteed that any larger app will be broken in at least one place in roll-forward mode, unless it is explicitly maintained with attention to roll-forward by the app developer.

I am not so sure about that, honestly. At least that's not my experience with .NET 5 to .NET 6 updates. I run a set of non-trivial dotnet tools like ILSpy, MSBuildStructuredLog viewer, and few others (command line tools though) and the TFM update on them was pretty painless. If it was not for the added ARM64 architecture support and related native assets a simple roll-forward would work in both cases. Since the addition of new architectures is not a common event I would expect this to work more often going forward than it does now. That would lead me to support the idea of making the option more visible (sure, mark it advanced or expert).

**Comment by RussKie** [comment]
I share the concern for discoverability (the lack of). How about we add an aka.ms link to docs explaining roll forward policies and how to enable those, if necessary?

**Comment by jkotas** [comment]
It is intentional that the roll forward is harder to discover. Roll forward is not the right option to fix this error for vast majority of the apps.

The .NET app deployment is a complex topic covered by the docs at https://docs.microsoft.com/en-us/dotnet/core/deploying/ . It would be dangerous to lead people to use roll forward without understanding the deployment topic as a whole. 

Searching for the "It was not possible to find any compatible framework version" error message gives you links to stackoverflow and github with discussion of the problem. Some of these links have mentions of roll forward and/or mentions of the above docs. Is that not enough for make the deployment docs discoverable?

**Comment by RussKie** [comment]
I hear what you're saying about being "complex and dangerous", but I do disagree with you on making developers spend time unnecessary searching online and SO (where they are much likely to get an incorrect or partially correct information), instead of providing them a link to our docs that explains the devil and clearly warns about dangers.

**Comment by akoeplinger** [comment]
Yeah if @KirillOsenkov and @filipnavara were not aware of the option then I don't know who you consider an expert :)

**Comment by jkotas** [comment]
I did not mean to imply that experts should be carrying everything in their heads. There are many expert-level details I do not know and I discover every day. And there are many that I will never learn about and that is fine.

> @KirillOsenkov and @filipnavara were not aware of the option

That just means they did not need it so far. It is reassuring that the default (install and run on the matching major runtime version that the error message guides you towards) works pretty well.

**Comment by filipnavara** [comment]
> That just means they did not need it so far. 

With the original scenario I had three options:
1) Install .NET 5 => It would break my development environment because coexistence between ARM64 SDK and x64 SDK didn't exist yet and .NET 5 didn't support Apple Silicon, so that was not an option.
2) Try running with roll-forward => I didn't do that because I was not aware of the command line option. If I knew about the option it would have helped for the command line tools [and fail for Avalonia apps because of native dependencies].
3) Updating the TFM manually => I did that but I could only do that because I had source code. Option 2) would either a) just work and get me running quicker, or b) not work with the same issue as updating the TFM (native deps)
