### ISSUE TITLE
[API Proposal]: InlineArrayAttribute

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#61135]
### Background and motivation

There were multiple proposals and ideas in the past asking for a no-indirection primitive for inline data. [Example1(inline strings)](https://github.com/dotnet/csharplang/issues/2099),  [Example2(inline arrays)](https://github.com/dotnet/runtime/issues/12320), [Example3(generalized fixed-buffers)](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#safe-fixed-size-buffers)
Our existing offering in this area – [unsafe fixed-sized buffers](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code#fixed-size-buffers) has multiple constraints, in particular it works only with blittable value types and provides no overrun/type safety, which considerably limits its use. 

In the recent hackathon we have explored a possibility of introducing a primitive for efficient, type-safe, overrun-safe indexable/sliceable inline data and it appears to be possible with relatively modest investments in the runtime.

### API Proposal

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class InlineArrayAttribute : Attribute
    {
        public InlineArrayAttribute (int length)
        {
            Length = length;
        }

        public int Length { get; }
    }
}
```     
 
When `InlineArray` attribute is applied to a struct with one instance field, it is interpreted by the runtime as a directive to replicate the layout of the struct `Length` times. That includes replicating GC tracking information if the struct happens to contain managed pointers.

Unlike "filed0; field1; field2;..." approach, the resulting layout would be guaranteed to have the same order and packing details as elements of an array with element `[0]` matching the location of the single specified field. 
That will allow the whole aggregate to be safely indexable/sliceable.

`Length` must be greater than 0.

struct must not have explicit layout.

In cases when the attribute cannot have effect, it is an error case handled in the same way as the given platform handles cases when a type layout cannot be constructed.
Generally, it would be a `TypeLoadException` thrown at the time of layout construction. 

### API Usage

```C#
// runtime replicates the layout of the struct 42 times 
[InlineArray(Length = 42)] 
struct MyArray<T> 
{ 
    private T _element0; 
    public Span<T> SliceExample() 
    { 
        return MemoryMarshal.CreateSpan(ref _element0, 42); 
    } 
} 
```     

For more details on how this attribute could be used on the Roslyn side see [`Low Level Struct Improvements` document](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#safe-fixed-size-buffers).

### Alternative Designs

During hackathon we have also explored an approach where the length is specified via a type parameter and arrays of concrete lengths are created by the way of generic instantiation - [`ValueArray<T, Size>`](https://github.com/dotnet/runtime/pull/60608).

Such approach moves some of the effort in creation of concrete struct arrays from the user to the runtime.
However in the [current .NET IL/metadata standard](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/), the `Size` parameter would need to be an integer constant encoded as a type. While such encodings are possible, finding one that everybody could comfortably accept has been an issue that we could not resolve.

### Risks

`InlineArrayAttribute` requires runtime cooperation to function correctly. On downlevel runtimes the attribute will not have any effect, contrary to the assumptions in the code that implements slicing or indexing.

### FAQ: 

**Why do we put the attribute on the struct and not on the field?** 

Allowing the attribute on individual fields introduces numerous additional scenarios and combinations that make the feature considerably more complex.
- we would need to rationalize or somehow forbid the attribute usage on static, threadstatic, RVA fields
- allowing replicated storage in classes would need to account for base classes that also may have instance fields, and perhaps with replicated storage as well.
- allowing multiple replicated fields in the same struct could make the overall layout computation a fairly complex routine when field ordering, packing, ref-ness and alignment of the fields are considered. (i.e alignment would need to consider pre-replicated sizes, but packing post-replicated)

All the above issues can be solved, but at a cost to the implementation complexity while most additional scenarios appear to be less common and easily solvable by providing a wrapper struct.

**Comment by VSadov** [comment]
CC: @jaredpar  @davidwrighton @jkotas @stephentoub

**Comment by jkotas** [comment]
I think this is ready for API review.

**Comment by lambdageek** [comment]
1. I think `Length = 0` should be allowed
2. What kind of validation do we want on the runtime side? E.g. throw `BadImageFormatException` if the length is negative, or if the struct has multiple fields.

2. Is this ok:
   ```csharp
    [InlineArray(Length = 10)]
    struct Tenner<T> where T : class {
       public T element0;
    }
   ```
   How about:
   ```csharp
    [InlineArray(Length = 10)]
    struct Tenner<T> {
       public T element0;
    }
   ```

**Comment by VSadov** [comment]
> I think Length = 0 should be allowed nevermind... I think I don't like it, actualliy.

I do not think we have a choice. We cannot remove the field that is already there, thus we cannot follow the directive to have a completely empty array.

> What kind of validation do we want on the runtime side? E.g. throw BadImageFormatException if the length is negative non-positive, or if the struct has multiple fields.

It must be a **struct with a single instance field and not having an explicit layout** 
(I forgot to add the layout part to the proposal, it would obviously be in conflict)

I am almost 50%/50% on how we handle nonconforming situations - whether we ignore or throw an exception. 
I think loader typically does not throw on misplaced attributes, but could be convinced otherwise.

> Is this ok:
   ```csharp
    [InlineArray(Length = 10)]
    struct Tenner<T> where T : class {
       public T element0;
    }
   ```
   How about:
   ```csharp
    [InlineArray(Length = 10)]
    struct Tenner<T> {
       public T element0;
    }
   ```

Yes.
I do not see anything strange about these. It is basically the target scenario similar to the example given in the proposal.
It may not be interesting to the user to make the field public, but no need to forbid that either.

**Comment by tannergooding** [comment]
> I do not think we have a choice. We cannot remove the field that is already there, thus we cannot follow the directive to have a completely empty array.

Why do you have to remove the field?

The intent behind 0 length fixed sized buffers in C/C++ is:
1. Do not impact `sizeof`
2. Be a marker field that you can succesfully use for indexing
3. Much like `length = 1`, support the concept of "variable length inline arrays" and so must be the last field in a struct

We should be able to support and special case both `0` and `1` and have it work as expected both in `sizeof` calculations and in error handling or type load exceptions if they aren't the last field of a struct.

> It must be a struct with a single instance field and not having an explicit layout

I think this is better stated as "must be a sequential layout struct with a single instance field", otherwise that leaves room for interpreting "auto layout" as being ok.

> While such encodings are possible, finding one that everybody could comfortably accept has been an issue that we could not resolve.

I do think this is somewhat unfortunate. There are numerous patterns we could allow, particularly in the numerics space (and therefore with opportunities to improve the ecosystem for ML, Tensors, and Vector acceleration) by actually having this.

I thought the idea of using multidimensional array metadata + a special recognized constraint was a clever solution here and would allow this without having to revise IL metadata.
* It's also then not much different from other newer constraints that we support like `unmanaged` or the possible new `self` constraint other than it being one the Runtime would enforce/recognize as well.

**Comment by lambdageek** [comment]
> > What kind of validation do we want on the runtime side? E.g. throw BadImageFormatException if the length is negative non-positive, or if the struct has multiple fields.
> 
> It must be a **struct with a single instance field and not having an explicit layout** (I forgot to add the layout part to the proposal, explicit would obviously be in conflict)
> 
> I am almost 50%/50% on how we handle nonconforming situations - whether we ignore or throw an exception. I think loader typically does not throw on misplaced attributes, but could be convinced otherwise.

I think field layout errors are usually TLE or BIFE when you actually try to use the type - but I don't think we're totally precise about when the exception is raised.

I guess the alternative is that any noncomforming use of the attribute is just ignored?  In that case it would be nice to have a C# analyzer flag the bad attribute usage.  Unexpected layout in conjunction with pointer-ful code seems like a source of hard to diagnose bugs.

**Comment by VSadov** [comment]
@tannergooding  - I think auto layout is ok. Since we require only one instance field, only explicit could be a problem.

**Comment by jkotas** [comment]
> I think field layout errors are usually TLE or BIFE when you actually try to use the type 

Right. Invalid uses of the attribute should produce TLE.

**Comment by tannergooding** [comment]
> I think auto layout is ok

I'm a bit skeptical. C# defaults to sequential structs so most users would have to go out of there way to define `Auto` layout in the first place. On top of that, the type layout algorithm differs in a few places for `Auto` layout + it prevents the usage in P/Invoke, so in almost every scenario you can think of, its undesirable to allow it IMO.

**Comment by VSadov** [comment]
I am ok with TLE when attribute cannot work. 

I assume  `Length == 0` is also a TLE case, right?     
(a struct can't have 0 size, and we can't make `[0]` not work, since there is a field)

**Comment by tannergooding** [comment]
> (a struct can't have 0 size, and we can't make [0] not work, since there is a field)

The intent behind length 0 isn't to remove the field, just to remove its from size calculations when it isn't the only field.
A struct only containing `T x[0]` impacts packing but not size, if you have additional fields, its no longer counted: https://godbolt.org/z/97qcx95oP
* Clang looks to have a bug here if you have a struct that only contains `T x[0]` and returns `0`, differing from GCC


That is, for:
```cpp
#include <stddef.h>
#include <stdint.h>

struct S0 { };

size_t SizeOf_S0() { return sizeof(S0); } // 1

struct S1A { int32_t x[0]; };
struct S1B { int64_t x[0]; };

size_t SizeOf_S1A() { return sizeof(S1A); } // 1 on Win32; 4 on Win64; 0 on Clang Unix; 1 on GCC Unix
size_t SizeOf_S1B() { return sizeof(S1B); } // 1 on Win32; 8 on Win64; 0 on Clang Unix; 1 on GCC Unix

struct S2A { size_t l; int32_t x[0]; };
struct S2B { size_t l; int64_t x[0]; };

size_t SizeOf_S2A() { return sizeof(S2A); } // 4 on 32-bit; 8 on 64-bit
size_t SizeOf_S2B() { return sizeof(S2B); } // 8 on Win on Unix64; 4 on Unix32

struct S3A { size_t l; int32_t x[1]; };
struct S3B { size_t l; int64_t x[1]; };

size_t SizeOf_S3A() { return sizeof(S3A); } // 8 on 32-bit, 16 on 64-bit
size_t SizeOf_S3B() { return sizeof(S3B); } // 16 on Win and Unix64; 12 on Unix32
```

Other than Unix32

**Comment by jkotas** [comment]
> Clang looks to have a bug here if you have a struct that only contains T x[0] and returns 0

And you would like this attribute to behave like clang for `Length == 0` that seems to be the most sensible behavior. Do I understand it right?

**Comment by tannergooding** [comment]
> And you would like this attribute to behave like clang for Length == 0 that seems to be the most sensible behavior. Do I understand it right?

Not quite. Clang's behavior here is a bug for `S1A`/`S1B`; the behavior is correct and matches GCC for `S2*` and `S3*`

------------------------------

The layout algorithm already special cases scenarios where the computed size is `0` and forces the managed size to `1`: https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/classlayoutinfo.cpp#L706-L710

We then later take into account the native size being `0`:
* https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/classlayoutinfo.cpp#L624-L626
* https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/classlayoutinfo.cpp#L803-L806
* https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/classlayoutinfo.cpp#L891-L895

I expect we will be tracking that it's a `fixed sized buffer` and the underlying `length`. So we should be able to do the "right thing" here by tweaking these existing spots.

------------------------------

That leaves us with:
* Treat `T x[n]` as size being `sizeof(T) * n` (therefore `Length = 0` gives `size = 0`)
* If the total size of a struct is `0`, treat it as `1`
  * Win64 is special cased in that if its `0` and contains a `fixed sized buffer`, its also upsized to be a multiple of `packing`
* If a field is to a struct where `IsZeroSized() == true` and it contains a `zero-length inline array`, don't treat it as `1` for layout purposes

This ends up:
* matching C/C++ for Windows and Unix
* does not remove the field
* does not introduce a scenario where `sizeof(T)` could return `0`

------------------------------

Given the typical usage scenario for `Length = 0` and potential bugs otherwise, I'd expect it to be fine to place additional constraints/requirements if desired:
* `T x[0]` can only be the last field of a struct
* `T x[1]` is in a similar boat, its only real usage is for variable length arrays so perhaps the same constraint for it

Which would also end up with:
* Not introducing new forms of aliasing or potential bugs where `T x[0]` would be at the same offset as the next field in the struct
* Wouldn't allow `T x[1]` to be defined where just `T x;` would do, enforcing its usage to variable-lengthed array scenarios and therefore "unsafe" C# code

**Comment by tannergooding** [comment]
> Are we sure this is not a UB in C ?

The Windows SDK and various GNU/Linux/MacOS native libraries use it fairly extensively, so I'm not really sure it matters if the language says "well defined" or "not" (not quite as much as `Length == 1`, but still frequently enough its an annoyance).

There are real type definitions in `microsoft/win32metadata` that should ideally be correctly encodable using `Length == 0` and which should be usable in P/Invoke and interop scenarios with correct `sizeof(T)` reporting and behavior around `address-of`, `indexing`, etc (generally requiring `unsafe` indexing since they are "variable length inline arrays" in practice).

**Comment by jaredpar** [comment]
One part that worries me is that the pattern here of slicing the inline array is hard to write correctly. It's very easy though to write as the example in the issue does and that creates a convenient yet large type safety hole. 

```c#
Span<int> Oops() {
  MyArray<int> array = default; 
  return array.SliceExample();
}
```

This will compile just fine and it's very unsafe.  In general I think if our API reviews need `MemoryMarshal.Unsafe` in the prime examples we should pause and think about whether or not we're pushing people towards more unsafe patterns. 

As we look to approve this in API review I think we should also be looking to promoting the correct and safe usage patterns around it. It's tricky though because the nature of this API essentially goes against the protections in the span safety rules. We may need to consider pairing this with a language change.

**Comment by jkotas** [comment]
My assumption was that this is enabling feature for https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#safe-fixed-size-buffers and the buffer will by typically accessed by auto-generated accessor that returns `ReadOnlySpan<T>`, except for the `Length = 0` cases discussed above where the memory is manually managed and the compiler cannot infer the actual length of the buffer.

**Comment by jaredpar** [comment]
I agree the primary use would be to enable that feature. I'm also trying to think of the general use case here. Essentially it's an API we're offering and what will be the implications of direct usage? Other features in that proposal, particularly offering the ability to invert our lifetime defaults, will make usage of this safe. I worry a bit though about taking this without the other though because the inclination is likely to be to go for the unsafe uses.

**Comment by jkotas** [comment]
FWIW, using Spans with fixed buffers has the lifetime type safety hole today. Example from this repo: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.WIN32_FIND_DATA.cs#L25-L28

> I worry a bit though about taking this without the other though because the inclination is likely to be to go for the unsafe uses.

I agree that we should commit to take both or neither for the release.

**Comment by jaredpar** [comment]
> FWIW, using Spans with fixed buffers has the lifetime type safety hole today. Example from this repo:

Indeed. That is somewhat mitigated because of the limitation of fixed buffers. This proposal is essentially fixing all those limitations and hence expanding the set of cases where people could fall into this safety trap. It is likely to be attractive to a number of developers. 

> I agree that we should commit to take both or neither for the release

👍

**Comment by VSadov** [comment]
> As we look to approve this in API review I think we should also be looking to promoting the correct and safe usage patterns around it. It's tricky though because the nature of this API essentially goes against the protections in the span safety rules. We may need to consider pairing this with a language change.

Yes. In the prototype we just tweaked C# escape rules to assume that all ref/span returning accessors on `ValueArray<T, Size>` behave like fields. It was sufficient since there was just one special type. 

With feature as proposed user user can write types like this and thus we need to provide means for annotating escape behavior.  
It can be  as simple as `[FieldLike]`/`[RefReturnsThis]` attribute that can be applied to members that escape "this". The attribute will both make "this" ref-returnable and will tell the escape analysis to assume that is happening.

Type-level attribute might also be acceptable, but once we start making these structs members of other structs, we will eventually want member-level annotation.

**Comment by jaredpar** [comment]
> It can be as simple as [FieldLike]/[RefReturnsThis] attribute that can be applied to members that escape "this". The attribute will both make "this" ref-returnable and will tell the escape analysis to assume that is happening.

I agree this case can be solved with that. Rather than one annotation though, I think we'd do the full set. The `[RefReturnsThis]` annotation is an expansion annotation for one specific parameter (flips a default of "can't return" to "can return"). There is also a need for the opposite (flipping a default of "can return" to "can't return"). To be fully expressive we essentially need both kinds of annotations for `ref` and value. 

`ref` lifetime is a complicated area. The defaults we chose have served us well since 7.2 but they're beginning to cause problems in a number of proposals: this proposal, `params Span<T>` wants to invert some defaults, `ref` fields is running up against friction points too, APIs to return stack alloc'd `Span<T>`, etc ... Rather than solve them individually I'd prefer to solve them together and do so in one single release. As I mentioned the nuances of the rules are complicated and I think it's better to update them in one release vs. make small updates across several releases. 

The low level struct doc does discuss these annotations a bit. It's the least refined part of the proposal though. It definitely needs work. Ideally I'd like to keep the number of annotations as small as possible (preference is two). I need to find some focused time to work through this and really tighten up that part of the proposal. 

But I'm comfortable saying there is a solution here and we can find a way to pair it with this proposal.

**Comment by VSadov** [comment]
Right. 7.2 escape defaults work well for uses such as `Span<T>` and `Memory<T>`. 
Inline arrays are different. They are not a proxy to data that someone else owns, thus the need for escape annotation.

>  I need to find some focused time to work through this and really tighten up that part of the proposal.

Let me know if you will need someone to try poking holes in the proposal :-)

**Comment by tannergooding** [comment]
Once we have a prototype, I'm happy to try it out in TerraFX.Interop, just like I did with function pointers. I have ~1500 usages of `fixed` and "artificial fixed-sized" buffers (things that can't use the existing `fixed` support before they aren't primitives).

**Comment by GrabYourPitchforks** [comment]
FWIW, we have immediate use for this in _S.T.E.W_ once this feature comes online. If desired, we can use that project to help validate the proposed design for this feature.

- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/AsciiByteMap.cs
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/AllowedBmpCodePointsBitmap.cs
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/OptimizedInboxTextEncoder.Ascii.cs

**Comment by hez2010** [comment]
Why not introduce const value specialization in generics from IL level, so we can write below code directly?

```csharp
class MyArray<T, int N>
{
    private ref Span<T> _ref;
    public MyArray()
    {
        _ref = Span.Create<T>(N);
    }
}

var array = new MyArray<int, 4>();
```

**Comment by terrajobst** [comment]
* Makes sense as proposed
* The assumptions are:
    - Runtimes that don't support this layout must not expose this attribute, which is why we don't need a `RuntimeFeature` field.
    - The developer won't apply the attribute manually, but uses language syntax and the compiler will emit the attribute, hence `System.Runtime.CompilerServices` is the appropriate home.

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class InlineArrayAttribute : Attribute
    {
        public InlineArrayAttribute (int length);
        public int Length { get; }
    }
}
```

**Comment by Joe4evr** [comment]
@hez2010 That's literally what the Alternative Designs paragraph talks about:

> ### Alternative Designs
> During hackathon we have also explored an approach where the length is specified via a type parameter and arrays of concrete lengths are created by the way of generic instantiation - [`ValueArray<T, Size>`](https://github.com/dotnet/runtime/pull/60608).
> 
> Such approach moves some of the effort in creation of concrete struct arrays from the user to the runtime. However in the [current .NET IL/metadata standard](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/), the `Size` parameter would need to be an integer constant encoded as a type. While such encodings are possible, finding one that everybody could comfortably accept has been an issue that we could not resolve.

**Comment by huoyaoyuan** [comment]
I' really don't like using magic representation of existing IL constructions, instead of standardize a new encoding.
The current IL/metadata standard is blocking many higher-kind generic features. We should push on an update on it.

**Comment by hez2010** [comment]
@Joe4evr 

Yes I've seen the Alternative Designs part. 

What I mean is that we should move forward and propose an update on the IL/metadata standard, instead of putting plenty of magic/workaround things on the existing standard. 

The standard needs evolution, and There're already many modern features and generic things being blocked for years due to the current "out-of-date" standard.

**Comment by Sergio0694** [comment]
I'm a bit confused about how would language support for constant-size arrays work when using `[InlineArray]`, as opposed to using a "shared" type like that `ValueArray<T, TSize>` that was mentioned before. Specifically, would built-in C# syntax still be possible when using this approach? How would the type match if const arrays are exposed at API boundaries, if there is not a single type that's shared by everyone?

Consider this:

```csharp
public int[4] GetSomeExampleArray() => default;
```

Imagine this is a public API. Given that that `int[4]` can no longer be universally encoded in IL as a `ValueArray<int, object[,,,]>` type, how would this work? If Roslyn just creates some implementation detail type in the declaring assembly to represent that `int[4]` type (ie. some struct with `[InlineArray]` on it of size 4), then that couldn't be used for a public API though, right? As in, if multiple assemblies had public APIs returning `int[4]` that'd make each of them return a different type, so eg. consumers couldn't freely assign one to another, which is instead possible if the type is the same (which is what `ValueArray<,>` would've provided. Similarly, doing things like `GetType()` or using reflection would return incompatible types for APIs declared in different assemblies, even if they were using a type (ie. `int[4]`) that "looks the same" 🤔

Is this `[InlineArray]` just meant to support things such as safe fixed buffers, and has the language support for constant sized arrays been discarded for now, or would that still work in some way? If so, how?

**Comment by jaredpar** [comment]
> Is this [InlineArray] just meant to support things such as safe fixed buffers, and has the language support for constant sized arrays been discarded for now, or would that still work in some way? If so, how?

Safe fixed buffers is a feature we've had on the backlog for some time now. There are multiple proposals out for it, there are a lot of existing scenarios that would immediately benefit from it and [most recent one](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#safe-fixed-size-buffers) has tentative LDM approval. It's a feature I would categorize as likely in the next few releases.

The biggest remaining question at this point is how we handle the storage at the runtime level for the feature. The language team is somewhat agnostic to this. As long as the runtime provides a mechanism that we can get a `Span<T>` over then the feature can be implemented. Thus far `[InlineArray]` is the most promising of the available proposals. 

Constant sized arrays are a relatively new idea. It does not have a formal proposal (that I'm aware of) and it has not been reviewed by LDM. There was an exciting proptotype that came out of the hackathon that provide out a number of elements but at this stage it's still a prototype item. I'm not saying it's good or bad just it hasn't been looked at in depth. Classifying it as "discarded" is an inaccurate description because can't discard something you haven't even really looked at.

**Comment by Sergio0694** [comment]
> "Classifying it as "discarded" is an inaccurate description because can't discard something you haven't even really looked at."

Sorry, bad choice of words. I know that was just a hackathon prototype, I just meant that as in "has that idea not gained enough interest for now [eg. compared to others prototyped in the hackathon that have now full proposals and/or implementations] for folks to consider investing some time into it to potentially move it out of the prototype state at some point in the future". My main question was really just about whether this `[InlineArray]` feature would effectively not allow language support for fixed sized arrays as prototyped in the hackathon (due to the various issues I mentioned above), or whether that could still be made possible in some way I'm not seeing. If `[InlineArray]` is specifically just meant to support safe fixed buffers and that would've just been out of scope, that's fine, of course. I'm not saying it's not a cool feature, it absolutely is 😄

Just was a bit confused on some details here is all.

**Comment by jaredpar** [comment]
I think the next step for the constant sized arrays work is for a proposal to get written up + have the feature championed. The prototype proved out the ability to implement but I, at least, haven't seen a good write up of how it fits into all the corners of the language. Basically the proposal. 

Happy to help review it but I don't have time to write it as my time right now is allocated to the `ref` field and `ref struct` generic works. As well as doing some finish up work on a few other proposals that are in progress for C# 11.

**Comment by deeprobin** [comment]
I guess for this we need changes to the VM.
Is this a simple issue for CLR newbies?

**Comment by huoyaoyuan** [comment]
> I guess for this we need changes to the VM.
> Is this a simple issue for CLR newbies?

Probably not. If we decide to not use generic hacks, but to support it in the type system instead, it would require huge change.

**Comment by GavinRay97** [comment]
Just wanted to comment a usecase here, I actually got here from the `FixedSizeBuffer` proposal

I'm writing a database as hobby, outside of my dayjob.
One of the  fundamental types is a `heap page`, which is essentially a 4kB buffer.


Being able to write something like this would be stellar:
```cs
struct HeapPage
{
    UInt32 PageId;
    PageType PageType;
    // <omitted rest of header>
    byte[PAGE_SIZE - SIZE_OF_HEADER_FIELDS] data;
}
```

I'd imagine there are a lot of optimizations to be had when size is known, and it would allow me to marshal directly to/from `HeapPage` as a blittable type if I had to guess.

**Comment by lambdageek** [comment]
@AaronRobinsonMSFT Do we need LibraryImportGenerator support for structs with this attribute?

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT Do we need LibraryImportGenerator support for structs with this attribute?

I would imagine we would need provide some support for this scenario.

/cc @dotnet/interop-contrib

**Comment by jkoritzinsky** [comment]
If this attribute can be applied by the author to any struct type (and not just generated on types by Roslyn), then we'll definitely need to add support for this scenario.

**Comment by lambdageek** [comment]
What runtime behavior do we want for incorrect / unusual uses of `InlineArrayAttribute`?

- Attribute applied to struct with multiple fields. => TypeLoadException? InlineArrayAttribute ignored struct is a normal struct?
- Attribute applied to struct with Auto layout. => TLE? IAA ignored?
- Attribute applied to struct with Explicit layout and Offset 0. => allowed (Offset is ignored)? TLE?  IAA ignored?  
- Atrribute applied to struct with Explicit layout and non-0 Offset. => TLE? IAA ignored?

For the Mono AOT compiler it would be slightly less work if we ignored IAA when it is used incorrectly.  Deferring an AOT error and arranging to throw a TLE at execution time is sometimes tricky.  I think this is ok for the initial use-cases of IAA as mainly an internal implementation detail by Roslyn for certain language features, but as a general purpose construct it's maybe not ideal.

**Comment by lambdageek** [comment]
> Is producing an error at AOT time and throwing TLE at runtime in non-AOT scenarios not an option? If that would be the easiest to implement, then that sounds like an enticing option to me.

Yea that's what Mono currently does for really malformed inputs (some of the existing runtime IL tests do this on purpose for example by breaking the Explicit layout rules about overlapping ref and non-ref fields).  It's just that in that case the testing infrastructure doesn't have a way to say "it's expected that the AOT compiler failed" and it's a little bit unsatisfying.

**Comment by MichalStrehovsky** [comment]
Would addressing #63654 help Mono AOT handle this case?

**Comment by lambdageek** [comment]
> Would addressing #63654 help Mono AOT handle this case?

Yes, you're right.

**Comment by tannergooding** [comment]
Could I get a couple questions answered as to how a few things are impacted.

1. Is `[InlineArray]` going to be usable as part of method parameters. That is, could you declare for example `Foo(float x[4])` (just using the C/C++ syntax here for simplicity).
2. How are assignments going to work between them. Some `[InlineArray]` declared in `struct S` wouldn't be assignment compatible (by default) with some `[InlineArray]` declared in `struct S2` since they would be different types
3. How are we expected to utilize inline arrays in areas outside of fields, such as type parameters, function pointers, etc.

Another question is specifically around the proposed but "we couldn't agree on an approach" for some `InlineArray<T, #>` approach and whether we can get a concrete summary of what the issues were and where the disagreements existed.

The approach of allowing numbers as part of a template is a powerful feature and one that is much more broadly applicable/useful to the .NET ecosystem, especially in the numerics and perf oriented domains. Trying to shuffle in the `InlineArray` feature and not considering this other aspect seems like a major downside and one that might come back to bite us later.

That is, why aren't we using a multidimensional array or even "Size" parameter: https://github.com/dotnet/runtime/pull/60519#issuecomment-946020503 -- That is, IL already allows `int[5] or `int[5, 6]`, etc. We could expose this completely unambiguously even for multidimensional inline arrays without having to specify large numbers of ranks or other unnecessary metadata, so why aren't we?

**Comment by DaZombieKiller** [comment]
> The approach of allowing numbers as part of a template is a powerful feature and one that is much more broadly applicable/useful to the .NET ecosystem, especially in the numerics and perf oriented domains.

Regarding this, several approaches for how to encode constant values in generic parameters were discussed in the C# Discord. To support `ValueArray<T, int Size>`, `MyClass<T, float F, int N>`, `MyClass<T, string N>`, etc. `F`/`N` could be a metadata token for a constant field encoded with an array length or rank. The constant field would contain the actual value to use (and would be emitted by the compiler).

For primitives that fit in 32-bits or less, it might be worth foregoing using a metadata token and using the array length/rank value directly. A runtime-recognized `MetadataTokenAttribute` could then be applied to the generic parameter when it is a larger type such as `long`, `string` or `double`.

This still requires agreeing on which method is appropriate for storing these values in IL, though. It would be very interesting to hear more about the discussions that occurred on this subject for `ValueArray<T, int Size>`.

**Comment by jaredpar** [comment]
> The approach of allowing numbers as part of a template is a powerful feature and one that is much more broadly applicable/useful to the .NET ecosystem, especially in the numerics and perf oriented domains

I agree it's much more powerful, it's also **much** more expensive. That is a significant revamping of the C# and IL type systems that is simply not necessary to solve the set of challenges that we're looking at right now. The current solution allows us to solve a number of outstanding problems such as safe fixed fields and `params ReadOnlySpan<T>`. That is a significant benefit to the ecosystem. 

The proposed solution does not preclude expanding to numeric template arguments in the future. 

Practically any feature we discuss can be done in a more expanded and powerful form so long as we're willing to up the complexity and resource investment. 

> How are assignments going to work between them. Some [InlineArray] declared in struct S wouldn't be assignment compatible (by default) with some [InlineArray] declared in struct S2 since they would be different types

This is part of the details we still need to work out. The current proposal suggests that the fields are not directly accessible but rather accessible through `Span<T> / ReadOnlySpan<T>` instances. That removes the issue of direct assignment and instead puts into known territory regarding copying spans. 

> How are we expected to utilize inline arrays in areas outside of fields, such as type parameters, function pointers, etc.

By using the types which are annotated with `[InlineArray]` 

Note: I'm somewhat ambivalent to the implementation here but this solution has a pretty understood mapping to the key C# scenarios we're trying to solve.

**Comment by terrajobst** [comment]
I assume this means the proposal is still approved as-is? Or is more discussion needed and we should reset it to api-needs-work?

**Comment by tannergooding** [comment]
I think its probably "fine" as-is, but I think there needs to be a FAQ explaining the "why" this route is being done. This may particularly be the case given the additional number of hearts/thumbs up on my comment above.

Ideally such a FAQ would also clearly cover things like how this will be exposed so that it doesn't prevent migration to some future `ValueArray<T, #>` or similar.

**Comment by Sergio0694** [comment]
> "I agree it's much more powerful, it's also much more expensive."

I just have a question on this point specifically. I understand that adding generic constants would be more work, but given that that would completely supersede the proposed `[InlinedArray]` "workaround", which is less work but still not free, this would mean that the current path requires doing more work overall just to get a subset of the features shipped sooner, right? As in, I assume this has been considered and doing a fair amount of extra overall work (as well as accepting having to deal with more complexity that will just have to forever remain in the runtime to keep supporting this) was still worth it? 🥲

**Comment by jkotas** [comment]
> I understand that adding generic constants would be more work

It would be close to two orders of magnitude more work all up. The throw-away work for `InlineArray` is noise compared to that.

**Comment by hez2010** [comment]
> "I agree it's much more powerful, it's also much more expensive."

Just putting a note that by using InlineArray approach you are accumulating tech debt that will be paid for in the future.

**Comment by tannergooding** [comment]
@VSadov, there was a small discussion on `Length == 0` above (https://github.com/dotnet/runtime/issues/61135#issuecomment-959466758).

Could you remind me on what was the outcome of that? I gave some examples on how it is spec'd to work for the Windows vs Linux ABI and listed some examples of Win32 APIs that utilize it. I don't, however, see any follow up on whether we decided to explicitly say that we're going to keep the restriction that `Length > 0` and therefore such types are "out of scope" or if the spec needs to be updated to account for them.

**Comment by VSadov** [comment]
There was no change for that. The purpose of the attribute is to replicate the storage and it will require `Length > 0`.

`T[0]` may still be a valid type from C# point of view and language may choose whichever of the behaviors described in this thread. -  I.E allowing such arrays only as the last field, etc.  
There is no need to map that to `InlineArray` though.

**Comment by tannergooding** [comment]
> There is no need to map that to InlineArray though.

It won't work "as expected" from an ABI perspective if the runtime doesn't special case it.

I think that's fine, just wanted to confirm there was no change and that we're explicitly considering it out of scope.

**Comment by hez2010** [comment]
> could the compiler solve the type mismatch by emitting a call to a method like [Unsafe.As<TFrom, TTo>(ref TFrom)](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.unsafe.as?view=net-7.0#system-runtime-compilerservices-unsafe-as-2(-0@)),

I believe you won't want this workaround. For example, how to handle reflection? Should all existing dependency injection frameworks introduce exceptions for InlineArray types? And not only the runtime, but all existing and new frameworks will need to special casing the InlineArray types. The whole type system will be unreliable due to this exception.

**Comment by hez2010** [comment]
> So no, I don't think DI would need to support the conversion.  It would be a bit like casting int[] to uint[], which is supported by the runtime but AFAIK not by DI frameworks.

DI is only a use case of reflection. This behavior will affect all reflection usage. 

My point is simple: if we can introduce integer const support in generic parameter in IL directly, all those problems are automatically gone and no workaround is needed here.

**Comment by hez2010** [comment]
> If .NET libraries first deploy InlineArrayAttribute-based APIs and a generics-based alternative becomes available later, the libraries might be unable to migrate because of compatibility requirements

We currently don't have the proposed fixed buffer language syntax support so it's okay that the InlineArray is for internal use. But if we expose InlineArray to the public and ship the syntax in the language, it will be an uncorrectable mistake and we end up with living with the issue forever.

**Comment by tannergooding** [comment]
Closing as this was implemented and is in .NET 8
