### ISSUE TITLE
Matrix4x4 class only works on Windows

### ISSUE THREAD

**Issue by Const-me** [dotnet/runtime#61178]
### Description

The .NET is cross-platform, yet functions of Matrix4x4 class which create various matrices are only compatible with Direct3D conventions about coordinate systems and clip space.

Specifically, there’re at least 4 different conventions about these things:

1. Left-handed versus right-handed coordinate system.
2. Z axis in the clip space can be clipped into [ -1 .. +1 ] like in GLES, or to [ 0 .. +1 ] like in Direct3D.

Matrix4x4 only implements one of them, and doesn’t even tell in the documentation which one that is.

Here’s a cross-platform C++ library which apparently doing right things:

https://github.com/g-truc/glm/blob/0.9.9.8/glm/ext/matrix_transform.inl#L98-L142
https://github.com/g-truc/glm/blob/0.9.9.8/glm/ext/matrix_clip_space.inl

Note how many similar but different versions of these functions are there with these `RH_NO` and `LH_ZO` suffixes, implementing different conventions about these matrices and coordinate systems. C# standard library only has one version.

If you’re unwilling to fix, at least document which convention[s] are you using in the standard library. 

### Reproduction Steps

C#:

```
const float degFovY = 90;
const float radFovY = degFovY * MathF.PI / 180;
float aspect = 16.0f / 9;

const float nearPlane = 1;
const float farPlane = 7;
Matrix4x4 proj = Matrix4x4.CreatePerspectiveFieldOfView( radFovY, aspect, nearPlane, farPlane );

Vector3 cameraPosition = new Vector3( 0, -5, 0.5f );
Matrix4x4 view = Matrix4x4.CreateLookAt( cameraPosition, Vector3.Zero, Vector3.UnitZ );
Matrix4x4 worldViewProj = view * proj;
```
GLSL for GLES 2.0:
```
// ==== Vertex Attributes ====
attribute highp vec3 inputPos;
attribute lowp vec4 inputColor;

// ==== Output Attributes ====
varying lowp vec3 vertexColor;

uniform highp mat4 worldViewProj;

void main()
{
	gl_Position = worldViewProj * vec4( inputPos, 1.0 );
	vertexColor = inputColor.xyz;
}
```

### Expected behavior

That matrix + vertex shader should be good enough to render a small mesh with coordinates around [ 0, 0, 0 ]

### Actual behavior

Doesn’t work due to different conventions about coordinate systems

### Known Workarounds

`[DllImport]` into C++ libraries like GLM or siilar

**Comment by tannergooding** [comment]
This isn't a Windows specific thing. There is no "correct" answer for left or right-handedness nor for the bounds or default direction of the Z-axis.

Due to back-compat, the `Matrix4x4` is matching what was done/exposed in XNA. IIRC, this is actual a "right-handed" system and differs from DirectX which is typically considered "left-handed".

The docs can certainly be updated to reflect the handedness of the APIs where that's relevant (contributions are welcome, docs are open source too: https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Numerics/Matrix4x4.xml)

I'd also be open to exposing APIs that explicitly list handedness and discussing whether or not we can mark the current APIs as a soft-obsolete to avoid future confusion, but that requires someone to open an API proposal: https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.yml
* I don't have the bandwidth to write up a proposal right now as I'm doing a bunch of planning for things like generic math and other .NET 7 features, so if someone cares deeply about this and is willing to put in the effort on a complete proposal, that'd be appreciated.

**Comment by hopperpl** [comment]
Actually, I do care about this.

I'm using a lot of hacks to get the Matrix4x4 working with D3D, Vulkan, OpenGL etc. There is not only an issue with handedness, but also with row/column layout (transposition). I often have to transpose matrices before I can use them in shaders. There is no standard, there is no right/wrong layout or orientation, but it causes a lot of headaches if you counter-intuitively switch matrix multiplication order to make it work. "If it looks weird, swap matrix order",

-----

https://docs.microsoft.com/en-us/windows/win32/direct3d9/dx9-graphics-reference-d3dx-functions-math

That was a great math library for matrices once. It supported left/right handed coordinate systems. It would be great to have a library that works from the start with the 3 base vectors, handedness, transposition and then in a natural way applies scale, rotation, translation etc. 

Maybe with a class (struct) around Matrix4x4 similar to DateTimeOffset/DateTime to carry additional information like handedness and transposition. All functionality of Matrix4x4 could stay as is and calculate in RHS, "Matrix4x4Offset" would just perform a correction when the final matrix "is pulled out".

-----

Regarding, transposition: This is the way I learned 3D graphic matrices decades ago, when I was young. This, for example, for translation:

```
-- -- -- dX
-- -- -- dY
-- -- -- dZ
-- -- -- --
```

but this is the way Matrix4x4 stores it (and transmits it via blitting)

```
-- -- -- --
-- -- -- --
-- -- -- --
dX dY dZ --
```

It's not wrong, it works (almost) the same. But it gives a few headaches with multiplication order as now the matrix is transposed; A(t). And then rotation order, yaw, pitch, roll. Which needs to be inverted as well. Of course using a Quaternion is better, but most 3D software still uses Euler angles in their export. 

I would really appreciate it if we can streamline this once and for all, for all the 6 * 4 * 2 = 48 different coordinate systems every 3D software is using. To provide the base vectors, to perform all standard transform operations, and then finally pulling out the matrix values in the correct format for further processing (in HW). And the beauty of matrices is that there is no need for 48 variants, it can be done in a corrective step at the final output.

**Comment by tannergooding** [comment]
> This is the way I learned 3D graphic matrices decades ago, when I was young

Yes. .NET (and indeed most vector math libraries such as `glm`, `directx math`, etc) store data in `Row Major`:
```
X.X X.Y X.Z X.W
Y.X Y.Y Y.Z Y.W
Z.X Z.Y Z.Z Z.W
W.X W.Y W.Z W.W
```

Which is conceptually the same as:
```
struct Matrix4x4
{
    public Vector4 X;
    public Vector4 Y;
    public Vector4 Z;
    public Vector4 W;
}
```

----------------------

While older versions of shaders and graphics frameworks typically stored and operated on data in `Column Major` order:
```
X.X Y.Y Z.Z W.W
X.X Y.Y Z.Z W.W
X.X Y.Y Z.Z W.W
X.X Y.Y Z.Z W.W
```

In older hardware, this had some benefits in how various algorithms could be implemented (such as by using efficient dot product implementations).

----------------------

However, in modern hardware shaders support either and while the default is still typically `column-major` for back-compat; you can trivially change the implementation to be `row-major` instead, such as via `#pragma pack_matrix( row_major )` in HLSL.

This is because modern GPU hardware often no longer operates in terms of actual SIMD operations (like you have on the CPU) and is instead "superscalar" and does many scalar operations at the same time in parallel; which improves overall performance and throughput for these cases; so there is no real benefit or drawback to `row major` vs `column major` on the GPU side.

CPUs are still not "superscalar" and so having it be setup for natural SIMD processing and for typical CPU operations still means that "row major" is "better" and that's not going to change, even in some new type.

I would be fine with exposing additional functions and to better provide parity with other major Graphics Math Libraries such as DirectX Math (https://github.com/Microsoft/DirectXMath) and GLM (https://github.com/g-truc/glm). These would involve additional methods that actually specify their handedness and which take care of correctly handling `quaternions`, `euler angles`, or other bits in a layout agnostic manner.
* Several of these helper functions already exist, they just don't call out the handedness where that's applicable and that's the major problem, IMO

**Comment by tannergooding** [comment]
Just noting the GLM docs are actually slightly confusing. The constructor indicates that its column major:
```
		X1 const& x1, Y1 const& y1, Z1 const& z1, W1 const& w1,
		X2 const& x2, Y2 const& y2, Z2 const& z2, W2 const& w2,
		X3 const& x3, Y3 const& y3, Z3 const& z3, W3 const& w3,
		X4 const& x4, Y4 const& y4, Z4 const& z4, W4 const& w4
```

However the following code shows they store it in `M41, M42, M43`:
```cpp
glm::mat4x4 x = glm::mat4x4(
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        1, 2, 3, 1
    );

    glm::vec3 scale = {};
    glm::quat orientation = {};
    glm::vec3 translation = {};
    glm::vec3 skew = {};
    glm::vec4 perspective = {};

    glm::decompose(x, scale, orientation, translation, skew, perspective);

    // translation == 1, 2, 3; matching System.Numerics.Matrix4x4
    // column major would've returned 0, 0, 0
```

**Comment by tannergooding** [comment]
Going to close this as not actionable. We'd be willing to take an API proposal that extends `Matrix4x4` (and friends) to expose the "missing" functions that support the other handedness.

Such a proposal would need to follow the outline laid out by https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps, which is also the template covered by https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.yml&title=%5BAPI+Proposal%5D%3A+
