### ISSUE TITLE
Remove unsupported fields from `GeneratedDllImport`

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#61181]
- https://github.com/dotnet/runtime/pull/61182
- https://github.com/dotnet/runtime/pull/65164

**Comment by jkotas** [comment]
Do we have a plan on what to do about `CharSet`, `CharSet.Ansi` in particular?

`CharSet.Ansi` makes no sense on non-Windows. I see that the [source generator requires you to explicitly specify `CharSet` when marshaling strings](https://github.com/dotnet/runtime/blob/main/docs/design/libraries/DllImportGenerator/Compatibility.md#semantic-changes-compared-to-dllimportattribute). At minimum, would it make sense to drop this requirement so that people on non-Windows do not have to write `CharSet.Ansi` and scratch their head wondering what it means?

**Comment by AaronRobinsonMSFT** [comment]
> Do we have a plan on what to do about CharSet, CharSet.Ansi in particular?

@jkotas Yep. The Interop team was discussing that. One of our current ideas involves the `Encoding` class and completely ignores the `CharSet` for `GeneratedDllImport` scenarios. We are still in preliminary discussions about it but will propose something soon.

**Comment by jkotas** [comment]
> One of our current ideas involves the Encoding class

I like this idea. It would allow us to handle all less common cases, without hardcoding them. But I think we should also have less verbose shortcuts or defaults for the most common cases (UTF16 on Windows, UTF8 on Unix, etc.). `CharSet` may be useful for these shortcuts.

**Comment by AaronRobinsonMSFT** [comment]
Encoding proposal at https://github.com/dotnet/runtime/issues/61326

**Comment by elinor-fung** [comment]
Fields have been pared down and now match the API approved in https://github.com/dotnet/runtime/issues/46822
