### ISSUE TITLE
wasm InvokeJS return value is broken

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#61192]
### Description

The transition to using a custom closure instead of eval broke the return value of InvokeJS.

### Reproduction Steps

```csharp
        var res = Interop.Runtime.InvokeJS(@"1 + 2", out int exceptionalResult);
        if (exceptionalResult != 0)
            throw new Exception("InvokeJS failed " + res);
        else if (res != "3")
            throw new Exception("InvokeJS returned invalid result " + res);
```

### Expected behavior

Doesn't throw

### Actual behavior

Throws, exception message indicates there was no return value

### Regression?

Yes

### Known Workarounds

If you put 'return' in the JS expression it may work

**Comment by kg** [comment]
cc @pavelsavara 

The ideal would be for us to figure out that we need to insert a 'return' keyword somehow, but I'm not sure there's any obviously correct way to do that.

**Comment by kg** [comment]
The new version of InvokeJS appears to also be considerably slower than the old one (~2x slower for a simple test), according to my benchmarks. While I would hope no one is relying on it to have high performance, it's worth trying to figure out whether we can accept the hit (and whether it's potentially much worse in Firefox or Safari, since I've only run these benchmarks in v8.)

**Comment by pavelsavara** [comment]
Is slower speed of micro-benchmark caused by the fact that `eval()` is interpreted and function constructor is JIT ?
Anyway, I don't think people should use this in perf critical scenarios.
We have `new Function("a", "b", "return a + b");` in C# which would perform much better with re-use of the function, than `InvokeJS` which needs to parse code on each call.

I don't have any good idea how to make `1+2` expression work either.
We could get back to `eval`, but I don't like it.
I will think about it some more, especially how to make that eval with `MONO, BINDING, Module` in the closure instead of global.

**Comment by maraf** [comment]
The previous version with `eval` supported a scenarios where state was shared between `InvokeJS` calls.

```
Interop.Runtime.InvokeJS("var a = 5;");
...
int a = Interop.Runtime.InvokeJS("a")
```

**Comment by pavelsavara** [comment]
The [original implementation](https://github.com/dotnet/runtime/pull/60928/files#diff-59bc072b78d32f6c66bd6e590eda1c5a723a3b870690d9c8ad7a980348cab0b1L140) was essentially 

EM_ASM_INT
```
var res = eval (js_str);
if (res === null || res === undefined)
  return 0;
else
   res = res.toString ();

```

**Comment by lewing** [comment]
The api is still private so we can definitely still discuss what the right course of action is.
