### ISSUE TITLE
use System.Drawing.Common.Bitmap.GetPixel got RGB data but the result is different from PS

### ISSUE THREAD

**Issue by ganluo960214** [dotnet/runtime#61195]
use System.Drawing.Common.Bitmap.GetPixel got RGB data but the result is different from photoshop.

many pixel are not the same. Especially when two colors intersect.

```csharp
Bitmap bitmap = new Bitmap(file.Path);
bitmap.GetPixel(400, 361);
```

```
nuget
System.Drawing.Common 5.0.2
```

![image](https://user-images.githubusercontent.com/8499204/140273330-0fee3460-db70-4139-90a1-875bc58f124e.png)

**Comment by ganluo960214** [comment]
this is origin image

![3-2-2](https://user-images.githubusercontent.com/8499204/140273509-332260c7-f182-4171-ae72-608f1aec9843.jpg)

**Comment by JimBobSquarePants** [comment]
https://github.com/dotnet/runtime/blob/bfc5ebc14a1e249fce8dab095361e322ef349180/CONTRIBUTING.md#writing-a-good-bug-report

**Comment by ganluo960214** [comment]
@JimBobSquarePants I use blank issue, I don't know it's bug or not.

**Comment by ganluo960214** [comment]
I tired use golang do something and show me the third result. next I will try rust. this is so fxxx.

**Comment by hopperpl** [comment]
Just a general note about images:

* Photoshop uses colorspace correction (color profiles)
* Photoshop also uses pixel averaging based on brush settings to pick up the color
* JPEG files use lossy compression; the used IDCT transform is defined with an error margin
* JPEG also uses YUV colorspace; YUV to RGB transformation is not exact and based on decoder settings can lead to additional error margins (within specification)

For JPEG images, minute differences in pixel values are normal among different decoder implementations, this is by design.
For pixel exact images use a lossless format like PNG and disable all colorspace corrections in Photoshop.

**Comment by ganluo960214** [comment]
@hopperpl thank u so much.
