### ISSUE TITLE
Create Codespaces Prebuild workflow fails on forks of this repository

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#61250]
My fork of this repository [is getting GitHub Actions errors](https://github.com/teo-tsirpanis/dotnet-runtime/actions/runs/1424617665) that seem to occur because prebuilding Codespaces is not generally available.

**Comment by stephentoub** [comment]
@eerhardt, seems more people besides me have been hitting this...

**Comment by vcsjones** [comment]
Do you need actions enabled in your fork? They can be disabled / enabled under Settings, Actions. You can either disable all of them (as I have) or allowlist the ones you find useful.

Perhaps in the meantime the [prebuild workflow](https://github.com/dotnet/runtime/blob/main/.github/workflows/create-codespaces-prebuild.yml) can be updated to:

```yaml
if: "github.event.repository.name == 'dotnet/runtime'"
```

(Untested, but illustrates the idea). This would mean folks that _want_ the prebuild can't use it in their fork, but, since it is a private preview feature, I wager most folks won't have it.

**Comment by eerhardt** [comment]
I have sent this feedback to the Codespaces team. I'm waiting to hear their response on what the most appropriate resolution to this issue is.

**Comment by teo-tsirpanis** [comment]
Thanks for the tip @vcsjones, I had tried that before but couldn't find how to disable Actions. I turned them off now, don't actually need them.

**Comment by eerhardt** [comment]
I followed up with the Codespaces team. Here is their recommendation:

You will need to disable the Actions workflow on the forked repository. You can do this with the following steps:

1. On the fork of the repository, go to the Actions tab.
2. Select your prebuilds workflow (`Create Codespaces Prebuild`) and click on the overflow button "[...]" on the right.
3. You should see a "Disable workflow" button. Click it to disable the workflow on the fork repo, so it will no longer run there. 

See image below of where to find the Disable workflow option.
![image](https://user-images.githubusercontent.com/8291187/141818637-5bbadc82-7722-478b-91fa-5d5d9a200598.png)

In the next few months with changes we are planning for the prebuilds feature, this behavior will change. Prebuilds will be disabled on forks of a prebuild-enabled repo and would need to be configured for the fork if desired.

**Comment by stephentoub** [comment]
Thanks.
