### ISSUE TITLE
We need a repo convention to ship source generators as part of the ref pack

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#61321]
I believe we want to ship the Regex source generator by default in .NET 7.0

I checked https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet7&package=Microsoft.NETCore.App.Ref&protocolType=NuGet&version=7.0.0-alpha.1.21558.2
And noticed that it wasn't present.

I believe because it is not built as part of the normal build that produces the refpack.  This is because there is no `AnalyzerReference` from the src project to the generator project and we have no convention to find and build generator projects as part of src.proj or ref.proj.

We should update the docs to indicate what steps are required (if any additional steps are necessary):
https://github.com/dotnet/runtime/blob/331823f4046da1530dd950ac3ad8a87b3cdd584d/docs/coding-guidelines/libraries-packaging.md#netcoreapp-shared-framework

Possible fixes here are:
1. Require some building src project add an `AnalyzerReference` to the shipping source generator.
2. Add some build convention to `src.proj` to build the generator.
3. Some other build convention, eg `generators.proj`.

@stephentoub @joperezr @eerhardt @safern

**Comment by ericstj** [comment]
cc @AaronRobinsonMSFT @elinor-fung in case they're also expecting the DllImport generator as well, since it's not currently in the ref pack.

**Comment by elinor-fung** [comment]
Thanks @ericstj.
Yeah, we will need to do something here as well when we get to productization (added an item to our team's tracking issue).

**Comment by joperezr** [comment]
Thanks for logging this. I'll follow your first suggestion so that we can get the source generator into the ref pack as soon as possible so we can start getting feedback on it from more people. I'll also log a separate infrastructure issue to talk about conventions, so that we can use that issue to update all of the existing generators once/if a convention is decided upon.

**Comment by kasperk81** [comment]
net6 comes with two generators, json and logging. not important for ref pack?

**Comment by ericstj** [comment]
Those are already in the ref-packs (JSON in the NetCore.App ref pack, Logging in ASP.NET).  This is about a new 7.0 generator that was not included correctly.

**Comment by ericstj** [comment]
Can this be closed now, @joperezr

**Comment by joperezr** [comment]
mm not really, if you see [this comment](https://github.com/dotnet/runtime/pull/61329#issuecomment-963741092) It was decided that this issue would track coming up with a better convention of how to automatically add source generators to the ref pack so that the issue we had in regex wouldn't happen again. I don't think we have done that just yet, we only fixed the individual regex case. We should probably rename this one to match what it is being tracked, or close this and open a new one that tracks specifically the convention work.

**Comment by safern** [comment]
I've renamed the issue (despite breaking email threads 😆) to reflect what we are tracking.
