### ISSUE TITLE
Algorithm `xml-exc-c14n` not implemented?

### ISSUE THREAD

**Issue by dmitriy-shleht** [dotnet/runtime#61361]
If I call this method `System.Security.Cryptography.CryptoConfig.CreateFromName("http://www.w3.org/2001/10/xml-exc-c14n#")`

**.net core 5** returns NULL
**.net framewirk 4.5** returns me an object `XMLDSIGEXCC14NTransform`

How to achieve the same behavior on .Net Core?

**Comment by bartonjs** [comment]
The use of `CryptoConfig` is generally discouraged.

In .NET Framework, SignedXml and friends are all part of the framework, and CryptoConfig was (more or less) invented to power SignedXml/EncryptedXml.

In .NET Core, (now just ".NET") all of the crypto XML has been removed from the framework, and it's available via a separate NuGet package.  Since it comes from a NuGet package, CryptoConfig can't reliably find it, so it doesn't even try.

If you really need it to work for some code you can't modify, then you can register it with `CryptoConfig.AddAlgorithm(typeof(XmlDsigExcC14NTransform), "http://www.w3.org/2001/10/xml-exc-c14n#");`

But much better would be to just use `new XmlDsigExcC14NTransform()`.

**Comment by vcsjones** [comment]
Interesting, I would expect this to work out of the box though...

https://github.com/dotnet/runtime/blob/985cb8329d76f3b8334999581bebde62c54270e0/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs#L15

**Comment by bartonjs** [comment]
> I would expect this to work out of the box though...

SignedXml can find it automatically, yes, since it has that CryptoConfig fallback table.  The question seemed to me to be about calling CryptoConfig directly.

**Comment by vcsjones** [comment]
> SignedXml can find it automatically, yes, since it has that CryptoConfig fallback table. The question seemed to me to be about calling CryptoConfig directly.

Ah, I got it. I overlooked that the translation table above is specific to `SignedXml`.

**Comment by dmitriy-shleht** [comment]
> CryptoConfig.AddAlgorithm(typeof(XmlDsigExcC14NTransform), "http://www.w3.org/2001/10/xml-exc-c14n#");
It worked. Thanks!
