### ISSUE TITLE
[.NET 6] UriBuilder breaking change not documented

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#61363]
Consider the following code:
```csharp
Console.WriteLine(new UriBuilder("msg", "dummy", 0, "segment").Uri);
```

On .NET 5 the output is `msg://dummy/segment`. On .NET 6 the output is `msg://dummy:0/segment`. It is possible to change the port number to `-1` to get the same result. This is not listed in the [documented breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0). If it was intentional it should be added in there.

**Comment by karelz** [comment]
@MihaZupan any thoughts?

**Comment by MihaZupan** [comment]
Introduced by #40986 which was a bug fix for https://github.com/dotnet/runtime/issues/37865#issuecomment-644174433.
As documented by [UriBuilder.Port](https://docs.microsoft.com/dotnet/api/system.uribuilder.port#remarks), `-1` should be used to get the default port.

You were relying on an undocumented bug affecting unknown Uri schemes. For example if you use `http` instead of `msg`, you will see that the port is present in both 5.0 and 6.0.

The is not specific to `UriBuilder`, and we may choose to document it as a breaking change.

**Comment by karelz** [comment]
It seems to fall into the "technical breaking change" category -- it was misbehaving against docs and we fixed it.
Given that it is fairly corner case, I would recommend to close the issue until we see at least couple of more customers hitting it. If more folks hit it, we should document it as breaking change. Otherwise this issue + docs may be sufficient IMO.

**Comment by filipnavara** [comment]
Thanks for the analysis! I expected that the change was intentional but it was a bit tricky to find what what going on (the bug didn't manifest anywhere close to the `UriBuilder` usage). I filed a ticket because it was not listed in the breaking changes and I thought that people may run into it.

**Comment by karelz** [comment]
Triage: Closing as per above explantion - https://github.com/dotnet/runtime/issues/61363#issuecomment-964260277
We will document it if more customers hit it. Please reply here, or file new issue referencing this one if you are in that category.
