### ISSUE TITLE
Use of JsonSerializerContext Can Cause CS1591

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/runtime#61379]
### Description

Using `JsonSerializerContext` can cause a `CS1591` "Missing XML comment" error on the generated code.

```c#
[JsonSerializable(typeof(Foo[]))]
public partial class CustomJsonSerializerContext : JsonSerializerContext
{
}
```

You cannot suppress `CS1591` from a global suppressions file because this is a compiler error. Disabling CS1591 from an `.editorconfig` file still causes the error.

```
dotnet_diagnostic.CS1591.severity = none
```

You also cannot disable the warning in source because the source code is generated in a separate file. It looks like the generated source code needs to include some suppressions.

```c#
#pragma warning disable CS1591
[JsonSerializable(typeof(Foo[]))]
public partial class CustomJsonSerializerContext : JsonSerializerContext
{
}
#pragma warning enable CS1591
```

The only workaround seems to be to globally disable this warning in the project `.csproj` file, which is not great since I would like to keep this warning.

```xml
<PropertyGroup>
    <NoWarn>CS1591</NoWarn>
</PropertyGroup>
```

### Configuration

.NET SDK 6.0.100

### Other information

See also:

- https://github.com/dotnet/roslyn/issues/12702

**Comment by RehanSaeed** [comment]
> 
> 
> Would marking your class `internal` work around the issue?

Thats another great workaround.

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/roslyn/issues/54119

**Comment by layomia** [comment]
Marking as 7.0 since the workaround here seems acceptable.

**Comment by JuanZamudioGBM** [comment]
If I make the class internal and I making a library, how my clients can invoke the serialization with JsonSerializerContext? Do I have to expose a Serialize method for all my classes?

**Comment by Youssef1313** [comment]
The generated file doesn't have to have a documentation comment. You can add the documentation on the partial that's not generated starting with https://github.com/dotnet/roslyn/pull/56419.

**Comment by Youssef1313** [comment]
My previous comment is misleading. I thought the diagnostic is issued for the partial `CustomJsonSerializerContext` type.

The issue is that generator can generate public members without doc comments. The generator should either add `#pragma warning disable`s or properly generate documentation comments.

**Comment by JakeYallop** [comment]
I'm running into this issue as well.

To allow users to provide their own documentation, would this not require (at least) something like [partial properties](https://github.com/dotnet/csharplang/discussions/3412) in order to work, or a fundamental re-design of the generator? At the moment, the way that code takes advantage of the library is via source-generated public properties.

Of the 2 options (either adding comments or adding `#pragma warning disable CS1591`) I would lean towards the latter for simplicity - but that reflects my experience in that I'm usually using the source generator in the context of ASP .NET Core so I don't directly use the properties on the JsonSerializerContext very often.

**Comment by JakeYallop** [comment]
What would an acceptable PR look like for this? Are we happy to go with `#pragma warning disable CS1591` at the top of each generated file?

**Comment by eiriktsarpalis** [comment]
After discussion with the @dotnet/area-system-text-json crew consensus seems to be that we would need to emit relevant XML docs for every generated member that is public.
