### ISSUE TITLE
TimeSeparator has changed from : to . for da-DK in .NET 5+

### ISSUE THREAD

**Issue by Henr1k80** [dotnet/runtime#61380]
### Description
The time separator has changed from : to . for da-DK in .NET 5 and 6

`System.Globalization.CultureInfo.GetCultureInfo("da-DK").DateTimeFormat.TimeSeparator`
is : for .NET Framework and .NET Core 3.1, as expected
https://dotnetfiddle.net/wPaJI1

it is . for .NET 5 & 6
https://dotnetfiddle.net/3fLj9J

**Comment by tarekgh** [comment]
In .NET 5.0 and 6.0 we have switched to use ICU library for the globalization support. Please review the [article](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) for more info. The article specifies a way to switch back to old behavior if needed. Please note we don't recommend that. The reason is ICU is picking the globalization data from the Unicode standard CLDR. This should be the correct behavior and there is a way to [file a ticket](https://cldr.unicode.org/index/bug-reports) to CLDR if you think this behavior is wrong.

Looking at [CLDR data for da cultures](https://github.com/unicode-org/cldr/blob/338a08a21925d129fa0ba3000aaf22efe6b81486/common/main/da.xml#L1464), it shows `.` is the correct time separator. 

I am closing this issue, feel free to respond back with any question or ask we can help with. Thanks for your report.

**Comment by Henr1k80** [comment]
Thank you @tarekgh 
If it is a bug in ICU, what is the workflow to fix .NET 5+ on Windows or Azure App Services?

1. Fix bug in ICU
2. Pull fix into MS ICU
3. Release Windows Update with MS ICU fix
4. Install Windows Update fix to update icu.dll
That could take ages, if it is correct?

Fixing it on linux is another workflow, I guess?
1. Fix bug in ICU
2. Update distro specific ICU package
3. Install updated package

**Comment by danmoseley** [comment]
Is another possibility to create a custom culture based on da-DK but with the other time separator, and use that? I have never done this.

**Comment by tarekgh** [comment]
@Henr1k80 I would suggest first to file the issue to CLDR to understand why they chose this time formats for `da`. It is possible this behavior is chosen intentionally and be the desired for such cultures.  

For working around the issue, you can do that in the code by creating `da-DK` culture and set the time separator property `CultureInfo.DateTimeFormat.TimeSeparator` to the desired value and overwrite any time formatting patterns too.

Also, you have the option to build your own copy of ICU with changing `da` culture time formats, it is not difficult to do so and use the [app-local](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu) feature.
