### ISSUE TITLE
ReadyToRun images crash if compiled for AVX2 but run on non-AVX2 CPU

### ISSUE THREAD

**Issue by rickbrew** [dotnet/runtime#61471]
_**Update:**_ Crash also happens if R2R image is built for SSE4.2 and run on CPU that only supports SSSE3 (I added a reply below)

### Description

I'm using `crossgen2` and .NET 6.0.0 GA with the following options to build a composite R2R image for my app (Paint.NET),

` --targetos:windows --targetarch:x64 --optimize-time --composite --inputbubble --compilebubblegenerics --instruction-set:avx2,bmi,bmi2,lzcnt,popcnt,fma`

From what I'm told, this image should still run fine on systems without support for these instruction sets, but the precompiled code will be ignored in favor of JITting. (or at least, any precompiled code which uses those instructions will be discarded -- still haven't heard conclusively if it's selective exclusion or if the whole native image is ignored)

However, I received a report from a private tester that the app just crashes. Their CPU is a Pentium(R) Dual-Core CPU T4400 which supports up through SSSE3.

If I use `bcdedit /set xsavedisable 1` on my own system, which is a Ryzen 5000 series CPU, I'm also able to reproduce the crash.

So it looks like ReadyToRun is doing something wrong here.

cc @tannergooding @EgorBo @AndyAyersMS 

### Reproduction Steps

Compile an app using crossgen2 and ` --targetos:windows --targetarch:x64 --optimize-time --composite --inputbubble --compilebubblegenerics --instruction-set:avx2,bmi,bmi2,lzcnt,popcnt,fma`

Run the app on an older CPU that lacks AVX2, or run `bcdedit /set xsavedisable 1` and reboot and run it on a CPU that is more recent.

### Expected behavior

Everything works fine

### Actual behavior

Crashes. Event Viewer has an entry for the app showing that it crashed.

### Regression?

Not sure if this is a regression.

### Known Workarounds

Compile with `--instruction-set:sse2` instead.

### Configuration

.NET 6.0.0
Windows 10/11
x64
CPU that lacks AVX2, or on one that does have AVX2 but first run `bcdedit /set xsavedisable 1` and reboot

**Comment by tannergooding** [comment]
CC. @davidwrighton 

My "best guess" here would be that there is a check somewhere that is only checking for `AVX/AVX2` and not also checking for the relevant `XSAVE` bits.

**Comment by tannergooding** [comment]
Possibly this check: https://github.com/dotnet/runtime/blob/948770a23b1e1b5d128d7bbc06f172fbd01d4ba5/src/coreclr/vm/cgensys.h#L113-L121 ?

**Comment by mangod9** [comment]
@dotnet/crossgen-contrib

**Comment by rickbrew** [comment]
I sent two more builds to my testers, one built for SSE4.2 and another just for SSE2.

On the Pentium T4400, which only supports SSSE3, only the SSE2 build worked. So, this goes further than just the AVX/AVX2 checks.

**Comment by mangod9** [comment]
Hi @rickbrew, could you please add a stack for the failures?

**Comment by MichalStrehovsky** [comment]
> ### Known Workarounds
> Compile with `--instruction-set:sse2` instead.

FWIW, you can drop `--instruction-set:sse2` - crossgen2 enables those by default because they're part of x64 and a baseline requirement on any of the supported OSes on x86:

https://github.com/dotnet/runtime/blob/775873f58510e50d7b4582c2728831311c7ea956/src/coreclr/tools/aot/crossgen2/Program.cs#L227-L232

**Comment by rickbrew** [comment]
> Hi @rickbrew, could you please add a stack for the failures?

How do I get a stack? App just dies, doesn't even display. Emits entry into the Event Log pointing at ntdll.dll

**Comment by mangod9** [comment]
run the test from within a debugger possibly?

**Comment by tannergooding** [comment]
Just copying the relevant message here as well: https://github.com/dotnet/runtime/pull/61474#issuecomment-966609022

> My tester confirmed that the SSE4.2 build does not work on the SSSE3 system. The SSE2 build is fine.

Given that SSE4.2 also has problems when run on a system without SSE4.2 support; this indicates a potentially deeper issue in the crossgen logic.

**Comment by rickbrew** [comment]
I'm hoping this can be fixed for .NET 7.0? If this isn't fixed, I'll have to choose between composite+SSE2, or non-composite + AVX2, and I'd really like to build with composite+AVX2.

**Comment by davidwrighton** [comment]
@rickbrew, sorry for the delay on this. I'm currently about to take a closer look and make sure this works correctly. The current expectation is that the `--instruction-set` argument to crossgen2 should make an image where all of the compiled code will be dropped if the application is run on a machine which does not support the specified instruction set. The end result will be significantly degraded startup time on machines without the specific instruction sets. Due to engineering concerns in the current implementation of the JIT/crossgen2 compiler, we're not currently able to enable AVX (or SSE4.2) support selectively on a subset of methods compiled into the application.

**Comment by rickbrew** [comment]
@davidwrighton Okay so the expectation w/ the current implementation is that it should throw away _all_ the AVX2 compiled code on a non-AVX2 supporting CPU. I was expecting it to only throw away compiled code that used instructions that couldn't be executed (e.g. AVX2 code on SSEx CPU), as that's what I've always heard and been told about this feature. If that's the case, then the only way I can get good startup performance on pre-AVX2 CPUs is to crossgen with e.g. `--instruction-set:sse2`. Is that right?

**Comment by davidwrighton** [comment]
@rickbrew Correct, the problem is that when AVX is enabled for use, the JIT will actually use AVX instructions for quite a few operations. For instance, the AVX instruction set adds access to more slightly more efficient instructions for performing regular floating point math, as well as if a function has any more than a very small number of locals, AVX instructions are used to zero out the locals of the method. The end result, is that without a significant engineering effort we're not able to produce a particularly useful mode in crossgen2 where only the appropriate subset of the functions would be disabled when AVX is not present at runtime. As such, the design was to disable codegen entirely from the module, as it would be much much simpler to implement. Unfortunately, even that is quite problematic to test, and we mishandled the composite mode case, leading to this bug.

In theory if you are truly seeing very significant wins from architecture specific compilation, it would be possible to build both dlls, and then write your own host, and choose exactly which set of compiled code to run at runtime, but that is so much work. I cannot recommend it. My recommendation would be to compile with the default instruction-set switch, and let the runtime default behavior of tiered compilation recompile as needed, or wait for us to fix this bug, compile assuming AVX2, produce an Arm64 build for customers running on Arm64 hardware, and accept the terrible startup performance on older X86 hardware. (Current Arm64 emulators do not support AVX, so you would likely want to avoid causing perf problems on newer Arm64 hardware). The realization of how complex all of this is, has led to us deprioritizing some of our efforts around higher order instruction set handling for CoreCLR in desktop application scenarios, in favor of exploring usage for the server container space, where developers can have extremely high confidence on what sort of hardware is in use, and that hardware pretty much all supports AVX.

**Comment by davidwrighton** [comment]
@rickbrew Well, the story is a bit more complex than that...

- The `--instruction-set` switch puts a baseline for the set of instruction sets that are expected to be present at runtime. What it do if the runtime environment doesn't have the instruction set is to reject all of the methods within the module.
- There is a curated list of instruction sets, which we've determined that today's implementation of the JIT will allow us to enable methods on a piecemeal basis. I believe this list includes SSE4.1, but it does not include at the moment. SSE4.2. This list is hardcoded into crossgen2, and not exposed via a command line. In principle, we could have a different curated list of instruction sets when the baseline instruction set is at least avx2, but the existing situation is complicated enough. This curated list is probably what @tannergooding is referring to.
- The story on Arm64 is simpler, as fewer of the instruction sets stack, and or replace the older instruction sets; however, when we eventually implement sve (or more likely sve2) complexity will arrive on the Arm64 platform.
