### ISSUE TITLE
[Mono] TE plaintext and json benchmarks regression

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#61484]
A recent change has caused regression for TE plaintext and json benchmarks running on Mono. The PR which caused this regression is https://github.com/dotnet/runtime/pull/53450

<img width="917" alt="Screen Shot 2021-11-11 at 5 44 10 PM" src="https://user-images.githubusercontent.com/52458914/141379670-b3e70f39-4bfd-454c-b186-a46de0039f85.png">

cc: @imhameed

**Comment by tannergooding** [comment]
@fanyang-mono, could you provide guidance on how to get the disassembly for Mono on these benchmarks, etc?

**Comment by tannergooding** [comment]
For what it's worth, this looks like a Mono bug and something its not handling correctly.
CoreCLR didn't regress and in fact looks like it has slightly better latency.

![image](https://user-images.githubusercontent.com/10487869/141385578-d157a21c-34f7-4406-9dae-b2cd78e569bf.png)

Given there were only two very minor mono file changes here: https://github.com/dotnet/runtime/pull/53450/files#diff-ce66e94ce2cdb8e54003a124a4057ce5d5dc5325ad32c9601a4662f8fa39367a

My guess is that Mono isn't handling some pattern or API which is getting handled by CoreCLR.

**Comment by fanyang-mono** [comment]
Could be. I will obtain the trace before and after the regression to see what changed for Mono.

**Comment by sebastienros** [comment]
@tannergooding  the drop in the charts happens when we switched from net6.0 to net7.0 so it could have been from any commits for about 1-2 months of changes on main while we were still benchmarking net6.0. So the improvements you are mentioning are for this 1-2 months period too, not specifically this change. @fanyang-mono identified the specific mono regression to two consecutive builds by running benchmarks manually on previous builds. It's possible that it also impacts the coreclr benchmarks, but other improvements in net7.0 have still a positive impact (ThreadPool improvements for instance).

@fanyang-mono can you share the runtime versions you used, and maybe do a run on coreclr for the same benchmarks between these two versions?

**Comment by tannergooding** [comment]
> It's possible that it also impacts the coreclr benchmarks, but other improvements in net7.0 still have a positive impact (ThreadPool improvements for instance).

@sebastienros, that's certainly possible, but I also think its somewhat unlikely. We have the `dotnet/performance` repo and run daily per commit benchmarks with semi-weekly triage to identify regressions and improvements.

**Comment by naricc** [comment]
It looks like we are also seeing this regression in Microbenchmarks: https://github.com/dotnet/perf-autofiling-issues/issues/2173 (that is a link to the automated issue). I don't think it makes sense for me to create another one, but using the microbenchmarks might be easier for validation of a fix.

**Comment by fanyang-mono** [comment]
> @fanyang-mono can you share the runtime versions you used, and maybe do a run on coreclr for the same benchmarks between these two versions?

Runtime packages of this regression:
7.0.0-alpha.1.21480.11 -> good
7.0.0-alpha.1.21480.12 --> regression

**Comment by fanyang-mono** [comment]
> It looks like we are also seeing this regression in Microbenchmarks: [dotnet/perf-autofiling-issues#2173](https://github.com/dotnet/perf-autofiling-issues/issues/2173) (that is a link to the automated issue). I don't think it makes sense for me to create another one, but using the microbenchmarks might be easier for validation of a fix.

Among all the regressions filed for the above issue, these microbenchmarks showed regression exactly on Sept 30th.

https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_08_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_Regression/System.Text.Json.Tests.Perf_Reader.html

https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_08_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_Regression/System.Memory.Span(Char).html

**Comment by tannergooding** [comment]
Just noting a related PR went in: <https://github.com/dotnet/runtime/pull/60094>

It would be interesting to see if Mono likewise sees a regression or any change here, particularly since these ones are showing 57% and 75% improvements in our perf triage from today: <https://github.com/dotnet/perf-autofiling-issues/issues/2339> and <https://github.com/dotnet/perf-autofiling-issues/issues/2346>

**Comment by fanyang-mono** [comment]
The solution of this regression is tracked by #64072

**Comment by SamMonoRT** [comment]
@fanyang-mono : assigning to you for tracking

**Comment by fanyang-mono** [comment]
Closing this issue as the planned work has finished.
