### ISSUE TITLE
WriteEventCore with DateTime has changed behavior in .Net 6.0

### ISSUE THREAD

**Issue by andrew-hampton** [dotnet/runtime#61563]
### Description

When updating to .NET 6.0, we encountered issues with DateTimes within events containing an incorrect year. It appears that the optimization in pull request #52092 changed the behavior so that it's no longer decoded from a FileTime and is instead decoded using the full tick value.

### Reproduction Steps

Write an event using WriteEventCore like the example below

```
            [Event(1)]
            public unsafe void DateTimeEvent(DateTime dateTime)
            {
                if (this.IsEnabled())
                {
                    var fileTimeVal = dateTime.Year < 1601 ? 0 : dateTime.ToFileTimeUtc();
                    EventSource.EventData* descrs = stackalloc EventSource.EventData[1];
                    descrs[0].DataPointer = (IntPtr)(&fileTimeVal);
                    descrs[0].Size = sizeof(long);
                    WriteEventCore(1, 1, descrs);
                }
            }
```

### Expected behavior

EventWrittenEventArgs payload from an EventTraceListener contains the DateTime matching the input.

### Actual behavior

EventWrittenEventArgs payload from an EventTraceListener contains the DateTime, but the year is off by 1600 as it appears to be decoding from ticks rather than file time ticks.

### Other information

This appears to be a breaking change from NetCore3.1 and Net 5.0 so seeking guidance on whether this is an expected change in behavior or if this is a bug. Thanks!

**Comment by andrew-hampton** [comment]
Area should be "area-System.Diagnostics.Tracing"

**Comment by MihaZupan** [comment]
This was an unintended behavioral change from #52092

**Comment by tarekgh** [comment]
CC @sywhang @noahfalk

**Comment by MJSanfelippo** [comment]
Hi, any updates on this?

**Comment by tommcdon** [comment]
@MJSanfelippo this issue is currently on our backlog and we have not yet had time to investigate.  Is this workaround sufficient or is this a higher priority issue?

A couple of quick questions:

1. The WriteEventCore repro seems to be writing a long (8 bytes) to the event pipe stream.  Are the 8 bytes being truncated or shifted?
2. As mentioned above no datetime is being written to EventPipe.   The datetime is being converted to a long using dateTime.ToFileTimeUtc().  Is the problem with the conversion to file offsets?  If so, this sounds like a bug in DateTime and not in EventPipe.

**Comment by MihaZupan** [comment]
@tommcdon it is a bug introduced by #52092 in .NET 6.0, but only affects in-process `EventListener`s.

The difference is in how the serialized value (`long`) is de-serialized by `DecodeObjects`:
- In 5.0, the `DateTime` would be [converted from a `long` back to a `DateTime` via `DateTime.FromFileTimeUtc`](https://github.com/dotnet/runtime/blob/2705fc02018f16cef2e99101cf8a58e16d26b692/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1832-L1836)
- In 6.0, the value is [interpreted as a `DateTime` directly](https://github.com/dotnet/runtime/blob/6dd808ff7ae62512330d2f111eb1f60f1ae40125/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1840-L1843) (i.e. exact number of ticks)

Sadly this was not caught by tests since none of them uses `DateTime` with `WriteEventCore` - we are only testing the `varargs` overload.

The fix here would be to change
https://github.com/dotnet/runtime/blob/a25aa6641b605f1ad28c75cddcfa204f8153abe3/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1844
to
```c#
decoded = DateTime.FromFileTimeUtc(*(long*)dataPointer);
```

**Comment by andrew-hampton** [comment]
The workaround I proposed also only works for local listeners. If you're sending events to another process, in my experience they're still expecting them to be FileTime ticks. This creates a scenario where you want to keep the same write event behavior as pre-6.0, but then you have to jump through extra hoops to get the correct value if using a local trace listener.

**Comment by MJSanfelippo** [comment]
I updated ours to be ToBinary() for now, but I'd like to keep them the way they were.

**Comment by Samirat** [comment]
@MihaZupan Yeah, I agree, it's not really a workaround, as far as I can tell, it results in a completely different telemetry contract. It only fixes things to jive between the .NET EventSource publishing libraries and listening libraries, but most people are sending telemetry somewhere else, and we're now sending a completely different timescale.

**Comment by MihaZupan** [comment]
Note that the serialized value of a `DateTime` has not changed.
The only thing that changed is how the in-process `EventListener` decodes this value.

External telemetry systems should not be impacted (unless they are being fed by data coming from `EventListener`).

**Comment by Samirat** [comment]
Thanks, @MihaZupan , I was afraid the other WriteEvent overloads would be impacted, but if they have the same contract, we can just fix the EventListener usages.

**Comment by andrew-hampton** [comment]
I've updated my original post to remove the known workaround since it's unlikely to result in the correct behavior in most cases. The workaround was that if you're only using a local listener then you can get the same behavior by updating to to use `dateTime.ToBinary()` instead of `dateTime.ToFileTimeUtc()` however this is unlikely to work when sending telemetry to external systems.
