### ISSUE TITLE
[wasm][debugger] Handle exceptions while evaluating expressions

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#61665]
Look at @radical comments in this PR https://github.com/dotnet/runtime/pull/61470 and fix it.

**Comment by ilonatommy** [comment]
Bringing user's exceptions to the UI (e.g. by displaying them in Value field on frame evaluation in Watch) works fine and is tested in DebuggerTests.EvaluateOnCallFrameTests.EvaluatePropertyThatThrows().

For internal errors of evaluation exception flow is not working properly:
- in VS instead of our exception some VS one is thrown:
Exception of type 'Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.ProtocolException' was thrown. (Unable to evaluate)
- in Browser user sees no exception.
