### ISSUE TITLE
System.Reflection.GetCustomAttribute(Type) returns null on .Net5 

### ISSUE THREAD

**Issue by mgabbay** [dotnet/runtime#61661]
### Description

I have a code that loads an assembly and using custom attributes to categorize data.

I'm trying to get the actual CustomAttribute object for some interfaces which have the requested Attribute.
on net framework48, the code returns the Attribute value as expected.
during migration to .Net5 -  Running the code on .Net5 returns null.
I tried few overloads with no luck.

### Reproduction Steps

A custom attribute:
    
    [AttributeUsage(AttributeTargets.Interface)]
    public class ApiInterfaceDescriptorAttribute : Attribute
    {
        public string ApiUsageName { get; }

        public ApiInterfaceDescriptorAttribute(string apiUsageName)
        {
            ApiUsageName = apiUsageName;
        }
    }

Sample interface:

    [ApiInterfaceDescriptor("powercontrol")]
    public interface IMyInterface 
    {
       [ApiMethodDescriptor(ApiExposureLevel.Basic, "a-method...")]
        void SomeMethod();
    }

usage:

    public void GetApi()
    {
       var assembly = Assembly.LoadFile("MyFile");
       var myInterface = assembly.DefinedTypes.FirstOrDefault(...) // get the interface
       var att = myInterface.GetCustomAttribute(typeof(ApiInterfaceDescriptorAttribute));// returns null on Net5 and value on net48
       var att = myInterface.GetCustomAttribute<ApiInterfaceDescriptorAttribute>();// returns null on Net5
    }

### Expected behavior

return the requested attribute

### Actual behavior

method returns null

### Known Workarounds

Read the CustomAtrributes object[] and itterate and query the requested attribute

### Configuration

Running on Win10 x64, .Net5

**Comment by Tornhoof** [comment]
You're manually loading your dll, where is the attribute defined?

**Comment by mgabbay** [comment]
Hi @Tornhoof 

I Tried alos using
    Assembly.GetAssembly(typeof(IMyInterface ));

The attribute is in the same project as the interface but with other namespace
the interface namespace is at 'MyProject'
the attribute namespace is at MyProject.Attributes

**Comment by vitek-karas** [comment]
I think this is because your `MyAssembly.dll` is loaded twice. You can check this by calling:
```C#
var defaultALC = AssemblyLoadContext.GetLoadContext(typeof(IMyInterface).Assembly);
var fileALC = AssemblyLoadContext.GetLoadContext(myInterface.Assembly);
```

I would expect the two variables to be different (even simple `ToString` should show a difference).

The root cause is the call to `Assembly.LoadFile`. This method always loads the specified assembly into its own `AssemblyLoadContext`. (More about [assembly load context](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext)).

This means that you have the assembly loaded into the `LoadFile` load context (one copy) and then I assume you also have a direct reference to it from your main code, which will load it into the default load context (second copy). While the assembly file is exactly the same, for the runtime these two copies are distinct assemblies and all types from the two will be treated as different types.

So the call `myInterface.GetCustomAttribute<ApiInterfaceDescriptorAttribute>()` is looking for the attribute type from the default load context, but it's doing so on the interface from the `LoadFile` load context, which has the attribute type from `LoadFile` load context. And so it returns null - nothing found. If you were to look at all the attribute on the type, you would see the attribute you're looking for by name.

It's hard to say what you're trying to implement, so I don't know what solution to recommend. If it's anything like a plugin scenario, you might want to look at this guide/sample: https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

**Comment by mgabbay** [comment]
Hi @vitek-karas
Thanks for the explanation, I understand now what makes the strange behavior.
in my code I changed the usage of accessing the assembly and I see that the API is working as expected.

Many thanks!
issue resolved
