### ISSUE TITLE
JSON serializer source generator produces warnings for types with nullable generic parameters

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#61734]
### Description

When the model type has a constructor with a generic type that has a nullable type argument, that nullability is not reproduced in the source-generated code for the JSON serializer and produces a nullability warning

### Reproduction Steps

In a `net6.0` `classlib` project:

```cs
using System.Text.Json.Serialization;

namespace JsonSerializerNullability;

public class Model
{
    public Model(Dictionary<string, object?> property) => Property = property;
    public Dictionary<string, object?> Property { get; }
}

[JsonSerializable(typeof(Model))]
internal partial class MyJsonSerializerContext : JsonSerializerContext
{ }
```

### Expected behavior

No warnings should be produced

### Actual behavior

```
Warning	CS8620	Argument of type 'Dictionary<string, object>' cannot be used for parameter 'property' of type 'Dictionary<string, object?>' in 'Model.Model(Dictionary<string, object?> property)' due to differences in the nullability of reference types.	JsonSerializerNullability	…\MyJsonSerializerContext.Model.g.cs	25	Active
```

### Configuration

`net6.0` on version 6.0.0

**Comment by eiriktsarpalis** [comment]
Related to #59464. When working on a fix I thought I had added tests for nullable generic parameters

https://github.com/dotnet/runtime/blob/2b23bfa5d60b185641a513a38a05d63f68e82503/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/RealWorldContextTests.cs#L796-L798

However it turns out this was never really being tested, since our test projects have their `Nullable` property set to `annotations`. We should service this.

**Comment by eiriktsarpalis** [comment]
Let's keep these open, given that suppressing warnings is not fundamentally addressing the issue.

**Comment by eiriktsarpalis** [comment]
Addressed in https://github.com/dotnet/runtime/pull/86334.
