### ISSUE TITLE
HttpClient with proxy throws when BadGateway

### ISSUE THREAD

**Issue by Shlyonov** [dotnet/runtime#61835]
### Description

HttpClient has started throw HttpRequestException  when using proxy and response is 502 BadGateway. Previously with .net 5 it ends request gracefully and retuns result with StatusCode == HttpStatusCode.BadGateway, but now throws HttpRequestException.

### Reproduction Steps

```
            var proxy = new WebProxy
            {
                Address = new Uri($"http://127.0.0.1:{port}"),
                BypassProxyOnLocal = false,
                UseDefaultCredentials = false
            };

            var httpHandler = new SocketsHttpHandler
            {
                Proxy = proxy,
            };

            var httpClient = new HttpClient(httpHandler);

            var result = await httpClient.GetAsync("Url with 502 response");
```

### Expected behavior

Gracefully return result with 

` result.StatusCode == HttpStatusCode.BadGateway`

### Actual behavior

Throws exception:

```
            try
            {
                var result = await httpClient.GetAsync(address);               
            }
            catch (HttpRequestException hre) when (hre.HResult == -2146233088)
            {
                // exception here
            }
```

### Regression?

Works fine with .net 5

### Configuration

.net 6, Windows 10

**Comment by geoffkizer** [comment]
I assume the actual URI you are trying to connect to is an https URI. Is that correct?

This is an intentional change in behavior. Specifically, when you try to retrieve an https URI through a proxy, we need to establish a tunnel through the proxy using the CONNECT method. If this CONNECT request fails, then we will now throw in .NET 6.

Previously, we would simply return the 502 status code from the CONNECT request. The problem with this is that the user could not distinguish whether this 502 was from the CONNECT itself or from the actual HTTP request after the CONNECT succeeded and a tunnel was established.

Effectively, this case isn't really any different than any other failure to create a connection -- failures here cause us to throw. If you want to handle it, you need a try/catch for the exception.

**Comment by Shlyonov** [comment]
> I assume the actual URI you are trying to connect to is an https URI. Is that correct?

Yes it's correct. My initial question was about https request using proxy. 
Thanks for reply, I guess I have got your point. Using https connection we have to send CONNECT to proxy server and if connection OK proxy should return 200 Connection Established, if not we assume that problem with proxy. Using http we can't determine who actually produced the response, proxy server or target server.
