### ISSUE TITLE
JsonElement does not respect JsonSerializerOptions

### ISSUE THREAD

**Issue by iinuwa** [dotnet/runtime#61843]
### Description

While trying to serialize a `JsonElement` with Pascal case properties to camel case, I expected that I could just set the `JsonSerializerOptions.PropertyNamingPolicy` to `JsonNamingPolicy.CamelCase` and be done. However, according to my tests and the [source code](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/JsonElementConverter.cs), the `JsonCoverter` for that type just writes out the raw JSON it parsed, without transforming property names.

### Reproduction Steps

```csharp
using System.Text;
using System.Text.Json;

var json = @"{""ShouldWindUpAsCamelCase"":""does it?""}";
var reader = new Utf8JsonReader(Encoding.UTF8.GetBytes(json));
var element = JsonElement.ParseValue(ref reader);
var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
var serialized = JsonSerializer.Serialize(element, options);
Console.WriteLine(serialized);
// returns {"ShouldWindUpAsCamelCase":"does it?"} instead of {"shouldWindUpAsCamelCase":"does it?"}
```

### Expected behavior

JsonElement serialization should respect JsonSerializerOptions, or at least, the PropertyNamingPolicy option.

### Actual behavior

The serialized JsonElement just returns the case of the original JSON, ignoring all JsonSerializationOptions.

### Regression?

No, I don't think this was available in previous releases.

### Configuration

Version: .NET 6.0, though this code was introduced in .NET 5.0.

**Comment by eiriktsarpalis** [comment]
This is by design -- the `JsonDocument` and `JsonElement` converters implement serialization using the [`WriteTo`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument.writeto?view=net-6.0) method. This reflects the design of `JsonDocument`: it's a read-only wrapper around a JSON encoded buffer focusing on performance. It does validate that the encoding is valid JSON but will otherwise copy the contents essentially verbatim.

Starting with .NET 6 my recommendation is to use [`JsonNode`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode?view=net-6.0) instead: it's a read-writer JSON DOM representation that offers some degree customizing serialization.
