### ISSUE TITLE
Blazor WebAssembly crashes on mobile devices with low RAM

### ISSUE THREAD

**Issue by martinmogusu** [dotnet/runtime#61925]
### Describe the bug
Blazor WebAssembly apps crash on devices with low RAM

### To Reproduce
I have created a minimal example at https://github.com/martinmogusu/CrashTest
The code is from the default WebAssembly template `dotnet new blazorwasm`

I have also hosted the site on Azure Static Web Apps here: https://icy-sky-0892af903.azurestaticapps.net/

If you load the site on a device with 1GB RAM, the app crashes. On the UI you see "An unhandled error has occurred"
On the browser console logs you find this error:

```
Uncaught (in promise) TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read

TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
window.Module.s.printErr @ blazor.webassembly.js:1
```

I was able to view the console logs by using Kiwi Browser for android, which has devtools.
The same site works okay on devices with higher RAM.

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual studio 2022
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by frieddumplings** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/12145555/143024229-26081cf4-7fe6-49ab-b6af-c57cc5fa477a.jpg)

Possibly related, this was also in the debug window when the above errors showed up in the console:
https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html
https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

**Comment by ldsenow** [comment]
I am not sure mine have the same root cause as yours. I ran a memory profile on chrome desktop version with .net 6 wasm published to IIS. The barebone template project is using 540mb memory compare to .net 5's 40mb. It is unacceptably high memory usage on a almost blank project. It is causing the whole application crashes after a few operations. I hope someone can take this seriously. It is NOT a small issue. 

Please refer to the issue below. The issue is not reported by me but I have the same symptom and I uploaded a few screenshots.

https://github.com/dotnet/runtime/issues/62054

**Comment by s21-himesh** [comment]
Is there any update on this issue. We have run into the same thing. Looks like it's not going to be fixed in .net 7 and pushed out to .net 8. Has anyone got any workarounds for this? At the moment there looks like no other solution but to pull back to .net 5.

MS guys on ticket, this is hardly a small issue is it. There are many devices with low ram

**Comment by Pethical** [comment]
Hi folks,
We ran into this issue, a Samsung Galaxy A52 is not enough to run a webassembly app. We are using .net 6.
Why the milestone is .NET 8? This is a serious bug, blazor is unusable on a normal consumer mobile devices, and opened a year ago.
Isn't NET 6 the current LTS stable release?
Really need to rollback to the unsupported net 5 to get work blazor on consumer mobile phones?

**Comment by dbridgman** [comment]
Hi all

I wanted to chime into this issue more, because I believe it's much more serious than MS believe it to be. Other people in this thread have been using relatively low-end phones, but I've tested this across a variety of devices, not just low end but iPhone 11, and some flagship samsung phones that're a bit older. I believe the threshold is devices 4gb and below.

I've taken an empty blazor WASM project and deployed it to azure, nothing fancy, no additions, no nothing, just a plain Blazor WASM app. 

The initial load is absolutely shocking, hitting a second by second usage of 1.91GB of ram. It absolutely should not be hogging this amount of memory.

![initial load](https://user-images.githubusercontent.com/5011609/196376938-1fe4b63a-03bc-4b38-9cdb-afb795cae375.png)

From this point on you can force an exception simply by refreshing the page, where you can see the max usage hits 3.26gb of RAM. Which again is madness for just an empty app.

![max memory load after refresh](https://user-images.githubusercontent.com/5011609/196377651-584ff19a-c1f5-459a-8f95-b4dd2a5235b4.png)

When hitting this amount it hits an exception:

![deployed-site-exceptiob](https://user-images.githubusercontent.com/5011609/196378693-aa8759d9-c223-4a68-85b9-7806cdcce879.jpg)

Now I get the iphone 11 is hardly a new phone being released in 2019, but reality is, this is this is reflective of most people walking around with a mobile device today. 

This needs a fix, at the moment I'd actively discourage anyone that's developing for mobile users to avoid using Blazor WASM until it's fixed.

**Comment by ldsenow** [comment]
Not supprised by this if your using net 6 blazor wasm. A few issues have been reported around memory leaks and crashes. Barely have any of them been fixed. We have to use.net 5 which is at least not broken. It has been like this for a year and not sure this will be resolved in.net 7 or not.

**Comment by pmedina61920** [comment]
I had the same problem, I fixed it by removing all **OnAfterRenderAsync** methods, I don't know the root cause but it worked for me.

**Comment by mtranchi** [comment]
I'm having the same issue. No way can I use Blazor 6 or 7 until this is fixed. This is a _**major**_ issue.

**Comment by simpsoc** [comment]
I am having the same issue.  To say that this is major is an understatement....

**Comment by pavelsavara** [comment]
I will spend some time next year on looking on this, but for now some hints:
1) Browsers can't do streaming wasm instantiation when content type HTTP header is wrong. That consumes more memory. See also https://github.com/dotnet/aspnetcore/issues/42055
2) you could use `<EmccTotalMemory>xxx</EmccTotalMemory>` in your .csproj file together with `<WasmBuildNative>true</WasmBuildNative>` or with AOT. Where xxx is memory size which still works for your app.

Remember that memory requirements of your app is not all we need here. We also expand IL->IR for interpreted methods. And the browser JIT will have to compile all the code too, consuming CPU and memory.

Perhaps for low powered mobile devices, consider server side rendering, where possible.
Maybe we should define some minimal spec on which WASM is supported.

**Comment by Pethical** [comment]
The headers are ok in my application. I have a Samsung Galaxy Note 10+ phone and the application can't load because this problem. If this is a low powered phone, then please tell me what is a high end device. And what can I define as minimum spec? A phone with 64Gb ram and 32 arm cores? 😅
Basically, net 5 is working like a charm, so I downgraded my apps. This is a security flaw and can cause problems, but no other way exists. The net 5 is the Windows XP today. We can't upgrade. 😂

**Comment by pavelsavara** [comment]
Did `EmccTotalMemory` help?

**Comment by simpsoc** [comment]
@pavelsavara 

> 2. you could use `<EmccTotalMemory>xxx</EmccTotalMemory>` in your .csproj file together with `<WasmBuildNative>true</WasmBuildNative>` or with AOT. Where xxx is memory size which still works for your app.

This helped in my case.  I've gone from seeing 3.5-4gb of memory consumed within a few actions to under 1gb.

Thank you

**Comment by boukenka** [comment]
@simpsoc Which value did you define for xxx? 
```C# 
<EmccTotalMemory>xxx</EmccTotalMemory>
```

**Comment by simpsoc** [comment]
> @simpsoc Which value did you define for xxx?
> 
> ```cs
> <EmccTotalMemory>xxx</EmccTotalMemory>
> ```

@boukenka

I set it to 16777216.

I had seen another[ post](https://github.com/dotnet/aspnetcore/issues/40548) that was mostly msft engineers discussing the issue earlier in the year.  I think I initially found it by searching my specific error message.  This was a value that someone mentioned fixing the issue in their testing.  The discussion seemed to mostly focus around implementing the ability to make the change vs the change already being something that could be made.  I did some googling around <EmccTotalMemory> and webassembly, blazor, wasm keywords but the only results I found were for emscripten, which is a 3rd party webassembly compiler that is used for building the webassembly.  Without any results or documentation focusing around blazor i didn't realize it was a configurable parameter.  @pavelsavara suggesting changing that value in csproj and adding the native build flag is as close to any instructions or documentation as I've seen for this.  His suggestion triggered my memory to go back and look at that thread for the value they'd used.

**Comment by pavelsavara** [comment]
Searching for `Module["INITIAL_MEMORY"]` in the final `dotnet.js` gives me following answers for vanilla Blazor template
- net6, release, no AOT, no relink: 16777216
- net7, release, no AOT, no relink: 16777216
- net8, release, no AOT, no relink: 536870912
- net6, release, relink: 536870912
- net7, release, relink: 536870912
- net8, release, relink: 536870912

It is set here 
https://github.com/dotnet/runtime/blob/70aadafa7e103821563c5247e90cafb6a138ad32/src/mono/wasm/build/WasmApp.Native.targets#L190-L191
and applies for customers anytime they do relink (even without AOT) for example via `<WasmBuildNative>true</WasmBuildNative>`

by passing `--initial-memory=536870912` to emcc

this is probably the PR which introduced it https://github.com/dotnet/runtime/pull/52941 which is Net6 timeframe

I was not able to replicate the issue with the repro repo without relink.

**Comment by pavelsavara** [comment]
questions: @radical @lewing @maraf @kg 
- what should be the default value for no-relink (no workload)
- what should be the default value for relink 
- what should be the default value for AOT
    - I suspect we increased it for some reasons with AOT builds and re-link is just side effect ?
    - **why did we go for such large value ?**
- Should we create patch for net7 ?
- Should we create patch for net6 ?

**Comment by pavelsavara** [comment]
Fixed by https://github.com/dotnet/runtime/pull/80849
