### ISSUE TITLE
Number of jit tests failing with `needLabel` assert

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#61939]
Saw this first [when testing OSR](https://github.com/dotnet/runtime/pull/61851#issuecomment-974674782) but it seems to be more widespread.

Eg from libraries-pgo run: https://dev.azure.com/dnceng/public/_build/results?buildId=1480057&view=ms.vss-test-web.build-test-results-tab
```
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 27 [0x0000001b], Thread: 33 [0x0021]): Assertion failed 'needLabel' in '<>c__DisplayClass207_0:<TryGenerateSimplifiedGo>g__EmitSingleCharAtomicLoop|22(System.Text.RegularExpressions.RegexNode):this' during 'Generate code' (IL size 1706)

    File: /__w/1/s/src/coreclr/jit/codegenlinear.cpp Line: 348
    Image: /root/helix/work/correlation/dotnet
```

Underlying issue is that we end up deciding to put align padding before an unreachable block, and then assert that that block does not have a label.

cc @kunalspathak @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
This is mostly causing because we sometimes can have back to back jumps as part of same IG. We might have an `align` instruction after the first `jmp` and then expect the next instruction (in this case a `jmp`) has its own label. https://github.com/dotnet/runtime/pull/62025 will fix this and some other loop alignment related issues.

```asm
       E97AFFFFFF           jmp      G_M22669_IG12
       E9A0060000           jmp      G_M22669_IG78
```
