### ISSUE TITLE
System.Text.Json to deserialize non-string

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#62078]
### Description

It is really annoying when things getting easier and simpler with C# and .NET but when it comes to migrating from JSON.NET to System.Text.Json it's getting more coding

With JSON.NET we don't have to worry about the data type coming from the REST as JSON.NET will take care of it and all that we have to do is:

```
public bool is_active { get; set; }
public int? priority { get; set; }
public DateTime queued_at { get; set; }
public string remarks { get; set; }

```

but now we have to consider all as string and then use a custom converter.

and the problem comes when the data is not a string such as true and false. Please refer to [Resolution 2](https://www.thecodebuzz.com/json-value-could-not-be-converted-to-system-string/)

### Reproduction Steps

Explained above.

### Expected behavior

System.Text.Json should be able to deserialize non-string like this:

```
public bool is_active { get; set; }
public int? priority { get; set; }
public DateTime queued_at { get; set; }
public string remarks { get; set; }

```

### Actual behavior

The JSON value could not be converted to System.Boolean. Path: $.notifications[16].is_active | LineNumber: 0 | BytePositionInLine: 40495.

**Comment by eiriktsarpalis** [comment]
Hi @jrahma, the link you shared concerns deserializing numbers and booleans as strings. Your sample class and error message seems to suggest you're looking to achieve the opposite, presumably converting strings to booleans. 

System.Text.Json is strict in its handling of read JSON types, by design. In the case of numbers it can be configured to support string values using the [`JsonNumberHandling.AllowReadingFromString`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonnumberhandling?view=net-6.0) enum. For booleans though you would still need to specify a custom converter.
