### ISSUE TITLE
Can we reopen the discussion about JsonIgnoreCondition for Deserialization?

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/runtime#62086]
With .NET 6 the property ``JsonSerializerOptions.IgnoreNullValues`` is now visibly obsolete, in .NET 5 the obsoletion attribute was not added (or removed afaik).
In one of my apps I actually now run into the problem of missing this for deserialization.
Scenario:
Let's assume you have a lot of DTOs with lists and since Enumerables shouldn't return null, but instead something empty, those DTOs all look like this:
```csharp
public class TestDto
{
	public List<string> Values { get; set; } = new List<string>();
}
```
In .NET 5 the behavior with ``IgnoreNullValues`` enabled  was that the a json like the following:
```json
{
	"Values": null
}
```
kept the list intact.
With .NET 6 and the obsoleted property  set to false (to remove the obsoletion message) it gets set to ``null``.
So either all the DTOs get changed to be ``List<string>?`` or I keep the obsoleted property (and postpone the problem until it's actually removed from the System.Text.Json source).
As (atleast in my case) a null value for the list is rather rare, it's usually either an array or the property not in the json, I'm leaning very much towards the case of just hiding the obsoletion message via:
```csharp
#pragma warning disable CS0618
#pragma warning disable SYSLIB0020 // Type or member is obsolete
				IgnoreNullValues = true
#pragma warning restore SYSLIB0020 // Type or member is obsolete
#pragma warning restore CS0618
```
Because the effort to change the code, where I would need to check for null then, is very much higher than just postponing the problem to a later version of .NET (one central JsonSerializerOptions vs. a high two digit number of properties)

Still this means, that I need to handle this sooner or later (e.g. .NET 7 at the earliest, that's why I want to reopen the discussion).
This is not yet an API proposal, it's just to figure out if it is even worth talking about it or if I should simply start adding ``?`` to my list/array etc. properties everywhere.

@layomia maybe you have input here what the right direction is.

**Comment by filipnavara** [comment]
Doesn't `JsonSerializeOptions.DefaultIgnoreCondition = JsonIgnoreCondition.Always` do the same thing? (Just asking, I honestly don't know the answer)

**Comment by Tornhoof** [comment]
That enum value should always ignore a property, at ``DefaultIgnoreCondition`` it throws, as it would mean that nothing will ever serialized/deserialized.

https://github.com/dotnet/runtime/blob/4723f00978e213dfd0904323a4ce9adf0744c8e7/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L300-L303

**Comment by layomia** [comment]
There are no plans to remove the obsolete `IgnoreNullValues` property from `JsonSerializerOptions`, as it is recognized that some users might have established a dependency on its behavior, as demonstrated here. When designing the `JsonIgnoreCondition` enum and functionality, we decided not to carry over the behavior of ignoring nulls on deserialization (see https://github.com/dotnet/runtime/issues/35649#issuecomment-625284674), as we couldn't land on a compelling enough reason to ignore null tokens received from the wire.

Given this scenario, I see no reason to not keep using the `IgnoreNullValues` since it contains functionality that works well for your application & you're okay with suppressing the obsoletion warning.

**Comment by olena-stoliarova** [comment]
I had this issue in my code, too after transition to .NET 6. It took some time and effort to figure out the cause. Such behavior was not described as a breaking change in the documentation.

The advice to replace IgnoreNullValues with JsonIgnoreCondition.WhenWritingNull from Microsoft official documentation is misleading because the behavior is not the same. It's a pity that I had to discover this myself and not from the docs!

Putting pragmas all over the project makes the code look ugly and raises a lot of concerns on code review.

I hope, this will be amended somehow for the future releases.

**Comment by semuserable** [comment]
We've also run into this problem. We migrated to .NET 6 and replaced `JsonSerializerOptions.IgnoreNullValues = true` with `JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull`, but we broke our deserialization. It was not an expected behaviour. 

Example is almost the same as @Tornhoof described

```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

var ignoreNullValues = new JsonSerializerOptions { IgnoreNullValues = true };
Console.WriteLine(JsonSerializer.Deserialize<Person>(@"{ ""Friends"": null }", ignoreNullValues)!.Friends is null); // false
Console.WriteLine(JsonSerializer.Deserialize<Person>(@"{ }", ignoreNullValues)!.Friends is null);                           // false

var whenWritingNull = new JsonSerializerOptions { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };
Console.WriteLine(JsonSerializer.Deserialize<Person>(@"{ ""Friends"": null }", whenWritingNull)!.Friends is null); // true -> not expected
Console.WriteLine(JsonSerializer.Deserialize<Person>(@"{ }", whenWritingNull)!.Friends is null);                           // false

class Person
{
    public List<string> Friends { get; set; } = new();
}
```

I would prefer to not use `pragma disable`, as it looks "hacky". Can the `ObsoleteAttribute` be removed from `IgnoreNullValues` property?

Thanks!

**Comment by PHermanov** [comment]
Facing the same issue after moving to .NET 6, deserialization is broken.
