### ISSUE TITLE
ConcurrentStack.PushRange(T[]) throws an ArgumentOutOfRangeException on empty T[]

### ISSUE THREAD

**Issue by megazyz** [dotnet/runtime#62121]
### Description

`ConcurrentStack<T>.PushRange(T[])` throws an ArgumentOutOfRangeException when `T[]` is an empty array. The exception message is 'The startIndex argument must be greater than or equal to zero.'.

- This behavior is not documented
- It should do nothing instead of throwing an exception, like `List<T>.AddRange(IEnumerable<T>)` does

### Reproduction Steps

`new ConcurrentStack<int>().PushRange(Array.Empty<int>());`

### Expected behavior

It should not throw an exception.

### Actual behavior

It throws an ArgumentOutOfRangeException: 'The startIndex argument must be greater than or equal to zero.'

### Known Workarounds

Check the array for `Length > 0` before calling `ConcurrentStack<T>.PushRange(T[])`.

### Configuration

.NET 6.0.100

**Comment by martincostello** [comment]
Looks like the argument validation happens before the zero length special case:

https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L346-L350

which throws because `startIndex` and `items.Length` are equal:

https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L412-L416

**Comment by martincostello** [comment]
Proposed fix: #62126
