### ISSUE TITLE
[mono] call GC.Collect(); block the main thread won't resume

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#62128]
### Description

i am embedding the monovm with ue.
i call GC.Collection will block the main thread.

### Reproduction Steps

our code is simple:
```
// call from native use mono_runtime_invoke
public void Unload(IPlugin plugin)
{
    plugin.Clear();  // do some clear work
    GC.Collect();
    plugin.Unload();
}
```
this is the thread call stack:

![image](https://user-images.githubusercontent.com/5187024/143863181-1c3d0c81-7be0-46fe-a189-c5b293a8798b.png)

### Expected behavior

no block

### Actual behavior

work correctly

### Configuration

build latest release/6.0
windows x64

**Comment by gfoidl** [comment]
>  i call GC.Collection will block the main thread.

It's documentated that way, to do a _blocking collection_. Do you aim for a _background collection_? If so see docs on how to call the method to perform a background GC.

**Comment by srxqds** [comment]
> ou aim for a _backgroun_

no, it is always block, not resume.

**Comment by gfoidl** [comment]
> and the monovm support background gc?

Let's have a look into the [docs for `GC.Collect`](http://docs.go-mono.com/?link=M%3aSystem.GC.Collect(System.Int32%2cSystem.GCCollectionMode%2cSystem.Boolean)) 😉

**Comment by srxqds** [comment]
ok, thanks, but it is not resumed after gc?

**Comment by srxqds** [comment]
and other thread call stack:

![image](https://user-images.githubusercontent.com/5187024/143868221-c621ddfd-47a2-45dd-b7fc-1cf0ef2af4e7.png)

**Comment by srxqds** [comment]
@lateralusX @lambdageek @vargaz  I am sorry for always ping you, can you help me figure out why made this block?

**Comment by vargaz** [comment]
The GC needs to wait for all the threads in the app to suspend, which doesn't happen here for some reason. Maybe there is a thread registered with the runtime which is blocking in some way.
Also note that the mono GC is conservative, which means that calling GC.Collect () is not guaranteed to collect all dead objects, so it might not achieve what you want it to achieve.

**Comment by srxqds** [comment]
> Also note that the mono GC is conservative, which means that calling GC.Collect () is not guaranteed to collect all dead objects, so it might not achieve what you want it to achieve.

ok, but in what situation dead objects will not collect immediately?

**Comment by lambdageek** [comment]
@srxqds There's probably a deadlock with some other thread.  hmm.. `wait_for_attach` requires GC Safe mode, but I'm not sure that `debugger_thread` is in GC Safe mode - I think it starts in GC Unsafe mode.

What is probably happening is because it's in GC Unsafe mode (ie cooperative suspension mode), the main collector thread is probably waiting for it to suspend.

You can try setting the environment variable `MONO_SLEEP_ABORT_LIMIT` to some number like 2000 (2 seconds). It will try to suspend the threads and if it doesn't work in 2 seconds, it will cause the app to abort and dump the thread states to stdout.

**Comment by srxqds** [comment]
> @srxqds There's probably a deadlock with some other thread. hmm.. `wait_for_attach` requires GC Safe mode, but I'm not sure that `debugger_thread` is in GC Safe mode - I think it starts in GC Unsafe mode.
> 
> What is probably happening is because it's in GC Unsafe mode (ie cooperative suspension mode), the main collector thread is probably waiting for it to suspend.
> 
> You can try setting the environment variable `MONO_SLEEP_ABORT_LIMIT` to some number like 2000 (2 seconds). It will try to suspend the threads and if it doesn't work in 2 seconds, it will cause the app to abort and dump the thread states to stdout.

I use `--debugger-agent=transport=dt_socket,embedding=1,suspend=n,server=y,address=127.0.0.1:9000` deubg options

**Comment by srxqds** [comment]
hi, I think the bug is the debug thread forget to set flags to `MONO_THREAD_INFO_FLAGS_NO_GC|MONO_THREAD_INFO_FLAGS_NO_SAMPLE` :
https://github.com/dotnet/runtime/blob/4da6b9a8d55913c0ea560d63590d35dc942425be/src/mono/mono/component/debugger-agent.c#L1497-L1509

**Comment by lateralusX** [comment]
Debugger thread needs to be a GC thread since it calls runtime methods as well as handles managed objects. Issue is what Aleksey points out, since you run with suspend=n, debugger thread will not block startup, but it waits in a code path that requires GC safe, it has several MONO_REQ_GC_SAFE_MODE on its path, so would have asserted on checked build.

debugger_thread starts in GC unsafe mode, but looking at functions already called by debugger_thread, like transport_recv, they include switch to GC safe, so fix is probably to make sure wait_for_attach also switch to GC safe and its only called by debugger_thread, so should not affect any other code paths.

**Comment by srxqds** [comment]
ok, thank you, I will modify the pr later

**Comment by srxqds** [comment]
ok, thank you, I will try to modify the pr later.

**Comment by srxqds** [comment]
> Debugger thread needs to be a GC thread since it calls runtime methods as well as handles managed objects. Issue is what Aleksey points out, since you run with suspend=n, debugger thread will not block startup, but it waits in a code path that requires GC safe, it has several `MONO_REQ_GC_SAFE_MODE `on its path, so would have asserted on checked build.
> 
> `debugger_thread `starts in GC unsafe mode, but looking at functions already called by `debugger_thread`, like `transport_recv`, they include switch to GC safe, so fix is probably to make sure `wait_for_attach `also switch to GC safe around its `socket_transport_accept `call and that function is only called by `debugger_thread`, so should not affect any other code paths.

but what is the right config for embedding debugger, can set suspend=n and not block startup?

**Comment by lateralusX** [comment]
If you don't want to attach debugger on runtime init (block startup) you use suspend=n, that will open up ability to attach debugger at a later point in time.

**Comment by srxqds** [comment]
I have modified the pr: https://github.com/dotnet/runtime/pull/62175
