### ISSUE TITLE
Document and/or change the relation between PGO and AggressiveOptimization

### ISSUE THREAD

**Issue by azhmur** [dotnet/runtime#62148]
Currently MSDN and header file states that meaning of MethodImplOption.AggressiveOptimization is "The method contains a hot path and should be optimized."

But it has some unexpected consequence with PGO: https://github.com/dotnet/runtime/pull/57327#discussion_r688903969

Some PR had already merged that removing usages of AggressiveOptimization:
https://github.com/dotnet/runtime/pull/58209
https://github.com/dotnet/runtime/pull/58253

But there are still plenty of them in dotnet/runtime.

I suppose there is space for few improvements:
1) Clarify documentation on the relation between AggressiveOptimization and PGO.
2) If PGO is enabled, than ignore AggressiveOptimization.
3) Remove usages AggressiveOptimization in dotnet/runtime.
4) Deprecate and ignore AggressiveOptimization completly.

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib @AndyAyersMS

**Comment by EgorBo** [comment]
In order to remove `AggressiveOptimization` usages in dotnet/runtime we need two things:
1) Enable OSR by default
2) Enable more optimizations in Tier0, especially those which can reduce allocations
but most likely some places will still need it.

I agree that docs should mention all the pitfalls.

**Comment by AndyAyersMS** [comment]
`AggressiveOptimization` provides a way to bypass tiering for certain methods that should never be left un-optimized. Since PGO relies on tiering, `AggressiveOptimization` and PGO are mutually exclusive.

I agree the name, while accurate, is a bit unfortunate -- the implications of using this on a method are not clear, and there are downsides.

Last I looked `AggressiveOptimization` was only used on a handful of key methods in the runtime. Looks like per [this comment](https://github.com/dotnet/runtime/pull/58209#issuecomment-907608496) there are more and we should indeed review them.

**Comment by AndyAyersMS** [comment]
@azhmur take a look at the proposed doc change and let me know what you think.

**Comment by azhmur** [comment]
Thank you. It looks great.

**Comment by AndyAyersMS** [comment]
Closed via https://github.com/dotnet/dotnet-api-docs/pull/8024.
