### ISSUE TITLE
Running android tests fails with xharness output "Unknown arguments: Debug"

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#62161]
Using the [current instructions](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing-android.md) I have recently been unable to run Android tests locally.

Here is what I am running:

```
./dotnet.sh build /t:Test src/libraries/System.Security.Cryptography/tests /p:TargetOS=Android /p:TargetArchitecture=x86
```

Doing so gives me:

>  XHarness command issued: android test --instrumentation=net.dot.MonoRunner --package-name=net.dot.System.Security.Cryptography.Tests --app=/code/personal/dotnet/runtime-main/artifacts/bin/System.Security.Cryptography.Tests/net7.0-Android-Debug/android-x86/AppBundle/bin/System.Security.Cryptography.Tests.apk --output-directory=/code/personal/dotnet/runtime-main/artifacts/bin/System.Security.Cryptography.Tests/net7.0-Android-Debug/android-x86/AppBundle/xharness-output --timeout=1800 Debug
  fail: Unknown arguments: Debug
  XHarness exit code: 3 (INVALID_ARGUMENTS)

If I get rid of the `$ADDITIONAL_ARGS` here:

https://github.com/dotnet/runtime/blob/d7f3f5861714568c8efb01c7337a5a6f565e2d1d/eng/testing/AndroidRunnerTemplate.sh#L43-L44

Then I can actually run the tests.

This used to work without me needing to modify `AndroidRunnerTemplate.sh`. Am I doing something wrong, or do the instructions need to be updated?

**Comment by steveisok** [comment]
I believe this is the problem... 

https://github.com/dotnet/runtime/blob/e43688a3fe6957f669ac10bc5413e285773732c3/eng/testing/tests.mobile.targets#L39

@mdh1418 can you take a look and provide a fix?

**Comment by mdh1418** [comment]
Yeah, the problem is that xharness doesn't expect an argument of just `Debug`. Locally I just bypassed it with conditioning it for not Android, but I'm wondering if it should just be removed overall. I'm not sure why this was introduced in the first place, and looking through the available arguments, it doesnt seem to match any? https://github.com/dotnet/xharness/tree/2863beb74c1abad7ddfe9ef7afea6fc2605e8a03/src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Arguments

I'll put up a PR now
