### ISSUE TITLE
Somebody please add support for BigInteger in Parallel.For

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62176]
Parallel.For ( 0,cycles,(i)=>{})
where cycles, i, is System.Numeric.BigInteger
I have algorithm that runs for a very long cycle that over floats even int64, it doesn't matter if I will finish it, but it does matter that I can represent it in the loop, I can use ordinary for, but parallel for gives me more performance

**Comment by Clockwork-Muse** [comment]
Tail calling is an optimization for recursion, not for general loops, and isn't parallelizable at all.

Back of the envelope calculation:  Assuming incrementing takes one cycle, `(2 ^ 63) / (3.5 * (10 ^ 12)) / 60 / 60 /24 = ~30.5 days` to cover the range of a `long`.  `Parallel.For`, because of the overhead, is best used when you have a _significant_ amount of work per cycle, which means your application runtime could reasonably be estimated to take a year or more.  
Practically speaking, with runtimes that long, you will **need** to have recovery scenarios for when the application goes down.  There are additional concerns with making sure you can run for anything close to that time.

Are you **sure** you actually have that many tasks?

**Comment by stephentoub** [comment]
https://www.hanselman.com/blog/back-to-parallel-basics-do-you-really-want-to-do-that-or-why-doesnt-the-new-parallelfor-support-biginteger

**Comment by jeffhandley** [comment]
Closing per the dialogue captured on @shanselman's blog:

> It’s achievable with Parallel.ForEach and either iterators or a custom Partitioner<T>.  For example, with iterators, you can write a handy method:

> ```C#
> static IEnumerable<BigInteger> Range(BigInteger fromInclusive, BigInteger toExclusive)
> {
>  
>     for(BigIntegeri=fromInclusive; i<toExclusive; i++) yield return i;
> }
> ```
> What? After telling me it's not desirable and I don't really want to do it, he actually DOES it. That's hot.
and then consume it in a method like:
> 
> ```c#
> public static void ParallelFor(BigInteger fromInclusive, BigInteger toExclusive, Action<BigInteger> body)
> {
>     Parallel.ForEach(Range(fromInclusive,toExclusive), body);
> }
> ```
> Which you can then use like:
> 
> ```c#
> ParallelFor(new BigInteger(from), new BigInteger(to), i=>
> {
>     // ... loop body here ...
> });
> ```
