### ISSUE TITLE
Example when use XmlDsigXPathTransform  alway validate fail

### ISSUE THREAD

**Issue by studentc0612l** [dotnet/runtime#62206]
hi team!
When I run example from URL https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.xmldsigxpathtransform?view=dotnet-plat-ext-6.0
Console window always print result when check valid xml signed: "The XML signature is not valid". what happened with xmldsigxpathtransform implement?.
Thanks

**Comment by krwq** [comment]
Seems like it was never ported from full framework. The code can be found here: https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/transform.cs,661

I'll leave to @bartonjs to consider if it's worth to bring it back or not

**Comment by bartonjs** [comment]
The xpath transform was removed from the safe transforms list in .NET Framework (you have to turn it back on via the Windows registry).  Since we don't have something analogous to the registry for Linux or macOS we don't have a way to opt this transform on or off for .NET Standard / .NET Core / .NET 5+... which means we decided to just leave the type out entirely.

Unfortunately, it is not possible to verify a signature that makes use of the xpath transform with the xmldsig implementation in .NET Core / .NET 5+.  After evaluating the security risks of allowing that transform you might want to look for another implementation of that specification.
