### ISSUE TITLE
Switch statement doesn't think int.maxvalue is constant

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62226]
### Description

![image](https://user-images.githubusercontent.com/35312807/144170235-9db46f7d-a5b0-4b87-85a6-6ca34a13a58f.png)

### Reproduction Steps

```
 BigInteger cycles = BigInteger.Pow(2, Dimension);
                    switch (cycles)
                    {
                        case < int.MaxValue:
                            //do something
                    }
```

### Expected behavior

case < int.MaxValue: shouldn't be an error when compiling

### Actual behavior

IDE highlights case < int.MaxValue:
compilation failed

**Comment by ryank425** [comment]
The constant in this error represents the 

`BigInteger cycles`

This is not constant. int.MaxValue is constant in this case, even though IDE is syntax error highlighting that specific value.
The reason it is not constant, is because

1. BigInteger is a struct https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger?view=net-6.0
2. "User-defined types, including classes, structs, and arrays, cannot be const. Use the readonly modifier to create a class, struct, or array that is initialized one time at run time (for example in a constructor) and thereafter cannot be changed." https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants

If you change the switch (cycles) to switch (some constant like int variable or int value like 5), it will go away.

**Comment by Xyncgas** [comment]
Yeah I gotta figure out another way to do it
