### ISSUE TITLE
Is issue with single instance of HttpClient and DNS changes still actual?

### ISSUE THREAD

**Issue by verdysh** [dotnet/runtime#62269]
Hey,

There was an issue #18348.
I tried reproduce it with next scenario. I run `.net core 3.1` console app with code:
```c#
var client = new HttpClient();
while (true)
{
	try
	{
		var result = await client.GetAsync("https://mysite.com");
		Console.WriteLine(result.StatusCode);
	}
	catch (Exception ex)
	{
		Console.WriteLine($"Exception {ex}");
	}

	Console.ReadLine();
}
```
Between loop iterations I was changing DNS server setting in my network connection: one DNS is absolutely working and the second give IP 127.0.01 for mysite.com.

In case when I set working DNS, I received status OK. In case with incorrect DNS server I received `HttpRequestException: No connection could be made because the target machine actively refused it.`.

For me it seems the issue I referred above is not actual already. Is it so? Or I reproduced not same scenario which mentioned in original issue?

**Comment by ManickaP** [comment]
https://github.com/dotnet/runtime/issues/18348#issuecomment-394396643 the comment is unfortunately drowned in all the other  discussion on the issue. Anyway, it has been fixed for quite some time, including .NET Core 3.1, the issue is closed.

However, by default, we do not recycle active connections, only idle ones after 2 minutes of inactivity. Which is what you're probably hitting in your example (seeing `Console.ReadLine();` there).

If you wish to recycle even active connections, you should set up https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime?view=net-6.0.

If this answers your question, please let me know, so I can close this issue.

**Comment by verdysh** [comment]
This is the answer! Thanks a lot!
