### ISSUE TITLE
[API Proposal]: Add JsonConverter with simple string to type serialization

### ISSUE THREAD

**Issue by tthiery** [dotnet/runtime#62406]
### Background and motivation

Sometimes whole types can be (de)serialized into a string representation. This is a common scenario and the .NET runtime already has a prime example of them: `UriJsonConverter`. While writing your own converter is not exactly hard (once you know the example of `UriJsonConverter`), it is creating bloat.

To simplify the setup, a simple parameterizable JsonConverter would be a nice idea.

### API Proposal

```C#
public class StringValueParserConverter<T> : JsonConverter<T>
{
    private readonly Func<string, T> _parser;
    private readonly Func<T, string> _serializer;

    public StringValueParserConverter(Func<string?, T> parser, Func<T, string> serializer)
    {
        _parser = parser;
        _serializer = serializer;
    }
    public override bool CanConvert(Type typeToConvert)
        => typeof(T) == typeToConvert;

    public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? stringValue = reader.GetString();

        var result = _parser(stringValue);

        return result;
    }

    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        var stringValue = _serializer(value);

        writer.WriteStringValue(stringValue);
    }
}
````

### API Usage

```C#
public record MyPath(string A, string B)
{
    public static MyPath Parse(string input) { ... }
    public override ToString() => $"{A} ./. {B}";
}
public record Test(string X, MyPath Y);

var data = new Test("x", new MyPath("a", "b"));

var options = new JsonSerializerOptions();
options.Converters.Add(new StringValueParserConverter<MyPath>(sv => MyPath.Parse(sv), p => p.ToString()));

var json = JsonSerializer.Serialize<Test>(data, options);

// json: { "X": "x", "Y": "a ./. b" }
```

### Alternative Designs

- Continue writing boiler plate instead of writing one-liner
- Could fall nicely into the category of using generic math interfaces for parsing and emiting.

### Risks

- More to maintain

**Comment by davidfowl** [comment]
This doesn't feel like it's saving much.

**Comment by tthiery** [comment]
Considering it as a new base type for the runtime own cases (uri, version, ...) but also usable externally :).

**Comment by eiriktsarpalis** [comment]
In .NET 6 we added the [`WriteAsPropertyName`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.writeaspropertyname?view=net-6.0)/[`ReadAsPropertyName`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.readaspropertyname?view=net-6.0) methods in `JsonConverter<T>`. These are specifically constrained to serializing and deserializing dictionary keys so they serve a slightly different purpose compared to your proposal. Note that these methods do not accept or return `string` since that typically entails an intermediate string allocation which we would prefer to avoid. This is why it is unlikely we would adopt such an intermediate converter type for `Uri` or `Version` converters. I would recommend authoring your own `StringValueParserConverter<T>` in your application if it makes your converter definitions more terse.

**Comment by tthiery** [comment]
I do not understand your feedback regards the WriteAsPropertyName.

**Comment by eiriktsarpalis** [comment]
I guess my point is that if you take a look at the method signatures for these methods they explicitly avoid taking or returning a string parameter. This is to avoid any intermediate string allocations that the baked in `Uri` and `Version` converters are careful to avoid.

**Comment by tthiery** [comment]
Well, that we could tweak in the proposal above.

But I think the overall interest is also not there. I tend to agree with David. And honestly once the polymorphic serialization is properly there, the big pain with serialization is gone and writing this converter project by project will be okay.

Thanks for your follow up. Very appreciated 👍
