### ISSUE TITLE
[API Proposal]: Add a SHA-256 Thumbprint convenience property to X509Certificate2

### ISSUE THREAD

**Issue by lawrencek76** [dotnet/runtime#62425]
### Background and motivation

For UI binding, and simple serialization I end up wrapping x509Certificate2 to add this property seems like it should be just built in and recommended over the sh1 version.

### API Proposal

```C#
namespace System.Security.Cryptography.X509Certificates
{
    public class X509Certificate2
    {
        //
        // Summary:
        //     Gets the sha-256 thumbprint of a certificate.
        //
        // Returns:
        //     The sha-256 hex string thumbprint of the certificate.
        public string Thumbprint256
    }
}
```

### API Usage

```C#
// Load a cert
var cert = new X509Certificate2(@"C:\github.cer");
// Getting the values out
Console.WriteLine(cert.Thumbprint256);
//  Prints for github's current cert 0AE384BFD4DDE9D13E50C5857C05A442C93F8E01445EE4B34540D22BD1E37F1B
```

### Alternative Designs

1. Name of the property could be simplified to Thumbprint2

**Comment by lawrencek76** [comment]
@vcsjones You are correct.

**Comment by GrabYourPitchforks** [comment]
We don't tend to add API on types for purely serialization & binding purposes unless those types are intended to be serialized / bound. Consider the flip side: if we were to add a property which returned the raw private key material, that could undermine the security of your application by disclosing sensitive data if you were to serialize all object properties into a single payload. It's useful to illustrate that adding convenience properties to encourage serialization ties our hands with respect to what functionality we can reasonably add in the future.

**Comment by lawrencek76** [comment]
I'll step back and explain a bit more.  
The existing Thumbprint is based on SHA1 and SHA1 is rapidly approaching the end of its useful life maybe exceeded it, that is all debatable.   In an abundance of caution, I no longer want to store or use sh1 hashes for uniquely identifying certificates so it would be very good to have the SHA2 as a property, to replace the SHA1.   

[NIST Guidance](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf)

Maybe this is just general use of the class but I see the thumbprint property ends up in logs and databases I think of that as the thumbprint being serialized to a database or log and then in a ui context I would previously bind or output that property to a ui element.   🤷

**Comment by bartonjs** [comment]
There's nothing wrong with displaying the SHA-1 thumbprint.  But that value shouldn't be used as the sole acceptance criteria for a certificate.

At this point, we believe the Thumbprint property was a mistake.  The cryptographic landscape moves forward, but the values returned from the property can't.  The methods GetCertHash and GetCertHashString take a parameter for what algorithm to use, which allows callers to move forward (or stay behind) at their own pace... and leave the algorithm identifier written down in their code where it can be easily audited.

`Thumbprint256` is a tad overreaching, since there are multiple 256-bit hash algorithms (admittedly, the only one currently in .NET is SHA-2-256, aka "SHA256").  Even if we named it ThumbprintSHA256 it'd still eventually end up on a banned API list, and we'd have to add yet another property.  Instead, we have the methods and their parameters.
