### ISSUE TITLE
Metadata for type 'CLASS' was not provided to the serializer, but it was.

### ISSUE THREAD

**Issue by MeepTech** [dotnet/runtime#62546]
### Description

I'm getting this exact Error:
```Metadata for type 'ActivityPub.Types.Link' was not provided to the serializer. The serializer method used does not support reflection-based creation of serialization-related type metadata. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.```

Despite having the JsonSerializeableAttribute on the type named in the error
My Code:
https://github.com/Meep-Tech/ActivityHub.Net/blob/collapse_links_during_serialization/Types/Link.cs#L22

The error occurs here:
https://github.com/Meep-Tech/ActivityHub.Net/blob/collapse_links_during_serialization/Utilities/DefaultConverterFactory.cs#L45

Which is a type I borrowed from this stackoverflow answer (the fiddle still seems to work too for net6): https://stackoverflow.com/a/65430421/5037067
This takes the base options, removed a custom Converter for the current type, and runs the default serialization given the class.
I need to do this because I have a type: Link, that sometimes needs to be serialized to just a pure string, and sometimes needs to be serialized to a full object.

This error either seems incorrect, or unhelpful for whatever is going on here. Any help would be greatly appreciated.

### Reproduction Steps

Donwloading the library, and using this code in a simple application:
```
static void Main(string[] args) {
      Settings.DefaultContext = new Link("ActivityPub.Net.Testing");

      var testObject = new Object {
        Type = "Test",
        At = new Link("/terry") {
          Rels = new string[] {
            "test",
            "test2"
          }
        },
        Attribution = "/meep",
        Audience = new Link("/all") {
          Rel = "test"
        }
      };

      string json = testObject
        .Serialize();

      System.IO.File.WriteAllLines(
        "test.json",
        new[] { json }
      );

      Object @object = json.DeSerializeEntity<Object>();
      System.IO.File.WriteAllLines(
        "test1.json",
        new[] { @object.ToString() }
      );
    }
```
    
Should throw the error.

### Expected behavior

The expected behavior is that the default write behavior occurs for the Link class, instead of throwing an exception.

### Actual behavior

This error is unexpected as I seem to have decorated the types properly with the attribute the error calls for. Currently this error is thrown when read or write is called on the modified options.

### Known Workarounds

This seems to work:
https://dotnetfiddle.net/TDXEZk

### Configuration

.net 6
Windows 10
x64
It shouldn't be
I am not

**Comment by pinkfloydx33** [comment]
You're applying the `JsonSerializableAttribute` to your `Link` type. I'm pretty sure you're supposed to specify it on your `JsonSerializerContext`. I'd have thought this would've produced a warning.

**Comment by MeepTech** [comment]
Strange, no warning. However I don't have a context type yet, and from what I can tell, source generation actually won't support my use case anyway because it's not comparable with init setters yet.

Is there any other way to just default serialization behavior as a fallback in system. Text. Json when using custom logic? I figure there's a way to add like, one field to a default serialization right?

**Comment by layomia** [comment]
> You're applying the JsonSerializableAttribute to your Link type. I'm pretty sure you're supposed to specify it on your JsonSerializerContext. I'd have thought this would've produced a warning.

This is the first time I've observed this usage mistake. We could consider a new diagnostic warning for this scenario based on how common this behavior turns out to be.

> I'm getting this exact Error:
Metadata for type 'ActivityPub.Types.Link' was not provided to the serializer. The serializer method used does not support reflection-based creation of serialization-related type metadata. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.


@MeepTech I'm curious how you encountered this error if you do not have context type yet. The pre-existing reflection-based `JsonSerializer` methods that accept `JsonSerializerOptions` instances do not yield this error. This means you'd have to be using a method that accepts a `JsonSerializerContext` or `JsonTypeInfo<T>` instance. Can you highlight where in your repro you are doing this?

> Is there any other way to just default serialization behavior as a fallback in system. Text. Json when using custom logic? I figure there's a way to add like, one field to a default serialization right?

> source generation actually won't support my use case anyway because it's not comparable with init setters yet.

I do not believe that there is a clean way to introduce a fallback (within the serializer itself) to reflection-based (de)serialization based on known unsupported features in source-gen. This is primarily because of the source-gen goal to enable application trimming where possible. A fallback feature would imply writing code in a way that would keep the reflection code around even for folks who do not need reflection and want reduced size.

The decision to use reflection, based on point-in-time functionality gaps, needs to be implemented by the user of the serializer, based on which class of serializer methods are called, i.e. those taking `JsonSerializerOptions` vs `JsonSerializerContext`/`JsonTypeInfo<T>`. Concretely, since deserialization of init-only properties is not supported in source-gen (fixing this is tracked by https://github.com/dotnet/runtime/issues/58770), then the reflection-based implementation should be used when such properties are present in the input object graph. Source-gen can be used in scenarios where it works well. See https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation-modes?pivots=dotnet-6-0.

**Comment by MeepTech** [comment]
> > I'm getting this exact Error:
> > Metadata for type 'ActivityPub.Types.Link' was not provided to the serializer. The serializer method used does not support reflection-based creation of serialization-related type metadata. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
> 
> @MeepTech I'm curious how you encountered this error if you do not have context type yet. The pre-existing reflection-based `JsonSerializer` methods that accept `JsonSerializerOptions` instances do not yield this error. This means you'd have to be using a method that accepts a `JsonSerializerContext` or `JsonTypeInfo<T>` instance. Can you highlight where in your repro you are doing this?
> 

Sure, [this ](https://github.com/Meep-Tech/ActivityHub.Net/blob/collapse_links_during_serialization/Utilities/DefaultConverterFactory.cs#L45)in my code is where the exception throws:
```
		public static void WriteOrSerialize<T>(this JsonConverter<T> converter, Utf8JsonWriter writer, T value, JsonSerializerOptions options) {
			if(converter != null)
>				converter.Write(writer, value, options);
			else
				JsonSerializer.Serialize(writer, value, options);
		}
```
`options` is a modified collection of options created [here](https://github.com/Meep-Tech/ActivityHub.Net/blob/collapse_links_during_serialization/Utilities/DefaultConverterFactory.cs#L14):
```
                       public DefaultConverter(JsonSerializerOptions options, DefaultConverterFactory<T> factory) {
				this.factory = factory;
>				this.modifiedOptions = options.CopyAndRemoveConverter(factory.GetType());
                                this.defaultConverter = (JsonConverter<T>)modifiedOptions.GetConverter(typeof(T));
		       }
```

This whole factory type is taken from here: https://stackoverflow.com/a/65430421/5037067

> I do not believe that there is a clean way to introduce a fallback (within the serializer itself) to reflection-based (de)serialization based on known unsupported features in source-gen. This is primarily because of the source-gen goal to enable application trimming where possible. A fallback feature would imply writing code in a way that would keep the reflection code around even for folks who do not need reflection and want reduced size.
> 
> The decision to use reflection, based on point-in-time functionality gaps, needs to be implemented by the user of the serializer, based on which class of serializer methods are called, i.e. those taking `JsonSerializerOptions` vs `JsonSerializerContext`/`JsonTypeInfo<T>`. Concretely, since deserialization of init-only properties is not supported in source-gen (fixing this is tracked by #58770), then the reflection-based implementation should be used when such properties are present in the input object graph. Source-gen can be used in scenarios where it works well. See https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation-modes?pivots=dotnet-6-0.

I was attempting to use reflection based/code first as much as possible based on annotations, but for some types could not find a way to do what I want with just that.

Do you know how I could acheive this type of serialization as well with just reflection logic?

**Comment by layomia** [comment]
@MeepTech I don't understand the issue. Can you please summarize it, along with a **minimal**, self-contained reproduction (e.g. a single project) that demonstrates the issue?

**Comment by MeepTech** [comment]
My issue ended up being solved here:
https://stackoverflow.com/a/70308500/5037067
