### ISSUE TITLE
String Formatting of f100 works differently in .NET 6

### ISSUE THREAD

**Issue by odhanson** [dotnet/runtime#62578]
### Description

The following code:
```c#
double val = 0;
Console.WriteLine($"{val.ToString("f100")}");
```
Produces both in FX and .NET 5, as output the value: f100
In .NET 6, it will produce the value: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Is this by design ? 
It will cause different behavior to our customers once they upgrade to new version of Excel.

### Reproduction Steps

Execute the following code in .NET 6:

```c#
double val = 0;
Console.WriteLine($"{val.ToString("f100")}");
```

### Expected behavior

Should output f100

### Actual behavior

Outputs 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

### Regression?

I believe this is a regression

**Comment by odhanson** [comment]
cc: @stephentoub , @danmoseley , @richlander

**Comment by SingleAccretion** [comment]
This was an intentional breaking change in .NET 6, see https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/numeric-format-parsing-handles-higher-precision.

Also cc @tannergooding.

**Comment by odhanson** [comment]
> This was an intentional breaking change in .NET 6, see https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/numeric-format-parsing-handles-higher-precision.
> 
> Also cc @tannergooding.

Thanks. Anyway perhaps to disable and force legacy behavior?
From a user point of view, this might be considered a regression.

**Comment by GrabYourPitchforks** [comment]
> Thanks. Anyway perhaps to disable and force legacy behavior? From a user point of view, this might be considered a regression.

There's not usually any way to globally disable these behaviors. .NET 5.0+ doesn't include many of the compat switches that .NET Framework had since .NET runtime installations are side-by-side and upgrades expected to be explicit gestures. Contrast this against .NET Framework, which was updated in-place on the machine.

There is a workaround listed on that breaking change page. Does that workaround suffice for your use cases? Are you able to detect instances where consumers wrote "f100" and rewrite the string on-the-fly to preserve compatible behavior?

**Comment by odhanson** [comment]
Thanks.
I guess we can make a change to make this backwards compatible as suggested in the doc.

Closing this issue
