### ISSUE TITLE
FileSystemEventArgs.FullPath does not return a fully qualified path

### ISSUE THREAD

**Issue by UnityAlex** [dotnet/runtime#62606]
### Description

As per the documentation https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemeventargs.fullpath?view=net-6.0 the `FullPath` property should return a fully qualified path. However it appears the constructor for `FileSystemEventArgs` assumes the directory passed in is fully qualified: https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemEventArgs.cs#L22

When used in conjunction with FileSystemWatcher it is possible for the path to be relative: https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs#L260

### Reproduction Steps

Repro code:
```
using System;
using System.IO;

namespace MyNamespace
{
    class Program
    {
        static void Main()
        {
            using var watcher = new FileSystemWatcher(@"bar");

            watcher.NotifyFilter = NotifyFilters.LastWrite;

            watcher.Changed += OnChanged;

            watcher.Filter = "*.txt";
            watcher.IncludeSubdirectories = false;
            watcher.EnableRaisingEvents = true;

            Console.WriteLine("Press enter to exit.");
            Console.ReadLine();
        }

        private static void OnChanged(object sender, FileSystemEventArgs e)
        {
            if (e.ChangeType != WatcherChangeTypes.Changed)
            {
                return;
            }
            Console.WriteLine($"Changed: {e.FullPath}");
        }
    }
}
```

1. I created the following dir structure on my machine:
`C:\foo\bar\footest.txt`

2. Set the working directory to be `C:\foo`
3. Run the program and then modify `footest.txt` to trigger a changed event.

### Expected behavior

Output should be:
`Changed: C:\foo\bar\footest.txt`

### Actual behavior

Current output:
`Changed: bar\footest.txt`

### Known Workarounds

Using `Path.GetFullPath` to fetch the fully qualified path
```
Console.WriteLine($"Changed: {Path.GetFullPath(e.FullPath)}");
```

### Configuration

.Net 6.0
Windows 10 x64
After looking at the source I believe that this is not unique to Windows

**Comment by adamsitnik** [comment]
cc @Jozkee

**Comment by Jozkee** [comment]
This would require a breaking change on `FileSystemEventArgs.FullPath` which I'm inclined to do given the name of the API.

cc @ericstj @jeffhandley

**Comment by slask** [comment]
Hi @Jozkee. Can I take this issue?

**Comment by Jozkee** [comment]
@slask Yes, let me assign you. Thanks!

**Comment by slask** [comment]
Linking docs issue https://github.com/dotnet/docs/issues/27916

**Comment by jeffhandley** [comment]
After fixing #68566 with #68582, which was addressing a regression caused by #63051, which fixed this issue, I've reconsidered this original issue further. I think we should revert both #68582 and #63051 and return `FileSystemEventArgs` and `RenamedEventArgs` back to their previous behavior and instead address this as a documentation issue.

The regression that was reported involved using an empty directory name, and it was relying on `FullPath` being relative to the process's directory. From that regression report, it's easy to imagine scenarios where the non-rooted path nature of `FullPath` is utilized and perhaps even leveraged to combine that full path to a different root. I remember such code I wrote myself back in .NET Framework days that would be broken by this change.

I'm going to submit a PR that reverts both #63051 and #68582, but leaves the additional tests in place, adapted to match the previous behavior.
