### ISSUE TITLE
JsonElement.TryGetDateTime throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by Lexeq** [dotnet/runtime#62720]
### Description

In some cases `JsonElement.TryGetDateTime` throws an exception. It happens when value is string containing two '>' and having length 2 or 3 (for example, ">>", ">> a", "> a>", etc.).

### Reproduction Steps

```cs
string json = JsonSerializer.Serialize(new { X = ">>a"});		
JsonDocument jsonDocument = JsonDocument.Parse(json);
jsonDocument.RootElement.GetProperty("X").TryGetDateTime(out var x); //IndexOutOfRangeException
```

### Expected behavior

return false from method

### Actual behavior

**IndexOutOfRangeException**
at System.Text.Json.JsonHelpers.TryParseDateTimeOffset(ReadOnlySpan`1 source, DateTimeParseData& parseData)
at System.Text.Json.JsonHelpers.TryParseAsISO(ReadOnlySpan`1 source, DateTime& value)
at System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime(ReadOnlySpan`1 source, DateTime& value)
at System.Text.Json.JsonDocument.TryGetValue(Int32 index, DateTime& value)
at System.Text.Json.JsonElement.TryGetDateTime(DateTime& value)

**Comment by layomia** [comment]
I was able to repro this. It's not regression from .NET 5.0.

The `IndexOutOfRangeException` doesn't occur when  the value is a single string token (as opposed to a nested object property), when parsing with both `JsonSerializer` and `JsonElement`. Needs further investigation and a bug fix for .NET 7.0. Please share if there are other test cases you find that lead to the error.

**Comment by henriblMSFT** [comment]
Here is another test case
```csharp
var jsonBytes = System.Text.Encoding.UTF8.GetBytes(@"""\u001c\u0001""");
var reader = new Utf8JsonReader(jsonBytes);
reader.Read();
reader.TryGetDateTime(out var datetime);
```
From my investigation the issue is that escaped string fool some of the string length validation in [TryGetDateTimeCore](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.TryGet.cs#L1075), but further down the `Unescape` call reduces the data length to less then 10 bytes.

This should happen regardless of if the value is in  `ValueSpan` or a `ValueSequence`
