### ISSUE TITLE
[Feature Request] cross-platform data protection

### ISSUE THREAD

**Issue by dtivel** [dotnet/runtime#62748]
NuGet enables credentials for authenticated package sources to be persisted in a NuGet.config file.  On Windows, NuGet client uses [`System.Security.Cryptography.ProtectedData`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?view=dotnet-plat-ext-6.0) to automatically encrypt and decrypt package source passwords using the caller's security context.  Because `ProtectedData` is only supported on Windows, only cleartext credentials are supported on Linux and macOS.

Context for this request is [NuGet/Home#1851](https://github.com/NuGet/Home/issues/1851). 

This request is for adding a new API for automatic encryption and decryption of data on all supported .NET platforms in the spirit of `ProtectedData`.  Although the Windows implementation for this new API may use `ProtectedData` under the covers, this request is not for modifying or extending the existing `ProtectedData`.

**Comment by GrabYourPitchforks** [comment]
Can you clarify your exact requirements? For example, `ProtectedData` makes an ironclad guarantee that you can never exfiltrate the key used to encrypt / decrypt data. (If this guarantee is broken, it would represent an EoP within the operating system itself, which the OS team would patch.) It also has the ability to encrypt to a session, a user, an entire machine, or even to a security group (using DPAPI-NG). Since this relies on core operating system functionality, this would be a nonstarter on non-Windows platforms. We cannot fake this level of security.

Do you need the passwords simply not to appear in plaintext in the file? Hardcoding a static key directly into the .NET runtime would satisfy this constraint, but that tactic would fail any realistic security review.

Who is the adversary in this scenario? (That is, why does the data need to be protected?) What capabilities are they assumed to have? If you start with that, then we can give a better description of what solutions may or may not be available on various platforms.

**Comment by GrabYourPitchforks** [comment]
For reference, the reason this is a Hard Problem™ is that everybody has different requirements. :(

In your case, if the requirement is to avoid accidental checkin of creds, it might be appropriate to say "just put the secret key into _/usr/foo/.keys/_." It is after all unlikely that the user will accidentally submit this folder.

Lots more scenarios (especially web servers) assume that the adversary has arbitrary file read. This means that they can read the locally deployed secrets file _and_ the secret file stashed away in a separate directory. So an API that stored the secret key in plaintext in a separate folder would not be appropriate for those scenarios. In ASP.NET's Data Protection API, they generally require the web server to point to an external place (like Azure Storage) to store key material, or the keys are protected using an X.509 cert which needs to be configured per-application.

For UI applications, using something like iOS's Keyring might be appropriate, but this might not work for applications which don't expect to show UI.

Hence the need to really dig in to the requirements and to see if it's possible to craft something that solves the majority of use cases. If we end up making a solution that's Nuget-specific, then that might end up belonging in the Nuget repo instead of the runtime repo.
