### ISSUE TITLE
CoreCLR breaks the ECMA spec (I.12.3.2.1) with ldsflda for custom types

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#62784]
### Description

As per ECMA spec:

> **I.12.3.2.1: The evaluation stack**
"Instructions that create pointers which are guaranteed not to point into the memory manager’s heaps (e.g., ldloca, ldarga, and **ldsflda**) produce transient pointers (type *) that can be used wherever a managed pointer (type &) or unmanaged pointer (type native unsigned int) is expected."

As far as I know (@SingleAccretion confirmed this), CoreCLR currently stores static fields of custom struct types into boxed objects, meaning they'll end up on the heap. This seems to directly go against the ECMA spec, which expects `ldsflda` to return a transient pointer that could then be used in place of a raw pointer just fine. The spec also implies that `ldsflda` in these cases would return a fixed address, which is not the case if CoreCLR instead returns a GC ref to a boxed object, which could be moved. I mean at the very least I would expect these objects to be pinned to ensure callers following the spec won't break, but this would still not adhere to the spec anyway as `ldsflda` specifically says it shouldn't return a ref to a location on a managed heap.

If the intention is to follow the ECMA spec, isn't this a bug that needs to be fixed?
If not, then shouldn't the spec be updated here? 🤔
Or, am I just reading this thing wrong? 😅

### Expected behavior

Static fields of a custom struct type (at the very least if `T` is unmanaged) should be pinned and not on the managed heap.
Not entirely sure whether this should apply to managed types too, but the spec seems to suggest it should?

### Actual behavior

Using `ldsflda` on static fields of custom struct types returns a GC ref to a boxed object, which is on the managed heap.
This goes against the ECMA spec bit mentioned above.

### Regression?

No, AFAIK this has always been the case on CoreCLR (and I would assume on NETFX too?).

**Comment by EgorBo** [comment]
I assume the idea for the following code:
![image](https://user-images.githubusercontent.com/523221/146036233-10b5c6ef-057b-41cb-9432-ef57692826ca.png)
to emit a single direct load inside `GetP1` with known address (targeting some unmanaged/Frozen Heap/POH memory)

**Comment by jkotas** [comment]
> CoreCLR currently stores static fields of custom struct types into boxed objects, meaning they'll end up on the heap.

It is not the only situation when CoreCLR stores static fields in on the managed heap. For example, object references are stored on managed heap or all statics of collectible types are stored on the managed heap as well. 

`ldsflda` returns the unmanaged pointer for RVA fields only. The documentation for `ldsflda` makes it clear: "The ldsflda instruction pushes the address (a managed pointer, type &, if field refers to a type
whose memory is managed; otherwise an unmanaged pointer, type native int) ...".

My guess is that these details were omitted from the text you have quoted for brevity. If you still think that clarification is needed, submit PR against https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md

**Comment by Sergio0694** [comment]
> "The documentation for ldsflda makes it clear: "The ldsflda instruction pushes the address (a managed pointer, type &, if field refers to a type whose memory is managed; **otherwise an unmanaged pointer, type native int**) ..."."

This is what confuses me though: doesn't CoreCLR currently still box static fields for custom struct types _even if_ they're unmanaged? In that case their location will be in the managed heap and they could get moved around if the GC compacts the heap, doesn't that strictly go against ECMA both in the section about transient pointers as well as this one for `ldsflda` you mentioned? That is, a user could read that bit of the ECMA, see they're using an unmanaged type, assume the runtime would return a raw pointer (which implies the backing store is fixed), use `Unsafe.AsPointer` on it, and then crashes could happen. It seems to me that either this is CoreCLR breaking the spec, or at the very least there's more than one place in ECMA that is out of date? I'm not sure I see how the spec is just shortened for brevity: unless I'm reading it wrong, some bits just seem to direclty contradict each other 🤔

Happy to make a PR to update ECMA if needed once everything's cleared up on here, sure thing! 🙂

**Comment by jkotas** [comment]
The intent of the ECMA spec has been:

If the static field has assigned RVA in metadata, `ldsflda` returns (unmanaged) pointer that does not move. It is not possible to create regular statics like this in C#.

Otherwise, `ldsflda` returns managed pointer that can move depending on the runtime implementation details.

The type of the static field does not affect this behavior.

"unmanaged type" is C# specific concept. The meaning of "unmanaged" in ECMA-335 spec has nothing with "unmanaged types" in C#.

My suggestion for the edit would be to change `(e.g., ldloca, ldarga, and ldsflda)` to ` (e.g., ldloca and ldarga)`. It is not correct to describe the pointer returned by `ldsflda` for RVA fields as transient pointer that can be only used within the method. The pointer returned by `ldsflda` for RVA fields is a regular unmanaged pointer that does not have the lifetime scoped to the method.

**Comment by jkotas** [comment]
Actually, the rest of the ECMA-335 does not mention the "transient pointers" anywhere else. I think the transient pointers might have been a concept in the early versions of the spec, the concept got deleted, and this one place was missed. We may want to delete the whole paragraph that talks about the transient pointers.

**Comment by Sergio0694** [comment]
> ""unmanaged type" is C# specific concept. The meaning of "unmanaged" in ECMA-335 has nothing to do with "unmanaged types" in C#."

Ooh I see, yeah that makes sense, thank you! 😊

So basically the only case where you can assume a static field is pinned is either if you use `[FixedAddressValueType]` or (better) if you're sure the backing store is a RVA field like it will be the case with (hopefully it everything makes it) constant buffers in C#11/.NET 7, but not in any other case?

> "Actually, the rest of the ECMA-335 does not mention the "transient pointers" anywhere else. I think the transient pointers might have been a concept in the early versions of the spec, the concept got deleted, and this one place was missed. We may want to delete the whole paragraph that talks about the transient pointers."

Right, I was quite puzzled by this too as I'd never seen them mentioned anywhere else, and they seemed a bit random.
Should we just open a PR to remove that entire paragraph then?

Related: would you mind taking a look at https://github.com/dotnet/roslyn/issues/57970 when you have some spare time? Was wondering whether this optimization would still be valid from a runtime/ECMA perspective even if we conclude that transient pointers are not actually a thing. You mentioned that `ldloca` and `ldarga` would still return a pointer that can be used as a raw pointer, so it seems like we should be able to ditch those extra `conv.u` opcodea and save some binary size "for free"? 😄

Closing this issue in the meantime given it's not actually an issue in CoreCLR itself then.

**Comment by jkotas** [comment]
> Closing this issue in the meantime given it's not actually an issue in CoreCLR itself then.

We are still tracking the ECMA updates in https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md
