### ISSUE TITLE
Strange RegEx performance in .NET 5

### ISSUE THREAD

**Issue by NiJeTi** [dotnet/runtime#62902]
### Description

Hello!

I've made a benchmark to test RegEx performance impact.
This benchmark tries to run a looping expression in a 2 seconds timeout.

Input:
`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa>`
Pattern:
`(a+)+$`

Then I've launched it on 3 different runtimes: _.NET Core 3.1_, _.NET 5_, _.NET 6_.
.NET Core 3.1 and .NET 6 failed by timeout in approximately the same time,
when .NET 5 ran to completion in about 90 microseconds with a result of an empty string.

_How is this possible and does this mean that .NET 5 is much more faster in RegEx handling?_

#### Benchmark source code
```cs
using System;
using System.Text.RegularExpressions;

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

namespace RegexBenchmark;

internal static class Program
{
    private static void Main()
    {
        BenchmarkRunner.Run<Benchmark>();
    }
}

[Config(typeof(Config))]
public class Benchmark
{
    private class Config : ManualConfig
    {
        public Config()
        {
            AddJob(Job.Default.WithRuntime(CoreRuntime.Core31));
            AddJob(Job.Default.WithRuntime(CoreRuntime.Core50));
            AddJob(Job.Default.WithRuntime(CoreRuntime.Core60));
        }
    }

    [Benchmark]
    public void MatchRegex()
    {
        try
        {
            Regex.Match(
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa>",
                "(a+)+$", RegexOptions.None, TimeSpan.FromSeconds(2));
        }
        catch (RegexMatchTimeoutException) { }
    }
}
```

### Configuration

```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1415 (21H1/May2021Update)
Intel Core i7-9700K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.101
  [Host]     : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
  Job-HDOIGS : .NET 5.0.13 (5.0.1321.56516), X64 RyuJIT
  Job-YSVULO : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
  Job-NVYNMT : .NET Core 3.1.22 (CoreCLR 4.700.21.56803, CoreFX 4.700.21.57101), X64 RyuJIT
```

### Data

|     Method |        Job |       Runtime |            Mean |        Error |       StdDev |
|----------- |----------- |-------------- |----------------:|-------------:|-------------:|
| MatchRegex | Job-HDOIGS |      .NET 5.0 |        90.56 μs |     1.547 μs |     1.447 μs |
| MatchRegex | Job-YSVULO |      .NET 6.0 | 1,997,947.41 μs | 2,505.165 μs | 2,220.763 μs |
| MatchRegex | Job-NVYNMT | .NET Core 3.1 | 1,998,568.38 μs | 2,812.096 μs | 2,630.436 μs |

```
Benchmark.MatchRegex: Job-HDOIGS(Runtime=.NET 5.0)
Runtime = .NET 5.0.13 (5.0.1321.56516), X64 RyuJIT; GC = Concurrent Workstation
Mean = 90.561 us, StdErr = 0.374 us (0.41%), N = 15, StdDev = 1.447 us
Min = 88.173 us, Q1 = 89.680 us, Median = 90.417 us, Q3 = 91.795 us, Max = 92.671 us
IQR = 2.115 us, LowerFence = 86.507 us, UpperFence = 94.968 us
ConfidenceInterval = [89.014 us; 92.109 us] (CI 99.9%), Margin = 1.547 us (1.71% of Mean)
Skewness = -0.18, Kurtosis = 1.71, MValue = 2
-------------------- Histogram --------------------
[87.858 us ; 89.868 us) | @@@@
[89.868 us ; 93.442 us) | @@@@@@@@@@@
---------------------------------------------------

Benchmark.MatchRegex: Job-YSVULO(Runtime=.NET 6.0)
Runtime = .NET 6.0.1 (6.0.121.56705), X64 RyuJIT; GC = Concurrent Workstation
Mean = 1.998 s, StdErr = 0.001 s (0.03%), N = 14, StdDev = 0.002 s
Min = 1.993 s, Q1 = 1.997 s, Median = 1.999 s, Q3 = 1.999 s, Max = 2.001 s
IQR = 0.002 s, LowerFence = 1.994 s, UpperFence = 2.002 s
ConfidenceInterval = [1.995 s; 2.000 s] (CI 99.9%), Margin = 0.003 s (0.13% of Mean)
Skewness = -0.53, Kurtosis = 2.36, MValue = 2
-------------------- Histogram --------------------
[1.992 s ; 2.002 s) | @@@@@@@@@@@@@@
---------------------------------------------------

Benchmark.MatchRegex: Job-NVYNMT(Runtime=.NET Core 3.1)
Runtime = .NET Core 3.1.22 (CoreCLR 4.700.21.56803, CoreFX 4.700.21.57101), X64 RyuJIT; GC = Concurrent Workstation
Mean = 1.999 s, StdErr = 0.001 s (0.03%), N = 15, StdDev = 0.003 s
Min = 1.995 s, Q1 = 1.996 s, Median = 1.999 s, Q3 = 2.000 s, Max = 2.005 s
IQR = 0.003 s, LowerFence = 1.991 s, UpperFence = 2.005 s
ConfidenceInterval = [1.996 s; 2.001 s] (CI 99.9%), Margin = 0.003 s (0.14% of Mean)
Skewness = 0.59, Kurtosis = 2.51, MValue = 2
-------------------- Histogram --------------------
[1.994 s ; 2.006 s) | @@@@@@@@@@@@@@@
---------------------------------------------------
```

**Comment by teo-tsirpanis** [comment]
Hello @NiJeTi, yes that's ~~strange~~ counterintuitive, in fact I had seen some tests fail because such slow regexes became fast and did not timeout. Since .NET 5 the `System.Text.RegularExpressions` types underwent significant performance optimizations which presumably included simplifying some common hard regex patterns. You can learn more about them at https://devblogs.microsoft.com/dotnet/regex-performance-improvements-in-net-5/.

And that's not all; regexes in .NET will get even more optimizations in the future, including source generators. You can see the planned work in https://github.com/dotnet/runtime/labels/area-System.Text.RegularExpressions.

**Comment by NiJeTi** [comment]
@teo-tsirpanis Hi! When I faced the problem for the first time I read this article about performance improvements. But this does not make it clear to me why for .NET 6 the performance is not the same or even better

**Comment by teo-tsirpanis** [comment]
Oh, didn't see that in .NET 6 it regressed. That's a bug then.

**Comment by teo-tsirpanis** [comment]
I have no idea, I am not on the .NET team (😛) but if you have a profiler perhaps you would help them by adding execution traces for .NET 5 and 6.

**Comment by hez2010** [comment]
I can also repro it in the latest main branch. Seems that it's a regression from .NET 5. @stephentoub

**Comment by ericstj** [comment]
cc @joperezr 
Might be something that's relatively easy to bisect here: https://github.com/dotnet/runtime/commits/release/6.0/src/libraries/System.Text.RegularExpressions/src

**Comment by hez2010** [comment]
The regression was introduced by #56735.

**Comment by joperezr** [comment]
@NiJeTi thanks for logging this, I'm taking a look now.

**Comment by joperezr** [comment]
@hez2010 thanks so much for finding the culprit change. You are correct, that seems to be the change that caused this performance regression. That said, it does mean that the regression here is kind of "by design". Let me explain: one of the first things we do when you create a new Regex with a pattern, is that we try to find ways where we can optimize your pattern to some equivalent but more performant variation of your pattern. This means that this more performant variation should still result in the same match results than the original pattern, except that performing said matches should be faster. One example of the optimizations we do is to try and make loops in your pattern atomic when possible, which would then result in us not having to backtrack (which of course avoiding backtracking as much as possible leads to much better perf). In .NET 5, we introduced an optimization which would turn your pattern `(a+)+$` into an atomic loop `(?>a+)+$` which of course was much faster since it removes entirely the need to backtrack. After making that loop atomic, all of what our engine does is to match 'a' as much times as possible and then check if the next character is a '\n', and if not, we immediately return an unsuccessful match since we won't try to backtrack. 

This optimization works perfect for your specific pattern, but it unfortunately affects other very similar patterns which were incorrectly getting the optimization. Take the pattern that is discussed on that PR for example: `(a{2,3}){2}`. In this case, we were making that first loop atomic as well (meaning `(?>a{2,3}){2}`) which is a problem since now we won't match `aaaa` given the first loop would have first matched 'a' greedily three times, but then that wouldn't be matched 2 times so that would fail. Without the optimization, the engine does successfully backtrack one position, matches 'aa' in the first group, and then does match that twice so the Match succeeds. This means that this optimization wasn't actually producing the same result as the original pattern, which is why that change was rolled back in 6.0. We could try to bring that optimization partially back for specific cases like yours, where the outer loop uses '+' but most range loops that are not 1 would need to stay without the optimization.

I hope the above explanation sort of made sense. One thing you may be interested in trying for patterns like yours, is the new NonBacktracking engine we added, which works very well for cases of patterns that might involve a lot of backtracking. This API is new in 7.0. You can use it by doing:

```c#
            Regex.Match(
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa>",
                "(a+)+$", RegexOptions.NonBacktracking, TimeSpan.FromSeconds(2));
```

The NonBacktracking engine is not as performant as the Interpreter (default engine) for patterns that don't have a lot of backtracking, but can guarantee close to linear times for heavy backtracking patterns like yours.

**Comment by joperezr** [comment]
Also, FWIW, this particular pattern's backtracking is an issue not only for .NET's engine, if you checkout other engines like even PCRE2, it would also cause a catastrophic backtracking issue on it: https://regex101.com/r/fwQLnB/1

**Comment by stephentoub** [comment]
> here is kind of "by design"

Yes,  this was on purpose. The optimization added to .NET 5 was erroneous, i.e. it was actually a functional regression, and that PR removed the faulty code. As noted in that PR, "There are likely special-cases of this special-case that are still valid, but I'm not convinced it's worth trying to maintain and risk other gaps." In other words,  we could probably add back a subset of what was reverted, but we'd need to think really hard about it to ensure we didn't reintroduce a regression.  What is the actual expression you're using that led you to open this issue? Presumably it's not the expression you cited :-)

**Comment by ericstj** [comment]
If this is a functional regression, would that make it a candidate for servicing 5.0?  Is this akin to silent-bad-code-gen? (certainly less severe)

**Comment by stephentoub** [comment]
> If this is a functional regression, would that make it a candidate for servicing 5.0?

We could, but the reason I didn't push for this is  while it will fix some incorrect answers (typically not matching things that should match), there are cases where the answer is still correct and we'd be pushing out a significant increase in algorithmic complexity as part of servicing. This is the second report I've seen,  though this one also doesn't appear to be a production issue.

**Comment by NiJeTi** [comment]
@stephentoub My project has a feature to add custom regular expressions to validate user data. So during testing I added this particular regex and also this input. After some testing I've found that this whole feature was a "kind of" performance bottleneck and eventually decided to test it whit different runtimes. So this is the result I've got...

**Comment by danmoseley** [comment]
Is seems this can be closed now?

**Comment by NiJeTi** [comment]
@danmoseley Hello! Yeah. Thanks!

**Comment by danmoseley** [comment]
Thanks @NiJeTi !
