### ISSUE TITLE
How to identify ICU is used in .net 6 and later...

### ISSUE THREAD

**Issue by igandrews** [dotnet/runtime#62930]
### Description

The [documentation describing the changes that happened in .net 5 and later regarding changing to use ICU](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) specifically state that doing an IndexOf for "\n" in a string containing "\r\n" would return -1 and it does in .net 5. However in .net 6 (presumably relating to [this change](https://github.com/dotnet/runtime/pull/57078)) it returns 6 as it did prior to .net 5. So how should a library developer determine that the application is using NLS or ICU?

### Reproduction Steps

string s = "Hello\r\nworld!";
int idx = s.IndexOf("\n");

### Expected behavior

As the documentation states "In .NET 5.0 and later versions on Windows 10 May 2019 Update and later versions, the snippet prints -1."

### Actual behavior

Returns 6.

### Regression?

Intentional change based on [this pull](https://github.com/dotnet/runtime/pull/57078) but then update the documentation and add api so developers can make runtime decisions based on which is used.

### Configuration

.NET 6 (6.00.21.52210)
Windows 10.0.19044

**Comment by tarekgh** [comment]
@igandrews thanks for your report.  Yes, we have changed the behavior of searching `\n` in the string in .NET 6.0 because there was a demand from the community to get the desired behavior. 

Your code result

```C#
string s = "Hello\r\nworld!";
int idx = s.IndexOf("\n");
``` 

can be used to differentiate the behavior difference. this will return -1 only in .NET 5.0.

If you are looking for generic way to know if running with ICU (and not NLS), I am including some code here which can help you detect that:

```C#
        public static bool ICUMode()
        {
            SortVersion sortVersion = CultureInfo.InvariantCulture.CompareInfo.Version;
            byte[] bytes = sortVersion.SortId.ToByteArray();
            int version = bytes[3] << 24 | bytes[2] << 16 | bytes[1] << 8 | bytes[0];
            return version != 0 && version == sortVersion.FullVersion;
        }
```

You can use `RuntimeInformation.FrameworkDescription` to know the version of the .NET too if needed. 

For the doc, you may log a doc issue https://github.com/dotnet/docs or even just submit a PR. I can do that too when I have a chance. 

Please let me know if you have any more questions.

**Comment by igandrews** [comment]
Thx. Yes that helps. We were using the \n to identify nls vs icu but since that changed it wasn't clear what is the best way to identify. It would be good if some api were added rather than having to discern that but obviously that's a feature request. I appreciate the code snippet and will use that instead.
