### ISSUE TITLE
Support file named 'NUL'

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#62943]
On Windows you can actually create a file named `NUL`. I found it when I tried to redirect output of curl.exe to null device, but it actually creates a file named `NUL`.

![image](https://user-images.githubusercontent.com/5644458/146490403-04f87897-7470-4702-9c20-9356621ea589.png)

There's some interesting characteristic of it:
- The explorer.exe can only see the existence of the file. It can't do any operation with the file.
  - When trying to delete the file, it prompts for elevation. The file disappears in view, but comes back after refresh.
  - When trying to copy the file, it claims "too large for destination file system".
- notepad can't open the file.
- PowerShell 7 can see the file when listing directory, but can't read or delete it.
- .NET Frameworks throws when trying to open the file. .NET Core opens the null device.
- However, **VS Code can read the content of the file, and copy or delete the file.** It just blocks creation of such file.

I'm on Windows 10, but I heard that Windows 11 may remove the restrictions of special DOS file names.

On .NET Core we should be moving forward and accept some breaking changes. Lack of support is also blocking PowerShell.

**Comment by huoyaoyuan** [comment]
https://github.com/nodejs/node/blob/c61870c376e2f5b0dbaa939972c46745e21cdbdd/deps/uv/src/win/fs.c#L1136

I'm also wonder why VSCode can manipulate it. It seems that node also uses `CreateFileW`, the same with .NET.

**Comment by huoyaoyuan** [comment]
I'm not able to create such file again with curl.exe. I don't remember the exact command I used. It may be manipulated by WSL, but I don't have WSL installed right now.

**Comment by vcsjones** [comment]
Does .NET even need to do anything to support this? If I am not mistaken, you just need to disable path parsing. Something like this would work:

```csharp
System.IO.File.WriteAllBytes(@"\\?\D:\NUL", new byte[] { 1, 2, 3 });
```

If I had to guess, node is doing that for you: https://github.com/nodejs/node/blob/c61870c376e2f5b0dbaa939972c46745e21cdbdd/deps/uv/src/win/fs.c#L124.

**Comment by huoyaoyuan** [comment]
> If I am not mistaken, you just need to disable path parsing.

Requiring additional work to get supported is painful. Paths are usually passed in the forms most familiar to everyone.

I remember that .NET adds the `\\?\` prefix in some situations. Can we expand it so that `NUL` file gets supported without additional work?

**Comment by vladd** [comment]
I think it must be possible to adjust the passed-in paths to auto-prepend the `\\?\` prefix if needed. The question which immediately appears is that the users would be unable to work with the files like that through the usual tools like Explorer.

This resembles the problem with `MAX_PATH`: we could overcome the restriction but will the rest of the world follow?

**Comment by adamsitnik** [comment]
During .NET 6 development, I've tried to use `NtCreateFile` instead of `CreateFileW` for opening file handles. The tests were passing, but the reviewers were sceptical because this change required to use paths prefixed with `\??\`. 

It turned out that I've introduced plenty of bugs (#54474,  #54475, #54337) because the logic for extending file paths was incomplete. I've carefully studied Windows source code and got to the conclusion that the best way to solve this problem would be to use one of the Windows methods like `RtlpWin32NtNameToNtPathName`. The problem is that all of them are private and by design, .NET can't rely on private OS methods (they can change over time).

I've tried to implement the mapping, but there were simply too many edge cases (https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html). The risk of introducing this change was not worth it (I wanted to use `NtCreateFile` to reduce the number of sys-calls).

Based on my experience I don't believe that expanding all paths by default just to make special DOS file names work is worth it. It increases the code complexity, chances for bugs, and perf regressions (it's extra work). Those who for some reason want to use such names need to do the research and provide the right prefix. If that is too much, they should give up on this idea.

**Comment by huoyaoyuan** [comment]
So PowerShell is responsible to modify at their side to handle the file correctly?

**Comment by adamsitnik** [comment]
> So PowerShell is responsible to modify at their side to handle the file correctly?

Yes.

**Comment by stephentoub** [comment]
> The tests were passing, but the reviewers were sceptical because this change required to use paths prefixed with \??\.

Skeptical's my middle name ;-)
![](https://media.tenor.co/images/b5dab8c12ded7e41b28a0164840c0aeb/raw)

**Comment by iSazonov** [comment]
@adamsitnik Please look https://github.com/PowerShell/PowerShell/issues/16841#issuecomment-1029846806
