### ISSUE TITLE
Runtime metric for synchronous waits

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#63016]
In my company there were many migrations from sync to async code and in many places some `Task.Wait()`, `Task.Result` or `Task.GetAwaiter().GetResult()` can be found which often greatly impact the performance of the applications. To help correlate these synchronous waits with other issues we wanted to increment a metric everytime the TPL event `TaskWaitBegin` was emitted.

A side-car application was already collecting the GC, Contention, and Exception events from `Microsoft-Windows-DotNETRuntime` so we started collecting `Tasktransfer` from `System.Threading.Tasks.TplEventSource`. The problem is that `Tasktranfer` also contains `TaskScheduled`, `AwaitTaskContinuationScheduled`, and `TaskWaitBegin` with `Behavior == TaskWaitBehavior.Asynchronous` (which is not relevant here).

To give some digits, in the side-car app before the change ~3500 events were processed (received **and** processed) by second and after it reached ~48K events. Our new metric shows 0.7 synchronous waits by second so there is ~45K asynchronous waits that we read and discard.
![After collecting TaskWaitBegin event, the number of events increases a lot](https://user-images.githubusercontent.com/9092290/146795831-b350ad09-bd27-43a3-9686-c5347a80be12.png)

On the side of the main application, the events `TaskScheduled`, `AwaitTaskContinuationScheduled` are emitted but never read. The CPU usage increased from 86% to 100% and we estimate that the application is working 5 times slower.

Is it already possible or would it make sense to only filter on `TaskWaitBegin` with `Behavior == TaskWaitBehavior.Synchronous`?

**Comment by verdie-g** [comment]
@ericstj @stephentoub do you think an event counter for synchronous waits would be a nice addition to the runtime?

**Comment by verdie-g** [comment]
> If the goal is to simply find places that are synchronously waiting

We already know where the synchronous waits are performed, but removing them can be extremely costly since we need to migrate the code to async all the way up. So often, this it simply not done. When having issues with an application that look like a thread starvation, having a metric for synchronous waits could help understand what's the cause and would help to justify the cost to do these async migrations.

**Comment by ericstj** [comment]
@noahfalk are you aware of any existing diagnostic tooling that might help here?

**Comment by noahfalk** [comment]
This is one approach to the problem: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-threadpool-starvation

@verdie-g the impression I got is that your team is already aware of this approach and looking for greater automation? A few thoughts:
1. In .NET 6 the threadpool heuristics changed to compensate more aggressively for blocking that comes from Task.Wait() and Task.Result. Maybe that will reduce the impact of the issue for you.
2. I am not aware of any current counter for TaskWaitBegin. However you might be able to synthesize one by counting events with an [EventListener](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/eventsource-collect-and-view-traces#eventlistener). Last time I benchmarked it an efficient EventListener consumed ~250ns/event so processing 4500 events per/sec might put you in the 1ms CPU/sec arena. That should be substantially lower than the overhead you were seeing in the sidecar.
3. Not to disuade you, but it is unclear to me how helpful the metric will be for you in practice. My understanding so far is that if you see threadpool starvation today you know that either it is being caused by one of N different locations in your code where threads are blocking in Task.Wait()/Task.Result, or it comes from one of M other reasons a thread is blocked. If you had a counter that said lots of threads were blocked in Task.Wait() then it narrows N + M possible causes down to only N causes. However you described fixing all N things at once would be expensive so I am guessing the next step would be to look at stack traces to figure out which of the N Task.Wait() call sites need fixing rather than trying to fix them all? Looking at callstacks is the same investigation step that would presumably happen if you didn't have the TaskWaitBegin counter and wanted to triage which of the N + M issues needed fixing.

Hope that helps!

**Comment by verdie-g** [comment]
1. True, we're still using .NET 5 and need to do that upgrade.
2. Thanks I'll look into that.
3. I think what I was looking for was a metric to easily prove those synchronous waits are an issue. Currently we are not even collecting all metrics used in https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-threadpool-starvation especially the "Completed Work Item Count" and "ThreadPool Queue Length" so we should start with that and when they get suspicious take a dump to see if we can find some synchronous wait in our stacktraces.

Thanks for you answers.
