### ISSUE TITLE
Writing an efficient custom AsyncMethodBuilder is too hard

### ISSUE THREAD

**Issue by simonferquel** [dotnet/runtime#63125]
Hi, as part of some experiments we are doing at Unity around leveraging async/await for our engine coroutine, I played with the idea of creating a custom Unity async return type, with a lot of restrictions allowing us to bring better scalability than ValueTask for some specific scenarios e.g. things allowing to write stuff like 
```
async UnityAwaitable<int> DoSomething(){
 // setup some animation
 await UnityAwaitable.EndOfFrame();
 // we are still within the same frame but the animation subsystem is done for current frame
 return <something produced by the animation subsystem>;
}
```

These are very short leaved, always async methods.

By implemting the corresponding AsyncMethodBuilder, I figured that:
- the naive approach (simply calling awaiter.UnsafeOnCompleted(stateMachine.MoveNext) is highly inefficient - it boxes the state machine to instanciate an Action delegate on each suspension point - which in our case can be as much as multiple times per frame.
- it is possible to reduce allocations to once per async method call (whatever number of suspension point we have): but it is far from obvious how to do that in a correct way, it requires a deep understanding about how the builder is attached to the state machine etc.

By looking at builtin AsyncMethodBuilders, I saw some hints at generalization of solving this problem, but everything seem internal, and thus all 3rd party implementations must re-implement these implementations by themselves.

It would be nice to provide a set of primitives to help achieve that.

**Comment by teo-tsirpanis** [comment]
I have been thinking of something like this to solve the allocations `UnsafeOnCompleted` causes:

``` csharp
namespace System.Runtime.CompilerServices;

interface IStatefulNotifyCompletion : INotifyCompletion, ICriticalNotifyCompletion
{
    // The existing (Unsafe)Oncompleted methods will be implemented as DIMs
    // in terms of this method, to ease implementations.
    void UnsafeOnCompleted(Action<object> continuation, object state);
}
```

Would it help with your use case @simonferquel? I can write an API proposal with more details.

**Comment by stephentoub** [comment]
> By looking at builtin AsyncMethodBuilders, I saw some hints at generalization of solving this problem, but everything seem internal, and thus all 3rd party implementations must re-implement these implementations by themselves.

> It would be nice to provide a set of primitives to help achieve that.

What specifically?

> I have been thinking of something like this to solve the allocations UnsafeOnCompleted causes
> I can write an API proposal with more details

That can easily just kick the can down the road.  For example, Task has a single object field used to store the continuation object.  If the whole continuation is represented as an Action, then it can be stored as-is into that single field, and interlocked operations can be used to manipulate the field.  If the continuation is instead represented as two object references, that's no longer feasible.  Any API proposal here should involve a full prototype that demonstrates how it actually beneficially moves the needle.

**Comment by simonferquel** [comment]
@stephentoub Originally, I was more thinking about providing a public StateMachineBox class and helper methods to make it easier to avoid allocation of the Action on each suspend point. Or even a generic asyncmethodbuilder struct implementation that would implement everything and take lamdas in its constructor for things like creating the Promise object and settings its result/exception.

**Comment by stephentoub** [comment]
> Originally, I was more thinking about providing a public StateMachineBox class and helper methods to make it easier to avoid allocation of the Action on each suspend point. Or even a generic asyncmethodbuilder struct implementation that would implement everything and take lamdas in its constructor for things like creating the Promise object and settings its result/exception.

Thanks.

The problem is I expect most implementations would need subtle differences.  For example, we have two implementations of this in corelib, one for AsyncTaskMethodBuilder and one for PoolingAsyncValueTaskMethodBuilder; the latter can't use the same implementation as the former as it needs control over the actual box implementation.  Note, too, that something like AsyncValueTaskMethodBuilder doesn't need to use the box type directly... it can just wrap AsyncTaskMethodBuilder (https://github.com/dotnet/corefx/blob/d6173e069a9bcedfdfd7f4f41e67d23f67157b61/src/System.Threading.Tasks.Extensions/src/System/Runtime/CompilerServices/AsyncValueTaskMethodBuilder.cs#L14-L17).

This is a case where we'd _really_ need multiple full consuming implementations demonstrating that the exposed APIs are both necessary and sufficient.  I can also count in single digits the number of times I've seen folks actually invest in building a custom task-like type, and some of those even just wrapped AsyncTaskMethodBuilder, so the audience here for anything we might expose is very limited, making the bar even higher.
