### ISSUE TITLE
Incorrect nullable annotation for ValidationAttribute.IsValid overload

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#63147]
### Description

The `System.ComponentModel.DataAnnotations.ValidationAttribute` defines:

```cs
protected virtual ValidationResult? IsValid(object? value, ValidationContext validationContext)
``` 

This should be:

```cs
protected virtual ValidationResult? IsValid(object? value, ValidationContext? validationContext)
``` 

Since the overload is called with a null validation context along several code paths. In particular, if someone calls this overload:

```cs
public void Validate(object? value, string name);
```

### Reproduction Steps

n/a

### Expected behavior

n/a

### Actual behavior

n/a

**Comment by geeknoid** [comment]
Oh, and the result value probably should be typed as ValidationResult? since ValidationResult.Success is just null. Right now, my code contains "return ValidationResult.Success!" to overcome that.

**Comment by stephentoub** [comment]
> Since the overload is called with a null validation context along several code paths. In particular, if someone calls this overload:

IsValid may also null ref if a null ValidationContext is provided, e.g.
https://github.com/dotnet/runtime/blob/a2b288d7da6a36164e5e556cd736ca50e0a9bc02/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/ValidationAttribute.cs#L374
and
https://github.com/dotnet/runtime/blob/a2b288d7da6a36164e5e556cd736ca50e0a9bc02/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/CompareAttribute.cs#L34
so while the annotation may not be ideal, just changing the annotation also isn't correct.

> Oh, and the result value probably should be typed as ValidationResult? since ValidationResult.Success is just null. Right now, my code contains "return ValidationResult.Success!" to overcome that.

I'm not understanding.  The return type is typed as `ValidationResult?`:
https://github.com/dotnet/runtime/blob/a2b288d7da6a36164e5e556cd736ca50e0a9bc02/src/libraries/System.ComponentModel.Annotations/ref/System.ComponentModel.Annotations.cs#L301-L303

**Comment by geeknoid** [comment]
Sorry, disregard my comment about the return type. I was seeing this because my local definition of the override didn't include ? in the return type. The C# compiler is happy with that. I just added the ? to my return type and all is well.

**Comment by geeknoid** [comment]
> so while the annotation may not be ideal, just changing the annotation also isn't correct.

I don't understand this. Either the function is sometimes called with a null reference or it isn't. What am I missing? The fact it is called with null implies that the parameter should be declared as nullable.

**Comment by stephentoub** [comment]
> I don't understand this. Either the function is sometimes called with a null reference or it isn't. What am I missing? The fact it is called with null implies that the parameter should be declared as nullable.

Anyone can call any reference type parameter with a null reference; that doesn't mean null was intended to be allowed.  There are any number of functions that don't validate a non-nullable parameter to be non-null, such that you might get away with passing in null even though it wasn't intended to be allowed.  And in this particular case, passing in null _will_ blow up in some cases, e.g. this ends up null ref'ing in the very method whose argument we're discussing:
```C#
using System.ComponentModel.DataAnnotations;

var a = new Int32ValidationAttribute();
a.IsValid("", null);

sealed class Int32ValidationAttribute : ValidationAttribute
{
    public new ValidationResult? IsValid(object? value, ValidationContext? validationContext) => base.IsValid(value, validationContext!);
    public override bool IsValid(object? value) => value is int;
}
```

It comes down to intent.  The only two public methods that accept a ValidationContext (GetValidationResult and Validate) both validate that their ValidationContext argument is non-null, throwing if it's null, and the base implementation of IsValid that takes a ValidationContext may null ref if given a null value, so the intent certainly seems to be that null ValidationContexts weren't intended to be supported and in most cases aren't.  Even the comment at that call site passing in `null!` speaks to this:
```C#
            // The IsValid method without a validationContext predates the one accepting the context.
            // This is theoretically unreachable through normal use cases.
```
So, at least as far as I read it, this `null!` is basically legacy and there only because it has to be there due to coming before the fixed thing.

Ultimately, those folks that know this library better should make a call.  However, specifically to my comment "so while the annotation may not be ideal, just changing the annotation also isn't correct" and your question "I don't understand this", I'm highlighting that _just_ changing the annotation to be nullable doesn't then magically also fix the fact that the base implementation may blow up if null is provided and yet the annotation would be saying "sure, pass in null".  So even if we decided it should be `?`, changing just that annotation is incorrect.
