### ISSUE TITLE
The System.Text.Encoding.Latin1 encoder fallback should encode the ligature `œ` as `oe` instead of `o`

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#63192]
### Description

Encoding the `œ` character (LATIN SMALL LIGATURE OE, U+0153) with the `System.Text.Encoding.Latin1` encoding results as the single character `o`, losing the character `e`.

This is unfortunate because transforming `œ` to `oe` would be much more understandable in most (if not every) cases.

For example, in wikipedia links:
* https://en.wikipedia.org/wiki/Onomatopœia ✅ Valid link
* https://en.wikipedia.org/wiki/Onomatopoeia ✅ Valid link
* https://en.wikipedia.org/wiki/Onomatopoia ❌ Invalid link

For example, in French:
* Cœur → Coeur ✅ Although linguistically incorrect, the word semantic is preserved
* Cœur → Cour ❌ Changes the word semantic (heart → yard)

Note: the same applies to the capital `Œ` ligature.

### Reproduction Steps

```csharp
var latin1 = System.Text.Encoding.Latin1;
foreach (var text in new[] { "Œuf", "Cœur" })
{
    System.Console.WriteLine($"{text,-4} -> {latin1.GetString(latin1.GetBytes(text))}");
}
```

### Expected behavior

The code snippet produces the following output:
```
Œuf  -> OEuf
Cœur -> Coeur
```

### Actual behavior

The code snippet produces the following output:
```
Œuf  -> Ouf
Cœur -> Cour
```

### Regression?

The [System.Text.Encoding.Latin1](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.latin1) encoding was introduced in .NET 5 and has always encoded `œ` as `o` so this is not a regression.

### Known Workarounds

Writing a custom `EncoderFallback` could probably workaround this issue but would miss the point of having a safe default behaviour.

### Configuration

- **.NET version**: both .NET 5 and .NET 6
- **OS and architecture**: not relevant

### Other information

I'd be happy to propose a pull request to fix this behaviour. I have already started looking at the [EncoderLatin1BestFitFallback](https://github.com/dotnet/runtime/blob/v6.0.1/src/libraries/System.Private.CoreLib/src/System/Text/EncoderLatin1BestFitFallback.cs) class where the best-fit fallback is happening.

**Comment by tarekgh** [comment]
@0xced

`Latin 1` encoding is the `iso-8859-1`. This encoding didn't support mapping characters like `œ`.  The support of such characters is introduced in the `iso-8859-15`.  You may look at the [doc](https://www.i18nqa.com/debug/table-iso8859-1-vs-iso8859-15.html) for more info what has changed between `so-8859-1` and `iso-8859-15`. You may look at the [wikipedia](https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Languages_with_incomplete_coverage) table which stating the same thing. 

To get the right mapping for `œ`, you need to use `iso-8859-15` instead. Something like:

```C#
            Encoding encoding = Encoding.GetEncoding("iso-8859-15");    

            byte [] bytes = encoding.GetBytes("œ"); //  should produce the byte 0xbd
            string s = encoding.GetString(bytes);      // should produce the `œ`
```


>  The System.Text.Encoding.Latin1 encoding was introduced in .NET 5

Latin1 encoding was supported since .NET Framework v1 through the iso-8859-1. 

I am closing this issue but feel free to send any questions we can help you with. Thanks for your report.

**Comment by 0xced** [comment]
I understand what iso-8859-1 is and that `œ` is not defined in this encoding. I know I can use `iso-8859-15` instead but that's not the point of the issue that I raised.

My point is that the encoder **fallback** should produce `oe` (0x6F 0x65) instead of `o` (0x6F) when calling `System.Text.Encoding.Latin1.GetBytes("œ")` because `oe` is a **better fit** for `œ` than simply `o`. That's what I tried to explain in the description of this issue.

Your reply makes me think that you didn't read the issue thoroughly or that I really failed to make my point.

**Comment by tarekgh** [comment]
> Your reply makes me think that you didn't read the issue thoroughly or that I really failed to make my point.

Sorry for that. 

> My point is that the encoder fallback should produce oe (0x6F 0x65) instead of o (0x6F) when calling System.Text.Encoding.Latin1.GetBytes("œ") because oe is a better fit for œ than simply o. That's what I tried to explain in the description of this issue.

The point is this encoding was introduced very long ago in Windows and in .NET Framework. There is no fallback happening here. This encoding just decided to map the codepoints directly and is not really falling back. That is why it is mapping it to one byte. I know you may think this is not the best to do but that is the behavior of how this encoding behaved for long time, and we'll not be able to change that not because of app compatibility.

**Comment by 0xced** [comment]
> There is no fallback happening here. This encoding just decided to map the codepoints directly and is not really falling back. That is why it is mapping it to one byte.

There's still some misunderstanding here because a **best-fit fallback** as explained in [How to use character encoding classes in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding#BestFit) is absolutely happening (*When a character does not have an exact match in the target encoding, the encoder can try to map it to a similar character*). If you set a breakpoint inside the [EncoderLatin1BestFitFallbackBuffer.Fallback()](https://github.com/dotnet/runtime/blob/v6.0.1/src/libraries/System.Private.CoreLib/src/System/Text/EncoderLatin1BestFitFallback.cs#L37) method you can witness the fallback first hand (executing the code in the reproduction steps).

<img width="981" alt="TryBestFit" src="https://user-images.githubusercontent.com/51363/149549854-8ff9676d-38e9-4af1-9a05-8dfb2c03658b.png">

This here is the (fallback) mechanism transforming `œ` into `o` as _best-fit_.

> we'll not be able to change that not because of app compatibility

I'm not really buying the compatibility argument here. Looking at the list of [Breaking changes in .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0#core-net-libraries) I can see many changes that have a much much bigger impact that this proposal.

Honest question: Is it still worth arguing about this topic or should I save my energy for something else and move on?

**Comment by tarekgh** [comment]
The best fit data is part of the encoding data, which is why I said it is not fallback like a real other fallback which you can control replacing the output with any desired result. You can notice the best fit still using one character.

> I'm not really buying the compatibility argument here. Looking at the list of Breaking changes in .NET I can see many changes that have a much much bigger impact that this proposal.

This encoding has existed for a very long time and it is compatible with Windows too. We were surprised before when people notice changes like that. I am not seeing any strong reason we need to change that now. Especially we are trying to educate all users to move to Unicode. 

> Honest question: Is it still worth arguing about this topic or should I save my energy for something else and move on?

I am not trying to shut down any idea here but honestly this is a very low priority with the risk which we can just avoid.
