### ISSUE TITLE
Validate that no important Stream overrides are missing based on a systematic check

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#63191]
Over time, there has been a trickle of cases where a method on `Stream` should have been overridden but was overlooked. I, therefore, decided to take a systematic look at this and write a tool that checks all streams in all assemblies in the .NET distribution.

I'm posting the results here so that the team can take a look.

I noticed, for example, these interesting missing overloads on .NET 6:

* System.IO.Compression.DeflateStream: WriteByte(Byte)
* System.IO.Compression.GZipStream: WriteByte(Byte)
* System.IO.ConsoleStream : Stream =>... Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), ...
* System.Net.Base64Stream: Read(Span), ReadByte(), Write(ReadOnlySpan), WriteByte(Byte)
* System.Net.RequestStream: BeginRead(Byte[], Int32, Int32, AsyncCallback, Object), EndRead(IAsyncResult), Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte(), Write(ReadOnlySpan), WriteByte(Byte)
* System.Net.HttpRequestStream: Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte(), Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), WriteAsync(ReadOnlyMemory, CancellationToken), WriteByte(Byte)
* System.Net.HttpResponseStream: Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte(), Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), WriteAsync(ReadOnlyMemory, CancellationToken), WriteByte(Byte)
* System.Net.Quic.QuicStream: ReadByte(), WriteByte(Byte)
* System.Security.Cryptography.CryptoStream: Read(Span), Write(ReadOnlySpan)
* System.Net.Security.AuthenticatedStream: BeginRead(Byte[], Int32, Int32, AsyncCallback, Object), BeginWrite(Byte[], Int32, Int32, AsyncCallback, Object), EndRead(IAsyncResult), EndWrite(IAsyncResult), Read(Byte[], Int32, Int32), Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte(), Write(Byte[], Int32, Int32), Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), WriteAsync(ReadOnlyMemory, CancellationToken), WriteByte(Byte)
* System.Net.Security.NegotiateStream: Read(Span), ReadByte(), Write(ReadOnlySpan), WriteByte(Byte)
* System.Net.Security.SslStream: Read(Span), Write(ReadOnlySpan), WriteByte(Byte)

I ran the tool for .NET 5 and 6. The full results are attached. I noticed that there were quite a few overrides added from 5 to 6, so there seems to be some interest in doing that.

[MethodOverrideReport 5.0.8.txt](https://github.com/dotnet/runtime/files/7788865/MethodOverrideReport.5.0.8.txt)
[MethodOverrideReport 6.0.1.txt](https://github.com/dotnet/runtime/files/7788864/MethodOverrideReport.6.0.1.txt)

**Comment by GSPP** [comment]
For `SslStream` I found this existing issue:

- https://github.com/dotnet/runtime/issues/22834

It's closed but as far as I can tell it wasn't fully completed.

**Comment by stephentoub** [comment]
> System.IO.Compression.DeflateStream: WriteByte(Byte)
> System.IO.Compression.GZipStream: WriteByte(Byte)

These are reasonable to override; I'm not sure why we haven't before.

> System.IO.ConsoleStream : Stream =>... Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), ...

By design. ConsoleStream is abstract.  The derived streams (e.g. WindowsConsoleStream) override Write(ReadOnlySpan).  And the console streams don't provide async I/O-based operations, so there's little-to-no benefit in overriding WriteAsync.

> System.Net.Base64Stream: Read(Span), ReadByte(), Write(ReadOnlySpan), WriteByte(Byte)

By design. This stream isn't handed out publicly and the cited members aren't used by the implementation.  We don't need to add overrides that will just be dead code.

> System.Net.RequestStream: BeginRead(Byte[], Int32, Int32, AsyncCallback, Object), EndRead(IAsyncResult), Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte()

By design.  This is a write-only stream; Read throws NotSupportedException... we don't need to optimize the throwing of NotSupportedException by overriding all the read methods and can instead just rely on the base implementation to do so.

> System.Net.RequestStream: Write(ReadOnlySpan), WriteByte(Byte)

By design. This whole library is considered legacy and only exists for backcompat; you only get to the point of getting a RequestStream by going through Obsolete methods.  So we're not investing in minor optimizations.

> System.Net.HttpRequestStream: Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), WriteAsync(ReadOnlyMemory, CancellationToken), WriteByte(Byte)

By design.  This is a read-only stream.  Read throws NotSupportedException.

> System.Net.HttpResponseStream: Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte()

By design.  This is a write-only stream.  Write throws NotSupportedException.

> System.Net.HttpResponseStream:Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), WriteAsync(ReadOnlyMemory, CancellationToken), WriteByte(Byte)
> System.Net.HttpRequestStream: Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte()

By design. We _could_ override these, but for the XxAsync methods, we'd either just be duplicating what the base implementations do (wrapping the APM implementations), in which case there's no value in overriding them, or we'd need to replumb the whole implementation to be Task-based, and we're not investing in such improvements to HttpListener, which is considered legacy and not something we push developers to use.

> System.Net.Quic.QuicStream: ReadByte(), WriteByte(Byte)

These are reasonable to override. (And QuicStream hasn't shipped yet.)

> System.Security.Cryptography.CryptoStream: Read(Span), Write(ReadOnlySpan)

By design.  This could be changed with non-trivial effort, but right now CryptoStream is implemented with a single shared implementation for both the sync and async code paths, based on `{ReadOnly}Memory<byte>`.  To marshal a span in as that `{ReadOnly}Memory` would necessitate allocating a custom memory manager object to back such an instance, at which point you might as well just use the base implementation that allocates a one-byte array.  The alternative is to separate the implementations, which hasn't been done due to lack of evidence that CryptoStream is being used in a manner where these overrides matter for performance.  If such a scenario arose, the work could be done.

> System.Net.Security.AuthenticatedStream: BeginRead(Byte[], Int32, Int32, AsyncCallback, Object), BeginWrite(Byte[], Int32, Int32, AsyncCallback, Object), EndRead(IAsyncResult), EndWrite(IAsyncResult), Read(Byte[], Int32, Int32), Read(Span), ReadAsync(Byte[], Int32, Int32, CancellationToken), ReadAsync(Memory, CancellationToken), ReadByte(), Write(Byte[], Int32, Int32), Write(ReadOnlySpan), WriteAsync(Byte[], Int32, Int32, CancellationToken), WriteAsync(ReadOnlyMemory, CancellationToken), WriteByte(Byte)

By design. AuthenticatedStream is abstract.

> System.Net.Security.NegotiateStream: Read(Span), ReadByte(), Write(ReadOnlySpan), WriteByte(Byte)
> System.Net.Security.SslStream: Read(Span), Write(ReadOnlySpan), WriteByte(Byte)

By design.  Same issue as with CryptoStream.
