### ISSUE TITLE
SpecialFolder.MyDocuments / Personal returning wrong path for Unix

### ISSUE THREAD

**Issue by Miepee** [dotnet/runtime#63214]
### Description

Using `Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)` (and by extensions also `SpecialFolder.Personal`) on Unix based systems does not return the documents folder, and instead returns the same path as `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)`.

### Reproduction Steps

```cs
Console.WriteLine("Environment.SpecialFolder.MyDocuments:");
Console.WriteLine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments));
Console.WriteLine("Environment.SpecialFolder.UserProfile:");
Console.WriteLine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile));
```

### Expected behavior

Since `Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)` should return the directory that serves as a common repository for documents, it should report the directory I have set via `xdg-users-dir` / `XDG_DOCUMENTS_DIR` or `~/Documents` on Mac.

### Actual behavior

It reports my home directory instead.
Comparison between Linux and Windows:
![grafik](https://user-images.githubusercontent.com/38186597/147738201-09956fdf-9a5a-413b-b18a-b0030fa88b53.png)

Checking [this](https://github.com/dotnet/runtime/blob/af9202a6daf91ba58d5d58bafbb6581aebb8a642/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L89) it seems that it's intentional. Why doesn't it just use `ReadXdgDirectory(home, "XDG_DOCUMENTS_DIR", "Documents");` there? I can do a PR if it's wished for.

### Configuration

Dotnet version: 6.0.101
Can reproduce on the following distros: Arch Linux WSL2, Ubuntu 20.04 WSL2, Arch Linux, macOS Big Sur
Architecture: x64

**Comment by danmoseley** [comment]
This code was copied from Mono (since they'd more mature code for this) and it's curious that [they didn't handle MyDocuments at all - it throws.](https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mcs/class/corlib/System/Environment.cs#L623)

For Linux, the only question is whether this would be a breaking change for anyone who has XDG_DOCUMENTS_DIR set, but prefers/expects `/` or whatever home is. I think this is a reasonable change to make in a major version as the intent is clear (as is the workaround)

For macOS, looking at their [list of user folders](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW2) the code is not just missing Documents (returning just home) but also should be returning Movies (not 'Videos'). I think (?) those are reasonable changes too but I'm not a macOS person.

**Comment by danmoseley** [comment]
Looks like they reverted in Mono for reasons unclear -- https://github.com/mono/mono/pull/1953

**Comment by Miepee** [comment]
Not that knowledgeable with development flow here, would it be required for this change to be implemented in mono first before it's done in dotnet?

> For macOS, looking at their list of user folders the code is not just missing Documents (returning just home) but also should be returning Movies (not 'Videos'). 

This got me curious, and found out there are actually a few Fields missing that could be assigned to something (else). Currently compiling a huge table of it.

**Comment by danmoseley** [comment]
No, Mono is not upstream.

**Comment by Miepee** [comment]
Finished creating the table. I separated it into two, the first one where there are pretty clear equivalents, the second one which would need some discussion.

| SpecialFolder Field | Windows | Linux | Mac | Currently
| --- | --- | --- | --- | --- |
| ApplicationData | `%APPDATA%` | `XDG_CONFIG_HOME` | `HOME/Library/Preferences/` | `XDG_CONFIG_HOME`
| LocalApplicationData | `%LOCALAPPDATA%` | `XDG_DATA_HOME` | `HOME/Library` | `XDG_DATA_HOME`
| Desktop / DesktopDirectory|  `%USERPROFILE%\Desktop` | `XDG_DESKTOP_DIRECTORY` | `HOME/Desktop` | `XDG_DESKTOP_DIRECTORY`
| Programs | `%APPDATA%\Microsoft\Windows\Start Menu\Programs` | `XDG_DATA_HOME/applications` | `HOME/Applications` | -
| MyVideos | `%USERPROFILE%\Videos` | `XDG_VIDEOS_DIR` | `HOME/Movies` | `XDG_VIDEOS_DIR`
| Startup | `%APPDATA%\Microsoft\Windows\Start Menu\Programs\StartUp` | `XDG_CONFIG_HOME/autostart` | `HOME/Library/LaunchAgents` | -
| Templates | `%APPDATA%\Microsoft\Windows\Templates` | `XDG_TEMPLATES_DIR` | No equivalent | `XDG_TEMPLATES_DIR`
| MyDocuments / Personal | `%USERPROFILE%\Documents` | `XDG_DOCUMENTS_DIR` | `HOME/Documents` | `HOME`
| CommonPrograms | `%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs` | `/usr/share/applications` | `/Applications` | -
| CommonTemplates | `%ALLUSERSPROFILE%\Microsoft\Windows\Templates` | `/usr/share/templates` | no equivalent | `/usr/share/templates`
| ProgramFiles | `%SystemDrive%\Program Files` | `/opt` | `/Applications` | (OSX-only) `/Applications`
| StartMenu | `%APPDATA%\Microsoft\Windows\Start Menu` | `XDG_DATA_HOME/applications` | No equivalent | - |
| CommonStartup | `%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\StartUp` | `/etc/xdg/autostart` | `/Library/LaunchAgents`| -
| CommonStartMenu | `%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu` | `/usr/share/applications` | no equivalent | -


| SpecialFolder Field | Windows | Linux | Mac | Currently | Problem(s)
| --- | --- | --- | --- | --- | --- |
| CommonApplicationData | `%ProgramData%` | no equivalent | `/Users/Shared` | `/usr/share` | `/Users/Shared` has a sticky bit set, which means that only the user who created files in there later has the permission to edit those. This would make it impossible for an application to edit its data if it's ran by a different user.
| InternetCache | `%LOCALAPPDATA%\Microsoft\Windows\Temporary Internet Files` | No equivalent, no default browser |  `HOME/Library/Containers/com.apple.Safari/Data/Library/Caches/com.apple.Safari/` | (OSX-only) `HOME/Library/Caches` | Probably not a good idea to expose Safari's cache folder like this.
| CommonAdminTools | `%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Administrative Tools` | `/sbin`, `/usr/sbin` or `/ usr/local/sbin` | `/sbin` | - | Depends on which type of admin tools should be exposed. Ones of utmost importance, slightly less important or ones which have been put in place by the local admin?
| Fonts | `%windir%\Fonts` | `/usr/share/fonts` (for system fonts, should only be touched by package manager) or `/usr/local/share/fonts` (custom fonts that should be available for every user) | `/System/Library/Fonts` (system fonts) or `/Library/Fonts` (fonts that should be available to every user) | (OSX-only) `HOME/Library/Fonts` / (Linux-only) `HOME/.fonts` | Depends on the usecase. Is this for figuring out if a certain font is installed by the system? Is this for installing a font?

Considering these are all breaking changes, would these be accepted? And since these go far over this issue's intent, should I close this and open a new one for these?

**Comment by danmoseley** [comment]
Thanks for the table. Note there is also notionally columns for [iOS/tvOS](https://github.com/dotnet/runtime/blob/fa284882f1fec209d2cadd915c621078e8041228/src/mono/System.Private.CoreLib/src/System/Environment.iOS.cs#L35) and [Android](https://github.com/dotnet/runtime/blob/fa284882f1fec209d2cadd915c621078e8041228/src/mono/System.Private.CoreLib/src/System/Environment.Android.cs#L35). I see the iOS code requests NSSearchPathDirectory rather than relying on HOME.

My suggestion is to only fix things that are clearly wrong today and for which there's a use case. Perhaps that's just documents (both mac and Linux) and movies (mac currently uses videos) .

**Comment by Miepee** [comment]
I'd do a PR then that fixes documents for linux + Movies/ApplicationData/LocalApplicationData for Mac and open a new issue for the other fields. Would that be fine?

**Comment by danmoseley** [comment]
Hmm, I found discussion in https://github.com/dotnet/corefx/pull/12575 expressing these concerns.

**Comment by Miepee** [comment]
> Do you know how that is typically set?

XDG user directories are usually set in `XDG_CONFIG_HOME/user-dirs.dirs` (and `/etc/xdg/user-dirs.dirs`, but that behaves slightly differently).
Any Desktop Environment that's XDG compliant (which is to say most of them) will create the file and fill it out with appropriate values. This is how an example configuration can look like:
```
XDG_DESKTOP_DIR="$HOME/Schreibtisch"
XDG_DOCUMENTS_DIR="$HOME/Dokumente/"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_MUSIC_DIR="$HOME/Musik"
XDG_PICTURES_DIR="$HOME/Bilder"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/Videos"
```
Variables that point to the Home directory (i.e. `XDG_TEMPLATES_DIR`) are considered [disabled](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/).

If a user wants to use custom directories they can go ahead and edit the file (either manually, via their system settings or with `xdg-user-dirs-update`). Since these aren't actually environment variables, a user could also create an environment variables with that name, which would take priority over the config files. For example, launching `XDG_PICTURES_DIR="~/myTestingFolder" ./dotnetPrintPicturesDirProgram` would change my pictures directory only for `dotnetPrintPicturesDirProgram` to `~/myTestingFolder` while all other programs would still use `~/Bilder`.

**Comment by danmoseley** [comment]
> will create the file and fill it out with appropriate values

Hmm, so we cannot use the presence of a `XDG_DOCUMENTS_DIR` value as evidence the user wants it. Hmm, I think I'd be inclined to support the change (we are a side-by-side install) but I'd like to hear other folks' input such as owners of this area.

cc @marklio who perhaps can think of some way we can use data to make a decision.

**Comment by Miepee** [comment]
Is there any progress or new info on this issue?
If there's none, then I'd like to do a PR that fixes the assignments for Documents (Linux) and Movies/ApplicationData/LocalApplicationData (MacOS), and open a separate issue for the other fields which are wrong, including ios/tvOS+Android. (If there are any there. I haven't checked that yet.)

**Comment by RayKoopa** [comment]
Great issue. I'm coming from a [discussion](https://github.com/dotnet/runtime/issues/554) also touching the `SpecialFolder` topic, having noticed the irregular behavior as you described aswell:

- Personally backing you here in fixing `MyDocuments` / `Personal` to point to `<home>/Documents` (via `XDG_DOCUMENTS_DIR` on Linux) rather than just `<home>`. I suppose this "hickup" happened due to "`Personal`" sounding like the home dir. But given the XML summary already mentioning the Documents folder, its origin being the Windows CSIDL name, and the comment on it in `ShlObj_core.h`...
  ```c
  #define CSIDL_PERSONAL                  0x0005        // My Documents
  #define CSIDL_MYDOCUMENTS               CSIDL_PERSONAL //  Personal was just a silly name for My Documents
  ```
  ...it really should be the "Documents" folder.
Of course, changing this would break code on Linux/macOS assuming other special home folders that are not yet covered in `SpecialFolder` as `Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Downloads")`, for example. But that is an incorrect assumption anyway and where I jump in by properly introducing those folders to `SpecialFolder` in https://github.com/dotnet/runtime/issues/554#issuecomment-1107636092, at least for "Downloads" and "Public".

- Also personally backing you in fixing `MyVideos` to point to `~/Movies` on macOS, and not `~/Videos`, that's just incorrect.

- Additionally, I also noticed that [`XDG` variables are being queried on macOS](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L102) for `Desktop` / `Templates` / `MyVideos`, despite them not existing there.  Since there already is a [preprocessor block](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L110) for special OSX handling, these folders should be queried without XDG and like the others in there.

Since you've already given a lot of thought in fixing the existing `SpecialFolder` paths cross-platform, and I've separately checked the new additions, I suppose it would be great to handle these as separate PRs despite the slightly overlapping topic (given I need an API Proposal for my additions anyway).

**Comment by danmoseley** [comment]
@Miepee do you want to offer that PR? I missed your reply earlier.

**Comment by Miepee** [comment]
Yep, I'll do that in a day or two when i get a little more time. Would also, as mentioned above, open a new issue for the other wrong less relevant SpecialFolder mappings.

**Comment by RayKoopa** [comment]
I hope I don't come along as a showstopper (I want this fix myself :-) ), but dug through related issues, PRs, and API proposals on this, and they make valid points on why this fix was rejected in the past. However, I cannot rate how important the points made are today:

- **2015-09-15** https://github.com/mono/mono/pull/2055
  - rejected as changing `MyDocuments` path would break existing apps
- **2016-10-12** https://github.com/dotnet/corefx/pull/12575
  - rejected as changing `MyDocuments` path would create incompatiblity between Mono and .NET Core
  - alternatively mentions obsoleting problematic enum values and adding new correct ones
    - but enum extensions would break code assuming it maps to CSIDLs on Windows
  - mentions deprecating whole SpecialFolder enum / API in favor of flexible new one
- **2016-10-21** https://github.com/dotnet/runtime/issues/19047 (API Proposal)
  - proposes said API, dropped by proposer due to missing interest
- **2021-12-30** https://github.com/dotnet/runtime/issues/63214 (Issue)
  - this issue, attempting to fix `MyDocuments` path again

(s. also my post at https://github.com/dotnet/runtime/issues/554#issuecomment-1107831878)

**Comment by Miepee** [comment]
From what I gathered from the short discussion above, this does seem like something that's wished for to be fixed as it's clearly wrong behaviour. However, the discussion here is also rather small compared to any of your listed ones.

@marklio was tagged above for further input on this but probably missed it.
