### ISSUE TITLE
An exception that "Could not find or load a specific file." is thrown when different versions of dependencies are loaded in the same domain.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#63213]
### Description

When I load different plug-ins into the same domain (the plug-ins have the same dependency name but different versions) the program throws an exception.

### Reproduction Steps

Library A  dependency Newtonsoft.Json 12.0.1

Library B  dependency Newtonsoft.Json 13.0.1

Fake code.
```C#

var randomAlc  = new MyAssemblyLoadContext("random");
var assm1 = randomAlc.LoadFromAssemblyPath( pluginA_DependencyWithJsonVersion1201 );

var assm2 = randomAlc.LoadFromAssemblyPath( pluginB_DependencyWithJsonVersion1301 );
var pTypeB =  assm2 .GetType()....;
var obj = Activetor.Create(pTypeB);
obj.Method();  //Throw Exception;
```
Alc Load:

```c#
protected override Assembly? Load(AssemblyName assemblyName)
{
       //var token = assemblyName.GetPublicKeyToken();
       //if (token != null && token.Length > 0)
       //{
            // return null;
      // }

      string? assemblyPath = _dependencyResolver!.ResolveAssemblyToPath(assemblyName);
      if (assemblyPath != null)
      {

            return  LoadFromAssemblyPath(assemblyPath);

      }
}
```

>  System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621)
---- System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.

### Expected behavior

Is there a way to allow users to select dependent file versions that have been loaded into the domain?

### Actual behavior

> System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621)
---- System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

### Other information

- Load an assembly with the same name and same version.  
- Load an assembly with the same name and diff version and same dependency(same version).  
- Load an assembly with the same name and diff version and same dependency(diff version).  
- Load an assembly with the diff name and same dependency(same version).  
- Load an assembly with the diff name and same dependency(diff version).  

What kind of exceptions will they throw?
In fact, I don't know much about the plug-in loading mechanism of .NET. I think this question is just the beginning. Does the official have a very detailed document on plug-in loading and dependency management?

**Comment by vitek-karas** [comment]
There's a guide on how to create a simple plugin app here: https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

Details on how ALCs work and how assembly loading works is here: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext

The short version: .NET 5+ doesn't support loading two different versions of the same assembly into the same `AssemblyLoadContext`. You can intercept loading by overriding the `AssemblyLoadContext.Load` method, but I would still suggest you don't resolve different versions into different assemblies as it may cause lot of confusion.
Much cleaner approach is to load each plugin into its own ALC - and it gets full isolation with no risk of version failures.

**Comment by NMSAzulX** [comment]
@vitek-karas  Thank you very much for your answer!  I am experimenting with letting developers make a choice if the plug-in dependencies loaded by ALC conflict with those in the default domain. So far, UT tests have told me that this solution is feasible. My plan is to determine whether the user wants the `AssemblyName` in the Load method, and if so, continue to load the assembly. Do you have any good suggestions for this plan?

FakeCode:

```c#
bool UserWantThisAsm(AssemblyName name)
{
    if(Alc.Default.FindName(name.Name)){  //.....return false or true  }
}


protected override Load(AssemblyName name)
{
     if(!UserWantThisAsm(name))
     {
           return null;
     }
     // Continue Load Others
}
```

**Comment by vitek-karas** [comment]
In general such approach is doable. The trouble will probably be the `Alc.Default.FindName`. Currently there's no such thing.
The closest is to call `Alc.Default.LoadFromAssemblyName`, but that will throw on failure. There's no `TryLoadFromAssemblyName` available.

Please do NOT rely on `Alc.Default.Assemblies` that returns the currently loaded assemblies. And so if nobody asked for that assembly yet, it won't be there, even though the default ALC might load in the future.

In general we recommend that plugins declare this at build time. Actually the cleaner approach is for the host to specify what it provides to the plugins: "These are the assemblies (and versions) which the host will have available in the default ALC and plugins are free to use them". This should include the framework and the assemblies containing the types which are used to communicate with the plugins. It can include more if needed, but it doesn't need to include all of the assemblies the host will have (in order to isolate it from the plugins).
And then at build time, the plugins declare the references correctly by either shipping the assembly with the plugin or not.

You can obviously add the additional layer of protection by checking this list at runtime in the ALC.Load override.

Personally I would not recommend to allow the plugins to change their assembly sharing behavior at runtime (dynamically), it will be really hard to debug if things go wrong. But I don't know your requirements.

**Comment by NMSAzulX** [comment]
Thank you for your advice! It is of great help to me.
