### ISSUE TITLE
Linux only:  The type initializer for 'System.Net.CookieContainer' threw an exception.

### ISSUE THREAD

**Issue by RodDaSilva** [dotnet/runtime#63228]
I have a program that is intended to run cross platform on Windows, and Linux from the same code base.  I build with .Net 6.0 on Windows and then publish with the following command to create my Windows and  Linux versions:

**dotnet publish -r win-x64 --self-contained  -c Debug**
**dotnet publish -r linux-x64 --self-contained  -c Debug**

The program runs fine on Windows but when I attempt to run it on Linux (WSL2 if that matters) I get the error:

**---> System.TypeInitializationException: The type initializer for 'System.Net.CookieContainer' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'iphlpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libiphlpapi.dll: cannot open shared object file: No such file or directory
at Interop.IpHlpApi.GetNetworkParams(IntPtr pFixedInfo, UInt32& pOutBufLen)
   at System.Net.NetworkInformation.HostInformationPal.GetFixedInfo()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Net.NetworkInformation.HostInformationPal.get_FixedInfo()
   at System.Net.CookieContainer.CreateFqdnMyDomain()
   at System.Net.CookieContainer..cctor()
   --- End of inner exception stack trace ---
   at System.Net.CookieContainer..ctor()
   at System.Net.Http.HttpConnectionSettings.CloneAndNormalize()
   at System.Net.Http.SocketsHttpHandler.SetupHandlerChain()
   at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at UnoSys.Core.HostCryptology.RawSecureApiCall(String callUriTemplate, Int32 op, String payload, Guid sourceID, String targetAsymmetricPublicKey, String sourceAsymmetricPrivateKey, Byte[]& key, Byte[]& iv)
   at UnoSys.Core.HostCryptology.SecureApiCall(String callUriTemplate, Int32 op, String payload, Guid sourceID, String targetAsymmetricPublicKey, String sourceAsymmetricPrivateKey)**

As per the error message I have enabled LD_DEBUG and I get the output below right before the error occurs.

I went looking for the source code to **System.Net.NetworkInformation.HostInformationPal.GetFixedInfo()** to see if I could see what is going on here, but couldn't find it.

Is there supposed to be **iphlpapi.dll.so** file as part of the generated published files?  

I have been working on this for a couple of days now with no progress.  Any help would be appreciated.

Thanks,
Rod

     20551:     file=/mnt/c/Users/Administrator/wcnode/publish/iphlpapi.dll.so [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     symbol=strerror;  lookup in file=./wcnode [0]
     20551:     symbol=strerror;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     20551:     symbol=strerror;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     20551:     symbol=strerror;  lookup in file=/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
     20551:     symbol=strerror;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
     20551:     symbol=strerror;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
     20551:     symbol=strerror;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
     20551:     binding file /lib/x86_64-linux-gnu/libdl.so.2 [0] to /lib/x86_64-linux-gnu/libc.so.6 [0]: normal symbol `strerror' [GLIBC_2.2.5]
     20551:     symbol=__dcgettext;  lookup in file=./wcnode [0]
     20551:     symbol=__dcgettext;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     20551:     symbol=__dcgettext;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     20551:     symbol=__dcgettext;  lookup in file=/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
     20551:     symbol=__dcgettext;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
     20551:     symbol=__dcgettext;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
     20551:     symbol=__dcgettext;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
     20551:     binding file /lib/x86_64-linux-gnu/libdl.so.2 [0] to /lib/x86_64-linux-gnu/libc.so.6 [0]: normal symbol `__dcgettext' [GLIBC_2.2.5]
     20551:     symbol=__asprintf;  lookup in file=./wcnode [0]
     20551:     symbol=__asprintf;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     20551:     symbol=__asprintf;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     20551:     symbol=__asprintf;  lookup in file=/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
     20551:     symbol=__asprintf;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
     20551:     symbol=__asprintf;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
     20551:     symbol=__asprintf;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
     20551:     binding file /lib/x86_64-linux-gnu/libdl.so.2 [0] to /lib/x86_64-linux-gnu/libc.so.6 [0]: normal symbol `__asprintf' [GLIBC_2.2.5]
     20551:
     20551:     file=iphlpapi.dll.so [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     find library=iphlpapi.dll.so [0]; searching
     20551:      search cache=/etc/ld.so.cache
     20551:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
     20551:       trying file=/lib/x86_64-linux-gnu/iphlpapi.dll.so
     20551:       trying file=/usr/lib/x86_64-linux-gnu/iphlpapi.dll.so
     20551:       trying file=/lib/iphlpapi.dll.so
     20551:       trying file=/usr/lib/iphlpapi.dll.so
     20551:
     20551:
     20551:     file=/mnt/c/Users/Administrator/wcnode/publish/libiphlpapi.dll.so [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:
     20551:     file=libiphlpapi.dll.so [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     find library=libiphlpapi.dll.so [0]; searching
     20551:      search cache=/etc/ld.so.cache
     20551:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
     20551:       trying file=/lib/x86_64-linux-gnu/libiphlpapi.dll.so
     20551:       trying file=/usr/lib/x86_64-linux-gnu/libiphlpapi.dll.so
     20551:       trying file=/lib/libiphlpapi.dll.so
     20551:       trying file=/usr/lib/libiphlpapi.dll.so
     20551:
     20551:
     20551:     file=/mnt/c/Users/Administrator/wcnode/publish/iphlpapi.dll [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:
     20551:     file=iphlpapi.dll [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     find library=iphlpapi.dll [0]; searching
     20551:      search cache=/etc/ld.so.cache
     20551:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
     20551:       trying file=/lib/x86_64-linux-gnu/iphlpapi.dll
     20551:       trying file=/usr/lib/x86_64-linux-gnu/iphlpapi.dll
     20551:       trying file=/lib/iphlpapi.dll
     20551:       trying file=/usr/lib/iphlpapi.dll
     20551:
     20551:
     20551:     file=/mnt/c/Users/Administrator/wcnode/publish/libiphlpapi.dll [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:
     20551:     file=libiphlpapi.dll [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     find library=libiphlpapi.dll [0]; searching
     20551:      search cache=/etc/ld.so.cache
     20551:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
     20551:       trying file=/lib/x86_64-linux-gnu/libiphlpapi.dll
     20551:       trying file=/usr/lib/x86_64-linux-gnu/libiphlpapi.dll
     20551:       trying file=/lib/libiphlpapi.dll
     20551:       trying file=/usr/lib/libiphlpapi.dll
     20551:
     20551:     symbol=_ZNK10__cxxabiv117__class_type_info11__do_upcastEPKS0_PKvRNS0_15__upcast_resultE;  lookup in file=./wcnode [0]
     20551:     symbol=_ZNK10__cxxabiv117__class_type_info11__do_upcastEPKS0_PKvRNS0_15__upcast_resultE;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     20551:     symbol=_ZNK10__cxxabiv117__class_type_info11__do_upcastEPKS0_PKvRNS0_15__upcast_resultE;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     20551:     symbol=_ZNK10__cxxabiv117__class_type_info11__do_upcastEPKS0_PKvRNS0_15__upcast_resultE;  lookup in file=/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
     20551:     binding file /lib/x86_64-linux-gnu/libstdc++.so.6 [0] to /lib/x86_64-linux-gnu/libstdc++.so.6 [0]: normal symbol `_ZNK10__cxxabiv117__class_type_info11__do_upcastEPKS0_PKvRNS0_15__upcast_resultE' [CXXABI_1.3]
     20551:
     20551:     file=Microsoft.DiaSymReader.Native.amd64.dll [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     find library=Microsoft.DiaSymReader.Native.amd64.dll [0]; searching
     20551:      search cache=/etc/ld.so.cache
     20551:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
     20551:       trying file=/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
     20551:       trying file=/usr/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
     20551:       trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
     20551:       trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
     20551:
     20551:
     20551:     file=/mnt/c/Users/Administrator/wcnode/publish/Microsoft.DiaSymReader.Native.amd64.dll [0];  dynamically loaded by /mnt/c/Users/Administrator/wcnode/publish/libcoreclr.so [0]
     20551:     symbol=SystemNative_LStat;  lookup in file=/mnt/c/Users/Administrator/wcnode/publish/libSystem.Native.so [0]
     20551:     binding file /mnt/c/Users/Administrator/wcnode/publish/libSystem.Native.so [0] to /mnt/c/Users/Administrator/wcnode/publish/libSystem.Native.so [0]: normal symbol `SystemNative_LStat'

**Comment by RodDaSilva** [comment]
I don't believe I have write permissions so if you could add the following area tag I would appreciate.

area-System.Net

**Comment by danmoseley** [comment]
It seems to be running a Windows version of the code.

**Comment by jkotas** [comment]
The problem you are seeing is caused by using Windows runtime binaries on Linux.

It is not possible to have one self-contained app binaries that run on both Windows and Linux. The self-contained apps are always platform specific. You need to have one separate self-contained per platform.

**Comment by RodDaSilvaWCO** [comment]
I agree.  I am trying to figure out how that is possible.   So what I am not telling you is that the application that is running dynamically compiles a C# source file into an assembly using the Roslyn APIs and then dynamically loads it and executes it.  It actually gets quite far along before the error occurs (i.e.; the code is compiled and is loaded and is running).   In fact it is not until the code attempts a network call (i.e.; a REST call) that it hits the reported problem with **System.Net.CookieContainer**

Now to compile with Roslyn you have to provide a List of compiler reference assemblies.  Because I want to make the application completely "self contained" under my own control, I have added all of the dependencies the app requires (both compile time and runtime) to the application itself as embedded resources.  (I am aware .NET supports creating single EXE output but I need more control so I am rolling my own).  Since the app was authored in Windows those assemblies are all coming from the win-x64 folder.  However to my knowledge the assemblies are all managed assemblies (i.e.; nothing native), so they should be portable to any .NET environment.

From the dump above, and from your comment, it appears I must have a platform specific assembly in there somewhere, but can't figure out which one.  Compile time appears to be fine since I am building against "reference only" assemblies, and because the resultant dynamically compiled assembly loads and is being executed at the time of the error.  So I suspect the issue is with the runtime assemblies.  I provide the list of assemblies my application uses (its extensive) at the end of this post.  Can anyone spot an assembly that is _platform specific_ that would lead to the error above?  For example am I right in my assumption that there is only a single  **System.Net.NetworkInformation.dll** for all of the .NET platforms - i.e.; that it is portable?  I have assumed all of the assemblies in the following list are in fact portable with any platform differences being handled with runtime environment checks.  

Thanks,
Rod

 10/26/2021  04:53 PM           100,480 Microsoft.AspNetCore.Antiforgery.dll
10/26/2021  04:53 PM            52,848 Microsoft.AspNetCore.Authentication.Abstractions.dll
10/26/2021  04:53 PM            79,472 Microsoft.AspNetCore.Authentication.Core.dll
10/26/2021  04:53 PM           144,512 Microsoft.AspNetCore.Authentication.dll
10/26/2021  04:53 PM            86,120 Microsoft.AspNetCore.Authorization.dll
10/26/2021  04:53 PM            56,424 Microsoft.AspNetCore.Authorization.Policy.dll
10/26/2021  04:53 PM           552,576 Microsoft.AspNetCore.Components.dll
10/26/2021  04:53 PM           284,800 Microsoft.AspNetCore.Components.Web.dll
10/26/2021  04:53 PM            64,640 Microsoft.AspNetCore.Connections.Abstractions.dll
10/26/2021  04:53 PM            78,976 Microsoft.AspNetCore.Cors.dll
10/26/2021  04:53 PM            66,664 Microsoft.AspNetCore.Cryptography.Internal.dll
10/26/2021  04:53 PM            39,016 Microsoft.AspNetCore.DataProtection.Abstractions.dll
10/26/2021  04:53 PM           415,872 Microsoft.AspNetCore.DataProtection.dll
10/26/2021  04:53 PM           393,856 Microsoft.AspNetCore.Diagnostics.dll
10/26/2021  04:53 PM           101,992 Microsoft.AspNetCore.dll
10/26/2021  04:53 PM            35,944 Microsoft.AspNetCore.HostFiltering.dll
10/26/2021  04:53 PM            32,896 Microsoft.AspNetCore.Hosting.Abstractions.dll
10/26/2021  04:53 PM           379,008 Microsoft.AspNetCore.Hosting.dll
10/26/2021  04:53 PM            19,048 Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
10/26/2021  04:53 PM            30,848 Microsoft.AspNetCore.Html.Abstractions.dll
10/26/2021  04:53 PM           223,848 Microsoft.AspNetCore.Http.Abstractions.dll
10/26/2021  04:53 PM           260,224 Microsoft.AspNetCore.Http.dll
10/26/2021  04:53 PM           304,768 Microsoft.AspNetCore.Http.Extensions.dll
10/26/2021  04:53 PM            57,984 Microsoft.AspNetCore.Http.Features.dll
10/26/2021  04:53 PM            63,104 Microsoft.AspNetCore.HttpOverrides.dll
10/26/2021  04:53 PM            40,064 Microsoft.AspNetCore.HttpsPolicy.dll
10/26/2021  04:53 PM            17,024 Microsoft.AspNetCore.Metadata.dll
10/26/2021  04:53 PM           202,368 Microsoft.AspNetCore.Mvc.Abstractions.dll
10/26/2021  04:53 PM           139,888 Microsoft.AspNetCore.Mvc.ApiExplorer.dll
10/26/2021  04:53 PM         1,881,216 Microsoft.AspNetCore.Mvc.Core.dll
10/26/2021  04:53 PM            45,184 Microsoft.AspNetCore.Mvc.Cors.dll
10/26/2021  04:53 PM           102,512 Microsoft.AspNetCore.Mvc.DataAnnotations.dll
10/26/2021  04:53 PM            31,872 Microsoft.AspNetCore.Mvc.dll
10/26/2021  04:53 PM           239,744 Microsoft.AspNetCore.Mvc.Razor.dll
10/26/2021  04:53 PM           450,176 Microsoft.AspNetCore.Mvc.RazorPages.dll
10/26/2021  04:53 PM           275,584 Microsoft.AspNetCore.Mvc.TagHelpers.dll
10/26/2021  04:53 PM           791,168 Microsoft.AspNetCore.Mvc.ViewFeatures.dll
10/26/2021  04:53 PM            61,568 Microsoft.AspNetCore.Razor.dll
10/26/2021  04:53 PM            62,592 Microsoft.AspNetCore.Razor.Runtime.dll
10/26/2021  04:53 PM            52,328 Microsoft.AspNetCore.Routing.Abstractions.dll
10/26/2021  04:53 PM           736,896 Microsoft.AspNetCore.Routing.dll
10/26/2021  04:53 PM           601,216 Microsoft.AspNetCore.Server.IIS.dll
10/26/2021  04:53 PM            43,112 Microsoft.AspNetCore.Server.IISIntegration.dll
10/26/2021  04:53 PM         2,076,264 Microsoft.AspNetCore.Server.Kestrel.Core.dll
10/26/2021  04:53 PM            22,656 Microsoft.AspNetCore.Server.Kestrel.dll
10/26/2021  04:53 PM           209,536 Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll
10/26/2021  04:53 PM           148,072 Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
10/26/2021  04:53 PM           245,888 Microsoft.AspNetCore.WebUtilities.dll
10/26/2021  04:52 PM            44,672 Microsoft.Extensions.Caching.Abstractions.dll
10/26/2021  04:52 PM            75,392 Microsoft.Extensions.Caching.Memory.dll
10/26/2021  04:52 PM            37,504 Microsoft.Extensions.Configuration.Abstractions.dll
10/26/2021  04:52 PM            58,984 Microsoft.Extensions.Configuration.Binder.dll
10/22/2021  06:50 PM            23,152 Microsoft.Extensions.Configuration.CommandLine.dll
10/26/2021  04:52 PM            69,736 Microsoft.Extensions.Configuration.dll
10/26/2021  04:52 PM            23,656 Microsoft.Extensions.Configuration.EnvironmentVariables.dll
10/26/2021  04:52 PM            39,016 Microsoft.Extensions.Configuration.FileExtensions.dll
10/26/2021  04:52 PM            37,992 Microsoft.Extensions.Configuration.Json.dll
10/22/2021  06:50 PM            24,688 Microsoft.Extensions.Configuration.UserSecrets.dll
10/26/2021  04:52 PM            82,560 Microsoft.Extensions.DependencyInjection.Abstractions.dll
10/26/2021  04:52 PM           191,088 Microsoft.Extensions.DependencyInjection.dll
10/26/2021  04:53 PM            30,848 Microsoft.Extensions.Features.dll
10/26/2021  04:52 PM            27,240 Microsoft.Extensions.FileProviders.Abstractions.dll
10/26/2021  04:52 PM            81,536 Microsoft.Extensions.FileProviders.Physical.dll
10/26/2021  04:52 PM            92,264 Microsoft.Extensions.FileSystemGlobbing.dll
10/26/2021  04:52 PM            43,136 Microsoft.Extensions.Hosting.Abstractions.dll
10/26/2021  04:52 PM           108,672 Microsoft.Extensions.Hosting.dll
10/26/2021  04:53 PM           420,968 Microsoft.Extensions.Identity.Core.dll
10/26/2021  04:53 PM            74,344 Microsoft.Extensions.Identity.Stores.dll
10/26/2021  04:53 PM            22,656 Microsoft.Extensions.Localization.Abstractions.dll
10/26/2021  04:52 PM           135,808 Microsoft.Extensions.Logging.Abstractions.dll
10/26/2021  04:52 PM            38,528 Microsoft.Extensions.Logging.Configuration.dll
10/26/2021  04:52 PM            97,408 Microsoft.Extensions.Logging.Console.dll
10/26/2021  04:52 PM            21,120 Microsoft.Extensions.Logging.Debug.dll
10/26/2021  04:52 PM            86,656 Microsoft.Extensions.Logging.dll
10/26/2021  04:52 PM            35,944 Microsoft.Extensions.Logging.EventLog.dll
10/26/2021  04:52 PM            53,352 Microsoft.Extensions.Logging.EventSource.dll
10/26/2021  04:53 PM            31,360 Microsoft.Extensions.ObjectPool.dll
10/26/2021  04:52 PM            31,856 Microsoft.Extensions.Options.ConfigurationExtensions.dll
10/26/2021  04:52 PM           115,816 Microsoft.Extensions.Options.dll
10/26/2021  04:52 PM            74,880 Microsoft.Extensions.Primitives.dll
10/26/2021  04:53 PM            29,824 Microsoft.Extensions.WebEncoders.dll
12/02/2021  01:52 PM            30,072 Microsoft.IdentityModel.Logging.dll
10/26/2021  04:53 PM           130,176 Microsoft.JSInterop.dll
10/26/2021  04:53 PM           216,704 Microsoft.Net.Http.Headers.dll
10/22/2021  07:08 PM            25,200 Microsoft.Win32.Primitives.dll
10/22/2021  07:08 PM            86,640 Microsoft.Win32.Registry.dll
10/22/2021  06:44 PM           100,480 netstandard.dll
10/22/2021  07:08 PM           245,872 System.Collections.Concurrent.dll
10/22/2021  07:08 PM           665,200 System.Collections.Immutable.dll
10/22/2021  07:08 PM            99,952 System.Collections.NonGeneric.dll
10/22/2021  07:08 PM            94,320 System.Collections.Specialized.dll
10/22/2021  07:08 PM           184,944 System.ComponentModel.Annotations.dll
10/22/2021  07:08 PM            17,520 System.ComponentModel.dll
10/22/2021  07:08 PM            74,352 System.ComponentModel.Primitives.dll
10/22/2021  07:08 PM           743,536 System.ComponentModel.TypeConverter.dll
10/22/2021  06:44 PM            14,976 System.Diagnostics.Debug.dll
10/22/2021  07:08 PM           379,504 System.Diagnostics.DiagnosticSource.dll
10/26/2021  04:52 PM           305,776 System.Diagnostics.EventLog.dll
10/22/2021  07:08 PM           289,392 System.Diagnostics.Process.dll
10/22/2021  07:08 PM            35,440 System.Diagnostics.StackTrace.dll
10/22/2021  06:44 PM            15,488 System.Diagnostics.Tracing.dll
10/22/2021  07:08 PM           196,208 System.Formats.Asn1.dll
10/22/2021  06:44 PM            14,976 System.Globalization.dll
10/22/2021  06:44 PM            23,168 System.IO.FileSystem.dll
10/22/2021  07:09 PM            71,280 System.IO.FileSystem.Watcher.dll
10/26/2021  04:52 PM           190,056 System.IO.Pipelines.dll
10/22/2021  07:09 PM           536,688 System.Linq.dll
10/22/2021  07:09 PM         3,855,984 System.Linq.Expressions.dll
10/22/2021  07:09 PM         1,798,768 System.Net.Http.dll
10/22/2021  07:09 PM           638,064 System.Net.HttpListener.dll
10/22/2021  07:09 PM            99,952 System.Net.NameResolution.dll
10/22/2021  07:09 PM           149,104 System.Net.NetworkInformation.dll
10/22/2021  07:09 PM           213,104 System.Net.Primitives.dll
10/22/2021  07:09 PM           290,928 System.Net.Quic.dll
10/22/2021  07:10 PM           681,072 System.Net.Security.dll
10/22/2021  07:10 PM            35,952 System.Net.ServicePoint.dll
10/22/2021  07:10 PM           505,456 System.Net.Sockets.dll
10/22/2021  07:10 PM           180,848 System.Net.WebSockets.dll
10/22/2021  06:44 PM            14,976 System.Numerics.Vectors.dll
10/22/2021  07:10 PM            89,712 System.ObjectModel.dll
10/22/2021  07:10 PM           252,016 System.Private.Uri.dll
10/22/2021  07:10 PM         8,496,240 System.Private.Xml.dll
10/22/2021  07:10 PM           404,080 System.Private.Xml.Linq.dll
10/22/2021  06:44 PM            14,960 System.Reflection.Emit.ILGeneration.dll
10/22/2021  06:44 PM            14,976 System.Reflection.Emit.Lightweight.dll
10/22/2021  07:10 PM         1,129,584 System.Reflection.Metadata.dll
10/22/2021  06:44 PM            14,976 System.Reflection.Primitives.dll
10/22/2021  06:44 PM            14,976 System.Resources.ResourceManager.dll
10/22/2021  07:10 PM            21,616 System.Runtime.CompilerServices.Unsafe.dll
10/22/2021  06:44 PM            41,584 System.Runtime.dll
10/22/2021  06:44 PM            17,008 System.Runtime.Extensions.dll
10/22/2021  07:10 PM            30,832 System.Runtime.InteropServices.RuntimeInformation.dll
10/22/2021  06:44 PM            15,472 System.Runtime.Intrinsics.dll
10/22/2021  07:10 PM           220,784 System.Runtime.Numerics.dll
10/22/2021  07:11 PM            93,296 System.Security.Claims.dll
10/22/2021  07:11 PM           484,464 System.Security.Cryptography.Cng.dll
10/22/2021  07:11 PM           188,528 System.Security.Cryptography.Csp.dll
10/22/2021  07:11 PM            92,784 System.Security.Cryptography.Encoding.dll
10/22/2021  07:11 PM           485,488 System.Security.Cryptography.X509Certificates.dll
10/22/2021  07:11 PM           150,640 System.Security.Principal.Windows.dll
10/22/2021  06:44 PM            14,976 System.Text.Encoding.Extensions.dll
10/22/2021  07:11 PM           130,160 System.Text.Encodings.Web.dll
10/22/2021  07:11 PM         1,482,864 System.Text.Json.dll
10/22/2021  06:44 PM            14,960 System.Threading.Overlapped.dll
10/22/2021  07:11 PM           504,432 System.Threading.Tasks.Dataflow.dll
10/22/2021  06:44 PM            15,976 System.Threading.Tasks.dll
10/22/2021  07:11 PM           137,840 System.Threading.Tasks.Parallel.dll
10/22/2021  06:44 PM            14,960 System.Threading.Thread.dll
10/22/2021  06:44 PM            14,960 System.Threading.ThreadPool.dll
10/22/2021  06:44 PM            21,120 System.Xml.ReaderWriter.dll
10/22/2021  06:44 PM            14,952 System.Xml.XDocument.dll

**Comment by jkotas** [comment]
> However to my knowledge the assemblies are all managed assemblies (i.e.; nothing native), so they should be portable to any .NET environment.

That's not correct. Managed assemblies can be platform specific. System.Net.NetworkInformation.dll is an example of an assembly that is compiled as platform specific. There is a different one for each platform.

**Comment by RodDaSilvaWCO** [comment]
Ah...that explains what I am seeing then.  Do you know how I can determine if an assembly is platform specific?  Is there a list of them somewhere?  I would hate to have to provide sets of assemblies for each environment if many/most are not platform specific.

**Comment by RodDaSilvaWCO** [comment]
When I create a self-contained app on Windows targeting Linux with:

**dotnet publish -r linux-x64 --self-contained**

Where do the assemblies come from that end up in the **publish** folder?

**Comment by jkotas** [comment]
> Do you know how I can determine if an assembly is platform specific? 

There is no way to determine it reliably by looking at the assembly. It is determined by the nuget package metadata that the assembly came from.

> Where do the assemblies come from that end up in the publish folder?

They come from https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.linux-x64/ nuget package

> I can attempt to do the needed file compares on each managed assembly to figure out which ones are platform specific.

All binaries in the https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.linux-x64/ nuget package are platform-specific.

**Comment by RodDaSilva** [comment]
Thank-you very much for the information!
