### ISSUE TITLE
When an assembly load fails, include detailed error information in the exception

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#63233]
Debugging assembly load failures can be a bit tricky (euphemism for being extremely frustrating) because the exception contains so little detail. Is it feasible to make it more descriptive?

I understand there's tracing available to debug this (https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/collect-details). It's quite a bit of work to do this, though, and it's hard to do in production.

The exception should include:

* The paths that were examined
* What's wrong with a file encountered (like wrong bitness)
* Conflicts with already loaded assemblies

If this is a performance problem it could be opt-in (e.g. `bool Assembly.DetailedLoggingEnabled`).

**Comment by agocke** [comment]
This would probably incur a perf penalty, but more importantly we would have to create some sort of logging system to gather this information. That's quite a lot of duplicated effort since the event tracing you linked basically does all that, at minimal overhead.

Overall, I don't think it's likely that we will do this.
