### ISSUE TITLE
Different codegen for ThrowHelper calls with and w/o MethodImplOptions.NoInlining option in .NET6

### ISSUE THREAD

**Issue by KeterSCP** [dotnet/runtime#63266]
I've been recently reading about ThrowHelper on https://docs.microsoft.com/en-us/windows/communitytoolkit/developer-tools/throwhelper and decided to check the codegen behind ThrowHelper calls in the sharplab using following code:

```c#
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

static void WithoutNoInliningAttr()
{
    var num = 10;
    ThrowHelper.ThrowArgumentNullException(nameof(num));
}

static void WithNoInliningAttr()
{
    var num = 10;
    ThrowHelper.ThrowArgumentNullExceptionNoInline(nameof(num));
}

public static class ThrowHelper
{
    [DoesNotReturn]
    public static void ThrowArgumentNullException(string paramName) => throw new ArgumentNullException(paramName);
        
    [DoesNotReturn]
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void ThrowArgumentNullExceptionNoInline(string paramName) => throw new ArgumentNullException(paramName);
}
```

Generated asm code:

WithoutNoInliningAttr
```asm
mov ecx, 1
mov edx, 0x1c49c030
call 0x725f8110
mov ecx, eax
call dword ptr [0x1c49c954]
int3
```

WithNoInliningAttr
```asm
mov ecx, [0x8adbe1c]
call dword ptr [0x1c49c964]
ret
```

I thought it was ok that we should explicitly set noinlining flag on methods until I checked version from .NET 5 by switching Roslyn branch in sharplab to some older one. Output was following:

WithoutNoInliningAttr
```asm
mov ecx, [0x94f6ecc]
call dword ptr [0xef1c988]
int3
```

WithNoInliningAttr
```asm
mov ecx, [0x94f6ecc]
call dword ptr [0xef1c998]
ret
```

I'm just starting to learn codegen in c# and i am curious if this is intended behavior? After checking some of the ThrowHelper classes in this repo I did not find any method with `NoInlining` flag. Sharplab link: https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcAMACOSB0AIgJZgDmAdgPYTDEDGE+AwlQCYCmAghWADYBPCMQgBudFlwEASgFcKdKBxZUoAB2J8OAJwDKOgG4MOY9BKQA2XABZsAdWLAAFlVnAAclQCSFPsQr+ZFzAwNoAFACU6ADe6Njx2AZg2tgUslDYALzYSJjiaAnYACpO2lQA7gASHHxqOvglZeVc2mTpHArusnx8AKIAHvQcanRUFGG8SlQAZhPpERH5AL5mGJY29o5Onj5+ARRBIeFRaLEFCUkpaRnZufmFjRXVtfWPza3tnd19g8OjFDtfP4OBMwFNZtcFstVnAAMxSKyIYqlJ41OraGJxBIAbUIVBMnmA0g4wFk2goAF0sfE4QiNm8Wm0lF8egMhiNiGMwngcGpkmD3GCOBEsgA+bDOJqpDjlbCMz4eb5sv6c8Z87QCoWLamFbA63H4iCE4mk8lU87xbEAWRJLjYXnUfDCNuc7Adaj4AHkOWMmIC9oEIubCrS8IjbAyPszFazfj6Ad4gRQQTzsOrNUoRZlxZKKtLZfLo11Y+z/mF01BBZnlkA

**Comment by SingleAccretion** [comment]
The compiler gets to know a method is a "throw helper" (no-return) by analyzing its body in a failed inlining attempt. Marking a method as `NoInlining` disqualifies it from this analysis outright and the compiler will not be able to learn that it is no-return.

Thus, the differences you observe are expected. For the `WithoutNoInliningAttr`:
```asm
IN0001: 000004 mov      ecx, 17
IN0002: 000009 mov      rdx, 0xD1FFAB1E
IN0003: 000013 call     CORINFO_HELP_STRCNS
IN0004: 000018 mov      rcx, rax
IN0005: 00001B call     ThrowHelper:ThrowArgumentNullException(System.String)
IN0006: 000020 int3     
```
The compiler recognized `ThrowArgumentNullException` as no-return and optimized the literal string load into a lazy one, anticipating that this path is rarely hit and it is not worth allocating a string on the heap for it right away. You can also see `int3` (and no `ret`) in the codegen here as the indication the compiler knows `ThrowArgumentNullException` will not return.

This exact flavor of "lazy string" optimization is somewhat recent, so that's why you don't see it in the older .NET Framework codegen.

> I thought it was ok that we should explicitly set noinlining flag on methods 

It is best practice to _not_ set `NoInlining` on throw helpers specifically.

Let me know if this answers your questions.

**Comment by KeterSCP** [comment]
Oh, I see now. Thanks @SingleAccretion, you’ve helped make it clearer
