### ISSUE TITLE
[API Proposal]: Fix inconsistencies with numeric/math related operations in `System` namespace

### ISSUE THREAD

**Issue by EternalClickbait** [dotnet/runtime#63279]
### Background and motivation

I'm currently working on a project that's using a lot of math related functions, and I've had lots of issues with inconsistencies between the classes `System.Math` and `System.MathF`. Both are supposed to be helper classes for doing math calculations, with `System.MathF` essentially being the `float` version of `System.Math`. There have been problems though, where `MathF` doesn't implement the functions from `Math`, or when they both implement the same function twice for the same type. Some examples:
* `Abs()`, `Min()` - Implemented for all numeric types in `Math`, and then again for `floats` in `MathF`
* `Clamp()` - Implemented in `Math` for all types, but not in `MathF`
* `Sqrt()`,  `Pow()` - Implemented separately in `Math` and `MathF` for `doubles` and `floats`, respectively

Since I'm using a lot of `float` math functions I tried to `static using System.MathF`, but I then ran into issues where functions like `Clamp` weren't defined. 
![image](https://user-images.githubusercontent.com/48875125/147519664-39a4ff2b-a219-44e3-bb19-d8d90625a986.png)
I then statically imported `System.Math` so I could access them, but this then caused ambiguous reference errors
![image](https://user-images.githubusercontent.com/48875125/147519714-6560ee2c-211e-41fd-bd6b-5b3d1e58bad0.png)

Another consideration is that almost no math operations are implemented for the `decimal` type - the only ones i have been able to find are `Ceiling()`, `Floor()`, and `Abs()`, with even simple power operations unimplemented.

### API Proposal

I propose to remove the `MathF` class, combining all numeric operations into the `Math` class, for all possible types that that operation type could be used. For example, the `Pow(x, y)` function (for raising `x` to the `y`'th should be implemented for `float`, `double` (as currently), but also for integer types as well (e.g. an `int` to the power of a `uint`) and the `decimal` type (such as in scientific computation use cases).

```C#
namespace System
{
    public static class Math
    {
        public float Pow(float x, float y);
        public double Pow(double x, double y);
        public float Pow(decimal x, float y);
        //etc...
    }
}
```

### API Usage

```C#
//Old code
using System;
float xf=0f, yf =0f;
float f = MathF.Pow(xf, yf);
double xd = 0d, yd = 0d;
double d = Math.Pow(xd, yd);
decimal xm = 0m, ym = 0m;
decimal m = ????;//No way to do xm ^ ym????

//New code
using static System.Math;
float xf=0f, yf =0f;
float f = Pow(xf, yf);
double xd = 0d, yd = 0d;
double d = Pow(xd, yd);
decimal xm = 0m, ym = 0m;
decimal m = Pow(xm, ym); //Precision go brrrrrrrr
```

### Alternative Designs

An alternative option would be to:
1. Move each function into it's own 'math' class, e.g. `System.Int32Math`, `System.SingleMath`, etc would each implement the respective math functions
2. The same as above, but into the type's own class - `System.Single` would implement all single-precision floating point numeric operations.

### Risks

This would have an impact on existing code due to class name/namespace changes, however this would not be a significant problem, as it is simply a matter of replacing every instance of `MathF` with `Math`, such as with Rider's "change all local XXX" or even a simple find-and-replace-string.

**Comment by Sergio0694** [comment]
> "The same as above, but into the type's own class - System.Single would implement all single-precision floating point numeric operations."

This is indeed the plan (although still leaving `Math` and `MathF` too for backcompat) for .NET 7, see [here](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/). Many (most?) of those APIs will become implicit interface methods then, so you'll be able to just do eg. `float.Sqrt(x)` and similar 🙂

**Comment by tannergooding** [comment]
> I propose to remove the MathF class, combining all numeric operations into the Math class

This is a non-starter. `MathF` was originally exposed because adding `float` overloads to the existing APIs in `Math` is a silent source breaking change. Image that you have code that does `double x = Math.Sqrt(5)`. Today, this calls the only overload available `Math.Sqrt(double)`. If you add `Math.Sqrt(float)` then that is preferred as `int->float` is preferrenced over `int->double`. This results in 2 different silent implicit conversions and changes the computed result leading to potential downstream bugs.

> , for all possible types that that operation type could be used. For example, the Pow(x, y) function (for raising x to the y'th should be implemented for float, double (as currently), but also for integer types as well (e.g. an int to the power of a uint) and the decimal type (such as in scientific computation use cases).

Many of these functions do not have "well-defined" behavior for all possible types or inputs (such as negative powers for `int` or undefined results for `int` or `decimal`). They would be very expensive and generally not recommended for use.|

> This is indeed the plan (although still leaving Math and MathF too for backcompat) for .NET 7, see here.

Sergio is correct here. With the introduction of `generic math` the interfaces will effectively expose APIs like `Sqrt` as static methods on the respective floating-point types and so `float.Sqrt(x)` will be possible. Given that `Math/MathF` are fairly unique to the "primitive types" and that other types including user-defined types and even other BCL types such as `Complex`, `BigInteger`, `DateTime`, etc expose their "operations" as `static methods` on the type; the general plan is for the same to be the "path forward" for the existing `Math/MathF` APIs and future additions.
