### ISSUE TITLE
OOB Library's AssemblyVersion is inconsistent between ref and src assemblies in servicing

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#63467]
When servicing a library that targets .NET Framework, we are bumping up the AssemblyVersion on the .NET Framework assemblies:

https://github.com/dotnet/runtime/blob/634dfa13d89800e629db86f0b947590fb0ffb077/eng/packaging.targets#L42-L44

However, this is only applying to the `src` project, because this logic is contained in `packaging.targets` which is only imported for the `src` project. For the `ref` project the AssemblyVersion is staying `6.0.0.0`, since this logic doesn't run and because the `ServicingVersion` is only defined in the `src` project.

I hit this problem because we have a test which was failing trying to load a serviced assembly:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

The reason this happened is because the `ref` assembly for `Microsoft.Extensions.Hosting` was being passed to the test, so the test was getting a reference to `Version=6.0.0.0`. But the `src` assembly is used at runtime, which is version `6.0.0.1`. No assembly binding redirect is getting generated for this reference because the test is the "top" of the dependency chain and no one else is referencing a lower version of `Microsoft.Extensions.Hosting`. So no redirect is getting generated.

This can also cause issues when a serviced library has a ProjectToProject reference to another serviced library. `Microsoft.Extensions.Hosting` references `Microsoft.Extensions.Configuration.UserSecrets`. The `Hosting` package version of `6.0.1` will reference the `UserSecrets` package version `6.0.1`. `UserSecrets v6.0.1` will contain the `6.0.0.1` netfx assembly. However `Hosting v6.0.1`'s netfx assembly will have a binary reference to `6.0.0.0` because that's what the `ref` assembly for `UserSecrets` is during our build.

In talking with @ericstj, we think the correct thing to do here is to ensure both the `ref` and `src` assemblies get the same AssemblyVersion during servicing.

@safern

**Comment by ViktorHofer** [comment]
@ericstj do you know if anyone started working on this? Based on https://github.com/dotnet/runtime/blob/e3860440c151897968eca2227ae98c1912580c44/eng/packaging.targets#L32-L46, it looks like the AssemblyVersion is still only set for the source project (because packaging.targets isn't imported in a ref project because it usually isn't packable).

Alternatively we could fix this by removing the out-of-band reference projects as they aren't shipping anymore anyways since NET6 which would have the added benefit of making the build graph smaller which has a positive impact on build times, solution file size, maintenance costs of the ref, etc.
