### ISSUE TITLE
Document the memory model guaranteed by dotnet/runtime runtimes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#63474]
We routinely run into questions about the coreclr / mono memory models and what model modern .NET code should be targeting.

ECMA specifies a memory model:
http://www.ecma-international.org/publications/standards/Ecma-335.htm
but it's mostly weaker than what's actually supported by the runtimes.

Joe Duffy wrote down a rough sketch of the model from the .NET Framework 2.0 days:
http://joeduffyblog.com/2007/11/10/clr-20-memory-model/
but that was a long time ago, and unofficial.

Igor Ostrovsky wrote two very nice articles about the memory model:
https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/december/csharp-the-csharp-memory-model-in-theory-and-practice
https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2
but that's also from a decade ago, and things have evolved.

We should:
1. Document the model we want developers to actually code to; that includes code generated by the C# compiler (e.g. it currently doesn't use volatile when caching things like delegates for lambdas into fields).  This could be in the Book of the Runtime (BOTR), on docs.microsoft.com, somewhere we can refer to as an official stance.
2. Fix up code in the repo to respect that model, removing volatile where it's no longer necessary and adding it where it is to conform.

**Comment by GSPP** [comment]
I just faced the case where I'm accessing the same memory mapped at two different addresses. It's a memory-mapped file based circular buffer. The implementation can be simplified by mapping the buffer two times back to back.

So I wonder what guarantees .NET makes in such a case.

**Comment by ericstj** [comment]
@stephentoub @danmoseley do you have a suggestion for a better area path where this expertise lies?

**Comment by stephentoub** [comment]
I'm not sure any is perfect, but area-CodeGen-coreclr is probably a good place to start.

**Comment by GSPP** [comment]
1. Is the "safe" event invocation `eventField?.Invoke()` actually thread-safe? ECMA says no, but I have seen this recommended in many places as being thread-safe. It's not safe under ECMA because the runtime is allowed to re-read a field.
2. What guarantees are there in case of unsafe casting between reference types (e.g. array and `RawArrayData`)? See [Document the behavior of the CLR when unsafe casts are used #6176](https://github.com/dotnet/runtime/issues/6176)
3. When retyping arrays and spans of value types, is that guaranteed to be safe? I'm thinking of aliasing assumptions that the JIT might make. A `byte[]` can't refer to the same memory as an `int[]` (except of course using `Unsafe.As`, see 2). What about spans (`Span<byte>` to a `Span<int>`)? A quick test shows that .NET 5 assumes that such arrays won't alias but spans might.

<hr>

For (3), here's my test code:

```csharp
[TestMethod]
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
public void AliasArray()
{
    Debugger.Break();

    var ba = GetArray<byte>();
    var ia = GetArray<int>();

    var sum = 0;
    for (int i = 0; i < ba.Length; i++)
    {
        sum += ba[i];
        ia[i] = 1; //write, uncomment this to see difference
        sum += ba[i];
    }

    GC.KeepAlive(sum);
}

[TestMethod]
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
public void AliasSpan()
{
    Debugger.Break();

    var ba = GetArray<byte>().AsSpan();
    var ia = GetArray<int>().AsSpan();

    var sum = 0;
    for (int i = 0; i < ba.Length; i++)
    {
        sum += ba[i];
        ia[i] = 1; //write, uncomment this to see difference
        sum += ba[i];
    }

    GC.KeepAlive(sum);
}

[MethodImpl(MethodImplOptions.NoOptimization)]
static T[] GetArray<T>() => new T[10];
```

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib .

**Comment by omariom** [comment]
[An example](https://github.com/dotnet/runtime/issues/6257) where having documented memory model would help.


[Another example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKDIAIBhOmgbxro7oGU6B9ANwDc7TiI7EUdALIAKHvwCUzapzpsVqzgLoBeOkLF0AvjRPUauDFACuYDN1aHiAZn0QANtgwBLdzDreAHb2/OTCGhxBIaThqlH6zrGc8fwo4WZAA===) asking for clarity.

**Comment by GSPP** [comment]
Do synchronization primitives (locks, events, tasks, ...) generate a barrier? Normally, the answer is yes. So if you call `Task.Result`, does it cause a full barrier? You could think "yes". But what if the task is already completed? Then, AFAIK, this just generates a volatile load (an acquire). So what synchronization APIs generate what barriers? It should be spelt out.

**Comment by VSadov** [comment]
I have a lot of context on this matter from various angles - from assumptions and guarantees in C# spec/compiler, to memory model invariants in the runtime (VM, GC, JIT), to how it translates to the native code (x64, arm, arm64).

I'd like to take this issue, if noone is already working on it.

**Comment by BruceForstall** [comment]
@VSadov I think it's safe to say it's yours.

**Comment by GSPP** [comment]
1. How do exceptions interplay with the memory model?
2. How do compilation relaxations and E-relaxed methods impact the guarantees being made?
 a. .NET supports the notion of relaxing the point where runtime exceptions are seen to occur. This can mean that, for example, an `IndexOutOfRangeException` is not observed at the point it is caused. This can change the writes to memory that actually occur before the exception (in sequential code). This claim might seem astonishing to some; it was to me, when I reported this as a codegen bug to Microsoft many years ago, to be told that it is by design.
b. An example of this is described in ECMA (https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf) at "VI.F.5.1 Hoisting checks out of a loop". Searching for "E-relax" or "CompilationRelaxations" delivers more results.
c. There is an open request to expose this facility more than before: https://github.com/dotnet/runtime/issues/8948. But a similar feature has existed before on .NET Framework. I can no longer find it, but I have reproduced it back then. Unless it has been removed from .NET Core (I find no evidence of that) it might still exist in the JIT.
d. A very approachable example of this is given in this comment: https://github.com/dotnet/runtime/issues/8948#issuecomment-329850023 (the hoisted null check on `o.someField`).
e. This means that right now, in practical code, there are surprisingly reduced guarantees about the order and actual occurrence of memory writes. This rarely manifests but, as I said, I reproduced it many years ago.
3. What form will the new specification take? Will it be more of an informal document posted "somewhere", or will existing documents such as ECMA be refreshed?

**Comment by KalleOlaviNiemitalo** [comment]
Based on <https://github.com/dotnet/csharpstandard/issues/366#issuecomment-909635912>, I think a new version of ECMA-335 is unlikely. I imagine the memory model documentation would be posted somewhere in <https://github.com/dotnet/runtime/tree/main/docs/design>.

**Comment by GSPP** [comment]
How do volatile loads and stores interact with the hardware? This discussion came up in

- https://github.com/dotnet/runtime/issues/6280

ECMA has the opinion that volatile accesses can access hardware registers. This means that volatile loads cannot be dropped or coalesced (e.g. `volatile int x; _ = x; _ = x;`).

Apparently, the JIT does just that, though. And @[VSadov](https://github.com/VSadov) just declared that this deviation from ECMA is acceptable.

If the .NET memory model is to be defined rigorously then this issue must be resolved.

**Comment by GSPP** [comment]
1. How does `StructLayout` interact with the memory model? If we have a `struct`

    struct S { long L1; int I1; int I2; }

And we use `Unsafe` to re-type it as `long`, will this work? You could say that the first field is long, so "yes". But the runtime is free to reorder fields in `Auto` layout structs. The reordering could be different based on the containing type or stack configuration (in other words, different each time).

2. Can I retype a `struct S { Object O; }` to a `struct S2 { IntPtr I; }` and write to it a reference to a pinned object? Can I write `IntPtr.Zero`? Can I read `S2.I` and print the address for debugging purposes? Can I use vector instructions to read and write references?
3. Can I create an object reference to a piece of native memory that I have allocated and formatted as an object? ("Frozen segments"?)
4. What happens if I read past the end of an object but I don't cross a page boundary (no page fault)? I believe, `IndexOf` does that.
5. Can I read the object header in any way? Framework code does that.

**Comment by SingleAccretion** [comment]
> Can I retype a `struct S { Object O; }` to a `struct S2 { IntPtr I; }` and write to it a reference to a pinned object?

No, this will omit a write barrier.

>  Can I write IntPtr.Zero?

It is an implementation detail of CoreCLR that writing `null`s does not require barriers, I do not see this being codified however. In general, any kind of reinterpretation of `object`s should be assumed to be pure UB.

> Can I read S2.I and print the address for debugging purposes?

I suppose there is no meaning to an answer to this question, anything and everything can be done for debugging purposes.

> Can I use vector instructions to read and write references?

No. They aren't guaranteed to be atomic, at the very least.

> Can I create an object reference to a piece of native memory that I have allocated and formatted as an object?

No.

> What happens if I read past the end of an object but I don't cross a page boundary (no page fault)? I believe, IndexOf does that.

The behavior is undefined.

> Can I read the object header in any way? Framework code does that.

No. The header specifically cannot be read by managed code in a safe manner.

**Comment by KalleOlaviNiemitalo** [comment]
> But the runtime is free to reorder fields in Auto layout structs.

C# structs have sequential layout by default, though.

**Comment by SingleAccretion** [comment]
> But the runtime is free to reorder fields in `Auto` layout structs...

Indeed, so the behavior of reinterpreting them is undefined.

**Comment by Suchiman** [comment]
> C# structs have sequential layout by default, though.

Only as long as they have non GC fields though, even though the metadata says sequential, they become auto layout as soon as a GC field is added, [see](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoagNwEMoACAZw1zAzKYF4m8YAdyYAVGGwDK7HJwAUASgDc1AJJ4WABxicAdFPpgA1rLYcuS6nUatpnEr35DR4jFLMB1AJYYAFgHEAYQAlGAAzBWUqNU1tDD0MA2NTGQwSCxoqZM5nSVsMagBvaiYSpiIAZiZPPAwqlEjSssqAGwg8AHMqgA5IgF9LTLyc1zyvX0CQ0MLi0oqqmrqG2cqIYAArWO6+oA==)

**Comment by tfenise** [comment]
Is [this](https://source.dot.net/System.Text.RegularExpressions/R/e0984d67e2b81785.html) kind of usage documented and guaranteed to work on possibly future versions of .net?


```
/// <summary>Simple struct of four strings.</summary>
[StructLayout(LayoutKind.Sequential)]
private struct FourStackStrings // used to do the equivalent of: Span<string> strings = stackalloc string[4];
{
    public string Item1;
    public string Item2;
    public string Item3;
    public string Item4;
}

FourStackStrings stackStrings = default;
MemoryMarshal.CreateSpan(ref stackStrings.Item1!, 4)
```

As the struct contains reference types, `LayoutKind.Sequential` is not preserved. Theoretically speaking, the runtime could decide to put `public string Item1;` at the end of the struct rather than at the beginning of the struct, in which case the code would be broken.

**Comment by jkotas** [comment]
> Is [this](https://source.dot.net/System.Text.RegularExpressions/R/e0984d67e2b81785.html) kind of usage documented and guaranteed to work on possibly future versions of .net?

No. It is one of the motivations for https://github.com/dotnet/runtime/issues/61135 that makes this explicit.

**Comment by tfenise** [comment]
The example in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange?view=net-6.0#system-threading-interlocked-compareexchange(system-double@-system-double-system-double)) of `Interlocked.CompareExchange` has codes like following:

```
private double totalValue = 0.0;

public double AddToTotal(double addend)
{
    double initialValue, computedValue;
    do
    {
        // Save the current running total in a local variable.
        initialValue = totalValue;

        computedValue = initialValue + addend;
    }
    while (initialValue != Interlocked.CompareExchange(ref totalValue, computedValue, initialValue));
    return computedValue;
}
```

In ECMA-335 I.12.6.4:
> Conforming implementations of the CLI are free to execute programs using any technology that guarantees, within a single thread of execution, that side-effects and exceptions generated by a thread are visible in the order specified by the CIL. For this purpose only volatile operations (including volatile reads) constitute visible side-effects. (Note that while only volatile operations constitute visible side-effects, volatile operations also affect the visibility of non-volatile references.)

The read `initialValue = totalValue;` is not a volatile operation. By ECMA-335, it seems to be allowed that the local variable `initialValue` be eliminated and the program be transformed into:
```
public double AddToTotal(double addend)
{
    double computedValue;
    do
    {
        computedValue = totalValue + addend;
    }
    while (totalValue != Interlocked.CompareExchange(ref totalValue, computedValue, totalValue));
    return computedValue;
}
```
which would be broken.

The [implementation](https://source.dot.net/#System.Private.CoreLib/Interlocked.cs,200) of `Interlocked.And(ref long, long)` currently has similar problem. Although it is certainly acceptable that codes in the runtime itself relies on implementation details of the memory model of the runtime, they should be corrected if the coming documented memory model of the runtime declares them to be wrong.

**Comment by GSPP** [comment]
I'm referencing a thread about the memory model that is posing difficult questions with lively discussion:

- https://github.com/dotnet/runtime/issues/67330

**Comment by GSPP** [comment]
Referencing a thread about the properties of `TypedReference`. Multiple (knowledgable) people disagreed about the semantics with respect to GC tracking (in particular, [this comment](https://github.com/dotnet/runtime/issues/69321#issuecomment-1126348509) by @jaredpar). Might be worth addressing in an official way:

- https://github.com/dotnet/runtime/issues/69321

**Comment by jkotas** [comment]
> Referencing a thread about the properties of TypedReference

This has nothing to do with memory model that this issue is meant to be about.

**Comment by vladd** [comment]
@VSadov Maybe it's a good idea to make the drafts on the topic available (e. g. on GitHub) for the developers' early reference? (Just stumbled upon this discussion coming [from StackOverflow](https://stackoverflow.com/q/72527995/276994).)

**Comment by VSadov** [comment]
Thanks for reminding me. I will try to put up something next week.

**Comment by VSadov** [comment]
It is very much work in progress, but here is an early draft: https://github.com/VSadov/runtime/blob/memModel/docs/design/coreclr/botr/memory-model.md

**Comment by vladd** [comment]
@VSadov Thanks a lot for your effort!

One question about it all: the article is called "_CLR_ memory model". Does this mean that it doesn't describe the guarantees given by the _language_ itself, but rather only the guarantees which are given when using Microsoft CLR? Or other runtimes must give the same guarantees?

Another question: is there a canonical place to ask questions on the memory model and related issues?

**Comment by VSadov** [comment]
In theory languages running on CLR can implement their own memory model. In practice languages typically specify only grammar and single-threaded semantics and leave memory model issues to the runtime. 
C# in particular, rarely mentions threading in its documentation. Even the [`lock` statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock) is specified in terms of translation to `System.Threading.Monitor` calls. C# does specify [execution order](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#710-execution-order) and aliasing/atomicity of [variable references](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/variables#95-variable-references).

The memory model for a language like C# mostly affects what optimizations may be performed, as memory model tells what would be observable. As a result it makes a lot of sense to just assume and provide the memory model of the underlying runtime.

For example consider:

```cs
x += 1;
```

Can we emit the code as 

```cs
x = x + 1;  // evaluating x twice
```

or must do

```cs
ref var t = ref x;  // evaluating x once
t = t + 1;
```

The language spec says that 
```
compound assignment expression of the form x op= y is equivalent to x = (T)(x op y), 
except that x is only evaluated once.
```

However the CLR memory model would tell that if x is accessed only by a single thread, then introducing reads and writes is allowed as long as overal result is the same. Therefore if compiler sees that x is a local variable, then it can use simpler `x = x + 1` form.

FWIW, for the purpose of providing examples in the CLR memory model doc I am going to use C#, assuming a mainstream compiler targeting CLR will preserve the memory model. 

> does a variable in C# always correspond to a memory location in CLR? Does a read/write/initialization in C# always correspond to a load/store in CLR? It seems that the optimizer may remove the variables and introduce new variables at its discretion, so it's not easy to reason in CLR terms while programming in pure C#.

Typically compiler will treat its code generation strategy as an implementation detail, so that not be constrained if changes need to be made. There are obvious concept leaks in areas like cross-language  interop or when working with platform services like reflection.  
I think C# compilers guarantee the publicly observed shape of classes/structs (i.e. public field of a public C# class must be a public field of a public CLI class), but I am not sure if it is formally documented.  
@MadsTorgersen - if we can have more details here.

**Comment by VSadov** [comment]
> Another question: is there a canonical place to ask questions on the memory model and related issues?

It is just another feature in the runtime.

GitHub is an obvious place for bugs, feedback, documentation clarifications or discussions of in-progress items, but items here tend to have action oriented lifetime - Opened/Assigned/Closed... 
I am not sure if there is a place specifically for questions.

**Comment by danmoseley** [comment]
> I am not sure if there is a place specifically for questions.

We have https://github.com/dotnet/runtime/discussions. Note that the labeler/notifications do not work there, so if a question gets overlooked, you may have to @-mention the right person.

**Comment by vladd** [comment]
@VSadov I'm not sure if the code generation strategy can be seen just as implementation detail. An optimizing compiler can remove variables and rewrite the code completely, so the guarantees about the loads/stores into the memory locations on CLR level may have no counterpart on C# level.

Here is my favorite example: https://godbolt.org/z/YGGffzaab. The optimizing compiler removed the loop variable and the loop altogether, so there is no memory location corresponding to the loop variable at all.

Keeping this in mind, I find it complicated to reason about the memory locations because I cannot control if they are going to exist in the compiled code at all.

**Comment by EgorBo** [comment]
> I can control only C# variables, but not whether the said variables would generate a memory location.

isn't when `volatile` enters the game?

**Comment by VSadov** [comment]
> I'm not sure if the code generation strategy can be seen as just implementation detail.

This is a choice of language designers and depends on their goals. 
It is not even either-or choice. There could be some parts that are defined in terms of implementation (like `lock` is defined as a translation to `System.Threading.Monitor` calls) and some, like `x += 1` can be defined in terms of sideeffects.

As another example specifying a C# local variable to be always an IL local would be inconvenient. Sometimes a local can be optimized away and sometimes it needs to be a field in a display class or struct if local's lifetime needs to exceed the lexical scope that created the local (happens in lambda or async capturing cases). Not specifying a particular implementation for locals is certainly useful.

I think that fields are always emitted as fileds, but can't find it in any formal spec.

**Comment by vladd** [comment]
@VSadov I understand that the code generation is free to do whatever it wants with a variable, and that this freedom is advantageous for the better compiled code quality.

But then, as a developer I am having troubles reasoning in memory locations and loads/stores, because the actual existence of memory locations depends on the compiler's code generation strategy. What I would need is an ability to reason in terms of C# variables, and obtain memory model guarantees _in terms of the variables_.

(These guarantees might be not well-suited for runtime repository, though.)

**Comment by vladd** [comment]
> isn't when `volatile` enters the game?

Maybe volatile would guarantee that a C# variable corresponds to a memory location. My point is however that the developers usually need to think in variables, not in memory locations, and given that there is no direct mapping between them (runtime is free to elide the variables and introduce temporary variables or maybe reuse a memory location for different variables etc.) it would be advantageous to get the memory model expressed in terms of variables.

**Comment by jkotas** [comment]
> What I would need is an ability to reason in terms of C# variables, and obtain memory model guarantees in terms of the variables.

You can do this sort of reasoning for methods such as `Volatile.Read/Write` or `Interlock.*`, and volatile fields that are equivalent to `Volatile.Read/Write`. Otherwise, all ordinary variable are subject to be optimized out.

**Comment by vladd** [comment]
@jkotas At least there is a guarantee that an immutable _object_ doesn't need any `Volatile.*`/`Interlocked.*` operations to be correctly published, right? I mean, we don't need an explicit synchronization if an immutable object is read from another threads, no matter if variables get their memory locations or optimized out. This is (hopefully) implied by [Object assignment chapter](https://github.com/VSadov/runtime/blob/memModel/docs/design/coreclr/botr/memory-model.md#object-assignment).

So as a developer I don't need to think in memory locations at least in this case. This is a kind of guarantees I'm talking about.

**Comment by VSadov** [comment]
As far as I know C# makes the same assumptions about observability of accesses to variables that can be shared with other threads. Optimizations are only performed when they are unobservable. See example in https://github.com/dotnet/runtime/issues/63474#issuecomment-1160848251

Either a variable is not observable from multiple threads, and then it can only follow just single-threaded semantics, or it must be a field and it must follow the memory model that is basically the same as CLR memory model.

Is this enough of a "connection" that would allow applying CLR memory model to C# variables?

**Comment by VSadov** [comment]
>I mean, we don't need an explicit synchronization if an immutable object is read from another threads, no matter if variables get their memory locations or optimized out. This is (hopefully) implied by [Object assignment chapter](https://github.com/VSadov/runtime/blob/memModel/docs/design/coreclr/botr/memory-model.md#object-assignment).

Yes, as long as object is initialized before publishing (in program order).
C# compiler will not reorder field modifications past the publishing of the object, and then the "publish" will be a release.

This is a very common pattern when a shared instance is lazily initialized by threads that see the instance is `null`. The pattern does not need synchronization if identity of the instance is unimportant. (In a case of a race you may have >1 instances created and assigned)

**Comment by vladd** [comment]
> Either a variable is not observable from multiple threads, and then it can follow just single-threaded semantics, or it must be a field and it must follow the memory model that is basically the same as CLR memory model.
> 
> Is this enough of a "connection" that would allow applying CLR memory model to C# variables?

Thank you for this valuable addition! I think this _should_ be enough for connecting C# to the CLR memory model, but I'd prefer an opinion of language specialists more experienced then me.

Can I reformulate your point this way:

> 1. If a C# variable cannot be accessed from different threads, the optimizer is totally free to do any optimizations which preserve the single-threaded semantics
> 2. If a C# variable can potentially be accessed from several threads (e. g. it's a field or a local in an async method or in an iterator), then this variable is necessarily lowered as a field and corresponds to a memory location, so the guarantees from [CLR memory model](https://github.com/VSadov/runtime/blob/memModel/docs/design/coreclr/botr/memory-model.md) apply?
>     * In particular this means that any temporary variables crossing the await boundary cannot be elided in async methods, right?

?

**Comment by VSadov** [comment]
> Can I reformulate your point this way:

>> 1. If a C# variable cannot be accessed from different threads, the optimizer is totally free to do any optimizations which preserve the single-threaded semantics (see [Execution order](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#710-execution-order)).
>> 2. If a C# variable can potentially be accessed from several threads (e. g. it's a field or a local in an async method or in an iterator), then this variable is necessarily lowered as a field and corresponds to a memory location, so the guarantees from [CLR memory model](https://github.com/VSadov/runtime/blob/memModel/docs/design/coreclr/botr/memory-model.md) apply
>>     * In particular this means that in async methods, any temporary variables crossing the await boundary cannot be elided, right?

Yes.
Except that lambda capture would be a better example than iterator/async. 

yield/await do not imply sharing local variables with another thread. 
It is possible to see a different OS thread running the continuation after execution is resumed, when identity of the thread is unimportant, but there is only one thread accessing the locals in async method at a given time, so compiler will treat accesses as thread-local.

**Comment by vladd** [comment]
> yield/await do not imply sharing local variables with another thread. It is possible to see a different OS thread running the continuation after execution is resumed, when identity of the thread is unimportant, but there is only one thread accessing the locals in async method at a given time, so compiler will treat accesses as thread-local.

@VSadov That's an interesting topic. Is there really a guarantee that enumeration won't happen on different threads? I mean something like this:

```csharp
var en = seq.GetEnumerator();
Task.Run(Enumerate);
Task.Run(Enumerate);

void Enumerate()
{
    while (en.MoveNext())
        Console.WriteLine(en.Current);
}
```

With this code, `MoveNext()` will be most probably executed simultaneously on different threads. While the outcome might be undefined on the language level (is it? what does the language standard say about this?), the compiler needs to ensure at least some synchronization in order to keep the basic guarantees, right?

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/pull/75790
