### ISSUE TITLE
Net 6.0 assembly dynamic loading and (un)/reloading not possible anymore?

### ISSUE THREAD

**Issue by azuriteemporium** [dotnet/runtime#63509]
Following the deprecation of the AppDomain.CreateDomain method in Net 6.0, which could be used to reload dynamically a DLL assembly after it changed (creating a new app domain, then loading the assembly in that domain, and finally unloading the app domain when we want to reload the updated assembly), is there a way to achieve the same functionality?

Assembly.LoadFrom(path) does not reload the updated assembly unfortunately, by design.

https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.createdomain?view=net-6.0

**Comment by teo-tsirpanis** [comment]
Hello @azuriteemporium, yes you can (un)load assemblies on the fly in modern .NET through the [`System.Runtime.Loader.AssemblyLoadContext`](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext) class.

You have to keep in mind however that the way `AssemblyLoadContext` works is fundamentally different than AppDomains (it isolates only loading and not the objects, and unloading is cooperative rather than forceful), but I can assure you that the former is _much_ easier to work with.

**Comment by azuriteemporium** [comment]
Thank you for the quick answer @teo-tsirpanis !
That worked like a charm.
