### ISSUE TITLE
[API Proposal]: Expose Buffer.ZeroMemory(void*, nuint)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#63547]
### Background and motivation

`Buffer.ZeroMemory` is currently internal (why?). This API just tunnels to `SpanHelpers.ClearWithoutReferences`, which is otherwise only accessible through `new Span<byte>(void*, int).Clear()`. This has two drawbacks: it's arguably clunkier than just doing `Buffer.ZeroMemory(p, size)`, and (most importantly) caps the length of the buffer to `int`, which makes it immediately a no-go when dealing with larger buffers. This proposal is to make `Buffer.ZeroMemory` public to solve both issues.

### API Proposal

```C#
namespace System;

public static class Buffer
{
    public static void ZeroMemory(void* buffer, nuint sizeInBytes);
}
```

### API Usage

```C#
// When dealing with a short buffer

new Span<byte>(p, size).Clear(); // Before
Buffer.ZeroMemory(p, size); // After

// When dealing with a large buffer

// new Span<byte>(p, size).Clear(); // Unusable
Buffer.ZeroMemory(p, size); // Works just fine
```

### Risks

None that I can see, really.

**Comment by adamsitnik** [comment]
I like the idea of making `Buffer.ZeroMemory` public. 👍 @GrabYourPitchforks do you have any objections?

> For parity, there should be a public overload of Buffer.MemoryCopy taking the size as a nuint

What would be the gain? The following code compiles just fine:

```cs
nuint byteCount = nuint.MaxValue;
void* ptr = IntPtr.Zero.ToPointer();

Buffer.MemoryCopy(ptr, ptr, byteCount, byteCount);
```

And I can't see any scenario where we could loose some data by casting `nuint` to `ulong` on 32bit system.

@bartonjs do we have any guidance for adding `nint` and `nuint` method overloads?

**Comment by Sergio0694** [comment]
> "What would be the gain?"

The gain would be making it more consistent with other modern APIs (eg. all the ones in `NativeMemory`), technically more future proof and "correct" (ie. the point is not to have a 64bit value, but a native sized value), and possibly better to handle for the JIT, though not entirely sure on this last point (@SingleAccretion?). APIs taking `int`/`uint`/`long`/`ulong` to express sizes should really just remain a thing of the past, so I figured it'd be nice to add this one here to move in that direction. I'm sure @tannergooding will be able to argue for this point better than I possibly could though 😄

**Comment by bartonjs** [comment]
> do we have any guidance for adding nint and nuint method overloads?

`int` is the preferred numeric type in .NET unless there's a reason to pick something else.  That's about it as far as formal guidance, partially because `n(u)int` was added after we finished FDGv3.

If we already had 32 and 64 bit overloads then I could be convinced that adding an nuint overload would make sense, to avoid using a double-register on 32 bit systems... but we don't, it's just a 64-bit input (overloaded as signed and unsigned).

Since if casting isn't required then I'd guess the review process would say something like "this is just a stylistic overload that feels like it costs more in the size increase to System.Private.Corelib than it has benefit to the ecosystem".  But if (e.g.) Jan K wants to endorse it as good because of register allocations on 32-bit systems, then we'd nod and take his word on it.

**Comment by jkotas** [comment]
> But if (e.g.) Jan K wants to endorse it as good because of register allocations on 32-bit systems, then we'd nod and take his word on it.

The preferred way to copy and clear memory is `Span.TryCopyTo` and `Span.Clear`. I think the JIT is able to do a good job with registration allocation to make the Span overhead to disappear if you are starting with pointer and int size.

These overloads are working around the fact that Span length is `int` and not `nuint`. Do we believe that these are the only overloads in the BCL that need to be working around this similar? How many of other similar overloads we may add over time to work around this limitation?

**Comment by tannergooding** [comment]
> These overloads are working around the fact that Span length is int and not nuint. Do we believe that these are the only overloads in the BCL that need to be working around this similar? How many other similar overloads we may add over time to work around this limitation?

Ideally not a lot, I think we end up with "at most" 1 "nuint" alternative to each `Span` API.

That being said, an alternative would be to just expose `NativeSpan<T>`, possibly in .NET 7 if we are actually getting `ref` fields, and most of this just becomes "if you need 'big data', use NativeSpan<T>"`.
This would also have the benefit that `Span<T>` just "forwards" to `NativeSpan` internally (since its just a zero extension of span length, which is known positive).
-- You can also have the same "forwarding" in the case where we don't have `NativeSpan`; we just would need to decide where to centralize everything.

**Comment by tannergooding** [comment]
Noting that if we don't expose `NativeSpan<T>` and `ref fields` are a thing, then I can think of at least 3 different libraries that are likely going to roll their own as soon as `ref fields` are available.

**Comment by Sergio0694** [comment]
I've updated the API proposal as requested 👍

**Comment by terrajobst** [comment]
* Makes sense but we believe it should live on `NativeMemory` instead.

```C#
namespace System.Runtime.InteropServices;

public static class NativeMemory
{
    public static void ZeroMemory(void* buffer, nuint sizeInBytes);
}

```

**Comment by Sergio0694** [comment]
@tannergooding @GrabYourPitchforks I'm happy to take this if it's up for grabs 😄
