### ISSUE TITLE
Support ODBC connection strings longer than 1024 characters

### ISSUE THREAD

**Issue by abelykh0** [dotnet/runtime#63630]
### Description

According to documentation (https://docs.microsoft.com/en-us/dotnet/api/system.data.odbc.odbcconnection.connectionstring?view=dotnet-plat-ext-6.0), the .Net ODBC driver don't support `ConnectionString` longer than 1024 characters. Please remove this limitation (or at least make it longer).

### Reproduction Steps

N/A

### Expected behavior

Should support `ConnectionString` longer than 1024 characters.

### Actual behavior

`ConnectionString` must be 1024 characters or shorter.

### Regression?

No

### Known Workarounds

If an ODBC driver supports connection strings longer than 1024 characters, you can use a data source name (DSN) to exceed the maximum length limitation.

### Configuration

N/A

**Comment by ajcvickers** [comment]
@abelykh0 The ODBC driver is not something we are investing resources in. This is not a change we are planning to make.

**Comment by abelykh0** [comment]
> @abelykh0 The ODBC driver is not something we are investing resources in. This is not a change we are planning to make.

What if I make a change and submit a pull request? Would it be considered then?

**Comment by laurencehartje** [comment]
I would request that this issue be re-evaluated for resolution. I recognize that ODBC is not the newest/latest data access technology, but it is still relevant in Microsoft’s cloud native offerings in Azure.

We are currently migrating our on-prem data processing and querying applications from .NET Framework and SQL Server to .NET Core and Azure Databricks.

In order to leverage Azure Active Directory authentication to Databricks, the Azure Active Directory access token must be included in the connection string as documented by [Microsoft here](https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#--authentication-parameters). In our testing, the Azure Active Directory token is over 1024 characters by itself (let alone any other connection string information, such as a server to connect to). The limitation of 1024 characters for a connection string will force us to reevaluate using .NET Core for our application tier as we have already signed a multi-year commitment for Azure Databricks. 

The approach of creating System DSNs to bypass the connection string limit will not work for us, as we have many users simultaneously accessing many various data sources which require user-level authentication, and I’m not even sure if we have permissions to create such DSNs in our production environment (the additional system-level access permissions will raise security concerns). The length of the Azure Active Directory token and the 1024 character limit on ODBC connection strings in .NET Core effectively rules out using .NET Core in our application tier for data access to Azure Databricks.

I do have a few questions:
* Is the limitation of 1024 characters a legacy limitation (maybe relevant to 32-bit ODBC drivers or specific drivers in the past)?
* Is the limitation of 1024 characters a Windows limitation that is being applied to other platforms that .NET core runs on (we leverage Linux in Azure App Service for hosing the services, but develop on Windows locally)?

As a quick test, I did locally compile System.Data.ODBC with a modification to double the allowed length for the connection string, and at least with the SIMBA Spark ODBC Windows driver it works without issue. This clearly is not a through test in any way (or even addresses the many ODBC drivers and platforms that .NET supports), but maintaining a fork of System.Data.ODBC is not ideal for a number of maintenance and compliance issues. 

If this will not be addressed by the .Net Core team, I'd appreciate any input for other approaches (as these are classes in the System namespace and the changes are on internal or sealed classes) and by my understanding we are not able to inherit or override the existing implementation.

Thanks!

**Comment by ajcvickers** [comment]
@roji and/or @bricelam to investigate.

**Comment by JeremyLikness** [comment]
Just a quick update. We're reaching out to the teams who maintain the underlying driver to understand limitations there and if there are concerns about potential issues if we extend the limit. I'll update once I find out more.

**Comment by roji** [comment]
@xygon and others, I have an experimental version of the System.Data.Odbc package with the limit removed, and I'd like your help in verifying it. Could you please write to my email (on my github profile) and I'll share it?

**Comment by georgewfisher** [comment]
@roji When will this patch be released?

**Comment by abelykh0** [comment]
I did a limited testing (docker with Ubuntu 20) and it does work and I didn't experience any regression issues.

**Comment by roji** [comment]
@georgewfisher this should go out in 6.0.9, which is probably a few weeks away.

**Comment by abelykh0** [comment]
> @georgewfisher this should go out in 6.0.9, which is probably a few weeks away.
Was this released? The current .Net is 6.0.10.

**Comment by roji** [comment]
Yes, this was released in 6.0.9.
