### ISSUE TITLE
Stop using Socket directly in HttpConnection

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#63710]
It seems like there is only one use for sync case:
https://github.com/dotnet/runtime/blob/8fef95be4a4fee42005a511d9b31a034e1fc3baf/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L161-L167

Since we already do type check on stream elsewhere, we can probably use it here as well and access NetworkStream.Socket.

https://github.com/dotnet/runtime/blob/b4dfd7d067a8523ec5fb9c3247daaffb2dde5341/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1368-L1373

And we would not need to store reference and drag the socket directly through the layers.

**Comment by geoffkizer** [comment]
I wonder if the call to Poll is even correct in all cases for SSL... seems like we could receive a renegotiation challenge that triggers the poll but doesn't actually result in any app data being received. @wfurt does that seem possible?

**Comment by wfurt** [comment]
probably. Also data may be buffered inside SslStream so Poll fails while data _are_ available. I was looking for answer for https://github.com/dotnet/runtime/issues/63663#issuecomment-1011518672 and I noticed how we pass Socket together with Stream.

**Comment by geoffkizer** [comment]
> Also data may be buffered inside SslStream so Poll fails while data are available. 

Yeah, that's even more concerning.

Seems like we should not use Poll on the underlying socket when we do SSL.

**Comment by stephentoub** [comment]
>> Also data may be buffered inside SslStream so Poll fails while data are available.

> Yeah, that's even more concerning.

Does it matter given the use case?  The consuming code always needs to be prepared for a false negative, since there's a race that the connection could become unusable after we take it from the pool, and so if the check here has false negatives because data was already consumed and buffered by the higher-layer, it'd just be another false negative.

We could of course remove the Poll'ing, entirely.  As an upside, doing so would avoid any theoretical concerns here and as a perf benefit would avoid the extra syscall, but it would also increase further the chances that we try to use a connection that's already unusable (or we'd need to replace it with a sync-over-async operation, which is also not ideal).

**Comment by karelz** [comment]
Triage: Key value is simplification of code with one less field.
