### ISSUE TITLE
.NET 6 - dotnet publish doesn't recognize RID any

### ISSUE THREAD

**Issue by AaravHattangadi** [dotnet/runtime#63728]
Hello.
I'm trying to build a self-contained .NET 6 WinForms app that would work on both 32 and 64 bit.
I've tried running `dotnet publish --os any -o ".\build" -sc` and I get an error that the RID "any" is not recognized.
I then tried running `dotnet publish --os win10-x86 -o "\build" -sc` and for some reason its trying to publish with the RID win10-x86-x64.

Is this an issue with .NET 6, or am I doing something wrong?

**Comment by filipnavara** [comment]
> Is this an issue with .NET 6, or am I doing something wrong?

That's by design. You are either doing framework dependent deployment (framework has to be installed on the machine) or self-contained deployment (carrying the framework with the app). However, in both cases, the host executable of the published application is specific to a single platform. This is different from .NET Framework which had a special support in the operating system loader that allowed locating the runtime and running AnyCPU code.

You may want to have a look at https://github.com/Tyrrrz/DotnetRuntimeBootstrapper. It explains the situation in more detail and offers a solution that may be appropriate for your use case.

**Comment by AaravHattangadi** [comment]
Hey @filipnavara,
Thanks for the prompt response. I'll look into DotNetRuntimeBootstrapper. If it doesn't work for me, I'll just make the installer check if its 32/64 bit and install the necessary version.

Do you have any idea why when I run "dotnet publish --os win10-x86 ..." it takes the RID as win10-x86-x64?

**Comment by vitek-karas** [comment]
> Do you have any idea why when I run "dotnet publish --os win10-x86 ..." it takes the RID as win10-x86-x64?

The `--os` should only supply the Operating System part of the RID, so in this case `win10`. There's also `--arch` which can supply the architecture, so `x86` or there's just the `-r` which can supply the entire RID. So these two are equivalent:
* `dotnet publish --os win10 --arch x86`
* `dotnet publish -r win10-x86`

I guess it would be good if the SDK provided a better error about this. Could you please create an issue in the dotnet/sdk repo for that?

**Comment by AaravHattangadi** [comment]
Hey Vitek,
I'll create an issue about this in the SDK repo.
Thanks for the help! Will try it out and let you know.
