### ISSUE TITLE
Remove CheckForOverflowUnderflow

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#63725]
I think this can be removed https://github.com/dotnet/runtime/blob/4d97cda06439540cbc8bdffcd191c7f6184257cd/src/libraries/Directory.Build.props#L90-L91 because #15152 is closed

**Comment by safern** [comment]
Thanks, @deeprobin I think we are referencing that issue on the code as a historical context on why we disabled it globally. We tried to enable it for some time but then disabled it. The comment says we decided to keep it disabled by default, @stephentoub do you happen to know why did we decide to turn this off again?

**Comment by stephentoub** [comment]
Because we don't want it enabled. The vast majority of code expects it to be off and it would be a sheer ton of busy work to reliability find and change all the places that depend on it.  And at that point, you've either cluttered up the code with lots of ifdefs to handle only having it enabled in debug, or you've added run-time cost to also have it enabled in release.  We don't want any of that :)

That said, the default is false, so I'm not sure why it's needed in the Directory.Build.props, unless we're concerned about it being flipped somewhere higher up.

**Comment by safern** [comment]
Thanks, @stephentoub :). 

From a quick GH search for the property that is the only place we have it set, so there is nowhere higher up flipping it on: https://github.com/dotnet/runtime/search?q=CheckForOverflowUnderflow

I think we can safely remove it.

**Comment by deeprobin** [comment]
I think we can close this issue, because #63825 was merged. 

Similar cases are superseded by #63902.
