### ISSUE TITLE
Microsoft.Extensions.DependencyInjections 6.0 is not compatible with netcoreapps 2.1 and 3.0 

### ISSUE THREAD

**Issue by anna-git** [dotnet/runtime#63744]
### Description

Although it's told to be compatible with netstandard 2.0, it can't be referenced from a netcore app 2.1 or 3.0:

```

Error		Microsoft.Extensions.DependencyInjection.Abstractions doesn't support netcoreapp2.1. Consider updating your TargetFramework to netcoreapp3.1 or later.	ConsoleApp1	...\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets	4	
```

### Reproduction Steps

Create a net core app 2.1 or 3.0 and reference last version of Microsoft.Extensions.DependencyInjections .

For us, it happened when trying to update Verify.Xunit which indirectly references Microsoft.Extensions.DependencyInjections 6.0. Verify.Xunit still states to be compatible with netcore app 2.1 and 3.0, but because of this reference, it doesn't.

### Expected behavior

net core app 2.1 should be able to reference a netstandard 2.0 library

### Actual behavior

net core app 2.1 can't reference anything that references Microsoft.Extensions.DependencyInjections 6.0

**Comment by danmoseley** [comment]
The 6.0 versions of many packages built from this repo no longer contain `netstandard2.0` assets. This is why you are seeing that `netcoreapp2.1` cannot consume it. The reason we did this is that in-support platforms such as `netcoreapp3.1` support `netstandard2.1` and do not need `netstandard2.0` assets.

If you want to consume this package from an out of support framework like `netcoreapp2.1` please lock the version you consume explicitly to `5.0.*`. But you may choose to do something similar, and drop support for out of support frameworks, so that you can consume the latest packages.

**Comment by danmoseley** [comment]
Here's info about this: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/older-framework-versions-dropped

I'll close, but LMK if you have other questions.

**Comment by danmoseley** [comment]
PS welcome to our repo @anna-git !

**Comment by anna-git** [comment]
thank you @danmoseley! so about your answer, if it no longer contains `netstandard2.0` assets, why not remove the target?

**Comment by ericstj** [comment]
I'll make a small correction to what @danmoseley mentioned above.  In the cases mentioned in the original post we actually kept the `netstandard2.0` assets -- we did because we still wanted to enable the folks who build once and share an assembly between multiple frameworks like `net48` and `netcoreapp3.1`.

At the same time, we needed a way to drop the framework specific assets from those packages for out-of-support frameworks: otherwise our packages which provide framework-specific implementations to take advantage of new .NET API or provide a better experience on new frameworks would grow without bound.  We didn't feel comfortable just removing those framework-specific assets for out-of-support frameworks since it would mean folks would see a different behavior when using the new package -- instead of getting the framework-specific asset for the out-of-support framework they'd get the `netstandard2.0` asset.  We wanted to send a stronger message and one that would be seen at design time -- this framework is no longer supported -- the implementation you receive may be different -- proceed at your own risk.  For folks that want the old (out-of-support) implementation for that framework they can use the old package.
