### ISSUE TITLE
ICorProfilerCallback::ObjectsAllocatedByClass does not work anymore since dotnet 6

### ISSUE THREAD

**Issue by ogxd** [dotnet/runtime#63806]
### Description

The CLR profiling API callback [ICorProfilerCallback::ObjectsAllocatedByClass](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-objectsallocatedbyclass-method) is not called by the CLR in dotnet 6.

### Reproduction Steps

1. Implement the `ICorProfilerCallback` interface
2. Print to the console in the `ObjectsAllocatedByClass` callback
3. Eventually also implement `ICorProfilerCallback2` and print in the `GarbageCollectionStarted` callback, so that you you'll see that `ObjectsAllocatedByClass` is not called when `GarbageCollectionStarted` is.
4. Use the COR_PRF_MONITOR_GC and COR_PRF_HIGH_MONITOR_NONE event mask 2 flags
5. Attach to a NET 5.0 application: it works.
6. Attach to a NET 6.0 application: it doesn't work anymore, `ObjectsAllocatedByClass` is not called.

### Expected behavior

The `ObjectsAllocatedByClass` callback should be called for each garbage collection like it used to be before.

### Actual behavior

The `ObjectsAllocatedByClass` callback is never called.

### Regression?

Yes

### Known Workarounds

No workaround was found

### Configuration

dotnet version:
- 6.0.101 (not working)
- 5.0.100 (working)

OS: Windows 11 x64

### Other information

Could it be due to [these recent changes](https://github.com/dotnet/runtime/commit/ab71c1f4031d449ed3d60ccaaecb629bb73b648a#)? @davmason     
![image](https://user-images.githubusercontent.com/12692438/149569719-0d1be607-71e3-4d4c-beee-13fbf623372a.png)

**Comment by ogxd** [comment]
So in order the check my hypothesis about the problem coming from theses changes, I installed the latest dotnet 6 SDK before this commit (6.0.100-preview.2.21155.3), and it works as expected: `ObjectsAllocatedByClass` is called as it should. I hope it will help finding the issue.

**Comment by davmason** [comment]
Thanks for reporting this @ogxd, it is indeed caused by that change. Specifically this part: https://github.com/dotnet/runtime/blob/02e22b02975d50944220e6e9a494af491487c6a9/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L1265-L1287

Line 1277 should be `BEGIN_PROFILER_CALLBACK(CORProfilerTrackGC())` and not `BEGIN_PROFILER_CALLBACK(CORProfilerTrackAllocations())`

I will create a fix sometime soon, we should be able to backport this one to 6.0.

If you (or anyone else out there) are interested in contributing to the runtime, this would be a great first issue. The fix is one line, and then it's just adding a simple test to make sure ObjectsAllocByClass works.

**Comment by davmason** [comment]
Oh, and it should be possible to work around this by enabling `COR_PRF_MONITOR_OBJECT_ALLOCATED`, although that is a very expensive thing to enable so I wouldn't suggest enabling that workaround in any production scenario

**Comment by ogxd** [comment]
Hi @davmason, thanks for the quick reply! A backport fix would be amazing :)  
Unfortunately I can't use `COR_PRF_MONITOR_OBJECT_ALLOCATED` since the profiler I use is attach to a process already running (using `[InitializeForAttach(...)](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback3-initializeforattach-method)`), and, from what I understood, it is only possible to use this flag for profilers that are initialized when the profiled app starts (using `[Initialize(...)](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-initialize-method)`)

**Comment by davmason** [comment]
For the workaround, it might just work if you set `COR_PRF_MONITOR_OBJECT_ALLOCATED` even on attach. You won't get the object allocated callbacks, since you need to set those at startup like you mention, but I don't think we prevent you from setting it later in the process.

I would like to see a test if you submit a fix, it hopefully is relatively straightforward but if you get blocked I'm happy to help get you going again.

You need to add a managed testcase, like inlining.csproj/inlining.cs in https://github.com/dotnet/runtime/tree/main/src/tests/profiler/unittest, and then a corresponding native profiler like the one in https://github.com/dotnet/runtime/tree/main/src/tests/profiler/native/inlining.

The managed app should allocate some classes, and then the native profiler should check that the classes it expected to see were allocated and write "PROFILER TEST PASSES" if everything is right.

**Comment by davmason** [comment]
Oh, nevermind about the workaround. I forgot we whitelist the allowable after attach flags. It won't work

**Comment by ogxd** [comment]
Thanks for the review and the merge @davmason! Shall I make another PR for an eventual backport to 6.0.0 or do you usually handle this on your side?

**Comment by davmason** [comment]
We have a bot that will do the actual work of opening a PR, but then it has to go through an approval process that I have no control over. I hope it gets through since we have a customer (you) asking for it and it is small, but can't promise anything.

**Comment by davmason** [comment]
Don't know why the backport bot isn't working, it looks like I'll have to create it manually

**Comment by davmason** [comment]
Closing since it is backported to 6 and in main
