### ISSUE TITLE
[API Proposal]: RemoteCertificateValidationCallback cannot detect future certificates

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#63830]
### Background and motivation

My application runs on IoT devices that may not have a synchronised system clock. My application connects to my server and can retrieve the current time from there, largely replacing NTP. But the connection fails if the server uses a certificate from the "future". I want to accept such certificates, but no other errors like self-signed or wrong host names. I also don't want to accept expired certificates, since the device clock is usually in the past, not in the future.

### API Proposal

I have no idea how that should work. The `RemoteCertificateValidationCallback` callback gets a `SslPolicyErrors` parameter that seems to be `RemoteCertificateChainErrors` in such cases. This is a very broad error message that cannot be used for anything. Do I have to redo all of what has led to this error flag, except the future check? Or can the API be helpful here?

### API Usage

see above

### Risks

If some application has used that very broad `RemoteCertificateChainErrors` value before, it might be too narrow then. I don't know how to handle a fix for such a generic API design flaw. I just need a solution.

BTW, I wasn't able to find the source code that originally generates these flags. It might be helpful to copy and patch the BCL code to have a good but custom certificate check.

**Comment by Clockwork-Muse** [comment]
.... assuming your device is _capable_ of NTP or a similar protocol, the "proper" solution is to set the correct time during initial deployment/installation and allow the OS to manage it for you.  Otherwise, you're essentially implementing the protocol as part of your application layer - and the proper way to do it is still to set the correct time during initial deployment (and keep it synced with a heartbeat if there aren't enough messages normally).

Strictly speaking, a future, not-yet-valid, cert is suspicious for the same reason a past, expired, cert is, because you don't actually have a guarantee of which direction your clock has drifted:
> I also don't want to accept expired certificates, since the device clock is **usually** in the past, not in the future.

(emphasis mine)
Clocks are equally likely to drift in either direction for any given duration (consumer-grade quartz-based timekeeping devices are generally on the order of +- 30sec/month).  The correct thing to do if a device is out-of-sync is to send somebody to correct the clock.

<hr />

That aside, if you really want to do this, you're going to have to check the entire chain yourself (if there are errors).  You're going to need to iterate through the elements of the `X509Chain chain` parameter and check whether the only error is an invalid time, and that the time appears to be in the future.  Note that you're going to need the entire chain, since there are almost certainly multiple certificates involved, any one of which can have (multiple) errors (one certificate could be expired, and one could not be valid yet, for example, although it's not likely).

**Comment by ygoe** [comment]
To clarify: The clock of simple IoT devices doesn't drift, it doesn't exist. There's no RTC in a Raspberry Pi. When booting, the clock is somewhere around 1970, or 2000, or whatever past year. Setting the clock at "deployment" is useless and impossible. Devices are deployed in a powered-off state. And the next power cycle will reset the time again. Even the fake RTC will fail if the device was powered off for a month and the certificate has expired since then and was replaced (LetsEncrypt certs don't live very long, I already had a connection failure because of this).

After getting the current time from the server, I can reevaluate the certificates. They should be valid then. I guess that provides slightly more security than a completely insecure NTP. Because a hypothetical attacker at least has to gain a valid certificate for my domain for some point in time. Which should not be possible ever.

Okay, so is this the right direction to go? `chain.ChainElements[*].ChainElementStatus[*].Status.HasFlag(X509ChainStatusFlags.NotTimeValid)`

**Comment by wfurt** [comment]
You also get the X509Chain as @Clockwork-Muse  mentioned.  You can walk the Status and check https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainstatusflags?view=net-5.0 for `NotTimeValid`

cc: @bartonjs

**Comment by wfurt** [comment]
BTW if you just want to ignore, time you would have to check that `NotTimeValid` is only one flag set. e.g. there are no other violations.

**Comment by Clockwork-Muse** [comment]
If the devices are usually powered off, I'd probably write a script that manually queries an NTP server and sets the system time from that, or configure the NTP client to not worry about a maximum (positive) clock drift and just sync to server time; strictly speaking this enables the same attack if the NTP server is impersonated (although this can be mitigated if there's an authoritative server on the local network).
Other options include updating the initial config time read on boot - the clock would still need to be synced up, but at least it wouldn't be _so_ out-of-date - or querying another server with a separate, non-expiring certificate.
Most of this is easier to set up than a custom certificate validation callback, and certainly less error-prone or exploitable.

In addition, if the Pi is attached to certain types of extra hardware, like a GPS or cellular unit, you may be able to use them for an authoritative time source, which would also solve your problem.

**Comment by karelz** [comment]
Triage: Looks like walking the chain is good enough workaround. Unless we have more requests to make it easier, we don't think we should add new API.
Closing. Please let us know if you disagree or if we missed some point.
