### ISSUE TITLE
[API Proposal]: add virtual Clone method to System.Random

### ISSUE THREAD

**Issue by ZacharyPatten** [dotnet/runtime#63911]
### Background and motivation

`System.Random` should have a `virtual` `Clone` method. Needing to clone a `System.Random` is niche, but there should still be a method to do it. Most google hits recommend using serialization to clone `System.Random` instances, but serialization should not be required to clone.

### API Proposal

```C#
// in the "System.Random" class...
public virtual Random Clone()
{
    // clones "this" and returns the constructed clone
}
```

### API Usage

```C#
Random a = new();
Random b = a.Clone();

// from then on, a & b should produce the same output...
while (true)
{
    Assert.IsTrue(a.Next() == b.Next());
}
```

**Comment by Clockwork-Muse** [comment]
> Needing to clone a `System.Random` is niche

.... and what is that niche?  What's your real-world use-case?  This would seem to make sense only when you keep the instances in sync (because if they diverge why would you bother to clone?).  The most likely case I can think of is going to be things like multiplayer games, but in those cases you're dealing with inter-machine communication, which means a `Clone()` wouldn't work (and in many cases you would save/transmit the initial seed, not the current state, anyways).

**Comment by stephentoub** [comment]
Even if we wanted to add this, there's no way we could add it correctly as proposed. The base implementation wouldn't know about any state in a derived type, and if the derived type doesn't override it, Clone'ing would produce an incorrect result for the consumer. As such, the Clone method would need to be a TryClone or a pair of Clone/CanClone members, or some such thing.

**Comment by skyoxZ** [comment]
(Not an API proposal) I think it's common for a game to implement a custom Random class below so that it can save the current position of random sequence.
```C#
public sealed class XoshiroRandom
{
    ....
    public byte[] State { get; }
    public XoshiroRandom(byte[] state) { throw null; }
}
```
ref [XoshiroImpl](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Random.Xoshiro128StarStarImpl.cs)

@ZacharyPatten Is this what you want? Implement it by yourself because 
> The implementation of the random number generator in the Random class isn't guaranteed to remain the same across major versions of the .NET Framework. As a result, you shouldn't assume that the same seed will result in the same pseudo-random sequence in different versions of the .NET Framework.

**Comment by ZacharyPatten** [comment]
@skyoxZ Yes, cloning the state of the `System.Random` is the request. An yes, you can easily make your own implementation, but I don't see why we can't add state cloning to `System.Random` too.

@stephentoub `System.Random` already has multiple virtual members on it. I fail to see how I couldn't use the same argument for either of the existing virtual members. If I intend to customize the random generation algorithm and I override `Next` but not `NextDouble`, I would consider that an _"incorrect result"_ too, as it would fall back to the base implementation rather than the derived algorithm.

**Comment by stephentoub** [comment]
> I fail to see how I couldn't use the same argument for either of the existing virtual members.

The new members we add are fully implementable in terms of those previously there. That's not the case for Clone.

**Comment by Clockwork-Muse** [comment]
> Yes, cloning the state of the `System.Random` is the request. And yes, you can easily make your own implementation, but I don't see why we can't add state cloning to `System.Random` too.

Note that @skyoxZ 's suggestion actually _exports_ the internal state, which would be useful for serialization, like for inter-machine communication.  And you can't do _that_ with `System.Random` either, because of subclasses.

That aside, you still haven't said _why_ you want this, or what problem this would solve.

**Comment by stephentoub** [comment]
Thank you for the suggestion.  I'm closing per the feedback.
