### ISSUE TITLE
Inconsistent assembly version for System.Text.Json netstandard2.0

### ISSUE THREAD

**Issue by cbersch** [dotnet/runtime#64003]
In the System.Text.Json NuGet package 6.0.1 the netstandard2.0 assembly has a different assembly version than the net461 assembly:

NuGet package version 6.0.0
netstandard2.0 -> 6.0.0.0
net461 -> 6.0.0.0

NuGet package version 6.0.1
netstandard2.0 -> 6.0.0.0
net461 -> 6.0.0.1

**Comment by ericstj** [comment]
Yes, this is by design.  

`netstandard2.0` asset needs to support compatibility with the latest `net6.0` framework where the assembly is inbox and serviced in place --> we don't change assembly version for in-place servicing. 

The .NETFramework version is out-of-band and carried with applications so it must version to ensure that the application's copy of the assembly is used rather than a different one with the same version in the GAC.

**Comment by cbersch** [comment]
@ericstj Thank you for the explanation
