### ISSUE TITLE
Remove `!` from `Microsoft.Extensions.Caching.Abstractions`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#64147]
This is a blanket issue for all `!` operations that were added in #64018
They should be removed or reviewed.

Left to be fixed/reviewed:
- https://github.com/dotnet/runtime/pull/64018#discussion_r790049971 (https://github.com/dotnet/runtime/pull/64018/commits/40d8838d4e586a74dbf2395292c9898e253a0474)

**Comment by hrrrrustic** [comment]
@eerhardt There is only one `!` left that was discussed in initial PR https://github.com/dotnet/runtime/pull/64018#discussion_r790049971

https://github.com/dotnet/runtime/blob/b9b5fefa08cecb9283f71e0b7fde6c91d22edda9/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/CacheEntryExtensions.cs#L175-L178

I don't think it's a bug because it doesn't make any sense to register null callbacks. Is it fine to just add null-check (with throwing) before invocation?

**Comment by eerhardt** [comment]
Yes, I think that is a fine solution here. Check if it `EvictionCallback` is null, and throw an exception here saying it can't be null.
