### ISSUE TITLE
[Blazor WebAssembly] Support for Cancelling HTTP Requests by Diposing Response Stream

### ISSUE THREAD

**Issue by tpeczek** [dotnet/runtime#64225]
When working with `ReadableStream` in JavaScript, one can call `ReadableStreamDefaultReader.cancel()` which will triger request cancellation if the server is still streaming.

In Blazor WebAssembly this is currently not possible, as `WasmHttpReadStream` uses the reader only to advance the `ReadableStream` and on dispose only diposes the references to JavaScript objects. It looks like this functionality could be achieved by adding call to `cancel()` in `WasmHttpReadStream.Dispose`.

```
private sealed class WasmHttpReadStream : Stream
{
    ...

    protected override void Dispose(bool disposing)
    {
        if (!(_reader is null))
        {
            _reader.Invoke("cancel");
        }

        _reader?.Dispose();
        _status?.Dispose();
    }

    ...
}
```

Such a change would be a great improvement for scenarios like consuming async streams coming from servers.

**Comment by gilm0079** [comment]
I'm experiencing the same issue. I probably posted in the wrong channel. I was advised to link it here. Would someone consider this fix for .net 6? I'm working on a blazor wasm production app and it would be helpful if user initiated cancels on token sources aborted http connections to the server api so that the asp.net core api treats the RequestAborted as a cancelled token and I can also cascade up cancellation of pending server operations. Thanks.

[https://github.com/mono/mono/issues/21436](https://github.com/mono/mono/issues/21436)
