### ISSUE TITLE
.NET Core app - submission to Mac app store

### ISSUE THREAD

**Issue by dimitrirostavo** [dotnet/runtime#64258]
(Noob alert) - Most of our windows code is built in .net5 core. We are trying to port it over to Mac and have it submit to mac app store. 
A few questions (would be really grateful if someone could respond)

- Are there any gotchas that others have seen that would be good to know? 
- Looking at the needed entitlements on the Mac app - 
`com.apple.security.cs.allow-jit`
`com.apple.security.cs.allow-unsigned-executable-memory`
`com.apple.security.cs.allow-dyld-environment-variables`
`com.apple.security.cs.disable-library-validation`

Curious - disabling some of the hardening requirements seem pretty scary. Would it be possible for someone to by-pass library validation and replace it with a malicious version (similarly for the dyld-environment variables)? Is the onus now on the developer to figure out how to validate if these libraries are code-signed or not? 

Lastly - is there a way to have VS Mac spit out a Mac app similar to xcode? Or does it only provide a standalone library that then needs to be repackaged manually?

**Comment by martincostello** [comment]
If it's of any use to you, I had a play with macOS notarization for packaging a .NET app last year and put the sum of where I got to into a GitHub sample repo: https://github.com/martincostello/dotnet-macos-notarization-example

The packaging, signing and notarization is all a [separate activity in CI after build](https://github.com/martincostello/dotnet-macos-notarization-example/blob/0282aa3b5482b3245b2c41faf62f13a9502b252b/.github/workflows/build.yml#L49-L127), rather than part of the `dotnet build` process itself.

This was just for use locally distributed via GitHub releases, so without any App Store submission, but should still be relevant.

**Comment by rolfbjarne** [comment]
> Lastly - is there a way to have VS Mac spit out a Mac app similar to xcode?

This will be possible when we release MAUI support this spring. You can try right now with the latest .NET 6 preview and use the `net6.0-macos` target framework.

**Comment by ericstj** [comment]
@rolfbjarne @akoeplinger can you speak more generally about the needed entitlements independent of MAUI?  Do we have any documentation on what the runtime requires and why?

**Comment by rolfbjarne** [comment]
The `com.apple.security.cs.allow-jit` seems rather obvious: we're executing a JIT compiler, so we need that entitlement.

I don't know why `com.apple.security.cs.allow-dyld-environment-variables` would be needed, that seems rather strange (maybe try without and see how things break?)

The `com.apple.security.cs.allow-unsigned-executable-memory` and `com.apple.security.cs.disable-library-validation` might be because all the .NET-related dylibs that must be loaded from the app bundle (or from the system installation of .NET) aren't signed (maybe it would be possible to get around this by signing everything that's loaded at runtime?). For MAUI apps in .NET 6 I believe we don't need these entitlements anymore, because we create a self-contained app bundle, and every library is automatically signed with the signing identity for the app bundle itself.

**Comment by janvorli** [comment]
We don't use the `com.apple.security.cs.allow-unsigned-executable-memory` from 6.0.1 on. The `com.apple.security.cs.allow-dyld-environment-variables` is not needed by the runtime, but we add it to enable troubleshooting of loading shared libraries where using the dynamic linker variables is helpful. I am not sure about the `com.apple.security.cs.disable-library-validation`, I suppose it is to support interop with unsigned 3rd party libraries.

**Comment by agocke** [comment]
@dimitrirostavo Feel free to test your app with a smaller set, if you want. `com.apple.security.cs.allow-jit` will definitely be necessary, but the others may not if you don't happen to use the functionality that requires them.

Otherwise, the standard security model for Windows likely applies.
