### ISSUE TITLE
Add Microsoft.VisualBasic.Core support to Microsoft.Windows.Compatibility for .NET Standard

### ISSUE THREAD

**Issue by stamminator** [dotnet/runtime#64334]
Though `Microsoft.VisualBasic.Core` has implementations in both .NET Framework and .NET Core+, the lack of cross-platform implementation at the time .NET Standard 2.0 was created puts developers with VB libraries to share between old and new projects in a tough spot. Is this support something that would be eligible for inclusion in a future release of the Windows Compatibility Pack?

**Comment by danmoseley** [comment]
@ericstj did we consider multitargeting M.VB.C to .NET Standard 2.0 as well?

**Comment by ericstj** [comment]
VB.Core was a rename of the subset of Microsoft.VisualBasic that was already shipped as a package in https://www.nuget.org/packages/Microsoft.VisualBasic (with a `netstandard2.0` reference IIRC).  The rename was necessary because the implementation needed to be split between low-level types and higher level https://github.com/dotnet/winforms/tree/main/src/Microsoft.VisualBasic.Forms.  No matter what the latter can't be represented in a `netstandard2.0` package since Winforms isn't available.

There was some discussion in https://github.com/dotnet/corefx/pull/34087 about preserving a package after the rename.  It's possible to make a package, but folks would need to consider what support would look like for all `netstandard2.0` compatible frameworks including `netcoreapp2.0` and `netcoreapp2.1` which exposed the types in `Microsoft.VisualBasic` and didn't support everything that was later added in 3.x.  It's not impossible to do, but it was significant additional work, and I don't think folks were prioritizing that scenario in the 3.0 timeframe.  @cston, @333fred, or @KathleenDollard might remember better.

**Comment by stamminator** [comment]
Thanks for the info @ericstj. So basically someone would have to recreate the functionality in M.VB.C that depends on M.VB.F targeting specifically toward frameworks like `netcoreapp2.0` and `netcoreapp2.1`, delivered in a version update to `M.VB.C` which introduces the wider compatibility. Assuming the will is there, is my understanding of the technical side of it accurate?

**Comment by stamminator** [comment]
The multi-targeting is the solution I settled on. Ended up forcing me to multi-target all of my downstream dependencies as well, but the tooling is great, so I have no complaints.
