### ISSUE TITLE
[API Proposal]: Add X509SubjectAlternativeNameExtension

### ISSUE THREAD

**Issue by stephenjust** [dotnet/runtime#64388]
### Background and motivation

Today, reading Subject Alternative Names from an X509Certificate2 is unnecessarily complicated.

https://stackoverflow.com/questions/16698307/how-do-you-parse-the-subject-alternate-names-from-an-x509certificate2 gives several examples for how to accomplish this, but this is so much more complicated than it needs to be.

Current options:

1. Use GetNameInfo(X509NameType, bool)
   This returns only a single name of each type. The behavior of which one to return if multiple are present is undefined, but experimentally it looks like it returns the last match?
2. Use AsnEncodedData.Format() on the X509Extension for Subject Alternative Name
   You need to do string parsing to pull out each DNS Name entry, for example. The stackoverflow above claims that this string's format differs between platforms, though I can't personally verify this.
3. Parse the AsnEncodedData.RawData manually (prior to .net 5) or using AsnReader (.net 5+)
    This is probably the most efficient option, but the most complicated to implement.

### API Proposal

```C#
namespace System.Security.Cryptography.X509Certificates
{
    public class X509SubjectAlternativeNameExtension : X509Extension
    {
        public IEnumerable<GeneralNameAsn> Names { get; }
    }
}
```

Existing internal GeneralNameAsn would need to be exposed (reusing the types from SubjectAlternativeNameBuilder)

### API Usage

```C#
// Read a certificate from the store
using var store = new X509Store(storeName, storeLocation);
store.Open(OpenFlags.ReadWrite);
var certificate = store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, validOnly)[0];

// Get the SAN DnsName values.
var names = certificate.Extensions[Oid.SubjectAlternativeName].Names;
var dnsNames = names.Where(names => names.DnsName != null);
```

### Risks

In theory an X509Extension could contain data that is not of the pattern SEQUENCE : GeneralName, GeneralName, etc. but I don't think this is a supported way to use the extension.

**Comment by stephenjust** [comment]
I don't have a strong opinion about what GeneralNameAsn looks like in the public API, the current version of it seems relatively clunky and probably cannot handle custom field types.

**Comment by bartonjs** [comment]
`GeneralNameAsn` is a generated type to facilitated encoding/decoding the GeneralName ASN.1 structure.

Defining what the public aspect would look like is an important part of this API proposal, unfortunately, and not something that can be hand-waved away.

#28771 suggests addressing the problem in a different way, anticipating that the question that one usually wants to answer is "is the cert appropriate for this hostname?".

#22699 suggests having the extension type, and two different enumerators, one for DNSName values, and one for IPAddress values (and mentions the concept from #28771).

Rather than create a third issue, please contribute thoughts to one of the existing ones.
