### ISSUE TITLE
GetActiveTcpListeners is not implemented on FreeBSD

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#64416]
On macOS we use `net.inet.tcp.pcblist`  sysctl code but that is not available on FreeBSD. We should figure out how netstat does it.

https://github.com/dotnet/runtime/blob/9eb90511ff6d079fa02832936c693d36289fc02b/src/native/libs/System.Native/pal_networkstatistics.c#L345-L351

**Comment by rootwyrm** [comment]
This honestly does not make any sense. `net.inet.tcp.pcblist` is still there, always has been - that's where OSX got it from. 

[sys/netinet/tcp_subr.c]](https://github.com/freebsd/freebsd-src/blob/releng/13.0/sys/netinet/tcp_subr.c)
[sys/netinet/in_pcb_var.h](https://github.com/freebsd/freebsd-src/blob/releng/13.0/sys/netinet/in_pcb_var.h)
[usr.bin/unix/netstat.c](https://github.com/freebsd/freebsd-src/blob/releng/13.0/usr.bin/netstat/unix.c)
[usr.sbin/tcpdrop/tcpdrop.c](https://github.com/freebsd/freebsd-src/blob/releng/13.0/usr.sbin/tcpdrop/tcpdrop.c)

**Comment by wfurt** [comment]
```
[furt@d13 ~/github/wfurt-runtime]$ sysctl -a | grep pcblist
[furt@d13 ~/github/wfurt-runtime]$
```
hmm. maybe it is missing because it gives binary data...? 
May be worths of shot to just try it.

**Comment by rootwyrm** [comment]
I *BELIEVE* this may be something I red tagged some time back due to known IPv4/IPv6 problems which are at least partly ignorable.

The way it works is thus:
```
SYSCTL_UINT(_net_inet_tcp, OID_AUTO, pcbcount, CTLFLAG_VNET | CTLFLAG_RD,
    &VNET_NAME(tcbinfo.ipi_count), 0, "Number of active PCBs");
```
Which gives you this:
```
09:27 PM Thu Jan 27 [J:0 C:2 H:499] FreeBSD 13.0-RELEASE-p4
rootwyrm@mojache ~ $ sysctl net.inet.tcp.pcbcount
net.inet.tcp.pcbcount: 37
```
The actual function internally is `static int tcp_pcblist` [found here](https://github.com/freebsd/freebsd-src/blob/afad340a14f85b6519fd2bd2b0dd47153eb18a99/sys/netinet/tcp_subr.c#L2705). That would cover count if that's literally all `GetActiveTcpListeners` is supposed to return in the spec. If it's supposed to return literally any other data, it would need to be handled very differently.

**Comment by wfurt** [comment]
For UDP, I think we expect only the count. For TCP we expect back list of IPEndPoints e.g. address and port. 
The failing test opens listening socket and then it expects it in the list.
