### ISSUE TITLE
[wasm] Simple linear search

### ISSUE THREAD

**Issue by iXyles** [dotnet/runtime#64455]
### Description

When performing a linear search in wasm it can become very slow once the list of items is getting bigger.
Yes - I do understand that a linear search is not a recommended thing to do in a scenario like this one, but the performance difference is the issue I wanna highlight.

### Configuration

* Which version of .NET is the code running on?
.NET 6 (6.0.1 to be exact)
* What OS version, and what distro if applicable?
Windows 11 Pro (two different machines)
* What is the architecture (x64, x86, ARM, ARM64)?
x64 architecture
* If relevant, what are the specs of the machine?
Specs not relevant regarding this issue

### Regression?

No, I have not done a similar test with previous versions then .NET 6 as it is not suitable for the use-case

### Data

Minimal repro project can be found here: https://github.com/iXyles/wasm-performance-issue-sample

Data in this case is random generated GUID's (3000 of them, which are added to a list)
Iterated to find the last item (worst case scenario) 5000 times

### Analysis

The issue seems to be related to wasm only, as the same code runs 87 times faster in a console app

### Anything else?

Blazor WASM 6.0.1
Chrome Version 97.0.4692.99 (Official Build) (64-bit)

Image of difference - wasm vs console app (64-bit on same windows machine)
![test-time](https://user-images.githubusercontent.com/5310286/151586389-d34fd471-c4a0-4b2d-800c-dea10a20429c.png)

**Comment by iXyles** [comment]
Noticed this morning that apparently when creating a WASM (webassmebly) project, the RunAOTCompilation flag is not on per default. This change the behaviour drastically and starting to see similar performance as a console app, just some minor overhead.

**Comment by iXyles** [comment]
Any updates regarding this? :)

**Comment by BrzVlad** [comment]
I remember checking the codegen for the mono interpreter for this test case and there was nothing fishy there. Don't think I tried on wasm. Will revisit in the next weeks.

**Comment by BrzVlad** [comment]
I'm unable to properly test this due to current limitations related to cryptography. However based on my investigation, there is no difference in code for the microbenchmark path compared to desktop, so I'd expect this benchmark to be between 6-10 times slower than coreclr on desktop (somewhat slower when using MoveNext). Some external factors that can make it seem like the code is much slower are: unless the application is published, debugging will be enabled, disabling all interpreter optimizations and sometimes the js engine might not tier up the interpreter execution loop in the case of microbenchark. This can easily make wasm seem over 10 times slower when running with interpreter.
