### ISSUE TITLE
Intermittent issues while executing "CoCreateInstance" to native c++ target

### ISSUE THREAD

**Issue by srikrishnag** [dotnet/runtime#64516]
### Description

We are making interop calls from c# to c++, and at times we are getting 0x80080005 (CO_E_SERVER_EXEC_FAILURE) while calling CoCreateInstance, we have a pause and retry mechanism as a work around but it is was not helping to avoid such scenarios.

Below is the root error from the thread dump:-
_File:        C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll
String:      Retrieving the COM class factory for component with CLSID {guid} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE))._

### Reproduction Steps

This is very intermittent and happens on any of the machine and happens once in 2 months/3 months.

### Expected behavior

Should fail fast and consequent retry should succeed in creation of CoCreateInstance

### Actual behavior

Request is getting struck in CoCreateInstanc, without any progress in succeeding the object creation.

### Other information

Below is the code snippet where we have the issue.
`while (!initialized)
            {
                try
                {
                    ++attempt;
                    **this.wsm = new XYZ();**
                    initialized = true;
                }
                catch (COMException ex)
                {
                    if (ex.ErrorCode == -2146959355 && attempt < 5) // HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)
                    {
                        Log.Trace(
                            Log.TRACE_LEVEL_ERROR,
                            Log.Config,
                            "Unable to initialize XYZ- Attempt %d. \n",
                            attempt);
                        Thread.Sleep(500);
                    }
                    else
                    {
                        // If 5th attempt was also not successful, then throw
                        throw;
                    }
                }
            }`

**Comment by AaronRobinsonMSFT** [comment]
This appears to be a .NET Framework scenario, not .NET 5+. Additionally, the resulting `HRESULT` is typically caused by an out-of-proc COM server that is slow to activate and is unlikely to be a .NET issue. The abstraction of calling `CoCreateInstance` is by-design and complex scenarios involving slow responding COM servers should be handled by calling `CoCreateInstance` directly using a P/Invoke.

Let's move this issue to [Developer Community](https://developercommunity.visualstudio.com/home) where we can pull in additional resources to help.
