### ISSUE TITLE
Regex ranges with unicode chars

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#64519]
### Description

Testing for the regular expression `[💩💪💫]` works fine. The unicode numbers for these chars are 

- `U+1F4A9`
- `U+1F4AB`
- `U+1F4AC`

When using ranges like `[💩-💫]` I am getting the `[x-y] range in reverse order` error.

I also tried `[💫-💩]` with the same exception. 

### Reproduction Steps

```c#
using System;
using System.Text.RegularExpressions;

Console.WriteLine(new Regex("[💩💪💫]").IsMatch("💩")); // Success
// Console.WriteLine(new Regex("[💩-💫]").IsMatch("💩")); // RegexParseException
// Console.WriteLine(new Regex("[💫-💩]").IsMatch("💩")); // RegexParseException
```

### Expected behavior

The range should be valid.

### Actual behavior

The range is not valid.

### Regression?

Confirmed in 4.6.1, netcoreapp3.1 and net6.0

**Comment by stephentoub** [comment]
Regex only looks at single System.Char units. U+1F4A9 for example is two Chars that, from Regex 's perspective, are independent. "[💩-💫]" is "[\ud83d\udca9-\ud83d\udcab]", so it just looks at the individual Char values, it sees "\udca9-\ud83d", which is not ordered, hence the error. This is a limitation of Regex that's existed since it was added, and there are currently no plans to improve that.

**Comment by danmoseley** [comment]
`Console.WriteLine(new Regex("(?:\ud83d[\udca9-\udcab])").IsMatch("💩")); ` would be a workaround, assuming the string is well-formed UTF-16 (which is not guaranteed)
