### ISSUE TITLE
Reducing minimum default size of .NET 6.0 app

### ISSUE THREAD

**Issue by demberto** [dotnet/runtime#64524]
The minimum size of a release build of a .NET 6 app is about 135KB on Windows for a simple Hello World program. Take that code, paste it on a .NET framework project and the release build size is negligible. What can I do to reduce the size? Why does it take this much space to begin with? Its not a issue, but knowing helps

**Comment by Symbai** [comment]
> .NET 6 app is about 135KB on Windows for a simple Hello World program

.NET is always overloaded comparing to other languages. No matter what you do with .NET. For example building with Winforms or WPF and using self contained to make sure it just runs on every Windows computer gives you 140mb, and no you cannot use trim feature here. Using NativeAOT a simple console program is about 5mb large, the same on a language like C++ or Delphi is below 1mb. If size matters SO much then .NET is not your choice. If coding friendliness matters more than size, then .NET is your choice.

**Comment by kasperk81** [comment]
> comparing to other languages.

author has asked question about .net application size in comparison with .net framework application size, not with any other language..

**Comment by tomrus88** [comment]
This difference is because .NET Framework runtime is integrated into OS (and its size isn't small) while .NET (Core) is decoupled and requires additional things for apps to run.

That 135KB exe you talking about performs additional tasks like searching installed runtime, starting that runtime and then executing your app.dll on that runtime.

**Comment by Symbai** [comment]
> author has asked question about .net application size in comparison with .net framework application size, not with any other language..

But its a .NET thing. If the .NET Framework wouldn't be part of the OS (Windows) already the executable would also be bloated up that much, @tomrus88 already explained that. Only way to reduce it further is to integrate some kind of .NET (Core) runner into Windows. But then again the size would only shrink for Windows executables.

**Comment by demberto** [comment]
@Symbai IDK what 140mb app you talk about, maybe UWP, it easily takes a few GBs per project. FYI, In .NET framework the executable is actually smaller than its equivalent C++/Delphi would be. .NET (not core, just plain .NET - awesome naming MS) is actually good

The size isn't an issue as I mentioned, I just wanted to know what is the purpose of the extra size. @tomrus88

**Comment by vitek-karas** [comment]
We've actually looked at what it would take to reduce the size of the apphost (the executable which is cca 150KB right now). It's relatively simple: rewrite it in C. Currently it's C++ using relatively small set of features from CRT, but those get us the 150KB. With pure C, my guess is that the exe would probably go down to around 50KB, if not less. But it will never be as small as .NET Framework, it really can't because the `app.dll` in .NET (Core) is basically exactly what your `app.exe` in .NET Framework is, on top of that we need the `app.exe` and currently at least the `.runtimeconfig.json` and `.deps.json` files.

**Comment by demberto** [comment]
@vitek-karas Ahh, this explains why IDA tells that the EXE is compiled with MSVC C++14 feature set. Why is that your require per process apphost? How about moving the apphost code itself to .NET? Because the assembly itself is almost always smaller than 150KB (I imagine it would require a significant amount of code to reach that size after getting compiled), a launcher process bigger than that kinda defeats the small size advantage .NET has. Also the JSON can be embedded inside the executable itself like how the manifest is stored, so the resulting output directory can be less messy

**Comment by vitek-karas** [comment]
The .exe must be native code, it can't be .NET. .NET code (or IL) is not directly executable by the OS, it needs the .NET runtime to run. So there has to be something which loads the runtime first. As described above, for .NET Framework this piece is part of Windows OS. For .NET (Core) it's not (many reasons, but for example it would not be possible on Linux/Mac).

In theory we could write it in .NET and use Native AOT to build the apphost with .NET and compile it all the way down to machine code, but that would make it even bigger.

You can already reduce the number of files by using single-file. Publish your app with `dotnet publish -r winx64 --self-contained false -p:PublishSingleFile=true`. This will produce just one executable which is roughly those 150 KB (for a console hello world, will be bigger the more code you add to the app).
