### ISSUE TITLE
GZipStream calling Flush before Dispose cause in more data being written when compressing

### ISSUE THREAD

**Issue by johnthcall** [dotnet/runtime#64590]
### Description

Calling Flush before Dispose vs just Dispose on a compression GZipStream results in a larger output to the base stream. Both outputs appear to properly decompress to the input. This is a change in functionality from Net Framework 4.7.2.

### Reproduction Steps

```
var testBytes = Encoding.UTF8.GetBytes("A");
using (var memoryStream = new MemoryStream())
{
    using (var gZipStream = new GZipStream(memoryStream, CompressionMode.Compress, true))
    {
        gZipStream.Write(testBytes, 0, testBytes.Length);
    }
    Console.WriteLine(String.Join(" ", System.Linq.Enumerable.Take(memoryStream.GetBuffer(), (int)memoryStream.Length)));
}
```
prints "31 139 8 0 0 0 0 0 0 10 115 4 0 139 158 217 211 1 0 0 0"
if `gZipStream.Flush();` is added after the write to the stream it instead prints
"31 139 8 0 0 0 0 0 0 10 114 4 0 0 0 255 255 3 0 139 158 217 211 1 0 0 0"

### Expected behavior

I expect that regardless of whether flush is called before disposing the GZipStream that the same output is produced.

### Actual behavior

A larger amount of data is instead written.

### Regression?

This issue exists in .Net 5 and .Net 6 but in .Net Framework 4.7.2 regardless of flushing the output is the same as in .Net 5/6 without flushing.

### Configuration

.Net 6.0.1 on Windows 11 running the samples on x64

**Comment by stephentoub** [comment]
Flush on .NET Framework was a nop: all it did was ensure the stream wasn't disposed.  We fixed that in .NET Core in https://github.com/dotnet/corefx/pull/4879, and what you're seeing is a by-design side-effect of that.  Upon Dispose, the stream needs to write out a footer; when Flush is called, it doesn't know whether more data will be written subsequently, and so it can't write out that final footer, and Dispose can't undo what was previously done by Flush.

**Comment by johnthcall** [comment]
Thanks @stephentoub should we add a remark in Flush or at the class level for this behavior?

**Comment by stephentoub** [comment]
> should we add a remark in Flush or at the class level for this behavior?

That says Flush flushes as requested?

**Comment by johnthcall** [comment]
The remark could be that the Footer is written as part of the Dispose since in most Stream implementations I've seen Dispose is purely for releasing objects and does not write to the base stream. Even though it appears that after Flush but before Dispose the content written can be decompressed successfully in .Net won't it not include the CRC footer?

**Comment by stephentoub** [comment]
> The remark could be that the Footer is written as part of the Dispose since in most Stream implementations I've seen Dispose is purely for releasing objects and does not write to the base stream

Many streams write as part of Dispose, flushing contents to their target. And many streams have the actual data written impacted by flushing. Flushing an SslStream will cause a packet to be written with the data, and as packets have overhead, calling Flush impacts the amount of data written. If you write two bytes to a NetworkStream vs writing one byte and then writing the second byte, that will likely impact the number of bytes on the wire because each write may get its own TCP packet. If you flush compression streams, there are headers typically required in most formats for every chunk of data (otherwise you often have to know in advance exactly how much data is required). If you have a stream for an HTTP chunked stream, every flush requires extra bits for the header/footer of the chunk, and there's a final ending footer that'll need to be output as part of closing / signaling no more data is going to come. CryptoStream needs to write a final transformed chunk. Etc. It's actually very common, which is why DisposeAsync was introduced ; that wouldn't be needed if IO wasn't done during disposal.

> Even though it appears that after Flush but before Dispose the content written can be decompressed successfully in .Net won't it not include the CRC footer?

Given that Flush is a nop in. NET Framework, I don't see how that could be reliable, as it's very likely there's still unflushed data that hasn't even left memory yet. And even if that happened to work out based on implicit flushing when buffers are full, if it's true that the crc is being ignored, that's arguably a bug, not something to emulate.

**Comment by johnthcall** [comment]
Thanks for the response, closing this issue!
