### ISSUE TITLE
[API Proposal]: remove dependency on System.Drawing.Common from System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by abelykh0** [dotnet/runtime#64592]
### Background and motivation

.Net 6 introduced a breaking change in the Windows compatibility (see https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). The motivation is to make `System.Runtime.Caching` to not require dependency on "not recommended" `System.Drawing.Common` (via `System.Windows.Extensions`).

### API Proposal

Somehow hide the dependency on `System.Drawing.Common` from `System.Runtime.Caching`, even if `System.Drawing.Common` it is used internally.

### API Usage

N/A

### Risks

Backward compatibility

**Comment by abelykh0** [comment]
Please look at https://github.com/dotnet/runtime/issues/62649 for more comments.

**Comment by ericstj** [comment]
Here the dependency is coming from https://github.com/dotnet/runtime/blob/53d52884198b15d83e1d9c2ce8009ef2c6a015c2/src/libraries/System.Runtime.Caching/src/System.Runtime.Caching.csproj#L81

System.Configuration.ConfigurationManager -> System.Security.Permissions -> System.Security.Permissions -> System.Drawing.Common

The dependency from ConfigurationManager on down is public API, so it cannot be broken without impacting binary compatibility.  The dependency between Caching and ConfigurationManager appears to be implementation only, so this could be hidden with `PrivateAssets="Compile"`.

@abelykh0 -- you may not want to expose a dependency on `System.Runtime.Caching` either.  It was ported for .NETFramework compatibility and its dependencies reflect that.  Any reason you can't mark it with `PrivateAssets="Compile"` at the point of reference to `Caching`?  Are you exposing it in your public API?

**Comment by abelykh0** [comment]
> @abelykh0 -- you may not want to expose a dependency on `System.Runtime.Caching` either. It was ported for .NETFramework compatibility and its dependencies reflect that. 

What is the correct assembly to use instead of `System.Runtime.Caching`? We need only Linux and Windows support.

**Comment by ericstj** [comment]
Here's what the [docs](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-6.0#systemruntimecachingmemorycache) say. cc @davidfowl @StephenMolloy

> Microsoft.Extensions.Caching.Memory/IMemoryCache (described in this article) is recommended over System.Runtime.Caching/MemoryCache because it's better integrated into ASP.NET Core. For example, IMemoryCache works natively with ASP.NET Core dependency injection.

>Use System.Runtime.Caching/MemoryCache as a compatibility bridge when porting code from ASP.NET 4.x to ASP.NET Core.

Here's some interesting discussion from when that doc was created: https://github.com/dotnet/AspNetCore.Docs/issues/8478#issuecomment-420043847

**Comment by abelykh0** [comment]
Thanks! I will consider migrating then.

**Comment by AraHaan** [comment]
Here is a fun one: System.Configuration.ConfigurationManager -> System.Security.Permissions  -> System.Security.AccessControl (which the package reference could be removed on the package version of System.Security.Permissions)

Why? because I run into this issue with SqlClient referencing S.C.CM 5.0.0, which references S.S.P 5.0.0 which references S.S.AC 5.0.0 which is a part of the runtime and ref packs so it should be using the version from there since S.S.P is not in the base runtime for some reason (along with S.C.CM).

**Comment by AraHaan** [comment]
Edit: it seems S.S.P is for Code Access Security which can be removed.

**Comment by NickCraver** [comment]
For what it's worth, we're getting questions about this due to CVEs in `System.Drawing.Common` when we're using performance counters upstream (`System.Diagnostics.PerformanceCounter` => `System.Configuration.ConfigurationManager`) - admittedly this dependency chain just going by names doesn't make a lot of sense to me either, but it's present even in the latest versions: https://github.com/StackExchange/StackExchange.Redis/issues/2283

**Comment by AraHaan** [comment]
Perhaps one should comb through all of the libraries in this repo for code that uses CAS (Code Access Security) so they can be removed (and their dependency on S.S.P) so that way they do not use a feature that afaik are no-ops anyway.

If they reference a nuget package version of the libraries from this repository in .NET Framework apps, then it could be conditionally only to use it from those frameworks, but I feel that it should be the only place where CAS apis should be called (under ``#if NETFRAMEWORK``).

**Comment by ericstj** [comment]
We've already removed nearly all usage of System.Security.Permissions in the dotnet/runtime libraries.  

The two cases remaining are DirectoryServices and ConfigurationManager and these are for public API.

We could try to push the public API down into System.Security.Permissions, type forward to it, then keep the dependency on System.Security.Permissions private (IOW dangling from Package graph perspective).  This would allow for retaining binary compatibility with existing API but trimming S.S.P out of the package graph.  We do have some precedent for this in that we have dangling dependencies for typeforwards elsewhere (eg: inbox mscorlib) however we haven't done so in packages.

The challenge with pushing types down might be that those types might rely on other types which we can't push down.   Dangling dependencies are OK for type-forwards since you only need those types if they're actually used, but if the types are used in other scenarios then it gets harder since you don't want to introduce exceptions in working scenarios.

**Comment by steveharter** [comment]
Per offline discussion with @buyaa-n it appears that the reference in CM to SSP is due to [System.Configuration.Internal.IInternalConfigHost.GetRestrictedPermissions()](https://github.com/dotnet/runtime/blob/895c99cc502913fd7393b95af7cae5b9e6fbdea3/src/libraries/System.Configuration.ConfigurationManager/ref/System.Configuration.ConfigurationManager.cs#L1387) and [GetRestrictedPermissions.DelegatingConfigHost.GetRestrictedPermissions(](https://github.com/dotnet/runtime/blob/895c99cc502913fd7393b95af7cae5b9e6fbdea3/src/libraries/System.Configuration.ConfigurationManager/ref/System.Configuration.ConfigurationManager.cs#L1477)) both of which are in the "[internal](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.internal?view=dotnet-plat-ext-6.0
)" namespace and not actually called from the framework's libraries.

We could then just remove those two methods. I haven't actually tested the removal of SSP however to ensure these are the only references.

**Comment by ericstj** [comment]
I put together a quick prototype of this.  DirectoryServices can push types down without breaking any API.  All dangling references are for typeforwards and none of those types are used by the implementation.

Configuration manager cannot push down any types.  As @steveharter mentioned, it's single reference to System.Security.Permissions is due to an interface method and it's implementations.  There are no callers to this inside the assembly, however there are implementations.  We may be able to get away with just leaving a dangling reference for this if the JIT is sufficiently lazy in compiling that method (and loading S.S.P).  
https://github.com/ericstj/runtime/commit/3426ddda056ea3a5838dadcc873b97d40fc1087d attempts this.  I didn't test it thoroughly to determine if it was viable.

Also as @steveharter suggests we might just remove the member from the interface - that would be minimally breaking -- only to callers of the method or explicit implementers (which would be very rare, especially since it's designated internal).
https://github.com/ericstj/runtime/commit/05a396e7251caf2c219a31a8c9427bc9b453e20e does this.

**Comment by 0xced** [comment]
I've just been hit by the `System.Windows.Extensions` → `System.Drawing.Common` dependency too.

I'm trying to migrate to [FastReport.Core.Skia](https://www.fast-report.com/en/blog/show/fastreport-core-skia/) which has replaced `System.Drawing.Common` with the Skia graphics engine. In order to ease migration, `FastReport.Core.Skia` includes an API almost identical to the `System.Drawing.Common` API (through the `FastReport.SkiaDrawing` package). It is even using the `System.Drawing` namespace (that was probably not a great idea but here we are)! Consequently it is not possible to have a dependency on `System.Drawing.Common`, else compilation errors ensue:
> [CS0433] The type 'FontFamily' exists in both 'FastReport.SkiaDrawing, Version=2022.3.0.0, Culture=neutral, PublicKeyToken=406e1f4c3c8ef97e' and 'System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

But unfortunately, the project I'm working on depends on `System.Drawing.Common` through an unexpected chain starting from a database driver!
```mermaid
graph
Oracle.ManagedDataAccess.Core --> System.DirectoryServices --> System.Security.Permissions --> System.Windows.Extensions --> System.Drawing.Common
```

Fortunatley, it is possible to get rid of the `System.Drawing.Common` dependency with a simple [MSBuild trick](https://stackoverflow.com/questions/59498770/how-to-excludedisable-packagereferences-transitivedependency-in-msbuild/59522307#59522307):
```xml
<Target Name="RemoveSystemDrawingCommon" AfterTargets="ResolveAssemblyReferences">
  <ItemGroup>
    <ReferencePath Remove="@(ReferencePath)" Condition="%(ReferencePath.NuGetPackageId) == 'System.Drawing.Common'" />
  </ItemGroup>
</Target>
```

I'm pretty sure that the Oracle database driver does not depend on `System.Drawing.Common` at runtime so removing it should not cause any issue.

**Comment by AraHaan** [comment]
Sadly, DirectoryServices seems like it does. However, I think that package might be in the same boat with S.C.CM as well.

**Comment by danmoseley** [comment]
Came up with internal customer, they depend on a package depending on AppInsights eventually to Configuration then Drawing and thus needing an unexpected update. So another +1 for any snip that can be done to this chain.

**Comment by steveharter** [comment]
>... We may be able to get away with just leaving a dangling reference for this if the JIT is sufficiently lazy in compiling that method (and loading S.S.P).
https://github.com/ericstj/runtime/commit/3426ddda056ea3a5838dadcc873b97d40fc1087d attempts this. I didn't test it thoroughly to determine if it was viable.

> Also as @steveharter suggests we might just remove the member from the interface - that would be minimally breaking -- only to callers of the method or explicit implementers (which would be very rare, especially since it's designated internal).
https://github.com/ericstj/runtime/commit/4d0c588fe77c435454d3c57a72c6d56bdffa8b9d does this.

The first approach depends on behavior that may be nondeterministic and requires testing. The second approach, being fully deterministic and cleaner, seems preferred to me at this point (I don't know if there are external implementors of IInternalConfigHost).

**Comment by danmoseley** [comment]
@marklio has the ability to scan nuget for implementors of `IInternalConfigHost` if you reach out.

**Comment by CumpsD** [comment]
We hit this today with Microsoft.Data.SqlClient when we were trying to eliminate System.Drawing.Common from our dependencies

**Comment by AraHaan** [comment]
Let me see if I can take a stab at this and find other usages of S.S.P and S.D.C in the 2 dependencies mentioned and see if they can be completely removed without breaking public facing API. And if it does break, I think it should be ok for breakage in .NET 8 for sake of API cleanup of deprecated no-op feature usage (or at least have the removed parts be specific to ``NETFRAMEWORK``).

**Comment by AraHaan** [comment]
The methods in S.C.CM can be put under ``#if NETFRAMEWORK`` it seems as it only is used in 3 places (internally but exposed publicly). An analyzer can also be added to also error when they use internal apis from S.C.CM as well (like what efcore does but instead of warning it is a hard error).

![image](https://user-images.githubusercontent.com/15173749/211206569-55ec3cc5-6016-4e2b-a7cd-48b3559d1d52.png)

After I removed those methods, the code compiled.

**Comment by AraHaan** [comment]
And I done the same for ``System.DirectoryServices``, however it comes with the following changes that could be breaking for some:

<details>
<summary>diff (ref):</summary>

```diff
+ #if NETFRAMEWORK
    public sealed partial class DirectoryServicesPermission : System.Security.Permissions.ResourcePermissionBase
+ #else
+     public sealed class DirectoryServicesPermission
+ #endif
    {
        public DirectoryServicesPermission() { }
        public DirectoryServicesPermission(System.DirectoryServices.DirectoryServicesPermissionAccess permissionAccess, string? path) { }
        public DirectoryServicesPermission(System.DirectoryServices.DirectoryServicesPermissionEntry[]? permissionAccessEntries) { }
+ #if NETFRAMEWORK
        public DirectoryServicesPermission(System.Security.Permissions.PermissionState state) { }
+ #endif
        public System.DirectoryServices.DirectoryServicesPermissionEntryCollection? PermissionEntries { get { throw null; } }
    }
```
</details>
<details>
<summary>diff (src):</summary>

```diff
    [Obsolete(Obsoletions.CodeAccessSecurityMessage, DiagnosticId = Obsoletions.CodeAccessSecurityDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
+ #if NETFRAMEWORK
    public sealed class DirectoryServicesPermission : ResourcePermissionBase
+ #else
+     public sealed class DirectoryServicesPermission
+ #endif
    {
        public DirectoryServicesPermission() { }
        public DirectoryServicesPermission(DirectoryServicesPermissionEntry[]? permissionAccessEntries) { }
+ #if NETFRAMEWORK
        public DirectoryServicesPermission(PermissionState state) { }
+ #endif
        public DirectoryServicesPermission(DirectoryServicesPermissionAccess permissionAccess, string? path) { }
        public DirectoryServicesPermissionEntryCollection? PermissionEntries { get; }
    }
```
</details>

**Comment by ericstj** [comment]
For DirectoryServices we can do this in a less breaking way if we just move DirectoryServicesPermission into System.Security.Permission, then add a type-forward from DirectoryServicesPermission to System.Security.Permission and put `PrivateAssets="All"` on the project reference so that we leave the dependency out of the nuspec.  That's what I prototyped in this change: https://github.com/ericstj/runtime/commit/3426ddda056ea3a5838dadcc873b97d40fc1087d#diff-c7413ea7bade71198dd11d098dc4707989ecdf075fa31c65ea9afcb2cfc61092R13

IMO this is less breaking and it's an acceptable dangling dependency.  We have similar dangling dependencies for typeforwards in other compatibility shims (mscorlib, system, system.core, etc)

**Comment by AraHaan** [comment]
I agree, I personally thing that S.S.P should be removed entirely from everything with how most of that assembly is either stubs that do nothing at all or minor things that can probably be moved into corelib (I think moving some of it to corelib would be even better).

**Comment by steveharter** [comment]
Closing based on https://github.com/dotnet/runtime/pull/82259 and https://github.com/dotnet/runtime/pull/82453.
