### ISSUE TITLE
Assemblies compiled in 6.0 and main contain an incorrect TargetPlatformAttribute in their metadata

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#64616]
When looking at the i.e. linux net6.0 runtime asset of System.Data.Odbc under `runtimes\linux\lib\net6.0\System.Data.Odbc.dll` from the [latest stable version of the package](https://www.nuget.org/packages/System.Data.Odbc/6.0.0) I just noticed that the `TargetPlatform` attributes are wrong:

`[assembly: TargetPlatform("Linux1.0")]` or `[assembly: TargetPlatform("Solaris1.0")]`.

I'm unsure what the impact of the wrong platform version is but I wanted to bring this to the team's attention.

cc @jeffhandley @ericstj

**Comment by ericstj** [comment]
Looks like @buyaa-n noticed this too and filed https://github.com/dotnet/sdk/issues/14836
@dsplaisted introduced the behavior in https://github.com/dotnet/sdk/pull/13672.

I'm not sure when if compiler / design time would ever see the `runtimes` implementation libraries.  I don't expect it would ever do so.  Would folks familiar with why the SDK does this chime in?  

This might mean it's just a cosmetic issue -- still worth fixing.  IMO we should just omit it since we aren't targeting a "TargetPlatform" in the same way the SDK sees it.

**Comment by safern** [comment]
ping @dsplaisted @marcpopMSFT could you please chime in?

**Comment by safern** [comment]
cc: @jeffhandley

**Comment by dsplaisted** [comment]
What's setting the TargetPlatformVersion to 1.0 in the runtime build?  If you can leave that property empty, then it looks like the `TargetPlatformAttribute` won't be generated.

We could add a property to disable generation of this attribute, but you'd have to wait for a version of the SDK with the fix.

The simplest workaround might be to remove the `AssemblyAttribute` item after it is added.  I think something like this would work:

```xml
<Target Name="RemoveTargetPlatformAttribute" AfterTargets="GetAssemblyAttributes">
    <ItemGroup>
        <AssemblyAttribute Remove="System.Runtime.Versioning.TargetPlatformAttribute" />
    </ItemGroup>
</Target>
```

**Comment by ViktorHofer** [comment]
> What's setting the TargetPlatformVersion to 1.0 in the runtime build?

https://github.com/dotnet/runtime/blob/607dccee09d06ef3f0d4c015da39fcc81117b4eb/eng/targetframeworksuffix.props#L15. That is necessary to make custom platforms which aren't yet understood by nuget/sdk work, i.e. net7.0-unix.

**Comment by ViktorHofer** [comment]
That got fixed with https://github.com/dotnet/runtime/commit/4c2ea7e9010e9c71bfba332e430e92f00e19c04e. Closing.
