### ISSUE TITLE
Is GetAwaiter().GetResult() cause a deadlock ?

### ISSUE THREAD

**Issue by melfeqy** [dotnet/runtime#64849]
I have .net 6 web application and i'm in situation that i'm **forced** to call  async method from sync method.

I read two  opinions in this case

**First opinion:** since I'm working on .net 6 and there is no SynchronizationContext so no fear from deadlock

https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

**Second opinion:** If you’re writing a dotnet core web application, you’re basically running everything on the thread pool. Any blocking code will block the thread pool and any .Result will lead to a deadlock

https://medium.com/rubrikkgroup/understanding-async-avoiding-deadlocks-e41f8f2c6f5d

Please advise is deadlock may happen and if yes what the best way to call async method from sync with avoid deadlock ?

Thanks

**Comment by melfeqy** [comment]
@stephentoub Any advice please ?

**Comment by stephentoub** [comment]
Blocking a thread on the thread pool doesn't necessarily lead to deadlock; it's just preventing that thread from doing anything else until the blocking completes, which means the number of threads available to do other work is decreased.  If the thing you're blocking on will itself require a thread pool thread to do work, then you're relying on there being another thread available in the pool at some point in order to release this thread.  So if you were in a pool with a max number of threads, it could deadlock.  In the .NET ThreadPool, there is a max, but it's very high, e.g. in a 64-bit process it defaults to a max of ~32K.  So it's typically rare that you'd actually see a true deadlock due to blocking a thread pool thread.  What's much more likely is that you see delays / spikes in latency.  At any given point in time the thread pool has some number of available threads, and if you block some, that will decrease the number of threads available to process other work.  If you block all of them, work will likely slow to a crawl or appear as a temporary deadlock.  At some point the ThreadPool should notice via one of multiple mechanisms that it would likely be beneficial to inject more threads, but that can take time.

As for the best way, there's fundamentally no perfect way.  If you absolutely must the calling thread, then there's really no other choice.  You can try to come up with complicated schemes for using that thread to pump other work, but every other scheme has its own flaws.

Best answer is change the code to not require blocking.  Next best answer is change the code that requires running synchronously  to only use synchronous operations.  Beyond that, close your eyes and hope for the best.

**Comment by melfeqy** [comment]
@stephentoub  Thank you
