### ISSUE TITLE
Test failure System.PrivateUri.Tests.UriCreationOptionsTest.DisableCanonicalization_WorksWithDifferentSchemes

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64889]
Run: [runtime-coreclr libraries-jitstress 20220205.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1595350&view=ms.vss-test-web.build-test-results-tab&runId=44606902&paneView=debug&resultId=129343)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open

- System.PrivateUri.Tests.UriCreationOptionsTest.DisableCanonicalization_WorksWithDifferentSchemes(scheme: \"custom-registered\")

```
**Error message:**
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'defaultPort')


Stack trace
   at System.UriParser.Register(UriParser uriParser, String schemeName, Int32 defaultPort) in /_/src/libraries/System.Private.Uri/src/System/UriScheme.cs:line 181
   at System.PrivateUri.Tests.UriCreationOptionsTest.DisableCanonicalization_WorksWithDifferentSchemes(String scheme) in /_/src/libraries/System.Private.Uri/tests/FunctionalTests/UriCreationOptionsTest.cs:line 218
```

**Comment by jakobbotsch** [comment]
I assume the problem here is that passing `0xffff` as the port to `UriParser.Register` is invalid:
https://github.com/dotnet/runtime/blob/8006e6a89bc02e410331e6323e3f6321b224b327/src/libraries/System.Private.Uri/src/System/UriScheme.cs#L177-L178
and the test does so every 1/2^16 runs:
https://github.com/dotnet/runtime/blob/fe50d91a99dc17f8b3cbbb18103a7e8dca051075/src/libraries/System.Private.Uri/tests/FunctionalTests/UriCreationOptionsTest.cs#L218

Not sure whether the test is wrong or `UriParser.Register` is wrong, so will defer to area owner on this.

**Comment by MihaZupan** [comment]
The check is `UriParser.Register` is wrong here. Should be `[-1, 0xFFFF]`.
