### ISSUE TITLE
In-box SymmetricAlgorithm implementations do not check for disposal

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#64924]
Consider the following:

```csharp
var key = new byte[]
{
    0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00,
    0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF,
};

Aes aes = Aes.Create();
aes.Key = key2;
Console.WriteLine(Convert.ToHexString(aes.Key));
aes.Dispose();
Console.WriteLine(Convert.ToHexString(aes.Key));

/*
Output:
FF00FF00FF00FF0000FF00FF00FF00FF
C466F8E68B887B480B10AFA162CDEA2F <- new random key
*/
```

`Dispose` wipes the current `Key` and nulls it out, so the next access of it generates a new key.

That means the encrypt/decrypt one shots, and `CreateEncryptor()` and `CreateDecryptor()` will not use the expected key after disposal, but rather a randomly generated one.

I think we should throw an `ObjectDisposedException` if you attempt to use a disposed SymmetricAlgorithm instance.

**Comment by vcsjones** [comment]
@bartonjs is there some "But .NET Framework" compat concern with fixing this?

**Comment by bartonjs** [comment]
There's definitely at least "some" compat concern :)

* AesCryptoServiceProvider didn't allow `CreateEncryptor()` to be called unless set_Key was performed, GenerateKey was called, or get_Key was read, implicitly calling GenerateKey.
  * https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/AesCryptoServiceProvider.cs,5f82967c8ea522c8,references
  * Disposing the instance puts it into a state that looks quite similar to the freshly instantiated case.
  * The exception here is CryptographicException, not ObjectDisposedException.
* AesManaged just wraps/defers to RijndaelManaged (unless FIPS mode is set, and then it defers to AesCryptoServiceProvider)
* RijndaelManaged doesn't override the parameterless CreateEncryptor, so it uses the property getters and cascades.
  * It also doesn't override the Key property, so it has the default behavior of calling get_Key calls GenerateKey when there is no key
  * And it has a default Dispose, which nulls the key out, making it look the same as a freshly created object.

From those "two" types, then, it looks like the design of SymmetricAlgorithm has always been that Dispose is rehydrating, at least with reference to CreateEncryptor/CreateDecryptor.  Since we don't have the Encrypt[Mode] or Decrypt[Mode] members in .NET Framework we can certainly make them be more "Dispose means Dispose."

**Comment by bartonjs** [comment]
If there's a practical benefit to eliminating the rehydrating behavior, and we find it hard to believe that someone would be relying on it, we can always try to make the break.  But if we're just doing it for purity's sake I don't think it's worthwhile.

**Comment by vcsjones** [comment]
> If there's a practical benefit to eliminating the rehydrating behavior

Probably not then, and it's a little complicated by that `Clear` actually just calls `Dispose` so that would need to be another "break".

It's a little odd to me, but, c'est la vie.
