### ISSUE TITLE
Application fails to start using System.Runtime.Experimental 6.0.1 with .NET 6.0.2

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#65018]
### Description

Attempting to run a self-contained deployment of a ASP.NET Core application using the .NET 6.0.102 SDK with System.Runtime.Experimental 6.0.1 fails with the following error when run.

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

This appears to be related to the fix for #62840 in #63525.

This can be worked around by using version `6.0.2-mauipre.1.22054.8` of the package so that the version numbers align.

### Reproduction Steps

Clone https://github.com/martincostello/adventofcode/commit/60fbfa4076b430b0da70d8c8021a8502bb2585d7 and then run the following commands:

```pwsh
.\build.ps1 -SkipTests -Runtime win10-x64
cd .\artifacts\publish
.\AdventOfCode.Site.exe
```

### Expected behavior

The ASP.NET Core application starts using the NuGet package that shipped today as part of the .NET 6.0.2 release, rather than requiring the use of a prerelease package for MAUI.

### Actual behavior

The ASP.NET Core application fails to start.

```pwsh
> .\AdventOfCode.Site.exe
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

```

### Regression?

Compared to .NET 6.0.0, yes.

.NET 6.0.1 was broken without a [workaround](https://github.com/dotnet/runtime/issues/62840#issuecomment-996304171) being applied.

### Known Workarounds

Use the [`6.0.2-mauipre.1.22054.8`](https://www.nuget.org/packages/System.Runtime.Experimental/6.0.2-mauipre.1.22054.8) version of the `System.Runtime.Experimental` package.

### Configuration

```pwsh
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.102\
```

**Comment by absid89** [comment]
same error on winforms:
after Visual Studio 17.0.6 update .net SDK updated to 6.0.2


client with 6.0.1 runtime installed, launched the app and got a crash
![runtime601](https://user-images.githubusercontent.com/26306868/153205869-bafaf991-2d0a-4e47-b2b0-ed4b70297f0b.png)

client without runtime, got friendly error with link to download .net 6 runtime
![without_runtime](https://user-images.githubusercontent.com/26306868/153205889-c0f31adf-d873-463b-813f-7eab8a62a08f.png)

**Comment by EatonZ** [comment]
[Related](https://github.com/dotnet/winforms/issues/6663)

**Comment by ericstj** [comment]
> System.Runtime, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

The problem here is that the `AssemblyVersion` should not change.  Can we double check if the package has this change?  If it does we need to fix that -- only FileVersion can change for the reference assembly in servicing.  In the meantime, you can workaround this by using the 6.0.0 version of System.Runtime.Experimental and the workaround from here https://github.com/dotnet/runtime/issues/62840#issuecomment-996304171

@absid89 -- looks like you might be hitting something different.  Care to open a seperate issue and include a full set of repro steps?

**Comment by martincostello** [comment]
Looking at [NuGet package explorer](https://nuget.info/packages/System.Runtime.Experimental/6.0.1), the version in the assembly is indeed 6.0.0.1.

![image](https://user-images.githubusercontent.com/1439341/153276014-99d19e58-77db-472a-9177-7fc188cd03a2.png)

**Comment by ericstj** [comment]
Yes, that agrees with what you're observing.  I was able to see what's happening.  This is what's changing it: https://github.com/dotnet/runtime/blob/ee4640a6a34e4410c7925615569019edf0ff4289/eng/packaging.targets#L48

Looking into why the real System.Runtime in the ref-pack isn't impacted yet this is...

**Comment by safern** [comment]
I think we can add a condition to disable automatically bumping the `AssemblyVersion` when a package is not in the targeting pack and set that flag to true on `System.Runtime.Experimental.`

**Comment by ericstj** [comment]
Do you know why we use `IsNetCoreAppSrc` here
https://github.com/dotnet/runtime/blob/ee4640a6a34e4410c7925615569019edf0ff4289/eng/packaging.targets#L46
That's only defined for a `src` project and not `ref`

Maybe we could use `'$(IsNETCoreAppSrc)' == 'true' or '$(IsNETCoreAppRef)' == 'true'` or create a property.
https://github.com/dotnet/runtime/blob/64f3bae738087a1ec1fd394bfd97c4e4feba5767/src/libraries/Directory.Build.targets#L36-L41

That would have been true for this assembly, since it's named `System.Runtime`

**Comment by tannergooding** [comment]
Is there something we can do to help test/validate/catch these issues before shipping?

**Comment by safern** [comment]
> Do you know why we use IsNetCoreAppSrc here

I believe the wrong assumption was made? https://github.com/dotnet/runtime/pull/57158/files#r687259631

I think this is because we never had cases like the System.Runtime.Experimental scenario where we ship a ref only package and the implementation is inbox.

I think that would be a better solution than what I proposed above.

> Is there something we can do to help test/validate/catch these issues before shipping?

That'd be hard as all these lists are "static" and we could've made the wrong assumption when testing (that we only need to check for `IsNetCoreAppSrc`.

**Comment by absid89** [comment]
> @absid89 -- looks like you might be hitting something different. Care to open a seperate issue and include a full set of repro steps?

sorry i had to write in the winforms thread

**Comment by teo-tsirpanis** [comment]
`System.Runtime.Experimental` 6.0.2 has been released, I ran a small repro that failed with (the now-unlisted) 6.0.1 and works with 6.0.2, and #65733 should have closed this issue but for some reason didn't. So I'm going to close it myself. Feel free to provide feedback if anything went wrong.
