### ISSUE TITLE
What happened with the Common Type System?

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/runtime#65073]
### Description

Weren't the whole  point of the CTS that a string is a string, an int is an int and a DateTime is a DateTime, no matter where it has been created/defined/used?

So how can I then get this error?
(2,94): error CS0029: Cannot implicitly convert type 'System.DateTime [C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0\System.Runtime.dll]' to 'System.DateTime [C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll]'

### Reproduction Steps

C# interactive in VS 2022

```csharp
> public class TestClass
. {
.     public DateTime TestDateTime { get; set; }
. }
> new TestClass() { TestDateTime = DateTime.Now }
// output: Submission#0.TestClass { TestDateTime=[2022-02-09 13:31:49] }

> #r "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0\System.Text.Json.dll"
System.Text.Json.JsonSerializer.Serialize(new TestClass() { TestDateTime = DateTime.Now })
// output: (1,76): error CS0029:
//   Cannot implicitly convert type 'System.DateTime [C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0\System.Runtime.dll]'
//     to 'System.DateTime [C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll]'
```

### Expected behavior

That a DateTime is the same type, no matter in which version of .NET it is defined.

### Actual behavior

DateTime is not the same everywhere

**Comment by vitek-karas** [comment]
> C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0\System.Text.Json.dll

This is a .NET Core assembly (note that it says `Microsoft.NETCore.App`. As mentioned by @hez2010  above your code is running on .NET Framework. You can use `System.Text.Json` on .NET Framework, but you need to get the .NET Framework compatible version of it - you can get that from NuGet: https://www.nuget.org/packages/System.Text.Json/.

**Comment by Bartolomeus-649** [comment]
The issue is about DateTime, and nothing else.

**Comment by vitek-karas** [comment]
It fails on `DateTime` because you're trying to use it from two different versions of .NET. First one is from .NET Framework (4.*) and another one is from .NET 5. Those two are simply not compatible. The reason why you run into this is because you're trying to use the .NET 5 version of System.Text.Json on .NET Framework 4.*, which won't work.

**Comment by Bartolomeus-649** [comment]
We have used DateTime from different versions of .NET for almost two decades now. I can still use a DateTime created in a .NET 2.0 assembly from a new solution based on .NET 4.8.

**Comment by Bartolomeus-649** [comment]
Still, why should it matter which version an assembly/type belong to, as long as the version of the IL being used is the same, then the only thing which should matter is if the type definition is the same or not, right?

**Comment by teo-tsirpanis** [comment]
The two `DateTime` types belong in assemblies with a different name, and they are entirely different and signature-incompatible types in the eyes of the runtime. The containing assembly's name has been part of a type's identity since the beginnings of the .NET Framework and this behavior is by design.

**Comment by danmoseley** [comment]
As @teo-tsirpanis says, the assembly is part of the type identity. In practice, what should happen is either that 
* the library targets the runtime you are executing on. This is called cross targeting. The library's Nuget package contains different copies of the library for different target frameworks, and as part of the restore process the right one is selected) or 
* the library targets .NET Standard. Such libraries "just work" on multiple target frameworks, because the .NET Standard machinery takes care of unifying the types correctly. You can read more about that here https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Let us know if you have more questions.

**Comment by Bartolomeus-649** [comment]
> The two `DateTime` types belong in assemblies with a different name, and they are entirely different and signature-incompatible types in the eyes of the runtime. The containing assembly's name has been part of a type's identity since the beginnings of the .NET Framework and this behavior is by design.

So, what you are saying is that the problem is not with the different versions, but that the signature changed?

**Comment by teo-tsirpanis** [comment]
The problem you reported when opening the issue happened because you referenced a modern .NET assembly from a .NET Framework application, something that is not supported by design.

**Comment by danmoseley** [comment]
@Bartolomeus-649 specifically you're manually referencing a library that declares it targets .NET 5.0 (`...ref\net5.0\System.Text.Json.dll`) but running on .NET Framework 4.8 (or whatever)

Type unification aside, that's not typically going to succeed, because such a library likely uses API's that are only available in .NET 5.0 or later. NuGet would not allow you to reference such a library and hit this problem.

What instead you need to do is to consume the copy from https://www.nuget.org/packages/System.Text.Json/ that targets .NET Framework 4.6.1. If you have a project file, you can reference this with `dotnet add package` or in Visual Studio with `Update NuGet Package` or similar. If you have to reference manually as you're doing here, choose the one out of the net461 folder inside the package.
