### ISSUE TITLE
[API Proposal]: INumber<T> should not implement IUnaryNegationOperators<T, T>

### ISSUE THREAD

**Issue by Timo-Weike** [dotnet/runtime#65147]
### Background and motivation

With the introduction of generic I would assume that the interface `INumber` does not specify if it is signed or unsigned number type.
There for I would remove the `IUnaryNegationOperators<T, T>` from `INumber` and add it to `ISignedNumber`. And also add the interface directly to types like `Unit32` because they have an implementation for it.

But in general it would make no sense to have a negation for unsigned number types.

### API Proposal

```C#
// Like before just without IUnaryNegationOperators
public interface INumber<TSelf> : ... where TSelf : INumber<TSelf> { ... }

public interface ISignedNumber<TSelf> : IUnaryNegationOperators<TSelf, TSelf> ... { ... }

// and add it to the primitytypes directly
// i.e.
public readonly struct UInt32 : IUnaryNegationOperators<UInt32, UInt32 > ... { ... }
```

### API Usage

```C#
// you still can just use - if the compiler knows your number type
uint x = 5;
var y = -x; // here the type would become long because of promotion done by the compiler

// or use a helper class to directly invoke the interface implementation
uint x = 5;
// type will be uint and value will be 4294967291
var y = Helper.Negate(x);

public static class Helper
{
    public static T Negate<T>(T value)
        where T : IUnaryNegationOperators<T, T>
    {
        return -value;
    }
}
```

**Comment by Timo-Weike** [comment]
But if you would like to implement an unbounded type (so no upperbound) for natural numbers you would either

- implement the `IUnsignedNumber` interface and for the negation operator throw a `NotImplementedException` or define a value like `NaN` . Throwing of any generic method only constraining on the `IUnsignedNumber` or `IUnaryNegationOperators` interface, because you either get an exception or you get the same value for all negated numbers
- do not implement `IUnsignedNumber` or `INumber` directly but only the subset of operator interfaces you can/want to support. Reducing the value of the interfaces `INumber`, `ISignedNumber` and `IUnsignedNumber`





> Negation is frequently used with unsigned number types in many kinds of algorithms, particularly in vectorized/simd or perf oriented code.
> 
> The definition for number types in general is effectively `Zero - x`

I also didn't argued that types like `uint` should not implement `IUnaryNegationOperators`, in fact they should because they have a properly defined negation operator.
The negation is in general simply the additive invers for any number so `x + (-x) == AdditiveIdentity` should hold for any type implementing the interfaces `IAdditiveIdentity`, `IUnaryNegationOperators` and `IAdditionOperators`.

But that does not hold for any number type you can think of, beause not all number types have an additive invers.


Also 
> [...] particularly in vectorized/simd or perf oriented code.
code that is mostly interested in performance should not use the `INumber` to constraint its input but declare the number type directly like `uint` or `byte`.

Also also: as you can see in this code
~~~ cs
uint x = 5;
var y = -x;
~~~
if you just negate a `uint` value you do not hit the negation of `uint` but the negation of `long`, because the value is promoted to negate it like the common coder would expect it to.

**Comment by tannergooding** [comment]
> in fact they should because they have a properly defined negation operator.

You are conflating what C# provides (which is not a negation operator on `-` but rather one on `long`) with what .NET is providing.

.NET likewise defines `byte + byte` as `(int)byte + (int)byte = int`; where-as `System.Byte` will define it as `byte + byte = byte` and the upcasting will have to be explicit by the user. .NET is not only supported by C#, it is not the C# Language Runtime. It also supports many other languages and scenarios, including F# which actually behaves like `byte + byte = byte`. 

The interfaces being exposed have been carefully considered against the languages that will/may be supported; what other languages are doing/providing; and the general extensibility and usability that is provided by them in the differing scenarios.

> But that does not hold for any number type you can think of, beacuse not all number types have an additive invers.

Yes, and it is not the aim or goal of these interfaces to support any theoretical type that users may want to implement. It is the aim and goal to provide a set of fine-grained "building blocks" in the form of the `I*Operators` interfaces and some coarser grained interfaces (`INumberBase`, `INumber`, etc) that are more generally usable by the ecosystem in common scenarios.

It is expected that some concepts will be left to be defined and supported by third party libraries and the general community where it makes sense. Now, the APIs we expose should try to cater and not intentionally block certain scenarios, but trying to perfectly match the mathematical model is explicitly not in scope because computer math != real math and there are limitations to what .NET can and should expose. There is actual finite cost to each and every interface/concept we expose here in terms of the general usability, extensibility, and maintainability. There is startup cost incurred for each of these interfaces that are implemented by the primitive types and this includes any interface in the hierarchy (e.g. `INumber` isn't `1 interface`, its some `15-20 interfaces` due to everything it indirectly implements as well).

If some user would like to model the concept of natural numbers, they are free to do so. But that will likely require the user to explicitly build up their own `INaturalNumber` interface and it will limit a number of core scenarios that are required for practical use of the types in a programming environment and the assumptions that most developers will have around number types and what they provide.
