### ISSUE TITLE
System.Text.RegularExpressions performance regressions

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#65187]
Latest manual perf run (.NET 6 vs .NET 7 preview 1) has discovered multiple regressions in System.Text.RegularExpressions. Since most of them were not reported previously, I am opening the issue, so the owners of System.Text.RegularExpressions can triage them accordingly.

I've uploaded a full report [here](https://github.com/adamsitnik/performance/blob/compareRuntimes/src/tools/ResultsComparer/net60_vs_net70p1_regex.md). It's sorted desc from biggest regression to biggest improvement.

The @performanceautofiler has not reported these regressions as they were most likely introduced before the benchmarks were added in November 2021 ([historical data](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern%3a%20%22Sherlock%7cHolmes%7cWatson%7cIrene%7cAdler%7cJohn%7cBaker%22%2c%20Options%3a%20Compiled).html))

Sample repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 net7.0 --filter System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count
```

Sample results:

## System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "Sherlock|Holmes|Watson|Irene|Adler|John|Baker", Options: Compiled)

| Result | Ratio | Operating System     | Bit   |
| ------ | -----:| -------------------- | ----- |
| Slower |  0.43 | Windows 11           | X64   |
| Slower |  0.45 | Windows 11           | X64   |
| Slower |  0.46 | Windows 10           | X64   |
| Slower |  0.42 | Windows 11           | X64   |
| Slower |  0.46 | Windows 10           | X64   |
| Slower |  0.42 | Windows 11           | X64   |
| Slower |  0.43 | Windows 11           | X64   |
| Slower |  0.44 | Windows 11           | X64   |
| Slower |  0.43 | Windows 11           | X64   |
| Slower |  0.43 | ubuntu 20.04         | X64   |
| Slower |  0.45 | ubuntu 18.04         | X64   |
| Slower |  0.40 | centos 7             | X64   |
| Slower |  0.43 | ubuntu 18.04         | X64   |
| Slower |  0.44 | alpine 3.13          | X64   |
| Slower |  0.43 | ubuntu 18.04         | X64   |
| Slower |  0.44 | ubuntu 20.04         | X64   |
| Slower |  0.47 | Windows 10           | Arm64 |
| Slower |  0.32 | Windows 10           | X86   |
| Slower |  0.53 | Windows 10           | Arm   |
| Slower |  0.43 | macOS Big Sur 11.6.3 | X64   |
| Slower |  0.43 | macOS Big Sur 11.4   | X64   |

## System.Text.RegularExpressions.Tests.Perf_Regex_Common.CtorInvoke(Options: Compiled)

| Result | Ratio | Operating System     | Bit   |
| ------ | -----:| -------------------- | ----- |
| Slower |  0.45 | Windows 11           | X64   |
| Slower |  0.48 | Windows 11           | X64   |
| Slower |  0.46 | Windows 10           | X64   |
| Slower |  0.48 | Windows 11           | X64   |
| Slower |  0.45 | Windows 10           | X64   |
| Slower |  0.46 | Windows 11           | X64   |
| Slower |  0.43 | Windows 11           | X64   |
| Slower |  0.44 | Windows 11           | X64   |
| Slower |  0.51 | Windows 11           | X64   |
| Slower |  0.51 | ubuntu 20.04         | X64   |
| Slower |  0.48 | ubuntu 18.04         | X64   |
| Slower |  0.53 | centos 7             | X64   |
| Slower |  0.51 | ubuntu 18.04         | X64   |
| Slower |  0.48 | alpine 3.13          | X64   |
| Slower |  0.47 | ubuntu 18.04         | X64   |
| Slower |  0.46 | ubuntu 20.04         | X64   |
| Slower |  0.57 | Windows 10           | Arm64 |
| Slower |  0.45 | Windows 10           | X86   |
| Slower |  0.59 | Windows 10           | Arm   |
| Slower |  0.52 | macOS Big Sur 11.6.3 | X64   |
| Slower |  0.52 | macOS Big Sur 11.4   | X64   |

(cc @stephentoub )

**Comment by EgorBo** [comment]
`Perf_Regex_Industry_RustLang_Sherlock` should be slightly better in .NET 7.0 Preview 2 with https://github.com/dotnet/runtime/pull/64872

But overall the benchmark hits the weakest spot in the new `IndexOf(substring)` algorithm - large text (0.5Mb) with low density of chars (upercased) 'S', 'H', 'I'. If we try to mitigate it we might lose significant wins for other cases, e.g.: https://github.com/dotnet/runtime/issues/64381#issuecomment-1030905550

**Comment by stephentoub** [comment]
> But overall the benchmark hits the weakest spot in the new IndexOf(substring) algorithm - large text (0.5Mb) with low density of chars (upercased) 'S', 'H', 'I'.

While I might enjoy passing the blame to you for this one @egorbo 😜 I don't think this is at all your fault.

First, for anyone reading, I'll call out that while this one specific test regressed, overall things have improved dramatically (and that's beyond all the [previous improvements](https://devblogs.microsoft.com/dotnet/regex-performance-improvements-in-net-5/) in .NET 5).  Looking at @adamsitnik's cited report above, searching for Slower yields 474 results, Same yields 1,555 results, and Faster yields 2,318 results, so many more have improved than regressed.  And some of those improvements are staggering, e.g.
432x faster:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/2642209/153610015-78bf38ad-1dad-475f-8d12-be2f3e853087.png">
150x faster:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/2642209/153610141-8f85de07-2305-470b-9e93-679b15e0eff2.png">
48x faster:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/2642209/153610388-320d7c15-f0ee-4830-8c84-f26698473b8c.png">
Etc.

Regex is one of those areas where it's difficult to look at just one result and make claims about improvements or regressions, as many optimizations play a guessing game as to what scenarios are most common and optimize for those at the expense potentially of others (as is the case with many optimizations, something common improves significantly in exchange for something expected to be less common regressing a bit).  In this particular case, the pattern "Sherlock|Holmes|Watson|Irene|Adler|John|Baker" suffers from a change that is typically beneficial but in this particular case is a step backwards.  To handle finding a match, we want to skip ahead as quickly as possible to the next potential place that could possibly match.  Previously, we would do that by looking at the first character of each branch (so 'S', 'H', 'W', 'I', 'A', 'J', and 'B').  This set is too large to be vectorized by IndexOfAny as it stands today, so we instead build a bitmap lookup and walk each character in the input looking for the first character that has a bit set.  However, .NET 7 now recognizes that, although there are 7 branches, other positions have overlap, e.g. it sees that if it were to instead focus on the second letter in each branch rather than the first, that would yield a set 'h', 'o', 'a', 'r', 'd', which is only 5 characters, and IndexOfAny does vectorize when there are 5 inputs.  So in .NET 7, rather than going character by character in the input, it instead does an IndexOfAny("adhor").  This is typically a good choice, because it's able to process 8 or 16 characters at a time rather than 1 at a time.  But in this particular case, there are lots of those letters in the input, and so the vectorized loop ends up stopping more frequently to further examine whether it's a good place to try to do a full match, and that ends up costing us. Hence the regression.  I knew this at the time I made the change, which improved other things as much and frequently more than this particular case.  There's very likely tweaking that could be done in the heuristics to improve this, but it'd still be a guessing game around all the tradeoffs involved.

It'd be great if IndexOfAny could be improved further, as Regex now makes very heavy use of it.  It'd also be really cool if someone could explore a .NET implementation of [Teddy](https://lib.rs/crates/teddy) (https://github.com/dotnet/runtime/issues/62447).

**Comment by joperezr** [comment]
Thanks for the analysis and for the explanation for the specific case that was called out @stephentoub. Also, thanks @adamsitnik for running these tests and for the report.

Looks like at least for the 2 specific tests called out above, we probably would want to not fix those, since as @stephentoub points out, these were less common cases that got a bit regressed in order to provide a much larger win for more common cases.

@stephentoub  is it feasible to plan to take a quick look to the biggest regressions of those 474 called out and ensuring that they are all cases of “optimizing for a more common case” as opposed to accidental regressions? Or are we confident enough that this is the case and that fir most accidental regression we already have a bug for logged? I mostly ask in order to know what to do with this issue.
