### ISSUE TITLE
Who is locking the File?

### ISSUE THREAD

**Issue by hamzashoukat94** [dotnet/runtime#65386]
In Dotnet, there is no way to find out who is locking the file. On IOException, we cannot find out who has access to the file. Kindly, put light if there is any way to find out.

**Comment by adamsitnik** [comment]
Hi @hamzashoukat94 

When .NET tries to open the file and it fails because the file is locked, the OS is not providing any information about who has locked the file. Hence .NET does not provide this information.

On Windows you can use Resource Monitor to find out who owns the lock: https://superuser.com/a/643312

**Comment by adamsitnik** [comment]
Since we don't intend to change this in the near future, I am going to close the issue. Thanks!
