### ISSUE TITLE
Can a File Stream open a File Larger than 5 Terabytes?

### ISSUE THREAD

**Issue by dotnetcadet** [dotnet/runtime#65602]
I tried putting this question on Stackover Flow and it got shot down for whatever reason, and I can't really test this cause I don't have a big enough hard drive to create a file this size 😆.

Basically, I want to be able to manipulate large files by moving around the stream, but I'm worried of building a program with FileStream and MemoryMappedFiles because I'm not sure they will be able to support it as the file grows.

Is it okay to use FileStream with files as large as 5 Terabytes? (Obviously, I will not be trying to load this in memory lol)

**Comment by HighPerfDotNet** [comment]
Yes

**Comment by huoyaoyuan** [comment]
The answer should be yes, as long as the OS supports it.

> I want to be able to manipulate large files by moving around the stream

You can also try the new random access api, in `System.IO.RandomAccess`.

**Comment by adamsitnik** [comment]
Hi @dotnetcadet 

From the implementation perspective I don't see any reasons why it should not work. `FileStream` can preload data to memory when buffering is enabled (the default), but the default buffer size is `4096` bytes so you are definitely not going to get OOM because of that.

And as @huoyaoyuan has suggested, using `System.IO.RandomAccess` would be most probably the best approach (nothing gets preloaded to memory, you just provide file offsets in explicit way and perform any read/write you want).

If you run into any issues please reopen the issue and provide more details. Thanks!
