### ISSUE TITLE
JIT: Faster Math.Max/Min for x64

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#65625]
Optimize `Math.Max/Min` to a single instruction on x64 when one of the arguments is a constant (not NaN and whoever will be implementing it has to be careful around -/+0.0)
```csharp
float Test(float a) => Math.Max(a, 10);
```
Currently emits:
```asm
; Method Tests4:Test(float):float:this
G_M55200_IG01:
       vzeroupper 
G_M55200_IG02:
       vmovss   xmm0, dword ptr [reloc @RWD00]
       vucomiss xmm1, xmm0
       jp       SHORT G_M55200_IG03
       je       SHORT G_M55200_IG06
G_M55200_IG03:
       vucomiss xmm1, xmm1
       jp       SHORT G_M55200_IG05
       vucomiss xmm1, xmm0
       ja       SHORT G_M55200_IG04
       jmp      SHORT G_M55200_IG08
G_M55200_IG04:
       vmovaps  xmm0, xmm1
       jmp      SHORT G_M55200_IG08
G_M55200_IG05:
       vmovaps  xmm0, xmm1
       jmp      SHORT G_M55200_IG08
G_M55200_IG06:
       vmovaps  xmm1, xmm0
       vmovd    eax, xmm1
       test     eax, eax
       jl       SHORT G_M55200_IG07
       jmp      SHORT G_M55200_IG08
G_M55200_IG07:
       vmovss   xmm0, dword ptr [reloc @RWD00]
G_M55200_IG08:
       ret      
RWD00  	dd	41200000h		;        10
; Total bytes of code: 68
```
**Expected codegen:**
```asm
; Method Tests4:Test(float):float:this
       vzeroupper 
       vmaxss   xmm0, xmm1, dword ptr [reloc @RWD00]
       ret      
RWD00  	dd	41200000h ; 10.0
; Total bytes of code: 12
```
https://github.com/dotnet/runtime/pull/65584 did it for ARM where we could do it even for both non-constants

**Comment by tannergooding** [comment]
In particular, `Math.Max` and `Math.Min` for floating-point have a requirement, from the IEEE 754 spec, that `-0.0` be the minimum of it and `+0.0`. Likewise, they have a requirement that `NaN` is propagated (if both inputs are NaN, then the exact NaN returned doesn't matter).

x86/x64 provide `maxss` and `minss`. These instructions will return the second operand if both operands are `0` (same or differing signs). Likewise, if either input is `NaN`, the second operand is returned. Otherwise, the correct max/min is returned.

What this functionally means is that if both inputs are unknown, we can't really "optimize" and instead have to use `maxss`/`minss` and then some follow up computations. However, if either input is constant then we actually can optimize it down to a single instruction in most cases:
* In the case both are constant, we simply constant fold and it doesn't matter.
* If either input is known to be `NaN`, it is used as the second argument.
* For `maxss`, if either input is `+0.0` it takes the second argument
* For `minss`, if either input is `-0.0` it takes the second argument
* Otherwise, for any other input it is the first argument

**Comment by SkiFoD** [comment]
Hey, everyone. I would like to take a look at the issue. @EgorBo Could you please tell me how you made "Math.Max" call to get inlined?

**Comment by EgorBo** [comment]
> Hey, everyone. I would like to take a look at the issue. @EgorBo Could you please tell me how you made "Math.Max" call to get inlined?

Hey, sure! What do you mean inlined? Intrinsic?

**Comment by SkiFoD** [comment]
I'm trying to get the same emit, but I always get something like this:
![image](https://user-images.githubusercontent.com/18483133/154937727-5e53e5cf-25e4-4c85-8922-4ab8951e07d4.png)
So I can't look inside the Math.Max call to invistigate it.

**Comment by EgorBo** [comment]
@SkiFoD see https://github.com/dotnet/runtime/pull/65584, it ifdefed special import for Max for x86/64, you need to enable it, most likely you will also have to modify lsraxarch and the xarch emitter

**Comment by SkiFoD** [comment]
@EgorBo Thank you, so basically you are changing the call to instrinsic use.

**Comment by SkiFoD** [comment]
@EgorBo Seems like I figured out how to make the changes, but I got a few questions.
Is it all right that the call transforms to the intrinsic use only under a pressure (like if the Math.Max/Min is called in a huge cycle) or if there are envs "COMPlus_TieredCompilation=0" and "COMPlus_JITMinOpts=0" set up?
p.s. For some reason if I used the envs along with "COMPlus_JitDump/JitDisasm" then there are not output in the console :( Have you ever come across with such a behaviour?

**Comment by EgorBo** [comment]
> @EgorBo Seems like I figured out how to make the changes, but I got a few questions. Is it all right that the call transforms to the intrinsic use only under a pressure (like if the Math.Max/Min is called in a huge cycle) or if there are envs "COMPlus_TieredCompilation=0" and "COMPlus_JITMinOpts=0" set up? p.s. For some reason if I used the envs along with "COMPlus_JitDump/JitDisasm" then there are not output in the console :( Have you ever come across with such a behaviour?

Yes, we don't expand intrinsics in tier0 (unoptimized code) - only a few "must expand" ones. So I'd suggest to disable tiered compilation during development

**Comment by SkiFoD** [comment]
@EgorBo please take a look at my PR, I would like to know what you think of this.

**Comment by danmoseley** [comment]
linking https://github.com/dotnet/runtime/pull/65700
