### ISSUE TITLE
Regression of Microsoft.Extensions.DependencyInjection with Unity and WebGL

### ISSUE THREAD

**Issue by bdovaz** [dotnet/runtime#65620]
### Description

I mention @joshpeterson @xoofx 

Since version 6.x the Microsoft.Extensions.DependencyInjection package has stopped working with Unity in WebGL.

The reason has been because now classes like ServiceProvider use an EventSource to make logs and this crashes in WebGL when using internally the Monitor class and threads (not supported by Unity + WebGL).

We have been using Microsoft.Extensions.* packages since version 2.x on Windows, macOS, Linux, WebGL, Android, iOS and UWP with Unity without any problem so far.

It's a pity that it stops working just because it starts logging.

Change in 6.x:

https://github.com/dotnet/runtime/blob/v6.0.2/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs#L78

Code until 6.x:

https://github.com/dotnet/runtime/blob/v5.0.14/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs#L50

### Reproduction Steps

Attached is the Unity project.

### Expected behavior

It should work as it has so far in all 2.x, 3.x and 5.x versions.

### Actual behavior

![image](https://user-images.githubusercontent.com/950602/154809075-682fe9e9-feec-430d-ab45-567dcd9f2b09.png)

### Regression?

It's considered a regression because until 6.x it worked without any issues.

### Known Workarounds

None.

**Comment by eerhardt** [comment]
@bdovaz - can you give more information about what isn't supported on Unity?

From looking at the `Actual behavior` call stack above, it appears that `Monitor.Enter` is throwing `Value cannot be null` from:

https://github.com/dotnet/runtime/blob/385fc8832b1d4160abe13645054b65458b6a12f8/src/libraries/Microsoft.Extensions.DependencyInjection/src/DependencyInjectionEventSource.cs#L141-L150

However, I'm not sure how `_providers` could ever be `null` since:

https://github.com/dotnet/runtime/blob/385fc8832b1d4160abe13645054b65458b6a12f8/src/libraries/Microsoft.Extensions.DependencyInjection/src/DependencyInjectionEventSource.cs#L27

Is there some `EventSource` specific alteration that happens in Unity?

cc @xoofx @joshpeterson

**Comment by bdovaz** [comment]
I can't answer what you ask due to the fact that it is in the Unity code base and I can't know or see it.

@xoofx or @joshpeterson will have the answer

**Comment by xoofx** [comment]
Don't think it is an issue in Microsoft.Extensions.DependencyInjection but maybe a IL linker issue in Unity. It will have to be submitted to Unity via repro bug so that our teams can have a look.

**Comment by bdovaz** [comment]
I am preparing a very basic project with a script that serves as a repro project. In a few minutes I will submit it to issue tracker.

**Comment by bdovaz** [comment]
@xoofx @joshpeterson Case 1408030

Tested on:

2021.2.13f1 (Latest as of today)
2022.1.0b10 (Latest as of today)

Same behaviour on both versions.

**Comment by eerhardt** [comment]
I'm going to close this issue for now. Feel free to re-open or create a new one if a change is necessary in DependencyInjection. I'm open to making a change for Unity, if needed. I just don't want to degrade the other experiences.
