### ISSUE TITLE
GZipCompressor implemented in netstandard2.0 package not working in .NETFramework4.8

### ISSUE THREAD

**Issue by denisulmer** [dotnet/runtime#65665]
### Description

I have implemented an internal SDK package that also uses a GZipCompressor. The SDK project is created using netstandard2.0 and works fine when used in a .NET 6.0 CLI application. 

A colleague uses the same SDK / NuGet in a .NETFramework4.8 WPF application, and the package / code runs without any exceptions, warnings etc. but after some investigation of a business problem in the WPF app, we discovered that the GZipCompressor in the SDK returns only 10 bytes when used in the WPF / .NETFramework app, vs the correct amount of bytes (around 2000) in the CLI that is build on net6.0

### Reproduction Steps

1. Implement following code using `System.IO.Compression` namespace in a netstandard2.0 project.

```
using (MemoryStream compressorOutputStream = new MemoryStream())
using (GZipStream compressor = new GZipStream(compressorOutputStream, CompressionLevel.Optimal))
{
    await compressor.WriteAsync(uncompressedData, 0, uncompressedData.Length, cancellationToken);
    await compressor.FlushAsync(cancellationToken);

    return compressorOutputStream.ToArray();
}
```

2. Generate package from the code above
3. Use package in .NET6.0 application, also use package in .NETFramework4.8 application
4. compare the output (compressed bytes)

### Expected behavior

The code should output the same data in both cases

### Actual behavior

The coded outputs different data (in my case 1800 bytes vs 10 bytes)

### Known Workarounds

I now implemented the Gzip compression using `SharpZipLib` instead of ` System.IO.Compression` , which now gives the expected outout in both consuming applications.

**Comment by stephentoub** [comment]
You're accessing the contents of the MemoryStream before the GZipStream has been disposed. What hapoens if you get the bytes after disposing the compressor stream?

**Comment by denisulmer** [comment]
I think that really fixes the issue. But why is this needed? Shouldn't the call to `FlushAsync` empty the buffer already and push all data to the output stream? It is not really clear that the dispose needs to happen before even after calling `FlushAsync`.

**Comment by stephentoub** [comment]
>  Shouldn't the call to FlushAsync empty the buffer already and push all data to the output stream?

FlushAsync on .NET Framework is a nop, literally:
https://referencesource.microsoft.com/#System/sys/System/IO/compression/DeflateStream.cs,293

FlushAsync on .NET Core actually does something meaningful, flushing out the data in a usable fashion to the underlying stream.

So the behavior you're reporting is actually backwards from what I'd expect.

I also can't repro it.

Can you please share a standalone project that demonstrates the issue so that we can try to repro what you're seeing?  Note that netstandard2.0 is just surface area purely for compilation; when it runs, it's running against the actual framework used by the app, so either .NET Framework or .NET 6.  So you should be able to just create a .NET 6 console app that uses your cited snippet to repro.
