### ISSUE TITLE
How to hot reload assemblies in mono runtime

### ISSUE THREAD

**Issue by ayoubbelatrous** [dotnet/runtime#65663]
`mono_set_dirs("assets/CsharpAssemblies/", "assets/CsharpAssemblies/");
		_MainDomain = mono_jit_init("Csharp");
		_Domain = mono_domain_create();
		_Assembly = mono_domain_assembly_open(_Domain, "assets/TestProject/Assem/Csharp.dll");
		_Image = mono_assembly_get_image(_Assembly);
	Reloading
		mono_domain_free(_Domain, true);
		mono_assembly_close(_Assembly);
      rebuild assemblies
      load assemblies
		_Domain = mono_domain_create();
		_Assembly = mono_domain_assembly_open(_Domain, "assets/TestProject/Assem/Csharp.dll");
`
program cashes when try to call functions again

**Comment by srxqds** [comment]
the .net6.0 is not supported multiple domains, you can try to use AssemblyLoadContext for code reload.

**Comment by lambdageek** [comment]
multiple app domains are not supported in mono in .NET 6 and later. 

Using ALCs may work, although ALC unloadability is not working in Mono yet.

For C# hot reload, you may be able to use the [MetadataUpdate.ApplyUpdate](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.metadataupdater.applyupdate?view=net-6.0) API, although the Roslyn APIs to create metadata deltas are not public APIs (but see [hotreload-utils](https://github.com/dotnet/hotreload-utils) for some unsupported ways to use them).  C# hot reload using Roslyn would be subject to [limitations on supported edits](https://github.com/dotnet/roslyn/blob/main/docs/wiki/EnC-Supported-Edits.md). In .NET 6 Mono only supports edits to method bodies - changes that add new classes or that add fields to existing classes are not supported (some of these restrictions are fixed in .NET 7 Mono)
