### ISSUE TITLE
Test failure System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65820]
Run: [runtime-libraries-coreclr outerloop 20220223.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1627854&view=ms.vss-test-web.build-test-results-tab&runId=45181458&resultId=100943&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open

- System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows

```
**Error message:**
```
System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\9A4E0857\p\dotnet.exe' with working directory 'C:\h\w\9A4E0857\w\9648088D\e'. El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.


Stack trace
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs:line 632
   at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 493
```

**Comment by danmoseley** [comment]
```kusto
TestResults
//| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-30d)
| where Result == "Fail"
| where WorkItemFriendlyName startswith "System.Diagnostics"
| where Method != "WorkItemExecution"
| where  Method == "TestUserCredentialsPropertiesOnWindows"
| where Source !startswith "pr/"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  //Test = Type1,
  //Result,
  Finished,
  //Duration,
  //Method,
  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline|Pipeline_Configuration|OS|Arch|Finished|Build|Message|
|---|---|---|---|---|---|---|
|runtime-libraries-coreclr outerloop-windows|Release|windows.10.amd64.serverrs5.open.rt|x64|2022-02-05 12:50:59.6860000|20220205.5|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\A1A208F7\p\dotnet.exe' with working directory 'C:\h\w\A1A208F7\w\C0CC0A20\e'. The process cannot access the file because it is being used by another process.|
|runtime-libraries-coreclr outerloop-windows|Release|windows.7.amd64.open.svc|x86|2022-02-11 13:03:09.3230000|20220211.2|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\A5260921\p\dotnet.exe' with working directory 'C:\h\w\A5260921\w\AD0408E1\e'. Access is denied.|
|runtime-libraries-coreclr outerloop-windows|Release|windows.amd64.server2022.open|x86|2022-02-12 12:39:46.7510000|20220212.6|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\9BAB0897\p\dotnet.exe' with working directory 'C:\h\w\9BAB0897\w\A7C90959\e'. The process cannot access the file because it is being used by another process.|
|runtime-libraries-coreclr outerloop-windows|Release|windows.10.amd64.server19h1.es.open.rt|x64|2022-02-16 13:01:42.0720000|20220216.2|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\BB0C0A15\p\dotnet.exe' with working directory 'C:\h\w\BB0C0A15\w\9FBF091E\e'. Acceso denegado.|
|runtime-libraries-coreclr outerloop|Release|windows.10.amd64.server19h1.es.open.rt|x64|2022-02-18 12:53:45.3350000|20220218.1|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\ACE8094E\p\dotnet.exe' with working directory 'C:\h\w\ACE8094E\w\9D2808FD\e'. Acceso denegado.|
|runtime-libraries-coreclr outerloop-windows|Release|windows.10.amd64.serverrs5.open.svc|x64|2022-02-18 12:57:51.5410000|20220218.6|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\C3A80A34\p\dotnet.exe' with working directory 'C:\h\w\C3A80A34\w\AAC40948\e'. Access is denied.|
|runtime-libraries-coreclr outerloop-windows|Release|windows.7.amd64.open.svc|x86|2022-02-23 13:06:53.8130000|20220223.2|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\AC790959\p\dotnet.exe' with working directory 'C:\h\w\AC790959\w\AB700955\e'. The system cannot find the file specified.|
|runtime-libraries-coreclr outerloop|Release|windows.10.amd64.server19h1.es.open.rt|x64|2022-02-23 13:10:55.2830000|20220223.7|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\9A4E0857\p\dotnet.exe' with working directory 'C:\h\w\9A4E0857\w\9648088D\e'. El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.|
|runtime-libraries-coreclr outerloop|Release|windows.amd64.server2022.open.svc|x86|2022-02-25 12:45:05.0620000|20220225.4|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\B5BF092D\p\dotnet.exe' with working directory 'C:\h\w\B5BF092D\w\B29D09A3\e'. The process cannot access the file because it is being used by another process.|
|runtime-libraries-coreclr outerloop-windows|Release|windows.7.amd64.open.svc|x86|2022-02-28 13:05:10.9170000|20220228.5|System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\h\w\ACFD0977\p\dotnet.exe' with working directory 'C:\h\w\ACFD0977\w\BE1C0A5E\e'. Access is denied.|

**Comment by danmoseley** [comment]
This is the only one of the ProcessStartInfo tests that has been failing recently -- so it's not a general fragility in how we launch child processes.

If the user had somehow not been created, we would have gotten Win32Exception: 'An error occurred trying to start process '...'. The user name or password is incorrect.'

Note that https://github.com/dotnet/runtime/pull/46083 added the SetAccessControl to avoid a similar error. But I'm not sure how that would be necessary here, and anyway I'd expect it to throw if that failed.

I looped essentially the test code locally without result.

**Comment by danmoseley** [comment]
Next step would be to loop the actual test.
