### ISSUE TITLE
[API Proposal]: Make the property `DataContractSerializer.SerializationSurrogateProvider` public

### ISSUE THREAD

**Issue by Takym** [dotnet/runtime#65826]
### Background and motivation

We have the internal property of type [`ISerializationSurrogateProvider`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iserializationsurrogateprovider).
https://github.com/dotnet/runtime/blob/625a9cdd4437a414f1fda220f5bacba101f209c8/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializer.cs#L195-L199

Also, we have extension methods just to get or set the above property value.
https://github.com/dotnet/runtime/blob/625a9cdd4437a414f1fda220f5bacba101f209c8/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerExtensions.cs#L8-L16

I think this costs to read/write a serialization surrogate provider.

### API Proposal

Before:
```cs
namespace System.Runtime.Serialization
{
    public sealed class DataContractSerializer : XmlObjectSerializer
    {
        // ......

        internal ISerializationSurrogateProvider? SerializationSurrogateProvider
        {
            get { return _serializationSurrogateProvider; } 
            set { _serializationSurrogateProvider = value; }
        }

        // ......
    }
}
```
After:
```cs
namespace System.Runtime.Serialization
{
    public sealed class DataContractSerializer : XmlObjectSerializer
    {
        // ......

        public ISerializationSurrogateProvider? SerializationSurrogateProvider { get; set; }
        // Internally, I think we could also use the auto-implemented property syntax.

        // ......
    }
}
```

### API Usage

Before:
```cs
// ......
DataContractSerializer dcs = /* ...... */;
ISerializationSurrogateProvider ssp = /* ...... */;

dcs.SetSerializationSurrogateProvider(ssp);
// ......
```

After:
```cs
// ......
DataContractSerializer dcs = /* ...... */;
ISerializationSurrogateProvider ssp = /* ...... */;

dcs.SerializationSurrogateProvider = ssp;
// ......
```

### Alternative Designs

Edit (2022/4/6): I alternatively propose to rename the property `SerializationSurrogateProvider` as `SurrogateProvider` for more shorter, since its accessibility is internal.

### Updates
* **2022/04/06**: I added an alternative design.
* **2022/06/03**: I updated the quoted codes to the latest version.

**Comment by StephenMolloy** [comment]
If we were porting DCS to Core again from scratch, I think we probably would have done the surrogate thing differently. But as it is, when DCS was first brought to .Net Core, it used a different interface for a half-implementation of the old IDataContractSurrogate. To bridge the gap between NetFx and Core funny tricks were pulled with type forwarding and extension methods and whatnot. So here we are today, using Get/Set methods instead of a property.

At this point, the Get/Set methods are the API for DCS. It's what folks have been coding against. A from-scratch API would probably have looked different, but that's not really enough reason to change the API. Neither does it make sense to offer a secondary API that does exactly the same thing as the first.
