### ISSUE TITLE
Writing unit tests for cultures that does not use hypen '-' as minus sign is a pain in .NET 6.0

### ISSUE THREAD

**Issue by appel1** [dotnet/runtime#65833]
We have unit tests that tests that we get the expected strings for different cultures that we now also want to run with .NET 6.0. All of them fail for .NET 6.0 since now we get a different minus sign character. Even worse is when you want to write new unit tests there's no key on the keyboard for typing this minus sign character. 

Another issue is that copy pasting text with this new minus sign doesn't work if you want to paste it into for example Calculator or Excel even if you set Windows to a matching region format. Or copy from Calculator or Excel. 

Simplified silly example:
```csharp
[Test]
public void SampleTest()
{
  var culture = CultureInfo.GetCultureInfo("sv-SE");
  string actual = (-44.4).ToString(culture);
  Assert.AreEqual("-44,4", actual);
}
```

```
  Message: 
  String lengths are both 5. Strings differ at index 0.
  Expected: "-44,4"
  But was:  "−44,4"
  -----------^
```

Using a culture specific comparer doesn't work as a workaround either. 
```csharp
Assert.That(actual, Is.EqualTo("-44,4").Using((IEqualityComparer<string>)StringComparer.Create(culture, false)));
```

**Comment by Joe4evr** [comment]
The runtime gets its globalization data from [the ICU database](http://site.icu-project.org/home) ([see MS Docs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api)), so any issue in this area is external.

Going through the history of CLDR's `sv.xml`, the `minusSign` seems to have always been the non-hyphen [since it was added from survey data back in 2006](https://github.com/unicode-org/cldr/blob/63508056f107d56838698dcb83bee59620d8fe00/common/main/sv.xml#L1555).

I think ideally you should just have your unit tests run against `InvariantCulture` and assume that the globalization infrastructure will do The Right Thing™️ when invoked, because culture data can change on a dime and you'll be rewriting your tests every time that occurs.

**Comment by tarekgh** [comment]
@Joe4evr is correct. You cannot assume all cultures will use the hyphen for the negative sign. The .NET picks the data from CLDR Unicode standard as pointed before. Using Invariant would be the way, or you should modify the tests to be resilient for non-hyphen negative signs. The other idea is manually overwrite the [NumberFormatInfo.Negativesign](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.negativesign?view=net-6.0).
