### ISSUE TITLE
Review workaround for IsolatedStorageFile dependency on System.Security.Policy.Evidence

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#65930]
[Cleanup Issue-URLs in Code · Issue #63902 · dotnet/runtime](https://github.com/dotnet/runtime/issues/63902) identified a workaround in place and it's unclear if the backing issue that necessitated the workaround has been resolved.

- The original issue was: [Add IsolatedStorageFile factory methods with Evidence dependencies · Issue #18208 · dotnet/runtime](https://github.com/dotnet/runtime/issues/18208)
- The PR that added the comment was: [Use [MemberNotNull] to reduce use of `= null!;` by stephentoub · Pull Request #37490 · dotnet/runtime](https://github.com/dotnet/runtime/pull/37490/files#diff-3f7f42b3d70cf427ed43a44879658e0f7951ee1520c748b949cc986c78d70753R41)

https://github.com/stephentoub/runtime/blob/3ae87395f638a533f37b8e3385f6d3f199a72f4f/src/libraries/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/IsolatedStorageFile.cs#L38-L41

The workaround should be evaluated to determine if it's still necessary. With the findings, we should either update the code to remove the workaround, or the code comment to reference an open issue for tracking when we can remove the workaround.

/cc @deeprobin

**Comment by Jozkee** [comment]
The comment is not a workaround, it is telling that certain API wasn't ported because `Evidence` is not available in current .NET.
 
We have decided twice in the past that this isn't a common secenario:
https://github.com/dotnet/runtime/issues/28654
https://github.com/dotnet/runtime/issues/18208

I think keeping the link is fine as it gives good context.
