### ISSUE TITLE
System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream_SynchronizingObject test failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65955]
Configuration: `net7.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open`
Build: [runtime pipeline of the rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1635569&view=ms.vss-test-web.build-test-results-tab&runId=45291136&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=147215), [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f713537715f04c66ac/System.Diagnostics.Process.Tests/1/console.34f7ff4c.log?sv=2019-07-07&se=2022-03-20T08%3A53%3A47Z&sr=c&sp=rl&sig=%2FCxSnOmgSEXdBGlx6bMmwpMV0AFOlnBRyg8Qd6IQSU8%3D)

```
    System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream_SynchronizingObject(invokeRequired: False) [FAIL]
      Assert.Equal() Failure
                                       ↓ (pos 105)
      Expected: ··· closed error stream
      Actual:   ··· closed error streamAssert failure(PID 18855 [0x000049a7], Th···
                                       ↑ (pos 105)
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs(85,0): at System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream_SynchronizingObject(Boolean invokeRequired)
...
  Finished:    System.Diagnostics.Process.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 317, Errors: 0, Failed: 1, Skipped: 2, Time: 42.933s
```

**Comment by adamsitnik** [comment]
It looks like some internal runtime assertion has failed (due to bug in the runtime itself) and it got printed to std error. This was was not expected by this test which is asserting the content of std error, so it has failed.

Since the error message does not contain full failure details (`xUnit` shows only part of it) I am going to close the issue as it's not actionable.

If someone has better idea, please let me know.

**Comment by danmoseley** [comment]
This has been a problem in the past. I dont know whether XUnit would accept a change to [increase the length](https://github.com/xunit/assert.xunit/blob/b4f2de311f3b050d3cce6d6024dcdccfcfa2bbf8/Sdk/Exceptions/EqualException.cs#L182), and we use 2.x anyway.

I suppose we could create an AssertExtensions.Equal(string, string) that logs more, and use that everywhere. Probably implemented as a wrapper of Assert.Equal since there's a bunch of code in that, then catching XunitException and logging 'actual'.

Or if it's just this test, of course we could simply modify this test to do that.

**Comment by danmoseley** [comment]
I see that XUnitException contains the full actual string, if you can downcast it to the non-public AssertActualExpectedException.
