### ISSUE TITLE
Assertion failed 'm_fgBBcount == m_compiler->fgBBcount' during 'Profile instrumentation'

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#65992]
```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public static void Main(string[] args)
    {
    }
}
/*
--------- Test ---------  

Environment:

set COMPlus_TC_PartialCompilation=1
set COMPlus_TieredCompilation=1
set COMPlus_TieredPGO=1
set COMPlus_JitStress=2
set COMPlus_EnableSSE2=0

Assert failure(PID 133364 [0x000208f4], Thread: 148276 [0x24334]): Assertion failed 'm_fgBBcount == m_compiler->fgBBcount' in 'System.Collections.Generic.ComparerHelpers:CreateDefaultEqualityComparer(System.Type):System.Object' during 'Profile instrumentation' (IL size 229)
    File: D:\git\dotnet-runtime\src\coreclr\jit\phase.cpp Line: 43
    Image: D:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Things are a bit messier here than I'd thought.

We currently require that the Tier0 BBINSTR anticipate all possible probes that might be needed by any later compile and build a master schema that is a superset of any subsequent schema. For partial compilation this isn't working right, as we only probe blocks that are actually imported, and partial compilation only imports a subset. So the schema it produces is too limited and omits some blocks:

```
Block probe 1 in BB01
Block probe 2 in BB02
Block probe 3 in BB03
Block probe 4 in BB04
Block probe 5 in BB05
Block probe 6 in BB06
Block probe 7 in BB07
Block probe 8 in BB08
....
Block probe 9 in BB15
Block probe 10 in BB16
Block probe 11 in BB17
Instrumenting method: 11 count probes and 0 class probes
```
Later when the PC patchpoint is hit and we go to recompile with OSR and BBINSTR, we end up importing the entire method that and produce a schema with 17 block probes. The PGO manager sees that this is incompatible with the Tier0 schema and so fails the schema allocation.

In this particular case the OSR compile needed to relocate some probes to handle tail calls (since BBJ_RETURN blocks we hope to probe won't be reached). That added flow. But then the schema allocation fails and we don't instrument. When this happens, we report that instrumentation didn't make any changes, which isn't true. Also, we need to scrub the cheap preds that we built.

So as noted above we should be producing a compatible schema, and we should be recovering properly in the case where schema allocation fails.

The compatible schema change likely means we need to split `ShouldHandle` into two parts (or pass in an arg):
* should we handle this block for schema purposes
* should we actually instrument this block

-----

Beyond all that we are also adding class probes during OSR + BBINSTR that aren't there during Tier0. These will also lead to incompatible schemas and fixing this is perhaps more pressing as we probably are hitting this case even without partial compilation.

One idea is to elevate schema failure to an assert in checked builds. Seems dangerous to just silently drop PGO. That may reveal a host of issues but is probably worth considering).

We need to be careful about class instrumentation for casts; it is dependent on the exact importation sequence and that varies between Tier0 and when optimizing, and so we can go astray. I don't have a good answer for this yet.

cc @EgorBo
