### ISSUE TITLE
COMHost/ComActivator without separate AssemblyLoadContext

### ISSUE THREAD

**Issue by batzen** [dotnet/runtime#66013]
I don't know if this has come up before, if that's the case i am sorry, but searching didn't yield any results.

We are currently trying to migrate from .NET 4.8 to .NET 6.0 and have hit a major road block with our usage of COM interop.

Architecture:
- C++ with lots of classes exposed via COM (this hosts our own ORM and large parts of our business logic)
- .NET (C# and WPF) GUI layer, business logic, configuration etc.

Problem case:
- Application is in .NET
- Calls into C++ via COM interop
- C++ calls into C# via COM interop
- The C# code references an interop assembly generated from a C++ tlb

Issue:
In .NET 4.8 everything works fine.
In .NET 6.0 we get type clashes (InvalidCastException for class originating from the generated interop assembly) as the .NET COMHost/ComActivator creates a separate AssemblyLoadContext, which in turn again loads the C++ interop assemblies.

I wasn't able to create a sample application, but the documentation for AssemblyLoadContext states that exactly these kinds of issues might happen if the same assemblies are loaded in different contexts.

What i would like to propose:
- Extend hostfxr to be able to create delegates for an existing context and/or allow it to return the context handle for the currently active context
- Extend comhost to allow users to specify if they want their components to be loaded in an isolated context or not (this might be transportable through the clsidmap or something new
- Extend ComActivator to allow the same as comhost would

The most important part however would be to allow ComActivator to work without AssemblyLoadContext, if a certain component requires/requests so. This would be enough to fix the issue we are experiencing.

I am not sure how to proceed from here, so i will just wait for someone to comment on this issue. ;-)

Tagging @AaronRobinsonMSFT as you seem to have added the ALC code back in 2019.

**Comment by jkoritzinsky** [comment]
cc: @vitek-karas as this is related to custom ALCs and hosting.

**Comment by AaronRobinsonMSFT** [comment]
This is the identical issue that our C++/CLI users are attempting to mitigate in https://github.com/dotnet/runtime/issues/62754.

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung and @vitek-karas What are our thoughts on this problem and do either of you recall where we landed on a solution relative to the C++/CLI decision to push into the default ALC - https://github.com/dotnet/runtime/pull/66486.

**Comment by elinor-fung** [comment]
I believe we were on:
- COM components remain loaded in an isolated context by default
- New runtime config property to indicate that a COM component should be loaded in the default ALC (with some descriptive name  `System.Runtime.InteropServices.LoadComComponentIntoDefaultContext`, `System.Runtime.InteropServices.LoadThisComComponentIntoDefaultContext`, ...)
- `comhost` checks for the property in the COM component's runtime config and can load that COM component in the default ALC

**Comment by elinor-fung** [comment]
Moving this to 8.0. We've been getting indication that this is problematic/painful for an increasing number of people as they try to move off of .NET Framework.

**Comment by AaronRobinsonMSFT** [comment]
@govert I think this feature might be something of interest to you. It is already in .NET 8, but we are looking to gather interest in .NET 7. Any thoughts?

**Comment by elinor-fung** [comment]
If you want to try it out in .NET 8, you'll need to rebuild your COM component targeting `net8.0`:
```csproj
<TargetFramework>net8.0</TargetFramework>
```
And add a [`RuntimeHostConfigurationOption`](https://learn.microsoft.com/dotnet/core/runtime-config/#msbuild-properties) to load in the default ALC:
```csproj
<RuntimeHostConfigurationOption Include="System.Runtime.InteropServices.COM.LoadComponentInDefaultContext" Value="true" />
```

**Comment by jmecosta** [comment]
@AaronRobinsonMSFT could you check my comment in DNNE https://github.com/AaronRobinsonMSFT/DNNE/issues/135, i was hoping .net 8 would fix the problem based on this. but same issue there. is it so that DNNE would then need to take this changes to support it? thanks in advance

**Comment by AaronRobinsonMSFT** [comment]
> is it so that DNNE would then need to take this changes to support it?

Yes, that is correct. We changed the behavior of C++/CLI in https://github.com/dotnet/runtime/pull/66486. @elinor-fung has been working on a longer term plan to enable finer grained access to loading assemblies into specific ALCs. When that is done, DNNE can take advantage of that mechanism.

**Comment by elinor-fung** [comment]
https://github.com/dotnet/runtime/pull/79026 enabled configuration for loading COM components in the default ALC in .NET 8 - [doc](https://learn.microsoft.com/dotnet/core/native-interop/expose-components-to-com#loading-in-the-default-assemblyloadcontext) and [sample](https://github.com/dotnet/samples/tree/main/core/extensions/COMServerDemo) are updated.

**Comment by jmecosta** [comment]
@elinor-fung im confused, i have this: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
	<OutputPath>$(BinDir)\TestApp</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Trimble.Tekla.TsepManager\Trimble.Tekla.TsepManager.csproj"  />
  </ItemGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Runtime.InteropServices.COM.LoadComponentInDefaultContext" Value="true" />
  </ItemGroup>
</Project>
```

with
6360:6c48 @ 1696204515 - LdrpCallTlsInitializers - INFO: Calling TLS callback 00007FFFFFA2DBF0 for DLL "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-preview.6.23329.7\clrjit.dll" at 00007FFFFF930000

See the callstack
<img width="1301" alt="image" src="https://github.com/dotnet/runtime/assets/1041352/351aa884-b5cd-4178-8197-ffe13c04ec15">

And the relevant loading of the dll in debug windows.
1st activation:
8dc0:44a0 @ 1696282187 - LdrLoadDll - ENTER: DLL name: D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll
8dc0:44a0 @ 1696282187 - LdrpLoadDllInternal - ENTER: DLL name: D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll
8dc0:44a0 @ 1696282187 - LdrpResolveDllName - ENTER: DLL name: D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll
8dc0:44a0 @ 1696282187 - LdrpResolveDllName - RETURN: Status: 0x00000000
8dc0:44a0 @ 1696282187 - LdrpMinimalMapModule - ENTER: DLL name: D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll
'WpfAppTestApp.exe' (Win32): Loaded 'D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll'. 
8dc0:44a0 @ 1696282187 - LdrpMinimalMapModule - RETURN: Status: 0x00000000
8dc0:44a0 @ 1696282187 - LdrGetDllHandleEx - ENTER: DLL name: ntdll.dll
8dc0:44a0 @ 1696282187 - LdrpFindLoadedDllInternal - RETURN: Status: 0x00000000
8dc0:44a0 @ 1696282187 - LdrGetDllHandleEx - RETURN: Status: 0x00000000
8dc0:44a0 @ 1696282187 - LdrpInitializeNode - INFO: Calling init routine 0000000000000000 for DLL "D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll"

Second activation:
8dc0:44a0 @ 1696287578 - LdrpGetProcedureAddress - INFO: Locating procedure "IsWow64Process2" by name
'WpfAppTestApp.exe' (CoreCLR: clrhost): Loaded 'D:\prod\TeklaStructuresPackagesServices\TSEP30\BuildDrop\TestApp\net8.0-windows\Trimble.Tekla.TsepManager.dll'. Symbols loaded.
8dc0:44a0 @ 1696290515 - LdrpGetProcedureAddress - INFO: Locating procedure "MultiByteToWideChar" by name

However the behaviour is still the same as before. the singleton class private static ITepManager? manager is null on second activation where im expecting after this change the manager to be non null since it was initialized by the managed side when the app started (Defaul behaviour in .net 4.8)

Can you clarify if the current preview 8.0.100-preview.6.23330.14 (8.0.0-preview.6.23329.7) supports this?

Thanks in advance

**Comment by elinor-fung** [comment]
The current preview should support this. It is the COM component itself (rather than the client app) that must specify it should be loaded in the default ALC. In your case, I believe that would be `Trimble.Tekla.TsepManager.csproj` - can you try that?

**Comment by jmecosta** [comment]
@elinor-fung thanks, in fact both have it
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputPath>$(BinDir)</OutputPath>
	  <TargetFrameworks>net6.0;net8.0;net48</TargetFrameworks>
	  <EnableDynamicLoading>true</EnableDynamicLoading>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <DnneAddGeneratedBinaryToProject>true</DnneAddGeneratedBinaryToProject>
	  <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DNNE" PrivateAssets="all" Version="2.0.1" />
	</ItemGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Runtime.InteropServices.COM.LoadComponentInDefaultContext" Value="true" />
  </ItemGroup>
</Project>
```

Just to clarify, this is not  a COM scenario. This would be a simple WPF application that simply loads native side via pinvoke 
thanks

**Comment by elinor-fung** [comment]
> Just to clarify, this is not a COM scenario. This would be a simple WPF application that simply loads native side via pinvoke
thanks

Ah, missed that. The configuration is specifically for COM activation.

.NET 8 also adds the ability for a native host to load an assembly in the default context: https://github.com/dotnet/runtime/issues/77696. However, I don't think that is exposed by DNNE yet - cc @AaronRobinsonMSFT

**Comment by jmecosta** [comment]
Alright thanks for clearing that up so we need done implementation to get
this running. Thanks for the clarification
