### ISSUE TITLE
DateOnly string interpolation causes OOM crash

### ISSUE THREAD

**Issue by tgrunshaw** [dotnet/runtime#66040]
### Description

Using string interpolation with DateOnly causes the runtime to crash with invalid string formats, such as below: 

```
var dateOnly = new DateOnly(2020, 05, 03);
var dateOnlyString = $"{dateOnly:yyyy:MM:dd}"; // We never proceed beyond this line
```
See an example: https://dotnetfiddle.net/jLN3uv

### Reproduction Steps

```
var dateOnly = new DateOnly(2020, 05, 03);
var dateOnlyString = $"{dateOnly:yyyy:MM:dd}"; // We never proceed beyond this line
```
See an example: https://dotnetfiddle.net/jLN3uv

### Expected behavior

Not have the runtime crash/stick/run out of memory. 

Whether this should throw an exception like it does when .ToString() is used or whether it should behave like DateTime where it works correctly is a decision I'll leave to the .NET team. 

### Actual behavior

Out of memory failure or stuck with high GC when debugging.

**Comment by jcouv** [comment]
The C# compiler emits:
```
        DateOnly dateOnly = new DateOnly(2020, 5, 3);
        string.Format("{0:yyyy:MM:dd}", dateOnly);
```
That seems correct (and the IL too). Here's the relevant section of the [spec](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#1173-interpolated-string-expressions).

Using `yyyy-MM-dd` or `yyyy\\:MM\\:dd` work as expected. So the problem has to do with the colons `:` (not escaped with `\`) in the format specification.
I think it's a BCL issue.

**Comment by KeterSCP** [comment]
It falls into infinite loop [here](https://github.com/dotnet/runtime/blob/96d7d903140d11f31143647d5e6f8678016cbc41/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/DefaultInterpolatedStringHandler.cs#L312) because `TryFormat` returns false from [this](https://github.com/dotnet/runtime/blob/312f23d67859ab47e041d40c621929a0ee31509e/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L1158) check. So it will also go into an infinite loop with following format characters: `t, f, F, h, H, m, s, z, K`

**Comment by stephentoub** [comment]
The format string used here is incorrect for a DateOnly. You can see that if you change the repro to use ToString:
```C#
var dateOnly = new DateOnly(2020, 05, 03);
Console.WriteLine(dateOnly.ToString("yyyy:MM:dd"));
```
as that will result in:
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.DateTimeFormat.IsValidCustomDateFormat(ReadOnlySpan`1 format, Boolean throwOnError)
   at System.DateOnly.ToString(String format, IFormatProvider provider)
   at Program.<Main>$(String[] args)
```
The problem is that DateOnly.TryFormat was erroneously returning false rather than throwing when passed an invalid format string.  This was fixed for .NET 7 in https://github.com/dotnet/runtime/pull/64398 and for the next servicing release of .NET 6.0.3 in https://github.com/dotnet/runtime/pull/64460.

**Comment by tgrunshaw** [comment]
Perfect, thanks for the explanation.
