### ISSUE TITLE
Update RegexGenerator to fail better on unsupported platforms

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#66047]
RegexGenerator requires API surface new to .NET 7, and if you try to use it on a previous platform, it'll generate code that will fail to compile.  We should update the generator to, at a minimum, look for the new RegexRunner.Scan(ReadOnlySpan) overload that it needs to override, and more gracefully fail if it's not found.  Simplest answer would be a diagnostic saying that the target platform isn't supported.  We could alternatively allow it to work, but fall back to generating the code path we use in other limited scenarios where we can't generate code, emitting a caching field that's just initialized to `new Regex(...)`.

**Comment by stephentoub** [comment]
@joperezr, we should get this in for Preview 3, since that also contains the Scan change.  Let me know if you'd like to handle this or if you'd like me to.  Or @teo-tsirpanis, since you're now one of the few other people that have played in this codebase, if you'd like to handle this, that'd be great, too. :smile:

**Comment by huoyaoyuan** [comment]
> We could alternatively allow it to work, but fall back to generating the code path we use in other limited scenarios where we can't generate code, emitting a caching field that's just initialized to `new Regex(...)`.

I like this approach, especially for libraries which need to support older platforms.

**Comment by joperezr** [comment]
I did some investigation here and I don't think this is an issue down-level. The Regex source generator ships as part of the net7.0 targeting pack, so if you try to use a previous platform (like net6.0 for example) then the regex source generator will not be used even when you manually define the `RegexGeneratorAttribute` as part of your application. This makes it so that we can guarantee that any dependency on new .NET 7.0 API that the generator takes on, will be present when the generator is used. The only way that somebody can use the source generator in a net6.0 project, is if a) they manually define the `RegexGeneratorAttribute` as part of their project and b) they manually edit their project to add an analyzer reference that is pointing into the net7.0 targeting pack to use the generator, which is definitely in unsupported territory.

This may be an issue in the future (e.g. .NET 8.0) if the generator in that future version starts requiring API that is not present in 7.0, but this is not something we should worry about now, and instead deal with it once this case happens. So due to all of this, I'll go ahead and close this issue for now. @teo-tsirpanis please let me know if you have any questions from this or if you think there are still scenarios where we should consider fixing this for 7.0.
