### ISSUE TITLE
[NativeAOT] Are RdXmlFile properties transitive?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#66085]
Let's say I have two console app projects: `A` and `B`.

`A` defines `<RdXmlFile>`:

```xml
<ItemGroup>
    <RdXmlFile Include="rd.xml" />
</ItemGroup>
```

`B` does not, but it references `A` via `ProjectReference`.

Does project `B` need to include `RdXmlFile` in explicit way if I want to publish `B`? Is this information transitive? 
If it's not transitive, do we plan to change it anytime soon?

cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
It's not transitive - MSBuild doesn't collect ItemGroups from referenced projects.

What we would need is to embed the RD.XML as a resource and have the compiler look for the embedded RD.XML manifest.

We have plans to do that for [ILLink.Descriptors.xml](https://github.com/dotnet/linker/blob/a709836737bf8ccc58d9b8c7d5e4bbabc8e28985/docs/data-formats.md#descriptor-format) because that's the format that also exists outside NativeAOT. But we don't have that yet and the format is also less powerful than RD.XML, unfortunately (can't express generic code).

The best would be to migrate away from the XML - either use the dataflow annotations ([DynamicallyAccessedMembers](https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/)), or write dummy code that can be analyzed (e.g. `if (string.Empty.Length > 0) typeof(Foo).GetMethod("Bar")` will keep method Bar on Foo because we can statically analyze that).

Can you point me to the RD.XML you have to see if there's better alternatives?

**Comment by adamsitnik** [comment]
> The best would be to migrate away from the XML - either use the dataflow annotations

I will give it a try, thanks!
