### ISSUE TITLE
Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#66205]
Many tests in the "runtime-coreclr jitstress-isas-x86" pipeline on x64 fail with this, e.g. JIT\\opt\\Vectorization\\UnrollEqualsStartsWIth\\UnrollEqualsStartsWIth.cmd in CoreCLR windows x64 Checked jitstress_isas_x86_nosse2:

https://dev.azure.com/dnceng/public/_build/results?buildId=1643987&view=ms.vss-test-web.build-test-results-tab&runId=45451108&paneView=debug

```
Assert failure(PID 4388 [0x00001124], Thread: 404 [0x0194]): Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()' in 'Tests_len14_9:Test_tst_32(System.String):bool' during 'Importation' (IL size 22; hash 0x1efa538e; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 18178
Image: C:\h\w\AF720924\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\AF720924\w\B4E30A89\uploads\Reports\JIT.opt\Vectorization\UnrollEqualsStartsWIth\UnrollEqualsStartsWIth.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AF720924\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  UnrollEqualsStartsWIth.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AF720924\p
C:\h\w\AF720924\w\B4E30A89\e\JIT\opt\Vectorization\UnrollEqualsStartsWIth\UnrollEqualsStartsWIth.cmd
Expected: True
Actual:   False
```

@tannergooding @dotnet/jit-contrib

**Comment by hoyosjs** [comment]
Seen profusely in #66174 for run [runtime-coreclr jitstress-isas-x86 20220305.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1643242&view=ms.vss-test-web.build-test-results-tab&runId=45433282&resultId=110069&paneView=debug)

**Comment by tannergooding** [comment]
Will take a look.

This is likely some path trying to generate SSE/SSE2 based hardware intrinsics when the user has opted into `COMPlus_EnableSSE2=0` or `COMPlus_EnableSSE=0`.

The possible fixes would be:
A. Fixup all paths to correctly respect `COMPlus_Enable*=0` for the "baseline" ISAs
B. Adjust `COMPlus_EnableSSE/SSE2=0` in particular to only impact direct hardware intrinsic importation.

We're expecting `A` today, but I'm thinking that since SSE/SSE2 is "baseline" this might be "too strict" for places in the JIT that want to utilize hardware intrinsic nodes independently of the user defined hardware intrinsics feature.

So I think doing `B` might be better, but still only for the "baseline" ISAs. Non-baseline ISAs (like SSE3 or AVX) would still require the correct checks to happen.
