### ISSUE TITLE
Change SocketsHttpHandler's default ConnectTimeout to a reasonable finite value

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#66297]
Windows will timeout a connection attempt after ~21s. Linux apparently waits much longer – around 3 minutes or more.

The connection pooling changes in 6.0 made it so that a pending connection is not associated with a specific request. As such, request cancellation no longer causes pending connections to be canceled. We do not impose any connect timeout by default (`DefaultConnectTimeout = Timeout.InfiniteTimeSpan`), so we are now exposed to Linux’s long connection timeout. In case of small request timeouts, this may lead to a potentially big number of requests timing out as they try to wait/reuse the same "pending" connection.

We should set a default ConnectTimeout to something reasonably small. We should also consider backporting that to 6.0.

I propose to unify Windows and Linux timeouts, i.e. set `DefaultConnectTimeout` to 21s.

**Comment by stephentoub** [comment]
This seems reasonable.  Technically it's a breaking change, but if a connection is taking that long to be established, it's likely going to fail, anyway.  There's also value in consistency across platforms.

Is the exception that occurs in the case of a timeout due to ConnectTimeout the same that occurs in response to the OS timing out a connection?

**Comment by CarnaViire** [comment]
> Is the exception that occurs in the case of a timeout due to ConnectTimeout the same that occurs in response to the OS timing out a connection?

Unfortunately, no.

If OS did the timeout, the error would bubble up from sockets, so we would see `HttpRequestException` with inner `SocketException` (`(110): Connection timed out` on Linux and `(10060): A connection attempt failed because the connected party did not properly respond after a period of time....` on Windows)

If it was our timeout, we would see `TaskCanceledException` with inner `TimeoutException: A connection could not be established within the configured ConnectTimeout.`

**Comment by geoffkizer** [comment]
Perhaps we should use 15s. That means that typically we'd do the timeout ourselves on both platforms. It's also a reasonably round number as compared to 21s.

**Comment by CarnaViire** [comment]
> Since we try connecting to all IPs returned by DNS (currently in serial), would changing the ConnectTimeout to something lower than the OS's timeout change the behavior so that we may no longer end up trying different IPs?

You are right 😢 and we currently don't have any per-IP timeout for multi-connect in Sockets (only a cancellation token for the whole operation) -- should we consider some new API like that?

**Comment by wfurt** [comment]
Even with eyeballs, you can have multiple addresses for the same family. And only some of them may be unreachable/unresponsive. But I would feel in most cases callers would care about overall responsiveness instead of details for each individual address.

**Comment by ManickaP** [comment]
By "something like happy eyeballs" I meant trying the parallel connect, even to multiple addresses of the same family at the same time. This is just an idea so please do not crucify me on all the details and pitfalls. I'm aware this wouldn't be as easy as running n connects in n tasks and seeing which finishes first. It would need to be carefully designed to not to drag down perf, hog ephemeral ports etc.

**Comment by CarnaViire** [comment]
Linking the existing issue containing API for socket's happy-eyeball-like parallel connect https://github.com/dotnet/runtime/issues/33418
We might want to revisit it and add more flexible options, e.g. not connecting to all IPs at once, but rather try to connect to the first IP, wait for 5s, and if it doesn't connect, try to connect to the second one without cancelling the first one, etc.

**Comment by CarnaViire** [comment]
Triage: change `DefaultConnectTimeout` to 15s in 7.0 (breaking change).
Multi-connect issues should be relatively rare. If it occurs, `ConnectTimeout` could be to set back to a big value. If we would see demand we would prioritize socket connect changes linked above.
For 6.0, consider adding telemetry to help troubleshoot hanged "pending" connection issue.

**Comment by CarnaViire** [comment]
I've put up a PR to revert this change https://github.com/dotnet/runtime/pull/68649

The change proved to be problematic as-is, because

1) There is a high chance that the user code has a retry logic that does retry when `SocketException` is caught but does not retry in case of `OperationCanceledException`. This can lead to a spike of (unretried) exceptions which weren't there before. Example:
https://github.com/NuGet/NuGet.Client/blob/93bb3921490e9d499be1fb48d6cb9dcaff734db1/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpRetryHandler.cs#L212-L263

2) The workaround with setting the `ConnectTimeout` back to infinity may not be available -- if `HttpClientHandler` is used instead of `SocketsHttpHandler` (e.g. due to reusing code between .NET Framework and .NET Core/.NET 5+), or if the code that executes the requests is hidden inside a library.

I'm reopening the issue for further discussion.

**Comment by CarnaViire** [comment]
Triage: we should address the issue in 7.0 with long OS timeouts in one way or another (retain the old exception type, tuning OS timeouts, reworking pooling logic in some way).

**Comment by pentp** [comment]
As a `SocketsHttpHandler` user I would find it very surprising to get a `TaskCanceledException` for something I haven't canceled. I would expect either `SocketException` or `TimeoutException`.

**Comment by karelz** [comment]
Triage: Let's separate 2 parts here:
1. nuget (and potentially other customers) was broken. We may break them again, but we need to document it properly.
    - The remaining risk is that someone doesn't like 15s timeout and cannot change it easily (e.g. because they target .NET Standard) -- ugly workaround for that is Reflection.
2. Which exception to throw to be consistent with our stack -- let's look at recent changes we did in the space and align with them. We may decide to follow that pattern (`TaskCanceledException` with inner `TimeoutException`), or fake `SocketsException` with inner `TimeoutException`, or start throwing directly `TimetoutException`.

**Comment by CarnaViire** [comment]
> Which exception to throw to be consistent with our stack -- let's look at recent changes we did in the space and align with them. We may decide to follow that pattern (TaskCanceledException with inner TimeoutException), or fake SocketsException with inner TimeoutException, or start throwing directly TimetoutException.

We already follow the pattern "TaskCanceledException with inner TimeoutException" in both places: 
For full-request-timeout
https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L607-L612
and for connect timeout
https://github.com/dotnet/runtime/blob/975aa549b689f10aa76addc259a0dba36419c14d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L435-L443

There was a huge discussion in https://github.com/dotnet/runtime/issues/21965 on what is better to do on timeouts, which ended up introducing this specific pattern. In general, we didn't want to change the exception type as historically TCE was thrown, and we just added a way to programmatically check whether it was a timeout (by putting TimeoutException inside)


Re mimicking SocketException, it is a bit funny given that we make sure we throw OCE and not SocketException on cancellation in Sockets 😄
https://github.com/dotnet/runtime/blob/975aa549b689f10aa76addc259a0dba36419c14d/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs#L120-L124
But there's no way on Socket level to say that the token signifies the timeout though.
I'm also not sure it would be ok to break existing behavior of ConnectTimeout, e.g. someone might depend that TCE was thrown on it?

**Comment by halter73** [comment]
I vote for simulating a `SocketException` with an inner `TimeoutException` if it's the socket that failed to connect within the timeout in order to more easily distinguish from a reqular request timeout. I usually don't really care if it's the OS or the framework that timed out the socket connection, but the message should make this clear.

> it is a bit funny given that we make sure we throw OCE and not SocketException on cancellation in Sockets 😄

If the `cancellationToken` fires before the timeout it should still be an OCE particularly if this is what could have caused the "timeout". I realize this is racy if in the background.

**Comment by antonfirsov** [comment]
`SocketException` as a subtype of `Win32Exception`, which is a type that indicates an occurrence of low level error reported by the OS. Throwing such an exception when there is no low level error directly linked to the request itself is not what I would expect from a framework. This would look even weirder when `ConnectCallback` is overridden in a way that there are no sockets involved at all.

**Comment by antonfirsov** [comment]
To me it looks like a combination of the following two mitigations would bring back the upsides of the old 5.0 connection and request cancellation behavior without hurting the benefits introduced in 6.0, and without the need of introducing an arbitrary `ConnectTimeout` value or other intrusive/breaking changes: 

1. Spawn a new connection if none is available - within limits, as recommended in Stephen's [comment](https://github.com/dotnet/runtime/issues/66297#issuecomment-1143695471).

This will not help the MaxConnectionPerServer=1 case, therefore also:

2. Link the connection's cancellation token with the cancellation token of the request that initiated it.

In case of `MaxConnectionPerServer == 1` this would practically result in a behavior that is identical to 5.0: there could be only one connection attempt, which is always associated with the first request in the queue. If the request is cancelled, the connection attempt is also cancelled, they are failing together.

In case of `MaxConnectionPerServer > 1` this would help against the accumulation of too many pending connection attempts to badly behaving servers. Thanks to #62935, a connection failure/cancellation should never fail an unrelated request. In fact, a connection failure helps serving follow-up requests, since in most cases it will spawn a new connection attempt. This would be also true if the cancellation happens because of the cancellation of the original unrelated request, therefore I see only positive effects from this change.

Note that point 2. alone does not solve the case when an earlier request with a long timeout creates a pending faulty connection that is stalling a later requests with a short timeout. From this perspective, this is why I'm recommending to combine it with more aggressive connection spawning.

@stephentoub @dotnet/ncl I wonder if I'm missing something or if you have some concerns regarding this idea?

**Comment by stephentoub** [comment]
> therefore I see only positive effects from this change.

The downsides I see to that are:
- If a request is made and then quickly canceled, we'll end up tearing down a connection that could be perfectly usable almost immediately.  We had the same issue in .NET 5, but in theory the pooling changes for .NET 6 fixed that, whether it was actually an issue in real workloads or not.
- If another connection handles a request that spawned a new connection, and that connection takes a long time to be established, it'll be holding on to the resources associated with the initial request's CancellationToken.  That might not be a big deal, but it's something to consider.
- If the initial request completes successfully due to another connection picking it up, and then after it completes successfully its token is canceled, that could again end up tearing down a connection that would have otherwise been usable soon thereafter.

It might be the right tradeoffs, of course.  Just pointing out it's not without possible issue.
