### ISSUE TITLE
Intermediate Certs not being sent from client to server on MAC

### ISSUE THREAD

**Issue by ppruthi-sfdc** [dotnet/runtime#66537]
### Description

I am trying to send certificates from client to the server to do a mTLS Handshake. Server expects 3 certs ( 1 Leaf + 2 Intermediates ).

I am adding leaf certificate like this in my code - 

```c#
HttpClientHandler handler = new HttpClientHandler();

handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.SslProtocols = SslProtocols.Tls12;

var c = X509Certificate2.CreateFromPemFile(certPath, pvtKey);
handler.ClientCertificates.Add(c);

// Create an HttpClient object
httpClient = new HttpClient(handler);
```
            

 I can see on the Wireshark that only leaf certificate is written on the wire.
 I understand that it will try to automatically build the chain from OS and add intermediates.
 Both my intermediate certs have been added to System keychain - but still it will only send the leaf cert.
 This is happening on .NET Core 5.
 Platform - MAC

### Reproduction Steps

Create HttpClient with HttpClientHandler on .NET Core 5 and try to send intermediate certs along with the leaf certificate.

### Expected behavior

Client sends the complete chain to server.

### Actual behavior

Client is not able to add intermediate certs.

**Comment by wfurt** [comment]
Can you check with X509Chain.Build that the chain can be successfully constructed. Would it make difference if you add the intermediates to users Ca store?

**Comment by ppruthi-sfdc** [comment]
1. Yes, I saw that chain is successfully getting constructed when I debugged with  X509Chain.Build.
    ```
            X509Chain chain = new X509Chain();
            chain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllFlags;
            chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
            chain.ChainPolicy.DisableCertificateDownloads = false;
            bool status = chain.Build(c);
      ```
      
      Used above policy flags and observed that chain.elements are successfully getting populated with intermediate certs.
      The chain status is "Partial Chain".
      
  2. I was under the impression that CA store doesn't work with Mac after seeing this issue opened by you.
       https://github.com/dotnet/runtime/issues/48207
       Also, tested this - but adding certs to CA store didn't help.

**Comment by wfurt** [comment]
I keep forgetting about  #48207. We should investigate. I assume you get `Partial Chain` because you did not feed it the root CA @ppruthi-sfdc?

**Comment by wfurt** [comment]
The "System Roots"  is for trusted CAs not intermediates. I look at this again we we should basically use 
```c#
SslStreamCertificateContext.Create(c, NULL, false);
```
that use `X509Chain``` under the cover. Once that build, it would be curious what that would be different. 
My assumption was that the client cannot construct the chain with intermediates. 

It may be worth of trying .NET 6 if you can. I did not see anything obvious that would make difference but it would be good to know.

**Comment by karelz** [comment]
Triage:
- Looks like a bug
- @ppruthi-sfdc any chance to provide runnable repro for us?

**Comment by maxarm** [comment]
I have a similar issue like @ppruthi-sfdc.

# Description
I am trying to send certificates from client to the server to do a mTLS Handshake. Server expects 2 certs (1 Leaf + 1 Intermediate) and I'm also using the HttpClientHandler to send the certificates from a pem file. 
This worked until .net 5.0.14; but stopped working with .net 5.0.15 and does not work with any .net 6.0.x version.
I can see on the Wireshark that only leaf certificate is written on the wire for .net 5.0.15/.net 6.0.x.
This is happening on .NET 5.0.15ff, .NET 6.0.0ff.
Platform - Linux Container

This issue is hindering to migrate to .NET 6.

# Expected behavior
Client sends the leaf and intermediate certificate to the server and client/server communication works.

# Actual behavior
The actual behavior was logged with Wireshark.
Client sends the leaf and intermediate certificate to the server when running in docker container mcr.microsoft.com/dotnet/runtime:5.0.14 and hence the communication works.
Client sends only the leaf certificate but no intermediate to the server when running in docker container mcr.microsoft.com/dotnet/runtime:6.0.6 resulting in an Unknown CA TLS error.
Client performs even no TLS handshake  when running in docker container mcr.microsoft.com/dotnet/runtime:5.0.17 resulting in failing communication.

# Additional information
- the certificates of the pem file are installed in the docker container using update-ca-certificates
- .net 5.0.14 container runs "OpenSSL 1.1.1d 10 Sep 2019" whereas .net 5.0.15/.net 6.0.x containers run "OpenSSL 1.1.1n  15 Mar 2022"
- .net 5.0.14: X509Chain.Build(cert) results in 
```
ChainBuild.Status: True
ChainBuild.ElementCount: 3
```
- .net 5.0.17/.net 6.0.x: X509Chain.Build(cert) results in
```
ChainBuild.Status: False
ChainBuild.ElementCount: 1
```

**Comment by wfurt** [comment]
While the behavior is similar this looks like distance problem @maxarm. 
@bartonjs may have some insight since it seems like you can reproduce it with simple  X509Chain.Build.
I suggest to open separate issue and post details about your intermediate certificates. 
It is certainly possible that newer OpenSSL is more picky about certificate extensions.

**Comment by bartonjs** [comment]
A diff of the v5.0.14 tag to the v5.0.15 tag shows no changes in certificate processing, so it must be something between OpenSSL 1.1.1d and 1.1.1n (or that you lost some client state during the upgrade).

As @wfurt said, it's a new problem, so should be in a new issue; but without a specific certificate that behaves differently between 5.0.14 and 5.0.15 there's no help we can provide or investigation we can do.

**Comment by maxarm** [comment]
Thanks @wfurt and @bartonjs for your help so far.
As suggested I created a new issue https://github.com/dotnet/runtime/issues/71825 containing additional information like certificates, code, stacktrace.

For me it's also interesting that 5.0.15/6.0.6 behave differently, though using same openssl 1.1.1n.
I extracted the critical code into a minimal application so there should be no unintended other changes leading to this issue.
