### ISSUE TITLE
Generating a new request from within a DelegatingHandler

### ISSUE THREAD

**Issue by j0nimost** [dotnet/runtime#66576]
I am trying to generate a new request from within the [DelegatingHandler](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers) instance but my requests are being received without the necessary headers.

_The question is on Stackoverflow : [here](https://stackoverflow.com/questions/71423646/validating-request-in-delegatinghandler-and-redirects)_

Here is my DelegatingHandler override;
```csharp
protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{

    if(!_tydeCache.IsSessionValid) // check session and redirect
        _tydeAuthHandler.SendAuthRequestAsync().GetAwaiter().GetResult(); // refresh token
 
    foreach (KeyValuePair<string, string> val in TydeCache.CacheStorage)
    {
        if(val.Key == "token")
        {
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", val.Value); // set auth header
            continue;
        }
        request.Headers.Add(val.Key, val.Value); // Add the Authorization Headers
    }
    
    return base.SendAsync(request, cancellationToken);
}
```

As you can see ` _tydeAuthHandler.SendAuthRequestAsync().GetAwaiter().GetResult(); ` generates a new Http Request if the validation fails.

**NOTE**: HTTPClient is Dependency Injected as `Singleton`

Once the sessions are validated the new header values are now added as the "request resumes".

However, on my client application. The headers are missing even though we added them on "resume". Below is how I check for headers on my client.

```csharp
 public async Task Invoke(HttpContext context, IAuthHandler authHandler)
 {
     var token = context.Request.Headers["Authorization"].FirstOrDefault()?.Split(" ").Last();
     var username = authHandler.ValidateToken(token);
     if (!String.IsNullOrEmpty(username))
     
         context.Items["User"] = UserService.UserDict[username];
     
     await _next(context);
 }
```

My questions are;
- Is it possible to instantiate a new request from the DelegatingHandler?
- Can I "resume" a request from a different scope than that of the DelegatingHandler?
- Is it possible to do the above implementation?

**Comment by ManickaP** [comment]
How do you instantiate and use the delegating handler, do you set up any settings on `SocketsHttpHandler`? Did you debug/log the actual requests being sent from the client side? Could you share the request/response exchanges (without any sensitive details), e.g. do a packet capture, or use fiddler.
Also be aware that `Authorization` header is a known header and `HttpClient` in some cases modifies it, e.g.: in case of a redirect it will remove it, in case of set up credentials it will try to do authentication on it's own.

Lastly, since you already are in an `async` method you shouldn't be using `.GetAwaiter().GetResult()`, you should just `await` the call.
