### ISSUE TITLE
System.Text.Json POCOs with constructor deserialization do not support metadata reads

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#66604]
While doing infrastructural work for #63747 I discovered that metadata reads for objects with constructor deserialization has not been implemented. This [appears to be by design](https://github.com/dotnet/runtime/blob/edf14c1d160006cb247c2ece7b16ddb01f03fd56/src/libraries/System.Text.Json/src/Resources/Strings.resx#L479-L481) and I'm guessing it's because it's impossible to use constructor-based deserialization for cyclic object graphs (@Jozkee to confirm or disconfirm this). We still need to bring metadata read support in constructor converters for a couple of reasons:

1. Reference preservation does not strictly concern itself with cyclic dependencies. We can still detect and fail on cyclic dependencies but support all other reference preservation scenaria.
2. Metadata reads are needed for polymorphism, which should be supported for constructor-based deserialization.

This change is needed by #63747 but it's substantial enough to warrant its own tracking issue. We should also extend reference preservation test coverage to async serialization (as tracked  by https://github.com/dotnet/runtime/issues/66463) before we can confidently make this change.

**Comment by Jozkee** [comment]
> We can still detect and fail on cyclic dependencies but support all other reference preservation scenaria.

May not be a good idea 
1) you would need to maintain an stack that tracks the object graph but `ReferenceHander.Preserve` is supposed to use map semantics, where it replaces every $ref with its respective $id, it shouldn't use stack semantics.
2) `ReferenceHander.IgnoreCycles` already does this but instead of failing, "ignores"; if you want failures it would be better to add another handler, say `ReferenceHandler.ErrorOnCycles`.

I don't remember the technical reasons why parameterized ctors doesn't support reference preservation metadata but it could be possible for both features to co-exist. If you read `$id`, call `ReferenceResolver.AddReference(...)` after the .ctor to save the reference, if you read `$ref`, don't call the .ctor, use `ReferenceResolver.ResolveReference(...)` instead.

**Comment by eiriktsarpalis** [comment]
Indeed, we might want to repurpose some of the `IgnoreCycles` object stack infrastructure to make such detection possible. One possible stopgap solution (I have this already working in a prototype) is to simply disallow references in constructor arguments. So for a poco such as:
```C#
public record Person(Person? parent);
```
It should be legal to deserialize a JSON value such as
```json
{ "$id" : "1", "parent" : { "parent" : null }}
```
But illegal to deserialize
```C#
{ "$id" : "1", "parent" : { "$id" : "2", "parent" : null } }
```
Even though no cycles are present.

**Comment by eiriktsarpalis** [comment]
>> disallow references in constructor arguments.
>
>What if you track those references as well?

Maybe I don't follow the question, but deserialization would fail with an exception (as is currently the case) so it shouldn't matter?
