### ISSUE TITLE
JsonSourceGenerationMode.Metadata emits references to internal members from another assembly

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#66679]
### Description

JsonSourceGenerationMode.Metadata emits references to internal members from another assembly

Discovered as F# generates most types with internal fields due to it having slightly different accessibility semantics than IL. We are using some of these types from a C# assembly where we've been experimenting with the json source generator.

This only concerns the `Metadata` mode, any internal field on a referenced type is being emitted/referenced by the source generator causing a C# compiler error `'Foo._value' is inaccessible due to its protection level`. 

Frustratingly `IncludeFields = false` has no effect here. JsonIgnore attributes seem to be the only workaround, assuming the type is even under your control.

### Reproduction Steps

Assembly 1

```cs
public struct Foo 
{
    internal int _value;
    public Foo(int value) => _value = value;
    public int Value => _value;
}
```

Assembly 2 
```cs
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata, PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, IncludeFields = false)]
[JsonSerializable(typeof(Bar))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}

public class Bar 
{
    public Foo Foo { get; set; }
}
```

### Expected behavior

-

### Actual behavior

```
System.Text.Json.SourceGeneration/System.Text.Json.SourceGeneration.JsonSourceGenerator/SourceGenerationContext.Foo.g.cs: error CS0122: 'Foo._value' is inaccessible due to its protection level.
```

### Configuration

.NET 6.0.201, also tried with 7.0 preview 2.

### Other information

@eiriktsarpalis besides this being an issue for C# it's even worse for F# as primary constructors don't allow you to add a JsonIgnore attribute, requiring you to rewrite the struct to use `val` (as let bindings are 'verboten' in them). Though better with classes it still requires binding all arguments to individual let bindings.

We are planning to move some of our app hosting code back to C# so we can use the source generator for our api models (which are already POCOs, no DUs etc). We want to work towards a trimmable and mostly reflection free app to for eventual NativeAOT compilation. I do hope for .NET 7.0 F# POCOs will just work, ideally without having to add JsonConstructor/JsonIgnore attributes everywhere.

**Comment by austindrenski** [comment]
> Moving to .NET 8 milestone.

@eiriktsarpalis This is disappointing, but can appreciate there are competing priorities.

If this bug is going to be around for a while, could we get some feedback on endorsed/recommended workarounds?

In my case, we've encountered this issue when our derived `JsonSerializerContext` includes POCOs with properties of [NodaTime](https://github.com/nodatime/nodatime) types. Specifically, the source generator emits references to the `internal` [`YearMonthDayCalendar`](https://github.com/nodatime/nodatime/blob/main/src/NodaTime/YearMonthDayCalendar.cs) type.

So far, we've been able to workaround this by defining a `public` stub for the type (_note: our stub has to be `public` because our `JsonSerializerContext` is `public`_), which works to get past the compiler, but leaves something to be desired since this stub type is now visible to downstream consumers of our package.


```csharp
namespace NodaTime;

[System.Obsolete("Proxy type for System.Text.Json to work around https://github.com/dotnet/runtime/issues/66679")]
public readonly struct YearMonthDayCalendar
{
}
```

**Comment by eiriktsarpalis** [comment]
As noted in #76919 the similar problem manifests within one assembly as well when handling `private protected` fields:

```C#
[JsonSerializable(typeof(MyPoco))]
internal partial class MyContext : JsonSerializerContext
{
}

public class MyPoco
{
    private protected int _field;
}
```

A fix should ensure that we address both issues.
