### ISSUE TITLE
[NativeAOT] Metadata not trimmed for nested Interface types when compiling TerraFx.Interop.Windows

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#66716]
Same repro as https://github.com/dotnet/runtime/issues/66593#issue-1168602488

Actual result: Nested `Interface` types like `TerraFX.Interop.Windows.IEnumWbemClassObject+Interface` types are present in the final binary

Expected result: `TerraFX.Interop.Windows.IEnumWbemClassObject+Interface` types are not present in the final binary (IL linker is able to trim these)

**Comment by jkotas** [comment]
@MichalStrehovsky Does this ring any bells?

**Comment by agocke** [comment]
@jkotas Fixed by #66593?

**Comment by MichalStrehovsky** [comment]
We don't trim interface lists. I played with it in the past (https://github.com/MichalStrehovsky/runtimelab/commit/2a702bcae6556cb866b10c9b54fb94d604de28b0), but it's a bit more involved (the above commit was enough to get a size estimate and I remember the size saving being interesting - more than 1% - but not interesting enough to spend time on it at that point).

It will require changing most of the occurrences of `.RuntimeInterfaces` in the dependency analysis within the compiler to use some kind of indirection. It will likely be something similar to how we track virtual method use.

I'll put this into Future since this is a nice to have size optimization.

**Comment by MichalStrehovsky** [comment]
I had a quick look - the only reason why we're generating the interfaces is because we're generating the struct that implements them. And the only reason why we generate the struct is because we called some instance methods on it and it became a potential target of reflection in the "IL Linker compat mode" we run by default (where whatever is called is considered reflection-accessible at runtime).

In the strict mode `<IlcTrimMetadata>true</IlcTrimMetadata>` we don't generate any of that. The repro in the top-post is 20% smaller with that setting.

I wish we just enabled the strict mode by default...

**Comment by jkotas** [comment]
> I wish we just enabled the strict mode by default...

I have been thinking about the recently. I think we should enable the strict mode by default.

**Comment by jkotas** [comment]
The default experience today is that you always see these messages:
- `Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeNativeAOT`
- `Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing.` message.`

We should change the default experience so that you only see `Generating native code` by default, enable `IlcTrimMetadata` by default, get all assemblies treated as trimmable by default (ie do not root app, etc.).

If there are no trimming or AOT warnings, it is all you get. Nice and clean experience.

If there are trimming or AOT warnings, we print additional message with a link to a top-level doc that has talks about fixing the warnings properly and that has list of workarounds (e.g. setting IlcTrimMetadata to false, etc.). 

Thoughts?

**Comment by jkotas** [comment]
The conservative defaults made sense before we had the analyzers and enabling AOT was a guesswork. Now that we have the analyzers, we should be able to be more aggressive by default.

**Comment by MichalStrehovsky** [comment]
The `Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing.` message shouldn't show up after https://github.com/dotnet/sdk/pull/22636 - it will only show up if warnings are disabled.

I can definitely get behind enabling `IlcTrimMetadata` by default. The only observable difference with that setting will be around code that is already generating a trimming warning. (For anyone else reading this, `IlcTrimMetadata` skips generating reflection metadata for members that are not visible targets of reflection, kind of similar to https://github.com/dotnet/linker/issues/1282, but with more stripping and less breaking of debugging experience since debug symbols are separate).

> get all assemblies treated as trimmable by default (ie do not root app, etc.).

But this one I would like to do consistently - we either do this with IL Linker too, or we don't. It doesn't feel good for the AOT business to be more breaking than PublishTrimmed when it comes to trimming. We had a discussion about what the default should be in .NET 6. We went with rooting all assemblies that are not manifested as trimmable. There is an argument for doing the more aggressive thing - pretty much all our trimming warnings are not relevant for most apps because the target of their reflection is not in a trimmable assembly - so we spam dozens of warnings and the app still works fine. It feels better to generate fewer warnings that are all relevant (and the app being more likely to be broken) and have the old behavior behind another opt in.

Cc @dotnet/ilc-contrib for thoughts.

**Comment by jkotas** [comment]
> It feels better to generate fewer warnings that are all relevant (and the app being more likely to be broken)

Agree. 

Also, I would like to keep emphasizing the importance of fixing the trimming warnings. The current defaults dilute this message since the conservative default covers up a lot of the issue, but not all of them.
