### ISSUE TITLE
IMemoryCache.Dispose should call Dispose on cached value if it implements IDisposable 2

### ISSUE THREAD

**Issue by ivanicin** [dotnet/runtime#66724]
Consider the following scenario:
- an object is stored in the cache and only the cache has the reference to it
- user code gets this object (e.g. there is a second reference to it) and starts using it
- cache senses memory pressure and choses to evict this object (and calls Dispose() on it)
- user code continues using the object even though it is now disposed
Looks like a recepe for troubles and various timing issues.

_Originally posted by @KKhurin in https://github.com/dotnet/runtime/issues/26431#issuecomment-396418359_

The reason above was quoted as the reason not to implement this behaviour. However I'll give you another 'recipe for troubles': use MemoryCache with Xamarin to store images as is currently implemented.

Just for the record the memory management in Xamarin is performed quite differently and it is expected that Dispose is called in cases like this for the app to manage memory properly.

The current implementation is basically useless in Xamarin unless you store only fully managed types which is extremely unlikely use case for Xamarin.

So as long as you want to support Xamarin something needs to be changed.

**Comment by KKhurin** [comment]
Regardless of Xamarin the issue is how would the cache know that it "owns" the items it references? Without such explicit knowledge it would not be able to properly determine whether it needs to dispose them or not. 

If one stores managed wrappers of images in the cache and one knows for sure that once the image is removed from the cache it must be disposed, one solution would be to rely on `RemovedCallback` to do the proper cleanup.

**Comment by ivanicin** [comment]
@KKhurin thanks, reading the previous conversation quoted above I believe that such callback was not implemented. It could be either that it wasn't implemented at that time or that it wasn't clearly explained as the user referred to that as a possible solution he would find satisfactory.

Anyway it is ok in that case.
