### ISSUE TITLE
[API Proposal]: Expose `NativeLength` in `Array`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#66775]
### Background and motivation

I like to work with n(u)ints

### API Proposal

```C#
namespace System {
    public abstract partial class Array : ICloneable, IList, IStructuralComparable, IStructuralEquatable
    {
        public nuint NativeLength { get; }
    }
}
```

### API Usage

```C#
var array = new int[100];
fixed(int* ptr = &array) {
    // Pass array length for marshalling purposes where the callee takes an architecture-width integer
    MyExternMethod(ptr, array.NativeLength);
}
```

### Risks

Property is currently internal. 
-> Minimal change
-> No risk

**Comment by teo-tsirpanis** [comment]
You can already implicitly cast the int `Length` returns to `nint`.

A `NativeLength` property would make sense only when and if it is decided that arrays can hold more than 2 billion elements. Until then I personally don't find a use case for it, and the risk is that it will be confusing since its value will always come from a truncated range.

**Comment by deeprobin** [comment]
> You can already implicitly cast the int `Length` returns to `nint`.
> 
> A `NativeLength` property would make sense only when and if it is decided that arrays can hold more than 2 billion elements. Until then I personally don't find a use case for it, and the risk is that it will be confusing since its value will always come from a truncated range.

Then why is there `LongLength`?

**Comment by tannergooding** [comment]
`LongLength` exists because it returns the linear length of a multi-dimensional array, which may in fact be over 2 billion elements.

Exposing an actual `NativeLength` (one that allows greater than `int.MaxValue` elements) wouldn't be possible without (likely non-trivial) GC work as well as determining how to handle the breaking changes. -- Any `for (int i = 0; i < array.Length; i++)` loop is now a potential point of failure.

The same in general goes for `Span<T>` and `ReadOnlySpan<T>`.

--------------------

This likely requires either a new type (e.g. `NativeSpan<T>`) or some explicit agreement/decision around how to handle the "break".

For the latter, the closest I've considered is having `Length` become a `checked` cast which the JIT is able to elide and hoist in the right scenarios to mitigate the cost. The likelihood of encountering inputs this big is "likely rare" and so most scenarios would "continue working" with the opportunity to update and adjust code over time to support the larger size.

However, that is also something that would need extensive design docs, discussion, and approval from relevant maintainers/architects and is non-trivial.

--------------------

There are many other issues along these lines including https://github.com/dotnet/runtime/issues/12221, so I'm going to close this as a duplicate.

CC. @jkotas as an FYI that there is another request here.
