### ISSUE TITLE
[API Proposal]: Can System.Net.Http.Json inject a serializer to let the user decide which serializer to use

### ISSUE THREAD

**Issue by sgalcheung** [dotnet/runtime#66835]
### Background and motivation

As we all know, Json.Net has been used as the default serializer for some time. However, as an official new player, System.Text.Json still needs time to improve. Therefore, Json.Net or System.Text.Json should submit It's up to the user to decide which serializer to use, maybe based on their project situation, or maybe the user's preference, so I suggest that it's better to allow injecting serializers

### API Proposal

private JsonContent(
            object? inputValue,
            Type inputType!!,
            MediaTypeHeaderValue? mediaType,
            JsonSerializer? serializer){}

### API Usage

new JsonContent(data, type, null, new Newtonsoft.Json.JsonSerializer())
or 
new JsonContent(data, type, null) // default System.Text.Json serializer

**Comment by teo-tsirpanis** [comment]
Hello @sgalcheung, unfortunately there is no common interface between `System.Text.Json` and `Newtonsoft.Json`, meaning that `JsonContent` cannot support both JSON libraries. To support it, you need to write your own descendant of `HttpContent`.

Since such class cannot be added to the BCL because it would involve taking a dependency on a third-party library, I will close this issue. Feel free to ask any further questions.
