### ISSUE TITLE
TrimEnd works strangely

### ISSUE THREAD

**Issue by master0luc** [dotnet/runtime#66909]
Hello, I am not sure, is it a bug or just a feature:
```
// See https://aka.ms/new-console-template for more information
var suffix = "/auth/realms/";
var suffixCharArray = suffix.ToCharArray();
var testString1 = "https://some-name.some-host.net/auth/realms/";
var testString2 = "https://some-name.some-host.net:90/auth/realms/";
Console.WriteLine($"suffix=>{string.Join("", suffixCharArray)}");
Console.WriteLine(testString1);
Console.WriteLine(testString1.TrimEnd(suffixCharArray));
Console.WriteLine(testString2);
Console.WriteLine(testString2.TrimEnd(suffixCharArray));
```
result
```
suffix=>/auth/realms/
https://some-name.some-host.net/auth/realms/
https://some-name.some-host.n
https://some-name.some-host.net:90/auth/realms/
https://some-name.some-host.net:90
```
so I see here unpredictable begavior of TrimEnd: remove 2 additional chars: "**et**" in the first case
May be I am wrong.

**Comment by Wraith2** [comment]
Your code creates a char array which contains all the characters in the suffix string. Your call to TrimEnd removes characters from the input string until it finds on that does not exist in the array argument or the string becomes 0 length. So for `https://some-name.some-host.net` because both `e` and 't' exist in the string you used to construct the array of items to be removed, `/au**t**h/r**e**alm' they are removed. It feels like you're looking to detect if the string EndsWith() and then substring or slice the input, not TrimEnd with a char array.

**Comment by master0luc** [comment]
@Wraith2, You are precisely right, I have tryed just trim a  suffix without an additional check.
So, now I  have got an idea of TrimEnd: Just remove any symbols from char[] if it is at the end of the string.
My fault
