### ISSUE TITLE
Environment.OSVersion.Platform Returns Unix NOT MacOSX

### ISSUE THREAD

**Issue by shmellyorc** [dotnet/runtime#66940]
### Description

Environment.OSVersion.Platform == PlatformID.MacOSX does not return back MacOs but it returns back as Unix.

### Reproduction Steps

go on ANY version MacOs and type Environment.OSVersion.Platform and see what the result you get.

### Expected behavior

should return PlatformID.MacOSX

### Actual behavior

PlatformID.Unix

### Regression?

N/A - didnt check.

### Known Workarounds

used RuntimeInformation.IsOSPlatform(OSPlatform.OSX) to check if I was on a mac but many might not know about it.

### Configuration

- Normal dotnet core 6 console application
- Latest version of Macos

### Other information

Please fix, very annoying.

**Comment by filipnavara** [comment]
This is documented historical quirk. `PlatformID.MacOSX` was only ever used on Sliverlight. Mono on macOS used `PlatformID.Unix` and .NET (Core) inherited that for broader compatibility.

You can use `OperatingSystem.IsMacOS()` as the preferred API which is also recognised by the code analysers to warn you about using platform specific APIs which would otherwise throw `PlatformNotSupportedException`.

**Comment by danmoseley** [comment]
Closing as it's answered -- @shmellyorc if the docs could be clearer, feel free to hit "edit" on that page.
