### ISSUE TITLE
JsonDocument.ParseValue throws exception when parsing Utf8JsonReader when the json has a comment

### ISSUE THREAD

**Issue by dermotblairca** [dotnet/runtime#67004]
### Description

JsonDocument.ParseValue throws exception `Expected start of a property name or value, but instead reached end of data` if the Utf8JsonReader has a comment in the json, even when the Utf8JsonReader has the CommentHandling option = JsonCommentHandling.Skip.

### Reproduction Steps

Run the following console app:
```
using System.Text;
using System.Text.Json;

try
{
    var options = new JsonReaderOptions
    {
        CommentHandling = JsonCommentHandling.Skip
    };
    var json = "{" +
                   "\"id\":\"test\", //comment" +
                   "\"id2\":\"test2\"" +
                "}";
    var jsonUtf8Bytes = Encoding.UTF8.GetBytes(json);
    var reader = new Utf8JsonReader(jsonUtf8Bytes, options);
    var jsonDoc = JsonDocument.ParseValue(ref reader);
    Console.WriteLine("Json parsed successfully");
}
catch (Exception ex)
{
    Console.WriteLine("Json parsing failed: " + ex.Message);
}
```

### Expected behavior

I think it should parse the json successfully, or maybe there should be another overload of `ParseValue(ref Utf8JsonReader reader)` available that also accepts a JsonDocumentOptions which could specify the JsonCommentHandling.Skip option.

### Actual behavior

An exception is thrown and the above app outputs `Json parsing failed: Expected start of a property name or value, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 39.`

### Configuration

.NET 6.0 on Windows x64. I don't think it's specific to just this configuration.

**Comment by B1Z0N** [comment]
Hi @dermotblairca!

> maybe there should be another overload of ParseValue(ref Utf8JsonReader reader) available that also accepts a JsonDocumentOptions which could specify the JsonCommentHandling.Skip option

Currently `JsonDocument.ParseValue` uses `Utf8JsonReader` options that you've passed to it and only allows `Skip` or `Disallow` values. On `Allow` it throws `ArgumentException`(see [declaration here](https://github.com/dotnet/runtime/blob/c5d40c9e703fd257db1b26ef4fd1399bbae73ab0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L1109) and [usage here](https://github.com/dotnet/runtime/blob/c5d40c9e703fd257db1b26ef4fd1399bbae73ab0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs#L403)). So, perhaps there's no need to change anything.

About the error, from what I see, it's that your json is a oneliner and the parser doesn't actually knows where the comment ends. It knows where the comments starts(here `//` characters) but it can't actually know where it ends. So you just need to decide where it ends and denote that place with end of line(e.g. "\n" symbol). For example:

```csharp
var json = "{" +
  "id\":\"test\", //comment\n" +
  "\"id2\":\"test2\"" +
"}";
```

And my question to some of the `System.Text.Json` devs here: should we swtich to more concise error message about **invalid json due to unfinished comment**  or it's very uncommon and we should leave it as is?

**Comment by dermotblairca** [comment]
Thanks for looking into it @B1Z0N I initially thought it might be an issue where the ParseValue function wasn't using the options of the Utf8JsonReader somehow. Good to know it can be resolved by adding a newline after the comment.

**Comment by eiriktsarpalis** [comment]
It would seem like your question has been answered @dermotblairca?
