### ISSUE TITLE
An error occurs when an expression is used as a parameter to a generic attribute constructor.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#67085]
### Description

An error occurs when an expression is used as a parameter to a generic attribute constructor.

### Reproduction Steps

```c#
    public class MapperAttribute<T> : Attribute
    {
        public MapperAttribute(Expression<Func<T, object>> exp)
        {

        }
    }

    public class MapperSrc
    {
        public string Name;
    }

    public class MapperDest 
    {
        [Mapper<MapperSrc>(item=>item.Name)]  // error : CS0181
        public string D_Name;
    }
```

### Expected behavior

No error.

### Actual behavior

https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS0181)

**Comment by Joe4evr** [comment]
Why do so many people believe that just because you can declare an attribute to be a generic class now that it suddenly also supports non-constant parameter values? And no, lambda expressions are not constant values.

You cannot supply parameter types to attributes that you couldn't supply prior to this change, which are well-documented.

**Comment by MichalStrehovsky** [comment]
`Expression<T>` is not a valid [attribute parameter type](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/attributes.md#2124-attribute-parameter-types) per the C# language spec. If you would like to change the language spec, those things happen in the dotnet/csharplang repo.

**Comment by NMSAzulX** [comment]
@MichalStrehovsky @Joe4evr  Thanks.
