### ISSUE TITLE
[API Proposal]: [ReadOnly]Span<T>.CreateUnsafe(ref T, int) for compiler-tracked, arbitrary length spans

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#67242]
### Background and motivation

> Follow up from the discussion started in #64750.

The general idea for this proposal is: with the changes to lifetime annotations for refs in C# 11, developers will be able to just do `new [ReadOnly]Span(ref foo)` to create a 1-length span from an arbitrary reference, which the compiler will be able to properly track. The issue remains though for arbitrary length spans, where currently the only alternative is `MemoryMarshal.CreateSpan`, which has the issue that does _not_ track lifetime annotations of the input reference. This is not desireable, as in many cases the only "unsafe" component library authors want is being able to pass an arbitrary length, but without giving up on lifetime tracking.

To solve this, the proposal is for a new set of APIs that would act as a "safer" version of `MemoryMarshal.CreateSpan`.
The crucial difference is that the `ref T` parameter would _not_ be `scoped`, so the compiler would see it escaping the API.

### API Proposal

```C#
namespace System
{
    public ref struct Span<T>
    {
        public static Span<T> CreateUnsafe(ref T value, int length);
    }

    public ref struct ReadOnlySpan<T>
    {
        public static ReadOnlySpan<T> CreateUnsafe(ref T value, int length);
    }
}
```

These two APIs will also validate that the length is in the allowed range, just like the `void*` span constructors. The two APIs should essentially be equivalent on this front, the only difference being this will work on a tracked GC-ref and not a raw pointer.

> Note: I'd be happy to be assigned this one in case it got past API review 🙂

### API Usage

Just like with `MemoryMarshal.CreateSpan`, but with tracking.

### Alternative Designs

A possible alternative could've been to break `MemoryMarshal.CreateSpan` and make the `ref T` argument a `scoped ref T`, but as discussed that could be problematic as there migth still be niche cases where dropping the tracking could be needed.

### Risks

None, really. If anything else, this would push developers towards a safer version of `MemoryMarshal.CreateSpan`.

**Comment by GrabYourPitchforks** [comment]
@Sergio0694 - per Discord chat, do you plan on argument checking the _value_ or _length_ parameters? E.g., don't allow _length_ to be negative, don't allow _value_ to be null if _length_ is nonzero, etc.?

**Comment by Sergio0694** [comment]
As @tannergooding also mentioned, the "unsafeness" of this API should just be from the arbitrary length, but outside of that the resulting instance should be valid and with arguments in the same range normally expected for the type. As such, I reckon we should validate that the length is in the allowed range, that is, the same exact check that the `void*` constructor is doing. The two APIs should essentially be equivalent on this front, the only difference being this will work on a GC-ref. I'll add this to the PR description as well.

**Comment by stephentoub** [comment]
> This is not desireable, as in many cases the only "unsafe" component library authors want is being able to pass an arbitrary length, but without giving up on lifetime tracking.

I'm having trouble seeing how this adds enough value to be worth the additional API, and in particular the ensuing confusion about having two different unsafe APIs for creating a span from a ref and a length that are unsafe in slightly different ways.

Both the proposed API and MemoryMarshal.CreateSpan are inherently unsafe and dangerous.  If you get the length wrong, you can start overwriting who knows what.  And anyone who feels the additional API is providing meaningful security can define it themselves in one line:
```C#
static Span<T> CreateUnsafeButMaybeSlightlyLessUnsafe(ref T value, int length) => MemoryMarshal.CreateSpan(ref value, length);
```

Can you share concrete examples where the proposed API will be used and significantly move the needle on security to the point where it's worth said confusion?

**Comment by Sergio0694** [comment]
The proposed API will essentially make it impossible to have dangling pointers, ie. to accidentally create GC holes (as well as not allowing negative lengths). Yes being able to pass an arbitrary length is still unsafe, but much less than it was before.

As per the latest version of the "lowlevel struct improvements" ([here](https://github.com/dotnet/csharplang/pull/5959)) proposal by @jaredpar, we'd have:

```csharp
// With this proposal
public ref struct Span<T>
{
    public static Span<T> CreateUnsafe(ref T value, int length);
}

// Updated BCL API in .NET 7
public static class MemoryMarshal
{
    public static Span<T> CreateSpan<T>(scoped ref T value, int length);
}
```

With `MemoryMarshal.CreateSpan` obviously cheating and not actually respecting `scoped`. Consider this:

```csharp
// Accidental GC hole
static Span<T> Foo(int x)
{
    return MemoryMarshal.CreateSpan(ref x, 1);
}

// Accidental GC hole #2
static Span<int> Bar()
{
    Span<int> foo = stackalloc int[10];
    
    ref int value = ref foo[0];
    
    return MemoryMarshal.CreateSpan(ref value, 1);
}

// This compiles and may lead to GC holes as there's no lifetime annotations
public struct Foo
{
    public long value;
    
    public Span<byte> AsBytes()
    {
        return MemoryMarshal.CreateSpan(ref Unsafe.As<long, byte>(ref value), 4);
    }
}
```

All of these scenarios can be avoided with a better `Span<T>.CreateUnsafe` that tracked lifetime rules.

The first two cases (and all analogous ones) would just outright fail to compile. The latter would force developers to properly annotate the type/APIs so that callers wouldn't be able to accidentally escape that returned `Span<byte>` outside the scope of a `Foo` instance where that method is invoked upon.

All in all the argument is: there's still plenty of scenarios in lowlevel code where developers might have to manually create a `Span<T>` instance from a reference with an arbitrary length. The current API is _extremely_ dangerous, and the current ones would make this pattern significantly safe, which for cases where you're already dealing with tricky code, is not a bad thing 🙂

**Comment by tannergooding** [comment]
I think Sergio gave a fairly good summary.

Not all `unsafe` is the same level of `unsafe` and 100% of unsafe code is safe when used safely.

This gives developers a tool that helps make something dangerous slightly less so. While you can still be error prone or do the wrong thing with it, it helps protect against what is often a more egregious and easier to make mistake around lifetimes.

I expect there are places we would use this in the BCL to help prevent various security or lifetime bugs while still allowing high perf. We're only human and so we're bound to make mistakes, having a little bit of safety rope or equipment is always good.

**Comment by stephentoub** [comment]
I understand the feature.  I disagree with the conclusion.

Of the existing use of MemoryMarshal.Create{ReadOnly}Span in dotnet/runtime, very few of them are used in a situation where there's even a possibility of a dev doing the wrong thing, e.g. it's in an API that doesn't hand back a ref struct.  I do not see the proposed API meaningfully moving a needle here.

> // Accidental GC hole
> static Span<T> Foo(int x)
> {
>     return MemoryMarshal.CreateSpan(ref x, 1);
> }
> 
> // Accidental GC hole #2
> static Span<int> Bar()
> {
>     Span<int> foo = stackalloc int[10];
>     
>     ref int value = ref foo[0];
>     
>     return MemoryMarshal.CreateSpan(ref value, 1);
> }

Those examples aren't "GC holes": they're spans referring to ints on the stack.  You can cause just as much trouble providing a wrong length as you can returning them.

> The current API is extremely dangerous

So is the proposed new one.  Except instead of having one dangerous "CreateSpan" that's unsafe, now we'd have two, and two with subtly different semantics.  Just adding an additional one doesn't somehow magically make the existing one go away.

If we _really_ believe it's meaningfully better, then we should _not_ add `scoped` to the existing `MemoryMarshal.Create{ReadOnly}Span`, essentially making some existing usage a breaking change upon upgrade to C# 11, and we should then add `scoped` to `Unsafe.AsRef`'s argument, such that someone who really needs the non-lifetime-tracked behavior can get it by using `Unsafe.AsRef` at the call site.  We should not add yet another variant of the same method.

**Comment by tannergooding** [comment]
> If we really believe it's meaningfully better, then we should not add scoped to the existing MemoryMarshal.Create{ReadOnly}Span, essentially making some existing usage a breaking change upon upgrade to C# 11, and we should then add scoped to Unsafe.AsRef's argument, such that someone who really needs the non-lifetime-tracked behavior can get it by using Unsafe.AsRef at the call site. We should not add yet another variant of the same method.

Today we have `Span<T> MemoryMarshal.CreateSpan(ref T value, int length) => new Span<T>(ref value, length)`. Due to current language rules the returned `Span<T>` is assumed that it cannot capture `ref value` and so the current API is unsafe.

With the C# 11 language rule changes here, if we make no changes it would be assumed to capture and the returned `Span<T>` would be tied to the lifetime of the `ref value`.

If we wanted to remain compatible, we can change the API to be: `Span<T> MemoryMarshal.CreateSpan(scoped ref T value, int length) => new Span<T>(ref Unsafe.AsUnscoped(ref value), length);`. This would preserve the current "non-capturing" semantics and uses an `Unsafe` API to strip the `scopedness` of the `ref value` to make this possible.

Now, if we were to take the "breaking" change to `CreateSpan`, then we would need some additional API that takes in the `Span<T>` which currently tracks the lifetime of `ref value` and return a new `Span<T>` which does not. My understanding is that we would, as such, need `Span<T> Unsafe.AsUnscoped(scoped Span<T> value)` and `ReadOnlySpan<T> Unsafe.AsUnscoped(scoped Span<T> value)`.

So I believe, and hopefully @jaredpar could confirm or tell me where I'm wrong, that we need some new API in most of the scenarios.
A) Preserve the semantics around `MemoryMarshal.CreateSpan` keeping it so the lifetime isn't tracked and expose no new APIs. Users need to build their own `Span<T> SomeClass.CreateSpan<T>(ref T value, int length) => MemoryMarshal.CreateSpan(ref value, length)` so that the returned `Span<T>` tracks the lifetime of `ref value`
B) Preserve the semantics around `MemoryMarshal.CreateSpan` keeping it so the lifetime isn't tracked and expose some API which does track the lifetime (`Span<T> Span<T>.CreateUnsafe<T>(ref T value, int length)`)
C) Break the semantics around `MemoryMarshal.CreateSpan`, breaking it so the lifetime is tracked and expose new APIs that allow removing the tracking -- I don't believe that there is a way (outside manually writing IL) for a user to do this

This proposal, and my own preference, are for B. We ultimately have to have some API on `Span<T>` regardless to support `MemoryMarshal.CreateSpan`. Today, that is an internal constructor which we would never want to expose since there is no way to do something like `UnsafeCallersOnly`. We could however expose a `Span<T> CreateUnsafe(ref T value, int length)` method which fits our existing pattern and points users towards a more correct, but still unsafe option. Another reason is that this is a feature which many lowlevel devs are passionate about and wanting, its why we already have a proposal up suggesting something be done here despite there being no feature branch or the like yet. There is obvious interest and desire for additional safety gear here, even if it only provide minimal protection.

**Comment by stephentoub** [comment]
> Now, if we were to take the "breaking" change to CreateSpan, then we would need some additional API that takes in the Span<T> which currently tracks the lifetime of ref value and return a new Span<T> which does not. My understanding is that we would, as such, need Span<T> Unsafe.AsUnscoped(scoped Span<T> value) and ReadOnlySpan<T> Unsafe.AsUnscoped(scoped Span<T> value).

Why would it need to be on the span?  If we were to leave `MemoryMarshal.CreateSpan` unadorned, a span returned from it is still returnable if the lifetime of the input ref isn't local... so an Unsafe.AsRef that removed the local lifetime would suffice.  In other words, you wouldn't modify the scopedness of the span returned from CreateSpan, rather you'd modify the lifetime of the ref being passed in (`MemoryMarshal.CreateSpan(ref Unsafe.AsRef(ref scopedRef), length)`).  That is what I was suggesting we do if we feel we must do something here.  We add `scoped` to the existing Unsafe.AsRef argument and call it a day.

**Comment by tannergooding** [comment]
I think B is the best, then A, and C would be the worst.

> you wouldn't modify the scopedness of the span returned from CreateSpan, rather you'd modify the lifetime of the ref being passed in (MemoryMarshal.CreateSpan(ref Unsafe.AsRef(localLifetimeRef), length)).

Right... This would work because even through `CreateSpan` tracks the lifetime; `ref Unsafe.AsUnscoped(ref value)` would be assumed to be a different scoping from `ref value` and would have to assume its therefore something directly in the GC heap (like an array interior pointer) or something...

**Comment by stephentoub** [comment]
> I think B is the best, then A, and C would be the worst.

Then I think we should close this.

**Comment by gfoidl** [comment]
Please don't let become `CreateSpan` the new timers in .NET 😉 

---

When (A) is not viable, then I find it much better to annotate, etc. the existing API and fix breaking changes there*, than introducing another API for (almost) the same thing (C).

\* it's unsafe, so not that widely used and users who use this API (hopefully) know what they are doing, so a breaking change here isn't that bad to also revisit what's done unsafe

**Comment by Sergio0694** [comment]
> "Those examples aren't "GC holes": they're spans referring to ints on the stack. You can cause just as much trouble providing a wrong length as you can returning them."

My bad, I should stop commenting on issues past midnight 😆
You're correct, the first two are just invalid references but not GC holes. The parameter should be some object for that, ie:

```csharp
// Accidental GC hole
static Span<string> Foo(string x)
{
    return MemoryMarshal.CreateSpan(ref x, 1);
}

// Accidental GC hole #2
static Span<string> Bar()
{
    // Assuming this will be valid in C# (or whenever)
    Span<string> foo = stackalloc string[10];
    
    ref string value = ref foo[0];
    
    return MemoryMarshal.CreateSpan(ref value, 1);
}
```

In this case that stack location being pointed at by the reference inside the span could get overwritten with all sorts of garbage oncee the method returns, but the GC will keep exploring it as that'll be a root, and all sorts of weird crashes and hard to track data corruptions may happen. This to me seems much worse than ie. just reading invalid data or a "classic" access violation if you happen to read out of bounds into an invalid memory area.

I also want to add, this API would be identical to the _existing_ `new Span<T>(void* p, int length)` API we have. And yes, "that API takes a pointer so it's assumed to be unsafe", but just like that, the proposed one has "Unsafe" in the name, so I don't see how the two are fundamentally different. In both cases they would allow for arbitrary lengths. The proposed `CreateUnsafe` would just make the behavior consistent in that the main source of unsafety is in fact the length, and not with _additional_ footguns like allowing developers to accidentally escape values outside of their valid scope. For the same reason (they're similar and consistent, just one for raw pointers and one for GC refs), it makes sense to me that they're in the same class, without forcing developers to both go down to `MemoryMarshal` to create a span, as well as also getting the "bonus" of additional unsafety when there's absolutely no reason to.

Just to make an example, I found myself using `MemoryMarshal.CreateSpan` dozens and dozens of times, and once we get C# 11 with scoped annotations, there is not a _single_ case where I'd want to keep using that API and have the compiler not double check that I'm not accidentally escaping things, because I've never once used it in place where I would've conceptually wanted an input valaue/ref to actually trick the caller and escape. I'd happily replace each and every one of those uses for `CreateUnsafe` and get extra safety, with no downsides. I think the same should apply to virtually all `CreateSpan` uses out there in the wild 🙂

**Comment by stephentoub** [comment]
> so I don't see how the two are fundamentally different

Because WE ALREADY HAVE IT. It's called MemoryMarshal.CreateSpan. It'd be like you proposing adding a differently named pointer-based method that is the same implementation as the existing one. We're not going to do that, and we shouldn't add the proposed duplicate either.

> I'd happily replace each and every one of those uses for CreateUnsafe and get extra safety, with no downsides. I think the same should apply to virtually all CreateSpan uses out there in the wild

This is not an argument for adding the proposed method; it is an argument for not changing the existing CreateSpan at all such that when the new C# 11 rules arrive, it's already exactly what you want. And as I've already stated, as long as doing so doesn't cause a significant amount of unexpected pain, I'm fine with that. That is the option (c) which I already stated might be the best option (and which Tanner stated he thinks is the worst). Pursuing that option is the natural course of evolution of the C# changes, and doesn't require an issue to track, since if which nothing, it's what's we'll get. In addition, and related but separate, as an escape hatch we'll want to add 'scoped' to Unsafe.AsRef's argument so that the method casts away not just readonly but also the scoping, and then is CreateSpan stays as is, AsRef can be used with it to restore it to its previous untracked semantics.

**Comment by jkotas** [comment]
> In this case that stack location being pointed at by the reference inside the span could get overwritten with all sorts of garbage once the method returns

The examples that you have shared are first and foremost use after free or stack buffer overrun security bugs. Yes, bugs like this can cause all sorts of crashed, including crashes inside GC.

> I'd happily replace each and every one of those uses for CreateUnsafe and get extra safety, with no downsides. 

It would be even better if you can stop using unsafe code completely in all those places.

When it comes to APIs that enable writing unsafe code, I think we only need to add minimum that gives you full power and makes it possible to do what is necessary. It you see a lot of value in variants with reduced powers or that combine the basic building blocks, you can always add them as helper methods in your project.

**Comment by jaredpar** [comment]
> I do not think we should do option (B). I'm fine with (A). Whether (C) is the best option remains to be seen based on hands-on experience when we actually get a compiler that implements the functionality, on how painful the break actually is in practice.

For me I just don't feel any urgency to introduce `Span<T> Span<T>.CreateUnsafe(ref T value, int length)` in .NET 7. The side benefit of `ref` fields is that customers are no longer dependent on dotnet/runtime for providing APIs like this. Any customer can define an API that has the exact same semantics and use it in their code. That means doing nothing is not blocking anyone who believes this API is worthwhile (which has not been the case in the past with `ref` field style APIs). 

Once the primitive APIs of `Span(ref T value)`, `MemoryMarshal.CreateSpan`, `Unsafe.AsRef` (which strips scoping) are in place customers have every tool necessary in their toolbox to build what they desire. Hence for me there is no urgency to add this now particularly with the lack of agreement on whether it's a good API. Customers can build this themselves, demonstrate the value and it can be considered at a later date.

**Comment by stephentoub** [comment]
Closing, since we're not going to add this method now.

**Comment by stephentoub** [comment]
>  I don't think its fine to say we already have it or that the proposed API is the same.

We do have it. At run time they are 100% identical, and both enable utter corruption of the process. At compile time they are both unsafe. The only difference is whether some additional compile-time analysis is available from the compiler because one has an extra attribute. 

Adding the exact same shape of an API just attributed to trigger that analysis doesn't take away the existing overload. Nothing prevents the existing one from being used, on purpose or accidentally, at which point any additional (real or imagined) safety evaporates. And having two that literally do the exact same thing at execution time, that are both marked as unsafe, is very confusing.

I'm done with the discussion. I don't appreciate the insinuation that I'm somehow not being sincere.

**Comment by tannergooding** [comment]
>  And having two that literally do the exact same thing at execution time, that are both marked as unsafe, is very confusing.

That wasn't the proposal. The proposal very clearly called out:
> These two APIs will also validate that the length is in the allowed range, just like the void* span constructors

They have similar and related, but differing functionality, different safety (in multiple ways), and yes different compile time analysis. Compile time analysis is an incredibly useful feature and is used by many languages, libraries, and even the BCL to help ensure correctness and catch bugs.

Unsafe code is a core part of many libraries to achieve perf goals and design requirements. Being able to provide additional safety on top, to me (and to many others), is always worthwhile.

**Comment by tannergooding** [comment]
I also didn't mean to insinuate that you weren't being sincere and I apologize if it came across that way.

I'm merely trying to explain my own (and what I assume are others) perspectives on how this differs and why we don't understand the statement of "we already have this".

**Comment by Sergio0694** [comment]
I agree with what Tanner said above on the API differences and reasons to support this proposal, so nothing to add there.

I do however want to say that of course also on my end, in case anything I said came across the wrong way, I'm sorry. I never thought nor meant to imply Stephen (or anyone) was being insincere, just sharing a different opinion on the issue, is all.

**Comment by AraHaan** [comment]
As much as I love MemoryMarshal.CreateSpan, it's validations are horrible at most and is a source of bugs, meanwhile the proposed api could have reduced those bugs significantly (even if the BCL cant make use of it yet or does not see such a bug being an issue yet does not mean it's not there and hiding from us as after all we are only human and won't know until it happens at runtime). Besides even if it's not of value in the BCL does not mean it's not of value for 100% of non-BCL code like TerraFX, or any other codebases.

**Comment by jaredpar** [comment]
> As much as I love MemoryMarshal.CreateSpan, it's validations are horrible at most and is a source of bugs,

This is true of every API in `Unsafe` or `MemoryMarshal`. The types and their members are explicitly listed as unsafe and can cause corruption bugs. These APIs should be approached with caution and a higher degree of inspection.

> Besides even if it's not of value in the BCL does not mean it's not of value for 100% of non-BCL code like TerraFX, or any other codebases.

Any code base can write the API being proposed here. It is not complicated either, it's cut and paste the following code:

```c#
Span<T> CreateSpan<T>(ref T value, int length) => MemoryMarshal.CreateSpan(ref value, length);
```

It's a single line of code that any repo can author and get the desired behavior. Customers who find this valuable can use this pattern as much as they desire. They can also use analyzers like banned API to remove `MemoryMarshal.CreateSpan` from their code base if desired. 

In the past there was definitely a need to push dotnet/runtime for certain APIs. After all so much logic was tied into `ByReference<T>` that some APIs could only be implemented here. That is not true once we have `ref` fields. Every repo will be on the same footing (save for the ability to convert a `stackalloc` directly to your type).
