### ISSUE TITLE
TimeZoneInfo doesn`t support Europeans identifiers (EET CET WET)

### ISSUE THREAD

**Issue by Kateryna-Shtets** [dotnet/runtime#67296]
### Describe the bug
TimeZoneInfo cstZone = TimeZoneInfo.FindSystemTimeZoneById("EET"); // CET and WET throw the same exception.

### Exception
Unhandled exception. System.TimeZoneNotFoundException: The time zone ID 'EET' was not found on the local computer.

### Additional Info
TargetFramework: net6.0

The issue even doesn't work on OS Name Microsoft Windows 10 Pro (Version 10.0.19043 Build 19043)

The issue is also reproducible using the container mcr.microsoft.com/dotnet/aspnet:6.0.
According to IANA timezones identifiers (https://nodatime.org/TimeZones and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)  EET, CET, WET are valid IANA identifiers, so the method  **TimeZoneInfo.FindSystemTimeZoneById** should work.

Also all other timezone ids from the list above work correctly.

**Comment by tannergooding** [comment]
@tarekgh, does TimeZoneInfo fall under the things you generally look at?

**Comment by tarekgh** [comment]
> does TimeZoneInfo fall under the things you generally look at?

Yes.

**Comment by tarekgh** [comment]
These time zones cannot currently be supported on Windows. The reason is there is no specific Windows time zone Id match such time zones. In other words, Windows doesn't carry zone data for such time zones. Even using such time zones on Linux will not be desirable, the reason is some countries using such time zones while the daylight savings are not applying to them. 
For example, according to https://www.timeanddate.com/time/zones/eet `EET` is used by `Africa/Cairo` while Egypt not observing any daylight during the year but if you look at the `EET` rules data, it says it has daylight saving from March to October:

```
DateStart                  : 03/27/2022 00:00:00 (Unspecified)
DateEnd                    : 10/30/2022 00:00:00 (Unspecified)
DaylightDelta              : 01:00:00
DaylightTransitionStart    : M:3, D:27, W:1, DoW:Sunday, Time:01/01/0001 03:00:00, FixedDate:True
DaylightTransitionEnd      : M:10, D:30, W:1, DoW:Sunday, Time:01/01/0001 03:59:59, FixedDate:True
```

It is better to use a specific time zone Ids e.g. `Africa/Cairo` instead of this generic zones.
