### ISSUE TITLE
[H/3] stress not running

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#67442]
```
Trying connect to the server [https://server:5001/.](https://server:5001/)
client_1  | Stress client could not connect to host https://server:5001/, 10 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 9 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 8 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 7 attempts remaining
```

Also happened to me and @rzikm locally, now seen in the pipeline as well: https://dev.azure.com/dnceng/public/_build/results?buildId=1694516&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=1451f5f3-0108-5a08-5b92-e984b2a85bbd

Might be related to docker, docker compose or docker image update.

**Comment by CarnaViire** [comment]
In the log, there's also
```
server_1  | Starting Kestrel server.
server_1  | Unhandled exception. System.InvalidOperationException: This platform doesn't support QUIC or HTTP/3.
server_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
```
So it doesn't connect because the server did not start. @rzikm did you also have this exception on the server?

**Comment by ManickaP** [comment]
The server error is related to having nightly build of kestrel which has not yet consumed updated S.N.Quic and thus doesn't have the expected msquic version (1.9) in the docker. So after all the pipeline problem might be different from what we experienced.

Finally, it worked locally on my machine because I have msquic 1.9 a 2.x both side-by-side.

**Comment by rzikm** [comment]
> In the log, there's also
> ```
> server_1  | Starting Kestrel server.
> server_1  | Unhandled exception. System.InvalidOperationException: This platform doesn't support QUIC or HTTP/3.
> server_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
> ```
> So it doesn't connect because the server did not start. @rzikm did you also have this exception on the server?

I think I got this exact message

**Comment by ManickaP** [comment]
When I was testing this, the server didn't write anything, and it was before the update of msquic.

**Comment by rzikm** [comment]
To summarize why the H3 still did not run with ManickaP's changes: stress server listening on `https://+:5001" leads to us passing "IPAddress.IPv6Any" to MsQuic to listen to, and in that case, MsQuic does not accept connections using IPv4 address of the server.

This is different from the TCP `Socket` behavior and seemed like a bug in MsQuic, because the connections were closed with ALPN negotiation failure TLS alert (which confused me a lot until I debugged the MsQuic code). When I filed a bug with MsQuic team (https://github.com/microsoft/msquic/issues/2704), it turns out that this behavior is by design, and that if we want to accept connections from any IP, we should use the "unspecified" value of the address family when specifying the listening address. So if we special-case IPv6Any to use the unspecified AF then this should work again.
