### ISSUE TITLE
HttpClientHandler.SupportsAutomaticDecompression throws PlatformNotSupportedException on net6.0-maccatalyst

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/runtime#67529]
### Description

HttpClientHandler.SupportsAutomaticDecompression throws PlatformNotSupportedException on net6.0-maccatalyst

found here https://github.com/getsentry/sentry-dotnet/issues/1561

### Reproduction Steps

https://github.com/anpin/MauiHttphandlerRepro

### Expected behavior

returns false on net6.0-maccatalyst

### Actual behavior

PlatformNotSupportedException 

### Regression?

no

### Known Workarounds

none

**Comment by steveisok** [comment]
Appears that this is known issue in the xamarin-macios repo.  That's where NSUrlSessionHandler lives.

https://github.com/xamarin/xamarin-macios/issues/14632

From the looks of the issue above, there was a PR, but it will only apply to .NET 7.  Since there is an issue filed, I'm closing in favor of it.
