### ISSUE TITLE
Expand libraries testing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#67741]
Currently running a single test only (look for NativeAOT in src\libraries\tests.proj) because in runtimelab we saw some odd race conditions when building multiple test projects. I think I fixed it for .NET 7, but we would need to update the .NET used to build the repo to .NET 7 to pick up the fix and see if the race is gone.

- [ ] Make PR validation run at least the System.Runtime, System.Reflection, System.IO.Compression, System.IO.FileSystem, System.Linq.Expressions, System.Threading tests because there are pieces that are meaningfully different for NativeAOT. I might be missing some, but it's a start.
  * We might need to do baselining if any of the tests e.g. depend on Ref.Emit (need to tag them as such so that they don't run), or have single file assumption. Look at System.Reflection as an example: #67575.
- [ ] Add means to run all libraries tests in rolling builds, on all supported platforms.

**Comment by LakshanF** [comment]
It would be good to have the following _features_ in the library testing before this is closed

1. All relevant NetCoreApp library tests are enabled. There are currently around 167 such assemblies but some are not relevant (type forwarders etc.) but there are tests from this assembly list that are currently excluded. This is primarily due to the requirement to add rd.xml files for these projects.
2. Although not directly related to this issue, it would be good to get these libraries native aot compatible
3. The tests should run on all relevant platforms. Currently, linux runs are behind windows, primarily due to lagging gc support

**Comment by MichalStrehovsky** [comment]
We should also expand the RR testing to all configurations we support - Linux ARM64 is missing from the RR runs.

We should also make a call on how much testing we do for macOS x64 and Linux-MUSL-x64 and Linux-MUSL-arm64. They're not in the official support matrix, but we do produce packages for them. At minimum, I would like to see us not regressing them. Might be good to just have them in the RR runs.

It might be good to also add RR runs for Checked/Debug versions of the runtime (i.e. pass `-rc Checked` or `-rc Debug` to the build script). We don't need the full matrix for those. Checked Windows x64, Checked Linux arm64, Debug Windows arm64 might be sufficient.

**Comment by MichalStrehovsky** [comment]
All the libraries tests that make sense to run are running, on all supported platforms (except Bionic and iDevices but those are not fully brought up and the status is experimental).
