### ISSUE TITLE
System.Text.Json options throws an exception setting DefaultIgnoreCondition = Always

### ISSUE THREAD

**Issue by Jagbri** [dotnet/runtime#67740]
### Description

Exception creating new System.Text.Json.JsonSerializerOptions with DefaultIgnoreCondition = JsonIgnoreCondition.Always

### Reproduction Steps

`var options = new JsonSerializerOptions
{
    DefaultIgnoreCondition = JsonIgnoreCondition.Always
};
`

### Expected behavior

Get a new instance of configured JsonSerializerOptions

### Actual behavior

System.ArgumentException: The value cannot be 'JsonIgnoreCondition.Always'.
   at System.Text.Json.JsonSerializerOptions.set_DefaultIgnoreCondition(JsonIgnoreCondition value)

### Configuration

- .NET 6
- Windows 10
- x64

**Comment by krwq** [comment]
Assuming this worked, wouldn't that always produce `{}` on serialize and deserialize everything to null?

**Comment by Jagbri** [comment]
It should ignore properties with null or default values and not serialize them.

**Comment by eiriktsarpalis** [comment]
Tagging @layomia for context. I'm guessing this was added because specifying `Always` globally was deemed too destructive and is only meant for property-level configuration?

**Comment by layomia** [comment]
> It should ignore properties with null or default values and not serialize them.

That's what setting `JsonSerializerOptions.DefaultIgnoreCondition` to `JsonIgnoreCondition.WhenWritingDefault` does.

> Assuming this worked, wouldn't that always produce {}/null on serialize and deserialize everything to null/default?
>
> Tagging @layomia for context. I'm guessing this was added because specifying Always globally was deemed too destructive and is only meant for property-level configuration?

Exactly right. We consider this invalid configuration.

I believe the confusion here is that some folks interpret `DefaultIgnoreCondition` to mean "when should property default values be ignored?" rather than what we intend, "the property ignore condition as applied to default values". FWIW I initially proposed calling this "JsonSerializerOptions.IgnoreCondition", but that was deemed too generic.
