### ISSUE TITLE
The !name2ee command of SOS doesn't work in .Net 6

### ISSUE THREAD

**Issue by Li7ye** [dotnet/runtime#67791]
I use default Program.cs code in .Net 6 console app as below:

`Console.WriteLine("Hello, World!")`

I wan to use Windbg Preview to set breakpoint to main function.

1. I open Windbg Preview and select **Launch executable** to debug the console app.
2. I type `.load sos` and `sxe ld clrjit` command. After that, I type `g` command to init CLR load.
3. I type `.loadby sos coreclr` to load coreclr module. Then I try to use `!name2ee  xxx.exe xxx.Program.<Main>$`  or `!name2ee xxx.dll xxx.Program.<Main>$`to get 'Main' method address. However, Windbg doesn't display anything.
![Untitled](https://user-images.githubusercontent.com/42088918/162556746-21f1d14b-b512-446a-a311-766d29c13634.png)

**Comment by AaronRobinsonMSFT** [comment]
@Li7ye The steps above seem to indicate that the `DotCore.dll` isn't loaded yet. This means there is no mapping because the assembly hasn't been loaded yet. Instead, I would look at using the `bpmd` method to set a breakpoint - https://github.com/dotnet/diagnostics/blob/fb6cad70656827f6a5a3e82f7fa56f13dcc50c6b/src/SOS/Strike/strike.cpp#L8349-L8363.

**Comment by Li7ye** [comment]
@AaronRobinsonMSFT Thank you reply. `bpmd` command can solve my problem.
