### ISSUE TITLE
Parsing format string precision intends to validate for overflow but the check does not work

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#67891]
In https://github.com/dotnet/runtime/pull/47353 the way format strings are validated was changed. This resulted in this code:

https://github.com/dotnet/runtime/blob/5707668eac999163740e42c70f228772e6bc3680/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L1705-L1718

The `temp < 0` check does not catch all forms of overflow. It is possible to overflow but to create a positive value. Roughly, the argument goes like this: At about `n == int.MaxValue / 10` overflow starts to happen and it results in negative results. But then, the remaining value range is stepped through in increments of 10. This quickly leads to crossing into the positive numbers.

An example of this can be found with this code:

```csharp
public static void StandardFormatStringParsingOverflowRepro()
{
    for (int n = 0; n < int.MaxValue; n++)
    {
        var temp = n * 10;
        if (temp < n && temp >= 0)
        {
            Debugger.Break();
        }
    }
}
```

The first number is 429496730 (roughly `int.MaxValue * 2 / 10`) and `temp` becomes 4. This should work as a repro, although I have not tested it on the live code.

I also wonder how this code guards against characters being other than 0-9. Maybe that is being validated elsewhere.

**Comment by tannergooding** [comment]
@GSPP, you're missing that `n` is reassigned each iteration:
```csharp
int n = 0;
int i = 1;
while (i < format.[Length](https://source.dot.net/System.Private.CoreLib/ReadOnlySpan.cs.html#02997da01a69d282) && (((uint)format[[](https://source.dot.net/System.Private.CoreLib/ReadOnlySpan.cs.html#68805c618159e1e5)i] - '0') < 10))
{
    int temp = ((n * 10) + format[[](https://source.dot.net/System.Private.CoreLib/ReadOnlySpan.cs.html#68805c618159e1e5)i++] - '0');
    if (temp < n)
    {
        throw new FormatException(SR.Argument_BadFormatSpecifier);
    }
    n = temp;
}       
```

This isn't checking is it positive/negative but rather `is the new temp less than the previous temp`.

For `4294967300` it would:
* `n = 0`, `temp = 4`
* `n = 4`, `temp = 42`
* ...
* `n = 42949673`, `temp = 429496730`
* `n = 429496730`, `temp = 4`
* FormatException

**Comment by GSPP** [comment]
OK, let me see. It's definitely not possible to check the expression `n * 10` for overflow if you're just checking for a less-than result. Multiplication overflow can result in a value from the entire 32 bit range. It can be more or less, positive or negative. For 1 in 10 `x`, I can give you an `n` so that `n * 10 = x`, evenly spaced through the entire int32 range.

OK, what I was getting wrong was that you're not checking for a negative result (which I mistakenly did in my brute force loop). You're checking for the result to be less than the input. That's not sufficient, either, because there are `n` for which `n * 10 > n` and there's overflow. The times ten expands the range of possible outcomes to many times the total value range of an `int`. You can use `*10` to reach any part of the value range, positive, negative and bigger than the input.

Am I incorrect, that checking for a result less than the input cannot determine overflow of a `*10` operation? I cannot see how that would be a reliable check given that the whole `int` value range can be reached.

I'll try a different approach. I'll try to find a value that passes your check but that triggers the built-in overflow check:

```csharp
	for (int n = 0; n < int.MaxValue; n++)
	{
		var temp = n * 10;
		if (temp >= n) //The reverse of the condition in the live code
		{
			var _ = checked(n * 10); //This throws at n == 477218589
		}
	}
```

So it seems that `477218589 * 10` results in a greater-than outcome but triggers an overflow check. This means that the live code is not identifying an actual overflow.

I can reproduce it as follows. I copied out the `ParseFormatSpecifier` routine to a console app and ran it like this:

```csharp
    ParseFormatSpecifier("G4772185890", out var digits); //Results in 477218594
```

Notice, how the new repro input is bigger than the wrong one that I mistakenly submitted at first. This is because we need to step further through the 32 bit range to not just reach a positive overflow result, but also one that is bigger than `temp`.

**Comment by tannergooding** [comment]
Yeah, that looks to be a problematic case. We should really just limit this to like 214 million or so, because there is really no reason for it to be bigger

**Comment by GSPP** [comment]
My suggested fix would be to `checked` multiply, catch and convert to `FormatException`. The JIT should generate optimal code for that overflow check. Would the `try-catch` impose a performance cost? If no or negligible, this would be a performant and clean fix.

**Comment by tannergooding** [comment]
The additional cost of try-catch or `checked` may be more significant then desired for the "happy path".

Ideally this is limited to a much more trivial check where possible that continues to minimize the cost around processing the format string or only incurs the cost in the rare case (format string is more than 5 digits, etc).

**Comment by tannergooding** [comment]
It prevents a number of optimizations, makes the overall assembly nearly twice as large, and impacts the general inner loop performance negatively.

There is no real benefit to allowing formats this big and the actual case of overflow could be detected by `if (n >= 214748364)` at the top of the loop rather than being after the multiply.

This technically disallows `2147483640` through `2147483647` but that's a reasonable limitation. As would just limiting it to `9` digits (`999999999`) or other similar setups.

**Comment by dakersnar** [comment]
I've solved the bug but uncovered another. A precision of int.MaxValue overflows because of this increment.
![image](https://user-images.githubusercontent.com/18474647/180082950-ea4d19ca-d7c1-479b-9483-e447b3e4485b.png)

https://source.dot.net/#System.Private.CoreLib/Number.Formatting.cs,435

**Comment by tannergooding** [comment]
I think restricting it to something like `999_999_999` is more than reasonable for now.

Even if we expose `Quad-Precision IEEE 754 Floating-Point` we need no more than `11_563` significant digits and by then we start getting into values where computation itself will be problematic due to expense.

The most precise `BigInteger` would theoretically need up to `646_456_974` digits and that would take a very long time to parse/format and is likely an unreasonable amount for a "typical" user to request.
-- `BigInteger` has a limitation that the backing array length can be no more than `Array.MaxLength`, given we currently use `uint[]` as the backing storage, this is theoretically 8GB
-- However, we want the two's complement representation of a `BigInteger` to be representable in a `ROSpan<byte>` so we divide `Array.MaxLength` (currently `2_147_483_591`) by `4` giving us `536_870_897` bytes
-- However, we also want the length in bits to be representable as an `int` so that shifting continues to make sense and so we actually divide this by `2` (equivalent to `Array.MaxLength / 8`) giving us `268_435_448` bytes
-- This ends up being a single number represented by a 255 MB allocation (`268_435_448 bytes` == `262_143 kilobytes` == `255 megabytes`).
-- Since the algorithm for max digits is `ceil(log10(2^bits))` and we have `268_435_448 * 8` bits, this is `ceil(log10(2^2_147_483_584))` which is `646_456_974` digits
