### ISSUE TITLE
Why does Reflection lie?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/runtime#68026]
```C#
using System;
using System.Reflection;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        var methodd1 = typeof(Task<string>).GetMethod("ContinueWith", new Type[] { typeof(Action<Task<string>>) });
        Show(methodd1); // True

        var method2 = typeof(MyTask<string>).GetMethod("ContinueWith", new Type[] { typeof(Action<Task<string>>) });
        Show(method2); // False

        Console.ReadKey();
    }

    static void Show(MethodInfo method)
    {
        var origMethod = method.Module.ResolveMethod(method.MetadataToken);
        var type = origMethod.GetParameters()[0].ParameterType.GenericTypeArguments[0];
        Console.WriteLine(type.IsGenericTypeDefinition);
    }
}

class MyTask<T>
{
    public void ContinueWith(Action<Task<T>> continuationAction) { }
}
```

Why `True` for `Task.ContinueWith` but `False` for `MyTask.ContinueWith`

**Comment by huoyaoyuan** [comment]
I believe it's some metadata difference between referencing self and other types. Changing the parameter to `Action<MyTask<T>>` gets true, and `Action<MyOtherClass<T>>` gets false.

**Comment by Frassle** [comment]
Task<T> in the MyTask.ContinueWith method is not a generic type definition, it's a generic instantiation of Task with the type argument given by the type parameter of MyTask.

Task<T> in the Task.ContinueWith method _is_ a generic type definition because it's a method that is part of defining that generic type.

**Comment by steveharter** [comment]
Without referencing specs, I would say this is sort of an implementation detail due to usage of `MetadataToken` being used to obtain the original method, which perhaps could be considered either an open or closed generic depending on the implementation. 

If the raw `MethodInfo` that is passed in is used instead of looking up the `MethodInfo` from the token then the results are the same.

Also was the intent to use one of the other properties like `ContainsGenericParameters` instead? Changing the `WriteLine` to
```cs
Console.WriteLine($"type:{type}\n" +
    $"IsGenericTypeDefinition:{type.IsGenericTypeDefinition}\n" +
    $"IsConstructedGenericType:{type.IsConstructedGenericType}\n" +
    $"IsGenericMethodParameter:{type.IsGenericMethodParameter}\n" +
    $"ContainsGenericParameters:{type.ContainsGenericParameters}\n" +
    $"IsGenericTypeParameter:{type.IsGenericTypeParameter}\n");
```
results in
```
type:System.Threading.Tasks.Task`1[TResult]
IsGenericTypeDefinition:True
IsConstructedGenericType:False
IsGenericMethodParameter:False
ContainsGenericParameters:True
IsGenericTypeParameter:False

type:System.Threading.Tasks.Task`1[T]
IsGenericTypeDefinition:False
IsConstructedGenericType:True
IsGenericMethodParameter:False
ContainsGenericParameters:True
IsGenericTypeParameter:False
```

**Comment by Frassle** [comment]
> I would say this is sort of an implementation detail due to usage of MetadataToken being used to obtain the original method, which perhaps could be considered either an open or closed generic depending on the implementation.

I believe metadata tokens always refer to the open method. Which is why there is an overload of [ResolveMethod](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.module.resolvemethod?view=net-6.0#system-reflection-module-resolvemethod(system-int32-system-type()-system-type())) that takes the generic context to construct the closed method with.

**Comment by CreateAndInject** [comment]
> Task in the MyTask.ContinueWith method is not a generic type definition, it's a generic instantiation of Task with the type argument given by the type parameter of MyTask.
> 
> Task in the Task.ContinueWith method _is_ a generic type definition because it's a method that is part of defining that generic type.

Seems it's my mistake...
