### ISSUE TITLE
[7.0.100-preview.4.22212.1] File.AppendAllTextAsync/WriteAllTextAsync doesn't throw System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#68073]
### Description

When launch 3rd party Kebler to create log, it fails.  With runtime .NET 5/6, it will show the exception details and help user locate the issue details. With Runtime .NET 7, nothing information display.

### Reproduction Steps

1) Create .net7 Console app
2) Add this code :
```
 File.AppendAllTextAsync(@"C:\Users\v-altunc\Documents\TestFolder\test.txt", "Testing");   //this directory does not exists
```
Note : TestFolder directory does not exist
3) Build and run the app

### Expected behavior

 System.IO.DirectoryNotFoundException

### Actual behavior

No exception

### Regression?

Verify Scenarios:

1). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.4.22212.1: Fail
2). Windows10 RS5 x64+7.0.100-preview.2.22156.6: Fail
3). Windows10 RS5 x64+dotnet-sdk- 6.0.201 Pass
4). Windows10 RS5 x64+dotnet-sdk- 5.0.407: Pass

### Configuration

**Application Name**: Kebler
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number:** dotnet-sdk-7.0.100-preview.2.22114.1

### Other information

@dotnet-actwx-bot @dotnet/compat

**Comment by Jozkee** [comment]
You need to `await` to get the exception. This was changed in #58167, before that OpenHandle was called on the sync part of the method and now it is called in the async part. I don't think this counts as a regression.

**Comment by stephentoub** [comment]
> You need to await to get the exception.

More generally, not awaiting it is a bug, since you have no idea if/when it completes until the task returned from the method completes.  If for example the program were to exit immediately after making this call, without the await, it's likely the file would never be written or only partially be written.

> I don't think this counts as a regression.

It's a bug fix.  Only usage exceptions (e.g. ArgumentNullException for an erroneously null argument) should be thrown synchronously out of an asynchronous method.  Everything else should be stored into the returned task:
https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap?msclkid=a711af27bcf511ec9a495ba8802ab269#exceptions
If previously this was throwing DirectoryNotFoundException synchronously out of the asynchronous method call, that was a bug.

**Comment by Jozkee** [comment]
@stephentoub at least we should document this as a breaking change?
https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-changes.md#bucket-2-reasonable-grey-area
> Bucket 2: Reasonable Grey Area
> * An exception is no longer thrown

**Comment by stephentoub** [comment]
It's still thrown, right? Just effectively and correctly thrown asynchronously rather than synchronously?  I don't believe this needs to be documented as a breaking change.  It's a small bug fix, and the difference is imperceivable if the call is await'd correctly.

**Comment by Jozkee** [comment]
> It's still thrown, right? Just effectively and correctly thrown asynchronously rather than synchronously?

Yes.

**Comment by danmoseley** [comment]
@Junjun-zhao could you either please update that line in the app to put "await" in front of it, or consider this to be expected behavior from this point onwards.

**Comment by danmoseley** [comment]
Aside, as discussed with folks above -- when I tried this in a test app, I was expecting to get " CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call."

I didn't, and that's because I was pasting into the default top-level-statements style template, and in those whether main is async is inferred [from the presence of the await keyword](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#implicit-entry-point-method). So ironically the warning intended to warn about the missing await keyword was disabled because the await keyword was missing. In theory the heuristic perhaps could extend to looking for any calls to methods returning Task in which the return result was neither used nor discarded.
