### ISSUE TITLE
Consider moving `IFloatingPointIeee754<T>.MaxNumber` down to `INumber<T>`

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#68191]
From https://github.com/dotnet/runtime/pull/68183#discussion_r852458171:

> We have IFloatingPointIeee754<T>.MaxNumber which does propagate the number instead, so maybe it'd be worth moving it down to INumber<T> so devs can do the right thing here...
>
> I'd suspect the NaN pre-loop probably isn't that useful in practice as I'd expect NaNs are actually decently rare; which would allow the impls to then be the same.

**Comment by stephentoub** [comment]
Alternatively, might we consider moving IsNaN down? Presumably it could just return false for any type that lacks the concept.

**Comment by tannergooding** [comment]
My existing plan, to bring to the next API review, is that we need to move a few key functions down that logically "make sense" for all number types which includes things like `MaxNumber`, `MaxNumberMagnitude`, and `IsNaN`.

If we had the ability to do something like the following, then this wouldn't matter and you could relegate concepts like `IsNaN` or `MaxNumber` only to "float"
```csharp
if (T is IFloatingPointIeee754<T>) // or relevant check/syntax
{
    T.MaxNumber(x, y);
}
```

However, since that doesn't exist you run into interesting scenarios where even with `Max` and `MaxMagnitude` you need to understand the concept of `NaN` if it ever needed to be implemented as a DIM.

APIs which just query information about a value (like `IsNaN` which returns `bool`) and APIs which don't create new values but merely return one of the two inputs (like `MaxNumber`) then can easily be implemented by integer or other types in that they'll return a constant `false` or defer to `Max`, etc.

Other APIs don't make sense to move down because there isn't an easy way to define behavior for them. For example, `RotateLeft` and `shift operators` don't make sense in any capacity for floating-point. While `Sqrt` and `Exp` have behavior which can only be questionably defined for integer types (at best you define it as `floor(op(value))`, which removes a lot of usability and adds impl expense; the limited range of integer types makes things like `Pow` super limited as well, given there are only a small extremely specific set of valid inputs)

**Comment by tannergooding** [comment]
This was reviewed, approved, and completed.
