### ISSUE TITLE
[API Proposal]: `IBinaryInteger<TSelf>.ReverseEndianess`.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#68227]
### Background and motivation

Since the generic math interface `IBinaryInteger<TSelf>` already has the concept of endianess through the `(Try)WriteLittleEndian` methods, perhaps it would be valuable to expose a method that would reverse the number's endianess.

### API Proposal

```C#
namespace System.Numerics
{
    public interface IBinaryInteger<TSelf>
    {
        TSelf ReverseEndianess();
    }
}
```

### API Usage

The generic `ReverseEndianess` could be used to write this:

```C#
public struct LittleEndian<T> : where T: unmanaged, IBinaryInteger<T>
{
    private T _value;
    public T Value
    {
        readonly get
        {
            T value = Unsafe.ReadUnaligned<T>(ref Unsafe.As<T, byte>(ref _value));
            if (!BitConverter.IsLittleEndian)
                value = value.ReverseEndianess();
            return value;
        }
        set
        {
            if (!BitConverter.IsLittleEndian)
                value = value.ReverseEndianess();
            Unsafe.WriteUnaligned<T>(ref Unsafe.As<T, byte>(ref _value), value);
        }
    }
    public LittleEndian(T value) => Value = value;
}
```

Which could be used to write clean endian-aware code that interops with binary files:

``` csharp
byte* data = GetPointerFromMemoryMappedFile("myfile.bin");

var header = (FileHeader*)data;
if (header.Magic.Value != 0xB8B8B8B8B8B8B8B8)
    throw new NotSupportedException();
// ...

[StructLayout(LayoutKind.Sequential)]
struct FileHeader
{
    public LittleEndian<ulong> Magic;
    public LittleEndian<int> Field1;
    public LittleEndian<short> Field2;
}
```

I might need to do it in my code one day. But even if not approved, specific types like `LittleEndianInt32` will work fine (I will have to write them either way to support earlier frameworks).

**Comment by Clockwork-Muse** [comment]
As a point of personal preference, I vastly prefer being explicit about the endianness of my source and destination values; in that sense I find `ReverseEndianess` to be suspect, because reversing endianness isn't a useful thing to do (as opposed to converting to a specific one - so something like `ToLittleEndian`).  Semantics, I know.

**Comment by teo-tsirpanis** [comment]
`ReverseEndianess` can be used to implement `ToLittleEndian` and `ToBigEndian`, and has the advantage of being the only platform-ignorant of the three.

**Comment by saucecontrol** [comment]
I would find this useful.  Consider writing a parser for a document that can be either endian.  Rather than explicitly matching platform endianness with document endianness on every read, or forking into separate readers for each endianness, you could simply check once "does document endianness match platform?" and save a flag.  Then every read is endian-agnostic and followed by a conditional `ReverseEndianness`.

**Comment by tannergooding** [comment]
Adopted into https://github.com/dotnet/designs/pull/262 which will be reviewed on Tuesday May 10th
