### ISSUE TITLE
LongContinuationChain_Unwrap_DoesNotStackOverflow long running test

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#68290]
Configuration: `net7.0-OSX-Release-x64-CoreCLR_release-OSX.1200.Amd64.Open`

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1721549

```
  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Tests (found 580 of 760 test cases)
  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 6)
    System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_DebuggerAttached_ReturnsAllSchedulers [SKIP]
      Condition(s) not met: "DebuggerIsAttached"
    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
      Condition(s) not met: "DebuggerIsAttached"
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:02:01
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:04:02
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:06:03
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:08:04
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:10:05
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:12:06
   System.Threading.Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:14:06
['System.Threading.Tasks.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by danmoseley** [comment]
In the last 30 days, these are the tests causing System.Threading.Tasks.Tests to time out:
```
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Await_DoesNotStackOverflow', Elapsed: 00:14:07
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Await_DoesNotStackOverflow', Elapsed: 00:14:13
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Await_DoesNotStackOverflow', Elapsed: 00:14:14
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:14:06
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:14:06
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:14:09
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:14:13
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_Unwrap_DoesNotStackOverflow', Elapsed: 00:14:18
Tasks.Tests: [Long Running Test] 'System.Threading.Tasks.Tests.UnwrapTests.RunStackGuardTests', Elapsed: 00:14:11
```
It is not specific to flavor, not specific to runtime. It only happens on osx.1200.amd64.open in the last 30 days and all but 2 cases since the start of the year were osx.1200.amd64.open.

```kusto
WorkItems
| where FriendlyName == "System.Threading.Tasks.Tests"
| where  Queued > ago(30d)
| where Status == "Timeout"
//| where QueueName endswith "armarch.open"
| join Jobs on JobId
| project
  Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  RuntimeFlavor = tostring(parse_json(Properties).runtimeFlavor),
  BuildId = tostring(parse_json(Properties).BuildId),
  QueueName, Source
```

|Queued|FriendlyName|ExitCode|Status|ConsoleUri|PhaseName|Pipeline|RuntimeFlavor|BuildId|QueueName|Source|
|---|---|---|---|---|---|---|---|---|---|---|
|2022-03-30 21:50:20.0010000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67011-merge-e66f0881c6024b53b8/System.Threading.Tasks.Tests/1/console.0165ae63.log?sv=2019-07-07&se=2022-04-19T21%3A50%3A18Z&sr=c&sp=rl&sig=ihL7YUDPbrVjdlBdD7dvDMurh4gIFgdydwdFLL7MpGY%3D|libraries_test_run_release_mono_OSX_x64_Debug|runtime|mono|1688386|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/67011/merge|
|2022-04-05 00:34:29.8250000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67184-merge-097f2ec10da04638bf/System.Threading.Tasks.Tests/1/console.17bf2842.log?sv=2019-07-07&se=2022-04-25T00%3A34%3A28Z&sr=c&sp=rl&sig=b1ic646sVWPryH7d41%2B1C9WgFJz0HZg3jRv5bh7t5uw%3D|libraries_test_run_release_mono_OSX_x64_Debug|runtime|mono|1699503|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/67184/merge|
|2022-04-05 06:12:18.2250000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67436-merge-a8d7f6be94224204b3/System.Threading.Tasks.Tests/1/console.ba2b4efd.log?sv=2019-07-07&se=2022-04-25T06%3A12%3A15Z&sr=c&sp=rl&sig=2BfxGmxpyPwXDnDxT8WxO4GsqefZvkqLMhNGJll4xA0%3D|libraries_test_run_release_coreclr_OSX_x64_Debug|runtime|coreclr|1699929|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/67436/merge|
|2022-04-06 16:53:26.7230000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61776-merge-562aa88902154c7e80/System.Threading.Tasks.Tests/1/console.a4d650f2.log?sv=2019-07-07&se=2022-04-26T16%3A53%3A25Z&sr=c&sp=rl&sig=CvLSiVEobFV%2BmMFodf2ijEC%2BL4yGTea5rjEFeH64I%2F4%3D|libraries_test_run_release_mono_OSX_x64_Debug|runtime|mono|1703112|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/61776/merge|
|2022-04-07 17:38:54.6910000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67709-merge-2ca8accabef348509b/System.Threading.Tasks.Tests/1/console.6e44b24a.log?sv=2019-07-07&se=2022-04-27T17%3A38%3A53Z&sr=c&sp=rl&sig=kV5dYsPZB1Fb3vpkD%2FxbhO7s9bsWWDspynE9OhR%2B3hA%3D|libraries_test_run_release_mono_OSX_x64_Debug|runtime|mono|1705318|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/67709/merge|
|2022-04-08 08:45:55.4460000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b408bbbde24a428398/System.Threading.Tasks.Tests/1/console.ce6e8a07.log?sv=2019-07-07&se=2022-04-28T08%3A45%3A54Z&sr=c&sp=rl&sig=xOISizxlmmMU9Xc3OyExIt7RDpOLvPEjEKcRU3fDAvs%3D|libraries_test_run_release_mono_OSX_x64_Release|runtime|mono|1706886|osx.1200.amd64.open|ci/public/dotnet/runtime/refs/heads/main|
|2022-04-09 08:20:53.8320000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67636-merge-4a21aa6b1d3447e48f/System.Threading.Tasks.Tests/1/console.746ca97d.log?sv=2019-07-07&se=2022-04-29T08%3A20%3A52Z&sr=c&sp=rl&sig=Y7CS7enYME5o8LKaPQP4wW6zUsBuMTbpjOfTgsafB5w%3D|libraries_test_run_release_mono_OSX_x64_Debug|runtime|mono|1708681|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/67636/merge|
|2022-04-14 17:58:21.6960000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67998-merge-0c64efe2b14b4116b7/System.Threading.Tasks.Tests/1/console.523fff4b.log?sv=2019-07-07&se=2022-05-04T17%3A58%3A20Z&sr=c&sp=rl&sig=x6%2FiLsooB0efoSUjYNiwxlb89%2FiyYd0rIaFNHOkr1BY%3D|libraries_test_run_release_coreclr_OSX_x64_Debug|runtime|coreclr|1718233|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/67998/merge|
|2022-04-15 03:02:29.5040000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61776-merge-9a516aaacca645bd82/System.Threading.Tasks.Tests/1/console.caa92278.log?sv=2019-07-07&se=2022-05-05T03%3A02%3A28Z&sr=c&sp=rl&sig=7EnX9F579UqZD49fKDlfS2qP3sCvEqh5UxILNlOWFoI%3D|libraries_test_run_release_coreclr_OSX_x64_Debug|runtime|coreclr|1719229|osx.1200.amd64.open|pr/public/dotnet/runtime/refs/pull/61776/merge|
|2022-04-16 08:51:38.4690000|System.Threading.Tasks.Tests|-3|Timeout|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4075992d15f842a09d/System.Threading.Tasks.Tests/1/console.281c44fc.log?sv=2019-07-07&se=2022-05-06T08%3A51%3A37Z&sr=c&sp=rl&sig=4bRScJO4OtDb4UJZTmPYsumALk9dnoXmXwNwH2skHZY%3D|libraries_test_run_release_coreclr_OSX_x64_Release|runtime|coreclr|1721549|osx.1200.amd64.open|ci/public/dotnet/runtime/refs/heads/main|

**Comment by danmoseley** [comment]
Digging deeper, this is has never passed on macOS 12.  Another macOS 12 issue. @ViktorHofer do you have a mac?  We need to know whether it hangs for you, and if so, whether reducing [this](https://github.com/dotnet/runtime/blob/0e6d607015bbf9b42c8914873071fecbd6dfacf0/src/libraries/System.Threading.Tasks/tests/Task/TaskContinueWithTests.cs#L1244) value makes it pass, or it just hangs period.


```kusto
WorkItems
| where FriendlyName == "System.Threading.Tasks.Tests"
//| where  Queued > ago(30d)
//| where Status == "Timeout"
//| where QueueName endswith "armarch.open"
| join Jobs on JobId 
| extend Elapsed = (Finished-  Started)
| where Elapsed > make_timespan(0, 0, 10, 0)
| where QueueName contains "osx"
| project Elapsed,
  Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  RuntimeFlavor = tostring(parse_json(Properties).runtimeFlavor),
  BuildId = tostring(parse_json(Properties).BuildId),
  QueueName, Source, Started
  | summarize count() by bin(Elapsed, 1m), bin(Started, 1d), QueueName, Status//, Pipeline
```

|Elapsed|Started|QueueName|Status|count_|
|---|---|---|---|---|
|00:10:00|2022-02-22 00:00:00.0000000|osx.1015.amd64.appletv.open|Pass|2|
|00:10:00|2022-03-09 00:00:00.0000000|osx.1015.amd64.appletv.open|Pass|1|
|00:15:00|2022-03-08 00:00:00.0000000|osx.1200.amd64.open|Timeout|2|
|00:15:00|2022-03-15 00:00:00.0000000|osx.1200.amd64.open|Timeout|2|
|00:15:00|2022-03-22 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-03-30 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-05 00:00:00.0000000|osx.1200.amd64.open|Timeout|2|
|00:15:00|2022-04-06 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-07 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-08 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-09 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-14 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-15 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|
|00:15:00|2022-04-16 00:00:00.0000000|osx.1200.amd64.open|Timeout|1|

**Comment by ViktorHofer** [comment]
@danmoseley nope, only Windows.

**Comment by danmoseley** [comment]
@wfurt you have a Mac - I assume with macOS 12? do you have a minute to run this test and see whether it hangs?

**Comment by wfurt** [comment]
I can take a look. I still run 11.6 on my main machine but I have VM and possibly few other options.

**Comment by danmoseley** [comment]
Did you get a chance to try it @wfurt?

**Comment by wfurt** [comment]
I had the test set run in loop over night on my 12.3.1 and I did see a single failure. While the queue is 1200 do we still run true 12.0 or is it 12.x current like my system? If anything, I would expect the difference may be in HW more so then exact OS version.

I know it is possible to work with core-eng and get machine out of the pool for investigations.  
Alternatively, we can (should?) collect core file on cases like this. At least on Unix this should be pretty easy and it would help use solve this and other mysteries.

**Comment by danmoseley** [comment]
@dotnet/dnceng can you answer @wfurt  question about macOS version?

**Comment by MattGal** [comment]
> @dotnet/dnceng can you answer @wfurt question about macOS version?

Helix machines in `osx.1200.amd64.open` are currently 12.3.1 (yes poor queue naming choice...), but do note that since these are physical-only machines it's always possible for a vendor to fail to update a particular machine, so if you want to ask about a specific machine we can be more specific.

**Comment by ilyas1974** [comment]
We are currently in the process of updating the systems in our environment (https://portal.microsofticm.com/imp/v3/incidents/details/309794356/home). Once the updates are complete, I will be updating our inventory information with the latest updates.

**Comment by danmoseley** [comment]
Thanks chaps. It does not appear machine specific --


```kusto
WorkItems
| where FriendlyName == "System.Threading.Tasks.Tests"
//| where  Queued > ago(30d)
//| where Status == "Timeout"
//| where QueueName endswith "armarch.open"
| join Jobs on JobId 
| extend Elapsed = (Finished-  Started)
| where Elapsed > make_timespan(0, 0, 10, 0)
| where QueueName startswith "osx"
| project Elapsed,
  Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  RuntimeFlavor = tostring(parse_json(Properties).runtimeFlavor),
  BuildId = tostring(parse_json(Properties).BuildId),
  QueueName, Source, Started, MachineName
  | summarize count() by QueueName, Status, MachineName // bin(Started, 1d), bin(Elapsed, 1m),
```

|QueueName|Status|MachineName|count_|
|---|---|---|---|
|osx.1015.amd64.open|BadExit|DCI-MAC-BUILD-037|1|
|osx.1015.amd64.open|BadExit|dci-mac-build-136|1|
|osx.1015.amd64.appletv.open|Error|DNCENGMAC038.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC024.local|2|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC058.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC037.local|2|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC006.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC018.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC035.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC030.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC034.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC043.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC003.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC017.local|3|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC014.local|2|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC027.local|2|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC039.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC041.local|1|
|osx.1200.amd64.open|Pass|dci-mac-build-377.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC005.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC004.local|3|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC007.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC028.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC013.local|1|
|osx.1015.amd64.appletv.open|Pass|DNCENGMAC038.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-311.local|2|
|osx.1200.amd64.open|Timeout|dci-mac-build-364.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-309.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-327.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-367.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-386.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-392.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-391.local|2|
|osx.1200.amd64.open|Timeout|dci-mac-build-307.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-314.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-340.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-390.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-333.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-351.local|1|
|osx.1200.amd64.open|Timeout|dci-mac-build-313.local|1|

**Comment by danmoseley** [comment]
Not sure whether this reflects progressively being updated --


```kusto
WorkItems
| where FriendlyName == "System.Threading.Tasks.Tests"
| where  Queued > ago(30d)
| where Status == "Timeout"
//| where QueueName endswith "armarch.open"
| join Jobs on JobId 
| extend Elapsed = (Finished-  Started)
//| extend Slow = Elapsed > make_timespan(0, 0, 10, 0)
| where QueueName startswith "osx"
| project Elapsed//, Slow,
  ,Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  RuntimeFlavor = tostring(parse_json(Properties).runtimeFlavor),
  BuildId = tostring(parse_json(Properties).BuildId),
  QueueName, Source, Started, MachineName
  | summarize count() by QueueName, MachineName // bin(Started, 1d), bin(Elapsed, 1m),
```

|QueueName|MachineName|count_|
|---|---|---|
|osx.1200.amd64.open|dci-mac-build-311.local|1|
|osx.1200.amd64.open|dci-mac-build-364.local|1|
|osx.1200.amd64.open|dci-mac-build-113|1|
|osx.1200.amd64.open|dci-mac-build-366.local|1|

@MattGal I wonder whether "exact OS version" might be something worth logging, if not in Kusto then on the first line of the logs eg
`Console log: 'System.Threading.Tasks.Tests' from job a34da4b3-dd95-43eb-901e-14a411b48721 workitem dfba90d7-72ce-4640-943b-2bb9269c9bed (osx.1200.amd64.open) executed on machine dci-mac-build-364.local running 12.3.1` or something.

**Comment by MattGal** [comment]
@danmoseley that'd be fairly cheap to add; feel free to write an issue in dotnet/arcade asking for it and we'll get to it in triage.  

As for the "osx1200" machines they're all running 12.3.1 now and have been for some time, Apple just has a much faster versioning cadence these days and we should have probably learned this and named the queues "osx.12.arch..."

**Comment by danmoseley** [comment]
By the query above, this has not occurred for nearly a month. I'm going to assume it's the updates that fixed it.
