### ISSUE TITLE
ECMA-335 clarification about assignable-to relation

### ISSUE THREAD

**Issue by Itay2805** [dotnet/runtime#68403]
Reading the ECMA-335 6th edition, I stumbled upon the following rule (Top of page 39) in the assignable-to relation:

```
4.T has intermediate type native int and U has intermediate type int32, or vice-versa.
```

This seems to implicate that verification assumes `native int` is `int32`, which is of course incorrect on most modern platforms... I can understand `int32` -> `native int` assumption, but in this case it allows both...

Is there a reason for this rule being in place that I don't see? Or is this just an issue with the spec?

**Comment by jkotas** [comment]
`assignable-to` does not guarantee that the value is preserved. "Note:" under the list of rules explicitly mentions this. For example, `int32` is assignable to `int8` due to "T has intermediate type V, U has intermediate type W, and V is identical to W.". Allowing `native int` to be assignable to `int32` is not unreasonable from this point of view.

This rule and text appeared in 5th edition of ECMA-335 that was published in 2010 (https://www.ecma-international.org/publications-and-standards/standards/ecma-335/). My guess is that somebody filled a bug that the .NET Framework implementation does not match what spec says. It was easier to augment the spec than to introduce a breaking change in the shipping implementation.
