### ISSUE TITLE
Collectible AssemblyLoadContext is collected by GC while type from it is still alive

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/runtime#68434]
### Description

The doc say the unload of AssemblyLoadContext will only finish after all strong reference to type/instance of type/assembly from the AssemblyLoadContext is gone. But I see an InvalidOperationException when I try to load AssemblyLoadContext, store type in a field and try to create an instance later.
Is something wrong with the doc or runtime?

https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability
https://github.com/dotnet/runtime/blob/main/docs/design/features/unloadability.md

### Reproduction Steps

Run `test.cmd` from https://github.com/yyjdelete/AssemblyLoadContext_GC

### Expected behavior

No exception should happen

### Actual behavior

System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.

### Regression?

No

### Known Workarounds

Keep an strong reference to the AssemblyLoadContext before the code from it is finished.

### Configuration

.net 6.0.4 win_x64

----
Updated:
Also try to run the example from 
https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#main-testing-program
https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#program-loaded-into-the-testassemblyloadcontext

I can see `unload success: False` by default. But when I comment out `alc.Unload();`, I see `unload success: True` instead, not sure why all `Issue preventing unloading` in the code didn't work in the case.

**Comment by janvorli** [comment]
@yyjdelete the reflection type that you get here https://github.com/yyjdelete/AssemblyLoadContext_GC/blob/main/x1/Program.cs#L15 doesn't keep the `AssemblyLoadContext` managed instance alive, because it is just a reflection representation of the type. That's why you see the exception, because there are no managed references to the `AssemblyLoadContext` left and so its finalizer is invoked and the unload initiated. 
The exception you are getting indicates that.

However, even though the unloading is initiated, it would not complete until the reflection type is collected, because it has an internal reference to the managed `LoaderAllocator` instance, which is an object that ensures that representations of the types are alive until there is no way to create their instances. 
https://github.com/dotnet/runtime/blob/85910e923d905b1c4117d5715d85dea2de73b524/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L2357
The reflection Type would enable you to create an instance of such type.

**Comment by agocke** [comment]
Closing as by-design
