### ISSUE TITLE
[API Proposal]: CollectionMarshal.AsSpan for a ReadOnlyCollection

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/runtime#68534]
### Background and motivation

[`CollectionMarshal.AsSpan`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal.asspan?view=net-6.0) was introduced with .net 5 and works on `List<T>`. Unfortunately there is currently no way to get the `Span<T>` from a `ReadOnlyCollection` or `ReadOnlyList` (or via their interfaces).

`ReadOnlyCollection` much like `ImmutableArray` is way safer to use as a `Span<T>` than `List<T>` itself. For example we can't run into stale data with immutable list's or arrays. `ImmutableArray` already offers `AsSpan` for such purposes, therefore it would be conistent if the `ReadOnlyXXX` also get the chance to be exposed via `Span<T>`.

### API Proposal

```C#
namespace System.Runtime.InteropServices
{
    public static class CollectionsMarshal
    {
        public ReadOnlySpan<T> AsSpan(ReadOnlyCollection<T>);
        public ReadOnlySpan<T> AsSpan(ReadOnlyList<T>);
    }
}
```

### API Usage

```C#
// Fancy the value
var readOnlyCollection= GetAll():
var dtoAsSpan = CollectionsMarshal.AsSpan(readOnlyCollection);

private ReadOnlyCollection<MyDto> GetAll()
{
    // ...
}
```

### Alternative Designs

Alternatively `AsSpan` is exposed via `IReadOnlyCollection` or even `IList` (impact would be much bigger).

### Risks

And don't see any further risks than getting the `Span<T>` of a `List`. The same problems (even less) we have with lists we have with ReadOnlyLists.

**Comment by svick** [comment]
> `ReadOnlyList`

What's `ReadOnlyList`? [The only public type in .Net with that name I could find](https://docs.microsoft.com/en-us/dotnet/api/?term=ReadOnlyList) is `Microsoft.SqlServer.Management.Sdk.Sfc.ReadOnlyList<T>`. And I don't think it would even be possible to add an overload for this type to `CollectionsMarshal`.

> `ReadOnlyCollection` much like `ImmutableArray` is way safer to use as a `Span<T>` than `List<T>` itself. For example we can't run into stale data with immutable list's or arrays.

That's not really true, since `ReadOnlyCollection` does not guarantee that the collection won't change (immutable types do). But I don't think that actually diminishes the usefulness of this proposal.

**Comment by linkdotnet** [comment]
Hupps you are right @svick . There is no `ReadOnlyList`. That's on me.

> That's not really true, since ReadOnlyCollection does not guarantee that the collection won't change (immutable types do). But I don't think that actually diminishes the usefulness of this proposal.

Fair point, if the underlying original list gets modified, the `ReadOnlyCollection` would "see" the new entry as well.

**Comment by teo-tsirpanis** [comment]
Furthermore, unlike `List`, there is no guarantee that a `ReadOnlyCollection` is backed by contiguous memory, which spans require.

**Comment by stephentoub** [comment]
> Furthermore, unlike List, there is no guarantee that a ReadOnlyCollection is backed by contiguous memory, which spans require.

Yes, and even more than that, Readonly Collection wraps arbitrary `IList<T>` implementations, and even if every one was backed by contiguous memory (they're not), there's no way CollectionsMarshal could know how to extract a reference to that memory, since there's no way to do it through the interface. The best it could do would be to type test for only the collections it knows about and how to handle, and throw for everything else.

As proposed, this is not an API we could add.

**Comment by eiriktsarpalis** [comment]
Closing, per feedback.
