### ISSUE TITLE
EnvelopedCms Decryption of binary data corrupts response on Linux if unencrypted data starts with byte value 0x04

### ISSUE THREAD

**Issue by keanergr** [dotnet/runtime#68554]
### Description

Encrypting a data buffer that begins with byte value 0x04 fails to properly decrypt on Linux.
The same encryption/decryption operation works properly on Windows.

### Reproduction Steps

Run the attached Visual Studio project to demonstrate failure
[CheckEncryption.zip](https://github.com/dotnet/runtime/files/8563915/CheckEncryption.zip)
.

### Expected behavior

Encryption of the unencrypted buffer followed by decryption of the encrypted buffer should produced the original unencrypted buffer.

### Actual behavior

If the unencrypted buffer starts with byte value 0x04, the decryption of the encrypted buffer produces a buffer that is different from the unencrypted buffer.

### Regression?

This test fails for Linux Centos7 for using release versions of netcoreapp3.1 linux-x64, net5.0 linux-x64 and net6.0 linux-x64.
It has not been tested on other versions of Linux.
This test does not fail on Windows.

### Known Workarounds

Our workaround is to prepend pad bytes before the data to be encrypted, and then to strip these out after decryption to insure that the unencrypted buffer does not start with a leading EOF (0x04) byte.

### Configuration

DotNet version: 6.0.100 targeting net6.0, net5.0 or netcoreapp3.1
OS and version: CentOS Linux release 7.9.2009 (Core)
Architecture: linux-x64
Problem exists on this Linux version; does not occur on Windows; has not been tested on other Linux distros.

**Comment by vcsjones** [comment]
This sounds related to https://github.com/dotnet/runtime/issues/27705.

The issue is, .NET Core _used_ to incorrectly wrap the input data in an OCTET STRING (which starts with 0x04). For compatibility purposes, we left in the "unwrap the octet string" because we needed to be able to remove the octet string data that we were previously removing.

We can perhaps improve the strictness of the octet string removal. We could make sure we consume all of data here:

https://github.com/dotnet/runtime/blob/169ec8ef53ca55fa19201ef1244abb73959ba4e5/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs#L118-L124

@bartonjs any other suggestions?

**Comment by bartonjs** [comment]
Updated the title to better reflect the problem.  (X509 -> EnvelopedCms, Encryption->Decryption, fail -> corrupt)
