### ISSUE TITLE
CultureInfoConverter doesn't work correctly with UseSystemResourceKeys=true

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#68651]
There's a feature switch which is intended to reduce size of applications by removing exception messages and instead using just the resource key as the exception message. This is turned on by setting MSBuild property `UseSystemResourceKeys=true`.
The code which does that is here: https://github.com/dotnet/runtime/blob/4ec7a81108d944f292c7886653fc8f42494adc9d/src/libraries/Common/src/System/SR.cs#L21
It's compiled into each library and the rest of SR class (all the properties) are generated from resources.

This means that calling `SR.CultureInfoConverterDefaultCultureString` in default app returns `(Default)` from resources, but when `UseSystemResourceKeys=true` it returns `CultureInfoConverterDefaultCultureString` (string). This is used here: https://github.com/dotnet/runtime/blob/f10cddaf0863336327643f8c8e6ca332c596bed6/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs#L25

The external visible repro is:

`dotnet new console`

Program.cs:
```C#
System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Globalization.CultureInfo)).ConvertFrom(null, null, "(Default)");
```

`dotnet run` -> prints out nothing == works correctly.

`dotnet build /p:UseSystemResourceKeys=true`
`./bin/Debug/net6.0/app.exe` -> prints:
```
Unhandled exception. System.ArgumentException: CultureInfoConverterInvalidCulture, (Default) Arg_ParamName_Name, value
   at System.ComponentModel.CultureInfoConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Program.<Main>$(String[] args) in ...\Program.cs:line 1
```

The `UseSystemResourceKeys` is set to true by default in Blazor WASM projects, so this is effectively broken in all Blazor projects by default.

**Comment by tarekgh** [comment]
@vitek-karas is there a way we can always turn off `UseSystemResourceKeys` on the `System.ComponentModel.TypeConverter` library? the reason I am asking is, even we fix this specific instance, we can run into the same problems with all resources in this library. Even the behavior would be wrong at that time.

**Comment by jkotas** [comment]
This should be fixed by calling `SR.GetResourceString` with `defaultString` argument in the affected places. Here is an example where we do it today: https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Private.CoreLib/src/System/Diagnostics/StackTrace.cs#L208

> We can run into the same problem with all other resources in this library. 

Yes, I can tell by looking at Strings.resx that there are a few more resource strings that have the same problem and the same fix should be applied to those. However, vast majority of the strings are still exception messages and we should be still stripping those. I do not think it makes sense to disable `UseSystemResourceKeys` wholesale for this library.

**Comment by eerhardt** [comment]
> is there a way we can always turn off UseSystemResourceKeys on the System.ComponentModel.TypeConverter library? 

we did something similar here: https://github.com/dotnet/runtime/pull/42274
