### ISSUE TITLE
Using only a static method generates warnings from the ctor

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#68660]
The below code currently generates warnings for both RUC and RDC even though the user is only accessing the static method

```C#
using System;
using System.Diagnostics.CodeAnalysis;

public class Program
{
    static void Main(string[] args)
    {
        Derived.D_Method();
    }
}

public class Base
{
    [RequiresDynamicCode("RDC")]
    [RequiresUnreferencedCode("RUC")]
    public Base() { }
}

public class Derived : Base
{
    public static void D_Method() { }
}

```

```
ILC: Trim analysis warning IL2026: Derived.Derived(): Using member 'Base.Base()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. RUC.
ILC: AOT analysis warning IL3050: Derived.Derived(): Using member 'Base.Base()' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. RDC.

```

**Comment by MichalStrehovsky** [comment]
I didn't test this, but I think it's caused by:

https://github.com/dotnet/runtime/blob/7ae227a5aa60dc337b8fd195e96e380123b76a1a/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ConstructedEETypeNode.cs#L87-L94

The AOT compiler considers the public parameterless constructor implicitly needed, we compile it, scan it, and therefore generate the warning. This code was inherited from .NET Native as a way to ensure `Activator.CreateInstance<T>` always works. We "fixed" it for trimming by introducing RUC annotation on the `T` of CreateInstance (so now it doesn't always work, but it works it there's no warnings). That will be good enough for NativeAOT as well.

We can probably delete the above code. There might be some small fallout that will need fixing up.
