### ISSUE TITLE
Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0'

### ISSUE THREAD

**Issue by B-DAP** [dotnet/runtime#68720]
### Description

Getting this error when trying to run the solution:

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'. The system cannot find the file specified. File name: 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

I'm upgrading my solution from .NET 5 to .NET 6 and started getting this error. I can reproduce it both on macOS and Windows 11.

### Reproduction Steps
- Setup NLog in your solution along with NLog.Web.AspNetCore
  - Or you can clone this [example](https://github.com/NLog/NLog.Web/tree/master/examples/ASP.NET%20Core%206/ASP.NET%20Core%206%20NLog%20Example) project
- Have `<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>` included in the `.csproj` file you are trying to run

### Expected behavior

The project runs without errors

### Actual behavior

A runtime error

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'. The system cannot find the file specified. File name: 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' at MyApp.Program.CreateHostBuilder(String[] args) at MyApp.Program.Main(String[] args) in ..\MyApp\Program.cs:line 18

### Regression?

No errors on .NET 5 or earlier

### Known Workarounds

Remove  `<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>` from the `.csproj` file you are trying to run

### Configuration

.NET 6
Windows 11 x64 (reproducible on macOS ARM64 as well)

### Other information

First opened the issue with NLog developers. They have advised to open an issue with .NET team. 
[The issue on NLog repo](https://github.com/NLog/NLog.Web/issues/765)

**Comment by vitek-karas** [comment]
The default SDK behavior (since 3.0) is to copy all dependencies into the build output. That is `CopyLocalLockFileAssemblies=true`. With that, there's little reason to produce the `app.runtimeconfig.dev.json` file into the output - that file is only applicable to the machine it was generated on (confuses lot of people). So in .NET 6 we stopped producing that file by default.

What it means is that setting `CopyLocalLockFileAssemblies=false` in your project may not work without the `runtimecofig.dev.json` because not all dependencies of the app are accessible. The `runtimeconfig.dev.json` effectively tells the runtime to go look into the local NuGet cache for dependencies - something which only works on the machine where the app is building.

I don't know why you're setting `CopyLocalLockFileAssemblies=false`. If it's important to keep it you can set `GenerateRuntimeConfigDevFile=true` and it will produce the `.runtimeconfig.dev.json` just like before and everything should work. Or you could leave `CopyLocalLockFileAssemblies=true`.

**Comment by B-DAP** [comment]
Thank you for the detailed explanation. It is necessary for me to have `CopyLocalLockFileAssemblies=false`, setting `GenerateRuntimeConfigDevFile=true` is what I needed. I must've missed this in .NET 6 breaking changes list.
