### ISSUE TITLE
Proposal: Add Static Library Support

### ISSUE THREAD

**Issue by mwasplund** [dotnet/runtime#68761]
### Description
Compiling many small libraries can lead to large unwieldly runtime folders. Ideally a developer should have full control over how they organize their internal codebase into isolated units of code for code cleanliness and incremental build performance that does not require for internal structures to leak into the distribution package. I propose that .Net Core introduce a new concept of a static library which contains precompiled IL that will be linked into target DLLs. This will allow for the creation of a single self-contained executable that can perform more aggressive IL trimming to limit binary size and simplify distribution packages.

Open Question: Would there be startup performance improvements from load dll overhead?

### Configuration
NA

### Regression?
.Net Framework used to have the concept of net modules which was a close approximation but was removed with .net core.

### Other information
Issue opened on Roslyn where it was suggested to raise this issue with the core team: https://github.com/dotnet/roslyn/issues/60503
Issue related asking for net modules: https://github.com/dotnet/core/issues/4212
Issue asking runtime to re-add netmodules old discussion with no clear answer: https://github.com/dotnet/runtime/issues/10598
ILMerge seems to be dead: https://github.com/dotnet/ILMerge

**Comment by vitek-karas** [comment]
There are two possibilities which might fulfill the ask here, but I don't know which one you're looking for:

"Single-file assemblies"
That is something which contains IL code, but consists of multiple separate assemblies. Basically something very similar to what multi-module assemblies were in .NET Framework.
This approach is somewhat problematic from an API point of view: We're not bringing back multi-module assemblies, so this would have to fit into existing assembly APIs somehow. But how would `Assembly.LoadFile` for example work on this, it probably wouldn't. It would probably need a new API which loads such a file and makes all the assemblies in it "loadable" via `Assembly.Load` (or similar). It would be pretty problematic to plug this into the existing system.
.NET Native has something similar to this, but it required changes to lot of things in the runtime to support it. So possible, but probably rather complex to implement.
The value of it is basically that you can dictate more closely the files which make up a package/app.
I don't see how this would help with trimming - the trimming already looks at the entire app, so it really doesn't matter if it's many small files on disk, or multiple bigger ones.

"Native DLLs consisting of multiple assemblies"
This is what Native AOT kind of already does. We will very likely not official support it in .NET 7, but I think something like this is already possible in a way.
Note that the biggest downside is that since NativeAOT has its own runtime - the library is externally just a native library (as if written in C), you can't share managed objects from it in other managed code outside the library.
Native AOT is inherently trimmed.

**Comment by agocke** [comment]
As described, I think both of the things you mention in the original issue are addressed by single-file, trimming, and NativeAOT.

**Comment by mwasplund** [comment]
Sorry, I have been on leave for the past 3 months. Thanks for all of the responses.

However, one of the main scenarios I would like to address with this feature request is the ability to create a managed DLL that is entirely self contained to support easy distribution for a plug-in model where a know type is discovered using reflection and instantiated. This does not seem possible with single file executables or Native AOT DLL compilation.

**Comment by vitek-karas** [comment]
@MichalStrehovsky for the details, but my understanding is that NativeAOT can do this.

**Comment by mwasplund** [comment]
I admit I have not tried it personally, but the [blog post](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-3/) explicitly states that Native AOT will not allow for loading new .Net Assemblies at runtime.

"Native AOT forbids emitting new code at runtime (e.g. Reflection.Emit), and loading new .NET assemblies at runtime (eg. plug-in models)."

**Comment by MichalStrehovsky** [comment]
I think this is basically a request for multi-module assemblies - maybe with a twist that the extra modules should be embedded within the manifest assembly to also get a single-file experience - a single assembly that embeds multiple separate modules.

There are no plans to bring back multi-module assemblies.

I recommend looking into some IL Merging solution as a workaround (a tool that merges multiple assemblies into one - there are multiple but I don't have personal experience with any of them).

**Comment by fowl2** [comment]
I think the the ask is for integrated tool/sdk support, regardless of the implementation details :)

ILMerge proper being explicitly unsupported (both by its' developers and eg. the Microsoft Dataverse team) definitely makes encouraging people to even experiment in this direction discouraging. Very few libraries are going even consider being distributed for consumption in this way as it is, even with the existence of some packages out there extending the build to do it.

**Comment by vitek-karas** [comment]
@fowl2 did you try some of the other packages which try to solve this? I don't think it's necessary (or even desirable) for the SDK to have built-in support for everything. Making it extensible so that doing things like this is easier should be the goal (not that it's particularly good at it, it's extensible, but not that easily).

@mwasplund This design discussion about "package shading" could be interesting: https://github.com/dotnet/designs/pull/242. It doesn't address (as far as I can tell) the "single-file" part, but it does address the "isolation of dependencies" aspect. Note that it's not designed for plugin scenarios per-se, but it could be used there as well I think.
