### ISSUE TITLE
Support AOT that target shared libraries on Mono for the .NET 7 time frame

### ISSUE THREAD

**Issue by rodrigovaras** [dotnet/runtime#68775]
On the Native AOT .NET 7 discussion it was made clear that targeting native shared libraries will be supported only on Windows (x64/ ARM64) and Linux/MacOS. For our scenario we are building a multi-platform SDK that will target mostly Windows ARM 64 and Android/iOS. We would expose ABI type entry points to allow consumers of different runtimes to consume our SDK (Unity/ Unreal engine and others).  We also think this effort could help several people that want to write JNI modules on Android for example.
We would like to start a discussion to see if it seems reasonable to fill the gap for Android/iOS, by enhancing the existing MONO support. The time frame for this effort should be around the proposed .NET 7 time frame.
Starting with a simple 'Hello World' would be the first step to convince the rest of the team that is a realistic option.
CC: @jkotas

**Comment by insinfo** [comment]
I'm excited that with .NET 7 it will be possible to compile C# code to create a dynamic native library for Android, iOS, Windows, macOS and linux, I hope this will come to fruition even if it is released as a beta or alpha feature in .NET 7

**Comment by agocke** [comment]
FYI @marek-safar

**Comment by marek-safar** [comment]
@lambdageek could you please comment on the "gap" concerns?

/cc @rolfbjarne @jonpryor for visibility

**Comment by rodrigovaras** [comment]
> This is rather unlikely to happen in the .NET 7 timeframe for iOS, because in a month Apple will release the next version of Xcode with new OS versions, which will keep us quite busy over the summer.
> 
> Also there are two big questions that would have to be answered, which really defines the scope and complexity:
> 
> * Exactly what is exposed from managed code? Exposing only methods with the `[UnmanagedCallersOnly]` would be the simplest, but it would also not enable some more complex scenarios (such as subclassing a managed class in Objective-C for instance).
> * What happens if an app wants to use two shared libraries, built with different versions of the SDK/Runtime/etc?

I would suggest baby steps first, subclassing is way out of the scope for this request. Having a standalone .dll or static .lib where we can dll load and invoke is more than enough in the first phase.  About your concern on multiple shared libs with different SDK version what would be the problem? Each of them is a self contained island and so i don't see the problem you are raising beyond the inefficient use of two large files

**Comment by rodrigovaras** [comment]
> In principle this is something that could be done with mono today (at least for the "simple" scenarios that Rolf mentions). In practice, there is no tooling support and each library would need a bespoke build process.
> 
> Just thinking out loud:
> 
> 1. We would need to statically link the mono runtime together with AOT images of the assemblies that define the "unmanaged callers only" entrypoints.
> 2. We would need to bundle the managed libraries, System.Native, etc and either embed them into the .so on android or place them into a .framework on iOS.  We would need to configure the runtime to be able to find all this stuff.
> 3. We probably need to alter how we generate the native-to-managed stubs for the UnmanagedCallersOnly functions to also initialize the runtime the first time any function is called.  Maybe we can have some additional attribute to put on a dedicated initialization function that would have to be called first.
> 4. No idea about debugging, profiling, etc.
> 
> I think there's a moderate amount of work here. It seems very likely that we won't have time to do this in .NET 7. Perhaps we would have time to prototype a proof of concept focusing on one platform only.

The proof of concept would be a giant step in my opinion. How can we decide to jump on this wagon without knowing it has good chances of succeeding? We can work for now on the Windows ARM 64 SDK but with the hope that we will be able to succeed on Android/iOS, otherwise is pointless.

Just to clarify a point, when you say Mono will be the original assembly be created using the standard modern project file and using the target 'net7-android' ? And then using the existing Mono AOT compiler ? Or this will force us to use the old Xamarin.Android project style?

The problem you describe about linking the mono runtime with the AOT image was already resolved by the current Desktop scenario in Windows/Linux right ? Would be possible to replicate or learn whatever approach they already resolve? Maybe being to naive.

**Comment by lambdageek** [comment]
> Just to clarify a point, when you say Mono will be the original assembly be created using the standard modern project file and using the target 'net7-android' ? And then using the existing Mono AOT compiler ? Or this will force us to use the old Xamarin.Android project style?

yes I meant modern projects.

> The problem you describe about linking the mono runtime with the AOT image was already resolved by the current Desktop scenario in Windows/Linux right ? Would be possible to replicate or learn whatever approach they already resolve? Maybe being to naive.

I'm not sure what the right solution will be.  Just noting that there's a problem we'll need to address.  (It's already been done on the mono side a couple of times too - the old `mkbundle` tool, the current android SDK's loader for assemblies directly from a compressed .apk, etc.  We will have to see if any of those or the CoreCLR single file support are apropriate).

**Comment by lambdageek** [comment]
> About your concern on multiple shared libs with different SDK version what would be the problem? Each of them is a self contained island and so i don't see the problem you are raising beyond the inefficient use of two large files

The straightforward way to do this with mono would be essentially to embed MonoVM in the shared library. In many configurations mono relies on late binding / dynamic symbol lookup for managed-native interop, as well as for parts of its platform abstraction layer.  So if there are two copies of the runtime in a process, we have to be careful to avoid clashes. We must have essentially two separate VMs in one process.  That's not something we've focused on

**Comment by ceztko** [comment]
> In principle this is something that could be done with mono today (at least for the "simple" scenarios that Rolf mentions). In > practice, there is no tooling support and each library would need a bespoke build process.


@lambdageek can you elaborate more on such "bespoke" build processes? Let say for example that I can do myself the tooling to generate an `.h` header for the library or other interfaces, which is actually easy enough with roslyn (I am serious about, I was able to generate automatically [ObjectiveC](https://github.com/ceztko/CodeBinder/tree/master/CodeBinder.Apple/ObjC)/[Java](https://github.com/ceztko/CodeBinder/tree/master/CodeBinder.Java/Java)/[JNI](https://github.com/ceztko/CodeBinder/tree/master/CodeBinder.Java/JNI) bindings/trampolines), is it possible to build shared objects to use in iOS/Android today with existing .NET SDKs and native toolchains? Are there some examples available?

**Comment by ceztko** [comment]
Answering myself, after a good talk in the other iOS specific [thread](https://github.com/xamarin/xamarin-macios/issues/15217), it's unlikely that the current Native AOT [framework](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets) that works for the desktop platforms can be easily tricked to produce a iOS/Android shared libraries. Still it doesn't look like the target is too far away. Speaking specifically about iOS:
- Somehow [`ILCompiler`](https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot) seems to be able to compile ARM64 code object using the `ios-arm64` runtime identifier/architecture, or at least it doesn't crash when doing so. I didn't verify the produced code, though;
- The required [bootstrap](https://github.com/dotnet/runtime/tree/main/src/coreclr/nativeaot/Bootstrap)/[runtime](https://github.com/dotnet/runtime/tree/main/src/coreclr/nativeaot/Runtime) that are required to be linked in the shared library seems to be hardcoded to support `OSX` but for system code once ARM64 and darwin pecularities are supported (as it is now), maybe iOS isn't a big special case;
- Based on my experience, the linking part should be very similar to producing a `.dylib` as in macosx, with some patching to produce a shared object that can be used to assemble a framework.

I confirm that filling the gap and enable the production of shared libraries for Android and iOS platforms would be extremely valuable for my company. In a sense, these platforms are more interesting since the .NET runtime is not available at all or not easy to deploy. In both platforms producing bare libraries would have some interfacing misalignment with the respective development platforms:
- A bare iOS framework enabled shared library (a patched `.dylib`) would miss headers (either bare C or Objective C) and a framework manifest;
- A bare android compiled `.so` shared library would provide a C API but not JNI trampolines to be accessible for Java/Kotlin users. Also the C API would have no C headers.

IMHO, a general solution for such misalignments is not obvious, as it can require some arbitrary choices (eg. namespace/name of the class for the JNI trampolines). Still I would love to see such bare shared libraries enablement for iOS/Android to happen for 8.0.0, so that power users that are not afraid to produce a custom interface can start experimenting.

**Comment by MichalStrehovsky** [comment]
If you don't mind getting off the beaten path, have a look at https://github.com/josephmoresena/NativeAOT-AndroidHelloJniLib - it's for C# callable from Java/Kotlin apps. You can either use your own build of the runtime repo or a community build ("bflat" in the instructions) - the repo covers both avenues.

**Comment by ceztko** [comment]
@steveisok thank you very much for supplying the tracking issue. I'm now understanding that the Native AOT team is not going to do the job for the iOS/Android world but this would be a mono AOT team task instead. This was not immediately clear considering how much work has been already done for the desktop platforms, most of it would be directly portable to mobile ones as well. Can you leave a short explanation why so?

**Comment by steveisok** [comment]
@ceztko Mono is the .NET runtime that is currently supported on iOS and Android and has been for many years.  We have an AOT compiler as well, so it makes sense to continue to build upon it. Seeing that there are two aot compilers, I expect some feature overlap.  Certainly not a bad thing as I think we can all learn from each other to make a better product.  

While I believe it would be possible to work in NativeAOT as another runtime option, it wouldn't be a drop in replacement and would likely take a good bit of testing / analysis.

**Comment by steveisok** [comment]
@rodrigovaras we've done the work on the runtime side to make this feature possible. Let me know if this works for you and if not, feel free to reopen.
