### ISSUE TITLE
Serialization issue in .NET 6 Blazor after publishing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#68826]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Serialization-issue-in-NET-6-Blazor-aft/1623360)._

---
[regression] [worked-in:.NET 5]
After upgrading to .NET 6 from .NET 5 I'm seeing an issue when serializing / deserializing a RectangleF.

This was working fine before in .NET 5. This works fine when running in the debugger. The issue only appears after publishing the project to the server. Here's a few lines of code to reproduce it in a Blazor Webassembly project.

var rect = new RectangleF(0.21500044F, 1.9283372F, 0.15833366F, 0.066666804F);
var serializedRect = JsonSerializer.Serialize(rect);
var deserializedRect = JsonSerializer.Deserialize<RectangleF>(serializedRect);

When debugging the deserialized rectangle will have a value. Once it's published to the server the rectangle is always empty.

This is a Blazor Webassembly app.
I'm running VS 2022 17.0.4
.NET 6 6.0.1 on the server.

Thanks

---
#### Feedback Bot on 12/27/2021, 10:44 PM: 

(private comment, text removed)
#### Feedback Bot on 12/28/2021, 01:07 AM: 

(private comment, text removed)
#### Adam Diament on 5/3/2022, 00:38 AM: 

(private comment, text removed)
#### Adam Diament on 5/3/2022, 00:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by agocke** [comment]
This looks like members are being trimmed away when using JsonSerializer. This would probably provide trim warnings if those were enabled in Blazor. I think using JsonSerializer source generation is supposed to be trim-compatible. 

@eerhardt are there any suggestions or guidance for customers who find themselves in this situation? Turn on trim warnings?

**Comment by eerhardt** [comment]
The reason this broke between .NET 5 and .NET 6 is because we removed the `[DynamicallyAccessedMembers]` attributes on the trim-unfriendly JsonSerializer APIs. See https://github.com/dotnet/runtime/issues/52268.

The general guidance is to not use the reflection based serializers and instead use source generation - https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation

Turning on trim warnings would help find issues, but the developer would need to ignore the warnings coming from the ASP.NET assemblies, since they are not fully annotated for trimming.

**Comment by agocke** [comment]
Thanks for the info. Maybe there's some small things we could do to help push people in the right direction. Is S.T.J source generation also mentioned in the Blazor docs? A pointer might help. I'm also curious -- has any investigation been done for the trim analyzer for Blazor? I wonder if that might work better, since it wouldn't surface any internal warnings in 3rd party code.

**Comment by eerhardt** [comment]
>  has any investigation been done for the trim analyzer for Blazor? I wonder if that might work better, since it wouldn't surface any internal warnings in 3rd party code.

Not that I'm aware of - but that's a really good idea. It will at least mark user code that calls into trim-incompatible APIs.

cc @SteveSandersonMS @captainsafia

**Comment by agocke** [comment]
We might need to mess with the suppression code for this -- SuppressTrimWarnings suppresses for both the analyzer and the trimmer, so we might need a new option that just suppresses for the trimmer.

**Comment by kasperk81** [comment]
> The general guidance is to not use the reflection based serializers and instead use source generation - https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation

how do we use these "general" guidelines in f# project, which is also supported by same .net 6 sdk?

**Comment by eiriktsarpalis** [comment]
> > The general guidance is to not use the reflection based serializers and instead use source generation - https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation
> 
> how do we use these "general" guidelines in f# project, which is also supported by same .net 6 sdk?

Source generation is not support in F# projects. You might want to consider putting your source generated DTOs in a C# class library or use an F#-specific metaprogramming solution like Myriad.
