### ISSUE TITLE
Visual Studio design time build failing to recognize essential types like Void, IDisposable, Enum in test code

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#68862]
@ViktorHofer 

It seems a recent change broke design time build for test code in Visual Studio. Not sure if widespread or not, but I can repro this in `System.Formats.Tar`:

- Sync your local clone to the latest bits in `main`.
- Clean with `git clean -fdx`.
- Build with `build.cmd clr+libs -rc release`.
- Open the solution with `build.cmd -vs System.Formats.Tar`.
- Open any test file.
- Notice the red squiggle error messages, they say we cannot find System.Void, System.IDisposable, System.Enum.

**Comment by ViktorHofer** [comment]
That's because you have a ProjectReference to the source project even though that source project is already referenced via the targeting pack: https://github.com/dotnet/runtime/blob/5992145db2cb57956ee444aa0f0c2f3f85ee3673/src/libraries/System.Formats.Tar/tests/System.Formats.Tar.Tests.csproj#L69-L71

When you remove that ProjectReference, the design time build failures go away. You can see in the design time binlog that the reference assembly is chosen from the ProjectReference's output folder:

![image](https://user-images.githubusercontent.com/7412651/166727417-a81ffdc1-9c03-4ec4-b7e2-cb3389c57c99.png)

**Comment by carlossanlop** [comment]
Thanks, that fixed it.

**Comment by ViktorHofer** [comment]
cc @ericstj as you might be interested in this. Seems there is a conflict between P2Ps that are exposed inbox as well via the targeting pack.

**Comment by ericstj** [comment]
yeah, that's not handled well in the SDK: https://github.com/dotnet/sdk/issues/2674

It might be nice if our infrastructure did some validation around what sort of reference to use where.  Guide people down the path of doing the right thing.

**Comment by ViktorHofer** [comment]
> It might be nice if our infrastructure did some validation around what sort of reference to use where. Guide people down the path of doing the right thing.

This already works for a normal build because of https://github.com/dotnet/runtime/blob/3116f288818f89ef6ca3f39e19b4e98cf022793f/eng/targetingpacks.targets#L131.

It might make more sense to investigate why this doesn't work for a design time build.
