### ISSUE TITLE
Addressing security vulnerability in System.Text.Json 4.X version

### ISSUE THREAD

**Issue by avanigupta** [dotnet/runtime#68931]
Is there any plan to release a new 4.X version of System.Text.Json due to the security vulnerability reported here: https://github.com/dotnet/runtime/issues/49377

The latest 4.X version of System.Text.Json is v4.7.2 but that version still depends on System.Text.Encodings.Web v4.7.1, which has the security vulnerability: https://www.nuget.org/packages/System.Text.Json/4.7.2

We have a dependency on System.Text.Json v4.6.0 and we cannot introduce breaking changes by upgrading to 5.X version.
What would be the best way to address this issue?

**Comment by huoyaoyuan** [comment]
> We have a dependency on System.Text.Json v4.6.0 and we cannot introduce breaking changes by upgrading to 5.X version.

The supported framework is the same for 5.0.X. Do you mean any behavioral breaking change that's unacceptable?

I believe you can add a direct reference of `System.Text.Encodings.Web` in your project and select a non-vulnerable version.

**Comment by avanigupta** [comment]
We use System.Text.Json v4.6.0 in our Microsoft.Extensions.Configuration.AzureAppConfiguration package. If we decide to upgrade System.Text.Json to 5.X version, we'll have to bump up the major version of our library. Since this is a security vulnerability, we were hoping to release the fix quickly as a minor version upgrade so that users can start using the new version without worrying about breaking changes.

**Comment by eiriktsarpalis** [comment]
Can't the Microsoft.Extensions.Configuration.AzureAppConfiguration package explicitly list System.Text.Encodings.Web v4.7.2 as a dependency?

**Comment by avanigupta** [comment]
We can do that, but that's more of a workaround than a real solution. 
Is the 4.X train of System.Text.Json out of support now? If not, it seems like this vulnerability should be addressed for anyone using the 4.X versions.

**Comment by eiriktsarpalis** [comment]
cc @ericstj

**Comment by jimmyca15** [comment]
@eiriktsarpalis @ericstj 

Is the 4.x package versions of System.Text.Json still being supported / still receiving any possible security updates?

**Comment by eiriktsarpalis** [comment]
.NET Core 3.1 will be supported until December this year, so any servicing updates should surface as 4.x package updates.

**Comment by jimmyca15** [comment]
@eiriktsarpalis 

I see thanks. Doesn't the package being supported mean that it should release an update if it has a dependency on a vulnerable package?

**Comment by jimmyca15** [comment]
@ericstj 

Thank you for clarifying.

**Comment by GrabYourPitchforks** [comment]
Generally speaking, the position of the .NET team has been that we do not issue patches for non-vulnerable packages. The package _System.Text.Json_ itself is not vulnerable and does not consume vulnerable functionality. The package _System.Text.Encodings.Web_ was the vulnerable package, and a patch has been issued for it. The solutions we have been promoting are solutions where _the application itself_ upgrades the version of the vulnerable package, since the application is the ultimate arbiter of what gets packaged as a single unit of deployment.

The NuGet team has been considering gestures which allow applications to self-remediate. This is the preferred mechanism from our perspective, since it does not require re-shipping the entire ecosystem and invalidating existing packages every time a single dependency updates. See https://github.com/NuGet/Home/pull/11549 for further discussion on this.

**Comment by ericstj** [comment]
@ViktorHofer just shared this new feature with me and I think it really helps in this scenario: https://devblogs.microsoft.com/nuget/introducing-central-package-management/#transitive-pinning

Have a look at this gist https://gist.github.com/ericstj/1b9aab17e6701cda6e7f054a53fed9e3
You can see that by centrally managing your packages you can control the version of the transitive dependency without having to mention it in the project that uses it's parent.  Nuget also will automatically list it in the nuspec so that folks consuming your package get the same behavior regardless of if they use that feature or not.  Nice work @jeffkl!
