### ISSUE TITLE
Way to unload a Managed assembly from native library using hostfxr

### ISSUE THREAD

**Issue by Chandra123539** [dotnet/runtime#68949]
**Issue**

Is there any way to unload a Managed assembly which is loaded from Native library using hostfxr library. Does unloading of hostfxr unload Managed assembly ?

Workflow
ASP.Net Core Service---> loads ---> Native Library-----> loads Managed Assembly using hostfxr.

we would like to know whether we have a possibility of unloading Managed Assembly .

Please let us know your inputs on this.

**Comment by vitek-karas** [comment]
Currently this is not supported. We don't expose API in `hostfxr` to unload managed assembly loaded when using `hostfxr` right now.

Unloading `hostfxr` will likely do nothing since it has been loaded by the ASP.NET main executable (not counting that some of it may still be in use, so doing that would be dangerous if you forced it).

With some work you could unload most of your code:
* Create a small assembly which is loaded by `hostfxr` and it in turn loads the rest of your code into a new collectible ALC
* Then call a method in that assembly which will unload the collectible ALC when you're done.
* The small assembly will still remain loaded, but the rest of your code will be gone.

**Comment by Chandra123539** [comment]
Thanks Vitek for the information.

**Comment by Chandra123539** [comment]
Just one more doubt out of curiosity.

Workflow
![image](https://user-images.githubusercontent.com/57258610/167550022-cd5784ad-c78d-4ecd-82ea-e97e770cf432.png)


Is it Possible load more than one Managed Assembly using hostfxr in the above mentioned workflow ?

**Comment by vitek-karas** [comment]
Yes - this is definitely possible. `hostfxr` entry points can be called multiple times to do this. Or if you go with the small assembly to get the unloadability, you can implement this in that small assembly.

**Comment by Chandra123539** [comment]
Thanks Vitek. we have got the information required.

Please close the issue.
