### ISSUE TITLE
SerialPinChange.ToString() returns an integer value

### ISSUE THREAD

**Issue by udaken** [dotnet/runtime#69290]
### Description

The code below for watching for PinChanged events on a serial port almost rightly prints the name of the event type.

```cs
SerialPort serialPort1 = /*...*/;
serialPort1.PinChanged += SerialPort1_PinChanged;

void SerialPort1_PinChanged(object sender, SerialPinChangedEventArgs e)
{
    Console.WriteLine($"PinChanged: {e.EventType}");
}
```

Output:
```
PinChanged: CtsChanged
PinChanged: DsrChanged
...
```

However, in rare cases, it displays integers and does not display names.
```
PinChanged: 24
```

`24` is the value of `System.IO.Ports.SerialPinChange.CtsChanged | (System.IO.Ports.SerialPinChange.DsrChanged`.

[`System.IO.Ports.SerialPinChange`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialPinChange.cs) enumeration type looks like Flags, but I think the attribute is missing.

### Reproduction Steps

Simply,
```cs
Console.WriteLine((System.IO.Ports.SerialPinChange.CtsChanged | System.IO.Ports.SerialPinChange.DsrChanged).ToString());
```

### Expected behavior

ToString() returns `CtsChanged, DsrChanged`.

### Actual behavior

ToString() returns `24`.

### Regression?

no.

### Known Workarounds

Set the "f" flag in the ToString() format string.

### Configuration

.NET 6 on Linux

**Comment by danmoseley** [comment]
On Windows `WaitCommEvent` apparently [signals once for each event](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-waitcommevent). The SerialPinChange enum values which originate from Windows are nevertheless bit flags because they are designed to be [combined](https://github.com/dotnet/runtime/blob/43dd0a74ab524278620d8c6a9d33a9b73b2d2228/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.Windows.cs#L30) to indicate which events one wants to wait for.

On Linux `ioctl(fd, TIOCMGET, ... )` can set [multiple bits](https://linux.die.net/man/4/tty_ioctl) and the matching SerialPinChange values are or-ed together.

So it seems everything is working correctly except the ToString() of SerialPinChange. @stephentoub are you aware of anything that applying `[Flags]` to an enum does other than make ToString() work for or-ed flags? It seems eg., that `Enum.HasFlags(..)` is not affected.

Assuming so, we should just apply it, but that would be a (tiny) API change proposal.

**Comment by danmoseley** [comment]
@bartonjs will know..

**Comment by bartonjs** [comment]
Adding the `[Flags]` attribute would enable the bitwise operators, but that's more permissive, not more restrictive.

The only real breaking change I can think of would be methods like `AsnWriter.WriteEnumerated<T>`, which rejects `[Flags]` based enums.  (https://github.com/dotnet/runtime/search?q=typeof%28FlagsAttribute%29 for the small number of similar concerns).

Honestly, if Windows is signalling once per event, and it's not already marked `[Flags]`, then I think the better answer is for non-Windows to change to signal once per set bit instead of once with them or'd together (calling code will probably not handle the or-d together values correctly).

**Comment by danmoseley** [comment]
thanks. @krwq thoughts about modifying the Unix code to fire once per event?

**Comment by krwq** [comment]
@danmoseley no objections, weird that API is marked as flags even though it never combines it but better to be consistent across platforms and split events on Linux

**Comment by krwq** [comment]
@udaken do you feel like making a contribution?

**Comment by danmoseley** [comment]
> weird that API is marked as flags even though it never combines it 

It’s not marked as [Flags] - assuming you mean, wierd that each entry has its own bit, it’s because the values were copied from Win32, where it’s used as a bitmap to indicate which events you want to subscribe to. We don’t expose that though.

**Comment by udaken** [comment]
@krwq I am interested but unable to prepare an environment to build the runtime, so unfortunately I am not likely to be able to contribute.

**Comment by eerhardt** [comment]
@udaken - Do you have Docker installed? If so, you can prepare an environment by following the steps in https://code.visualstudio.com/docs/remote/create-dev-container with a dotnet/runtime clone. We have a `.devcontainer` folder in the repo with all the requirements needed to prepare an environment. All you need is Docker.

If that isn't possible, another option would be to get your account enabled for Codespaces. But in order to do that, I think you need to be part of the dotnet organization. If you want to try going down this route, I can try to get you added.

**Comment by udaken** [comment]
Please see @pedrobsaila's PR about this Issue.
