### ISSUE TITLE
Microsoft.Interop.SourceGeneration.csproj and LibraryImportGenerator.csproj have hard-coded RunAnalyzers setting

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#69450]
The following prebuilts are being reported by source-build:

1. Microsoft.NET.ILLink.Analyzers.7.0.100-1.22255.1
2. StyleCop.Analyzers.1.2.0-beta.406

These are being reported as coming from 

...artifacts/obj/LibraryImportGenerator/project.assets.json
...artifacts/obj/Microsoft.Interop.SourceGeneration/project.assets.json

These projects appear to have a hard-coded RunAnalyzers setting vs utilizing the [eng/Analyzers.Props setting](https://github.com/dotnet/runtime/blob/main/eng/Analyzers.props#L4).

**Comment by AaronRobinsonMSFT** [comment]
The LibraryImport generator is required to run during build since it auto-generates all DllImport IL stubs for netcoreapp. Turning either of them off would result in a broken build. I could be missing something though.

/cc @dotnet/interop-contrib

**Comment by elinor-fung** [comment]
The issue here is not that the LibraryImportGenerator is running on other projects, but that the LibraryImportGenerator project is always pulling in other analyzers to run on the LibraryImportGenerator project itself. We should instead respect the setting that @MichaelSimons pointed out and only set `RunAnalyzers=true` if it wasn't already set.

**Comment by ViktorHofer** [comment]
I agree that if possible, generator projects like these two should use the analyzers that come via the Analyzers.props file.
