### ISSUE TITLE
Equals/GetHashCode for UnixDomainSocketEndPoint

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#69488]
### Background and motivation

My network framework uses _EndPoint_ class as abstraction layer to represent the peer address. It is easy to determine whether the two endpoints represent the same address using _Equals_ method. However, _UnixDomainSocketEndPoint_ doesn't override necessary methods in contrast to _IPEndPoint_ and _DnsEndPoint_.

### API Proposal

```csharp
namespace System.Net.Sockets;

public sealed class UnixDomainSocketEndPoint : EndPoint
{
  public override bool Equals(object? other);
  public override int GetHashCode();
}
```

### API Usage

var set = new HashSet<EndPoint>();

set.Add(new UnixDomainSocketEndPoint("@abstract"));
set.Contains(new UnixDomainSocketEndPoint("@abstract"));

### Alternative Designs

Implement custom equality logic:
```csharp
static bool EndPointsAreEqual(EndPoint x, EndPoint y)
{
  if (x is UnixDomainSocketEndPoint uds1)
    return y is UnixDomainSocketEndPoint uds2 && string.Equals(uds1.ToString(), uds2.ToString(), StringComparison.Ordinal);

  return object.Equals(x, y);
}
```

### Risks

Breaks behavior of default implementation of _Equals_ and _GetHashCode_.

**Comment by stephentoub** [comment]
Given that both IPEndPoint and DnsEndPoint override these, it's reasonable for UnixDomainSocketEndPoint to as well.  I don't think this really needs to be considered an API proposal.  Technically it could break someone relying on Equals providing reference equality, but the chances of that are slim, especially since that's not what it means generally when using the base EndPoint.

**Comment by sakno** [comment]
@stephentoub , if so, I'm ready to make a PR.

**Comment by CarnaViire** [comment]
Triage: that makes sense; we would gladly accept the contribution @sakno
Moving to Future as it's not a priority
