### ISSUE TITLE
Audit source-generated marshallers for integer overflow bugs

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#69532]
For example, here:
https://github.com/dotnet/runtime/blob/bcded447f1558e7f891f3411f566db49f2ced6ec/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/ArrayMarshaller.cs#L69
What happens when this multiplication overflows?

**Comment by GrabYourPitchforks** [comment]
I noticed this in the string marshallers as well the other day, e.g.:

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/Utf8StringMarshaller.cs#L48

I _think_ the worst that will happen here is a runtime exception since somebody somewhere will detect the overflow, but I don't think we want to rely on the good graces of the implementation to handle error checking on our behalf.
