### ISSUE TITLE
create-mibc with spgo on Linux

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#69607]
As says 62df49298ae1 trace with sample data could be collected on Windows with xperf. Corresponding to https://github.com/dotnet/runtime/blob/main/docs/design/features/dotnet-pgo.md instrumented traces on Linux could be collected with dotnet-trace tool. Is there any tool on Linux for collecting spgo-traces to create mibc-file?

cc @jakobbotsch @davidwrighton @AndyAyersMS @alpencolt

**Comment by davidwrighton** [comment]
There is no tool on Linux which will be able to gather the appropriate data for spgo optimization via dotnet-pgo. However, this isn't a major loss as the sampled pgo optimizations did not show a significant improvement in performance due to the lack of accuracy when presented with optimized code, and the lack of integration with the type based optimizations that have shown to be extremely important to gain a benefit from profile guided optimization in .NET. We may revisit this in future years, but currently I do not expect sample based pgo to provide a significant benefit to any customer in the near term.
