### ISSUE TITLE
[Uri] Absolute paths using UriKind.RelativeOrAbsolute parsed as relative on iOS and Android

### ISSUE THREAD

**Issue by dotMorten** [dotnet/runtime#69618]
### Description

`Uri.TryCreate` with `UriKind.RelativeOrAbsolute` fails to detect absolute paths on .NET 6 iOS and Android, whereas this worked with the legacy Xamarin mono runtimes.

### Reproduction Steps

Run the code on both .NET 6 ios/android and legacy xamarin. Note that the asserts are very different for the code to work on both platforms.
```cs
#if __IOS__ || __ANDROID__
            if (System.Uri.TryCreate("/data/user/0/file.txt", System.UriKind.RelativeOrAbsolute, out System.Uri? result))
            {
#if NETCOREAPP
                System.Diagnostics.Debug.Assert(result.IsAbsoluteUri == false);
                try
                {
                    System.Diagnostics.Debug.Assert(result.IsFile == false); //Throws invalid operation
                    System.Diagnostics.Debug.Assert(false); // We don't get here
                }
                catch(System.InvalidOperationException)
                {
                }
#else // Legacy xamarin
                System.Diagnostics.Debug.Assert(result.IsAbsoluteUri == true);
                System.Diagnostics.Debug.Assert(result.IsFile == true);
#endif
            }
#endif
```

### Expected behavior

IsAbsoluteUri and IsFile behavior matches legacy xamarin behavior.

### Actual behavior

Incorrectly doesn't detect that the URL is absolute (ie starting with '/').

### Regression?

Yes this worked correctly in Xamarin.

### Configuration

.NET 6.0.5, ARM64. iOS and Android.

**Comment by dotMorten** [comment]
Found this reference regarding the difference: https://www.mono-project.com/docs/faq/known-issues/urikind-relativeorabsolute/

**Comment by filipnavara** [comment]
This was always a difference between .NET [Core]. The problem is that the input is ambiguous, it can either be relative to server Uri (eg. `/foo/bar/` relative to `https://foo.com/example/` is `https://foo.com/foo/bar) or an absolute path with implicit `file://` scheme. Mono (& legacy Xamarin) chose to interpret it one way and .NET Core the other way. .NET 6 follows the .NET Core interpretation.

**Comment by MihaZupan** [comment]
As Filip mentioned, `Uri` recognizes implicit file paths (without the `file://` scheme prefix), and this behavior differs between platforms. The observed behavior is, unfortunately, by design.

We're solving the opposite problem by introducing a new API in .NET 7 (if we get around to implementing it) that will let you explicitly opt out of parsing implicit file paths (#59099), but there's no plan to make Unix absolute path parsing work on other platforms.

If at all possible, I would recommend using `Path` APIs when dealing with files.

**Comment by karelz** [comment]
Triage: Given that this is difference between Mono and .NET Core, there is not much we can do -- having unified ways across our platforms is somewhat useful.
If we see more people hitting it, we might want to call it out as breaking change in Xamarin/Mono.
