### ISSUE TITLE
Update zlib (zlib-Intel) to 1.2.12

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#69652]
We're currently using 1.2.11.  Newer versions have been released.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/68219

**Comment by AraHaan** [comment]
So, zlib 1.2.12 was recently tagged in madler/zlib and might have other changes as well,

Also it would be nice if System.IO.Compression.Native exported all of the symbols that the regular zlib library exports as well because technically I have manual code that needs it and trying to figure out making a nuget package for the native zlib myself for:

- win-x86
- win-x64
- win-arm64
- linux-x64
- linux-arm
- linux-arm64
- all of linux-musl and linux-rhel's that .NET supports
- osx-x64
- osx-arm64

While it might be possible, it is more of a pain than what it is worth and I feel simply adding all the exports that zlib.def (and the other export files from madler/zlib would be the best option. Yeah it might add exports not used by dotnet/runtime but it allows code outside of dotnet/runtime to P/Invoke those to get the best performant options of:

- crc32
- adler32
- etc.

Those exports could be renamed to ``[export symbol]_zlib`` for the original exports that would normally be exported from ``zlib.dll`` (or ``zlibwapi.dll`` or ``zlib1.dll``), ``libzlib.so``, or even ``libzlib.dylib``. It would be better for a lot of developers this way as well too.

**Comment by jkotas** [comment]
> While it might be possible, it is more of a pain than what it is worth and I feel simply adding all the exports that zlib.def (and the other export files from madler/zlib would be the best option

We treat exports from `System.*.Native` libraries as internal implementation detail and explicitly do not want to 3rd party code to depend on it. We would not want to add these exports.

If the public managed APIs are not doing what you need, submit an API suggestion to improve them.

**Comment by AraHaan** [comment]
I did, however they are sorta still waiting for review and I kinda needed the code now so I had to try to write code separate from it that could use ``System.*.Native`` with some added exports locally to try to get it to work.

Basically the APIs I needed was span based zlib apis for compression / decompression.
