### ISSUE TITLE
string.LastIndexOf(char, int, int) doesn't work

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#69666]
### Description

The function `int string.LastIndexOf(char value, int startIndex, int count)` doesn't work properly.

It checks the `count` parameter incorrectly [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/String.Searching.cs#L286).

It should check `count < 0 || (uint)count + (uint)startIndex > (uint)Length` or `(uint)count > (uint)(Length - startIndex)` (simplified) for a failure, not `(uint)count > (uint)startIndex + 1`.

I'm happy to make a PR, just let me know that I should, I'll also check the other functions if so.

### Reproduction Steps

```cs
var x = "abcdef";
var y = x.LastIndexOf('d', 0, 5)
```

### Expected behavior

`y = 3`

### Actual behavior

System.ArgumentOutOfRangeException: Count must be positive and count must refer to a location within the string/array/collection.
Parameter name: count

### Regression?

It also happens in the .NET Framework 4.8. It should probably also fixed there, in 4.8.1 or a servicing release.
It's probably also broken in earlier .NET Core versions, so the fix should be back-ported there too.

### Known Workarounds

Use `Substring` and then `LastIndexOf(char)`

**Comment by KalleOlaviNiemitalo** [comment]
It works as documented in <https://docs.microsoft.com/en-us/dotnet/api/system.string.lastindexof?view=net-6.0#system-string-lastindexof(system-char-system-int32-system-int32)>. `startIndex` is the starting position of the search, not the numerically smallest position to search. So if you want to search the first five positions of `string x`, then the search should start at `x[4]` and proceed toward `x[0]`, and you have to call ` x.LastIndexOf('d', 4, 5)` rather than ` x.LastIndexOf('d', 0, 5)`.
