### ISSUE TITLE
P/Invoke string encoding doesn't work properly in some cases

### ISSUE THREAD

**Issue by fandrei** [dotnet/runtime#69660]
### Description

When running the code below, I get "?" chars instead of some Unicode chars.

### Reproduction Steps

```
[DllImport(User32, SetLastError = true, CharSet = CharSet.Unicode)]
public static extern IntPtr CreateWindowEx(
	int dwExStyle,
	UInt16 regResult,
	[MarshalAs(UnmanagedType.LPStr)] string lpWindowName,
	UInt32 dwStyle,
	int x,
	int y,
	int nWidth,
	int nHeight,
	IntPtr hWndParent,
	IntPtr hMenu,
	IntPtr hInstance,
	IntPtr lpParam);

// ....

var classReg = RegisterClassEx(ref classInfo);
if (classReg == 0)
	throw new Win32Exception();

var hWnd = CreateWindowEx(0, classReg, ""խխխ 3"", WS_POPUP | WS_VISIBLE,
Location.X, Location.Y, Size.Width, Size.Height, IntPtr.Zero, IntPtr.Zero, classInfo.hInstance, IntPtr.Zero);
```

### Expected behavior

Show the window titled "խխխ 3"

### Actual behavior

Shows "??? 3" instead.
Same code rewritten in C++ works no problem.

### Configuration

.NET 6
Windows 10
x64

**Comment by jkoritzinsky** [comment]
You're passing the window name with the `[MarshalAs(UnmanagedType.LPStr)]`; however, since you're specifying the `CharSet = CharSet.Unicode`, the runtime is calling the `CreateWindowExW` method, which expects an `LPWSTR` for the `lpWindowName` parameter. You should remove the `[MarshalAs]` attribute on the `lpWindowName` parameter.

Also for correctness, you should change the type of the `regResult` parameter to `nuint` as the native function expects a pointer-sized value (either a pointer to a string or an atom, which is what you're passing).

**Comment by fandrei** [comment]
@jkoritzinsky 
`You should remove the `[MarshalAs]` attribute on the `lpWindowName` parameter.

I already tried that and it works even worse in this case. All the text gets truncated by the first letter or is written garbled.
```
	[DllImport(User32, SetLastError = true, CharSet = CharSet.Unicode)]
	public static extern IntPtr CreateWindowEx(
		int dwExStyle,
		UInt16 regResult,
		string lpWindowName,
		UInt32 dwStyle,
		int x,
		int y,
		int nWidth,
		int nHeight,
		IntPtr hWndParent,
		IntPtr hMenu,
		IntPtr hInstance,
		IntPtr lpParam);
```

**Comment by jkoritzinsky** [comment]
Okay, that's very odd. Can you put together a small repro and share it?

**Comment by fandrei** [comment]
@jkoritzinsky https://github.com/fandrei/PInvokeWindowRepro

**Comment by fandrei** [comment]
PS the window itself doesn't have the title bar; it's shown in the taskbar only.

**Comment by fandrei** [comment]
@jkotas this issue is **not** resolved.

**Comment by AaronRobinsonMSFT** [comment]
@fandrei This is an issue with inconsistent API use across the Win32 boundary. It appears that Unicode was desired and that was specified in several locations, but in one, `DefWindowProc`, it was not and so the ANSI version of the API was being used. The Win32 API is very picky about this when using the windowing system - all API should match because they interpret the stored contents differently.

Another issue we saw was that the delegate wasn't being stored so this could have been collected during a GC and caused a problem. This can be solved using `GC.KeepAlive()`. Alternatively, since this was written in .NET 6, C# function pointers could have been used which would be much more performant.

```diff
diff --git a/Program.cs b/Program.cs
index 8fdd96d..873d261 100644
--- a/Program.cs
+++ b/Program.cs
@@ -21,11 +21,12 @@ internal static class Program
 			Debugger.Break();
 		}
 
+		DelegateWndProc del = (DelegateWndProc)WndProc;
 		classInfo = new WNDCLASSEX
 		{
 			cbSize = Marshal.SizeOf(typeof(WNDCLASSEX)),
 			style = (int)(CS_HREDRAW | CS_VREDRAW | CS_DBLCLKS),
-			lpfnWndProc = Marshal.GetFunctionPointerForDelegate((DelegateWndProc)WndProc),
+			lpfnWndProc = Marshal.GetFunctionPointerForDelegate(del),
 			cbClsExtra = 0,
 			cbWndExtra = 0,
 			hInstance = hInstance,
@@ -49,6 +50,7 @@ internal static class Program
 		UpdateWindow(hWnd);
 
 		Application.Run();
+		GC.KeepAlive(del);
 	}
 
 	const string User32 = "user32";
@@ -65,8 +67,8 @@ internal static class Program
 		public IntPtr hIcon;
 		public IntPtr hCursor;
 		public IntPtr hbrBackground;
-		[MarshalAs(UnmanagedType.LPStr)] public string lpszMenuName;
-		[MarshalAs(UnmanagedType.LPStr)] public string lpszClassName;
+		public string lpszMenuName;
+		public string lpszClassName;
 		public IntPtr hIconSm;
 	}
 
@@ -75,7 +77,7 @@ internal static class Program
 
 	[DllImport(User32, SetLastError = true, CharSet = CharSet.Unicode)]
 	[return: MarshalAs(UnmanagedType.Bool)]
-	public static extern bool GetClassInfoEx(IntPtr hInstance, [MarshalAs(UnmanagedType.LPStr)] string lpClassName, ref WNDCLASSEX lpWndClass);
+	public static extern bool GetClassInfoEx(IntPtr hInstance, string lpClassName, ref WNDCLASSEX lpWndClass);
 
 	public const UInt32 CS_DBLCLKS = 8;
 	public const UInt32 CS_VREDRAW = 1;
@@ -135,7 +137,7 @@ internal static class Program
 	[DllImport(User32, SetLastError = true)]
 	public static extern bool DestroyWindow(IntPtr hWnd);
 
-	[DllImport(User32)]
+	[DllImport(User32, CharSet = CharSet.Unicode)]
 	public static extern IntPtr DefWindowProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);
 
 	[DllImport(User32)]
```

**Comment by fandrei** [comment]
@AaronRobinsonMSFT  great, thanks.

**Comment by fandrei** [comment]
@AaronRobinsonMSFT  but it's strange that it chose ANSI version of the API by default on Windows 10, isn't it?

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT but it's strange that it chose ANSI version of the API by default on Windows 10, isn't it?

Sad, nope. The default for `CharSet` in `DllImport` is `ANSI`, so that is the [look up logic](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute.charset#remarks) - it is terribly confusing.

**Comment by jkotas** [comment]
FWIW, the [interop source generator](https://github.com/dotnet/runtime/tree/main/src/samples/LibraryImportGeneratorSample) that we are introducing in .NET 7 does not have these legacy defaults.
