### ISSUE TITLE
WASM error handling in SubtleCrypto through web worker

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#69740]
The work to enable WASM to use SubtleCrypto, https://github.com/dotnet/runtime/pull/65966, had some follow ups on how to handle error cases. Specifically, the communication channel with the web worker could be hardened to convey more errors/failures. This could be accomplished through throwing an exception or the web worker communicating a failure case explicitly.

Source hints:
- `crypto-worker.ts`
    - see `read_response` and consider throwing an `error`.
- `dotnet-crypto-worker.js`
    - The reading in of a request could be including in the `try`/`catch` in `await_request`.
    - The `await_request` function could return a bespoke "error occurred" message instead of an exception string.

See https://github.com/dotnet/runtime/issues/69741

/cc @radical @ericstj @layomia

**Comment by radical** [comment]
Another suggestion would be for the tests to *confirm* that the tests when running on browser did actually use the worker implementation.

**Comment by AaronRobinsonMSFT** [comment]
> Another suggestion would be for the tests to _confirm_ when running on browser that it did actually use the worker implementation.

I think this is being done. See [src/tests/BuildWasmApps/Wasm.Build.Tests/NativeLibraryTests.cs](https://github.com/dotnet/runtime/pull/65966/files#diff-a0e59145c9c2cce301eb73824e9b771ce8c6ecbefcc89d3ed987593c79475df4). There is a check for console output. I commented on this in the JavaScript file.

**Comment by radical** [comment]
> I think this is being done. See [src/tests/BuildWasmApps/Wasm.Build.Tests/NativeLibraryTests.cs](https://github.com/dotnet/runtime/pull/65966/files#diff-a0e59145c9c2cce301eb73824e9b771ce8c6ecbefcc89d3ed987593c79475df4). There is a check for console output. I commented on this in the JavaScript file.

Yes, but the xharness webserver is setup in two different places for Wasm.Build.Tests, and the library tests. I was just suggesting that we add some kinda confirmation for the library tests also, so it doesn't accidentally start using the fallback, and we don't find out.

**Comment by eerhardt** [comment]
Note: when fixing this, we also need to ensure that the "lock" added in https://github.com/dotnet/runtime/pull/70185 is cleared on error.

**Comment by lewing** [comment]
What is left to do here?

**Comment by radical** [comment]
> > I think this is being done. See [src/tests/BuildWasmApps/Wasm.Build.Tests/NativeLibraryTests.cs](https://github.com/dotnet/runtime/pull/65966/files#diff-a0e59145c9c2cce301eb73824e9b771ce8c6ecbefcc89d3ed987593c79475df4). There is a check for console output. I commented on this in the JavaScript file.
> 
> Yes, but the xharness webserver is setup in two different places for Wasm.Build.Tests, and the library tests. I was just suggesting that we add some kinda confirmation for the library tests also, so it doesn't accidentally start using the fallback, and we don't find out.

Only this, *if* @eerhardt thinks we should do it.

**Comment by eerhardt** [comment]
> that we add some kinda confirmation for the library tests

@radical - do you know how we would do this in the libraries tests?

**Comment by radical** [comment]
> @radical - do you know how we would do this in the libraries tests?

One simple check would be to call `Interop.BrowserCrypto.CanUseSubtleCrypto` via reflection, and compare it against an environment variable which indicates whether we are expecting to use subtlecrypto. We can do this as:
1. Add a separate test that does this
2. Or do this is all the relevant test class' .ctor . This would catch the case where some tests do use subtlecrypto, then one causes an error, and the subsequent tests would end up using the managed implementation. This can work because, once we hit an error which disables it, `Interop.BrowserCrypto.CanUseSubtleCrypto` should return `false`.3. 

https://github.com/dotnet/runtime/blob/ed2a5a1492edda956323086e6cb1a456d9418f44/src/mono/wasm/runtime/crypto-worker.ts#L120-L123

**Comment by eerhardt** [comment]
> This can work because, once we hit an error which disables the use of subtlecrypto, Interop.BrowserCrypto.CanUseSubtleCrypto should return false.

This is actually a problem in the current code, because of the following C# code:

https://github.com/dotnet/runtime/blob/8f75cc9306b0508506f60a94f94d2227ee020798/src/libraries/Common/src/Interop/Browser/System.Security.Cryptography.Native.Browser/Interop.SubtleCrypto.cs#L21

This only gets called once, and then cached in the field. So if an error happens subsequently, we don't P/Invoke back into JS code to see if `mono_wasm_crypto` is null or not.

How fast is the P/Invokes in WASM? Should this `CanUseSubtleCrypto` always call into the JS code every time it is invoked?

**Comment by bartonjs** [comment]
> This can work because, once we hit an error which disables the use of subtlecrypto, Interop.BrowserCrypto.CanUseSubtleCrypto should return false.

I dunno.  I think (in all sincerity) we should just let all crypto operations blow up.
