### ISSUE TITLE
[NativeAOT] Investigate esoteric failures in System.Linq.Expression.Tests

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#69944]
The following tests need further investigation, creating a tracking issue for now, so as to enable the large number of tests in the meantime.

1. [MethodName_TypeArgsDontMatchConstraints_ThrowsArgumentException](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/tests/Call/CallTests.cs#L553)
 ```
Assert.Equal() Failure
  Expected: (null)
  Actual:   GenericArguments[0]
     at System.AssertExtensions.Throws[T](String, Func`1) + 0x3c
     at System.Linq.Expressions.Tests.CallTests.MethodName_TypeArgsDontMatchConstraints_ThrowsArgumentException() + 0x4f
     at System.Linq.Expressions.Tests!<BaseAddress>+0xb60f8e
     at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x158
```
2. [GenericMethod](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/tests/Dynamic/InvokeMemberBindingTests.cs#L89)
```
  System.Reflection.MissingRuntimeArtifactException : MakeGenericMethod() cannot create this generic method instantiation because no code was generated for it: 'System.Dynamic.Tests.InvokeMemberBindingTests.TestBaseClass.TellType<System.Int32>(System.Int32)'.
     at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x113

```
3. [Quote_RuntimeVariables_ClosureAndLocal](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/tests/Unary/UnaryQuoteTests.cs#L453)
```
  System.Reflection.MissingRuntimeArtifactException : This object cannot be invoked because no code was generated for it: 'System.Func<System.Runtime.CompilerServices.IRuntimeVariables,System.Runtime.CompilerServices.IRuntimeVariables,System.Int32[],System.Runtime.CompilerServices.IRuntimeVariables>.Invoke(System.Runtime.CompilerServices.IRuntimeVariables,System.Runtime.CompilerServices.IRuntimeVariables,System.Int32[])'.
     at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x113
     at System.Reflection.Runtime.MethodInfos.RuntimeMethodInfo.get_MethodInvoker() + 0xa1
```
4. [VerifyMethodsCalledWithMakeGenericMethod](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/tests/TrimCompatibilityTests.cs#L17)

**Comment by MichalStrehovsky** [comment]
If you have the stack traces around, I could probably point in the right direction for fixing these.

For example, if `VerifyMethodsCalledWithMakeGenericMethod` is failing with a NullReferenceException in the foreach, the fix is to put the 3 types listed here into RD.XML (or rewrite the code to make it trimming friendly - extract the foreach block below this into a separate method that has `[DAM]` on the type and call the method for each type individually instead of doing a foreach over an array):

https://github.com/dotnet/runtime/blob/4719135a5fd6c9f22ce429ad8a211d696eae0426/src/libraries/System.Linq.Expressions/tests/TrimCompatibilityTests.cs#L19-L25
