### ISSUE TITLE
Codegen optimization of `(a << 4) | (b >> 4)`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#69983]
> @deeprobin feel free to file an issue. Related one is https://github.com/dotnet/runtime/issues/13816 (you can use PR that closed it as a foundation for your PR if you want to contribute 🙂)

_Originally posted by @EgorBo in https://github.com/dotnet/runtime/pull/69884#discussion_r884816459_

---

See https://godbolt.org/z/T8eqE9chv

### LLVM
```asm
        shr     sil, 4
        shl     dil, 4
        or      dil, sil
        movzx   eax, dil
        ret
```

### .NET JIT

```asm
       movzx    rax, dil
       shl      eax, 4
       movzx    rdi, sil
       sar      edi, 4
       or       eax, edi
       ret      
```

**Comment by hopperpl** [comment]
**_Assuming_** rsi/rdi are byte parameters (as in the example) and all high-bits therefore are zero, and additionally that the result is not masked back to byte (as in the example)... use this... otherwise all examples return nonsense.

```asm
        shr     rsi, 4                             ; can use shr sil, 4 as well, but that gives a stall
        lea     eax, [rdi * 4 + rsi]
        ret
```

This will return a masked byte value. Yes, lea is a very nice C = A + B instruction to keep both source registers. And on top, it's free, as the memory address unit is bored.

```asm
        shr     sil, 4
        shl     dil, 4
        lea     eax, [rdi + rsi]
        ret
```

But I think that's overkill for special optimization.

**Comment by deeprobin** [comment]
@EgorBo 
This is my first change that should change something about the JIT logic. How should you start?
Is there any guide for the JIT changes?

**Comment by EgorBo** [comment]
@deeprobin it turns out that this opt is not as simple for first-time-contributors (and not useful) as I thought so I'll find something better for you. For now you can start from building everything and follow steps in https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging.md

**Comment by deeprobin** [comment]
@EgorBo Thank you 👍🏼
