### ISSUE TITLE
Blazor wasm HttpClient ignores spaces at the end of URIs even if it is escaped (%20)

### ISSUE THREAD

**Issue by davidmilligan** [dotnet/runtime#70025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using HttpClient from Blazor wasm to send an HTTP request with a URI that ends with a space results in the space at the end being ignored and not sent as part of url of the actual request the browser sends. E.g. the following code:
```
await HttpClient.GetAsync("/api/test%20");
```
Incorrectly results in a request to `GET /api/test` (with no space at the end)

However, escaping spaces in other parts of the URI works just fine. E.g.:
```
await HttpClient.GetAsync("/api/test%20test");
```
Correctly results in a request to `GET /api/test test`

Also, as a workaround, an empty query can be added, and it works correctly:
```
await HttpClient.GetAsync("/api/test%20?");
```
Correctly results in a request to `GET /api/test ` (with space)

The same behavior is exhibited when using the overloads that take a `Uri` instead of `string`.

### Expected Behavior

`HttpClient.GetAsync("/api/test%20")` should result in a request to `GET /api/test%20` not `GET /api/test`

### .NET Version

6.0.202

**Comment by mkArtakMSFT** [comment]
@lewing can you please look into this? Thanks!

**Comment by radical** [comment]
This is not wasm specific, and reproducible with a regular console app.

**Comment by MihaZupan** [comment]
@radical can you share your console repro please?

**Comment by radical** [comment]
I started a local http-server, and tried:

```csharp
var hc = new HttpClient();
await hc.GetAsync("http://127.0.0.1:8080/api/test ");
```

.. and I get `"GET /api/test" Error (404): "Not found"` - no trailing space.

And with trailing `%20`: `"GET /api/test%20" Error (404): "Not found"`.

**Comment by MihaZupan** [comment]
`Uri` will strip trailing space characters: `new Uri("http://a/b ").PathAndQuery` => `/b`.
It will preserve them if you encode them yourself though: `new Uri("http://a/b%20").PathAndQuery` => `/b%20`

I think the behavior you are seeing in the console is the expected behavior. What davidmilligan is reporting is that when using the browser handler the trailing space is gone even if they encode it.

I'm not too familiar with the browser's implementation, but my guess is that the issue is here:
https://github.com/dotnet/runtime/blob/8a043bf7adb0fbf5e60a8dd557c98686bc0a8377/src/libraries/System.Net.Http/src/System/Net/Http/BrowserHttpHandler/BrowserHttpHandler.cs#L242
`Uri.ToString()` is not the format you want to send on the wire. You should be using something like the following instead:
```c#
Uri requestUri = request.RequestUri;
args.Push(requestUri.IsAbsolute ? requestUri.AbsoluteUri : requestUri.ToString());
```

**Comment by radical** [comment]
cc @pavelsavara
