### ISSUE TITLE
recreate CI - Status/Health - issue in runtime

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#701]
@dotnet/runtime-infrastructure will we have something like https://github.com/dotnet/coreclr/issues/27231 for the new repo? 
Jobs are red again ([PR testing](https://dev.azure.com/dnceng/public/_build?definitionId=649&_a=summary) and [outerloop](https://dev.azure.com/dnceng/public/_build?definitionId=655&_a=summary)) and it would be nice to have an issue where you could find known failures fast.

**Comment by trylek** [comment]
We definitely should; the only problem is that due to a miscommunication with GitHub the issues haven't yet been transferred to the new repo. I guess that in this particular case it's probably worth creating a new item right away as there's not yet an established date for the issue transfer and real issues are trickling in. What about just renaming this item to CI status / health and copying over the old content (you have already included the link to the old CoreCLR item)? I can easily do that, I just want to make sure we're in agreement on that.

**Comment by jaredpar** [comment]
@trylek 

I will just transfer that issue individually to this repository.

**Comment by jaredpar** [comment]
Issue transfered as #702.

**Comment by sandreenko** [comment]
I think that is fixed then.

**Comment by sandreenko** [comment]
Thanks, @trylek, @jaredpar.
