### ISSUE TITLE
JsonNode serialize should respect naming policy

### ISSUE THREAD

**Issue by ahdung** [dotnet/runtime#70129]
```c#
// make a json body dynamically:
var jobj = new JsonObject
{
    ["StaticProperty1"]="whatever",
    ["StaticProperty2"]="whatever",
};

if (xxx)
    jobj["DynamicalProperty1"] = "whatever";

if (anotherCondition)
    jobj["DynamicalProperty2"] = "whatever";

// post to different services
PostToService1(jobj, jsonSerializerOptions1); // service1 accept camelCase
PostToService2(jobj, jsonSerializerOptions2); // service2 accept PascalCase

So, WHY don't respect naming policy?? WHY make developer unhappy?? at least give me a choice.

**Comment by eiriktsarpalis** [comment]
I believe that's by design. `JsonNamingPolicy` is meant as a mechanism for binding JSON properties to .NET properties. `JsonNode` represents a JSON DOM and as such it doesn't support many of the .NET POCO serialization features such as `JsonNamingPolicy` and `JsonNumberHandling`. 

I would recommend either constructing separate DOM instances using different casing rules. For example you could do the following:
```C#
jobj[namingPolicy.ConvertName("StaticProperty1")] = "whatever";
```
Alternatively, you could model your JSON body using a POCO and subsequently use one of the `JsonSerializer.SerializeToJsonNode` methods. These should convert the POCO to `JsonNode` honoring the `JsonNamingPolicy` of your options instance.

cc @steveharter

**Comment by ahdung** [comment]
@eiriktsarpalis Awkward design, who tell you DOM shouldn't respect serialization things? If developer doesn't want change name case, it is his responsibility to pass the appropriate serialize options. You guys please try not to make decisions for developers, what should be and should not be, give us choices.
