### ISSUE TITLE
Loading a .NET host in a C++ program seems to change exception handling behavior

### ISSUE THREAD

**Issue by lanyizi** [dotnet/runtime#70136]
### Description

I'm trying to write a C++ program which loads the .NET host using `hostfxr.dll`.
However I noticed that after loading a .NET host, unhandled C++ exceptions no longer triggers `std::terminate`.

### Reproduction Steps

1. set a terminate handler with `std::set_terminate()`. 
2. load the .NET host (I'm using `hostfxr_initialize_for_runtime_config` of `hostfxr.dll`)
3. throw an `std::runtime_error` without any `try` / `catch`, observe that terminate handler will NOT be invoked

If step 2 is skipped (i.e. do not load the .NET host), then terminate handler will be invoked as usual

### Expected behavior

`std::terminate` should be invoked for unhandled exceptions

### Actual behavior

`std::terminate` is not invoked for unhandled exceptions.

However, manually calling `std::terminate()` can still trigger the terminate handler.
Violating a `noexcept` specification, destroying a non-joined `std::thread` etc. all still correctly invoke `std::terminate`, even after .NET host is loaded.
This issue only affects unhandled exceptions.

### Known Workarounds

Catch all C++ exceptions manually with `try` / `catch`, instead relying on the terminate handler

### Configuration

.NET version: 6.0.5
OS: Windows 10
Architecture: x86, compiled with MSVC v143

**Comment by jakobbotsch** [comment]
cc @janvorli

**Comment by janvorli** [comment]
I've found the reason - .NET runtime intentionally doesn't chain unhandled exception filters and it installs its own one (`COMUnhandledExceptionFilter`). The whole description linked below comes from a long time ago even before .NET Core 1.0 and it seems that at least some of the concerns are not valid for the current state of .NET Core. 
It seems to me that we could change the behavior so that unhandled C++ exceptions are actually chained to the C terminate handler, as such exceptions should never be escaping from runtime's native code and so we seem to have no business with those.
@jkotas what do you think?

https://github.com/dotnet/runtime/blob/7d4d8c1e323de69f9eab63bbabf7da23e8ac71e9/src/coreclr/vm/excep.cpp#L4970-L5004

**Comment by jkotas** [comment]
Chaining to previous handler sounds reasonable to me.

**Comment by janvorli** [comment]
I've verified that chaining to the previous handler fixes the reported issue. I'll create a PR soon.
