### ISSUE TITLE
ReJITID is always zero in ILToNativeMapDCStart event

### ISSUE THREAD

**Issue by pharring** [dotnet/runtime#70187]
### Description

I've been looking at how we implement "Goto Source (Def)" in PerfView for JIT-compiled frames when using ETW (i.e. _not_ EventPipe)

The mapping from stack frame to source goes via a number of steps. One important piece is mapping from { module, RVA } to { Assembly, Namespace, Type, Method, IL offset }
That's achieved by tracking three tables emitted by the CLR's rundown provider: Loader/ModuleDCStart, Method/DCStartVerbose and Method/ILToNativeMapDCStart.

The first two gets us the Assembly, Namespace, Type, Method part. The final table gives us a way to find the IL offset (which, along with the PDB, allows us to identify the line number in source).

If the method in question has been re-JIT-ted -- perhaps due to tiered compilation -- we get two entries in the DCStartVerbose and ILToNativeMapDCStart tables, as you'd expect. In the DCStartVerbose table, the ReJITID can be used to distinguish them. Typically, I see 0 for "QuickJitted" and 1 for "OptimizedTier1". However, in the ILToNativeMapDCStart table the ReJITID always appears to be 0. That makes it difficult to correlate reliably (you have to rely on heuristics).

It looks like a bug that the ReJITID is always 0 in the ILToNativeMapDCStart event.

### Reproduction Steps

I can share a .diagsession, if necessary.
1. Capture a trace with PerfView of a reasonably complex .NET 6 application (something that exercises tiered compilation)
2. Open the trace, view the CPU stacks and try to "Goto Source" for some of the JITted methods. Assuming it works at all, you're likely to end up at the wrong line number. The difference may be very subtle.

More directly (which is how I found it), take a look at the raw events in the trace using PerfView's Events view. Filter to "Method/DCStartVerbose" and "Method/ILToNativeMapDCStart" events. Find an interesting method in the DCStartVerbose table -- one that has been JITted twice for tiered compilation (has a ReJITID of 1). Then search for that MethodID in the ILToNativeMap table. You'll find that it has two entries, each with ReJITID of 0. They likely have completely different IL offsets (view the raw event data) even though they claim to be the same.

### Expected behavior

ReJITID is set correctly in the ILToNativeMapDCStart event

### Actual behavior

ReJITID is always zero

### Regression?

I suspect it's been that way forever -- it's just that tiered compilation only recently became widely available.

### Known Workarounds

None

### Configuration

.NET 6, Windows, x64

**Comment by tommcdon** [comment]
@davmason @noahfalk

**Comment by davmason** [comment]
Looking at the code https://github.com/dotnet/runtime/blob/45589f2a1ea20b4bce66058994de52f317716558/src/coreclr/vm/eventtrace.cpp#L6891-L6915

We correctly set the ID for the non-rundown event but it's hardcoded to 0 for the rundown events. I haven't thought about it too much but at the surface level it seems like a one line type of fix.

**Comment by pharring** [comment]
@davmason thanks for looking at this. 
FWIW, the link to code led me to this commit: https://github.com/dotnet/runtime/commit/3f7a996ffeead601a20a43c36cea7928a3ad4c24 which appears to be replacing ReJITID with NativeCodeID. I know almost nothing about the implementation and history here, so please take this with a grain of salt. I just mention it because it seemed relevant. If I've misunderstood the purpose of the ReJITID field, or if PerfView/TraceEvent needs to be modified to understand NativeCodeID, then please let me know. At the end of the day, I just want "Goto Source" to work reliably and accurately every time.

**Comment by davmason** [comment]
@kouvel is there any compat reason to hard code the rundown ILToNativeMap events to 0? I can't think of any reason so this seems like an easy fix for 7

**Comment by kouvel** [comment]
I don't know why it was hardcoded to 0, it seems to have been like that from the beginning in the history

**Comment by noahfalk** [comment]
I can offer a little background on why the ids and naming is confusing. In the history of developing CLR the ICorProfiler ReJIT feature came first and tiered compilation came later. ICorProfiler ReJIT allows the profiler to change the IL which has the consequence of changing the jitted code as well and for a period of years that was the only way to do it (ignoring ENC). This meant that IL version == native version == rejitId. When tiered compilation entered the scene that invariant broke because we could change the native version of the code without changing the IL version. At this point we had the term rejitID already exposed in various places, in some cases refering to the concept of IL version and in others refering to the concept of native code version. When tools read our ETW events via TraceEvent, the name of the parameter is exposed to them in the public API ([example](https://cs.github.com/microsoft/perfview/blob/0527048440767c382867e4c08ece226cde01a7dd/src/TraceEvent/Parsers/ClrEtwAll.cs.base?q=ReJITID#L5484)) so we chose not rename it even though it may be getting used for different purposes.

My best understanding at the moment is that rejitId, when it appears in MethodDCStart, refers to native code version and when it appears in ILToNativeMap it refers to IL version (of course given that it is always zero may mean it is broken regardless). If we wanted to change its meaning in ILToNativeMap we should confirm that this doesn't cause problems for PerfView or VS profiler source mapping. Another alternative would be to add a new parameter to event named 'nativeCodeVersion'. Regardless of what else we do it would probably be helpful to add some comments clarifying what is going on. Hope that helps!

**Comment by davmason** [comment]
@pharring this is fixed in main now, the sooner you can verify it fixes your scenario the better since we are getting close to shutting down for 7.0
