### ISSUE TITLE
System.Globalization.CultureInfo compatibility issues

### ISSUE THREAD

**Issue by Provru** [dotnet/runtime#70342]
If the following code is written in a Windows environment, some methods will get data from NLS instead of ICU.

```C#
var aaa = CultureInfo.GetCultureInfo("ja-JP");
Console.WriteLine($"Symbol:{aaa.NumberFormat.CurrencySymbol}");

var bbb = new CultureInfo("ja-JP", false);
Console.WriteLine($"Symbol:{bbb.NumberFormat.CurrencySymbol}");

var ccc = new CultureInfo("ja-JP", true);
Console.WriteLine($"Symbol:{ccc.NumberFormat.CurrencySymbol}");

var ddd = CultureInfo.CurrentCulture;
Console.WriteLine($"Symbol:{ddd.NumberFormat.CurrencySymbol}");

// output
// Symbol:￥(EFBFA5)
// Symbol:￥(EFBFA5)
// Symbol:¥(C2A5)
// Symbol:¥(C2A5)
```

The yen sign retrieved from NLS is half-width, but the yen sign retrieved from ICU is full-width, so there is no consistency.
It may be that NLS is used for backward compatibility, but it would be better to change the method to use only ICU.

**Comment by tarekgh** [comment]
@Provru 

did you mean the output from your code should be the following instead? 

```
// output
// Symbol:¥(C2A5)       <-- CultureInfo.GetCultureInfo("ja-JP");
// Symbol:￥(EFBFA5)    <--  new CultureInfo("ja-JP", false);
// Symbol:¥(C2A5)       <--  new CultureInfo("ja-JP", true);
// Symbol:￥(EFBFA5)    <-- CultureInfo.CurrentCulture;
``` 

When setting `ja-JP` as the default locale on your machine and then calling `CultureInfo.GetCultureInfo("ja-JP")` or calling `new CultureInfo("ja-JP", true)`, this means asking for getting the user settings, which is picked up from the machine (and not from the ICU). Usually picked up from `HKEY_CURRENT_USER\Control Panel\International\sCurrency`. Users are free to set whatever symbols they like there. So, this is a behavior we cannot change. 

Developer can still control that by not creating culture the way picks the user setting which will ensure always getting the ICU data at that. time.

CC @jefgen @shawnsteele from Windows side if it is possible to have Windows use the full width currency symbol instead of the half width.
