### ISSUE TITLE
Biginteger logarithm error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#70359]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Biginteger-logarithm-error/10018992)._

---
       Hello I am getting error working with biginteger logarithm. My sample code below. 
 Dim BigInt As BigInteger = "22758377872047801994499502579404088515069830671470709664446026543569013625861699705718264701424487993283566718344462216931566145674100201708773768933908779361002052920749"
        Dim Base = 15
        Dim Exp As Double = BigInteger.Log(BigInt, Base) 'This is integer 144   
        Dim Pwr = BigInteger.Pow(Base, Exp) 'This must be equal to BigInt 
        Dim Div As BigInteger = BigInteger.Divide(BigInt, Pwr) 'Result is 0 but this must be 1
        Dim Subs = BigInteger.Subtract(BigInt, Pwr) 'This must be always positive but this is negative

---
#### Tracy Wang [MSFT] on 4/21/2022, 03:07 AM: 

(private comment, text removed)
#### Guven Acar on 4/21/2022, 10:21 PM: 

(private comment, text removed)
#### Guven Acar on 4/22/2022, 00:46 AM: 

(private comment, text removed)
#### Feedback Bot on 4/22/2022, 04:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tannergooding** [comment]
There are some broken user expectations here. The code given is equivalent to the following C# code, which I'll use to explain the issue:
```csharp
var BigInt = BigInteger.Parse("22758377872047801994499502579404088515069830671470709664446026543569013625861699705718264701424487993283566718344462216931566145674100201708773768933908779361002052920749");
var Base = 15;
var Exp = BigInteger.Log(BigInt, Base); // This is integer 144
var Pwr = BigInteger.Pow(Base, (int)Exp); // This must be equal to BigInt
var Div = BigInteger.Divide(BigInt, Pwr); // Result is 0 but this must be 1
var Subs = BigInteger.Subtract(BigInt, Pwr); // This must be always positive but this is negative
```

`BigInt` is exactly as given and there are no issues. The same goes for `Base`.

`Exp` is computed using `BigInteger.Log` and there are a few "gotchas" here. The first being that `Base` is taken as a `double` and so there can be precision loss for very large `base` (any value over `2^52`). The second being that this is internally computed using `double` as well, which is in fact lossy for values over `2^52`. Since `BigInt` is over `2^52` we have some rounding error here. In particular the value that the `Log` is being computed for is `2.2758377872047801E+169`

The infinitely precise result of `log15(BigInt)` should be `143.99999999999999999999873285907803497867300404944684964177812480...` and so by normal `floating-point` to `integer` rounding rules this should return `143`. Due to the rounding loss converting `BigInt` to double, we end up with a slightly larger value that returns `144` instead. -- This is something that could (and likely should) be fixed, but it is complex and expensive to do since it requires avoiding precision loss for the intermediate floating-point format -or- doing a correct and purely integral equivalent.

Because `144` is computed rather than `143.99999...`, `Pwr` ends up being `22758377872047801994577597525864318671123930960450575616711044149860905790692622126405688710575851480883426725904701805200947548925294317001544186496175825595855712890625`. This is a correct result given `15^144`.

This is where the algorithm and expectations are broken. Computer types are not infinitely precise and so there is imprecision introduced here. This means that you may not get back exactly `BigInt` and the remaining expectations are incorrect.
