### ISSUE TITLE
Implement INumber<T> for System.Numerics.BigInteger and System.Numerics.Complex 

### ISSUE THREAD

**Issue by hjrb** [dotnet/runtime#70404]
This would enable generic implementations for Matrix<T>, Vector<T> etc. based on these numeric types.

**Comment by tannergooding** [comment]
As indicated above, `BigInteger` already implements `INumber<BigInteger>` in the latest source. Likewise, `Complex` already implements `INumberBase<Complex>` and does so because it is not comparable and therefore `INumber<Complex>` doesn't make sense. `INumberBase` includes `MaxMagnitude` and `MinMagnitude` functions and so those are also available on `Complex`.

These will be publicly available once .NET 7 Preview 5 is published.
