### ISSUE TITLE
createdump failing to capture a dump during force quit of VSMac

### ISSUE THREAD

**Issue by sgmunn** [dotnet/runtime#70696]
### Description

Force quitting VSMac on x64 (Monterey) machine results in a failed attempt by createdump to produce a crash report.

createdump diagnostic log:
https://gist.github.com/sgmunn/bd459c5e7037242d0232a91528f0b6e3

### Reproduction Steps

Start VSMac on an x64 machine
Force Quit
View logs in ~/Library/Logs/VisualStudio/17.0, createdump log messages in the IDE log and we see fail messages

### Expected behavior

a crash report is produced

### Actual behavior

createdump fails with a message similar to

CLRDataCreateInstance(ICLRDataEnumMemoryRegions) FAILED 80131c4f
Gathering state for process 4195
Crashing thread 00011923 signal 0000000f

### Regression?

yes

### Known Workarounds

None

### Configuration

x64. Machine happens to be Monterey 12.4 but given we are not getting telemetry for x64 in the "catch all" bucket we don't believe it to be specifically Monterey.

**Comment by mikem8361** [comment]
The DAC initialization failure HRESULT 0x80131c4f (CORDBG_E_MISSING_DEBUGGER_EXPORTS) are happening when the read memory failures for the DAC global table symbol or the DAC global table itself. These read memory failures are caused by the target process being terminated before createdump is finished.
