### ISSUE TITLE
Test failure: Interop\\IJW\\CopyConstructorMarshaler\\CopyConstructorMarshaler\\CopyConstructorMarshaler.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#70791]
https://dev.azure.com/dnceng/public/_build/results?buildId=1825350&view=ms.vss-test-web.build-test-results-tab&runId=48383318&resultId=101751&paneView=debug

Pipeline: runtime-coreclr jitstress2-jitstressregs
job: `coreclr windows x64 Checked jitstress2_jitstressregs1` and `coreclr windows x64 Checked jitstress2_jitstressregs8`

Example:
```
C:\h\w\A17C08F5\w\ADD6092B\e>type C:\h\w\A17C08F5\w\ADD6092B\u\SetStressModes_jitstress2_jitstressregs8.cmd 
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=8
...
    Interop\IJW\CopyConstructorMarshaler\CopyConstructorMarshaler\CopyConstructorMarshaler.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\A17C08F5\w\ADD6092B\uploads\Reports\Interop.IJW\CopyConstructorMarshaler\CopyConstructorMarshaler\CopyConstructorMarshaler.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A17C08F5\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CopyConstructorMarshaler.dll 
      Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 2
      Actual:   44
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63
         at CopyConstructorMarshaler.CopyConstructorMarshaler.Main(String[] args)
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
```

Related issue? https://github.com/dotnet/runtime/issues/67372

@AaronRobinsonMSFT @jkoritzinsky @elinor-fung Given that https://github.com/dotnet/runtime/issues/67372 looks similar, and was disabled, does this look like a JitStress issue (since it happens during a JitStress run), or is there a general interop failure here that the interop team should investigate?

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall We disabled the referenced issue because it was only occurring on arm32, but if it is occurring elsewhere it is possible there are underlying issues. This is something we can investigate but it might be faster for someone from the JIT to let us know what invariant is being invalidated. If that can be done we are likely fine fixing the problem if it is something we are doing that is odd.

**Comment by jkotas** [comment]
It may be regression introduced by my change #68186. I will take a look.

**Comment by kunalspathak** [comment]
In the test, we call `B`'s ctor but fail to initialize `A`'s field (may be because it is marked private) and that makes the use of garbage value to return. 

This happens even without any jitstressregs, but since the stack location we access with `JitStressRegs` make this problem visible as seen in left (without JitStressRegs) and right (with JitStressRegs)

![image](https://user-images.githubusercontent.com/12488060/177659124-7a1e619b-0b80-4adc-91f8-a276e24b3b8c.png)

Thanks @AaronRobinsonMSFT for your help in narrowing down the problem

**Comment by kunalspathak** [comment]
Update: We initialize `copyCount` of `A`, but remove the initialization of `B`'s `bCopyCount` in `optRemoveRedundantZeroInits()`.


```
*************** In optRemoveRedundantZeroInits()
Marking V07 as having an explicit init

removing useless STMT00009 ( INL01 @ 0x007[E-] ... ??? ) <- INLRT @ 0x000[E-]
N003 (  5,  6) [000035] -A--G---R--                         *  ASG       int   
N002 (  3,  4) [000029] D---G--N---                         +--*  LCL_FLD   int    V07 tmp3         [+4]
N001 (  1,  1) [000033] -----------                         \--*  CNS_INT   int    0
```
