### ISSUE TITLE
PAX Tar timestamps from extended attributes parsing may not be a `double`, but `long.long`

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#70801]
Discussion started here: https://github.com/dotnet/runtime/pull/70325#discussion_r895853560

The pax timestamp that is stored in the extended attributes section can be a string representing a number with a dot, but it most likely is not a double, but a long, a dot, and another long.

Since the discussion in that issue was not related to the problem the PR was fixing, I am opening a new issue to track that fix separately.

**Comment by carlossanlop** [comment]
Tarek helped me figure it out: The original parsing is correct, we are dealing with an actual `double`. The decimal part is _fractions of seconds_.

Here is a stackoverflow thread asking about such timestamp: https://stackoverflow.com/questions/21696323/epoch-time-with-dot-1391759952-7056 . Notice that the decimal part is larger than 1000, which means it cannot be milliseconds. And the answer below is "fractions of seconds".

Also, the example in the FreeBSD tar manual is: `25 ctime=1084839148.1212\n` which again, means it is not milliseconds.

**Comment by bartonjs** [comment]
GNU TAR writs the value as (more or less)  `sprintf(buf, "%ld.%d", t.tv_sec, t.tv_nsec)`, which means we are flirting with the maximum precision a double can represent, and it gets worse in 2038.  (It's not that simple of a print since 9 ns is "000000009").

GPL warning: https://git.savannah.gnu.org/cgit/tar.git/tree/src/misc.c#n443


If we're concerned with faithfully roundtripping the values, we need to parse it as two different integers, do FromUnixTimestamp on the first one, then add as nanoseconds for the second.
