### ISSUE TITLE
Expression.ToString() does not show milliseconds for DateTime properties

### ISSUE THREAD

**Issue by HypeillingerChillinger** [dotnet/runtime#70935]
### Background and motivation

```C#
        var date = new DateTime(2022, 3, 3, 2, 2, 2, 222, DateTimeKind.Utc);
        var expConstant = Expression.Constant(date, typeof(DateTime));
        var xParameter = Expression.Parameter(typeof(TestEntity), "x");
        var dateProperty = Expression.PropertyOrField(xParameter, nameof(TestEntity.DateTimeTest));
        var notEqualExp = Expression.NotEqual(dateProperty, expConstant);
        var lambda = Expression.Lambda<Func<TestEntity, bool>>(notEqualExp, xParameter);
        var unfortunatelyNoMilliseconds = lambda.ToString(); // "x => (x.DateTimeTest != 03.03.2022 02:02:02)"
```

```lambda.ToString()``` does not show the milliseconds. 
Result is ```"x => (x.DateTimeTest != 03.03.2022 02:02:02)"```

### API Proposal

I suggest to use .ToString("o") internally to provide all necessary information of a ```DateTime``` value.

### API Usage

No proposal here.

**Comment by Clockwork-Muse** [comment]
Alas, this isn't possible - this would require special casing for a specific type, because it's calling the base `ToString()` for all class types.  It would also be a (somewhat - value is culture specific) breaking change because of the change in format.

Why do you want this change?  Because the value is culture specific you can get it to output the format you want by switching the context to using a specific culture (hacky, but should work).  If you have more specific requirements, though, you may want to implement your own formatter, or something.

**Comment by HypeillingerChillinger** [comment]
I wanted to use it for tests to proof that the created expression is correct. Feel free to close this if you like I can work around that one.

**Comment by Clockwork-Muse** [comment]
> I wanted to use it for tests to proof that the created expression is correct. Feel free to close this if you like I can work around that one.

Normally you shouldn't be doing this by comparing the `ToString()` output (which, besides culture issues for things like dates, may or may not insert parenthesis where you expect, for example), you'd manually create the "expected" expression tree and compare against your actual generated tree structurally.
That's if you even care about the structure of the expression, as opposed to the results of calling it, which is usually way easier to test, and way more relevant.

**Comment by cston** [comment]
Closing, given the alternatives suggested.
