### ISSUE TITLE
DateTimeOffset.Now TimeZone data impacts Android startup

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#71004]
### Description

Reviewing a [customer issue](https://github.com/jonathanpeppers/maui-profiling/issues/16), we noticed any accidental usage of `DateTimeOffset.Now` has a noticeable impact to startup:

![image](https://user-images.githubusercontent.com/840039/174640114-0de238f2-441d-43de-a1f8-39e518d13f1b.png)

277ms is a lot of time given that the total startup time is 182ms of a `dotnet new android` app in `Release` mode. (It's also possible that 277ms is somewhat inflated by tracing)

If I record a custom AOT profile (to avoid JIT-ting), the time is better, but still shows up:

![image](https://user-images.githubusercontent.com/840039/174640186-5cc2c6a7-38b5-4a32-9b53-d8a9e6b162f6.png)

In this case, it would be better to use `UtcNow`, but I could see a lot of developers might run into this on accident. Is there anything we could do to improve this? Thanks!

### Reproduction Steps

1. `dotnet new android`
2. Open `MainActivity.cs` and put `_ = DateTimeOffset.Now;` in the `OnCreate()` method.
3. Build/run with `dotnet build -c Release -t:Run`

### Expected behavior

`DateTimeOffset.Now` doesn't significantly slow down an Android app.

### Actual behavior

`DateTimeOffset.Now` does seem to significantly slow down an Android app.

### Regression?

No

### Known Workarounds

Use `UtcNow`?

### Configuration

I tested this with the .NET 6.0.400-preview.22301.10 SDK, and the SR 1 version of .NET MAUI.

### Other information

Here is `dotnet trace` output:

[datetimeoffset.now.zip](https://github.com/dotnet/runtime/files/8942094/datetimeoffset.now.zip)

One is default settings (code path is JIT), and the second is using an AOT profile (code path is AOT).

**Comment by Clockwork-Muse** [comment]
> `DateTimeOffset.Now` doesn't significantly slow down an Android app.

It's not `DateTimeOffset.Now` - it's everything under that to get the (local) offset that's the real culprit.  The moment you need a localized value of some sort you're going to incur the cost to get the necessary info.

**Comment by steveisok** [comment]
I suspect most of the cost is due to parsing the timezone xml file on device.

**Comment by mdh1418** [comment]
`DateTimeOffset.Now` should not be equal to `DateTimeOffset.UtcNow` unless the device/emulator's system settings are set to be in UTC.

I took a look at the previous behavior (also the existing behavior for non Android Unix platforms) prior to https://github.com/dotnet/runtime/pull/54845 (≈which overhauled the previous behavior and followed the mono/mono implementation that had performance in mind) and it returns Utc because it fails to find the timezone data, and by consequence, it doesn't find the correct current timezone that would represent `DateTimeOffset.Now`. Here is a speedscope of a sample where I ported over the previous behavior https://gist.github.com/mdh1418/6f4671548bcadb4c8ec7563f99e26abe. It would make sense that `DateTimeOffset.Now` is quick **67.89ms!**  if it fails fast and returns a default.

I made modifications to have the previous behavior look for the tzdata file in the correct locations (noted in https://github.com/dotnet/runtime/pull/54845 description), and the time for `DateTimeOffset.Now` is **690.38ms** https://gist.github.com/mdh1418/6df6e249bb66f1caca3f10cf01865fdb. However, even with the right directories (and therefore a tzdata file), it fails to find the proper timezone and defaults to returning Utc. 

Running the current behavior, it took **555.76ms**. https://gist.github.com/mdh1418/e037763acd0cfa4ece6d046f34186223

Both the current and previous behavior end up calling `GetTimeZoneFromTzData`, which is measured to be relatively similar at 209ms and 208ms.

The current behavior instantiates an AndroidTzData instance (loading all of the tzdata into relevant arrays for faster lookup) and takes **221ms**, a significant portion of which is due to filtering out Backward TimeZone IDs https://github.com/dotnet/runtime/pull/64028, which fixes an issue where duplicate IDs show up. Removing the filtering, `DateTimeOffset.Now` takes **386.58ms** https://gist.github.com/mdh1418/bc5ddcd343375dab598d9f4f464aac49.

I ran these in Debug configuration, so the times are worse than in release, but relatively speaking, the new behavior performs better and actually returns the correct `DateTimeOffset.Now`.

I'll look more into the logic to see if theres some more time savings to be made, but I agree that if the actual local time is to be obtained, the data needs to be loaded, and as stated before, the previous mono/mono implementation had performance in mind. Not sure if @grendello has any other ideas of ways to speed this up or if its taking longer than expected. 

Its worth investigating if `GetTimeZoneFromTzData` is optimal as that takes a significant portion of the time.

**Comment by grendello** [comment]
@mdh1418 I have one idea in two variants which might make startup less affected by this, however it would likely require some changes in both XA and MonoVM.  Namely, XA startup code is Java and the JavaVM already has all the tz data loaded and the current tz selected when it calls into our code. We could grab the current local time and pass it to the runtime as the default value for `DateTimeOffset.Now` (as well as `DateTime.Now`). In addition to the current time in Java, we also obtain the value of the kernel monotonic clock (by calling `clock_gettime (CLOCK_MONOTONIC, ...)`) and pass that to the runtime as well. With these values, when `*.Now` is first called, we can call `clock_gettime` again, add it to the stored default `*.Now` value and return current time with reasonable accuracy (the difference between the actual time and the calculated one should be more than a millisecond, usually less than that most probably). At the same time, MonoVM kicks off the process of finding and retrieving the current tz data in a background thread, so that the next time `*.Now` is called we get the actual time.

The other variant would be to use `*.UtcNow` and obtain, in Java, the current zone offset from UTC and make the first call to `*.Now` use that to calculate the time. The rest would remain the same. The previous idea, even though more complicated, might be faster (depending on what Java does when requesting the offset vs the current local time - it would have to be measured).

**Comment by rgroenewoudt** [comment]
An idea might be to introduce a fast path to `TimeZoneInfo.GetLocalUtcOffset()` to not initialize the timezones but directly returns the offset from Android.

**Comment by grendello** [comment]
https://developer.android.com/reference/java/time/ZoneOffset?hl=en#getTotalSeconds() could also be used, whichever is faster

**Comment by Clockwork-Muse** [comment]
... That gets you the offset in effect at the instant you start.

It's immediately stale - the offset could change in the next tick/nanosecond, for any or all of the following reasons:
 - The timezone you're in observes Daylight Savings Time, and there was a DST change.
 - The timezone you're in is changing the offset rules, and it was time for the rules to change (somewhat rare, but rules are updated multiple times a year).
 - Because this is Android, the device is likely cell-enabled, and you physically moved to a different timezone (that is, you've connected to a cell tower configured for a different timezone).

Getting the **current offset** is insufficient - you need to have a complete enough set of rules to know when it might change.  
The runtime _probably_ doesn't have enough information to decide if any next call to `DateTime.Now` will happen sufficiently late so as to get the value updated from the background (as opposed to just blocking for a significant portion of that time, at which point you're probably not significantly better off using any of these tricks).

**Comment by grendello** [comment]
@Clockwork-Muse we would notice the tz change, since we install a [broadcast handler](https://github.com/xamarin/xamarin-android/blob/a4a1c58642c22af60231c81eb567da4f057d93c6/src/java-runtime/java/mono/android/MonoPackageManager.java#L33-L36) during startup. The likelihood of that happening within the ~180ms of the application startup is small enough to allow this to happen, IMO. Also, this would only serve to respond immediately to the very first `.Now` request in the application startup sequence and whether or not the application would call `.Now` during that time, the runtime could always initialize TZ data in a background thread once the managed land is running. 

Since the chance of the scenario you described is indeed very low and the optimization would benefit every one, I think it's OK to accept that risk.

**Comment by grendello** [comment]
> Getting the **current offset** is insufficient - you need to have a complete enough set of rules to know when it might change. The runtime _probably_ doesn't have enough information to decide if any next call to `DateTime.Now` will happen sufficiently late so as to get the value updated from the background (as opposed to just blocking for a significant portion of that time, at which point you're probably not significantly better off using any of these tricks).

It doesn't need to know that.  Until the full tz data is available it can return the stored value + `clock_gettime (CLOCK_MONOTONIC)` offset. When the tz data is loaded, a flag is set (atomically) and from that point on `.Now` works in its usual way.

**Comment by grendello** [comment]
We could also use @rgroenewoudt's idea and provide a p/invoke that'd use JNI to call https://developer.android.com/reference/java/time/ZoneOffset?hl=en#getTotalSeconds(), which would make the performance a bit worse than the above ideas of mine, but likely still faster than the current code.  The rest of the logic (initializing tz data in a background thread after the first call to `.Now`) could stay the same.

**Comment by jonpryor** [comment]
Perhaps I am mis-reading @mdh1418 's [comment](https://github.com/dotnet/runtime/issues/71004#issuecomment-1171848178), but why can't we just use the mono/mono implementation?  I don't see an explicit statement for why the mono/mono code -- which was working on Android -- cannot be used anymore.

**Comment by jonpryor** [comment]
Looks like #54845 was in fact a "port" of the mono/mono implementation.  My bad.

**Comment by steveisok** [comment]
> @rgroenewoudt `TimeZoneInfo.GetLocalUtcOffset()` could use the value we'd store after obtaining it from the API in the previous comment. Ideally, we should avoid doing any JNI during startup, if possible. Local timezone offset could become a parameter to `monovm_initialize_preparsed` (possibly a member of the `MonoCoreRuntimeProperties` struct?)

If that doesn't cost too much, I would prefer this option.

**Comment by grendello** [comment]
> > @rgroenewoudt `TimeZoneInfo.GetLocalUtcOffset()` could use the value we'd store after obtaining it from the API in the previous comment. Ideally, we should avoid doing any JNI during startup, if possible. Local timezone offset could become a parameter to `monovm_initialize_preparsed` (possibly a member of the `MonoCoreRuntimeProperties` struct?)
> 
> If that doesn't cost too much, I would prefer this option.

I'm counting on Java being able to access the tz data quicker than us, which should be the case.

Also, this isn't much, but [this code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.Android.cs#L106-L110) may be kicking off ICU loading. It might be worth doing something similar to what @jonathanpeppers did in [this PR](https://github.com/xamarin/java.interop/pull/1001). Another good suggestion from @jonathanpeppers that came up in a discussion about this issue on Discord was that [tz code](https://github.com/dotnet/runtime/blob/7b89c8634ead6ea88ddcae32e3145b250f3d687d/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.Android.cs#L457) could use ArrayPool to not only save memory but also probably speed up the code a bit.
