### ISSUE TITLE
Use modern-themed buttons in the host error message box.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#71288]
The recent blog post with the apphost improvements features an error message box for the cases when the appropriate runtime was not found.

![image](https://user-images.githubusercontent.com/12659251/175784832-7f56712e-ad54-4c78-aa91-83864f41713e.png)

As seen in the screenshot, the message box uses old-style buttons. They could be made more modern [pretty easily](https://docs.microsoft.com/en-us/windows/win32/controls/cookbook-overview). This is how it would look like:

![image](https://user-images.githubusercontent.com/12659251/175793286-a8cb7942-1557-4c83-a7ee-b63ac0d6eceb.png)

**Comment by Symbai** [comment]
This has been suggested before and it has been dropped by the words of "its not worth it". Which both is also stated by @richlander in the blog post in the comment section, see https://devblogs.microsoft.com/dotnet/dotnet-apphost-improvements/#comment-15937

**Comment by teo-tsirpanis** [comment]
I've seen the issue, I'm not asking for a task dialog, just the existing message box to be modernly themed.

**Comment by richlander** [comment]
I changed my mind based an abundance of feedback. Let's try again for .NET 8.

I added a (currently closed) line item at https://github.com/dotnet/runtime/issues/71284. I added yours there, too, @teo-tsirpanis.

**Comment by richlander** [comment]
I'll leave it to @elinor-fung if she thinks something targeted can be done with the current implementation for .NET 7. I'm quite happy with the improvements we made for .NET 7 and to wait for considering a broader set of changes in .NET 8.

**Comment by reflectronic** [comment]
Improving the appearance of MessageBox as suggested requires using ComCtl32 version 6, which is also what blocked the use of Task Dialog. @vitek-karas's [workaround](https://github.com/dotnet/runtime/issues/3816#issuecomment-617426068) would work for both, but I do not think the idea was explored in full to ensure that it's appropriate for apphost.

**Comment by richlander** [comment]
I could imagine custom hosts. For example, for WinUI apps, a host that loaded and used WinUI might make sense. It might not make sense for all scenarios, but might be great for some.

**Comment by teo-tsirpanis** [comment]
I didn't know how big of a problem referencing ComCtl 6 would be, I thought it was something easy. I was going to say "why not do what WinForms' `Application.EnableVisualStyles()` does?", but then I realized that [it creates a temporary manifest file on the disk](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs#L84), which is too much for the host in an error case.

If the host _happens_ to have a custom manifest with ComCtl 6, it would "just work", right? In this case this issue can be closed and superseded by the bigger Task Dialogs effort.

**Comment by richlander** [comment]
The host team's viewpoint is that the host shouldn't bring any additional dependencies or files. That's pretty justifiable, IMO. Custom hosts could do anything. That's basically it.

**Comment by vitek-karas** [comment]
> If the host happens to have a custom manifest with ComCtl 6, it would "just work", right?

Correct (although I didn't test this), you can add this manifest to your app as a native resource (and will be copied/applied to the host).

The challenge is how to enable ComCtl6 dynamically without writing to disk and only where we're about to fail. (and without needed any other files around). There are some ideas, but we haven't really looked into the details yet. As @richlander noted, https://github.com/dotnet/runtime/issues/71284 adds this into the list for .NET 8 proposal.

**Comment by richlander** [comment]
An easy first step is for someone to build an app (Windows Forms, WPF, ...) that demonstrates the desired UX.

**Comment by deeprobin** [comment]
> An easy first step is for someone to build an app (Windows Forms, WPF, ...) that demonstrates the desired UX.

How about something like this?
![grafik](https://user-images.githubusercontent.com/10373452/188289055-50ce7b5e-692e-497d-b815-850c9352b584.png)
[DotnetHost.zip](https://github.com/dotnet/runtime/files/9483456/DotnetHost.zip)

**Comment by elinor-fung** [comment]
I was actually playing with this a bit last week too. Didn't try anything with the .NET icon, since we don't include that with `apphost` to keep its size down and I don't think we want to introduce it just for this error.

Newer visual style via embedded manifest (not as exe/dll manifest) and activation context:
+1kB to Windows `apphost`
![image](https://user-images.githubusercontent.com/47805090/188761502-7a60bf3e-09a6-4a17-b7de-83c0ac868ff4.png)

TaskDialog (also requires the activation context) - I think we'd need this to get a clickable link:
+2kB to Windows `apphost`:
![image](https://user-images.githubusercontent.com/47805090/188761623-e789f860-acd8-42eb-8bbc-c0b9f6875d88.png)

Thoughts?

**Comment by deeprobin** [comment]
> Didn't try anything with the .NET icon, since we don't include that with apphost to keep its size down and I don't think we want to introduce it just for this error.

The host size is basically decisive in the single file host.
For the normal apphost, I think we should prioritize convenience/UX over size.

> TaskDialog (also requires the activation context) - I think we'd need this to get a clickable link:
+2kB to Windows apphost:

Looks also good to me. But I like the icon ;)

**Comment by vitek-karas** [comment]
Agree that we should not include the icon due to its size.
If we were to use TaskDialog I would remove the red cross icon - feels too jarring to me. I think a big (which this will be) dialog clearly explaining what the problem is looks better.
With TaskDialog I would also include the link the dialog redirects to in its text as a link (getting the URL the dialog points to is tricky since when opened it immediately redirects and it might be useful).

I'm obviously a terrible designer, but if we want nicer, we could do something like this:
![image](https://user-images.githubusercontent.com/10670590/188822267-f44465fa-6db3-42d5-80b8-5e6956027194.png)

And this is how it looks when expanded:
![image](https://user-images.githubusercontent.com/10670590/188822379-0c381313-1785-43c1-8279-8ad060c69b24.png)

**Comment by elinor-fung** [comment]
Another variation could be to keep the things like architecture and version in the main content and have the 'see details' only include the full download link. Or show it with the details expanded by default (but the full - usually long - link shown by default might be a bit noisy). I know we've gotten feedback in the past about wanting to have architecture/version clearly called out, so it might be good to keep those shown by default.

**Comment by vitek-karas** [comment]
That sounds good as well - I was kind of hoping that the architecture/version should be handled by the website - since mostly it's needed to pick the right URL on the existing website. But either way works great.

**Comment by elinor-fung** [comment]
https://github.com/dotnet/runtime/pull/76762 has just the visual style / modern-themed buttons portion of this. It is the change in the issue's original description and would be a prerequisite for using the win32 task dialog (for clickable links, download button, expandable details, etc.)

**Comment by TheDusty01** [comment]
I know this already has a PR but the new TaskDialog style fits more to Windows 7 or 8 than to 10 and 11 (looks way better than the dialog before though).

Since the goal is to make the dialog look more modern, WinUI 3 would be better here imho. It fits more to Windows 10 & 11 and also has the most modern style.
I'm curious, is there a reason on why this isn't considered or possible?

A sample WinUI 3 MessageDialog:
![image](https://user-images.githubusercontent.com/21290407/212373509-2d37e584-700d-45bd-ae30-02b69b2adcfe.png)

**Comment by elinor-fung** [comment]
Since the apphost that shows the dialog is part of every .NET application, one of its basic tenets is to be as lightweight as possible. WinUI 3 uses the Windows App SDK runtime and would mean deploying and bootstrapping those runtime packages. That's not a requirement/dependency we'd want, so WinUI is not really an option for the host, unfortunately.
