### ISSUE TITLE
[NativeAOT]  Data Contract Serializer

### ISSUE THREAD

**Issue by AhmedZero** [dotnet/runtime#71350]
### Description

in an older version of NativeAOT it works well, but when I upgrade NativeAOT to the last version. it doesn't work well, I don't know what's the reason if it's problem with .NET 7 or NativeAOT.

### Reproduction Steps

```C#
using System.Drawing;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace MyApp // Note: actual namespace depends on the project name.
{
  
    public unsafe class Program
    {
        [DataContract]
        public class DrawingProperties
        {
            [DataMember]
            public Color TestColor = Color.Red;

        }
        public static void Save(DrawingProperties obj, string path)
        {
            
                using FileStream stream = new FileStream(path, FileMode.OpenOrCreate);
                DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(DrawingProperties));

                serializer.WriteObject(stream, obj);

            
        }
        public static DrawingProperties Load(string path)
        {
            using FileStream stream = new FileStream(path, FileMode.OpenOrCreate);
            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(DrawingProperties));

            return (DrawingProperties)serializer.ReadObject(stream);

        }
        public static DrawingProperties DrawProp = new();

        static void Main(string[] args)
        {
            Console.WriteLine($"R: {DrawProp.TestColor.R} G: {DrawProp.TestColor.G} B: {DrawProp.TestColor.B}");
            Save(DrawProp, "config.json");
            DrawProp = Load("config.json");
            Console.WriteLine($"R: {DrawProp.TestColor.R} G: {DrawProp.TestColor.G} B: {DrawProp.TestColor.B}");

            Console.ReadKey();
        }
 
    }
}
```

### Expected behavior

```
R: 255 G: 0 B: 0
R: 255 G: 0 B: 0
```

### Actual behavior

```
R: 255 G: 0 B: 0
R: 0 G: 0 B: 0

```

### Configuration

.NET NativeAOT  7.0.0-preview.6.22327.1
Windows 11 X64

**Comment by MichalStrehovsky** [comment]
DataContractJsonSerializer is not compatible with trimming - you likely see a lot of warnings when compiling the above code. Trimming is a prerequisite for Native AOT. The problem is that trimming doesn't see the Color type as used by reflection and trims its members away.

The recommendation is to move to System.Text.Json and enable the [source generation](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation?pivots=dotnet-6-0). Source generated serialization is compatible with trimming.

You can also work around by adding `typeof(Color).GetFields(); typeof(Color).GetProperties();` somewhere in your Main. It makes it obvious to the compiler that fields and properties of Color shouldn't be trimmed. It's not ideal. The compile-time warnings you're seeing are real issues.

**Comment by AhmedZero** [comment]
It works well with the old version of nativeaot. What's the different between old and new?

**Comment by MichalStrehovsky** [comment]
> It works well with the old version of nativeaot. What's the different between old and new?

Change to the defaults that allows more trimming: https://github.com/dotnet/runtime/pull/70201.
