### ISSUE TITLE
CTS.TryReset method must be virtual

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#71494]
`CancellationTokenSource.TryReset` method must be virtual because in some cases its usage is invalid even if method returns **true**. This is true for linked CTS created by `CancellationTokenSource.CreatedLinkedTokenSource` because linked CTS violates the key rule of this method: _No-one else will attempt to cancel it._

In case of linked CTS, the overridden method returns **false** all the time regardless of internal state of CTS.

**Comment by stephentoub** [comment]
I don't understand the argument being made.  The premise of TryReset is that it's only valid if no one else is able to concurrently cancel the CTS... as the docs say, "[TryReset()](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.tryreset?view=net-6.0#system-threading-cancellationtokensource-tryreset) is intended to be used by the sole owner".  In the case of CreateLinkedTokenSource, TryReset isn't relevant / useful because it doesn't meet these guarantees.  It's no different from handing out a CTS to someone else and then calling TryReset; TryReset may return true, but that doesn't mean it's actually valid, as the code calling TryReset isn't the sole owner.

**Comment by sakno** [comment]
OK, thanks for explanation. Closing the issue.
