### ISSUE TITLE
AsyncTaskMethodBuilder stopping objects being garbage collected due to reference loop

### ISSUE THREAD

**Issue by mikenorgate** [dotnet/runtime#71538]
### Description

I noticed a scenario in one of our applications where memory usage was higher than expected, after a bit of profiling I found that there was objects being retained by the garbage collector where the only reference too them was an `AsyncTaskMethodBuilder`

### Reproduction Steps

I managed to create this short console app which reproduces the problem

```
{
    var start = new Start();

    var result = start.WorkSync();

    Console.WriteLine($"(Test 1) Result: {result}");
}

GC.Collect();

Console.ReadLine();

{
    var start = new Start();

    var result = await start.WorkAsync();

    Console.WriteLine($"(Test 2) Result: {result}");
}

GC.Collect();

Console.ReadLine();

class Start
{
    public int WorkSync()
    {
        var result = 0;
        var c = new WorkingClass();
        result = c.DoWork();
        return result;
    }

    public async Task<int> WorkAsync()
    {
        var result = 0;
        var c = new WorkingClass();
        result = await c.DoWorkAsync();

        return result;
    }
}

class WorkingClass
{
    private List<int[]> _list = new List<int[]>();

    public int DoWork()
    {
        for (var i = 0; i < 1000; i++)
        {
            _list.Add(new int[50000]);
        }

        return _list.Count;
    }

    public async Task<int> DoWorkAsync()
    {
        for (var i = 0; i < 1000; i++)
        {
            _list.Add(new int[50000]);
        }

        await Task.Delay(10);

        return _list.Count;
    }
}
```

### Expected behavior

Everything allocated in `Start.WorkAsync` is garbage collected on the second call to `GC.Collect();`

### Actual behavior

Using Jetbrains dotMemory I was able to capture the following

![image](https://user-images.githubusercontent.com/2479870/176908359-1b8540e8-1da8-4737-b381-5515d701108c.png)

The first spike is the synchronous execution and shows that after the first `GC.Collect` that the objects on the LOH are collected, Snapshot `Snapshot #1` contains no instances of the classes created in the test code

As you can see when the async function is run the LOH increases but is never collected by the second call to `GC.Collect`

 `Snapshot #2` shows that the `int[]` and `WorkingClass+<DoWorkAsync>d__2` are still retained 

![image](https://user-images.githubusercontent.com/2479870/176909274-7c8d6020-900d-43d7-a2fb-61ed7aad3eea.png)

Looking at the retention path for `WorkingClass+<DoWorkAsync>d__2` it appears to be retained by the async state machine

![image](https://user-images.githubusercontent.com/2479870/176909543-e4766a21-23f1-469c-8dac-033cf01b2076.png)

Which in turn is retained by `WorkingClass+<DoWorkAsync>d__2` creating an infinite loop

![image](https://user-images.githubusercontent.com/2479870/176909652-874c161d-395e-4add-87a5-e45b9c5a5895.png)

![image](https://user-images.githubusercontent.com/2479870/176909959-8df1c307-cf1c-4795-909b-faf73caa9ffd.png)

### Configuration

.NET version: 6.0.300
OS Version: Windows 11 21H2 (22000.613)
Architecture: x64
Not known if specific to this configuration

**Comment by stephentoub** [comment]
The async machinery clears out references from the object:
https://github.com/dotnet/runtime/blob/d04a5899a749316dfb56539d7266a327fe2f2517/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs#L315-L335
but it's only able to do so after calling StateMachine.MoveNext, and its StateMachine.MoveNext that might move the task object to a completed state.  When it does so, any synchronous continuations off of that task will be synchronously executed, which means those continuations can run before the builder gets a chance to forcibly clear out references.  The Task object itself contains those references, and the stack likely has a temporary storing the Task, which is causing the state to be temporarily rooted: the stack references the Task which stores the state machine which stores the WorkingClass reference, which hasn't _yet_ been cleared.

I expect if you add an `await Task.Yield()` before your GC.Collect call (and/or potentially an `await Task.Delay(1)` for good measure in order to give this thread a chance to do the clearing prior to the continuation of this await being scheduled), you'll see the references no longer being rooted.

While it would be nice to be able to clear the state prior to completing the task, there isn't a good way to do so, so this is by-design.

**Comment by mikenorgate** [comment]
Adding `await Task.Yield()` did cause the data to be garbage collected. That's an interesting quirk that I'll have to keep in mind for the future

**Comment by stephentoub** [comment]
Thanks for confirming
