### ISSUE TITLE
Net50 SortedSet<string>.add do not add items to the collection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#71643]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net50-SortedSetstringadd-do-not-add-i/10067925)._

---
//Every runtime before net50 produce list2:=['\0','\u0001','\u0002];
//BUT Runtime net50 produce list2:=['\0'].

var list1 = Enumerable.Range( 0, 3 ).Select( c => (char)c ).ToList();
var list2 = new SortedSet();

foreach( var item in list1 ) 
	list2.Add( item.ToString() );

---
#### Feedback Bot on 6/12/2022, 10:48 PM: 

(private comment, text removed)
#### mauro sampietro on 6/14/2022, 04:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tfenise** [comment]
Seems to be globalization related. `Console.WriteLine(list1[0].ToString().CompareTo(list1[1].ToString()));` prints 0, and `var list2 = new SortedSet<string>(StringComparer.Ordinal);` fixes the problem.

**Comment by tfenise** [comment]
I speculate this is [ICU](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api) related and is by design, but it is really confusing that `string.CompareTo` compares with current culture, while `string.Equals` compares by ordinal.

**Comment by danmoseley** [comment]
I think your diagnosis is correct @tfenise - but @tarekgh can confirm.

Yes, it is confusing. Unfortunately it can't be changed now. It's a good idea to always specify the comparer you want. 
https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings

You can use an analyzer to help
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1307

**Comment by tarekgh** [comment]
You can work around this creating the list with

```C#
var list2 = new SortedSet<string>(StringComparer.Ordinal);
```

If you are using a collection of strings and not passing any comparer, the default string comparison will be used which is performed as linguistic comparison. There are a set of Unicode characters which are ignored characters. These are treated as if it does not exist in the string at all. You can look at this set [here](https://www.unicode.org/charts/collation/chart_Ignored.html). The workaround I provided just tell to use the ordinal string comparison instead of linguistic comparisons.

Also, although you experience this new behavior starting with .NET 5.0, but this is on Windows only. If running on Linux even with .NET Core 3.1 for instance, you will get this same behavior.
