### ISSUE TITLE
.NET 7 dotnet-trace output has `???` in stacks on Android

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#71640]
### Description

If I follow the instructions here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

.NET 7 looks like this:

![image](https://user-images.githubusercontent.com/840039/177356291-24766b87-a550-4924-8a06-c490aab425d0.png)

While .NET 6 looks like:

![image](https://user-images.githubusercontent.com/840039/177356369-06bd84f2-202f-45fb-8800-e460c3da111f.png)

### Reproduction Steps

Use `dotnet-dsrouter` and `dotnet-trace` to get a `.speedscope` file, following instructions here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

### Expected behavior

There isn't a stack frame that says `???`

### Actual behavior

There is a stack frame that says `???`

### Regression?

Yes, worked in .NET 6

### Configuration

This was happening with the .NET versions listed here: https://github.com/xamarin/xamarin-android/commit/a4a1c58642c22af60231c81eb567da4f057d93c6

.NET SDK 7.0.100-preview.7.22327.1

### Other information

Example `.speedscope` and `.nettrace` files:

[dotnet-new-maui-7.zip](https://github.com/dotnet/runtime/files/9047380/dotnet-new-maui-7.zip)

**Comment by steveisok** [comment]
@lateralusX I don't recall if the '?' indicated native code.

**Comment by jonathanpeppers** [comment]
.NET 6 traces have this method name:

![image](https://user-images.githubusercontent.com/840039/177383021-16f3a024-0098-4028-9d86-257fd54edbc9.png)

So maybe just this name is getting lost somehow?

Here are some examples: [dotnet-new-maui-6.zip](https://github.com/dotnet/runtime/files/9048328/dotnet-new-maui-6.zip)

**Comment by lateralusX** [comment]
Seems to be JNINativeWrapper.Wrap_JniMarshal_* that should be first managed frame, they seem to be part of the MethodLoadVerbose events in .net7 trace as well, so I will need to parse the raw callstacks to detect what address it uses, since it seems to not match the expected methods that should be available in the symbol table.

**Comment by jonathanpeppers** [comment]
@lateralusX did you try a `dotnet new maui` project? I was also doing `Release` builds.

**Comment by lateralusX** [comment]
I think I have located the issue, it's a regression from https://github.com/dotnet/runtime/pull/68134 that will overwrite the first stack frames address with event payload, due to struct padding on 64-bit systems not taken into account when calculating buffer manager buffer offsets. Its only in release builds, since debug adds another set of items in the stacks, that will get the corruption, but since that data is not used in serialized event it won't be visible.

**Comment by lateralusX** [comment]
Running with https://github.com/dotnet/runtime/pull/72362 seems to resolve the issue on Android, running startup profiling on MAUI app on Android collecting the following nettrace file with correct top level stack frames:

![image](https://user-images.githubusercontent.com/11529140/179479720-01a2966c-092d-4547-a190-13cf7370cb22.png)
