### ISSUE TITLE
[wasm] Review generated js binding code urls

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#71727]
We get `scriptParsed` events like

`
{"method":"Debugger.scriptParsed","params":{"scriptId":"70","url":"https://mono-wasm.invalid/converter_ss", ,"startLine":0,"startColumn":0,"endLine":24,"endColumn":2..
`
`
{   "scriptId": "66",   "url": "https://mono-wasm.invalid/_debugger_test__Math_NestedInMath_AsyncTest",   "startLine": 0,   "startColumn": 0,   "endLine": 52,   "endColumn": 2,
`

1. Do we need these?
2. Can/should we try to get a usable url?
3. Or should we change `mono-wasm.invalid` to something like `mono-wasm.generated`, or `mono-wasm.binding` etc.

**Comment by lewing** [comment]
> We get `scriptParsed` events like
> 
> `{"method":"Debugger.scriptParsed","params":{"scriptId":"70","url":"https://mono-wasm.invalid/converter_ss", ,"startLine":0,"startColumn":0,"endLine":24,"endColumn":2..` `{ "scriptId": "66", "url": "https://mono-wasm.invalid/_debugger_test__Math_NestedInMath_AsyncTest", "startLine": 0, "startColumn": 0, "endLine": 52, "endColumn": 2,`
> 
> 1. Do we need these?

these are the stubs for marshalling that are generated at runtime by the browser we'd have to swallow them to get rid of them and we don't want to do that

> 2. Can/should we try to get a usable url?

I think @kg used .invalid because it is guaranteed to no be valid,  we could try to make them look like the hosting url by storing that (would be useful for the source map base which is also wrong)

> 3. Or should we change `mono-wasm.invalid` to something like `mono-wasm.generated`, or `mono-wasm.binding` etc.

I'd change mono-wasm - dotnet.generated.invalid makes more sense than the current value
