### ISSUE TITLE
Source generators are introducing Microsoft.CodeAnalysis prebuilts in source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#71741]
The runtime source generators are referencing multiple hard coded Microsoft.CodeAnalysis versions defined in [Versions.props](https://github.com/dotnet/runtime/blob/main/eng/Versions.props#L25) which are introducing source-build prebuilts.  Source-build only builds one version of Microsoft.CodeAnalysis.   Source-build also doesn't need to be concerned with supporting VS.  How should these prebuilts be addressed?  Is it possible to condition these for source-build so that latest is picked up and only one Roslyn version is supported?

**Comment by MichaelSimons** [comment]
cc @ericstj

**Comment by ViktorHofer** [comment]
cc @eerhardt

**Comment by stephentoub** [comment]
> For the other generators that only ship "in box", we would just build against the latest 4.3 version, which we aren't today for Regex, which uses 4.0

For all the in-box ones, we should be aiming to have them referencing 4.4.x (or whatever the version is that'll be available when .NET 7 ships).  I think the question is just when can we cut over to that.  I'm fine sacrificing design time builds temporarily in dotnet/runtime; the bigger issue would be if consuming repos would be on the floor as a result of moving over, so we need to find the right time.

> One approach we can take for Logging and STJ is to build 3 versions of the source generators

That sounds right to me.

**Comment by ericstj** [comment]
Rather than thinking about this as "build 3 versions", which implies growth of the package -- can we instead just make sure all generators' latest build will use source-build-friendly reference for Roslyn when building?  Maybe we are saying the same thing.

**Comment by eerhardt** [comment]
> can we instead just make sure all generators' latest build will use source-build-friendly reference for Roslyn when building?

What does `"all generators' latest build"` mean?

> which implies growth of the package

I was explicitly proposing that we include 3 versions of the Logging and STJ source generators in the package. This would allow us to take advantage of new Roslyn APIs (for example https://github.com/dotnet/runtime/issues/70754 and https://github.com/dotnet/runtime/pull/71765), and it would solve the source-build case, since source-build would use the latest Roslyn version.

**Comment by MichaelSimons** [comment]
Is there an ETA on when this can get fixed?

**Comment by eerhardt** [comment]
Have we agreed on the appropriate fix for this? I think there are at a high-level two options:

1. We special case the PackageReference during source-build to use the "latest Roslyn version" ( `$(MicrosoftCodeAnalysisCSharpVersion)`). But when we aren't building for source-build, we still use the older Roslyn versions (what we are doing today). This is the approach taken in dotnet/roslyn-analyzers.
2. We change the build to always use the "latest Roslyn version" (`$(MicrosoftCodeAnalysisCSharpVersion)`).

I assume option (1) is the fastest way to fix this for source-build. But option (2) may be the most appropriate fix for 7.0 RTM.

We could make the fix for (1) for now to unblock source-build. And then later in 7.0 decide to go route (2).

Thoughts?

**Comment by jkoritzinsky** [comment]
We can't do 2 without limiting us from adopting new Roslyn features in our build and non-shipping Roslyn-based tooling without breaking consuming repos.

I believe the correct solution is to do option 1: Update the generators that ship in-box (which should be the only ones that source-build builds to my knowledge) to use the "latest Roslyn version". We shouldn't need to update any of the packages, as any NuGet packages for out-of-band assemblies built during source-build are not shipped from that build, correct?

**Comment by ViktorHofer** [comment]
> We special case the PackageReference during source-build to use the "latest Roslyn version" ( $(MicrosoftCodeAnalysisCSharpVersion)). But when we aren't building for source-build, we still use the older Roslyn versions (what we are doing today). This is the approach taken in dotnet/roslyn-analyzers.

Just to double check, you are suggesting to include the source generators that target "the version of roslyn that ships with .NET 7" in the targeting pack (irrelevant of in source build or not) but also include them in the packages?

In the example of System.Text.Json, we would add a roslyn4.4 targeting source generator that ships in both the targeting pack and in the System.Text.Json package. The number of source generators in the System.Text.Json package will grow by one.

Asking as if we would omit the roslyn4.4 targeting source generator from the S.T.J package and a customer would reference it, they would revert to the previous roslyn4.0 asset in the package instead of what they have in their targeting pack (assuming that we will service the net6.0 targeting pack - which was discussed in yesterday's tactics meeting).

As an example:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="7.0.0-preview.6.22324.4" />
  </ItemGroup>

</Project>
```

results in the analyzer from the package being chosen over what's in the targeting pack because of the assembly's higher assembly and file version:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/7412651/179980869-fef68214-54d9-4738-9641-a0f943016c93.png">

**Comment by ViktorHofer** [comment]
Cool. I would be very much in favor of 3. To summarize that means:
- Add the 3.11 and 4.4 roslyn microsoft.codeanalysis contract packages to https://github.com/dotnet/source-build-reference-packages and remove the existing source generator build from source conditions.
- Add roslyn4.4 source generators to the libs that ship out-of-band.
- Just upgrade the inbox (shipping and non-shipping) source generators from roslyn4.0 to roslyn4.4.
- Update the [NetCoreAppLibrary.props's source generator section](https://github.com/dotnet/runtime/blob/c046354e4b0e0b9c09d7fefb8f916704c7e2fa1f/src/libraries/NetCoreAppLibrary.props#L185-L190).

**Comment by jkoritzinsky** [comment]
We can’t just upgrade the inbox generators to 4.4 without considering how to avoid breaking upstream repos for non source-build scenarios. For source-build, I’m all good targeting 4.4 as all repos will build with the same Roslyn version, but for non source-build, we’ll break prodcon if we just upgrade to 4.4 on main without looking at how to handle upstream repos.

**Comment by ViktorHofer** [comment]
> We can’t just upgrade the inbox generators to 4.4 without considering how to avoid breaking upstream repos for non source-build scenarios. For source-build, I’m all good targeting 4.4 as all repos will build with the same Roslyn version, but for non source-build, we’ll break prodcon if we just upgrade to 4.4 on main without looking at how to handle upstream repos.

AFAIK the plan is to coherently build the final bits of .NET 7 with VS 17.4 and the latest SDK (presumably RC2). All repos will eventually need to unpin their compiler version and use the compiler that comes via that SDK and VS. Both that SDK and VS will include the roslyn4.4 codeanalysis api.

Presumably, if we upgrade the source generators at the right time (ideally when VS 17.4 Preview 1 is out), we will be ones that drive the adoption of the coherent toolset that we plan to ship with, inside the stack. I don't see a problem in that and just as something that we need to consider and actively work towards.

**Comment by jkoritzinsky** [comment]
Yes, if we wait until VS 17.4 Preview 1 is out and all the repos are updated to use an SDK that has Roslyn 4.4, then we'll be good. But looking forward to future versions of the product, we don't want to end up in this situation again at the end of the next release, and always using the "latest" Roslyn won't work for generators that ship in-box during .NET 8+ development before the end of the release cycle. I think we need some source-build-specific code here to handle this problem permanently for the future (instead of just handling .NET 7 now and fixing it for 8 again down the line).

**Comment by ViktorHofer** [comment]
AFAIK the plan is that the only way to produce an official build is through source build with the effort that @mmitche and @jaredpar are driving. Ideally we will come up with a plan that works for all ways of building.

**Comment by mmitche** [comment]
> AFAIK the plan is that the only way to produce an official build is through source build with the effort that @mmitche and @jaredpar are driving. Ideally we will come up with a plan that works for all ways of building.

That's pretty far off at this point. The intention is to eventually remove the existing official build though, yes.
