### ISSUE TITLE
Dotnet 6.06 install failure

### ISSUE THREAD

**Issue by kbdevs** [dotnet/runtime#71869]
### Description

Trying to install dotnet failing.

![image](https://user-images.githubusercontent.com/86767129/178087843-9884447b-2418-431f-a58d-4d868ea0563d.png)
![image](https://user-images.githubusercontent.com/86767129/178087844-7779cdac-e8e0-4b38-86a2-13a07336a03d.png)

### Reproduction Steps

Opened installer hit next couple of times the errors above popped up and nothing I have tried works

### Expected behavior

Install of dotnet framework

### Actual behavior

Failure to install to folder?

### Regression?

I do not know

### Known Workarounds

None

### Configuration

Windows 11
x64

**Comment by hez2010** [comment]
Each installation puts an uninstaller under `C:\ProgramData\Package Cache`. The dotnet runtime installer will need to launch the uninstaller of previous versions to make sure there's only the latest one installed on your computer. 
If you cleaned `C:\ProgramData\Package Cache` manually, the uninstaller will also be removed, so that the problem you post will happen if you try to uninstall a dotnet runtime, which can be triggered either by yourself or by a newer version of dotnet runtime installation.

**Comment by NikolaMilosavljevic** [comment]
Based on the provided screenshots, this looks like a missing installer for previous .NET version. This can happen if Installer cache is corrupted or if user has deleted it.
