### ISSUE TITLE
Http3Request SendAsync cancellation

### ISSUE THREAD

**Issue by bentoi** [dotnet/runtime#71922]
### Description

The following code doesn't look correct:

https://github.com/dotnet/runtime/blob/16058007315d1068e8c07f0c96270d0e79681ff9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L254

The cancellation of a linked cancellation token source raises an `OperationCanceledException` with a token that matches the linked cancellation source not the token of the predecessors sources.

The source from the try/catch block doesn't actually use the linked token source, sounds like another but related issue.

### Reproduction Steps

```
await request.SendAsync(new CancellationToken(true));
```

### Expected behavior

Cancels the request.

### Actual behavior

Doesn't cancel the request.

### Other information

I didn't actually try to reproduce, the issue is obvious from the source.

**Comment by ManickaP** [comment]
The cancellation of a linked cancellation token source will actually cancel `_requestBodyCancellationSource` which is the token we're passing into all the async operation within this method:
https://github.com/dotnet/runtime/blob/62eb291312749c52507309d50051dd61538cc62d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L122

The linked token is not actually passed to anything.

@bentoi have you observed any weird behavior that might be caused by this? Or is this just observation from the code?

If this is just from reading the code, I'm leaning towards closing this. Unless I've misunderstood your concern.

**Comment by bentoi** [comment]
Sorry, I misread the code, looks fine!
