### ISSUE TITLE
System.Text.Json can't deserialize type with more than 64 ctor parameters.

### ISSUE THREAD

**Issue by Emeka-MSFT** [dotnet/runtime#71984]
## Overview
[Deserialize<TValue>(String, JsonSerializerOptions)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-6.0#system-text-json-jsonserializer-deserialize-1(system-string-system-text-json-jsonserializeroptions)) can not deserialize a type with more than 64 ctor-parameters.

### Observations:
- Serialization of such type works fine (however deserialization fails).
- This (64-ctor-param-max) limit is not documented anywhere -- at least I couldn't find it.
- C# class doesn't have a 64-ctor-max-param limit.

### Source Of Problem:
[runtime/src/libraries/System.Text.Json/Common/JsonConstants.cs](https://github.com/dotnet/runtime/blob/02f875be4cd25802118d7934169866db173ba3c4/src/libraries/System.Text.Json/Common/JsonConstants.cs#L9)
```csharp
// The maximum number of parameters a constructor can have where it can be supported by the serializer.
public const int MaxParameterCount = 64;

```

I wonder how this (64-max) was chosen, and if it could be removed or at least made configurable. NOTE: [MaxDepth](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth?view=net-6.0) is configurable.

## Create Sample Class:
* Create an immutable class (with only `get` properties).
* Add at least 65 member properties to this class.
* Add a constructor that takes at least 65 arguments (one for each property)
* Instantiate this class, and serialize it to a string.

### Recreate The Error:
* Attempt to deserialize this string back to the object using:
  `JsonSerializer.Deserialize<TType>(jsonString, jsonOptions);`
* It will throw an exception similar to the following:

### Sample Error:
```
The deserialization constructor on type '{}' may not have more than 64 parameters for deserialization.
Path: $[0] | LineNumber: 0 | BytePositionInLine: {}. ---> System.NotSupportedException:
The deserialization constructor on type '{}' may not have more than 64 parameters for deserialization.
```

### Expected behavior

I expect to not have this limit.
For classes without custom serialization (e.g. converters), `System.Text.Json` should be able to deserialize/serialize the output of what it serialized/deserialized.

### How Found:
* I serialized a data-class (which has more than 64 ctor parameters) to string.
* Then I attempted to deserialize the class back to object.
* If failed.

### Actual behavior

See sample exception above.

### Regression?

Don't know; `public const int MaxParameterCount = 64;` was added a long time ago...

### Known Workarounds

If you want immutable classes, then I don't know.
You might be able to use `init` in the property (e.g. `public string MachineName { get; init; }`).
However, I'm not sure if it's affected by issue #58770
An alternative that might work could be to use [`[JsonInclude]`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-6.0).

**Comment by krwq** [comment]
@Emeka-MSFT I'd suggest contributing to the library here. I think (I might be wrong) that having more than 64 parameters on the constructor is rather rare. IMO:
- we should not add public APIs to control this
- ok to increase the limit
- let's make sure we don't make scenarios of less than 64 args slower but anything above can be much slower (if it can be fast that's fine but priority should be to not regress perf)

also in vNext we might allow contract customization to handle ctor parameters.

Some workaround is to create a (builder) class with all constructor args as read/write properties and rather than deserializing class deserialize into that class and then construct the immutable class from that.

I'll for now mark this issue as `Future` because we'll unlikely pick this up over other issues but if this gets enough upvotes or scenarios described here we might increase priority. The best path forward is probably to get someone who cares more about this scenario to contribute to the library

**Comment by eiriktsarpalis** [comment]
This is where this upper bound is being used:

https://github.com/dotnet/runtime/blob/0a68c2029a1dcf962b6f488c860fa062b41c1262/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/ReflectionEmitMemberAccessor.cs#L79-L106

I might be missing something, but this restriction seems artificial to me. The constructor is compiled to a `Func<object[], T>` delegate so arities should be practically unlimited. Assuming the original concern was dynamic method size, we can always fall back to using a delegate that wraps `constructorInfo.Invoke`:
```C#
if (parameterCount > JsonConstants.MaxParameterCount) 
{
    return (args=> (T)constructorInfo.Invoke(args)!);
}
```
Related to #33444. cc @ layomia

**Comment by Emeka-MSFT** [comment]
@eiriktsarpalis, yes, it seems artificial to me as well.
@krwq, I can make a short term fix and send a PR.

**Two Fix Options:**
There are two short-term fixes that I can create:
1. Increate the max from `64` to (e.g.) `256` for now.
2. Remove the [test for max-params](https://github.com/dotnet/runtime/blob/0a68c2029a1dcf962b6f488c860fa062b41c1262/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/ReflectionEmitMemberAccessor.cs#L79-L82)

Which one is preferred?

**Comment by krwq** [comment]
I'm wondering why the limit was added in the first place... We should definitely add a test with some large number of args (something artificially generated) to make sure there is no weird issues like corrupted stack or similar. Assuming no issues I agree we should remove limit

**Comment by Emeka-MSFT** [comment]
How long does it normally take for fix to be publicly released?

**Comment by krwq** [comment]
If we merge fix today before 4PM Redmond (today is snap date) it will be available in Preview 7 (release around Aug 9) if fix is made before Aug 12 then RC 1 release is around Sep 13

**Comment by steveharter** [comment]
@GrabYourPitchforks do you recall a discussion around an upper limit? I believe the algorithm is O(n2) so it may be related to that.

**Comment by Emeka-MSFT** [comment]
> If we merge fix today before 4PM Redmond (today is snap date) it will be available in Preview 7 (release around Aug 9) if fix is made before Aug 12 then RC 1 release is around Sep 13

OK, I made quick fix that quadruples the count from `64` to `256`, if that is ok.
[!72053](https://github.com/dotnet/runtime/pull/72053)

**Comment by eiriktsarpalis** [comment]
The release of new language features such as positional records and init-only properties (for the case of sourcegen) means that it will become increasingly likely for users to hit this threshold. We should try to fix this, but I don't think simply raising or eliminating the upper bound is a sustainable approach. We need to make sure that the implementation scales well enough for a large number of constructor parameters.

**Comment by krwq** [comment]
FYI, if we change this behavior we should update following exception message:

```
  <data name="ConstructorMaxOf64Parameters" xml:space="preserve">
    <value>The deserialization constructor on type '{0}' may not have more than 64 parameters for deserialization.</value>
  </data>
```

**Comment by BenjaminBrienen** [comment]
I can't deserialize a response from my database into a DTO because of an arbitrary limit with no configuration? Amazing.

**Comment by ikill69** [comment]
I have run into this exact hard limit... It seems crazy to put a hard limit so low on something that is needed by so may code generators like Entity Framework and Swagger Open API.

I am using the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) from OpenAPITools to Scaffold a Swagger file. 

@eiriktsarpalis ,  I am very disappointing this workaround did not make it into Preview 7 https://github.com/dotnet/runtime/pull/72053. While it would not have fixed the problem it would have helped alleviate it and the point of a Preview is to trial these things.  

@Emeka-MSFT , Perhaps making it configurable in [System.Text.Json.JsonSerializerOptions](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs) with a default if 64 might have been a way to help people out while you investigate the exact cause and reason of this hard-coded rule. They have done this exact same thing for backward compatibility with [DefaultMaxDepth](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#:~:text=set%3B%20%7D%20%3D-,DefaultMaxDepth,-%3B) in JsonSerializerOptions.

The only solution I seem to have right now is to basically pull out [System.Text.Json](https://github.com/dotnet/runtime/tree/62948580b4d3547473cb567bff6cc61308136d81/src/libraries/System.Text.Json) and revert back to Newtonsoft again.     

One thing is for sure though it is hardly used. https://github.com/dotnet/runtime/search?q=MaxParameterCount

I have looked at the history, looks like at some point it was moved but it is not clear why it was really added in the first place other then its only purpose being to support "deserializing with parameterized ctors."  

https://github.com/dotnet/runtime/pull/56354/files 

"Add JSON src-gen support for deserializing with parameterized ctors"
https://github.com/dotnet/runtime/commit/91021fe27b1b845f51ff29cfd47b2405fa91b683

"Add [JsonConstructor] and support for deserializing with parameterized ctors"
https://github.com/dotnet/runtime/commit/4a804959512a76556add344d998f3fc9ca9513e8

Surely we can not have every code generator and scaffolding tool in the world coding this rule in.

I think a fix for this needs to be prioritized.

**Comment by BenjaminBrienen** [comment]
> Surely we can not have every code generator and scaffolding tool in the world coding this rule in.

I don't understand how someone could have put that constant there without even thinking to make it a configurable option. If it's for performance reasons, then that should merely be documented as the reason for the default setting! Surely we can do better than O(n^2) for this algorithm, but I'm no expert. My ugly workaround is to deserialized into an object and interpret it as a JsonElement. In other words, I'm circumventing the type system due to a magic number in a system library 💀
My stringly typed code hurts my soul.

**Comment by ikill69** [comment]
@krwq and @eiriktsarpalis 

I made this suggestion earlier to make it configurable and I am wondering what you think about it? 

> Perhaps making it configurable in [System.Text.Json.JsonSerializerOptions](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs) with a default if 64 might have been a way to help people out while you investigate the exact cause and reason of this hard-coded rule. They have done this exact same thing for backward compatibility with [DefaultMaxDepth](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#:~:text=set%3B%20%7D%20%3D-,DefaultMaxDepth,-%3B) in JsonSerializerOptions. They have defaulted it to 64 as well.

**Comment by eiriktsarpalis** [comment]
We hear your pain, and we'll try to have this fixed in an upcoming release. In the meantime, please consider upvoting the OP so that [it features more prominently](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-System.Text.Json+sort%3Areactions-%2B1-desc) in our backlog.

**Comment by eiriktsarpalis** [comment]
I took a closer look at the constructor argument reader algorithm, at the core of the implementation lies the `JsonTypeInfo.GetParameter` method:

https://github.com/dotnet/runtime/blob/f595e028167bfa16986662f5dc0d5d9cfedbfb1a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs#L242-L374

This method is used to look up parameter metadata every time a JSON property is read by the relevant converter. The assumption is that the reader algorithm is $O(n^2)$ because this method is linear. Even though the parameter resolution is done using an $O(1)$ dictionary lookup,

https://github.com/dotnet/runtime/blob/f595e028167bfa16986662f5dc0d5d9cfedbfb1a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs#L313

This is preceded by a linear traversal over a different cache:

https://github.com/dotnet/runtime/blob/f595e028167bfa16986662f5dc0d5d9cfedbfb1a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs#L253-L308

I'm not sure why this has been added, but I would guess it's there to avoid allocating an intermediate string when performing the dictionary lookup. Perhaps @steveharter can illuminate.

Upon closer inspection, there don't appear to be any scalability concerns with this implementation, for a couple of reasons:

1. The intermediate cache length [is bounded by](https://github.com/dotnet/runtime/blob/f595e028167bfa16986662f5dc0d5d9cfedbfb1a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs#L218-L236) a [constant](https://github.com/dotnet/runtime/blob/f595e028167bfa16986662f5dc0d5d9cfedbfb1a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs#L25-L26), so asymptotically speaking the linear search section is constant time.
2. The [equivalent lookup method for properties is essentially identical](https://github.com/dotnet/runtime/blob/f595e028167bfa16986662f5dc0d5d9cfedbfb1a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs#L86-L240), and STJ supports arbitrarily many properties in POCOs.

In light of the above, I think we could simply remove the limit. The PR should add tests with large enough constructors to make sure the implementation is adequately stress tested.

**Comment by ikill69** [comment]
Great Job @eiriktsarpalis

**Comment by NattyMojo** [comment]
It looks like this issue has been resolved in .NET 8 preview, is there any info on if this is going to be ported to all supported releases? I use .NET 6 and ran into this problem yesterday. I work with many http services that expect large JSON objects (over 64 properties) and sometimes provide responses that exceed that limit that I need to figure out how to deserialize. I do not expect to switch versions of .NET until a new LTS version is supported, so I'd like to see this be back ported if at all possible.

**Comment by eiriktsarpalis** [comment]
@NattyMojo it's not the type of fix that would meet the bar for backporting. If it's a blocking issue I would suggest ingesting the .NET 8 preview nuget package -- it can be used to target `net6.0` applications.

**Comment by NattyMojo** [comment]
@eiriktsarpalis thanks for the info, just for future knowledge do you have any recommend steps for deserializing a very large JSON object into a record? I've solved my current issue as the deserializing wasn't a serious necessity. But who knows when it will become a real necessity and I can't currently think of any way that one would get around this issue, Except doing some weird custom deserializer?

**Comment by eiriktsarpalis** [comment]
Creating a custom converter has its own pitfalls. I would recommend expressing some of the data points as property setters rather than constructor parameters. If they're required you might consider adding the new `required` keyword.

**Comment by drdamour** [comment]
> @NattyMojo it's not the type of fix that would meet the bar for backporting. If it's a blocking issue I would suggest ingesting the .NET 8 preview nuget package -- it can be used to target `net6.0` applications.

that's a pretty high bar :(  using .net8 preview in production is a no fly zone in my org
