### ISSUE TITLE
[NativeAOT] llvm-objcopy is missing in default build pre-requisities

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#72155]
Repro:

1. Install Linux pre-reqs according to https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot#prerequisites
2.
```
dotnet new console
dotnet publish -c Release -r linux-x64 /p:PublishAot=true /p:StripSymbols=true
```

Result:
```
/home/jkotas/net7/sdk/7.0.100-rc.1.22363.25/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.Unix.targets(135,5): error : Symbol stripping tool ('llvm-objcopy') not found in PATH. Make sure 'objcopy' is available in PATH
```

**Comment by jkotas** [comment]
@am11 What is the advantage of using `llvm-objcopy` for nativeaot? Can we just always default to `objcopy` since it is comes with binutils that we indirectly depend on via clang. 

Otherwise, we would need to add `llvm` to out pre-requisites to make `p:StripSymbols` work that is not very desirable.

**Comment by jkoritzinsky** [comment]
@janvorli made the change to use `llvm-objcopy` as it handles cross-compilation scenarios significantly better.

**Comment by am11** [comment]
Currently, we expect user to additionally pass `ObjCopyName=objcopy` in case they installed `clang` package without  `llvm` as, that prerequisite document suggests (at least this is how Debian packages it and it can be different for other packaging systems).

During the runtime build, if llvm-objcopy is available on the machine && toolchain being used is llvm, only then we use it. Otherwise we use binutil's objcopy with clang. So llvm-objcopy is preferred but not required. For gcc we only use objcopy.

We can use the same defaults for `PublishAot=true;StripSymbols=true`. @jkotas, I can prepare a PR to change the targets if this is the desired UX.

**Comment by jkotas** [comment]
I think it would be nice to make `llvm-objcopy` preferred, but not required. It would be great if you can prepare PR that does it. Thank you!
