### ISSUE TITLE
QUIC: DefaultStreamErrorCode and DefaultCloseErrorCode default values cause error

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#72160]
### Description

This is on the preview7 branch, reacting to API changes.

`QuicConnection.ConnectAsync` errors when passed `QuicConnectionOptions` without having `DefaultStreamErrorCode` or `DefaultCloseErrorCode` set.

### Reproduction Steps

1. Create `QuicClientConnectionOptions` and don't set default error codes
2. Call `QuicConnection.ConnectAsync`
3. Get error.

### Expected behavior

I would expect values on `QuicClientConnectionOptions` that work by default or are required to be set to create `QuicClientConnectionOptions`.

I would expect validation of the range of values to happen in property setters.

### Actual behavior

Can create `QuicClientConnectionOptions` that's invalid.

```
  Message: 
System.ArgumentNullException : options (Parameter ''DefaultStreamErrorCode'' should be within [0, 4611686018427387903) range.')

  Stack Trace: 
QuicConnectionOptions.Validate(String argumentName)
QuicClientConnectionOptions.Validate(String argumentName)
QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
QuicConnectionContextTests.AcceptAsync_CancellationThenAccept_AcceptStreamAfterCancellation() line 35
QuicConnectionContextTests.AcceptAsync_CancellationThenAccept_AcceptStreamAfterCancellation() line 59
--- End of stack trace from previous location ---
```

### Regression?

No

**Comment by ManickaP** [comment]
These properties are required, user needs to set them up.
In the last round of API review, it was decided to forgo the `required` since it's not exactly nice to work with from user's perspective and we still have properties that cannot be validated by this (ALPN list, SslAuthenticationOptions). So we gave the user ability to construct the object in whatever way they deem the best and validate everything at a single point in time, i.e.: ConnectAsync/ListenAsync and finish of handshake for inbound connection. With the last one, since we're not in user code, we have no other option then to just log the error.

But since we're in preview, we're certainly open to suggestions about this and we'll consider different model if this proves to be to problematic.

Finally, did this happen to you with server inbound connection? If so, how painful was the diagnostics of this issue?

**Comment by ManickaP** [comment]
Triage: let's discuss user-friendliness of postponed options validation as well as how to better surface errors from failed inbound connections.
