### ISSUE TITLE
Application goes to "No symbol loaded" mode and pops up an exception when stop running application

### ISSUE THREAD

**Issue by Cassie-Li01** [dotnet/runtime#72241]
### Description

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.InteropServices.Marshalling.AnsiStringMarshaller' from assembly 'Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' due to value type mismatch.
  Source=Microsoft.Win32.SystemEvents
  StackTrace:
   at Interop.Kernel32.GetProcAddress(IntPtr hModule, String lpProcName)
   at Microsoft.Win32.SystemEvents.get_DefWndProc()
   at Microsoft.Win32.SystemEvents.Dispose()
   at Microsoft.Win32.SystemEvents.WindowThreadProc()

### Reproduction Steps

1. Create a .Net 7.0 application (.NET version is .NET 7.0.100-rc.1.22364.25)
2. Run the application and stop it

### Expected behavior

Stop application normally

### Actual behavior

Application goes to "No symbol loaded" mode and pops up an exception
![image](https://user-images.githubusercontent.com/96758262/179129453-1d445c59-7294-4617-abe0-35885340f1c5.png)
![bug](https://user-images.githubusercontent.com/96758262/179129824-d61eda4e-a971-4ab2-b0c8-b8d1506ddf1d.gif)

### Regression?

Yes, it is a regression issue, cannot repro in .Net 7.0.100-preview.7.22357.5

**Comment by danmoseley** [comment]
Moving to interop as nothing changed here.

**Comment by AaronRobinsonMSFT** [comment]
This is because of the breaking change in the marshaller shapes introduced between Preview 7 and RC1. The solution is to stay within the same version of the SDK and implementation. If using RC1, then RC1 of WinForms should be used - mixing Preview 7 and RC1 will result in the above issues.

@jkoritzinsky or @elinor-fung may have another mitigation but this is a known break.

See https://github.com/dotnet/runtime/issues/70859 for the API changes.

**Comment by AaronRobinsonMSFT** [comment]
Closing this as it will be sorted once WindowsDesktop moves onto RC1.
