### ISSUE TITLE
QUIC: ApplicationProtocol in ConnectionOptionsCallback not used

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#72361]
### Description

`QuicListenerOptions.ApplicationProtocols` appears to override the values set on `QuicServerConnectionOptions.ServerAuthenticationOptions.ApplicationsProtocols` which is returned from `ConnectionOptionsCallback`.

I recall from discussion with msquic team that `QuicListenerOptions.ApplicationProtocols` must contain all possible protocols, and then the application protocols returned from `ConnectionOptionsCallback` must be one of those values.

### Reproduction Steps

1. Set `QuicListenerOptions.ApplicationProtocols` to h3.
2. Set `QuicListenerOptions.ConnectionOptionsCallback` to return options with a different `ApplicationProtocols` value, e.g. `new SslApplicationProtocol("custom")`
3. Connect with a client that has application protocols of h3.

### Expected behavior

I expected an error for multiple reasons:
1. The server has done something invalid by specifying `h3` protocol to the listener but `custom` protocol in the callback.
2. The client is specifying `h3` but the connection callback has specified `custom`.

### Actual behavior

The client connects to the server and the negotiated protocol is `h3`.

It seems like the protocol in the callback is being ignored.

**Comment by ManickaP** [comment]
This feature unfortunately didn't make into MsQuic for .NET 7.0. As you can see https://github.com/microsoft/msquic/issues/2418 is still open, as well as https://github.com/dotnet/runtime/issues/49423.
MsQuic team didn't have time to address it and since we now only have "h3" and no need to narrow it down, we confirmed we can live without it for one more release.

We should either close this issue as duplicate of https://github.com/dotnet/runtime/issues/49423 or keep this and close the other (after all this one better describes the remaining problem).

**Comment by JamesNK** [comment]
Ok. I'll close this.
