### ISSUE TITLE
Infinite recursion during resource lookup within System.Private.CoreLib

### ISSUE THREAD

**Issue by introspection3** [dotnet/runtime#72381]
### Description

 ```
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_NullReferenceException
Stack:
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.NullReferenceException..ctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.NullReferenceException..ctor()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__186`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__186`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.InvokeContinuation(System.Action`1<System.Object>, System.Object, Boolean, Boolean)
   at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by eiriktsarpalis** [comment]
Thanks. In order to assess the problem we will need more information, including SDK versions and a minimal reproduction demonstrating the problem.

**Comment by danmoseley** [comment]
@introspection3 this is possibly a bug in .NET 6 but much more likely to be a corrupted process, and we should eliminate that first. So a repro case would be ideal, or else a dump file. Also please try to repro on another machine, another install. Also if possible whether it reproed before .NET 6.

Eg., https://github.com/dotnet/runtime/issues/53833  - unresolved, needed dump.
https://github.com/dotnet/runtime/issues/53504 -- ICU was suspected.
https://github.com/dotnet/runtime/issues/1716 -- bad install - mixed up bits.

**Comment by danmoseley** [comment]
Would there be value in improving the message, eg.,

```diff
< Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially .  Resource name: Arg_NullReferenceException
> Infinite recursion during resource lookup within System.Private.CoreLib. Verify that the process state is not corrupted. This can also be caused by an incomplete or corrupt installation of .NET, or by a bug in code running in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: Arg_NullReferenceException
```
We could add `This may be a bug in System.Private.CoreLib,` in DEBUG only -- it was originally intended for developers working on .NET itself, and by the time the product is shipped, it's the least likely possibility.

**Comment by karelz** [comment]
Triage: 6.0 problem. Unlikely networking -- these kind of issues typically indicate bad installation. Changing to Meta area for further investigation/triage/routing.

**Comment by KiristonK** [comment]
Hi, is there any information about when this issue will be fixed? 

May be useful:
Also when starting to debug application step-by-step from CreateMauiApp method, app will load correctly for the first time (if no previous versions of app was installed). The next time i try to do same process (without uninstalling app) Infinite recursion loop will stop code execution before hitting breakpoint and without showing any exception, only logcat shows this error.

By the way, for me changing phone language to EN-US fixes this problem.  I've seen some threads on StackOverflow with simillar issues on other languages?

**Comment by jeffhandley** [comment]
@tarekgh Does anything stand out for you on this, especially given @KiristonK's comment that setting locale to `en-us` works around it?

@KiristonK what locale were you on before changing to `en-us`?

**Comment by KiristonK** [comment]
@jeffhandley I had `pl-PL` locale. For me the problem was in FlyoutItem template, somehow it worked with `debug` configuration, and does not in `release`. Today, after launching test project (in main i've just removed template) it works fine. Attaching test project that had problems.
[FlyoutTest.zip](https://github.com/dotnet/runtime/files/9239301/FlyoutTest.zip)


Also some workaround for me with locales was setting app locale to `en-US`. 
In case someone needs code (file App.xaml.cs inside constructor):
```csharp
            CultureInfo.CurrentUICulture = new CultureInfo("en-US", false);
            CultureInfo.CurrentCulture = new CultureInfo("en-US", false);
            CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US", false);
            CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en-US", false);
```

**Comment by tarekgh** [comment]
> Does anything stand out for you on this, especially given @KiristonK's comment that setting locale to en-us works around it?

I don't think the issue is related to cultures or resources at all. There is another severe problem that is hiding there. Even when using culture different than `en-US`, we should fall back to the neutral resources at the end which is the English resources. Looking at the stack, I am seeing NullReferenceExcpetion is thrown twice in the stack. This can suggest something wrong in general, not allowing creating objects from various places. Switching to `en-US` could be just using some cached data which hide the path trying to create the needed objects. 

Do we have dump for such failure? What OS was running on? does it repro on other machines/devices? 

CC @jkotas

**Comment by jkotas** [comment]
> Do we have dump for such failure?

Yes, we would need a full crash dump to diagnose this issue. @KiristonK Is it possible to share the crash dump with us somehow?

You can either save the dump in debugger, or you can configure OS to collect the crash dump on all fatal errors https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps when running without debugger.

Does you app has a lot of custom interop with native code? It is not unusual for crashes like this one to be caused by bugs in interop that lead to memory corruptions.

**Comment by KiristonK** [comment]
@jkotas As i said before, now i can't reproduse this problem.  The project that i attached still have wierd Flyout behavior (items does not show in release config, problem in `FlyoutItemTemplate`), but app launches and does not throw `Infinite recursion during resource lookup within System.Private.CoreLib`. That is MAUI project so maybe problem was caused by MAUI and recent update fixed it.  
Today tested app on Windows 11 and Anroid 11, app launches correctly.

If issue will occur again, where should i write about it, at dotnet/runtime or dotnet/maui issues?

**Comment by jkotas** [comment]
> MAUI project so maybe problem was caused by MAUI and recent update fixed it.

Yes, that's quite possible.

> If issue will occur again, where should i write about it, at dotnet/runtime or dotnet/maui issues?

For the " Infinite recursion during resource lookup" crash like the one at the top, it is better to start with dotnet/runtime.

**Comment by rzikm** [comment]
Reproduced in https://github.com/dotnet/runtime/pull/67049
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67049-merge-d7aa731dedaf40d491/System.Net.Security.Tests/1/console.4a866944.log?helixlogtype=result

**Comment by jkotas** [comment]
@rzikm The stacktrace that you have shared points to the problem with the PR https://github.com/dotnet/runtime/pull/67049 at one point that was fixed before the PR got merged.

The PR was optimizing `String.Replace` and the crash starts with `String.Replace`: 
```
00007ECD735510E0 00007f0e9ecf8347 [FaultingExceptionFrame: 00007ecd735510e0]
00007ECD73551EE0 00007F0E213B6F7E System.String.Replace(Char, Char) 
```

The "infinite recursion during resource lookup" is generic symptom of the things going wrong and the process state being corrupted. If you see this error message, it is unlikely to be a duplicate of the problem tracked by this issue - open a new issue instead.
