### ISSUE TITLE
Vector256.Create() randomly throws PlatformNotSupportedException

### ISSUE THREAD

**Issue by dubiousconst282** [dotnet/runtime#72506]
### Description

Calling `Vector256.Create()` on a machine with no support for AVX2 will throw `PlatformNotSupportedException` after a short amount of time.

### Reproduction Steps

```cs
using System.Runtime.Intrinsics;

int i = 0;
while (true) {
    Vector256.Create(0f);
    if (i++ % 10000 == 0) Console.WriteLine("OK " + i);
}
```

### Expected behavior

The program above should run indefinitely.

### Actual behavior

The program crashes after a short amount of time:

```
...
OK 3390001
OK 3400001
Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.Vector256.Create(Single value)
   at Program.<Main>$(String[] args) in ...\Program.cs:line 4
```

### Regression?

I'm pretty sure it is. Changing the target to .NET 6 works as expected, and I've only found this issue after upgrading to .NET 7 preview 6.

### Configuration

.NET SDK: 7.0.100-preview.6.22352.1 (commit 492644e08e)
OS: Windows 10 (6.3.9600, x64)
CPU: Intel i3 Gen2 (Sandy Bridge, with no AVX2 support)

**Comment by huoyaoyuan** [comment]
The behavior looks related to tiered compilation. Or maybe dynamic PGO?

**Comment by dubiousconst282** [comment]
Can confirm that `dotnet run -p:TieredCompilation=false` works as expected.

**Comment by EgorBo** [comment]
There are few problems here: 

1) We treat Vector256 "ISA" as not-supported on AVX1 only CPUs so `Vector256.IsHardwareAccelerated` returns `false` on e.g. Ivy Bridge

2) Inside Vector256.Create we still check for AVX1 https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector256.cs#L979-L984 and if it's true we think that Vector256.Create is an intrinsic (but it's actually not since Vector256 ISA is disabled).

Solution:
1) Replace `Avx.IsSupported` checks with `Vector256.IsHardwareAccelerated` for consistency so we will always be using software fallbacks on Avx1
2) Enable some Vector256 helper instrinsics on AVX1 (makes more sense)
