### ISSUE TITLE
Serialization is not consistent 

### ISSUE THREAD

**Issue by SrdjanPaunovic** [dotnet/runtime#72591]
### Description

The following code does not produce the same result. I couldn't find documentation that this is by design. The example is a simplified version where we have multiple inherited `ProblemDetails` returned for serialization.

### Reproduction Steps

```cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Text.Json;

ProblemDetails v = new ValidationProblemDetails(new Dictionary<string, string[]> { { "propA", new[] { "value cannot be null" } } });
Console.WriteLine(JsonSerializer.Serialize(v));
Console.WriteLine(JsonSerializer.Serialize((object)v));
```

### Expected behavior

```json
{"Errors":{"propA":["value cannot be null"]},"Type":null,"Title":"One or more validation errors occurred.","Status":null,"Detail":null,"Instance":null,"Extensions":{}}
{"Errors":{"propA":["value cannot be null"]},"Type":null,"Title":"One or more validation errors occurred.","Status":null,"Detail":null,"Instance":null,"Extensions":{}}
```

### Actual behavior

```json
{"Type":null,"Title":"One or more validation errors occurred.","Status":null,"Detail":null,"Instance":null,"Extensions":{}}
{"Errors":{"propA":["value cannot be null"]},"Type":null,"Title":"One or more validation errors occurred.","Status":null,"Detail":null,"Instance":null,"Extensions":{}}
```

### Known Workarounds

Casting to `object` type.

### Configuration

```
Version:   6.0.302
 Commit:    c857713418
Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.302/
global.json file:
  Not found
Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96
.NET SDKs installed:
  6.0.302 [/usr/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by eiriktsarpalis** [comment]
Your reproduction is missing the declarations for `ProblemDetails` and `ValidationProblemDetails`, but I believe what you are seeing is by design: when a type is serialized as `object` then it is being serialized _polymorphically_, that is, it is using the contract of the runtime type rather than the declared type. What you end up seeing being serialized over the wire are the properties of `ValidationProblemDetails` rather than `ProblemDetails`.

See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism for more details.
