### ISSUE TITLE
Extra jmp in code

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#72776]
### Description

Discovered with sharplab. I wonder why there is `jmp short` in two places.

### Reproduction Steps

https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmOATEBqAPgAQCYBGAWACgL8BmAAhQQCcBXAYwVoBFaBvC2gbRq1YHCAG5+g4QBsA9jADmtYJPIBfClTpFaAYV5SBw/ABZaAWQAUASkPlBjrrQBuap4JcA6YAF5q7h4iAGa0VgAqjACeAOIApghWcswcLjZ2fA5BjnoKKHIycV4A6oxQCHFW3hA2gR6aWR5GTi4QjK4utL608Ym1zTl5BUWl5ZUuLgD8Pv2NtA2OzcLAcgW0kbEJSSnOGBgZA4J7XhBdtMR1TsfAZ4SXjvgA7LRMzHGXDUt0nJM9WwdzB7PGBxADuXB4EF8xDgKl8pnUHwo6iAA===

### Expected behavior

No extra jmp present

### Actual behavior

Extra jmp present.

**Comment by svick** [comment]
Can you clarify which `jmp short`s you are talking about and why you think an extra one is a problem? Especially since you're looking at a Debug version of the code and [the Release version](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUEZgMwAEKCATgK4DGC5AIuQN5HlflnmxMQA3J268ANgHsYAc3LBhhAL5ESFHOQDC7EV16YALOQCyACgCU2wt2styANwU3udgHTAAvKUdO+AM3ImACrUAJ4A4gCmCCYStEx2ZhYcVj7WGlIoEmIRLgDq1FAIESauEGbeTsopTjo2dhDU9nbk7uSR0eW1aRlZOfmFxXZ2APxundXkVda1vMASWeTB4VExcbYAJutJXdybLhAt5LgVNnvAh9gn1pgA7OQ0tBEnVTMUzMNtK9sT13cwEQB3FhsCDuXBwOTufSKZ5ERRAA===) is quite different.

**Comment by stephentoub** [comment]
Closing as fixed

**Comment by iSazonov** [comment]
If it was fixed in Jun why do sharplab show them (for Roslyn main branch Jul 23)?

**Comment by iSazonov** [comment]
Thanks! I see it is only in Debug code now.
