### ISSUE TITLE
CryptoStream .Read truncates the decoded byte array depending on the input length of the encoded one

### ISSUE THREAD

**Issue by FZilli** [dotnet/runtime#72797]
### Description

Following the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rc2cryptoserviceprovider?view=net-6.0) but using the updated ".Create()" method of the base type (instead of the constructor of the derived one) and the ".Read(...)" method (instead of ".ReadByte()"), I can't encode/decode a byte array using RC2 and CryptoStream.

As an example, the process (encode then decode) works if the starting array has a length of 8 and doesn't work if it has a length of 9 - different input lengths produce different results. 

The issue doesn't occur if a loop with ".ReadByte()" is being used.

### Reproduction Steps

I've created the following gist to reproduce the issue

`https://gist.github.com/FZilli/49b2a35162e9f56f007b4912805a5890`

### Expected behavior

The input array is correctly encoded and decoded - same length and content

### Actual behavior

The input array is encoded but it doesn't match the decoded one - last byte is missing

### Regression?

Worked in .NET5 5.0.101, encountered the issue when migrating to .NET6

### Known Workarounds

Use a loop and ".ReadByte" as in the docs

### Configuration

- SDK .NET6 6.0.300
- OS Windows 10 [Version 10.0.19044.1826]
- Architecture x64
- Should not depend on this configuration
- No Blazor

### Other information

Should I create a pull request with a test directly in [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/tests/CryptoStream.cs) (.../tests/CryptoStream.cs)?

**Comment by stephentoub** [comment]
Stream.Read does not guarantee to read as much as requested.  In your repro, you need to change the code that calls Stream.Read to loop until either it returns 0 (indicating EOF) or you've read as much in total as is desired.  .NET 7 has a set of Stream.ReadExact and Stream.ReadAtLeast helpers to make this easier.

CryptoStream in .NET 6 became more likely to return fewer than requested.  More details are available at https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams.

**Comment by bartonjs** [comment]
We're working on updating the samples to stop doing it wrong.

The 3DES version of the update is at https://github.com/dotnet/dotnet-api-docs/pull/8227/files.

RC2 is old and busted, you shouldn't be using it anyways.

Whether an old SymmetricAlgorithm or a new one, unless you're using Streams because you're processing large data (e.g. a file of unknown size) you probably want to use the new one-shot methods in .NET 6+, e.g. https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.encryptcbc?view=net-6.0 rather than the CryptoStream approach.
