### ISSUE TITLE
Huge memory consumption by process "wasm-opt" when publishing aot .net 7 preview 6

### ISSUE THREAD

**Issue by ahmed-salem-me** [dotnet/runtime#73069]

**Comment by ahmed-salem-me** [comment]
![image](https://user-images.githubusercontent.com/95217221/181802263-0f8cfcc1-8aa5-47dd-90e5-a42ba550bc01.png)

**Comment by ahmed-salem-me** [comment]
Had several failed publishing with .net 7 preview 5 with out of memory error

**Comment by lewing** [comment]
wasm-opt optimizes all the native code in a single pass post compilation, if there is a lot of AOTd code this can require substantial resources.   Without more information about what your application there is no way to know if there is anything wrong.

**Comment by ahmed-salem-me** [comment]
> wasm-opt optimizes all the native code in a single pass post compilation, if there is a lot of AOTd code this can require substantial resources. Without more information about what your application there is no way to know if there is anything wrong.

@lewing We are working on this opensilver.com , which runs as a blazor wasm app, though doesn't use any blazor specific features.
So I'm not sure I can isolate the issue without using opensilver libraries.
I will try, but I might have to send you an opensilver test app, where the issue appears.

**Comment by Eddie-Hartman** [comment]
@lewing @ilonatommy Bumping this issue since I ran into it as well. This issue seems to have stalled out because of a lack of additional info, but I'm willing to help here where I can.

In investigating a follow up on #103293 I had given Ilona access to our private repo for investigation. She went above and beyond in terms of helping and we (more like she) eventually boiled it down to this.

When running publish on my repo locally, I get extreme memory usage:
![image](https://github.com/user-attachments/assets/7f03f866-8bad-4798-ab31-6be917cee19f)
and this is causing out of memory exceptions when building in my Azure DevOps pipeline.

I can't make the repo public, but if certain members from the Microsoft team want to investigate this issue with a real-world example, feel free to reach out to me.

If this is considered "normal" then I certainly won't be able to utilize this feature since the Microsoft hosted Azure DevOps agents run out of memory. I will also look into some of the changes Ilona proposed such as publishing trimmed to reduce the memory usage, but this seems like it still warrants an investigation of some sort.

**Comment by lewing** [comment]
Reducing the optimization level should also help the memory usage here, I think including dwarf info in the native symbols also heavily impacts the memory usage.

**Comment by lewing** [comment]
You could try applying https://github.com/dotnet/runtime/pull/105727 and seting WasmNativeDebugSymbols=false (or editing your sdk temporarily to remove the llvmdebug arg) and see if that helps.
