### ISSUE TITLE
Regex Compiled and Source generated engines are loosing some state causing backtracking to be incomplete and fail finding matches for some cases.

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#73209]
While porting PCRE2 engine tests, we discovered that there are patterns that can lead to bad code-gen causing inconsistency between the results from our Interpreted and codeGen engines. The following test:

```c#
Assert.True(Regex.IsMatch("bababc", "^(b*|ba){1,2}?bc"));
```

passes in the Interpreted engine, but fails in the Source Generated and Compiled engines.

cc: @stephentoub

**Comment by stephentoub** [comment]
The problem is in our handling of optional empty matches (via an alternation, via an optional, etc.) in lazy loops.  The semantics of our engine (and most others) dictate that loops and lazy loops needs to stop iterating once an iteration matches as empty, as otherwise they could match infinitely.  We track in a local whether the last iteration seen was empty.  However, we fail to handle the fact that backtracking into that last iteration should reset whether empty was seen.
