### ISSUE TITLE
"CTRL+M" is captured as "Enter" in console app on Linux

### ISSUE THREAD

**Issue by MrM40** [dotnet/runtime#73379]
### Description

In .Net 6 vb.net `Console.ReadKey()` read "CTRL+M" as "Enter"
![image](https://user-images.githubusercontent.com/16258063/182876144-109cbc45-2331-499b-af00-8d0f556ce404.png)

Any other CTRL+ combinations seems to work fine e.g. "CTRL+L":
![image](https://user-images.githubusercontent.com/16258063/182877294-a03245c0-9aa0-4ae3-9c74-51dd96176ebd.png)

I worked fine in .net core 2.2

Tried on OpenSUSE 15.3 and Debian 11 Linux boxes (also directly on the VGA/keyb console).
And tested nn these terminals: Kitty and Windows Terminal.

.net runtime installation on the Linux box:
![image](https://user-images.githubusercontent.com/16258063/182878580-cb1d41b1-6de1-48bf-90a5-cfbd0a5d29ce.png)

### Reproduction Steps

Debug `Console.ReadKey()` and see what .net interpret the key keystroke CTRL+M

### Expected behavior

`ConsoleKeyInfo.Modifiers` should be `Control`
and
`ConsoleKeyInfo.Key` should be `M`

### Actual behavior

Read as `Enter`

**Comment by danmoseley** [comment]
Can you try with the latest daily build of .NET 7?

**Comment by MrM40** [comment]
I will tomorrow....thanks for the suggestion.

**Comment by MrM40** [comment]
Ohhh....I see I need to reinstall (or at least update) my Visual Studio 2022 for 7.0 support, which I don't dare right now. It's my production PC :-/
If you already have a 7.0 environment up an running, can you make a quick test-project?
Or perhaps just take a quick look in the 6.0 code.....I wouldn't be suppressed if it was just the switch-value for CTRL-M which wasn't updated (I have no clue where to look myself)

**Comment by danmoseley** [comment]
You do not need to modify VS. See

https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md

VS will not be directly affected. You will just change the TargetFramework of your test project, by editing it directly.

**Comment by adamsitnik** [comment]
Hi @MrM40

Every Unix Terminal maps keys pressed by the user to their byte representation that .NET reads via `read()` sys-call.

The best utility for finding out the mappings is using `showkey -a` Linux command line tool.

In the following picture I've pressed `Enter`, `Ctrl+J` and `Ctrl+M`:

![image](https://user-images.githubusercontent.com/6011991/183032177-3e10316f-e742-4032-89a4-386bbfa873cf.png)

As you can see, `Ctrl+M` is just mapped to exactly same byte as `Enter` (`0x0d`) by the Terminal. This is a Unix convention; .NET has no control over that. We can't map `Ctrl+M` to `Ctrl+M` because it would mean that we would need to map `Enter` to `Ctrl+M` as well.

We have rewritten `Console.ReadKey` for .NET 7 and in https://github.com/dotnet/runtime/pull/72193 I've listed all limitations:
- `Ctrl+M` is mapped to `Enter` with carriage return character (`\r`)
- `Ctrl+J` is mapped to `Ctrl+Enter` with new line character (`\n`)
- `Ctrl+I` is mapped to `Tab`
- `Clr+H` is mapped to `Ctrl+Backspace`

This is by design.

**Comment by MrM40** [comment]
@adamsitnik 
Confirmed!
I guess it wasn't work in .NET Core 2.2 after all :-/
Thanks for sharing your wisdom and sorry for the "noise".
