### ISSUE TITLE
URIBuilder misinterpret "domain:port" format as "scheme:path"

### ISSUE THREAD

**Issue by KohGeek** [dotnet/runtime#73521]
### Description

When parsing a string in the format of `domain:port`, URI Builder interprets the domain part as `scheme` and port as `path`.
Unsure if this is intended or a bug.

### Reproduction Steps

```
var input = "test:80";
var urlBuilder = new UriBuilder(input);
```

### Expected behavior

urlBuilder.Host should be `test`
urlBuilder.Port should be `80`

### Actual behavior

urlBuilder.Host is empty, but urlBuilder.Scheme is `test`
urlBuilder.Port is empty, but urlBuilder.Path is `80`

### Configuration

.net 6.0

**Comment by MihaZupan** [comment]
This is intentional. `UriBuilder` is expecting a full Uri string (`https://test:80`), not just the authority.
The `Uri` class supports custom schemes, and `test:80` happens to be a valid Uri with a `test` scheme.

If you know your input will always be just `host:port`, you can use `new Uri($"https://{input}"`) instead.

**Comment by KohGeek** [comment]
Understood, in that case, I will close this issue.
