### ISSUE TITLE
Microsoft.Extensions.Configuration.dll has wrong modified date

### ISSUE THREAD

**Issue by sunmijiang** [dotnet/runtime#73544]
### Description

Runtime version .net framework 4.7.2
Create a new C# project and add reference Microsoft.Extensions.Configuration 3.1.0, build project, then you will see the following dlls have wrong modified date in the bin folder.
![image](https://user-images.githubusercontent.com/110593895/183321117-a97e1b40-8ed6-40f6-95e4-f37cbeb7973a.png)

### Reproduction Steps

Create a new C# project and add reference Microsoft.Extensions.Configuration 3.1.0, build project, then you will see the following dlls have wrong modified date in the bin folder.

### Expected behavior

The modified date should be same with created date.

### Actual behavior

The modified date is 1/1/1980.

### Regression?

It works about one week ago.

**Comment by eerhardt** [comment]
This appear to only happen with the `3.1.0` nuget package. If I use the latest 3.1 version, `3.1.27`, it doesn't occur.

Since we can't fix `3.1.0` (because nuget packages are immutable), this can't be fixed. My suggestion is to update to the latest `3.1.27` which contains the latest servicing fixes.
