### ISSUE TITLE
API Proposal: Unsafe.IsNullRef(ref readonly)

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#73608]
### Background and motivation

Currently we cannot test whether a ref readonly is null ref or not because Unsafe.IsNullRef() takes a ref parameter instead of ref readonly parameter. 
Given that Unsafe.IsNullRef doesn’t need mutability, the signature should be changed from IsNullRef(ref) to IsNullRef(ref readonly). 

### API Proposal

```diff
namespace System.Runtime.CompilerServices;

public static class Unsafe
{
-    public bool IsNullRef(ref value);
+    public bool IsNullRef(ref readonly value); // or in value
}
```

### API Usage

```csharp
ref readonly int Foo() {…}
ref readonly int x = ref Foo();
Unsafe.IsNullRef(in x);
```

**Comment by sakno** [comment]
@hez2010 , you can but with a bit more verbose code:
```csharp
ref readonly int x = ref Foo();
Unsafe.IsNullRef(ref Unsafe.AsRef(in x));
```

**Comment by stephentoub** [comment]
> the signature should be changed from IsNullRef(ref) to IsNullRef(ref readonly).

The language doesn't currently support that, changing the current signature to in instead of ref would be breaking, and we can't overload on ref vs in.

This would require https://github.com/dotnet/csharplang/issues/6010, at which point there are a bunch of methods including this one we'd be looking to change over.

**Comment by jkotas** [comment]
Superseded by https://github.com/dotnet/runtime/issues/73608.

**Comment by hez2010** [comment]
I think you mean by #85911?
