### ISSUE TITLE
stop runtime maestro from consuming dotnet/msquic 

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#73645]
MsQuic released 2.1 on Friday and we branched  dotnet/msquic early as preparation for 7.0. 
main of dotnet/msquic becomes 8.0 and it will produce msquic 2.2.

Until runtime branches for 7.0 release we will consume msquic updates manually as needed. 
and we don't want maestro to interfere in mean time.

**Comment by wfurt** [comment]
We don't know how use darc @riarenas and it was always done for us by core-eng ... perhaps as unofficial support.

**Comment by wfurt** [comment]
cc: @karelz

**Comment by riarenas** [comment]
@wfurt I'll help with this one, but it's really better if the product repos keep track of these so that you can re-enable when necessary, and that's our general expectation. 

You can find documentation on darc, and specifically on the update-subscription command here: https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md#update-subscription

the current subscriptions I see are:

```
darc get-subscriptions --source-repo msquic
https://github.com/dotnet/msquic (.NET 7) ==> 'https://github.com/dotnet/runtime' ('main')
  - Id: 2c02cca6-9dfc-41ac-a21d-08d94c99dc63
  - Update Frequency: EveryDay
  - Enabled: True
  - Batchable: True
  - PR Failure Notification tags:
  - Merge Policies:
    AllChecksSuccessful
      ignoreChecks =
                       [
                         "WIP",
                         "license/cla",
                         "runtime-coreclr superpmi-diffs",
                         "runtime-coreclr superpmi-replay",
                         "runtime-libraries enterprise-linux"
                       ]
    NoRequestedChanges
  - Last Build: 20220721.1 (620c3a5e7982c143ba8eb3d0f0d902f55359e905)
https://github.com/dotnet/msquic (.NET 6) ==> 'https://github.com/dotnet/runtime' ('release/6.0')
  - Id: 4165ecc1-3ee5-46b7-ebf6-08da0218026c
  - Update Frequency: None
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies:
    Standard
```

Since the one we want to disable is the one to main, I run 

```
darc update-subscription --id 2c02cca6-9dfc-41ac-a21d-08d94c99dc63
```
and set the enabled property to `False`.

Once you are ready to resume flow, you can use the same command and set the property back to `True`

If you won't need the subscription anymore, you can also delete it using the `delete-subscriptions` command.

**Comment by ViktorHofer** [comment]
@wfurt Anirudh, me and others took care of this in the past. Please ping the infrastructure team if you need subscription updates.

**Comment by wfurt** [comment]
thanks @riarenas and @ViktorHofer. The responsibilities are somehow fuzzy to me so I was not even sure who to ask.

**Comment by hoyosjs** [comment]
Now that updates are paused on 7, should this be an 8.0 issue to reenable the flow?

**Comment by wfurt** [comment]
yes. @rzikm did some scouting so we _may_ be able to do it with the notes above.

**Comment by rzikm** [comment]
Yes, we should close this issue as done and create an issue to reenable.it in 8.0. I am not at the PC right now so I can do that tomorrow.
