### ISSUE TITLE
Test failure - `S.R.Tests.ControlledExecutionTests.CancelOnTimeout_ThrowFromFinally` on ``Libraries Test Run checked coreclr Linux arm64 Debug`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73647]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1930800&view=logs&jobId=e4f18bbc-2f57-55e3-8831-999b74ca15c3&j=e4f18bbc-2f57-55e3-8831-999b74ca15c3&t=7dbfac67-24c2-5451-1abf-2cb25235c000) for `Libraries Test Run checked coreclr Linux arm64 Debug`:

```
   System.Runtime.Tests.ControlledExecutionTests.CancelOnTimeout_ThrowFromFinally [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Runtime/tests/System/Runtime/ControlledExecutionTests.cs(56,0): at System.Runtime.Tests.ControlledExecutionTests.CancelOnTimeout_ThrowFromFinally()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jeffhandley** [comment]
@steveharter It looks like Reflection might be in the call stack here and a couple folks from this area pod are away from work right now. Can you take a look please?

**Comment by steveharter** [comment]
>It looks like Reflection might be in the call stack here

Reflection is only in the call stack because XUnit uses reflection to invoke the test methods.

Likely related to https://github.com/dotnet/runtime/issues/73739 since they use the same test helpers and the failure occurred around the same date.

The failure indicates the actual target test method `LengthyAction_ThrowFromFinally` was not called, since the first line of code in that method sets `_startedExecution = true` and the assert that is failing checks against that.

Stack is:
```
RunTest(LengthyAction_ThrowFromFinally, cts.Token);
->ControlledExecution.Run(action, cancellationToken);
```

And since `ControlledExectution` is [new](https://github.com/dotnet/runtime/pull/71661), that should be investigated -- [AntonLapounov](https://github.com/AntonLapounov) PTAL.
