### ISSUE TITLE
Can't get assembly probing to work; not sure why.

### ISSUE THREAD

**Issue by mavnorthwind** [dotnet/runtime#73710]
### Description

With earlier .NET Framework versions I was used to be able to configure additional paths for assembly probing by adding a 
/configuration/runtime/assemblyBinding/probing node to my app.config file.
With .NET 6.0 this doesn't seem to work anymore.
After a lot of searching I found the additionalProbingPaths setting in <app>.runtimeconfig..json, but this didn't work either.

Using the Resolving event from AssemblyLoadContext, I was able to load the assembly from code, but I was hoping for a config way.

### Reproduction Steps

Create a library project, add a class, build.
Create an app project (I tried with a WinForms app), add an assembly reference to the library and set "Local copy" to false.
Instantiate a class from the library in the app.
Create a folder "Lib" in your app project, copy the library output to this folder and set "Copy to output" to Always.

Running the app as it is now will throw a FileNotFoundException because .NET doesn't know where to find the library assembly.

Add
"additionalProbingPaths": [
 "Lib"
 ],
to the <app>.runtimesettings.json

Running the app will also throw the FileNotFoundException.

### Expected behavior

App will find the assembly in (one of) the paths given in additionalProbingPaths and load it from there.

### Actual behavior

Assembly is not being found and a FileNotFoundException is thrown.

### Configuration

{
  "runtimeOptions": {
    "tfm": "net6.0",
	"additionalProbingPaths": [
		"Lib" 
	],
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "6.0.0"
      }
    ]
  }
}

**Comment by huoyaoyuan** [comment]
I remember `additionalProbingPaths`, but can't find it in official documentation.
See also https://github.com/dotnet/runtime/issues/72571#issuecomment-1191819042.

**Comment by mavnorthwind** [comment]
[This document](https://github.com/dotnet/sdk/blob/38ee26994c512ad3e53de801e06feddc73b47662/documentation/specs/runtime-configuration-file.md#runtimeoptions-section-runtimeconfigjson) describes the additionalProbingPaths setting.

**Comment by LakshanF** [comment]
The linked issue comment and the document seem to provide context for this issue

**Comment by vitek-karas** [comment]
.NET 6 intentionally doesn't have a way to add probing - the overall design is for the SDK to construct the entire app.

Note that while `additionalProbingPaths` can be used to achieve something like this, it's noteasy - the path this property points to is expected to look like NuGet's cache directory - so it needs certain structure for it work, otherwise it will be effectively ignored. It's definitely not just "also look into that directory" and it also only works for assemblies which are actually listed as part of the app in the `.deps.json` (so SDK knew about them). It will NOT work for `Assembly.Load` type of usage.

The code approach is the best solution for this - you can write your code to read the location from a config file of some sort.
