### ISSUE TITLE
testhost missing host files when building with different libraries and host configurations

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#73777]
### Description

To build on Linux Arm64 or X64 I use:
```
$ ./build.sh -rc checked -lc release
```

After building I would expect to see a fully populated testhost. Eg:
```
$ ls /home/alahay01/dotnet/runtime/artifacts/bin/testhost/net7.0-Linux-Release-arm64
dotnet  host/  shared/
```

Instead I just see a shared directory:
```
$ ls /home/alahay01/dotnet/runtime/artifacts/bin/testhost/net7.0-Linux-Release-arm64
shared/
```

Has something changed to stop the dotnet and host/ being generated?

### Reproduction Steps

On Linux:
```
$ ./build.sh -rc checked -lc release
```

### Expected behavior

artifacts/bin/testhost/net7.0-Linux-Release-arm64/ would contain a fully populated testhost, including dotnet and host/

Same with the X64 directory.

### Actual behavior

artifacts/bin/testhost/net7.0-Linux-Release-arm64/  contains only the shared/ contents. Same with the X64 directory.

### Regression?

This used to work for me.

### Known Workarounds

Don't know of any commands to force the missing pieces

### Configuration

Latest HEAD
ubuntu 18.04
Arm64 and X64

**Comment by elinor-fung** [comment]
I think this is due to mixed configurations not being respected properly now that the testhost uses a live build of the host (https://github.com/dotnet/runtime/pull/73095/files).

`./build.sh -rc checked -lc release` results in a checked runtime, release libraries, and debug host. 

The [project](https://github.com/dotnet/runtime/blob/main/src/libraries/externals.csproj) that creates the testhost gets built with its `Configuration` set to the libraries configuration (release in your case). When looking for the host binaries, it uses the same configuration:
https://github.com/dotnet/runtime/blob/209c040d261558d6d58ebf046e39491b22fb28f1/Directory.Build.props#L234

But since the host was actually built for debug, those binaries aren't found and aren't copied to the testhost directory.
https://github.com/dotnet/runtime/blob/3e0a5adaefc0936bdb8ec4b152914b5c996c97c6/src/libraries/externals.csproj#L35-L37

As a workaround, you can build using the same configuration for libraries and host:
`./build.sh -rc checked -c release`
or
`./build.sh -rc checked -lc release -c release`

**Comment by ViktorHofer** [comment]
> When looking for the host binaries, it uses the same configuration:

Should we change that so that the host uses the runtime configuration?

**Comment by a74nh** [comment]
> ./build.sh -rc checked -lc release -c release

This works for me ok. I'm happy with building like this from now on.
However, it's all a little confusing as to what does what.

> Should we change that so that the host uses the runtime configuration?

Alternatively - you could introduce a host configuration:
`./build.sh -rc checked -lc release -hc release`
It does make things more explicit.

However, that would mean
`./build.sh -rc checked -lc release -hc debug`
would end up in the situation I'm in now where the host build fails to find the binaries.

So, maybe going to to the host using the runtime configuration makes more sense.

**Comment by vitek-karas** [comment]
> Should we change that so that the host uses the runtime configuration?

I think it would make sense. It will make development of host a bit harder (everything will be slower), but consistent build system feels like a better idea.
