### ISSUE TITLE
UInt128 implicit casting

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#74001]
Consider following code (variant of this is frequently used by serializers):

```csharp
namespace Repro
{
    internal class Program
    {
        static void Main(string[] args)
        {
            byte test = 12; // same repro for ushort, uint
            Test(test);
        }

        static void Test(long value) => Console.WriteLine("long overload"); // currently picked overload
        static void Test(ulong value) => Console.WriteLine("ulong overload");
        static void Test(Int128 value) => Console.WriteLine("Int128 overload"); // note: no effect for Int128
        // now let's add:
        // static void Test(UInt128 value) => Console.WriteLine("UInt128 overload");
    }
}
```

now uncomment new UInt128 overload which will likely be added by libraries after net7.0 ships and now users of those libraries get compile error:

```
Error CS0121: The call is ambiguous between the following methods or properties: 'Program.Test(long)' and 'Program.Test(UInt128)'
```

I'm getting those errors both in the product and tests in https://github.com/dotnet/runtime/pull/73892 and have to workaround them by explicitly casting. Also this has broke source gen since now it produces no longer compiling code.

Is it possible for this behavior to be changed to somehow hint compiler to prefer `long`/`ulong` overload? Current behavior might be rather unexpected for users and might potentially be source breaking and I'd personally prefer this to be explicit cast if that's not possible since this is rather annoying.

Ignore this issue if this has been discussed already.

Note: There are possibly variants of this behavior for Int128 and casting from/to other numeric types but I'll leave this for the owner to figure out if needed.

cc: @tannergooding

**Comment by tannergooding** [comment]
CC. @jaredpar who can likely explain the language semantics behind this.

In general, however, we shouldn't rely on implicit conversions for these cases. Implicit conversions do not work well with some languages, such as F#. Likewise, due to how overload resolution works in languages like C# there are often odd rules for which gets picked for various primitive types and adding new types can subtly break or impact which overload is selected.

The "right thing" to do here is likely to explicitly expose `byte`, `sbyte`, `short`, `ushort`, `int`, and `uint` overloads so that the "correct" semantics can be explicit and not language dependent.

**Comment by jaredpar** [comment]
Think the reason for this is a bit clearer if you shrink down `UInt128` and `Int128` to these minimal representations:

```csharp
class Int128
{
    public static implicit operator Int128(byte b) => throw null;
    public static implicit operator Int128(long b) => throw null;
}

class UInt128
{
    public static implicit operator UInt128(byte b) => throw null;
    public static implicit operator UInt128(ulong b) => throw null;
}
```

Notice the implicit conversion from `long` to `Int128`. This serves as a tie break because it establishes the relationship between `long` and `Int128`. That means overload resolution can tie break between them. There is no such relationship between `long` and `UInt128`. In both cases `byte` to the type is an implicit conversion, no tie break between them because they have no relationship hence ambiguity. 

> In general, however, we shouldn't rely on implicit conversions for these cases.

+100.

**Comment by krwq** [comment]
So recommendation is to add extra overloads for serializers which might have ambiguity problem. Given that I think we can close this issue and I'll fix this in System.Text.Json by adding missing overloads. Thanks for clarifying @jaredpar and @tannergooding!
