### ISSUE TITLE
Nullability annotation missing on CacheControlHeaderValue.TryParse

### ISSUE THREAD

**Issue by FreeApophis** [dotnet/runtime#74061]
### Description

In the namespace System.Net.Http.Headers are many very specific header classes which all have their own TryParse method.

For the following classes TryParse was annotated:
`AuthenticationHeaderValue`, `ContentDispositionHeaderValue`, `ContentRangeHeaderValue`, `EntityTagHeaderValue`, `MediaTypeHeaderValue`, `MediaTypeWithQualityHeaderValue`, `NameValueHeaderValue`, `NameValueWithParametersHeaderValue`, `ProductHeaderValue`, `ProductInfoHeaderValue`, `RangeConditionHeaderValue`, `RangeHeaderValue`, `RetryConditionHeaderValue`, `StringWithQualityHeaderValue`, `TransferCodingHeaderValue`, `TransferCodingWithQualityHeaderValue`, `ViaHeaderValue`, `WarningHeaderValue`

It seems like `CacheControlHeaderValue` was overlooked.

### Reproduction Steps

This does not compile without a null-forgiving operator.

```cs
#nullable enable

CacheControlHeaderValue ParseHeaderOrThrow(string candidate)
    => CacheControlHeaderValue.TryParse(candidate, out var result)
        ? result
        : throw Exception("parse failed");
```

### Expected behavior

`CacheControlHeaderValue.TryParse` should have correct nullability annotations like the others, to avoid the unnecessary null-forgiving operator.

### Actual behavior

No nullability annotations.

**Comment by CarnaViire** [comment]
Triage: it is most possibly an oversight, but it is possible there was a reason for it. Nice to have, seems to be the first complaint since introducing nullability annotations. Moving to Future.

**Comment by MihaZupan** [comment]
Most header values support only a single value via `TryParse`, but `Cache-Control` is different.
For example, we will let you parse `public,max-age=3600` (two values) and turn that into a single `CacheControlHeaderValue`.

One side-effect (I don't know whether it was intentional) is that this header will allow parsing empty values.
For example, `CacheControlHeaderValue.TryParse(",, ,", out var value)` will return true, but `value` will be null.
But `Parse` is not annotated correctly. `CacheControlHeaderValue.Parse("")` will not throw, but just return `null`.

So I think there are a few ways of looking at this. Either:
- a) Allowing empty values is correct and we should mark `Parse` as nullable.
- b) Allowing empty values is correct and we should start returning empty `CacheControlHeaderValues` objects and mark `TryParse` with `NotNullWhen(true)`.
- c) Empty values shouldn't be allowed and we should start throwing/returning false in those cases and mark `TryParse` with `NotNullWhen(true)`.

**Comment by karelz** [comment]
Triage: `CacheControlHeaderValue` is unique, not like others and its ability to accept empty string makes lives of devs hard for all other headers.
We do not like to change the annotation to Nullable -- it would break users as they would have to change their code.
Throwing for empty string is even more breaking.
Returning empty value instead of null sounds like the best option - least impactful on users. We can also change `TryParse` annotation to NotNullable (which will match all other headers).

**Comment by karelz** [comment]
This should be fairly straightforward to do. It is not important for any release, but we would take a contribution.
@FreeApophis are you interested?

**Comment by Marusyk** [comment]
I'm interested in this PR. Can I start?

**Comment by pierrebelin** [comment]
Hey @karelz, since this issue is not important and not in a rush, can I take this one as first issue to start contributing?

**Comment by karelz** [comment]
Great, thanks! Assigning to you @pierrebelin
Let us know if things are more complicated than we expected.

**Comment by pierrebelin** [comment]
Of course, I'll try to do my best!

I have some issues when I try to build the project. I have installed .NET Runtime/SDK/ASP.NET Core 7.0 preview but it seems that all my dependencies are missing. Do you know what I missed ?

![image](https://user-images.githubusercontent.com/25244392/187497274-88bc1657-680f-44bc-9c89-76c5da20eb18.png)

**Comment by rzikm** [comment]
@pierrebelin in my experience, VS sometimes struggles with the runtime repo, but as long as it builds without errors you should be fine.

**Comment by pierrebelin** [comment]
I tried to build following the step you gave me : `build.cmd clr+libs -rc Release`
And I get this error:
![image](https://user-images.githubusercontent.com/25244392/187617014-f38ad587-863a-4a51-92ba-333815124dbc.png)

This is probably a installation missing...

If you want to take a look of what I have in VS:
![image](https://user-images.githubusercontent.com/25244392/187616955-a24d1d77-37df-45a4-9332-5c36051a44f0.png)

**Comment by rzikm** [comment]
The last BUILD: Error: line says it all, Visual Studio 2019 or 2022 with C++ tools are required. Did you try importing the .vsconfig in the Visual Studio Installer? Not sure if this thing requires a reboot.

**Comment by pierrebelin** [comment]
Yes, that's why I deleted my post... I think it's too late to open correctly my eyes. I'm gonna grab a coffee
