### ISSUE TITLE
Impersonation via Kerberos and HttpClient leads to TCP port exhaustion

### ISSUE THREAD

**Issue by rgueldenpfennig** [dotnet/runtime#74078]
I'm currently helping out one of my clients to solve the following issue.

First of all some details about the environment:

- Windows Server 2019
- IIS 10, Integrated Pipeline mode
- ASP.NET MVC application running on .NET Framework 4.8

Note: As this repository is only for the "new" .NET framework versions my question regarding to .NET 6 is following at the end :)

We are maintaining a custom developed reverse proxy that accepts requests by Windows users who are authenticated by Kerberos (Negotiate payload in the WWW-Authenticate header). 

The user principal and identity is then resolved by the ASP.NET pipeline and is accessible in the `HttpContext` as expected.

Every request will then be forwarded to the destination system by a static `HttpClient` instance while the `SendAsync` operation is encapsulated in a `WindowsImpersonationContext` like that:

```csharp
var identity = HttpContext.User.Identity;
using (identity.Impersonate())
{
  response = _httpClient.SendAsync(destinationRequest, HttpCompletionOption.ResponseHeadersRead).GetAwaiter().GetResult();
}
```

Note: We do not await this call due to context switching issues while the executing thread is impersonated. But that should not matter here.

Hereby the `HttpClient` is instantiated as a singleton for the application lifetime:
```csharp
_httpClient = new HttpClient(new HttpClientHandler
{
  UseDefaultCredentials = true,
  PreAuthenticate = true,
  AllowAutoRedirect = false,
  Timeout = TimeSpan.FromMinutes(10)
});
```

While we process hundreds of requests/second successfully we notice that the IIS application pool process is allocating dozens of TCP TIME_WAIT state connections when taking a look at `netstat -ano`.

This happens only when we execute the `HttpClient` while impersonated. Doing the same with a `HttpClient` that does not use default credentials and is executed without impersonation there are none or just a few TCP TIME_WAIT connections at all.

So it appears that the Kerberos negotiation protocol which is being executed by the impersonated `HttpClient` seems to open and close a TCP connection for every request before the actual request to the destination server is being done instead of reusing them.

This is also described in this StackOverflow question: https://stackoverflow.com/questions/51236268/static-httpclient-still-creating-time-wait-tcp-ports

Due to the high load of the reverse proxy we were only able to mitigate this behaviour by setting the `TcpTimedWaitDelay` to 30 seconds (default is 4 minutes) in the registry and to increase the available ephemeral port ranges which does not feel quite good.

## Main question
As far as I know the HTTP and TCP relevant classes have been greatly redesigned since .NET Core. 

1. Is this behaviour expected on .NET Framework 4.8?
2. And has this been fixed in the newer .NET versions as described in the StackOverflow question?

Thanks for any feedback!

**Comment by SteveSyfuhs** [comment]
What you're doing is requesting a new identity for each HTTP call. You have a service identity "proxy$" that accepted the identity in the frontend proxy and have produced an identity "alice". This is a fairly cheap operation because all the proxy service has to do is decrypt the ticket and voila--identity. Then as proxy$ what you're doing is saying "well, I need to take this alice identity and go off box". Well, that alice ticket to proxy$ can only be understood by proxy$; it's meaningless to any other server. Therefore, what you need to do is contact a domain controller as proxy$ and say "heeeeey DC, I'm proxy$ and have this ticket for alice, and now need to pretend to be alice when talking to backend$" and the DC returns a ticket to proxy$ as alice targeting backend$. Rinse and repeat for every request because these impersonated tickets cannot be cached.

That connection to the DC is over TCP, so you're eating outbound sockets there first. 

Second, the backend IIS service is going to keep that TCP session open because from its perspective it has no idea whether something higher up the stack is creating a more persistent binding for the authenticated connection, so it ties the first auth to the socket and leaves the socket open, that way any future communications over that socket can act as that identity. Once the socket closes you must repeat the auth dance.

Third, the HttpClient is almost certainly aware of this server behavior, so for every new identity (or whatever the decision mechanism is) it's going to see that the server kept the socket open, and therefore any additional calls as some other user must be over a new socket.

Why exactly are you doing it this way? Proxy impersonation is an incredibly expensive operation, especially if all you're doing is forwarding the request on to another server.

**Comment by rgueldenpfennig** [comment]
Thanks for your feedback @SteveSyfuhs 
Your overall description of the proxy functionality matches quite well.

> That connection to the DC is over TCP, so you're eating outbound sockets there first.

Here I'm not quite sure yet. Using `netstat` I was not able to find a huge bunch of outbound connections to any domain controller. Most of the time there are just a few connections sitting around in `ESTABLISHED` state.
I expected to see much more here but it seems that the `HttpClient` is reusing TCP connections here when talking to the KDC.

The huge bunch of outgoing TCP connections are connected to the destination backend side. Where most of them go directly into `TIME_WAIT` state.

And this makes me guess that the `HttpClient` is opening and closing a TCP connection for every impersonated request. Maybe due to prevention of false credential sharing?

That's the reason why I have the theory in mind that the new `System.Net` stack is having an optimized behaviour were different identities my be able to share the same TCP connections.

> Why exactly are you doing it this way? Proxy impersonation is an incredibly expensive operation, especially if all you're doing is forwarding the request on to another server.

I'm also very aware of the performance and operation cost due to the impersonation of every Windows authenticated request. My customer already implemented this some time ago and on lesser active productive systems it's already running. The use case is to force the user to provide additional authentication factors while using the reverse proxy before the request is going through to the final destination backend which is not available directly to any client due to network configurations.

Simply described it's like that:

`Client with Kerberos ticket -> Reverse Proxy -> Validating additional authentication & impersonating client -> copy and execute original request to destination server`

**Comment by wfurt** [comment]
Yes, I think the identity management is the main issue. As far as 4.8, I don't think we would touch it. That could be major initiative and risk and since 4.8 is really in maintenance mode I don't think this would meet the servicing bar. 

In .NET Core we had few issues where wrong credentials were used. (#38414 and #58033 for example)
With #303 and #58922 I think it should work better. The Identity is part of the connection lookup now so it should find previous connection for given user. It is still not cheap as each impresonification will create new thread  but at least the port issue should go away.
 
It seems like we do not have any test to verify that same identity would re-use existing connection. 
But I think it would be reasonable to try it with 6.0+ and report if that does not work @rgueldenpfennig

**Comment by rgueldenpfennig** [comment]
@wfurt Thanks for providing the additional info.

In the meantime I was able to test and compare the basic implementation with both .NET Framework 4.8 and .NET 6.

The results are quite confident. For now the port exhaustion issue due to the high number of TCP connections in `TIME_WAIT` state is mitigated. .NET 6 seems to reuse the established TCP connections as expected instead of creating always a new one.

The high rate of KDC TGS requests on the side of the DCs is also much decreased. It seems that .NET 6 has a caching algorithm for the acquired Kerberos tickets when doing impersonation. Maybe someone has additional info on that?

Additionally the performance regarding the throughput has increased greatly by nearly doubling it.

I hope I will be able to provide the repro here in the upcoming days.

**Comment by wfurt** [comment]
good to know. Thanks for the feedback @rgueldenpfennig
