### ISSUE TITLE
Fix all tests under test\src\readytorun to work with the crossgen2 run

### ISSUE THREAD

**Issue by fadimounir** [dotnet/runtime#743]
These tests are disabled (ex: see https://github.com/dotnet/runtime/pull/741) because they have explicit crossgen.exe commands that produce .ni.dll images.

The presence of these images is tripping crossgen2.
Also, these tests are not giving the coverage we need with crossgen2 currently, so that needs to be fixed.

We can fix them by doing something like:
```
if (RunCrossgen2 is set)
    compile using crossgen2.exe
else
    compile using crossgen.exe
```

**Comment by janvorli** [comment]
There is also a bug in the test scripts that expects that the tests assemblies are .exe instead of .dll. So the invocation of the old crossgen fails due to that. I assume this is a remnant from the time before we've migrated the test projects to use SDK style project files.
I actually wonder what is the right way to make these tests work with crossgen2. The problem is that the tests themselves always crossgen their components even when no RunCrossGen or RunCrossGen2 are set. This is needed as otherwise they would not make sense. Now the question is how to make them choose between crossgen and crossgen2 for this case.

**Comment by davidwrighton** [comment]
This isn't going to happen in .NET 5

**Comment by trylek** [comment]
@janvorli / @davidwrighton, could you please help me understand the current status here? I believe that, as of today,

https://github.com/dotnet/runtime/blob/45287ed696a4bea906cc15a4bc870960a4b0e623/src/tests/Common/CLRTest.CrossGen.targets#L70

has full support for CG / CG2 switching on both Windows and Linux. I went over the 20 CoreCLR tests defining &lt;CrossGenTest&gt;false and I haven't found any remaining ones with hardwired CG1 logic -

https://github.com/dotnet/runtime/blob/45287ed696a4bea906cc15a4bc870960a4b0e623/src/tests/JIT/Regression/JitBlue/GitHub_25027/GitHub_25027.ilproj#L4

and the remaining negative tests like

https://github.com/dotnet/runtime/blob/45287ed696a4bea906cc15a4bc870960a4b0e623/src/tests/Loader/classloader/generics/Instantiation/Negative/abstract02.ilproj#L7

and

https://github.com/dotnet/runtime/blob/45287ed696a4bea906cc15a4bc870960a4b0e623/src/tests/Regressions/coreclr/16354/notimplemented.ilproj#L8

anecdotally claim that they are not intended for CG testing while the rest reside under the <code>readytorun</code> subfolder and typically contain specific provisions for running CG1 / CG2 in special ways on purpose. Do we still need this work item?
