### ISSUE TITLE
System.IO.Ports.SerialPort not working on Linux arm64

### ISSUE THREAD

**Issue by GeorgeStephens** [dotnet/runtime#74332]
### Description

'Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies

Similar to issue #63187 though Linux versions differ. Presumably the same root issue.

### Reproduction Steps

Create new console app (.net 6.0)
Add `System.IO.Ports` NuGet.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RuntimeIdentifier>linux-arm</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
  </ItemGroup>

</Project>
```

```
using System.IO.Ports;

namespace RaspberryPiIoTTestApp02
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");

            string[] ports = SerialPort.GetPortNames();
            // Display each port name to the console.
            foreach (string p in ports)
            {
                Console.WriteLine($"GetSerialPorts(): {p}");
            }

            string _portName = "/dev/ttyAMA1";
            SerialPort port = new SerialPort(_portName);
            port.BaudRate = 19200;
            port.DataBits = 8;
            port.Parity = Parity.Even;
            port.StopBits = StopBits.One;
            port.Open();
        }
    }
}
```

### Expected behavior

Program runs.

Prints out available serial ports, (in my case)
```
GetSerialPorts(): /dev/ttyAMA1
GetSerialPorts(): /dev/ttyAMA2
GetSerialPorts(): /dev/ttyAMA0
```

Opens port `/dev/ttyAMA1`

### Actual behavior

Program runs.

Prints out available serial ports, (in my case)
```
GetSerialPorts(): /dev/ttyAMA1
GetSerialPorts(): /dev/ttyAMA2
GetSerialPorts(): /dev/ttyAMA0
```

Exception at `port.Open();`

```
Exception thrown: 'System.DllNotFoundException' in System.IO.Ports.dll
An unhandled exception of type 'System.DllNotFoundException' occurred in System.IO.Ports.dll: 'Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSystem.IO.Ports.Native: cannot open shared object file: No such file or directory'
Stack trace:
 >   at Interop.Serial.SerialPortOpen(String name)
 >   at System.IO.Ports.SafeSerialDeviceHandle.Open(String portName)
 >   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
 >   at System.IO.Ports.SerialPort.Open()
 >   at RaspberryPiIoTTestApp02.Program.Main(String[] args) in C:\Users\georg\OneDrive\Documents\Visual Studio\2022 - vs22\RaspberryPiIoTTestApp02\RaspberryPiIoTTestApp02\Program.cs:line 17
```

Setting `LD_DEBUG=all` gives some info though unfortunately its all a bit beyond me!

```
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/libSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/libSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=libSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	find library=libSystem.IO.Ports.Native.so [0]; searching
      5612:	 search cache=/etc/ld.so.cache
      5612:	 search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib		(system search path)
      5612:	  trying file=/lib/aarch64-linux-gnu/libSystem.IO.Ports.Native.so
      5612:	  trying file=/usr/lib/aarch64-linux-gnu/libSystem.IO.Ports.Native.so
      5612:	  trying file=/lib/libSystem.IO.Ports.Native.so
      5612:	  trying file=/usr/lib/libSystem.IO.Ports.Native.so
      5612:	
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/liblibSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/liblibSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/liblibSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=liblibSystem.IO.Ports.Native.so [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	find library=liblibSystem.IO.Ports.Native.so [0]; searching
      5612:	 search cache=/etc/ld.so.cache
      5612:	 search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib		(system search path)
      5612:	  trying file=/lib/aarch64-linux-gnu/liblibSystem.IO.Ports.Native.so
      5612:	  trying file=/usr/lib/aarch64-linux-gnu/liblibSystem.IO.Ports.Native.so
      5612:	  trying file=/lib/liblibSystem.IO.Ports.Native.so
      5612:	  trying file=/usr/lib/liblibSystem.IO.Ports.Native.so
      5612:	
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/libSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/libSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=libSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	find library=libSystem.IO.Ports.Native [0]; searching
      5612:	 search cache=/etc/ld.so.cache
      5612:	 search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib		(system search path)
      5612:	  trying file=/lib/aarch64-linux-gnu/libSystem.IO.Ports.Native
      5612:	  trying file=/usr/lib/aarch64-linux-gnu/libSystem.IO.Ports.Native
      5612:	  trying file=/lib/libSystem.IO.Ports.Native
      5612:	  trying file=/usr/lib/libSystem.IO.Ports.Native
      5612:	
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/liblibSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/liblibSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=/home/pi/vsdbg/RaspberryPiIoTTestApp02/liblibSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	
      5612:	file=liblibSystem.IO.Ports.Native [0];  dynamically loaded by /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.8/libcoreclr.so [0]
      5612:	find library=liblibSystem.IO.Ports.Native [0]; searching
      5612:	 search cache=/etc/ld.so.cache
      5612:	 search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib		(system search path)
      5612:	  trying file=/lib/aarch64-linux-gnu/liblibSystem.IO.Ports.Native
      5612:	  trying file=/usr/lib/aarch64-linux-gnu/liblibSystem.IO.Ports.Native
      5612:	  trying file=/lib/liblibSystem.IO.Ports.Native
      5612:	  trying file=/usr/lib/liblibSystem.IO.Ports.Native
      5612:	

```

Note that the exception appears on `port.Open();` not when an instance of `SerialPort` is created or when we're getting all available serial ports.

### Regression?

Unknown though though the notnet/iot team have example code for Controlling Arduino with .NET using Raspberry Pi via serial port [here](https://github.com/dotnet/iot/tree/main/samples/serialport-arduino) using `System.IO.Ports -v 4.6.0-preview.18571.3`. It may be that they are using ARM (32-bit) that is unaffected by this or it is a regression.

### Known Workarounds

Unknown though some people have reported work arounds in issue #63187.

### Configuration

Which version of .NET is the code running on? **.NET 6.0**
What OS and version, and what distro if applicable? **Raspberry Pi OS - 64-bit - Lite**
What is the architecture (x64, x86, ARM, ARM64)? **ARM64**
Do you know whether it is specific to that configuration? **It appears to be affecting other versions of linux through similar issues** #63187

**Comment by krwq** [comment]
can you try removing `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` and `<PlatformTarget>AnyCPU</PlatformTarget>` from your csproj and run the app with `dotnet run` and see if still repros?

**Comment by GeorgeStephens** [comment]
Removing `<PlatformTarget>AnyCPU</PlatformTarget>` leads to:

`An unhandled exception of type 'System.BadImageFormatException' occurred in Unknown Module.: 'Could not load file or assembly '/home/praysio/vsdbg/RaspberryPiIoTTestApp02/RaspberryPiIoTTestApp02.dll'. An attempt was made to load a program with an incorrect format.'`

Removing `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` makes no difference:

`An unhandled exception of type 'System.DllNotFoundException' occurred in System.IO.Ports.dll: 'Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSystem.IO.Ports.Native: cannot open shared object file: No such file or directory'`

**Comment by danmoseley** [comment]
@krwq  where is "libSystem.IO.Ports.Native.so" supposed to be on disk?

**Comment by GeorgeStephens** [comment]
Running `sudo find / -name "libSystem.IO.Ports.Native.so"` provides the following:

```
/home/pi/vsdbg/RaspberryPiIoTTestApp02/linux-arm/libSystem.IO.Ports.Native.so
/home/pi/vsdbg/RaspberryPiIoTTestApp02/libSystem.IO.Ports.Native.so
```

@krwq it appears that removing `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` did actually make a difference in that for an apps where I haven't removed `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>`  don't appear to have `libSystem.IO.Ports.Native.so` in the `/linux-arm/` sub directory. They still fail with the same exception though.

**Comment by krwq** [comment]
it supposed to come from https://www.nuget.org/packages/runtime.native.System.IO.Ports ([or one of these](https://www.nuget.org/packages?q=system.io.ports.native) to be more specific) and be published along with the app.

@GeorgeStephens can you perhaps try publishing app `dotnet publish -f ... -r ... --self-contained` and replace libSystem.IO.Ports.Native.so with i.e. arm64 version coming from the nuget package (you should be able to simply use curl to download a package and unzip it, i.e. https://www.nuget.org/api/v2/package/runtime.linux-arm64.runtime.native.System.IO.Ports/7.0.0-preview.7.22375.6) and see if any of them works for you? If any of them works it would be good to know which one. Is it possible you should be using `linux-arm64` rather than `linux-arm`?

Worst case scenario you can try building dotnet/runtime on your machine (`./build.sh -rc Release -s clr+libs` then search `artifacts` folder for the `libSystem.IO.Ports.Native.so`) and simply copy paste the .so file to your output directory to temporarily unblock yourself while we figure out how to fix this properly

**Comment by jeffhandley** [comment]
I'm moving this issue to Future and applying `needs-author-info` while we gather more info (to keep this issue from showing up in our 7.0 release queries since it isn't specific to 7.0).

**Comment by williambowsher** [comment]
I have been trying to use the Serial Port on a Raspberry Pi 3 with Raspberry OS installed, 
I have tried using /dev/ttyS0, /dev/serial0, /dev/ttyAMA0 and /dev/serial1 with various dtoverlays but they all give the same error

System.DllNotFoundException: Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSystem.IO.Ports.Native: cannot open shared object file: No such file or directory
   at Interop.Serial.SerialPortOpen(String name)
   at System.IO.Ports.SafeSerialDeviceHandle.Open(String portName)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at Drivers.Gps.GTU7.ReadStream() in C:\Projects\SecureArt\Drivers\Gps\GTU7.cs:line 20
   at Services.Sensors.GpsReceiverService.ProcessAdaptor(Object sensor) in C:\Projects\SecureArt\Services\Sensors\GpsReceiverService.cs:line 41
   at Services.Sensors.GpsReceiverService.Start() in C:\Projects\SecureArt\Services\Sensors\GpsReceiverService.cs:line 35
   at Services.HostedService.IotDeviceHostedService.<StartAsync>b__6_1() in C:\Projects\SecureArt\Services\HostedService\IotDeviceHostedService.cs:line 48

I can see the libSystem.IO.Ports.Native.so file is in the vsdbg\Client folder.
The only NUGET package I have included is the System.IO.Ports, as all the native packages say that they should not be referenced directly.

I have also tried with a RID of linux-arm and linux-arm64

**Comment by PRIMETSS** [comment]
Trying this on OpenWRT of RiPi, which is an Alpine like linux-musl-arm64
Latest SDK 6.0.402 and 7.0.100-rc.2

Publishing a ASPNET Web App for standalone for linux-musl-arm64
Sever runs and severs HTML pages ok, but if try do a `System.IO.Ports.SerialPort.Open();`
`System.IO.Ports.SerialPort.GetNames();` works fine (which stung me as I was using that as quick test to see if System.IO.Ports lib was working on on different hardware.

![image](https://user-images.githubusercontent.com/11331370/197375263-1407f18c-5db8-4954-a1b0-d2cdd0b15ed6.png)
If check libSystem.IO.Ports.Native.so, shows ld-linux-aarch64.so.1 Is missing
![image](https://user-images.githubusercontent.com/11331370/197375317-d8f98184-b5d6-4513-91bb-027deaeefd54.png)
As its linux-musl and has ld-musl-aarch64.so.1
![image](https://user-images.githubusercontent.com/11331370/197375532-62162c1f-ccbf-4575-b56e-4159cddcbd1f.png)

So as people have said before, is this a problem with what libSystem.IO.Ports.Native dependencies it gets built with for certain linux-arm RID's?

**Comment by PRIMETSS** [comment]
Obviously NOT a fix, but work around, not have USB Serial port (actually FTDI device) opening and communicating `System.IO.Ports.SeriialPort()` by duplicating ls-musl-aarch64.so.1 to `ld-linux.aarch64.so.1` on OpenWRT which runs a musl-arm64 version of 
![image](https://user-images.githubusercontent.com/11331370/197932640-6498cc85-ae6a-4a97-86d4-67e35bbcc0c9.png)

So still seems something wrong happening when building `libSystem.IO.Ports.Native.so`

This maybe seem to be addressing it, but preview SDK 7.0.100-rc.2 still issue
[https://github.com/dotnet/runtime/issues/75636](https://github.com/dotnet/runtime/issues/75636)

**Comment by markbeau** [comment]
This is an issue for me as well. Can we keep this issue open?

**Comment by PRIMETSS** [comment]
@markbeau I just tried this as I had a OpenWRT Pi all configured (same project I was having issues with above)  and can now get SerialPorts (FTDI USB) opening and R/W with latest SDK

On Pi installed OpenWrt SNAPSHOT, r21087-288b36c2ea (was latest daily at the time, obviously later versions now avail) then installed DotNet SDK 7.0.102 (pretty sure worked with .100 too) copied over serial port project, built and run locally.
SerialPort works as expected.

Let me know, if till have issues we can communicate direct. Looks like System.IO.Ports has had quite a few refactoring commits last 6 months+ and more stable on more Linux architectures.

**Comment by markbeau** [comment]
@PRIMETSS Thanks for the input. Sorry I didn't provide more specifics before. 

This is a background services app which communicates with a sensor device via serial IO, /dev/tty/AMA0 via the PL011 (bt) UART port.  It's been running on a Pi 3, Raspberry Pi OS 32-bit lite.  

I ran into the 'unable to load shared library' exception on System.IO.Ports.SerialPort.Open() when I deployed the app, recompiled with .NET 7.0.102 and updated packages, to a fresh Pi 4 running Raspberry Pi OS 64-bit lite.

The same bits work on the Pi 4 imaged instead with Raspberry Pi OS 32-bit.  But I'd like to find a path to 64-bit. 

It's interesting that you no longer see the issue on OpenWRT.  Is it possible they've addressed something Raspberry Pi OS hasn't caught up with yet?

**Comment by PRIMETSS** [comment]
Yes sounds like it. Or something is happening in the source build pipeline for that combination of runtime & architecture, the switching combinations during build can get complex to follow.
I've gone over the dotnet runtime Repo several times to look at how the native libs are built but starting to wonder if it's actually a problem in the SDK, and that repo I am not familiar with.

I know people use it, but is Raspbian officially supported by .dot net 7?
What is the --runtime your targeting during build? And you're building on the device using an installed SDK or PC and building for Alpine or something and ARM64 ?
What's the error your getting, same as above missing libSystem.IO.Ports.Native ?

What happens when you CD into the project folder (bin) and run `ldd` on the library? ` ldd libSystem.IO.Ports.Native.so` As below?
https://github.com/dotnet/runtime/issues/74332#issuecomment-1288010254

Are you building a Self-Contained app or runtime dependant, tried both?
Out of pure curiosity can you run this & send back just the relevant-interesting OS/bitlevel/etc Environment fields?
[https://github.com/PRIMETSS/DotNetCoreOpenWRTLinux32](url)

**Comment by markbeau** [comment]
Raspberry Pi OS 32/64-bit is based on Debian 11, and as much as I can infer in Microsoft's [documentation](https://learn.microsoft.com/en-us/dotnet/iot/deployment), is supported in .NET 7.  
 
My problem is that I'd left the target runtime in .csproj set to linux-arm when it needs to be linux-arm64. 
It's all working now as expected, either runtime dependent or self-contained. 

Your questions got me aimed in the right direction.  Thank you very much for your help!

**Comment by PRIMETSS** [comment]
I find using the CLI dotnet with command line switches eg [`dotnet publish -c Debug -r linux-musl-arm64 --sc`] is often better than using latest upgrade of VS2022 IDE as it tends to lack new configuration features. Although since they swapped to new Project Properties config menu it is getting closer.
