### ISSUE TITLE
XML Test/Validation for handling of w3.org redirect changes

### ISSUE THREAD

**Issue by spyder007** [dotnet/runtime#74382]
[w3.org](https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/) is planning on disabling non-SSL traffic to their sites, favoring redirects to SSL for all documents.  This includes all of their schema documentation, such as http://www.w3.org/2001/XMLSchema.

w3.org performed a "test" today in which they turned on these https redirects, and the results were not great.  We noticed issues with schema validation (particularly as it relates to SAML) within a few of our Java clients.  Additionally, we are still tracing some issues in our ASP.NET 5.0 application.  These issues centered around SAML, specifically around validating XML schemas.

Is there any way to confirm that redirects that w3.org are implementing will not adversely affect the parts of ASP.NET core that deal with XML schema validation?  w3.org plans on another redirect test Sept. 1 through Sept 3, and we'd like to have a plan in place to verify that our sites will continue to work with this change, as well as make any necessary changes/updates as necessary.

Any insights that anyone has would be much appreciated!

**Comment by bartonjs** [comment]
The "easiest" way I can think of to test it is to

* Open an HTTP listener on port 80, redirect all traffic to https://whatever/was/requested
  * You could also log all the URLs that were requested to see if there's perhaps a beneficial code change to be made, since redirects aren't free.
* Open a TCP listener on port 443, forward all traffic to w3.org
  * Or do super fancy stuff with SNI, but... nah.
* Edit your hosts file to claim that service is w3.org, www.w3.org, etc.

The easierest way I can think of to test it is if W3C was hosting that themselves (e.g. "tell your hosts file that [some IP] (redirects.w3.org) is w3.org/www.w3.org/etc"), but I don't see in their memos that they've done that as a public testing service.

I can't think of anything in .NET that would be bothered by it... at least not off the top of my head.

**Comment by spyder007** [comment]
@bartonjs Thanks for the feedback.

We saw some errors come through our ASP.NET Core Oauth2 provider, but I am starting to believe that these were messages that came from the identity providers we were talking to, not our platform.  It also does not help that, during w3.org's most recent test, the https file was also unavailable, meaning they were, for a time, redirecting http:// to a page that wasn't being served.

If I find some time this week i'll try your suggestion to see if I can get a local test running before w3.org starts their next test on Sept. 1.

**Comment by krwq** [comment]
@spyder007 please share your findings and if there are any specific work items we should do I'll recommend to create new issue per work item in the relevant repo

**Comment by spyder007** [comment]
Closing this issue:  redirects were put in place last year, so any issues with them would have been seen by now.  Apologize for this staying open for so long.
