### ISSUE TITLE
Namespace System.Numerics.Generic - IEEE 754 and custom number types

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#74475]
### I would like to propose a template solution to support IEEE 754 floating-point and decimal types in arbitrary size.

A implementation for floating-point already exists and can be tested: [Generic.Float.cs](https://github.com/c-ohle/RationalNumerics/blob/master/System.Numerics.Rational/Generic.Float.cs)

The function set is identical to the system's other floating-point types and current NET7 naming conventions. `INumber` / `IBinaryFloatingPointIeee754` is fully supported.
For the user it is easy to use and to define number types in any desired precision: 

![image](https://user-images.githubusercontent.com/63112403/186301640-89fb463b-2fa9-4995-89bc-cf218cba8f4c.png)

Difference to the system types are only the constants implemented as static properties.

![image](https://user-images.githubusercontent.com/63112403/186305808-86829c7c-73b6-421f-a2df-c562e5caefe2.png)

It's not all about to have floating-point for higher precision. It is also to support old and new special formats like Extended [Float80](https://github.com/c-ohle/RationalNumerics/blob/65f22629e062ce467a13f3851a46ea6dcbee6f0e/System.Numerics.Rational/Generic.Types.cs#L308) or to emulate the processors with specific internal precisision, rounding modes etc. 
To make this easy the solution includes a `IFloat<T>` template that allows to implement new special number types based on `Float<T>` that inherit the base functionality inclusive all the `INumber` interfaces.
Examples for this can be found here: [Generic.Types.cs](https://github.com/c-ohle/RationalNumerics/blob/master/System.Numerics.Rational/Generic.Types.cs)

### How it works

The template type definition is simple as possible. 
The template parameter defines the struct size and the struct size the default IEEE 735 floating-point type and the binary layout:

```csharp
public readonly struct Float<T> where T : unmanaged
{
  readonly T p;
}
```
Based on this principle, a set of number type templates are possible, which could stay in a namespace `System.Numerics.Generic`:

![image](https://user-images.githubusercontent.com/63112403/186325528-72c8775d-19b9-4ee6-848f-1215b8b2f74e.png)

(The implementation for `Decimal<T>` is already in work.)

Internally, all template-based number types can use the same calculation core. Once initialized, this core does not require any further memory allocation at runtime. Since the number data is stored in the fixed size defined in the template, calculations with such number types can be performed without memory allocations. This is in contrast to other arbitrary number types such as BigInteger or BigRational, where dynamic buffers are required.

### API Proposal

```csharp
namespace System.Numerics.Generic;

// see: https://github.com/c-ohle/RationalNumerics/blob/master/System.Numerics.Rational/Generic.Float.cs
public readonly struct Float<T> : IFloat<Float<T>>, IComparable<Float<T>>, IEquatable<Float<T>>, IComparable, ISpanFormattable where T : unmanaged
{
}

// see: https://github.com/c-ohle/RationalNumerics/blob/master/System.Numerics.Rational/Generic.IFloat.cs
public interface IFloat<T> : IBinaryFloatingPointIeee754<T>, IMinMaxValue<T> where T : unmanaged, IFloat<T>
{ 
}

```

### API Usage

```csharp
// nothing special, native arithmetic:

Float128 a, b, c;
a = 1;
a = 1.5f;
a = 1.5m;
a = 1.5;      
b = Float128.Sqrt(a);
c = a * b + a / b;      

var d = (double)c;
var e = (decimal)c;
var s = b.ToString("G100"); // but much more precision
```

**Comment by tannergooding** [comment]
Thanks for the interest in this area!

For providing some "big float", the most likely name would be `BigFloat` and it would ultimately not be generic as it has no need. It would internally track an array or other allocation and need to follow the IEEE 754 requirements that it be at least 128-bits. It would likewise always be a multiple of 32 in terms of "total bits" used to represent the `binary floating-point value`.

Some corresponding `IEEE 754 decimal floating-point value` would then be called `BigDecimal` and similarly follow the IEEE 754 requirements.

Due to the nature of `IEEE 754` floating-point values, changing the precision would need to be an "explicit" action.

There would then be no need for some `IFloat` interface as `BigFloat` would simply implement `IBinaryFloatingPointIeee754<BigFloat>` and `BigDecimal` would likewise implement `IDecimalFloatingPointIeee754<BigDecimal>.

I'm going to close this as I don't believe the current proposal is in the shape or direction that we'd want to take this. As part of .NET 8 planning, the `dotnet/area-system-numerics` group is going to take a closer look at these areas and will be opening a meta issue to track larger feature requests, such as this or `Rational`/`BigRational`. We will lay down some of the more core requirements around those types and likely put up a proposal covering the intended API shape.

**Comment by c-ohle** [comment]
@tannergooding Hi, it is not a BigFloat. 
The number data is stored in fixed size defined by the template parameter.
e.g. Float<UInt128> results in a Float128 fixed-point type.
e.g. A 80 bit struct size as parameter results in a 80-bit Extended floating-point number type.
There is no array inside. It is not a BigRational. It is total different from the solutions we discussed so far.
Please try to understand and give it at least a chance so far there are no strong arguments against such solution.

**Comment by c-ohle** [comment]
@tannergooding 

> There would then be no need for some IFloat interface as BigFloat would simply implement IBinaryFloatingPointIeee754<BigFloat> and BigDecimal would likewise implement `IDecimalFloatingPointIeee754.

This is really something to discuss. So far I found no better solution. It is to allow more specific implemenations based on the templates to overwrite cast operators etc. For every of such sub-number type it would be necessary to implement IBinaryFloatingPointIeee754 completely new. But the `IFloat<T>` solution solves this problem as can be applyed to such types.
Example: [Float128](https://github.com/c-ohle/RationalNumerics/blob/d1d2d7756d3871a762363673811fb7b160f9fd49/System.Numerics.Rational/Generic.Types.cs#L18)

**Comment by tannergooding** [comment]
> Hi, it is not a BigFloat.
The number data is stored in fixed size defined by the template parameter.

Then I don't believe this is something we'd be interested in providing from the BCL as providing non-standard or largely deprecated formats, such as the 80-bit "extended-precision" format provided by the x87 FPU, is a non-goal of the BCL. Adding more "custom" formats is likewise problematic and comes with many negative downsides.

We may in the future provide an IEEE 754 `binary128` type (sometimes called `Quad`), but that would be an explicit `Float128` or similar name. We may likewise in the future provide some `BigFloat` type, but that would likewise follow the IEEE 754 requirements and would match existing BCL patterns to ensure that developers can easily use and intuitively understand the type and its API surface.

Having a type that takes a `T` but which doesn't actually use the `T` for anything other than sizing information is problematic on multiple levels and I don't see such a proposal ever passing API review. It also comes with numerous usability concerns since a user could pass in `(byte, Guid, nuint)` and due to the `AutoLayout` mechanics of `ValueTuple` it may differ in size and behavior across different platforms/architectures.

> For every of such sub-number type it would be necessary to implement IBinaryFloatingPointIeee754 completely new.

This is normal and expected. Default Interface Members (DIMs) are largely meant to be a temporary "catch" for functionality that is rarely used or new functionality which types haven't been able to provide themselves yet. There can be hidden costs in terms of calling such DIMs in the form of boxing (for value types) and inefficient or incomplete implementations, so the ideal is that most types end up providing their own implementation anyways.

Such an interface is not something we would be interested in providing through the BCL and its not something we could recommend that most developers consider implementing for their types.

**Comment by c-ohle** [comment]
@tannergooding 
> Having a type that takes a T but which doesn't actually use the T for anything other than sizing information is problematic

Ok. The plan for NET 7 is to constrain the type parameter with a static abstract interface definition that can also provide very type and processor specific information. To emulate internal precision, rounding modes etc like for SIMD, reduced precision,...not just old stuff like x87.
It should be clear that this is easy to implement.

**Comment by tannergooding** [comment]
Ease of implementation is not the only consideration for adding types to the BCL.

We must also consider usability, consistency, performance, how many customers are asking for such functionality, if other frameworks/languages/runtimes provide equivalent functionality, if there is any standardized spec around the functionality, long term maintenance cost, target audience, and much more.

The type you've described above is not something we'd be interested in providing from within the BCL at this time. If such a type is useful to you, then I encourage you to continue as you've already done by creating your own repository with the relevant types/API surface and then publishing your own 3rd party NuGet package.

I would not recommend continuing to place unofficial types, even in your own repository, under the `System.*` namespace (or any other namespace that is "owned" by the BCL). Placing types into namespaces you don't own risks causing downstream confusion to consumers and can potentially cause later conflicts, such as if the BCL decided to expose a `Float128` type in the `System.Numerics` namespace.

**Comment by c-ohle** [comment]
@tannergooding step by step:

I can make such T type solution for tomorrow. Internally, the desired props are already in use, but kept as static flags for compatibility with NET 6.

I am currently writing an API proposal for the `IFloat<T>` problem, where I explain the situation in detail, maybe there is already a workaround or something is planned. But it's more about making implementations easier. In any case, a T-constraint would also make this solution safe and efficient.

**Comment by c-ohle** [comment]
@tannergooding 
> We must also consider usability, consistency, performance, how many customers are asking for such functionality

Ok, it's probably the best to publish this as idea in discussions. Maybe it gives constructive feedback and new ideas.
