### ISSUE TITLE
NCL stress tests fail to build since ProductVersion update to 8.0.0

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#74604]
In #61689 HttpStress and SslStress has been updated to utilize the live-built runtime with the help of `targetingpacks.targets` in a manner similar to our unit and functional tests.

Builds are broken since #73985: with `ProductVersion` still set to 7.0.0 in our tests, we get the usual framework resolution error "`You must install or update .NET to run this application`".

However, bumping `ProductVersion` in our [`Directory.Build.props`](https://github.com/dotnet/runtime/blob/48713582dd5a8a27e4d1439725777250d0694ed9/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Directory.Build.props#L10) seems to be insufficient. After setting it to `8.0.0`, `<testhost>/dotnet.exe exec HttpStress.dll` reports the following error:

```
The specified framework 'Microsoft.NETCore.App', version '7.0.0-rc.1.22422.12', apply_patches=1, version_compatibility_range=patch cannot roll-forward to the previously referenced version '8.0.0'.
```

Note that one tricky detail is that we need to use the `7.0.0` `Microsoft.AspNetCore.App` runtime (currently `7.0.0-rc.2.22424.4`) together with the live-built `Microsoft.NETCore.App`.

@ViktorHofer any idea how to solve this, or what should be my next troubleshooting step? This is a high-priority issue, since we need to get stress tests running to stabilize QUIC / HTTP3.

**Comment by wfurt** [comment]
do we use custom NuGet config? We may need to add dotnet-8 feed.....
There were also some variables to roll forward on version.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/pull/74157 will update the assembly versions to 8.0.0.0. I expect that change to go in soon. It sounds like that won't help you in this case as you control these versions yourself and don't import the repo infrastructure.

> Builds are broken since https://github.com/dotnet/runtime/pull/73985: with ProductVersion still set to 7.0.0 in our tests, we get the usual framework resolution error "You must install or update .NET to run this application".

This broke because the testhost folder path contains the `$(ProductVersion)` which got changed from 7.0.0 to 8.0.0. So changing your hardcoded `$(ProductVersion)` version is the right thing to do. Note that such hardcodes are very fragile and will break at least once per year when change the ProductVersion property.

> However, bumping ProductVersion in our [Directory.Build.props](https://github.com/dotnet/runtime/blob/48713582dd5a8a27e4d1439725777250d0694ed9/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Directory.Build.props#L10) seems to be insufficient. After setting it to 8.0.0, <testhost>/dotnet.exe exec HttpStress.dll reports the following error:

Can you please provide me a binlog so that I can take a closer look? It's hard for me to diagnose this as you have your own  custom infrastructure and don't use any of the repo settings. Again this is very fragile as we might change some of these artifacts paths in the future (like the testhost path) by changing their underlying msbuild property. I would be good if you could find a more robust way to calculate inputs that you depend on.

**Comment by antonfirsov** [comment]
@ViktorHofer attached my binlogs:
[binlogs.zip](https://github.com/dotnet/runtime/files/9434151/binlogs.zip)

>  this is very fragile as we might change some of these artifacts paths in the future (like the testhost path) by changing their underlying msbuild property

I created the current solution based on the recommendation in https://github.com/dotnet/runtime/issues/60769#issuecomment-951332931, using `targetingpacks.targets` as a minimal dependency from the eng infra. If you have specific recommendations, I can try to pull in more bits of that infrastructure but then we need a robust way to copy the necessary bits to the stress test docker image (we don't copy the whole repo). Note we are also fine with the current setup where a change in eg. `Versions.props`  requires trivial changes from us (eg. to update our `Directory.Build.props`). The problem comes when we encounter unexpected issues, like in the current case where updating ProductVersion did not fix the problem for some reason.

**Comment by antonfirsov** [comment]
> do we use custom NuGet config? We may need to add dotnet-8 feed.....

@wfurt we don't as far as I'm aware, and I don't see how could a dotnet-8 feed feed help us. We only use 3rd party packages which should be forward-compatible with .NET 8.0.

https://github.com/dotnet/runtime/blob/536f34d9ab88e153aa11329e789afe6975fbe9a9/src/libraries/System.Net.Http/tests/StressTests/HttpStress/HttpStress.csproj#L10-L17

**Comment by antonfirsov** [comment]
Unfortunately, applying the changes from #74157 doesn't seem to fix this in my environment. @dotnet/area-infrastructure-libraries @dotnet/runtime-infrastructure any chance someone can help?

**Comment by ericstj** [comment]
> This is a high-priority issue, since we need to get stress tests running to stabilize QUIC / HTTP3.

Should that be happening in `main` or `release/7.0`?  `main` has moved on from 7.0 and the failures you're seeing seem to be because not all of the product has moved forward.

My first suggestion would be to either 1) retarget the HTTP tests to 8.0 so they get the correct runtimeconfig, or 2) allow them to rollforward and run on a newer 8.0 framework.  I don't think either of those would work since you're trying to do this: 
> use the 7.0.0 Microsoft.AspNetCore.App runtime (currently 7.0.0-rc.2.22424.4) together with the live-built Microsoft.NETCore.App.

**Comment by ericstj** [comment]
@vitek-karas @agocke - do you know of any special environment variables or anything that can let us tell the host to load a specific Microsoft.NETCore.App instead of the one listed in Microsft.ASPNetCore.App's runtimeconfig.json?  Or tell the host to rollforward even though ASP.NET's runtimeconfig says not to?  That might let us skirt by this point-in-time issue where the product is out of sync.

**Comment by vitek-karas** [comment]
I can think of two ways:

Prepate a private .NET install (don't use the global installed runtimes) which has the 8.0 NETCore.App and 7.0 ASP.NET only. Set `DOTNET_ROOT` to point to it, and also set `DOTNET_ROLL_FORWARD=Major`. Then run the test with that install. The env. variable should take precedence over anything in the `.runtimeconfig.json`. (The reason for the private install is that otherwise this would apply to the ASP.NET reference as well, and thus you might end up running with 8.0 ASP.NET if it's on the machine).
This is probably the cleanest solution which doesn't require hacking anything.

*Disclaimer: This is a hack and I won't admit I advised its usage 😉* Make sure that the test/app has the `Microsoft.NETCore.App` framework reference as its first reference in the `.runtimeconfig.json`. Then use `--fx-version` command line to specify the 8.0 version - this should override anything in runtimeconfig. But it only applies to the first framework reference, thus the need for the very specific ordering in the json.

**Comment by antonfirsov** [comment]
> Prepate a private .NET install

Our scripts are already doing it.

> and also set `DOTNET_ROLL_FORWARD=Major`

Looks like this is all I needed to make this work again, thanks a lot @vitek-karas & @ericstj!
