### ISSUE TITLE
standard2.0 Type.IsAssignableFrom not work

### ISSUE THREAD

**Issue by wangrd** [dotnet/runtime#74700]
### Description

`Type.IsAssignableFrom` or `typeA == typeB` always return false even they have the same type with .net standard.

### Reproduction Steps

I have a Interface `ITest` in .net project A of standard2.0, and I implement I with class `Test:ITest` in project B of .net6.
Now I get the type of Test from `AssemblyA` as `typeA`, then compare it with the `ITest`:
```csharp
typeof(ITest).IsAssignableFrom(typeA)  //return false
typeA.IsSubclassOf(typeof(ITest) )  //return false too
```

### Expected behavior

return a expected result.

### Actual behavior

always return false.

**Comment by teo-tsirpanis** [comment]
Hello, can you provide a program that reproduces this behavior?

**Comment by wangrd** [comment]
> Hello, can you provide a program that reproduces this behavior?

[TypeVerify.zip](https://github.com/dotnet/runtime/files/9437961/TypeVerify.zip)

**Comment by wangrd** [comment]
> Hello, can you provide a program that reproduces this behavior?

It maybe because of loading the assembly via `AssemblyLoadContext`, but why ?

**Comment by svick** [comment]
> It maybe because of loading the assembly via `AssemblyLoadContext`, but why ?

That's exactly it. The type `Test` from your `PluginLoadContext` implements the interface `ITest` from the `PluginLoadContext`, which is different from the `ITest` interface in the `Default` context that you're testing against.

If I add the following code at the start of your `PluginLoadContext.Load`, it seems to make the code work:

```c#
if (assemblyName.FullName == typeof(ITest).Assembly.FullName)
    return typeof(ITest).Assembly;
```

But I don't know enough about `AssemblyLoadContext` to tell you whether something like this is the right way to do it.

**Comment by teo-tsirpanis** [comment]
> But I don't know enough about `AssemblyLoadContext` to tell you whether something like this is the right way to do it.

I do, and that's the right way.

**Comment by teo-tsirpanis** [comment]
Also @wangrd, please do not use the `System.Runtime.Loader` package, for the reasons explained in #38503. After removing it, you can either retarget the `TypeHelper` library to .NET 6, or move the `AssemblyLoadContext`-related code in the `Main` project.

**Comment by wangrd** [comment]
> Also @wangrd, please do not use the `System.Runtime.Loader` package, for the reasons explained in #38503. After removing it, you can either retarget the `TypeHelper` library to .NET 6, or move the `AssemblyLoadContext`-related code in the `Main` project.

That's a bad message for me, because i'm trying to write a basic library for my team and aims to  universal as far as possible, and I alse want wo load my assembly like a alone plugin.

**Comment by wangrd** [comment]
> Also @wangrd, please do not use the `System.Runtime.Loader` package, for the reasons explained in #38503. After removing it, you can either retarget the `TypeHelper` library to .NET 6, or move the `AssemblyLoadContext`-related code in the `Main` project.

any way, thanks.

**Comment by vitek-karas** [comment]
> But I don't know enough about AssemblyLoadContext to tell you whether something like this is the right way to do it.

There's a cleaner way - the plugin should not contain assemblies provided by the host - it should only build against them. Take a look at https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#simple-plugin-with-no-dependencies specifically this:
```XML
    <ProjectReference Include="..\PluginBase\PluginBase.csproj">
        <Private>false</Private>
        <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
```

The `Private=false` and `ExcludeAssets=runtime` make it so that the build output of the project doesn't contain the binaries from the project reference (or package reference).

It's also cleaner to use `AssemblyDependencyResolver` as that will solve potential issues with plugins which have platform specific dependencies (Windows versus Linux for example) or plugins which carry localized resources.

Combined the above problem should not happen since the plugin load context won't resolve the assembly provided by the host and thus only one copy of it will be loaded.

That said the above code will work, it's just more fragile.
