### ISSUE TITLE
System.IO Binary Reader ReadChars method  behaves differently on net6

### ISSUE THREAD

**Issue by sandrolivajaenv** [dotnet/runtime#74917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I run this code on net 3.1 I reader.ReadChars(2) will return a empty char array which will then become an emptry string and that is the expected behavior in our project.

But if I run it on .net6 I will get an exception: 'System.ArgumentOutOfRangeException': ' Specified argument was out of the range of valid values' which now changes the behavior of the reader.readchars(2). Is this intended or it's a bug?

````
using System;
using System.IO;

namespace ConsoleApp2
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var stream = new MemoryStream();
            using var reader = new BinaryReader(stream);
            reader.BaseStream.Position = 8;
            var chars = reader.ReadChars(2);
            string test = new string(chars);
            Console.WriteLine(test);
        }
    }
}
````

### Expected Behavior

I expect to get an empty char array from reader.ReadChars.

### Steps To Reproduce

Copy the code I wrote in a Console app for 3.1.
Do the same for net6 Console project.
Compare results.

### Exceptions (if any)

On net 6: System.ArgumentOutOfRangeException

### .NET Version

3.1 and 6.0

**Comment by Clockwork-Muse** [comment]
... I was wondering why all changes in this area were 3 years old, since I thought it was a change 6 -> 7... but no, it's 3.1 -> 6.

Your real problem is: `reader.BaseStream.Position = 8;`
... you're trying to read starting past the end of your data.  Stop doing that.  You won't hit the error if you're at the end of the buffer (because it allows perfect striding), so this implies you have an error in some higher-level partitioning/striding/splitting code.

That said....

The most likely culprit is 616609744aaec2cb8a4a753375beb7fe53a75450, which switched to `Span`.  Because `Span` validates the starting offset, this had the effect of performing that validation before a [later check for the number of valid bytes to read](https://github.com/dotnet/runtime/commit/616609744aaec2cb8a4a753375beb7fe53a75450?diff=split#diff-eda5fa56d36f6567a9adeb289bc9fb375617698d002f6932cf8589700990a5aaL431-L434):
```cs
if (numBytes == 0)
{
    return (buffer.Length - charsRemaining);
}
```

... instead of after, as it was originally.  So the previous behavior would be restored by adding an additional length check before the creation of the `Span`.

(as a side note, we allocate a new zero-length array for the case where we _actually_ read zero bytes, which is maybe an optimization to look at - we already return the default empty array for the case where we _requested_ to read zero bytes)

**Comment by adamsitnik** [comment]
As @Clockwork-Muse has explained, this is by design.
