### ISSUE TITLE
Make System.Transactions.Local trimmable on Windows

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#75031]
https://github.com/dotnet/runtime/pull/72051 added `IsTrimmable=false` to `System.Transactions.Local`, which is an assembly in the shared framework. This means it is referenced for every app. Users don't opt-in and can't opt-out of referencing it in their app.

As https://github.com/dotnet/runtime/issues/74506 points out, this caused a size regression on WASM. Subsequently https://github.com/dotnet/runtime/pull/74828 fixed it to only be `IsTrimmable=false` on non-Windows.

However, Windows is still a problem. Setting `IsTrimmable=false` on any shared framework library is not correct. Instead, we need to be marking the unsafe APIs with `[RequiresUnreferencedCode]` and need to be using [trimmer descriptors](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/ILLink-files.md#illinkdescriptorsxml) as necessary in order to make the library build not trim needed, unreferenced code.

As part of this, we should probably add a rule to our build that says "All shared fx libraries should be 'IsTrimmable=true' on all platforms."

**Comment by jkotas** [comment]
The library was marked as `IsTrimmable=false` due to COM interop. We should not need to mark any APIs with `[RequiresUnreferencedCode]`. We just need to makr the COM interop compatible with trimming.

**Comment by roji** [comment]
@eerhardt @jkotas the distributed transactions part of System.Transactions - which is what does the COM interop - is something we ported mainly in order to unblock .NET Framework users and allow them to move to modern .NET. We don't expect to invest in this component in the future; if a significant need is signaled for cross-platform distributed transactions (#71769), we'll consider implementing new support for that, but that would likely be a separate API, and would most likely not do COM interop in any direct way.

So I'm not sure I see us investing the effort to port the COM interop here to be trimming-compatible (via ComWrappers, if I understand correctly); could you provide the context on why this is important?

System.Transactions does have an unfortunate design whereby distributed transaction code paths - which require the COM interop - aren't clearly distinguishable (e.g. by the linker) from those which aren't. In other words, some users use Sys.Tx only as a way to manage non-distributed transactions in an ambient way (via TransactionScope), and Sys.Tx implicitly escaltes to a distributed transaction needed (i.e. when more than one database is enlisted in the transaction). That does mean that users not needing distributed transactions take the hit of a non-trimmable Sys.Tx (when on Windows only), but whether that's a big problem isn't clear to me.

/cc @ajcvickers @AaronRobinsonMSFT

**Comment by vitek-karas** [comment]
I think it's OK if we decide to not support trimming for Sys.Tx (depends on scenarios and resource availability and so - also if we get ComWrappers source generated it might become a lot easier). In that case we should annotate the APIs which can lead to the COM usage with `RequiresUnreferencedCodeAttribute` (and probably also `RequiresDynamicCodeAttribute`) - so that developers which try to trim an app using Sys.Tx will get a warning.

**Comment by jkotas** [comment]
> depends on scenarios

System.Data.Common references System.Transactions.Local. 

In the current state, I believe that pretty much any database access will generate trim warnings due to System.Transactions.Local reference.

**Comment by roji** [comment]
@jkotas that's true, but is there a reason we can't just leave the assembly with IsTrimmable=false? Wouldn't the entire assembly be trimmed away if the user doesn't use any Sys.Tx (or System.Data) APIs? If so, that sounds like it could be an acceptable state of affairs until we have ComWrappers source generation etc.

**Comment by roji** [comment]
Thanks for the info, I wasn't aware that `IsTrimmable=true` was necessary even for assembly trimming (in partial mode).

I'm not sure what our options here are... I think it's probably too late to switch to ComWrappers for 7.0. If this can be somehow handled by marking the assembly `IsTrimmable=false` during the libraries build but `IsTrimmable=true` for shipping, as you suggest, maybe that's the way to go. Otherwise, having Sys.Tx not be trimmed when on Windows in partial trimming mode may be acceptable for 7.0, I don't know.
