### ISSUE TITLE
NullabilityInfoContext reports `Unknown` instead of `NotNull` for `ClassRestrictedGeneric<>`

### ISSUE THREAD

**Issue by maurei** [dotnet/runtime#75126]
### Description

I'm following up on the overview in https://github.com/dotnet/runtime/issues/63660#issuecomment-1010934151.

The case `ClassRestrictedGeneric<>.K` is currently not behaving as outlined in this overview. It equals `Unknown`, but should be `NotNull`.

Tangent to this: it is unclear to me why `NullClassRestrictedGeneric<>.M` should equal `Unknown`. Why is it not `Nullable`?

### Reproduction Steps

```c#
using System.Reflection;

var propK = typeof(ClassRestrictedGeneric<Class1>).GetMember("K").First();
var stateK = new NullabilityInfoContext().Create((PropertyInfo)propK).ReadState; // Equals `Unknown`, should be `NotNull`.

public class ClassRestrictedGeneric<T> where T :  Class1  { public T K { get; set; } }
public class Class1 {  }
```

### Expected behavior

Expected result is `NotNull` as per the overview above.

### Actual behavior

Actual result is `Unknown`.

### Regression?

No.

### Known Workarounds

Adding a `notnull` constraint works around the problem:

```c#
using System.Reflection;

var propU = typeof(ClassRestrictedGenericWithNotNull<Class1>).GetMember("U").First();
var stateU = new NullabilityInfoContext().Create((PropertyInfo)propU).ReadState; //  Equals `NotNull`, as desired.

public class ClassRestrictedGenericWithNotNull<T> where T : notnull,  Class1  { public T U { get; set; } }
public class Class1 {  }
```

ReSharper code analysis indicates `notnull` as redundant. [I thought it was an analyzer bug at first](https://youtrack.jetbrains.com/issue/RSRP-489137/False-positive-on-RedundantNotNullConstraint), but I now think it is correct.

### Configuration

Microsoft.NETCore.App 7.0.0-preview.7.22375.6

**Comment by buyaa-n** [comment]
> I'm following up on the overview in https://github.com/dotnet/runtime/issues/63660#issuecomment-1010934151.

If you continue reading the comments from that thread, there were [question same as yours and we discussed ](https://github.com/dotnet/runtime/issues/63660#issuecomment-1014197473). Overall, it was compiler that injecting wrong `NullableAttribute` to the type constraint, later [it seems we could not repro the issue ](https://github.com/dotnet/runtime/issues/63660#issuecomment-1048466911) and closed https://github.com/dotnet/runtime/issues/63660. If you are seeing this most likely it is caused by your compiler, upgrading it might fix your issue

> @buyaa-n PTAL and determine if we should fix this in 8.0. Thanks

No, I don't think it is reflection bug, need to verify again
