### ISSUE TITLE
Chain.build() fails for custom certs in certain environments

### ISSUE THREAD

**Issue by maxcoh3n** [dotnet/runtime#75170]
My company is using custom certs to verify our internal servers, and after upgrading to gRPC dotnet, we tried to implement this ServerCertificateCustomValidation Callback:
https://stackoverflow.com/questions/64905704/using-custom-root-ca-with-httpclient

While this works locally, it breaks when running from a gitlab pipeline.
The automatically created X509Chain.ChainStatus object that is created from the server public key gets StatusInformation = `unable to get local issuer certificate`

**Comment by vcsjones** [comment]
> The automatically created X509Chain.ChainStatus object that is created from the server public key gets StatusInformation = unable to get local issuer certificate


It sounds like you have an incomplete certificate chain that sometimes works because AIA fetching is performed, and other times it does not work because AIA fetching fails, or perhaps your local environment has the intermediate certificate in the system cache.

If you have intermediate certificates, you can specify them on the [`ExtraStore`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.extrastore?view=net-6.0) property.
