### ISSUE TITLE
System.Half ToString() bug 

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#75204]
### System.Half ToString() produces incorrect numbers.

Example: Half.MaxValue shows 65500, Half.MinValue -65500
but should be 65504 and -65504.
Binary, the values are correct as I have checked:

![image](https://user-images.githubusercontent.com/63112403/188938770-2684d5e8-f412-4b1a-8a56-b39ec95faab8.png)

### Reproduction Steps

```csharp
      var s1 = Half.MaxValue.ToString(); // 65500
      var s2 = ((double)Half.MaxValue).ToString(); // 65504
```

### Expected behavior

```csharp
      var s1 = Half.MaxValue.ToString(); // 65504
```

### Actual behavior

```csharp
      var s1 = Half.MaxValue.ToString(); // 65500
```

### Configuration

7.0.0-rc.1.22422.12

**Comment by deeprobin** [comment]
Can reproduce.

@teo-tsirpanis Can you assign the right labels (`bug` and `area-System.Numerics`, I think)?

**Comment by tannergooding** [comment]
This isn't a bug, we return the "shortest roundtrippable string". Due to the underlying algorithm, it preferences `65500` over `65504`, as both round to `65504`.

You'd need to explicitly ask for `G5` to see the longer version (the string that guarantees roundtripping without being the shortest possible) and `G19` to see the most precise string.

**Comment by tannergooding** [comment]
Just to clarify, it's preferenced because `6.55e4` is shorter than `6.5504e4` (because `6.55` is 3 digits, where-as `6.5504` is 5 digits).

The algorithm doesn't take into account things like the length of `e##` or that we only use the `e` format for more than 6 or so digits. We just determine that `6.55` is the shortest sequence of significant digits (plus trailing zeros) that rounds to the infinitely precise value represented.

**Comment by c-ohle** [comment]
@tannergooding hi, there is a better and more simple algorithm that produces precise rounded string results. Not only for Half, not only for border cases. Check it out, you know where you can find it.

**Comment by tannergooding** [comment]
This is not a question about precision.

The current behavior is to return the shortest roundtrippable string and that is exactly what the algorithm is doing. This is the same behavior done by many different programming languages/runtimes and is done using one of the faster algorithms available. Changing this is undesirable and is not something we're interested in doing.

We have a different algorithm that will correctly and quickly compute a specific number of digits, which you can achieve using `G5` for Half, as indicated above. `G9` works for `Single` and `G17` for `double`.

**Comment by c-ohle** [comment]
@tannergooding I know these things and I understand the situation. Cannot simply changed as users expect same results as previous versions. Are you aware that midpoint rounding is also wrong? for float and double too. 
I followed many discussions over the years about this. What I do is to implement both, that the user can switch. Not ready yet since I completely rework the templates approach. All more compact and efficient now. It works great together with your INumber system.

**Comment by tannergooding** [comment]
> Are you aware that midpoint rounding is also wrong? for float and double too.

Can you share an example? If this is `Math.Round()` I've already stated on the other issues that there is a longstanding known issue that's been around since .NET Framework.

**Comment by c-ohle** [comment]
@tannergooding in short and with my words: 

When I look to the Math.Round [implementation](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Math.cs,1331) it is a pure floating-point evaluation. 
But this ops round already, especially the division using internal a bit-logic over the last extended bit(s) of the mantissa and a even-rule for error-diffusion. 
This leads to the seemingly undetermined rounding mode behavior.
Solution: a integer division of the mantissas, with divisor shiftet left by the max mantissa bit count + 1. The first two result bits in combi with the desired rounding mode can be used as a right round up/down criteria.

Of course there are many ways to implement this. I would try several to find the best compromise.

**Comment by c-ohle** [comment]
@tannergooding To make it more clear and this belongs to some (old) sensitive floating-point math functions and the not very precise string builder functions:

The (hardware) implementation of the base ops: +,-,*,/ includes already a rounding. This is hardware dependent, different IEEE specs etc.. 
The rounding happens internal at normalization what is a shift op. (to adjust the higest bit) In this moment processor specific extended bit information is used to round up or down, where  round up is a also processor specific a full or partial increment of the mantissa.

But:
This rounding is not for precision - it is for error-diffusion.
A sequence of math operations would tend to go in one direction, to zero or away from zero. To reduce this error it rounds once up, once down based on 'random' bit test. This method, to keep the error small in calculations is already introduced by Carl Friedrich Gauß. Meanwhile with much science several non-perfect versions are in use.

And this is the reason the rounding-issues for the border cases, the confusion by the users that it works sometimes, sometimes not. And the solution is simple as metioned.

**Comment by tannergooding** [comment]
What you're stating is not clear to me and trying to give a concrete example of where `Math.Round(T value)`, `Math.Round(T value,  MidpointRounding mode), `T.ToString`, or `T.Parse` produces an error is likely necessary.

IEEE 754 floating-point has many considerations that users may need to take into account when building more complex algorithms. However, within the confines of what IEEE 754 requires we are believed to be compliant for the above functions.

`Math.Round(T value, int digits)` and `Math.Round(T value, int digits, MidpointRounding mode)` have known issues, as stated. Fixing this to be correct/compliant is non-trivial both due to the behavior break and therefore back-compat risk, but also because it requires mapping `base-10` rounding onto a `base-2` represented value, which can be expensive and negatively impact performance.

**Comment by c-ohle** [comment]
@tannergooding You need to understand what is happening at processor level. Then it is easy to re-evaluate the several math functions based on pure (hardware) floating-point arithmetic.
More then this, then it is also easy to construct the cases with wrong results.

Please let me know at which point my stating is not clear.

**Comment by c-ohle** [comment]
@tannergooding 

> Fixing this to be correct/compliant is non-trivial 

It is trivial and not time critical. Only some lines and a integer division. The division can be a partial divison since only low bits needed. Not time critical since a bit mask test could be used to detect the critical cases.

**Comment by tannergooding** [comment]
> You need to understand what is happening at processor level.

I promise I'm intimately familiar with how floating-point processing works. Other team members are likewise familiar to varying degrees.

> More then this, then it is also easy to construct the cases with wrong results.

Than please do so.  As stated multiple times above, we are not aware of any issues with several of the above functions. The two `Round` cases that do have known issues are non-trivial to fix for multiple reasons given above, not because coming up with a correct implementation is necessarily difficult.

**Comment by c-ohle** [comment]
@tannergooding 

> I promise I'm intimately familiar with how floating-point processing works.

> What you're stating is not clear to me

Please let me know at which point my stating is not clear.
I suspect there is a misunderstanding.

**Comment by tannergooding** [comment]
You're stating there are issues here and that it is trivial to produce them. You have not provided any concrete examples or explicitly stated which specific methods you believe to have issues.

You are likewise making statements that fixing these, while maintaining perf, is likewise trivial to do. This is done without example, proof, or references to existing papers that go over this in detail.

I am simply requesting you provide concrete evidence and statements. This is not a forum where "exercise left to the reader" is desired. We want and prefer concrete details and reproduction steps.

**Comment by tannergooding** [comment]
> But my question was at which point my stating is not clear?

All of it. More specifically:
* You've made claims that there are issues, but not which APIs have issues.
* You've made claims that it is trivial to produce these issues, but not given any example of a function you'd call that has unexpected output as compared to the value you would it expect it to return
* You've made claims that fixing these, while maintaining perf, is likewise trivial; but not shown any example of how this would be done and why the approach is correct (such that it doesn't introduce new bugs/edge cases)

We would very much appreciate concrete examples, preferably code that we can reproduce locally. Such code should likely be "trivial" as indicated. I would personally define trivial as something that is under 30 lines of code that I could reproduce in a new Console Application. Likewise exact clarification on what APIs are the problem as I've listed several functions which are believed to be correct and two functions which are known to have issues, but have still yet to get clarification on what APIs you believe are problematic.

**Comment by c-ohle** [comment]
@tannergooding

> You've made claims that there are issues, but not which APIs have issues.

Since you asked and mentioned: "that there is a longstanding known issue that's been around since .NET Framework."
It's all about the Round() functions:   
-  for double in Math `public static unsafe double Round(double value, int digits, MidpointRounding mode);`   
- for float in MathF  `public static unsafe float Round(double float, int digits, MidpointRounding mode);`   
And the Round() function versions that use these as well.

And since you asked, I've tried to explain why there are sometimes wrong results, different results on different processor architectures and platforms. Wrong regarding Midpointrounding for border cases - for other cases not wrong but less precise then necessary.

For the string formatting functions it has the same reason and result. 
Not wrong but less precise in general and different string representations on different platforms what could be avoid.

> You've made claims that it is trivial to produce these issues

It is easy to reproduce but for every case I would present you can argu like for Half.MaxValue.ToString(). 
That 65500 is equivalent to 65504.
Confusing for the user, spec. said is 65504, binary its 65504, every cast 65504, only ToString() shows 65500.

> You've made claims that fixing these, while maintaining perf, is likewise trivial

As I already tryed to explain: insted of the floating point division:
"a integer division of the mantissas, with divisor shiftet left by the max mantissa bit count + 1. The first two result bits in combi with the desired rounding mode can be used as a correct round up/down criteria."
This is actually identical what all processors does but without rounding for error-diffusion.

Pseudo code for float:
```csharp
   // like a fixed point division but with one bit more (extended part)  
   var a = (dividend_mantissa << 25) / divisor_mantissa;   
  
   var case = (a >> 24) & 3; //shift the bits down we are  interested 
   
   // now  we can combine the desired rounding mode with the case
   switch(case) { case 0: break; case 1: break; case 2: break; case 3: break; }

  // several possebilities from here
```
A working implementation is [here.](https://github.com/c-ohle/RationalNumerics/blob/ff0cce7a8b423ecbbc4b369178c96c92500abb41/System.Numerics.Rational/BigRational.cs#L2169) 
Difficult to read but easy to debug.

**Comment by tannergooding** [comment]
> It's all about the Round() functions:

So no new issues, only issues that have been stated to already be known and which are problematic to fix for many reasons.

> For the string formatting functions it has the same reason and result.
Not wrong but less precise in general and different string representations on different platforms what could be avoid.

This has already been covered as "by design". We return the shortest roundtrippable string. `6.55e4` is shorter than `6.5504e4` and both round to the same underyling binary value. We then use the "F" format for numbers with less than 6 significant digits, so this expands to `65500`. This is the shortest string because we only include 3 significant digits and then the rest of the data is trailing zeros. This is not going to change and is deterministic on all platforms/architectures currently supported by .NET.

> This is actually identical what all processors does but without rounding for error-diffusion.

This is not going to have the desired handling and won't be identical to `double.Parse(double.ToString("G#"))` (with the specified rounding mode differing from the current hardcoded `ToEven`).

When rounding any given number, we have to take the exact value represented. For `Math.PI`, this is `3.141592653589793115997963468544185161590576171875`.

We then have to find the first `digits` significant digits, so if the user specified `10`, we'd need to find `3.1415926535`.  Depending on the rounding mode, we may then need to consider remaining digits beyond `n`. The trailing here is `0.000000000089793115997963468544185161590576171875`. If the trailing value is exactly `0.5` we need to consider midpoints, otherwise we need to round up/down. In this case, its above the midpoint so we'd typically round up (except for `Truncate`) and so the rounded value would be `3.1415926536`, which can be represented as a double as `3.1415926536000000623971573077142238616943359375`.

Simply dividing the two mantissas here, even with an adjustment, won't correctly account for the base-10 vs base-2 representations.

Take `Math.PI` which is represented as `0x4009_21FB_5444_2D18` and `1e10` which is represented as `0x4202_A05F_2000_0000`. Extracting the mantissas and adding the leading implicit 1 gives `0x19_21FB_5444_2D18` and `0x12_A05F_2000_0000`. If you right shift the dividend by 53 you get `0xA300_0000_0000_0000`, dividing these then gives `0x8C0` where right shifting will give 0.

Scaling up by `10` in the first place is where the rounding issues first become present because certain inputs will end up having a loss of data. Consider `1.15` which is actually represented by `1.149999999999999911182158029987476766109466552734375` and therefore rounding to 1 digit scales up to `11.5`, thereby seemingly becoming a midpoint and losing the fact that this is under the midpoint and should therefore round down.

This simply does not provide correct IEEE 754 compliant rounding as required and will continue producing incorrect results.

**Comment by c-ohle** [comment]
@tannergooding 

> So no new issues, only issues that have been stated to already be known and which are problematic to fix for many reasons.

But this is what I want to say and nothing else. It is possible to fix, with less code and without performance impact.
Only some lines are necessary and must not called always - the problem cases can detected by simple bitmask tests.
The same approach can be helpfule to improve the precision for many functions, string formatting as example - but it must not used.
This was alredy tested for the earlier Float<T> versions. Tested to float and double with millions of random numbers 
and there was no difference, except for the problem cases where midmap rounding fails for float and double.

> We return the shortest roundtrippable string

This is nice and new to me, I didn't realize this NET7 change. It's currently not updated in the online documentation.
Will urgently update my code for this and test it. Maybe the known problems up to NET6 are solved now.
This however was not the case by tests with explict "G17" less precise for random numbers an differencences already between X86 and X64. (SIMD of course)

> This is not going to have the desired handling and won't be identical to double.Parse(double.ToString("G#"))

Parse was never a problem. Dont know where Round, especially with MidMapRounding is needed. 
If you mean ToString("G#"), how can this be a problem? The optimized version selects only the more precise digits version.
For example: selects 65504 for Half MaxValue and not 65500.

> When rounding any given number, we have to take the exact value represented.

That looks to me like you mean really Parse. But there is no problem.
I checked again the latest code: NumberBuffer and NumberToSingleFloatingPointBits dont need round as espected.

> Take Math.PI which is represented as 0x4009_21FB_5444_2D18 and 0x4202_A05F_2000_0000

Sorry, I had a Typo (shift dividend -> divisor), edited this already earlier. 
Another change was that for the simple up down test only one bit is needed.
Then for your case it looks like:

```csharp
   var up = ((((0x19_21FB_5444_2D18 << 53) / 0x12_A05F_2000_0000) >>52) & 1) != 0;
   if(up) {  } else { } //down    
```
But it's a draft, more easy to test with float at first since ulong can be used as int and no long shift- and div is necessary.
And as I said, many versions are possible, most easy but not most efficient, to continue with double.

**Comment by Joe4evr** [comment]
> > We return the shortest roundtrippable string
> 
> This is nice and new to me, I didn't realize this NET7 change.

This is not something that changed with .NET 7, [it changed in .NET Core 3.0](https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/#making-the-formatter-ieee-754-2008-compliant).

**Comment by c-ohle** [comment]
@Joe4evr Thanks for the info, very helpful, then it's probably mature and I don't need to expect further changes for my implementation for arbitrary number types that should be 100% compatible. But I will leave it switchable.

**Comment by c-ohle** [comment]
@Joe4evr One question. Maybe you are familiar with the algorithm. I recognized that the more precise rounding version not automatically need more digits what is logic since the other version is the more precise representation for another input value close to this. Is this in the for me new algorithm already taken into account?
