### ISSUE TITLE
JIT: check/release diff in arm SPMI libraries_tests.pmi

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#75221]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=4324&view=results

```
Invoking: C:\h\w\ACDB0909\p\superpmi.exe -a -v ewmi -f C:\h\w\ACDB0909\t\tmpf8lq3vty\libraries_tests.pmi.Linux.arm.checked.mch_fail.mcl -diffMCList C:\h\w\ACDB0909\t\tmpf8lq3vty\libraries_tests.pmi.Linux.arm.checked.mch_diff.mcl -r C:\h\w\ACDB0909\t\tmpf8lq3vty\repro -baseMetricsSummary C:\h\w\ACDB0909\t\tmpf8lq3vty\libraries_tests.pmi.Linux.arm.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\ACDB0909\t\tmpf8lq3vty\libraries_tests.pmi.Linux.arm.checked.mch_diff_metrics.csv -target arm -p -failureLimit 100 C:\h\w\ACDB0909\p\base\clrjit_universal_arm_x86.dll C:\h\w\ACDB0909\p\diff\clrjit_universal_arm_x86.dll C:\h\w\ACDB0909\p\artifacts\spmi\mch\1b9551b8-21f4-4233-9c90-f3eabd6a322b.Linux.arm\libraries_tests.pmi.Linux.arm.checked.mch

...

[10:55:41] ISSUE: <ASM_DIFF> main method 284216 of size 213 differs
```

**Comment by AndyAyersMS** [comment]
This was introduced sometime after Aug 28 (48a3dbe5509f53f89db0a48c8285a2eec0758fea).

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I can reproduce the asmdiff even with 48a3dbe so seems like this was uncovered by a new collection.

**Comment by jakobbotsch** [comment]
Looks like a case where we end up with some odd behavior around non-canonicalized NaNs, maybe due to MSVC optimizations. The test is this one:
https://github.com/dotnet/runtime/blob/2ed931d06a662eb416e363f2dde798729eae4c25/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs#L852
It was added in #74517, so the timing lines up with this being a new collection.

In checked we have the following codegen:
```scala
Generating: N053 (  5, 10) [004648] ------------                t4648 =    CNS_DBL   double -nan REG f8 $c4
IN0012:             mov     r0, -1
IN0013:             mov     r1, -1
IN0014:             vmov.i2d d8, r0, r1

Generating: N069 (  5, 10) [004654] ------------                t4654 =    CNS_DBL   double nan REG f8 $c5
IN0016:             mov     r0, -1
IN0017:             mvn     r1, 0x80000000
IN0018:             vmov.i2d d8, r0, r1
```

Ultimately, it leads to the following checked/release diff:
```diff
             mov     r0, -1
-            mov     r1, -1
+            mvn     r1, 0x80000
             vmov.i2d d8, r0, r1
             vstr    d8, [r4+0x18]
             mov     r0, -1
-            mvn     r1, 0x80000000
+            movw    r1, 0xffff
+            movt    r1, 0x7ff7
             vmov.i2d d8, r0, r1
```

As a side node, I hit an assert in debug JIT builds that I do not hit in checked JIT builds on the same method context, so there is something interesting going on.

**Comment by jakobbotsch** [comment]
The debug/checked difference seems to be because the x87 FPU will turn signaling NaNs into quiet NaNs on `fld`. This means that all functions in the code base that return floating point values may silently do this in x86 builds when they aren't inlined, due to the ABI returning floats on the x87 stack.

The particular case that hits assert is this one:
https://github.com/dotnet/runtime/blob/3776c9fe1f4bef96eb9dc7a6e5cdc164353dc620/src/coreclr/jit/valuenum.h#L1017-L1041

In debug builds `SafeGetConstantValue<double>` is not inlined and it normalizes the NaN, so we get the mismatch. In checked builds it is inlined and does not normalize the NaN.

I suspect a similar situation is the cause of the checked/release diff, potentially due to LTCG that may change ABI of these functions to return in SSE registers instead of on x87 stack. I haven't found the exact location yet however.

I'm not really sure how we can fix this without having to find and mark all float functions that deal with JIT IR literals as `__vectorcall` on x86 builds, or using some custom types. Not sure if making `__vectorcall` the default is feasible. Any ideas @tannergooding @jkotas?

**Comment by tannergooding** [comment]
The IEEE 754 spec allows `NaN` normalization and specifies users should not rely on the payload or sign bits of NaN in most cases.

Most platforms will at most quiet a signaling NaN and preserve sign/payload otherwise, which is what SSE and the x87 FPU do. They do this to minimize the number of hardware exceptions thrown, in that once a sNaN "raises" its exception, it is then quieted to prevent each later interaction from also raising the signal. We of course disable IEEE 754 exceptions so nothing is ever actually raised.

The main difference between x87 and SSE is that `fld` also handles `sNaN` where-as `movaps`, `movups`, `movss`, and others typically do not (they just copy bits). Operations like `addps`/`addss` and friends do however still "handle" the `sNaN`.

**Comment by tannergooding** [comment]
We don't have very good handling of `NaNs` in the JIT today in general and pessimize several scenarios when we encounter them. I expect this is just another where we likely should be slightly more lenient to account for what the hardware allows and does.

**Comment by JulieLeeMSFT** [comment]
Setting this to Future.

**Comment by jakobbotsch** [comment]
> I expect this is just another where we likely should be slightly more lenient to account for what the hardware allows and does (while still remaining IEEE 754 compliant and matching typical user expectations for .NET code).

When you say lenient, what do you mean? If normalization is permitted then the best solution seems to be to normalize NaN literals in the JIT IR.
