### ISSUE TITLE
Crash with unmanged DLL did not create a StackTrace in Eventlog

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#75245]
### Description

We have an error, were we access Pointers from an unmanged DLL wich we freeed before.
If we do this in a Net4.8 Application in Debug Mode, we get a Stacktrace in the Eventlog.

If we du this in a Net6 Application in Debug Mode we get only this:

        Application: MCC.Common.Services.NTServiceHost.exe
        CoreCLR Version: 6.0.822.36306
        .NET Version: 6.0.8
        Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE9F791FDD (00007FFE9F5C0000) with exit code c0000005.

If we create a MiniDump we could see the Stacktrace in the Dump

### Reproduction Steps

Crash a Net6 Application in unmanged COde

### Expected behavior

We should see a Stacktrace in Eventlog

### Actual behavior

No Stacktrace

### Other information

see https://github.com/dotnet/runtime/issues/67897

**Comment by hoyosjs** [comment]
@noahfalk @janvorli @jkotas Do we always do EventLog reporting in core and do we do so for unmanaged resources? I don't know if our SEH logic tries to do anything for such cases or if that's a Windows capability

**Comment by jogibear9988** [comment]
I get an Eventlog Entry, but without any Stacktrace

**Comment by hoyosjs** [comment]
Is your app deployed as a self contained publish?

**Comment by jogibear9988** [comment]
no. I'll try if I could recreate a sample app

**Comment by hoyosjs** [comment]
How are you running the app?

**Comment by noahfalk** [comment]
This is probably relevant code for whether we get a callstack in the error report: https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/eepolicy.cpp#L458-L464

I don't recall that we made an intentional change to change the error report text, but it is certainly possible that it is a byproduct of other changes .NET Core made to have a simpler and more consistent cross-platform exception handling story. .NET Framework has a complex mechanism that can marshal exceptions across native<->managed interop boundaries whereas .NET Core treats exceptions crossing the boundary as fatal. If the stacktrace on .NET Framework was created by allowing a managed exception to unwind through native code .NET Core probably isn't going to replicate that behavior.

@jogibear9988 - are you able to show us the error log message produced by .NET Framework and what stacktrace you see in the minidump on .NET Core?

**Comment by jogibear9988** [comment]
in minidump I get the stacktrace. 
I will post the messages from eventlog when I've created the sample.

![image](https://user-images.githubusercontent.com/364896/189233323-4e6be5db-6025-484e-bbc8-0b0b0136edf0.png)

The Stacktrace is in manged code. And this one I also get in fullframework in the eventlog

**Comment by jogibear9988** [comment]
If I debug the minidump mixed, I get this:
![image](https://user-images.githubusercontent.com/364896/189233860-05fe7792-badc-4b40-ab99-e5df65358f72.png)

But I only need the managed stacktrace, wich was in the eventlog in fullFramework

**Comment by tommcdon** [comment]
@jogibear9988 just a friendly reminder to share the event log output once you have it available.

**Comment by jogibear9988** [comment]
So I now created a Sample app to reproduce the error.

Net4.8 Eventlog:
![image](https://user-images.githubusercontent.com/364896/190005085-daf1007d-ca64-41bd-ba79-1d54385a2930.png)
![image](https://user-images.githubusercontent.com/364896/190005141-1d5ef446-3a0c-4b38-af9b-072460281585.png)

**Comment by jogibear9988** [comment]
In Net4.8 you see this:

Ausnahmeinformationen: System.AccessViolationException
   bei Accon.AGLink.AGL4_Class.AGL64.AGL_Symbolic_GetChildCount(IntPtr, Int32 ByRef)
   bei Program.Main()

**Comment by jogibear9988** [comment]
In Net6 only a internal error

**Comment by noahfalk** [comment]
Thanks for the info @jogibear9988!

@AaronRobinsonMSFT @janvorli - Just wanted to double check my understanding around runtime behavior is accurate:
1. In .NET Framework if managed code p/invokes to a native method that triggers a native access violation (SEH exception) then the runtime converts that to a System.AccessViolationException managed exception object when 1st pass exception dispatch reaches the pinvoke frame and the runtime allows 1st pass dispatch to continue. Assuming we don't find a catch handler in the remainder of exception dispatch we report it as an unhandled exception to the EventLog and terminate the process.
2. In .NET Core in the same situation we do not convert the exception to a System.AccessViolationException, nor do we allow the 1st pass unwind to continue. Instead we log a fatal error to the Event Log immediately and terminate the process.
3. The decision not to map SEH exceptions to managed exception objects and to no longer allow exception dispatch to continue was an intentional design change

Does that all sound correct? I'm not encouraging a change to our exception marhsalling/dispatch behavior (assuming we did it deliberately) but it does seem like having a stack trace included with the fatal error report in the event log would be useful feature addition.

**Comment by jkotas** [comment]
Yes, that's correct. Process state corrupting exceptions are intentionally converted to FailFast in .NET Core very early. We do not allow them to be handled.

> it does seem like having a stack trace included with the fatal error report in the event log would be useful feature addition.

Agree.

**Comment by jogibear9988** [comment]
I've had some errors as how we used the unmanged Library. I was always able to find them in my Code when I got the Stacktrace from the Eventlog in Net4.x
In Net6, I only got a Cryptic Message wich did not help. As the crashes never occurend on my side, I needed to enable MiniDumps on our customers computers, needed a way to get to the dumps and so on.

So it would be a huge help to get the Stacktrace

**Comment by janvorli** [comment]
This seems to be eventing problem. The console output still contains the stack trace in .NET 6. When running the repro app from the command line, I get this:
```
dotnet F:\issues\75245\TestCrashNet\TestCrashNet\bin\Debug\net6.0\TestCrashNet.dll
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Accon.AGLink.AGL4_Class.AGL64.AGL_Symbolic_GetChildCount(IntPtr, Int32 ByRef)
--------------------------------
   at Accon.AGLink.AGL4_Class.AGL64.IAGL_Symbolic_GetChildCount(IntPtr, Int32 ByRef)
   at Accon.AGLink.AGL4.Symbolic_GetChildCount(IntPtr, Int32 ByRef)
   at Program.Main()
```

**Comment by janvorli** [comment]
In other words - we generate the stack trace, but it is not directed to the event log for some reason.

**Comment by jogibear9988** [comment]
and my real app is a windows service 😊

**Comment by janvorli** [comment]
While investigating this issue, I have just found that .NET 7 has broken the error event, it no longer contains the address and error code. See #75600

**Comment by janvorli** [comment]
The stack trace reporting code is still in `EEPolicy::LogFatalError`, but it is invoked only for failures with COR_E_FAILFAST or COR_E_CODECONTRACTFAILED. 
Interestingly, the .NET 4.8 code has the same implementation, so I don't know yet how the call stack ends up being reported.

However, I have found that if we lifted the limitation and reported the call stack on access violation too, the managed stack trace printing works fine. So we could consider enabling it.

**Comment by noahfalk** [comment]
> Interestingly, the .NET 4.8 code has the same implementation, so I don't know yet how the call stack ends up being reported

My initial guess is that the stack trace reported by .NET Framework is coming from reading the StackTrace property of the unhandled managed exception object and not from doing an explicit stackwalk solely for error reporting purposes.

> we generate the stack trace, but it is not directed to the event log for some reason

Hopefully it at least means we won't need a large change to get it working in the error log too :)

**Comment by jogibear9988** [comment]
so maybe for 7.0?

**Comment by noahfalk** [comment]
> so maybe for 7.0?

Sorry to be the bearer of bad news but getting this change in 7.0 RTM release is unlikely. We've already entered the RC phase of the release process for 7.0 and only limited critical fixes are taken at this point.

**Comment by noahfalk** [comment]
Yeah that does look pretty simple 👍. I'm happy to support us doing it if Tactics thinks it meets the bar. 

There is probably a broader version of this same issue where the native code triggers some other SEH exception that isn't an access violation, but if you are aiming for 7.0 narrow seems better than broad. Thanks @janvorli!

**Comment by janvorli** [comment]
Fixed by #75721

**Comment by danmoseley** [comment]
Is COR_E_CODECONTRACTFAILED even still possible in .NET Core?

**Comment by jkotas** [comment]
Nothing prevents people from using `ContractException` that will produce `COR_E_CODECONTRACTFAILED`.
