### ISSUE TITLE
Run ServiceController.Start(serviceName) throw exception  access is denied

### ISSUE THREAD

**Issue by danies8** [dotnet/runtime#75554]
### Description

Run ServiceController.Start(serviceName) throw exception  access is denied

### Steps to Reproduce

1.Create maui app.
2.Create worker service.
3.Run this code from maui in VS as admin or MSIX
  ServiceController service = new ServiceController(servicName);
   service.Start();
    service.WaitForStatus(ServiceControllerStatus.Running);
4.Exception:
2022-09-13 10:57:12,636 [1] ERROR AutomationClient.Shared.Helpers.ServiceHelper - StartService
System.InvalidOperationException: Cannot open 'GS Automation Client Worker Service' service on computer '.'.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at AutomationClient.Shared.Helpers.ServiceHelper.StartService(String servicName)

### Link to public reproduction project repository

...

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window 10 

### Did you find any workaround?

No

### Relevant log output

```shell
2022-09-13 10:57:12,636 [1] ERROR AutomationClient.Shared.Helpers.ServiceHelper - StartService
System.InvalidOperationException: Cannot open 'GS Automation Client Worker Service' service on computer '.'.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at AutomationClient.Shared.Helpers.ServiceHelper.StartService(String servicName)
```

**Comment by danmoseley** [comment]
Also what happens if you do "sc start <your service name>"? I would expect that to be doing essentially the same calls

**Comment by danies8** [comment]
@danmoseley  "sc start yourservicename" will start the service after installation of the service.

**Comment by danies8** [comment]
@ViktorHofer
[TestService.zip](https://github.com/dotnet/runtime/files/9775168/TestService.zip)
 both in MAUI and console is not working.

**Comment by danmoseley** [comment]
What if you change the code at the place you do service.Start() right now, and instead of that run `sc start yourservicename` using Process.Start() ? If that succeeds, it means that service.Start() is apparently running with the necessary privileges.

**Comment by danies8** [comment]
> Instring fileName = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + @"\runService.bat"; Process proc = new Process(); ProcessStartInfo info = new ProcessStartInfo(fileName, string.Empty); info.WindowStyle = ProcessWindowStyle.Hidden; info.UseShellExecute = true; info.Verb = "runas"; proc.StartInfo = info; proc.Start(); mean time I used powershell.
> 
> @echo OFF
> 
> echo start GS Automation Worker Service echo --------------------------------------------------- sc.exe start "GS Automation Client Worker Service" pause echo Done
Did y mean that code ? It working.

**Comment by ericstj** [comment]
I took a look at the repro -- first thing - this application is not a windows service.  On start you'll see:
> The service did not respond to the start or control request in a timely fashion

First problem was due to your script:
> sc.exe create "Test Service" binpath="%~dp0\Debug\net6.0\WorkerService3.exe startup="delayed-auto"

Missing a trailing quote after `WorkerService3.exe`, also the parameter is `start` not `startup`.  I modified this to:
> sc.exe create "Test Service" binpath="%~dp0\Debug\net6.0\WorkerService3.exe" start=delayed-auto

Next it never starts successfully when run manually.  This is because it never tells SCM it started.  To fix that make sure you call `UseWindowsService()` in your service app.  I made this change and the service would start successfully on the commandline.
> sc start "Test Service"

I tried your console app and it didn't start the service.  This was because they were using "WorkerService3" as the service name.  I changed these to use "Test Service" to match your script and they worked for me.

For your Maui project - I modified it to build as self-contained.  Then I was able to run it and it successfully started your service (after the changes I mention above).

Note that ran these from an elevated command-prompt. 

So my best guess is one of these fixed the problem, or the way I'm running the app made it work.  I wouldn't be surprised if msix|appx installs might not have permission to start services -- you might need some sort of app capability declaration.

Since this is no-repro I'm going to close this out.  I hope my suggestions here might help shed some light on what might be going wrong.
