### ISSUE TITLE
QUIC and HTTP/3 tests should log which exact version of msquic they use

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75596]
At least to the console -- that will allow us to better check in CI if the right version of msquic is installed (even in future).

**Comment by CarnaViire** [comment]
Tiny note which might be obvious: manually built msquic (from main) will have the same version as the next release will have. So you wouldn't be able to track a switch from manual main to official release package.

Why it might be important: if a release was made to include important changes X, and it has version A.B, making sure that our code uses version A.B is not really enough, because it could be a manual build from main prior to introducing changes X. (this actually happened here https://github.com/dotnet/runtime/pull/73563#issuecomment-1209437833)

**Comment by karelz** [comment]
Good point. Perhaps we could log more -- incl. date of built msquic.dll, or some other details from it?

**Comment by wfurt** [comment]
I think when we build msquic our selves or consume mainline, we know what we are up to. I still feel there is value in collecting some basic info.
Perhaps even storing msquic version in static variable so it would be visible in core dumps.
