### ISSUE TITLE
[wasm] app startup regression

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#75598]
There is a regression visible in our measurements of `AppStart, Reach managed` on 07/11/22. It impacts the interpreter builds most, worst is the `interp.default.chrome`, which goes from 438ms to 960ms. aot builds are slower too.

By adding more measurements in that area, we can now pin-point the regression to https://github.com/dotnet/runtime/commit/4a2ebf204801dc099d4e58dcdaf715dcecedcfda.

![image](https://user-images.githubusercontent.com/4147484/190110659-2c114407-abea-4f6d-9b91-546c30b88c32.png)

@pavelsavara could you please take a look at it? I wonder which part of the commit is causing this, whether the changes to the bench sample itself or something in the rest of it.

**Comment by pavelsavara** [comment]
Ideas for the production code
- this is probably caused by `[JSExport]` initialization
- we could remove `ModuleInitializerAttribute` from the roslyn generated code and only do the `[JSExport]` initialization when `getAssemblyExports` for that dll is called.

Ideas for the benchmark:
- we could move all `JSExport` from the WebSocket benchmark to another assembly and avoid it's cost in the `ReachManaged` test. See if that makes any difference.
- we could add `LegacyReachManaged` via `bind_static_method` as it was before

**Comment by pavelsavara** [comment]
Here is branch based  on `4a2ebf2` without JSExport https://github.com/pavelsavara/runtime/tree/wasm_old_bench_without_jsexport. It's 30% faster on AOT on my chrome. It think that proves that the regression is caused by `JSExport` usage in the benchmark. At the same time it means JSExport initialization performance matters.

**Comment by pavelsavara** [comment]
I measured `428cb9b` vs `4a2ebf2` without AOT and I have same numbers on my machine. That's strange. Let's wait for Radek's numbers.
