### ISSUE TITLE
Question about Vectorize IndexOf for OrdinalIgnoreCase

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#75674]
#67758 vectorize IndexOf for ASCII only
https://github.com/dotnet/runtime/blob/ad8debf62d9ae538c4e1a2f473a5a86377eabbc8/src/libraries/System.Private.CoreLib/src/System/Globalization/Ordinal.cs#L237-L245

I don't understand why the trick works for ASCII only if we search char, not byte, we do non-linguistic search and we can get upper (valueCharU) and lower (valueCharL) for any char (a bit slow than for ASCII of course):
https://github.com/dotnet/runtime/blob/ad8debf62d9ae538c4e1a2f473a5a86377eabbc8/src/libraries/System.Private.CoreLib/src/System/Globalization/Ordinal.cs#L256-L272

**Comment by iSazonov** [comment]
My question is about 
> it's because for ASCII we can quickly compute

Does it matter in this context? I mean if the first (valueChar) character is not ASCII then we will be doing these case conversions and comparison anyway so why the same vectorization can't be used?
```c#
            if (char.IsAsciiLetter(valueChar))
            {
                valueCharU = (char)(valueChar & ~0x20);
                valueCharL = (char)(valueChar | 0x20);
                isLetter = true;
            }
            else
            {
                valueCharU = valueChar.ToUpperInvariant();
                valueCharL = valueChar.ToLowerInvariant();
                isLetter = valueCharU != valueCharL;
            }

            do
            {
                // Do a quick search for the first element of "value".
                int relativeIndex = isLetter ?
                    SpanHelpers.IndexOfAnyChar(ref Unsafe.Add(ref searchSpace, offset), valueCharU, valueCharL, searchSpaceLength) :
                    SpanHelpers.IndexOfChar(ref Unsafe.Add(ref searchSpace, offset), valueChar, searchSpaceLength);
                if (relativeIndex < 0)
                {
                    break;
                }
```

**Comment by stephentoub** [comment]
> we will be doing these case conversions and comparison anyway (in OrdinalCasing.IndexOf())

No, we won't.  Note that there both characters are upper-cased according to the casing table, and the two upper case characters are then compared for equality.  That's potentially different from getting a ToUpper and a ToLower and searching for those.  This is most evident by the fact that some characters have more than two characters that upper-case to them, e.g. this:
```C#
string s = "\u00B5\u039C\u03BC";
Console.WriteLine(s.IndexOf("\u00B5", 0, StringComparison.OrdinalIgnoreCase));
Console.WriteLine(s.IndexOf("\u00B5", 1, StringComparison.OrdinalIgnoreCase));
Console.WriteLine(s.IndexOf("\u00B5", 2, StringComparison.OrdinalIgnoreCase));
```
prints
```
0
1
2
```
because all three of '\u00B5', '\u039C', and '\u03BC' upper case to '\u039C'.  If the code did what you propose, the above example would fail to produce the same results because '\u00B5' would map only to '\u00B5' and '\u039C', and thus the code would miss the equality with '\u03BC'.

**Comment by iSazonov** [comment]
Thanks for the clarification! The "ordinal" in the name misled me.
