### ISSUE TITLE
The mscordbi.dll 6.0.922.42201 is missing from symbol servers. 

### ISSUE THREAD

**Issue by valeriob** [dotnet/runtime#75747]
Description
Hi.
I have a problem similar to https://github.com/dotnet/runtime/issues/62939, https://github.com/dotnet/runtime/issues/61775, https://github.com/dotnet/runtime/issues/62962 - when I try to open the dump, VS cannot download symbols from the servers.

![image](https://user-images.githubusercontent.com/1522516/190614417-ad5a7f1f-7fa4-4c2a-9f36-475401b26e8f.png)

I would really love to see why my app is crashing :D

**Comment by tommcdon** [comment]
@hoyosjs This looks like the latest 6.0.9 release is missing dbi/dac symbols

**Comment by cfauchere** [comment]
+1 here. this issue has occurred with so many versions. Why can't this be fixed once and for all?

**Comment by cfauchere** [comment]
Could you please provide an update?

**Comment by hoyosjs** [comment]
Thanks for the ping on this, it dropped from my notifications. @rbhanda, once more the staging pipeline failed to index symbols correctly here. Is there any check we can have to ensure the step runs? These failures make production diagnostics harder than they need to be.

**Comment by hoyosjs** [comment]
Sorry, @cfauchere @valeriob - that version doesn't seem like something that we've published. The ID doesn't match the 6.0.9 release. How did you get this build?

**Comment by cfauchere** [comment]
@hoyosjs hopefully the following clarifies a bit

using WSL I have 6.0.9.
![image](https://user-images.githubusercontent.com/12868340/198167176-58ccd432-099c-496d-9715-a87eaf4ba5fe.png)

the containers from which the dump is collected is running redhat. 
![image](https://user-images.githubusercontent.com/12868340/198167260-6c2e3aa4-b709-47ae-b796-3852e38b0def.png)

when I try to debug the dump in VS I get the following
![image](https://user-images.githubusercontent.com/12868340/198167378-1bdf8722-9317-4257-8e86-ed71fa880aa4.png)
![image](https://user-images.githubusercontent.com/12868340/198167389-0c6ed431-eef7-4605-9d5b-c40bf4b2faa4.png)


![image](https://user-images.githubusercontent.com/12868340/198167429-71d55257-d231-416b-9862-3a99374f459f.png)

**Comment by hoyosjs** [comment]
That explains why the versions don't match. Since Microsoft doesn't own the RedHat builds, they won't be indexed in the symbol servers. Cross-OS .NET debugging is also something they don't do since it's a Windows binary, and it's tied to the exact build, so the one we provide from out build won't match. It's odd that the version doesn't match our public version though (separate issue, but cc @omajid @tdms @dotnet/source-build-internal @mmitche).

**Comment by cfauchere** [comment]
@hoyosjs, not sure I understand the framework for Linux is not provided by MS?

**Comment by hoyosjs** [comment]
We do have a build for Linux, you can easily get it from the download page or there's docs on other ways to get it. But the build you get from RH's package manager is built by them. They grab the source and build it in isolation - it's part of their requirements for distro package manager distribution. They have their own story on how to acquire symbols and how to debug. You'll likely need to be in a RedHat machine and use LLDB on your dump to debug the coredump. The folk i tagged have more familiarity with RH's symbol story.

**Comment by mmitche** [comment]
@cfauchere Thanks a ton for the info. This is an interesting scenario and I'll bring it up tomorrow in our sync on this kind of thing,

**Comment by mmitche** [comment]
To be clear @cfauchere, they're building exactly what Microsoft ships (commit-wise), just in their own environment. You might think of Microsoft and RedHat/Canonical as ".net distributions"? That said, this does complicate some cross-OS situations. I'll sync with my team tomorrow and see what we have in the works around this.

**Comment by cfauchere** [comment]
@mmitche, I see. The code is open source and each distribution can build for its own.

**Comment by hoyosjs** [comment]
dotnet dump will load, but can you run any commands like clrstack? The other issue is dump can only look at managed state, but maybe that isn't a concern to you.

**Comment by cfauchere** [comment]
@hoyosjs yes, I can run commands like dumpgen or dumpheap etc works like a charm.
```
whereis dotnet
dotnet-dump analyze ...
setclrpath whateverpathwasfoundbefore
dumpheap
```

**Comment by hoyosjs** [comment]
Is this on your Windows machine? I don't expect that to work. Can you please run sos status and setclrpath.

**Comment by cfauchere** [comment]
yes, that's my windows machine using WSL.
![image](https://user-images.githubusercontent.com/12868340/198397790-0f5fcd7d-e446-43eb-8f04-8a15fae75dc8.png)

**Comment by hoyosjs** [comment]
This one is "interesting". You aren't really debugging on Windows per-se, but rather you are in a Linux system running on windows. That means the debugging system is an ELF compilation (*.so). The way that dotnet-dump hosts the diagnostics stack is a bit more permissive on Linux - particularly it skips the version check. You used `setclrpath` to your local runtime - this says "trust me, the runtime I used to do this lives here". SOS loads the ELF files from there and you get something - this view *may* be correct, if things haven't changed too much. The RedHat build has a layout, and our build has another one potentially - this is up to the compiler. Given that they are built by clang and they are from the same commit you are likely to see the right answer.

Visual Studio won't host an ELF since it runs on Windows. It has to host the services in a PE format (a dll essentially). The dll has a bit of version information to make sure that it has the same info that the Linux version of the runtime. There's no equivalent windows version of the Linux RH-built runtime, so it fails to fetch the symbols and there's no DLL that will make the version check happy here... Essentially you can't point Visual Studio to a dump of a runtime built by RH - there's no debugging service they can host to reason about the bits on the dump.

**Comment by hoyosjs** [comment]
I'll be closing this one as it is not actionable from a symbols perspective - it's not really that symbols are missing but rather is a whole unsupported scenario (cross-OS diagnostics with a build we don't index, cc: @dotnet/dotnet-diag). As for the versioning issue, should we have another issue for that @mmitche?
