### ISSUE TITLE
[API Proposal]: AsnWriter Encode with callback

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#75759]
### Background and motivation

`AsnWriter` has `Encode` in two forms: writing to a `Span<byte>` and allocate-and-return `byte[]`.

There are several uses of `AsnWriter` where we write something to ASN.1 and then do something with it, like sign it or hash it. The allocating return well, allocates. The span-writing forces developers to come up with an intermediate, either on the stack, a pool rental, etc. Both require the contents to be copied.

However, `AsnWriter` already has the data available internally. I propose we make this available with a callback to `Encode`.

### API Proposal

```csharp
namespace System.Formats.Asn1;

public partial class AsnWriter {
#if NET9_0_OR_GREATER
        public TReturn Encode<TReturn>(Func<ReadOnlySpan<byte>, TReturn> encodeCallback);
        public TReturn Encode<TState, TReturn>(TState state, Func<TState, ReadOnlySpan<byte>, TReturn> encodeCallback)  where TState : allows ref struct;
#endif
}
```

The proposal allows passing in a state and a return. The state and return can be used to feed in state and allow the callback to remain static and not capture anything.

An overload without `state` exists so that passing in something is not required if it is not needed.

Since System.Formats.Asn1 is supported down level, these APIs will only exist for .NET9+ since ref structs as type arguments is not permitted until then.

### API Usage

Consider this snippet in the runtime today:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X500DistinguishedNameBuilder.cs#L355-L359

This would become:

```csharp
return _writer.Encode(static (ReadOnlySpan<byte> encoded) => {
    return new X500DistinguishedName(encoded);
});
```

The same pattern is used for decoding DSA keys for macOS and Android:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Pal.macOS.cs#L95

Encrypting CMS in PKCS:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs#L144-L146

Encoding a CMS:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs#L136

Hashing signed attributes:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs#L646

Etc.

**Comment by bartonjs** [comment]
I feel like in my original proposal for AsnWriter I had a SpanAction (or custom SpanAction-like delegate) for Encode; but I don't see it in https://github.com/dotnet/designs/blob/main/accepted/2020/asnreader/asnreader.md or https://github.com/dotnet/corefxlab/blob/archive/src/System.Security.Cryptography.Asn1.Experimental/System/Security/Cryptography/Asn1/AsnWriter.cs so someone must have convinced me to cut it pretty early.  (I also don't see it in the private implementation that led up to the public one... huh.)

Anyways, the question from that is mainly why ReadOnlyMemory instead of ReadOnlySpan?  I was going to say next that AsnWriter is pretty defensive about its buffer, but exposing the ReadOnlySpan in a SpanAction would still allow unsafe (or Unsafe) access to turn it back into something writable; so it probably doesn't matter that with ReadOnlyMemory it's slightly easier to just reach in and grab the array and turn it into something writable...

Oh, there is one difference (aside from ReadOnlyMemory being able to flow to more places): As a ReadOnlyMemory someone can capture it and exit the callback with the reference.  As a ReadOnlySpan it's tightly contained.

I'll also ask if you think there's value in an Action-based variant, or if we should just make anyone who only cares about draining the value into (e.g.) a hash accumulator return 0 (until it becomes too popular to do so, or whatever).

**Comment by vcsjones** [comment]
> So someone must have convinced me to cut it pretty early

I think the original proposal had `SpanAction` in it, but `SpanAction` isn't in netstandard2.0, so we couldn't use it, and it became a "eh we'll add it when someone wants it", so, "Hi."

> I also don't see it in the private implementation that led up to the public one

Right now we have an internal API that just returns a `ReadOnlySpan<byte>`.

>  why ReadOnlyMemory instead of ReadOnlySpan

I started off this way, but changed it because a ROM is at least as useful as a ROS, but a ROS is not as useful as a ROM. For example, in the above examples I found of places this would be useful, `PkcsHelpers.EncodeContentInfo` takes a ROM, and it couldn't easily be made to take a ROS, unless we did the "pin it and use a custom memory manager" trick.

>  it probably doesn't matter that with ReadOnlyMemory it's slightly easier to just reach in and grab the array and turn it into something writable

Right. Plus the capturing ergonomics you already mentioned.

> I'll also ask if you think there's value in an Action-based variant

I thought about it... but "just return `null`" seemed fine to me instead of introducing an overload.

**Comment by GrabYourPitchforks** [comment]
I'm not thrilled about the idea of adding a delegate that exposes an ephemeral `ROM<T>`. If your API takes `ROM<T>` instead of `ROS<T>`, it means that you're intending to hold on to it or otherwise "capture" it. But this API would by definition be giving you something that's borrowed, and if you pass it to a capturing API it could lead to weird instability.

```cs
ReadOnlyMemory<byte> bytes = default;
instance.DoSomethingWith((/* ..., */ memory) => { bytes = memory; });
byte[] array = bytes.ToArray(); // ?????
```

This code sample is basically unsafe-equivalent, because you could be pointing to something that has been returned to the array pool, or to random stackalloc memory in a frame which has already been popped, or \<whatever\>.

Since we don't have a runtime / language-wide concept of borrowing an object, the best course of action is to rely on our existing type which represents "borrowed memory" - and that existing type is `ROS<T>`.

**Comment by vcsjones** [comment]
That's a good point that I agree with. Span makes sense from that perspective. Proposal updated.

**Comment by bartonjs** [comment]
The delegate probably wants appropriate co-and-contra-variance annotations

```C#
public delegate TReturn SpanEncodeFunc<in TState, out TReturn>(TState state, ReadOnlySpan<byte> encoded);
```

For naming and ordering.  Based on SpanAction, it probably should be `(ReadOnlySpan<byte> ???, TState state)`.  The only delegates I see that currently take spans call them `span`, which is pretty weak.  So `encoded` might be the best name to start with.

`TState` is probably the right name for the generic parameter on the Encode method, but based on Action and Func it should probably just be `<T>`.

```C#
namespace System.Formats.Asn1
{
    partial class AsnWriter
    {
        public delegate TReturn SpanEncodeFunc<in T, out TReturn>(ReadOnlySpan<byte> encoded, T arg);

        public TReturn Encode<TState, TReturn>(TState state, SpanEncodeFunc<TState, TReturn> encodeFunc);
    }
}
```

There's also an interesting question of whether we should be doing

a) SpanFunc, here
b) SpanFunc in System.Buffers
c) Just use the existing SpanAction (and make return values go via a mutable TState)

Since we have a netstandard2.0 reference assembly, (c) is awkward, and (c) is not netstandard2.0, I'd suggest not (c).  I feel like we don't like having public delegate types as nested types, so (a) is really (a') (System.Formats.Asn1.SpanEncodeFunc).  Since nothing in the signature really ties it to the ASN.1 namespace that feels like it might be (b).

```C#
// Do we have a place to do this ns2.0, or are we splitting our ref.cs now?
namespace System.Buffers
{
    public delegate TReturn ReadOnlySpanFunc<in T, out TReturn>(ReadOnlySpan<byte> span, T arg);
}

namespace System.Formats.Asn1
{
    partial class AsnWriter
    {
        public TReturn Encode<TState, TReturn>(TState state, SpanEncodeFunc<TState, TReturn> encodeFunc);
    }
}
```

@stephentoub We've avoided (RO)SpanFunc thus far... it it popped up with this proposal would that be something you'd endorse, fight, or not really care about?

**Comment by stephentoub** [comment]
> We've avoided (RO)SpanFunc thus far... it it popped up with this proposal would that be something you'd endorse, fight, or not really care about?

I'd like to see if we can get to a point in .NET 8 / C# 12 where ref struct constraints would enable us to define a more general set of delegates (cc: @AaronRobinsonMSFT, @steveharter), or better yet, enable us to use the _existing_ `Action<...>`/`Func<...>` as long as the `T`s used are so constrained.

In the meantime, we can make forward progress on these kinds of issues with whatever custom delegates we need to define, but it'd be good to keep track of the ones we'd like to rip out prior to shipping .NET 8 should we be able to replace them successfully.

**Comment by AaronRobinsonMSFT** [comment]
>enable us to use the existing Action<...>/Func<...> as long as the Ts used are so constrained.

@stephentoub I assume you mean https://github.com/dotnet/runtime/issues/65112? As in when `ref` structs are permitted in Generics we ensure the constraints allow us to express signatures with them rather than creating new full types. We are in agreement.

**Comment by stephentoub** [comment]
Right, e.g. the goal here would be to be able to write:
```C#
public TReturn Encode<TState, TReturn>(TState state, Func<ReadOnlySpan<byte>, TState, TReturn> encodeFunc) { ... }
```
with the existing `Func<...>`.

**Comment by vcsjones** [comment]
Updated the proposal with `Func` now that it can be used.

**Comment by bartonjs** [comment]
* We talked about the consequences and future upgradability of TReturn not being `allows ref struct`, and are good with it as proposed.

```C#
namespace System.Formats.Asn1;

public partial class AsnWriter {
#if NET9_0_OR_GREATER
    public TReturn Encode<TReturn>(Func<ReadOnlySpan<byte>, TReturn> encodeCallback);
    public TReturn Encode<TState, TReturn>(TState state, Func<TState, ReadOnlySpan<byte>, TReturn> encodeCallback)
        where TState : allows ref struct;
#endif
}
```
