### ISSUE TITLE
AccessViolationException when Trimming using .NET 7 preview trimming with GetTypeFromProgID

### ISSUE THREAD

**Issue by adirh3** [dotnet/runtime#75775]
### Description

When trimming a .NET 7 Console App that uses `GetTypeFromProgID` it will crash on `AccessViolationException` when trying to invoke any method of the newly created type.

### Reproduction Steps

Program.cs - 
```C#
using System;
var t = Type.GetTypeFromProgID("Shell.Application");
dynamic shellApp = Activator.CreateInstance(t!)!;
dynamic ws = shellApp.Windows();
```

csproj - 
```XML
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>partial</TrimMode>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>
</Project>
```

Run - 
`dotnet publish -c release -r win10-x64 --self-contained=true`

### Expected behavior

Program runs without crashing

### Actual behavior

Program crashes due `AccessViolationException` in the last line of `Program.cs`.

### Regression?

This issue started when I updated my app to .NET 7, same thing in .NET 6 with `TrimMode` set to `CopyUsed` is working.

### Configuration

Windows 11, x64
.NET 7 RC1

**Comment by vitek-karas** [comment]
Publishing this app produces 3 warnings:
```Console
C:\repro\illinker\comid\Program.cs(3,1): Trim analysis warning IL2072: Program.<Main>$(String[]): 'type' argument does
not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Activator.CreateInstance
(Type)'. The return value of method 'System.Type.GetTypeFromProgID(String)' does not have matching annotations. The sou
rce value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\r
epro\illinker\comid\comid.csproj]
C:\repro\illinker\comid\Program.cs(4,1): Trim analysis warning IL2026: Program.<Main>$(String[]): Using member 'Microso
ft.CSharp.RuntimeBinder.Binder.InvokeMember(CSharpBinderFlags, String, IEnumerable<Type>, Type, IEnumerable<CSharpArgum
entInfo>)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Using
dynamic types might cause types or members to be removed by trimmer. [C:\repro\illinker\comid\comid.csproj]
ILLink : Trim analysis warning IL2026: Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal(Com
ActivationContextInternal*): Using member 'Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForType(ComActi
vationContext)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. B
uilt-in COM support is not trim compatible. https://aka.ms/dotnet-illink/com [C:\repro\illinker\comid\comid.csproj]
```

Extracting two parts of this message:
`Using dynamic types might cause types or members to be removed by trimmer.`
`Built-in COM support is not trim compatible.`

Switching to .NET 6 the publish actually produces even more warnings - 7 in total. But the picture is basically the same. Dynamic and COM are not supported with trimming.

I think these make it pretty clear that the app may break. In .NET 6 it happened to work, in .NET 7 it doesn't. The toolchain produces these warnings exactly for this reason - we can't guarantee that the app will work.

As for expectations:
* We're unlikely to support `dynamic` with trimming anytime soon (I would say ever, but never say never)
* We've looked at supporting built-in COM with trimming, but it's effectively impossible to do it correctly, so that won't happen anytime soon either (if ever)

Currently this is by design - we simply don't support this type of app to be trimmed.

**Comment by adirh3** [comment]
Thanks for the quick reply @vitek-karas!
I have noticed using `CopyUsed` trim mode, it will work in .NET 7, but it will still invoke the new trimming all libraries feature in .NET 7, which can only be disabled by using `TrimMode` set to `partial`.

I understand that you are not planning to support this specific scenario, but this is a breaking change that may affect other scenarios when partial trimming is needed with `CopyUsed`.
I think it's worth mentioning in the [breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/deployment/7.0/trim-all-assemblies) which currently states that using `partial` reverts to same behavior as .NET 6.

**Comment by vitek-karas** [comment]
Thanks - I will add it to the list.
