### ISSUE TITLE
Host can stop when it knows all IHostedServices stopped

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#75972]
The host doesn't support running one or more finite tasks and then exiting.
Ones the tasks are done, it sits idle.

Example application:

```cs
IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .Build();

await host.RunAsync();

public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await Task.Delay(1000, stoppingToken);
        _logger.LogInformation("DONE!");
    }
}
```

In case all `IHostedServices` are `BackgroundServices` the host knows when they are finished, and it can stop itself.

cc @eerhardt @davidfowl

**Comment by davidfowl** [comment]
I see the appeal of this but I wonder what the use case for this is.

**Comment by tmds** [comment]
Use Configuration, DI and Logging in apps that don't run until stopped.

**Comment by eerhardt** [comment]
So a `Console App` + `Microsoft.Extensions`?

**Comment by davidfowl** [comment]
https://github.com/Cysharp/ConsoleAppFramework

**Comment by tmds** [comment]
> https://github.com/Cysharp/ConsoleAppFramework

Nice! This is what I'm looking for.

**Comment by eerhardt** [comment]
Also see https://github.com/dotnet/command-line-api/tree/main/src/System.CommandLine.Hosting. (Full disclosure, I haven't actually used this. Just heard about it from @jonsequitur).

cc @adamsitnik for the "Console App Model" angle here.

**Comment by tmds** [comment]
I'll also take a closer look at the `System.CommandLine.Hosting` package.

**Comment by jonsequitur** [comment]
I'm not super familiar with the hosting package myself. We're very interested though in knowing what kinds of patterns people are looking for here. 

The prevailing approach taken by `Microsoft.Extensions.Configuration.CommandLine`, for example, is that command line parameters are part of configuration, which is an input to DI, which is in turn an input to the primary work of the app (e.g. web request handlers). System.CommandLine is in many ways more like an application framework. Command line handlers are more like web request handlers and sometimes need injected dependencies in order to do their work. But the existing patterns lend themselves to slower, more complex startup that can hurt performance for command line apps that are very short-lived (including the current model for command line completions.) An additional complexity is that *all apps are command line apps*. Sometimes a single CLI will have different commands that lead to very different kinds of runtime behaviors. In one mode the app might be a web server and in another mode, a utility. I've often recommended using completely different dependency setups for different subcommands on the same CLI for this reason.
