### ISSUE TITLE
[Mono] Intrinsify Vector128:ExtractMostSignificantBits on ARM64 and AMD64

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#76025]
WASM has added intrinsics support for `Vector128:ExtractMostSignificantBits`, where they saw big performance gain on a few Span and Json API's. 
Implement intrinsics support for `ExtractMostSignificantBits` on:

- [x] ARM64 mini JIT
- [x] ARM64 LLVM
- [x] AMD64 mini JIT
- [x] AMD64 LLVM

NOTE: Additionally, investigate if `Vector64` variant could be easily handled by the change.

**Comment by jandupej** [comment]
Did a little checking, on x86 we can use `_mm_movemask_epi8/ps/pd`, these are SSE and SSE2, so this is perfectly fine with x86-64. There is no such operation for int16 - if we want it, we can `_mm_shuffle_epi8` so that odd bytes are packed in the lower half of the reg, then extract the byte mask and keep only the lower 8 bits of that. That requires SSSE3 and one load for the shuffle indices. It seems CoreCLR does it this way also.

For arm64, there is no instruction to extract mask. CoreCLR does this by `and`ing away all but the MSB from each element, shift the MSBs and `addv` them to form the mask. This seems like the best option right now.

**Comment by SamMonoRT** [comment]
cc @matouskozak for further work.
