### ISSUE TITLE
WASM: GL object no longer accessible in .net 7 (Skiasharp)

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/runtime#76077]
### Description

If you have a `wasm-browser` or blazor wasm app.

In .net 6 ES6 module (iiuc) were not used... that means that the javascript that gets added to dotnet.js

![image](https://user-images.githubusercontent.com/4672627/191994548-45c4f91a-8168-4962-8cb8-86b5c49efc75.png)

This added js (note the var GL =... etc)

becomes global and allows webgl interop in skiasharp and others.

Now the ES6 modules are used... my understanding is that this is no longer accessible outside of dotnet.js.

### Reproduction Steps

clone --recursive https://github.com/AvaloniaUI/Avalonia/tree/features/blazorless-wasm

cd into src/Web/Avalonia.Web.Sample

dotnet run

then open in dev tools, put a breakpoint in line 5794 dotnet.js, confirm GL object created.

note that in main.js its lost from scope, after dotnet runtime create() function ends.

### Expected behavior

some mechanism to capture this variable or for this to be global.

### Actual behavior

no longer available.

### Regression?

yes, this worked fine in net 6 and many libraries are relying on this.

**Comment by thaystg** [comment]
@pavelsavara

**Comment by pavelsavara** [comment]
This is similar to https://github.com/dotnet/runtime/issues/74664
The Net7 runtime is not spilling the emscripten guts into JS global namespace anymore.

If this is in context of Blazor , you want to find it on `window.Module.GL`.
If this is in non-blazor scenario, you could make it global yourself 
```.js
import { dotnet } from './dotnet.js'

const { Module } = await dotnet.create();
globalThis.Module=Module;
globalThis.GL=Module.GL;
```

The real question is how to configure the emscripten compilation to add A) webGL module and to B) export the `GL` symbol.

A) is passing something like `<EmccFlags>-s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_GLFW=3</EmccFlags>` but that didn't work for me today.  Maybe I also need to pass `-lwebgl.js` ?
@danwalmsley How did you do that in the past ?

B) I think `-s EXPORTED_RUNTIME_METHODS` needs to be extended with `GL` and other symbols, so that they would be visible on `Module` object. As far as I can tell we currently don't support that extensibility and we could improve that.

@radical please advise me on the MSBuild properties.

**Comment by pavelsavara** [comment]
I made some progress. This is what you want included:
https://github.com/emscripten-core/emscripten/blob/fc3a21739ba9720b9a1010bc771ad2d16d73fee5/src/library_webgl.js#L164

I did that by

```.xml
  <PropertyGroup>
    <EmccExtraLDFlags> -s USE_CLOSURE_COMPILER=1 -s ASSERTIONS=1 -s LEGACY_GL_EMULATION=1 -lGL -lSDL -s EXPORTED_RUNTIME_METHODS=&quot;['FS','GL','print','ccall','cwrap','setValue','getValue','UTF8ToString','UTF8ArrayToString','FS_createPath','FS_createDataFile','removeRunDependency','addRunDependency']&quot;</EmccExtraLDFlags>
    <WasmBuildNative>true</WasmBuildNative> 
  </PropertyGroup>
```

```.c
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <SDL/SDL.h>
#include <emscripten.h>

extern void glBegin(int mode);
extern void glBindBuffer(int target, int buffer);

int EMSCRIPTEN_KEEPALIVE test_gl() {
	SDL_Init(SDL_INIT_VIDEO);

	return 0;
}
```

That together links the right things into `dotnet.js` and makes it visible on `Module` object.

the hack of `EXPORTED_RUNTIME_METHODS` is ugly because instead of merging with our list of values you have a copy. That would break you in the future if you don't get it in sync. So I think we need to provide extension point instead.

The `USE_CLOSURE_COMPILER` is there because otherwise `library_glemu.js` is not ES6 friendly and makes `assignment to undeclared variable _emscripten_glEnable` and many more like this 
https://github.com/emscripten-core/emscripten/blob/fc3a21739ba9720b9a1010bc771ad2d16d73fee5/src/library_glemu.js#L195

Overall I wonder if you want to upgrade to WebGL2 ?

**Comment by radical** [comment]
re:EXPORTED_RUNTIME_METHODS, we can add a property to allow extending it.

**Comment by mattleibow** [comment]
What would be something to do that is minimal impact and just in JS?

Something like this?

```js
GL = GL || window.Module.GL
```

I know this is not perfect JS, but instead of adding all sorts of properties and targets files, is this reasonable?

**Comment by pavelsavara** [comment]
> I know this is not perfect JS, but instead of adding all sorts of properties and targets files, is this reasonable?

Could you please re-phrase your question. I do not follow. Thanks!

**Comment by mattleibow** [comment]
I am basically asking if there is a way to do this in just JS code and not have to do a whole bunch of work like this: https://github.com/dotnet/runtime/issues/76077#issuecomment-1260231545

**Comment by mattleibow** [comment]
I suppose this code here is the thing I should be looking at? https://github.com/dotnet/runtime/issues/76077#issuecomment-1259974327

**Comment by pavelsavara** [comment]
> I am basically asking if there is a way to do this in just JS code and not have to do a whole bunch of work like this: [#76077 (comment)](https://github.com/dotnet/runtime/issues/76077#issuecomment-1260231545)

I think the answer is no.

It really depends on how SkiaSharp configures the emscripten already. Could you please point me to it ?
Or was older version of emscripten including GL emulation module by default ?

**Comment by mattleibow** [comment]
SkiaSharp uses the default things that blazor provided and just referenced GL and GLctx directly from the global namespace:

https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/wwwroot/SKHtmlCanvas.ts#L2

**Comment by pavelsavara** [comment]
The top description speaks about Avalonia, which has some tweak for the way how `dontnet.js` is built.

https://github.com/AvaloniaUI/Avalonia/blob/features/blazorless-wasm/src/Web/Avalonia.Web.Sample/Avalonia.Web.Sample.csproj#L10

https://github.com/AvaloniaUI/Avalonia/blob/features/blazorless-wasm/src/Web/Avalonia.Web/Avalonia.Web.props#L3

https://github.com/AvaloniaUI/Avalonia/blob/features/blazorless-wasm/src/Web/Avalonia.Web/interop.js#L8

**Comment by mattleibow** [comment]
I added the `GL` to the list of exports, it appears but I am not sure how to get hold of `GLctx`?

**Comment by mattleibow** [comment]
I see I can get it from `GL.currentContext.GLctx`, so all good on that.

**Comment by mattleibow** [comment]
I got this working again by writing a bit of JS and doing a call in that to set it up: https://github.com/mono/SkiaSharp/pull/2268
