### ISSUE TITLE
[API Proposal]: Non static variants of IMultiplicativeIdentity and IAdditiveIdentity

### ISSUE THREAD

**Issue by MichalBrylka** [dotnet/runtime#76132]
### Background and motivation

It seems that both
``` c#
interface IAdditiveIdentity<TSelf, TResult> where TSelf : IAdditiveIdentity<TSelf, TResult>?
{
    static abstract TResult AdditiveIdentity { get; }
}
```
and 
``` c#
public interface IMultiplicativeIdentity<TSelf, TResult> where TSelf : IMultiplicativeIdentity<TSelf, TResult>?
{
    static abstract TResult MultiplicativeIdentity { get; }
}
```
contain only static members which are fine for most cases (almost all number classes/fields/groups). But how about cases like matrices where additive identity depends on size of given matrix and multiplicative identity actually also depends on whether operand is on the left or on the right side of multiplication. 

### API Proposal

Introduce an interface like that:
```csharp
public interface IMultiplicativeIdentity<TSelf, TResult, TContext> where TSelf : IMultiplicativeIdentity<TSelf, TResult>?
{
    TResult GetMultiplicativeIdentity(TContext context);
}
```

### API Usage

```csharp
record struct MultiplicationContext(bool IsLeftOperand);

class MyMatrix<TNumber> : IMultiplicativeIdentity<MyMatrix<TNumber>, MyMatrix<TNumber>, MultiplicationContext>
    where TNumber : INumber<TNumber>
{
    private readonly TNumber[,] _data;
    public int Rows { get; }
    public int Columns { get; }

    public TNumber this[int iRow, int iCol] => _data[iRow, iCol];

    public MyMatrix(TNumber[,] data)
    {
        _data = data;
        Rows = data.GetLength(0);
        Columns = data.GetLength(1);
    }

    public MyMatrix<TNumber> GetMultiplicativeIdentity(MultiplicationContext context) 
        => context.IsLeftOperand ? GetIdentityMatrix(Rows) : GetIdentityMatrix(Columns);

    private MyMatrix<TNumber> GetIdentityMatrix(int rows)
    {
        throw new NotImplementedException();
    }
}
```

### Risks

I know it's quite tricky to provide a universal interface, so I guess this design also does not cover everything

**Comment by tfenise** [comment]
> But how about cases like matrices where additive identity depends on size of given matrix and multiplicative identity actually also depends on whether operand is on the left or on the right side of multiplication.

1. If the problem is "additive identity depends on size of matrix", the problem is not really the additive group has possibly "multiple" additive identities, rather, it's that there are possibly multiple additive groups to be used (the additive group of n*m matrices, n and m varying). Unfortunately, the current design of generic math requires a type (.NET) for every algebraic structure (math) (group, ring, etc.), as one needs to plug the algebraic structure in the generic parameter of some generic method/type. As a result, every algebraic structure to be used can only be statically defined, not dynamically created like one creates instances of some class. One may create as many instances implementing `IEnumerable` (to be consumed by e.g., LINQ) as one wants at runtime, but one may only have as many algebraic structures (to be consumed by generic math) as one may define in source code (unless using reflection emit. Generic algebraic structures may offer some flexibility, but still largely limited). It's like C without `malloc`, where one may only use static, fixed-size arrays, not dynamically allocated arrays. I'd say this is an inherent limitation of the design of the generic math or type system. We could try some workaround, though.
2. If the problem is "multiplicative identity actually depends on whether operand is on the left or on the right side of multiplication", the problem is not really the multiplicative identity "depends" on something, but rather there are mathematical concepts not covered by the generic math interfaces provided by .NET, like left/right multiplicative identity which you proposed. If really needed, we should add interfaces like `ILeftMultiplicativeIdentity` (but note that left/right multiplicative identities may not be unique, which may have mathematical or programmatical consequences), rather than a single interface `IMultiplicativeIdentity<,, TContext>` to attempt to cover them all.

**Comment by tannergooding** [comment]
It was not a goal of Generic Math to map to higher mathematical concepts like `groups`, `rings`, or `fields`. It was an explicit goal to provide an interface which maps well to concepts and patterns developers need to handle when working with math on a computer. Such a system for practical purposes has finite resources (memory and time, at the very least) and therefore has other limitations that must be considered such as rounding error, that many core mathematical principles no longer hold (associativity and distributivity, for example), and that they are often built on and represented by a "type system" which has its own limitations making it not as flexible or abstract as may be desired.

Concepts like the "identity" are not related to the instance and should not require creation of an instance to acquire. That is altogether counter-intuitive and makes it prohibitive to acquire, particularly in the case that the `T` is a reference type. Given the limitations of the .NET type system and the reasonable expectations for a math library to be used in more general purpose computing scenarios, I'd expect there to be several alternatives possible for an arbitrary `Matrix` or `Vector` type. 

The simplest approach to "fit" in with the interfaces currently defined would be that a specialized "sentinel" value be used to track the concept of "identity" and/or "zero". These values in particular are fairly "core" and also allow many shortcuts and optimizations when they can be trivially identified. At the hardware level for scalar values, many CPUs likewise have specialized concepts for such values to allow similar optimizations. Given that an `m x n` matrix can only have an identity `n x n`, this also simplifies the concept count a user must consider.

You might also want a custom interface for the Matrix/Vector concepts and to have a corresponding type to help with their creation, including in the retrieval of core values for an `m x n` matrix that better works for when the data needs to be directly tracked outside the general "concept". Such an interface would be domain specific and would not be "zero/minimal cost" like the additive and multiplicative identity properties currently exposed are designed to be.

**Comment by MichalBrylka** [comment]
@tfenise this is what I meant 
@tannergooding that's fair assumption. I kinda expected that generic math was trying to model concepts available to mostly used structures - numbers. In that regard it works nicely. This issue can be closed
