### ISSUE TITLE
Incorrect marshalling of IntPtr in union

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#76175]
### Description

Next example shows incorrect output in managed code of `StructA.Y`. For some reason the value is truncated.

Managed part:
```c#
using System;
using System.Runtime.InteropServices;

public class Program
{
  [StructLayout(LayoutKind.Sequential)]
  internal struct StructA
  {
    internal IntPtr X;
    internal IntPtr Y;
    internal IntPtr Z;
    internal uint XLength;
    internal uint YLength;
    internal uint ZLength;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal struct StructB
  {
    internal IntPtr Data;
    internal uint DataLength;
    internal bool Flag;
  }

  [StructLayout(LayoutKind.Explicit)]
  internal struct UnionStruct
  {
    [FieldOffsetAttribute(0)]
    internal StructA A;
    [FieldOffsetAttribute(0)]
    internal StructB B;
  }

  [DllImport("tmp.so", EntryPoint = "test_func")]
  internal static extern IntPtr testFunc(int value);

  static void Main(string[] args)
  {
    Console.WriteLine("Hello World!");

    IntPtr ptr = testFunc(10);

    var unmanagedStruct = Marshal.PtrToStructure<UnionStruct>(ptr);

    Console.WriteLine(">>> managed:");
    Console.WriteLine(unmanagedStruct.A.X);
    Console.WriteLine(unmanagedStruct.A.Y);
    Console.WriteLine(unmanagedStruct.A.Z);
    Console.WriteLine(unmanagedStruct.A.XLength);
    Console.WriteLine(unmanagedStruct.A.YLength); 
    Console.WriteLine(unmanagedStruct.A.ZLength);

    Console.WriteLine(unmanagedStruct.B.Data);
    Console.WriteLine(unmanagedStruct.B.DataLength);
    Console.WriteLine(unmanagedStruct.B.Flag);
  }
}
```

Native part:
```c
#include <malloc.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>

typedef union {
  struct {
    unsigned char *x;
    unsigned char *y;
    unsigned char *z;
    unsigned int x_length;
    unsigned int y_length;
    unsigned int z_length;
  } A;

  struct {
    unsigned char *data;
    unsigned int size;
    bool flag;
  } B;
} union_s;

void* test_func()
{
  printf(">>> test_func:\n");

  union_s * x = (union_s *) malloc(sizeof(union_s));

  x->A.x = (unsigned char *) (0x7ea33f5000);
  x->A.y = (unsigned char *) (0x7ea3440000);
  x->A.z = (unsigned char *) (0x7ea3452c00);
  x->A.x_length = (555);
  x->A.y_length = (666);
  x->A.z_length = (1010);

  printf("x = %p, y = %p, z = %p, x_length = %u, y_length = %u, z_length = %u\n", 
    x->A.x, x->A.y, x->A.z, x->A.x_length, x->A.y_length, x->A.z_length);

  return x;
}
```

### Reproduction Steps

Compile native part with `gcc -shared -fPIC 1.c -o tmp.so`. 

### Expected behavior

Expected output:
```
Hello World!
>>> test_func:
x = 0x7ea33f5000, y = 0x7ea3440000, z = 0x7ea3452c00, x_length = 555, y_length = 666, z_length = 1010
>>> managed:
543904714752
543905021952
543905098752
555
666
1010
543904714752
2739142656
True
```

### Actual behavior

Actual output:
```
Hello World!
>>> test_func:
x = 0x7ea33f5000, y = 0x7ea3440000, z = 0x7ea3452c00, x_length = 555, y_length = 666, z_length = 1010
>>> managed:
543904714752
7034109952
543905098752
555
666
1010
543904714752
2739142656
True
```

`7034109952` value corresponds to truncated `543905021952`.

### Configuration

- Reproduces on x64/arm64. Managed part of test is built with dotnet sdk 6.0.201 or dotnet sdk 5.0.408.
- Reproduces on 6.0.0, 6.0.9 and main (8bf6a86f1bc309529604430c568c14490d44d069).
- Reproduces with Release/Debug builds of managed part of test.
- Reproduces both for Release/Debug builds of runtime.
- Reproduces both with and without any R2R images.
- Doesn't reproduce if type of `Struct.B.DataLength` is changed to ulong (as well as type of corresponding field in native part).

### Other information

cc @alpencolt @jkotas

**Comment by DaZombieKiller** [comment]
The issue here is that your `StructB` type contains a managed `bool` field, which causes it to be treated as a non-blittable type. Since `UnionStruct` contains a field of `StructB`, it too is considered non-blittable. This means that `Marshal.PtrToStructure` will attempt to marshal your type instead of just blitting the data across, resulting in the corruption of your pointer.

For ease of reproduction, here is a managed replacement for the native `test_func` method, which still reproduces the problem:
```cs
static unsafe IntPtr testFunc(int value)
{
    Console.WriteLine(">>> test_func:");
    var a = (StructA*)NativeMemory.Alloc((uint)sizeof(StructA));
    a->X = unchecked((nint)0x7ea33f5000);
    a->Y = unchecked((nint)0x7ea3440000);
    a->Z = unchecked((nint)0x7ea3452c00);
    a->XLength = 555;
    a->YLength = 666;
    a->ZLength = 1010;
    Console.WriteLine($"x = 0x{a->X:X}, y = 0x{a->Y:X}, z = 0x{a->Z:X}, x_length = {a->XLength}, y_length = {a->YLength}, z_length = {a->ZLength}");
    return (IntPtr)a;
}
```

There are a few solutions:
1. Use `*(UnionStruct*)ptr` instead of `Marshal.PtrToStructure`.
2. Change the `bool` field to `byte`, which will cause the types to be considered blittable and no marshaling will occur.
3. Add `[assembly: DisableRuntimeMarshaling]` and use `*(UnionStruct*)ptr` instead of `Marshal.PtrToStructure`.

My personal recommendation would be to go with option 2 and use `*(UnionStruct*)ptr` to read the value.

**Comment by gbalykov** [comment]
Thanks for response.

Doesn't it mean then that `Marshal.PtrToStructure` works incorrectly in such case of non-blittable types? Or marshaler is expected to work incorrectly in case of non-blittable types?

I've checked solution 2, as a workaround it works, thanks.

**Comment by DaZombieKiller** [comment]
I think this is expected behaviour, even if it may be a bit confusing.

Think about how the type would be marshaled. Each field will be written in order. The marshaller normalizes booleans to `0` (`false`) or `1` (`true`).

They are also marshaled as a Win32 `BOOL` by default, which is a 32-bit integer (so it actually needs `[MarshalAs(UnmanagedType.U1)]` to have a matching layout with native).

This means that if your pointer overlaps with a `bool`, the overlapping byte will be normalized, corrupting the value once the marshaller starts marshaling `StructB`.

To help with understanding the problem, you can try performing the marshaling yourself. Define `StructB` as:
```cs
[StructLayout(LayoutKind.Sequential)]
internal struct StructB
{
    internal IntPtr Data;
    internal uint DataLength;
    internal int Flag; // Win32 BOOL = int
}
```
And then read the value with:
```cs
var unmanagedStruct = *(UnionStruct*)ptr;

// normalize the bool
unmanagedStruct.B.Flag = unmanagedStruct.B.Flag != 0 ? 1 : 0;
```
And you will see the same pointer corruption.
As a result, you can actually "hide" the problem by defining `UnionStruct` like this:
```cs
[StructLayout(LayoutKind.Explicit)]
internal struct UnionStruct
{
    [FieldOffset(0)]
    internal StructB B;
    [FieldOffset(0)]
    internal StructA A;
}
```
Because `StructB` is marshaled first, you won't see the pointer corruption.

**Comment by jkotas** [comment]
```
  struct {
    unsigned char *data;
    unsigned int size;
    bool flag;
  } B;
```
Note that your managed definition of B does not match this structure. Size of `bool` is likely 1 byte in your C/C++ compiler. The default marshalling for `bool` assumes that the size is 4 bytes. This mismatch is contributing to the confusing behavior that you are seeing.

Manual marshalling that @DaZombieKiller suggested is the best way to avoid problems like this for more complex structs with unions, etc. You should use `byte` as managed equivalent for unmanaged `bool`.

Also, take a look at `DisableRuntimeMarshallingAttribute` that is new in .NET 7.

**Comment by gbalykov** [comment]
@DaZombieKiller @jkotas thanks for detailed descriptions!
