### ISSUE TITLE
[API Proposal]: ChannelWriter<T>.WriteAsync(Func<CancellationToken, ValueTask<T>, CancellationToken)

### ISSUE THREAD

**Issue by wsugarman** [dotnet/runtime#76281]
### Background and motivation

One use of a bounded channel is to limit the number of expensive operations performed by producers if the 1 or more consumers are not reading quickly enough. However, together the existing APIs `ChannelWriter<T>.WaitToWriteAsync(CancellationToken)` and `ChannelWriter<T>.WriteAsync(T, CancellationToken)` provide best-effort signals for whether the value can be enqueued. For multiple concurrent producers, a common pattern may look like the following:

```csharp
while (/* ... stuff to do ... */)
{
    await writer.WaitToWriteAsync(token);
    T result = await PerformExpensiveOperationAsync(token);
    await writer.WriteAsync(result, token);
}
```

As noted in the [intro to channels blog post](https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/#built-in-channel-implementations), the state of the channel may have changed between `WaitToWriteAsync` and `WriteAsync` such that the producer ends up waiting after performing its operation. Instead, it would be ideal if there was an API that enabled the execution of operations only if their results could be written to the channel.

### API Proposal

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

namespace System.Threading.Channels;

public abstract class ChannelWriter<T>
{
    public abstract ValueTask WriteAsync(Func<CancellationToken, ValueTask<T>> itemFactory, CancellationToken cancellationToken = default);
}
```

### API Usage

Refactoring the above producer:

```csharp
while (/* ... stuff to do ... */)
{
    await writer.WriteAsync(t => PerformExpensiveOperationAsync(t), token);
}
```

### Alternative Designs

Alternatively, the existing API surface may be "good enough" for concurrent producers, and the execution of arbitrary user delegates may be outside of the scope of this type.

### Risks

There are a few problems I see with this solution:
- The invocation of the `itemFactory` is inconsistent with the similar-looking method `ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey, Func<TKey,TValue>)` where the `valueFactory` is invoked outside of the lock
- This API is prescribing that the computation of values occur asynchronously whereas the other APIs accept values of type `T` and are agnostic to how to they were assigned
- There isn't a parallel for `TryWrite(T)`
- While the Channel APIs are focused on reducing allocations, this API almost encourages the use of closures

**Comment by gfoidl** [comment]
> be ideal if there was an API that enabled the execution of operations only if their results could be written to the channel
> ...
> ```c#
> while (/* ... stuff to do ... */)
>{
>    await writer.WriteAsync(t => PerformExpensiveOperationAsync(t), token);
>}
>```
So `PerformExpensiveOperationAsync` would be delayed until there's room in the channel, meaning reader(s) can also read from it, thus it's more or less equivalent* to:
```c#
Channel<Func<Task<T>>> channel = ...

// Producer:
while (/* ... stuff to do ... */)
{
    await writer.WriteAsync(() => PerformExpensiveOperationAsync());
}

// Reader:
await foreach (Func<Task<T>> itemFactory in reader.ReadAllAsync())
{
    T item = await itemFactory();
}
```
\* cancellation left aside and Task is used as "PerformExpensiveOperationAsync" is assumed to be non-sync in this example as opposed to the general API suggestion)

Or -- if possible from the use-case of course -- instead of the `Func<Task<T>>` you could put the `Task<T>` into the channel, then the reader just needs to await the read task and has it's T to operate on.
```c#
Channel<Task<T>> channel = ...

// Producer:
while (/* ... stuff to do ... */)
{
    await writer.WriteAsync(PerformExpensiveOperationAsync());
}

// Reader:
await foreach (Task<T> itemTask in reader.ReadAllAsync())
{
    T item = await itemTask;
}
```

**Comment by stephentoub** [comment]
Thanks for the suggestion. I'm not really clear on what benefits this would provide... the only benefit here is one line instead of three?

**Comment by wsugarman** [comment]
The problem I am looking to solve is to delay the execution of potentially expensive operations until the channel has capacity for the result.

For example, my team is leveraging channels with many producers asynchronously downloading blobs in parallel while one consumer reads the results and returns them to the user. We use a bounded channel to prevent too many blobs from being fetched and taking up memory while the consumer catches up. While these producer threads can use `WaitToWriteAsync` to wait on the channel's capacity, more producers than spare capacity may be signaled when space finally becomes available, leading to more operations executing than intended. So, I was hoping there could be a more accurate API for concurrent producers.

Without it, any bound we place on the channel is a best effort; sure the elements aren't entering the channel, but we spent the time fetching them and the memory holding them until the channel is ready.

**Comment by stephentoub** [comment]
So what you're actually looking for is a way to reserve a spot in the channel before creating the thing to fill it?

**Comment by wsugarman** [comment]
Yeah, exactly!

**Comment by theodorzoulias** [comment]
> [...] thus it's more or less equivalent* to:
> 
> ```cs
> Channel<Func<Task<T>>> channel = ...
> 
> // Producer:
> while (/* ... stuff to do ... */)
> {
>     await writer.WriteAsync(() => PerformExpensiveOperationAsync());
> }
> 
> // Reader:
> await foreach (Func<Task<T>> itemFactory in reader.ReadAllAsync())
> {
>     T item = await itemFactory();
> }
> ```

@gfoidl I don't think that it's equivalent. With your approach the producer is doing essentially nothing, and all the work is done by the consumer. This defeats the whole purpose of the producer-consumer pattern.

**Comment by theodorzoulias** [comment]
@wsugarman let me describe the simplest possible scenario that I can think, where the suggested feature would be useful:

- 2 producers
- 1 consumer
- Bounded `Channel<T>` with capacity 2.
- Requirement for a maximum of 3 `T`s to be either instantiated or under construction concurrently.

Currently it's impossible to satisfy this requirement with a `Channel<T>`, because at some moment the consumer might be consuming a `T`, the channel containing another `T`, and the two producers both instantiating one `T` each, having 4 `T`s is total.

Your suggestion would make possible to satisfy the requirement, with the side-effect of delegating the responsibility of constructing the `T`s from the producer to the channel. Essentially the channel would be the actual producer, and the original producer would do essentially nothing. I think that in most scenarios this delegation of responsibility would be undesirable or unacceptable. At the minimum you would need an overload that accepts [`TaskScheduler`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.paralleloptions.taskscheduler) argument, to allow people have a say about where the `itemFactory` will be invoked. Too complicated IMHO. There might be simpler solutions to the problem than this.

**Comment by wsugarman** [comment]
@theodorzoulias - I think you make a lot of sense. The simplest solution to control the number of instantiations probably is to leverage something like a semaphore that is entered by the producers and released by consumers. It's sort of a bummer, as this scenario seems so close to bounded channels, especially given Stephen's [intro in the blog](https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/#what-is-a-channel). However, perhaps the firm constraint of controlling instantiations would sabotage the relative simplicity of channels and its API.
