### ISSUE TITLE
DSACertificateExtensions is not supported on iOS

### ISSUE THREAD

**Issue by tranb3r** [dotnet/runtime#76305]
Why isn't System.Security.Cryptography.X509Certificates.DSACertificateExtensions supported on iOS ?
Is there something that prevents iOS from using a DSA certificate ?

**Comment by vcsjones** [comment]
Apple does not support DSA on iOS because DSA is a largely obsolete algorithm. Even on macOS, support is limited to importing existing keys only, it does not support key generation for DSA.

The documentation for [`kSecAttrKeyTypeDSA`](https://developer.apple.com/documentation/security/ksecattrkeytypedsa) does not include iOS, tvOS, etc. Compare that with [`kSetAttrKeyTypeRSA`](https://developer.apple.com/documentation/security/ksecattrkeytypersa) which indicates iOS is supported.

**Comment by tranb3r** [comment]
I need to get the publicKey from a DSA certificate, in order to compute spki fingerprint (for certificate pinning).
I do not understand why this operation would be restricted on iOS ?
Using BouncyCastly, I can totally do it, so I would expect dotnet to implement it as well. What do you think ? 
Or maybe there is another way to get the public key from a DSA certificate, using dotnet, and that is cross-platform ? (android/ios/windows)

**Comment by vcsjones** [comment]
> I do not understand why this operation would be restricted on iOS ? Using BouncyCastly, I can totally do it, so I would expect dotnet to implement it as well.

.NET's built-in cryptographic primitives do not implement cryptographic algorithms in C# like BouncyCastle does. .NET uses the underlying platform for cryptographic support. Since iOS does not support DSA, neither does .NET.

> Or maybe there is another way to get the public key from a DSA certificate, using dotnet, and that is cross-platform ? 

It sounds like you are already able to do this with BouncyCastle then. But I would caution that just about everything that is built in to .NET is going to fail with a DSA key on iOS.

Personally, I would instead make an effort to use an ECDSA or RSA certificate instead of investing effort in trying to support DSA.

**Comment by tranb3r** [comment]
Thank you for the clarification !
