### ISSUE TITLE
MemoryStream.Seek moves past the end of the stream

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#76351]
### Description

MemoryStream.Seek not only returns a seek amount past the end of the stream, but the stream itself is now in an invalid state.

![image](https://user-images.githubusercontent.com/1096616/192937479-62f3bf22-c662-4016-9bf4-572c0d28fb85.png)

### Reproduction Steps

```cs
var data = new byte[1024];
for (var i = 0; i < data.Length; i++)
{
    data[i] = (byte)(i % byte.MaxValue);
}

var stream = new MemoryStream(data);

var pos = stream.Seek(10000, SeekOrigin.Current);
```

### Expected behavior

Seek does not go past the end of the stream

### Actual behavior

Seek moves into the abyss

### Configuration

Using a net6.0 TFM in the net7.0 SDK:

```
> dotnet --list-sdks
7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]
```

**Comment by hartez** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream.seek?view=net-7.0#remarks

> Seeking to any location beyond the length of the stream is supported.

**Comment by mattleibow** [comment]
I see that, but isn't that both useless and invalid?

What is the purpose of supporting a position past the length?

**Comment by hopperpl** [comment]
This behavior is required by file streams. It was then specified as a **requirement by the base class ```Stream```**, so ```MemoryStream``` must support it as well.

File streams on all operating systems have 2 markers. Last Byte Written and Length. This allows allocating large files without the need of actually filling such files. All read operations between these two markers always zero bytes. 

> The fseek() function shall allow the file-position indicator to be set beyond the end of existing data in the file. If data is later written at this point, subsequent reads of data in the gap shall return bytes with the value 0 until data is actually written into the gap.
https://pubs.opengroup.org/onlinepubs/009696899/functions/fseek.html


> The pointer can also be positioned beyond the end of the file. 
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fseek-fseeki64?view=msvc-170


While dotnet per se is not required to follow these requirements or recommendations, dotnet usually follows the lower level ABI restrictions and their design behavior for less friction with existing software implementations. dotnet classes ```Stream```, ```FileStream```, ```MemoryStream``` were designed over 20 years ago, now due to compatibility this behavior cannot be changed anymore.

In theory, but to my knowledge not implemented, MemoryStream could allow a similar feature by reserving large memory first without actually committing it. That means, a MemoryStream could pre-allocate for example 100 GiB of memory without using such amount of physical memory until it is actually written that far. MemoryStream itself is limited to a maximum size of int.MaxValue, but the class is not sealed and can be overwritten with an extension class.

Also note, that ```Position``` not only can be larger than ```Length```, ```Position``` can also be negative. The same reasoning applies here, the underlying ABI does not specifically forbid that. But subsequent Read/Write operations will return an error.

**Comment by mattleibow** [comment]
Sounds like this is a feature!
