### ISSUE TITLE
Linguistic apostrophe does not work with DateOnly.TryParseExact

### ISSUE THREAD

**Issue by jmroyb** [dotnet/runtime#76413]
(NET 6.0.401, Windows 11 Version 10.0.22621.521 x64)

Folks,

DateOnly.TryParseExact with format "d MMMM 'de' yyyy" fails with text "16 d'agost de 1972" due to the apostrophe (char 39 '\'').
Text "16 d´agost de 1972" with apostrophe (char 8217 '’') works but it is not a valid apostrophe char. 

Apostrophe char ' is legal in ca-es cultureInfo but accent char ’ is not legal as apostrophe (only is valid upper some vowels). So the text should work is the one that fails: 

        var temp = "16 d'agost de 1972"; // Valid apostrophe 
        DateOnly.TryParseExact(
              temp,
              "d MMMM 'de' yyyy",
              ci,
              DateTimeStyles.None,
              out DateOnly Result);

        Console.WriteLine($"{temp} => {Result} !!Fails and should work!!");

        temp = "16 d’agost de 1972";    //Invalid apostrophe 
        DateOnly.TryParseExact(
              temp,
              "d MMMM 'de' yyyy",
              ci,
              DateTimeStyles.None,
              out Result);

Console.WriteLine($"{temp} => {Result} OK");

This code is for illustrate my tests. Please, do not copy and paste it. Use cs of zip file.

Thanks
		
[Program.zip](https://github.com/dotnet/runtime/files/9679704/Program.zip)

**Comment by tarekgh** [comment]
@jmroyb .NET gets the month names from ICU library. The month names are defined by Unicode standard (CLDR). August month name is defined as `d’agost` and notice it uses the character `’` which is `RIGHT SINGLE QUOTATION MARK` (ordinal value `0x2019`). You can look at this in the [Unicode CLDR Data](https://github.com/unicode-org/cldr/blob/97ebca5936448ef9a023c6f369814b984126a035/common/main/ca.xml#L1858).

Now you are trying to parse the date with a month name `d'agost` using the other single quote `'` (ordinal value 39). This correctly fails because the parser has no idea about a month name `d'agost`. The parser can only recognize the name `d’agost`. If you are saying month name shouldn't use `’` (0x2019) and should be `'` (39), then you need to report that to Unicode by [opening a ticket to CLDR](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues/). The parser is working as expected with the current provided month names.
