### ISSUE TITLE
System.DirectoryServices.Protocols.LdapConnection fails Bind() on Linux Systems for non-ASCII Passwords

### ISSUE THREAD

**Issue by MichaWe** [dotnet/runtime#76426]
Hello Dev-Team,

we are using `System.DirectoryServices.Protocols.LdapConnection` to connect to an Active Directory with an application that runs on a Debian system. Sadly users with non-ASCII password (like german umlauts) can't login due to an "Invalid Credentials" message.

We researched the problem and it seams that the integration of `System.DirectoryServices.Protocols.LdapConnection` with the underlying LDAP library does not handle multi-byte charaters in UTF-8 correctly. We could verify, that the password bytes are send in UTF-8 like required in LDAP-Version 3. However if the password contains multi-byte-characters, characters from the password gets cut off.

Our assumption is a conflict of "Password".Length and Encoding.UTF8.GetBytes(plainPassword).Length.
We found a workaround, that if we append so many dummy characters at the end of password string as there are multi-byte utf-8 charaters the login succeeds.

## Reproduction

System: Debian 10
LDAP: libldap-2.4-2
`.NET`: 5
`System.DirectoryServices` and `System.DirectoryServices.Protocols`: 6.0.0

```csharp
var userPassword = "passwörd";
LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier("address.ad.tld", 389);
LdapConnection cn = new LdapConnection(ldi);

cn.Credential = new NetworkCredential("user", userPassword);
cn.AuthType = AuthType.Basic;
cn.SessionOptions.ProtocolVersion = 3;
                
cn.Bind();
```
If you tcpdump the communication between host and AD you will see the missing `d` from the password.

## Workaround

Pad with dummy bytes:
```csharp
var plainPassword = "passwörd";
var passwordLength = plainPassword.Length;
var passwordBytesLength = Encoding.UTF8.GetBytes(plainPassword).Length;
var userPassword = plainPassword;
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && passwordBytesLength > passwordLength)
{
    userPassword = plainPassword + String.Concat(Enumerable.Repeat(" ", passwordBytesLength - passwordLength));
}
```

**Comment by MichaWe** [comment]
Hi @joperezr - thank you for your kind response and triage. I would be glad to help resolving the issue if you can give me some short guidance how to do so.

We tested the authentication in our Windows environment and the bug did not occur. Therefore we assume that it’s a Linux specific problem.

**Comment by joperezr** [comment]
Sure, the easiest way to try to see what is going on would be to do it under the debugger. I would start by putting a breakpoint on these lines:

https://github.com/dotnet/runtime/blob/505c27e14bb335714fcdc352c0410b901117c98e/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L1086-L1096

Which is the entry point of where we actually perform the connection and pass the password. Our library is mainly a managed wrapper on top of libldap native library, which is the responsable of actually connecting to the ldap server, and performing any operations with it, so the thing we want to debug is what is it that we are passing in as a password into that native library. 

We should be calling this method https://github.com/dotnet/runtime/blob/505c27e14bb335714fcdc352c0410b901117c98e/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/Interop/LdapPal.Linux.cs#L123-L141 which essentially is calling into this https://github.com/dotnet/runtime/blob/505c27e14bb335714fcdc352c0410b901117c98e/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/Interop/LdapPal.Linux.cs#L178 which is where I suspect the problem is. Essentially that last method must not be marshalling correctly passwords that contain non-ascii passwords. The thing to test, is probably to try to use `Marshal.StringToHGlobalAuto` and see if this works for both cases (passwords with only ascii characters, and passwords with unicode characters as well).

**Comment by joperezr** [comment]
Thanks @KonH I will take a look at your PR. The easiest way to test against a server is using docker in linux/WSL. You can check the steps that we have called out here https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/System/DirectoryServices/LDAP.Configuration.xml on how to very easily setup a docker container that runs a dummy ldap server that you can run our tests against.

**Comment by joperezr** [comment]
Not sure if you saw the feedback on the PR @KonH, but it was suggested that perhaps the issue you were hitting didn't actually have to do with the PInvoke of the line that I pointed at, but instead it is likely an issue that you are not using LDAP version 3.0 in your connection which is where unicode support got added. Can you please try in your environment to see if you can still repro if you change the LDAP version of your LdapConnection via the Session Options?

**Comment by KonH** [comment]
Unfortunately, I can't reproduce it in my environment. I think it's better to redirect this to the original author, @MichaWe
