### ISSUE TITLE
When using X509KeyStorageFlags.EphemeralKeySet, AllowPlaintextExport is missing in Export policy, and we will Exception when invoke ExportPkcs8PrivateKey

### ISSUE THREAD

**Issue by michaelkira** [dotnet/runtime#76449]
### Describe the bug
When using X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.EphemeralKeySet importing the cert, we found the export policy is System.Security.Cryptography.CngExportPolicies.AllowExport. 
![image](https://user-images.githubusercontent.com/938883/192958563-9b9bc459-9822-47db-98ca-9801cc10b84b.png)

When using X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet, we found the export policy is System.Security.Cryptography.CngExportPolicies.AllowExport | System.Security.Cryptography.CngExportPolicies.AllowPlaintextExport
![image](https://user-images.githubusercontent.com/938883/192958662-b34b2fe5-5d4f-44b2-95d7-267c02ba6b2d.png)

For some reason, we would like to use X509KeyStorageFlags.EphemeralKeySet while still able to export the plain text key, but the current behaviors is, when EphemeralKeySet is set, we will get exception when try to invoke the ExportPkcs8PrivateKey.
![image](https://user-images.githubusercontent.com/938883/192958434-1c9eba7a-9e74-420e-9d3f-b37e99ff1e77.png)

Is there a way we can override the export policy when import the certificate with X509KeyStorageFlags.EphemeralKeySet.

**Comment by bartonjs** [comment]
There's not anything you can do in the PFX open call, no.  .NET only has one bit here, because PFXImportCertStore only has one bit here.

What you're seeing when not setting EphemeralKeySet is that the key is actually being loaded into the older Windows crypto system (CAPI).  CAPI only has one bit: exportable.  When a CAPI key gets wrapped by the CNG layer it reports that one bit as two bits: exportable, plaintext-exportable.

When you set EphemeralKeySet that tells .NET to tell Windows to ignore the PFX-indicated provider entirely (since it's in-memory) and it ends up in CNG, which only sets CNG's Exportable bit.

You can, however, update the policy... if you do so before doing anything else with the key.

```C#
using (X509Certificate2 serverCert = new X509Certificate2(
    pfx,
    pwd,
    X509KeyStorageFlags.EphemeralKeySet | X509KeyStorageFlags.Exportable))
using (RSA key = serverCert.GetRSAPrivateKey())
{
    if (key is RSACng rsaCng)
    {
        rsaCng.Key.SetProperty(
            new CngProperty(
                "Export Policy",
                BitConverter.GetBytes(
                    (int)(CngExportPolicies.AllowPlaintextExport | CngExportPolicies.AllowExport)),
                CngPropertyOptions.None));
    }

    Console.WriteLine(Convert.ToHexString(key.ExportParameters(true).D));
}
```

If you try that with, and without, the middle block you should see it toggle between success and failure.

**Comment by vcsjones** [comment]
It looks like Jeremy gave a reply here - @michaelkira can you let us know if that unblocks your export?
