### ISSUE TITLE
Optimize CheckSample

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#76520]
[CheckSample](https://github.com/dotnet/runtime/blob/ae4dc9cef942258098164beae987589c9d569215/src/coreclr/vm/jithelpers.cpp#L5408-L5459) is invoked for each class probe in codegen (when TieredPGO is enabled) and seems to be quite hot, e.g.: 
![image](https://user-images.githubusercontent.com/523221/193485534-5921bc61-ef90-434a-98a2-55e3d5499857.png)

Even a simple `__rdtsc` [here](https://github.com/dotnet/runtime/blob/ae4dc9cef942258098164beae987589c9d569215/src/coreclr/vm/jithelpers.cpp#L5440) seems to speed up start time for an app I'm testing locally.

cc @AndyAyersMS 

category:performance
theme:optimization
skill-level:beginner
cost:small
impact:small

**Comment by AndyAyersMS** [comment]
Seems odd that it would be that costly.

**Comment by EgorBo** [comment]
Yes, it might be just a side-effect from that other problem I shared in the Discord, the fact that `MemberInfoCache.AddMethod` is super slow when TieredPGO is enabled. And that method stays in Tier0 (is not promoted neither to Tier1 nor OSR):

![image](https://user-images.githubusercontent.com/523221/193486237-7bc75e40-892d-4aeb-a1b0-12346bb015f2.png)

Top - PGO is enabled, Bottom - disabled. Purple  - `AddMethod`

**Comment by EgorBo** [comment]
That's extremely weird, `MemberInfoCache`1[System.__Canon]:AddMethod` is never promoted to tier1 despite being hot 🤷‍♂️ Doesn't look PGO related it's just that with PGO it's way slower due to class-probes inside the loops (~ 255 iterations so not enough for OSR?)

**Comment by EgorBo** [comment]
@AndyAyersMS Ok here is the problem:

Method `MemberInfoCache:AddMethod` is invoked 16 times, then there is some pause (App is doing different things) then it's invoked again ~10000 times this time. And is still not promoted to Tier1.

If I change `DOTNET_TC_CallCountThreshold` from 30 to e.g. 10 -- it's promoted just fine.

**Comment by EgorBo** [comment]
Ugh... it seems like the number of methods pending promotion to Tier1 is constantly growing up to 6000 (in `m_methodsPendingCountingForTier1` array) and `AddMethod` is somewhere in the end of that queue

**Comment by AndyAyersMS** [comment]
> (~ 255 iterations so not enough for OSR?)

OSR needs ~50,000 iterations. Note with PGO enabled the OSR version will still have class probes.

> Ugh... it seems like the number of methods pending promotion to Tier1 is constantly growing up to 6000 (in `m_methodsPendingCountingForTier1` array) and `AddMethod` is somewhere in the end of that queue

Right, this is what I was mentioning the other day, likely a good number of those 6000 are not all that important/interesting to rejit, but we have a straight FIFO rejit queue so no re-prioritizing can happen.

**Comment by EgorBo** [comment]
> Right, this is what I was mentioning the other day, likely a good number of those 6000 are not all that important/interesting to rejit, but we have a straight FIFO rejit queue so no re-prioritizing can happen.

I wonder if at least changing it to FILO will help. Also, I think we should check if we can set affinity for the Jit thread to run on E-cores/low priority with lower delay (e.g. 100ms->20ms)

**Comment by EgorBo** [comment]
Another quick idea: having a separate "high priority" queue for methods with loops

**Comment by EgorBo** [comment]
So, I think it's an interesting case: A single method, not promoted to Tier1 on time, causes a serious start-time regression for AvaloniaILSpy app.

It's [MemberInfoCache<_Canon>.AddMethod](https://github.com/dotnet/runtime/blob/039ced57d88703bd88a0490e3209a8e1815bebbc/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L229-L271) in this case - this method has loops but usually it operates on small arrays so not enough for OSR. The method itself is hot, at some point during start this method is invoked 10000 times! and due to PGO instrumentation and small loops, that method bottle-necks itself in class-probes (hence, the initial reason I filed this issue for). The app has a lot of code to JIT so `AddMethod` is lost somewhere in the "pending promotion to tier1" queue.

So, as Andy said, we should slightly redesign "pending promotion" queue to be, like Andy suggested, priority queue or something similar (for that we might need to continue call-counting for methods after they reach 0 in their cells)

cc @davidwrighton @noahfalk

**Comment by AndyAyersMS** [comment]
Also, did you look at where we add class probes and why? We must be putting one or more in each loop. If more than one, then perhaps some are redundant?

**Comment by noahfalk** [comment]
I like the notion of a priority queue or perhaps some rough priority buckets (ie call count 30-100, 100-1000, 1000+)? Another approach we heard about from the javascript team but never tested ourselves is bounding the promotion queue at a small size (10s or 100s) and pushing new items on the queue evicts the oldest item if needed to prevent overflow. The idea is that frequently called methods can be expected to re-enter the queue rapidly if they are evicted. This also should bias us towards promoting methods that were hot recently rather than methods that were hot in the past but no longer are.

In the past one reason we didn't do call counting for very long is that the overhead of counting was pretty high. I think @kouvel's work with call counting stubs resolved that issue and it would now be reasonable to leave call counters installed indefinitely, but we probably would want to test that out.

A last thought is that we could use stack sampling as an alternative prioritization measure. We tried this years ago using EESuspend as the sampling mechanism and the overhead was too high, but with some investment we should be able to do stack sampling more efficiently. Stack sampling also didn't identify nearly as many methods to promote. From a prioritization perspective that is useful, but if we only promoted the methods identified by sampling we didn't get same level of steady state perf wins vs. when we promoted based on call counting. We might need to combine multiple approaches to get the best results. I think a stack sampling approach takes more dev effort than many of the others, but it would also be independently useful for improving our diagnostic profiling story so we might nab two birds with one stone.
