### ISSUE TITLE
Investigate size of `.rela.dyn` section on Linux

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#76657]
It seems like this section contributes significantly to the size of the output executable on Linux (20+% of the image size).

For reference, relocations on NativeAOT/Windows accounts for only about 2% of the image size.

We should investigate whether we're doing something wrong/what can we do about it.

**Comment by filipnavara** [comment]
I'll have a peek at this.

**Comment by MichalStrehovsky** [comment]
This section is to support pointer-sized relocations. Apparently a reloc on Linux costs like 24 bytes of metadata (vs ~2 bytes on Windows).

I'm working on a change to remove a bunch of them in perf critical parts that we want to keep pointer-sized relocations in.

I'll leave some that we should just change to 32bit relative relocs because there's no good reason to use pointer-size:

- [ ] Reloc in EmbeddedPointerIndirectionNode
- [ ] Relocs in GCStaticsNode
- [ ] Reloc in ThreadStaticsNode
- [ ] Reloc in NonGCStaticsNode
- [ ] Relocs in ModuleInitializerListNode
- [ ] Relocs in PInvokeMethodFixup/PInvokeModuleFixup

There's some that need to keep pointer-size relocs but cannot be switched to the new plan right away:

- [ ] Frozen strings and frozen objects
- [ ] InterfaceDispatchCellNode

**Comment by filipnavara** [comment]
Couple of random notes:
- On x64 it would likely be possible to emit the `.rel` section instead of `.rela` and store the addends in the data. That can save a couple of bytes per record. On ARM64 this would be problematic for some types of relocations where the addend cannot be expressed (eg. `IMAGE_REL_BASED_ARM64_PAGEBASE_REL21`/`IMAGE_REL_BASED_ARM64_PAGEOFFSET_12A`).
- Currently ObjWriter emits two different types of 32-bit relative relocations. `IMAGE_REL_BASED_RELPTR32` becomes `R_X86_64_PC32`/`R_AARCH64_PREL32`. `IMAGE_REL_BASED_REL32` becomes `R_X86_64_PLT32`. The relevant code that turns `REL32` into PLT relocation is [here](
https://github.com/dotnet/llvm-project/blob/37e45ddf04fe430c3c0c4f6a45ebaea965b2c085/llvm/tools/objwriter/objwriter.cpp#L468-L472).
- PLT relocations are not necessary when referencing code within the same section, and they are not optimized away by the compiler. Quite possibly they are not optimized away by the linker either but I didn't check that yet.

**Comment by filipnavara** [comment]
> vs ~2 bytes on Windows

That's not entirely accurate.

COFF (object) relocation is 10 bytes. PE COFF (image) relocation is page-based, so that's 8 bytes for each page that has relocation and 2 bytes for each relocation within the page. The amortized cost of relocation basically depends on how close you have the pointers within the data structure. The closer they are the bigger chance that they fit within the page and have the 2-byte cost in the final executable.

`.rel` ELF relocation is 8/16 bytes (32-bit/64-bit). `.rela` ELF relocation is 12/24 bytes (32-bit/64-bit). They use the same format for object files and image files.

For completeness, Mach-O also compresses the relocations in the final image file. The format is more complex though.

**Comment by MichalStrehovsky** [comment]
This was fixed in the above mentioned pull requests.
