### ISSUE TITLE
[wasm] [question] JSInterop usage with javascript 'buf' data type

### ISSUE THREAD

**Issue by Jack-Edwards** [dotnet/runtime#76672]
I am attempting to use JSInterop in a Blazor WASM project to interact with [libsodium.js](https://github.com/jedisct1/libsodium.js).  libsodium.js makes frequent use of a `buf` data type, both as arguments and as returned data.

I'm seeing some differences between IJSInProcessRuntime.Invoke() and IJSRuntime.InvokeAsync() when it comes to this `buf` data type.  The in-process runtime seems to work great; I can receive and provide `byte[]` wherever JS returns or requires an instance of `buf`.  However, I'm experiencing serialization problems whenever I try to call the same JS functions with the same data using the "normal" runtime.

Is this type of behavior anticipated?  I surely don't need this functionality with Blazor Server, so this is fine for my use case.

Example repo: https://github.com/Jack-Edwards/BlazorSodium

Code:

```
public static async Task<byte[]> HashStringAsync(IJSInProcessRuntime inProcessRuntime, IJSRuntime standardRuntime, string password, int opsLimit = OPSLIMIT_INTERACTIVE, int memoryLimit = MEMLIMIT_INTERACTIVE)
{
   uint saltLength = 16;
   Console.WriteLine("getting random bytes");

   // I don't know what type 'buf' is ahead of time.
   // ref: https://github.com/jedisct1/libsodium.js/blob/master/wrapper/symbols/randombytes_buf.json
   object randomBytesAsObject = inProcessRuntime.Invoke<object>("window._sodium.randombytes_buf", new object[] { saltLength });
   Console.WriteLine($"Object type is: {randomBytesAsObject.GetType()}"); // System.Text.Json.JsonElement

   // Trying as JsonElement
   JsonElement randomBytesAsJsonElement = inProcessRuntime.Invoke<JsonElement>("window._sodium.randombytes_buf", new object[] { saltLength });
   Console.WriteLine($"Object raw text is: {randomBytesAsJsonElement.GetRawText()}"); // {"__byte[]":0}

   // Trying as byte[]
   // It works!
   byte[] randomBytesAsBytes = inProcessRuntime.Invoke<byte[]>("window._sodium.randombytes_buf", new object[] { saltLength });
   Console.WriteLine($"Object length is: {randomBytesAsBytes?.Length}");
   foreach (var item in randomBytesAsBytes)
   {
      Console.WriteLine(item.ToString());
   }

   // The commented code below produces the following exception: System.Text.Json.JsonException: JSON serialization is attempting to deserialize an unexpected byte array.
   //byte[] randomBytesAsAsyncBytes = await standardRuntime.InvokeAsync<byte[]>("window._sodium.randombytes_buf", new object[] { saltLength });

   Console.WriteLine("hashing password");
   int argonAlt = 1; // or 2
   byte[] randomSalt = new byte[] { 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, };

   // ref: https://github.com/jedisct1/libsodium.js/blob/master/wrapper/symbols/crypto_pwhash.json
   byte[] passwordHash = inProcessRuntime.Invoke<byte[]>("window._sodium.crypto_pwhash", new object[] { 32, password, randomSalt, opsLimit, memoryLimit, 1 });
   Console.WriteLine(Convert.ToBase64String(passwordHash)); // yO4j8RrepwXrnfUsZvtWAKYWouYjx/AEERpUJ48xnhk=

   return passwordHash;
}
```

**Comment by pavelsavara** [comment]
`IJSRuntime.InvokeAsync()` is for good remote calls with server. In which case you probably could use server side crypto. In any case, your data is serialized to JSON for the transfer and would not be very efficient.

The `IJSInProcessRuntime` is client side Blazor, and here is the documentation. 
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0
If you find **issues** in any of them, please report it to `aspnetcore` repo or to the documentation.

Note that for client side only, there is also new interop in .NET 7, which is in my opinion better fit for your use-case.
https://devblogs.microsoft.com/dotnet/use-net-7-from-any-javascript-app-in-net-7/

Possibly together with browser native https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto it would be better than libsodium.

For general discussion, I recommend https://aka.ms/dotnet-discord channel `#blazor` rather than opening github issues.
