### ISSUE TITLE
Buffer for enumerator

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#76675]
I suggest adding to linq the ToBuffer extension method (you can have a second name), which will buffer the enumerator into the collection. Well, so that the buffer is returned only if the enumerator is iterated to the end.

The code will not work in multithreading, you can throw an error if two threads call GetEnumerator

An example of how it can be implemented (you can come up with your own version), the reflection can be taken away
https://github.com/Mr0N/Cache/blob/master/Buffer_/Iterator.cs
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace BufferEnumerable
{
   public class Iterator<T>:IEnumerable<T>
    {
        ListNode<T> buffer;
        public IEnumerator<T> GetEnumerator()
        {
            if(this.enumerable?.GetType() == this.buffer?.GetType())
            {
                return enumerable.GetEnumerator();
            }
            return Get();
        }
        private IEnumerator<T> Get()
        {
            bool check = false;
            var enumerator = this.enumerable.GetEnumerator();
            try
            {
                while (check = enumerator.MoveNext())
                {
                    var temp = enumerator.Current;
                    buffer.Add(temp);
                    yield return temp;
                }
            }
            finally
            {
                ((IDisposable)enumerator).Dispose();
                if (check==false)
                {
                    this.enumerable = this.buffer;
                }
                else
                {
                    this.buffer = new ListNode<T>();
                }
            }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
           return this.GetEnumerator();
        }

        IEnumerable<T> enumerable;
        public Iterator(IEnumerable<T> enumerable)
        {
            this.enumerable = enumerable;
            this.buffer = new ListNode<T>();
        }
    }
}
```
examples of use
```
public void Get(IEnumerable<string> enumerable){
foreach(var element in enumerable){
}
}
var obj = GetLazyEnumerator().ToBuffer();
Get(obj);
Get(obj);
Get(obj);
Get(obj);
Get(obj);
Get(obj);
```

**Comment by Clockwork-Muse** [comment]
What is the benefit of this over current methods like `ToList()`?  That explicitly captures the results, works with multithreading better than the hidden capture, and is better understood.

**Comment by Mr0N** [comment]
> What is the benefit of this over current methods like `ToList()`? That explicitly captures the results, works with multithreading better than the hidden capture, and is better understood.

Because these are different methods.

**Comment by Clockwork-Muse** [comment]
> Because these are different methods.With different work logic.

"Different implementations" is somewhat irrelevant.  This doesn't appear to provide markedly different _results_ than calling `ToList()`.  Why would I, as a user, want to call this instead of getting a list?  This method doesn't appear to enable any new behavior, or speed up any existing behavior.

Note that this method is suspect because it seems to want to be a running cache.  The problem with this is `IEnumerable` is supposed to be used as "enumerate once", and if you want to access the results multiple times you're supposed to capture into a known collection type.  So this method is playing against that, for no readily apparent reason.

**Comment by Mr0N** [comment]
> > Because these are different methods.With different work logic.
> 
> "Different implementations" is somewhat irrelevant. This doesn't appear to provide markedly different _results_ than calling `ToList()`. Why would I, as a user, want to call this instead of getting a list? This method doesn't appear to enable any new behavior, or speed up any existing behavior.
> 
> Note that this method is suspect because it seems to want to be a running cache. The problem with this is `IEnumerable` is supposed to be used as "enumerate once", and if you want to access the results multiple times you're supposed to capture into a known collection type. So this method is playing against that, for no readily apparent reason.

This method is lazy at the first call, at the second it is list, then ToList, enumerable is no longer lazy.

**Comment by Mr0N** [comment]
> > This method is lazy at the first call, at the second it is list, then ToList, enumerable is no longer lazy.
> 
> That's not really a benefit. Or rather, that doesn't provide any benefit. Presumably any time you use this you enumerate to the end, so you incur the same memory use and allocations as calling `ToList()`. So even if it is "lazy", that doesn't make a significant difference.

But there is a difference when memory allocation is made, and IEnumerable may not be used at all and it will occupy memory

**Comment by Mr0N** [comment]
in theory, the program can work for 12 hours, and IEnumerable is needed at the end of the program, that is, it will take up 12 hours of memory, with ToBuffer there will be no such problem

**Comment by eiriktsarpalis** [comment]
> The code will not work in multithreading

Apart from applications for this proposal being questionable, this very clearly violates the contract for IEnumerable. IEnumerable instances typically follow a call-by-name evaluation strategy (i.e. enumeration is repeated on each enumerator instantiation) rather than a lazy or call-by-need evaluation strategy and are thus mostly thread-safe by construction.

**Comment by Mr0N** [comment]
> 

Something in F#, there is a cache for IEnumerable, and everything works fine (almost)
List<int> also does not work in multithreading, and this is just a code example, you can write your own multithreading

**Comment by Mr0N** [comment]
> > The code will not work in multithreading
> 
> Apart from applications for this proposal being questionable, this very clearly violates the contract for IEnumerable. IEnumerable instances typically follow a call-by-name evaluation strategy (i.e. enumeration is repeated on each enumerator instantiation) rather than a lazy or call-by-need evaluation strategy and are thus mostly thread-safe by construction.


Something in F#, there is a cache for IEnumerable, and everything works fine (almost)
List also does not work in multithreading, and this is just a code example, you can write your own multithreading

**Comment by Mr0N** [comment]
https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#cache

**Comment by Mr0N** [comment]
> > The code will not work in multithreading
> 
> Apart from applications for this proposal being questionable, this very clearly violates the contract for IEnumerable. IEnumerable instances typically follow a call-by-name evaluation strategy (i.e. enumeration is repeated on each enumerator instantiation) rather than a lazy or call-by-need evaluation strategy and are thus mostly thread-safe by construction.

Does F# violate any contracts?

**Comment by eiriktsarpalis** [comment]
> Something in F#, there is a cache for IEnumerable, and everything works fine (almost)

You mean `Seq.cache`? FWIW that method uses locking in order to guarantee thread safety:

https://github.com/dotnet/fsharp/blob/main/src/FSharp.Core/seq.fs#L1176-L1185

Which arguably defeats any benefits that the method might provide. 

> Does F# violate any contracts?

So per the above, no. But at the expense of needing to use locking.

**Comment by Clockwork-Muse** [comment]
> in theory, the program can work for 12 hours, and IEnumerable is needed at the end of the program, that is, it will take up 12 hours of memory, with ToBuffer there will be no such problem

This is grossly false.

If you have 12 hours of calling an `IEnumerable`, the buffer call will still retain 12 hours worth of memory.  If you're trying to have streaming-only memory you need alternate strategies.

**Comment by Mr0N** [comment]
> 

Is Lock so evil?

**Comment by Mr0N** [comment]
> > Something in F#, there is a cache for IEnumerable, and everything works fine (almost)
> 
> You mean `Seq.cache`? FWIW that method uses locking in order to guarantee thread safety:
> 
> https://github.com/dotnet/fsharp/blob/e389d7744b7ddf81fd62cf01ce870cf92f6dcabd/src/FSharp.Core/seq.fs#L1176-L1185
> 
> Which arguably defeats any benefits that the method might provide.
> 
> > Does F# violate any contracts?
> 
> So per the above, no. But at the expense of needing to use locking.


Is Lock so evil?

**Comment by Mr0N** [comment]
> > Something in F#, there is a cache for IEnumerable, and everything works fine (almost)
> 
> You mean `Seq.cache`? FWIW that method uses locking in order to guarantee thread safety:
> 
> https://github.com/dotnet/fsharp/blob/e389d7744b7ddf81fd62cf01ce870cf92f6dcabd/src/FSharp.Core/seq.fs#L1176-L1185
> 
> Which arguably defeats any benefits that the method might provide.
> 
> > Does F# violate any contracts?
> 
> So per the above, no. But at the expense of needing to use locking.

Well, it is not necessary to block the stream, but you can simply throw an error if a second stream enters the stream, if the first stream is in it

**Comment by Mr0N** [comment]
It seems to me that something like this can be written relatively quickly

**Comment by Clockwork-Muse** [comment]
You still haven't provided an answer as to where or why this would be preferable to any of the existing methods.

Implementation is rarely interesting at this stage, the larger and more important question now is "why should we?".

**Comment by Mr0N** [comment]
> You still haven't provided an answer as to where or why this would be preferable to any of the existing methods.
> 
> Implementation is rarely interesting at this stage, the larger and more important question now is "why should we?".
Well, for example
```
using System;
using System.Linq;


var random = new Random();
var result = Enumerable.Range(0,1000)
    .Select(a=>random.Next())
    .ToList();

foreach(var obj in result){
    Console.WriteLine(obj);
}


```
```
using System;
using System.Linq;


var random = new Random();
var result = Enumerable.Range(0,1000)
    .Select(a=>random.Next())
    .ToBuffer();

foreach(var obj in result){
    Console.WriteLine(obj);
}


```

**Comment by Mr0N** [comment]
Is there a difference in memory allocation in these two codes at the stage of creating Enumerable?

**Comment by Mr0N** [comment]
And if you imagine that this foreach is in some other method.
I also suggest returning the result to the IBuffer interface

```
interface IBuffer<T>:IEnumerable<T>{}
public static IEnumerable<T> ToBuffer<T>(){
return ToBufferRet<T>()
}
static IBuffer<T> ToBufferRet<T>(IEnumerable<T> ls){}
```




}

**Comment by Clockwork-Muse** [comment]
> Is there a difference in memory allocation in these two codes at the stage of creating Enumerable?

While it's true that the `ToList()` version will fully realize the list, and hence consume more memory at `var result`, the problem is that people aren't going to capture the list unless they intend to use it more than once.  When the `foreach` completes, `ToList()` and `ToBuffer()` will have consumed roughly equal amounts of memory (although due to certain internal optimizations `ToList()` is likely able to pre-size the list and consume less memory than `ToBuffer()` in this trivial case, but this isn't necessarily relevant in real-world scenarios).  Note that the realization

And that's the problem.  Programmers shouldn't realize the enumerable if they only use `foreach` to iterate through once, and thus wouldn't have a need for `ToBuffer()`.  If they do need to re-use for some reason, `ToBuffer()` doesn't offer any advantages over the existing ways to capture the result.

> And if you imagine that this foreach is in some other method.

So what?
In most cases the method will be taking `IEnumerable<T>`, which `List<T>` also implements.  From a consumer perspective there are two cases:
 1. You call one such method, and don't re-use the enumerable otherwise: just pass the unrealized `IEnumerable<T>` (ie, just `Enumerable.Repeat(0, 1000).Select(_ => random.Next())`.
 2. You call two or more such methods, or otherwise re-use the enumerable: realize the enumerable ahead of time as appropriate and pass the result to each method (ie, `ToList()`).

> I also suggest returning the result to the IBuffer interface

If you're concerned about this other method re-using the enumerable, or otherwise capturing it, `ToBuffer()` isn't going to provide an optimization.  

 1. If the method _doesn't_ actually re-use the enumerable, it's not needed.
 2. If the method is best implemented by re-using the enumerable, and you want to telegraph that to the caller (to force them to realize it themselves), the parameter should likely be changed to `IReadOnlyCollection<T>`.
 3.  If the method needs to capture the collection for other reasons (any time the collection will be used after the end of the method, especially in multithreading scenarios), an extra copy will be created regardless.

... your proposal would best fit where the method is best implemented by collection-re-use, but you don't want to telegraph that to the user (ie, the parameter is still `IEnumerable<T>`).  The problem is that the best thing for the method to do is to check whether the actual value passed implements `IReadOnlyCollection<T>`/`ICollection<T>` (which are implemented by the built-in collections) and not realize the passed value if that is the case, since this would allow the caller to capture the collection if they plan on re-using it.

**Comment by Mr0N** [comment]
```
using System;
using System.Linq;


var random = new Random();
var result = Enumerable.Range(0,1000)
    .Select(a=>random.Next())
    .ToList();

foreach(var obj in result){
    Console.WriteLine(obj);
}
foreach(var obj in result){
    Console.WriteLine(obj);
}
```
```
using System;
using System.Linq;


var random = new Random();
var result = Enumerable.Range(0,1000)
    .Select(a=>random.Next())
    .ToBuffer();

foreach(var obj in result){
    Console.WriteLine(obj);
}
foreach(var obj in result){
    Console.WriteLine(obj);
}

```
With ToBuffer, two cycles are performed, with ToList three cycles

**Comment by Mr0N** [comment]
That is, minus one loop, which is executed in ToList

**Comment by Clockwork-Muse** [comment]
> With ToBuffer, two cycles are performed, with ToList three cycles

This is true.
Do you have any evidence that represents any significant savings, especially for realistic development patterns?  Especially when you consider the context switching.
Keep in mind that in most cases where enumerables are captured, the resulting collection is going to be modified, or used _far_ more than twice, which means that the "extra" enumeration in `ToList()` ends up being amortized.

**Comment by Mr0N** [comment]
> 

I tested earlier, I don’t remember where the tests were, then ToBuffer is twice as fast as ToList, if you do two cycles

**Comment by Mr0N** [comment]
> > With ToBuffer, two cycles are performed, with ToList three cycles
> 
> This is true. Do you have any evidence that represents any significant savings, especially for realistic development patterns? Especially when you consider the context switching. Keep in mind that in most cases where enumerables are captured, the resulting collection is going to be modified, or used _far_ more than twice, which means that the "extra" enumeration in `ToList()` ends up being amortized.

I tested earlier, I don’t remember where the tests were, then ToBuffer is twice as fast as ToList, if you do two cycles

**Comment by Clockwork-Muse** [comment]
> I tested earlier, I don’t remember where the tests were, then ToBuffer is twice as fast as ToList, if you do two cycles

... they're not relevant unless you present them here.

**Comment by theodorzoulias** [comment]
@Mr0N if I am not wrong the suggested `ToBuffer` operator is functionally identical with the [`Memoize`](https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Interactive/System/Linq/Operators/Memoize.cs) operator from the [System.Interactive](https://www.nuget.org/packages/System.Interactive/) package (owned by the dotnetfoundation). My understanding is that this functionality is kind of specialized, so it makes sense to be available from a dedicated package. Most people will never have a need for it, and it would just pollute their IntelliSense dropdown, which is already crowded.

**Comment by Mr0N** [comment]
> @Mr0N if I am not wrong the suggested `ToBuffer` operator is functionally identical with the [`Memoize`](https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Interactive/System/Linq/Operators/Memoize.cs) operator from the [System.Interactive](https://www.nuget.org/packages/System.Interactive/) package (owned by the dotnetfoundation). My understanding is that this functionality is kind of specialized, so it makes sense to be available from a dedicated package. Most people will never have a need for it, and it would just pollute their IntelliSense dropdown, which is already crowded.

Probably yes

**Comment by mikernet** [comment]
@Clockwork-Muse
> Programmers shouldn't realize the enumerable if they only use foreach to iterate through once, and thus wouldn't have a need for ToBuffer(). If they do need to re-use for some reason, ToBuffer() doesn't offer any advantages over the existing ways to capture the result.

For what it's worth, I have definitely run into at least one situation where this would be useful, where I don't know ahead of time whether an enumerable will be enumerated over partially, fully, or how many times until later and the source of the enumerable is something like a file stream so locking overhead wouldn't matter and not fully realizing the enumerable for the cases where it is only partially enumerated is a big win. That said, that is a rather rare and esoteric situation.
