### ISSUE TITLE
Implementation of a `static` `virtual` method in base type is getting ignored by runtime in context of derived type

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/runtime#76673]
### Reproduction Steps

Compile, run and observe output from:
```
interface I1
{
    static virtual void M1() { System.Console.WriteLine("I1.M1"); }
    static abstract int M2();
}

class Test1 : Test2, I1
{
    static public int M1() { return 0; }
    static public ref int M2() { throw null; }

    static void Main()
    {
        System.Console.WriteLine("Testing Test2");
        Test<Test2>();
        System.Console.WriteLine("Testing Test1");
        Test<Test1>();
    }

    static void Test<T>() where T : I1
    {
        T.M1();
        System.Console.WriteLine(T.M2());
    }

}

class Test2 : I1
{
    static void I1.M1()
    {
        System.Console.WriteLine("Test2.M1");
    }
    static int I1.M2() => 2;
}
``` 

### Expected behavior

```
Testing Test2
Test2.M1
2
Testing Test1
Test2.M1
2
```

### Actual behavior

```
Testing Test2
Test2.M1
2
Testing Test1
I1.M1
2
````

**Comment by AlekseyTs** [comment]
@davidwrighton, @trylek FYI

**Comment by trylek** [comment]
@davidwrighton, @AlekseyTs - I think I already understand what is happening here. When we're trying to resolve the virtual static method in the base type descent,

https://github.com/dotnet/runtime/blob/d462be072d71d98534da318d3418465f788ecea1/src/coreclr/vm/methodtable.cpp#L8164

after unsuccessful resolution attempt we call the routine for default interface implementation; so that when we don't resolve the SVM on <code>Test1</code>, instead of descending into the base class <code>Test2</code> we call the default interface implementation resolution which finds the implementation on I1. I believe that we should first walk the entire base class tree and only then attempt default interface implementation resolution. It also seems to me that we shouldn't need to call the default interface implementation resolution multiple times for the base classes, the method should walk the entire ordered graph of implemented interfaces. I'm working on the fix now.

**Comment by AlekseyTs** [comment]
I am curious why behavior for abstract methods is different?

**Comment by trylek** [comment]
I have also double-checked the ECMA 335 addenda to see whether we need to change the wording in accordance with the proposed fix and I believe it's not needed. In the section on default interface methods, I believe that the paragraph

**[The general gist of the implementation is that default interface methods (either the slot defining method, or a MethodImpl for the interface method on another interface type) is always used as a fallback - only if the "old rules" didn't find an implementation, we apply the new rules and try to find an implementation on one of the interfaces.]**

clearly states that default interface lookup should only be applied after the *old rules didn't find an implementation* where *old rules* involve resolution of virtual methods on classes; in this sense the base class descent in <code>ResolveVirtualStaticMethod</code> represents the *old rules* and only after it doesn't yield a match we should apply the *new rules* by calling the default interface implementation resolution.

**Comment by trylek** [comment]
Fixed in https://github.com/dotnet/runtime/pull/76724, closing.
