### ISSUE TITLE
outerloop legs failing to detect `dotnet`

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76755]
Original issue was opened in dotnet/arcade: https://github.com/dotnet/arcade/issues/11185

Many outerloop legs fail with this message when attempting to run unit tests:

```
./RunTests.sh: line 168: /tmp/helix/working/A6B808E3/p/dotnet: No such file or directory
```

The investigation found that this may have been caused by a runtime change that happened between these two runs (from 8/2 to 8/3):

pr/public/dotnet/runtime/refs/pull/73300/merge
pr/public/dotnet/runtime/refs/pull/73020/merge

<details>
<summary>Kusto Query</summary>

```kusto
Jobs
| where QueueName == "osx.1200.amd64.open"
| extend Propz = parse_json(Properties)
| where Propz["DefinitionName"] == "runtime-libraries-coreclr outerloop"
| where Propz["System.PhaseName"] == "libraries_build_OSX_x64_Debug"
| order by Finished desc 
```
</details>

The main suspect PR is one that seeked to remove the host packages conditionally and was merged at a time between the above two PRs likely merge commits: https://github.com/dotnet/runtime/pull/73095/files

We need to confirm this issue caused the regression and get it fixed.

**Comment by elinor-fung** [comment]
https://github.com/dotnet/runtime/pull/73095 made it so that the `host.native` subset needs to be built for the libraries `testhost` to be complete. It was added to the default `clr`/`mono` subsets, but it looks like the build isn't relying on those.

This is the portion of the change that handled it in PR/innerloop test runs: https://github.com/dotnet/runtime/blob/cb6e5e7ff92871b9209e61815ae3d01081b05214/eng/pipelines/libraries/run-test-job.yml#L91-L93

It seems outerloop doesn't go through that. My guess would be that `host.native` is not being built, so host components (like `dotnet`) are missing from testhost. Whichever part of the outerloop pipeline is building `libs.pretest` probably needs to include `host.native` first.

**Comment by danmoseley** [comment]
fwiw the badssl homepage says "badssl.com is meant for _manual_ testing of security UI in web clients."

**Comment by antonfirsov** [comment]
Because of this, outerloop is completely unreliable unreliable now, note that only about 12% of the cases are passing. This is very unfortunate eg. for the networking libs, where a significant portion of the tests live in outerloop.
