### ISSUE TITLE
[wasm][debugger] RootHidden is not working correctly in DebuggerTypeProxy

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#76876]
```
var list = new List<string>();
var a = "test";
list.Add(a);
```
On wasm:
![image](https://user-images.githubusercontent.com/4503299/195104763-4367ff88-506f-4b34-85d0-ea1f98e0cfda.png)
In a console app:
![image](https://user-images.githubusercontent.com/4503299/195105086-b12fdc25-4d9b-4409-bf88-6cb2546ff609.png)

`Items` is `DebuggerRootHidden`, so I think it should not show.
https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/ICollectionDebugView.cs#L19

When fixed, remove `else` block from:
https://github.com/dotnet/runtime/blob/8064bfe0c2b1b90f9922767a4475685722eaeb78/src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs#L149-L161

**Comment by ilonatommy** [comment]
It's caused by two implementations of `TypeInfo` constructor that populate an instance with complete or incomplete data based on which one we use. This leads to a situation where we draw conclusion about a type having incomplete information about it in some places.

**Comment by ilonatommy** [comment]
We don't have access to external code's `DebuggerHidden`, probably because of trimming.
In the case with a list you suggested:
```
{
  "type": "object",
  "value": null,
  "description": "Count = 1",
  "className": "System.Collections.Generic.List<string>",
  "objectId": "dotnet:object:2"
}
```
after calling `getProperties` we are getting an info about the list's type correctly: `System.Collections.Generic.ICollectionDebugView<string>`. We have access to its properties, we can see it has a member `Items`. For `Items` we are getting only one element in `CustomAttributeHandleCollection` and it's of `MethodDefinition` kind. It belongs to the default constructor `.ctor`.

**Comment by thaystg** [comment]
This is fixed by the new debugger.
