### ISSUE TITLE
Support wasm variants in NuGet packages

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#76959]
We need some way for NuGet package authors to provide single threaded and multi-threaded versions of native assets.

Additionally, library authors should be able to identify whether they are in a single- or multi-threaded app.
(For example consider making `System.Threading.Thread.IsThreadStartSupported` a public property (and also linker-friendly))

**Comment by lambdageek** [comment]
@lewing @richlander This probably needs to be part of a broader discussion than just the runtime

**Comment by lewing** [comment]
yes

cc @jeromelaban

**Comment by jeromelaban** [comment]
Thanks Larry! Indeed, this is needed. For native assets, [here's what we've been using with Uno](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/main/doc/features-module-linking.md#static-linking-multi-version-support) to address that problem (along with the emscripten version number, for backward compatibility). For a moment, Wasm exceptions support was considered a variant, but since it is supported by all major browsers, that leaves simd and threading for now.

As for capabilities detection, it's for now available as part of [an environment variable for threading](https://github.com/unoplatform/uno/blob/7f6120d550005ae386df6da90496eed89b44937c/src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs#L14), yet it's a quite weak API at this point.

This issue should also be linked to another issue about startup time features detection. This is to include multiple builds of the same payload with different variants, based on browser capabilities, considering there's no current way (as far as I can see) to make fined-grained feature switching at IL level, or runtime level.
