### ISSUE TITLE
[API Proposal]: Add PipeOptions.FirstPipeInstance enum value

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#76984]
### Background and motivation

It's not possible for an app hosting multiple named pipe connections to verify that no one else is using the pipe name when it starts.

For example, Kestrel is looking at adding a named pipe transport, and when we start Kestrel we want to verify that no one else is using the configured pipe name:

* We don't want to share the pipe between Kestrel instances. It's common for devs to accidentally launch Kestrel when it's already running. A socket errors if you bind to it when it's already open. We want the same protection with a named pipe.
* A pipe gets many of its settings when it is first opened. Want to verify that Kestrel's settings are applied to the pipe.

Named pipes have a built-in option for checking this - FILE_FLAG_FIRST_PIPE_INSTANCE. See https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createnamedpipea

.NET doesn't expose this option. While it is automatically set if the max number of pipe instances is 1, there is no way to explicitly set this option.

https://github.com/dotnet/runtime/blob/c59b5171e4fb2b000108bec965f8ce443cb95a12/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Windows.cs#L121-L124.

If the `PipeOptions.FirstPipeInstance` options was available, then Kestrel would create the first `NamedPipeServerStream` with it the option to verify that there is no existing pipe with that name and create subsequent `NamedPipeServerStream` instances without the option.

Note that validation on the `NamedPipeServerStream` ctor _currently prevents_ the enum value having FILE_FLAG_FIRST_PIPE_INSTANCE value added to it. e.g.

```cs
// NamedPipeServerStream errors when passed this pipe option
pipeOptions |= (PipeOptions)0x00080000;
```

### API Proposal

```csharp
namespace System.IO.Pipes
{
    [Flags]
    public enum PipeOptions
    {
        FirstPipeInstance = unchecked((int)0x00080000)
    }
}
```

### API Usage

```csharp
private NamedPipeServerStream CreateServerStream(bool firstStream)
{
    var pipeOptions = PipeOptions.Asynchronous | PipeOptions.WriteThrough;
    if (_options.CurrentUserOnly)
    {
        pipeOptions |= PipeOptions.CurrentUserOnly;
    }
    if (firstStream)
    {
        pipeOptions |= PipeOptions.FirstPipeInstance;
    }

    return new NamedPipeServerStream(
        _endpoint.PipeName,
        PipeDirection.InOut,
        NamedPipeServerStream.MaxAllowedServerInstances,
        PipeTransmissionMode.Byte,
        pipeOptions,
        inBufferSize: 0,
        outBufferSize: 0);
}
```

### Alternative Designs

```cs
[Flags]
public enum PipeOptions
{
    EnsureFirstPipeInstance = unchecked((int)0x00080000)
}
```
It still alludes at the name of the Windows API flag and conveys "throw if already exists".

**Comment by Jozkee** [comment]
Thanks for the proposal, it looks to me like a good case to expose the option. 

> Note that validation on the NamedPipeServerStream ctor currently prevents the enum value having

I also thought of just excluding FILE_FLAG_FIRST_PIPE_INSTANCE from said validation, but the history shows that it is in place since *Pipe* code was ported over to core.

Regarding the proposed name, I'm not sure if `FirstPipeInstance` is the best name, since it doesn't quite convey that it will throw if the pipe already exists. 

As an alternative proposal I suggest `EnsureFirstPipeInstance`, it still alludes at the Windows flag and conveys "error if already exists".

**Comment by JamesNK** [comment]
I went with `FirstPipeInstance` because it lines up with the windows API flag. I agree that something like `EnsureFirstPipeInstance` is more descriptive.

**Comment by terrajobst** [comment]
* The proposal looks reasonable, but given the angle is security, we can't just no-op this in the non-Windows implementation. Is there a reasonable cross-platform implementation or do we need to consider this a Windows-only feature?
    - If it's Windows-only we should mark the enum member as `[SupportedOSPlatform("windows")]`

```C#
namespace System.IO.Pipes
{
    [Flags]
    public enum PipeOptions
    {
        FirstPipeInstance = unchecked((int)0x00080000)
    }
}
```

**Comment by JamesNK** [comment]
Named pipes support in Kestrel is limited to Windows only. Ideally, `PipeOptions.FirstPipeInstance` would be cross-platform, but if isn't possible on Linux/macOS then limiting it to Windows is fine with me.

**Comment by Tarun047** [comment]
Hi People, I'd like to take this up and contribute a PR.

**Comment by Tarun047** [comment]
I've created a commit in [my fork](https://github.com/dotnet/runtime/compare/main...Tarun047:runtime:76984-Add-PipeOptions-FirstPipeInstance)

I wanted to make sure these are the changes that we should be doing before creating a PR and I don't want to create a
PR that fails during build.

When I build my local repository with the following command
`./build.sh -c Release -subset clr+libs+libs.tests`

However it's throwing a build error which says the call site is reachable on Unix but the parameter PipeOptions.FirstPipeInstance itself is supported only on Windows.
<img width="1003" alt="Screenshot 2023-03-25 at 12 07 52 PM" src="https://user-images.githubusercontent.com/32017154/227701459-16d1d51c-9d37-4962-8957-858763ab3026.png">


But I don't see why this is a problem, because even `PipeTransmissionMode.Message` is also annotated as only supported by Windows, but that doesn't throw any build error.

I would really appreciate any help in this regard and let me know if I'm missing something here.

**Comment by Jozkee** [comment]
@Tarun047 that seems to me like a bug in CA1416 analyzer. I just filed an issue for it https://github.com/dotnet/runtime/issues/84258.
