### ISSUE TITLE
System.Text.Json  have bug on .net461

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#76995]
### Description

```C#

> #reset 64
正在重置执行引擎。
从“CSharpInteractive.rsp”加载上下文。
> #r "C:/Users/ABlue/.nuget/packages/system.text.encodings.web/6.0.0/lib/net461/System.Text.Encodings.Web.dll"
> #r "C:/Users/ABlue/.nuget/packages/system.text.json/6.0.0/lib/net461/System.Text.Json.dll"
> using System.Text.Json;
> JsonSerializer.Serialize(new { A = 2.1, B = 2.1f })
"{\"A\":2.1000000000000001,\"B\":2.0999999}"

```

### Reproduction Steps

add this package in  VS's  interctive window (C#)

### Expected behavior

2.1 =  "2.1"

### Actual behavior

2.1 = "2.1000000000000001"

**Comment by huoyaoyuan** [comment]
I should also be worth pointing out the FP precision and formatting changes in .NET Core 2.1 and 3.1.

**Comment by John0King** [comment]
@teo-tsirpanis   I knowt this can happen when you  caculate the floating number (+-*/) , but  can you show me a example that how can you  convert  `2.1f`    or  `2.1d`   into the string  `2.0999999`   and  `2.1000000000000001`,
I can't   because  `(2.1).ToString()`    always be `2.1`.
this serializer issue only accured in .net framework with  `System.Text.Json`   there are no problem in  `Newtonsoft.json`  and  .net core with `System.Text.Json`  !

**Comment by Clockwork-Muse** [comment]
```csharp
// Prints 2.1000000000000001
Console.WriteLine((2.1).ToString("G17"));
```
([proof](https://dotnetfiddle.net/IgQHOF))

More generally, due to the way singles/doubles are implemented, any number that isn't the result of dividing an integer by a power of two is not going to have an exact base-10 representation.  For instance:
```csharp 
// Prints 0.10000000000000001
Console.WriteLine((0.1).ToString("G17"));
```
(In base-10, `0.1` is the result of `1 / 10`.  Since `10 = 2 * 5` and is not a power of `2`, you're going to get some odd leftovers due to the base-2 math binary floating point uses)

Any rounding issues due to mathematical operations are minor compared to the fact that the numbers you **think** you're working with are rarely the 'exact' values you specified as constants or as input.

If the values you're specifying represent monetary amounts (and a few other cases), you should be using `decimal`, period.

**Comment by John0King** [comment]
@Clockwork-Muse  @teo-tsirpanis @huoyaoyuan 

this can not prove this issue: 
because :

```C#
#reset 64
正在重置执行引擎。
从“CSharpInteractive.rsp”加载上下文。
> (2.1).ToString("G17")
"2.1000000000000001"
> #reset core
正在重置执行引擎。
从“CSharpInteractive.rsp”加载上下文。
> (2.1).ToString("G17")
"2.1000000000000001"
> 
```

.net framework have the same output than  .net core

**Comment by saucecontrol** [comment]
The behavior is different because Newtonsoft.Json uses the [roundtrip formatting specifier](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#RFormatString) for double and float.  System.Text.Json does not use roundtrip formatting under .NET Framework because the Framework implementation of roundtrip formatting was buggy, as explained in the docs:

> In .NET Framework and in .NET Core versions earlier than 3.0, the "R" format specifier fails to successfully round-trip [Double](https://learn.microsoft.com/en-us/dotnet/api/system.double) values in some cases. For both [Double](https://learn.microsoft.com/en-us/dotnet/api/system.double) and [Single](https://learn.microsoft.com/en-us/dotnet/api/system.single) values, the "R" format specifier offers relatively poor performance. Instead, we recommend that you use the ["G17"](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#GFormatString) format specifier for [Double](https://learn.microsoft.com/en-us/dotnet/api/system.double) values and the ["G9"](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#GFormatString) format specifier to successfully round-trip [Single](https://learn.microsoft.com/en-us/dotnet/api/system.single) values.


This is also referenced in the comments for Utf8JsonWriter:

https://github.com/dotnet/runtime/blob/004d73283b037900f121137d75b9a891eb310e9e/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Double.cs#L103-L112

Which refers to:

https://github.com/dotnet/runtime/blob/004d73283b037900f121137d75b9a891eb310e9e/src/libraries/System.Text.Json/Common/JsonConstants.cs#L8-L10

So the behavior is to use `"R"` formatting for .NET \[Core\] and `"G17"` for .NET Framework.
