### ISSUE TITLE
Only canonical types show up in profilers for generics

### ISSUE THREAD

**Issue by tvass83** [dotnet/runtime#77007]
While profiling .NET code (this is version independent AFAIK), captured stacks seem to only include canonical types for generics (with some exceptions).
Like `List<System.__Canon>` instead of `List<string>`

I understand that canonical instantiation helps a lot with sharing common data for generics, but it's definitely not helpful when it comes to performance profiling applications.

Is there a way to opt-out this behavior or am I missing something straightforward here?

This can also be an issue while debugging (e.g. in Windbg using SOS debugger extension), although some tools seem to perform additional tweaks (like Visual Studio) to show proper stack frames.

Tools tested: Perfview, Windows Performance Toolkit, Visual Studio, Windbg

**Comment by tommcdon** [comment]
@davmason

**Comment by tvass83** [comment]
@Alois-xx Are you aware of any fixes/workarounds for this? Any hints would be greatly appreciated! :)

**Comment by davmason** [comment]
Hi @tvass83,

This is a byproduct of how the runtime handles generics. There is separate jitted code for every value type, but reference types share one jitted method body, which is referred to as the System.__Canon instantiation.

Because all reference types share the same jitted code, there is no way to determine which reference type was in the call unless you evaluate the parameters. The VS debugger can inspect locals and determine this when computing the callstack, but it would be too expensive to collect that information when profiling. Perfview, WPA, etc, just collect the IP address and don't collect information about parameter types so there is no way to differentiate in those traces.

**Comment by tvass83** [comment]
Thanks for the clarification @davmason.

Would it be possible to add a new [COMPLUS variable](https://github.com/dotnet/runtime/blob/243cf9f617a0bb99c1189de54c1bbd8d26cdba5a/src/coreclr/inc/clrconfigvalues.h) to control this default behavior of the JIT compiler, so that defining the variable ends up with no canonical instantiations?
This could be extremely useful even if we lost some performance while profiling.

@stephentoub Any thoughts on this?

**Comment by davmason** [comment]
It would be possible to add a configuration that does that, but it would be a fundamental change to how the runtime operates and would require a large amount of work for a comparatively small improvement. I doubt that it would make any team's list of work items due to how much work it would be.

**Comment by davmason** [comment]
Since this question is answered, closing this issue. If you have further questions please feel free to reopen or file a new issue.
