### ISSUE TITLE
Hidden version files in .NET runtime installation

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#77061]
### Description

.NET Core installations - runtime and sdk - include hidden version files.

```
$ find /usr/lib64/dotnet -iname '.*'
/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-rc.2.22476.2/.version
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.2.22472.3/.version
/usr/lib64/dotnet/sdk/7.0.100-rc.2.22511.1/.version
/usr/lib64/dotnet/sdk/7.0.100-rc.2.22511.1/.toolsetversion
```

Is there a good reason they have to be hidden files? What if we just renamed them to `version` instead of `.version`? Hidden files are often a surprise to users and some software can flag them as suspicious.

### Reproduction Steps

- Install .NET
- Run a find command to find hidden files: ` find $INSTALL_DIR -iname '.*'`

### Expected behavior

No hidden files

### Actual behavior

Users see some hidden files

### Regression?

No

### Known Workarounds

None

### Configuration

This has affected all versions of .NET (Core) as far back as .NET Core 2.1, at least. 7.0 RC2 is still affected

**Comment by ViktorHofer** [comment]
> /usr/lib64/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.2.22472.3/.version

Only this one applies to dotnet/runtime. All the other ones are produced by different repositories (aspnetcore, SDK, etc.). Maybe @ericstj remembers the reason for that design decision?

**Comment by ericstj** [comment]
Not something I was involved in.  I did a bit of digging and traced it back to CLI where found this: https://github.com/dotnet/cli/commit/e27ef0f18cecce262ddb8dcd20a3ae3fe64b33e5#diff-65f19ff0411f431016c58d5b37a853a45b7add7a0d4211cc3730e2322e58cb11R133 but that doesn't seem like the first place.  I wonder if @eerhardt can remember?

**Comment by eerhardt** [comment]
That change was just when it was ported from the C# build system to MSBuild.

It was originally introduced in https://github.com/dotnet/cli/commit/d5e9ac88cafedaa7d791bbaedba4f58e41d80478.

I'm not sure why it was named `.version` to start with. I don't believe it was intended to be hidden, especially since the development was done on Windows at the time.

If we make a breaking change here by renaming the file, we should take the opportunity to:

1. Ensure this file is necessary (I believe this information is embedded in the assemblies now, so it might not be needed - See the `Product Version` in the .dll)
2. If the file is necessary, we should ensure the format of the file is one that we want going forward. Adding new information to the file has been prohibited in the past since it could break someone trying to parse it.

**Comment by jkoritzinsky** [comment]
This file is still necessary. I tried to remove it in .NET 6 and we started getting some really weird failures without it. Apparently, VS uses it to identify correctly-installed TFMs.

https://github.com/dotnet/runtime/pull/47717

**Comment by ericstj** [comment]
> What if we just renamed them to version instead of .version? Hidden files are often a surprise to users and some software can flag them as suspicious.

So it seems a simple rename or removal will have consequences.  @omajid can you help weigh those against the benefit?  Do we have any evidence of this being a problem?

Just looking at my dev box I see some other products (on windows) using similarly named files: npm, android SDK, and Office all had files prefixed with `.`

**Comment by omajid** [comment]
>  Do we have any evidence of this being a problem?

No, not yet. [I have seen rkhunter flag things in the past](https://askubuntu.com/questions/1537/rkhunter-warning-about-etc-java-etc-udev-etc-initramfs). It seemed like a bad hygine issue that we could fix early, but if it has a non-trivial impact on the product, it's probably not worth fixing.
