### ISSUE TITLE
[API Proposal]: ICopyable<T>

### ISSUE THREAD

**Issue by ZP-ZPanda** [dotnet/runtime#77077]
### Background and motivation

To copy an object to another object (can not be of the same type)

There hasn't been a stable API to deep-clone objects (`object.MemberwiseClone()` exists for shallow clone) and the need to clone objects is pretty high ([This Stack Overflow question](https://stackoverflow.com/questions/78536/deep-cloning-objects)).

### API Proposal

```csharp
namespace System
{
    public interface ICopyable<TSelf, TFrom> where TSelf : ICopyable<TSelf, TFrom>
    {
        public static abstract TSelf Copy(TFrom t);
    }
}
```

### API Usage

```csharp

public class MyCopyable : ICopyable<MyCopyable, MyCopyable> { ... }
public class MyOtherCopyable : ICopyable<MyOtherCopyable, MyOtherCopyable>, ICopyable<MyOtherCopyable, MyOtherDerivedCopyable> {...}
public class MyOtherDerivedCopyable : ICopyable<MyOtherDerivedCopyable, MyOtherDerivedCopyable>, ICopyable<MyOtherDerivedCopyable, MyOtherCopyable> {...}

// Copy to another
MyCopyable mc1 = new MyCopyable();
MyCopyable mc2 = MyCopyable.Copy(mc1);

Console.WriteLine(mc1.Equals(mc2)); // true
Console.WriteLine(object.ReferenceEquals(mc1, mc2)); // false

// Copy to different type

MyOtherCopyable moc = new MyOtherCopyable();
MyOtherDerivedCopyable modc = MyOtherDerivedCopyable.Copy(moc);

// modc is an appropriate MyOtherDerivedCopyable representation of moc
```

### Alternative Designs

Making ICloneable generic.

```csharp
public interface ICloneable<T> where T : ICloneable<T>
{
    public T Clone();
}
```

### Risks

May wreak havoc on whoever creates a makeshift deep copy method called `Copy()`.

**Comment by huoyaoyuan** [comment]
It should be named as `Clone`. `Copy` is more about copying to existing object/storage.

**Comment by Clockwork-Muse** [comment]
... generally you create an interface to be used at an interface point (method parameter, return value, etc).  But in those cases, why wouldn't you just use the destination type outright?

You've shown it being used, but why would I use it in the first place?  Note that if I want to make my type convertible today, the recommendation would be to create conversion operators.

**Comment by vcsjones** [comment]
> Making ICloneable generic

This has been proposed a number of times. Previous discussions can be seen at https://github.com/dotnet/runtime/issues/49433 and https://github.com/dotnet/runtime/issues/37561.

Regarding the original proposal, this seems largely the same as a generic IClonable, so many of the concerns noted in those issues I think applies here as well.

**Comment by RenderMichael** [comment]
I think I finally found a good use case for `ICloneable<T>`: custom `with` operations.

If this picks up steam it would probably have to go through the LDM, but since this issue is here this is a good place to bring it up.

Here's what I the proposal would look like
``` csharp
public interface ICloneable<T> : ICloneable where T : ICloneable<T>
{
    object ICloneable.Clone() => Clone();
    new T Clone();
}
```

where a record type's generated `<Clone$>` method (I think I got that syntax right) would no longer be emitted and instead replaced with `ICloneable<T>.Clone()`.

An alternative design would be dropping the non-generic `ICloneable`, I was thinking it would be an easy way to "hook in" existing `ICloneable` implementations to the `with` functionality, much like the proposed IBitwiseEquatable https://github.com/dotnet/runtime/issues/75642. It would involve merely changing the interface and the return type of Clone() and `with` would work

**Comment by RenderMichael** [comment]
> I think I finally found a good use case for `ICloneable<T>`: custom `with` operations.

Just so there's motivation laid out: the primary use case for custom `with` implementations would be deep cloning. That's not an uncommon use case, and having first-class support for it (at least for records) would be nice.

**Comment by Clockwork-Muse** [comment]
> Just so there's motivation laid out: the primary use case for custom `with` implementations would be deep cloning. That's not an uncommon use case, and having first-class support for it (at least for records) would be nice.

Press `X` to doubt.
The larger use case for `record`s/`with` is probably more often immutable struct uses.  Where you don't need a deep clone at all.

That aside, `with` works by using a copy constructor on classes - which you can explicitly write (and thus make deep).

**Comment by Zhu-Panda** [comment]
> ... generally you create an interface to be used at an interface point (method parameter, return value, etc).  But in those cases, why wouldn't you just use the destination type outright?
> 
> You've shown it being used, but why would I use it in the first place?  Note that if I want to make my type convertible today, the recommendation would be to create conversion operators.

But properties may be references themselves and the conversion operators might just copy over the reference instead of doing a deep copy.

**Comment by Clockwork-Muse** [comment]
> But properties may be references themselves and the conversion operators might just copy over the reference instead of doing a deep copy.

That's not actually relevant to the point I'm making there, and potentially not at all.
 1. If the caller doesn't want a method to modify a parameter, it's the caller's responsibility to pass in a copy, not the the called method (and so the called method wouldn't take the interface, because the parameter would already be copied).
 2. If the called method wants a "safe" copy, it's generally due to a more specific concern.  The most common example of this is copying the contents of a collection into a new copy, when the copied collection is going to live longer than the method call.  In almost all cases it's not generalizable to all objects, and doesn't need to be.  If there's a wider specific framework requirement, generally that framework is going to be providing the copy/clone mechanisms.

So far, there hasn't been any demonstration of why a method would need to clone an object at all, much less one best served by the use of the interface.

**Comment by dakersnar** [comment]
As discussed in this issue and in the previous ones, this is not something we will be moving forward with. Closing as duplicate.
