### ISSUE TITLE
JSExport did not export top-level statements

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#77167]
I have create `dotnet new wasmbrowser` project and edit these files

```cs
// Program.cs
using System;
using System.Runtime.InteropServices.JavaScript;

Console.WriteLine(args);

[JSExport]
static string Greeting2()
{
	var text = $"Hello, World! Greetings from Greeting2";
	Console.WriteLine(text);
	return text;
}

public partial class MyClass
{
    [JSExport]
    static string Greeting()
    {
        var text = $"Hello, World! Greetings from {GetHRef()}";
        Console.WriteLine(text);
        return text;
    }

    [JSImport("window.location.href", "main.js")]
    internal static partial string GetHRef();
}
```

In the js file I could call `exports.MyClass.Greeting()` properly but then the `Greeting2` was not being exposed. I have expected that `JSExport` would export top level statement into direct property of the export and then I could just call `exports.Greeting2()` directly. Or at least expose it as default class name

Also I would like to propose that we should allow to change the name of export function. And so `JSExport` attribute should have string parameters for name of class and name of function we want to export

Such as

```cs
// Program.cs
using System;
using System.Runtime.InteropServices.JavaScript;

Console.WriteLine(args);

[JSExport] // exports.Greeting();
static string Greeting()
{
	var text = $"Hello, World! Greeting";
	Console.WriteLine(text);
	return text;
}

public partial class MyClass
{
    [JSExport] // exports.MyClass.Greeting();
    static string Greeting()
    {
        var text = $"Hello, World! Greetings from {GetHRef()}";
        Console.WriteLine(text);
        return text;
    }

    [JSImport("window.location.href", "main.js")]
    internal static partial string GetHRef();
}

public partial class MyAnotherLongNameClass
{
    [JSExport("MyClass","Greeting2")] // exports.MyClass.Greeting2();
    static string Greeting()
    {
        var text = $"Hello, World! Greeting2";
        Console.WriteLine(text);
        return text;
    }
}
```

And will throw build error on any same name and same class

**Comment by radical** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
As far as I could tell, there is no partial class into which we would be able to generate the code. 
The JSExport generator is not even called for this method.
_I guess 'Program' class in the IL is produced at some later phase of Roslyn compiler pipeline, but I don't know that for sure._

**Because there is easy workaround for this, I will close this issue as won't fix.**

For the proposal to custom name the export of the function, we considered that in the original proposal.
We have not included it because the current approach makes for better consistency and predictability on JS side.
Regarding compile time errors on name conflict, we could not really do that because we don't compile JSExport in some nuget library at the same time as your application code. So we don't have visibility.

**Comment by Thaina** [comment]
Thank you very much for your clarification
