### ISSUE TITLE
System.Drawing enumerations cause CA1416 errors when a project compiled against .NET 7 RC2

### ISSUE THREAD

**Issue by e1em3ntoDX** [dotnet/runtime#77248]
Hi,

We at DevExpress are now in the final stages of migrating our core libraries dependent on System.Drawing to SkiaSharp. These are libraries of multiple products such as DevExpress Reports, Office File API, which are cross-platform.

While we have implemented our cross-platform counterparts for most of the affected classes (e.g., Font, Pen, Brush, Bitmap), we see that an attempt to compile our sources against .NET 7 RC2 throws a lot of code analysis [CA1416 errors](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416). These errors are mostly related to enumerations from the System.Drawing.* namespace, the examples are: 

* [StringAlignment](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.stringalignment?view=dotnet-plat-ext-6.0)
* [GraphicsUnit](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphicsunit?view=dotnet-plat-ext-6.0)
* [DashStyle](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.drawing2d.dashstyle?view=dotnet-plat-ext-6.0)
* [StringFormatFlags](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.stringformatflags?view=dotnet-plat-ext-6.0)
* [LineCap](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.drawing2d.linecap?view=dotnet-plat-ext-6.0)
* so on...

Could you please confirm that this is intended and that this subset of the API is considered a Windows-only API? Will it stop operating on non-Windows systems soon?

The other question concerns the [PrintEventArgs](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.printing.printeventargs?view=dotnet-plat-ext-6.0) class. Our cross-platform source code contains multiple [PrintEventHandler](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.printing.printeventhandler?view=dotnet-plat-ext-6.0) subscriptions with the PrintEventArgs. Could you please confirm that this API call will also throw the PlatformNotSupported exception on non-Windows platforms? 

Thank you

**Comment by e1em3ntoDX** [comment]
@safern Perhaps, you or someone from your team can shed a light on this, so that my teams are able to make a future development decision?

**Comment by ericstj** [comment]
Right now these are all part of System.Drawing.Common.dll so they should be avoided since we've made that entire assembly Windows-only.

Do you have a need for these to be used on non-Windows?  If so, can you please explain your scenario for using these types?  We could consider moving types down to [System.Drawing.Primitives](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Drawing.Primitives/ref/System.Drawing.Primitives.cs), in a new version of .NET (eg: 8.0) if there is a strong case for a cross-platform scenario that does not require gdiplus.

**Comment by ericstj** [comment]
Technically speaking, using the enums in System.Drawing will not actually throw a `PlatformNotSupportedException` since they contain no code.  The reason for the warning here is that the entire `System.Drawing.Common` assembly is attributed with `
[assembly: SupportedOSPlatform("windows")]`.  Hypothetically the attribute could be applied differently such that it wasn't added at the assembly level and only added on API that would throw, though this would require changes to the not-supported-assembly infrastructure.

Can you say for certain that **all** the API you're exposing from `System.Drawing.Common` is of this form -- enums or constants with no code?  If any are not this form then it would mean you need a breaking change regardless, and it's probably best to batch that with breaking changes for enums.

I don't expect it makes a lot of sense in the long term for .NET to define a bunch of drawing exchange types like enums without having any actual use cases for those.  Even if we did, I don't expect we'd keep the shape they have today in System.Drawing.

**Comment by e1em3ntoDX** [comment]
>Can you say for certain that all the API you're exposing from System.Drawing.Common is of this form -- enums or constants with no code?

Yes, we implemented a common cross-platform abstraction layer, which calls the corresponding gdiplus/skia API depending on the current platform. And yes, this also affects the public API of our tools.

I see your point and thank you for your reply, Eric. You can close the issue.
