### ISSUE TITLE
System.IO.Ports.SerialPort make methods virtual to allow overrides

### ISSUE THREAD

**Issue by mattbaker-digital** [dotnet/runtime#77255]
It would be useful to be able to use the SerialPort class as a skeleton for new serial port classes such as one that supports FTDI direct features. At the moment I can't override any of the methods to add new functionality.

Or maybe a common SerialPort interface that can be used interchangeably.

**Comment by krwq** [comment]
cc: @raffaeler

**Comment by krwq** [comment]
You might want to open an issue in https://github.com/dotnet/iot/pull/1860 so that @raffaeler accounts for that in his design.

FWIW currently you can also use https://learn.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.basestream?view=dotnet-plat-ext-7.0 currently and write your own stream implementation for FTDI devices.

**Comment by raffaeler** [comment]
Thanks @kwrq.
Please @mattbaker-digital add your suggestion to the thread linked from @kwrq.
As you can read there I already logged the abstraction requirement which should allow adding application-level protocols.
The work is till in-progress but the initial part was the most difficult because I had to completely refactor the code from the SerialPort (where I started from).

**Comment by krwq** [comment]
Please let us know if using Stream works for you

**Comment by raffaeler** [comment]
> Please let us know if using Stream works for you

Stream is not always the best abstraction. If you have a protocol that is packet-oriented and variable in size (depending on the length written in a packet), the Stream makes the management quite hard.
Anyway, I am considering different options to leave space to user-implementation in the new class.

In any case I am eager to have feedback from the author of this issue to understand what use-cases he is facing.

**Comment by krwq** [comment]
Let me clarify: we don't currently have plans to make those methods virtual in System.IO.Ports. In many cases Stream (BaseStream) can be used as an abstraction. Implementation @raffaeler you're working on may incorporate this issue in design if it makes sense.

I'll close this issue though since currently we don't plan on doing this change here. We can reconsider this if there is enough interest. Please respond to this issue or open new one if you strongly feel we should do this.
