### ISSUE TITLE
Consider consolidating logic of JSON Snake/Kebab naming with Camel

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#77262]
In https://github.com/dotnet/runtime/pull/69613 we've added Snake/Kebab casing but it uses slightly different word splitting logic. We should decide which we prefer and consider consolidating the code.

cc: @YohDeadfall

**Comment by eiriktsarpalis** [comment]
camelCase conversion doesn't require splitting tokens -- it simply converts the first group of uppercase characters to lowercase:

https://github.com/dotnet/runtime/blob/24813dc41dd3d573458e710292a109f8ffa4f415/src/libraries/System.Text.Json/Common/JsonCamelCaseNamingPolicy.cs#L32-L57

Consolidating the logic would introduce complexity where it shouldn't exist. Why would we want to do this?

**Comment by eiriktsarpalis** [comment]
As of .NET 7, the CamelCase policy has the following behavior:
```F#
> JsonNamingPolicy.CamelCase.ConvertName <| nameof ``Lemme break your code :trollface:`` ;;
val it: string = "lemme break your code :trollface:"
```
and changing that would be a breaking change.

**Comment by YohDeadfall** [comment]
Without jokes, in my previous attempt of making naming policies I analyzed implementation in other libraries and platforms. Anywhere else policies are implemented exactly as @krwq wrote, i.e., split an input into words, transform them using some logic and concatenate them. When I asked you about `ITransform` interface the idea was about expanding the taken approach to the camel case too. The only change the base class will get is a generic argument to which you pass a struct implementing the interface. A single method of it shall be called instead of `ToLowerInvariant`/`ToUpperInvariant`, and that method will do all the transformation logic and adding a separator if needed.

As I noticed you in the PR, most likely it won't pass "it's written in stone" rule, but let's think that it won't affect too many users and with each release there are breaking changes already (:

**Comment by krwq** [comment]
@YohDeadfall I'd suggest compiling a list of differences in behavior (i.e. table with examples). If we were to make this change we'd possibly introduce compat switch. We'll likely need more upvotes on this issue to proceed though

**Comment by YohDeadfall** [comment]
Hard to point to any exact place in the original PR since there was a discussion about rules, so you have to check at least a half of dotnet/corefx#41354. Some links are provided by a @ahsonkhan in https://github.com/dotnet/corefx/pull/41354#issuecomment-553608572. For my package and merged changes, I also checked Rust libraries, especially [heck](https://github.com/withoutboats/heck).

To conclude, usually name transformers use the same method under the hood to parse an input string and then work on extracted words using rule specific to each policy like lower casing and an underscore as separator. I say usually because I have faced no library which does policies differently, but it might exist since I checked popular only.
