### ISSUE TITLE
superpmi-replay pipeline fails when re-run in CI due to the log artifact already existing

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#77295]
I've re-run the superpmi leg in my PR today and it has failed in the "Publish SuperPMI logs" and "Publish SuperPMI build logs" with errors:
`##[error]Artifact SuperPMI_Logs_x64_checked already exists for build 58267.`
and
`##[error]Artifact SuperPMI_BuildLogs_x64_checked already exists for build 58267.`

It sounds like a bug.

**Comment by janvorli** [comment]
Here is a reference to the log:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=58267&view=logs&j=406f67d9-8952-5074-7a53-dcb346cb6a5f&t=feeda9ba-a6cf-55e3-b217-8f390a72d061

**Comment by janvorli** [comment]
The PR was #77268

**Comment by mangod9** [comment]
@BruceForstall to route appropriately? Also looks like there are some intermittent failures in the jobs recently?

**Comment by BruceForstall** [comment]
This happens when the job is re-run in AzDO. We use the `PublishPipelineArtifact@1` task which fails when trying to overwrite the same log file name. I don't think it supports a "force" mode. All other users seem to use `continueOnError: true` so maybe we need to do that as well to avoid this. Of course, that means we still won't upload the second or subsequent log files, but we won't complain about it, either.

**Comment by mangod9** [comment]
> Of course, that means we still won't upload the second or subsequent log files, but we won't complain about it, either.

correct, other legs show that as a warning but the leg itself completes as green if tests are passing on rerun

**Comment by BruceForstall** [comment]
This was fixed with https://github.com/dotnet/runtime/pull/77685
