### ISSUE TITLE
Correct Nuget Project URL to new location

### ISSUE THREAD

**Issue by peteraritchie** [dotnet/runtime#773]
The current [nuget Project URL](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.IO.Ports/4.6.0-preview4.19164.7) points to https://github.com/dotnet/corefx instead of https://github.com/dotnet/runtime

**Comment by scalablecory** [comment]
@dagood

**Comment by dagood** [comment]
I believe this will happen automatically for the Libraries (formerly CoreFX) packages when they start getting released from 5.0 builds rather than 3.0/3.1 builds. It isn't easy to tell which branch packages like https://www.nuget.org/packages/System.IO.Ports/4.7.0 are associated with, though, as far as I know.

It's more clear-cut for the Installer (Core-Setup) packages, like `Microsoft.NETCore.App.Ref`, which is already changed so that 5.0 builds point to dotnet/runtime.

I suppose there's a question about whether we want to service 3.0/3.1 so that those packages start pointing to point at dotnet/runtime. It would make sense because we're filing and tracking servicing issues in dotnet/runtime. On the other hand, the source code for for 3.0/3.1 still lives in dotnet/coreclr, dotnet/corefx, and dotnet/core-setup, and I think there *might* actually be a functional dependency here for sourcelink that we'd need to make sure we don't break.

**Comment by peteraritchie** [comment]
Yeah, I tried to find out where, but no luck :-)

**Comment by ViktorHofer** [comment]
>  It would make sense because we're filing and tracking servicing issues in dotnet/runtime. On the other hand, the source code for for 3.0/3.1 still lives in dotnet/coreclr, dotnet/corefx, and dotnet/core-setup, and I think there might actually be a functional dependency here for sourcelink that we'd need to make sure we don't break.

We don't plan to port the servicing branches into the dotnet/runtime repo. Work for < 5.0 will be done in the archived repositories (corefx, coreclr and core-setup).

cc @jaredpar 

> I believe this will happen automatically for the Libraries (formerly CoreFX) packages when they start getting released from 5.0 builds rather than 3.0/3.1 builds.

Right, as soon as we publish new packages to nuget (when we release .NET 5), the link will be updated automatically and point to dotnet/runtime.

Closing as no action needed.
