### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces() on Android leads to FileNotFoundException

### ISSUE THREAD

**Issue by kdotdk** [dotnet/runtime#77441]
### Description

This has been reported previously in [#3617](https://github.com/dotnet/maui/issues/3617) but problem still exists.

I have tried the following combinations:
- Works on Android 9 API 28 (Physical Tablet)
- Works on Android 10 API 29 (Visual Studio Pixel 5 Emulator, Win 10)
- Fails on Android 11 API 30 (Visual Studio Pixel 5 Emulator, Win 10)
- Fails on Android 12 API 31 (Visual Studio Pixel 5 Emulator, Win 10)
- Fails on Android 13 API 32 (Visual Studio Pixel 5 Emulator, Win 10)
- Fails on Windows 11 Windows Subsystem for Android Version 2207.40000.8.0

### Steps to Reproduce

1) Get [MAUI sample app](https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/Shell)
2) Add Permissions:
[assembly: UsesPermission(Android.Manifest.Permission.AccessNetworkState)]
[assembly: UsesPermission(Android.Manifest.Permission.ChangeNetworkState)]
[assembly: UsesPermission(Android.Manifest.Permission.AccessWifiState)]
[assembly: UsesPermission(Android.Manifest.Permission.ChangeWifiMulticastState)]
[assembly: UsesPermission(Android.Manifest.Permission.ChangeWifiState)]
[assembly: UsesPermission(Android.Manifest.Permission.Internet)]

3) Add a call to System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces() on a button click (E.g. in AboutPage TabCommand)

Result the application crash with FileNotFoundException. 

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/Shell

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11-13 + Windows Subsystem for Android Version 2207.40000.8.0

### Relevant log output
[windows-subsystem-android-crash-log.txt](https://github.com/dotnet/runtime/files/9866921/windows-subsystem-android-crash-log.txt)

**Comment by grendello** [comment]
@jonathanpeppers it's possible, although the code that lives in xamarin/xamarin-android (and which was moved to dotnet/runtime recently) deals with enumerating interface addresses, not interfaces themselves. The code which enumerates interfaces lives in dotnet/runtime. I'll try to repro this issue and when/if I see the trace I'll be able to tell more.

**Comment by grendello** [comment]
Note that it might be due to tightened security on Android, since they have been gradually restricting access to bits and pieces of information about the system.

**Comment by kdotdk** [comment]
- Issue updated with used permissions 
- Log from Windows Subsystem for Android Windows 11 added

Note first line:
    10-26 08:37:07.924  4736  4736 W DOTNET_NETLINK: Failed to bind to the netlink socket. Permission denied

**Comment by grendello** [comment]
Yes, that's what it appears to be. xamarin/xamarin-android [does use netlink](https://github.com/xamarin/xamarin-android/blob/ab6712a48e4b93e9c3d605c7b393814d477e2bc8/src/monodroid/jni/xamarin_getifaddrs.cc) when [`getifaddrs`](https://github.com/xamarin/xamarin-android/blob/ab6712a48e4b93e9c3d605c7b393814d477e2bc8/src/monodroid/jni/xamarin_getifaddrs.cc#L365-L385) is not available in bionic (the Android libc). dotnet/runtime ported `xamarin/xamarin-android` `getifaddrs` [implementation](https://github.com/dotnet/runtime/blob/a6cb7705bd5317ab5e9f718b55a82444156fc0c8/src/native/libs/System.Native/pal_ifaddrs.c) recently. `getifaddrs` is available (at least as a public API) on Android >= 24 (this is a **compile time** dependency), so if the runtime is built against an earlier version of Android API (both Xamarin.Android and dotnet/runtime are built against API 21) the netlink implementation is very likely used.

Until [very recently](https://github.com/dotnet/runtime/commit/e2e4e71056df75a528d8c40b16e122cd914c9893) the dotnet/runtime implementation **always** used the netlink implementation, with the commit linked to previously switching to the same strategy as the implementation in Xamarin.Android, to dynamically look up `getifaddrs` and, if found, use that instead of the netlink code. This fix might be required for the enumeration to work on Android 30 and above.

/cc @simonrozsival was your fix above backported to net6? Or is it going to be part of only net7+?

**Comment by simonrozsival** [comment]
@grendello the most recent fix should be included in a servicing release of .NET 6 soon: https://github.com/dotnet/runtime/pull/77260

**Comment by kdotdk** [comment]
Have tried with new .Net 6.0.12.
It works on Android 11 API 30 (Visual Studio Pixel 5 Emulator, Win 10) 👍 
(I have not access to Physical Android Device )

**Comment by kdotdk** [comment]
I have no other issues for now
