### ISSUE TITLE
[wasm] ManagedError constructor has significant overhead due to reading Error.stack

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#77473]
### Description

The `ManagedError` constructor unintentionally reads the current stack when being created, with this line:
```javascript
this.superStack = Object.getOwnPropertyDescriptor(this, "stack"); // this works on Chrome
```
Unfortunately that descriptor appears to have a `value` instead of a `get` so doing this is equivalent to just doing `this.stack`. When running browser-bench, `ManagedError`'s ctor takes up a considerable amount of execution time (over 13 seconds in my last run), with the majority of that spent getting the stack.
The `Object.defineProperty` call afterwards is probably also expensive.

### Configuration

browser-bench using a Release build of dotnet.wasm, with AOT/trimming disabled (so running under the interpreter). Should repro under AOT too, though.

### Regression?

No, this is new code

### Data

Current data:
| measurement | time |
|-:|-:|
|            JSInterop, JSImportTaskFail |  1217.4000ms |
|                JSInterop, JSImportFail |   487.1818ms |

With proposed change:
| measurement | time |
|-:|-:|
|            JSInterop, JSImportTaskFail |   958.8333ms |
|                JSInterop, JSImportFail |   469.4167ms |

### Analysis

The most likely fix is to instead create a regular instance of Error we can use to request `.stack` on demand, and define our custom `stack` getter in our prototype instead of doing it in the ctor on each new instance. That should make creating `ManagedError` instances much less expensive.

**Comment by kg** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
![image](https://user-images.githubusercontent.com/271576/199195405-b0a8222c-b460-4588-9e3e-4251f234a735.png)

This is what I see on chrome. It seems to me that `super` is building the stack and that's expensive.
Especially when this very deep stack. And possibly `async` calls on it are making the task even more difficult for the browser.

Because of this issue in V8, we could not make `stack` override in the class prototype.
https://bugs.chromium.org/p/chromium/issues/detail?id=1379185

**Comment by kg** [comment]
I guess the profiler data on my end was incorrect, since it said all the time was being spent in the stack getter. Your data also makes sense.
