### ISSUE TITLE
System.IO.Hashing's ref is missing a csproj

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#77846]
As far as I can tell, it's the only ref folder in all of libraries that lacks one.  Whether or not we're publishing a ref assembly in the nuget package, it means the System.IO.Hashing.cs in that folder isn't being validated.

cc: @ViktorHofer, @bartonjs

**Comment by bartonjs** [comment]
Back in https://github.com/dotnet/runtime/pull/53623#issuecomment-862530135 (and slightly above) it had been brought up, I said I copied what System.Formats.Asn1 did, there were some nods of agreement, and we all moved on.

But since System.Formats.Asn1\ref _does_ have a csproj... I no longer know what's what.
