### ISSUE TITLE
Assert content is type System.Net.Http.EmptyContent

### ISSUE THREAD

**Issue by swasun99** [dotnet/runtime#77893]
We are facing an issue after .net 6 upgrade with the below code.

Current Code:

HttpResponseMessage result = await httpClient.PostAsJsonAsync(...);
if (result.Content != null)
{
    //Read content
    Data d = await result.Content.ReadFromJsonAsync<Data>()
}

After the upgrade to .net 6, we see that we no longer get the content as null but of type  System.Net.Http.EmptyContent, which if we dont check ReadFromJsonAsync call throws an exception. However we are unable to include a check by type in the if condition to skip the call as it doesnt get resolved from the namespace System.Net.Http

We had to do a hacky check as below which is working but somehow it doesnt look good, hence wanted to check if there is a better way.

 if (result.Content != null && !string.IsNullOrWhiteSpace(result.Content!.ToString()) && !result.Content!.ToString()!.Equals("System.Net.Http.EmptyContent", StringComparison.OrdinalIgnoreCase))

**Comment by stephentoub** [comment]
What were you upgrading to .NET 6 from, and on what OS?

In .NET 5, HttpResponseMessage.Content was changed by design to never return null, as part of better supporting nullable reference types.  But in general it wouldn't be visible because the underlying SocketsHttpHandler would never return a null content in a response message.  So I'd like to understand what platform you're running on and how your HttpClient is configured that you were ever seeing a null content emerge from PostAsJsonAsync.

**Comment by swasun99** [comment]
Hi, we are upgrading to .net 6 from .net core 3.1 on windows.
Without the check, the ReadFromJsonAsync() is throwing an exception so we need a way to know if the content is of type EmptyContent before using ReadFromJsonAsync().

Our HttpClient is the default one from System.Net.Http version 4.2.2.0

**Comment by swasun99** [comment]
Do you suggest replacing ReadFromJsonAsync() with the below code if there is no way we can assert the type i.e read as string first and then deserialize by type?

            if (result.Content != null)
            {
                string responseOptions = await result.Content.ReadAsStringAsync();
                response.Options = string.IsNullOrWhiteSpace(responseOptions) ? Array.Empty<Option>() : JsonSerializer.Deserialize<Option[]>(responseOptions, jsonSerializerOptions)!;
            }

**Comment by stephentoub** [comment]
First I'd like to understand how you were ever seeing Content be null.  Can you share a zipped standalone repro project that demonstrates that happening?  Thanks.

**Comment by swasun99** [comment]
We dont see it null anymore, the content is now of type System.Net.Http.EmptyContent.

For example, the unit test below mocks it to return an empty content

            Response? response = new Response();

            Mock<HttpMessageHandler> mockHandler = new Mock<HttpMessageHandler>();

            _ = mockHandler.SetupAnyRequest()
                .ReturnsResponse(HttpStatusCode.OK);

            _ = mockHandler.SetupRequest(HttpMethod.Get, $"{baseUrl}/app/v1/options")
                .ReturnsResponse(JsonSerializer.Serialize(response), "application/json");

and the ReadFromJsonAsync call fails as we dont skip it if its empty content

**Comment by stephentoub** [comment]
> We dont see it null anymore, the content is now of type System.Net.Http.EmptyContent.

I mean a repro on .NET Core 3.1, since you said you were seeing it null then.

> For example, the unit test below mocks it to return an empty content

Oh! So this is only happening when you mock and provide your own HttpMessageHandler, not when actually using the real types?  If that's the case, this is expected.  As noted, HttpResponseMessage.Content was changed in .NET 5 to never return null, but in real use, it would never return null anyway.  Because you're mocking and returning null explicitly, that's why you're seeing a change in behavior.

**Comment by swasun99** [comment]
We are not mocking it as null, we are mocking it with an empty object in the unit test and in the real code also we see EmptyContent being sent and not null

**Comment by stephentoub** [comment]
> and in the real code also we see EmptyContent being sent and not null

I understand, that's what you see on .NET 6.  In the real code you see that happening in .NET Core 3.1 as well?  Can you share a repro project for that?

> We are not mocking it as null, we are mocking it with an empty object in the unit test

But on .NET Core 3.1, your mock is using an HttpResponseMessage with Content set to null, yes?

**Comment by stephentoub** [comment]
Let me try to be clearer.

SocketsHttpHandler creates an HttpResponseMessage with a Content _that's never null_.  Never has been.  Same goes for HttpClientHandler, in both .NET Framework and .NET Core.

However, HttpResponseMessage can be constructed by other code, and if you just new up an HttpResponseMessage, its _content will default to null.

It was never intended for HttpClient to return HttpResponseMessages with Content as null, and real handlers would never do that.  So in .NET 5, we changed HttpResponseMessage.Content to essentially do `return _content ??= new EmptyContent();` instead of just `return _content;`.

If your mocking layer is creating an HttpResponseMessage but not setting the Content, that's why you were seeing it as null in .NET Core 3.1 but not in .NET 6.  And it also highlights that the mocking layer is providing different behavior from what you'd get in real use, because the underlying handlers would never do what your mocking layer is doing; they'd never return null.

If you're saying you were seeing the real (not-mocked) HttpClient calls produce HttpResponseMessages with null Content when running on .NET Core 3.1, then I'd like to understand that with a repro project, because that shouldn't have been happening.

And assuming it wasn't actually happening in real use, then I think your mocking test needs to be improved to not return null Content, either, since that's not something that would happen in real use, on either .NET Core 3.1 or .NET 6.

**Comment by swasun99** [comment]
ok makes sense, I will try to change the mocking to not return a null content if it wont happen in real world anymore.

**Comment by stephentoub** [comment]
Thanks.

> if it wont happen in real world anymore

Not just "anymore"... it wouldn't have happened before, either :wink: (And if you have a repro showing otherwise, I'd really like to see it :smile:.)

**Comment by swasun99** [comment]
What I mean is the same unit test was successful on .net core 3.1 but ReadFromJsonAsync throws an exception after the upgrade to .net 6 which is because we are not skipping the call with the null check as it is not true anymore

**Comment by stephentoub** [comment]
> So, it makes sense to not have the null check at all if it is not going to be null and the unit test mocking null content should also be removed is what I understand.

Correct.

**Comment by swasun99** [comment]
Thanks for the detailed explanation :) With these changes, hopefully we should be good.

**Comment by stephentoub** [comment]
Excellent.  Thanks for the discussion.
