### ISSUE TITLE
Handle returned GetMainProgramHandle() not sufficient for resolving statically linked native symbols on iOS

### ISSUE THREAD

**Issue by stanger** [dotnet/runtime#77985]
### Description

Based on the discussion in #57610 we were under the impression that using `GetMainProgramHandle()` in tandem with `NativeLibrary.SetDllImportResolver()` would be a replacement for having to modify third party packages to use `[DllImport("_Internal")]` on iOS. So far in testing on .NET 7 this has not been the case. 

I created a sample native iOS library (libsayhello) and a wrapping C# lib which handles [DllImport("libsayhello')]. Then within a sample Maui app I added Interop code to allow my lib to be statically linked into the main application at compile time, then attempted to catch the resolution of 'libsayhello' in the import resolver and return the handle returned by GetMainProgramHandle(). 

### Reproduction Steps

A test app showing the behavior is located at [stanger/ResolverTest](https://github.com/stanger/ResolverTest).

### Expected behavior

DllImport calls for 'libsayhello' should be able to resolved to their statically linked symbols in the main binary.

### Actual behavior

DllNotFoundException

### Configuration

.NET: 7.0.100-rc.2.22477.23
iOS 16 and MacOS 13 (originally discovered on iOS)
Tested on x64 and ARM64

**Comment by jkoritzinsky** [comment]
I see the problem. We definitely should have caught this earlier as this was the end-to-end scenario...

Sometimes, the value returned by `GetMainProgramHandle()` is `IntPtr.Zero`, as that's the handle to use for this case. However, `SetDllImportResolver` expects the delegate to return `IntPtr.Zero` for the failure case. As a result, using `GetMainProgramHandle` with `SetDllImportResolver` as it exists today has a fundamental problem on platforms where `IntPtr.Zero` is the correct handle for this case.

I see a few solutions here:

1. Introduce an API specifically for resolving `DllImport`s to the main program handle (what we were trying to avoid).
2. Introduce an overload of `SetDllImportResolver` that takes a delegate that returns `IntPtr?` instead of `IntPtr`. The user experience here would be pretty rough though as overload resolution would prefer the `IntPtr` overload for target-typed lambdas unless we got something like https://github.com/dotnet/runtime/issues/65965 (I don't think ref-assembly tricks would work here well).

**Comment by am11** [comment]
> Sometimes, the value returned by `GetMainProgramHandle()` is `IntPtr.Zero`

Going by: 
https://github.com/dotnet/runtime/blob/02c3e95fc2f87dcabfea8bef2c1b1a48c2249d9d/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.cs#L261 it throws an exception instead of returning `IntPtr.Zero`.

**Comment by jkoritzinsky** [comment]
In which case, I'm not sure what would be causing a `DllNotFoundException` specifically.

@stranger, can you confirm what `GetMainProgramHandle` is returning?

**Comment by stanger** [comment]
This is the value I see in the debugger.

`handle	0xfffffffffffffffe`

<img width="291" alt="Screenshot 2022-11-07 at 3 11 57 PM" src="https://user-images.githubusercontent.com/96721/200416400-638fc5f0-76b9-42c2-a691-82b49095ded1.png">

**Comment by stanger** [comment]
The stack trace isn't overly verbose.

`System.DllNotFoundException: libsayhello
   at ResolverSample.MainPage.OnCounterClicked(Object sender, EventArgs e) in /Users/stanger/Workspaces/Enclave/ResolverSample/src/ResolverSample/MainPage.xaml.cs:line 17`
