### ISSUE TITLE
Marshal.GetIUnknownForObject throws a TypeLoadException if the parameter has a covariant property. 

### ISSUE THREAD

**Issue by NikitaSemenovAkvelon** [dotnet/runtime#78090]
### Description

Using a class with [a covariant property](https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/proposals/csharp-9.0/covariant-returns#class-property-and-indexer-override) as the `o` parameter of `Marshal.GetIUnknownForObject` causes a `TypeLoadException`. 

### Reproduction Steps

1. Create two classes, first as a base with virtual property and second as derived with overriding the property's type.
2. Pass an instance of the derived class to `Marshal.GetIUnknownForObject`.

### Expected behavior

The `IUnknown` pointer is returned. No exception is thrown.

### Actual behavior

A `TypeLoadException` is thrown.

### Regression?

No

### Known Workarounds

No

### Configuration

.NET SDK:
 Version:   8.0.100-alpha.1.22480.9
 Commit:    429fe082c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64

### Other information

A small sample to reproduce the issue.
[CovariantPropertySample.zip](https://github.com/dotnet/runtime/files/9967965/CovariantPropertySample.zip)

**Comment by AaronRobinsonMSFT** [comment]
@NikitaSemenovAkvelon Thank you for the very helpful repro.

This is a tricky issue and my initial thought is this is "won't fix". The problem here is the code used to generated vtable layout for COM interop in the class interface scenario is ignorant of covariant returns - the logic was set in stone in .NET Framework 1.0 timeframe I believe.

https://github.com/dotnet/runtime/blob/c04cf0ca8068c6306c135abb3ce98a33de13579c/src/coreclr/vm/classcompat.cpp#L2245-L2268

My perspective here is types involved in COM interop are limited in what they can be used for because these code paths are expected to remain static and stable. This is a relaxation of rules so possible "okay", but without a broader audit and specific business need to justify the change, I am not keen on fixing this.

@jkotas or @davidwrighton may have a different take, but right now my vote is "won't fix".

**Comment by AaronRobinsonMSFT** [comment]
Source repro for issue, taken from OP's supplied example.

```csharp
internal class BaseClass
{
    public BaseClass(object value)
    {
        Value = value;
    }

    public object Value { get; }

    internal virtual object ValueInternal => Value;
}

internal class DerivedClass : BaseClass
{
    public DerivedClass(string value) : base(value)
    {
    }

    internal override string ValueInternal => (string)Value;
}

unsafe class Program
{
    public static void Main(string[] args)
    {
        BaseClass instance = CreateInstance();

        // Throws System.TypeLoadException:
        IntPtr iUnknown = Marshal.GetIUnknownForObject(instance);

        [MethodImpl(MethodImplOptions.NoInlining)]
        static BaseClass CreateInstance() => new DerivedClass("test");
    }
}
```

**Comment by AaronRobinsonMSFT** [comment]
Closing as "Won't Fix" for now. We can revisit if this becomes important to the community.
