### ISSUE TITLE
Apps crashing when using ZipFile.CreateFromDirectory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78165]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Apps-crashing-when-using-ZipFileCreateF/10134164)._

---
I reported https://developercommunity.visualstudio.com/t/Apps-crashing-when-using-ZipFileCreateF/1651269?space=61&ftype=problem&preview2=true&q=CreateFromDirectory&sort=newest back in January,
During my summer vacation Microsoft support asked for some extra info, but that request did not reach me as I was away. Anyway, here is the info as requested.

In our application customers are experiencing crashes when ZipFile.CreateFromDirectory. To me it appears, as that function does not clean itself properly in case of failure, and then GarbageCollector experiences an exception, leading to crash.

In January, the crash occurred when creating the zip file to a network drive with aforementioned function. Now I've noticed that the same (similar) thing occurs also, when the target drive is a USB stick, that is almost full, so that during the execution of the function the drive becomes full.

In January, I was using VS 2019 with .Net Framework 4.7.1, now I've switched to .Net 4.8. As far as I can tell, my Visual studio is up-to-date with updates.

---
#### Feedback Bot on 8/30/2022, 01:03 AM: 

(private comment, text removed)
#### Dan Moseley [MSFT] on 11/8/2022, 09:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by itorsti** [comment]
Did another example project of this, and added dump file as well as screenshot of stack trace from garbage collector thread causing the problem


Dump file:
https://drive.google.com/file/d/1uFmGA6Acq6keNc7aRd1mf1hBcSDTni78/view?usp=sharing


![StackTrace](https://user-images.githubusercontent.com/118543445/209813002-87783ffd-704a-4855-b49e-e8cfbedecd3a.png)
[ZipTester.sln.zip](https://github.com/dotnet/runtime/files/10314230/ZipTester.sln.zip)

**Comment by danmoseley** [comment]
Can you please try on .NET 7, for comparison?

**Comment by adamsitnik** [comment]
> There is not enough space on the disk.

It looks like you don't have enough disk space to create zip file from given folder.

> In January, the crash occurred when creating the zip file to a network drive with aforementioned function. Now I've noticed that the same (similar) thing occurs also, when the target drive is a USB stick, that is almost full, so that during the execution of the function the drive becomes full.

Was the network drive almost full as well?

**Comment by svick** [comment]
@adamsitnik As I understand it, an exception is expected. An exception thrown by the finalizer is not.

**Comment by itorsti** [comment]
Asked a colleague to try this with .Net 6.0 (or newer). 

It is of course natural, that an error (an exception) occurs if and when the target drive becomes full during creation of zip, but as the zip creation routine already catches exceptions, it feels plain wrong that there is an exception in finalizer too.

**Comment by adamsitnik** [comment]
@svick  Thanks for the clarification 👍

**Comment by adamsitnik** [comment]
`FileStream` finalizer won't throw in .NET 6 or 7:

https://github.com/dotnet/runtime/blob/d87f7b2b81647917528286d91ed91db2a34b0985/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs#L128-L132

But it may on .NET Framework:

https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,1288

Since it's not a security issue, we won't backport the fix to .NET Framework.

I did a quick search and it seems that there is no way to tell .NET Framework to not crash the application on unhandled finalizer thread exceptions. We can do it for:

- Task exceptions: https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/throwunobservedtaskexceptions-element
- WinForms threads exceptions: https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.setunhandledexceptionmode?view=netframework-4.8.1

I've take a look at your code sample:

```cpp
try {
    ZipFile::CreateFromDirectory("C:\\temp\\temp", targetZip);
}
catch (...) {
    return -1;
}
```

Since `ZipFile::CreateFromDirectory` returns void there is nothing we can do. You could always try to re-implement this method by using `ZipArchive` directly (create it from a file stream) and own the `FileStream` and supress the finalization on your own, but you would need to mimic everything the method does. Some conceptual pseudocode below:

<details>

```cs
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;

namespace ZipFull
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string source = args[0];
            string dest = args[1];

            using (FileStream fs = File.Create(dest))
            {
                GC.SuppressFinalize(fs); // supress FileStream finalization

                using (ZipArchive archive = new ZipArchive(fs, ZipArchiveMode.Create))
                {
                    // iterate over all files in source and add entires
                    DirectoryInfo sourceDirectory = new DirectoryInfo(source);
                    foreach (FileSystemInfo file in sourceDirectory.EnumerateFileSystemInfos("*", SearchOption.AllDirectories))
                    {
                        if (file is FileInfo)
                        {
                            archive.CreateEntryFromFile(file.FullName, file.Name);
                        }
                        else if (file is DirectoryInfo di && !di.EnumerateFileSystemInfos().Any())
                        {
                            archive.CreateEntry("$getTheName");
                        }
                    }
                }
            }
        }
    }
}
```

</details>
