### ISSUE TITLE
Is it possible to use a AOT dll with a WPF project?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/runtime#78211]
I know that by the moment it is not possible to compile a WPF project with the AOT option.

But in my case, the WPF project use another C# libraries which I have configure to compile as AOT.

But if I am not wrong, when I add the reference to the library from my WPF project and I publish it, the dll is not AOT. So I guess that the projects of the dlls use the same configuration than the main project.

So I have to try to publish the dll manually, and in this case I get the AOT dll. I add the reference to this dll in my WPF project, browising it, but I get an error that the reference is invalid or unsupported.

If I compile the library without AOT then I can add the reference to the WPF project.

So my question is, is it possible to use AOT dlls in a project that is not compile as AOT? Because I was thinking that if the WPF project can't be compiled as OAT, at least I would like to can get the benefits of AOT in the libraries that can be compiled in this way.

Thanks.

**Comment by jkotas** [comment]
Native AOT compilation is only applicable to the final output of .NET project (ie `.exe`). It is not possible to apply native AOT compilation to a subset of project assemblies.

WPF applications can be optimized using `PublishReadyToRun`.

**Comment by agocke** [comment]
Note: it looks like you are trying to use Native AOT to compile a managed library, and then reference it as a managed library. If you compiled the library into a native library using Native AOT and then P/Invoked into that library, that should work. However, it doesn't seem like that would be very helpful. You would have to marshal all your code across the native boundary and I don't think your code size would decrease that much, since the WPF framework itself would still pull in large portions of the .NET framework.
