### ISSUE TITLE
.NET 7 PublishReadyToRun causes crash when publishing, but it worked on .NET 6

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/runtime#78278]
### Description

Hello,

I am experimenting .NET 7 on my project and I am having a problem with PublishReadyToRun. It causes the `dotnet publish` process to crash.
The project is an Avalonia desktop GUI.

### Reproduction Steps

My .csproj is as below. The referenced projects, Domain and Infrastructure, are vanilla, without any external dependencies, only pure .NET code.
This is the repo for the project: [link](https://github.com/alexandrehtrb/Pororoca).

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Pororoca.Desktop</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <EnableCompressionInSingleFile>True</EnableCompressionInSingleFile>
    <PublishReadyToRun>True</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pororoca.Domain\Pororoca.Domain.csproj"/>
    <ProjectReference Include="..\Pororoca.Infrastructure\Pororoca.Infrastructure.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.18" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.18" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.18" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="0.10.18" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.18" />
  </ItemGroup>
</Project>
```

My `dotnet publish` full command is below; runtime is `win-x64`, `PublishSingleFile` is `true`:

```ps1
dotnet publish ./src/Pororoca.Desktop/Pororoca.Desktop.csproj `
		--verbosity quiet `
		--nologo `
		--configuration Release `
		-p:PublishSingleFile=${publishSingleFileArg} `
		--self-contained true `
		--runtime $runtime `
		--output $outputFolder
```

### Expected behavior

It should publish without problems.

### Actual behavior

The following message shows up on console and an error dialog also appears:

```
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):
error MSB6006: "C:\Users\Alexandre\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\7.0.0\tools\crossgen2.exe" exited with code -1073741511.
[C:\Projetos\Pororoca\src\Pororoca.Desktop\Pororoca.Desktop.csproj]
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(353,5):
error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false.
[C:\Projetos\Pororoca\src\Pororoca.Desktop\Pororoca.Desktop.csproj]
```

![PublishReadyToRun_Error_NET7](https://user-images.githubusercontent.com/27026741/201495016-4dba349a-21d8-4afb-a6f1-47e807dd03be.png)

```
crossgen2.exe - Entry Point Not Found
The procedure entry point EventSetInformation could not be located in the dynamic link library ADVAPI32.dll.
```

### Regression?

It worked without problems on .NET SDK 6.0.402.

### Configuration

`dotnet --info`:

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

### Other information

Running on Windows 7 x64.

**Comment by EgorBo** [comment]
Presumably, the answer is the same as https://github.com/dotnet/runtime/issues/78277#issuecomment-1312579354

**Comment by Symbai** [comment]
[Here](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#windows) it says Windows 7 is still supported by .NET 7

**Comment by hez2010** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/evntprov/nf-evntprov-eventsetinformation

EventSetInformation does not exisit on Windows 7. Crossgen2 has dropped support for Windows 7.

**Comment by MichalStrehovsky** [comment]
crossgen2 is compiled with NativeAOT and NativeAOT generates this import because WindowsAPIs.txt says it's safe to do so:

https://github.com/dotnet/runtime/blob/b6deba5721419d14e8b71670fdce8a2c78b0d84e/src/coreclr/nativeaot/BuildIntegration/WindowsAPIs.txt#L106

Without that entry, it would use LoadLibrary/GetProcAddress.

Apparently there's a try/catch that catches the EntryPointNotFoundException at runtime:

https://github.com/dotnet/runtime/blob/b6deba5721419d14e8b71670fdce8a2c78b0d84e/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs#L1207-L1218

If Windows 7 is still supported, we'll probably have to go through the whole list and find APIs that don't exist on 7. The list was already supposed to do that, but looks like there was an issue seeding it:

https://github.com/dotnet/runtime/blob/b6deba5721419d14e8b71670fdce8a2c78b0d84e/src/coreclr/nativeaot/BuildIntegration/WindowsAPIs.txt#L3-L4

**Comment by MichalStrehovsky** [comment]
Fortunately, we disable EventSource by default on NativeAOT so this is somewhat harder to hit for regular users. I made crossgen2 opt into EventSource because we actually wanted it to be enabled :/.

**Comment by jkotas** [comment]
> we'll probably have to go through the whole list and find APIs that don't exist on 7

When I have compiled this list, I have verified that all APIs in the list exist by running a script that did LoadLibrary+GetProcAddresses on Windows 7 test machine.

I think that the problem is that this API was backported to Windows 7 by [KB3080149](https://support.microsoft.com/en-us/topic/update-for-customer-experience-and-diagnostic-telemetry-0b4f29c3-8361-b748-f862-7ecedbc57cbf
) and the Windows 7 test machines have this KB installed. One way to fix this problem is to add this KB to the list of Windows 7 prerequisites at https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#additional-deps

**Comment by MichalStrehovsky** [comment]
> Hello, I have a similar issue on windows 11 When publishing the app as a single file application, the `dotnet publish` command never finish. And it looks like there is a memory leak, if the process is not linked all the available memory will be used after some time. Last time it used up to 47GB of RAM. Setting `PublishReadyToRun` to false will solve the issue

This issue is not similar because it's not on Windows 7 and it's not a crash. Your symptom sounds like #66079 that hasn't been addressed yet. I suggest commenting there or opening a new issue until it can be root caused to really be the same one.

**Comment by agocke** [comment]
.NET 7 does not have Windows 7 support: https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md. If this were a fundamental API in the runtime itself, I would consider fixing this anyway, but because this is specifically for the SDK, crossgen in particular, I don't think Windows 7 support is necessary.

Users can publish on a Windows 10 machine and deploy to a Windows 7 machine. Development on Windows 7 itself is not a high priority.
