### ISSUE TITLE
[API Proposal]: Implement AES OCB mode

### ISSUE THREAD

**Issue by Kebechet** [dotnet/runtime#78309]
### Background and motivation

Currently library `System.Security.Cryptography` contains `AesGcm`  what is an authentication cipher used in many application for many use cases. But among the modes there is AesOcb which has comparable security as AesGcm but is ~2x faster what is a huge benefit.

Probably the reason behind not implementing AesOcb in the past is that it was patented. But in [2021 this patent was intentionally  abandoned](https://en.wikipedia.org/wiki/OCB_mode#Patents).

Currently there is not any performant and FIPS certified implementation in the .NET for this cipher mode and thus implementing this mode into runtime would bring additional value.

### API Proposal

API design will be almost the same as `AesGcm`. Because both have same structure of inputs and outputs.

```
public sealed class AesOcb
{
    public AesOcb(byte[] key)
    {
    }

    public void Encrypt(byte[] nonce, byte[] plaintext, byte[] ciphertext, byte[] tag, byte[]? associatedData = null)
    {

    }

    public void Decrypt(byte[] nonce, byte[] ciphertext, byte[] tag, byte[] plaintext, byte[]? associatedData = null)
    {

    }
}
```

### API Usage

```csharp
var aes = new AesOcb(keyBytes);

aes.Encrypt(nonceBytes, plaintextBytes, ciphertextBytes, tagBytes, associatedDataBytes);
aes.Decrypt(nonceBytes, ciphertextBytes, tagBytes, plaintextBytes, associatedDataBytes);

```

**Comment by filipnavara** [comment]
.NET has a policy on using system cryptography libraries. AES OCB is not implemented in any of them as far as I know (perhaps with the exception of OpenSSL but all I can find is reports about it being broken). I implemented a managed version of it (https://github.com/1hub/springburg/blob/master/src/Cryptography/Algorithms/AesOcb.cs) but it's not extensively tested.

**Comment by bartonjs** [comment]
One problem with OCB is there are actually three of them (OCB1, OCB2, OCB3), though the creator of OCB did an RFC where he proposes the OCB3 variant as "OCB", so that's probably what is intended by just "OCB" now.

The second problem, as @filipnavara mentioned, is that we don't write our own cryptographic routines.  OpenSSL has an OCB mode for AES, but neither Windows (CNG or CAPI) nor macOS (CommonCrypto or CryptoKit) do.  Because of our multi-OS nature, our general approach has been to wait for at least two major platforms to support an algorithm before we add it to .NET Cryptography.

While we could keep this issue open in perpetuity waiting on there being a second major platform to offer OCB (like we have for SHA-3), I don't have the same confidence that it'll ever happen with OCB.  So, instead, I'm going to close the issue as it is non-actionable; but we can resume it again if we get support on Windows or macOS.

**Comment by Kebechet** [comment]
@bartonjs thank you for these details. Is there a way to create a proposition to add a new feature into Windows CNG somewhere ?
