### ISSUE TITLE
Dynamicaly loading "Microsoft.Codealaysis" fails in Net6 but works in 7

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#78349]
### Description

I've a complex project, wich I switched to Net7. During this change I also updated Microsoft Code Analysis Assemblies.
Now we need to switch our Software also back to 6, but the new Codeanalysis Assemblies do not work when dynamicaly loaded.
I get the error that a Method is not found:

      MissingMethodException: Method not found: 'Void Microsoft.CodeAnalysis.Emit.EmitOptions..ctor(Boolean, Micro....
      
but the method is there, and also the correct Asse´mbly is loaded to Memory

### Reproduction Steps

I created a sample:

[ComplexAssemblyLoadingSample.zip](https://github.com/dotnet/runtime/files/10007627/ComplexAssemblyLoadingSample.zip)

The sample crashes with the exception. It work if you switch to Net7.

### Expected behavior

The sample provided should not crash even in Net6.
Can anybody tell me where a wrong dll is bound or found?

### Actual behavior

It crashes.

**Comment by jogibear9988** [comment]
I've a custom assembly loader in the project (but it is much trimmed down). It loads all the assemblies from a byte array, so the files are not locked on disk.

**Comment by jogibear9988** [comment]
Also if you remove the reference to "System.Collections.Immutable" from the dynamicly loaded assembly ("MCC.Common.CommonServiceImpl") it also works in Net6. But why?

**Comment by jogibear9988** [comment]
Okay, our big project now works, after I removed all the refernces to System.Collections.Immutable, but why?

**Comment by dakersnar** [comment]
cc @jaredpar as this is code analysis related

**Comment by jkotas** [comment]
> I've a custom assembly loader in the project (but it is much trimmed down). It loads all the assemblies from a byte array, so the files are not locked on disk.

The repro is loading `System.Collections.Immutable` assembly twice. One copy is loaded into default load context and second copy is loaded into `Assembly.Load(byte[], ...)` load context. The `MissingMethodException` is caused by assembly bound against one copy of `System.Collections.Immutable` trying to call an assembly bound against different copy of `System.Collections.Immutable`.

Logging code like this helps with troubleshooting problems with loading multiple copies of the same assembly:
```
foreach (var a in AppDomain.CurrentDomain.GetAssemblies())
{
    Console.WriteLine($"{a.GetName().Name} loaded into {AssemblyLoadContext.GetLoadContext(a)}");
}
```
When you repro fails, it shows that System.Collections.Immutable was loaded twice:
```
...
System.Collections.Immutable loaded into "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
...
System.Collections.Immutable loaded into "Assembly.Load(byte[], ...)" System.Runtime.Loader.IndividualAssemblyLoadContext #3
...
```
