### ISSUE TITLE
CA2007 for Durable function Orchestrations

### ISSUE THREAD

**Issue by austy81** [dotnet/runtime#78371]
Orchestrations in Durable functions has certain constraints. Would it be possible to support in [CA2007 ](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007) (Do not directly await a Task) the fact, that it is only possible to use ConfigureAwait(true) in the orchestration code?

Docs for code constraints in Durable functions orchestrations:
https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-code-constraints?tabs=csharp#net-threading-apis

Functions serving as Orchestrations are decorated by attribute: [OrchestrationTrigger]

In our case, function having ConfigureAwait is used in the base class so actual class decorated with [OrchestrationTrigger] inherits from the base class.

Thanks

**Comment by mavasani** [comment]
@stephentoub

**Comment by stephentoub** [comment]
How does an orchestrator handle a case where you call into a helper function that itself awaits with ConfigureAwait(false), or otherwise involves threading?  For example, if you make a call to HttpClient.GetStringAsync, even if you await that without ConfigureAwait or with ConfigureAwait(true), you're still very likely going to be doing work on other threads as part of the operation.  It seems like the requirement is really that you shouldn't be calling any async or threading-related APIs, and trying to flag use of ConfigureAwait and suggesting it be true is too little too late?
