### ISSUE TITLE
Calling GetType on resource from loaded assembly returns type from currently executing runtime version, not the assembly target runtime version

### ISSUE THREAD

**Issue by ericcdub** [dotnet/runtime#78436]
### .NET version

.NET6, .NET7

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

tl;dr Is there a way to accomplish creation of .NET6 satellite assemblies, using .NET7?

I'm trying to extract localisable resources from a .NET 6 assembly, using a .NET 7 class library, so I can create satellite assemblies for that assembly using that same library.

I'm not even sure at this point if it's possible to do, but I'm hoping it is because otherwise I'll have to build a different version of my class library to target each runtime version, and also add code to detect the incoming assembly version and instantiate the version of my class library which targets the same runtime as the assembly I'm trying to localise.

Assuming what I want to do is possible, when I load an assembly to be localised and extract the resources into a dictionary using ResourceReader, I extract the type information for each resource and store it so it can be written into a satellite assembly later on. However, I noticed that for certain reference and value type resources extracted from the assembly into the dictionary, such as Int32, System.Drawing.Size, System.String and others,  the type information returned by GetType() for the resources in the dictionary corresponds to that of the executing runtime, in this case, .NET7, whereas the assembly itself targets .NET6.

This is causing problems after I create the satellite assemblies, because when the newly localised assembly is trying to load the localised resources, it throws exceptions saying that binary serialization is not supported. I think this is a red herring, because when I looked into it further, the types that the runtime is trying to load from the satellite assembly are .NET7 types, so the .NET 6 runtime is unable to load those types.

Any help appreciated,

Thanks

### Steps to reproduce

Use ResourceReader to extract a dictionary of resources a .NET6 assembly, using .NET7.
Iterate over that dictionary and call GetType for each entry. 
You will see that each entry's type information corresponds to .NET7 types:

```
Stream ReadStream = myAssembly.GetManifestResourceStream(strAssemblyName);

if(null != ReadStream)
{
   using (DeserializingResourceReader reader = new DeserializingResourceReader(ReadStream))
   {
      foreach (DictionaryEntry entry in reader)
      {
	System.Type vValueType = entry.Value.GetType();
      }
   }
}

```

**Comment by vitek-karas** [comment]
The problem is that you're deserializing the data into real instances - those will have to be .NET 7 types if you're running .NET 7 runtime. And then when you're serializing (assuming - the code is not shown) you're passing in these instances. The serializer can't tell that you want different version - that information is basically lost - so it serializes the types it gets, which are .NET 7.

I can think of two possible solutions.

One is to always run this on .NET Framework - it will do the same thing as described above, but the difference is that for types which are part of the framework, there are facades in .NET 6/7/... to map the .NET Framework types to the respective .NET Core types. So the resource file serialized with .NET Framework is very likely readable by .NET 6/7 app (you would have to test this obviously).

Alternatively, do not deserialize into object instances, instead handle the raw data directly. You can use `ResourceReader.GetResourceData` to get the type name as a string (not resolved to the current runtime) and the value as a binary blob. You can then write these using `ResourceWriter.AddResourceData` which should preserve the same type name. (I didn't try this either though).

Note on netstandard2.1 - I don't think that would help, since the deserialization would still have to actually resolve the type names to the active framework, and again the version information (or that it was from netstandard) would be lost.

**Comment by ericcdub** [comment]
> The problem is that you're deserializing the data into real instances - those will have to be .NET 7 types if you're running .NET 7 runtime. And then when you're serializing (assuming - the code is not shown) you're passing in these instances. The serializer can't tell that you want different version - that information is basically lost - so it serializes the types it gets, which are .NET 7.
> 
> I can think of two possible solutions.
> 
> One is to always run this on .NET Framework - it will do the same thing as described above, but the difference is that for types which are part of the framework, there are facades in .NET 6/7/... to map the .NET Framework types to the respective .NET Core types. So the resource file serialized with .NET Framework is very likely readable by .NET 6/7 app (you would have to test this obviously).
> 
> Alternatively, do not deserialize into object instances, instead handle the raw data directly. You can use `ResourceReader.GetResourceData` to get the type name as a string (not resolved to the current runtime) and the value as a binary blob. You can then write these using `ResourceWriter.AddResourceData` which should preserve the same type name. (I didn't try this either though).
> 
> Note on netstandard2.1 - I don't think that would help, since the deserialization would still have to actually resolve the type names to the active framework, and again the version information (or that it was from netstandard) would be lost.

Thank you very much for that detailed reply. I think the second option is more feasible for us, but I will check both and let you know how I get on.

Thanks

**Comment by ericcdub** [comment]
Closing as I found the issue. 

In .NET 6 at least, ResourceWriter requires developers to add any instances whose types fall outside of a list to the writer using AddResourceData. AddResourceData requires an instance to first be serialized into a byte array beforehand, so I used BinaryFormatter, which having checked using DotPeek, adds lots of extra information into the resulting satellite assembly for each resource, compared to the main assembly. This was causing the main assembly to crash if the .NET runtime targeted by our code didn't match that of the assembly. 

The solution was to use PreserializedResourceWriter instead of ResourceWriter, and to call AddBinaryFormattedResource, passing in the binaryformatter-created byte array which holds the serialized version of our instances.
