### ISSUE TITLE
Performance Benchmark

### ISSUE THREAD

**Issue by weifenluo** [dotnet/runtime#78451]
Is there any open source performance benchmark repo to compare .Net JSON serializers including System.Text.Json? How STJ is tested for performance benchmark? I'm asking this question because I have written a custom serializer and would like to compare the performance with STJ (and others).

**Comment by gfoidl** [comment]
See https://github.com/dotnet/performance/tree/main/src/benchmarks/micro/Serializers

**Comment by eiriktsarpalis** [comment]
@gfoidl Note that the STJ benchmarks in that repo are designed to measure against earlier versions of itself and not against other serialization stacks. It might be worth including STJ in https://github.com/dotnet/performance/tree/main/src/benchmarks/micro/Serializers so that we have more up to date comparison data. @adamsitnik thoughts?

@weifenluo as it happens, I recently [ran benchmarks](https://gist.github.com/eiriktsarpalis/163ff9f44af1f22feb9935a2b379456c) comparing Json.NET with STJ (reflection & sourcegen) in .NET 7, using a typical POCO one might see in an application. Hope this helps in the meantime.

**Comment by adamsitnik** [comment]
> @adamsitnik thoughts?

Sounds good to me!
