### ISSUE TITLE
.NET 7 DateTime.AddXXX undocumented behaviour changes

### ISSUE THREAD

**Issue by pirrmann** [dotnet/runtime#78452]
### Description

"Enhance the date and time precision in Add methods" (https://github.com/dotnet/runtime/pull/73198) has indroduced changes in the behaviour of various DateTime.Add methods, where the values to add are not rounded to the nearest millisecond anymore.

The previous behaviour was less precise, but it has been there for a long time, and the change could break some of our code which expects that adding periods of time to a DateTime which is on a grid would stay on a millisecond grid.

Those changes have not been reflected in the documentation (for instance, see https://learn.microsoft.com/en-us/dotnet/api/system.datetime.addhours?view=net-7.0, where it still states that "The value parameter is rounded to the nearest millisecond."). There was a docs PR, but it has been closed and nothing has been updated (https://github.com/dotnet/dotnet-api-docs/issues/8292)

### Reproduction Steps

```
var start = new DateTime(641987360181930000L);
var end = new DateTime(651296593079000000L);
var span = end - start;
var windows = span.TotalHours / 2.0;
var computed = start.AddHours(windows * 2.0);
```

In .NET 6, `computed` is equal to `end`. In .NET 7, this is not the case anymore.

### Expected behavior

The input parameter for AddHours should be rounded to the nearest millisecond (if we believe the current documentation).

### Actual behavior

The input is not rounded to the millisecond anymore.

### Regression?

This is an undocumented change of behaviour, so it *could* be described as a regression

### Known Workarounds

Compute the number of rounded milliseconds, then use `AddMilliseconds` directly.

### Configuration

.NET 7.0 on Windows 10 Pro for Workstations version 22H2, 64-bit

### Other information

I think that the added precision should be an opt-in behaviour for non-precise overloads such as AddHours, and maybe enabled by default only for precise overloads such as AddMilliseconds, AddMicroseconds etc.

**Comment by tarekgh** [comment]
We have discussed that in the issue https://github.com/dotnet/dotnet-api-docs/issues/8292 and @tannergooding explained we don't need to change the docs there. You may reply on that issue if you disagree with what has been said there. Thanks for your report.

**Comment by pirrmann** [comment]
The conclusion was "Ok, let's keep it as it is for now and we can revisit if we get any complaints. I'll close this issue."

Now, I'm complaining that:
- not only the documentation is wrong (stating that the input is rounded to the nearest millisecond, when it's not rounded anymore)
- this change of behaviour is actually susceptible to introduce subtle bugs in client code (I already have failing tests in my projects to prove that)

Do you feel that having wrong documentation is "good enough"?

**Comment by tarekgh** [comment]
@pirrmann feel free to open a PR in https://github.com/dotnet/dotnet-api-docs/ suggesting the change and we can discuss the details on that PR. sounds good?

**Comment by pirrmann** [comment]
If my concern was only about the documentation, then I'd be happy to open the PR and continue the discussion there. However, my concern is mostky about the change in behaviour, not about the documentation:

If I evaluate the code `(new System.DateTime(2022, 1, 1)).AddHours(9.2).ToString("hh:mm:ss.ffffff")` in .NET 6.0 and 7.0, I get:

| 6.0 | 7.0 |
|---|---|
| 09:12:00.000000 | 09:11:59.999999 |

This is what my concern is about.

**Comment by tarekgh** [comment]
@pirrmann the change was intentional, and we have done it because users were complaining about the old behavior. So, it is an improvement for old behavior. We have enhanced the precisions in other types in previous releases too (like with TimeSpan). We understand this change will produce different results than before. From your issue title it is suggest the concern was this change is undocumented. Could you please clarify what exactly you are asking here? Are you asking to document the change of behavior? If so, we can do that.

**Comment by pirrmann** [comment]
I've created a PR (https://github.com/dotnet/dotnet-api-docs/pull/8641) to document the new behaviour, but I still think that the rounding logic should be improved in the runtime itself...

**Comment by tarekgh** [comment]
@tannergooding what you think about @pirrmann suggestion https://github.com/dotnet/runtime/issues/78452#issuecomment-1317639671?

**Comment by tarekgh** [comment]
Thanks @pirrmann for the PR.

**Comment by tannergooding** [comment]
> Because (long) 0.99 truncates and evaluates to 0, I would suggest adding back the (value >= 0 ? 0.5 : -0.5) in order to have:

This is making an assumption that `doubles` follow normal decimal-based math rules, but they do not. If any rounding needs to happen, it should be done explicitly via `Math.Round`.  However, this can also be problematic in some cases and lead to other undesired or unexpected behaviors due to `double` being a `binary floating-point` format.

**Comment by tannergooding** [comment]
The easiest solution here would be to have an analyzer that warns users typing double/float literals that `9.2` is actually `9.199999999999999289457264239899814128875732421875`.

The next best "fix" would be to expose overloads that take `decimal` and/or `integers` to help avoid any implicit rounding or misrepresentation of values. `Integers` would be fast, `decimal` would be slow.

**Comment by pirrmann** [comment]
> > Because (long) 0.99 truncates and evaluates to 0, I would suggest adding back the (value >= 0 ? 0.5 : -0.5) in order to have:
> 
> This is making an assumption that `doubles` follow normal decimal-based math rules, but they do not. If any rounding needs to happen, it should be done explicitly via `Math.Round`. However, this can also be problematic in some cases and lead to other undesired or unexpected behaviors due to `double` being a `binary floating-point` format.

This technique was good enough when rounding to the millisecond, but now it's not good enough anymore when we want to round the tick instead? 

`9.199999999999999289457264239899814128875732421875` has more than enough precision to compute accurate ticks, which are only 10e-7 seconds, but at the moment we're simply dropping the last digits. For that specific example of 9.2 hours, `fractionalPart * ticksPerUnit = 7199999999.99997` and were converting it to `7199999999` instead of `7200000000`.

**Comment by pirrmann** [comment]
As an ever more significant example:
`System.DateTime(2022, 1, 1).AddMicroseconds(9.2).Ticks' evaluates to `637765920000000091` instead of `637765920000000092`.

Do you still think that this is correct, and a sane behaviour to expect?

**Comment by tannergooding** [comment]
> This technique was good enough when rounding to the millisecond, but now it's not good enough anymore when we want to round the tick instead?

It was not good enough, it was riddled with bugs and unexpected behavior for other inputs and is part of the reason the behavior was fixed.

> 9.199999999999999289457264239899814128875732421875 has more than enough precision to compute accurate ticks, which are only 10e-7 seconds, but at the moment we're simply dropping the last digits. For that specific example of 9.2 hours, fractionalPart * ticksPerUnit = 7199999999.99997 and were converting it to 7199999999 instead of 7200000000.

There is much more to this than simply how many numbers are visible in the `double`.

A double can accurately represent around 15-17 decimal digits (although even this is a bit hand wavy). Anything more than this is data that may exist but which may not be correct (this is similar in premise to how we can claim `millisecond` level accuracy, but can track 100 nanosecond ticks).

What this means is that when you factor in scaling and other bits there can be error introduced and the naive algorithm is likely not trivially correct. 

We could do 100% accurate interpretation of the `double` input, but that leads to unacceptable perf regressions.

Likewise, we don't want to force an artificial rounding to make some results look "pretty" because it loses important import data in other cases and leads to even more inaccurate results in others.

> As an ever more significant example:
System.DateTime(2022, 1, 1).AddMicroseconds(9.2).Ticks evaluates to 637765920000000091 instead of 637765920000000092.

This is a case where correctly handling it is difficult due to the performance loss required to get it correct across all scenarios.

`double` is a binary based type and so it can only exactly represent values that are a multiple of a power of 2. This is why `9.2` isn't representable and it's actually `9.199999999999999289457264239899814128875732421875`. This is likewise why scaling this by `10` gives you `92`, not `91.99999999999999289457264239899814128875732421875` and why scaling `0.199999999999999289457264239899814128875732421875` by `1000` gives you `1999.999999999992951416061259806156158447265625`.

The "loss of precision" can be introduced at any operation and the exact scenarios where the decimal digits are exactly preserved vs lost is dependent on the inputs to the operation.

The way we have it setup is accurate to the millisecond level of the exact represented input given, but may lose precision at the microsecond or nanosecond level (and yes, this is to the 100ns level since that's all a tick can represent).

Developers who want exact results and who are fine with slower computation can directly add ticks themselves, call multiple independent `Add*` functions using only integral inputs less than `2^53`, etc

We could likewise look at providing a `decimal` based overload that is slower but doesn't have these same representation issues. Similarly we could expose an analyzer to help flag to users "hey, `9.2` is actually `9.199999999999999289457264239899814128875732421875`"

**Comment by pirrmann** [comment]
I'm very well aware that there can be a loss of precision with double,
please stop trying to explain me how double works...

At the moment you're doing an effort to split the double between integer
ant fractionnal part, in order to achieve maximal precision, and then you
drop all digits after the tick, without even trying to round? How does that
make any sense? All your explanations are focused on double precision when
here the error is in the cast to long, not the double representation.

Now, you're saying that my suggestion of adding 0,5 to the double before
casting to long leads to bugs and unexpected behaviours. Could you point me
to any?

Le jeu. 17 nov. 2022 à 16:27, Tanner Gooding ***@***.***> a
écrit :

**Comment by isaacabraham** [comment]
> The easiest solution here would be to have an analyzer that warns users typing double/float literals that

C# only.
