### ISSUE TITLE
Why aren't operators overloaded for Vector and Matrix?

### ISSUE THREAD

**Issue by CeSun** [dotnet/runtime#78483]
After overloading operators, developers can handle vectors and matrices more like numbers.
What is the reason for doing this now?

**Comment by tannergooding** [comment]
Could you elaborate and give an example of what you mean?

The vector/matrix types expose a significant number of operators.

**Comment by CeSun** [comment]
> Could you elaborate and give an example of what you mean?
> 
> The vector/matrix types expose a significant number of operators.

Hello~, 
like this:
```csharp
  var matrix = Matrix4x4.CreateTranslation(new Vector3 { X = 200 });
  var position = new Vector3(100, 0, 0);

  // I want to do this:
  // var TargetPosition = position * matrix;

  // But i can only do this:
  var TargetPosition = Vector3.Transform(position, matrix);
```

**Comment by svick** [comment]
@CeSun [`Vector3` does have overloaded operators](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.vector3?view=net-7.0#operators), but not one for multiplying `Vector3` with a `Matrix4x4`. Which makes sense to me, since `Transform` is not just a matrix multiplication (you can't multiply a length 3 vector by a 4x4 matrix).

**Comment by CeSun** [comment]
> [does have overloaded operators](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.vector3?view=net-7.0#operators), but not one for multiplying `Vector3` with a `Matrix4x4`. Which makes sense to me, since `Transform` is not just a matrix multiplication (you can't multiply a length 3 vector by a 4x4 matrix).

The operators of vector4 and matrix4x4 also do not have

**Comment by dakersnar** [comment]
Thanks for the suggestion.

> Why aren't operators overloaded for Vector and Matrix?

I don't think there is a particular reason why these APIs don't currently exist in .NET. However, I think the reverse is a more important question to answer: why _should_ the operators you bring up be overloaded?

If you believe this is a common enough situation to be worth adding these new APIs, feel free to open a new issue that follows the API suggestion template. Our API review process and a link to the template/good example is here:  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps.

As this issue is not actionable, I'm closing it for now.
