### ISSUE TITLE
FreeBSD build break with cmake version 3.25.0

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#78528]
## Repro

Try to build the repo using latest mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-freebsd-12 image

## Result:

Build breaks (src/native/libs/System.Native/pal_networkstatistics.c(430,16): error G3B749D71: (NETCORE_ENGINEERING_TELEMETRY=Build) assigning to 'struct inpcb' from incompatible type 'struct xinpcb')

Context https://github.com/dotnet/runtime/issues/78522

Revert https://github.com/dotnet/runtime/pull/78526 as part of fixing this issue.

**Comment by jkotas** [comment]
It sounds like cmake 3.25.0 has `LINUX` variable set to 1 by default. It makes the build scripts think that we are building for Linux even though we are actually building for FreeBSD.

**Comment by jkotas** [comment]
@am11 Would you be interested in looking into what's the best way to fix this? Thank you!

**Comment by am11** [comment]
I'll take a look. We had a similar issue with new image of illumos https://github.com/illumos/sysroot/issues/3, due to libz package built against newer kernel than the toolchain, so instead of building libz manually in build-rootfs, I pinned the container to May 2022 image while waiting for their new release.
