### ISSUE TITLE
CVE-2022-3786 - Any impact?

### ISSUE THREAD

**Issue by kudlatiger** [dotnet/runtime#78536]
As there is a vulnerability, https://nvd.nist.gov/vuln/detail/CVE-2022-3786

We would like to know if there is any impact on `System.Security.Cryptography` library from .NET?

**Comment by bartonjs** [comment]
That CVE does not directly apply to .NET.

.NET on Linux does use OpenSSL from the underlying OS.  If you are using .NET 6 or .NET 7 (or current builds out of main) on a Linux/FreeBSD system that has OpenSSL 3.0.x installed, and that library is older than 3.0.7, then an application _might_ be vulnerable.

To my casual inspection, the affected area is not used by .NET, but I might have missed something.  

Since we don't static-link or redistribute OpenSSL any potential threat is remediated by applying OS security updates (or, if you built OpenSSL 3 yourself, pulling the upstream patches).
