### ISSUE TITLE
Reusing RC2 CryptoDecryptor with the combination of DeflateStream causes invalid reads starting from net6.

### ISSUE THREAD

**Issue by Tomius** [dotnet/runtime#78569]
### Description

The code sample in the Reproduction Steps section runs fine with all versions up to net5, but starts to generate invalid reads from net6.

### Reproduction Steps

Run the following code with net6 or net7:

``` c#
using System.IO.Compression;
using System.Security.Cryptography;

public class Program
{
    public static void Main()
    {
        var symmetricAlgorithm = new RC2CryptoServiceProvider { Key = new byte[16], IV = new byte[8], };
        var encryptor = symmetricAlgorithm.CreateEncryptor();
        var decryptor = symmetricAlgorithm.CreateDecryptor();
        if (!decryptor.CanReuseTransform)
        {
            throw new Exception("This code relies on UniversalCryptoDecryptor.CanReuseTransform being true");
        }

        var payload = new byte[] { 5, 6, 7, 8, 9, 10 };
        var encodedMessage = EncodedAndEncrypt(encryptor, payload);

        DecodeAndDecrypt(encodedMessage, decryptor, new byte[payload.Length]);
        DecodeAndDecrypt(encodedMessage, decryptor, new byte[payload.Length]);
    }

    private static byte[] EncodedAndEncrypt(ICryptoTransform encryptor, byte[] payload)
    {
        using var stream = new MemoryStream();
        using var encryptStream = new CryptoStream(stream, encryptor, CryptoStreamMode.Write);
        using (var compressStream = new DeflateStream(encryptStream, CompressionMode.Compress))
        {
            compressStream.Write(payload);
        }

        var encodedMessage = stream.ToArray();
        return encodedMessage;
    }

    private static void DecodeAndDecrypt(byte[] encodedMessage, ICryptoTransform decryptor, byte[] decodedMessage)
    {
        using var stream = new MemoryStream(encodedMessage, 0, encodedMessage.Length);
        using var encryptStream = new CryptoStream(stream, decryptor, CryptoStreamMode.Read);
        using var compressStream = new DeflateStream(encryptStream, CompressionMode.Decompress);

        ReadUntilEnd(compressStream, decodedMessage);
    }

    private static void ReadUntilEnd(Stream compressStream, byte[] decodedMessage)
    {
        int numRead = 0, current;
        do
        {
            current = compressStream.Read(decodedMessage, numRead, decodedMessage.Length - numRead);
            numRead += current;
        } while (current != 0 && numRead < decodedMessage.Length);
    }
}

```

### Expected behavior

The program runs without exception (this is the behavior until net5).

### Actual behavior

An exception is thrown:

```
Unhandled exception. System.IO.InvalidDataException: The archive entry was compr
essed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 lengt
h, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int3
2& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] buffer, Int32 offset, Int3
2 count)
   at Program.ReadUntilEnd(Stream compressStream, Byte[] decodedMessage) in C:\U
sers\t.csala\RiderProjects\ConsoleApp1\ConsoleApp1\Program.cs:line 50
   at Program.DecodeAndDecrypt(Byte[] encodedMessage, ICryptoTransform decryptor
, Byte[] decodedMessage) in C:\Users\t.csala\RiderProjects\ConsoleApp1\ConsoleAp
p1\Program.cs:line 42
   at Program.Main() in C:\Users\t.csala\RiderProjects\ConsoleApp1\ConsoleApp1\P
rogram.cs:line 20
```

### Regression?

Yes, the issue only happens starting from net6

### Known Workarounds

If the UniversalCryptoDecryptor is not reused, then there isn't any problem.

### Configuration

I ran on Windows x64, but the configuration is probably not very relevant. 

### Other information

The `UniversalCryptoDecryptor`  is a reusable Transform.

Normally at the end of the reading of a message,  the `TransformFinalBlock` is called on Transform, and so it finishes in a "clean state", where its `_heldoverCipher` buffer is empty.

However when combined with a `DeflateStream` and a payload whose size is not a multiple of 4 bytes, I find that the `TransformFinalBlock` is never called, and so at the start of the second Decrypt there are still left over bytes in the  `_heldoverCipher` buffer from the previous read (see [code](https://github.com/dotnet/runtime/blob/ae24a8f8dd745e24384f19c22f85b28aa1f33cd6/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/UniversalCryptoDecryptor.cs#L44)), which passes invalid values to the `DeflateStream` and causes it to blow up with an exception.

**Comment by vcsjones** [comment]
This seems to be an interesting interaction between `DeflateStream` and `CryptoStream`. With `CryptoStream`, I think the current contract requires calling `Read` on it until it returns 0 in order for `TransformFinalBlock` to get called and for things to get flushed out.

But `DeflateStream` knows whether it or not it needs more input so it might skip reading as soon as it has all of the information it needs.

https://github.com/dotnet/runtime/blob/3cfd6cffc495e4539bf6cdb5919922b8d8972e57/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L269-L277

So it never makes the read to `CryptoStream`.

One way to fix this is to issue an empty `Read` to `CryptoStream` after the `ReadUntilEnd`.

```C#
private static void DecodeAndDecrypt(byte[] encodedMessage, ICryptoTransform decryptor, byte[] decodedMessage)
    {
        using var stream = new MemoryStream(encodedMessage, 0, encodedMessage.Length);
        using var encryptStream = new CryptoStream(stream, decryptor, CryptoStreamMode.Read);
        using var compressStream = new DeflateStream(encryptStream, CompressionMode.Decompress);
        ReadUntilEnd(compressStream, decodedMessage);
        encryptStream.Read(Span<byte>.Empty);
    }
```

This feels somewhat related to #76948.

**Comment by bartonjs** [comment]
Before looking at the technical aspects here, note that it's a bad idea (in general) to encrypt after compression.  See the [CRIME](https://en.wikipedia.org/wiki/CRIME) and [BREACH](https://en.wikipedia.org/wiki/BREACH) vulnerabilities.  Also, RC2 is a horribly out of date algorithmic choice.

From a technical perspective, this is just a perfect storm:

* The compression of those 6 bytes is an anti-compressed 8 bytes.
* 8 bytes is the block size of RC2.
* The full RC2-CBC-PKCS7 flow turns into 16 bytes: `[one encrypted block][one pure padding block]`

When reading it back:

* You ask DeflateStream to read up to 6 bytes, since you already know the answer.
* It has no data, so it asks the underlying stream for data
* DeflateStream asks CryptoStream to read up to 8192 bytes
* CryptoStream has no pending data, so it asks MemoryStream for up to 8192 bytes
* MemoryStream gives all 16 bytes it has.
* CryptoStream asks the transform to process 16 bytes
* Depadding is required, so the last 8 bytes are held as reserve, they might be the padded block.
  * As it turns out, they are.
* The first `16 - 8 => 8` bytes can be processed, though.
* The 8 bytes are decrypted, there's no padding (not the last block), so return them.
* DeflateStream sees that those 8 bytes moved the zlib-interpreter to a terminal position, so it emits the 6 bytes it already produced and exits.
  * At this point I believe any further calls will also do no work.
* We're done.  No one ever asked for the next (last) block to be processed, so we still have state.

The next time around:

* You ask DeflateStream to read up to 6 bytes, since you already know the answer.
* It has no data, so it asks the underlying stream for data
* DeflateStream asks CryptoStream to read up to 8192 bytes
* CryptoStream has no pending data so it asks MemoryStream for up to 8192 bytes
* MemoryStream gives all 16 bytes it has.
* CryptoStream asks the transform to process 16 bytes
* The transform sees it has 8 bytes of data left over from the last call (it has no idea we're in a different context), so it decrypts that (which turns into `{ 0, 0, 0, 0, 0, 0, 0, 0 }`).  It probably also decrypts the next 8 bytes, and holds the last 8 again.
* DeflateStream gets upset with processing all those zeroes and throws an exception.

Basically, these two things are never going to play well together in read mode, unless you can guarantee that Deflate never wrote anything that was an integer multiple of the block size.  You'll pretty much be forced to use a new decryptor instance each time when using it in conjunction with DeflateStream.  (Write mode is fine, since the stream cascade close is the signal to do TransformFinalBlock)
