### ISSUE TITLE
Quic listen internal error

### ISSUE THREAD

**Issue by pepone** [dotnet/runtime#78573]
If a program calls Quic.ListenAsync twice with the same address, the second call fails with an internal error.

```
Unhandled exception. System.Net.Quic.QuicException: An internal error has occurred. ListenerStart failed: Unknown (0x5b)
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.QuicListener.ListenAsync(QuicListenerOptions options, CancellationToken cancellationToken)
   at Program.ListenAsync() in /home/jose/quic-listen/Program.cs:line 20
   at Program.Main() in /home/jose/quic-listen/Program.cs:line 16
   at Program.<Main>()
```

See the test case at https://github.com/pepone/quic-listen-address-in-use

I find this unexpected, when each listener is created by a separate process you don't get any error (see https://github.com/microsoft/msquic/issues/3177) why is this different if both are created in the same process?

Also using `InternalError` seems to indicate this is an unexpected condition.

Dotnet Info

```
jose@ubuntu22:~/quic-listen$ dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /opt/dotnet-7.0/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/opt/dotnet-7.0/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/opt/dotnet-7.0/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/opt/dotnet-7.0/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet/dotnet6-6.0.110]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by wfurt** [comment]
What version of libmsquic do you have? The `InternalError` is unfortunate and also depends on you ALPN setting. Check https://github.com/dotnet/runtime/pull/73072 and https://github.com/dotnet/runtime/issues/73045 for more background.

**Comment by pepone** [comment]
> What version of libmsquic do you have? 

libmsquic/jammy,now 2.1.4 amd64

**Comment by rzikm** [comment]
0x5b is the error code for QUIC_STATUS_ALPN_IN_USE, you may not start two listeners on the same port with overlapping ALPNs (but you can start two with disjoint ALPN sets). This has been fixed by https://github.com/dotnet/runtime/pull/74754 for 8.0. Since that is an API change (adding a `QuicError` enum member), we can't backport it to 7.0 as a whole. But maybe we could port a part of it that improves the exception message. Thoughts? @wfurt?

> I find this unexpected, when each listener is created by a separate process you don't get any error

That is unexpected, because you do get an exception with "Address already in use" on Windows in that case. But that is a behavior coming from the MsQuic library itself and we don't have control over it.

**Comment by ManickaP** [comment]
If I understand it correctly, the change for "ALPN_IN_USE" depended on changes in msquic. I assume the new QUIC_STATUS has a completely new number, so adding check for it and improving the message (https://github.com/dotnet/runtime/pull/74754/files#diff-51caac37827727f2963184c748e6fb36f66e8bf0be169b7647c2cb01b3526606R159) would help if you have msquic 2.1+, but be NOP in 2.1-. So we could safely backport this change to 7.0 and it would light up if you have higher version of msquic (relevant only for Linux, since on Windows it's us who ships the lib). Question is whether this meets the bar or not.

**Comment by ManickaP** [comment]
Triage: this issue is solve in main: https://github.com/dotnet/runtime/pull/74754, I'll close this for now. If this proves to be a problem for more customers on 7.0, we can port back the partial fix (without any API change) suggested by Radek.
