### ISSUE TITLE
Iterating large queue throws exception

### ISSUE THREAD

**Issue by AkiSakurai** [dotnet/runtime#78590]
### Description

Iterating large queue throw exception.

### Reproduction Steps

 ``` c#
 using System.Collections.Generic;
 using System;

 var queue = new Queue <int> ();
 queue.EnsureCapacity(Array.MaxLength);
 for (var i = 0; i < Array.MaxLength - 2; i++) {
   queue.Enqueue(i);
   queue.Dequeue();
 }
 for (var i = 0; i < Int32.MaxValue - Array.MaxLength + 4; i++) {
   queue.Enqueue(i);
 }

 var latest = 0;
 foreach(var i in queue) {
   latest = i;
 }
 Console.WriteLine(latest);

```

### Expected behavior

Do not throws exception.

### Actual behavior

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
```

**Comment by am11** [comment]
`foreach(var i in queue) {` line is throwing the exception (during `MoveNext`).

This expression overflows: https://github.com/dotnet/runtime/blob/6b170de3428356845261b0f025ed9153aa293f47/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Queue.cs#L465 `arrayIndex` becomes `-2147483648` on iterating the last (59<sup>th</sup>) index.

Current workaround is to call `ToArray()`, as in: `foreach(var i in queue.ToArray()) {` which  will make a copy of underlying storage (it's horrible, but better than being blocked 🙂).

> Regression?

No. This issue is also present in .NET 6.
