### ISSUE TITLE
Trying to send email to international email address

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78640]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Trying-to-send-email-to-international-em/10150605)._

---
Windows 2019 Server
.Net 4.8

I thought smtpClient.DeliveryFormat = SmtpDeliveryFormat.International; would solve it.

I am getting the following error message:

System.Net.Mail.SmtpException: The client or server is only configured for E-mail addresses with ASCII local-parts: {prefix}+JoséRamón@gmail.com.

If send to an email like [Redacted]@[Redacted] it works fine.

I am using Office 365's  SMTP Server.  When adding the POP/SMTP configuration to Outlook the email to {prefix}+JoséRamón@gmail.com, it works fine.

What about this code would prevent sending to an email address with accents?   Please let me know if any additional information is needed.   Thanks

```
                using (SmtpClient smtpClient = new SmtpClient(emailConfig.EmailServerName, emailConfig.EmailPort))
                {
                    smtpClient.EnableSsl = emailConfig.EmailUseSSL;
                    smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                    smtpClient.UseDefaultCredentials = false;
                    smtpClient.Credentials = new System.Net.NetworkCredential(emailConfig.EmailAccountUser, emailConfig.EmailAccountPassword);
                    smtpClient.DeliveryFormat = SmtpDeliveryFormat.International;

                    MailAddress from = new MailAddress(emailConfig.EmailAccount, String.Empty, System.Text.Encoding.UTF8);

                    List lst = new List();
                    string[] _arrsplit = sendTo.Split(';');
                    for (int i = 0; i < _arrsplit.Length; i++)
                    {
                        lst.Add(new MailAddress(_arrsplit[i].ToString()));
                    }

                    using (MailMessage message = new MailMessage())
                    {
                        message.From = from;
                        foreach (MailAddress m in lst)
                        {
                            message.To.Add(m);
                        }
                        message.IsBodyHtml = true;
                        message.Body = body;
                        message.BodyEncoding = System.Text.Encoding.UTF8;
                        message.Subject = subject;
                        message.SubjectEncoding = System.Text.Encoding.UTF8;
                        if (attachmentFile != null && attachmentFile.Length > 0)
                        {
                            Attachment atach = new Attachment(attachmentFile);
                            atach.Name = Path.GetFileName(attachmentFile);
                            message.Attachments.Add(atach);
                        }
                        smtpClient.Send(message);
                    }
                }
```

---
#### Feedback Bot on 9/19/2022, 01:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ManickaP** [comment]
The UTF-8 support depends on the server capabilities as well, your server must support SMTPUTF8 extension: https://www.rfc-editor.org/rfc/rfc6531.html#section-3.2

Could you try to get a network capture from the connection initialization between the client and server, to confirm my suspicion?

And why it works with different client, once again, just a suspicion, but it the other client might be using A-label encoding of the name: https://www.rfc-editor.org/rfc/rfc5890.html#section-2.3.2.1. I.e. "xn--" followed by "punycode" name: https://www.rfc-editor.org/rfc/rfc3492, which is not considered as internationalized.

Also be aware that `SmtpClient` is in maintenance mode only, moreover since you're on Framework 4.8.

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
I am the original poster from the Visual Studio Feedback site.   According to this SMTPClient is still supported through .Net 7.   I am going to test the situation now that I have converted the app to .Net 6.

More feedback to come.

https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-7.0

**Comment by wfurt** [comment]
It is supported but as @ManickaP  mentioned it is mostly in maintenance mode and it will get only critical fixes. (so as 4.8) 
```
$ telnet smtp.office365.com 587
Trying 52.96.166.50...
Connected to eat-efz.ms-acdc.office.com.
Escape character is '^]'.
220 MW4P220CA0004.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 22 Nov 2022 17:14:24 +0000
EHLO me
250-MW4P220CA0004.outlook.office365.com Hello [75.172.71.139]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
```

**Comment by wfurt** [comment]
AFAIK many users successfully used https://github.com/jstedfast/MailKit

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
@wfurt Thanks for the MailKit suggestion.   MailKit and SmtpClient seem to work well .Net 6.   However, not in .Net 4.8.   

When we first converted one of our applications to .Net 6, there was an issue in a decryption/decompression/base64 routine related to UTF.  I suspect there was an underlying UTF bug fixed between .Net 4.8 and .Net 6, which caused the base64 issue (since resolved) and resolved the international email with SmtpClient.
