### ISSUE TITLE
Enable baseline validation for packages introduced in .NET 7

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#78705]
The `System.Security.Cryptography.Cose` package contains a comment that we should enable package validation after a stable version has shipped.

Such as 

https://github.com/dotnet/runtime/blob/2ae7f5d42c817614839f3bf2e889981fdaa03631/src/libraries/System.Security.Cryptography.Cose/src/System.Security.Cryptography.Cose.csproj#L6-L8

Since .NET 7 has shipped, I assume we should enable validation at this point.

**Comment by radical** [comment]
Do you have link to examples in `dotnet/runtime` where we use baseline validation for packages? It could be useful for wasm ones too, IIUC.

**Comment by ViktorHofer** [comment]
It's automatically turned on for libraries that use packaging.targets because of this property: https://github.com/dotnet/runtime/blob/6a047a9aec7a36039cffac61186b04bd3f16dbe0/eng/packaging.targets#L4-L7

Ideally, every project would use packaging.targets but there are still a few pkgprojs that we first would need to migrate to normal .csproj/.proj NuGet Pack task based projects.
