### ISSUE TITLE
Blazor Wasm TimeZoneInfo.Local.GetUtcOffset is returning 7:53:00 in PST zone

### ISSUE THREAD

**Issue by WayneHiller** [dotnet/runtime#78721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.Net 7 Blazor Wasm

Calling TimeZoneInfo.Local.GetUtcOffset is returning 7:53:00 (PST Zone) in Chrome/Edge. 
Calling JS new Date().getTimezoneOffset() returns 480.

Logged to browser console from my app:
Is Daylight Savings: No
Daylight Savings Name: PDT
Time Zone Name: (UTC-08:00) America/Los_Angeles
UTC Offset: -07:53:00

### Expected Behavior

Should return -8:00:00?

### .NET Version

7.0.100

**Comment by WayneHiller** [comment]
It is working as designed on my system too now. Thanks for looking into it.

**Comment by Clockwork-Muse** [comment]
Note: The 7:53 offset is the original offset for dates in that zone before 1883, when time was based on local solar noon (usually).  All (almost?) timezones have these first adjustment offsets in their history, some much more recent (that I can recall, 1945).

If that showed up, it likely means that only the first zone entry was included in the zone data, instead of the latest (which is still wrong, for multiple reasons, but at least less-ish wrong).
