### ISSUE TITLE
Positional record cannot handle in-memory array configuration

### ISSUE THREAD

**Issue by wimoy** [dotnet/runtime#78771]
This bug repros in VS 17.4.0

```C#
using Microsoft.Extensions.Configuration;

// options1 has two values as expected.
var options1 = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string?>
    {
        ["Property:0"] = "value0",
        ["Property:1"] = "value1"
    })
    .Build()
    .Get<RecordOptions>();

try
{
    // Throws
    var options2 = new ConfigurationBuilder()
        .AddInMemoryCollection(new Dictionary<string, string?>
        {
            ["Property:0"] = "value0",
            ["Property:1"] = "value1"
        })
        .Build()
        .Get<PositionalRecordOptions>();
}
catch (Exception)
{
}

// options3 has FOUR values: "value0", "value1", "value0", "value1"
var options3 = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string?>
    {
        ["Property"] = string.Empty,
        ["Property:0"] = "value0",
        ["Property:1"] = "value1"
    })
    .Build()
    .Get<PositionalRecordOptions>();

Console.ReadKey(false);

public record RecordOptions
{
    public string[]? Property { get; init; }
}

public record PositionalRecordOptions(
    string[]? Property);
```

**Comment by tarekgh** [comment]
defining 

```C#
public record RecordOptions
{
    public string[]? Property { get; init; }
}
```

is worked fine because the defined record will be a class with a parameter-less constructor.  while defining the following record:

```C#
public record PositionalRecordOptions(string[]? Property);
```

not worked because this record will be a class with a constructor taking one parameter `string[]? Property`. The binding failed to bind the constructor parameter because there is no configuration section with name `Property`.

But when adding `["Property"] = string.Empty,` to the configuration, make the parameter binding work. The values will be set twice now. Once when creating the instance after binding the constructor parameter.  And again, when binding the properties.

**Comment by tarekgh** [comment]
Looking more at this issue, the current behavior is expected because it define the record as 

```C#
public record PositionalRecordOptions(string[]? Property);
```

To have the binding be able to create instance of this record, will need to invoke the constructor that is taking `string[]? Property` parameter. When there are no entries listed for this parameter in the configuration, you cannot assume will create the record using `null` for this parameter. The reason is the Record constructor didn't specify the default value. To make this work, set a default value to the parameter. 

```C#
public record PositionalRecordOptions(string[]? Property = null);
```
