### ISSUE TITLE
[API Proposal]: Allow Lazy<T> to be invalidated

### ISSUE THREAD

**Issue by jez9999** [dotnet/runtime#78770]
### Background and motivation

Quite often I'll use a `Lazy<T>` to lazily initialize data that is calculated from some other data.  However, that other data may get changed from time to time, at which point my `Lazy<T>` needs recalculating.  There should be a way to mark `Lazy<T>` as invalidated or 'dirty' such that the next `.Value` call will trigger another call to the factory, cache and return the new result.

### API Proposal

```csharp
namespace System;

public class Lazy<T>
{
    public void Invalidate();
}
```

### API Usage

```csharp
public class EntityValues
{
    public Lazy<string> LazyProperty { get; set; }

    private object _lkLazyLock = new();

    private string _baseProperty = "";
    public string BaseProperty
    {
        get
        {
            lock (_lkLazyLock)
            {
                return _baseProperty;
            }
        }
        set
        {
            lock (_lkLazyLock)
            {
                LazyProperty.Invalidate(); // Force recalculation based on the new value
                _baseProperty = value;
            }
        }
    }
}
```

**Comment by timcassell** [comment]
I don't think this is a good idea, as that would cause the delegate to have to be cached indefinitely, disallowing the GC to collect any closed over values. Why not just create a new Lazy instance?

**Comment by tannergooding** [comment]
I'd guess the reason is to avoid the extra allocation.

To that end, `Reset(Func<T> valueFactory, bool isThreadSafe)` might be a viable API, but it also itself has some threading concerns since the object is initialized already and could be concurrently accessed.

It's potentially something worth discussing further since that would avoid regressing how long the factory is cached, but I'm also not necessarily convinced its worthwhile and just allocating a new `Lazy<T>` is likely safer/easier
