### ISSUE TITLE
Process.GetProcessesByName() error on linux

### ISSUE THREAD

**Issue by killaragorn** [dotnet/runtime#78800]
### Description

Chrome Browser's  process name is chrome, but `Process.GetProcessesByName("chrome") ` return empty array.  
I need pass  "chrome --enable-crashpad" to get the right result.

### Reproduction Steps

var processes = Process.GetProcessesByName("chrome --enable-crashpad");

### Expected behavior

var processes = Process.GetProcessesByName("chrome");

### Actual behavior

...

**Comment by am11** [comment]
> Chrome Browser's process name is chrome, but `Process.GetProcessesByName("chrome") ` return empty array.

Did you have chrome browser running when it returned an empty array? If your user is not the owner of the process in question, it might not have permission to list it either. You can check it by iterating over `GetProcesses()`:

```c#
using System;
using System.Diagnostics;

foreach (Process process in Process.GetProcesses())
{
    // Console.WriteLine($"ID: {process.Id}, Name: {process.ProcessName}");

    if (process.ProcessName.StartsWith("chrome", StringComparison.OrdinalIgnoreCase))
                     // or .Contains
    {
        Console.WriteLine($"ID: {process.Id}, Name: {process.ProcessName}");
    }
}
```

>  I need pass "chrome --enable-crashpad" to get the right result.

1. `chrome --enable-crashpad` is a crash reporting process (usually running in the background). It does not represent the actual process running the browser tabs, i.e. it's probably not what you expected.
2. (a bit unconventional but) a process can change its own name after the launch, and the name itself can use hyphens like `example --arg`, which looks like the process name is `example` and its argument is `--arg`, but in fact, its name _is_ `example --arg`. It will cause the API such as `GetProcessesByName("example")` to return an empty array and `ProcessName` to return `example --arg` instead of `example`. Based on your description, it sounds like chrome's crash reporting tool does something like that.
    * e.g. on linux, you can test it with:
      ```c
      // mychrome.c

      #include <stdio.h>
      #include <string.h>
      #include <sys/prctl.h>

      int main (int argc, char *argv[])
      {
          char* processName = "mychrome --enable-crashpad";
          prctl(PR_SET_NAME, processName, NULL, NULL, NULL);
          sprintf(argv[0], processName);

          printf("Press any key to continue ...\n");
          getchar();
      }
      ```
      In first terminal: `cc  mychrome.c && ./a.out` (don't press any key)
      In second terminal: `ps uax` to find `mychrome --enable-crashpad`

**Comment by killaragorn** [comment]
sorry for the late reply。My English is poor, but i will try to explain clearly。
the htop result 
![image](https://user-images.githubusercontent.com/67131511/203926695-afc1f2b8-0bd4-4502-a42d-62eedb5bb61e.png)
the chrome process id is '2155', let see the /proc/2155/status content
![image](https://user-images.githubusercontent.com/67131511/203926929-cad480b1-9e71-4fb2-82c1-c4273469f6ce.png)

I think the actual process name is `chrome`, but the dotnet think it's name is `chrome --enanbl***`.
I also try `Process.GetProcesses()` the target process id `2155` ,it's name is 'chrome --enable***'.
There might be something wrong with the logic inside the dotnet process module.

**Comment by am11** [comment]
> let see the /proc/2155/status content

We don't use `/status` for name, we use `/cmdline` and fallback to `/stat`.

> There might be something wrong with the logic inside the dotnet process module.

Yes, it works fine under normal circumstances when process is not changing its title or arguments (which, as I said above, is unconventional thing to do.. but chrome does it anyway).

More specifically, the issue is when chrome changes its title, it does not insert NULL characters in between the process name and argument. We rely on that NULL character to be there (per the [manpage](https://linux.die.net/man/5/proc): `The command-line arguments appear in this file as a set of strings separated by null bytes ('\0'), with a further null byte after the last string. `): https://github.com/dotnet/runtime/blob/4f53c2f7e62df44f07cf410df8a0d439f42a0a71/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs#L295-L301

so when there is no NULL between the process name and its arguments, our assumption and calculation goes wrong from that point onward.

Unless area owners think it's not worth the trouble (cc @adamsitnik), we can make it robust for these corner cases. PRs are welcome.

**Comment by killaragorn** [comment]
ok. I will close this issue. thanks for your answer

**Comment by am11** [comment]
As a general improvement, one thing we could do is to early bail from `GetUntruncatedProcessName`:

`if (stat.comm.Length < 15) return stat.comm; // name was not truncated`
(before reading `/proc/<pid>/cmdline`)

it will fix this particular chrome issue. Note that `GetUntruncatedProcessName` has the same issue with chromium and other chrome (and electron) based apps, such as vscode, codium, and dozens of others. So this solution will only improve a few scenarios. Longer-than-fourteen-chars process names will suffer, but they are rare.

**Comment by stephentoub** [comment]
> So this solution will only improve a few scenarios. Longer-than-fourteen-chars process names will suffer, but they are rare.

What do other platforms do here? This is an area we don't need to innovate.

**Comment by am11** [comment]
Golang and node.js do not provide process module from standard libraries. I think the most popular package for node.js is `ps-list` and one from go is `go-ps`.

node.js:
```javascript
// file: testps.mjs

import psList from 'ps-list'

console.log((await psList())
  .filter(x => x.name.includes('codium'))
  .map(x => `ID: ${x.pid}, Name: ${x.name}`)
  .join('\n'));
```

```sh
# npm install ps-list
$ node testps.mjs
ID: 11785, Name: codium
ID: 11788, Name: codium
ID: 11789, Name: codium
ID: 11791, Name: codium
ID: 11818, Name: codium
ID: 11834, Name: codium
ID: 11856, Name: codium
ID: 11876, Name: codium
ID: 11889, Name: codium
ID: 11900, Name: codium
ID: 11916, Name: codium
```

golang:
```go
// file: testps.go

package main

import (
  ps "github.com/mitchellh/go-ps"
  "fmt"
  "strings"
)

func main() {
  processList, err := ps.Processes()
  if err != nil {
    fmt.Println("Failed to get processes")
    return
  }

  for x := range processList {
    var process ps.Process
    process = processList[x]
    if strings.Contains(process.Executable(), "codium") {
      fmt.Printf("ID: %d, Name: %s\n", process.Pid(), process.Executable())
    }
  }
}
```

```sh
# go mod init
# go mod tidy
$ go run testps.go
ID: 11785, Name: codium
ID: 11788, Name: codium
ID: 11789, Name: codium
ID: 11791, Name: codium
ID: 11818, Name: codium
ID: 11834, Name: codium
ID: 11856, Name: codium
ID: 11876, Name: codium
ID: 11889, Name: codium
ID: 11900, Name: codium
ID: 11916, Name: codium
```

and with `Process.ProcessName:

```
ID: 11785, Name: codium --ms-enable-electron-run-as-node .
ID: 11788, Name: codium --type=zygote --no-zygote-sandbox
ID: 11789, Name: codium --type=zygote
ID: 11791, Name: codium --type=zygote
ID: 11818, Name: codium --type=gpu-process --field-trial-handle=15444129778417464948,13321624767095949502,131072 --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --disable-color-correct-rendering --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files
ID: 11834, Name: codium --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=15444129778417464948,13321624767095949502,131072 --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=none --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --shared-files=v8_context_snapshot_data:100
ID: 11856, Name: codium
ID: 11876, Name: codium
ID: 11889, Name: codium
ID: 11900, Name: codium
ID: 11916, Name: codium
```
