### ISSUE TITLE
Generate Unsafe Span code for most of the looping

### ISSUE THREAD

**Issue by sirinath** [dotnet/runtime#78981]
Optimise most of the loops to be Unsafe Span loops then index bounds can be inferred at compile time so that one does not need use these for additional performance. 

If index bounds cannot be guaranteed at compile time, always generate span based loops.

**Comment by stephentoub** [comment]
The JIT already eliminates bounds checks where it can prove doing so is correct.

Can you elaborate on what you're hoping for? Repro?

**Comment by sirinath** [comment]
Can you close the performance gap with `MemoryMarshal.GetReference` + `Unsafe.Add` to access elements.

Anyway you write a loop the performance should be the same with the compiler doing the most appropriate optimisation, code transformation and code generation.

**Comment by stephentoub** [comment]
> What I am hoping for is to close the performance gap with MemoryMarshal.GetReference + Unsafe.Add to access elements.

What gap? Please share a concrete example. Thanks.

**Comment by sirinath** [comment]
Consider:

```csharp
for(int i = 0; i < items.Count; i++) {
   var item = items[i];
   // ...
}
```

and

```csharp
for(var item in items) {
   // ...
}
```

and

```csharp
var las = CollectionMartial.AsSpan(Items);
ref var e = ref MemoryMartial.GetReference(las);
for(int i = 0; i < las.Length; i++) {
   var item = Unsafe.Add(ref e, i);
   // ...
}
```

The performance is difference.

In the 1st 2 case the compiler should ideally optimise the code and generate the code equivalent in the 3rd case as they are effectively the same and the last case is more optimal.

**Comment by davidfowl** [comment]
@sirinath can you share performance numbers?

**Comment by jnyrup** [comment]
Given the timing it could be related to this new video from Nick Chapsas
https://youtu.be/cwBrWn4m9y8

**Comment by tannergooding** [comment]
For array and span the first two are already equivalent. The third option doesn't exist.

For other collection types, the first two may or may not be equivalent operations and its not something the JIT can trivially optimize since there may or may not be observable differences between the approaches. Either a handful of special types, like `List<T>`, would need to have very specific knowledge baked in or the JIT would have to do very complex and expensive analysis/inlining that spans a few different methods (`GetEnumerator`, `MoveNext`, `Current`) and the various state stored in the enumerator type to "prove" that they are truly "equivalent".

For the third case, using `CollectionsMarshal` is not equivalent and results in observably different behavior for cases where multithreading is involved. As such, it is not a safe optimization for the JIT to automatically perform.

In all the cases, the differences here don't matter for a majority of applications and contexts. This is largely only going to show up in hot paths where the bottleneck can be recognized as part of profiling the application to determine where extra care needs to be given. Developers who are writing perf oriented frameworks/libraries tend to be familiar with these differences and will tend to avoid the patterns that are "less efficient".

**Comment by tannergooding** [comment]
It's also worth noting that in many cases the second approach is not equivalent for other collection types. This is often due to the requirement that enumerators throw if the underlying collection is mutated while enumeration is ongoing. Hence the simple check of `if (_version != _list._version) { throw ...; }` is enough to make it observably different behavior and therefore not a safe optimization for a compiler to implicitly make.
