### ISSUE TITLE
System.IO.Ports.SerialPort has no IntelliSense documentation

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#79030]
### Description

The SerialPort class and its members are completely undocumented within Visual Studio.

### Reproduction Steps

* Install the System.IO.Ports NuGet package
* Create an instance of the SerialPort class
* Browse its members in the C# code editor

### Expected behavior

Some documentation

### Actual behavior

No documentation

### Known Workarounds

Probably some information can be found online

### Configuration

.NET 6.0 project, .NET 7.0 package, VS 2022 17.4.1 on Windows 10 x64

### Other information

Other inline documentation works great, from within the project and from other packages and the BCL

**Comment by krwq** [comment]
I confirm there is no intellisense data. I'm also not seeing XML docs in the code... cc: @carlossanlop

**Comment by krwq** [comment]
Per offline conversation with @carlossanlop that should work and we should be picking up xml docs from dotnet-api-docs. For some reason that's not happening. We should aim to fix this in 8.0 timeline.

**Comment by krwq** [comment]
@carlossanlop you mentioned offline this might be already fixed by unrelated PR of yours. Can you confirm?

**Comment by krwq** [comment]
FWIW it's still not showing for me:
![image](https://user-images.githubusercontent.com/660048/219043690-57f0a005-e4e3-4e2b-8804-31f697f0a801.png)

What's the timeline for the intellisense data to be uploaded assuming this is fixed already?

**Comment by carlossanlop** [comment]
I checked, and the System.IO.Ports assembly uses both `GeneratePlatformNotSupportedAssemblyMessage` and `IsPartialFacadeAssembly`, which are special cases that my unrelated PR did _not_ fix. We will address this at a later time.

**Comment by carlossanlop** [comment]
I tested the System.IO.Ports package in VS, and noticed that IntelliSense was still working in nuget package version `6.0.0-rc.1.21451.13` (published on Sept 14 2021), and stopped working in version `6.0.0-rc.2.21480.5` (published on Oct 12 2021).

This happened due to some refactoring changes in our infrastructure, either in https://github.com/dotnet/runtime/pull/58558 or in https://github.com/dotnet/runtime/pull/58011.

The current logic is broken for two scenarios: When the assembly generates "PlatformNotSupportedException", or when the assembly is a partial facade assembly. Unfortunately for System.IO.Ports, it enables both properties.

This is how we decide which intellisense xml we should ship to customers:

- We download the internal intellisense nuget package that gets built by dotnet-api-docs, which is currently our source of truth for documentation. For the specific date range mentioned above, we consumed the package we generated from RC1 bits, and we bumped it here: https://github.com/dotnet/runtime/pull/75582. Note that the documentation included in that package was correct: System.IO.Ports.xml contained all the expected documentation for that assembly, and I should mention that all newer intellisense packages we've generated since then contain the right information as well.
- We build the runtime libraries. The normal build process generates an intellisense xml file, but since it contains information from triple slash comments, and we don't consider it the source of truth yet, we replace that file with the equivalent xml file contained in the nuget package.
- After the infra refactorings mentioned above, it seems we stopped doing the xml substitution in OOB packages, and instead we just shipped the xml generated during the build, which, in the case of System.IO.Ports at least, it contains only information from exception resource strings, due to the PNSE property being enabled.
- My recent "unrelated PR" added a new property that can be used in src csproj files that are _not_ using PNSE or Facade assemblies, and use their own built xml instead of copying the one that comes from the nuget package. Adding this property to System.IO.Ports would not work since it generates only SR strings in the built xml.

So the next step is to figure out if it is possible to overwrite the xml generated by System.IO.Ports (and other OOB assemblies with a similar issue) with the dotnet-api-docs xml. There's a chance that this is another symptom of either the PNSE or the Partial Facades problem, which are not trivial to solve.

**Comment by carlossanlop** [comment]
We have fixed the underlying issue affecting OOB packages:

- main https://github.com/dotnet/runtime/pull/79134
- 7.0 https://github.com/dotnet/runtime/pull/82554
- 6.0 https://github.com/dotnet/runtime/pull/82562

The next time any of these affected OOB packages gets a servicing fix and we enable it for building, the intellisense xml will contain the full docs as expected.
