### ISSUE TITLE
Inconsistent ISO 8601 parsing between `DateTime` and `DateTimeOffset`

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/runtime#79131]
### Description

When parsing a `DateTimeOffset.UtcNow` to `ISO 8601` format, it does not convert the time zone component to `"Z"`, but `DateTime.UtcNow` does.

### Reproduction Steps

```c#
Console.WriteLine($"[{DateTime.UtcNow:O}]");
Console.WriteLine($"[{DateTimeOffset.UtcNow:O}]");
```

### Expected behavior

```log
[2022-12-02T02:25:12.3762910Z]
[2022-12-02T02:25:12.3774923Z]
```

### Actual behavior

```log
[2022-12-02T02:25:12.3762910Z]
[2022-12-02T02:25:12.3774923+00:00]
```

### Configuration

```log
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**Comment by Clockwork-Muse** [comment]
Because `DateTimeOffset` doesn't actually know about "time zone", and an offset of `00:00` is not a guarantee that you're in the UTC zone (there are multiple zones that have such an offset).

`DateTime`, in contrast, does know about "time zone" (sorta, and there are issues with the API because of that).

Note that the `u` specifier does coalesce `00:00` offsets to `Z`, but drops fractional seconds.
If you need both, you're going to need to construct it from a custom format string:

```cs
var dto = DateTimeOffset.UtcNow;
var offsetFormat = $"{dto:zzz}";
Console.WriteLine($"[{dto:yyyy-MM-ddTHH:mm:ss.fffffff}{(dto.Offset == TimeSpan.Zero ? "Z" : offsetFormat)}]");
```

**Comment by BrunoBlanes** [comment]
> Because DateTimeOffset doesn't actually know about "time zone", and an offset of 00:00 is not a guarantee that you're in the UTC zone (there are multiple zones that have such an offset).

I took a look at the source code and understood what you meant, however, since I asked for `UtcNow` and that does create a `DateTime` element which contains a `DateTimeKind` property, I would imagine that once I tried parsing, I would be able to confirm its kind.

```c#
public static DateTimeOffset UtcNow
{
    get
    {
        DateTime utcNow = DateTime.UtcNow;
        var result = new DateTimeOffset(0, utcNow);
        return result;
    }
}
```

I think it is worth adding a private read-only field to `DateTimeOffset` to check whether it was initialized as UTC time or not.

**Comment by Clockwork-Muse** [comment]
> I think it is worth adding a private read-only field to `DateTimeOffset` to check whether it was initialized as UTC time or not.

No.  The existence of `DateTimeKind` is actually a problem, and causes issues both in the current API (due to backwards compatibility concerns, because it didn't initially have it), and in the conceptual state of `DateTime` (for instance, calling `DateTime.Now` on a computer set to UTC does **not** give you a value with `DateTimeKind.Utc`).  Persisting the source type this way is perpetuating such an issue.  Note too that in many cases you may end up with UTC values with `DateTimeKind.Unspecified`, which would be a subtle source of bugs here.  That's beside the fact that changing output because of this would be a fairly large breaking change.

If you need to retain zone, you will be **far** better off using an actual `DateTimeZoned` type.  Which unfortunately we don't currently provide in the BCL - if you're doing any serious date/time work, you are advised to use NodaTime.

**Comment by BrunoBlanes** [comment]
I've been looking around for discussions on the matter and from what I could understand this has always been this way and is not worth the change. So as much as it pains to know this is the case and makes me want a fix for it so badly (even if via a new API), I'll live. So, feel free to close this issue.

**Comment by Joe4evr** [comment]
> So as much as it pains to know this is the case and makes me want a fix for it so badly (even if via a new API)

Check out NodaTime, then. If you need to do anything with dates and times that's more than taking the current time, you should be using NodaTime.

**Comment by tarekgh** [comment]
The replies of @Clockwork-Muse are correct. It is not good to add DateTimeKind to DateTimeOffset. Actually, DateTimeOffset is introduced mostly to solve the issues with DateTimeKind. You can work around this by doing something `new DateTime(DateTimeOffset.UtcNow.Ticks, DateTimeKind.Utc)` too.

I am closing this issue but feel free to send any question if you still have any.
