### ISSUE TITLE
Extra call in AppContext.BaseDirectory

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#79150]
### Description

https://github.com/dotnet/runtime/blob/47e26b2ed8639810fbed20391eeaa246e46f68f5/src/libraries/System.Private.CoreLib/src/System/AppContext.cs#L20-L26

In current implementation we call `GetData()` every time although there is already static `s_defaultBaseDirectory`.
I guess we can cache `GetData()` too.

### Regression?

No.

**Comment by DaZombieKiller** [comment]
Caching it would be a breaking change, because [you can change the value of `BaseDirectory` by calling `SetData`](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoagQQAd6BhCPDGBDAOgGUYMAIgEMMQgBQAiWgAVpAfSYB5AHIAVAKIANVXIBCtHurkCAkgCV1TVYrMBNCWgAEE3UIDOMAQEtYYDNABPRQA3GCgoLwATGAkASgBuaiIyAE4xBmZWdk4uVw9vX38oAITqIA).

**Comment by iSazonov** [comment]
I will not insist on breaking change, but it is surprising that a property defined only as `get` can mutate. At least this should be mentioned in the documentation.
