### ISSUE TITLE
Deadlock with ClientWebsocket and lock blocks/Lazy objects

### ISSUE THREAD

**Issue by jzatarain** [dotnet/runtime#79171]
### Description

I'm writing stress tests for an asp.net core app, and I'm calling and endpoint 500 times with a List of Task, and the endpoint that gets executed, creates websockets connections with the ClientWebsocket class.
After running the test, I noticed that ClientWebSocket.ConnectAsync never completed, and that was due to this connection being made within the method that creates the instance of a Lazy<T> with LazyThreadSafetyMode.ExecutionAndPublication as the mode parameter.

### Reproduction Steps

    public void Test()
    {
        var tasks = new List<Task<ExpectedResult>>();
        var amount = 500;
        for (var i = 0; i < amount; i++)
        {
            tasks.Add(AnHttpClientRequest);
        }
        Task.WaitAll(tasks.ToArray());
    }

    public ExpectedResult AnHttpClientRequest()
    {
        /*process request*/
        var wsClient = new Lazy<WSClient>(() => CreateClientWSConnection(), LazyThreadSafetyMode.ExecutionAndPublication);
        //return response of the obove process
    }

    public WSClient CreateClientWSConnection()
    {
         using (var ws = new ClientWebSocket())
         {
            ws.ConnectAsync(uri, CancellationToken.None)
                .ConfigureAwait(false)
                .GetAwaiter()
                .GetResult();
                switch (ws.State)
                {
                    case WebSocketState.Open:
                        return WSClientObj;
                }
         }
    }`

### Expected behavior

ws.ConnectAsync should connect to the websockets server.

### Actual behavior

ws.ConnectAsync never connects to the websockets server, and the List of Task ends up with 500 canceled Tasks.

### Regression?

Not sure, but I did see reports of similar situations in older versions of .net, and then some comments that it was rewritten for .net 6

### Known Workarounds

I changed the usage of Lazy<T> to lock(obj) blocks, and that fixed the problem, but the next time that an instance of ClientWebsocket was created to connect again, the issue appeared again, so I feel like there's a deadlock in that class.

Example:
`lock(someObj) { //usage of ClientWebSocket }`

### Configuration

6.0.9
Windows 10 enterprise v21H2
x64
I don't know

**Comment by stephentoub** [comment]
Can you please share a complete, minimal repro?  Your example above never actually touches `wsClient.Value`, for example, so it won't ever invoke the Lazy's initializer.  Thanks.

**Comment by jzatarain** [comment]
[ClientWebsocketTest.zip](https://github.com/dotnet/runtime/files/10168427/ClientWebsocketTest.zip)
@stephentoub attached a new project.
Just modify the URI used in the WeatherForecastController to something that you are able to connect.
I duplicated it with Test1.

**Comment by jzatarain** [comment]
Line 25 was an example of the connection working correctly; it should get stuck when the other tasks are trying to access the `WsClient` variable in `WeatherForecastController` at line 28, because they are waiting for `_wsclient` to be initialized, which is currently stuck in `WeatherForecastController` at line 46.

If you have other suggestions to create a similar test, that would also help.
Thanks.

**Comment by stephentoub** [comment]
This looks like a deadlock due to how the repro is implemented.  There are effectively 500 queued calls into WeatherForecastController.Get.  A thread pool thread picks up the first of those, runs Get, which in turn takes a lock and calls CreateClientWSConnection.  All of the other available thread pool threads also pick up the work items to call Get, and each of them ends up blocking waiting on that same lock, so now all of your thread pool threads are blocked on the same lock.  The thread pool will slowly inject additional threads as it sees everything is stalled, but the moment it injects another, that thread will dutifully pick off the next work item, which is another request to call Get, and it too will block. The only thing that will unblock these threads is CreateClientWSConnection completing, and it's waiting for a connection to be established.  But as part of establishing that connection, HttpClient queued a work item to the thread pool, and that work item is now stuck behind the remaining hundreds of calls to Get.  Thus the app has effectively deadlocked itself.
