### ISSUE TITLE
Make LINQ providers (Queryable) compatible with NativeAOT

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#79199]
The queryable LINQ operators are currently marked with [RequiresDynamicCode] (e.g. [Where](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/Queryable.cs#L47)), because their implementation [uses MakeGenericType](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/CachedReflection.cs#L1000). This makes them incompatible with NativeAOT.

In typical LINQ providers, the expression tree doesn't end up getting compiled and executed, but rather translated to something else (e.g. SQL); this means that the Types and MethodInfos in the tree are only there for the proper tree structure, and we don't need them to actually contain code. However, MakeGenericType and MakeGenericMethod are currently eager, and throw right away in NativeAOT if the native code isn't pregenerated.

To solve this, we'd need to be able to make **lazy** Types, MethodInfos, which only throw if a method/property is actually invoked on them. From a conversation with @jkotas, the eager behavior of the reflection types was done in order to provide fail-fast behavior to users; we could revisit this decision.

As an alternative, since Type/MethodInfo/PropertyInfo are abstract base classes, we could add lazy implementations of these. These implementations could either throw if code is invoked, or lazily call the real MakeGenericMethod when needed (which would fail in NativeAOT). Construction of these lazy types should be exposed as a new API, since LINQ providers such as EF would need to make use of them as well (otherwise LINQ providers would need to duplicate the lazy types internally).

Thanks for @jkotas for the suggestions and conversation. 

/cc @ajcvickers @AndriySvyryd

**Comment by jkotas** [comment]
The challenge is how to differentiate the Linq queries that are acting as a template for Linq providers like EF Core from the Linq queries that are going to be executed at runtime. We still want to have `RequiresDynamicCode` warning for the Linq queries that are executed at runtime. The warning is produced when as the query is being built today. If we made the clause building AOT compatible by constructing the required types lazily, where would the `RequiresDynamicCode` annotation moved for runtime execution so that the analyzers can still warn you?

> the expression tree doesn't end up getting compiled and executed, but rather translated to something else (e.g. SQL); this means that the Types and MethodInfos in the tree are only there for the proper tree structure, and we don't need them to actually contain code.

This problem may be actually another case for callsite rewriting that we are designing for make other ASP.NET dynamic patterns compatible with native AOT (@jaredpar has been working on the design). The idea is to allow source generators to replace the user-written code with a different code that is AOT compatible. For example, it can replace the call to the standard `IQueryable` `Where` method with a call to a different `Where` method that instantiates the generic types lazily, that is only usable as a template EF Core query and never executed at runtime, and that does not have the `RequiresDynamicCode` annotation.

**Comment by roji** [comment]
Yeah. My idea here was indeed to check RuntimeFeature.IsDynamicCodeSupported in the implementation of e.g. Queryable.Where, and return the lazy version accordingly. And yeah, `RequiresDynamicCode` is the problem here.

First, it doesn't seem right to warn about the LINQ provider requiring dynamic code via the queryable operators; the real question is whether the LINQ provider itself is compatible or not. For example, someone can just as well enumerate the query root without composing any operators on it:

```c#
_ = efcontext.Blogs.ToList();
```

There's no operator being composed in the query, although the LINQ provider may definitely not be AOT-compatible. This is maybe an edge case; but the interesting thing really is whether the provider requires dynamic code to execute the query rather than the detail of how the operators are created when composing them in the expression tree.

Unfortunately, given the design of it all - I'm not sure how that can be done; the LINQ provider is basically like an IEnumerable whose enumerator implementation needs dynamic code. There's simply no good place to handle this AFAICT. As far as I know there's no assembly attribute that can tell us whether a dependency has declared itself compatible with AOT (and which would activate the analyzer when building it), right?

Tagging @eerhardt too.

**Comment by jkotas** [comment]
> As far as I know there's no assembly attribute that can tell us whether a dependency has declared itself compatible with AOT 

There is not one today. I do not think it would help to solve this problem even if it existed. The analyzer that runs at publish time has to always analyze the whole app for the result to be meaningful.

**Comment by roji** [comment]
> I do not think it would help to solve this problem even if it existed. The analyzer that runs at publish time has to always analyze the whole app for the result to be meaningful.

Ah, I didn't have the right picture in mind (so I'm guessing that the warnings I'm getting while running the code are only a subset of the warnings I'd get at publish time, just like with trimming?).

If the entire app is analyzed at publish time, and an old LINQ provider package uses code generation somewhere, then won't that generate a warning in any case (since the provider code internally uses dynamic code generation without propagating `[RequiresDynamicCode]`)? If that's the case, that seems good enough (the user is notified the provider isn't compatible), and we don't need the warnings from the operators?

**Comment by jkotas** [comment]
There are no warnings at runtime. It is just going to crash or misbehave at runtime. We want to guarantee that there is always a warning at build time if the code crashes or misbehaves at runtime due to trimming or AOT problem.

You can move where warnings are reported by suppressing them in one place and reporting them at different place (typically earlier) instead. We use this strategy in the dotnet/runtime in some places. Here is one random example: https://github.com/dotnet/runtime/blob/8e2a059a1f5395aa7395b268ac57e5c5c23b7528/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs#L66-L69. Notice that there is `Justification` that explains why the warning suppression is sound.

> an old LINQ provider package uses code generation somewhere, then won't that generate a warning in any case (since the provider code internally uses dynamic code generation without propagating [RequiresDynamicCode])? If that's the case, that seems good enough (the user is notified the provider isn't compatible), and we don't need the warnings from the operators?

Can somebody use the operators with a LINQ provider that does not use any dynamic code? If the operators use the dynamic code and the warnings on them are suppressed, where is the warning going to be instead in this situation?

**Comment by roji** [comment]
> There are no warnings at runtime. It is just going to crash or misbehave at runtime. We want to guarantee that there is always a warning at build time if the code crashes or misbehaves at runtime due to trimming or AOT problem.

Right. But that's my point - if you use any LINQ provider the does dynamic code generation, don't you already get a build-time warning for the places where that provider does that? If so, that seems to remove the need for warnings from the construction of the operators (and indeed, the real problem isn't with them, it's with what the provider does with them - whether it compiles them or not).

> Can somebody use the operators with a LINQ provider that does not use any dynamic code? If the operators use the dynamic code and the warnings on them are suppressed, where is the warning going to be instead in this situation?

That's ideally the plan for EF Core 8.0 - no actual runtime code generation would take place (since it will have been generated at build time), but various expression tree processing must still occur (e.g. to generate SQL from that tree). For other providers which do use dynamic code, I'd expect the warning to come from the use of [`Expression<TDelegate>.Compile()`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.compile?view=net-7.0#system-linq-expressions-expression-1-compile), MethodInfo.Invoke, etc. In other words, move the warning from the construction of the LINQ operators to when code is actually invoked.

**Comment by jkotas** [comment]
> move the warning from the construction of the LINQ operators to when code is actually invoked.

We would also have to move the construction of the problematic generic types from the construction of the LINQ operators to when code is actually invoked. The construction of the operators would have to be switched to use place holders for generic types, and the actual generic types would get fully inflated only once the LINQ provider tries to compile or run the query.

**Comment by roji** [comment]
Yeah, that's exactly what I have in mind; the [construction](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/CachedReflection.cs#L1000) of the queryable LINQ operators would check RuntimeFeature.IsDynamicCodeSupported, and if it's false, return a lazy implementation of MethodInfo for Where.

Since others are going to need to do this as well (e.g. custom LINQ operators that EF providers), we'd ideally provide a runtime API that returns these (e.g. an overload of MakeGenericType/Method which accepts a lazy flag parameter)?

In a sense, this introduces a bit of AOT laziness around Type and MethodInfo (allow constructing them but not invoking stuff on them), specifically within the context of LINQ providers (because LINQ providers don't necessary execute the expressions). Of course, if we wanted to consider making Type/MethodInfo lazy in general in AOT, we wouldn't need this.

**Comment by roji** [comment]
I think that a runtime API is needed...

The problem is that (queryable) LINQ operators aren't a close set that comes only from from System.Linq.Expressions - EF adds some of its own (e.g. Include, AsNoTracking...), and I'm guessing other LINQ providers do this as well. It's possible for each LINQ provider to re-implement the lazy Type/MethodInfo internally and do the same thing, but that's not ideal... There may be other scenarios where someone needs to pass around e.g. a constructed Type, without code on it being actually invoked - so an API to produce a lazy version could be useful elsewhere as well.

But if the public API part blocks this in some way, then we can indeed copy-paste the runtime implementation into EF, at least as a first step.

**Comment by jkotas** [comment]
> if the public API part blocks this in some way, then we can indeed copy-paste the runtime implementation into EF, at least as a first step.

Yes, I think it would be better to avoid introducing public APIs as the first step, and instead prove that the whole scheme actually works first.

**Comment by vitek-karas** [comment]
I'm a bit confused about the proposed design. Specifically, we need to make sure that if the query provider actually invokes the `MethodInfo` it will produce a build-time warning. Currently the design for these things is that:
* Once there's a type system representation in existence (like `MethodInfo`) it is safely invocable.
* The warnings are generated at the point of obtaining the type system representation - so `GetMethod`, `MakeGenericMethod`, ...

If we use lazy implementations of the type system objects, that would get around the warnings generated at the entry point, but then such `LazyMethodInfo` would have to do something "dangerous" in its `Invoke`. The problem is that `Invoke` is virtual and currently the trimming system can't annotate one override as dangerous while keeping the abstract base method un-annotated. (The reasoning is that it's VERY hard to reason about virtual calls statically). Typically this is solved by "blaming the .ctor" - that is suppressing the warning in the override method and adding a `RequiresUnreferencedCode` (or the other attribtues) on the `.ctor` of the class. But this approach would not work in this case, we want the `.ctor` to be safe - that's the whole point of the "lazy" design.

My main question is - what static pattern would the trimmer look for to generate a warning that the query provider does "dangerous" things.

**Comment by jkotas** [comment]
I think `MethodInfo.Invoke` and other similar APIs would have to throw on the lazy Type and MethodInfos, and one would have to get the real Type or MethodInfo first in order to call `MethodInfo.Invoke`. The method to get the real Type and MethodInfo would be marked with `RequiresUnreferencedCode`/`RequiresDynamicCode`

**Comment by vitek-karas** [comment]
My understanding was that the `LazyMethodInfo.Invoke` would actually "Work" (as in it would get the real `MethodInfo` and call `Invoke` on it). Meaning the Query provider would not need to know about the "lazy" versions - they would be transparent. If the query provider knows about all this, then I agree it's the responsibility of the query provider to propagate the "dangerousness" correctly through its code.

**Comment by roji** [comment]
Sorry, my mental picture here was wrong, I was under the mistaken impression that MethodInfo.Invoke was annotated with `[RequiresDynamicCode]`. So yeah, non-AOT-compatible LINQ providers calling Invoke on these placeholders wouldn't generate a warning.

However... [Queryable.Where](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/Queryable.cs#L47) adds a node to the query expression tree, with the (constructed) MethodInfo node pointing to... itself (i.e. Queryable.Where). In other words, that MethodInfo really gets inserted into the expression tree only so that it can be identified by the provider and translated to something else (e.g. SQL). While technically possible, I can't imagine any valid scenario in which a LINQ provider would actually execute this MethodInfo. So while from a purely theoretical point of view, it's a MethodInfo that could be executed, in the specific context of queryable LINQ expression trees, that isn't something that happens.

If we're OK with this, then for the same reason, the placeholder MethodInfo that's inserted into the tree doesn't need to be lazy, and can just throw.

Otherwise, I can't see any other option except for a call-site-replacing source generator, as @jkotas suggested above - unless someone  has other ideas... The source generatorwould replace the Where calls with an alternate Where method, returning the placeholder. Aside from the general complexity and risk, this has the following issues:

* It would force all LINQ providers to have such a source generator in order to be AOT-compatible - even if they don't use any dynamic code and would otherwise be fine.
* Identifying the LINQ queries in user source code which need to be replaced is non-trivial. We have to do static LINQ query identification for EF in any case - since it's a code-generating LINQ provider - but providers which aren't wouldn't otherwise need to do this.
* If two LINQ providers are used in the same program, the source generator from one might interfere with queries from the other. Identifying LINQ queries which belong to a specific provider adds even more complexity, and makes the source generator provider-specific.

So I'm really hoping we can avoid the big hammer of a call-site-replacing source generator here, just in order to avoid a build warning which, thinking about it, is extremely unlikely to add any actual value.

**Comment by roji** [comment]
But the MethodInfo isn't Enumerable.Where (which filters out elements) - it's Queryable.Where, which adds a MethodCallExpression of itself onto the given queryable expression tree.

**Comment by vitek-karas** [comment]
Just for my own education - the whole `Func<...>(MyMethod).GetMethodInfo()` is basically a way to do something like `methodof(MyMethod)`, right? (so `ldtoken` followed by conversion from handle to `MethodInfo`). It seems wasteful as it requires delegate allocation... but I guess there's no better way currently.

**Comment by roji** [comment]
Exactly - @jkotas just said the exact same thing to me offline. Fortunately, there's already caching of the MethodInfo so the lookup is just a one-time thing per operator; and I'm not sure doing it via `new Func<...>.Method` is any slower than the current MakeGenericMethod technique (I'll benchmark).

**Comment by davidfowl** [comment]
This is a great discussion and outcome 😄
