### ISSUE TITLE
AsnEncodedData.Format return empty for CRL extension in Linux 

### ISSUE THREAD

**Issue by t-bzhan** [dotnet/runtime#79265]
### Description

AsnEncodedData.Format return empty for CRL extension in Linux with below code snippet:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System.Text.RegularExpressions;

namespace X509Extension
{
    class Program
    {
        static void Main(string[] args)
        {            
            var x509Cert = new X509Certificate2("cert.pem");
            var crlInfo = x509Cert.Extensions["2.5.29.31"];
            var crlDistribitionPoints = new AsnEncodedData(crlInfo.Oid, crlInfo.RawData).Format(true);
            Console.WriteLine(crlDistribitionPoints);
        }
    }
}

```

It works as expected in Windows which outputs:

> [1]CRL Distribution Point
>      Distribution Point Name:
>           Full Name:
>                URL=http://crl.globalsign.com/gsrsaovsslca2018.crl

However in Linux, it output nothing.

### Reproduction Steps

Repo attached: [X509Extension.zip](https://github.com/dotnet/runtime/files/10164753/X509Extension.zip)

### Expected behavior

The code snippet above should return the correct CRL info in Linux as in Windows

### Actual behavior

It returns empty.

### Configuration

> dotnet --info
> .NET SDK (reflecting any global.json):
>  Version:   6.0.403
>  Commit:    2bc18bf292
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  18.04
>  OS Platform: Linux
>  RID:         ubuntu.18.04-x64
>  Base Path:   /usr/share/dotnet/sdk/6.0.403/
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.11
>   Architecture: x64
>   Commit:       943474ca16
> 
> .NET SDKs installed:
>   6.0.403 [/usr/share/dotnet/sdk]

**Comment by vcsjones** [comment]
On macOS this outputs the hex string, which is the behavior for "I don't have special formatting rules for this". On Windows, is works as described. On Linux, it outputs a line feed (`\n`), which is somewhat interesting but likely "that's what OpenSSL told us it was". I can look in to it further to see if any exception is getting swallowed internally, which can sometimes be the cause of why empty things are returned from this API.

On a different note however, I would caution using `Format(..)` if you intend to parse or otherwise try to interpret the data, like extract the CRL URI. Different versions of Windows, OpenSSL, and the Managed version, and even the OS locale / language can affect the output of this API which can make it tricky to parse.

You can use the `System.Formats.Asn1` package to parse and read the `cRLDistributionPoints` extension, but it's somewhat non-trivial in effort to do. The RFC describes the ASN.1 syntax in section 4.2.1.13.

**Comment by vcsjones** [comment]
Okay, so the issue is our use of `BIO_gets`

https://github.com/dotnet/runtime/blob/e1081df6da8ffbe667a7ea909a154c5b59e86351/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/OpenSslAsnFormatter.cs#L63

We assume it is going to do the read all in one go. From the docs:

> Usually this operation will attempt to read **a line of data** from the BIO of maximum length size-1

So it reads a line and writes it to a buffer, but it didn't read it to completion. We basically need to do the equivalent of "keep reading in to the buffer until there is no more data to be read"*.

<sup><sub><sup>*</sup>The irony of this is not lost on me.</sub></sup>
