### ISSUE TITLE
[API Proposal]: Allow disabling cache for RSAKey class

### ISSUE THREAD

**Issue by chriskarlsson** [dotnet/runtime#79338]
### Background and motivation

In RSACryptoServiceProvider class there is a property called PersistKeyInCsp. We used this in order to disable pin caching on e.g. SmartCards. This property is missing on RSAKey class and there is no easy way of clearing the cache once a pin is added.

Not sure if this is even possible with the underlying implementation. But it is a bit frustrating in our use case.

### API Proposal

```csharp
namespace System.Security.Cryptography

public sealed partial class CngKey : IDisposable
{
    ...
    public bool PersistKey { get; set; }
    ...
}
```

### API Usage

```csharp
using var cng = x509Certificate2.GetRSAPrivateKey() as RSACng;
// Disable pin caching
cng.Key.PersistKey = false;
return cng.SignData(dataToSign, HashAlgorithmName.SHA512, RSASignaturePadding.Pkcs1);
```

**Comment by bartonjs** [comment]
`PersistKeyInCsp` on `RSACryptoServiceProvider` isn't about caching...  if it's set to `false` then when the RSACryptoServiceProvider object is disposed (or finalized) it asks the OS to **delete** the key.

That same functionality is already available in a much more straightforward manner on CngKey, you can just invoke the `Delete` method.

**Comment by bartonjs** [comment]
Digging deeper, it looks like there's no way to forcibly uncache the PIN unlock for the Microsoft Platform provider, except for a key created with the high protection policy (or deleting the key), which vaguely matches the docs:

https://learn.microsoft.com/en-us/windows/win32/seccng/key-storage-property-identifiers#NCRYPT_PIN_PROPERTY

> **NCRYPT_PIN_PROPERTY**
>
>    L"SmartCardPin"
>
>    A pointer to a null-terminated Unicode string that contains the PIN. The PIN is used for a smart card key or the password for a password-protected key stored in a software-based KSP. This property can only be set. **_Microsoft KSPs will cache this value so that the user is only prompted once per process._**

(emphasis mine)

Since the caching is from the underlying Windows API (and has no knobs), I'm going to go ahead and close this as not something we can make progress on.
