### ISSUE TITLE
JsonPropertyOrderAttribute doesn't work on property with JsonExtensionDataAttribute

### ISSUE THREAD

**Issue by azchohfi** [dotnet/runtime#79379]
### Description

When using JsonPropertyOrderAttribute in a property, as well as JsonExtensionDataAttribute, it is expected that the order is obeyed, but it is not the case.

### Reproduction Steps

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

var json = """
{
    "Anything": "abc",
    "Anything2": "def"
}
""";

var myClass = JsonSerializer.Deserialize(json, SourceGenerationContext.Default.MyClass);
myClass.NewPropertyAtTheEnd = "Hello, World!";

Console.WriteLine(JsonSerializer.Serialize(myClass, SourceGenerationContext.Default.MyClass));

class MyClass
{
    [JsonExtensionData]
    [JsonPropertyOrder(int.MinValue)]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyOrder(int.MaxValue)]
    public string? NewPropertyAtTheEnd { get; set; }
}

[JsonSourceGenerationOptions]
[JsonSerializable(typeof(MyClass))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}

```

### Expected behavior

JsonPropertyOrderAttribute works when used with JsonExtensionDataAttribute.

### Actual behavior

JsonExtensionDataAttribute seems ignored for the JsonExtensionDataAttribute property.

### Regression?

Not that I'm aware of.

### Known Workarounds

None.

### Configuration

DotNet 7.0.100

**Comment by eiriktsarpalis** [comment]
The current behavior is by-design, i.e. properties marked as extension data are always serialized at the tail end of an object regardless of their order (specified either implicitly via the declaration order of the properties or explicitly using `JsonPropertyOrderAttribute`). That being said, this is currently not documented, and we should make sure it is in the future.

Changing the behavior at this point would be a breaking change, since it would change the serialization order even for types not specifying `JsonPropertyOrderAttribute`.
