### ISSUE TITLE
.NET 7 - Process terminated. Error while reaping child. errno = 10

### ISSUE THREAD

**Issue by JaroslavMajera** [dotnet/runtime#79540]
### Description

Hello. We have a cloud docker microservice which runs headless chromium in process. When we switch to .NET 7 we have encountered _Process terminated. Error while reaping child. errno = 10_ during killing chromium process. We cannot reproduce this  behavior with .NET 6. I have prepared repro https://github.com/JaroslavMajera/DotNetReaper. 

Thanks

### Reproduction Steps

1. Prepare Dockerfile which periodically runs chromium or maybe something else which spawns child processes.
2. Start chromium process
3. Call Process.Kill a Process.WaitForExit()
4. Repeat

Source code: [DotNetReaper-main.zip](https://github.com/dotnet/runtime/files/10208347/DotNetReaper-main.zip)

### Expected behavior

No Exception and chromium is successfully killed 

### Actual behavior

Sometimes we get

`Process terminated. Error while reaping child. errno = 10
   at System.Environment.FailFast(System.String)
   at System.Diagnostics.ProcessWaitState.TryReapChild(Boolean)
   at System.Diagnostics.ProcessWaitState.CheckChildren(Boolean, Boolean)
   at System.Diagnostics.Process.OnSigChild(Int32, Int32)`

### Regression?

Cannot reproduce on .NET 6

### Configuration

- .NET 7
- Docker image mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim
- Chromium 108

**Comment by adamsitnik** [comment]
@tmds is there any chance you could take a look?

**Comment by tmds** [comment]
I haven't run the reproducer yet, but I think it's a regression caused by https://github.com/dotnet/runtime/pull/65061.

When the `dotnet` process runs as pid 1, it will reap also processes that are not direct children here:

https://github.com/dotnet/runtime/blob/e49d7ec7f04f84abc5b6ad35dd00b8d71347c811/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessWaitState.Unix.cs#L674-L680

Inadvertently, we're also reaping direct children, which then leads to the `FailFast`.

If you change your ENTRYPOINT so `dotnet` is no longer pid 1, the issue should disappear. Something like:

```
ENTRYPOINT ["/bin/sh", "-c", "dotnet DotNetReaper.dll"]
```

I'll work on a fix next week.
