### ISSUE TITLE
mcs /dumpMap has stopped working

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#79568]
`mcs.exe /dumpMap` has recently stopped working. It fails after printing 10~20 methods. I didn't get chance to debug thoroughly but seems related to recent changes in superpmi.

**Comment by kunalspathak** [comment]
@jakobbotsch - can you please take a look?

**Comment by jakobbotsch** [comment]
I guess we have to duplicate all of the printing logic in mcs to make this work.

**Comment by kunalspathak** [comment]
> I guess we have to duplicate all of the printing logic in mcs to make this work.

Why is that the case? Earlier it was shared logic with superpmi, right?

**Comment by jakobbotsch** [comment]
The previous logic sort of duplicates it here: https://github.com/dotnet/runtime/blob/b33aede9f365f9231108c2d9f26ad8955c4e36a1/src/coreclr/tools/superpmi/mcs/verbildump.cpp#L11-L110

The problem is it makes assumptions about what the context is storing for each parameter in the signature, which depends on exactly how the printing in the JIT works. But now that I look at it some more I think I probably just need to handle a few basic cases to make it work somewhat similar to before.
