### ISSUE TITLE
Regex never completes

### ISSUE THREAD

**Issue by Simon-Miller** [dotnet/runtime#79596]
### Description

under .NET 7 (maybe older) a regex that is parsing over text that doesn't match the pattern, which includes capture groups, never completes.

### Reproduction Steps

```
string killer = "            // NOTE: THIS IS SUPER IMPORTANT TO UNDERSTAND! - you're effectively passing through the desire to ask for permission\r\n";
var classModifiersRegex = new Regex("(([a-z]*) {0,})*(?:partial class )");
var result = classModifiersRegex.Match(killer);
```

### Expected behavior

a Match instance, or even NULL would be ok!

### Actual behavior

the regex seems to enter into an eternal loop of some kind - as there is NEVER a result returned.

### Regression?

Doesn't seem to work in any .NET version I've tried.

### Configuration

I've tried .NET 7
I've tried .NET Core 3.1
I've tried .NET Framework 4.6.1
Running Windows 11
X64

### Other information

The issue doesn't fail on all text that's passed into it.
But this is the first line (in a c# source code document) that fails.
Initially I tried parsing the whole file as a single string, but then decided to break is down to a reading lines of code in from the file one at a time. 
The regex in the example works just fine in JavaScript, as I tend to develop regex expressions using online tooling (regexpal.com)
I usually find a niggle or two translating to C#'s regex, but this is nasty!

**Comment by grbell-ms** [comment]
Workaround: use `RegexOptions.NonBacktracking`
```csharp
string killer = "            // NOTE: THIS IS SUPER IMPORTANT TO UNDERSTAND! - you're effectively passing through the desire to ask for permission\r\n";
var classModifiersRegex = new Regex("(([a-z]*) *)*(?:partial class )", RegexOptions.NonBacktracking);
var result = classModifiersRegex.Match(killer);
```

**Comment by stephentoub** [comment]
This regex leads to catastrophic backtracking; most any backtracking-based engine will have trouble with it.  Try it on regex101.com for example:
https://regex101.com/r/viShjG/1
You'll see with PCRE2, PCRE, JavaScript, Python, Java, and C# it leads to errors like:
"Catastrophic backtracking has been detected and the execution of your expression has been halted."
or
"Your expression took too long to finish and was terminated."

You can either change your expression to avoid such catastrophic backtracking, avoid input that could be problematic, or use a non-backtracking engine, such as by specifying RegexOptions.NonBacktracking in .NET 7.

> The regex in the example works just fine in JavaScript, as I tend to develop regex expressions using online tooling (regexpal.com)

I'm surprised by that.  When I try that expression with that input on that site, the page hangs, presumably because of that catastrophic backtracking:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/2642209/207619673-22c9fb77-a4ca-4711-a238-4ce8909a0edc.png">
