### ISSUE TITLE
COM Interop not working on Linux builds

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/runtime#7968]
I noticed this.. and got the exception...

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/RtType.cs#L4885

Will this be implemented in netcore 2.0?

current windows builds this works fine.

**Comment by obiwanjacobi** [comment]
I have a use case for RCW/CCW support on linux (mac). [My project](https://github.com/obiwanjacobi/vst.net/tree/master/Source3/Code) is bridge between an unmanaged (C++) plugin standard (Steinberg VST3) and a managed (.NET) plugin implementation and/or a managed host that can work with unmanaged VST3 plugins. Because the VST3 plugin interface is COM compatible I thought it would be quick to implement / marshal it with RCW/CCW (in-process). I have a minimal version working in Windows and it would be great if this could port (painlessly?) to linux. 
My current version of my project is a window-only implementation for VST2 (not COM related) and is being used by several hobbyists, but VST2 is not being supported anymore by Steinberg as of 2018. With more and more development on .NET Core -now .NET5- I was hoping support for VST3 would become feasible and give my users access to the current (VST3) plugin standard.

**Comment by Const-me** [comment]
@obiwanjacobi You can try my library, it implements COM interop for .NET core 2.1 or newer: https://github.com/Const-me/ComLightInterop

**Comment by obiwanjacobi** [comment]
> @obiwanjacobi You can try my library, it implements COM interop for .NET core 2.1 or newer: https://github.com/Const-me/ComLightInterop

Yeah I found it just after I was typing this. I have it on my list - currently low in spare time... Thanks!

**Comment by AaronRobinsonMSFT** [comment]
The first few steps of this support are done.
- Enable a COM calling convention declaration: https://github.com/dotnet/runtime/issues/46775
- Enable `ComWrappers` API for all platforms: https://github.com/dotnet/runtime/issues/36582

**Comment by Skynetuz** [comment]
No implementation yet?)

**Comment by jkoritzinsky** [comment]
I'd rather open a new issue to track the docs work than use this issue.
