### ISSUE TITLE
Unused resources analyzer

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#79745]
PR https://github.com/dotnet/roslyn-analyzers/pull/6338 attempts to implement the analyzer.

https://github.com/dotnet/roslyn-analyzers/pull/6338#issuecomment-1354580318 suggests we get this to be reviewed by dotnet/runtime team.

**Comment by dakersnar** [comment]
Hi @Youssef1313, thanks for your submission. In order to simplify our own work and ease the API (and analyzer) review process, we require proposals to generally follow a given template (and provide such a template when you select "new issues":  https://github.com/dotnet/runtime/issues/new/choose).  Our API review process and a link to the template/good example is here:  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps." Please resubmit this issue following that template and let me know if you have any questions.

**Comment by Youssef1313** [comment]
The template is more written for "API"s rather than analyzers, but I'll fill it.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/runtime/issues/79765

**Comment by dakersnar** [comment]
Ahh, I see what you mean. We might want to add an analyzer-specific template/doc in the future. Thanks anyway.

**Comment by Youssef1313** [comment]
No problem!
