### ISSUE TITLE
ConsoleLogger Queue optimization can lead to missed log entries

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/runtime#79812]
### Description

[`CompleteAdding`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProcessor.cs#L196) and [`TryDequeue`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProcessor.cs#L159) try to compete for same lock. Once `CompleteAdding` wins, no more entries are being logged despite there might still be some in the queue.
 
More details: https://github.com/dotnet/runtime/pull/70186#discussion_r1052103771

### Reproduction Steps

Just manual code analysis for now (after one of our integration test broke with runtime upgrade).
We can work on repro if needed.

FYI @vlada-shubina - as she started to dig into our broken test and pointed the focus to the recent console logger queue behavior change

### Expected behavior

All logged items, that are logged prior calling `Dispose` are being flushed after calling `Dispose`. No items are skipped.

### Actual behavior

Some already logged items can be skipped (and not flushed) after calling `Dispose`

### Regression?

Yes

**Comment by JanKrivanek** [comment]
repro: https://github.com/JanKrivanek/ConsoleLogging

**Comment by hymccord** [comment]
I did some research into this for a StackOverflow [question](https://stackoverflow.com/questions/75698463/console-app-using-console-logger-will-not-write-final-messages-easy-repro). I'll re-paste it here

It's due to the way `Microsoft.Extensions.Logging.Console\src\ConsoleLoggerProcessor.cs` was refactored in [this commit](https://github.com/dotnet/runtime/commit/bb17fb55c96ed45a6323ded2b88f8b432694840d) ([Associated PR](https://github.com/dotnet/runtime/pull/70186)).

Calling `logger.Log` doesn't have to immediately flush the message. If it did, the call could possibly take a long time and block longer than desired. The logger passes the message to all the internal `ILoggers` created from your `ILoggerProvider`s and do what they will with those messages. Configuring LoggerFactory with `builder.AddConsole();` adds `ConsoleLoggerProvider : ILoggerProvider` in your situation.

Upon creating an `ILoggerFactory`, all of your configured providers are instantiated and this is when `ConsoleLoggerProvider` [constructs a new class](https://github.com/dotnet/runtime/blob/9c818a3176c8505af9ac374ad3369c5832328013/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs#L58) called `ConsoleLoggerProcessor`. It's responsible for writing messages to `Console.Out` from a [background thread it creates](https://github.com/dotnet/runtime/blob/9c818a3176c8505af9ac374ad3369c5832328013/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProcessor.cs#L71-L76) to process the console logger message queue. Loggers push messages to this queue so they can return to the caller quickly and not block for file IO.

When `ILoggerFactory` is disposed, it will dispose of all created `ILoggerProviders` which results in the disposal of `ConsoleLoggerProcesser`. Disposing _that_ class calls `Thread.Join` on the message queue processing thread linked above.

Previously, `ConsoleLoggerProcessor`'s queue was implemented with `BlockingCollection<T>`. Here's an extremely simplified view:

```csharp
public class ConsoleLoggerProcessor : IDisposable
{
    private readonly Thread _outputThread;
    private readonly BlockingCollection<string> _messageQueue = new();

    public ConsoleLoggerProcessor()
    {
        _outputThread = new Thread(ProcessLogQueue) { IsBackground = true };
        _outputThread.Start();
    }

    public void EnqueueMessage(string message)
    { /* snip */ }

    private void ProcessLogQueue()
    {
        foreach (var message in _messageQueue.GetConsumingEnumerable())
        {
            Console.WriteLine(message);
        }
    }

    public void Dispose()
    {
        _messageQueue.CompleteAdding();
        _outputThread.Join(millisecondsTimeout: 1500);
    }
}
```

Upon disposal, the `BlockingCollection` is completed which prevents more adding, **but** `_messageQueue.GetConsumingEnumerable()` does not `yield break;` until **both** conditions are true
* Is adding complete?
* Is the queue empty?  

This means that `_outputThread` will not terminate until either `ProcessLogQueue` returns or the `1500` millisecond timeout hits.

Compare this to the new implementation using `Queue<T>`. Again extremely simplified to get the point across.

```csharp
public class ConsoleLoggerProcessor : IDisposable
{
    private readonly Thread _outputThread;
    private readonly Queue<string> _messageQueue = new();
    private bool _isAddingCompleted;

    public ConsoleLoggerProcessor()
    {
        _outputThread = new Thread(ProcessLogQueue) { IsBackground = true };
        _outputThread.Start();
    }

    public void EnqueueMessage(string message)
    { /* snip */ }

    private void ProcessLogQueue()
    {
        while (_isAddingCompleted)
        {
            if (_messageQueue.Count > 0)
            {
                Console.WriteLine(_messageQueue.Dequeue());
            }
        }
    }

    public void Dispose()
    {
        _isAddingCompleted = true;
        _outputThread.Join(millisecondsTimeout: 1500);
    }
}
```

When this implementation is disposed, the flag `_isAddingCompleted` is set to `true` and the tight loop in `ProcessLogQueue` essentially terminates immediately. In the real implementation, there are some synchronization barriers so `ProcessLogQueue` doesn't pin a core at 100%.

So it boils down to this:  

The previous logger had up to 1.5 seconds to flush what is left in the queue. Blocking your application from exiting for up to 1.5 seconds because `Thread.Join` blocks the calling thread (the main thread) until it terminates.

The current implementation doesn't wait for messages to be flushed. It exits immediately.

**Comment by hymccord** [comment]
> Expected Behavior: All logged items, that are logged prior calling Dispose are being flushed after calling Dispose. No items are skipped.

This isn't necessarily true. It just happens that all the items that are already in the `_messageQueue` can usually be flushed to `Console.Out` in less than 1.5 seconds.

> repro: https://github.com/JanKrivanek/ConsoleLogging

You can see this behavior if instead you change `Thread.Yield` to `Thread.Sleep(1)` to simulate some seriously slow IO.

**Comment by eerhardt** [comment]
IMHO, I don't think that `Microsoft.Extensions.Logging.Console` should be used outside of long running server applications (i.e. ASP.NET, Microsoft.Extensions.Hosting, etc.). At least not in its current form. For simple console apps, starting a background thread to serialize the writing to the console just doesn't make sense.

**Comment by eerhardt** [comment]
> so the fix can be as easy as

would you be willing to send a PR with the fix and some tests?
