### ISSUE TITLE
[API Proposal]: 

### ISSUE THREAD

**Issue by wangronghua** [dotnet/runtime#79923]
### Background and motivation

need to generate a son class and init the base class

### API Proposal

```csharp
```

### API Usage

```csharp

//need support
var testb = GetSonClassWithInitBaseClass<TestB>(3);
var testc = GetSonClassWithInitBaseClass<TestC>(3);
public static T GetSonClassWithInitBaseClass<T>(int x) where T:TestA, new()
{
	return new T(x);//need support
}

//otherwise now the onlyway is
var testa = GetSonClassWithInitBaseClass(3);
var testc = new TestC(testa);
public static TestA GetSonClassWithInitBaseClass(int x) 
{
	return new TestA(x);
}


public class TestA
{
	public TestA(int a) {
		A = a;
	}
	public TestA()
	{
	}

	public int A { get; set; }
}
public class TestB : TestA
{
	public int B { get; set; }
}
public class TestC : TestA
{
        public TestC(TestA a){
             A = a.A;
        }
	public int C { get; set; }
}
```

**Comment by svick** [comment]
Are you effectively asking for an improved `new()` constraint? That's https://github.com/dotnet/csharplang/discussions/769.

As a workaround, you can emulate that today using static abstract interface methods.

Though it's not clear to me whether that's actually what you're asking for, since neither `TestB` nor `TestC` have an `int` constructor.

**Comment by stephentoub** [comment]
Closing as a duplicate.  If the request is actually something else, please reopen and clarify. Thanks.
