### ISSUE TITLE
[API Proposal]: `System.Decimal` constants

### ISSUE THREAD

**Issue by just-ero** [dotnet/runtime#80042]
### Background and motivation

Today, both `System.Single` and `System.Double` have the following constant or static values:
```
Epsilon
NegativeInfinity
PositiveInfinity
NaN
NegativeZero
E
Pi
Tau
```
All of which are missing from the `System.Decimal` type. It would be nice to have this type mirror those fields of its siblings.

### API Proposal

```csharp
namespace System;

public readonly partial struct Decimal : /* omitted interfaces */
{
    public const decimal Epsilon = /* some math stuff */;
}
```

### API Usage

```csharp
decimal epsilon = decimal.Epsilon;
```

**Comment by epeshk** [comment]
`double.Epsilon` is misleading constant. Precision loss during floating-point computations typically much larger than it, and other constants depending on computations typically used for equality comparison, like `Math.Abs(a - b) < 1e-9` rather than `Math.Abs(a - b) < double.Epsilon`.

Are there any use cases when `Epsilon` constant will be useful for `decimal` type?

```
NegativeInfinity
PositiveInfinity
NaN
NegativeZero
```
Aren't representable as `decimal` values.

**Comment by just-ero** [comment]
I see. I'll admit this *was* moreso about the `E`, `Pi`, and `Tau` values. I simply included the other values as well to make the proposal more "complete".

**Comment by danmoseley** [comment]
Just curious what is your use case for Decimal that involves Pi? It's presumably not financial calculations.
