### ISSUE TITLE
Cookies lose implicit domain after serialization and adding to container.

### ISSUE THREAD

**Issue by radloffl** [dotnet/runtime#80053]
### Description

Using System.Text.Json to serialize and deserialize System.Net.Cookie objects will not always maintain roundtrip integrity.

Specifically, cookies with an implicit domain will have a '.' prepended after being verified (if they didn't already have a leading dot).

### Reproduction Steps

```C#
var cookieA = new System.Net.Cookie("session", "foobar", "/", "foo.bar");
var cookieJson = System.Text.Json.JsonSerializer.Serialize(cookieA);
var cookieB = System.Text.Json.JsonSerializer.Deserialize<System.Net.Cookie>(cookieJson);

// Add cookie A to a container
var cookiesA = new System.Net.CookieContainer();
cookiesA.Add(cookieA);

// Add cookieB to a container
var cookiesB = new System.Net.CookieContainer();
cookiesB.Add(cookieB);

// Test uri matching
Uri testUri = new Uri("https://foo.bar/account/login");

var headA = cookiesA.GetCookieHeader(testUri);
var headB = cookiesB.GetCookieHeader(testUri);

Assert.Equal(headA.Domain, headB.Domain); // headA has Domain=foo.bar, headB has Domain=.foo.bar
```

This becomes and issue when the domain no longer matches so cookies aren't sent with `HttpClient` calls.

### Expected behavior

Maintain implicit domain through serialization (and therefore maintain Domain).

### Actual behavior

`m_implicit_domain` is set before `m_domain` during serialization so `VerifySetDefaults` prepends a `'.'` because `m_implicit_domain` is `false`.

https://github.com/dsisco11/runtime/blob/c861e47b42178c283688753994c8e11c2fc838bb/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L421

### Regression?

Unknown

### Known Workarounds

Manually copy cookie excluding leading '.' using initializer so `Domain` setter isn't called.
```C#
var cookieA = new System.Net.Cookie("session", "foobar", "/", "foo.bar");
var cookieJson = System.Text.Json.JsonSerializer.Serialize(cookieA);
var cookieB = System.Text.Json.JsonSerializer.Deserialize<System.Net.Cookie>(cookieJson);

// Add cookie A to a container
var cookiesA = new System.Net.CookieContainer();
cookiesA.Add(cookieA);

// Add cookieB to a container
var cookiesB = new System.Net.CookieContainer();
cookiesB.Add(new Uri("https://foo.bar"), new Cookie(cookieB.Name, cookieB.Value, cookieB.Path, cookieB.Domain.TrimStart('.'))
			{
				Comment = cookie.Comment,
				CommentUri = cookie.CommentUri,
				Discard = cookie.Discard,
				Expired = cookie.Expired,
				Expires = cookie.Expires,
				HttpOnly = cookie.HttpOnly,
				Port = cookie.Port,
				Version = cookie.Version,
				Secure = cookie.Secure,
			});

// Test uri matching
Uri testUri = new Uri("https://foo.bar/account/login");

var headA = cookiesA.GetCookieHeader(testUri);
var headB = cookiesB.GetCookieHeader(testUri);

Assert.Equal(headA.Domain, headB.Domain);
```

### Other information

Very similar to https://github.com/dotnet/runtime/issues/70227

This issue does not occur with `BinaryFormatter` serialization but using that method of serialization is strong discouraged [due to security vulnerabilities](https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide).

**Comment by radloffl** [comment]
This issue has also been mentioned on https://github.com/dotnet/runtime/issues/17526#issuecomment-743756389

**Comment by antonfirsov** [comment]
Triage: assuming this can be addressed in a way https://github.com/dotnet/runtime/issues/70227 was fixed, it would be nice to have it fixed. Not critical for 8.0.

**Comment by antonfirsov** [comment]
@tudoranghelina91 thanks! Go ahead! :)

**Comment by tudoranghelina91** [comment]
Unless I'm missing something, from what I can tell, I think the test cases look a bit outdated...
GetCookieHeader method seems to return a string, therefore headA nor headB have a Domain property.

However, it seems that we can set m_domain_implicit via a DomainImplicit setter manually, which leads to this behavior.
Judging by the comment in the link with the code provided, it looks to be expected behavior.

Are we sure we want to drop this behavior? Because I don't see a problem with the serialization that System.Text.Json is doing.

@antonfirsov @radloffl

**Comment by antonfirsov** [comment]
> GetCookieHeader method seems to return a string, therefore headA nor headB have a Domain property.

Sorry I totally missed that detail. Given that the strings `headA` and `headB` are identical I don't see what's the actual issue here. @radloffl can you elaborate? If there is no unexpected observable behavior, I don't think we should change anything.

**Comment by tudoranghelina91** [comment]
> > GetCookieHeader method seems to return a string, therefore headA nor headB have a Domain property.
> 
> Sorry I totally missed that detail. Given that the strings `headA` and `headB` are identical I don't see what's the actual issue here. @radloffl can you elaborate? If there is no unexpected observable behavior, I don't think we should change anything.

I don't want to do too many assumptions, but if we set the domain via the constructor and assigning the passed value via the setter, the setter sets the value of m_domain_implicit to false, though it starts as true initially. 

So, when we call the constructor with domain argument like so:
```var cookieA = new System.Net.Cookie("session", "foobar", "/", "foo.bar");```

this overloaded constructor gets called
```
        public Cookie(string name, string? value, string? path, string? domain)
            : this(name, value, path)
        {
            Domain = domain;
        }
```
And finally, the setter for the domain gets called, which sets the ```m_domain_implicit``` field to false
```
        [AllowNull]
        public string Domain
        {
            get
            {
                return m_domain;
            }
            set
            {
                m_domain = value ?? string.Empty;
                m_domain_implicit = false;
                m_domainKey = string.Empty; // _domainKey will be set when adding this cookie to a container.
            }
        }
```
And then, when we add a cookie to the container
```
// Add cookie A to a container
var cookiesA = new System.Net.CookieContainer();
cookiesA.Add(cookieA);
```
This method inside the cookie gets called
https://github.com/dsisco11/runtime/blob/c861e47b42178c283688753994c8e11c2fc838bb/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L322

Which then reaches this path:
https://github.com/dsisco11/runtime/blob/c861e47b42178c283688753994c8e11c2fc838bb/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L421

Because we are setting the m_domain_implicit to false in the constructor via the setter.

**Comment by antonfirsov** [comment]
I think that constructor is meant to set an explicit domain. Assuming the actual problem is what @tudoranghelina91 described in https://github.com/dotnet/runtime/issues/80053#issuecomment-1489800270, I'm closing this as a duplicate of #84820.

@radloffl let me know if we misunderstood your concern!
