### ISSUE TITLE
Causing diffrent memory layout in .NET 6 and .NET 7 when field member has LayoutKind.Auto

### ISSUE THREAD

**Issue by neuecc** [dotnet/runtime#80077]
### Description

`LayoutKind.Sequential`(default) struct if a member of struct contains a `LayoutKind.Auto` (for example, `DateTime` or `DateTimeOffset` ), .NET 6 and .NET 7 have different memory layouts.
.NET 7, it is Sequential in .NET 7, but seems to be Auto in .NET 6.

Is this documented as a breaking change?
Is there a specification of the behavior anywhere?

![image](https://user-images.githubusercontent.com/46207/210130059-d0c037fa-1311-4107-9ba8-f4695fb09a98.png)

![image](https://user-images.githubusercontent.com/46207/210130067-7ec0baa5-9b19-4389-a2e0-4e08b9594f50.png)

### Reproduction Steps

Run this console app in .NET 6 and .NET 7

```csharp
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

var value = new SequentialStruct { V = new AutoLong { V = 9 }, X = 4, B = true };

var array = new byte[Unsafe.SizeOf<SequentialStruct>()];
Unsafe.WriteUnaligned(ref MemoryMarshal.GetArrayDataReference(array), value);

// .NET6: 4,0,0,0,1,0,0,0,9,0,0,0,0,0,0,0 (int, bool, AutoLong)
// .NET7: 9,0,0,0,0,0,0,0,4,0,0,0,1,0,0,0 (AutLong, int, bool)
Console.WriteLine(".NET Version:" + Environment.Version);
Console.WriteLine(string.Join(",", array));

[StructLayout(LayoutKind.Sequential)]
public struct SequentialStruct
{
    public AutoLong V;
    public int X;
    public bool B;
}

[StructLayout(LayoutKind.Auto)]
public struct AutoLong
{
    public long V;
}
```

### Expected behavior

shows same result both .NET 6 and .NET 7

### Actual behavior

different result in .NET 6 and .NET 7

.NET 6
`4,0,0,0,1,0,0,0,9,0,0,0,0,0,0,0 (int, bool, AutoLong)`

.NET 7:
`9,0,0,0,0,0,0,0,4,0,0,0,1,0,0,0 (AutLong, int, bool)`

### Configuration

Microsoft Windows 10 Pro
AMD Ryzen 9 5950X(x64)
.NET 6.0.404
.NET 7.0.100

### Other information

When saving data to a file with memory-copy, data saved in .NET 6 cannot be loaded in .NET 7.

**Comment by neuecc** [comment]
discuessed at https://github.com/dotnet/runtime/issues/44579
and affected from this PR? https://github.com/dotnet/runtime/pull/61759

**Comment by MichalPetryka** [comment]
You shouldn't rely on type layouts, even sequential ones since those are only guaranteed to be the same within a single OS and process architecture. Auto layout means that the runtime is free to change it whenever it deems it to be a good idea, in the future it's even possible that the runtime could use PGO data to change it.

**Comment by neuecc** [comment]
Given that it will be used in Native Interop, doesn't Sequential's warranty coverage need to be wider than you describe?

**Comment by MSDN-WhiteKnight** [comment]
They don't, because the runtime could create a copy of the struct with different layout when marshalling it to unmanaged code. And for your struct SequentialStruct it actually have to, because bool is not a blittable type. So i don't think there's an issue, runtime is allowed to change managed layout of non-blittable struct.

**Comment by MichalStrehovsky** [comment]
> Given that it will be used in Native Interop, doesn't Sequential's warranty coverage need to be wider than you describe?

Auto layout structs cannot be used in native interop. If you replace the `Unsafe.SizeOf` in your snippet with `Marshal.SizeOf` (to get the native size of the struct when the runtime passes it to native code), you'll get "System.ArgumentException: Type 'SequentialStruct' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.". This is because of the auto layout field that disqualifies the struct from interop.

**Comment by AaronRobinsonMSFT** [comment]
> Auto layout structs cannot be used in native interop.

Right. As soon as an auto layout is detected around type load the layout of the type is suspect and cannot be used in an interop scenario. This is "by design".

**Comment by neuecc** [comment]
AI had a response for sequential and auto, and I responded as talking about sequential.
Well, I can confirm that there was a breaking change in .NET 6 and 7 regarding struct memory layout, so it's ok.
Thank you very much.
