### ISSUE TITLE
Subtraction of -25893.178 from -25893.179 returns value with extra precision

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#80101]
### Description

This issue occurs at runtime with .NET 7 / Visual Studio 2022 17.4.3
The expression -25893.179 - -25893.178 returns -0.0010000000002037268 as result.
The expected result is -0.001.

### Reproduction Steps

var result =  -25893.179 - -25893.178;

### Expected behavior

The expected result is -0.001.

### Actual behavior

The expression -25893.179 - -25893.178 returns -0.0010000000002037268 as result.

### Configuration

.NET 7
Windows 11
x64

**Comment by tannergooding** [comment]
This is expected.

`float`, `double`, and `Half` are IEEE 754 floating-point types and represent values using multiples of powers of 2. If the value is not a multiple of a power of 2 (or it is, but is outside the precision of the type) then it cannot be exactly represented and must round to the nearest representable result.

In the case of `-25893.179`, it is not exactly representable and so it rounds to the nearest representable value: `-25893.17900000000008731149137020111083984375`
In the case of `-25893.178`, it is not exactly representable and so it rounds to the nearest representable value: `-25893.177999999999883584678173065185546875`

These two values are taken using the exact underlying values, the operation is done as if to infinite precision and unbounded range (which computes `-0.00100000000020372681319713592529296875`), and then it too is rounded to the nearest representable result (which in this case the result was exact and so no more rounding occurs).

The displayed string is the "shortest roundtrippable string". That is, the string with the least number of significant digits that when parsed returns the original value. In the case of the two inputs, it's generally the exact "literal" you typed. In the case of the output, that is `-0.0010000000002037268`.

The change to the displayed string happened in .NET Core 3 (https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/) to ensure that values would roundtrip by default. This was done because simple cases like `double.Parse(Math.PI.ToString())` did not return `Math.PI` and that led to all manner of undesirable bugs.

The actual bits computed haven't changed and you can observe this by using `BitConverter.DoubleToInt64Bits` between .NET Core 3+ and any prior version of .NET.

**Comment by danmoseley** [comment]
If in your scenario/your app you need this to get the result you expect, you should use double or decimal.

**Comment by danmoseley** [comment]
another variation of explanation -- https://github.com/dotnet/runtime/issues/34783
