### ISSUE TITLE
stop linking wasm native references with --allow-undefined to warn from bugged behavior 

### ISSUE THREAD

**Issue by Hazardu** [dotnet/runtime#80132]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have come across an issue while making a C++/C#  WebAssembly app. 
I have been assigning a global function pointer variable on the C++ side with a C# delegate passed with pinvoke, but the value caused a `null function or function signature mismatch` runtime error. After a lot of debugging, I have found that the reason behind that is writing to an uninitialized global variable.
It is only the first assignment where the global variable results in the field being assigned with a function pointer offset by +1 compared to the local variable. 

```
//header file
class MyClass
{
public:
  using FunctionPtrT = void (*)(void);
  static set(FunctionPtrT func);

  static FunctionPtrT static_pFunc;
};
```

```
//source file
extern "C"
{
void set(FunctionPtrT func) //called from C#
{
  static_pFunc = func;

  printf("%p\n",func);
  // calls function properly
  func(); 
  // always prints a value +1 relative to `func
  printf("%p\n",static_pFunc);
  // crashes with RuntimeError null function or function signature mismatch
  static_pFunc(); 
}
}
```

### Describe the solution you'd like

The solution would be to propagate a warning/error that would normally appear during linking of the native file references. The error is suppressed by  `--allow-undefined` flag as it is right now.

### Additional context

Assigning the same value to the global var again works, however. 
```
void set(FunctionPtrT func)
{
  static_pFunc = func;
  static_pFunc = func;
}
```
The second and subsequent assignments, as well as initializing the static member with `inline` solves the problem. Finding the reason behind this was a real challenge on its own.

**Comment by devshgraphicsprogramming** [comment]
Normally I'd expect to see something like this
```
Undefined symbols for architecture WASM: "MyClass::static_pFunc", referenced from: set(MyClass::FunctionPtrT) in libTest.a(MyClass.o) ld: symbol(s) not found for architecture WASM clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

but thanks to Mono-WASM's usage of `-Wl.--allow-undefined` the linker pretty much ignores all variables and functions it can't find. When you throw into the mix that WASM functions and global variables are but simple contiguous IDs, missing symbols create a perfect storm.

Normally unresolved functions get a pretty runtime assert from Emscripten (if you use the `-sASSERT` flag) so you at least know what's going on, albeit at runtime.

However this spectacular screw-up is because the static variable here is a **function pointer** and not a function itself, so Emscripten can't assert anything at runtime that it wasn't found.

# Solutions

I know that Mono AOT needs to generate some `.c` and `.h` sources on the fly and link them into the final `.wasm` in a deferred fashion.

However that is not reason to just blanket allow all symbols to be undefined.

## Autogenerate a C or C++header full of `extern`

Just list out all your symbol names and signatures you need undefined.

## Use the `-Wl,-u symbolName` flag

Create a list of all symbols you need undefined explicitly and invoke the linker of that

## Use a custom Clang Linker script

Again list all the symbols you need undefined explicitly.
