### ISSUE TITLE
HttpClient tries to verify the certificate issuer in Azure App Service

### ISSUE THREAD

**Issue by lrojasv** [dotnet/runtime#80238]
**Description:** 
I have a web service that makes calls to another remote end point that has a self-signed certificate, I have managed to add the ca root and the intermediate in the api provided by X509ChainPolicy, with that I have managed to do the validation correctly.

The problem I am encountering is that I see that calls are being made to the URL of the CA issuer (pki.caroot.com.pe) and since there is no connectivity to the pki.caroot.com.pe server, it generates a timeout than 15 seconds, affecting the response time of the requests.

It is worth mentioning that the calls to the pki.caroot.com.pe server are made every 1.5 minutes approximately, affecting the requests that are in progress at that moment.

This is the code I am using:

```c#
builder.Services.AddHttpClient("VtsApis")
    .ConfigurePrimaryHttpMessageHandler(_ => {
        HttpClientHandler httpClientHandler = new HttpClientHandler();
        httpClientHandler.ClientCertificates.Add(CertificateExtensions.LoadCertificate("2494C82EBF8AB13xxx452DB9F21BCxxxx")); //load certificate 
        httpClientHandler.ClientCertificates.Add(CertificateExtensions.LoadCertificate("9FC76B6FBDD38235xxx")); //load caroot
        httpClientHandler.ClientCertificates.Add(CertificateExtensions.LoadCertificate("9257B6CB3B3Bxxxx8FC26B7246A")); //load intermediate
        httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;

        httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, _) => {
            chain.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;

            var caroot = Convert.FromBase64String(@"ca_root");
            chain.ChainPolicy.CustomTrustStore.Add(new X509Certificate2(caroot));
            var caintermediate = Convert.FromBase64String(@"ca_intermediate");
            chain.ChainPolicy.ExtraStore.Add(new X509Certificate2(caintermediate));
            chain.ChainPolicy.DisableCertificateDownloads = true;
            chain.ChainPolicy.UrlRetrievalTimeout = new TimeSpan(1);
            chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
            chain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority | X509VerificationFlags.IgnoreEndRevocationUnknown;
            

            return chain.Build(cert);
        };

        return httpClientHandler;
    });
```

![image](https://user-images.githubusercontent.com/6382825/210815533-a19992bb-3094-4931-bb0e-b8240c216c44.png)

The question is, Is there a way to avoid the call to the server pki.caroot.com.pe?

**Expected:**
Evitar la llamada al server pki.caroot.com.pe

**Additional data**
I'm using:
.Net 6
Azure App Service Linux

**Comment by Suchiman** [comment]
Try setting https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.checkcertificaterevocationlist?view=net-7.0#system-net-http-httpclienthandler-checkcertificaterevocationlist to false?

**Comment by lrojasv** [comment]
> Intente establecer https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.checkcertificaterevocationlist?view=net-7.0#system-net-http-httpclienthandler-checkcertificaterevocationlist en falso.

Yes I tried and the problem persists

**Comment by lrojasv** [comment]
> No creo que sea posible con 6.0. Lo que ve sucede _antes_ de que se llame a ServerCertificateCustomValidationCallback, por ejemplo, la devolución de llamada ya se construyó en cadena. En cuanto a la frecuencia, esto probablemente se relacione con el tiempo de espera absoluto o inactivo en HttpHandler, por ejemplo, reanudamos la conexión para algunas solicitudes, pero luego caduca y realizará un nuevo protocolo de enlace y validación. Si el intento tuviera éxito al menos una vez, los intermedios se almacenarían en caché. La única opción que veo es poner los intermedios en el almacén de certificados "Ca" para que se pueda construir una cadena completa sin búsqueda adicional.
> 
> Si cambia a 7.0, puede usar [SslClientAuthenticationOptions.CertificateChainPolicy](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificatechainpolicy?view=net-7.0) en combinación con [SocketsHttpHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-7.0) . Eso le permite expresar la política deseada _antes_ `SslStream` de que la necesite.

Thanks for the answer, I'm going to try the 2 options you mention and I'll tell you the results.

**Comment by bartonjs** [comment]
Since the log shows that it's trying to fetch a certificate (vs a CRL or OCSP statement) that suggests that the chain can't be resolved locally.  Specifically, that whatever certificate is available at that URL was not found.

The most stable fix would be to preload those certificates onto the system, in `new X509Store(StoreName.CertificateAuthority, StoreLocation.CurrentUser)` for intermediate certificates or untrusted root authorities, or `new X509Store(StoreName.Root, StoreLocation.CurrentUser)` for trusted root authorities.

If the log is coming from the server (and it's not also the client) then the chain build is probably the TLS server host trying to load the chain to offer out during the TLS handshake.  That's not a chain operation whose policy you can influence... unless you bypass it entirely by changing the SslServerAuthenticationOptions from using `Certificate` to `CertificateContext`, and you build that context in offline mode.

If the log is coming from the client (and it's not also the server) then I'm confused, since DisableCertificateDownloads should have covered it.  If the cert that's being downloaded is an intermediate, then the fetch would indicate the server didn't include it in the TLS handshake.  If the cert being downloaded is the root then it just indicates that the client doesn't have any idea what that cert is, and is trying to find out if it can build a chain up to something trusted with more data.  (But... since DisableCertificateDownloads is true a client shouldn't have attempted the fetch at all...)

**Comment by wfurt** [comment]
The `DisableCertificateDownloads` is set after `SslStream` already called `chain.Build` @bartonjs  and the resulting chain is passed to the `ServerCertificateCustomValidationCallback`.

**Comment by bartonjs** [comment]
Oh, right.  Ha.  That was inside the callback.

That makes it less confusing overall :smile:.

**Comment by lrojasv** [comment]
@wfurt 
I've got it working on net 7 using SslClientAuthenticationOptions and SocketsHttpHandler, it's just not clear where to add the CA and intermediates in CustomTrustStore and ExtraStore that I set when using HttpClientHandler, where can I set them?

Here is my code that I have implemented for my tests:

```
builder.Services.AddHttpClient("VtsApis")
    .ConfigurePrimaryHttpMessageHandler(_ => {
        var sslOptions = new SslClientAuthenticationOptions
        {

            // Leave certs unvalidated for debugging
            RemoteCertificateValidationCallback = delegate { return true; },

            CertificateChainPolicy = new X509ChainPolicy
            {
                DisableCertificateDownloads= true
            }
        };

        var handler = new SocketsHttpHandler()
        {
            SslOptions = sslOptions
        };

        return handler;
    });
```

**Comment by wfurt** [comment]
That should be same as your original code. It simply tells `SslStream` to use your policy instead of creating one internally.  
Intermediates goe to `ExtraStore`, root CA to `CustomTrustStore`. 

You can take inspiration from
https://github.com/dotnet/runtime/blob/ecc1ca12aeb7935b7268e752a88c2fa16b875abc/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs#L757

**Comment by lrojasv** [comment]
Thanks, I got it to work.

In short, to get around the problem I had to use Net 7 with SslClientAuthenticationOptions.CertificateChainPolicy in combination with SocketsHttpHandler, as wfurt recommended.

I leave the implemented code in case it helps someone:

```
builder.Services.AddHttpClient("Apis")
    .ConfigurePrimaryHttpMessageHandler(_ => {
        var sslOptions = new SslClientAuthenticationOptions
        {
            CertificateChainPolicy = new X509ChainPolicy
            {
                DisableCertificateDownloads= true,
                RevocationMode = X509RevocationMode.NoCheck,
                TrustMode = X509ChainTrustMode.CustomRootTrust
            }
        };
    sslOptions.CertificateChainPolicy.CustomTrustStore.Add(CertificateExtensions.LoadCertificate("thumb_ca_root"));
        sslOptions.CertificateChainPolicy.ExtraStore.Add(CertificateExtensions.LoadCertificate("thumb_intermediate"));
        var handler = new SocketsHttpHandler()
        {
            SslOptions = sslOptions
        };

        return handler;
    });
```

Thanks
