### ISSUE TITLE
Can't add typed HttpClient for BackgroundService

### ISSUE THREAD

**Issue by sergiojrdotnet** [dotnet/runtime#80303]
### Description

I'm trying to inject a typed HttpClient into a BackgroundService, is it possible?

### Reproduction Steps

Program.cs

```
using BackgroundServiceHttpClientTests;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHostedService<MyService>()
    .AddHttpClient<MyService>(c => c.BaseAddress = new Uri("https://nfe.io"));

builder.Services.AddControllers();

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

MyService.cs

```
namespace BackgroundServiceHttpClientTests;

public class MyService : BackgroundService
{
    private readonly HttpClient _httpClient;

    public MyService(HttpClient httpClient)
    {
        _httpClient = httpClient;

        var baseAddress = _httpClient.BaseAddress;
    }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        return Task.CompletedTask;
    }
}
```

### Expected behavior

Injected `HttpClient` should have the configured `BaseAddress`.

### Actual behavior

![image](https://user-images.githubusercontent.com/72770006/211076210-f0c3698e-a7ad-4d37-b3e4-ea95dbaf759e.png)

### Configuration

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22623
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

**Comment by ovska** [comment]
Maybe configure a named client, inject `IHttpClientFactory` and retrieve the client that way, e.g. `_httpClient = httpClientFactory.CreateClient(nameof(MyService))` ?

**Comment by CarnaViire** [comment]
@sergiojrdotnet there are a couple of things that are erroneous in your approach.

A Typed client is not an HttpClient instance, it is a service you would have HttpClient instance automatically injected to. So you've essentially tried to *register BackgroundService as a Typed client* rather than inject Typed client into a BackgroundService. The problem with that is that both `AddHostedService` and `AddHttpClient` would register the type in the container; `AddHostedService` would register a singleton on `IHostedService` interface, and `AddHttpClient` would register a transient. Then the hosting infrastructure would resolve `IHostedService` (registered by `AddHostedService`) and inject a *default* HttpClient in it (that's what you see in your repro, the instance is injected, but it's not set up the way you wanted it to be).

The second problem is that BackgroundService is a singleton, but HttpClients created by HttpClientFactory are expected to be short-lived. Otherwise, DNS changes would not be respected, without additional setup. You can learn more in https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory#use-typed-clients-in-singleton-services. The bottom line is that you don't want to inject Typed clients into singletons, unless you set up SocketsHttpHandler with configured PooledConnectionLifetime.

The solutions to what you're trying to achieve would be:

1) Use Named client approach, as @ovska suggested. Note that you would need to call CreateClient whenever you'd need an HttpClient instance, *not* in a constructor.

```c#
builder.Services.AddHostedService<MyService>();
builder.Services.AddHttpClient("foo", c => c.BaseAddress = new Uri("https://nfe.io"));

...

public class MyService : BackgroundService
{
    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            using var httpClient = _httpClientFactory.CreateClient("foo");
            await FooAsync(httpClient, stoppingToken);
        }
    }
    ...
}

```

-or-

2) For a Typed client approach, you would need a *separate* Typed client class, and you would need to set up SocketsHttpHandler with PooledConnectionLifetime as described in https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory#using-ihttpclientfactory-together-with-socketshttphandler

```c#
builder.Services.AddHostedService<MyService>();
builder.Services.AddHttpClient<FooClient>(c => c.BaseAddress = new Uri("https://nfe.io"))
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        return new SocketsHttpHandler()
        {
            PooledConnectionLifetime = TimeSpan.FromMinutes(2) // Make Typed client safe to be injected into singletons
        };
    })
    .SetHandlerLifetime(Timeout.InfiniteTimeSpan); // Disable rotation, as it is handled by PooledConnectionLifetime

...

public class MyService : BackgroundService
{
    private readonly FooClient _fooClient;

    public MyService(FooClient fooClient)
    {
        _fooClient = fooClient;
    }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            await _fooClient.FooAsync(stoppingToken);
        }
    }
    ...
}

```

-or-

3) If you only ever need ONE HttpClient configuration, you can bypass HttpClientFactory entirely and just register a singleton HttpClient (with PooledConnectionLifetime)

```c#
builder.Services.AddHostedService<MyService>();
builder.Services.AddSingleton<HttpClient>(_ =>
    {
        var handler = new SocketsHttpHandler()
        {
            PooledConnectionLifetime = TimeSpan.FromMinutes(2) // Make HttpClient safe to be singleton
        };
        return new HttpClient(handler);
    });

...

public class MyService : BackgroundService
{
    private readonly HttpClient _httpClient;

    public MyService(HttpClient httpClient) // httpClient is singleton
    {
        _httpClient = httpClient;
    }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            await FooAsync(_httpClient, stoppingToken);
        }
    }
    ...
}

```

Let me know if this helps @sergiojrdotnet 

I'm going to close the issue as answered, but feel free to reopen if you need any additional help with your question.
