### ISSUE TITLE
An `extern` method without a body causes its entire containing type to fail to load.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#80300]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgZgAIiylGT6Bhegb2vr8YZMWMBBhhQ8jFPQByACgCUAbl79VfUmx5V+9AL7U9QA

Consider the following snippet:

```csharp
public static class C {
    public static extern void M();
    
    public static void Main() {
    }
}
```

`M` is not called but its mere existence causes a `TypeLoadException` on the entire class when attempting to run the program. I wonder if it's necessary. Can't we let the type load normally and JIT `M` to a stub that throws say `InvalidProgramException`?

As for the motivating scenario, this pattern could be used as a hook to let weavers add a method body. I cannot use it because my weaver first executes code from the assembly.

**Comment by jkotas** [comment]
We prefer to detect invalid programs sooner rather than later. It is very cheap to detect this type of invalid method during type loading in the current type loader and so that's why it is done during type loading.

I do not think that we want to start making guarantees about when invalid program exceptions are thrown.

> I cannot use it because my weaver first executes code from the assembly.

Can you weave the code into a valid shape before executing it?

**Comment by teo-tsirpanis** [comment]
Thanks for the feedback. Pre-weaving would add an additional step to my process and affect performance, but I understand your reasoning, and either way my use case is not enough reason to diverge from established behavior. Maybe I can use a source generator to prevent the users from writing a dummy method body themselves, if I want to avoid it.
