### ISSUE TITLE
Regex with GeneratedRegex attribute is slower in some cases

### ISSUE THREAD

**Issue by esben2000** [dotnet/runtime#80317]
In the regex-benchmark test at
[https://github.com/mariomka/regex-benchmark](https://github.com/mariomka/regex-benchmark)
both the Email and URI regex is much faster on first load when using GeneratedRegex attribute. However, the IPv4 regex seems to be slower. Even when running the match count 10 times in a loop, all match count using GeneratedRegex attribute will be slower than just a regex without options and much slower than a regex with Compiled option.
Shouldn’t the regex with the GeneratedRegex attribute always be faster or at least as fast as the Compiled version?

Here is code to reproduce the problem:
```csharp
using System.Diagnostics;
using System.Text.RegularExpressions;

bool doEmail = true;
bool doUri = true;
bool doIP = true;
bool doRegex = true;
bool doNormal = true;
bool doCompiled = true;

#if NET7_0_OR_GREATER
Regex emailRegex = EmailRegex();
Regex uriRegex = URIRegex();
Regex ipRegex = IPRegex();
#endif

string data = new HttpClient().GetStringAsync(@"https://raw.githubusercontent.com/mariomka/regex-benchmark/8e11300825fc15588e4db510c44890cd4f62e903/input-text.txt").Result;

for (int i = 0; i < 10; i++)
{
    // Email
    if (doEmail)
    {
        #if NET7_0_OR_GREATER
        MeasureRegex(data, emailRegex, "Email");
        #endif
        Measure(data, @"[\w\.+-]+@[\w\.-]+\.[\w\.-]+", "Email");
        MeasureCompiled(data, @"[\w\.+-]+@[\w\.-]+\.[\w\.-]+", "Email");
    }

    // URI
    if (doUri)
    {
        #if NET7_0_OR_GREATER
        MeasureRegex(data, uriRegex, "URI");
        #endif
        Measure(data, @"[\w]+://[^/\s?#]+[^\s?#]+(?:\?[^\s#]*)?(?:#[^\s]*)?", "URI");
        MeasureCompiled(data, @"[\w]+://[^/\s?#]+[^\s?#]+(?:\?[^\s#]*)?(?:#[^\s]*)?", "URI");
    }

    // IP
    if (doIP)
    {
        #if NET7_0_OR_GREATER
        MeasureRegex(data, ipRegex, "IP");
        #endif
        Measure(data, @"(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])", "IP");
        MeasureCompiled(data, @"(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])", "IP");
    }
}

void Measure(string data, string pattern, string regname)
{
    if (!doNormal)
        return;

    //var swStart = Stopwatch.GetTimestamp();
    Stopwatch stopwatch = Stopwatch.StartNew();

#if NET7_0_OR_GREATER
    int count = Regex.Count(data, pattern);
#else
    int count = 0;
    Match m = Regex.Match(data, pattern);
    while (m.Success)
    {
        count++;
        m = m.NextMatch();
    }
#endif

    stopwatch.Stop();
    Console.WriteLine($"{regname} Normal {stopwatch.Elapsed.TotalMilliseconds.ToString("G", System.Globalization.CultureInfo.InvariantCulture)} - {count}");
}

void MeasureCompiled(string data, string pattern, string regname)
{
    if (!doCompiled)
        return;

    //var swStart = Stopwatch.GetTimestamp();
    Stopwatch stopwatch = Stopwatch.StartNew();

#if NET7_0_OR_GREATER
    int count = Regex.Count(data, pattern, RegexOptions.Compiled);
#else
    int count = 0;
    Match m = Regex.Match(data, pattern, RegexOptions.Compiled);
    while (m.Success)
    {
        count++;
        m = m.NextMatch();
    }
#endif

    stopwatch.Stop();
    Console.WriteLine($"{regname} Compiled {stopwatch.Elapsed.TotalMilliseconds.ToString("G", System.Globalization.CultureInfo.InvariantCulture)} - {count}");
}

void MeasureRegex(string data, Regex regex, string regname)
{
#if NET7_0_OR_GREATER
    if (!doRegex)
        return;

    var swStart = Stopwatch.GetTimestamp();

    int count = regex.Count(data);

    Console.WriteLine($"{regname} Regex {Stopwatch.GetElapsedTime(swStart).TotalMilliseconds.ToString("G", System.Globalization.CultureInfo.InvariantCulture)} - {count}");
#endif
}

#if NET7_0_OR_GREATER
partial class Program
{
    [GeneratedRegex("[\\w\\.+-]+@[\\w\\.-]+\\.[\\w\\.-]+")]
    private static partial Regex EmailRegex();

    [GeneratedRegex("[\\w]+://[^/\\s?#]+[^\\s?#]+(?:\\?[^\\s#]*)?(?:#[^\\s]*)?")]
    private static partial Regex URIRegex();

    [GeneratedRegex("(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])")]
    private static partial Regex IPRegex();
}
#endif
```

**Comment by Clockwork-Muse** [comment]
We use [benchmarkdotnet](https://benchmarkdotnet.org/) for performance testing in this repository (see also [the benchmarking repo](https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md), and performance issues generally need to be written to use that library.

In particular, the current repro code runtime-compiles the regexes each loop, which means the performance will be reported as lower than in a realistic application (which would compile only once).
(... although I believe there may be a cache, which is likely distorting things anyways...)

**Comment by stephentoub** [comment]
Just measuring a few iterations with Stopwatch isn't sufficient to get an accurate picture of steady-state throughput. If you want to measure throughput, especially with tiered compilation on by default, you need to do the measurements in such a way that it allows the code to "tier up", meaning execute it enough times and for long enough that the JIT will generate an optimized implementation; otherwise, the code the JIT initially generates for code in your app will be unoptimized, instead preferring to JIT it quickly rather than spend time optimizing code that may never or infrequently be used again.  Using a tool like benchmark.net will help with that.  In your example, just using a Stopwatch and calling the functions a few times is not sufficient.  With the interpreter, the same interpreter code is used regardless of the target regex, so you're likely executing the interpreter's routine enough to get it to tier up.  With Compiled, it uses a DynamicMethod that currently doesn't participate in tiering, and thus it's always compiled immediately with optimized code.  But with the source generator, the generated code is just part of your project, and so by default it will also participate in tiering, so more discipline is needed in measuring.

So, doing this as a benchmark.net benchmark:
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Net.Http;
using System.Text.RegularExpressions;

public partial class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

    internal static readonly string s_data = new HttpClient().GetStringAsync(@"https://raw.githubusercontent.com/mariomka/regex-benchmark/8e11300825fc15588e4db510c44890cd4f62e903/input-text.txt").Result;
}

public partial class EmailRegex
{
    private const string Pattern = "[\\w\\.+-]+@[\\w\\.-]+\\.[\\w\\.-]+";

    [Benchmark(Baseline = true)] public int Interpreted() => s_interpreted.Count(Program.s_data);
    [Benchmark] public int Compiled() => s_compiled.Count(Program.s_data);
    [Benchmark] public int SourceGenerated() => s_sourceGenerated().Count(Program.s_data);

    private static readonly Regex s_interpreted = new Regex(Pattern);
    private static readonly Regex s_compiled = new Regex(Pattern, RegexOptions.Compiled);
    [GeneratedRegex(Pattern)]
    private static partial Regex s_sourceGenerated();
}

public partial class URIRegex
{
    private const string Pattern = "[\\w]+://[^/\\s?#]+[^\\s?#]+(?:\\?[^\\s#]*)?(?:#[^\\s]*)?";

    [Benchmark(Baseline = true)] public int Interpreted() => s_interpreted.Count(Program.s_data);
    [Benchmark] public int Compiled() => s_compiled.Count(Program.s_data);
    [Benchmark] public int SourceGenerated() => s_sourceGenerated().Count(Program.s_data);

    private static readonly Regex s_interpreted = new Regex(Pattern);
    private static readonly Regex s_compiled = new Regex(Pattern, RegexOptions.Compiled);
    [GeneratedRegex(Pattern)]
    private static partial Regex s_sourceGenerated();
}

public partial class IPRegex
{
    private const string Pattern = "(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])";

    [Benchmark(Baseline = true)] public int Interpreted() => s_interpreted.Count(Program.s_data);
    [Benchmark] public int Compiled() => s_compiled.Count(Program.s_data);
    [Benchmark] public int SourceGenerated() => s_sourceGenerated().Count(Program.s_data);

    private static readonly Regex s_interpreted = new Regex(Pattern);
    private static readonly Regex s_compiled = new Regex(Pattern, RegexOptions.Compiled);
    [GeneratedRegex(Pattern)]
    private static partial Regex s_sourceGenerated();
}
```
Here's what I get (with `dotnet run -c release -f net7.0 --filter **`):

Email:
|          Method |     Mean |    Error |   StdDev | Ratio | RatioSD |
|---------------- |---------:|---------:|---------:|------:|--------:|
|     Interpreted | 676.3 us | 13.22 us | 15.73 us |  1.00 |    0.00 |
|        Compiled | 617.1 us | 12.19 us | 23.18 us |  0.92 |    0.04 |
| SourceGenerated | 598.9 us | 11.93 us | 23.54 us |  0.90 |    0.03 |

Uri:
|          Method |      Mean |     Error |    StdDev | Ratio |
|---------------- |----------:|----------:|----------:|------:|
|     Interpreted | 23.742 ms | 0.4573 ms | 0.3819 ms |  1.00 |
|        Compiled |  5.140 ms | 0.0465 ms | 0.0435 ms |  0.22 |
| SourceGenerated |  5.054 ms | 0.0282 ms | 0.0264 ms |  0.21 |

IP:
|          Method |     Mean |     Error |    StdDev | Ratio |
|---------------- |---------:|----------:|----------:|------:|
|     Interpreted | 2.652 ms | 0.0410 ms | 0.0343 ms |  1.00 |
|        Compiled | 1.476 ms | 0.0133 ms | 0.0104 ms |  0.56 |
| SourceGenerated | 1.374 ms | 0.0259 ms | 0.0287 ms |  0.52 |

So at steady state, the source generated code is _not_ slower than either compiled or the interpreter.  It's generally much faster than the interpreter (unless the entire search is spent in some shared routine like IndexOf), and it's generally either as fast or a bit faster than Compiled, while also being faster to get started because all of the parsing and code generation happens at compile time rather than run time.

**Comment by esben2000** [comment]
Hi Stephen 
Thank you for the answer. It makes sense when you say that “With Compiled, it uses a DynamicMethod that currently doesn't participate in tiering, and thus it's always compiled immediately with optimized code”. I just had the impression that source generated regex code would be the fastest on the *first* run. And therefore, I did not do a benchmark.net test, because it will do a lot of runs and I wanted to measure first run.

Btw. I tried to find a way to write this ‘question’ to you but couldn’t find any contact info anywhere.

And thank you for your in-depth blogs on performance, it is a big pleasure to read them!

**Comment by stephentoub** [comment]
> I just had the impression that source generated regex code would be the fastest on the first run. And therefore, I did not do a benchmark.net test, because it will do a lot of runs and I wanted to measure first run.

I expect it will be if you disable tiered compilation so you're comparing apples to apples.

**Comment by esben2000** [comment]
You’re perfectly right! I have now tried with tiered compilation disabled and now the source generated regex code is fastest on first run.
