### ISSUE TITLE
Aes-Gcm tags should support other sizes than 16 on macOS

### ISSUE THREAD

**Issue by Fabi** [dotnet/runtime#80329]
### Description

Using tag sizes like 12 bytes are not uncommon and should not be forbidden to be used at all on macOS. With the recently merged PR that is the case now.

PR: https://github.com/dotnet/runtime/pull/76490

Removing (unless I've overseen some ways) the ability to manually fallback to openssl seems to be a bad decision.

In scenarios where you are forced or do not have control over the tag size you are not able to use the .NET implementation of Aes-Gcm anymore.

### Reproduction Steps

1. Create a .NET 8 project using latest installer.
2. Use Aes-Gcm class with tag size 12 to Encrypt/Decrypt something on macOS

### Expected behavior

Support non 16 byte tag sizes in Aes-Gcm on macOS using openssl fallback using an env var. For example `DYLD_LIBRARY_PATH=/opt/homebrew/opt/openssl@3/lib`

### Actual behavior

Aes-Gcm does not support non 16 byte tags on macOS since .NET 8

### Regression?

Works in .NET 7

### Configuration

```.NET SDK:
 Version:   8.0.100-alpha.1.23056.11
 Commit:    7bea0af7fe

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-alpha.1.23056.11/

Host:
  Version:      8.0.0-alpha.1.23055.3
  Architecture: arm64
  Commit:       9197fd5551
```

**Comment by adamsitnik** [comment]
Afaik this is by design, @vcsjones has created a breaking change doc where he described it: https://github.com/dotnet/docs/issues/32346

**Comment by vcsjones** [comment]
@Fabi am I to understand you are asking us to re-consider the breaking change?

We could implement a fallback to OpenSSL for short AES-GCM tags, but we chose not to for a couple of reasons.

1. We can not implement the OpenSSL fallback on iOS / tvOS. So the fallback would be inconsistent across the Apple ecosystem. We don't support `AesGcm` on those platforms yet, but intend to when certain roadblocks are resolved.
2. Apple made the design decision that their implementation of AES-GCM should only support 16 byte tags. If CryptoKit supported other tag sizes, we would likely support them (at least the ones that NIST defines). .NET prefers to adhere to the limits of the platform's preferred cryptographic implementation.
3. I think the fallback would be confusing to developers to understand their application's dependencies. 

> Using tag sizes like 12 bytes are not uncommon

While I am sure they exist, I personally view them as uncommon.

/cc @bartonjs and @GrabYourPitchforks for input as y'all had some input on the breaking change.

**Comment by Fabi** [comment]
I basically ask you to revert that breaking change or giving us an option to allow using the openssl libs by setting some env vars or similar settings. like a really opt in way and not an auto fallback

**Comment by vcsjones** [comment]
> like a really opt in way and not an auto fallback

Can you please explain why you would prefer to use OpenSSL over CryptoKit? For the sake of argument, what's wrong with using CryptoKit for 16-byte tags, and OpenSSL for 12-15-byte tags?

**Comment by bartonjs** [comment]
Thanks for opening this issue... literally the only way we know that someone cares about 12-15 byte tags is someone speaking up.

If all you care about is AES-GCM encryption, there's good news for you... the algorithm (foolishly, IMO) doesn't use the length of the tag as an input into tag generation, so you can encrypt for a 16 byte tag, then just discard the final four bytes... and that's a 12-byte tag.

For decryption, you would then be forced to brute force any missing bytes.  My best presumption is that Apple chose to disallow shortened tags so that applications weren't susceptible to the trap of not checking the incoming tag length on decryption, then processing a shorter tag than expected and having less forgery protection than expected.

In general, our stance in .NET cryptography is to use system libraries.  When we first added support for AES-GCM on macOS it was not available to us from system libraries.  Now that it is, we don't really want to have people encounter the difficulties of .NET+OpenSSL on macOS just because of the tag length... where things would work fine at 16 bytes, then you get weird exceptions for 12-15 (assuming you haven't already had to go through the work to make .NET able to find/bind to OpenSSL).

So, in this case, we view this as a macOS system limitation, and we're reflecting that limitation in .NET.  If Apple makes changes to allow shorter tags, we'll add that support to .NET.  Alternatiely, if we get a whole lot of feedback saying that the OSSL-fallback model would provide more utility than frustration, we might consider that.... but we're basically pursuing never using OpenSSL on macOS, just because the acquisition and integration story is rough.

**Comment by Fabi** [comment]
> > like a really opt in way and not an auto fallback
> 
> Can you please explain why you would prefer to use OpenSSL over CryptoKit? For the sake of argument, what's wrong with using CryptoKit for 16-byte tags, and OpenSSL for 12-15-byte tags?

Oh I only wrote that because you said it would be confusing to fallback from developers. But bartonjs doesn't seem to see any valid reasons in allowing that due to the absolute wrong way of using system libraries instead of .NET implementations of algorithms and seeing something like the tag length as an OS limitation and not offering the openssl fallback alternative.

And that 'workaround' is just not an acceptable and weird, foolish way to do those things. Especially when working on applications that use those tags and you have to work with its traffic to encrypt and decrypt externally. You never want to do those weird things.
