### ISSUE TITLE
System.Text.Json TryGetDateTimeOffset String=\u007F\u007F Error=Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by ni-xue** [dotnet/runtime#80383]
### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by eiriktsarpalis** [comment]
Does the error go away when running it in .NET 7? Could you share a minimal repro? Thanks!

**Comment by ni-xue** [comment]
@eiriktsarpalis  .net 6

**Comment by ni-xue** [comment]
@eiriktsarpalis No experiment, no environment at present

**Comment by eiriktsarpalis** [comment]
We would need a [minimal reproduction](https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#why-are-minimal-reproductions-important) in order to take a better look at this. I'm going to close the issue for now, feel free to reopen if you could share one or confirm that the issue has been resoved in System.Text.Json v7.
