### ISSUE TITLE
DateTime.ToString() behavior diverged in ru-RU locale in alpine on 7.0.2

### ISSUE THREAD

**Issue by wingrime** [dotnet/runtime#80542]
### Description

After minor update from 7.0.1 to 7.0.2 we start to see that unit test for locale start to fail on linux but not windows.

Localized date representation changed behavior and added non break space beteween year number and "year" short signature - "г." 

### Reproduction Steps

```
public class CultureTests
{
    private static readonly CultureInfo RussianCulture = CultureInfo.GetCultureInfo("ru-RU");

    /*
Assert.Equal() Failure
                             ↓ (pos 19)
Expected: среда, 15 июня 2022 г.
Actual:   среда, 15 июня 2022 г.
                             ↑ (pos 19)
     */
   [Fact]
   public void ShouldBeDateStringInRuCulture_WhenToStringAndRussianCulture()
    {
        var date = new DateTime(2022, 6, 15);

        Assert.Equal("среда, 15 июня 2022 г.", date.ToString("D", RussianCulture));
    }
}
```
![изображение](https://user-images.githubusercontent.com/533665/212057817-81ed9383-7ae0-4726-9beb-0dd7ecab1ca1.png)

### Expected behavior

Behavior should be same regardless OS

Behavior should not changed in minor update

### Actual behavior

Linux and Windows date's ToString() give binary different strings

### Regression?

YES

### Configuration

alpine, most recent net7
windows, most recent sdk

**Comment by tarekgh** [comment]
.NET depends on the installed ICU library for globalization data. Looking at the Unicode CLDR data https://github.com/unicode-org/cldr/blob/ac66592c93d0cb26d0b8666d3978bcab1ec889fb/common/main/ru.xml#L1751 I am seeing the Russian date format contains the non-breaking space as you are seeing it in Alpine. So, this is the correct format. Windows most likely hasn't updated the installed ICU version yet, but this should happen eventually and should see consistent data at that time. Meanwhile, you may force the format you like in your code, something like:

```c#
		// Overwrite the Russian date format and use it for date formatting and parsing.

            CultureInfo ci = new CultureInfo("ru-RU");
            ci.DateTimeFormat.ShortDatePattern =  // assign the format you prefer 
            ci.DateTimeFormat.LongDatePattern =  // assign the format you prefer 
```

**Comment by tarekgh** [comment]
https://unicode-org.atlassian.net/browse/CLDR-14032

**Comment by richlander** [comment]
@tarekgh -- Do you think we should elevate this issue to a PSA on dotnet/announcements and/or listing in our breaking change documents? It seems like a breaking change (not ours) that could affect a lot of users. This issue (and the dotnet/dotnet-docker one) might not be super discoverable.

**Comment by tarekgh** [comment]
@richlander I think getting this announced somewhere will be good. Let me know which best visible place and I can try to write something there.

**Comment by richlander** [comment]
Here is an example: https://github.com/dotnet/announcements/issues/223

**Comment by richlander** [comment]
We talked about this a bit more. Apparently, we see breaks like this commonly.

Our policy is to test new OS versions with the tests we have (which can be improved over time). If the tests pass, then we consider the OS good, including in containers. OS and package breaks are outside of our control and it isn't our responsibility (in the general case) to address them unless they specifically break the .NET product. We also shouldn't document them since we're not in the business of documenting OS changes in general.

**Comment by MichalPetryka** [comment]
> .NET depends on the installed ICU library for globalization data. Looking at the Unicode CLDR data https://github.com/unicode-org/cldr/blob/ac66592c93d0cb26d0b8666d3978bcab1ec889fb/common/main/ru.xml#L1751 I am seeing the Russian date format contains the non-breaking space as you are seeing it in Alpine. So, this is the correct format. Windows most likely hasn't updated the installed ICU version yet, but this should happen eventually and should see consistent data at that time. Meanwhile, you may force the format you like in your code, something like:
> 
> ```cs
>            // Overwrite the Russian date format and use it for date formatting and parsing.
> 
>             CultureInfo ci = new CultureInfo("ru-RU");
>             ci.DateTimeFormat.ShortDatePattern =  // assign the format you prefer 
>             ci.DateTimeFormat.LongDatePattern =  // assign the format you prefer 
> ```

The report says that the difference is between Linux 7.0.2 and 7.0.1, not Linux and Windows.

**Comment by tarekgh** [comment]
> The report says that the difference is between Linux 7.0.2 and 7.0.1, not Linux and Windows.

Here what is listed in the issue description:
`After minor update from 7.0.1 to 7.0.2 we start to see that unit test for locale start to fail on linux but not windows.`

Anyway, the difference is coming from installed ICU versions.

**Comment by wingrime** [comment]
It's not expected that major alpine  v3.16->v3.17 happens in dotnet minor update. Such changed should be in sync with dotnet major releases. 

With this update we had more one issue due packages. We install additional alpine packages on top dotnet alpine image. In v3.17  some packages was split. Update required source changes, that's not expected for patch level update.

**Comment by tarekgh** [comment]
@wingrime thanks for the feedback. @richlander do you have more info about reasons for upgrading Alpine images now?  was this just to keep up to date with the newest OS releases?

**Comment by richlander** [comment]
That's not feasible, @wingrime. Alpine updates come quite frequently and go out of support at the same rate. In general, Alpine releases every 6 months and each release is supported for 2 years. Also, we've found that security vulnerabilities are often fixed first in tip releases, and our users _demand_ quick access to them for that reason (which we've done).

However, it sounds like you are using an Alpine floating tag. You don't need to. For example, you can use a version-specific tag to avoid this problem. However, it is then your responsibility to watch our announcements to see when the version you are using is no longer maintained.

Alpine announcements: https://github.com/dotnet/dotnet-docker/discussions/categories/announcements?discussions_q=category%3AAnnouncements+alpine

Our tagging policies are documented at: https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md. Admittedly, the document is a little hard to understand. I suggest searching on "alpine" since it is used as an example in the doc, and you should get to the info you need.
