### ISSUE TITLE
Implement CryptoStream Write overload that takes ReadOnlySpan

### ISSUE THREAD

**Issue by abhijitpai** [dotnet/runtime#80540]
Implementing the Write(ReadOnlySpan<byte> buffer) method in CryptoStream will avoid making a copy of the input the base Stream implementation does.

**Comment by stephentoub** [comment]
For reference, this has been discussed several times:
https://github.com/dotnet/runtime/issues/22828#issuecomment-321087214
https://github.com/dotnet/runtime/issues/63191#issuecomment-1009042551

**Comment by bartonjs** [comment]
As mentioned (https://github.com/dotnet/runtime/issues/22828#issuecomment-321087214), overriding the method could remove the array allocation from the base class... then move it into that method, since ICryptoTransform is still array-based.

When working with spans and encryption, your best bet is to avoid CryptoStream entirely, and use the new methods like [EncryptCbc](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.encryptcbc?view=net-7.0).
