### ISSUE TITLE
System.Diagnostics.Process.StandardInput.WriteLine does not work properly on macOS.

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [dotnet/runtime#80648]
### Description

When I start zsh using `System.Diagnostics.Process.Start` on macOS and try to enter a command using `System.Diagnostics.Process.StandardInput.WriteLine` to zsh, it is not entered.

### Reproduction Steps

The following code can be easily checked: 
```fsharp
open System.Diagnostics
open System.Text

[<Literal>]
let private zsh' = "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal"

let exec () =
  use p = 
    ProcessStartInfo (zsh',
      UseShellExecute = false,
      RedirectStandardInput = true,
      RedirectStandardOutput = true,
      CreateNoWindow = true)
    |> System.Diagnostics.Process.Start

  let stdout = StringBuilder()    
  p.OutputDataReceived.Add (fun e -> if e.Data <> null then stdout.AppendLine(e.Data) |> ignore)
  p.BeginOutputReadLine()
  p.StandardInput.WriteLine "ls ./"
  p.StandardInput.WriteLine "exit"
  p.WaitForExit()
  stdout.ToString()
```
It is reproduced for both net6.0 and net7.0.

### Expected behavior

Must be able to enter commands into zsh with `System.Diagnostics.Process.StandardInput.WriteLine` and get execution results.

### Actual behavior

`System.Diagnostics.Process.StandardInput.WriteLine` cannot be used to enter commands into zsh, so `exit` is not executed and `System.Diagnostics.Process.WaitForExit` waits indefinitely.

### Regression?

No idea.

### Known Workarounds

Nothing.

### Configuration

- Which version of .NET is the code running on?
→ net6.0 / net7.0 
- What OS and version, and what distro if applicable?
→ macOS Venture 13.1
- What is the architecture (x64, x86, ARM, ARM64)?
→ ARM64

**Comment by drasticactions** [comment]
@tatsuya-midorikawa I believe your issue is that you're running `Terminal.app` instead of `zsh` itself, so you're feeding commands into the void. If you use

`let private zsh' = "/bin/zsh"` instead, it should work.

<img width="805" alt="スクリーンショット 2023-01-15 19 42 46" src="https://user-images.githubusercontent.com/898335/212536214-ff50c4e4-d3d0-48e2-99c3-a64f1f9af408.png">

<img width="484" alt="スクリーンショット 2023-01-15 19 42 56" src="https://user-images.githubusercontent.com/898335/212536224-85cb2427-af31-49b6-80b9-4d633aad0da7.png">

**Comment by adamsitnik** [comment]
@drasticactions thank you for your help, I believe this answers the question so I am closing.
