### ISSUE TITLE
builder.Services.Configure bind configuration multiple times

### ISSUE THREAD

**Issue by kzhui125** [dotnet/runtime#80669]
### Description

when use builder.Services.Configure to bind configuration multiple times, I expect get the same result as binding once.

### Reproduction Steps

appsettings.json:

```json
{
    "Primary": {
        "List": [
            "A",
            "B",
            "C"
        ]
    },
    "AllowedHosts": "*"
}
```

Program.cs

```cs
using Microsoft.Extensions.Options;

var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<PrimarySettings>(builder.Configuration.GetSection("Primary"));
builder.Services.Configure<PrimarySettings>(builder.Configuration.GetSection("Primary"));

var app = builder.Build();

app.MapGet("/", (IOptions<PrimarySettings> options) =>
{
    int count = options.Value.List.Count;
    return $"hello";
});

app.Run();


public class PrimarySettings
{
    public required List<string> List { get; set; }
}
```

### Expected behavior

count is 3

### Actual behavior

count is 6

<img width="761" alt="image" src="https://user-images.githubusercontent.com/11925432/212546329-b82daa43-b502-4904-912b-c1c6f1486bb0.png">

**Comment by tarekgh** [comment]
You are calling the configuration binding twice. It is expected the same created binding instance to be used when performing these two-configuration binding which will just add the configuration elements again. What you are seeing is the expected behavior. The question is why you are binding twice to the same configuration?
