### ISSUE TITLE
System.Drawing.Common no longer cross-compatible - stalling migration to .net 7

### ISSUE THREAD

**Issue by SpiraMira** [dotnet/runtime#80837]
### Description

- we develop on macOS + Xcode and were betting on long term .net core cross-compatibility across the board.

- One of the driving goals with .net core was cross-compatibility - **that's why we consider this a bug.**

- While we are refactoring our solution to avoid using System.Drawing.Common in favor of other 3rd party alternative drawing engines, other 3rd party libraries are still based on cross-compatible System.Drawing.Common v5 or v6 : a local downgrade can also work ->  Unfortunately System.Windows.Extensions v7 references System.Drawing.Common v7 which presents a build conflict for our local .net 7 project.

- the industry obviously needs more time to catch up - why not re-enable some sort of workaround like we had in .net 6?  

### Reproduction Steps

- create a .net core v7 project that includes System.Configuration.ConfigurationManager
- include a reference to a 3rd party drawing engine that depends on a cross-compatible System.Drawing.Common like v5
- include a reference to System.Drawing.Common v5 in a your .csproj (attempt to downgrade the System.Drawing.Common version to something compatible with macOS)
- the following build error occurs 
- `System.Configuration.ConfigurationManager 7.0.0 -> System.Security.Permissions 7.0.0 -> System.Windows.Extensions 7.0.0 -> System.Drawing.Common (>= 7.0.0) 
`

### Expected behavior

better support for macOS or Nix .net 7 based development 
re-enable .net 6 like  workarounds for System.Drawing.Common (like "System.Drawing.EnableUnixSupport": true)

### Actual behavior

does not break with NU1605

### Regression?

no

### Known Workarounds

none

### Configuration

.net7
macOS Ventura 13.1
arm64

**Comment by stephentoub** [comment]
This is by design.  It was removed in https://github.com/dotnet/runtime/pull/64084, following the deprecation plans outlined in https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md.

@ericstj, I don't see a breaking change notification in https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0.  Are we missing one?

**Comment by ericstj** [comment]
Correct, this is by design.  The .[NET 6 breaking change doc](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) mentions the removal in .NET 7 but we were missing an explicit new doc in the .NET 7 list.  I've filed that here: https://github.com/dotnet/docs/issues/33653

In this case, I believe the problem raised by @SpiraMira is that ConfigurationManager also brings in System.Drawing.Common.  I believe we would also [discourage](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Configuration.ConfigurationManager/README.md#systemconfiguration) the use of System.Configuration.ConfigurationManager in cross-platform / new code (cc @dotnet/area-system-configuration).  This package was only brought back for .NETFramework / Windows compatibility.  @SpiraMira are you able to move of your use of ConfigurationManager as well and move to a different library like Microsoft.Extensions.Configuration?

**Comment by SpiraMira** [comment]
> Correct, this is by design. The .[NET 6 breaking change doc](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) mentions the removal in .NET 7 but we were missing an explicit new doc in the .NET 7 list. I've filed that here: [dotnet/docs#33653](https://github.com/dotnet/docs/issues/33653)
> 
> In this case, I believe the problem raised by @SpiraMira is that ConfigurationManager also brings in System.Drawing.Common. I believe we would also [discourage](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Configuration.ConfigurationManager/README.md#systemconfiguration) the use of System.Configuration.ConfigurationManager in cross-platform / new code (cc @dotnet/area-system-configuration). This package was only brought back for .NETFramework / Windows compatibility. @SpiraMira are you able to move of your use of ConfigurationManager as well and move to a different library like Microsoft.Extensions.Configuration?

interesting - am I to understand that Microsoft.Extensions.Configuration has no such dependency to system.drawing.common v7 - we will investigate that option and report back here.
