### ISSUE TITLE
[API Proposal]: Regex .ctor(string, TimeSpan)

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/runtime#80835]
### Background and motivation

Currently when trimming code that makes use of ```Regex``` and friends it is impossible to construct a ```Regex``` instance which specifies a pattern, and timeout without inadvertently bringing in the non-backtracking implementation.

The constructor we would need to use in order to specify culture and timeout is as follows:

```csharp
public Regex(string pattern, RegexOptions options, TimeSpan matchTimeout);
```

The problem is that the trimmer is unable to trim out the following code when Regex options are passed in:

```csharp
if ((options & RegexOptions.NonBacktracking) != 0)
{
    // CANNOT TRIM THIS CODE!!!!
    // If we're in non-backtracking mode, create the appropriate factory.
    factory = new SymbolicRegexRunnerFactory(tree, options, matchTimeout);
}
else
{
    if (RuntimeFeature.IsDynamicCodeCompiled && (options & RegexOptions.Compiled) != 0)
    {
        // If the compile option is set and compilation is supported, then compile the code.
        // If the compiler can't compile this regex, it'll return null, and we'll fall back
        // to the interpreter.
        factory = Compile(pattern, tree, options, matchTimeout != InfiniteMatchTimeout);
    }

    // If no factory was created, fall back to creating one for the interpreter.
    factory ??= new RegexInterpreterFactory(tree);
}
```

In scenarios we are trying to optimize binary size from native AOT publishing this results in an extra ~800KB of binary size for a feature that we do not use. This is already a recognized issue, for example the following text can be found in an internal constructor within the ```Regex``` class:

```csharp
internal Regex(string pattern, CultureInfo? culture)
{
    // Validate arguments.
    ValidatePattern(pattern);

    // Parse and store the argument information.
    RegexTree tree = Init(pattern, RegexOptions.None, s_defaultMatchTimeout, ref culture);

    // Create the interpreter factory.
    factory = new RegexInterpreterFactory(tree);

    // NOTE: This overload _does not_ delegate to the one that takes options, in order
    // to avoid unnecessarily rooting the support for RegexOptions.NonBacktracking/Compiler
    // if no options are ever used.
}
```

This internal constructor is used when the ```new Regex(string)``` constructor is used, and by the ```Regex.RegexCache``` internal class with the specific purpose of allowing this code to be trimmed out.

The goal of this proposal is to mark the existing internal constructor as public and introduce an additional constructor which takes a TimeSpan to specify the timeout within resulting in the non-backtracking implemenetation being rooted for the purposes of trimming.

### API Proposal

```diff
namespace System.Text.RegularExpressions;

public class Regex
{
+    public Regex(string pattern, TimeSpan matchTimeout) // new
}
```

### API Usage

```csharp
var r2 = new Regex("mypattern", TimeSpan.FromSeconds(1));
```

### Alternative Designs

Originally this proposal included adding a ```CultureInfo?``` parameter to the constructor, but after the discussion below it makes sense to stick to the convention in .NET of setting ```CultureInfo.CurrentCulture``` instead prior to constructing the regular expression (at which point the constructed regular expression would adopt the current culture).

### Risks

This risk with this change is that we are introducing constructors where a particular trimming benefit is a side effect that subsequent changes could break. Hopefully at some point in the future the trimmer can handle constant propagation with enum flag situations which would have made this change unnecessary, but that could take some time.

However, we believe these additional constructors could be considered "missing" from the framework anyway.

**Comment by stephentoub** [comment]
Thanks.

This is focused on addressing one very specific use of Regex.  The moment someone wanted to use any other option, like RegexOptions.MultiLine, these constructors would no longer suffice.  For some options, a developer could employ inline options (e.g. `(?m)`), but for others (e.g. RegexOptions.ECMAScript or RegexOptions.RightToLeft), there's no way to specify that, and inline options for these don't make sense as they are top-level only (something like `(?i)` for ignore case can be specified effectively anywhere in the pattern and is scoped to applying only to a particular segment of the pattern).

There's also RegexOptions.Compiled.  A developer can care about trimming for scenarios other than NativeAOT/wasm, where reflection emit is available and where Compiled is a valuable tool for performance in situations where the pattern is only known dynamically (and if it's known statically, this proposal isn't needed anyway because the source generator can/should be used).  And this proposal doesn't accommodate trimming out the non-backtracking engine if Compiled is specified; similarly it doesn't accommodate trimming out the reflection-emit engine if NonBacktracking is specified. (I also continue to believe until proven otherwise that, moving forward, the majority of scenarios where a pattern is dynamically specified would be likely to benefit from NonBacktracking, as the dynamism suggests the pattern may less trusted / vetted than it would have been if it were statically known, and a key benefit of NonBacktracking is being able to tackle untrusted patterns safely.) It's also likely in the future that NonBacktracking | Compiled will be meaningful (today the Compiled is nop'd as we don't do anything special with reflection emit while also using non-backtracking, but that was primarily due to lack of time to take advantage of it... Compiled is really just a flag that means "use reflection emit if it's useful in order to optimize whatever processing is being done, and there are aspects of non-backtracking that would benefit from that... and from source generation, which is also on our todo list).

I'm also not keen on adding CultureInfo to the public surface area of Regex.  It's debatable whether Regex should have considered culture at all years ago when it was initially designed, but that's water under the bridge at this point.  Its design is to just pick up the ambient culture and for users to set the current CultureInfo if they need to influence it, with CultureInfo.InvariantCulture being a fast path for what probably should have been the default anyway.  (It actually is the default for source generation, since picking the ambient culture from a build-time tool is fraught with peril.)  I don't want to make culture more explicit in the existing APIs as a result (culture only has any impact when ignore case is used, and even then it only impacts a very small handful of specially-cased characters related to Turkish i), and if someone really needs to change the culture, to use the existing mechanism to do so: setting the current culture so that Regex picks it up, as it was designed to do.  There are also many Regex APIs that pick up the current culture, including not just the public ctor but also all public static overloads of Count, EnumerateMatches, IsMatch, Match, Matches, Replace, and Split, and I don't want to end up in a situation where we slippery slide into adding new overloads for all of those, too.

If it's absolutely necessary to fix this trimming issue with ASP.NET / NativeAOT and we don't have another good option (like making it opt-in at ASP.NET level so that all of regex is trimmed away by default, which is even better than just trimming away part of it), I would be ok adding just:
```C#
public Regex(string pattern, TimeSpan matchTimeout)
```
As I understand the issue, that should solve the problem and without adding more culture-related surface area to Regex.  ASP.NET can for its specific use-case utilize the existing mechanism for changing the culture:
```C#
CultureInfo existing = CultureInfo.CurrentCulture;
Regex r;
try
{
    r = new Regex("...", timeout);
}
finally
{
    CultureInfo.CurrentCulture = existing;
}
```

And, finally, since I'll keep suggesting it until my face turns blue, this is a trimming problem, and there's a trimming solution:
https://github.com/dotnet/linker/issues/1868
I think that's a much better long-term answer to this problem (and others like it) than one-off new APIs to workaround it like this.  I understand it's a challenging problem in the trimmer, but I expect it will also have much larger reward.

**Comment by mitchdenny** [comment]
Thanks for the detailed response. I think adding ```Regex(string, TimeSpan)``` would get us where we need to go and I agree that it doesn't make sense to add ```CultureInfo``` to the public API given it isn't there already (even though we see it on the internal constructors). I've adjusted the proposal to match this.

I think that given that we already have a ```Regex(string,RegexOptions,TimeSpan)``` variant of the constructor, then ```Regex(string,TimeSpan)``` shouldn't be too hard to adopt and is useful above and beyond the trimming implications mentioned above.

**Comment by davidfowl** [comment]
> It actually is the default for source generation, since picking the ambient culture from a build-time tool is fraught with peril.

That's interesting, so there's no way to change the culture with the source generated regex?

**Comment by stephentoub** [comment]
> > It actually is the default for source generation, since picking the ambient culture from a build-time tool is fraught with peril.
> 
> That's interesting, so there's no way to change the culture with the source generated regex? Or did I misunderstand?

There is. Since passing via CurrentCulture isn't viable with the generator, and since we don't even have the option of passing in a CultureInfo, we added to the attribute the ability to take an optional string culture name. We strongly considered not doing so and simply not having it be configurable at all, but we didn't want to the lack of Turkish i support to be a reason to avoid using the generator.

**Comment by mitchdenny** [comment]
@stephentoub and @davidfowl do you think that the API proposal as it currently stands is ready for API review?

**Comment by stephentoub** [comment]
I only want to add it if it's truly needed. If we're pursuing the approach to make regex entirely opt-in for the slim routing, we won't need this, right?

**Comment by davidfowl** [comment]
I would wait until we get the feature into ASP.NET Core first, so that we better understand the edges, then we can come back to this API.

**Comment by mitchdenny** [comment]
We have now done the work in ASP.NET Core to completely Regex in the slim builder scenario so I don't think we'll need this anymore. Closing for now but re-open if folks think there is something worth exploring further there.
