### ISSUE TITLE
SortedList<> Enumerator is allocated on the heap

### ISSUE THREAD

**Issue by emilsteen** [dotnet/runtime#81128]
### Description

When looping over a `SortedList<>` with `foreach()` the Enumerator gets allocated on the heap. With `Dictionary<>` (and probably most other collections) the Enumerator is allocated on the stack and does not show any allocation in Benchmark.NET.

### Configuration

Benchmarked with .NET 6.0.13 (6.0.1322.58009), X64 RyuJIT SSE4.2, but also confirmed in .NET 7.
Tested on a small Hyper-V client running Windows 10 (x64).

### Data

The benchmarking was done by repeating a foreach() loop on a small SortedList<int, int> with 15 items, one million times. 
This is approximately what is done on our production server.

### Analysis

Sometime after .NET Framework the `SortedList<>` Enumerator switched from class to struct, but the Enumerator is still allocated on the heap.

After some local benchmarking I found the reason for this discrepancy between `SortedList<>` and `Dictionary<>`. The difference is that the `GetEnumerator()` in `SortedList<>` has return type `IEnumerator<KeyValuePair<TKey, TValue>>`, while the the `GetEnumerator()` in `Dictionary<>` has return type `Enumerator`. Changing the return type on `GetEnumerator()` in `SortedList<>` removes the allocation on the heap.

In my local benchmarking the current `GetEnumerator()` takes at least twice as much time as the `GetEnumerator()` with return type `Enumerator`. 

I've found the same return type in `GetEnumerator()` in `ReadOnlyDictionary`, which also seems to be affected by this heap allocation. And also a few other collections.

**Comment by stephentoub** [comment]
> Changing the return type on GetEnumerator() in SortedList<> removes the allocation on the heap.

Yes.  However, it's a breaking change; the return type is part of the signature, so any existing binary that was foreach'ing a SortedList would break if changed it.

**Comment by emilsteen** [comment]
> Yes. However, it's a breaking change; the return type is part of the signature, so any existing binary that was foreach'ing a SortedList would break if we changed it.

Thank you for your clarification! That is an important reason I did not think of.

Is there a simple explanation to why the return type changes the allocation?

**Comment by stephentoub** [comment]
> Is there a simple explanation to why the return type changes the allocation?

Boxing.
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing
"Boxing is the process of converting a [value type](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types) to the type object or to any interface type implemented by this value type."
To return the Enumerator struct as an IEnumerator, it results in allocated a boxed object to store that struct.

**Comment by emilsteen** [comment]
> Boxing. 

Thank you again! I was only aware of boxing to object, not to interfaces.

**Comment by koszeggy** [comment]
Maybe not the answer you are looking for but you can try my [`CircularSortedList<TKey, TValue>`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Collections_CircularSortedList_2.htm), which is functionally compatible with `SortedList<TKey, TValue>` with a few optimizations:
* It has both value type and reference type enumerators. In a simple foreach the value enumerator is used, whereas generally (such as in a LINQ query) the reference type one, which prevents using a boxed enumerator.
* Adding a new element to the end/beginning (eg. populating from an already sorted collection) is an O(1) operation. In contrast, Inserting elements at the end of a `SortedList<TKey, TValue>` has an O(log n) cost because a binary search is performed for the key even if its value is greater than the last value, and has an O(n) cost when the new element has to be inserted at the first position because in that case all of the elements are shifted in the underlying arrays.

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
