### ISSUE TITLE
Consider adding IEqualityOperators<string, string, bool> to System.String

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#81173]
System.Numerics.IEqualityOperators<T, T, bool> is very helpful with generics.
Since the operators (== and !=) are already there, please extend this interface to System.String.

**Comment by dakersnar** [comment]
We discussed this last year when designing Generic Math and decided against it. 

For one, IEquatable already achieves the general need and is implemented by far more types since it's been around since .NET 2.0. 

Additionally, for String in particular, using == isn't generally what you want in the first place. You typically want some form of Equals where you pass in StringComparison.Ordinal or OrdinalIgnoreCase or some other relevant parameter. See the note at the bottom of this article for more details: https://learn.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings. Basically, by putting IEqualityOperators on String, we would be encouraging users to follow a pattern that we no longer recommend in most cases.
