### ISSUE TITLE
ILVerify fails to verify code that passes Nullable<T> to parameter with unmanaged constraint

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#81177]
### Description

The following code should compile without error and be verifiable

```C#
F(new Nullable<int>(1)); // error CS8377

void F<T>(T value) where T : unmanaged
{
}
```

Currently the Roslyn compiler reports an error (tracked by issue https://github.com/dotnet/csharplang/discussions/6918):

```
CS8377: The type 'int?' must be a non-nullable value type, along with all fields at any level of nesting,
in order to use it as parameter 'T' in the generic type or method 'Program.F<T>(T)'
```

If this code is emitted by other tool and the binary passed to ILVerify, it reports
`Method instantiation has unsatisfied method type parameter constraints.`.

The following code compiles and verifies:

```C#
F(new S());

void F<T>(T value) where T : unmanaged
{
}

struct S
{
    int? a;
}
```

### Reproduction Steps

See above

### Expected behavior

See above

### Actual behavior

See above

**Comment by jkotas** [comment]
This looks by design. `where T : unmanaged` is compiled by Roslyn into `where T: struct` with `UnmanagedType` modopt.

The problem is that `Nullable<T>` does not satisfy the `where T: struct` constraint.

**Comment by tmat** [comment]
> The problem is that `Nullable<T>` does not satisfy the `where T: struct` constraint.

I don't follow, `Nullable<T>` is defined like so:

```C#
public struct Nullable<T> where T : struct { ... }
```

If I define

```C#
public struct MyNullable<T> where T : struct { ... }
```

The type `MyNullable<int>` satisfies the `unmanaged` constraint and there is no error.

**Comment by jkotas** [comment]
`Nullable<T>` is not ordinary struct. It is special cased in number of ways in the type system.

In particular, `Nullable<T>` does not satisfies the `struct` constraint. The struct is called `NotNullableValueTypeConstraint` at IL level that makes it more obvious.

You example does not compile and fails verification for the same reason that this does not compile and fails verification:
```
F<Nullable<int>>();

void F<T>() where T : struct { }
```

**Comment by tmat** [comment]
I see, but wouldn't it make sense to allow `Nullable<T>` to satisfy the `struct` constraint?

**Comment by jkotas** [comment]
It would be major breaking change with number of ripple effects. A great deal of thought with multiple iterations went into the `Nullable<T>` design back in the day before we arrived at the current design.

For example, `Nullable<Nullable<T>>` is disallowed thanks to the `struct` constraint today. If we were to relax the struct constraint, `Nullable<Nullable<T>>` would be allowed. What would be the semantics of boxing/unboxing `Nullable<Nullable<int>>`?

**Comment by tannergooding** [comment]
`Nullable<Nullable<int>>` would be disallowed due to it being recursive at runtime.

There is really no reason why Roslyn couldn't specially recognize the type or the scenario at compile time as it already does for the direct case.

-- Not necessarily saying taking the change is appropriate, just indicating that the recursive problem shouldn't be a blocker and could be handled fairly easily.

**Comment by jkotas** [comment]
> `Nullable<Nullable<int>>` would be disallowed due to it causing a cycle in the struct layout

`Nullable<Nullable<int>>` does not have any cycles in the layout. The following works just fine:
```csharp
var x = new MyNullable<MyNullable<int>>();

public struct MyNullable<T> where T : struct
{
    internal bool hasValue;
    internal T Value;
}
```

> the recursive problem shouldn't be a blocker and could be handled fairly easily.

The problem is semantics in general. To give you another example:

This compiles fine today (w/ `<Nullable>enable</Nullable>`):
```csharp
void f<T>(T val) where T: struct
{
    object o = val;
}
```
If we were to relax the struct constraint, it would need to start generating "warning CS8600: Converting null literal or possible null value to non-nullable type." and the code would have to be written like this instead:
```csharp
void f<T>(T val) where T: struct
{
    object? o = val;
}
```

Relaxing the struct constraint would have many ripple effects like this.

**Comment by tannergooding** [comment]
> Nullable<Nullable<int>> does not have any cycles in the layout.

Ah, right, my mistake. I was thinking of `Nullable<T>` cannot contain `Nullable<T>` but that doesn't necessarily apply to `Nullable<T>` containing `Nullable<U>`.

**Comment by tmat** [comment]
@jkotas Makes sense. Thanks!

**Comment by TahirAhmadov** [comment]
I'm not very convinced by the reasoning here. Specifically, if the requirement is to prevent `Nullable<Nullable<int>>`, why not use a static ctor which throws with such generic arguments?

**Comment by jkotas** [comment]
> isn't it possible to "special case" unmanaged constraint somehow?

It would again produce number of breaking changes. For example, the ` f<T>` breaking change from https://github.com/dotnet/runtime/issues/81177#issuecomment-1404605625 applies for the special-cased unmanaged constraint as well. Or consider situations where libraries compiled with old definition of the constraint are combined with libraries compiled with new definition of the constraint. 

It would be more workable to introduce a new constraint instead of trying change the specification of the existing constraints. This would be a new .NET feature that increases concept count, so we would need a very strong justification for it.
