### ISSUE TITLE
Integer.TryParse with Nothing object

### ISSUE THREAD

**Issue by teunlielu** [dotnet/runtime#81225]
### Description
Dim a As Object = Nothing
	If Integer.TryParse(a, Nothing)
		Debug.WriteLine("Is int")
	Else
		Debug.WriteLine("Is not int")
       End If

error:
Overload resolution failed because no Public 'TryParse' is most specific for these arguments:
    'Public Shared Function TryParse(s As String, ByRef...

### Configuration

.net 4.8 Oke
.net core  3.1 error
.Net 5.0 error
.net 6.0.13 error
.Net 7.0.12 Oke.

### Other information
Please fixed for .net 6 to

**Comment by huoyaoyuan** [comment]
Can you provide your VB compiling configurations, like `Options Explicit` and `Options Infer`?
I believe it's caused by the difference of VB casting settings. Passing `Object` directly to the first parameter of `Integer.TryParse` is never valid.

**Comment by teunlielu** [comment]
I have testing. No result. error (compiler does not know which function to choose)

Overload resolution failed because no Public 'TryParse' is most specific for these arguments:
'Public Shared Function TryParse(s As String, ByRef...

**Of cource result must: Debug.WriteLine("Is not int")**

**Comment by huoyaoyuan** [comment]
https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdgHwPIAcYEsD2yABAMozw4DGMh6yAsAFCMCSAtpnvDAM4kCe3GAFNWjAAqIIwSoQCyeACaJgQwmPh4A5vACGohoUNrJ0iiUlydOZAAoAlIyNPCAERytCOwgEFe6CABWQlSEALyEAHJ4MAAW1pqOzobMAGaEzMjCmkLwAHQAKvB8Yjrw3EI2OlCR0XHImg4GSc4AwgTceCq5AOrkwgAy1hUARMy81jDDjc2EAKLA5Ykzhm3IHV29OANDNqO8yNGEE1NLzrPICukpp+eXxJKMt3KKykJAA===

`Option Strict` can make it a compilation error, but not the same error.

**Comment by teunlielu** [comment]
sorry i testing wrong.  you get build error.
why are there differences between .net version with Option Strict off. Is this bug?
And if so, will it be adjusted.
Converting from .net48 to .net 6 unnecessarily risky. sure if version after it is fixed again.

**Comment by tannergooding** [comment]
@KathleenDollard, could you weigh in here?

The APIs exposed in .NET 6 were:
[TryParse(String, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-6.0#system-int32-tryparse(system-string-system-int32@))
[TryParse(ReadOnlySpan<Char>, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-6.0#system-int32-tryparse(system-readonlyspan((system-char))-system-int32@))
[TryParse(ReadOnlySpan<Char>, NumberStyles, IFormatProvider, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-6.0#system-int32-tryparse(system-readonlyspan((system-char))-system-globalization-numberstyles-system-iformatprovider-system-int32@))
[TryParse(String, NumberStyles, IFormatProvider, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-6.0#system-int32-tryparse(system-string-system-globalization-numberstyles-system-iformatprovider-system-int32@))

In .NET 7 we expanded this to also include:
[TryParse(String, IFormatProvider, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-7.0#system-int32-tryparse(system-string-system-iformatprovider-system-int32@))
[TryParse(ReadOnlySpan<Char>, IFormatProvider, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-7.0#system-int32-tryparse(system-readonlyspan((system-char))-system-iformatprovider-system-int32@))

I'm not familiar enough with how VB does overload resolution or conversions here to understand how the code is compiling in the first place, nor why these new overloads break ambiguity.

This is notably not something we can or will fix for already shipped versions of .NET

**Comment by KlausLoeffelmann** [comment]
This is working as expected and consistent.

When `Option Strict` is switched off (also known as _[Visual Basic Typeless Programming](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/considerations-in-overloading-procedures#typeless-programming-as-an-alternative-to-overloading)_, the compiler attempts implicit conversions from one type to another desired type based on the best possible overload resolution. This is done based on what types are actually defined and what types in the different overload signatures are expected. There is a special handling by the compiler for `ByRef` parameters which are passed `Nothing`: here, the compiler automatically generates type-compliant temporary variables, and then it later just discards the returned result.

So, this (compiled with `Option Strict Off`)...

``` VB
        Dim a As Object = Nothing

        If Integer.TryParse(a, Nothing) Then
            Debug.WriteLine("Is int")
        Else
            Debug.WriteLine("Is not int")
        End If
```

...the compiler turns into this:

```VB
        ' a will automatically get replaced by a temporary variable,
        ' which will fit the first parameter of the method.
        Dim s As String = a.ToString()

        ' Nothing gets automatically replaced by a temporary variable...
        Dim result As Integer = 0

        ' whose result will be discarded.
        If Integer.TryParse(s, result) Then
            Debug.WriteLine("Is int")
        Else
            Debug.WriteLine("Is not int")
        End If
```

This is By Design.
Here is an [overview of how Overload Resolution works in VB](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/overload-resolution):

**Comment by teunlielu** [comment]
Explaining the correct behavior logically is because functions have been added. But is behavior desirable that increases the difference in behavior and the risk of bugs per framework? 

Note: Option Strict On works better, but then you have to make the most simple conversion yourself. which is often unnecessary work.

**Comment by teunlielu** [comment]
Default is off in VB.

**Comment by KlausLoeffelmann** [comment]
Using Typeless Programming is a manageable risk, since the implicitly generated type conversion code will be generating the most plausible conversion possible. Also, if adding an overload would lead to an ambiguous case, the compiler would point that out with an compile error, and then by adding strongly type parameters can resolve those ambiguities. 

For the best Default setting: For existing projects this cannot change for backwards compatibility reasons. 
For new projects, you can always control what new Default VB `Option...` settings should be applied, by making those adjustments in Tools/Options:

![image](https://user-images.githubusercontent.com/9663150/229612044-3c54581d-7353-42a1-931f-37388e76cd7b.png)
