### ISSUE TITLE
[API Proposal]: JsonConverter to deserialize Dictionary<string,object> as values objects not JsonElements

### ISSUE THREAD

**Issue by smartouss** [dotnet/runtime#81270]
### Background and motivation

Hello,

In Newtonsoft.Json when we deserialize a dictionary of values objects the values get deserialized as the corresponding object (string, int...) but when using System.Text.Json converter values comes as JsonEelement and we need to cast them again, i couldn't find something that say this already supported or no but it will be great if it get added.

### API Proposal

```csharp
namespace System.Text.Json;

var dic = JsonConvert.Deserialze<IDictionary<string,object>>(json)
```

### API Usage

```csharp
// Fancy the value
namespace System.Text.Json;

var dic = JsonConvert.Deserialze<IDictionary<string,object>>(json)

foreach(item in dic)
{
//return a primitive type instead of JsonEelement
  var type =   dic.First().Value.GetType();
}
```

**Comment by eiriktsarpalis** [comment]
This is by design -- System.Text.Json does not support polymorphic `object` deserialization because this is a known vector for remote code execution. `object` instances are deserialized either as `JsonElement` or `JsonNode` instances and you can control this via the `JsonSerializerOptions.UnknownTypeHandling` setting. `JsonNode` might offer more flexibility w.r.t. casting primitive values:
```C#
var options = new JsonSerializerOptions { UnknownTypeHandling = JsonUnknownTypeHandling.JsonNode };
var dic = JsonSerializer.Deserialize<IDictionary<string, object>>("""{"id" : 42 }""", options);
Console.WriteLine((int)(JsonNode)dic["id"]);
```

**Comment by smartouss** [comment]
that would be a problem migrating from newtonsoft as we have to go through all our code to handle those cases, it would be great if there's way to disable it.

**Comment by eiriktsarpalis** [comment]
We have no plans on adding support for polymorphic deserialization for `object`, because doing so would be introducing potential security issues in applications using STJ. The same concern also applies to Json.NET and uses of the `TypeNameHandling` setting, see https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2326

**Comment by smartouss** [comment]
I see the issue here but my case i don't use `TypeNameHandling`, i simply serialize a `Dictionary<string,object>` that contains some primitives and strings and not complex objects, anyway thanks for the info.
