### ISSUE TITLE
ConfigurationBinder.Get<T> ignores value types .ctor

### ISSUE THREAD

**Issue by ppilev** [dotnet/runtime#81298]
Given the following configuration the test won't pass:

``` C#
    var configuration = new ConfigurationBuilder()
        .AddInMemoryCollection(new Dictionary<string, string>()
        {
            { "Key", "my-key" },
            { "Value", "my-value" },
        })
        .Build();

    var instance = configuration.Get<KeyValuePair<string, string>>();
    Assert.That(instance.Key, Is.EqualTo("my-key"));
    Assert.That(instance.Value, Is.EqualTo("my-value"));
```
Seems that for value types `ConfigurationBinder.CreateInstance` method will be using only the default parameterless constructor.

**Comment by tarekgh** [comment]
> Seems that for value types ConfigurationBinder.CreateInstance method will be using only the default parameterless constructor.

That is right. only default parameter less constructor is used in the binding. 

> IMO the problematic code line is [ConfigurationBinder.cs#L411](https://github.com/dotnet/runtime/blob/170587e444c43d5c0080f7b2ea454e37463c832a/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L411) where type.IsValueType should not interfere when hasParameterlessConstructor is set. Seems better to have value types being used as last resort only in case when no suitable constructor was found, i.e.

How will the binder know if there is a suitable constructor? note, the binder has no knowledge about `KeyValuePair<,>` to decide which constructor to use. 

`KeyValuePair<,>` is a read-only struct which does not have any setter to its properties. You can use @KalleOlaviNiemitalo ideas which use a struct with property `init`. something like:

```C#
    public readonly struct KeyValue<TKey, TValue>
    {
        public TKey Key { get; init; }
        public TValue Value { get; init; }
    }
```

I am closing the issue as what you are seeing is the expected behavior according to how the binder is currently working. We don't have any plan so far to change that.
