### ISSUE TITLE
Need _udiv128 intrinsic as a .Net API, eg, Math.BigDivRem.

### ISSUE THREAD

**Issue by shonk-msft** [dotnet/runtime#81337]
The `ulong Math.BigMul(ulong a, ulong b, out ulong low)` multiplies two 64 bit values and produces the full 128 bit product. This roughly corresponds to the `x64` C intrinsic named `_umul128` (although for some reason the return value and out parameter are swapped - the C intrinsic puts the high bits in the out parameter and returns the low bits, probably because the low bits naturally end up in the rax register). We need the inverse, namely an intrinsic method that corresponds to the `x64` intrinsic named `_udiv128`.

This is needed to implement dividing an arbitrarily large unsigned integer (stored as an array of ulong values) by a single ulong value. That is, we want to be able to implement something like:
```csharp
void DivOne(int count, ulong[] num, ulong den, ulong[] quo, out ulong rem)
{
    // The caller should ensure that den > 0. Given that, we’re guaranteed that hi < den throughout.
    ulong hi = 0;
    for (i = count; --i >= 0; )
        quo[i] = Math.BigDivRem(hi, num[i], den, out hi);
    rem = hi;
}
```
This is the "inverse" of the following, which computes a * b + carry and stores the result in res and carry:
```csharp
void MulOneAdd(int count, ulong[] a, ulong b, ulong[] res, ref ulong carry)
{
    ulong c = carry;
    for (int i = 0; i < count; i++) {
        ulong tmp = Math.BigMul(hi, a[i], b, out res[i]);
        if ((res[i] += c) < c)
            tmp++;
        c = tmp;
    }
    carry = hi;
}
```
Of course, this demonstrates that a "fused mul-add" would also be useful, then that latter would simplify to:
```csharp
void MulOneAdd(int count, ulong[] a, ulong b, ulong[] res, ref ulong carry)
{
    ulong c = carry;
    for (int i = 0; i < count; i++)
        c = Math.BigMulAdd(hi, a[i], b, c, out res[i]);
    rem = hi;
}
```

**Comment by AaronRobinsonMSFT** [comment]
@tannergooding Should this go under the Numerics tag or since this is an intrinsic do we mark it with codegen?

**Comment by tannergooding** [comment]
Numerics, given what's being requested it isn't representable by a 1-2 CPU instructions.

**Comment by shonk-msft** [comment]
@tannergooding, can you clarify what you mean by "it isn't representable by a 1-2 CPU instructions"? For x64 we'd like it to resolve to exactly the div instruction.

**Comment by huoyaoyuan** [comment]
For x86/x64 DivRem, it's exactly #27292.

**Comment by tannergooding** [comment]
@shonk-msft, sorry I misunderstood the request initially. However, it's worth noting such an API is only intrinsic for 64-bit systems.

That being said, what is blocking the current API from being used? That is, `_umul128` is effectively `ulong BigMul(ulong left, ulong right, out ulong upper)` but we expose `ulong BigMul(ulong left, ulong right, out ulong lower)`. This should still achieve the "right thing", just inverse how the assignments are done.

If we were to expose a "new" API here, it would notably still not match the native intrinsic. It would end up looking like `(ulong Lower, ulong Upper) BigMul(ulong left, ulong right)` (or potentially even `UInt128 BigMul(ulong left, ulong right)`).

> "fused mul-add would also be useful"

Fused isn't the term I'd use, it has a specific semantic with regards to rounding. It would probably be named `BigMultiplyAddWithCarry` or similar instead. That being said, we have a general tracking issue around such "carry" APIs and it being non-trivial for the JIT to support them today due to its limited tracking of flags as a type of side effect.

We do have some basic support, in the form of things like `long/ulong decomposition` on 32-bit, but those don't allow passing in the "carry" as external state

**Comment by shonk-msft** [comment]
We need this for x64 hardware. If/when we care about other hardware, yes, we'd need a different solution.

Nothing is wrong with the current `Math.BigMul` api - the _main_ request is for the inverse operation, a `BigDivRem` that divides (unsigned 128 bits by 64 bits to produce 64 bit quotient and 64 bit remainder). This corresponds directly to the `_umul128` intrinsic, which is for the x64 `div` instruction.

Much lower priority is the suggestion that a fused multiple add would be useful. And "fused multiple add" is the common term for computing a * b + c (searching for it will show many results).

**Comment by tannergooding** [comment]
> a BigDivRem that divides (unsigned) 128 bits by 64 bits to produce 64 bit quotient and 64 bit remainder. This corresponds directly to the _udiv128 intrinsic, which is for the x64 div instruction.

This is being tracked/added already (as huoyaoyuan pointed out): https://github.com/dotnet/runtime/issues/27292.

We could likely also special-case and recognize `UInt128 / UInt64` if that was more generally desirable. We'd just have to recognize the `UInt128 / op_implicit(UInt64)` pattern.

> And "fused multiple add" is the common term for computing a * b + c (searching for it will show many results)

`FMA` is not quite the same as `MAD` even though both represent computation of `a * b + c`. The differences are covered in most of the search results, particularly the wikipedia article on the topic: https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation

In particular `MultiplyAdd` is when rounding is not a special consideration (that is, it is actually equivalent to doing `(a * b) + c`). `FusedMultiplyAdd` is when rounding is a special consideration (that is, it may produce a different result than the naive `(a * b) + c`)

We accordingly differentiate these two in our own existing APIs (intrinsic or otherwise). As does hardware in its assembly instructions and C/C++ in its own intrinsic functions.

**Comment by shonk-msft** [comment]
Any comment on when a `_udiv128` equivalent might be added? The item referenced above was opened in 2018.

**Comment by tannergooding** [comment]
It will likely be in for .NET 8, there is an active PR (https://github.com/dotnet/runtime/pull/66551) that is almost ready to be merged.

Correctly supporting the multi-register returns and ensuring they could be efficiently handled on the managed side in the face of `out parameters` or tuple returns was non-trivial and is one of the reasons the API has taken so long to get in.

**Comment by tannergooding** [comment]
Closing this as it is covered by `X86Base.X64.DivRem`.

Otherwise, you have access to `UInt128.operator /`. There are potentially other optimizations and improvements we could make to that general API, but those should be tracked separately where appropriate.
