### ISSUE TITLE
Running tests tries to run .NET Framework tests with mono on non-Windows

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#81395]
When I run tests on my Mac now, it seems to be trying to run .NET Framework tests with mono. For example, running this command on my Mac

```shell
./dotnet.sh test src/libraries/System.Security.Cryptography.Pkcs/tests
```

It will first run all of the .NET (Core) tests and everything passes. Great. Then it proceeds to run the .NET Framework test, and gives this error:

```
A total of 1 test files matched the specified pattern.
System.IO.FileNotFoundException: Could not find 'mono' host. Make sure that 'mono' is installed on the machine and is available in PATH environment variable.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.GetMonoPath()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, IInternalTestRunEventsHandler eventHandler)
```

Even if I install mono, the tests will absolutely crash and burn since most of the project I work on that target .NET Framework assume they are running on Windows. Running S.S.C.Pkcs on macOS with Mono with the .NET Framework target has hundreds of failures.

Was there a change that introduced this recently, and, was it intentional? Or did something change in my environment that's making it try to do this?

**Comment by ViktorHofer** [comment]
Probably regressed with https://github.com/dotnet/arcade/commit/e82404fca08383513e0b0b3c5308d4a9b18b7c7a. I will take a look in the next days.

**Comment by Bartleby2718** [comment]
@ViktorHofer Do you happen to have any updates on this?

I think my real question is: what's the suggested way to _exclude .NET Framework tests_? AFAIK exactly one argument is expected for the `--framework` flag of [`dotnet test`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test), so I'm not sure if there's a project-agnostic way of excluding .NET Framework tests in a multi-targeting project.

**Comment by vcsjones** [comment]
> I'm not sure if there's a project-agnostic way of excluding .NET Framework tests in a multi-targeting project.

I've been doing something like this for now.

```
./dotnet.sh test src/libraries/Microsoft.Bcl.Cryptography/tests /p:TargetFramework=net8.0
```

I can't exclude .NET Framework, but I can run a particular framework, which works for my purposes.

**Comment by ViktorHofer** [comment]
I had to put this on the back-burner, unfortunately. We could either change this directly only for runtime or move this issue over into the vstest repository and ask for a switch to not invoke Mono when testing .NET Framework. These days, running .NET Framework via Mono on Unix platforms is a niche scenario.

**Comment by ViktorHofer** [comment]
Just to clarify, I wasn't asking for your team to make a breaking change and remove VSTest's .NET Framework Mono support (which could still be done, but might require more discussion). I was asking if it would be possible to expose a flag when invoking dotnet test (which would also be set via a runsettings variable and/or msbuild property) to disable that code path.

**Comment by nohwnd** [comment]
It would be great if this could be handled on the msbuild level, ideally we should run all the dlls that you give us to run, and in this case we get both .net and .net framework dlls because the build that happens under dotnet test (when used with csproj or sln) is building all the multi-targets. 

Implementing this on vstest level would mean adding a tfm filter, which I don't think is impossible, but might be a bit confusing to use, and because we historically succeed when stuff is not run, we should have do it here as well and it would make ignoring your whole test-suite quite easy. 

E.g. naming the allowed frameworks --framework-filter: dotnet test --framework net8.0 --framework-filter net6.0, net7.0 

This would filter your dlls only to net6.0. and net7.0 dlls from run that targets only net8.0, so tests from 0 assemblies are run. We can warn about --framework and --framework-filter not having any intersection, and fail, but then it is not consistent with many of the other parameters that allow you to get a warning and continue.

**Comment by Bartleby2718** [comment]
@ViktorHofer Thanks for fixing this! Given that .NET 8 is an LTS, is there any chance this can be backported to .NET 8?

**Comment by akoeplinger** [comment]
@Bartleby2718 this only affects development inside of the dotnet/runtime repository so it's not likely we'll backport it.
