### ISSUE TITLE
[API Proposal]: ECDsa.Create() should be marked as obsoleted

### ISSUE THREAD

**Issue by wsq003** [dotnet/runtime#81410]
### Background and motivation

ECDsa.Create() will create an instance with `NIST P521` algorithm which is widely doubted not safe.

see also:
http://safecurves.cr.yp.to/index.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1128792

The default behavior should be safe, or we should not provide it.

### API Proposal

```csharp
[System.Obsolete("Cryptographic factory methods without elliptic-curve parameter are obsolete. The previous default P521 is doubted not safe.", DiagnosticId="xxxxx", UrlFormat="https://aka.ms/dotnet-warnings/{0}")]
public static System.Security.Cryptography.ECDsa? Create ();
```

### API Usage

N/A

### Alternative Designs

An alternative choice is to describe the risk of `NIST P521` in MSDN.

### Risks

The obsolete warning may break some projects from building, if those projects choose to treat build warning as error.

**Comment by vcsjones** [comment]
> http://safecurves.cr.yp.to/index.html

The SafeCurves website from Daniel J. Bernstein (henceforth "DJB") is somewhat controversial, and I think is missing considerable context.

If the SafeCurves website is to be interpreted as you describe, then what you are really advocating for is an almost fully obsoletion of `ECDsa`.

DJBs arguments largely affect _the implementation_ of the ECC scheme. And to that effect, yes ECDSA is known to be a bit hard to implement correctly that is resistant to side channels, and has some sharp edges like the infamous "K" nonce issue. But those are concerns of the implementation of ECDSA, not consumers of it.

But we can't really fully obsolete ECDsa. It's far too popular. The unsafeness of prime-order curves that you cite comes from a (well respected) cryptographer who has competing ideas and (without good context) made arguments that their competing curves are unsafe.

There is some speculation that the NIST curves are problematic for other reasons, but [speculation is about as far as it has gone](https://github.com/google/tink/issues/477#issuecomment-792969185).

> https://bugzilla.mozilla.org/show_bug.cgi?id=1128792

I don't see how this is relevant to the safety of P521. The issue is specifically discussing a mode of Firefox where it can be used to force ["Suite B"](https://en.wikipedia.org/wiki/NSA_Suite_B_Cryptography) algorithms only. P521 is not in Suite B. But neither is SHA-2-512 or AES-192, and we don't believe SHA-2-512 or AES-192 to be broken, either. The concept of Suite B has been deprecated for a while now, anyway.

Largely a lot of the finger pointing at P-521 is that it is just wildly too big, in the same reason that we don't really use RSA with 16,384-bit keys.

Now, do I wish `ECDsa.Create` defaulted to something other than P-521? Yes. But changing it would be a breaking change, and too noisy to obsolete since `var ecdsa = ECDsa.Create(); ecdsa.GenerateKey(ECCurve.NamedCurves.nistP256);` is perfectly valid.

**Comment by bartonjs** [comment]
As @vcsjones said, there's not enough justification for a breaking change, or obsoletion here.
