### ISSUE TITLE
GC does not correctly take into account available cache for a VM

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#81428]
The GC (nor runtime in general) take advantage of the associativity or other information to create better models of the cache. Instead, we effectively take the largest reported cache size “as is” and carry on: https://github.com/dotnet/runtime/blob/main/src/coreclr/gc/windows/gcenv.windows.cpp

What this means is that a VM which was allocated 2 cores of a 64-core/128-thread server believes it has `32MB L3 Cache` available to work with. However, in practice this L3 cache is additionally reported as 16-way associativity which means that we in practice get around `4MB L3 Cache` available for our own use (assuming "perfect" distribution of resources).

Inversely, a dedicate server or workstation that has the entire 64-core/128-threads available is not necessarily limited to this single `32MB L3 Cache`. In fact the server CPU in question has `2x32MB L3 Cache`, each with `16-way associativity`. Meaning that the entire CPU has `64MB L3 Cache`. However, only `32MB L3` cache is directly accessible to one group of `16 cores` and the other `32MB L3` is directly accessible to a different group of 16 cores.

By better accounting for the associativity and allocated processors, we can better scale to the environment we're running in.

**Comment by mangod9** [comment]
@janvorli @Maoni0. @tannergooding, is this for specific hardware configurations, or applies to all recent configurations?

**Comment by tannergooding** [comment]
@mangod9, as best as I can tell it applies to Windows VMs both in Azure and locally. It applies to Win7, 10, and 11.

I did not test the behavior of docker or Linux.

**Comment by Maoni0** [comment]
> in practice this L3 cache is additionally reported as 16-way associativity which means that we in practice get around 4MB L3 Cache available for our own use

are you calculating this 4mb number by doing 32/16*2? that doesn't really add up to what associativity means though (if 2 cores would have access to 4mb, that means 64 cores would have access to 128mb which is of course not the case). high associativity means fewer conflict misses (although 8 is in general considered high enough) so it means the cache is more usable. so if this was 4-way it should be less usable to cores.  

if we are in a VM, we wouldn't know that there are total 64 physical cores, since the VM will just report we have 2 cores. and the way `GetLogicalProcessorInformation` reports things on VMs isn't always predictable - sometimes it halftens the L3 cache size reported when the number of vcpus is halftened, other times it doesn't, even though the vcpus is smaller than the total number of cores that share the same L3 slice (I suppose it just means the vcpus happen to straddle 2 nodes that span 2 L3 slices).

having said that, it's completely reasonable to say that we shouldn't use the total shared L3 size as the L3 size every core sees. there's other factors in GC that would limit the size if we are in small container scenarios to be smaller than this. using the L3/# of cores sharing this L3) can be dangerous as it could be too small. it's something we can't change lightly which is why we haven't changed it yet (our 8.0 work will include re-evaluate this size though).

**Comment by tannergooding** [comment]
> are you calculating this 4mb number by doing 32/16*2? that doesn't really add up to what associativity means though (if 2 cores would have access to 4mb, that means 64 cores would have access to 128mb which is of course not the case).

Right, a 16-way associative cache indicates that there are effectively 16 places that a given copy of memory can be placed. While there is not a strict guarantee that this is 1-to-1 with the available cores, it is often correlated with the number of cores that have direct access to that part of the cache (and the AMD/Intel architecture and optimization manuals touch on this to various extents).

On AMD Zen processors in particular, a 16-core, 32-thread machine may have 64-MB L3. However, it reports its as 2x separate L3 caches each being 16-way associative and with CPUID reporting which cores have access to that L3. There being 2x L3 is because the CPU is split into CCXs (Core Complexes) each having its own L3 and using an interconnect (Infinity Fabric) to communicate between them. This interconnect means that even though the entire 64 MB L3 is accessible, there is a greater latency for accessing the L3 on a different CCX.

This also takes into account for Hyperthreading, which is simply 1 core splitting (or competitively sharing) its own ports/resources since typical applications do not fully saturate things.

Thus, for a 16-core, 32-thread machine with 64MB L3. Each core has access to 64MB L3, however due to the associativity there is in practice around 4MB "per core". Then because of the division into 2x L3 and the additional latency required to access the other L3, we have fast access to 2 MB per core. If hyper-threading is in use, it is then useful to be mindful that this 2MB may be split between two active threads.

The general setup on Intel is similar and CPUID for both architectures reports all the necessary information to confirm these details since it gives an exact affinitization of a given cache to cores. This same affinitization information is reported via `GetLogicalProcessorInformation`.

> sometimes it halftens the L3 cache size reported when the number of vcpus is halftened, other times it doesn't, even though the vcpus is smaller than the total number of cores that share the same L3 slice (I suppose it just means the vcpus happen to straddle 2 nodes that span 2 L3 slices).

What I've seen from local testing and manual affinitization in Hyper-V (for both Intel and AMD cpus) was that it will only report the L3 that is accessible to cores allocated to the VM.

This means that in a non-uniform model (such as an AMD 7950X3D, where one CCX has 96MB L3 and the other has 32MB L3) you will see one of:
* `1x 96MB L3` - All cores belong to CCX 0
* `1x 32MB L3` - All cores belong to CCX 1
* `1x 96MB L3 + 1x32MB L3` - Some cores belong to CCX 0 and some to CCX 1

In both cases, the rest of the reported information around `#-ways` and which cores have access to each remains correct such that you can still correctly take the reported information and get an accurate estimate for the given VM around how much you can assume is "fair" to use.

**Comment by Maoni0** [comment]
with the DATAS work, we are moving away from using the shared cache size to calculate min gen0 budget because it makes very little sense now. DATAS uses the old generation size to determine an appropriate value for this budget. we are still tuning this but that's the idea going forward. so I'm closing this issue.
