### ISSUE TITLE
`AssemblyVersion` and `FileVersion` doesn't seem correct when accessed programmatically

### ISSUE THREAD

**Issue by ypoul** [dotnet/runtime#81435]
### Description

The `AssemblyVersion` or `FileVersion` doesn't seem correct when accessed programmatically

### Reproduction Steps

1. Create a new Console Application with the following Program.cs
```cs
using System.Diagnostics;
using System.Reflection;

var assembly = Assembly.GetExecutingAssembly();
var fileVersionInfo = FileVersionInfo.GetVersionInfo(assembly.Location);
var fileVersion = fileVersionInfo.FileVersion;
Console.WriteLine($"FileVersion {fileVersion}");
Console.WriteLine($"AssemblyVersion {assembly.GetName().Version?.ToString()}");
```
2. Build the application: `dotnet build --configuration Release /p:Version=2.0.0.0`
3. Run the application: `dotnet run bin\Release\net7.0\ConsoleApp1.dll`

### Expected behavior

The output of the run should be:
```
FileVersion 2.0.0.0
AssemblyVersion 2.0.0.0
```

### Actual behavior

The output of the run is:
```
FileVersion 1.0.0.0
AssemblyVersion 1.0.0.0
```

### Regression?

I don't know

### Configuration

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Other information

The version seems to be correctly set when I inspect the properties of the dll itself

![dll](https://user-images.githubusercontent.com/121655359/215838032-4dcb0bc4-b14d-4856-8168-21ae59f77fd0.png)

**Comment by vitek-karas** [comment]
This is caused by confusion over the command line for `dotnet run`. That command is meant to "Run a project" and takes all its inherent parameters as command line options (run `dotnet run -?` to see the list), anything it doesn't understand it will pass it to the application as a command line argument.
So if you want to specify which project to run, you do `dotnet run --project my.csproj`.

In your case it didn't recognize the path to the dll and thus it passed it onto the app. Add this to the repro application:
```C#
Console.WriteLine($"args: {string.Join(' ', args)}");
```

And run it again:
```console
> dotnet run .\bin\Release\net7.0\consoleapp1.dll
args: .\bin\Release\net7.0\consoleapp1.dll
FileVersion 1.0.0.0
AssemblyVersion 1.0.0.0
> 
```

In fact, any string will work the same:
```console
> dotnet run something-I-wanted-to-say
args: something-I-wanted-to-say
FileVersion 1.0.0.0
AssemblyVersion 1.0.0.0> 
```

The reason why in prints versions 1.0.0.0 is that `dotnet run` by default builds the project and then runs it. So it's effectively equivalent to:
```console
> dotnet build -c Debug
> .\bin\Debug\net7.0\ConsoleApp1.exe
```

If you specify the Version property to it, it will work:
```console
> dotnet run -p:Version=2.0.0.0
FileVersion 2.0.0.0
AssemblyVersion 2.0.0.0
```

If you just want to run already built application you can either just launch the generated executable, or use `dotnet path-to-the-app.dll`. So to use your example:
```console
> dotnet build -c Release -p:Version=2.0.0.0
> dotnet .\bin\Release\net7.0\ConsoleApp1.dll
FileVersion 2.0.0.0
AssemblyVersion 2.0.0.0
> .\bin\Release\net7.0\ConsoleApp1.exe
FileVersion 2.0.0.0
AssemblyVersion 2.0.0.0
```

**Comment by ypoul** [comment]
Awesome! Thanks for your prompt answer!
