### ISSUE TITLE
Assertion failed '(emitCurIGfreeBase <= lastInsActualStartAddr) && (lastInsActualStartAddr < emitCurIGfreeEndp)'

### ISSUE THREAD

**Issue by markples** [dotnet/runtime#81505]
runtime-coreclr libraries-jitstress-random

https://dev.azure.com/dnceng-public/public/_build/results?buildId=151733&view=logs&j=f9affed7-8d82-5c58-eb09-b33088a0b629&t=841cba2d-9b8a-52d6-e2e0-be8034011045
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b15cc1fa12494ff594/System.Runtime.Serialization.Xml.Tests/1/console.dce60002.log?helixlogtype=result

```
  Starting:    System.Runtime.Serialization.Xml.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 5588 [0x000015d4], Thread: 9016 [0x2338]): Assertion failed '(emitCurIGfreeBase <= lastInsActualStartAddr) && (lastInsActualStartAddr < emitCurIGfreeEndp)' in 'SerializationTestTypes.Mixed1:.ctor(bool):this' during 'Generate code' (IL size 67; hash 0x7e69e4d9; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\emit.cpp Line: 9264
```

cc @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Introduced in https://github.com/dotnet/runtime/pull/77540 

cc: @BruceForstall @a74nh

**Comment by BruceForstall** [comment]
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=144
```

**Comment by BruceForstall** [comment]
Failure is in test `DataContractSerializerTests.DCS_BasicPerSerializerRoundTripAndCompare_ItRef`:
```
pushd z:\gh\runtime\artifacts\bin\System.Runtime.Serialization.Xml.Tests\Release\net8.0\
c:\bugs\coreroot\windows.arm64.Debug\corerun.exe xunit.console.dll System.Runtime.Serialization.Xml.Tests.dll -nologo -nocolor -verbose -parallel none -method "DataContractSerializerTests.DCS_BasicPerSerializerRoundTripAndCompare_ItRef"
popd
```

**Comment by BruceForstall** [comment]
@a74nh This assert is because the ldp/stp optimization is kicking in when the instruction to be replaced is the last instruction of an already-saved IG. When I originally wrote the `emitRemoveLastInstruction()` function, it handled this case -- in particular, it handled either removing the last instruction of the currently accumulating IG, or the last instruction of the last saved IG (which means the current IG is empty). Somewhere along the way, the code to handle removing the last instruction of the previous IG was removed and replaced with an assert that we don't hit that case. Do you remember why? I'm inclined to bring back that code.

**Comment by BruceForstall** [comment]
The case here is two back-to-back nogc regions. Disabling GC always creates a new extension IG even if the existing IG is already nogc (which would be really rare). The second IG wants to delete an instruction in the previous, which `emitCanPeepholeLastIns()` allows because they both have the same nogc flag.

We could possibly change clients of `emitRemoveLastInstruction()` to also require `emitLastInsIG != emitCurIG` but that seems unnecessarily constraining, long-term. We could also change `emitDisableGC()` to check the `emitCurIG` nogc flag before creating a new IG. But I've long been hoping we could get rid of all the complicated-to-understand checks before creating new IGs and just always create them when we want to, allowing for empty IGs.

So I think the best solution is to generalize `emitRemoveLastInstruction()` to handle the saved instruction case.

**Comment by a74nh** [comment]
> @a74nh This assert is because the ldp/stp optimization is kicking in when the instruction to be replaced is the last instruction of an already-saved IG. When I originally wrote the `emitRemoveLastInstruction()` function, it handled this case -- in particular, it handled either removing the last instruction of the currently accumulating IG, or the last instruction of the last saved IG (which means the current IG is empty). Somewhere along the way, the code to handle removing the last instruction of the previous IG was removed and replaced with an assert that we don't hit that case. Do you remember why? I'm inclined to bring back that code.

I suspect that during debugging I never hit that case so assumed it wasn't possible.

> The case here is two back-to-back nogc regions. Disabling GC always creates a new extension IG even if the existing IG is already nogc (which would be really rare). The second IG wants to delete an instruction in the previous, which `emitCanPeepholeLastIns()` allows because they both have the same nogc flag.

Ah, I didn't realise that could happen.
