### ISSUE TITLE
NativeAot publish fail

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#81584]
### Description

ConsoleApp1 -> E:\ConsoleApp1\bin\Release\net7.0\win-x64\ConsoleApp1.dll
  系统找不到指定的文件。
  Generating native code
  文件名、目录名或卷标语法不正确。
C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.targets(350,5): err
or MSB3073: 命令“"系统找不到指定的文件。;d:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\bin\Hostx64
\x64\link.exe" @"obj\Release\net7.0\win-x64\native\link.rsp"”已退出，代码为 123。 [E:\ConsoleApp1\ConsoleApp1
.csproj]

### Reproduction Steps

1.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

</Project>
```
2.
`dotnet publish -r win-x64 -c Release`

### Expected behavior

publish success

### Actual behavior

publish fail

**Comment by am11** [comment]
Looks like your Visual Studio installation is in unusual state. Please show the output of:

```cmd
:: windows command prompt

"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -products * ^
    -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^
    -version [16^,18^) ^
    -property installationPath
```

**Comment by am11** [comment]
It is the same value as your error message. So it is trying to find `Hostx64` directory under that path at `d:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\bin\Hostx64` which does not exist.

Check the output of:
```cmd
dir d:\Program Files\Microsoft Visual Studio\2022\Preview
:: does it exist?
:: do you see VC directory in the output of dir command?
```

If it does not, you can try uninstalling Visual Studio and reinstalling again. Otherwise, see https://github.com/microsoft/vswhere/issues/258, https://github.com/microsoft/vswhere/issues/41 and some other discussions to find out the problem with your VS installation (most likely some registry key or environment variable is out of sync).

**Comment by am11** [comment]
OK. The paths exist. Does it give some useful information if you run the linker command manually?

```cmd
cd E:\ConsoleApp1

rmdir /s /q obj
rmdir /s /q bin

:: let it fail once
dotnet publish -r win-x64 -c Release -v:diag > publish-dump.log

findstr /I "_FindVCVarsallOutput" publish-dump.log
findstr /I "_VCVarsAllFound" publish-dump.log

"d:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\bin\Hostx64\x64\link.exe" ^
    @"obj\Release\net7.0\win-x64\native\link.rsp"

echo %errorlevel% 
```

**Comment by am11** [comment]
Thanks. So 1181 with `cannot open input file 'advapi32.lib'` looks like https://github.com/dotnet/runtimelab/issues/1449.

Does this error go away if you unset `LIB` and `LIBPATH` environment variables? Like this:

```cmd
cd E:\ConsoleApp1

rmdir /s /q obj
rmdir /s /q bin

echo %LIB%
set LIB=

echo %LIBPATH%
set LIBPATH=

dotnet publish -r win-x64 -c Release

"d:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\bin\Hostx64\x64\link.exe" ^
    @"obj\Release\net7.0\win-x64\native\link.rsp"

echo %errorlevel% 
```

**Comment by am11** [comment]
I think it will be under `"%ProgramFiles(x86)%\Windows Kits"`

**Comment by am11** [comment]
Yes, please test if installing just Windows SDK fixes your problem. If it does, we should (at least) add a note for it explicitly in the documentation that Windows SDK is needed https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/#prerequisites.

The documentation mentions `Desktop development with C++` which may select it automatically in the installer UI, but then in `Individual Components` tab, user can un-select items. In my Windows 10 system, I selected `Desktop development with C++` (and few other things like .NET Framework for my work), but if I remember it correctly, that was enough to get `dotnet publish -p:PublishAot=true` working.

**Comment by am11** [comment]
Yes, or the accompanying bat file (which runs vswhere command) can also detect it and produce the error? Lets see. I will wait for @jkotas thoughts on Windows SDK requirement.

We switched to vswhere in https://github.com/dotnet/corert/commit/9e2f0159b80f37f8caaf7589febe6172c8b2f8c4. At that time, I had a system which I was restoring to factory settings to create different kinds of undesired states to form error message. IIRC, Windows SDK requirement wasn't spotted; which could be an oversight or because it is now pulled from cryptography lib object required by one of the runtime libs object. Maybe there is a way to not depend on Windows SDK and still facilitate advapi32.lib dependency. 🤔

**Comment by jkotas** [comment]
> I will wait for @jkotas thoughts on Windows SDK requirement.

Yes, Windows SDK (and number of other components that come with `Desktop development with C++` workload) are required. We do not want to be in a business of reshipping or recreating Windows SDK or other parts of Visual Studio.

We depend on number of Windows SDK libs, it is not just advapi32.lib: https://github.com/dotnet/runtime/blob/21a8eb51ad181f6eb2d7f24d8eda34840025a8a0/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.targets#L53-L67

**Comment by jkotas** [comment]
I do not mind improving the error handling if it is reasonably simple. However, it is close to impossible to make these script detect all possible ways that your Visual Studio installation can be corrupted.

**Comment by agocke** [comment]
It's not clear to me how to detect that. Although if there is an easy way to do so, happy to include it. Maybe we could check the registry inside the build task, assuming there's a well-known registry key.

**Comment by am11** [comment]
Finding Windows SDK paths manually in all kinds of 32/64 x64/x86/arm64/arm variations robustly gets complex and it is nondeterministic; Windows / VS teams can and do make breaking changes. Even if we figure it out via registry, it doesn't really help because we don't know if the final cl.exe call will actually select the Windows SDK version which we identified as installed, because user can have side-by-side VS installed; one with required components and the other without.

We can continue using vswhere and add the additional required component ID. This way, it will match the components in context of instance of VS. The problem there is that the current version of vswhere which ships with Visual Studio is 3.0. This version doesn't support glob patterns, so it's not feasible to list _all_ the applicable/supported SDKs IDs. In the next version 3.1.1, they have added glob pattern support which we can use to determine if any Windows SDK version is present that applies to the instance of VS. So for the upcoming VS version, we can improve it a little bit.

The general guidance is to refer to documentation for prerequisites applicable to your platform. We have similar blind spots in clang/gcc toolchains. For advanced issues, build diagnostics (bin logs or diag logs)  help finding the compiler command and troubleshooting.
