### ISSUE TITLE
Failed to read NuGet.Config due to unauthorized access.

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#81619]
### Build

All dotnet/runtime release/7.0 PRs seem to be failing in test runs with:
```
NuGet.Configuration.NuGetConfigurationException : Failed to read NuGet.Config due to unauthorized access. Path: '/.nuget/NuGet/NuGet.Config'.
---- System.UnauthorizedAccessException : Access to the path '/.nuget' is denied.
-------- System.IO.IOException : Permission denied
```

Direct link to one of the failures: https://dev.azure.com/dnceng-public/public/_build/results?buildId=158966&view=ms.vss-test-web.build-test-results-tab&runId=3279457&resultId=131719&paneView=debug

### Build leg reported

Libraries Test Run checked coreclr Linux_musl arm Release
Libraries Test Run checked coreclr Linux_musl arm64 Release
Libraries Test Run checked coreclr Linux arm64 Debug

### Pull Request

Examples:
- https://github.com/dotnet/runtime/pull/80866
- https://github.com/dotnet/runtime/pull/81295
- https://github.com/dotnet/runtime/pull/81607

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section)

 ```json
 {
    "ErrorMessage" : "NuGet.Configuration.NuGetConfigurationException : Failed to read NuGet.Config due to unauthorized access. Path: '\/.nuget\/NuGet\/NuGet.Config'.",
    "BuildRetry": false,
    "ExcludeConsoleLog": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MattGal** [comment]
> I'm going to move this to the runtime repository unless someone knows something in the infrastructure that's broken. It appears to be specific to a small set of tests in runtime, in PR's only, in the release 7.0 branch only.

One clue is the fact that it's a docker work item and the docker tag is `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652`.    Due to the implementation of how helix work items are mapped into docker containers, you need to have the user id of the outside match the inside of the container, and this was addressed some time later (here's the same work item passing from today: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81547-merge-c4cbe00f5d014147a3/LibraryImportGenerator.Unit.Tests/1/console.94b92f68.log?helixlogtype=result )

Changing your usage from  `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652` to `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8` should unblock you as well as keep you on the latest version of this image.

**Comment by carlossanlop** [comment]
I merged https://github.com/dotnet/runtime/pull/81712 

If we stop seeing the nuget failures in the next few days, I'll close this.

**Comment by lewing** [comment]
closing based on the previous comment
