### ISSUE TITLE
Selecting Network Interface for Socket Connections

### ISSUE THREAD

**Issue by Tazzi3** [dotnet/runtime#81698]
### Discussed in https://github.com/dotnet/maui/discussions/12682

<div type='discussions-op-text'>

<sup>Originally posted by **Tazzi3** January 16, 2023</sup>
I am trying to create a socket connection from Android/iOS that will connect to a ESP32 access point although MAUI keeps indicating "No Route to Host" when trying to open the connection. My understand of this is the host responded with that this request does not have a valid 'destination', which is expected if the requested IP address does not exist.

This access point (ESP) does not have an internet connection, it is purely used for connecting to a smartphone or PC to allow sending commands via a socket connection.

After connecting to the ES32 Wifi from the phone settings, I am able to use any free TCP applications on both Android and iOS to open a socket connection to 192.168.4.1 on port 23. Once the connection is opened, I am able to send and receive information happily.

I am able to use the code below on an android and the socket connection opens fine. When I use it on iOS, I get back a "No Route to Host" error. Considering I am able to connect using a different application on the same iphone, I know its not the ESP failing here.

`CancellationToken CToken = new CancellationToken();
 using Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
 await socket.ConnectAsync(IPAddress.Parse("192.168.4.1"), 23, CToken);`

When connected to the ESP32 and looking at the wifi settings off the iphone, we have:
IP Address: 192.168.4.2
Subnet Mask: 255.255.255.0
Router: 192.168.4.1
DNS (is on Automatic): 192.168.4.1

Now here comes the next confusing part. A work colleague is able to use his iphone using the exact same EP32 access point, and able to connect a socket with the exact three lines of code above using MAUI. Both phones are identical (iphone 12 pro) and running the exact same iOS firmware 16.1.2
The only thing I can kind of figure that may be a difference, is the iphone is selecting the incorrect network adapter. So instead of using the ESP32 wifi connection, its possibly trying to connect a socket from one of the other network interfaces? Such as cellular?

Does anyone know how to enforce using a specific network adaptor for iOS? Even if its iOS platform specific code that needs to be run to setup/enforce at the beginning? Or have any other suggestions?</div>

**Comment by steveisok** [comment]
@rolfbjarne can you help on the `"System.Exception: Could not initialize an instance of the type 'CoreFoundation.DispatchQueue': handle is null."` comment?

**Comment by rolfbjarne** [comment]
This error is weird: "System.Exception: Could not initialize an instance of the type 'CoreFoundation.DispatchQueue': handle is null."

Do you have a complete stack trace for the exception? It would also be nice to know exactly which line of your code triggered that exception.

**Comment by Tazzi3** [comment]
@rolfbjarne Here is a screen shot of the exact code and the error inside of the 
![ErrorMaui](https://user-images.githubusercontent.com/10905969/217114340-dbb90ddf-872d-4bc1-b52e-cb0f658c0d55.PNG)

And this is the call trace from it:
`0x80 in TestForiOSAndroid.WifiBase..ctor at C:\Users\Jason\source\repos\TestForiOS\TestForiOSAndroid\Platforms\iOS\WIFIiOS.cs:33,13
	at C:\Users\Jason\source\repos\TestForiOS\TestForiOSAndroid\Platforms\iOS\WIFIiOS.cs(33)
0x1B in TestForiOSAndroid.MainPage.ConnectVehicleButton_Clicked at C:\Users\Jason\source\repos\TestForiOS\TestForiOSAndroid\Pages\MainPage.xaml.cs:107,9
	at C:\Users\Jason\source\repos\TestForiOS\TestForiOSAndroid\Pages\MainPage.xaml.cs(107)
0x2F in System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TestForiOSAndroid.MainPage.<ConnectVehicleButton_Clicked>d__13>
0x1 in System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<TestForiOSAndroid.MainPage.<ConnectVehicleButton_Clicked>d__13>
0x35 in TestForiOSAndroid.MainPage.ConnectVehicleButton_Clicked
0x11 in Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked
0x20 in Microsoft.Maui.Controls.ButtonElement.ElementClicked
0x2 in Microsoft.Maui.Controls.Button.SendClicked
0x1 in Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked
0x1C in Microsoft.Maui.Handlers.ButtonHandler.OnButtonTouchUpInside
0x15 in UIKit.UIControlEventProxy.Activated
0x88 in UIKit.UIApplication.xamarin_UIApplicationMain
0x6 in UIKit.UIApplication.UIApplicationMain
0x51 in UIKit.UIApplication.Main
0xD in TestForiOSAndroid.Program.Main at C:\Users\Jason\source\repos\TestForiOS\TestForiOSAndroid\Platforms\iOS\Program.cs:13,3
	at C:\Users\Jason\source\repos\TestForiOS\TestForiOSAndroid\Platforms\iOS\Program.cs(13)
0x1C in System.Reflection.RuntimeMethodInfo.InternalInvoke
0x70 in System.Reflection.RuntimeMethodInfo.Invoke
0x6 in System.Reflection.MethodBase.Invoke
0x18D in Xamarin.iOS.HotRestart.Application.Run
0x45 in Xamarin.PreBuilt.iOS.Applications.Main at /Users/builder/azdo/_work/2/s/xamarin-macios/msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Main.cs:12,7`

**Comment by rolfbjarne** [comment]
That's an exception that occur when the IDE inspects the ReadDispatchQueue and WriteDispatchQueue properties. Your code doesn't use those properties, so your code should run just fine.

As for your other questions/problems:

* The `CFStreamCreatePairWithSocketToHost` API doesn't seem to allow for selecting the network interface, so it's up to iOS to choose. We don't do anything here.
* Have you tried removing all your other network interfaces to see what happens if there's only a single network interface (the one you want)? For instance by disconnecting cellular data on your phone, and only leaving wifi on.
* Your app might need an entry in the Info.plist file to allow connections to the local network: https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads?language=objc and/or https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking?language=objc.

**Comment by Tazzi3** [comment]
@rolfbjarne Ok, I assumed there might have been a problem since it was stating the handle was null. Which I assume was relating to the actual handle variable inside those streams.

The CFStreamCreatePairWithSocketToHost API automatically targets the WIFI connection in iOS Xcode, the support team for Xcode also confirmed it will always use wifi when available.
After opening the input/output streams, they both indicate the following but there is no further details on what this error is:
![ErrorOpeningPorts](https://user-images.githubusercontent.com/10905969/217407151-1f074b7e-802e-4370-84ca-63ee3ed4d431.PNG)


I have also tried with cellular disabled, same issue occurs. We also already have the NSLocalNetwork permissions in the plist (iPhone also asked with a popup), and even the multicast entitlement since I wasn't sure if it was being blocked.

**Comment by rolfbjarne** [comment]
@Tazzi3 and the _exact same app_ works as expected on another phone?

**Comment by Tazzi3** [comment]
@rolfbjarne  Correct. Exact same app (coding described in my first post) will work on a different iPhone, and its the only one that seems to work our of 5 iphones (2x iphone 12 Pros on same OS, iphone X and iphone 14 and iphone 8).

One of the iphone 12 pros will connect using the standard Socket API as described in the first post. We believe this is defaulting to wifi connection for whatever reason, whereas the others are not. This is what has lead to trying to use iOS specific socket routines to try enforce using the wifi interface.

All of the above phones work with the iOS Xcode.

**Comment by rolfbjarne** [comment]
Do any/all/some of the phones have a VPN installed, or a proxy configured?

**Comment by Tazzi3** [comment]
@rolfbjarne None at all.

**Comment by rolfbjarne** [comment]
To say that this is puzzling is an understatement... I have no idea what the issue might be, but I can always come up with ideas for diagnosing it.

One idea would be to write the code in C to make the connection (like you did with Swift above), and create a static library with this code. Then you make sure it works by calling it from an Xcode project, and after that use it in a MAUI project to see if that works. Note: I'd write in C because that's simpler to consume from a MAUI project (and I know C better than Swift), but it's possible to make Swift work too.

Another idea would be to try to make the Swift and the MAUI apps as similar as possible:
* Start by using the same bundle identifier (so that when one version is installed it overwrites the other). Make sure that the Swift app works after installing over the MAUI version, and that the MAUI version doesn't after installing over the Swift version).
* Then try to make the apps as similar as possible when it comes to the Info.plist and entitlements (by inspecting those in the app that's actually installed, and not the project files, because both Visual Studio and Xcode add both entitlements and entries to the Info.plist automatically that aren't in the projects - maybe Xcode adds something that ensures its app always works).

**Comment by Tazzi3** [comment]
It is very puzzling. I think its still coming down to wrong interface used, which is somehow being affect from how microsofts calling or passing parameters to the API.
Basically that is what I have done, I created the ios Xcode app using Swift, all I added was a button click and the code posted above.

For the MAUI project, I have to create the base partial class, then make the same class in iOS and android so I can use the iOS specific code there. Then just copied the equivalent code into the iOS specific class.

In the last couple days, I had a similar issue with using Android USB, where the built in MAUI Android.hardware.usb API does not work the same as using it directly from Android Studio. When creating the same code in Android studio then importing it into a native android binding in MAUI, it works perfectly. Whereas using the MAUI API calls to the hardware usb API, it seems to have issues with reading from endpoints with a direction of IN.

Anyways, I spent today trying to do the same with iOS for the socket connection following this guide: https://medium.com/@tema.denisoff/how-to-use-swiftui-components-in-maui-f43c54d2173c

But VS MAC does not allow targeting .NET6 which is used for my project and other dependencies. It auto defaults to .NET 7 which I cannot seem to change. Everytime I open the project properties and select it from .NET7 to .NET6 then click OK, it goes back to .NET 7.
I then tried just making the project in VS MAC using .NET 7, but .NET7 seems to not be very stable for debugging on iOS either, it crashes regularly before even loading the main screen.

I am hoping that using the framework built in Xcode directly should hopefully solve the issues like I had with android USB. If it works, can upload it as a nuget for anyone else facing similar issues (I see alot of xamarin/maui issues similar to mine for sockets).

**Comment by Tazzi3** [comment]
Ok, coming back to this after some success with binding an iOS library here: https://github.com/dotnet/maui/issues/14775

The main function for creating the socket connection in the iOS Objective-C code is:

(void)connectToHost:(NSString *)host port:(NSInteger)port {
    CFReadStreamRef readStream;
    CFWriteStreamRef writeStream;
    CFStreamCreatePairWithSocketToHost(NULL, (__bridge CFStringRef)host, (UInt32)port, &readStream, &writeStream);
    self.inputStream = (__bridge NSInputStream *)(readStream);
    self.outputStream = (__bridge NSOutputStream *)(writeStream);
    [self.inputStream setDelegate:self];
    [self.outputStream setDelegate:self];
    [self.inputStream scheduleInRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];
    [self.outputStream scheduleInRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];
    [self.inputStream open];
    [self.outputStream open];
}

I can then use this simple function to then write a string:
(void)writeString:(NSString *)stringToSend {
    NSData *data = [stringToSend dataUsingEncoding:NSUTF8StringEncoding];
    [self writeData:data];
}

When connection is opened, I am using the handleEvent for NSStreamEvent which allows indicating when the stream has successfully opened, along with reading in bytes to a queue when received.

I have tested this in multiple iOS phones and it works everytime to connect. Whereas the default class does not work as previously indicated. Is there anything I can do or provide to have the socket class for iOS reviewed?

I am glad there is a working solution now, and will get something posted up onto git and link it here for anyone else with the problem, but would love to have it solved in the official socket class.

**Comment by rolfbjarne** [comment]
> Is there anything I can do or provide to have the socket class for iOS reviewed?

The managed binding for CFStreamCreatePairWithSocketToHost is here:

https://github.com/xamarin/xamarin-macios/blob/491c5c979cdf5f1d0751f16fd260b21d06e63e2b/src/CoreFoundation/CFStream.cs#L336-L385

You could try copying that code in your own project and see if you can still reproduce it - and then tinkle with it to see if you can figure out what the problem is. The fact that it seems only you can reproduce the problem makes it rather difficult for anyone else to diagnose what's going on.

**Comment by karelz** [comment]
@vitek-karas can you please help with triage?

**Comment by vitek-karas** [comment]
@simonrozsival - I'll move this to 6.0 as based on the comments above the customer is using 6.0 for this. If we need more info from the customer we should mark this with the right tag.

**Comment by simonrozsival** [comment]
@vitek-karas I will try to reproduce this issue, although it might be challenging because I won't be able to use the same hardware (especially the ESP router).

I suggest we move the issue back to the 8.0 milestone though since we don't support MAUI on .NET 6.0 for a year now and it is actually the very last day of .NET 7 support for MAUI today (https://dotnet.microsoft.com/en-us/platform/support/policy/maui).

**Comment by vitek-karas** [comment]
Thanks - moved to 8.0.

**Comment by simonrozsival** [comment]
I'm struggling to reproduce the issue. I am not getting the error, I can connect to my wifi router on port 80. It is possible that this issue has been already fixed since .NET 6.

@Tazzi3 have you been able to find a workaround or have you been able to identify the cause of the issue since you reported the issue last year?

**Comment by Tazzi3** [comment]
> I'm struggling to reproduce the issue. I am not getting the error, I can connect to my wifi router on port 80. It is possible that this issue has been already fixed since .NET 6.
> 
> @Tazzi3 have you been able to find a workaround or have you been able to identify the cause of the issue since you reported the issue last year?

If you are not getting the exact error that I was, then it is likely a different problem.

I believe compiling and running off of a MAC computer directly seems to fix the problem. There are different versions of the iOS library being used on a MAC compared to on a Windows, it looks like the MAC edition actually uses a newer version.

I have not yet tried using .Net8 to see if this issue has been resolved on the latest releases. I will be rolling back to this again in the next month or so.
