### ISSUE TITLE
Recommendation needed for using NuGet packages for .Net 6 target

### ISSUE THREAD

**Issue by nicoleta-scrimint** [dotnet/runtime#81740]
Hi,

In order to be up to date with the latest NuGet packages changes, my team regularly updates the used NuGet packages in the Visual Studio projects.
Based on [a past GitHub issue](https://github.com/dotnet/aspnetcore/issues/28098) for the update to NuGet packages for .Net 5 when the project targets .Net Core 3.1, it is recommended by Microsoft to update to the latest patch of the NuGet packages that correspond to the major.minor of the project target.

I have the following questions:
1. Is the upper recommendation to update to the latest patch of the NuGet packages that correspond to the major.minor of the project target also applicable for the update of NuGet packages for .Net 7 when the project targets .Net 6? Is there an issue if a project which targets of .Net 6, uses NuGet packages with 7.X.X version, since the "Manage Packages for Solution" does not block NuGet packages updates from 6.X.X to 7.X.X version and there are no compilation errors?
2. Should the .Net runtime version installed through the .Net SDK correspond to the version of the NuGet packages?
          - I observe on the https://versionsof.net/core/6.0/ that the .Net release versions would match the versions of the NuGet packages for .Net, e.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization#versions-body-tab. Though for the https://www.nuget.org/packages/Microsoft.Extensions.Options.ConfigurationExtensions/, I do not see different NuGet package versions for all the .Net 6 releases.

Thank you!

**Comment by ViktorHofer** [comment]
Hello @nicoleta-scrimint 👋 

> Is the upper recommendation to update to the latest patch of the NuGet packages that correspond to the major.minor of the project target also applicable for the update of NuGet packages for .Net 7 when the project targets .Net 6? Is there an issue if a project which targets of .Net 6, uses NuGet packages with 7.X.X version, since the "Manage Packages for Solution" does not block NuGet packages updates from 6.X.X to 7.X.X version and there are no compilation errors?

Our recommendation is to always stay on the latest patch version for NuGet packages and the .NET SDK itself. This is especially true for security vulnerabilities that might have been fixed in the most recent patch update.

In general, feel free to cross-bands (update to a higher major version) when the referenced packages support your project's target framework. Note that based on [semantic versioning](https://semver.org/lang/de/) you should expect breaking changes that will require code changes. While .NET maintains a high level of compatibility, we started
- obsoleting API that shouldn't be used anymore
- enabling analyzers that could emit a warning or error
- ...

Versions of the .NET SDK / .NET Runtime and our NuGet packages aren't in sync because they only work together but because they ship at the same time. I.e. you will be able to reference 8.0 Preview 1 NuGet packages from a net6.0 project.

> Should the .Net runtime version installed through the .Net SDK correspond to the version of the NuGet packages? I observe on the https://versionsof.net/core/6.0/ that the .Net release versions would match the versions of the NuGet packages for .Net, e.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization#versions-body-tab. Though for the https://www.nuget.org/packages/Microsoft.Extensions.Options.ConfigurationExtensions/, I do not see different NuGet package versions for all the .Net 6 releases.

Many of our NuGet packages ship with every release, even when the underlying component's code hasn't changed (i.e. AspNetCore packages). Other packages (most from dotnet/runtime) don't ship with every release and only update when the underlying codebase changes. We call that mechanism "incremental servicing".

**Comment by nicoleta-scrimint** [comment]
Hi,

Regarding the compatibility between the .Net runtime version installed on the operating system level or as self contained and the NuGet packages installed on the project, I understand that the following situations should work:
- on the operating system level/self contained, .Net runtime 6.0.0 is installed and in the project with target net6.0, the NuGet packages for AspNetCore are installed with version 6.0.13, e.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization/6.0.13
- on the operating system level/self contained, .Net runtime 6.0.13 is installed and in the project with target net6.0, the NuGet packages for AspNetCore are installed with version 6.0.0, e.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization/6.0.0

From what I understand, it does not need to match the patch version between the installed .Net runtime version on the operating system level/self contained and the AspNetCore NuGet package version installed on the project level.
Is this a correct conclusion from your point of view?

Thank you!

**Comment by ViktorHofer** [comment]
> Can you please point me to some official Microsoft documentation which explains how the .Net runtime, project target and Microsoft NuGet packages work together? I only found this document which states the relation between the .Net runtime and project target https://learn.microsoft.com/en-us/dotnet/core/versions/selection.

I don't know if we have such documentation publicly available anywhere (cc @richlander) but I can describe how this works behind the scenes. When assemblies are referenced from both the shared framework (more precisely, its targeting pack) and via a NuGet package, the .NET SDK decides which asset to pick.

That decision is made in the `ResolvePackageFileConflicts` msbuild task which receives all the references (shared framework + NuGet packages) as an input.

As an example, let's take `System.Text.Json` which is available in both. Here's a sample app:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="7.0.1" />
  </ItemGroup>

</Project>
```

As we reference a newer version of `System.Text.Json` via the PackageReference than what's present in the shared framework, "conflict resolution" decides that the former should win:

> Encountered conflict between 'Platform:System.Text.Json.dll' and 'CopyLocal:C:\Users\vikto\.nuget\packages\system.text.json\7.0.1\lib\net7.0\System.Text.Json.dll'. Choosing 'CopyLocal:C:\Users\vikto\.nuget\packages\system.text.json\7.0.1\lib\net7.0\System.Text.Json.dll' because file version '7.0.122.56804' is greater than '7.0.22.51805'.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/7412651/217568718-a8bc580d-8c52-48aa-9d33-2fae0825a8f7.png">

That task considers both the assembly's AssemblyVersion and FileVersion. You can find its implementation here: https://github.com/dotnet/sdk/blob/main/src/Tasks/Common/ConflictResolution/ResolvePackageFileConflicts.cs#L18

> From what I understand, it does not need to match the patch version between the installed .Net runtime version on the operating system level/self contained and the Microsoft AspNetCore NuGet packages version installed on the project level.
Is this a correct conclusion from your point of view?

Exactly. A patch version update must not change public API which is why compilation continues to work just fine. The run time behavior differs, i.e. when a security vulnerability got patched in a recent update.

**Comment by nicoleta-scrimint** [comment]
Thank you very much for your quick responses!

**Comment by ViktorHofer** [comment]
Let me close the issue then. Feel free to file a new issue for more questions.
