### ISSUE TITLE
[API Proposal]: Take required modifier into account when validating options.

### ISSUE THREAD

**Issue by voroninp** [dotnet/runtime#81750]
### Background and motivation

When `[Required]` attribute is commented, code does not throw.
```
void Main()
{
	var sc = new ServiceCollection();
	var cfg = new ConfigurationBuilder().AddInMemoryCollection().Build();
	sc.AddOptions<Foo>().ValidateDataAnnotations().Bind(cfg);
	
	var provider = sc.BuildServiceProvider();
	
	var opt = provider.GetRequiredService<IOptions<Foo>>();
	_ = opt.Value;
}

public sealed class Foo
{
	//[Required]
	required public string Bar {get; init;}
}
```
Yes, when it is commented out, there are no data annotations attributes applied, but is not `required` modifier somewhat stronger than `[Required]` and hence it should be inferred, so to say??

### API Proposal

I'd expect the inference of `[Required]` attribute if property is marked as required.

### API Usage

It should be implicit and work out of the box.

**Comment by eiriktsarpalis** [comment]
It's an interesting proposal, one thing to note though is that the semantics of `RequiredAttribute` are slightly different to the C# `required` keyword. More specifically, the former validates if the value present on a property is not null or the empty string, whereas the `required` keyword simply provides compile-time guarantees that a property has been set at construction without concern for what the set value is:
```C#
var value = new MyPoco { Value = null }; // required property set to null, passes type check.

public sealed class MyPoco
{
	required public string? Value {get; init;}
}
```
This suggest to me that we shouldn't use the `required` keyword as a drop-in substitute for `RequiredAttribute`. 

It's worth mentioning that we recently added support for the `required` keyword in System.Text.Json, however this only validates if a given property has been deserialized, it is _not_ validating if the deserialization is not null.

cc @krwq @jeffhandley

**Comment by ajcvickers** [comment]
> This suggest to me that we shouldn't use the required keyword as a drop-in substitute for RequiredAttribute.

This is the same conclusion we came to for EF Core.

**Comment by voroninp** [comment]
Ah, empty string... =(
Otherwise for `required + nullable enabled + not nullable ref type` it could be a match with `[Required]`

**Comment by eiriktsarpalis** [comment]
I'm going to leave this open, since there might be an opportunity to leverage the `required` keyword in validation although it most likely will have different semantics compared to `RequiredAttribute`.

**Comment by eiriktsarpalis** [comment]
cc @geeknoid

**Comment by jeffhandley** [comment]
I also support the position of keeping these concerns separate (as far as DataAnnotations validation is concerned).

**Comment by amis92** [comment]
I'd just like to say that we've built our own crude validation based on the C# annotations (nullability and requiredness), because it seems like a missed opportunity to validate simple cases using what C# already provides. Specifically, the case of `required string` (not-null with nullable enabled) very much lends itself to simple C#, attribute-less declaration that a value (even an empty string) will be provided. It also silences nullability warnings (a not required `string` will warn that it is not initialized to non-null value) which means that if there's no validation, we end up with a null value without warning after retrieving such an object.

**Comment by krwq** [comment]
For JSON we do infer that (required keyword is equivalent to `[JsonRequired]`). I'm not strongly opinionated here but I have more bias toward user friendliness. From user perspective most of the time it's likely expected required keyword will imply `[Required]` but from library point of view it seems it's a separate concern especially given there are some nuanced differences.

To me nullability is 100% separate concern because null might mean something in two different libraries (i.e. null in some cases might be same as no value and in some other it might mean to delete something and in some other like `bool?` it might be one of the tri-state value).

I don't have full context on data annotations but possibly some switch in the options to control this behavior would make sense here?

**Comment by klemmchr** [comment]
From my point of view the interpretation of `RequiredAttribute` has been convenient over the past years since .NET was missing crucial features like Nullable Reference types and the `required` keyword. However, looking at the current state it is questionable whether it is really needed any more for strings (besides checks for non-whitespace strings).

When using Nullable Reference Types in combination with the `required` keyword you can control even more cases:

| `required` | `nullable` | validation
|---|---|---|
| ❌ |  ❌ | Non-null value needs to be set |
| ✅ | ❌ | Non-null value needs to be set |
| ❌ | ✅ | Null or non-null value needs to be set |
| ✅ | ✅ | Null or non-null value needs to be set |

This is not saying that it should be removed. But adding support for `required` and/or nullability would just be very convenient.

**Comment by krwq** [comment]
@klemmchr when you need null validation you can create DefaultJsonTypeTypeInfoResolver modifier which changes setter so it rejects null for all required properties. Would that work as a workaround for you?

**Comment by klemmchr** [comment]
> @klemmchr when you need null validation (i.e. reject it) you can create DefaultJsonTypeTypeInfoResolver modifier which changes setter so it rejects null for all required properties (just throw exception on null). Would that work as a workaround for you?

How do I do that?

**Comment by krwq** [comment]
@klemmchr sorry my bad I thought this was a JSON issue (most of my issues are in there)

**Comment by eiriktsarpalis** [comment]
Closing as wontfix. The C# `required` keyword does not enforce non-nullability, so is fundamentally different to the semantics of `RequiredAttribute`.

**Comment by amis92** [comment]
@eiriktsarpalis would you be open to a different API suggestion that allows validation of `T` in `IOptions<T>` according to C# annotations, like nullability and requiredness?

I'd gladly open a new issue, but honestly have no idea where to put it, or how to name it.

**Comment by eiriktsarpalis** [comment]
Presumably such a feature would validate for non-nullability in general, not specifically `required` members right?
