### ISSUE TITLE
[API Proposal]: Create `ulong` from two `uint`

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#81767]
#### Background and motivation

`UInt128` and `Int128` have this functionality, but it is lacking from `UInt64` and `Int64`:

```csharp
public UInt128(ulong upper, ulong lower) { ... }
public Int128(ulong upper, ulong lower) { ... }
```

#### API Proposal
```csharp
public readonly struct UInt64
{
  /// <summary>Initializes a new instance of the <see cref="UInt64" /> struct.</summary>
  /// <param name="upper">The upper 32-bits of the 64-bit value.</param>
  /// <param name="lower">The lower 32-bits of the 64-bit value.</param>
  [CLSCompliant(false)]
  public UInt64(uint upper, uint lower)
  {
#if BIGENDIAN
    m_value = (ulong)lower << 32 | (ulong)upper;
#else
    m_value = (ulong)lower | (ulong)upper << 32;
#endif
  }
}

public readonly struct Int64
{
  /// <summary>Initializes a new instance of the <see cref="Int64" /> struct.</summary>
  /// <param name="upper">The upper 32-bits of the 64-bit value.</param>
  /// <param name="lower">The lower 32-bits of the 64-bit value.</param>
  [CLSCompliant(false)]
  public UInt64(uint upper, uint lower)
  {
#if BIGENDIAN
    m_value = (long)lower << 32 | (long)upper;
#else
    m_value = (long)lower | (long)upper << 32;
#endif
  }
}
```
#### Alternative Designs

```csharp
public static class BitConverter
{
  public ulong GetUInt64(uint upper, uint lower) { ... }
  public long GetInt64(uint upper, uint lower) { ... }
}

**Comment by tannergooding** [comment]
The functionality exists for `UInt128` because they are not primitive types and so the constructor existing is a necessity (and perf advantage).

For `long`/`ulong`, there are multiple other APIs that handle endianness and which allow a `uint64` to be properly construct. The simplest of which is simply `(((ulong)upper) << 32) | lower`. There is no perf advantage or necessity around such an API for these types.

Also worth noting that this code is not correct:
>```csharp
#if BIGENDIAN
    m_value = (ulong)lower << 32 | (ulong)upper;
#else
    m_value = (ulong)lower | (ulong)upper << 32;
#endif
```

`m_value` is a single primitive field and will already be laid out correctly in memory. Therefore, `(((ulong)upper) << 32) | lower` is always correct and will result in the lower 32-bits being `lower` and the upper 32-bits being `upper`.

**Comment by tannergooding** [comment]
The other APIs available include `BinaryPrimitives.ReadInt64LittleEndian`, `BinaryPrimitive.ReadInt64BigEndian`, as well as corresponding methods for writing and for `UInt64`.

Such APIs also exist for `Int32/UInt32` and `Int16/UInt16`
