### ISSUE TITLE
Basic Authentication via HTTPClientHandler not working for Android

### ISSUE THREAD

**Issue by mimegh** [dotnet/runtime#81839]
### Description

The basic authentication via HTTPClientHandler credentials doesn’t work for Android (.net 7.0). 
Can you confirm, this is a bug or is something wrong with the coding below?
Thanks,
  Michael

### Steps to Reproduce

1. Create MAU project .net 7.0
2. add the following coding:
```cs
HttpClientHandler lClientHandler = new HttpClientHandler();
CancellationTokenSource lCancel = new CancellationTokenSource();
lCancel.CancelAfter(TimeSpan.FromMilliseconds(5000));
lClientHandler.Credentials = new NetworkCredential("<user>", "<password>");
var lClient = new HttpClient(lClientHandler);
var lResponse = await lClient.GetAsync("https://<web address>" , HttpCompletionOption.ResponseContentRead, lCancel.Token).ConfigureAwait(false);
```
This returns a 401 (Unauthorized) for android.
The same code works just fine for windows. I have tested the problem with multiple android emulators (Android 11 and Android 13) and an android device (Android 13). The web service is accessible via browser on the device (and the login/password works as well).

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11/ Android 13, probably others as well

### Did you find any workaround?

If I set the Authorization manually it works just fine.
(Instead of:
`lClientHandler.Credentials = new NetworkCredential("<user>", "<password>");`
for instance use:
```
var byteArray = Encoding.ASCII.GetBytes("<user>:<password>");
lClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));
```
)
However this workaround doesn’t really work for me, because the code is part of a library implementation I use and which I cannot change. Furthermore this coding works in a Xamarin Android app (non MAUI) without problem.

**Comment by simonrozsival** [comment]
AFAIK the default native handler that's used internally by HttpClientHandler on Android won't include Credentials by default. I would recommend using the [AndroidMessageHandler](https://learn.microsoft.com/en-us/dotnet/api/xamarin.android.net.androidmessagehandler) directly and configuring its `PreAuthenticate` and `PreAuthenticationData` directly. What's also necessary is that the server sends the `WWW-Authenticate: Basic` header.

Here's a short sample:

```csharp
using System.Net;
using Xamarin.Android.Net;

var url = "https://httpbin.org/basic-auth/username/correct-password";

await SendWith(username: "username", password: "wrong-password");
await SendWith(username: "username", password: "correct-password");

async Task SendWith(string username, string password)
{
    Console.WriteLine($"=======");
    Console.WriteLine($"Test username={username}, password={password}");
    Console.WriteLine($"=======");

    var handler = new AndroidMessageHandler
    {
        Credentials = new NetworkCredential(username, password),
    };
    var client = new HttpClient(handler);

    var response = await client.GetAsync(url) as AndroidHttpResponseMessage;
    await Dump(response);

    if (response.RequestNeedsAuthorization)
    {
        handler.PreAuthenticationData = response.RequestedAuthentication.FirstOrDefault(auth => auth.Scheme == AuthenticationScheme.Basic)
             ?? new Exception("In this sample we require Basic auth");
        handler.PreAuthenticate = true;

        response = await client.GetAsync(url) as AndroidHttpResponseMessage;
        await Dump(response);
    }

    Console.WriteLine();
}

async Task Dump(AndroidHttpResponseMessage response)
{
    Console.WriteLine($"Request: {response.RequestMessage}");

    var body = await response.Content.ReadAsStringAsync();
    Console.WriteLine($"Response: {response}");
    Console.WriteLine($"Response body: '{body}'");
}
```

The expected output is:
```
[DOTNET] =======
[DOTNET] Test username=username, password=wrong-password
[DOTNET] =======
[DOTNET] Request: Method: GET, RequestUri: 'https://httpbin.org/basic-auth/username/correct-password', Version: 1.1, Content: <null>, Headers:
[DOTNET] {
[DOTNET] }
[DOTNET] Response: StatusCode: 401, ReasonPhrase: 'UNAUTHORIZED', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
[DOTNET] {
[DOTNET]   Access-Control-Allow-Credentials: true
[DOTNET]   Access-Control-Allow-Origin: *
[DOTNET]   Connection: keep-alive
[DOTNET]   Date: Fri, 10 Feb 2023 12:17:26 GMT
[DOTNET]   Server: gunicorn/19.9.0
[DOTNET]   WWW-Authenticate: Basic realm="Fake Realm"
[DOTNET]   X-Android-Received-Millis: 1676031445941
[DOTNET]   X-Android-Response-Source: NETWORK 401
[DOTNET]   X-Android-Selected-Protocol: http/1.1
[DOTNET]   X-Android-Sent-Millis: 1676031445603
[DOTNET]   Content-Length: 0
[DOTNET] }
[DOTNET] Response body: ''
[DOTNET] Request: Method: GET, RequestUri: 'https://httpbin.org/basic-auth/username/correct-password', Version: 1.1, Content: <null>, Headers:
[DOTNET] {
[DOTNET] }
[DOTNET] Response: StatusCode: 401, ReasonPhrase: 'UNAUTHORIZED', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
[DOTNET] {
[DOTNET]   Access-Control-Allow-Credentials: true
[DOTNET]   Access-Control-Allow-Origin: *
[DOTNET]   Connection: keep-alive
[DOTNET]   Date: Fri, 10 Feb 2023 12:17:26 GMT
[DOTNET]   Server: gunicorn/19.9.0
[DOTNET]   WWW-Authenticate: Basic realm="Fake Realm"
[DOTNET]   X-Android-Received-Millis: 1676031446474
[DOTNET]   X-Android-Response-Source: NETWORK 401
[DOTNET]   X-Android-Selected-Protocol: http/1.1
[DOTNET]   X-Android-Sent-Millis: 1676031445992
[DOTNET]   Content-Length: 0
[DOTNET] }
[DOTNET] Response body: ''
[DOTNET] 
[DOTNET] =======
[DOTNET] Test username=username, password=correct-password
[DOTNET] =======
[DOTNET] Request: Method: GET, RequestUri: 'https://httpbin.org/basic-auth/username/correct-password', Version: 1.1, Content: <null>, Headers:
[DOTNET] {
[DOTNET] }
[DOTNET] Response: StatusCode: 401, ReasonPhrase: 'UNAUTHORIZED', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
[DOTNET] {
[DOTNET]   Access-Control-Allow-Credentials: true
[DOTNET]   Access-Control-Allow-Origin: *
[DOTNET]   Connection: keep-alive
[DOTNET]   Date: Fri, 10 Feb 2023 12:17:27 GMT
[DOTNET]   Server: gunicorn/19.9.0
[DOTNET]   WWW-Authenticate: Basic realm="Fake Realm"
[DOTNET]   X-Android-Received-Millis: 1676031446650
[DOTNET]   X-Android-Response-Source: NETWORK 401
[DOTNET]   X-Android-Selected-Protocol: http/1.1
[DOTNET]   X-Android-Sent-Millis: 1676031446491
[DOTNET]   Content-Length: 0
[DOTNET] }
[DOTNET] Response body: ''
[DOTNET] Request: Method: GET, RequestUri: 'https://httpbin.org/basic-auth/username/correct-password', Version: 1.1, Content: <null>, Headers:
[DOTNET] {
[DOTNET] }
[DOTNET] Response: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
[DOTNET] {
[DOTNET]   Access-Control-Allow-Credentials: true
[DOTNET]   Access-Control-Allow-Origin: *
[DOTNET]   Connection: keep-alive
[DOTNET]   Date: Fri, 10 Feb 2023 12:17:28 GMT
[DOTNET]   Server: gunicorn/19.9.0
[DOTNET]   X-Android-Received-Millis: 1676031447873
[DOTNET]   X-Android-Response-Source: NETWORK 200
[DOTNET]   X-Android-Selected-Protocol: http/1.1
[DOTNET]   X-Android-Sent-Millis: 1676031446664
[DOTNET]   Content-Length: 51
[DOTNET]   Content-Type: application/json
[DOTNET] }
[DOTNET] Response body: '{
[DOTNET]   "authenticated": true, 
[DOTNET]   "user": "username"
[DOTNET] }
[DOTNET] '
[DOTNET] 
```

**Comment by wfurt** [comment]
> AFAIK the default native handler that's used internally by HttpClientHandler on Android won't include Credentials by default.

Should it? This makes it problematic for anybody who wants to write portable code that runs same on all platforms. 
It would be great IMHO if people do not need to understand all  the platform differences.

**Comment by mimegh** [comment]
I agree with @wfurt . The implementation should be platform independent or at least should have the same behavior for all platforms.   

@simonrozsival : thank you for your analysis. However I would like to prevent a platform dependent implementation.

**Comment by grendello** [comment]
Credentials handling is found in [`HttpClientHandler`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.credentials?view=net-7.0) and it defaults to `null`, therefore the Android message handler assumes the same default.  The underlying handler cannot set any default credentials, obviously, but it also doesn't have access to the `HttpClientHandler` properties, so it can't fetch the credentials from it.  This is an unfortunate consequence of an API break in `NET6` which the underlying Android handler predates.

The problem here stems from the inherited design of the native Android client handler.  Before .NET6, it was derived directly from `HttpClientHandler` and everything worked seamlessly, since it had full access to the necessary properties (in this case `Credentials`, but also `Proxy` which is relevant in certain cases).  However, starting with `NET6` it's derived from `HttpMessageHandler` while having to retain the API interface from before that change for backward compatibility reasons - therefore it needs to define its own `Credentials` property (among others).  There's unfortunately no good solution here - either the native client handler's API compatibility needs to be broken (which may not be the worst idea) or `HttpClientHandler` must be made aware of the requirements of the underlying message handler or the underlying message handler needs to be given access to its "owning" client handler so that it can read the various properties affecting the request.

An additional complication here is the inherent difference between the actual native handlers (Java's `HttpURLConnection` and e.g. iOS `NSUrl`) themselves and their requirements/quirks/incompatibilities with regards to the managed API we deal with.

**Comment by simonrozsival** [comment]
@grendello I'm not sure I understand you right now. `HttpClientHandler` is just a proxy for `AndroidMessageHandler` in this case and so setting the `Credentials` or `Proxy` properties of `HttpClientHandler` will [set the corresponding properties](https://github.com/dotnet/runtime/blob/be84df7642f21702b0e7859f0c134e4d6cfc67eb/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.InvokeNativeHandler.cs#L146-L147) on `AndroidMessageHandler`. It should have all the necessary information to pre-authenticate requests when `PreAuthenticate` is `true` and there are credentials available for the URL.

**Comment by grendello** [comment]
@simonrozsival yes, you're correct, but what I meant was that the interface is not, hmm, complete in the adaptation of the "old" native Android client handler and the "new" one. Your code sample shows that we need to set `PreAuthenticationData` which was unfortunately necessary to make it work with the Java native handler and I just wonder if `HttpClientHandler` could be modified to set that property as well, somehow. Also, your code sample showed setting `Credentials` on the message handler directly, I assumed that it was because setting them on the `HttpClientHandler` instance wouldn't work?

**Comment by simonrozsival** [comment]
@grendello I see. I used the AndroidMessageHandler because I don't think it's possible to achieve the result without working with it directly.

To match the behavior of SocketsHttpHandler, we would have to handle 401 Unauthorized with WWW-Authenticate headers and repeat the request with authentication if we have the matching credentials. I can't see how that's dependent on the Java HttpURLConnection. We already handle NTLM authentication this way in the Android handler.

**Comment by grendello** [comment]
@simonrozsival yeah, it's a bit of a confusing mess... Perhaps handling 401 would make sense, even at the cost of the extra request. It would be enabled by default, with a way to disable it (a property on `AndroidMessageHandler`) if need be. I suppose most people would be fine with this kind of a breaking change.

**Comment by wfurt** [comment]
`SocketsHttpHandler` has `Credentials` and `PreAuthenticationData`. And they are filled in automatically when it is used as backend for `HttpClientHandler`.
I'm wondering if there is some complexity as the Android code lives in separate repo. I feel we should figure out how to make it work as this is going to be ongoing pain IMHO. We should ask @stephentoub for help if we cannot figure it out.

**Comment by steveisok** [comment]
> `SocketsHttpHandler` has `Credentials` and `PreAuthenticationData`. And they are filled in automatically when it is used as backend for `HttpClientHandler`. I'm wondering if there is some complexity as the Android code lives in separate repo. I feel we should figure out how to make it work as this is going to be ongoing pain IMHO. We should ask @stephentoub for help if we cannot figure it out.

I don't think there's a high degree of complexity in terms of where it lives. The problem is more about certain assumptions changing between mono/mono and dotnet/runtime in terms of how the handler is used. 

@simonrozsival came up with a few ideas of what it may take to bring enough things back to runtime. Even though it isn't a high priority item for us right now, it might be a good idea to submit the design and get feedback on it.

**Comment by steveisok** [comment]
> To match the behavior of SocketsHttpHandler, we would have to handle 401 Unauthorized with WWW-Authenticate headers and repeat the request with authentication if we have the matching credentials. I can't see how that's dependent on the Java HttpURLConnection. We already handle NTLM authentication this way in the Android handler. It might be a breaking change though so I'm not sure if we should actually change the behavior or not.

I think that's what needs to happen in order to fix the issue.  @grendello is there an easy way to transfer this to the XA repo?

**Comment by grendello** [comment]
@steveisok I don't think there's a way to transfer this issue as-is. I think it's best to keep this one here open and create a new one referring to it in the XA repo.

**Comment by ScottV78** [comment]
For anyone else having this issue the following code seems to work for me.

`_httpClient = new HttpClient();

            string headAuth = Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes($"{userName}:{userPassword}"));

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", headAuth);`

**Comment by JimAIT** [comment]
I have the same problem.  Very simple code.

HttpClient http;
var credentials = new NetworkCredential(Globals.UserName, Globals.Password);
var handler = new HttpClientHandler { Credentials = credentials };
http = new System.Net.Http.HttpClient(handler);
url = Globals.oDataService + "/OdataV4/Company('" + Globals.CompanyName + "')/" + postUrl;
var response = await http.GetAsync(url);

Works fine in Xamarin Forms both Windows and Android
Works fine in MAUI on Windows
MAUI on Android - 401 unauthorized error

**Comment by steveisok** [comment]
Closing in favor of https://github.com/xamarin/xamarin-android/issues/8379 because that's where the fix needs to happen.
