### ISSUE TITLE
How to set the maximum memory usage of a .net program

### ISSUE THREAD

**Issue by dingsongjie** [dotnet/runtime#81872]
I have some .net programs running in kubernetes, and set memory limits in the containers. Recently, I found that some containers were restarted due to oomkilled. I set some environment variables to let the .net programs  create dump file automatically before crashing, and added eating persistent storage, but this seems to have no effect, because the container is quickly killed by kubelet,  the dump file is not completely created, so I think it is possible to manually set the memory limit of the .net program, And set it lower than the memory limit of the container, that the .net program has insufficient memory, the container will not be killed, and there is enough time to create a dump file before it is automatically restarted

**Comment by Symbai** [comment]
Take a look at [Heap Limit](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-limit)

**Comment by janvorli** [comment]
@dingsongjie can you please share:
* Which version of .NET you are using
* What memory limits do you set for the containers
* Does your code do reflection emit, use Linq or any other dynamic code generation?
* Do you happen to have a virtual memory limit set for your containers?
* Do you use server GC or workstation GC?

The OOM can be caused by several factors like exceeding physical memory usage, exceeding virtual memory limit if set or exceeding number of memory mappings (the default is 65536). 

As an experiment, you can try to limit the GC heap size using DOTNET_GCHeapHardLimit env variable to a hexadecimal value (without any prefix) representing size in bytes. For example `DOTNET_GCHeapHardLimit=c800000` would set the limit to 200MB.
