### ISSUE TITLE
CA5392 Misses Violations on Local P/Invoke Functions Generated by LibraryImportGenerator

### ISSUE THREAD

**Issue by BadEcho** [dotnet/runtime#81939]
### Description

~~This is written under the assumption that the `DefaultDllImportSearchPath` attribute is ignored and has no effect on source-generated P/Invoke functions that are declared using the `LibraryImport` attribute.~~

The CA5392 analysis rule is only detecting violations for P/Invoke functions that use the `LibraryImport` attribute if the signatures are blittable; i.e., the stub produced by `LibraryImportGenerator` is a basic forwarder stub (regular `DllImport`).

On the other hand, if the stub's `DllImport` is a local function, CA5392 doesn't end up checking for the lack of a `DefaultDllImportSearchPath` attribute.

### Reproduction Steps

Paste the following into VS 2022:

```
internal static partial class Interop
{
    private const string LIBRARY_NAME = "user32";

    // CA5392 violation: signature is blittable and basic forwarder stub produced.
    [LibraryImport(LIBRARY_NAME)]
    public static partial int ReleaseDC(IntPtr hWnd, IntPtr hdc);

    // No CA5392 violation: Local P/Invoke function produced due to SetLastError being set to true.
    [LibraryImport(LIBRARY_NAME, SetLastError = true)]
    public static partial IntPtr CallNextHookEx(IntPtr hhk, int nCode, IntPtr wParam, IntPtr lParam);

    // CA5392 violation: signature is blittable as all parameters are built-in types.
    [LibraryImport(LIBRARY_NAME, EntryPoint = "GetWindowLong")]
    public static partial IntPtr GetWindowLongPtr32(IntPtr hWnd, int nIndex);

    // No CA5392 violation: Local P/Invoke function produced due to one of the members being a derived SafeHandle.
    [LibraryImport(LIBRARY_NAME, EntryPoint = "GetWindowLongPtrW")]
    public static partial IntPtr GetWindowLongPtr64(WindowHandle hWnd, int nIndex);
}
```

### Expected behavior

All of the above methods should flag CA5392 violations because they are all missing `DefaultDllImportSearch` attributes.

### Actual behavior

Only some of the methods (the ones that result in basic forwarder stubs) result in CA5392 violations.

### Regression?

Unknown.

### Known Workarounds

SuppressMessageAttribute :)

### Configuration

.NET 7, latest version of VS 2022 17.4.4
Windows 10 x64

**Comment by AaronRobinsonMSFT** [comment]
@omniscientist Thanks for reporting this issue, I don't think we considered this attribute.

> This is written under the assumption that the DefaultDllImportSearchPath attribute is ignored and has no effect on source-generated P/Invoke functions that are declared using the LibraryImport attribute.

The `LibraryImport` attribute does generate a `DllImport`, albeit with a different signature, and certain attributes on the declaration are forwarded to the generated `DllImport` - see https://github.com/dotnet/runtime/blob/ff3ee85603125a2d5c1fe8f797701a1ead9c5b5b/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/LibraryImportGenerator.cs#L113-L158

If you are interested in contributing feel free to submit a PR otherwise we should add the above attribute to the list we forward.

/cc @jtschuster

**Comment by omniscientist** [comment]
> The `LibraryImport` attribute does generate a `DllImport`, albeit with a different signature, and certain attributes on the declaration are forwarded to the generated `DllImport` - see

OK, thanks. Took a look at the source involved and it seems that the actual issue is that CA5392 fails to find violations if the end result P/Invoke signature with the `DllImport` is a local statement.

All the P/Invoke functions I had that were triggering the CA5392 were basic forwarder stubs (`pInvokeStubCodeGenerator.StubIsBasicForwarder == true`).

I'll edit the reported issue above so it's a bit more accurate.

**Comment by jkoritzinsky** [comment]
Fixed by https://github.com/dotnet/roslyn-analyzers/pull/6493
