### ISSUE TITLE
Fast-path serialization should provide OOTB support for JsonSerializerDefaults.Web

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#81985]
In https://github.com/aspnet/Benchmarks/pull/1772/commits/eb2b486e8e64a3b47ba9370aa5463eda462343f4 we experimented with using the new [streaming fast path serialization](https://github.com/dotnet/runtime/pull/78646).

While the RPS stays the same for a simple single string field struct, the allocations per second drops from 177m bytes/sec to 33m bytes/sec, and working set drops from 465MB to 437MB.

----

What we found is that it's unusable in an ASP.NET Core app without very deep knowledge of the stack.
You have to match some of the JsonOptions in the source-gen context with those provided by the framework (ASP.NET Cores web defaults), [set the `Encoder` to null](https://github.com/dotnet/runtime/issues/59424) in order to get the fast path to run, and combine TypeInfoResolvers in the correct order https://github.com/dotnet/runtime/blob/9e7d3c00f03c61402b17acdaeb6d0e0d323b8940/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerContext.cs#L44
```
builder.ConfigureHttpJsonOptions(jsonOptions =>
{
    // Worked before the recent changes to fix Combining contexts
    // jsonOptions.SerializerOptions.AddContext<CustomJsonContext>();
    jsonOptions.SerializerOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine(new CustomJsonContext(), jsonOptions.SerializerOptions.TypeInfoResolver);
});
```
`DefaultJsonTypeInfoResolver` will always resolve a `JsonTypeInfo` so the custom one won't be used unless you order it correctly.
https://github.com/dotnet/runtime/blob/7576cc5d467d56d9f61dccc333cb8de29601fd80/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoResolver.cs#L67-L69

We would like to figure out if there is a way to make this happy path easier to use. In an ideal world the source-gen and the frameworks `JsonOptions` would just work together seamlessly, but we understand there is a disconnect between the APIs which might make it difficult.

One suggestion was there could be a "Web" default for example on the `JsonSourceGenerationOptions` or as a separate attribute.

**Comment by eiriktsarpalis** [comment]
If I'm understanding the ask correctly, it can be broken down to two separate concerns:

1. Adding fast-path support for features not currently supported, like #59424.
2. Combining multiple contract resolvers without needing to be concerned with order.

We can try to prioritize work for 1) as long as you pinpoint the specific features you would like to see brought over, however 2) is tricky: when multiple sources provide contracts for the same type some form of disambiguation is necessary -- the `Combine` method does this by giving precedence to the first components. I don't think we could avoid this.

I'm wondering if the concern is primarily an issue of API ergonomics rather than semantics. In other words, do you think the problem primarily lies with the fact that the following assignment
```C#
jsonOptions.SerializerOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine(new CustomJsonContext(), jsonOptions.SerializerOptions.TypeInfoResolver);
```
is too much code to type? Or is it something different?

One possibility might be to expose [`CombinedJsonTypeInfoResolver`](https://github.com/dotnet/runtime/blob/b4c1a099be69fce0e4354453c2181b06144400fc/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoResolver.cs#L58-L78) as a mutable class implementing `IList<IJsonTypeInfoResolver>` so that users can view and manipulate the order of resolvers in an explicit manner. But because the `TypeInfoResolver` property is of type `IJsonTypeInfoResolver` this wouldn't be as straightforward to use:
```C#
// Perform an unsafe cast on the assumption that the resolver provided by `JsonOptions` is a list of resolvers
((CombinedJsonTypeInfoResolver)jsonOptions.SerializerOptions.TypeInfoResolver).Insert(0, new CustomJsonContext());
```
So we might instead consider exposing a second property on `JsonSerializerOptions` as follows:
```diff
public class JsonSerializerOptions
{
    public IJsonTypeInfoResolver? TypeInfoResolver { get; set; }
+    public IList<IJsonTypeInfoResolver> TypeInfoResolvers { get; }
}
```
I think it should be possible to do this without breaking the shipped property and so that the two settings are always kept in sync. With that change, your code would look as follows:
```C#
jsonOptions.SerializerOptions.TypeInfoResolvers.Insert(0, new CustomResolver());
```

**Comment by eiriktsarpalis** [comment]
I believe the concerns have mostly been addressed via #83095 and #71933, so I think we can close this?

**Comment by BrennanConroy** [comment]
> You have to match some of the JsonOptions in the source-gen context with those provided by the framework (ASP.NET Cores web defaults), https://github.com/dotnet/runtime/issues/59424 in order to get the fast path to run

Both of these are still true I believe which are the main issues.
See https://github.com/aspnet/Benchmarks/commit/eb2b486e8e64a3b47ba9370aa5463eda462343f4#diff-11c7e968ccf631f289d062511dff16517a49ac828795705b0eebbfd588ecb475R52 and https://github.com/aspnet/Benchmarks/commit/eb2b486e8e64a3b47ba9370aa5463eda462343f4#diff-c913014230437d5b01e6ec0498c04360edca84d3e436f49883c669fe5a5d2a96R90 for the non-obvious changes that need to be done to use the fast-path in ASP.NET Core apps.

**Comment by eiriktsarpalis** [comment]
> Both of these are still true I believe which are the main issues. See [aspnet/Benchmarks@eb2b486#diff-11c7e968ccf631f289d062511dff16517a49ac828795705b0eebbfd588ecb475R52](https://github.com/aspnet/Benchmarks/commit/eb2b486e8e64a3b47ba9370aa5463eda462343f4#diff-11c7e968ccf631f289d062511dff16517a49ac828795705b0eebbfd588ecb475R52) and [aspnet/Benchmarks@eb2b486#diff-c913014230437d5b01e6ec0498c04360edca84d3e436f49883c669fe5a5d2a96R90](https://github.com/aspnet/Benchmarks/commit/eb2b486e8e64a3b47ba9370aa5463eda462343f4#diff-c913014230437d5b01e6ec0498c04360edca84d3e436f49883c669fe5a5d2a96R90) for the non-obvious changes that need to be done to use the fast-path in ASP.NET Core apps.

Supporting custom encoders is tracked by https://github.com/dotnet/runtime/issues/59424. Keeping this issue open to track possibly adding support for compile-time `JsonSerializerDefaults` configuration.

**Comment by eiriktsarpalis** [comment]
Related to Related to https://github.com/dotnet/runtime/issues/57321.

**Comment by eiriktsarpalis** [comment]
I've incorporated this request into the API proposal in https://github.com/dotnet/runtime/issues/57321
