### ISSUE TITLE
PS7.3 (using .NET 7) locks up when used with screen on Linux and macOS

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#82110]
### Description

When using PS7.2 (built on .NET 6) with screen, it works fine on Linux (still seems to lock up on macOS).

PS7.3 (built on .NET 7) with screen will lock up (seems to be waiting on stdin) after running a native command:

```bash
screen ./pwsh
ls
```

Running cmdlets (like `get-childitem`) works fine.  Only when executing a native command does it seem to be blocking and because the process doesn't finish, the PS prompt never comes.

I did rebuild 7.2 (which works with screen on Linux) against .NET 7 and that also exhibits the same locking behavior, so it seems that it's due to a change in .NET 7.

Using `set DOTNET_SYSTEM_CONSOLE_USENET6COMPATREADKEY=1` does not resolve the issue, so it seems unrelated to those changes.

### Reproduction Steps

I tried creating a simple repl that starts exes, but it doesn't repro the issue.  PS7 does more complex work reading keyboard and handling starting exes.

```bash
screen ./pwsh
ls
```

### Expected behavior

`ls` to output and PS prompt to come back

### Actual behavior

`ls` shows output, and process is blocked

### Regression?

From .NET 6

### Configuration

Specifically tested under Ubuntu 22.04 using WSL

**Comment by adamsitnik** [comment]
@tmds is there any chance you could take a look? Is it possible that it's related to 7.0 Process changes?

**Comment by tmds** [comment]
I don't think so, the Process change for .NET 7 shouldn't affect anything that isn't running in a container (where .NET runs as pid 1).

I will take a closer look.

**Comment by tmds** [comment]
I took a closer look at this.

When the `ls` process exits, PowerShell sets the `Console.Title` and it calls `Console.GetCursorPosition()`.

For `Console.Title`, .NET 6 does nothing, and .NET 7 sends:

https://github.com/dotnet/runtime/blob/414732beabdf460c15d4ed56f664191c853b784e/src/libraries/System.Console/src/System/TerminalFormatStrings.cs#L214

due to this new condition:

https://github.com/dotnet/runtime/blob/414732beabdf460c15d4ed56f664191c853b784e/src/libraries/System.Console/src/System/TerminalFormatStrings.cs#L196-L199

I think we're sending something inappropriate for `Title`.
Then the request is made for the cursor position, it is not understood, and no response comes.

The issue can be reproduced by running the following program under `screen`:

```cs
Console.Title = "title";
Console.GetCursorPosition();
```

Under `screen`, I have `TERM` of `screen.xterm-256color`.

**Comment by tmds** [comment]
> I think we're sending something inappropriate for Title.

The escape sequence is missing a backslash at the end.

From https://www.gnu.org/software/screen/manual/html_node/Naming-Windows.html:

> To change the name after the window has been created you can use the title-string escape-sequence (ESC k name ESC \\)
