### ISSUE TITLE
Some OOB assemblies are not copying intellisense extracted from docs package

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#82214]
Some of our assemblies are not showing intellisense in VS.

With our recent intellisense changes, I checked if we were overwriting the built intellisense xml with the one from the docs nuget package, and noticed it's not. I think we should, if the `UseIntellisensePackageDocXmlFile` property is not explicitly set to `false` in the csproj.

This problem seems to be somewhat related to having the `GeneratePlatformNotSupportedAssemblyMessage` property specified in the csproj, but I'm not entirely confident, because there are some assemblies without this problem. The `IsPartialFacadeAssembly` property does not seem to be affecting, although it could also be a combination of the two properties.

Here's a list I collected:

| IsPackable assembly                        | Generates PNSE? | Is Façade? | Intellisense in VS? |
|--------------------------------------------|-----------------|------------|---------------------|
| System.Security.Cryptography.ProtectedData | No              | Yes        | No                  |
| System.Net.Http.WinHttpHandler             | Yes             | No         | No                  |
| System.Security.Cryptography.Pkcs          | Yes             | No         | No                  |
| System.Speech                              | Yes             | No         | No                  |
| System.Diagnostics.EventLog                | Yes             | Yes        | No                  |
| System.IO.Ports                            | Yes             | Yes        | No                  |
| Microsoft.Extensions.Hosting               | No              | No         | Yes                 |
| System.Reflection.MetadataLoadContext      | No              | No         | Yes                 |
| System.Resources.Extensions                | No              | No         | Yes                 |
| System.Text.Encodings.Web                  | No              | No         | Yes                 |
| System.ComponentModel.Composition          | Yes             | No         | Yes                 |
| System.Reflection.Context                  | Yes             | No         | Yes                 |
| System.Data.Odbc                           | Yes             | Yes        | Yes                 |

Related to https://github.com/dotnet/runtime/issues/79030

**Comment by carlossanlop** [comment]
Looking at this a bit more with a binlog, it seems the property `IsNetCoreAppSrc` is not set when running `dotnet pack` on the src csproj of an OOB assembly. This causes the `CopyDocumentationFileToXmlDocDir` target to get skipped.

https://github.com/dotnet/runtime/blob/2ba2396495c22429035d165e478672c442f81e22/eng/intellisense.targets#L41-L43

This might be naive to ask, but I wonder if that condition could be extended to check if either `IsNetCoreAppSrc` is `true` or if `IsPackable` is `true`.

**Comment by carlossanlop** [comment]
What we discussed it in my PR was the placement of xml files of OOB packages in the `artifacts/bin/docs` folder, which is useless for OOB packages. What I am trying to do in this issue is to understand why the documentation of OOB packages regressed from 5.0: they used to have their full documentation, but now they only show SR strings. I posted some additional findings, specific to System.IO.Ports, in https://github.com/dotnet/runtime/issues/79030.

I think we could add logic that swaps the built xml file of OOB packages with the one from dotnet-api-docs. I assume we would have to do this somewhere in the `packaging.targets` file. The logic would be very similar to what we have in `intellisense.targets` but the target path of the xml would be different.

**Comment by carlossanlop** [comment]
> What you describe is what this target already does

I tested running the `dotnet pack` command inside `src/libraries/System.IO.Ports`, and Unfortunately, the `ChangeDocumentationFileForPackaging` target is not getting called at all. That target only gets invoked in `System.Text.Encoding.CodePages`, which seems to be a referenced project of `System.IO.Ports`.

If it worked for that command, I am not sure if the file would be swapped on time, because it looks like `packaging.targets` gets included _before_ `intellisense.targets`. Unless I'm missing something, I think that means the nupkg gets generated first.

**Comment by ViktorHofer** [comment]
> If it worked for that command, I am not sure if the file would be swapped on time, because it looks like packaging.targets gets included before intellisense.targets. Unless I'm missing something, I think that means the nupkg gets generated first.

That's not how msbuild works. The order of target file imports doesn't define the order in which target files are run.

> I tested running the dotnet pack command inside src/libraries/System.IO.Ports, and Unfortunately, the ChangeDocumentationFileForPackaging target is not getting called at all. That target only gets invoked in System.Text.Encoding.CodePages, which seems to be a referenced project of System.IO.Ports.

That's because you missed @ericstj's comment here: https://github.com/dotnet/runtime/pull/79134#discussion_r1082929940. He suggested to use a different hook point as the current one runs too late. It's not clear to me how this actually worked to begin with and I'm nervous that our current packages in main contain the wrong intellisense file. Can you please double check that that's not the case?

**Comment by carlossanlop** [comment]
It seems that we've been including the wrong intellisense file in OOB packages since .NET 6.0 RC2.

I created a console app targeting net6.0, I added the System.IO.Ports nuget package as a dependency, and manually changes versions, until I found that VS was still showing the correct intellisense in the nuget package version `6.0.0-rc.1.21451.13` (published on Sept 14 2021), and intellisense completely disappeared starting with version `6.0.0-rc.2.21480.5` (published on Oct 12 2021).

The RC1 package contained the xml file that included all the APIs, and the RC2 only contained exceptions with SR strings.

The .NET 6.0 RC1 branch was snapped on August 17th and shipped on Sept 14th, while RC2 was snapped on Sept 14th and shipped on Oct 12th. Both RC1 and RC2 got snapped from main. [Calendar](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/28480/NET-6-Schedule-Archive-(completed-previews)).

I found a couple of big refactoring that were merged to main before the RC2 snap and touched the packaging infra (Sept 14th):
- https://github.com/dotnet/runtime/pull/58558 (Sept 10th).
- https://github.com/dotnet/runtime/pull/58011 (Sept 8th).

I also found a change that might be relevant _only_ to the System.IO.Ports case, but it went into RC1, so chances are it didn't cause this regression:
- https://github.com/dotnet/runtime/pull/57118 (Aug 10th)

**Comment by ViktorHofer** [comment]
> Simplify .NETFramework tfms #58558

That change isn't part of the release/6.0 branch (it can't be - otherwise we would have shipped net7.0 assemblies in our 6.0 packages):

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7412651/219746389-6178f97d-b4b7-4287-81b2-2cb574280445.png">

> Upgrade to net7.0 and remove target frameworks #58011 (Sept 8th).

That change isn't either in 6.0:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/7412651/219754624-59442ea6-84a6-41e5-bd26-008c6fb1aeda.png">

I agree that the intellisense files are broken since .NET 6 but the above listed changes aren't the culprit.

**Comment by ViktorHofer** [comment]
Reason for that is that the packaging logic tries to find the documentation file here (from the release/7.0 branch): `C:\Users\vikto\.nuget\packages\microsoft.private.intellisense\7.0.0-preview-20221010.1\IntellisenseFiles\net\1033\System.Drawing.Common.xml`. I think we already talked about this and noticed that the wrong intellisense files were picked up for some time.

This regressed with https://github.com/dotnet/runtime/commit/22cee85aa08061e5b2c1e893797a860e3c642e6c which converted pkgprojs to NuGet Pack task based project packaging. [The previous logic logic considered all directories](https://github.com/dotnet/runtime/blob/19fde2f5b9dd7c8b5f37e9f02688ff9b708b24b5/eng/restore/docs.targets#L12) while that change introduced the behavior to only look into the `net` folder.

Fortunately this is already fixed in main: https://github.com/dotnet/runtime/blob/986abeccbf7766cebc02eaa017cf92f07c2e4c33/eng/intellisense.targets#L20-L21

I will start an offline conversation about backporting a fix into release/7.0 and release/6.0. Meanwhile, @carlossanlop can you please work on the fix that @ericstj suggested in https://github.com/dotnet/runtime/pull/79134#discussion_r1082929940?
