### ISSUE TITLE
Clarification on NuGet versioning with regards to supported SDK/runtime

### ISSUE THREAD

**Issue by handerss-tibco** [dotnet/runtime#82225]
This is essentially a continuation of https://github.com/dotnet/runtime/issues/81740. I opened a new issue as was suggested by @ViktorHofer at the end of that issue thread.

From what I could gather from that thread this is true:
1. Recommended to stay on latest SDK/runtime and packages release using incremental servicing due to security reasons.
2. SDK/runtime and package version are **not** in sync.
3. Some package ship with every release (AspNetCore) and some use incremental servicing (dotnet/runtime libraries).

Unfortunately staying on latest SDK/runtime, may not be possible for all applications, especially the ones which aren't self-contained. Luckily, some packages (the ones which use incremental servicing) ship DLLs for earlier versions, e.g. [System.Windows.Extensions](https://www.nuget.org/packages/System.Windows.Extensions/) 7.0.0 contains libs for .NET 6. This allows for using the latest libraries (with security patches) when targeting older but still supported SDKs/runtimes. 

This breaks down however if you have conflicting transitive dependencies. Considering for example if I want to use [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) 6.0.0 (due to it throwing on Linux in 7.0.0) but I want to have the latest security patches for System.Windows.Extensions. From what I gather from the previous issue I would need to use the latest version of System.Windows.Extensions, which is 7.0.0, to get these patches. This leads to package downgrade errors (NU1605, NU1109) and a failing compilation since the package transitively requires System.Drawing.Common to also be >= 7.0.0.

If a CVE or other security issue is detected in a dotnet/runtime package released via incremental servicing will there also be a 6.x.x release which is compatible with other 6.x.x packages? E.g. does the LTS support for .NET 6 extend to its packages in the sense that they will be backported to API compatible versions? Or does a CVE in a library now force me to upgrade all dependencies, some of which may not be API compatible with my original .NET6 application?

As far I can tell the version requirement on System.Drawing.Common from System.Windows.Extensions is too strict since System.Drawing.Common has not introduced any new APIs or changed behavior in such a way that would warrant this version range (>= 7.0.0 for net6.0). Note that I am talking about the version ranges with regards to the net6.0 target here, obviously the net7.0 target needs the later package versions. Shouldn't the version ranges be as forgiving as possible to avoid transitive dependency hell (maybe they are and I am actually wrong here)?

A second question with regards to (3.) is that I assume I **should not** use the latest version of packages which ship with every release, since these will ship a compatible version for each supported .NET SDK/runtime. Is this true? Since these library usually ship a .NET Standard 2.0 library I won't get any warnings/errors if I accidentally pick a 7.0.0 version for my .NET 6 application. Is that a problem, i.e. is the .NET Standard 2.0 dll worse that the .NET 6 dll?

**Comment by ViktorHofer** [comment]
> This breaks down however if you have conflicting transitive dependencies. Considering for example if I want to use [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) 6.0.0 (due to it throwing on Linux in 7.0.0) but I want to have the latest security patches for System.Windows.Extensions. From what I gather from the previous issue I would need to use the latest version of System.Windows.Extensions, which is 7.0.0, to get these patches. This leads to package downgrade errors (NU1605, NU1109) and a failing compilation since the package transitively requires System.Drawing.Common to also be >= 7.0.0.

In this case it's fine to stay on the 6.0.x packages, there's no requirement to always use the very latest. Note that this "workaround" around Unix support for System.Drawing.Common won't work anymore with .NET 9 packages (which release next year) as such won't contain .NET 6 assets. Only mentioning that so that you are aware that in less than two years, the System.Drawing.Common cross-plat offering won't be supported anymore and that you would be better off to find an alternative for it, sooner than later.

> If a CVE or other security issue is detected in a dotnet/runtime package released via incremental servicing will there also be a 6.x.x release which is compatible with other 6.x.x packages? E.g. does the LTS support for .NET 6 extend to its packages in the sense that they will be backported to API compatible versions? Or does a CVE in a library now force me to upgrade all dependencies, some of which may not be API compatible with my original .NET6 application?

Yes. As long as the associated .NET release is in support, packages will be serviced. See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core for the release lifecycle. That effectively means that you will get servicing updates for .NET 6 until November 12, 2024.

> As far I can tell the version requirement on System.Drawing.Common from System.Windows.Extensions is too strict since System.Drawing.Common has not introduced any new APIs or changed behavior in such a way that would warrant this version range (>= 7.0.0 for net6.0). Note that I am talking about the version ranges with regards to the net6.0 target here, obviously the net7.0 target needs the later package versions. Shouldn't the version ranges be as forgiving as possible to avoid transitive dependency hell (maybe they are and I am actually wrong here)?

We don't apply semver2 strictness per library today. While that might be aspirational, it's not a pattern that we currently follow and we don't have anything on our backlog to change that. Instead, we rev the major package and assembly version for all libraries once per release (i.e. .NET 8 compiled assemblies have 8.0.0.x versions and and the produced packages an 8.0.x version).

> A second question with regards to (3.) is that I assume I should not use the latest version of packages which ship with every release, since these will ship a compatible version for each supported .NET SDK/runtime. Is this true?

As mentioned in the other thread, using latest package versions in a non EOL .NET release is fully supported. What makes you believe otherwise?

> Since these library usually ship a .NET Standard 2.0 library I won't get any warnings/errors if I accidentally pick a 7.0.0 version for my .NET 6 application. Is that a problem, i.e. is the .NET Standard 2.0 dll worse that the .NET 6 dll?

Only speaking about the dotnet/runtime packages here as I don't know what other teams do but a 7.0.0 package usually has a net6.0 assembly in it (except for very new releases of a library) which means that the netstandard2.0 assembly won't be chosen as the net6.0 is the nearest compatible assembly tfm.

If you would instead ask: `What happens if I use a .NET 9 package in my .NET 6 app?` I would respond with, that you would get a build warning mentioning that .NET 6 isn't supported anymore by the package (even though it has a netstandard2.0 asset in it). That's because the netstandard2.0 assembly might behave differently or doesn't work at run-time at all.

cc @ericstj @carlossanlop

**Comment by handerss-tibco** [comment]
@ViktorHofer Thanks a lot for the response! My takeaway then is that the packages released via incremental servicing will get 6.0.x releases for security issues (within the support window).

I should have added some context to the question about packages which ship with every release. Take for example [Microsoft.AspNetCore.JsonPatch](https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/) (or any other Microsoft.AspNetCore package I believe), this package has 2 latest versions 6.0.14 and 7.0.3. The 7.0.3 version does not include a .NET6 dll. I assume that if accidentally bump my package version to 7.0.3 then I may get a "worse" dll since I will then end up with the .NET Standard compiled dll.

However, if my takeaway that 6.0.x packages will release when security issues are patched then this is a non issue since that means we can just trust that Microsoft follows semantic versioning.

**Comment by ViktorHofer** [comment]
@handerss-tibco yes, your above observation is correct within the support window. I'm closing the issue now.
