### ISSUE TITLE
[QUIC] Revisit exceptions in Quic

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#82262]
We have several exception issues cropping up for 8.0:
- [ ] https://github.com/dotnet/runtime/issues/78751
- [x] https://github.com/dotnet/runtime/issues/75184
- [ ] https://github.com/dotnet/runtime/issues/72666
- [ ] https://github.com/dotnet/runtime/issues/78096
  - Partially fixed in https://github.com/dotnet/runtime/pull/82261

**Comment by antonfirsov** [comment]
It would be also nice to distinguish name resolution errors and define `QuicError.HostNotFound` so we can have a unified name resolution error case in #76644.

**Comment by wfurt** [comment]
We agreed that we should:
- throw `SocketException` for transport problem e.g. for cases like MsQuic AddressInUse, HostUnreachable and InvalidAddress. That generally comes either as user error, host limitation and network conditions. That also covers cases when target name cannot be resolved to address.  
- We will throw `AuthenticationException` for TLS and certificate related issues - preferably matching `SslStream` behavior. 
- We will throw `QuicException` for reasons related to Quic protocol or processing specific to Quic.
- `ArgumentException` when supplied parameters or options provided by callback are not valid.
- `OperationCanceledException` for cases when processing fail because of cancellation.
- `ObjectDisposedException` for cases caused by disposing underlying object(s)

We shall document this in some way. Either reach consensus when https://github.com/dotnet/dotnet-api-docs/issues/7840 is resolved, via remarks section or via examples.

**Comment by wfurt** [comment]
While some work related to exceptions remains it is tracked by other issues. We reached agreement on strategy and that fulfills spirit to this issue IMHO
