### ISSUE TITLE
Perform assembly signature verification in .Net 6

### ISSUE THREAD

**Issue by UnknownDarkMatter** [dotnet/runtime#82288]
### Description

Hi,

the strong name signature is not verified in .Net 6 
It may be because the assembly is loaded into a full-trust domain (Mycomputer)

In the [following documentation](https://learn.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature#disable-the-strong-name-bypass-feature-for-a-single-application) it is explained how to disable bypass of the signature verification for .Net Framework

Is it because we need to deactivate bypassTrustedAppStrongNames in .Net Core ? How to do that ?

Thanks in advance

### Reproduction Steps

Create a console app in .Net 6 that is signed
Create a class library in .Net 6 that is not signed and use it in the console app
Run the console app

 

### Expected behavior

The console app should say it that the located assembly's manifest definition does not match the assembly reference or some error message

### Actual behavior

The unsigned assembly is loaded and executed

### Configuration

.Net 6, on Windows and Linux

**Comment by teo-tsirpanis** [comment]
Hello, [modern .NET does not validate strong name signatures by design](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named#:~:text=For%20.NET%20Core%20and%20.NET%205%2B%2C%20strong%2Dnamed%20assemblies%20do%20not%20provide%20material%20benefits.%20The%20runtime%20never%20validates%20the%20strong%2Dname%20signature%2C%20nor%20does%20it%20use%20the%20strong%2Dname%20for%20assembly%20binding.).

**Comment by UnknownDarkMatter** [comment]
OK thanks
