### ISSUE TITLE
HttpClient Hangs for Certain GET Requests with HTTP 1.1

### ISSUE THREAD

**Issue by jlynch630** [dotnet/runtime#82327]
### Description

When using HttpClient for a simple `GET https://www.microsoft.com/en-us?redir=true`, it will hang and eventually reach a 100second timeout (or whatever it's set to). The request executes normally from other http clients, e.g. curl. Note that, despite the `redir` parameter, the request returns a normal `200 OK` response. The problem only seems to occur with HTTP 1.1, it works fine when setting the client to use HTTP 2.

### Reproduction Steps

```cs
HttpResponseMessage Message = await new HttpClient().SendAsync(new HttpRequestMessage {
    RequestUri = new Uri("https://www.microsoft.com/en-us?redir=true"),
    Version = new Version(1, 1) // works with new Version(2, 0) instead
});
```

### Expected behavior

I expect that the request completes in a timely fashion

### Actual behavior

HttpClient.Send(Async) hangs until it reaches a Timeout

### Configuration

I'm using .NET `7.0.200-preview.22628.1` on Windows 11 x64 25295.1000, but the problem also happens on MacOS Monterey

**Comment by wfurt** [comment]
You should get packet captures @jlynch630. This clearly seems like something specific to your environment. 
Note that `HttpClient` will prefer IPv6 if it is available.

**Comment by jlynch630** [comment]
I'm inclined to agree, but it is an issue across devices/networks, and works fine from other clients. Here's a packet capture, which seems normal, although I'm not sure how to decrypt SSL traffic coming from `HttpClient`. Here is also a screenshot from an eventsource capture, which seems like it makes it to headers and then stops.
![image](https://user-images.githubusercontent.com/1965320/219891463-f6be68be-876d-4963-991a-e7b5ea1aac5f.png)

![image](https://user-images.githubusercontent.com/1965320/219890962-6d1d4a9a-345b-446d-8a1f-9dd90a6096b5.png)
[httpclientpcap.zip](https://github.com/dotnet/runtime/files/10775101/httpclientpcap.zip)

**Comment by wfurt** [comment]
Yes, the trace looks reasonable. It is more muddy with TLS 1.3 but I suspect that the frame 17 is the actual request, followed by 14s gap and then closure. 

My guess that this is environemtal turned out to be wrong. I could reproduce on my machine. What I see is request that the server never despond to. You can use tool like https://www.telerik.com/fiddler or more crude https://github.com/wfurt/PcapStream

With some little experiments I was able to make it work:
```c#
var request = new HttpRequestMessage {
    RequestUri = new Uri("https://www.microsoft.com/en-us?redir=true"),
    Version = new Version(1, 1) // works with new Version(2, 0) instead
};
request.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.62");

HttpResponseMessage Message = await new HttpClient().SendAsync(request);
Console.WriteLine(Message);
```

It seems like the site is picky about "User-Agent" - if you do not send it it won't give you back content ;(
While the header is not mandatory per HTTP RFC I would not consider it as HttpClient bug.

**Comment by jlynch630** [comment]
Gotcha, okay that makes sense, those other tools add their own User-Agent headers. Thanks for the help!
