### ISSUE TITLE
Casting double to float returns strange number, with difference of  nearly 8 units

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#82402]
### Description

float floatValue = (float)(-221833752.02686611) returns -221833760

### Reproduction Steps

float floatValue = (float)(-221833752.02686611);

### Expected behavior

Truncated value

### Actual behavior

float floatValue = (float)(-221833752.02686611) returns -221833760
float floatValue2 = (float)(-221833752) returns -221833760
float floatValue3 = (float)(221833752) returns  221833760

### Configuration
Visual Studio 2022 Version 17.4.5
.Net 7, c# 11
Windows 11, 64 Bits

### Other information

Label: System.Numerics

**Comment by tannergooding** [comment]
That's expected. `double` has a larger range than `float` and thus can accurately represent more numbers than `float` can. Downcasting can and will often lose precision, just as downcasting from `long` (`System.Int64`) to `int` (`System.Int32`) will.

----------------

Both `double` and `float` are binary-based floating-point numbers. They are represented by a `sign`, `exponent`, and `significand`.

For `double`, this is:
* Sign: 1-bit
* Biased Exponent: 11-bits
* Trailing Significand: 52-bits (the full significand is 53-bits, with the 53rd bit being implicitly determined based on the biased exponent)

For `float`, this is:
* Sign: 1-bit
* Biased Exponent: 8-bits
* Trailing Significand: 23-bits (the full significand is 24-bits, with the 24th bit being implicitly determined based on the biased exponent)

The general algorithm for computing the exact represented value is: `-1^s * b^e * (b^(1-p) * m)`, where:
* `s` is the sign
* `b` is the radix (2 for float/double)
* `e` is the unbiased exponent
* `p` is the number of bits in the full significand
* `m` is the full significand

Thus, `float` can accurately represent integral data up to `2^24`. For `2^24` to `2^25` it can only represent even numbers. For `2^25` to `2^26` it can only represent numbers divisible by 4. For `2^26` to `2^27`, numbers divisible by `8`, and so on.

Inversely, this means that `2^24` to `2^25` cannot represent fractional data. For `2^23` to `2^24` it can only represent multiples of `0.5`. For `2^22` to `2^23` it can only represent multiples of `0.25`, and so on all the way down to `float.Epsilon` being the smallest value that compares greater than `0`.

`double` is similar but with the integral boundary being `2^53`.

----------------

Given that, and that `log2(221833752)` is `27.7`, we cannot accurately represent it as a `float` and thus must round it to the nearest representable result. This is `221833760` because it is divisible by `16` (The `ceil(27.7)` is `28`, then `28 - 24` is `4`, so the representable values are multiples of `2^4`).

This also, by extension means that while every `short/ushort` can be exactly represented as a `float`. Not every `int`/`uint` can and they may introduce "rounding error". Likewise while very `int`/`uint` is exactly represented as a `double`, not every `long`/`ulong` is.

**Comment by Clockwork-Muse** [comment]
Also, `float` is not an integral value type, so why would you expect the cast to truncate?
