### ISSUE TITLE
[API Proposal]: Create FrozenArray

### ISSUE THREAD

**Issue by mungojam** [dotnet/runtime#82552]
### Background and motivation

I see there will currently only be FrozenSet and FrozenDictionary in net 8, which might give me a difficult choice given the style I encourage in our team. 

I don’t actually make use of any of the adders for the Immutable collections, I just use them to enforce a functional style with pure functions etc. So FrozenSet and FrozenDictionary will be very tempting given the performance benefits and perhaps better support for covariance.

However, I’ll then have a mixture of Frozen... and Immutable... types in our code base which feels a bit yukky and will be difficult to communicate. Can we get FrozenArray as well, providing an alternative to ImmutableArray?

### API Proposal

It just needs to be consistent with the other frozen methods and have a FrozenArray.Create method and I'll be happy

### API Usage

Hopefully self explanatory

**Comment by stephentoub** [comment]
The primary benefit to FrozenDictionary/Set as compared to ImmutableDictionary/Set is the implementations don't need to accomodate creating variations of the original, which leads to ImmutableDictionary/Set having relatively slow lookup speeds.  On top of that, because they don't need to accomodate frequent "mutations" (creating a new collection with all the data from the first and then also incorporating the mutation), the FrozenDictionary/Set can take more time during construction to further improve how the data is stored and to compute how lookups should be performed.

Those benefits don't exist for a hypothetical FrozenArray, which would just be ImmutableArray with a different name and less surface area.  I don't see huge benefits in introducing one and creating more choice where there isn't actually a difference in implementation.

Note, too, that these FrozenDictionary/Set types are part of the System.Collections.Immutable.dll/nupkg, because they are logically immutable collections and go together in that regard, they're just optimized for different uses of immutability.

**Comment by mungojam** [comment]
Yeah I can understand that reluctance here and for many people I'm sure it will be fine.

For me though it will grate with me and make it harder to communicate and parse code, but perhaps I need to get creating some analysers and automatic PR checkers to enforce use of types across the code base.

The covariance thing is a real benefit right? Just today I had to .Cast because I couldn't automatically upcast an ImmutableArray (I may have mixed up some terms here)

**Comment by eiriktsarpalis** [comment]
> The covariance thing is a real benefit right?

I don't think it would be possible to offer an experience that is substantially different to what ImmutableArray offers, unless we exposed it as a covariant interface. But there's already a type for that, `IReadOnlyList<T>`, and ImmutableArray/ImmutableList already implement it.
