### ISSUE TITLE
`AssemblyName` lacks override on `GetHashCode` resulting multiple values in `HashSet<AssemblyName>`

### ISSUE THREAD

**Issue by elachlan** [dotnet/runtime#82580]
### Description

If you attempt to use `HashSet<AssemblyName>` and add multiple `AssemblyName` instances from different objects in the same assembly you will get multiple values in the HashSet.

### Reproduction Steps

```csharp
object a = new();
object b = new();
HashSet<AssemblyName> names = new();
names.Add(a.GetType().Assembly.GetName(true));
names.Add(b.GetType().Assembly.GetName(true));
```

### Expected behavior

Only one item should exist in the `HashSet`.

### Actual behavior

Two items exist in the `HashSet`.

### Known Workarounds

Implement your own IComparer and pass it to the HashSet constructor.

**Comment by elachlan** [comment]
This came about from work in Winforms refactoring this code:
https://github.com/dotnet/winforms/blob/972155ddaaf6c0b08636f55163479ef6680ae369/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs#L357-L371

**Comment by elachlan** [comment]
`Assembly` seems to work and it doesn't have an implementation of `GetHashCode`, so maybe its an issue further down the stack in the base `GetHashCode`?

**Comment by MSDN-WhiteKnight** [comment]
I think it's more because Assembly instances are cached in loader context, so calling Type.Assembly multiple times always returns the same object with the same hashcode, but it's not true for AssemblyName. The default hashcode implementation for reference types is tied to reference equality, so different object instances will have different hash codes. Because nothing in docs says that AssemblyName provides value equality, it is probably by design. You need to provide custom comparer yourself if you need value equality.

**Comment by buyaa-n** [comment]
As @MSDN-WhiteKnight mentioned it looks like by design, `AssemblyName` doesn't override `Equals()` nor `GetHashCode()` and `Assembly.GetName(true)` you are using always returns new instance of `AssemblyName` https://github.com/dotnet/runtime/blob/0a15c3b97dabaf94e5d4399aef2fd48c2b3f446a/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L126-L131

And I don't think we will change it. Instead, you could implement [IEqualityComparer](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1?view=net-7.0) to override `AssemblyName.GetHashCode()` and pass it as the constructor argument of your [HashSet<T>(IEqualityComparer<T>)](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.-ctor?view=net-7.0#system-collections-generic-hashset-1-ctor(system-collections-generic-iequalitycomparer((-0))))
