### ISSUE TITLE
What is the C# equivalent code for the Powershell sript to remove user from Adminstrators group?

### ISSUE THREAD

**Issue by viveknuna** [dotnet/runtime#82726]
I have a PowerShell script. It is to remove the user from the Administrators group. It's working fine for local and domain users both.

`Remove-LocalGroupMember -Group "Administrators" -Member "Admin02"`
I want to implement this in C#. I have tried the below code. But it's not working for the domain account.

```
using (PrincipalContext ctx = new PrincipalContext(ContextType.Machine))
{
    UserPrincipal user = UserPrincipal.FindByIdentity(ctx, IdentityType.Name, args[0]);
    GroupPrincipal group = GroupPrincipal.FindByIdentity(ctx, IdentityType.Name, "Administrators");

    if (user != null && group != null)
    {
        try
        {
            if (group.Members.Remove(user))
            {
                Console.WriteLine("User successfully removed from Local Administrators.");
            }
            else
            {
                Console.WriteLine("User is not a Local Administrator1.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("User is not a Local Administrator.");
            Console.WriteLine(ex.ToString());
        }
    }
    else
    {
        Console.WriteLine("User was not found.");
    }
}
```
Its printing User was not found.

I have tried with ContextType.Domain as well.

target .net framework 4.7.2.

It will be great, If there is a solution which works for non english systems as well.

I have raised the similar question here as well.

@ericstj 

https://stackoverflow.com/questions/75559291/how-to-remove-domain-user-from-administrators-group-using-c

**Comment by viveknuna** [comment]
This is the area.


area-System.DirectoryServices | @ericstj | @dotnet/area-system-directoryservices | Consultants: @BRDPM @grubioe @jay98014

**Comment by omariom** [comment]
StackOverflow is a good place for such questions. 
But **chatGPT**  is even better.

Here is its unedited answer.

> The reason you are not able to find the user when using PrincipalContext(ContextType.Machine) or PrincipalContext(ContextType.Domain) is because these contexts only search for users and groups on the local machine or domain, respectively. They do not search for users in the entire domain.
> 
> To remove a user from the Administrators group on a local machine or domain, you need to use the DirectoryEntry class in C#. Here is an example code that removes a user from the Administrators group on a local machine:
> 

```
using System.DirectoryServices;

string userName = args[0];
string machineName = Environment.MachineName;

DirectoryEntry localMachine = new DirectoryEntry("WinNT://" + machineName);
DirectoryEntry admGroup = localMachine.Children.Find("Administrators", "group");

if (admGroup != null)
{
    DirectoryEntry user = localMachine.Children.Find(userName, "user");
    if (user != null)
    {
        try
        {
            admGroup.Invoke("Remove", new object[] { user.Path });
            Console.WriteLine("User successfully removed from Local Administrators.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("Failed to remove user from Local Administrators.");
            Console.WriteLine(ex.ToString());
        }
    }
    else
    {
        Console.WriteLine("User was not found.");
    }
}
else
{
    Console.WriteLine("Administrators group was not found.");
}
```

> This code uses DirectoryEntry to connect to the local machine and find the Administrators group. It then finds the user and removes it from the group using the Invoke method.
> 
> To make this code work for domain users, you can modify the DirectoryEntry constructor to point to the domain instead of the local machine. Here is an example:

```
using System.DirectoryServices;

string userName = args[0];
string domainName = "mydomain.com";

DirectoryEntry domain = new DirectoryEntry("LDAP://" + domainName);
DirectoryEntry admGroup = domain.Children.Find("CN=Administrators,CN=Builtin," + domain.Path.Substring(domain.Path.IndexOf("DC=")), "group");

if (admGroup != null)
{
    DirectoryEntry user = domain.Children.Find("CN=" + userName, "user");
    if (user != null)
    {
        try
        {
            admGroup.Invoke("Remove", new object[] { user.Path });
            Console.WriteLine("User successfully removed from Domain Administrators.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("Failed to remove user from Domain Administrators.");
            Console.WriteLine(ex.ToString());
        }
    }
    else
    {
        Console.WriteLine("User was not found.");
    }
}
else
{
    Console.WriteLine("Administrators group was not found.");
}
```

> This code connects to the domain using LDAP://mydomain.com, and finds the Administrators group using the CN=Builtin path. It then finds the user using the CN= syntax and removes it from the group using the Invoke method.
> 
> Regarding non-English systems, the DirectoryEntry class should work on any system regardless of language, as long as the object names (such as "Administrators") are the same. However, if you are not sure about the object names, you can use the System.Globalization.CultureInfo class to get the localized names of objects. For example:

```
using System.DirectoryServices;
using System.Globalization;

string groupName = "Administrators";
string localizedGroupName = new CultureInfo("en-US").TextInfo.ToTitleCase(groupName.ToLower());

DirectoryEntry admGroup = localMachine.Children.Find(localizedGroupName, "group");
```

> This code uses the CultureInfo class to get the localized name of the Administrators

**Comment by viveknuna** [comment]
@omariom i don't think that your solution is going to work.

And also what if there are 100 domains and you have only user name.

**Comment by ericstj** [comment]
I'm sorry you are facing difficulty using DirectoryServices.  I'll start by saying that these types of questions are better suited for StackOverflow or Microsoft Support.  Issues in this repository should be used to report issues with .NET - specifically .NET Core or .NET 5 and later.

That said, I happened to take a look at how that powershell cmdlet was implemented and you may find this helpful:
https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/RemoveLocalGroupMemberCommand.cs#L248-L263
It seems this eventually calls the Win32 [LookupAccountName method](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupaccountnamew)
https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Sam.cs#L2741-L2805

> The LookupAccountName function accepts the name of a system and an account as input. It retrieves a [security identifier](https://learn.microsoft.com/en-us/windows/desktop/SecGloss/s-gly) (SID) for the account and the name of the domain on which the account was found.

Since this issue is not reporting a problem with DirectoryServices on .NET I'm going to go ahead and close it.  I hope this was helpful.

**Comment by viveknuna** [comment]
@ericstj thank you for responding, but my problem is not related to PowerShell. I have mentioned just to show that it works. But C# code is not working as expected.

Remove method is not able to remove the domain user account from administrators group. So it's something wrong with my code or Remove method has this limitation.

**Comment by ericstj** [comment]
I gave an example for how the PowerShell script implements the same functionality.  It looks up the SID from the non-domain-qualified name then creates a principal from that.  Your solution might need a similar step.

> C# code is not working as expected.

I am not sure it's expected to work: you mentioned it never worked with a domain user.

> Remove method is not able to remove the domain user account from administrators group. So it's something wrong with my code or Remove method has this limitation.
> Its printing User was not found.

You mentioned your sample was printing `User was not found` so that indicates to me that you never reached a `Remove` call in the domain user case.  The sample failed in user lookup.  It's this part: `UserPrincipal.FindByIdentity(ctx, IdentityType.Name, args[0]);`.  As was mentioned on StackOverflow post you linked (which seems to have a good suggestion), you may need to consider the domain context when searching for the user.  I'm not certain as I've never tried to implement the exact task you're trying to accomplish.  I did see how PowerShell did it, so I tried to share that example.

For an explanation of available support options, please visit [Support for Business and Developers](https://support.microsoft.com/hub/4343728/support-for-business). For community support options, see the [Community](https://dotnet.microsoft.com/en-us/platform/community) page.
