### ISSUE TITLE
`System.Net.Http.HttpClient` empty `Content.Headers.ContentLength` when using `AutomaticDecompression`

### ISSUE THREAD

**Issue by CarloToso** [dotnet/runtime#82737]
### Description

When connecting to [example.com](http://example.com/) with `AutomaticDecompression`, Content.Headers.ContentLength` is null
Described better in: https://github.com/PowerShell/PowerShell/issues/19230

### Reproduction Steps

Tested in PowerShell:
```ps1
$handler = [System.Net.Http.HttpClientHandler]::New()
$handler.AutomaticDecompression = "All" #<--- BUG ORIGIN
$client = [System.Net.Http.HttpClient]::new($handler)
$message = [System.Net.Http.HttpRequestMessage]::New('HEAD', "http://example.com/")
Write-Output "first: $($client.sendAsync($message).Result.Content.Headers.ContentLength)" #--> $null or rarely 1258

$handler = [System.Net.Http.HttpClientHandler]::New()
$client = [System.Net.Http.HttpClient]::new($handler)
$message = [System.Net.Http.HttpRequestMessage]::New('HEAD', "http://example.com/")
Write-Output "second: $($client.sendAsync($message).Result.Content.Headers.ContentLength)" #--> 648 or 1258
```

### Expected behavior

Result.Content.Headers.ContentLength is not null

### Actual behavior

Result.Content.Headers.ContentLength is null

### Configuration

Tested in PowerShell 5 - 7.33 - 7.4 preview1 - latest
OS Windows10 x64

### Other information

The content-encoding of the website is GZip, it might be related

<html><body>

Type | Error 
-- | -- 
All | ***Yes***
Brotli | No
Deflate | No
GZip | ***Yes*** <-- BUG ORIGIN
None | No

</body>
</html>

**Comment by stephentoub** [comment]
This is by design.  The Content-Length that gets sent by the server is the encoded length.  By asking for it to be automatically decompressed, you're asking for the handler to give you back the decoded bytes, which are no longer related in a meaningful way to the Content-Length.  Thus the handler removes the then erroneous Content-Length:
https://github.com/dotnet/runtime/blob/eccbe90f0f3840fa0316adcce7aee38ab1016180/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L118-L122

**Comment by CarloToso** [comment]
Thanks

**Comment by MihaZupan** [comment]
Beyond just the decompression, the assumption that a response will even contain a content-length header is not correct (it may be chunked transfer encoding, or connection close for example).
E.g. https://github.com/PowerShell/PowerShell/blob/0ba89599b234acac4b3b2ccce64a6407b4c30326/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L558

The only way to know the actual length of the content is to look for the header, and otherwise read the whole response content.
