### ISSUE TITLE
.NET Core Path.GetFileName inconsistent with full framework

### ISSUE THREAD

**Issue by ScottKane** [dotnet/runtime#82760]
```cs
using System;
using System.IO;
using System.Linq;
					
public class Program
{
	public static void Main()
	{
		var files = new string[]
		{
			"D:\\Some\\Path\\To\\File1.svg",
			"D:\\Some\\Path\\To\\File2.svg",
		};
		files = files.Select(d => Path.GetFileName(d)).ToArray();
		
		foreach (var file in files)
			Console.WriteLine(file);
	}
}
```

Running the above sample in full framework produces:
```
File1.svg
File2.svg
```

Runnning the same in Core produces:
```
D:\Some\Path\To\File1.svg
D:\Some\Path\To\File2.svg
```

Full Framework example: https://dotnetfiddle.net/ydNqcD
Core example: https://dotnetfiddle.net/x08h43

Guessing the output should be the same and that something will need to change.

**Comment by huoyaoyuan** [comment]
On Windows it outputs `File1.svg` and `File2.svg`.
Behavior of `Path.GetFileName` depends on the operating system. It matches the current `DirectorySeparator` and `AltDirectorySeparatorChar`. On Windows both `/` and `\` are recognized, while on Unix only `/` is recognized.

**Comment by stephentoub** [comment]
@huoyaoyuan is correct.  Your repro produces:
```
File1.svg
File2.svg
```
on both .NET Framework and .NET Core _on Windows_.  On Linux .NET Core produces:
```
D:\Some\Path\To\File1.svg
D:\Some\Path\To\File2.svg
```
because `\` is a valid character in a file name on Linux; it's not a directory separator.

And your `Core example: https://dotnetfiddle.net/x08h43` is running on Linux; you can see that if you update the repro to include `Console.WriteLine(OperatingSystem.IsLinux())`; it'll print True.  Change it to IsWindows(), and it'll print False.
