### ISSUE TITLE
[API Proposal]: IRandom interface (which System.Random and Cryptography.RandomNumberGenerator implement)

### ISSUE THREAD

**Issue by BenMakesGames** [dotnet/runtime#82799]
### Background and motivation

Related tickets: https://github.com/dotnet/runtime/issues/28229 and https://github.com/dotnet/runtime/issues/73567 (an earlier proposal of mine); my interest was renewed following a recent Nick Chapsas video on new RNG features coming in .NET 8: https://www.youtube.com/watch?v=zCF-CUuVzGI

`System.Random` and `Cryptography.RandomNumberGenerator` conceptually do the same thing: generate random numbers. However, because these implementations are unrelated, neither benefits from additions to the other; work is being duplicated, and developers have to learn two APIs.

It feels like like `System.Random` and `Cryptography.RandomNumberGenerator` are mixing concerns: 1. the concern of generating random bytes; 2. the concern of what to _do_ with those random bytes (e.g., compose them into an integer, shuffle an array, etc).

Third-party libraries also suffer. For example, Unity has its own `Random` class, which offers methods like `insideUnitCircle` (https://docs.unity3d.com/ScriptReference/Random-insideUnitCircle.html), however the authors of this class had to re-implement features of `System.Random` (including a static, shared instance, before .NET offered this), and came up with some new names for methods which already exist on `System.Random`. Unity's Random implementation will not gain any additions made to `System.Random` in .NET 8, or later, and this is a _third_ API developers must learn.

I believe this can all be tidied up.

### API Proposal

To solve the issues above, I propose a single interface - `IRandom` - which requires a single method: `NextBytes`. `System.Random` and `Cryptography.RandomNumberGenerator` would implement this method; the other methods we're familiar with from these classes (`Shuffle`, `NextDouble`, etc) would be removed, now provided by extension methods to the `IRandom` interface.

```csharp
namespace System;

public interface IRandom
{
    static abstract IRandom Shared { get; } // not sure if this should really be part of the interface...??

    Span<byte> NextBytes(int count);
}

// whether these are on a separate extension class, or live inside IRandom, I don't have strong feelings about:
public static class RandomExtensions
{
    public static int NextInt(this IRandom random, int min, int exclusiveMax)
    {
        var bytes = random.NextBytes(4);
        var value = BitConverter.ToInt32(bytes);
        return Math.Abs(value % (exclusiveMax - min)) + min;
    }

    public static double NextDouble(this IRandom random)
    {
        // copied from existing System.Random:
        var value = BitConverter.ToUInt64(random.NextBytes(8));
        return (value >> 11) * (1.0 / (1ul << 53));
    }

    // etc...
}
```

`System.Random` would be rewritten:

```csharp
namespace System;

public class Random: IRandom
{
    public static IRandom Shared => new Random();

    public Span<byte> NextBytes(int count)
    {
        // however System.Random currently generates bytes

        return bytes;
    }
}
```

`Cryptography.RandomNumberGenerator` would also be rewritten, generating its bytes using `BCryptGenRandom`, as before. For backwards compatibility, its various static methods (`GetInt32`, etc) would be rewritten as pass-thrus to the `IRandom` extensions (and perhaps marked `[Obsolete]`?)

### API Usage

From a developer's point of view, `System.Random` and `Cryptography.RandomNumberGenerator` would each gain (most of) the methods of the other. Existing code continues to work as always.

However, package writers can now write extensions on `IRandom` to buff all implementations, and write new implementations of `IRandom` without giving up the BCL RNG methods they know and love.

---

Example third-party `IRandom` extensions:

```csharp
public static class MyWeirdRandomExtensions
{
    // using .NET 8's new GetItems<T>
    public static List<T> GetEnums<T>(this IRandom random, int count) where T: Enum
        => random.GetItems(Enum.GetValues(typeof(T)).Cast<T>().ToList(), count);

    public static int RollDice(this IRandom random, int numberOfDice, int numberOfSides)
    {
        // ...
    }
}
```

Example third-party implementation of `IRandom`:

```csharp
// `BadRandom` loops through the same sequence of bytes over and over again. The exact values used are taken from the
// NES game Final Fantasy 1, which used these values to determine when "random" enemy encounters should occur.
//
// Other possible implementations that come to mind: wrappers for Noise/Perlin Noise functions (e.g., Squirrel3).
public sealed class BadRandom: IRandom
{
    public static IRandom Shared { get; } = new BadRandom();

    private int _index;

    public Span<byte> NextBytes(int count)
    {
        if (_index + count < bytes.Length)
        {
            var result = bytes.AsSpan().Slice(_index, count);
            _index = (_index + count) % bytes.Length;
            return result;
        }
        else
        {
            var result = new byte[count];
            var offset = 0;
            while (offset < count)
            {
                var length = Math.Min(count - offset, bytes.Length - _index);
                bytes.AsSpan().Slice(_index, length).CopyTo(result.AsSpan().Slice(offset, length));
                offset += length;
                _index = (_index + length) % bytes.Length;
            }

            return result;
        }
    }

    public BadRandom(int seed = 0)
    {
        _index = seed % bytes.Length;
    }

    // from https://tasvideos.org/GameResources/NES/FinalFantasy1#EncounterAlgorithms
    private static readonly byte[] bytes =
    {
        0x1F, 0xA6, 0xDE, 0xBA, 0xCC, 0x12, 0x7D, 0x74, 0x1B, 0xF3, 0xB4, 0x88, 0xF8, 0x52, 0xF4, 0x07,
        0x90, 0xAB, 0xB3, 0xBD, 0xAA, 0x55, 0x28, 0xBC, 0x8A, 0x6D, 0x0E, 0xC4, 0x83, 0xA9, 0x3B, 0x76,
        0x20, 0x7C, 0x09, 0x92, 0xFD, 0x4A, 0xA8, 0xF0, 0x61, 0xE3, 0xF2, 0x69, 0x6C, 0xBB, 0x38, 0xC3,
        0xAE, 0xB7, 0x43, 0x84, 0x78, 0x23, 0x7B, 0x9B, 0x2D, 0xDB, 0x3E, 0x91, 0xCF, 0x02, 0x2A, 0xB6,
        0x86, 0xEE, 0x9C, 0x8E, 0xB8, 0x6F, 0x1A, 0x57, 0x05, 0xE9, 0x73, 0x31, 0xD2, 0xD9, 0x1D, 0xFB,
        0x94, 0x9D, 0xB1, 0x0A, 0x3A, 0x11, 0x5A, 0x47, 0x95, 0x2C, 0x44, 0xE0, 0x6A, 0x8C, 0x5B, 0x7A,
        0xA7, 0x5D, 0x36, 0x70, 0xE5, 0xC7, 0x49, 0xDC, 0x68, 0x97, 0xD8, 0x66, 0xA3, 0x0F, 0xB0, 0x9F,
        0x03, 0xD6, 0x77, 0x16, 0x13, 0x30, 0x25, 0x3C, 0x10, 0x17, 0xAD, 0x98, 0x6B, 0x2F, 0xD7, 0xA1,
        0xFF, 0xA4, 0xEB, 0x51, 0xFE, 0x27, 0x8D, 0x93, 0xD5, 0x3D, 0xF6, 0x08, 0x75, 0xE1, 0xA5, 0x46,
        0x63, 0xF5, 0x4D, 0xDA, 0x32, 0xAF, 0x40, 0x37, 0xD3, 0xC0, 0x89, 0x67, 0x06, 0x21, 0x6E, 0x81,
        0xB5, 0xA0, 0x4F, 0x0C, 0x2E, 0xE7, 0x1C, 0x58, 0x85, 0xE8, 0x59, 0xCE, 0x35, 0xCB, 0x1E, 0xC6,
        0x2B, 0x9A, 0xE6, 0xDD, 0xF1, 0xEC, 0x96, 0xCA, 0xAC, 0x00, 0x50, 0xC9, 0x4C, 0xFC, 0x14, 0x7E,
        0x56, 0x80, 0xD0, 0x79, 0xBF, 0x29, 0x87, 0x48, 0x24, 0x19, 0xC5, 0x22, 0x71, 0x7F, 0x72, 0x0D,
        0xCD, 0x8F, 0xBE, 0x3F, 0x9E, 0x34, 0xED, 0x53, 0x54, 0x04, 0x62, 0xA2, 0xC2, 0x41, 0x5E, 0x82,
        0x4B, 0x26, 0x5C, 0x42, 0x65, 0x99, 0x4E, 0x60, 0x8B, 0xF7, 0x0B, 0x33, 0xDF, 0xD1, 0x64, 0xC8,
        0xC1, 0x01, 0xEF, 0xF9, 0xFA, 0xE4, 0x5F, 0x18, 0xB9, 0xB2, 0x39, 0xD4, 0x15, 0xE2, 0xEA, 0x45
    };
}
```

**Comment by vcsjones** [comment]
> IRandom - which requires a single method: NextBytes. System.Random and Cryptography.RandomNumberGenerator 

Generally, I think the opinion would remain that from #73567:

> The CSPRNG (System.Security.Cryptography.RandomNumberGenerator) has moved to static methods to indicate that deriving the type or otherwise substituting it isn't generally a good idea; and no one who needs to use the CSPRNG would benefit from an interface here. So RandomNumberGenerator should be left out.

So your proposal would at least only encompass `Random`.

`RandomNumberGenerator` wants to be used statically. `Random` does not. Nor would I want to promote instance methods on `RandomNumberGenerator` or the use of them.

Folks are always free to build their own abstractions on top of these concepts as they need for their own purposes.

> ` return Math.Abs(value % (exclusiveMax - min)) + min;`

This has bias in it. It might be fine for a non-cryptographic reason, but the CSPRNG implementation has a try-discard pattern. The random does not. You can't build `GetInt32` the same for both `RandomNumberGenerator` and `Random`. The former wants to avoid bias. The latter wants to go fast.

**Comment by BenMakesGames** [comment]
> `RandomNumberGenerator` wants to be used statically. `Random` does not. Nor would I want to promote instance methods on `RandomNumberGenerator` or the use of them.

* `RandomNumberGenerator` currently has a `protected` constructor; `RandomNumberGeneratorImplementation`, a `private` one. I did not mean to suggesting changing that.
* `Random` sometimes wants to be accessed statically (`Random.Shared`), but that feels besides the point.

**Comment by bartonjs** [comment]
We've been moving away from instances for the CSPRNG, just using the static methods.  I don't have any particular taste for making them more instancy again (which an interface would do).

One could derive System.Random to make a PRNG instance that calls into the CSPRNG... and at that time an interface isn't required :smile:.

FWIW: The sniff test for interfaces in the shared runtime is that they should end in "able" (IEnumerable, IDisposable).  If they don't end in "able" then the design guidelines are almost certainly going to say that you instead want an abstract class.  It's not a 100% rule, but it's the quick one.

**Comment by koszeggy** [comment]
Actually there is no need for a new interface as the `Random` class can be derived and all of the important `Next*` methods are virtual. So such [extension methods](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/master/KGySoft.CoreLibraries/CoreLibraries/_Extensions/RandomExtensions.cs) can be defined simply for the regular `Random` class. Thus a derived class that uses `RandomNumberGenerator` internally will be automatically compatible with the extensions as illustrated nicely [in my case](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Security_Cryptography_SecureRandom.htm) at the **Extension Methods** section.

**Comment by BenMakesGames** [comment]
> Actually there is no need for a new interface [...]

well, I can't argue against "there is no need" :P there's no _need_ for most things; C# could toss out `IEnumerable`, and still have a usable language.

the purpose of this issue is to create a clearer/easier path for devs working with RNGs by expressing sources of random numbers as something more fundamental - as fundamental as "I like to iterate over stuff, sometimes" - and not just a feature that a couple classes happen to implement.

the current design of RNGs in C# _discourages_ re-use through its obtuseness; one must dig into the source code of `System.Random` to understand how to even begin to extend it. by contrast, a single-method interface is immediately understandable - as intuitive as `IDisposable` - and like `IDisposable` or `IEnumerable`, an implementer of `IRandom` (name pending, I suppose) can be confident that their implementation will receive all the benefits provided by other libraries, or possibly even the language itself.

**Comment by bartonjs** [comment]
While it may be true that someone who would use a DRNG (Deterministic Random Number Generator) may be willing to accept a CSPRNG, it's extremely rare that someone who wants a CSPRNG would ever want to accept a DRNG.

The CSPRNG (System.Security.Cryptography.RandomNumberGenerator) has a very different shape, and now actively discourages instantiation, to prevent the extraordinarily bad security bugs that would arise from getting a DRNG instead.

In the System.* namespaces we adhere to the guidelines published in the Framework Design Guidelines book (or, more accurately, the published book contains our design guidelines, since we inform it, not the other way around).  That includes

* DO favor defining classes over interfaces.
* DO use abstract classes instead of interfaces to decouple the contract from implementations.
* DO define an interface if you need to provide a polymorphic hierarchy of value types.
* CONSIDER defining interfaces to achieve a similar effect to that of multiple inheritance.

System.Random is a class, so the third bullet doesn't apply.  It's not abstract, but it does have virtual members, and the virtualness allows different algorithms to be used.  So the second bullet says no interface.  The fourth bullet is where the "-able" sniff test comes into play, as generally the reason for multiple inheritance is to express capability.  And the first bullet basically is "don't make an interface unless you need to".  All together, the conclusion is that System.IRandom is contrary to our design guidelines.

**Comment by BenMakesGames** [comment]
* my understanding is that `RandomNumberGenerator` is both a CSPRNG and a DRNG... but I think this is an implementation detail that is unrelated to the proposal. (am I missing something?)
* the proposal does not say anything about the instantiability of `RandomNumberGenerator`. whatever access modifier its constructor has now, I'm sure is fine.

if you've got the time and will, I'm curious to hear about the thinking behind bullet point 2. what are the advantages to using abstract classes instead of interfaces; what are the cons to using interfaces instead of abstract classes; and how do interfaces like ICollection, IDisposable, IEquatable, INumber, ILogger, etc fit in here?

**Comment by bartonjs** [comment]
> my understanding is that RandomNumberGenerator is both a CSPRNG and a DRNG

https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator

While most (all?) cryptographic random number generation algorithms are procedural (and therefore are deterministic if you know everything about them), they all involve hidden entropy.  An outside person being able to predict the next byte (at better than 1/256 odds) utterly destroys the security of any algorithm using it.

* Launch a VM
* Have your process warmed up
* Snapshot the VM
* Run twenty thousand clones of it
* Have the next resumed line of your program be requesting 8 bytes from the CSPRNG

On Windows (which I know to specifically defend against VM cloning / VM rollback), there's only a 0.000000001% chance that any two of those VMs will have generated the same 8 byte sequence.  (For a 50% chance of there being collision anywhere across all of the clones, you'd need 5,056,937,541 clones)

For C's srand/rand(), or .NET's `new Random(seed)`, or .NET's `new Random()` or `Random.Shared` every single clone will produce the same 8 byte sequence.  That's because these are deterministic RNGs, where the next output (for the underlying algorithms) is determined solely by the seed (or implicit seed) and the number of bytes requested thus far.

> since System.Random is already well-suited to extension, do you have any thoughts, or can hazard any guess, as to why RandomNumberGenerator does not extend System.Random?

For one, to explicitly indicate that they're not interchangeable.  For two, System.Random's abstraction is fundamentally down to a float in the range `[0, 1)`, like Java's; the CSPRNG is in bytes.  Until .NET Core 3.0 the CSPRNG was only about bytes, and then we started adding some other interactions because we found people were writing RNG-based security critical algorithms incorrectly.  (For example, selecting from a list at random... `list[randomByte % list.Length]` does not have a uniform selection rate).

> what are the advantages to defining abstract classes instead of interfaces

If your breaking change tolerance is as strict as it is for the System.* namespaces, interfaces can't meaningfully evolve new functionality.  For example, ICryptoTransform was mistakenly created as an interface... but since that interface predated Span and ReadOnlySpan those types can't be used with it. (Default Interface Methods /might/ help here, some, but we haven't worked out all the corner cases yet)

> how do interfaces like ICollection, IDisposable, IEquatable, INumber, ILogger, etc fit in here?

IEquatable and INumber are designed to be implemented by value types, so they meet criteria 3.

IDisposable and IEquatable are capability descriptions that apply in the "multiple inheritance" criteria 4.

ICollection and friends are partially criteria 4; though I'd argue they were a mistake from before we learned when to not use interfaces.

ILogger is not part of System.*.  My belief is that had it been subject to the oversight of the .NET API Review process it would not have been an interface.

> the proposal does not say anything about the instantiability of RandomNumberGenerator. (whatever access modifier its constructor has now I'm sure is fine.)

It's not supposed to be instantiated, but used in a static manner (e.g. `byte[] bytes = RandomNumberGenerator.GetBytes(8);`).  The fact it has a constructor and any instance methods at all (and isn't declared as a `static class`) is viewed by the current security team as a historical mistake.

**Comment by BenMakesGames** [comment]
I think we're getting a little lost in the weeds here.

I am curious to ask "what is the definition of a random number generator?"

to get to that answer, I might ask some questions of what I expect an RNG to do. for example, should an RNG be able to...

1. generate random bytes?
2. generate integers of whatever width I like?
   * just signed ones, or also unsigned ones?
3. generate random strings from a given whitelist of characters?
4. pull random items from a list?
5. shuffle lists?

(sorted, roughly, from closest to the metal, to furthest.)

based on the methods made available by `Random` and `RandomNumberGenerator`, it feels as though they do not agree on the definition of an RNG, and have been developed in isolation of one another (whether or not that's true).

consequences of not having an agreed-upon definition of an RNG:

1. `Random`, `RandomNumberGenerator`, Unity's `Random`, Perlin Noise methods online, etc, all offer different subsets of functionality; different APIs
2. when switching RNGs, devs must learn a different API, and/or must fill in the gaps with hand-rolled methods
3. development work is duplicated in the C# ecosystem as a whole, and within the CLR, itself

I understand we can write wrappers ourselves to unify the APIs, but, again, that excuse can be used to hand-wave anything. it's nice that in modern languages, I don't have to write, or find, enumerators myself; it'd be nice if C# could also provide a standard way to generate random numbers, to reduce learning curves, and reduce duplication of effort.

a list of four bullet points from a book does not propose a solution to these problem.

I propose that the definition of an RNG is only to generate random bytes. this is a useful definition, because:

1. every other function can be derived from it
2. we can use C# features (an interface or abstract class, and many extension methods) to enable easy sharing of those derived functions across any number of byte-generators, and easy sharing of byte-generators among those functions

(for maximum purity, I suppose you could say an RNG should generate random _bits_, but bytes are more convenient to work with.)

**Comment by koszeggy** [comment]
> > Actually there is no need for a new interface [...]
>
> well, I can't argue against "there is no need" :P there's no _need_ for most things: C# could toss out `IEnumerable`, and still have a usable language.

No need to be cynical, I didn't mean to make you upset. Maybe you just misunderstood my point so let me be more precise: there is no need for a new interface _to make a secure random implementation work in extension methods the same way as the regular `Random` class_. As I demonstrated in my comment, a derived `Random` class solves this in a compatible way. Introducing a new `IRandom` interface would not make the already existing `this Random` extensions work for `this IRandom`, which creates a confusion: should all existing libraries replace or duplicate the extensions to make them work for a new `IRandom` interface? 

And tossing out `IEnumerable` would be a huge breaking change. As I tried to emphasize compatibility in my answer I don't even get how such an argument is relevant here.

Btw. I would basically agree that interface abstractions are generally better than classes with virtual members. But this design choice should've been emerged before releasing C# 1.0 (same for streams, resource sets and a few other classes). Due to compatibility restrictions late abstractions are often far from perfect, see the inheritance of `IReadOnlyCollection<T>` and its friends. But in that case the cost of such imperfections were undoubtedly compensated by the added value. I simply don't see such a great benefit here, that's all.

**Comment by atomknack** [comment]
We need at least some kind of common "interface" between randoms, as source of "randomness" in common methods. 
If all of current Net random generators were childs of some common public class that implements random source it would, probably, be fine for new code.
Also public signature probably should be in form of **void** `NextBytes(Span<byte> buffer)`, so there is no additional allocations, and Random already have it in that form.
