### ISSUE TITLE
[browser][build][libraries] Properties are not propagated from nested build upwards

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#82819]
Found in https://github.com/dotnet/runtime/pull/82619.

The test `InvariantGlobalizationFalse` from `src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj` needs Turkish locale loaded, in order to pass. By default, we are loading only small shard connected with the environment's locale, in the CI tests it's EFIGS that does not contain Turkish. We expect WASM users to indicate they would like to have bigger download size by setting WasmIncludeFullIcuData flag. The test mentioned above requires such a flag to load full ICU (that contains Turkish).

Setting the flag in `eng/testing/tests.browser.targets` has the proper effect and the value is passed correctly to `WasmApp.targets` where the decision about icu mode is made.
However, setting the flag directly in the test project: `System.Runtime.TrimmingTests.proj` or in `eng\testing\linker\trimmingTests.props` does not have the same effect because they do not belong to the same build process.

It would be helpful to have an option to set the propertys directly in the test project.

Connected comment: https://github.com/dotnet/runtime/pull/82748#discussion_r1121363410

**Comment by radical** [comment]
The problem seems to be that the nested publish does not see the property being set in the test project. This could be because of how the project is setting the property, because for the nested build the project gets evaluated again so if a property was set in a target before then that would not show up in this nested build.

This will automatically go away once https://github.com/dotnet/runtime/issues/83108 is fixed, because it would remove the nested publish.

Closing in favor of https://github.com/dotnet/runtime/issues/83108 .
