### ISSUE TITLE
CodeGen should be updated to support the FMA instruction set

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#8289]
**Rationale**
Performing a multiplication followed by an add is a frequent operation in code (`d = (a * b) + c`) and modern processors provide instructions to help perform this operation in a fast/efficient manner.

**Proposal**

The runtime should be updated to recognize the `d = (a * b) + c` pattern and emit FMA instructions in those scenarios.

This pattern should be handled for both scalar and vector operations (float, double, Vector<float>, Vector<double>, Vector2, Vector3, and Vector4).

**Other Thoughts**
The runtime already has support for the AVX instruction set and the VEX encoding which should make it significantly easier to support for the FMA instructions.

An explicit API (`Math.MultiplyAdd`, or something similar) could also be provided so users can explicitly opt into the behavior.

category:cq
theme:intrinsics
skill-level:intermediate
cost:medium

**Comment by CarolEidt** [comment]
@tannergooding - the runtime would require some kind of knob to enable the JIT to optimize these kinds of sequences. Given that, and the fact that fused multiply add intrinsics are supported on both x86/x64 and Arm64, I'd propose that we close this issue since it is a subset of #12753. Any objection?

**Comment by tannergooding** [comment]
Sounds reasonable to me!
