### ISSUE TITLE
Bug in Configuration Binder 7.0.3

### ISSUE THREAD

**Issue by xottal** [dotnet/runtime#82998]
### Description

Problem with binding TraceSwitch class from .json. The problem occurs only using Microsoft.Extensions.Configuration.Binder 7.0.3 or later. Using 7.0.2 and earlier don't have this problem.

### Reproduction Steps

Program.cs
```c#
Console.WriteLine("Reading from appsettings.json in {0}", arg0: Directory.GetCurrentDirectory());
ConfigurationBuilder builder = new();
builder.SetBasePath(Directory.GetCurrentDirectory());

builder.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
IConfigurationRoot configuration = builder.Build();

TraceSwitch ts = new(displayName: "TraceSwitch", description: "This switch is set via a JSON config.");

ConfigurationBinder.Bind(configuration, "TraceSwitch", ts);
```

appsettings.json
```json
{
    "TraceSwitch": {
        "Level": "Info"
    }
}
```

### Expected behavior

Load TraceSwitch Level value

### Actual behavior

Exception
```
Exception has occurred: CLR/System.Reflection.TargetInvocationException
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll: 'Exception has been thrown by the target of an invocation.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ArgumentException : Must specify valid information for parsing in the string. Arg_ParamName_Name
   at System.Enum.TryParse[TEnum](ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.TryParse[TEnum](String value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.Parse[TEnum](String value, Boolean ignoreCase)
   at System.Diagnostics.TraceSwitch.OnValueChanged()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Configuration

Windows 10 x64
.NET 7.0
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>Debug_Trace</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
  </ItemGroup>

</Project>
```

**Comment by tarekgh** [comment]
@xottal thanks for your report. The binding logic is working as expected. I couldn't reproduce getting the exception you are getting but I can see the value of the `TraceSwitch.Level` is initialized with `Off` value instead of `Info` value. During the binding, it is initialized correctly from the configuration to `Info` but it got overridden to `Off` again when we initialize the `TraceSwitch.Value` property. Here are some answers for some raised question:

> Why this worked in Configuration Binder `7.0.0`, `7.0.1`. and `7.0.2`

We had a bug we fixed on `7.0.3`. The issue was not initializing the properties inside the object when this property doesn't have listed item in the configuration. This is important because some classes are designed to initialize some internal stuff when calling the property setter. Skipping the setters of such properties was causing injurious behavior.
This fix exposed a problem in the `TraceSwitch` class. This class maintains the `level` with matching field called `_switchSettings`. Also, this class is subclassing `Switch` class which maintain the field `_switchValueString`. The `_switchSettings` numeric value is supposed to match the `_switchValueString` string value. But unfortunately, this is not happening and depends on setting the properties in specific order. This is what is causing the issue because the binder gets the property order from the reflection and then calls `Level` and then later will call `Value` properties. This causes resetting the `Level` value again when setting `Value` property. 

> Does it work on .NET 6.0?

Yes, it worked because in .NET 6.0 the `Switch` class has the [`Value` property](https://github.com/dotnet/runtime/blob/19fde2f5b9dd7c8b5f37e9f02688ff9b708b24b5/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs#L171) as a protected property. But in .NET 7.0 the [`Value` property](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs#L173) is changed to be a public property. The binder only sets the public properties which caused to start setting the `Value` property in .NET 7.0.

> What is the workaround to use when using a configuration for the `TraceSwitch` class?

try to explicitly set the `Level and `Value` together to ensure getting the expected result. 

```json

  "TraceSwitch": {
    "Value":  "3",
    "Level": "Info"
  },

```

Please let me know if this works for you.

**Comment by xottal** [comment]
Thanks
Your advice works.
Also for me works just setting Value
```json
  "TraceSwitch": {
    "Value":  "3",
  }
```

**Comment by tarekgh** [comment]
> Also, for me works just setting Value

I proposed to set both in the configuration to make it work on .NET 7.0 and .NET 6.0 too.
