### ISSUE TITLE
Port 'Restrict named mutex files permissions' pull to current stable release

### ISSUE THREAD

**Issue by MrPippin66** [dotnet/runtime#83133]
Can https://github.com/dotnet/runtime/pull/78106 be ported to the current stable release? Though this is a minor security issue, it's not one easily managed on host systems, since if /tmp is volatile, this will re-appear after reboots.

Having to wait for the 8.0 release and then wait for PowerShell-core to adopt this will take much longer to address this than should be for a security issue.

**Comment by vcsjones** [comment]
It looks like this was fixed for 7.0 here https://github.com/dotnet/runtime/pull/78057 and 6.0 here https://github.com/dotnet/runtime/pull/78051 back in November 2022.

**Comment by MrPippin66** [comment]
Cool! Thanks for the information

**Comment by janvorli** [comment]
@MrPippin66 I already did before the release. But I've double-checked now. I've deleted the /tmp/.dotnet/shm and then ran
```sh
dotnet new console
dotnet run
```
After that:
```sh
ls -la /tmp/.dotnet/shm/
total 12
drwxrwxrwt 3 janvorli janvorli 4096 bře 10 07:18 .
drwxrwxrwt 3 janvorli janvorli 4096 bře 10 07:18 ..
drwx------ 2 janvorli janvorli 4096 bře 10 07:18 session1131269
```
as you can see, the session1131269 has access for my account only.

**Comment by MrPippin66** [comment]
@janvorli 

What is the permissions on /tmp/.dotnet? Primary issue on my side to validating stickybit was set on that directory.

**Comment by janvorli** [comment]
The .dotnet doesn't have the sticky bit set with the change. When I did the ls above, I've removed just the shm. Removing /tmp/.dotnet and re-running "dotnet clean" "dotnet build" creates .dotnet without the sticky bit. The only subdirectory created in this directory is the shm and that can be created by any user. So the sticky bit wouldn't make sense here.
This is for 7.0.3, right.

**Comment by MrPippin66** [comment]
Okay, but the text of the original change included the comment 'sticky bit is set for the /tmp/.dotnet,'.

Was that in error, since the primary concern is any directory in /tmp with world write with the sticky bit set from a security standpoint.

**Comment by janvorli** [comment]
It was a mistake. I have originally had it set that way, but then I've removed the sticky bit on the .dotnet due to the reason mentioned above, but obviously forgotten to modify the comment.
Here is an overview of what the change did to the permissions / sticky bits. The changes are highlighted using bold:
Before: 
/tmp RWX for all users, sticky bit set 
/tmp/.dotnet - RWX for all users 
/tmp/.dotnet/shm - RWX for all users 
/tmp/.dotnet/shm/global - RWX for all users 
/tmp/.dotnet/shm/sessionXXXX - RWX for all users 
/tmp/.dotnet/shm/global/somemutexfile- RW for all users 
/tmp/.dotnet/shm/sessionXXXX/somemutexfile - RW for all users 

After: 
/tmp - RWX for all users, sticky bit set 
/tmp/.dotnet - RWX for all users 
/tmp/.dotnet/shm - RWX for all users, **sticky bit set** 
/tmp/.dotnet/shm/global - RWX for all users 
/tmp/.dotnet/shm/sessionXXXX - **RWX for current user only** 
/tmp/.dotnet/shm/global/somemutexfile- RW for all users 
/tmp/.dotnet/shm/sessionXXXX/somemutexfile - RW **for current user only**

**Comment by MrPippin66** [comment]
I appreciate the clarification. Is there a reason to not have the sticky bit set on /tmp/.dotnet?

Again, from a Unix/Linux security standpoint, that's a security issue on world-writable directories.

**Comment by janvorli** [comment]
I've just mentioned the reason in my comment above. The only subdirectory created in this directory is the shm and that can be created by any user. So the sticky bit wouldn't make sense here. There is no reason to prevent other users from deleting the shm directory.

**Comment by MrPippin66** [comment]
Other than this is still a bad security practice and countless tools flag this as a security issue.

World writable directories without the sticky-bit set in Unix should always be avoided.

**Comment by MrPippin66** [comment]
The issue isn't expressly about anyone being able to write into a directory. That's the nature of /tmp and /var/tmp, for that matter. The issue is that having them be world-writable alone allows anyone to remove files in that directory, even if they don't own the file. That includes renaming file they don't own as well.

That's why the sticky bit should be added, so that only the owner of a file in a world-writable directory can remove/rename it.

What I'm gathering is a problem with how the 'shm' directory within /tmp/.dotnet is managed.

**Comment by janvorli** [comment]
I understand the reasons for avoiding world writable directories and using sticky bits. But I see that as something to avoid doing by accident, since in 99% of cases, you don't really want world writeable directories without the sticky bits. If you do it by design for a reason, then it seems ok. 
In our case, can you describe a reason for adding the sticky bit to the `.dotnet` directory and thus prevent other users from deleting the `shm` folder? The folder doesn't logically belong to any user. Imagine a machine with 100 users actively using it. A random user from that groups will be the first one to use .NET and thus the `shm` folder would be created by that user. Since that's a random user, why should the user own the "delete rights" to `shm`?

**Comment by MrPippin66** [comment]
Because a malicious user (or other un-informed task) can cause a denial of service by removing that directory or renaming it. Y, it can't be deleted with items within it, and having the sticky bit on SHM prevents anyone but the user from deleting files in 'shm', but any user can rename that folder.

Now...from what I can tell, once /tmp/.dotnet/shm is created, as long as the permissions on shm are world-writable w/sticky-bit, it doesn't matter about the permissions for /tmp/.dotnet in regards to the sticky-bit. Upon a session going away, /.dotnet/shm isn't removed.

The issue becomes if there's a reason a non-priviliged user would need to remove /tmp/.dotnet/shm once it's created.

**Comment by MrPippin66** [comment]
Is this still being investigated?

**Comment by mitch-lansweeper** [comment]
[#78106](https://github.com/dotnet/runtime/pull/) has been reverted as part of this change https://github.com/dotnet/runtime/commit/1c4e4c11e4ad514a6a1198ce494873365af4eace. Are there any plans to bring the sticky bit back for /tmp/.dotnet/shm? 

Security scanners are tripping over Serilog creating a Mutex file that is world writable and missing a sticky bit.

**Comment by MrPippin66** [comment]
Yes, disappointing. This is a very longstanding security issue
