### ISSUE TITLE
Lazy: ValueFactory attempted to access the Value property of this instance

### ISSUE THREAD

**Issue by kemsky** [dotnet/runtime#83163]
### Describe the bug
The code below throws:

_System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance._

This is obviously not true, looks like some concurrency issue.
 
MSDN promises undefined behavior but I doubt that it includes misleading InvalidOperationException.

https://learn.microsoft.com/en-us/dotnet/api/system.threading.lazythreadsafetymode?view=net-7.0

### To Reproduce
```csharp
    [Test]
    public async Task Test()
    {
        var innerLazy = new Lazy<string>(() =>
        {
            // simulate some heavy operation
            Thread.Sleep(10);
            return "lazy";
        }, LazyThreadSafetyMode.None);

        var outerLazy = new Lazy<string>(() => innerLazy.Value, LazyThreadSafetyMode.PublicationOnly);

        var task1 = new Task<string>(() => outerLazy.Value);
        task1.Start();
        var task2 = new Task<string>(() => outerLazy.Value);
        task2.Start();

        await Task.WhenAll(task1, task2);

        Assert.That(outerLazy.Value, Is.EqualTo("lazy"));
    }
```

### Exceptions (if any)
```
System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()
   at Test.<>c__DisplayClass0_0.<Test>b__1() in Test.cs:line 19
   at System.Lazy`1.CreateValue()
```

### Further technical details

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home//.dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.422 [/home//.dotnet/sdk]
  6.0.400 [/home//.dotnet/sdk]
  7.0.100 [/home//.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [/home//.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/home//.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/home//.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [/home//.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/home//.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/home//.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home//.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by svick** [comment]
> MSDN promises undefined behavior but I doubt that it includes misleading InvalidOperationException.

It does. That's what "undefined behavior" means: the code is allowed to do *anything*. And it's your responsibility to ensure that the condition that results in undefined behavior never happens.

**Comment by kemsky** [comment]
@svick, sounds more like an opinion rather than an argument. If it can do anything then let it delete everything from Drive C:\ in this case. 

Basically, current implementation is a landmine: hard to reason and impossible to debug. 

11 years: https://stackoverflow.com/questions/6300398/invalidoperationexception-in-my-lazy-value-factory/75667962

**Comment by svick** [comment]
> If it can do anything then let it delete everything from Drive C:\ in this case.

[Yes, that's technically allowed:](https://en.wikipedia.org/wiki/Undefined_behavior)

> In the C community, undefined behavior may be humorously referred to as "nasal demons", after a comp.std.c post that explained undefined behavior as allowing the compiler to do anything it chooses, even "to make demons fly out of your nose".[1]

**Comment by En3Tho** [comment]
`MSDN promises undefined behavior but I doubt that it includes misleading InvalidOperationException.`

I doubt that "undefined behaviour" is generally less misleading than that.

**Comment by tannergooding** [comment]
`None` goes through `ViaFactory` which effectively does:
```csharp
Func<T>? factory = _factory;
if (factory == null)
    throw new InvalidOperationException(SR.Lazy_Value_RecursiveCallsToValue);
_factory = null;
```

Because you've opted for `None`, the code presumes execution as if it were only done from a single thread and thus the only way `_factory` could already be `null` is via recursion.

There is not a trivial way to differentiate the case where the user said `None` but used multi-threading anyways, since adding logic to detect that would unnecessarily complicate and slow down the implementation.

"UB" indeed means "anything can happen" and while yes it will "typically" not make demons fly out of your nose, that doesn't mean that all behaviors will be perfectly sensible.

In this case the exception message is presuming correct usage and so will be slightly "off" when you explicitly use the API incorrectly.

**Comment by kemsky** [comment]
@tannergooding, the problem is that nobody owns all of the code, Lazy can throw from third party library, in debugger, even from .net code itself. 

> There is not a trivial way to differentiate the case where the user said None but used multi-threading anyways, since adding logic to detect that would unnecessarily complicate and slow down the implementation.

 Without experiment its subjective, it is easy to track thread id when `None` is selected and impact will be minimal because it is cached in ThreadStatic.

> In this case the exception message is presuming correct usage and so will be slightly "off" when you explicitly use the API incorrectly.

Exception message is totally off in this case, it obfuscates debugging, and since we selected `None` then message can state that two options are possible with literally zero effect on performance.

**Comment by tannergooding** [comment]
> the problem is that nobody owns all of the code, Lazy can throw from third party library, in debugger, even from .net code itself.

Yes, there is in general a transitive issue where if `x` is thread unsafe, then `y` which consumes it is potentially also thread unsafe.

Developers must take care when writing any kind of multi-threaded or asynchronous code.

> Without experiment its subjective, it is easy to track thread id when None is selected and impact will be minimal because it is cached in ThreadStatic.

Tracking such state correctly effectively requires treating `None` at least as `PublicationOnly`. This is undesirable and a non-starter.

`ThreadStatic`, while not overly expensive, is also not "cheap". Getting or tracking the thread ID correctly requires an additional `volatile` field and memory barrier to ensure other threads are guaranteed to observe the value. Doing anything else would just lead to spending more execution time to "potentially" surface more information about an unexpected error case. It would not ensure correctness nor would it reliably surface an error if used incorrectly.

> Exception message is totally off in this case, it obfuscates debugging, and since we selected None then message can state that two options are possible with literally zero effect on performance.

In this particular case, the code is just happening to hit the right sequence such that `Thread A` nulls out `_factory` and that modification of memory is published such that `Thread B` reads the nulled out value.

It is alternatively possible for both threads to view a non-nulled out `_factory` and to race on initializing the `T`. For non-atomic T, this can result in torn state.

The best we could do here is potentially update the error message to include something like:
> "ValueFactory attempted to access the Value property of this instance -or- ValueFactory is being incorrectly called from multiple threads"

And while that may minimally help surface that the user is doing something correct, it is not definitive or deterministic. The code can still surface UB in other ways. It may also lead users down the wrong path as they may start looking for a race condition rather than a recursion issue.
