### ISSUE TITLE
NativeAOT type instantiation sharing

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#83318]
In similar vein of https://github.com/dotnet/runtime/pull/82591, would it be possible to reduce duplication when all type parameters on a type are not relevant for type layout/size?

As an example
```cs
// or struct
class Wrapper<T>
{
    public List<T> Value { get; }
}
```

As I understand it today this produces a new instantiation per value type for T.
I understand .NET isn't (immediately) going to support gc shapes (in the golang generics sense) as a size optimization. However this particular case seems like an analysis that can be done at the template level which can 'significantly' reduce bloat.

Is there any appetite for optimizations like these?

@MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
People rely on this for perf optimizations. E.g. struct that implements an interface and then using that struct with a constrained generic `T : IInterface` method, expecting to get optimal inlining.

**Comment by NinoFloris** [comment]
I wouldn't want this to happen for methods, only for the type side. As I understand it this still adds overhead for bookkeeping that is basically entirely duplicate.

**Comment by MichalStrehovsky** [comment]
If the struct is not boxed, the type pretty much disappears after AOT compilation.

If it is boxed, the identity is observable through `is` checks or `object.GetType`. We cannot fold it - it needs a unique identity.

**Comment by NinoFloris** [comment]
The reason for this issue is the following report in Slon https://github.com/NinoFloris/Slon/actions/runs/4399086979

Slon is essentially a greenfield Npgsql, which I'm using to prototype improvements that flow back into Npgsql.
To support postgres features like user defined database types and arrays, ranges etc (composition) these drivers ships with an extensible serializer. As a result we face a many of the same challenges as STJ.

The interesting type that my example was modeled on is defined here https://github.com/NinoFloris/Slon/blob/main/Slon/Pg/PgConverterInfo.cs#L263-L280

This type is IMO the definition of such a data carrying type that never actually deals with T directly. 

Yet here under "Top 20 Slon Types By Size" it's seen as many times as there are value type T's.
<img width="547" alt="Screenshot 2023-03-13 at 03 08 01" src="https://user-images.githubusercontent.com/4218809/224592074-7b252c0f-af9c-4536-a061-c32be363bdc2.png">


Additionally under "Top 20 Slon Classes By Methods Size" you can find method sizes for 
<img width="501" alt="Screenshot 2023-03-13 at 02 43 33" src="https://user-images.githubusercontent.com/4218809/224589556-cd3900ab-f3ae-4c89-9927-e6916999ee60.png">

I'm a bit at a loss why `__GetFieldHelper` is as big as it is (it also grows per instantiation)

This is basically what I hope can be reduced as this brings an abstraction tax where even bundling values under a nice nominal type causes bloat (as opposed to pushing them into a ValueTuple which wouldn't duplicate as PgConverter<T> is a class)

**Comment by MichalStrehovsky** [comment]
It indeed doesn't look like PgConverterResolution is getting boxed anywhere - the reason why there's still the extra metadata around the type is because it's a generic valuetype instantiated over reference types. Reference type instantiations do get shared but in order to know what the actual T is at runtime, an extra argument to the method needs to be provided. This extra argument is the MethodTable (which is the 112-byte thing you see).

I have a WIP change that should be able to get rid of them. I'll try to finish it tomorrow: https://github.com/MichalStrehovsky/runtime/commit/530b76b6e4a65b85538a5bee56f68d65029a0528

> I'm a bit at a loss why __GetFieldHelper is as big as it is (it also grows per instantiation)

The method supports calling Equals/GetHashCode on the struct at runtime. There is a method body per each non-reference instantiation and the size of the individual method bodies is proportional to the number of fields on the type.

**Comment by NinoFloris** [comment]
That's fantastic @MichalStrehovsky, really cool to see the work. 

So TypeDictionaries were already a thing for R2R? 

Another relevant question would be whether Equals/GetHashCode should even stick around if the type is never boxed? (if it's never boxed we should be able to analyze whether Equals/GetHashCode is ever called on the T directly right?) Would the current alternative be to override these methods and leave them empty?

**Comment by MichalStrehovsky** [comment]
> Would the current alternative be to override these methods and leave them empty/throw?

No, that will be worse for size. The Equals/GetHashCode support is added because the compiler thinks it needs a full datastructure that describes the type. The TypeDictionary is stored in the virtual method table, along with the virtual methods. The fix I have would remove the need for both.

**Comment by MichalStrehovsky** [comment]
Do you have a sample where this saving would be meaningful? I tried the NativeAOT sample in the slon repo but that one only has one type we get rid of and the saving is not very meaningful (can't justify 140 lines of code in the compiler to maintain).

**Comment by NinoFloris** [comment]
Ah I see, it's in the following PR https://github.com/NinoFloris/Slon/pull/1. Rooting happens here https://github.com/NinoFloris/Slon/pull/1/files#diff-0b1de98cf568fad82059feddd85fa310dc9f1b528b9dff1ba74eb7e7fe5ae07cR315

We root a lot of types by default to make sure users can actually use these in their aot apps without encountering errors. 
Given these conversions can be extended or overridden there isn't a static path from say `DbDataReader.GetFieldValue<int[]>` to the actual construction of `PgConverterInfo.Create(new ArrayConverter<int>(new IntConverter(), DataTypeNames.Int.ToArrayName())` that would allows to do this generically.

With ADO.NET being an abstraction we can't easily introduce STJ like api's which would allow consuming libraries or users to root them explicitly.
```cs
public static string Serialize<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo)
```

So we compromise by manually rooting a set of converters that we feel is a good default for postgres. Most of these converters deal with structs and their various collection and System.Nullable forms. All of these add to PgConverterResolution duplication.

The PR I linked to doesn't even root half of the types Npgsql would ship out of the box with, so I wouldn't take it as the maximum expected savings either, it's more of a guiding measure for me to optimize the bloat we create.

**Comment by MichalStrehovsky** [comment]
Thanks! So this is a different problem. My fix would only help for those converters that are over reference types `PgConverterResolution<string>`, etc. The savings from my fix are minuscule.

The reason why these converters are generated is reflection:

https://github.com/NinoFloris/Slon/blob/00d082db53ffc18e97ef44a149bf371122f59f96/Slon/Pg/Converters/ArrayConverter.cs#L282-L286

The analysis in the compiler finds out we're reflecting over a constructor here. `ArrayConverter<T>` has a constructor that has `PgConverterResolution<T>` in the signature. The reflection implementation needs a full data structure describing all parameters, so we generate it, so that one can reflection-call the constructor.

The only way to get rid of the `PgConverterResolution` instances is to do ***any one*** of these:
* Not create ArrayConverter<bool>, etc. Getting rid of the instantiation of ArrayConverter also get rid of PgConverterResolution.
* Not have `PgConverterResolution<T>` in the constructor signature
* Not to reflect on this constructor

**Comment by NinoFloris** [comment]
Ah I see, yeah the reflection is not strictly necessary at all, it's essentially old/dead code. I've removed it from main. Thanks for taking a look btw, it's appreciated.

Now in the PR after rebasing on the new main I do see quite a difference (so that's really good!) but still there are about 7 matches of `PgConverterResolution`1`, do those stick around because reference types are not being shared?

**Comment by MichalStrehovsky** [comment]
I used https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot/DependencyGraphViewer.

Run the tool, click the "Use ETW events" and dotnet publish your app as usual. You'll see two graphs showing up. Double click the _second one_. Search for `PgConverterResolution.*constructed` (it's a regex). Then you can double click on the results to explore the dependencies - it's essentially a graph viewer, so it shows you incoming edges in the upper part (things that brought in the thing you're looking at), and outgoing edges (what this thing depends on).

Sometimes it will just tell you the reason something was added is "reflection". Then repeat the process with the _first graph_. The first graph has the whole program analysis before code generation and can often have more details.

**Comment by NinoFloris** [comment]
Good to know, it's just too bad I'm on macOS. Ideally I don't have to boot a VM and sync a project just to do it. I see there are some other tools for inspecting dgmls but they'll probably only deal with the 'first graph' as the second needs ETW?

**Comment by MichalStrehovsky** [comment]
The readme also describes a second approach - add `<IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>` to the project file. This will generate the two XML files that the tool can also open (the "scan" one is whole program analysis, "codegen" one is the code generation one).

You'll still need a way to run a WinForms app though because the tool is based on WinForms. Wine would probably work on Linux - I don't know if there's Apple equivalent.

There's also https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot/WhyDgml but this tool only shows you a path from a specific node name in the XML to the root. It also works. It's command line based.

**Comment by NinoFloris** [comment]
>The readme also describes a second approach 

I noticed, does the dgml meaningfully differ in some way from the ETW events as far as you know?

>https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot/WhyDgml

Yup thanks, trying that one right now!

**Comment by MichalStrehovsky** [comment]
> I noticed, does the dgml meaningfully differ in some way from the ETW events as far as you know?

The DGML only captures the first edge leading to a vertex. I.e. if X is referenced by A and B, the ETW events will show you both A and B, but DGML will only show A. If your goal is to get rid of X, you can still achieve that with DGML. First you get rid of A and then you get rid of B. Often times this makes the job easier because there's less noise.

**Comment by agocke** [comment]
@NinoFloris I'm not sure how your serializer system works, but you might also be interested in https://github.com/agocke/serde-dn. My aim in the project there isn't to be particularly efficient in minimizing size-per-type, but the goal is to get one "serialize" implementation per type in the vast majority of cases, which would mean that there's lots of sharing across the stack, and you only pull in what you actually use.

**Comment by NinoFloris** [comment]
@agocke definitely interesting work, I've seen the library in rust, not a bad approximation! I might even prototype some part in our internal codebase to use this instead of the STJ serializer, just to see how it goes.

For the driver level serialization I'm working on it won't be an easy fit though, prime example being that we do quite a bit of streaming reading/writing of variable length column data, which as far as I can see wouldn't be possible.

Additionally we have to deal with the unfortunate reality that db nulls pose (the protocol sends these as a negative column length). We handle those on the outside so not all our value type converters have to be defined over Nullable (users are also expected to call IsDbNull before GetInt on DbDataReader if they expect db nulls).

Some of these could maybe be overcome by different factoring but it all makes for an awkward fit with generalized serializer frameworks...

**Comment by agocke** [comment]
> For the driver level serialization I'm working on it won't be an easy fit though, prime example being that we do quite a bit of streaming reading/writing of variable length column data, which as far as I can see wouldn't be possible.

This is pretty interesting. Do you have an example?

**Comment by NinoFloris** [comment]
Npgsql has a ring buffer for reading and one for writing. This means that for instance to read strings larger than this buffer size we stream the bytes through an encoder to get chars to build a string with. For writing this amounts to a flush each time we fill up the buffer with utf8 encoded bytes.

If we couldn't do this we would need to read the entire thing into memory at once, encode it in one go and make a string that way, quite a bit less efficient. For writing it would preclude pass through streaming of say json from http requests.

Npgsql also support TextReader and Stream as column readers but in these cases we internalize all the streaming into the stream implementation so that would work without streaming at the serializer level.

Finally as pg has support for composite types like arrays, multiranges, and records (and arrays of these) each of these values could be a large value again. Forcing some form of streaming support throughout the stack.

As you probably know similar support for streaming exists in STJ, it's just not publicly extensible.

**Comment by MichalStrehovsky** [comment]
The costs of async are known and there has been some thinking whether we could move more of this support into the runtime. There's not much we can do about this.

Otherwise I don't see much actionable here, so I'm going to close this. Sizoscope tool can be used to investigate why something was generated: https://github.com/MichalStrehovsky/sizoscope. If there's something suspicious, feel free to open issue on that thing.
