### ISSUE TITLE
Make get_hostfxr_parameters.dotnet_root behave the same on linux and windows

### ISSUE THREAD

**Issue by Simoyd** [dotnet/runtime#83403]
### Description

When your runtimeconfig specifies includedFramework(s), get_hostfxr_parameters.dotnet_root needs to be your included framework directory for both linux and windows. This is consistent.

When runtimeconfig does not specify includedFramework(s):
-windows ignores the value in get_hostfxr_parameters.dotnet_root and uses the system installed frameworks (C:\Program Files\dotnet).
-linux still uses get_hostfxr_parameters.dotnet_root and does not use the system installed frameworks (DOTNET_ROOT environment variable).

In my opinion, linux should be made to functionally work like windows and use the DOTNET_ROOT environment variable to find the system installed frameworks when includedFramework(s) is not specified in the runtimeconfig. If someone still needs to force a custom framework location, they can set the environment variable for their process. I think this makes sense because the system is your environment, hence environment variable, and the system installed framework is what you're using here, not the get_hostfxr_parameters.dotnet_root for your included framework.

The work-around for this behavioral inconsistency bug I've resorted to is to open the runtimeconfig file myself, search for "includedFramework" then decide based on that whether to set get_hostfxr_parameters.dotnet_root or not. I don't think my application should need to be aware of the contents of the runtimeconfig at this level.

Failing any fix here, the difference should at least be documented.

### Reproduction Steps

call hostfxr_initialize_for_dotnet_command_line, with get_hostfxr_parameters.dotnet_root set to your custom assembly path where the runtimeconfig does not specify includedFramework(s) on linux.

### Expected behavior

Should behave same as windows and uses the system installed framework. on linux this is specified by the DOTNET_ROOT environment variable.

### Actual behavior

Fails to find system installed framework.

### Regression?

unknown

### Known Workarounds

manually open the runtimeconfig file yourself, search for "includedFramework", and if not present, leave get_hostfxr_parameters.dotnet_root as null. This will use the DOTNET_ROOT environment variable.

### Configuration

.net 6
windows 10
ubuntu 22.04.1

**Comment by vitek-karas** [comment]
I'm pretty sure this is due to multi-level lookup. Up till .NET 7 there was a behavioral difference where on Windows `DOTNET_MULTILEVEL_LOOKUP` was default set to true. This means that the search for the framework location would be:
* The location of the app - or whatever is in the `get_hostfxr_parameters.dotnet_root`
* Any globally registered location (registry)
* The default location `C:\Program Files\dotnet`

Unlike on Linux where the env. variable wasn't even recognized and its value was effectively always 0. What that means that if the `dotnet_root` is specified, that is the only location the app would look for the framework.

Starting with .NET 7 the default is also 0 on Windows and the behavior should be the same.
You should be able to achieve the consistent behavior by setting `DOTNET_MULTILEVEL_LOOKUP=0` on Windows (and you should basically get the Linux behavior).

The behavior and the change is described in detail here: https://github.com/dotnet/designs/blob/main/accepted/2022/disable-multi-level-lookup-by-default.md

About the `includedFrameworks`. .NET has two types of apps, framework dependent (FDD) and self-contained (SCD).

The FDD apps will have `frameworks` property in the `runtimeconfig.json`, and it means that the app doesn't have the framework, and this property declares which framework/s it needs to run. For such an app to work, the system has to be able to find the framework/s - the locations where these are looked for are described in here: https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md

The SCD apps will have the `includedFrameworks` property only. These apps carry the framework with them, and the `runtimeconfig.json` only serves as a description what they carry with them (this is only used from plugin scenarios and similar, not to start the app). When the is starting it will not use that information, it will simply note that there's no `frameworks` property -> it's self-contained -> will look next to the app for the runtime and frameworks. In this case the `dotnet_root` should act as the only location to look at.

The `DOTNET_ROOT` environment variable is only used for the FDD apps, SCD apps should ignore it. And we intentionally don't require developers to modify the env. variable as the only way to achieve a certain behavior. If the hosting code lives in a bigger process, it's not proper to modify the hosting process environment, so there should be a way to do what you want without modifying env. variables.

/cc @elinor-fung

**Comment by Simoyd** [comment]
So assuming .NET 7.0 works like linux....

I feel like calling hostfxr_initialize_for_dotnet_command_line is somewhat synonymous with double clicking a .net exe for example. When you start your exe, it figures out if it's an FDD or SCD app based on the runteimeconfig.json, and gets the framework accordingly from either the local directory (SCD) or from the system installed framework directory (FDD). When you call hostfxr_initialize_for_dotnet_command_line however, you have to know ahead of time if it's FDD or SCD and set get_hostfxr_parameters.dotnet_root to either your app path (for SCD) or null (for FDD) before calling it. This would be like requiring the user to pass a parameter to an exe or set an environment variable before running an exe. Imagine the user needing to open the runtimeconfig.json to check if the app is SCD or FDD, then run the exe in a certain way. I feel like that's what I have to do here to call hostfxr_initialize_for_dotnet_command_line. Is there any way I can use hostfxr_initialize_for_dotnet_command_line, and have it auto-detect SCD vs FDD instead of me detecting it myself by opening the runtimeconfig.json?

Or does this scenario just work differently in .NET 7.0 and it's no longer an issue?

**Comment by elinor-fung** [comment]
Just want to call out the two separate steps of how things are found here:

1. `nethost` finding `hostfxr`
    - Setting `get_hostfxr_parameters::dotnet_root` is basically telling `nethost` to look for `hostfxr` relative to that path.
    - `get_hostfxr_parameters::assembly_path` will make `nethost` find `hostfxr` as if it was for that app assembly. This would handle both SCD (looking next to the assembly) or FDD (looking in the [install locations](https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md)).
2. `hostfxr` finding the actual runtime/frameworks
    - `hostfxr` will determine where the install root is based on its own location
    - On Windows, locating the frameworks was affected by the multi-level lookup behaviour @vitek-karas mentioned
`get_hostfxr_parameters::assembly_path`

> Is there any way I can use hostfxr_initialize_for_dotnet_command_line, and have it auto-detect SCD vs FDD instead of me detecting it myself by opening the runtimeconfig.json?

When using `get_hostfxr_path`, you can set `get_hostfxr_parameters::assembly_path` to your assembly path (and `get_hostfxr_parameters::dotnet_root` to null). That should find the appropriate `hostfxr` (next to your assembly or in an install location) and then that `hostfxr`, when `hostfxr_initialize_for_dotnet_command_line` is called, will find the runtime/frameworks based on its determination of the app as SCD or FDD.

**Comment by Simoyd** [comment]
ok, so this is looking better now that I have set get_hostfxr_parameters::assembly_path (I had it null before), but I still have a small issue. Let me outline my 3 use-cases:

1. User installs FDD version of app. This has appropriate json files and doesn't have the .net "framework" assemblies. This scenario is working for me on windows and linux without reading the json file(s) myself.
2. User installs SCD version of the app. This has appropriate json files and does have the .net "framework" assemblies. This scenario is working for me on windows and linux without reading the json file(s) myself.
3. User installs SCD version of the app, which includes both sets of json files (FCD and SCD) and copies the FDD json files to the right place. On windows this works, but on linux this isn't working. hostfxr_initialize_for_dotnet_command_line returns 0x80008096 and it outputs to console ".NET location:" followed by my app path, not the DOTNET_ROOT env var path as expected.

Number 1 working but number 3 not working tells me that there's some other file in there that it's using to detect FCD vs SCD. I assume that if I can just rename that file, linux will fall back to the system installed .net location. What file or files to I need to rename to get this working?

We want to provide SCD for our customers with the option of switching to FDD if they want to update their framework. On windows we can just toggle the json files, but on linux there seems to be something else. 

Thanks a lot for the help so far from both of you. Looking forward to your response.

**Comment by elinor-fung** [comment]
Thanks for the use-case outline - that is helpful.

When `hostfxr` determines the .NET root, it uses its own location - if the runtime exists next to itself - as it would for (3), it uses its own directory as the root (tried to clarify that a little in https://github.com/dotnet/runtime/pull/83802). Then when it searches for frameworks for a framework-dependent app, it will expect frameworks to be laid out relative to that root (and fail when they aren't). 

Since we really just check for file existence/layout, renaming libhostfxr for (3) is probably your best bet here. Basically, that will make it so that `nethost` finds the `hostfxr` from the system install (and that `hostfxr` will use the .NET root for the system install and be able to find the frameworks).

**Comment by vitek-karas** [comment]
I have to add that modifying SCD to FDD this way is something we don't test in any way and things may be broken. One area which comes to mind is dependency resolution. When building the FDD version of the json files, make sure you build those as RID specific, so something like `dotnet publish -r win-x64 --self-contained false`. This will give you a better chance that the layout will look the same between SCD and FDD (for the files which are application specific, not "framework") and thus the generated json files will work correctly. The case where this matters is if the app has a dependency which carries RID specific assets (like native libraries).

**Comment by elinor-fung** [comment]
@Simoyd I'm going to close this issue - please do open another issue you hit other problems (and note Vitek's comment around the scenario of SCD-FDD modification).
