### ISSUE TITLE
Support all applicable ConfigurationBinder method overloads in binding generator

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#83600]
Full list: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration.configurationbinder?view=dotnet-plat-ext-8.0

An open question is whether to support overloads that take `BinderOptions`:  

<html>
<html>

BindNonPublicProperties | When false (the default), the binder will only attempt to set public properties. If true, the binder will attempt to set all non read-only properties.BindNonPublicProperties | When false (the default), the binder will only attempt to set public properties. If true, the binder will attempt to set all non read-only properties.
-- | ---- | --
ErrorOnUnknownConfiguration | Gets or sets a value that indicates whether an exception is thrown when a configuration key doesn't have a matching property in the model object.ErrorOnUnknownConfiguration | Gets or sets a value that indicates whether an exception is thrown when a configuration key doesn't have a matching property in the model object.

The issue is that source generators cannot support `private` properties; and it might not make sense to have partial support for the binder options.

cc @tarekgh @ericstj @eerhardt

**Comment by layomia** [comment]
> An open question is whether to support overloads that take BinderOptions

The current direction is to support `BinderOptions`. We'll throw `NotSupportedException` when `BindNonPublicProperties` is specified, but support `ErrorOnUnknownConfiguration`

**Comment by DamianEdwards** [comment]
We also need to support:
- `OptionsBuilderConfigurationExtensions.OptionsBuilder<TOptions>.BindConfiguration<TOptions>(this OptionsBuilder<TOptions> optionsBuilder, string configSectionPath, Action<BinderOptions>? configureBinder)`
- `OptionsBuilderConfigurationExtensions.OptionsBuilder<TOptions>.Bind<TOptions>(this OptionsBuilder<TOptions> optionsBuilder, IConfiguration config)`
- `OptionsBuilderConfigurationExtensions.OptionsBuilder<TOptions>.Bind<TOptions>(this OptionsBuilder<TOptions> optionsBuilder, IConfiguration config, Action<BinderOptions>? configureBinder)`

**Comment by layomia** [comment]
The following issues related to supported/generated overloads will be present in .NET 8 preview 4 and addressed in p5:

- Compilation error in generated 1OptionsConfigurationServiceCollectionExtensions.Configure` implementations
- We don't yet support the full matrix of Bind​, Get​ method overloads on `ConfigurationBinder​`
- We don't yet support `Bind`​ and `BindConfiguration​` overloads on `OptionsBuilderConfigurationExtensions.OptionsBuilder`

**Comment by ericstj** [comment]
The following entry points also call into the binder:
1. [ConsoleLoggerExtensions.AddConsoleFormatter Method (Microsoft.Extensions.Logging) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.consoleloggerextensions.addconsoleformatter?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-consoleloggerextensions-addconsoleformatter-2(microsoft-extensions-logging-iloggingbuilder))
Constrast this to other built in loggers, AddConsole doesn't actually use binding, instead it uses [ConsoleFormatterConfigureOptions](https://github.com/dotnet/runtime/blob/b05b4e44c00f7d8e32aa6b839b842f7ddd7d503b/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleFormatterConfigureOptions.cs) to invoke the [internal virtual void Configure(IConfiguration configuration)](https://github.com/dotnet/runtime/blob/b05b4e44c00f7d8e32aa6b839b842f7ddd7d503b/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleFormatterOptions.cs) which is implemented by those loggers to do their own binding.  We didn't expose this method though, so customer formatters can only go through the binder.  Here's a sample app that registers a custom formatter: https://gist.github.com/ericstj/19a60f344cb2ea170d5d885004c16ccc
We could give this the treatment (lift code into source gen, removing type parameter) or we could try to expose that Configure member and tell people to implement it rather than rely on the binder.
2. [LoggerProviderOptions.RegisterProviderOptions<TOptions,TProvider> Method (Microsoft.Extensions.Logging.Configuration) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.configuration.loggerprovideroptions.registerprovideroptions?view=dotnet-plat-ext-8.0) 
3. Here's a couple places we can remove annotations by ensuring we use the generator:
https://github.com/dotnet/runtime/blob/b05b4e44c00f7d8e32aa6b839b842f7ddd7d503b/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L260-L261
https://github.com/dotnet/runtime/blob/b05b4e44c00f7d8e32aa6b839b842f7ddd7d503b/src/libraries/Microsoft.Extensions.Logging.Configuration/src/LoggerFilterConfigureOptions.cs#L55-L57

**Comment by eerhardt** [comment]
@layomia - can this issue be closed? Or is there work remaining that this is tracking?

**Comment by layomia** [comment]
Yup we can close this following https://github.com/dotnet/runtime/pull/87733.
