### ISSUE TITLE
Static tests in abstract classes aren't running

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#83617]
I don't know if something changed with our test runner, but we have a handful of tests that don't run because the tests themselves are `static` in an `abstract` class.

Consider this test:

https://github.com/dotnet/runtime/blob/dfb3d24cec0a227817420de0ae95f45b210e7c25/src/libraries/System.Collections/tests/Generic/LinkedList/LinkedList.Generic.Tests.Constructor.cs#L67

Attempting to run it:

```shell
./dotnet.sh test src/libraries/System.Collections/tests/ --filter Ctor_IEnumerableTest_Negative
```

I get:

> No test matches the given testcase filter

If I remove `static` from the test, then the test starts running.

There are a bunch of tests that fall in to this category. Some more examples:

* Some in `System.Text.Json`: https://github.com/dotnet/runtime/blob/dfb3d24cec0a227817420de0ae95f45b210e7c25/src/libraries/System.Text.Json/tests/Common/CollectionTests/CollectionTests.Dictionary.KeyPolicy.cs#L198
* Some in `System.Security.Cryptopgrahy`: https://github.com/dotnet/runtime/blob/dfb3d24cec0a227817420de0ae95f45b210e7c25/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaTests.NistValidation.cs#L17
* Some in `System.Runtime`: https://github.com/dotnet/runtime/blob/dfb3d24cec0a227817420de0ae95f45b210e7c25/src/libraries/System.Runtime/tests/System/ArraySegmentTests.cs#L82

etc.

Is this a recent regression in test running / discovery?

**Comment by pedrobsaila** [comment]
@ViktorHofer I tried with dotnet 7.0/6.0/3.1 and on 1.0.0 branch of corefx (which run the same test against .NET Framework 4.0) : static methods annotated with Fact in abstract class do not run.

**Comment by pedrobsaila** [comment]
After further investiguation I may found why : `Type.GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)` aka `GetRuntimeMethods(this Type type)` does not return static method that are inherited from abstract classes

**Comment by ViktorHofer** [comment]
@layomia FYI, the tests added in https://github.com/dotnet/runtime/pull/54429 aren't being executed.

**Comment by danmoseley** [comment]
Should we open a bug against xunit to either run such test methods or warn that they will not be run?

**Comment by stephentoub** [comment]
> Should we open a bug against xunit to either run such test methods or warn that they will not be run?

Sounds like a good idea.  It should either have an analyzer highlighting that such base static methods won't be used, or it should be using BindingFlags.FlattenHierarchy (or doing something equivalent manually).

Note the issue here isn't limited to abstract base classes... without FlattenHierarchy, base static methods in general won't be returned via Type.GetMethods on a derived type, regardless of whether the base is abstract.  Our approach to tests just makes it much more likely that tests on a base class or on an abstract base class. I fixed (most of?) the abstract base class ones, as they were easy to regex search for.  It's harder to search for the non-abstract case.  We'd really need an analyzer to do that well.

**Comment by danmoseley** [comment]
@pedrobsaila since you looked at it, do you want to open that issue on the xunit repo?

**Comment by pedrobsaila** [comment]
Sure, here it is xunit/xunit#2704
