### ISSUE TITLE
Array (single d, double d, and jagged) performance

### ISSUE THREAD

**Issue by brimfulofashar** [dotnet/runtime#83719]
### Description

Upon testing the insert performance of single dimension, 2 dimension, and jagged array, I find that the jagged array performs nearly 10x slower than an equivalent sized single dimension array. The code below gives the following output:

| Method | Mean | Error |

|------------------- |-------------:|------:|
| TestSingleArray   | 798.1 ms    | NA |
| TestDoubleArray | 1,875.5 ms  | NA |
| TestJaggedArray | 6,691.0 ms  | NA |

```
[DryJob]
public class ArrayTest
{
	private int count = Int16.MaxValue * Int16.MaxValue;

	[Benchmark]
	public char[] TestSingleArray()
	{
		char[] singleArray = new char[count];
		for (int i = 0; i < count; i++)
		{
			singleArray[i] = 'a';
		}

		return singleArray;
	}

	[Benchmark]
	public char[,] TestDoubleArray()
	{
		char[,] doubleArray = new char[count / Int16.MaxValue, count / Int16.MaxValue];

		for (int i = 0; i < count / Int16.MaxValue; i++)
		{
			for (int j = 0; j < count / Int16.MaxValue; j++)
			{
				doubleArray[i, j] = 'a';
			}
		}

		return doubleArray;
	}

	[Benchmark]
	public char[][] TestJaggedArray()
	{
		char[][] jaggedArray = new char[count][];

		var chars = new[] { 'a' };

		for (int i = 0; i < count; i++)
		{
			jaggedArray[i] = chars;
		}

		return jaggedArray;
	}
}
```

**Comment by brimfulofashar** [comment]
Hi

I would expect that jagged and 2d array should be similar in performance. The test shows that even reusing the same char array in the jagged array for loop, the difference between 2d and jagged array is more than 3x. And conceptually, a 2d array is the same as a single dimension array in that a single dimension has a y axis of 1 whereas a 2d array has a y axis of 1 or more. I just don't understand why there is such a massive difference between single d, double d, and jagged array

**Comment by krwq** [comment]
You can play around with sharplab, i.e.:
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgYhgVwDZ4TB4CmABACZQpGkCwAUAAIBMAjI0wMxmtkDCZAN6MyYsgGMA9jBQIysedJwx5AXjJsWXANyMAkN15sAbJIAWEAE4BtALpkAKiTkBlWAHNSAQStWIAJ4AFACUBiIM+voSlrYOKJ4+foFkGjAkAO4W1jbKqnZ6kfoAZlJWZEGKCqlkAAw61QA8klIqCA1QANSdYUURUfoJMF4kvv4BNlAOGgDkEDOFUQC+jAaGAOxkQyNjgYsrDOJkouJGTKbZcfZOLggAUhAeHiQUu8G9+v3RsfbXAFaPZ6vZIBGrpLIxHJ5BB2eyFNYAN2slxQYMy1yEZDmMzIS3hRVK5UqqmqGnqTRabQ63Q+nzW+gBTxeb0m0xRi30BzWTE2jKBb32jCWQA=

to figure out what we could do better. If you have any specific suggestion please share more details

**Comment by krwq** [comment]
Here is a more fair comparison:
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgYhgVwDZ4TB4CmABACZQpGkCwAUAAIBMAjI0wMxmtkDCZAN6MyYsgGMA9jBQIysedJwx5AXjJsWXANyMAkN15sAbLwAsZACok5AZVgBzUgEEATm4gBPABQSAFhBuANoAumRBnl5wkoFuZCSkYCSqAJQGIgz6+gBmUvE+igpkGgAMOsUAPJJSKggVUADUjelZ+pnZ+pHewVDhGokkyap6bQC+BhMM4mSi4kZMphbWtggAUhCOjiQU7lF+cWFhER7eMQFBx4PDCK3tBrn5ZIWqxWUNZNXKIwrNd/dtLqnLy9foJJIpeoPKb6KZjIA===

**Comment by stephentoub** [comment]
In this particular benchmark, though, it has very little to do with it being a jagged array, as it's not writing to the inner arrays.  This particular benchmark, comparing TestSingleArray and TestJaggedArray, beyond the allocation (which is allocating different amounts of memory between the benchmarks and thus isn't apples to apples), is really just a test of writing different kinds of Ts into a T[].  The TestSingleArray is writing a small value type (a char) and the TestJaggedArray is writing a reference type (a char[]).  Writing reference types to shared locations requires write barriers (and in some cases covariance checks) that aren't incurred for value types.  Try changing your TestSingleArray to use an `object[]` instead of a `char[]`, and you'll see similar overhead as with your TestJaggedArray.
