### ISSUE TITLE
[API Proposal]: Add global JsonSerializerOptions to System.Net.Http.Json

### ISSUE THREAD

**Issue by LioRei** [dotnet/runtime#83767]
### Background and motivation

I have a problem with System.Net.Http.Json => it's not possible to set a global JsonSerializerOptions like the one when you do :

```csharp
services.AddControllers().AddJsonOptions(options =>.....
```

### API Proposal

Something like this would be nice

```csharp
namespace System.Net.Http.Json;

public void ConfigureServices(IServiceCollection services)
{
  services.AddHttpJsonOptions(options =>
  {
    options.JsonSerializerOptions.Converters.Add(new TimeOnlyJsonConverter());
  };
}
```

### API Usage

the same usage as before but with the configured option as default option so you do not have to do this anymore :
```csharp
httpClient.PostAsJsonAsync("endpoint", myObject, myStaticJsonSerializerOptions);
```

but just :
```csharp
httpClient.PostAsJsonAsync("endpoint", myObject);
```

### Risks

from my point of view there is no breaking change because if you do not set a JsonSerializerOptions, the API is working like before

**Comment by eiriktsarpalis** [comment]
Note that the `AddHttpJsonOptions` is a component that lives in ASP.NET so `System.Net.Http.Json` components can't reference it. At the same time, we want to avoid making the global default options user-configurable since independent components in an application could race to set it. See https://github.com/dotnet/runtime/issues/31094 for a discussion on the matter.
