### ISSUE TITLE
[globalization] Get CultureInfo.NumberFormat may throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by lindexi** [dotnet/runtime#83764]
### Description

In the special windows system with the icu issues, the dotnet 6 application may throw IndexOutOfRangeException when get the CultureInfo.NumberFormat by `new CultureInfo("en-US").NumberFormat`

### Reproduction Steps

1. Find the special windows system with the icu issues
2. Run the application with this code:

```csharp
_ = new CultureInfo("en-US").NumberFormat;
```

### Expected behavior

The code can get the right NumberFormat.

### Actual behavior

The code will throw the IndexOutOfRangeException

### Regression?

.NET 5

### Known Workarounds

How to fix?

1. Use NLS instead of ICU. See https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu
2. Cherry pick the https://github.com/dotnet/runtime/pull/58598

### Other information

Why it will throw the IndexOutOfRangeException? Because the `digits` will be the empty string, but we will assume that there must be 10 chars, just as the screenshots:

![image](https://user-images.githubusercontent.com/16054566/226824277-01965303-89b7-4834-b850-0740a13bfbc8.png)

See https://github.com/dotnet/runtime/blob/cd1b4cff818a700b6ff82fde024c65b036979894/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L2171-L2180

Starting with .NET 5, we will use International Components for Unicode (ICU) in all the platforms. See https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

And the .NET will call the icu by `GlobalizationNative_GetLocaleInfoString`, see https://github.com/dotnet/runtime/blob/c2ec86b1c552ac8a1749f9f98e012f707e325660/src/libraries/Common/src/Interop/Interop.Locale.cs#L14-L16

https://github.com/dotnet/runtime/blob/9d6396deb02161f5ee47af72ccac52c2e1bae458/src/native/libs/System.Globalization.Native/pal_localeStringData.c#L207-L218

And the CultureData.IcuGetLocaleInfo will return the string.Empty when the `GlobalizationNative_GetLocaleInfoString` return false, see

https://github.com/dotnet/runtime/blob/9260c249140ef90b4299d0fe1aa3037e25228518/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L134-L141

But the CultureData.GetNFIValues will get 10 chars from the CultureData.IcuGetLocaleInfo result and throw the IndexOutOfRangeException

This issue was fixed by https://github.com/dotnet/runtime/pull/58598 , but this fix was not merged into .NET 6.0.12

Thank you @tarekgh and can this fix merge to .NET 6?

**Comment by tarekgh** [comment]
@lindexi thanks for your report. 

> Use NLS instead of ICU. See [learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu)

I don't think this is a workaround. The original problem here is the user override settings were corrupted. Instead of using `_ = new CultureInfo("en-US").NumberFormat;` try to use `_ = CultureInfo.GetCultureInfo("en-US").NumberFormat;` or use `_ = new CultureInfo("en-US", false).NumberFormat;` and the problem should go away because at that time .NET will not read the user overrides. 

On the machine you are seeing this issue, try to look at the registry key `HKEY_CURRENT_USER\Control Panel\International` and look at the value of `sNativeDigits`, for `en-US` the value should be something like `0123456789`. If you are not seeing that, try to fix it with this value and that should fix the issue too. 

Considering the two workarounds I have listed here; I don't think this will meet the bar for doing any fix in .NET 6.0. Every change in servicing release comes with some risk. Please confirm the workaround is working fine for you.

**Comment by lindexi** [comment]
Thank you @tarekgh 

But I do not think we can ignore the user override in our application. The origin issues is my wpf application will hang when it runs in the special devices. The wpf application should use `CultureInfo.NumberFormat` to print the UI. And the client application should not ignore the user override.

See https://github.com/dotnet/wpf/issues/7658

**Comment by tarekgh** [comment]
@lindexi let the user fix the settings on their machine.

**Comment by lindexi** [comment]
@tarekgh Doing so is against the principles of client applications. But thanks for your help. And I think setting environment variables is a way to go.
