### ISSUE TITLE
[ARM64] Consider using LDAPR for volatile variables

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#83830]
https://github.com/dotnet/runtime/issues/67374 added support for using ldapr instead of ldar within the jit.

However, both `gc/env/volatile.h` and `inc/volatile.h` use __atomic_load() on Arm64 Linux. This will compile to ldar. On Arm64 Windows, it directly uses an ldar() intrinsic call.

If coreclr was compiled for 8.2 or armv8-a+rcpc then it could instead use ldapr:
This could be done by either:
* Use inline assembly instead of calling __atomic_load()
* LLVM 16+ and GCC 13.1+ will use ldapr by default for __atomic_load() when compiling for 8.2.

Of course, this means coreclr would only run on 8.2 or machines with rcpc. This is far from ideal, but may be useful in closed scenarios (such as cloud machines).

It would be possible to outline the atomic_load call and/or add rcpc runtime checks so that it still works on 8.0, but I wouldn't recommend this as it would remove performance gains.

**Comment by a74nh** [comment]
@kunalspathak

**Comment by VSadov** [comment]
One thing is worth mentioning is that current systems that implement LDAPR do not seem to provide much performance gain over LDAR, as it was observed when the JIT optimization was implemented.

That could be because it is valid to implement LDAPR as an alias to LDAR (since LDAR is stronger) and it is possible that initial "implementations" of LDAPR are just LDARs.

This may change in the future, but as a matter of urgency to switch to LDAPR, it is mostly "good to have, if easy to arrange".

**Comment by VSadov** [comment]
> If coreclr was compiled for 8.2 or armv8-a+rcpc then it could instead use ldapr

Is that already the case when targeting Apple ARM64?

**Comment by EgorBo** [comment]
> One thing is worth mentioning is that current systems that implement LDAPR do not seem to provide much performance gain over LDAR, as it was observed when the JIT optimization was implemented.

It seems to be the case for Apple M1 while on Amepere Altra it resulted in benefits for various projects

> Is that already the case when targeting Apple ARM64?

yes, we didn't even set any args for native compiler, XCode's clang did it itself since M1 is a baseline for macOS-arm64. Crossgen/NATO do the same when compiling for `osx-arm64` RID.

> Of course, this means coreclr would only run on 8.2 or machines with rcpc. This is far from ideal, but may be useful in closed scenarios (such as cloud machines).

I don't think we want to add (and maintain) a new type of SDK for each OS on the given arch unless it provides signifacant benefits which is unlikely to be the case here.

**Comment by VSadov** [comment]
> It seems to be the case for Apple M1 while on Ampere Altra it resulted in benefits for various projects

Nice! 
I did not know about that. I kind of thought this optimization is a bit ahead of its time.

**Comment by a74nh** [comment]
> I don't think we want to add (and maintain) a new type of SDK for each OS on the given arch unless it provides signifacant benefits which is unlikely to be the case here.

If you're not already making special builds of dotnet, then agreed it's a lot of hassle to add that.

I was looking at perf logs for aspnet techempower, and there were quite a lot of uses of Volatile loads in there. However, this was a Debug build of Dotnet. Switching to a Release build, the volatiles vanished. I tried using LDAPR and it did improve performance stability on Debug, but (as expected) did nothing for Release.

**Comment by kunalspathak** [comment]
> I tried using LDAPR and it did improve performance stability on Debug, but (as expected) did nothing for Release.

I don't think there is anything actionable at this point. Closing it.
