### ISSUE TITLE
[API Proposal]: Update nullable annotations on `JsonSerializer.Serialize<TValue>`

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#83930]
### Background and motivation

```c#
// CS8625 Cannot convert null literal to non-nullable reference type.
_ = JsonSerializer.Serialize<Sample>(null);

// This is ok
_ = JsonSerializer.Serialize<Sample?>(null);

class Sample {  }
```

As the method support null values, I think the annotation could be updated to reflect that.

### API Proposal

```diff+csharp
namespace System.Text.Json;

public static class JsonSerializer
{
    // existing
    public static string Serialize<TValue>(TValue value);

    // Suggested
    public static string Serialize<TValue>(TValue? value);

    // Same for similar methods and overloads: 
    // Serialize<TValue>, SerializeAsync<TValue>, 
    // SerializeToDocument<TValue>, SerializeToElement<TValue>,  
    // SerializeToNode<TValue>, SerializeToUtf8Bytes<TValue>
}
```

### API Usage

```c#
Console.WriteLine(JsonSerializer.Serialize<Sample>(null));
```

**Comment by stephentoub** [comment]
This is by design.  The developer has specified that null is not a valid value by specifying a non-nullable T.  It's similar to how if you have a `Dictionary<string, string>` and try to store a null as a value, you'll get a nullability warning; technically the dictionary can handle it, but the developer has explicitly stated that nulls are not in the domain of valid values.

**Comment by meziantou** [comment]
Thanks for the explanation
