### ISSUE TITLE
[libraries-jitstress-random] Assertion failed '(emitThisGCrefRegs & regMask) == 0' during 'Emit code' 

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#83963]
Several tests are failing with this assert, in both win-x86 and linux-arm32.
Test run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=201954&view=results
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-9423de4c7e154d2480/System.Private.Xml.Tests/1/console.d22bcbec.log?helixlogtype=result

```scala
Assert failure(PID 6288 [0x00001890], Thread: 8356 [0x20a4]): Assertion failed '(emitThisGCrefRegs & regMask) == 0' in 'System.String:Concat[ushort](System.Collections.Generic.IEnumerable`1[ushort]):System.String' during 'Emit code' (IL size 417; hash 0x33a0d879; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 13883
    Image: C:\h\w\A6C2090E\p\dotnet.exe
```

**Comment by JulieLeeMSFT** [comment]
@TIHan PTAL.

**Comment by TIHan** [comment]
I have managed to reproduce this locally, so I can iterate on this.

**Comment by TIHan** [comment]
I think I know the underlying problem.

A register, `edx`, is assigned for a ref null node:
`CNS_INT   ref    null REG edx $VN.Null`

But later we decide to re-use `edx` for a constant zero node:
`CNS_INT   int    0 reuse reg val REG edx $40`

This occurs because the two nodes are seen as equivalent, but we do not update the `emitThisGCrefRegs` to remove `edx` as GC tracked when `edx` is re-used in a non-GC way.

The decision to re-use the register is handled in LSRA, though the updating of the `emitThisGCrefRegs` appears to only be in the emitter. A possible fix might be to update `emitThisGCrefRegs` if we see that we are going to emit a constant int 0 that is re-using a register that was previously GC tracked.

// cc @kunalspathak  - not sure if there needs to be something done in LSRA in this case
full dump: [dump.txt](https://github.com/dotnet/runtime/files/11095074/dump.txt)
