### ISSUE TITLE
[perf] RSA is significantly slower than RSACryptoServiceProvider when verifying data

### ISSUE THREAD

**Issue by rymeskar** [dotnet/runtime#83994]
### Description

There is a degradation of performance when invoking `RSA.VerifyData(byte[] data, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)` over `RSACryptoServiceProvider.VerifyData(byte[] buffer, object halg, byte[] signature)`. This is visible on Windows machine both on .NET Framework as well as .NET. This does not reproduce on Linux. The degradation is two fold.
Repro can be found in [the following repository](https://github.com/rymeskar/rsa_degradation_repro/blob/master/RsaCryptoDegradations.cs).

*Is this known?*

### Data

[Benchmark.NET Results](https://github.com/rymeskar/rsa_degradation_repro/blob/master/BenchmarkDotNet.Artifacts/results/RsaRepro.RsaCryptoDegradations-report_48.html)

I can also provide further details of my machine CPU.

### Analysis

Initial analysis showcases that the RSACryptoServiceProvider invokes CAPI under the hood.

**Comment by vcsjones** [comment]
This doesn't exactly surprise me. I was able to reproduce the difference in behavior between CSP and CNG, but it wasn't quite as dramatic for me.

In .NET 7 (and below), RSA is backed by the "NCrypt" implementation in CNG - so it's doing a bunch of work and RPC calls to the Microsoft KSP.

Starting in .NET 8, we use the "BCrypt" primitives for RSA where we can. This means signature verification takes place in-proc.

Here's your same benchmark for .NET 8, which shows an improvement.

|                   Method |     Mean |    Error |   StdDev | Ratio |
|------------------------- |---------:|---------:|---------:|------:|
|                  RsaSpan | 27.71 us | 0.044 us | 0.039 us |  1.00 |
| RsaCryptoServiceProvider | 37.02 us | 0.294 us | 0.275 us |  1.34 |
|                RsaString | 27.65 us | 0.084 us | 0.070 us |  1.00 |

I would say this has been fixed for .NET 8 (I tried on a nightly). Would you be able to try a .NET 8 preview and confirm that the performance issue is resolved in .NET 8?

**Comment by vcsjones** [comment]
One tiny nit on the benchmark, too: the `RsaCryptoServiceProvider` benchmark is deferring cleanup of the hash to the finalizer thread. The benchmark should look like:

```C#
[Benchmark]
public bool RsaCryptoServiceProvider()
{
    using (var sha = SHA256.Create())
    {
        return Artifacts.CryptoServiceProvider.VerifyData(Artifacts.PayloadBytes, sha, Artifacts.SignatureBytes);
    }
}
```

It doesn't make a significant impact on the benchmark, but the overloads that accept `HashAlgorithmName` do properly cleanup their hash resources - so a comparable benchmark for CryptoServiceProvider should as well, too.

**Comment by rymeskar** [comment]
Awesome! Thank you for the swift response. I can confirm the improvements on .NET 8 preview. Now, there is however the opposite problem: `RSACryptoServiceProvider` is significantly slower than `RSA`.

**Comment by vcsjones** [comment]
@rymeskar Generally, `RSACryptoServiceProvider` shouldn't be used - you should use `RSA rsa = RSA.Create()`. This factory method will always return "the best" implementation for the platform, be-it Linux, macOS, or Windows. If you use `RSA.Create()` instead of `new RSACryptoServiceProvider()`, you'll get the same bcrypt goodness (for .NET 8).

The only time `RSACryptoServiceProvider` should be used is when you specifically need to interop with old CAPI features. But if all you want is to verify (or sign) RSA signatures, then `RSA.Create()` is the way to go.

**Comment by rymeskar** [comment]
Thanks for the explanation. The way I got here is by benchmarking the default .NET JsonWebToken validation library (Wilson) and not understanding the numbers compared to vanilla RSA. 

This means the Wilson library rather uses the [`RSACryptoServiceProvider`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs). Should the library then switch to `RSA` type with the release of .NET 8?

cc: @brentschmaltz, @jmprieur

**Comment by vcsjones** [comment]
> Should the library then switch to RSA type with the release of .NET 8?

I'm less certain what that proxy class is used for, or if it should be used. Some basic thoughts:

1. `RSACryptoServiceProvider` is not really a cross-platform concept. On non-Windows it fakes it - it just uses `RSA.Create` under the covers and wraps that.
    https://github.com/dotnet/runtime/blob/ed3721b092e395ac3576c2d93f4134650a44dc08/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSACryptoServiceProvider.Unix.cs#L27

    The reason we do this is because a ton of code has been written to use `RSACryptoServiceProvider`, so we wanted to make it work. But certain CryptoServiceProvider APIs like `CspContainerInfo` [will just throw](https://github.com/dotnet/runtime/blob/ed3721b092e395ac3576c2d93f4134650a44dc08/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSACryptoServiceProvider.Unix.cs#L39-L40).

2. On Windows, `RSACryptoServiceProvider` is the real-deal. It uses Windows CSP CAPI API, which [is deprecated](https://learn.microsoft.com/en-us/windows/win32/seccrypto/cryptographic-service-providers) in favor of Windows CNG APIs. On Windows, `RSA.Create()` and `new RSACng()` use CNG.

    "Wait, what's `RSACng`?" - this is a Windows specific class like `RSACryptoServiceProvider`. It exists solely to interop with Windows' CNG APIs. It should not be used unless you are Windows only _and_ you care about a CNG specific API.

3. To really answer your question, I would say "You should always use `RSA.Create` because it will always do the right thing on your platform (and if it doesn't, we'll fix it). Unfortunately it's slower than `RSACryptoServiceProvider` until .NET 8, but unless you have clear data showing you that the performance impact matters, I would still use `RSA.Create`.

My interpretation of that particular library is that it should just take an `RSA` implementation and let the caller decide what implementation of RSA is best for that library to use.

And to point it out - `RSACryptoServiceProvider` _is_ an `RSA` type. `RSACryptoServiceProvider` derives from `RSA`. So anywhere you are working with `RSACryptoServiceProvider` could be changed to work with `RSA`. And if anyone really wanted, they could keep giving `RSACryptoServiceProvider` instances where `RSA` is expected.

**Comment by rymeskar** [comment]
Thank you for the extensive explanation. In that case, feel free to close this issue.

Just one question: are consumers on .NET framework also going to get the bcrypt goodies through some nuget updates?

**Comment by vcsjones** [comment]
> Just one question: are consumers on .NET framework also going to get the bcrypt goodies through some nuget updates?

Not to my knowledge. These APIs are inbox and part of the framework, and I do not believe .NET Framework will get serviced for that.

Based on your comment then, I am going to close this out, but please feel free to re-open or open a new issue if anything is unanswered.

**Comment by brentschmaltz** [comment]
@rymeskar thanks for this work.
Wilson does wrap a RSACryptoServiceProvider to handle some edge cases with [SHA2 ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2b1b78bf38a5739719e95b7045d81902a2cf09d5/src/Microsoft.IdentityModel.Tokens/RsaCryptoServiceProviderProxy.cs#L51)and X509Certificzate2.GetPublicKey.Key returned RSACryptoServiceProvider. Otherwise Wilson uses [RSA.Create](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2b1b78bf38a5739719e95b7045d81902a2cf09d5/src/Microsoft.IdentityModel.Tokens/AsymmetricAdapter.cs#L255)()
