### ISSUE TITLE
Is There a Plan to Support TLS Session Resumption Without Server-Side State RFC 5077

### ISSUE THREAD

**Issue by Azizck** [dotnet/runtime#84136]
One of the main features in TLS 1.3 is Session Ticket Resumption, which is defined in the RFC 5077 standard. Session Ticket Resumption offers significant advantages over Session Resumption using SessionID.

Session Ticket Resumption works in scalable software, unlike Session Resumption with SessionID. In Session Ticket Resumption, the responsibility of storing the session information is pushed to the client. The server encrypts the session information, called a ticket, with a session ticket encryption key and sends it to the client. The client keeps hold of the ticket, and when it wants to resume the connection, it sends the ticket to the server in the Hello message.

On a side note, in a[ Microsoft dev blog on .NET 7](https://devblogs.microsoft.com/dotnet/dotnet-7-networking-improvements/), it is stated that session resumption with the stateless server is supported. In reality, the current implementation actually caches client session information.

the area is: area-System.Net.Security

**Comment by wfurt** [comment]
Now, it is somewhat more complicated. The changes described in the blog are applicable only to Linux. (we should probably make that more clear @ManickaP @CarnaViire) 

On Windows, you can get either one, it is fully handled by schannel and registry setting. On macOS none of the resume features work at the moment. 

For Linux there is currently no plan. We started with the stateless option as it does not take any additional resources from server. Server can handle LOT of connections while client can be somewhat more in control. I may be more inclined to do more if needed as #78305 was approved and gives at least some control. But any fine grain control is going to be difficult IMHO because of the platform disparity. 

cc: @Tratcher @davidfowl  for more thoughts on the server.

**Comment by rzikm** [comment]
I filed https://github.com/dotnet/runtime/issues/85113 to track demand for stateless TLS resumption feature on Linux/Mac
