### ISSUE TITLE
Deduction double values does give incorrect value.

### ISSUE THREAD

**Issue by olljanat** [dotnet/runtime#84227]
### Description

I noticed that all versions of PowerShell gives incorrect values on deduction.

### Reproduction Steps

![image](https://user-images.githubusercontent.com/6213926/229362730-43f1382a-702a-4297-bec3-485613610870.png)

After playing with code:
```csharp
using System;
					
public class Program
{
	public static void Main()
	{
		double a = 10.1;
		double b = 10.0;
		Console.WriteLine(a - b);
		
		decimal c = 10.1m;
		decimal d = 10.0m;
		Console.WriteLine(c - d);
	}
}
```
on https://dotnetfiddle.net it looks that same actually applies whole C#
![image](https://user-images.githubusercontent.com/6213926/229362792-d7140b46-94ce-4c85-a089-c99b6bade797.png)

### Expected behavior

Same than we see with decimal.

### Actual behavior

Very odd number as output.

### Known Workarounds

Force numbers to decimal.

**Comment by olljanat** [comment]
Oh, ChatGPT does good work by explaining why this is case so closing...
![image](https://user-images.githubusercontent.com/6213926/229363518-41c65c03-07f4-4346-b40a-af63cac036c2.png)

<img width="393" alt="image" src="https://user-images.githubusercontent.com/6213926/229363499-28adc349-3c4e-4151-b634-b156dd359dac.png">

**Comment by tannergooding** [comment]
It's worth noting that "precise" is potentially an incorrect distinguishing factor. `double` is extremely precise and is typically accurate to between 15 and 17 significant decimal digits. `decimal` is accurate to 28 significant digits and is "more precise" because it has twice as many bits (128 vs 64) that can be used to represent the underlying value. A comparatively sized 64-bit `decimal` following the same format as `System.Decimal` would actually be able to represent less significant digits than `double` (around 14 of them). The IEEE 754 `decimal64` type is able to represent around 16 significant digits and so is approximately "as precise" as `double`, sometimes being slightly less and sometimes being slightly more. -- It all comes down to the format and how the bits are represented/handled.

Since `decimal` is base-10 and `double` is base-2 this means that `decimal` can exactly represent values that are a multiple of a power of 10 while `double` can exactly represent values that are a multiple of a power of 2. In both cases, you have `n` significant digits that can be represented and anything "additional" is used to round towards the nearest representable result. Both of these introduce rounding error, both come with imprecision for some values, and there are values (such as `1/3`) that neither can exactly represent.

For integral values, both exactly represent the values within their domain. The real difference comes down with fractional values and that decimal` works more like how we were taught math in school in that it doesn't introduce any error for the type of fractional numbers that humans typically use and think about, such as `0.1` (as long as they are under the tracked significant digit count). This comes at an additional cost/overhead and may or may not be relevant to the domain you're working in. For `double` or other binary-based numbers, you can account for such error introduced and still get an answer that is accurate to within 15-17 significant decimal digits if that's the need/desire.
