### ISSUE TITLE
Null Checks in NativeAOT?

### ISSUE THREAD

**Issue by ChrisKoebke** [dotnet/runtime#84239]
### Description

When I'm compiling the following code with .net-7.0 NativeAOT (win-x64), I get a NullReferenceException (and therefore a null check?) in unsafe code.

Exception:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.<Main>$(String[]) + 0x9a
   at ConsoleApp2!<BaseAddress>+0x16aa6b
```

### Reproduction Steps

Code (Program.cs):

```
unsafe {
    Test* t = null;

    Console.WriteLine("Before dereference");

    Console.WriteLine($"A = {t->A}");

    Console.WriteLine("After dereference");
}

struct Test {
    public int A;
}
```

### Expected behavior

I would have expected this to crash my program as there should be no null check here due to unsafe code.

### Actual behavior

NullReferenceException (and null check?).

### Configuration

.net-7.0
win-x64
PublishAot=true

### Other information

Is this a bug, or, if not, is there a way to deactivate all null checks for unmanaged pointers? I am specifically looking for maximum speed and am using unmanaged code to achieve that here, but having null checks for all pointer dereferences kind of defeats the purpose here for me. I deliberately want my app to crash whenever I'm dereferencing a null pointer.

Thanks in advance for the help!

**Comment by SingleAccretion** [comment]
This is expected behavior. Loads, stores and field address computation in C#/CLI must throw an NRE if their base is null.

> is there a way to deactivate all null checks for unmanaged pointers?

No.

> I am specifically looking for maximum speed and am using unmanaged code to achieve that here, but having null checks for all pointer dereferences kind of defeats the purpose here for me. I deliberately want my app to crash whenever I'm dereferencing a null pointer.

NREs induced by loads or stores have essentially no runtime cost on mainstream platforms. They are implemented by mapping access violations that occur in managed code to managed exceptions.

There are cases where "explicit" null checks are required, such as with `ldflda`. They are also quite cheap and implemented as unconsumed loads.
