### ISSUE TITLE
Memory Leak in MulticastDelegate 

### ISSUE THREAD

**Issue by seanhalliday** [dotnet/runtime#84709]
In CombineImp it can reuse the _invocationList if it has room.  The following program shows how this can cause a memory leak if a copy is taken of the delegate and then an item added to the delegate which modifies the _invocationList in the copy taken before the item was added.

```

public class Listener
{
	public static int s_count = 0;
	public Listener()
	{
		s_count++;
	}
	public void Callback(object sender, EventArgs args)
	{
	}
	~Listener()
	{
		s_count--;
	}
}

public class Program
{
	public static event EventHandler MyEvent;
	public static int Main(string[] args)
	{
		for (int i = 0; i < 10; i++)
		{
			var l = new Listener();
			MyEvent += l.Callback;
		}
		var copy = MyEvent;
		var l2 = new Listener();
		MyEvent += l2.Callback;
		MyEvent = null;
		l2 = null;
		GC.Collect();
		GC.WaitForPendingFinalizers();
		var count = Listener.s_count;
		return 0;
	}
}
```

I used dotMemory to show that "copy" had an invocationCount of 10 but an _invocationList with 11 items in it, so l2 will be held in memory.

**Comment by tannergooding** [comment]
CC. @jkotas for additional input

It does look like, from managed code, we can end up with a scenario where two delegates may share the same underlying array and where one of them uses an additional slot that isn't null'd out.

I am uncertain if we have any specialized handling for this scenario that may otherwise special-case things.

If there is not, this is likely a very sensitive issue to fix and it looks to have been around for a very long time.

**Comment by jkotas** [comment]
I do not see a good way how this can be fixed without regressing `Combine` performance. `Combine` performance tends to be important for event handlers in UI frameworks. The implementation assumes that the old multicast delegate is not going to be kept around, as it is the case in the event subscribe pattern. 

> it looks to have been around for a very long time.

Yes, this issue has been around since .NET Framework 2.0 where we did a lot of performance work on delegates. (.NET Framework 1.x used linked list to store targets of multicast delegates. It was a lot less efficient, but it probably did not have this issue.)

**Comment by tannergooding** [comment]
Closing based on the feedback above. It's possible some analyzer could be written to help flag such cases, but its not necessarily a common or easy to identify pattern.
