### ISSUE TITLE
XmlSerializer.GenerateSerializer alternate API in .NET Core

### ISSUE THREAD

**Issue by venknar** [dotnet/runtime#84777]
Hi

We have a code that uses the XmlSerializer.GenerateSerializer to generate the assemblies. Here is the sample reference:
```

                         XmlSerializer.GenerateSerializer(
                                types.ToArray(),
                                xmlMapping.ToArray(),
                                parameters);
```
Returns an assembly that contains typed serializers.

https://learn.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer.generateserializer?view=netframework-4.8#system-xml-serialization-xmlserializer-generateserializer(system-type()-system-xml-serialization-xmlmapping()-system-codedom-compiler-compilerparameters)

Using the above API in the .NET framework code.

As we are now moving to .NET Core looking for equivalent api or alternate mechanism to do the above.

please provide suggestions on how to support the same.

**Comment by StephenMolloy** [comment]
There is no equivalent API in .Net Core because that Framework API had a potential dependency on compilers, which are not part of the .Net Core runtime. Thus the equivalent in .Net Core is a design-time approach using [Microsoft.XmlSerializer.Generator](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator).
