### ISSUE TITLE
Intermittent failure in JIT/Directed/coverage/oldtests/tlstest_il_r/tlstest.dll

### ISSUE THREAD

**Issue by markples** [dotnet/runtime#84818]
Not much information in the logs:

Output:
08:16:17.751 Running test: JIT/Directed/coverage/oldtests/tlstest_il_r/tlstest.dll
08:16:18.001 Failed test: JIT/Directed/coverage/oldtests/tlstest_il_r/tlstest.dll

Comments:
{ "HelixJobId": "517d00ed-60bb-4043-9a15-6268bcfef42a", "HelixWorkItemName": "Directed_r" }

Error message:
Object reference not set to an instance of an object.

Stack trace:
   at tls.tlstest.Main()
   at Program.&lt;&lt;Main&gt;$&gt;g__TestExecutor2|0_1(StreamWriter tempLogSw, StreamWriter statsCsvSw, &lt;&gt;c__DisplayClass0_0&amp;)

Instances from refs/heads/main:
[#20230411.8 • [browser][non-icu] `HybridGlobalization` not supported on WASI (#84629)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=235831&view=ms.vss-test-web.build-test-results-tab&runId=4502586&resultId=100532&paneView=debug) coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
[#20230412.1 • [browser][non-icu] `HybridGlobalization` not supported on WASI (#84629)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=235949&view=ms.vss-test-web.build-test-results-tab&runId=4506924&resultId=100331) coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
[#20230412.3 • JIT: Add an in-release flag to enable physical promotion (#84689)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=236667&view=ms.vss-test-web.build-test-results-tab&runId=4524582&resultId=100607) coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
[#20230412.12 • Zlib: Update zlib to v1.2.13, intel-zlib to v1.2.13_jtk (#84602)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237422&view=ms.vss-test-web.build-test-results-tab&runId=4539782&resultId=100088) coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
[#20230413.2 • Revert "[browser] Wasm SDK packed as a nuget package (#84082)" (#84743)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237792&view=ms.vss-test-web.build-test-results-tab&runId=4548692&resultId=100938) coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open

I started looking at this upon hitting the failure in
[#20230413.1 • Fix type initialization ordering under R2R](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237775&view=ms.vss-test-web.build-test-results-tab&runId=4548378&resultId=104123&paneView=debug) 
and finding it unlikely to be from that PR.

**Comment by EgorBo** [comment]
Can be the TLS PR? cc @kunalspathak

**Comment by trylek** [comment]
Apparently we have several non-deterministically failing tests on Windows arm; all that I saw fail with a nullref, either in the runtime when executing the test, or in Crossgen2 when compiling it. The Crossgen2 determinism tests frequently hit this but they are not the only ones, it seems to be sporadically affecting other random tests. I'm wondering whether this may indicate something like an arm-specific GC hole, I find it hard to imagine how this could be caused by a codegen bug.

**Comment by trylek** [comment]
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=241282&view=results

Failed tests:
* crossgen2determinism
* coreroot_determinism
* BasicTestWithMcj
* runtimeeventsource
* BinderTracingTest.ResolutionFlow

**Comment by trylek** [comment]
Even though at the first glance some of the Crossgen2 test fail with an AV, when you look at the detailed log, you can see the underlying nullref thrown somewhere inside the compiler.

**Comment by trylek** [comment]
One thing that seems weird to me is how the codegen problem you describe can cause non-deterministic behavior as the set of affected tests seem to be fluctuating randomly. I should actually double-check this across a couple of runs, maybe I didn't look closely enough and the set of tests is actually stable. If the set of test is bounded, we could at least add temporary exclusions to issues.targets to make the outerloop green after a while, Jeff asked me to do that last Monday, I fixed about two or three different problems since then and I'm still not there.

**Comment by kunalspathak** [comment]
Yes, I would hope that this should have surfaced immediately in the outerloop CI.
