### ISSUE TITLE
Bad CodeAnalysis warning and inaccessible DynamicallyAccessedMembersAttribute to fix it 

### ISSUE THREAD

**Issue by ststeiger** [dotnet/runtime#84990]
### Description

Bug: <br />
Somehow the constructor of [System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/DynamicallyAccessedMembersAttribute.cs) does not seem to be public. 

In the bellow minimal reproduction for line 

    ConstructorInfo constructorInfoObj = ValueType.GetConstructor(Type.EmptyTypes);

I get this warning: 

>   ValueDescriptor.cs(58, 50): [IL2080] 'this' argument does not
> satisfy
> 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in
> call to 'System.Type.GetConstructor(Type[])'. The field
> 'MigraDocCore.DocumentObjectModel.Internals.ValueDescriptor.ValueType'
> does not have matching annotations. The source value must declare at
> least the same requirements as those declared on the target location
> it is assigned to.

This only occurs if I add 

    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>

to the .csproj-file. 

Why is this warning thrown in the first place, and what has it to do with trimmable ? <br />
And, far worse, according to ChatGPT, I can remedy this by setting the DynamicallyAccessedMembers attribute on ValueType: 
```
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
public Type ValueType;
```
and also include the package as build-dependency
```
<ItemGroup>
  <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" PrivateAssets="all" />
</ItemGroup>
```

But this doesn't work because apparently DynamicallyAccessedMembersAttribute is not public, aka internal. 
WTF ? 
I don't understand why this is, because according to the .NET Framework sources, it should be public in NetCore, isn't it ? 
VisualStudio also doesn't show me the namespace in IntelliSense. 
```
#if SYSTEM_PRIVATE_CORELIB
    public
#else
    internal
#endif
    sealed class [DynamicallyAccessedMembersAttribute]
```

This is the code for context: 

    using System;
    using System.ComponentModel;
    using System.Collections;
    using System.Diagnostics;
    using System.Globalization;
    using System.Reflection;
    
    namespace MigraDocCore.DocumentObjectModel.Internals
    {
        /// <summary>
        /// Base class of all value descriptor classes.
        /// </summary>
        public abstract class ValueDescriptor
        {
            public Type ValueType;

            internal ValueDescriptor(Type valueType)
            {
                this.ValueType = valueType;
            }

            public object CreateValue()
            {
                ConstructorInfo constructorInfoObj = ValueType.GetConstructor(Type.EmptyTypes);
                
                return constructorInfoObj.Invoke(null);
            }
            
            // [...]
        }
    }

If you need a project to reproduce, the git repository is 
https://github.com/ststeiger/PdfSharpCore/
and the csproj in question is MigraDocCore.DocumentObjectModel.

This is full source of the ValueDescriptor class:
https://github.com/ststeiger/PdfSharpCore/blob/master/MigraDocCore.DocumentObjectModel/MigraDoc.DocumentObjectModel.Internals/ValueDescriptor.cs#L58

I stress again, the warning only occurs if i set 
```
<IsTrimmable>true</IsTrimmable>
<EnableTrimAnalyzer>true</EnableTrimAnalyzer>    
```

I have now disabled the warning with 
```
<!-- fuck this shit -->
<EnableTrimAnalyzer>false</EnableTrimAnalyzer>    
```

So you need to set this to true again to reproduce the issue. 

### Reproduction Steps

Set 
```
<IsTrimmable>true</IsTrimmable>
<EnableTrimAnalyzer>true</EnableTrimAnalyzer>    
in the .csproj
```

If you need a project to reproduce, the git repository is 
https://github.com/ststeiger/PdfSharpCore/
and the csproj in question is MigraDocCore.DocumentObjectModel.

This is full source of the ValueDescriptor class:
https://github.com/ststeiger/PdfSharpCore/blob/master/MigraDocCore.DocumentObjectModel/MigraDoc.DocumentObjectModel.Internals/ValueDescriptor.cs#L58

I stress again, the warning only occurs if i set 
```
<IsTrimmable>true</IsTrimmable>
<EnableTrimAnalyzer>true</EnableTrimAnalyzer>    
```

### Expected behavior

Warning gone

### Actual behavior

Compile time error 
ValueDescriptor.cs(141, 42): [CS0122] 'Access to 'DynamicallyAccessedMembersAttribute' is not possible due to protection level.

### Regression?

No

### Known Workarounds

`<EnableTrimAnalyzer>false</EnableTrimAnalyzer>`

### Configuration

.NET Core 7, on Windows 10 X64 German. 
Visual Studio 2022. 

### Other information

Is it possible this is caused by build target NetStandard2.0 or netcorapp3.1 or netcore5 or netcore6 ?

**Comment by jasper-d** [comment]
Your project targets `netstandard2.0;netcoreapp3.1;net5.0;net6.0`.

`DynamicallyAccessedMembersAttribute` is only available in .NET 5+ [as is documented here](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-7.0#applies-to)

**Comment by vitek-karas** [comment]
Some explanation about the `DynamicallyAccessedMembersAttribute`: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/fixing-warnings#dynamicallyaccessedmembers

In your case the warning is basically saying:
The trimming tool can't guarantee that all types represented by the 'MigraDocCore.DocumentObjectModel.Internals.ValueDescriptor.ValueType' field will preserve public parameterless constructor.  If there's a type for which the public parameterless constructor was removed (because it was not seen being used) and that type makes it into that field, the behavior of the app will change (the `GetConstructor` would return `null` now).

The trimming needs to be able to statically determine if any given code in the app is used or not. Reflection APIs are problematic, since they can potentially access random parts of the code. So we added the `DynamicallyAccessedMembersAttribute` as a way to annotate `Type` values in the code with additional information. The annotation basically says - any type stored in the `Type` value needs to preserve "something" (methods, fields, constructors, ...). The tooling then checks that if you assign a value to such `Type` variable it can satisfy that requirement. In this case this is not true.

The way to fix this would be to add the attribute like this:
```C#
    public abstract class ValueDescriptor
    {
        [DynamicallyAccessedMembers(DynamicallyAccessedMemberType.PublicParameterlessConstructor)]
        public Type ValueType;

        internal ValueDescriptor([DynamicallyAccessedMembers(DynamicallyAccessedMemberType.PublicParameterlessConstructor)] Type valueType)
        {
            this.ValueType = valueType;
        }

        public object CreateValue()
        {
            ConstructorInfo constructorInfoObj = ValueType.GetConstructor(Type.EmptyTypes);
            
            return constructorInfoObj.Invoke(null);
        }
```

Now any callers to the .ctor or the field will need to do the same, unless they pass a specific type, like `typeof(MyType)` in which case the tooling will be able to fullfill the requirement by preserving the default .ctor on `MyType`.

As for the definition of the `DynamicallyAccessedMembersAttribute` type. It is only defined in .NET5 and above. If you need to also target your library to lower TFMs, you can either use ifdefs, or you can compile the attribute in (simple way is to copy the source file for it from the runtime repo: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/DynamicallyAccessedMembersAttribute.cs)

Some other info about annotating libraries for trimming: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

**Comment by vitek-karas** [comment]
C#/.NET doesn't allow attributes on local variables. The trimming tools perform full data flow analysis on all local variables, so the problem is not the local variable, but the value which is assigned to it, in this case the `attr.Type` - which is `DVAttribute.Type` property. Put the annotation there, since the code effectively requires all types assigned there to have default constructors.

I would expect the warning to actually contain information where the value came from (`DVAttribute.Type` property).

**Comment by ststeiger** [comment]
Doesn't work. 

```
<!-- fuck this shit -->
<EnableTrimAnalyzer>false</EnableTrimAnalyzer>    
```
