### ISSUE TITLE
[Analyzer suggestion]: Avoid recursive iterators

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#85015]
### Background and motivation

Recursive iterators perform poorly if used in a hot path, especially when the number of recursive calls is large.

Each call will allocate a new iterator state machine causing poor performance.

### API Proposal

Analyzer flags and recursive method that uses `yield return`

### API Usage

N/A

**Comment by stephentoub** [comment]
I don't think this is something we should be creating an analyzer for. Recursive use of iterators is a reasonable solution to various problems. Specific usage may be more problematic from a perf perspective, but the false positive rate would likely be too high.

**Comment by Youssef1313** [comment]
I thought in most cases there should be a way to re-write the code to be iterative? The rule could be made disabled by default though.

**Comment by stephentoub** [comment]
> I thought in most cases there should be a way to re-write the code to be iterative

Typically with other expenses and a much more complicated implementation.

**Comment by Youssef1313** [comment]
Yeah definitely agree the implementation would be more complicated. I think the false positives will essentially be "the performance benefit isn't good enough to complicate the code", but I assume that's what "disabled by default" rules are used for. The user then will have to decide when to suppress, when to fix, or whether to not enable the rule at all.

**Comment by stephentoub** [comment]
But it's an opinionated, broad reaching rule with no ability to auto fix nor the ability to even provide good guidance for what to do instead. It also can't catch what are arguably the worst offenses, those where the recursion happens because of consumptkon rather than in the implementation itself (eg Enumerable.Concat and in particular its old implenentation).

What examples are driving you to push this, and what would the analyzer recommend be done in those cases instead?

**Comment by Youssef1313** [comment]
> What examples are driving you to push this

I have (and previously had) such pattern in code, and it seems it's hurting perf in this case. It's a hot path.

> and what would the analyzer recommend be done in those cases instead?

as a codefix? I guess such analyzer can't have a codefix. There is probably no systematic way to re-write the code. The user should think of how to rewrite it.

---

> Off by default analyzers have to be incredibly valuable to be worth it, as they'll be enabled explicitly by very few people.

I have to say this analyzer suggestion is not "incredibly valuable". The cases where the suggestion is helpful are probably limited.

Feel free to close if this doesn't worth it.

**Comment by tannergooding** [comment]
> I have (and previously had) such pattern in code, and it seems it's hurting perf in this case. It's a hot path.

Scenarios such as this are really best identified by profiling and then adjusting the algorithm when it does come up. If it doesn't show up in the profiler then its potentially not worth spending the additional cycles to optimize.

Given that such an analyzer would need to be opt-in anyways, since its perf oriented and therefore optional, there's not a lot of benefit that many users will get out of it.

We can always revisit this in the future, but I tend to agree with Stephen that this isn't worth doing.
