### ISSUE TITLE
This operation is not supported on .NET Standard as Reflection.Emit is not available

### ISSUE THREAD

**Issue by emishura** [dotnet/runtime#85025]
### Description

Invoke CreateChannel on ClientBase falls error in standatd 2.0 
Message : This operation is not supported on .NET Standard as Reflection.Emit is not available. CallStack at 
```
System.Reflection.DispatchProxy.Create[T,TProxy]() at 
System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel) at 
System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel) at 
System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via) at 
System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via) at 
System.ServiceModel.ClientBase`1.CreateChannel() at System.ServiceModel.ClientBase`1.CreateChannelInternal() at 
System.ServiceModel.ClientBase`1.get_Channel() 
```
The installed packages:
System.ServiceModel.Primitives 4.10.2
System.Private.ServiceModel 4.10.2
System.ServiceModel.Http 4.10.2
System.Reflection.Emit 4.7.0
System.Reflection.DispatchProxy 4.7.1
System.Net.Sockets 4.3.0

UPD. As far as I can see this error is thrown by System.Reflection.DispatchProxy (DLL for .netstandard2.0). However this dll is referenced from System.Private.ServiceModel

### Reproduction Steps

generate proxy with SvcUntil in VS22. Try to invoke method -> exception is thrown

### Expected behavior

No exception is thrown

### Actual behavior

the exception is thrown

**Comment by mconnew** [comment]
This happens when you are using a runtime which doesn't support using packages which target netcoreapp2.0 but does support netstandard2.0. Basically the package has an implementation for netstandard2.0 which throws, and an implementation for netcoreapp2.0 which has the actual implementation. This was because netstandard2.0 doesn't have the APIs to use Ref.Emit but .NET Core 2.0 does.  
What runtime are you using? One of three things is wrong. 
1. The runtime you are using is missing a TFM in its search list when evaluation what pieces to get from a nuget package and the solution is to fix the TFM search list for that runtime.
2. This package might need updating to add a new TFM
3. The runtime you are using needs to provide its own implementation. This is what .NET Native did.

**Comment by StephenMolloy** [comment]
Nothing actionable. Closing.
