### ISSUE TITLE
netcore ignores client certificate when using TLS 1.2

### ISSUE THREAD

**Issue by pruebas7a** [dotnet/runtime#85077]
I am trying to communicate with a mutual authentication web service. 

When i use tls 1.1 it works perfectly but if i use tls 1.2 the certificate is ignored. i was able to see this with wireshark.

The certificate is valid, has private key and signature has algorithm is sha512RSA (i have tried other certificates with other signature algorithms like sha256 and is working fine)

**Comment by rzikm** [comment]
What is the OS and .NET version? Are you able to reproduce it with latest .NET 7?

Do you know what TLS stack is running on the server?

It will be hard to reproduce/debug issues without the above details. It would be best if you could create a self-contained repro (even using e.g. docker if necessary)

**Comment by pruebas7a** [comment]
Using Windows 10 pro
.NET 6.0 (also tried .NetFramework 4.7.2)
We need to use TLS 1.2 (forcing tls 1.1 works ok)
to reporduce

test certificate with openssl
openssl req -x509 -nodes -sha512 -days 365 -newkey rsa:2048 -keyout cert.com.key -out cert.com.crt
openssl pkcs12 -export -out certificate.pfx -inkey cert.com.key -in cert.com.crt

HttpClient tls hanshake Certificate Verify message is missing and Certificate message in zeros.

Edge browser tls handshake is completed ( https://sifen-test.set.gov.py/de/ws/consultas/consulta-ruc.wsdl?wsdl )

![image](https://user-images.githubusercontent.com/130100505/233435818-907393b9-8114-4d89-a8c5-c6f9a4b6d9da.png)

**Comment by pruebas7a** [comment]
An update: is the same issue with .NET 7.0

**Comment by wfurt** [comment]
make sure you client cert has (E)KU claiming it is client certs. And how do you set the certificate? Via properties or via callback? If you enable .NET tracing (or use https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace you should see logs about certificate selection)

**Comment by pruebas7a** [comment]
Yes it has EKU 
Client Authentication (1.3.6.1.5.5.7.3.2)
Server Authentication (1.3.6.1.5.5.7.3.1)
 
We are using multiples certificates for the tests and we have already analyzed and tested that the problem is not found in the methods of the ClientCertificateMiddleware.cs class. The problem seems deeper...

I just enable and got the .NET tracing but I don't understand where to look... can t find logs about certificate selection

**Comment by pruebas7a** [comment]
This is the client code, the firts post uses sha 512 certificate and the second uses a sha 256 certificate (the certificates were created with open ssl as mentioned above)

        string url = "https://sifen-test.set.gov.py/de/ws/consultas/consulta-ruc.wsdl";
        string soapUI = "some string";
        var mediaType = "application/soap+xml";
        var content = new StringContent(soapUI, Encoding.UTF8, mediaType);
        var handler = new HttpClientHandler();
        handler.ClientCertificateOptions = ClientCertificateOption.Manual;
        handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
        handler.ClientCertificates.Add(new X509Certificate2("certificate512.pfx", "password"));
        var httpClient = new HttpClient(handler);
        var response = httpClient.PostAsync(url, content).Result;
        response.EnsureSuccessStatusCode();
        var responseBody = await response.Content.ReadAsStringAsync();
        var handler2 = new HttpClientHandler();
        handler2.ClientCertificateOptions = ClientCertificateOption.Manual;
        handler2.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
        handler2.ClientCertificates.Add(new X509Certificate2("certificate256.pfx", "password"));
        var httpClient2 = new HttpClient(handler2);
        response = httpClient2.PostAsync(url, content).Result;
        response.EnsureSuccessStatusCode();
        responseBody = await response.Content.ReadAsStringAsync();

The wireshark capture for the firts post:
![image](https://user-images.githubusercontent.com/130100505/234364110-2221ec8a-8f89-48ef-be0e-2bc14025aadb.png)

The wireshark capture for the second post:
![image](https://user-images.githubusercontent.com/130100505/234364755-94099208-2c96-4d7a-87d1-2ea163a80511.png)

this one includedes certificate message and the Certificate Verifiy message is sent

Here is more detail from the Certificate Request message of the server:
![image](https://user-images.githubusercontent.com/130100505/234365022-945279e0-fb80-4915-be07-d9c19f83d237.png)


I need help to find the reason why, .net is not selecting the sha 512 certificate to comunicate with this particular server

**Comment by rzikm** [comment]
Triage: we should investigate in 8.0 timeframe.

**Comment by wfurt** [comment]
The reason is in the posted picture. The server advertise support for `rsa_pkcs1_sha256` but not for `rsa_pkcs1_sha512`.
So the schannel does not send the cert. I tested same .NET code on Ubuntu with OpenSSL and OpenSSL seems to ignore the hints - probably same way as Edge does. But that seems incorrect behavior. I set up simple server on Windows and that advertise `sha512` by default and everything works as expected. So the server seems to limit the algorithms on purpose or does not have support for the stronger algorithm. I think if you want to make it work you will either need to use `sha256` or update the server (if possible) 

BTW the openssl commands above do not set any EKU so there is still some discrepancy between the claims about EKU and used command.

**Comment by mconnew** [comment]
@wfurt, I found [this interesting piece](https://learn.microsoft.com/en-us/windows-server/security/tls/tls-schannel-ssp-changes-in-windows-10-and-windows-server#changes-to-windows-tls-adherence-to-tls-12-requirements-for-connections-with-non-compliant-tls-clients) of information about how later versions of Windows don't strictly honor the signature_algorithm RFC due to other platforms not doing so. I believe this is what Edge and OpenSSL are doing. I think there's a good argument for being more loose with the algorithm requirements in .NET using SCHANNEL.  
As for not setting any EKU, the spec says if there's no EKU listed, then that's equivalent to saying it's suitable for all usages.

**Comment by wfurt** [comment]
The negotiation is out of our hands as far as I can tell e.g. it is not .NET doing filtering. The article is related but it talk about server. I'm not sure if same loose logic apply when selecting client certificate. It seems like the right fix is to use certificate with algorithm server is claiming to support. Doing otherwise seems path to troubles to me.

**Comment by mconnew** [comment]
@wfurt, that was my initial thoughts too until I came across that documentation. To me the relevant facts are:  
1. Windows has loosened this constraint on the server side because that's what everyone else was doing and it's better for interop. The Windows team wouldn't do this if it broke security.
2. Microsoft Edge is using a looser constraint too. Are they using SCHANNEL? I think Chrome doesn't, but have Edge changed that? If Edge is using SCHANNEL, then there's a way to do it with SCHANNEL so it's within the scope of SslStream to do something different.
3. .NET on Linux uses OpenSSL which uses the looser constraint and having different behavior on different platforms is less than ideal.
4. The OpenJDK implementation of TLS also supports a looser constraint.
5. It doesn't weaken security as ultimately it's just a hint and it's up to the server to decide whether to accept it once sent. It's purely an attempt to reduce wasting time if you won't accept certain certificates. But this whole mechanism has been made ineffective by multiple implementations not stating what their real requirements are and accepting things different than specified.

If there isn't a way to do this with SCHANNEL, then I think the .NET team should start a discussion with the Windows team that owns SCHANNEL pointing out the multiple precedents in OpenSSL, Edge, and OpenJDK. It doesn't help this specific case, but it improves things going forward in the future.
