### ISSUE TITLE
Warning for ArgumentNullException.ThrowIfNull when passing a struct

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/runtime#85154]
### Describe the problem you are trying to solve

Passing a struct to `ArgumentNullException.ThrowIfNull` makes no sense and would only happen accidentally. The developer should be warned about this.

### Describe suggestions on how to achieve the rule

The analyzer would check the type of the value being passed and emit a warning if it is a struct. A code fix could remove the entire invocation.

**Comment by gfoidl** [comment]
Just noting: the JIT will [dead code eliminate](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4aNAMQihAG2W9lMBgBNxudTDm0AzAzIMAYhAgMA3jQYOG9xwG0AUuIwBxGCJhRxMAAKDABPDhgIADMg8TEASniAXWcHd08fPwDgsIjo2LEAfkSU6kdTEziMBgAhdgAeABUAPiDGhgA3bGV4pzLHO37yhwBBKABzISkxADkVZQBRBDAYDgkIET5GligIAHcASSi51SCuntkh4dTh4gB2BhRSS/KAXxpXoA=) the case when a non-nullable struct is passed to `ArgumentNullException.ThrowIfNull`.

> Passing a struct to `ArgumentNullException.ThrowIfNull` makes no sense

Well, there's a legit case for passing a struct in. Namely `Nullable<T>` (is a struct) like `int?`, and so on.
So that analyzer should check for non-nullable structs (for JIT see above).

**Comment by CollinAlpert** [comment]
Right, I had forgotten about `Nullable<T>` that should be excluded, of course.

**Comment by bartonjs** [comment]
Looks good as proposed.

For non-nullable struct types it should be

Category: Reliability
Level: Warning

For nullable struct types it should be a different diagnostic ID

Category: Performance
Level: Info

**Comment by buyaa-n** [comment]
Update: it was revisited while discussing another analyzer and changed to `Usage`
