### ISSUE TITLE
[8.0.100-preview.4.23223.1] IEnumerable<T>.Current throw System.InvalidOperationException when IEnumerable<T> collection is empty

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#85243]
### Description

**When run the PKHeX  with the latest .NET 8 Preview4 runtime,  IEnumerable<T>.Current throw System.InvalidOperationException when IEnumerable<T> collection is empty .**
**GitHub Site:**: https://github.com/kwsch/PKHeX 
**Or App Location checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1807725

### Reproduction Steps

**Minimal Repro steps:**

1.Create a default .NET 7.0 Console app.

2. Add following code to Program.cs file.

```
internal class Program
{
    private static void Main(string[] args)
    {
        IEnumerable<string> extra = new List<string> {  };
        var enumerator = extra.GetEnumerator();
        while (enumerator.Current == null)
        {
        }
        Console.WriteLine("Hello, World!");
    }
}
```
3. Build the project.

4. Open the runtimeconfig.json file to change the runtime version to let the app run against 8.0.100-preview.4.23223.1:
```
 "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0-preview.4.23221.1"
    }
```
5. Launch the app.

### Expected behavior

App will output "Hello World!" in console window.

### Actual behavior

Following exception will be thrown on "enumerator.Current":
System.InvalidOperationException: 'Enumeration has not started. Call MoveNext.'

**Stack Trace:**
   at System.ThrowHelper.ThrowInvalidOperationException_EnumCurrent(Int32 index) in /_/src/libraries/System.Private.CoreLib/src/System/ThrowHelper.cs:line 479
   at System.SZGenericArrayEnumerator`1.get_Current() in /_/src/libraries/System.Private.CoreLib/src/System/Array.Enumerators.cs:line 134
   at Program.Main(String[] args) in C:\Users\v-weiwc\source\repos\WinFormsApp1\ConsoleApp1\Program.cs:line 8

### Regression?

Yes
**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-7.0.202-win-x64: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk- 8.0.100-preview.2.23121.12: Pass
3).  Windows 10 21H2 AMD64 + dotnet-dotnet-sdk-8.0.100-preview.2.23124.7: Fail
9). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.4.23223.1: Fail

### Configuration

**Application Name**: PKHeX 
**OS**: Windows10 21h2
**CPU**: x64

### Other information

**Findings:**

When replace IEnumerable<string> to List<string>, the exception gone.
If the extra list in demo is not empty, the exception gone.

@dotnet-actwx-bot @dotnet/compat

**Comment by stephentoub** [comment]
This code is invalid. It is undefined behavior to use an enumerator's Current without calling MoveNext first.

**Comment by huoyaoyuan** [comment]
The `foreach` loop basically lowers to:

```csharp
while (enumerator.MoveNext())
{
    var item = enumerator.Current;

}
```

**Comment by Junjun-zhao** [comment]
> This repro code is invalid. It is undefined behavior to use an enumerator's Current without calling MoveNext first.
> 
> It's not clear to me how the repro relates to the cited app. Where does the app do the above invalid pattern?
**code link :** https://github.com/kwsch/PKHeX/blob/d4d353c087f840b40627575f56db319e3b7d7551/PKHeX.WinForms/Subforms/SAV_FolderList.cs#L265

@stephentoub Thanks for your explanation. Because it's passed with 8.0.100-preview.2.23121.12 but the latest 8.0 version fails with, is there a behavior change? If yes, could you share us the breaking changes link? We will communicate it with App owners about this change.

**Comment by stephentoub** [comment]
This wasn't a breaking change resulting in breaking change documentation.  Accessing `Current` before calling `MoveNext` has been called out as erroneous usage since .NET Framework 1.0 :-)
https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current
"[Current](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current) is undefined under any of the following conditions:
 The enumerator is positioned before the first element in the collection, immediately after the enumerator is created. [MoveNext](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.movenext) must be called to advance the enumerator to the first element of the collection before reading the value of [Current](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current).

`List<T>` was changed to use the same enumerator as `T[]` when the list is empty, and `T[]`'s enumerator already threw in this situation.
https://github.com/dotnet/runtime/pull/82499

**Comment by Junjun-zhao** [comment]
@stephentoub Thanks for sharing the document and the detailed explanation for the usage for the Current property.
In previous versions, including .NET Framework, if we access Current before calling MoveNext, Current value is NULL.
But starting from .NET 8, it throws System.InvalidOperationException: 'Enumeration has not started. Call MoveNext.' exception, is this an expected behaviour?

**Comment by eiriktsarpalis** [comment]
Calling `Current` before `MoveNext` is undefined, therefore either `null` or an exception is acceptable depending on the particular enumerator implementation you're using.

**Comment by stephentoub** [comment]
> if we access Current before calling MoveNext, Current value is NULL.
But starting from .NET 8, it throws System.InvalidOperationException:

Now try it with other collections, like T[].

**Comment by stephentoub** [comment]
> I think we should focus on answering that question.

@Junjun-zhao answered by supplying that "code link", the GitHub formatting just made it hard to see that it was the answer rather than the question.  The app is doing this:
```C#
        var enumerator = saves.GetEnumerator();
        while (enumerator.Current == null)
        {
            if (!enumerator.MoveNext())
                return list;
        }
```
which is wrong and presumably only happens to work in the app because they only call it with a `List<string>` that happens to not throw for this undefined behavior.  If that `IEnumerable<string> saves` were instead a `string[]`, a `Queue<string>`, a `Stack<string>`, etc., it would be throwing just as `List<string>` now is (again, as an implementation detail of undefined behavior).

**Comment by PriyaPurkayastha** [comment]
My bad, I didn't see the link. Thanks @stephentoub, we will mark this as an app issue and let the app owners know.

**Comment by Junjun-zhao** [comment]
Thank you everyone, we have marked this app as an application issue and notified the app owners.
