### ISSUE TITLE
"You must download or install .NET" task dialog repeatedly doubles in size on 200% DPI systems

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#85571]
### Description

Each time you click "See details"/"Hide details," the dialog doubles in width and height until it is even blocking the task bar from view and no buttons can be seen on the screen.

(Give the gif time to load; it's very large, so it will start repeating before the whole loop is downloaded)

![taskdialog resize bug](https://user-images.githubusercontent.com/8040367/235367678-208724b1-e1c3-470f-86d4-18a5ee5e7bd6.gif)

This task dialog UI was added in #78087 by @elinor-fung.

### Reproduction Steps

On a system set to 200% DPI (maybe other percentages too), run a .NET app that requires a version of the .NET runtime that is not installed.

### Expected behavior

Minimal size change needed to show and hide the extra content.

### Actual behavior

See description and screenshot above.

**Comment by jnm2** [comment]
Would modes other than `DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2` potentially work around the problem without accepting blurriness?

**Comment by RussKie** [comment]
Maybe @dreddy-work can help with guidance.

**Comment by dreddy-work** [comment]
I see task dialog used here is native one. @elinor-fung, i see two statements from you contradicting each other above. Do you see this issue irrespective of setting thread's  DpiAwareness?  or Only when you try to set threads DpiAwareness to any of these modes?

Why not set application DpiAwareness to PermonV2 instead of just for this dialog? was that not an option?

**Comment by huoyaoyuan** [comment]
> Why not set application DpiAwareness to PermonV2 instead of just for this dialog's thread? was that not an option?

If I'm understanding correctly, the dialog happens when the framework required by the application is missing. The application's manifest isn't owned by the host that shows the dialog.

**Comment by elinor-fung** [comment]
This is only happening when we set the thread's DPI awareness to the *_AWARE modes.

@huoyaoyuan is spot on about why we don't do it at the application level.

I confirmed with folks that this is an issue in Windows. This happens when window animations are on (system-wide setting). Setting `DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED` is a potential workaround - with some additional testing for possible clipping with GDI scaled at different DPIs.

**Comment by elinor-fung** [comment]
It is also only an issue when the thread and process are using different DPI awareness contexts, so it may sense to just leave it using whatever the process is using (so if the developer set DPI awareness in their manifest, it will be non-blurry and if they didn't it will be blurry at high DPI).

**Comment by dreddy-work** [comment]
> so it may sense to just leave it

Agree.

**Comment by elinor-fung** [comment]
We have made the host setting the DPI awareness. It is left to the developer to specify DPI awareness in their manifest if desired - the dialog shown will just use the application's setting.

Windows has also fixed the issue on their side for future releases of the OS. Thanks for reporting this!

**Comment by huoyaoyuan** [comment]
> Windows has also fixed the issue on their side for future releases of the OS.

I've also seen some similar issues on Qt-based applications. Surprisingly it's actually Windows' fault.
