### ISSUE TITLE
Test Failure - `jit64_do.0.1`

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#85590]
[Link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257442&view=logs&j=6dfec640-5b96-5d95-2a5b-7c236ea2d5c5&t=caa3e910-40a5-5f97-2688-844d50a74012)

runtime-coreclr gcstress0x3-gcstress0xc

```
18:35:36.365 Running test: JIT/jit64/regress/ddb/87766/ddb87766/ddb87766.cmd
App Exit Code: 259
Expected: 100
Actual: 259
END EXECUTION - FAILED
FAILED
```

**Comment by BruceForstall** [comment]
@TIHan Please include a link to the failure pipeline and indication of which configuration failed.

In this run:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=257442&view=ms.vss-test-web.build-test-results-tab

I see all the failures are in jit64 tests with GCStress=3.

Most are timeouts (@markples -- more GCStress timeouts in merged groups)

win-x64 failure is:
```
18:46:40.734 Running test: JIT/jit64/regress/vsw/610378/vsw610378/vsw610378.dll
SMALL FRAME SIZE - STATIC
   farg1=1.1 farg2=2.2 expecting 1.1 and 2.2
   bs.f1=1.1 bs.fx=2.2 expecting 1.1 and 2.2
LARGE FRAME SIZE - STATIC
   farg1=1.1 farg2=2.2 expecting 1.1 and 2.2
App Exit Code: 259
Expected: 100
Actual: 259
END EXECUTION - FAILED
FAILED
```

perhaps that's also a symptom of timeout, since it's the last test run?

**Comment by TIHan** [comment]
Sure, will do.
