### ISSUE TITLE
dotnet.exe: Need a specific error message when running a .dll of the wrong bitness

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/runtime#85691]
### Description

If we use the 64-bit dotnet.exe on Windows to run a .dll that has PlatformTarget=x86 the experience is:

![image](https://user-images.githubusercontent.com/679326/235808492-0c66a3a0-7a60-418f-aa44-b793c3913e58.png)

```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\temp\net60\bin\Debug\net6.0\net60.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\temp\net60\bin\Debug\net6.0\net60.dll'
```

We need a more specific error message here, such as:
`Could not run net60.dll because it is 32-bit, but the current dotnet.exe is 64-bit. Consider using the 32-bit dotnet.exe, the apphost .exe or use dotnet run to run the application.`
And same for vice versa (or come up with a single clear error message that works both ways).

But the current error message is not informative and leaves the user guessing what specifically is wrong with the assembly format.

### Reproduction Steps

On Windows,

`dotnet new console`, replace the .csproj with this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget> 
  </PropertyGroup>

</Project>
```

build, 
cd bin\Debug\net60 (or whatever), run via `dotnet net60.dll`, such that dotnet.exe resolves to the 64-bit runtime.

### Expected behavior

Should clearly indicate that it failed because of the bitness mismatch.

### Actual behavior

Gives a generic error that's not helpful

### Regression?

not a regression

### Known Workarounds

Use the .exe, the matching dotnet.exe or use dotnet run if source is available

### Configuration

Windows, .NET 7, 64-bit runtime (but 32-bit assembly)

**Comment by vitek-karas** [comment]
I'm curious about the scenario where this happens.
From my experience, most people use the executable to run the apps - so `app.exe` which will always match. I rarely see people invoke `dotnet app.dll` manually. It's possible that it's common in scripted scenarios and such, but then in that case I imagine it's not very common to get a mismatch (it's less likely to get the wrong `dotnet.exe`).

That said, I agree the exception could be improved. The question is if we need a specific message for the application dll, or if it's good enough to improve the message for all assembly loads which hit the bitness mismatch. Having a special message for the application is obviously more complex and will hit lot of corner cases where it won't work well (cases which don't run the app the normal way for example).

**Comment by KirillOsenkov** [comment]
I think it’s good enough to improve the message for all assembly loads with bitness mismatch. As soon as bitness is mentioned it immediately becomes vastly more useful. No need to tailor it to the entry point.

**Comment by danmoseley** [comment]
Was going to open this then I found this existing issue.

This comes up fairly often as a result of installation mismatches. Eg in the dotnet/vscode-csharp repo, there are [numerous hits ](https://github.com/search?q=repo%3Adotnet%2Fvscode-csharp+0x8007000B&type=issues) and generally because it wasn't clear from the message that there was an attempt to load code for arm64 into an x64 SDK, or x64 into x86, etc.

eg https://github.com/dotnet/vscode-csharp/issues/5700  "The issue is the arm64 build of the extension will not work with a x64 SDK. Try uninstalling and installing a arm64 build instead."

https://github.com/dotnet/vscode-csharp/issues/5256 "Typically we see this issue with M1 Macs that have a x64 SDK installed instead of the arm64 build"

https://github.com/dotnet/vscode-csharp/issues/5235 "It appears you have the x86 SDK folder (C:\Program Files (x86)\dotnet) before the x64 SDK folder (C:\Program Files\dotnet) in your environment PATH. To fix this issue, update your System Environment PATH by removing the x86 folder."

I was trying to figure out exactly the situation when this occurs. I assumed it was when you try to mix architecture in R2R binaries. But 

seems to [come from here](https://github.com/dotnet/runtime/blob/d0c25155a46d5b1955189a64df1c1c53e3e6b2c8/src/coreclr/binder/assemblybindercommon.cpp#L139-L186) where it's essentially validating the flags are valid. That causes this message `ERROR_BAD_FORMAT, W("An attempt was made to load a program with an incorrect format.`

Mismatches of the R2R image are caught by a XOR of the OS mask [checked here](https://github.com/dotnet/runtime/blob/d0c25155a46d5b1955189a64df1c1c53e3e6b2c8/src/coreclr/vm/peassembly.cpp#L45-L61) which fails with `IDS_CLASSLOAD_WRONGCPU                  "Could not load file or assembly '%1'. This assembly was compiled for a different processor."`

My suggestion is to simply improve the hard coded string(s) to give more clues. It would be nice to have more specific messages, more info etc but that should not stop us in the short term just making the messages more suggestive so more people can self diagnose.

@vitek-karas if you can help clarify what leads to these messages specifically maybe we could take a crack at adjusting the strings

**Comment by danmoseley** [comment]
for completeness, BadImageFormatException can also be thrown from managed, eg from metadata reading, but it has the string `Format of the executable (.exe) or library (.dll) is invalid.` and isn't what's causing these reports above.

**Comment by vitek-karas** [comment]
@elinor-fung will know much better than me what to tweak and where.

**Comment by elinor-fung** [comment]
That hard-coded message is made to match the Windows `ERROR_BAD_FORMAT` error code and message. We'd want to [define a new resource](https://github.com/dotnet/runtime/blob/main/src/coreclr/dlls/mscorrc/mscorrc.rc) with the tailored message.

`AssemblyBinderCommon::IsValidArchitecture` does the architecture check:
https://github.com/dotnet/runtime/blob/d0c25155a46d5b1955189a64df1c1c53e3e6b2c8/src/coreclr/binder/assemblybindercommon.cpp#LL1311C43-L1311C43

The callers of interest that explicitly return `ERROR_BAD_FORMAT`:
1. https://github.com/dotnet/runtime/blob/56c427bb4d3321d8bb5cb7600d37237176ad5970/src/coreclr/binder/defaultassemblybinder.cpp#L129-L132
2. https://github.com/dotnet/runtime/blob/56c427bb4d3321d8bb5cb7600d37237176ad5970/src/coreclr/binder/customassemblybinder.cpp#L120-L123
3. https://github.com/dotnet/runtime/blob/56c427bb4d3321d8bb5cb7600d37237176ad5970/src/coreclr/binder/assembly.cpp#L48-L52

In all three cases, the expected error behaviour is a returned HRESULT rather than throwing, so they might need a new [custom error code](https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/corerror.xml).

(1) and (2) should be the path for doing something like running the main .dll (`dotnet <dll>`) or loading from a path (`AssemblyLoadContext.LoadFromAssemblyPath`).

(3) would be loading by assembly name, where the assembly is found in [default probing](https://learn.microsoft.com/dotnet/core/dependency-loading/default-probing). The added complication there is that we continue with other resolution steps (for example, extension points), so I'm not sure how/if the error from the default probing is propagated.

I think (1) and (2) would cover the scenario in this issue description and the examples from the vscode-csharp repo.

**Comment by danmoseley** [comment]
> AssemblyBinderCommon::IsValidArchitecture does the architecture check:

Ah - yes I misread that a switch not #ifdefs.

Is the change you suggest something your team might consider doing?

**Comment by elinor-fung** [comment]
Definitely agree it is an improvement we should do - at least for the dotnet <dll> / load from path case. I think it is more a matter of sitting down and spending the time to go through it. (And of course, if anyone else is feeling like tackling it, we'd be grateful and happy to help.)
