### ISSUE TITLE
RequiresDynamicCode based on interface implementation

### ISSUE THREAD

**Issue by weifenluo** [dotnet/runtime#85829]
Given the following generics method based on interface implementation:

```
// In most cases, source generator will generate this interface implementation
public interface IWithEntityTypeDescriptor<T>
{
    EntityTypeDescriptor<T> Descriptor { get; }
}

void Initialize<T>(T entityType)
{
    if (entityType is IWithEntityTypeDescriptor<T> withTypeDescriptor)
    {
        var typeDescriptor = withTypeDescriptor.Descriptor;
        ... // go with code path without reflection to initialize entityType object
    }
    else
    {
        ... // use reflection to initialize entityType object
    }
}
```

Currently, to make the library trimmable, a `RequiresDynamicCode` attribute should be applied to above `Initialize` method. In order to trim reflection at all, an additional API must be added:
```
void Initialize<T>(T entityType, EntityTypeDescriptor<T> typeDescriptor)
{
    ... // go with code path without reflection to initialize entityType
}

[RequiresDynamicCode]
void Initialize<T>(T entityType)
{
    ...
}
```

I don't feel very comfortable that I need to add the API just for trimming support. Is it possible to add some configuration param to existing `RequiresDynamicCode` attribute so that the analyzer can determine whether code should be trimmed. Or maybe we can provide some mechanism writing custom attribute to extend the analyzer?

**Comment by vitek-karas** [comment]
The analysis of this would be relatively complicated. The analyzer would have to figure out that the condition (whatever it would look like) on the attribute matches the condition in the code and trim away the reflection only branch - without this the app would still carry the reflection based code which is incompatible.

On top of that, the analysis actually happens in two places, there's a Roslyn analyzer, but there's also the NativeAOT compiler which performs the same analysis, so both would need to be able to handle this case. This is the main reason why having some way to customize the "analyzer" logic is very difficult, since the two analysis engines operate on very different things (one operates on the Roslyn AST, the other on top of IL).

The best solution is to express the difference in the language. In this case it might be possible to do something like this:

```C#
// In most cases, source generator will generate this interface implementation
public interface IWithEntityTypeDescriptor<T>
{
    EntityTypeDescriptor<T> Descriptor { get; }
}

void Initialize<T>(IWithEntityTypeDescriptor<T> entityType)
{
        var typeDescriptor = withTypeDescriptor.Descriptor;
        ... // go with code path without reflection to initialize entityType object
}

void Initialize<T>(T entityType)
{
    ... // use reflection to initialize entityType object
}
```

But I don't know if the compiler will be clever enough to pick the right overload automatically.

Question: You discuss adding `RequiresDynamicCode`, but that attribute is about AOT compatibility. At the same time you mention that you're trying to make the library trim compatible - if the code has trim related issues, then it should use `RequiresUnreferencedCode` instead. It's possible that it has both trim and AOT incompatibilities, in which case it might need both attributes.

@agocke @eerhardt @sbomer for ideas?

**Comment by weifenluo** [comment]
First thanks for the clarification regarding AOT/trimming compatibilities, I thought they are same thing.

The `Initialize` method code are provided just for demonstration purpose, the real situation is far more complex. So I can't expect the compiler will be smart enough to pick the right overload. For example, there are following public API cannot be resolved during compile time without adding new signature:

```
public Entity<T> Entity.Create<T>() where T : class, new()
{
    T entityType = new T();
    Initialize(entityType);
    ...
}

public EntitySet<T> EntitySet.Create<T>() where T : class, new()
{
    T entityType = new T();
    Initialize(entityType);
    ...
}
```

The problem is AOT/trimming thing is propagating through all the calling chain, result in mess up with API design.

Is it possible to handle this at assembly level? For example, there is a compiler switch `IsAOTEnabled`, and there are two DLLs distributed within a nuget package, say `Lib.dll` and 'Lib.AOT.dll`.

In `lib.dll`, the methods are annotated with `RequiresDynamicCode` and/or `RequiresUnreferencedCode`;

In `lib.AOT.dll`, the method is implemented to throw exception when reflection required:

```
void Initialize<T>(T entityType)
{
    if (entityType is IWithEntityTypeDescriptor<T> withTypeDescriptor)
    {
        var typeDescriptor = withTypeDescriptor.Descriptor;
        ... // go with code path without reflection to initialize entityType object
    }
    else
    {
        throw new NotSupportedException();
    }
}
```

The compiler can automatically select the assembly based on the provided switch.

**Comment by vitek-karas** [comment]
> The problem is AOT/trimming thing is propagating through all the calling chain, result in mess up with API design.

In some cases, making the library fully trim compatible requires API changes, because the existing API behaviors are relying on reflection/dynamic behavior. This is unfortunate but expected and in the general case there's little anybody can do about it. We're trying to add new mechanisms how to hide this from the users though - typically this can be solved with source generator and some clever mechanism of hooking it up - ideally it would not require any code changes from the user, currently that's unfortunately rarely the case still.

Regarding your idea with AOT specific assemblies:
Long time ago we decided against having different assemblies for these additional publishing modes (trimming, AOT, single-file, ...). Instead we use runtime checks. At runtime, we check for a given capability and choose the right path through the code. Note that there are two cases here:
* Checks which simply switch to use a different implementation of the same functionality - for example RegEx will check if dynamic code compilation is supported, and if so, it will allow use of Ref.Emit to precompile the regex. If it's not supported it will transparently fall back to the "interpreter" implementation. This doesn't change the functional behavior, only performance characteristics are affected.
* Checks which change the functional behavior - typically they cause certain scenarios to not work at all. 

So far we're trying to separate all trim/AOT compatibility issues into these two camps. If the API can work, just needs different implementation we will have a runtime check and transparently switch the implementation (like RegEx). If there's no way to make the API work we typically add a [feature switch](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md), for example recently we've added `System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault` which disables the reflection based serialization implementation (and will fail unless everything used source generation).

Note though that we try to add some kind of warning if the disabled implementation were to be used - so for example in the above case, using the non-source-generator based APIs for System.Text.Json will still produce warnings (uses `RequiresUnreferencedCode` attributes to achieve that).

The main idea behind trimming/AOT is that it will not change the behavior of the app - and if it can't guarantee that, the tooling will produce warnings instead. Feature switches are a way to get the same behavior with/without trimming/AOT for cases where we had to disable some functionality. This helps with predictability - the application behaves the same in Debug builds and trimmed/AOT release builds - because the feature switches disable the relevant functionality even in Debug builds (were technically it could still work).

In your case above there are generally two options I can think of:
* Change the public APIs such that it's possible to use trim/AOT compatible code without any warnings, feature switches, ... The upside is that newly authored code can target the new APIs and not have any issues. The downside is that it requires API changes (they don't need to be breaking necessarily).
* Don't change public APIs and instead use something like a feature switch to disable the unsupported functionality. This is arguably still an API change, since you're changing the behavior of the API (in a breaking way), but it's opt-in.

There are some limitations for the second approach:
* Currently we don't have an existing generic "AppIsTrimmed" feature switch in the system - and we don't plan to add one. So you would need to add a new feature switch into your library.
* There's no good way to annotate these APIs for warnings currently. We've had a long discussion about this, but so far could not find a good solution. Technically with the feature switch the APIs don't need `RequiresUnreferencedCode`, but without them there's no indication that they change behavior based on trimming. This is not a problem for application code, but it can be a problem if your APIs are used from another library - as the author of the library will have no way of knowing that the API will change behavior.

**Comment by weifenluo** [comment]
Just back to work after taking couple of days off.

It seems feature switch is the right direction for me because I really don't want to mess up with the whole API design. To better understand feature switch, I took some time reading source code related to `System.Text.Json.IsReflectionEnabledByDefault` as suggested. Taking `JsonSerializationOptions.GetConverter` as example:
https://github.com/dotnet/runtime/blob/9e49620aeee78c0d37dd741f88aff89850a6f5fb/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L39-L56

`JsonSerializationOptions.GetConverter` is annotated with `[RequiresUnreferencedCode]` and `[RequiresDynamicCode]`, and in the method implementation, a test of `IsReflectionEnabledByDefault` value to determine whether reflection converters will be resolved. I'm a bit confused here: I'm expecting when `IsReflectionEnabledByDefault` is `false`, the whole reflection code path should/will be trimmed (the feature switch turned off the feature), but it appears this is not the case: the  `[RequiresUnreferencedCode]` and `[RequiresDynamicCode]` populates to any user code uses `JsonSerializationOptions.GetConverter`, no matter the value of `IsReflectionEnabledByDefault` is. If this is what you mean in:

>There's no good way to annotate these APIs for warnings currently. We've had a long discussion about this, but so far could not find a good solution. Technically with the feature switch the APIs don't need RequiresUnreferencedCode, but without them there's no indication that they change behavior based on trimming. This is not a problem for application code, but it can be a problem if your APIs are used from another library - as the author of the library will have no way of knowing that the API will change behavior.

I don't understand how come "This is not a problem for application code". Am I missing anything here? I guess we need some extra annotation such as `[ConditionallyRequiresUnreferencedCode("IsReflectionEnabledByDefault", true)]`, which can specify the feature switch here, and the linker can properly trim the code based on feature switch.

**Comment by vitek-karas** [comment]
The `JsonSerializer.IsReflectionEnabledByDefault` might not be the best example. Turning it off doesn't make the System.Text.Json code trim compatible. One can still enable the reflection-based code by explicitly referencing some of the public APIs which require it. It's basically a workaround to a "turned on by default" problem - using the default APIs one can get a serializer which has the reflection based enabled in it (by default) - the feature switch is to change that behavior - mostly for size reasons. Our recommendation for this API is still to only use the APIs which are trim compatible by design (and some of them were added for that reason). The feature switch is added for cases where it's highly impractical and that callsite will have to suppress the warning and we've spent considerable effort to make sure it's still trim compatible (and we're still nervous about it, since it's really hard to prove correctness without the tools).

That said, I agree that there are scenarios where if you don't change the public API there's no good way to annotate the API currently (as already mentioned above). In general, we strongly suggest people to consider changing public APIs to be more trim/AOT compatible. No matter what we do, there will always be cases where the tooling won't be able to figure it out, so not relying on that is always better - making it compatible "by design".

> I don't understand how come "This is not a problem for application code". 

Let's say the above `GetConverter` API didn't have `RequiresUnreferencedCode` on it. If it's used in an application which turns off `IsReflectionEnabledByDefault`, the tooling will not generate any warning. If it's used in an application which leaves `IsReflectionEnabledByDefault` on, the tooling will generate a warning (the call to `DefaultJsonTypeInfoResolver.GetConverterForType` will warn since that method as `RequiresUnreferencedCode` on it). So, if one is building an application, the attribute on the `GetConverter` is not necessary, the behavior will be correct in all cases.

But there's a problem when building libraires. Now let's assume I'm an author of some NuGet library and I use JSON serialization to for example read files (or something). I add code which calls `GetConverter` into my library. If there's no attribute on that method, I will not get any warnings from the analyzer. And when I build and test my library, I will not get any warnings either (trimmer doesn't run in these cases). So even if I'm aware of trimming, and enabled the trimming analyzer for my library, I have no idea that `GetConverters` is trim incompatible potentially and that I should not call it. The only way to learn that is to have a specific trim test as part of my libraries test suite (which would run trimmer and thus show the warning).

That is why I said that for applications this is not a problem, and we could leave the attribute missing, but for libraries it is.

> I guess we need some extra annotation such as [ConditionallyRequiresUnreferencedCode("IsReflectionEnabledByDefault", true)], which can specify the feature switch here, and the linker can properly trim the code on compile time.

You're correct that to make this scenario work we need something new - attribute, or some other mechanism. We've already discussed this several times and so far, didn't come up with something which would sound good unfortunately.

*Note: the linker will properly trim the code regardless of the attribute, the `RequiresUnreferencedCode` has no effect on actual trimming, it only has effects on warnings.*

**Comment by weifenluo** [comment]
@vitek-karas Thank you so much for your patience and very helpful explanations!

There were two things I didn't know:
1. The `RequiresUnrefencedCode` has no effect on actual trimming, it only has effects on warnings. I thought ILLink trimmer relies on it;
2. The value of feature switch is respected by tooling/trimmer. I thought I need to replace the method with exception throw in `ILLink.substituions.xml` to break the calling chain into reflection.

Here comes to the solution of my scenario:
1. Add a feature switch `TrimmableWithoutReflection` with default value `true`, and a `[RequiresDescriptorWhenTrimming]` attribute which conceptually equals to `[ConditionallyRequiresUnreferencedCode("TrimmableWithoutReflection", false)]` as I proposed;
2. Add `[UnconditionalSuppressMessage]` to `Initialize<T>` method to eliminate ILLink analyzer warning, and add `[RequiresDescriptorWhenTrimming]` attribute to `Initialize<T>` method and all subsequent caller(s) such as `Entity.Create<T>` and `EntitySet.Create<T>`;
3. An additional custom analyzer distributed together with the library to enforce the call stream of `[RequiresDescriptorWhenTrimming]`, which takes over the trimming warning from the ILLink analyzer, with some additional checks, for example, check whether `<T>` generic parameter implements `IWithEntityTypeDescriptor<T>` interface, and produce warning/error respectively.

Any comments are welcome.

**Comment by weifenluo** [comment]
>  If you had some theory before, I'd be interested - maybe it's worth some better docs or samples or something.

Not theory but instinct. The trimmer must rely on the *very first* marker attributes (used in `System.Reflection` for example). Since these marker attributes are bubbled up, I naturally thought these are required by the trimmer. Some better docs will definitely help.

> - Do you expect many usages of the new attribute? Technically if there will be some kind of system solution in the future, the attribute would have to become obsolete/do nothing. Not a big problem, just curious.

Not much, maybe a dozen. It may propagate to users' code though. IMO I don't think future system solution can cover all scenarios, because we have to use marker attribute, and marker attribute has no logic and can carry very limited data. The future might be opening API to customize the analyzer/trimming process.

> - If there's a library which didn't add these, the caller of that library will not know that there's a potential problem.

At this moment I haven't started the implementation yet. I believe an ordinary Roslyn analyzer will do the trick. If there's a library which didn't add this, the library will get compile error/warning, unless the library author suppressed them.

Regarding naming, this is always a big challenge for me, since I work alone and I'm not a native English speaker (ChatGPT doesn't help either). The only way for me is to revisit at later time to see if it's appropriate.

> - What are the reasons you think it's a bad idea to adapt the public API to make it trim/AOT compatible?

Ideally the public API should **not** be affected by trim/AOT compatibility, which is a deployment concern in general. Under certain circumstance, this can lead to anti-pattern design. For example, in an event driven pattern, which the calling chain is reversed, it's hard to add/modify public API to make it trim/AOT compatible.

> - What kind of feature/capability would you like to see from the underlying platform - which would help you solve this easier?

Apparently there is something missing from current underlying platform: some kind of mechanism to terminate the analyzer warning conditionally. Feature switch is doing good job to get code get trimmed conditionally, the analyzer warning should go away together with it.

> - Is it true that you only need this basically for generic parameters, that is you will make it so that if a T for a given method actually implements a given interface it would make the method 100% trim/AOT compatible? 

Yes, the generic parameters is all what I need at this moment. I have two interfaces at this moment (may grow in the future):

The interface to load type metadata without reflection:
```
    public interface IWithEntityTypeDescriptor<T>
        where T : class, IEntityType
    {
#if NET7_0_OR_GREATER
        static abstract EntityTypeDescriptor<T> Descriptor { get; }
#endif

        EntityTypeDescriptor<T> GetDescriptor();
    }
```
and another one for JSON serialization to load `JsonConverter` (that's why I picked the `JsonSerializationOptions.GetConverter` example) and other things without reflection:
```
    public interface IWithJsonEntityTypeDescriptor<T>
        where T : class, IEntityType
    {
#if NET7_0_OR_GREATER
        static abstract JsonEntityTypeDescriptor<T> JsonDescriptor { get; }
#endif

        JsonEntityTypeDescriptor<T> GetJsonDescriptor();
    }
```

Implementations of these two interfaces are automatically generated by source generator. Yes, the implementation is 100% trim/AOT compatible. It's not an easy job, for example consider all annotations under `
System.ComponentModel.DataAnnotations` namespace, plus custom attributes.

Some description regarding conditionally terminate `[RequiresDescriptorWhenTrimming]` attribute:
- The very first `[RequiresDescriptorWhenTrimming]` annotated method:
```
[RequiresDescriptorWhenTrimming]
void Initialize<T>(IWithEntityTypeDescriptor<T> entityType)
{
        var typeDescriptor = withTypeDescriptor.Descriptor;
        ... // go with code path without reflection to initialize entityType object
}
```
- Calling `[RequiresDescriptorWhenTrimming]` annotated method with open generic type must have `[RequiresDescriptorWhenTrimming]` attribute too. For example:
```
[RequiresDescriptorWhenTrimming]
public Entity<T> Entity.Create<T>() where T : class, new()
{
    T entityType = new T();
    Initialize(entityType);
    ...
}

[RequiresDescriptorWhenTrimming]
public EntitySet<T> EntitySet.Create<T>() where T : class, new()
{
    T entityType = new T();
    Initialize(entityType);
    ...
}
```
- Calling with closed generic type does not need `[RequiresDescriptorWhenTrimming]` attribute any more (terminated). For example:
```
var entitySet = EntitySet.Create<Person>();
```
The analyzer will check the provided generic type `Person` to see if it implements `IWithEntityTypeDescriptor<Person>` interface. If it's not, emit a compile error, because eventually it will end up with an exception throw.

Some other challenges to get 100% trimming/AOT compatible so far:
- [Cannot call static abstract interface member conditionally](https://github.com/dotnet/runtime/discussions/86741). The static `JsonDescriptor` interface property is required for JSON deserialization, I have to add an additional API specially for it.
- In order to use existing JSON converters, I need to access internal `JsonConverter<T>.ReadNumberWithCustomHandling` and `WriteNumberWithCustomHandling` method:  (https://github.com/dotnet/runtime/issues/47689). Currently it's workaround via reflection.

Some background of my project: it's a complete rewrite of [RDO.Net](https://rdo.devzest.com/). RDO.Net is not successful, but I think it's a great Proof of Concept.

**Comment by weifenluo** [comment]
Oh, it turns out my scenario has a better solution via compiling into two set of nuget packages, say LibXxxx and LibXxxx.Trimmable.

The two interfaces are included into LibXxxx.Trimmable only:
```
// IWithEntityTypeDescriptor.Trimmable.cs:
public interface IWithEntityTypeDescriptor<T>
        where T : class, IEntityType
    {
#if NET7_0_OR_GREATER
        static abstract EntityTypeDescriptor<T> Descriptor { get; }
#endif

        EntityTypeDescriptor<T> GetDescriptor();
    }

// IWithJsonEntityTypeDescriptor.Trimmable.cs:
    public interface IWithJsonEntityTypeDescriptor<T> : IWithEntityTypeDescriptor<T>
        where T : class, IEntityType
    {
#if NET7_0_OR_GREATER
        static abstract JsonEntityTypeDescriptor<T> JsonDescriptor { get; }
#endif

        JsonEntityTypeDescriptor<T> GetJsonDescriptor();
    }
```

All generics with `<T>` generic parameter should have a `where T : IWithEntityTypeDescriptor` or `where T : IWithJsonEntityTypeDescriptor` generics constraint. For example, the `EntitySet<T>` class:

In LibXxxx:
```
// EntitySet.cs
public partial class EntitySet<T>
    where T : class, IEntityType
    ...
```

In LibXxxx.Trimmable:
```
// EntitySet.cs
public partial class EntitySet<T>
    where T : class, IEntityType
    ...

// EntitySet.Trimmable.cs
partial class EntitySet<T>
    where T : IWithEntityTypeDescriptor
    ...
```

This did exactly what `[RequiresDescriptorWhenTrimming]` does, without introducing any new attribute. Conceptually there are two set of public APIs (only differs from the generics type constraint), the consumer can choose to use any one of them, but not both. The problem is handled at assembly level, which I believe it's reasonable: trimming/AOT is a deployment concern, and assembly is the smallest deployment unit.

As you mentioned earlier:

> Long time ago we decided against having different assemblies for these additional publishing modes (trimming, AOT, single-file, ...). Instead we use runtime checks.

Is there any strong reason behind?

**Comment by vitek-karas** [comment]
> trimming/AOT is a deployment concern, and assembly is the smallest deployment unit.

That depends what you're looking at. Some functionality will never work in trimming/AOT - for example plugins. So while I agree that trimming/AOT should be transparent for most code, it simply won't be the case for everything.

As for use cases like serializers, DTOs and so on, there are other considerations. Using reflection makes the code very flexible, but it tends to be slower and less predictable (meaning the behavior of an API can only be observed at runtime, it's hard to reason what the API will do just looking at the code without knowing the exact input). Trimming/AOT compatibility is mostly about reflection and removing (or decreasing) the need for reflection comes with other benefits like typically better perf, more predictable behavior and easier to diagnose failure modes.

> Is there any strong reason behind? (not compiling different assemblies for trim/non-trim versions)

Mainly predictable behavior. Same reason why we try to avoid using feature switches if there's some other way around the problem. But it depends on your setup. If you were to use the non-trim assembly when building the Debug version of the app and then use the trim assembly when publishing, you're running the risk of behavioral changes which are going to be really hard to catch. On the other hand, if you run the same code regardless of configuration, the app developer can easily test everything in debug and then just deploy without much worry that things will break.

I do agree that given current capabilities of the platform, your proposed solution looks pretty good though.

My takeaway from this is:
* Ideally there would be a way to have method overloads which only differ in generic constraints and the compiler/runtime would have some reasonable way to resolve these. (having this done the right way would be that you would not need any feature switch, custom attribute or second compilation of the assembly, it could happily live side-by-side)
* Alternatively source generators would have a bit more influence on callsites of certain methods - for example in your case, if the source generator could rewrite the call to Initialize, you could again have a second overload (maybe even different name) which would be the trim/AOT version of the API and the source generator would simply redirect all calls to it.

Having a conditional way to produce warnings feels problematic because of its potential issues with integration with the rest of the code. More specifically - how does one specify the condition? And in such a way that it can be expressed both in the annotation as well as in code, but still it's fully statically analyzable by the tooling.

**Comment by weifenluo** [comment]
I've done the implementation of second compilation of the assembly, it's a commit of about 150 files change for one core assembly (including tests), far more than I expected.

In `Directory.Build.props`:
```
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Trimmable')) or $(MSBuildProjectName.Contains('.Trimmable.'))">
    <IsTrimmableProject>true</IsTrimmableProject>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <IsTrimmableProject Condition ="$(IsTrimmableProject) == ''">false</IsTrimmableProject>
  </PropertyGroup>

  <PropertyGroup Condition="$(IsTrimmableProject)">
    <DefineConstants>TRIMMABLE</DefineConstants>
  </PropertyGroup>
```

In `Directory.Build.targets`:
```
  <ItemGroup>
    <None Remove="*.targets" />
  </ItemGroup>

  <ItemGroup Condition="!$(IsTrimmableProject)">
    <Compile Remove="**/*.Trimmable.cs" />
  </ItemGroup>

  <ItemGroup Condition="$(IsTrimmableProject)">
    <Compile Remove="**/*Reflection*.cs" />
  </ItemGroup>
```

There are two .csproj files for the same assembly, say `Lib.csproj` and `Lib.Trimmable.csproj`, the common part are moved into `Lib.targets`, and both projects import `Lib.targets`.

All reflection related implementations are done into internal classes which name contains `Reflection`. These classes will automatically be excluded for trimmable projects which name ends with `.Trimmable` or contains `.Trimmable`. Similarly, source files ends with `.Trimmable.cs` are only included in trimmable projects and automatically excluded from other projects. For example (these are real code):

`EntityModel_T.cs`
```
    public abstract partial class EntityModel<T>
    {
        protected EntityModel(T entityType, bool shouldMount)
        {
            Mounter = GetEntityTypeMounter(entityType);
            ...
        }
    ...
    }
```

`EntityModel_T.Reflection.cs`:
```
    partial class EntityModel<T>
        where T : class, IEntityType
    {
        private ReflectionEntityTypeMounter<T> GetEntityTypeMounter(T entityType)
        {
            return ReflectionEntityTypeMounter<T>.Singleton;
        }
    }
```

`EntityModel_T.Trimmable.cs`:
```
    partial class EntityModel<T>
        where T : class, ITrimmableEntityType<T>
    {
        private EntityTypeMounter<T> GetEntityTypeMounter(T entityType)
        {
            return entityType.GetDescriptor().TypeMounter;
        }
    }
```

A `TRIMMABLE` constant is defined for trimmable projects only so we can use `#if TRIMMABLE ... #else ... #endif` to write code only differs from generic constraint, for example (real code too):

```
public abstract EntitySet
{
        public static EntitySet<T> Create<T>(int capacity = 0)
#if TRIMMABLE
            where T : class, ITrimmableEntityType<T>, new()
#else
            where T : class, IEntityType, new()
#endif
            => CreateCore(EntityType.GetOrCreate<T>(), capacity);
}
```

We need to do the same for all the projects. The conditional code branching is controlled at assembly level via source code. I'm quite satisfied with the result: it's clean, flexible and test friendly.

I'll leave this issue open for a while to see if there are any further comments.
