### ISSUE TITLE
[API Proposal]: Directory.GetDirectories / Directory.GetFiles IAsyncEnumerable

### ISSUE THREAD

**Issue by thomhurst** [dotnet/runtime#85835]
### Background and motivation

The current methods for scanning files or directories returns you an array, which means that you won't see results until the scan has finished and the results committed to an array. This means we can't do anything until we get all of the results.

Imagine starting at the root of a large drive, this could not only take ages, but could also consume a large memory footprint by committing all that data into an array.

With IAsyncEnumerable now existing, we can yield a result as we find it, and that means we can await a foreach loop and then process it in real time as it's returned.

This means while we're waiting for results, we can still do work as data comes back to us, improving the speed of IO heavy programs.

It could also improve memory as we're discarding objects after we're done processing each item returned to us.

### API Proposal

```csharp
Directory.GetFilesAsync(path, pattern, searchOption);
Directory.GetDirectoriesAsync(path, pattern, searchOption);
```

### API Usage

```csharp
await foreach (var file in Directory.GetFilesAsync(path, pattern, searchOption))
{
    // Do stuff
}

await foreach (var directory in Directory.GetDirectoriesAsync(path, pattern, searchOption))
{
    // Do stuff
}
```

### Alternative Designs

If accepted, Similar APIs should also be implemented on the DirectoryInformation class.

**Comment by Tornhoof** [comment]
Are you aware of https://learn.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystemenumerable-1?view=net-8.0?
While not async, it solves a lot of the common problems of the APIs you mentioned.

**Comment by Tornhoof** [comment]
As for proper async, the same issues apply here as for your other proposal, there is simply no support by the OS for such operations.

**Comment by thomhurst** [comment]
If FileSystemEnumerable yields on each item, it has the benefit of not only speeding up an application, but also reducing its memory footprint right?

I wonder if these existing methods I mentioned should be marked as obsolete with recommendations to move over to this other class? I had no idea it existed, and I'm sure a lot of people will be like me and just default to the basic File / Directory classes.

I assume the original implementations are relics from early .NET and can't currently be changed due to backwards compatibility.

**Comment by pinkfloydx33** [comment]
Even before `FileSystemEnumerable`, [`EnumerateFiles`](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=net-7.0), [`EnumerateDirectories`](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratedirectories?view=net-7.0) and cousins on `DirectoryInfo` have been around since 4.0 and were the preferred mechanism over the `Get` variants, accepting the same arguments yet returning a lazy enumerable.

**Comment by danmoseley** [comment]
I don't think this is enough reason to mark the original API obsolete (not least because it's quick and easy when that's all you need) but we're always interested in PRs to improve docs. Eg a note in the doc for the original API. Just click the button when viewing the topic.

**Comment by neon-sunset** [comment]
While not for perf. reasons, seconding this proposal due to advantages for writing idiomatic and async-friendly code that would allow expressing (with `System.Linq.Async` package)
```cs
await Directory
    .GetFilesAsync(path, pattern, searchOption)
    .ForEachAsync(FileHandler);
```
with runtime implementation being free to do optimizations like batching/chunking enumerated files, using better (if available) OS APIs for reading filesystem metadata and otherwise reducing syscalls, etc.

**Comment by stephentoub** [comment]
We don't add async APIs if we can't implement then using async I/O. The proposed methods would either run synchronously or we'd be forced to use async-over-sync approaches. As @Tornhoof commented, neither Linux nor macOS nor Windows offer APIs to do this asynchronously.
