### ISSUE TITLE
[API Proposal]: RequiresLocationAttribute (supporting ref readonly parameters)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#85910]
### Background and motivation

As part of the new `ref readonly` parameters feature (https://github.com/dotnet/csharplang/issues/6010), Roslyn will emit a new `[RequiresLocation]` attribute in some cases, all documented in the spec in that linked issue (as well as in the speclet at https://github.com/dotnet/csharplang/pull/7165). This issue tracks adding the attribute to the runtime as well, so it can be shared (just like eg. `[RefSafetyRules]`).

### API Proposal

```cs
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class RequiresLocationAttribute : Attribute
    {
    }
}
```

**Comment by Sergio0694** [comment]
Of course. This isn't meant to go to to API review yet 🙂

**Comment by tannergooding** [comment]
Why is this attributed needed? Won't the compiler be synthesizing the attribute if it doesn't exist, as it does with most of the other attributes it needs?

API review has typically rejected such attributes in the past.

**Comment by Sergio0694** [comment]
Wouldn't that be the same as with eg. `[RefSafetyRules]`? That's also synthesized by the compiler when missing, but the runtime does bundle it. I always assumed this was mostly to save size (ie. to avoid having multiple internal definitions in each project?), is that not the case? @jaredpar would the compiler team have a preference for this being included in the runtime or not, and/or would there be other considerations to make here to support this point one way or the other? 🙂

**Comment by tannergooding** [comment]
Marked as `ready-for-review`, but keeping in `future` until the language feature gets closer to completion.

We can push update the milestone and push forward as/when needed.

**Comment by bartonjs** [comment]
Looks good as proposed.  Marking the issue as blocked, though, since it's intentional that this attribute not be added until .NET 9 (to give the compiler feature one version of prototyping/experimentation/etc that might affect the public attribute).

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class RequiresLocationAttribute : Attribute
    {
    }
}
```

**Comment by jaredpar** [comment]
This is the first I've heard of us holding back for a release to give the compiler time to experiment. When did that policy come into place? The compiler feature is going to RTM in `net8.0` so, at least at the compiler level, this attribute is supported forever. Unsure why runtime is holding back here.

**Comment by jaredpar** [comment]
Ah okay. A deliberate slip between when compiler finishes and when we commit to the shape in runtime makes sense. Based on your comment i would expect that in most cases we ship the attribute and compiler feature in same release. Cases like this where we merge too late would be the rarer case. I read the previous comment as waiting a release being the general policy not the reflection of the specifics of this feature.

**Comment by hamarb123** [comment]
It would be ideal to add this in .NET 8 imo if at all possible.
Here's why:

Using it like so: `delegate* managed<ref readonly int, void>` causes it to be emitted as a `modopt`, meaning that for binary compatibility purposes, the assembly it's defined in can be important.

Let's say with .NET 8 I write an API like so:
```csharp
public void X(delegate* managed<ref readonly int, void> ptr);
```
when .NET 9 happens (assuming we add it to corelib here), I now need to add a type forwarding to maintain binary compatibility, even though this is a fully supported feature in .NET 8 and .NET 9 with C# 12 and 13 respectively.
Even worse is the scenario that I reference an assembly with either a public definition, or with `[InternalsVisibleTo]`, as I now also have to change that assembly to also type forward it to maintain binary compatibility for both.
Even just adding a reference to an assembly with a public definition, or with `[InternalsVisibleTo]` would be a binary breaking change if I don't set up type forwarding correctly.
It is a similar problem to `IsExternalInit`, except that roslyn will generate it for you (unlike `init`, which requires you to manually define it, and thus deal with it yourself).

The best solution imo would be to: let roslyn generate it every time if used as a modifier, ignore any public definition in a dependency, unless in corelib (ie. < .NET 8), otherwise use the definition from corelib (if >= .NET 8) & have roslyn generate a type forward if it's used as a modifier. If it's not used as a modifier (ie. no uses in as a function pointer parameter), then it doesn't matter which definition is used as it's not significant for binary compatibility purposes, so there would be no need to generate type forwards or worry about which version we're referencing in this case.

The main part of this solution is to add it to corelib asap (that way there will be no issues transitioning from .NET 8 to 9, which are the only "supported" .NET versions for the C# version with this feature), I'm happy to add type forwards myself in a library that targets multiple tfms if this is not something we want to burden roslyn with.

**Comment by jjonescz** [comment]
The attribute isn't synthesized for function pointers, they require the attribute to be defined manually somewhere (by user or corelib), otherwise it's an error to declare function pointer signature with `ref readonly`. That's consistent with `in`, for example.

So there could be a break if user defines the attribute manually, but that seems expected.

Adding some more tests to demonstrate this behavior: https://github.com/dotnet/roslyn/pull/69328

**Comment by Sergio0694** [comment]
Out of curiosity: if we do need to add the attribute to .NET 8 to avoid breaking changes with function pointers (which makes perfect sense), does it still make sense to have Roslyn synthesize the attribute at all if it doesn't exist already? 🤔

**Comment by tannergooding** [comment]
The compiler won't synthesize the attribute for the `modreq` only for cases where its safe. Hence if we didn't provide the type the ability to use `ref readonly` in function pointers would be restricted.

Users could still define their own public type, but then they'd never be able to remove it or would have to appropriately type forward in the future, etc.

**Comment by Sergio0694** [comment]
Yeah no I get that, but what I'm saying is, if due to the type being used as a `modreq` in function pointer we're in fact going to add the attribute in .NET 8, then what's the point of the additional complexity in Roslyn to synthesize the type if not present? Especially given that .NET 8+ would be the only officially supported use case scenario for C# 12 anyway? 🤔

(and of course, folks downlevel can just polyfill and type forward as usual)

**Comment by tannergooding** [comment]
The support to synthesize the type is general purpose and it is likely more work (and more risk this late in the cycle) to remove that support than it is to simply keep it.

It also allows the feature to be used on older frameworks for the power users that do that (noting its still officially an unsupported scenario; but that's never stopped people in the past).

Typically the types that aren't synthesized have some pretty tough restrictions, such as being required to be defined in "corelib" (that is the assembly that defines `object` and has no dependencies).
