### ISSUE TITLE
RuntimeHostConfigurationOption for GC configuration ignored in NativeAOT

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#85961]
### Description

as reported by @wizardars
The hardlimit in AOT doesn't work.

### Reproduction Steps

Add to project file.
```
<PropertyGroup>
    <PublishAot>true</PublishAot>
</PropertyGroup>
<ItemGroup>
	<RuntimeHostConfigurationOption Include="System.GC.HeapHardLimit" Value="100000000" />
</ItemGroup>
```
Put following code 
```
Console.WriteLine($"Total available bytes");
Console.WriteLine($"{GC.GetGCMemoryInfo(GCKind.Any).TotalAvailableMemoryBytes}!"); ; ;

Console.WriteLine($"GC configuration");
var gcConfiguration = GC.GetConfigurationVariables();
foreach (var (key, value) in gcConfiguration)
{
    Console.WriteLine($"{key}: {value}");
}
```

### Expected behavior

```
Total available bytes
4294967296!
GC configuration
ServerGC: False
ConcurrentGC: True
RetainVM: False
NoAffinitize: False
GCCpuGroup: False
GCLargePages: False
HeapCount: 1
GCHeapAffinitizeMask: 0
GCHeapAffinitizeRanges:
GCHighMemPercent: 0
GCHeapHardLimit: 4294967295
GCHeapHardLimitPercent: 0
GCHeapHardLimitSOH: 0
GCHeapHardLimitLOH: 0
GCHeapHardLimitPOH: 0
GCHeapHardLimitSOHPercent: 0
GCHeapHardLimitLOHPercent: 0
GCHeapHardLimitPOHPercent: 0
GCConserveMem: 0
GCName:
```

### Actual behavior

```
Total available bytes
17053245440!
GC configuration
ServerGC: False
ConcurrentGC: True
RetainVM: False
NoAffinitize: False
GCCpuGroup: False
GCLargePages: False
HeapCount: 1
GCHeapAffinitizeMask: 0
GCHeapAffinitizeRanges:
GCHighMemPercent: 0
GCHeapHardLimit: 4294967295
GCHeapHardLimitPercent: 0
GCHeapHardLimitSOH: 0
GCHeapHardLimitLOH: 0
GCHeapHardLimitPOH: 0
GCHeapHardLimitSOHPercent: 0
GCHeapHardLimitLOHPercent: 0
GCHeapHardLimitPOHPercent: 0
GCConserveMem: 0
GCName:
```

### Regression?

No.

**Comment by kant2002** [comment]
I file fix for NativeAOT to be able read configuration from environment variables. https://github.com/dotnet/runtime/pull/85921 but seems to be application does not allow embed `RuntimeHostConfigurationOption` values as default values for the executable which looks like valid request.

**Comment by kant2002** [comment]
Right now `RuntimeHostConfigurationOption` options populated `AppContext`. Should I somehow expose `AppContext` to `RhConfig::ReadConfigValue`

**Comment by mrsharm** [comment]
Hi @kant2002, what version of the runtime are you running? 

We recently made a fix for something similar: https://github.com/dotnet/runtime/pull/84201 - the underlying issue of which might be related to the issue you are observing.

**Comment by MichalStrehovsky** [comment]
The issue is that all these settings have two names:

https://github.com/dotnet/runtime/blob/af1de1308163bb19f02d4b7277a62b3ff4bba457/src/coreclr/gc/gcconfig.h#L66-L140

We currently allow setting the variables using their names from the second column. It's the existing `--runtimeopt` option in ILC. We currently only use it to set server GC here:

https://github.com/dotnet/runtime/blob/af1de1308163bb19f02d4b7277a62b3ff4bba457/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L221

Unfortunately the mapping from the name exposed as RuntimeHostConfigurationOption to the name that we support embedding only exists in the GC. I don't think we want to duplicate it.

It seems like the only option we have is to introduce a way to store both of these.

The existing mechanism generates things around here:

https://github.com/dotnet/runtime/blob/af1de1308163bb19f02d4b7277a62b3ff4bba457/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/RuntimeConfigurationRootProvider.cs#L23

They're read round here:

https://github.com/dotnet/runtime/blob/af1de1308163bb19f02d4b7277a62b3ff4bba457/src/coreclr/nativeaot/Runtime/RhConfig.cpp#L147

We need to either add another blob with the new values, or come up with some sort of mangling so that we can store both key/value pairs in the same blob. I don't have an opinion. Whichever looks better.

**Comment by kant2002** [comment]
@mrsharm I was using latest (couple days ago runtime). 

Michal give me hints to the solution and to workaround. 

If add `<IlcCompileInput Include="--runtimeopt:GCHeapHardLimit=FFFFFFFF" />` to ItemGroup then you can configure hard limit up to 4Gb-1 on .NET 7, and with https://github.com/dotnet/runtime/pull/85921 you can set anything that's possible on CoreCLR.

Also @MichalStrehovsky I notice that NativeAOT configuration ignore public key, even if GC request it. so if change 
https://github.com/dotnet/runtime/blob/32db6312055372e223c0a3eb6cb72bfaacf6e8e3/src/coreclr/nativeaot/Runtime/gcrhenv.cpp#L1361-L1384

and teach this function together with `GetIntConfigValue` that `publickey` parameter is useful and try to read it, then we can have everything almost for free, assuming that all `RuntimeHostConfigurationOption` would be passed to ILC not only using `--appcontextswitch` but also `--runtimeopt`.

**Comment by kant2002** [comment]
@mrsharm I was using latest (couple days ago runtime). 

Michal give me hints to the solution and to workaround. 

If add `<IlcCompileInput Include="--runtimeopt:GCHeapHardLimit=FFFFFFFF" />` to ItemGroup then you can configure hard limit up to 4Gb-1 on .NET 7, and with https://github.com/dotnet/runtime/pull/85921 you can set anything that's possible on CoreCLR.

Also @MichalStrehovsky I notice that NativeAOT configuration ignore public key, even if GC request it. so if change 
https://github.com/dotnet/runtime/blob/32db6312055372e223c0a3eb6cb72bfaacf6e8e3/src/coreclr/nativeaot/Runtime/gcrhenv.cpp#L1361-L1384

and teach this function together with `GetIntConfigValue` that `publickey` parameter is useful and try to read it, then we can have everything almost for free, assuming that all `RuntimeHostConfigurationOption` would be passed to ILC not only using `--appcontextswitch` but also `--runtimeopt`.
