### ISSUE TITLE
[API Proposal]: Math.Clamp<T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#85979]
### Background and motivation

I need to Clamp IComparable

### API Proposal

```csharp
namespace System;

public class Math
{
    public T Clamp<T>(T value, T min, T max) where T : IComparable<T>;
}
```

### API Usage

```csharp
Math.Clamp(Value, TimeSpan.Zero, MaxRange);
```

**Comment by huoyaoyuan** [comment]
I believe the specific usage is covered by #76225.

**Comment by svick** [comment]
Here are some facts:

1. `Math` currently has no generic methods.
2. New generic methods are being added to generic numeric interfaces. In particular, [`INumber<T>.Clamp`](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumber-1.clamp) already exists.
3. `INumber<T>` is not appropriate for many `IComparable<T>` types (including `TimeSpan`).
4. Default interface methods, especially on common interfaces like `IComparable<T>` are problematic.

Because of these, I don't see a good place in .Net for this method, even though I agree it would be useful if it existed.

**Comment by svick** [comment]
@huoyaoyuan That proposal suggests adding several numeric interfaces to `TimeSpan`, but as far as I can tell, not `INumber`, which is the one that includes `Clamp`.

**Comment by tannergooding** [comment]
As svick called out, a generic `Clamp` method already exists as `INumber<T>.Clamp`. If we were to expose any generic `Clamp` on `Math` it would match this behavior, and not the behavior of `IComparable<T>`

In particular, `IComparable` takes into account `.NET Equality` rules, such as are suitable for hash based collections or sorting. It doesn't necessarily do the same as the underlying relational operators (`<`, `<=`, `>`, `>=`, `==`, and `!=`) which are more oriented towards the types and their "mathematical properties". The simplest example of this difference is with the `floating-point` types where `NaN` exists.

I don't think we have a good place to expose such an `IComparable.Clamp` method (nor Min/Max/etc) and they are simple enough that any developer could roll their own if they desired it for their own codebases.

A separate proposal to expose `Min`, `Max`, and `Clamp` explicitly on `TimeSpan` would not be unreasonable and might be worth suggesting.

**Comment by tannergooding** [comment]
As per https://github.com/dotnet/runtime/issues/18481, I'd be open to someone opening a proposal covering an explicit `static class Comparable` that exposes `Min`/`Max`/`Clamp` with the relevant constraints.
