### ISSUE TITLE
Regression on INTEL machines with TechEmpower Fortunes

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#86113]
![image](https://github.com/dotnet/runtime/assets/1165805/3d413265-9f04-4b83-89c6-0421d5ccb039)

Only INTEL, both windows and linux. All Fortunes middleware (not platform).

Minimum set of commits: https://github.com/dotnet/runtime/compare/a442971...ab98c9b

**Comment by MihaZupan** [comment]
From https://github.com/dotnet/runtime/pull/84184#issuecomment-1544685759

Tried the following commits:
1. 1b56e9667da4b447182d14a08966fb1ed739232f (PR #84184)
2. e241509952cc6300198ce4c31f2220a3f4ef15a9 (commit just before nr. 3)
3. 58a13652d0c1811ecf5684a4e750fe796d5cde93 (PR #85894)

| load                   | 1         | 2         |         | 3         |        |
| ---------------------- | --------- | --------- | ------- | --------- | ------ |
| Requests/sec           |   304,458 |   302,716 |  -0.57% |   281,044 | -7.69% |
| Requests               | 4,585,264 | 4,570,922 |  -0.31% | 4,243,602 | -7.45% |
| Bad responses          |         0 |         0 |         |         0 |        |

**Comment by sebastienros** [comment]
Thanks @MihaZupan, that's very helpful.

**Comment by sebastienros** [comment]
@EgorBo confirmed this would also be fixed by https://github.com/dotnet/runtime/pull/85551

**Comment by MihaZupan** [comment]
Since I already had the runtime built, here are the numbers from `aspnet-perf-win` to further confirm https://github.com/dotnet/runtime/pull/85894#issuecomment-1544699031:
| load                   | 2-perf    | 3-perf    |         |
| ---------------------- | --------- | --------- | ------- |
| Requests/sec           |   208,299 |   204,782 |  -1.69% |
| Requests               | 3,145,265 | 3,092,240 |  -1.69% |
| Bad responses          |         0 |         0 |         |

**Comment by EgorBo** [comment]
Fixed via #85551 + improved by Dynamic PGO:

![image](https://github.com/dotnet/runtime/assets/523221/8cdaa879-be9e-4800-8d20-02de23b4793b)
