### ISSUE TITLE
[API Proposal]: update legacy apis with ICollection<T> / IReadOnlyCollection<T>/ IEnumerabe<T>

### ISSUE THREAD

**Issue by Bonuspunkt** [dotnet/runtime#86219]
### Background and motivation

There are still classes with only `ICollection` / `IEnumerable` / `IEnumerator` implemented.
The users currently need to explict call `.OfType<T>()` to take advantage of the `IEnumerable<T>` extensions (LINQ)

### API Proposal

imho best solution would be a roslyn analyzer to determine the most appropriate interface

afaik for `ICollection`, `IEnumerable` this would be 
- `ICollection<T>` 
- `IReadOnlyCollection<T>` 
- `IEnumerabe<T>`

and for `IEnumerator` it would be 
-  `IEnumerator<T>`

plus a codefix to implement it.

### API Usage

the classes and interfaces already exists. it would just combine them and leverage the power of those generic interfaces to the developers

### Risks

- new interfaces on (legacy?) classes
- existing user code becomes obsolete
- better ux for new code

**Comment by Bonuspunkt** [comment]
not sure, if System.Collections is the only area

i found this issue at `System.Management.ManagementObjectCollection` (rel. #86215) 
and a quick and dirty reflection search, picking some at random and manual verifying it revealed, it is also present at
- `System.Collections.BitArray`
- `System.ComponentModel.PropertyDescriptorCollection`
- `System.Security.Cryptography.OidCollection`
- `System.Xml.XmlNode` 
they all use enumerator implementations, which are lacking `IEnumerator<T>` and holding `Current` internally typed

as mentioned above, imho the only proper way to find all areas would be with an analyzer

**Comment by eiriktsarpalis** [comment]
I think this is a determination that should be made on a case-by-case basis when reviewing particular components. For some types it might be a welcome enhancement, in others however it might the case that we're either no longer investing in improving it or that the particular improvement does not provide a lot of value to users.

I would recommend filing individual API proposals for the specific types you are interested in (e.g. `ManagementObjectCollection` since you created that PR). That should give the chance to each area owner to review your proposal separately.

With that, I'm going to close this issue as it's a bit too broad to be actionable.

**Comment by eiriktsarpalis** [comment]
As mentioned, my recommendation would be to open up issues on a case-by-case basis.
