### ISSUE TITLE
`System.Text.Json` source generator creates default type converters for properties with `JsonConverter` attribute

### ISSUE THREAD

**Issue by ngarside** [dotnet/runtime#86223]
### Description

When using the `System.Text.Json` source generator to serialise properties adorned with `JsonConverterAttribute`, the source generator still generates a default converter for the property type despite this not being used. This causes builds to fail if the property is of a type which `System.Text.Json` does not natively support (in this case `ReadOnlyMemory<byte>`).

### Reproduction Steps

Create a project with these files:

```csharp
// Project.csproj

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
</Project>

// Program.cs

using System.Text.Json;
using System.Text.Json.Serialization;

var entity = new Entity { Content = new byte[] { 1, 2, 3 } };
var json = JsonSerializer.Serialize(entity, JsonContext.Default.Entity);
Console.WriteLine(json);

record Entity
{
    [JsonConverter(typeof(MemoryConverter))]
    public ReadOnlyMemory<byte> Content { get; set; }
}

[JsonSerializable(typeof(Entity))]
partial class JsonContext : JsonSerializerContext { }

class MemoryConverter : JsonConverter<ReadOnlyMemory<byte>>
{
    public override ReadOnlyMemory<byte> Read(
        ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return reader.GetBytesFromBase64();
    }

    public override void Write(
        Utf8JsonWriter writer, ReadOnlyMemory<byte> value, JsonSerializerOptions options)
    {
        writer.WriteBase64StringValue(value.Span);
    }
}
```

Run the project with `dotnet run`.

### Expected behavior

Program should run and output `{"Content":"AQID"}`.

### Actual behavior

Program compilation fails with (full paths redacted):

```
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.ReadOnlySpanByte.g.cs(10,129): Error CS0306 : The type 'ReadOnlySpan<byte>' may not be used as a type argument
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.ReadOnlySpanByte.g.cs(19,128): Error CS0306 : The type 'ReadOnlySpan<byte>' may not be used as a type argument
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.ReadOnlySpanByte.g.cs(14,127): Error CS0306 : The type 'ReadOnlySpan<byte>' may not be used as a type argument
```

### Regression?

No (same behaviour in .NET 7).

### Known Workarounds

- Use reflection serialisation (only if not using AOT)
- Use a different type for the property (in this case `byte[]`), although this may not be an option for other types
- Write a custom `JsonConverter` for the entire class/record

### Configuration

.NET 8.0.100-preview.3.23178.7
Windows 11 x64

**Comment by ngarside** [comment]
Maybe related to #86222

**Comment by eiriktsarpalis** [comment]
It is related to https://github.com/dotnet/runtime/issues/86222, since in both cases the serializer is attempting to generate metadata for the unsupported `ReadOnlySpan<T>` property inside `ReadOnlyMemory`. We address both issues by having the serializers explicitly declare the type as unsupported so that no nested member generation is going to be attempted.

**Comment by Sergio0694** [comment]
> "since in both cases the serializer is attempting to generate metadata for the unsupported `ReadOnlySpan<T>` property inside `ReadOnlyMemory`. We address both issues by having the serializers explicitly declare the type as unsupported so that no nested member generation is going to be attempted."

Just trying to make sure I'm following what the issue is here. My understanding was that if you have a type that's annotated with a custom serializer, that would automatically block the source generator from crawling the nested type hierarchy. In fact, I remember we stumbled upon this exact behavior in the Store as well (where we had a type that had a few properties using a custom serializer, and the generator wasn't automatically crawling those types, exactly due to those types having `[JsonSerializer]` on them. How come that's not the case here? Is that because on one hand we had the attribute on the type, whereas here it's applied just on a given property of an unannotated type? Is the difference in behavior by design? 🤔

Thank you! 🙂

**Comment by eiriktsarpalis** [comment]
> Is that because on one hand we had the attribute on the type, whereas here it's applied just on a given property of an unannotated type? Is the difference in behavior by design?

Yes, and yes. The problem here is that we don't have a way to gracefully handle unsupported types in the latter case.

**Comment by Sergio0694** [comment]
Gotcha, thank you for the additional info! Definitely good to know! 🙂
