### ISSUE TITLE
.net7 HRESULT: 0x8007000E on linux with read-only fs

### ISSUE THREAD

**Issue by galakt** [dotnet/runtime#86259]
### Description

Trying to run .net 7 app in linux container with read-only fs 
with command ```dotnet someapp.dll``` and see
``` Failed to create CoreCLR, HRESULT: 0x8007000E```

Works fine with writable fs.
Works fine with `COMPlus_EnableDiagnostics=0`

#### Questions
1. Should it work on read-only fs without additional configuration during build\run?
2. ~~Do I miss something and have to set something up to be able to run application on read-only fs?~~
3. Should error be more readable in this case?

#### stracelog
[stracelog.txt](https://github.com/dotnet/runtime/files/11480258/stracelog.txt)

### Reproduction Steps

Run .net 7 app in linux container with read-only fs

### Expected behavior

It works or returns more readable error

### Actual behavior

Failed to create CoreCLR, HRESULT: 0x8007000E

### Configuration

Base image: `mcr.microsoft.com/dotnet/aspnet:7.0-cbl-mariner2.0`

dotnet info:
```

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by tommcdon** [comment]
Thanks for the highly detailed report @galakt!  Do you have a business requirement to run the app on a read-only filesystem or do you allow for writing to a tmp filesystem?  If not, the debug pipe should be written to `$TMPDIR`, so setting that environment variable pointed to a writable filesystem should workaround the issue.

**Comment by hoyosjs** [comment]
It will fail under a multitude of diagnostic scenarios: the debugger pipe, event pipe, and the writing of perfmap files. We probably should document it, and potential workarounds. Other than the perfmap - used by tools like perf and some cloud native solutions - tmpdir redirection could help, as long as it's only root fs that's getting into RO mode and you have a mount that's RW. Otherwise, you'd probably have to disable diagnostics.

**Comment by MichalStrehovsky** [comment]
Regarding the "question" label - should this fail with a less obscure error message that suggests a fix, even if writing to filesystem is by design?

**Comment by hoyosjs** [comment]
At the very least it's fair not to expect an OOM HR - that's fair.

**Comment by galakt** [comment]
@tommcdon 
> Do you have a business requirement to run the app on a read-only filesystem

It is requirement from security team

@MichalStrehovsky @hoyosjs 
> Regarding the "question" label

Would be happy to see less obscure error message

**Comment by hoyosjs** [comment]
cc: @richlander since this lines up with containerized workloads security.

It's fair that there's two things.

- Finer grainer control for diagnostic experiences. You should be able to shut down the debugger without needing to shut down things like EventPipe. Particularly interesting for production environments.
- There should be a better diagnostic experience on the startup. We have another issue around failing to startup the diagnostic client. The two questions are what should we consider an initialization error vs a warning and where should we log it to make it obvious to the customer.

**Comment by tommcdon** [comment]
Hello @galakt!  Do you have a requirement to have a non-writable tmp directory?

We took some time to investigate the issue - we found that there are two places where the runtime creates pipes/domain sockets for diagnostics:
* [Diagnostics IPC](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-port) - By default the 'listen' port is created in /tmp or `$TMPDIR` if the env variable is set.  It provides a transport for collecting memory dumps, starting an EventPipe tracing session, requesting a dump, ...  It is considered non-fatal if it doesn't start.  
* [Debugger Port](https://github.com/dotnet/runtime/blob/ddbce91b241bcf0d7f33d04d33520659addd6dd7/src/coreclr/debug/ee/debugger.cpp#L1813) - creates 2 pipes in /tmp or `$TMPDIR` if the variable is set in Debugger::Startup.  This is considered fatal if we can't create the port.  This is not only related to read only file systems.  For example, if `$TMPDIR` is set to a Windows mount in WSL2, the pipe will also fail to be created.

> Finer grainer control for diagnostic experiences. You should be able to shut down the debugger without needing to shut down things like EventPipe. Particularly interesting for production environments.

I have a draft implementation here: https://github.com/tommcdon/runtime/commit/3820f5b6051371fa94f99ad517d4821bf687faf7.  Please let me know if there is any interest.

> There should be a better diagnostic experience on the startup. We have another issue around failing to startup the diagnostic client. The two questions are what should we consider an initialization error vs a warning and where should we log it to make it obvious to the customer.

I have a draft commit that allows .net to start without initialization failure if it can't create the debugger pipe: https://github.com/tommcdon/runtime/commit/e7e36fdfb854118816aabeff36546d2c0a2b7259.  Please let me know if there is any interest.

**Comment by timmydo** [comment]
@tommcdon , I'm also interested it this feature. We have a YARP-based reverse proxy that shouldn't have any dependencies on writing to the disk, so I'm trying to enable it now for that application. For now, I'll going to try leaving /tmp as read-write (kubernetes emptydir) rather than disabling diagnostics.

**Comment by tommcdon** [comment]
Closing via #90159 and #90161
