### ISSUE TITLE
Invalid IL produced by unreachable code blocks optimization

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#86304]
IL Linker tries to remove unreachable basic blocks from exception filter blocks, but may strip the `endfilter` instruction in the process, making the IL invalid.

Ran into this in the CoreCLR Pri0 test suite because Native AOT also imported this bug. The CoreCLR test is in IL but it can be reached with C# - this is the simplest way to reach it (pardon the nonsensical code, didn't want to think about this much):

```csharp
try
{
    throw new Exception();
}
catch when (IntPtr.Size == 8 ? throw new Exception() : true)
{
    Console.WriteLine("Hey");
}
```

**Comment by vitek-karas** [comment]
I think I found a compiler bug... I played with the above sample and created this:
```C#
        try
        {
            throw new Exception();
        }
        catch when (IntPtr.Size == 8 ? throw new Exception() : throw new Exception())
        {
            Console.WriteLine("");
        }
```

When compiled it produces IL like this:
```
	.try
	{
		IL_0000: newobj instance void [System.Runtime]System.Exception::.ctor()
		IL_0005: throw
	} // end .try
	IL_0006: pop
	IL_0007: call int32 [System.Runtime]System.IntPtr::get_Size()
	IL_000c: ldc.i4.8
	IL_000d: pop
	IL_000e: pop
	IL_000f: newobj instance void [System.Runtime]System.Exception::.ctor()
	IL_0014: throw
```

It's a try block with no handlers.

Trying to run this on CoreCLR produces:
`System.InvalidProgramException: Common Language Runtime detected an invalid program.`

Trying to trim this crashes Cecil:
```
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Cecil.Cil.CodeReader.ReadExceptionHandlers(Int32 count, Func`1 read_entry, Func`1 read_length)
     at Mono.Cecil.Cil.CodeReader.ReadSmallSection()
     at Mono.Cecil.Cil.CodeReader.ReadSection()
     at Mono.Cecil.Cil.CodeReader.ReadFatMethod()
```

NativeAOT actually handles this the best and prints out:
` ILC: Method '[FilterBlockRemoval]Repro.Test()' will always throw because: Invalid IL or CLR metadata`
(and then fails with `InvalidProgramException` at runtime).

**Comment by vitek-karas** [comment]
Hmm - somebody already did: https://github.com/dotnet/roslyn/issues/67494

**Comment by MichalStrehovsky** [comment]
@vitek-karas  can we close this?

**Comment by vitek-karas** [comment]
Yes.
