### ISSUE TITLE
[HTTP/3] Compare perf for OpenSSL 1.1 vs OpenSSL 3+ MsQuic versions on a same machine

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#86516]
Spawned from https://github.com/dotnet/runtime/issues/81801

While https://github.com/microsoft/msquic/issues/3410 is considered fixed by updating to 3.1, it would be nice to get numbers on our side to confirm that. (Current automated perf tests run on Debian 11, so they use OpenSSL 1.1).

Might be easier to do on Ubuntu 22.04.

<details>

OpenSSL 3+ MsQuic package is published in https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/libm/libmsquic/libmsquic_2.2.1_amd64.deb

OpenSSL 1.1 MsQuic package can be taken from previous distro version (20.04 or 18.04) https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/libm/libmsquic/libmsquic_2.2.1_amd64.deb
OpenSSL 1.1 itself can be taken from http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb

</details>

**Comment by rzikm** [comment]
I ran the benchmarks with latest libmsquic.2.2.4 builds from the above sources. First with LD_DEBUG=libs to verify that the libs were actually picked up, then without it to perform measurements. The measurements were run on the `aspnet-perf-lin` profile (Ubuntu 22.04), 5 clients, 10 threads per client, 5 repetitions.

![image](https://github.com/dotnet/runtime/assets/32671551/7c78393b-f8e0-483f-af2a-bb972ad222bc)

The difference between the two versions does not seem significant.

I wanted to run it with older libmsquic as well to see if I reproduce the perf drop, but we have since then increased the minimal version to 2.2.2 which should already use OpenSSL 3.1

## Repro steps

<details>

put .so files in ./openssl1.1 or, ./openssl3.1 dirs no need to add libcrypto because a compact package was installed on the runner.

run.ps1:

```ps
. $PSScriptRoot/Run-HttpClientBenchmark.ps1

function Run {
    $files = @("$PSScriptRoot/openssl1.1/**")
    $tag = "1.1"
    Run-HttpClientBenchmark -ClientExtraFiles $files -ServerExtraFiles $files -Properties @{ "OpenSSL" = $tag } @args

    $files = @("$PSScriptRoot/openssl3.1/**")
    $tag = "3.1"
    Run-HttpClientBenchmark -ClientExtraFiles $files -ServerExtraFiles $files -Properties @{ "OpenSSL" = $tag } @args
}

# $profile = 'local'
$profile = 'aspnet-perf-lin'
$CsvOutput = "$PSScriptRoot/Results.csv"

$Args = @{
    RunProfile = $profile 
    CsvOutput = $CsvOutput
    HttpVersion = '3.0' 
    Clients = 5
    ConcurrencyPerClient = 10
    # uncomment to debug
    # ServerEnvVars = @{ LD_DEBUG = "libs" }
}

$runs = 5

foreach ($size in @(0, 16384)) {
    $Args.ResponseSize = $size
    $Args.RequestContentSize = $size

    for ($i = 0; $i -lt 5; $i++) {
        Run -Post @Args
    }
}
```
[Run-HttpClientBenchmark.ps1 source](https://gist.github.com/rzikm/229422515958f29ee41126da9e269bda)

</details>
