### ISSUE TITLE
Improve debugging experience of Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#86553]
`Microsoft.Extensions.DependencyInjection` debug experience could be improved.

I think there are two primary APIs to focus on: `ServiceCollection` and `IServiceProvider` implementations.

`ServiceCollection` is already pretty good. It could be improved with a debugger display that shows the count and whether it's read-only.

![image](https://github.com/dotnet/runtime/assets/303201/c135cad1-fc5f-41cb-a9fa-5dc2ba8d509f)

`IServiceProvider` is difficult to debug. Useful information to make available:

* Its service descriptors (the information that `ServiceCollection` displays)
* Is it a scoped or root service provider
* Is it disposed
* Realized services
* Registered disposable services
* More that I haven't thought of?

![image](https://github.com/dotnet/runtime/assets/303201/c2f0fa9f-7fc1-46f9-9ec7-607ed17bab49)

**Comment by ericstj** [comment]
@steveharter this seems like a nice thing to improve in 8.0.

**Comment by kwaazaar** [comment]
I would like something that helps with detecting an attempt to resolve a circular dependency that was not detected on build (eg when using a factory, like `services.AddTransient<IService>(sp => sp.GetRequiredService<MyService>())`).

I know my codebase needs refactoring, but it's so big (and not created by myself), that I have no idea where those circular dependencies are. Result is now that I have to start the application and see if memory usage will suddenly increase dramatically (result of the circular dependency) and then manually check all code to find where the cause could be.

Logging could help, but detecting on build OR resolve would help even more.
And since I know from my factory-code which types I create, I could even provide it to the TryAdd/Add on the servicecollection, so it could use that information for detection. Something like this: `services.AddTransient<IService>(sp => sp.GetRequiredService<MyService>(), new[] { typeof(MyService) })`.

**Comment by JamesNK** [comment]
Fixed by https://github.com/dotnet/runtime/pull/88082
