### ISSUE TITLE
[AOT] ExpressionTree AOT very slow

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#86568]
### Description

When I try expression call method with `ExpressionTree`, the result is slower than `MethodInfo.Invoke`

### Configuration

dotnet --info
```cmd
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\
```

### Regression?

I don't know.

### Data

Code is here

Program.cs
```csharp
internal class Program
    {
        static void Main(string[] args)
        {
            BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args, new MyConfig());
        }
    }
    public class MyConfig : ManualConfig
    {
        public MyConfig()
        {
            AddLogger(BenchmarkDotNet.Loggers.ConsoleLogger.Unicode);
            AddJob(Job.ShortRun.WithPlatform(Platform.X64).WithGcServer(true).WithRuntime(CoreRuntime.Core70));
            AddJob(Job.ShortRun.WithPlatform(Platform.X64).WithGcServer(true).WithRuntime(NativeAotRuntime.Net70).WithStrategy( BenchmarkDotNet.Engines.RunStrategy.ColdStart).WithId("AOT"));
            AddExporter(BenchmarkDotNet.Exporters.DefaultExporters.Markdown);
            AddExporter(BenchmarkDotNet.Exporters.DefaultExporters.Csv);
            AddAnalyser(EnvironmentAnalyser.Default
                , OutliersAnalyser.Default
                , MinIterationTimeAnalyser.Default
                , MultimodalDistributionAnalyzer.Default
                , RuntimeErrorAnalyser.Default
                , ZeroMeasurementAnalyser.Default
                , BaselineCustomAnalyzer.Default
                , HideColumnsAnalyser.Default
                );
            AddValidator(BaselineValidator.FailOnError
                , SetupCleanupValidator.FailOnError
                , JitOptimizationsValidator.FailOnError
                , RunModeValidator.FailOnError
                , GenericBenchmarksValidator.DontFailOnError
                , DeferredExecutionValidator.FailOnError
                , ParamsAllValuesValidator.FailOnError
                );
            AddColumnProvider(BenchmarkDotNet.Columns.DefaultColumnProviders.Instance);
        }
    }
```

Job.cs
```csharp
    [MemoryDiagnoser]
    public class Method
    {
        private Student student;

        private Action<object,object> expression;
        private MethodInfo methodInfo;

        [GlobalSetup]
        public void Setup()
        {
            student = new Student();
            var par1 = Expression.Parameter(typeof(object));
            var par2 = Expression.Parameter(typeof(object));
            expression = Expression.Lambda<Action<object,object>>(
                Expression.Call(
                        Expression.Convert(par1, typeof(Student)), typeof(Student).GetMethod(nameof(Student.Go)), Expression.Convert(par2, typeof(int))), par1,par2).Compile();
            methodInfo = typeof(Student).GetMethod(nameof(Student.Go));
        }

        [Params(5012)]
        public int LoopCount { get; set; }

        [Benchmark(Baseline = true)]
        public void Raw()
        {
            for (int i = 0; i < LoopCount; i++)
                student.Go(i);
        }
        [Benchmark]
        public void ReflectionCall()
        {
            for (int i = 0; i < LoopCount; i++)
                methodInfo.Invoke(student, new object[] { i });
        }
        [Benchmark]
        public void ExpressionCall()
        {
            for (int i = 0; i < LoopCount; i++)
                expression(student,i);
        }
    }
    public class Student
    {
        public static double B { get; }

        public int Id { get; set; }

        public string Name { get; set; }

        public void Go(int a)
        {

        }
    }
```

Result
![image](https://github.com/dotnet/runtime/assets/26201412/09e0146c-3ce4-4ccb-b4d3-f513d052f07c)

I compile with command `dotnet publish -c Release -f net7.0 -r win-x64`

### Analysis

I don't know.

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/ba775cd50984e0a0fa06526f74feb2c95ace237e/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L28-L29

`Expreesion<T>` should be interpreted in AOT. You can speficy `preferInterpretation` to true to check and compare it's performance.

**Comment by Cricle** [comment]
I try `.Compile(preferInterpretation:true)`

Result
![image](https://github.com/dotnet/runtime/assets/26201412/0b3188ba-b6d5-4237-ae8e-86ef64bb53a1)

**Comment by MichalStrehovsky** [comment]
Why do you have `WithStrategy( BenchmarkDotNet.Engines.RunStrategy.ColdStart)` for NativeAOT but not for CoreCLR? This is comparing apples and oranges. The standard deviations for the NativeAOT run are all over the place.

**Comment by MichalStrehovsky** [comment]
> Is that what you mean?

Yes, thanks.

The difference is very small. @VSadov do you think it would be worthwhile to merge the NativeAOT-specific parts of #82443? I assume it would help a little bit for NativeAOT to get closer to CoreCLR.

Expression trees are not recommended in perf-sensitive code paths with AOT in general because they cannot be compiled and that's a fundamental issue (whether it's 20x slower than compiled or 20.5x slower doesn't make much difference).

**Comment by jkotas** [comment]
What is the NativeAOT-specific part of that PR? It looks all shared between all runtimes to me.

**Comment by VSadov** [comment]
Changes under `nativeaut` and `tools` are NativeAOT-specific. That is the codepath that calls interpreted delgates and marshals strong-typed arguments as object array.

**Comment by VSadov** [comment]
I assume we do not want to touch `System.Linq.Expressions`, but we could take the changes that are outside of that.

**Comment by jkotas** [comment]
Ah ok, it does not change System.Linq.Expression technically. It is changing [System.Linq.Expression code](CreateObjectArrayDelegateRefEmit) that was replicated in the AOT compiler, so it would make the  System.Linq.Expression copy and AOT compiler copy of this logic to diverge.

**Comment by VSadov** [comment]
Since this is just adding a cache, the logic is mostly the same. 

My view on this is that the problems with expression evaluator tend to affect specifically NativeAOT, so maybe it is ok to have some differences. 
The expression evaluator has little use outside of AOT scenarios. The whole deal was created to support one of NativeAOT predecessors. The `preferInterpretation` exists primarily because `#ifdef`'d interpreter was hard to test. It is probably ok if NativeAOT entry point is a bit more optimized.

**Comment by MichalStrehovsky** [comment]
Let's close. This is now documented at https://github.com/dotnet/docs/pull/35483. The performance difference in interpreted expressions can be explained by the fact that the interpreter uses delegates to invoke methods on CoreCLR, but MethodInfo.Invoke in NativeAOT. This is because it may not be possible to construct a delegate without runtime code generation. So we have a penalty from the interpreter, plus an additional penalty because the interpreter is a bit slower without runtime code generation.
