### ISSUE TITLE
Trim analyzer doesn't see members on open generic type

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#86633]
The trim analyzer implementation of enumeration of members doesn't work on open generic types:

```C#
[RequiresUnreferencedCode("test")]
class GenericType<T>
{
    public static int Field;
}

static void RequireFields([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] Type type)
{
}

static void Test()
{
    // Expecting IL2026 about access to a static Field on a type with RUC
    // ILLink and ilc will produce the warning, analyzer will not
    RequireFields(typeof(GenericType<>));
}
```

If it's changed to an instantiated generic it works:
```C#
// IL2026 reported by all tools
RequireFields(typeof(GenericType<int>));
```

**Comment by vitek-karas** [comment]
This seems to be a problem with how we're working on Roslyn type system. The open generic type is represented to us as `NonErrorNamedTypeSymbol`, but that reports to have 0 members. It seems we need to use the `OriginalDefinition` to get to the generic type definition which will report all members correctly.

@agocke as the resident expert on Roslyn type system :-)

**Comment by agocke** [comment]
Sounds right to me. @jtschuster could you take a look?

**Comment by jtschuster** [comment]
FWIW it looks like when reflecting over members of an open generic type, GetValue will fail with `Unhandled exception. System.InvalidOperationException: Late bound operations cannot be performed on fields with types for which Type.ContainsGenericParameters is true.`

If I use MakeGenericType first, then I can trigger the cctor / access the member, but MakeGenericType warns anyway.

Is there another way to trigger the cctor or do anything trim unsafe that wouldn't otherwise warn/throw? Or should there not be warnings on open generic types here? Or maybe it just makes sense to warn for consistency?
