### ISSUE TITLE
[API Proposal]: Recognized internal namespace

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#86682]
### Background and motivation

https://github.com/dotnet/runtime/discussions/85503#discussioncomment-5751203

### API Proposal

```csharp
var type = assembly.GetTypes()[0];
type.IsAvailable //false
assembly.IsAvailable //true or false
assembly.MarkAsReferenceAssembly //true or false 
```

### API Usage

```csharp
if(type.IsAvailable)
{
    usingRecoder.Add(type.Namespace);
}
```

**Comment by steveharter** [comment]
The API suggestion is not clear - is the ask for an `Assembly.IsAvailable` and `Assembly.MarkAsReferenceAssembly`? If so, what are the semantics of those?

**Comment by NMSAzulX** [comment]
@steveharter  Flag "MarkAsReferenceAssembly" means an Assembly marked as a ReferenceAssembly. If exist refs folder,  ReferenceAssembly maybe found in this folder. 
Compare the following code:

```c#
var path = paths = DependencyContext.Default?
            .CompileLibraries.SelectMany(cl => cl.ResolveReferencePaths().Where(asmPath =>
            {
                try
                {
                    return Assembly.LoadFrom(asmPath);
                }
                catch
                {
                    return false;
                }
           }));
```
```c#
var assemblies = AppDomain.CurrentDomain.GetAssemblies();
foreach(var assembly in assemblies ){
  if(assembly.MarkAsReferenceAssembly)
  {
      return assembly;
  }
}
```

My main advice is about Type.:
```c#
var assemblies = AppDomain.CurrentDomain.GetAssemblies();
foreach(var assembly in assemblies ){
  if(assembly.MarkAsReferenceAssembly)
  {
      var types = assembly.ExportTypes;
      foreach(var type in types){
          //this means:
          //The type can be recognized by VS, 
          //         not in internal assembly, 
          //         not the kind of Type that cannot be used even though it is marked as public.
          if(type.IsAvailable)
          { 
             //The result will not contans the type such as the FullName is "Internal.Console".
             return type;
           }
      }
  }
}
```

**Comment by MSDN-WhiteKnight** [comment]
> Flag "MarkAsReferenceAssembly" means an Assembly marked as a ReferenceAssembly.

Reference assembly cannot be loaded into execution context, so this API is useless on Assembly class. It probably needs to be extension method in MetadataLoadContext or something. But it's already easy to detect reference assembly by presence of assembly-level ReferenceAssemblyAttribute. And it probably should be called "IsReferenceAssembly" to match naming guidelines.

>not the kind of Type that cannot be used even though it is marked as public

What are the types that are public but cannot be used? Ones without a public constructor? "IsAvailable" is not a good name anyway because any type declared is assembly is available in some sense (at least to reflection).

**Comment by MSDN-WhiteKnight** [comment]
I've actually found what type you mean: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/Internal/Console.cs

The type is marked as public, but not exposed in reference assembly. It's probably only to make it available in corelib tests without InternalsVisibleTo. There's not a lot of such types to introduce special API for this, i think it's better to special-case them when they are used in runtime reflection. It's hard to detect such types in general case, because reference and implementation assemblies don't always match (for example, APIs from System.Private.CoreLib are exposed by System.Runtime reference assembly). So they need to be special-cased somehow either way.

**Comment by NMSAzulX** [comment]
@MSDN-WhiteKnight Thank you for your reply. The solution is that I can pick available types by type name or use `MetadataLoadContext`, right? 

I had try this way. It is OK to load the referenced assembly with `MetadataLoadContext` and get the namespace of the type. But the `type.Namespace` code has grown by nearly 10 megabytes of memory(MetadataLoadContext.Dispose has been call and exist current method(no inline)). If this problem is solved, it will become an alternative to the issue (PlanB).

**Comment by MSDN-WhiteKnight** [comment]
Yes, in theory you could use MetadataLoadContext to load reference assembly and check if the type is there. You need to have reference assembly available for it - either use PreserveCompilationContext property, or use ones from locally installed SDK somehow. I expect simpler solution would be to special-case these types: if type is in System.Private.CoreLib and namespace starts with "Internal", treat it as internal even if it's public.

>It is OK to load the referenced assembly with MetadataLoadContext and get the namespace of the type. But the type.Namespace code has grown by nearly 10 megabytes of memory

Yes MetadataLoadContext is heavy, i remember people already files issues that it's slower then Cecil. Using System.Reflection.Metadata directly can allow inspecting types faster.

**Comment by NMSAzulX** [comment]
> Yes, in theory you could use MetadataLoadContext to load reference assembly and check if the type is there. You need to have reference assembly available for it - either use PreserveCompilationContext property, or use ones from locally installed SDK somehow. I expect simpler solution would be to special-case these types: if type is in System.Private.CoreLib and namespace starts with "Internal", treat it as internal even if it's public.
> 
> > It is OK to load the referenced assembly with MetadataLoadContext and get the namespace of the type. But the type.Namespace code has grown by nearly 10 megabytes of memory
> 
> Yes MetadataLoadContext is heavy, i remember people already files issues that it's slower then Cecil. Using System.Reflection.Metadata directly can allow inspecting types faster.

Thank you. I have benefited a lot. I will continue to explore. :)

**Comment by steveharter** [comment]
Closing as answered.
