### ISSUE TITLE
Directory.CreateDirectory is able to create invalid folder names

### ISSUE THREAD

**Issue by JaPeterson1** [dotnet/runtime#86874]
### Description

Folder names like con, prn, aux, and several others are not valid on Windows. Running Directory.CreateDirectory should throw an error when the program attempts to create a folder with these names, but instead the invalid folder is created. 

### Reproduction Steps

Run
```c#
Directory.CreateDirectory("C:\\con\\")
```

### Expected behavior

An error should be thrown

### Actual behavior

The invalid directory is created. 

### Known Workarounds

Validation prior to calling CreateDirectory is the best temporary solution. The invalid file names are:
`"con", "prn", "aux", "nul", "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8", "com9", "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9"`

### Configuration

.NET 6.0.16 on Windows 10 version 10.0.19044, x64

### Other information

The Directory.CreateDirectory method is at the link below:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Directory.cs

File.Write works to create, edit, and delete files in the invalid folders. Windows explorer and the command line are both unable to open the invalid folders. The command line or Directory.Delete can delete invalid folders. 

Creating "C:\\a" creates a folder named a. However, creating "C:\\con" will throw an error. The invalid folder's name must end in a path separator for it to be created.

**Comment by danmoseley** [comment]
Hello. This is by design. .NET relies on the underlying OS to judge whether paths are valid or not.

Context: .NET Framework tried very hard to replicate Windows path nuances as amongst other reasons it was necessary for Code Access Security. This was really an impossible task even for Windows, which has idiosyncrasies and ways to create files with names like CON that might be rejected by Win32 API normally. That's ignoring filesystem, policies and configurations. Also OS version - recently Windows began to allow "con" in order to allow Windows programs to read files with such names out of Linux file systems in WSL.

As well as not being possible to do correctly, CAS is now obsolete, and for many years now Windows has been just one of many .NET platforms. Plus, this "validation" had a real perf cost. So modern .NET does not attempt any path validation. The only way to be sure whether a path is valid is to call into the OS.

If that gives inconsistent results, it's an OS bug and should be reported through Windows Feedback.

**Comment by danmoseley** [comment]
Also take a look at https://github.com/microsoft/WSL/issues/2689 and related issues.
