### ISSUE TITLE
Can't run blazor hosted wasm when BlazorWebAssembly project's has private tags for references

### ISSUE THREAD

**Issue by bmzn** [dotnet/runtime#86942]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In my blazor hosted wasm application, I need to set <Private>false</Private> tags under the references because all my external libraries are stored in another root folder. I'm using a custom AssemblyResolver to retrieve the dll in this folder. It works fine for the Server project, but I can't make it work for the Client's one. It keeps showing "Loading..." and never loads, and only works once I remove my <Private> tags. I tried to load them dynamically using AssemblyLoadContext.Default.LoadFromAssemblyPath(string) method, but it can't load them.

### Expected Behavior

We should be able to be able to prevent external libraries to be copied under client's output folder and load them by using an AssemblyResolver.

### .NET Version

6.0.2

**Comment by maraf** [comment]
In context of the browser, dlls need to be downloaded over the network first, when there are ready, they can be loaded using `AssemblyLoadContext`. To make them downloadable, they need to be copied to a location (wwwroot) where web server can serve them. 

Blazor Server is completely different, because the .NET code runs on the server.

What is the motivation of loading dlls manually?
Is the premise of making them downloadable ok for you scenario?

**Comment by bmzn** [comment]
I need to load the dlls manually because they're all in another folder to prevent duplicate dlls.
My arborescence looks like this :
\root
- \AllDlls
- \MyApps\
  - App1
  - App2
  - BlazorAppServer
  - BlazorAppClient

Since they basically all use the same dlls, I'm putting them in the AllDlls folder and retrieve them manually. With "basic" exe application I'm using the AssemblyResolve event to load the dlls from the folder, so I wanted to have similar workflow with my blazor app. 
It works fine for the BlazorAppServer which can retrieve those dlls but not for the client one.
Also, my application is an hosted wasm so if I understand correctly I should be able to "send" needed dlls to my client application ?

**Comment by maraf** [comment]
In Blazor WebAssembly, assemblies get trimmed to reduce download size, so although they are the same assemblies the content of published files might be different for two applications based on what is used in the concrete application. 

You can dissable trimming, but that will increase the download size. 

Are you running in an environment with low server disk space? 

Anyway if you want to do it, you can modify the Blazor startup. The loadBootResource callback gives you ability to modify the URL for each resource that blazor downloads https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources. With that in place and server configured to serve dlls from shared folder, you can achieve the described layout.

**Comment by bmzn** [comment]
As you mentioned, I tried to use the loadBootResource callback, however, it seems that the libraries set with the private tag to false are not loaded and they do not call the loadBootResource callback. Is there any way to like "inject ?" dlls into the webassembly before it starts ?

**Comment by maraf** [comment]
Sorry for late reply. The assemblies get filtered earlier during build because they are marked not be copied to the output. At the moment, there isn't a really nice solution. These are two options that come to my mind
1) Write an after build/publish action that overrides blazor.boot.json config file. The resources/assembly add the assemlies that you want to download from a different location. Then use the loadBootResource in JS to override the location for those assemblies. Keep in mind that blazor.boot.json schema in not public and can change between .NET versions
2) Manually download the assemblies and pass them to .NET the same as blazor lazy loading works. Call the download very early, probably from Main functions. This can only work if the assemblies are not needed before you manually load them. Also, this approach bypass blazor resource cache.
- https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Services/LazyAssemblyLoader.cs#L116
- https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L296

**Comment by bmzn** [comment]
Ok thanks for the info, I will try this soon.
Sorry for the late reply !
