### ISSUE TITLE
Regsvr32 fails with 0x80008093 (seems to be invalid configuration error) on COM Host DLL when it is published in self-contained mode. Works correctly in framework dependent publish.

### ISSUE THREAD

**Issue by rwasef1830** [dotnet/runtime#870]
Hello,
I found a bug in COM registration system. To reproduce this error perform the following steps:

1. Create a .NET Core Project with the following contents:
```cs
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <EnableComHosting>true</EnableComHosting>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```
2. Create a simple class that is exposed to COM:
```cs
    [ComVisible(true)]
    [Guid("A0154EB6-E662-4E34-8E8B-AFF567903D2E")]
    public class TestClass
    {
        public void Test()
        {
            MessageBox.Show("Test");
        }
    }
```

3. In the project directory, run this command: `dotnet publish -r win-x64 -c Release --self-contained`
to create a self-contained publish.

4. Go to the publish output directory (bin\Release\netcoreapp3.1\win-x64\publish), and run regsvr32 on the `Project.comhost.dll` file.

# Expected output:
DllRegisterServer succeeded.

# Actual output:
- RegSvr32
The module "ComHostingSelfContainedPublishRegistrationFailure.comhost.dll" was loaded but the call to DllRegisterServer failed with error code 0x80008093.

- If you repeat the same steps but omit --self-contained from the publish command, the DLL registration will succeed.

- Is self-contained deployment of .Net Core COM components not a supported scenario ?

Migrated from: https://github.com/dotnet/core-sdk/issues/5851
@AaronRobinsonMSFT  @jkoritzinsky

**Comment by jeffschwMSFT** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
>Is self-contained deployment of .Net Core COM components not a supported scenario ?

@rwasef1830 It is not a support scenario in this case, at least from the server project itself. This is specifically blocked since success would be very hard to achieve unless there is only a single managed COM server in an application. The reason here is related to potentially having multiple CoreCLR instances in a single process.

https://github.com/dotnet/runtime/blob/b52ce534329e79547630bcba6102a86ca3fccb23/src/installer/corehost/cli/fxr/fx_muxer.cpp#L576-L581

Is this scenario something that is of interest or merely investigation? What would your expectations be for where other managed COM servers would load/discover the CLR?

/cc @vitek-karas @elinor-fung

**Comment by rwasef1830** [comment]
@AaronRobinsonMSFT I guess it makes sense to prevent the possibility of multiple CoreCLR instances from loading in a single process... But it should be at least documented to prevent surprise :-)

It's not a high priority to have for me, I just thought it would be a nice thing to have, but I recognize that multiple CoreCLRs in a single process can be very problematic. I guess then it matches .NET Framework semantics.

So actually the real problem is that this is not documented.

**Comment by AaronRobinsonMSFT** [comment]
>But it should be at least documented to prevent surprise :-)

Very much agreed. Thank you for letting us know about the missing restrictions.

**Comment by DoCode** [comment]
@AaronRobinsonMSFT what about out-of-process COM server in .NET Core?

**Comment by AaronRobinsonMSFT** [comment]
@DoCode I am a big fan of out-of-proc COM, has some performance concerns but addresses many issues. As far as setting up an activatable COM server in a .NET Core application, that is probably possible but will require working with the [hosting API](https://github.com/dotnet/runtime/blob/master/docs/design/features/native-hosting.md) and having a good understanding of authoring a [COM server](https://docs.microsoft.com/windows/win32/com/com-clients-and-servers) in general. It may also require some additional work if the interfaces aren't defined in MIDL because `TlbExp` doesn't exist for .NET Core.  In order to consume the interfaces in a non-managed environment, headers or a TLB and [proxy/stubs](https://docs.microsoft.com/windows/win32/com/building-and-registering-a-proxy-dll) would need to be created and registered.

There is also the slightly cheaper way to get to an out-of-proc COM scenario using the [Running Object Table](https://docs.microsoft.com/windows/win32/api/objidl/nn-objidl-irunningobjecttable). A managed example using .NET Framework is [here](https://github.com/AaronRobinsonMSFT/COMInterop/tree/master/OutOfProcDemo).

The above aside, the build issue being faced in this scenario involves building a COM server class library, not a standalone application. A .NET Core application - not library - exposing a COM server should build in a self-contained manner, however that scenario hasn't been tested in .NET Core - see the [COM-activation](https://github.com/dotnet/runtime/blob/master/docs/design/features/COM-activation.md) design documentation for .NET Core.

**Comment by elinor-fung** [comment]
Documentation has been updated to indicate that self-contained .NET Core COM components are not supported: dotnet/docs#17792
