### ISSUE TITLE
Difference in X509Chain output on Linux and Windows

### ISSUE THREAD

**Issue by engelhardtda** [dotnet/runtime#87010]
### Description

We are currently trying to do CA pinning via implementing the "ServerCertificateCustomValidationCallback".
Therefore we want to check the root CA of the certification chain. Running our code on an Windows machine works fine since the X509Chain object returns the whole chain up to the root CA Certificate. Running the code on Linux (Ubuntu 20.04) gives us less certificates. Also the the output contains certificates which do not appear in windows

### Reproduction Steps

Sample code used for generating the outputs:
`
    private static async Task Main(string[] args)
    {
        var httpHandler = new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = (HttpRequestMessage message, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) =>
            {
                foreach (var chainElement in chain.ChainElements)
                {
                    Console.WriteLine($"{chainElement.Certificate.IssuerName.Name} with CertHash {chainElement.Certificate.GetCertHashString()}");
                }
                return false;
            }
        };
        HttpClient httpClient = new(httpHandler)
        {
            BaseAddress = new Uri("https://acloudguru.com/")
        };
        using var requestMessage = new HttpRequestMessage(HttpMethod.Get, "/");
        try
        {
            var response = await httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseContentRead);
            var responseString = await response.Content.ReadAsStringAsync();
        }
        catch (Exception ex)
        {
        }
        Console.ReadLine();
    }
`

### Expected behavior

I would expect the output on windows and linux to be the same.
If the depth causes a problem there should be an option to get the whole chain.

### Actual behavior

Here is the example output

Windows:

CN=Amazon RSA 2048 M01, O=Amazon, C=US with CertHash E78F52875A105DE655EA64E8B859F7B67CD28AE3
CN=Amazon Root CA 1, O=Amazon, C=US with CertHash 2AD974A775F73CBDBBD8F5AC3A49255FA8FB1F8C
CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, S=Arizona, C=US with CertHash 06B25927C42A721631C1EFD9431E648FA62E1E39
OU=Starfield Class 2 Certification Authority, O="Starfield Technologies, Inc.", C=US with CertHash 9E99A48A9960B14926BB7F3B02E22DA2B0AB7280
OU=Starfield Class 2 Certification Authority, O="Starfield Technologies, Inc.", C=US with CertHash AD7E1C28B064EF8F6003402014C3D0E3370EB58A

Same domain on Ubuntu 20.04;

CN=Amazon RSA 2048 M01, O=Amazon, C=US with CertHash E78F52875A105DE655EA64E8B859F7B67CD28AE3
CN=Amazon Root CA 1, O=Amazon, C=US with CertHash 2AD974A775F73CBDBBD8F5AC3A49255FA8FB1F8C
CN=Amazon Root CA 1, O=Amazon, C=US with CertHash 8DA7F965EC5EFC37910F1C6E59FDC1CC6A6EDE16

**Comment by vcsjones** [comment]
Different platforms and versions will differ in how their chains are built depending on how the platform's trust store is represented.

It looks like [2AD974A775F73CBDBBD8F5AC3A49255FA8FB1F8C](https://crt.sh/?sha1=2AD974A775F73CBDBBD8F5AC3A49255FA8FB1F8C) chain up to different roots due to cross signing.

The [8DA7F965EC5EFC37910F1C6E59FDC1CC6A6EDE16](https://crt.sh/?sha1=8DA7F965EC5EFC37910F1C6E59FDC1CC6A6EDE16) root is in the Ubuntu trust store. For your Windows instance, it does not, so it goes up to the star field cross signing.

This is the trust graph of the 8DA certificate:

<img width="761" alt="image" src="https://github.com/dotnet/runtime/assets/361677/2e98b2e6-149e-48e2-9a6c-dff5b16ff508">

From that perspective, the OS is just building the best chain that it can. When the Windows trust store becomes aware of the new root, it's probably going to start building the shorter chain.

> If the depth causes a problem there should be an option to get the whole chain.

The are both returning the whole chain. They are just different chains, because chain building is really a graph problem, and there is no one "single" chain when cross signing gets involved, and almost all CAs use cross signing to some extent to stand up new CAs.

> I would expect the output on windows and linux to be the same.

This is not a fair expectation - chains are going to change on the trust store environmental factors. The chain that is built will vary between platforms, or even within the same platform depending on the OS updates and OS version.

If you want to pin to a particular root then you should consider using [`CustomTrustStore`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.customtruststore?view=net-7.0) and give it the roots that you explicitly trust, and give `ExtraStore` all of the needed intermediates to build to that root(s).

**Comment by SteveSyfuhs** [comment]
Also note that when you're pinning a certificate issuer, you should pin the most stable intermediate certificate closest to the leaf certificate. Pinning to a root means an attacker just needs to compromise something within the root's scope, which can potentially be quite broad. Targeting a smaller scope is generally safer.

**Comment by engelhardtda** [comment]
Thank you very much for the detailed explanation @vcsjones 
We where also looking at the 'openssl showcerts' command and got the chain up to the Starfield Root CA - that got us confused. But I guess they are using their own trust store, if I understand correctly.
Also importing the Amazon CA Cert in the Windows certificate store causes us to have the same output like on Linux, exactly as you explained.

Also thanks for the hint @SteveSyfuhs we are aware of that, basically we are in an non-update-friendly environment so we need to be stable as long as possible... its a trade...

**Comment by vcsjones** [comment]
Since everything is working as expected, I'm going to close this issue out. Please feel free to re-open this issue or open a new issue if there are any additional concerns.
