### ISSUE TITLE
[API Proposal]: Add stream support to IDbConnection

### ISSUE THREAD

**Issue by denisenko93** [dotnet/runtime#87092]
### Background and motivation

Streaming in Database connection helps to execute very large sql scripts in database with small memory usage.
Example usages:
1. Put large sql files to database (like as database dump)
2. Generate sql script and put it to database directly (without loading script in memory)

### API Proposal

```csharp
namespace System.Collections.Generic;

public interface IDbConnection
{
    public Stream GetStream();
}
```

### API Usage

```csharp
IDbConnection connection = new MyDbConnection();

using(Stream stream = connection.GetStream())
{
    using(StreamWriter writer = new StreamWriter(stream))
   {

        bool first = true;
        writer.Write("INSERT INTO sample_table (id, name) VALUES");
        foreach(DataItem item in GetData())
        {
             if(!first)
             {
                 writer.Write(",");
             }
             else
             {
                 first = false;
             }

             writer.Write($"({item.Id}, '{item.Name}')");
        }
        writer.Write(";");
   }
}
```

**Comment by MMaximus111** [comment]
Cool idea!

**Comment by roji** [comment]
If I understand the proposal correctly, it would allow streaming the SQL to be executed at the database. In other words, instead of creating a DbCommand and assigning its CommandText to an in-memory string, the SQL would be streamed instead.

Executing huge SQL files is almost exclusively a one-time operation, e.g. restoring a database dump as mentioned above; in those scenarios, the memory footprint typically isn't important. Memory savings are typically important in an operation that's likely happen over and over again in the lifetime of the application. Note also that for efficient operation, you typically don't want to use a huge SQL script anyway, but rather a database-specific backup/restore mechanism or bulk-insert mechanisms such as SqlBulkCopy; these are already efficient and support streaming where needed.

In theory, this could be helpful where the SQL script is simply too large to fit in memory (I have yet to hear about anyone actually running into this problem). But as above, in those cases, using a SQL script is likely the wrong thing any way.

Adding an API to System.Data also means that all providers must implement it; this is unlike other areas of .NET, where functionality can simply be added. As a result, it's usually important for the proposal to deliver substantial value, which I don't think is the case here.

**Comment by Wraith2** [comment]
This feels like something that is only useful for MySql because other providers have totally different methods of bulk load or database restore.

**Comment by denisenko93** [comment]
So. I am using MySql in my project. MySql supports `MySqlBulkLoader`. But in my case I need to update some columns if the row exists, for example `ON DUPLICATE KEY UPDATE count = count + 1`

Another case is updating many rows in a database:

```
StringBuilder sb = new StringBuilder()
foreach(Data data in GetData())
{
   sb.AppendLine($"UPDATE data_table SET name = {data.Name} WHERE id = {data.Id};");
}
```

Problems in these cases:
1. I need more memory on the server to store all the scripts in memory
2. If the length of the script exceeds 40,000 characters, the GC creates it in LOH, and this affects the speed of the GC memory cleanup if I have many concurrent executions

**Comment by Wraith2** [comment]
For those operations you should use a single parameterised query and then update the parameter and execute in the loop. There is no benefit to generating a huge script. If you run into performance issues with the roundtrip time on individual queries per item then bulk upload the new data into a temp table and then execute a single command to update the target from the temp data and apply any logic there.

**Comment by roji** [comment]
Agree with @Wraith2 - you can also batch a certain number of these UPDATE (e.g. 1000) if it makes sense, to cut down on memory requirements. But I also agree that bulk upload into a temporary table (via MySqlBulkLoader) then merging is probably the way to go.

**Comment by denisenko93** [comment]
Thanks for your advice. This is a good decision. But MySqlBulkLoader is a database-specific function. I would like to have a universal tool for working with a large amount of data in the database. Thank you

**Comment by roji** [comment]
I'll go ahead and close this issue as something we don't plan to work on. If we see more interest in an ADO.NET abstraction over provider bulk-insert APIs, we can revisit this. The Stream-based API to stream a large SQL command is not something I believe is a good way to import large data.
