### ISSUE TITLE
Add support for LPArray when marshalling struct fields

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#8719]
Today, I have finally found the reason, why my DBus implementation works with Mono, but doesn't with .NET Core:
```
System.TypeLoadException: Cannot marshal field 'control' of type 'msghdr': Unknown error.
    at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkList& pCleanupWorkList)
    at Dbus.Connection.recvmsg(IntPtr sockfd, msghdr& buf, Int32 flags)
    at Dbus.Connection.receive()
```
Here's a quick copy of the code from [here](https://github.com/Tragetaschen/DbusCore/blob/3e0d30ca8e29605d85cd6eddfb771db9d36684aa/src/Dbus/Connection.Receive.cs#L9)
```cs
[DllImport("libc")]
private static extern int recvmsg(IntPtr sockfd, [In] ref msghdr buf, int flags);

private unsafe struct iovec
{
    public byte* iov_base;
    public int iov_len;
}

private unsafe struct msghdr
{
    public IntPtr name;
    public int namelen;
    public iovec* iov;
    public int iovlen;
    public int[] control;
    public int controllen;
    public int flags;
}
```

When calling `recvmsg`, Mono is fine with marshalling the `control` member of `msghdr`. For .NET Core (1.1 and 2.0-preview2), I had to change `int[]` to `int*` and add another fixed statement to my code.

The `Unknown error` makes me wonder if there's something missing in .NET Core.

**Comment by garrynewman** [comment]
This would save a ton of energy, thanks for looking into it

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung and @jkoritzinsky Let's make sure the struct marshalling for DllImport source generation can handle this case. https://github.com/dotnet/runtime/issues/46838.

**Comment by AaronRobinsonMSFT** [comment]
Now that the [LibraryImport generator](https://github.com/dotnet/runtime/issues/60595) (i.e., source generated `DllImport`s) has been exposed as a publicly consumable tool, this issue should be explored relative to that effort. This specific issue is being close due to lower priority relative to other interop needs and should be solved using the source generator.

Support for marshalling customized types can be found in the new API described at https://github.com/dotnet/runtime/issues/66121.
