### ISSUE TITLE
Blazor - System.Security.Cryptography.Algorithms is not supported on this platform

### ISSUE THREAD

**Issue by PeterSomosDF** [dotnet/runtime#87214]
I have a Blazor WebApp, with .net6. I'd like to use encryption/decryption in it, but if I try to use System.Security.Cryptography.Algorithms, I get the exception, that it is not supported in a browser.
I've seen, that this was an issue with .net5, but I do not see any solution for .net6.
Is there any workaround, or a real solution for this problem?
Thank you for the response!

**Comment by martincostello** [comment]
As far as I can see [in the breaking changes documentation](https://learn.microsoft.com/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly) this is still the case.

.NET ultimately delegates cryptographic operations to the underlying host platform, so it is constrained by what native JavaScript functionality is available to browsers in the case of Blazor.

**Comment by PeterSomosDF** [comment]
Unfortunately I haven't seen any changes in the documentation neither. :( As this problem is pretty old, I wanted to check, if there is a good workaround for this problem, or any real solution, that would fix it...

**Comment by vcsjones** [comment]
For .NET 5, the SHA-2 family of hashing algorithms are supported. For .NET 7, the HMAC SHA-2 family of algorithms are also supported.

Symmetric encryption is currently not implemented and it will not be for .NET 8. An attempted to introduce AES was made for .NET 7, but it [was reverted](https://github.com/dotnet/runtime/issues/738580). The linked issue goes in to the challenges that prevented it from shipping.

You can use AES from Blazor, however you need to interop with `SubtleCrypto` yourself. The standard .NET classes like `Ads` will not work. There is an example on how to do so here:

https://github.com/dotnet/designs/blob/main/accepted/2021/blazor-wasm-crypto.md#blazor-wasm--js-interop-example

The example uses HMAC, however it shows the basic concepts for interoping with SubtleCrypto.

**Comment by PeterSomosDF** [comment]
The situation is the following: we already have a Xamarin Forms solution, which uses the default System.Security.Cryptography.Algorithms to encrypt/decrypt passwords.
We've implemented a Blazor page, which should be able to use the very same methods, or at least result in the very same encrypted/decrypted values, as the Xamarin Forms solution.
Do you think, that it would be somehow possible?

**Comment by vcsjones** [comment]
> The situation is the following: we already have a Xamarin Forms solution, which uses the default System.Security.Cryptography.Algorithms to encrypt/decrypt passwords.
We've implemented a Blazor page, which should be able to use the very same methods, or at least result in the very same encrypted/decrypted values, as the Xamarin Forms solution.
Do you think, that it would be somehow possible?

Unfortunately not. If you are using any built-in symmetric encryption in .NET, like `Aes.Create()`, `new AesCryptoServiceProvider()`, etc. (and repeat for other symmetric encryption algorithms like 3DES) then it is currently not implemented in the Runtime.

Xamarin Forms is able to do this because I believe it uses Mono's implementation of Aes, [which is written in C#](https://github.com/mono/mono/blob/771947925a512a91e1ac88eb463ec845cafc2807/mcs/class/System.Core/System.Security.Cryptography/AesTransform.cs#L440).

The .NET Runtime has a different policy here: cryptographic primitives are preferred to be used as provided by the platform. For Windows that's CNG, for macOS that's SecurityTransforms or CryptoKit, and Linux it's OpenSSL.

In browser / wasm that would be SubtleCrypto. Unfortunately, SubtleCrypto has an async-only design, and sync-over-async is WASM has some significant barriers that prevented SubtleCrypto from being adopted.

For Hashing, it was decided that using a managed implementation was a possible solution. However a purely managed implementation of symmetric and asymmetric cryptography was not accepted.

The only current way to gain symmetric cryptography in Blazor / wasm is:

1. Use a 3rd party package that implements the algorithms as you need, and is capable of executing as Blazor.  Developers will need to understand the tradeoffs of using 3rd party packages such as compliance, patching, etc.
2. Use JSInterop to asynchronously use SubtleCrypto.

**Comment by TimPurdum** [comment]
https://github.com/dotnet/runtime/pull/70915 reads as if this was solved in July 2022, but as @vcsjones said, it was reverted https://github.com/dotnet/runtime/issues/73858. I'm adding these links here because there was no link from the initial PR making it apparent that the changes were reverted.

**Comment by vcsjones** [comment]
Given that the behavior is intentional, and it appears that all questions have been answered, I am going to close this out. Please feel free to re-open the issue if there are any unaddressed concerns or questions.
