### ISSUE TITLE
[Performance] Startup regression

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#87235]
![image](https://github.com/dotnet/runtime/assets/1165805/96b5c6b5-742b-4557-8ae5-b1aaca794b68)

Smallest commits set:
https://github.com/dotnet/runtime/compare/fe980088a91c65a6f021ab788d703211f4fc6427...10222f94e5d89b19959117dd9e5b8576ef63f878

Crank command lines:

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/json.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario mapaction --profile intel-lin-app --profile intel-load2-load --application.framework net8.0 --application.collectDependencies true --application.options.collectCounters true --application.aspNetCoreVersion 8.0.0-preview.6.23302.1 --application.runtimeVersion 8.0.0-preview.6.23305.2 --application.sdkVersion 8.0.100-preview.6.23305.4

crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/json.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario mapaction --profile intel-lin-app --profile intel-load2-load --application.framework net8.0 --application.collectDependencies true --application.options.collectCounters true --application.aspNetCoreVersion 8.0.0-preview.6.23302.1 --application.runtimeVersion 8.0.0-preview.6.23306.5 --application.sdkVersion 8.0.100-preview.6.23305.4
```

**Comment by EgorBo** [comment]
Seems like arm64 is not affected

**Comment by sebastienros** [comment]
@EgorBo you are correct, was checking and the last run is past the culprit build on these machines too.

**Comment by EgorBo** [comment]
Methods jitted `3,644` --> `11,398` so something went wrong with R2R, perhaps, @jkotas can spot an offender
My guess is https://github.com/dotnet/runtime/pull/85551 (cc @tannergooding)

**Comment by tannergooding** [comment]
Is there an easy way to get a list of functions that are now jitted that weren't before?

**Comment by tannergooding** [comment]
I had done the r2rdump check for corelib as part of the PR and hadn't seen any differences; but maybe I had done something wrong here...

**Comment by EgorBo** [comment]
> Is there an easy way to get a list of functions that are now jitted that weren't before?

```
--application.environmentVariables DOTNET_JitDisasmSummary=1 --application.options.displayOutput true
```
should do the trick

**Comment by EgorBo** [comment]
I guess it makes sense to add a smoke test to dotnet/sdk to e.g. check number of entries in JitDisasmSummary for a hello word. E.g if we see, say, more than 200 (etw thing) - something went wrong

**Comment by tannergooding** [comment]
Not quite back to where we should be in the official runs:
![image](https://github.com/dotnet/runtime/assets/10487869/1090d149-e7ad-4399-9808-3299bcc7e4c7)

**Comment by tannergooding** [comment]
Looks like we're still jitting more methods than before. This looks to be because ASP.NET Core is using a crossgen2 version that has the issue. Once it pulls in an updated version of the SDK with the fix it should be resolved.

| application                             | baseline                  | diff                      |         |
| --------------------------------------- | ------------------------- | ------------------------- | ------- |
| CPU Usage (%)                           |                        99 |                        99 |   0.00% |
| Cores usage (%)                         |                     2,781 |                     2,770 |  -0.40% |
| Working Set (MB)                        |                       458 |                       468 |  +2.18% |
| Private Memory (MB)                     |                     1,233 |                     1,242 |  +0.73% |
| Build Time (ms)                         |                     3,446 |                     6,121 | +77.63% |
| Start Time (ms)                         |                       214 |                       320 | +49.53% |
| Published Size (KB)                     |                    90,772 |                    91,037 |  +0.29% |
| Symbols Size (KB)                       |                        21 |                        22 |  +4.76% |
| .NET Core SDK Version                   | 8.0.100-preview.6.23305.4 | 8.0.100-preview.6.23308.7 |         |
| Max CPU Usage (%)                       |                        99 |                       100 |  +0.97% |
| Max Working Set (MB)                    |                       480 |                       490 |  +2.16% |
| Max GC Heap Size (MB)                   |                       325 |                       321 |  -1.40% |
| Size of committed memory by the GC (MB) |                       414 |                       422 |  +1.81% |
| Max Number of Gen 0 GCs / sec           |                      1.00 |                      1.00 |   0.00% |
| Max Number of Gen 1 GCs / sec           |                      1.00 |                      1.00 |   0.00% |
| Max Number of Gen 2 GCs / sec           |                      1.00 |                      1.00 |   0.00% |
| Max Time in GC (%)                      |                      0.00 |                      0.00 |         |
| Max Gen 0 Size (B)                      |                       584 |                       584 |   0.00% |
| Max Gen 1 Size (B)                      |                 4,041,864 |                 4,048,776 |  +0.17% |
| Max Gen 2 Size (B)                      |                 3,996,016 |                 4,036,208 |  +1.01% |
| Max LOH Size (B)                        |                   775,072 |                   873,264 | +12.67% |
| Max POH Size (B)                        |                 1,187,064 |                 1,187,064 |   0.00% |
| Max Allocation Rate (B/sec)             |               173,551,248 |               176,208,664 |  +1.53% |
| Max GC Heap Fragmentation               |                         1 |                         1 |  +9.54% |
| # of Assemblies Loaded                  |                        88 |                        93 |  +5.68% |
| Max Exceptions (#/s)                    |                       458 |                       436 |  -4.80% |
| Max Lock Contention (#/s)               |                        96 |                        48 | -50.00% |
| Max ThreadPool Threads Count            |                        48 |                        48 |   0.00% |
| Max ThreadPool Queue Length             |                       199 |                       160 | -19.60% |
| Max ThreadPool Items (#/s)              |                 1,105,618 |                 1,123,343 |  +1.60% |
| Max Active Timers                       |                         1 |                         1 |   0.00% |
| IL Jitted (B)                           |                   366,491 |                   524,816 | +43.20% |
| Methods Jitted                          |                     3,634 |                     6,871 | +89.08% |


| load                   | baseline   | diff       |         |
| ---------------------- | ---------- | ---------- | ------- |
| CPU Usage (%)          |         67 |         68 |  +1.49% |
| Cores usage (%)        |      1,884 |      1,899 |  +0.80% |
| Working Set (MB)       |         48 |         48 |   0.00% |
| Private Memory (MB)    |        358 |        358 |   0.00% |
| Start Time (ms)        |          0 |          0 |         |
| First Request (ms)     |        215 |        311 | +44.65% |
| Requests/sec           |    974,651 |    974,338 |  -0.03% |
| Requests               | 14,716,749 | 14,711,973 |  -0.03% |
| Mean latency (ms)      |       0.44 |       0.47 |  +6.46% |
| Max latency (ms)       |      48.19 |      43.77 |  -9.17% |
| Bad responses          |          0 |          0 |         |
| Socket errors          |          0 |          0 |         |
| Read throughput (MB/s) |     201.70 |     201.64 |  -0.03% |
| Latency 50th (ms)      |       0.24 |       0.24 |  -0.84% |
| Latency 75th (ms)      |       0.28 |       0.28 |  -0.36% |
| Latency 90th (ms)      |       0.32 |       0.32 |  +1.25% |
| Latency 99th (ms)      |       7.82 |       8.65 | +10.61% |
