### ISSUE TITLE
Reduce duplication between InstrumentRecorder and MeterCollector

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#87243]
In .NET 8 we introduced the [InstrumentRecorder API](https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/Metrics/InstrumentRecorder.cs,14) to aid with unit testing metrics. dotnet/extensions has also introduced their [MeterCollector](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Telemetry.Testing/Metering/MetricCollector.cs#L22) which serves a similar purpose. Preferably I'd like to avoid releasing two different test helpers for what appears to be the same scenario. 

- [ ] - Martin is going to review the MeterCollector API to see if there is any functionality which is important to bring to InstrumentRecorder
- [ ] - If needed, make changes to InstrumentRecorder
- [ ] - Either remove MeterCollector, or determine it still has a role to play that is not covered by InstrumentRecorder.

cc @geeknoid @dpk83 @tarekgh @JamesNK

**Comment by geeknoid** [comment]
Here's my analysis of the two models:

MetricCollector is designed for real-world use in unit tests whereas InstrumentRecorder is minimalistic in nature, providing the bare minimum functionality. Whereas InstrumentRecorder just gives you an enumerable (not indexable!) list of measurements, MetricCollector offers a number of facilities that are intended to make writing tests simpler:

* MetricCollector has methods to directly obtain the value of specific instruments (GetCounterValue, GetHistogramValue) which is usually what you want to do in tests.

* MetricValuesHolder<T> has the LatestWritten, LatestWrittenValue, and GetValue functions which are frequently useful in tests.

* MetricCollector captures timestamps for the individual measurements which is often useful in tests.

* MetricCollector makes it easy to capture groups of instruments, rather than needing distinct recorders.

* MetricCollector has a clear method making it convenient to reuse in tests.

I recommend that we remove InstrumentRecorder from the runtime, and rely on MetricCollector as the solution we document and recommend to customers.

@dpk83

**Comment by JamesNK** [comment]
I think we need to see how `MeterCollector` features are used to understand any gaps.

Some feedback:

> Whereas InstrumentRecorder just gives you an enumerable (not indexable!) list of measurements

Someone could call `ToList()` on the measurements returned if they want to index over them. If this is common then `InstrumentRecorder` could be changed to return `IReadOnlyList<T>` instead of enumerable.

I've been using `Assert.Collection` to assert returned measurements, so an indexer wasn't important.

> MetricCollector captures timestamps for the individual measurements which is often useful in tests.

I'm skeptical that a timestamp is useful. Almost always, you want to abstract time away in unit tests. But I'd be curious to see how timestamp is used with meter collector tests.

> MetricCollector has a Clear method making it convenient to reuse in tests.

`InsturementRecorder` supports clear today.

**Comment by geeknoid** [comment]
@JamesNK I don't see a Clear method on InstrumentRecorder, but I just noticed the clear argument on the GetMeasurements method which was a bit surprising.

Time should in fact be abstracted from tests, this is why we introduced TimeProvider. MetricCollector integrates with TimeProvider and lets you get reliable time values which lets you get an understanding of the relative occurrence of different activities within a test. FakeLogger also integrates with TimeProvider so you can correlate logs an metering activity.

Please see https://domoreexp.visualstudio.com/R9/_git/SDK (Microsoft internal link) for many uses of the metric collector, in addition to the ones in https://github.com/dotnet/extensions.

**Comment by tarekgh** [comment]
After examining the MetricCollector, I have made the following observations:

- The MetricCollector encompasses a broader range of test scenarios compared to the original design of the InstrumentRecorder. In fact, the MetricCollector is designed similar to the MeterListener scenarios, whereas the InstrumentRecorder is intended for listening to a single instrument to keep things simple.
- The MetricCollector can be considered a superset of the InstrumentRecorder, but the latter is much simpler to use when only monitoring one instrument is required. In terms of complexity, the MetricCollector falls somewhere between the InstrumentRecorder and the MeterListener.
- MetricCollector does not natively support the IMeterFactory.
- Regarding the testing scenarios covered by the MetricCollector, it's unclear whether they represent actual product scenarios or merely serve as support. Are these scenarios genuinely useful in providing comprehensive coverage?

Based on these observations, I would suggest removing the InstrumentRecorder from the runtime and relying solely on the MetricCollector as the recommended solution documented for customers.

I agree with the principle that having both the InstrumentRecorder and the MetricCollector is unnecessary. Since the MetricCollector covers a wider range of scenarios and is still relatively simple to use for testing purposes, it should be retained. However, I do not support incorporating the features of the MetricCollector into the runtime, as it would create confusion in distinguishing between the MetricCollector and the MeterListener. Therefore, I lean towards agreeing with the removal of the InstrumentRecorder from the runtime.

**Comment by geeknoid** [comment]
@tarekgh Do you have suggestions on how to make MetricCollector easier to use? It'd be a snap to add more convenience constructors or accessors as needed to bridge the gap.

**Comment by tarekgh** [comment]
> Do you have suggestions on how to make MetricCollector easier to use? It'd be a snap to add more convenience constructors or accessors as needed to bridge the gap.

I was thinking of the scenario for listening to one instrument as InstrumentRecorder does. Maybe if we can think of having MetricCollector mode for single instrument that can help. 

> Is there a need to allow meter tests in runtime and aspnetcore?

Do yu mean use MetricCollector in runtime and aspnet testing? aspnet for sure will need to use it as it is currently using InstrumentRecorder. But nothing prevents our tests from depending on the R9/extension package.

**Comment by geeknoid** [comment]
For reference: https://github.com/dotnet/extensions/pull/4055

**Comment by JamesNK** [comment]
> @JamesNK I don't see a Clear method on InstrumentRecorder, but I just noticed the clear argument on the GetMeasurements method which was a bit surprising.

You need a way to clear when getting measurements, otherwise there is a race between the last measurements you saw and a background process adding more measurements while a separate clear method is called. It needs to happen in the same lock.

**Comment by noahfalk** [comment]
I did some of my own research. Short story: I think InstrumentRecorder with a few ergonomic adjustments would make a better API but its not a strong position. If folks read through my concerns below and decide they want the MetricCollector API + support for scopes and InstrumentRecorder gets removed then I'm not going to object to that.

Longer story:

These are my concerns with the existing MetricCollector API:
- It doesn't currently support scopes (aka IMeterFactory). This means concurrently running tests that listen to the same Meters by name may fail non-determistically. Replacing `MetricCollector(IEnumerable<string> meterNames, TimeProvider? timeProvider = null)` and `MetricCollector(TimeProvider? timeProvider = null)` with `MetricCollector(object? scope, IEnumerable<string> meterNames, TimeProvider? timeProvider = null)` and `MetricCollector(object? scope, TimeProvider? timeProvider = null)` respectively would alleviate that problem. I consider this one important, but fixable.

- MetricCollector's abstraction of collected measurements seems inconsistent (or I screwed up analyzing the code). In some cases it aggregates, in other cases it doesn't, and I am not sure how users are intended to predict the behavior other than trying it experimentally or looking it up in a doc. For example without reverse engineering the code, try to predict what numbers you should expect to see in the asserts for this test:
```C#
//arrange
Meter m = ...
ObservableGauge og = m.CreateObservableGauge<int>("OG", () => Random.Shared.Next());
ObservableUpDownCounter oc = m.CreateObservableUpDownCounter<int>("OC", () => Random.Shared.Next());
Counter c = m.CreateCounter<int>("C");
Histogram h = m.CreateHistogram<int>("H");
MetricCollector collector = new MetricCollector(m);

//act
collector.CollectObservableInstruments();
c.Add(4);
h.Record(4);
collector.CollectObservableInstruments();
c.Add(7);
h.Record(7);

//assert
Assert.Equal(??, collector.GetObservableGaugeValues("OG").AllValues.Count);
Assert.Equal(??, collector.GetObservableCounterValues("OC").AllValues.Count);
Assert.Equal(??, collector.GetCounterValues("C").AllValues.Count);
Assert.Equal(??, collector.GetHistogramValues("H").AllValues.Count);
```
For InstrumentRecorder the answer in every case would be 2.

These remaining concerns are relatively minor and subjective IMO...

- The case for a single instrument even with Martin's changes is still more complex. The instrument needs to be identified once in the constructor and again every time it is queried. I do recognize this is a mixed bag. MetricCollector's API is more ergonomic in cases where a single Meter is being queried for multiple instruments, and less ergonomic when data for same instrument is being queried repeatedly. I found examples of both in the source, though by far the most common case I noticed in my search were tests that looked at one instrument one time.

- MetricCollector has APIs like GetAllHistograms() and tests seemed to be taking advantage of that to take, IMO, questionable shortcuts. Rather than write the name of the instrument they wanted to verify instead they would get all instruments of a certain type, use the first instrument in the collection and assume that is the one they intended to test. If the name of such an instrument ever changes users are going to be impacted but the unit test isn't going to flag it.

- MetricCollector doesn't expose the Instrument object itself. This should be easily fixable, but as-is it prevents anyone from writing a unit test that verifies the metadata on the instrument is correct such as the Unit or the Description.

- I recognize this one is very subjective, but IMO the MetricCollector API is overly rich which may hurt more than it helps for code devs are interacting with infrequently and aren't likely to remember by heart. At the moment I think InstrumentRecorder is a bit too lean (I absolutely intended InstrumentRecorder.GetMeasurements() to be indexable, this is a fixable oversight) but adding a few additional ergonomics to a lean API is easier than simplifying one that is already more complex.

**Comment by geeknoid** [comment]
> > @JamesNK I don't see a Clear method on InstrumentRecorder, but I just noticed the clear argument on the GetMeasurements method which was a bit surprising.
> 
> You need a way to clear when getting measurements, otherwise there is a race between the last measurements you saw and a background process adding more measurements while a separate clear method is called. It needs to happen in the same lock.

Just like you're skeptical of the need to associated TimeProvider with MetricCollector, I am quite skeptical abound this inherently racy design in a unit test :-)

**Comment by tarekgh** [comment]
We removed InstrumentRecorder from the runtime and the MeterCollector implementation is updated too. 

https://github.com/dotnet/runtime/pull/87873
