### ISSUE TITLE
DateTime "MMM" format is inconsistent for June, July, September if day is also part of format

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [dotnet/runtime#87307]
### DateTime "MMM" format is inconsistent

```
        static void Main(string[] args)
        {
            for (var m = 1; m <= 12; m++)
            {
                var date = new DateTime(2023, m, 1);
                Console.WriteLine($"{date.ToString("dd MMM yyyy")} | {date.ToString("MMM yyyy")}");
            }
        }
```

### Broken in .NET5, .NET6, .NET7

```
01 Jan 2023 | Jan 2023
01 Feb 2023 | Feb 2023
01 Mar 2023 | Mar 2023
01 Apr 2023 | Apr 2023
01 May 2023 | May 2023
01 June 2023 | Jun 2023  <<<<<<
01 July 2023 | Jul 2023  <<<<<<
01 Aug 2023 | Aug 2023
01 Sept 2023 | Sep 2023  <<<<<<
01 Oct 2023 | Oct 2023
01 Nov 2023 | Nov 2023
01 Dec 2023 | Dec 2023
```

### Regression - Worked in .NET Core 3.1

```
01 Jan 2023 | Jan 2023
01 Feb 2023 | Feb 2023
01 Mar 2023 | Mar 2023
01 Apr 2023 | Apr 2023
01 May 2023 | May 2023
01 Jun 2023 | Jun 2023  <<<<<<
01 Jul 2023 | Jul 2023  <<<<<<
01 Aug 2023 | Aug 2023
01 Sep 2023 | Sep 2023  <<<<<<
01 Oct 2023 | Oct 2023
01 Nov 2023 | Nov 2023
01 Dec 2023 | Dec 2023
```

**Comment by stephentoub** [comment]
What OS are you using?  What's returned from `CultureInfo.CurrentCulture`?

I just tried your repro on .NET 6, .NET 7, and .NET 8, and for all three I get:
```
01 Jan 2023 | Jan 2023
01 Feb 2023 | Feb 2023
01 Mar 2023 | Mar 2023
01 Apr 2023 | Apr 2023
01 May 2023 | May 2023
01 Jun 2023 | Jun 2023
01 Jul 2023 | Jul 2023
01 Aug 2023 | Aug 2023
01 Sep 2023 | Sep 2023
01 Oct 2023 | Oct 2023
01 Nov 2023 | Nov 2023
01 Dec 2023 | Dec 2023
```

**Comment by EvgenyMuryshkin** [comment]
@stephentoub 
Windows 11 Pro, 22H2
en-AU

**Comment by EvgenyMuryshkin** [comment]
![image](https://github.com/dotnet/runtime/assets/11254187/cb5fcc61-930b-44c6-8a3b-b88b11fe2317)

**Comment by stephentoub** [comment]
Ah, got it.

So the difference based on the presence of the day is by design.  It comes from here:
https://github.com/dotnet/runtime/blob/7c00b17be1b2ffb6ed49ad68cf36e9a056323152/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L354-L366
When the day is present, it results in the code using the genitive month name.  And if you run this:
```C#
using System.Globalization;

CultureInfo.CurrentCulture = new CultureInfo("en-AU");

Console.WriteLine(string.Join(", ", CultureInfo.CurrentCulture.DateTimeFormat.AbbreviatedMonthGenitiveNames));
```
you'll see those values include "June", "July", and "Sept":
```
Jan, Feb, Mar, Apr, May, June, July, Aug, Sept, Oct, Nov, Dec,
```

As for why the difference between .NET Core 3.1 and .NET 5+, .NET 5 switched to getting its globalization data from ICU rather than from NLS.  If you switch back to using NLS by adding this to your csproj:
```xml
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
  </ItemGroup>
```
you'll see the results switch back:
```
Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec,
```

As to why the globalization data differs here, I don't know.  @tarekgh might.

**Comment by EvgenyMuryshkin** [comment]
@stephentoub thank. We found it while testing out web application and comparing with JS date format. 
This logic is not the case in JS world, so our test case failed on first run in June.

**Comment by Clockwork-Muse** [comment]
The `en-AU` culture was updated recently, we've had multiple questions about it: #86643 #87128.

As I mentioned in those other issues, "Why do you care what it looks like?".  You generally shouldn't be inspecting the output of formatting operations, including in test code.  If this is for API interchange, you shouldn't be using a localized format.

**Comment by EvgenyMuryshkin** [comment]
@Clockwork-Muse we care because we are testing data on web interface. JS output does not match C# output for 3 month, which is weird.
 
Suggested solution with RuntimeHostConfigurationOption works so should be fine.

**Comment by Clockwork-Muse** [comment]
> JS output does not match C# output for 3 month, which is weird.

It's not guaranteed to match in the first place.

> Suggested solution with RuntimeHostConfigurationOption works so should be fine.

This will only work on Windows (maybe - Windows updates the NLS data on occasion too), and will have no effect on Linux, including if you're delivering any ICU data from a server.  If you're getting culture data from the host the correct way, it's not guaranteed to match then, either, since formats might be customized by the user.

> we care because we are testing data on web interface.

If you're testing input formats for webforms and similar, what you **should** be doing is using a (potentially custom) static, unchanging culture (there's a variety of ways to do this), which would prevent this and potentially subtler issues.  At minimum you could use the `InvariantCulture`, but something more obviously different is probably a good idea (since it would also help test localization data); for instance, [pseudolocalization](https://learn.microsoft.com/en-us/globalization/methodology/pseudolocalization).

**Comment by EvgenyMuryshkin** [comment]
That's ok. It was working in 3.1 and now it is not. We will work around it.
Thanks.
