### ISSUE TITLE
GC Gen size counters don't show on Linux in native AOT

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#87325]
### Description

When running our native AOT benchmarks on Linux, we aren't seeing GC Gen 0/1/2 and LOH/POH Sizes show from `dotnet-coutners`:

![image](https://github.com/dotnet/runtime/assets/8291187/ad05bad2-2519-4f08-b8ac-42a48381e7a5)

But when running them on Windows, we do see all the numbers show up:

![image](https://github.com/dotnet/runtime/assets/8291187/f77826c7-0916-4d35-adc3-ab4067460868)

### Reproduction Steps

On linux, publish an app with `PublishAot=true`. Then run it and run `dotnet-counters monitor` on the process.

### Expected behavior

Should show values for `Gen 0 Size (B)`, Gen 1 Size (B), etc. 

### Actual behavior

All those values have 0.

### Other information

cc @LakshanF @agocke @mao

**Comment by elinor-fung** [comment]
Pretty sure this is because a bunch of the tracking for GC info is under `#ifdef FEATURE_EVENT_TRACE`:
https://github.com/dotnet/runtime/blob/fa4f15ef27796f7d1971ef6ab185da70a03a709e/src/coreclr/gc/gcee.cpp#L72-L80
And nativeaot only defines it on Windows:
https://github.com/dotnet/runtime/blob/fa4f15ef27796f7d1971ef6ab185da70a03a709e/src/coreclr/nativeaot/Runtime/CMakeLists.txt#L239-L241

**Comment by LakshanF** [comment]
I can see Gen 0/1/2 Size and POH Size values in a Linux build for a repro app after the fix went in.
