### ISSUE TITLE
Symbols are not correctly indexed for 6.0.16 Sytem.Collections.dll

### ISSUE THREAD

**Issue by chuckries** [dotnet/runtime#87334]
### Description

The System.Collections.pdb that is indexed on Microsoft Public Symbol Servers (https://msdl.microsoft.com/download/symbols) does not match the System.Collections.dll that is shipping with 6.0.16 shared runtime.

### Reproduction Steps

1. In Visual Studio, create a new C# console app for net6.0. (I have the 6.0.311 sdk installed with the 6.0.16 shared runtime)
2. In Tools > Options > Debugging > Symbols, ensure Microsoft Public Servers is enabled
3. Add the following code to the console app:
```cs
    SortedDictionary<string, string> sortedDict = new();
```
4. Set a breakpoint on the line and start debugging.
5. Open the modules window and Load Symbols from the context menu for System.Collections.dll

### Expected behavior

The PDB is downloaded from MSDL and is loaded by the debugger.

### Actual behavior

A PDB is downloaded, but the debugger refuses to load it because the signature does not match. An incorrect PDB has been indexed for the shipping version of the DLL.

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by hoyosjs** [comment]
There's not much we can do here. It's another manifestation of https://github.com/dotnet/runtime/issues/45649. The fix is in the linker in [`ComputeChecksumAndPdbId`](https://github.com/dotnet/cecil/blob/3e46711f5a933551557286d211970faa08b07b7e/Mono.Cecil.Cil/PortablePdb.cs#L456-L472). However, chatting with @vitek-karas confirmed that the 6.0 port of the fix is too risky. The indexing collides in between different architectures. Since this  is win-x64 which is fairly common compared to the other platform I've reindexed this.
