### ISSUE TITLE
Assertion failed '((regArgMaskLive & RBM_FLTARG_REGS) == 0) && "Homing of float argument registers with circular dependencies not implemented."'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#87515]
win/arm64

Pipeline: runtime-coreclr jitstress-isas-arm
coreclr windows arm64 Checked jitstress_isas_nohwintrinsic @ Windows.11.Arm64.Open
JIT.SIMD Work Item

https://dev.azure.com/dnceng-public/public/_build/results?buildId=302647&view=ms.vss-test-web.build-test-results-tab&runId=6137478&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=110096

```
set DOTNET_TieredCompilation=0
set DOTNET_EnableHWIntrinsic=0
```

```
21:11:48.632 Running test: JIT/SIMD/AbsGeneric_r/AbsGeneric_r.dll

Assert failure(PID 9288 [0x00002448], Thread: 9176 [0x23d8]): Assertion failed '((regArgMaskLive & RBM_FLTARG_REGS) == 0) && "Homing of float argument registers with circular dependencies not implemented."' in 'System.Numerics.Vector:Abs[short](System.Numerics.Vector`1[short]):System.Numerics.Vector`1[short]' during 'Generate code' (IL size 185; hash 0xff7e0044; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\codegencommon.cpp Line: 3400
    Image: C:\h\w\BF8C09A5\p\corerun.exe
```

Related? https://github.com/dotnet/runtime/issues/87511 https://github.com/dotnet/runtime/issues/87388

**Comment by BruceForstall** [comment]
@kunalspathak

**Comment by kunalspathak** [comment]
This seems to be related to https://github.com/dotnet/runtime/issues/87515 because I bisect the issue to https://github.com/dotnet/runtime/pull/85551

**Comment by kunalspathak** [comment]
@tannergooding

**Comment by kunalspathak** [comment]
> This leads to downstream issues when the support is disabled, which can negatively impact R2R or other scenarios.

What is the action item here? How do we want to tackle it?

**Comment by tannergooding** [comment]
We need to identify the places that are making assumptions and ensure they are updated to "do the right thing".

There's effectively two types of code we can encounter:
* Optimization
* ABI code

Code that exists just as an optimization should respect the `DOTNET_EnableHWIntrinsic=0` flag (and related baseline flags) and not light up if its off.

Code that exists for ABI purposes likely needs to ignore the `DOTNET_EnableHWIntrinsic=0` flag (and related baseline flags) and emit the correct codegen/handling regardless. This is because its part of the baseline support and so is required to work in order for HFA/HVA handling, among many other factors.

**Comment by kunalspathak** [comment]
Thanks @tannergooding.  I am assigning this to you for now.
