### ISSUE TITLE
System.Text.Json.JsonSerializer ,need complier error if target class have no pubic memeber

### ISSUE THREAD

**Issue by mrs01dev** [dotnet/runtime#87520]
utilizing System.Text.Json.JsonSerializer to serialize json string int class  
if the class have no public members ,serilization will give null with out any error.
c# compiler  should detect this issue , make an error.

**Comment by eiriktsarpalis** [comment]
Are you using the reflection serializer or the source generated one? If it's the former then there's nothing the compiler can do to reason about it since contract resolution happens at run time. If it's the latter, even though it technically is possible for the source generator to emit a diagnostic at compile time, I question whether that's a good idea because in some cases serializing to an empty JSON object might be desirable.
