### ISSUE TITLE
[API Proposal]: Additional ToFrozenDictionary overloads with optimizeForReading

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#87633]
### Background and motivation

When experimenting with using `FrozenDictionary` in https://github.com/dotnet/aspnetcore/issues/47569, we had to write
`entries.ToDictionary(x => x.text, x => x.destination).ToFrozenDictionary(StringComparer.OrdinalIgnoreCase, true);`
to get an optimized `FrozenDictionary` when ideally it would have been
`entries.ToFrozenDictionary(x => x.text, x => x.destination, StringComparer.OrdinalIgnoreCase, true);`

This matches the other overload of `ToFrozenDictionary` that takes an `IEnumerable<KeyValuePair<TKey, TValue>>`.

### API Proposal

```diff
public static partial class FrozenDictionary
{
    public static FrozenDictionary<TKey, TValue> ToFrozenDictionary<TKey, TValue>(this IEnumerable<KeyValuePair<TKey, TValue>> source, IEqualityComparer<TKey>? comparer = null) where TKey : notnull;
    public static FrozenDictionary<TKey, TValue> ToFrozenDictionary<TKey, TValue>(this IEnumerable<KeyValuePair<TKey, TValue>> source, IEqualityComparer<TKey>? comparer, bool optimizeForReading) where TKey : notnull;
    public static FrozenDictionary<TKey, TSource> ToFrozenDictionary<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer = null) where TKey : notnull;
+   public static FrozenDictionary<TKey, TSource> ToFrozenDictionary<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer, bool optimizeForReading) where TKey : notnull;
    public static FrozenDictionary<TKey, TElement> ToFrozenDictionary<TSource, TKey, TElement>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, IEqualityComparer<TKey>? comparer = null) where TKey : notnull;
+   public static FrozenDictionary<TKey, TElement> ToFrozenDictionary<TSource, TKey, TElement>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, IEqualityComparer<TKey>? comparer, bool optimizeForReading) where TKey : notnull;
}
```

### API Usage

```csharp
entries.ToFrozenDictionary(x => x.text, x => x.destination, StringComparer.OrdinalIgnoreCase, true);
```

### Risks

More API surface.

**Comment by stephentoub** [comment]
While I'm the one who pushed for us to add optimizeForReading, I'd still really like to see if we can do away with it before we actually ship.  It's there because a) the creation costs are so massive when compared to dictionary that anyone choosing to use the type for its surface area rather than many, many reads over the lifetime of the app will find themselves regressing perf, and b) for native aot carrying around all the different specializations for each TKey/TValue leads to asm bloat.  However, @adamsitnik is currently whittling down the costs; if we got them down sufficiently, it'd be nice to not force extra work on behalf of devs to achieve the primary reason these types were initially created.  That said, if we don't get there and we need to ship with the flag still in place, adding the additional overloads is reasonable.
