### ISSUE TITLE
all flags(ars) to optimize for native aot

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#87698]
i use this 
dotnet publish -c Release -p:PublishAot=true -p:InvariantGlobalization=true --p:UseSystemResourceKeys=true -p:EnableUnsafeUTF7Encoding=false -p:IlcOptimizationPreference=Size -p:IlcGenerateStackTraceData=false --p:EventSourceSupport=false -p:DebuggerSupport=false -p:EnableUnsafeBinaryFormatterSerialization=false -p:HttpActivityPropagationSupport=false -p:MetadataUpdaterSupport=false -p:DebugSymbols=false -p:DebugType=None -p:PublishTrimmed=true -p:TrimMode=true -p:DynamicCodeSupport=false -p:IlcDisableReflection=true -p:RootAllApplicationAssemblies=false -p:IlcGenerateCompleteTypeMetadata=false -p:IlcDisableUnhandledExceptionExperience=false -p:IlcFoldIdenticalMethodBodies=true

I wonder if there are any more flags to optimize it further, currently building native aot with the flags on is 1mb compared to 3mb without

**Comment by NCLnclNCL** [comment]
help

**Comment by MichalStrehovsky** [comment]
The supported ones are documented at https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/optimizing and https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#trimming-framework-library-features linked from there. The unsupported ones are documented at https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/optimizing.md.

I would suggest sticking to options that you see doing something. Most of the switches on the command line in your post don't do anything because either they already default to the value you specify, or they did something many years ago.
