### ISSUE TITLE
[API Proposal]: Recover JsonNode from string path

### ISSUE THREAD

**Issue by pedronihwl** [dotnet/runtime#87749]
### Background and motivation

**Hi,**

I think it's a good idea to add a method to obtain a JsonNode from an input string path. It should be similar to the 'SelectToken' method from Newtonsoft."

**Example:**
With Newtonsoft, we can access only the information we need by passing a string path with declared JSON labels and using a dot to indicate the depth.

```csharp
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

JObject obj = JObject.Parse(content);
string path = "child.nestedChild.nestedNestedChild";
JToken token = obj.SelectToken(path);
```

### API Proposal

```csharp
//This is the possible approach currently
JsonNode node = JsonNode.Parse(content);
JsonNode childNode = node["child"]["nestedChild"]["nestedNestedChild"];
```

### API Usage

```csharp
//This is a better aproach
JsonNode node = JsonNode.Parse(content);
string path = "child.nestedChild.nestedNestedChild";
JsonNode childNode = node.AsObject().NodeFromPath(path);
```

**Comment by davidfowl** [comment]
> I think it's a good idea to add a method to obtain a JsonNode from an input string path. It should be similar to the 'SelectToken' method from Newtonsoft."

Can you elaborate where you need this and what you are doing today? Yes I know JSON.NET has it but part of the background and motivation section should express the scenarios where this API will be used.

**Comment by gregsdennis** [comment]
I think what you're looking for us JSON Pointer.  I have an implementation [here](https://www.nuget.org/packages/JsonPointer.Net/).

The syntax slash-based instead of dot-based, but it's easy enough to translate between them.

Another option, though, [I'd argue that it's the wrong tool](https://blog.json-everything.net/posts/paths-and-pointers/), is JSON Path.  I have an [implementation](https://www.nuget.org/packages/JsonPath.Net) of that as well.  I believe this is what Newtonsoft's `SelectToken()` is based on.

**Comment by eiriktsarpalis** [comment]
> Can you elaborate where you need this and what you are doing today?

Second that, extracting nodes from a string path seems to require more work compared to nesting indexers. I also think it should be possible to express this as an extension method over the existing indexer implementations.
