### ISSUE TITLE
Possibly broken NuGet package for System.Data.Odbc 7.0

### ISSUE THREAD

**Issue by gordon-matt** [dotnet/runtime#88281]
I am using **.NET 7** and attempting to use the **System.Data.Odbc 7.0** package. However, I keep getting a `PlatformNotSupportedException`. When navigating to the implementation of `OdbcConnection` I see this:

![ODBC](https://github.com/dotnet/runtime/assets/2860937/7362993e-3b9b-487f-8a74-d7a2beb65238)

This is not what I see in your [source code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Data.Odbc/src/System/Data/Odbc/OdbcConnection.cs), so what's going on here? What am I missing?

**UPDATE**: I should mention I am on Windows 10 and I have Office 2016. I am attempting to connect to an Access Database (.accdb).

**Comment by jkotas** [comment]
> I am using .NET 7 and attempting to use the System.Data.Odbc 7.0 package

Could you please share a project that reproduces the problem?

System.Data.Odbc package has multiple OS-specific implementations. This error means that you are using the placeholder implementation for unknown OS instead of the implementation for Windows. 

The default dotnet build and assembly loader should take care of this detail for you and pick the implementation for Windows without doing anything special. This sort of problem is typically encountered when assemblies are loaded manually by file paths instead of depending on the default dotnet behavior.

**Comment by 0xced** [comment]
I recently had the exact same issue when _navigating to the implementation_, i.e. ctrl + click on `OdbcConnection` and let Rider/ReSharper decompile the assembly.

I think that the IDEs are not aware of the runtime loading rules. But indeed looking at `%USERPROFILE%\.nuget\packages\system.data.odbc\7.0.0\runtimes\win\lib\net7.0\System.Data.Odbc.dll` with JetBrains dotPeek produces the expected result.

**Comment by jkotas** [comment]
> I think that the IDEs are not aware of the runtime loading rules

If the problem is in the IDE or the IDE extension, it should be filled in their respective issue tracing systems.
