### ISSUE TITLE
Read files generated by obsolete BinaryFormatter

### ISSUE THREAD

**Issue by panxn** [dotnet/runtime#88316]
Perhaps it's not a good issue, I just need some suggestions.

According to [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), using `BinaryFormatter` is error in .NET8, and totally removed in .NET9.

Our product is preparing for it, we plan to replace `BinaryFormatter` with `Json/Xml`, but the difficulty is backward compatibility, how to read old file format in new product.

Is there anyway else (except `BinaryFormatter`) to read/parse files generated by `BinaryFormatter`? I guess `BinaryFormatter` saves type info and data members into files, so is it possible to dump all these information into json structure?

Currently I'm trying to create a Migrator.exe that stays in fixed old .NET version (maybe .NET framework) so that `BinaryFormatter` can keep alive for longer time, however the dependency assemblies are not available, so I create a `SerializationBinder` to return fake types. I have to say this way is too difficult. That's why I want to ask here to look for a better way.

**Comment by teo-tsirpanis** [comment]
Item 4 in #29976 seems to be what you need. @GrabYourPitchforks any news on the safe `BinaryFormatter` deserializer?

**Comment by JeremyKuhne** [comment]
@panxn in WinForms I created [`BinaryFormattedObject`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObject.cs) for manual parsing of existing data. You're welcome to copy it under the MIT license. It can also serialize as well. The only record type it doesn't handle is multidimensional/jagged arrays, didn't need to do that yet so I haven't written it. :)

**Comment by GrabYourPitchforks** [comment]
@teo-tsirpanis An officially supported package is indeed being discussed, but development of such a package hasn't been resourced. I don't really have any progress on it to share at this time.

If you wanted to take the WinForms code you're totally free to do so. However, it has not been threat modeled or security reviewed for any scenarios outside of WinForms-specific scenarios. You would need to perform your own analysis of it in the context of your own application.

**Comment by rickbrew** [comment]
This is also critical for Paint.NET -- it'd be nice to have, say, a nuget package that provides `BinaryFormatter` and all the serialization logic, but requires me to provide surrogate serializers for every type I need to handle (even if that means things like `string` and `T[]`, I'll do it!). For both serialization and deserialization. Otherwise I can't move forward to whatever version of .NET eventually removes `BinaryFormatter` (8? 9?), as all .PDN image files (the native multi-layered Paint.NET image format) would become instantly unusable.

**Comment by JeremyKuhne** [comment]
@rickbrew I'm curious whether or not the `BinaryFormattedObject` mentioned above has the functionality you require. It's effectively a DOM for the NRBF format.

**Comment by panxn** [comment]
Hi @JeremyKuhne thanks for your advice. We have considered copy .NET code, it should work, just hard to maintenance for us.
Our team has started the plan to convert BF format to JSON via a standalone .NET framework app so that BF keeps available as long as .NET framework is under support.

**Comment by rickbrew** [comment]
> @rickbrew I'm curious whether or not the `BinaryFormattedObject` mentioned above has the functionality you require. It's effectively a DOM for the NRBF format.

It might work, but I need deserialization _and_ serialization. Otherwise I will not be able to support both the old and new file format versions simultaneously, which could make things quite difficult for some end-users. For example: several people working on project(s), sharing and collaborating on files, but not all of them have the new version of my app. Person 1 saves some images in the new format, but then Person 2 can't load the images at all because they haven't installed the new app version. Maybe they can't because they're in an office and their IT department hasn't deployed the new version, and maybe won't for some time. If I can still use BinaryFormatter and support the old file format version, then Person 1 can at least File -> Save As -> and choose "Legacy .PDN Format" in the file type dropdown.

**Comment by tannergooding** [comment]
@GrabYourPitchforks does this need to stay open to track the areas being investigated you mentioned or can it be closed?

**Comment by GrabYourPitchforks** [comment]
@tannergooding this is already being tracked by internal work items. Feel free to keep this open or close it depending on your own needs. I personally don't need this item to remain open.

**Comment by jkotas** [comment]
API proposal: #102014
