### ISSUE TITLE
TryParseExact not working properly for TimeSpan and custom format not working for "\" in DateTime and DateTimeOffset

### ISSUE THREAD

**Issue by mohanrajsf3477** [dotnet/runtime#88372]
### Description

I have already created issue #88119. However, I am still facing the issue. Even though I did not confirm the resolution on my end, the issue was closed. I added a comment, but the issue was not reopened.

please check and provide proper solution 

### Reproduction Steps

reffer : #88119 

### Expected behavior

1.TryParseExact method need to work properly for TimeSpan 
2. TryParseExact method need to work properly for custom format for datetime and datetimeoffset

### Actual behavior

1.TryParseExact method not work properly for TimeSpan 
2.TryParseExact method not work properly for custom format for datetime and datetimeoffset

**Comment by mohanrajsf3477** [comment]
Hi @KeterSCP ,
 
Oh, we need to use only the TryParseExact method. I tried the provided solution on the declared time value too, so it did not work. 
After reviewing the sample, you provided, I understand the solution that was provided. 
Thank you.

**Comment by Clockwork-Muse** [comment]
@mohanrajsf3477 - The reason nobody responded is that you posted in the middle of the night, PST (where Microsoft main campus is located, although not all teams/members are there), on the day before a major US holiday (and since the holiday falls on a Tuesday this year, many people would have taken Monday off as well).

Even without the above, you should expect to wait more than an hour for a response, and generally for things like this you would want to force-notify members of the conversation first (and that after a couple of days/a week), rather than opening a new issue.
