### ISSUE TITLE
System.IO.MemoryStream: ReadByte() and WriteByte() can throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by elgonzo** [dotnet/runtime#88541]
_(Edit: I updated the issue report, as not only ReadByte() is affected but WriteByte() as well)._

### Description

When creating a non-resizable MemoryStream from an array region whose start/origin index is larger than zero, the _MemoryStream.Position_ value can be set in a way that leads to IndexOutOfRangeException when calling _MemoryStream.ReadByte()_ or _MemoryStream.WriteByte()_ . 

This is due to the assignment of the private _\_position_ field in the _MemoryStream.Position_ set accessor:
https://github.com/dotnet/runtime/blob/57608c3728279917a401a97ef80fa533c86b062f/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs#L315
which can lead to _\_position_ becoming negative.

Both the _ReadByte()_ and _WriteByte()_ method, however, do not test for _\_position_ being negative before using it as an index into the _\_buffer_ byte array, thus being vulnerable to causing IndexOutOfRangeException.

ReadByte():
https://github.com/dotnet/runtime/blob/57608c3728279917a401a97ef80fa533c86b062f/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs#L430-L433

WriteByte():
https://github.com/dotnet/runtime/blob/57608c3728279917a401a97ef80fa533c86b062f/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs#L736-L754

### Reproduction Steps

```C#
byte[] buffer = new byte[100];
using var ms = new System.IO.MemoryStream(buffer, 10, buffer.Length - 10, true);

//
// Let the private MemoryStream._position field overflow
//
var newPosition = int.MaxValue - 9;
ms.Position = newPosition;
System.Console.WriteLine("ms.Position == newPosition: " + (ms.Position == newPosition));

System.Console.WriteLine();
System.Console.WriteLine("ReadByte");
try
{
	var b = ms.ReadByte();
	System.Console.WriteLine("ms.ReadByte() returned " + b);
}
catch (System.Exception ex)
{
	System.Console.WriteLine(ex);
}

System.Console.WriteLine();
System.Console.WriteLine("WriteByte");
try
{
	ms.WriteByte(0);
}
catch (System.Exception ex)
{
	System.Console.WriteLine(ex);
}
```

### Expected behavior

Expected result/output:
```
ms.Position == newPosition: True

ReadByte
ms.ReadByte() returned -1

WriteByte
System.NotSupportedException: Memory stream is not expandable.
   ...
```

### Actual behavior

Actual result/output:

```
ms.Position == newPosition: True

ReadByte
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.IO.MemoryStream.ReadByte()
   ...

WriteByte
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.IO.MemoryStream.WriteByte(Byte value)
   ...
```

### Configuration

.NET 8 Preview 3 (https://dotnetfiddle.net/V1POV0)
.NET Framework 4.7.2 (https://dotnetfiddle.net/gM2LkH)

Considering that the bug is already present and reproducible in the old .NET Framework 4.7.2, it's reasonable to assume that at least any .NET version following Framework 4.7.2 is also affected by this issue.

**Comment by manandre** [comment]
Thanks for reporting this issue.
The issue here starts you try to set the `Position` property with an invalid value, an error already exists for this situation:
```
ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
```
used in https://github.com/dotnet/runtime/blob/31106939ba524a7e6df8225cf8d0fedefba92b9f/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs#L313-L314
But this code does not take into account the `_origin` field!
This must be fixed.
It seems that the `Seek` method is also impacted with the same type of issue.

**Comment by elgonzo** [comment]
> The issue here starts you try to set the `Position` property with an invalid value, an error already exists for this situation:
> 
> ```
> ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
> ```
> 

Your argument is in conflict with the documentation for _MemoryStream.Position_, which states (https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream.position?view=net-8.0#exceptions):

> Exceptions
>[ArgumentOutOfRangeException](https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception?view=net-7.0)
>
>The position is set to a negative value or a value greater than [Int32.MaxValue](https://learn.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=net-7.0#system-int32-maxvalue).

I am in no position to tell whether your argument is mistaken or the documentation is incorrect. But if the team decides that the _MemoryStream.Position_ property should throw for positive values **less than or equal to**  _int.MaxValue_, then the _MemoryStream.Position_ documentation needs to be updated to correctly reflect the changed behavior.

**Comment by manandre** [comment]
I agree that the situation is quite confusing here.
- The documentation states that the `ArgumentOutOfRangeException` must only be raised when the position value is greater than `int.MaxValue`
- In such a situation, the `MemoryStream.Position` property currently raises the `ArgumentOutOfRangeException` with the following message:
```
Stream length must be non-negative and less than 2^31 - 1 - origin.
````

The limit of `MemoryStream.Position` to `Int32.MaxValue`, while it returns an `Int64` (long) type, is only related to the underlying array limitation, what then must take into account the origin : `index = _origin + Position < Int32.MaxValue`.
From my point of view, the documentation of the `ArgumentOutOfRangeException` for `Position` (and `Seek`) methods should be aligned on the [SetLength](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream.setlength?view=net-8.0#exceptions) one (or just removed to strictly follow the `Stream` contract).

@stephentoub Can you please help here to define the expected behavior in this _overflow_ case?

**Comment by Jozkee** [comment]
https://github.com/dotnet/dotnet-api-docs/issues/9201
