### ISSUE TITLE
NativeAOT builds aren't updated when rebuilding with different MSBuild options

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#88725]
### Description

> **Note**: this issue is a follow up from a conversation with @MichalStrehovsky, @tannergooding, @SingleAccretion and others on the C# Discord. I'm aware the culprit here is likely just MSBuild, but opening this just for tracking 🙂

While working on https://github.com/Sergio0694/ComputeSharp/pull/542, I noticed that rebuilding my CLI sample with NAOT using different MSBuild options was just... Not doing anything. And the resulting binary was exactly the same. I have configured a bunch of MSBuild options to build my sample with or without some more size saving options, and my assumptions was that rebuilding after setting up those new environment variables would do "the right thing", but it seems it doesn't 😅

### Reproduction Steps

- Clone https://github.com/Sergio0694/ComputeSharp
- Run these commands:
```powershell
$env:COMPUTESHARP_SWAPCHAIN_CLI_PUBLISH_AOT='true';
dotnet publish samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj -c Release -f net7.0 -r win-x64
```
- Verify the resulting binary is ~2.3 MB, and has an icon
- Run these commands:
```powershell
$env:COMPUTESHARP_SWAPCHAIN_CLI_PUBLISH_AOT='true';
$env:COMPUTESHARP_SWAPCHAIN_CLI_SIZE_OPTIMIZED='true';
$env:COMPUTESHARP_SWAPCHAIN_CLI_DISABLE_REFLECTION='true';
dotnet publish samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj -c Release -f net7.0 -r win-x64
```
- Verify the binary is exactly the same (but it should be ~1.1 MB, and with no icon instead)

### Expected behavior

The build should be retriggered with the right properties. The resulting binary should be the same you would get if you tried building with the same exact commands but from a freshly cloned repo instead, not affected by previous builds.

### Actual behavior

The resulting binary doesn't change.

### Known Workarounds

You can run `git clean -fdx` before the second build. That works, but isn't ideal.

**Comment by tannergooding** [comment]
There are multiple options available for helping ensure that property inputs impact the rerunability of targets.

What a lot of the SDK does is similar to the following handling for `GenerateAssemblyInfo`: https://github.com/dotnet/sdk/blob/ce54eaa3bd5a380985825a8c789a5f7d31301884/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets

You can see that there is the main target `GenerateAssemblyInfo` which has the high level condition and is otherwise empty. It simply inserts itself into the right "BeforeTargets" and adds the relevant `DependsOnTargets`, one of which is `CoreGenerateAssemblyInfo`.

That target itself has the inputs/outputs where one of the inputs is `GeneratedAssemblyInfoInputsCacheFile` which is created by the `CreateGeneratedAssemblyInfoInputsCacheFile` target.

The `CreateGeneratedAssemblyInfoInputsCacheFile` target is going to effectively "always" run and it does the minimal steps of basically hashing all the input properties into a file, but with `WriteOnlyWhenDifferent=true` so the timestamp doesn't change when inputs don't change.

There are of course other options as well, but having the input properties somehow written to a file that is an "input" to the main target is the basic principle behind which it typically operates.
