### ISSUE TITLE
Debugger display of dictionary types and `DebuggerDisplayAttribute.Name`

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#88736]
[DebuggerDisplayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute.-ctor?view=net-7.0) has `Name` and `Type` properties. We never use these.

A place `Name` is useful is collection items. It can be used to display a custom name instead of an index in a debugger window.

Before:

![image](https://github.com/dotnet/runtime/assets/303201/7efb3a7e-df89-4f66-a7e4-cf75b003703f)

After:

![image](https://github.com/dotnet/runtime/assets/303201/3686f8c8-3f77-4d45-94c2-eef469260dcb)

This seems like an improvement to me. It's easier to see what the keys and values are.

I was wondering why [IDictionaryDebugView](https://github.com/dotnet/runtime/blob/1b2664df569cbe103811377b1a98e744f1afe159/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/IDictionaryDebugView.cs) and other dictionary type proxies don't use this feature. Right now the key and value are squashed together in the debugger, and a meaningless index is displayed as the name.

**Comment by JamesNK** [comment]
@jaredpar Curious if you have any insight here or historical context.

**Comment by jaredpar** [comment]
Don't really have any historical context on this specific decision.

I will say that in general the rules of `DebuggerDisplay` and the power when combined with `DebuggerTypeProxy` and `DebuggerBrowsable` wasn't fully appreciated by everyone when it first came out. That combined with various bugs in the EE, perf issues evaluating so many new expressions, and actual bugs how developers structured meant they weren't as utilized as they could have been. It wasn't until probably VS 2010 until I think the entire system was in a fully formed state. 

It's quite possible the original author didn't realize these type of tricks were possible, or tried and gave up due to the mentioned issues and no one has revisited it since then.
