### ISSUE TITLE
Proposal: expose <IlcFoldIdenticalMethodBodies> as a supported option

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#88748]
> **Note**: related to #88235 regarding making more NativeAOT options publicly documented.

NativeAOT currently exposes the `<IlcFoldIdenticalMethodBodies>`, which produces some nice binary size wins at the cost of worse stack traces. Of course, being an ilc-prefixed property, this is not actually supported. Would it make sense to either:
- Expose this as a supported option (eg. `<FoldIdenticalMethodBodies>`)
- Consider adding some other property to aggregate "destructive" size optimizations options (folding being one?)

Leaving `<IlcDisableReflection>`, method body folding is effectively the last remaining unsupported size saving option 😄

**EDIT:** @SingleAccretion just pointed out this would actually also break delegate equality (and hence events too), so I suppose maybe we can't really make this a publicly supported feature after all as it could cause too many random breaks? 🥲

**Comment by MichalStrehovsky** [comment]
> EDIT: @SingleAccretion just pointed out this would actually also break delegate equality (and hence events too), so I suppose maybe we can't really make this a publicly supported feature after all as it could cause too many random breaks?

Yes, this requires extra work. Native linkers (both LLVM and MSVC) can optionally do the right thing for these, but the protocol for MSVC is specific to .NET Native and I don't know if we could take a dependency).

**Comment by MichalStrehovsky** [comment]
> Consider adding some other property to aggregate "destructive" size optimizations options (folding being one?)

The more things get added to such aggregate, the less useful it becomes because it will become more likely _one_ of those things will break your app and then you have to reverse engineer the switch to find the problematic switch one-by-one. Enabling all destructive switches (including future ones) will likely only work for a hello world long term.

**Comment by jkoritzinsky** [comment]
> Yes, this requires extra work. Native linkers (both LLVM and MSVC) can optionally do the right thing for these, but the protocol for MSVC is specific to .NET Native and I don't know if we could take a dependency).

I didn't know that MSVC had a solution here. It would be a way to solve the comdat folding problem that violates the as-if rule for equality (or inequality) of function pointer addresses (which CoreCLR has to work around).

**Comment by MichalStrehovsky** [comment]
> > Yes, this requires extra work. Native linkers (both LLVM and MSVC) can optionally do the right thing for these, but the protocol for MSVC is specific to .NET Native and I don't know if we could take a dependency).
> 
> I didn't know that MSVC had a solution here. It would be a way to solve the comdat folding problem that violates the as-if rule for equality (or inequality) of function pointer addresses (which CoreCLR has to work around).

I remember when this got added to link.exe there was a discussion about also using it VC++ to make `/opt:icf` standard-conformant but I don't know where that want. If I remember correctly, it required generating a section with a well-known name into the executable that lists all symbols that require a unique address and an extra flag to link.exe (a value of `opt` that doesn't look documented). I don't know if cl can be coerced to generate it but since the link.exe flag is not documented it probably didn't go through.

**Comment by jkoritzinsky** [comment]
Looks like the most recent open discussion on this was from you a few years ago: https://github.com/dotnet/runtime/issues/49640#issuecomment-799712730

I'll see if I can get some traction on this.

**Comment by tannergooding** [comment]
One consideration could be to name it (or other similar options) `*Unsafe` (i.e. `FoldIdenticalMethodBodiesUnsafe`), so that its clear that it may have undesired side effects for some apps

**Comment by jkotas** [comment]
> *Unsafe (i.e. FoldIdenticalMethodBodiesUnsafe), so that its clear that it may have undesired side effects for some apps

Supported unsafe options need to have a documentation for how to use them safely. With the current behavior of `IlcFoldIdenticalMethodBodies`, the documentation would have to say that you can only use it safely if nothing in your app and libraries depends on delegate equality. There is no reasonable way to audit for that.

**Comment by Sergio0694** [comment]
Sharing here for context too, this is now also tracked here:
- https://developercommunity.visualstudio.com/t/Provide-a-documented-mechanism-to-specif/10562439
- https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1941080 (internal only)

**Comment by MichalStrehovsky** [comment]
This is now folded when we generate the object file. There's limited benefit in doing the COMDAT folding in the linker due to:

* It would be Windows specific.
* We currently don't have any supported modes to compile managed code into multiple obj files so it cannot provide any benefit beyond what the compiler is already doing.

Closing.
