### ISSUE TITLE
`.\build.cmd -subset clr+libs -config release` fails in `ConfigurationBindingGenerator`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#88918]
As per the title, currently running `.\build.cmd -subset clr+libs -config release` currently fails with the following:
```
CSC : error CS8785: Generator 'ConfigurationBindingGenerator' failed to generate source. It will not contribute to the
output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message '
repeatCount ('-4') must be a non-negative value. (Parameter 'repeatCount') [D:\Users\tagoo\source\repos\runtime\src\lib
raries\Microsoft.Extensions.Logging.Configuration\src\Microsoft.Extensions.Logging.Configuration.csproj::TargetFramewor
k=net8.0]
D:\Users\tagoo\source\repos\runtime\src\libraries\Microsoft.Extensions.Logging.Configuration\src\LoggerFilterConfigureO
ptions.cs(54,72): error IL2026: Using member 'Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue<T>(IConfi
guration, String, T)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application c
ode. In case the type is non-primitive, the trimmer cannot statically analyze the object's type so its members may be t
rimmed. [D:\Users\tagoo\source\repos\runtime\src\libraries\Microsoft.Extensions.Logging.Configuration\src\Microsoft.Ext
ensions.Logging.Configuration.csproj::TargetFramework=net8.0
```

**Comment by layomia** [comment]
Can you check again with the latest bits? Doesn't repro for me with latest main https://github.com/dotnet/runtime/commit/e264ba7fa83312a35f2d31eb1a41cf8e7a47bfbd. What commit were you folks on when you saw this?

**Comment by jasper-d** [comment]
Does repro for me with 218d2ef and `git clean -ffdx && dotnet nuget locals all --clear && .\build.cmd -s clr+libs -c Release`. Will try with e264ba7fa83312a35f2d31eb1a41cf8e7a47bfbd next.

**Comment by jasper-d** [comment]
Still able to reproduce with e264ba7fa83. This is what I ran:
```powershell
git checkout e264ba7
get-process dotnet | stop-process
dotnet build-server shutdown
git clean -ffdx
dotnet nuget locals all --clear
.\build.cmd -s clr+libs -c Release
```

**Comment by vcsjones** [comment]
I've hit a couple of errors trying to build with the preview 6 SDK installed.

Do y'all have .NET 8 preview 6 installed? Does it build if you do `export useInstalledDotNetCli=0` then try a build?

**Comment by lateralusX** [comment]
I get this on debug builds as well, but in that scenario it will trigger an assert instead of a crash.

C:\Users\xxxx\.nuget\packages\microsoft.net.compilers.toolset\4.7.0-2.23319.4\tasks\netcore\Microsoft.CSharp.Core.t
argets(80,5): error : Process terminated. Assertion failed. [C:\git\runtime\src\libraries\Microsoft.Extensions.Logging.
Configuration\src\Microsoft.Extensions.Logging.Configuration.csproj::TargetFramework=net8.0]
C:\Users\xxxx\.nuget\packages\microsoft.net.compilers.toolset\4.7.0-2.23319.4\tasks\netcore\Microsoft.CSharp.Core.t
argets(80,5): error :    at Microsoft.Extensions.Configuration.Binder.SourceGeneration.SourceWriter.WriteBlockEnd(Strin
g extra) in C:\git\runtime\src\libraries\Microsoft.Extensions.Configuration.Binder\gen\Helpers\SourceWriter.cs:line 30
[C:\git\runtime\src\libraries\Microsoft.Extensions.Logging.Configuration\src\Microsoft.Extensions.Logging.Configuration
.csproj::TargetFramework=net8.0]

**Comment by ericstj** [comment]
I was able to get symbols and updated the above.  Here's the parameter to `WriteBlock(string source)`
```
"    global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(services);\r\n    global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Microsoft.Extensions.Options.IOptionsChangeTokenSource<TOptions>>(services, new global::Microsoft.Extensions.Options.ConfigurationChangeTokenSource<TOptions>(name, configuration));\r\n    return global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Microsoft.Extensions.Options.IConfigureOptions<TOptions>>(services, new global::Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>(name, obj => global::Microsoft.Extensions.Configuration.Binder.SourceGeneration.CoreBindingHelper.BindCoreUntyped(configuration, obj, typeof(TOptions), configureOptions)));\r\n}"
```

**Comment by layomia** [comment]
Thanks! I'll move this convo to https://github.com/dotnet/runtime/issues/89014 since that deals with MacOs/Linux specifically. Taking a look.

**Comment by ericstj** [comment]
It looks to me like the the multi-line string literal embedded into the binary has new-line constants that depend upon whatever the git client settings are on the machine building the generator:
https://github.com/dotnet/runtime/blob/90b85ea16c97c16545cd2b22a5ae9ee05a16d7c7/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/Helpers/Emitter/OptionsConfigurationServiceCollectionExtensions.cs#L57-L59

So if I disassemble the one on the mac it has `\r\n` because we're shipping one copy of the source generator assembly for all platforms, built from windows.  Looks to me like having a mismatch in line endings is causing this line ending logic to fail, https://github.com/dotnet/runtime/blob/90b85ea16c97c16545cd2b22a5ae9ee05a16d7c7/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/Helpers/SourceWriter.cs#L47.

@tannergooding observed a break here because his local git client on windows was configured for source line-endings (eg: LF), which differed from Environment.NewLine:
https://github.com/dotnet/runtime/blob/90b85ea16c97c16545cd2b22a5ae9ee05a16d7c7/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/Helpers/SourceWriter.cs#L14

@martincostello observed a break because his mac/unix build client's had a different line ending in the generator (built on windows) than his environment.

**Comment by eiriktsarpalis** [comment]
@jasper-d thanks for the offer, but I believe a fix is already in the works :-)
