### ISSUE TITLE
AesGcm documentation needs some adjustments

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#88933]
User @ProIntegritate wrote in [this dotnet-api-docs PR](https://github.com/dotnet/dotnet-api-docs/pull/9140):

> Not sure if this comment is in the right place, but i don't know how to message someone on github or comment the page as there is no "provide feedback" option on it. I'm guessing it belongs here:
> 
> Just a note on this page:
> https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-8.0
> 
> The function AesGcm now requiring a Byte array with Keybytes AND a Tag size in bytes - this is not applicable for .NET 6 and earlier as they only need a Byte array with Keybytes to be created.
> 
> The Tag + Nounce can be provided as parameters to the .Encrypt() and .Decrypt() methods. The requirement to add an Int32 with the size of the nounce is something new that i observed in .NET 8 () - so the documentation needs an update. ( i haven't tested it in .NET 7 because it's not LTS and i don't care about non-LTS releases)
> 
> I really wonder why this change was necessary at all as it breaks some cryptographic code. The size of the Nounce is always automatically provided by passing a byte array to the methods.

cc @dotnet/area-system-security @vcsjones @GrabYourPitchforks

**Comment by carlossanlop** [comment]
@gewarren was lightning fast to address it: https://github.com/dotnet/dotnet-api-docs/pull/9140#issuecomment-1636445894

If that's all that's needed to address the reported issue, then please feel free to close this issue.

**Comment by vcsjones** [comment]
As noted, this is an intention change as outlined in https://github.com/dotnet/runtime/pull/86211 and https://github.com/dotnet/runtime/issues/71366. The pull request @gewarren made over at https://github.com/dotnet/docs/pull/36265/ seems like a good justification of the obsoletion.

> The size of the Nounce 

Just to be clear, it's the tag, not the nonce, that requires matching the constructor. There should be no behavior changes around the nonce.

> is always automatically provided by passing a byte array to the methods.

The automatic length was the behavior we are addressing here. It's meant to make consumers of AesGcm explicitly determine what their intended tag size is. "Did you REALLY mean to give a 12 byte tag instead of a 16 byte tag?"

**Comment by ProIntegritate** [comment]
Developers should keep track of whatever parameters they input into their functions, if they input a 12 byte (96) bit instead of a 16 byte (128 bit) and break something - that is on them.

I write wrappers for pretty much all cryptography in .NET to make things easier and also Bouncycastle (which is consistent in their API), and changes like this makes it impossible to maintain those. Before you make such changes in the future and especially in cryptography, please consider the effects before you make final decision.

**Comment by vcsjones** [comment]
The new constructors are documented now that we've applied .NET 8 documentation. The obsoletion warning links to a page describing why the change was made, and, how to migrate to the new constructors.

https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0053

I don't think there are any additional documentation changes needed here, so I am going to close this issue.

If it is believed that we need to further improve the documentation or I misunderstood the state of the issue, please feel free to re-open.
