### ISSUE TITLE
Configuration binding source generator fails with CS8598 error

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#89010]
### Description

Attempting to enable the Configuration binding source generator with a struct used as a custom configuration type causes the source generator to emit code that fails to compile with a CS8598 error.

```
Repro\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\GeneratedConfigurationBinder.g.cs(122,17): error CS8598: The suppression operator is not allowed in this context [Repro\Repro.csproj]
```

The method generated is below. The failing line is `element! = temp4;`.

```csharp
public static void BindCore(IConfiguration configuration, ref IDictionary<string, Geolocation> obj, BinderOptions? binderOptions)
{
    if (obj is null)
    {
        throw new ArgumentNullException(nameof(obj));
    }

    foreach (IConfigurationSection section in configuration.GetChildren())
    {
        if (!(obj.TryGetValue(section.Key!, out Geolocation element)))
        {
            element = InitializeGeolocation(section, binderOptions);;
        }
        var temp4 = InitializeGeolocation(configuration, binderOptions);;
        BindCore(section, ref temp4, binderOptions);
        element! = temp4; // CS8598 occurs here
        obj[section.Key!] = element;
    }
}
```

### Reproduction Steps

1. Clone [martincostello/config-binding-source-generator-cs8598-repro](https://github.com/martincostello/config-binding-source-generator-cs8598-repro)
1. Run `dotnet build`

### Expected behavior

The application compiles and configuration binding works equivalently to runtime binding.

### Actual behavior

The application fails to compile with a CS8598 error.

### Regression?

No.

### Known Workarounds

None.

### Configuration

.NET SDK 8.0.100-preview.6.23330.14

**Comment by layomia** [comment]
Side note: I notice that you're using a `TypeConverter` for the `Geolocation` type in question. The generator doesn't probe for or generate code to support `TypeConverter` usage. This is to facilitate AOT / trim compat, given that's the primary goal for the feature. We have an issue tracking a new extensibility feature that we can consider post .NET 8 - https://github.com/dotnet/runtime/issues/83599.

After this bug is fixed, could you try the generator again to see if the binding behavior matches your expectations?

**Comment by martincostello** [comment]
Sure. The repro is adapted from a private repo that has a suite of tests. Once it uses a version of the SDK that should compile, it should be trivial to see if the binding behaviour works correctly.

**Comment by layomia** [comment]
Looking at the core parsing logic, it looks like the generator would not handle your inputs as expected - https://github.com/martincostello/config-binding-source-generator-cs8598-repro/blob/57998e5dcd44f6ec59429240bcc63839f6d1a70e/Repro/Geolocation.cs#L69.

So IIUC the input `IConfiguration` shape would be something like `{ Geolocation: "3, 4" }` rather than `{ Geolocation: { Latitude: 3, Longitude: 4 } }`. I believe the generator would only support the latter.
