### ISSUE TITLE
Assembly.LoadFrom throws exception when loading System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by mjkkirschner** [dotnet/runtime#89215]
### Description

We are migrating a large .Net4.8 project to .Net6 - we have some code in our project that falls back to loading assemblies using `Type.Assembly.Location` - in .net6 `System.Decimal`'s Location now points to `"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\6.0.18\\System.Private.CoreLib.dll"`

When `Assembly.LoadFrom` is called on this path and `System.Private.CoreLib.dll` is already loaded - `System.IO.FileNotFoundException: ‘Unable to load the specified file` is thrown.

The docs for `Assembly.LoadFrom` state: 
`If an assembly with the same identity is already loaded, LoadFrom returns the loaded assembly even if a different path was specified.` 

Is something special happening for this assembly, for this path, is this a bug?

### Reproduction Steps

Call Assembly.LoadFrom on `"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\6.0.18\\System.Private.CoreLib.dll"`

### Expected behavior

I expect the returned assembly to be the already loaded version of `System.Private`CoreLib`

### Actual behavior

An exception is thrown.

### Regression?

Not applicable, we never tried to load this assembly in .net 4.8.

### Known Workarounds

We use `Assembly.Load` if the assembly name contains `System.Private` - and this works, no exception is thrown.

### Configuration

* .net6
* windows 11
* x64
* unknown
* NA

**Comment by teo-tsirpanis** [comment]
Tagging subscribers to this area: @vitek-karas, @agocke, @VSadov
See info in [area-owners.md](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) if you want to be subscribed.

**Comment by vitek-karas** [comment]
`System.Private.CoreLib` is special in that it's part of the core runtime. The loader will block any attempts to load it via any of the load APIs (it's always already loaded). Note that `Assembly.Load` is not technically loading the assembly, it's resolving the assembly name, so that will work even for CoreLib. But any API which takes a path or stream will not allow loading CoreLib, no matter where it came from.

I'm curious: If you have `type.Assembly`, why do you need to load that assembly again, it should basically always return the same assembly without loading anything (except for CoreLib which has this special block).

/cc @elinor-fung

**Comment by mjkkirschner** [comment]
Hi @vitek-karas - can you confirm if the other `System.Private.xyz` binaries are also special and will be blocked by the loader?

And of course you are correct about not needing to load the library again, it's just an attempt on our part to unify a code path, we're not sure what type the user will attempt to load or where it is located.

**Comment by vitek-karas** [comment]
Only `System.Private.CoreLib` is special. That said we absolute don't recommend custom loading basically any assembly which part of the framework. It should fail if you provide the wrong version, but if you somehow manage to make it work it's likely going to break things later on.

**Comment by mjkkirschner** [comment]
Thanks for your response @vitek-karas - and that leads me to another question - is there anyway to identify an assembly as part of the framework besides where it is located on disk?

**Comment by vitek-karas** [comment]
> is there anyway to identify an assembly as part of the framework besides where it is located on disk?

Not really - it's also a bit fuzzy. In general, this is something the SDK knows how to answer, the runtime has no clue. That's why loading assemblies "at random" at runtime will be problematic. Assuming you don't want to involve isolation provided by `AssemblyLoadContext` I would probably prefer `Assembly.Load` first and only if that doesn't work fallback to loading from path (but if you already have a type loaded from that assembly, then `Assembly.Load` should basically never fail).

Note that the answer to the questions becomes really fuzzy in a self-contained applications for example, and then there are assemblies which are both in some framework but also exist as standalone NuGet packages, so it's hard to answer this correctly. In general I would code the loading code such, that if the app already has the assembly loaded then use that - if you're loading everything into the default load context.

**Comment by mjkkirschner** [comment]
thanks for your time @vitek-karas - I will close this issue.
