### ISSUE TITLE
logging JsonConsole default option

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#89306]
Hi there, could we configure the default json writer options of  `JsonConsole` to use the `JavaScriptEncoder.UnsafeRelaxedJsonEscaping`, would it has any security risk?

For now, we had to configure it for all the apps to ensure the logs log as expected

``` c#
builder.Services.AddLogging(x => x.AddJsonConsole(options =>
{
    options.JsonWriterOptions = new JsonWriterOptions()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };
}));
```

otherwise, some logs may look wired:

![](https://github.com/dotnet/runtime/assets/7604648/7d062f94-e733-4ec7-951b-78cc9ef63c59)

Think it would be safe since the logs would be logged to the console only?

**Comment by eiriktsarpalis** [comment]
The `JavascriptEncoder` settings is not applicable to the `Utf8JsonWriter`/`JsonWriterOptions` layer, but only on the `JsonSerializer`/`JsonSerializerOptions` layer. Assuming the Json console logger lets you specify `JsonSerializerOptions` somewhere, you should use that configuration point to specify a custom `JavascriptEncoder` instance.

**Comment by WeihanLi** [comment]
@eiriktsarpalis thanks very much for the quick response, yeah, I mean for json console options, configure the `JsonConsoleFormatterOptions.JsonWriterOptions.Encoder` only

**Comment by layomia** [comment]
The JSON console logger doesn't use `JsonSerializer[/Options]`, it writes using the writer [directly](https://source.dot.net/#Microsoft.Extensions.Logging.Console/JsonConsoleFormatter.cs,28).

@WeihanLi  seems you're already configuring the encoder to get the behavior you want. We wouldn't be able to change the default setting here because that would be a breaking change. It also doesn't seem worth it to add a new default API to enable this specific scenario. Perhaps you could implement an abstraction to avoid the duplication

**Comment by WeihanLi** [comment]
@layomia thanks, think if we're sure it's safe to use the `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` for `JsonConsoleFormatterOptions.JsonWriterOptions.Encoder`, maybe we could make it as a default behavior without adding a new API, and seemed mostly it would not have compatibility issues, and since .NET 8 is a breaking change, maybe we could consider it or leave it in future major release if feature freeze for .NET 8?

**Comment by eiriktsarpalis** [comment]
I think I misunderstood your original request, apologies for the confusion. 

The proposal is to change the default JsonConsole encoder to `UnsafeRelaxedJsonEscaping`, since the fact that it's only outputting to stdout implies that it will never be parsed by a machine, correct? 

I don't believe that's a valid assumption, since console output can always be redirected to files or ingested by log aggregators. I think it's fair to assume that if a user opts for Json logging in the console, the expectation is that this json _could_ be parsed by machine in the future.

Regardless of the above, this would be a potential breaking change, it would deviate from the default STJ semantics elsewhere and the API already provides a good workaround for changing the encoding semantics if necessary.

cc @GrabYourPitchforks

**Comment by WeihanLi** [comment]
> I don't believe that's a valid assumption, since console output can always be redirected to files or ingested by log aggregators. I think it's fair to assume that if a user opts for Json logging in the console, the expectation is that this json could be parsed by machine in the future.

Yeah, totally agree with that, we mostly use the JSON console logging for easier log parsing and analysis, while from what we use, elastic/OpenSearch kibana, grafana loki, we do not see there's an issue from them when using the `UnsafeRelaxedJsonEscaping`.

And from the document, it's unsafe because `this encoder instance does not escape HTML-sensitive characters`, they're well handled by kibana/loki etc logging ui system, if we're trying to show the log directly we would do html encode before showing since the log may from another system which log is not html-safe.

So I think maybe it's not so necessary to keep our out html-safe, it would be a convenient way for this

**Comment by eiriktsarpalis** [comment]
Closing as not planned.
