### ISSUE TITLE
ILC doesn't return an error -- docker build keeps on running

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#89332]
I'm experimenting with native aot. I am doing that poorly such that my configuration is returning errors. However, `docker build` is happy to keep on building since no error is presented. That seems wrong.

```bash
root@869059bb2a82:/source# dotnet publish -a arm64 -o /app releasesapi.csproj -p:ObjCopyName=aarch64-linux-gnu-objcopy
MSBuild version 17.7.0+5785ed5c2 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/share/dotnet/sdk/8.0.100-preview.6.23330.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/source/releasesapi.csproj]
  releasesapi -> /source/bin/Release/net8.0/linux-arm64/releasesapi.dll
  Generating native code
  ILC: Method '[releasesapi]Program.<Main>$(string[])' will always throw because: Failed to load assembly 'Microsoft.AspNetCore'
  releasesapi -> /app/
root@869059bb2a82:/source# echo $?
0
```

**Comment by jkotas** [comment]
> Failed to load assembly 'Microsoft.AspNetCore'

Missing dependencies are only a warning, they are not a hard error.

Assemblies with (intentionally) missing dependencies are very common in .NET ecosystem. We make best effort to treat missing dependencies as non-fatal errors and make the AOT binary throw the same exception as the JIT-based runtime would throws.

The actual problem is that the ASP.NET framework is not getting referenced by the AOT compilation for some reason.

**Comment by richlander** [comment]
I figured out what going wrong. It is due to this: https://github.com/dotnet/sdk/issues/34026.

OK. That's a design choice. This particular issue was fatal (the app crashes, obviously). I can see the category is more general, however.
