### ISSUE TITLE
[RijndaelManaged] System.PlatformNotSupportedException: 'BlockSize must be 128 in this implementation.'

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/runtime#895]
Hi,

What should I do to fix this?

Example code:

```
var aes = new RijndaelManaged // or AesManaged 
{
    KeySize = 256,
    BlockSize = 256,
    Padding = PaddingMode.PKCS7,
    Key = Convert.FromBase64String(key),
    IV = Convert.FromBase64String(iv)
};
```

 `<TargetFrameworks>netstandard2.1;net461</TargetFrameworks>`

**Comment by Gnbrkm41** [comment]
Which framework do you get the error from? [The document seem to suggest any other size than 128 is not supported on .NET Core:](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndaelmanaged?view=netframework-4.8)
> This algorithm supports key lengths of 128, 192, or 256 bits; defaulting to 256 bits. In .NET Framework, this algorithm supports block sizes of 128, 192, or 256 bits; defaulting to 128 bits (Aes-compatible). In .NET Core, it is the same as AES and supports only a 128-bit block size.

Though your `TargetFrameworks` is set to target .NET Framework 4.6.1 as well, so I can't tell. Also interesting that there's mention in the document that you should use `Aes` instead of this due to this being a predecessor of it..

**Comment by dehghani-mehdi** [comment]
I get the error when I changed `<TargetFrameworks>netstandard2.1;net461</TargetFrameworks>` to `<TargetFramework>netstandard2.1</TargetFramework>`  too. (I'm using same code in my other project which target net461 without problem).

I'm using some web service which gives me the `key` and `iv` and I have to send back the encrypted data in order to use their sevice, using `Aes` will be provide same result?

**Comment by Gnbrkm41** [comment]
Targeting .NET Standard doesn't tell much about the runtime you're running it on, though as far as I'm know .NET Core and Mono is the only framework that is compatible with .NET Standard 2.1 so it's probably .NET Core.

From what I understand AES is a subset of Rijndael which supports fixed block size of 128 bits and a key size of 128, 192, or 256 bits. The block size being 256 here might cause problems using AES perhaps.

I can't find an implementation of Rijndael which support block size of 256 on .NET Core, though I'm not good at this area either so someone that knows better could chime in 🙂

**Comment by dehghani-mehdi** [comment]
Thank you @Gnbrkm41 

I tried https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes?view=netframework-4.8#examples (`EncryptStringToBytes_Aes` method) in LINQPad with the key which I got from that service provide, and I got same error. (but using `RijndaelManaged` everything works as expected). so I think I have to use `RijndaelManaged`.

I have no idea what should I do, it's blocking issue for me. I can not run/test my code because of this problem.

**Comment by vcsjones** [comment]
.NET Core does not support AES/Rijndael with a block size other than 128. @Gnbrkm41 gave a pretty good summary of the issue.

Rijndael (pre AES-specification) supported different block sizes. The final, standardized version of AES only uses a block size of 128 and different block sizes were removed from its specification.

`RijndaelManaged` in .NET Framework was a pure, C# implementation of Rijndael (as were all of the other `*Managed`). In .NET Core there are no managed implementations of cryptographic primitives. They all depend on components as part of the underlying operating system. To my knowledge, none of these underlying components support block sizes other than 128-bits for AES.

The `RijndaelManaged` class was brought back in .NET Core 2.0 for API compatibility. However unlike the .NET Framework, the implementation forwards to an AES implementation.

> I have no idea what should I do, it's blocking issue for me. I can not run/test my code because of this problem.

You should use AES / Rijndael with a block size of 128 bits - or plan to migrate to it. I suppose you could do that with the .NET Framework by decrypting it with `RijndaelManaged` and re-encrypting it with a block size of 128. Then you are using AES and .NET Core will be able to interact with it.

**Comment by dehghani-mehdi** [comment]
@vcsjones very nice explanation. thank you.

> You should use AES / Rijndael with a block size of 128 bits - or plan to migrate to it. I suppose you could do that with the .NET Framework by decrypting it with RijndaelManaged and re-encrypting it with a block size of 128. Then you are using AES and .NET Core will be able to interact with it.

You mean I have to make separate .NET Framework project just for decrypting and re-encrypting, and then use the result inside my .NET Core app? it's not possible for me and I think it's not ideal solution. 

Also what about cross-platform support if we add such a dependency to NET Framework?

**Comment by vcsjones** [comment]
> You mean I have to make separate .NET Framework project just for decrypting and re-encrypting, and then use the result inside my .NET Core app?

I suppose it depends on what you use-case is for using a non-standard block size. If you are trying to decrypt / encrypt your own data, my personal recommendation would be to migrate to Aes by making a one-time-use .NET Framework application that would decrypt the data using the 256-bit block size, then re-encrypt it with a 128-bit block size. That way everything is migrated. Once your data is encrypted with a 128-bit block size, The `Aes` class will work as-expected in .NET Core.

If you are trying to decrypt data that you have no control over that is coming from a 3rd party, or for other reasons need to continue to use a non-standard block size, you could have a private implementation of `RijndaelManaged` and `RijndaelManagedTransform` in your own application: https://github.com/microsoft/referencesource/blob/master/mscorlib/system/security/cryptography/rijndaelmanagedtransform.cs which is MIT licensed.

**Comment by dehghani-mehdi** [comment]
> If you are trying to decrypt data that you have no control over that is coming from a 3rd party

Yes, this is the case

> you could have a private implementation of RijndaelManaged and RijndaelManagedTransform in your own application:

It's too scary for me, I have no idea about cryptography stuff.

I'm wondering is there any similar migration (from .NET Framework to .NET Core) problems? If so, I guess using .NET Core could be problem for lot's of companies, they have some sort of working projects (as we do) and for using .NET Core they have to convert their code to .NET Core world __AND__ start implementing such a low level classes? that's not what I was thinking about .NET Core.

**Comment by bartonjs** [comment]
.NET Framework implemented the Rijndael algorithm before AES got standardized (2001) (it was sort of unfortunate timing, because AES standardization beat the release of .NET Framework 1.0, but not the betas... I wasn't on the team back then, so I don't know if there was a discussion of "do we cut support at the last minute?" or not).  The AES algorithm is just the Rijndael algorithm when the block size is fixed at 128-bit.

To avoid timing side-channel vulnerabilities, and compliance problems (both for us as a platform and applications built on us), .NET Core has eliminated the managed implementations of cryptographic algorithms.  The plan is to never bring them back (as @vcsjones pointed out, we brought back the class names, but they're purely for ease of porting... AesManaged asks the OS to do AES, and RijndaelManaged asks the OS to do AES... the OS won't do the more general Rijndael algorithm).

> I'm wondering is there any similar migration (from .NET Framework to .NET Core) problems?

There are a lot of things that either aren't in .NET Core at all (AppDomains, non-AES Rijndael) or aren't available on other platforms (System.DirectoryServices). 

https://docs.microsoft.com/en-us/dotnet/core/porting/ recommends the API Port tool (which identifies compile failures you're likely to expect from types or members that don't exist in .NET Core) and the [API Analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer), which identifies places that .NET Core throws PlatformNotSupportedException (when .NET Framework didn't).  The API Analyzer should flag calling RijndaelManaged.BlockSize's setter.

> what about cross-platform support if we add such a dependency to NET Framework?

.NET Framework only runs on Windows.

> I have no idea what should I do, it's blocking issue for me. 

I'll agree with @vcsjones that the best answer is to get existing data converted from Rijndael-with-blocksize-256 to AES, and change the pipeline going forward.  If you can't get the encrypting party to adjust their process to use the algorithm which has been the industry standard for years; you might be able to do it with BouncyCastle, or another 3rd party solution.  Per http://www.bouncycastle.org/specifications.html, their RijndaelEngine class supports the 256-bit block size, but the easier to use Rijndael class does not.

Helping you with BouncyCastle (or other 3rd party packages) is outside our domain of expertise.  I also don't know that it would actually work for you, I'm just basing it on their docs. (Heck, I don't even know which of the BouncyCastle packages to reference.  Maybe BouncyCastle.Portable?)

**Comment by dehghani-mehdi** [comment]
> .NET Framework only runs on Windows.

I know that :p.

By

> what about cross-platform support if we add such a dependency to NET Framework?

I meant if I build the .NET Framework app to do the encrypting job and then use this data in .NET Core app, now I have to run my app in Windows only, because my app depends on that _.NET Framework_ app. and this is not what I want.

**Comment by GrabYourPitchforks** [comment]
I'd like to put a finer point on something mentioned earlier. The AES standard that we all know and love supports __only__ a 128-bit block size. If an application is using Rijndael with a 256-bit block size, it's almost certainly doing something custom which doesn't conform to any industry standard or regulation.

I understand the desire to keep the surface area small for consumers of this application. But the bottom line is that there's a near-zero chance of this functionality being brought back to .NET Core. The reasons for this have been outlined above.

The best bet would be to follow one of the alternative proposals: decrypt and re-encrypt the data with a standardized cryptographic algorithm, or rely on a third-party component to implement the non-standard algorithm, or implement the non-standard algorithm manually in your own code. Since you mentioned your application handles payment data, I'd recommend the "use a standardized algorithm" approach.

**Comment by dehghani-mehdi** [comment]
@GrabYourPitchforks 

I don't control over their data and I have to use Rijndael with a 256-bit block size, because they do. I'll try to contact them and maybe send link of this issue to them, maybe they change their implementation. in the meanwhile, what you mean by `use a standardized algorithm approach`.

**Comment by GrabYourPitchforks** [comment]
"Use a standardized algorithm" means migrate to AES proper, as recommended in an earlier comment. You could write a tool in .NET Framework to perform this migration. Alternatively, you could use a third-party library (even from .NET Core) to perform this migration.

**Comment by dehghani-mehdi** [comment]
@GrabYourPitchforks 

> You could write a tool in .NET Framework to perform this migration

If you mean I can build an app (using .NET Framework) to convert non-standard data (from service which I'm working with) and then change it to standard data and then I use this data, I mentioned before, with this solution I have to run my app on Windows (because that convertor app).

About _third-party library_ I also mentioned this before, using other libraries to deal with this kind of data is not an option for me. I have to use native solution.

If I got you wrong, please explain with more details.

**Comment by bartonjs** [comment]
We just seem to be circling here. The only options that I can think of:

* Using .NET Framework, you do a one-time decryption all of the data then re-encrypt it with AES.
  * This is for data at rest, and you're the data encryptor, but neither of those applies here.
* You convince the data encryptor to change to AES.
  * In progress?
* You write Rijndael yourself to decrypt the 256-bit blocksize data.
  * You, understandably, don't want to do this.
* You use a 3rd party implementation of Rijndael.
  * You don't want to do this.
* You write a service in .NET Framework that decrypts the data using Rijndael and re-encrypts it using AES before your .NET Core programs see it.
  * This may or may not be feasible, depending on where your programs run, how they get keys, et cetera.

**Comment by dehghani-mehdi** [comment]
@bartonjs 

> You convince the data encryptor to change to AES. 

Yeah, they won't do that anytime soon.

So I guess the only option is using "3rd party implementation of Rijndael". I have to convince my clients. is there any chance so I can copy non-standard .NET Framework implementation directly to my source code?

**Comment by suj87** [comment]
For anyone else coming across this, see https://github.com/2Toad/Rijndael256/issues/13#issuecomment-637724412 for a quick solution. Requires BouncyCastle.NetCore.
