### ISSUE TITLE
JIT: LowerHWIntrinsicGetElement can reorder trees unsafely

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#89565]
The following example throws `ArgumentOutOfRangeException` when `Vector256` is hardware accelerated, but `NullReferenceException` when it isn't (`DOTNET_EnableAVX=0`).

```csharp
public class Program
{
    public static unsafe void Main()
    {
        Foo(null);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static unsafe float Foo(Vector256<float>* v)
    {
        return (*v)[8];
    }
}
```

Context: https://github.com/dotnet/runtime/pull/83005#issuecomment-1653663453

**Comment by AndyAyersMS** [comment]
The `InsertBefore` here can reorder the indir and the bounds check, we need to check that the indir is invariant in the range between its old position and new.

https://github.com/dotnet/runtime/blob/6f18b5ef46a8fbc6675b07d4b256c35b36fc4e3c/src/coreclr/jit/lowerxarch.cpp#L4462-L4468

**Comment by AndyAyersMS** [comment]
Seems like there are potentially two problems here. First we may move op1 (indir) below an existing bounds check this (issue). We can fix that by having the indir appear earlier if there is interference.

For the second problem, we may incorporate op2 into the indir. However it appears that any side-effecting computation feeding op2 must be done earlier and op2 will be a temp, since the value needs to be used in both the bounds check and the index. So it should be ok for op2 to be evaluated early.

**Comment by AndyAyersMS** [comment]
If op2 ends up being very large or negative and is folded into the indir, we might violate the implicit null check rules, so we might fail to properly null check before we bounds check (which presumably will fail). Hmm. So perhaps we can't fold `op2` into the indir if the indir itself can't be moved up.
