### ISSUE TITLE
[browser][perf] Blazor startup regression 2023-04-21

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#89631]
- https://msit.powerbi.com/groups/me/reports/10265790-7e2e-41d3-9388-86ab72be3fe9/ReportSection5ddef44dec0ed1074279?experience=power-bi
- Affected run from commit `e795ec77ab3737b54c8ab3e92f87a02d29eaeabb`, previous run from commit `e21ecb3dc51338f4d8288a844cb8491f550e4cd1`
- Runtime changes between 2023-04-14 - 2023-04-21
- Suspicious changes
  - https://github.com/dotnet/runtime/pull/83998
  - https://github.com/dotnet/runtime/pull/84296
  - https://github.com/dotnet/aspnetcore/pull/47752

cc @radekdoulik

**Comment by maraf** [comment]
It wasn't able to reproduce the regression locally. Local runs for commits from mentioned PRs had variations

**Comment by lewing** [comment]
Were there any System.Text.Json commits nearby in the history but outside the range?

**Comment by pavelsavara** [comment]
Right now I think that the regression could be caused by postponing the start of the DLL downloads until `dotnet.runtime.js` is loaded , which happened in https://github.com/dotnet/aspnetcore/pull/47752

I hope I mostly fixed that in my https://github.com/dotnet/runtime/pull/89857

**Comment by pavelsavara** [comment]
I Net7 Blazor didn't have any download throttling at all.
After unification of the loader, we throttle downloads to max 16  in parallel.
We do it in order to make the startup **more stable in low resource environments**, such as codespaces and helix.
Maybe also mobile phones benefit, but I don't have data for that.

https://github.com/dotnet/runtime/blob/c6db89c5d5d4f1667f0a72451cf816315492a265/src/mono/wasm/runtime/loader/globals.ts#L70

But maybe it's impacting the perf benchmark because it's running on beefy machine with local web server.

We could
- change the default to something more aggressive, like 32 parallel or even unlimited (and just set it low for our unit tests)
- admit that measuring startup time on fast machine with local server is not realistic. Leave it as is, or even add server side network throttling.
- disable our throttling just for Blazor

**Comment by maraf** [comment]
The throttling was still "disabled" in this regression https://github.com/maraf/aspnetcore/blob/4b7087f7dd984b2a7d882ff8ad3305a5959f7f66/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L252C27-L252C34

**Comment by maraf** [comment]
Changes from https://github.com/dotnet/runtime/pull/90388 seems promising 
![image](https://github.com/dotnet/runtime/assets/10020471/edbf9e89-fdbb-40b3-8d43-d9778caffda1)

**Comment by maraf** [comment]
We have gained something back with mentioned PR
![image](https://github.com/dotnet/runtime/assets/10020471/1819442d-680c-48f2-b3d4-2a4080f96e04)
