### ISSUE TITLE
Self-contained C++/CLI 

### ISSUE THREAD

**Issue by cincuranet** [dotnet/runtime#897]
Is there a way to force a C++/CLI (using `Ijwhost.dll`) to load runtime etc. from local (or some) directory, instead of looking into `C:\Program Files`?

**Comment by jeffschwMSFT** [comment]
Ijwhost should respect all the same mechanisms for finding an appropriate runtime to load as other entry points into .NET Core.  You can set DOTNET_ROOT or publish self contained.  What is scenario, so that we can best help?

cc @jkoritzinsky

**Comment by cincuranet** [comment]
In my case the `DOTNET_ROOT` does not work, because I'm compiling a DLL and when it's being loaded (and I don't have control over the process) it's too late to set the envvar.

I'd go for publishing self-contained, but how to do it for C++/CLI project?

**Comment by jkoritzinsky** [comment]
We currently don't support self-contained components (comhost.dll, ijwhost.dll, and nethost.dll) since the "two self-contained components loaded into the same process" scenario would result in loading .NET Core into the process twice, which is unsupported. The code snippet below is where it is blocked.

https://github.com/dotnet/runtime/blob/3c0cea3b5b329f4ed2e7ed32b9d4de3dc41f6f35/src/installer/corehost/cli/fxr/fx_muxer.cpp#L577-L581

**Comment by cincuranet** [comment]
In my scenario I could make it a requirement (and failing otherwise is fine) in case .NET Core would be loaded twice. But at the moment I suppose I'm out of luck. :(

Maybe I can try building my own ijwhost.dll.
