### ISSUE TITLE
[API Proposal]: Make AggregationManager public

### ISSUE THREAD

**Issue by hananiel** [dotnet/runtime#89727]
### Background and motivation

From this [comment](https://github.com/dotnet/runtime/issues/66592#issuecomment-1067202287) from @noahfalk it appears that Metrics that are collected using the Meter API, need a third party aggregation mechanism even though an internal implementation exists [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/AggregationManager.cs).

We are a third party provider of Metrics functionality which provides customized [views](https://docs.steeltoe.io/api/v3/management/metrics-endpoint.html) for observability tooling such as CloudFoundry and other OSS tools such as [Spring Boot Admin](https://github.com/codecentric/spring-boot-admin) and [Tanzu App Live View ](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-app-live-view-about-app-live-view.html)(commercial).  Currently we are using the internal implementation by copy-paste to get this functionality.  We cannot take a dependency on OpenTelemetry.NET  without interfering with customers own use of OpenTelemetry.NET.  

### API Proposal

Make `AggregationManager` public along with the provided aggregation types and make the the aggregation types easily extensible - for example we should be able to add a HistogramMax and Sum to the existing HistogramAggregation. 

### API Usage

```csharp
  var aggregationManager = new AggregationManager(...)

  // ... elsewhere 
  aggregationManager.Collect()
``` 
The input types to AggregationManager should also be public. 

### Alternative Designs

We have used HDRHistogram and OpenTelemetry in the past, but would prefer the implementation above.

**Comment by tommcdon** [comment]
@tarekgh is this work included with planned .NET 8 metrics work?  Since we are past platform shutdown for .NET 8 I would expect that work not already planned at this point should be moved to .NET 9.

**Comment by tarekgh** [comment]
Exposing this class is not part of the plan and has not been discussed as a viable option. The runtime is not designed to offer aggregator APIs, as this functionality is already covered by OpenTelemetry. Certainly, this will not be for .NET 8.0. Exposing any APIs has to go through design and approval process.

> We cannot take a dependency on OpenTelemetry.NET without interfering with customers own use of OpenTelemetry.NET.

I find it puzzling why relying on OpenTelemetry would hinder customers from utilizing it for their own purposes. If this situation indeed arises, it should be addressed by the OpenTelemetry project itself rather than resorting to makeshift solutions. It is essential to tackle the root of the issue rather than applying temporary workarounds.

CC @reyang @CodeBlanch @noahfalk

**Comment by bart-vmware** [comment]
> > We cannot take a dependency on OpenTelemetry.NET without interfering with customers own use of OpenTelemetry.NET.
> 
> I find it puzzling why relying on OpenTelemetry would hinder customers from utilizing it for their own purposes. If this situation indeed arises, it should be addressed by the OpenTelemetry project itself rather than resorting to makeshift solutions. It is essential to tackle the root of the issue rather than applying temporary workarounds.

We used to reference OpenTelemetry in the past, but it has been a painful experience over time, due to breaking changes. It's basically the same story as with Newtonsoft.Json vs System.Text.Json. Assuming our library references Otel v1.x and a consumer uses Otel v2.x (which has binary breaking changes) together with our project, then it breaks. OpenTelemetry can't solve that.

The only thing we can do to avoid this is reflection-loading the OpenTelemetry assemblies at runtime without referencing them, but then we can't expose APIs that use their types. And reflection-based calls on metrics are pretty expensive. However, if the basic building blocks for what we need are provided by the .NET BCL, then we can multi-target against .NET versions to deal with breaking changes.

That's why we currently have copied internal classes from the BCL. It performs well and enables consumers of our library to reference any version of OpenTelemetry they'd like. But this isn't great from a maintainability perspective of our codebase. We're simply choosing the lesser of evils.

**Comment by tarekgh** [comment]
@reyang @CodeBlanch do you have any thoughts around the OpenTelemetry dependency problem? Any suggestions on how users can take dependency safely and avoid breaking?

**Comment by reyang** [comment]
> @reyang @CodeBlanch do you have any thoughts around the OpenTelemetry dependency problem? Any suggestions on how users can take dependency safely and avoid breaking?

I don't know what are the specific problems, @bart-vmware would you provide more context here? Or maybe you have a link to the OpenTelemetry .NET issue or discussion?

**Comment by noahfalk** [comment]
@bart-vmware @hananiel - thanks for reaching out! A couple thoughts:

- We want to spend our .NET engineering efforts on features that will benefit a large number of projects built on .NET at the same time. From what I know so far, not enough projects would likely benefit to justify supporting AggregationManager + new features as a public API.
- Copying the source doesn't seem a bad place to be. My understanding is that we've found relatively few bugs in this code that would require effort for you to merge an update and you get total control over any new features/extensibility you want without being tied to the .NET release schedule.
- There are options using tools like [ILRepack](https://github.com/gluck/il-repack) or [AssemblyLoadContext](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=net-7.0) to load different versions of the same library side by side. I don't have enough context to know if these would be good solutions for your situation, just giving a heads up if you weren't aware of them.
- @reyang is a great contact for OpenTelemetry.NET, if you discuss with him and his team you might find solutions to your underlying OpenTelemetry troubles.

Sorry I know its not what you were aiming for initially, but hopefully it still helps a bit.

**Comment by hananiel** [comment]
@noahfalk Thank you!  Yes this is helpful and completely makes sense.
