### ISSUE TITLE
Building ILC causes double writes in the runtime build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#89763]
Repro: `build.cmd/sh clr+libs /bl`

Inspect the binary log and find the following double write:

<img width="589" alt="image" src="https://github.com/dotnet/runtime/assets/7412651/9b86c601-26ea-44a0-9e8b-a6d559e57ea4">

This is problematic as it makes the build slower as it needs to be and might break the incremental build feature in msbuild. After fixing this issue, we should consider adding CI protection to guard against double writes by doing something similar to https://www.meziantou.net/detecting-double-writes-in-msbuild-using-the-binlog.htm. AFAIK the roslyn team already does that.

cc @MichalStrehovsky

**Comment by ViktorHofer** [comment]
I see. Do you know if there's something that we can do in runtime meanwhile to avoid the double write?

**Comment by MichalStrehovsky** [comment]
I don't like that we do that in the product itself either. I don't think there's anything we can do from here besides patching the SDK targets in the nuget cache after they restore.

The SDK gets really mad if UseAppHost is false on something it considers self-contained. I was trying to fix this in https://github.com/dotnet/sdk/pull/33229 that you're Cc'd on but it's currently in limbo because I'm _sure_ it will break something else and I'm not mentally capable to deal with the worms from that can at this time. I'll be taking some time off soon so maybe after that.
