### ISSUE TITLE
Serialization not supported Exception in .Net Core 

### ISSUE THREAD

**Issue by jyoti17github** [dotnet/runtime#89811]
I am trying to migrate WPF application to .NET core . In my project serialization is used heavily. Below function work well on .NET 4.7 framework but after migrating to .NET core 3.1 gives error ' Serializing delegates is not supported on this platform' .

 ```

  public static T Clone<T>(T source)
    {
        if (ReferenceEquals(source, null))
            return default(T);

        IFormatter formatter = new BinaryFormatter();
        Stream stream = new MemoryStream();
        using (stream)
        {
           
            formatter.Serialize(stream, source); // this line is erring 
            stream.Seek(0, SeekOrigin.Begin);
            return (T) formatter.Deserialize(stream);
        }
    }
```
I have changed serializable classes where ever => operator used or any property used delegates. After doing this part of  project code worked but some of module in project still throwing error - Serializing delegates is not supported on this platform.

Also typeof(T) - shows ReflectedType = null  so to check using Reflection source(type).isSerializable won't help.

Is there anyway to find which particular object or property is throwing this exception?

Also , there is no option to change formatter type to another JSON/XML as that will need significant architecture change in Project. 

Appreciate any guidance or suggestion on this issue.

Thanks in advance.

**Comment by marcpopMSFT** [comment]
Old issue triage: Moving to runtime. (we also see binary formatter in there)

**Comment by tannergooding** [comment]
@GrabYourPitchforks, could you take a look at this as it seems related to binary serialization?

**Comment by GrabYourPitchforks** [comment]
The list of Serializable types is provided at https://learn.microsoft.com/previous-versions/dotnet/fundamentals/serialization/binary/binary-serialization. Note that delegates and other reflection-based constructs are intentionally not on this list.

In general there is no reliable way to clone arbitrary object graphs in dotnet. If you control the types I suppose you could always create a dedicated DeepClone method and recursively clone the objects within that method. But it requires you to own every type in the graph, because you can't clone arbitrary dotnet types.

Triage owners: the runtime is behaving by design. This is more of a discussion issue and doesn't require any changes to the runtime.
