### ISSUE TITLE
Consider memoizing more CNG properties on CngKey that can't change after the key is finalized

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#89821]
#89599 shows that accessing some CNG properties are relatively expensive to the cryptographic operation itself. That pull request memoized the result for KeySize so that reading the KeySize property doesn't incur the overhead of reading ncrypt properties, which requires an RPC call.

We should consider what other properties can be memoized for performance. https://github.com/dotnet/runtime/pull/89819 showed that `AlgorithmGroup` is likely another candidate.

**Comment by bartonjs** [comment]
I think there are times that we can see a non-"finalized" key, e.g. between PFX import and the key first use (which is why the export policy can be changed then).  So the remembering part might need to be itself guarded by a semi-memoized state check on key finalization (remember yes, don't remember no).
