### ISSUE TITLE
Compatibility issue with ProcessStartInfo with UseShellExecute=False and WindowStyle=Hidden

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#89910]
Earlier in .NET 8, we made a change to [Support WindowStyle without UseShellExecute #82662](https://github.com/dotnet/runtime/pull/82662) to open up a scenario for PowerShell to avoid the need for a P/Invoke. This change was found to cause unexpected behavior changes regarding the order of events received by child process windows (such as `Activated` and `Loaded`). This led to [Test failures in WPF](https://github.com/dotnet/wpf/issues/8043).

We need to reconsider the changes made in #82662 for #81681 and determine if the event ordering change can be safely mitigated to not cause this unexpected change in behavior. As it is, those WPF tests indicate the likelihood of app developers having set these properties (even if not wholly necessary in their scenarios), and now their subsequent code can have application-level bugs where the event ordering leads to different behavior. In the case of the WPF tests, this change led to an `ArgumentOutOfRangeException` later in the application code because the tests depended on the event ordering.

Unless there is a clear, low-risk fix, we should err on the side of reverting the change. Reverting will have impact on PowerShell though, as it's likely they've updated code to remove the P/Invoke that would no longer be needed with the new behavior that became supported.

@Jozkee @jborean93 @SteveL-MSFT @iSazonov

/cc and kudos to @rchauhan18 for the diagnosis conducted on the WPF test issue.

**Comment by jborean93** [comment]
> Reverting will have impact on PowerShell though, as it's likely they've updated code to remove the P/Invoke that would no longer be needed with the new behavior that became supported.

No progress was made on the PowerShell side so you can revert without affecting them. I cannot say for any other application that might be using the changes in the new preview, if there are any.

> Unless there is a clear, low-risk fix, we should err on the side of reverting the change

While I no longer have any vested interest or driver in preserving the change and I can understand the desire to not break any external applications I would like to still advocate keeping the change for the following reasons:

* The docs explicitly mention that to use `WindowStyle.Hidden` you need to specify `UseShellExecute = false`

Granted this is only a doc entry and not a behaviour enforced in the code the docs do state for [ProcessStartInfo.UseShellExecute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=net-7.0)

> If you set the `WindowStyle` to `ProcessWindowStyle.Hidden`, `UseShellExecute`must be set to true.

The fact that people might be setting `WindowsStyle = ProcessWindowStyle.Hidden;` today and it's not actually hiding the Windows could even be considered a bug as the code is completely ignoring the value.

* Implementing support for this will be impossible without a more complex API

If you do revert this change but still want to support setting the window style without the "shell", you would have to probably add another property that tells dotnet to use the flag for `UseShellExecute = false`. You can't even warn users about this because WPF or other applications are setting it without anything happening today. This makes an already complex API even more confusing. I'm not even aware of any deprecation mechanism in dotnet where things are actively removed so we will be essentially stuck with what we have.

> There is a workaround that works for both existing versions and the dotnet 8

As `WindowStyle.Hidden` (or any other the other styles) does nothing with dotnet 7 or earlier and `UseShellExecute = false` they can simply just not set the window style and the behaviour will be the same. I understand that there is code today out there which might be setting the value but tying back to my original point where `WindowStyle.Hidden` does nothing with `UseShellExecute = false` there shouldn't be any sane reason for people to continue to set that when it does nothing.

The difference is that now if people wish to use the features available to a process with `UseShellExecute = false` (like redirection, environment variables, credentials) they can now do so while also specifying the Window style. Without a change like the one in the PR users will either have to:

* Use their own PInvoke code and reimplement all the complexities of the Win32 `CreateProcess*` APIs
* Use a 3rd party nuget that does that for them which is now another dependency

Even then these solutions won't solve everything as you won't be able to produce a `System.Diagnostics.Process` object using your own handle. If you can't use your own handle then you need to create an object with [Process.GetProcessById](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.getprocessbyid?view=net-7.0) which won't work if you don't have permission to open the process (started it with different credentials).

In the end I'm just a user of dotnet and would love to see this change stay but I have no authority to make this decision, hopefully this may persuade you to avoid reverting the changes.

**Comment by Jozkee** [comment]
I agree with @jborean93 on keeping the change as it is really fixing a bug in our code. PowerShell may still not depend on it but another partner does already https://github.com/microsoft/playwright-dotnet/pull/2623.

I suggest we document the breaking change explaining that now that we correctly honor the WindowStyle.Hidden flag, the order of events changed when used.

**Comment by iSazonov** [comment]
If it's a bug fix, it certainly shouldn't be reverted. Another question is how much WPF depends on this fix and whether it needs backward compatibility. If WPF is unrealistic to fix, then maybe add an environment variable for backwards compatibility, if it is allowed, or a new parameter in csproj so that WPF can use old behavior.

**Comment by Jozkee** [comment]
cc @dotnet/compat

**Comment by jeffhandley** [comment]
Thanks for the notes, folks! We'll work with our compatibility champs to do some more assessment of the potential impact.

I understand that ideally we wouldn't revert a bug fix, but the type of code that was in place that led to the behavior that this would break is innocent-seeming code that I can imagine lots of WPF apps have put in place without reading the docs or realizing they were becoming dependent upon buggy behavior. The fix leads to errors _elsewhere_ in their code and it won't be clear that the cause was us fixing this bug.

I need us to measure potential impact, consider how customers would even know what caused the change in behavior, and be certain it's a tradeoff we can make.

**Comment by jborean93** [comment]
> I can imagine lots of WPF apps have put in place without reading the docs or realizing they were becoming dependent upon buggy behavior.

While yes I can understand this viewpoint if code had an explicit `WindowStyle` with `UseShellExecute = false` set then they would most likely realise that the Window style wasn't actually being set. For example `WindowStyle = WindowStyle.Hidden` and `UseShellExecute = false` does nothing before the PR mentioned was implemented. The new process will be created without a hidden window. This would lead me to believe that it would be a rarer scenario with this happening as you would think people setting a window style would expect that style to actually be set.

**Comment by iSazonov** [comment]
> explicit `WindowStyle` with `UseShellExecute = false`

I see CreateNoWindows is usually used in the scenario. https://github.com/search?q=WindowStyle.Hidden+%22UseShellExecute+%3D+false%22+WPF&type=code
The request returns ~236 results. If there are popular projects we could directly ask them about the update.

**Comment by jeffhandley** [comment]
We had some more internal conversation about this, with some more impact analysis conducted. We've concluded that we should keep the change in place and document it as a breaking change. I labeled #82662 as a breaking change needing a doc created. That doc will need to cite examples like those @iSazonov pointed and show the types of errors/exceptions that can occur in app code when the change in behavior becomes observable.
