### ISSUE TITLE
`NetworkInterface.GetAllNetworkInterfaces()` doesn't list disabled adapters on Windows

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#89990]
### Description

On Windows, a disabled network adapter is not listed by `NetworkInterface.GetAllNetworkInterfaces()`.

### Reproduction Steps

1.
    ```csharp
    foreach (var ni in System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces())
    {
        Console.WriteLine(ni.Name + ": " + ni.OperationalStatus);
    }
    ```
2. Disable a network adapter.
3. Run the code again.

### Expected behavior

The disabled adapter is listed with `OperationalStatus.Down`.

### Actual behavior

The disabled adapter is not listed.

### Configuration

Windows 10
.NET 6 / .NET 7

**Comment by karelz** [comment]
.NET returns what [GetAdapterAddresses](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses) OS function gives us back:
https://github.com/dotnet/runtime/blob/e2b5936b758c10fe4f4f287393cb14a288febbd7/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/SystemNetworkInterface.cs#L103-L117

I assume that the function does not list disabled interfaces and that's why you don't see them.
I am not sure if there is other way for us to query network interfaces from the OS. @wfurt any thoughts?

Not critical for 8.0, moving to Future.

**Comment by wfurt** [comment]
We should verify what `GetAdaptersAddresses` returns. If anything, we should make it clear in documentation.

**Comment by MojtabaTajik** [comment]
@karelz @wfurt

It depends on the "flags" parameter we asked for "GetAdaptersAddresses" The current .Net implementation is:

https://github.com/dotnet/runtime/blob/e2b5936b758c10fe4f4f287393cb14a288febbd7/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/SystemNetworkInterface.cs#L88-L91

Based on [Windows API docs](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses), we need to pass "GAA_FLAG_INCLUDE_ALL_INTERFACES" as flag, if we want information of all adapters:

<img width="649" alt="image" src="https://github.com/dotnet/runtime/assets/15414923/aa8a14bf-75a9-4c06-a8c3-2b465fdf2cc8">

Then the received "IP_ADAPTER_ADDRESSES_LH" structure contains "OperStatus", which indicates the enabled state of the adapter.

**Comment by MojtabaTajik** [comment]
@wfurt I want to pick this ticket up.

**Comment by danmoseley** [comment]
What does it do on Linux/Mac?
