### ISSUE TITLE
Could not find core Assembly in MetadataLoadContext

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#90009]
### Description

I was switching to the preview of .NET 8 to try out the behavior of the framework.
Everything worked before so that switch to .NET 8 causes the problem. The code is simply Following:

```
            PathAssemblyResolver resolver = new(SearchFileNames);
            var ctx = new MetadataLoadContext(resolver);
```

has something changed here?

Thanks

### Reproduction Steps

I'm not sure if this is a known problem, and the core assembly needs to be handed over now.

### Expected behavior

Core assembly should not be needed.

### Actual behavior

It simply works.

### Regression?

Yes, in .NET7 it worked, now in .NET8 it doesn't work anymore.

### Known Workarounds

Switch back to .NET7

### Configuration

.NET8 / win-x64
Windows 10

**Comment by msedi** [comment]
It seems it has been reported already before: https://github.com/dotnet/runtime/issues/41921
The questions still is why did it work on .NET7?

**Comment by steveharter** [comment]
No changes to my knowledge were made from v7 to v8 to MetadataLoadContext that would have affected the loading behavior of the core assembly.

I assume the example in https://github.com/dotnet/runtime/issues/41921#issuecomment-881647265 works?

**Comment by MSDN-WhiteKnight** [comment]
What is in SearchFileNames variable in your example? If you try to inspect something that depends on System.Runtime, the collection of resolution paths must contain it. You could try to include all runtime assemblies, like in this example: https://github.com/dotnet/samples/blob/main/core/assembly/MetadataLoadContext/Program.cs#L23

**Comment by msedi** [comment]
@MSDN-WhiteKnight. Thanks for the info. Will try and show the result. The question is still why did it work before?

**Comment by MSDN-WhiteKnight** [comment]
>I have tried your suggestions and then the System.Runtime exception is gone, but then I get exceptions, like System.Xaml, PresentationFramework, etc.

MetadataLoadContext requres every dependency to be explicitly added into resolver paths, including framework assemblies. It is documented there: <https://learn.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext>, and it was always like that. The example i've linked adds every built-in runtime assembly to resolver paths, but does not include WPF assemblies such as System.Xaml, they are shipped separately. If you need to inspect code depending on WPF types, you need to add WPF assemblies too. I'm not aware of any easy way to lookup their paths, probably harcoding a path like 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\(version)' is the only solution.

I don't know how it was working before. Some differences in runtime versions behavior could be explained by type forward changes: MLC follows type forwards, so if previously some type was found via type forward, and then it was removed, next version will throw exceptions. But that can't explain how System.Xaml was found, there couldn't be any type forwards to it in runtiem assemblies. Maybe previously you were building a self contained application that copied all dependencies to current directory, and used current directory to lookup assemblies to resolve. Then in some version the publication changed to framework dependent due to some MSBuild properies, and now dependencies couldn't be found. In any case, the best way to ensure that dependencies will be resolved is to explicitly specify all paths.

**Comment by msedi** [comment]
@MSDN-WhiteKnight: Thanks for the feedback. I compared the output from NET7 to NET8 with the same build configuration, etc.
It seems that something really has changed. All the presentation framework assemblies that have been originally copied in NET7 are now not copied over to the output path in NET8. 

So in the end if is not a problem of the MLC, it must be some change in the output behavior.

**Comment by msedi** [comment]
I think we can close this one, as its seems not be a problem of the MLC. It seems something in the build process has changed in NET8 which does not copy the runtime assemblies to the output folder anymore.

I have opened an issue here #90513
