### ISSUE TITLE
Activity Tracking option for logger factory works differently for tags and baggage

### ISSUE THREAD

**Issue by yoziv** [dotnet/runtime#90071]
### Description

When using the activity tracking option on Microsoft extension logging logger factory to add baggage and tags from current tracing context adding tags to the log scope works good regarding the placement of key value pairs to the scope, and can be propagated to every exporter correctly, but when trying to add baggage to the scope each item is included such that the key for the scope is null and the value for the scope is the list of baggage items enumerated , because of that some log exporters don't pick up the scope because the key is null.

![image](https://github.com/dotnet/runtime/assets/59967231/59eaabb2-04cd-439f-a234-35c17d7ab5bc)

the difference is between scope 1 and 2 in the picture above

### Reproduction Steps

Used the weather forecast .net example and added instrumentation with activity tracking option a console exporter and open telemetry tracer.
this is instrumentation part of my service registration:

```c#
builder.Services
    .AddOpenTelemetry()
    .WithTracing(traceBuilder =>
    {
        traceBuilder
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("TestOtel"))
        .AddSource(Instrumentation.ActivitySourceName)
        .SetSampler(new AlwaysOnSampler())
        .AddHttpClientInstrumentation()
        .AddAspNetCoreInstrumentation()
        .AddConsoleExporter();
    });


builder.Logging
    .ClearProviders()
    .Configure(options => options.ActivityTrackingOptions = ActivityTrackingOptions.TraceId | ActivityTrackingOptions.SpanId | ActivityTrackingOptions.Baggage | ActivityTrackingOptions.Tags)
    .AddOpenTelemetry(options =>
{
    options.IncludeScopes = true;
    options.SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("TestOtel"));
    options.AddConsoleExporter();
    options.AddGenevaLogExporter(exporterOptions =>
    {
        exporterOptions.ConnectionString = "EtwSession=OpenTelemetry";
        exporterOptions.ExceptionStackExportMode = ExceptionStackExportMode.ExportAsString;
        exporterOptions.EventNameExportMode = EventNameExportMode.ExportAsPartAName;
    });
});
``` 

this is my controller:
```c#
        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            using var activityTest = _instrumentation.ActivitySource.StartActivity("TestActivity");
            activityTest?.SetBaggage("BagKeyFirst", "BagValueFirst");
            activityTest?.SetBaggage("BagKeySecond", "BagValueSecond");
            activityTest?.SetTag("TagKeyFirst", "tagValueFirst");
            activityTest?.SetTag("TagKeySecond", "tagValueSecond");
            var placeholder = "actual runntime value";
            _logger.LogInformation("{testPlaceHolder}", placeholder);

            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
``` 

### Expected behavior

the baggage will be added to the scope with a key so that exporters ( specifically the geneva log exporter) will be able to pick it up and send forward

### Actual behavior

the baggage is added to the scope without a key or with null key and so ignored by some exporters

### Configuration

.net 6

**Comment by tarekgh** [comment]
@yoziv what kind of logger and logging formatter is used to produce the output you are showing? The baggage scope is produced as [`IEnumerable<KeyValuePair<string, string>>`](https://source.dot.net/#Microsoft.Extensions.Logging/LoggerFactoryScopeProvider.cs,223) and implement `ToString()` which produce the output you are seeing in the output. The logger/formatter is what decide the formatting. Teh Tags scope is just exposed as `IEnumerable<KeyValuePair<string, object>>` which looks the formatter handle it differently than the baggage.  

CC @CodeBlanch @cijothomas

**Comment by tarekgh** [comment]
The problem is in OpenTelemetry code https://github.com/open-telemetry/opentelemetry-dotnet/blob/a831093ae18efeb7bcbcef1042d05c0cef05e7a8/src/OpenTelemetry/Logs/LogRecordScope.cs#L63. It doesn't handle the case `IEnumrable<KeyValuePair<string, string>>` and at that time will just use `ToString` to log the scope which produce the logger output you are seeing there. 

@CodeBlanch you may confirm and move this issue to OpenTelemetry repo.

**Comment by tarekgh** [comment]
@cakescience no worries, I'll do it.

**Comment by CodeBlanch** [comment]
I chatted with @tarekgh offline about this. My feedback was (more or less)...

IMO the best fix is to update [this custom TState](https://source.dot.net/#Microsoft.Extensions.Logging/LoggerFactoryScopeProvider.cs,223) to implement `IEnumerable<KeyValuePair<string, object>>` (`IReadOnlyList` would be even better for perf in OTel).

Because support for `KeyValuePair<string, object>` seems to be ubiquitous. `OpenTelemetry` and `runtime` support that convention, as does [Serilog](https://github.com/serilog/serilog-extensions-logging/blob/b524ab61765c7576971563355b5e68d8cd769ed9/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerScope.cs#L80-L107). I didn't check other `ILoggerProvider` implementations, but I suspect we will find the same.

I did a quick search through aspnetcore and it was turning up consistent as well for custom scope TStates:

* https://github.com/dotnet/aspnetcore/blob/55fa3024d23666e3301ddc06f349febac8f98449/src/Mvc/Mvc.Core/src/MvcCoreLoggerExtensions.cs#L280
* https://github.com/dotnet/aspnetcore/blob/55fa3024d23666e3301ddc06f349febac8f98449/src/HealthChecks/HealthChecks/src/HealthCheckLogScope.cs#L10
* https://github.com/dotnet/aspnetcore/blob/55fa3024d23666e3301ddc06f349febac8f98449/src/Mvc/Mvc.ViewFeatures/src/ViewComponents/DefaultViewComponentInvoker.cs#L284

A couple other notes:

* The [docs show using KeyValuePair<string, object>](https://github.com/dotnet/docs/blob/444753733df757d910cb9a7d46ea11eadcdd245b/docs/core/extensions/logging.md?plain=1#L478).
* The [proposed fix in OpenTelemetry is expensive](https://github.com/open-telemetry/opentelemetry-dotnet/pull/4746/files#diff-27f9c77032025b8e7903e44874f67a07845bf202bfe6f9a47bfdfb7baa1cf5e3R69) costing a list allocation and an enumerator allocation and CPU to copy things.
