### ISSUE TITLE
StringValues.IsNullOrEmpty returns false when multiple null values

### ISSUE THREAD

**Issue by TwentyFourMinutes** [dotnet/runtime#90240]
### Description

`StringValues.IsNullOrEmpty` returns false when only null values are present and the count is greater than 1.

### Reproduction Steps

```cs
StringValues.IsNullOrEmpty(new StringValues(new string?[] { null, null }))
```

### Expected behavior

```cs
StringValues.IsNullOrEmpty(new StringValues(new string?[] { null, null })) // Should return: true
```

### Actual behavior

```cs
StringValues.IsNullOrEmpty(new StringValues(new string?[] { null, null })) // Currently returns: false
```

### Configuration

Using `.NET 7.0.10`.

**Comment by ericstj** [comment]
Doesn't seem to be a regression.

Current behavior is
https://github.com/dotnet/runtime/blob/b35572540e0904c6a23dc5466f73c361ed877dc1/src/libraries/Microsoft.Extensions.Primitives/src/StringValues.cs#L435

Same as 3.1
https://github.com/dotnet/extensions/blob/8be8055472b38bfe594a47e71583192e20b704c6/src/Primitives/src/StringValues.cs#L367C1-L368C1

And even further back.  It's hard to tell if it's intentional but definitely not a regression.

**Comment by tarekgh** [comment]
The current behavior is documented behavior, and I don't think we can change it now as will be a breaking change. Users can easily workaround this issue if it is really blocking.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.stringvalues.isnullorempty?view=dotnet-plat-ext-7.0#returns
