### ISSUE TITLE
Assertion failed 'fgDidEarlyLiveness'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#90295]
I'm seeing this assert in a one-off `gcstress-extra` run (which shouldn't actually matter):

https://dev.azure.com/dnceng-public/public/_build/results?buildId=369204&view=ms.vss-test-web.build-test-results-tab

```
04:08:53.124 Running test: JIT/Regression/JitBlue/Runtime_78891/Runtime_78891/Runtime_78891.cmd

Assert failure(PID 5948 [0x0000173c], Thread: 3248 [0x0cb0]): Assertion failed 'fgDidEarlyLiveness' in 'System.Diagnostics.Tracing.EventSource:Initialize(System.Guid,System.String,System.String[]):this' during 'Physical promotion' (IL size 414; hash 0x578c91f2; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\forwardsub.cpp Line: 472
    Image: C:\h\w\BCD60A35\p\corerun.exe

```

**Comment by jakobbotsch** [comment]
#89876 added this test. The test disables early liveness and physical promotion, but when running with JitStress also, physical promotion can become reenable due to the stress mode. Physical promotion reinvokes forward sub in certain cases, and we hit this assert when early liveness was disabled.
Since physical promotion provides its own liveness information the assert is just overeager and should be removed (the forward sub pass already knows not to do anything if early liveness was disabled).
