### ISSUE TITLE
.net 8 preview 7: published Blazor app cannot start with js failed to load blazor.boot.json

### ISSUE THREAD

**Issue by jjzhang12** [dotnet/runtime#90324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We migrated our Blazor Webaseembly application from .net 7 to .net 8. It was fine in .net 8 preview 6.

After migrated it to preview 7, it's still fine to start it from Visual Studio, both debug and release mode.

Then we published the application, and then the application is stucked at initial stage without downloading any assemblies. The progress is stuck at 0%. The errors in the browser:

dotnet.js:3 MONO_WASM: onConfigLoaded() failed TypeError: **n is not a function**
    at Object.onConfigLoaded (blazor.webassembly.js:1:38355)
    at dotnet.js:3:24155
    at async dotnet.js:3:23069
    at async Object.create (dotnet.js:3:29764)
    at async blazor.webassembly.js:1:38520
    at async Yt (blazor.webassembly.js:1:54783)
    at async on (blazor.webassembly.js:1:56394)
a @ dotnet.js:3
blazor.webassembly.js:1 Error: Failed to start platform. Reason: Failed to load config file ./blazor.boot.json TypeError: n is not a function
    at Yt (blazor.webassembly.js:1:54824)
    at async on (blazor.webassembly.js:1:56394)
(anonymous) @ blazor.webassembly.js:1
4dotnet.js:3 Uncaught (in promise) Failed to load config file ./blazor.boot.json TypeError: n is not a function

Just created a new application from template cannot reproduce this issue.

### Expected Behavior

.net and our assemblies should start downloading.

### Steps To Reproduce

Not reproducible with new Blazor application from template, but with our full application. Please suggest what I should provide.

### .NET Version

8.0.100-preview.7.23376.3

**Comment by mkArtakMSFT** [comment]
@lewing this looks severe enough to address in RC1, for which we have very little time left.

**Comment by pavelsavara** [comment]
Is this possibly workload version mismatch ?
It seems that blazor is calling function which doesn't exit in the runtime, possibly `invokeLibraryInitializers` which didn't exist in preview 7.

@jjzhang12 we discussed latest nightly build on another issue and so I think that your dev environment could be broken.

I suggest that you 
- clean your build and do full re-build 
- if that doesn't help, delete your dotnet SDK folder and install just desired version. then clean and rebuild again.

Please let us know.

**Comment by kg** [comment]
A zip file with the dotnet.js and blazor.webassembly.js from your publish dir would also help us troubleshoot, if you can provide that.

**Comment by jjzhang12** [comment]
@pavelsavara I did not use night build for that issue. I only installed Preview 7. But my machine did have previous previews.

Today I just setup a new machine with VS 18.1 and .net 8 preview 7, and copy my project folder to there. I can still see the issue.

I looked at the published folder, see the dotnet.js.br is dated 7/26 and it's not packed today. I seached my machine and I don't find the file elsewhere. I download the donet.js file from browser and compare with the dotnet.js file, it's different. See attached files for the three dotnet.js files.
[dotnet.js.zip](https://github.com/dotnet/runtime/files/12318081/dotnet.js.zip)

If I delete the dotnet.js.br file from the published folder, then startup will not stuck there and go all the way to 98% and met  the famous dll 'integrity' issue, but that's different issue and I will see if I can clear it.

**Comment by pavelsavara** [comment]
Maybe clean browser cache ?

**Comment by pavelsavara** [comment]
cc @maraf

**Comment by markushaslinger** [comment]
I ran into this today when testing the latest build from GH Actions. Turns out GH Actions still uses preview6 (as of a couple hours ago) if only version `8.0.x` is specified for the `actions/setup-dotnet@v3`.

Building with `8.0.100-preview.7.23376.3` explicitly resolved the issue for me. 
Just in case that helps you tracking the issue down.

**Comment by jjzhang12** [comment]
@pavelsavara I alway cleared the browser cache for newly published app. The issue is that the compressed dotnet.js inside published donet.js.br is different than the plain text dotnet.js file, and Blazor host server is always sending the br file to browser.

For testing purpose, I only published the project manually from Visual Studio Publish. Seems I cannot specify the exact preview version to use as well. Also my new machine only has .net 8 preview 7, not sure where the bad dotnet.js.br came from.

**Comment by MackinnonBuck** [comment]
@jjzhang12 Could you please generate a binlog for a publish that produces a faulty app? Instructions on how to do that can be found [here](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md). That will help us investigate this further. For security reasons, please submit a ticket using the "Send Feedback" button in Visual Studio and include the binlog there, rather than uploading it to this issue.

**Comment by MackinnonBuck** [comment]
And if you do that, would you please also link the feedback ticket in this chat? Thanks.

**Comment by jjzhang12** [comment]
@MackinnonBuck Here is the ticket: https://developercommunity.visualstudio.com/t/VS-2022-178-preview1:-Publish-Blazor-ap/10438850

**Comment by maraf** [comment]
@jjzhang12 Thank you for the logs! 

The brotli compression (because it is more computational expensive) runs only on `publish`. The logs that you shared are for `build`. Anyway the output structure (both `bin` and `obj`) contained brotli compressed files. It seems the output folder is combination of build and publish (I found that your project has custom `OutputPath`, but I don't have information about how/where do you publish it). Do you have a publish profile that outputs to the same folder as build? Or do you run publish any other way that outputs to the same folder?

The issue should disappear when you delete `bin` and `obj` folders (manually).

Also note that `clean` doesn't remove files produced by `publish`.

**Comment by jjzhang12** [comment]
@maraf: Thanks for the help, after deleting all the bin and obj folders for all projects, I cannot reproduce the issue now. We can close the issue.
Anyway, my publish folder was set to "Publish" under customized output folder. That's selected by Visual Studio by default.
Previous I used to Clean the solution from Visual Studio, and also removed the customized output folder and the publish folder. But that seems not "clean" enough.
