### ISSUE TITLE
[Mono] Consider switching to C11

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#90404]
Currently Mono is supposed to use C99. As a result, we're relying on platform or compiler intrinsics for some functionality that has been added to the standard since then such as `stdatomic.h`.

We should consider upgrading Mono to a more recent language standard.

This came up as part of #88279, for example.

Some concrete things we could take advantage of:

* `stdatomic.h` for atomic reads/writes, CAS, etc
* `_Alignas`
* static assertions
* `_Noreturn`
* possibly thread locals (although the JIT likes to take advantage of understanding TLS layout, so we need to ensure we don't take a perf hit)

Some reasons we might not want to do it:
* Anecdotally, I've heard that MSVC C11 support has some issues - we will need to understand the specific pitfalls to avoid so we don't break `mono-aot-cross` running on Win32 and also Mono on non-Windows Win32 platforms

**Comment by lambdageek** [comment]
cc @vargaz @AaronRobinsonMSFT @lateralusX @am11

**Comment by MichalPetryka** [comment]
> * I've heard that MSVC C11 support has some issues

MSVC doesn't support C11, only C17.

**Comment by AaronRobinsonMSFT** [comment]
> > * I've heard that MSVC C11 support has some issues
> 
> MSVC doesn't support C11, only C17.

Yes it does - https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/. There is no support for optional features and there are bugs around atomics, but it has support.

**Comment by am11** [comment]
In libraries, we are using C11 for couple of years:

https://github.com/dotnet/runtime/blob/376e2353e4a06bd79639cad4ea83fd9001e62883/eng/native/configurecompiler.cmake#L10-L11
and e.g. its 'Generic Selection' feature.: https://github.com/dotnet/runtime/blob/376e2353e4a06bd79639cad4ea83fd9001e62883/src/native/libs/System.Native/pal_process.c#L559

VCR handles it just fine. Only these features are not supported: https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/#whats-not which we don't use in libs.

**Comment by AaronRobinsonMSFT** [comment]
The atomics in C11 is recent and experimental, announced at https://devblogs.microsoft.com/cppblog/c11-atomics-in-visual-studio-2022-version-17-5-preview-2/.

**Comment by barcharcraz** [comment]
Hi, I'm on the C++ libraries team and I'm the one who wrote the library support for c11 atomics and threads. We actually thought of providing gcc style atomic intrinsics that could work in c99 mode, but because of how our C++ atomics are designed MSVC really, really needs that new `_Atomic` keyword.

C11 threads will probably work fine in C99 mode, with the possible exception of the new `_Thread_local/thread_local` keyword. The TLS layout for implicit TLS is the same as `__declspec(thread)` or c++ `thread_local`. For the `tss_*` family of functions the implementation is new, and not shared with the `Tls*` or `Fls*` functions, because `tss_*` needs to support destructors with slightly different semantics than fls. The layout used here is very basic, with an array for global data and a per-thread array for per-thread data that's allocated when you use a relevant function for the first time on a particular thread.

All the C11 threads stuff is new, and distinct from C++ threads. The ABI is also somewhat better protected than for C++ threads, so layouts and implementation are subject to change (in ABI compatible ways).

**Comment by barcharcraz** [comment]
oh, I should say that C11 threads is just implemented in terms of windows threading functions (`CreateThread` and friends), and its threads are "normal" threads and don't have any extra state or anything. They do briefly allocate some memory in order to thunk between cdecl and stdcall, but that's it.

Note that this does mean `thrd_t` thread handles work a little differently for our C11 threads than they tend to in pthreads based implementations. In particular you can't detach yourself by writing `thrd_detach(thrd_current())`.

**Comment by tgani-msft** [comment]
> The atomics in C11 is recent and experimental, announced at https://devblogs.microsoft.com/cppblog/c11-atomics-in-visual-studio-2022-version-17-5-preview-2/.

It's currently being actively worked on (both front-end and back-end teams) - we can talk about .NET taking a dependency on this support in our sync meetings.

**Comment by lambdageek** [comment]
Thinking about `_Atomic` a little bit more, I think once we bump to C11, the guidance in Mono will be not to use `_Atomic(T)` or the `_Atomic` qualifier.  There's no good compile-time way to know if that will be lockfree (sadly `static_assert (atomic_is_lock_free (&someAtomicStruct))` cannot work).  In general we cannot use locks inside Mono (in the runtime itself, I mean - pinvokes are fine) without making the coop GC thread state machine aware of them - otherwise we will deadlock if two threads try to take the lock at the same time that a GC is started

https://github.com/dotnet/runtime/blob/cd4a25371c721f83be3fa3367be6cb143709dadc/src/mono/mono/utils/checked-build.c#L207-L221

So I think at best we will end up redefining `mono_atomic_cas_TYPE`, `mono_atomic_compare_exchange_TYPE`, etc in terms of the C11 atomic ops (and adding something along the lines of `static_assert ((sizeof(int32_t) == sizeof(atomic_int) && ATOMIC_INT_LOCK_FREE == 2) || (sizeof(int64_t) == sizeof(atomic_llong) && ATOMIC_LLONG_LOCK_FREE == 2))` somewhere in our headers)

**Comment by lambdageek** [comment]
This initial work has been completed.

Mono now requires a C11 compiler - and we use `static_assert` in some places.

Some platforms now opt into using C11 atomics for the `mono_atomic_XYZ` functions.

We are not using c11 atomics for MSVC builds yet, but we could switching. Created #91748 for follow-up work.

We are using "strong" not "weak" atomics.  Created #91747 for follow-up work.

**Comment by lambdageek** [comment]
We're reverting the atomics PR because of some build failures https://github.com/dotnet/runtime/pull/91812

A proper fix is in progress in https://github.com/dotnet/runtime/pull/91808 but it's failing due to some weird clang problem on our linux-arm64 crossrootfs

**Comment by lewing** [comment]
@lambdageek what is the status of this?

**Comment by lambdageek** [comment]
We're done. #91808 was good.
