### ISSUE TITLE
Receive 0x80070057 from load_assembly_and_get_function_pointer call when self hosting .NET 6.

### ISSUE THREAD

**Issue by NightWulfe** [dotnet/runtime#90525]
I am attempting to self host .NET6 in a native executable (C++). Everything seems to load properly, but it fails when trying to get the function pointer for the delegate. The call fails with error code 0x80070057. 

I understand that this indicates that it can't find the specified type, but I have verified the type names and paths numerous times and Object Browser shows the types I expect to see.

I'm sorry if this is something stupid that I am overlooking, but I cannot for the life of me figure out why I am getting this error code.

Source files are attached: [net6_host.zip](https://github.com/dotnet/runtime/files/12337321/net6_host.zip)

1. To run the project, extract the files and then open the directory in Visual Studio 2022.
2. Switch to the CMake Targets view and set "net6" as the startup project
3. Replace "D:\\Prototypes\\" with the root directory to which you extracted the files on lines 28 and 29 of `src/main.cpp`.
4. Ensure the .NET 6.0 paths to nethost/hostfxr are correct in `src/plugins/CMakeLists.txt`
5. Put a break point on line 77 of `src/main.cpp`
6. Debug the application by pressing F5

You should hit the breakpoint. Stepping over will result in `rc` being set to 0x80070057. However, as you can see from the `src/plugin/plugin.cs` file, and the output `plugin.dll`, the type names are correct (`net6.Plugin, plugin` for assembly `plugin`, namespace `net6`, class `Plugin`).

Any help will be greatly appreciated.

Thank you,
- Josh

**Comment by vitek-karas** [comment]
The problem is that the `load_assembly_and_get_function_pointer` needs to know the delegate type. You pass in nulls for both, which means it will default to the `public delegate int ComponentEntryPoint(IntPtr args, int sizeBytes)` - your method `Bootstrap` doesn't match that delegate (it returns `void` instead of `int`).

Alternatively you can mark the method with `UnmanagedCallersOnly` (which you did), in which case you need to pass in a special delegate type name `(const char_t*)-1` which will tell the runtime to use this other mechanism (umanaged callers only).

Unfortunately we don't have a good public doc about this yet, so the only one is here: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#loading-and-calling-managed-components
See the ".NET 5 and above" note in the `delegate_type_name` section.

(Note that I didn't try to fix your code and run it, so maybe there are other issues as well - but this is the one which seems the most obvious problem).

**Comment by NightWulfe** [comment]
Oh my God I can't believe I missed that. I am sorry for wasting your time.

Thank you so much. It's working, now.
