### ISSUE TITLE
Implement standalone GC loading in NativeAOT

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#90676]
This will allow us to do perf experiments for NativeAOT under various GC tweaks easier.

**Comment by jkotas** [comment]
This would degrade security characteristics of native AOT that are important for some customers. There is no way to inject extra .dlls into native AOT process by setting environment variables today. This would introduce one.

**Comment by cshung** [comment]
Maybe we can do that optionally? Like using a #define or having an optional lib during link?

**Comment by AustinWise** [comment]
It looks like standalone loading of the GC was implemented in #91038.

There is one problem I noticed: GC events don't show up in `dotnet trace` when standalone GC is enabled. I think it's because of this function:

https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/gcheaputilities.cpp#L90-L94

Currently it always calls `GCEventStatus::Set` on the GC linked into the executable. It should instead call the methods on the `g_pGCHeap` object.

Note that the CoreCLR version of this function has some synchronization. The event pipe command to start tracing could happen before the GC is fully loaded:

https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/gcheaputilities.cpp#L360-L370
