### ISSUE TITLE
Generated docs xml files do not contain the newest APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#90738]
We found this issue while attempting to port new documentation for System.Security and System.Text.Json to dotnet-api-docs. Probably affecting many other areas too.

The xml files under `artifacts/bin/<AssemblyName>/Debug/net8.0/<AssemblyName>.xml` are not adding documentation for some of the newest APIs.

For example, we cannot find:

- SHA3_256 in System.Security.Cryptogtaphy.xml
- JsonUnmappedMemberHandling in System.Text.Json.xml

@ViktorHofer 

Cc @vcsjones @eiriktsarpalis thanks for reporting this.

**Comment by ViktorHofer** [comment]
That's because we swap the compiler generated documentation file with the one from the intellisense package when the library's source of truth isn't dotnet/runtime: https://github.com/dotnet/runtime/blob/45acd380b37c9ee883070a70a2ef2cb7eca77683/eng/intellisense.targets#L41-L48

Sounds like you don't want this to happen when porting documentation to dotnet-api-docs. Consider adding another property to the condition to skip the target.

**Comment by carlossanlop** [comment]
Ok I understand now. The latest intellisense transport file is from 7.0.

I thought we were still swapping the files in the docs folder, not directly in the artifacts.

I'll adjust my documentation instructions so that folks use the obj folder. We can close this.
