### ISSUE TITLE
Trimmed InlineArrayAttribute breaks Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#90745]
### Description

When enabling trimming and using `Microsoft.Extensions.DependencyInjection` directly or indirectly (e.g. through `M.E.Logging`), execution fails when service accessors are created.

### Reproduction Steps

Create a piece of code that uses `M.E.DependencyInjection`, such as this one:

```csharp
Microsoft.Extensions.Logging.LoggerFactory.Create(b =>{});
```

and enable the trimming for all types.

### Expected behavior

Execution completes.

### Actual behavior

```
System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, collection
dotnet.native.js:8    at System.Collections.Generic.List`1[[Microsoft.Extensions.Options.IConfigureOptions`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]..ctor(IEnumerable`1 collection)
dotnet.native.js:8    at Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]..ctor(IEnumerable`1 setups, IEnumerable`1 postConfigures, IEnumerable`1 validations)
dotnet.native.js:8    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
dotnet.native.js:8    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
dotnet.native.js:8    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
dotnet.native.js:8    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
dotnet.native.js:8    at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
dotnet.native.js:8    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[ILoggerFactory](IServiceProvider provider)
dotnet.native.js:8    at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
```

### Regression?

yes

### Known Workarounds

Add the following to linker directives:

```xml
<assembly fullname="System.Private.CoreLib">
   <type fullname="System.Runtime.CompilerServices.InlineArrayAttribute" />
</assembly>
```

### Configuration

6d0e3e59dd2f96eb9ca5c5397ff2a9d7c5526cac, using WebAssembly, but likely to repro on any other linker compatible target.

**Comment by jkotas** [comment]
Does ILLink have a list of attributes recognized by the runtime that should not be trimmed?

**Comment by jeromelaban** [comment]
There are files [like this one](https://github.com/dotnet/runtime/blob/7bc69ad2639a98e5940e4061edd8aacfae50128f/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Descriptors.LibraryBuild.xml#L1), so I guess that this particular attribute could make its way there.

**Comment by jkotas** [comment]
The existing attributes recognized by the runtime are hardcoded here: https://github.com/dotnet/runtime/blob/7bc69ad2639a98e5940e4061edd8aacfae50128f/src/tools/illink/src/linker/Linker.Steps/MarkStep.cs#L1154-L1167 . I think `InlineArrayAttribute` should be added to this list.

Number of other attributes recognized by the runtime seems to be missing in this list. The list of attributes recognized by the runtime is in https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/wellknownattributes.h . Should all of these attributes be hardcoded in the linker? (It should be ok to omit attributes for scenarios like COM interop that are not trim compatible by design.)

**Comment by agocke** [comment]
@sbomer Is attribute trimming turned on by default? Or is this a Blazor-specific setting?

We can certainly add the attribute to that list, but I'm trying to figure out the scope of the problem.

**Comment by Youssef1313** [comment]
I think Uno has the setting turned on. It's probably not turned on by default.

**Comment by agocke** [comment]
OK, one other option I can think of: a "runtime intrinsic" attribute, or abstract attribute. We would either apply the attribute to various attribute definitions, or have other attributes inherit from the "runtime intrinsic" attribute.

The linker would check if this attribute is present, and always preserve if true.

**Comment by jeromelaban** [comment]
> Yup, just that this issue is the classic case of, "something happens in one place and it breaks if another place isn't changed as well."

@agocke that's fair! For what I can tell for what our modest canaries, excluding the attribute unconditionally is good enough to get going.

**Comment by jkotas** [comment]
> a "runtime intrinsic" attribute, apply the attribute to various attribute definitions

This option sounds reasonable to me. We can assert in the debug builds of the runtime that the annotations are correct.

> The linker would check if this attribute is present, and always preserve if true

Nit: It needs to preserve it only if it is actually used.

**Comment by vitek-karas** [comment]
I'm a bit lost in this. Linker should not remove any attributes by default - there is a hidden feature which would do that, but it's not enabled and is VERY experimental (and we don't really maintain it anymore). If this issue is about the fact that turning on this hidden feature breaks things... it's basically by design. There would need to be other work on top of the "keep these at all times" list - it's basically a new feature work.

There is a hardcoded list of attributes which are OK to be removed and there's an XML file which directs linker to do that. That list is different for some targets (Blazor removes more attributes than normal console apps for example). If that list contains this attribute, than that would be a bug.
https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L6
https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.Shared.xml#L188
https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/coreclr/nativeaot/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L6

**Comment by agocke** [comment]
I think Blazor turns this on by default :(.

I'll file an issue for long-term fixing. For 8.0 we can probably just add InlineAttribute to the list.

@AaronRobinsonMSFT mentioned that a more robust long-term solution would be to create an enum or list of attributes in corelib that both the runtime and the linker can check. This would also ensure that a linker of a different version could analyze a different corelib version safely. That's not really supported, but it's a nice property.

**Comment by jkotas** [comment]
> a more robust long-term solution would be to create an enum or list of attributes in corelib that both the runtime and the linker can check.

It sounds complicated build-system wise. The "runtime intrinsic" attribute suggested in https://github.com/dotnet/runtime/issues/90745#issuecomment-1682764113 that gets applied to affected attributes should be a lot simpler, less magical solution.

**Comment by AaronRobinsonMSFT** [comment]
> It sounds complicated build-system wise.

I could be missing context here, but the issue is around attributes that the runtime absolutely needs right? If so, then we could define that list in SPCL and that would then be retrievable by the both the runtime itself and the trimmer when it does trimming.

Adding a new "runtime intrinsic" attribute seems a bit more magic because there is nothing to validate they are all set, the explicit list is clear about what is needed and SPCL can be descriptive of its needs.

If I am misunderstanding this issue and the build system does need to be involved somehow, then yes the attribute sounds good.

**Comment by jkotas** [comment]
The current list of these attributes recognized by the runtime is in https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/wellknownattributes.h. It is not that many attributes and it is not changing frequently. I think it would be simplest to duplicate annotations as attributes than to invent custom encodings of the list.

The problem is that the issue is not actually limited to the attributes recognized by the runtime. Managed code out there can look for arbitrary attributes by name as well and the linker is not able to reason about it. As Vitek pointed out in https://github.com/dotnet/runtime/issues/90745#issuecomment-1683003039, the attribute stripping is very experimental feature, it does not work well, and it is not enabled in any workloads supported by .NET team.

**Comment by jkotas** [comment]
> If this issue is about the fact that turning on this hidden feature breaks things... it's basically by design

I agree.

As a follow up, we may want to delete it so that it does not cause confusion.

**Comment by MichalStrehovsky** [comment]
There was a long discussion on `--used-attrs-only` at https://github.com/dotnet/linker/issues/952#issuecomment-591975814. It's a fragile list of attributes to keep track of. Their behaviors can be subtle, up to and including causing MSRC-level (security) issues (e.g. stripping attributes that affect DLL path resolution or generation of stack cookies).

We introduced the ability to list attributes that are "_safe_" to remove and trim those since the linked discussion happened. I think the savings will be very small compared to this new option.

I think we should just delete `--used-attrs-only` from the product so that people don't use this and file (potentially MSRC-level) bugs on this.

**Comment by MichalStrehovsky** [comment]
> That being said, I'd still find interesting to be able to explicitly remove attributes (such as the nullable ones), but that's probably a comment for the other thread.

The nullable attributes are currently removed by setting the `NullabilityInfoContextSupport` MSBuild property (#88805 is a discussion about making that property publicly documented - it's currently used by the Blazor SDK only).

**Comment by vitek-karas** [comment]
> I'd still find interesting to be able to explicitly remove attributes (such as the nullable ones), but that's probably a comment for the other thread.

That ability exists, although we don't document it too publicly (it's dangerous and easy to get wrong). We use it to remove some attributes which are known to not be useful at runtime: https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L6
You can construct a similar XML file and pass it to the linker via `--link-attributes`. Just please be very careful :-)

**Comment by vitek-karas** [comment]
I created https://github.com/dotnet/runtime/issues/90793 to discuss and potentially implement removal of the feature.

@jeromelaban - does this answer the issue?

**Comment by jeromelaban** [comment]
> The nullable attributes are currently removed by setting the `NullabilityInfoContextSupport` MSBuild property (#88805 is a discussion about making that property publicly documented - it's currently used by the Blazor SDK only).

That's going to be useful! Thanks!

> You can construct a similar XML file and pass it to the linker via `--link-attributes`. Just please be very careful :-)

Noted! Thanks for the warning.

> @jeromelaban - does this answer the issue?

It does! Thanks for the help!

**Comment by agocke** [comment]
Well, given that this is an unsupported flag, I'm fine tabling this for the moment. We can decide if we want to even support this flag in .NET 9.
