### ISSUE TITLE
[API Proposal]: Modify static abstract interfaces for functions

### ISSUE THREAD

**Issue by RVShershnev** [dotnet/runtime#90744]
### Background and motivation

I try create math library for fuzzy numbers.

Fuzzy numbers are a type of mathematical concept that allows for values to be expressed in a range rather than a single point.
They are used to represent uncertain or imprecise data, where there is some degree of ambiguity or variability in the measurement. Fuzzy numbers are typically defined by a membership function that assigns a degree of membership to each value within the range. This allows for more flexible and nuanced analysis of data, particularly in situations where traditional numerical methods may not be appropriate or effective.

### API Proposal

1) Add interface for IAbsFunctions<TSelf, TResult> as `Math.Abs(...)`.
2) Change interface [IPowerFunctions<TSelf>](https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.ipowerfunctions-1) to `IPowerFunctions<TSelf, TPower, TResult>`. 
3) Change interface [IExponentialFunctions<TSelf>](https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.iexponentialfunctions-1) to `IExponentialFunctions<TSelf, TResult>` 
4) Change interface [IRootFunctions<TSelf>](https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.irootfunctions-1) to `IRootFunctions<TSelf, TResult>`
5) Change interface [ILogarithmicFunctions<TSelf>](https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.ilogarithmicfunctions-1) to `ILogarithmicFunctions<TSelf, TBase, TResult>`
6) Change interface [ITrigonometricFunctions<TSelf>](https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.itrigonometricfunctions-1) to `ITrigonometricFunctions<TSelf, TResult>`

### API Usage

```csharp
public readonly partial struct Triangular  :  IPowerFunctions<Triangular, double, Triangular>
{
    public static Triangular Pow(Triangular number, double power)
} 
```

**Comment by tannergooding** [comment]
> Change interface [IPowerFunctions](https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.ipowerfunctions-1) to IPowerFunctions<TSelf, TPower, TResult>.
Change interface [IExponentialFunctions](https://learn.microsoft.com/dotnet/api/system.numerics.iexponentialfunctions-1) to IExponentialFunctions<TSelf, TResult>
Change interface [IRootFunctions](https://learn.microsoft.com/dotnet/api/system.numerics.irootfunctions-1) to IRootFunctions<TSelf, TResult>
Change interface [ILogarithmicFunctions](https://learn.microsoft.com/dotnet/api/system.numerics.ilogarithmicfunctions-1) to ILogarithmicFunctions<TSelf, TBase, TResult>
Change interface [ITrigonometricFunctions](https://learn.microsoft.com/dotnet/api/system.numerics.itrigonometricfunctions-1) to ITrigonometricFunctions<TSelf, TResult>

None of these are possible, they are breaking-changes.

> Add interface for IAbsFunctions<TSelf, TResult> as Math.Abs(...).

`Abs` is already provided on `INumberBase`, which `IAbsFunctions` would be required to implement so that the interface can be versioned over time.

-------------------

In general, `INumber<T>` and related interfaces are designed to work over "scalar" values, typically where you have `T-in, T-out` (as otherwise you run into overload resolution and conversion problems).

Higher level concepts dealing with non-scalar values or mixed-types would require their own interface. The same would be true for proper support of say `Complex` where you have both an imaginary and a real part; and where frequently overloads are provided (typically for performance) that allow `Complex op Real`. Thus in such a scenario we'd define `interface IComplex<TSelf, T> where TSelf : IComplex<TSelf, T> where T : INumber<T>` (or similar).

This seems along the same avenue where you would want to define a new `IFuzzyNumber` interface that extends the baseline functionality with the new support you desire.

**Comment by RVShershnev** [comment]
@tannergooding Thank you for advice.

My way of defining fuzzy numbers is similar to complex ones. I'll think about it.

Could you recommend me some thematic chat on generic math C#?
