### ISSUE TITLE
`CA2229` conflicts with the new `SYSLIB0051`

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/runtime#90783]
### Analyzer

**Diagnostic ID**: [CA2229](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA2229): `Implement serialization constructors`

### Analyzer source

**Version**: 8.0 preview 6

### Describe the bug

In .NET 8, obsoletion warning [SYSLIB0051](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0051) was introduced which added a warning to any type using Exception's .ctor(SerializationInfo, StreamingContext)

However, not implementing this .ctor lights up CA2229.

### Steps To Reproduce
```csharp
public class M : Exception // CA2229: Add a constructor to M with the following signature: 'protected M(SerializationInfo info, StreamingContext context)'.
{
   public M(string? message) : base(message) { }

   public M(string? message, Exception innerException) : base(message, innerException) { }

//   protected M(SerializationInfo info, StreamingContext context) : base(info, context) { }

   public M() { }
}
```

### Expected behavior

Given the long term [obsoletion strategy of binary serialization](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), this analyzer should probably be sunset, or perhaps only apply to .NET <8.

### Actual behavior

Either `CA2229` or `SYSLIB0051` are triggered, depending on whether the commented code above is un-commented.

**Comment by mavasani** [comment]
> Given the long term [obsoletion strategy of binary serialization](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), this analyzer should probably be sunset, or perhaps only apply to .NET <8.

Moving to runtime repo to get this triaged.

**Comment by mavasani** [comment]
FYI @buyaa-n

**Comment by danmoseley** [comment]
Xx @GrabYourPitchforks

**Comment by buyaa-n** [comment]
> Given the long term [obsoletion strategy of binary serialization](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), this analyzer should probably be sunset, or perhaps only apply to .NET <8.

Removing the analyzer sounds good to me, what you think @GrabYourPitchforks, and probably need to ported to 8.0 CC @jeffhandley

**Comment by jeffhandley** [comment]
Since `CA2229` indicates the following, I'm uncertain we can just delete the rule without potentially causing harm to folks.

> Do not suppress a violation of the rule. The type will not be deserializable, and will not function in many scenarios.

I presume we'd also need to reconsider [CA2237: Mark ISerializable types with SerializableAttribute](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2237) and [CA2235: Mark all non-serializable fields](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2235) as well.

What do you recommend, @GrabYourPitchforks?

Thanks a bunch for reporting this, @RenderMichael!!

**Comment by RenderMichael** [comment]
> Thanks a bunch for reporting this, @RenderMichael!!

Always glad! This issue would come up for every user with `CA2229` enabled and a user-defined exception, so hopefully this can be resolved before .NET 8 ships

**Comment by GrabYourPitchforks** [comment]
CA2235 strikes me as still useful. If you've slapped `[Serializable]` on a type but introduced members which are not serializable, then you've probably made a mistake. The ways to correct this are: (a) remove `[Serializable]`; or (b) change each of the fields to be a serializable type; or (c) customize the serialization logic via implementing `ISerializable`.

CA2237 should probably be changed to say that if you have implemented the `ISerializable` interface _directly_, you should also annotate yourself as `[Serializable]`. That is, the rule should not fire if the interface is introduced not at your layer, but rather at a layer somewhere else in your type hierarchy. That way you could still subclass `ISerializable` types and not have to worry about implementing serialization logic yourself.

**Comment by RenderMichael** [comment]
The analyzer severity could be tied to the [feature switch for binary serialization](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#allow-disabling-binaryformatter-via-an-opt-in-feature-switch-net-5)

Ultimately, this does not need a detailed analysis because types like `ISerializable` and `[Serializable]` are [being obsoleted in .NET 9](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#remainder-of-legacy-serialization-infrastructure-obsoleted-net-9).

**Comment by buyaa-n** [comment]
> Since CA2229 indicates the following, I'm uncertain we can just delete the rule without potentially causing harm to folks.
> 
> > Do not suppress a violation of the rule. The type will not be deserializable, and will not function in many scenarios.

That warning probably only matter for to .Net framework users + .Net core users that turned on the switch for binary serialization, it seems Net framework users could use the [NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers#versions-body-tab) from nuget, in that case I guess they would still want to the diagnostics, correct me if I am wrong @mavasani @stephentoub.


> The analyzer severity could be tied to the [feature switch for binary serialization](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#allow-disabling-binaryformatter-via-an-opt-in-feature-switch-net-5)

Interesting, but not sure if we could check within analyzer if a user turned on a feature switch at compile time CC @mavasani  


> > I presume we'd also need to reconsider [CA2237: Mark ISerializable types with SerializableAttribute](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2237) and [CA2235: Mark all non-serializable fields](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2235) as well.
> 
> CA2235 strikes me as still useful. If you've slapped [Serializable] on a type but introduced members which are not serializable, then you've probably made a mistake. The ways to correct this are: (a) remove [Serializable]; or (b) change each of the fields to be a serializable type; or (c) customize the serialization logic via implementing ISerializable.
> 
> CA2237 should probably be changed to say that if you have implemented the ISerializable interface directly, you should also annotate yourself as [Serializable].

Looks CA2235 doesn't work properly on .NET Core/netstandard (because the [Serializable] attribute not included in reference assemblies), therefore CA2235 is [bail out on .NET Core/netstandard](https://github.com/dotnet/roslyn-analyzers/issues/1775#issuecomment-519981159). Both analyzers CA2235 and CA2237 are [disabled by default and marked as candidate for removal](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SerializationRulesDiagnosticAnalyzer.cs#L66). 

Is that would change your suggestion @GrabYourPitchforks?

**Comment by buyaa-n** [comment]
Solution update:

- For CA2229, we are going to remove it as suggested from our experts, as `We have been fine to delete other security and serialization analyzers that are no longer valid on modern .net versions. We can always ask users to stay on older versions of NuGet package if they really care so much about such deleted rules`

- For CA2235 and CA2237 as they have already disabled by default and marked as candidate for removal leaving them as is, they could be reviewed/handled with [Review CandidateForRemovals rules and remove in .NET 9](https://github.com/dotnet/roslyn-analyzers/issues/6349) later

Please let me know if you have other thoughts.
