### ISSUE TITLE
Remove support for `--used-attrs-only` in illink

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#90793]
That feature has always been more or less experimental, and with each recent release of .NET it got worse and worse. Currently it's effectively unusable as it breaks to many things in core runtime (let alone some libraries). There is no official scenario which uses the feature currently.

https://github.com/dotnet/linker/issues/952 has a long discussion of the problems and the potential size savings.
https://github.com/dotnet/runtime/issues/90745 contains another discussion on the topic and shows how it can break functionality of apps.

This issue not meant to decide if we will ever support automatic attribute trimming, just that the current implementation of it is very problematic and we don't have any immediate plans to fix it.

@mrvoorhe @sbomer @agocke @MichalStrehovsky

**Comment by vitek-karas** [comment]
If we decide to do this, now would be a good time as it's very early in .NET 9 and it would give us plenty of time to react to potential problems.

My main concern is impact on Unity - @mrvoorhe what do you think?
We could remove just the command line option, and keep the implementation, but then testing it would be problematic (not that we have many tests for it). Ideally, we would remove it completely.

**Comment by mrvoorhe** [comment]
@vitek-karas I did some research and here is what I learned.

First some context.
* We don't really have the information necessary to determine how important this is to real projects for a variety of reasons.
* We are not far enough along with our coreclr work to get size numbers for projects built against coreclr. 
* The size numbers I could get are based on mono bcl & sample projects.

What I found from mono bcl and sample projects is that turning off --used-attrs-only increases total (metadata + code) player size by less than 1mb.  On the projects I had this seemed relatively fixed.  A 460mb project saw a 0.5mb increase by turning off --used-attrs-only.  While a 121mb project saw a 0.6mb increase.  I suspect this number could vary considerably by project, however, even if it were to increase by 2 or 3 times for a project it would still be a small percentage of the total player size.

Next I looked at the impact of used-attrs-only compared to other size savings optimizations to help get an idea of where this falls in the bigger picture.

Here are the things I looked at.  Ordered from largest impact to least.
1) Engine Module Stripping - This is Unity specific.  Impact could vary but in this case it was 11mb.
2) Changing the Managed Stripping Level from Minimal to Medium - This is essentially going from trimming only core libraries to trimming all assemblies.  Impact was 7.5mb
3) Our method body modification during High Managed stripping level.  This is where we do borderline dangerous stuff to the class libraries.  Inline property getters, etc.  Although, I suspect a large chunk comes from ripping out Microsoft.Win32.Registry ( I was testing iOS build).  Impact is in the relm of 3-4mb.
4) --used-attrs-only.  Impact of 0.4 to 0.6 mb.
5) CodeOptimizations.BeforeFieldInit.  Came in barely behind --used-attrs-only
6) CodeOptimizations.UnusedInterfaces.  About half the impact of (4) and (5)
7) CodeOptimizations.UnreachableBodies.  Just behind `UnusedInterfaces`.
8) CodeOptimizations.OverrideRemoval.  About half the impact of (6) and (7)

My takes aways from that are

* In the grand scheme of things, we can live without --used-attrs-only
* At the same time, --used-attrs-only is either the #1 or #2 size saving optimization that illink has.  It's a shame to give up on it.  Personally, it feels like a process challenge rather than some sort of complex technical challenge.

I think what I'd like to ask is that the tests and code paths to support --used-attrs-only be left in place for the time being.  Maybe just remove the help details about the option?  It would be nice if we could have the ability to re-evaluate again when we are up and running with coreclr and can get data on coreclr.  The logic to supported --used-attrs-only required a bit of a paradigm shift to the MarkStep.  If the code were removed, it would not be practical to add it back into UnityLinker.

To clarify a bit on "time being".  At least not removing it from net8 would be helpful.  If it were removed from net9 but before we can test with coreclr on our end, that's not ideal as it's probably a death sentence, but it would be better than removing it from net8.

Thanks for checking with us!

**Comment by vitek-karas** [comment]
Thanks a lot for all this information. In that case I would be in favor of:
* Removing this from the docs and help
* Maybe renaming the command line option, so that we intentionally break anybody using it (and get them to not use it). Unity would adapt the new name if it needs it.
* Keep the code in the product and the existing tests, but don't invest in any improvements in this area.

Re
> Personally, it feels like a process challenge rather than some sort of complex technical challenge

The fully correct solution is as much a technical challenge as anything else. There is a need to not remove a set of attributes recognized by the runtime, which is a process challenge. But there are still patterns which are trim incompatible and can't be safely analyzed right now. We do see lot of attribute usage where the attribute type is never referenced directly (outside of the instantiation of the attribute), the code works like:
* Scan all attributes on a given member
* Compare the type name of the attribute to a constant string - so the search is by name, not by type reference
* When found access the attribute's constructor parameters using the general (reflection-like) APIs - the attribute's instance is never casted to its actual type in the consumption code

Such patterns are really hard to analyze correctly - and the current optimization will break these.

**Comment by vitek-karas** [comment]
@sbomer, what do you think?

**Comment by mrvoorhe** [comment]
> Maybe renaming the command line option, so that we intentionally break anybody using it (and get them to not use it). Unity would adapt the new name if it needs it.

Good idea.  That would be fine.

> There is a need to not remove a set of attributes recognized by the runtime, which is a process challenge.
Yes.  Essentially all current and future attributes in the bcl need to be labeled as either needed by the runtime or not needed.  

> But there are still patterns which are trim incompatible and can't be safely analyzed right now. 

I think this is where Microsoft's and Unity's different views on code trimming start to show themselves.  My impression is that Microsoft strives for low risk of incorrect behavior.  That has been much needed and the reflection warnings have been a great addition.  An addition that Unity was not willing to invest in.  Unity's mindset is more, correctness by default, but if a user wants to aggressively push down size, we'll give you the ability to do so with the understanding that you may need to do some handholding or not do certain things, for example limit reflection.   That does have it's downsides.  We do introduce bugs where our own attributes are incorrectly stripped with `--used-attrs-only`.

> Such patterns are really hard to analyze correctly - and the current optimization will break these.

I agree.  And I don't know if I see a way to ever have `--used-attrs-only` enabled by default.  It does lead to problems even if all of the bcl attributes were handled correctly.  At the same time, there are users who can understand the behavior and care enough about shaving size off a small game that they are willing to annotate attributes that are needed at runtime.  We have https://docs.unity3d.com/ScriptReference/Scripting.RequireAttributeUsagesAttribute.html to help make annotating easier.

Thanks for keeping the code in the linker for the time being!

**Comment by vitek-karas** [comment]
> I think this is where Microsoft's and Unity's different views on code trimming start to show themselves. My impression is that Microsoft strives for low risk of incorrect behavior.

Absolutely agree - and it's not just Unity ;-) - for example Balzor and MAUI also opt-in to the same approach which Unity uses, maybe not as aggressive, but the same general principle.

The goal of the default trimming behavior (for console apps anyway) is to be "correct by construction". If trimming breaks the app, it's really difficult to diagnose the failure - even for us, let alone for external developers. This problem is exaggerated in NativeAOT where the runtime failures are often even more confusing. It also allows us to introduce improvements (size or performance...) without big fear of breaking something. We've ran into cases recently where correctness fixes (not anything to improve size) in the linker broke apps because they relied on the old behavior marking more things by accident.

**Comment by jkotas** [comment]
We do have unbaked unreliable options and switches in many places - AOT compilers, JIT, GC, ..., for our own experiments. We omit these from official documentation. People have to find them in the repo and use them at their own risk if they really want to.

> Maybe renaming the command line option

I do not think that this helps much in practice. All it takes somebody discovering the options (with a new name). mentioning it somewhere others are likely to copy&paste from, and you have a new cycle of the problem.

**Comment by vitek-karas** [comment]
Thanks a lot for your opinions. Makes sense.
The only other value for renaming would be to find out what does it break - but that's probably not worth the trouble.
