### ISSUE TITLE
[API Proposal]: Add additional overloads for `Random.Next*`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#90998]
### Background and motivation

It would be useful to be able to get a random value of other types than those currently supported on `Random`, such as `nint`.

### API Proposal

```diff
 namespace System;

 public partial class Random
 {
     public virtual int Next() { throw null; }
     public virtual int Next(int maxValue) { throw null; }
     public virtual int Next(int minValue, int maxValue) { throw null; }
     public virtual long NextInt64() { throw null; }
     public virtual long NextInt64(long maxValue) { throw null; }
     public virtual long NextInt64(long minValue, long maxValue) { throw null; }
+    public virtual Int128 NextInt128() { throw null; }
+    public virtual Int128 NextInt128(Int128 maxValue) { throw null; }
+    public virtual Int128 NextInt128(Int128 minValue, Int128 maxValue) { throw null; }
+    public virtual nint NextNInt() { throw null; }
+    public virtual nint NextNInt(nint maxValue) { throw null; }
+    public virtual nint NextNInt(nint minValue, nint maxValue) { throw null; }
     public virtual float NextSingle() { throw null; }
     public virtual double NextDouble() { throw null; }
+    public virtual Half NextHalf() { throw null; }
 }
```

### API Usage

```csharp
var value = Random.Shared.NextNInt();
```

cc @tannergooding

**Comment by koszeggy** [comment]
I prefer [extensions](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_CoreLibraries_RandomExtensions.htm) to introducing newer and newer virtual methods on `Random` because they can be a [pain](https://github.com/dotnet/runtime/issues/57272) for already existing derived classes (not mentioning when the fallback implementation isn't functionally [perfect](https://github.com/dotnet/runtime/issues/85016)). In an extension method you don't need to bother with any fallback `Next()`/`Sample()` calls just use the already available tool set, eg. `NextBytes(Span<byte>)` and one singe implementation.

Btw. I think #75431 covers this (where `Next<T>` is _not_ a virtual method).

**Comment by Neme12** [comment]
@koszeggy You could use the already available tool set in a virtual method as well. And even if the decision is to not make them virtual, why do they need to be extension method instead of regular methods?

Anyway, I like that proposal better so I'll close this one.

**Comment by Neme12** [comment]
Actually, that proposal has many problems and seems impossible to actually implement generically, so I'm reopening this.

**Comment by stephentoub** [comment]
> that proposal has many problems and seems impossible to actually implement generically

Care to elaborate?

**Comment by Neme12** [comment]
@stephentoub I posted a comment there right now.

**Comment by koszeggy** [comment]
> You could use the already available tool set in a virtual method as well.

It's not that simple. The `Random` class itself has three internal implementations for all virtual methods: a.) an optimized one for the newly added Xoshiro implementation, b.) a legacy one for seeded instances and c.) a default implementation for derived classes that don't override the virtual method. If a new virtual method is added the optimized implementation can do whatever it want but for the non-derived virtual implementation a fallback implementation (eg. using `Next()` calls) should be added as well.

In .NET Framework 1.x the non-derived virtual methods all used the protected `Sample()` method as a fallback but since 2.0 it's no longer the case: overriding `Sample` will not affect the result of `Next()`, `NextDouble()`, etc. so you have to override all of the methods to use your own custom implementation. A newly added virtual `NextInt128` method cannot assume that `NextInt64` is overridden, because that's also a fairly new method so in the fallback implementation you should stick to the original toolset such as `Next`, `NextDouble` or `NextBytes`. Of course, nothing stops you from using `NextInt64` also in that case but as it's likely not overridden either if your custom library wasn't updated recently, the deep chain of fallbacks will end up in a very bad performance.

On the other hand, for a non-virtual (or an extension) method you only need to add one implementation and it doesn't put a burden to library developers to update their implementations as soon as possible.

> And even if the decision is to not make them virtual, why do they need to be extension method instead of regular methods?

It's just a personal preference. There is nothing wrong with a nonvirtual method, but to me it communicates better that you don't need to think about the concerns above and that the extensions are safe to use by any `Random` implementation such as [`FastRandom`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_CoreLibraries_FastRandom.htm), [`SecureRandom`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Security_Cryptography_SecureRandom.htm), [`ThreadSafeRandom`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_CoreLibraries_ThreadSafeRandom.htm), etc.

Similarly, I wasn't quite [happy](#57276) to see the static `Shared` property in `Random` because it returns a fixed pseudorandom implementation but is available also from derived classes such as `SecureRandom`, which can cause confusion. I still think it would've been cleaner to put it into a new class but at least there is a planned [possible solution](https://github.com/dotnet/runtime/issues/57276#issuecomment-897946605) to fix this issue.
