### ISSUE TITLE
HttpResponseMessage

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#91036]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HttpResponseMessage/10409197)._

HttpResponseMessage Windows has a return value while Mac does not

Repro from (hidden) reply:

```c#
var loginurl = "/user/login/";
var loginOut = new LoginOut();
string json = JsonSerializer.Serialize<LoginModel>(login);
StringContent content = new StringContent(json, Encoding.UTF8, “application/json”);
HttpResponseMessage response = await _client. PostAsync(url + loginurl, content);

//maui Android
```

**Comment by tarekgh** [comment]
The link https://developercommunity.visualstudio.com/t/HttpResponseMessage/10409197 has more info.

**Comment by wfurt** [comment]
there are some confusing fragments - is this macOS issue or Android? We should get full tunable repro - it would be hard to triage otherwise.

**Comment by tarekgh** [comment]
@wfurt this is moved from the VS community portal. The author here is [vsfeedback](https://github.com/vsfeedback) which will never response. You may try to ping the author of this on [developercommunity.visualstudio.com/t/HttpResponseMessage/10409197](https://developercommunity.visualstudio.com/t/HttpResponseMessage/10409197) to get more info as needed.

**Comment by antonfirsov** [comment]
Accoring to the [reply](https://developercommunity.visualstudio.com/t/HttpResponseMessage/10409197#T-N10409482-N10409490) on the developercommunity ticket, here is the repro, and it is a "MAUI Android" problem:

```C#
var loginurl = "/user/login/";
var loginOut = new LoginOut();
string json = JsonSerializer.Serialize<LoginModel>(login);
StringContent content = new StringContent(json, Encoding.UTF8, “application/json”);
HttpResponseMessage response = await _client. PostAsync(url + loginurl, content);
```

This is still insufficient information: eg. what does it mean that "HttpResponseMessage has no return value on Mac"?

The developercommunity conversation is locked so we can not ask further questions there. @tarekgh according to your [resolution comment](https://developercommunity.visualstudio.com/t/HttpResponseMessage/10409197#T-N10448444), the author is informed to continue the conversation on GitHub, so they should provide further information here if it is still relevant for them. IMHO it's unlikely to happen since their latest activity is from the beginning of July. A problem with our developercommunity triage process is that by the time a question is routed to the right people to answer, it loses its' relevance and the user is gone.

**Comment by tarekgh** [comment]
@antonfirsov I have pinged the author on VS community ticket https://developercommunity.visualstudio.com/t/HttpResponseMessage/10409197#T-N10448444-N10449466. you can add reaction there with a comment even the issue is resolved there.

**Comment by karelz** [comment]
Triage: No response, closing.
