### ISSUE TITLE
Rfc2898DeriveBytes.Pbkdf2 is trimming unfriendly

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#91181]
In Npgsql we're using `Rfc2898DeriveBytes.Pbkdf2` for a sha256 hash. Unfortunately we're rooting all the other supported HashAlgorithms as a result. Any reason not to add Pbkdf2#Algo# methods to make things trimming friendly?

<img width="571" alt="Screenshot 2023-08-27 at 23 21 33" src="https://github.com/dotnet/runtime/assets/4218809/04119da1-6c7c-429e-a745-4c6f4c3ac840">

**Comment by vcsjones** [comment]
> Pbkdf2#Algo# 

Are you suggesting there be a Pbkdf2Sha256, Pbkdf2Sha384, etc?

Assuming so, there are currently 6 overloads. There are 7 hash algorithms supported by PBKDF2. Adding 42 APIs, documenting them, and testing them doesn't seem like it will scale, and there are many other APIs that accept a HashAlgorithmName. Why wouldn't we do it for Sign / Verify of asymmetric algorithms then?

Are there other ways to enlighten the trimmer?

**Comment by vcsjones** [comment]
The rooting is because of this, on Windows:

https://github.com/dotnet/runtime/blob/f5881e59f1e625b2f27d1553dc572c5e9b66dbe4/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/Pbkdf2Implementation.Windows.cs#L86-L109

When we do a key adjustment, we need to go to the primitives directly to pre-hash the HMAC key to the block size.

On Linux, (and probably macOS), where we don't have to do key adjustment, none of the HashAlgorithm instances are rooted because they go straight to P/Invoke:

<img width="810" alt="image" src="https://github.com/dotnet/runtime/assets/361677/24b62569-e0c5-42a6-b9e3-30487e6d3b59">

I suspect many APIs that accept a HashAlgorithmName are going to end up with all of the HashAlgorithm instances rooted because we need to resolve the HashAlgorithmName to "some hash implementation" at runtime.

For the purposes of understanding the "impact" on Windows, this trimming unfriendliness is about 5 kilobytes.

**Comment by NinoFloris** [comment]
It was at least double on linux (though I didn't do a diff)

**Comment by vcsjones** [comment]
> It was at least double on linux (though I didn't do a diff).

Using sizoscope for a Linux instance shows that there are _no_ HashAlgorithm instances rooted on Linux caused by Pbkdf2. If they are rooted on Linux, then something else is rooting them or something else is taking the space.

This is the entirety of S.S.Cryptography according to sizoscope:

<img width="823" alt="image" src="https://github.com/dotnet/runtime/assets/361677/53a0ceb2-db42-40a0-aa1b-5d3d19ae229a">


While the sizes reported may be underreported, in this case they are not reported at all.

This was the code I used to generate the report:

```C#
using System;
using System.Security.Cryptography;

System.Console.WriteLine(Convert.ToHexString(Rfc2898DeriveBytes.Pbkdf2(ReadOnlySpan<byte>.Empty, default, 1, HashAlgorithmName.SHA256, 32)));
```

**Comment by vcsjones** [comment]
I think what we need is a public API that does one-shot hashes that accept `HashAlgorithmName`. I suspect a good amount of hash algorithm instances are going to be rooted by this in common applications:

https://github.com/dotnet/runtime/blob/704beaa5b427fd5c47e537ff7c3deee7de28378c/src/libraries/Common/src/System/Security/Cryptography/HashOneShotHelpers.cs#L13-L27

The public one-shot API that accepts HashAlgorithmName can go straight to `HashProviderDispenser` and avoid rooting all of the HashAlgorithm types from switching over the name.

**Comment by NinoFloris** [comment]
> then something else is rooting them

Apologies, the other algorithms are rooted through this path. We use both Rfc2898DeriveBytes.Pbkdf2 @ SHA256 as we do HMACSHA256, it seems it's the latter that pulls in SHA3 and friends. I concluded too quickly based on a cursory look at the Rfc2898DeriveBytes code that it was responsible. 
<img width="1073" alt="Screenshot 2023-08-27 at 23 13 19" src="https://github.com/dotnet/runtime/assets/4218809/5a56ce2a-b91b-4f97-92fb-81dd142e23ca">

>The public one-shot API that accepts HashAlgorithmName can go straight to HashProviderDispenser and avoid rooting all of the HashAlgorithm types from switching over the name.

How would that help? Wouldn't that still require something of the trimmer that it doesn't do, namely trim control flow via value analysis? (Or do the dispenser codepaths not split things up similarly?)

**Comment by vcsjones** [comment]
@NinoFloris 

Yeah, you're basically hitting the key-adjustment problem again for `new HMACSHA256`. For .NET 7 you can change your [HMAC here](https://github.com/npgsql/npgsql/blob/274a1d174b44640d727f57751921541f335d6ffb/src/Npgsql/Internal/NpgsqlConnector.Auth.cs#L261-L265).

I would recommend using `HMACSHA256.HashData` for .NET 7+. That will avoid the HMACCommon which needs to do the key adjustment and won't root all of the hash types.

Aside: The usage of the `key` and `data` parameters seem backward in the API that I linked to . The data parameter is being used as the key and the key is being used as data.

**Comment by vcsjones** [comment]
Okay, I think I see a way forward to improving trimability here without additional API proposals.

**Comment by NinoFloris** [comment]
>Aside: The usage of the key and data parameters seem backward in the API that I linked to . The data parameter is being used as the key and the key is being used as data.

I noticed this too (I'm only a visitor in this area of the codebase) but it seems to be to comply with the order of operations a (postgres?) SASL client impl requires.
