### ISSUE TITLE
SmtpClient not sending QUIT on Dispose?

### ISSUE THREAD

**Issue by mguinness** [dotnet/runtime#912]
Per the documentation at [SmtpClient.Dispose](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.dispose?view=netcore-2.1) this method should send QUIT:

> Sends a QUIT message to the SMTP server, gracefully ends the TCP connection, and releases all resources used by the current instance of the SmtpClient class.

However when using in .NET Core, this does not appear to be the case.

In the .NET Reference Source, the underlying SmtpTransport class does this:
https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/mail/SmtpTransport.cs#L35-L58

In the .NET Core Libraries, the same code isn't present in SmtpTransport class:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs

Was there a reason this code wasn't ported over to .NET Core?

**Comment by scalablecory** [comment]
Not sending QUIT shouldn't be an issue if the socket is otherwise shutdown properly and the server is checking for recv()=0. I can vaguely see a less than robust server behaving unexpectedly when it doesn't receive one and is still processing messages, but we haven't really had reports of incompatibilities so far.

Given that this appears to be non-critical, and that I'd love to avoid spending I/O in a `Dispose()`, I agree that the most we should do is add a `Quit()` or `Shutdown()` method.

**Comment by mguinness** [comment]
This feels like groundhog day, it caused a lot of issues in .NET Framework 2.0 since [SmtpClient not sending QUIT](https://social.msdn.microsoft.com/Forums/vstudio/en-US/945d740b-5b43-406c-94bf-a6f1e619ea84/smtpclient-not-sending-quit) then eventually fixed in .NET Framework 4.0 and still exists in the [full framework](https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/mail/SmtpTransport.cs#L35-L58).

Why it still shows up in the documentation for .NET Core is beyond me as it's not correct and is misleading to say the least.

![image](https://user-images.githubusercontent.com/14002844/51948595-ee0bb500-23dd-11e9-8be1-57fce4a5ef8a.png)

At the end of the day if you aren't going to issue that command in `Dispose()` please remove that from documentation and please provide a `Disconnect()` or `Shutdown()` method so it can be sent manually.

**Comment by Tratcher** [comment]
> @Tratcher since you were involved in this issue around 10 years back, maybe you have some input?

I was. How did you know?

@scalablecory @tmds @davidsh I know the Dispose design might be a bit outdated, but it's still the best option here.
- Having .NET Framework compatible behavior is a high priority for existing API.
- SmtpClient.Dispose is included in netstandard and should have consistent behavior, library authors depend on this. Any new Shutdown API would not be available in netstandard.
- The Dispose design is the simplest to use correctly and benefits existing users without them having to change their code.
- It does result in IO, but not very much, it should almost never block. This has not been an issue in .NET Framework.

Being standards compliant here is important, especially since this has been a known source of issues in the wild over a long period. Please address this or allow someone else to do so.

**Comment by scalablecory** [comment]
@Tratcher I'm not strongly opposed if it's the right think to do, but I have yet to find an example of this causing an issue.

**Comment by Tratcher** [comment]
Here's the original issue and fix:
http://vstfdevdiv:8080/DevDiv/Dev10/_queries/edit/703015/?triage=true
http://vstfdevdiv:8080/DevDiv/Dev10/_versionControl/changeset/1202965

> Customer Scenario (including workaround):
Customer creates an SmtpClient object and uses it to send email to an Smtp server.  When the underlying Smtp connection times out, it will force-close the connection by sending a RST instead of gracefully closing it by sending a QUIT message as is required by RFC 2822.  A customer has no way to deterministically close any open connections; they will only be closed when they time out.  There is no workaround.

> Description of the Solution:
The solution is to implement IDisposable on SmtpClient so that a customer can deterministically free connections.  In addition, connections are now always closed by sending a QUIT message under all circumstances except when an Abort is called on an asychronous send.  In that case, the state of the connection is indeterminate and a RST must be sent instead to indicate that the send is being cancelled.

The missing QUIT wasn't the primary issue, the more fundamental issue was that the connections weren't being gracefully closed at all, they were timing out in the connection pool and causing RSTs. This can lead to socket exhaustion on the server. QUIT was added for RFC compliance as part of gracefully closing the connections.

Does Core have the same connection lifetime issue?

**Comment by scalablecory** [comment]
> Does Core have the same connection lifetime issue?

No. We do a `shutdown()`+`closesocket()` on `Dispose()`.

**Comment by Tratcher** [comment]
Oh good, that does make this a less severe issue. It also means you already have a non-abortive callstack where it would be appropriate to send the QUIT for RFC compliance so it would be a small fix.
https://github.com/dotnet/runtime/blob/9bf91f8d178e09bb81fb1749a82d588cbe8028cf/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs#L200

SmtpClient has a seperate Abort code path non-graceful disposes.

**Comment by davidsh** [comment]
>@scalablecory @tmds @davidsh I know the Dispose design might be a bit outdated, but it's still the best option here.
Being standards compliant here is important, especially since this has been a known source of issues in the wild over a long period. Please address this or allow someone else to do so.

@Tratcher Good summary of pros/cons of this issue. Based on this and the advantage of .NET Framework compat and netstandard compat, I'm fine with keeping the original design and doing the QUIT in the Dispose().

**Comment by MarcoRossignoli** [comment]
@davidsh to the fix of this issue, but have also shutdown/quit method could be useful for new users, if someone call shutdown/quit before dispose, dispose will be a no-op and performance will be better and we won't have a blocking dispose(shareable Cory concern), for old code and new code with only Dispose() call behaviour will be compat with past one.
I mean I wouldn't kill the idea of the new api for "better performance", maybe could be a good addition to renew a bit this class.

**Comment by Tratcher** [comment]
How realistic is the performance issue? The connection would have to be backlogged before sending QUIT would block.  The connection should only be backlogged while a message is in flight, and calling Dispose during a message send would trigger Abort rather than QUIT.

**Comment by tmds** [comment]
Protocol close doesn't belong in Dispose.
Sending/receiving to a peer may block, and Dispose offers no way out.
Dispose should stick to resource cleanup. A separate method for the protocol close which can be cancelled is better.
This is the pattern followed by [WebSocket.CloseAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.closeasync?view=netcore-3.1).

**Comment by MarcoRossignoli** [comment]
@Tratcher is not possible that in a congested server(where we use smtpclient) a possible true async quit scale better than dispose in same condition?Or are you saying that this is not possible because if we have sent the message on same connection dispose won't block?

**Comment by Drawaes** [comment]
Add a dispose async for those that are worried about the blocking and thread starvation, it will be as accessible as the close method, and put the quit in the dispose to maintain compatibility.... My 2c

**Comment by Tratcher** [comment]
@MarcoRossignoli Dispose already Aborts if there are any operations still in progress.
https://github.com/dotnet/runtime/blob/416ef2aa2f71565fa19697aa41f9e0d0e5f83066/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs#L1102-L1106
Given that, it should be difficult to get into a situation where sending QUIT would block.

**Comment by MarcoRossignoli** [comment]
> Given that, it should be difficult to get into a situation where sending QUIT would block.

It's not clear to me why inflight data send and quit are "related" to blocking...I mean AFAIK every data send to network can block, unrelated to previous send data, am I wrong?I mean I can send message and at the end block on send quit. My concern is not related to dispose that wait for the inflight message, but the normal workflow send->quit.

**Comment by scalablecory** [comment]
> It's not clear to me why inflight data send and quit are "related" to blocking...I mean AFAIK every data send to network can block, unrelated to previous send data, am I wrong?

@Tratcher's assumption is that `SmtpClient` will not be used in a way which would fill up your TCP send buffer. In this case, writing a QUIT will just write to the same buffer without blocking.

**Comment by tmds** [comment]
If you want to send QUIT in Dispose, set `Socket.Blocking` to `false` before sending. That avoids the blocking behavior.

**Comment by scalablecory** [comment]
Note, the spec actually calls for more than QUIT -- it calls for us to wait for the reply. So, if we really wanted to be compatible, we would be blocking regardless of `SmtpClient` usage.

**Comment by MarcoRossignoli** [comment]
Yep per spec we should wait reply.

**Comment by davidsh** [comment]
Fixed by PR #683

**Comment by mguinness** [comment]
Thanks to Marco for the PR.  @davidsh Are there plans to backport this to 3.1, or will we need to wait for .NET 5?

**Comment by davidsh** [comment]
> Are there plans to backport this to 3.1, or will we need to wait for .NET 5?

There are no plans for backport to 3.1.  But I'll let @karelz or @danmosemsft comment on that. We would need to see many customers impacted in order to considering a backport.

**Comment by karelz** [comment]
As @davidsh mentioned, it depends on impact - how big, how many customers, how hard to workaround.
So far, this didn't seem to be absolutely terrible adoption blocker IMO.
