### ISSUE TITLE
Assertion failed 'curSize < maxSplitSize' during 'Emit code' 

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#91251]
```c#
// Found by Antigen


using System;
public class TestClass
{
    public static void Main(string[] args)
    {
    }
}
/*
Environment:

set COMPlus_JitSplitFunctionSize=4

Assert failure(PID 5728 [0x00001660], Thread: 10212 [0x27e4]): Assertion failed 'curSize < maxSplitSize' in '(dynamicClass):InvokeStub_EventAttribute.set_Level(System.Object,System.Object,ulong):System.Object' during 'Emit code' (IL size 25; hash 0x433e37b5; FullOpts)
    File: D:\a\_work\1\s\src\coreclr\jit\emit.cpp Line: 3146
    Image: e:\kpathak\CORE_ROOT\corerun.exe
*/

**Comment by kunalspathak** [comment]
I see this and few other issues with `COMPlus_JitSplitFunctionSize`. Also see this on arm. We should evaluate how important it is to try out this environment variable and such issues. If it is less important, I can reduce its weight (or remove) from Antigen. Let me know @BruceForstall

**Comment by BruceForstall** [comment]
I think it's important this stress mode works for any given value, and we use it, even if (and because) the actual scenario requiring splitting is very rare.

**Comment by jakobbotsch** [comment]
The assert (but not the problem) is new with #90246, but likely the problem is just that we cannot support a `JitSplitFunctionSize` that is smaller than a certain size due to how the splitting only works on IG boundaries.

The minimal size we can support splitting is probably something like the max size of a prolog + the max size of an IG + the max size of an epilog to guarantee we can always find a split point.

**Comment by BruceForstall** [comment]
> the problem is just that we cannot support a `JitSplitFunctionSize` that is smaller than a certain size

There is logic that is supposed to allow splitting above the specified size if necessary (and thus allow any size to be specified); perhaps it's not working.

**Comment by jakobbotsch** [comment]
> There is logic that is supposed to allow splitting above the specified size if necessary (and thus allow any size to be specified); perhaps it's not working.

Well, if we want a "best-effort" thing for testing purposes then the assert I added should likely just be relaxed or removed again. Under normal operation `emitSplit` is not allowed to be best effort, though, so should we really allow it when testing?

**Comment by BruceForstall** [comment]
The actual required split size (512KB or 1MB) is always greater than our required minimum (max size of prolog, etc.), so in reality it's not a problem. I wanted to allow you to say `JitSplitFunctionSize=1` (for example) to force the maximum amount of splitting, without worrying about what the actual practical JIT minimum number is.

**Comment by BruceForstall** [comment]
Related? https://github.com/dotnet/runtime/issues/91139

**Comment by BruceForstall** [comment]
I think it's not very useful to try and calculate a "minSupportedSplitSize" since it's not clear how to accurately calculate that, given that epilogs can be an arbitrary number of IGs, and multiple consecutive epilogs could appear, and we can't tell currently where one ends and another begins.

I'm going to loosen the assert to the hard requirement (which might not be terribly useful).
