### ISSUE TITLE
NativeAOT Checked smoke tests are taking a long time

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#91296]
Debug takes about 40 minutes, but Checked takes > 120 minutes. We should figure out what check is taking such a long time. If it's important, we might want to move the test suite to runtime-extra-platforms.

**Comment by MichalStrehovsky** [comment]
The checked leg does multimodule testing so that one adds a couple minutes to the build because we compile the entire framework. We also run the Loader and Interop tests there.

The checked leg also does all sorts of event pipe testing. Most recently we added quite a few extra tests to it: https://github.com/dotnet/runtime/pull/89976#discussion_r1286265063

We might want to make a better call on what is a smoke test vs what is okay to just run as part of extra platforms (we do run _all of the above_, except for multimodule testing, in extra platforms). IIRC the event pipe tests take more than Loader+Interop combined and they also depend on libs.oob subset so we need to spend time building things like System.Speech just for event pipe testing sake (https://github.com/dotnet/runtime/pull/89153#issuecomment-1641468099).

Cc @LakshanF @elinor-fung
