### ISSUE TITLE
C# ADO.NET Transaction Scope Auto Committed Before Calling Complete()

### ISSUE THREAD

**Issue by ras90it** [dotnet/runtime#91376]
### Description

```c#
using (TransactionScope scope = new TransactionScope())
{
    try
    {
        using (OleDbConnection myCon = new OleDbConnection(db2ConnectionString))
        {
            myCon.Open();

            OleDbCommand cmd = new OleDbCommand
            {
                CommandType = CommandType.Text,
                CommandText = insertQuery, // INSERT QUERY
                Connection = myCon
            };

            _ = cmd.ExecuteNonQuery();

            scope.Complete();
        }
    }
    catch (Exception ex)
    {
        throw;
    }
}
```

### Reproduction Steps

1. Run the C# code with DB2 Connection String.
2. Before Calling scoep.complete() method, the inserted value is committed in DB2 and able to be seen by querying in the DB2 table.
3. But the similary code for SQL Connection works well.

### Expected behavior

1. Until call scope.complete() the method, should not auto commit in db

### Actual behavior

1. Now after executing **cmd.ExecuteNonQuery()**, the data gets auto-commited in db2 before calling scope.complete().

**Comment by roji** [comment]
@ras90it if there's a problem here, it's a problem with the DB2 provider - that's not maintained here; you'll have to report the issue to the maintainers of the DB2 driver. It's possible that the DB2 provider doesn't support TransactionScope, or that you have to explicitly opt into enlisting to it (some providers work this way).

I'm going to close this as external, but if you need further help don't hesitate to post back to this issue.

**Comment by roji** [comment]
> But the similary code for SQL Connection works well.

Just to be 100% sure, you're saying that the above code with TransactionScope **does** work with SQL Server? Can you confirm whether that's via OleDB, or via ADO.NET?

**Comment by ras90it** [comment]
`using (TransactionScope scope = new TransactionScope())
{
    try
    {
        using (SqlConnection myCon = new SqlConnection(sqlConnectionString))
        {
            myCon.Open();

            SqlCommand cmd = new SqlCommand
            {
                CommandType = CommandType.Text,
                CommandText = insertQuery, // INSERT QUERY
                Connection = myCon
            };


            _ = cmd.ExecuteNonQuery();

            scope.Complete();
        }
    }
    catch (Exception ex)
    {
        throw;
    }
}`

Above code works fine

**Comment by roji** [comment]
@ras90it the code you posted for SQL Server uses ADO.NET rather than OleDB, and so doesn't tell us much.

First, in general I'd recommend trying to use the DB2 ADO.NET driver rather than OleDB; OleDB access is old and can be considered archived at this point.

Otherwise, TransactionScope is indeed supported with OleDB - but I don't have any specific knowledge about the DB2 provider. [This documentation page](https://www.ibm.com/docs/en/db2/9.7?topic=ods-ole-db-services-automatically-enabled-by-ole-db-provider) suggests that it's supported, but may be disabled via the Windows Registry. You may also have better luck by setting `OLE DB Services` on the connection string, see [this SO question](https://stackoverflow.com/questions/1545064/how-do-i-keep-an-oledbconnection-from-trying-to-enlist-in-a-distributed-transact) and [this resource](https://learn.microsoft.com/en-us/previous-versions/ms810829(v=msdn.10)?redirectedfrom=MSDN#configuring-resource-pooling-from-your-application) for more information.

**Comment by roji** [comment]
Closing as I'm not seeing evidence of a runtime issue.
