### ISSUE TITLE
Segmentation fault (core dumped) started popping a lot since upgrading to .NET 7

### ISSUE THREAD

**Issue by gdoron** [dotnet/runtime#91571]
### Description

Since migrating to .NET 7, we have started getting a lot of `Segmentation fault (core dumped)` crashes in our ASP.NET Core applications.

Unlike other issues here, .NET was not installed with snap or any other tool distribution tools, since we are using the official .NET docker:

`dotnet/aspnet:7.0-jammy` after we migrated from `dotnet/aspnet:6.0.15-jammy`.

`dmesg` yielded this result:

>[ 5198.137895] dotnet[6138]: segfault at 7f365c282000 ip 00007f36d250b99e sp 00007ffd7ece7738 error 4 in libc.so.6[7f36d2385000+195000]
[ 5198.145939] Code: 00 00 00 00 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 83 fa 20 77 36 b9 ff ff ff ff c4 e2 68 f5 c9 c5 fb 92 d1 62 e1 7f 2a 6f 16 <62> f3 6d 22 3e 0f 04 c5 fb 93 c1 85 c0 75 03 c3 66 90 f3 0f bc c0

Let me know if there is any additional info I can gather that will help you debug the issue.

### Reproduction Steps

The only thing our dockerfile has, is installation of newrelic's agent (which was there also in .NET 6).

```
# Newrelic agent
RUN apt-get update && apt-get install -y wget ca-certificates gnupg curl \
&& echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
&& wget https://download.newrelic.com/548C16BF.gpg \
&& apt-key add 548C16BF.gpg \
&& apt-get update \
&& apt-get install -y newrelic-dotnet-agent \
&& rm -rf /var/lib/apt/lists/*

ENV CORECLR_ENABLE_PROFILING=1 \
CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
CORECLR_NEWRELIC_HOME=/usr/local/newrelic-dotnet-agent \
CORECLR_PROFILER_PATH=/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so
# Newrelic agent
```

### Regression?

We did see some issues with `dotnet/aspnet:6.0.15-jammy`, but it was once or two a week, now it's dozens a day.

**Comment by hez2010** [comment]
Can you try removing the newrelic profiler and see if the issue still persists?

**Comment by mangod9** [comment]
Also would be good to capture a few dumps so we would know where its crashing. Thx.

**Comment by gdoron** [comment]
@mangod9 can you please guide us on how to collect these dumps on k8s and docker?
We couldn't really understand where these dumps are written to.

And I'm not sure it would be easy for us to remove new-relic in our production environment, as it only happens there (and dozens of times a day)

**Comment by mangod9** [comment]
documentation on collecting crash dumps is here: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash

**Comment by tommcdon** [comment]
> @mangod9 can you please guide us on how to collect these dumps on k8s and docker?
> documentation on collecting crash dumps is here: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash

In addition to the above, in case you are running in kubernetes there are a couple more things to consider:
1. You might need to increase container memory limits.  Once .NET is configured to collect a dump on crash, it will launch createdump inside of the container causing both space as well as memory will increase.  We suggest temporarily increasing the container memory limits to address this as needed.
2. If your Kubernetes system is using liveness probes to monitor container health, you might find that it terminates the container while we are collecting a dump as the service becomes non-responsive once it crashes.  For example, depending on the size of the process, it might take a while for createdump to complete and result in the health monitoring system to terminate the container.  If this is happening, we suggest making the liveness probes less aggressive.
3. We suggest mounting non-ephemeral storage to the container so that the dump can be retrieved after it crashes.  The .NET crash dump environment variables allow you to configure the location, but that location will always be written to a directory inside of the container.  If the file system is destroyed after the dump is created, then we won't be able to download the dump.  A couple options include a) use a host directory into the container, then scp the dump from the node, or b) use a network-based storage solution, such as azure storage to egress the dump from kubernetes to a location where it can be later retrieved.

Hope this helps!

**Comment by gdoron** [comment]
@tommcdon @hez2010 @mangod9 Sorry for ghosting...
How can we share the dumps privately with MSFT?

**Comment by gdoron** [comment]
@mangod9 kind ping.

**Comment by mangod9** [comment]
hey @gdoron, if you can put it on a secure share and send details via email -- would that work?

**Comment by gdoron** [comment]
@mangod9 it would, yes.
Where should I send it to?

**Comment by mangod9** [comment]
my email in my profile. Thanks!

**Comment by gdoron** [comment]
@mangod9 sent, thanks and sorry for the delay, tons on my plate and the whole mess in Israel right now...

**Comment by mangod9** [comment]
This looks like the same issue as https://github.com/dotnet/runtime/issues/87012. @janvorli doesnt look like the fix is ported to 7?

**Comment by mangod9** [comment]
@gdoron, since .NET 8 is now released do you plan to move to that soon? If not we could port to 7 but the next servicing release would most likely be in Jan. Thanks!

**Comment by gdoron** [comment]
@mangod9 I don't think we'll be able to upgrade to .NET 8 before January.
But even if we specifically could, I'm sure the broader .NET community would still want it to back ported to .NET 7, it's a major bug crushing the processes.

Thanks for your help on this guys!

**Comment by mangod9** [comment]
Hi @gdoron, we are looking into porting the fix to 7, but the next servicing release is going to be in Feb, and given that 8 is out wanted to check the priority on porting to 7. Thanks.

**Comment by gdoron** [comment]
@mangod9 The R&D teams are pretty much overloaded with work and are spread thin, so it's very likely we'll have to wait with upgrading to .NET 8 even after Feb (and in some projects we are blocked by a 3rd party that still doesn't support .NET 8, so anyway we'll need it).

So we'll very much appreciate if you could patch it to 7, and I'm sure we won't be the single company using .NET 7 after Feb given the support is until end of May.

Thanks!

**Comment by jkotas** [comment]
> using .NET 7 after Feb given the support is until end of May.

The last 6 months of support is Maintenance support where  .NET releases are updated to mitigate security vulnerabilities, only.
This is documented at https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#servicing . Backporting this fix to .NET 7 would require an exception.

**Comment by gdoron** [comment]
I'm wondering why does it have the 9.0.0 milestone.

**Comment by jkotas** [comment]
We ended up to not backporting the fix: https://github.com/dotnet/runtime/pull/95859#issuecomment-1983061099

This issue should be closed.

**Comment by gdoron** [comment]
Just wanted to confirm the issue was fixed by upgrading to .NET 8, we haven't have a single crash since then, for over a month.
