### ISSUE TITLE
System.Diagnostics.Metrics.LastValue looks like it could experience torn reads

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#91591]
`LastValue`, which is used by `ObservableGauge<>`, has an `Update(double value)` method that just does:
```C#
        private double? _lastValue;

        public override void Update(double value)
        {
            _lastValue = value;
        }
```
Writing a `double` on a 32-bit platform is not guaranteed to be an atomic operation, and regardless of bitness, writing a `double?` is not guaranteed to be an atomic operation. We could thus end up in a situation where, for example, `_lastValue` reports it contains a value but the value hasn't actually been initialized, or where the reported value is an amalgum of an old value and one currently being written.

**Comment by tommcdon** [comment]
@noahfalk @tarekgh

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/blob/c53e4dcdaae1912b57b2bfb3c67d2e99d3a2bdd1/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/LastValueAggregator.cs#L10

@stephentoub would using `Interlocked.Exchange` should fix that, right?

**Comment by noahfalk** [comment]
This type should never get accessed concurrently from multiple threads so I believe functionally we are fine, but certainly I made a mistake including the lock() statement on Update() which implies multi-threaded use. The LastValue aggregator is only used for the ObservableGauge instrument and the values of an ObservableGauge are only populated on-demand once per collection cycle. This collection always occurs on the same thread that is under our control, and the type never gets exposed to user code where some other thread might interact with it concurrently. 

I think the correct fix here is just to comment that the type is accessed in a single-threaded manner and to delete the misleading lock() statement in Update(). Since there is no functional issue we could easily make this change in .NET 9, no worry about squeezing anything into .NET 8 builds.

**Comment by tarekgh** [comment]
I moved it to 9.0. @noahfalk are you willing to submit a fix for it? no rush, I am asking just to avoid double working :-)

**Comment by noahfalk** [comment]
I'm glad to let you take it : )

**Comment by stephentoub** [comment]
@noahfalk, now that `Gauge<>` also uses this:
https://github.com/dotnet/runtime/blame/c829f9c816384910bb88afd0fc4b5e3562f48db1/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/AggregationManager.cs#L320-L329
is your statement above still accurate? `Gauge<>` is actually exposed in such a way that user code could interact with it from multiple threads, right?

**Comment by noahfalk** [comment]
Good memory @stephentoub! You are correct, adding `Gauge<>` now exposes the LastValue aggregator to multi-threaded concurrent writes and my suggestion from last year no longer holds. Thinking on it more, it looks like we have another bug as well that we probably want to fix by not using the same aggregator implementation for the Observable and Non-observable cases. Writing code like this should report the new value 123 indefinitely:
```
Gauge<double> g = meter.CreateGauge(...);
g.Record(123);
```
But the [Collect()](https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/Metrics/LastValueAggregator.cs,20) call is clearing the previous value after one reporting cycle. That clearing behavior is only by-design for ObservableGauge<>() where failing to report a value in the callback is considered meaningful.

Probably a decent fix would be having an ObservableLastValue that is single threaded + clearing behavior and a LastValue that is multi-threaded with no clearing behavior. Not supporting the clear is nice because we can use double instead of double? which should let us avoid tearing on x64 without doing anything expensive.
