### ISSUE TITLE
Negative double Formatting difference between .NET 6 and .NET Framework 472

### ISSUE THREAD

**Issue by BartvanLaar** [dotnet/runtime#91777]
### Description

When upgrading a project from .NET Framework 472 to .NET 6 some unit tests started to fail.
The application is very dependent on the textual representation of numbers as the end result is a XML file that's later transformed into a PDF.

Since upgrading to .NET 6 a test failed because negative zero doubles are formatted differently between .NET 6 and .NET Framework.

I expected (-0d).ToString() to behave the same as (-0.0).ToString() like they do in .NET Framework 472.
But the first example results in "0" and the second results in "-0" in .NET 6 while in .NET Framework 472 they both result in "0".
For completeness sake the reproduction steps also include an integer case.

I do not know whether this is by design or an oversight, but i'd like to know what will happen moving forward and how one should deal with this case.

### Reproduction Steps

The following code can be run in both a .NET Framework 472 and .NET 6 console application.
```
internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(((int)-0).ToString());
            Console.WriteLine(((double)-0).ToString());
            Console.WriteLine((-0.0).ToString());
            Console.ReadKey();
        }
    }
```

### Expected behavior

The console program should output the following in .NET 6 to be consistent with the .NET Framework 472 implementation:
```
0
0
0
```

### Actual behavior

The console program outputs the following in .NET 6:
```
0
0
-0
```

### Regression?

Like mentioned, in .NET Framework this works differently.

### Known Workarounds

Removing the minus sign from the string representation when the value is equal to 0.

### Configuration

**Which version of .NET is the code running on?**
Both .NET 6 and .NET Framework 472.

**What OS and version, and what distro if applicable?**
Edition:    Windows 10 Enterprise
Version:   22H2
OS Build: 19045.3324

**What is the architecture (x64, x86, ARM, ARM64)?**
Tested on both x64 and x86.

**Do you know whether it is specific to that configuration?**
I don't know, but I wouldn't assume it matters.

**Comment by huoyaoyuan** [comment]
See also #54537

**Comment by tannergooding** [comment]
Everything is working as expected, intended. The issue is you have some precedence considerations here.

`(int)-0` is:
1. Declare integer literal `0` (you have `0`)
2. Negate (you still have `0`, there is no negative integer zero)
3. Cast to `int` (you still have `0`, it was already an int)

`(double)-0` is:
1. Declare integer literal `0` (you have `0`)
2. Negate (you still have `0`, there is no negative integer zero)
3. Cast to `double` (you still have `0`, it was an int where there is no negative integer zero)

`-0.0` and `-0.0d` are:
1. Declare double literal `0` (you have `+0.0`)
2. Negate (you have `-0.0`, because there is a negative double

You could always open an issue suggesting that Roslyn enable a warning wave for a literal `-0`, since that is likely a user error/bug and they intended it to be a float/double instead.

**Comment by tannergooding** [comment]
As for why .NET Core 3.0 and later prints `-0.0` for the last, rather than `0`. This was an intentional break done to ensure IEEE 754 compliance and to remove a known case of user bugs/issues: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

It was not fixed in .NET Framework due to the much higher backwards compatibility bar.

**Comment by Clockwork-Muse** [comment]
> The application is very dependent on the textual representation of numbers as the end result is a XML file that's later transformed into a PDF.

@BartvanLaar - 

... if this process is culture-aware (especially if it uses the implied culture by not explicitly specifying one), these tests can fail at any time anyways, when the culture data is updated on the OS.  Absent some _very_ specific requirements (which should result in you creating a custom culture) you generally shouldn't be testing the outputting of formatting (other than "not empty", and possibly "parses back to the original value", although that's hard in some situations).
Also, if these values represent monetary values, you shouldn't be using `float`/`double` for them, but `decimal`.

**Comment by BartvanLaar** [comment]
@Clockwork-Muse 
I've dumbed down the example a lot to illustrate the issue (for which i don't think culture matters) that a (double)0 behaves different from a (double)0.0 and that it behaves entirely differently from .NET Framework 472.
And no these values do not represent monetary values.

**Comment by BartvanLaar** [comment]
@tannergooding then how would you expect -0d to behave?

**Comment by tannergooding** [comment]
> then how would you expect -0d to behave?

As I indicated above. `-0d`. `-0d` represents `double: negative zero` because it is explicitly suffixed with `d` and so `0d` is interpreted as `double: 0` and then negated to get `double: -0`. You can effectively envision this as 2 steps of code:
```
double d = 0;
d = -d;
```

`-0.0` is the same way because `0.0` represents: `double: 0` (the `.` causes this). Again two steps of code:
```
double d = 0.0;
d = -d;
```

`(double)-0`, however, has no suffix (`d` or `f`) and no `.`, so it is interpreted as an integer literal. Integers do not have a negative zero and so negating it keeps it as 0. You can envision this as three steps of code:
```
int i = 0;
i = -i;
double d = (double)i;
```

------------------------

>  that it behaves entirely differently from .NET Framework 472.

Also as indicated, .NET Core took an explicit breaking change here to ensure that values would roundtrip by default (no loss of data) and that we remained IEEE 754 compliant by default.

.NET Framework did not get this fix due to its much higher backwards compatibility bar. Its implementation is effectively "frozen" and not getting changes outside of critical security fixes and the like: https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/

**Comment by BartvanLaar** [comment]
Thanks for the explanation
