### ISSUE TITLE
[mono] how to free object allocate using `mono_object_new_pinned`

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#91784]
we want to call `mono_object_new_pinned` allocate object, but how to free the gc handle

**Comment by srxqds** [comment]
and these line maybe cause object leak when it have been cached?
https://github.com/dotnet/runtime/blob/f3c7893c5283af55fea171bb694596a2f53b650e/src/mono/mono/metadata/reflection.c#L558-L574C6

@vargaz  @lambdageek

**Comment by srxqds** [comment]
anyone can help me?

**Comment by BrzVlad** [comment]
Objects allocated normally can be moved around during GC collections, if they are promoted or a heap compaction happens. If you allocate an object from native and you only hold a reference to it from native, it can die during future GC collection. In order to prevent this you would need to allocate a GC handle for the object, store the ref in some other reachable object etc., so that the GC can detect that the object is still alive.

`mono_object_new_pinned` does not allocate a GC handle. The only thing that this api ensures is that, during its lifetime, the object will not be moved around. But it can die like any other object if it is not referenced.

**Comment by srxqds** [comment]
ok, thank you got it!
