### ISSUE TITLE
Updating to .NET 8 Preview 7 from .NET 7 Different behavior on Configuration Binding

### ISSUE THREAD

**Issue by miaooss** [dotnet/runtime#91823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I found a different behavior from .NET 7 to .NET 8.

In the app settings if you have an array of objects, but another configuration provider adds a property in the wrong way (Just as an object.)

When binding the configuration as a list, it will return 2 objects.
One with the correct data and one with null values.

I added a demo project to reproduce the issue.

Note :
We are using the `AddAzureKeyVault` function from this package `Azure.Extensions.AspNetCore.Configuration.Secrets`.
I'm able to reproduce it without the need of a key vault.

By removing the wrong entry on the key vault I was able to fix the issue on our end

### Expected Behavior

When binding the configuration as a list, I should receive the number of items I have in my configuration and not One that contains no values

### Steps To Reproduce

Here is a small project to see the difference:
https://github.com/miaooss/animated-octo-winner

### .NET Version

8.0.100-preview.7.23376.3

**Comment by layomia** [comment]
Doesn't seem to be a source-gen issue. Will take a look. cc @tarekgh.

**Comment by tarekgh** [comment]
@layomia I can look next week on this.

**Comment by miaooss** [comment]
Hi thank you for your time on this.

To be honest this is not critical and I found a fix on our side (Remove the wrong entry).

I was just mentioning it because it's a change of behavior .

**Comment by tarekgh** [comment]
@miaooss thanks for your report. I confirmed this is the breaking change we have done https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/dictionary-configuration-binding. Although the title mentions dictionary, it is really done for collections in general. The PR did the change is https://github.com/dotnet/runtime/pull/86485. I can see the new change in the collection binding is acceptable and gives a chance to the developers to catch wrong configurations instead of just ignoring it. 

CC @Maximys
