### ISSUE TITLE
EFCore Design v7 Package Requires Net7 System Libraries

### ISSUE THREAD

**Issue by brandonryan** [dotnet/runtime#91922]
`Microsoft.EntityFrameworkCore.Design@7.0.10` Requires Net7 System libraries. 

Dependency Resolution Chain:
- `Microsoft.EntityFrameworkCore.Design@7.0.10`
- `Microsoft.Extensions.DependencyModel@7.0.0`
- `System.Text.Json@7.0.0`
- `System.Text.Encodings.Web@7.0.0`

Runtime exceptions occur when project is targeting net6 and is using above system libraries.
The issue specifically happens when you reference a project that is using it as a Private Asset.

Runtime exception:
```
message=Could not load file or assembly 'System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

[Original Issue](https://github.com/dotnet/efcore/issues/31685)

# Reproduction
dotnet run in TestApp dir
https://github.com/brandonryan/efcore-repoduce-net6-compat

**Comment by ViktorHofer** [comment]
@ajcvickers why was this issue moved over into dotnet/runtime? Isn't this an EFCore issue? And btw, from reading the description, it's not clear to me what the issue is. @brandonryan it would if you provide an isolated piece of code that reproduces the problem.

**Comment by ajcvickers** [comment]
@ViktorHofer The assertion is that a package pulled in transitively through a .NET Standard 2.0 dependency is attempting to use a binary that is for .NET 7 when running on .NET 6.

**Comment by brandonryan** [comment]
> @ajcvickers why was this issue moved over into dotnet/runtime? Isn't this an EFCore issue?
> 
> From reading the description, it's not clear to me what the issue is. @brandonryan it would if you provide an isolated piece of code that reproduces the problem.

Can't get more isolated than the reproduction repository that I provided. The project structure is important

**Comment by brandonryan** [comment]
It could definitely be argued that the runtime (linker?) is falling short here and its not really an EFCore problem. Other languages can handle this situation. Given the current behavior though, I think its necessary to downgrade to `Microsoft.Extensions.DependencyModel` v6 if possible. Or maybe there is some dependency flag that im missing?

**Comment by ViktorHofer** [comment]
So in your case `TestLib.csproj` references M.EFC.Design/7.0.10 which transitively brings-in System.Text.Json which itself brings-in `System.Text.Endcodings.Web`.

Now, when you build the test app, you will see a build warning:

> C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277: Found conflicts between different versions of "System.Text.Encodings.Web" that could not be resolved. [C:\temp\efcore-repoduce-net6-compat\TestApp\TestApp.csproj]

The warning already hints that something is wrong when trying to resolve the S.T.E.W dependency. The `ResolveAssemblyReferences` task that emits that warning is responsible for - take a guess - resolving assembly references. It looks at the assembly references of `TestLib` and sees that it references System.Text.Encodings.Web/7.0.0.0:

<img width="684" alt="image" src="https://github.com/dotnet/runtime/assets/7412651/486a2745-93d2-4ed0-8204-b0cabc3c7086">

Now, that task needs to resolve the S.T.E.W dependency somehow. It knows that TestLib depends on the 7.0.0.0 version while the `TestApp` depends on the 6.0.0.0 version (because the app targets net6.0 and S.T.E.W is an implicit framework reference). As the task can't find the 7.0.0.0 version (i.e. in the output folder), it picks the 6.0.0.0 version instead. 

The problem here is that your app and your referenced library depend on different versions of the same library which is incompatible (as the .NET loader needs to resolve the library/identity from a single assembly). This is because of your use of `PrivateAssets` on the M.EFC.Design PackageReference.

**Note, this isn't a package or build authoring issue on our side.** You as the app owner must make sure that your libraries use compatible dependencies.

You can either remove the PrivateAssets attribute or make sure that `TestApp` uses the same version of `S.T.E.W` as the `TestLib` by adding a PackageReference to the project.

**Comment by brandonryan** [comment]
Right, Thank you for the detailed explanation. That was (roughly) what I thought was going on.
This is why I put it in EFCore repo. v7 is supposed to be compatible with v6, and the designer is a developer tool. Didn't really want to include it in all my projects. I guess I'll just add `S.T.E.W` 7.0 to my dependencies for now.

**Comment by ViktorHofer** [comment]
While the designer package might be a developer tool (can't speak to that), it brings in other dependencies like S.T.J and S.T.E.W which are runtime packages and interact with the main app at build and run time.

Your `TestLib` has a direct dependency on `S.T.E.W` (see my picture above), so it makes sense to add a package reference to it (without PrivateAssets!) in `TestLib`. That dependency then flows transitively to the parent project: `TestApp`.
