### ISSUE TITLE
Performance of System.Formats.Cbor

### ISSUE THREAD

**Issue by andrei-faber** [dotnet/runtime#91969]
### Description

System.Formats.Cbor is about x100 slower than Newtonsoft.Json. Isn't this a bit too much? Or am I missing something?

### Reproduction Steps

Simple data writing benchmark [https://github.com/andrei-faber/SerializationBenchmark](https://github.com/andrei-faber/SerializationBenchmark)
And the results:
```
JSON:   0.7759061 secs
CBOR:   80.0668419 secs
```

### Expected behavior

not be so slow

### Actual behavior

is very slow

### Configuration

.NET 7
WIndows 10 x64

**Comment by vcsjones** [comment]
> System.Formats.Cbor is about x100 slower than Newtonsoft.Json. Isn't this a bit too much? Or am I missing something?

`CborWriter` doesn't have the capability to write directly to a stream. It instead writes to an internal buffer. For such a large array, it is constantly re-allocating the internal buffer as the buffer needs to grow.

As a work around, if you grow the buffer with a "one shot" API, and just clear it out, I get much better results. Change `WriteCbor` to this:


```C#
static void WriteCbor(string fileName, int[] data)
{
	var writer = new CborWriter();
	writer.WriteByteString(new byte[0x1FFFFFF]);
	writer.Reset();
	writer.WriteStartArray(null);
	foreach (var cur in data)
	{
		writer.WriteInt32(cur);
	}
	writer.WriteEndArray();

	var bytes = writer.Encode();
	File.WriteAllBytes(_dataPath + fileName, bytes);
}
```

And for me it's actually faster than JSON.NET now:


```
JSON:   0.5767138 secs          30,888,891
CBOR:   0.1196781 secs          19,868,650
```

This seems "interesting" and there are two potential ways I think we can improve here.

1. We can, [like we did for AsnWriter](https://github.com/dotnet/runtime/issues/69573), implement an initial capacity for the writer so that callers can give a size hint to avoid so much re-allocating.
2. WriteStartArray when we know the array length because it's a definite array, we can at least use that as a size hint for the floor of what is going to be written. It doesn't know what it is an array of, so it can probably err on the size of "writing small things", but if the array it is given is 4,000,000, we know we are going to write at least 4_000_000 bytes.

**Comment by andrei-faber** [comment]
@vcsjones making it work with streams would be the best solution, but reserving the capacity is second best I guess.

**Comment by eiriktsarpalis** [comment]
You could also try pooling your writers to amortize the cost of initial allocation (see https://github.com/dotnet/runtime/issues/67868). There are a few other issues with this benchmark as well, it includes IO operations in its measurements and it allocates an intermediate buffer to store the encoded CBOR. If I rewrite the benchmark so that it avoids these problems and uses `BenchmarkDotNet` instead:

```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Buffers;
using System.Formats.Cbor;
using Newtonsoft.Json;

BenchmarkRunner.Run<SerializationBenchmark>(args: args);

[MemoryDiagnoser]
public class SerializationBenchmark
{
    private readonly int[] _data = CreateData();
    private readonly MemoryStream _destination = new MemoryStream();
    private readonly JsonSerializer _jsonSerializer = new();
    private readonly CborWriter _cborWriter = new();

    [Benchmark]
    public void WriteJson()
    {
        // Clear pooled state
        var destination = _destination;
        destination.Position = 0;
        // Serialize
        using var writer = new StreamWriter(destination, leaveOpen: true);
        _jsonSerializer.Serialize(writer, _data);
    }

    [Benchmark]
    public void WriteCbor()
    {
        // Clear pooled state
        var destination = _destination;
        var writer = _cborWriter;
        var data = _data;
        writer.Reset();
        destination.Position = 0;
        // Serialize
        writer.WriteStartArray(data.Length);
        foreach (var cur in data)
        {
            writer.WriteInt32(cur);
        }
        writer.WriteEndArray();
        // Copy encoding to stream
        byte[] buffer = ArrayPool<byte>.Shared.Rent(writer.BytesWritten);
        try
        {
            int written = writer.Encode(buffer);
            destination.Write(buffer, 0, written);
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(buffer);
        }
    }

    private static int[] CreateData()
    {
        var data = new int[4_000_000];
        for (var i = 0; i < data.Length; i++)
        {
            data[i] = i;
        }

        return data;
    }
}
```

Then results become dramatically different:

|    Method |      Mean |    Error |   StdDev |      Gen0 |  Allocated |
|---------- |----------:|---------:|---------:|----------:|-----------:|
| WriteJson | 294.70 ms | 5.611 ms | 6.236 ms | 9500.0000 | 96005952 B |
| WriteCbor |  31.95 ms | 0.243 ms | 0.228 ms |         - |          - |

Needless to say, this isn't comparing apples-to-apples but in terms of benchmarking pure serialization performance of the two approaches I think this is a better approximation of reality.

**Comment by eiriktsarpalis** [comment]
I think we can close this as answered, we have an API proposal tracked by https://github.com/dotnet/runtime/issues/91978 in response to feedback.

**Comment by andrei-faber** [comment]
For the sake of accuracy - IO has negligible effect here, so I wouldn't call it a problem. And copying data to MemoryStream creates an extra buffer anyway. Reusing the stream only shifts the burden of allocation to another test.
So, only preallocation in CborWriter has a significant effect.

**Comment by eiriktsarpalis** [comment]
When measuring performance it's important to isolate the particular component being tested. Blending in IO operations or incurring allocations from unrelated components may skew the final result, often substantially.

**Comment by andrei-faber** [comment]
@eiriktsarpalis in this case it doesn't change the result much. And in any case, making the MemoryStream allocate memory in one test and not in the other is much worse.

**Comment by eiriktsarpalis** [comment]
> And in any case, making the MemoryStream allocate memory in one test and not in the other is much worse.

The same `MemoryStream` is being reused in both benchmarks.

**Comment by fandrei** [comment]
@eiriktsarpalis and as much as I understand in the test that runs first it spends extra time to allocate the internal buffer, and in the second test it doesn't.

**Comment by eiriktsarpalis** [comment]
The way that BenchmarkDotNet works is that it will run each test method in isolation multiple times and extract statistical data on its performance. Any buffers will have been allocated on the initial run so will be reused in subsequent runs.

In other words, BDN is pretty cool https://github.com/dotnet/BenchmarkDotNet

**Comment by fandrei** [comment]
@eiriktsarpalis it doesn't look like it isolates the subsequent runs of the same test method, though.
