### ISSUE TITLE
DateTimeOffset constructor returning incorrect offset on macOS & Linux

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#92084]
Consider the following snippet:
```C#
Console.WriteLine(new DateTimeOffset(DateTime.MinValue).Offset);
```
This prints `00:00:00` when run on Windows but `-00:01:00` on macOS & Linux. 

Reproducing using .NET 8 RC1.

**Comment by tarekgh** [comment]
@eiriktsarpalis `DateTimeOffset(DateTime)` calculate the UTC offset according to the local TimeZone on the machine. You can print `TimeZoneInfo.Local.Id` when running and look if you see different time zone used there.

**Comment by Clockwork-Muse** [comment]
We're not using ICU on Windows for tz offset data yet.  Generally when this issue has come up before it's because Windows doesn't have any historical entries for "past offsets" (or that far back).

That aside, using `DateTime.MinValue` is actually "dangerous" behavior; as @tarekgh says it's using the UTC offset for the local TimeZone, and if the offset would be positive this would throw `ArgumentOutOfRangeException`.

**Comment by tarekgh** [comment]
Good point @Clockwork-Muse. @eiriktsarpalis you may print the value `TimeZoneInfo.Local.BaseUtcOffset` too.

**Comment by eiriktsarpalis** [comment]
Seems we can close this as by design.
