### ISSUE TITLE
Support direct P/Invokes without an import library.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#92140]
I tried to build an app with Native AOT and added a `DirectPInvoke` item in the project file that ports to a native library it is using. When I published the app, I was greeted by several warnings about unresolved imports from my native library. My guess is that the linker requires an import library to link, and for the Windows APIs that have direct P/Invokes by default it gets them from the Windows SDK.

Is there something that can enable direct P/Invokes without an import library from the NativeAOT side?

**Comment by MichalStrehovsky** [comment]
> My guess is that the linker requires an import library to link, and for the Windows APIs that have direct P/Invokes by default it gets them from the Windows SDK.

Yup, [on Windows, Native AOT uses a prepopulated list of direct P/Invoke methods that are available on all supported versions of Windows](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop). It will also pass the appropriate LIB files as references to the linker.

> Is there something that can enable direct P/Invokes without an import library from the NativeAOT side?

We could generate a LIB file same way [anyone can generate one](https://stackoverflow.com/questions/9946322/how-to-generate-an-import-library-lib-file-from-a-dll). It has issues because it won't have [import hints](https://devblogs.microsoft.com/oldnewthing/20100317-00/?p=14573) or any other things a proper LIB would have. It would have to be an extra opt-in, not something we'd do by default.

We'd be in no control over whether such generated LIB conflicts with any other libs the compiler (or the user) is passing to the linker. Think: someone specifying a kernel32 API to be done this way that we don't recognize within the compiler because it's not on the whitelist. Our generated LIB would redefine a symbol kernel32.lib already has, leading to a link failure.

I don't think we'd want to be in this business. The default behavior is to resolve p/invokes through `LoadLibrary`. If someone changes it to direct p/invokes, one should provide the LIBs, like for any other ahead of time compiled language. We document it this way.
