### ISSUE TITLE
Feature Request: restrict PDB resolution

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#92227]
It would appear there are chronic problems in PDB file parsing leading to remote code execution bugs.

We would like a flag in *.runtimeconfig.json (the loader configuration) that restricts PDB resolution to only resolve PDB files adjacent to the DLL files, not from any other paths. That is, for each DLL file loaded there is only one acceptable path for its PDB file, by changing the extension from DLL to PDB.

This is a defense in depth measure.

Setting might look something like this:

````
{
    "runtimeOptions": {
        "pdbResolver": "restrict"
    }
}
````

Clearly a single file application bundle with this setting set in the template runtimeconfig would result in only loading PDB files included in the bundle.

An additional setting of "off" to never load PDB files may also be useful, but not to us.

**Comment by tommcdon** [comment]
Hi @jhudsoncedaron, thanks for reporting this issue! 

The .NET Runtime / CoreCLR only uses PDBs for making exceptions better by adding line numbers. It already restricts itself to pdbs which are placed alongside the DLLs they apply to.  

Additionally, Visual Studio and Visual Studio Code support symbol configuration options, including restricting loading PDB's next to their respective DLL's.  Please see https://devblogs.microsoft.com/devops/understanding-symbol-files-and-visual-studios-symbol-settings/ for Visual Studio and https://github.com/dotnet/vscode-csharp/blob/main/debugger-launchjson.md#symbol-options for Visual Studio Code (with the C# extension loaded).

Since the runtime is already configured to only load symbols next to binaries, I will close this issue.

**Comment by jhudsoncedaron** [comment]
@tommcdon : Are you sure it doesn't follow source map paths, because it certainly did at one time? (We currently point our source map off into nilspace on release builds.)

**Comment by tommcdon** [comment]
@jhudsoncedaron Can you clarify what is meant by "following source map paths"?  Are you referring to runtime code that does this work, or an attached debugger to the application doing that work?  As previously mentioned, the runtime will only open a matching PDB next to the DLL and display the line number information in exception callstacks.   The runtime does not read Source Server or Source Link data from the PDB.

**Comment by jhudsoncedaron** [comment]
We have:

````
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=F:\src\Cedaron.FormBuilder.Presentation</PathMap>
  </PropertyGroup>
````

The result is "F:\src\Cedaron.FormBuilder.Presentation\bin\Release\net7\Cedaron.FormBuilder.Presentation.pdb" gets written to Cedaron.FormBuilder.Presentation.dll as the path to the pdb file. I don't have a good way of checking if the runtime still does this, but at one time it would try to resolve the pdb file from the F drive. (While I can point this anywhere; there aren't any universally safe paths.)

**Comment by tommcdon** [comment]
Hi @jhudsoncedaron, thanks for the quick response!  The Roslyn compiler's [PathMap](https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-options/advanced#pathmap) option changes the file path information stored in portable PDB's and does not affect PDB load behavior.
