### ISSUE TITLE
IEnumerator does not work properly if received directly from a List inside a linq statement

### ISSUE THREAD

**Issue by vmikhailov** [dotnet/runtime#92253]
### Description

IEnumerator.Current does not work as expected in case it is obtained from a List class without any casting and put into a list.
Works okay if casted or container is an Array.

### Reproduction Steps

Consider the following code:

`   

    var list1 = new List<string> { "aaa1", "bbb1", "ccc1" };
    var list2 = new List<string> { "aaa2", "bbb2", "ccc2" };

    var lists = new []{ list1, list2 };
    var e1 = lists.Select(x => x.GetEnumerator()).ToArray();
    var e2 = lists.OfType<IEnumerable<string>>().Select(x => x.GetEnumerator()).ToList();
    var e3 = lists.Select(x => x.GetEnumerator()).ToList();

    for(var i = 0; i < 2; i++)
    {
        Debug.Assert(e1[i].MoveNext());
        Debug.Assert(e1[i].Current is not null, "Iterator in an array");

        Debug.Assert(e2[i].MoveNext());
        Debug.Assert(e2[i].Current is not null, "Iterator in a casted list");

        Debug.Assert(e3[i].MoveNext());
        Debug.Assert(e3[i].Current is not null, "Iterator in a list");
    }`

### Expected behavior

The last assertion in the loop should not fail.

### Actual behavior

The assertion fails because there is no value in the Current while it should be there.

### Known Workarounds

Make ToArray or cast to (IEnumerable<string>) prior getting the enumerator.

### Configuration

Tested in dotnetfiddle on all the versions available at the moment (3.1, 5, 6, 7, 8 preview 3, fw4.7.2)
mac os arm 64, win64 both 7.0.401

### Other information
https://dotnetfiddle.net/W43axe

_No response_

**Comment by stephentoub** [comment]
This is by design.

The public `List<T>.GetEnumerator()` returns a struct enumerator. When you access `e3[i]`, you're getting back a copy of that struct, and when you then call the mutating `MoveNext` on it, you're mutating that copy, not the struct stored in the list.  Thus every time you access `e3[i]`, you're getting back a new copy that hasn't been pushed forward at all.

If you were to change:
```C#
Debug.Assert(e3[i].MoveNext());
```
to instead be:
```C#
var e = e3[i];
Debug.Assert(e.MoveNext());
e3[i] = e;
```
the assert would go away, as you'd then be updating the list with the mutated copy.

Your `e1` doesn't have this problem because, with an array, you're actually accessing the data stored in the array, not a copy returned from some get accessor method. And your `e2` doesn't have this problem because you called `IEnumerable<string>.GetEnumerator()`, and thus got back a boxed object containing the enumerator.
