### ISSUE TITLE
AspnetCore application tries to load Microsoft.DiaSymReader.Native.amd64.dll at runtime on centos linux

### ISSUE THREAD

**Issue by neyromant** [dotnet/runtime#92278]
### Description

I ran my aspnet core application on centos linux using the LL_DEBUG=libs command and found that it was unsuccessfully trying to load the Microsoft.DiaSymReader.Native.amd64.dll library. This does not lead to any visible consequences, but I would like to understand the reasons for this behavior.
After all, Microsoft.DiaSymReader.Native.amd64.dll is a windows-only library

Can someone tell me what is the reason for this behavior and how to avoid it?

Thanks in advance for any answer.

### Reproduction Steps

Build self contained asp.net core app, run it on linux centos by LL_DEBUG=libs ./my-app

### Expected behavior

An application does not try to load Microsoft.DiaSymReader.Native.amd64.dll on linux

### Actual behavior

Application tries to load Microsoft.DiaSymReader.Native.amd64.dll on linux

### Configuration

.net 7
centos 9
x64

**Comment by tommcdon** [comment]
@neyromant thanks for reporting this issue! I completely agree we do not need to probe for `Microsoft.DiaSymReader.Native.<arch>.dll` on Linux.  This is the code is used for displaying line numbers in exception callstacks.  Here is the code that attempts to load the Windows DLL:

https://github.com/dotnet/runtime/blob/034d27f4a9420e10601447d0385c88de9b4a2925/src/coreclr/vm/ceeload.cpp#L2262-L2273

And if `GetISymUnmanagedReaderNoThrow` returns NULL (as it should on Linux), we will fall back to loading portable PDB's which is supported on all platforms:

https://github.com/dotnet/runtime/blob/034d27f4a9420e10601447d0385c88de9b4a2925/src/coreclr/vm/debugdebugger.cpp#L570-L592

I feel we could #ifdef this code out on Linux as we do not support Windows PDB's on Linux.  Feel free to open a PR for review otherwise we will leave it on the backlog for .NET 9.

**Comment by neyromant** [comment]
@tommcdon thanks for you answer! I made a [draft pull request](https://github.com/dotnet/runtime/pull/92492). Could you take a look to see if I understood your idea correctly?

**Comment by jkotas** [comment]
Fixed by #92492

**Comment by neyromant** [comment]
@tommcdon @jkotas Please tell me,  is it possible to bring this fix to net7 or at least 8? What should I do for this?

**Comment by jkotas** [comment]
Backports require a strong justification. Why is this change important for you?

**Comment by neyromant** [comment]
@jkotas I'm concerned that it could be a potential local privilege escalation vulnerability via shared object hijaking.
This is just my guess. Unfortunately, I do not have sufficient knowledge in this area to provide any supporting facts.

**Comment by jkotas** [comment]
This case is “Scenario 2: Malicious binary planted in an untrusted application directory.” from https://msrc.microsoft.com/blog/2018/04/triaging-a-dll-planting-vulnerability/ . According to this guidance, a DLL planting issue that falls into this category is treated as Defense-in-Depth issue that will be considered for updates in future versions only.
