### ISSUE TITLE
Introduce default value for OptimizationPreference

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#92312]
The [documentation](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/optimizing) for `OptimizationPreference` mentions:

> By default, the compiler chooses a blended approach: generate fast code, but be mindful of the size of the application

However the default option can't be explicitly chosen, and you can only set `Size`, `Speed` or not set anything. It's like there are three options but one is not proposed.

Wouldn't it improve clarity to expose the "blended" option (name based on documentation for the sake of discussion) such that it's clearer what the choice is if not speed vs size? 

That would also mean that "default" (no value) could still behave like "Blended" but any future change to what that default behavior would not impact the output of the app if it's set to "Blended".

**Comment by MichalStrehovsky** [comment]
> Wouldn't it improve clarity to expose the "blended" option (name based on documentation for the sake of discussion) such that it's clearer what the choice is if not speed vs size?

I think the right name would be "None" (meaning: "I don't have a preference").

What's the scenario where someone would need to set a property to X what we already default to X? One can already do that today by doing `<OptimizationPreference></OptimizationPreference>`. It feels weird to do that. It _should_ feel weird to do that.

> That would also mean that "default" (no value) could still behave like "Blended" but any future change to what that default behavior would not impact the output of the app if it's set to "Blended".

I don't see likely that we'd introduce another possible value for this. PreferSize/PreferSpeed/NoPreference is what pretty much all native compilers converged to over the past decades. I'm not aware of any other high level preference one could set in any mainstream compilers.

**Comment by sebastienros** [comment]
> It should feel weird to do that.

I love the honesty 😁

> I don't see likely that we'd introduce another possible value for this. 

Not a new value, but maybe change what the default is, like make Speed be the default optimization if we think most customers actually care about this.

**Comment by MichalStrehovsky** [comment]
> Not a new value, but maybe change what the default is, like make Speed be the default optimization if we think most customers actually care about this.

If we ever do that, we can introduce the value then.

But I don't see it likely - Speed optimizations cause 5-10% regression in size and only a small improvement to TP. E.g. for the NativeAOT compiler itself it's a 6% size regression and 3% throughput improvement. 

The throughput improvement is generally not worth the size regression. It helps ASP.NET TP a lot more than 3%, but it is an outlier and there's a very specific reason for why it helps ASP.NET more. We'll likely be making the size of the speed-optimized even worse over time with more marginal improvements to TP.

We're more likely to shift individual optimizations between no-preference/size/speed depending on measurements, but I think no-preference is the right default.

**Comment by gfoidl** [comment]
> What's the scenario where someone would need to set a property to X what we already default to X?

Following scenario:
1. edit `.csproj` in Visual Studio
2. type `<OptimizationPreference` and close the `>`
3. now let's assume Intellisense has all the info including AOT settings
4. as options `PreferSize` and `PreferSpeed` pop up -- so a user can infer that there are only two of them and which is the default if not set?

If there would pop up also `None` (or `Default` or whatever) than that's more clear for an Intellisense-based workflow.

Note: I'm not arguing that this options should be added (as the comments above are very valid), just highlighting a scenario 😉.

**Comment by MichalStrehovsky** [comment]
The scenario where someone randomly tries things in IntelliSense without checking docs is a good way to [find out](https://www.youtube.com/watch?v=WntjAM2wqF8) many things, but we don't really optimize for it. Users who blindly try random things will more likely run into this not doing anything at all (like #91353) because it only means something for PublishAot when doing a publish and IntelliSense schema will never express that.

**Comment by gfoidl** [comment]
Sure, I totally agree. 
But (unfortunately) reality is that lots of people only rely on intellisense (and the ask questions in forums or here on why something is not working as (they) expected). So I believe we shouldn't blind ourselves from that situation, and provide Intellisense-hints where helpful and confusion can be avoided -- all in all resulting in better user experience.
Even if Intellisense would just provide a link to the docs that would be more helpful than showing nothing.

Now I fear this is becoming off-topic related to the title of this issue...

PS: nice video

**Comment by eerhardt** [comment]
> The throughput improvement is generally not worth the size regression.

I'm not sure that is true in many web apps. We are tracking 3 apps in https://aka.ms/aspnet/nativeaot/benchmarks

* Stage 1 - Minimal API hard-coded objects serialized to JSON
* Stage 1 Grpc - The same as above, only Grpc instead of Minimal API + JSON
* Stage 2 - Data from a postgres DB, validation, auth

With the current numbers:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/eerhardt/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/eerhardt/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">



Stage1 | CoreCLR | NativeAOT Default | NativeAOT Speed
-- | -- | -- | --
RPS (thousands) | 837 | 720 | 797
Memory (MB)** | 90 | 43 | 43
Disk Size (MB) | 95 | 10 | 10.6
Startup (ms) | 141 | 36 | 36
  |   |   |  
  |   |   |  
Stage1 Grpc | CoreCLR | NativeAOT Default | NativeAOT Speed
RPS (thousands) | 1,130 | 910 | 990
Memory (MB)** | 156 | 115 | 118
Disk Size (MB) | 95 | 12 | 12.8
Startup (ms) | 161 | 50 | 50
  |   |   |  
  |   |   |  
Stage2 | CoreCLR | NativeAOT Default | NativeAOT Speed
RPS (thousands) | 245 | 207 | 227
Memory (MB)** | 187 | 129 | 137
Disk Size (MB) | 100 | 22 | 24
Startup (ms) | 411 | 95 | 97



</body>

</html>

You can see the RPS regression in NativeAOT (Default) from CoreCLR is 14%, 20%, and 15% respectively. Using `Speed` optimization, the RPS regression is down to 5%, 12%, and 7% respectively. While the size regression from NativeAOT (Default) to NativeAOT (Speed) is 6%, 6%, and 10%.

If I was running these apps in a production environment, I would definitely make this tradeoff of size (a couple MB) in exchange for higher throughput.

**Comment by sebastienros** [comment]
I could not find any csproj property that has a meaning when it's empty. Only `<RestoreSources></RestoreSources>` but in this case it's a list so having it empty makes sense. Does anyone know of any?

**Comment by MichalStrehovsky** [comment]
> I could not find any csproj property that has a meaning when it's empty. Only `<RestoreSources></RestoreSources>` but in this case it's a list so having it empty makes sense. Does anyone know of any?

Just quickly scanning properties used by the C# compiler task, I see the [`CodePage`](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022#list-of-common-properties-and-parameters) property. The task has special behavior if `CodePage` is empty. There is no documented value of the property (or the associated command line argument) one could set to get the default behavior besides clearing the property.

**Comment by MichalPetryka** [comment]
> If I was running these apps in a production environment, I would definitely make this tradeoff of size (a couple MB) in exchange for higher throughput.

I feel like since .NET usually doesn't default to size savings like trimming, defaulting to Speed for AOT would make the most sense here.
