### ISSUE TITLE
(U)Int128 should provide correct op_IntegerDisivion and op_Disivion

### ISSUE THREAD

**Issue by LEI-Hongfaan** [dotnet/runtime#92461]
### Description

I noticed that the new (U)Int128 types only support op_Division, which performs integer division and returns a (U)Int128 result. However, many languages (such as VB.NET and Python/IronPython) distinguish between op_Division (accurate division, which usually returns a floating-point or fractional result) and op_IntegerDivision (integer division, which usually rounds towards zero) and prefer op_Division for '/' division expressions. In this case, the current design combination makes VB.NET very difficult to use the new (U)Int128 types without some problems.

### Reproduction Steps

```VB.NET
Imports System

Module Program

    Sub Main(args As String())
        Dim a = CType(3, Int128) / CType(2, Int128)
        Dim b = 3 / 2
        Console.WriteLine(a)
        Console.WriteLine(b)
    End Sub
End Module
```

### Expected behavior

Output
```
1.5
1.5
```

### Actual behavior

Output
```
1
1.5
```

### Other information

Considering that CLR is Common Language Runtime rather than CSharp Language Runtime, I'm concerned about the recent trend of making many improvements completely centered on C#, without considering the adaptability of other .NET languages (such as F#, VB.NET, Python/IronPython).

Additionally, considering the closely related checked/unchecked operators, I think the best solution is to prioritize checked operators and consider whether op_Xxx, op_CheckedXxx, op_UncheckedXxx are implemented when looking for operators. This would allow types that do not support checked/unchecked operators to continue using the original checked design similar to BigInteger type, make VB.NET easier, and also be better for program correctness.

**Comment by huoyaoyuan** [comment]
> However, many languages (such as VB.NET and Python/IronPython) distinguish between op_Division (accurate division, which usually returns a floating-point or fractional result)

It's not the case for C# and IL itself. All the integer types have only integer division operators. It's also the case for C++/Rust etc.

It's inconsistent in VB.NET for compatibility with VB 6. For Int32/Int64, op_Division is not consistent with `/` either.

**Comment by LEI-Hongfaan** [comment]
This is not just a VB.NET issue, as I said before, all languages that distinguish between two kinds of division are also affected. So, I think it would be better for the whole ecosystem to name the C# '/' operator in integer contexts as op_IntegerDivision according to its actual meaning. Or, at least, let me specify the method name of the C# '/' operator by an attribute, like IndexerNameAttribute and DefaultMemberAttribute do for indexers. This way, other languages can consume these new types smoothly without changing the existing conventions. (For example, here I can compile the method name of the (U)Int128 '/' operator as op_IntegerDivision) And it would also be easier to write libraries for other languages in C#.

**Comment by MichalPetryka** [comment]
![image](https://github.com/dotnet/runtime/assets/35800402/485a9387-c19e-42f1-904b-e7705cae4df8)
As per ECMA 335, `op_Division` corresponds to C++-like division, which is integer based for integers.

**Comment by tannergooding** [comment]
Doing this would violate the general framework design guidelines which exist and were designed to explicitly account to consider cross language scenarios.

We typically follow the principle of `T in, T out` and any kind of lossy conversion should not be implicit. Thus, a division operation for `Int128` that returned a `double` would be explicitly disallowed as both involving an implicit change in data type and simultaneous loss of data.

This loss of precision can be seen in VB.NET, for example, by looking at `(9007199254740993 / 9007199254740992).ToString("G99")` where the result printed is `1` but where the nearest representable `double` would actually be `1.0000000000000001110223024625157`.

This is because VB.NET implements such functionality for the primitive types by emulating it using `(double)x / (double)y`

If another language, such as VB.NET, wanted to add customized support to support `float = integer / integer`, they could do so using the baseline functionality. But it would not be something we aim to provide out of the box as part of the BCL.

**Comment by tannergooding** [comment]
>  This way, other languages can consume these new types smoothly without changing the existing conventions.

You can emulate the functionality by emitting a static method named `op_IntegerDivision` for your own types and attributing it with `[System.Runtime.CompilerServices.SpecialName]` on your own types.

The BCL would not add such functionality to it's own types as it would be a breaking change and cause silent, implicit loss of data.

> think it would be better for the whole ecosystem to name the C# '/' operator in integer contexts as op_IntegerDivision according

Notably, this is a VB.NET specific convention and isn't actually spec'd by the general framework/runtime. It would also be a breaking change to make now, some 20 years into `op_Division` being defined for user-defined types at the binary level.

The goal of the BCL isn't to support the functionality available to all languages; and in fact that is impossible since many languages may deviate on core points or may not follow the Framework Design Guidelines or the runtime spec that indicates what particular IL names are "intended" to be used for.

Rather, the BCL is meant to provide a set of common and baseline functionality that can be widely used across many languages.

There are many general C# features we don't use in the BCL either, because they can have hidden implications to the public API surface we ship. We likewise don't always support all possible C# features on all types. We support what is necessary, what is actually needed, and what allows most APIs to be generally used by a wide variety of languages safely.

All languages, including C#, F#, VB.NET, etc. Need to take into account the core runtime spec, intended usage of well-known IL names, the general framework design guidelines, interoperability concerns, and more when designing their own features. This is required to ensure that they can be as widely adopted and used as intended.

**Comment by LEI-Hongfaan** [comment]
Thank you for your comments and the information provided. I understand that it might be too late to change the specification or BCL now.

Regarding the rounding error of the operation, I don't think it's a problem. Because it's the same in Python, and people don't have much complaints. Maybe I should use the word fraction division to avoid ambiguity. (Although not closely related to the topic, we also allow Int64 to be implicitly converted to double, which also loses precision.)

But I think it's very useful to allow library authors to specify the method name of the '/' operator for other custom types by an attribute. This is also feasible, because we do the same for indexers.

Please consider this scenario: I implemented a numeric type (such as: (U)Int128) in C#. And, as you suggested, I added the op_IntegerDivision method. Of course, we hope that this type can be used by both C# and VB.NET.
But there will be a problem right away, if I define fraction division as op_Division, then C# or C++/CLI will call it incorrectly (instead of calling integer division). On the other hand, if I define integer division as op_Division, then VB.NET and Python will call it incorrectly (instead of calling fraction division). My current approach is not to define op_Division, and to provide static methods Division and some other static methods to represent fraction division. The disadvantage of this approach is obvious, I can't use the '/' operator in C# or C++/CLI.

Therefore, if I can specify the method name of the '/' operator, I can compile the '/' operator (here refers to integer division) into the op_IntegerDivision method, and provide op_Division to represent fraction division.

This solution does not violate ECMA-335. Compiling the '/' operator (here refers to integer division) into the op_IntegerDivision method does not violate the usage rules of op_Division. Moreover, the annotation of C++ operators is informative, mainly saying the corresponding operator symbols. Finally, excluding the meaning of fraction division is also unreasonable, especially when providing libraries for other languages.

In addition, I think it might be a good idea to modify or add some APIs for Generic Math. For example, if there is a way to determine whether a type is an integer, other languages and toolchains that distinguish between two types of division should be able to find the correct division according to certain rules. Adding `IIntegerDivisionOperators` and `IFractionDivisionOperators` interfaces might be better. This is also helpful for writing generic algorithms.

This problem also affects CPython (via pythonnet), IronPython and countless other .NET languages and tools. Although many of them are not as popular as C#, they also have many users and fans. Let's imagine that compared with countless adaptations and separate conventions, it is obviously more manageable and efficient to solve this problem here. Because if we don't do this, every time we add a new BCL integer type, we need to adapt it by hard coding and special handling. Also, there is no good way to deal with user-defined integer types consistently.

This is the result of CPython (via pythonnet)
```
>>> from pythonnet import load
>>> load("coreclr", runtime_config="net7.0.runtimeconfig.json")
>>> from System import Int64
>>> from System import Int128
>>> str(3 / 2)
'1.5'
>>> str(Int64.Parse("3") / Int64.Parse("2"))
'1.5'
>>> str(Int128.Parse("3") / Int128.Parse("2"))
'1'
```
This is the result of IronPython
```
IronPython 3.4.1 (3.4.1.1000)
[.NETCoreApp,Version=v6.0 on .NET 7.0.11 (64-bit)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> from System import Int64
>>> from System import Int128
>>> str(3 / 2)
'1.5'
>>> str(Int64.Parse("3") / Int64.Parse("2"))
'1.5'
>>> str(Int128.Parse("3") / Int128.Parse("2"))
'1'
```

**Comment by jeffhandley** [comment]
Per the discussion above, we aren't planning to add this functionality to the core libraries. Thank you for the idea and discussion, @LEI-Hongfaan.
