### ISSUE TITLE
Incompatible values of the AssemblyVersion attribute in System.Security.Cryptography.Xml 7.0.1

### ISSUE THREAD

**Issue by rafal-zieba** [dotnet/runtime#92486]
### Description

There are four versions of the System.Security.Cryptography.Xml 7.0.1 package
- netstandard2.0
- net6.0
- net7.0
- net462

The first three have `[assembly: AssemblyVersion("7.0.0.0")]` while the net462 one has `[assembly: AssemblyVersion("7.0.0.1")]`

If there is a reference from .net48 through a netstandard2.0 package to System.Security.Cryptography.Xml 7.0.1 the code in netstandard2.0 package wants `[assembly: AssemblyVersion("7.0.0.0")]` and gets `[assembly: AssemblyVersion("7.0.0.1")]`

### Reproduction Steps

Net48 project referencing netstandard2.0 project referencing System.Security.Cryptography.Xml 7.0.1 package

### Expected behavior

All AssemblyVersion values should be the same

### Actual behavior

AssemblyVersion in net462 version of the package is different than in netstandard2.0 version of the package causing a fatal error

### Known Workarounds

Do not use netstandard2.0 version
Use multitargeting (<TargetFrameworks>net48;net7.0</TargetFrameworks)

### Configuration

net48 and net6.0 with common libraries written targeting netstandard2.0

**Comment by rafal-zieba** [comment]
There is the same problem with System.Security.Cryptography.Xml 7.0.0 and System.Security.Cryptography.Xml 6.0.1
Version 5.0.0 is ok

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
This is expected and by design.  We version the NETFramework assemblies so that they are guaranteed a unique version should someone install to the GAC.  This is especially important in servicing so that applications can guarantee they receive a serviced version.  

We must not version the netstandard2.0 nor NET6/NET7 versions because this assembly also ships in the shared framework which is updated in place.

Consuming a newer assembly version than what a binary was built with is completely normal.  The same thing happens when updating packages.  So long as the version increases across compatible relationships (newer assembly version, newer framework version, netstandard -> netstandard-compatible-framework) then the version increase is acceptable.

When using NuGet package on .NETFramework you **must** configure your project to use bindingRedirects in order to allow for these newer versions.  In most cases the build [will do this for you](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection).
