### ISSUE TITLE
8.0 Performance regression

### ISSUE THREAD

**Issue by johnnygiter** [dotnet/runtime#92530]
Code below runs about 3-5% slower on both .net 8 RC1 and on 7.x - than on 6.x  (all mentioned major releases in latest official builds tested as for today)

```
using System;
using System.Linq;

namespace csharpprime
{
    public class Program
    {
        public const int Limit = 12000000;

        public static void Main(string[] args)
        {
            var startTime = Environment.TickCount;
            var serial = Serial(1, Limit);
            var serialMs = Environment.TickCount - startTime;

            startTime = Environment.TickCount;
            var parallel = Parallel(1, Limit);
            var parallelMs = Environment.TickCount - startTime;

            Console.WriteLine($"{serial}({serialMs}), {parallel}({parallelMs})");
        }

        public static bool IsPrime(int number)
        {
            if (number <= 1)
                return false;

            var end = (int)Math.Floor(Math.Sqrt(number));
            for (var index = 2; index <= end; index++)
                if (number % index == 0)
                    return false;

            return true;
        }

        public static int Serial(int start, int end) =>
            Enumerable.Range(start, end - start)
                      .Count(IsPrime);

        public static int Parallel(int start, int end) =>
            Enumerable.Range(start, end - start)
                      .AsParallel()
                      .Count(IsPrime);
    }
}
```

**Comment by huoyaoyuan** [comment]
`Environment.TickCount` or manual `Stopwatch` are not reliable for performance measurement. You should use [BenchmarkDotnet](https://benchmarkdotnet.org) to get reliable result.

With the following benchmark code:
```csharp
    public class Program
    {
        static void Main(string[] args)
        {
            BenchmarkSwitcher
                .FromAssembly(typeof(Program).Assembly)
                .Run(args);
        }

        [Benchmark]
        public bool Bench()
        {
            bool result = false;

            for (int i = 0; i < 10000; i++)
                result ^= IsPrime(i);

            return result;
        }

        public static bool IsPrime(int number)
        {
            if (number <= 1)
                return false;

            var end = (int)Math.Floor(Math.Sqrt(number));
            for (var index = 2; index <= end; index++)
                if (number % index == 0)
                    return false;

            return true;
        }
    }
```

I'm getting this result:

| Method |  Runtime |     Mean |   Error |  StdDev | Ratio |
|------- |--------- |---------:|--------:|--------:|------:|
|  Bench | .NET 6.0 | 148.2 us | 1.20 us | 0.93 us |  1.00 |
|  Bench | .NET 7.0 | 149.5 us | 2.30 us | 2.15 us |  1.01 |
|  Bench | .NET 8.0 | 144.2 us | 0.56 us | 0.53 us |  0.97 |

The performances are about the same.

**Comment by johnnygiter** [comment]
@huoyaoyuan 
Are  you sure your code in benchmark equals to posted? I don't think so...

**Comment by gfoidl** [comment]
In the recent .NET release a lot changed to JIT compilation. As keyword: tiered compilation.
Put in simple words: this means that for faster startup (among other things) the code is compiled with little optimizations and when a method is called often enough it's recompiled with more optimizations to get good perf in the steady state.

So for benchmarking Stopwatch, etc. isn't suitable. You should use a tool like BenchmarkDotnet (see comment above) which takes this into account.

**Comment by johnnygiter** [comment]
@gfoidl 
Benchmarked(fully) unlike to removed paraller part posted by @huoyaoyuan :
Paraller shows similar results to stopwatch actually
Verdict: .NET 8.0.0 is there **over 17% SLOWER**, definetely performance regression, like in topic.


DefaultJob : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2

| Method            | Mean     | Error   | StdDev  |
|------------------ |---------:|--------:|--------:|
| SerialBenchmark   | 865.2 ms | 0.12 ms | 0.10 ms |
| ParallelBenchmark | 168.2 ms | 3.27 ms | 3.06 ms |



DefaultJob : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT AVX2


| Method            | Mean     | Error   | StdDev  |
|------------------ |---------:|--------:|--------:|
| SerialBenchmark   | 869.9 ms | 0.20 ms | 0.18 ms |
| ParallelBenchmark | 143.0 ms | 0.30 ms | 0.28 ms |

**Comment by T1000v2** [comment]
I can confirm at my end paraller version runs on .NET 8RC1 18% slower, hopefully it's quirk of release candidate stage.

**Comment by stephentoub** [comment]
The difference here is purely because the `IEnumerable<int>` returned from `Enumerable.Range` in .NET 8 also implements `IList<int>` whereas it didn't in .NET 7.

PLINQ, which hasn't changed meaningfully for .NET 8, will now see that the source is `IList<int>` and will thus that interface (rather than an `IEnumerator<int>` retrieved from it) to partition the input range rather than needing to enumerate the source, as it can have its partitions access that `IList<int>` without the same synchronization with which it needs to access an arbitrary `IEnumerator<int>`. You can see the impact that synchronization has just by using a smaller workload such that the overheads associated with the parallelism and partitioning are proportionally higher, e.g.
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Tests).Assembly).Run(args);

[HideColumns("start", "end", "Error", "StdDev")]
[MemoryDiagnoser]
public partial class Tests
{
    [Benchmark]
    [Arguments(1, 12_000_000)]
    public int Parallel(int start, int end)
    {
        return Enumerable.Range(start, end - start)
                         .AsParallel()
                         .Count(IsPrime);
    }

    public static bool IsPrime(int number)
    {
        return number % 2 == 0;
    }
}
```

| Method   | Runtime  | Mean     | Ratio | Allocated | Alloc Ratio |
|--------- |--------- |---------:|------:|----------:|------------:|
| Parallel | .NET 7.0 | 73.03 ms |  1.00 |  15.23 KB |        1.00 |
| Parallel | .NET 8.0 | 12.80 ms |  0.18 |   8.18 KB |        0.54 |

But as the `IsPrime` workload is non-uniform (the larger the index, the larger the amount of time this IsPrime workload will require), that change in partitioning can result in some of the threads involved in the computation getting slightly more work than other threads.  You can see this just by adding a `.Select(i => i)` after the `Range`, or by using your own `Range` iterator that doesn't implement `IList<int>` (e.g. `private static IEnumerable<int> Range(int start, int count) { for (int i = start; i < start + count; i++) yield return i; }`), or by wrapping the `Enumerable.Range` in a call to `Partitioner.Create` (e.g. `Partitioner.Create(Enumerable.Range(start, end - start + 1))`), all of which have the effect of hiding that `IList<int>` implementation from PLINQ, and all of which should show .NET 8 and .NET 7 on par (I typically see .NET 8 then a bit faster).
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Tests).Assembly).Run(args);

[HideColumns("start", "end", "Error", "StdDev")]
[MemoryDiagnoser]
public partial class Tests
{
    [Benchmark]
    [Arguments(1, 12_000_000)]
    public int Parallel(int start, int end)
    {
        return Enumerable.Range(start, end - start).Select(i => i)
                         .AsParallel()
                         .Count(IsPrime);
    }

    public static bool IsPrime(int number)
    {
        if (number <= 1)
            return false;

        var end = (int)Math.Floor(Math.Sqrt(number));
        for (var index = 2; index <= end; index++)
            if (number % index == 0)
                return false;

        return true;
    }
}
```

| Method   | Runtime  | Mean     | Ratio | Allocated | Alloc Ratio |
|--------- |--------- |---------:|------:|----------:|------------:|
| Parallel | .NET 7.0 | 588.7 ms |  1.00 |   16.5 KB |        1.00 |
| Parallel | .NET 8.0 | 565.4 ms |  0.96 |  15.79 KB |        0.96 |

You can see PLINQ with .NET 7 taking a similar amount of time if you change the benchmark to instead do `return ParallelEnumerable.Range(start, end - start).Count(IsPrime);`, as then just as when `Enumerable.Range` in .NET 8 returns something indexible, PLINQ in .NET 7 will similarly change its partitioning scheme as it no longer needs to do synchronization to access an enumerator, and you should see this taking as long or longer than when using Enumerable.Range.AsParallel in .NET 8.

Given all that, this is all by design, even if a little surprising for this or that case. This is the nature of partitioning in these kinds of parallel systems; choices in how partitioning is handled can lead to swings in performance based on the data source and on the work being performed over the data, sometimes slightly for worse and sometimes for the better.

Thanks.
