### ISSUE TITLE
When a package has native assets for multiple rids the host ignores assets for base rids

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#92706]
When a package has native assets for a base rid (like `unix`) and a more specific rid (like `linux-x64`), then the host ends up ignoring the assets for the base rid.

These are the relevant lines in the host trace output:

```
Filtering RID assets for lib/1.0.0
  Matched RID linux-x64 for native assets
    Removing unix assets
```

My expectation was for the host to prefer the more specific assets (`linux-x64`) but still consider the base rid assets (`unix`) as a fallback.

cc @elinor-fung

**Comment by elinor-fung** [comment]
I think this is expected. The host uses the most specific RID native (or managed) assets for the package - and stops looking at other RIDs for native assets, so assets in that package under less specific RIDs aren't used. It matches the NuGet restore behaviour when targeting a specific RID (so building an app targeting `linux-x64` referencing a package with native assets under both `linux-x64` and `unix` will only include those under `linux-x64`). This was also how the RID fallback chain was handled before moving to portable RIDs and we didn't set out to change that.

I could see how a package author might want some native `asset1` under `linux-x64` and `asset2` under `unix-x64` (for linux and osx, say) rather than having `asset2` under the most specific RID as well. That would be a significant shift in existing behaviour though - I don't know that we've had much/any push to change this.

**Comment by tmds** [comment]
Thank you for clarifying.

It seems this is working as intended.
