### ISSUE TITLE
JsonException error messages include type information

### ISSUE THREAD

**Issue by giulianob** [dotnet/runtime#92776]
Hello,

The exceptions thrown by System.Text.Json sometimes include type information. For example, this is the exception thrown when using `[JsonRequired]`:
> JSON deserialization for type 'MyNamespace.MyType' was missing required properties, including the following: Name

This is problematic when we'd like to return which properties are missing in a response as it exposes internal type information that is not important to the user. The `JsonException` does not contain enough information in its properties to craft a custom message either (e.g. the missing properties are only available in the message).

I'd like an option that allows either disabling including type information in the message, the ability to customize these error messages, or enough information in the other properties of `JsonException` that allows us to craft our own messages.

**Comment by eiriktsarpalis** [comment]
>  it exposes internal type information that is not important to the user.

> I'd like an option that allows either disabling including type information in the message, the ability to customize these error messages, or enough information in the other properties of JsonException that allows us to craft our own messages.

I don't think that would be possible in the general case, depending on the type of exception being thrown there is always the possibility of internal implementation details being leaked. It is also the reason why generally speaking surfacing exceptions to users is not recommended since it could be disclosing security sensitive information to potential attackers. If you're looking to provide request validation feedback to the user, I would [recommend using validation](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0) instead of relying on the serializer.
