### ISSUE TITLE
gRPC client failed to establish TLS connection to grpc service

### ISSUE THREAD

**Issue by khteh** [dotnet/runtime#92788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```c#
var httpHandler = new HttpClientHandler
{
    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
    //ServerCertificateCustomValidationCallback = (request, cert, chain, errors) => { return true; },
    SslProtocols = SslProtocols.Tls13
};
// Return `true` to allow certificates that are untrusted/invalid
//AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
using var channel = GrpcChannel.ForAddress(_grpcConfig.Endpoint, new GrpcChannelOptions { HttpHandler = httpHandler });
MyServiceClient client = new MyServiceClient(channel);
response = await client.MyRpcAsync(request);
```

### Expected Behavior

Successfully complete gRPC call to https endpoint.

### Steps To Reproduce

```c#
syntax = "proto3";
option csharp_namespace = "MyService.Ping";
package Ping;
import "google/protobuf/empty.proto";
service SvcPing {
  rpc Ping (google.protobuf.Empty) returns (Pong);
}

message Pong {
  string message = 1;
}
```
Deploy the gRPC service to production behind load balancer.

Create a console application and invoke the gRPC:
```
$ export DOTNET_ENVIRONMENT=Production&& ./Console ping
Environment: Production, server: https://mydomain.com
Press ENTER when the gRPC server @https://mydomain.com is ready

Exception! Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed, see inner exception. SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_ZERO_RETURN.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.")
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_ZERO_RETURN.
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions, SelectClientCertificate clientCertificateSelectionCallback)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   --- End of inner exception stack trace ---
   at Program.PingCommand() in /usr/src/myapp/Program.cs:line 238
```
### Exceptions (if any)

```
Exception! Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed, see inner exception. SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_ZERO_RETURN.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.")
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_ZERO_RETURN.
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions, SelectClientCertificate clientCertificateSelectionCallback)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   --- End of inner exception stack trace ---
```

### .NET Version

7.0.111

**Comment by wfurt** [comment]
I don't think the `SSL_ERROR_ZERO_RETURN` comes from validation. It would be useful to get packet captures @khteh or set up small runable repro.

**Comment by khteh** [comment]
Updated post.

**Comment by khteh** [comment]
> The error is the same if you call HttpClient directly instead of the gRPC APIs, correct?

What do you mean? Any example?

**Comment by rzikm** [comment]
I think we will not be able to do anything without packet captures, or a self-contained repro. Can you share it as a runnable project? Maybe even with docker file if the repro requires both client and server.

**Comment by khteh** [comment]
WTF is the laziness shown by you!!?! I have shared the code here, both server and client, and it's a private repo! Don't you get it that it's server code deployed behind the load balancer and client trying to access it?

**Comment by karelz** [comment]
@khteh the above comment violated our [Code of Conduct](https://github.com/dotnet/runtime/blob/main/CODE-OF-CONDUCT.md). Please let's keep things professional. Attacking people/teams is not going to help with collaboration (attacked people are less likely to engage and help the attacker).

I feel that you are frustrated, although I am not very clear why. Let me explain some background that might help you understand our general approach:
We do not have infinite amount of experts nor time, therefore we have to prioritize:
- For suspicious/weird/one-off/hard-to-reproduce problems, we often ask for small minimal repros, or additional logs or others thing that might help us root cause problems. In certain cases we even have to ask reporters to help us debug it on their machines.
- For problems that seem to impact wider set of customers we try to be more proactive.

We ask for additional information when it is not super-simple for us to reproduce, or when it looks like one machine problem (which is your case - because this is the first report on 7.0 since its release a year ago). Debugging and trying to reproduce one-machine problems is very costly for us and we do not scale to do that.
In general, we expect that creation of minimal repro is the first thing that every developer does / tries to do when reporting a problem. We do it as well when we report bug against lower layers (like the OS, OpenSSL, msquic and other components we depend on). Surprisingly often during minimizing exercise one can discover that the problem is in user code, another higher-level library, or even machine/environment configuration, etc. It might not be the case in this issue, but sadly we do not have an oracle to tell us for sure (or even with decent probability that it is real bug, not an environmental/configuration problem).

Of course, there are cases when it is not possible to create minimal repro (e.g. for stress issues that happen only occasionally) - in such cases, unless the problem is clear, we often need more details like logs. In rare cases even that is rather hard to get and then we have to get creative together with the reporter.

Hopefully the above explains enough our motivation. We ARE trying to help here, but we first need something actionable. Right now this report is not actionable for us, that's why we are offering SUGGESTIONS what MIGHT make it ACTIONABLE for us. Does it make sense?

**Comment by khteh** [comment]
> because this is the first report on 7.0 since its release a year ago

Are you sure!?! https://github.com/dotnet/aspnetcore/issues/47702 What have you done since this issue was opened in April to resolve it? If it is a retry issue with AWS, I should have at least succeeded one time but I never!

Reproduction? Here you go!

https://github.com/khteh/AspNetCoreWebApi/blob/master/src/Web.Api/Services/PingService.cs
https://github.com/khteh/AspNetCoreWebApi/blob/master/test/Console/Program.cs

**Comment by rzikm** [comment]
> Reproduction? Here you go!

Not sure where to begin
- The repro is not self-contained (it depends on a certificate being manually generated to /tmp/localhost.pfx)
- There seems to be a dockerfile, but it does not build the necessary project, only consumes binaries built from a separate step
- The build.sh script is not helpful either since it just runs docker build and push
- Web.Api depends on Redis running somewhere, there is no docker-compose file to set up all relevant dependencies, requiring more manual work to get repro running (none of which are mentioned in the Readme)
- After commenting out use of Redis (and ElasticSearch), we finally get to a point where the Web.Api starts via provided Dockerfile
- The issue does not reproduce.

All in all, 2 hours spent and we are not single a step closer to identifying the issue.

To move this forward, the issue you mentioned suggests that this may be specific to AWS, and not necessarily issue of .NET, I suggest that you either
- provide us with packet captures when the problem occurs, as wfurt asked 4 days ago
- setup a public endpoint which can be reached by the console app to trigger the exception.

**Comment by karelz** [comment]
> Are you sure!?! https://github.com/dotnet/aspnetcore/issues/47702 What have you done since this issue was opened in April to resolve it? If it is a retry issue with AWS, I should have at least succeeded one time but I never!

That issue has been in another repo, which our team does not monitor. When we don't know about a problem, then nothing is happening ...
Moreover, the issue you linked was filed by you as well and there was no reply to the suggestion that AWS addressed it by retries. If it didn't help, why wait 4+ months to say so? Nobody expected it is still a problem.

> If it is a retry issue with AWS, I should have at least succeeded one time but I never!

That was not explicitly communicated. Also, it might be good to bring it to the attention of AWS folks - it may be problem with their SDK, or their infrastructure. Did you try to follow up with them about that?
As @rzikm mentioned above, a packet capture might be able to pin point for you if it is a problem on client side, or with network infrastructure on the way to the server.

**Comment by khteh** [comment]
I can confirm that this is 100% the problem with your `gRPC` client. Postman `ping` the service successfully.

> it may be problem with their SDK, or their infrastructure

What SDK are you talking about? It's all Microsoft .Net Core code here!

And being a public cloud provider, specifically the load balancer in this case, which handles application-agnostic traffic, would you lightly settles with just "retry" as the solution?

> which our team does not monitor.
How would I know? Does your "small team" work in sub-optimized silos?

**Comment by karelz** [comment]
> Postman `ping` the service successfully.

That is valuable information, thank you!

> I can confirm that this is 100% the problem with your `gRPC` client.

Are you saying you are not using any other code (like AWS SDK, Redis, etc.) in your application? All these layers might interact and cause the problem.
Also note, that gRPC is another set of experts, so even if from outside it might look like Microsoft, there may be several layers involved and identifying the right layer (e.g. gRPC vs. Networking vs. OS) is important to pull in the right experts.

> What SDK are you talking about? It's all Microsoft .Net Core code here!

AWS SDK. Or is it not involved at all?
AWS SDK is not owned by Microsoft. It just happens to be for .NET, incl. C#.

> And being a public cloud provider, specifically the load balancer in this case, which handles application-agnostic traffic, would you lightly settles with just "retry" as the solution?

I think the only "retry" I saw was from AWS SDK, which is owned and driven by Amazon. Yes, they are also public Cloud provider, but I can't speak on their behalf, goals, or expectations as Microsoft employee.

> How would I know?

You can notice different repos, and different set of people who transferred the issue here - see above comment https://github.com/dotnet/runtime/issues/92788#issuecomment-1739790580 ... which wasn't answered yet I think.

> Does your "small team" work in sub-optimized silos?

This is passive aggressive comment. Please refrain from those and keep things professional.
Just a reminder that attacking people who are trying to help you will NOT help with resolution, or speed it up. (Just imagine yourself being on the receiving side -- how would you feel?)
We are more than happy to answer valid questions.

If you want to understand more, I recommend you to try monitor one larger repo (e.g. aspnet or dotnet/runtime) for a week, to see if you can keep up with everything, read everything, not miss anything. On the larger team I know only about couple of people who can lightly check on everything, because it is A LOT of messages each day (it used to take me 3-6 hours each day to do just that - monitoring and some answering). That's why we have repos split into expertise areas - see https://github.com/dotnet/runtime/blob/main/docs/area-owners.md ... this is specialization and focus, not silo. Again, try to imagine being on the other side, maintaining as large project as .NET itself (or rather, its parts).
