### ISSUE TITLE
Request to backport JsonDocument thread safety fix to System.Text.Json v7 (PR#76716)

### ISSUE THREAD

**Issue by jagdeepsingal** [dotnet/runtime#92808]
Hi,

This is to request for backport JsonDocument thread safety fix to System.Text.Json v7. This is the relevant PR: https://github.com/dotnet/runtime/pull/76716/files.

Thanks, and Best Regards,
Jagdeep Singal

**Comment by danmoseley** [comment]
@jagdeepsingal could you say more about why you want it ported? How is it affecting you?

**Comment by eiriktsarpalis** [comment]
@jagdeepsingal System.Text.Json v8 is due to be released in November, which is probably sooner than the next servicing release that could accommodate such a backport. Using the latest STJ doesn't necessitate updating to the latest version of .NET, you can just consume the latest [NuGet package](https://www.nuget.org/packages/System.Text.Json). We've already released the [RC1 version](https://www.nuget.org/packages/System.Text.Json/8.0.0-rc.1.23419.4) so you can try it out today.

**Comment by teo-tsirpanis** [comment]
Closing, the issue has been backported to .NET 7 and 6.
