### ISSUE TITLE
Double.IsNegative returns true for Double.NaN

### ISSUE THREAD

**Issue by ErzengelLichtes** [dotnet/runtime#92834]
### Description

`Double.NaN` represents "not a number", which should be neither positive nor negative. However, asking if NaN is negative via `Double.IsNegative` returns `true`. This is inconsistent with comparing against 0, which returns `false`.

### Reproduction Steps

```
var test = Double.NaN;
Console.WriteLine($"Is {test} negative? {Double.IsNegative(test)}");
Console.WriteLine($"Is {test} less than 0? {test < 0}");
```

### Expected behavior

"Is NaN negative? false"
"Is NaN less than 0? false"

### Actual behavior

"Is NaN negative? true"
"Is NaN less than 0? false"

### Known Workarounds

If you can bind to `IComparisonOperators` instead of (or in addition to) `INumberBase`, use `<0` instead of `IsNegative`.

### Configuration

Target Framework: .NET 7.0
Frameworks: Microsoft.NETCore.App 7.0.10

**Comment by tannergooding** [comment]
This is by design and per the IEEE 754 specification.

All floating-point values, including NaN, having a sign. `IsNegative` reports the value of that sign.

There exist four types of `NaN` values:
* `+QNaN`
* `-QNaN`
* `+SNaN`
* `-SNaN`

Among these `NaN` values, there can also exist a "payload" that exists in the significand portion of the underlying bit representation, thus allowing several million different `NaN` for each type, even for `float32`.

For historical reasons, `NaN` defaults to `-QNaN` and thus will report itself as negative. While `NaN` constructed by other means will report accurately report their sign bits as well.

**Comment by tannergooding** [comment]
Likewise, per the spec, comparisons do not strictly report whether a value is "negative" or not. For example, there exists `-0.0` which will also report `false` for `x < 0`.

`IsNegative` exists as an explicit API to get the value of the sign irrespective of comparison or other rules that may exist for the domain.

Additionally, `IsNegative` being `false` does not strictly mean `IsPositive` will be true. There exist, for example, `Complex` numbers which are neither due to having both positive and negative components.

**Comment by ErzengelLichtes** [comment]
I expected that NaN would be both IsPositive == false and IsNegative == false per the documentation of IsNegative, which states "Determines if a value represents a negative real number." Since NaN is not a real number, I expected it to be false. The documentation is poorly worded and the function poorly named if it is by design.

**Comment by tannergooding** [comment]
> The documentation of IsNegative states "Determines if a value represents a negative real number."

Yes, the documentation for `INumberBase<T>.IsNegative` could indeed be improved and PRs are welcome. The documentation for `double.IsNegative` does not have this issue and avoids the use of the word "number" and the API itself has been around since .NET Core 2.1.

The intent of `INumberBase<T>.IsNegative` was to be compatible with the existing definition that `double`/`float` has. It was also meant to be compatible with the concept of `Complex` numbers, which may not have a singular sign definition due to the domain they exist in. In an effort to ensure clarity on one part of the documentation, the nuance on the other aspect was lost.

> The "by design" should be in the IBinaryFloatingPointIeee754 interface, not INumberBase. INumberBase should work logically, not be affected by nuances of implementation.

One cannot overload based on generic constraints in .NET and so a person wanting to work with "any number type" needs to be able to account for different number concepts from the base interface. Thus, `INumberBase<T>` is the correct location to expose concepts such as `IsNaN`, `IsNormal`, `IsOddInteger`, `IsRealNumber`, `IsFinite`, and so on. This allows a method constrained `where T : INumberBase<T>` to correctly account for all the different nuances and still have the correct outcome.

It was explicitly designed this way to ensure that developers could achieve success and the documentation was attempted to ensure various nuances were covered, such as `IsX()` being `false` not implying that a related method `IsY()` would be `true`. `NaN` being missed in the `IsNegative` xml summary was a minor and unintentional side effect that we can rectify by updating the documentation.

These nuances are exposed here because not considering them leads to user error and bugs when working with numbers in the abstract sense. Because a user believing that `x < 0` means `IsNegative` is problematic for many number types across many domains and the nuance needs to be surfaced. The same would be true of a user believe that `0` has no sign or whether `0` has a sign or not. All these concepts must be defined at the base level to ensure support for all manner of number types, including things like `Not a Number`

**Comment by ErzengelLichtes** [comment]
Additional work around: IsRealNumber(test) && IsNegative(test) to act the way the documentation describes.
