### ISSUE TITLE
IParsable<'T> is not referentially transparent for DateTimeOffset with InvariantCulture

### ISSUE THREAD

**Issue by gusty** [dotnet/runtime#92851]
### Description

Despite sending `CultureInfo.InvariantCulture` it will default to machine locals in case the offset is not specified in the source string.

### Reproduction Steps

```FSharp
open System
open System.Globalization

let parse<'T when 'T :> IParsable<'T>> (x: string) : 'T = 'T.Parse (x, CultureInfo.InvariantCulture)
let dateTimeOffset = parse<DateTimeOffset> "2023-09-12T00:20:13"
```

### Expected behavior

`val dateTimeOffset: DateTimeOffset = 12/09/2023 00:20:13 +00:00`

### Actual behavior

`val dateTimeOffset: DateTimeOffset = 12/09/2023 00:20:13 +02:00`  // My local machine is in CEST

### Regression?

No

### Known Workarounds

I can't think of any workaround.

### Configuration

```
Microsoft (R) F# Interactive version 12.8.0.0 for F# 8.0
```

### Other information

The cause is evident [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/DateTimeOffset.cs#L1099):

This is sending always `DateTimeStyles.None` even if the culture is Invariant.

The fix is to send `DateTimeStyles.AssumeUniversal` always, or at least when Invariant is selected, otherwise it's not fully invariant.

**Comment by danmoseley** [comment]
I see you marked regression:no. What versions did you try?

**Comment by gusty** [comment]
Yes, I marked no as I don't think it's a regression. 
I tested it in .net8 the version I specified there.

**Comment by tarekgh** [comment]
This is by design. All default parsing is using the default time zone. This has nothing if you are passing Invariant or any other formatting provider. 
If you want to force specific behavior, try to use Parse/TryParse which can take `DateTimeStyles` parameter. Let me know if you still have any questions.

**Comment by gusty** [comment]
Well, then let tell you this is a terrible design and I'm sure it will bite other developers in real life.

You are giving a way to do generic parsing and even include one parameter to make it invariant, still in some situations it will give you the wrong date. I mean, I can't think of a better way to surprise developers.

**Comment by tarekgh** [comment]
I am not trying to argue here but want to clarify if we parse it as UTC, users will get surprised too why not considered the local time zone on the result. The returned DateTimeOffset in your case will have an UTC offset that you can choose to ignore if you want. The DateTime part will be what you want.

**Comment by gusty** [comment]
The answer is very simple: because defaulting to UTC makes your function **referentially transparent**, whereas using the local time zone won't, and it will become probably the only exception in the the whole IParsable interface where things are depending on the context without any way to "fix it" other than, what you suggest which is basically staying away from the interface.

**Comment by wallymathieu** [comment]
This is a bit surprising. If you get a string in a format that indicates that it is a UTC timestamp and parse it, then it returns the local time?

**Comment by gusty** [comment]
No, if the string indicates UTC it will work. But that's the sad part, it will work most common scenarios except one.

The situation is, you can be consuming json from a provider, in his API docs he states he sends UTC dates, but you parse them with DateTimeOffset and you are being defensive in the event he suddenly start sending offsets others than cero (it happened to me recently).

Now, what if he doesn't break the contract, but he simply remove the offset, since the spec says that it's UTC already?

Bad things will happen !
Not to tell you if you have your application deployed in a multi-region service: you will get different times, depending on machine local settings.

You may argue, ok then I change the local settings. No, you can't, there's no such thing as UTC timezone, the closest is GMT, but in summer it will change.

So yes, no matter all the progress in .Net languages about good defaults for FP like immutability, null references, ... , as long as you keep living in .Net and the .Net team in 2020's keep ignoring basic things like referential transparency, all the other efforts are in vain.

**Comment by Clockwork-Muse** [comment]
> No, you can't, there's no such thing as UTC timezone

All the major server OSes I'm aware of (and the major date/time libraries) provide a UTC "timezone" (pedantically speaking it doesn't exist, but having one present for the OS/library just makes things easier), and it's more or less a successor to the GMT timezone.

> the closest is GMT, but in summer it will change

GMT, in a computer context, almost never refers to a timezone that receives a DST adjustment (eg, as in [RFC822](https://www.rfc-editor.org/rfc/rfc822#section-5)), and except for UTC/GMT most platforms have abandoned short codes due to ambiguities (The airline/travel industry had a UTC zone for Utrecht, Germany, and there are duplicates of many of the three-letter codes).  Just about everything has moved to the IANA/Olson/tzdb, where the zone you're referring to would be called [`Europe/London`](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#LONDON).

> You may argue, ok then I change the local settings.

If this is a client/consumer computer, you shouldn't do this.  If this is a server computer, you likely should as a safety measure.
What you should do, as a matter of good practice, and which will cover both cases, is to do as @tarekgh suggested and use the appropriate `DateTimeStyles` settings.

> The answer is very simple: because defaulting to UTC makes your function referentially transparent, whereas using the local time zone won't

This makes the opposite assumption from the original writers of the function - they believed that the most likely reader would be the same entity that wrote the value (whereas your point of view is that the writer and reader are different).  This, for example, is the way that base `DateTime` works (however many problems that causes in the name of backwards compatibility), and most other libraries take a similar stance.
It also assumes that a value coming in without a zone will always be in UTC, which is often not the case.  Especially in legacy systems, which may not have good utilities for dealing with different timezones, they may not be included as part of a format string, and instead anticipate it be parsed as local to the original entity (or based on another field).  Referential transparency doesn't help you here - in the absence of definite information effectively any answer is equally likely to be wrong.  Note that making it parse this way also means that application writers could simply change from `DateTime` to `DateTimeOffset`, and their code would correctly read data it had previously written.

<hr />

@tarekgh - The only wrinkle I see here is that from a very cursory look it doesn't appear that our JSON library/options provides a way to specify `AssumeUniversal`, meaning if the remote party starts dropping the timezone (as @gusty indicates has happened) working around it would require creating a custom converter.

(ASP.NET Core switched to assuming UTC, but as a server application that's fine globally)

**Comment by eiriktsarpalis** [comment]
I'm somewhat conflicted about this. While it's true that existing `Parse` methods use `DateTimeStyles.None` as their default, `IParsable<T>` is a generic parsing abstraction which affords compositional patterns like the following:
```C#
public record Envelope<T>(T value) : IParsable<Envelope<T>>
    where T : IParsable<T>
{
    public static Envelope<T> Parse(string s, IFormatProvider? provider)
        => new(T.Parse(s, provider));

    // Try-method omitted for brevity
}
```
As such, the recommendation to use a `DateTimeOffset.Parse` overload that does accept a `DateTimeStyles` parameter is not applicable, as the concrete type is often not visible at the callsite. That does suggest to me that the `DateTime` implementation should assume a TZ invariant aka "referentially transparent" implementation even if it does diverge from the other static methods.

Tagging @tannergooding who might also have opinions on the matter.

**Comment by tannergooding** [comment]
Most types in the BCL are not invariant by default, rather they default to the current culture.

I agree that invariant by default might have been nice, but there are general considerations around globalization and the like that come into play.

This is, at the end of the day, no different than the default behavior of `T.Parse("5,000")` which will result in different answers for `int` based on the machine it's running against. Or the fact that `T.Parse("AA55")` can't be parsed due to the hex number style being unsupported, and there needing to be an additional constraint to `INumber<T>` to get access to pass in the `NumberStyles`.

Given that `DateTime.Parse(string s)` itself also behaves as passing `DateTimeStyles.None` by default; I'd expect the same behavior here, even if it might be an unfortunate historical default.

**Comment by Clockwork-Muse** [comment]
What about a potential proposal around supplying some easier way to control this behavior for `System.Text.Json` scenarios?  Possibly at minimum globally, but preferrably via an attribute on a field.  Or are we thinking this is best handled via third-party libraries?

**Comment by gusty** [comment]
@tannergooding what you say is not clear for me at all.

The interface takes 2 parameters, the second being the culture. So I don't know what do you mean with `T.Parse("5,000")` but if you pass the invariant culture, you'll get always the same result AFAIK.

Then you say `DateTime.Parse(string s) ` but this is about `DateTimeOffset`, I think you can never get a string representation without the offset by doing `string` on a DateTimeOffset which makes me think that even failing the parsing had been a better alternative than "silently" succeding by using the local time.

Finally I wanted to say, that I'm aware of the (unfortunate) initial decision 20 years ago of using locals as default, but at that time there were no static interfaces, so no generic way of doing things, this interface is doing the right thing by accepting a parameter to make it invariant, I mean the signature force you to be explicit, it's just the DateTimeOffset implementation that "escapes" the invariant in that specific scenario.

As I said, having a failure (parsing error: missing offset) would be better than getting wrong times and then having to figure it out how to fix them if there's a way to fix them at all.
