### ISSUE TITLE
ReflectionTypeLoadException when interface is loaded from different locations

### ISSUE THREAD

**Issue by angelaki** [dotnet/runtime#93013]
### Description

When lazy loading a library that shares an interface with the executing program, I get an error loading its types:

> Method does not have an implementation

Both implementations are binary identical, they just have a different location. Shouldn't this work anyway? My Plugin (ClassLib) needs to set `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` because most of them come with Nuget-packages, that need to be copied to their output directory.

### Reproduction Steps

[ReflectionTypeLoadException.zip](https://github.com/dotnet/runtime/files/12805199/ReflectionTypeLoadException.zip)

Since it's super hard to describe, I've created this minimal repro.

### Expected behavior

Program executes, wether `InterfaceLib.IInterface _;` is commeted out or not.

### Actual behavior

Program crashes, if the executing program uses the Interface itself.

### Configuration

.Net 7.0

**Comment by angelaki** [comment]
@vitek-karas thank you **so** much for that pretty sophisticated and detailed answer! It really provided me an even deeper insight into .Net's addin system - I'm pretty thankful!

At runtime this doesn't matter for me because I'm actually having control over all the plugins - I just use it for composing my applications. All the shared libs are of the same version and in the same directory like every plugin is. Since the executing application (usually) doesn't need any shared libs itself, all the plugins need to copy their shared libs. Elseway noone would. They just get overwritten on compilation and I don't really need to care.

But now I need to reference a single shared lib from a unit-test loading a plugin. I came down to this pretty simplified code I shared and totally understand why it behaves different depending on the declared variable `InterfaceLib.IInterface _;` exists or not. I just don't get why it wouldn't work, since they both still reference a binary identical version of the interface - just from two different locations. Does this make it a different version for the .Net runtime? So it seams like the only solution I might use is the one you provided last?

Just putting `try { Default.LoadFromAssemblyName(assemblyName); } catch { }` as first line in my `LoadInternal()` actually made it work. I wasn't aware of this method and tried to achive the same using

```
var knownAssembly = Default.Assemblies.FirstOrDefault(a => a.FullName == assemblyName.FullName);
if (knownAssembly != null) { return knownAssembly; }
```

Why does that even behave different? Thank you so much for supporting me here! I know this is for reporting bugs, not support. But I actually thought it should work with binary identical libs (eventough they have difference locations)

**Comment by vitek-karas** [comment]
> I just don't get why it wouldn't work, since they both still reference a binary identical version of the interface - just from two different locations. Does this make it a different version for the .Net runtime? 

This is a behavior of `AssemblyLoadContext` https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext
In short - each `AssemblyLoadContext` (ALC) can load only one version of any given assembly. But also, there's no implicit sharing of assemblies between ALCs, they are intentionally isolated. So if you load an assembly file into ALC (`AssemblyLoadContext.LoadFromAssemblyPath` for example), the runtime will do it regardless of what is already loaded into other ALCs. This can mean that the exact same file (even the exact same path, not just binary equivalent) can be loaded into runtime multiple times and the runtime will treat it as two distinct assemblies.

> Why does that even behave different?

`AssemblyLoadContext.Assemblies` returns the list of all assemblies already loaded into that ALC. There's basically no good way to "predict" the set of assemblies which will be loaded into an ALC. Note that even the ALC.Default loads everything very lazily, so while it has some data on what assemblies are part of the app, it really can't presume which will be actually used. This means that over time the set of assemblies in any given ALC can change (it can really only grow, we don't support unloading single assemblies, only entire ALCs).

`AssemblyLoadContext.LoadFromAssemblyName` actually triggers the loading process - no more being lazy about that assembly. And so you get the answer one way or another, there's no uncertainty about it anymore. This is important because the loading process has lot of extension points, and those will run now.

As a general comment: If you only use dynamic loading as a way to construct the app, but the different components are not real plugins it might be better to not use ALCs for this. You can load everything into the Default ALC - and you can provide the fallback resolution logic by registering a handler for `AssemblyLoadContext.Default.Resolving` - that event is fired if the ALC can't resolve a given assembly name, and you can provide code to resolve it (basically just like you do in `Load`, there's only ordering difference, `Load` is the very first thing called, while `Resolving` is near to the end of the resolution process).

**Comment by angelaki** [comment]
@vitek-karas sorry this is even more getting a Q/A. I now at least totally understood that .Net behaves totally correct here (this this issue can be closed). If it's OK for you, I'd love to ask one more question:

Now that I want to implement your solution, relying only on the `Default` ALC and supply missing assemblys in it's `Resolving` method, I am not able to load the assembly named _{Microsoft.EntityFrameworkCore.resources, Version=7.0.11.0, Culture=de-DE, PublicKeyToken=adb9793829ddae60}_. For every assembly loaded, I create a `AssemblyDependencyResolver` for the directory it is located. But none of them can find the requested assembly. In my previous solution this library wasn't even request in the `Load` method at all.

I thought about just adding lookup directories from assemblys to the `Default` ALC somehow but this doesn't seam to be possible at all, is it?

Thank you so much! Hope I'm done now.

**Comment by vitek-karas** [comment]
> I thought about just adding lookup directories from assemblys to the Default ALC somehow but this doesn't seam to be possible at all, is it?

No, this is not possible by just adding a path somewhere (some asterixis, but we'll ignore that). On the other hand - you get to run your code in the Resolving handler - so it's pretty simple to scan a couple of paths if that's what you want to do.

> I am not able to load the assembly named {Microsoft.EntityFrameworkCore.resources, Version=7.0.11.0, Culture=de-DE, PublicKeyToken=adb9793829ddae60}.

I don't know what might be going on here. Do you have the `.deps.json` of the "plugin" which brings in EF Core? Does it point to the resources file? Where is the file on the disk?...

**Comment by angelaki** [comment]
Yes, I've seen there are _ways_, but they all seamed pretty hacky / actually not supported.

Sorry I can't tell for sure. The `deps.json` file exists but it does not contain a `Microsoft.EntityFrameworkCore.resources` file. Neither does the other solution request to load it at all - and it works. So I can't tell where it is. Maybe it just isn't required. Trying to use Default ALC only, I get this error at runtime, when EFCore is used for the first time:

> System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.dll' or one of its dependencies: Das angegebene Modul wurde nicht gefunden.

Sorry, I guess it's quite hard to support me here. Should I try to build a minimal reproduction? Guess that'd be hard enough, too.

**Comment by angelaki** [comment]
It's actually just the solution I provided first vs

```
public class PlugInLoadContext
{
    private readonly Dictionary<string, Assembly> _knownPlugIns = new Dictionary<string, Assembly>();
    private readonly Dictionary<string, AssemblyDependencyResolver> _knownPlugInResolvers = new Dictionary<string, AssemblyDependencyResolver>();

    public PlugInLoadContext()
    {
        AssemblyLoadContext.Default.Resolving += Default_Resolving;
    }

    private Assembly? Default_Resolving(AssemblyLoadContext arg1, AssemblyName arg2)
    {
        var assemblyPath = _knownPlugInResolvers.Values.Select(r => r.ResolveAssemblyToPath(arg2)).Where(p => p != null).FirstOrDefault();
        if (assemblyPath != null) { return AssemblyLoadContext.Default.LoadFromAssemblyPath(assemblyPath); }
        return null;
    }

    public IEnumerable<Assembly> PlugIns => _knownPlugIns.Values;

    public Assembly AddPlugIn(string plugInPath)
    {
        if (_knownPlugIns.TryGetValue(plugInPath, out var assembly)) { return assembly; }

        var result = AssemblyLoadContext.Default.LoadFromAssemblyPath(plugInPath);

        _knownPlugIns.Add(plugInPath, result);
        if (!_knownPlugInResolvers.ContainsKey(plugInPath)) { _knownPlugInResolvers[plugInPath] = new AssemblyDependencyResolver(plugInPath); }

        return result;
    }
}
```

**Comment by vitek-karas** [comment]
> System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.dll'

The `Microsoft.Data.SqlClient.SNI.dll` is a native library. To support that with your custom resolution logic, you will need to also handle [`ResolvingUnamangedDll`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.resolvingunmanageddll?view=net-7.0) event. For native libraries the runtime does implement some kind of "search some paths", but I guess it's not in any of those paths in this case, so you need to resolve it yourself.

**Comment by angelaki** [comment]
That totally was the issue! Loaded it via `NativeLibrary.Load` (guess that's the way to go?). Thank you **so** very much for that deep insight to ALC!

**Comment by vitek-karas** [comment]
Or `AssemblyLoadContext.LoadUnamanagedDllFromPath` - but it doesn't matter - native libs are not loaded into a context anyway (they're global).

Glad I was able to help :-)
