### ISSUE TITLE
[mono][hotreload] Add instance field

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#93036]
If I add a field and do not assign anything to it the field->type is NULL.

Adding a test case in this draft PR:
https://github.com/dotnet/runtime/pull/93035/files

**Comment by lambdageek** [comment]
I think it's a bug. And actually, I think I know why it is doing that. We need to resolve the field type. If it's not used anywhere, we don't resolve it. We don't resolve it when we first add it because it might be some new type from the Delta and we don't want to trigger type initialization before we see the whole delta

**Comment by lambdageek** [comment]
Probably the easiest fix is to make the debugger (and reflection) call field resolve type if the type is null. But it might also be possible to make hot reload resolve all the added fields at the end of applying the deltas. Just need to iterate through the enclog one more time and look for fielddef tokens - although we might need to only do it for fields in existing types.

I'll try to fix it tomorrow
