### ISSUE TITLE
RyuJIT: Implement induction variable analysis

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#93143]
This analysis would be used for IV widening (https://github.com/dotnet/runtime/issues/7312) as well as to help implement better arm64 post-increment addressing modes.

Strength reduction: Re-express "secondary" IVs involving multiplication into addition. Pre-requisite for general post-increment. May be an alternative to IV widening if secondary IVs appear as addresses.

**Comment by Sergio0694** [comment]
Will this allow the JIT to automatically achieve the same codegen for loops over eg. spans or arrays, that you can do today if you manually write them as a `while (Unsafe.IsAddressLessThan(...))` and then increment a moving `ref`, rather than indexing every single iteration? Eg. we adopted this pattern everywhere in ImageSharp and while it did give us a noticeable ~10% perf boost overall (which admittedly is fairly big), but the code ended up being basically unreadable and very error prone and quite not safe 😅

**Comment by BruceForstall** [comment]
> Will this allow the JIT to automatically achieve the same codegen for loops over eg. spans or arrays...

I hope the answer is "yes", either via this or other improvements to the JIT.

> we adopted this pattern everywhere in ImageSharp

Hmmm... that's unfortunate. Maybe you could open an issue with this example (before, and after, and why the Unsafe version is faster), if you haven't already?

**Comment by jakobbotsch** [comment]
#97865 adds an initial framework for IV analysis, but let's keep this issue open for strength reduction which I expect to work on in March.

**Comment by jakobbotsch** [comment]
I split out strength reduction into #100913. I'm going to consider this one fixed by #97865.
