### ISSUE TITLE
Support System.DirectoryServices on Linux

### ISSUE THREAD

**Issue by sebgamby** [dotnet/runtime#93326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to run an application using System.DirectoryServices.DirectoryEntry in a Linux container but this is still not supported on the Linux platform.

### Describe the solution you'd like

Support the library System.DirectoryServices on Linux. Could you please indicate if this is on the roadmap or if we should look for alternatives?

**Comment by buyaa-n** [comment]
> Support the library System.DirectoryServices on Linux. Could you please indicate if this is on the roadmap or if we should look for alternatives?

We have no plan to add Linux support for this in near future, better to look for alternatives. Not sure if we ever would consider adding Linux support tag @joperezr for more info, I'll leave the issue open.

**Comment by joperezr** [comment]
Correct. When trying to add LDAP support on Linux from one of the three libraries that currently had this functionality in Windows (System.DirectoryServices.Protocols, System.DirectoryServices, and System.DirectoryServices.AccountManagement), we opted to do the first one because System.DirectoryServices has some types in their APIs that are Windows-specific (not only that, that are COM types). Because of this, in terms of existing API, it was decided that System.DirectoryServices.Protocols would be the most appropriate one to support cross-platform, as it mostly is just a layer on top of the LDAP protocol, which is platform-agnostic.
