### ISSUE TITLE
[wasm] wasmbrowser template is not trimmed on publish

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#93400]
When I do `dotnet publish -c Release` on wasmbrowser template app with WBT installation, it doesn't trim the assemblies.

@radical do you know what might be broken here?

**Comment by maraf** [comment]
Local testing with RC2
- During restore, task `ProcessFrameworkReferences` doesn't return `Microsoft.NET.ILLink.Tasks` as `_ImplicitPackageReference`, and so ILLink target remains an empty placeholder, instead of the actual target.
- The `ProcessFrameworkReferences` returns `Microsoft.NET.ILLink.Tasks` as `_ImplicitPackageReference` only in following `Publish` and `WasmTriggerPublishApp` target execution.
- For `wasmconsole` is the `Microsoft.NET.ILLink.Tasks` during restore and so ILLink works.
- It might be related to `Microsoft.NET.Sdk.WebAssembly.Pack` also provided by `ProcessFrameworkReferences`, which is provided for browser, but not for console template.
