### ISSUE TITLE
OpenTelemetry SDK usage in C# Library project is giving System.Runtime.CompilerServices.Unsafe.dll not found error

### ISSUE THREAD

**Issue by trivikso** [dotnet/runtime#93421]
### Description

We are trying to consume OTel SDK in C# Library project where redirection is not available. Consuming latest Package OpenTelemetry 1.6.0 is failing with System.Runtime.CompilerServices.Unsafe.dll 4.0.4.1 version not found.
 
{"Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}
 
Looking at Fusion logs, this is the version between conflict between 
OpenTelemetry 1.6.0 -> OpenTelemetry.Api.ProviderBuilderExtensions 1.6.0 -> OpenTelemetry.Api 1.6.0 -> System.Diagnostics.DiagnosticSource 7.0.2 -> System.Runtime.CompilerServices.Unsafe (>= 6.0.0)
 
OpenTelemetry 1.6.0 -> OpenTelemetry.Api.ProviderBuilderExtensions 1.6.0 -> OpenTelemetry.Api 1.6.0 -> System.Diagnostics.DiagnosticSource 7.0.2 -> System.Memory 4.5.5 -> System.Runtime.CompilerServices.Unsafe (>= 4.5.3)
 
Any idea how we can fix this in Library project where redirection is not available?
 
Thanks.

### Reproduction Steps

Create C# Library project

Add OpenTelemetry package

Use Open OpenTelemetry API or call ActivityTraceId.CreateRandom();

### Expected behavior

OpenTelemetry works without errors

### Actual behavior

Failing with this error - 

{"Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

### Configuration

.NET Framework 4.7.2

**Comment by noahfalk** [comment]
So far I am unable to reproduce this problem. Your repro steps said to create a library project but I created a console app instead, otherwise there would be nothing to execute. I'm not sure what you mean by "redirection isn't available"? By default .NET Framework does support redirection and I'm not sure what is different about your environment vs. a standard one. I tried deleting the assembly redirects in my app.config file, but even after doing that my sample app still ran fine.

Options that might help me (or others) understand the problem:
- Are you able to refine the repro steps so that others can replicate the problem?
- Can you include the full fusion log?

Guessing at what might cause the problem since I don't have a repro:
- When you deploy your project, is there a copy of System.Runtime.CompilerServices.Unsafe.dll included with the other application binaries that has assembly version 6.0.0.0 (file version and product version in the OS file properties details tab should both start with 6.0)

**Comment by noahfalk** [comment]
With a little offline discussion I am able to repro this now. I am using a console app with this source:
```C#
using System.Diagnostics;

namespace ConsoleApp5
{
    internal class Program
    {
        static void Main(string[] args)
        {
             var traceId = ActivityTraceId.CreateRandom();
        }
    }
}
```
Then if I delete the app.config file and run the app (without doing anything that triggers a rebuild) it will fail with this output:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()
   --- End of inner exception stack trace ---
   at System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   at System.Diagnostics.ActivityTraceId.CreateRandom()
   at ConsoleApp5.Program.Main(String[] args) in C:\Users\noahfalk\source\repos\ConsoleApp5\ConsoleApp5\Program.cs:line 9
Press any key to continue . . .
```

As best I can tell this is by design behavior because the assembly redirections in the app.config file were necessary to retarget the 4.x reference to the 6.x assembly. I'm not sure what is causing assembly redirection to be unavailable to you? I'm also unsure if there is any workaround, eliminating redirects seems like it might block you from using many NuGet packages.

**Comment by noahfalk** [comment]
After spending a little more time on it, I think a viable alternative approach is to use the AssemblyResolve callback to retarget the assembly load at runtime:

```C#
internal class Program
{
    static void Main(string[] args)
    {
        AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
         var traceId = ActivityTraceId.CreateRandom();
    }

    private static System.Reflection.Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
    {
        // if we are trying to resolve an older major version of System.Runtime.CompilerServices.Unsafe,
        // retarget that to version which is currently loaded.
        Assembly csuAssembly = typeof(Unsafe).Assembly;
        AssemblyName csuAssemblyName = csuAssembly.GetName();
        AssemblyName loadName = new AssemblyName(args.Name);
        if(loadName.Name == csuAssemblyName.Name && loadName.Version.Major < csuAssemblyName.Version.Major)
        {
            return csuAssembly;
        }

        return null;
    }
}
```

**Comment by ericstj** [comment]
BindingRedirects are required when using NuGet packages.  There is nothing that forces everyone to agree and compile against the same assembly version.  Whenever using NuGet packages on .NETFramework you need to make sure you use bindingRedirects to redirect all versions less than the version you deploy to the version you deploy.  There are built in features in MSBuild to do this https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.

You cannot rely on AseemblyResolve as suggested above.  AssemblyResolve is only ever called if a bind fails.  That may not happen if someone has installed the referenced version in the GAC, or if it's otherwise loaded in the process or probable from the process (eg: in case of a plugin).  BindingRedirects are a hard requirement of NuGet + .NETFramework.

**Comment by noahfalk** [comment]
Thanks for correcting that @ericstj!
