### ISSUE TITLE
Complex.ToString format changed from (a, b) to <a; b>

### ISSUE THREAD

**Issue by chrfin** [dotnet/runtime#93454]
### Description

The implementation of `Complex.ToString` did change from `(a, b)` to `<a; b>`, but the documentation (https://learn.microsoft.com/en-us/dotnet/api/system.numerics.complex.tostring) still documents `(a, b)`

### Reproduction Steps

Run e.g. in LINQPad or see https://dotnetfiddle.net/LZoCLY and https://dotnetfiddle.net/LhhIRo:

```
RuntimeInformation.FrameworkDescription.Dump();
new Complex(1, 2).ToString().Dump();
```

### Expected behavior

.NET 6.0.23
(1, 2)

### Actual behavior

.NET 7.0.12
<1; 2>

### Regression?

Worked with .NET 6.0

**Comment by stephentoub** [comment]
@tannergooding, this changed in https://github.com/dotnet/runtime/pull/69582. Was that on purpose?

**Comment by tannergooding** [comment]
The change to use `semicolon` was intentional and it was because we support formatting with culture specific information and correspondingly need to be able to parse results back out given it implements `INumberBase<T>`.

There's basically `NumberFormatInfo.NumberDecimalSeparator` and `NumberFormatInfo.NumberGroupSeparator` which need to be considered, which are typically `.` and `,`; but which is which differs. This necessitates having a unique identifier, such as `;` to separate the parts of the complex number. If we had a `TextInfo` then we could use `TextInfo.ListSeparator` to disambiguate, but that isn't always possible.

The change to use `<` and `>` rather than `(` and `)` I don't recall, but I believe it was also intentional. In either case, it was probably copied from the `Vector*` types which use it to disambiguate. -- I believe the reason `(` and `)` aren't used here is because of `NumberFormatInfo,NumberNegativePattern`, where-in `(x)` may be used to represent a negative number. Ideally there would be some `TextInfo.ListGroupStartSymbol` and `TextInfo.ListGroupEndSymbol` from which formatting could generally use and disambiguate based on culture needs, but that doesn't exist today.

**Comment by chrfin** [comment]
@tannergooding This means the behavior is correct/intended, but the documentation is wrong?

**Comment by chrfin** [comment]
@tannergooding / @stephentoub Can you please confirm the behavior is correct/intended, but the documentation is wrong?
We are in the process of updating to .NET 8.0 (from .NET 6.0) and this is a breaking change for us, as we use(d) `ToString` to save complex numbers and the old logic can't parse them now, as it expects `(a, b)`, not `<a; b>`.

**Comment by tannergooding** [comment]
Yes. This is expected (and far too late for us to change before .NET 8 releases).

You could always use a custom `ToString` mechanism such as `$"({complex.Real}, {complex.Imaginary})"` if you want to preserve the older behavior.

**Comment by stephentoub** [comment]
@tannergooding, if we haven't already, we should create a breaking change notice for this.

**Comment by chrfin** [comment]
> You could always use a custom `ToString` mechanism such as `$"({complex.Real}, {complex.Imaginary})"` if you want to preserve the older behavior.

Thanks, that's exactly what we did, just wanted to confirm so we can document the change in our codebase accordingly.

**Comment by jeffhandley** [comment]
dotnet/docs#41835 was created for the breaking change document and dotnet/dotnet-api-docs#10125 was opened to update the API docs.
