### ISSUE TITLE
[AOT] Add support for compressing output file

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#93510]
I tried AOT on one of my larger .NET 8 console projects and the executable file was 12mb large. I used UPX and it went down to 4.5mb and still executes fine. Which makes me wonder why there is no option to compress the output file in the .NET SDK yet? There are already lots of options to further reduce the file size, even a full page on MSDN about that https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/optimizing and  https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#trimming-framework-library-features

Why not introduce something we can opt-in like: `<UseBinaryCompression>true</UseBinaryCompression>` for those who care more about size than startup speed? If we can reduce the file size by more than 50% it should be worth it.

**Comment by KeterSCP** [comment]
There is a nuget package for https://github.com/MichalStrehovsky/PublishAotCompressed
You simply put `<PackageReference>` in your csproj and the output binary will be automatically compressed on publish

**Comment by Symbai** [comment]
> There is a nuget package for https://github.com/MichalStrehovsky/PublishAotCompressed (which uses UPX underneath) You simply put `<PackageReference>` in your csproj and the output binary will be automatically compressed on publish

I don't want to use UPX. The moment I used UPX Windows Defender completely freaked out and deleted the file. I'm requesting an in-house solution. Similar to publising as Single File which also can be done using external tools but was added to .NET sdk.

**Comment by NCLnclNCL** [comment]
> > There is a nuget package for https://github.com/MichalStrehovsky/PublishAotCompressed (which uses UPX underneath) You simply put `<PackageReference>` in your csproj and the output binary will be automatically compressed on publish
> 
> I don't want to use UPX. The moment I used UPX Windows Defender completely freaked out and deleted the file. I'm requesting an in-house solution. Similar to publising as Single File which also can be done using external tools but was added to .NET sdk.

Using this <IlcScanReflection>false</IlcScanReflection>

**Comment by Symbai** [comment]
> Using this `<IlcScanReflection>false</IlcScanReflection>`

For what? Reducing the file size? Just like all of the other ways in the MDSN link in my first post it's not compressing the output file which is what I propose. And unlike I`lcScanReflection` it doesn't come with any other drawback except of slower start. But thanks

**Comment by jkotas** [comment]
> I don't want to use UPX. The moment I used UPX Windows Defender completely freaked out and deleted the file. 

If you see false positives with UPX, report them per https://github.com/upx/upx/issues/437 . 

Native AOT uses platform linker to produce the final binary. As long as these fundamental characteristic stays, any code self-extractor will look like UPX. In-house native AOT clone of UPX would have similar issues as regular UPX. 

Decompressing code in the process is always going to have potential to confuse antivirus software. We do see occasional reports of antivirus software issues with PublishSingleFile as well.

**Comment by Symbai** [comment]
> If you see false positives with UPX, report them per [upx/upx#437](https://github.com/upx/upx/issues/437) .

This is about false positives of UPX releases. Not about false positives of binaries compressed by UPX. 

> Decompressing code in the process is always going to have potential to confuse antivirus software. We do see occasional reports of antivirus software issues with PublishSingleFile as well.

Yes but these are getting addressed very soon, either here or by antivirus companies. With UPX they are not. It could also be that UPX itself makes things look suspicious and not the fact that its compressed. No idea what makes them raise an alert. My uncompressed program is harmless and not "detected". As soon as its UPX compressed its marked as a specific trojan. If I use another binary compression tool its not "detected". 

The risk of detection is there but just that didn't stopped you from adding publishing to single file. So it shouldn't be a reason to not add compression to .NET SDK. The benefit of >50% reduced size is superb.

**Comment by jkotas** [comment]
> If I use another binary compression tool its not "detected"

Would you mind sharing the name of this binary compression tool that works for you?

> The risk of detection is there but just that didn't stopped you from adding publishing to single file. So it shouldn't be a reason to not add compression to .NET SDK. 

Adding compression to PublishSingleFile was a simple feature, everything needed was there and it just required integrating a few components together.

Compression for native AOT binaries means to either create UPX clone, or stop using platform linker to produce the final native AOT binary. Both of these are very expensive features with dubious results. 

> Especially when seeing your team is fighting about 5-10% or ~100-200kb size improvements. We speak about more than 6mb in my case.

We care about striking the right balance. On disk binary size is not the only metric that we care about.

**Comment by Symbai** [comment]
> Would you mind sharing the name of this binary compression tool that works for you?

MPRESS, for example.

**Comment by MichalStrehovsky** [comment]
> Yes but these are getting addressed very soon, either here or by antivirus companies. With UPX they are not. It could also be that UPX itself makes things look suspicious and not the fact that its compressed.

UPX is more popular than .NET single file executables. The authors behind UPX run a business with licensing the decompressor to antivirus vendors. For many, UPX is transparent.

> Especially when seeing your team is fighting about 5-10% or ~100-200kb size improvements.

The size improvements we're typically after come with zero drawbacks (or maybe a drawback in the form of "more product code to maintain"). They're not opt-in - everyone gets them for free. Executable compression significantly affects startup time and process working set - that's 2 out of 3 key metrics that we care about the most for native AOT (the third is size).

If we compress code, we'd do it  the same way how UPX is doing it: there's no difference and no advantage to having this inbox. We can't do anything better - we need to operate on a binary generated by the platform linker same way as any other tool would do. Compression in single file is different - the single file tooling has a unique position to do this and no other external tool could be used to replicate what it is doing (it's about compressing a blob of data that is glued to the single file host executable).

For native AOT, we could in theory compress data. We have many data structures that could in theory be compressed. But the size savings will not even be close to what one can achieve with UPX (that also compresses the code).

If we keep this issue open, it would be to track compressing data because we don't plan to build a general purpose executable compressor (a tool that compresses executables that come out of platform linkers is just a general purpose compressor - we could label it as ".NET compressor", but it would likely be capable of compressing any other natively compiled binary).

**Comment by Symbai** [comment]
> that's 2 out of 3 key metrics that we care about the most for native AOT (the third is size).

Still you have TONS of options available to opt-in to decrease the size (look at the MDSN link in first post). So either you dont care but your customers do, or you care more than you are willing to confirm. Or someone adding these things to the SDK although nobody wanted them... ah that seems, for some reason, pretty unlikely to me... but I got your point even if you don't say it out loud, don't worry.
