### ISSUE TITLE
Deprecated package used by System.Security.Cryptography.Cng

### ISSUE THREAD

**Issue by sofiyanguyen** [dotnet/runtime#93577]
### Description

The version of the dependency System.Formats.Asn1 referenced by the latest release of System.Security.Cryptography.Cng is >=5.0.0, which is now deprecated in Nuget. System.Security.Cryptography.Cng is a transitive dependency of Microsoft.EntityFrameworkCore.SqlServer, so whenever the latest version (7.0.12) of EF Core SqlServer is referenced in a project, the deprecated dependency is automatically installed. 

There is a [newer version of Asn1 available](https://www.nuget.org/packages/System.Formats.Asn1/7.0.0)
 
If some package ranges in System.Security.Cryptography.Cng could be bumped to include the newer Asn1 package versions that would be much appreciated.

### Reproduction Steps

Add `<PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />` (or replace 5.0.0 with latest version) to a project file and run `dotnet restore`. Then run `dotnet list package --deprecated --include-transitive`

### Expected behavior

No packages returned as deprecated.

### Actual behavior

System.Formats.Asn1 Version 5.0.0 returned as deprecated.

### Configuration

using .NET 6.0.413, Windows x64. not specific to this configuration.

**Comment by bartonjs** [comment]
System.Security.Cryptography.Cng is an end-of-life package, 5.0.0 was its last version.  It's a little surprising that it's in EFCore's dependency graph at all, but c'est la vie.

@ViktorHofer I feel like you're tracking this sort of meta-problem.

**Comment by ViktorHofer** [comment]
Microsoft.Data.SqlClient brings in these old dependencies:

<img width="371" alt="image" src="https://github.com/dotnet/runtime/assets/7412651/7276f358-e601-44f4-9976-cb4f287ab3e7">

Both System.Security.Cryptography.Cng and System.Security.Principal.Windows shouldn't be referenced anymore by TFMs >= net6.0.

**Comment by ViktorHofer** [comment]
Here's the dependency graph of [those dead-ended 5.0.0 packages](https://github.com/dotnet/announcements/issues/190):

- System.Formats.Asn1/5.0.0
- System.Buffers/4.5.1
- System.Memory/4.5.4
- System.Security.AccessControl/5.0.0
- System.Security.Principal.Windows/5.0.0

As part of the .NET deprecation effort, (nearly) all 5.0.0 packages were deprecated. For the packages that were dead-ended after .NET 5, we un-deprecated them so that they can continue to be used on .NET Framework and/or .NET Standard. When we un-deprecated packages, we (I) didn't look at the dependency graph. So, we missed the `System.Formats.Asn1` transitive dependency. I just un-deprecated that package version.

Sorry for the inconvenience here and thank you for reporting the issue. Closing as the reported issue should now be fixed.
