### ISSUE TITLE
[API Proposal]: Swizzling operators for Vector[2,3,4] similar to HLSL

### ISSUE THREAD

**Issue by dev-3mensio** [dotnet/runtime#93609]
### Background and motivation

The purpose is to make dense vector code more readable, because the properties eliminate a lot of constructor calls. In HLSL there are swizzling operators that can be used to reorder components and change the width of vectors.

I would like to see the same for Vector[2,3,4] in System.Numerics.

### API Proposal

For instance, to retrieve y,x from a float3, you can use foo3.yx;

In our (homegrown) library we have added them as C# properties, plus some more:
vec2.YX  := new Vector2(vec2.Y, vec2.X);
vec2.XY0 := new Vector3(vec2.X, vec2.Y, 0);

vec3.XY := new Vector2(vec3.X, vec3.Y);
vec3.YZX := new Vector3(vec3.Y, vec3.Z, vec3.X);

vec3.XYZ1 := new Vector4(vec3.X, vec3.Y, vec3.Z, 1);

The above are examples. I believe there is no real need for all possible permutations, but I don't mind if they are there. The most common are transpose, remove last component, and pad with a 0/1 for  the last component.

### API Usage

```csharp
Vector2 val = vec3.XY;
```
### Alternative Designs

The alternative are extension methods that do the same. 

like vector.XY() to retrieve a Vector2 with the first 2 components. But it's less elegant. 

### Risks

Can't think of any.

**Comment by tannergooding** [comment]
I don't expect we would be likely to expose an API that works like this. Such APIs aren't strictly obvious in how they function and require many overloads (not just all combinations of `XYZW`, but also cases like `XXXX` or `XXXY`).

For `Vector<T>` and `Vector64/128/256/512<T>` we expose an explicit `Shuffle(vector, indices)` API instead. This likewise allows us to support concepts like `Shuffle(vector1, vector2, indices)` as well, which is commonly supported in hardware. Special cases like `Broadcast` (sometimes called Splat) or Zip/Unzip (sometimes called Pack/Unpack) can also have named alternatives if desirable.

Doing similar for Vector2/3/4 or Quaternion is likely a better direction.

**Comment by dev-3mensio** [comment]
Thanks for taking a look. I understand it looks non-obvious, but in practice I never need to explain. As I said you don't need all permutations. By far the most popular use is converting between Vector2 and Vector3.

I am not interested in the Shuffle() idea: I'd rather define extension methods (like XY1() ) which is what we had before we added properties to our Vector[2,3,4] types.

**Comment by tannergooding** [comment]
> I understand it looks non-obvious, but in practice I never need to explain

I agree it's something that can be learned, or even figured out fairly easily. But that's not how .NET designs or exposes APIs.

> As I said you don't need all permutations.

Part of API design/review includes envisioning how a feature request might be expanded upon and what the reasonable worst case scenario is. The worst cases here is that there are many different permutations and we'd eventually need to expose them all. The right answer for that is to either expose a general purpose API, like `Shuffle`, or to whittle it down to an exact subset with reasoning why that subset is special/unique and won't need to expand later.

> By far the most popular use is converting between Vector2 and Vector3.

A more appropriate way to do this in .NET, which would be consistent with how we do other functionality, is to expose `As*` or `To*` methods, with `As*` is used when the conversion is "free" or low cost and `To*` is used otherwise.

It would not be unreasonable to propose `ToVector2/3/4()` and `ToVector2/3/4Unsafe()` methods which make getting a smaller or larger type cheap and efficient. The difference between the regular and `Unsafe` variants is that the former explicitly zeros new elements when widening, while the latter leaves them undefined (thus allowing a cheaper operation if the state of those fields is unimportant).
