### ISSUE TITLE
Inconsistency when Parsing System.Reflection.AssemblyMetadataAttribute Value

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/runtime#93781]
### Description

When parsing a `CustomAttribute` of type `System.Reflection.AssemblyMetadataAttribute` obtained with MetadataReader, the resulting attribute values exhibit inconsistent spacing. The attribute values can appear in various formats, including:

"KeyValue"
"Key Value"
"Key*Value"
"Key!Value"

### Reproduction Steps

```
byte[] data = reader.GetBlobBytes(attr.Value);
string attributeValue = Encoding.UTF8.GetString(data);
```

### Expected behavior

Consistency in the resulting `attributeValue` string.

### Actual behavior

Inconsistent spacing and non-readable characters in the resulting `attributeValue` string.

**Comment by teo-tsirpanis** [comment]
`CustomAttribute.Value` points to a blob that encodes the attribute's parameters, as specified in section II.23.3 of the [ECMA-335](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/) specification. Directly decoding the blob from UTF-8 produces no meaningful results.

To properly decode an attribute, you have to implement an [`ICustomAttributeTypeProvider`](https://learn.microsoft.com/en-gb/dotnet/api/system.reflection.metadata.icustomattributetypeprovider-1) (in your case it can be trivial since you don't care about the types), and use the [`CustomAttribute.DecodeValue`](https://learn.microsoft.com/en-gb/dotnet/api/system.reflection.metadata.customattribute.decodevalue) method. That method will return a value of type `CustomAttributeValue`, and its `FixedArguments` property should contain the metadata's key and value.

**Comment by buyaa-n** [comment]
Closing as the question answered
