### ISSUE TITLE
DllImport with SuppressGCTransition causes PAL_SEHException with a hosted runtime in release configuration.

### ISSUE THREAD

**Issue by Raphtaliyah** [dotnet/runtime#94029]
### Description

Hosting CoreCLR and trying to use ``DllImport`` (or ``LibraryImport``) with ``SuppressGCTransition`` in a release build causes ``PAL_SEHException`` regardless if the library or entry point exists. Passing a function pointer with the attribute (``delegate* unmanaged[SuppressGCTransition]<void>``) works.

To keep it as close as possible to my code, the example code is from my application but stripped of any error handling, logging, and namespaces/classes.

### Reproduction Steps

The example code is available in [this](https://github.com/Raphtaliyah/dotnet-issue-PAL_SEHException) repository. Building the C# library in release mode and running the native example should reproduce the issue.

### Expected behavior

``DllImport`` working as expected.

### Actual behavior

``PAL_SEHException`` is thrown when ``SuppressGCTransition`` is applied to ``DllImport`` or ``LibraryImport``.

### Configuration

.NET version: 8.0.0-rc.2.23479.6 or built from 9a6d53050f15071287e6d2b111be80af54e43689, haven't tried newer or older.
OS: Linux x64 Ubuntu 22.04 (in WSL)

**Comment by AaronRobinsonMSFT** [comment]
> PAL_SEHException is thrown when SuppressGCTransition is applied to DllImport or LibraryImport.

The following code is found in the repro. Judging from this, I would expect an exception to be thrown because the name of the library to import isn't valid. Is the concern the a non intuitive exception is thrown?

```csharp
    [SuppressGCTransition]
    [DllImport("DoesntHaveToBeValid", EntryPoint = "DoesntHaveToExist")]
    private static extern void Test();
```

> DllImport working as expected.

Understood, but the repo as designed will always throw an exception. If we replace this with a valid binary and export is the failure still observed?

**Comment by Raphtaliyah** [comment]
Hi, thanks for taking a look at it!
> If we replace this with a valid binary and export is the failure still observed?
Yes, but only if the c# library is built in release mode, in debug mode it works fine.
The reason I submitted with a not valid entry point and library name because I found this the more interesting, it's not the *call* to a ``SuppressGCTransition`` external function that's causing the exception, it's just the creation of the function. Also having to build a shared library for the import to actually work would have further complicated the example with probably not much useful information (as the exception happens when JITing the function), I should have made this more clear.

> I would expect an exception to be thrown
Yes, a C# exception (``System.EntryPointNotFoundException`` more specifically), ``PAL_SEHException`` is a C++ exception, this can't be caught in C# or handled in any way, it gets thrown right back into C++ where the managed function was called. If the c# library is built in debug mode this also stops and a regular ``EntryPointNotFoundException`` is thrown. I've also just tested how it would interact with a ``finally`` block, it simply gets ignored (along with the ``catch`` block, but that was expected).

To further complicate the issue if I now try it in my actual application it *sometimes* works (adding it to a logger function behind many calls, generics, etc, not sure what "fixes" it) and sometimes causes even weirder behaviour: The dll importer I set for ``__internal`` to be recognized as the application itself simply stops working, functions (not (necessarily) marked with ``SuppressGCTransition``) stop being able to resolve ``__internal`` after I try to call one with ``SuppressGCTransition`` where it doesn't work. Extremely simplified: In the entry point I have a try/catch (and now finally, when I attempted to do the test) that calls an ``Initialize`` function. In the ``catch`` block I log with a logger *if* the dll resolver was set and to console if something went wrong before it (I track it with a ``bool``). I try to call a dummy function like in the demo, it now throws the c# exception, gets caught and tries to log with the logger and fails again because it can't resolve ``__internal``, but I used the logger before I attempted the call to the dummy function and it worked. If I remove the ``SuppressGCTransition`` from the dummy function I get the c# exception, gets caught and logs it nicely with the logger func that it now can resolve.

So the 3 different kind of behaviour I encountered are:
* C++ ``PAL_SEHException``, doesn't respect managed ``finally`` blocks and throws it right back to the original call to managed from native. It doesn't matter whether the export actually exists, the behaviour is the same.
* Correctly recognizes that the export doesn't exist, throws ``EntryPointNotFoundException``, messes up the dll resolver and breaks any native call regardless of ``SuppressGCTransition`` on those methods.
* It works, haven't managed it get a small code to reproduce it. Tried with a logger func that's behind many calls with generics, ``fixed`` statements, etc, not sure what "fixes" it.

**Comment by Raphtaliyah** [comment]
The fact that it sometimes worked really bothered me so I experimented a bit and I think I found what causes it and updated the repo. It's really simple to get it to work: don't make the native call from the first stack frame. The new example includes a shared library linked to the main executable, the dll import resolver to support ``__internal``, a valid ``DllImport`` with ``SuppressGCTransition`` and updated the CMake build script to also build the C# library (along with the new shared library). In ``Entry.cs`` on the first line there is a ``#define NO_INLINE_METHOD``, this applies ``MethodImpl(MethodImplOptions.NoInlining)`` to a new function to force a second stack frame, running it this way everything works as expected. Removing the ``define`` applies ``MethodImpl(MethodImplOptions.AggressiveInlining)`` to force the removal of the stack frame which brings back the same issue.

**Comment by AaronRobinsonMSFT** [comment]
@Raphtaliyah This is all by design. The use of `SuppressGCTransition` is an advanced scenario that has certain non-obvious side effects on code generation and typical P/Invoke semantics. The first being function look-up. Consider the following C# method:

```csharp
static void Bar(bool b)
{
    if (b)
        Foo("string");
}

[DllImport("DoesNotExist")]
static extern void Foo(string b);
```

if `b` is `false`, the call to `Foo()` will never execute so a `EntryPointNotFoundException` is not thrown even though the binary "DoesNotExist" doesn't exist. This would throw in cases where `b` was `true`. When `SuppressGCTransition` is applied to a P/Invoke the look up of the assembly is done during the JIT to gain the highest possible performance - this is different than without. Note that in `Debug` the JIT may not inline the call whereas in a `Release` build this is quite likely. This is also why wrapping the function in a function hides the throwing and forcing inlining changes that behavior, this is all by design.

The use of `UnmanagedCallersOnly` means that if an unwind during exception handler lookup finds that method with no try block on non-Windows the process will be torn down because managed exceptions are not permitted to escape the runtime. On Windows this is permitted due to the CLR respecting [SEH](https://devblogs.microsoft.com/dotnet/how-clr-maps-seh-exceptions-to-managed-exception-types/). On non-Windows this will result in potentially odd/unexpected behavior, especially when combined with `SuppressGCTransition`.

Both of these features are consider very advanced and as a result their UX is not always what a user would expect, but their currently described behavior is by design.

**Comment by jkotas** [comment]
> On non-Windows this will result in potentially odd/unexpected behavior, especially when combined with SuppressGCTransition.

This should not be odd or unexpected behavior. This should produce proper "Unhandled Exception". 

`PAL_SEHException` is internal implementation detail of the runtime. It should not be leaking to user code.

@janvorli Could you please take a look?

#### Repro steps (Ubuntu 22.04, .NET 8 RC2)

1. `git clone https://github.com/Raphtaliyah/dotnet-issue-PAL_SEHException`
2. Apply following diff 
```diff
--- a/Lib/Entry.cs
+++ b/Lib/Entry.cs
-#define NO_INLINE_METHOD
+// #define NO_INLINE_METHOD^M
--- a/Native/main.cpp
+++ b/Native/main.cpp
-static constexpr auto RUNTIME_PATH = "runtime"; // can be empty to use system installed runtime.
+static constexpr auto RUNTIME_PATH = ""; // can be empty to use system installed runtime.^M
```
3. `cmake CMakeList.txt`
4. `make`
5.  `./NativeExec`

#### Result
```
terminate called after throwing an instance of 'PAL_SEHException'
Aborted
```

**Comment by jkotas** [comment]
This problem is triggered by any errors that happen during JITing of `UnmanagedCallersOnly` entrypoint on Linux. It is not specific to `SuppressGCTransition`.

For example, modifying the repro as follows is going to repro the problem as well:
```csharp
[UnmanagedCallersOnly]
internal static void Initialize()
{
    typeof(InvalidType).ToString();
}

[StructLayout(LayoutKind.Explicit)]
struct InvalidType
{
    [FieldOffset(0)]
    int i;
    [FieldOffset(0)]
    object o;
}
```

**Comment by AaronRobinsonMSFT** [comment]
> This problem is triggered by any errors that happen during JITing of UnmanagedCallersOnly entrypoint on Linux. It is not specific to SuppressGCTransition.

Thanks @jkotas. Let's make sure we distinguish the way the exception is being exposed from the reason for it manifesting.

I see the point about `PAL_SEHException` and I should have been more careful on that front. With regard to why and how a an exception is emanating from a P/Invoke adorned with `SuppressGCTransition`, I think my statement remains. The binding of the export is done at JIT instead of when called. This is a semantic difference compared to when `SuppressGCTransition` is not applied and is by design.

**Comment by Raphtaliyah** [comment]
Thanks for taking a look at it @jkotas!

So it throws because it's being resolved at JIT time before ``SetDllResolver`` is run and the ``PAL_SEHException`` is trying to be the ``EntryPointNotFoundException``, that makes sense. Adding a ``Console.WriteLine`` also doesn't run so it does confirm that the real issue is that errors that happen during JITing doesn't get converted to proper exceptions.

It doesn't explain how did it manage to corrupt the dll import resolver and fail after it already made native calls but I'm unable to reproduce that again so that remains unexplained, might have just been corruption somewhere else.

Also I feel like this behaviour of ``SuppressGCTransition`` should be documented.

This probably explains other cases of ``PAL_SEHException`` leaking that I didn't open an issue for:
* Loading an assembly without a dependency allows getting a function pointer to a function that depends on the not loaded dependency and calling that function results in ``PAL_SEHException``.
* Trying to return ``bool`` from ``UnmanagedCallersOnly`` function results in ``PAL_SEHException``. (I was not aware that ``bool`` requires marshalling and ``UnmanagedCallersOnly`` doesn't support that.)

**Comment by AaronRobinsonMSFT** [comment]
@Raphtaliyah and @jkotas I have added a note to documentation for `SuppressGCTransitionAttribute`. The `CallConvSuppressGCTransition` documentation  references the attribute so that is handled. See https://github.com/dotnet/dotnet-api-docs/pull/9433
