### ISSUE TITLE
Microsoft.WindowsDesktop.App missing from dotnet distribution

### ISSUE THREAD

**Issue by barf** [dotnet/runtime#94078]
### Description

Hello, as per the title this framework namespace is missing from the dotnet distributions version 6 and 7, I have not tested 8 but porting applications from Windows to Linux is blocked by this issue.

### Reproduction Steps

1. Install dotnet 6 or 7 on Linux following the Microsoft documentation.
2. Attempt to build and/or run any dotnet application built with reference to Microsoft.WindowsDesktop.App

### Expected behavior

dotnet framework includes the basic libraries required for the claimed "cross platform" support

### Actual behavior

Dot net applications which worked in previous frameworks no longer run

### Regression?

Yes. Dot net version 4 and 5 applications run on Linux under wine, these new framework versions have rendered applications that previously worked in wine, unusable.

### Known Workarounds

Build applications using framework versions 4-5

**Comment by Joe4evr** [comment]
![](https://i.imgur.com/jks6Qqr.png)

**Comment by jeffschwMSFT** [comment]
Thanks for giving a detailed report.

```
Install dotnet 6 or 7 on Linux following the Microsoft documentation.
```

This was the key detail.  Microsoft.WindowsDesktop is only supported on Windows.

**Comment by jeffschwMSFT** [comment]
Consider trying (.NET Maui)[https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?tabs=vswin&pivots=devices-android] or (.NET Blazor)[https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro] for x-plat UI.

**Comment by barf** [comment]
Thank you for the feedback. It is difficult to recommend Microsoft solutions to customers when this is the experience.

**Comment by barf** [comment]
Yeah stdio works fine but don't ask about the airbags or ABS.
![car-sales-Untitled](https://github.com/dotnet/runtime/assets/584684/8bedbbce-c16d-4bd1-876d-200b48165c77)

**Comment by En3Tho** [comment]
I don't get what you're trying to do. If you run things under Wine then they have to be built targeting Windows and not Linux anyway.

Try building self-contained app targeting Windows and see how it runs in Wine.

Why would you want Windows-specific runtime be a part of Linux distribution anyway?

This is all very confusing honestly.

**Comment by barf** [comment]
The dotnet platform has not been tested on Linux with basic applications, I can also only guess why Microsoft would announce "cross platform" framework that lacks basic GUI framework.

**Comment by En3Tho** [comment]
But there are:

[Avalonia](https://github.com/AvaloniaUI/Avalonia) for native-feel ui apps
[Photino](https://github.com/tryphotino/photino.Blazor) provides a cross platform host for Blazor based apps
[Terminal.Gui](https://github.com/gui-cs/Terminal.Gui) is a framework to create terminal apps

The fact that `Windows`Forms (or should I say `!!!WINDOWS!!!`Forms) do not work on Linux natively doesn't have anything to do with cross platform capabilities of `.Net` itself.

Anyway, have you tried a self-contained app under Wine?

**Comment by barf** [comment]
Thank you En3Tho, I will look at those but the issue should not have been closed. Unimpressed by Microsoft's response. 

libhostfxr.so is the provided host/fxr and this needs a companion X or Wayland host interface before the claims of "cross platform" can be taken seriously

**Comment by huoyaoyuan** [comment]
Microsoft.`!!!WINDOWS!!!`Desktop.App which consists of `!!!WINDOWS!!!` Forms and `!!!WINDOWS!!!` Presentation Framework, have very close relationship with Windows. There was never announcement of porting them to other platforms, and likely never in the future because of technical difficulty.

Nothing prevents an application to use P/Invoke to support X Window or Wayland. "cross platforms" means more fundamental things like enabling P/Invoke on Linux. GUI frameworks are built on top of programming language runtime.

**Comment by barf** [comment]
Thank you huoyuan. This does still seem like an issue, most dot net apps are Windows Forms AFAIK? Java does not have this limitation.

**Comment by huoyaoyuan** [comment]
> most dot net apps are Windows Forms AFAIK?

It's hard to get detailed statistics in individual application/installation/launch count, but Windows Forms should be a little portion of popular, actively maintained applications since it's very old.

Windows Forms is 1:1 direct wrapper of Win32 controls. It's too native to be ever portable.

> Java

The less feature exposed by a native control wrapper, the easier to get ported.

**Comment by barf** [comment]
Sorry if I wasn't clear, Windows Forms may have been too specific. If most dot net apps are GUI applications of some kind (whether Forms or MAUI etc) but no GUI framework is ported to the Linux OS, this is an issue. I like C# and .NET but this prevents me from using it on projects.

**Comment by barf** [comment]
But in any case the MSFT person closed the bug, and with that attitude I have no interest in supporting the company.

**Comment by barf** [comment]
I see the MSFT rep has edited their snide remark, what an experience ...

**Comment by jkotas** [comment]
> most dot net apps are GUI applications of some kind (whether Forms or MAUI etc)

Not true. The publicly available results of .NET usage surveys consistently show that most dot net apps are web and cloud apps. For example: https://www.surveymonkey.com/stories/SM-GDSVMB2C/ . You are right that .NET is a popular platform for building GUI applications, but it is not most dotnet apps.

> no GUI framework is ported to the Linux OS, this is an issue.

Not true. https://github.com/dotnet/runtime/issues/94078#issuecomment-1784024103 lists several .NET GUI frameworks for Linux. You are right that there is no .NET GUI framework for Linux supported by Microsoft currently. If your project requires GUI framework for Linux supported by a large company, you have to look elsewhere. I am sorry.

> I see the MSFT rep has edited their snide remark, what an experience ...

There was no harm done by the edit. You can check delta via github UI - the edit only adjusted the markdown, without changing the content. You are right that .NET MAUI suggested by the remark is not a viable option on Linux since it is not supported there.

**Comment by barf** [comment]
I hope this can be reconsidered as a feature request! It would greatly help bridge a gap.
