### ISSUE TITLE
[API Proposal]: Enhance Single, SingleOrDefault, First, and Last to allow throwing a custom exception.

### ISSUE THREAD

**Issue by arturek** [dotnet/runtime#94153]
### Background and motivation

**Motivation**

Currently methods `Single`, `SingleOrDefault`, `First`, `Last` (from the `System.Enumerable` class) throw an `InvalidOperationException` exception when the (filtered) collection contains unexpected numbers of elements. This behavior is useful when these methods are used as a form of an assert, but not very helpful when a more meaningful exception is desired.

To replace `InvalidOperationException` with a more suitable exception, a try/catch statement can be used (see one of [examples](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=net-8.0)). This solution is far from perfect, especially for variable initializations where a single (often one line) expression becomes a long statement block. When multiple variables are initialized, the block has to be multiplied because it's not easy to match thrown exceptions to the initialization expression of a specific variable. Additionally, such try/catch can incorrectly catch other `InvalidOperationException` unexpectedly thrown the predicate of `SingleOrDefault`.

Developers sometimes write their own implementations of these methods using `Where` followed by manual verification of its result. Such solutions sometimes introduce other issues (such as double enumeration) and always hinder the readability of the code. More often in practice, these methods are applied directly, leading to longer resolution of such cases and a worse user experience (caused by a not very useful generic error message).

**Proposed solution**

To improve the situation, I would like to add one additional parameter named `orElseThrow` to these methods. The parameter would accept a function that should return an exception to be thrown instead of the default `InvalidOperationException`. If the provided function returns null (ignoring nullability of its return type) the default exception is thrown.

In case of the `Single` method the `orElseThrow` parameter should have the type `Func<bool, Exception>`. The boolean value would allow its user to differentiate between two reasons of throwing an exception (none matched or more than one found) if needed. In cases of `SingleOrDefault`, `First`, and `Last` methods the `orElseThrow` parameter would be of type `Func<Exception>`.

All exceptions thrown for reasons different then unexpected number of matching elements are not affected by this change. For example, using a null value instead of a predicate will throw `ArgumentNullException` (without triggering the evaluation of the `orElseThrow` parameter).

### API Proposal

```csharp
namespace System.Link;

public class Enumerable
{
  public static TSource First<TSource>(this IEnumerable<TSource> source, Func<Exception> orElseThrow);
  public static TSource First<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, Func<Exception> orElseThrow);
  public static TSource Last<TSource>(this IEnumerable<TSource> source, Func<Exception> orElseThrow);
  public static TSource Last<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, Func<Exception> orElseThrow);

  public static TSource Single<TSource>(this IEnumerable<TSource> source, Func<bool, Exception> orElseThrow);
  public static TSource Single<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, Func<bool, Exception> orElseThrow);

  public static TSource? SingleOrDefault<TSource>(this IEnumerable<TSource> source, Func<Exception> orElseThrow);
  public static TSource SingleOrDefault<TSource>(this IEnumerable<TSource> source, TSource defaultValue, Func<Exception> orElseThrow);
```

### API Usage

```csharp
void ProcessTasks(List<task> tasks)
{
  var intialTask = tasks.Single(t => t.IsInitial), orElseThrow: foundMore => new InputDataException(foundMore ? "Expected to find exactly one initial task but found more." : "Expected to find exactly one initialTask but found none.");
  var closingTask = tasks.Single(t => t.IsClosing, orElseThrow: _ => new InputDataException ($"Exactly one closing tasks should be configured for {this.ProcessName}.");
  var task = task.SingleOrDefault(t => t.CanSubmit, this.DefaultSubmitTask, orElseThrow: () => new InputDataException ("At most one submittable task can be used.");
```

### Alternative Designs

Methods such as `TryGetFirst`, `TryGetSingleOrDefault` can be created. They would be more similar to existing `TryGetValue` and allow to do something more then only throwing an exception. On the other hand, they are less readable (since their desired output is returned via a parameter, and not a return value), harder (if possible, at all) to use as part of an expression, and IMO lest discoverable.

### Risks

The risk should be low. Using this feature requires explicit changes to the code. The older code is not affected.

**Comment by eiriktsarpalis** [comment]
Thank you for taking the time to write the proposal, but throwing delegates is not really a pattern that we would want to implement or recommend for the case of LINQ methods. I would instead recommend doing it using a check on the result of one of the existing `OrDefault` methods:

```C#
var result = source.FirstOrDefault();
if (result is null)
{
    throw new MyCustomException();
}
```

I realize that the above is predicated on the source enumerable being a reference type, but there are workarounds for that as well. It is something I'm hoping we'd be able to address in the general case once the language gets support for true optional types.

Finally, I recognize that the above will not work with `SingleOrDefault`, since unlike its sibling APIs this one can still throw. It is rather unfortunate, but altering that at this point would be a breaking change. You might want to consider authoring your own LINQ helper method or perhaps utilize collection pattern matching:
```C#
if (source is not [int single])
{
    throw new MyCustomException();
}
```
The above requires that the `source` type uses indexers, so to extend it to arbitrary IEnumerables you could change it to
```C#
if (source.Take(2).ToArray() is not [int single])
{
    throw new MyCustomException();
}
```
Hope this helps.

**Comment by colejohnson66** [comment]
Using collection pattern matching seems like a hack. "Why am I taking two items just to compare it against one?" It even took me a few minutes to realize why. Having to `ToArray` the result also seems odd.

**Comment by eiriktsarpalis** [comment]
FWIW the `Take` component isn't strictly necessary, it just avoids enumerating the full source and allocating a potentially large array. Fundamentally, the issue is that collection pattern matching isn't supported with IEnumerable types so the source needs to be converted -- I don't see why it couldn't in principle, however pattern matching that case could force unpredictable enumerations so maybe the language team is explicitly trying to avoid that. @CyrusNajmabadi might know.
