### ISSUE TITLE
[NativeAOT] Hello World app making remote connections? Why?

### ISSUE THREAD

**Issue by Slxdy** [dotnet/runtime#94165]
### Description

I have created a win-x64 NativeAOT hello world app with reflection disabled. Scanning the final output in virustotal not only triggers 3 antiviruses, but sandboxes also show remote connections.

Here is my scan:
https://www.virustotal.com/gui/file/6adffcb9d167001e538f76da1899c2ac86cc128700e2d45248e5958ad7fc6097

I don't think I have to explain why this is a problem. It's a Hello World app. It shouldn't make any remote connections.

### Reproduction Steps

- Create a Hello World app. 
- Enable `PublishAot` and `IlcDisableReflection` in the csproj. 
- Publish the app to win-x64.

### Expected behavior

The app shouldn't do anything other than write to the console.

### Actual behavior

The app makes remote connections.

### Configuration

- net7.0
- Windows 11 (10.0.22621)
- x64
- No

**Comment by MichalStrehovsky** [comment]
It does not make network connections or drop files to the filesystem like the report states.

The app simply crashes in the sandbox because of whatever the sandbox is doing to the system.

If you scroll down [in the details of the sandbox report](https://vtbehaviour.commondatastorage.googleapis.com/6adffcb9d167001e538f76da1899c2ac86cc128700e2d45248e5958ad7fc6097_VirusTotal%20Jujubox.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1698666303&Signature=IvQy%2F8dMArcUqnpCGQVZ7aQqjiL6CYQ6KttpZBzrOy9A0adnpKz11WX7v%2FUyrVA5w8L4HFHWdKkF%0ADJ9nWsjRCF2RT7NnbFkOF1imwI7XuRjToRvW%2FH0eugALKA9DbGmfFdZFTEHnwOA%2B6sXZNE5jAgyL%0AxvEJ9w%2F2RdFl7WHUAUcAuw83I9jEX4M7N8CgKCdJE3L1P2sQ4wa%2Fm4%2BR00tduKj88RRCFdU9Iyml%0AC9sMKs0IJIrhSh1%2FCsq5yU7SIN8VE2xrAvp6YX%2BlyDnYnjNN1P4n%2FjEOT%2BL3Xff7wJsu5fUzaDzM%0Ad6Yc2cSDh%2Fhm4U2TQTehcp8IuJ8TJguaG9Fd3w%3D%3D&response-content-type=text%2Fhtml;), you'll see:

```
KernelBase.dll!WriteFile#file(#2380) ConsoleApp2.exe
Arguments:
{"nNumberOfBytesToWrite":"0x15","lpBuffer":"Unhandled Exception: ","lpNumberOfBytesWritten":"0x27ebc8","hFile":"0x0"}
Returned value:
0x0
```

The last thing the app did was printing the stack trace to the console. You'll also see that the dropped files on the filesystem are named WER4EC.tmp.WERInternalMetadata.xml.

You are seeing Windows Error Reporting sending the crash report. It's a Windows component making these network requests.

Native AOT is open source, you can simply step through it. There are no network calls inserted into a Hello world.

**Comment by Slxdy** [comment]
Hi, thanks for the clarification. I still have to argue that this should be considered a bug, or at least the antivirus flags. Sure, false positives are a thing, but if your user base is a bunch of children, have fun explaining that lol. But if a C++ app doesn't trigger antiviruses, neither should a NativeAOT C# app.

**Comment by jkotas** [comment]
> if a C++ app doesn't trigger antiviruses, 

You should see the same behavior in C/C++ app when it hits unhandled exception.
