### ISSUE TITLE
RuntimeBinder: A field being used after checking it for null

### ISSUE THREAD

**Issue by Genbox** [dotnet/runtime#94184]
### Description

In the C# RuntimeBinder, inside the [MemberLookup:RecordType()](https://github.com/dotnet/runtime/blob/7dba9af08cf7a6919ab8e3e15cfd62341167edc3/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/MemberLookup.cs#L82) method, it seems `_swtFirst` is checked for null before using it. That seems like a bug to me.

It could be that the original developer meant to check if it is *not* null, but it seems excessive to encompass _fMulti as well if that is the case.

### Reproduction Steps

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by pinkfloydx33** [comment]
It has an overloaded `operator==` which tests a field on the type for `null` as part of the comparison:
https://github.com/dotnet/runtime/blob/7dba9af08cf7a6919ab8e3e15cfd62341167edc3/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/WithType.cs#L60-L75

The field in question is initialized to non-null in the constructor:
https://github.com/dotnet/runtime/blob/7dba9af08cf7a6919ab8e3e15cfd62341167edc3/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/MemberLookup.cs#L495

I don't think it's a bug. Just unusual usage

**Comment by Genbox** [comment]
> It has an overloaded `operator==` which tests a field on the type for `null` as part of the comparison:
> I don't think it's a bug. Just unusual usage

There is nothing unusual about it. The first line, `if (ReferenceEquals(swt1, swt2))` would do a reference comparison of null and null, which equals true. As such `_swtFirst` is null, and the call to `_swtFirst.Set(sym, type)` would cause a NullReferenceException.

To demonstrate it, I copied the SymWithType class into a blank console project. It has an identical equality overload:

![image](https://github.com/dotnet/runtime/assets/657616/7ca00c91-23ef-450f-897f-b6446422afa8)

As you can see, it does indeed cause an exception.

**Comment by pinkfloydx33** [comment]
Right, it would cause an exception if `_swtFirst` was **literally** `null`. But it's not. 

It's **instantiated to a value** inside of the constructor:
https://github.com/dotnet/runtime/blob/7dba9af08cf7a6919ab8e3e15cfd62341167edc3/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/MemberLookup.cs#L495

Since it's a `readonly` field, it could never be set to a different value (ie the literal `null`). Therefore when that line of code is invoked, `swt1` is `_swtFirst` which is _equivalent to_ `new SymWithType()` and `swt2` is `null`. When the operator is invoked, the comparisons look like:

- `ReferenceEquals(swt1, null)` returns `false` because it's essentially _equivalent_ to:
   -  `ReferenceEquals(_swtFirst, null)`, or
   -  `ReferenceEquals(new SymWithType(), null)`
- `swt1 is null` returns `false` since it has a value 
- `swt2 is null` returns `true` since it's the literal `null`
- `swt1._sym == null` returns `true` because the `_sym` field of a newly constructed `SymWithType` is itself `null`

The operator returns true, the if block in question is entered, but `_symFirst` is **not** `null`. The comparison is confusing because it relies on the operator looking at a field of the type. 

If instead it were written as `if (_symFirst is null)` then you'd be correct that it'd cause an exception **iff** the body were entered since the operator won't be invoked and the field would be tested for the literal value `null`. But since the field is initialized to a value, it could never be the literal `null` and the whole block would be dead code.

**Comment by cston** [comment]
`_swtFirst` is a `readonly` field and is initialized to a non-`null` value in the `MemberLookup` constructor. As mentioned above, `operator==` is overloaded for that type to handle comparing non-`null` values against `null`, so the behavior appears to be by design.
