### ISSUE TITLE
gcstress0x3 hangs for osx arm64 Checked

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#94224]
https://dev.azure.com/dnceng-public/public/_build?definitionId=112 pipeline is failing during October.

The console log ends with 
```
Sc['Loader.0.1' END OF WORK ITEM LOG: Command timed out, and was killed]
```

```
Build FAILED.

/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/9.0.0-beta.23528.1/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(89,5): error : Work item Loader.0.1 in job 75c188a3-6613-4d78-891f-681094711aa9 has failed. [/Users/runner/work/1/s/src/tests/Common/helixpublishwitharcade.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/9.0.0-beta.23528.1/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(89,5): error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/75c188a3-6613-4d78-891f-681094711aa9/workitems/Loader.0.1/console [/Users/runner/work/1/s/src/tests/Common/helixpublishwitharcade.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 04:23:42.19
Build failed with exit code 1. Check errors above.
Finishing: Send tests to Helix (Unix)
```

**Comment by BruceForstall** [comment]
This test (collection) appears to be super slow under GCStress=3. Maybe it needs more GCStress striping?

**Comment by markples** [comment]
Striping will probably help.  I don't (obviously at least) see any of the "merged group slowdown" that we've seen in some other groups.  The last successful run of this directory took ~4 hours.  There are 3 huge (3 MB) il files in this directory that are each one [Fact], so setting the striping to 3 would split them apart (a bit of a hack - it will work because I think they are consecutive tests - we don't have feedback of test times or anything like that).  Splitting those into multiple [Fact]s, if possible, would remove the brittleness of a striping fix.
