### ISSUE TITLE
IntersectBy second parameter has wrong type

### ISSUE THREAD

**Issue by demian-floreani** [dotnet/runtime#94296]
### Description

The extension method IntersectBy has the wrong type for the second element.

`public static IEnumerable<TSource> IntersectBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelector)`

Should be:

`public static IEnumerable<TSource> IntersectBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TSource> second, Func<TSource, TKey> keySelector)`

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Intersect.cs

### Reproduction Steps

No need

### Expected behavior

The first and second element should have the same type

### Actual behavior

The first and second element have different types

**Comment by eiriktsarpalis** [comment]
This was done intentionally to support intersection of heterogeneous collections, which is possible [like so](https://github.com/dotnet/runtime/issues/27687#issuecomment-773550893).

While we did initially approve overloads that include `IEnumerable<TSource>` second parameters, we ultimately ended up removing them since they were causing type [inference issues](https://github.com/dotnet/runtime/pull/50335).
