### ISSUE TITLE
Determine whether running in NativeAOT at runtime

### ISSUE THREAD

**Issue by vaind** [dotnet/runtime#94380]
Is there any API that can be used to determine at runtime, from a normal, not AOT compiled library, whether the application that includes this library has been published as Native AOT? The only thing I'm aware of is an indirect approach of checking stack trace & the features available there

**Comment by KeterSCP** [comment]
See https://github.com/dotnet/runtime/issues/76739

**Comment by MichalStrehovsky** [comment]
> See #76739

To be clear that issue was not about Native AOT (it's for Mono AOT). `RuntimeFeature.IsDynamicCodeSupported` will return false if dynamic code is not supported by the runtime, like the docs say. It can return false on runtimes that are not Native AOT: even CoreCLR with JIT can report false here if the app disables Reflection.Emit through an AppContext switch. There's no API to check for native AOT specifically. If native AOT ever gets an IL interpreter, this API could return true on Native AOT as well. What's the scenario you need this for?

**Comment by vaind** [comment]
> What's the scenario you need this for?

Different stack trace handling in [Sentry](https://github.com/getsentry/sentry-dotnet) based on the library being included in a NativeAOT-compiled vs "standard" app. We were considering shipping two versions of the library but that would be complicating and we'd likely need to add a new nuget package which is terrible for library consumers.

**Comment by MichalStrehovsky** [comment]
It would be more reliable to tie it to the difference in stack trace behavior. IsDynamicCodeSupported will work in .NET 8, but you have to accept it is going to report true even in Mono scenarios (that have different problems for stack traces on Blazor-WASM-AOT) and also when running on top of CoreCLR with JIT sometimes (e.g. adding `<PublishAot>true</PublishAot>` to a project will report IsDynamicCodeSupported=false even for `dotnet run` with no AOT compilation in sight).

**Comment by vaind** [comment]
> It would be more reliable to tie it to the difference in stack trace behavior

I've done just that, thanks for confirmation that's the right approach for now.
```c#
#if NET6_0_OR_GREATER   // TODO NET7 once we target it
        var stackTrace = new StackTrace(false);
        IsAot = (stackTrace.GetFrame(0)?.GetMethod() is not { });
#endif
