### ISSUE TITLE
int.TryParse has ambiguous

### ISSUE THREAD

**Issue by leyserai** [dotnet/runtime#94422]
1. Define a generic method TryGetValue .
2. Use TryGetValue and input type is string, but rowValue is dynamic.
3. Use TryParse convert rowValue to int ,  will throw exception  .
   **The call is ambiguous between the following methods or properties: 'int.TryParse(string, out int)' and 
     'int.TryParse(System.ReadOnlySpan<byte>, out int)'**.
4. Change var rowValue to string rowValue , Specifies the rowValue type, this will work fine.

```
private static object TryGetValue<T>(ExpandoObject obj, string propertyName, T defaultValue = default)
 {
      if (((IDictionary<string, object>)obj).ContainsKey(propertyName))
      {
          return ((IDictionary<string, object>)obj)[propertyName];
      }

      return defaultValue;
 }
 var rawValue = TryGetValue<string>(obj, "id");
 if (int.TryParse(rawValue, out int id))
 {
     answer.Id = id;
 }
```

**Comment by stephentoub** [comment]
From your description, this sounds by design: there are two overloads that differ only in type of one parameter, and if the caller has that type as dynamic, it's ambiguous which you're actually trying to use.

The repro you shared, though, isn't a complete repro of the problem.  If you share a complete, standalone repro that demonstrates the compiler error, we can comment for sure.

**Comment by leyserai** [comment]
@stephentoub  Here is a complete example
```
using System;
using System.Collections.Generic;
using System.Dynamic;
					
public class Program
{
	public static void Main()
	{
		dynamic obj = new System.Dynamic.ExpandoObject();
		var dictionary = (IDictionary<string, object>)obj;
		dictionary["0"] = "{[questionId, ValueKind = Number : \"1\"]}";
		dictionary["1"] = "{[questionType, ValueKind = Number : \"2\"]}";
		dictionary["2"] = "{[value, ValueKind = String : \"選択肢１\"]}";
		var rawValue = TryGetValue<string>(obj, "id");

		Console.WriteLine(rawValue);
	}
	
	static object TryGetValue<T>(ExpandoObject obj, string propertyName, T defaultValue = default)
	{
		if (((IDictionary<string, object>)obj).ContainsKey(propertyName))
		{
			return ((IDictionary<string, object>)obj)[propertyName];
		}
		return defaultValue;
	}
}
```

This throws an exception, as flows
```
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The call is ambiguous between the following methods or properties: 'System.Console.WriteLine(string, params object[])' and 'System.Console.WriteLine(char[])'
   at CallSite.Target(Closure, CallSite, Type, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Program.Main()
Command terminated by signal 6
```

**Comment by leyserai** [comment]
@stephentoub 
Here is a complete code:
```
using System;
					
public class Program
{
	public static void Main()
	{
		int.TryParse(null, out int id);
		Console.WriteLine("Hello World");
	}
}
```
This throws an exception, as follows
```
Compilation error (line 7, col 7): The call is ambiguous between the following methods or properties: 'int.TryParse(ReadOnlySpan<byte>, out int)' and 'int.TryParse(string?, out int)'
```
But in.NET 7 it will work fine.

**Comment by tannergooding** [comment]
Can you provide a repo that doesn't involve passing the literal `null`?

Such a call is ambiguous, but its also effectively pointless as the call will always return `false` and set `id` to `0`. So it isn't the type of breaking change that we are concerned about. It's left as an extremely rare niche case where users should correct their code.

**Comment by leyserai** [comment]
@tannergooding  The purpose of using TryPase is to avoid throwing exceptions, if null will throw exceptions, what method should be used?

**Comment by tannergooding** [comment]
`TryParse` does not throw for `null`, it returns `false`. 

The issue is that there are two APIs: `TryParse(ReadOnlySpan<byte>, out int)` and `TryParse(string?, out int)`. The literal `null` doesn't specify a type and thus the compiler cannot determine if you would prefer `ROSpan<byte>` or `string`, both of which are equally valid conversions for `null`.

If you instead did the following, it would work as expected.
```csharp
string s = null;
int.TryParse(s, out int id);
```

However, this is also "nonsensical". Passing in the literal `null` will always result in `TryParse` returning `false` and `id` being set to `0`. So you should just not do this in the first place. You should change this code to simply `int id = 0;`

This is why I was asking for a more complete example, as the simple repro you gave with the literal `null` does not help us to understand the failure case. -- It sounds like the failure case involves `dynamic`, but the sample snippet you gave doesn't have `TryGetValue` returning `dynamic`. It has it returning `object`, so `rawValue` is `object` and the code is invalid. If you make it `dynamic` you do get the ambiguity at runtime, but that's then expected for a `null` and therefore untyped object as it can't pick which overload to use.

**Comment by leyserai** [comment]
@tannergooding 
I made the mistake of defining a TryGetValue party in my code that accepts generic T but returns object, causing TryParse to Error CS1503, but if I define the return type of TryGetValue as T, Then it can work normally, the code is as follows:


```
object TryGetValue<T>(ExpandoObject obj, string propertyName, T defaultValue = default)
{
    if (((IDictionary<string, object>)obj).ContainsKey(propertyName))
    {
        return ((IDictionary<string, object>)obj)[propertyName];
    }

    return defaultValue;
}
void SetAnswerCommonProperties(dynamic obj)
{
  var rawValue =TryGetValue<string>(obj, "id");
 if (int.TryParse(rawValue, out int id))
 {
     id.Dump();
 }
 "empty".Dump();
}
 
dynamic o = new ExpandoObject();
o.id = "123";
SetAnswerCommonProperties(o);
```

Here is the revised TryGetValue
```

T TryGetValue<T>(ExpandoObject obj, string propertyName, T defaultValue = default)
{
    if (((IDictionary<string, object>)obj).ContainsKey(propertyName))
    {
        return(T)((IDictionary<string, object>)obj)[propertyName];
    }

    return defaultValue;
}
void SetAnswerCommonProperties(dynamic obj)
{
  var rawValue =TryGetValue<string>(obj, "id");
 if (int.TryParse(rawValue, out int id))
 {
     id.Dump();
 }
 "empty".Dump();
}
 
dynamic o = new ExpandoObject();
o.id = "123";
SetAnswerCommonProperties(o);

```
Thank you very much for your patient answer

**Comment by tannergooding** [comment]
`CS1503: Argument 1: cannot convert from 'object' to 'System.ReadOnlySpan<byte>'` exists because no API takes `object`. Only APIs taking `string`, `ReadOnlySpan<char>`, and `ReadOnlySpan<byte>` exist. You have to explicitly select the target type for it to function as expected. Making `TryGetValue` return `T` instead makes it `string` and thus the right overload can be picked.
