### ISSUE TITLE
.NET7 NativeAOT worked for us right before updating today to .NET8, now NativeAOT is breaking on an error.

### ISSUE THREAD

**Issue by BradChase2011** [dotnet/runtime#94744]
### Description

We are currently updating our libraries to .NET 8 and everything is working except NativeAOT has failed which used to work in .NET 7.

The error is so:

5>Failed to load type 'System.Nullable`1<System.Enum>' from assembly 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
5>Internal.TypeSystem.TypeSystemException+TypeLoadException: Failed to load type 'System.Nullable`1<System.Enum>' from assembly 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
5>   at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID, String, String) + 0x37
5>   at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc) + 0x61a
5>   at ILCompiler.CompilerTypeSystemContext.EnsureLoadableType(TypeDesc) + 0x6f
5>   at ILCompiler.RootingServiceProvider.AddReflectionRoot(TypeDesc, String) + 0x22
5>   at ILCompiler.RootingHelpers.RootType(IRootingServiceProvider, TypeDesc, Boolean, String) + 0x49
5>   at ILCompiler.RdXmlRootProvider.ProcessTypeDirective(IRootingServiceProvider, ModuleDesc, XElement) + 0x2e9
5>   at ILCompiler.RdXmlRootProvider.ProcessAssemblyDirective(IRootingServiceProvider, XElement) + 0x29e
5>   at ILCompiler.RdXmlRootProvider.AddCompilationRoots(IRootingServiceProvider) + 0x225
5>   at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1, NodeFactory, IEnumerable`1, ILProvider, DebugInformationProvider, DevirtualizationManager, IInliningPolicy, Logger) + 0x126
5>   at ILCompiler.RyuJitCompilation..ctor(DependencyAnalyzerBase`1, NodeFactory, IEnumerable`1, ILProvider, DebugInformationProvider, Logger, DevirtualizationManager, IInliningPolicy, InstructionSetSupport, ProfileDataManager, MethodImportationErrorProvider, RyuJitCompilationOptions, Int32) + 0x81
5>   at ILCompiler.RyuJitCompilationBuilder.ToCompilation() + 0x4e8
5>   at ILCompiler.Program.Run() + 0x269f
5>   at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass221_0.<.ctor>b__0(ParseResult result) + 0x315

### Reproduction Steps

Move from .NET7 to .NET8 and try to publish AOT.

We have tried everything from trying to put it in MyRoots.xml and rd.xml which we have been using for .NET7 AOT.

### Expected behavior

Publishing with AOT passes.

### Actual behavior

Publishing with AOT enabled fails on Windows x64.

### Regression?

It previously worked on the last public .NET 7.

### Known Workarounds

None.

### Configuration

.NET 8, Windows 11, x64, NativeAOT.

### Other information

Would love to know how we can get around it by using the directives or roots in the meantime.

**Comment by jkotas** [comment]
This error means that you have invalid type `Nullable<Enum>` in your rd.xml file.

rd.xml is not supported and the experience is pretty poor. It would be best if you can replace it by supported alternative.

**Comment by BradChase2011** [comment]
> This error means that you have invalid type `Nullable<Enum>` in your rd.xml file.
> 
> rd.xml is not supported and the experience is pretty poor. It would be best if you can replace it by supported alternative.

We put it in after the error occurred after updating to .NET8.  With it removed, we still get the error.

**Comment by agocke** [comment]
Can you post the error after removing the entry? The existing error specifically mentions `Nullable<Enum>`, so that type name must be coming from somewhere. But it shouldn't be able to be written in code because it's a compiler error (System.Enum is not a struct, and Nullable<T> is constrained to struct).

**Comment by MichalStrehovsky** [comment]
Besides the question @agocke asks, could you also point us to the docs that instructed you to use rd.xml? We had such docs when native AOT was an experimental project in the runtimelab repo, but none of those should have made it into .NET 7.

**Comment by BradChase2011** [comment]
Per jkotas comment that rd.xml has been deprecated, we moved the code out of the RdXmlFile to TrimmerRootDescriptor and that fixed the problems.  It seems just having the RdXmlFile in the project with older assemblies was causing it with .NET8.  We have Json serialization issues where as our binary is fine, but thats to be expected and alot easier to debug as its probably due to the new json stuff.

agocke, correct the System.Enum is a sealed class I thought, which is why I had no idea how its even possible to have that error show up.  I only added it to the rd.xml AFTER the error showed up.  With it removed from the rd.xml, the error still shows up.  But since we can now get into the app for the most part using only the TrimmerRootDescriptor, we will move forward there unless you would like me to explicitly test the rd.xml (but since its deprecated?).

I had a bunch of links saved for the rd.xml but looks like you guys have scrubbed it or put warnings almost everywhere the last two days like so:
https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/rd-xml-format.md

All my links that documentation exists now are either in microsoft archived repositories or in other websites like Medium.  Here are some of my really old saved links not archived:

https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/rd-xml-format.md
https://learn.microsoft.com/en-us/windows/uwp/dotnet-native/runtime-directives-rd-xml-configuration-file-reference
https://github.com/dotnet/corert/blob/master/Documentation/using-corert/rd-xml-format.md

I think the issue is we have been using it for quite a long time and we were not aware it was deprecated.  I am happy to say we are moving forward now using the TrimmerRootDescriptor, I presume that is the way forward?  Is there another option or better recommendation?

Thanks for all the support.

**Comment by MichalStrehovsky** [comment]
Thank you for being an early adopter! Yes, old versions pointed to the docs from the error message. We got rid of those links because the experience of having sidecar XML file is subpar and most people don't know what to put there (I would not expect `System.Nullable<System.Enum>` to fix any issue, for example). I also marked the repo docs on RD.XML with the big warning now so that if someone stumbles upon those docs by chance, they get warned. But there should be no links to those docs from the product ever since we graduated it from an experiment.

The supported mechanism is the `TrimmerRootDescriptor`, or kind of less-typing-required [`TrimmerRootAssembly`](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0#root-assemblies). We do not encourage people to use these though. The experience is unreliable - one can never be sure if the app actually works after trimming and we cannot support people in helping to create descriptors tailored to their specific problem because it doesn't scale.

Trimming/AOT compilation will produce warnings at build time for any code patterns that could be problematic. Our [recommendations and warnings](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/fixing-warnings) point people to fixing the issue at the source - address the warning, and problem goes away. For things like JSON serialization, we recommend people to switch to source generated JSON - System.Text.Json with source generation, or other JSON serializers that have this option (Utf8Json has it for example).
