### ISSUE TITLE
DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection? extraStore) should throw AggregateException

### ISSUE THREAD

**Issue by RufusJWB** [dotnet/runtime#94769]
When decrypting a CMS object, the method DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection? extraStore) iterates through all recipients of this CMS object: 
https://github.com/dotnet/runtime/blob/18cac43e79503cb2d9424dd19822e7ee8444db26/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs#L259
If working down the recipients results in more than one exception, only the last exception is thrown but the other exceptions are overwritten.

Here https://github.com/dotnet/runtime/blob/18cac43e79503cb2d9424dd19822e7ee8444db26/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs#L264

and

https://github.com/dotnet/runtime/blob/18cac43e79503cb2d9424dd19822e7ee8444db26/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs#L274

I'd like to propose that this behavior should be changed to throw an [AggregateException ](https://learn.microsoft.com/en-us/dotnet/api/system.aggregateexception?view=net-8.0) with all collected exceptions.

**Comment by RufusJWB** [comment]
If you are interested, I could provide a pull request implementing my proposed features

**Comment by bartonjs** [comment]
I'm pretty sure the behavior stems from AggregateException having been first introduced in .NET Framework 4.0, but EnvelopedCms comes from .NET Framework 2.0.

Unfortunately, this type of change is not possible under our [breaking change rules for exceptions](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#exceptions).  Because anyone who has

```C#
try
{
   cms.DecryptContent(infos, extra);
}
catch (CryptographicException)
{
   Alert("Decryption failed!");
}
```

would now have exceptions falling outside their catch block.

So, thanks for the suggestion... but it's not something that we can do.

**Comment by MichalPetryka** [comment]
> it's not something that we can do.

Would putting an AggregateException with all the other exceptions as InnerException be legal here?

**Comment by RufusJWB** [comment]
> Unfortunately, this type of change is not possible under our [breaking change rules for exceptions](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#exceptions). Because anyone who has

Understood. How about deriving a new `AggregatedCryptographicException` from `CryptographicException` ? According to your rules, this should be possible:

>✓ Allowed
>
> Throwing a more derived exception than an existing exception

And if I have a look into https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Exceptions.cs# it should be not to complex to implement this.

**Comment by bartonjs** [comment]
If that's

```C#
throw new AggregateException(
   recip1.Exception,
   recip2.Exception,
   ...);
```

If it's more like

```C#
throw new CryptographicException(
   lastException.Message,
   new AggregateException(
       recip1.Exception,
       recip2.Exception,
       ...));
```

that would, I suppose, be possible.  (The pseudo-code is wrong, of course, since it is losing the HResult value on Windows, but is demonstrating the layering)  Is that what you want and something you'd find useful?

**Comment by RufusJWB** [comment]
> Is that what you want and something you'd find useful?

Yes! Maybe let me explain the problem I'm trying to solve: I have an EnvelopedCMS object with multiple recipients. While decoding it, I get for all but one recipient a CryptographicException with the content "RecipientsNotFound". But for one of the recipients there is a different content in the exception. And since this recipient is not the last recipient in the list, I'm not able to react on this exception as it gets overwritten.

**Comment by bartonjs** [comment]
It feels more straightforward to me to just change from

```C#
try
{
   cms.Decrypt(extraStore);
}
...
```

to

```C#
foreach (RecipientInfo ri in cms.RecipientInfos)
{
    try
    {
        cms.Decrypt(ri, extraStore);
    }
    catch (CryptographicException e)
    {
        // the error that came from this specific recipientinfo
    }
}
```

so that you have the recipient affinity right there.

`AggregateCryptographicException` would require a different codepath for .NET 9 vs older, since the correct place to introduce that exception type would be in System.Security.Cryptography.dll (part of the platform), but EnvelopedCms is in a NuGet package that is available for older versions.  Wrapping AggregateException (if that's desired) would be something that would light up "retroactively", since it's something that can be written in common-version code.

**Comment by RufusJWB** [comment]
Thank you for your help! I'll go with this approach:

```
foreach (RecipientInfo ri in cms.RecipientInfos)
{
    try
    {
        cms.Decrypt(ri, extraStore);
    }
    catch (CryptographicException e)
    {
        // the error that came from this specific recipientinfo
    }
}
```
