### ISSUE TITLE
.NET 8.0 JsonArray.Add throws System.InvalidOperationException: "The element cannot be an object or array."

### ISSUE THREAD

**Issue by campersau** [dotnet/runtime#94842]
### Description

Adding a `JsonElement` via `JsonArray.Add` throws an exception with .NET 8. In .NET 7 it worked without throwing.

It is interesting that `JsonArray.Add` worked in .NET 7 but `JsonValue.Create` fails in both .NET 7/8 when passing in a `JsonElement` with `ValueKind.Object/Array`.

Related: https://github.com/dotnet/runtime/issues/70427
Regression in https://github.com/dotnet/runtime/commit/1db4357891752cc028620710fe924425235b8f89 ?

### Reproduction Steps

```c#
using System.Text.Json;
using System.Text.Json.Nodes;

var element = JsonDocument.Parse("""{"test":"hello world"}""");

var array = new JsonArray();
array.Add(element.RootElement); // .NET 8.0 throws here

Console.WriteLine(array.ToJsonString());
```

### Expected behavior

Works without exception.

### Actual behavior

Throws a System.InvalidOperationException: "The element cannot be an object or array."

```
   bei System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeElementCannotBeObjectOrArray()
   bei System.Text.Json.Nodes.JsonValue.VerifyJsonElementIsNotArrayOrObject(JsonElement& element)
   bei System.Text.Json.Nodes.JsonValue.Create[T](T value, Nullable`1 options)
   bei System.Text.Json.Nodes.JsonArray.Add[T](T value)
```

### Regression?

Yes, it works with .NET 7.0

### Known Workarounds

For this particular case the `JsonDocument` could be added instead of the `RootElement`.
A general workaround would be https://github.com/dotnet/runtime/issues/70427#issuecomment-1150960366

### Configuration

.NET 8
Windows
x64

**Comment by eiriktsarpalis** [comment]
It seems that the particular example was working until .NET 7 because the method was creating a `JsonValue` instance directly:

https://github.com/dotnet/runtime/blob/90f1525472b2162029006fb4a7d843d62945e9db/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonArray.cs#L111

Bypassing the usual validation in place when creating `JsonValue` instances from `JsonElement`:

https://github.com/dotnet/runtime/blob/90f1525472b2162029006fb4a7d843d62945e9db/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonValue.CreateOverloads.cs#L319

The validation is in place because `JsonValue` instances do not support nesting, so if you try to pass in anything more complex that won't be inspectible by the DOM APIs (although it would still generated valid JSON).

Nevertheless, we should try to fix this because it's a regression. I'll follow up with a PR.
