### ISSUE TITLE
Question: How does JSON source gen interact with `JsonConverter<T>`?

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/runtime#94937]
Stemming from a [question](https://github.com/gregsdennis/json-everything/issues/549) on my library suite, I'm curious how JSON source generators interact with existing `JsonConverter<T>` types.

Specifically, my user has the following case:

```c#
// Build error: 'JsonPointerJsonConverter' is inaccessible due to its protection level
public record ErrorResponse(string Code, string Message, JsonPointer? Target);

[JsonSerializable(typeof(ErrorResponse))]
public partial class ErrorResponseContext : JsonSerializerContext { }
```

This error apparently occurs because I've defined `JsonPointerJsonConverter` as internal to my lib.

I've read through the ["how to use source gen" docs](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation), but they don't mention this kind of interaction.

The only thing I can think of is that the generated code directly references the converter type.

Also, would this mean that I would have to expose _all_ of my internals?  For example, if `JsonPointer` used internal classes that had their own internal converters, do I need to also then expose those to support source gen?

Just looking for more information.  Thanks.

**Comment by eiriktsarpalis** [comment]
> The only thing I can think of is that the generated code directly references the converter type.

That's correct, the source generator needs to be able to instantiate the converter somehow (since reflection isn't being used). We had to make similar changes to some of our own types to accommodate that scenario: https://github.com/dotnet/runtime/issues/81702

> Also, would this mean that I would have to expose all of my internals? For example, if JsonPointer used internal classes that had their own internal converters, do I need to also then expose those to support source gen?

I wouldn't think so, by default the serializer will only include the transitive closure of _public_ members found in `JsonPointer`, so these would necessarily have to be public as well. If any public type in that type graph uses a custom converter, that converter would need to be public as well though.

**Comment by gregsdennis** [comment]
Perfect. Thank you.
