### ISSUE TITLE
JIT: Missing zero initialization of stackallocs converted to locals for "init mem" mismatches during inlining

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#95056]
```csharp
using System;
using System.Runtime.CompilerServices;

public class Program
{
    public static void Main()
    {
        Foo();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Foo()
    {
        Span<byte> bytes = stackalloc byte[8];
        Console.WriteLine(bytes[0]);
    }
}
```

This program frequently prints a non-zero value. It should always print 0. The example is adapted from a customer reported example on the community Discord, where it was exposed by new inlining due to PGO in .NET 8.

When the caller does not have .locals init, but the callee does, we insert zero initialization here:
https://github.com/dotnet/runtime/blob/3b61ad9e3acb6302fd2fcef4947373475a0dcc29/src/coreclr/jit/fginline.cpp#L1952-L1994

This code does not handle the locals created by the stackalloc-to-local transformation, and the transformation itself also does not insert any zero initialization (which would likely be the easiest fix).

**Comment by kamronbatman** [comment]
I would like to request a backport to fix this for .NET 8 since our project is used on fairly substantial video game servers that have hundreds of concurrent users, and millions of objects. This bug causes corrupt data to be sent down the pipe which was really hard to track down, especially since in debug mode, and attaching a debugger deoptimized the code making it feel like the bug "magically disappeared."

Additionally, we have similar patterns for high performance serialization to memory/disk where data could be written that is corrupt causing bad save states and corrupting entire servers.

Also note, that even thought his bug apparently existed in previous versions of .NET, we specifically never fell into the trap until PGO was enabled by default on .NET 8.

Thanks and if i can help guinea pig this fix, I would love to!
