### ISSUE TITLE
Passing generic class with nullable reference type in JsonSerializableAttribute raises CS8620 when used

### ISSUE THREAD

**Issue by JenyaRostov** [dotnet/runtime#95083]
### Description

Take this class
```cs
[JsonSerializable(typeof(IDictionary<string, object?>))]
public partial class JsonContextTest : JsonSerializerContext { }
```
When used like this:
```cs
IDictionary<string, object?> d = new Dictionary<string, object?>()
{
    ["A"] = "b",
    ["D"] = 1,
    ["C"] = null
};
var b = JsonContent.Create(d, JsonContextTest.Default.IDictionaryStringObject);
```
It raises CS8620 `Argument of type 'System.Collections.Generic.IDictionary<string,object?>' cannot be used for parameter 'inputValue' of type 'System.Collections.Generic.IDictionary<string,object>?' in 'System.Net.Http.Json.JsonContent.Create<T>' because of differences in the nullability of reference types`
Generated code for JsonContextTest:
```cs
public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IDictionary<string, object>> IDictionaryStringObject
``` 
Notice the absence of `object?`
It does not raise any runtime errors however when using
My colleague is treating all warnings as errors so is there any way to avoid raising CS8620 besides `NoWarn`?

### Reproduction Steps

Create class
```cs
[JsonSerializable(typeof(IDictionary<string, object?>))]
public partial class JsonContextTest : JsonSerializerContext { }
```
Use it
```cs
IDictionary<string, object?> d = new Dictionary<string, object?>()
{
    ["A"] = "b",
    ["D"] = 1,
    ["C"] = null
};
var b = JsonContent.Create(d, JsonContextTest.Default.IDictionaryStringObject);
```

### Expected behavior

No warning raised

### Actual behavior

CS8620 is raised

### Configuration

.NET 8

**Comment by eiriktsarpalis** [comment]
This is by design -- the STJ source generator is nullable reference type agnostic but it still supports NRTs. You can safely suppress the warning at the callsite like so:
```C#
var b = JsonContent.Create(d, JsonContextTest.Default.IDictionaryStringObject!);
```

**Comment by JenyaRostov** [comment]
> This is by design -- the STJ source generator is nullable reference type agnostic but it still supports NRTs. You can safely suppress the warning at the callsite like so:
> 
> ```cs
> var b = JsonContent.Create(d, JsonContextTest.Default.IDictionaryStringObject!);
> ```

It works when adding `!` to `d` and not `IDictionaryStringObject`
Still, is there a way to not raise the warning at all?

**Comment by eiriktsarpalis** [comment]
Other than suppressing nullability warnings locally, not really. 

FWIW The source generator will intentionally discard any nullability annotations you might be putting on `JsonSerializableAttribute`. This is because the underlying metadata model being generated is being keyed on `System.Type` which cannot distinguish between `object?` and `object`.

In the future we should investigate having the source generator emitting nullable-oblivious JsonTypeInfo properties.

**Comment by RenderMichael** [comment]
> FWIW The source generator will intentionally discard any nullability annotations you might be putting on `JsonSerializableAttribute`. This is because the underlying metadata model being generated is being keyed on System.Type which cannot distinguish between `object?` and `object`.

This issue has led to usability problems for me, especially when working with people who are loath to suppress any nulls, especially when using an API idiomatically like this.

This justification is an implementation detail, and luckily doesn’t prevent NRTs from being used.

Would it be possible to just blindly pass along the same NRTs that were supplied?

**Comment by RenderMichael** [comment]
> NRT annotations are a very useful tool but cannot provide a complete representation of the actual run-time nullability semantics

That’s entirely true, and we have scenarios where, for example, the nullability of two locals are intertwined, and roslyn has stated tracking that is not realistic. My team understands that and we will suppress null warnings where we can justify it.

The difference with this issue is, this is the “standard” and intended way of using this API, and the API isn’t unsafe or niche or anything like that.

Thanks for the fix in .NET 9, this is already justification enough for my team to upgrade next year 😃

**Comment by eiriktsarpalis** [comment]
FWIW you wouldn't need to upgrade the SDK just to use the latest System.Text.Json features. You could try referencing the latest NuGet package instead (this fix should become available in Preview 1 coming in January).
