### ISSUE TITLE
Crash when allocating 4+ MB with high LOH threshold

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#95219]
### Description

I realized that there is no higher limit on `DOTNET_GCLOHThreshold` so I wondered how the GC would handle it if I tried to allocate 4+ MB with a LOH threshold that is bigger than that.

The application hangs with the memory usage continuously increasing. I didn't debug in detail, but it looks like the GC enters in an infinite loop where it tries to allocate a new 4MB basic region, only to find that the allocation doesn't fit in any available region.

### Reproduction Steps

Set `DOTNET_GCLOHThreshold=6400000` then run the code:

```csharp
var alloc = new byte[1024 * 1024 * 4];
```

### Expected behavior

Either of:
 - The array is successfully allocated in gen 0
 - The LOH threshold is capped at ~3 MB and the array is successfully allocated in LOH
 - The CLR refuses to start

### Actual behavior

The GC is stuck in a seemingly infinite loop, creating new regions.

### Regression?

The issue only happens with regions enabled.

### Known Workarounds

Reduce the LOH threshold or disable regions.

**Comment by mrsharm** [comment]
Thanks for reporting this, @kevingosse! I was able to easily repro this issue and are working on a fix to set an upper bound on the LOH Threshold to be < basic region size. Will link this issue with the fix and subsequently update the documentation.

Can you confirm that this is an OOM rather than an infinite loop by running your application via a shell? In all our repros, I am observing an OOM indicated by the message "Out of memory." printed to the console. 

## My Repro:

I printed out all the configuration variables to ensure that your LOH value is actually getting applied.

```csharp
 static void Main()
    {
        foreach (var d in GC.GetConfigurationVariables())
        {
            Console.WriteLine($"{d.Key}: {d.Value}");
        }

        var alloc = new byte[1024 * 1024 * 4];
    }
```
