### ISSUE TITLE
PeriodicTimer the first tick is instantaneous

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#95238]
### Description

In case the instantiation of a [`PeriodicTimer`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer) is not chronologically adjacent to the first `WaitForNextTickAsync` operation, this operation is immediately completed upon creation.

### Reproduction Steps

```C#
PeriodicTimer timer = new(TimeSpan.FromMilliseconds(500));
await Task.Delay(1000);
Console.WriteLine(timer.WaitForNextTickAsync().IsCompleted); // True
```

### Expected behavior

The `timer.WaitForNextTickAsync()` is expected to complete after 500 milliseconds. So the `IsCompleted` should be `false`.

### Actual behavior

The `timer.WaitForNextTickAsync().IsCompleted` is `true`. [Online demo](https://dotnetfiddle.net/whusGN).

### Regression?

No. Same behavior on all .NET 6, 7 and 8.

### Configuration

- .NET 8.0
- Console application
- 64-bit operating system, x64-based processor

**Comment by stephentoub** [comment]
This is by design. The timer starts when the instance is created, not when you call WaitForNextTickAsync. If the timer ticks before the call, it'll complete immediately. That's true even when it's not the first, eg if you call Wait and it completes, then you go away for longer than the period, the next call to Wait will also likely complete immediately.

**Comment by theodorzoulias** [comment]
Makes sense. Thanks for the clarification.
