### ISSUE TITLE
[API Proposal]: Vector256.ReplaceElementAt<T>(Int32 index, Vector256<T> vector, T newValue) Method

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#95316]
### Background and motivation

A similar method is Vector256.WithElement<T>(Vector256<T>, Int32, T), but it creates a new instance. The proposed method should only replace the value at the specified index, without creating a new instance. The method could be tagged/marked as unsafe to draw the attention of the programmer about the behaviour.

It's all about performance that will benefit Vector256<T> and Vector512<T>.

### API Proposal

```csharp
namespace System.Runtime.Intrinsics;

public static unsafe class Vector256
{
    public void ReplaceElementAt<T>(Int32 index, Vector256<T> vector, T newValue);
}
```

### API Usage

```csharp
// Create vector
Vector256<double> vector = Vector256.Create(0.0, 1.1, 2.2, 3.3);

// Replace value at index 1
Vector256.ReplaceElementAt(1, vector, 10.1);//Result: vector changes to <0.0, 10.1, 2.2, 3.3>
```

**Comment by huoyaoyuan** [comment]
> but it creates a new instance

Vector256 is a readonly struct type that maps to vector registers of CPU. There's no concept of "instance". With hardware accelerated instructions, it is more similar to an integer type. The compiler and CPU can manage how to store and use the values.

**Comment by tannergooding** [comment]
As indicated above, `Vector256<T>` (and other vector types) are intentionally readonly. They likewise intentionally do not allow mutation because they are primarily meant to be used when `Vector256.IsHardwareAccelerated` reports `true`. In that case, they are functionally "primitive" types, much like `int` or `float`, and as such should be treated as a single value (even if they contain many values).

Accordingly, `x = x.WithElement(index, value)` is the correct and most efficient way to work with vector data and we have no plans of exposing such an unsafe API like `ReplaceElementAt` or making the vectors mutable, as that would lead users into a pit of failure when working with these types.
