### ISSUE TITLE
PGO Instrumented SDK fails to load coreclr.dll

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#95534]
When trying to run `dotnet` runtime startup fails and prints the following error message

```
Failed to load the dll from [D:\git\dotnet-optimization\artifacts\out\sdk\x64\shared\Microsoft.NETCore.App\9.0.0-alpha.1.23577.7\coreclr.dll], HRESULT: 0x8007007E
```

You can obtain a copy of the instrumented SDK from [here](https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-alpha.1.23580.4/dotnet-sdk-pgo-9.0.100-alpha.1.23580.4-win-x64.zip). I took a quick look at this is `windbg`, but all I could find is that we were getting an access violation when this error is printed. I couldn't find any symbols so I don't know where we were in startup.

Tagging @jkotas for routing.

**Comment by jkotas** [comment]
This was broken by #89311. The problem is that the PGO instrumented coreclr.dll depends on pgort140.dll. pgort140.dll is copied locally next to coreclr.dll. The flag added by #89311 enforces that coreclr.dll can only depend on system .dlls. Locally copied pgort140.dll is not a system .dll and that leads to the coreclr.dll load failure.

@DrewScoggins @AustinWise @elinor-fung Do you have opinions about the best way to proceed?

I can think about two options:
- Try work to work around it by copying pgort140.dll to %WINDIR%\System32. It requires admin access and modifies global machine state on the machine that runs the optimization workloads that comes with a new set of problems. @DrewScoggins What do you think about that?
- Revert #89311 and ask the C++ team to ignore the DEPENDENTLOADFLAG mismatch between instrumented and non-instrumented builds. Try again once the C++ toolset is fixed.

**Comment by AustinWise** [comment]
Personally, I like the second option if it is available. The linker should be affected by the `/DEPENDENTLOADFLAG` flag, both when collecting and applying PGO data. And it should not care about differences in this flag between collection and application of PGO data. This would help our immediate problem in .NET as well as help anyone else using PGO.

In terms of risks of reverting #89311, the risk is low. This is a defense-in-depth type protection. Reverting it does not expose any known security problems. I don't believe BinSkim currently checks this flag, so CI should not complain.

**Comment by jkotas** [comment]
Ok, I have opened https://devdiv.visualstudio.com/DevDiv/_queries/edit/1924842/ (internal MS link) to get a fix in the linker. Let's revert https://github.com/dotnet/runtime/pull/89311 for now to get the PGO data flow unblocked.

**Comment by DrewScoggins** [comment]
This all sounds good to me. We are still waiting on this change to flow through to the installer, but once it makes it in I will make sure we get another run going to make sure this fixed the issue.
