### ISSUE TITLE
String interning broke with .NET 8?

### ISSUE THREAD

**Issue by chrischu** [dotnet/runtime#95675]
### Description

When running the following code
`(object) "2" == (object) 2.ToString()`
the result is `true` when running in .NET 7, but `false` when running in .NET 8.

### Reproduction Steps

Run `(object) "2" == (object) 2.ToString()`

### Expected behavior

Should return `true`

### Actual behavior

Returns `false`

### Regression?

Yes it worked in .NET 7.

### Known Workarounds

It is possible to use `.Equals` instead of `==`.

### Configuration

- .NET 8
- Windows 10
- x64
- Specific to .NET 8, probably not to Windows/x64

**Comment by stephentoub** [comment]
This is by design.

.NET 7 had an optimization where the strings for the digits 0 through 9 were precomputed and stored in a table, so comparing the references for "2" and 2.ToString() would return true because 2.ToString() was just accessing a "2" string out of a table. .NET 8 now optimizes the ToString()s for hundreds of int values (e.g. 0 through 299), but to avoid storing a bunch of strings it doesn't actually need, it populates them lazily, and as such, the resulting strings aren't the consts.

**Comment by chrischu** [comment]
Interesting! Thanks for the quick reply!

**Comment by fschmied** [comment]
@stephentoub Would it make sense if `ToString` used `string.Intern` upon that lazy population to avoid the breaking change? And wouldn't it make sense in general if those strings were interned?

(Okay, interning more than before could be considered as a breaking change, too, but to me too much inlining feels less likely to cause inconvenience than too little interning.)

**Comment by stephentoub** [comment]
We don't consider this "breaking" (most bug fixes are visible in some way). Why is this impactful to you? Strimg reference equality or inequality is a very dangerous thing to take a meaningful dependency on, as it can easily change due to name levels of the stack.

**Comment by fschmied** [comment]
It makes sense to me that you don't classify such a change as breaking. I was just wondering if it wouldn't generally be a good idea to intern those lazily cached `int.ToString()` results. Apparently there was a design decision to not do it when reimplementing the cache for .NET 8 and I'd like to understand it. Or was it just a "don't care" thing?

**Comment by MichalPetryka** [comment]
> It makes sense to me that you don't classify such a change as breaking. I was just wondering if it wouldn't generally be a good idea to intern those lazily cached `int.ToString()` results. Apparently there was a design decision to not do it when reimplementing the cache for .NET 8 and I'd like to understand it. Or was it just a "don't care" thing?

Caching every single ToString would make DoS attacks way easier, attackers could just cause servers to allocate millions of strings and OOM.

**Comment by fschmied** [comment]
I'm only talking about the specific `int.ToString()` results that Stephen mentioned earlier (".NET 8 now optimizes the ToString()s for hundreds of int values (e.g. 0 through 299)"). I understand those are already cached?

**Comment by fschmied** [comment]
>> I was just wondering if it wouldn't generally be a good idea to intern those lazily cached int.ToString() results
>
> Why?

Well, there are probably no large benefits, but there are a few small ones - and as far as I can see there is no _disadvantage_ in this case, or is there? One could say, as a general rule, that interning is better than not interning if it has no disadvantages?

The small benefits in this case I can think of right now:
* It avoids a small bit of wasted memory (in case a program uses both `int.ToString()` and the corresponding string literals).
* It provides reference equality as a fast path in string comparisons.
* It keeps reference equality for those cases where it existed in .NET 7.

However, I've now taken a look at the [.NET 7 implementation of the cache](https://github.com/dotnet/runtime/blob/v7.0.14/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L269) and have noticed my mistake. I thought that .NET Core up to .NET 7 had interned the values on purpose and was thus assuming an explicit decision to stop doing so in .NET 8. Instead, the values were likely interned by accident, just because the code in question used literal strings, which the current implementation no longer does.

So, my question was built on an invalid assumption, sorry.

**Comment by danmoseley** [comment]
No need to apologize! Good discussion. BTW you are welcome to contribute here if you like.
