### ISSUE TITLE
upgrade to .net 8.0 error CS8347, How to solve it? please.

### ISSUE THREAD

**Issue by qcbf** [dotnet/runtime#95686]
<img width="1303" alt="1701869099215" src="https://github.com/dotnet/runtime/assets/3467543/a53d2b79-22b5-4d4d-b8c7-d89063f49c75">

**Comment by joegoldman2** [comment]
You can use the `scoped` keyword:

```diff
- public static ReadOnlySpan<char> SegmentTextReadWithMoveNext(ref ReadOnlySpan<char> text, string breaks = ",/|+")
+ public static ReadOnlySpan<char> SegmentTextReadWithMoveNext(scoped ref ReadOnlySpan<char> text, string breaks = ",/|+")
```

**Comment by huoyaoyuan** [comment]
This is caused by reference lifetime rule update in C# 11 (.NET 7). See https://learn.microsoft.com/dotnet/csharp/whats-new/csharp-11#ref-fields-and-ref-scoped-variables and https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/low-level-struct-improvements#scoped-modifier .

Updating the parameter of `SegmentTextReadWithMoveNext` to `scoped ref ReadOnlySpan<char>` solves the error. **However, in this case you should not pass the span as `ref` because it harms performance.** Even if you are passing modification to caller, it's suggested to return the span instead of modifying in-place.

You should also check the new `MemoryExtensions.Split(ReadOnlySpan<char>, ...)` methods in .NET 8 that makes similar functionality.

**Comment by qcbf** [comment]
> This is caused by reference lifetime rule update in C# 11 (.NET 7). See https://learn.microsoft.com/dotnet/csharp/whats-new/csharp-11#ref-fields-and-ref-scoped-variables and https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/low-level-struct-improvements#scoped-modifier .
> 
> Updating the parameter of `SegmentTextReadWithMoveNext` to `scoped ref ReadOnlySpan<char>` solves the error. **However, in this case you should not pass the span as `ref` because it harms performance.** Even if you are passing modification to caller, it's suggested to return the span instead of modifying in-place.
> 
> You should also check the new `MemoryExtensions.Split(ReadOnlySpan<char>, ...)` methods in .NET 8 that makes similar functionality.

thank very much
