### ISSUE TITLE
Strange behavior of Dictionary initializer

### ISSUE THREAD

**Issue by alexbembel** [dotnet/runtime#96011]
### Description

I ran through an interesting behavior of dictionary short initializer form. It looks like the initializer does not create a new Dictionary object, rather just adds elements to already existing object, effectively ignoring "=" statement. The following code crashes rather than just creating a Person class object.

In case this behavior is interpreted to be by design, please ignore this bug report.

### Reproduction Steps

var person = new Person()
{
    Inventory = { { "apples", 1 } }
};

class Person
{
    public Dictionary<string, int> Inventory { get; set; } = new()
    {
        { "apples", 0 },
    };
}

### Expected behavior

I was expecting to get a Person object having "apples" in his/her inventory.

### Actual behavior

ArgumentException exception: 'An item with the same key has already been added. Key: apples'

### Known Workarounds

This code works as intended:

var person = new Person()
{
    Inventory = new() { { "apples", 1 } }
};

**Comment by eiriktsarpalis** [comment]
This is by design. Using this syntax
```C#
var person = new Person()
{
    Inventory = { { "apples", 1 } }
};
```
Will try to append a new entry to the existing dictionary via the `Add` method which will fail because a conflicting entry already exists. In order to get the desired behaviour you could try writing the following instead:
```C#
var person = new Person()
{
    Inventory = new() { { "apples", 1 } }
};
```
The obvious downside is that you'd now be allocating two dictionaries instead of one. 

If you want to use object initializer syntax on list/dictionary types, my recommendation would be to design your properties such that they are initialized to an empty collection. This should ensure fewer surprises for users of your types.

**Comment by gregsdennis** [comment]
Note that you can still use this syntax (I think; haven't tested).

```c#
var p = new Person {
    Inventory = { ["apples"] = 1 }
};
```

I believe this calls the indexer instead of the `.Add()` method to add/update the value, which avoids the exception.

**Comment by gregsdennis** [comment]
(not really sure how this got labeled as an STJ issue, though)
