### ISSUE TITLE
failure assigning ulong to decimal

### ISSUE THREAD

**Issue by aavaav** [dotnet/runtime#96152]
### Description

This code gives wrong result: 

ulong DE004_Tran_Amount = 1500;
decimal tranAmount = 0 - DE004_Tran_Amount; 

### Regression?

with .NET 6 result is correct

### Other information
This fixes the problem:

decimal tranAmount = 0;
tranAmount  -= DE004_Tran_Amount;

**Comment by tannergooding** [comment]
This code:
```csharp
ulong DE004_Tran_Amount = 1500;
decimal tranAmount = 0 - DE004_Tran_Amount;
```

Is equivalent to doing:
```csharp
ulong DE004_Tran_Amount = 1500;
ulong tmp1 = 0;
ulong tmp2 = tmp1 - DE004_Tran_Amount;
decimal tranAmount = tmp2;
```

Which is to say, `DE004_Tran_Amount` is a `ulong` and `0` is an integer literal. The operation `0 - DE004_Tran_Amount` therefore treats `0` as a `ulong` and thus gives you `18446744073709550116` (as `0UL - 1UL` produces `ulong.MaxValue`). This is because binary operations have a higher precedence than assignment operations, so the implicit conversion happens after.

Then that result is upcast to `decimal`, giving you `18446744073709550116.0M`

You can force this to behave more as expected by using `0M` or `0.0M`, which ensures that the subtraction operation is treated as `decimal` instead, and thus the code is more similar to:
```csharp
ulong DE004_Tran_Amount = 1500;
decimal tmp1 = 0;
decimal tmp2 = (decimal)(DE004_Tran_Amount);
decimal tranAmount = tmp1 - tmp2;
```

**Comment by aavaav** [comment]
Hi,  
There is just one mathematical fact: It is that 0 -1500 is equal to: -1500. 

if the system is giving a different result, it is called a BUG that needs to be investigated and fixed. The incident should not be close. 

Sorry, but all the explanation about integers, ulong,  precedence, binary, does not fix the BUG.

I reported the BUG just to help the community.

**Comment by danmoseley** [comment]
@aavaav agreed it is a bug, but respectfully, we the bug is in the calling code, as described above.

**Comment by tannergooding** [comment]
> There is just one mathematical fact: It is that 0 -1500 is equal to: -1500.

This only holds true when considering the type of standard math most people are familiar with and does not hold true when considering the broader domains of mathematics and various constraints that can be placed on the computation. For example, when purely considering the natural number domain, negatives do not exist. The same as when considering the real number domain, the result of `sqrt(-1)` doesn't exist, but this becomes "well defined" when you move into the complex number domain.

"Computer Math" != "Real Math", it does not have the benefit of having infinite time or space, nor the complexities of the human brain where one can trivial represent abstract concepts using symbolism. As such, it places constraints against the representation and uses types with defined limits and behaviors when those limits are reached.

Most computers and most programming languages implement their integer types as two's complement values using a fixed number of bits. The types provided are most often signed in nature, but many also provide a set of types that can be exclusively unsigned. The behavior of these types when reaching the boundary value is to "wrap around" from the maximum to the minimum, or vice versa.

Telling time or measuring angles work much the same way where they operate in a constrained system and where you encounter this wrap around behavior. A circle is 360 degrees, where 360 == 0. A clock has the numbers 1-12 or there are 24 hours in a day and while one can define a 25th hour, it is better and more typically defined as the 1st hour of the next day.

As such, when working with languages like C# (but this also applies to most C/C++ implementations, Java, Rust, and many other languages), one must be aware of the precision of the types you are working with and what happens when reaching a boundary value. For a language like C, C++, C#, and Rust where unsigned types exist, this means that `0 - 1500` will not produce `-1500`, but rather will produce `MaxValue - 1500 + 1`. It is then a bug on the user's code for not having accounted for this overflow/underflow behavior.

**Comment by aavaav** [comment]
Hi, this instruction.

decimal tranAmount = 0 - DE004_Tran_Amount.

should assign a value from the right to the left and no more.  and the value of the right must be -1500.  If it is not -1500 is a bug but not in the line of code above. 

I have no problem anymore; I'm using something like this:

decimal tranAmount = 0;
tranAmount -= DE004_Tran_Amount; 


and I have -1500

Thank you, Dan, and Happy new year.

**Comment by svick** [comment]
> the value of the right must be -1500.

It can't be. When the type of `DE004_Tran_Amount` is `ulong`, the type of `0 - DE004_Tran_Amount` is also `ulong`, so it can't possibly represent a negative value. Only once that `ulong` value is computed, it can be converted to `decimal`.

It sounds like you want target typing: the compiler sees that the expression is assigned to a `decimal` variable, so it performs the calculation using `decimal`s. That might be a reasonable behavior in some languages, but it's not in C#, with its C/C++/Java heritage (which all behave like this).

**Comment by aavaav** [comment]
Dear Tanner, 

I really enjoyed your article. I loved math.  

The problem is incompatibility between .NET 6 and 8.  So, there is a BUG in one or the other. In my opining the BUG was introduced in 8. We test in development before moving to production, so we were not affected. But running the original code will credit millions to customers while processing ATM reversal transaction.
Subtracting and amount from zero to obtain a negative value was an old trick to avoid multiplying the amount by -1.  Addition or substructions should be faster than multiplication. Faster computers let us forget the need to think on performance, but cloud computing is remembering it.  

Happy 2024

**Comment by tannergooding** [comment]
> The problem is incompatibility between .NET 6 and 8

A trivial reproduction does not work in .NET 6, .NET 8, or even going back to .NET Framework. In all 3 cases the following program prints `18446744073709550116`:
```csharp
        ulong DE004_Tran_Amount = 1500;
        decimal tranAmount = 0 - DE004_Tran_Amount;
        Console.WriteLine(tranAmount);
```

> But running the original code will credit millions to customers while processing ATM reversal transaction.

Arithmetic overflow/underflow is something your code may need to be robust against, especially if it operates in a financial market.

> Subtracting and amount from zero to obtain a negative value was an old trick to avoid multiplying the amount by -1.

There are many ways to get a negative value, including simply doing `-x`. All of them require the type be signed and had you down the naive `decimal tranAmount = -DE004_Tran_Amount`, you would have seen `CS0023: Operator '-' cannot be applied to operand of type 'ulong'`.

This failure is all because you are performing an operation on a type that is explicitly unsigned and where negative values cannot be represented. You need to be explicit about your types and use signed types where you expect negative values to exist.
