### ISSUE TITLE
TLS session resumption on Linux clients using client-side certificates

### ISSUE THREAD

**Issue by CaringDev** [dotnet/runtime#96164]
### Description

In #64369 client-side TLS resumption using session tickets was implemented. However, according to https://github.com/dotnet/runtime/issues/22977#issuecomment-1118216257 using client-side certificates prevents resumption.

As I couldn't find an open (commentable) issue about this, I dare to open this new one to gauge interest and ask @wfurt "Could you give a rough estimate of what would be needed to make the client-certificate use case work?"

### Configuration

Linux

### Regression?

No

### Motivation

We have to deploy a side-car NodeJS container as a proxy for accessing a service that forces its users to support resumption.

**Comment by rzikm** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/94561. Can I ask you to comment/upvote that issue? Thanks.

**Comment by CaringDev** [comment]
Whaaat... how did I miss that one 🤦‍♂️
So sorry... many thanks!

**Comment by wfurt** [comment]
Just to answer here since you asked @CaringDev:
This will need some more thinking and testing. I'm concern about cases when we unintentionally restore session with wrong certificate. When you only have once identity for any given server it is pretty simple. But if you have multiple services running on different port (SslStream does not have access to EndPoint) or if you want to maintain multiple identities to same service things do get more tricky. 

There may be some incremental improvement IMHO. For example `sslAuthenticationOptions.ClientCertificates?.Count == 1` may be simple and safe. I feel @rzikm has it on his radar and may see improvements in 9.0. Cases with `CertSelectionDelegate` may be more tricky.  

Certainly describing the intended use would be helpful for us. As minimal to think through test cases and behaviors we may miss otherwise.
