### ISSUE TITLE
NaN arithmetic is not consistent with the IEEE 754 standard.

### ISSUE THREAD

**Issue by DenisParal** [dotnet/runtime#96246]
### Description

The problem is when adding two NaNs the result is left operand (when adding signaling NaN and quiet NaN the result is signaling NaN) but according to the IEEE 754 standard the result should be quiet NaN.

"For an operation with quiet NaN inputs, other than maximum and minimum operations,
if a floating-point result is to be delivered the result shall be a quiet NaN which should be one of the input
NaNs."

One more point is what behavior we expect when adding signaling NaN and another floating value (not quiet NaN)?
Currently the result is signaling NaN on x64 but it is quiet NaN on RISC-V.

### Reproduction Steps

```
public class Program
    {
        public static void Main()
        {
            Test();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Test()
        {
            float sNaN = BitConverter.Int32BitsToSingle(0x7FD55555); // sNaN
            float qNaN = BitConverter.Int32BitsToSingle(0x7FC00000); // NaN
            float res1 = sNaN + qNaN;
            float res2 = qNaN + sNaN;
            Console.WriteLine(BitConverter.SingleToInt32Bits(res1).ToString("b32"));
            Console.WriteLine(BitConverter.SingleToInt32Bits(res2).ToString("b32"));
        }
    }
```

### Expected behavior

Expected result:
01111111110000000000000000000000
01111111110000000000000000000000

### Actual behavior

01111111110101010101010101010101
01111111110000000000000000000000

### Configuration

* 9.0.100-alpha.1.23524.3
* Ubuntu22.04
* x64 (probably x86, arm, arm64)

### Other information

Part of https://github.com/dotnet/runtime/issues/84834
cc @tannergooding

**Comment by DenisParal** [comment]
cc @gbalykov @t-mustafin

**Comment by gbalykov** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
> "For an operation with quiet NaN inputs, other than maximum and minimum operations,
if a floating-point result is to be delivered the result shall be a quiet NaN which should be one of the input
NaNs."

This is from the 2008 specification and no longer exists in the 2019 specification. This was explicitly relaxed because many systems did not force propagation of a quiet NaN, particularly when IEEE 754 exception handling was disabled and therefore the signal was never raised.

The specification now simply defines it as the following:
> 6.2.3 NaN propagation
>
>An operation that propagates a NaN operand to its result and has a single NaN as an input should produce a
NaN with the payload of the input NaN if representable in the destination format.
>
> If two or more inputs are NaN, then the payload of the resulting NaN should be identical to the payload of
one of the input NaNs if representable in the destination format. This standard does not specify which of
the input NaNs will provide the payload.
>
> Conversion of a quiet NaN from a narrower format to a wider format in the same radix, and then back to
the same narrower format, should not change the quiet NaN payload in any way except to make it
canonical.
>
> Conversion of a quiet NaN to a floating-point format of the same or a different radix that does not allow
the payload to be preserved shall return a quiet NaN that should provide some language-defined diagnostic
information.
>
> There should be means to read and write payloads from and to external character sequences (see 5.12.1).
Except for the operations specified otherwise in 5.5, a NaN result shall be canonical, even if that NaN
result were derived from a non-canonical NaN operand.

The general intent of a "signaling NaN" is to allow an exception to be raised one time when the value is processed as an input to certain types of functions. Once that exception has been raised, the signalling bit is meant to be stripped, making it a "quiet NaN", so that exceptions are not continuously raised any time the value is touched.

However, many systems have opted not to use that functionality at all in order to simplify the implementation or improve performance. Thus, while there are many "recommended" operations detailed throughout the 1985, 2008, and 2019 specs, a number of them are not guaranteed and is covered in the "Literal meaning and value-changing optimizations" and "Reproducible floating-point results" sections where it covers things like:
* "Changing the payload or sign bit of a quiet NaN." is considered a value-changing transformation which preserves the literal meaning of the source code
* "Do not depend on quiet NaN propagation, payloads, or sign bits."
* "Do not use signaling NaNs."
* etc

.NET does not support IEEE 754 exceptions (doesn't support signaling NaN and treats it the same as quiet NaN) and we cannot guarantee or depend on which NaN input is propagated back out.

**Comment by DenisParal** [comment]
@tannergooding, sorry for bothering you but could you clarify what behavior do we want to have for all arches? Payload propagation as you mentioned in your comment?

**Comment by tannergooding** [comment]
Up until now we've typically tried to propagate NaNs as is where possible, but its almost impossible to guarantee any particular behavior and the IEEE 754 spec doesn't require (only recommends) a particular behavior.

Some platforms like RISC-V may force normalization of NaNs. Other platforms may or may not do things like strip the signalling bit. There's also cases where things like `NaN + NaN` could return either NaN and there is no guarantee over which is propagated.

So for NaN in particular it is effectively forced to be semi-flexible and we can only guarantee that some NaN will be returned
