### ISSUE TITLE
DotNet doesn't respect encoding of Chinese strings?

### ISSUE THREAD

**Issue by ly-nld** [dotnet/runtime#96348]
Hello, I am have been trying for a while to compile a project 
https://github.com/ly-nld/ja-learner

Using this GitHub action:
https://github.com/ly-nld/ja-learner/blob/naifaufiwafwa/.github/workflows/ubuntu.yml

But it doesn't encode Chinese characters properly and it ends up being a garbled mess.
![293053914-f8875849-42ce-450b-89e6-f4a4a359c4da](https://github.com/dotnet/runtime/assets/38471793/68ed0a01-948c-46a3-8b9c-5bb4e7fd056d) (from https://github.com/ks233/ja-learner/pull/4 )

Sorry if this isn't the right place.

**Comment by MichalPetryka** [comment]
This is because you use Auto (which defaults to ANSI) encoding here:
https://github.com/ks233/ja-learner/blob/72cf199dcd9cfbaff8c7cc7dd5b4d65adf56a2be/WindowAttacher.cs#L23-L27

If you want your code to work reliably with non ASCII text on different machines, you should use Unicode encoding and the `W` API variants (like `GetWindowTextW`) everywhere.
Using StringBuilders and built-in marshalling with PInvokes is also discouraged these days, you should probably use NativeMemory.Alloc or an array there and create a string from it using a ReadOnlySpan with the length returned from `GetWindowTextW`

**Comment by huoyaoyuan** [comment]
You can also use https://github.com/Microsoft/CsWin32 to generate the most "correct" code for Windows API.

**Comment by ly-nld** [comment]
The issue has been resolved.
