### ISSUE TITLE
[API Proposal]: Add a simple option to inject the default/system TimeProvider.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/runtime#96717]
### Background and motivation

C# finally has [`TimeProvider`](https://learn.microsoft.com/en-us/dotnet/api/system.timeprovider?view=net-8.0), that's great.

However, we still require that applications manually wire up their own clocks.  Given that time is such an integral part of most applications, it would be great if the system time provider was one of the default services wired up (ie, by `HostApplicationBuilder`).  Given that in almost all cases the system time is the "correct" choice this presents a suitable default, and then all that would be required is overriding it for those rare cases where it's not what the customer actually needs.

### API Proposal

```diff
public partial interface IHostEnvironment
{
+    System.TimeProvider TimeProvider { get; }
}
```

### API Usage

By default, the application should wire up the host/system default time provider, so there wouldn't be any explicit usage of the API.

### Risks

We would need to ensure that the default is overriden if a time provider is being injected by already deployed applications.

**Comment by steveharter** [comment]
Without a new API, the solution today is a one-liner:
```cs
builder.Services.AddSingleton(TimeProvider.System);
```

so I don't see much benefit.

Also we can't add a new member to an interface (`IHostEnvironment`) since that is a breaking change. Normally we could use Default Interface Methods to prevent that breaking change, but since `IHostEnvironment` is used on .NET Framework (which doesn't support DIMs) that is not an option. We would need a new interface.
