### ISSUE TITLE
Update pinned System.Reflection.Metadata and System.Collections.Immutable versions to 8.0.0

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#96809]
Wait until VS 17.9 is broadly available

Just one hit of many:
https://github.com/dotnet/runtime/blob/89411b708ceb38e1cc5699fe8ac98d2312688a78/src/installer/managed/Microsoft.NET.HostModel/Microsoft.NET.HostModel.csproj#L22-L23

**Comment by am11** [comment]
Related info from @rainersigwald: https://github.com/dotnet/runtime/pull/97021#issuecomment-1904515180

Current situation is that we are out of sync:

`https://github.com/dotnet/runtime/blob/48ae7e11727d0d2c77e5468cc5aa631816b7eadc/src/installer/managed/Microsoft.NET.HostModel/Microsoft.NET.HostModel.csproj#L22-L23` => 6.0 hardcoded

`https://github.com/dotnet/runtime/blob/48ae7e11727d0d2c77e5468cc5aa631816b7eadc/src/tasks/Microsoft.NET.WebAssembly.Webcil/Microsoft.NET.WebAssembly.Webcil.csproj#L18-L21` => 7.0 central version

`https://github.com/dotnet/sdk/blob/87edfcb2fba7334fedd0a4fdc3d1b319047dea67/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj#L74` => 7.0 hardcoded

`https://github.com/dotnet/msbuild/blob/d51ae5297cd0a24caa8cfe356442cc8634c3f087/eng/Version.Details.xml#L29` => 8.0 (and assembly redirect is 0.0-8.0) central version + hardcoded assembly redirect

but it seems to be accidentally working (due to the assembly redirect in msbuild?)

Not sure what's the best way to keep them in sync aside from manual follow-up once in a while.
