### ISSUE TITLE
Large MacOS deployed size with NativeAOT including large __LINKEDIT file

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/runtime#96997]
### Description

Our MacOS app has a v large size on disk

### Reproduction Steps

No repro available

### Expected behavior

Small app size <100MB

### Actual behavior

Large app size > 500MB

Pkg file:

https://summatic-my.sharepoint.com/:u:/g/personal/charles_roddie_summatic_co_uk/EetAMNrqTgdCkHCSsHGFc0QBCloYPh3_B8l8Il8Q24lIbw?e=flaauH

This is small 78MB but unzips to 530MB
__LINKEDIT file of approx 400MB is the large part of this.

### Other information

Related to the fixed issue https://github.com/dotnet/runtime/issues/86707

**Comment by charlesroddie** [comment]
Binlog here: https://summatic-my.sharepoint.com/:u:/g/personal/charles_roddie_summatic_co_uk/Ea4QM7BxaapOuNU0I6Iqky0B4YIapF_STmCXQecSdqFgYg?e=6CYpLO

**Comment by ivanpovazan** [comment]
@charlesroddie from the attached binlog it seems like you are using CoreCLR instead of NativeAOT when building your application. 
<img width="939" alt="Screenshot 2024-01-18 at 11 22 08" src="https://github.com/dotnet/runtime/assets/55002338/423cc3a8-85eb-4741-9b3a-69bab867beda">


<img width="1003" alt="Screenshot 2024-01-18 at 11 23 18" src="https://github.com/dotnet/runtime/assets/55002338/a9355e99-278a-4fc4-8d7a-bcfefd3a9d18">



Is this maybe a wrong binlog, or the reported issue was not marked correctly?

**Comment by charlesroddie** [comment]
Ah sorry we didn't have release mode set for that binlog. Here is a good one: https://summatic-my.sharepoint.com/:u:/g/personal/charles_roddie_summatic_co_uk/EeGon9HW6E1JiJaWotcYCZkB1b4IP-iYZPQ5CtiQ9jGp7g?e=kns14d

**Comment by ivanpovazan** [comment]
This seems to be a Xamarin build issue.

The large __LINKEDIT segment (most of the space goes for the `LC_SYMTAB` command storing all the symbols in the Mach-O file) comes from the fact that we do not strip binaries (invoking the `_NativeStripFiles` post process build task) when targeting MacOS with Xamarin. 

This is happening, because in MacOS builds we set `NoSymbolStrip=true`: https://github.com/xamarin/xamarin-macios/blob/d00a1907666ff0ceabcc21ff0ceb83b44f689b54/msbuild/Xamarin.Shared/Xamarin.Shared.props#L238-L241

@rolfbjarne do you know what is the reason for this? 

--- 
@charlesroddie, could you try building your application by passing `-p:NoSymbolStrip=false` on a command line, or set the property in your project file:
```xml
<NoSymbolStrip>false</NoSymbolStrip>
```
and see if it helps?

**Comment by charlesroddie** [comment]
Thanks! `<NoSymbolStrip>false</NoSymbolStrip>` resolves the problem.

**Comment by ivanpovazan** [comment]
Closing as setting the appropriate property solved the issue.
Opened https://github.com/xamarin/xamarin-macios/issues/19864 as a follow-up.

**Comment by tipa** [comment]
So glad I found this thread as I also was blown away by the huge file size when trying out NativeAOT for macOS (after getting such small file sizes when using it on iOS). I thought it was because the AOT-compiled code was just so much larger than the IL code...
Now (with stripping symbols) I get ~10% smaller bundle sizes when using NativeAOT compared to a fully trimmed JIT app
