### ISSUE TITLE
Nuget package "System.DirectoryServices 8.0" is not compatible to .NET6

### ISSUE THREAD

**Issue by WolfgangHG** [dotnet/runtime#97094]
### Description

"System.DirectoryServices.dll" from Nuget package "System.DirectoryServices" 8.0.0 references a .NET8 framework DLL and thus might fail to load in .NET6 or .NET7 environment.

We have code in our .NET6 application that tries to load all referenced DLLs recursively, and it fails because it does not find "System.Security.Permissions, Version=8.0.0.0". Probably, this error could also occur if code from this dll is used at runtime. 

The previous version 7.0 of System.DirectoryServices references the .NET6 framework dll.

The nuget page states that 8.0 is compatible with .NET6 and, .NET7, which is actually wrong. And updating to the new package is suggested in .NET6 applications.
![image](https://github.com/dotnet/runtime/assets/138049/6ed91c99-189a-46d1-a292-d3858257ef26)

### Reproduction Steps

See attached zip: it contains two .NET6 projects, one referencing System.DirectoryServices 7.0.1, the other 8.0. Both samples loop over all referenced assemblies of "System.DirectoryServices.dll" and report the versions.
The sample "DirectoryServicesTest8" also tried to load "System.Security.Permissions"
[DirectoryServicesTest.zip](https://github.com/dotnet/runtime/files/13963614/DirectoryServicesTest.zip)

### Expected behavior

Version 8.0 of the package should work with .NET6.

### Actual behavior

Dependencies of System.DirectoryServices.dll are not available in .NET6.

**Comment by steveharter** [comment]
> The sample "DirectoryServicesTest8" also tried to load "System.Security.Permissions"

For 8.0, this was addressed by https://github.com/dotnet/runtime/pull/82453.

However, from your repro:
- The 6.0 project is pulling in the 7.0 version of S.S.P.
- The 7.0 project is pulling in the 8.0 version of S.S.P.

Thoughts? @ViktorHofer @ericstj

**Comment by ericstj** [comment]
> We have code in our .NET6 application that tries to load all referenced DLLs recursively, and it fails because it does not find "System.Security.Permissions, Version=8.0.0.0".

`System.Security.Permissions` is an intentional dangling dependency from `System.DirectoryServices`.   See https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/directoryservices-package

>  Probably, this error could also occur if code from this dll is used at runtime.

The only case it would happen at runtime is if someone is using the obsolete type [DirectoryServicesPermission](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.directoryservicespermission?view=dotnet-plat-ext-8.0)

> The previous version 7.0 of System.DirectoryServices references the .NET6 framework dll.

As @steveharter also pointed out the 7.0 version of the package referenced the 7.0 version of `System.Security.Permissions`.  From your sample you can see this as it prints the 7.0.0.0 version when running the 6.0 app.

> System.Security.Permissions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

`System.Security.Permissions` is not a framework dll - its delivered via a nuget package just like DirectoryServices.  All we did in the 8.0 release was remove that package reference to avoid folks bringing a large set of legacy assemblies.  If you actually need the `DirectoryServicesPermission` type - then reference the 'System.Security.Permissions` package.

For the purposes of your code that's trying to pre-load dependencies - I'd recommend just ignoring the missing dependency.  It's not uncommon for our libraries to have dangling dependencies for type-forwards like this.  If you look at the assemblies in the shared framework (mscorlib, system, system.core) you'll notice they all have dangling references to types we've moved out.

**Comment by WolfgangHG** [comment]
@ericstj Thanks for the detailed explanation, I added code to ignore System.Security.Permissions 8.0 for our preloading.

Closing this issue.
