### ISSUE TITLE
[API Proposal]: Making ConfigurationKeyNameAttribute easier to use

### ISSUE THREAD

**Issue by Evgeny608799** [dotnet/runtime#97164]
### Background and motivation

I suggest making the `Microsoft.Extensions.Configuration.ConfigurationKeyNameAttribute` attribute more convenient by adding the `System.Runtime.CompilerServices.CallerMemberNameAttribute` attribute to the [constructor parameter](https://github.com/dotnet/runtime/blob/a7b63ae925d7aa8c89039636b9fef2d5512a2642/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/ConfigurationKeyNameAttribute.cs#L18C6-L18C6), so that I do not have to constantly write the property name if I want to make the section name the property name.

### API Proposal

```diff
namespace Microsoft.Extensions.Configuration
{
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class ConfigurationKeyNameAttribute : Attribute
    {
-       public ConfigurationKeyNameAttribute(string name) => Name = name;
+       public ConfigurationKeyNameAttribute([System.Runtime.CompilerServices.CallerMemberName] string name = "") => Name = name;  // Use the System.Runtime.CompilerServices.CallerMemberNameAttribute

        public string Name { get; }
    }
}
```

### API Usage

```csharp

public class MyClass
{
// It is not necessary to explicitly specify the name in the attribute, but use the default member name
    [ConfigurationKeyName()]
    public string NamedProperty { get; set; }
// It will also be possible to detect traces of the name we need
    [ConfigurationKeyName("NamedProperty2")]
    public string NamedProperty2 { get; set; }
}
```

**Comment by tarekgh** [comment]
@bartonjs when adding `[System.Runtime.CompilerServices.CallerMemberName]` to the constructor parameter and making the parameter nullable, is it considered a breaking change?

**Comment by bartonjs** [comment]
> is it considered a breaking change?

So long as the position of the argument doesn't have to change, no.  So, in this case, not a break.

Existing compiled modules will make the call just fine, new compiled modules will see the call as having an optional parameter, but the compiler inserts the parameter at compile time (not just because it says CallerMemberName).

For a source generator consuming this attribute, defaulting the parameter would be a logic break, as they'd need to know what a null value meant.  But, since it's combined with `[CallerMemberName]`, the compiler actually updates the call to pass in the string of the name; so a source generator won't need to react at all.

The nullability annotations here do mean that passing an explicit `null` won't get a warning.  You might want to make it use `null!` instead of `string?`, so

```C#
namespace Microsoft.Extensions.Configuration
{
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class ConfigurationKeyNameAttribute : Attribute
    {
        // Use the System.Runtime.CompilerServices.CallerMemberNameAttribute
        public ConfigurationKeyNameAttribute(
            [System.Runtime.CompilerServices.CallerMemberName] string name = null!) => Name = name;

        public string Name { get; }
    }
}
```

To continue saying "null is bad".

**Comment by tarekgh** [comment]
> To continue saying "null is bad". (You could also do string name = "", if you don't like null!)

I like the suggestion to use empty string instead of null. Thanks for confirming there is no breaking change with this proposal. 

@Evgeny608799 I'll update the proposal to use empty string if you don't have strong objection.

**Comment by tarekgh** [comment]
@Evgeny608799 what would be the benefit of anyone specifying the attribute with empty parameter? would using the attribute at all in such cases give the same result?

**Comment by Evgeny608799** [comment]
@tarekgh I think being able to explicitly specify the elements that will be mapped can make the code clearer.

**Comment by tarekgh** [comment]
To be honest, I don't see much benefit in marking the property with `ConfigurationKeyName` if the key name remains unchanged during binding. I'll close this request for now, but we can revisit it if there's a noticeable demand in the future. Thanks for your report.
