### ISSUE TITLE
Suggestion: Runtime support for faster BigInteger

### ISSUE THREAD

**Issue by lskyum** [dotnet/runtime#97199]
I love C# and usually it's "fast enough" compared to lower level languages. But I have encountered a performance case, where it seems impossible to achieve even slightly comparable performance to C++ and Rust.

Some of my geometric calculations heavily relies on fractions, which I calculate with two BigInteger's. But this is relatively slow and my tests shows that this is at least x10 slower than the C/C++ library GMP and similar Rust libraries. Viewing the code for C# BigInteger, it's clear that the author is really skilled in both math and low level C# optimizations, so it's probably not possible to do any better?

There exists C# wrappers around GMP, but the overhead itself makes the performance slightly _worse_ than just sticking with BigInteger. So my only option seems to be, to rewrite the calculations in C++ or Rust, which I really don't want to. Not only because it's tedious, but because I love C# ;-)

So the suggestion is to make BigInteger a Runtime optimized type that uses GMP (or similar) under the hood. Also the addition of a Runtime optimized BigFraction would be awesome. Obviously it will not beat C++ or Rust, but if the difference was x2 instead of x10, then it would be a game changer. It would open possibilities for making libraries like CGAL (https://www.cgal.org/) in C#. 

Since I'm not a Runtime engineer I can't say if this is even possibly or how it should be done.

**Comment by huoyaoyuan** [comment]
See the discussion in https://github.com/dotnet/runtime/issues/92184#issuecomment-1722521610

**Comment by lskyum** [comment]
@tannergooding Any chance of a BigFraction that takes advantage of the same highly optimized internal code from BigInteger? :-)

**Comment by huoyaoyuan** [comment]
> the same highly optimized internal code from BigInteger?

BigInteger is optimized, but it's not essentially "internal". It's not in the CoreLib and does not have access of those magics. You can copy its code and compile it in your library.

**Comment by tannergooding** [comment]
A `BigFraction` type is one of those types that sounds good on paper, but doesn't tend to work well in practice.

Integers in particular have a lot of limitations and well-defined behavior that make their general computation and growth relatively trivial to understand. Most of this stems from division being well-defined and having a truncating (round towards zero) behavior. But as soon as you start trying to represent some sort of fractional data, this breaks down because the growth of an operation like `1 / 3` is infinite. You can try to normalize some of this with a `BigRational` type that tracks a `BigInteger Numerator` and `BigInteger Denominator`, but that itself runs into several efficiency problems and other considerations around operations that cannot be trivial represented (needing to represent `pi`, `inf`, `nan`, etc; so you can do trig, sqrt, and other common calculations correctly). The same applies to if you try to use some `BigFixedPoint` type instead.

Instead, the "right" approach to these scenarios tends to work a bit differently where instead of allowing arbitrary growth you instead define it in terms of explicit growth by the user instead. Which is to say you specify each created value has a target bitwidth and operations use the bitwidth of the largest input to determine the target precision of the output.

Defining such a type might happen eventually, but it is out of scope for the near future. It is also typically not needed, with the cases where it's used tending to be ones where developers are working in niche scenarios, or not properly handling their existing float/double values and accounting for their operating domain. We're much more likely to explicitly get a `Float128` and the `Decimal32/64/128` types that IEEE 754 defines first.
