### ISSUE TITLE
.net 8.0.1 but reports  8.0.0 on arm 32

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/runtime#97250]
### Description

Wrong version reported? running locally it displays 8.0.1

but deployed it still shows  8.0.0 built with vs preview.

local machine is **win x64** deployed is **arm 32**

deploy settings so the runtime is included... so the version should be 8.0.1
![image](https://github.com/dotnet/runtime/assets/1920090/d94ed788-96fb-468a-bb75-b9f26e964064)

### Reproduction Steps

deploy 8.0.1 code to arm and see the reported version back 

### Expected behavior

its should say 8.0.1 but says 8.0.0

### Actual behavior

says 8.0.0 instead of 8.0.1

**Comment by vitek-karas** [comment]
Where do you get the version from? Some API call, file, ... ?

**Comment by Seabizkit** [comment]
environment.version

**Comment by jkotas** [comment]
The version comes from version attribute on System.Private.CoreLib.dll.

I am not able to reproduce what you are seeing.

When you publish self-contained app, the runtime version included in the app matches the .NET SDK version used for publishing. I think the behavior that you are seeing is most likely caused by .NET SDK 8.0.100 used when publishing your app. .NET SDK 8.0.100 comes with .NET runtime 8.0.0.

Do you happen to have global.json that pins .NET SDK to 8.0.100 in your application? 

What does `dotnet --info` display - do you see .NET SDK 8.0.101 installed?

**Comment by Seabizkit** [comment]
![image](https://github.com/dotnet/runtime/assets/1920090/1c6cf4c6-2585-49c9-864b-676f41550f2f)

when i run the project locally, the machine is win x64 it displays correctly

**Comment by jkotas** [comment]
You have 8.0.200-preview SDK installed that is older than 8.0.1 runtime. This SDK has the highest version, and it is going to be used by default when building your application. This SDK is going to include 8.0.0 runtime in your self-contained application.

If you `dotnet run` your application locally, it is going to use 8.0.1 shared runtime.

Any of the following should fix the mismatch that you are observing:
- Uninstall 8.0.200-preview SDK
- Install latest preview SDK
- Lock your build to 8.0.101 using global.json, to avoid using preview SDK

**Comment by jkotas** [comment]
If you are using preview SDKs, it is a good idea to keep upgrading the preview SDK frequently to avoid issues like this one.

**Comment by Seabizkit** [comment]
closing , i can confirm it worked with none preview... so it was like the preview version wasnot updated anyway... i have since updated to the latest preview and now this time it includes it which it normally does.... which is why i was confused.

reporting 8.0.2 made with 17 10 preview 1
