### ISSUE TITLE
[API Proposal]: Add `ThrowIfEmpty(Guid)` method to ArgumentException

### ISSUE THREAD

**Issue by carzaza** [dotnet/runtime#97279]
### Background and motivation

This class already implements a method for strings. It is very common to check if an input Guid is Empty and consider it as an error.

By this reason, and motivated by the addition of the method for strings (and also in `ArgumentNullException` class), I think it can be an interesting feature to add.

The issue can be assigned to me.

### API Proposal

```csharp
public static void ThrowIfEmpty(Guid argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
{
    if (argument == Guid.Empty)
    {
        throw new ArgumentException("The value cannot be an empty Guid.", paramName);
    }
}
```

### API Usage

```csharp
Guid anyId = ...;

ArgumentException.ThrowIfEmpty(anyId);
```

**Comment by danmoseley** [comment]
I don't think this is common enough to be worth adding, especially as it can trivially be done in app code.

**Comment by stephentoub** [comment]
There's already ThrowIfEqual. You can use that with Guid.Empty.

**Comment by carzaza** [comment]
> I don't think this is common enough to be worth adding, especially as it can trivially be done in app code.

In fact, I currently have it supported in my own app code. The point of this proposal is to homogenize `ArgumentNullException` and other `ArgumentException` methods. Currently, I can:
```csharp
ArgumentException.ThrowIfNullOrEmpty(anyString);
```
but I cannot do the same for Guid :-/


> There's already ThrowIfEqual. You can use that with Guid.Empty.
> 
> ```cs
> ArgumentOutOfRangeException.ThrowIfEqual(anyId, Guid.Empty)
> ```

Is a Guid Empty an out of range value? It can be interpreted in different ways. Some people would say it is not, this is because I am proposing an `ArgumentException`. For example, in this repo there are many examples of this check, and an `ArgumentException` is thrown.

**Comment by stephentoub** [comment]
> Is a Guid Empty an out of range value? It can be interpreted in different ways. Some people would say it is not, this is why I am proposing an ArgumentException.

ArgumentOutOfRangeException derives from ArgumentException, so every one of the former is a latter.

> For example, in this repo there are many examples of this check, and an ArgumentException is thrown.

Yes, but all but one of them include a descriptive error message about that specific use case. We wouldn't switch them to such a helper even if it existed, which is also why we didn't switch them to use ThrowIfEqual.

> Currently, I can `ArgumentException.ThrowIfNullOrEmpty(anyString)` but I cannot do the same for Guid

Yes, because ThrowIfNullOrEmpty is needed by a very broad set of code bases and very frequently. It's used hundreds of times in this repo alone, for example.

> In fact, I currently have it supported in my own app code

Which is of course totally fine. That doesn't mean it needs to be added to the core libraries. There are always going to be special-cases in a particular library that aren't supported by the one-liners we provide helpers for, and for such cases, the trusty "if (condition) throw new XxException(...)" exists and does the job.  We can't possibly include a helper for every specific case.

I don't see us adding such a method.  You're obviously welcome to use `ArgumentOutOfRangeException.ThrowIfEqual(guid, Guid.Empty)` if it meets your needs, and if it doesn't, you can obviously continue to use your own helper or just use if/throw.

Regardless, thank you for the suggestion.
