### ISSUE TITLE
in C# Round 256.3665,3,MidpointRounding.AwayFromZero 

### ISSUE THREAD

**Issue by FarooqAlhaboub** [dotnet/runtime#97287]
### Description

when rounding 256.3665 for 3 decimal and using midpoint away from zero its giving wrong output = 256.366.
but rounding 255.3665 for 3 decimal and using midpoint away from zero  = 255.367.

### Reproduction Steps

//C# Code
using System;

public class HelloWorld
{
    public static void Main(string[] args)
    {
        
        Console.WriteLine ("round 346.3665 = "+ Math.Round(346.3665,3,MidpointRounding.AwayFromZero));        
        Console.WriteLine ("round 257.3665 = "+ Math.Round(257.3665,3,MidpointRounding.AwayFromZero));        
        Console.WriteLine ("round 256.3665 = "+ Math.Round(256.3665,3,MidpointRounding.AwayFromZero));        
        Console.WriteLine ("round 255.3665 = "+ Math.Round(255.3665,3,MidpointRounding.AwayFromZero));
    }
}

### Expected behavior

round 346.3665 = 346.367
round 257.3665 = 257.367
round 256.3665 = 256.367
round 255.3665 = 255.367

### Actual behavior

round 346.3665 = 346.367
round 257.3665 = 257.366
round 256.3665 = 256.366
round 255.3665 = 255.367

### Regression?

rounding is coming different depends on the non decimal value sometime (between 256-261)

### Known Workarounds

for this one we can do Round(256.3665*1000,MidpointRounding.AwayFromZero)/1000 
but only for this case I don't know where it might come again

**Comment by FarooqAlhaboub** [comment]
resolve is to put (m) at the end of the number (to decimal number)
Console.WriteLine ("round 346.3665 = "+ Math.Round(346.3665m,3,MidpointRounding.AwayFromZero));        
Console.WriteLine ("round 257.3665 = "+ Math.Round(257.3665m,3,MidpointRounding.AwayFromZero));        
Console.WriteLine ("round 256.3665 = "+ Math.Round(256.3665m,3,MidpointRounding.AwayFromZero));        
Console.WriteLine ("round 255.3665 = "+ Math.Round(255.3665m,3,MidpointRounding.AwayFromZero));

**Comment by huoyaoyuan** [comment]
The current algorithm for `MidpointRounding.AwayFromZero` is `(value * 1Edigits + BitDecrement(0.5)) / 1Edigits`.
Though there's decimal-binary rounding issues, the bit patterns for the fractional parts are the same. `Round` should give consistent result for them.

**Comment by tannergooding** [comment]
@FarooqAlhaboub, the issue here is that the literals you typed, such as `346.3665`, are `double` which is a `base-2 floating-point number` and is therefore represented using multiples of powers of `2`.

As such, the actual values represented aren't exactly what you typed but are instead:
```
346.3665 = 346.3664999999999736246536485850811004638671875
257.3665 = 257.3664999999999736246536485850811004638671875
256.3665 = 256.3664999999999736246536485850811004638671875
255.3665 = 255.366500000000002046363078989088535308837890625
```

In particular you'll note that 256, 257, and 346 all have the same fractional value of `0.3664999999999736246536485850811004638671875` because they exist within the same power of 2 window (`>= 2^8 && < 2^9`). While 255 has a different because it exists within a separate window (`>= 2^7 && < 2^8`).

Given this, none of the values are actually `midpoints` at the 4th decimal digit and are instead either just above or just below the cutoff. `346.3665` notably should be returning `346.366` instead, but the algorithm being used is inexect because its currently scaling the input by a power of 10 first which allows additional imprecision to be introduced and can cause the result to be off by 1ULP (instead it should be working directly with the fractional portion to avoid such issues and producing a result that is off by 0.5ULP, which is the infinitely correct result rounded to the nearest representable result).

------------

The reason using `346.3665m` works is because it is using `decimal` which is a `base-10 floating-point number` and is therefore represented using multiples of powers of `10`. This allows `346.3665` to be exactly represented and therefore introduces no additional rounding error, but it comes at the cost of the code executing much more slowly.

The decision for perf or computing exact results is entirely dependent on the workload and domain in question.
