### ISSUE TITLE
The type loader has silent integer overflows

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#97412]
From:  https://github.com/dotnet/runtime/issues/95193#issuecomment-1885347542

These silent integer overflows are present in handling of LayoutKind.Sequential as well. For example, this:

```cs
Console.WriteLine(sizeof(X));

struct X
{
   byte x;
   BigArray a;
}

[StructLayout(LayoutKind.Sequential, Size = int.MaxValue)] 
struct BigArray
{
}
```

prints -2147483648.

**Comment by MichalStrehovsky** [comment]
Is this really an integer overflow in the type loader? Spec for the IL sizeof instruction says the result is unsigned int32. The code generated by Roslyn treats it like it was signed so it gets formatted as signed but it wasn't.

The signedness of the value disappears on the IL evaluation stack so it's not bad IL, but still kind of wrong.

Cc @jaredpar

**Comment by jaredpar** [comment]
> Spec for the IL sizeof instruction says the result is unsigned int32

The spec for C# says it's a signed int. 🤷

That decision was so long ago, hard to say why the two disagreed here. Wonder if that was due to CLS compliance and wanting to avoid unsigned types in the language. That's just speculation. But either way, it's very explicit in the language that it's done this way.

**Comment by jkotas** [comment]
I agree that the runtime is following the IL spec and the problem is technically in C#. I think we should make the runtime fit C# that is our primary user experience.
