### ISSUE TITLE
[API Proposal]: Add constants RadiansPerDegree, DegreesInCircle, and (optionally) DegreesPerRadian to System.Math.

### ISSUE THREAD

**Issue by CodeSetting** [dotnet/runtime#97611]
### Background and motivation

`System.Math` contains many trigonometric functions, most of which accept an argument in units of radians.  Whereas, most user interfaces communicate these values in units of degrees.  The math for converting between these two units is quite simple and well-known.  It would be helpful if the following two constants were added to `System.Math`  to facilitate this conversion: `RadiansPerDegree` and `DegreesInCircle`.

Optionally, to avoid division during conversions, the addition of a third constant `DegreesPerRadian` might also be nice.

### API Proposal

```csharp
namespace System;

public static partial class Math
{
  public const int DegreesInCircle = 360;

  public const double RadiansPerDegree = Math.PI / 180D;

  // Optionally to avoid divisions during conversions from radians to degrees
  public const double DegreesPerRadian = 180D / Math.PI;
}
```

### API Usage

```csharp
// Normalizing a user-provided number of degrees
int userDegrees = 365;
int normalDegrees = userDegrees % Math.DegreesInCircle;
if (normalDegrees < 0)
  normalDegrees += Math.DegreesInCircle;

// Converting degrees to radians (for trigonometric function parameters)
double degrees = 45D;
double radians = degrees * Math.RadiansPerDegree;
double result = Math.Cos(radians);

// Converting radians to degrees (for trigonometric results)
degrees = result / Math.RadiansPerDegree;

// Optional (to avoid the above division)
degrees = result * Math.DegreesPerRadian;
```

### Alternative Designs

One alternative design might be to add the following two new methods:

```
double DegreesToRadians(double degrees);
double RadiansToDegrees(double radians);
```

Since the math, in either case, is a single multiplication/division, the addition of the two proposed constants seems a simpler (and slightly less risky) approach.

### Risks

There is a minimal risk that users might misunderstand the purpose of these constants. However, this can be mitigated with half-decent documentation.

There is a small, but more significant risk that this might create a "slippery slope" for adding a slew of other mathematical constants. However, with appropriate restraint, this risk can also be mitigated. Simply asking the following question, should be a good litmus test: "Does the new constant make it easier to use one or more of the pre-existing methods?" Given the large number of trigonometric functions currently present in `System.Math`, I believe the answer to this question, for these proposed constants, is "Yes".

**Comment by tannergooding** [comment]
We already exposed `T.DegreesToRadians(x)` and `T.RadiansToDegrees(x)` in .NET 8. This is available to any type implementing `System.Numerics.ITrigonometricFunctions<TSelf>` which at a minimum includes `float`, `double`, and `Half`.

It was an explicit design decision to not expose constants due to the issues they can introduce from rounding error. The exposed methods will still constant fold for `float`/`double` and produce a JIT constant given a constant input.

**Comment by tannergooding** [comment]
It's also worth noting that since .NET 7 with the introduction of `Generic Math` (https://learn.microsoft.com/en-us/dotnet/standard/generics/math), `System.Math` and `System.MathF` are no longer being versioned and are effectively frozen.

All new math APIs are being exposed directly on the given type instead. Thus, `float.Sin(x)`, `float.Hypot(x, y)`, or `double.DegreesToRadians(x)` are the preferred way to access these APIs and the only place to access new APIs exposed moving forward.

This was done for many reasons, including to avoid silent breaks in overload resolution, to be more consistent with how non-primitive types expose their equivalent functionality, to allow the APIs to be accessible via constrained generic contexts (such as `where T : ITrigonometricFunctions<T>` or `where T : IFloatingPointIeee754<T>`), etc.

**Comment by CodeSetting** [comment]
@tannergooding Thank you for the information and for closing the issue. I was aware of the generic interfaces that were added for numerics and the support for basic math functions (e.g. addition, multiplication, etc.). I somehow missed that more advanced math functions, like trigonometry, were also added as static methods. This is very interesting. It is also somewhat amusing that they chose the same method names as I proposed :)
