### ISSUE TITLE
IPv6 uri with leading zeros makes it IPv4 look like

### ISSUE THREAD

**Issue by MrFishchev** [dotnet/runtime#97719]
### Description
I'm not sure if it's a bug or not, but when I create Uri instance with IPv6 (e.g. `https://[::b1c2:ef3]/path`) it goes to IPv4 style (e.g. `https://[::177.194.14.243]/path`) which will not work and looks not 

```
var url = new Uri("https://[::b1c2:ef3]/path");
// url.AbsoluteUri -> https://[::177.194.14.243]/path
// url.Host -> [::177.194.14.243]
```

### Configuration
.NET 6

### Other information
I didn't check with a newer version of .NET, I just want to understand if it's a bug or known begavior

**Comment by colejohnson66** [comment]
I would say this is a bug. Don't IPv6 addresses need to be `::ffff:aabb:ccdd` in order to be equivalent to (the IPv4) `[0x]aa.bb.cc.dd`? Interpreting `::aabb:ccdd` as `[0x]aa.bb.cc.dd` would be wrong.

**Comment by MihaZupan** [comment]
This appears to be intentional
https://github.com/dotnet/runtime/blob/cfd909200f1c564f75ae7dcd8ac10d53949b26c2/src/libraries/Common/src/System/Net/IPv6AddressHelper.Common.cs#L41-L62

https://github.com/dotnet/runtime/blob/cfd909200f1c564f75ae7dcd8ac10d53949b26c2/src/libraries/System.Net.Primitives/tests/FunctionalTests/IPAddressParsing.cs#L413

**Comment by MrFishchev** [comment]
Thanks @MihaZupan, I don't know details but seems to be the correct logic.
