### ISSUE TITLE
System.Security.Cryptography.OpenSsl 5.0.0 DLL for net461 targets .NET Framework 4.7

### ISSUE THREAD

**Issue by mvanhilst-msft** [dotnet/runtime#97728]
### Description

System.Security.Cryptography.OpenSsl 5.0.0 DLL for net461 targets .NET Framework 4.7.

> "C:\Users\user\.nuget\packages\system.security.cryptography.openssl\5.0.0\ref\net461\System.Security.Cryptography.OpenSsl.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.2".

![image](https://github.com/dotnet/runtime/assets/136656465/d5ba5af0-3518-4634-9478-b2f2538b0a57)

### Reproduction Steps

Create a new .NET Framework 4.6.2 project and add a PackageReference to System.Security.Cryptography.OpenSsl 5.0.0.

### Expected behavior

No warnings.

### Actual behavior

> "C:\Users\user\.nuget\packages\system.security.cryptography.openssl\5.0.0\ref\net461\System.Security.Cryptography.OpenSsl.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.2".

### Regression?

This is a regression from version 4.7.0 of the package, where there was no net461 DLL, only netstandard2.0.

This problem still exists in 6.0.0-preview.3.21201.4.

**Comment by teo-tsirpanis** [comment]
This package is no longer actively maintained. Its assembly that targets .NET Framework contains dummy methods that throw `PlatformNotSupportedException`. If you target .NET 6+ these types are built-in to the shared framework, and if you target .NET Framework you should use the regular cryptography APIs instead (using OpenSSL on .NET Framework is pointless since it runs only on Windows and has access to Windows cryptography APIs).

**Comment by mvanhilst-msft** [comment]
> This package is no longer actively maintained. Its assembly that targets .NET Framework contains dummy methods that throw `PlatformNotSupportedException`. If you target .NET 6+ these types are built-in to the shared framework, and if you target .NET Framework you should use the regular cryptography APIs instead (using OpenSSL on .NET Framework is pointless since it runs only on Windows and has access to Windows cryptography APIs).

Understood, though inconvenient. Anyone on .NET 4.6.2 using a package with a dependency on System.Security.Cryptography.OpenSsl 5.0.0 (such as [Microsoft.VisualStudio.Services.Client](https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/19.232.0-preview#dependencies-body-tab)) will receive this warning. Given that .NET 4.6.2 is LTS, we will have to deal with this warning for years to come.

Would you suggest I file a bug against Microsoft.VisualStudio.Services.Client and ask them to multi-target .NET Framework to explicitly remove the dependency on System.Security.Cryptography.OpenSsl 5.0.0 for .NET Framework?

**Comment by teo-tsirpanis** [comment]
I took a look at the metadata of the assemblies of `Microsoft.VisualStudio.Services.Client`, and realized that the `System.Security.Cryptography.OpenSsl` assembly is actually not referenced and the dependency to the NuGet package can simply be removed.

Beyond that, I also recommend you to tell the packages' maintainers to multi-target the package to .NET 6 or 8, which will enable to remove the dependencies to the following packages:

* `Microsoft.Win32.Registry`
* `System.Memory`
* `System.Security.AccessControl` (built-in since .NET 7)
* `System.Security.Cryptography.Cng` (maybe this is unused as well; you can ask them to try removing it and see if building does not fail)
* `System.Security.Cryptography.OpenSsl` (remove this even from .NET Standard 2.0, it is unused)
* `System.Security.Cryptography.Pkcs`
* `System.Security.Cryptography.ProtectedData`
* `System.Security.Principal.Windows`
* `System.ServiceModel.Primitives`
* `System.ServiceProcess.ServiceController` (>= 6.0.1)
* `System.Xml.XPath.XmlDocument` (remove this even from .NET Standard 2.0, it brings tons of unnecessary transitive dependencies)
