### ISSUE TITLE
Unable to configure host environment from a JSON settings file when using Host.CreateApplicationBuilder

### ISSUE THREAD

**Issue by f2bo** [dotnet/runtime#97930]
I've recently been experimenting with the .NET Generic Host. According to the [docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host?tabs=appbuilder#host-configuration), the code shown in that section can be used to load the host configuration from a JSON file. The article describes two different approaches, namely using `IHostApplicationBuilder` and `IHostBuilder`. Unfortunately, I don't seem to be able to make the former work as described.
 
For example, given the following `hostsettings.json` file and code that uses `CreateApplicationBuilder`:

**hostsettings.json**
```json
{
    "applicationName": "MyApp",
    "environment": "QA"
}
```

```C#
HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);
builder.Configuration.AddJsonFile("hostsettings.json", optional: true);

using IHost host = builder.Build();

IHostEnvironment hostEnvironment = host.Services.GetRequiredService<IHostEnvironment>();
Console.WriteLine($"EnvironmentName: {hostEnvironment.EnvironmentName}");
Console.WriteLine($"ApplicationName: {hostEnvironment.ApplicationName}");
Console.WriteLine($"IsQAEnvironment: {hostEnvironment.IsEnvironment("QA")}");
...
```

I would expect the following to be output:
```
EnvironmentName: QA
ApplicationName: MyApp
IsQAEnvironment: True
```

Instead, it shows the following: (TestApp is the name of the .exe)

```
EnvironmentName: Production
ApplicationName: TestApp
IsQAEnvironment: False
```

If I use the `IHostBuilder` approach instead, the host configuration is loaded correctly and I see the expected output.

``` C#
IHostBuilder builder = Host.CreateDefaultBuilder(args);
builder.ConfigureHostConfiguration(config => config.AddJsonFile("hostsettings.json", optional: true));

using IHost host = builder.Build();

IHostEnvironment hostEnvironment = host.Services.GetRequiredService<IHostEnvironment>();
Console.WriteLine($"EnvironmentName: {hostEnvironment.EnvironmentName}");
Console.WriteLine($"ApplicationName: {hostEnvironment.ApplicationName}");
Console.WriteLine($"IsQAEnvironment: {hostEnvironment.IsEnvironment("QA")}");
...
```

**Comment by Clockwork-Muse** [comment]
You don't actually need to explicitly list and load a file for `CreateApplicationBuilder()`, there's a configuration package that can be injected that (usually automatically) loads a chain of configuration sources, including specifically-named json files and environment variables (among other things).

[See this section on configuration in .Net](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration#alternative-hosting-approach).

**Comment by f2bo** [comment]
> loads a chain of configuration sources, including specifically-named json files and environment variables (among other things).

The documentation you linked refers to app configuration. For host configuration, the code example in the generic host documentation specifically suggests loading it from a `hostsettings.json` file and, as I mentioned, I'm unable to make that code work when using `CreateApplicationBuilder`. In contrast, the host configuration can be loaded from the same JSON file when using `CreateDefaultBuilder` so if that difference was intended, it would seem that the docs are incorrect.

[See this section on host configuration](https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host?tabs=appbuilder#host-configuration)

**Comment by steveharter** [comment]
Either the doc is incorrect\old or this is a bug. Adding to 9.0 for evaluation.

Note that the values can be obtained outside of `IHostEnvironment`:
```cs
Console.WriteLine($"EnvironmentName: {builder.Configuration["EnvironmentName"]}");
Console.WriteLine($"ApplicationName: {builder.Configuration["ApplicationName"]}");

// or

IConfiguration hostConfig = host.Services.GetRequiredService<IConfiguration>();
Console.WriteLine($"EnvironmentName: {hostConfig["EnvironmentName"]}");
Console.WriteLine($"ApplicationName: {hostConfig["ApplicationName"]}");
```

**Comment by f2bo** [comment]
I can't say whether it's a bug or if the behavior of `Host.CreateApplicationBuilder()` was never intended to be the same as the one provided by `Host.CreateDefaultBuilder()` in this regard, but if that's the case then the docs certainly need to be updated.

> Note that the values can be obtained outside of IHostEnvironment:
>
>Console.WriteLine($"EnvironmentName: {builder.Configuration["EnvironmentName"]}");
>Console.WriteLine($"ApplicationName: {builder.Configuration["ApplicationName"]}");
>
>// or
>
>IConfiguration hostConfig = host.Services.GetRequiredService<IConfiguration>();
>Console.WriteLine($"EnvironmentName: {hostConfig["EnvironmentName"]}");
>Console.WriteLine($"ApplicationName: {hostConfig["ApplicationName"]}");

That doesn't seem to be equivalent as it's returning the value from the app's configuration settings which were initialized from the `hostsettings.json` file. However, any service relying on `IHostEnvironment` to determine its environment might observe a different value. For example:

``` C#
IHostEnvironment hostEnvironment = host.Services.GetRequiredService<IHostEnvironment>();
IConfiguration hostConfig = host.Services.GetRequiredService<IConfiguration>();

// using "Environment" instead of "EnvironmentName" as the name of the configuration setting 
// because that's the name expected by IHostBuilder
Console.WriteLine($"From IConfiguration: {hostConfig["Environment"]}"); // * 
Console.WriteLine($"From IHostEnvironment: {hostEnvironment.EnvironmentName}");
```
Running the code above displays:
```
From IConfiguration: QA
From IHostEnvironment: Production
```

or if you previously set the `DOTNET_ENVIRONMENT` variable to, for example, "Staging":

```
From IConfiguration: QA
From IHostEnvironment: Staging
```

**Comment by MagnusMikkelsen** [comment]
The issue seems to be that HostApplicationBuilder initializes host configuration already on construction.
The constructor [calls Initialize](https://github.com/dotnet/runtime/blob/c57f9aebb290fe7b626c6799c1b55aa7cf646497/src/libraries/Microsoft.Extensions.Hosting/src/HostApplicationBuilder.cs#L99), which [builds the HostingEnvironment](https://github.com/dotnet/runtime/blob/c57f9aebb290fe7b626c6799c1b55aa7cf646497/src/libraries/Microsoft.Extensions.Hosting/src/HostApplicationBuilder.cs#L164).

In contrast `HostBuilder` doesn't apply host configuration until [`.Build` is called.](https://github.com/dotnet/runtime/blob/c57f9aebb290fe7b626c6799c1b55aa7cf646497/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L161)

The workaround I've used in one app is reading hostsettings.json manually and use it to create the HostApplicationBuilderSettings. But it isn't quite as neat as the .AddJsonFile way.

**Comment by koenigst** [comment]
@buyaa-n My analysis shows that the real issue is that `HostBuilder` clearly separates host configuration and app configuration while `HostApplicationBuilder` uses the same `ConfigurationManager` for both.

I would make a PR with the following:
* Renaming the `HostApplicationBuilderSettings.Configuration` to `HostConfiguration` and marking the old property obsolete.
* Include the host configuration in the app configuration analogous to how [`HostBuilder` does](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L281).
* Update the documentation of the `Configuration` properties to reflect this logic change.

This is a breaking change in the case when the `HostApplicationBuilder.Configuration` property is used to configure the host behaviour instead of the application behaviour.

**Comment by koenigst** [comment]
> We should spend time making this nicer.

```lang=csharp
var settings = new HostApplicationBuilderSettings { Configuration = new(), };
settings.Configuration.AddJsonFile("hostsettings.json", optional: true);

var builder = Host.CreateApplicationBuilder(settings);
using var host = builder.Build();
```

This is as nice as it is possible at the moment.

It would be an option to create `Configuration` in the `HostApplicationBuilderSettings` ctor as it is created anyway in the `HostApplicationBuilder` ctor. This would mean we could make `Configuration` non-nullable but this again is a breaking change.
