### ISSUE TITLE
It looks like now all objects support IAgileObject interface, regression to .NET Framework

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [dotnet/runtime#98071]
Hi

I'm porting .NET Framework desktop application to .NET 6 and there is a native code that checks if interface supports `IAgileObject` interface and do something special. And that code stopped working correctly because all interfaces that come from .NET now support `IAgileObject`. It wasn't the case for .NET Framework.

I found that in some .NET code from year 2015 in file `comcallablewrapper.cpp` in function `IUnknown* SimpleComCallWrapper::QIStandardInterface(REFIID riid) `looks like this:

```cpp
    CASE_IID_INLINE(  enum_IAgileObject            ,0x94ea2b94,0xe9cc,0x49e0,0xc0,0xff,0xee,0x64,0xca,0x8f,0x5b,0x90)
        {
            // Don't implement IAgileObject if we are aggregated, if we are in a non AppX process, if the object explicitly implements IMarshal,
            // or if its ICustomQI returns Failed or Handled for IID_IMarshal (compat).
            // ... 
            if (!IsAggregated() 
#if !defined(FEATURE_CORECLR)
            && AppX::IsAppXProcess()
#endif // !defined(FEATURE_CORECLR)
            )
```

but now it looks like this:

```cpp
    CASE_IID_INLINE(  enum_IAgileObject            ,0x94ea2b94,0xe9cc,0x49e0,0xc0,0xff,0xee,0x64,0xca,0x8f,0x5b,0x90)
        {
            // Don't implement IAgileObject if we are aggregated, if the object explicitly implements IMarshal, or if its ICustomQI returns
            // Failed or Handled for IID_IMarshal (compat).
            if (!IsAggregated())
```

It is not a problem for me because none of our .NET objects implements `IAgileObject` anyway so I can check if object is come from .NET and then exclude it but I wonder if this oversight because from comment in old code it looks like interfaces in desktop app are not supposed to support `IAgileObject` because it is "**not non AppX process**".

**Comment by AaronRobinsonMSFT** [comment]
Hi @vladimir-cheverdyuk-altium. The [`IAgileObject` interface](https://learn.microsoft.com/windows/win32/api/objidlbase/nn-objidlbase-iagileobject) has nothing to do with AppX process detected or at least it shoudn't. The `IAgileObject` simply means it is free threaded. It was introduced in the Windows 8 timeframe for use in some UWP scenarios so there is some connection but it should not be used as an indication of AppX. It is used to indicate a free threaded object.

Technically all .NET objects are free threaded in COM and UWP environments and so all CCWs can have that interface. The interface in general should be thought of as a "falsey" indication of free threaded. Meaning if a QI for `IAgileObject` succeeds, it is definitely free threaded, but if it doesn't it may still be free threaded.

This is by design.
