### ISSUE TITLE
Replacement for the obsolete ObjectIDGenerator

### ISSUE THREAD

**Issue by gdoron** [dotnet/runtime#98168]
Hi,

Following the [announcement](https://github.com/dotnet/docs/issues/34893) of obsoleting `BinaryFormatter`, `ObjectIDGenerator` got also obsolete.
I searched quite a while, but I couldn't find any replacing API for it, is there one?
How do we get a reference ID for an object in .NET 8?

**Comment by gdoron** [comment]
@CyrusNajmabadi thanks for the prompt reply!
I checked the [source code](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/runtime/serialization/objectidgenerator.cs) of it, maybe I'm missing something, but I do not see anything that uses the risky `BinaryFormatter`, why is it obsolete and pending removal?

**Comment by CyrusNajmabadi** [comment]
Because it exists for that use case and that whole space is being removed.  As mentioned, it's trivial to use a different system, so that makes the removal process extremely easy

**Comment by gdoron** [comment]
Well it wasn't an internal API with a warning to use on your own risk.
So people could use and did use it.

I personally would have not removed it just because the internal runtime usage of it is no longer needed.
It's a helpful utility class, that now everyone in the community would need to implement on its own.

**Comment by stephentoub** [comment]
cc: @GrabYourPitchforks

**Comment by gdoron** [comment]
@stephentoub Do you expect it to come back, or do we need to implement it ourselves?

**Comment by stephentoub** [comment]
@GrabYourPitchforks would need to speak to whether ObjectIdGenerator goes away with BinaryFormatter, but the functionality is also trivially implemented with a simple class like this:
```C#
internal sealed class IdGenerator
{
    private readonly Dictionary<object, long> _ids = new Dictionary<object, long>(ReferenceEqualityComparer.Instance);

    public long GetId(object obj, out bool firstTime)
    {
        ArgumentNullException.ThrowIfNull(obj);
        ref long id = ref CollectionsMarshal.GetValueRefOrAddDefault(_ids, obj, out bool exists);
        firstTime = !exists;
        if (firstTime) id = _ids.Count;
        return id;
    }
}
```

**Comment by IS4Code** [comment]
@CyrusNajmabadi 
> Because it exists for that use case and that whole space is being removed. As mentioned, it's trivial to use a different system, so that makes the removal process extremely easy

I dare to disagree with this notion. It may have been created to be used alongside other classes in `System.Runtime.Serialization`, but it has obviously surpassed its purpose as it's being used by people for various reasons unrelated to serialization.

There is no sense in telling people "use something else" when this one works, does not use any dangerous/obsolete features by itself, and, most importantly, is *standardized* for this purpose. By the same logic, you should remove many other types from .NET, such as [`System.CodeDom.Compiler.IndentedTextWriter`](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.indentedtextwriter) since `System.CodeDom` was surpassed by Roslyn, or [`System.Drawing.Color`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.color) as, of course, `System.Drawing` is Windows-only.

It's marked obsolete just because it happened to be put in a wrong namespace, but namespaces are not atomic code units and are just for association, not containment. Thus arguing with "that whole space is being removed" is just begging the question.

----

That being said (and I assume the type is not actually going away like the `BinaryFormatter`), I agree the type needs to be marked in *some* way, just not as strongly as being obsolete. The programmer needs to be informed and decide whether a two-way, non-synchronized mapping really is sufficient and not too much, for example in my case all that I needed was this:
```cs
static long nextObjectId;
static readonly ConditionalWeakTable<object, object> objectIds = new();
static readonly ConditionalWeakTable<object, object>.CreateValueCallback valueCallback = _ => Interlocked.Increment(ref nextObjectId);
```
All that is needed is to shift from "don't use it, find something else" to "it is okay to use this, but try to find other solutions first".

**Comment by jeffhandley** [comment]
@bartonjs This issue is included in the tracking issue for BinaryFormatter efforts and needs to be considered as part of our final removals of usage

**Comment by bartonjs** [comment]
When removing BinaryFormatter for 9, we decided that the only thing we were going to hollow out ("remove") was `BinaryFormatter` itself, all the supporting types stayed as-were.

ObjectIDGenerator didn't really need to be marked as Obsolete, but removing the attribute is... unusual.

I don't think there's really much value (or a sensible place/way) in documenting "this class is obsolete, but it's fine to keep using, though it's easily replaced with [10 lines of code](https://github.com/dotnet/runtime/issues/98168#issuecomment-1964328902)... or, depending on what you need... [less](https://github.com/dotnet/runtime/issues/98168#issuecomment-2022450827)"
