### ISSUE TITLE
Ambiguous constructors exception

### ISSUE THREAD

**Issue by Uriil** [dotnet/runtime#98228]
### Description

I have a service with two constructors, first constructor with one parameter and second with two. According to [documentation](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#multiple-constructor-discovery-rules) DI should select the one with the most parameters, however it throws exception "The following constructors are ambiguous" and pastes both constructors

### Reproduction Steps

```
namespace WebApplication4
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.

            builder.Services.AddControllers();
            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();

            builder.Services.AddScoped<ITest1, Test1>();
            builder.Services.AddScoped<ITest2, Test2>();
            builder.Services.AddScoped<ITest3, Test3>();
            builder.Services.AddScoped<MyMainClass>();

            var myClass = builder.Services.BuildServiceProvider().GetService<MyMainClass>();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseHttpsRedirection();

            app.UseAuthorization();


            app.MapControllers();

            app.Run();
        }
    }

    public interface ITest1
    {

    }

    public interface ITest2
    {

    }

    public interface ITest3
    {

    }

    public class Test1 : ITest1
    {

    }

    public class Test2 : ITest2
    {

    }

    public class Test3 : ITest3
    {

    }

    public class MyMainClass
    {
        public MyMainClass(ITest1 test) { }
        public MyMainClass(ITest2 test2, ITest3 test3) { }
    }
}
```

If I change `MyMainClass(ITest2 test2, ITest3 test3) { }` to `MyMainClass(ITest1 test1, ITest3 test3) { }` (first parameter type, so second constructor extends first one) it will work.

### Expected behavior

Instance of MyMainClass should be created

### Actual behavior

Exception is thrown:

Unable to activate type 'WebApplication4.MyMainClass'. The following constructors are ambiguous:
Void .ctor(WebApplication4.ITest2, WebApplication4.ITest3)
Void .ctor(WebApplication4.ITest1)

### Known Workarounds

Explicitly define constructor to be used

### Configuration

.NET8, tried on two different machines

**Comment by allantargino** [comment]
It is ambiguous because all types are resolvable **and** there is no overlapping arguments. That's expected and documented as a unit test (even though I agree it is not clear in the documentation):

https://github.com/dotnet/runtime/blob/3e9cce64d25dc95a2509952b33f3eded6041c47c/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceLookup/CallSiteFactoryTest.cs#L709-L728

Although that behavior can be changed to consider what you are expecting (resolving that ambiguity by selecting the constructor with the greatest number of parameters), I agree with the current implementation. It prevents me to couple my class behavior with the DI container behavior. You could fix your code by:

```cs
    public class MyMainClass
    {
        public MyMainClass(ITest1 test) { }
        public MyMainClass(ITest2 test2, ITest3 test3) { }
        public MyMainClass(ITest1 test, ITest2 test2, ITest3 test3) { }
    }
```

Which actually express a real possibility in your solution: all parameters are available.

**Comment by Uriil** [comment]
I agree with you statement and that's proper behavior, was confused by documentation.
