### ISSUE TITLE
[API Proposal]: Extend IMemoryCache to also provide keys/provider info

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#98251]
### Background and motivation

I like what has been done with #36554 however for me it is not enough to be able to implement an actuator to provide information about the cache as done in spring boot.

I would like the method to be available as part of the interface so that i have a consistent way to get the keys and the metadata regardless of the provider.

### API Proposal

Interface extension
```csharp
namespace System.Collections.Generic;

IEnumerable<CacheItem> GetCacheItems => new IEnumerable<CacheItem>();
```

new class
```csharp
public class CacheItem
{
    public string ProviderName
    public string StorageType
    public object Key
}
```

### API Usage

```csharp

foreach (var item in _memoryCache.GetCacheItems.ToList())
{
    //build object as per actuator needs which includes 
}
```

### Alternative Designs

- Default implementation throws a not implemented exception

### Risks

Should be low risk as not a breaking change by providing default implementation.

**Comment by Jozkee** [comment]
Is CacheItem a view of a CacheEntry? What's ProviderName and StorageType? Can you be more specific about the [extension method](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) you are proposing here? In which static type will it live?

**Comment by julealgon** [comment]
@thompson-tomo if you want to know what happens with the `IMemoryCache` object, why don't you just create a simple decorator for it that intercepts the calls and stores the information you need before/after each method is executed?

From your description, introspection on the calls (and callbacks) should be enough to be able to provide a "view" of the cache.

Also, instead of viewing the entire state of the cache, I believe it would be better to have metrics around the cache so that you could graph them in observability tools.
