### ISSUE TITLE
Regex.Match(string input, int startat) method fails to give expected result when startat is larger than 0

### ISSUE THREAD

**Issue by oysteinsor** [dotnet/runtime#98282]
### Description

class Regex ( System.Text.RegularExpressions ) in c# 8.
Method:  Match Match( string input, int startat )

Fails to match if startat parameter is larger than 0. 

### Reproduction Steps

string input1  = " abc  stest";
string input2 = "abc stest";
Regex regex = new Regex(@"^abc");

Match m1 = regex.Match( input1 , 1 );
Console.WriteLine(m1.Success); // this fails, even success is expected
Match m2 = regex.Match( input2 , 0 );
Console.WriteLine(m2.Success); // this succeeded

### Expected behavior

I expect to get a match on position 1 with the pattern "^abc" in the example above. since the input string has abc at position 1.

### Actual behavior

it fails me every time.

### Regression?

I do not remember. It may be an issue in more versions.

### Known Workarounds

/* easiest workaround is to use the function:

Match Match( string input, int startat, int length ).
This behaves as expected, always. 

*/
string input1  = " abc  stest";
string input2 = "abc stest";
Regex regex = new Regex(@"^abc");

Match m1 = regex.Match( input1 , 1 );
Console.WriteLine(m1.Success); // fails this is the problem described in this case.
Match m2 = regex.Match( input2 , 0 );
Console.WriteLine(m2.Success); // succeeds

// workaround:
Match m3 = regex.Match(input1, 1, input1.Length - 1 );
Console.WriteLine(m3.Success); // succeeds , yes. 

Match m4 = regex.Match(input2, 0, input2.Length - 0 );
Console.WriteLine(m4.Success); // succeeds

### Configuration

Use windows 11 professional, latest.
x64 architecture

### Other information

https://referencesource.microsoft.com/#System/regex/system/text/regularexpressions/Regex.cs

I can see that the startat parameter is used differently, and also named differently in the two instances. And in the first here, the beginning is set to 0, so that is why I believe it fails when I use the first of these two methods.

![image](https://github.com/dotnet/runtime/assets/18237004/f0e6bc08-66f6-4faa-ba2e-f38fe6b5de83)

**Comment by danmoseley** [comment]
Hi there, it could probably be better documented, but this isn't a regression and it's by design.

The `string,int` overload has the int parameter `starttat` documented as `The zero-based character position at which to start the search.` whereas `string,int,int` overload documents the first int parameter `beginning` as `The zero-based character position in the input string that defines the leftmost position to be searched.`

What this is trying to say in the first case is that it's using the string as supplied, but starting at an offset into the string, as if it had already scanned from the start of the string. That fails to match in this case as the `^` fails to match as it's one character into the string, rather than at the start. That's why it's called `startat`.

The second case is pretending the string begins at that position - that's why it's called `beginning`. Effectively (and actually) it's creating a `ReadOnlySpan<char>` internally starting at that point. So the earlier chars are invisible, and `^` matches successfully.

It's always been this way - and that's why the parameter names are different - but you're welcome to offer a PR to tweak the docs for clarity if you'd like, here: https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text.RegularExpressions/Regex.xml

**Comment by stephentoub** [comment]
This is expected. startat and beginning are not the same thing. startat doesn't change what is considered the beginning of the input, which impacts constructs like anchors that match against a specific input location.

**Comment by danmoseley** [comment]
as an aside -- in github issues, you can make the code you type easier to read and colorized like this
```C#
static void Main() {...}
```
by putting a fence around it, which you type like this
````
```c#
static void Main() {...}
```
````

**Comment by danmoseley** [comment]
Looking at the docs, it does explain it for `string,int,int` : see Remarks of https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.match?view=net-8.0#system-text-regularexpressions-regex-match(system-string-system-int32-system-int32)

But for `string,int` it links to an explanation: see Remarks of https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.match?view=net-8.0#system-text-regularexpressions-regex-match(system-string-system-int32).

I'm not sure why in the latter case it isn't directly in the topic -- if there are no other links to it, I suggest moving that part of the linked topic into the main topic directly.

**Comment by oysteinsor** [comment]
the place that document this behaviour best is at the page:
https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-text-regularexpressions-regex-match
in the section about the startat parameter.

The basic documentation about the function should in some way tell this,
because it is not very clear the difference between beginning and startat.

So that is the place where I actually understood the documentation. But I
did not find it until today.

_______________

Med vennlig hilsen
Øystein Søreide
