### ISSUE TITLE
System.IO.Packaging.InternalRelationshipCollection.GetRelationshipIndex doesn't scale

### ISSUE THREAD

**Issue by mabrahamsen** [dotnet/runtime#983]
**Use case**
The Microsoft OpenXml SDK relies on the System.IO.Packaging API to generate Microsoft Excel files. This allows adding hyperlinks to Excel columns, but with the current resource consumption this is impossible when you have an excel sheet with about 100.000 records that each has a link to some additional record information - for instance a deep link to a HTTP resource. This API uses PackagePart.CreateRelationship inside the System.IO.Packaging stack.

**Background**
When adding hyperlinks to Excel cells, you have to call AddHyperlinkRelationship on the OpenXmlContainer. This will then follow the stack in System.IO.Packaging:
PackagePart.CreateRelationship -> InternalRelationshipCollection.Add -> InternalRelationshipCollection.ValidateUniqueRelationshipId -> InternalRelationshipCollection.GetRelationshipIndex.

**Problem**
ValidateUniqueRelationshipId  will call GetRelationshipIndex to ensure that the relationship id is unique, and it loops through all the links each time it is invoked. As the identifier list grows it will (obviously) become exponentially slower. Backing this identifier store by something similar to a HashSet would greatly improve the lookup time.

**Comment by danmosemsft** [comment]
@carlossanlop  would we accept a PR here?

**Comment by carlossanlop** [comment]
Thank you for bringing this to our attention, @danmosemsft.

Here are my notes about this request:

- Anyone consuming [InternalRelationshipCollection](https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/InternalRelationshipCollection.cs,28) may depend on the list-like behavior of the `IEnumerable` interface, so we cannot just change the interface without a better understanding of the consequences.
- HashSets typically inherit from `ISet` and/or `IReadOnlySet` (`ISet` would be the appropriate interface for this particular case, since it needs to be modified). The `InternalRelationshipCollection` class implements `IEnumerable<PackageRelationship>`. Changing the interface to `ISet` would mean implementing all the APIs of this new interface, and removing the ones from `IEnumerable`, as well as the calls to those APIs, which would be problematic.
- We have a class that implements both `IEnumerable` and `ISet`: [System.Collections.Generic.SortedSet](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1?view=netcore-3.1), which may be able to solve this issue, but we would still need an investigation on any unexpected consequences of adding the extra functionality from this class. Keep in mind that `SortedSet` implements many interfaces which would have to be implemented: `ICollection<T>`, `IEnumerable<T>`, `IReadOnlyCollection<T>`, `ISet<T>`, `ICollection`, `IEnumerable`, `IDeserializationCallback` `ISerializable`.
- The name of the `InternalRelationshipCollection` would probably need to be changed to something more appropriate, since it would not be just a collection anymore.
- Seems that the `WindowsBase` project is duplicating or depending on the code of `System.IO.Packaging`, and putting inside its own namespace, `MS.Internal.IO.Packaging` (see [source.dot.net](https://source.dot.net/#q=InternalRelationshipCollection)). We need to understand the relationship of these two. If there's a dependency, then we would probably be affecting an even larger set of APIs that depend on `InternalRelationshipCollection`.

@mabrahamsen, a couple of requests for you:

- Would you be interested in addressing the above questions, and if the proposed fix seems feasible, work on a PR?
- Can you please share a code snippet to test your use case?

**Comment by mabrahamsen** [comment]
Hi @carlossanlop,

I have extracted a simple sample and attached hit here. This will generate an Excel sheet using the Microsoft OpenXML SDK, and I have code with or without the hyperlink. You will see how the hyperlink version doesn't scale if you change the rowcounts. With the current rowcount a profiler will show you that about 98% of the time is sued calling InternalRelationshipCollection.Add, to add a hyperlink per row.

[WorksheetWriter.zip](https://github.com/dotnet/runtime/files/4109999/WorksheetWriter.zip)

Also, when I mentioned the HashSet, it was more to point towards a collection lookup strategy to avoid doing all the loops over the internal list. Not that I recommended changing the type itself to inherit from IDictionary<TKey, TValue> or ISet<T>. I suspect that in additional to maintaining the IEumerable<T> implementation, some clients might expect the collection to keep the sequence provided by the List<T> implementation. One could partner the List with a HashSet to help with the Add uniqueness validation, but as the list supports index lookup (which could be solved with Dictionary) and Delete (which would require something similar to a Lazy HashSet/Dictionary rebuild) it becomes slightly more complicated.

I don’t have any good suggestions for a solution strategy at this point. As InternalRelationshipCollection is internal one would need to analyze its call-sites to better understand what it is really used for, and perhaps one could replace the type altogether.

I will try and get some time to come up with a possible solution, and then I guess a pull request would be possible. My concern is that I need a much better understanding of the codebase to see how this can be implemented with a reliable performance profile. I have only used this API indirectly through the Microsoft OpenXML SDK, and I have no clue what other uses it might have.

**Comment by twsouthwick** [comment]
Here's a benchmark test to repro it:

```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using System;
using System.IO;
using System.IO.Packaging;

namespace SystemIOBenchmarks
{
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    [MemoryDiagnoser]
    public class BenchmarkClass
    {
        [Params(10, 100, 1000, 10000)]
        public int N;



        [Benchmark]
        public Stream AddRelationships()
        {
            using (var ms = new MemoryStream())
            using (var package = Package.Open(ms, FileMode.Create))
            {
                for (int i = 0; i < N; i++)
                {
                    package.CreateRelationship(new Uri("http://localhost"), TargetMode.External, "RelationshipType");
                }

                return ms;
            }
        }
    }
}
```
