### ISSUE TITLE
[API Proposal]: Add missing BigMul overload for uint x uint -> ulong

### ISSUE THREAD

**Issue by lilinus** [dotnet/runtime#98346]
### Background and motivation

Many of the integer types available for other operations are missing for Math.BigMul

### API Proposal

```csharp
namespace System;

public static class Math
{
    public static Int128 BigMul(long a, long b);
    public static ulong BigMul(uint a, uint b);
    public static UInt128 BigMul(ulong a, ulong b);
}

public readonly struct Int32
{
    public static long BigMul(int a, int b);
}

public readonly struct Int64
{
    public static Int128 BigMul(long a, long b);
}

public readonly struct UInt32
{
    public static ulong BigMul(uint a, uint b);
}

public readonly struct UInt64
{
    public static UInt128 BigMul(ulong a, ulong b);
}
```

### API Usage

```csharp
// Fancy the value
var x = uint.MaxValue;
var y = uint.MaxValue - 1;
var z = Math.BigMul(x, y);
```

### Alternative Designs

Only adding it to Uint32 class instead of Math. (BigMul doesnt exist on other concrete types yet, but can be taken in other api suggestion if relevant)

```csharp
namespace System;

public readonly struct UInt32
{
    public static ulong BigMul(uint a, uint b);
}
```

**Comment by huoyaoyuan** [comment]
In fact, there's no arithmetic operator defined for small integer types. They need to be upcasted to 32bit. The default operator already behaves as BigMul.

**Comment by lilinus** [comment]
Ah i see, the main one IMO that is missing is uint x uint -> ulong, suince we already have int x int -> long

**Comment by colejohnson66** [comment]
What's wrong with just using `(ulong)left * (ulong)right`? IMO, `long BigMul(int, int)` shouldn't exist.

**Comment by tannergooding** [comment]
> What's wrong with just using (ulong)left * (ulong)right? IMO, long BigMul(int, int) shouldn't exist.

It's not as clear and not as easy to take advantage of hardware specific optimizations, particularly on 32-bit platforms.

> Ah i see, the main one IMO that is missing is uint x uint -> ulong, suince we already have int x int -> long

We have this one internally, so if you update the proposal we can discuss exposing it.

Notably, we may want to discuss whether or not this should be `int.BigMul` and `uint.BigMul` instead, since generic math has effectively soft-obsoleted Math and new APIs were planned to be static methods on the concrete types instead.

**Comment by lilinus** [comment]
Updated suggestion accordingly @tannergooding

**Comment by MichalPetryka** [comment]
Should there be some new `IBigMultiplicable<TSelf, TResult>` for this?

**Comment by lilinus** [comment]
> Should there be some new `IBigMultiplicable<TSelf, TResult>` for this?

Sounds reasonable. Maybe `IBigMultiplicable<TSelf, TOther, TResult>` so it is more aligned with e.g. `IMultiplyOperators<TSelf,TOther,TResult>`

Best to make separate api suggestion for that?

**Comment by bartonjs** [comment]
* The question was raised of why add these on the `Math` type, since we have previously said that the type is soft-deprecated.
  * The answer is "because they're overloading an existing member."
* There was a brief question about the applicability to generic math, but since that requires `(TSelf, TBigger)` or `(TSelf, TSmaller)` that's too complicated, so this finite set is all we get.
* We'll leave the ones on Math as `(a, b)` to match the current method, but the ones on each type will use the more globally-consistent `(left, right)` naming.
* There's no real need to do this for (s)byte -> (~u)short, or (u)short -> (u)int.

```c#
namespace System;

public static partial class Math
{
    public static Int128 BigMul(long a, long b);
    public static ulong BigMul(uint a, uint b);
    public static UInt128 BigMul(ulong a, ulong b);
}

public readonly partial struct Int32
{
    public static long BigMul(int left, int right);
}

public readonly partial struct Int64
{
    public static Int128 BigMul(long left, long right);
}

public readonly partial struct UInt32
{
    public static ulong BigMul(uint left, uint right);
}

public readonly partial struct UInt64
{
    public static UInt128 BigMul(ulong a, ulong right);
}
```
