### ISSUE TITLE
The handling of NaN in TensorPrimitives.Max() is inconsistent with Enumerable.Max()

### ISSUE THREAD

**Issue by aalmada** [dotnet/runtime#98367]
### Description

In the `System.Numerics.Tensors` library, both the `Min()` and `Max()` aggregation operations utilize the same `MinMaxCore` iteration code. While this behavior aligns with LINQ's `Enumerable.Min()`, it differs from `Enumerable.Max()`.

### Reproduction Steps

Run the following:

```csharp
using System;
using System.Linq;
using System.Numerics.Tensors;

float[] array = [1.0f, float.NaN, 2.0f];
Console.WriteLine($"LINQ Min: {array.Min()}");
Console.WriteLine($"LINQ Max: {array.Max()}");
Console.WriteLine($"Tensors Min: {TensorPrimitives.Min(array)}");
Console.WriteLine($"Tensors Max: {TensorPrimitives.Max(array)}");
```

### Expected behavior

```
LINQ Min: NaN
LINQ Max: 2
Tensors Min: NaN
Tensors Max: 2
```

### Actual behavior

```
LINQ Min: NaN
LINQ Max: 2
Tensors Min: NaN
Tensors Max: NaN
```

`TensorPrimitive.Max()` return `NaN` instead of the expected `2`.

### Configuration

.NET 8
System.Numerics.Tensors 8.0.0
The executed code is platform-agnostic and not tied to any specific operating system or architecture.

**Comment by tannergooding** [comment]
This is "by design".

`Enumerable` handles things according to `IComparable` which treats `NaN` as less than everything. However, IEEE 754 defines a particular behavior for `Max`/`Min` which is that it always propagates the `NaN` value. There then exists `MaxNumber`/`MinNumber` which never propagate the `NaN`.

`Math/MathF`, `IFloatingPointIeee754<T>`, and now `TensorPrimitives` all follow the IEEE 754 requirements as they are explicitly operating on numerical data, not general enumerables.

**Comment by tannergooding** [comment]
If this were being designed today, I'd likely have had `float`/`double` implement `IComparable` using the IEEE 754 "total order" concept (this is available in .NET 8+ via `System.Numerics.TotalOrderIeee754Comparer<T>`)

Outside of that, it's too late to "fix" `IEnumerable` and the difference here remains sensible given the differing domains.

**Comment by aalmada** [comment]
Good to know. Sorry for the confusion and thank you for the explanation.
