### ISSUE TITLE
Large Memory Consumption in Docker Causing OOM

### ISSUE THREAD

**Issue by maganuk** [dotnet/runtime#98524]
### Description

We upgraded all our microservices from .NET 7 to 8 and deployed them to Kubernetes. Ever since the upgrade, we can see really high consumptions by the containers, to the point where running our E2E tests is causing the containers to be evicted due to high memory consumption. We have allocated 512MB to each of the containers and there has been almost no change to our codebase since we migrated to .NET8. These were working absolutely fine in .NET7.

We mainly use GRPC, MassTransit and MongoDB in all our services. Initially we thought that this may be caused by an OCSP Stapling issue which was floating around, but that was fixed in 8.0.2, we didn't see any change in the consumption after updating to 8.0.2

### Reproduction Steps

Upgrade application from .NET 7 to .NET8 using the 8.0.2 runtime-deps image in docker.

### Expected behavior

Consistent memory consumption (lower or comparable to .NET7)

### Actual behavior

Unmanaged growth of memory causing the container to be OOMed and evicted.

### Regression?

.NET 7 was fine.

**Comment by Steve887** [comment]
I am having the same issue. Was waiting for 8.0.2 to see if #95922 was fixed, and still seeing OOM kills pretty quickly, along with large unmanaged memory usage. I was able to pull a dotmemory dump from my app and it has a gig of unmanaged memory with about 100 mb of allocated memory. This is just after the app restarted after a crash too.
![image](https://github.com/dotnet/runtime/assets/129719/690fff9a-c46e-43c6-8c46-f248cebb6047)

**Comment by janvorli** [comment]
@Steve887 can you please open your dump in WinDbg on Windows or using dotnet-dump analyze and run the following commands like I've suggested to someone else in the other issue? That would give us some basic idea on where the native memory is coming from (if running in WinDbg, please use `!dumpheap` instead of `dumpheap`:
```
dumpheap -type Microsoft.Win32.SafeHandles.SafeX509Handle -live -stat
dumpheap -type Microsoft.Win32.SafeHandles.SafeBioHandle -live -stat
dumpheap -type System.Reflection.RuntimeAssembly -live -stat
```

**Comment by jdlegan** [comment]
We are experiencing the same symptoms. I have pulled dotnet-dumps and dotnet-gcdumps for the past week trying to isolate the leak and came across the issue for which this one was opened at the conclusion of a few days back. Would you like me to provide the output of all of the requested commands in this issue or open a separate one?

**Comment by danmoseley** [comment]
Putting them in a gist and linking would work.

**Comment by Steve887** [comment]
@janvorli dump info below. Let me know if there's any other commands you want me to run, or if there's a better format for this.
I'm not super knowledgeable about how to analyze this, but nothing here seems to stand out to me. Although my dump file size is over 1 gig.

![image](https://github.com/dotnet/runtime/assets/129719/53af6b6c-83dc-45cf-95db-25ae3565f4be)

**Comment by janvorli** [comment]
@Steve887 looking at the info you've dumped, based on the number of RuntimeAssembly instances, I am almost sure that the problem is due to dynamic assemblies that are not collectible (unloadable). There are some libraries that use them, like xml serialization. When a dynamic assembly is created without the `RunAndCollect` option, it stays in memory forever. 
You can check what keeps those `RuntimeAssembly` instances alive using the `gcroot` command of the dotnet-dump analyze for some of the instances of the runtime assembly. You'd run `dumpheap -type System.Reflection.RuntimeAssembly -live` to dump all of the instance addresses and then run the `gcroot` on some of those addresses. In WinDbg, it would be a bit easier as you'd be able to script it to run the command on all of the instances so that you don't need to manually get a random sample.

**Comment by tl-luca-mazzanti** [comment]
Hi we are facing on multiple dotnet services hosted on k8s the same issue probably after moving on NET 7/8.
We have aspnet processes working heavily with HttpClients using mTLS certificates with their own CA chain.
We saw a huge degradation on CPU and memory moving to NET 8 probably some changes related to openssl.

I collected the same use case with dotMemory where we have **2-4Gb of memory for 30-50Mb of managed memory everything else is unmanaged**. I dumped some process and searched for the same handles like the X509 but I can't see huge numbers or memory retained. Still I can send you more details anyway.

We are on `mcr.microsoft.com/dotnet/sdk:8.0.201-bookworm-slim` so every patch related is yet applied.
I tried to force the old GC with `DOTNET_GCName=libclrgc.so` but this didn't changed the weird behavior.

This worked fine: `<ServerGarbageCollection>false</ServerGarbageCollection>`and the memory unmanaged did not completely disappear but now processes are stable to 300 Mb, a good compromise.

Anyway I would like to understand better why and how this work cause this is just a temporary patch on the project.
Is the environment missing some information and opting for a bad choice or this is only a way to have a more impacting GC collect but the issue is still open on your side?

**Comment by maganuk** [comment]
@tl-luca-mazzanti I think there are two distinct issues here. 

The certificate issue that you are encountering is most likely related to the new docker images and the way the runtime handles openssl 3. I'm presuming that in the process of upgrading to .NET 8 you also changed images from bullseye to bookworm. In this transition the openssl on linux has been updated from v1 to v3. There is known issue in openssl that causes performance degradation. We're working with certificate chains and mTLS too and can see latency of almost 5-10 times than usual. In fact, a simple conversion of a PEM to a certificate, which usually takes less than 1ms on windows and on linux bullseye is taking about 70ms on bookworm. There has been a patch recently somewhere in the DotNet runtime, but we will only see that in the next patch release in march.

The memory issue on docker seems unrelated and still unresolved.

**Comment by denislohachev1991** [comment]
Hello everyone, I faced the same problem. My application runs on Linux under the Ubuntu distribution with the Kestrel server. After switching from Windows to Linux, I noticed that the application consumes a lot of memory over time. Here is a dump made using DotMemory.
![DotMemorypng](https://github.com/dotnet/runtime/assets/44192808/1491f7f9-5f2e-42cc-945d-5318a6c02f0a)
I'm very surprised that 3.66 GB is unmanaged memory and only 70 MB is managed memory. When the application ran on Windows under IIS, the application consumed an average of 150 MB of memory.I made a dump of the running application using dotnet-dump, after which I opened it in WinDbg and did as Janvorli wrote https://github.com/dotnet/runtime/issues/98524#issuecomment-1948072208 here are the results that I got.
![WinDbgStat](https://github.com/dotnet/runtime/assets/44192808/0ceaaa9e-a855-4ea5-b421-ae2770224eb3)
Then I executed the command .foreach ($obj {!dumpheap -type System.Reflection.RuntimeAssembly -live -short}){.echo $obj; !gcroot $obj} as described in https://github.com/dotnet/runtime/issues/98524#issuecomment-1959140368 the result of running the command below
[RuntimeAssembly.txt](https://github.com/dotnet/runtime/files/14419631/RuntimeAssembly.txt)
I noticed a message that is repeated quite often, but I'm very bad at dump research and don't know if it matters.
7f9c12d5ec58
HandleTable:
    00007f9ff18413a0 (strong handle)
          -> 7f9bb2805ff8     System.Object[] 
          -> 7f9c12d5ec58     System.Reflection.RuntimeAssembly 

Found 1 unique roots.
7f9c12e4d1f0
Found 0 unique roots.
7f9c12e78548
HandleTable:
    00007f9ff18413a0 (strong handle)
          -> 7f9bb2805ff8     System.Object[] 
          -> 7f9c12e78548     System.Reflection.RuntimeAssembly 

Found 1 unique roots.
I'm stuck and can't figure out what to do next, maybe you have any ideas?

**Comment by jcauv4** [comment]
Same issue for me. Upgraded to .NET 8 from 7 (no other significant changes) and saw a massive spike in memory usage. Using linux containers in AKS.

**Comment by janvorli** [comment]
@denislohachev1991 thank you for the log, I'll go through it. When the gcroot report only a strong handle referencing an object array that references the assembly and no other roots, it means that the assembly object is not accessible to any of the managed code and is effectively just eating memory. It is a bit simplified claim, there can still be code running in it, but it is sufficient for determining whether a memory consumption is coming from the problem with non-collectible assemblies in case there are many of such cases. The reference chains that are of other form would then indicate what could have created and abandoned such assemblies. I can see two major cases in your dump. One is coming from ASPNet.Core and the other from Microsoft.CSharp.RuntimeBinder. But I need to look into it in more detail and check the source of the classes that hold those references to see how they work with the assemblies.

**Comment by denislohachev1991** [comment]
Thank @janvorli  you for your time. If you need anything else let me know.

**Comment by janvorli** [comment]
@denislohachev1991 one thing that would be great to check is to see how / if the number of live RuntimeAssembly instances grows over time. So taking a dump at two different times in the lifetime when you observe the memory growth and run the `!dumpheap -type System.Reflection.RuntimeAssembly -live -stat` to see the numbers.

**Comment by mnebes** [comment]
Possibly related: https://github.com/dotnet/runtime/issues/99046

**Comment by denislohachev1991** [comment]
@janvorli  I just made a dump of an application that worked for a short time after the restart. The command !dumpheap -type System.Reflection.RuntimeAssembly -live -stat showed these results:

0:000> .load sos
0:000> !dumpheap -type System.Reflection.RuntimeAssembly -live -stat
Calculating live objects, this may take a while...
Caching GC roots, this may take a while.
Subsequent runs of this command will be faster.

Calculating live objects complete: 286,992 objects from 206 roots
Statistics:
          MT Count TotalSize Class Name
7f6ffc819400     8       768 System.Reflection.RuntimeAssembly+ManifestResourceStream
7f6ff838c520   164     7,872 System.Reflection.RuntimeAssembly
Total 172 objects, 8,640 bytes

I'll wait until my memory grows, repeat everything again and provide the results. But this may take a long time.

**Comment by denislohachev1991** [comment]
After the application started using 1.5 GB of memory, I took a dump and ran everything again. Here's the result:

0:000> .load sos
0:000> !dumpheap -type System.Reflection.RuntimeAssembly -live -stat
Calculating live objects, this may take a while...
Caching GC roots, this may take a while.
Subsequent runs of this command will be faster.

Calculating live objects complete: 522,578 objects from 255 roots
Statistics:
          MT Count TotalSize Class Name
7f6ffc819400    12     1,152 System.Reflection.RuntimeAssembly+ManifestResourceStream
7f6ff838c520   173     8,304 System.Reflection.RuntimeAssembly
Total 185 objects, 9,456 bytes

**Comment by janvorli** [comment]
Thank you @denislohachev1991, so it seems that the number of runtime assemblies has grown insignificantly, so it is probably not the culprit. Can you please share the output of the `!maddress`  windbg command on a dump when significant amount of memory is allocated? Please feel free to delete any filenames that you don't want others to see, they don't play any role in the analysis.

**Comment by denislohachev1991** [comment]
@janvorli  For some reason the !maddress command doesn't work for me. WinDbg writes: No export maddress found.
I don’t know if this is correct, but I used the !address command, and here is the result:
[address.txt](https://github.com/dotnet/runtime/files/14459241/address.txt)

**Comment by denislohachev1991** [comment]
@janvorli  If necessary I can provide 2 dumps. One was made when the application consumed quite a bit of memory, the other when memory consumption increased to ~1.5 GB.

**Comment by denislohachev1991** [comment]
Thank you @kevingosse  . I used !ext maddress, here is the result:
[maddress.txt](https://github.com/dotnet/runtime/files/14464776/maddress.txt)

**Comment by cr0fters** [comment]
Just a question to anyone still facing this issue - have you tried switching to the latest Alpine based docker image (as opposed to Debian based) to see if you're still getting the issue?

Today I've switched to using `8.0-alpine` and so far memory consumption appears to have gone back to normal.

**Comment by Kiechlus** [comment]
Yep, we face the same issue using `8.0-alpine`.

**Comment by maganuk** [comment]
@janvorli can I provide you with any other information to resolve this issue? Once traffic hits them, most of our pods are getting evicted in kubernetes. I was hoping the 8.0.3 docker images would resolve the issue, but it hasn't

**Comment by denislohachev1991** [comment]
I still can't solve the problem with high memory consumption. Here are the GC settings we are using:
{
  "configProperties": {
    "System.GC.Server": true,
    "System.GC.DynamicAdaptationMode": 1,
    "System.GC.ConserveMemory":7,
    "System.GC.HighMemoryPercent": 75,
    "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
    "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
  }
}
With these parameters, memory consumption decreased quite slightly, and consumption is still high.

**Comment by ioerrors** [comment]
In a k8s environment, since you are sharing node resources with other pods, do we want to use workstation GC instead of Sever GC?

This info may be outdated though?
https://devblogs.microsoft.com/dotnet/running-with-server-gc-in-a-small-container-scenario-part-0/
https://devblogs.microsoft.com/dotnet/running-with-server-gc-in-a-small-container-scenario-part-1-hard-limit-for-the-gc-heap/

**Comment by denislohachev1991** [comment]
Hello @Maoni0  , could you provide me with an email or other way so that I can send you a link to the dumps?

**Comment by Maoni0** [comment]
@denislohachev1991, certainly, my email alias is maonis and the domain is microsoft.com.

**Comment by cshung** [comment]
To collect a trace for a dotnet process running under the Kubernetes environment, the recommended solution is to use `dotnet-monitor`. This assume you have access to changing your `deployment.yaml`.

The high level idea is that `dotnet-monitor` is a RESTful service that allows you to issue HTTP requests to collect traces (and perform other monitoring activities). To do that, it must be ran as a side-car container to your process of interest, and we need to make some environment variable changes so that your process of interest is aware of the existence of `dotnet-monitor`.

[Here](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md) is a sample `deployment.yaml` from the official documentation.

> Be aware that the sample explicitly turned off authentication just for simplicity, you might want to make sure you have the proper level of security as you need.

Much of the `spec/template/spec/name: monitor` and `spec/template/spec/volume` part can simply be copied (unless you happen to have a name conflict that you need to change).

Note specifically that you need to modify the `app` part with the `DOTNET_DiagnosticPorts` and the `volumeMounts` so that the dotnet process is aware of the existence of `dotnet-monitor`.

Also note that the documentation does not expose the port for connection, you will want to be able to access it. If you could get into the monitor container (e.g. `kubectl ssh`), you can get into it an issue the HTTP request there. Otherwise you need to expose the port `52323` to make it accessible 

> Again, beware of security of exposing a port.

With the setup ready, we can now issue requests to collect traces. 

`dotnet-monitor` does not come with a client, we just simply issue HTTP requests using `curl`, for example, you can collect a GCCollect only profile using this request.

```bash
curl --header "Content-Type: application/json"   --request POST   --data '{ "Providers": [{ "Name": "Microsoft-Windows-DotNETRuntime", "EventLevel": "Informational", "Keywords": "0x1" },{ "Name": "Microsoft-Windows-DotNETRuntimePrivate", "EventLevel": "Informational", "Keywords": "0x1" }], "BufferSizeInMB": 1024}' http://localhost:52323/trace?durationSeconds=20 -o trace.nettrace
```

> In our trace collection lingo, you specify what you want to log through a list of 3 tuples, provider means the source of the trace data, level means the verbosity and keyword is a bitmask for selecting relevant events. These particular settings mean we want to have some basic information about what happened with the GC (keyword = 1 is GC) and we only want information events (i.e. not verbose)

This particular setup is meant for the simplest scenario. We understand real life deployments are complicated, let us know if you have particular setup that you would like to get it to work but these instructions are not sufficient.

**Comment by Kiechlus** [comment]
Hi @Maoni0, at the moment we are happy so I don't know what to share with you :-) Maybe we find something over time. For collecting we spoofed our docker container (non-prod only):

````
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine # Use SDK and not Runtime to have dotnet tool command
...
RUN dotnet tool install --global dotnet-trace
RUN dotnet tool install --global dotnet-dump
RUN dotnet tool install --global dotnet-counters
ENV PATH="${PATH}:/root/.dotnet/tools"
````

We then used e.g. `dotnet-dump collect -p <pid>` to collect the trace and `kubectl cp ...` to get it to the local machine.

**Comment by maganuk** [comment]
This PR could potentially be addressing the issue: https://github.com/dotnet/runtime/pull/100502

**Comment by mangod9** [comment]
Hey @maganuk, can you please verify if https://github.com/dotnet/runtime/pull/100502 might solve your scenario too?

**Comment by maganuk** [comment]
Yes it does. Closing this. Thank you @mangod9

**Comment by dpalat** [comment]
hi @maganuk, at the end which is the solution? thanks

**Comment by maganuk** [comment]
@dpalat till the next release of the docker images (2nd Tuesday of May) you could try and set the DOTNET_GCgen0size environment variable to 1E00000

This worked for me
