### ISSUE TITLE
AOT之后的软件怎么暴漏一些参数给vmp软件,让vmp自动选择加密的函数

### ISSUE THREAD

**Issue by ByboyCn** [dotnet/runtime#98645]
AOT之后的软件怎么暴漏一些参数给vmp软件,让vmp自动选择加密的函数

**Comment by MichalStrehovsky** [comment]
Machine translated: "How can software after AOT leak some parameters to the vmp software so that vmp can automatically select encrypted functions?".

You'll have to be more specific in this question. We don't work on vmp software (VMProtect?). If this is a vmp question, it might be better to ask vmp developers.

**Comment by ByboyCn** [comment]
但是vmp的开发者让问dotnet的aot的开发者,之前开发的时候只需要在方法上加上类似于        [Obfuscation(Feature = "virtualization",Exclude = false)]
这样的特性就可以让vmp软件识别到了,但是我加上这个特性之后,aot编译后,没有效果

**Comment by MichalStrehovsky** [comment]
I think VMProtect authors need to learn about [native AOT compilation](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/). The output of native AOT compilation is a native binary, like if it was generated by any other native compiler. I assume the custom attribute approach only works when running code in the .NET virtual machine. There's no .NET virtual machine in native AOT, it needs to be obfuscated same as e.g. C++.
