### ISSUE TITLE
Incorrect CFI unwinding information in ARM64 assembly helpers

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#98738]
RhpNewObject, RhpNewArrayRare, RhyCallFinallyFunclet, RhpCallFilterFunclet, and RhpWaitForGC on ARM64 Unix appear to have wrong unwinding information that the latest libdwarf can no longer unwind.

When comparing to the x64 versions of these, we seem to be missing `.cfi_remember_state`/`.cfi_restore_state` around basic blocks with an exit.

Unfortunately, the lldb and gdb versions I tried didn't seem to mind and could unwind the stack from any of the instructions in `RhpNewObject` I tried so not sure what's the best way to test this. WinDbg runs into this.

**Comment by janvorli** [comment]
I agree that the `.cfi_remember_state`/`.cfi_restore_state` are needed there. Otherwise the `.cfi_restore` annotations that are in the POP_COOP_PINVOKE_FRAME (transitively) make the unwinder on the code following the POP_COOP_PINVOKE_FRAME use the state as if the function didn't return in between. The unwinder doesn't care about the code, just about the .cfi annotations.

The reason why lldb doesn't care is because it has multiple unwinding "plans" in addition to the one from the dwarf. So somehow its internal heuristic has probably figured out that the unwind info is incorrect and used e.g. one that it creates by analyzing the code.  You can view all the unwind plan lldb has for a given address using `image show-unwind -a <address>`

I guess gdb has something similar too.
