### ISSUE TITLE
Double.TryParse calculation result accuracy error in asp.net

### ISSUE THREAD

**Issue by r-V2** [dotnet/runtime#99145]
### Description

When I run the code: 
```
var number = "422.3262"; 
double.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out double value);
``` 
On the console program, the result is 422.3262. 
But when I run it on the asp.net program, the result is 422.32619999999997.

### Reproduction Steps

1. create a asp.net webforms project.
2. copy these code in code behind:
```
var number = "422.3262"; 
double.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out double value);
```
3. Debug code to check calculation result.

### Expected behavior

The results in the console application should be same with the calculation result in the asp.net webapp.

### Actual behavior

Calculation results in asp.net webapp are not accurate. 

### Known Workarounds

Call the `Math.Round Method` on the calculation result.

**Comment by tannergooding** [comment]
This is a formatting difference, not a value difference (and thus `Math.Round` doesn't fix this scenario, it may actually introduce different bugs).

`422.3262` is the shortest roundtrippable string of the exact underlying value `422.32619999999997162376530468463897705078125` (which has a bitwise representation of `0x407A_6538_1D7D_BF48`, as can be seen using `BitConverter.DoubleToUInt64Bits`). The ASP.NET result of `422.32619999999997` happens to be the equivalent of `422.4362.ToString("G17")` which is likely done to ensure correct roundtripping across a broad range of systems, some of which may incorrectly handle some shorter inputs. -- https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/ covers some of the improvements we made in .NET Core 3.0+ to ensure shortest roundtrippable strings and general IEEE 754 compliance. .NET Framework remains non-compliant due to backcompat as can various other non .NET languages/runtimes, depending on the version you interoperate with (the latest versions tend to have made similar fixes as .NET, but you can't strictly guarantee that you'll interoperate with such an updated system).
