### ISSUE TITLE
VB default ByVal marshalling behavior is actually VBByRefStr and it truncates MBCS input

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#9944]
VB defaults ByVal marshalling to VBByRefStr, which will truncate inputs that are MBCS.  Here is the repro:

Suppose there is a DLL contains a function which requires char* argument as below.

    void __stdcall func (char * pszText)
    {
        return;
    }

If you call this function via P/Invoke with multi-bytes character as below, the argument is corrupted.

    Declare Sub func Lib "CppDll" (ByVal text As String)
    Sub Main()

        Dim str As String = "あいうえお"
        Console.WriteLine(str)
        func(str)
        Console.WriteLine(str)

    End Sub

Instead of using the declaration above, any of the followings can avoid the corruption.

    Declare Sub func Lib "CppDll" (<MarshalAs(UnmanagedType.LPTStr)> ByVal text As String)
    Declare Sub func Lib "CppDll" (<MarshalAs(UnmanagedType.LPStr)> ByVal text As String)
    Declare Sub func Lib "CppDll" (<MarshalAs(UnmanagedType.BStr)> ByVal text As String)

Here is the analysis:
ByValStr marshaling concept is flawed when it comes to marshaling multi-byte characters, such as Japanese and Chinese. It marshales it out to native code correctly – allocating enough buffer and marshal it as ANSI characters. However, when it marshal the string back into native, it assumes the length of the string is the managed length of the string, which is 5 in this case. As you’ve already guessed by now, this will result in a partial string being read/convert into managed and you’ll see a truncation in the middle of the string. This is a bug in the CLR. 

Refer to 270066 for more details, moving to .NET Core due to the potential breaking nature of this request.

**Comment by AaronRobinsonMSFT** [comment]
Updated in repro in C#

```CSharp
public unsafe class Program
{
    static void PrintBytes(string str)
    {
        byte[] bytes = new byte[str.Length * sizeof(char)];
        System.Buffer.BlockCopy(str.ToCharArray(), 0, bytes, 0, bytes.Length);

        foreach (var b in bytes)
        {
            Console.Write($"{b:x} ");
        }
        Console.WriteLine();
    }

    [DllImport(@"NativeLibrary.dll")]
    extern static void Test2([MarshalAs(UnmanagedType.VBByRefStr)] ref string ff);
    static void Main(string[] args)
    {
        string ff = "あいうえお";

        PrintBytes(ff);
        Test2(ref ff);
        PrintBytes(ff);
    }
}
```

```C
extern "C" void Test(char* s)
{
    return;
}
```

Bad output:
```
42 30 44 30 46 30 48 30 4a 30
3f 0 3f 0 3f 0 3f 0 3f 0
```

**Comment by AaronRobinsonMSFT** [comment]
>Here is the analysis:
ByValStr marshaling concept is flawed when it comes to marshaling multi-byte characters, such as Japanese and Chinese. It marshales it out to native code correctly – allocating enough buffer and marshal it as ANSI characters. However, when it marshal the string back into native, it assumes the length of the string is the managed length of the string, which is 5 in this case. As you’ve already guessed by now, this will result in a partial string being read/convert into managed and you’ll see a truncation in the middle of the string. This is a bug in the CLR.

This underlying issue here isn't length but the lossy nature character encodings and some dubious logic.

1) The string comes into the marshaler as expected and is converted via `VBByValStrMarshaler::ConvertToNative()` into an ANSI string. This is the point where the mangling and data loss are occurring. The string length is computed using characters instead of bytes which results in a length of 5 and that is encoded in the returned string: `05 00 00 00 3F 3F 3F 3F 3F 00`.
https://github.com/dotnet/runtime/blob/8baf392aa16123ecf1c27bcf73d11d8b5b8dd3e3/src/coreclr/src/System.Private.CoreLib/src/System/StubHelpers.cs#L428-L467

2) The native function is called with the converted string from (1).

3) The string computed in (1) is then passed to `VBByValStrMarshaler::ConvertToManaged()` since it was a `ref` and we want to bring back any changes from the native call. However at this point we are converting the converted string (i.e. `05 00 00 00 3F 3F 3F 3F 3F 00`).
https://github.com/dotnet/runtime/blob/8baf392aa16123ecf1c27bcf73d11d8b5b8dd3e3/src/coreclr/src/System.Private.CoreLib/src/System/StubHelpers.cs#L469-L477

4) The converted string from (1), which was passed to (2), and then converted back in (3) is now passed back out as the `ref` dictates. The user then observes `3F 00 3F 00 3F 00 3F 00 3F 00 00 00` which is the converted string back into nonsense.

There are options here to fix this but I am dubious there is a lot of value in fixing this issue after so many years.

**Comment by AaronRobinsonMSFT** [comment]
@jeffschwMSFT @jkoritzinsky @elinor-fung Any thoughts here?
