### ISSUE TITLE
[iOS][non-icu] Clean up ICU related files from runtime pack

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/runtime#99521]
- [x] Clean up runtime packs- done by https://github.com/dotnet/runtime/pull/104443
- [x] Clean up xamarin repo to not include these files when HybridGlobalization is on- done by https://github.com/xamarin/xamarin-macios/pull/20830

Contributes to https://github.com/dotnet/runtime/issues/80689

**Comment by ivanpovazan** [comment]
In this work could you please also remove the dependency on `HybridGlobalization` property from NativeAOT:
https://github.com/dotnet/runtime/blob/2a72651144ccc127284a0e1aa8c78dd7705adcc1/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L144-L146

This affects users who are using NativeAOT iOS library mode.
If they don't set the property to `true` in their project files, it breaks their build because of missing references.

**Comment by mkhamoyan** [comment]
This was done by https://github.com/dotnet/runtime/pull/104443 and https://github.com/xamarin/xamarin-macios/pull/20830
