### ISSUE TITLE
[API Proposal]: Add MonthOnly type

### ISSUE THREAD

**Issue by esbenbjerre** [dotnet/runtime#99751]
### Background and motivation

I sometimes find myself using the `DateOnly` type for scenarios where all I need to know is the year and month. We can of course use `DateOnly(y, m, 1)` but it feels hacky to me. My suggestion is to add a `MonthOnly` type to better fit these scenarios. Note that the proposal is written in F# but I expect the real version would be written in C#.

### API Proposal

```fsharp
type MonthOnly(year: int, month: int) =

  static member FromDateOnly (dateOnly: DateOnly) = MonthOnly(dateOnly.Year, dateOnly.Month)

  static member Parse (s: string) = MonthOnly.FromDateOnly (DateOnly.Parse s)

  static member MinValue = MonthOnly.FromDateOnly DateOnly.MinValue

  static member MaxValue = MonthOnly.FromDateOnly DateOnly.MaxValue

  member __.Year = year

  member __.Month = month

  member __.ToDateOnly = DateOnly(year, month, 1)

  member __.AddYears (years: int) = MonthOnly.FromDateOnly (__.ToDateOnly.AddYears years)

  member __.AddMonths (months: int) = MonthOnly.FromDateOnly (__.ToDateOnly.AddMonths months)
```

### API Usage

```fsharp
MonthOnly(2024, 3)
```

**Comment by huoyaoyuan** [comment]
There's a natural difference around date and month. Because month has variable length, it requires more complex logic to do arithmetic for dates. In contrast, doing arithmetic for months *at month level* would only require simple math.

Thus, `DateOnly` can provide additional calculation support like addition and difference comparing to a tuple `(yyyy, mm, dd)`, but `MonthOnly` won't provide such benefit than a tuple `(yyyy, mm)`.

**Comment by esbenbjerre** [comment]
> Thus, `DateOnly` can provide additional calculation support like addition and difference comparing to a tuple `(yyyy, mm, dd)`, but `MonthOnly` won't provide much benefit than a tuple `(yyyy, mm)`.

I agree that it's *simpler* than handling dates but a tuple does not provide much context and does not handle e.g. `% 12`.

**Comment by Clockwork-Muse** [comment]
nit: probably should be called `YearMonthOnly`
