### ISSUE TITLE
Remove `--fuse-ld=` from Native AOT link argument

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#99912]
In https://github.com/dotnet/runtime/pull/85478 we came to the conclusion that we will inevitably have to support multiple linkers on the machine and we should not try too hard to prefer one linker over another. The current linker behavior prefers bfd and fails if it's not available.

We should instead just let the compiler use the default system linker.

**Comment by akoeplinger** [comment]
This causes linking to fail on cbl-mariner which doesn't ship bfd by default (reported by an internal user):

`dotnet publish -r linux-x64 --self-contained true -c Release <project>` results in

```
clang-12 : error : invalid linker name in argument '-fuse-ld=bfd'
```

**Comment by jkotas** [comment]
cc @am11

**Comment by am11** [comment]
> The current linker behavior prefers bfd and fails if it's not available.

There was a reason for it; see https://github.com/dotnet/runtime/pull/83558#issuecomment-1478970872. We needed to set explicit defaults and required users to specify when they wanted to use something other than what 99% of the linux builds use in real world because we have specific linker script when someone diverges from the norms. That was the idea behind `LinkerFlavor` option to make it easy to explain.

> invalid linker name in argument '-fuse-ld=bfd'

Current way is to use `<LinkerFlavor>lld</LinkerFlavor>` in those cases. We basically **need** to know which linker is in use, so if we really want automate it without hardcoded bfd, we need to use a more improved version of this logic: https://github.com/dotnet/runtime/blob/cbb30bd4fa74d460fb4f8be23d8da11b15f5321c/eng/native/configuretools.cmake#L80-L93 The first question to ask, why they are not using lld in CBL-mariner? There is no licensing issues here and I feel like it's just some big misunderstanding which lead folks to believe using lld, and going against every major linux distro choice, is somehow a "good" thing. llvm-project itself defaults to bfd on linux..

**Comment by MichalStrehovsky** [comment]
I agree with @am11 that doing this would complicate things by a lot, and all because a Microsoft-internal distro wants to be weird. More detection logic is just going to mean more bugs. The `invalid linker name in argument '-fuse-ld=bfd'` is a lot easier to troubleshoot than whatever new failure modes a detection logic would bring. I'm not sure we'd really want to go there.

**Comment by agocke** [comment]
Ah, my mistake, I forgot that other linkers do not work in all cases. Then we probably shouldn't let defaults flow through.

> Current way is to use <LinkerFlavor>lld</LinkerFlavor> in those cases.

The problem here is that bfd was not installed, and the fix wasn't clear from the linker error.

> The first question to ask, why they are using lld in CBL-mariner?

Probably because it just isn't installed when you install clang, but not binutils.

**Comment by agocke** [comment]
Closing this for now. If this becomes more common I think we should re-consider better detection and a better error message.
